### ISSUE TITLE
[Wizard] No retry and server url empty after failure

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10002]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

After entering an invalid server url, or the server is temporarily not available, I can't retry the connection. Server url got deleted from the input field, and I need to type it again. Also a retry button would be handy.

### Expected behavior

I'd expect an option to correct and/or retry a server connection.

### Steps to reproduce the issue

1. Enter invalid server url

### Screenshots

![CleanShot 2022-08-05 at 15 01 28](https://user-images.githubusercontent.com/214010/183083386-bf4e6ab5-12e5-43d7-a5e0-1bdb7936c3cb.png)

### Client version number

```
ownCloud 3.0.0.8266-daily20220805 bde1a7 Aug 5 2022 02:10:42
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-21.6.0
```

### Additional context

@tbsbdr any ideas?

**Comment by TheOneRing** [comment]
Related: https://github.com/owncloud/client/issues/9540

**Comment by fmoc** [comment]
I suppose you'd be happy with the wizard putting the URL back into where it should go? You can then retry this by clicking `Next >`.
