### ISSUE TITLE
Reconnect when the server was unreachable

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10033]
Followup to: https://github.com/owncloud/client/pull/10028

Currently the client might remain in a disconnected state and does not offer any possibility to reconnect.

The user needs to restart the client or log out and back in.

**Comment by TheOneRing** [comment]
Supposed to be fixed.
We now have a reconnect button and the client should be more stable in general.

**Comment by HanaGemela** [comment]
Doesn't work with [ocis.ocis-keycloak.latest.owncloud.works](https://ocis.ocis-keycloak.latest.owncloud.works/)
Tested with ownCloud 4.0.0.10373-daily20230310, mac

Steps to recreate:
1. Turn off wi-fi
2. Force sync (to disconnect from the server) 
3. Turn on wi-fi
4. Click Reconnect button

Actual result: Connecting but will never connect, remains offline
Expected result: Back online. Like when using demo.owncloud.com, that works well

**Comment by HanaGemela** [comment]
Log: [ownCloud.log](https://github.com/owncloud/client/files/10943796/ownCloud.log)

**Comment by TheOneRing** [comment]
Hmm `23-03-10 17:04:34:518 ` is when the connection failed.
The log ends at `23-03-10 17:04:51:175`.
We expect it to take 5-10 minutes for the client to try to reconnect.
How long did you wait?

**Comment by HanaGemela** [comment]
Then why do we have the Reconnect button when I have to wait until the client reconnects by itself? I haven't waited 5 minutes. It wasn't needed for demo.owncloud.com. That reconnects well when clicking the button

**Comment by TheOneRing** [comment]
Oh yes I was talking about automatic recconection.
I'll have a look next week.

**Comment by HanaGemela** [comment]
But that's a good point. What is this issue about? The description is too general

**Comment by jnweiger** [comment]
Thanks, I also had reconnect issues in https://github.com/owncloud/client/issues/10559

**Comment by TheOneRing** [comment]
> [ocis.ocis-keycloak.latest.owncloud.works](https://ocis.ocis-keycloak.latest.owncloud.works/)

Can you reproduce the issue with ocis.owncloud.com (I can't) .
https://ocis.ocis-keycloak.latest.owncloud.works/ appears to be currently broken in different ways.

**Comment by TheOneRing** [comment]
Automatic reconnect worked, I opened a new issue for your discovery.

**Comment by HanaGemela** [comment]
Automatic reconnect fixed in ownCloud 4.0.0.10576-daily20230405,mac
