### ISSUE TITLE
Download with the client much slower than with browser

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10031]
![image](https://user-images.githubusercontent.com/200626/184861409-275d807d-1fb0-4596-ab9f-2d00add43378.png)
![image](https://user-images.githubusercontent.com/200626/184861419-249dfdf2-ae03-4573-8cdb-6c919b217088.png)

**Comment by HanaGemela** [comment]
Expected result: Virtual file downloaded by double clicking in the file browser gets downloaded quicker than 2.11

**Comment by individual-it** [comment]
download in both cases (VFS & webUI) take similar time :+1:
