### ISSUE TITLE
[Spaces] Visually Distinguish Personal and Shares Spaces from Project Spaces

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10041]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

On the account page, it would be nice, to have Personal Files and Shares on top, then all your spaces below, with some visual separation.

### Proposed solution

See current iOS implementation for inspiration:
<img width="436" alt="CleanShot 2022-08-18 at 12 15 40@2x" src="https://user-images.githubusercontent.com/214010/185371641-4a305cd2-173c-4438-ab86-2d74117bdaec.png">

### Additional context

Current state:

![CleanShot 2022-08-18 at 12 06 09@2x](https://user-images.githubusercontent.com/214010/185371761-e7729af0-9fd7-43d4-8ad4-7c9067dd7529.png)

```
testpilotcloud 3.0.0.8351-daily20220818 804d66 Aug 18 2022 02:40:12
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-21.6.0
```

**Comment by TheOneRing** [comment]
First attempt can be seen in https://github.com/owncloud/client/pull/10265

**Comment by erikjv** [comment]
List views on iOS support grouping, while Qt does not. One option is to add a separator item, but that would complicate the underlying model code even more. Another option is to sort the "personal" and "shared" spaces into different items in a treeview, but this would be a big change to the underlying model, the views, and the painting code. We thing that complicating this code is a good idea, on the contrary: we are simplifying it by moving the "Add" button out of the list and into the surrounding dialog.

So I would propose to take the simple route: just add an extra text label for shared spaces. See the "(Shared)" text in the screenshot below.

<img width="912" alt="Screenshot 2023-02-02 at 15 18 09" src="https://user-images.githubusercontent.com/151956/216350545-d13112e5-1f0e-4766-8fda-1c7005960a39.png">

**Comment by tbsbdr** [comment]
Is it possible to separate
- Personal
- Shares
- Spaces
just via different icons?

![image](https://user-images.githubusercontent.com/26610733/218466859-f9b87682-9e66-4a8e-b93f-d9faae4b77c4.png)

**Comment by michaelstingl** [comment]
Looks sorting not properly working:

![CleanShot 2023-02-13 at 14 16 11@2x](https://user-images.githubusercontent.com/214010/218468043-3c7561bb-245b-49ff-93fb-506bc1649823.png)

```
testpilotcloud 4.0.0.10074-daily20230209 6ba0a9
Libraries Qt 5.15.8, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: suffix
osx-22.2.0
```

**Comment by michaelstingl** [comment]
Proposal was, to use different icons:

<img width="875" alt="CleanShot 2023-02-14 at 11 08 35@2x+" src="https://user-images.githubusercontent.com/214010/218727263-733c7309-6daf-47b0-9d88-301d31690168.png"> | <img width="875" alt="CleanShot 2023-02-14 at 12 35 44@2x+" src="https://user-images.githubusercontent.com/214010/218727295-4d533052-fa0d-4250-9ef4-8debfae48a75.png">
-- | --

Personal
- http://ocis.ocis-traefik.latest.owncloud.works/icons/resource-type-folder-fill.svg

Shares
- http://ocis.ocis-traefik.latest.owncloud.works/icons/share-forward-fill.svg

Project Spaces
- http://ocis.ocis-traefik.latest.owncloud.works/icons/layout-grid-fill.svg
  (or Space image thumbnail)

Default icons Gould be retrieved from `theme.json`
- https://github.com/owncloud/web/issues/8424

@fmoc already separated the overlay status icons

/cc  @TheOneRing

**Comment by michaelstingl** [comment]
Proposal from @TheOneRing : 

- Graph API Drives endpoint should respond with a default image, if no Space image is set.

**Comment by TheOneRing** [comment]
Alternatively the web fronted should set a default image if none is set by the user.

**Comment by kulmann** [comment]
Is using a default icon an option as well? I.e. space returns the icon name from the `remixicon` icon set. Could be used by all clients then if no space image is set.

**Comment by TheOneRing** [comment]
> Is using a default icon an option as well? I.e. space returns the icon name from the `remixicon` icon set. Could be used by all clients then if no space image is set.

Is that icon available in the new branding endpoint?  Or are you suggesting to start a shared resources initiative?

**Comment by HanaGemela** [comment]
Icons look all the same in ownCloud 4.0.0.10645-daily20230414, mac

<img width="315" alt="Screenshot 2023-04-14 at 10 44 47" src="https://user-images.githubusercontent.com/49001702/231993000-176e3956-f4c3-44a7-b5d9-7154199950b1.png">

**Comment by michaelstingl** [comment]
> Icons look all the same in ownCloud 4.0.0.10645-daily20230414, mac
> 
> <img alt="Screenshot 2023-04-14 at 10 44 47" width="315" src="https://user-images.githubusercontent.com/49001702/231993000-176e3956-f4c3-44a7-b5d9-7154199950b1.png">

Works as designed ✅ 

Backend need to provide different icons:
- https://github.com/owncloud/ocis/issues/5895

Currently you only see different icons when you upload a Space image.

**Comment by HanaGemela** [comment]
Wouldn't it be nice to handle the non-square images the same way server does? (I'm not saying the server approach is the correct one, just that both of them should be the same) 

<img width="1332" alt="Screenshot 2023-04-14 at 13 58 15" src="https://user-images.githubusercontent.com/49001702/232037625-cbd3689a-50e6-4e35-9c89-a4ee82a07232.png">

**Comment by HanaGemela** [comment]
@michaelstingl confirmed that it works as designed. Client displays what server provides
