### ISSUE TITLE
[Mac] Display context menu for sync roots

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10056]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Context menu for sync roots is needed for the following uses cases:

- Hydrate / dehydrate the full sync folder (VFS)
- Share the current folder, especially in cases where the sync root is an arbitrary remote subfolder
- Open in web (support advanced use cases, like Space management)

### Proposed solution

I'd vote to bring back the context menu for sync roots.

### Additional context

Tested with:

```
ownCloud 3.0.0.8373-daily20220823 99e2e6
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-21.6.0
```

![CleanShot 2022-08-23 at 10 42 15](https://user-images.githubusercontent.com/214010/186114574-a61397c6-a1d0-408a-972b-23191b1bc3ff.png) | ![CleanShot 2022-08-23 at 10 42 55](https://user-images.githubusercontent.com/214010/186114694-f875af67-b8d2-4842-b874-574ed81d9b87.png)
-- | --
Sync root (Space) | Subfolder of sync root

Related:
- https://github.com/owncloud/client/issues/8595
- https://github.com/owncloud/client/pull/9849

**Comment by TheOneRing** [comment]
3.0 on Windows
![image](https://user-images.githubusercontent.com/200626/189107449-e3d4252b-7e87-4eea-ad0f-d40d55ecc765.png)

**Comment by michaelstingl** [comment]
> 3.0 on Windows

Ah, okay. Then we need it add it only for Mac. (and Linux?) Previously, those actions were accessible via the "`⋯`" button for each sync connection.

**Comment by TheOneRing** [comment]
Only mac I think
