### ISSUE TITLE
[Wizard] Deprecate link to app password setup

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10055]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

App passwords are oC10 only, and aren't supported with oCIS. And also oC10 moves to OAuth 2.0 and OpenID Connect.

<img width="496" alt="CleanShot 2022-08-23 at 09 22 06@2x" src="https://user-images.githubusercontent.com/214010/186096536-2ebf9251-74c4-447e-9bd4-a4787c284363.png">

### Proposed solution

I'd propose to remove the link to the app password setup. (app password will still work with basic auth)

### Alternative solutions you considered

Only remove the link to the app password setup when connected to a oCIS instance?

### Additional context

Tested with:

```
ownCloud 3.0.0.8373-daily20220823 99e2e6
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-21.6.0
```

**Comment by pmaier1** [comment]
**PB**
- Potential harm of the feature in the desktop client is larger than the benefit
- Accepted

**Comment by michaelstingl** [comment]
@fmoc please remove this line from the wizard.
