### ISSUE TITLE
Ubuntu 22.04 installation instructions are outdated

### ISSUE THREAD

**Issue by pizzasok** [owncloud/client#10053]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The installation instructions for Ubuntu 22.04 are outdated:
https://download.owncloud.com/desktop/ownCloud/stable/2.11/linux/download/

### Expected behavior

By the new standards for key handling the following two commands should be used:
$ wget -q -O - https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_22.04/Release.key | gpg --dearmor | sudo tee /usr/share/keyrings/owncloud_archive-keyring.key
$ echo 'deb [signed-by=/usr/share/keyrings/owncloud_archive-keyring.key] https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_22.04/ /' | sudo tee -a /etc/apt/sources.list.d/owncloud.list

### Client version number

owncloud-client-2.11.0+oc-8354

### Desktop environment (Linux only)

Ubuntu 22,04 GNOME 42

### Client package version and origin (Linux only)

owncloud-client-2.11.0+oc-8354

**Comment by fmoc** [comment]
Fixed for the upcoming releases.
