### ISSUE TITLE
[QA] Cannot pause sync

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10067]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

While re-testing #9967 with 2.11.1-rc.1 in Linux Mint using the appimage.

![image](https://user-images.githubusercontent.com/1108546/187091585-08d9bd92-dc63-45b1-953f-50f19b85dc0d.png)

Expected behaviour:
* the 3-dots menu should have many more entries. E.g. pause sync is missing.

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

.

### Actual behavior

.

**Comment by fmoc** [comment]
The sync connection apparently has some issue. Please provide a log.

**Comment by jnweiger** [comment]
[ownCloud-logdir.zip](https://github.com/owncloud/client/files/9447017/ownCloud-logdir.zip)

This is a multi-acocunt client. The logs are after creating afresh connection with demo.owncloud.org
Hope nothing from the other accounts is showing...
(All accounts are affected. Old existing, and newly created)

**Comment by jnweiger** [comment]
Fixed in ownCloud 2.11.1rc2 (build 8424)
- Thanks!
