### ISSUE TITLE
Subfolders do not expand - Owncloud Desktop Client 2.11.0 (bluild 8354)

### ISSUE THREAD

**Issue by worldnetworksr** [owncloud/client#10064]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Hello everyone, 

We have a issue with new release of Owncloud Desktop Client 2.11.0 (bluild 8354).

With this version (2.11.0 (bluild 8354) )we cannot expand subfolders to add them locally.

![image](https://user-images.githubusercontent.com/110347234/186750678-f31b32be-33ae-407a-aead-7a0b921792d6.png)

As you can see in the image, the subfolder does not open in this version.

With version 2.10.1 (build 7187) this does work.

![image](https://user-images.githubusercontent.com/110347234/186751294-ad3a07e0-156b-45bc-83ed-30388d7fd3f0.png)

### Expected behavior

A possible solution to the problem in this new version 2.11.0

### Client version number

Owncloud Desktop Client 2.11.0 (bluild 8354)

**Comment by gmexops** [comment]
We've also found this. All our clients have had to be downgraded to 2.10.1

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/client/issues/9967

**Comment by michaelstingl** [comment]
Please test with the 2.11.1 RC:
https://download.owncloud.com/desktop/ownCloud/testing/2.11.1-rc1.8388/
