### ISSUE TITLE
Japanese localization does not exist.

### ISSUE THREAD

**Issue by devi69** [owncloud/client#10076]
### Pre-submission Checks

- [x] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Since ver2.10.1, Japanese (ja_jp) is no longer an option for language.

### Expected behavior

Japanese can be selected from the language in the settings.

### Steps to reproduce the issue

Install ver2.10.1 or ver2.11.1 and check the language list in the settings.

### Screenshots

![image](https://user-images.githubusercontent.com/23556623/188049467-49e377a9-cd10-4733-8030-184d6283403b.png)

### Client version number

ownCloud 2.11.1 (build 8438) [c6dbf3](https://github.com/owncloud/client/commit/c6dbf397482d074bc931e2812bb5542f0fa23d0d) Aug 31 2022 04:04:04
Libraries Qt 5.12.11, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: wincfapi
windows-10.0.19044

**Comment by TheOneRing** [comment]
Our translations are provided by the community and only distributed with the client if they cover 75%.
The 75% may sound like a random value but it indicates how well the translations are maintained.
Japanese dropped to 74% and was thus automatically removed.

**Comment by devi69** [comment]
Thank you very much. I now understand that it is due to a lower translation rate.
We will work hard on our translations to make sure we cover 75%.
