### ISSUE TITLE
[QA] Reduce server logs size by adding only the logs of the failed test scenario

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#10082]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

The server logs generated by the squish is `~24MB` in size. Reducing its size would be a good way to utilize resources.
So, instead of full server log, I think we care only about the logs of the failed tests. We can find a way to only include the logs of the failed tests so that the logs file will be smaller and only required logs are reported.

**Comment by saw-jan** [comment]
CC @fmoc @TheOneRing thoughts?

**Comment by fmoc** [comment]
As long as we have the server space, I don't really see a reason to reduce the size. Can we even be sure not to redact or remove information we might find useful?

What's your main argument? Saving space on the storage server? Making it easier to navigate in these logs?

**Comment by saw-jan** [comment]
> As long as we have the server space, I don't really see a reason to reduce the size. Can we even be sure not to redact or remove information we might find useful?
> 
> What's your main argument? Saving space on the storage server? Making it easier to navigate in these logs?

I was only concerned about the size of the server log file (that will be removed after a certain period of time - maybe 20-30 days).
If the size doesn't matter then I gues my concern is cleared.
