### ISSUE TITLE
[OIDC] fallback to static client id when OIDC DCR fails

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10097]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Insights from @micbar

> I see no possible way to deactivate "Dynamic Client registration" (DCR) on Keycloak. So it seems we always have the registration endpoint available. Keycloak has policies, which clients, origins and redirect urls it accepts. So it is very likely that the registration request can fail.

### Proposed solution

The client should be graceful when the registration attempt fails and try to connect with the public client ID

### Additional context

iOS implementation:
- https://github.com/owncloud/ios-app/issues/1006
- https://github.com/owncloud/ios-app/pull/1068

Android issue:
- https://github.com/owncloud/android/issues/3755

@TheOneRing

**Comment by TheOneRing** [comment]
Looking at the code, this should already be the case...

**Comment by TheOneRing** [comment]
I implemented two unit tests for dynamic registration and the fallback appears to be working.

**Comment by micbar** [comment]
awesome. What happens when the userinfo request after the registration fails?

**Comment by TheOneRing** [comment]
In that case we the authentication fails as we can't compare the server provided user with the requested user.
This check is required to prevent mixing up the sync of einstein with those from katherine

**Comment by michaelstingl** [comment]
@TheOneRing seems DCR fails with the 1st token refresh:
https://cloud.owncloud.com/index.php/f/5901500
(5 minute with Keycloak)

**Comment by TheOneRing** [comment]
Can you retest with a current client? 
Was https://github.com/owncloud/client/commit/e939d8b20cfed3b826bfdcd08383634c9f75395d already part of your build?

**Comment by michaelstingl** [comment]
> Can you retest with a current client?
> Was [e939d8b](https://github.com/owncloud/client/commit/e939d8b20cfed3b826bfdcd08383634c9f75395d) already part of your build?

I'll re-test…

**Comment by michaelstingl** [comment]
> > Can you retest with a current client?
> > Was [e939d8b](https://github.com/owncloud/client/commit/e939d8b20cfed3b826bfdcd08383634c9f75395d) already part of your build?
> 
> I'll re-test…

Can't test because of:
- https://github.com/owncloud/ocis/issues/4818
- https://github.com/owncloud/ocis/issues/4858

**Comment by TheOneRing** [comment]
Please test

**Comment by TheOneRing** [comment]
Testing requires keycloak default setup.

**Comment by lsnow99** [comment]
Hey, I was able to test this successfully in my setup with Keycloak and OCIS (no DCR enabled) using the [v3.0.0-rc3 Desktop Client](https://github.com/owncloud/client/releases/tag/v3.0.0-rc3).
