### ISSUE TITLE
Latest AppImage on the main download page is a beta / test version

### ISSUE THREAD

**Issue by alariej** [owncloud/client#10108]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Hi, the link for downloading the latest AppImage on the main ownCloud desktop client download page (https://owncloud.com/desktop-app/) is:

https://download.owncloud.com/desktop/testpilotcloud/stable//2.11.1.8439/linux-appimage/testpilotcloud-2.11.1.8439.AppImage

Until now the name of the file has been ownCloud-<version_number>.AppImage and not testpilotcloud-<version_number>.AppImage. Is this change intentional?

Also, note that the link in the Updates section ("New ownCloud Client 2.11.1 available. Please click here to download the new AppImage manually") of the app where users would download the latest AppImage manually points to https://download.owncloud.com/desktop/ownCloud/stable/2.11.1.8438/linux/download/, which is where the repository packages can be downloaded, not the AppImage ones.

### Expected behavior

A link to the latest production AppImage file.

### Client version number

ownCloud Client AppImage 2.11.0 (build 8354)

### Desktop environment (Linux only)

Ubuntu 22.04

### Client package version and origin (Linux only)

https://download.owncloud.com/desktop/ownCloud/stable//2.11.0.8354/linux-appimage/ownCloud-2.11.0.8354.AppImage

**Comment by TheOneRing** [comment]
Thx for reporting, the link is indeed wrong and should not point to our canary builds. 
https://download.owncloud.com/desktop/ownCloud/stable/2.11.1.8438/linux-appimage/ is the right location to look at 
Something went wrong with the release page.

**Comment by alariej** [comment]
OK sounds good, looking forward to 3.0. Thanks for the link!
