### ISSUE TITLE
Appimage Segmentation fault when starting browser (OAuth2)

### ISSUE THREAD

**Issue by vidaren** [owncloud/client#10100]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

This could be a duplicate of #9985, however the console log, version and environment are different. Feel free to close/merge.

Having downloaded and launched `ownCloud-2.11.1.8438.AppImage`, I enter the URL of the ownCloud server, which has OAuth2 enabled, and click Next.

Then the main window is minimized but nothing else happens. The browser doesn't open, and if it's already open, nothing happens in the browser. When launched in a console, "Segmentation fault" is logged, nothing else.

The "Re-open browser" button also does nothing.

### Expected behavior

I expected a browser to open, to let me authenticate and authorize the client.

When I instead install the Debian-supplied package, owncloud-client (2.5.1.10793+fsdg-1), this works as expected.

### Client version number

ownCloud-2.11.1.8438.AppImage
on KDE Neon 5.25 (Debian 11 based)

### Desktop environment (Linux only)

KDE Plasma 5.25

### Client package version and origin (Linux only)

ownCloud-2.11.1.8438.AppImage downloadet from https://download.owncloud.com/desktop/ownCloud/stable//2.11.1.8438/linux-appimage/ownCloud-2.11.1.8438.AppImage

### Server information

ownCloud 10.7.0 (stable)
on Debian 10.12 VM

**Comment by fmoc** [comment]
Can be reproduced in a live CD environment using `neon-user-20221011-1244.iso`... to some extent. I can see a "Segmentation fault" message in the terminal. The client is just running fine, though. The initial attempt and every subsequent click on the "Open browser" button create such a message in the terminal.

Seems like whatever `QDesktopServices::openUrl` is doing internally is crashing... It should just make a call to a D-Bus interface. I tested this manually, it's working fine...

**Comment by fmoc** [comment]
Fixed in craft, see https://invent.kde.org/packaging/craft/-/merge_requests/94.
