### ISSUE TITLE
Nautilus integration on Rocky Linux is missing in AppImage

### ISSUE THREAD

**Issue by dpapac** [owncloud/client#10124]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Using the AppImage via Rocky Linux 9 on VirtualBox VM: damkencloud-2.11.1.8547.AppImage

- no overlays are displayed 
- ownCloud submenu isn't present

### Expected behavior

Overlays are displayed
ownCloud submenu is available

### Steps to reproduce the issue

Using the AppImage via Rocky Linux 9 on VirtualBox VM: damkencloud-2.11.1.8547.AppImage

### Client version number

damkencloud
Version: 2.11.1 (build 8547)

## Workaround: 
- Install the damkencloud-client-overlays-icons-2.11.1-8547.x86_64.rpm from Fedora 36 or CentOS7
- Close all instances and reboot the machine

Use the following command to run the application: 
``` env QT_QPA_PLATFORM=wayland ./damkencloud-2.11.1.8547.AppImage -s ```

![grafik](https://user-images.githubusercontent.com/101094874/191252918-c4eec184-d43d-48ad-9cd5-541c1f8c75d6.png)
![grafik](https://user-images.githubusercontent.com/101094874/191253017-9262f8ff-08d1-4c10-92b0-a048af37a154.png)
![grafik](https://user-images.githubusercontent.com/101094874/191254059-467ca3c6-7419-47c1-b7ab-70a83e13ea93.png)

It works.

**Comment by michaelstingl** [comment]
You can find the AppImage docs here:
https://doc.owncloud.com/desktop/2.11/installing.html#appimage

**Comment by michaelstingl** [comment]
Related: https://github.com/owncloud/docs-client-desktop/issues/267
