### ISSUE TITLE
Windows Client does not remove folder icon after delete sync connection removed

### ISSUE THREAD

**Issue by kyesil** [owncloud/client#10148]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

owncloud client does not remove folder icon after sync connection removed. it's confusing which folder is sync

### Expected behavior

1- Remove default Sync folder  with ui. 
2- "Add folder sync connection" button then select my folder on my desktop.
3- Next step add new folder on root path. 
4- Finish wizard and wait all folder for synced. After I see folder icon changed my folder.
5- After I remove Syncf folder connection with ui. 
6- Wait 1 minitue. After refresh desktop.  I see owncloud icon.  

We can remove Desktop.ini file then fix it.  But we need to go folder option then uncheck hide system file then we can remove Desktop.ini file.  
It can be automatic remove after sync folder connection removed.

### Screenshots

![own2](https://user-images.githubusercontent.com/8676372/192730137-861d9ec5-4494-46bb-9fcd-4a8d0ef69083.png)
![own3](https://user-images.githubusercontent.com/8676372/192730146-9ddfdbb1-0c52-4e39-8b7a-04005e9ddaa3.png)
![own4](https://user-images.githubusercontent.com/8676372/192730149-e74ba6fb-d3eb-495e-9a81-71f24a8e5db6.png)

### Client version number

ownCloud 2.11.1 (build 8438)
windows-10.0.25206
os Windows 11 22H2

### Installation path (Windows only)

C:\Program Files\ownCloud

### Server information

ownCloud10.11.0 (stable) on docker machine

**Comment by michaelstingl** [comment]
Known limitation, workaround in the docs:
https://doc.owncloud.com/desktop/2.11/removing.html#windows-navigation-sidebar
