### ISSUE TITLE
[QA] admin or guest user cannot connect a desktop or mobile client

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10160]
Seen with openidconnect 2.2.0-rc.6 and desktop client 2.11.1, server 10.11.0

* setup kopano IDP, so that it does not include the admin account.
* admin can login fine through the cassic web UI using username and password
* connect a desktop client using the admin account.
* the client immediately opens a web browser with the IDP login page. Admin cannot enter their password with owncloud. BAD.

Not a regression. Not directly related to https://github.com/owncloud/openidconnect/pull/253 (but the test was motivated from there).

Expected behaviour
* admin or other local (guest) users still can use desktop clients after openidconnect is enabled.
* not sure where this could be implemented in the connection wizard, though :see_no_evil:

**Comment by TheOneRing** [comment]
Won't fix, not supported.
