### ISSUE TITLE
Polishing: Single Space is not recognised as clickable item

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/client#10161]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

## Problem:
@michaelstingl told me, that @dragotin and maybe others finds it hard to recognise a single Space as a selectable item. (Please correct if understood wrong)

### Single Space in list is not recognised as clickable item
![image](https://user-images.githubusercontent.com/26610733/194270023-cfc1d5ca-aa05-4e94-88ee-4d8ce8cdcae9.png)

### Proposed solution

Thrifty proposal without big changes
*Assumption:* The attention is on the Space Image, as the image is the biggest element in the view; Thus, the radiobutton could be overlooked.

### Proposed solution:

- Make the Space image smaller
- Radiobutton should have even whitespace around it initially to give it more importance 
![Screenshot 000717](https://user-images.githubusercontent.com/26610733/194275885-476fa084-e140-4dce-b3da-e3d4e79a6e9d.png)

![image](https://user-images.githubusercontent.com/26610733/194273278-1a58f248-4b77-4145-b2f6-9bf4dfb75752.png)

@dragotin @michaelstingl do you think the proposal would solve the issue of unrecognised clickable items?

### Some research examples / inspiration for list-presentations in System-UIs: 

![Screenshot 000713](https://user-images.githubusercontent.com/26610733/194264228-7ea6ce4d-7ab7-43f7-b73e-5e3da7e7b9f4.png)

![Screenshot 000714](https://user-images.githubusercontent.com/26610733/194264358-79e14406-f87e-4789-9269-f5adbba90604.png)

![image](https://user-images.githubusercontent.com/26610733/194270882-3856339b-caa4-4388-97c1-a11407ec60a1.png)

![image](https://user-images.githubusercontent.com/26610733/194271079-6d203ffc-9744-4e62-8aeb-a6805c1ed6ab.png)

![image](https://user-images.githubusercontent.com/26610733/194271191-b6765dd7-96d1-4c76-8519-a0fb03fde053.png)

![image](https://user-images.githubusercontent.com/26610733/194271298-72a21088-035b-4147-8fa3-0b32e168d347.png)

![image](https://user-images.githubusercontent.com/26610733/194271900-77e65078-5d19-4edd-95ef-5be95301e9ef.png)

![Screenshot 000716](https://user-images.githubusercontent.com/26610733/194272718-f5967fa8-57d9-4c04-9290-b0b670298031.png)

**Comment by TheOneRing** [comment]
I still think that radio buttons in a table are weird.
We could select one space from the beginning, but the confused user could then ad the same space multiple times.

**Comment by michaelstingl** [comment]
I had the opinion, the lines without the radio button are hard to recognise as interaction elements. 

Adding the radio button was my first proposal, to make it more clickable. 

@TheOneRing and @dragotin don‘t like the radio buttons, and I agree. I’d love to have something nicer that works.

**Comment by tbsbdr** [comment]
maybe @TheOneRing nails it about the table - what about using cardish-representation like this?

![](https://user-images.githubusercontent.com/26610733/194322822-ef41faa1-ddc3-49cd-9dfb-27b8f0a37031.png)

**Comment by TheOneRing** [comment]
Nothing you would like to do with Qt Widgets

**Comment by DeepDiver1975** [comment]
space ui is meanwhile reimplemented -> close
