### ISSUE TITLE
[Mac] Crash reporter missing on Apple Silicon (Rosetta 2 emulation and native builds)

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10163]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Our crash reporter doesn't work. Instead the useless one from macOS is shown.

### Expected behavior

.

### Steps to reproduce the issue

```
michaelstingl@Michaels-MacBook-Air ~ % /Applications/testpilotcloud.app/Contents/MacOS/testpilotcloud --version
testpilotcloud testpilotcloud 3.0.0.8694-daily20221005
86a804
Libraries Qt 5.15.5, OpenSSL 1.1.1q  5 Jul 2022
Using virtual files plugin: suffix
osx-21.6.0
michaelstingl@Michaels-MacBook-Air ~ % /Applications/testpilotcloud.app/Contents/MacOS/testpilotcloud --debug
```

### Client version number

```
testpilotcloud 3.0.0.8694-daily20221005 86a804
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-21.6.0
```

**Comment by TheOneRing** [comment]
Could be related to rosetta.
Crash reporter comes up at @HanaGemela intel mac but not on my m1.

**Comment by michaelstingl** [comment]
We can check with 4.0 preview-M1 builds @HanaGemela

**Comment by michaelstingl** [comment]
> We can check with 4.0 preview-M1 builds @HanaGemela

Crash reporter also not working on native Apple Silicon builds. Maybe breakpad update will help:
- https://github.com/owncloud/client/issues/10451

**Comment by michaelstingl** [comment]
> Works with m1 builds on m1

```
% /Applications/testpilotcloud.app/Contents/MacOS/testpilotcloud --debug
m_crashReporterChar:  /Applications/testpilotcloud.app/Contents/MacOS/testpilotcloud_crash_reporter
Dump file was written to: /private/var/folders/9s/j95dtkp17t5gyy9br589s6r00000gn/T/B195ED12-389E-4F28-ADAA-EEADA9FA562A.dmp
% RESPONSE: "CrashID=e91213cc-9892-401e-b4f8-22bff286efd8"
```

👍

**Comment by HanaGemela** [comment]
Works also on intel mac, ownCloud 4.0.0.10484-daily20230323
