### ISSUE TITLE
Structure menu with horizontal lines

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10170]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

3.0 client does't have the horizontal divider lines in the tray menu.

### Expected behavior

Should have the lines as in 2.11.1

### Screenshots

![CleanShot 2022-10-07 at 14 52 20@2x](https://user-images.githubusercontent.com/214010/194558981-a5cf4e0b-91d8-49b3-8742-548d19599864.png) | ![CleanShot 2022-10-07 at 14 52 40@2x](https://user-images.githubusercontent.com/214010/194558993-828e889b-3aa5-49f6-8d4c-efa0de0f9089.png)
-- | --
2.11.1 | 3.0

### Client version number

```
testpilotcloud 3.0.0.8706-daily20221007 66ca88
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-21.6.0
```

**Comment by TheOneRing** [comment]
Nope 
![image](https://user-images.githubusercontent.com/200626/194561339-ad4bdb68-83e9-4fe3-bbe4-1575febf1dba.png)

**Comment by michaelstingl** [comment]
Mac only issue?

**Comment by fmoc** [comment]
https://bugreports.qt.io/browse/QTBUG-94802

**Comment by TheOneRing** [comment]
In 4.0 we will update Qt to 5.15.7 or later.

**Comment by TheOneRing** [comment]
Should be fixed by https://github.com/owncloud/client/pull/10376, the change only affects 4.0 builds

**Comment by TheOneRing** [comment]
This was a mac issue. Always worked on Windows.

**Comment by michaelstingl** [comment]
![CleanShot 2023-01-16 at 15 46 52@2x](https://user-images.githubusercontent.com/214010/212705991-805566da-3b0b-484f-adc0-3480229f46c5.png) | ![CleanShot 2023-01-16 at 15 47 05@2x](https://user-images.githubusercontent.com/214010/212706028-cd9b57bb-8142-4dd5-8bf1-aa40e669b193.png)
-- | --
`ownCloud 3.1.0.9784-daily20230115 b4ec19`<br>`Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022` | `testpilotcloud 4.0.0.9783-daily20230115 f30e04`<br>`Libraries Qt 5.15.8, OpenSSL 1.1.1s 1 Nov 2022`

Looks good with 4.0 daily builds on macOS 13.1 Ventura! ✅
