### ISSUE TITLE
[Spaces] Exclude disabled Spaces from initial sync

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10173]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Spaces can be "disabled". At least at initial sync, we should exclude them. (no concept for Spaces that get disabled or deleted later yet)

### Proposed solution

Exclude disabled Spaces from initial sync.

**Comment by TheOneRing** [comment]
Handling spaces that get disabled after they where added is not possible in the scope of 3.0.
Prevent them from being added in the first place is another thing, and can be done for 3.0.

**Comment by fmoc** [comment]
Fixed by #10244.
