### ISSUE TITLE
owncloud not working on ubuntu 22.04 

### ISSUE THREAD

**Issue by kuateric** [owncloud/client#10188]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Following behaviours occur on any fresh installed server with ubuntu 22.04 wayland: 
- owncloud either crashes with the start of the system 
- or does not respond when trying to connect to a owncloud repository 

### Actual behavior

- crash:
![grafik](https://user-images.githubusercontent.com/22998049/196356026-98169fab-c0c5-4c12-87e9-d7c08469fe1d.png)

- The next button somehow does not respond. 
![image](https://user-images.githubusercontent.com/22998049/196240579-de8719c0-ee35-430c-9987-925af5537cb6.png)

I am working on a virtual machine that I set up only for the purpose of testing. In this machine, there is nothing else installed beside owncloud.  As in our enterprise servers, echo "$QT_QPA_PLATFORM" outputs nothing on the terminal. 

I really think that the problem is repeatable. Another guy mentioned that [here](https://central.owncloud.org/t/cannot-connect-to-my-owncloud-server-on-linux-ubuntu/38294). 

### Client version number

the version you can find here:
 https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/

**Comment by kuateric** [comment]
I am not an experienced user. Owncloud is used by my company (over 2000 employees) for collaborative work. Our IT-department maintains the client on Windows and not on Linux.  Because I have some projects on Linux, I need to use the client there. So if there is a contractual technical assistance agreement between you and us, we might also try to go this way. I can bring you in contact with my IT-colleagues that install that on our servers.

**Comment by michaelstingl** [comment]
> So if there is a contractual technical assistance agreement between you and us, we might also try to go this way. I can bring you in contact with my IT-colleagues that install that on our servers.

Sure, for professional help, you can get in touch with our colleagues:
https://owncloud.com/contact-us/
