### ISSUE TITLE
desktop client cannot share any item from within a space that is not the personal space

### ISSUE THREAD

**Issue by individual-it** [owncloud/client#10183]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The client can only share files/folders from within the personal space. Its impossible to share or create public links from any other space

### Expected behavior

ability to share the file

### Steps to reproduce the issue

1. create a space
2. add a file into the space
3. sync the space with the desktop client
4. try to share the file by using the desktop client

### Screenshots

![image](https://user-images.githubusercontent.com/2425577/195506341-9a2dcfe2-ab74-419a-b655-e59a6c4dc4af.png)
![image](https://user-images.githubusercontent.com/2425577/195506354-044ca0d4-b592-4779-9721-a3d08512dfbc.png)

### Client version number

3.0.0.8761-alpha6 [2a0649](https://github.com/owncloud/client/commit/2a06490795f0549ca123a2ad4b5f4ae8654d281a)
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: wincfapi
windows-10.0.17763

**Comment by pmaier1** [comment]
cc @michaelstingl @TheOneRing

**Comment by TheOneRing** [comment]
Does the user have edit settings for that space?

**Comment by pmaier1** [comment]
Good point. The user has to have the "Manager" role in order to be able to share.

**Comment by michaelstingl** [comment]
@individual-it please share log including HTTP

**Comment by individual-it** [comment]
@michaelstingl uploaded. The file tried to be shared when capturing that log is `mz own space\\app.prg`

**Comment by TheOneRing** [comment]
Did the client crash or was run without `--logflush` (as an alternative close the client before caputuring the log file)?
The log ends when its getting interesting.

**Comment by individual-it** [comment]
@TheOneRing I've retried with 
```
ownCloud 3.0.0.8912-daily20221025 [db8853](https://github.com/owncloud/client/commit/db885317895f219421ee1a9ea2d35bb391b886f4)
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: wincfapi
windows-10.0.17763
```
When I get into the window I still get the `not found` red string, but I can search for existing users, but when I select a user the client tells me `Wrong path, file/folder does not exist`
![image](https://user-images.githubusercontent.com/2425577/197767635-2d0d1304-7b6c-4c41-b7e0-2337193549ea.png)

Here the log file, I hope its more useful this time
[ownCloud.log](https://github.com/owncloud/client/files/9860020/ownCloud.log)

**Comment by michaelstingl** [comment]
Final 3.0 will send users to web UI for sharing:
- https://github.com/owncloud/client/pull/10241
