### ISSUE TITLE
[Spaces] Identify "Shares" Space by UUID

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10196]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

This would align the implementation with ownCloud web:
[`export const SHARE_JAIL_ID = 'a0ca6a90-a365-4782-871e-d44447bbc668'`](https://github.com/owncloud/web/blob/2ab7e6da432cb344cd86f3451eea1678461c5c90/packages/web-client/src/helpers/space/types.ts#L11)

Same is planned for the iOS app:
- https://github.com/owncloud/ios-app/issues/1164

Change of the backend implementation would break all clients.

/cc @fel @kulmann @micbar 

### Proposed solution

Identify "Shares" Space by UUID

**Comment by michaelstingl** [comment]
@TheOneRing what is the current condition? only `type=virtual` ?

**Comment by TheOneRing** [comment]
we currently handle drives with the type virtual as "Shares"
