### ISSUE TITLE
Direct access (oCIS) versions in ownCloud web

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10197]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

oCIS with ownCloud web now has the version history for files. ownCloud desktop client 2.6+ supports this already for oC10 with classic web UI (https://github.com/owncloud/client/issues/7196). We should work with oCIS and web team to support this for the new platform too.

### Proposed solution

Needs technical concept.

### Alternative solutions you considered

A while ago, I thought about a AppProvider-based solution:
- https://github.com/owncloud/ocis/issues/2792

**Comment by michaelstingl** [comment]
Blocked by:
- https://github.com/owncloud/ocis/issues/4983

/cc @fschade @micbar

**Comment by micbar** [comment]
You want to show the versions in a web view?

**Comment by michaelstingl** [comment]
> You want to show the versions in a web view?

No, just open system browser with the versions in the sidebar already opened.

**Comment by saw-jan** [comment]
Tested with `ownCloud 5.0.0.11369-daily20230703 511b96`

![Screenshot from 2023-07-03 17-45-03](https://github.com/owncloud/client/assets/52366632/813812b4-6eef-4d8f-8a1d-2b670d18c279) | ![Screenshot from 2023-07-03 17-45-30](https://github.com/owncloud/client/assets/52366632/66466d94-7b74-47f0-91d7-e17f4590aeb7)
--|--
