### ISSUE TITLE
[QA] Crash after an update to alpha9

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10221]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Crash when updating from daily 20221025 to alpha9 
Crash number 9919540e-9d46-4aac-94bc-197bdffcc210

### Steps to reproduce the issue

1. Update from daily 20221025 to alpha9 

### Screenshots

<img width="617" alt="Screenshot 2022-10-27 at 13 06 12" src="https://user-images.githubusercontent.com/49001702/198268891-f1297251-0432-4049-b6b8-fdedc56dfca7.png">

### Expected behavior

No crash

### Actual behavior

Crash 9919540e-9d46-4aac-94bc-197bdffcc210

**Comment by TheOneRing** [comment]
Could you please start the client in a terminal and provide the full log?

**Comment by TheOneRing** [comment]
Could you also run `ls -al /Applications/owncloud.app/Contents/PlugIns/` I'd like to see the timestamps

**Comment by TheOneRing** [comment]
Ok the alpha is broken, it contains only the suffix plugin.
![image](https://user-images.githubusercontent.com/200626/198279717-493d4a61-687a-475f-9fc3-f70bda2c8d95.png)

**Comment by TheOneRing** [comment]
I did a rebuild and the plugin is contained again. I have no idea what happened here, logs also don't contain anything conspicions.

**Comment by fmoc** [comment]
I guess we'll call it a hiccup in the CI then.
