### ISSUE TITLE
Free up space button is still clickable after freeing space

### ISSUE THREAD

**Issue by bishwasojha** [owncloud/client#10229]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

- If a folder contains files and folders and space was freed, the Free up space button is still clickable
- If a folder contains only files then the Free up space button is disabled after freeing up space once.

### Expected behavior

- After Free up space is clicked once, the button should be disabled.

### Steps to reproduce the issue

1. Create files & folders within a folder.
2. Click on `Free up space` on main folder of that filestructure.
3. Again check if `Free up space` is clickable or not on main folder.
4. `Free up space` button is clickable.

### Screenshots

![Screenshot from 2022-10-31 17-27-44](https://user-images.githubusercontent.com/33860671/199000463-247246f0-5d72-4bc1-abc0-ea97a33ab508.png)
![Screenshot from 2022-10-31 17-27-30](https://user-images.githubusercontent.com/33860671/199000470-b26cb4db-1991-4d5a-985d-67ca25ef7e52.png)
![Screenshot from 2022-10-31 17-28-50](https://user-images.githubusercontent.com/33860671/199000461-700ff51e-a03b-4be0-a7f0-4adcae51b52d.png)
![Screenshot from 2022-10-31 17-29-15](https://user-images.githubusercontent.com/33860671/199000696-48c28653-f470-4b9f-8113-6da9ffef95c6.png)

### Logs

[ownCloud.log](https://github.com/owncloud/client/files/9900767/ownCloud.log)

### Client version number

ownCloud 3.0.0.8973-daily20221031 [9ffbc1](https://github.com/owncloud/client/commit/9ffbc1ce7d4eaf8c4c7ae666aa3a13404d0d3fa7)
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: wincfapi
windows-10.0.19044

### Installation path (Windows only)

C:\Program Files\ownCloud

### Server information

**ocis from docker image ocis:2.0.0-beta.8**

**Comment by fmoc** [comment]
I guess this is more of a minor inconvenience than a bug. What happens when you click the button? (I guess nothing will happen, but we should make sure.)

I'm not sure we control that button anyway...

**Comment by bishwasojha** [comment]
yes, nothing happens. It is just clickable and does nothing.

**Comment by fmoc** [comment]
Looks like we have no control about that button, we can't make Windows disable or hide it.
