### ISSUE TITLE
Pause Sync button terminates the syncing

### ISSUE THREAD

**Issue by bishwasojha** [owncloud/client#10231]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

- The pause sync button says to **terminates the syncing** in dialog box. Syncing is paused. When we resumes sync, it resumes from the starting rather than from where it is paused. 

### Expected behavior

Pause sync button pauses the syncing and the resume sync button should resumes from where it is paused.

### Steps to reproduce the issue

1. Upload a file
2. Click on **Pause sync** 
3. After sync gets paused, click on **Resume sync** button.
4. **Resume sync** button resumes syncing from the beginning not from where it is paused.

### Screenshots

![Screenshot from 2022-11-04 12-04-47](https://user-images.githubusercontent.com/33860671/199906921-845ff0bc-c292-4044-9b1d-ea74e21fc995.png)

![Screenshot from 2022-11-04 12-04-57](https://user-images.githubusercontent.com/33860671/199906905-7da3aad8-6d55-401b-a77e-4e097d04b842.png)

![Screenshot from 2022-11-04 12-05-08](https://user-images.githubusercontent.com/33860671/199906706-dfd5adec-2ba4-47a8-9df7-8070d19953b9.png)

![Screenshot from 2022-11-04 12-10-32](https://user-images.githubusercontent.com/33860671/199906944-8786e000-746e-40ba-afce-7b0573eb0b91.png)

### Logs

[ownCloud.log](https://github.com/owncloud/client/files/9935677/ownCloud.log)

### Client version number

ownCloud 3.0.0.8999-daily20221104 [c677c7](https://github.com/owncloud/client/commit/c677c72fb7b4d237ce51738560eb8474048065c0)
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: wincfapi
windows-10.0.19044

### Installation path (Windows only)

C:\Program Files\ownCloud

### Server information

ocis from docker image ocis:2.0.0-beta.8

**Comment by TheOneRing** [comment]
@michaelstingl we should probably rename it to stop syncing?

**Comment by michaelstingl** [comment]
> @michaelstingl we should probably rename it to stop syncing?

Abort?

**Comment by TheOneRing** [comment]
It is permanent as the folder will then enter the paused state and only continue syncing once resumed.

**Comment by TheOneRing** [comment]
TODO: Rename button to "Stop synchronization"
