### ISSUE TITLE
Macs 13.0 shows "owncloud" is damaged

### ISSUE THREAD

**Issue by hannesa2** [owncloud/client#10236]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

After update to MacOS 13.0 I see 
`"owncloud" is damaged and can't be opened. You should move it to the Bin.`

Even a fresh download and reinstall doesn't solve it

### Expected behavior

It should work

### Steps to reproduce the issue

Use MacOS 13.0

### Screenshots

![image](https://user-images.githubusercontent.com/3314607/200176896-8dd68890-c774-44f7-be5c-8732fd60ac75.png)

### Client version number

I can't start it anymore, so there is no chance to show. It was the latest one

**Comment by michaelstingl** [comment]
> Even a fresh download and reinstall doesn't solve it

What's the exact name of the binary? [`ownCloud-2.11.1.8946.pkg`](https://download.owncloud.com/desktop/ownCloud/stable/2.11.1.8946/mac/ownCloud-2.11.1.8946.pkg)?

**Comment by hannesa2** [comment]
Exactly, I reinstalled ownCloud-2.11.1.8438.pkg on macOS 13.0 and it shows me this.
A manual open with control key let me choose to open it anyway.
For me it looks like, there is something wrong with notarization.

**Comment by michaelstingl** [comment]
Can't reproduce:

1. Install and run [`ownCloud-2.11.1.8946.pkg`](https://download.owncloud.com/desktop/ownCloud/stable/2.11.1.8946/mac/ownCloud-2.11.1.8946.pkg) on macOS Monterey 12.6
2. Update to macOS Ventura 13.0
3. Opens ownCloud (asks to re-install Rosetta2 on my M1) ✅ 

<img width="741" alt="CleanShot 2022-11-07 at 10 59 10@2x" src="https://user-images.githubusercontent.com/214010/200269335-b34a3d5a-5c9b-42ef-9b0a-00c3b9e8f8a9.png">

Anything in you `Console.app` ?

**Comment by hannesa2** [comment]
This is my situation 
<img width="1155" alt="image" src="https://user-images.githubusercontent.com/3314607/200275887-2f23adc8-d852-4579-9f50-167b88ed4b39.png">
And I was not asked about Rosetta.

I've no clue for what I should search in Console.app

Keep in mind that I made it work already by
> A manual open with control key let me choose to open it anyway.

**Comment by hannesa2** [comment]
Btw, I see you use a more recent version

**Comment by TheOneRing** [comment]
Hi @hannesa2 where did you download it?
(Michael is using a rebuild directly from our mirrors, but this should have no effect on the mac build.)

**Comment by hannesa2** [comment]
I downloaded it from here https://owncloud.com/desktop-app/ exactly this on https://download.owncloud.com/desktop/ownCloud/stable/2.11.1.8438/mac/ownCloud-2.11.1.8438.pkg

**Comment by michaelstingl** [comment]
> I downloaded it from here https://owncloud.com/desktop-app/ exactly this on https://download.owncloud.com/desktop/ownCloud/stable/2.11.1.8438/mac/ownCloud-2.11.1.8438.pkg

Installs und runs fine on my macOS Ventura 13.0:

<img width="734" alt="CleanShot 2022-11-07 at 13 42 03@2x" src="https://user-images.githubusercontent.com/214010/200301910-35d0f38e-5e26-4f70-a7e7-f87aaf61b96e.png">

**Comment by BaloMueller** [comment]
I have the same issue.
Had owncloud installed, updated to Ventura 13.0. After a restart, Mac asked me to put the binary in the trash bin. 
`"owncloud" is damaged and can't be opened. You should move it to the Bin.`

Tried to download and install the most recent version from the website: `https://download.owncloud.com/desktop/ownCloud/stable/2.11.1.8438/mac/ownCloud-2.11.1.8438.pkg`
Resulted into the same error.

**Comment by michaelstingl** [comment]
Thanks for reporting. Unfortunately, we weren't able to reproduce on our machines. This error occurs before ownCloud app starts, so the only way to investigate, is to check your system logs in the `Console.app`. Anything related to ownCloud in there?

**Comment by hannesa2** [comment]
I can give today evening my old laptop an addition try, I'll report the result ...

**Comment by michaelstingl** [comment]
@dschmidt @fmoc @TheOneRing @felix-schwarz any idea what Apple doesn't like about the installed `owncloud.app`? Why does this happen on @BaloMueller 's machine, but can't be reproduced?

**Comment by BaloMueller** [comment]
I was able to fix it 🥳
The key was to remove the Application from Applications folder. So: Dragging the owncloud.app to the trash bin.
After that, I just reinstalled the package from the website. Then it worked like a charm.

**Comment by hannesa2** [comment]
So you have to setup it again ?
At least for me, it's not an option. 

I get headache when I setup everything again on an update. This is just a sign of an error prone tool, I would defiantly avoid this.

**Comment by hannesa2** [comment]
> Please run spctl -a -vvvvv /Applications/ownCloud.app. What's the output?

<img width="484" alt="image" src="https://user-images.githubusercontent.com/3314607/200815419-1f6fb766-cf5f-4d4c-a435-122fab80c5db.png">

**Comment by hannesa2** [comment]
> so any change made after first launch will now also lead to a dialog showing the app as damaged.

Why ? I don't get the point

**Comment by hannesa2** [comment]
> Looks like macOS really sees a difference from what the code signature / notarization expects, then.

Exactly, there is something with the notarization

> A delete + reinstall from the .pkg as suggested ...

I already fixed it dirty as well https://github.com/owncloud/client/issues/10236#issuecomment-1308469882

anything else I can contribute is just a recall of 
https://github.com/owncloud/client/issues/10236#issuecomment-1308468249

**Comment by felix-schwarz** [comment]
FWIW I checked `ownCloud-2.11.1.8438.pkg` and it is properly signed and notarized:

```
Installer package signature info:
~/Downloads/ownCloud-2.11.1.8438.pkg: accepted
source=Notarized Developer ID
origin=Developer ID Installer: ownCloud GmbH (4AP2STM4H5)

pkgutil signature check:
Package "ownCloud-2.11.1.8438.pkg":
   Status: signed by a developer certificate issued by Apple for distribution
   Notarization: trusted by the Apple notary service
   Signed with a trusted timestamp on: 2022-08-31 11:21:38 +0000
   Certificate Chain:
    1. Developer ID Installer: ownCloud GmbH (4AP2STM4H5)
       Expires: 2024-01-29 10:35:51 +0000
       SHA256 Fingerprint:
           AD F3 16 BF DC 33 D2 87 AC B7 33 82 C1 67 C3 28 B4 27 70 0E BA 22 
           D4 10 DB C5 CE 16 83 C2 3B F3
       ------------------------------------------------------------------------
    2. Developer ID Certification Authority
       Expires: 2027-02-01 22:12:15 +0000
       SHA256 Fingerprint:
           7A FC 9D 01 A6 2F 03 A2 DE 96 37 93 6D 4A FE 68 09 0D 2D E1 8D 03 
           F2 9C 88 CF B0 B1 BA 63 58 7F
       ------------------------------------------------------------------------
    3. Apple Root CA
       Expires: 2035-02-09 21:40:36 +0000
       SHA256 Fingerprint:
           B0 B1 73 0E CB C7 FF 45 05 14 2C 49 F1 29 5E 6E DA 6B CA ED 7E 2C 
           68 C5 BE 91 B5 A1 10 01 F0 24
```

The `owncloud.app` it installs also passes all checks:

```
App path: /Applications/owncloud.app
app ID: com.owncloud.desktopclient
version: 2.11.1 (build 8438)
build: 2.11.1.8438
SDK version: [none]

Usage Descriptions:

Entitlements:

No property list returned.
App signature check:
/Applications/owncloud.app: accepted
source=Notarized Developer ID
origin=Developer ID Application: ownCloud GmbH (4AP2STM4H5)

codesign check:
Executable=/Applications/owncloud.app/Contents/MacOS/owncloud
Identifier=com.owncloud.desktopclient
Format=app bundle with Mach-O thin (x86_64)
CodeDirectory v=20500 size=22854 flags=0x10000(runtime) hashes=707+3 location=embedded
Hash type=sha256 size=32
CandidateCDHash sha256=0b0550aa6c4a57e3b53d6e60f21ea033c2888df4
CandidateCDHashFull sha256=0b0550aa6c4a57e3b53d6e60f21ea033c2888df4a942c6915860b60605763ead
Hash choices=sha256
CMSDigest=0b0550aa6c4a57e3b53d6e60f21ea033c2888df4a942c6915860b60605763ead
CMSDigestType=2
Launch Constraints:
	None
CDHash=0b0550aa6c4a57e3b53d6e60f21ea033c2888df4
Signature size=8926
Authority=Developer ID Application: ownCloud GmbH (4AP2STM4H5)
Authority=Developer ID Certification Authority
Authority=Apple Root CA
Timestamp=31. Aug 2022 at 13:21:30
Info.plist entries=16
TeamIdentifier=4AP2STM4H5
Runtime Version=12.3.0
Sealed Resources version=2 rules=13 files=476
Internal requirements count=1 size=188
```

Anecdotally, after upgrading to Ventura, macOS also reported Apple's own `SF-Symbols.app` as damaged to me and I had to reinstall it - even though I had never made any changes to it.

**Comment by hannesa2** [comment]
I observed this with _ownCloud_ and _Thunderbird_

**Comment by TheOneRing** [comment]
> I observed this with _ownCloud_ and _Thunderbird_

Only uninstall and reinstall. The configuration will be unaffected by an uninstall.

**Comment by hannesa2** [comment]
Let's assume it: The issue is not 100% understood why now this raises up, but there is a workaround
* either reinstall it
* or open in finder with control key to start it anyway

In both cases, the customer is bothered, and not everyone knows what to deal with it and will lead to little joy and frustration. Not everyone will search with understanding and benevolently seek a solution.

If you are happy with it you can close the ticket.

**Comment by hannesa2** [comment]
I brought me a new Mac and this issue still araise
