### ISSUE TITLE
[QA] Too many log files kept

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10230]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Too many log files are kept

### Steps to reproduce the issue

1. Go to Settings -> Log Settings  
2. Set 'Log files to keep' to 5
3. Make sure 6 log files get created (e.g. restart the client 6 times) 

### Screenshots

<img width="739" alt="Screenshot 2022-11-02 at 16 54 32" src="https://user-images.githubusercontent.com/49001702/199538083-c0a1913c-c33e-4f4b-ba3f-5e013f44589e.png">

### Expected behavior

5 files are kept in the log folder

### Actual behavior

6 files are kept in the log folder

**Comment by fmoc** [comment]
Fixed by #10344, please re-test.

**Comment by HanaGemela** [comment]
Passed in ownCloud 3.1.0.9307-daily20221209 on mac
