### ISSUE TITLE
[QA] ''You're all set!'' window can be closed without any warning

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10232]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

User wants to add a new account but after closing the ''You're all set!'' window, the account hasn't been added

### Steps to reproduce the issue

1. Click `Add account` in settings
2. Add server address
3. Login in WebUI
4. Click the Cross to close `You're all set` window

### Screenshots

<img width="719" alt="Screenshot 2022-11-04 at 11 46 33" src="https://user-images.githubusercontent.com/49001702/199956114-3d194a26-5f6d-4a68-bb1f-0d1ee9071072.png">

### Expected behavior

Either:
There's a pop-up with warning that the actions will not be saved and user is prompted to confirm his decision 

or: 
The cross behaves like the Finish button and the account is saved like the 'You're all set" description suggest

@michaelstingl please decide

### Actual behavior

The windows gets closed without a warning and the account hasn't been added

**Comment by jnweiger** [comment]
Reproduced on 3.0.0-beta.1

The issue is not about having or hiding a close button. It is about a false expectation induced by "You are all set", when the user actually has not set up anything, unless he also presses the "Finish" button.

I suggest to change the text to "You are all set. Press 'Finish' to start syncing." :see_no_evil:

**Comment by jnweiger** [comment]
![grafik](https://user-images.githubusercontent.com/1108546/201330880-8387adcd-bdec-4482-9be1-6b3f823c06fe.png)

While working in the Advanced configuration, it is obvious, that the "You are all set!" info is premature.

**Comment by TheOneRing** [comment]
Not a bug.

**Comment by jnweiger** [comment]
Problems in the UX design are by definition "Works as designed" -- so, I understand, that they cannot qualify as "bug" here.
That is unfortunate, as I see no other way to address them. If we just close here, it will be forgotten and won't see improvement, right? @michaelstingl do you have an idea, how to report such issues properly?
