### ISSUE TITLE
[QA] run UI tests with ocis backend in CI

### ISSUE THREAD

**Issue by individual-it** [owncloud/client#10249]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

currently the CI runs the UI tests only with oc10, they also should run with ocis

### Steps to reproduce the issue

NA

### Screenshots

NA

### Expected behavior

NA

**Comment by saw-jan** [comment]
This has been implemented with PR https://github.com/owncloud/client/pull/10261
