### ISSUE TITLE
[QA] Spaces: Disabled space is not deleted locally

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10257]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Disabled space is not deleted locally
 mac 3.0.0 beta1
ocis 2.0.0 rc1

### Steps to reproduce the issue

1. Add a space in the desktop client
2. Disable the space in webUI
3. Sync the space in the desktop client

### Screenshots

<img width="1050" alt="Screenshot 2022-11-10 at 10 07 22" src="https://user-images.githubusercontent.com/49001702/201049165-35395770-6ad1-4c45-9deb-48e8a663714d.png">

### Expected behavior

Consequence of a disabled space: The desktop client will delete the contents of that space locally
https://github.com/owncloud/ocis/issues/4316

### Actual behavior

The desktop client doesn't delete the contents of that space locally

**Comment by michaelstingl** [comment]
Works as designed. No concept how to deal with deleted or disabled Spaces in desktop and mobile apps yet.

**Comment by michaelstingl** [comment]
Docs issue:
- https://github.com/owncloud/docs-client-desktop/issues/320

**Comment by michaelstingl** [comment]
Docs updated:
> When a space gets disabled or deleted via the Web UI, no data is deleted locally.

(see https://doc.owncloud.com/desktop/4.2/using.html#spaces)
