### ISSUE TITLE
[QA] Remove all files dialog, does not delete excluded folders

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10253]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

When user removes all the files in the client, the files get synced back to the client instead of deleting them on the server.
mac client 3.0.0 beta1
ocis 2.0.0 rc1

### Steps to reproduce the issue

1. Create a Space on the server with files bigger than 500MB (this is important, works fine with small files)
2. Sync the Space to the client
3. Rename the Space folder in the Finder 
4. Create a new folder with the name of Space in the Finder
5. Confirm that you want to delete all the files

### Screenshots

<img width="820" alt="Screenshot 2022-11-09 at 12 59 14" src="https://user-images.githubusercontent.com/49001702/200828520-b87cfaf1-c5b9-4e4a-8350-49525df99d3b.png">

### Expected behavior

The files have been deleted on the server

### Actual behavior

The files have been synced back to the client

**Comment by TheOneRing** [comment]
Is the space read only?

**Comment by TheOneRing** [comment]
Also does this only happen with spaces? Sounds more like something related to ask for confimation before syncing large folders.

**Comment by roshanlc** [comment]
**On Ubuntu 22.04.1 LTS, works as expected.**
***
**On Windows 10, the space folder is prevented from being renamed as shown in the following screenshot.**
`Error 0x8007018B: Access to the cloud file is denied.`

![unable-to-rename-folder-from-explorer](https://user-images.githubusercontent.com/6222781/204239305-f3ccb5d1-4a30-4bf8-a2da-1888425223a6.png)

**Comment by TheOneRing** [comment]
renaming sync roots is not supported, you can achive the same by closing the client and deleting all files from the sync root, including the db.
So this issue is not about SPACES its about the everything was deleted do you wan't to delete .... dialog....

**Comment by michaelstingl** [comment]
Assumption:
- It's only about deletion of unsynced files (files in folder > 500 MB or what the user configured)

@HanaGemela could you verify?
