### ISSUE TITLE
AppImage version numbers should be more specific

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#10252]
Right now, the version numbers embedded in the AppImage are relatively short (e.g., just `2.11.0`, `3.0.0`). AppImages allow the use of multiple versions in parallel. In order to be able to distinguish between these in the application launcher, we should embed the full version numbers including the build number (e.g., `3.0.0-beta1.9006`).

**Comment by fmoc** [comment]
Looks like this needs to be changed in `craft` directly. I am not sure whether we can pass a suitable version number to `craft --package`. CC @TheOneRing

**Comment by TheOneRing** [comment]
![grafik](https://user-images.githubusercontent.com/200626/201043221-4017a05d-283d-4c2b-896b-c12cc61abde3.png)
https://download.owncloud.com/desktop/ownCloud/testing/3.0.0-beta1.9005/linux-appimage/
?

**Comment by fmoc** [comment]
Current builds contain a version like `3.0.0.9006`, which is better but still doesn't reveal whether a build is a beta, RC, daily...

**Comment by fmoc** [comment]
Should be fixed by https://github.com/owncloud/craft-blueprints-owncloud/commit/63a39d9326a3766e93cd7da5cf16b27d82717e6a.

**Comment by michaelstingl** [comment]
@fmoc where is this user-facing? What/where could testers check?

**Comment by TheOneRing** [comment]
Lets update the file name.

**Comment by fmoc** [comment]
Fixed: `testpilotcloud-3.1.0.9986-daily20230202-x86_64.AppImage`

**Comment by saw-jan** [comment]
Daily build: `testpilotcloud-3.2.0.10137-daily20230213-x86_64.AppImage`
RC: `testpilotcloud-3.2.0.10080-rc1-x86_64.AppImage`

:heavy_check_mark: Looks good
