### ISSUE TITLE
[Testpilotcloud] Update channel warning does not reset dropdown selection

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#10251]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When changing the update channel in the settings, a dialog will pop up informing about the consequences. If the dialog is aborted, the selection in the dropdown is not reset.

The selection can be reset manually without triggering a new dialog.

### Expected behavior

When aborting a dialog like this, the original state should be restored.

### Steps to reproduce the issue

Change the update channel from "beta" to "stable" for instance.

### Client version number

3.0.0-beta1 build 9006 on Ubuntu 22.04

**Comment by TheOneRing** [comment]
Can't reproduce on Windows.

**Comment by fmoc** [comment]
Reproduced on Ubuntu 22.04 with the latest AppImage:

```
testpilotcloud 3.2.0.10137-daily20230213 c03e01
Qt Bibliotheken 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
verwenden die Erweiterung für virtuelle Dateien: suffix
ubuntu-5.15.0-56-generic
```

**Comment by fmoc** [comment]
Turns out the issue is localization. The settings dialog sets the entry by string and also uses string comparison to configure the current channel. When, e.g., using a German locale, the strings change from "stable" to "Stabil" and "beta" to "Beta", breaking the code. Using numeric indices to change back to the original value fixes the problem.

**Comment by Salipa-Gurung** [comment]
Version : ` testpilotcloud 4.0.0.10477-daily20230322 bb5d97 `  
|Reproduced on |Ubuntu 22.04.2 |  Windows 10 pro |
|--|--|--|
| Initial channel: `beta`| ![Screenshot from 2023-03-22 11-25-11](https://user-images.githubusercontent.com/53458341/226825630-3dce8dd3-28c3-41c9-9f29-c81a0de24392.png) | ![Screenshot from 2023-03-22 11-16-03](https://user-images.githubusercontent.com/53458341/226825804-dc18bfc7-80e1-41d1-9a38-3db2292bb691.png) |
| Aborting dialog | ![Screenshot from 2023-03-22 11-25-23](https://user-images.githubusercontent.com/53458341/226827039-3483023e-417f-4ab6-bc5f-5bd91e33d198.png) | ![Screenshot from 2023-03-22 11-16-54](https://user-images.githubusercontent.com/53458341/226827102-4d73456f-f87a-4e4d-b276-9ea2255e85f4.png) |
| dropdown selection changed to: `stable`| ![Screenshot from 2023-03-22 11-25-35](https://user-images.githubusercontent.com/53458341/226827256-12beeb0c-5975-4326-a8a7-708bd577f7b9.png) | ![Screenshot from 2023-03-22 11-17-09](https://user-images.githubusercontent.com/53458341/226827300-6691fe38-0c96-449f-a55d-4bf8056673a6.png) |
| | initial state is not restored :x: | initial state is not restored :x: |
> Same behaviour shown while selecting update channel from stable to beta and aborting dialog 

CC: @fmoc @TheOneRing @HanaGemela

**Comment by fmoc** [comment]
Please test with a non-English locale.

**Comment by Salipa-Gurung** [comment]
After changing language to Deutsch, dropdown selection is not resetting after aborting dialog box :x: 
|![Screenshot from 2023-03-22 15-05-34](https://user-images.githubusercontent.com/53458341/226860569-1f133eb2-2f1f-4043-bf5e-f4cf29d2d55c.png)|![Screenshot from 2023-03-22 15-05-45](https://user-images.githubusercontent.com/53458341/226860616-158ce035-bad1-433e-aec0-8123be435154.png)|![Screenshot from 2023-03-22 15-06-02](https://user-images.githubusercontent.com/53458341/226860652-77a1fd96-4e4f-438a-a094-0c2df95eed9f.png)|
|--|--|--|

**Comment by fmoc** [comment]
Confirmed; worse than before, en locale is broken as well.

**Comment by fmoc** [comment]
Fix provided in https://github.com/owncloud/client/pull/10627.

**Comment by saw-jan** [comment]
Tested with `testpilotcloud 4.0.0.10610-daily20230411 a8eb35`

![Screenshot from 2023-04-11 16-08-28](https://user-images.githubusercontent.com/52366632/231132737-e4503f1d-06bc-4118-a541-da6b6b2a8b28.png) | ![Screenshot from 2023-04-11 16-08-22](https://user-images.githubusercontent.com/52366632/231132733-5d483a4f-41a0-4bdc-b119-1c61277ad409.png) | ![Screenshot from 2023-04-11 16-08-15](https://user-images.githubusercontent.com/52366632/231132727-05217b39-8840-4f28-9fce-f55c6cfdb0b7.png)
--|--|--
Default state | Change the channel and Cancel | Reverts to previous state :heavy_check_mark:
