### ISSUE TITLE
Folder Sync Icons not showing in MacOS

### ISSUE THREAD

**Issue by sndbbbl** [owncloud/client#10250]
## Describe the bug

When syncing ownCloud folders / files, one expects that there are Folder / File sync icons showing the sync status
![image](https://user-images.githubusercontent.com/14177299/200761821-e7879689-a4f0-4a10-9517-6601971e4f9b.png)

in MacOS there are several SYSTEM PREDEFINED folders (i.e. Desktop, Documents, Downloads, ...). These usually are folder which have a different ICON than other folders:

![image](https://user-images.githubusercontent.com/14177299/200763012-5dc39e3a-4159-4999-9169-26ab45aa8ea3.png)

If one of these folders is being used as an ownCloud sync, then the Folder / File sync icons do not show.

## Steps to reproduce

1. Create Folder Sync with a Folder (or Subfolder) of a MacOS System Predefined folder (i.e. Documents, Desktop, Downloads, Photos, Music, ...)
2. Let ownCloud perform the sync
3. No FOLDER SYNC ICONS appear
4. Create Folder SSync with a folder which is not one of the MacOS Predefinde folders, and also not a subfolder thereof
5. Let ownCloud sync
6.Folder Sync icons will show up as expected.

## Expected behavior

It is expected that any folder which is chosen to be synced with ownCloud (also system predefined folders) will show the FOLDER SYNC STATUS ICONS... same as for DropBox or other syncing apps.

## Actual behavior
Right now, the folder sync icons only show when the folder is NOT A SYSTEM SPECIFIC PREDEFINED FOLDER...
![image](https://user-images.githubusercontent.com/14177299/200767595-169c35e2-463d-4bcd-9b52-1af64ede823e.png)

## Setup

Client: MacBookPRO, Apple M1, MacOS Venture 13.0
ownCloud client: Version 2.11.1 (build 8438)

Host: Version 10.6.0 (stable)

**Comment by sndbbbl** [comment]
> @michaelstingl @TheOneRing FYI

Hi，any update/progress on this? Just sending this msg to prevent this issue from closing automatically...

**Comment by TheOneRing** [comment]
@erikjv can you have a look?
I assume apple doesn't want us to change the icon, maybe it is documented somewhere.

**Comment by sndbbbl** [comment]
> @erikjv can you have a look? I assume apple doesn't want us to change the icon, maybe it is documented somewhere.

I guess it is possible. I have another computer where I am running BoxCryptor. BoxCryptor always shows without error the status (encrypted / not enxcrypted) in an icon behind the file.

![Screenshot 2023-01-19 at 10 49](https://user-images.githubusercontent.com/14177299/213412181-daccbfa3-d474-4fd6-87fb-0d8cec7d40b1.jpg)

ownCloud status icons show up sometimes, and other times they do not show up. I could not find out the situation when it shows up and when it does not show up...

**Comment by sndbbbl** [comment]
> @erikjv can you have a look? I assume apple doesn't want us to change the icon, maybe it is documented somewhere.

Made some further testing. Is it possible that the DEFAULT folders of MacOS (i.e. DOCUMENTS, MUSIC, Pictures, ... all the photos that are there already in MacOS and have a special pictogram in the folder ICON) have difficulties with the ownCloud status ICON?

I realized that folders created by the user ALWAYS show the ownCloud STATUS icons, while the DEFAULT FOLDERS sometimes show them, most of the times not...
![ownCloud Status Icons 2](https://user-images.githubusercontent.com/14177299/213549545-fda4832f-9f70-4930-9535-4a3f5bacdaab.jpg)
![ownCloud Status Icons](https://user-images.githubusercontent.com/14177299/213549555-a1cca1f4-a4b8-4285-b9df-f9693821e89f.jpg)

**Comment by erikjv** [comment]
I can reproduce this. We do set the badge for these folders, but they seem to be ignored. I posted a question on the Apple dev forums about this: https://developer.apple.com/forums/thread/729720 .

**Comment by sndbbbl** [comment]
There seems to be an improvement on this matter from Apple - all folders who the sync status now, also the "dedicated macOS folders", except the Documents folder itself. Desktop, Downloads, etc. and the subfolders of Documents show the sync status now, except the Documents folder itself...

So this is a big improvement to what was there before...
