### ISSUE TITLE
[macOS] "Start on Login" setting also re-starts after quitting the client

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10269]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Enabling "Start on Login" setting also re-starts after quitting the client

### Expected behavior

Also when "Start on Login" is enabled, users should be able to quit the ownCloud client. Only next system restart or login should bring it up again.

### Steps to reproduce the issue

1. Install [`ownCloud-3.0.0-beta1.9005-x86_64.pkg`](https://download.owncloud.com/desktop/ownCloud/testing/3.0.0-beta1.9005/mac/ownCloud-3.0.0-beta1.9005-x86_64.pkg) on virgin macOS Ventura 13.0.1 (M1)
2. Install Rosetta2 when asked
3. Open `owncloud.app` and configure account `admin:admin@demo.owncloud.org` with default settings
  ==> macOS notification "Background Items Added" is shown
4. Restart macOS
  ==> `owncloud.app` starts automatically ✅ 
5. Quit `owncloud.app`
  ==> `owncloud.app` re-starts automatically ⚠️
6. Disable "Start on Login" in Settings
7. Quit `owncloud.app`
  ==> `owncloud.app` re-starts automatically ⚠️
8. Restart macOS
9. Open `owncloud.app`
10. Quit `owncloud.app`
  ==> `owncloud.app` doesn't re-start automatically ✅
11. Open `owncloud.app`
12. Enable "Start on Login" in Settings
13. Restart macOS
  ==> `owncloud.app` starts automatically ✅ 
14. Quit `owncloud.app`
  ==> `owncloud.app` re-starts automatically ⚠️

### Screenshots

<img width="508" alt="CleanShot 2022-11-11 at 12 36 42@2x" src="https://user-images.githubusercontent.com/214010/201336326-5ef8b4e9-94df-4f84-836b-2c1770d7b461.png"> | <img width="438" alt="CleanShot 2022-11-11 at 12 36 58@2x" src="https://user-images.githubusercontent.com/214010/201336343-611fec8b-f2a5-4e8f-b7fc-bd5f8180bd32.png">
-- | --

### Client version number

```
ownCloud 3.0.0.9005-beta1 6b12ec
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-22.1.0
```

### Server information

No server needed

**Comment by michaelstingl** [comment]
I think I saw the same with macOS 12, only the "Background Items Added" is new in 13

**Comment by michaelstingl** [comment]
When "Start on Login" is disabled, there is no `~/Library/LaunchAgents/com.owncloud.desktopclient.plist` ✅

**Comment by erikjv** [comment]
Please verify if https://github.com/owncloud/client/pull/10279 fixes this issue.

**Comment by michaelstingl** [comment]
> Please verify if #10279 fixes this issue.

Yes, I can confirm the fix 👍 

```
ownCloud 3.0.0.9105-daily20221115 461419
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-22.1.0
```
