### ISSUE TITLE
Windows VFS: Detect long path and the lack of windows opt in and add a display a warning

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10264]
Add check to vfs setup whether we opted in to https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry#enable-long-paths-in-windows-10-version-1607-and-later when the path is  > 260 chars.

Related: https://github.com/owncloud/client/pull/10136

**Comment by TheOneRing** [comment]
See https://github.com/owncloud/client/blob/5e3ec66d9dca60775732d39a975b22a001f07457/src/gui/folder.cpp#L200-L200

**Comment by enbrnz** [comment]
Does this mean long file paths are going to be support with client version 3?
If yes, is it restricted to VFS or generally supported?

**Comment by TheOneRing** [comment]
3.0 supports long path in general, but for vfs there are extra steps to be taken.

**Comment by erikjv** [comment]
> See
> 
> https://github.com/owncloud/client/blob/5e3ec66d9dca60775732d39a975b22a001f07457/src/gui/folder.cpp#L200-L200

But isn't this only called for the sync folder? Should we also check it for every directory we receive from the server, before trying to create it?

Actually, can you even have (and select) a folder with >260 chars on a Windows system that doesn't have this support turned on?

**Comment by TheOneRing** [comment]
At this point we only care for the sync root, if the path is too long we can't register t as cfapi root, without that windows option being enabled.

**Comment by HanaGemela** [comment]
Crash when adding `C:\Users\hana\ownCloudalotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\ - [demo@demo.owncloud.com](mailto:demo@demo.owncloud.com)`
as a local path, VFS on, long path off: `6c31aa65-fa20-4a44-b369-38b6a03fcc56`
ownCloud-4.0.0.10576-daily20230405.x64.msi

**Comment by HanaGemela** [comment]
Tested blocked by https://github.com/owncloud/client/issues/10668

**Comment by HanaGemela** [comment]
@TheOneRing Message is displayed for both VFS and non VFS as well, that's intended? ownCloud-4.0.0.10581-daily20230405, windows

**Comment by TheOneRing** [comment]
Yes its a Windows thing unrelated to vfs

**Comment by HanaGemela** [comment]
Passed
