### ISSUE TITLE
[QA] Last deleted Share remains present locally 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10278]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

When all shares are deleted on the server, user gets an option to keep the files locally 
mac client 3.0.0 beta2
ocis 2.0.0 rc1

### Steps to reproduce the issue

1. Accept a share
2. Sync it to the client
3. Decline a share 
4. Sync the client
5. Select 'Keep files' in the client 

### Screenshots

<img width="422" alt="Screenshot 2022-11-14 at 11 30 38" src="https://user-images.githubusercontent.com/49001702/201638390-51d8879a-e6ac-496f-aaed-8051eec65782.png">

### Expected behavior

Declined shares are deleted from the desktop client. User isn't offered an option to keep them

### Actual behavior

Declined shares are kept locally when user chooses to keep them

**Comment by michaelstingl** [comment]
Nothing to do in the desktop client. Waiting for the backend change:
- https://github.com/owncloud/ocis/issues/5190

**Comment by saw-jan** [comment]
Tested with desktop-client `ownCloud 4.0.0.10422-daily20230316 8e8490`

Expected: :x: User isn't offered an option to keep them

And the shared file/folder remains if we choose `keep files` option

![Screenshot from 2023-03-16 12-00-19](https://user-images.githubusercontent.com/52366632/225531498-e0e683da-6780-49fa-83c3-f2bc1a938dc1.png)

CC @TheOneRing @michaelstingl

**Comment by michaelstingl** [comment]
> When all files are removed on the server this is to be expected.

yes 👍

**Comment by TheOneRing** [comment]
What no longer should happen is that the folder reports an error.
This was however a server issue which is supposed to be fixed, so I'd say no testing needed at least not on the client side.
