### ISSUE TITLE
[QA] Space in not renamed in the client

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10284]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Space in not renamed in the client

### Steps to reproduce the issue

1. Add a new space in the desktop client
2. Rename the space in web ui
3. Sync the changes to the client

### Screenshots

No screenshot

### Expected behavior

Space has been renamed in the client

### Actual behavior

Space hasn't been renamed in the client

**Comment by michaelstingl** [comment]
Works as designed. Needs documentation.
