### ISSUE TITLE
[QA] Exmembers have spaces saved locally

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10285]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Exmembers have spaces saved locally

### Steps to reproduce the issue

1. Admin creates a space
2. Shares it with Emma
3. Emma syncs space in the desktop client
4. Admin removes Emma from members in web ui 

### Screenshots

No screenshot

### Expected behavior

Space has been deleted locally

### Actual behavior

Space is not synced anymore but not deleted locally

**Comment by TheOneRing** [comment]
Deleting spaces locally is not supported. 
Duplicate: #10257
