### ISSUE TITLE
[QA] Client renames files and folders with slash in the name

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10287]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Client renames files and folders with slash in the name

### Steps to reproduce the issue

1. Create a folder called `/`
2. Check the name on the server

### Screenshots

<img width="705" alt="Screenshot 2022-11-16 at 13 09 45" src="https://user-images.githubusercontent.com/49001702/202177318-cbc12969-5315-42c6-a1ff-5732d0bf882e.png">

### Expected behavior

User has been informed about the name change or folder with such name as been ignored etc. @michaelstingl please specify

### Actual behavior

Folder has been renamed to `:` 
Probably introduced by commit 4ad165ce26f1a26ac30b7ac92ffc5266443485f0

**Comment by michaelstingl** [comment]
This has always been the case in ownCloud on Mac. It's caused by a macOS or Finder problem:
https://alexwlchan.net/2021/12/slashes/


<img width="703" alt="CleanShot 2022-11-16 at 13 15 36@2x" src="https://user-images.githubusercontent.com/214010/202178340-14cd63ab-eb9e-49d3-947b-24ca7dd0eb61.png">
