### ISSUE TITLE
[QA] client 3.0.0 dereferences symbolic links

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10281]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen with testpilotcloud 3.0.0.9000-daily20221104

* Use a Linux or Mac client to connect to demo.owncloud.org
* Wait for the initial sync to finish

![grafik](https://user-images.githubusercontent.com/1108546/201874196-3a07e213-4dcd-4489-b643-019f955661f6.png)

* Use a shell to go to the local sync folder `cd "testpilotcloud - demo@demo.owncloud.org"`
* `ln -s "Learn more about ownCloud" symlink`
* The 3.0.0 client syncs another copy of that folder. (2.11.x would complain that symlinks are not supported). BAD

![grafik](https://user-images.githubusercontent.com/1108546/201874387-aab1462d-3caa-4990-9b33-9b6636ac16eb.png)

* `ln -s ~/Music .`
* The 3.0.0 client now syncs my Music folder, which is outside of the sync folder. It can even delete files there. BAD.

![grafik](https://user-images.githubusercontent.com/1108546/201875224-6796e0e0-d6a7-4aac-8dca-74636c4a1e50.png)

* `cd Documents; ln -s ../Documents .`
* A recursive symlink is also recursively dereferenced, client and server become very busy.

![grafik](https://user-images.githubusercontent.com/1108546/201875717-19b33bfd-aa1b-4a48-acbc-d35f3fd4ff45.png)

Expected behaviour:
* either ignore symbolic links as with 2.11.x (but don't flag them an error please)
* or implement symbolic links completely, including
   - in tree symlink is stored as a new object type, (not full copy)
   - out of tree symlinks are ignored.

**Comment by jnweiger** [comment]
Confirmed fixed in testpilotcloud 3.0.0.9132-daily20221118

![grafik](https://user-images.githubusercontent.com/1108546/202667408-64bd55ee-5069-4f4b-be9b-07178f18cb8b.png)

**Comment by roshanlc** [comment]
Works as expected in build ownCloud-3.0.0-daily20221125.9173

![ownCloud-3 0 0-daily20221125 9173-x86_64](https://user-images.githubusercontent.com/6222781/203954504-27a77924-5265-4452-8713-8815b60d310e.png)
