### ISSUE TITLE
Escape Gtk 3.0 bookmarks correctly

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#10280]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Currently, our Gtk 3.0 bookmark generation does not escape new entries correctly. This causes a variety of issues, as documented in #9752. On MATE, this even prevents the entries from being displayed at all.

### Expected behavior

We should URL-escape the entries we add.

### Steps to reproduce the issue

Run any of the distros mentioned in #9752.

### Client version number

3.0.0-beta1/2 or any recent daily.

### Additional context

Follow-up from #9752.

**Comment by fmoc** [comment]
Fixed by #10309.

**Comment by jnweiger** [comment]
I don't think, we currently handle the bookmarks file format correctly. 
With my Cinnamon, the file seems to split at the first whitespace in each line, see https://github.com/owncloud/client/pull/9752#issuecomment-1327246076 and following.

**Comment by HanaGemela** [comment]
@fmoc I've moved the issue back to dev
