### ISSUE TITLE
[QA] Not enough information about ignored files in Activity tab

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10286]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Not enough information about ignored files in Activity tab - missing account and file/folder name

### Steps to reproduce the issue

1. In the client create a folder called `~`
2. Check `Not synced` in Activity tab

### Screenshots

<img width="756" alt="Screenshot 2022-11-16 at 13 00 17" src="https://user-images.githubusercontent.com/49001702/202175664-dbf2a359-4443-4f74-9c8a-b7695bd2f701.png">

### Expected behavior

Folder name is specified and also the account 

### Actual behavior

No file/folder name, no account stated. Also folders are called files

**Comment by TheOneRing** [comment]
Please reizse the table header.
![grafik](https://user-images.githubusercontent.com/200626/202235680-e90670d5-153f-455b-bd96-c3f52ed1d1ad.png)

**Comment by HanaGemela** [comment]
Wow, shouldn't there be some hint? Like arrows showing there is more hidden somewhere? or just show the entire table by default? or not allow user to drag the column size behind the gui?

**Comment by HanaGemela** [comment]
@michaelstingl I'd fix it. At least it is not user friendly

**Comment by TheOneRing** [comment]
The default should display all columns. But if you resize a coulmn it saves the state.
