### ISSUE TITLE
Provide Linux packages for Fedora 37

### ISSUE THREAD

**Issue by ivnmad** [owncloud/client#10291]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Upgraded from Fedora 36 to Fedora 37.
ownCloud fails to update client to v2.11.1 via ownCloud repository because of libicu-69 dependency, while Fedora 37 has libicu-71 instead.

### Expected behavior

Update to v2.11.1 by supporting libicu-71 via ownCloud repository

### Screenshots

![Screenshot from 2022-11-16 22-02-28](https://user-images.githubusercontent.com/35845319/202304138-2265f8d9-da58-4dda-ba43-9cb0b25dc9f3.png)

**Comment by michaelstingl** [comment]
As a workaround, you can run the AppImage.

**Comment by fmoc** [comment]
You are trying to use the Fedora 36 repository on Fedora 37, apparently. This is not going to work. We're looking into providing a Fedora 37 repository for the upcoming 3.0 release.

**Comment by ivnmad** [comment]
@michaelstingl thank you for the suggestion, but luckily the ownCloud client installation from Fedora 36 is still working, so the issue is only the upgrade.

@fmoc got you..
I shouldn't need to update the repository manually and it should update automatically, like for any other repository, including external ones to the distribution. As mentioned above, because it was an upgrade the "old" Fedora ownCloud client installation is still working.

**Comment by fmoc** [comment]
We don't even provide packages for Fedora 37 at this point, so any form of auto upgrade can't work. Working on it, as said.

**Comment by SurvivaLlama** [comment]
> As a workaround, you can run the AppImage.

The AppImage does not install on F37.

**Comment by fmoc** [comment]
A bit of nitpicking, but you do not have to install AppImages. You can just run them. It's running fine here. Please open a new issue if you disagree.

**Comment by SurvivaLlama** [comment]
Well now I feel dumb. What do you do to run it? I can't figure it out.

**Comment by fmoc** [comment]
Please see .https://doc.owncloud.com/desktop/2.11/installing.html#appimage.

**Comment by fmoc** [comment]
The final 3.0 release will be available shortly and feature native Fedora 37 packaging.

**Comment by TheOneRing** [comment]
Will be in 3.1 due to ci issues.

**Comment by TheOneRing** [comment]
In the meantime you can give the 3.0.0 Appimage a try https://github.com/owncloud/client/releases/tag/v3.0.0 it is now fully supported including auto updates.

**Comment by JoKalliauer** [comment]
I solved the issue using the commands from https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/


```
sudo rpm --import https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Fedora_37/repodata/repomd.xml.key
sudo dnf config-manager --add-repo https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Fedora_37/owncloud.repo
sudo dnf clean all
sudo dnf install owncloud-client
sudo dnf upgrade owncloud-client
sudo dnf update
```
