### ISSUE TITLE
Cannot close OAuth login dialog after retry

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#10300]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When using the retry feature to retry after an error, the dialog is not closed when logging in successfully.

Note that failed logins correctly lead to a new error message as expected. This only affects successful logins after at least one retry.

### Expected behavior

The dialog should close automatically when logged in successfully.

### Steps to reproduce the issue

1. Connect to account using OAuth/OIDC
1. Log out of accout
1. Log in again
1. In the dialog, make sure you need to retry (e.g., by supplying incomplete credentials on the server)
1. Log in with the correct username

### Client version number

Current 3.0 branch

### Additional context

Follow-up from #9772.

**Comment by PrajwolAmatya** [comment]
### Step to reproduce
1. Connect to an oc10 server with oauth2 as admin
2. Log out in the client
3. Start login process in the client
4. Open the browser
5. Log in with demo (demo existing user)

Logging with the `demo` shows the error in browser

![Screenshot from 2022-11-28 11-31-16](https://user-images.githubusercontent.com/83579989/204204043-8192bd48-aaf6-4fe2-a9c5-ff4fcc910273.png)

but the dialog box on the client doesnot show the retry button
![Screenshot from 2022-11-28 11-32-35](https://user-images.githubusercontent.com/83579989/204204215-ff0bda88-d8e6-4953-86c4-42c970645bd7.png)

again logging with the correct user in the browser shows the message
![Screenshot from 2022-11-28 11-33-58](https://user-images.githubusercontent.com/83579989/204204391-1775c958-3743-4560-8d8a-77ada5a93c36.png)

user doesnot login and must log out from desktop client and login again


Logs: [ownCloud.log](https://github.com/owncloud/client/files/10100947/ownCloud.log)

**Comment by PrajwolAmatya** [comment]
With ocis:
1.  Connect with ocis server with oauth2 as admin
2. Log out in the client
3. Start login process in the client
4. Open the browser
5. Log in with einstein

Logging with `einstein` shows the error in the browser
![Screenshot from 2022-11-28 12-02-04](https://user-images.githubusercontent.com/83579989/204208194-0ba86284-5e70-4785-a02f-e94d339c6025.png)

and desktop client show the retry option
![Screenshot from 2022-11-28 12-02-23](https://user-images.githubusercontent.com/83579989/204208441-068a92e1-35ee-4329-a4ba-4a39056d44aa.png)

after retry and logging with the `admin`, logging in is successful and the dialog box on the desktop client closes automatically
![Screenshot from 2022-11-28 12-13-30](https://user-images.githubusercontent.com/83579989/204208794-2b72f2e2-097e-4292-826f-64f95d1fba01.png)

**Comment by individual-it** [comment]
@fmoc I think is still an issue with oc10 ^

**Comment by fmoc** [comment]
There doesn't seem to be any interaction with the client, the server generates this error message. This makes sense, as the client suggests the server it wants a login as `demo`.

Consider this scenario:
- try to log into an account for `demo` again
- in the browser, edit the URL opened by the client replacing `&login_hint=demo&user=demo` with `&login_hint=admin&user=admin`
- log in as `admin` instead of `demo` and click on "Authorize"

In this scenario, the client correctly reports the failure and suggests a retry. Retrying with correct credentials works.

Seems to me like the server is trying to be too smart here (which would hint that this might have been an issue with older clients, too; I'll test some older daily next).

A short term fix is to just remove the `user` query string parameter from the URL, giving the server no chance of handling such problems server-side (`login_hint` is OIDC according to our code, whereas `user` is oC10 (probably refers to oC10's OAuth2)). This method seems to work reliably, and is just a one-liner change. In the long run, to fix this properly, we'd need to make the server redirect back to the client in such cases so it can recognize the problem at all. I think this will be overengineering, though, given the fact that oCIS is soon going to be released (and also, there is no server-side handling of users logging in with the wrong username either).

I'll finish my testing and send a PR.

**Comment by fmoc** [comment]
Yep, same behavior in testpilotcloud `3.0.0.9006-beta1`. This is not a regression introduced by #10305, this is a general issue with oC10 that has been there for a long time. Please open a new issue.

**Comment by individual-it** [comment]
moved to the oauth2 app https://github.com/owncloud/oauth2/issues/347
