### ISSUE TITLE
MacOS: Autosrtart migration fails

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10302]
Test failed

1. Install 2.11.1, make sure Start on login is checked 
2. Update to 3.0.0.9153-daily20221122

Start on login is not checked after the update.

_Originally posted by @HanaGemela in https://github.com/owncloud/client/issues/9800#issuecomment-1323482517_

**Comment by erikjv** [comment]
Fixed in https://github.com/owncloud/client/pull/10307

**Comment by HanaGemela** [comment]
Fixed in 3.0.0 rc2
