### ISSUE TITLE
[QA] Crash at startup, trying to find vfs plugin

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10318]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen on Linux Mint 20.3 (based on Ubuntu 20.04 with the deb package:
```
⏚ [testy:~] $ owncloud --version
gui.platform: Core dumps enabled
ownCloud ownCloud 3.1.0.9175-daily20221125
https://github.com/owncloud/client/commit/0fbaf515aa67e3265a2309ed2033061af53f5e6e
Libraries Qt 5.15.2, OpenSSL 1.1.1f  31 Mar 2020
Using virtual files plugin: off
linuxmint-5.4.0-132-generic
⏚ [testy:~] $ owncloud -s
gui.platform: Core dumps enabled
Aborted (core dumped)
⏚ [testy~] 134 $
```

The debug log ends with
```
...
11-25 10:45:49:385 [ info gui.application ]:	Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
11-25 10:45:49:386 [ info gui.folder.manager ]:	Setup folders from settings file
11-25 10:45:49:387 [ critical plugins ]:	Could not load plugin: not existant or bad metadata "owncloudsync_vfs_off"
11-25 10:45:49:387 [ fatal default ]:	Could not load plugin
Aborted (core dumped)
```

Does not happen with daily 3.0 or good old 2.11

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

No crash.

### Actual behavior

Crash.

**Comment by TheOneRing** [comment]
Patch was not yet merged back to master
