### ISSUE TITLE
Desktop client ignore New Folder created

### ISSUE THREAD

**Issue by mbhkoay** [owncloud/client#10316]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Would like to see a feature to ignore empty folders name New Folder. 
The reason being everytime a new folder is created in windows, and while the folder is still being renamed, it is picked up by the client and synced to the server. This does not happen every time though. 

### Proposed solution

Was thinking to put the name into the ignored list, but not sure if that is a good idea to ignore all folders name New Folder as the remaining of the office users might have folders not named properly sometimes. (Understand that this is a user problem and not a software issue - just putting it out here)

### Alternative solutions you considered

The proposal where a delay can be determined before the sync starts for certain / all files seems like a great solution for this situation. [https://github.com/owncloud/client/issues/3935](url)
Have used Goodsync extensively in the past and it was very handy to be able to set a custom delay for a specific sync folder before the sync happened.

### Additional context

Have searched was surprised to not find other people facing this same issue, hence creating this topic. Any other input is appreciated.

**Comment by TheOneRing** [comment]
We can't just ignore "New Text File.odt" or "New Folder", this has too many implications, people can actually put data in a "New Folder" also it relies on the system language.

For files we already ensure that the file wasn't touched for a certain time frame.

**Comment by TheOneRing** [comment]
Also what is the problem with creating an empty folder on the server and renaming it?

**Comment by jnweiger** [comment]
Specifying a sync delay for some name patterns seems to be a useful option.

But I also don't see it as a problem. When the user finally renames their file or folder, so does the desktop client. And everything is in sync. The interesting artifact is, that other users see the temporary name "New Folder" -- this might even be a good thing, has they see that someone else is working here.

**Comment by mbhkoay** [comment]
Ahh maybe my experience with how new folders are created differs from others. Typically in a day we file lots of stuff from email to the server, so immediately upon creating a new folder, it is renamed to the date the email arrives. 

With the synced folders, sometimes it would lag and cause file rename to not happen. Or sometimes it would rename properly, but then a new folder appears after a few seconds... Its a bit janky and an odd case I guess.

Thanks for the input from you guys as well, can see where you guys are coming from
