### ISSUE TITLE
[QA] Repetitive notification ca every 5 min

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10319]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen with ownCloud 3.0.0.9173-daily20221125 on Linux Mint 20.3

![grafik](https://user-images.githubusercontent.com/1108546/203964968-54bb6c59-dbd7-4ca9-98c7-b677ded5e53b.png)

The desktop client now tells me ca every 5 minutes, that it does not like nextcloud servers.

This is more negativism than what we had in the past, where we only had the red text in the settings UI.
It appears we now much stronger want to make users of the ownCloud client switch to the nextcloud client.
Imo, we should not complain so much, but instead strongly demonstrate, that we have the client that works with both servers (which it does very well for me since many years.)

The text has a whitespace before the first period.

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

.

### Actual behavior

.

**Comment by jnweiger** [comment]
There is another repetitive Notification:
Add a new folder connection, which includes big folders. 
The client wants me to confirm syncing. While the dialog is open, a notification repeats:
![grafik](https://user-images.githubusercontent.com/1108546/203991032-f76a6780-f417-44c9-b61c-3891d770c41d.png)


(The logic of this notification is inverted. It says "has been added" but in reality it hasn't been added.)

**Comment by TheOneRing** [comment]
> There is another repetitive Notification: Add a new folder connection, which includes big folders. The client wants me to confirm syncing. While the dialog is open, a notification repeats: ![grafik](https://user-images.githubusercontent.com/1108546/203991032-f76a6780-f417-44c9-b61c-3891d770c41d.png)
> 
> (The logic of this notification is inverted. It says "has been added" but in reality it hasn't been added.)

unrelated to this issue, and most probably a server notification that an external storage was added to the server.

**Comment by jnweiger** [comment]
The 'unsupported version" notification continues even when sync is paused.

**Comment by TheOneRing** [comment]
Please test with rc2
