### ISSUE TITLE
[QA] Accepting a share via client GUI does not accept the share

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10322]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen with ownCloud 3.0.0.9173-daily20221125 (also 3.0.0.9193-daily20221128)  and damkencloud.

* Using the web-ui as user testy-jw at damkencloud share a file with user jw.
* Connect the client as user jw.
* The client presents a notification in the 'Server activity' about the pending share. OK
![grafik](https://user-images.githubusercontent.com/1108546/204281832-e954d2a3-0e96-47cb-a5d4-4647ace4c456.png)

----
* Click the 'Accept' button. An extra message gets added, showing the exact date when it was accepted. The buttons disappear. OK
![grafik](https://user-images.githubusercontent.com/1108546/204282403-a8e749e5-bc30-4888-a77c-cb5b1d0d6535.png)

----
* Wait a few minutes to let the client sync, whatever it needs to sync. The extra message changes to indicate when the share was created. OK
* The file does not appear in the local filesystem. BAD
* The client does not log a download event in the 'Sync Protocol' tab. BAD
![grafik](https://user-images.githubusercontent.com/1108546/204283439-7f33ae3a-df83-453c-b0df-abf658dc8abb.png)

----
* Using the web-ui, user jw can see in his 'Shared With You' page, that the share is still pending. BAD
* Restarting the client, brings back the original notification, including the buttons. BAD
![grafik](https://user-images.githubusercontent.com/1108546/204283481-a0ec9864-b618-4b12-b5fc-b47bf1ff5056.png)
![grafik](https://user-images.githubusercontent.com/1108546/204283605-316f4099-84e5-4026-8cc9-6faa22e60007.png)

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

The share should be accepted, or if the accept attempt fails, an error message should appear.

### Actual behavior

The client claims something it did not do.

## Workaround

Accept the share at the web ui.

**Comment by jnweiger** [comment]
It's a regression. Accepting shares works fine with e.g. 2.10.0 (build 6611) 168639 Jan 24 2022 12:14:42

**Comment by HanaGemela** [comment]
I'm not even getting the message about pending share on the server with desktop client 3.0.0 rc2, ocis 2.0.0 rc2

**Comment by jnweiger** [comment]
I's damkencloud. It has auto accept disabled
![grafik](https://user-images.githubusercontent.com/1108546/204316759-282f9736-317b-426d-9805-8646dd5bca63.png)
and it is currntly running 10.11.0
