### ISSUE TITLE
[QA] "Show in web browser" is missing, when connected to a nextcloud server

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10333]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen with client 3.0.0.9193-daily20221128 on Linux Mint, connected to a nc 24.0.7 server

![grafik](https://user-images.githubusercontent.com/1108546/205738053-011867ef-da58-4f74-b131-75fbe4eefd4c.png)

The right click menu on the sync folder connection, or on one of the folders should have
"Show in web browser" next to "Show in file manager"

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

.

### Actual behavior

doesnt

**Comment by TheOneRing** [comment]
They either don't promote the capabilities we use to check whether the server supports private links or they don't offer private links as part of the propfind, as done by onwcloud since 9.0.

As discussed with @michaelstingl unsupported product.
