### ISSUE TITLE
[QA] Not enough log files kept

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10345]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Not enough log files are kept
See also https://github.com/owncloud/client/issues/10230

### Steps to reproduce the issue

1. Go to Settings -> Log Settings
2. Set 'Log files to keep' to 6
3. Make sure 6 log files get created (e.g. restart the client 6 times)

### Screenshots

No screenshot

### Expected behavior

6 files are kept in the log folder

### Actual behavior

5 files are kept in the log folder

**Comment by fmoc** [comment]
Closed by #10354.

**Comment by HanaGemela** [comment]
Passed in ownCloud 3.1.0.9453-daily20221222 on mac
