### ISSUE TITLE
Czech language not listed in supported languages

### ISSUE THREAD

**Issue by nextMJ** [owncloud/client#10348]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

In the `GUI -> Settings -> General -> Language` is not listed the Czech language even though it's listed in [transifex](https://explore.transifex.com/owncloud-org/owncloud/). I spent some time translating the content of owncloud (gui/android app/web) to Czech and with the new update, the GUI changed to English without an option to switch it back.

### Expected behavior

I would expect the Czech language in the list of supported options.

### Steps to reproduce the issue

- `GUI -> Settings -> General -> Language`
- Czech language not present

### Client version number

ownCloud 3.0.0.9215- [457b08](https://github.com/owncloud/client/commit/457b08ed362e4c9ae430797508791ff25171c36c)
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: wincfapi
windows-10.0.19045

### Desktop environment (Linux only)

Win 10

### Installation path (Windows only)

C:\Program Files (x86)\ownCloud

**Comment by fmoc** [comment]
I can't find any documentation on this. [In the commit](https://github.com/owncloud/client/commit/2d3155f6a4960b1b29a757766749168b553bc3b9), a whole bunch of files was deleted.

**Comment by fmoc** [comment]
See https://github.com/owncloud/client/blob/master/translations/Makefile#L27. There is a 75% minimum percentage required for files to be included. Apparently, when a language falls below that threshold, the `tx` tool removes the corresponding file.

**Comment by nextMJ** [comment]
@michaelstingl @fmoc  Thanks for the clarification :-)

Great, I pushed the translation level to 85% for now. So I guess that it's enough right now and in the next update it will be available again.

There are two major problems:
- There were added many duplicate strings which already were translated and only waited for confirmation (e.g. [link](https://www.transifex.com/owncloud-org/owncloud/translate/#cs_CZ/client/118697868?q=text%3AConnecting) or search `text:'Connecting'`). Only the confirmation of identical entries "translated" at least 5 %
- I (and I guess other translators as well) do not get any notification that something was added. So with a major update, it can easily fall under some threshold again.

**Comment by HanaGemela** [comment]
Still no translations in ownCloud 3.1.0.9424-daily20221219 even though 80% is reviewed

**Comment by fmoc** [comment]
Translations are back in the branch and should be in the next daily.

**Comment by HanaGemela** [comment]
Czech available in ownCloud 3.1.0.9431-daily20221220
