### ISSUE TITLE
Broken on MacOS

### ISSUE THREAD

**Issue by nxmndr** [owncloud/client#10342]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [x] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The MacOS client seems to be broken in several ways :

- Its icon doesn't appear in the system's icons bar
- It remains, however, in the Cmd+Tab icons list of open programs – but its window is invisible, & I can't see it by launching it manually either.
- It will occasionally use a 100% of one CPU and make the case surrounding the keyboard really hot.

### Expected behavior

Hide like a background program and not overload my CPU.

### Steps to reproduce the issue

I just have it launched automatically at session startup.

### Client version number

```
/Applications/owncloud.app/Contents/MacOS/owncloudcmd --version

sync.utility: migrateLaunchOnStartup: has launch agent plist: false has deprecated launch on startup: false
owncloudcmd ownCloud 3.0.0.9215-
https://github.com/owncloud/client/commit/457b08ed362e4c9ae430797508791ff25171c36c
Libraries Qt 5.15.5, OpenSSL 1.1.1q  5 Jul 2022
Using virtual files plugin: suffix
osx-20.6.0
```

MacOS 11.5.2 on MacBook Pro laptop.

### Server information

- owncloud 10.0.3
- php 7.0
- debian 9

I know these are old versions, but this shouldn't affect owncloud client overloading the CPU.

Thanks !

**Comment by nxmndr** [comment]
That was my problem ; neither worked.

I've reinstalled it and it seems to behave, now. I'll close the issue in a few days if it still does.

**Comment by depeje** [comment]
I'm having the same issue with the client after the update last month on my Macos 11.6.7 in combination with my Owncloud server 10.1.1.1 .

**Comment by depeje** [comment]
From the macos crash report

```
Process:               owncloud [1364]
Path:                  /Applications/owncloud.app/Contents/MacOS/owncloud
Identifier:            com.owncloud.desktopclient
Version:               3.0.0 [build 9215] (3.0.0.9215)
Code Type:             X86-64 (Native)
Parent Process:        zsh [1007]
Responsible:           Terminal [1003]
User ID:               501

Date/Time:             2023-01-07 16:49:20.931 +0100
OS Version:            macOS 11.6.7 (20G630)
Report Version:        12
Anonymous UUID:        57AE3F20-6874-4222-8A55-C7A2ABA6BBC6


Time Awake Since Boot: 150 seconds

System Integrity Protection: enabled

Crashed Thread:        6  Qt bearer thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [1364]
```

**Comment by michaelstingl** [comment]
@depeje Dis you submit a crash report? What's the ID from the ownCloud crash report window?

**Comment by depeje** [comment]
I'm a bit confused the mac log mentions a segmentation fault. Maybe the force quit caused the segfault....

**Comment by michaelstingl** [comment]
Could you post the last few lines from the debug log?
https://doc.owncloud.com/desktop/appendices/troubleshooting.html#log-files

**Comment by depeje** [comment]
I fear that will be difficult since I can't get to the UI to activate it. The UI never shows up. I also can't pass the "--logdir" or "--logfile" when running from the terminal, since the owncloud command is not found:

```
peter@PeterBookPro ~/
→ owncloud                                                                                                                                                                                                    [16:09:41]
zsh: command not found: owncloud
```

At least when using the installer for the client, it installs a app package. I can't easily find information on line on how to run these packages from the command line while passing arguments.

**Comment by depeje** [comment]
Ah, apparently I can `/Applications/owncloud.app/Contents/MacOS && ./owncloud --....`

I'll check next week if I can make some time to install a different version of owncloud to test this.

**Comment by michaelstingl** [comment]
You can install the testpilotcloud build in parallel to not mess with your production installation:
https://owncloud.com/beta-testing/#desktop-testpilot

**Comment by depeje** [comment]
The test pilot v3.0.0.9216 is running fine while connected to the same server, syncing only a subset of my data, so I assume the problem arises with a certain set of user data.

I did the following:
- Installed the test pilot
- Ran the pilot and configured the sync
- Let it sync some data
- Quit the test pilot
- Started the test pilot

I notice no erroneous behavior while doing this.

**Comment by Gribnif** [comment]
I can also confirm the exact behavior described by the original poster. More information:

* I can cause a manual sync to occur by using owncloudcmd.
* The test pilot UI works fine.
* The regular UI (daily build arm64 4.0 or 3.2.x) fails to open. It just hangs.
* Mac OS 12.6.3 on an M1 Max Mac Studio and an M1 MacBook Pro.

**Comment by michaelstingl** [comment]
@Gribnif could you run this from the Terminal?

```
/Applications/owncloud.app/Contents/MacOS/owncloud --logflush --logdebug --logfile -
```

What's the output?

**Comment by Gribnif** [comment]
@michaelstingl  So the first time I ran it, the UI was already running and all I got was this:

```
platform.macos: IORegisterForSystemPower OK! Root port: 25347
gui.application: Already running, exiting...
```

So I terminated everything having to do with owncloud and got the attached log.
[owncloud-log.txt](https://github.com/owncloud/client/files/10970662/owncloud-log.txt)

**Comment by Gribnif** [comment]
Well, as it turns out, my problem is now fixed. I can use the UI in the regular (non-testpilot) version without a problem. I'm not sure if the cure was an update I did to the server side (from 10.0 to 10.8), or just running the commandline test you suggested. So you can go ahead and re-close the ticket.
