### ISSUE TITLE
Login dialog loop when adding an HTTP basic auth account

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#10351]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When adding a new account, logging out is not possible right after the initial sync has finished. When hitting the logout button, the client will sign the user out, but immediately requests the user to log in again. When trying to log out in the dialog, the dialog closes but is immediately reopened, creating an infinite loop.

When logged in successfully a second time, signing out works normally as expected.

This bug only shows when using a server that uses HTTP basic auth, e.g., https://demo.owncloud.org (OAuth2/OIDC are not affected), and only on Windows. I checked various Windows 10 and 11 VMs. Ubuntu doesn't seem to be affected.

### Expected behavior

The client should just let a user log out normally using the button in the account settings.

Same goes for the button in the "login required" dialog.

### Steps to reproduce the issue

1. Use the wizard to add an account on any server utilizing HTTP basic authentication (e.g., https://demo.owncloud.org) on some Windows 10/11
2. Let the sync finish (it is currently unknown whether this is needed, though)
3. Sign out using logout button in the account settings dialog
4. You will see the "login required" dialog in an infinite loop

### Screenshots

![screenshot_2022-12-15_14-40-41](https://user-images.githubusercontent.com/80399010/207874382-5fb47e27-9a50-42a2-8208-6a799f2d6ad4.png)

![screenshot_2022-12-15_14-41-12](https://user-images.githubusercontent.com/80399010/207874396-80ecec19-0784-4f96-b3bd-0b623eeb639d.png)

![screenshot_2022-12-15_14-42-44](https://user-images.githubusercontent.com/80399010/207874420-1bd8928c-4134-469a-90db-db7d0a006ff4.png)

### Logs

First time trying to log out:

```
22-12-15 12:18:26:506 [ info gui.account.state ]:	AccountState state change:  "Verbunden" -> "Abgemeldet"
22-12-15 12:18:26:506 [ debug gui.activity ]	[ OCC::ActivitySettings::slotRefresh ]:	Do not check as last check is only secs ago:  3
22-12-15 12:18:26:506 [ info gui.socketapi ]:	Sending SocketAPI message --> "UNREGISTER_PATH:C:\\Users\\test\\ownCloud - admin@demo.owncloud.org5" to QLocalSocket(0x274dd0daca0)
22-12-15 12:18:26:532 [ info gui.folder.manager ]:	Account "admin@demo.owncloud.org" disconnected or paused, terminating or descheduling sync folders
22-12-15 12:18:26:532 [ info sync.httplogger ]:	"8c414466-4dab-472a-8b32-e64328826bd0: Request: PROPFIND https://demo.owncloud.org/remote.php/dav/files/admin/ Header: { Depth: 1, Prefer: return=minimal, User-Agent: Mozilla/5.0 (Windows) mirall/3.0.0.9215- (ownCloud, windows-10.0.19044 ClientArchitecture: x86_64 OsArchitecture: x86_64), Accept: */*, Content-Type: text/xml; charset=utf-8, X-Request-ID: 8c414466-4dab-472a-8b32-e64328826bd0, Original-Request-ID: 8c414466-4dab-472a-8b32-e64328826bd0, Content-Length: 196, } Data: [<?xml version=\"1.0\" encoding=\"utf-8\"?><d:propfind xmlns:d=\"DAV:\"><d:prop><d:resourcetype/><size xmlns=\"http://owncloud.org/ns\"/><permissions xmlns=\"http://owncloud.org/ns\"/></d:prop></d:propfind>\n]"
22-12-15 12:18:26:532 [ info sync.networkjob ]:	Created OCC::PropfindJob(OCC::Account("admin@demo.owncloud.org"), "https://demo.owncloud.org/remote.php/dav/files/admin/", "PROPFIND", Original-Request-ID: "8c414466-4dab-472a-8b32-e64328826bd0", X-Request-ID: "8c414466-4dab-472a-8b32-e64328826bd0") for OCC::FolderStatusModel(0x274e09958e0)
22-12-15 12:18:26:557 [ info sync.credentials.manager ]:	removed "ownCloud_credentials:demo.owncloud.org:e01b8b00-7331-4d3e-bbbe-467084e84e75:http/password"
22-12-15 12:18:26:710 [ debug sync.credentials.http ]	[ OCC::HttpCredentials::slotAuthentication ]:	void __cdecl OCC::HttpCredentials::slotAuthentication(class QNetworkReply *,class QAuthenticator *) QNetworkReplyHttpImpl(0x274e0f04660)
22-12-15 12:18:26:711 [ info sync.httplogger ]:	"8c414466-4dab-472a-8b32-e64328826bd0: Response: PROPFIND 401 (Error: Der Host verlangt eine Authentifizierung,166ms) https://demo.owncloud.org/remote.php/dav/files/admin/ Header: { Cache-Control: no-store, no-cache, must-revalidate, Content-Length: 448, Content-Security-Policy: default-src 'none';, Content-Type: application/xml; charset=utf-8, Date: Thu, 15 Dec 2022 11:18:26 GMT, Expires: Thu, 19 Nov 1981 08:52:00 GMT, Pragma: no-cache, Referrer-Policy: strict-origin-when-cross-origin, Server: Apache, Set-Cookie: octez35euq13=hf63jihgsoeg9gihp28uv96evg; path=/; secure; HttpOnly; SameSite=Lax\noc_sessionPassphrase=Y3480NKudWojbpIGnONTFrgBsJhxPV4qknrZDTH4tXFMqlpXQhZudfm737v5%2B4fDGzfE5Xm6xGO88F4cmeW%2FArDtghvSod6yz56aIbhAVAsrtsZWjaem1OAbiiG%2BMFTD; expires=Thu, 15-Dec-2022 11:38:26 GMT; Max-Age=1200; path=/; secure; HttpOnly; SameSite=Lax, Strict-Transport-Security: max-age=315360000; preload, Www-Authenticate: Basic realm=\"ownCloud\", charset=\"UTF-8\", X-Content-Type-Options: nosniff, X-Download-Options: noopen, X-Frame-Options: SAMEORIGIN, X-Permitted-Cross-Domain-Policies: none, X-Robots-Tag: none, X-Xss-Protection: 0, } Data: [<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<d:error xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\">\n  <s:exception>Sabre\\DAV\\Exception\\NotAuthenticated</s:exception>\n  <s:message>No public access to this resource., No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured, No 'Authorization: Basic' header found. Either the client didn't send one, or the server is misconfigured</s:message>\n</d:error>\n]"
22-12-15 12:18:26:711 [ info gui.account.state ]:	Invalid credentials for "https://demo.owncloud.org/"
22-12-15 12:18:26:711 [ info gui.account.state ]:	refreshing oauth
22-12-15 12:18:26:711 [ info gui.account.state ]:	refreshing oauth failed
22-12-15 12:18:26:711 [ info gui.account.state ]:	asking user
22-12-15 12:18:26:711 [ info gui.account.state ]:	AccountState state change:  "Abgemeldet" -> "Zugangsdaten werden abgefragt"
```

After logging in successfully again, logging out works:
```
22-12-15 12:18:35:708 [ info gui.account.state ]:	AccountState state change:  "Verbunden" -> "Abgemeldet"
22-12-15 12:18:35:708 [ debug gui.activity ]	[ OCC::ActivitySettings::slotRefresh ]:	Do not check as last check is only secs ago:  12
22-12-15 12:18:35:708 [ info gui.socketapi ]:	Sending SocketAPI message --> "UNREGISTER_PATH:C:\\Users\\test\\ownCloud - admin@demo.owncloud.org5" to QLocalSocket(0x274dd0daca0)
22-12-15 12:18:35:759 [ info gui.folder.manager ]:	Account "admin@demo.owncloud.org" disconnected or paused, terminating or descheduling sync folders
22-12-15 12:18:35:790 [ info sync.credentials.manager ]:	removed "ownCloud_credentials:demo.owncloud.org:e01b8b00-7331-4d3e-bbbe-467084e84e75:http/password"
22-12-15 12:18:37:994 [ debug gui.account.manager ]	[ OCC::AccountManager::saveAccount ]:	Saving account "https://demo.owncloud.org/"
22-12-15 12:18:38:020 [ info gui.account.manager ]:	Saving  0  unknown certs.
22-12-15 12:18:38:047 [ debug gui.account.manager ]	[ OCC::AccountManager::saveAccount ]:	Saved account settings, status: QSettings::NoError
22-12-15 12:18:38:047 [ info sync.credentials.manager ]:	set "ownCloud_credentials:demo.owncloud.org:e01b8b00-7331-4d3e-bbbe-467084e84e75:http/password"
22-12-15 12:18:38:047 [ info gui.account.manager ]:	Saving  0  unknown certs.
22-12-15 12:18:38:093 [ info gui.account.manager ]:	Saved all account settings, status: QSettings::NoError
22-12-15 12:18:38:154 [ debug gui.folderwatcher ]	[ OCC::WatcherThread::watchChanges ]:	Received stop event, aborting folder watcher thread
22-12-15 12:18:38:155 [ info sync.database ]:	Closing DB "C:/Users/test/ownCloud - admin@demo.owncloud.org5/.sync_journal.db"
22-12-15 12:18:38:193 [ debug gui.socketapi ]	[ OCC::SocketApi::~SocketApi ]:	dtor
22-12-15 12:18:38:194 [ info gui.socketapi ]:	Lost connection  QLocalSocket(0x274dd0daca0)
22-12-15 12:18:38:196 [ debug sync.utility ]	[ OCC::Utility::startShutdownWatcher::::operator() ]:	app closed
```

Complete log can be found [here](https://gist.github.com/fmoc/68f0c46342ea88bddc8f9b36da4aea6e).

### Client version number

ownCloud 3.0.0 release (build 9215)

### Installation path (Windows only)

`C:\Program Files\ownCloud`

### Additional context

CC @d7oc

**Comment by erikjv** [comment]
I cannot reproduce this with a (debug) build from the 3.1 branch

**Comment by fmoc** [comment]
Reproducible with `3.1.0.9403-daily20221216` daily build.

**Comment by TheOneRing** [comment]
This appears to be a duplicate, we already had an issue for this.

**Comment by fmoc** [comment]
Cannot reproduce any more with the 3.2 release. The linked issue was using a prerelease. QA, please comment on this issue if you manage to reproduce the problem.

**Comment by fmoc** [comment]
By the way, the fact that https://github.com/owncloud/client/issues/10512 exists (which was clearly written on some Linux Mint, given the screenshot, unless that's completely misleading) hints that this might not be a VFS-only issue. @jnweiger please provide the results from https://github.com/owncloud/client/issues/10512 in a comment here along with an exact description of your setup (I'm mainly interested in the platform and version).

**Comment by jnweiger** [comment]
In case of 10512 I have no steps to reproduce. It happened once and is not reproducable. Sorry.
Seen with testpilot 3.2.0.10176 on Linux Mint 20.3

**Comment by fmoc** [comment]
So we have an intermittent issue which probably hasn't been fixed yet that is very hard to reproduce. Also, our assumption so far that this is VFS induced is wrong. Great...

I guess that VFS is still a good way to trigger the problem, if any. The problem used to be very reproducible with the older client versions. I suggest that if the problem becomes worse again, we'll start digging using the known-broken versions to identify code paths leading to the issue.

**Comment by saw-jan** [comment]
Reproducible with `ownCloud 5.0.0.11640-daily20230803`

:x: Login required dialog re-appears when choosing `logout` or close dialog (`x`) option

![Screenshot from 2023-08-03 11-47-49](https://github.com/owncloud/client/assets/52366632/37c4d7ef-204a-4a3d-a28a-8723068c0d9d)

Log: [ownCloud-.log](https://github.com/owncloud/client/files/12247360/ownCloud-.log)

**Comment by fmoc** [comment]
I just reproduced it this morning with a fresh 5.0.0 dev build with demo.owncloud.org.

**Comment by saw-jan** [comment]
Tested with `ownCloud 5.0.0.11689-daily20230810 f87a3a`

- no loop with Login required dialog - `logout` and `x` button can close the dialog :heavy_check_mark: 
- but login required is not prompted upon restart :question: CC @TheOneRing

**Comment by TheOneRing** [comment]
When you decided to log out we remember that.

**Comment by saw-jan** [comment]
So, upon restarting the client, there will be no login pop? Thne can it be considered done?
