### ISSUE TITLE
[QA] desktop client opens a new browser tab every 5 minutes when connected via IDP

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10372]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen with client 2.11.1 connected to server 10.11.0 which runs openidconnect app 2.2.0-rc.7 with a keycloak IDP.

* Connect client to server.
* Wait 5 minutes, a new browser window appears with an URL like e.g. 
  `http://127.0.0.1:36355/?state=ejKWV1xzZqqBML...PQ%3D&session_state=0791f3f8-5c53-4b4b-b362-...&code=199d0c21-c41c-4a2e-bf75-...`
* Wait longer. new broeser windows keep appearing every 5 minutes.
![grafik](https://user-images.githubusercontent.com/1108546/209120249-9319d272-4098-41fc-859f-89142f48d142.png)

Is this some strange form of token-revalidation?

Client log showing e.g. the reconnects using port 36355:
[20221222_1123_owncloud.log.0.gz](https://github.com/owncloud/client/files/10286362/20221222_1123_owncloud.log.0.gz)

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

No browser windows accumulate.

### Actual behavior

They do.

**Comment by TheOneRing** [comment]
We no longer automatically open the browser but ask the user in 3.0

**Comment by jnweiger** [comment]
Confirmed fixed in 3.0.0

Not sure what "ask the user" means. Nothing pops up, as expected.
