### ISSUE TITLE
[QA] How to get the "client-desktop-vfs-win" source code?

### ISSUE THREAD

**Issue by toyua** [owncloud/client#10371]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

I just tried to build version 3.0 for windows, using kde craft env.I found that the plugins folder does not have "client-desktop-vfs-win"  source code. Isn't this part open source?
I read the "client-desktop-vfs-win.py  " file: 
...
self.versionInfo.setDefaultValues(gitUrl="git@github.com:owncloud/client-desktop-vfs-win.git"
..
this url is not accessible.

can I get this part of code?  
I want to get the full source code.
thanks.

### Steps to reproduce the issue

1.setup and launch the KDE Craft
2.setup the ownCloud repository
3.build the  windows desktop app
4.build succeed, but no owncloudsync_vfs_win.dll

### Screenshots

nothing

**Comment by michaelstingl** [comment]
Related:
- https://github.com/owncloud/client/issues/8006

> Isn't this part open source?

No, not published yet.

**Comment by toyua** [comment]
> Related:
> 
> * [VFS is disabled and not included on custom Windows Build. #8006](https://github.com/owncloud/client/issues/8006)
> 
> > Isn't this part open source?
> 
> No, not published yet.



> It's been two years，when will it be published ?

**Comment by michaelstingl** [comment]
> It's been two years，when will it be published ?

Currently not planned, sorry.
