### ISSUE TITLE
owncloudcmd command as a typo in an option

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#10389]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Referenced docs issue: https://github.com/owncloud/docs-client-desktop/issues/314 (owncloudcmd documentation incorrect.)
```
$ owncloudcmd -h
gui.platform: adding plugin directory "/opt/ownCloud/ownCloud/bin/../lib/x86_64-linux-gnu/plugins"
Usage: owncloudcmd [options] source_dir server_url remote_folder
owncloudcmd version 3.0.0.9215- - command line client tool

Options:
  -s, --silten                      Don't be so verbose.
```
`--silten` --> `--silent`

Here are more improvements for other option descriptions:

`--httpproxy <http://server:port>` 
`Specify a http proxy to use.` --> `Specify a HTTP proxy to use.`

`--server <url>`
`Use [url] as the location of the server. OCIS only (server location and spaces url can differ)` -->
`Use [url] as the location of the server. Infinite Scale only (server location and spaces URL can differ)`

### Expected behavior

Fix option typo

### Steps to reproduce the issue

Just run `owncloudcmd`

### Client version number

![image](https://user-images.githubusercontent.com/3321281/211014987-69d28f80-8058-488f-8fa4-6d90fa1956c3.png)

**Comment by TheOneRing** [comment]
Fixed in 3.1
