### ISSUE TITLE
MacOS: Virtual files does not open anything on M1 MacBook pro

### ISSUE THREAD

**Issue by andrejkolesa** [owncloud/client#10385]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

I have enabled virtual files share and sync is OK.
But when i try to open file (with extension .owncloud) nothingf happens.
I have owncloud client as default app for this extension. Also i can try "Open with" but nothing helps.

Thanks and br,
Andrej

### Expected behavior

I expect file to be downloaded and opened in respected application (excel, word ...) but nothing happens.

### Steps to reproduce the issue

1. Add folder sync
2. Sync everything
3. Open file

### Client version number

Owncloud 3.0.0.9215

**Comment by michaelstingl** [comment]
> But when i try to open file (with extension .owncloud) nothingf happens.
> I have owncloud client as default app for this extension. Also i can try "Open with" but nothing helps.

macOS suffix VFS is experimental, and I don't have an ETA for a fix. I'd recommend to use use ownCloud'd context menu entry as a workaround:

![CleanShot 2023-01-05 at 10 21 31](https://user-images.githubusercontent.com/214010/210746754-6e7941b6-8695-4438-8bff-3cdba122e0f1.png)

**Comment by TheOneRing** [comment]
ownCloud is supposed to be the default application to open those files.
What happens if you double-click a .owncloud file?

**Comment by ammannit** [comment]
Hi

When i double click on the file, its open owncloud. But nothing happing anymore

**Comment by TheOneRing** [comment]
Please provide client logst

**Comment by ammannit** [comment]
[ownCloud.log](https://github.com/owncloud/client/files/14497947/ownCloud.log)

**Comment by ammannit** [comment]
could the reason be that the database is not located directly on the server?

**Comment by TheOneRing** [comment]
In the second case it claims that the client does not know about the affected file.
Does the file exist on the server, or is it a zombie placeholder?

**Comment by TheOneRing** [comment]
And if you perform a forced sync and try it again, does it still complain that the file is not in the db?
