### ISSUE TITLE
Can't open files from Windows Search / Start Menu with VFS

### ISSUE THREAD

**Issue by redelschaap** [owncloud/client#10380]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When using ownCloud client for Windows with VFS, I can't open my files anymore when searching for them within Explorer / Windows Search / Start Menu.

The files are in the search results when I start typing, but when I hit Enter / click "Open", nothings happen. Opening the folder of the file from the Start Menu works as expected.

### Expected behavior

When searching for a file in Windows, I expect it to open when I hit Enter or click "Open".

### Steps to reproduce the issue

1. Open the Start Menu.
2. Type a (part of a) file name.
3. When the correct file shows up, hit Enter or select it and click "Open"
4. Nothing happens.

### Logs

Logs do not contain any information about the file I'm trying to open.

### Client version number

ownCloud 3.0.0.9215-457b08
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: wincfapi
windows-10.0.22621

### Installation path (Windows only)

C:\Program Files (x86)\ownCloud

### Server information

ownCloud 10.1.1 (stable)

**Comment by TheOneRing** [comment]
Hi @redelschaap I can't reproduce your issue (while the client is running).
When the client is currently not running I can indeed reproduce that behavior.
Can you also verify that the path for that file is correct and it is not a leftover placeholder from a previous setup?

Could you please provides logs from the client (https://doc.owncloud.com/desktop/next/appendices/troubleshooting.html#log-files) when you try to access such a file.

**Comment by redelschaap** [comment]
I can verify that the path for the file is correct. If, for example, I look for an XLSX document, it won't open from the Start Menu. If I use the "Copy path" button in the Start Menu, open Excel manually, and open the file using the path, it opens the file.

After I activated the log feature and tried to open the file again, I noticed something interesting. When I open the file from the start menu, it toggles the availability checkmark in Windows Explorer. When opening the file from the start menu, the availability checkmark turns fully green and the status in the status bar says "Always available on this device" (roughly translated from Dutch). When opening the file from the Start Menu again, the availability checkmark turns partly green and the status bar says "Available on this device".

Here are the logs from the moment I activated until after I tried to open the file from the Start Menu a couple of times:

```log
ownCloud 3.0.0.9215- 457b08  biliotheken Qt 5.15.5, OpenSSL 1.1.1q  5 Jul 2022 Gebruikt virtuele bestandenplugin: wincfapi windows-10.0.22621 ownCloud
23-01-05 09:03:10:827 [ info gui.folderwatcher ]:	Detected changes in paths: "C:/Users/username/OWNCLOUD FOLDER/PATH TO FILE/FILENAME.xlsx"
23-01-05 09:03:10:827 [ debug sync.localdiscoverytracker ]	[ OCC::LocalDiscoveryTracker::addTouchedPath ]:	inserted touched "PATH TO FILE/FILENAME.xlsx"
23-01-05 09:03:10:827 [ info gui.folder ]:	Ignoring spurious notification for file "PATH TO FILE/FILENAME.xlsx"
23-01-05 09:03:21:006 [ info gui.folderwatcher ]:	Detected changes in paths: "C:/Users/username/OWNCLOUD FOLDER/PATH TO FILE/FILENAME.xlsx"
23-01-05 09:03:21:006 [ debug sync.localdiscoverytracker ]	[ OCC::LocalDiscoveryTracker::addTouchedPath ]:	inserted touched "PATH TO FILE/FILENAME.xlsx"
23-01-05 09:03:21:006 [ info gui.folder ]:	Ignoring spurious notification for file "PATH TO FILE/FILENAME.xlsx"
23-01-05 09:03:31:047 [ info gui.folderwatcher ]:	Detected changes in paths: "C:/Users/username/OWNCLOUD FOLDER/PATH TO FILE/FILENAME.xlsx"
23-01-05 09:03:31:047 [ debug sync.localdiscoverytracker ]	[ OCC::LocalDiscoveryTracker::addTouchedPath ]:	inserted touched "PATH TO FILE/FILENAME.xlsx"
23-01-05 09:03:31:050 [ info gui.folder ]:	Ignoring spurious notification for file "PATH TO FILE/FILENAME.xlsx"
23-01-05 09:03:33:812 [ info gui.folder ]:	Trying to check "https://cloud.our-domain.nl/remote.php/dav/files/oc_username/" for changes via ETag check. (time since last sync: 554 s)
23-01-05 09:03:33:812 [ debug gui.folder.manager ]	[ OCC::FolderMan::slotRunOneEtagJob ]:	Scheduling "https://cloud.our-domain.nl/remote.php/dav/files/oc_username/" to check remote ETag
23-01-05 09:03:33:812 [ info sync.networkjob ]:	Created OCC::RequestEtagJob(OCC::Account("MyName@cloud.our-domain.nl"), "https://cloud.our-domain.nl/remote.php/dav/files/oc_username/", "PROPFIND", Original-Request-ID: "af2888d8-eb49-4a26-aab6-74682f7eacd3", X-Request-ID: "af2888d8-eb49-4a26-aab6-74682f7eacd3") for OCC::Folder(0x2b4c8f86060)
23-01-05 09:03:35:382 [ info sync.networkjob.propfind ]:	LSCOL of QUrl("https://cloud.our-domain.nl/remote.php/dav/files/oc_username/") FINISHED WITH STATUS "OK"
23-01-05 09:03:35:382 [ info gui.folder.manager ]:	void __cdecl OCC::FolderMan::setSyncEnabled(bool) true
23-01-05 09:03:35:398 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job finished OCC::RequestEtagJob(OCC::Account("MyName@cloud.our-domain.nl"), "https://cloud.our-domain.nl/remote.php/dav/files/oc_username/", "PROPFIND", Original-Request-ID: "af2888d8-eb49-4a26-aab6-74682f7eacd3", X-Request-ID: "af2888d8-eb49-4a26-aab6-74682f7eacd3")
23-01-05 09:03:43:748 [ info gui.folderwatcher ]:	Detected changes in paths: "C:/Users/username/OWNCLOUD FOLDER/PATH TO FILE/FILENAME.xlsx"
23-01-05 09:03:43:748 [ debug sync.localdiscoverytracker ]	[ OCC::LocalDiscoveryTracker::addTouchedPath ]:	inserted touched "PATH TO FILE/FILENAME.xlsx"
23-01-05 09:03:43:748 [ info gui.folder ]:	Ignoring spurious notification for file "PATH TO FILE/FILENAME.xlsx"
```

**Comment by redelschaap** [comment]
Any update on this?

**Comment by redelschaap** [comment]
Any update on this? Still having the issue.

**Comment by redelschaap** [comment]
This now seems to be resolved on my system. I recently updated the client to:

### Client version number

ownCloud 3.2.0.10193-718af2
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: wincfapi
windows-10.0.22621
