### ISSUE TITLE
App window resizing is not working properly

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#10406]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Windows 10x64
<img width="218" alt="resolution" src="https://user-images.githubusercontent.com/3321281/213142581-e7be365d-037f-4ff3-8155-0f172e7c28cd.png">
Using the recommended scaling (150%)
<img width="218" alt="resolution" src="https://user-images.githubusercontent.com/3321281/213142843-04e565df-8de8-49b1-a97f-6aacd47061f4.png">
I cant reduce the size of the app more down as the following:
<img width="800" alt="150" src="https://user-images.githubusercontent.com/3321281/213143174-65f4ad11-b320-4fe6-9299-17da94d78d3c.png">
compared when using 125%
<img width="400" alt="125" src="https://user-images.githubusercontent.com/3321281/213143299-f7726d04-1023-4bc5-84c7-f38ce85856c2.png">

Now this may look identical when comparing the **contents** of the windows.
But when looking to the **absolute window sizes** (see images above) this is a huge difference and more than 17%. (125 --> 155)

The impact is, that with 150% (recommended by MS) the screen is more or less blocked by the app window and you cant see other stuff and you cant size it more down.

Note that it necessary to at least make the window shrink **vertically** more than it does now.
Horizontally you can move the window to get content into the visible area.

I cant imagine that this behaviour is benificial for important customers.

### Expected behavior

Ability to further shrink down the app window size making other screen content visible.

### Client version number

![image](https://user-images.githubusercontent.com/3321281/213145285-5689a0df-5f09-45c9-9f5a-a43552065f06.png)

### Installation path (Windows only)

C:\Program Files (x86)\ownCloud

**Comment by TheOneRing** [comment]
Did you restart the client after changes to the scaling?

**Comment by mmattel** [comment]
I just did the following:

Set "Scale and Layout" to 125% and restarted the app.
The red area cant be shrinked down
<img width="300" alt="restarted after setting to 125" src="https://user-images.githubusercontent.com/3321281/213674332-98091987-b9ca-4950-92e7-7eeb534fb0ca.png">

Here you can compare the font sizes from the app and the desktop icons. You see that with 125% the font sizes are more or less the same while with 150% the app has a much bigger fontsize compared to the desktop:

125%
<img width="168" alt="compare font size 125" src="https://user-images.githubusercontent.com/3321281/213675363-de5f21e6-2d2f-46fe-82fe-37631da6ebf6.png">
150%
<img width="168" alt="compare font size 150" src="https://user-images.githubusercontent.com/3321281/213675482-9b6ec021-8d5d-40d2-8d8e-aacd1279d481.png">

After setting  "Scale and Layout" back to 150% **without** touching the app, it looks like that.
<img width="479" alt="post resetting to 150" src="https://user-images.githubusercontent.com/3321281/213676051-9b397918-a8f9-43eb-88be-5e9990fc33eb.png">

When I click on the app, it **exploded** vertically to a size where the bottom went **under** the screen and due to its size the **Hide** button was not accessible anymore. Only by fully closing the app and restarting it, it was fitting into the screen again but in a size as described for 150% on top.

**Comment by TheOneRing** [comment]
As a workaround for now please set:
```
set QT_SCALE_FACTOR_ROUNDING_POLICY="Floor"
```

Works with 3.0 and later.

For development:
https://doc.qt.io/qt-5/qguiapplication.html#highDpiScaleFactorRoundingPolicy
https://doc.qt.io/qt-5/highdpi.html#microsoft-windows

**Comment by mmattel** [comment]
@TheOneRing after installing 3.2, I cant make this working as we tested last time ... ?

**Comment by mmattel** [comment]
ok, my fault, some mistyping (🤦‍♂️) here a powershell command that works:
`$env:QT_SCALE_FACTOR_ROUNDING_POLICY="Floor"; .\owncloud.exe`
from the directory where owncloud is installed.

**Comment by amrita-shrestha** [comment]
# Tested
### Display resolution ` 1920 * 999 `
###  Set "Scale and Layout" from 100% to 150%
1. without restarting the owncloud app
![Screenshot from 2023-03-30 12-15-50](https://user-images.githubusercontent.com/54478846/228749098-2596cdb3-200c-4851-94e4-d48844b933da.png)
-  button buttons are hidden ❓ 
-  can't shrink the app window  ❓ 
- font size looks justified 
- activity table left side border line disappears ❓  
![Screenshot from 2023-03-30 13-30-23](https://user-images.githubusercontent.com/54478846/228766280-3039a6e3-8d48-48c3-b84d-ee181437b664.png)


2. restarted the app.
![Screenshot from 2023-03-30 12-20-07](https://user-images.githubusercontent.com/54478846/228749865-86e8ab81-d0e3-4c4d-a57d-dc4c88f5b98b.png)
- after restarting the app text and icon size shrink a little bit than before ❓ 
- bottom buttons are visible ✔️ 
- can shrink ✔️ 
![Screenshot from 2023-03-30 12-26-13](https://user-images.githubusercontent.com/54478846/228751085-37c440fb-a2d0-439b-b56b-5f5a94e7ee75.png)
- activity table left side border line disappears ❓ 
![Screenshot from 2023-03-30 13-30-45](https://user-images.githubusercontent.com/54478846/228766328-24970be6-028a-49df-b5ec-831f332f7893.png)



###  Set "Scale and Layout" from 150% to 100%
1. without restarting the owncloud app
![Screenshot from 2023-03-30 12-35-09](https://user-images.githubusercontent.com/54478846/228753287-6a5f5b3b-b391-465e-9c23-dcd9957500bd.png)
- can shrink ✔️ 
- font size looks very small

2. restarted the app

![Screenshot from 2023-03-30 12-35-30](https://user-images.githubusercontent.com/54478846/228764059-d5745ac2-5927-40a7-a3c2-8d3c0e683191.png)
- after restarting the app text and icon size expand a little bit more than before ❓ 
- can shrink ✔️ 


cc @TheOneRing
