### ISSUE TITLE
Cant delete sync folder post removing the sync relationship with non admin user

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#10405]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Using W10x64 as client host

Note that the server name used is obfuscated.

I created a sync relation ship with: `internal.works`. After I have done what I was looking for, **I removed the sync relationship** (Account, Remove, worked) and tried to delete the local files. 

The folder in explorer is shown as: `ownCloud - Admin@internal.works` (the name was given by the app). Right click on delete requested admin permissions - ok

<img width="337" alt="rights_1" src="https://user-images.githubusercontent.com/3321281/213134228-20328c0b-583e-41d0-ac13-347de2720f68.png">

but then it tells me that it cant delete the folder - it requires notebook permissions ?? withouty any choice.

<img width="335" alt="rights_2" src="https://user-images.githubusercontent.com/3321281/213134347-d239900c-24c6-4660-b623-6bfe64212555.png">

I cannot proceed and no files get deleted.

In addition, the folder does not show up in the comand shell, but does in powershell??

Trying to run power shell with admin rights `rm -r "ownCloud - Admin@internal.works"` returns many times:
```
rm : Cannot remove item C:\Users\marti\ownCloud - Admin@internal.works\Desktop.ini: You do not
have sufficient access rights to perform this operation.
```
any ideas what is going on and how to fix this?

Note that there is no change in behaviour when quitting the app.

### Expected behavior

1. The sync folder can be shown in the cmd shell
2. The sync folder can be deleted by using the explorer, cmd shell, powershell etc.

### Client version number

![image](https://user-images.githubusercontent.com/3321281/213132001-dfdb998d-ed54-49f9-8300-c1b83228cdcb.png)

### Installation path (Windows only)

C:\Program Files (x86)\ownCloud

**Comment by jnweiger** [comment]
Is the desktop client still running? I am thinking of something still being locked...

**Comment by mmattel** [comment]
> Is the desktop client still running? I am thinking of something still being locked...

As I have written above: `Note that there is no change in behaviour when quitting the app.`

And even then, I have quit the relationship and the folder has to be freed from any locking!

**Comment by mmattel** [comment]
@TheOneRing your title change:
`Cant delete sync folder post removing the sync relationship with non admin user`

Can lead to the interpretation that this **only** happens when you are not admin.
See the screenshots that it does not work even you grant admin rights.
Consider that I AM admin on my NB.

**Comment by TheOneRing** [comment]
The folder is marked as a system folder, maybe that has an influence.
I deleted hundreds of sync folders as admin user so it should work in general, have you tried a reboot? Maybe Windows is just acting up.

**Comment by mmattel** [comment]
> have you tried a reboot? 😱 

I rarely reboot (running my NB 24x7) and only it is necessary by MS updates that force a reboot.
Let me know if I can try other things.

**Comment by mmattel** [comment]
`Special Permissions`, which you cant see in the window below, are not set and cant be set.
All accounts shown have the same security settings

<img width="269" alt="security" src="https://user-images.githubusercontent.com/3321281/213163635-6ba8d7d7-66c1-4a42-8520-23d78db4044f.png">

**Comment by mmattel** [comment]
Doing some research, I found that you can **in explorer**:
1. mark the file with the mouse
2. via the **keyboard** press together `shift` `delete` (final delete without waste bin)
(not working with the context menu or powershell !!)
3. a window pops up
<img width="334" alt="shift delete" src="https://user-images.githubusercontent.com/3321281/213164916-fd8a48fd-72c3-42b4-8443-cf6b62e32531.png">

4. either check `Do this for all current items`
or manually accept for each items this windows comes up
5. Click `Yes`

Done

Now, having a workaround, this is not a behaviour we should accept.

* deleting should be fixed using the context menu and Powershell / cmd shell
(note, AD admins are not amused...)
* the folder should be visible in the cmd shell

**Comment by jnweiger** [comment]
A 'desktop.ini' file inside the sync root is probably a corner case. It is blacklisted afaik.

**Comment by mmattel** [comment]
> It is blacklisted afaik.

Blacklisting a file in the App should not have any impact when deleting the folder of a fully removed synchronisation. This is because the behaviour is the same when the Desktop App has been stopped.

**Comment by mmattel** [comment]
Hmmm, this is getting strange.

I re-tested and did the following:

* Create new sync relationship with the same instance as above ✔️ 
* Added locally a file which gets synced ✔️ 
* Added a file via the web which gets synced ✔️ 
* Added an Office file which gets synced ✔️ 
* Added an image which creates a `.Desktop.ini` file ✔️ 
* All is synced and visisble on both sides ✔️ 
* Remove the sync relationship ✔️ 
* Delete the sync folder via explorer context menu ✔️ 

Result, I cant reproduce the behaviour 😢 

Learning: we need to drop a note in the Desktop App documentation for windows how to delete a sync folder post removing teh relationship that is reluctant against to be deleted (shift delete works).

The only thing that is still an issue is, that the folder name like `ownCloud - Admin@internal.works` will not show up in the command shell when running `dir`. Works in PowerShell. But this can be solved by documenting.

@TheOneRing if you agree, I will close this issue and file a documentation issue referencing this one here.

**Comment by TheOneRing** [comment]
Its not related to the folders name, the folder is marked as a system folder and not listed by cmd dir.
Powershell is supposed to list them at least in more recent versions.
The listing issue is discussed in different issues all over the place. @michaelstingl can you remember?

**Comment by mmattel** [comment]
> The listing issue is discussed in different issues all over the place.

There is no doc issue filed for that, so how can one know?

**Comment by TheOneRing** [comment]
Please open a docs issue about that cmd can't list the sync folder.
