### ISSUE TITLE
[maCOS] Update section missing on Settings view

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10414]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Update section missing on Settings view

### Expected behavior

Update section should be shown on Settings view

### Steps to reproduce the issue

n.a.

### Screenshots

![CleanShot 2023-01-19 at 10 40 21@2x](https://user-images.githubusercontent.com/214010/213408337-dad1531c-84f9-4f44-966e-9ef2f122644e.png)

### Client version number

```
ownCloud 3.1.0.9784-daily20230115 b4ec19
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-22.2.0
```

**Comment by TheOneRing** [comment]
It appears that the mac updated using sparkle does not provide us with the necessary information to display the status.
https://github.com/owncloud/client/blob/c7367fe174fe5c50f4691528aa028ba8d5e5f275/src/gui/generalsettings.cpp#L121-L122
