### ISSUE TITLE
[QA][gui-tests] Implement `on the server` steps in python (squish)

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#10432]
### Describe the QA issue

Currently, we are using `owncloud-test-middleware` to configure the server during the tests. In order to reduce the test dependencies we need to create those `on the server` steps in the local test directory i.e. in the gui test directory of this repo.
 
Steps to implement:
- [x] [Given steps](https://github.com/owncloud/client/issues/10432#issuecomment-1404861686)
- [x] [Then steps](https://github.com/owncloud/client/issues/10432#issuecomment-1404862169)
- [x] remove middleware code and middleware service from CI

**Comment by saw-jan** [comment]
Then steps:
- [ ] `Then as "<user>" file "<fileName>" should not exist on the server`
- [ ] `Then as "<user>" folder "<folderName>" should not exist on the server`
- [ ] `Then as "<user>" file "<fileName>" should exist on the server`
- [ ] `Then as "<user>" folder "<folderName>" should exist on the server`
- [ ] `Then as "<user>" the file "<fileName>" on the server should have the content "<content>"`
- [ ] `Then as user "<user>" the file "<fileName>" should have a public link on the server`
- [ ] `Then as user "<user>" the folder "<folderName>" should have a public link on the server`
- [ ] `Then as user "<user>" the file "<fileName>" should not have any public link on the server`
- [ ] `Then as user "<user>" the folder "<folderName>" should not have any public link on the server`
- [ ] `Then the public should be able to download the file "<fileName>" without password from the last created public link by "<user>" on the server`
- [ ] `Then the public should be able to download the folder "<folderName>" without password from the last created public link by "<user>" on the server`
- [ ] `Then the public should not be able to download the file "<fileName>" from the last created public link by "<user>" on the server`
- [ ] `Then the public should not be able to download the folder "<folderName>" from the last created public link by "<user>" on the server`
- [ ] `Then the public should be able to download the file "<fileName>" with password "<password>" from the last created public link by "<user>" on the server`
- [ ] `Then the public should be able to download the folder "<folderName>" with password "<password>" from the last created public link by "<user>" on the server`
- [ ] `Then the public should not be able to download the file "<fileName>" with password "<password>" from the last created public link by "<user>" on the server`
- [ ] `Then the public should not be able to download the folder "<folderName>" with password "<password>" from the last created public link by "<user>" on the server`
- [ ] `Then the last public link share response of user "<user>" should include the following fields on the server`
```feature
| <field_name> | <value> |
```
- [ ] `Then user "<user>" on the server should have a share with these details:`
```feature
| <field_name> | <value> |
```
- [ ] `Then as user "<user>" folder "<folderName>" should contain "<number>" items on the server`

**Comment by ishabaral** [comment]
All middleware dependencies have been removed. So the middleware repository can now be archived.
