### ISSUE TITLE
NO sync for dll, bat, log, or exe files

### ISSUE THREAD

**Issue by RobertATVT** [owncloud/client#10434]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The Windows Sync app will not sync dll, bat, exe, log, ini files or several others.  I have viewed the settings and exclusions and cannot find a way to allow them to sync. I understand the precautions but there should be a way to allow someone willing to take the risk to sync these. I'm currently running my own OwnCloud server on my own hardware and as such am okay with the risk.

### Expected behavior

People running their own personal OwnCloud severs should be allowed to sync whatever files they want if they are willing to accept that risk.

### Steps to reproduce the issue

1. Setup OwnCloud Community Edition
2. Install Windows Sync Application
3. Copy any .dll, .exe., .bat, .log, .ini files to the OwnCloud folder on windows.
4. Watch as all the error messages roll in telling you that these files were ignored.

### Screenshots

![Screenshot 2023-01-26 082044](https://user-images.githubusercontent.com/14984393/214854479-6f826660-3f8e-4e48-8a98-7316e261b0fa.jpg)

### Logs

# This file contains fixed global exclude patterns

*~
~$*
.~lock.*
~*.tmp
]*.~*
]Icon\r*
].DS_Store
].ds_store
*.textClipping
._*
]Thumbs.db
]photothumb.db
System Volume Information

.*.sw?
.*.*sw?

].TemporaryItems
].Trashes
].DocumentRevisions-V100
].Trash-*
.fseventd
.apdisk
.Spotlight-V100

.directory

*.part
*.filepart
*.crdownload

*.kate-swp
*.gnucash.tmp-*

.synkron.*
.sync.ffs_db
.symform
.symform-store
.fuse_hidden*
*.unison
.nfs*

My Saved Places.

\#*#

*.sb-*

### Client version number

ownCloud 3.0.0.9215

### Installation path (Windows only)

C:\Program Files\OwnCloud

### Server information

version | 10.11.0.6
versionstring | 10.11.0
edition | Community
productname | ownCloud
product | ownCloud

**Comment by michaelstingl** [comment]
@RobertATVT please reproduce with demo.owncloud.com. Maybe your ownCloud instance has some special configuration.

**Comment by RobertATVT** [comment]
I uploaded a composer.json file and a random windows .dll to the demo instance, and it worked fine. Where would I find a configuration to allow these on my server?  There's nothing in the exception for any of these file types for the client.  I've been looking for a solution for weeks.

**Comment by michaelstingl** [comment]
This is the issue tracker of the ownCloud desktop sync client, not a help forum. Please use https://central.owncloud.org/ instead.
