### ISSUE TITLE
[QA] Cannot click Next in Wizard when entering username in WebFinger section

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10441]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Cannot click Next in Wizard when entering username in WebFinger section
Client 3.1.0

### Steps to reproduce the issue

1. Get a client with WebFinger
2. Enter a server address
3. Enter a username
4. Click Next

### Screenshots

<img width="720" alt="Screenshot 2023-01-31 at 13 54 47" src="https://user-images.githubusercontent.com/49001702/215766058-f0009dbf-626b-4a8d-9520-18ab2bb784de.png">

### Expected behavior

Next button is available

### Actual behavior

Next button is greyed out

**Comment by TheOneRing** [comment]
Does the server support webfinger?

**Comment by michaelstingl** [comment]
Can be reproduced with proper Webfinger setup.

![CleanShot 2023-02-03 at 17 13 28](https://user-images.githubusercontent.com/214010/216652929-3bb96e1b-d85c-4b25-9c51-7af7b1dd2958.png) | ![CleanShot 2023-02-03 at 17 14 11](https://user-images.githubusercontent.com/214010/216652993-358e3c03-6bbc-40a2-bfc5-41a49835266a.png)
-- | --

3.1.0 client:
- https://cloud.owncloud.com/index.php/f/5962115

Theme:
- https://gitea.owncloud.services/ownbrander/themes/src/commit/fa0026e6134f6bbceefec3f51143786886e1e97f/zivcloud/mirall

**Comment by fmoc** [comment]
You need to enter a username before the button will be enabled.

**Comment by michaelstingl** [comment]
> You need to enter a username before the button will be enabled.

Maybe a special macOS issue?

![CleanShot 2023-02-07 at 11 16 36@2x](https://user-images.githubusercontent.com/214010/217217313-6feff452-97d0-4f91-9c1a-0bc451f40692.png)

```
branded 3.1.0.10011 e99d0f
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-22.3.0
```

**Comment by fmoc** [comment]
General problem. Fix on the way.

**Comment by HanaGemela** [comment]
Passed in qa-3.2.0.10094-rc1 mac
