### ISSUE TITLE
[QA] FabLab client can't login to oAuth2-enabled server and doesn't ask for username

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10447]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

FabLab client can't login to oAuth2-enabled server 
Client 3.1.0 https://cloud.owncloud.com/index.php/f/5960114 
Logs https://cloud.owncloud.com/index.php/f/5960152

### Steps to reproduce the issue

1. Install 3.1. FabLab client 
2. Connect to [ocis.ocis-keycloak.released.owncloud.works](https://ocis.ocis-keycloak.released.owncloud.works/)

And note that the client doesn't ask for username

### Screenshots

<img width="718" alt="Screenshot 2023-02-01 at 12 59 25" src="https://user-images.githubusercontent.com/49001702/216038089-ba7fc943-2a52-4cc5-b6ad-efeddcadbc8f.png">

### Expected behavior

Login flow works 

### Actual behavior

Client doesn't ask for username
And can't connect to [ocis.ocis-keycloak.released.owncloud.works](https://ocis.ocis-keycloak.released.owncloud.works/)

**Comment by TheOneRing** [comment]
The client only asks for the username when webfinger or basic auth is used.
From the logs:
```
23-02-01 12:59:52:006 [ warning sync.credentials.oauth ]:	Error when getting the accessToken "Error returned from the server: <em>Code not valid</em>
```
We also send the http error page which should have appeared in your browser, stating `Code not valid`

**Comment by HanaGemela** [comment]
Yes, @jnweiger confirmed that the config is his special setting

**Comment by jnweiger** [comment]
I am only saying, that each config IDP may need some fine tuned settings, and I have no overview which branding works where. Sorry.
