### ISSUE TITLE
[QA] Advanced settings for sync of large folders missing in GUI

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10456]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Missing section in setting in GUI - see screenshot. Hana Client doesn't provide these options.

Could be because of VFS? 
VFS settings is:
VFS - yes 
Enforce virtual files - yes

But that should be only for Win. This is mac client 3.1.0 https://cloud.owncloud.com/index.php/f/5961797

Then I've set:
Define folder sync limit - checked 
Folder sync limit - 598

It has been changed in this commit https://gitea.owncloud.services/ownbrander/themes/commit/de01a37d90f01034c13a5b217646f136baeec07d

But the client used for this bug report has been built 4 commits later from https://gitea.owncloud.services/ownbrander/themes/commit/778f872ecec8a7f30de9fae1d8c666c86fb38e71

### Steps to reproduce the issue

1. Build a client with:

Define folder sync limit - checked 
Folder sync limit - 598

2. Check if this settings is available in GUI

I don't think these steps are sufficient. There will be also some other condition for sure

### Screenshots

<img width="1321" alt="Screenshot 2023-02-03 at 10 10 47" src="https://user-images.githubusercontent.com/49001702/216559464-a25fc965-736e-416a-aa28-cbb2c8f74059.png">

### Expected behavior

All settings available

### Actual behavior

Missing settings section

**Comment by TheOneRing** [comment]
If vfs is enforced the section which is not affecting vfs, is hidden.
`Theme::forceVirtualFilesOption`

**Comment by HanaGemela** [comment]
From ownBrader `Check this if you want to enforce native WinVFS.`

Mac client should not be affected

**Comment by michaelstingl** [comment]
Expectation: These options present in non-experimental branded builds with selective sync

**Comment by HanaGemela** [comment]
Passed qa 3.2.0.10140-rc1 mac
