### ISSUE TITLE
Fix crash reports

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10451]
We need to update breakpad in order to support m1.

We are currently using an old fork, for breakpad tools, and an old submodule for the crash reporter.

Related:
https://github.com/owncloud/craft-blueprints-owncloud/pull/21/files
https://github.com/owncloud/client/issues/6005

**Comment by TheOneRing** [comment]
Breakpad was updated.
It appears however that the old version of dump_syms we use doesn't provide the symbols in the way we require.

symsorter looks like a promising replacement.
https://github.com/getsentry/symbolicator/releases/tag/0.6.0

See https://docs.sentry.io/platforms/apple/data-management/debug-files/symbol-servers/

**Comment by TheOneRing** [comment]
We now use symsorter, sentry still complains about some symbols.

**Comment by HanaGemela** [comment]
Tested by @michaelstingl on m1
