### ISSUE TITLE
Versioned configuration files

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#10466]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Users like @dragotin or us developers regularly use older versions than the development version. As our configuration files do not ensure forward compatibility (see, e.g., #10465), downgrading may or may not work with a configuration file that is compatible with the latest version (we perform migrations only in one way, from old to new versions).

### Proposed solution

To "fix" the problem, we could version the configuration files or even the whole configuration directory. This is showcased by JetBrains' IDEs for instance: every IDE release creates a new versioned directory (e.g., `~/.config/JetBrains/PyCharm2022.3/`). Depending on the IDE and configuration, you may be asked whether you want to migrate the files from the old configuration directory, otherwise the old files are migrated automatically.

In our case, we could have a `~/.config/ownCloud/3.1.0` directory that contains both config file and cookies database. When upgrading to, e.g., 4.0, a new directory `~/.config/ownCloud/4.0.0` will be created and the configuration files will be migrated. This allows both clients to be used in parallel (the old client continues to use the old config while the new client uses the migrated one). By defining a distinct migration event rather than having to upgrade or downgrade constantly, the configuration files will be detached from each other and can be edited separately. This is acceptable in my opinion, since downgrading is not a common operation.

In fact, we already have a similar setup with our different themes: Both the `ownCloud` and `testpilotcloud` clients can configure the same directories etc., but they have different configuration directories. Running multiple clients on the same directory should be recognized in some way (e.g., because either client can't open or lock the sync db); in fact, running multiple clients at the same time is already prevented by Qt's single instance feature.

Of course, this will only see any use in the release after the one where this feature is introduced.

### Alternative solutions you considered

Instead of maintaining a `.config/ownCloud/<version>/` directory, we could just version the configuration file itself (e.g., `~/.config/ownCloud/owncloud.cfg.3.1.0`. I think copying the entire directory is much better, though.

**Comment by TheOneRing** [comment]
This would also require version databases and versioned sync folders.
We try to prevent downgrades for a reason.

**Comment by TheOneRing** [comment]
See: https://github.com/owncloud/client/issues/10473
