### ISSUE TITLE
[QA] selective sync setting is ignored

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10468]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

seen with damkencloud 3.1.0 on opensuse leap 15.4

* Start damkencloud client. It uses oauth and offers a button [Open Browser]. Click this.
* Authenticate the client with the web browser session at cloud.damken.com
* Click open [ ] Advance Configuration.
  - switch from 'Download everything (recomended)' to 'Configure synchronization manually'
* Select a local folder name (as suggested)
* Select a remote destination folder: (Why is this called a destination??? It is the source in my case)
* I am selecting folder 'emco' which has two subfolders: 
![grafik](https://user-images.githubusercontent.com/1108546/217095032-5b11667a-0fee-47af-9aef-18d21193d604.png)
* Next I deselect folder images, to save some bandwidth:
![grafik](https://user-images.githubusercontent.com/1108546/217095267-98ca7a8c-28a0-43a8-a4d2-51419cb683da.png)
* Click 'Add Sync Connection' - syncing starts:
![grafik](https://user-images.githubusercontent.com/1108546/217095477-ed0ed33c-7b8a-4fa5-86ea-b91d9c198283.png)

Note that it starts to sync 1.6 GB, which is too much. 
Check the selective sync setting:
![grafik](https://user-images.githubusercontent.com/1108546/217095644-66e8af17-f7ec-4ba6-afcc-a9b972cada63.png)

Both folders are selected. BAD.

Expected behaviour:
- deselected folders during connection setup do not start to sync.

Workaround
- deselect folder images again after the sync started. This works as expected. 

### Steps to reproduce the issue

.

### Screenshots

.

**Comment by michaelstingl** [comment]
@HanaGemela looks like an additional regression test is needed. Please coordinate with @TheOneRing . Can this be added to the automated test?

**Comment by saw-jan** [comment]
Client: `qa 3.2.0.10140-rc1 74126d`

1. :information_source: No `Select a remote destination folder` window
2. :heavy_check_mark: `Deselect remote folders ...` window
![Screenshot from 2023-02-14 11-51-12](https://user-images.githubusercontent.com/52366632/218653826-d6965e01-1115-4701-a845-b901bea07575.png)

3. :heavy_check_mark: Only selected folder is synced
![Screenshot from 2023-02-14 11-51-36](https://user-images.githubusercontent.com/52366632/218653839-a33347a4-f89e-44df-9b70-08d18775ce4a.png)
