### ISSUE TITLE
Make sure app name etc. can only be queried from theme

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#10461]
We should define `APPLICATION_NAME` and friends only on the theme code and call `Theme::instance()->property()` everywhere.

See e.g., https://github.com/owncloud/client/pull/10458/commits/d1f3a827208481ed37c315eb35327c5ab22b56bb.

**Comment by saw-jan** [comment]
Is this only the code refactoring? Or can be tested in some way?
CC @TheOneRing
