### ISSUE TITLE
[QA] unexpected debug output

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10467]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen with client 3.1.0 on linux.
When called from the command line, additional output is seen:
```
$ damkencloud -v
gui.platform: adding plugin directory "/opt/ownCloud/damkencloud/bin/../lib64/plugins"
damkencloud damkencloud 3.1.0.9987
e99d0f
Libraries Qt 5.15.2, OpenSSL 1.1.1l  24 Aug 2021 SUSE release 150400.7.19.1
Using virtual files plugin: suffix
opensuse-leap-5.14.21-150400.24.41-default

$ BtR -v
gui.platform: adding plugin directory "/opt/ownCloud/btr/bin/../lib64/plugins"
libpng warning: iCCP: CRC error
btr btr 3.1.0.9951
https://github.com/owncloud/client/commit/e99d0f90375fc3801d38d6761cbb319ea714ddb0
Libraries Qt 5.15.2, OpenSSL 1.1.1l  24 Aug 2021 SUSE release 150400.7.19.1
Using virtual files plugin: suffix
opensuse-leap-5.14.21-150400.24.41-default
suse@localhost:~> 
```

The line "gui.platform: adding plugin directory ..." should not be there.
The line "libpng warning: iCCP: CRC error" should not be there.

Expected behaviour:
- debug output is only printed, when called with --debug.

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

.

### Actual behavior

.

**Comment by fmoc** [comment]
>  The line "libpng warning: iCCP: CRC error" should not be there.

Doesn't show up in your log. Please include the complete log.

I don't think we can get rid of the plugin path directory. The order of operations requires us to print that while no logger is available. We cannot make it a debug message.

**Comment by jnweiger** [comment]
The message from libpng probably directly comes from libpng, and would not show up in owncloud log files.
Probably can be avoided by having PNG files without color profile in the theme.
Probably can be disabled by setting some flags like PNG_FLAG_CRC_ANCILLARY_NOWARN in libpng.
Not sure, where our libpng comes from. System? Qt5?

**Comment by jnweiger** [comment]
Caused in this case by:
```
$ pngcheck btrtesting/mirall/theme/colored/btr-icon-1024.png
btrtesting/mirall/theme/colored/btr-icon-1024.png  CRC error in chunk iCCP (computed 4be1e6c5, expected 72e6e67d)
```

**Comment by TheOneRing** [comment]
> Caused in this case by:
> 
> ```
> $ pngcheck btrtesting/mirall/theme/colored/btr-icon-1024.png
> btrtesting/mirall/theme/colored/btr-icon-1024.png  CRC error in chunk iCCP (computed 4be1e6c5, expected 72e6e67d)
> ```

I suggest you fix your png.

**Comment by fmoc** [comment]
> We could remove the log message and add the text to the about statement.

I think the idea was to print it as early as possible to allow for debugging deployment problems. If the client crashes prematurely, we can't access the about dialog. Unless now with the "off" plugin the client will always have a fallback. @TheOneRing is that the case?

Of course we could also just add a custom CLI flag for this and refactor arguments parsing (which got better in https://github.com/owncloud/client/pull/8632, but could still use some love).

**Comment by TheOneRing** [comment]
The about text is shared between -v and the about dialog.
So it should work here too.

**Comment by TheOneRing** [comment]
Yes but debug output in -v will break scripts.

**Comment by fmoc** [comment]
That's why I'd make it a separate CLI flag and want to refactor CLI parsing.

**Comment by TheOneRing** [comment]
Yes but we need to fix the issue for 3.2.
Refactoring the parser and the application instance it totally out of scope for 3.2

**Comment by TheOneRing** [comment]
On mac we also have additional log output.
`sync.utility: migrateLaunchOnStartup: has launch agent plist: false has deprecated launch on startup: false`

I will remove that line for now, but for 4.0 we really need to fix that properly.
Meaning: Setup the logger BEFORE we setup Application.

**Comment by saw-jan** [comment]
```bash
$ ./qa-3.2.0.10140-rc1-x86_64.AppImage -v    
qa qa 3.2.0.10140-rc1
https://github.com/owncloud/client/commit/74126d1a0046b93034ed96b3e3a8ac107dac67c7
Libraries Qt 5.15.5, OpenSSL 1.1.1q  5 Jul 2022
Using virtual files plugin: suffix
ubuntu-5.15.0-60-generic

```
