### ISSUE TITLE
[QA] Client installation builds for CentOS is missing but mentioned in the docs

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#10463]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

There is no installation build and guides for the CentOS in the download page and the builds `.tar` file (see [download page](https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/) and [builds](https://download.owncloud.com/desktop/ownCloud/stable/3.1/linux/))
But the installation on CentOS is mentioned in the [docs](https://doc.owncloud.com/desktop/3.1/installing.html#system-requirements)

Qn: Are we expecting the builds for CentOS? or do the docs need to be updated? or something else?

**Comment by michaelstingl** [comment]
2.11.1 had old Qt version that worked with CentOS 7, but 3.0.x Qt doesn't work with CentOS 7.

**Comment by HanaGemela** [comment]
Also Fedora need adjustments

**Comment by HanaGemela** [comment]
and openSUSE Leap as well

**Comment by michaelstingl** [comment]
Was already for 3.2:
- https://github.com/owncloud/docs-client-desktop/pull/372

https://doc.owncloud.com/desktop/3.2/installing.html#system-requirements-and-installation

@HanaGemela @saw-jan works for you?

**Comment by HanaGemela** [comment]
Docs updated
