### ISSUE TITLE
[WebFinger] WebFinger not a good user-facing term

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10474]
The step shouldn't be called WebFinger. This is only a technical term.

![CleanShot 2023-02-07 at 11 16 36@2x](https://user-images.githubusercontent.com/214010/217217313-6feff452-97d0-4f91-9c1a-0bc451f40692.png)

```
branded 3.1.0.10011 e99d0f
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-22.3.0
```

@tbsbdr What would be a good term? (English + German)

Instance Lookup? Server Lookup?

**Comment by tbsbdr** [comment]
hehe 👉very fingerish👈

### Thoughts
first thought was something with "~~auto~~" but this would still be about some processes going on "backstage" -> not interesting for the user.
Would "Username" or better "User" or **Your Account** work as this is what the user needs to enter?

### My favourite:
- `Your Account`

... as it's a more personal wording. @michaelstingl do you agree?

**Comment by michaelstingl** [comment]
> ### My favourite:
> * `Your Account`
> * `Dein Account`
> 
> ... as it's a more personal wording. @michaelstingl do you agree?

Shouldn't be too similar to the next step "Credentials"

<img width="489" alt="CleanShot 2023-02-08 at 12 37 11@2x" src="https://user-images.githubusercontent.com/214010/217519446-553b3182-a836-4e5f-a0ab-183e817ce994.png">

**Comment by michaelstingl** [comment]
@fmoc @TheOneRing go for `Your Account` / `Dein Account` ?

**Comment by fmoc** [comment]
Makes no sense to me, really. The "credentials" page also is about "my account", after all. For this very special edge case we have here, I could imagine calling this page "Username"...

**Comment by d7oc** [comment]
> Makes no sense to me, really. The "credentials" page also is about "my account", after all. For this very special edge case we have here, I could imagine calling this page "Username"...

Maybe it might make sense to rename the "credentials" step to "Authentication" / "Authentifizierung" as you enter the credentials there, but the step you are actually doing at that point is Authentication.

Similar to that the "Webfinger" step could also be named "Lookup". As you enter the username there but what the step really does is looking up a user.

Just my 2 cents.

**Comment by tbsbdr** [comment]
Yes, we should tune the wordings for "credentials" or "Authentication" as well. Both are not every-day words for most people. How does just `Login` instead of `Credentials` sound to you, @fmoc and @michaelstingl ?

**Comment by fmoc** [comment]
Works for me.

**Comment by HanaGemela** [comment]
Passed in qa-3.2.0.10094-rc1 mac
