### ISSUE TITLE
[QA] testpilot 3.1 downloads expose minio url to the public

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10470]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen while looking for 3.1 testpilotcloud build:

![grafik](https://user-images.githubusercontent.com/1108546/217102205-d16743d7-d276-4c7f-9e25-c2459fe746ad.png)

The minio url is found in testing and daily, but not in stable.

Expected behavour:
* the repo is initialized using repo-admin.py 
* links in a repo at download.owncloud.com contain only references to download.owncloud.com 

### Steps to reproduce the issue

.

### Screenshots

.

**Comment by jnweiger** [comment]
Best solution is to remove the hardcoded --url and rely on the new .repo-admin.prefix feature.

**Comment by fmoc** [comment]
I do not see how this makes anything better here, @jnweiger. You still need to pass the right data.

**Comment by fmoc** [comment]
The issue was that `bash` was not installed and our CI didn't care to report the problem.

**Comment by fmoc** [comment]
Fixed in the CI:

- https://gitea.owncloud.services/client/build-linux/pulls/21
- https://gitea.owncloud.services/client/build/commit/ab5361159e1fd1bc66a17af7c6b0f776420b2348

**Comment by saw-jan** [comment]
3.2.0.10080-rc1 doesn't expose the minio url (same for 3.2 daily): :heavy_check_mark: 

![Screenshot from 2023-02-13 16-11-10](https://user-images.githubusercontent.com/52366632/218433678-b07d3cfc-316a-4176-9559-88e549d34818.png)
