### ISSUE TITLE
[QA] Branded sync folder is not added to the Explorer's sidebar

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10472]
Waiting for config in https://github.com/owncloud/enterprise/issues/5586 …

**Comment by saw-jan** [comment]
Tested with `qa 3.2.0.10140-rc1 74126d` (client has no vfs option)

:heavy_check_mark: Sidebar folder is added

![Screenshot from 2023-02-14 12-14-22](https://user-images.githubusercontent.com/52366632/218657200-3ed2f4f5-2855-4838-97f8-16ce1c595db4.png)
