### ISSUE TITLE
[QA] Mac: Can't quit the client from Dock when Wizard is open

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10485]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Can't quit the client from Dock when Wizard is open
Client 3.1.0
mac 13.2

### Steps to reproduce the issue

1. Click 'Add account' in GUI
2. Right click on the ownCloud icon in Dock 
3. Quit

### Screenshots

![Image](https://github.com/owncloud/client/assets/200626/683ec133-dd89-402e-bd8a-7a9e607aea71)

No screenshot

### Expected behavior

User can quit the client

### Actual behavior

Client remains running

**Comment by TheOneRing** [comment]
It's kind of what you requested when you complained that you could abort the wizard by accident.

**Comment by TheOneRing** [comment]
![image](https://user-images.githubusercontent.com/200626/217512896-3b5bbd33-f1a5-4b87-acfe-9c2b5787a415.png)

Works as designed.
When we have open dialogs on mac the menu is disabled.

**Comment by HanaGemela** [comment]
Then after clicking quit from the Dock, user should be asked if he really wants to cancel account setup

**Comment by TheOneRing** [comment]
I couldn't event click quit as the menu is disabled.
See screenshot.

**Comment by HanaGemela** [comment]
I meant the icons at the bottom of the screen

**Comment by erikjv** [comment]
macOS actually sends an expose event, not a quit/close event. With Qt 6.4, the window gets raised, but not over the active application (unless it's the Finder). I'm not sure if the not-raising-over-active-application is a macOS policy, but in Qt 6.5 dialogs are implemented using native dialogs, so the behaviour there might be different/better.

So we should re-test this with Qt 6.5

**Comment by TheOneRing** [comment]
Fixed in 6.0 as we no longer use a modal dialog.
