### ISSUE TITLE
[4.0] [OIDC] "No connection configured" after application access was removed in Keycloak

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10494]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When 4.0 client starts after application access was removed in Keycloak, it shows misleading "No connection configured" message.

### Expected behavior

Client should start with proper login prompt after token refresh failure.

### Steps to reproduce the issue

1. Connect 4.0 desktop sync client to https://ocis.team.owncloud.works ✅ 
2. Restart 4.0 desktop sync client  ✅ (`testpilotcloud-0209_21.58.39.341.log.gz`)
3. Quit 4.0 desktop sync client
4. Remove application access in Keycloak (https://keycloak.team.owncloud.works/auth/realms/oCIS/account/#/applications)
5. Launch 4.0 desktop sync client  ➡️ "No connection configured" ⚠️ (`testpilotcloud-0209_22.00.18.892.log.gz`)
6. Quit 4.0 desktop sync client
7. Launch 4.0 desktop sync client  ➡️ Prompts for login ✅ (`testpilotcloud-0209_22.01.15.586.log.gz`)

## Desktop Client

![CleanShot 2023-02-09 at 21 59 15](https://user-images.githubusercontent.com/214010/217941842-9ff4c043-86d6-4409-b85e-be48d369b4a0.png) | ![CleanShot 2023-02-09 at 22 00 33](https://user-images.githubusercontent.com/214010/217941769-7868c154-afd9-40e7-8ca0-4f6a7752a897.png) | ![CleanShot 2023-02-09 at 22 01 35](https://user-images.githubusercontent.com/214010/217941756-e600d5d4-e2a5-4c3f-9367-91b43ad3814e.png)
-- | -- | --
(2) Restart 4.0 desktop sync client  ✅ | (5) Launch 4.0 desktop sync client  ➡️ "No connection configured" ⚠️ | (7) Launch 4.0 desktop sync client  ➡️ Prompts for login ✅

## Keycloak

![CleanShot 2023-02-09 at 21 59 27](https://user-images.githubusercontent.com/214010/217941528-72439678-c21c-4fe4-b726-e98699db3858.png) | ![CleanShot 2023-02-09 at 21 59 33](https://user-images.githubusercontent.com/214010/217941546-1a4bbf0a-be1c-4700-aaed-4d11e894ae7e.png) | ![CleanShot 2023-02-09 at 22 02 49](https://user-images.githubusercontent.com/214010/217941601-80e5a44b-19cc-4957-8b9c-7cb92a7983e7.png)
-- | -- | --

### Logs

https://cloud.owncloud.com/index.php/f/5963264

```
testpilotcloud-0209_21.58.39.341.log.gz
testpilotcloud-0209_22.00.18.892.log.gz
testpilotcloud-0209_22.01.15.586.log.gz
```

### Client version number

```
% /Applications/testpilotcloud.app/Contents/MacOS/testpilotcloud --version    
sync.utility: migrateLaunchOnStartup: has launch agent plist: true has deprecated launch on startup: false
testpilotcloud testpilotcloud 4.0.0.10074-daily20230209
6ba0a9
Libraries Qt 5.15.8, OpenSSL 1.1.1t  7 Feb 2023
Using virtual files plugin: suffix
osx-22.2.0
```

### Server information

https://ocis.team.owncloud.works

```
ownCloud Web UI 6.0.0-rc.6 
Infinite Scale 2.0.0-rc.1 Community 
```

**Comment by TheOneRing** [comment]
Relevant message:
```

23-02-09 22:00:19:541 [ info sync.httplogger ]:	"4f4e9011-7fa3-41b2-8066-1cb21901aed0: Response: POST 400 (Error: Error transferring https://keycloak.team.owncloud.works/auth/realms/oCIS/protocol/openid-connect/token - server replied: Bad Request,83ms) https://keycloak.team.owncloud.works/auth/realms/oCIS/protocol/openid-connect/token Header: { Cache-Control: no-store, Content-Length: 78, Content-Type: application/json, Date: Thu, 09 Feb 2023 21:00:19 GMT, Pragma: no-cache, Referrer-Policy: no-referrer, Strict-Transport-Security: max-age=31536000; includeSubDomains, X-Content-Type-Options: nosniff, X-Frame-Options: SAMEORIGIN, X-Xss-Protection: 1; mode=block, } Data: [{\"error\":\"invalid_grant\",\"error_description\":\"Offline user session not found\"}]"
```
See: https://github.com/owncloud/client/blob/0531ebdb6e2d43de68b2298b95ab1ec4e2c1529d/src/libsync/creds/oauth.cpp#L662

**Comment by saw-jan** [comment]
Tested with `ownCloud 4.0.0.10422-daily20230316 8e8490`

Client:

![Screenshot from 2023-03-16 13-33-28](https://user-images.githubusercontent.com/52366632/225550144-66f48189-36e6-41fb-8dc6-33d182b9676d.png) | ![Screenshot from 2023-03-16 13-35-48](https://user-images.githubusercontent.com/52366632/225550162-639abdec-86c6-4cdb-9a3d-e757ddc7b36d.png)
-- | --
(2) Restart 4.0 desktop sync client  ✅ | (5) Launch 4.0 desktop sync client -> Prompts for login ✅

Keycloak:

![Screenshot from 2023-03-16 13-33-54](https://user-images.githubusercontent.com/52366632/225550555-81c5f02b-ad8a-45c0-b0b8-0290e7e3e265.png) | ![Screenshot from 2023-03-16 13-34-04](https://user-images.githubusercontent.com/52366632/225550582-9cc4348f-0da2-4a12-9fd7-2e68189dc843.png) | ![Screenshot from 2023-03-16 13-34-31](https://user-images.githubusercontent.com/52366632/225550599-0434c005-4b57-4a97-8636-9685c1da9ea1.png)
-- | -- | --
||
