### ISSUE TITLE
Client AUT crashes with oCIS server

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#10498]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Client AUT crashes while running Squish tests against the oCIS server.

CI failure on master: https://drone.owncloud.com/owncloud/client/14283

Client: `4.0.0-git f56b10`
oCIS: `2.0.0`

### Logs
```
 Test 'tst_editFiles' aborted because the AUT crashed
Process /drone/src/build/bin/owncloud -s --logfile - --logdebug --logflush --confdir /tmp/owncloud-client/ exited abnormally, return code -1: Received signal number 6.. Dumped core.

OSError: [Errno 22] Invalid argument
```
![Screenshot from 2023-02-13 10-02-47](https://user-images.githubusercontent.com/52366632/218369377-f8f96aa3-a07a-401e-a919-8abf5ec9d9dd.png)

Stacktrace: [stacktrace-ocis.log](https://github.com/owncloud/client/files/10718618/stacktrace-ocis.log)
Testlog: [serverlog-ocis.log](https://github.com/owncloud/client/files/10718622/serverlog-ocis.log)

**Comment by michaelstingl** [comment]
@fmoc anything we can use for bug hunting?

@saw-jan any change we can get the crash Id?
 https://doc.owncloud.com/desktop/3.1/appendices/troubleshooting.html#crash-reports

**Comment by fmoc** [comment]
Problem was introduced in https://github.com/owncloud/client/pull/10422. One of these assertions fails: https://github.com/owncloud/client/pull/10422/files#diff-b0159ef26964eede011c7eb85930ce8acf9289a14f2e258577678c2aa0470db8R130-R131

Not sure if this is a bug in #10422 or #10422's changes helped us discover an existing bug.

**Comment by saw-jan** [comment]
> @fmoc anything we can use for bug hunting?
> 
> @saw-jan any change we can get the crash Id? https://doc.owncloud.com/desktop/3.1/appendices/troubleshooting.html#crash-reports

I will definitely try to get the crash report :+1:

**Comment by saw-jan** [comment]
I got this this morning:
crash id: `153314a7-fb70-4d5b-b4d6-34293403452a`

![Screenshot from 2023-02-15 09-06-16](https://user-images.githubusercontent.com/52366632/218918790-c215e2e4-2175-485d-80d3-a33d8937f85f.png)

**Comment by TheOneRing** [comment]
The crash id is from a 3.2 client, the issue here can only occur on 4.0.
Also the crash appears to happen in the autoupdater.

**Comment by TheOneRing** [comment]
I was able to reproduce https://github.com/owncloud/client/blob/0531ebdb6e2d43de68b2298b95ab1ec4e2c1529d/src/libsync/propagateuploadtus.cpp#L122-L122

**Comment by saw-jan** [comment]
> The crash id is from a 3.2 client, the issue here can only occur on 4.0. Also the crash appears to happen in the autoupdater.

Ohh, maybe it's because I have multiple clients on my machine :smile: . Crash window appeared and I just reported :sweat_smile:

**Comment by TheOneRing** [comment]
I have a fix should be good once merged.

**Comment by saw-jan** [comment]
> I have a fix should be good once merged.

yeah, CI looks happy with it
