### ISSUE TITLE
[Spaces] "Personal" and "Shares" not on top of sync folder list

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10501]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

"Personal" and "Shares" Spaces not on top of sync folder list.

### Expected behavior

"Personal" and "Shares" Spaces should be on top of sync folder list.

### Steps to reproduce the issue

1. `katherin:gemini` creates Space on https://ocis.ocis-traefik.latest.owncloud.works/ , then shares with `einstein:relativity`
2. Setup 4.0 client for `einstein:relativity`

### Screenshots

![CleanShot 2023-02-14 at 11 04 06@2x](https://user-images.githubusercontent.com/214010/218703563-514a6bb5-aa5e-45aa-86d3-c49110f29195.png) | ![CleanShot 2023-02-14 at 11 04 20@2x](https://user-images.githubusercontent.com/214010/218703586-f2f77163-e230-4bb5-92ca-1f3d7c515019.png)
-- | --
⚠️ | ✅

### Logs

[testpilotcloud.log](https://github.com/owncloud/client/files/10731200/testpilotcloud.log)

### Client version number

```
testpilotcloud 4.0.0.10138-daily20230213 f56b10
Libraries Qt 5.15.8, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: suffix
osx-22.2.0
```

### Server information

```
ownCloud Web UI 7.0.0-rc.12 
Infinite Scale 2.0.0+2b0457362 Community 
```

**Comment by saw-jan** [comment]
Tested with desktop-client `ownCloud 4.0.0.10398-daily20230313 f8e194`

Expected: :x: "Personal" and "Shares" Spaces should be on top of sync folder list

![Screenshot from 2023-03-15 16-41-52](https://user-images.githubusercontent.com/52366632/225291596-c1507015-6f2b-4126-b801-26b7740aff40.png) | ![Screenshot from 2023-03-15 16-49-07](https://user-images.githubusercontent.com/52366632/225291634-ba2ec858-24f7-4db8-a4b2-21edc940bf8a.png)
-- | --
:heavy_check_mark: | :x:

CC @TheOneRing

**Comment by saw-jan** [comment]
Tested with desktop-client `ownCloud 4.0.0.10422-daily20230316 8e8490`

Expected: :heavy_check_mark:  "Personal" and "Shares" Spaces should be on top of sync folder list

![Screenshot from 2023-03-16 09-48-31](https://user-images.githubusercontent.com/52366632/225511533-1d238b1a-43f4-49c7-aec3-29583ae9da02.png) | ![Screenshot from 2023-03-16 09-48-53](https://user-images.githubusercontent.com/52366632/225511543-14612736-b23f-4b86-84cd-6dc61d980346.png)
-- | --
:heavy_check_mark: | :heavy_check_mark:

CC @TheOneRing
