### ISSUE TITLE
Add brandable button in top toolbar

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#10518]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Some of our customers may want to add a custom button to the toolbar in the settings window to, e.g., open a link in the browser.

### Proposed solution

See the screenshot:

![screenshot_2023-02-20_12-16-55](https://user-images.githubusercontent.com/80399010/220091059-2362be2e-0367-4492-af58-ede7d97ef80b.png)

### Alternative solutions you considered

The button could be placed anywhere, really. Three properties should be configurable through branding parameters:

- button logo (possibly different icons for dark and light modes)
- button text
- button action (or just URL)

**Comment by TheOneRing** [comment]
We need to support arbitrary subtitles, so using the title for the icon was a bit short sighted.

**Comment by michaelstingl** [comment]
Example theming commit for testing:
- https://github.com/owncloud/enterprise/issues/5576#issuecomment-1487015598

**Comment by HanaGemela** [comment]
The button is there in qa 4.0.0.10572-daily20230404, mac

**Comment by rizlas** [comment]
Is this available in ownBrander?

**Comment by michaelstingl** [comment]
> > Is this available in ownBrander?
> 
> No

Please get in touch with ownCloud support team for more information.
