### ISSUE TITLE
[QA] Missing Ubuntu 21.10 package

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10522]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Missing Ubuntu 21.10 package

### Steps to reproduce the issue

Damken cloud damkencloud-3.2.0.10202-linux.tar doesn't include the package

### Screenshots

No screenshot

### Expected behavior

Packages for all supported platforms have been built
https://doc.owncloud.com/desktop/3.2/installing.html#system-requirements

### Actual behavior

Missing Ubuntu 21.10 package

**Comment by fmoc** [comment]
21.10 has been end of life since mid 2022 and has been announced deprecated. The docs are outdated. Closing here.

**Comment by fmoc** [comment]
See https://github.com/owncloud/docs-client-desktop/pull/380.
