### ISSUE TITLE
Replace https://doc.owncloud.org/ help url with doc.owncloud.com/

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10539]
Seen with desktop client 3.0 and server 10.11.0

* Connect client to server, wait for initial sync.
* Change one file simultaneously on server and client. wait for sync.
* A conflict error occurs. OK
![grafik](https://user-images.githubusercontent.com/1108546/216598913-bf6852ba-0b0a-491d-8d1b-fa7363f87dd3.png)

* Click on the yellow link in the client. the client shows the not synced details. OK
![grafik](https://user-images.githubusercontent.com/1108546/216600216-aeb33c35-868d-4e32-a2f3-165edc53821d.png)

* Click the link at the bottom.
* A browser window opens for https://doc.owncloud.org/desktop/3.0/conflicts.html
* But this is immediately redirected to https://doc.owncloud.com/docs/next/ where we have a short section about client 3.0, but nothing about conflict resolution.

**Comment by michaelstingl** [comment]
Vanilla app needs to be fixed in [`theme.cpp`](https://github.com/owncloud/client/blob/master/src/libsync/theme.cpp). 4.0?

**Comment by HanaGemela** [comment]
https://doc.owncloud.com/desktop/4.0/conflicts.html in ownCloud 4.0.0.10490-daily20230324
Passed - the url has been changed
