### ISSUE TITLE
Sparkle updater errors are not logged sufficiently

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#10531]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

When using a self-hosted HTTP-only update server, the Sparkle updater reports an error:

<img width="265" alt="image" src="https://user-images.githubusercontent.com/80399010/220929949-af87e4b8-3ef0-458f-bcac-574bca0a1611.png">

One would assume that the updater now terminates, but it seems to continue:

<img width="620" alt="image" src="https://user-images.githubusercontent.com/80399010/220930126-dd49b9d2-2cbd-44be-9fa3-db4b79a32b14.png">

So far, so good. Now, when we click `Install update`:

<img width="443" alt="image" src="https://user-images.githubusercontent.com/80399010/220930347-cd8e30a5-fa96-4170-a6a1-5b08927aa639.png">

My guess is that since the URL provided by the updater is also HTTP and not HTTPS, the updater refuses to continue. Unfortunately, we can't tell for sure. The regular Sparkle updater log, `~/Library/Logs/SparkleUpdaterLog.log` is not being used by our own updater. This is likely due to the fact that we use the Objective-C API, which provides some handlers to handle errors manually. We do use some of these handlers, but this seems insufficient.

Long story short: we need better error logging for the Sparkle updater. Currently, it is impossible to tell for sure why the scenario described above failed.

### Proposed solution

Looking at Sparkle's [updater API docs](https://sparkle-project.org/documentation/api-reference/Protocols/SPUUpdaterDelegate.html), I noticed we only override a few of the handlers. I could imagine we need to override more of these (basically all of them which are passed an error). 

### Alternative solutions you considered

Maybe we can enable writing a log file to our config directory, or maybe there is a callback interface that can provide Sparkle's log messages to us. If possible, we should increase the verbosity of the update server.

### Additional context

I am going to deploy the config used to produce this bug on our demo update server later. I'll provide a URL then.

Another Sparkle issue (which is not really related, but could be worked on, too, while we're at it anyway): https://github.com/owncloud/client/issues/7592

**Comment by fmoc** [comment]
Turns out they're logged, but only on debug level. We should "upgrade" (pun intended) updater errors to at least warning level.

**Comment by HanaGemela** [comment]
Expected result: we now log the localised error message on warning level in the log, and the full error on info level
The info level is for debugging purposes: it's an object dump of the NSError object.
