### ISSUE TITLE
Log mac energy saver events

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10546]
MacOS wakes up a macbook air periodically for a short moment.
If we trigger a token refresh during one of the wakeups, the computer might have returned to sleep before we received an answer.

- Log the events to better understand issues related to periodic wakeups.
- As we might want to block traffic during such a wakeup, design it  with the possibility to emit signals.

Related:
https://ladydebug.com/blog/2020/05/21/programmatically-capture-energy-saver-event-on-mac/

**Comment by michaelstingl** [comment]
Maybe avoid performing tasks during wake from [Power Nap](https://support.apple.com/en-gb/guide/mac-help/mh40773/13.0/mac/13.0) ? (Can be disabled on Intel Macs, always active in Apple Silicon)
