### ISSUE TITLE
Install wizard: Inform user about VFS and implications

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/client#10555]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Problem: Currently the user is not well informed that he/she needs an internet connection in most cases to access files.

## 1. Proposal (my Favourite)
If VFS is available, provide an option and implicit info about VFS.
![image](https://user-images.githubusercontent.com/26610733/222227173-713c1297-9890-4c97-8d7b-1a9c56eb5afe.png)
(Advanced options would need to be adjusted as well in this scenario)

## 2. Proposal
Just inform the user that VFS is enabled and that she/he needs internet to access files in most cases.
![image](https://user-images.githubusercontent.com/26610733/222228134-ed157e70-0ecb-44f5-a7e7-b408802844c1.png)

I'd favour "Proposal 1" as it provides a easy possibility to switch to "Download all".

**Comment by michaelstingl** [comment]
@hodyroff @tbsbdr branding option or general product?

/cc @TheOneRing

**Comment by tbsbdr** [comment]
Heuristics: I checked box, onedrive and google drive install wizards yesterday and they don't highlight the on-demand concept upfront any more as they did ~a year ago. Further more the on-demand concept was made very well known via netflix, spotify et al. (everyone knows that you can't netflix if you'r not online).

But: Having no access to your files is a real blocker in a work routine scenario, so I'd say it would be fair to inform the user that the new "On-Demand" standard has landed for your synclient as well. We should communicate that the standard has changed. (we might remove it after 2-3 years)

**--> General product**

**Comment by tbsbdr** [comment]
discussed with @hodyroff and @TheOneRing , agreed not to do it.
