### ISSUE TITLE
[QA] [4.0] "No connection configured" shown if connection status is unknown

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10557]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Server is down, but 4.0 client shows "No connection configured".

### Steps to reproduce the issue

Tested with

```
testpilotcloud 4.0.0.10306-daily20230301 8d1874
Libraries Qt 5.15.8, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: suffix
osx-22.2.0
```

### Screenshots

![CleanShot 2023-03-02 at 10 29 21@2x](https://user-images.githubusercontent.com/214010/222389290-b71551a7-7e7b-4a53-863f-b8706cea50ff.png) | ![CleanShot 2023-03-02 at 10 29 03@2x](https://user-images.githubusercontent.com/214010/222389318-b94e1d98-4592-474c-95b0-748a704dd420.png)
-- | --
wrong status at startup | switches to correct status after a while

**Comment by saw-jan** [comment]
Tested with `ownCloud 4.0.0.10434-daily20230317 ddeb95`

Expected: No `No connection conf...` text at startup :heavy_check_mark: 

![Screenshot from 2023-03-17 16-31-17](https://user-images.githubusercontent.com/52366632/225883754-500ab44c-7ac3-4597-b71e-cbb1c78c55d9.png) | ![Screenshot from 2023-03-17 16-31-26](https://user-images.githubusercontent.com/52366632/225883760-b6d43982-5346-40d2-85d1-5f4c3079550a.png)
--|--
|1. Connecting :heavy_check_mark: | 2. Disconnected :heavy_check_mark: |

![Screenshot from 2023-03-17 16-24-48](https://user-images.githubusercontent.com/52366632/225885113-65975de3-7d9e-42d3-9dcb-837c350da2e7.png)
|--|
| (Ubuntu) Disconnected :heavy_check_mark: |
