### ISSUE TITLE
[QA] Cannot send crash report on mac

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10561]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Cannot send crash report on mac btr 3.2.1.10303-rc1

### Steps to reproduce the issue

Start the client with --debug option
Select 'Crash now' in the context menu when clicking on the tray icon

### Screenshots

<img width="697" alt="Screenshot 2023-03-02 at 16 25 55" src="https://user-images.githubusercontent.com/49001702/222473072-87b79eda-9736-4ed6-8a0c-374d106482bf.png">

### Expected behavior

Report has been sent and assigned a number

### Actual behavior

Sending failed.

This message in terminal:

```
RESPONSE: ""
Error: 301 "Protocol \"\" is unknown"
```

**Comment by TheOneRing** [comment]
Branded clients have no report server configured.

**Comment by HanaGemela** [comment]
Then don't show the windows if it doesn't work
