### ISSUE TITLE
[QA] conflict state is not resolved by removing the conflict file

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10569]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen with testpilotcloud client 3.2.0.10176 and server 10.12.0-rc.2

* Connect client to server,
* Change a file on the server,
* Quickly also change the same file locally.
* A conflict occurs. OK.
* Messages are show in the 'Not Synced' tab, and a message in the main window indicates the conflict. OK.
![grafik](https://user-images.githubusercontent.com/1108546/222811072-3514a766-0a33-4cb6-97aa-a0972fc9a9cb.png)
![grafik](https://user-images.githubusercontent.com/1108546/222811110-b053da78-66a7-4b7d-a9d3-709dba996c49.png)
----
* User studies the tow copies locally, and decides to remove the one named "... (conflicted copy ...) ..."
* Wait for next sync run. Nothing happens. The conflict messages remain. BAD.
* User edits the file locally. 
* The file is happily uploaded to the server
![grafik](https://user-images.githubusercontent.com/1108546/222811541-ed09ee31-5433-453e-93fa-3638d6bb07fd.png)
-----
* Wait for next sync run. Still nothing happens. The conflict messages remain. BAD.
* User edits the file on the server.
* Wait for next sync run. The file gets downloaded correctly. But still the messages remain in both places.
* Renaming also does not change the messages.

It is unclear, what actions should be done to remove the messages after clearing the conflict.

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

.

### Actual behavior

[tp10569-log.zip](https://github.com/owncloud/client/files/10885756/tp10569-log.zip)

**Comment by fmoc** [comment]
Can you try to force the sync and see if the error goes away?

**Comment by jnweiger** [comment]
> Can you try to force the sync and see if the error goes away?

Yes. Same as normal sync. The file is already synced. But the error message remains.

**Comment by TheMrAnderson** [comment]
I've noticed the same thing for a while now.  One of my folders I have synced is my repo folder so I can switch machines and pick up where I left off the other.  Most of the time it goes off without a hitch, but here lately it's been saying there are conflicted files within this folder.  I'm on Linux on both machines and running the latest client.  Just to verify there were no more conflicted files I ran the following command "find . -name "* (conflicted copy*" -type f" and it returned no results after I had resolved all the conflicts.

**Comment by Salipa-Gurung** [comment]
Tested with ` ownCloud version 4.0.0.10458-daily20230320 `
oCIS Server: [ocis.ocis-traefik.latest.owncloud.works](https://ocis.ocis-traefik.latest.owncloud.works/)

Expected: Conflict error message eliminated after clearing conflict

> In windows

| ![Screenshot from 2023-03-20 15-24-23](https://user-images.githubusercontent.com/53458341/226303436-f3b6c648-462b-47f6-bf92-6567711a4ee8.png)  ![Screenshot from 2023-03-20 15-24-44](https://user-images.githubusercontent.com/53458341/226303496-b40d2949-45c0-4920-8dc2-028cbad32c52.png) | ![Screenshot from 2023-03-20 15-26-35](https://user-images.githubusercontent.com/53458341/226303595-bda8c70a-312e-45ab-9f1d-31dd9f6c3334.png) ![Screenshot from 2023-03-20 15-26-18](https://user-images.githubusercontent.com/53458341/226303544-42772a19-9212-4144-bf5e-c206a9062a4b.png)
|--|--|
| Conflict error message displayed during conflict | Conflict error message eliminated after clearing conflict :heavy_check_mark:  |
