### ISSUE TITLE
[QA] folder icons are confusing in selective sync

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10567]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen with 10.12.0-rc.2 and testpilotcloud client 3.2.0.10176
* Install the server using files_primary_s3, add an SFTP mount.
* User alice shares the folder 'alice docs'  with user admin
* Admin connects with the client, not using VFS.
* The selective sync list looks like this:
![grafik](https://user-images.githubusercontent.com/1108546/222805297-c6641dc5-948a-4483-b096-075bcec2b9c3.png)
----
* The folder 'alice docs' has a normal folder icon, although it is a shared folder, not owned by admin. BAD
* The folder 'SFTP has the 'remote storage' icon. It is an external storage. OK.
* All other folders also have the 'remote storage' icon, although they are on admin's primary storage. BAD.

 

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

Folders on the primary storage should have the normal folder icon.
Shared folders are marked with a frog-foot Icon in the web UI. Can we do the same in the client UI?

### Actual behavior

.

**Comment by TheOneRing** [comment]
Not planned.
Selective sync is currently not in our focus and will in the future be displayed less prominent.
In the file Browser we already display it.

**Comment by michaelstingl** [comment]
@jnweiger (HTTP) log available?
