### ISSUE TITLE
[QA] Cannot install 3.2.1 rc3 on Windows

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10570]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Cannot install 3.2.1 rc3 on Windows

### Steps to reproduce the issue

1. Install ownCloud-3.2.1.10328-rc3.x64.msi on Windows 10

### Screenshots

<img width="503" alt="Screenshot 2023-03-05 at 23 28 56" src="https://user-images.githubusercontent.com/49001702/222991379-bdac7cfe-1c90-4262-90cc-963a1ed3bec8.png">

<img width="347" alt="Screenshot 2023-03-05 at 23 29 57" src="https://user-images.githubusercontent.com/49001702/222991390-1ed6d48a-a7f8-48b3-8563-e5a2332684fd.png">

### Expected behavior

ownCloud has been install

### Actual behavior

Error message

**Comment by fmoc** [comment]
Which version of Windows?

**Comment by michaelstingl** [comment]
@HanaGemela anything in the logs?
https://doc.owncloud.com/desktop/next/installing.html#windows-installer-logging

@fmoc issues in the build job? Signing failed etc?

**Comment by fmoc** [comment]
Testpilotcloud v3.2.1 RC 3 installs just fine on Windows 10. ownCloud v3.2.1 RC 3 also installs fine on Windows 10. Cannot reproduce at this point. I'll try Windows 11 next.

**Comment by HanaGemela** [comment]
```
=== Verbose logging started: 06/03/2023 11:36:39 Build type: SHIP UNICODE [5.00.10011.00](https://5.00.10011.00/) Calling process: C:\Windows\system32\msiexec.exe ===

MSI (c) (18:6C) [11:36:40:005]: Font created. Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg


MSI (c) (18:6C) [11:36:40:005]: Font created. Charset: Req=0, Ret=0, Font: Req=MS Shell Dlg, Ret=MS Shell Dlg


MSI (c) (18:60) [11:36:40:083]: Resetting cached policy values

MSI (c) (18:60) [11:36:40:083]: Machine policy value 'Debug' is 0

MSI (c) (18:60) [11:36:40:083]: ******* RunEngine:

******* Product: ownCloud-3.2.1.10328-rc3.x64.msi

******* Action:

***** CommandLine: ********

MSI (c) (18:60) [11:36:40:114]: Note: 1: 2203 2: ownCloud-3.2.1.10328-rc3.x64.msi 3: -2147286775

MSI (c) (18:60) [11:36:40:114]: MainEngineThread is returning 1620

=== Verbose logging stopped: 06/03/2023 11:36:40 ===
```

**Comment by HanaGemela** [comment]
Windows 10 Home, OS build 19045.2604

Yes, testpilot worked fine

**Comment by HanaGemela** [comment]
Installation now worked with a new VM

**Comment by fmoc** [comment]
Can you update your Windows 10 Home installation and retry, please?

**Comment by HanaGemela** [comment]
It was failing on 19045.2006 then I've updated to 19045.2604 and still failing.
I've tried again on 19045.2006 but fresh VM and worked well

**Comment by fmoc** [comment]
Fascinating. It also worked in both my Windows 11 VMs. I guess we can then call this a local problem then.

**Comment by HanaGemela** [comment]
OK
