### ISSUE TITLE
[Spaces] "Open in Web" in File Manager Context Menu

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10572]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

I'd like to open my Space in the browser directly from my file manager.

### Proposed solution

I'd propose to add the "Open in Web" action for a Space also in the context menu of my file manager.

### Additional context

![CleanShot 2023-03-06 at 18 37 19](https://user-images.githubusercontent.com/214010/223188020-1e1b1877-588f-49cd-a450-a1c67e21b24f.png) | ![CleanShot 2023-03-06 at 18 37 33](https://user-images.githubusercontent.com/214010/223188055-9044fe2b-f290-4959-bca9-aac601a93a82.png) | ![CleanShot 2023-03-06 at 18 38 19](https://user-images.githubusercontent.com/214010/223188075-e5cffcd5-2f01-49c2-b9f1-db2f9778e06a.png)
-- | -- | --
"Open in Web" in Space browser ✅  | "Open in Web" for each sync connection ✅  | no "Open in Web" action from file manager ⚠️

**Comment by saw-jan** [comment]
Tested with `ownCloud 4.0.0.10422-daily20230316 8e8490`

Expected: `Open in browser` file menu context :heavy_check_mark: 

![Screenshot from 2023-03-17 12-07-03](https://user-images.githubusercontent.com/52366632/225828860-f064639e-950e-40a6-81bc-9abdb870c002.png) | ![Screenshot from 2023-03-17 12-08-01](https://user-images.githubusercontent.com/52366632/225828875-76582b0d-d629-476b-b9dd-6d50bb670498.png) | ![Screenshot from 2023-03-17 12-08-25](https://user-images.githubusercontent.com/52366632/225828881-5eee8e7a-3ebf-4627-be0d-7a102cbdd707.png)
--|--|--
Context menu in sync connection :heavy_check_mark: | Context menu in right-click menu :heavy_check_mark: | Opens correct space in browser :heavy_check_mark:
