### ISSUE TITLE
[Spaces] Display Space subtitle instead of local folder in folder sync item

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10577]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

In new oCIS world, with multiple Spaces synced as multiple folder sync connection, all in the same parent folder, the displayed local path information isn't that important anymore. On the other hand, one user can receive multiple spaces with the same name, that can be distinguished with the Subtitle metadata information

### Proposed solution

We could display the Space subtitle instead of local folder in every folder sync item

### Additional context

![](https://user-images.githubusercontent.com/214010/223203141-ef08a345-88ec-4a70-91ca-cde13e09e86b.png)

**Comment by saw-jan** [comment]
Tested with `ownCloud 4.0.0.10422-daily20230316 8e8490`

Quota and Subtitle for spaces

![Screenshot from 2023-03-16 10-48-39](https://user-images.githubusercontent.com/52366632/225519828-9165a0a4-fe99-4858-a4da-92444e9c5879.png)

**Comment by michaelstingl** [comment]
Mixing local path and subtitles look strange? 🤔 /cc @tbsbdr

**Comment by TheOneRing** [comment]
We can hide the subtitle if none is set

**Comment by michaelstingl** [comment]
I thought about always hiding the local path.

**Comment by TheOneRing** [comment]
Too much white space?
