### ISSUE TITLE
[QA] Quota update is too slow

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10594]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Quota update is too slow
mac 
ownCloud 4.0.0.10373-daily20230310

### Steps to reproduce the issue

1. Set quota 
2. Upload the first file
3. Check used quota

### Screenshots

<img width="798" alt="Screenshot 2023-03-15 at 10 52 40" src="https://user-images.githubusercontent.com/49001702/225275737-810ea9b8-2233-4ee7-85ed-5bb02b842e81.png">

### Expected behavior

Quota is updated straightaway

### Actual behavior

It takes too long to update the quota

**Comment by TheOneRing** [comment]
Should not take longer than 30s for the quota to update which in my opinion should be quite ok

**Comment by TheOneRing** [comment]
Can you try with https://github.com/owncloud/client/pull/10600

**Comment by HanaGemela** [comment]
This could also be a solution for https://github.com/owncloud/client/issues/10453#issuecomment-1471471063

**Comment by HanaGemela** [comment]
I think this has fixed 10453. 
Quota update can take up to 30s cc @michaelstingl - please reopen if this is not sufficient 
Tested with ownCloud 4.0.0.10422-daily20230316, mac
