### ISSUE TITLE
Wizard: Implement selective sync for spaces

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10596]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Selective sync should be available when adding a new space on mac

### Proposed solution

User is offered a list of folders in space to sync

**Comment by michaelstingl** [comment]
Yes, could be similar to "add folder" process from oC10 when adding a new Space

![CleanShot 2023-03-16 at 10 06 24@2x](https://user-images.githubusercontent.com/214010/225568423-19f67262-eba4-4466-936c-69761cbb4829.png) | ![CleanShot 2023-03-16 at 10 06 56@2x](https://user-images.githubusercontent.com/214010/225568445-6f048893-9c88-4670-bfa2-de4b6ca12333.png) | ![CleanShot 2023-03-16 at 10 07 04@2x](https://user-images.githubusercontent.com/214010/225568458-f1cd7945-30a2-47bb-bdf8-ef4f5b1b35cb.png) | ![CleanShot 2023-03-16 at 10 07 26@2x](https://user-images.githubusercontent.com/214010/225568470-77be60a9-07b5-47a1-9774-4b3e3cc93acb.png)
-- | -- | -- | ---
(1) | (2) | (3) Not planned for Spaces | (4) would be nice to have for Spaces 👍

**Comment by HanaGemela** [comment]
Selective sync is available in ownCloud 5.0.0.11523-alpha.1, mac

**Comment by HanaGemela** [comment]
This message about "Unchecked folders..." takes up now a lot of space. Which I like as it makes is more obvious that there is some action required. But it wasn't this way so I'm just making sure it was changed on purpose - @fmoc @TheOneRing 

<img width="960" alt="Screenshot 2023-07-24 at 10 00 07" src="https://github.com/owncloud/client/assets/49001702/dba04d0b-404c-466e-b396-56df0182f8fd">

**Comment by TheOneRing** [comment]
> This message about "Unchecked folders..." takes up now a lot of space. Which I like as it makes is more obvious that there is some action required. But it wasn't this way so I'm just making sure it was changed on purpose - @fmoc @TheOneRing
> <img alt="Screenshot 2023-07-24 at 10 00 07" width="960" src="https://user-images.githubusercontent.com/49001702/255527945-dba04d0b-404c-466e-b396-56df0182f8fd.png">

Unrelated to this issue please open a new one.
