### ISSUE TITLE
(linux-ubuntu) Desktop client crashes when file-manager is opened

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#10603]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Desktop-client crashes when the file manger is opened

Reproduced with:
- [ownCloud-4.0.0.10422-daily20230316-x86_64.AppImage](https://download.owncloud.com/desktop/ownCloud/daily/4.0/linux-appimage/?sort=time&order=desc)
- fresh build from git master

### Expected behavior

Client to work fine while opening file manager

### Steps to reproduce the issue

1. Open the desktop client
2. Open file manager while the desktop client is open

### Logs

coredump: [coredump.txt](https://github.com/owncloud/client/files/10987911/coredump.txt)
log: [ownCloud.log](https://github.com/owncloud/client/files/10987697/ownCloud.log)
Crash report id: `4cbc8fca-ecf2-40ac-8f07-e9107a05747e`

### Client version number

ownCloud 4.0.0.10422-daily20230316 [8e8490](https://github.com/owncloud/client/commit/8e8490142435f85b30871ac0f2eabae86ac1eb37)
Libraries Qt 5.15.8, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: suffix
ubuntu-5.19.0-35-generic

### Desktop environment (Linux only)

Ubuntu 22.04

### Installation path (Windows only)

ownCloud-4.0.0.10422-daily20230316-x86_64.AppImage

**Comment by michaelstingl** [comment]
Where does the shell extension come from? Installed according our docs? What version?

**Comment by TheOneRing** [comment]
```
23-03-16 12:31:51:580 [ warning default ]:	Only C and default locale supported with the posix collation implementation
23-03-16 12:31:51:580 [ warning default ]:	Only C and default locale supported with the posix collation implementation
23-03-16 12:31:51:580 [ warning default ]:	Case insensitive sorting unsupported in the posix collation implementation
23-03-16 12:31:51:580 [ warning default ]:	Numeric mode unsupported in the posix collation implementation

```
Can you make sure that `LANG=en_US.UTF-8` is set to anything utf8?

**Comment by saw-jan** [comment]
I have this:
```bash
$ echo $LANG
en_US.UTF-8
```

**Comment by saw-jan** [comment]
Also seen with `win10`

Client:
```
ownCloud 4.0.0.10422-daily20230316 8e8490
Libraries Qt 5.15.8, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: wincfapi
windows-10.0.17763
```
Crash id: `911ad40b-8114-4711-a5fb-4e2ddc3b7e4a`
log: [ownCloud-0316_04.03.21.170.log](https://github.com/owncloud/client/files/10989861/ownCloud-0316_04.03.21.170.log)

Steps:
1. Install desktop-client 4.0 daily (Do not open yet)
2. Open file explorer
3. Now, open the desktop-client
4. Open a new file explorer instance (nothing crashes)
5. Close all the file explorers (above opened two)
6. Now, Open a new file explorer instance
7. Desktop-client crashes

Note: skip steps `2`, `4`, `5` to directly reproduce

https://user-images.githubusercontent.com/52366632/225599413-736773ab-a660-4550-9689-a083c4881765.mp4

**Comment by saw-jan** [comment]
Tested with `ownCloud 4.0.0.10458-daily20230320 9e0f47` (`Ubuntu 22.04` and `Win10`)

Expected: :heavy_check_mark: Client doesn't crash while opening the file manager
