### ISSUE TITLE
[QA] CLI Parameter "--list-languages" has wrong description

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10614]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Parameter description for `--list-languages` is `Override UI language.`, should be `List available languages.`

### Steps to reproduce the issue

1. Execute `/Applications/testpilotcloud.app/Contents/MacOS/testpilotcloud --help`

### Screenshots

```
% /Applications/testpilotcloud.app/Contents/MacOS/testpilotcloud --help
Usage: /Applications/testpilotcloud.app/Contents/MacOS/testpilotcloud [options] [<vfs file>]
testpilotcloud version 4.0.0.10457-daily20230320
File synchronization desktop utility.


Options:
  -h, --help             Displays help on commandline options.
  --help-all             Displays help including Qt specific options.
  -v, --version          Displays version information.
  -s, --showsettings     Show the settings dialog while starting.
  -q, --quit             Quit the running instance.
  --logfile <filename>   Write log to file (use - to write to stdout).
  --logdir <name>        Write each sync log output in a new file in folder.
  --logflush             Flush the log file after every write.
  --logdebug             Output debug-level messages in the log.
  --language <language>  Override UI language.
  --list-languages       Override UI language.
  --confdir <dirname>    Use the given configuration folder.
  --debug                Enable debug mode.

Arguments:
  vfs file               Virtual file system file to be opened (optional).
```

### Expected behavior

Parameter description for `--list-languages` should be `List available languages.`

### Actual behavior

Parameter description for `--list-languages` is `Override UI language.`

**Comment by HanaGemela** [comment]
Failed in 4.0.0.10490-daily20230324
Expected: List available languages.
Actual: Lists available translations, see --language.

**Comment by michaelstingl** [comment]
works for me
