### ISSUE TITLE
Always send a language header in all requests

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10619]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Latest oCIS notifications API (`/ocs/v2.php/apps/notifications/api/v1/notifications?format=json`) responds with translated content. Other endpoints will learn this too.

### Proposed solution

Desktop app should always send a language header in all requests which follows the Accept-Language spec:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language

### Additional context

Related:
- Web: https://github.com/owncloud/web/issues/8612
- iOS: https://github.com/owncloud/ios-app/issues/1193
- Android: https://github.com/owncloud/android/issues/3980

**Comment by michaelstingl** [comment]
> I would only enable that on a per endpoint basis, I don't know where we parse random strings and thus "only speak English"

Better send same to all endpoints.

**Comment by fmoc** [comment]
Note: @TheOneRing thinks there might be at least one location where we actually parse an error message from the server (somewhere in the common error handling). We may need to either replace this with a more reliable solution (if possible) or force an English locale in `Accept-Language` for these requests explicitly.

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/blob/e4ae0539664dbf1e9d3c522a7ec4bc41aebd4cb3/src/libsync/owncloudpropagator_p.h#L78-L87

**Comment by HanaGemela** [comment]
Passed ownCloud 5.0.0.11523-alpha.1
