### ISSUE TITLE
[3.2.][Linux]Client disconnects after suspend and waking up the computer

### ISSUE THREAD

**Issue by MojmirDocekal** [owncloud/client#10613]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

After suspending the computer (ownCloud client working) and waking it up, the ownCloud client doesn't connect to the server. Linux used: arch based distro (Garuda) with KDE DE. The same issue is on two other computers with arch Linux.

### Expected behavior

I expect the client reconnects after the network connection is re-established.

### Steps to reproduce the issue

1. start the ownCloud client (connects properly);
2. suspend the computer;
3. wake up the computer;
4. the client doesn't connect to the server with a message: "no connection".

### Client version number

owncloud-client 3.2.1.10355-1
Operating System: Garuda Linux 
KDE Plasma Version: 5.27.3
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.7-zen1-1-zen (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-6200U CPU @ 2.30GHz
Memory: 7.7 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 520
Manufacturer: HP
Product Name: HP SpectrePro x360 G2

### Desktop environment (Linux only)

Operating System: Garuda Linux  KDE Plasma Version: 5.27.3 KDE Frameworks Version: 5.104.0

### Client package version and origin (Linux only)

owncloud-client 3.2.1.10355-1

**Comment by MojmirDocekal** [comment]
Seems to be related to old and closed issue with 2.0 ownCloud client: https://github.com/owncloud/client/issues/3888

**Comment by michaelstingl** [comment]
Anything in the logs?
http://doc.owncloud.com/desktop/appendices/troubleshooting.html#log-files

**Comment by TheOneRing** [comment]
Behaviour should have been improved in 4.0

**Comment by MojmirDocekal** [comment]
Partial past from the log below. There's " disconnected or paused, terminating or descheduling sync folders" error but nothing else I can decipher as a clue:

23-03-21 16:22:57:294 [ warning gui.account.state ]:	checkConnectivity blocking: false
23-03-21 16:22:57:295 [ debug sync.connectionvalidator ]	[ OCC::ConnectionValidator::checkServer ]:	Checking server and authentication
23-03-21 16:22:57:295 [ debug sync.connectionvalidator ]	[ OCC::ConnectionValidator::checkServer ]:	Trying to look up system proxy
23-03-21 16:22:57:296 [ info sync.connectionvalidator ]:	No system proxy set by OS
23-03-21 16:22:57:364 [ info sync.checkserverjob ]:	status.php returns:  QJsonDocument({"edition":"Community","installed":true,"maintenance":false,"needsDbUpgrade":false,"product":"ownCloud@CESNET","productname":"ownCloud@CESNET","version":"10.10.0.3","versionstring":"10.10.0"})   QNetworkReply::NoError  Reply:  QNetworkReplyHttpImpl(0x55fc826951f0)
23-03-21 16:22:57:364 [ info sync.connectionvalidator ]:	** Application: ownCloud found:  QUrl("https://owncloud.cesnet.cz/")  with version  "10.10.0"
23-03-21 16:22:57:364 [ debug sync.connectionvalidator ]	[ OCC::ConnectionValidator::checkAuthentication ]:	# Check whether authenticated propfind works.
23-03-21 16:22:57:364 [ info sync.networkjob ]:	Created OCC::PropfindJob(OCC::Account("Mojmír Dočekal@owncloud.cesnet.cz"), "https://owncloud.cesnet.cz/remote.php/webdav/", "PROPFIND", Original-Request-ID: "96a8f8d1-4af8-4a62-b85e-e750cd2ded1c", X-Request-ID: "96a8f8d1-4af8-4a62-b85e-e750cd2ded1c") for OCC::ConnectionValidator(0x55fc826ab060)
23-03-21 16:22:57:365 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::needsRetry ]:	Not Retry auth job OCC::PropfindJob(OCC::Account("Mojmír Dočekal@owncloud.cesnet.cz"), "https://owncloud.cesnet.cz/remote.php/webdav/", "PROPFIND", Original-Request-ID: "96a8f8d1-4af8-4a62-b85e-e750cd2ded1c", X-Request-ID: "96a8f8d1-4af8-4a62-b85e-e750cd2ded1c", NetworkError: "Zadané nastavení nelze použít.") QUrl("https://owncloud.cesnet.cz/remote.php/webdav/")
23-03-21 16:22:57:365 [ info sync.networkjob.propfind ]:	LSCOL of QUrl("https://owncloud.cesnet.cz/remote.php/webdav/") FINISHED WITH STATUS "NetworkSessionFailedError, Zadané nastavení nelze použít."
23-03-21 16:22:57:365 [ debug sync.connectionvalidator ]	[ OCC::ConnectionValidator::reportResult ]:	OCC::ConnectionValidator::Timeout
23-03-21 16:22:57:371 [ info gui.folder.manager ]:	Account "Mojmír Dočekal@owncloud.cesnet.cz" disconnected or paused, terminating or descheduling sync folders
23-03-21 16:22:57:371 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job finished OCC::PropfindJob(OCC::Account("Mojmír Dočekal@owncloud.cesnet.cz"), "https://owncloud.cesnet.cz/remote.php/webdav/", "PROPFIND", Original-Request-ID: "96a8f8d1-4af8-4a62-b85e-e750cd2ded1c", X-Request-ID: "96a8f8d1-4af8-4a62-b85e-e750cd2ded1c", NetworkError: "Zadané nastavení nelze použít.")
23-03-21 16:23:59:294 [ warning gui.account.state ]:	checkConnectivity blocking: false
23-03-21 16:23:59:294 [ debug sync.connectionvalidator ]	[ OCC::ConnectionValidator::checkServer ]:	Checking server and authentication
