### ISSUE TITLE
[QA] GUI does not react when logging in while adding a new account

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10621]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

ownCloud 4.0.0.10444-alpha1
mac

### Steps to reproduce the issue

1. Log out of your account
2. Click Add new account 
3. Minimise the client
4. Right click on the icon in the top bar 
5. Select the account you're logged out of 
6. Click Log in

### Screenshots

No screenshots

### Expected behavior

For example: Adding a new account action is not interrupted or the pop-up to confirm the cancellation of adding a new account is shown

### Actual behavior

User can't click anything, the pop-up to confirm the cancellation of account setup is hidden somewhere. 

To get rid of that state:

1. Minimise the client
2. Right click on the owncloud icon in the bottom bar 
3. Select Quit -> The pop-up is finally shown

**Comment by TheOneRing** [comment]
Thats a feature.
You need to close the dialog to interact with the client.

**Comment by TheOneRing** [comment]
You can even see how the rest of the client is grayed out.

**Comment by TheOneRing** [comment]
Ok so you can't close that dialog?

**Comment by HanaGemela** [comment]
no

**Comment by TheOneRing** [comment]
Related: https://github.com/owncloud/client/issues/8421

**Comment by HanaGemela** [comment]
Fixed in ownCloud 4.0.0.10576-daily20230405, mac
