### ISSUE TITLE
[QA] The Help url in 4.0 daily builds returns 404 error

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10634]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

The Help url (https://doc.owncloud.com/desktop/4.0/) in 4.0 daily builds returns 404 error
Shouldn't we use next till we have a release?

### Steps to reproduce the issue

1. Click in the owncloud icon in the tray menu 
2. Click on Help

### Screenshots

No screenshot

### Expected behavior

Help has been shown

### Actual behavior

404 error

**Comment by HanaGemela** [comment]
Originally changed on @mmattel request https://github.com/owncloud/client/issues/10539#issuecomment-1446417190

**Comment by TheOneRing** [comment]
@mmattel suggested to always point to latest

**Comment by michaelstingl** [comment]
Then make it version-agnostic?
- `https://doc.owncloud.com/desktop/`

**Comment by HanaGemela** [comment]
Passed ownCloud 4.0.0.10542-daily20230331, mac
