### ISSUE TITLE
Change custom basic auth field display

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10633]
3 times the same information
![image](https://user-images.githubusercontent.com/200626/227482040-1336addc-a857-44d0-84e4-8f9fa2407e84.png)

**Comment by HanaGemela** [comment]
https://doc.owncloud.com/desktop/4.0/conflicts.html in ownCloud 4.0.0.10490-daily20230324

**Comment by michaelstingl** [comment]
Please configure the `User ID Hint` in oB:

<img width="677" alt="CleanShot 2023-03-28 at 10 41 11@2x" src="https://user-images.githubusercontent.com/214010/228180235-6eea8676-efae-4797-8bbd-00688c7a6e00.png"> | <img width="687" alt="CleanShot 2023-03-28 at 10 40 59@2x" src="https://user-images.githubusercontent.com/214010/228180265-d65967be-3e7e-4c46-a88c-38e5eb213abc.png">
-- | --

**Comment by fmoc** [comment]
Given the hint can be adjusted, this should not be needed any more.
