### ISSUE TITLE
[QA] WebFinger - Client always shows username at the bottom

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10635]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

No matter if user ID is email, username or custom, the client always shows username at the bottom

### Steps to reproduce the issue

1. Get a build with WebFinger 

### Screenshots

<img width="717" alt="Screenshot 2023-03-24 at 10 04 51" src="https://user-images.githubusercontent.com/49001702/227513230-33a294e0-c2e0-4df6-9c94-85e857e01d5c.png">

### Expected behavior

Please decide @michaelstingl 

### Actual behavior

No matter if user ID is email, username or custom, the client always shows username at the bottom

**Comment by HanaGemela** [comment]
Beginning of the discussion https://github.com/owncloud/enterprise/issues/5607#issuecomment-1429560928

**Comment by michaelstingl** [comment]
> ### Steps to reproduce the issue
> 1. Get a build with WebFinger

- Link to theme/commit?
- Link to binaries?

**Comment by michaelstingl** [comment]
Edge case with legacy WebFinger. No change needed. ✅
