### ISSUE TITLE
Autostart on Appimage contains the wrong path 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#10650]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

We're getting reports from users of the Appimage with the "autostart" feature. The `Exec` path is pointing to the wrong place on the PATH:

From `~/.config/autostart/cernbox.desktop`

```
[Desktop Entry]
Name=CERNBox
GenericName=File Synchronizer
Exec=/tmp/lvonfree/.mount_cernboeKENCY/usr/bin/cernbox
Terminal=false
Icon=cernbox
Categories=Network
Type=Application
StartupNotify=false
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Delay=10
```

Is that already 

### Expected behavior

The client should autostart with the right path to the binary

### Client version number

```
sudo dnf list --installed | grep cernbox
ocqt5129-libqt5-qttranslations.x86_64 5.12.9-6.6 @cernbox
ocqt5129-libsqlite3-0.x86_64 3.31.1-6.15 @cernbox
puppet-cernbox.noarch 2.4-2.el9.cern @locmap 
```

### Desktop environment (Linux only)

Almalinux 9

**Comment by michaelstingl** [comment]
@HanaGemela test with the 4.0 (branded?) pre-release AppImage?

**Comment by fmoc** [comment]
I need a proper version number, @SamuAlfageme. Qt 5.12.9 implies it's some 2.x release, where AppImages were just provided as a preview. We have fixed lots of bugs including autostart since.

**Comment by saw-jan** [comment]
Tested with `ownCloud 4.0.0.10690-daily20230418 4f0368`

1. Ubuntu22.04 :heavy_check_mark: 
```bash
[Desktop Entry]
Name=ownCloud
GenericName=File Synchronizer
Exec=/home/sawjan/Downloads/ownCloud-4.0.0.10690-daily20230418-x86_64.AppImage
Terminal=false
Icon=owncloud
Categories=Network
Type=Application
StartupNotify=false
X-GNOME-Autostart-enabled=true
X-GNOME-Autostart-Delay=10
```

**Comment by fmoc** [comment]
Confirms my own testing. Closing as resolved.
