### ISSUE TITLE
MacOS desktop Client stuck in Disconnected after reboot when server cannot be reached

### ISSUE THREAD

**Issue by nliechti** [owncloud/client#10654]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

My ownCloud server is only reachable behind a VPN. When the ownCloud client starts on system boot it seems to be stuck in 
the "Disconnected" state. 
If you quit and restart the Client with the VPN then connected, the authentication dialog pop's up and you have to authorise the client in the Browser again. This also happens if you start the client manually before being connected to the VPN.

If you start the client manually when connected to the VPN everything works fine.

It seems only to be a problem on the first launch after a reboot. After that everything works as intended.

### Expected behavior

If the first authentication fails, the server should try to reconnect the same way it does when you quit and restart the app manually.

### Steps to reproduce the issue

1. Have your ownCloud instance not accessible.
2. Restart the computer (tested only on MacOS)
3. Start ownCloud client
4. Make ownCloud server accessible from the computer
5. The client should now be stuck in "Disconnected"

### Client version number

ownCloud 3.2.1.10355 [9724d6](https://github.com/owncloud/client/commit/9724d662fd9a668a981c58a7db7c7231a4c5bfe1)
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-22.4.0

### Server information

ownCloud 10.11.0.6 on AlmaLinux 8

PHP 7.4.30 (cli) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.30, Copyright (c), by Zend Technologies

### Additional context

Authorisation is done via oAuth in the Browser.

**Comment by michaelstingl** [comment]
Could you check with the 4.0 pre-release builds?
- https://download.owncloud.com/desktop/ownCloud/testing/4.0.0.10444-alpha1/
- https://download.owncloud.com/desktop/testpilotcloud/testing/4.0.0.10443-alpha1/

Try with the `testpilotcloud` build to not mess up your production ownCloud setup.

**Comment by nliechti** [comment]
Hey thanks for the super fast reply, what exactly is the difference between the ownCloud and the thestpilotcloud client?

**Comment by nliechti** [comment]
The new 4.0.0 build does a bit better of a job to throw up the "Reauthentication" dialog when i open the client. But still needs to be spotted manually that it didn't work and the reauthentication shouldn't be necessary in the first place.

**Comment by nliechti** [comment]
Hey I have uploaded the logfile owncloud_github_10654.log.
It should contain the start without VPN connection and manual reconnection after the VPN is connected.

**Comment by nliechti** [comment]
@michaelstingl  @TheOneRing Thank you for your excellent support. I think i never had any issue solved as fast as this.
