### ISSUE TITLE
[QA] Authentication process failed message

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10653]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Authentication process failed message
ownCloud 4.0.0.10542-daily20230331,mac 

The Retry button just makes the message disappear and the account is logged out. After a short while the dialog pops up again with this message about failed process. 

### Steps to reproduce the issue

Not known

### Screenshots

<img width="717" alt="Screenshot 2023-04-03 at 09 16 16" src="https://user-images.githubusercontent.com/49001702/229459396-46e2754a-ac75-45dd-ac6e-d8b6493241d6.png">

### Expected behavior

@michaelstingl please define

### Actual behavior

23-04-03 09:21:59:261 [ info sync.httplogger ]:	"a1ca34fc-255f-4603-92aa-f834a2aa88c1: Request: GET https://ocis.ocis-traefik.released.owncloud.works/status.php Header: { OC-Connection-Validator: desktop, User-Agent: Mozilla/5.0 (Macintosh) mirall/4.0.0.10542-daily20230331 (ownCloud, osx-22.3.0 ClientArchitecture: x86_64 OsArchitecture: x86_64), Accept: */*, X-Request-ID: a1ca34fc-255f-4603-92aa-f834a2aa88c1, Original-Request-ID: a1ca34fc-255f-4603-92aa-f834a2aa88c1, } Data: []"
23-04-03 09:22:00:470 [ debug sync.credentials.http ]	[ OCC::HttpCredentials::fetchUser ]:	user already set, no need to fetch from settings
23-04-03 09:22:00:470 [ info sync.account ]:	Clearing cookies
23-04-03 09:22:00:471 [ info sync.account ]:	Clearing cookies
23-04-03 09:22:00:471 [ info gui.account.state ]:	AccountState state change:  "Asking Credentials" -> "Signed out"
23-04-03 09:22:00:473 [ info gui.folder.manager ]:	Account "Admin@ocis.ocis-traefik.released.owncloud.works" disconnected or paused, terminating or descheduling sync folders

**Comment by michaelstingl** [comment]
Not sufficient information. Please keep 👀 on it when @TheOneRing 's modal fix was merged 🤞
