### ISSUE TITLE
own cloud deleted all my files but kept the folders when sync from windows client

### ISSUE THREAD

**Issue by AndresArias09** [owncloud/client#10655]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Today I turned my pc on and my ownclient app for windows was Asking me to choice if I wanted to delete all my files from the remote server or if I wanted to keep them locally. I chose to keep them locally, but the client kept asking me the same thing. Finally I chose the delete files from server option, and the client stared to sync. Later, my files were completely deleted, so I Check my trash bin and no files were there.

Is there any option to recover these files?

I tried to execute the 

php restore.php --url=https://cloud.excellentiam.co --username="soporte.it" --password="XYZ" --date="2023-04-03"

command, but it says that there's nothing to recover

### Expected behavior

I expected to see my files in the trash bin in the web client, but there weren't any files in it

### Client version number

ownCloud 3.2.0 for Windows 11

### Desktop environment (Linux only)

Ubuntu 22.04.2 LTS

### Installation path (Windows only)

C:\Program Files\ownCloud

**Comment by michaelstingl** [comment]
> I chose to keep them locally, but the client kept asking me the same thing.

Sounds like bug. I hope we can fix this in one of the next versions. /cc @HanaGemela 

> Later, my files were completely deleted, so I Check my trash bin and no files were there

Local trash bin is on the roadmap, but no ETA yet.

For issues with your server trash bin, please open issue in the ownCloud 10 `core` repo.
