### ISSUE TITLE
Using the reconnect button can break the reconnect

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10666]
Doesn't work with [ocis.ocis-keycloak.latest.owncloud.works](https://ocis.ocis-keycloak.latest.owncloud.works/)
Tested with ownCloud 4.0.0.10373-daily20230310, mac

Steps to recreate:
1. Turn off wi-fi
2. Wait till the client gets into Disconnected state
3. Turn on wi-fi
4. Click Reconnect button

Actual result: Connecting but will never connect, remains offline
Expected result: Back online. Like when using demo.owncloud.com, that works well

_Originally posted by @HanaGemela in https://github.com/owncloud/client/issues/10033#issuecomment-1463925693_

**Comment by TheOneRing** [comment]
On servers with an app provider the client got stuck during the reconnect as we queued the request we waited for.

**Comment by HanaGemela** [comment]
Testing blocked by ocis.ocis-keycloak.latest.owncloud.works being down

**Comment by michaelstingl** [comment]
> Testing blocked by ocis.ocis-keycloak.latest.owncloud.works being down

Use one of the other demo instances?
- https://owncloud.dev/ocis/deployment/continuous_deployment/

Or is the error specific to the Keycloak instance?

**Comment by HanaGemela** [comment]
Specific to "servers with an app provider". What is it @TheOneRing ?

**Comment by michaelstingl** [comment]
> Specific to "servers with an app provider". What is it @TheOneRing ?

WOPI instances:
- https://owncloud.dev/ocis/deployment/continuous_deployment/#ocis-with-wopi-server

**Comment by HanaGemela** [comment]
Works with wopi ownCloud 4.0.0.10581-daily20230405, mac
