### ISSUE TITLE
Windows: The client crashes with very long sync roots

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10668]
Crash when adding `C:\Users\hana\ownCloudalotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\alotofletters\ - [demo@demo.owncloud.com](mailto:demo@demo.owncloud.com)`
as a local path, VFS on, long path off: `6c31aa65-fa20-4a44-b369-38b6a03fcc56`
ownCloud-4.0.0.10576-daily20230405.x64.msi

_Originally posted by @HanaGemela in https://github.com/owncloud/client/issues/10264#issuecomment-1497299672_

**Comment by HanaGemela** [comment]
With long path on: `ada44e9f-3f7f-4294-8990-629cbbcb705c`
