### ISSUE TITLE
Wizard: improve the behaviour if selected sync destination is unusable

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10680]
![image](https://user-images.githubusercontent.com/200626/230325840-5343cb8e-06cc-40c8-a952-2b0f2813af60.png)

**Comment by michaelstingl** [comment]
"Finish" button should be disabled.

@TheOneRing steps to reproduce? Permissions?

**Comment by HanaGemela** [comment]
Passed in ownCloud-5.0.0.11543-daily20230725.x64
