### ISSUE TITLE
Client renames local file after upload 

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10693]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Seen with testpilot 4.0.0 daily and server 10.12.1 RC3

* Connect client to server wait for initial sync.
* Create a file that has an UTF-8 umlaut in NFD form in its name. Here I am using an `ü` character, which is decomposed as 'u' followed by the diaeresis dots. hex bytes `75 cc 88`)
* Wait for the client to sync. 
* Wait a bit longer.
* Check the encoding. Now it is an NFC form `ü` (hex bytes `c3 bc`). BAD.
----
* Lowriter adds a .lock while editing. The client still renames it. Lowriter is surprised. BAD.
![grafik](https://user-images.githubusercontent.com/1108546/231414161-57263003-6e21-49ff-81b0-0ba0d1afeec4.png)
![grafik](https://user-images.githubusercontent.com/1108546/231415691-de1c7069-5a9b-4d72-9c4b-881e33058186.png)

### Expected behavior

* the client leaves the filename unchanged.
* lowriter does not report unexpected changes.

### Steps to reproduce the issue

Copy paste `these two ü and ü` and use them in a filename.

### Client version number

testpilotcloud 4.0.0.10620-daily20230412 dab5e4
Libraries Qt 5.15.2, OpenSSL 1.1.1f 31 Mar 2020
Using virtual files plugin: suffix
linuxmint-5.4.0-139-generic

### Additional context

Test motivated by

**Comment by TheOneRing** [comment]
Is that a real world scenario?
Please add steps to produce such a file.

**Comment by TheOneRing** [comment]
And how did you create that file?
On a file system where the encoding is mandatory I assume we would not be able to rename it?

**Comment by jnweiger** [comment]
I created mine on Linux by copy/paste from @jvillafanez 's github issue :innocent:
There is a nice (latex related) discussion on stackoverflow, that explains the Mac situation quite nicely: https://tex.stackexchange.com/questions/94418/os-x-umlauts-in-utf8-nfd-yield-package-inputenc-error-unicode-char-u8%CC%88-not
 
But yes, I am afraid, on a file system where the encoding is mandatory the rename would fail, possibly leading to inconsistencies.
To be tested on MacOS with HFS please.

**Comment by TheOneRing** [comment]
On mac we call QString::NormalizationForm_C in many cases.

**Comment by jvillafanez** [comment]
I'm not sure if there is anything to do for the client. The server is likely responding with a NFC filename, which is different than the one the client sent. In this case, I'm not sure what is expected. Renaming the file to match whatever the server has seems reasonable.

MacOS might need special handling because renaming to a NFC name might not be possible. If there hasn't been any complain, I guess it works and there is nothing to do.

> Is that a real world scenario?
Please add steps to produce such a file.

I don't know how customers end up having those kind of files, but sometimes they have them. I guess that's one of the reasons external storages have the "NFD compatibility" option.
In my case, I crafted the name, so it isn't a completely valid scenario.

**Comment by michaelstingl** [comment]
> To be tested on MacOS with HFS please.

Apple switched to APFS 2017:
- https://en.wikipedia.org/wiki/HFS_Plus

Could be added to the FAQ docs, but no need to fix stuff in the client.

**Comment by TheOneRing** [comment]
@HanaGemela can you open a doc issue please?

**Comment by michaelstingl** [comment]
More information:
- https://medium.com/@sthadewald/the-utf-8-hell-of-mac-osx-feef5ea42407
- https://gist.github.com/JamesChevalier/8448512 (`mac_utf8_insanity.md`)

**Comment by michaelstingl** [comment]
> @HanaGemela can you open a doc issue please?

Rare edge case, no action required. (for now) I'll maybe open docs issue the next time this pops up again…
