### ISSUE TITLE
folder sharing dialog misses Download/View/Upload

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#10690]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Seen with testpilotcloud 3.2.0.10176 (and 4.0.0.10620-daily20230412) and server 10.12.1 RC3

The sharing dialog for public folder links at the server has four differnet settings, only three of them are available in the client.
![grafik](https://user-images.githubusercontent.com/1108546/231195947-7761af6c-fd4a-4316-bdbc-660c65b690ce.png)

### Expected behavior

Identical sharing options at server and client.

### Steps to reproduce the issue

click.

### Screenshots

.

### Client version number

testpilotcloud 3.2.0.10176 718af2
Libraries Qt 5.15.2, OpenSSL 1.1.1f 31 Mar 2020
Using virtual files plugin: suffix
linuxmint-5.4.0-139-generic

**Comment by TheOneRing** [comment]
The dialog is deprecated and no longer maintained.

**Comment by voroyam** [comment]
> The dialog is deprecated and no longer maintained.

Do you mean the specific dialog option that @jnweiger is pointing to or the whole dialog?

**Comment by TheOneRing** [comment]
The share dialog.
With ocis we open the web.

**Comment by jnweiger** [comment]
Thanks for the info! So this is a valid issue with oc10 only.
