### ISSUE TITLE
Epic: Port to Qt6

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10701]
- Fix all Qt5 deprecation warnings
- https://github.com/owncloud/client/issues/10744
- https://github.com/owncloud/client/issues/10745
- https://github.com/owncloud/client/issues/8432 (Drop our copy of QSingleApplication) 
- https://github.com/owncloud/client/issues/10832
- https://github.com/owncloud/client/issues/10846
- https://github.com/owncloud/client/issues/10903
- https://github.com/owncloud/client/issues/10902
- https://github.com/owncloud/client/issues/10889
- https://github.com/owncloud/client/issues/10961

**Comment by michaelstingl** [comment]
@erikjv any help is appreciated… (split up in individual issues / PR's?)
