### ISSUE TITLE
[4] Spaces are not listed immediately when adding folder sync connection manually

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#10718]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Spaces are not listed immediately when adding account with `Configure sync manually` option.

![Screenshot from 2023-04-19 12-18-43](https://user-images.githubusercontent.com/52366632/232986720-ffdaa821-8a1c-4bf2-b405-d49810e99bdf.png)

But after waiting for some minutes (`~5 mins`), all spaces appear.

![Screenshot from 2023-04-19 12-27-19](https://user-images.githubusercontent.com/52366632/232988432-1436230d-4678-4f40-8167-47e13c21c715.png)

### Expected behavior

Personal and Shares spaces to be listed

### Steps to reproduce the issue

1. Build desktop-client (from `4` branch)
2. Start desktop-client
3. Add ocis server and authorize
4. From `Advanced configuration` choose `Configure sync manually` and Finish
5. Try to select spaces (Personal and Shares) - no spaces listed :x:

### Logs

ocis server logs:
```bash
desktop-client-testing-ocis-1  | 2023/04/19 06:36:35 http: TLS handshake error from 172.24.0.1:57342: EOF
desktop-client-testing-ocis-1  | 2023/04/19 06:36:35 http: TLS handshake error from 172.24.0.1:57350: EOF
desktop-client-testing-ocis-1  | 2023/04/19 06:36:38 http: TLS handshake error from 172.24.0.1:57378: remote error: tls: unknown certificate
desktop-client-testing-ocis-1  | 2023/04/19 06:36:38 http: TLS handshake error from 172.24.0.1:57382: remote error: tls: unknown certificate
desktop-client-testing-ocis-1  | 2023/04/19 06:36:40 http: TLS handshake error from 172.24.0.1:57406: remote error: tls: unknown certificate
desktop-client-testing-ocis-1  | 2023/04/19 06:36:40 http: TLS handshake error from 172.24.0.1:57396: remote error: tls: unknown certificate
desktop-client-testing-ocis-1  | 2023/04/19 06:36:40 http: TLS handshake error from 172.24.0.1:57426: remote error: tls: unknown certificate
desktop-client-testing-ocis-1  | 2023/04/19 06:36:40 http: TLS handshake error from 172.24.0.1:57432: remote error: tls: unknown certificate
desktop-client-testing-ocis-1  | 2023/04/19 06:36:40 http: TLS handshake error from 172.24.0.1:57438: remote error: tls: unknown certificate

# after around 5 minutes (when spaces are listed)
desktop-client-testing-ocis-1  | 2023-04-19T06:41:59Z ERR failed to authenticate the request error="failed to verify access token: token is expired by 15.117596269s" authenticator=oidc path=/remote.php/webdav/ service=proxy
```

### Client version number

ownCloud 4.0.0-git [12b7ee](https://github.com/owncloud/client/commit/12b7eea34e09377cb763976566c33d4c6a3eed40)
Libraries Qt 5.15.3, OpenSSL 3.0.2 15 Mar 2022
Using virtual files plugin: suffix
ubuntu-5.19.0-38-generic

### Server information

ocis `2.0.0`

**Comment by TheOneRing** [comment]
Hmm do you have client logs?

**Comment by saw-jan** [comment]
> Hmm do you have client logs?

here is the client log: [ownCloud.log](https://github.com/owncloud/client/files/11271182/ownCloud.log)

**Comment by HanaGemela** [comment]
I've added a new space in web ui and now also waiting till it'll be shown in 'Add a space' dialog...

**Comment by saw-jan** [comment]
Still experiencing the same problem. In the fix PR CI was not happy: https://github.com/owncloud/client/pull/10722#issuecomment-1514490704
Fixing this should make the CI green
CC @TheOneRing
