### ISSUE TITLE
[QA] Run GUI tests against early versions of the servers

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#10717]
### Describe the QA issue

Currently, we run squish GUI tests against the latest released versions of the servers (oC10 `10.12.1` and oCIS `2.0.0`).
In order to catch the regressions early, we may want to run tests against the early versions of the servers.

How and which early versions should we consider for testing client?
1. git master (unstable - changes frequently)
2. alpha and beta releases
3. RC releases

**Comment by saw-jan** [comment]
CC @HanaGemela @michaelstingl @TheOneRing @fmoc

**Comment by fmoc** [comment]
beta, RC and release should be good enough. I think we are not interested in unstable states of the server repositories, which the development branch and alpha releases clearly are. The APIs in there may not be stable.

> I'd run them when a tag is created - that means for each alpha, beta and RC

You mean a tag in the server repository?

**Comment by HanaGemela** [comment]
> beta, RC and release should be good enough. I think we are not interested in unstable states of the server repositories, which the development branch and alpha releases clearly are. The APIs in there may not be stable.
> 
> > I'd run them when a tag is created - that means for each alpha, beta and RC
> 
> You mean a tag in the server repository?

Yes, server repo

**Comment by saw-jan** [comment]
We will run tests against the latest rolling release of ocis server.
Closing in favor of https://github.com/owncloud/client/issues/11808
