### ISSUE TITLE
[QA] Error message displayed multiple times under a space 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10723]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Error message displayed multiple times under a space 

ownCloud 4.0.0.10697-daily20230419

### Steps to reproduce the issue

1. Add a new space
2. Disable the space in web ui
3. Force sync the space 
4. Make an action that will cause the space to sync again (again force sync or add a new space...)

### Screenshots

<img width="791" alt="Screenshot 2023-04-19 at 11 58 28" src="https://user-images.githubusercontent.com/49001702/233041445-059cf5de-63d3-4c15-852b-f4a0ac3b0dcd.png">

### Expected behavior

Message displayed just once

### Actual behavior

Each sync writes the same message

**Comment by TheOneRing** [comment]
Isn't that the case for all errors?

**Comment by HanaGemela** [comment]
Fixed in ownCloud 4.0.0.10718-beta2
