### ISSUE TITLE
[QA] Webfinger: local sync folder name uses lookup server, not the instance server

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10720]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Local sync folder name uses lookup server, not the instance server
ownCloud 4.0.0.10690-daily20230418

### Steps to reproduce the issue

1. Add a new space 

Test setup: https://github.com/owncloud/enterprise/issues/5579#issuecomment-1481259279

### Screenshots

No screenshot 

### Expected behavior

Local sync folder name includes the **instance** server name

### Actual behavior

Local sync folder name includes the **lookup** server name

**Comment by TheOneRing** [comment]
![image](https://user-images.githubusercontent.com/200626/233392966-2299f39f-aa31-4a29-8598-aed61ad4b6c5.png)
Testing passed

```
ownCloud 4.0.0.10716-daily20230420 [1f8a7d](https://github.com/owncloud/client/commit/1f8a7d6836d3adc7d86201bedb6f5a14261827ab)
Libraries Qt 5.15.8, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: wincfapi
windows-10.0.22621
```
