### ISSUE TITLE
Cache content to prevent re-download

### ISSUE THREAD

**Issue by zatricky** [owncloud/client#1074]
#### Situation/Issue

Example: Content on one client (A) is accidentally deleted or moved out of the shared folder. All other clients (B, C, D) remove the corresponding files.

Upon putting the content back (from backups/etc), A re-uploads the files to the server, and B, C, and D re-download these same files, resulting in a waste of bandwidth and possibly lost productivity.
#### Mitigation

The clients keep a cache of recently-deleted content. When it is found that the files need to be "put back", the content can simply be copied/moved back to the correct location, saving a download/upload.
#### Caveats/Dependencies/Notes
- This very likely depends on #110.
- Where possible, "cached" content could simply be a hardlinked version of the original file, thereby not taking up any extra diskspace. With a CoW filesystem this could be a snapshot/reflinked version of the file.
- The client should be configurable in so far as how far back to keep deleted content as well as how much diskspace can be "reserved" for deleted content.
- The server could benefit from a similar optimisation. Please let me know if I should create a corresponding issue there.
- In order for client A to potentially benefit from a cache in this scenario, ALL files would need to be stored in the cache. This would necessitate use of reflinked and/or hardlinked "copies" of _all_ files. The benefit would be the facilitation of "restore" functionality in the OwnCloud server interface. As above, please let me know if I should create a corresponding issue there.

**Comment by DeepDiver1975** [comment]
edge case we will not support
