### ISSUE TITLE
Qt6: Detect connection changes based on QNetworkInformation

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10745]
https://doc.qt.io/qt-6/qnetworkinformation.html

**Comment by TheOneRing** [comment]
Requires Qt6

**Comment by TheOneRing** [comment]
Removed in https://github.com/owncloud/client/pull/10746

**Comment by saw-jan** [comment]
Looks like only code refactoring. Nothing is to be tested manually. Moving to Done
CC @TheOneRing

**Comment by TheOneRing** [comment]
Please test how the client behaves on connection changes, loss of wifi and then reconnection etc

**Comment by saw-jan** [comment]
Tested with `ownCloud 5.0.0.11369-daily20230703 511b96`

Desktop client looks fine - connection changes don't break the client or sync process
