### ISSUE TITLE
Possibility to synchronize subfolder of a space

### ISSUE THREAD

**Issue by kaivol** [owncloud/client#10753]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Add the possibility to synchronize individual subfolders of a _Space_ to different, indepentent locations on the local system.

This would make it possible, for example, to use different physical drives for different folders or to synchronize predefined locations like Windows' Desktop folder.
I suppose it could also improve performance if only a small part of a potentionally huge _Space_ is synchronized. 

### Proposed solution

After clicking `Add Space` and subsequently choosing a _Space_ to add (e.g. `Personal`), I would like to be able to select a subfolder in the space. 

### Alternative solutions you considered

Alternatively one could use different _Spaces_ for this purpose, but I assume that this is not the intended use case for _Spaces_, as by default users don't even have the ability to create _Spaces_. 

### Additional context

I seem to remember that this was possible in older versions of ownCloud or the desktop client...

I'm using 
- owncloud oCIS cersion3.0.0-alpha.2+e0b6ca0e2
- desktop client version 4.0.0.10732-rc1 (Windows)
- also tried version 3.2.1 of the desktop client

**Comment by michaelstingl** [comment]
First, we plan the selective sync feature for Spaces in non-VFS mode:
- https://github.com/owncloud/client/issues/10596

No ETA for synchronization of subfolders of a space.

> ### Alternative solutions you considered
> Alternatively one could use different _Spaces_ for this purpose, but I assume that this is not the intended use case for _Spaces_, as by default users don't even have the ability to create _Spaces_.

Should be configurable in the future…

**Comment by mcarbonne** [comment]
That would be a great feature!
My goal is to replace my Synology Drive with an oCIS server. But the owncloud desktop client lacks this major feature (for my use case).
With Synology Drive, the process is pretty straightforward: you select a source folder (on the server), and a target folder on your computer (very similar to what @kaivol suggested).

Just out of curiosity, what is the process for choosing the next features to be developed (voting, internal decisions...)?

**Comment by sfadschm** [comment]
This is currently a serious disadvantage for people trying to migrate from OC10 to OCIS (be me ...).
As normals users cannot create spaces, the only workaround for now seems to be quite dirty as shown in the screenshots below.

OC10 (pretty):
![old](https://github.com/user-attachments/assets/50915b03-0cc8-4c68-a564-57a057e7a70b)

OCIS (not so much, and also prone to errors):
![new](https://github.com/user-attachments/assets/3465c35b-dac2-4d72-b66f-b0e43a6b04f5)

**Comment by TheOneRing** [comment]
Not planned

**Comment by sfadschm** [comment]
Understood.
What would be the preferred solution for this use case?
Using Spaces as "Top-Level Sync Folders"?

**Comment by TheOneRing** [comment]
Syncing arbitrary system folders is an advanced use case, likely involving users with permissions to create spaces. Therefore, I recommend using spaces in this scenario.

**Comment by AndyScull** [comment]
Hello, just a simple workaround that seems to be working for now, maybe because there actually is some back compatibility in client and OCIS.
Quit the client, edit owncloud.cfg, find your account and change this parameter - 0\supportsSpaces= true to false.
Since this is my first account in client, I don't know what will happen if you do it on non-empty one.
If you do it and start client again, your account will now have old "Add Folder" button, and wizard to select specific folder.
So far it's working for me, and I'll see how it works.
I don't expect it to keep working for long with updates coming out, but for now it's enough for me.
