### ISSUE TITLE
[QA] Release new online updater

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10755]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

New version of online updater is needed before the next release following 4.0.0

### Steps to reproduce the issue

1. Merge https://github.com/owncloud/client-updater-server/pull/147/files
2. Release the online updater with the new config

### Screenshots

No screenshot

**Comment by fmoc** [comment]
Done, see https://github.com/owncloud/client-updater-server/releases/tag/v0.7.3.
