### ISSUE TITLE
[QA] Small files don't get synced

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10756]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Small files don't get synced
ownCloud 4.0.0.10732-rc1

### Steps to reproduce the issue

1. Connect to demo.owncloud.com
2. In web ui create a new txt file
3. Sync the file to the client

### Screenshots

No screenshot

### Expected behavior

File gets synced

### Actual behavior

File doesn't get synced

**Comment by TheOneRing** [comment]
Can't reproduce

**Comment by HanaGemela** [comment]
Can't recreate either
