### ISSUE TITLE
[QA] Sync progress bar drawn over the three dots menu

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10759]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Sync progress bar drawn over the three dots menu
ownCloud 4.0.0.10732-rc1
mac

### Steps to reproduce the issue

1. Sync a large file

### Screenshots

<img width="783" alt="Screenshot 2023-04-25 at 19 54 40" src="https://user-images.githubusercontent.com/49001702/234367472-b79c73e8-f167-4229-a0bf-49b3e465d0a4.png">

### Expected behavior

Sync progress bar is not drawn over the three dots menu

### Actual behavior

Sync progress bar drawn over the three dots menu

**Comment by TheOneRing** [comment]
When testing please have an eye on the progress font size.
I'd also recommend to test with an rtl language and check whether the "option button" is clickable where its supposed to be.

**Comment by HanaGemela** [comment]
Passed in ownCloud 4.0.0.10771-daily20230426
