### ISSUE TITLE
Display Welcome page and spinner after an account was added

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10751]
When a new account is added and that account is subscribed to many spaces the client will require a couple of seconds to create all sync folders.

During this time the client appears unresponsive.

Display a welcome page and a spinner, until we are done.

**Comment by TheOneRing** [comment]
"Setting up account *spinner*"

**Comment by fmoc** [comment]
Please do not play any audio from the widget.

**Comment by HanaGemela** [comment]
There is an additional welcome page in ownCloud 5.0.0.11486-daily20230718, mac

<img width="742" alt="Screenshot 2023-07-18 at 10 29 33" src="https://github.com/owncloud/client/assets/49001702/a082f351-7565-4c01-b66e-9d97aa0dcdd9">
