### ISSUE TITLE
[QA] Windows VFS: Error when adding the folder C:/Users/currentUser as a new sync connection comes too late

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10762]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Windows VFS: Error when adding the folder C:/Users/currentUser comes too late

### Steps to reproduce the issue

1. Add a new folder sync connection when VFS is on and use local directory: C:/Users/currentUser

### Screenshots

<img width="754" alt="Screenshot 2023-04-26 at 09 56 27" src="https://user-images.githubusercontent.com/49001702/234511986-e05fe39c-9a3b-406d-810a-2e2d0f553a71.png">

### Expected behavior

Error gets displayed sooner so that user can choose another directory

### Actual behavior

Folder is added as a new sync connection but doesn't work due to Access denied error and there is no _easy_ way out of it

**Comment by michaelstingl** [comment]
> ### Expected behavior
> Error gets displayed sooner so that user can choose another directory

Can be improved in the future, but more difficult than it seems.
