### ISSUE TITLE
[QA] Suffix VFS: Make the current state clear

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10777]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

The current state of a virtual file is not clear
ownCloud 4.0.0.10776-daily20230427

### Steps to reproduce the issue

1. Turn on VFS
2. In the file manager in the context menu select "Make always available locally"

Now the third option from the bottom in the context menu says "Always available locally"

3. In the file manager in the context menu select "Free up local space"

Now the third option from the bottom in the context menu says "Available only online"

### Screenshots

<img width="278" alt="Screenshot 2023-04-27 at 11 37 22" src="https://user-images.githubusercontent.com/49001702/234824662-39ea825d-aadb-4db6-b85a-f3d1a13c1ca7.png">

### Expected behavior

Make it clear that this is the current state: 
Always available locally -> Currently always available locally
Available only online -> Currently available only online

There could also be a horizontal bar in the menu to separate the VFS options 

### Actual behavior

That third option from the bottom looks just like a duplicate to the other VFS options. And is always greyed out...

**Comment by michaelstingl** [comment]
No efforts planned for suffix VFS.
