### ISSUE TITLE
Pull dolphin extention out of main repo

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10770]
Dolphin requires its own version of system Qt and having it in the main repo makes things overly complicated.

**Comment by michaelstingl** [comment]
@TheOneRing @fmoc ping me, then we create a new repo. Name? `https://github.com/owncloud/client-desktop-whateveryouwant`

**Comment by michaelstingl** [comment]
New repo:
- https://github.com/owncloud/client-desktop-shell-integration-dolphin
