### ISSUE TITLE
[QA] vfs overlay icons are different from expected while moving vfs file into the hydrated-pinned folder

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/client#10778]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Moving dehydrated file (`online-only`) into pinned hydrated (`always available on this device`) folder does not change moved file as pinned and hydrated, rather the pinned and hydrated folder shows dehydrated status.

Windows
client version 4.0.0.10732-rc1

Before moving `online-only` file (report1 file) :

![Screenshot from 2023-04-27 16-22-33](https://user-images.githubusercontent.com/53458341/234838826-ba35bfe8-0811-4bca-b460-daa665e5f13f.png)

After moving `online-only` virtual file(report1) into `always available on this device` folder(Documents folder):

![Screenshot from 2023-04-27 16-22-58](https://user-images.githubusercontent.com/53458341/234838963-7a655290-c4ae-40de-80a3-350e4baed736.png)

![Screenshot from 2023-04-27 16-23-11](https://user-images.githubusercontent.com/53458341/234838994-601f1a84-cd86-47d4-be03-5db560c47d41.png)

-  `online-only` file remains same 
- instead `always available on this device` folder becomes `online-only` and shows `Available when online` status

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

Expected to see the moved dehydrated file to be downloaded and `always available on this device` status to be shown.

### Actual behavior

- moved file remains dehydrated and
- the pinned and hydrated folder in which it is moved also shows dehydrated status

**Comment by TheOneRing** [comment]
I'd say expected behavior.

- the move file will not change its pin state
- and the previously fully pinned folder now contains unpinned files
- it displays the cloud icon

Please compare to OneDrive

**Comment by Salipa-Gurung** [comment]
same behaviour in OneDrive
