### ISSUE TITLE
ownCloud Desktop client can not upload big files

### ISSUE THREAD

**Issue by MadriSX** [owncloud/client#10773]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

I am using "Guests" market app , this external app let any user share files with pseudo owncloud accounts linked to a shared folder, this way you can use ownCloud desktop app.

If I login using web (Chrome i.e.) and invited account I have no problems uploading >1 GB files, if I use webdav protocol using Desktop App, I can download big files but upload is limited to <10 MB files. If bigger ownCloud Desktop app shows just "error" state with no log information.

### Expected behavior

Uploading big files >10 MB should be equal using webdav than web interface.

### Steps to reproduce the issue

Add invited user, configure ownCloud Desktop app with the user, try to upload a file >10 MB

### Screenshots

![image](https://user-images.githubusercontent.com/9337015/234609781-3d9d693f-c7bc-40ec-8b53-86a3249e02ac.png)
![CORRECT_UPLOAD](https://user-images.githubusercontent.com/9337015/234609906-557a4b6e-5496-4745-a555-72155a9fe241.png)

### Logs
```
23-04-26 16:22:25:298 [ debug sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "post treewalk" and starting new transaction
23-04-26 16:22:25:298 [ debug sync.database.sql ]	[ OCC::SqlQuery::prepare ]:	SQL prepare "SELECT tmpfile, etag, errorcount, path FROM downloadinfo" Try: 0
23-04-26 16:22:25:298 [ debug sync.database.sql ]	[ OCC::SqlQuery::prepare ]:	SQL prepare "SELECT path,transferid FROM uploadinfo" Try: 0
23-04-26 16:22:25:298 [ debug sync.database ]	[ OCC::SyncJournalDb::deleteStaleUploadInfos ]:	class QVector<unsigned int> __cdecl OCC::SyncJournalDb::deleteStaleUploadInfos(const class QSet<class QString> &) Keep: QSet() Removing Stale: ()
23-04-26 16:22:25:298 [ debug sync.database.sql ]	[ OCC::SqlQuery::prepare ]:	SQL prepare "SELECT path FROM blacklist" Try: 0
23-04-26 16:22:25:299 [ debug sync.database.sql ]	[ OCC::SqlQuery::prepare ]:	SQL prepare "DELETE FROM blacklist WHERE path = ?" Try: 0
23-04-26 16:22:25:299 [ debug sync.database ]	[ OCC::deleteBatch ]:	Removing stale "blacklist" entries: "UCI_Motril/REG_0005.NHS"
23-04-26 16:22:25:299 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec: Estimated query: "'UCI_Motril/REG_0005.NHS'DELETE FROM blacklist WHERE path = ?" Actual query: "DELETE FROM blacklist WHERE path = 'UCI_Motril/REG_0005.NHS'" Try: 0
23-04-26 16:22:25:299 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 1 rows.
23-04-26 16:22:25:299 [ debug sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "post stale entry removal" and starting new transaction
23-04-26 16:22:25:299 [ info sync.engine ]:	#### Post-Reconcile end ####################################################  151 ms
23-04-26 16:22:25:300 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec: "DELETE FROM datafingerprint;" Try: 0
23-04-26 16:22:25:300 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 1 rows.
23-04-26 16:22:25:300 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec: "INSERT INTO datafingerprint (fingerprint) VALUES (?1);" Try: 0
23-04-26 16:22:25:300 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 1 rows.
23-04-26 16:22:25:300 [ debug sync.database.sql ]	[ OCC::SqlQuery::prepare ]:	SQL prepare "SELECT path FROM conflicts" Try: 0
23-04-26 16:22:25:300 [ debug sync.database.sql ]	[ OCC::SqlQuery::prepare ]:	SQL prepare "DELETE FROM flags WHERE path != '' AND path NOT IN (SELECT path from metadata);" Try: 0
23-04-26 16:22:25:301 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec: "DELETE FROM flags WHERE path != '' AND path NOT IN (SELECT path from metadata);" Try: 0
23-04-26 16:22:25:301 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
23-04-26 16:22:25:301 [ debug sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "All Finished." 
23-04-26 16:22:25:304 [ info sync.engine ]:	Sync run took  155 ms
23-04-26 16:22:25:304 [ info gui.socketapi ]:	Sending SocketAPI message --> "STATUS:OK:C:\\Users\\XXXXX\\ownCloud - XXXXX@cloud.nuubo.com" to QLocalSocket(0x20a3799a090)
23-04-26 16:22:25:304 [ debug sync.localdiscoverytracker ]	[ OCC::LocalDiscoveryTracker::slotSyncFinished ]:	sync success, forgetting last sync's local discovery path list
23-04-26 16:22:25:305 [ info gui.folder ]:	Client version "ownCloud 3.2.1.10355 9724d6 Libraries Qt 5.15.5, OpenSSL 1.1.1q  5 Jul 2022 Using virtual files plugin: wincfapi windows-10.0.19044"
23-04-26 16:22:25:305 [ info gui.folder ]:	SyncEngine finished without problem.
```
### Client version number

ownCloud 3.2.1.10355 9724d6 Libraries Qt 5.15.5, OpenSSL 1.1.1q  5 Jul 2022 Using virtual files plugin: wincfapi windows-10.0.19044

### Installation path (Windows only)

C:\ProgramFiles\ownCloud

### Server information

PHP 7.4.33 (cli) (built: Apr  9 2023 16:49:24) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.33, Copyright (c), by Zend Technologie

OC Version 10.11.0.6

**Comment by Darkexy** [comment]
I don't know, if this is related, but I have an simular problem with uploading big files (testfiles hadabout 10GB size) via Desktop Client after reinstall my owncloud on a new raspberrypi. 

I configurated owncloud like the documentary says and uploading the testfiles that failed via Desktop Client over the browser worked perfetcly fine. In the Desktop Client the Upload goes to 100%, than fails and start all over again, ending in a loop.

**Comment by michaelstingl** [comment]
@Darkexy better open a separate issue.

**Comment by michaelstingl** [comment]
@MadriSX share a test account with `apps-at-owncloud-dot-com` ?
