### ISSUE TITLE
Reimplement .netrc support

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10782]
During the Qt6 port the support to use .netrc in the cmd client was removed.
https://github.com/owncloud/client/pull/10781

**Comment by michaelstingl** [comment]
> During the Qt6 port the support to use .netrc in the cmd client was removed.
> #10781

Currently I'm not aware of of any requirements. Could be done when needed. I'd love to have [oidc-agent](https://owncloud.dev/clients/rclone/webdav-sync-oidc/) first:
- https://github.com/owncloud/client/issues/10256
