### ISSUE TITLE
[Win] Remove legacy setting for sidebar entries

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10788]
https://central.owncloud.org/t/synced-folders-still-show-in-win10-explorer-pane-despite-unchecking-show-option-in-owncloud-client/42096

@TheOneRing @HanaGemela 4.x or 5.0 ?
---

The setting has no effect on windows vfs, its only relevant for vfs off mode.
As Windows vfs is the default, we decided to remove the legacy setting which is confusing to the user.
This means with vfs off we will always create a sidebar entry.
![image](https://github.com/owncloud/client/assets/200626/f419f1ae-5297-4641-af44-1b80b0477f63)

**Comment by saw-jan** [comment]
Tested with `ownCloud 5.0.0.11384-daily20230705 1c0613` on `win10`

![Screenshot from 2023-07-05 11-24-44](https://github.com/owncloud/client/assets/52366632/e1c77738-9c1c-499d-800f-04d4d1c98a6c)
