### ISSUE TITLE
Support Fedora 38

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#10780]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

No installer for Fedora 38

### Expected behavior

I can install the desktop-client on Fedora 38

### Client version number

Noticed when testing 4.0.0-rc1

### Desktop environment (Linux only)

Fedora 38

### Additional context

https://fedoraproject.org/workstation/download/

Fedora 38 was released 2023-04-18

It would be nice to add it to the supported platforms.

**Comment by michaelstingl** [comment]
@fmoc please take care for vanilla + branded 3.2.1 and all 4.x builds

**Comment by fmoc** [comment]
Done.
