### ISSUE TITLE
upload of a folder with a lot of files needs force-sync

### ISSUE THREAD

**Issue by individual-it** [owncloud/client#10807]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When uploading a folder with a lot of subfolders, not all files are uploaded without a force-sync

### Expected behavior

I expect all files to be uploaded

### Steps to reproduce the issue

1. in ocis create a space
2. connect the space to the client
3. copy a folder with a lot of files and folders to the space
4. wait till the client says all files are uploaded
5. look through all the folders => some files are not uploaded
6. force-sync in the client => finally all files are uploaded

### Screenshots

![image](https://user-images.githubusercontent.com/2425577/236169321-e4e87f8b-c69e-4c36-83fc-63bfc7e724e0.png)
![image](https://user-images.githubusercontent.com/2425577/236169595-e1c58f5d-5f4d-4468-b550-83b4479940d8.png)
![image](https://user-images.githubusercontent.com/2425577/236169657-db1e56b5-5830-4986-bc1c-58979522ff0b.png)

### Logs

[ownCloud.zip](https://github.com/owncloud/client/files/11396145/ownCloud.zip)

### Client version number

4.0.0 rc2
![image](https://user-images.githubusercontent.com/2425577/236170931-1848b4fa-6d93-4e05-98eb-ccec04394e9c.png)

### Server information

Ocis 3.0.0 rc2

**Comment by michaelstingl** [comment]
> 6\. force-sync in the client => finally all files are uploaded

Also next full discovery (default=1h) should upload the remaining files.

**Comment by individual-it** [comment]
Tested with ocis 3.0.0RC3 and the client v4.0.0 RC3 and cannot reproduce the issue anymore

**Comment by HanaGemela** [comment]
I was able to reproduce with rc3, logs here https://cloud.owncloud.com/index.php/f/6001018

**Comment by HanaGemela** [comment]
Retested again without sleep and all went ok. Passed. Will test again tomorrow with sleep and open a new issue if needed
