### ISSUE TITLE
[macOS] craft fails to package libLibreGraphAPI

### ISSUE THREAD

**Issue by erikjv** [owncloud/client#10810]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

`craft --compile --install --package owncloud-client` does not package libLibreGraphAPI, so launching fails.

### Expected behavior

craft should put the lib in the Frameworks folder

### Client version number

master branch

**Comment by TheOneRing** [comment]
I'd recommend to reinstall craft

**Comment by TheOneRing** [comment]
Maybe related to https://github.com/owncloud/craft-blueprints-owncloud/commit/295ddf694ed37bfc3720a7eded865716eb5318fe
