### ISSUE TITLE
[QA] Do not list all the files not synced due to Low disk space

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10811]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

ownCloud 4.0.0.10776-daily20230427
mac

When listing all the files that have not been synced due to low disk space, the message can become very long. The Not synced protocol in Activity tab should be sufficient 

### Steps to reproduce the issue

1. Sync a file when disk space is low

### Screenshots

No screenshot

### Expected behavior

Short warning message maybe pointing to Not synced in Activity tab

### Actual behavior

All the not synced files listed

**Comment by michaelstingl** [comment]
Maybe only first line in red box, because users see the detailed errors in the "Not synced" tab

**Comment by HanaGemela** [comment]
Same problem when the checksum doesn't match
https://cloud.owncloud.com/index.php/apps/files/?dir=/Shared/owncloud/Client%20-%20desktop/issues/10811&fileid=6000198#/

**Comment by TheOneRing** [comment]
Its a serious issue and in the past it was decided that those are displayed as red rectangles.
@michaelstingl @tbsbdr

**Comment by TheOneRing** [comment]
Can't reproduce with ocis, will try with oc10...
![image](https://github.com/owncloud/client/assets/200626/aa60f781-1721-466f-9711-ffc938e6cb5a)

**Comment by TheOneRing** [comment]
Ok I was testing the wrong direction...

**Comment by TheOneRing** [comment]
Can't reproduce
![image](https://github.com/owncloud/client/assets/200626/06c4b2c7-9d25-4969-b41c-cc594bc35685)

And to be honest, I don't think that scenario is worth any more work.
