### ISSUE TITLE
[QA] ocis accounts don't have Activities enabled 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10814]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Are the activities disabled for ocis accounts because ocis doesn't support them? It looks like I can enable it somewhere. Could the message be different for ocis accounts? Or is the feature coming soon?

ownCloud 4.0.0.10776-daily20230427
mac

### Steps to reproduce the issue

1. Add a new ocis account
2. Open the Activity tab - Server activities

### Screenshots

<img width="794" alt="Screenshot 2023-05-08 at 13 04 19" src="https://user-images.githubusercontent.com/49001702/236808418-a05f327b-652c-49c1-8799-e47531b9055e.png">

### Expected behavior

ocis accounts don't have Activities at all  

### Actual behavior

ocis accounts don't have Activities enabled

**Comment by michaelstingl** [comment]
No activities in `/ocs/v1.php/cloud/capabilities?format=json` 🤷‍♂️ 

```
% curl -s 'https://ocis.ocis-traefik.latest.owncloud.works/ocs/v1.php/cloud/capabilities?format=json' \
-X 'GET' \
-H 'Pragma: no-cache' \
-H 'Accept: application/json, text/plain, */*' \
-H 'Authorization: Bearer eyJhbGciOiJQUzI1NiIsImtpZCI6InByaXZhdGUta2V5IiwidHlwIjoiSldUIn0.eyJhdWQiOiJ3ZWIiLCJleHAiOjE2ODM1NDQ1NTgsImlhdCI6MTY4MzU0NDI1OCwiaXNzIjoiaHR0cHM6Ly9vY2lzLm9jaXMtdHJhZWZpay5sYXRlc3Qub3duY2xvdWQud29ya3MiLCJqdGkiOiJackNEU2VDQU5xMG5WR0x2N1UtM1A4MjJGUlR4YUQ5VSIsImxnLmkiOnsiZG4iOiJBbGJlcnQgRWluc3RlaW4iLCJpZCI6InVpZD1laW5zdGVpbixvdT11c2VycyxvPWxpYnJlZ3JhcGgtaWRtIiwidW4iOiJlaW5zdGVpbiJ9LCJsZy5wIjoiaWRlbnRpZmllci1sZGFwIiwibGcudCI6IjEiLCJzY3AiOiJvcGVuaWQgcHJvZmlsZSBlbWFpbCIsInN1YiI6Img5Skk1RWtDUlptV1NjYUhAdW05TWtPZ2VHU3Nlck54TDRzSGhiMWl4bGlTLXRrdHFkV28yTURqNHExa3ZwYnJNQTFXcDBQNGVnTHh4bEZNNnJCb0ZBQSJ9.VHPhx0axQOfIlMLiLMky9rAfoaKg6AvaFVxp65tb9GvHVpZFs1ZPtoOLSiLGsp7BIxNOvzOpArYaHkMSd6-HEa9Dn2whv_eS2d5wbZ5YQUcrcaF_oegLu7ZDrXbEplG-qTa6bOx_OlIDdsRA1xte5dWGZcY-X1QHwYbDSHGuzlE61iYRCOQkZ9HZtfcl-8KCFye_1AZ1Pq4vxcJeIIpC-963Rh9GD796FRyqmZ-c_U3Nuq1MM6rL4TQMtyeh3M4C9llyHoH-qGC5_qtE3NvQSEJTPnETgADuZgTUnGJHBfLl6gPP-by2sSbb14eyYFut49Yle337xGWcxe0GSJYoIM1Et-yshWSImWnZ2f9tzjqmwxEeT7KwPMrqKB1NCKd3Ar7B08O5VR08ZzMfdlkEflJ_07APCGQYz-MBNZLirAWqezKdA8vw4S6D2Ond4XO3p3bo7R6TseSyX_sct0wca9NIXeLC6rX3OAtWmRzYnf9wBTKeuyNCmPeLF5rHw9ChwzJUt9zeW8mgNOy9BHTkO0Z7nd0M6hL_veJ8z8rjzJ1h_0OxLrdNZ2aG5sF6fI_nLKSBNUsTc88LCxqdLw3RPyBZ_aO6k75U0etgHGT6FysY8q9AESKer7VZ9KQUGikc5Miu3_O73VtfWJPwdIPMSVB0I151MSTfWs6Lx9zB-pI' | jq | grep acti
```

**Comment by michaelstingl** [comment]
> @fmoc how does the desktop app know if activities are enabled?

@fmoc ping

**Comment by fmoc** [comment]
Let's just rename the message on the activities page as @michaelstingl suggested to "does not provide activities".

**Comment by S-Panta** [comment]
Tested with `ownCloud 5.0.0.11369-daily20230703 [511b96]`

![Screenshot from 2023-07-03 12-49-19](https://github.com/owncloud/client/assets/64484313/e60208e9-0036-4ecc-9730-29d2f260d3a5)
