### ISSUE TITLE
[QA][master] Unable to build client in drone-ci (LibreGraphAPI error)

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#10817]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

```bash
-- Looking for lstat - found
CMake Error at src/libsync/CMakeLists.txt:1 (find_package):
  By not providing "FindLibreGraphAPI.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "LibreGraphAPI", but CMake did not find one.

  Could not find a package configuration file provided by "LibreGraphAPI"
  (requested version 1.0.4) with any of the following names:

    LibreGraphAPIConfig.cmake
    libregraphapi-config.cmake

  Add the installation prefix of "LibreGraphAPI" to CMAKE_PREFIX_PATH or set
  "LibreGraphAPI_DIR" to a directory containing one of the above files.  If
  "LibreGraphAPI" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
```

### Client version number

Master branch

**Comment by fmoc** [comment]
Next time, please be more elaborate, e.g., include a link to an example build. This would save me a lot of time searching for this kind of information myself.

**Comment by fmoc** [comment]
Fix available in https://github.com/owncloud-ci/client/pull/20.

**Comment by saw-jan** [comment]
> Next time, please be more elaborate, e.g., include a link to an example build. This would save me a lot of time searching for this kind of information myself.

Yeah, true
I should have added any master branch's drone-ci build.
great apologies for the inconvenient
