### ISSUE TITLE
Qt6:Set   QNetworkRequest::RedirectPolicyAttribute to QNetworkRequest::ManualRedirectPolicy

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10832]
In Qt6 the default redirect policy changed from QNetworkRequest::ManualRedirectPolicy to QNetworkRequest::NoLessSafeRedirectPolicy.

As our connection validation relies on not following redirects, we need to explicitly set ManualRedirectPolicy for our abstractnetowork jobs.

TODO: have a look on core jobs

**Comment by saw-jan** [comment]
Looks like only code refactoring. Nothing is to be tested manually. Moving to Done
CC @TheOneRing
