### ISSUE TITLE
Invokes on qApp

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10835]
We used to inherit qApplication which allowed us to hack around some dependency issues.

https://github.com/owncloud/client/blob/076efb21272562acdd35bb78461399acf5e1aeeb/src/libsync/platform_mac.mm#L44-L45

We probably need an `setCoreInstance(CoreInstance *)` function in platform.h  where CoreInstance is an interface define in libsync.

https://github.com/owncloud/client/blob/f4f59cc02998fcbc133861d88ea86a17855d4604/src/libsync/creds/oauth.cpp#L569-L575

https://github.com/owncloud/client/blob/2c2a8d71cb538353806430ffa2ab8e8167db9cfb/src/libsync/appprovider.cpp#L88-L90

There are probably more.
We should also run clazy to port away from string based connects...

**Comment by erikjv** [comment]
Wouldn't it be better to have the `Platform` class emit a signal, which we then connect to `Application::showSettingsDialog`?

**Comment by TheOneRing** [comment]
> Wouldn't it be better to have the `Platform` class emit a signal, which we then connect to `Application::showSettingsDialog`?

Thats what I've done

**Comment by saw-jan** [comment]
Looks like only code refactoring. Nothing is to be tested manually. Moving to Done
CC @TheOneRing
