### ISSUE TITLE
Status in systray menu should never be empty

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10834]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

ownCloud 4.0.0.10879-rc.3
mac

There is an entry in the sys tray menu which is sometimes empty

### Steps to reproduce the issue

Right click on the ownCloud icon in the sys tray

### Screenshots

Sometimes there is some info about the sync but it's not obvious to which account it belongs

<img width="350" alt="Screenshot 2023-05-11 at 10 41 44" src="https://github.com/owncloud/client/assets/49001702/78d979e3-4070-4f1c-b240-4f48cebdf1ae">

Sometimes it's empty 

<img width="344" alt="Screenshot 2023-05-11 at 10 40 17" src="https://github.com/owncloud/client/assets/49001702/508752f8-f23c-4535-8e60-2b81523c38e4">

### Expected behavior

@michaelstingl please specify 

### Actual behavior

Empty entry or some status without an account

**Comment by erikjv** [comment]
@HanaGemela From the code, it looks like this can only happen when an error occurred. Can you tell if that's the case?

**Comment by HanaGemela** [comment]
Do you mean that some file has not been sync due to an error? Or what kind of error do you mean?

**Comment by HanaGemela** [comment]
@michaelstingl what is the expected result here? What should I see in that entry?

**Comment by michaelstingl** [comment]
> What should I see in that entry?

Everything not empty would be nice. We can check for more details with the team next week.

**Comment by HanaGemela** [comment]
Not empty anymore in ownCloud 4.1.0.11195-rc.2
