### ISSUE TITLE
Qt6: Mac QDialogd does not emit accepted if modal

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10846]
A modal QMessageBox does not emit accepted.

https://github.com/owncloud/client/blob/16317207c1970916726dc02db0c072c430032fff/src/gui/settingsdialog.cpp#L252-L258

If we don't set the parent for the message box, qt complains about it but the accept is emited.

The reason therefore appears to be that the modal dialog is a native mac dialog therefor a different code path is used.

With a non modal dialog https://github.com/qt/qtbase/blob/aea92807be2567c4212b96ae67de7137075ba4ee/src/widgets/dialogs/qmessagebox.cpp#L483-L493 is executed

for the modal dialog:
https://github.com/qt/qtbase/blob/aea92807be2567c4212b96ae67de7137075ba4ee/src/widgets/dialogs/qmessagebox.cpp#L495-L508

Which then call QDialog::done https://github.com/qt/qtbase/blob/aea92807be2567c4212b96ae67de7137075ba4ee/src/widgets/dialogs/qdialog.cpp#L617

With https://github.com/qt/qtbase/blob/aea92807be2567c4212b96ae67de7137075ba4ee/src/widgets/dialogs/qdialog.cpp#L163  (wrong dialogCode)

https://github.com/qt/qtbase/blame/fd565750f3cec5fcf4017cba0ffbb42efc20edd5/src/plugins/platforms/cocoa/qcocoamessagedialog.mm#L285

appears to be the relevant code, introduced in Qt 6.5.

**Comment by erikjv** [comment]
Created a bug report: https://bugreports.qt.io/browse/QTBUG-113685

**Comment by TheOneRing** [comment]
Fixed upstream

**Comment by HanaGemela** [comment]
@TheOneRing any test steps?

**Comment by TheOneRing** [comment]
You can test it in a couple of month once we switched to Qt 6.5.3
