### ISSUE TITLE
Provide space_ref to share requests when using spaces

### ISSUE THREAD

**Issue by individual-it** [owncloud/client#10845]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When clicking on "Create and copy public link to clipboard" from the context menu the user is lead to the webUI of ocis instead of a link being created.
This happens only after the first start of the client after connecting a new space, after a restart it works fine.

### Expected behavior

I expect to get a public link in my clipboard

### Steps to reproduce the issue

1. start ocis, in my case `OCIS_URL=https://192.168.56.1:9200  ./ocis-3.0.0-rc.1-linux-amd64 server`
2. connect the desktop client to ocis using the admin user
3. login to the webUI as admin
4. create a new space (in my case `ict`)
5. connect the new space to the desktop client
6. via webUI upload some files to the space
7. wait till the files are synced to the client
8. open the context menu of one of the files and select `Create and copy public link to clipboard`

=> browser opens and leads to the webUI

~~If the desktop client is restarted, the action works as intended~~

### Logs

[ownCloud.log](https://github.com/owncloud/client/files/11330920/ownCloud.log)

### Client version number

ownCloud 4.0.0.10732-rc1
![image](https://user-images.githubusercontent.com/2425577/234523973-2ee52007-d475-4859-a5b7-a5efe08d93a0.png)

### Installation path (Windows only)

c:\Program Files\ownCloud\

### Server information

ocis 3.0.0-rc.1

**Comment by michaelstingl** [comment]
@TheOneRing @fmoc so, we'll send the `space_ref` when `"public": { "enabled": true,` AND `/graph/v1.0/me/drives` is present?

**Comment by TheOneRing** [comment]
To check for spaces support: 
https://github.com/owncloud/client/blob/e4ae0539664dbf1e9d3c522a7ec4bc41aebd4cb3/src/gui/accountstate.cpp#L552-L552

**Comment by TheOneRing** [comment]
> api/v1/shares

Oh the old code performs two requests, it lists the existing shares and creates a new one if it didn't exist.
So we only did the listing.

**Comment by erikjv** [comment]
> Oh the old code performs two requests, it lists the existing shares and creates a new one if it didn't exist.
> So we only did the listing.

Can you point out where the two requests are made in the old code?

**Comment by TheOneRing** [comment]
(https://github.com/owncloud/client/blob/92f5d9867a81ceefb105cd4b6b61bdbe411e221d/src/gui/socketapi/socketapi.cpp#L615

https://github.com/owncloud/client/blob/92f5d9867a81ceefb105cd4b6b61bdbe411e221d/src/gui/socketapi/socketapi.cpp#L570

**Comment by fmoc** [comment]
@micbar ^

**Comment by michaelstingl** [comment]
What we did before:

```
23-08-02 10:09:46:707 [ info sync.httplogger ]:	"0e177d5a-8e16-4b80-a09a-d69dc4a14460:
Request: GET https://ocis.ocis-traefik.daily.owncloud.works/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2FHacker-Songs&reshares=true&format=json
Header: { OCS-APIREQUEST: true, Authorization: Bearer [redacted], User-Agent: Mozilla/5.0 (Macintosh) mirall/5.0.0.11632-daily20230802 (testpilotcloud, macos-22.6.0 ClientArchitecture: arm64 OsArchitecture: arm64), Accept: */*, Accept-Language: en_DE, X-Request-ID: 0e177d5a-8e16-4b80-a09a-d69dc4a14460, Original-Request-ID: 0e177d5a-8e16-4b80-a09a-d69dc4a14460, }
Data: []"

23-08-02 10:09:46:760 [ info sync.httplogger ]:	"0e177d5a-8e16-4b80-a09a-d69dc4a14460:
Response: GET 200 (52ms) https://ocis.ocis-traefik.daily.owncloud.works/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2FHacker-Songs&reshares=true&format=json
Header: { Content-Length: 74, Content-Type: application/json; charset=utf-8, Date: Wed, 02 Aug 2023 08:09:46 GMT, Ocs-Api-Version: 1, Vary: Origin, X-Request-Id: 0e177d5a-8e16-4b80-a09a-d69dc4a14460, }
Data: [{\"ocs\":{\"meta\":{\"status\":\"error\",\"statuscode\":998,\"message\":\"not found\"}}}]"
```

Now, we ask for existing Shares, and the response look sane:

```
23-07-28 16:52:19:340 [ info sync.httplogger ]:	"b642efc9-75f2-4e8f-9e7e-7cd17f2b2e90: 
Request: GET https://ocis.owncloud.com/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Funtitled folder%2Fasdf.txt&reshares=true&space_ref=166d1210-cdb9-50ab-9f1e-ecb9ef12a304%24534bb038-6f9d-4093-946f-133be61fa4e7&format=json 
Header: { OCS-API
REQUEST: true, Authorization: Bearer [redacted], User-Agent: Mozilla/5.0 (Macintosh) mirall/5.0.0-git (ownCloud, macos-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64), Accept: */*, Accept-Language: en_DE, X-Request-ID: b642efc9-75f2-4e8f-9e7e-7cd17f2b2e90, Original-Request-ID: b642efc9-75f2-4e8f-9e7e-7cd17f2b2e90, } 
Data: []"

23-07-28 16:52:19:387 [ info sync.httplogger ]:	"b642efc9-75f2-4e8f-9e7e-7cd17f2b2e90: 
Response: GET 200 (46ms) https://ocis.owncloud.com/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%2Funtitled folder%2Fasdf.txt&reshares=true&space_ref=166d1210-cdb9-50ab-9f1e-ecb9ef12a304%24534bb038-6f9d-4093-946f-133be61fa4e7&format=json 
Header: { Content-Length: 74, Content-Type: application/json; charset=utf-8, Date: Fri, 28 Jul 2023 14:52:19 GMT, Ocs-Api-Version: 1, Referrer-Policy: strict-origin-when-cross-origin, Strict-Transport-Security: max-age=315360000; preload, Vary: Origin, X-Content-Type-Options: nosniff, X-Frame-Options: SAMEORIGIN, X-Xss-Protection: 0, } 
Data: [{\"ocs\":{\"meta\":{\"status\":\"ok\",\"statuscode\":100,\"message\":\"OK\"},\"data\":[]}}]"
```

(no existing share ✅ )

**Comment by michaelstingl** [comment]
> The easiest is to just take the `oc:fileid` from a propfind and send it as the `space` form value instead of a `path`. They can be combined, clients can use the space root id as `space` and a `path` relative to the space root. Technically `path` is always relative to `space`. and if `space` is unset the users home is assumed. That is why it works for personal spaces.

Creating the Share with `space_ref` added also fails:

```
Data: [
path=%2Funtitled%20folder%2Fasdf.txt
&shareType=3
&name=Context%20menu%20share
&space_ref=166d1210-cdb9-50ab-9f1e-ecb9ef12a304%24534bb038-6f9d-4093-946f-133be61fa4e7
]"
```

Full HTTP:

```
23-07-28 16:52:19:389 [ info sync.httplogger ]:	"64ba3a19-eb98-40f7-8344-7ddfe39eb42e: 
Request: POST https://ocis.owncloud.com/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json 
Header: { Content-Type: application/x-www-form-urlencoded; charset=UTF-8, OCS-API
REQUEST: true, Authorization: Bearer [redacted], User-Agent: Mozilla/5.0 (Macintosh) mirall/5.0.0-git (ownCloud, macos-21.6.0 ClientArchitecture: x86_64 OsArchitecture: x86_64), Accept: */*, Accept-Language: en_DE, X-Request-ID: 64ba3a19-eb98-40f7-8344-7ddfe39eb42e, Original-Request-ID: 64ba3a19-eb98-40f7-8344-7ddfe39eb42e, Content-Length: 162, } 
Data: [path=%2Funtitled%20folder%2Fasdf.txt&shareType=3&name=Context%20menu%20share&space_ref=166d1210-cdb9-50ab-9f1e-ecb9ef12a304%24534bb038-6f9d-4093-946f-133be61fa4e7]"

23-07-28 16:52:19:419 [ info sync.httplogger ]:	"64ba3a19-eb98-40f7-8344-7ddfe39eb42e: 
Response: POST 200 (29ms) https://ocis.owncloud.com/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json 
Header: { Content-Length: 89, Content-Type: application/json; charset=utf-8, Date: Fri, 28 Jul 2023 14:52:19 GMT, Ocs-Api-Version: 1, Referrer-Policy: strict-origin-when-cross-origin, Strict-Transport-Security: max-age=315360000; preload, Vary: Origin, X-Content-Type-Options: nosniff, X-Frame-Options: SAMEORIGIN, X-Xss-Protection: 0, } 
Data: [{\"ocs\":{\"meta\":{\"status\":\"error\",\"statuscode\":400,\"message\":\"Can not share space root\"}}}]"
```

@micbar @butonic how should the request look like? Link to docs?

**Comment by michaelstingl** [comment]
Web does this:

```
--data '
shareType=3
&path=%2FHacker-Songs
&space_ref=e51de7b9-c2c2-4719-ac38-1d933cf03e67%24c4f11913-eaa6-4c7d-bb60-ce5cf8d25b38!428f6a92-486a-4f65-9252-e32216e0509c
&permissions=1
&name=Link
&quicklink=true
&attributes%5B0%5D%5Bkey%5D=isQuickLink
&attributes%5B0%5D%5Bscope%5D=files_sharing
&attributes%5B0%5D%5Bvalue%5D=true'
```

Copy as cURL from Web Inspector:

```
curl 'https://ocis.ocis-traefik.daily.owncloud.works/ocs/v1.php/apps/files_sharing/api/v1/shares' \
-X 'POST' \
-H 'Content-Type: application/x-www-form-urlencoded' \
-H 'Authorization: Bearer eyJhbGciOiJQUzI1NiIsImtpZCI6InByaXZhdGUta2V5IiwidHlwIjoiSldUIn0.eyJhdWQiOiJ3ZWIiLCJleHAiOjE2OTA5NjUwMjcsImlhdCI6MTY5MDk2NDcyNywiaXNzIjoiaHR0cHM6Ly9vY2lzLm9jaXMtdHJhZWZpay5kYWlseS5vd25jbG91ZC53b3JrcyIsImp0aSI6ImZGNENENzc4SktWOFR4ZmdtU1l6TGxyX3dXTHBEdENHIiwibGcuaSI6eyJkbiI6IkthdGhlcmluZSBKb2huc29uIiwiaWQiOiJvd25DbG91ZFVVSUQ9NTM0YmIwMzgtNmY5ZC00MDkzLTk0NmYtMTMzYmU2MWZhNGU3IiwidW4iOiJrYXRoZXJpbmUifSwibGcucCI6ImlkZW50aWZpZXItbGRhcCIsImxnLnQiOiIxIiwic2NwIjoib3BlbmlkIHByb2ZpbGUgZW1haWwiLCJzdWIiOiJlcHZEcFBoN2tuTl9MeUk2QG1MSzVzU3FVYWVfVjAzbVNPa0ZCS1NkbUs2REx6THJacVNESVpIWXRqb0ZpdEJOcTV0aTNtN19YTUxIekhVbGpXNUx4Z3cifQ.THeMqHglbc241cPJ2BKpdHDf0bLkXfvOP3RirCHqD9Kd4FMGfNaXAWNNsAcbIuKIglEe94xgmct2vxdrqu1LbJ-8XCswgecYbGCH29h6bfBC7Zw2QVUGrfXZiB68yYE4HozmEIuq9KNsv2HcjbAiwYI3hnkTKBC7mVc_SwQ2Yfj8zUVq5I_lSW2zqsg5LAa8DLWKbya0cr5IPKfReq1PoyVAmtXX6VX2XWDDxUXTnZvDUNLowd4stUU5XKCkYIbusmCZUfDFX55fUQrcapQsMYqp7EuULBrBcC2qQTaJECW2VaRZdMp5O9_wr95xOnIcFsAMTS6WOtIvwcxFjF2Btygb6LvR7xmzOyIucAuue6vZ3VKE-4gaFxI0vLl5RR3ypPTKmBGkitQQ4o3meB1tS8KxtpRmXo1Eg81VAILIADStG9eYajcpa_xqe7iJMA8bSFPGWA4zOaA7sY5ur7srkNAgXNxKmhOScDwMiy1Wf56XFDUXm2F7XmNa1frpp0LgB0HcqNE8NDFoKGJQ2e29SGKV18IT_-Th6hva6HvyWOfDhDKFV0sA7IXV-U4afDymaoEQZsh7OlMHEnTKA2o4lv8ceYqFDbzt6UE6A3jz7Hadn6-BJUMHuC8pLjiWhsvMDtE1gB07rAQZJaiMOo7NBWU7-R-5MYOVFfR91HQWy6c' \
-H 'Accept: */*' \
-H 'Sec-Fetch-Site: same-origin' \
-H 'Accept-Language: en' \
-H 'Accept-Encoding: gzip, deflate, br' \
-H 'Sec-Fetch-Mode: cors' \
-H 'Origin: https://ocis.ocis-traefik.daily.owncloud.works' \
-H 'Referer: https://ocis.ocis-traefik.daily.owncloud.works/files/spaces/project/ict?fileId=e51de7b9-c2c2-4719-ac38-1d933cf03e67%24c4f11913-eaa6-4c7d-bb60-ce5cf8d25b38%21c4f11913-eaa6-4c7d-bb60-ce5cf8d25b38&items-per-page=100&files-spaces-generic-view-mode=resource-table&tiles-size=1&sort-by=name&sort-dir=asc' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15' \
-H 'Content-Length: 310' \
-H 'Connection: keep-alive' \
-H 'Host: ocis.ocis-traefik.daily.owncloud.works' \
-H 'Sec-Fetch-Dest: empty' \
-H 'ocs-apirequest: true' \
-H 'x-requested-with: XMLHttpRequest' \
-H 'x-request-id: d52b2d98-565c-4149-8933-4a77761eb7b5' \
--data 'shareType=3&path=%2FHacker-Songs&space_ref=e51de7b9-c2c2-4719-ac38-1d933cf03e67%24c4f11913-eaa6-4c7d-bb60-ce5cf8d25b38!428f6a92-486a-4f65-9252-e32216e0509c&permissions=1&name=Link&quicklink=true&attributes%5B0%5D%5Bkey%5D=isQuickLink&attributes%5B0%5D%5Bscope%5D=files_sharing&attributes%5B0%5D%5Bvalue%5D=true'
```

Tested with:

```
[Log]  ownCloud Web UI 7.1.0-rc.4  (index.html-25ddd689.mjs, line 7)
[Log]  Infinite Scale 3.1.0-beta.1+d65476ff0 Community  (index.html-25ddd689.mjs, line 7)
```

**Comment by michaelstingl** [comment]
@micbar @butonic `space_ref` deprecated?

- https://github.com/cs3org/reva/pull/2913

**Comment by michaelstingl** [comment]
Seems `space` parameter also didn't work?

- https://github.com/owncloud/ocis/issues/5139#issuecomment-1551602018

What exactly does https://github.com/cs3org/reva/pull/4004 fix?

**Comment by micbar** [comment]
# Conclusion

`space` and `space_ref` are currently treated equal.

## oc10 compatibility

The `path` parameter is there to  stay compatible with oc10
It can be used by clients which know "nothing about spaces"


## ocis (bad ocs API experience, will be replaced by graph ASAP)

On the backend, we identify resources by a Reference (https://cs3org.github.io/cs3apis/#cs3.storage.provider.v1beta1.Reference)

### Easiest solution

Use the `id` of the target resource and no `path`

So the easiest way to go, is to use the `OC-FileID` from WebDAV and no path.

### Optional

Like in the mentioned CS3 Api docs, you could also use the id and a relative path.
The combination needs to be a valid resource, which means the id needs to point to a resource which is in the correct relative location to the path.

**Comment by michaelstingl** [comment]
@micbar thanks for the recommendation. I'll coordinate across clients.

Desktop client team decided to kill the `/ocs/` for accounts setup with `/graph/v1.0/me/drives` , and they'll build a shiny future based on a new API:

**Comment by TheOneRing** [comment]
@erikjv please disable the context menu entry if account->supportsSpaces is true.

**Comment by fmoc** [comment]
Resolved by and tested in https://github.com/owncloud/client/pull/11079.
