### ISSUE TITLE
[QA] Linux install test fails on Fedora 38 and AppImage

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10858]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Branded regression test failed - see details in: 

https://github.com/owncloud/enterprise/issues/5728#issuecomment-1556792565

### Steps to reproduce the issue

https://confluence.owncloud.com/display/OG/Automated+Tests#AutomatedTests-LinuxInstallTest

### Screenshots

https://github.com/owncloud/enterprise/issues/5728#issuecomment-1556792565

### Expected behavior

Test passed on all platforms

### Actual behavior

Failed on Fedora 38 and AppImage

check_spurious_unbranded.sh is broken
Fedora 38 RPMs fail with the usual 'public key is not trusted'

**Comment by michaelstingl** [comment]
> ### Actual behavior
> Failed on Fedora 38

Tracked here:
- https://github.com/owncloud/client/issues/10854

**Comment by HanaGemela** [comment]
AppImage passed now https://github.com/owncloud/enterprise/issues/5728#issuecomment-1559077561

**Comment by fmoc** [comment]
Blocked by https://github.com/owncloud/client/issues/10854.

**Comment by fmoc** [comment]
Please try the latest dailies, @HanaGemela.

**Comment by HanaGemela** [comment]
Failed

|| Linux Package Installation Report |
|-|-|
|date| Thu Jun  1 12:27:41 CEST 2023
|repourl| https://download.owncloud.com/desktop/ownCloud/daily/4.1/linux/
|package| owncloud-client

<details><summary>Test details (click to view)</summary>

|Platform|Test|Result|
|-|-|-|
|fedora:38|01_cmd_vers|	----------- NO OUTPUT ------------
|fedora:38|02_integration|	----------- NO OUTPUT ------------
|fedora:38|06_xvfb_appimage|	m_crashReporterChar:  /tmp/appimage_extracted_56a4d9df738d116a8121867c284afa56/usr/bin/owncloud_crash_reporter
|fedora:38|06_xvfb_appimage|	0x200006 "ownCloud": ("AppRun.wrapped" "ownCloud") 800x700+0+0 +0+0 -> (750,20)  -> [Quit]  -> ym_crashReporterChar:  /tmp/appimage_extracted_56a4d9df738d116a8121867c284afa56/usr/bin/owncloud_crash_reporter
|fedora:38|06_xvfb_appimage|	 -> OK
|fedora:38|08_appimage|	ownCloud ownCloud 4.1.0.11119-daily20230531 - bf8de3df30b1cb102292cbfde044f6f5d6d67f12 - Qt 5.15.8, OpenSSL 1.1.1t 7 Feb 2023

**Comment by HanaGemela** [comment]
```
Key imported successfully
Import of key(s) didn't help, wrong key(s)?
Public key for ocqt5152-libQt5Core5-5.15.2-41.1.x86_64.rpm is not trusted. Failing package is: ocqt5152-libQt5Core5-5.15.2-41.1.x86_64
 GPG Keys are configured as: https://download.owncloud.com/desktop/ownCloud/daily/4.1/linux/Fedora_38/repodata/repomd.xml.key
Public key for ocqt5152-libQt5DBus5-5.15.2-41.1.x86_64.rpm is not trusted. Failing package is: ocqt5152-libQt5DBus5-5.15.2-41.1.x86_64
 GPG Keys are configured as: https://download.owncloud.com/desktop/ownCloud/daily/4.1/linux/Fedora_38/repodata/repomd.xml.key
Public key for ocqt5152-libQt5Gui5-5.15.2-41.1.x86_64.rpm is not trusted. Failing package is: ocqt5152-libQt5Gui5-5.15.2-41.1.x86_64
 GPG Keys are configured as: https://download.owncloud.com/desktop/ownCloud/daily/4.1/linux/Fedora_38/repodata/repomd.xml.key
Public key for ocqt5152-libQt5Network5-5.15.2-41.1.x86_64.rpm is not trusted. Failing package is: ocqt5152-libQt5Network5-5.15.2-41.1.x86_64
 GPG Keys are configured as: https://download.owncloud.com/desktop/ownCloud/daily/4.1/linux/Fedora_38/repodata/repomd.xml.key
Public key for ocqt5152-libQt5PrintSupport5-5.15.2-41.1.x86_64.rpm is not trusted. Failing package is: ocqt5152-libQt5PrintSupport5-5.15.2-41.1.x86_64
 GPG Keys are configured as: https://download.owncloud.com/desktop/ownCloud/daily/4.1/linux/Fedora_38/repodata/repomd.xml.key
Public key for ocqt5152-libQt5Sql5-5.15.2-41.1.x86_64.rpm is not trusted. Failing package is: ocqt5152-libQt5Sql5-5.15.2-41.1.x86_64
 GPG Keys are configured as: https://download.owncloud.com/desktop/ownCloud/daily/4.1/linux/Fedora_38/repodata/repomd.xml.key
Public key for ocqt5152-libQt5Widgets5-5.15.2-41.1.x86_64.rpm is not trusted. Failing package is: ocqt5152-libQt5Widgets5-5.15.2-41.1.x86_64
 GPG Keys are configured as: https://download.owncloud.com/desktop/ownCloud/daily/4.1/linux/Fedora_38/repodata/repomd.xml.key
Public key for ocqt5152-libqt5-qtsvg-5.15.2-3.1.x86_64.rpm is not trusted. Failing package is: ocqt5152-libqt5-qtsvg-5.15.2-3.1.x86_64
 GPG Keys are configured as: https://download.owncloud.com/desktop/ownCloud/daily/4.1/linux/Fedora_38/repodata/repomd.xml.key
Public key for ocqt5152-libqt5-qttranslations-5.12.10-3.1.x86_64.rpm is not trusted. Failing package is: ocqt5152-libqt5-qttranslations-5.12.10-3.1.x86_64
 GPG Keys are configured as: https://download.owncloud.com/desktop/ownCloud/daily/4.1/linux/Fedora_38/repodata/repomd.xml.key
Public key for ocqt5152-libqt5-qtwayland-5.15.2-4.1.x86_64.rpm is not trusted. Failing package is: ocqt5152-libqt5-qtwayland-5.15.2-4.1.x86_64
 GPG Keys are configured as: https://download.owncloud.com/desktop/ownCloud/daily/4.1/linux/Fedora_38/repodata/repomd.xml.key
Public key for ocqt5152-qt5keychain1-0.12.0-7.1.x86_64.rpm is not trusted. Failing package is: ocqt5152-qt5keychain1-0.12.0-7.1.x86_64
 GPG Keys are configured as: https://download.owncloud.com/desktop/ownCloud/daily/4.1/linux/Fedora_38/repodata/repomd.xml.key
Public key for owncloud-client-4.1.0-0.daily20230531.11119.x86_64.rpm is not trusted. Failing package is: owncloud-client-4.1.0-0.daily20230531.11119.x86_64
 GPG Keys are configured as: https://download.owncloud.com/desktop/ownCloud/daily/4.1/linux/Fedora_38/repodata/repomd.xml.key
The downloaded packages were saved in cache until the next successful transaction.
You can remove cached packages by executing 'dnf clean packages'.
Error: GPG check FAILED
```

**Comment by fmoc** [comment]
Tested by @saw-jan in #10854.
