### ISSUE TITLE
Refactor: Fix invalid use of davUser for storing the username in AbstractAuthenticationStrategy

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10879]
In AbstractAuthenticationStrategy davuser is used for the username property.
https://github.com/owncloud/client/blob/2995bf08579e674af51bb5f69c486bb25b2562b5/src/gui/newwizard/setupwizardaccountbuilder.h#L51-L52

Add an additional `username()` property to the basic auth implementation to clarify the situation around 
https://github.com/owncloud/client/blob/9d44cd72cb1276a8c521d1c8cb8d7269ae59caec/src/gui/newwizard/setupwizardcontroller.cpp#L182-L184

**Comment by fmoc** [comment]
We need another specific username variable to store the "credentials username" because it may not be the same as the `davUser`.

**Comment by saw-jan** [comment]
Steps to confirm this?
@TheOneRing

**Comment by TheOneRing** [comment]
There is already a refractor in the title. Nothing to test.
