### ISSUE TITLE
Merge various `SyncResult::Status` to string functions

### ISSUE THREAD

**Issue by erikjv** [owncloud/client#10882]
Follow up on #10860 , specifically https://github.com/owncloud/client/pull/10860#issuecomment-1559494253

**Comment by TheOneRing** [comment]
Please coordinate with https://github.com/owncloud/client/issues/9043

**Comment by erikjv** [comment]
@fmoc what's the status of #9043 ?

**Comment by fmoc** [comment]
@erikjv just need to clean up and send a PR, already made the changes.

**Comment by fmoc** [comment]
Closed by #10957.
