### ISSUE TITLE
Give a Settings tab item a better name

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#10894]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Rename:

**Settings:**
![image](https://github.com/owncloud/client/assets/200626/22d5e8a6-e53c-45ef-a4be-170d9c8a2c4c)

`Advanced - Approval of folder sync (Non virtual file mode only)` 
-->
`Advanced - Approval Synchronizing Folders (Non virtual file mode only)`

### Proposed solution

Rename as suggested above

### Alternative solutions you considered

None

### Additional context

@TheOneRing @fmoc

**Comment by michaelstingl** [comment]
> Rename:
> 
> **Settings:** ![image](https://user-images.githubusercontent.com/200626/246423864-22d5e8a6-e53c-45ef-a4be-170d9c8a2c4c.png)
> 
> `Advanced - Approval of folder sync (Non virtual file mode only)` --> `Advanced - Approval Synchronizing Folders (Non virtual file mode only)`

No efforts planned (feature is deprecated)

**Comment by michaelstingl** [comment]
> One more minor text only change, in the systray icon, the menu, at the bottom:
> 
> `Show ownCloud` --> `Show the ownCloud Desktop App` `Quit ownCloud` --> `Quit the ownCloud Desktop App`
> 
> (keeping the term ownCloud for ease of identification)
> 
> ![image](https://user-images.githubusercontent.com/200626/246419863-09dfd346-dfec-4702-8c9a-729d320c658a.png)

No, don't need the extension. (also think about branding scenarios)

Improvements planned:
- https://github.com/owncloud/client/issues/10939

**Comment by fmoc** [comment]
> No efforts planned (feature is deprecated)

Could you elaborate, please? I'm not entirely sure which elements you refer to.

Is this related to VFS?

**Comment by fmoc** [comment]
@michaelstingl explained on IRC that in the long term (i.e., VFS for macOS/Linux) this entire section in the configuration dialog will be removed entirely. Therefore, we shouldn't touch this code any more.
