### ISSUE TITLE
Qt6: MSI package all plugins

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#10903]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Client 5.0 throws `Could not detect compatible server at https://...` while trying to connect with oCIS server

### Expected behavior

Able to connect to oCIS server

### Steps to reproduce the issue

1. Install client v5.0 (https://download.owncloud.com/desktop/ownCloud/daily/5.0/win/?sort=time&order=desc)
2. Try to connect to oCIS server (https://ocis.ocis-traefik.latest.owncloud.works/)

### Screenshots

![Screenshot from 2023-06-01 09-50-04](https://github.com/owncloud/client/assets/52366632/5be0c681-5df1-465e-9a90-9d9944d0d798)

### Logs

[ownCloud-ocis.log](https://github.com/owncloud/client/files/11620842/ownCloud-ocis.log)

### Client version number

ownCloud 5.0.0.11120-daily20230531 [cf17cd](https://github.com/owncloud/client/commit/cf17cd5663b1f9edb81d3182bd884d546cf080fd)
Libraries Qt 6.4.3,
Using virtual files plugin: wincfapi
windows-10.0.19045

### Installation path (Windows only)

C:\Program Files\ownCloud

### Server information

 Infinite Scale 3.0.0-rc.4+09c95d3af Community

**Comment by michaelstingl** [comment]
SSL issue?

23-05-31 21:04:34:135 [ warning qt.network.ssl ]:	No functional TLS backend was found

**Comment by saw-jan** [comment]
AppImage worked though. (Same build)
```bash
ownCloud 5.0.0.11120-daily20230531 cf17cd
Libraries Qt 6.4.3, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: suffix
ubuntu-5.19.0-43-generic
```

![Screenshot from 2023-06-01 12-10-26](https://github.com/owncloud/client/assets/52366632/8c454024-becd-4daf-8d20-641afcf59963)

**Comment by michaelstingl** [comment]
`Libraries OpenSSL 1.1.1t 7 Feb 2023` is missing in the version information from the broken build ⚠️ 

@fmoc builds shouldn't succeed without OpenSSL

**Comment by TheOneRing** [comment]
I'll check whether qt for windows was build without openssl 😅

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client-desktop-msi/pull/12

**Comment by TheOneRing** [comment]
We need to test the installer for regressions

**Comment by saw-jan** [comment]
Tested with `ownCloud 5.0.0.11369-daily20230703 511b96`
Connection to oCIS server can be made :heavy_check_mark: 

![Screenshot from 2023-07-03 17-42-29](https://github.com/owncloud/client/assets/52366632/56ae62ae-0638-49c1-8245-c787b1f25327) | ![Screenshot from 2023-07-03 17-42-34](https://github.com/owncloud/client/assets/52366632/7658dcd6-d15b-4424-8760-2807d2b4515c) | ![Screenshot from 2023-07-03 17-42-06](https://github.com/owncloud/client/assets/52366632/230e89dd-840a-4f07-b67d-4a7db3614a1d)
--|--|--
