### ISSUE TITLE
Qt6: Cannot sync down large file (>1GB) from the server

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#10902]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

On client version 5.0, large files (> 1GB) cannot be synced. Throws `Decompression failed` error

### Expected behavior

Able to sync large files

### Steps to reproduce the issue

1. Install client v5.0 (https://download.owncloud.com/desktop/ownCloud/daily/5.0/win/?sort=time&order=desc)
2. Add a user account that has 1GB file in the server
3. Sync with VFS OFF

### Screenshots

![Screenshot from 2023-05-31 17-49-26](https://github.com/owncloud/client/assets/52366632/6d7eef66-3691-4042-8564-689ea32523c5) | ![Screenshot from 2023-05-31 17-53-01](https://github.com/owncloud/client/assets/52366632/3f4ab1d4-244a-420e-b53b-5fbb4add0023) | ![Screenshot from 2023-05-31 17-53-11](https://github.com/owncloud/client/assets/52366632/26f5e9fd-2dce-48e4-86af-25a9aa8033b5)
--|--|--
Stuck in syncing mode | After a while error appears | sync tab

### Logs

[ownCloud.log](https://github.com/owncloud/client/files/11620752/ownCloud.log)

### Client version number

ownCloud 5.0.0.11120-daily20230531 [cf17cd](https://github.com/owncloud/client/commit/cf17cd5663b1f9edb81d3182bd884d546cf080fd)
Libraries Qt 6.4.3, 
Using virtual files plugin: wincfapi
windows-10.0.19045

### Installation path (Windows only)

C:\Program Files\ownCloud

### Server information

`ownCloud 10.12.1 (stable)`

**Comment by michaelstingl** [comment]
Unrelated finding:
23-05-31 05:08:05:017 [ info sync.httplogger ]:	"5ce4031d-73bc-4913-8a80-82126f512a18: Response: GET 500 (Error: Error transferring http://10.0.2.2/ocstable/ocs/v2.php/cloud/activity?page=0&pagesize=100&format=json - server replied: Internal Server Error,46ms) http://10.0.2.2/ocstable/ocs/v2.php/cloud/activity?page=0&pagesize=100&format=json Header: { Date: Wed, 31 May 2023 12:08:05 GMT, Server: Apache/2.4.52 (Ubuntu), X-Content-Type-Options: nosniff, X-XSS-Protection: 0, X-Robots-Tag: none, X-Frame-Options: SAMEORIGIN, X-Download-Options: noopen, X-Permitted-Cross-Domain-Policies: none, Expires: Thu, 19 Nov 1981 08:52:00 GMT, Cache-Control: no-store, no-cache, must-revalidate, Pragma: no-cache, Set-Cookie: oc_sessionPassphrase=qvhd6HPpsZnVO%2BGmDC%2FBoRTc5VhzV2czHef97%2FOaDJnkXaGjZeBolOvZdMIKvkFxBgrt4GJeJd9jjfxjKYSdEFkUOplDbHpfhP3TT61Oz7UZVG108SixawSm0Ujmt3r3; expires=Wed, 31-May-2023 12:28:05 GMT; Max-Age=1200; path=/ocstable; HttpOnly; SameSite=Strict, Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src * data: blob:; font-src 'self' data:; media-src *; connect-src *, Content-Length: 242, Connection: close, Content-Type: application/json; charset=utf-8, } Data: [{\"ocs\":{\"meta\":{\"status\":\"failure\",\"statuscode\":500,\"message\":\"Invalid query, please check the syntax. API specifications are here: http:\\/\\/www.freedesktop.org\\/wiki\\/Specifications\\/open-collaboration-services. DEBUG OUTPUT:\\n\"},\"data\":[]}}]"

/cc @HanaGemela

**Comment by michaelstingl** [comment]
@erikjv Qt?

**Comment by Salipa-Gurung** [comment]
### Client version number 
ownCloud 5.0.0.11384-daily20230705 1c0613
Libraries Qt 6.4.3, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: wincfapi
windows-10.0.19045

Large file(>1GB) can sync down from the server(VFS off) :heavy_check_mark: 

### Screenshots
![Screenshot from 2023-07-05 12-26-02](https://github.com/owncloud/client/assets/53458341/896e82ea-ecc7-42eb-9ce7-49d931a04212) | ![Screenshot from 2023-07-05 12-27-33](https://github.com/owncloud/client/assets/53458341/37613058-5f1e-4b1b-b888-6ab43b4004d3) | ![Screenshot from 2023-07-05 12-27-55](https://github.com/owncloud/client/assets/53458341/17abc914-4964-43a5-9e0a-38961fb0092b)
-------------------|-------------------------|----------------
| Syncing mode | No error | Sync tab
