### ISSUE TITLE
libcloudproviders DBus path is no longer unique

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#10914]
https://github.com/owncloud/client/pull/10911 introduced sanitizing for the `libcloudproviders` DBus path that is deduced from the reverse domain name provided by the theme. As with all sanitizing, this potentially removes the uniqueness property from the value, as more than one input value can generate the same output.

We may want to think about how to make these values unique again, e.g., by using some sort of unique identifier. This value (and maybe the resulting DBus path) would have to be stored inside the theme, though. However, this would allow for checking whether the values are unique at least for the themes we provide and use.

CC @erikjv

**Comment by TheOneRing** [comment]
We decided to remove libcloudproviders support.
