### ISSUE TITLE
[QA] Linux install test fails on Fedora 38 due to a wrong email

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#10925]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Linux install test fails on Fedora 38 due to a wrong email
ownCloud ownCloud 4.1.0.11237-daily20230614

Full report here: https://github.com/owncloud/client/issues/10909#issuecomment-1590749524

### Steps to reproduce the issue

Run the Linux install test

### Screenshots

```
|fedora:38|10_key_expiry|	<info@owncloud.com> expires: 2025-03-20
|fedora:38|10_key_expiry|	ERROR: got [<info@owncloud.com>], wanted <devel@s2.owncloud.com>
```

### Expected behavior

No error

### Actual behavior

```
|fedora:38|10_key_expiry|	<info@owncloud.com> expires: 2025-03-20
|fedora:38|10_key_expiry|	ERROR: got [<info@owncloud.com>], wanted <devel@s2.owncloud.com>
```

Full report here: https://github.com/owncloud/client/issues/10909#issuecomment-1590749524

**Comment by HanaGemela** [comment]
So for Fedora 38 we use info@owncloud.com and for the rest of distros we have devel@s2.owncloud.com.
Is that right? @TheOneRing

**Comment by TheOneRing** [comment]
At the moment yes, from 5.0 on we will use only info@...

**Comment by fmoc** [comment]
Yes, exactly.

**Comment by HanaGemela** [comment]
> At the moment yes, from 5.0 on we will use only info@...

Then I'll move this into 5.0 milestone and change then for all platforms

**Comment by fmoc** [comment]
Closing in favor of https://github.com/owncloud/client/issues/11061, which focuses on 5.x+. This issue has been resolved for 4.x
