### ISSUE TITLE
[BUG] TUS -H 'Upload-Metadata: mtime missing

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#10950]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

@glensc reported:

> I’ve started using OCIS 3.0 and using the latest macOS desktop client, all my files show upload time for file date. Full sync hasn’t completed yet so perhaps such is synced after, I’m not sure, though I think if it were syncing date it would be correct on upload.

- https://github.com/owncloud/ocis/issues/1248#issuecomment-1595902593

### Expected behavior

Old local file should have original date on the server after upload.

### Client version number

```
ownCloud 4.1.0.11250 279a6f
Libraries Qt 5.15.8, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: suffix
osx-22.5.0
```

### Server information

oCIS 3.0

### Additional context

Desktop client only sends `Upload-Metadata: filename`:

```
23-06-19 15:03:47:322 [ info sync.httplogger ]:	"a429b677-89f8-4d3c-a955-605de0331f63: 
Request: POST https://ocis.ocis-traefik.daily.owncloud.works/dav/spaces/0f1c87f7-92e5-4549-8197-c7ece53e2e87$4c510ada-c86b-4815-8820-42cdf82c3d51 
Header: { X-OC-Mtime: 1685710240, 
Content-Type: application/offset+octet-stream, 
Content-Length: 1040524, 
Upload-Offset: 0, 
Tus-Resumable: 1.0.0, 
Upload-Metadata: filename L1Bob3Rvcy0wMDEuemlw,checksum U0hBMSBiYjg4ZTY1ZTRkMzNlZTVhMWNjY2QxMjViNzY2OGY1ZWM3NDlkNjNj, 
Upload-Length: 1040524, 
Authorization: Bearer [redacted], 
User-Agent: Mozilla/5.0 (Macintosh) mirall/5.0.0.11270-daily20230619 (testpilotcloud, 
macos-22.5.0 ClientArchitecture: arm64 OsArchitecture: arm64), 
Accept: */*, 
X-Request-ID: a429b677-89f8-4d3c-a955-605de0331f63, 
Original-Request-ID: a429b677-89f8-4d3c-a955-605de0331f63, 
} 
Data: [1040524 bytes of application/offset+octet-stream data]"
```

But should also send the `mtime` in the `Upload-Metadata:` header.

**Comment by TheOneRing** [comment]
Server needs to define expectations first..

**Comment by saw-jan** [comment]
Tested with `ownCloud 5.0.0.11384-daily20230705 1c0613` against `oCIS-3.0.0`
File upload request has `mtime` in `Upload-Metadata` :heavy_check_mark: 

```bash
23-07-04 22:02:01:022 [ info sync.httplogger ]:	"d4b0f977-60b0-4321-bc71-a800eff9dee5:
Request: POST https://192.168.56.1:9200/dav/spaces/b26335e6-34ab-4c9f-be72-f6a7f8877e88$2382df98-b4cd-420d-8fd1-5ccf023a6545
Header: {
    X-OC-Mtime: 1684314742, 
    Content-Type: application/offset+octet-stream, 
    Content-Length: 20766720, 
    Upload-Offset: 0, 
    Tus-Resumable: 1.0.0, 
    Upload-Metadata: filename L3FhLTQuMC4wLjEwOTY3Lng2NC5tc2k=,checksum U0hBMSA2MGJhMmRlOGE5MDk3ZmRhNzgwOGRiZmQxMDYyNzBlM2Q0YzU3Yjdl,mtime MTY4NDMxNDc0Mg==, 
    Upload-Length: 20766720, 
    Authorization: Bearer [redacted], 
    User-Agent: Mozilla/5.0 (Windows) mirall/5.0.0.11384-daily20230705 (ownCloud, windows-10.0.17763 ClientArchitecture: x86_64 OsArchitecture: x86_64), 
    Accept: */*, 
    X-Request-ID: d4b0f977-60b0-4321-bc71-a800eff9dee5, 
    Original-Request-ID: d4b0f977-60b0-4321-bc71-a800eff9dee5, 
} 
Data: [20766720 bytes of application/offset+octet-stream data]"
```
