### ISSUE TITLE
Fix new Linux packages' meta info (license etc.)

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#10963]
Look into old 4.x packages and transfer as much metadata to the new packaging as possible.

**Comment by fmoc** [comment]
Note: this also includes setting dependency information correctly (e.g., depending on libGL/libOpenGL packages).

**Comment by fmoc** [comment]
Implemented in https://gitea.owncloud.services/client/build/commit/5cde5ae65b7e816812953c2bfd3903b6a67b36ec.

**Comment by fmoc** [comment]
Can be tested by downloading a daily build (I just started an `ownCloud` themed one) and inspecting its metadata using `dpkg -I`/`rpm -qpi` on the respective file.

**Comment by HanaGemela** [comment]
the commands' output should look similar compared to the 4.x packages

ownCloud 

- [ ] rpm
- [ ] deb

testpilotcloud

- [ ] rpm
- [ ] deb

**Comment by HanaGemela** [comment]
Today's daily 20230904:

ownCloud deb: 
maintainer is not set, LDNP_META_DEB_VENDOR is missing

ownCloud rmp:
DNP_META_RPM_REQUIRES is missing, LDNP_META_RPM_RELEASE is set to 1

**Comment by HanaGemela** [comment]
> For `.deb`: Priority change is fine. Please provide more information on "multi arch". The other data should be there. Reopening therefore.
> 
> Description change is fine, too.
> 
> `rpm`: Release is okay, too. I left a TODO in the code. There is no urgency to this. The lack of `Requires` is a problem.

In meta info of 4.2 I see:

`Multi-Arch: same`

This information has been lost in 5.0

**Comment by fmoc** [comment]
`Multi-Arch:` is not relevant to us at this point, as far as I can see. `same` seems to have been wrong ever since. We may want to set `Multi-Arch: no` in the future.

**Comment by fmoc** [comment]
For the record, `rpm -qpi` does not list `Requires` and some other metadata fields. You can use `rpm -qpi --requires` to query these.

I fixed a few remaining bugs and started another dailies build.

Please check against the latest version: https://gitea.owncloud.services/client/build/src/branch/5/craft.ps1#L98-L118

**Comment by fmoc** [comment]
Looks good to me now. Please re-test.

**Comment by HanaGemela** [comment]
owncloud rpm requires is:

libGL.so.1
libGLX.so.0
libOpenGL.so.0
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1

should be only:

libGL.so.1
libGLX.so.0
libOpenGL.so.0

**Comment by fmoc** [comment]
`rpmlib` dependencies are automatically added if `rpm`packages need specific features from the package manager itself. We cannot just remove these apparently. I'd ignore these until there are any compatibility problems. The rest looks good.

> Vendor is missing

For `.deb`, there is no vendor. This mistake was corrected already.

> Both should be just libowncloudsync0 but actually are:

Please check the latest version in https://gitea.owncloud.services/client/build/src/branch/5/craft.ps1#L98 where additional were made. The value looks good to me.

**Comment by HanaGemela** [comment]
Moving to Done as @fmoc confirmed that everything is correct
