### ISSUE TITLE
addStatusFilter handles enum values in switch/case to enable compiler warnings for unhandled values

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10960]
https://github.com/owncloud/client/blob/7668e0aef5f110412215f0fd7fc5f40ef26b9f33/src/gui/issueswidget.cpp#L383-L387

**Comment by erikjv** [comment]
@TheOneRing can you elaborate a bit please?

**Comment by TheOneRing** [comment]
At the time I opened the issue we discovered that that we forgot to handle a new state.
If the code would be refactored to iterate over all items and handle them in a switch statement, we would get warnings (now errors) when there is an unhandled case.
