### ISSUE TITLE
Extend "restart required" dialog to Windows

### ISSUE THREAD

**Issue by nicholas-wilson-au** [owncloud/client#10980]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

I am getting an ownCloud notification when I log in to my PC that there is an update available and that I should restart the client to start the update.  However, restarting the client nor restarting the PC results in the update starting.

### Expected behavior

I expect that after closing the program, I should get a UAC request in windows to allow the updater to run.

### Steps to reproduce the issue

Start the owncloud client.
Get the pop up.
right click on the owncloud client taskbar tray icon and select quit owncloud.
Wait.

### Screenshots

https://cloud.owncloud.com/s/mFEXiz1bCBku780

### Logs

https://cloud.owncloud.com/s/k4hSM1oadCTx8K0

### Client version number

[4.0.10896](https://download.owncloud.com/desktop/ownCloud/stable/4.0.0.10896/win/)

### Installation path (Windows only)

c:\program files\owncloud\owncloud.exe

### Server information

cloud.owncloud.com

### Additional context

For reference, while collecting the system information and unrelated program, Notepad++, showed an upgrade was available and its behavior was as expected.

**Comment by michaelstingl** [comment]
This notification isn't really actionable:

<img width="406" alt="CleanShot 2023-07-04 at 14 44 36@2x" src="https://github.com/owncloud/client/assets/214010/6a560f35-824e-4630-a985-6748b7fa4dc7">

Restart needs to be performed from the Settings screen:

<img width="819" alt="CleanShot 2023-07-04 at 14 45 55@2x" src="https://github.com/owncloud/client/assets/214010/92c3dca8-0330-4a2b-8484-afbc4aaabb3d">

Then it successfully updates:

<img width="934" alt="CleanShot 2023-07-04 at 14 46 57@2x" src="https://github.com/owncloud/client/assets/214010/4a24ae7c-7400-4495-9a0f-c8968384d16c">

**Comment by michaelstingl** [comment]
> Notepad++, showed an upgrade was available and its behavior was as expected.

Notepad++ shows own update pop-up, not the native Win notification:

<img width="920" alt="CleanShot 2023-07-04 at 14 52 19@2x" src="https://github.com/owncloud/client/assets/214010/af0c6116-c80a-4787-aa74-be83dfc95523">

**Comment by michaelstingl** [comment]
> Yes we still just emit the equivalent of balloon notifications...
> #7552

Could a click on the Win balloon notification open the Settings screen?

**Comment by TheOneRing** [comment]
Not on Windows https://doc.qt.io/qt-6/qsystemtrayicon.html#messageClicked .
I'd suggest to implement notifications for Windows.
Luckily I'm maintaining a project for that xD

**Comment by TheOneRing** [comment]
Implement a dialogue like mentioned in https://github.com/owncloud/client/issues/10980#issuecomment-1620198377

**Comment by rpausch-owncloud** [comment]
I ran in the very same problem. I manually closed the owncloud client and reopened it: Nothing happened.

The button "Restart & update" is hidden at the bottom of the ownCloud Client Window.
![grafik](https://github.com/owncloud/client/assets/144467728/986624de-de6c-4013-9c8a-e7dff25c0d22)

**Comment by saw-jan** [comment]
Tested with `ownCloud 6.0.0..13174-daily20240121 [ab204c]`

![image](https://github.com/owncloud/client/assets/52366632/7157bc09-ef9a-4a9d-b250-381a75cde530)

But clicking `Restart now` button closes the client but doesn't restart it :x:

**Comment by saw-jan** [comment]
Tested on ``

![Screenshot from 2024-03-28 16-33-24](https://github.com/owncloud/client/assets/52366632/d7f1f1c2-47fb-4a93-b5f6-590f8478a1e0)

- Clicking `Restart now` restarts the client :heavy_check_mark: 
- The dialog appears again and update doesn't start :x:

**Comment by erikjv** [comment]
@saw-jan How was the client started? Did it have command-line options?

**Comment by saw-jan** [comment]
Tested with `ownCloud-6.0.0.14181-daily20240709-x86_64.AppImage`, the update is downloaded and `Restart now` button restarts the client. :heavy_check_mark:

![Screenshot from 2024-07-10 09-49-39](https://github.com/owncloud/client/assets/52366632/12eed2da-9ba2-420e-8842-5bf4814d5110)


>How was the client started? Did it have command-line options?

I just ran `./ownCloud-6.0.0.14181-daily20240709-x86_64.AppImage` in the terminal

**Comment by saw-jan** [comment]
The restart works now.

**Comment by TheOneRing** [comment]
> @saw-jan How was the client started? Did it have command-line options?
> 
> Note to myself and @TheOneRing : we do not check for updates after start-up if the user tried to open a file or if the settings dialog is requested through the cmdline. And with a restart, we pass these options along again.

Can you please open an issue?
