### ISSUE TITLE
ownCloud icon bigger that MacOS standard

### ISSUE THREAD

**Issue by d7oc** [owncloud/client#10995]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

On Mac M2 the ownCloud icon is bigger that other apps haven't noticed this on Intel before. See the attached screenshots.

### Expected behavior

Icon size should correspond to system standard

### Steps to reproduce the issue

1. Open ownCloud
2. Watch the Icon size in the dock and the task switcher

### Screenshots

Taskbar:
<img width="420" alt="Screenshot 2023-07-03 at 11 59 18" src="https://github.com/owncloud/client/assets/102977884/a3a7e645-4163-4073-b6fb-21ee260275ae">

Dock:
<img width="273" alt="Screenshot 2023-07-03 at 11 58 42" src="https://github.com/owncloud/client/assets/102977884/3b1f3ce2-6633-4d91-b521-6786e409b40d">

### Client version number

ownCloud 4.1.0.11250 [279a6f](https://github.com/owncloud/client/commit/279a6f3ff8ffc7138acee7b160ad9edab8f913bb)
Libraries Qt 5.15.8, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: suffix
osx-22.5.0

**Comment by michaelstingl** [comment]
Duplicate for https://github.com/owncloud/client/issues/8251
