### ISSUE TITLE
[ critical  ]: QEventDispatcherWin32::registerTimer: Failed to create a timer (The current process has used all of its system allowance of handles for Window Manager objects.)

### ISSUE THREAD

**Issue by ckupferschmid** [owncloud/client#10994]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

I have like 405'000 files in 113'000 folders that I'm syncing to my private server.
I now run into the error message "[ critical  ]: QEventDispatcherWin32::registerTimer: Failed to create a timer (The current process has used all of its system allowance of handles for Window Manager objects.)" and the sync process terminates.

My Client ist Windows 11, OwnCloud 4.1.0.11250
My Server runs OwnCloud 10.9.0

### Expected behavior

Just keep syncing ....

### Steps to reproduce the issue

that might be hard
1. Have 405'000 files in 113'000 folders (primarily raw images from my camera)
2. Run normal sync
3. Sync runs for some time, then the log file reports 2'200 times the folloing message before the client displays the 'Error' and restarts the sync:
[ critical  ]:	QEventDispatcherWin32::registerTimer: Failed to create a timer (The current process has used all of its system allowance of handles for Window Manager objects.)

### Logs

[extract_owncloud.txt](https://github.com/owncloud/client/files/11930299/extract_owncloud.txt)

### Client version number

ownCloud 4.1.0.11250 [279a6f](https://github.com/owncloud/client/commit/279a6f3ff8ffc7138acee7b160ad9edab8f913bb)
Libraries Qt 5.15.8, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: wincfapi
windows-10.0.22621

### Installation path (Windows only)

C:\Program Files\ownCloud

### Server information

OwnCloud 10.9.0 (stable) on CentOS 8.5 
PHP 7.3.20 
Apache/2.4.37

**Comment by ckupferschmid** [comment]
Downgraded the client to 3.2.1 and removed the IPv6 address from the server hostname. Now the sync has completed. Not sure if the issue was due to network issues, IPv6 related or the version.
Would need further investigation ...

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/pull/11126 only fixes a new issue and is unrelated to this one.

**Comment by TheOneRing** [comment]
I'm closing this issue as there was no update in over a year.
Please reopen if this issue is still relevant.
