### ISSUE TITLE
Credentials dialog for removed account is displayed

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10990]
Under certain conditions the credentials dialog is displayed for an account that is already removed.
When the new credentials are entered, we crash.

**Comment by TheOneRing** [comment]
Appears to be related to the legacy etag polling

**Comment by Salipa-Gurung** [comment]
Tested on Windows 10 and Ubuntu 22.04.2 LTS
ownCloud version :ownCloud 5.0.0.11392-daily20230706

|Expected | Test result |
|-------------|---------------|
| Credential dialog should not be displayed for removed account | Credential dialog is not displayed for removed account :heavy_check_mark: |
