### ISSUE TITLE
DiscoveryPhase::checkSelectiveSyncNewFolder check whether used with vfs

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#10997]

**Comment by erikjv** [comment]
If this is to check if that function is called: yes. I tested it on `1c0613a342614c5dc0e3ba59b1cb945869d908de` (Jul 3), and if nothing changed in the discovery phase, it is called. See stack trace below.

<img width="631" alt="Screenshot 2023-08-01 at 17 53 25" src="https://github.com/owncloud/client/assets/151956/4a090bde-b5a6-4c6b-bb78-65524a705795">

**Comment by TheOneRing** [comment]
I think that was a note to myself and I forgot to check.
I think it was about the propfind performed in the function which is pointless with vfs.
It looks like no propfind is performed.
https://github.com/owncloud/client/blob/3c74da1ada49d27bbe493ad168f364fb17b6c7b9/src/libsync/discoveryphase.cpp#L103-L103
