### ISSUE TITLE
Use MD5 sum to confirm file has changed.

### ISSUE THREAD

**Issue by mpfj** [owncloud/client#110]
** Reopened issue from https://github.com/owncloud/core/issues/523 ***

[See forum posting @ http://forum.owncloud.org/viewtopic.php?f=3&t=5612]

I have a home OC server (4.5.2) up and running on a Linux box.

I took a copy of my parents' photos (13Gig of data) on to a USB disk, took the disk home and then copied the photos (using my local network) on the OC server.

I now setup a sync between the photos directory on my parents' PC (client 1.1.1) and the copy on the OC server at my house.

But the client on my parent's PC is a bit stupid and clearly doesn't check the actual file contents, and so starts to copy all the photos back across to the server.

This is a completely pointless operation.

Surely an md5sum (or similar hash calculation) should be performed to determine if a file copy is required. This is how rsync works under Linux.

I now understand that you only check the modification timestamps, but I would have thought a behaviour like the following would be possible:-

(a) if timestamp has *not* changed, do nothing
(b) if timestamp has changed, perform an md5sum to confirm the contents have change
(c) if the contents have changed, copy the file data
(d) if the contents have not changed, but the timestmpa has, then just sync the timestamps.

Or at least make this an option !?!

**Comment by guruz** [comment]
Please track https://github.com/owncloud/client/issues/2542

**Comment by guruz** [comment]
Re-opening, this is about different issues.

**Comment by DaddySmash** [comment]
Adding checksum capabilities could help a lot to prevent syncing failures.

**Comment by ogoffart** [comment]
duplicate: #3235
