### ISSUE TITLE
libsync: Reduce dependencies on GUI libraries

### ISSUE THREAD

**Issue by badshah400** [owncloud/client#11010]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Firstly, many thanks for the great app.

It would be a big benefit to owncloud client users on headless systems (no-X servers, for instance) to be able to install the command line app (`-DBUILD_GUI=OFF -DBUILD_SHELL_INTEGRATION=OFF`) without dragging in ~350 MiB of Qt GUI and X libraries. As things stand, the shared library libsync (or libowncloudsync) itself drags in all sorts of QtGUI libraries; this makes installing the command-line only client — which depends on libsync — rather useless in comparison to installing the full GUI app for such systems (they both drag in a full GUI stack, but the latter obviously provides more features). To keep noX systems as lean and trim as possible, I request that the GUI app be completely factored out of the libsync library and only be pulled in when the full desktop app is required.

### Proposed solution

Completely factor out GUI dependencies of the libsync library and only require them for the full desktop app.

**Comment by badshah400** [comment]
I don't understand why even let users open issues if they just auto-close without a look or comment from any dev? Like throwing balloons into a black-hole.

**Comment by TheOneRing** [comment]
Keeping the core free of gui libraries is a lot of effort (we would not be able to handle images and icons).
It would be quite some effort to get the libraries in shape.
Quite some effort to maintain that state.

All just to save some MiB of disk space?

**Comment by badshah400** [comment]
> Keeping the core free of gui libraries is a lot of effort (we would not be able to handle images and icons). It would be quite some effort to get the libraries in shape. Quite some effort to maintain that state.
> 
> All just to save some MiB of disk space?

Not really. As mentioned above, on headless systems (no-X) requiring X and GUI libraries to run the simple command line util for manual synchronisation is a bigger issue, independent of the disk space problem. I don't see how the command-line util `owncloudcmd` uses icons or images at all to be honest, and all this request is asking is to free that app of the GUI dependencies (whether be it by making libsync free from GUI or having a simpler GUI-free libsync<noX> separately that `owncloudcmd` then uses, or some other way).

**Comment by TheOneRing** [comment]
The cmd client does not use icons but the classes it uses can provide icons.
Now we can decide to crash if such a code path is hit by accident or we start as a gui ap.
If you need to use the client on a headless system you can set an environment variable `export QT_QPA_PLATFORM=offscreen`.

A massive time investment in the cmd client is currently out of scope.
