### ISSUE TITLE
Show account name in "Login required" dialog

### ISSUE THREAD

**Issue by fwinn** [owncloud/client#11014]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When opening the sync client without unlocking the keyring with the passwords on Linux, the "Login required" dialog pops up.
In my case, I've got two accounts with the same username, but on different servers. So I get the exact same password prompt twice, but it doesn't show which prompt is for which server so I can't know.

### Expected behavior

I expected to see the corresponding account for the username and password.

### Steps to reproduce the issue

1. Start Owncloud sync client with multiple accounts
2. Do **not** unlock system keyring

### Screenshots

![Screenshot_20230706_162412](https://github.com/owncloud/client/assets/64732965/1605d739-06b8-4a6f-a14d-559f66fb8d21)

### Client version number

ownCloud 4.1.0 [GITDIR](https://github.com/owncloud/client/commit/GITDIR-NOTFOUND)
Libraries Qt 5.15.10, OpenSSL 3.1.1 30 May 2023
Using virtual files plugin: suffix
opensuse-tumbleweed-6.3.9-1-default

### Desktop environment (Linux only)

OpenSUSE Tumbleweed 20230705
KDE Plasma 5.27.6
KDE Frameworks 5.107.0
Graphics Platform: X11

### Client package version and origin (Linux only)

Installed from standard openSUSE repository

**Comment by michaelstingl** [comment]
Yes, same information as in the account bar:

![CleanShot 2023-07-06 at 16 51 10@2x](https://github.com/owncloud/client/assets/214010/eeee7490-9cce-4e26-bdd8-6c5b1642eae0)

**Comment by saw-jan** [comment]
Tested with `ownCloud 5.0.0.11640-daily20230803`: :heavy_check_mark: 

![Screenshot from 2023-08-03 11-35-22](https://github.com/owncloud/client/assets/52366632/11c92690-eca3-4d99-aed5-173baa75b430)
