### ISSUE TITLE
[macOS] Progress bar misplaced

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#11022]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Progress bar misplaced:

![CleanShot 2023-07-10 at 17 28 43](https://github.com/owncloud/client/assets/214010/3c69f1c6-0dfa-486a-b954-0d5a0c03f318)

### Expected behavior

Progress bar should be attached to the related sync folder connection.

### Client version number

```
testpilotcloud 5.0.0.11221-daily20230611 078f59
Libraries Qt 6.4.3, OpenSSL 1.1.1t 7 Feb 2023
Using virtual files plugin: suffix
macos-22.5.0
```

**Comment by TheOneRing** [comment]
Upstream Qt but we patch. Ill investigate why the patch fails.

**Comment by TheOneRing** [comment]
Hmm your build I a month old.

**Comment by michaelstingl** [comment]
> Hmm your build I a month old.

Ups. Maybe I downloaded the wrong daily 🤔. Let me check

**Comment by michaelstingl** [comment]
Correct in testpilotcloud 5.0.0.11432-daily20230711 b4273b ✅ 

![CleanShot 2023-07-11 at 09 26 52@2x](https://github.com/owncloud/client/assets/214010/215ef48a-1ebd-4607-ab3f-9ace196b4836)

```
testpilotcloud 5.0.0.11432-daily20230711 b4273b
Libraries Qt 6.4.3, OpenSSL 3.1.1 30 May 2023
Using virtual files plugin: suffix
macos-22.5.0
```
