### ISSUE TITLE
Use QLocale to format filesize

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11024]
At the moment we format datasizes in https://github.com/owncloud/client/blob/354b47e49bab6752b09315ac357cdeb13d951047/src/common/utility.cpp#L82

Qt however provides a localized function for that.
https://doc.qt.io/qt-5/qlocale.html#formattedDataSize-1

For now use: QLocale::DataSizeTraditionalFormat
- update once https://github.com/owncloud/enterprise/issues/5808 decided

**Comment by HanaGemela** [comment]
Scenarios to test:

1) File sizes every where in the client have to be the same - selective sync, quota, Activity tab, sync progress

2) Correct number of decimal places.
Expected result:
bytes and kB without decimal places
MB one decimal place
GB and above two decimal places

3) Decimal places are marked correctly by decimal point (e.g. United Kingdom) or decimal comma (e.g. Spain, France, Norway, the Czech Republic, Denmark) according to a country

**Comment by HanaGemela** [comment]
Passed in ownCloud 6.0.0.12685-daily20231124, mac
