### ISSUE TITLE
[Linux] "Cancel account setup" dialog not modal

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#11032]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When canceling the account setup, a dialog is shown asking for confirmation. It's possible to click on the setup wizard again, which thereafter effectively hides the confirmation dialog. To be able to access it again, one has to move it out of the way. Clicking on the item in the taskbar or using the systray to show the UI do not yield a different result.

### Expected behavior

The cancel dialog must be a mandatory modal dialog that is always shown above all other windows.

### Screenshots

![screenshot_2023-07-12_12-14-00](https://github.com/owncloud/client/assets/80399010/dcedd19b-acbe-4d1b-8b96-72872c6a45a1)

![screenshot_2023-07-12_12-14-04](https://github.com/owncloud/client/assets/80399010/1fdb9145-9ef3-487b-a443-910bf06b635c)

### Client version number

Build made from latest `master`. Should affect the current dailies, too.

**Comment by TheOneRing** [comment]
Can't reproduce on Windows.

**Comment by fmoc** [comment]
Smells like a Qt bug.

**Comment by fmoc** [comment]
Needs to be tested on Wayland.

**Comment by saw-jan** [comment]
Tested with `ownCloud 6.0.0.13177-daily20240122 [ab204c]`

Confirmation dialog is always on top of new account setup window
