### ISSUE TITLE
Implement local collissions following the ownCloud convention

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#11048]
When local sync folders collide (re-adding the same Space, or syncing 2 Spaces with identical names), they should be created with "` (2)`" at the end. (Same as in other ownCloud products, for example when I receive 2 Shares with the same name.

![CleanShot 2023-07-21 at 15 35 34](https://github.com/owncloud/client/assets/214010/28151a82-0cbf-495b-b4b8-4ac9a7f59fd3)

**Comment by TheOneRing** [comment]
See https://github.com/owncloud/client/blob/23bbc69759177b97e37e7ba1cd75de6ca7a8be67/src/gui/folderman.cpp#L788-L788

**Comment by Salipa-Gurung** [comment]
Tested with 
Desktop client version `ownCloud 5.0.0.11822-daily20230821 65017f`
windows-10.0.19045


Syncing 2 spaces with same name, one space is created with `(2)` at the end. :heavy_check_mark: 

![Screenshot from 2023-08-21 10-08-51](https://github.com/owncloud/client/assets/53458341/4bb5dc8a-1f93-498f-86db-89826c6e86bb)

**Comment by michaelstingl** [comment]
> @michaelstingl haven't you meant the Space name?

No, only collision of local sync folders

**Comment by Salipa-Gurung** [comment]
Tested with
Desktop client version `ownCloud 5.0.0.11822-daily20230821 65017f`
windows-10.0.19045


Before force sync | After force sync 
---|---
| Error occurs: `Error transferring https://192.168.56.1:9200/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668$a0ca6a90-a365-4782-871e-d44447bbc668/test-share (1) - server replied: Not Found` | it works as expected|
|  [ownCloud.log](https://github.com/owncloud/client/files/12394020/ownCloud.log) | [ownCloud.log](https://github.com/owncloud/client/files/12394082/ownCloud.log) |
| ![Screenshot from 2023-08-21 13-06-55](https://github.com/owncloud/client/assets/53458341/46cbca20-538e-4e48-a0ba-349d6a854c9b) ![Screenshot from 2023-08-21 13-07-44](https://github.com/owncloud/client/assets/53458341/dd6ac082-fdf7-4227-8aa6-7bac891b6d27) | ![Screenshot from 2023-08-21 13-14-47](https://github.com/owncloud/client/assets/53458341/28aaa9b9-c130-4d6a-bee1-8bff5a293b13)

**Comment by HanaGemela** [comment]
> Tested with Desktop client version `ownCloud 5.0.0.11822-daily20230821 65017f` windows-10.0.19045
> 
> Syncing 2 spaces with same name, one space is created with `(2)` at the end. ✔️
> 
> ![Screenshot from 2023-08-21 10-08-51](https://user-images.githubusercontent.com/53458341/261917612-4bb5dc8a-1f93-498f-86db-89826c6e86bb.png)

Closing as fixed and passed QA.
