### ISSUE TITLE
Conflict existing Linux packages

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#11057]
Set up metadata in new Linux packages to conflict with existing, distribution provided packages to avoid clashes on the filesystem (tested at least against the set of Linux distribution releases we support officially). This should ensure smooth updates which clean up unused dependency packages, too.

**Comment by fmoc** [comment]
This change needs to be tested with upgrades from 4.x installations resp. when switching from distro-provided packages to ours. Therefore, it is blocked by #11080.

**Comment by fmoc** [comment]
Conflicts on Debian/Ubuntu:
- `owncloud-client`: `owncloud-client-cmd`, `owncloud-client-data`
- `owncloud-client-caja`: `caja-owncloud`
- `owncloud-client-nautilus`: `nautilus-owncloud`
- `owncloud-client-nemo`: `nemo-owncloud`
- `owncloud-client-dolphin`: `dolphin-owncloud`

**Comment by fmoc** [comment]
Implemented for `owncloud-client` in https://gitea.owncloud.services/client/build/commit/622577594e40e8d5cc1fbbbd7c13411c9c7e791b for Debian/Ubuntu, for the RPM-based distros no `Conflicts` metadata is needed.

The shell integration packages never conflicted their distro-provided counterparts, so no action required there. We can implement such changes separately if needed.

I'll have the CI build another set of dailies ASAP.

To test, make sure you install the distro-provided `owncloud-client`, `owncloud-client-cmd` and `owncloud-client-data` on Debian 12 and Ubuntu 22.04. Then install the client using the 5.0 dailies Linux repositories and run an upgrade. The `cmd` and `data` packages should be removed upon the upgrade because they are replaced by the `-client` package.

**Comment by HanaGemela** [comment]
Testing coordinated in https://github.com/owncloud/client/issues/11171
