### ISSUE TITLE
Deploy icons, MIME files and other resources needed for proper system integration with new Linux packages

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#11059]
The experimental Linux packages already deploy desktop entries to the system installation directories to allow users to launch the client. However, there are additional files that need to be deployed such as application icons or MIME files. We need to make the tools deploy those files correctly as well.

**Comment by fmoc** [comment]
Implemented and seems to work fine.

**Comment by fmoc** [comment]
To test, please make sure that icons are available in `/usr/share/icons` whose filenames matches `/usr/share/applications/<shortname>.desktop`'s `Icon=` entry and show up in the applications menu. Also, please make sure the OS suggests you to open `.owncloud` files with the client in VFS mode.

**Comment by HanaGemela** [comment]
QA in https://github.com/owncloud/client/issues/11171
