### ISSUE TITLE
[QA] Make sure new packages pass the install tests

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#11061]

**Comment by fmoc** [comment]
There will be builds around 1pm CEST on https://download.owncloud.com/desktop/ownCloud/daily/5.0/linux which can be used for a first run of the install tests.

**Comment by HanaGemela** [comment]
The first run gives a report without data. The error with appimages is fault of the test as there is no specification how to adjust the path of the appimage - needs better documentation  cc @jnweiger 

|| Linux Package Installation Report |
|-|-|
|date| Mon Aug 28 10:36:13 CEST 2023
|repourl| https://download.owncloud.com/desktop/ownCloud/daily/5.0/linux/download/
|package| owncloud-client

<details><summary>Test details (click to view)</summary>

|Platform|Test|Result|
|-|-|-|
|debian:11|SETUP ERROR|	find_appimage_url failed: ''
|debian:11|SETUP ERROR|	curl https://download.owncloud.com/desktop/ownCloud/daily/5.0/linux/download//Debian_11 -> status 404
|debian:12|SETUP ERROR|	find_appimage_url failed: ''
|debian:12|SETUP ERROR|	curl https://download.owncloud.com/desktop/ownCloud/daily/5.0/linux/download//Debian_12 -> status 404
|fedora:38|SETUP ERROR|	find_appimage_url failed: ''
|fedora:38|SETUP ERROR|	curl https://download.owncloud.com/desktop/ownCloud/daily/5.0/linux/download//Fedora_38 -> status 404
|fedora:36|SETUP ERROR|	find_appimage_url failed: ''
|fedora:36|SETUP ERROR|	curl https://download.owncloud.com/desktop/ownCloud/daily/5.0/linux/download//Fedora_36 -> status 404
|fedora:37|SETUP ERROR|	find_appimage_url failed: ''
|fedora:37|SETUP ERROR|	curl https://download.owncloud.com/desktop/ownCloud/daily/5.0/linux/download//Fedora_37 -> status 404
|ubuntu:22.04|SETUP ERROR|	find_appimage_url failed: ''
|ubuntu:22.04|SETUP ERROR|	curl https://download.owncloud.com/desktop/ownCloud/daily/5.0/linux/download//Ubuntu_22.04 -> status 404
|ubuntu:22.10|SETUP ERROR|	find_appimage_url failed: ''
|ubuntu:22.10|SETUP ERROR|	curl https://download.owncloud.com/desktop/ownCloud/daily/5.0/linux/download//Ubuntu_22.10 -> status 404
|ubuntu:23.04|SETUP ERROR|	find_appimage_url failed: ''
|ubuntu:23.04|SETUP ERROR|	curl https://download.owncloud.com/desktop/ownCloud/daily/5.0/linux/download//Ubuntu_23.04 -> status 404
|opensuse/leap:15.4|SETUP ERROR|	find_appimage_url failed: ''
|opensuse/leap:15.4|SETUP ERROR|	curl https://download.owncloud.com/desktop/ownCloud/daily/5.0/linux/download//openSUSE_Leap_15.4 -> status 404

**Comment by HanaGemela** [comment]
Include also https://github.com/owncloud/client/issues/11060

**Comment by fmoc** [comment]
Tests run again and finished successfully. We track their formatting in a separate issue.
