### ISSUE TITLE
Add "reset to default" UI element for local sync dir to last setup wizard page

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#11078]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Currently, once the user changes the local sync dir, the value will be stored and shown every time the page is displayed. There is no way for the user to reset the value at the moment, they need to start over completely.

### Proposed solution

A "reset button" next to the line edit was suggested so far. Perhaps Qt provides us with some nicer option.

**Comment by saw-jan** [comment]
Tested with `ownCloud 5.0.0.11679-daily20230808 ad2489`

![Screenshot from 2023-08-08 16-21-58](https://github.com/owncloud/client/assets/52366632/e3a8a9c1-c727-419f-b338-2d67ea7db643) | ![Screenshot from 2023-08-08 16-20-29](https://github.com/owncloud/client/assets/52366632/e1672b08-9db7-44d8-82cc-d4abff95391a)
--|--
| 1. initial | 2. edit | 3.reset |
![Screenshot from 2023-08-08 16-20-22](https://github.com/owncloud/client/assets/52366632/7588d54a-3939-45af-8889-0f84f3a355a0)
3. reset
