### ISSUE TITLE
Set up distro-specific Linux repositories again with new `.deb`/`.rpm` packages and distro-specific extension packages

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#11080]
We need to change the build process to first complete `client/build`, then run `client/build-linux`. There, we build the shell extension packages for every supported distro, then combine those with the distro-independent `.deb`/`.rpm` packages and generate Linux repositories with the existing scripts (including the download page).

**Comment by fmoc** [comment]
Status update: building of Dolphin plugins and repositories is set up (the former as a prototype at the moment). Next steps: restore Nautilus plugins, set up automated daily builds.

**Comment by fmoc** [comment]
Nautilus and overlays icons packages restored. I need to make a test build first, then we can close this issue.

**Comment by fmoc** [comment]
Branding implemented, daily builds are on the way.

**Comment by HanaGemela** [comment]
QA in https://github.com/owncloud/client/issues/11171
