### ISSUE TITLE
Unify button/widget height in advanced configuration page

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#11094]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The "reset to default" button introduced in https://github.com/owncloud/client/pull/11092 appears taller than the button next to it.

### Expected behavior

The UI elements in this line should have the same height.

### Client version number

5.0.0 master (post https://github.com/owncloud/client/pull/11092).

**Comment by Salipa-Gurung** [comment]
#### Tested with desktop client version : `ownCloud 5.0.0.11938-daily20230828 84a468`

ubuntu-6.2.0-26-generic  :x:| windows-10.0.19045  :heavy_check_mark: 
---|---
![Screenshot from 2023-08-28 11-50-28](https://github.com/owncloud/client/assets/53458341/87c5af44-956f-4dd0-b10e-f7a91863931b) | ![Screenshot from 2023-08-28 11-49-33](https://github.com/owncloud/client/assets/53458341/c2eea0ae-f0f6-4266-b54e-adedbbe14d0f)
![Screenshot from 2023-08-28 11-51-11](https://github.com/owncloud/client/assets/53458341/cf3ef18f-f252-49d5-b0cc-6f733626c106) | ![Screenshot from 2023-08-28 11-57-37](https://github.com/owncloud/client/assets/53458341/5f2e774a-1f98-4de0-8a1d-c6b7bd038bd4) 
UI elements are of different heights |  UI elements has same height

**Comment by HanaGemela** [comment]
Moving to done as the buttons are the same now. New issue has been opened for Ubuntu
