### ISSUE TITLE
Client won't retry to sync upon sync error

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11104]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Files that fail to upload/sync to the server are not retried and are not blacklisted.

### Expected behavior

Try to sync and blacklist the file if not synced upon certain retries

### Steps to reproduce the issue

1. Add an account to the client
2. Create and try to upload a file having very long name
`aQuickBrownFoxJumpsOverAVeryLazyDog-aQuickBrownFoxJumpsOverAVeryLazyDog-aQuickBrownFoxJumpsOverAVeryLazyDog-aQuickBrownFoxJumpsOverAVeryLazyDog-aQuickBrownFoxJumpsOverAVeryLazyDog-aQuickBrownFoxJumpsOverAVeryLazyDog-aQuickBrownFo.txt`
3. wait for sync - sync error :heavy_check_mark: 
4. No sync retries and file is not blacklisted :x:

### Screenshots

![Screenshot from 2023-08-09 16-50-35](https://github.com/owncloud/client/assets/52366632/2627a1c1-3793-40fd-8a37-e9ab634df39d)

### Logs

[ownCloud.log](https://github.com/owncloud/client/files/12301488/ownCloud.log)

### Client version number

ownCloud ownCloud 5.0.0.11675-beta.1 https://github.com/owncloud/client/commit/77cf77e78741e715421b9e24a729a8d756044c97
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: suffix
ubuntu-6.2.0-26-generic

### Server information

ownCloud 10.13.0 prealpha (git)

**Comment by TheOneRing** [comment]
Apparently the hourly discovery also does not happen.

**Comment by Salipa-Gurung** [comment]
### Client version number
ownCloud 5.0.0.11775-daily20230817 65017f
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: wincfapi
windows-10.0.19045

### Server 
 ownCloud 10.12.2 (stable)

1. Sync Error :heavy_check_mark: 
2. File is blacklisted when not synced upon certain retries :heavy_check_mark: 

![Screenshot from 2023-08-17 12-47-25](https://github.com/owncloud/client/assets/53458341/8621c9ce-edfa-4d20-9312-a3437a305d45)
