### ISSUE TITLE
[QA] Add account button is not highlighted

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11101]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

'Add account' is not selectable

ownCloud 5.0.0.11675-beta.1

### Steps to reproduce the issue

1. Remove all the accounts from the client

### Screenshots

<img width="962" alt="Screenshot 2023-08-09 at 10 19 44" src="https://github.com/owncloud/client/assets/49001702/ae395436-a380-4013-a952-3757e1cf22f7">

### Expected behavior

Add account button is selected when the Account Wizard is opened

### Actual behavior

Activity tab is selected

**Comment by TheOneRing** [comment]
This is a very minor cosmetic issue
