### ISSUE TITLE
Multiple "Remove All Files" dialog boxes

### ISSUE THREAD

**Issue by grgprarup** [owncloud/client#11102]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

C2041 - Desktop sync client smoke test
While Testing 
[owncloud_5.0.0.11675-beta.1.deb](https://download.owncloud.com/desktop/ownCloud/testing/5.0.0.11675-beta.1/linux-appimage/owncloud_5.0.0.11675-beta.1.deb)
[owncloud_5.0.0.11675-beta.1.rpm](https://download.owncloud.com/desktop/ownCloud/testing/5.0.0.11675-beta.1/linux-appimage/owncloud_5.0.0.11675-beta.1.rpm)

Ubuntu 22.04
Fedora 38

The `Remove all files` `Keep files` dialog box appears multiple (equal to the number of files) when all files are deleted from the file manager but work fine when deleted from the server.

### Steps to reproduce the issue

1. Connect with the server
2. Upload multiple files to the server
3. Let sync with the client (or Force sync)
4. Delete all files from the file manager

### Screenshots

![Screenshot from 2023-08-09 12-57-56](https://github.com/owncloud/client/assets/8559121/e3024637-a02b-4840-a291-1ff7105751ee)

### Expected behavior

A single dialog box should appear.

![Screenshot from 2023-08-09 14-42-31](https://github.com/owncloud/client/assets/8559121/b43e58fe-e8ec-4049-b1c6-a1953d4eaff5)

### Actual behavior

Multiple dialog boxes appeared. Also, the UI of the dialog box is distorted.
![Screenshot from 2023-08-09 12-57-56](https://github.com/owncloud/client/assets/8559121/eba7b8e0-8f32-48ec-85a4-74d822539a7e)
[ownCloud.log](https://github.com/owncloud/client/files/12300444/ownCloud.log)

**Comment by HanaGemela** [comment]
Can recreate with mac ownCloud 5.0.0.11675-beta.1

**Comment by fmoc** [comment]
Time box for reproduction: 1 hour.

**Comment by HanaGemela** [comment]
Passed in ownCloud 5.0.0.12024-daily20230904, mac
