### ISSUE TITLE
[QA] file browser integration (nemo, nautilus, dolphin) script should added to the install instructions

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#11134]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

E.g. https://download.owncloud.com/desktop/ownCloud/daily/5.0/linux/download/
has the option to manually copy past some install instructions, or to download and run a INSTALL.sh installer script.

The download area does not mention browser integration (aka shell integration)

### Expected behavior

Expected behaviour:
* link to https://github.com/owncloud/client-desktop-install-shell-integration#readme
* and/or directly integrate that into the INSTALL.sh

### Client version number

any. e.g. 5.0

**Comment by michaelstingl** [comment]
Currently we have it only mentioned in the docs:
- https://doc.owncloud.com/desktop/next/installing.html#installing-shell-integration-packages

**Comment by spupuz** [comment]
why not supporting arch too? is quite used in these days
