### ISSUE TITLE
Provide separate package for overlay icons again

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11133]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Upgrading from 4.2 to 5.0 using `.deb` is not possible. The upgrade command throws error:

```bash
sudo apt install ./owncloud-client_5.0.0.11822-daily20230821.deb
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'owncloud-client' instead of './owncloud-client_5.0.0.11822-daily20230821.deb'
The following packages were automatically installed and are no longer required:
  libsecret-tools ocqt5152-libqt5core5a ocqt5152-libqt5dbus5 ocqt5152-libqt5gui5 ocqt5152-libqt5keychain1 ocqt5152-libqt5network5 ocqt5152-libqt5sql5 ocqt5152-libqt5sql5-sqlite ocqt5152-libqt5widgets5
  ocqt5152-qtsvg5 ocqt5152-qttranslations5 ocqt5152-qtwayland5
Use 'sudo apt autoremove' to remove them.
The following packages will be upgraded:
  owncloud-client
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 0 B/36.4 MB of archives.
After this operation, 348 GB of additional disk space will be used.
Get:1 /home/mimi/Downloads/owncloud-client_5.0.0.11822-daily20230821.deb owncloud-client amd64 5.0.0.11822-daily20230821 [36.4 MB]
Reading changelogs... Done           
(Reading database ... 155323 files and directories currently installed.)
Preparing to unpack .../owncloud-client_5.0.0.11822-daily20230821.deb ...
Unpacking owncloud-client (5.0.0.11822-daily20230821) over (4.2.0+oc-11670) ...
dpkg: error processing archive /home/mimi/Downloads/owncloud-client_5.0.0.11822-daily20230821.deb (--unpack):
 trying to overwrite '/usr/share/icons/hicolor/128x128/apps/ownCloud_error.png', which is also in package owncloud-client-overlays-icons 4.2.0+oc-11670
Errors were encountered while processing:
 /home/mimi/Downloads/owncloud-client_5.0.0.11822-daily20230821.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

### Expected behavior

Expected update to be successful

### Steps to reproduce the issue

1. Install client 4.2 https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/
2. Install nautlius
    ```
    sudo apt install owncloud-client-nautilus
    ```
3. Add an account
4. Quit the client
5. Install client 5.0 (https://download.owncloud.com/desktop/ownCloud/daily/5.0/linux-appimage/)
    ```bash
    sudo apt install ./owncloud-client_5.0.0.<build>-daily<date>.deb
    ```

### Client version number
ownCloud 5.0.0.11822-daily20230821-x86_64.AppImage

**Comment by fmoc** [comment]
We need to either (re-)provide or conflict this old package. See #10963.

**Comment by fmoc** [comment]
Packages are back, will be available with the next daily builds.

**Comment by saw-jan** [comment]
Tested in https://github.com/owncloud/client/issues/10702#issuecomment-1700513444
