### ISSUE TITLE
Client crashes when database version check fails

### ISSUE THREAD

**Issue by erikjv** [owncloud/client#11135]
The check is done after the application constructor is run. In this constructor, a couple of signals get fired, which in turn queues showing the GUI window (e.g. an account is logged out, and needs new authentication). When the version check fails, it brings up a (modal) dialog, and the event loop is spun, which also brings up the GUI window. Somewhere halfway this, the quit button is clicked, tearing down the application with a half-way set up window. This causes a crash somewhere deep in a child-widget-deletion process.

The fix is to move even more out of the application constructor, so the full check can be done before any other GUI code is run. This comes down to setting up the account manager and the folder manager in the main function.

This should fix the crash mentioned in #11114 .

**Comment by TheOneRing** [comment]
I think you might be correct but as the crash is in the destructor of the ui, it might also help if you call qApp->exec() in https://github.com/owncloud/client/blob/65017f978ed45f3f2ff0e639c367bb63d6e7e333/src/gui/main.cpp#L354

so that the delayed close is executed:
https://github.com/owncloud/client/blob/65017f978ed45f3f2ff0e639c367bb63d6e7e333/src/gui/main.cpp#L210-L214

**Comment by Salipa-Gurung** [comment]
### Desktop client version: `ownCloud 5.0.0.11907-daily20230825 d82ccf`
Tested with both oc10 and ocis server
- older client version cannot be used with upgraded database :heavy_check_mark: 
- client does not crash :heavy_check_mark: 

ubuntu-6.2.0-26-generic | windows-10.0.19045 |
---|---
![Screenshot from 2023-08-25 12-10-01](https://github.com/owncloud/client/assets/53458341/2d50a7ff-b41f-44fc-979b-23de0b50e3ce) | ![Screenshot from 2023-08-25 12-00-01](https://github.com/owncloud/client/assets/53458341/7ede85a1-216d-406a-9c63-2f9af1fce5ff)
