### ISSUE TITLE
[QA] Can't upgrade from 4.2 to 5.0 beta1 on Fedora 37

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11130]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Can't upgrade from 4.2 to 5.0 beta on Fedora 37

### Steps to reproduce the issue

1. Install 4.2. on Fedora 37 as described here: https://download.owncloud.com/desktop/ownCloud/stable/4.2.0.11670/linux/download/

2. Install 5.0 beta1 rpm package (https://download.owncloud.com/desktop/ownCloud/testing/5.0.0.11675-beta.1/linux-appimage/) 

### Screenshots

No screenshot 

### Expected behavior

Successfully installed

### Actual behavior

[hana@fedora Downloads]$ sudo rpm -i owncloud_5.0.0.11675-beta.1.rpm
[sudo] Passwort für hana:
Datei /usr/bin/owncloud aus der Installation von owncloud-5.0.0.11675_beta.1-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/bin/owncloudcmd aus der Installation von owncloud-5.0.0.11675_beta.1-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/applications/owncloud.desktop aus der Installation von owncloud-5.0.0.11675_beta.1-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/1024x1024/apps/owncloud.png aus der Installation von owncloud-5.0.0.11675_beta.1-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/128x128/apps/owncloud.png aus der Installation von owncloud-5.0.0.11675_beta.1-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/16x16/apps/owncloud.png aus der Installation von owncloud-5.0.0.11675_beta.1-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/24x24/apps/owncloud.png aus der Installation von owncloud-5.0.0.11675_beta.1-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/256x256/apps/owncloud.png aus der Installation von owncloud-5.0.0.11675_beta.1-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/32x32/apps/owncloud.png aus der Installation von owncloud-5.0.0.11675_beta.1-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/48x48/apps/owncloud.png aus der Installation von owncloud-5.0.0.11675_beta.1-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/64x64/apps/owncloud.png aus der Installation von owncloud-5.0.0.11675_beta.1-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64

**Comment by fmoc** [comment]
Known problem. Should be fixed in latest dailies. Please try https://download.owncloud.com/desktop/ownCloud/daily/5.0/latest/linux-appimage/. The issue was the name of the new package didn't match the old one's (`owncloud` vs. `owncloud-client`).

**Comment by HanaGemela** [comment]
Not fixed 

```
[hana@fedora Downloads]$ sudo rpm -i owncloud-client_5.0.0-daily-latest.rpm
[sudo] Passwort für hana:
Datei /usr/bin/owncloud aus der Installation von owncloud-client-5.0.0.11804_daily20230818-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/bin/owncloudcmd aus der Installation von owncloud-client-5.0.0.11804_daily20230818-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/applications/owncloud.desktop aus der Installation von owncloud-client-5.0.0.11804_daily20230818-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/1024x1024/apps/owncloud.png aus der Installation von owncloud-client-5.0.0.11804_daily20230818-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/128x128/apps/owncloud.png aus der Installation von owncloud-client-5.0.0.11804_daily20230818-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/16x16/apps/owncloud.png aus der Installation von owncloud-client-5.0.0.11804_daily20230818-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/24x24/apps/owncloud.png aus der Installation von owncloud-client-5.0.0.11804_daily20230818-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/256x256/apps/owncloud.png aus der Installation von owncloud-client-5.0.0.11804_daily20230818-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/32x32/apps/owncloud.png aus der Installation von owncloud-client-5.0.0.11804_daily20230818-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/48x48/apps/owncloud.png aus der Installation von owncloud-client-5.0.0.11804_daily20230818-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
Datei /usr/share/icons/hicolor/64x64/apps/owncloud.png aus der Installation von owncloud-client-5.0.0.11804_daily20230818-1.x86_64 kollidiert mit der Datei aus dem Paket owncloud-client-4.2.0-11670.x86_64
```

**Comment by fmoc** [comment]
Apparently, one may not use `rpm` to upgrade packages, as it will then complain about such conflicts. Can you try to use the repositories and `dnf`? A new set of dailies is on the way and should be uploaded by ~1pm today.

**Comment by fmoc** [comment]
Upgrade works fine when using the instructions from the download page. Also, `dnf install owncloud-client_5.0.0.11857-daily20230822.rpm` works just as expected.

Upgrades directly with `rpm` are an unsupported use case. Closing therefore.
