### ISSUE TITLE
Move auto-update check before new account wizard

### ISSUE THREAD

**Issue by erikjv** [owncloud/client#11141]
The auto updater is checked in the `main()` function after the UI is initialised. If an update is available, the application will quit. So it would be better to do this before any UI is set up. But we need to check if the updater depends on other UI to be there.

See https://github.com/owncloud/client/pull/11137#discussion_r1303036960

**Comment by erikjv** [comment]
This is a bit more complicated than described because of command-line options: if a user requested opening the settings dialog, or to open a (virtual) file, then upgrading (and quitting) will not be appreciated. So, the steps are:

1. Version checks
2. if opening the settings dialog is requested, do that, and no update check.
3. if not opening the dialog, but opening a file is requested, do that, and no update check
4. if non of the above is the case, do the update check

Then lastly, if no accounts are configured (and no update is found), open the new-account-wizard.

**Comment by HanaGemela** [comment]
Steps to test:
1. Update using auto updater

**Comment by HanaGemela** [comment]
Update using online auto updater works from 4.2. to ownCloud 5.0.0.12103-daily20230912
