### ISSUE TITLE
The UI elements in a line should have the same height on Ubuntu

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11156]
#### Tested with desktop client version : `ownCloud 5.0.0.11938-daily20230828 84a468`

ubuntu-6.2.0-26-generic  :x:| windows-10.0.19045  :heavy_check_mark: 
---|---
![Screenshot from 2023-08-28 11-50-28](https://github.com/owncloud/client/assets/53458341/87c5af44-956f-4dd0-b10e-f7a91863931b) | ![Screenshot from 2023-08-28 11-49-33](https://github.com/owncloud/client/assets/53458341/c2eea0ae-f0f6-4266-b54e-adedbbe14d0f)
![Screenshot from 2023-08-28 11-51-11](https://github.com/owncloud/client/assets/53458341/cf3ef18f-f252-49d5-b0cc-6f733626c106) | ![Screenshot from 2023-08-28 11-57-37](https://github.com/owncloud/client/assets/53458341/5f2e774a-1f98-4de0-8a1d-c6b7bd038bd4) 
UI elements are of different heights |  UI elements has same height 

cc: @fmoc

_Originally posted by @Salipa-Gurung in https://github.com/owncloud/client/issues/11094#issuecomment-1695094567_

**Comment by TheOneRing** [comment]
Todo:
-Replace ... with the 3dot icon
- Try reverting the size restrictions

**Comment by TheOneRing** [comment]
With https://github.com/owncloud/client/pull/11215 we might still get different heights but thats the system theme and no longer us dictating sizes.
