### ISSUE TITLE
Command line invocations like `-h` trigger a quit of the main application

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11151]
Steps to reproduce:
Start the client
Invoke the client with -h in the terminal

Expected behaviour:
The help text is displayed, and the main instance continues to run.

Actual behaviour:
The help text is displayed.
The main instance quits.

**Comment by HanaGemela** [comment]
@TheOneRing are the steps to recreate complete? I can't recreate in ownCloud 5.0.0.11499-daily20230719 on mac

**Comment by TheOneRing** [comment]
Maybe windows only?

**Comment by HanaGemela** [comment]
Passsed in ownCloud-5.0.0.12034-daily20230905.x64
