### ISSUE TITLE
ubuntu 22.04 SSL handshake failed

### ISSUE THREAD

**Issue by eagirre** [owncloud/client#11172]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Moving to a new laptop. 

Owncloud client 2.5.1.10973+dsg-1ubuntu4 on Ubuntu 20.04.6 LTS was working on my company's server: https:/ehubox.ehu.eus

In the new laptop I installed ubuntu 22.04.3 LTS and the latest stable owncloud

When trying to connect to https:/ehubox.ehu.eus I get: Could not detect compatible server at https://ehubox.ehu.eus

The log mentions "Failed to resolve URL https://ehubox.ehu.eus, error: SSL handshake failed"

### Expected behavior

I expected it to ask for user and password and connect to the server

### Steps to reproduce the issue

1. $ owncloud --logdir /tmp/owncloud_logs --logflush
2. type server: ehubox.ehu.eus
3. read error
4. read log

### Logs

```
ownCloud 4.2.0.11670 f5a29b Libraries Qt 5.15.2, OpenSSL 3.0.2 15 Mar 2022 Using virtual files plugin: suffix ubuntu-6.2.0-31-generic ownCloud
23-09-02 11:59:26:104 [ debug default ]	[ OCC::Logger::setLogRules ]:	""
23-09-02 11:59:26:104 [ info gui.application ]:	################## "ownCloud" locale: "eu_ES" version: "ownCloud 4.2.0.11670 f5a29b Libraries Qt 5.15.2, OpenSSL 3.0.2 15 Mar 2022 Using virtual files plugin: suffix ubuntu-6.2.0-31-generic"
23-09-02 11:59:26:104 [ info gui.application ]:	Arguments: ("owncloud", "--logdir", "/tmp/owncloud_logs", "--logflush")
23-09-02 11:59:26:104 [ info gui.application ]:	Using "en" translation
23-09-02 11:59:26:105 [ critical gui.application ]:	Could not load qtkeychain translations
23-09-02 11:59:26:105 [ info gui.application ]:	Plugin search paths: ("/opt/ownCloud/ownCloud/lib/x86_64-linux-gnu/plugins", "/opt/ownCloud/qt-5.15.2/lib/x86_64-linux-gnu/qt5/plugins", "/opt/ownCloud/ownCloud/bin")
23-09-02 11:59:26:105 [ info gui.application ]:	VFS suffix plugin is available
23-09-02 11:59:26:105 [ debug default ]	[ OCC::Logger::setLogRules ]:	""
23-09-02 11:59:26:118 [ info gui.application ]:	VFS suffix plugin is available
23-09-02 11:59:26:118 [ info gui.socketapi ]:	server started, listening at  "/run/user/1000/ownCloud/socket"
23-09-02 11:59:26:118 [ info gui.folder.manager ]:	void OCC::FolderMan::setSyncEnabled(bool) true
23-09-02 11:59:26:184 [ info gui.application ]:	Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
23-09-02 11:59:26:185 [ info gui.folder.manager ]:	Setup folders from settings file
23-09-02 11:59:26:185 [ info sync.clientproxy ]:	Set proxy configuration to use system configuration
23-09-02 11:59:26:202 [ info gui.application ]:	No configured folders yet, starting setup wizard
23-09-02 11:59:26:205 [ debug setupwizard.controller ]	[ OCC::Wizard::SetupWizardController::changeStateTo ]:	Current wizard state: OCC::Wizard::SetupWizardState::ServerUrlState
23-09-02 11:59:26:218 [ info gui.folder.manager ]:	void OCC::FolderMan::setSyncEnabled(bool) false
23-09-02 11:59:32:431 [ debug setupwizard.controller ]	[ OCC::Wizard::SetupWizardController::SetupWizardController(OCC::SettingsDialog*)::<lambda ]:	next button clicked, current state OCC::Wizard::ServerUrlSetupWizardState(0x55a446b41f10)
23-09-02 11:59:32:431 [ info setupwizard.states.serverurl ]:	no URL scheme provided, prepending default URL scheme "https://"
23-09-02 11:59:32:570 [ critical wizard.resolveurl ]:	"Failed to resolve URL https://ehubox.ehu.eus, error: SSL handshake failed"
23-09-02 11:59:32:572 [ debug setupwizard.controller ]	[ OCC::Wizard::SetupWizardController::changeStateTo ]:	Current wizard state: OCC::Wizard::SetupWizardState::ServerUrlState
23-09-02 11:59:32:577 [ warning wizard.resolveurl ]:	"Could not detect compatible server at https://ehubox.ehu.eus"

```

### Client version number

```
ownCloud 4.2.0.11670 [f5a29b](https://github.com/owncloud/client/commit/f5a29bc3446734c565b106c1bdddc09ec03f76eb)
Libraries Qt 5.15.2, OpenSSL 3.0.2 15 Mar 2022
Using virtual files plugin: suffix
ubuntu-6.2.0-31-generic
```

### Desktop environment (Linux only)

Ubuntu 22.04.3 GNOME 42.9 Wayland

### Client package version and origin (Linux only)

```
#!/bin/sh grep 'Ubuntu 22.04' /etc/os-release || ( echo "This INSTALL.sh is for 'Ubuntu 22.04'. Press CTRL-C to abort, ENTER to continue"; read a ) apt-get update -y && apt-get install -y wget gnupg2 curl binutils apt-transport-https wget -nv https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_22.04/Release.key -O - | apt-key add - || exit 1 echo 'deb https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_22.04/ /' > /etc/apt/sources.list.d/owncloud.list apt-get update -q apt-get install -y owncloud-client
```

### Server information

n/a

**Comment by michaelstingl** [comment]
Maybe your 2nd cert causes problems:

![IMG_2330](https://github.com/owncloud/client/assets/214010/4d5fdca8-5108-4f7b-a655-c6be7ce3a086)

(see https://www.ssllabs.com/ssltest/analyze.html?d=ehubox.ehu.eus)

@fmoc any idea?

**Comment by fmoc** [comment]
It's likely not an SSL certificate problem, otherwise the dialog to accept invalid certificates would have been shown.

**Comment by fmoc** [comment]
HTTP logger had this to say:

```
Response: GET 0 (Error: SSL handshake failed: Error during SSL handshake: error:0A000438:SSL routines::tlsv1 alert internal error,77ms) https://ehubox.ehu.eu/status.php Header: { } Data: []"

**Comment by fmoc** [comment]
Ubuntu 22.04 ships two broken OpenSSL versions, 1.1.1n and 3.0.2. See https://github.com/openssl/openssl/issues/19518 for more information.

If you look at the issue, it's the server rejecting the client with this error message "internal error". At this point, no fix is available which Ubuntu or we could deploy.

You may want to extend TLS version support a bit to work around the problem.

**Comment by fmoc** [comment]
Also reproducible with the current AppImages which ship OpenSSL 3.1.2.

**Comment by fmoc** [comment]
Comment from the OpenSSL issue:

> So basically the server is buggy. There is no bug in OpenSSL (at least on the client that is).

I'm not so sure that is the case, I suspect there is no bug but a compatibility/negotiation problem. In any case, we cannot do anything at the moment.

**Comment by eagirre** [comment]
Apparently my university IT service fixed the compatibility problem (won't tell me anything about it though). It's working now. Thanks for the help!
