### ISSUE TITLE
Client launched my launchd restarts immediately after `kill $pid`

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11178]
Our pkg, kills any running ownCloud process : https://github.com/owncloud/client/blob/master/admin/osx/pre_install.sh.cmake#L14
before an update.
Launchd however restarts the process when it was started at login, which can then lead to a crash as the binaries in the install dir might be a mix between to builds.

If the client is closed manually everything works as expected.

Os: mac sonoma

Steps to reproduce:
Login with the client in autostart.
Get the pid.
kill pid

TODO:
call the original application with -q
wait for x seconds.
Kill the client with a signal that prevents the restart (or ask launchd to terminate it?)

**Comment by erikjv** [comment]
Use launchd to stop/start the process:

```
launchctl stop com.owncloud.desktopclient 
launchctl start com.owncloud.desktopclient
```

If either fails, then launchd doesn't know about the process, which means it's not enabled for auto-start.

**Comment by michaelstingl** [comment]
> `launchctl start com.owncloud.desktopclient`

works 👍 

> `launchctl stop com.owncloud.desktopclient`

Quits the desktop sync client 👍 , but then it immediately re-starts again after a few seconds 👎 ⚠️

**Comment by michaelstingl** [comment]
@erikjv found, my `~/Library/LaunchAgents/com.owncloud.desktopclient.plist` was corrupted. We fixed it manually:

![CleanShot 2023-09-06 at 18 02 57@2x](https://github.com/owncloud/client/assets/214010/8f30aff7-9fb5-4a87-85a7-606c600ceb4c)

**Comment by TheOneRing** [comment]
While we should still try to quit the client more gracefully I guess we can close this issue?
I assume your com.owncloud.desktopclient.plist dates back to when we had the restart issue?

**Comment by michaelstingl** [comment]
> I assume your `com.owncloud.desktopclient.plist` dates back to when we had the restart issue?

Yes, could be the case 🤷
