### ISSUE TITLE
[QA] Default download directory is already being used 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11182]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Default download directory is already being used 

ownCloud 5.0.0.12046-daily20230906
mac

### Steps to reproduce the issue

1. Add a new account (leave the Advanced configuration as default)

### Screenshots

<img width="956" alt="Screenshot 2023-09-06 at 09 24 58" src="https://github.com/owncloud/client/assets/49001702/91f4eb25-6a25-411f-8da1-045b7c474433">

### Expected behavior

New account has been created with a default local download directory

### Actual behavior

There is no such folder in my system but the client shows it as already used. It seems it evaluates only /Users/hana/ and not the entire path

**Comment by TheOneRing** [comment]
Sounds like fallout of https://github.com/owncloud/client/pull/11117 @erikjv

**Comment by erikjv** [comment]
I cannot reproduce this with a build of the 5 branch.

**Comment by fmoc** [comment]
Cannot reproduce either on Ubuntu 22.04 with the AppImage using the same daily build from 2023/09/06.

**Comment by TheOneRing** [comment]
The problem was a stale sync db in /Users/hana
