### ISSUE TITLE
[macOS] Sonoma beta WARNING: Secure coding is not enabled for restorable state!

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#11191]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When I open the 5.0.0-preview builds from macOS Sonoma Terminal it prints this warning:

```
% /Applications/owncloud.app/Contents/MacOS/owncloud          
2023-09-07 12:37:39.625 owncloud[3205:176246] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.
```

(Everything seems to work normal)

### Expected behavior

I shouldn't see warnings like this

### Steps to reproduce the issue

1. open `Terminal.app`
2. execute `/Applications/owncloud.app/Contents/MacOS/owncloud`

### Client version number

```
% /Applications/owncloud.app/Contents/MacOS/owncloud --version
ownCloud ownCloud 5.0.0.12034-daily20230905
https://github.com/owncloud/client/commit/f53f7c8c984d0d4ea8c09bcce1189fc302fb2ccc
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: suffix
macos-23.0.0
```

**Comment by michaelstingl** [comment]
I can confirm it's fixed in the `ownCloud-5.0.0.12187-rc.2-arm64.pkg` ✅

**Comment by oladapo-joseph** [comment]
how can I correct this error, running into the same error, 
using python tkinter on M1 MacOS Sonoma

**Comment by michaelstingl** [comment]
Probably tkinter needs to fix in their code. Here’s the example from ownCloud:
- https://github.com/owncloud/client/commit/4041ff7ebe17b25a242b1d1ff410743f97133bb1
