### ISSUE TITLE
Prevent: Same default sync folder for multiple accounts

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11204]
Steps to reproduce:
- Add an ocis account
- Add a second ocis account, use advanced settings and use the default sync root form the first account

Both accounts use the same syncroot and differentiate the directory names _inside_ that syncroot:
- `root/Personal`
- `root/Personal (1)`

Expectations:
The client prevents the user from using the same syncroot directory, instead offering a different syncroot:
- `root/Personal`
- `root (1)/Personal`

**Comment by TheOneRing** [comment]
We could use xattr and ntfs streams to "claim" a folder, if neither is supported for the folder we ignore it.
That way we should always be able to prevent multiple accounts from using the same default sync root.

**Comment by Salipa-Gurung** [comment]
Tested on : 
ownCloud 6.0.0.13062-daily20240108 b46134
Libraries Qt 6.6.0, OpenSSL 3.1.4 24 Oct 2023
Using virtual files plugin: wincfapi
OS: windows-10.0.19045 (build arch: x86_64, CPU arch: x86_64)
QPA: windows

Server:
Infinite Scale 4.0.5 Community and ownCloud 10.13.4 (stable)

Adding account for brian after admin's account was added | Using default syncroot from the first account
-----|-----
| ![Screenshot from 2024-01-08 12-05-05](https://github.com/owncloud/client/assets/53458341/8f199a9e-bb99-4a3e-8d1b-75846bbd3217) | ![Screenshot from 2024-01-08 12-07-35](https://github.com/owncloud/client/assets/53458341/7d5c2cea-e3e0-46cd-994c-112119442dad) |
Client provides different syncroot :heavy_check_mark: | Client prevents user from using same syncroot directory :heavy_check_mark: 

`Finish` button remains clickable when error message is being displayed. :grey_question: 

cc: @erikjv
