### ISSUE TITLE
[QA] About dialog blocks the update 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11208]
Blocked by:
 - https://github.com/owncloud/client/issues/11214
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

ownCloud 5.0.0.12103-daily20230912
mac

### Steps to reproduce the issue

Make sure there is an update available on the online updater

1. Start the app
2. Show the app
3. Open About dialog
4. Click Install Update
5. Click Install and Relaunch

### Screenshots

No screenshot

### Expected behavior

Update successfull

### Actual behavior

Update doesn't progress. 
The update dialog is closed, About dialog remains open.
Quitting the app is needed to continue the update

**Comment by HanaGemela** [comment]
Screenshots here (the Log out dialog behaves the same)

<img width="800" alt="Screenshot 2023-09-18 at 10 32 43" src="https://github.com/owncloud/client/assets/49001702/69b15cdd-cfcd-4851-bf9c-e9fb27a5968d">


<img width="804" alt="Screenshot 2023-09-18 at 10 33 12" src="https://github.com/owncloud/client/assets/49001702/6b0e6285-99cc-4052-9d7a-6ffcbaab5664">

**Comment by michaelstingl** [comment]
@HanaGemela did Sparkle update fix it?
