### ISSUE TITLE
Mac: Update sparkle 

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11214]
The latest sparkle version is https://github.com/sparkle-project/Sparkle/releases/tag/2.5.0
While we still ship 1.24 https://invent.kde.org/packaging/craft-blueprints-kde/-/blob/master/libs/_mac/sparkle/sparkle.py
Related: 
- https://github.com/owncloud/client/issues/11208

**Comment by TheOneRing** [comment]
Fixed in: https://invent.kde.org/packaging/craft-blueprints-kde/-/commit/ae1d547e6a13bc6ef3a6f6b9985c8febcf17e127

**Comment by TheOneRing** [comment]
Will be tested in 6.0 auto update test.

**Comment by HanaGemela** [comment]
Update from 5.1.2 to ownCloud 6.0.0.12640-daily20231117 successful

**Comment by TheOneRing** [comment]
Updates fail due to: https://github.com/owncloud/client/issues/11388

**Comment by TheOneRing** [comment]
unblocked: needs testing

**Comment by fmoc** [comment]
For testing instructions, see #11388.

**Comment by HanaGemela** [comment]
Will be tested in https://github.com/owncloud/client/issues/11388
