### ISSUE TITLE
2.11: Folder tree in account settings is not unfoldable

### ISSUE THREAD

**Issue by buhtz** [owncloud/client#11212]
I'm aware that version 2.11 is quit old. And I'm also aware that the bug I describe seems to be fixed in the latest version.

In context of Debian 12/stable package https://tracker.debian.org/pkg/owncloud-client I would like to find out when and how this was fixed. I wasn't able to find the related Issue or Commit for that. Hope you can help so the Debian package can get a patch. The Debian bug ticket is: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1037133

The problem is that the folders do not unfold except the first level. See this screen recording for explanation.
![Peek 2023-09-18 15-12](https://github.com/owncloud/client/assets/11861496/1e4d3147-30b6-4a6b-b441-37462379a806)

Can you name how and when this was fixed?

**Comment by TheOneRing** [comment]
Sounds like it was fixed in 2.11.1 https://github.com/owncloud/client/blob/master/CHANGELOG.md#details-8

**Comment by buhtz** [comment]
Thanks a lot.

**Comment by TheOneRing** [comment]
In general I'd however recommend to use a newer client as we don't provide lts releases and there might have been more serious fixes than the selective sync tree.

**Comment by buhtz** [comment]
> In general I'd however recommend to use a newer client as we don't provide lts releases and there might have been more serious fixes than the selective sync tree.

In Debian 12 (the current latest stable) 2.11 is the version. It is Debian policy not to do updates inside a release. The do patching if possible, e.g. bugs like we discuss here. There is also a backports repository where a newer owncloud-client might become available in the future.

Debian 13 will be release round about in the year 2025. Until then there are some 2.11 users out there.
