### ISSUE TITLE
Fedora packages install i686 deps instead of x64

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11223]
![image](https://github.com/owncloud/client/assets/200626/d5bf542d-d44b-48ae-947c-1528603038f7)

**Comment by jnweiger** [comment]
Dependencies of testpilotcloud-client look like this:
```
rpm -q -requires testpilotcloud-client
libGL.so.1
libGLX.so.0
libOpenGL.so.0
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
```

With most other packages, I see that there is a `(64bit)` suffix, like e,g,:
```
libc.so.6(GLIBC_2.7)(64bit)
libcrypt.so.2()(64bit)
libcrypt.so.2(XCRYPT_2.0)(64bit)
libpam.so.0()(64bit)
libpam.so.0(LIBPAM_1.0)(64bit)
libtinfo.so.6()(64bit)
libutempter.so.0()(64bit)
```

The absence of this suffix probably means, pull in both, 32bit and 64bit?

**Comment by fmoc** [comment]
Should be fixed in the next set of dailies. See https://gitea.owncloud.services/client/build/commit/e40b6d0afd1d068430246e96a4781c34bc9b7540.

**Comment by fmoc** [comment]
Confirmed fixed in the latest daily build.

**Comment by HanaGemela** [comment]
```
rpm -q -requires owncloud-client_5.1.0.12323-daily20231011.rpm
libGL.so.1()(64bit)
libGLX.so.0()(64bit)
libOpenGL.so.0()(64bit)
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
```

✅
