### ISSUE TITLE
Multiple sync of the same remote folder (scenario: Sync to HD and USB stick)

### ISSUE THREAD

**Issue by entfernt** [owncloud/client#1122]
I tried to sync on folder in the cloud to two folders on my local pc 
one on the hardrive and on on an usb flash disk to go.
atm it prevents me from setting up this scenario with the message
that the cloud folder is already in sync ...

maybe a warning instead of  a block..

thanks

ps: more compatibillity to make the client portable would fit better in the whole onecloud thing..

**Comment by SamuAlfageme** [comment]
Think this is done after https://github.com/owncloud/client/pull/6032 

@ogoffart close here?
