### ISSUE TITLE
Reconnect does not trigger a sync

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11229]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

ownCloud 5.0.0.12187-rc.2
mac

### Steps to reproduce the issue

1. Rename a file when offline
2. Go online

### Screenshots

<img width="798" alt="Screenshot 2023-09-26 at 20 48 24" src="https://github.com/owncloud/client/assets/49001702/5ff0b863-5172-4da1-9cf1-7ea9fa5541ad">

### Expected behavior

Rename synced once the network becomes available

### Actual behavior

I've been waiting 20 minutes and still no sync

**Comment by TheOneRing** [comment]
Logs please

**Comment by TheOneRing** [comment]
Also what kind of offline do you mean, kill the server? disconnect the computer? log out?

**Comment by HanaGemela** [comment]
> Also what kind of offline do you mean, kill the server? disconnect the computer? log out?

Turn off wifi

**Comment by HanaGemela** [comment]
> Also what kind of offline do you mean, kill the server? disconnect the computer? log out?

https://cloud.owncloud.com/f/6092617

New file.txt renamed to New file.txt1

23-09-27 20:09:15:170 [ debug sync.localdiscoverytracker ]	[ OCC::LocalDiscoveryTracker::startSyncPartialDiscovery ]:	partial discovery with paths:  QList("New file.txt", "New file1.txt")

**Comment by HanaGemela** [comment]
Passed in ownCloud 5.0.0.12227-daily20230929, mac
