### ISSUE TITLE
Add sync folder tries to use existing invalid local location

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11231]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

ownCloud 5.0.0.12187-rc.2
oc10

### Steps to reproduce the issue

1. Add an oc10 account
2. Click Add folder 
3. Click Next

### Screenshots

<img width="799" alt="Screenshot 2023-09-27 at 08 16 17" src="https://github.com/owncloud/client/assets/49001702/88c0c782-dace-469c-8be9-f4c11847896b">

### Expected behavior

Default folder name is unique and can be used straightaway 

### Actual behavior

User has to change the folder name to be able to use it

**Comment by TheOneRing** [comment]
Duplicate of: https://github.com/owncloud/client/issues/11204

**Comment by HanaGemela** [comment]
ownCloud 5.0.0.12227-daily20230929, mac:

When adding a new account, the number in brackets gets increased e.g. /Users/hana/ownCloud - demo@demo.owncloud.com (**41**)

When adding a new folder, we get another pair of brackets now e.g. /Users/hana/ownCloud - demo@demo.owncloud.com **(41) (2)**

<img width="803" alt="Screenshot 2023-09-29 at 09 15 42" src="https://github.com/owncloud/client/assets/49001702/d1c08aac-6f7a-439e-8ea4-9769fa58ea63">

**Comment by HanaGemela** [comment]
Works as expected
