### ISSUE TITLE
Deleting virtual file/folder (online only) does not show warning message

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/client#11234]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

While deleting a virtual file or a virtual folder (online only/dehydrated), it gets deleted both in desktop client and server without warning message.

### Expected behavior

Warning message was expected 

### Steps to reproduce the issue

VFS must be enabled.
1. Add a file or a folder from client 
2. Make the file or folder online only ( `Free up space` from context menu )
3. Delete the virtual file or virtual folder from the client

### Client version number

ownCloud 5.0.0.12187-rc.2 5a9119
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: wincfapi
OS: windows-10.0.19045
QPA: windows

### Server information

ownCloud Web UI 7.0.0
Infinite Scale 3.0.0 Community

**Comment by TheOneRing** [comment]
Virtual files are "placeholder" for  actual files and should in this regard behave like the original file.
If you delete the original file its gone too?

**Comment by TheOneRing** [comment]
As far as I know we never displayed a dilog, please reopen if I'm wrong.

**Comment by Salipa-Gurung** [comment]
In windows-10.0.19045,
virtual files and virtual folders gets deleted from client as well as from server.

In ubuntu-6.2.0-33-generic,
when virtual files are deleted, it gets added again, but virtual folder get deleted in both client and server.

**Comment by TheOneRing** [comment]
Suffix placeholders are broken by design.

Proper placeholders should behave like the actual file.

**Comment by michaelstingl** [comment]
> Warning message was expected

We could compare with other solutions. I think Dropbox, iCloud etc show warnings. Needs research…

**Comment by TheOneRing** [comment]
.owncloud files are deprecated and will be removed in 7.0
