### ISSUE TITLE
[QA] Add space button gets renamed to Add folder when logged out 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11230]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

ownCloud 5.0.0.12187-rc.2
mac

### Steps to reproduce the issue

1. Add an ocis account
2. Log in -> check the button at bottom left, it's called Add space
3. Log out -> it's called Add folder

### Screenshots

<img width="802" alt="Screenshot 2023-09-27 at 08 04 37" src="https://github.com/owncloud/client/assets/49001702/3de22d0b-90b1-49fc-b011-33883defe613">

### Expected behavior

The button doesn’t change it's name. It just gets greyed out

### Actual behavior

Button changes its name when account is logged out

**Comment by erikjv** [comment]
"Blocked": wait for the 5.0 release, so this can be merged for 5.1

**Comment by TheOneRing** [comment]
> @TheOneRing What should be changed? And for which branch?

See pr. I'd say 5.1.

**Comment by fmoc** [comment]
Resolved in PR #11256.

**Comment by HanaGemela** [comment]
Fixed in ownCloud 5.1.0.12421-daily20231018
