### ISSUE TITLE
No `Create and copy public link to clipboard` in the righ-click menu with oCIS server

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11242]
### Describe the bug

No `Create and copy public link to clipboard` context menu in desktop client with oCIS server

### Expected behavior

to see `Select Create and copy public link to clipboard` menu item

### Steps to reproduce the issue

1. Add account to desktop client
2. Right click on any file/folder
3. Select `ownCloud`
4. No `Create and copy public link to clipboard` :x: :question:

### Screenshots

![Screenshot from 2023-09-28 17-32-12](https://github.com/owncloud/client/assets/52366632/2e58e7f4-54c5-45ad-868e-5e6806523bff)

### Logs

[owncloud.log](https://github.com/owncloud/client/files/12749234/owncloud.log)

### Client version number

```
ownCloud 5.0.0.12187-rc.2 5a9119
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: suffix
OS: debian-6.1.0-12-amd64
QPA: xcb
```

### Desktop environment (Linux only)

Ubuntu 22.04 and Debian12

### Installation path (Windows only)

Win10

### Server information

 `Infinite Scale 4.0.1 Community`

**Comment by TheOneRing** [comment]
The functionality was never really supported by ocis and was thus removed from the context menu. https://github.com/owncloud/client/pull/11079

**Comment by saw-jan** [comment]
Ohh, then have to update the test cases
