### ISSUE TITLE
[linux] Virtual files inside a folder are not downloaded after disabling VFS support

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11240]
### Describe the bug

After disabling VFS support files inside the folder are not downloaded and `.owncloud` files of downloaded files are also not removed.

### Expected behavior

All files are downloaded and synced to the sync folder

### Steps to reproduce the issue

1. Add some files/folders-with-files to the server
2. Add the account to the desktop client with VFS enabled
3. Disable the VFS support
4. Files on root level gets downloaded but respective `.owncloued` files are still there :x:
5. Files inside some folders don't get downloaded :x:

### Screenshots

![Screenshot from 2023-09-28 11-56-48](https://github.com/owncloud/client/assets/52366632/1d00fe4d-b80b-4370-a8d2-829ba67e1d32) | ![Screenshot from 2023-09-28 11-58-01](https://github.com/owncloud/client/assets/52366632/8cd5bb77-aa39-444a-83e9-d35ff0062bbd)
--|--
VFS ON | VFS OFF - root level files are downloaded but `.owncloud` files still remain :x:

![Screenshot from 2023-09-28 11-58-07](https://github.com/owncloud/client/assets/52366632/0baf2a5b-8ff7-480b-98dd-acb32ae2d076) | <a>
--|--
Files inside a folder are not downloaded :x: |

### Client version number

```
owncloudcmd ownCloud 5.0.0.12187-rc.2
https://github.com/owncloud/client/commit/5a9119bdfd0794421f9ac7888f05b3ab16df4e59
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: suffix
OS: ubuntu-6.2.0-33-generic
```

### Desktop environment (Linux only)

Ubuntu (gnome with nautilus)

### Client log
[ownCloud.log](https://github.com/owncloud/client/files/12747694/ownCloud.log)

**Comment by TheOneRing** [comment]
@saw-jan can you try to run the app image with https://github.com/TheAssassin/AppImageLauncher .
It will ask you to integrate the appimage, click yes and try again.

The reason will be that we don't register the app image as a responsible for the mime type.

**Comment by TheOneRing** [comment]
Are the two files actual placeholders, empty 1 byte files, or where they modified with a text editor as the client did not download the actual file when double clicking them.

**Comment by saw-jan** [comment]
> Are the two files actual placeholders, empty 1 byte files, or where they modified with a text editor as the client did not download the actual file when double clicking them.

those files were synced from server to the client with vfs enabled and after disabling vfs they should be converted to actual file, right?

**Comment by TheOneRing** [comment]
Only if they are not modified, if placeholder file is modified its detected as some random file with a stupid file name and ignored.
Your logs would tell you.

**Comment by saw-jan** [comment]
> Only if they are not modified, if placeholder file is modified its detected as some random file with a stupid file name and ignored. Your logs would tell you.

I just synced with vfs on and then disabled vfs. so nothing touched in the sync folder.
I will report the logs as well.

**Comment by saw-jan** [comment]
I have attached the log in the description. Maybe something can be found there

**Comment by TheOneRing** [comment]
I can see the file "short.txt.owncloud" in the logs with the same behaviour as INSTALL.sh.owncloud.
And in https://github.com/owncloud/client/issues/11239 I can see a screenshot that that file was opened in a text editor.

**Comment by saw-jan** [comment]
> And in https://github.com/owncloud/client/issues/11239 I can see a screenshot that that file was opened in a text editor.

yeah, for #11239, only `short.txt.owncloud` is opened in the editor. But for this, I cleaned up everything and tried it fresh

**Comment by TheOneRing** [comment]
Did the files still exist on the server, if you manage to have .owncloud files on your system that don't have an actual file on the server we would see something like this too.

**Comment by saw-jan** [comment]
The server has all the files. nothing got deleted

**Comment by TheOneRing** [comment]
```
23-09-28 14:51:11:369 [ info sync.discovery ]:	Processing "f1/INSTALL.sh.owncloud" | valid: true/true/db | mtime: 1695645471/1695645471/0 | size: 499/1/0 | etag: "73c7dbc7acff9d85175d3bb3dcfd189e"//"" | checksum: "SHA1:c923cdd0b22dace6b0342b45134186fc45ddb3c1"//"" | perm: "WDNVR"//"" | fileid: "c80f2074-a213-43fd-a607-1a2ab1112e3a$27491a5b-e357-452f-bf4b-d03b51b22eae!eb168cc6-ea33-4997-9fab-82c1b27d1b7b"//"" | inode: 1053049/1053049/ | type: CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeFile
23-09-28 14:51:11:369 [ info sync.discovery ]:	Processing "f1/example.sh.owncloud" | valid: true/true/db | mtime: 1695645443/1695645443/0 | size: 729/1/0 | etag: "9da29dc55e4c5851709a2886b1de3c94"//"" | checksum: "SHA1:8645746e32eda723bc16d0dcbac4117040101f72"//"" | perm: "WDNVR"//"" | fileid: "c80f2074-a213-43fd-a607-1a2ab1112e3a$27491a5b-e357-452f-bf4b-d03b51b22eae!2bd6da9f-9e12-40ed-a960-9efb06294799"//"" | inode: 1053065/1053065/ | type: CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeVirtualFile/CSyncEnums::ItemTypeFile
```
For bot files it says it has no mtime on the server and no file size, it looks more like you copied a example.sh.owncloud file to the sync root.

**Comment by saw-jan** [comment]
hmm, that's not what I did though. Let me do it again in some other VMs

**Comment by saw-jan** [comment]
> hmm, that's not what I did though. Let me do it again in some other VMs

Still same with Fedora38. But also now noticed that re-enabling VFS deletes all the `.owncloud` files (but files are fine in the server)

**Comment by saw-jan** [comment]
Works for Windows - all vfs files are downloaded

**Comment by TheOneRing** [comment]
This is a linux issue, what happens on linux?

**Comment by saw-jan** [comment]
Tested with `ownCloud 5.1.1.12577-rc.1 a98b47` on `Ubuntu 22.04`
All files are download after disabling the VFS :heavy_check_mark:

**Comment by TheOneRing** [comment]
great, if I just had understood the impact of your finding here earlier 🙈
