### ISSUE TITLE
Deprecate legacy `--confdir` command-line  argument

### ISSUE THREAD

**Issue by erikjv** [owncloud/client#11246]
This command-line argument causes problems with the language setup, see issue #11142 .

**Comment by michaelstingl** [comment]
Needed for roaming profiles?
- https://github.com/owncloud/client/issues/684#issuecomment-247280687

**Comment by erikjv** [comment]
> Needed for roaming profiles?
> 
> * [Windows Roaming Profiles: Make it easier to allow roamed client configuration #684 (comment)](https://github.com/owncloud/client/issues/684#issuecomment-247280687)

@TheOneRing is that still relevant? IIRC we now always use a roaming profile?

**Comment by TheOneRing** [comment]
We use roaming profiles since ages.
