### ISSUE TITLE
The error message in "Add sync folder" dialog is unreadable with dark theme

### ISSUE THREAD

**Issue by erikjv** [owncloud/client#11243]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Click the "Add sync folder" button for an account, and enter an existing folder. The error is (probably) in white text on a white background:

<img width="912" alt="Screenshot 2023-09-28 at 13 10 43" src="https://github.com/owncloud/client/assets/151956/17568852-11d9-4232-96cf-ae0e83ca268d">

The label in `folderwizardsourcepage.ui` uses a custom palette, which is probably the cause.

### Expected behavior

The error message should at least be readable.

### Client version number

The 5 branch in git, sha1: `bcab27aefda27a33af7bcb70e229ecff99b95363`

**Comment by TheOneRing** [comment]
We should remove all questionable uses of QPalette

**Comment by erikjv** [comment]
There is now also a dark theme on Windows, so check that too.

**Comment by erikjv** [comment]
The dark theme on Windows shows the same problem. So either can be used for testing.
