### ISSUE TITLE
The `--language` option does not work

### ISSUE THREAD

**Issue by erikjv** [owncloud/client#11245]
The value is read from the command-line options, but it is never used.

The question is if we still need it. It was there before there was the possibility to choose a different language in the UI. So on top of that, do we need the command-line option to override both the UI-configured language and the system language?

See also issue #11142 .

**Comment by erikjv** [comment]
The value should have been passed to the `Application` class when it is constructed, and stored in the `_userEnforcedLanguage` member field (which is currently never set).

**Comment by fmoc** [comment]
I use it as part of my development cycle in order to start the client with different languages. I think this should be kept.

**Comment by HanaGemela** [comment]
Removed in ownCloud 6.0.0.12402-daily20231016 ✅

**Comment by fmoc** [comment]
We decided on removing it as there are other means of changing the language for testing.
