### ISSUE TITLE
With VFS enabled, activity of forbidden file types does not appear in Not Synced tab 

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/client#11247]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

With `VFS enabled`, adding a forbidden file types (file ending with '.owncloud') in the client, ignores the file but the ignored activity is shown in `Sync Protocol` tab with ignored blue 'i' icon.

### Expected behavior

1. File should be ignored and should not be synced to the server
2. Ignored activity should appear in 'Not Synced' tab of Activity tab.

### Steps to reproduce the issue

1. Turn VFS on
2. Add a file ending with '.owncloud' in the desktop client

### Screenshots

![Screenshot from 2023-09-29 09-44-01](https://github.com/owncloud/client/assets/53458341/4009faa0-351e-467b-b1b6-c16c3f075755)

### Client version number

ownCloud 5.0.0.12187-rc.2 [5a9119](https://github.com/owncloud/client/commit/5a9119bdfd0794421f9ac7888f05b3ab16df4e59)
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: suffix
OS: ubuntu-6.2.0-33-generic
QPA: xcb

### Server information

 ownCloud Web UI 7.0.0 
Infinite Scale 3.0.0 Community

**Comment by TheOneRing** [comment]
Duplicate of: https://github.com/owncloud/client/issues/11248
