### ISSUE TITLE
[QA] [gui-tests] Squish test hardfailure while sorting folders

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/client#11255]
### Describe the QA issue

GUI test fails while sorting folder list by size.

Example CI builds:
https://drone.owncloud.com/owncloud/client/16696/2/15
https://drone.owncloud.com/owncloud/client/16699/3/15
https://drone.owncloud.com/owncloud/client/16700/3/15
https://drone.owncloud.com/owncloud/client/16701/3/15
https://drone.owncloud.com/owncloud/client/16702/3/15
https://drone.owncloud.com/owncloud/client/16703/3/15

### Screenshots

![Screenshot from 2023-10-02 09-56-37](https://github.com/owncloud/client/assets/53458341/7d24fc90-df98-4d95-b3ec-316a4b274c77)

**Comment by Salipa-Gurung** [comment]
Previously, size of folders were shown and tests for sorting folders according to their size worked.
![Screenshot from 2023-10-02 13-04-38](https://github.com/owncloud/client/assets/53458341/0b9208cb-6360-4768-a454-15ad2bb599c0)


After, https://github.com/owncloud/client/pull/11237 size of all folders are 0 B.
![Screenshot from 2023-10-02 13-09-03](https://github.com/owncloud/client/assets/53458341/b807d20f-72a6-4afc-8cc4-5c6f6c905594)

cc: @TheOneRing

**Comment by fmoc** [comment]
This is just a trailing/duplicate slashes issue. I'm tracing the origin currently, but we need more string sanitation or assertions. There are at least 3 locations in which duplicate slashes cause problems, one even triggers an assertion, in the other cases, a string filter doesn't work.

**Comment by saw-jan** [comment]
CI says the tests are passing. :+1: 
https://drone.owncloud.com/owncloud/client/16720
