### ISSUE TITLE
Desktop client login via keycloak fails

### ISSUE THREAD

**Issue by mrjumpingjack** [owncloud/client#11254]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

In the login process in the desktop client using v5.0.0-rc.3 I'm not redirected to the keycloak login but to the default owncloud login. If I login using this I'm logged-in in the webbrowser but the desktop client is not.

If I use the v5.0.0-beta.1 everything works fine.

### Expected behavior

After providing the server address and clicking "Open browser" I expect to be redirected to the login mask of keycloak.

### Steps to reproduce the issue

1. Follow the install process of the desktop client
2. Reboot
3. Click "Add account"
4. Provide Server address to the dialog
5. Click "open browser"
6. Be redirected to the login mask of owncloud (in my case https://cloud.[domain].cc/login) and not the keycloak one.

### Client version number

Desktop client v5.0.0-rc.3
Qt 6.4.3

### Installation path (Windows only)

C:\Program Files\ownCloud

### Server information

owncloudserver 10.12.2 on docker
PHP 7.4.3
mariadb 10.6

**Comment by TheOneRing** [comment]
In v5.0.0-beta.1 we had a bug where we followed redirects, we no longer do so, this aligns with the previous releases of ownCloud.
I'd recommend to enable http logs, https://doc.owncloud.com/desktop/next/appendices/troubleshooting.html#log-http-requests-and-responses . And look for a 302 where none is expected.
