### ISSUE TITLE
Auto updates push updates to unsupported platforms(macOS 10.13 and 10.14)

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#11269]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Running an older iMac with 10.14 and client 4.2
Got an update message to 5.0
I updated which worked flawless but when starting it complained that it cant as you minimum need 10.15
I was not able to revert just by (re)installing 4.2, it still complained about the minimal release necessary 10.15.
I needed to uninstall the client (using app-zapper) and was then able to reinstall 4.2 and get it up and running.

@michaelstingl @TheOneRing @fmoc 

### Proposed solution

What is needed is:
- do not propose and update if the requirements are not met
- do not install the update if the requirements are not met
- find a procedure that ensures reinstalling a former release is possible

**Comment by TheOneRing** [comment]
Thank you for reporting.
Well try to not push push out updates to unsupported platforms in the future.
We will also investigate whether we can prevent the pkg from installing on unsupported platforms.

For uninstalling: The pkg never performs a downgrade, so in order to successful downgrade you first need to uninstall (move the app to the trash bin) and reinstall.

# Note to downgrades: 
Under normal circumstances donw grades are not supported. They only work in cases like this where the client wasn't actually executed.

**Comment by mmattel** [comment]
> Well try to not push push out updates to unsupported platforms in the future.

Pls also add that you try to prevent or at least highlight not to install a client if the prerequisites are unsupported. One can download the package manually and then tries to install not knowing about the restriction...

**Comment by fmoc** [comment]
> Pls also add that you try to prevent or at least highlight not to install a client if the prerequisites are unsupported.

I don't think that the installers are capable of that. We might be able to provide this information in some installer page, maybe.

Regarding the updater, I'd like to add some UI feature that explains that the platform is too old now instead of just saying "no update available".

**Comment by TheOneRing** [comment]
We forgot to raise the requirements in the sparkle metadata.

**Comment by TheOneRing** [comment]
> > We forgot to raise the requirements in the sparkle metadata.
> 
> Which means? Is there a fix that can be referenced?

Internal ansible repo

**Comment by fmoc** [comment]
If you need more information, please check the examples in the update server docs. There's a setting to configure the minimum macOS version for the Sparkle updater to read.

**Comment by sbgraphic** [comment]
I had the same issue on Mac os 10.13 with auto update… I had to trash some pref / resinstall release v4.2.0 manually... fortunately without too much trouble, Best to all.

**Comment by workflowsguy** [comment]
Installation on unsupported macOS versions can easily be prevented by including the key/value pair

```
<key>LSMinimumSystemVersion</key>
<string>10.15</string>
```

in the app's `Info.plist`file.

**Comment by fmoc** [comment]
CC @TheOneRing
