### ISSUE TITLE
[macOS] Inconsistent systray menu behaviour

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11264]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

User can't quit when About dialog (or please authenticate dialog) is open and the app is in the background 

ownCloud 5.0.0.12278, mac

### Steps to reproduce the issue

1. Start the app
2. Open About dialog
3. Open another app, e.g. web browser
4. Quit the client from the system tray

### Screenshots

No screenshot

### Expected behavior

Quit option is not available - the same way as when the user click "Show owncloud". Then the option to Quit disappears 

### Actual behavior

Nothing happens

**Comment by HanaGemela** [comment]
@michaelstingl  the entire system tray menu has different availability when the client is in the background. Please confirm what the expected behaviour is

**Comment by TheOneRing** [comment]
If I remember it correctly you opened an issue like that before.
And we came to the conclusion its a Qt bug?
When ownCloud with the modal dialog is active, the systray is correctly disabled, if the app is in the background its active (it should not be).

**Comment by TheOneRing** [comment]
Fixed in 6.0
