### ISSUE TITLE
owncloudcmd --unsyncedfolders not working

### ISSUE THREAD

**Issue by risacher** [owncloud/client#11261]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Summary: when using owncloudcmd to sync on a headless server, at least one of the unwanted directories listed in "--unsyncedfolders unsynced.txt" is being synced. 

The following command is invoked from a cron job:

`/usr/bin/owncloudcmd --non-interactive --unsyncedfolders /home/USER/.owncloud/unsynced.txt /home/USER/ownCloud 'https://USER:PASSWORD@FQDN.org/owncloud/'`

The file 'unsynced.txt' contains the line 'games', but when the command is run, the 'games' directory is synced anyway.

For example, after deleting the file 'games/TEST_UNSYNC.txt', the output includes: 
`23-10-04 16:41:21:073 [ info sync.discovery ]:	Discovered "games/TEST_UNSYNC.txt" SyncInstruction(CSYNC_INSTRUCTION_REMOVE) OCC::SyncFileItem::Up CSyncEnums::ItemTypeFile
23-10-04 16:41:32:743 [ info sync.propagator ]:	Starting SyncInstruction(CSYNC_INSTRUCTION_REMOVE) propagation of "games/TEST_UNSYNC.txt" by OCC::PropagateRemoteDelete(0x559c2ca8e240)`

I'm not sure if it's relevant, but the selectivesync table in .sync_journal.db includes entries for the _other_ directories listed in unsynced.txt, but not the one I recently added: 

```
$ sqlite3 ownCloud/.sync_journal.db 'select * from selectivesync;'
-- Loading resources from /home/magnus/.sqliterc
2015trip/|1
Photos/|1
photos/|1
video/|1
Video/|1
Calibre\ Library/|1
Calibre Library/|1
```

### Expected behavior

No directories listed in a file passed to --unsyncedfolders should be synced.

### Steps to reproduce the issue

See bug description.

### Client version number

owncloudcmd ownCloud 4.2.0.11670
https://github.com/owncloud/client/commit/f5a29bc3446734c565b106c1bdddc09ec03f76eb
Libraries Qt 5.15.2, OpenSSL 1.1.1f  31 Mar 2020
Using virtual files plugin: suffix
ubuntu-5.15.0-1047-aws

### Desktop environment (Linux only)

ubuntu-5.15.0-1047-aws

### Server information

ownCloud 10.13.1 (stable)

Installed via docker-compose, image: owncloud/server:latest

```
      - OWNCLOUD_SUB_URL=/owncloud
      - OWNCLOUD_APPS_INSTALL=files_primary_s3
      - OWNCLOUD_OBJECTSTORE_ENABLED=true
      - OWNCLOUD_OBJECTSTORE_CLASS=OCA\Files_Primary_S3\S3Storage
```

### Additional context

 Possibly relevant, but whenever I run owncloudcmd, the output starts with something like this:

```
23-10-04 16:39:35:012 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:39:40:523 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:39:46:032 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:39:51:541 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:39:57:049 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:40:02:570 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:40:08:084 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:40:13:594 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:40:19:102 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:40:24:611 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:40:30:120 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:40:35:628 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:40:41:139 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:40:46:648 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:40:52:156 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:40:57:666 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:41:03:184 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:41:08:694 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:41:14:204 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:41:19:712 [ warning sync.database.sql ]:    SQL exec failed "DROP INDEX IF EXISTS metadata_parent;" "database is locked"
23-10-04 16:41:20:212 [ warning sync.database.sql ]:    Sqlite exec statement error: 5 "database is locked" in "DROP INDEX IF EXISTS metadata_parent;"
23-10-04 16:41:20:212 [ warning sync.database ]:        SQL Error "updateMetadataTableStructure: remove index metadata_parent" "database is locked"
```

**Comment by TheOneRing** [comment]
Please try: `games/` instead of `games` in the not sync list.

The db error is unrelated and indicates that the db is already opened by another process.
