### ISSUE TITLE
Virtual files + hidden folders not synchronized

### ISSUE THREAD

**Issue by zeroxx1986** [owncloud/client#11260]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Completely new OwnCloud client install on Windows 11, virtual filesystem is used, "Sync hidden files" is set in Settings, but the hidden folders (anything starting with ".") are not visible and not synchronized locally, even when trying forced sync many times.

### Expected behavior

Hidden folders are synchronized when "Sync hidden files" is turned on.

### Steps to reproduce the issue

1. Add a hidden folder into owncloud, i.e. ".wind" and add some content inside (additional folders / normal files, whatever)
2. Install a new client in a new computer and sync it to the server
3. Enable virtual file support
4. Try to find the ".wind" folder - it's not visible in the local filesystem, while owncloud says everything is synced.
5. Enable "Sync hidden files" in settings
6. Force sync
7. Try to find the ".wind" folder - it's not visible in the local filesystem, while owncloud says everything is synced.

### Client version number

OwnCloud 4.2.0.11670

### Installation path (Windows only)

c:\Program Files\ownCloud

### Server information

ownCloud 10.12.2 (stable) running in Docker

### Additional context

The hidden folder & all files are correctly visible and browsable / downloadable on the webUI.

**Comment by zeroxx1986** [comment]
up

**Comment by TheOneRing** [comment]
I can't reproduce the issue with version 5.
![image](https://github.com/owncloud/client/assets/200626/9f396ce7-76fc-4d5b-8cee-3e69a0149e3e)
```
Action         ,File                                                            ,Folder                        ,Size  ,Account             ,Time                ,Status              ,
Downloaded     ,.wind                                                           ,ownCloud - Albert Einstein@ocis.owncloud.test (4)\Personal,      ,Albert Einstein@ocis.owncloud.test,2023-11-07T10:57:44.883,Success             ,

```
Please share your synced/not synced table (right click copy)

**Comment by zeroxx1986** [comment]
Hi Hannah,

I've created a vanilla VM to reproduce this issue with the newest OwnCloud client - and the issue is still there, easily reproducible.

What I did:
1. Set up OwnCloud, default settings except for the owncloud folder (I set it to C:\OwnCloud instead)
2. Checked in settings to sync hidden files
3. Wait for sync complete (very fast) & just to be sure, forced another sync
4. Tried copying the synced files table, but it's just only a small subset of the synced files, and even the root folder where this app is residing in (/apps) is not present there, so I'll not add waste logs in here.
5. Not synced table is completely empty
6. Checked the folder where the .wind subfolder should be, and it's not there
7. Over the web, the .wind folder is clearly visible

Is there any other way to capture the whole sync process (this table you mentioned) so you'll get more information?

![01_setup](https://github.com/owncloud/client/assets/4190724/3af262ef-c962-459c-ae67-c38609d92afd)
![image](https://github.com/owncloud/client/assets/4190724/15b669ba-5ef7-493b-9b39-e3bde77cb70a)
![image](https://github.com/owncloud/client/assets/4190724/9742bc7e-1ccf-45dd-8356-25b8f26df8f7)
![image](https://github.com/owncloud/client/assets/4190724/2d50db44-6c40-48a5-8d52-ca6f371de976)
![06_hidden_folder_missing](https://github.com/owncloud/client/assets/4190724/eb500bc4-9b7d-44e1-bf0b-6d56cc527a2b)
![07_hidden_folder_in_webview](https://github.com/owncloud/client/assets/4190724/44a88b1b-29a9-4345-89b4-6b330a583708)

**Comment by TheOneRing** [comment]
If synced the file is supposed to be listed in the synced tab.
Could you provide some logs including http logs? Or give https://github.com/owncloud/client/releases/tag/v5.1.1-rc.1 a try.

Please upload logs to: https://cloud.owncloud.com/s/RExA7HZWRuIMvW2

**Comment by zeroxx1986** [comment]
Upon trying to collect the logs from zero, I think I've stumbled upon the actual issue..

If I add the account first, then after it syncs (or it started to sync) for the first time I enable the "Sync hidden files" in the Settings, no hidden files or folders are added, no matter how much I try to force sync. The Activity shows nothing under Not Synced tab either.

On the other hand, if I enable the "Sync hidden files" first, then after it I add the account, the setting is ignored and gets unchecked right after the account is added.. 

The only way this works correctly is if just after the account has been added, immediately I go into settings & check the Sync hidden files - after the initial sync, the hidden files & folders are correctly synced and I do see the previously missing .wind folder.

I uploaded logs related to both scenarios (first & last) to the provided url, thanks!

**Comment by zeroxx1986** [comment]
up

**Comment by TheOneRing** [comment]
Ok so I have a theory, you switched it on before any account was added?
The setting is stored in the accounts (for historic reasons) and if there is no account....

**Comment by zeroxx1986** [comment]
> Ok so I have a theory, you switched it on before any account was added? The setting is stored in the accounts (for historic reasons) and if there is no account....

Yes, You are correct - I did a brand new install, no accounts present prior to it whatsoever. 

I think this should be a very generic use-case for home users - for whatever reason, i.e. you reinstall your computer or just have a new one which you want your owncloud to be available, you don't have any prior accounts there at that point - and after the very first sync goes through without this switch being enabled, there is no way to get the hidden files/folders anymore unless you remove everything and tick the sync hidden files option prior of the first sync being done.

Btw I don't see the hidden option being bound to an account an issue, rather the fact that after you do your initial sync with this hidden option disabled, if you enable it, you won't get the hidden files/folders afterwards. It will add & sync anything new, but not the ones which existed earlier - and it happily overwrites existing ones on the server also - like with the same application example (windterm):
1. you have an existing .wind folder on the server which wasn't synced due to the hidden option not being set initially, 
2. then you enable the hidden option (it won't sync/add the existing .wind folder from the server) 
3. you start windterm, 
4. it sees there's no .wind folder, creates it with initial configuration.
5. owncloud detects a hidden file/folder change, and syncs it to the server, overwriting the existing one.

**Comment by TheOneRing** [comment]
Hmm did you try `force sync` after you changed the sync hidden files option?
![image](https://github.com/owncloud/client/assets/200626/972f8ec2-9b9c-41e4-9969-60c5114a2fb0)
An incremental sync would not check the whole tree by default, only the next full sync (1/1h) would go through everything.

**Comment by zeroxx1986** [comment]
Yes, I did try the force sync, it did not solve the issue, the existing hidden folders/files did not appear after.
What would this next full sync (1/1h) be? It does a full sync every 1 hour or 1 day?

**Comment by fmoc** [comment]
It does a full sync run whenever you hit "force sync", so that should have done it, if any.

Have you updated to the latest release 5.2.0? If not, please do so and try again. This is the version we test against.

**Comment by zeroxx1986** [comment]
> It does a full sync run whenever you hit "force sync", so that should have done it, if any.
> 
> Have you updated to the latest release 5.2.0? If not, please do so and try again. This is the version we test against.

Just tried it. Removed owncloud completely, installed the newest one: `5.2.0.12726`. Added my account, let it sync through. After it finished, I ticked `Sync hidden files` and went back to the Account tab and did a `Force sync now` - nothing changed, the hidden folder did not appear. Tried doing the force sync several times, same result, nothing changed.

**Comment by zeroxx1986** [comment]
up

**Comment by zeroxx1986** [comment]
up

**Comment by zeroxx1986** [comment]
up

**Comment by zeroxx1986** [comment]
up

**Comment by zeroxx1986** [comment]
up

**Comment by zeroxx1986** [comment]
up
