### ISSUE TITLE
[5.0.0] Stuck in "Connecting" after Response: PROPFIND 0 (Error: Temporary network failure.,1219413ms)

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#11274]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

ownCloud sync client got stuck in "Connecting" state after receiving `Response: PROPFIND 0 (Error: Temporary network failure.,1219413ms)`

### Expected behavior

Client should recover

### Screenshots

![CleanShot 2023-10-10 at 16 49 09](https://github.com/owncloud/client/assets/214010/6ef266a2-3ef0-4170-8f0b-a59b8b314e91)

### Logs

- https://cloud.owncloud.com/f/6096380

### Client version number

ownCloud 5.0.0.12278 [8f9152](https://github.com/owncloud/client/commit/8f9152e5eb6fde81a1a1ba889ee03df2e3e9445c)
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: suffix
OS: macos-23.0.0
QPA: cocoa

### Additional context

Related?

- https://github.com/owncloud/client/issues/11250
- https://github.com/owncloud/client/pull/11244

**Comment by michaelstingl** [comment]
@TheOneRing I see `PROPFIND` with `Depth: 0` was fired a second time after `59ms` , with same `X-Request-ID` 🙀 

```
23-10-08 04:08:31:844 [ info sync.httplogger ]:	"3e12a243-3f68-4b3e-8f7c-95def044c355: 
Request: PROPFIND https://cloud.owncloud.com/remote.php/dav/files/mstingl/ 
Header: { Depth: 0, 
Prefer: return=minimal, 
Authorization: Bearer [redacted], 
User-Agent: Mozilla/5.0 (Macintosh) mirall/5.0.0.12278 (ownCloud, 
macos-23.0.0 ClientArchitecture: arm64 OsArchitecture: arm64), 
Accept: */*, 
Accept-Language: en_DE, 
Content-Type: text/xml; charset=utf-8, 
X-Request-ID: 3e12a243-3f68-4b3e-8f7c-95def044c355, 
Original-Request-ID: 3e12a243-3f68-4b3e-8f7c-95def044c355, 
Content-Length: 108, 
Cookie: #######, 
} 
Data: [<?xml version=\"1.0\" encoding=\"utf-8\"?>
<d:propfind xmlns:d=\"DAV:\">
<d:prop>
<d:getetag/>
</d:prop>
</d:propfind>\n]"

23-10-08 04:08:31:903 [ info sync.httplogger ]:	"3e12a243-3f68-4b3e-8f7c-95def044c355: 
Request: PROPFIND https://cloud.owncloud.com/remote.php/dav/files/mstingl/ 
Header: { Depth: 0, 
Prefer: return=minimal, 
Authorization: Bearer [redacted], 
User-Agent: Mozilla/5.0 (Macintosh) mirall/5.0.0.12278 (ownCloud, 
macos-23.0.0 ClientArchitecture: arm64 OsArchitecture: arm64), 
Accept: */*, 
Accept-Language: en_DE, 
Content-Type: text/xml; charset=utf-8, 
X-Request-ID: 3e12a243-3f68-4b3e-8f7c-95def044c355, 
Original-Request-ID: 3e12a243-3f68-4b3e-8f7c-95def044c355, 
Content-Length: 108, 
Cookie: #######, 
} 
Data: [<?xml version=\"1.0\" encoding=\"utf-8\"?>
<d:propfind xmlns:d=\"DAV:\">
<d:prop>
<d:getetag/>
</d:prop>
</d:propfind>\n]"

23-10-08 04:28:51:262 [ info sync.httplogger ]:	"3e12a243-3f68-4b3e-8f7c-95def044c355: 
Response: PROPFIND 0 (Error: Temporary network failure.,1219413ms) https://cloud.owncloud.com/remote.php/dav/files/mstingl/ 
Header: { } 
Data: []"

```

**Comment by cdamken** [comment]
I uploaded my logs: https://cloud.owncloud.com/f/6102956

**Comment by steelcuts** [comment]
FYI: Switch has the same issue.

**Comment by michaelstingl** [comment]
@fmoc what is the blocker?

**Comment by michaelstingl** [comment]
Related?
- https://github.com/owncloud/client/issues/11281

**Comment by rainforest1155** [comment]
Since the version 5 update, the linux client is stuck on "connecting" every time I resume my machine from hibernation. Possibly related to the fact that due to various reasons, before going into hibernation I turn off networking and manually bring it up upon resuming.

This was never a problem on the owncloud client prior to version 5. Now it basically never syncs and I'm always wondering why I see no new files. Then I remember this issue and I have to close and reopen the owncloud client. 

I'm hoping this gets fixed soon. Thanks!

my OS is: manjaro-6.1.55-1-MANJARO
with OC client 5.0.0 8f9152

**Comment by michaelstingl** [comment]
Does someone has 5.2 logs with this? There we improved debug logs.

**Comment by michaelstingl** [comment]
You can test-drive with the latest 5.x dailies:
- https://download.owncloud.com/desktop/ownCloud/daily/5.2/?sort=time&order=desc
- https://download.owncloud.com/desktop/testpilotcloud/daily/5.2/?sort=time&order=desc

**Comment by HanaGemela** [comment]
Steps to test:
1. Quit the client
2. Turn on maintenance mode on the server
3. Start the client
4. Turn off maintenance mode on the server
5. Click Reconnect in the client

Client needs 1-2 minutes to reconnect ✅ 
Tested with ownCloud 5.2.1.13015-daily20240103

**Comment by michaelstingl** [comment]
> 5\. Click Reconnect in the client

Shouldn't be necessary. Do we have an issue for this?

**Comment by HanaGemela** [comment]
> > 5. Click Reconnect in the client
> 
> Shouldn't be necessary. Do we have an issue for this?

It was necessary to recreate in 5.2.0
Without this step the client recovered within 2 minutes

**Comment by michaelstingl** [comment]
> Without this step the client recovered within 2 minutes

Works for me 👍

**Comment by HanaGemela** [comment]
> > Without this step the client recovered within 2 minutes
> 
> Works for me 👍

The old broken 5.2.0 recovered within 2 minutes without this step
