### ISSUE TITLE
To support AD FS make redirect_uri port range configurable

### ISSUE THREAD

**Issue by butonic** [owncloud/client#11276]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

I would like to authenticate users with an on-premise AD FS 2022 using OpenID Connect. While the documentation for AzureID has documented [`redirect_url` restrictions](https://learn.microsoft.com/en-us/azure/active-directory/develop/reply-url), especially for [`localhost`](https://learn.microsoft.com/en-us/azure/active-directory/develop/reply-url#localhost-exceptions) registering any of these withg AD FS does not work:
```
http://127.0.0.1/callback/
http://127.0.0.1/callback
http://127.0.0.1:48395/callback/
http://localhost/callback
http://localhost:55555/callback
https://localhost/callback
http://127.0.0.1:*
```

Only `redirect_uri` entries that include a port will let the client authenticate. All other cases lead to an error like this:
```
    Activity ID: a8f9f18b-dd70-47bf-ba00-0040000000ee
    Error details: MSIS9224: Received invalid OAuth authorization request. The received 'redirect_uri' parameter is not a valid registered redirect URI for the client identifier: '01d03691-b75e-4828-b93d-a33ac2ed6631'. Received redirect_uri: 'http://127.0.0.1:62216'.
    Node name: 4210c302-325f-4e8d-8d99-3aa76743da3e
    Error time: Tue, 10 Oct 2023 23:16:39 GMT
    Cookie: enabled
    User agent string: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0
```

### Proposed solution

Intead of letting the client randomly pick a port allow configuring a port range. The client then randomly picks one of those ports until he finds a free port. Admins can brand clients to only use a limited range of ports and register them as valid `redirect_uri` entries in AD FS.

### Alternative solutions you considered

We could hardcode a single port, but that will lead to corner cases where the port is in use by another application.

The correct solution would be to register a protocol scheme and the desktop client as a handler for that scheme. The problem here is that different versions of the client then need to register different protocol schemes, otherwise the user might be presented with a dialog to choose which desktop client should handle them. We could register a scheme like `owcloud.mirall.{clientid}` to use the clientid as part of the protocol handler to work around that. But this looks to be a lot of effort.

**Comment by butonic** [comment]
Another thing I ran into was
```
Fehler vom Server zurückgegeben: MSIS9631: Received invalid OAuth request. Multiple client authentication methods were attempted.
```

which led me to https://github.com/FusionAuth/fusionauth-issues/issues/445#issuecomment-580996329 and consecutively to this change that made ADFS successfully authenticate the desktop client:

```cpp
diff --git a/src/libsync/creds/oauth.cpp b/src/libsync/creds/oauth.cpp
index 34cb759d4..dee405fa1 100644
--- a/src/libsync/creds/oauth.cpp
+++ b/src/libsync/creds/oauth.cpp
@@ -436,9 +439,15 @@ QNetworkReply *OAuth::postTokenRequest(const QList<QPair<QString, QString>> &que
     req.setAttribute(HttpCredentials::DontAddCredentialsAttribute, true);

     QUrlQuery arguments;
-    arguments.setQueryItems(QList<QPair<QString, QString>> { { QStringLiteral("client_id"), _clientId },
-                                { QStringLiteral("client_secret"), _clientSecret },
-                                { QStringLiteral("scope"), Theme::instance()->openIdConnectScopes() } }
+    arguments.setQueryItems(QList<QPair<QString, QString>> { 
+        /*
+        with these part of the body AD FS dies with a MSIS9631: Received invalid OAuth request. Multiple client authentication methods were attempted. error
+          see https://github.com/FusionAuth/fusionauth-issues/issues/445
+          { QStringLiteral("client_id"), _clientId },
+          { QStringLiteral("client_secret"), _clientSecret },
+        */
+        { QStringLiteral("scope"), Theme::instance()->openIdConnectScopes() }
+    }
         << queryItems);
     req.setUrl(requestTokenUrl);
     return _networkAccessManager->post(req, arguments.toString(QUrl::FullyEncoded).toUtf8());
```

To get the ports going I hardcoded a few of them like this:
```cpp
diff --git a/src/libsync/creds/oauth.cpp b/src/libsync/creds/oauth.cpp
index 34cb759d4..dee405fa1 100644
--- a/src/libsync/creds/oauth.cpp
+++ b/src/libsync/creds/oauth.cpp
@@ -249,7 +249,9 @@ void OAuth::startAuthentication()
     qCDebug(lcOauth) << "starting authentication";

     // Listen on the socket to get a port which will be used in the redirect_uri
-    if (!_server.listen(QHostAddress::LocalHost, 51015)) {
+    if (!_server.listen(QHostAddress::LocalHost, 2005) || !_server.listen(QHostAddress::LocalHost, 11010) || !_server.listen(QHostAddress::LocalHost, 51010) || !_server.listen(QHostAddress::LocalHost, 51011) || !_server.listen(QHostAddress::LocalHost, 51012) || !_server.listen(QHostAddress::LocalHost, 51013) || !_server.listen(QHostAddress::LocalHost, 51014) || !_server.listen(QHostAddress::LocalHost, 51015)) {
+        qCDebug(lcOauth) << "server listening on " << _server.serverPort();
+    } else {
         qCDebug(lcOauth) << "server is not listening";
         emit result(NotSupported, QString());
         return;
```

I also disabled the certificate check because we were using a self signed certificate. Don't do this at home ...
```cpp
diff --git a/src/libsync/creds/oauth.cpp b/src/libsync/creds/oauth.cpp
index 34cb759d4..dee405fa1 100644
--- a/src/libsync/creds/oauth.cpp
+++ b/src/libsync/creds/oauth.cpp
@@ -331,6 +333,7 @@ void OAuth::startAuthentication()
                     { QStringLiteral("redirect_uri"), QStringLiteral("%1:%2").arg(_redirectUrl, QString::number(serverPort)) },
                     { QStringLiteral("code_verifier"), QString::fromUtf8(_pkceCodeVerifier) },
                 });
+                reply->ignoreSslErrors();

                 connect(reply, &QNetworkReply::finished, this, [reply, socket, this] {
                     const auto jsonData = reply->readAll();
@@ -654,6 +663,7 @@ void AccountBasedOAuth::refreshAuthentication(const QString &refreshToken)
         auto refresh = [this, refreshToken] {
             auto reply = postTokenRequest({ { QStringLiteral("grant_type"), QStringLiteral("refresh_token") },
                 { QStringLiteral("refresh_token"), refreshToken } });
+            reply->ignoreSslErrors();
             connect(reply, &QNetworkReply::finished, this, [reply, refreshToken, this]() {
                 const auto jsonData = reply->readAll();
                 QJsonParseError jsonParseError;
```

I'm not saying we should do it like this ... I'm documenting what I had to do to get it working ...

**Comment by michaelstingl** [comment]
So, a branding option that limits the random port to a smaller range would work fine for now?

**Comment by michaelstingl** [comment]
Yeah, this is what I’d prefer mid-term. It would also allow us, to navigate to local files from the web UI one day…

**Comment by butonic** [comment]
> So, a branding option that limits the random port to a smaller range would work fine for now?

that would be sufficient, yes

**Comment by fmoc** [comment]
The most basic implementation is a comma-separated list instead of introducing some range syntax.

**Comment by michaelstingl** [comment]
> The most basic implementation is a comma-separated list instead of introducing some range syntax.

Works for me 👍

**Comment by TheOneRing** [comment]
I added an option to configure a list of ports.
Not sending a client id and secret sound wrong and like a different issue?
I will definitely not ignore ssl errors during auth 😝

**Comment by michaelstingl** [comment]
> Not sending a client id and secret sound wrong and like a different issue?

Sending them shouldn't cause problems?

**Comment by TheOneRing** [comment]
Example:
```
QVector<quint16> oauthPorts() const
{
    // zero means a random port
    return {1, 2, 3};
}
