### ISSUE TITLE
Mac: Investigate whether we can ignore mac os periodic wakeups

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11281]

**Comment by erikjv** [comment]
https://developer.apple.com/forums/thread/739933

**Comment by erikjv** [comment]
Note: check if we can ask what kind of wake-up this is.

**Comment by erikjv** [comment]
> Note: check if we can ask what kind of wake-up this is.

As far as I can see, no wake-up reason is passed to applications.

**Comment by erikjv** [comment]
> Note: check if we can ask what kind of wake-up this is.

I checked, and I cannot find an API or parameter that does this.

**Comment by TheOneRing** [comment]
Thx
