### ISSUE TITLE
Mojave support broken, updater installs it anyway

### ISSUE THREAD

**Issue by codepoet80** [owncloud/client#11287]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Prompted to install latest version on Mojave, after install app wouldn't start. Found out its because Mojave no longer supported. The updater shouldn't offer to break itself. Also, the [ownCloud home page claims support for macOS 10.12 or higher](https://owncloud.com/desktop-app/). Mojave is 10.14, which is definitely higher than 10.12.

Just because Apple hates their customers doesn't mean an OSS project should.

### Expected behavior

Continued support for Mojave -- its advertised on the ownCloud homepage, and the main reason I use ownCloud. Failing that, don't offer to install a version that doesn't work.

### Steps to reproduce the issue

1. Use ownCloud on Mojave (still the most compatible macOS)
2. Get prompted to update
3. Install update
4. Find out ownCloud no longer works

### Screenshots

![Screen Shot 2023-10-12 at 9 52 13 AM](https://github.com/owncloud/client/assets/16038880/29307b42-5353-488a-97ce-7b250d35a647)

![Screen Shot 2023-10-12 at 9 55 38 AM](https://github.com/owncloud/client/assets/16038880/fd96b13a-fd62-4d41-acb0-eec2a133e1f2)

![Screen Shot 2023-10-12 at 10 14 22 AM](https://github.com/owncloud/client/assets/16038880/38c2d0a0-ab2c-44ec-a5fb-6ba9ae135b51)

### Client version number

ownCloud Client 5.0.0.12278

### Server information

Server: 10.12.2 (stable)

**Comment by TheOneRing** [comment]
We just fixed our updater to not push updates to < 10.15.
The screenshot you posted is for 4.2 which indeed still supported 10.12.
Please uninstall ownCloud and reinstall 4.2.

**Comment by TheOneRing** [comment]
`Just because Apple hates their customers doesn't mean an OSS project should.`
We don't but we can only support the platforms supported by the software we use (Qt).

**Comment by codepoet80** [comment]
> We don't but we can only support the platforms supported by the software we use (Qt).

Fair enough -- but if you don't support the OS, the website shouldn't _claim_ to support the OS, and the updater shouldn't install the package on an unsupported OS.

**Comment by TheOneRing** [comment]
> > We don't but we can only support the platforms supported by the software we use (Qt).
> 
> Fair enough -- but if you don't support the OS, the website shouldn't _claim_ to support the OS, and the updater shouldn't install the package on an unsupported OS.

The website still provides 4.2 which supports macOS 10.12, once they promote 5.0 it will provide the updated requirements.

**Comment by codepoet80** [comment]
ownCloud 5 is being promoted on the home page, but minimum requirements still say macOS 10.12 is the minimum requirement. ownCloud 5 does not work on macOS 10.12.
![Capture](https://github.com/owncloud/client/assets/16038880/72930dcb-527c-42c4-8b99-b64d777d79ea)

**Comment by michaelstingl** [comment]
Docs for reference:
- https://doc.owncloud.com/desktop/5.0/installing.html#system-requirements
