### ISSUE TITLE
Unreadable UI in GNOME with display scale

### ISSUE THREAD

**Issue by simeonborko** [owncloud/client#11289]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

In the GNOME environment (running Debian) with zoom (display scale), UI elements and text is not scaled and is cropped and not fully readable.

### Expected behavior

I expected to see scaled client UI.

### Steps to reproduce the issue

1. Use Debian with GNOME
2. Go to Settings -> Display
3. Set scale 200% for your display
4. Run OwnCloud client

### Screenshots

![Screenshot from 2023-10-13 10-30-42](https://github.com/owncloud/client/assets/12039032/1982b5fa-aaa8-4999-820c-4fa6b6ee68c2)

### Client version number

ownCloud 4.2.0.11670 [f5a29b](https://github.com/owncloud/client/commit/f5a29bc3446734c565b106c1bdddc09ec03f76eb)
Libraries Qt 5.15.2, OpenSSL 1.1.1w 11 Sep 2023
Using virtual files plugin: suffix
debian-5.10.0-26-amd64

### Desktop environment (Linux only)

Debian 11 with GNOME version 3.38.5

### Client package version and origin (Linux only)

ownCloud mirror

**Comment by TheOneRing** [comment]
Could you give the 5.0 appimage a try?

**Comment by simeonborko** [comment]
I'd prefer to use apt, but yes, using the 5.0 apptainer works, thanks, closing.

**Comment by michaelstingl** [comment]
> I'd prefer to use apt

Apt will be back with 5.1+
