### ISSUE TITLE
Regression: AppImage thumbnail's resolution is too small

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#11298]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Seen in linux mint, using nemo 5.2.4

* install a helper that enables rendering of appimage icons: https://github.com/mttbernardini/appimage-thumbnailer/releases
* download both, 5.0.0 and 4.2.0 appimage from https://download.owncloud.com/desktop/ownCloud/stable/
* navigate into the download folder with nemo.
* the 4.2.0 appimage icon is low quality, but acceptable. 
* the 5.0.0 appimage icon is a very poor quality blurr. BAD.
![grafik](https://github.com/owncloud/client/assets/1108546/ffeeb4f8-1975-4442-9242-668b3682c756)

/tmp/.mount_ownClonifZkG/.DirIcon -> owncloud.png
/tmp/.mount_ownClonifZkG/owncloud.png -> usr/share/icons/hicolor/24x24/apps/owncloud.png
![owncloud](https://github.com/owncloud/client/assets/1108546/5bfedca6-f43e-4ca0-ac33-ef1b2d561f31)

There is a range of larger resolutions included too:
`file  /tmp/.mount_ownClonifZkG/usr/share/icons/hicolor/*/apps/owncloud.png`
```
/tmp/.mount_ownClonifZkG/usr/share/icons/hicolor/1024x1024/apps/owncloud.png: PNG image data, 1024 x 1024, 8-bit/color RGBA, non-interlaced
/tmp/.mount_ownClonifZkG/usr/share/icons/hicolor/128x128/apps/owncloud.png:   PNG image data, 128 x 128, 8-bit/color RGBA, non-interlaced
/tmp/.mount_ownClonifZkG/usr/share/icons/hicolor/16x16/apps/owncloud.png:     PNG image data, 16 x 16, 8-bit/color RGBA, non-interlaced
/tmp/.mount_ownClonifZkG/usr/share/icons/hicolor/24x24/apps/owncloud.png:     PNG image data, 24 x 24, 8-bit/color RGBA, non-interlaced
/tmp/.mount_ownClonifZkG/usr/share/icons/hicolor/256x256/apps/owncloud.png:   PNG image data, 256 x 256, 8-bit/color RGBA, non-interlaced
/tmp/.mount_ownClonifZkG/usr/share/icons/hicolor/32x32/apps/owncloud.png:     PNG image data, 32 x 32, 8-bit/color RGBA, non-interlaced
/tmp/.mount_ownClonifZkG/usr/share/icons/hicolor/48x48/apps/owncloud.png:     PNG image data, 48 x 48, 8-bit/color RGBA, non-interlaced
/tmp/.mount_ownClonifZkG/usr/share/icons/hicolor/64x64/apps/owncloud.png:     PNG image data, 64 x 64, 8-bit/color RGBA, non-interlaced
```
The folder /tmp/.mount_ownClonifZkG/usr/share/icons/hicolor/scalable/apps/ exists, but is empty.

### Expected behavior

* make owncloud.png a symlink to usr/share/icons/hicolor/128x128/apps/owncloud.png
that looks reasonably crisp on my screen, while being smallish.
![owncloud](https://github.com/owncloud/client/assets/1108546/c8b48e71-f922-4398-9f82-f77d251394e0)
* usr/share/icons/hicolor/scalable/apps/ should contain an svg image.

### Steps to reproduce the issue

yes

### Screenshots

yes

### Logs

no

### Client version number

yes

### Desktop environment (Linux only)

yes

### Client package version and origin (Linux only)

yes

### Installation path (Windows only)

no

### Server information

no

### Additional context

no

**Comment by fmoc** [comment]
Should be fixed upstream.

**Comment by fmoc** [comment]
The `.DirIcon` is still a 24x24px PNG image. Reopening.

**Comment by fmoc** [comment]
We now ship a 64x64 icon:

```sh
> identify squashfs-root/.DirIcon 
squashfs-root/.DirIcon PNG 64x64 64x64+0+0 8-bit sRGB 2326B 0.000u 0:00.000
```

Previously, we apparently shipped a 256x256 icon. I am looking into whether a bigger resolution would be more adequate.

**Comment by fmoc** [comment]
64x64 is the default linuxdeploy will ship now. I consider this sufficient for our use case. Changes to the recent change in the lookup algorithm need to be discussed there of course.

**Comment by saw-jan** [comment]
![Screenshot from 2023-11-02 17-32-00](https://github.com/owncloud/client/assets/52366632/5242ac18-49b5-4218-b351-40230822a744)

| 4.2 stable | 4.3 daily | 5.0 stable | 5.1 daily | 6.0 daily |
--|--|--|--|--
`.DirIcon PNG 256x256` | `.DirIcon PNG 24x24` (Expected) | `.DirIcon PNG 24x24` (Expected) | `.DirIcon PNG 64x64 64x64` :heavy_check_mark:  | `.DirIcon PNG 64x64 64x64` :heavy_check_mark:
