### ISSUE TITLE
[QA] Linux: landscape pictures don't have an overlay icon

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11306]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Ubuntu 22.04
owncloud 5.1.0 rc1
nautilus file manager, nemo

Fedora 38
Nemo file manager

### Steps to reproduce the issue

1. Add a demo.owncloud.com account 
2. Check an overlay icon of /Photos/Lake-Constance.jpg

### Screenshots

<img width="902" alt="Screenshot 2023-10-24 at 11 03 17" src="https://github.com/owncloud/client/assets/49001702/3059ac58-a6f4-4d40-9c0c-74e02a831559">

### Expected behavior

An icon

### Actual behavior

No icon

**Comment by michaelstingl** [comment]
@HanaGemela regression? Or same with 4.2?

**Comment by fmoc** [comment]
![screenshot_2023-10-24_12-54-45](https://github.com/owncloud/client/assets/80399010/9eb8ac5b-9bba-48a6-9333-a47280a586c7)

Looks like an upstream bug.

**Comment by fmoc** [comment]
Note: this can affect Nautilus as well as its forks. Looks like it depends on the icon position. Only when the overlay is shown in the bottom right corner, images with (extreme?) landscape aspect ratio are affected.

![screenshot_2023-10-24_12-30-42](https://github.com/owncloud/client/assets/80399010/bf54ecc0-6b50-4882-a4da-83fee1e0607e)
![screenshot_2023-10-24_12-32-04](https://github.com/owncloud/client/assets/80399010/0739a431-e5c3-4e2e-b348-4c0b324f08fe)

**Comment by fmoc** [comment]
I've experimented a bit. It seems that at an aspect ratio of `w/h <= 1.65` (roughly), the overlay icon is shown in all cases.

**Comment by fmoc** [comment]
Apparently, this is a hardcoded issue either within Nautilus and its forks or libgdk. Either way, this needs to be reported upstream. We should report it with the distributions which configure the bottom-right overlay, or alternatively ask Nautilus and its forks to review the problem.

**Comment by TheOneRing** [comment]
No actions planned
