### ISSUE TITLE
[QA] Linux docker install test is hard to evaluate

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11301]
[test_20231019_1423.log](https://github.com/owncloud/client/files/13042628/test_20231019_1423.log)

The report is too long and contains too much information.
Please report only relevant results and make it clear if it passed or failed

**Comment by fmoc** [comment]
This was just a bug in the script.

**Comment by HanaGemela** [comment]
10_key_expiry test looks good now

The rest needs to be adjusted so that it displays clear result

**Comment by TheOneRing** [comment]
Going forward, we will no longer use this test.
