### ISSUE TITLE
[QA] The initial sync takes too long to start

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11308]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Ubuntu 22.04
owncloud 5.1.0 rc1

### Steps to reproduce the issue

1. Add a new account
2. Wait for the initial sync

### Screenshots

<img width="801" alt="Screenshot 2023-10-24 at 12 53 29" src="https://github.com/owncloud/client/assets/49001702/9046a654-a9fb-40b3-ab05-fa52889765a6">

### Expected behavior

Sync starts immediately 

### Actual behavior

It takes a couple of seconds till the sync begins

**Comment by TheOneRing** [comment]
My guess, one of the others is syncing?

**Comment by TheOneRing** [comment]
Anyhow the logs would tell us.

**Comment by HanaGemela** [comment]
@TheOneRing logs here https://cloud.owncloud.com/f/6115577

**Comment by HanaGemela** [comment]
Fixed in Ubuntu_22.04 owncloud-client-5.1.0.12517-daily20231031
