### ISSUE TITLE
[QA] Dolphin file manager does not display the overlay icons 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11309]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Ubuntu 22.04
owncloud 5.1.0 rc1

### Steps to reproduce the issue

1. Install dolphin file manager 
2. Install owncloud-client-dolphin

### Screenshots

No screesnhot

### Expected behavior

Overlay icons displayed 

### Actual behavior

No icons at all

**Comment by fmoc** [comment]
Note: this only occurs when installing Dolphin as a secondary file manager on Ubuntu with GNOME. Nautilus works as expected.

**Comment by fmoc** [comment]
The context menu extension seems to work on most of the listed distributions. The overlay icons seem to miss some KDE component.

**Comment by TheOneRing** [comment]
QT_DEBUG_PLUGINS to the rescue?

**Comment by fmoc** [comment]
Sent a mail to the mailing list linked on their homepage. No response so far, probably because it has not been published yet.

**Comment by TheOneRing** [comment]
We were not able to reproduce the issue with the KF6 version.
