### ISSUE TITLE
[QA] Linux: GUI looks different when automatically started on login

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11307]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Ubuntu 22.04
owncloud 5.1.0 rc1

### Steps to reproduce the issue

1. Restart the computer
2. Let the owncloud client start
3. Show owncloud

### Screenshots

Autostart on login
<img width="831" alt="Screenshot 2023-10-24 at 12 46 32" src="https://github.com/owncloud/client/assets/49001702/4bbc10dc-f6cb-453f-ad94-bd0db4a66e0c">

Started manually
<img width="813" alt="Screenshot 2023-10-24 at 12 46 56" src="https://github.com/owncloud/client/assets/49001702/56f8f143-2eab-4ebc-854e-7e34f6d71e4c">

### Expected behavior

Looks the same

### Actual behavior

Different look

**Comment by TheOneRing** [comment]
Current theory: With our native packages autostart is not using the aprun script but directly calls the appplication, which then lacks the proper environment vars.

**Comment by fmoc** [comment]
Confirmed. Maybe we need to use `argv[0]` rather than Qt's application binary path to configure the autostart file.

**Comment by TheOneRing** [comment]
> Confirmed. Maybe we need to use `argv[0]` rather than Qt's application binary path to configure the autostart file.

that could be any symlink...

**Comment by TheOneRing** [comment]
I guess we need to add special handling for our native packages?

**Comment by fmoc** [comment]
We could have a special AppRun hook that exports an environment variable so that when the client is run from some AppDir (which includes our native packages but also the AppImage), it is aware of that fact.
