### ISSUE TITLE
[QA] Linux: No overlay icons in Nemo file manager on openSUSE

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11311]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

openSUSE 15.4
Nemo file manager

### Steps to reproduce the issue

1. Check the overlay icons in Nemo file manager on openSUSE

### Screenshots

No screenshot

### Expected behavior

Overlay icons are present

### Actual behavior

No icons

**Comment by fmoc** [comment]
What desktop environment was used on openSUSE? KDE?

**Comment by fmoc** [comment]
I installed the nemo extension in an openSUSE KDE live VM. The Dolphin one works exactly as expected. The nemo one, despite being installed as expected to `/usr/share/nemo-python`, does not even show up as an extension in nemo's plugins manager. Investigating.

**Comment by fmoc** [comment]
![screenshot_2023-10-25_12-01-42](https://github.com/owncloud/client/assets/80399010/7f965697-0608-40ae-aec8-740ed806485a)

Looks like a bug in our code.

**Comment by HanaGemela** [comment]
> What desktop environment was used on openSUSE? KDE?

yes, KDE

**Comment by fmoc** [comment]
Should be fixed by https://gitea.owncloud.services/client/build-linux-mk2/commit/0fd874225e302ed8259e4e6d42aa77e0eddcd168.

**Comment by HanaGemela** [comment]
Passed in owncloud-client-nemo-5.1.0~daily20231025-12476
