### ISSUE TITLE
Client v5.x.x doesn't work on Windows 7

### ISSUE THREAD

**Issue by ask6483** [owncloud/client#11327]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

After updating client to v5.0.0 there is an error popup:
"The Application was unable to start correctly (0xc000000c). Click OK to close the application"

### Expected behavior

Client should start normally

### Steps to reproduce the issue

1. Update client to version v5.0.0 from previous version or download the installer..
2. Install..
3. Client application is not starting with error message..

### Client version number

ownCloud v5.0.0 (build 12278)

### Server information

10.13.2.3
Linux 5.10.0-26-amd64 #1 SMP Debian 5.10.197-1 (2023-09-29) x86_64

**Comment by michaelstingl** [comment]
5.x runs on Win10+. See docs:
- https://doc.owncloud.com/desktop/5.0/installing.html#system-requirements

**Comment by TheOneRing** [comment]
Windows 7 is not supported by us and Unsupported by Microsoft since 2020

**Comment by ask6483** [comment]
Find understand this but why client is not informing about its and is happily downloading new version?

**Comment by michaelstingl** [comment]
> Fine understand this but why client is not informing about this and happily downloading new version?

Fixed for macOS:
- https://github.com/owncloud/client/issues/11269#issuecomment-1759786494

Planned for Win:
- https://github.com/owncloud/client/issues/11328
