### ISSUE TITLE
Deprecate suffix vfs in 6.0

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11325]
- No longer provide suffix vfs in the wizard/folder wizard
- No longer allow to switch to vfs in "..." menu
- Add warning that suffix vfs will be removed without a migration path in 7.0. Recommend to switch to native files.

**Comment by HanaGemela** [comment]
Passed in ownCloud 6.0.0.12685-daily20231124, mac

**Comment by Salipa-Gurung** [comment]
### Desktop client version
ownCloud 6.0.0.12685-daily20231124 
Libraries Qt 6.6.0, OpenSSL 3.1.4 24 Oct 2023
Using virtual files plugin: suffix
OS: ubuntu-6.2.0-37-generic (build arch: x86_64, CPU arch: x86_64)
QPA: xcb


1. Suffix vfs not provided in the wizard :heavy_check_mark: 
![Screenshot from 2023-11-24 14-32-35](https://github.com/owncloud/client/assets/53458341/7feeeef1-c927-41c9-8061-4e745224ca93)

2. Switch to vfs not available in "..." menu :heavy_check_mark: 

| oc10 version 10.13.3 (stable) | ocis version 4.0.2 | 
|---|---|
| ![Screenshot from 2023-11-24 15-08-20](https://github.com/owncloud/client/assets/53458341/df699cac-6c2e-4ddd-a26e-9ecb793736e1) | ![Screenshot from 2023-11-24 15-11-46](https://github.com/owncloud/client/assets/53458341/d4dc6178-2490-4c79-a09d-cafe4f941991) |

3. Migration from desktop client version ownCloud 5.2.0.12684-daily20231124 to ownCloud 6.0.0.12685-daily20231124 with vfs enabled, warning is shown. :heavy_check_mark: 

| oc10 version 10.13.3 (stable) | ocis version 4.0.2 | 
|---|---|
| ![Screenshot from 2023-11-24 15-26-52](https://github.com/owncloud/client/assets/53458341/60b6eaf5-7ced-4334-a776-f02592abf82f) | ![Screenshot from 2023-11-24 15-21-33](https://github.com/owncloud/client/assets/53458341/638c04a2-6fd6-4dd2-8c01-66ed6cb2d69a) |
| ![Screenshot from 2023-11-24 15-27-27](https://github.com/owncloud/client/assets/53458341/b4e4bba5-fd34-4b25-8f4a-e22520297b13) | ![Screenshot from 2023-11-24 15-22-17](https://github.com/owncloud/client/assets/53458341/408c4653-4dd2-415c-9136-b59cceb3002d) |

**Comment by nagarindkx** [comment]
"No longer provide suffix vfs in the wizard/folder wizard" -> Does it mean the virtual filesystem be no longer exist?

**Comment by rijndael86** [comment]
so VFS was just removed without an alternative? I'm on linux and now I'm supposed to sync a multiple TB cloud without virtual files? is there really no alternative?

**Comment by mlazzarotto** [comment]
> If you need to use VFS from a new machine, you can install ownCloud-5.3.2.15463-arm64, connect to your server, activate VFS where you need it, and then install the last version. It displays warning but still has VFS activated (if you install directly the last version, it doesn't seems possible to use VFS at all)

So you're saying that updating the client to the latest version (where VFS was removed) won't delete the VFS capability on Mac?

**Comment by Surfict** [comment]
That was not my experience. It is not removed, it is hidden if you didn't activate it yet in older versions, so technically you can't activate it if you do not come from an older version where VFS was already activated. You can see it in the screenshot provided in the conversation : 

<img width="1360" height="615" alt="Image" src="https://github.com/user-attachments/assets/46a3ad14-9bca-4302-9fb5-780d22e5f263" />

It will removed for V7.0.
