### ISSUE TITLE
[5.1][win] Disabling VFS deletes the dehydrated files

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11331]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Disabling VFS deletes all the dehydrated files (files with cloud icon) but files that are already downloaded still do not get deleted. Files are also deleted from the server

### Expected behavior

Download the cloud files

### Steps to reproduce the issue

1. Upload some files and a folder with some files in it
2. Install client 5.1 (https://download.owncloud.com/desktop/ownCloud/testing/5.1.0.12543/win/)
3. Add account - VFS enabled
4. Open some files from file-manager
5. Disabled VFS in client (:x: dehydrated files get deleted)

### Screenshots

![Screenshot from 2023-11-03 14-19-20](https://github.com/owncloud/client/assets/52366632/13297187-9773-4d13-a4f2-adc9631c9c6a) | ![Screenshot from 2023-11-03 14-19-32](https://github.com/owncloud/client/assets/52366632/83829f1b-f4c0-4dbf-8acf-5c24ccee7ce9)
--|--

### Logs
[ownCloud.log](https://github.com/owncloud/client/files/13248298/ownCloud.log)

### Client version number

ownCloud 5.1.0.12543 [652b67](https://github.com/owncloud/client/commit/652b67d1e5915b6a736b5f5858e38589060ac929)
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: wincfapi
OS: windows-10.0.22621
QPA: windows

### Installation path (Windows only)

WIndows 11

**Comment by HanaGemela** [comment]
Passed in 5.1.1 rc1 win
