### ISSUE TITLE
How to install ownCloudcmd v5.0?

### ISSUE THREAD

**Issue by withit** [owncloud/client#11339]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

I can't see in the documentation how to install the cmd client on a headless ubuntu server (so no UI)

### Expected behavior

package ppa instructions per the desktop client, but for the cmd client

### Client version number

version 5.0, version 5.1

### Desktop environment (Linux only)

Ubuntu 22.04

### Server information

Server
version | 10.13.1.3
versionstring | 10.13.1

**Comment by michaelstingl** [comment]
You can install the cmd client using [packages](https://doc.owncloud.com/desktop/5.0/installing.html#native-installation) or with the [AppImage](https://doc.owncloud.com/desktop/5.0/installing.html#appimage)

Both can run without GUI:
- https://doc.owncloud.com/desktop/5.0/advanced_usage/command_line_client.html

**Comment by withit** [comment]
Except that the packages only install v2.6.3, and AppImage requires UI interaction on first run which isn't possible in a headless configuration.

**Comment by michaelstingl** [comment]
> Except that the packages only install v2.6.3,

Sounds like a bug. Please open new issues with the detailed steps you performed.

**Comment by fmoc** [comment]
> AppImage requires UI interaction on first run

Could you elaborate on that? AppImage as a technology does not require UI interaction. The ownCloud client itself does require a graphical environment to be able to launch. (There are workarounds available.)

**Comment by bitbacchus** [comment]
> > You can install the cmd client using [packages](https://doc.owncloud.com/desktop/5.0/installing.html#native-installation) or with the [AppImage](https://doc.owncloud.com/desktop/5.0/installing.html#appimage)
> 
> @michaelstingl How? I can't find any docs. Following the instructions at https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/ results in 2.6.3 being installed without `owncloudcmd`

I followed these instructions: https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/ and it worked for me.
