### ISSUE TITLE
Sharing option Download+View+Upload is missing

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#11333]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Seen with 4.1.0 and 5.0.0 (and probably more)

* Install Desktop client and shell integration plugins. (for nemo in my case)
* Right click on a synced folder, enter the ownCloud sub-menu, select Share ...
* Click 'Public', it shows three options, 
  - Download / View
  - Download / View / Edit
  - Upload only
* I'd like to offer some files to a (yet unknown) group of users, and want to allow them to also add files. But I don't want anonymous people to change or delete any files. That combination is missing. BAD

Expected behaviour:
* the desktop client's sharing options should be in sync with the sharing options of the web UI
* We should also have: Download / View / Upload

 
![grafik](https://github.com/owncloud/client/assets/1108546/11eacb0e-a70a-42f1-8fbc-8e197058ed8d)

### Expected behavior

.

### Client version number

.

**Comment by TheOneRing** [comment]
The sharing dialogue is considered deprecated and not longer maintained.
