### ISSUE TITLE
Crash in uninitialised vfs plugin

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/client#11348]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue
In windows 10
While upgrading desktop with VFS on from client version 2.5.4 to client version 5.1.1.12577-rc.1, client crashes.

### Steps to reproduce the issue

1. Install desktop client 2.5.4
2. Enable VFS
3. Sync some files 
4. Upgrade desktop client to 5.1.1.12577-rc.1 

### Screenshots

![Screenshot from 2023-11-08 16-49-38](https://github.com/owncloud/client/assets/53458341/163dd21f-637c-4c19-8560-9c88f52795e0)

Crash id: `1ecc82e3-daa4-4ea1-bc24-2319b62fc030`
[log10.10vfsOn.txt](https://github.com/owncloud/client/files/13296207/log10.10vfsOn.txt)

### Expected behavior

Client upgrade to 5.1.1.12577-rc.1 was expected. 

### Actual behavior

The client unexpectedly crashed.

**Comment by fmoc** [comment]
Corresponding stacktrace: https://owncloud.sentry.io/issues/4612889665/events/1ecc82e3daa44ea1bc242319b62fc030

**Comment by TheOneRing** [comment]
The scenario is unsupported, additionally it appears that an old 5.x profile is loaded after the upgrade from 2.5.
The stack trace makes no sense as the logged qfatal is the one manually triggered by starting the client with --debug and selecting `Crash now - qFatal` from the context menu.

**Comment by saw-jan** [comment]
Works fine with 5.0.0 release.
I will retest with clean setup and report the result here.

**Comment by saw-jan** [comment]
Client 5.1.1 crashes
Crash report `e21f71f8-6e9e-46cc-8201-5daf65da364d`

**Comment by TheOneRing** [comment]
We dropped support for the migration of very old legacy profiles in 5.0.
Directly upgrading from 2.5 to 5 is not supported and at least requires an update to 4 and then to 5.
What happened in the above logs is.
- 5.x was installed and a profile created
- 2.5 was installed created a legacy profiel
- 5.x was installed, it did not migrate the 2.5 profile but found the old 5.x profile and started
- Weird stuff happend

**Comment by TheOneRing** [comment]
While weird stuff was going on here it appears there was a crash introduced during refactoring,
Some old migration from suffix vfs to win vfs did not initialise the suffix vfs plugin.

**Comment by Salipa-Gurung** [comment]
With server : ownCloud 10.12.2 (stable)

1. Migration from 2.5.4 to 5.1.1 (just for confirmation though it is not supported) - client does not crash :heavy_check_mark: 
2. Migration from 2.10 to 5.1.1 works. :heavy_check_mark: 
3. Migration from 2.5.4 to 4.0.0 and then from 4.0.0 to 5.1.1 works. :heavy_check_mark:
