### ISSUE TITLE
client refuses to re-use existing sync folder connections

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#11344]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Seen with client 4.1.0.11250 on Linux Mint

I have three servers (damkencloud, cloud.owncloud, fablab cloud) conntected to my ownCloud client.
After upgrading to 4.1.0, I was surprised that the client starts empty. None of the three servers showed up any more.  Okayish. (Mabye that is intended, or necessary?)

* Connecting a server manually works, but the client suggests a different local sync folder.
  I want to re-use the original local folder, as the download is huge.
* In advanced settings, I can select the original folder, but the client refuses to accept the folder, as it "belongs to a sync connection". BAD
![grafik](https://github.com/owncloud/client/assets/1108546/fb48b32b-c1f5-4e49-9973-a9225b85f1d1)

----

* The message is correct. It belongs to a sync connection, and I want to re-activated this connection. There seems to be no way in the client to do so.

Workaround:
* go to the folder, `mv .sync_99e09106a2d1.db .sync_99e09106a2d1.db.old`
* this has the disadvantage, that all the selective sync settings need to be done again.

### Expected behavior

Message:
"This folder belongs to the sync connection with server XXXX"
Do you want to re-connect? Y/N

### Steps to reproduce the issue

not sure how to get into the initial state where the client does not automatically pick up the existing sync folder connections.

### Client version number

ownCloud 4.1.0.11250 [279a6f](https://github.com/owncloud/client/commit/279a6f3ff8ffc7138acee7b160ad9edab8f913bb)

### Desktop environment (Linux only)

Mint,  ubuntu 20.04

**Comment by TheOneRing** [comment]
https://doc.owncloud.com/desktop/5.0/faq.html#folder-is-used-in-a-folder-sync-connection
