### ISSUE TITLE
[QA] Win: No overlay icons when VFS is off

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11349]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Client 5.1.1 rc1
Windows 10

### Steps to reproduce the issue

1. Add an account with VFS off
2. Check the overlay icons in the file manager

### Screenshots

No screenshot

### Expected behavior

Overlay icons are shown

### Actual behavior

No overlay icons

**Comment by TheOneRing** [comment]
Can't reproduce.
