### ISSUE TITLE
Owncloud client deleted all files that were previously synced upon switching from VFS to selective sync

### ISSUE THREAD

**Issue by cdorn** [owncloud/client#11356]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Owncloud client deleted all files that were previously synced upon switching from VFS to selective sync. 
Seems like a regression bug of: https://owncloud.com/news/important-windows-client-issue-fix-available/

Upon install of new client on new machine with win 11, I initially selected VFS and then switched to selective sync to only sync those folders that I'm interest in.

### Expected behavior

Switching between VFS and selective sync should not remove any files.

### Steps to reproduce the issue

I dont want to replicate this as loss of data is not acceptable.
What I did was:

- Install client fresh
- Setup with Virtual File System support
- Connect to ownCloud server
- Switch to Selective Sync
- Select folders for synchronization
- Files get deleted, only synchonized folders remain (but without any files in them)

### Client version number

ownCloud 5.0.0.12278 8f9152
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: wincfapi
OS: windows-10.0.22621
WPA: windows

### Installation path (Windows only)

C:\Program Files\ownCloud

### Server information

[Custom Cloud - Custom Claim ](https://owncloud.org/)10.3.2 (stable)

**Comment by michaelstingl** [comment]
Fix included in the 5.2 release:
https://github.com/owncloud/client/releases/tag/v5.2.0
