### ISSUE TITLE
Folder Sync Selection Tree Collapses every few seconds

### ISSUE THREAD

**Issue by eliaswendt** [owncloud/client#11357]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

While selecting folders for sync, the tree view completely collapses (also all sub-folders) every few seconds. This happens both when actively selecting folder checkboxes, but also when not clicking anything (except the folder expansion arrows).

### Expected behavior

The folder tree should stay expanded until applying the changes (or even staying open after that).

### Client version number

ownCloud 5.0.0.12278 [8f9152](https://github.com/owncloud/client/commit/8f9152e5eb6fde81a1a1ba889ee03df2e3e9445c)
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: suffix
OS: macos-23.1.0
QPA: cocoa

### Server information

status.php
```
{
    "installed": true,
    "maintenance": false,
    "needsDbUpgrade": false,
    "version": "10.11.0.0",
    "versionstring": "10.11.0",
    "edition": "Community",
    "productname": "Infinite Scale",
    "product": "Infinite Scale",
    "productversion": "4.0.2"
}
```

### Additional context

Note that I am using OCIS 😊

**Comment by eliaswendt** [comment]
Still relevant

**Comment by eliaswendt** [comment]
<removing stale label>

**Comment by saw-jan** [comment]
Tested on `ownCloud 6.0.0.13589-daily20240328 [32670a]`
Different view is implemented for sync selection where folder tree doesn't collapse
 
![Screenshot from 2024-03-28 14-57-58](https://github.com/owncloud/client/assets/52366632/8f7da1fc-d542-4391-af74-89d4550d30aa)
