### ISSUE TITLE
Client crashes when adding ocis account (Debian12/Fedora38)

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11358]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Desktop client crashes when adding ocis account

Observed in `Debian12` and `Fedora38` :x:
Works on `Ubuntu22.04` :heavy_check_mark: 

What happens:
1. Adding ocis account
2. Re-open the client - ocis account is logged out
3. Relogin ocis account syncs files and doesn't crash

### Expected behavior

Adding both server accounts should work

### Steps to reproduce the issue

1. Install client (5.1.1)
2. Add ocis account - crashes after a while

### Logs

Crash id: `be8ecc56-295c-4e41-ba0a-d6bdfdc7fb47`
[crashlog.txt](https://github.com/owncloud/client/files/13318278/crashlog.txt)

### Client version number

ownCloud ownCloud 5.1.1.12592 https://github.com/owncloud/client/commit/0d41a9bbf2ec2227bc71f9c539a02140edc41f68
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: suffix
OS: ubuntu-6.2.0-35-generic
QPA: xcb

### Server information
`oCIS 4.0.2`

**Comment by TheOneRing** [comment]
```
11-10 02:50:59:186 [ warning sync.database.sql ]:	Sqlite prepare statement error: 1 "no such table: version" in "SELECT major, minor, patch FROM version;"
23-11-10 02:50:59:186 [ fatal default ]:	ENFORCE: "allow_failure" in file /drone/src/src/linux-64-gcc/ownCloud-5.1.1.12592/src/common/ownsql.cpp, line 292 int OCC::SqlQuery::prepare(const QByteArray&, bool) with message: SQLITE Prepare error
```
I'd guess your disk is full.

**Comment by michaelstingl** [comment]
> I'd guess your disk is full.

How the disk got full? ownCloud data? Detailed steps to reproduce?

**Comment by saw-jan** [comment]
My VM has enough free space though. And the servers has only few Mbs of files

![Screenshot from 2023-11-10 14-38-54](https://github.com/owncloud/client/assets/52366632/ee196201-4f7f-476e-bea3-b4180bda35c5)

**Comment by saw-jan** [comment]
Appimage also crashes on same scenario
Crash id: `98efcde3-48f4-4a2c-aa4d-745ad1ca0da0`

**Comment by saw-jan** [comment]
Tested with `ownCloud 5.1.2.12600 [9a0beb]`
Debian :heavy_check_mark: 
Fedora :heavy_check_mark: 
Ubuntu :heavy_check_mark:
