### ISSUE TITLE
Move to next input when pressing Enter

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#11362]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

In the basic auth dialog, when hitting enter in the username input field, the cursor should be moved to the password input field.

### Proposed solution

Plain an simple, see above.

**Comment by TheOneRing** [comment]
Not planned.
On Windows and Linux user should use tab.
On mac... the mouse.
