### ISSUE TITLE
Renames to new folders result in a new folder and the download of the old folder

### ISSUE THREAD

**Issue by Ishan-Kaura** [owncloud/client#11369]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

[When you rename a folder in the Own Cloud desktop application, it creates a new folder with the same name instead of renaming the existing one. We are using 4.2.0.11670 desktop version](https://central.owncloud.org/t/when-you-rename-a-folder-in-the-own-cloud-desktop-application-it-creates-a-new-folder-with-the-same-name-instead-of-renaming-the-existing-one-we-are-using-4-2-0-11670-desktop-version/45764)

### Expected behavior

It should be renamed that folder instead of creating a new one with the same name.

### Steps to reproduce the issue

Create a folder name (Apple) on desktop.
Rename that folder name from Apple to AppleNew
It is creating a new folder with the name AppleNew, it should be rename that Apple folder to AppleNew.

### Screenshots

![image](https://github.com/owncloud/client/assets/150885970/45171ffa-3c0e-44a9-9f5c-2799f96f2437)

### Client version number

4.2.0.11670

**Comment by TheOneRing** [comment]
Please provide log with http logs enabled. https://doc.owncloud.com/desktop/next/appendices/troubleshooting.html#logging-to-a-temporary-directory

**Comment by TheOneRing** [comment]
Reproduced:
When renaming a folder before its sync was completed can result in the behaviour.

**Comment by TheOneRing** [comment]
@Ishan-Kaura now that https://github.com/owncloud/client/pull/11347 is merged can you give it another try with tomorrows 6.0 nightly?
I'd recommend to use the testpilotclient https://download.owncloud.com/desktop/testpilotcloud/daily/6.0/ .
(Donwgrades are not supported and testpilotcloud won't modify your productive setup)
