### ISSUE TITLE
Automate ansible steps for the update server tests

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11375]
Please add the ansible step into drone so that when a PR gets merged the changes are automatically deployed

**Comment by fmoc** [comment]
There is no point in creating issues in this repository for internal repositories that actually have their own issue tracker...

**Comment by HanaGemela** [comment]
If you track also another repositories and schedule them in sprint planning, you can close it.

**Comment by fmoc** [comment]
We usually track these using draft items or enterprise tickets. I already had created a draft item on the board. Closing.
