### ISSUE TITLE
Moving files to trash option has no effect if server-side quota is exceeded

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#11377]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When the server-side quota is exceeded, files are deleted normally on the client and not moved to the trash bin even though the box was checked in the settings.

### Expected behavior

If this option is enabled, files must not just be deleted but always moved to the client side. Server-side quota should have no influence on this at all.

### Steps to reproduce the issue

0. Make sure to have a file synced both on server and client.
1. Change quota for user on the server to a very small value (e.g., 1 M) and make sure the server displays "quota exceeded".
2. Force sync
3. Delete file on the server
4. Check trash bin to make sure it's not there

### Client version number

6.0.0.12640-daily20231117 on Windows 11.

### Server information

Tested against https://demo.owncloud.org.

**Comment by erikjv** [comment]
Placeholders are removed, hydrated files are moved to the trash. Tested on win10. 

@fmoc Can you make sure that the files were hydrated before removing them on the server?

**Comment by erikjv** [comment]
@TheOneRing Is this the expected/desired behaviour? Should we make it clearer by somehow adding "fully downloaded files" to the label?

**Comment by fmoc** [comment]
> Can you make sure that the files were hydrated before removing them on the server?

I did. Let me retry, though.
