### ISSUE TITLE
If a folder name is renamed with a dot at the end in the web app, the desktop app will remove the folder from the desktop

### ISSUE THREAD

**Issue by Ishan-Kaura** [owncloud/client#11370]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

If a folder name is renamed with a dot at the end in the web app, the desktop app will remove the folder from the desktop

### Expected behavior

If a folder name is renamed with a dot at the end in the web app, it must renamed in the desktop app.

### Steps to reproduce the issue

Create a folder name (Apple) on desktop
Rename that folder name from Apple to Apple.(dot)
Currently it is removing from the desktop

### Client version number

Desktop version 4.2.0.11670

**Comment by TheOneRing** [comment]
When renamed to "name." the client can't sync it to Windows.
This means that the rename results in the deletion of the original "name"
Once a platform compatible name is used again the folder will be synced again.
