### ISSUE TITLE
Add branding option to hide the trash bin feature

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11378]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

https://github.com/owncloud/client/issues/9001 has to have a branding option to hide it

### Proposed solution

Add another checkbox to ownbrander

**Comment by saw-jan** [comment]
How can I confirm the fix? Need steps.
CC @erikjv @TheOneRing @HanaGemela

**Comment by TheOneRing** [comment]
For testing add
```
bool enableMoveToTrash() const
{
    return false;
}

```
To a theme or change it for a local build.
If the feature is disabled, the setting should not appear and the trash bin must not be used.

**Comment by HanaGemela** [comment]
<img width="1414" alt="Screenshot 2024-01-09 at 13 05 58" src="https://github.com/owncloud/client/assets/49001702/c04a8d1b-3b57-48ab-8263-870f99488ddb">

ownCloud 6.0.0.13051-daily20240106 [a8d75a](https://github.com/owncloud/client/commit/a8d75a2da49617b5a732500bd6a9d6fdfee0f6d7)
Libraries Qt 6.6.0, OpenSSL 3.1.4 24 Oct 2023
Using virtual files plugin: suffix
OS: macos-22.6.0 (build arch: x86_64, CPU arch: x86_64)
QPA: cocoa

on the left. And then cactus on the right built without the trash bin feature

cactus 6.0.0.13073-daily20240109 [e073ea](https://github.com/owncloud/client/commit/e073eaafa009ab4ae31b45bbe7147444bb50f5f5)
Libraries Qt 6.6.0, OpenSSL 3.1.4 24 Oct 2023
Using virtual files plugin: suffix
OS: macos-22.6.0 (build arch: x86_64, CPU arch: x86_64)
QPA: cocoa

✅
