### ISSUE TITLE
OwnCloud desktop app does not support folder names ending with a dot

### ISSUE THREAD

**Issue by Ishan-Kaura** [owncloud/client#11372]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Own Cloud desktop app does not support folder names ending with a dot, whereas the web application of Own Cloud allows folder names to end with a dot, which is causing synchronization issues in the desktop app.

### Expected behavior

For the desktop version, it also allows the folder names to end with a dot.

### Steps to reproduce the issue

Login in the desktop version and rename any folder with the end of the dot, it is not reflecting it. 

### Client version number

ownCloud: 10.13.2

**Comment by TheOneRing** [comment]
Its a Windows that doesn't allow folders ending with a dot.
