### ISSUE TITLE
When files are uploaded from the local system, the last modified date used is from the local system, not the upload date.

### ISSUE THREAD

**Issue by Ishan-Kaura** [owncloud/client#11371]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When files are uploaded from the local system, the last modified date used is from the local system, not the upload date.

### Expected behavior

OwnCloud uses the uploaded date time instead of the last modified date for files/folders.

### Client version number

ownCloud: 10.13.2

**Comment by michaelstingl** [comment]
This is a feature, not a bug. Works as designed.
