### ISSUE TITLE
Running as a different user (gksudo)

### ISSUE THREAD

**Issue by MetaChrome** [owncloud/client#1138]
The expected behavior is that it is possible (and implemented as a function of the software if there is further complexity to facilitating this) to fully run the client as an arbitrary user seperate from the logged in user. 

It is critical to be able to disable owncloud client from access to the sync folder using chown. 

A practical immediate reason being that I wish to place it's folder in an encrypted container and disallow access when the container isn't mounted by changing the unmounted path to an inaccessible user.

What occurs:

To run as a different user:

    xhost +SI:localuser:owncloud
    gksudo -u owncloud owncloud

The problem is that on the first run it specifies that owncloud requires a system tray paraphrased here:

ownCloud requires a working system tray. Please install a system tray application such as trayer. If you are running xfce follow these instructions: http://docs.xfce.org/xfce/xfce4-panel/systray

But still offers the configuration wizard. In future runs the wizard appears to fail to run. In either case it's not a particular issue as the client can be manually configured.

Either way the system tray is not functional and the behavior is undefined in general though it appear syncing works as the client is a fairly simple program. As the complexity grows, please facilitate this workflow in the architecture or specify a workflow to facilitate the entire spectrum of said functionality.

**Comment by ogoffart** [comment]
Closing old issue.
Running owncloud as a different user is not something we want to support officialy (altough i do it all the time for testing purposes and it works good enough)
