### ISSUE TITLE
Linux Download page does not work for LinuxMint

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#11383]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Our download page currently offers
Debian, Fedora, openSUSE, Ubuntu.

Linux Mint users probably choose Ubuntu, bechause Mint is based on Ubuntu.
The next challenge is then to identify the correct Ubuntu version.
E.g.
- for Linux Mint 20.3 (Una) the correct Ubuntu version is 20.04 (focal)
- for Linux Mint 21.2 (Virtoria) the correct Ubuntu version is 22.04 (jammy)

/etc/os-release has the Ubuntu codename, but not the version number:

![grafik](https://github.com/owncloud/client/assets/1108546/de190dcc-9e9d-4ae6-acd4-54a3147bead4)

Knowing the Ubuntu Codename does not help with our download page:
* The text on the download page needs the ubuntu version number
* The Installer scripts check /etc/os-release, but also only the version numbers.

Possible improvements
* Add LinuxMint as a separate icon next to Ubuntu, and allow to choose by Mint version numbers (and also codenames)
* Improve the text on the ubuntu download instruction page to also list Linux Mint version numbers (and codenames)
* Build one installer script, that works for all linux distros

### Expected behavior

.

### Client version number

latest

**Comment by michaelstingl** [comment]
@jnweiger thanks for your suggestions. LinuxMint is currently not a supported platform. We could discuss at PB1, Tuesday 10 AM (`#concepts`)
