### ISSUE TITLE
[QA] Remove/adjust suffix vfs related GUI tests

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11393]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Suffix vfs is deprecated with https://github.com/owncloud/client/pull/11365 and the GUI tests are failing. We need to remove the tests related to VFS.

Builds: https://drone.owncloud.com/owncloud/client/17118
Report: https://cache.owncloud.com/public/owncloud/client/17118/oc10/guiReportUpload/index.html

**Comment by Salipa-Gurung** [comment]
https://github.com/owncloud/client/pull/11394#issue-2007487994
