### ISSUE TITLE
Ubuntu 20.04 and 22.04 packages report needing 300GB of disk space to install

### ISSUE THREAD

**Issue by natesdot** [owncloud/client#11402]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Perhaps just a bad metadata in the package, as the package does not require this much space

$ apt-cache show owncloud-client
Package: owncloud-client
Status: install ok installed
Priority: standard
Section: devel
**Installed-Size: 344243626**
Maintainer: Fabian Müller <fmueller@owncloud.com>
Architecture: amd64
Version: 5.2.0.12726
Replaces: libowncloudsync0, owncloud-client-cmd, owncloud-client-data
Depends: libgl1, libopengl0, libglx0
Suggests: owncloud-client-dolphin, owncloud-client-nautilus, owncloud-client-nemo, owncloud-client-caja
Conflicts: libowncloudsync0, owncloud-client-cmd, owncloud-client-data
Conffiles:
 /etc/owncloud-client/sync-exclude.lst 3f0a4de3f1b450ef1f614e8b125ac288 obsolete
Description: ownCloud Desktop Client
Description-md5: 440f6bf505f96c70abe5bb2b283e90ee
Homepage: https://github.com/owncloud/client
Built-Using: linuxdeploy-plugin-native_packages

apt-get -y install owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
[snip listing of a bunch of unrelated packages]
Use 'sudo apt autoremove' to remove them.
Suggested packages:
  owncloud-client-dolphin owncloud-client-nautilus owncloud-client-nemo owncloud-client-caja
The following packages will be REMOVED:
  libowncloudsync0
The following packages will be upgraded:
  owncloud-client
1 upgraded, 0 newly installed, 1 to remove and 91 not upgraded.
Need to get 36.5 MB of archives.
After this operation, **353 GB of additional disk space will be used.**

### Expected behavior

I expect it to show a regular amount of disk space required (seems to be just a few MB)

### Steps to reproduce the issue

Followed the guide here https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/

### Client version number

5.2.0.12726

### Desktop environment (Linux only)

Linux Mint 20

### Client package version and origin (Linux only)

installed 

### Server information

(Issue is package only, not related to server anything)

### Additional context

I don't use github very much so may not see replies, this isn't a critical issue for me of course but of all of the Debian packages I have used over the last 25 years I thought this was a really unique situation. Originally encountered when I installed the Ubuntu 22.04 packages on Linux Mint 20 (which is based on Ubuntu 20), though the packages worked fine, later, just in case, I deleted the 22.04 packages and installed the 20.04 packages just to see if it would change, but it did not.

**Comment by fmoc** [comment]
Apparently, this was a bug upstream. It was fixed this morning. It should be fixed in future builds. We'll reopen in case it'll happen again.

**Comment by TheOneRing** [comment]
Future=6.0 builds

**Comment by thomaswasle** [comment]
The issue occurs again in ubuntu 23.10 following the guide [https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/](url)

**Comment by michaelstingl** [comment]
@thomaswasle check 6.0 pre-release builds:
- https://download.owncloud.com/desktop/ownCloud/daily/6.0/linux/download/
