### ISSUE TITLE
Another unreadable error message

### ISSUE THREAD

**Issue by erikjv** [owncloud/client#11412]
After fixing issue #11243 , we found three more places with styled error messages. Two are in legacy dialogs (and accidentally are actually readable), but the third is a problem. This is in the `folderwizardtargetpage.ui`:

<img width="503" alt="Screenshot 2023-11-30 at 18 12 09" src="https://github.com/owncloud/client/assets/151956/f01f529a-ac9e-4fc7-acbd-bf93f2a9e3e4">

It is the selected label which reads "Placeholder text", a white text on a yellow background.

One way to fix this is to do the same as in the log browser UI:

<img width="588" alt="Screenshot 2023-11-30 at 18 09 13" src="https://github.com/owncloud/client/assets/151956/4cb509cb-3a17-4127-851a-0a60d5916b29">

The question is if we want the red text or un-styled text, and if the latter is the case, if we want to change the log browser UI too.

**Comment by TheOneRing** [comment]
![image](https://github.com/owncloud/client/assets/200626/4ca9c5a4-293b-4ffa-924c-540dcaa81db1)

**Comment by saw-jan** [comment]
Tested on `ownCloud 6.0.0.13582-daily20240327 [4258b6]`

![Screenshot from 2024-03-28 15-40-51](https://github.com/owncloud/client/assets/52366632/99ae7c2e-a2fe-4cee-9988-e23f14593d76) | ![Screenshot from 2024-03-28 15-42-16](https://github.com/owncloud/client/assets/52366632/14d2c7eb-ca50-4b2a-948a-211032648d85)
--|--
![Screenshot from 2024-03-28 15-47-13](https://github.com/owncloud/client/assets/52366632/41242606-967e-4fcb-954f-96aa2c72c31f)
