### ISSUE TITLE
Owncloud client not working anymore after server update to 10.13.3 / Version number chaos

### ISSUE THREAD

**Issue by n0valis** [owncloud/client#11422]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Unsupported client Version after Server update to 10.13

### Expected behavior

supported client Version after Server update to 10.13

### Steps to reproduce the issue

Server update to 10.13

### Client version number

Here it becomes interessting
https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/
says Debian_12 owncloud-client-5.2.0.12726
Owncloud client after installation (after done from description above) says it's 2.11.0

### Desktop environment (Linux only)

Linux Mint DE 6

### Client package version and origin (Linux only)

from https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/

### Server information

10.13.3 (stable)
on Debian 11
php 7.4.33

### Additional context

Particulaly interessted in this odd Version irritation. Why are you talking about  owncloud-client-5.2.0.12726 on your website though it actually is 2.11
So there is no update to the client as of now.
When can we expect to use the client again? Would like to access my files if possible. Just asking.

**Comment by michaelstingl** [comment]
ARM CPU? ownCloud currently only supports x86-64
- https://doc.owncloud.com/desktop/5.2/installing.html#system-requirements
