### ISSUE TITLE
Handle server error in setup wizard

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11424]
https://github.com/owncloud/client/blob/d452430b3b61448a34d1f4c62251859f6d5bd23d/src/gui/owncloudgui.cpp#L855

The current code just ignores errors.

**Comment by saw-jan** [comment]
Any way we can confirm this?
CC @TheOneRing

**Comment by TheOneRing** [comment]
I modified the user agent to report a 2.0 client. Which causes the server to block the client.

**Comment by saw-jan** [comment]
Any steps that we can test it?
Or we can move it to the Done if you have done already

**Comment by TheOneRing** [comment]
Lets move it to done
