### ISSUE TITLE
fading out of space notification fails

### ISSUE THREAD

**Issue by thommierother** [owncloud/client#11429]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

client is connected to ocis 4.x. The UI notification that the user has been added to a new space can not be faded out

### Expected behavior

fading out of notification

### Steps to reproduce the issue

- ocis 4.x as backend
- client  Release v5.2.0 on linux as sync client (openSUSE Tumbleweed)
- create space and add user
- user side: client displays notification
- user has read the nitification and wanbts to close it
- this fails

### Screenshots

![20231211_073613](https://github.com/owncloud/client/assets/6594120/c2c32433-2843-412e-9327-0849ebf4fce6)

### Logs

-

### Client version number

Release 5.2

### Desktop environment (Linux only)

openSUSE Tumbleweed

### Client package version and origin (Linux only)

client installed fron download.owncloud.com repo

### Server information

OCIS 4 stable

**Comment by thommierother** [comment]
![20231211_074824](https://github.com/owncloud/client/assets/6594120/2c4243cd-b9a9-4291-82e6-5a4d01e3ee65)

error msg in UI "fehlgeschlagen"

**Comment by michaelstingl** [comment]
Known limitation:
- https://github.com/owncloud/ocis/issues/5675#issuecomment-1462494513

**Comment by michaelstingl** [comment]
![CleanShot 2023-12-11 at 11 34 20](https://github.com/owncloud/client/assets/214010/7e703102-e498-456f-a14c-49235a4c67ff)

**Comment by thommierother** [comment]
ok Means, currently the notification can only be accepted/confirmed from the WEB UI, but not from the sync client UI. Correct?

**Comment by michaelstingl** [comment]
Exactly. Can't be accepted because of:
- https://github.com/owncloud/ocis/issues/6256

Can't be dismissed because of:
- https://github.com/owncloud/ocis/issues/5675#issuecomment-1462494513

oCIS backend implementation was inspired from oC10, but not fully compatible, so client support has known limitations.
