### ISSUE TITLE
[QA] Notification shown even though no changes occurred 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11438]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Notification shown even though no changes occurred 
windows
owncloud 6.0.0 alpha 1

### Steps to reproduce the issue

1. Turn VFS on
2. Have a folder with two files - one is Available on this device and the second Available when online
3. VFS off
4. Turn quickly VFS on before the second file gets downloaded

### Screenshots

No screenshot

### Expected behavior

No notification as nothing has changed 

### Actual behavior

Notification that the second file has been added

**Comment by TheOneRing** [comment]
I'd guess you were not fast enough and the file was actually downloaded?
If it's the notification about a created placeholder, switching it off removes the placeholder, switching it on recreates it and issues a notification.

**Comment by HanaGemela** [comment]
Oh, you're right. Placeholder gets removed when VFS is turned off. And added when on. But still, should there be a notification when "nothing" actually changed?

**Comment by TheOneRing** [comment]
Well technically something changed 😁
