### ISSUE TITLE
[QA] Crash during login 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11433]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

ownCloud 6.0.0 alpha.1, win
Crash: e4b4da91-9aa5-4342-a978-564baab08ad4
Logs: https://cloud.owncloud.com/f/6148010

### Steps to reproduce the issue

Not sure, it happened after login 

### Screenshots

No screenshot

**Comment by TheOneRing** [comment]
Can't reproduce
