### ISSUE TITLE
[QA] Awaiting sync & Aborted at the same time

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#11435]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

ownCloud 6.0.0 alpha.1, win
The client is in Awaiting sync & Aborted state at the same time
Waiting already more than 5 minutes and it still hasn't recovered 
Logs: https://cloud.owncloud.com/f/6148026

### Steps to reproduce the issue

Not sure, I've just unpaused the sync

### Screenshots

<img width="756" alt="Screenshot 2023-12-12 at 11 26 49" src="https://github.com/owncloud/client/assets/49001702/be3c3230-c1c0-41fb-9615-4547aa9169d4">

### Expected behavior

The client starts syncing after unpausing 

### Actual behavior

The sync is still aborted

**Comment by HanaGemela** [comment]
@TheOneRing I've added another log from today when it happened again. I still can't reproduce reliably but it's when switching VFS on and off

**Comment by HanaGemela** [comment]
I've added a log called Third occurrence - this time I've had just Awaiting sync for some time, eventually the client got disconnected, tried to Connect back but never recovered from this state. I've seen that the client disconnected many times during testing but sure, I can't rely on the VM..

**Comment by TheOneRing** [comment]
Can't reproduce.
Yes, I get the abort message, which is expected, but it recovers a few seconds later.

**Comment by TheOneRing** [comment]
From the logs I can only tell that you also had a timeout during the test.
