### ISSUE TITLE
Client no longer able to sync files with the server  (Arch Linux)

### ISSUE THREAD

**Issue by mikpom** [owncloud/client#11440]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

My ownCloud client on Arch Linux stopped syncing completely presumable after system update. I run my own server. Everything is fine from ubuntu owncloud clients I have on different devices.

`Activity-> Sync protocol` and `Not synced` are suspiciously blank while the client seems to be connected. (see the screenshot).

### Expected behavior

File should be synced.

### Screenshots

![Screenshot from 2023-12-15 10-08-29](https://github.com/owncloud/client/assets/11643719/14834843-e519-447f-8461-c24e63b311e9)

### Logs

Client logs collected with `owncloud --debug -s --logfile - > owncloud.log` : https://pastebin.com/2rgrkVBh

### Client version number

owncloud-client 5.2.0

### Desktop environment (Linux only)

ArchLinux 6.6.6-zen1-1-zen with Gnome 45.2-1

### Server information

ownCloud 10.7.0 Ubuntu 20.04.6 PHP 7.4.3

**Comment by mikpom** [comment]
Update: looks like my local client lost sync connection. So I added a new connection to arbitrary `~/ownCloud2` folder instead of my original `~/ownCloud` and the client started syncing the contents from the server to this new folder.

At the same time I can't add connection to the original `~/ownCloud` directory as the client states there is already a connection to it.

**Comment by michaelstingl** [comment]
Duplicate for:
- https://github.com/owncloud/client/issues/11411
