### ISSUE TITLE
[5.2] Client crashed in OCC::SyncEngine::slotPropagationFinished at `syncengine.cpp:705`

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11453]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Desktop client crashed in `OCC::SyncEngine::slotPropagationFinished` at `syncengine.cpp:705`

Build: https://drone.owncloud.com/owncloud/client/17367/4/4

```c
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f87cfcdc844 in __pthread_kill_implementation () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f87cc5fbf00 (LWP 4925))]
#0  0x00007f87cfcdc844 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007f87cfc8babe in raise () at /lib64/libc.so.6
#2  0x00007f87cfc7490f in abort () at /lib64/libc.so.6
#3  0x00007f87d02580eb in qgetenv(char const*) [clone .cold] () at /lib64/libQt6Core.so.6
#4  0x00007f87d0258b7f in  () at /lib64/libQt6Core.so.6
#5  0x00007f87d1433fc0 in __OC_ENSURE(bool, char const*, char const*, int, char const*) (condition=false, cond=0x7f87d146a593 "isOpen()", file=0x7f87d1467af5 "/drone/src/src/common/syncjournaldb.cpp", line=2331, info=0x7f87d146a59c "const QVector<SyncJournalFileRecord> OCC::SyncJournalDb::getFileRecordsWithDirtyPlaceholders() const") at /drone/src/src/common/asserts.h:43
#6  0x00007f87d142ff83 in OCC::SyncJournalDb::getFileRecordsWithDirtyPlaceholders() const (this=0x2ad6710) at /drone/src/src/common/syncjournaldb.cpp:2331
        locker = {m_mutex = 0x2ad6770, m_isLocked = true}
#7  0x00007f87d1ee79f9 in OCC::SyncEngine::slotPropagationFinished(bool) (this=0x7f877400c340, success=true) at /drone/src/src/libsync/syncengine.cpp:705
```

### Logs
[stacktrace.log](https://github.com/owncloud/client/files/13783203/stacktrace.2.log)
[clientlog.log](https://github.com/owncloud/client/files/13783205/serverlog.log)

### Client version number

client build from `5` branch (5.2.0)

### Server information

ocis:4

**Comment by TheOneRing** [comment]
Somehow, the db was not yet open.
Do you have steps to reproduce?

**Comment by TheOneRing** [comment]
Uh looks like a sync was running while the account/sync was removed?

**Comment by saw-jan** [comment]
> Do you have steps to reproduce?

it's from GUI test run. Could be due to race condition in somewhere with something

**Comment by saw-jan** [comment]
Haven't seen this recently. so I will keep this closed
