### ISSUE TITLE
[6.0] "Copy public link to clipboard" context menu item with oCIS

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#11450]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Desktop client connected with oCIS shows "Copy public link to clipboard" context menu item.

### Expected behavior

Desktop client doesn't support oCIS Sharing, so this menu entry shouldn't be there.

### Screenshots

![CleanShot 2023-12-21 at 13 33 50@2x](https://github.com/owncloud/client/assets/214010/b9f53877-bac6-41a1-b29e-b936ea7e740e)

### Client version number

```
testpilotcloud 6.0.0.12868-alpha.1 7aea4b
Libraries Qt 6.6.0, OpenSSL 3.1.4 24 Oct 2023
Using virtual files plugin: suffix
OS: macos-23.2.0 (build arch: arm64, CPU arch: arm64)
QPA: cocoa
```

### Server information

https://ocis.ocis-traefik.latest.owncloud.works
```
[Log]  ownCloud Web UI 8.0.0-alpha.12  (index.html-j_RvZHve.mjs, line 1)
[Log]  Infinite Scale 5.0.0-alpha.5+71f7c1e73 Community  (index.html-j_RvZHve.mjs, line 1)
```

**Comment by TheOneRing** [comment]
Can't reproduce

**Comment by saw-jan** [comment]
Tested on `ownCloud 6.0.0.13582-daily20240327 [4258b6]` (Windows and Linux)

:exclamation: The `Copy public link to clipboard` item exists. Opens the sharing in the browser (expected to have the item?)

![Screenshot from 2024-03-28 15-34-31](https://github.com/owncloud/client/assets/52366632/80e73cf0-1fd3-4ac5-b1cd-0fc1c6d45ff0)


CC @TheOneRing

**Comment by saw-jan** [comment]
Tested with `ownCloud 6.0.0.14185-daily20240710 [a947c5]`
