### ISSUE TITLE
ownCloud Desktop Mac Always Paused

### ISSUE THREAD

**Issue by codepoet80** [owncloud/client#11464]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

After signing into my account, ownCloud works for 3-4 boots, then always and only ever stays "Paused" when started. The icon in the toolbar shows the Paused icon, but no errors are reported. When I "Show ownCloud" it says that its connected to my server in the Account tab. In the Activity tab, it shows recent activity, but will not sync. "Force Sync Now" is not available anywhere in the UI.
Sync will not resume until I remove the account, then re-add it, at which point the loops starts again (works 3-4 times, then stays Paused.)
The logs show no errors (that I can see).

### Expected behavior

ownCloud shouldn't start Paused. If Paused, a user should be able to resume syncing. 

### Steps to reproduce the issue

1. Install ownCloud Desktop
2. Sign in to account
3. Observe that ownCloud Desktop syncs normally
4. Reboot (x3)
5. Observe that ownCloud Desktop is Paused
6. Look for a way to un-Pause
7. Determine that there is no way to un-Pause
8. Remove the account (not just sign out)
9. Sign back into account
10. Repeat 3-10

### Screenshots

![Screen Shot 2024-01-07 at 2 00 48 PM](https://github.com/owncloud/client/assets/16038880/d6e5e4ea-867a-4c47-b1ba-0bba1b9c1be5)

### Logs

[ownCloud.log](https://github.com/owncloud/client/files/13854620/ownCloud.log)

### Client version number

5.2.1.13040 979bb9 Mac
Qt 6.4.3
OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: suffix
OS: macos-21.6.0
QPA: cocoa

### Server information

ownCloud 10.13.4 (stable), via Docker on macOS Monterey

### Additional context

Not having this issue on other client machines (Windows 10, Ubuntu 22.04.3, macOS Catalina)

Please help!

**Comment by michaelstingl** [comment]
Looks like your sync connections disappeared. This was reported before:
- https://github.com/owncloud/client/issues/11411
- https://github.com/owncloud/client/issues/11455

Workaround:
- https://github.com/owncloud/client/issues/11455#issuecomment-1873849100

An improvement was made in the 5.2.1 release:
- https://github.com/owncloud/client/pull/11413

Question would be, did this happen before or after upgrading to 5.2.1?

**Comment by codepoet80** [comment]
Thanks for the reply. Yes this has been happening with all 5.x versions.
Tried to follow the work-around in the comment, but don't know where the equivalent files are on macOS -- any tips?

**Comment by michaelstingl** [comment]
> but don't know where the equivalent files are on macOS -- any tips?

Check docs:
https://doc.owncloud.com/desktop/5.2/advanced_usage/configuration_file.html#location-of-the-configuration-file

**Comment by codepoet80** [comment]
The backup was also missing the account info, so I had to remove then re-add the account. I've made my own backup of a working .cfg so if it goes missing again, I'll be able to paste the dropped lines back into place, per the work-around.

I'll close this Issue, since its a dupe, and I can live with work-arounds on this particular machine. However, it would be nice to have it fixed in the app itself. Since this happens on this machine repeatedly, I'm happy to capture any additional logs you need to hunt this down.

Thanks for your help!

**Comment by codepoet80** [comment]
I have not seen this issue re-occur in the last 2 weeks.
