### ISSUE TITLE
Include update information in about dialog (Move from settings to about).

### ISSUE THREAD

**Issue by rpausch-owncloud** [owncloud/client#11486]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Currently only the current version is displayed in the about dialog. User has no information if this is the latest or not and if they have to update or not. In order to get this information user has to scroll down in the client GUI where the information is displayed as well as the update button if applicable. For dummy users like me this is very uncommon and therfore they won't find that update button.

### Proposed solution

In additon to the version number display if this is the latest. If not display an update button or update automatically if automatic updates are enabled. See examples from Firefox and Chrome.
![297787203-667ee75e-2148-402d-95c3-bb247a432cb9](https://github.com/owncloud/client/assets/144467728/cdc79cb7-d00b-43ab-8bff-da4c2d404cfa)

![297787505-666bc42f-8b5b-4da7-9eef-7af459dc2c12](https://github.com/owncloud/client/assets/144467728/6dbdd58d-735f-41a1-8d81-1ffc347534e6)

![297787746-5293bbf0-1b2e-4aa4-bf9e-290b0c3d4dd9](https://github.com/owncloud/client/assets/144467728/8846fd88-8a84-453d-a80d-75c18877a540)

**Comment by TheOneRing** [comment]
We display that information on all platforms but mac.
![image](https://github.com/owncloud/client/assets/200626/b86ff749-87e3-4ec2-b292-fdeb73e2c10d)

On Mac, we don't display it at the moment as it's handled by a third party software.

**Comment by rpausch-owncloud** [comment]
I do not want it here but in the about dialig
![grafik](https://github.com/owncloud/client/assets/144467728/c6a789a7-ca55-431d-aa71-d6f65537f600)

, since as I wrote, this information is usually hidden because you have to scroll down in the UI in order to see it. Users are used to se this information in the about screen, e.g. in Firefox, Chrome, Thunderbird, Rocket.chat
![grafik](https://github.com/owncloud/client/assets/144467728/68d8e363-2c19-40f0-b7b1-89065541af4a)

**Comment by saw-jan** [comment]
Tested with `ownCloud 6.0.0.14185-daily20240710 [a947c5]`

![Screenshot from 2024-07-10 12-18-06](https://github.com/owncloud/client/assets/52366632/e5173180-fc13-46ef-93d8-8974359bba3a) | ![Screenshot from 2024-07-10 12-18-10](https://github.com/owncloud/client/assets/52366632/96aa9d22-bc8a-4e49-954b-aa493dbf6382)
--|--
