### ISSUE TITLE
[OIDC] Branding option to remove "login_hint" and "user" parameter from re-login URL

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#11489]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

The ownCloud-internal username not always works fine on the OpenID Connect IdP. When ownCloud clients append `&login_hint=test&user=test` to the re-login URL, in some cases the IdP has no way to let the user log in again.

### Proposed solution

I'd need a branding option to remove "login_hint" and "user" parameter from re-login URL.

### Alternative solutions you considered

We discussed requesting other user attributes from the `/ocs/v1.php/cloud/user` endpoint, and using those for the "login_hint" and "user", but it sounds like a nightmare to maintain and test.

**Comment by michaelstingl** [comment]
Related:

- Android: https://github.com/owncloud/android/issues/4288
- iOS: https://github.com/owncloud/ios-app/issues/1318

**Comment by TheOneRing** [comment]
Couldn't that be hacked on the server side by an Apache rule or something like that?

**Comment by TheOneRing** [comment]
But changing all 3 clients is a lot of work to fix their broken system.
It also means that the change won't be available for quite some time.

**Comment by michaelstingl** [comment]
Rejected in PB1.

Workaround:

1. Remove account
2. Login again
