### ISSUE TITLE
owncloud complains of unsupported client version

### ISSUE THREAD

**Issue by howardlowndes** [owncloud/client#11498]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The server is Raspberry Pi running Raspberry Pi OS bullseye (Debian version 11)
The client is Raspberry Pi running Raspberry Pi OS bookworm (Debian version 12)
From /var/www/owncloud/version.php on the server I have 

> <?php 
$OC_Version = array(10,13,4,1);
$OC_VersionString = '10.13.4';
$OC_Channel = 'stable';
$OC_Edition = 'community';
$OC_VersionCanBeUpgradedFrom = [[8,2,11],[9,0,9],[9,1]];
$OC_Build = '2023-12-13T16:53:08+00:00 902d2f2dca70b483fef959febea763d861e93c3e';
$vendor = 'owncloud';

On the client I have

> $ owncloud --version
QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0770 instead of 0700
ownCloud ownCloud 2.11.0 Mar 23 2023 10:21:23
Libraries Qt 5.15.8, OpenSSL 3.0.11 19 Sep 2023
Using virtual files plugin: suffix
debian-6.1.0-rpi7-rpi-v8

When I try to run _owncloud --showsettings_ I receive the screen shown below
![20240131_17h17m25s_grim](https://github.com/owncloud/client/assets/52798206/4cc093a4-b165-4b62-9310-05ff7054a246)

### Expected behavior

The client should be able to access the server for normal synchronization

### Client version number

$ owncloud --version
QStandardPaths: wrong permissions on runtime directory /run/user/1000, 0770 instead of 0700
ownCloud ownCloud 2.11.0 Mar 23 2023 10:21:23

Libraries Qt 5.15.8, OpenSSL 3.0.11 19 Sep 2023
Using virtual files plugin: suffix
debian-6.1.0-rpi7-rpi-v8

### Server information

$ cat /var/www/owncloud/version.php 
$OC_Version = array(10,13,4,1);
$OC_VersionString = '10.13.4';
$OC_Channel = 'stable';
$OC_Edition = 'community';
$OC_VersionCanBeUpgradedFrom = [[8,2,11],[9,0,9],[9,1]];
$OC_Build = '2023-12-13T16:53:08+00:00 902d2f2dca70b483fef959febea763d861e93c3e';
$vendor = 'owncloud';

**Comment by TheOneRing** [comment]
ownCloud 10.13.4 does not support 2.11 clients, as the error message mentions.

**Comment by howardlowndes** [comment]
As 2.11 is the latest version of owncloud client that is available from Debian, what is the latest compatible earlier version of the web service?

**Comment by TheOneRing** [comment]
I don't recommend to downgrade the server as only the latest version contains all required security fixes.
Usually I'd recommend our official binaries, but we don't support arm yet.

**Comment by howardlowndes** [comment]
Your own documentation states:
	
For Linux distributions, we support, if technically feasible, the latest two versions per platform and the previous LTS Version.

**Comment by TheOneRing** [comment]
Yes we do: https://download.owncloud.com/desktop/ownCloud/stable/5.2.1.13040/linux/download/
However, only x86_64 platforms.
![image](https://github.com/owncloud/client/assets/200626/157d1530-c0d1-48e6-a0ac-7067889c56bd)
