### ISSUE TITLE
Wizard: Strip user info from url

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11497]
If a user enters a URL with username or password encoded, we should remove that information and not send it to the server (`QUrl::RemoveUserInfo`)
The user info should just be ignored, and the wizard will behave as if no information was provided.

_Originally posted by @TheOneRing in https://github.com/owncloud/client/issues/11045#issuecomment-1645486797_

**Comment by saw-jan** [comment]
Tested on `ownCloud 6.0.0.13582-daily20240327 [4258b6]`

![Screenshot from 2024-03-28 16-05-55](https://github.com/owncloud/client/assets/52366632/a5a949b0-8f9f-4b6b-846f-23e6b869b282) | ![Screenshot from 2024-03-28 16-06-01](https://github.com/owncloud/client/assets/52366632/4406bedc-97ed-4951-9a46-5160ca4de497) | ![Screenshot from 2024-03-28 16-06-05](https://github.com/owncloud/client/assets/52366632/16bd1b6a-7087-47f1-a974-94144aa7cb93)
--|--|--
