### ISSUE TITLE
[QA] Linux client fails to 'Show in file manager'

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#11502]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

testpilotcloud 6.0.0.13190-daily20240124 ab204c
Libraries Qt 6.6.1, OpenSSL 3.2.0 23 Nov 2023
Using virtual files plugin: suffix
OS: linuxmint-5.4.0-169-generic (build arch: x86_64, CPU arch: x86_64)
QPA: xcb

Installed via DEB packages.

* Connect client to server,
* wait for the initial sync to complete.
* click open the little triangle to expose the synced folder list.
* Right click one folder, -> Show in file manager

Nothing happens in the UI, the console prints:
```
Unable to init server: Could not connect: Connection refused
Could not parse arguments: Cannot open display: 

```
Nothing in the client.log 

![grafik](https://github.com/owncloud/client/assets/1108546/8c93cee3-4e72-47af-8cd4-f4a2b86209a5)

### Steps to reproduce the issue

* Connect client to server,
* wait for the initial sync to complete.
* click open the little triangle to expose the synced folder list.
* Right click one folder, -> Show in file manager

### Screenshots

![grafik](https://github.com/owncloud/client/assets/1108546/8c93cee3-4e72-47af-8cd4-f4a2b86209a5)

### Expected behavior

the file browser should open.

### Actual behavior

-

**Comment by TheOneRing** [comment]
You could at least try to upload logs...

**Comment by jnweiger** [comment]
Attached log containing
* connecting to demo.owncloud.com 
* click on open in File browser (nothing gets added to the log)
* click on open in Web browser (the last few line get added to the log)

[tp-0201_1355.log](https://github.com/owncloud/client/files/14125568/tp-0201_1355.log)

**Comment by TheOneRing** [comment]
Sounds like its using this code path: https://github.com/owncloud/client/blob/51b0ce5e0cc2249932a17c9717d8600da3561772/src/gui/openfilemanager.cpp#L188-L188
But why is the display env var missing....

**Comment by TheOneRing** [comment]
Fixed in https://github.com/owncloud/craft-blueprints-owncloud/commit/bef9d1629a2a40513bba19dc2a61de3193b87136

**Comment by saw-jan** [comment]
Tested on `ownCloud 6.0.0.13582-daily20240327 [4258b6]`

Can open in file manager and web browser (Activity tab)
