### ISSUE TITLE
client crashed in OCC::Folder::startVfs() at `folder.cpp:551`

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11503]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

CI Build: https://drone.owncloud.com/owncloud/client/17620/4/10

```c
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/drone/src/build/bin/owncloud -s --logfile - --logdebug --logflush'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007ff6642bf844 in __pthread_kill_implementation () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7ff660be7f00 (LWP 4635))]
#0  0x00007ff6642bf844 in __pthread_kill_implementation () at /lib64/libc.so.6
#1  0x00007ff66426eabe in raise () at /lib64/libc.so.6
#2  0x00007ff66425790f in abort () at /lib64/libc.so.6
#3  0x00007ff66483b0eb in qgetenv(char const*) [clone .cold] () at /lib64/libQt6Core.so.6
#4  0x00007ff66483bb7f in  () at /lib64/libQt6Core.so.6
#5  0x00000000004da39f in OCC::Folder::startVfs() (this=0x1d8aab0) at /drone/src/src/gui/folder.cpp:551
        result = {<OCC::Result<OCC::detail::NoResultData, QString>> = {{_result = {<No data fields>}, _error = {d = {d = 0x89ce1700, ptr = 0x7ffc89ce1800 u"馈ǜ", size = 30976688}, static _empty = 0 u'\000'}}, _isError = 64}, <No data fields>}
        vfsParams = {filesystemPath = {d = {d = 0x7ffc89ce1630, ptr = 0x7ffc89ce16a0 u"ꪰǘ", size = 11}, static _empty = 0 u'\000'}, remotePath = {d = {d = 0x8, ptr = 0x7ffc89ce1650 u"", size = 22}, static _empty = 0 u'\000'}, account = {value = 0x7ffc89ce1640, d = 0x7ff664a1e9fd <QArrayData::allocate(QArrayData**, long long, long long, long long, QArrayData::AllocationOption)+93>}, journal = 0xb, providerDisplayName = {d = {d = 0x74208eca67a26800, ptr = 0x16 <error: Cannot access memory at address 0x16>, size = -328}, static _empty = 0 u'\000'}, providerName = {d = {d = 0x2, ptr = 0x1f7b920 u"", size = 0}, static _empty = 0 u'\000'}, providerVersion = {m_segments = {{dummy = 0, inline_segments = "\000\000\000\000\000\000\000", pointer_segments = 0x0}}}, multipleAccountsRegistered = false, _baseUrl = {d = 0x7ff6642ce1ce <free+126>}, _groupInSidebar = 176, _syncEngine = 0x7ffc89ce16c0}
#6  0x00000000004e9ec1 in QtPrivate::FunctorCall<QtPrivate::IndexesList<>, QtPrivate::List<>, void, void (OCC::Folder::*)()>::call(void (OCC::Folder::*)(), OCC::Folder*, void**) (f=(void (OCC::Folder::*)(OCC::Folder * const)) 0x4da310 <OCC::Folder::startVfs()>, o=0x1d8aab0, arg=0x1dc9988) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:135
#7  0x00000000004e9e1d in QtPrivate::FunctionPointer<void (OCC::Folder::*)()>::call<QtPrivate::List<>, void>(void (OCC::Folder::*)(), OCC::Folder*, void**) (f=(void (OCC::Folder::*)(OCC::Folder * const)) 0x4da310 <OCC::Folder::startVfs()>, o=0x1d8aab0, arg=0x1dc9988) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:172
#8  0x00000000004e9d62 in QtPrivate::QSlotObject<void (OCC::Folder::*)(), QtPrivate::List<>, void>::impl(int, QtPrivate::QSlotObjectBase*, QObject*, void**, bool*) (which=1, this_=0x1dc9910, r=0x1d8aab0, a=0x1dc9988, ret=0x0) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:383
#9  0x00007ff664931767 in QObject::event(QEvent*) () at /lib64/libQt6Core.so.6
```

### Logs

[stacktrace.log](https://github.com/owncloud/client/files/14120324/stacktrace.1.log)
[clientlog.log](https://github.com/owncloud/client/files/14120332/serverlog.1.log)

### Client version number

owncloud 6.0.0.git `59a9cfb`

### Server information

ocis 4

**Comment by TheOneRing** [comment]
This issue is kind of interesting.
We delayed the start of the sync until the application is properly setup, the account is prepared.

This test however, manages to wipe the folder ("Remove folder sync connection" or by account removal) before that happens.

I'm not sure how to prevent something like that in the future, for now... could we add a short delay before the test removes the folder?

CC: @erikjv

**Comment by erikjv** [comment]
@TheOneRing So if I understand it correctly, the folder is already torn down. If so, we should change the OC_ENFORCE to a normal if statement and just return without doing anything.

**Comment by TheOneRing** [comment]
Well I don't think this can happen in a real world scenario and in this case pointed out that the test might need a timeout to better simulate human behavior :D

**Comment by saw-jan** [comment]
> Well I don't think this can happen in a real world scenario and in this case pointed out that the test might need a timeout to better simulate human behavior :D

Yep, I will go through the test code how to better handle this. :+1:

**Comment by saw-jan** [comment]
We have harden the GUI test in https://github.com/owncloud/client/pull/11512
So closing this one. Will reopen if it appears again
