### ISSUE TITLE
Bug: getDirectorySyncRootMarking prevents adding spaces to sync folder

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11516]
The code recursively checks its parents and accidentally prevents us from adding a new space using the "Add space" button.

https://github.com/owncloud/client/blob/2e5c31640a490540264d6d3536fe95b942da140e/src/gui/folderman.cpp#L723-L723

**Comment by saw-jan** [comment]
Tested on `ownCloud 6.0.0.13582-daily20240327 [4258b6]`

New Space can be added
![Screenshot from 2024-03-28 16-16-02](https://github.com/owncloud/client/assets/52366632/b9d5fb7a-00a2-4efc-a05f-78557b2d4bc9)
