### ISSUE TITLE
Sync folder name becomes invisible

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/client#11525]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

While clicking on sync folder, details of sync folder disappears. It reappears some time.

### Steps to reproduce the issue

1. Build and run client from master branch (Using `QT 6.4.3`)
```
$ cmake \
  -DCMAKE_PREFIX_PATH=$HOME/packages/lib/cmake \
  -G"Ninja" -DCMAKE_C_COMPILER="clang" \
  -DCMAKE_CXX_COMPILER="clang++" \
  -DCMAKE_BUILD_TYPE="Debug" \
  -DBUILD_TESTING=OFF \
  -S ..

$ ninja -j4

$ ./owncloud -s
```
2. Add one account
3. Right click on any sync folder or click on `...` to open context menu

### Screenshots

![Screenshot from 2024-02-21 14-17-15](https://github.com/owncloud/client/assets/53458341/8bb53e66-342c-4a58-9dae-c1ab8cd85585)

### Client version number

ownCloud 6.0.0-git [3b5bbe](https://github.com/owncloud/client/commit/3b5bbe127bfda3c84ea0420507813c87d43329e5)
Libraries Qt 6.4.3, OpenSSL 3.0.2 15 Mar 2022
Using virtual files plugin: suffix
OS: ubuntu-6.5.0-18-generic (build arch: x86_64, CPU arch: x86_64)
QPA: xcb

### Additional context

This behavior does not occur in daily built client. 

client version:
ownCloud 6.0.0.13362-daily20240221 [590fe5](https://github.com/owncloud/client/commit/590fe5cde58f70b9067b2bf20364936b81b53180)
Libraries Qt 6.6.1, OpenSSL 3.2.1 30 Jan 2024
Using virtual files plugin: suffix
OS: ubuntu-6.5.0-18-generic (build arch: x86_64, CPU arch: x86_64)
QPA: xcb

cc: @TheOneRing

**Comment by TheOneRing** [comment]
I expect the issue to be resolved with the new implementation
