### ISSUE TITLE
Wrong Credentials like in 1.4.0

### ISSUE THREAD

**Issue by Ekranos** [owncloud/client#1153]
Hi all,

i still have the problem that i can't login with the desktop client. It says "Fehler: Falsche Anmeldeinformationen". I updated to 1.4.2 and tried to downgrade to 1.4.1. Both doesnt work. I have the newest ownCloud version installed.

I can login to the backend via http, but not with the client. My username and password are alphanumeric.

Also tested it on a fresh installed windows laptop. It didn't work as well...

**Comment by Pastafarianist** [comment]
I can reproduce this with client version 1.5.0 (latest in Mint repository) and ownCloud version 8.1. How do I reopen this?

**Comment by danimo** [comment]
@Pastafarianist Not unless you can reproduce it with our official binaries. 1.5.0 is ancient.

**Comment by Pastafarianist** [comment]
@danimo I reproduced it with 1.7.0 which is the latest in Kubuntu 15.04 repos.

**Comment by fischmax** [comment]
I reproduce this problem with owncloud server version 8.1 on debian 8.1  and client version 1.8.4 on kubuntu 14.04. I can connect via web interface as well as the Windows client on Windows 7 and 10 without any problems and don't have non-ascii chars in my password.

**Comment by RedSocks157** [comment]
I'm having this issue with the desktop client on Linux Mint. Clearly this problem has been going on for some time...any fix yet?

**Comment by dragotin** [comment]
@RedSocks157 please open a new issue, following the issue template with logs, versions and stuff.
