### ISSUE TITLE
Client fails with "Could not detect compatible server" when server hardening is applied

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#11534]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Seen with server 10.13 (probably) and client 5.2.x

When status.php is hardened with
```
/**
 * Show or hide the ownCloud version information in `status.php`
 * This hardens an ownCloud instance by hiding the version information in `status.php`.
 * This can be a legitimate step. Please consult the documentation before enabling this.
 */
'version.hide' => true,
```
then the available info looks like
```
curl https://oc10140-20240226.jw-qa.owncloud.works/status.php
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"","versionstring":"","edition":"","productname":"","product":""}
```

This leads in one case to a client error message in src/gui/newwizard/jobs/resolveurljobfactory.cpp
```
setJobError(job, QApplication::translate("ResolveUrlJobFactory", "Could not detect compatible server at %1").arg(oldUrl.toDisplayString()));
```

In my reproducer attempt with testpilotcloud client 5.2, this error did not occur though.
@steelcuts may have more details.

### Expected behavior

client connections are not hindered by well documented server  hardening.

### Steps to reproduce the issue

not sure.

### Screenshots

.

### Client version number

5.2

### Server information

.

**Comment by TheOneRing** [comment]
Has nothing todo with version.hide.
This might be a 404 or a network error.
I'd need logs to tell you more.
