### ISSUE TITLE
[QA] VFS is deprecated in v7.0

### ISSUE THREAD

**Issue by ammannit** [owncloud/client#11535]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

I have found the following comment:

We decided to deprecate the suffix VFS implementations and thus prepare its
removal in 7.0.

Will there be an alternative function?

### Steps to reproduce the issue

-

### Screenshots

-

**Comment by TheOneRing** [comment]
Some day we will implement native mac vfs.
For linux we have a fuse layer in mind.
