### ISSUE TITLE
Detect captive portal and pause sync

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11533]
See https://github.com/owncloud/client/issues/11531
https://doc.qt.io/qt-6/qnetworkinformation.html#isBehindCaptivePortal-prop

**Comment by erikjv** [comment]
Where should we do this exactly? In the account state? Or when the SSL cert. checks fail? Also, should we listen for this and somehow show a notification on the desktop that we stopped/resumed syncing?
