### ISSUE TITLE
Regression: Branded clients are not using the branded systray icons

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11548]

**Comment by saw-jan** [comment]
Tested on `testpilotcloud 6.0.0.13591-daily20240328 32670a`
![Screenshot from 2024-03-28 14-47-01](https://github.com/owncloud/client/assets/52366632/337de0ae-fb6e-48e7-888a-b55fcb20f8e0) | ![Screenshot from 2024-03-28 14-47-15](https://github.com/owncloud/client/assets/52366632/4d4dbc0d-97cd-4faf-9101-567ab335ebbc)
--|--
Before | Now
