### ISSUE TITLE
Hard to read red error message

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11547]
![image](https://github.com/owncloud/client/assets/200626/a39961ae-542e-46b2-bc29-2c61a126dc53)

**Comment by saw-jan** [comment]
Tested on `ownCloud 6.0.0.13589-daily20240328 [32670a]`

![Screenshot from 2024-03-28 14-36-11](https://github.com/owncloud/client/assets/52366632/2e0aaf13-451a-476a-be86-ec682ec7be05)
