### ISSUE TITLE
[macOS] Sync connection visuals broken (tinted + overlay scaling)

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#11544]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Sync connection visuals look broken

### Expected behavior

- Overlay status element should have the original colors
- Overlay status element should be smaller, aligned to the top right

### Steps to reproduce the issue

Login with new account.

### Screenshots

![CleanShot 2024-03-13 at 18 34 17@2x](https://github.com/owncloud/client/assets/214010/7381e4e2-6d6f-4ccc-97e8-305da2e39365) | ![CleanShot 2024-03-13 at 18 34 29@2x](https://github.com/owncloud/client/assets/214010/18366e3c-9ab1-4299-a401-932bfff6ae00)
-- | --

### Client version number

```
ownCloud 6.0.0.13500-daily20240313 bac757
Libraries Qt 6.6.2, OpenSSL 3.2.1 30 Jan 2024
Using virtual files plugin: suffix
OS: macos-23.3.0 (build arch: arm64, CPU arch: arm64)
QPA: cocoa
```

### Server information

```
[Log]  ownCloud Web UI 9.0.0-alpha.2  (index.html-wYupJ6na.mjs, line 1)
[Log]  Infinite Scale 5.1.0-prealpha+dc98e7a6b Community  (index.html-wYupJ6na.mjs, line 1)
```

### Additional context

Compare:
- https://github.com/owncloud/client/issues/11403

**Comment by TheOneRing** [comment]
Just wait a few more days :D
![Clipboard - March 12, 2024 13 20](https://github.com/owncloud/client/assets/200626/efc8c445-b031-429d-904e-cfb1446d22d9)
