### ISSUE TITLE
[Debian] owncloud Client 5.2.1 has no images

### ISSUE THREAD

**Issue by P-EB** [owncloud/client#11558]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Hello,

While trying to get owncloud client 5.2.1 working in Debian (unstable, testing), I achieved a built version which has no images, be it in the client itself or its systray icon.

It seems the way resources are handled changed between the versions not supporting Qt6 and those supporting Qt6.

I'm not able yet to identify where the underlying issue is. Could someone, eg @TheOneRing who already helped me once on building 5.2.1 properly, help me to try backtracking the issue?

Any advice is welcome!

### Expected behavior

I'd expect to have pretty images, but none appear

![owncloud_client_no_images](https://github.com/owncloud/client/assets/3770652/35e21fda-45ca-4e2b-93ea-528210893c08)
![systray](https://github.com/owncloud/client/assets/3770652/4a778b89-f415-4c84-8bde-213f1cf659d4)

### Client version number

5.2.1.13040+dfsg-1

**Comment by TheOneRing** [comment]
Can you check whether the qt6 svg module is installed?

**Comment by P-EB** [comment]
> Can you check whether the qt6 svg module is installed?

Well spotted, I was missing it.

It seems the way I used to collect new dependencies is flaky. I've yet to find a file that lists the requirements for owncloud-client, did I miss something in the repo?

**Comment by TheOneRing** [comment]
I usually rely on the CMakeList.txt, when building packages myself but runtime dependencies like QSvg or qt6-image-formats-plugins are usually not covered by cmake...
Is there a best practice pattern we should follow here?

The 6.0 client introduces a dependency to qml, wich on debian based systems is split up into a gazillion of packages (`qml6-module-qtqml-*`)
Not sure on how to communicate something like that...

**Comment by P-EB** [comment]
@TheOneRing any documentation file listing dependencies would be fine I guess. :)

I admit for compiled programs I see no clear standards being widely used

**Comment by P-EB** [comment]
@TheOneRing would you be fine with such a solution?

**Comment by TheOneRing** [comment]
If such a list is not kept in sync with reality, it hurts more than it helps, so I'm not sure that's the best solution....

**Comment by proofy** [comment]
Is it a new bug or is it here?
The debian overlay package wants to have the owncloud-client version of 5.2.1+oc-13040, but there is not this version, there is only  owncloud-client_5.2.1.13040.deb without '+oc-'.

```
dpkg-deb --info ./owncloud-client-overlays-icons_5.2.1+oc-13040_all.deb 
 neues Debian-Paket, Version 2.0.
 Größe 193008 Byte: control-Archiv= 1832 Byte.
     354 Byte,    11 Zeilen      control              
    5277 Byte,    58 Zeilen      md5sums              
 Package: owncloud-client-overlays-icons
 Source: owncloud-client-overlays
 Version: 5.2.1+oc-13040
 Architecture: all
 Maintainer: Jürgen Weigert <jw@owncloud.com>
 Installed-Size: 279
 Suggests: owncloud-client (= 5.2.1+oc-13040), nautilus
 Section: devel
 Priority: optional
 Description: nautilus plugin for owncloud
  This package contains the overlay icons.

```
Because it is only a suggestion, it is possible to install..

**Comment by TheOneRing** [comment]
> Is it a new bug or is it here? The debian overlay package wants to have the owncloud-client version of 5.2.1+oc-13040, but there is not this version, there is only owncloud-client_5.2.1.13040.deb without '+oc-'.
> 
> ```
> dpkg-deb --info ./owncloud-client-overlays-icons_5.2.1+oc-13040_all.deb 
>  neues Debian-Paket, Version 2.0.
>  Größe 193008 Byte: control-Archiv= 1832 Byte.
>      354 Byte,    11 Zeilen      control              
>     5277 Byte,    58 Zeilen      md5sums              
>  Package: owncloud-client-overlays-icons
>  Source: owncloud-client-overlays
>  Version: 5.2.1+oc-13040
>  Architecture: all
>  Maintainer: Jürgen Weigert <jw@owncloud.com>
>  Installed-Size: 279
>  Suggests: owncloud-client (= 5.2.1+oc-13040), nautilus
>  Section: devel
>  Priority: optional
>  Description: nautilus plugin for owncloud
>   This package contains the overlay icons.
> ```
> 
> Because it is only a suggestion, it is possible to install..

Unrelated to this issue please open a new issue and provide an extended description.
