### ISSUE TITLE
Remove the remove all dialog

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11569]
I'd remove the dialog at all.
              if all files got deleted from the server, the default should be that all files get also deleted from the client. the server is the source of truth; files can be restored from the server trashbin if this was done unintentionally.

_Originally posted by @tbsbdr in https://github.com/owncloud/client/issues/11545#issuecomment-2022078654_

Additionally, the functionality was limited nowadays, as with virtual files the local `backup` was only partly existing.

**Comment by saw-jan** [comment]
Tested on `ownCloud 6.0.0.13631-daily20240405 [de909e]`

No `Remove All Files?` dialog :heavy_check_mark:
