### ISSUE TITLE
Local DB: Separate parent_phash column

### ISSUE THREAD

**Issue by guruz** [owncloud/client#1157]
Right now the file metadata table looks like this:
```
CREATE TABLE metadata(phash INTEGER(8),pathlen INTEGER,path VARCHAR(4096),inode INTEGER,uid INTEGER,gid INTEGER,mode INTEGER,modtime INTEGER(8),type INTEGER,md5 VARCHAR(32),PRIMARY KEY(phash));
```

When a directory is read from the DB, it is done via a LIKE SQL string operation (See http://code.woboq.org/owncloud/csync/src/csync_statedb.c.html#csync_statedb_get_below_path ). This is probably not efficient.
A dedicated ```parent_phash``` column (with index?) could speed this up.

Challenges:
* Migration for old DB where this column is missing

**Comment by guruz** [comment]
@dragotin@ogoffart @ckamm  Is there a chance that this is an easier win (fruit to pick) than keeping-the-tree-in-memory?

But this would only help for the remote discovery not the local one right?
And we think the local one is a problem?

**Comment by dragotin** [comment]
Maybe instead of keeping the tree, a better idea is to build it completely from the sync journal instead from the file system? That should be possible if we can assume that the file system notifications are reliable.

**Comment by ogoffart** [comment]
Since commit 597d36dcf20b838524c250eba55ed0425480565a we use the index and i don't think a parent_phash would help in any better way.
