### ISSUE TITLE
[a11y] 1.4.11 Non-text contrast

### ISSUE THREAD

**Issue by tschiebel** [owncloud/client#11583]
https://infinite.owncloud.com/s/KcGPhbRgJfHYHuw

[BIT inklusiv BITV-Softwaretest - BIT inklusiv (bit-inklusiv.de)](https://www.bit-inklusiv.de/bitv-softwaretest/)

### Space and Settings

- [x] The active tabs (checkboxes) in the navigation (toolbar) differ from the inactive tabs 
the non-active tabs only by the background color. The 
contrast requirements are not met, as the contrast ratio between active and inactive 
active and non-active tabs is less than 3:1, at only 1.1:1. 
increasing the contrast, emphasizing the labeling with bold print or adding a frame color. 
by using bold print or adding a frame.

### Server activity and Synchronization protocol

- [ ] Active tabs such as "Server activity" differ from the inactive tabs 
tabs only by the background color. The 
contrast requirements are not met, as the contrast ratio between active 
active and non-active tabs is less than 3:1, at only 1.4:1. 
solution would be, for example, to increase the contrast, emphasize the 
the labeling with bold print or increasing the contrast of the frame.

- [x] Active tabs (checkboxes) of the navigation (toolbar) - See comment on 
Space.

**Comment by erikjv** [comment]
About tab contrast:

<img width="684" alt="Screenshot 2024-06-05 at 18 04 12" src="https://github.com/owncloud/client/assets/151956/08dc3264-2371-4578-b19b-3f260be54550">

For me (on mac) the contrast is fine. Which platform is this tested on?

**Comment by erikjv** [comment]
For Windows most contrast issues are fixed by using the "High Contrast" theme.

**Comment by TheOneRing** [comment]
@erikjv  Could you gather a bunch of screenshots with the high contrast theme?

**Comment by erikjv** [comment]
With the "Aquatic" contrast theme on windows 11:

![Image](https://github.com/user-attachments/assets/67e05030-69b6-43e2-8427-8e1a8b6a8e87)



![Image](https://github.com/user-attachments/assets/03e98970-3b63-47b8-a93a-b8ea51d71258)

**Comment by erikjv** [comment]
With the "Glow" (non-contrast) theme (Win11):



![Image](https://github.com/user-attachments/assets/c39e4ca8-0be8-4cd8-ba68-f2cce9ec6e1c)



![Image](https://github.com/user-attachments/assets/7d49bc33-6b64-4f89-9815-d23c0ee7873b)

**Comment by erikjv** [comment]
For both: I've set my laptop to use a smaller default font.

**Comment by TheOneRing** [comment]
Could you also test with a build where: https://github.com/owncloud/client/blob/33384118c29d7378cad37d9971e5f90123f234e3/src/libsync/platform_win.cpp#L69-L69 is commented out? 
As those two look pretty similar....

**Comment by erikjv** [comment]
What is still a problem are the tabs in the activity view: the fusion theme (and the new Windows theme) do not show much contrast between active and inactive tabs

**Comment by erikjv** [comment]
Closing this issue, the problem described above now has its own issue: #11825
