### ISSUE TITLE
[a11y] 1.3.2 Sensible sequence

### ISSUE THREAD

**Issue by tschiebel** [owncloud/client#11582]
https://infinite.owncloud.com/s/KcGPhbRgJfHYHuw

[BIT inklusiv BITV-Softwaretest - BIT inklusiv (bit-inklusiv.de)](https://www.bit-inklusiv.de/bitv-softwaretest/)

### Space

- [x] The elements of the navigation (toolbar) are not displayed according to their visual 
arrangement. The tab with the space name is incorrectly displayed as the 
last element in the navigation. In addition, when using the 
Windows language output, the navigation is output as the last element of the page.
![image](https://github.com/owncloud/client/assets/132444655/5048f6de-a86e-4585-9d68-cd7d3c92688b)

###  Server activity

- [x] #11679
displayed. First, the notifications are displayed in the list, 
followed by the "Server activity" tab bar and so on. Only then are the 
elements of the navigation (toolbar) are displayed at the top of the page, but 
not in the correct order.

- [x] #11778
nested group elements, whereby all of these groups have no group labels. 
group labels.

###  Synchronization protocol

- [x] #11680
according to their visual arrangement. The contents of the table are displayed first, followed by the 
tab bar "Server activity" etc. Only then are the elements of the 
main navigation (toolbar) are displayed at the top of the page, but not in the correct order. 
correct order.

### Settings

- [x] #11780
nested group elements, whereby none of these groups have group labels. 
group labels.

- [x] #11781
output by screen readers.

- [x] #11782
output. The contents of the group with the settings 
and only then the elements of the main navigation (toolbar) at the top of the page 
at the top of the page, which are also not displayed in the correct order. 
are also not displayed in the correct order.

### Add Space

- [x] #11779
the contents of the table.

**Comment by tschiebel** [comment]
@tbsbdr all tasks are done, but ticket is still open - is that right? Or do you close this?

**Comment by tbsbdr** [comment]
Closing, please reopen if this is not correct @TheOneRing
