### ISSUE TITLE
[a11y] 2.1.2 Keyboard trap in protocol

### ISSUE THREAD

**Issue by tschiebel** [owncloud/client#11585]
https://infinite.owncloud.com/s/KcGPhbRgJfHYHuw

[BIT inklusiv BITV-Softwaretest - BIT inklusiv (bit-inklusiv.de)](https://www.bit-inklusiv.de/bitv-softwaretest/)

###  Synchronization protocol and Add Space 

- [ ] If the data cells of the table receive the keyboard focus, it is no longer possible to 
possible to leave the table using the keyboard. The keyboard focus remains 
trapped in the table

**Comment by erikjv** [comment]
Fixed somewhere along the way.
