### ISSUE TITLE
Port `LoginRequiredDialog` from a `QDialog` to an `AccountModalWidget`

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11592]
`LoginRequiredDialog` is still a real `QDialog` that is now used as a widget in an account modal view.
It should be adopted to the new aspect ratio and better use the visual space in the account page.

**Comment by erikjv** [comment]
<img width="912" alt="Screenshot 2024-04-18 at 16 22 10" src="https://github.com/owncloud/client/assets/151956/7fd1091f-9c58-4dde-87c1-7bd040459252">

Current/old "dialog"

**Comment by saw-jan** [comment]
Tested with `ownCloud 6.0.0.14181-daily20240709 [13f49d]`

![Screenshot from 2024-07-10 12-13-35](https://github.com/owncloud/client/assets/52366632/81a29e83-d7b8-4b4d-af5e-c233637a57c2) | ![Screenshot from 2024-07-10 12-14-02](https://github.com/owncloud/client/assets/52366632/f1bb4bb4-600a-4e45-9957-93ec08103fe6)
--|--
