### ISSUE TITLE
Adopt Update dialogs to the new modal widget experience

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11593]
The update dialogs are still simple dialogs that are now displayed on the full window size.
We need to evaluate how we can update their appearance for a dialog free approach.
 
https://github.com/owncloud/client/blob/8cbcb2ccf71b18410a73169be834ffc64c3c344b/src/gui/updater/ocupdater.cpp#L417-L417
https://github.com/owncloud/client/blob/8cbcb2ccf71b18410a73169be834ffc64c3c344b/src/gui/updater/ocupdater.cpp#L56-L56

They are currently displayed as a tiny dialog in the top left corner.

**Comment by erikjv** [comment]
Current state:

<img width="884" alt="Screenshot 2024-04-23 at 17 39 02" src="https://github.com/owncloud/client/assets/151956/1a3f2938-8e0d-4743-a324-1a043d0b04af">

**Comment by erikjv** [comment]
How can I get the message box to show up?

**Comment by saw-jan** [comment]
Tested with `ownCloud 6.0.0.14181-daily20240709 [13f49d]`

![Screenshot from 2024-07-10 13-06-50](https://github.com/owncloud/client/assets/52366632/d31b9221-4002-4553-afb8-5982dd7edcb0) | ![Screenshot from 2024-07-10 13-07-02](https://github.com/owncloud/client/assets/52366632/ccf552c0-bffc-436f-a18b-05a89f90e780)
--|--

Is this the expected UI for 'Update available' dialog?
@TheOneRing @erikjv

**Comment by TheOneRing** [comment]
Hmm thats the restart dialog, by then the update is already installed.

**Comment by saw-jan** [comment]
I mean this dialog.
![Screenshot from 2024-07-10 13-06-50](https://github.com/owncloud/client/assets/52366632/a37a42b2-0ffd-4691-a60a-9a8a15303686)

**Comment by TheOneRing** [comment]
Oh I thought that was an old screenshot, thx we should update the dialog thx.
