### ISSUE TITLE
Owncloud is used in a folder sync connection

### ISSUE THREAD

**Issue by Step72** [owncloud/client#11618]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Good morning
I just updated my computer to macOS 14.4.1
So I installed the ownCloud version 5.2.1.13040 and I put the owncloud-complete-20240226 version on my web server

I’m trying to add my hard drive to my owncloud but I get this message

### Expected behavior

ownCloud 5.2.1.13040 979bb9 Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023 Using virtual files plugin: suffix OS: macos-23.4.0 QPA: cocoa ownCloud

### Screenshots

<img width="894" alt="Capture d’écran 2024-04-28 à 11 27 53" src="https://github.com/owncloud/client/assets/18511992/fad6e8a6-293a-4461-bee5-8bcc4aecb7cc">
<img width="783" alt="Capture d’écran 2024-04-28 à 11 28 28" src="https://github.com/owncloud/client/assets/18511992/5f8de3ef-f69a-4844-8c63-b0681e4a6bdd">

How to synchronize the download of the five folders (téléchargement, image, sauvegarde, documents, documents, Mojave, sauvegarde SSD)  as well as all the content in SDD ?

### Client version number

ownCloud 5.2.1.13040 [979bb9](https://github.com/owncloud/client/commit/979bb990f214fbd1cccc5536c582d84e196d499f)
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: suffix
OS: macos-23.4.0
QPA: cocoa

### Server information

$OC_Version = array(10,14,0,3);
$OC_VersionString = '10.14.0';
$OC_Channel = 'stable';
$OC_Edition = 'community';

**Comment by TheOneRing** [comment]
Hi @Step72 sounds like you encounter this issue https://doc.owncloud.com/desktop/next/faq.html#folder-is-used-in-a-folder-sync-connection

**Comment by Step72** [comment]
I saw this article, but where is the file `.sync_journal.db` ?

**Comment by TheOneRing** [comment]
I consider this issue to be fixed, please reopen if needed.
