### ISSUE TITLE
v5.2.1 won't reconnect automatically after waking from sleep

### ISSUE THREAD

**Issue by haimiko** [owncloud/client#11613]
[ownCloud - Copy.log](https://github.com/owncloud/client/files/15069207/ownCloud.-.Copy.log)
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

owncloud 5.2.1 installed on both my laptop and desktop.  Both exhibit the similar behavior.  After waking from an extended sleep, owncloud shows "grayed" out until I manually click "Reconnect".

### Expected behavior

Previous versions would automatically reconnect after waking from sleep.

### Steps to reproduce the issue

1. Place computer to sleep for an extended time (i.e. +8hrs).
2. Wake computer and ownCloud client doesn't reconnnect

### Logs

TBD.  Only just enabled logging. Waiting to catch issue.

### Client version number

ownCloud 5.2.1.13040 [979bb9](https://github.com/owncloud/client/commit/979bb990f214fbd1cccc5536c582d84e196d499f)
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: wincfapi
OS: windows-10.0.22621
QPA: windows

### Installation path (Windows only)

c:\program files\ownCloud

### Server information

ownCloud 10.7.0 (docker version 10.7)

**Comment by TheOneRing** [comment]
Waiting for logs

**Comment by haimiko** [comment]
Added log.  Seems the client thinks the host is unreachable even though it is.
Network error:  OCC::JsonApiJob(OCC::Account("user@10.0.0.1:8080"), "http://10.0.0.1:8080/ocs/v2.php/cloud/capabilities?format=json", "GET", Original-Request-ID: "f457f237-4d4c-4187-8a81-c4e182f940ef", X-Request-ID: "f457f237-4d4c-4187-8a81-c4e182f940ef", NetworkError: "Host unreachable") "Host unreachable"

**Comment by TheOneRing** [comment]
But that's what the system reports to us.
Do you have http logs enabled? https://doc.owncloud.com/desktop/next/appendices/troubleshooting.html#log-files

**Comment by apach3guy** [comment]
Yep. Same problem here. I’m having this issue on multiple PCs. If I close the Owncloud app and reopen it then it connects to the server right away.

**Comment by TheOneRing** [comment]
> Yep. Same problem here. I’m having this issue on multiple PCs. If I close the Owncloud app and reopen it then it connects to the server right away.

And the reconnect has no effect either?

> 
> @TheOneRing Try this on your PC. I guarantee you will see the same bug.

I haven't seen this behavior, however I'm already testing 6.


>NetworkError: "Host unreachable" 

That really doesn't look like a client issue.
If the client encounters a network issue, it should trigger the connection validator. Which should try every X seconds to reach the server.

Could you please upload some log, with http logs enabled, to:
https://infinite.owncloud.com/s/AySXaQgrjbiRlYv
Password: y2#Z.B9j[h6V

**Comment by haimiko** [comment]
I'll enable http logging and wait for the next failure.   I'm guessing its because, after the laptop wakes up, wifi connection hasn't been fully established and may take a few seconds to stabilize.  By that time, the client has given up and isn't retrying the connection.   What's interesting is that I I'm not using a DNS hostname but rather an IP, so we really can't blame hostname resolution.

**Comment by haimiko** [comment]
No new logs.  owncloud stopped logging 2 days ago when the connection was lost.  As soon as I click "reconnect" the logs start flowing again.

**Comment by TheOneRing** [comment]
The log file is buffered so only written out when enough log lines accumulated. Also, sometimes the explorer only updates the filesize with a huge delay.
So the log file might still contain something.
If you want to see what's going right now, you can also start the client in a terminal.
`owncloud.exe --logfile -` this will not buffer, and you can always see what's going on.

**Comment by klaasdc** [comment]
Just wanted to confirm the same issue on my laptop with Win10, since the last update. The interface says that the account is signed out, in the tooltip. Only solution to get the syncing restarted is to exit and restart the client.

**Comment by nicobsa** [comment]
Hi,
Same issue on my computer,
version 5.2.1.13040,
when I click "reconnect", the sync works again after some seconds

**Comment by TheOneRing** [comment]
I do believe you all, but please, could someone try to upload logs 🙂

**Comment by nicobsa** [comment]
Hi all,
I succeed to reproduiced just now,
after wake up after hibernation at 15h50 this after noon,
wake up at 18:00

**Log below** (I hope I remove sensitive data)
[owncloud_log_failed_after_wake_up_no_sensitive_data.txt](https://github.com/owncloud/client/files/15202644/owncloud_log_failed_after_wake_up_no_sensitive_data.txt)


target URL is reachable, status URL seems to be ok,
never use a proxy (and settings not changed between before and after hibernation)
I can't check more by myself


But sync directories stay greyed, and account seems to be not connected

Hope it will help you

**Comment by TheOneRing** [comment]
```
24-05-03 18:16:22:163 [ info sync.connectionvalidator ]:	ConnectionValidator "xxxx" still running after duration(0h, 15min, 59s, 989ms)
```
Meh thats a strong hint

**Comment by TheOneRing** [comment]
Most probably fixed by: https://github.com/owncloud/client/pull/11467
The change was merged to the 5 branch. Could you try the 5 nightly build, it is definitely stable but should fix this issue.

**Comment by nicobsa** [comment]
Hi,

thanks,

Could you help me to find out the nightly builds ?

**Comment by TheOneRing** [comment]
https://download.owncloud.com/desktop/ownCloud/daily/5.2/

**Comment by nicobsa** [comment]
5.2.2.13816-daily20240507 installed,
I'll test it during some days (the issue does not appears each time)

Thanks for your help :)

**Comment by nicobsa** [comment]
It seems to work fine !

Thanks for your help

**Comment by haimiko** [comment]
Same here.  It's been behaving as expected.
