### ISSUE TITLE
[QA] GUI tests sometime fails due to system keyring dialog

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11619]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Builds: https://drone.owncloud.com/owncloud/client/18181/6/10, https://drone.owncloud.com/owncloud/client/18177, https://drone.owncloud.com/owncloud/client/18176

### Screenshots

![Screenshot from 2024-04-30 13-21-32](https://github.com/owncloud/client/assets/52366632/ccd35e75-7c96-420b-9b46-b65ff991e002)

![Open_log_dialog_with_Ctrl+l_keys_combination](https://github.com/owncloud/client/assets/52366632/a9a425c7-8141-49d6-b92a-06ed816ad7b3)

### Logs
[clientlog.log](https://github.com/owncloud/client/files/15430646/clientlog.log)

Open task:
- [x] Unskip tests: https://github.com/owncloud/client/pull/11639/commits/79026eae72feacbee397ddf40a630d62eb404a40
  - https://github.com/owncloud/client/pull/11662

**Comment by saw-jan** [comment]
Seen more frequently:
- https://drone.owncloud.com/owncloud/client/18248
- https://drone.owncloud.com/owncloud/client/18244
- https://drone.owncloud.com/owncloud/client/18243
- https://drone.owncloud.com/owncloud/client/18242

**Comment by saw-jan** [comment]
These are the failures after some test fixes:
- https://drone.owncloud.com/owncloud/client/18457

**Comment by PrajwolAmatya** [comment]
This failure seems to be intermittent with some investigation the result is still unknown. So, moving this to backlog.

**Comment by saw-jan** [comment]
Seen more frequently now:
- https://drone.owncloud.com/owncloud/client/18826/2/16
- https://drone.owncloud.com/owncloud/client/18842/2/16
- https://drone.owncloud.com/owncloud/client/18860/2/16
- https://drone.owncloud.com/owncloud/client/18862/2/16
