### ISSUE TITLE
Improve wayland support by setting qApp->desktopFileName()

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11625]
https://doc.qt.io/qt-6/qguiapplication.html#desktopFileName-prop

**Comment by TheOneRing** [comment]
During the testing, we discovered that setting the desktop file name is not possible when using AppImages.
https://github.com/AppImageCommunity/libappimage/issues/192
There it was discovered that setting `StartupWMClass` (https://specifications.freedesktop.org/desktop-entry-spec/latest/ar01s06.html) in the `.desktop` file solves the issue.
Please give it a try.

**Comment by erikjv** [comment]
Is the value for the `StartupWMClass` property the `@APPLICATION_NAME@`?

**Comment by TheOneRing** [comment]
> Is the value for the `StartupWMClass` property the `@APPLICATION_NAME@`?

Hmm as far as I understand it yes https://github.com/owncloud/client/blob/cc15035325e9d5152f37003b67b7955282990a5a/src/gui/settingsdialog.cpp#L71-L71
https://github.com/owncloud/client/blob/cc15035325e9d5152f37003b67b7955282990a5a/src/libsync/theme.cpp#L98-L98

**Comment by TheOneRing** [comment]
![image](https://github.com/user-attachments/assets/830966d5-69d6-4cb3-9b6e-02c14d98abda)

**Comment by TheOneRing** [comment]
![image](https://github.com/user-attachments/assets/ab0c3147-ef3f-465b-807c-bf2d43605272)
