### ISSUE TITLE
Option to disable popup for update

### ISSUE THREAD

**Issue by CoWayger** [owncloud/client#11620]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

I would like checkbox for disabling popup with update

### Proposed solution

Checkbox for disabling popup with update, updates should be done on system level via package manager. Popup is spaming user each time OS boots. 

### Alternative solutions you considered

1. Option to disable checking of new version.
2. Option to remember, I wont see pending updates again.

**Comment by TheOneRing** [comment]
Not planned. Just install the update.
