### ISSUE TITLE
Raspberry Pi Owncloud client installable from 'sudo apt install'

### ISSUE THREAD

**Issue by robin48gx** [owncloud/client#11627]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

I would like a simple to install raspberry pi based owncloud client. 

### Proposed solution

a raspberry cloud client that can be installed from `sudo apt install`

### Alternative solutions you considered

I tried to install the client but found that its was difficult to compile and get working.
I have nextcloud working but work does not use this

### Additional context

where development machines are upgraded every few years, the store of site visit reports and photographs grows.
Sometimes it is necessary to go back and look at these and owncloud has worked well for this. My ideal solution is a 1TB drive attached to a raspberry pi. This means I wont have to re-install owncloud when the dev machine changes

**Comment by TheOneRing** [comment]
Hi @robin48gx I'm sorry, but native packages for raspberry pi are currently completely out of scope.
We might however be able to provide AppImages for arm this year.
