### ISSUE TITLE
[QA] Failing GUI tests

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11634]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

CI builds: https://drone.owncloud.com/owncloud/client/18225/3/10

Some GUI tests started failing in the master branch ci. This could be due to the changes in the object selectors.

### Screenshots

![Screenshot from 2024-05-08 12-57-40](https://github.com/owncloud/client/assets/52366632/bd675e60-a5f0-400c-9304-84639a565c54)

![Adding_multiple_accounts](https://github.com/owncloud/client/assets/52366632/752fd07f-8858-4fff-a6fd-ad4e70387892)

**Comment by TheOneRing** [comment]
The top bar changed, sorry.
I hope this will be the last broken test for now... 🙈

**Comment by saw-jan** [comment]
> The top bar changed, sorry. I hope this will be the last broken test for now... 🙈

No worries :smile:. Thanks for confirming the cause
