### ISSUE TITLE
"Local sync protocol" tab a11y issues

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11637]
The heading of the "Local synchronization log" table is not recognized as such and is only output as normal text. In addition the table itself is output without an accessible name.

**Comment by erikjv** [comment]
What does "Local sync protocol" actually mean? Same for the tab title. Is this the counterpart to "Server Activity"? If so, maybe we can remove that label and name the tab "Local Activity"?

**Comment by TheOneRing** [comment]
So the activity tab provides a server side feed of what happens on the server (oc10).
This feed also includes events for unsynced folders or events that happened in the past.
The sync protocol only contains what the client did, upload/download/move....

**Comment by saw-jan** [comment]
Tested with `ownCloud 6.0.0.13899-daily20240522 [7ba266]`

![Screenshot from 2024-05-29 09-36-35](https://github.com/owncloud/client/assets/52366632/833b101d-cc6c-41c3-89a4-4dd72c371b1b) | ![Screenshot from 2024-05-29 09-35-17](https://github.com/owncloud/client/assets/52366632/00112860-10dc-4afb-a4e5-abb2159abea8)
--|--
old | new
