### ISSUE TITLE
[QA] Automate GUI regression tests

### ISSUE THREAD

**Issue by Salipa-Gurung** [owncloud/client#11653]
### Synchronization

- [x] **Sync of multiple items** - Covered in scenario: `Scenario: Syncing folders each having 500 files`
  
   | ID | Test cases | Steps to reproduce | Expected Result | Assignee |
    --|--|--|--|--
   | 1 | Sync of multiple items | Sync 1000 files from the client to the server | Files are synced to the server | |
   | 2 | Sync of multiple items | Sync 1000 files from the server to the client | Files are synced to the client | |

- [x] **Force sync now** - Covered in scenario: `Scenario: Try to sync files having space at the end (Windows only)`
  
    | ID | Test cases | Steps to reproduce | Expected Result |  Assignee |
    --|--|--|--|--
     | 1 | Force sync now | 1. Make some changes to your files/folders in ownCloud <br>2. Go to your Account tab<br>3. Open three dots menu<br>4.Select 'Force sync now' | Sync has been trigered immediately |  |

- [x] **Pause/Resume sync** - Covered in scenario: `Scenario: Syncing a file from the server and creating a conflict`

    | ID | Test cases | Steps to reproduce | Expected Result |  Assignee |
    --|--|--|--|--
    | 1 | Pause sync | 1. Connect the client to the server<br>2. Let the file download be about >100MB<br>3. Pause the sync | Sync has been paused | |
    | 2 | Resume sync | Resume the sync | Sync has been resumed from where the download was paused | |

- [x] **Account: Add Folder**

    | ID | Test cases | Steps to reproduce | Expected Result |  Assignee |
    --|--|--|--|--
    | 1 | Add folder | 1. Open ownCloud desktop client<br>2. Go to account tab<br>3. Click Add Folder | 1. `Pick a local folder on your computer to sync` window has been opened<br>2. Cancel, Back and Next buttons present, Back button greyed out<br>3. New folder has been prepopulated but can be changed | @PrajwolAmatya <br>Step 1 and Step 3 has been covered in Step `When the user selects manual sync folder option in advanced section` <br> For Step 2 check for Cancel and Back buttons are skipped |
   | 2 | Add folder | Click Next | `Select a remote destination folder` window has been opened.<br>Buttons available:<br>1. Create Folder<br>2. Refresh<br>3. Cancel<br>4. Back<br>5. Next<br>If a folder is already synced, there is a warning at the bottom of the window | @PrajwolAmatya https://github.com/owncloud/client/pull/11668 |
   | 3 | Add folder | Create a new folder by clicking on `Create folder` button | New folder has been created | https://github.com/owncloud/client/pull/11668 |
   | 4 | Add folder | 1. Add a new folder on the server<br>2. Click `Refresh` | New folder has been shown in the list | https://github.com/owncloud/client/pull/11668 |
   | 5 | Add folder | 1. Pick a folder (with at least 2 subfolders)<br>2. Click Next | `Deselect remote folders you do not wish to sync` window has been opened.<br>Buttons available:<br>1. Cancel<br>2. Back<br>3. Add Sync Connection<br>User can choose virtual files | Covered in `Scenario: Sync only one folder from the server` |
  | 6 | Add new account and new folder | 1. Add a new account<br>2. Add a new folder<br>3. Check the paths | 1. When adding a new account, the number in brackets gets increased e.g. /Users/hana/ownCloud - [demo@demo.owncloud.com](mailto:demo@demo.owncloud.com) (41)<br>2. When adding a new folder, we get another pair of brackets now e.g. /Users/hana/ownCloud - [demo@demo.owncloud.com](mailto:demo@demo.owncloud.com) (41) (2) | https://github.com/owncloud/client/pull/11710 |

- [x] **Remove folder sync connection**

    | ID | Test cases | Steps to reproduce | Expected Result |  Assignee |
    --|--|--|--|--
    | 1 | Try to remove folder sync connection | 1. Go to Account tab<br>2. Click on the three dots menu<br>3. Select Remove folder sync connection | `Confirm Folder Sync Connection Removal` dialog is shown with following message: [ Do you really want to stop syncing the folder <local-sync-path>?<br>Note: This will not detete any files ]| @PrajwolAmatya https://github.com/owncloud/client/pull/11725  |
    | 2 | Cancel `Confirm Folder Sync Connection Removal` dialog | Select Cancel | Sync has been resumed from where the download was paused | https://github.com/owncloud/client/pull/11725 |
    | 3 | Remove Folder Sync Connection | 1. Select "Remove folder sync connection" from context menu<br>2. Click on Remove Folder Sync Connection button | 1. Folder has been removed from the list of folder sync connection in the Account tab<br>2. No data have been deleted locally<br>3. No data have been deleted on the server | https://github.com/owncloud/client/pull/11725 |

- [x] **Selective sync** - Covered in scenario `Scenario: Sync only one folder from the server`
  
   | ID | Test cases | Steps to reproduce | Expected Result | Assignee |
    --|--|--|--|--
   | 1 | Selective sync | Verify if folder is checked in the Account tab, it gets synchronized | 1. Folder has been synchronized<br>2. Checking the folder triggers a warning that all unchecked folders will be removed locally | test coverage available for windows |
   | 2 | Selective sync | Verify if folder is not checked in the Account tab, it doesn't get synchronized | 1. Folder has not been synchronized<br>2. Unchecking the folder triggers a warning that the folder will be removed from your local file system | test coverage available for windows |
  | 3 | Selective sync | 1. Add a new account<br>2. Check 'Advance configuration' option<br>3. Choose 'Configure synchronization manually'<br>4. Select a folder which has two subfolders and deselect one folder<br>5. Click 'Add Sync Connection' | 1. Just the selected folder is synced<br>2. [Unchecking the folder triggers a warning that the folder will be removed from your local file system](https://github.com/owncloud/client/issues/10468) | |

### Activity
- [x] **Activity tab - basic**
  
   | ID | Test cases | Steps to reproduce | Expected Result | Assignee |
    --|--|--|--|--
   | 1 | Activity tab - basic | Verify Activity tab includes the below tabs<br>1. Server activity<br>2. Sync protocol | Activity tab contains all the necessary information | https://github.com/owncloud/client/pull/11726 |
   | 2 | Activity tab - basic | Verify there is some content in these tabs | There is some content in these tabs | https://github.com/owncloud/client/pull/11726 |

### File/Folder operations 
- [x] **Rename**
  
   | ID | Test cases | Steps to reproduce | Expected Result | Assignee |
    --|--|--|--|--
   | 1 | Rename | 1. Make sure you have only one single file in your ownCloud<br>2. Rename the file | File has been renamed (no pop-up message "All files in the sync folder 'ownCloud' folder were deleted on the server....". )[#7204](https://github.com/owncloud/client/issues/7204) | Covered in scenario: `Scenario: Rename a file and a folder` |

- [x] **Delete**
  
   | ID | Test cases | Steps to reproduce | Expected Result | Assignee |
    --|--|--|--|--
   | 1 | Delete | 1. Delete everything (all files and folder)<br>A warning message that all the files in your local sync folder were deleted<br>2. Select `Keep files` | Files are recreated during the sync | @Salipa-Gurung https://github.com/owncloud/client/pull/11677 NOTE: [comment](https://github.com/owncloud/client/pull/11677#issuecomment-2157496257) |

**Comment by PrajwolAmatya** [comment]
All tasks have been covered and tests scenarios are added for the cases that are not covered. Closing this issue as completed.
