### ISSUE TITLE
Flatpak release

### ISSUE THREAD

**Issue by e-renna** [owncloud/client#11657]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

It would be great if the team at ownCloud could release an official Flatpak of the ownCloud client.
[Flatpak](https://www.flatpak.org/) supports 38 Linux distributions, and has become the default way to install applications in atomic distributions such as Fedora Silverblue.

### Proposed solution

Flatpak provides all the information to release a flatpak of an application in their [documentation](https://docs.flatpak.org/en/latest/introduction.html).

### Additional context

This was previously raised in 2017 in #5716 regarding creating a Flatpak version of the NextCloud client.
However, 7 years have passed, this request is specific to ownCloud client (not NextCloud), and Flatpak popularity has increased. The distributions that support Flatpak have also increased, meaning that with a single release ownCloud would provide their client to 38 different distributions.

**Comment by TheOneRing** [comment]
We provide official AppImages, a community provided Flatpack would be more than welcome.

**Comment by TorrSamaho** [comment]
> We provide official AppImages, a community provided Flatpack would be more than welcome.

I gave this a try and reworked the flatpak manifest for the Nextcloud client to build the ownCloud client instead: https://github.com/TorrSamaho/com.owncloud.desktopclient.owncloud

At least at first glance, the client GUI seems to work fine (tested under openSUSE Aeon).

**Comment by iasdeoupxe** [comment]
Follow-up available in #11989

**Comment by bjoli** [comment]
> > We provide official AppImages, a community provided Flatpack would be more than welcome.
> 
> I gave this a try and reworked the flatpak manifest for the Nextcloud client to build the ownCloud client instead: https://github.com/TorrSamaho/com.owncloud.desktopclient.owncloud
> 
> At least at first glance, the client GUI seems to work fine (tested under openSUSE Aeon).

I tried installing this and could not. It tries initializing the qtkeychain repo, but then fails with

```
git: 'remote-https' is not a git command. See 'git --help'.
fatal: remote helper 'https' aborted session
Failed to download sources: module qtkeychain: Child process exited with code 128
```

which is weird, since my git has git remote-https. Does flatpak bundle it's own git? I also run aeon, but my setup is a bit wonky: apart from the base system I install every command through guix. But since flatpak-builder finds git (I only have one set installed) I don't understand why it is not working...

Sorry for mentioning it here, but the linked repo has no bug reports.

**Comment by TorrSamaho** [comment]
> Sorry for mentioning it here, but the linked repo has no bug reports.

I now activated issues on that repo. Feel free to open an issue there.
