### ISSUE TITLE
[QA] client silently disconnects

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#11667]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Seen with ownCloud 5.2.1.13040 on linux mint 20.3

The client is running long time on a laptop, connected to my account at cloud.owncloud.com (and 2 other servers)
The laptop is suspended and resumed ca. twice a day.

Today I noticed a 
![grafik](https://github.com/owncloud/client/assets/1108546/bf033dc5-c4f2-48e5-86f5-9f1b18076ffe)
icon in the status bar.

The client window shows
![grafik](https://github.com/owncloud/client/assets/1108546/69696920-b113-4535-b07e-cedb4b31a3b3)

The Account drop down offers 'log out', so the client thinks it is still logged in, despite the red error message telling me the opposite.

### Expected behavior

I expect to see re-connect attempts, maybe a client window prompting me for credentials or mabye a browser window prompting me of oauth.

### Logs

[owncloud-11667.log.zip](https://github.com/owncloud/client/files/15486825/owncloud-11667.log.zip)

Log messages repeat every 30 seconds, several MB per hour.

### Client version number

ownCloud 5.2.1.13040 on linux mint 20.3

### Desktop environment (Linux only)

ownCloud 5.2.1.13040 on linux mint 20.3

**Comment by TheOneRing** [comment]
It's just a failed sync, does a force sync clear the issue?
