### ISSUE TITLE
Spaces support on Linux

### ISSUE THREAD

**Issue by poscat0x04** [owncloud/client#11670]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Currently the owncloud client doesn't seem to support syncing ocis spaces on Linux.

### Proposed solution

Add support for spaces on Linux.

**Comment by TheOneRing** [comment]
We support spaces since years, I assume your distro is shipping a very old client, can you please report the client version and the distro.
I'd suggest you to follow the instructions to install an official ownCloud build, https://owncloud.com/desktop-app/ .

**Comment by poscat0x04** [comment]
It seems that I somehow missed the spaces button... my apologies.
