### ISSUE TITLE
client sometime crashes in OCC::AccountSettings::addModalLegacyDialog at `src/gui/accountsettings.cpp:559`

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11673]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Desktop client sometimes can crash in `OCC::AccountSettings::addModalLegacyDialog` at `/drone/src/src/gui/accountsettings.cpp:559`

Crashed in:
- https://drone.owncloud.com/owncloud/client/18407
- https://drone.owncloud.com/owncloud/client/18408

```c
###########################################
Scenario: simple sharing of a file by public link with default expiration date
-------------------------------------------
Executable: /drone/src/build/bin/owncloud
Timestamp: 2024-06-04 05:42:03
Process ID: 4715
Signal Number: 6
-------------------------------------------
<<<<< STACKTRACE START >>>>>
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/drone/src/build/bin/owncloud -s --logfile - --logdebug --logflush'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f82d0f42834 in __pthread_kill_implementation () from /lib64/libc.so.6
[Current thread is 1 (Thread 0x7f82cd32e940 (LWP 4715))]
#0  0x00007f82d0f42834 in __pthread_kill_implementation () from /lib64/libc.so.6
No symbol table info available.
#1  0x00007f82d0ef08ee in raise () from /lib64/libc.so.6
No symbol table info available.
#2  0x00007f82d0ed898f in abort () from /lib64/libc.so.6
No symbol table info available.
#3  0x00007f82d14aea4a in qAbort() () from /ownbuild/master/linux-gcc-x86_64-squish/lib/libQt6Core.so.6
No symbol table info available.
#4  0x00007f82d14e3a05 in ?? () from /ownbuild/master/linux-gcc-x86_64-squish/lib/libQt6Core.so.6
No symbol table info available.
#5  0x00007f82d14af6d8 in QMessageLogger::fatal(char const*, ...) const () from /ownbuild/master/linux-gcc-x86_64-squish/lib/libQt6Core.so.6
No symbol table info available.
#6  0x00007f82d14ae9c7 in qt_assert(char const*, char const*, int) () from /ownbuild/master/linux-gcc-x86_64-squish/lib/libQt6Core.so.6
No symbol table info available.
#7  0x00007f82d434c411 in OCC::AccountSettings::addModalLegacyDialog (this=0x1549820, widget=0x5441500, sizePolicy=OCC::AccountSettings::ModalWidgetSizePolicy::Expanding) at /drone/src/src/gui/accountsettings.cpp:559
        outerWidget = 0x546a470
        groupBox = 0x5459350
#8  0x00007f82d43bffbf in OCC::ownCloudGui::slotShowShareDialog (this=0x1218cf0, sharePath=..., localPath=..., startPage=OCC::ShareDialogStartPage::UsersAndGroups) at /drone/src/src/gui/owncloudgui.cpp:1078
```

### Logs

[clientlog.log](https://github.com/user-attachments/files/15543233/serverlog.1.log)
[stacktrace.log](https://github.com/user-attachments/files/15543234/stacktrace.1.log)

### Client version number

git master

**Comment by erikjv** [comment]
@TheOneRing So code allows for multiple sharing dialogs, but only one dialog per path. With the current UI all being in 1 window, I would like to change this to only allow for 1 "dialog", and remove any already open "dialogs". That way we only have to keep track of 1 widget: when the slot is triggered, check if there is an open "dialog", and if so, delete it. Then display the one for the latest request.

**Comment by TheOneRing** [comment]
Hmm as a modal dialog the behavior should probably be to raise the current modal window.
Closing a dialog with unfinished actions could cause other issues.
So I suggest raising the old window without creating a new page in the dialog.

**Comment by erikjv** [comment]
@saw-jan when this happens again, please attach a new log file

**Comment by saw-jan** [comment]
Similar crash: https://drone.owncloud.com/owncloud/client/19287/2/16
[stacktrace.log](https://github.com/user-attachments/files/16925347/stacktrace.log)
[clientlog.log](https://github.com/user-attachments/files/16925355/clientlog.log)
![Screenshot from 2024-09-09 10-11-08](https://github.com/user-attachments/assets/c0422d14-dfec-49ad-922c-36c9fa3ddc79)

**Comment by erikjv** [comment]
Ok, that shows that there was a previously raised dialog for the share, which is now being re-used. And at that point the delete-on-close attribute is gone, triggering the assert. @TheOneRing : we have to discuss what we do with this. I'm not a fan of that caching/re-use of dialogs.

**Comment by erikjv** [comment]
Show only 1 share "dialog", and don't cache others.
