### ISSUE TITLE
Server activity tab: tab order does not follow visual arrangement

### ISSUE THREAD

**Issue by erikjv** [owncloud/client#11679]

**Comment by saw-jan** [comment]
Tested with `ownCloud 6.0.0.14185-daily20240710 [a947c5]`

Tab navigation flow: `current activity tab` -> `filter` -> `table`
![Screenshot from 2024-07-10 11-50-02](https://github.com/owncloud/client/assets/52366632/e3a20ec6-365a-4002-a487-7bbaf3ae1bf2) | ![Screenshot from 2024-07-10 11-50-05](https://github.com/owncloud/client/assets/52366632/0e91eea8-dd62-4705-a729-dd5a4d4f5a2e) | ![Screenshot from 2024-07-10 11-50-06](https://github.com/owncloud/client/assets/52366632/757763bf-aefc-453f-a8f2-6a1b60d9ddae)
--|--|--

**Comment by saw-jan** [comment]
Tested on `ownCloud 6.0.0.14688-daily20240918 [967f29]`

![Screenshot from 2024-09-18 18-35-58](https://github.com/user-attachments/assets/443f2fb6-6bd2-4152-807d-b27956f7b89f)

Tab flow might not be correct: :question: 
`Server Activity` -> `Notifications` -> `Server Activities: Filter` -> `Server Activities: table` -> `Notifications: [Dismiss|Accept|Decline]`

**Comment by saw-jan** [comment]
^ CC @erikjv @TheOneRing

**Comment by erikjv** [comment]
Please open a new issue for that. It is not correct, but this tab is a bit of a headache, so we might not fix it for the next release.

**Comment by saw-jan** [comment]
Opened a new issue: https://github.com/owncloud/client/issues/11890
