### ISSUE TITLE
Release 5.3.0

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11671]
### Administration

* [x] QA: Update [Test Plans](https://confluence.owncloud.com/display/OG/Desktop+Client+Test+Plan+Maintenance)
* [x] Update [supported platforms](https://doc.owncloud.com/desktop/next/installing.html#system-requirements) @michaelstingl
* [x] QA: Check the translations coming from transifex: https://github.com/owncloud/client/commits/ -> Filter based on a release branch/tag and search for `[tx] updated client translations from transifex [skip ci]`
* [x] DEV: Check for new OpenSSL version 
* [x] DEV: Update [dependencies](https://confluence.owncloud.com/display/OG/Dependencies)
* [x] DEV: For a major release create `X` version branch
  * [x] QA: In drone adjust the branch for nightly [GUI tests](https://confluence.owncloud.com/display/OG/Squish+Testing#SquishTesting-Prerequisite) @individual-it
* [x] QA: Communicate documentation changes  
   * [x] Inform ``#client-dev-internal`` (@mmattel) about the start of testing phase (latest a week before the release!). They'll prepare a PR with respective doc version
   * [x] Open issues in ``docs-client-desktop`` repo for already known doc-relevant items and mark them accordingly, e.g. backport to 2.X.x necessary
* [x] Decide if the prerelease stage will be public or internal @michaelstingl 
* [x] Announce feature freeze in ``#release_coordination`` channel before Beta build
* [x] Announce string freeze in ``#release_coordination`` channel a few days later
   * [x] Inform ``#client-dev-internal`` about it so that they can do the translations
  
### Copy for Each Build (Beta/RC)

* [x] DEV: Tag (Beta or RC) and build [builds](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-Sprintbuild) for theme 'ownCloud' and 'testpilotcloud' (includes ChangeLog for the tag on https://github.com/owncloud/client/releases/)
* [x] QA: [Smoke test](https://owncloud.testrail.io/index.php?/cases/view/2469) (for public prelease)
* [x] DEV: GitHub release
* [x] Beta/RC [Communication](https://confluence.owncloud.com/x/loJK)
    * [ ] Inform ``#updates`` that we have Beta/RC    
    * [ ] For public prerelease: Inform ``#marketing`` and tell them to send email to beta testers
    * [ ] For public prerelease: Write/edit Central post https://central.owncloud.org/tags/c/news/desktop with link to github release 
* [ ] DEV: Prepare the update server for new version (AppImages included)
   * [ ] DEV: Provide 'testpilotcloud' on **Beta** update channel
     
### QA 

* [x] QA: [Antivirus scan](https://www.virustotal.com/gui/home/upload) the first RC
* [x] QA: [Upload](https://confluence.owncloud.com/display/OG/Upload+linux+gpg+keys+to+key+server) linux gpg keys to key server (Automated) - (confirmed via [package install](https://download.owncloud.com/desktop/ownCloud/testing/5.3.0.13937-rc.1/linux/download/))
* [x] QA: Check Crash reporter:
    1. Start `owncloud --debug` on cmd line
    2. system tray right-click menu: `Crash now - qt fatal` -> report window not empty, sending the report works
  * [x] Windows  
  * [x] macOS
  * [x] AppImage (Linux)
* [x] [Automated tests](https://confluence.owncloud.com/display/OG/Automated+Tests) (for the first beta and the last RC):
  * [x] QA: Linux GUI tests on a tag ( [ :heavy_check_mark: ](https://drone.owncloud.com/owncloud/client/18373))
  * [x] QA: Windows GUI tests
* [x] QA: All [Linux platform install](https://confluence.owncloud.com/display/OG/Automated+Tests#AutomatedTests-LinuxInstallTest)
* [x] Manual tests:
   * [x] QA: [Changelog](https://github.com/owncloud/client/releases/tag/v5.3.0-rc.1) test
   * [x] QA: [Smoke test](https://owncloud.testrail.io/index.php?/tests/view/5067&group_by=tests:status_id&group_order=asc&group_id=3)
   * ~[ ] QA: Regression test~
   * ~[ ] QA: Branded regression test~

### Prerequisites for final release

* [ ] DEV: Create vX.Y.Z release tag in client repo and everywhere else
* [ ] DEV: bump VERSION.cmake in master to say 3.(x+1).x unless already done.

### Final Rebuild after QA Approval

* [ ] QA: Inform on ``#client-dev-internal`` that the tag for the final release will be set a day or at least half a day __before__ (only for a major/minor release). They'll merge docs PR before that.
* [x] DEV: Create final release tag (e.g., `v4.5.6`)
* [x] DEV: Create [builds](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-Tags) for themes 'ownCloud' and 'testpilotcloud' for final release tag
* [x] DEV: Update version for future builds
* [x] QA: Check [squish tests](https://confluence.owncloud.com/display/OG/Squish+Testing#SquishTesting-Finalreleasestep) running successfuly on [drone](https://drone.owncloud.com/owncloud/client) for the final tag v3.X.x
* [ ] QA: Create a new release issue for a branded release if needed [Branded Client Release Template](https://github.com/owncloud/enterprise/blob/master/internal_release_templates/internal_client_release_template.md)

### Final Steps

* [x] QA: [Smoke test](https://owncloud.testrail.io/index.php?/tests/view/5066&group_by=tests:status_id&group_order=asc&group_id=3)
* [x] DEV: Publish the release in GitHub
* [ ] QA: Update lines 4 and 5 of [install docs](https://github.com/owncloud/docs-client-desktop/blob/master/modules/ROOT/pages/installing.adoc) with the final build number. Merge into master and backport to the respective branch
* [ ] QA: Check that [documentation](https://doc.owncloud.com/desktop/next/) offers the new version
* [x] DEV: Merge version branch into master
* [ ] DEV: Update [SBOM](https://cloud.owncloud.com/f/6072843)

### [Marketing and Communication](https://confluence.owncloud.com/display/OG/Marketing+and+Communication)
   
* [ ] QA: Ping ``#marketing``at marketing@owncloud.com; @bwalter to update links on https://owncloud.com/desktop-app/ (provide links from github releases) and @mfeilner to update [wiki de](https://de.wikipedia.org/wiki/OwnCloud), [wiki en](https://en.wikipedia.org/wiki/OwnCloud), [wikidata](https://www.wikidata.org/wiki/Q20763576))
* [ ] QA: Central post https://central.owncloud.org/tags/c/news/desktop
* [ ] QA: Inform on ``#updates`` channel
* [ ] QA: Inform [packagers](https://confluence.owncloud.com/x/QYLEAg)

### Infrastructure Check

* [x] QA/DEV: Update [stable channel](https://confluence.owncloud.com/display/OG/Online+Updater%2C+Crash+reporter%2C+Transifex#OnlineUpdater,Crashreporter,Transifex-UpdatetheUpdater) in the owncloud hosted auto updater
* [x] QA: Check the linux download pages whether the URLs are correct (e.g. contain stable, not testing)
* [x] QA: Ensure that the [client release template](https://github.com/owncloud/client/blob/master/.github/release_template.md) is up to date

### A Few Days After the Release

* [x] DEV: Check the [crash reporter](https://confluence.owncloud.com/display/OG/Online+Updater%2C+Crash+reporter%2C+Transifex#OnlineUpdater,Crashreporter,Transifex-CrashReporter) for bad/frequent crashes

**Comment by saw-jan** [comment]
Might need to update this release ticket and template as well

CC @TheOneRing

**Comment by saw-jan** [comment]
|| Linux Package Installation Report |
|-|-|
|date| Wed Jun  5 05:19:22 PM +0545 2024
|repourl| https://download.owncloud.com/desktop/ownCloud/testing/5.3.0.13937-rc.1/linux/
|package| owncloud-client

<details><summary>Test details (click to view)</summary>

|Platform|Test|Result|
|-|-|-|
|debian:12|01_cmd_vers|	ownCloud 5.3.0.13937-rc.1
|debian:12|01_cmd_vers|	Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
|fedora:38|01_cmd_vers|	ownCloud 5.3.0.13937-rc.1
|fedora:38|01_cmd_vers|	Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
|ubuntu:22.04|01_cmd_vers|	ownCloud 5.3.0.13937-rc.1
|ubuntu:22.04|01_cmd_vers|	Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
|opensuse/leap:15.5|01_cmd_vers|	ownCloud 5.3.0.13937-rc.1
|opensuse/leap:15.5|01_cmd_vers|	Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
|debian:12|02_integration|	(5.3.0\~rc+oc-1): dolphin nemo nautilus caja
|fedora:38|02_integration|	(5.3.0\~rc-1): dolphin nemo nautilus caja
|ubuntu:22.04|02_integration|	(5.3.0\~rc+oc-1): dolphin nemo nautilus caja
|opensuse/leap:15.5|02_integration|	(5.3.0\~rc-1): dolphin nemo nautilus caja
|debian:12|05_xvfb_run|	Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
|debian:12|05_xvfb_run|	Qt shall use a UTF-8 locale ("C.UTF-8") instead. If this causes problems,
|debian:12|05_xvfb_run|	reconfigure your locale. See the locale(1) manual for more information.
|debian:12|05_xvfb_run|	Fontconfig error: Cannot load default config file
|debian:12|05_xvfb_run|	0x200006 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0 -> (750,20)  -> [Quit]  -> yDetected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
|debian:12|05_xvfb_run|	Qt shall use a UTF-8 locale ("C.UTF-8") instead. If this causes problems,
|debian:12|05_xvfb_run|	reconfigure your locale. See the locale(1) manual for more information.
|debian:12|05_xvfb_run|	Fontconfig error: Cannot load default config file
|debian:12|05_xvfb_run|	 -> OK
|fedora:38|05_xvfb_run|	Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
|fedora:38|05_xvfb_run|	Qt shall use a UTF-8 locale ("C.UTF-8") instead. If this causes problems,
|fedora:38|05_xvfb_run|	reconfigure your locale. See the locale(1) manual for more information.
|fedora:38|05_xvfb_run|	Fontconfig error: Cannot load default config file
|fedora:38|05_xvfb_run|	0x200006 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0 -> (750,20)  -> [Quit]  -> yDetected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
|fedora:38|05_xvfb_run|	Qt shall use a UTF-8 locale ("C.UTF-8") instead. If this causes problems,
|fedora:38|05_xvfb_run|	reconfigure your locale. See the locale(1) manual for more information.
|fedora:38|05_xvfb_run|	Fontconfig error: Cannot load default config file
|fedora:38|05_xvfb_run|	 -> OK
|ubuntu:22.04|05_xvfb_run|	Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
|ubuntu:22.04|05_xvfb_run|	Qt shall use a UTF-8 locale ("C.UTF-8") instead. If this causes problems,
|ubuntu:22.04|05_xvfb_run|	reconfigure your locale. See the locale(1) manual for more information.
|ubuntu:22.04|05_xvfb_run|	Fontconfig error: Cannot load default config file
|ubuntu:22.04|05_xvfb_run|	0x200006 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0 -> (750,20)  -> [Quit]  -> yDetected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
|ubuntu:22.04|05_xvfb_run|	Qt shall use a UTF-8 locale ("C.UTF-8") instead. If this causes problems,
|ubuntu:22.04|05_xvfb_run|	reconfigure your locale. See the locale(1) manual for more information.
|ubuntu:22.04|05_xvfb_run|	Fontconfig error: Cannot load default config file
|ubuntu:22.04|05_xvfb_run|	 -> OK
|opensuse/leap:15.5|05_xvfb_run|	Detected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
|opensuse/leap:15.5|05_xvfb_run|	Qt shall use a UTF-8 locale ("C.UTF-8") instead. If this causes problems,
|opensuse/leap:15.5|05_xvfb_run|	reconfigure your locale. See the locale(1) manual for more information.
|opensuse/leap:15.5|05_xvfb_run|	Fontconfig error: Cannot load default config file
|opensuse/leap:15.5|05_xvfb_run|	0x100006 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0 -> (750,20)  -> [Quit]  -> yDetected system locale encoding (ANSI_X3.4-1968, locale "C") is not UTF-8.
|opensuse/leap:15.5|05_xvfb_run|	Qt shall use a UTF-8 locale ("C.UTF-8") instead. If this causes problems,
|opensuse/leap:15.5|05_xvfb_run|	reconfigure your locale. See the locale(1) manual for more information.
|opensuse/leap:15.5|05_xvfb_run|	Fontconfig error: Cannot load default config file
|opensuse/leap:15.5|05_xvfb_run|	 -> OK
|debian:12|06_xvfb_appimage|	timeout: failed to run command '/usr/bin/client.appimage': No such file or directory
|debian:12|06_xvfb_appimage|	/mnt/test/05-xvfb-run.sh: line 36: /root/.config/\*/owncloud.cfg: No such file or directory
|debian:12|06_xvfb_appimage|	/usr/bin/xvfb-run: 184: /usr/bin/client.appimage: not found
|debian:12|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|debian:12|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|debian:12|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|debian:12|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|debian:12|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|debian:12|06_xvfb_appimage|	convert-im6.q16: unable to open image `/var/tmp/Xvfb_screen0': No such file or directory @ error/blob.c/OpenBlob/2924.
|debian:12|06_xvfb_appimage|	convert-im6.q16: no images defined `/mnt/test/assets/screenshot_01.png' @ error/convert.c/ConvertImageCommand/3229.
|debian:12|06_xvfb_appimage|	settings window did not open.
|fedora:38|06_xvfb_appimage|	timeout: failed to run command '/usr/bin/client.appimage': No such file or directory
|fedora:38|06_xvfb_appimage|	/mnt/test/05-xvfb-run.sh: line 36: /root/.config/\*/owncloud.cfg: No such file or directory
|fedora:38|06_xvfb_appimage|	/usr/bin/xvfb-run: line 181: /usr/bin/client.appimage: cannot execute: required file not found
|fedora:38|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|fedora:38|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|fedora:38|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|fedora:38|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|fedora:38|06_xvfb_appimage|	convert: unable to open image '/var/tmp/Xvfb_screen0': No such file or directory @ error/blob.c/OpenBlob/3571.
|fedora:38|06_xvfb_appimage|	convert: no images defined `/mnt/test/assets/screenshot_01.png' @ error/convert.c/ConvertImageCommand/3362.
|fedora:38|06_xvfb_appimage|	settings window did not open.
|ubuntu:22.04|06_xvfb_appimage|	timeout: failed to run command '/usr/bin/client.appimage': No such file or directory
|ubuntu:22.04|06_xvfb_appimage|	/mnt/test/05-xvfb-run.sh: line 36: /root/.config/\*/owncloud.cfg: No such file or directory
|ubuntu:22.04|06_xvfb_appimage|	/usr/bin/xvfb-run: 184: /usr/bin/client.appimage: not found
|ubuntu:22.04|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|ubuntu:22.04|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|ubuntu:22.04|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|ubuntu:22.04|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|ubuntu:22.04|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|ubuntu:22.04|06_xvfb_appimage|	convert-im6.q16: unable to open image `/var/tmp/Xvfb_screen0': No such file or directory @ error/blob.c/OpenBlob/2924.
|ubuntu:22.04|06_xvfb_appimage|	convert-im6.q16: no images defined `/mnt/test/assets/screenshot_01.png' @ error/convert.c/ConvertImageCommand/3229.
|ubuntu:22.04|06_xvfb_appimage|	settings window did not open.
|opensuse/leap:15.5|06_xvfb_appimage|	timeout: failed to run command '/usr/bin/client.appimage': No such file or directory
|opensuse/leap:15.5|06_xvfb_appimage|	/mnt/test/05-xvfb-run.sh: line 36: /root/.config/\*/owncloud.cfg: No such file or directory
|opensuse/leap:15.5|06_xvfb_appimage|	/usr/bin/xvfb-run: line 168: /usr/bin/client.appimage: No such file or directory
|opensuse/leap:15.5|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|opensuse/leap:15.5|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|opensuse/leap:15.5|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|opensuse/leap:15.5|06_xvfb_appimage|	xwininfo: error: unable to open display ":99"
|opensuse/leap:15.5|06_xvfb_appimage|	convert: unable to open image '/var/tmp/Xvfb_screen0': No such file or directory @ error/blob.c/OpenBlob/3536.
|opensuse/leap:15.5|06_xvfb_appimage|	convert: no images defined `/mnt/test/assets/screenshot_01.png' @ error/convert.c/ConvertImageCommand/3322.
|opensuse/leap:15.5|06_xvfb_appimage|	settings window did not open.
|debian:12|08_appimage|	- -
|fedora:38|08_appimage|	- -
|ubuntu:22.04|08_appimage|	- -
|opensuse/leap:15.5|08_appimage|	- -
|debian:12|10_key_expiry|	<info@owncloud.com> expires: 2025-03-20
|debian:12|10_key_expiry|	<info@owncloud.com> expires: 2025-05-29
|fedora:38|10_key_expiry|	<info@owncloud.com> expires: 2025-01-03
|fedora:38|10_key_expiry|	<info@owncloud.com> expires: 2025-03-20
|ubuntu:22.04|10_key_expiry|	<info@owncloud.com> expires: 2025-03-20
|ubuntu:22.04|10_key_expiry|	<info@owncloud.com> expires: 2025-05-29
|opensuse/leap:15.5|10_key_expiry|	<info@owncloud.com> expires: 2025-01-03
|opensuse/leap:15.5|10_key_expiry|	<info@owncloud.com> expires: 2025-03-20
|debian:12|15_wayland|	Available: offscreen, xcb, minimal, linuxfb, vnc.
|fedora:38|15_wayland|	Available: offscreen, xcb, minimal, linuxfb, vnc.
|ubuntu:22.04|15_wayland|	Available: offscreen, xcb, minimal, linuxfb, vnc.
|opensuse/leap:15.5|15_wayland|	Available: offscreen, xcb, minimal, linuxfb, vnc.
|debian:12|20_qttrans_de|	OK 6
|fedora:38|20_qttrans_de|	OK 6
|ubuntu:22.04|20_qttrans_de|	OK 6
|opensuse/leap:15.5|20_qttrans_de|	OK 6
|debian:12|30_openssl_vers|	Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
|fedora:38|30_openssl_vers|	Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
|ubuntu:22.04|30_openssl_vers|	Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
|opensuse/leap:15.5|30_openssl_vers|	Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
|debian:12|50_sync_excl.lst|	392 /opt/owncloud-client.AppDir/usr/etc/ownCloud/sync-exclude.lst
|fedora:38|50_sync_excl.lst|	392 /opt/owncloud-client.AppDir/usr/etc/ownCloud/sync-exclude.lst
|ubuntu:22.04|50_sync_excl.lst|	392 /opt/owncloud-client.AppDir/usr/etc/ownCloud/sync-exclude.lst
|opensuse/leap:15.5|50_sync_excl.lst|	392 /opt/owncloud-client.AppDir/usr/etc/ownCloud/sync-exclude.lst

</details>

Generated via client/linux-docker-install/run_tests.sh

**Comment by mmattel** [comment]
Note the channel `#documentation-internal` named above for informing docs is no longer available (chat is shut down). Pls correct to [client-dev-internal](https://talk.owncloud.com/group/client-dev-internal).

**Comment by T-SysDev** [comment]
We have had a issue with 5.3.0 on Windows 11 22H2. After installing 5.3.0, open Outlook, create an email, browse for an attachment, and Outlook crashes. This has happened for us in Outlook, Excel, and MS Teams. We didn't test any more than that before going back to 5.2.1.

If this is the wrong thread for this, please move at will. Thanks.

**Comment by saw-jan** [comment]
>We have had a issue with 5.3.0 on Windows 11 22H2. After installing 5.3.0, open Outlook, create an email, browse for an attachment, and Outlook crashes. This has happened for us in Outlook, Excel, and MS Teams. We didn't test any more than that before going back to 5.2.1.

Related to https://github.com/owncloud/client/pull/11692 ?

CC @TheOneRing

**Comment by TheOneRing** [comment]
> > We have had a issue with 5.3.0 on Windows 11 22H2. After installing 5.3.0, open Outlook, create an email, browse for an attachment, and Outlook crashes. This has happened for us in Outlook, Excel, and MS Teams. We didn't test any more than that before going back to 5.2.1.
> 
> Related to #11692 ?
> 
> CC @TheOneRing

See https://github.com/owncloud/client/issues/11691 for which I provided a hotfix release https://github.com/owncloud/client/releases/tag/v5.3.1

**Comment by TheOneRing** [comment]
Thanks everyone involved.
Even so we didn't check all the boxes above, I consider this release as done.
