### ISSUE TITLE
Local activity tab: tab order does not follow visual arrangement

### ISSUE THREAD

**Issue by erikjv** [owncloud/client#11680]

**Comment by saw-jan** [comment]
Tested with `ownCloud 6.0.0.14185-daily20240710 [a947c5]`

Tab navigation flow: `current activity tab` -> `filter` -> `table`
![Screenshot from 2024-07-10 11-49-45](https://github.com/owncloud/client/assets/52366632/6a4f34c6-788b-4bf7-9289-dfcd71486604) | ![Screenshot from 2024-07-10 11-49-49](https://github.com/owncloud/client/assets/52366632/7166c916-5db3-4007-9019-baee648729f5) | ![Screenshot from 2024-07-10 11-49-51](https://github.com/owncloud/client/assets/52366632/38d081da-0c07-41a4-9673-28ba33c21d08)
--|--|--
