### ISSUE TITLE
Capturing logs on crash fails for branded clients

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11686]
In  https://github.com/owncloud/client/blob/9a6fa8a9389133337f0da1cbd9762204240ef0af/src/libsync/logger.cpp#L245-L245
We use `APPLICATION_SHORTNAME` to write the log file.

In the reporter we however use https://github.com/owncloud/client/blob/9a6fa8a9389133337f0da1cbd9762204240ef0af/src/crashreporter/CrashReporterConfig.h.in#L8-L8

**Comment by saw-jan** [comment]
Tested on `testpilotcloud-6.0.0.14184-daily20240710-x86_64.AppImage`. Logs are there
![Screenshot from 2024-07-10 10-04-07](https://github.com/owncloud/client/assets/52366632/eec8c2f0-1ffc-4a1d-b1a4-2551dbc50199)
