### ISSUE TITLE
Client should change windows folder permissions for read only spaces

### ISSUE THREAD

**Issue by b1schumacher** [owncloud/client#11694]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

If a read only share/space is mounted in windows, the client should change the folder permissions, that the user can't accidentally save files in this directory and not knowing that these files are not synced with the owncloud server. 

### Proposed solution

- The client creates the folder for read only shares/spaces as read only. 
- The user can't write any files to the windows folders which are in sync with a read only share/space. 

### Additional context

We have the fear that if folders are not sufficiently enough marked as not synced with the server, that files accidentally moved or saved in this folder are lost.
The error message within the client is not really enough to ensure that this is not happening.

**Comment by dragotin** [comment]
The client currently does not sync the file permissions from the server, and it is currently not planned to do so.

The reason for that is: The local file system is completely under control of the user. She can easily change the permissions of the synced tree any time, which would lead to numerous error situations that the client would have to handle. First and foremost, it would mean that the client would be expected to sync the permissions from the client to the server, which does not have a representation on the server currently.

With the situation now, if the user puts a file into a sync dir of a read only space, the client would display an error for the file to make the user aware.
