### ISSUE TITLE
The table on page 4 can be sorted, but the sorting status is not available to non-visual users.

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11706]
TODO: Extend the context menu with sorting, indicate the current sorting

**Comment by erikjv** [comment]
Fixed in #11723

**Comment by ishabaral** [comment]
Tested on: ownCloud-6.0.0.14988-daily20241113 [9a5ab4]

![Selection_005](https://github.com/user-attachments/assets/82c9d130-93e1-4aa2-bfdd-49c0130ee26c)
