### ISSUE TITLE
Login ui is not vertically centered

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11718]
![image](https://github.com/owncloud/client/assets/200626/803c2772-e466-4c71-91d9-a9b1d0c76cae)

**Comment by saw-jan** [comment]
Tested with `ownCloud 6.0.0.14185-daily20240710 [a947c5]`

![Screenshot from 2024-07-10 10-14-04](https://github.com/owncloud/client/assets/52366632/1d29c524-3510-4144-b348-be9714d916a6) | ![Screenshot from 2024-07-10 10-14-14](https://github.com/owncloud/client/assets/52366632/7f2b8f29-dd1a-4923-b82f-4427065e43f0)
--|--
