### ISSUE TITLE
[QA] client starts busy-loop, when server is in singleuser mode

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#11722]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen with owncloud core 10.14.0 and testpilotcloud client 5.3.1

* connect client to server using basic auth.
* wait until the inital sync is done.
* `occ maintenance:singleuser --on`
* the client starts to retry connecting. Initially one attempt ca. every 5 seconds. OK
* After ca. 40 sec, the reconnect attempts occur very fast. BAD

Expected behaviour:
* reconnect attempts may back off to longer intervals or remain at the same interval.

Client log:
[client531-busy-loop-singleuser.log](https://github.com/user-attachments/files/15991703/client531-busy-loop-singleuser.log)

### Steps to reproduce the issue

.

### Screenshots

.

**Comment by TheOneRing** [comment]
OC 10 is deprecated, and we won't add support for such exotic modes.
