### ISSUE TITLE
Add ocis update channel

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11742]
7.0 Will remove support for ownCloud 10.
We will provide 6.x builds for an extended period, users will have to either manually install a 7.x client or select a special update channel.

- Reactivate update channel selection for the desktop client
- Add `ocis` channel
- Keep default `stable`

**Comment by mmattel** [comment]
This also needs a prominent note in the docs release notes!

**Comment by ishabaral** [comment]
Tested with: `ownCloud 6.0.0.14851-daily20241019 [a46984]`

![Screenshot from 2024-11-18 11-51-02](https://github.com/user-attachments/assets/7f383cd2-74b9-4757-bd40-9c30448ee8fe)

![Screenshot from 2024-11-18 11-51-39](https://github.com/user-attachments/assets/296c7dd3-811f-42c7-9269-99f4207d2092)

![Screenshot from 2024-11-18 11-52-04](https://github.com/user-attachments/assets/cf8f9ab6-5382-4551-bbd1-1d54887e011a)
