### ISSUE TITLE
When a new unsynced space is discovered, add it to the synced folders

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11751]
Depends on https://github.com/owncloud/client/issues/11750

**Comment by saw-jan** [comment]
Tested on `ownCloud 6.0.0.14688-daily20240918 [967f29]`

All available spaces (personal, shares, project-space) are sync when adding new account

**Comment by TheOneRing** [comment]
> Tested on `ownCloud 6.0.0.14688-daily20240918 [967f29]`
> 
> All available spaces (personal, shares, project-space) are sync when adding new account

With the branding enabled, also new spaces added on the server side are automatically synced.
