### ISSUE TITLE
All elements of the page are not output according to their visual arrangement.

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11782]
Please validate.

**Comment by erikjv** [comment]
I don't know how to get Narrator or VoiceOver to read the whole dialog.

That said, we (partially) fixed the tab-order, and I think that was the cause. We still have tab-order issues: the network part is only focussed after everything else on the parenting page is cycled through. This means: .... -> Log Settings button -> About button -> No Proxy radio-button.

**Comment by erikjv** [comment]
@TheOneRing setting the widget inside the Network Settings group box gives it tab-focus, but nothing inside it is focussed. The first checkbox is only tab-focussed after the About button.

**Comment by TheOneRing** [comment]
> @TheOneRing setting the widget inside the Network Settings group box gives it tab-focus, but nothing inside it is focussed. The first checkbox is only tab-focussed after the About button.

You mean you gave it StrongFocus?

**Comment by saw-jan** [comment]
Tested on `ownCloud 6.0.0.14688-daily20240918 [967f29]`

Tab order: `General Settings` -> `Advanced` -> `Network` -> `Network: Proxy settings` -> `Network: Download Bandwidth` -> `Network: Upload Bandwidth` -> `About`
