### ISSUE TITLE
The visually hidden elements of the "Language" drop-down element are output by screen readers.

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11781]

**Comment by erikjv** [comment]
Will also test this on macOS.

**Comment by TheOneRing** [comment]
Could also be fixed with Qt6.
With the normal menus we opened, we had the issue that they did not receive focus, and were thus not read by the screen reader.
We worked around by manually calling focus()

**Comment by erikjv** [comment]
Fixed, probably by using Qt6
