### ISSUE TITLE
The group with the settings is located within four nested group elements, whereby none of these groups have group labels.

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11780]
Please validate.

**Comment by erikjv** [comment]
It's a bit hard to say, but I do sometimes get "Settings pane, group, group, navigation bar, pane". So it looks like it's actually the navigation bar causing this?

**Comment by erikjv** [comment]
Note: it is a known issue that the network settings get tab-focus after the buttons on the bottom had tab-focus.

**Comment by erikjv** [comment]
> Note: it is a known issue that the network settings get tab-focus after the buttons on the bottom had tab-focus.

This has been fixed.
