### ISSUE TITLE
Theme::syncNewlyDiscoveredSpaces

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11799]
When `true`, also do the following:
- Disable space removal (otherwise the removed space is immediately added)
- Hide add space button (there is no space to add manually)
- ...

**Comment by saw-jan** [comment]
Tested on `ownCloud 6.0.0.14688-daily20240918 [967f29]`

![Screenshot from 2024-09-18 17-54-27](https://github.com/user-attachments/assets/4b098c56-0109-4065-abe0-b80f0a499caa)
