### ISSUE TITLE
Ubuntu sync indicator

### ISSUE THREAD

**Issue by Elkimo** [owncloud/client#1181]
Hey, I'm not sure if this is in the right place to ask this, but I was wondering if there are any plans to make the desktop sync indicator integrate with the Ubuntu sync indicator. Right now it is in a separate indicator. I couldn't find anything about this, but it would be really nice to have.

The design specification is located here: https://wiki.ubuntu.com/SyncMenu

It shows Dropbox and Ubuntu One as example synchronization software, but I don't see why ownCloud wouldn't fit in there as well. It would really clean up my indicator-area and help with consistency.

Its not anything critical of course, but I made an account just to ask about this since I really love everything you are doing with ownCloud and this is the one little thing that is missing in the desktop client for me (I'm really glad there is a monochrome icon option though, so that kind of makes up for it :) ).

**Comment by jancborchardt** [comment]
@Elkimo @danimo @dragotin any statement / update on this by the way? Do we integrate already, or are there plans to do it?

**Comment by bittner** [comment]
I've asked this via IRC on [#ubuntu-desktop@freenode](http://irclogs.ubuntu.com/2015/11/27/%23ubuntu-desktop.html#t12:51). It looks like Canonical stopped development. This may be related to their decision of shutting down Ubuntu One cloud storage in July last year.

**Comment by jancborchardt** [comment]
@bittner great, thanks for inquiring!

In that case it makes even less sense to invest there. A solution for only a single system is oftentimes not worth the investment since we need to focus our limited resources on improving the core product.

**Comment by bittner** [comment]
That's sad. Still, I'd love to see a nicely integrated ownCloud in both my Ubuntu desktop PC and my Ubuntu phone (which will ultimately be one and the same platform). If there is some synchronization code at hand somewhere and it's just about integrating the stuff with the Ubuntu desktop (i.e. app indicators) I'd be ready to find out how far Canonical has come, and what's still missing for a working solution.

As long as this can be coded in Python I'd be ready to contribute myself. I need a complete Google Apps replacement in the long run, and I believe this could be ownCloud on a RAID in my living room.

**Comment by dragotin** [comment]
@bittner I'd assume that Ubuntu stopped development of the sync menu  as a whole, no?

If not, don't be afraid about the technology we use, we're here to help if you want to help - would be very appreciated. Challenge yourself :smiley_cat:
