### ISSUE TITLE
[QA] GUI test failing with oC10 server

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11813]
## Describe the QA issue

CI build: https://drone.owncloud.com/owncloud/client/19070/2/16, https://drone.owncloud.com/owncloud/client/19068/2/16
Report: https://cache.owncloud.com/public/owncloud/client/19070/oc10/guiReportUpload/index.html
![Screenshot from 2024-08-21 13-11-55](https://github.com/user-attachments/assets/89569dc8-cae7-4071-ab92-89393f22cff2)

**Comment by TheOneRing** [comment]
What changed?

**Comment by saw-jan** [comment]
client crashed while removing the sync connection folder. Crash report on the way

**Comment by ishabaral** [comment]
crash report : [https://github.com/owncloud/client/issues/11814](url)   @HanaGemela

**Comment by saw-jan** [comment]
Fix has been merged and test is unskipped: https://github.com/owncloud/client/pull/11875
Tested: https://github.com/owncloud/client/issues/11814#issuecomment-2367963171
