### ISSUE TITLE
[QA][gui-tests] fix failing tests due to the changes in client UI

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#11847]
### Describe the QA issue

PR https://github.com/owncloud/client/pull/11810 has some changes that break the GUI test.
CI build: https://drone.owncloud.com/owncloud/client/19197/5/12
Test report: https://cache.owncloud.com/public/owncloud/client/19197/ocis/guiReportUpload/index.html

### Screenshots

![Screenshot from 2024-08-30 14-56-02](https://github.com/user-attachments/assets/84629848-d9e4-402b-9fd7-5299eeafeec8)

**Comment by erikjv** [comment]
Sorry, I was not aware of the fact that the widget names were used in the GUI tests 😬

**Comment by saw-jan** [comment]
> Sorry, I was not aware of the fact that the widget names were used in the GUI tests 😬

No worries, just ping us if the CI is red with the PRs. :smiley:
