### ISSUE TITLE
Missing Actual releases (LTS) to download for Linux distributions

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#11845]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When looking on
https://download.owncloud.com/desktop/ownCloud/stable/5.3.1.14018/linux/
and
https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/

we are lacking latest LTS releases eg. for Ubuntu:
![image](https://github.com/user-attachments/assets/7f759453-06a9-4d1a-9b6b-ba568d0b5394)

![image](https://github.com/user-attachments/assets/35464a78-6326-4cc5-8901-7d618b9e26a2)

This should be fixed asap

@TheOneRing 

### Expected behavior

Releases are provided, Ubuntu LTS 24.04 is available since April 2024

### Steps to reproduce the issue

Try to follow docs installing natively for U24.04

### Client version number

5.3.1

### Desktop environment (Linux only)

U24.04 Mate

**Comment by TheOneRing** [comment]
Not planned

**Comment by bredereck** [comment]
Why is it not planned?

**Comment by ptrebert** [comment]
I would also like to know why a support for 24.04 is not planned ...

**Comment by DeepDiver1975** [comment]
the desktop client for linux will be distributed via AppImage only. It has been quite a hassle to provide package repos for all various distributions out there. :shrug:

**Comment by ptrebert** [comment]
ah, thank you for making this simple explanation explicit.
In case somebody else stumbles upon this, I am now successfully running the ownCloud AppImage Client on an Ubuntu 24.04
