### ISSUE TITLE
CPack packaging tool error

### ISSUE THREAD

**Issue by nedimhx** [owncloud/client#1184]
I have problem with ...

Run CPack packaging tool...
CPack: Create package using NSIS
CPack: Install projects
CPack: - Run preinstall target for: mirall
CPack: - Install project: mirall
CPack: Create package
CPack Error: Problem running NSIS command: "/usr/bin/makensis" "/owncloud/mirall-build/_CPack_Packages/unused/NSIS/project.nsi"
Please check /owncloud/mirall-build/_CPack_Packages/unused/NSIS/NSISOutput.log for errors
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: ownCloud
make: **\* [package] Error 1

After I check log I found this

Error in script "/owncloud/mirall-build/_CPack_Packages/unused/NSIS/project.nsi" on line 300 -- aborting creation process

On line 300 I have find this 

File "${SQLITE_DLL_PATH}\qsqlite4.dll"

So please how to install qsqlite4.dll

**Comment by NguyenVanVuong** [comment]
it work?
