### ISSUE TITLE
Crash on start

### ISSUE THREAD

**Issue by ventrue3000** [owncloud/client#11864]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Owncloud Client terminates within seconds after starting. No windows open, no taskbar icon appears, no errors appear. Can't get it to create any logfiles. "& 'C:\Program Files\ownCloud\owncloud.exe' --logfile - --logflush | Write-Host" also does not give any output. Have quickly glanced over the Windows error reports, can't find anything related to Owncloud there. Owncloud does also not create a directory in %appdata%, nor is it among the autostart apps, not sure if this is normal at this point, with the program never having run properly.

What does work are the --version and --help commands.

No idea what else I could try. A way to get an exceptionally verbose log output might help, to see where it terminates.

Changes I've made recently, compared to when I last used Owncloud:
1. Hardware upgrade, everything's new. Wouldn't expect a high-end machine or lots of RAM to cause issues, though, especially since the only hardware requirement seems to be "64 bit". Definitely got that covered.
2. Fresh Windows install, along with an upgrade from 10 Pro to 11 Pro (23H2, build 22631.4112).
3. Disabled the  desktop shortcut during Owncloud's installation.

I did initially copy a bunch of folders back into my %appdata% to keep settings, including Owncloud's. Don't think this should be causing issues, but I have since removed every Owncloud folder I could find (both in programs and appdata) and reinstalled multiple versions with plenty of restarts in between. Not sure if there are any other remnants from the first installation (registry maybe?) that might be causing issues.

### Expected behavior

Would expect it to not terminate.

### Client version number

Tried these Owncloud versions:
5.0.0.12278.x64
5.3.1.14018.x64
6.0.0.14368-daily20240809.x64

### Installation path (Windows only)

C:\Program Files\ownCloud

**Comment by TheOneRing** [comment]
If this still happens, could you try to run it with https://github.com/TheOneRing/vsd/actions/runs/11055000795
```
vsd.exe 'C:\Program Files\ownCloud\owncloud.exe'
```
If that ends with something like:
`owncloud.exe (49068) With exit Code: 0xc0000135 After: 0:0:2:473`

```
vsd.exe 'C:\Program Files\ownCloud\owncloud.exe' --vsd-debug-dll
```

**Comment by ventrue3000** [comment]
Running it with vsd, the Owncloud window opened and everything worked as expected. The output is below, in case this is interesting to anyone. At the end, I closed it myself to try running Owncloud on its own, which also worked.

Not sure if running it with vsd somehow magically "repaired" it, but other than maybe a few Windows updates that happened in between, I'm not aware of making any changes that might have solved this issue. I hadn't touched Owncloud since I wrote the report and instead resorted to using WebDAV directly in Windows to get access to the server I need.

PS C:\Program Files\ownCloud> ./vsd.exe 'C:\Program Files\ownCloud\owncloud.exe'
C:\Program Files\ownCloud\owncloud.exe
Process Created: C:\Program Files\ownCloud\owncloud.exe ["C:\Program Files\ownCloud\owncloud.exe"                                          ] (184612)
owncloud(184612): gui.main: Using "de_Latn_DE" translation "de_DE"
owncloud(184612): gui.main: Could not load qtkeychain translations
owncloud(184612): 24-09-26 21:33:52:435 [ debug default ]       [ OCC::Logger::setLogRules ]:   ""
owncloud(184612): 24-09-26 21:33:52:437 [ info gui.main ]:      ################## "ownCloud" locale: "de_DE" version: "ownCloud 6.0.0.14368-daily20240809 6babf3 Qt Bibliotheken 6.7.1, OpenSSL 3.2.1 30 Jan 2024 Verwendete Erweiterung für virtuelle Dateien: wincfapi OS: windows-10.0.22631 (build arch: x86_64, CPU arch: x86_64) QPA: windows"
owncloud(184612): 24-09-26 21:33:52:446 [ info gui.main ]:      Arguments: QList("C:\\Program Files\\ownCloud\\owncloud.exe")
owncloud(184612): 24-09-26 21:33:52:898 [ debug default ]       [ unknown ]:    m_crashReporterChar:  C:/Program Files/ownCloud/owncloud_crash_reporter.exe
owncloud(184612): m_crashReporterWChar: C:/Program Files/ownCloud/owncloud_crash_reporter.exe
owncloud(184612): 24-09-26 21:33:52:911 [ info gui.account.manager ]:   "Legacy settings migration: " restoreFromLegacySettings, checking settings group "ownCloud"
owncloud(184612): 24-09-26 21:33:52:915 [ info gui.account.manager ]:   "Legacy settings migration: " checking old config  "C:/Users/marku/AppData/Roaming/ownCloud/owncloud.cfg"
owncloud(184612): 24-09-26 21:33:52:921 [ info gui.folder.manager ]:    Setup folders from settings file
owncloud(184612): 24-09-26 21:33:52:923 [ info gui.folder.manager ]:    void __cdecl OCC::FolderMan::setSyncEnabled(bool) true
owncloud(184612): 24-09-26 21:33:52:927 [ info gui.application ]:       Plugin search paths: QList("C:/Program Files/ownCloud")
owncloud(184612): 24-09-26 21:33:52:931 [ info gui.application ]:       VFS windows plugin is available
owncloud(184612): 24-09-26 21:33:52:958 [ info gui.application ]:       VFS suffix plugin is available
owncloud(184612): 24-09-26 21:33:52:960 [ debug default ]       [ OCC::Logger::setLogRules ]:   ""
owncloud(184612): 24-09-26 21:33:57:585 [ warning qt.qml.typeregistration ]:    Invalid QML element name "UrlButtonData"; value type names should begin with a lowercase letter
owncloud(184612): 24-09-26 21:34:04:813 [ info sync.credentials.manager ]:      get "ownCloud_credentials:Proxy/Password"
owncloud(184612): 24-09-26 21:34:04:817 [ debug sync.credentials.manager ]      [ OCC::CredentialJob::start ]:  We don't know "Proxy/Password" skipping retrieval from keychain
owncloud(184612): 24-09-26 21:34:04:966 [ info gui.application ]:       Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
owncloud(184612): 24-09-26 21:34:04:991 [ info gui.socketapi ]: server started, listening at  "\\\\.\\pipe\\ownCloud-marku"
owncloud(184612): 24-09-26 21:34:04:996 [ info sync.clientproxy ]:      Set proxy configuration to use system configuration
owncloud(184612): 24-09-26 21:34:05:011 [ debug gui.setupwizard.controller ]    [ OCC::Wizard::SetupWizardController::changeStateTo ]:  Current wizard state: OCC::Wizard::SetupWizardState::ServerUrlState
owncloud(184612): 24-09-26 21:34:05:017 [ warning default ]:    QLayout::removeWidget: Cannot remove a null widget.
owncloud(184612): 24-09-26 21:34:05:272 [ info gui.folder.manager ]:    void __cdecl OCC::FolderMan::setSyncEnabled(bool) false
owncloud(184612): 24-09-26 21:34:07:980 [ info gui.updater ]:   Checking for available update
owncloud(184612): 24-09-26 21:34:09:280 [ info gui.updater ]:   Version info arrived: Your version: QVersionNumber(6.0.0.14368) Skipped version: QVersionNumber() Available version: QVersionNumber() "" Available version string: "" Web url: "" Download url: ""
owncloud(184612): 24-09-26 21:34:09:284 [ info gui.updater ]:   No version information available at the moment
owncloud(184612): 24-09-26 21:34:27:199 [ warning default ]:    qrc:/qt/qml/org/ownCloud/gui/qml/AccountBar.qml:119: TypeError: Cannot read property 'currentPage' of null
owncloud(184612): 24-09-26 21:34:27:205 [ warning default ]:    qrc:/qt/qml/org/ownCloud/gui/qml/AccountBar.qml:105: TypeError: Cannot read property 'currentPage' of null
owncloud(184612): 24-09-26 21:34:27:305 [ info gui.account.manager ]:   Saved all account settings
Process Stopped: C:\Program Files\ownCloud\owncloud.exe (184612) With exit Code: 0 After: 0:0:35:726

**Comment by ventrue3000** [comment]
Running Owncloud with vsd worked, the output is below, in case this is interesting to anyone. At the end, I closed it myself to run it normally, which also worked.

Not sure if running it like this somehow magically repaired it, but other than maybe a few Windows updates that might have happened in between, I'm not aware of making any changes to resolve this issue. In fact, I hadn't touched Owncloud since writing this and instead resorted to using WebDAV directly in Windows to get access to the server I need. 

PS C:\Program Files\ownCloud> ./vsd.exe 'C:\Program Files\ownCloud\owncloud.exe'
C:\Program Files\ownCloud\owncloud.exe
Process Created: C:\Program Files\ownCloud\owncloud.exe ["C:\Program Files\ownCloud\owncloud.exe"                                          ] (184612)
owncloud(184612): gui.main: Using "de_Latn_DE" translation "de_DE"
owncloud(184612): gui.main: Could not load qtkeychain translations
owncloud(184612): 24-09-26 21:33:52:435 [ debug default ]       [ OCC::Logger::setLogRules ]:   ""
owncloud(184612): 24-09-26 21:33:52:437 [ info gui.main ]:      ################## "ownCloud" locale: "de_DE" version: "ownCloud 6.0.0.14368-daily20240809 6babf3 Qt Bibliotheken 6.7.1, OpenSSL 3.2.1 30 Jan 2024 Verwendete Erweiterung für virtuelle Dateien: wincfapi OS: windows-10.0.22631 (build arch: x86_64, CPU arch: x86_64) QPA: windows"
owncloud(184612): 24-09-26 21:33:52:446 [ info gui.main ]:      Arguments: QList("C:\\Program Files\\ownCloud\\owncloud.exe")
owncloud(184612): 24-09-26 21:33:52:898 [ debug default ]       [ unknown ]:    m_crashReporterChar:  C:/Program Files/ownCloud/owncloud_crash_reporter.exe
owncloud(184612): m_crashReporterWChar: C:/Program Files/ownCloud/owncloud_crash_reporter.exe
owncloud(184612): 24-09-26 21:33:52:911 [ info gui.account.manager ]:   "Legacy settings migration: " restoreFromLegacySettings, checking settings group "ownCloud"
owncloud(184612): 24-09-26 21:33:52:915 [ info gui.account.manager ]:   "Legacy settings migration: " checking old config  "C:/Users/marku/AppData/Roaming/ownCloud/owncloud.cfg"
owncloud(184612): 24-09-26 21:33:52:921 [ info gui.folder.manager ]:    Setup folders from settings file
owncloud(184612): 24-09-26 21:33:52:923 [ info gui.folder.manager ]:    void __cdecl OCC::FolderMan::setSyncEnabled(bool) true
owncloud(184612): 24-09-26 21:33:52:927 [ info gui.application ]:       Plugin search paths: QList("C:/Program Files/ownCloud")
owncloud(184612): 24-09-26 21:33:52:931 [ info gui.application ]:       VFS windows plugin is available
owncloud(184612): 24-09-26 21:33:52:958 [ info gui.application ]:       VFS suffix plugin is available
owncloud(184612): 24-09-26 21:33:52:960 [ debug default ]       [ OCC::Logger::setLogRules ]:   ""
owncloud(184612): 24-09-26 21:33:57:585 [ warning qt.qml.typeregistration ]:    Invalid QML element name "UrlButtonData"; value type names should begin with a lowercase letter
owncloud(184612): 24-09-26 21:34:04:813 [ info sync.credentials.manager ]:      get "ownCloud_credentials:Proxy/Password"
owncloud(184612): 24-09-26 21:34:04:817 [ debug sync.credentials.manager ]      [ OCC::CredentialJob::start ]:  We don't know "Proxy/Password" skipping retrieval from keychain
owncloud(184612): 24-09-26 21:34:04:966 [ info gui.application ]:       Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
owncloud(184612): 24-09-26 21:34:04:991 [ info gui.socketapi ]: server started, listening at  "\\\\.\\pipe\\ownCloud-marku"
owncloud(184612): 24-09-26 21:34:04:996 [ info sync.clientproxy ]:      Set proxy configuration to use system configuration
owncloud(184612): 24-09-26 21:34:05:011 [ debug gui.setupwizard.controller ]    [ OCC::Wizard::SetupWizardController::changeStateTo ]:  Current wizard state: OCC::Wizard::SetupWizardState::ServerUrlState
owncloud(184612): 24-09-26 21:34:05:017 [ warning default ]:    QLayout::removeWidget: Cannot remove a null widget.
owncloud(184612): 24-09-26 21:34:05:272 [ info gui.folder.manager ]:    void __cdecl OCC::FolderMan::setSyncEnabled(bool) false
owncloud(184612): 24-09-26 21:34:07:980 [ info gui.updater ]:   Checking for available update
owncloud(184612): 24-09-26 21:34:09:280 [ info gui.updater ]:   Version info arrived: Your version: QVersionNumber(6.0.0.14368) Skipped version: QVersionNumber() Available version: QVersionNumber() "" Available version string: "" Web url: "" Download url: ""
owncloud(184612): 24-09-26 21:34:09:284 [ info gui.updater ]:   No version information available at the moment
owncloud(184612): 24-09-26 21:34:27:199 [ warning default ]:    qrc:/qt/qml/org/ownCloud/gui/qml/AccountBar.qml:119: TypeError: Cannot read property 'currentPage' of null
owncloud(184612): 24-09-26 21:34:27:205 [ warning default ]:    qrc:/qt/qml/org/ownCloud/gui/qml/AccountBar.qml:105: TypeError: Cannot read property 'currentPage' of null
owncloud(184612): 24-09-26 21:34:27:305 [ info gui.account.manager ]:   Saved all account settings
Process Stopped: C:\Program Files\ownCloud\owncloud.exe (184612) With exit Code: 0 After: 0:0:35:726
