### ISSUE TITLE
After dismissing a "new style modal dialog", the toolbar buttons have the wrong text color

### ISSUE THREAD

**Issue by erikjv** [owncloud/client#11874]
- from the "..." menu, select "Choose what to sync"
- press the cancel button

<img width="789" alt="Screenshot 2024-09-12 at 17 03 49" src="https://github.com/user-attachments/assets/dc5cad53-2e40-4596-847d-608c76446f07">

**Comment by ishabaral** [comment]
Tested with: `ownCloud 6.0.0.14906-daily20241029 [b056cf]`

![Screenshot from 2024-10-29 17-12-36](https://github.com/user-attachments/assets/7d3a11e5-e901-4f39-b0ed-9e00a8bbab3a)
