### ISSUE TITLE
[macOS] Dark mode UI bug

### ISSUE THREAD

**Issue by hed320** [owncloud/client#11887]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

I found another similar issue https://github.com/owncloud/client/issues/7043 however I wanted to make a new one as this issue is about ownCloud versions that are alot older v2.x.x with comments in the issue from between 2019 and 2023. While my bug report is about v5.3.1.

Then for the issue itself. When I try to add a folder that was previously synced the warning message does not display properly if the system is using dark mode. The warning message does display properly when using the normal/light mode.

### Expected behavior

That the warning message is properly displayed/can be read.

### Steps to reproduce the issue

1. Have the systemwide dark mode enabled.
2. Use the "Add folder" button on the tab where the user is logged in, this issue does not seem to happen when using the setup wizard.
3. Try to add a folder that still has the hidden sync-journal.db files from a previous synchronisation.
4. The warning should now be shown.

### Screenshots

![sync client v5 3 1 UI bug](https://github.com/user-attachments/assets/24ef2ade-ccad-4130-9de8-36afde6a61e7)

### Client version number

v5.3.1

**Comment by TheOneRing** [comment]
Fixed in master
