### ISSUE TITLE
Immich Processing Library Item multiple times

### ISSUE THREAD

**Issue by psla** [owncloud/client#11894]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

I refreshed my library in immich after fixing issue with glob patterns. Unfortunately, the thumbnails do not seem to get processed, or get processed extremely slowly (after a week I am still 300k short of all files, and I have been 300k short 5 days ago too). 

While some progress is being made, Immich attempted to parse a folder containing 11k files approx 130k times. Here is a quick analysis of a single file, `/mnt/media/Fotografie/2021/2021-09_Italy_Wlochy/D750/DSC_0165.JPG`

There are 32 entries for this file in the docker log:

```
grep 2021-09_Italy_Wlochy /mnt/newhome/unprivileged-docker/.local/share/docker/containers/c374ef9a2f3b9cf3548b2877d10223659a85497898e67db7b6ec904df367e85a/c374ef9a2f3b9cf3548b2877d10223659a85497898e67db7b6ec904df367e85a-json.log  > ~/logs.gz

unprivileged-docker@usa:~$ grep 2021-09_Italy_Wlochy/D750/DSC_0165.JPG ~/logs  | wc -l
32
```

It looks like this file was queued for metadata extraction **5 times**

```

{"log":"\u001b[95m[Nest] 7  - \u001b[39m09/15/2024, 11:15:31 PM \u001b[95m  DEBUG\u001b[39m \u001b[33m[Microservices:LibraryService]\u001b[39m \u001b[95mQueueing metadata extraction for: /mnt/media/Fotografie/2021/2021-09_Italy_Wlochy/D750/DSC_0165.JPG\u001b[39m\n","stream":"stdout","time":"2024-09-15T23:15:31.652787541Z"}
{"log":"\u001b[95m[Nest] 7  - \u001b[39m09/16/2024, 12:31:23 AM \u001b[95m  DEBUG\u001b[39m \u001b[33m[Microservices:LibraryService]\u001b[39m \u001b[95mQueueing metadata extraction for: /mnt/media/Fotografie/2021/2021-09_Italy_Wlochy/D750/DSC_0165.JPG\u001b[39m\n","stream":"stdout","time":"2024-09-16T00:31:23.466406573Z"}
{"log":"\u001b[95m[Nest] 7  - \u001b[39m09/18/2024, 12:33:03 AM \u001b[95m  DEBUG\u001b[39m \u001b[33m[Microservices:LibraryService]\u001b[39m \u001b[95mQueueing metadata extraction for: /mnt/media/Fotografie/2021/2021-09_Italy_Wlochy/D750/DSC_0165.JPG\u001b[39m\n","stream":"stdout","time":"2024-09-18T00:33:03.140897797Z"}
{"log":"\u001b[95m[Nest] 7  - \u001b[39m09/20/2024, 12:24:32 AM \u001b[95m  DEBUG\u001b[39m \u001b[33m[Microservices:LibraryService]\u001b[39m \u001b[95mQueueing metadata extraction for: /mnt/media/Fotografie/2021/2021-09_Italy_Wlochy/D750/DSC_0165.JPG\u001b[39m\n","stream":"stdout","time":"2024-09-20T00:24:32.966181535Z"}
{"log":"\u001b[95m[Nest] 7  - \u001b[39m09/22/2024, 12:25:23 AM \u001b[95m  DEBUG\u001b[39m \u001b[33m[Microservices:LibraryService]\u001b[39m \u001b[95mQueueing metadata extraction for: /mnt/media/Fotografie/2021/2021-09_Italy_Wlochy/D750/DSC_0165.JPG\u001b[39m\n","stream":"stdout","time":"2024-09-22T00:25:23.091309452Z"}
```

And the preview was also generated **4 times**

```
{"log":"\u001b[32m[Nest] 7  - \u001b[39m09/17/2024, 8:21:07 AM \u001b[32m    LOG\u001b[39m \u001b[33m[Microservices:MediaService]\u001b[39m \u001b[32mSuccessfully generated JPEG image preview for asset /mnt/media/Fotografie/2021/2021-09_Italy_Wlochy/D750/DSC_0165.JPG\u001b[39m\n","stream":"stdout","time":"2024-09-17T08:21:07.052349783Z"}
{"log":"\u001b[32m[Nest] 7  - \u001b[39m09/19/2024, 2:25:58 PM \u001b[32m    LOG\u001b[39m \u001b[33m[Microservices:MediaService]\u001b[39m \u001b[32mSuccessfully generated JPEG image preview for asset /mnt/media/Fotografie/2021/2021-09_Italy_Wlochy/D750/DSC_0165.JPG\u001b[39m\n","stream":"stdout","time":"2024-09-19T14:25:58.203703109Z"}
{"log":"\u001b[32m[Nest] 7  - \u001b[39m09/20/2024, 8:03:28 PM \u001b[32m    LOG\u001b[39m \u001b[33m[Microservices:MediaService]\u001b[39m \u001b[32mSuccessfully generated JPEG image preview for asset /mnt/media/Fotografie/2021/2021-09_Italy_Wlochy/D750/DSC_0165.JPG\u001b[39m\n","stream":"stdout","time":"2024-09-20T20:03:28.94949771Z"}
{"log":"\u001b[32m[Nest] 7  - \u001b[39m09/22/2024, 5:22:55 PM \u001b[32m    LOG\u001b[39m \u001b[33m[Microservices:MediaService]\u001b[39m \u001b[32mSuccessfully generated JPEG image preview for asset /mnt/media/Fotografie/2021/2021-09_Italy_Wlochy/D750/DSC_0165.JPG\u001b[39m\n","stream":"stdout","time":"2024-09-22T17:22:55.154199538Z"}
```

The log file from docker has now over 4GB with 13M lines.

It seems like immich is processing some of the same files multiple times and not getting through the backlog of the files to process.

[logs.gz](https://github.com/user-attachments/files/17090636/logs.gz)

Have you seen this before? Is there anything else I can do to help diagnose the issue?

It does seem like Immich is making **some** progress, as the number of "outstanding" files reduced in the past 3 days, but it feels like it's making a progress slowly, processing each file multiple times.

### Expected behavior

Process each file once

### Steps to reproduce the issue

not sure.

1) I changed the "excluded path" patterns in my external library (one that was processed before)
2) And then I refreshed (scan library) operation

I've waited a week and it seems like immich got stuck, not making much progress, and recent files do not have thumbnails generated for them (some do, some don't)

### Screenshots

![image](https://github.com/user-attachments/assets/3601f425-6c08-4496-8b70-3e8d12905ea3)

Screenshot today:
![image](https://github.com/user-attachments/assets/8959c1d9-8eda-457d-8cae-2b0b90af35c8)

Screenshot 3 days ago
![Screenshot 2024-09-20 175103](https://github.com/user-attachments/assets/e9093111-b3a8-4c79-98e4-f61a7ccac2dc)

Edit! Screenshot now (a few hours later). The backlog is back to 320k items. and FWIW no Library tasks or metadata tasks are being performed (i.e. I am not adding tens of thousands of new files)
![image](https://github.com/user-attachments/assets/d171dd43-91e9-4a20-8af5-0bfa787ac332)

![image](https://github.com/user-attachments/assets/0f897463-5ca5-4cc0-aaf2-e2ce533fb4f0)

### Logs

[logs.gz](https://github.com/user-attachments/files/17090636/logs.gz)

Happy to provide more, the file is massive though (4GB, might compress to a few hundred megs)

### Client version number

n/a (web client)

### Desktop environment (Linux only)

Linux  6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux

### Server information

1.115.0, docker

**Comment by psla** [comment]
Wondering if periodic library scanner would re-queue files that are already in the queue.... Leading to processing them multiple times.

![image](https://github.com/user-attachments/assets/d67a938a-38bd-48d8-9c2e-c9364062c4f2)

**Comment by DeepDiver1975** [comment]
Looks like you opened this issue in the wrong repository.
