### ISSUE TITLE
Proposal: better singed out icon

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/client#11905]
Proposal to have a better to understand singed out icon

# Status Quo
![image](https://github.com/user-attachments/assets/fdc2f41a-2be4-42c9-88a4-2fa8a2ed0410)

# 1. Proposal
![Picture 1-white](https://github.com/user-attachments/assets/42e0dbd6-59fb-44ac-8442-74f16feea9e4)

# 2. Proposal

![Picture 2 white](https://github.com/user-attachments/assets/835b287c-8eed-4b91-9c10-b5e8d6337637)

# 3. Proposal
![Picture 3 white](https://github.com/user-attachments/assets/6906317a-fdea-475c-9d4d-263e41a5b8df)

@TheOneRing @erikjv @dragotin are the proposals improvements and if yes, which would you favour?

**Comment by TheOneRing** [comment]
1. I think that small it looks like "exploding death stars prohibited"
2. maybe
3. hmm wrong message?

**Comment by tbsbdr** [comment]
ok, lets go with 2
https://fontawesome.com/icons/plug-circle-xmark?f=classic&s=solid
