### ISSUE TITLE
Alignment for basic auth

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11913]
![image](https://github.com/user-attachments/assets/b60371bb-8d1e-4f98-9e9e-e592e185e754)

**Comment by saw-jan** [comment]
Tested with: `ownCloud 6.0.0.14906-daily20241029 [b056cf]`

![Screenshot from 2024-10-29 14-02-57](https://github.com/user-attachments/assets/d8f2f5f3-64ea-40ea-bbb6-20dc4fab7f88)
