### ISSUE TITLE
button alignment oauth screen

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/client#11915]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

buttons are miss aligned

### Expected behavior

shall be alligned

### Screenshots

![image](https://github.com/user-attachments/assets/b8d07c28-e8eb-44f0-b441-56ef2fdced8d)

### Client version number

master

**Comment by erikjv** [comment]
I cannot reproduce this on my macOS build. This is probably on Linux, so I'll try that next.

**Comment by erikjv** [comment]
I tried to reproduce this on Neon Linux (Wayland), and for me it looks fine:

<img width="830" alt="Screenshot 2024-10-02 at 16 27 53" src="https://github.com/user-attachments/assets/699a2685-62db-48f2-9c0e-982ed498f838">

**Comment by erikjv** [comment]
What Qt are you using? Or, is this a craft build, or a native Linux build?

**Comment by DeepDiver1975** [comment]
> I tried to reproduce this on Neon Linux (Wayland), and for me it looks fine:

git the 'open browser' button and see the text change ...

**Comment by saw-jan** [comment]
Tested with: `ownCloud 6.0.0.14906-daily20241029 [b056cf]`
1. Open new account wizard
2. Click `open web browser`

![Screenshot from 2024-10-29 13-57-51](https://github.com/user-attachments/assets/4583dedc-98f0-4fb0-bc5f-f2d98b899469)
