### ISSUE TITLE
OCIS sync: wrong endpoint for re-login

### ISSUE THREAD

**Issue by thommierother** [owncloud/client#11926]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The Desktop Client 5.3.1 shows a strange error upon re-connect of the client after a restart of the operating system (tested with both SUSE Tumbleweed and Windows 11):

- create an account for a classic OC server, here cloud.netzwissen.de with OC 10.x
- create a second account with a different username for an OCIS server 5.x, here: ocis.netzwissen.de

The initial re-direction and auth to the OIDC server (login.netzwissen.de, keycloak 24.x IDP) and the creation of both accounts is successful

- Close the operating system and re-open it again
- re-login of the account with the classic OC 10.x is successful
- re-login of the account with the OCIS servers fails: the OIDC re-direction URL uses an invalid endpoint at https://ocis.netzwissen.de/index.php/apps/oauth2/authorize?response_type=code&client_id=xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69&redirect_uri=http://localhost:49794&code_challenge=1Ppns4yJJs1ucKt3zdf4cdg4yafIcp0Of6QVa9zV2dU&code_challenge_method=S256&scope=openid%20offline_access%20email%20profile&prompt=select_account%20consent&state=dyGjucCHalzgwF1OKGdGecFsugBB6BsMcH7BLpHjYzo%3D&login_hint=thommie.rother%40gmx.de&user=thommie.rother%40gmx.de

### Expected behavior

successful re-login of both accounts, redirection to correct OIDC endpoint

### Client version number

- ownCloud desktop client 5.3.1.14018

### Desktop environment (Linux only)

openSUSE Tumbleweed (same error on WIndows 11)

### Server information

- ownCloud classic server 10.13.4
- ownCloud OCIS server 5.0.0

**Comment by TheOneRing** [comment]
Your ocis server needs to provide https://ocis.netzwissen.de/.well-known/openid-configuration to tell the client the location of the idp

**Comment by thommierother** [comment]
arghh, "layer 8 issue": I had an old redirect rule in the haproxy load balancer

`http-request set-path /index.php/apps/openidconnect/config if oidc-config`

This was used for OC 10 OIDC in the past, but it interferes with the OIDC implementation for OCIS. Removing this rule from the LB fixed the problem ;-)
