### ISSUE TITLE
mTLS Client Certificate support

### ISSUE THREAD

**Issue by lemiceo** [owncloud/client#11933]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Hello,

Thanks to issue #69 then MR #5289 in 2017, the desktop client should ask for a client certificate if the webserver requires it for early authentification also known as mTLS (or mutual TLS). It seems to no longer be the case, since the desktop client has changed throughout the years, especially with a migration to Qt6. For that reason I'm opening a new issue instead of reviving one from 7 years ago that perharps doesn't correlate to current codebase anymore.

### Expected behavior

While error 400 is returned by the webserver not being presented with a valid client certificate, which is reported as debug line "error:0A000412:SSL routines::sslv3 alert bad certificate" by the client, the user should then be provided with a pop-up window suggesting to add a .p12 certificate.

Qt6 documentation still supports PKCS#12 : https://doc.qt.io/qt-6/qsslcertificate.html

### Steps to reproduce the issue

1. Open "New Account" setup wizard
2. Submit a server adress or domain in front of a webserver requiring a client certificate (also known as mTLS)

### Screenshots

![Capture d’écran du 2024-10-15 16-57-15](https://github.com/user-attachments/assets/59b8e6a9-0c3e-4938-84cc-4be8f4283f0b)

Please note the URL has been anonymized for this issue.

### Logs

24-10-15 17:02:20:078 [ debug gui.setupwizard.controller ]	[ OCC::Wizard::SetupWizardController::SetupWizardController(OCC::SettingsDialog*)::<lambda ]:	next button clicked, current state OCC::Wizard::ServerUrlSetupWizardState(0xd500470)
24-10-15 17:02:20:177 [ critical gui.wizard.resolveurl ]:	"Failed to resolve URL https://blabla.bleubl.eu, error: Erreur lors de la lecture : error:0A000412:SSL routines::sslv3 alert bad certificate"
24-10-15 17:02:20:179 [ debug gui.setupwizard.controller ]	[ OCC::Wizard::SetupWizardController::changeStateTo ]:	Current wizard state: OCC::Wizard::SetupWizardState::ServerUrlState
24-10-15 17:02:20:181 [ warning gui.wizard.resolveurl ]:	"Could not detect compatible server at https://blabla.bleubl.eu"
24-10-15 17:02:31:874 [ debug gui.setupwizard.controller ]	[ OCC::Wizard::SetupWizardController::SetupWizardController(OCC::SettingsDialog*)::<lambda ]:	wizard window closed

### Client version number

ownCloud 5.3.1.14018 [f15fd5](https://github.com/owncloud/client/commit/f15fd5635eb4b24e7e5a29a36a882628fb87a1e9)
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: suffix
OS: fedora-6.11.3-200.fc40.x86_64
QPA: xcb

### Desktop environment (Linux only)

Fedora 40 – Gnome 46

### Client package version and origin (Linux only)

ownCloud version 5.3.1.14018 — Fedora Official Repos

### Server information

- OCIS 6.5.0
- RHEL 9.4
- Caddy

### Additional context

I'm able to set up and get OCIS runnig just fine without the client certificate required by the caddy webserver. Though the webserver is not at fault: other apps succeed with asking for a client certificate when required, and I've tested it with Nextcloud desktop client for example. However the lack of this security feature prevents me from switching everything to OCIS, which I'd love to do considering how much faster it has been during my testing.

**Comment by lemiceo** [comment]
Hello ! Looking at the commit history, I realized @TheOneRing removed support for client side certificate with commit #bb2d7b9 in 2021. That's unfortunate, it's a very efficient security feature to prevent unauthorized access without having to resort using a VPN.

**Comment by DeepDiver1975** [comment]
based on the description in the changelog item in the linked change we never really supported this. for the time being I see not changing this as this is a very rare used feature. Once this is back on the roadmap we will reopen this. THX a lot

**Comment by lemiceo** [comment]
> this is a very rare used feature
I'd argue it is not a rare feature, but quite the opposite : it's a widely deployed security practice used by the [biggest](https://www.microsoft.com/en-us/security/business/zero-trust) [companies](https://cloud.google.com/learn/what-is-zero-trust) out there adopting the industry standard [Zero Trust security model](https://en.wikipedia.org/wiki/Zero_trust_security_model). Since OCIS seems to be targeting the high-scalability cloud business I'd argue it should be on the roadmap rather sooner than later for B2B adoption of this project, though it's true there's no point for you guys to support this feature strictly for a few homelab users, even though these "few homelab users" [have highly requested this feature](https://github.com/nextcloud/android/issues/603) in another very similar project which then was implemented only recently.

> we never really supported this
Yes it was clear in the mentioned changelog item dating back to 2021. I just hoped the team would give it a second thought instead of closing the feature request right away. Thanks for clarifying that this level of security is not within the scope of this project for the time being.

**Comment by DeepDiver1975** [comment]
locking this discussion now - al has been said. Thank you
