### ISSUE TITLE
In case the graph endpoint is returning multiple personal spaces - we should really use the drive name

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/client#11952]
https://github.com/owncloud/client/blob/e51dce78e143681585b69f8d637839d5762e9f02/src/libsync/graphapi/space.cpp#L101

**Comment by TheOneRing** [comment]
Ocis has only one personal drive and doesn't provide a useful name.

**Comment by DeepDiver1975** [comment]
```cpp
if (_drive.getDriveType() == personalC && _drive.getDriveType().isNotUseful()) {
    return tr("Personal");
}

**Comment by DeepDiver1975** [comment]
How does the ocis response look like for personal folders?

**Comment by DeepDiver1975** [comment]
ios has the same issue - and I assume android will as well

Proposal: add capability to identify if multiple personal spaces are supported by the backend (like kiteworks) or not like ocis
In case the property is not set it is to be interpreted as `false`

```json
        "spaces": {
          "version": "0.0.1",
          "enabled": true,
          "has_multiple_personal_spaces": true
        }
