### ISSUE TITLE
Qt 6.8: Native tooltips for Navigation bar

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#11951]
Since Qt6.8 it supports native popups, however for now it appears that they are only active for menus by default.
However, it can be enabled by setting:
`ToolTip.toolTip.popupType: Popup.Native `

This would fix the issue where the toolbar prevents interaction with the element.
![image](https://github.com/user-attachments/assets/b61e48ec-724b-4f6e-8a4b-f642c644569a)

**Comment by erikjv** [comment]
Note for testing: this is only enabled for Qt 6.8 or later.
