### ISSUE TITLE
[OCIS/OAUTH] Windows client requesting login whenever computer awakens from deep sleep

### ISSUE THREAD

**Issue by sfadschm** [owncloud/client#11980]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

With the Windows client being connected to a live OCIS instance, the client request a new login via OAUTH / Browser whenever the computer awakes from deep sleep.
Here, "deep sleep" is my amateur description of what Windows11 does when you close the laptop lid and leave the computer in the sleep state for a longer time period.

### Expected behavior

Credentials should be stored and not need to re-authenticate.

### Steps to reproduce the issue

1. Have ownCloud running and connected to an account on an OCIS instance on a Win11 laptop.
2. Close the laptop lid to have the computer go to sleep.
3. Wait until "deep sleep" sets in. (That is, if you open the lid again, you will not directly be prompted with the Win11 login screen, but with a sped-up booting procedure.)
4. ownCloud client opens and states that the current account has been logged out.

### Logs

Log have been collected and I believe this is the crucial part right after the computer wakes up, leading to "OCC::ConnectionValidator::CredentialsNotReady":
https://gist.github.com/sfadschm/21d18d9306627f951f101d03625d6766

### Client version number

ownCloud 5.3.1.14018 [f15fd5](https://github.com/owncloud/client/commit/f15fd5635eb4b24e7e5a29a36a882628fb87a1e9)
Libraries Qt 6.4.3, OpenSSL 3.1.2 1 Aug 2023
Using virtual files plugin: wincfapi
OS: windows-10.0.22631
QPA: windows

### Installation path (Windows only)

C:\Program Files\ownCloud

### Server information

ownCloud 	Infinite Scale
Edition 	Community
Version 	5.0.6
Web client version 	8.0.4

on
Ubuntu 20.04.6 LTS

installed via
Docker container

**Comment by erikjv** [comment]
@sfadschm Can you include a bit more of the log file before that first line, so we can check what went on there? Also, what is the time of "sleep" and the "wake up" time?

**Comment by sfadschm** [comment]
@erikjv Extended the gist accordingly. It looks like 8:33 was the time that the computer went into deep sleep. Before that, there is a long period of "Host XXX not found" log entries, likely because WLAN was inactive during sleep.
After waking up the computer on 10:59, we see some "Host not found" errors again, likely because it takes some time for the computer to reconnect to the WLAN network.

Unfortunately, there does not seem to be any indication in the Windows setting that tell after which time the OS goes into "deep sleep". "Closing the lid" is simply set to "sleep", yet behaviour differs depending on whether it is opened/woken up 30 mins later (no OC issue, Win11 password prompt shows up immediately) or after a longer time of ~2 h (OC logs out).

**Comment by erikjv** [comment]
Next time it happens, can you include The last few (20?) lines before the `ConnectionValidator::StatusNotFound` messages?

**Comment by sfadschm** [comment]
Updated the GIST again to include anything between the last "#### Discovery End ####" and the first "#### Discovery Start ####". The first "ConnectionValidator::StatusNotFound" appears on line 69.

Here goes the link again:
https://gist.github.com/sfadschm/21d18d9306627f951f101d03625d6766

Will add another gist when it appears again.

**Comment by erikjv** [comment]
What happens in sequence is:
- when Windows wakes up, the network becomes available shortly _after_ the applications are woken up (DHCP?)
- also, when Windows goes back to sleep, the network disappears first before the applications are put to sleep (probably so they can handle any incomplete network requests)
- when the last login is long enough in the past, the authentication token needs refreshing
- when this succeeded, the client tries to do a request using the new token
- when the network disappears at this point, _and_ stays unavailable for 3 tries total, the user is logged out:

```
24-11-13 07:48:22:404 [ debug sync.credentials.oauth ]  [ OCC::AccountBasedOAuth::fetchWellKnown ]:     starting CheckServerJob before fetching "/.well-known/openid-configuration"
24-11-13 07:48:22:451 [ info sync.httplogger ]: "74a8fb13-7452-4ce4-b0d6-f20e3880b950: Response: GET 0 (Error: Network unreachable,46ms) https://ocis.cloud.de/status.php Header: { } Data: []"
24-11-13 07:48:22:451 [ warning sync.checkserverjob ]:  error: status.php replied 0
24-11-13 07:48:22:451 [ debug sync.credentials.oauth ]  [ OCC::AccountBasedOAuth::fetchWellKnown::::operator() ]:       CheckServerJob failed, error: "Invalid HTTP status code received for status.php: 0"
24-11-13 07:48:22:451 [ warning sync.credentials.http ]:        Too many failed refreshes 3 -> log out
```

(The previous 2 attempts are in the log file right in front of this snippet.)

The fix is not to retry those jobs when there is no network available, or to not invalidate the credentials when the network disappeared.

**Comment by sfadschm** [comment]
Thanks for the analysis ! The described sequence of events sounds like what Windows "modern standby" is intended to do, so seems legit.

Rechecking connection after a failed attempt seems like the more natural approach to me.

**Comment by sfadschm** [comment]
Btw. What is the lifetime of the authentication token? Because this error on some days occured 3-5 times. Such short lifetime appears a little over the top on a first glance.

**Comment by erikjv** [comment]
Note: this also has a new feature that you might be interested in: in the settings there is now an option "Move remotely deleted files to the local trash bin instead of deleting them".

**Comment by sfadschm** [comment]
Will test it for a few days and give feedback if the error occurs again. The implementation looks robust however.

The trash bin feature sounds great!

**Comment by sfadschm** [comment]
No occurence so far.

**Comment by DeepDiver1975** [comment]
@sfadschm hey - how did the client behave in the past 2 weeks? THX a lot

**Comment by sfadschm** [comment]
@DeepDiver1975 sorry I considered my last report as final, as this was 4 days of intensive use.

However, no issue since then so I guess this can be merged 👍
