### ISSUE TITLE
VFS hangs in Finder

### ISSUE THREAD

**Issue by hrdwdmrbl** [owncloud/client#12001]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

# The problem

I cannot navigate the "VFS" folder in Finder

# Context

There are 2 folders: 

1) The "regular" folder within my home `~` 
2) The "VFS" folder on the sidebar. 

# What does work

I _am_ able to navigate the "regular" folder and navigate around. Clicking on any .nextcloud file does cause Nextcloud app to download the file and then I can open it.

# What does not work

But the "VFS" folder does not open.  It forever presents a loading spinner. The Nextcloud app is open.

![Screenshot 2024-11-29 at 16 04 33](https://github.com/user-attachments/assets/627517ba-424f-4eb7-8a67-8f007accca76)

Clicking Sign-in opens a menu which never loads. The only escape is to restart Finder.

![Screenshot 2024-11-29 at 16 05 20](https://github.com/user-attachments/assets/aa8010b5-8f81-4bcb-947c-7b3d8c6efff6)

# Solutions that I have tried

Several times I have:

1. Tried to reset Finder by deleting its plist file.
2. Restarted
3. Removed the connection from Nextcloud and re-added it.
4. Re-installed Nextcloud
5. Enabled and disabled VFS

### Expected behavior

Be able to open the VFS folder and navigate around.

I don't want to have double-click .nextcloud files to have Nextcloud download the files. I want to just open the file and for it to seamlessly work like VFS for iCloud.

### Steps to reproduce the issue

1. Open the Nextcloud VFS folder from the Finder sidebar.

### Screenshots

VFS folder

![Screenshot 2024-11-29 at 16 04 33](https://github.com/user-attachments/assets/3d6053f4-52d9-410f-9c17-fd3ac1d7c54f)
![Screenshot 2024-11-29 at 16 05 20](https://github.com/user-attachments/assets/88f010b4-5b68-4cd3-a28e-2ddc453a8747)

"Regular" folder
![Screenshot 2024-11-29 at 16 08 19](https://github.com/user-attachments/assets/fb8d1253-2fc0-49b3-a4f7-dffeaafdc73c)

### Logs

The biggest error that I see is `2024-11-29 16:07:34:885 [ warning default qrc:/qml/src/gui/tray/MainWindow.qml:99 ]:	qrc:/qml/src/gui/tray/MainWindow.qml:99: ReferenceError: appsMenu is not defined`

### Client version number

Version 3.15.0daily. For more information please click [here](https://docs.nextcloud.com/desktop/3.15/).
This release was supplied by Nextcloud GmbH.
Built from Git revision [eb04ac](https://github.com/nextcloud/desktop/commit/eb04ac92122be40ce0fdc82557a26ccbd8684474) on Nov 25 2024, 15:09:54 using Qt 6.7.2, OpenSSL 3.3.2 3 Sep 2024

### Desktop environment (Linux only)

OSX 15.1 (24B83)

### Additional context

This used to work about a month ago. I kept re-installing and installing new versions, but finally I am here.

**Comment by DeepDiver1975** [comment]
![9c3d93](https://github.com/user-attachments/assets/0c00d001-dbd9-41b0-931a-2f7447c3afda)
