### ISSUE TITLE
propagation of mtime and ctime: unnecessary redownload if oc_filecache entry missing on the server?

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#1206]
Hello,

Server: 5.0.13 CE
Client: 1.4.2

I was doing a test to delete the content of oc_filecache table on the server (drop and recreate). The client started downloading all the files, also the ones which have not been touched for a long time. If I recall correctly this should not be happening if mtimes are the same?

So I did a separate test to understand what happens with mtime and ctime when I sync from a linux client to the linux server with a local disk storage behind. It looks to me that the mtime/ctime is truncated to the last second in propagation.

How does the sync client compare the mtimes? Do you compare the numeric values truncated to a second resolution? How do you take into account that on FAT the effective resolution is 2 seconds?

Here is the file touched on the client:

<pre>
stat ~/ownCloud/STAT.TEST 
  File: `/home/moscicki/ownCloud/STAT.TEST'
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: fd02h/64770d	Inode: 7604227     Links: 1
Access: (0644/-rw-r--r--)  Uid: (  500/moscicki)   Gid: (  500/moscicki)
Access: 2013-11-26 12:06:52.637736782 +0100
Modify: 2013-11-26 12:06:52.637736782 +0100
Change: 2013-11-26 12:06:52.637736782 +0100
</pre>

Here is the file propagated to the server:

<pre>
stat  files/clientsync/STAT.TEST 
  File: `files/clientsync/STAT.TEST'
  Size: 0         	Blocks: 0          IO Block: 4096   regular empty file
Device: 976h/2422d	Inode: 80740366    Links: 1
Access: (0644/-rw-r--r--)  Uid: (   48/  apache)   Gid: (   48/  apache)
Access: 2013-11-26 12:06:52.000000000 +0100
Modify: 2013-11-26 12:06:52.000000000 +0100
Change: 2013-11-26 12:07:07.444994580 +0100
</pre>

**Comment by ogoffart** [comment]
closing old bug. I don't think this is valid anymore since both the client and the server have changed a lot.
