### ISSUE TITLE
[1.5.0beta1] Client (Mac) reports 'Unable to initialize a sync journal'

### ISSUE THREAD

**Issue by kwillems** [owncloud/client#1228]
### Expected behaviour

The client should 'run' and not report an error 'Unable to initialize a sync journal'.
### Actual behaviour

On Mac the desktop client (1.5.0beta1) gives an error when syncing has finished. See the attached file.
![schermafbeelding-2013-11-30-om-23 13 49](https://f.cloud.github.com/assets/2992051/1649546/1591970c-5a0d-11e3-9b25-d815676a0271.png)
### Steps to reproduce
1. Install client 1.5.0beta1
2. Start the client and let it download the files of an excisting ownCloud account
3. Wait max 30 seconds
### Server configuration

Operating system: Ubuntu 12.04 64bit 3.2.0-54-virtual
Web server: Apache 2.2.22-1ubuntu
Database: postgresql 9.1.9-0ubuntu1
PHP version: 5.3.10-1ubuntu3.8
ownCloud version: 5.0.13
Storage backend: NFS3 share
### Client configuration

Client version: 1.5.0beta1
Operating system: OS X 10.9
OS language: Dutch
Installation path of client: default
#### First here is a sample part of the log during downloading of the files:

11-30 22:45:26:185 void Mirall::CSyncThread::transferCompleted(const Mirall::SyncFileItem&) "20131216 folder/20.1. document.pdf" 4 "" 
11-30 22:45:26:185 Database Drivers could not be loaded. 
11-30 22:45:26:185 Database Drivers could not be loaded. 
11-30 22:45:26:185 Transaction Start  "download file start" 
11-30 22:45:26:185 No database Transaction to commit 
11-30 22:45:26:185 ERROR commiting to the database:  "Driver not loaded Driver not loaded" 
11-30 22:45:26:203 FolderWatcherPrivate::callback by OS X 
11-30 22:45:26:209 FolderWatcherPrivate::callback by OS X 
11-30 22:45:26:341 Content encoding ist <empty> with status 200
11-30 22:45:26:352 Database Drivers could not be loaded. 
11-30 22:45:26:352 Failed to connect database. 
11-30 22:45:26:352 Database Drivers could not be loaded. 
11-30 22:45:26:352 Transaction Start  "download file start2" 
11-30 22:45:26:352 No database Transaction to commit 
11-30 22:45:26:352 ERROR commiting to the database:  "Driver not loaded Driver not loaded" 
#### Later, when the downloading has finished the following is stated in the logfile:

11-30 22:45:28:382     \* event notification  enabled 
11-30 22:45:56:383 \* Polling "ownCloud" for changes. (time since last sync: 30 s) 
11-30 22:45:56:389 Loading config:  "/Users/Koen/Library/Application Support/ownCloud/owncloud.cfg"  (URL is  "https://website.nl" ) 
11-30 22:45:56:390 !!! Mirall::RequestEtagJob created for  QUrl( "https://website.nl" )  querying "" 
11-30 22:45:56:758 \* Compare etag  with previous etag:  true 
11-30 22:45:56:772 Schedule folder  "ownCloud"  to sync! 
11-30 22:45:56:773 XX slotScheduleFolderSync: folderQueue size:  1 
11-30 22:45:56:773 Folder in overallStatus Message:  Mirall::Folder(0x10489a1c0)  with name  "ownCloud" 
11-30 22:45:56:774 Sync state changed for folder  "ownCloud" :  "SyncPrepare" 
11-30 22:45:56:774 SocketApi:  Sync state changed 
11-30 22:45:56:775 SocketApi:  Broadcasting to 0 listeners:  "UPDATE_VIEW" 
11-30 22:45:56:775 **\* Start syncing 
11-30 22:45:56:775 Loading config:  "/Users/Koen/Library/Application Support/ownCloud/owncloud.cfg"  (URL is  "https://website.nl" ) 
11-30 22:45:56:776   ==> returning exclude file path:  "/Applications/owncloud.app/Contents/Resources/sync-exclude.lst" 
11-30 22:45:56:776 ==== added system ignore list to csync: "/Applications/owncloud.app/Contents/Resources/sync-exclude.lst" 
11-30 22:45:56:777 csync_exclude_load: Adding entry: _.filepart
11-30 22:45:56:777 csync_exclude_load: Adding entry: *~
11-30 22:45:56:778 csync_exclude_load: Adding entry: *.part
11-30 22:45:56:778 csync_exclude_load: Adding entry: *.crdownload
11-30 22:45:56:779 csync_exclude_load: Adding entry: *.unison_
11-30 22:45:56:779 csync_exclude_load: Adding entry: _csync_timedif.ctmp_
11-30 22:45:56:779 csync_exclude_load: Adding entry: csync_journal.db
11-30 22:45:56:780 csync_exclude_load: Adding entry: csync_journal.db.ctmp
11-30 22:45:56:780 csync_exclude_load: Adding entry: ._.sw?
11-30 22:45:56:781 csync_exclude_load: Adding entry: ._._sw?
11-30 22:45:56:781 csync_exclude_load: Adding entry: ].csync-progressdatabase
11-30 22:45:56:781 csync_exclude_load: Adding entry: ].DS_Store
11-30 22:45:56:782 csync_exclude_load: Adding entry: ].ds_store
11-30 22:45:56:782 csync_exclude_load: Adding entry: ]Thumbs.db
11-30 22:45:56:783 csync_exclude_load: Adding entry: desktop.ini
11-30 22:45:56:783 csync_exclude_load: Adding entry: *.kate-swp
11-30 22:45:56:784 csync_exclude_load: Adding entry: *_conflict-_
11-30 22:45:56:784 csync_exclude_load: Adding entry: ]_.~_
11-30 22:45:56:784 csync_exclude_load: Adding entry: ].TemporaryItems
11-30 22:45:56:785 csync_exclude_load: Adding entry: ].Trashes
11-30 22:45:56:785 csync_exclude_load: Adding entry: ].DocumentRevisions-V100
11-30 22:45:56:786 csync_exclude_load: Adding entry: .fseventd
11-30 22:45:56:786 csync_exclude_load: Adding entry: .apdisk
11-30 22:45:56:787 csync_exclude_load: Adding entry: .htaccess
11-30 22:45:56:787 csync_exclude_load: Adding entry: ]Icon\r*
11-30 22:45:56:787 csync_exclude_load: Adding entry: ~$*
11-30 22:45:56:788 csync_exclude_load: Adding entry: .~lock.*
11-30 22:45:56:788 csync_exclude_load: Adding entry: ~_.tmp
11-30 22:45:56:789   ==> returning exclude file path:  "/Users/Koen/Library/Application Support/ownCloud/sync-exclude.lst" 
11-30 22:45:56:789 ==== added user defined ignore list to csync: "/Users/Koen/Library/Application Support/ownCloud/sync-exclude.lst" 
11-30 22:45:56:790  QUrl( "https://website.nl/remote.php/webdav/" )  
11-30 22:45:56:790     \* event notification  disabled 
11-30 22:45:56:790 >===================================== sync started for  "ownCloud" 
11-30 22:45:56:790 void Mirall::CSyncThread::startSync() Sync started 
11-30 22:45:56:790 starting to sync  QThread(0x104c00120) QThread(0x104c96f00) 
11-30 22:45:56:790 Loading config:  "/Users/Koen/Library/Application Support/ownCloud/owncloud.cfg"  (URL is  "https://website.nl" ) 
11-30 22:45:56:790 Database Drivers could not be loaded. 
11-30 22:45:56:790 No database Transaction to commit 
11-30 22:45:56:790 No way to create a sync journal! 
11-30 22:45:56:836 -> CSync Finished slot with error  true warn count 0 
11-30 22:45:56:836 Starting Event logging again in  2000  milliseconds 
11-30 22:45:56:837 Loading config:  "/Users/Koen/Library/Application Support/ownCloud/owncloud.cfg"  (URL is  "https://website.nl" ) 
11-30 22:45:56:895 OO folder slotSyncFinished: result:  2 
11-30 22:45:56:895   *_ error Strings:  ("Unable to initialize a sync journal.") 
11-30 22:45:56:896     \* owncloud csync thread finished with error 
11-30 22:45:56:896 Folder in overallStatus Message:  Mirall::Folder(0x10489a1c0)  with name  "ownCloud" 
11-30 22:45:56:898 Sync state changed for folder  "ownCloud" :  "Error" 
11-30 22:45:56:898 SocketApi:  Sync state changed 
11-30 22:45:56:898 SocketApi:  Broadcasting to 0 listeners:  "UPDATE_VIEW" 
11-30 22:45:56:899 <===================================== sync finished for  "ownCloud"

**Comment by guruz** [comment]
@tps800 Do you still get this with 1.7.1 ?
What version of libsqlite3 do you have installed?

**Comment by tregeagle** [comment]
I was having the same error and just realised the drive containing the owncloud directory was not mounted. Silly me :/

**Comment by leenetworks** [comment]
The work around fix is to add Qt4 plugin path, which contains sqldriver explicitly, to env variable QT_PLUGIN_PATH.   make sure libqt-sqlite in your system

**Comment by guruz** [comment]
@leenetworks btw, the later client versions don't use Qt4 or the sqlite3 bundled with Qt anymore.

**Comment by sbliven** [comment]
I'm still seeing this message in 1.8.4 if my harddrive is full. I guess that's OK, although a more informative message would be more desirable.
