### ISSUE TITLE
Improve "Ignore Files" documentation

### ISSUE THREAD

**Issue by Pro** [owncloud/client#1261]
I couldn't find any useful information on the sync eclude patterns for the client.

(@danimo I alredy mentioned it in this issue but it seems that it isn't fixed: #788 , at least I couldn't find anything here http://doc.owncloud.org/desktop/1.4/visualtour.html#the-ignored-files-editor)

Can you explain in more detail the following points:
* For the exclude file list, does it take the absolute path, relative (to sync base) path or only the filename to match the regex?
* Which regex operators are supported? Only '*' and '?' or also '^' and '$' for beginning and end, or what about '[a-z]'?
* Do we need to escape special characters. If we want to match `foo.txt`we need to write `foo\.txt`
* How can I exclude a specific folder and all its content but not folder with the same name on a different level?

It would help if you provide some examples such as:

(assume I'm syncing `/home/user`)
* Exclude a specific directory (containing spaces) on root level (and all containing files) `/home/user/foo Dir` (but not `/home/user/bar/foo Dir`)
* Exclude all directories/files matching `.git` exactly (but not `/home/user/fooDir.git`)
* Exclude all directories/files containing foo in the name `/home/user/fooDir` and `/home/user/dir foo`)
* Exclude a specific file `/home/user/bar/fileToExclude.txt`

**Comment by carlaschroder** [comment]
I forgot to close this. http://doc.owncloud.org/desktop/1.7/navigating.html#using-the-ignored-files-editor
Thanks @KeyboardMidas

**Comment by KeyboardMidas** [comment]
NP ... looking good!
