### ISSUE TITLE
No E-Tag received from server, check Proxy/Gateway

### ISSUE THREAD

**Issue by anagno** [owncloud/client#1291]
Hi all,

Using the desktop client i am getting "No E-Tag received from server, check Proxy/Gateway" and a large portion of files is re-downloaded. (similar with https://github.com/owncloud/mirall/issues/1269?source=cc)

![screenshot from 2013-12-15 13 20 22](https://f.cloud.github.com/assets/5438380/1750224/30ab8514-657c-11e3-9c34-f3ba1ebb10a7.png)

Server configuration

Operating system: Ubuntu Server 12.04 LTS

Web server: Apache 2.2.22

Database: MySQL 5

ownCloud version: 6.0 (stable)

Client configuration

OS: ubuntu 12.04

Client: 1.5

Thanks in advance

**Comment by ogoffart** [comment]
Owncloud 8 has a OC-Etag header that should solve this problem.

In any cases, i'm closing this old issue because it has too many comments and this is not practical to track.  

If you still have problem with a recent owncloud, please open a new issue (following the issue template)

**Comment by blaskovic** [comment]
So.. This will NOT be fixed for owncloud 7?

**Comment by danimo** [comment]
@blaskovic correct.

**Comment by ottok** [comment]
@ogoffart If you consider this fixed, you can collect 150 USD from the bounty at https://www.bountysource.com/issues/1383937-no-e-tag-received-from-server-check-proxy-gateway

**Comment by ogoffart** [comment]
Someone just told me that the issue is actually not fixed in owncloud 8 because the fix of the server was reverted ->  https://github.com/owncloud/core/issues/9005
Maybe this is going to be in owncloud 8.1

Anyway, the client part is done as we read the oc-etag  header.
There is not much more we can do. So just make sure you don't have a proxy that remove the headers Or just track the server issue.

**Comment by moscicki** [comment]
@ogoffart: is the intention to replace standard Etag by OC-Etag in the future completely?

**Comment by Germano0** [comment]
I confirm this problem on Owncloud 8.0.3 / mirall-1.7.1-2.fc22.x86_64

**Comment by Germano0** [comment]
I disabled gzip but I am still experiencing the problem
nginx-1.6.3-2.fc21.x86_64
owncloud-8.0.3-2.fc21.noarch

```
# cat /etc/nginx/nginx.conf
# For more information on configuration, see:
#   * Official English Documentation: http://nginx.org/en/docs/
#   * Official Russian Documentation: http://nginx.org/ru/docs/

user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log;
#error_log  /var/log/nginx/error.log  notice;
#error_log  /var/log/nginx/error.log  info;

pid        /run/nginx.pid;


events {
    worker_connections  1024;
}


http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  65;

    #gzip  on; questa riga è l'originale. Ho messo off per via del bug di Owncloud con gli e-tag
    gzip off;
    index   index.html index.htm;

    # Load modular configuration files from the /etc/nginx/conf.d directory.
    # See http://nginx.org/en/docs/ngx_core_module.html#include
    # for more information.
    include /etc/nginx/conf.d/*.conf;

    server {
        listen       80 default_server;
        server_name  localhost;
        root         /usr/share/nginx/html;

        #charset koi8-r;

        #access_log  /var/log/nginx/host.access.log  main;

        # Load configuration files for the default server block.
        include /etc/nginx/default.d/*.conf;

        location / {
        }

        # redirect server error pages to the static page /40x.html
        #
        error_page  404              /404.html;
        location = /40x.html {
        }

        # redirect server error pages to the static page /50x.html
        #
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
        }
    }
}
```

**Comment by RealRancor** [comment]
To avoid double-posts: This post above was also posted in https://github.com/owncloud/client/issues/2980#issuecomment-112222382
