### ISSUE TITLE
1.5.0(build 1913) - Files containing '+' (plus) signs not synching

### ISSUE THREAD

**Issue by linuxcrash** [owncloud/client#1309]
### Expected behaviour

Files should get synced to the server.
### Actual behaviour

The windows client always reports "File not found" for that file if any of the files it tries to sync is containing a '+' sign. As soon as the filename is changed to not include '+' in the name it syncs correctly.
### Steps to reproduce
1. Create a folder
2. Create 3 files and 2 of them containg a '+' sign in the name (ex. "This is + my + file,jpg"
3. Wait for the client to report "File not found".
### Server configuration

Operating system: Windows 2008 R2 Standard English

Web server: IIS 7.5

Database: MSSQL 2012 Express

PHP version: 5.4.4

ownCloud version: 6.0 a

Storage backend: local disk
### Client configuration

Client version: 1.5.0(b 1913)

Operating system: Windows 7 Enterprise English x64

OS language: English

Installation path of client: default.

**Comment by Trapulo** [comment]
same problem. Owncloud 8.0, client 1.7.1, server on IIS 8/2012

**Comment by dragotin** [comment]
@Trapulo note that IIS is not supported. Better use linux for your server.

**Comment by Trapulo** [comment]
Is not supported? It has installation procedure in online administrator's guide...

However, IIS is a full featured platform. Owncloud is based on PHP, and PHP is officially supported on IIS. So I think that is will a be a great result every effort to run it on IIS without problem, it may be not so hard. My 2 cents, of course...

**Comment by danimo** [comment]
Unfortunately, this deduction is wrong. PHP for IIS is terribly limited. For instance, it still does not support Unicode filenames. There is not much hope that the PHP project will approach this any time soon.

While you are right that there is still a description in the docs, support for it was only "best effort". Consequently we're hence going to deprecated Windows in the forthcoming versions.

**Comment by elessard84** [comment]
Sorry if my english is not so good

I have the same exact biavior on a linux server (ubuntu + owncloud from the lastest repository + mariadb) I use utf-8. I migrated from my iis Owncloud to an ubuntu based server on the assumtion that will have helped with that glitch but same exact glitch on linux. Only thing that helped me with is upload over 2.2gb
Here an screen of what does the sync client.
![owncloud_2015-03-10_23-02-00](https://cloud.githubusercontent.com/assets/11358571/6589711/a2a011c4-c77a-11e4-9280-2d795272e87c.png)

**Comment by elessard84** [comment]
@danimo Your 100% right --' that IIS the culprit. Before reaching my linux server I use a iis reverse proxy to separate owncloud from my other web service. I tried to bypass the iis reverse proxy by using the server IP on my local network and all work fine... soooo I have few hours of work reconfiguring all my system or I use the port fowardind inelegant solution.

**Comment by Trapulo** [comment]
Sorry, IIS is not a culprit. It's a very flexible and robust platform. You can do anything you need using IIS, and it's solid. PHP can be a problem, as @danimo said, this is right. But is PHP the problem, non IIS.
