### ISSUE TITLE
Cannot add new folder for syncing because of stale TCP connection(?)

### ISSUE THREAD

**Issue by csware** [owncloud/client#1312]
Mirall 1.5, Windows 7 x64

1. Open Mirall
1. Click Add folder
1. Choose lokal folder and alias
1. Click Next

Now, the remote server tree stays empty. Clicking on refresh doesn't help.

I experienced this several times. Restarting Mirall 1.5 sometimes helps.

**Comment by guruz** [comment]
With the 1.8 client we use a different network library which should fix this.
