### ISSUE TITLE
Linux Mint: Client-Icons is not visible

### ISSUE THREAD

**Issue by stefan-niedermann** [owncloud/client#1326]
I am using Linux Mint Debian Edition with Cinnamon 1.8.8
I downloaded the latest ownCloud client and started it.

a dialoge appeared where i can configure my url, username and password.
the sync works perfectly, all is synced in the $home$/ownCloud folder.

But in my list (where date, battery, sound etc) the icon of owncloud does not appear, so i can't configure the client, i can not start the gui.

I tried to purge and reinstall, but the icon does not appear.

it works in other configurations (linux mint based on ubuntu with cinnamon 2.0).

Any idea or workaround to start the gui?

**Comment by gijshvg** [comment]
I shared the problem and also the solution (working with Mint 17 with Cinnamon). I only had to push up the delay to 20 seconds before it worked.

**Comment by iguild** [comment]
Just wanted to leave a note that @Jehan's workaround works in Linux Mint 19 as well.
