### ISSUE TITLE
Excel saving problem

### ISSUE THREAD

**Issue by dali-dbr** [owncloud/client#1341]
Hi.

I have a big Excel file (cca 10mb). It will take about 10sec to save. In the meantime OC client already tries to upload it resulting in error.

![excel](https://f.cloud.github.com/assets/6317229/1893748/5cad172c-7ab2-11e3-9d79-2e7a2bdb074b.JPG)

It seems OC grabs the file, making it not available for other apps to overwrite it.

My system:
Windows 8.1
OC client. 1.5.0 (b1913)
The folder is synced to a shared folder from another account. Can Edit is enabled.

Thank you
Br,
Dali

**Comment by guruz** [comment]
1.8 will have a improved method for uploading on Windows.
If you are brave enough to try a recent daily build of the client, please try out http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.4644-nightly20150126-setup.exe and report back if we can close this issue by now...

CC @dragotin

**Comment by ckamm** [comment]
@suamikim Could you try the nightly build guruz linked - or try it once 1.8 is out?

**Comment by suamikim** [comment]
I just installed the nightly on one of my clients and am going to let you know how it works. Thanks for the update!

**Comment by suamikim** [comment]
I've already installed the nightly at one of my clients at home and can say that it seems to work flawlessly so far. I just wanted to install it on my work client too but can't download it anymore since the link is broken...

**Comment by ckamm** [comment]
@suamikim You can find all the daily builds at http://download.owncloud.com/desktop/daily/

Please reopen this issue if you experience this problem again.
