### ISSUE TITLE
Sync client could have manual "force sync" option and display last sync info

### ISSUE THREAD

**Issue by halfgaar** [owncloud/client#135]
The sync client could provide the user with more information about the sync status. Currently, all it says "the last sync was successful", but you have no idea when it was or what it synced.

Also, I think it would be a good idea to have a manual sync button.

**Comment by McCovican** [comment]
I have found myself in a near-identical situation as @Klausthorn here. Using a password DB, make change, save it, and ownCloud just wont update it in regular course. It's been over an hour now, which clearly isn't optimal. Fixing the issue that causes the client to not sync changes automatically would obviously be a preference, but I think at this point a "Force Sync" button is also an absolutely necessary measure. To put this all down to PEBKAC is a poor show.

**Comment by AshleyYakeley** [comment]
I tend to switch my server on and off a lot, so a way of telling OwnCloud that the server is available would be really useful.
