### ISSUE TITLE
system ignored files list in enterprise use-case

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#1369]
Hello,

We want to include several ignore patterns for all users. These patterns should be treated in a similar way as the hardcoded set of patterns distributed with the client (i.e. users should not be able to remove them).

How do we achieve this? What if we identify a new ignore pattern to be added and distributed to hundreds of enterprise clients without requiring them to reinstall / upgrade version?

One implementation I can think of is that the sync client periodically downloads the pattern definition from the server. Is this possible?

kuba

**Comment by MarkMaldaba** [comment]
See https://github.com/owncloud/core/issues/22607 for a suggested method of handling this.

**Comment by guruz** [comment]
-> https://github.com/owncloud/client/issues/434
