### ISSUE TITLE
Make (all) remote poll intervals configurable in the GUI

### ISSUE THREAD

**Issue by eht16** [owncloud/client#1393]
Am I missing something or is the remotePollInterval config setting not configurable from the UI? If not, please make it configurable (yes, one can change it in the config file, after figuring it has to be specified in MILLIseconds with a lower limit of 5000...).

But more important, it seems there is a hardcoded 30 seconds interval which can't be configured (https://github.com/owncloud/mirall/blob/master/src/mirall/quotainfo.cpp#L25). Could that be made configurable as well or even better, make it to use the already existing remotePollInterval config setting.

I'm trying to reduce HTTP requests to my OwnCloud instance.

Using version 1.5.0

**Comment by oxidworks** [comment]
The place is still /.local/share/data/ownCloud but the Bug report is closed.
This is a strange place for the config file of the client
