### ISSUE TITLE
Find out how we can have gzip compressed WebDAV XML responses

### ISSUE THREAD

**Issue by guruz** [owncloud/client#1399]
Neon does not send ```Accept-Encoding``` and also doesn't seem to have a way of decoding the XML responses before parsing them.
PUT and GET are another thing, we are installing a ne_decompression_reader manually in http://code.woboq.org/owncloud/csync/modules/csync_owncloud.c.html#994 but since ne_propfind_named doesnt have a content reader we cannot use this.
See also http://code.woboq.org/owncloud/neon/ne_props.c.html#propfind

Me asking on the neon mailinglist didn't give a response (http://comments.gmane.org/gmane.comp.web.webdav.neon.general/912 )

Maybe there is a way after all somehow?

**Comment by guruz** [comment]
Closing this as #2507 has been merged.
Could at some point convince the server to send us gzipped WebDAV response.. (not sure if this is a webserver setup thing or needs to be done in PHP with output handlers..)

CC @evert @DeepDiver1975

**Comment by evert** [comment]
I'm personally very curious what the answer is to this. I could definitely help get this going by providing a patch, but I'd need people to test this on various clients.
