### ISSUE TITLE
Client v1.5.0 Problem with files having extension eml

### ISSUE THREAD

**Issue by GrafKrollock** [owncloud/client#1403]
Hello,
we observe here a strange behavior with files that having the extensions EML (Thunderbird mail) or LNK (Windows shortcuts). Once created, they can no longer get away.
If you delete this on a client, the deletion is replicated clean to the server. But all other clients load up the files again and distribute them so again to everybody. It does not matter which client performs the deletion and what operating system it is running (tested on Windows and Mac). A direct delete via the web interface brings no success. It is by the way also not matter what content the file has. Any file that I rename two one of the two extensions will be an permanent guest in the ownCloud.

The only thing that really brought success, was a coordinated simultaneous erasure on all clients and the server. But that can not be the intention.

We talked with other people in the owncloud forum. And many else can confirm this issue.

Regards
GrafKrollock

**Comment by pierrejochem** [comment]
Thank you. Had the same case with OC 9 and CL 2.1.1 ... I could not explain why the only pattern was the extension eml and after checking the create time from the files I saw that they are changed frequently... The reasion makes now sense and the good point is that the cloud is working like it is designed for :+1:

**Comment by buggy82** [comment]
Still have the .eml issue with OC 9.0.2 and Sync Client 2.1.1 (build 5837) on Windows 10.
The fix from Sync Client 2.1. did not fix this issue.
"Don’t re-upload *.eml-files if size and checksum are unchanged"

Had to put .eml files on Ignore List to stop continuous traffic.

**Comment by guruz** [comment]
@buggy82 We have special code for this in 2.2beta2. Maybe you want to try that (with *.eml removed again from the ignore list). https://owncloud.org/install/#testing-development
Please report back if this works or not.

**Comment by pierrejochem** [comment]
Sounds Great :-)
