### ISSUE TITLE
Config file location on Linux should be in ~/.config instead of ~/.local

### ISSUE THREAD

**Issue by eht16** [owncloud/client#1409]
According to http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html, I'd suggest to use *~/.config/ownCloud/* instead of *~/.local/share/data/ownCloud/* as *~/.local/share/data/* is rather meant for data files. 

*~./config/ownCloud/* would also actually be the first place where I expected to find the config file as an ordinary Linux user.

**Comment by guruz** [comment]
@ogoffart Does it make sense to tackle this as part of the anyway (?) refactored handling of sync folder / account settings storage migration?

**Comment by ogoffart** [comment]
Merged with #2245
