### ISSUE TITLE
Simplify Enterprise Provisioning (MSI)

### ISSUE THREAD

**Issue by danimo** [owncloud/client#1419]
Simplify the job of rolling out ownCloud in Enterprises:
- Depends: #860 (MSI Installer) for deployment on WIndows
- Depends: Move config routines in their native environment on Windows (registry) and Mac (plist, see #803)

Usually, there are two kinds of settings: Global Settings (pre-seed values, which can be overridden by the user) and Policies (which cannot be overridden): While the former is well-understood and established on all platforms, the question is what the the solutions to the latter are:
- Windows: Use Group Policies (well-established)
- Mac: best practices unclear, input appreciated
- Linux: no clear standard, input appreciated

Possible use cases:
- Provision Server URL
- Set restrictions
- Set scheme to automatically use as user name

**Comment by charliwest** [comment]
For the autopkg idea raised here is that something someone would be able to work on? I have tried but got no where with it really :(

**Comment by danimo** [comment]
@dragotin This one makes no sense to have for a certain milestone, it's a tracking-only issue. Rescheduling to backlog.

**Comment by MTRichards** [comment]
Returning to this for 2.2 planning purposes.

**Comment by charliwest** [comment]
For those following this who use autopkg I did finally manage to get a recipe for pkg and jss if anyone would like to use it
https://github.com/charliwest/jss-recipes/tree/master/ownCloudDesktopClient

**Comment by dragotin** [comment]
@MTRichards can we move this out of the 2.2 milestone?

**Comment by MTRichards** [comment]
Ok. To discuss in design days I think.

**Comment by danimo** [comment]
Moved to 2.3

**Comment by dragotin** [comment]
For milestone 2.3.0: research, Implementation for 2.4.0

**Comment by xav-stargate** [comment]
Development started? I would also be very interested =)

**Comment by michaelstingl** [comment]
@xav-stargate We built the first MSI's and it would be awesome if you could provide feedback. Ping **michaelstingl** in `#owncloud-testing` on IRC (webchat.freenode.net for example).

Here you can find an early draft of the docs:
https://github.com/owncloud/client/blob/msi-doc/doc/installing.rst

**Comment by t2d** [comment]
As soon as one can pre-configure the `Server Address`, I would be very happy to test.

**Comment by michaelstingl** [comment]
@t2d MSI installer works only on system level. All operations in the wizard are in the scope of the current user.

Do you use other software where you set "per user" configuration with the MSI installer?

**Comment by t2d** [comment]
@michaelstingl I wasn't aware of this fact. However, you *could* implement a system-wide default and a switch that says

1. Pre-fill the field with the default or 
2. Pre-fill the field with the default  and don't allow other values

I'm aware, you cannot implement this in the installer only. But it would be very handy for a corporate environment.

**Comment by michaelstingl** [comment]
For corporate environments ownCloud offers branding services that generate customized clients with corporate design, fixed URL, etc for Win, Mac and all flavours of Linux. Everything that gets implemented based on the MSI installer is limited to the Win platform only.

**Comment by Square252** [comment]
Any news on this?

This is becoming a major one for us in the next time...

**Comment by michaelstingl** [comment]
@Square252 please send a mail to apps@owncloud.com, I could send you a *.MSI for testing.

Here you can find an early draft of the docs:
https://github.com/owncloud/client/blob/msi-doc/doc/installing.rst

**Comment by guruz** [comment]
@dschmidt FYI https://github.com/owncloud/client/pull/6113/files#diff-6d334f4d2fb17b337b721262d6904f16L605

**Comment by michaelstingl** [comment]
Win clients 2.5.0+ available with MSI installer.

Blog post:
https://owncloud.org/news/desktop-client-2-5-0-release-virtual-file-system/

Docs:
https://github.com/owncloud/client/blob/v2.5.0/doc/installing.rst#customizing-the-windows-installation

**Comment by guruz** [comment]
Closing as we have MSI now.
Specific provisioning variables should be done in  new tickets :)
