### ISSUE TITLE
Add display of transfer speed to the client

### ISSUE THREAD

**Issue by that0n3guy** [owncloud/client#142]
It would be nice if we could hover over the owncloud client icon (or right click, or show it in status) and see the transfer speed (dropbox does this).

Not a high priority, just something that would be nice.

**Comment by llamafilm** [comment]
This issue is about showing current transfer speed.  The pull request is about showing estimated completion time.  Two different things, so this issue should be reopened.

**Comment by michaelstingl** [comment]
Transfer speed is show in the tooltip (verified with 2.6.0 on macOS)
