### ISSUE TITLE
Desktop activity list is not the activity stream

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#1443]
Currently, the Activity tab of the desktop client is not the same as the server activity stream.  While the desktop activity list is QUITE helpful, it should be called something like sync log, and the actual server activity stream should load in the activity tab.

**Comment by guruz** [comment]
@MTRichards I don't think this is feasible still for 2.0
Move?

**Comment by MTRichards** [comment]
Updated to 2.1, thanks for the ping.

**Comment by jancborchardt** [comment]
Ref https://github.com/owncloud/client/issues/2530 https://github.com/owncloud/client/issues/1745

**Comment by MTRichards** [comment]
https://github.com/owncloud/activity/issues/349

**Comment by Dianafg76** [comment]
Related #3732 , #4083

**Comment by dragotin** [comment]
I think this is only a high level view on #3732, closing hence, lets track over there.

**Comment by jancborchardt** [comment]
I disagree with closing this as now the low-level technical detail overruled the high-level plan which is easier for people to relate.

See feedback from @jospoortvliet at https://github.com/owncloud/client/issues/3737#issuecomment-159935917 and my counter points at https://github.com/owncloud/client/pull/4083#issuecomment-154416450

**Comment by dragotin** [comment]
See new issue #4208
