### ISSUE TITLE
Settings dialog layout, simplification

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#1451]
Some small suggestions for improving the settings dialog:

* cut the »Account to Synchronize« header, it duplicates the »Account« navigation entry
* shorten Storage Usage -> Storage
* shorten Account Maintenance -> Maintenance
* left-align the elements to the headers
* right-align the buttons on the right with the close button on the right
* the »Note« section of the Storage Usage part is not that important, so it should not be bold. The whole note should have a bit smaller font-size and be lighter/grey instead of black.

Before:
![owncloud-settings](https://f.cloud.github.com/assets/925062/2198374/85378d5c-98c7-11e3-9a95-776595978e31.png)
After:
![owncloud-settings-new](https://f.cloud.github.com/assets/925062/2198378/8e66a502-98c7-11e3-91bd-5cda8a838313.png)

**Comment by guruz** [comment]
Please re-evaluate

**Comment by jancborchardt** [comment]
We basically took care of all of this during 2.0 (thanks @ogoffart and everyone involved!) so I’ll close this. :)
