### ISSUE TITLE
Sync dialog note twitches

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#1455]
When downloading files, the sync dialog note twitches between saying »Start downloading ```filename```« and »Currently downloading ```filename```«. That usually happens so fast (with small files) that it looks like a glitch. And you can’t really follow which file it’s working on.

Instead, just say »Downloading ```filename```«. No matter if it’s »Starting« or »Currently« doing that – whatever the difference is.

**Comment by Dianafg76** [comment]
I tested this issue. I have not had any dialogue Sync spasms note.
DESKTOP v 1.8.2 (build 2417)
So, I close the issue
