### ISSUE TITLE
[1.5.1] client syncing fails silently, when the certificate has changed. Expected behaviour: immediate warning, that certificate has changed

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/client#1468]
I noticed a misbehaviour of the client when the certificate of the server has **changed** (in my case, the certificate was changed intentionally as explained below).

#### How to reproduce

* install the client and enable (add) an account on your oc server via SSL ( (I use http://www.CAcert.org certificate)
* during the installation, the client asks you to check the certificate (fingerprint and issuer data) if the CA is not part of the operating system CA list (CAcert.org is not). If the fingerprints match the fp's detected on your server, that's fine.
* client-server syncing works. That is the normal state, and you'll always see the **green** sync checkmark in the task tray.

#### when the server certificate changes ...

Now assume, that you update the server certificate- in my case, I updated my certificates, because CAcert.org recently (2014-01-23) improved security by changing their signature hashing algorithm to SHA512 see http://blog.cacert.org/2014/01/cacert-with-new-signature-algorithm/ .

If the server certificate is changed, the client silently stops syncing - which is a secure and safe reaction, but the user is perhaps not aware of this sync stop.

#### ... the oc client should immediately pop up the server certificate warning

I wish and suggest, that then the oc client shows the server certificate warning window (like during account creation, see above) every time, when the certificate has changed, immediately.

#### Workaround to get the sync working when server certificate has changed

I used this work-around, to get the sync working again:

* close the client
* restart the client - then(!) the server certificate warning window pops up and prompted me to verify and confirm the new certificate.
* syncing started again.

**Comment by ogoffart** [comment]
Closing old issue since we don't use neon anymore
