### ISSUE TITLE
Use remotePollInterval for quotainfo sync interval

### ISSUE THREAD

**Issue by eht16** [owncloud/client#1470]
Since I can't re-open #1393 here we go with a new issue:

I still would wish that the currently hardcoded 30 seconds timeout for the quota stuff (https://github.com/owncloud/mirall/blob/master/src/mirall/quotainfo.cpp#L25) would be changed to be the same as the already configurable remotePollInterval setting.

As described in #1393, for me personally 30 seconds are too short and I guess I'm not the only person thinking so.

**Comment by LukeOwncloud** [comment]
Any update here? IMHO it is essential to respect users' configurations. With a poll interval of e.g. 5 minutes the server should not be contacted every 30 seconds! It unnecessarily drains the battery on portable computers.

**Comment by niltonvasques** [comment]
I would appreciate if it can be done using some config file. As @LukeOwncloud said, is annoying have all clients pulling the server two times per minute, plus waste of battery charge. +1

**Comment by guruz** [comment]
Good news, the 2.0 client will only query the server if the UI is visible.. :)

@ogoffart correct me if i'm wrong

**Comment by nonzerosums** [comment]
Using  OC client v2.1 from Linux Mint 17.3, I still see this issue.  I'm not sure I understand "... if the UI is visible.."  I do have it set to autostart upon login but even without opening the interface, it is polling the server every 30 seconds.  Are the rest of you still seeing this too?

**Comment by guruz** [comment]
Those are not polling the quota but if there were remote changes..

**Comment by eht16** [comment]
For me it doesn't make much difference for what the client is querying the server. I personally can live with delayed checks for updates, accepting the risk of not being completely up2date.
The point here is to make the server query intervals configurable for the user. Then the user can choose which interval fits best for her.

**Comment by nonzerosums** [comment]
@guruz:  Yes, I understand that.  True, perhaps this isn't the most appropriate issue report to be commenting on but I was brought here from yet another closed issue report where @LukeOwncloud linked to this thread for further discussion of client connection frequency and configurability.

He, I, and @eht16(OP!) seem to be coming from the same perspective.  And fwiw, I'd advocate for @eht16 position on configurability of query intervals.  

But my question has been answered -- so I know it's not just me seeing this issue.  If anyone else visiting this thread can point to a more appropriate one addressing this issue, I'd be appreciative.  Thanks.

**Comment by LukeOwncloud** [comment]
I just checked the server log. I set `remotePollInterval=5min`. When starting oc client the server is connected every 30 seconds for 5 minutes. After that server is contacted only every 5 minutes. When opening the oc client GUI, again for 5 minutes every 30 seconds a query is issued (even though GUI was opened only for a few seconds).

	ip - luke [27/Jan/2016:19:13:05 +0100] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 1332 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [27/Jan/2016:19:13:26 +0100] "PROPFIND /remote.php/webdav/luke HTTP/1.1" 207 11835 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [27/Jan/2016:19:18:57 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1245 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [27/Jan/2016:19:19:28 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [27/Jan/2016:19:20:00 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [27/Jan/2016:19:20:32 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [27/Jan/2016:19:21:04 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [27/Jan/2016:19:21:36 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [27/Jan/2016:19:22:08 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [27/Jan/2016:19:22:40 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [27/Jan/2016:19:23:02 +0100] "PROPFIND /remote.php/webdav/luke HTTP/1.1" 207 1222 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [27/Jan/2016:19:28:02 +0100] "PROPFIND /remote.php/webdav/luke HTTP/1.1" 207 1222 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [27/Jan/2016:19:33:02 +0100] "PROPFIND /remote.php/webdav/luke HTTP/1.1" 207 1222 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"

Can anybody confirm this? Is this the intended behavior?

**Comment by ogoffart** [comment]
`5min` is not a proper value, you need to set a value in ms.

`remotePollInterval=300000` should work

**Comment by LukeOwncloud** [comment]
Yes, that is what I did. My wording above was just bad.

**Comment by LukeOwncloud** [comment]
I have to correct myself. The server log looks like this:

	ip - luke [01/Feb/2016:13:06:32 +0100] "PROPFIND /remote.php/webdav/Media HTTP/1.1" 207 1221 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:13:12:01 +0100] "PROPFIND /remote.php/webdav/Media HTTP/1.1" 207 4135 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:13:17:31 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1245 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:13:18:03 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:13:18:35 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:13:19:07 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:13:19:39 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:13:20:11 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:13:20:43 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:13:21:15 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:13:21:32 +0100] "PROPFIND /remote.php/webdav/Media HTTP/1.1" 207 1221 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:13:26:32 +0100] "PROPFIND /remote.php/webdav/Media HTTP/1.1" 207 1221 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:13:31:32 +0100] "PROPFIND /remote.php/webdav/Media HTTP/1.1" 207 1221 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	... 20 more times ...
	ip - luke [01/Feb/2016:15:17:01 +0100] "PROPFIND /remote.php/webdav/Media HTTP/1.1" 207 4135 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:15:22:51 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1245 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:15:23:23 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:15:23:55 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:15:24:27 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:15:24:59 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:15:25:31 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:15:26:03 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:15:26:32 +0100] "PROPFIND /remote.php/webdav/Media HTTP/1.1" 207 1221 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:15:31:32 +0100] "PROPFIND /remote.php/webdav/Media HTTP/1.1" 207 1221 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:15:36:32 +0100] "PROPFIND /remote.php/webdav/Media HTTP/1.1" 207 1221 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	... 20 more times ...
	ip - luke [01/Feb/2016:17:22:01 +0100] "PROPFIND /remote.php/webdav/Media HTTP/1.1" 207 4135 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:17:27:39 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1245 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:17:28:11 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:17:28:43 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:17:29:15 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:17:29:47 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:17:30:19 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:17:30:51 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:17:31:23 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1388 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"
	ip - luke [01/Feb/2016:17:31:32 +0100] "PROPFIND /remote.php/webdav/Media HTTP/1.1" 207 1221 "-" "Mozilla/5.0 (Windows) mirall/2.1.0"

So `PROPFIND /remote.php/webdav/Media` takes place every 5 minutes and thus obeys `remotePollInterval=300000`. I assume this is for checking for changes. However, about every 2 hours `PROPFIND /remote.php/webdav/` is issued every 30 seconds for 5 minutes. These propfinds are for quota checking, correct? Checking every two hours sounds good to me. But why is the check repeated so often?

**Comment by guruz** [comment]
@LukeOwncloud Sounds indeed funny. Will need to have a look at the code..

**Comment by ogoffart** [comment]
The quota check is done every 30 seconds only if the settings dialog is visible.
