### ISSUE TITLE
No way of changing between HTTP and HTTPS.

### ISSUE THREAD

**Issue by danielholm** [owncloud/client#1478]
Hi,

It should be easier to change the security back and fourth between HTTP and HTTPS.
I recently got a cert for my server and I am unable to change the setting to a secure connection.

There should therefore be a checkbox, or something in the settings window.

Is there a certain reason why there already isn't like it's complex to change or something?

**Comment by ckamm** [comment]
Making it easy to edit the server URL would lead to lots of problems and confusion, we're unlikely to allow that.

Building an explicit switch or automatic detection for this particular case seems like it'd not be worth the effort.

I think editing the URL is going to stay the prefered way of making this change.
