### ISSUE TITLE
Error in NSIS/NSISOutput.log 

### ISSUE THREAD

**Issue by Knudn** [owncloud/client#1480]
Hi, im trying to build myself a client, and ive been going on forever now. As far as I know, i've followed the instructions as good is I can. 
But im still getting this output when in the /root/mirall/_CPack_Packages/unused/NSIS/NSISOutput.log  running  the “make package” command.

…
…
File: "QtNetwork4.dll" 1438208 bytes
File: "QtSql4.dll" 249856 bytes
File: "QtXml4.dll" 374272 bytes
File: "QtWebKit4.dll" 23380480 bytes
File: "libpng15-15.dll" 174209 bytes
File: "/usr/i686-w64-mingw32/sys-root/mingw/bin\libsqlite3-0.dll" -> no files found.
Usage: File [/nonfatal] [/a]([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "/root/mirall/_CPack_Packages/unused/NSIS/project.nsi" on line 401 -- aborting creation process

Running Opensuse 12.1 x64 on VirtualBox, and im trying to build a client for windows.

And I have tried to do anything I can think of, I would really appreciate any help :)

**Comment by lmartinez073** [comment]
Hi

I followed your link but I still get this error 

CPack Error: Problem running NSIS command
CPack Error: Problem compressing the directory.

Any advice will be apreciated.
