### ISSUE TITLE
Bandwidth Throttling: Provide automatic limit setting for download as well

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#1485]
In the current desktop client, the bandwidth throttling tab has download and upload. For some reason, download is by KB only. Upload is automatic.

What does automatic mean?

Would be great if we had three options on both upload and download sides:
1) None
2) High/Med/Low Dropdown (for the uninitiated user)
3) Set KB/s 

![untitled3](https://f.cloud.github.com/assets/1818977/2269997/e56add32-9ee4-11e3-8cd9-51a52e348318.png)

**Comment by Dianafg76** [comment]
I close this issue, it is working fine
