### ISSUE TITLE
Accounts to Synchonize sort order

### ISSUE THREAD

**Issue by MU7L3Y** [owncloud/client#1529]
### Expected behaviour
The client accounts (folders on PC) should list the accounts in a logical order. Perhaps order them alpha-numerical.

### Actual behaviour
The client accounts seem to list the accounts (folders on PC) in a random order.
See my example. It should list 01-18 but they are all out of whack...
![image](https://f.cloud.github.com/assets/5826968/2329382/6eaf9ec0-a417-11e3-8250-717effbb657b.png)

### Steps to reproduce
1. Install client 1.5.2
2. Remove default folder and add a number of other folders to sync.
3. Right-click tray icon or open OC.

### Server configuration
Operating system: Linux shared hosting

Web server: Apache

Database: MySQL

PHP version: 5.3.27

ownCloud version: 6.0.1

### Client configuration
Client version: 1.5.1 & 1.5.2

Operating system: Windows Small Business Server 2003

OS language: English

Installation path of client: C:\Program Files\ownCloud

**Comment by danimo** [comment]
Merged @rullzer 's patch. Closing because I do not think it should be sorted by status (that would seemingly randomize it again).

**Comment by danimo** [comment]
Thanks @rullzer btw!

**Comment by MU7L3Y** [comment]
@rullzer @danimo I just installed 1.8.0 and that right-click tray menu is perfect, thanks. But it seems the actual owncloud dialog was missed in sorting the folders?
![image](https://cloud.githubusercontent.com/assets/5826968/6720604/81fcdb6a-ce18-11e4-8f5c-b35b28d42555.png)

**Comment by guruz** [comment]
Let's re-evalulate this as part of the new account UI in 2.0

@ogoffart

**Comment by MU7L3Y** [comment]
I look forward to this update. I have 1.8.1 now and it's still really hard to find folders sometimes, especially with each folder shown really big like in the pic I posted above. Maybe have different view options? Large/Small etc.

**Comment by Dianafg76** [comment]
I tested with DESKTOP v ownCloud-2.0.0.5232, is working fine.
I close the bug

**Comment by MU7L3Y** [comment]
Yes this is working now in 2.0.0 and 2.0.1. Thank you.
