### ISSUE TITLE
OC-920 Linux OwnCloudClient GLib Error - Too many open files 

### ISSUE THREAD

**Issue by msrex** [owncloud/client#154]
http://bugs.owncloud.org/thebuggenie/owncloud/issues/oc-920

The original report:
Unknown info from ownCloud status.php:  "installed" = "true" 
# -------# oC found on  "https://cloud.***.org"
- Polling "***" for changes. Ignoring all pending events until now 
-  "**_" Poll timer disabled 
  Schedule folder  "**_"  to sync! 
  XX slotScheduleFolderSync: folderQueue size:  1 
  ==> load folder icon  "owncloud-icon-framed" 
  Sync state changed for folder  "_**" :  false 
  *_\* Start syncing url to ownCloud:  "ownclouds://cloud.**_.org/files/webdav.php/**_" , with localOnly:  false 
  GLib-ERROR **: Creating pipes for GWakeup: Too many open files
  Trace/Breakpoint triggered

There are lots of attachments in buggenie, and a reporter actively waiting and checking back.

**Comment by jult** [comment]
Still existing, even with the 1.8.3.* clients. Both x64 linux as well as Windows.

**Comment by sciurius** [comment]
Haven't seen this for a while now on Fedora 22 with owncloud-client-2.0.1-3.1.x86_64.
