### ISSUE TITLE
ownCloud folder modification time misleading

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#1566]
Even when you didn’t change any files in your ownCloud for the past days, the modified date of the ownCloud folder is always very recent. (This is especially apparent if you have set your folders to sort by modification date.)

This apparently is due to the .csync_journal.db which updates regularly. Because it’s a hidden technical file and not interesting to people, it’s confusing as to why the modified date is so recent. It leads to worries if files have changed or were deleted.

I guess a way to resolve this would be to not have the .csync_journal.db inside the ownCloud folder but rather in the config directory (in the case of Ubuntu `~/.local/share/data/ownCloud`).

**Comment by ogoffart** [comment]
Closing old issue.

**Comment by jancborchardt** [comment]
The issue still exists though. The modification time of the »ownCloud« folder is newer than any of the contents I have in it.

**Comment by hodyroff** [comment]
As we have no good idea how to deal with this any differently and it seems logical that the mtime changes when we put a hidden file into the folder and update it, this is closed as works as designed. We might want to make a note in a FAQ or documentation. Reopen (or comment) please if there is great idea how to make it differently.
@owncloud/doc @pmaier1
