### ISSUE TITLE
Desktop Client: Run as a Windows Service

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#1581]
As an administrator, I would like to run ownCloud as a Windows service so that I can sync between a server and ownCloud.

@gig13 Please add info.

**Comment by jfulfer** [comment]
Tried running through the steps within the forum post here to configure owncloud to run as a service which works for the most part as long as it's setup correctly.
https://forum.owncloud.org/viewtopic.php?t=2675

One thing that will need to be addressed before OC can officially run as a service is the prompt when a synchronized directory is cleared out via the webUI. This prompt prevents the service from allowing continuous synchronization until it is answered. This requires the user to log in which defeats the purpose of allowing it to run as a service.

**Comment by hodyroff** [comment]
I am quite sure that this can be configured and switched off. Can you check @jfulfer ?

**Comment by danimo** [comment]
Set `promptDeleteAllFiles=false` in the owncloud config file. However, running the client as a Windows Service is not advisable, nor supported, even considered harmful. The client is not guranteed to run properly without its GUI and may therefore stop syncing at any time.

**Comment by vapaa** [comment]
is any activity on this topic?

**Comment by hodyroff** [comment]
@vapaa Did you try to run it with NSSM? If so, any specifics problems you did run into? We continue to recommend that patch and its mostly used for functional users who don't delete the folder connection on the server side ... which will make it non-working anyway.
Do we officially support this, no but its used by some of our customers for those specific situations. We have no way to cover all the corner cases ...

**Comment by vapaa** [comment]
@hodyroff The sync with the service works fine, not with the tool you recommended but it works ;)

Thanks

**Comment by michaelstingl** [comment]
Related blog post:
https://blog.network-it.ch/?p=665

**Comment by TheOneRing** [comment]
> Related blog post:
> https://blog.network-it.ch/?p=665

**Comment by Knutowskie** [comment]
The blog is dead. is there any solution? as nextcloud and owncloud are close together, i need solutions for both cloud solutions.
