### ISSUE TITLE
[Documentation] Document sync workflow

### ISSUE THREAD

**Issue by danimo** [owncloud/client#1588]
We should document the basic commands flowing in a typical client session so other people can verify and understand what's happening. This should include:
- Commands sent during setup / start
- Commands sent when a remote server poll is triggered
- Basic Commandfow of a sync, including possible commands
- Commands sent under special conditions

We also need to document special conditions, like extra headers, timing of certain jobs as implemented in the client currently, etc.

Let's do it in a GitHub wiki page

@dragotin @ogoffart @guruz

**Comment by guruz** [comment]
@ogoffart Wasn't this done?

**Comment by settermjd** [comment]
@ogoffart @guruz is this still required?

**Comment by guruz** [comment]
Let's close this as we have https://github.com/cernbox/smashbox/tree/master/protocol and the code should be the main documentation for engineers.
