### ISSUE TITLE
Code signing Mac client fails

### ISSUE THREAD

**Issue by scolebrook** [owncloud/client#1592]
Expected behaviour
Running the code signing script should at admin/osx/sign_dmg.sh should convertthe dmg created during the build process to a writable one, mount it, sign owncloud.app with the supplied identity, unmount and convert back to read only image.

Actual behaviour
The codesign command fails. Disk images all get made successfully but the app never gets signed.

Steps to reproduce
1. Build client for Mac.
2. cd to build directory.
3. ../mirall-1.5.3/admin/osx/sign_dmg.sh ownCloud-1.5.3.0.dmg <name of code signing identity in Keychain>

Client configuration
Client version: 1.5.3

Operating system: OS X 10.9.2

Output:
<path to owncloud.app>: bundle format unrecognized, invalid, or unsuitable
In subcomponent: <path to QtCore.framework>

The Qt\* frameworks do not have Info.plist files copied during the build process so codesign doesn't recognize them as bundles in Mavericks. It appears that this is a change in the Mavericks version of codesign. Mavericks requires all frameworks in an app bundle to be signed, not just the app itself. Attempting the sign the frameworks individually results in the same error message.

Manually copying the Info.plist from /usr/local/cellar/qt/4.8.5/Frameworks/QtCore.framework/Contents to <path to finished owncloud.app>/Contents/Frameworks/QtCore.framework/Contents for example allows codesign to successfully sign the framework.

The fix would be altering the build scripts to copy Contents/Info.plist for each framework.

**Comment by abraithwaite** [comment]
I was just going through my apps and noticed that owncloud was the only one which wasn't being codesigned.

What's the status of signing the owncloud app for OSX?  According to the blog linked above, it should have been fixed in recent qt releases (if that's still the issue).

**Comment by guruz** [comment]
FYI @danimo

**Comment by danimo** [comment]
That's not intentional, and it seems that this has slipped during testing. We'll make sure that 1.8.1 is signed.

**Comment by danimo** [comment]
https://github.com/owncloud/client/issues/3114

**Comment by abraithwaite** [comment]
Cool thanks! :+1: 

I saw [this](https://github.com/owncloud/client/blob/master/admin/osx/sign_app.sh) was added a few months ago and double checked the site to make sure I wasn't going crazy.

:beers:

**Comment by danimo** [comment]
@abraithwaite Executed in our build environment, one of those commands underneath the "just for debug" should return with an error status, halting the build, but somehow that does not happen.
