### ISSUE TITLE
owncloud client often forgets password 

### ISSUE THREAD

**Issue by jochenwezel** [owncloud/client#1598]
a few users reported that ownCloud Client always or often asks for a Password (maybe every time after reboot or other Special circumstances)

I assume that those users with Special characters run into the Problem - all other users won't do. Example for special characters might be a '#' or German Umlauts - but needs to be proven!

Has somebody else experienced such Problems?

**Comment by kollix** [comment]
I have the same issue here with owncloud-client 1.8.4 on openSuse 13.2 (server is 7.0.4 on openSuse 12.1).
I get the "password" dialog whenever my user logs in (into a KDE session).
kwalletd is running, I also see org.kde.kwalletd in qdbusviewer, but
in kwalletmanager I see that the wallet is closed.

It seems as if OC-client can not or does not open the wallet.
