### ISSUE TITLE
Incorrect usage of XDG base directories

### ISSUE THREAD

**Issue by hefee** [owncloud/client#1601]
On linux the std location for the configfile is in ~/.local/share (i.e. XDG_DATA_HOME) and not ~/.config/ (i.e. XDG_CONFIG_HOME). This is according to [basedir-spec](http://standards.freedesktop.org/basedir-spec/basedir-spec-latest.html) wrong.

See also [debian bug report #741954 "Incorrect usage of XDG base directories"](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=741954)

**Comment by ogoffart** [comment]
Superseded by #3017

**Comment by hefee** [comment]
@ogoffart: This issue hasn't to do anything with #3017. 

3017 is about packaing stuff and the files that are shipped outside the user folder.

This one is about the configfiles that are created for the user aka owncloud.cfg etc.

**Comment by hodyroff** [comment]
@crrodriguez please advise

**Comment by crrodriguez** [comment]
@hodyroff not a packaging issue.. files in stored there are never packaged. distributions buildsystems will reject them if they were anyway.. this is application specific, so it is a client bug.

**Comment by hodyroff** [comment]
@guruz is this something we can/will fix in the client or are we running into troubles with updates then?

**Comment by guruz** [comment]
Not worth to change, that's why we have it P4. Feel free to close if this does/did not come up again.

**Comment by ogoffart** [comment]
Part of https://github.com/owncloud/client/issues/2245
