### ISSUE TITLE
ownCloud Client ignores files with mtime = 0

### ISSUE THREAD

**Issue by Aentfs** [owncloud/client#1603]
### Expected behaviour
ownCloud Client should should sync files with mtime = 0 as it syncs files with mtime = 1.

### Actual behaviour
ownCloud Client ignores files, with mtime = 0, but synces files with mtime = 1. 
This happend, as i wanted to sync a file, and for some reason the mtime was not copyed over with the file.

### Steps to reproduce
1. Create a file outside of owncloud
2. Use ```touch -t 19700101010000.00 file```
3. Copy or move file to the sync dir
4. ownCloud Client ignores file
5. Now use ```touch -t 19700101010000.01 file``` on file in Sync dir
6. ownCloud Client syncs file

### Server configuration
Operating system: [will be provided if necessary]

Web server: [will be provided if necessary]

Database: [will be provided if necessary]

PHP version: [will be provided if necessary]

ownCloud version: ```ownCloud 6.0.2 (stable)``` 

Storage backend: [will be provided if necessary]

### Client configuration
Client version: 
* ```Version 1.5.3 (Git revision c8a8eb; OCsync 0.19.5; Qt 4.8.5)```
* ```qtkeychain: 0.3-1```
* ```qtwebkit: 2.3.3-1```
* ```neon: 0.30.0-1```

Operating system: ```Archlinux x86_64 with KDE 4.12.3``` 
```Linux 3.13.6-1-ARCH #1 SMP PREEMPT Fri Mar 7 22:47:48 CET 2014 x86_64 GNU/Linux```

OS language: ```de_DE.UTF-8``` (generated locals: ```de_DE.UTF-8``` ```en_US.UTF-8```)

Installation path of client: ```$ whereis owncloud
owncloud: /usr/bin/owncloud [binary] /usr/share/owncloud [folder with l10n inside]```

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`

https://gist.github.com/Aentfs/b9fd9a07c0d75ea5b181

2. Web server error log: [will be provided if necessary]

3. ownCloud log (data/owncloud.log): [will be provided if necessary]

**Comment by stefaanderoeck** [comment]
I have the same issue. The zero mtime files (they're pictures) are also on an ext4 filesystem, and originate from my android phone, probably transferred through mtp to Windows and then through either smb or scp to this remote Linux box. 

I admit it's strange to have 0 mtime files, but apparently it happens. 
I was expecting to be able to delete my source after syncing, it's a good thing I didn't. From my perspective, this is therefore quite a serious issue, as it causes data loss, even if indirectly.

**Comment by Redsandro** [comment]
I have the same issue, also with images on ext4. I believe they came in through Dropbox from my Android phone.

I reckon they should be synced irregardless of the mtime value. Once they are changed in a picture editor, the mtime will be set (and thus increased from 0).

**Comment by mcastroSG** [comment]
Hi hi:

**Steps to executed**

1. Log out ownCloud Client.
2. Create a new file to test at ownCloud folder. 
3. Use `touch -t 197001010000.00 file`.
4. Log in ownCloud Client

**Results**

It works on IOS Desktop Client. The file is sync with server without any problem. 

Client Version : Version 2.2.0-nightly20160419 (build 3282)
Client OS: IOS El Capitan  10.11.4
Server Version: 9.0.1
Server OS: Ubuntu

So, @Aentfs  coud you please check Linux Solution?

[https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/owncloud-client](url)

**Comment by mcastroSG** [comment]
Hi hi:

**Steps executed**

1. Pause sync at ownCloud Client.
2. Create a new file to test at ownCloud folder.
3. Use touch -t 197001010000.00 file.
4. Enable sync at ownCloud Client.

**Results**

It works on Ubuntu Desktop Client. It works.

Client Version : Version 2.2.0nightly2016421 (build 1557)
Client OS: Linux Ubuntu 14.04 LTS
Server Version: 9.0.1
Server OS: Ubuntu
