### ISSUE TITLE
Update on Debian doesn't update libqtkeychain0

### ISSUE THREAD

**Issue by RealRancor** [owncloud/client#1605]
Hi,

after pushing the libqtkeychain0 from version 0.20140128 to 0.3 the libqtkeychain0 package is not updated to 0.3. It seems Debian/Ubuntu sees version 0.20140128 as a higher version and a manual "downgrade" to 0.3 is needed.

**Comment by jnweiger** [comment]
we have libqtkeychain0 = 0.4 meanwhile, the above suggestion does not work.
Debian does not allow a logical AND that is needed here. Negations and groups are also not supported.
Wontfix. sorry.

**Comment by RealRancor** [comment]
@jnweiger 

What about just adding a conflict to libqtkeychain0 0.20140128?

I think that was never an "official" version number and only provided by the OBS repository:

https://packages.debian.org/search?keywords=libqtkeychain0

**Comment by jnweiger** [comment]
Good idea. Not sure if that helps the solver to look again for another version -- but better than nothing.

**Comment by jnweiger** [comment]
I see libqtkeychain0 0.20140128 only in private playgrounds  on obs. The case is moot.
Adding Conflicts as suggested and closing.

**Comment by RealRancor** [comment]
Hi,

yes, the 0.20140128 was only available in the public OBS repositories one year ago. There are probably not many systems out there which are still having this installed so the conflicts is probably more than enough.

**Comment by ArcTanH** [comment]
I can't remember where I got v 0.20140128 from, but I had this installed on Linux Mint (based on Ubuntu 14.04LTS).

Marking this package as conflict leads to the confusing situation where apt tells me 

```bash
Die folgenden Pakete haben unerfüllte Abhängigkeiten:
 owncloud-client : Kollidiert mit: libqtkeychain0 (= 0.20140128) aber 0.20140128 soll installiert werden
```

which translates as

```
The following packages have unmet dependencies:
 owncloud-client : Collides with libqtkeychain0 (= 0.20140128) but 0.20140128 is requested ''to be installed''
```

Manual install of libqtkeychain0=0.4 solved this, though.

**Comment by RealRancor** [comment]
Hi,

> Manual install of libqtkeychain0=0.4 solved this, though.

unfortunately thats the only possible solution to fix such broken installations.

**Comment by jnweiger** [comment]
Maybe this help to make the solver prefer 0.4  over 0.20140128 ?

    Replaces: libqtkeychain0 (= 0.20140128)
    Breaks:   libqtkeychain0 (= 0.20140128)
