### ISSUE TITLE
CPack Error: Problem running NSIS command

### ISSUE THREAD

**Issue by nedimhx** [owncloud/client#1622]
Hello, last time I was building mirall was about 2 months, and now I want new version, Building has complted at 100% but after building, when compiler Run CPack packaging tool I get this:

[100%] Built target owncloudcmd
Run CPack packaging tool...
CPack: Create package using NSIS
CPack: Install projects
CPack: - Run preinstall target for: mirall
CPack: - Install project: mirall
CPack: Create package
CPack Error: Problem running NSIS command: "/usr/bin/makensis" "/owncloud/mirall             -build/_CPack_Packages/unused/NSIS/project.nsi"
Please check /owncloud/mirall-build/_CPack_Packages/unused/NSIS/NSISOutput.log f             or errors
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: ownCloud
make: **\* [package] Error 1

on log file I get this
File: "/usr/i686-w64-mingw32/sys-root/mingw/share\qt5\translations\qt_??.qm" -> no files fou$
Usage: File [/nonfatal] [/a]([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "/owncloud/mirall-build/_CPack_Packages/unused/NSIS/project.nsi" on line 373$

**Comment by FrancisBou** [comment]
Did you have any success with this?

**Comment by lmartinez073** [comment]
Hi

Could some one post step by step to compile this, what to download and how to download it please

I am using this https://github.com/owncloud/administration/tree/build-1.7.1/build-clients
