### ISSUE TITLE
Unneeded UI error when file renamed between update and propagate step

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#1625]
I copied some files into my sync folder and renamed one of them X->Y immediately after. The client reported an error (file X does not exist). After the subsequent sync run it recovered correctly and uploaded file Y. 

I guess that the file was renamed after the client created a list of file for update but before the propagate step. The time windows may be sufficiently large as my sync folder is getting larger (~10K files).

I am not sure if this condition should result in an error so much visible to the user (including the status icon turning red). After all, it is probably something pretty "normal" in this update/propagate model.

**Comment by guruz** [comment]
@ckamm Fixable by making this error soft and re-scheduling a sync?
Just need to make sure not to get into an endless loop if somehow the file can't ever be read..

**Comment by ckamm** [comment]
@guruz Sounds good. If a file we want to propagate doesn't even exist, that should be a soft error.

**Comment by ckamm** [comment]
@moscicki @lmaestro This problem was already fixed for 1.8 by @ogoffart in 3253cc38b219b5aa39c03e8793de8426d97b426d as a response to #1981. Feel free to reopen this issue if you can still reproduce it.
