### ISSUE TITLE
Resume button when synchronization fails

### ISSUE THREAD

**Issue by purigarcia** [owncloud/client#1627]
In Setting/Account, when the synchronization has failed, there is a pause button to click on, then a "resume" button is shown.
Would it be more clear if it was a "resume" button in the first place?

**Comment by Dianafg76** [comment]
It is working Ok, when the sync is in "Paused" state, the button is in "Resume" to begin with
Desktop v ownCloud-2.1.1.3037-nightly20160118.pkg 
Server v 8.2.2
