### ISSUE TITLE
Pause sync: Don't show confusing dialog and red errored UI-state

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#1649]
When the ownCloud client is syncing and I then press the »Pause« button I expect the sync to just be paused.

Instead I am confronted with this:
![owncloud-pause-terminate-sync](https://cloud.githubusercontent.com/assets/925062/2635292/95b9d4a0-be83-11e3-823c-077602649d20.png)

Do I want to »terminate« it? I have no clue. I just wanted to pause it. ;)

After I click »Yes«, it looks completely broken, gives me a red error and says something about »sync aborted by user« (too technical, also »user« is the term for a drug addict).
At the same time I get a notification that »some file and 644 other files have been successfully synced. That is plain wrong because there were only about 10 or 20 files synced down by that time.

Now after I resumed, everything seemed to go fine. So, why is there:
* this popup asking if I want to »terminate«
* the red error saying »the user« aborted something
* the wrong notification

From what I experienced they could all be cut and instead there should just be the standard pause state.

cc @dragotin @danimo

**Comment by dragotin** [comment]
I think this is solved for long time.
