### ISSUE TITLE
Make a one way sync option - so local files can never be deleted 

### ISSUE THREAD

**Issue by kaplandani** [owncloud/client#1651]
This is crucial - since there are many posts about owncloud deleting files - Please add feature to totally block the client from deleting a file locally.

It is a good option for anyone who uses this as a backup solution and not more than that.

**Comment by TheGrave** [comment]
There is another good reason to implement one-way sync which scares the shit out of me: imagine somebody hacks your server and purges the files. No matter on how many clients you have them synced if they are deleted transparently it would be a disaster. So my suggestion is:

1) Non-existing files to be downloaded transparently on the owncloud client machine (as they are now).
2) Modified files to be updated transparently (as they are now). The versions app should help you restore an older version of something is screwed.
3) File deletion on client machine to be confirmed. Not by default but the user should have a checkbox in the config GUI to enable this option. Implementation can (soft of) follow Microsoft's multi-stage prompts on file deletion - first it asks you whether you want to delete the main folder, then sub-folders, then individual files. Without this being a configurable prompt it won't work for everybody - a lot of people are scripting data migrations and they need silent acceptance of all changes on clients.

**Comment by wrapper** [comment]
+1 to this issue!

We are hosting our owncloud data folder in an encrypted container. Whenever the server is rebooted a passphrase must be entered to decrypt the data. OwnCloud detects this as the data being deleted and deletes all local data. Has happened twice so far!

If anyone has a workaround please let me know

**Comment by rfaelens** [comment]
@TheGrave: This should be covered by off-site backups, not by owncloud.
@wrapper: Do not start owncloud automatically. Start it manually after entering your encryption password. Or store the encryption password in your TPM chip and use a secure boot process (BIOS password, bootloader password, physical intrusion detection, etc).

**Comment by TheGrave** [comment]
Sorry but offsite backups do not make sense to me when data is already present in multiple locations. Why should I waste resources to handle another xTBs for data I already have in so many places?

**Comment by radical-equanimity** [comment]
Example: I just accidentally deleted half of my /data folder because it's a mount and the upgrade instructions have me do a copy of owncloud/ to OLDcloud/ . When I copy, the link between OLDcloud/data and my external mount is still present. So removing OLDcloud caused me to delete data

**Comment by floridop** [comment]
As much as I understand the preachers of backup, this one feature is the key thing for which ownCloud could be used as a backup system and the lack of it might be the reason why we will stop using it. Others in the business have solved it by having a one way sync. One way sync exists since rsync. I do not understand the obsession for a dangerous behavior nor who advocates it.
To the sentence: run a backup because the sync client will harm your files. Answer: I shouldn't be using such a sync client then!
