### ISSUE TITLE
Make sync client able to login to multiple owncloud instances and/or users)

### ISSUE THREAD

**Issue by jonathan-besanceney** [owncloud/client#166]
Hi all,

I've installed a personal owncloud instance and now I want to use it in my office, but the sync client doesn't allow me to make a second connection.

Multiple connection should be really usefull in this case.

Regards,

**Comment by thinking-aloud** [comment]
+1

**Comment by danimo** [comment]
@thinking-aloud That was very useful... :(

**Comment by thinking-aloud** [comment]
ups :) *laughing*.
I did not read that before, sorry

**Comment by mdonges** [comment]
+1
If you want to be uses much more, this feature seems pretty essential!

**Comment by danimo** [comment]
@mdonges I am not sure if the concept of reading is known to you (spamming certainly is), but https://github.com/owncloud/client/issues/166#issuecomment-56263757 explains that it's being working on and asks everyone to stop +1ing.
