### ISSUE TITLE
[Windows] Auto Update does not retry if closed before install

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#1691]
If ownCloud (1.5.3) gets closed after the dialog "new update is about being installed" was shown but before the actually installation routine is performed, the auto update is not retried. Instead the old "a new version is available" which forwards to owncloud.org/sync-clients/ is displayed. In my case I restarted my machine while the dialog was displayed, same happens if UAC (Win7) is denied (in this case ownCloud terminates itself).

Is it on purpose that auto update is not retried?

**Comment by danimo** [comment]
@LukeOwncloud It looks like it is. Closing.
