### ISSUE TITLE
Could not resolve hostname for IDN

### ISSUE THREAD

**Issue by ogasser** [owncloud/client#1693]
When connecting to a host with an internationalized domain (i.e. xn--... notation) the Sync client can not resolve the host name and refuses to start the syncing process.

See also #1692.

**Comment by guruz** [comment]
@blitz We have a nightly build of 1.8.0 which is using a different network stack. Do you want to try it? http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.4644-nightly20150126-setup.exe
It should work alright, but please be sure to have backups..

@ogasser Please switch to Qt 5.4 and latest OpenSSL and retry.. the problem might be ```libneon```, not Qt. The client 1.8.0 builds can work completely without neon if Qt 5.4 is used.

**Comment by danimo** [comment]
Please try http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.4651-nightly20150128-setup.exe

**Comment by lmaestro** [comment]
It is working fine in the latest version.
