### ISSUE TITLE
Unclear copyright in cmake dir

### ISSUE THREAD

**Issue by hefee** [owncloud/client#1699]
In the cmake/modules dir are now two different Coyright files (Copyright.txt and COPYING-CMAKE-SCRIPTS). Now there are different files in this directory withount any copyright header, so it is unclear, which coyright they have. It would be nice if you can make this somehow clear ( a file that say, all files in this directoy are under BSD, or a header in every file):

DefineCMakeDefaults.cmake
DefineCompilerFlags.cmake
DefineInstallationPaths.cmake
DefinePlatformDefaults.cmake
FindINotify.cmake
FindPackageVersionCheck.cmake
FindPdfLatex.cmake
FindQt5Keychain.cmake
FindQtKeychain.cmake
FindSphinx.cmake
MacroCopyFile.cmake
QtVersionAbstraction.cmake
UseDoxygen.cmake
Warnings.cmake

**Comment by dragotin** [comment]
Not all (or almost none) of these file are copyright of ownCloud, as @gladiac mentioned. We need to find the correct copyright headers. 
cc @crrodriguez can you come up with a patch?

**Comment by crrodriguez** [comment]
@dragotin sure

**Comment by crrodriguez** [comment]
So, we will use BSD license for now

**Comment by ogoffart** [comment]
It seems that all file have a copyright header now. Is this issue resolved?

**Comment by hefee** [comment]
Looks better now :D But there are still files without headers and two coyright files in cmake/modules (Copyright.txt and COPYING-CMAKE-SCRIPTS)

the files with unclear license:

* cmake/modules/ECMFindModuleHelpersStub.cmake
-> ( it is only a stub, fine to have no copyright header)

* cmake/modules/FindIcoTool.cmake
-> Vincent Pinon <vpinon@kde.org> marked coyright there must be also the license listed

* cmake/modules/MacOSXBundleInfo.plist.in
-> xml data but under what license is this file? I would recommend to move this file to admin/osx than it is clear that is osx related AND the license can be specified in admin/osx directory.

* cmake/modules/NSIS.InstallOptions.ini.in
* cmake/modules/NSIS.template.in
-> Same recommend like for osx related files.

**Comment by DeepDiver1975** [comment]
As far as I double checked the cmake files - they are hold proper license headers .... closing
