### ISSUE TITLE
deleted files reappear over and over

### ISSUE THREAD

**Issue by mkopetzky** [owncloud/client#1716]
We have a shared volume, where we deleted files and directories. Not all clients are online at the same time.
In irregular intervalls earlier deleted files and directories reappear over and over. We try to delete them, but don´t get rid of them.

**Comment by bisclavrettk** [comment]
I can reproduce this problem.
I use owncloud on Linux (Raspbian) in version 8.0.2 and Windows client 1.8.0 (build 4893).
I uploaded file with Windows client and then deleted it with web client. After couple of seconds in Windows client I saw that it was "discovering" folder and uploading deleted file.

**Comment by orfeas0** [comment]
One way to stop Directories from reappearing is:
1) Enter owncloud web client.
2) Delete the directory.
3) Create a file with the same name.

That way, all clients will have the folder deleted and the file created.
4) After some time (2-3 days?), when all clients are in sync, delete the file too.

**Comment by beniroquai** [comment]
I have the same problem here! I delete a file in the web-interface, press F5 and after refresh is done, the files reappear. Following the procedure from @orfeas0 works, but I won't do it for all files! Any ideas what could cause this problem?

I'm using MAC, windows and Android (foldersync). Is this causing any problems? Lockfiles, Timestamps..anything? It really frustrates me! 

Thank you for any suggestions!

**Comment by bigsteve** [comment]
Sometimes hosting servers use different clusters which use the same file system, having crons restoring files, so you can check with hosting about these background sync or restore processes.
You also can blame Houdini.
