### ISSUE TITLE
csync tests fail when ran in parallel

### ISSUE THREAD

**Issue by hefee** [owncloud/client#1727]
This guy tries to build the package from debian. The patches made by debian are not interfering here. You can see the patches [at git of the owncloud-client]
(http://anonscm.debian.org/gitweb/?p=pkg-owncloud/owncloud-client.git;a=tree;f=debian/patches)

The problem is, that the paralell execution of the test (everytime other tests break):

    /usr/bin/ctest --force-new-ctest-process -j4
    [...]
    | touch: cannot touch '/tmp/check/c_mkdirs/with/check/foobar.txt': No such file or directory
    | 0x100 != 0
    | /tmp/buildd/owncloud-client-1.5.3+dfsg/csync/tests/std_tests/check_std_c_dir.c:43: error: Failure!
    | [  FAILED  ] check_c_isdir_on_file_setup
    | [==========] 7 test(s) run.
    | [  PASSED  ] 6 test(s).
    | [  FAILED  ] 1 test(s), listed below:
    | [  FAILED  ] check_c_isdir_on_file_setup
    
    
    | The following tests FAILED:
    |         2 - check_std_c_dir (Failed)
    |        11 - check_csync_log (Failed)
    |        13 - check_csync_statedb_load (Failed)
    |        18 - check_csync_statedb_query (Failed)

The full build log can be found here:

  http://95.85.27.130/builds/owncloud-client_1.5.3+dfsg-1_amd64.build

See also the full bugreport in [debian bts #746278](http://bugs.debian.org/746278)

**Comment by ogoffart** [comment]
Sorry, we don't support running the test in parallel.
