### ISSUE TITLE
OS X menubar icon: Polish design

### ISSUE THREAD

**Issue by tweh** [owncloud/client#1730]
### Expected behaviour
The OS X menu bar icon should become white when it is clicked as the other icons do:

![white icon](https://cloud.githubusercontent.com/assets/3011538/2835216/4cba540e-cfe6-11e3-80b7-40a745c477e5.png)  (quick illustration done with Photoshop)

### Actual behaviour
The icon becomes greenish:

![green icon](https://cloud.githubusercontent.com/assets/3011538/2835185/fb3fd66c-cfe5-11e3-94cd-7c730d941157.png)

### Steps to reproduce
1. click the icon … 

### Client configuration
Client version: 1.5.4 (build 2580)

Operating system: OS X 10.9.2 Mavericks

<sub>I can’t answer the other questions from the template or consider them as irrelevant for this “bug” … let me know if you need some more information.</sub>

**Comment by jancborchardt** [comment]
Did we solve this by now? @LukasReschke @danimo @tweh

**Comment by LukasReschke** [comment]
No.

**Comment by Dianafg76** [comment]
Any news about this? @LukasReschke @guruz @tweh

**Comment by tsparber** [comment]
Fix proposed in https://github.com/owncloud/client/pull/5227.

**Comment by dragotin** [comment]
Done.
