### ISSUE TITLE
Http to HTTPS redirection?

### ISSUE THREAD

**Issue by kylejvrsa** [owncloud/client#1735]
Hi,

I have a bunch of friends using my owncloud server so I decided to setup HTTPS on a loadbalancer in front of my owncloud server. I now have http and https working and whenever someone queries a http link in a browser they get redirected to https. However on all the existing client installs I now get and error (The server is unavailable) saying that it can't connect to the server. This is because the server was initially setup on http. Is there a way to handle the redirect in the sync client like they do in the browsers or is this a far fetched idea? Otherwise I will have to tell all the users using it currently that they have to change their connections settings. I was hoping for a seamless transition, any thoughts welcome.

Thank you,

**Comment by ckamm** [comment]
Currently when we set up new accounts, we do follow redirects. We don't do that when encountering a redirect for an already configured account yet.
