### ISSUE TITLE
Linux Mint: Desktop client on startup won't load GUI

### ISSUE THREAD

**Issue by IVXCVI** [owncloud/client#1739]
Initially the client seemed to work as expected, but after using it about twice, it seemed to revert to the following behaviour. I never really changed anything in between time. I know at least one other user is experiencing this:

https://forum.owncloud.org/viewtopic.php?f=14&t=21189

I also installed the client normally.

### Expected behaviour
Owncloud client should initialize notification icon & GUI on startup.

### Actual behaviour
The client won't initialize notification icon or GUI unless killed first and restarted manually.

### Client configuration
Client version: 1.5.3

Operating system: Linux Mint 13 (12.04)

OS language: English

Installation path of client: /usr/bin/owncloud

### Logs

1. Output of `owncloud --logwindow`: Sys Info size: 85

**Comment by enoch85** [comment]
Can confirm this on Ubuntu 14.04 desktop mint.

**Comment by ogoffart** [comment]
Can you please try again with the 1.8.2 version. Does the problem still exists?
If yes, what is the Qt version? What is the version of the desktop shell? Is owncloud running but the system tray not visible?  Is the main UI visible? 

There could be several different problem:
 - Owncloud is started before the desktop shell initialized system tray icon. This bug should be solved in recent version.
 - The system tray icon is not working with that Qt version.

**Comment by ogoffart** [comment]
Closing because 1.8 should show the gui even if there is no systemtray
