### ISSUE TITLE
Sync path/file is limited to 260 character 

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#174]
Transferred from bug genie:
http://bugs.owncloud.org/thebuggenie/owncloud/issues/oc-1470

Description:
I have some long path and files names in the share. There seams to be a limit in characters until which the client is able to sync. It looks like the GET command supports only max 260 characters. Found in the access.log of the apache2. All characters above 260 will be cut and it will result in an HTTP 404.

Server: ownCloud Version 4.0.6 with apache2 on Ubuntu 12.04 Client: ownCloud 1.0.3 on Win XP

Reproduction steps:
- create a folder tree with long file names (more than 20 character for a folder) - create a long file name - the filename in the complete folder tree will be cut after 260 characters

The GET command will cut the file name after 260 characters. Therefore it will result in an HTTP 404 GET http://IPAdressOwnCloud/ownCloud/files/webdav.php/VeryVeryVeryVeryVeryLongPathToAFileInTheShare/VeryVeryVeryVeryVeryLongPathToAFileInTheShare/VeryVeryVeryVeryVeryLongPathToAFileInTheShare/VeryVeryVeryVeryVeryLongPathToAFileInTheShare/ThisIsALongFileNameInTheLongPath.txt

GET http://IPAdressOwnCloud/ownCloud/files/webdav.php/VeryVeryVeryVeryVeryLongPathToAFileInTheShare/VeryVeryVeryVeryVeryLongPathToAFileInTheShare/VeryVeryVeryVeryVeryLongPathToAFileInTheShare/VeryVeryVeryVeryVeryLongPathToAFileInTheShare/ThisIsALongFileNameInTheL <- cut after 260 character. The client is not be able to sync this file. HTTP 404 in access.log of the apache2 webserver.

**Comment by hoho508** [comment]
erm , it path is too long .. it will delete all our data if we try to rename it
