### ISSUE TITLE
Sync only the file change, not entire file [$1,755]

### ISSUE THREAD

**Issue by wesleyhuang** [owncloud/client#179]
In Dropbox, there notes that only the file changes are sync-ed, not the entire file. https://www.dropbox.com/help/8/en.  It is great if ownCloud can do the same.  Especially for large files, sync-ing the entire files make a lot of bandwidth and time unnessararily wasted.

In my testing with latest 4.5.4 and sync client in Ubuntu 12.04, I prepared a 1GB text file, append a few characters to the end, and monitor the traffic and the file in the server, I see the entire 1GB file is transffered to the server and the server is actually creating a new file. 

A reply from the forum indicates that librsync has this feature http://librsync.sourceforge.net/, maybe the csync can be switched to the libsync.

**Comment by setovi** [comment]
Is there an estimated date for this feature? Issue was opened two years ago... TIA.

**Comment by LukasReschke** [comment]
Locking for contributors only because the notifications of all those "+1" are going to disturb me too much.

If you want to implement this feature please create a new issue or even better a Pull Request where we can discuss this. I think this issue left enough hints and more "+1" are not going to change anything.

**Comment by enoch85** [comment]
Anyone working on this?

**Comment by jospoortvliet** [comment]
@gadLinux wants to work on it but needs input from the client developers on what direction to take with this.

**Comment by dragotin** [comment]
I added some brainstorming: https://github.com/owncloud/core/issues/16162#issuecomment-104616147

Note that probably the big thing is in the ownCloud server component.

**Comment by enoch85** [comment]
$1755 folks! Where's the like button on that? :)

**Comment by PVince81** [comment]
Ref, PRs in progress:
- server-side: https://github.com/owncloud/core/pull/29404
- client-side: https://github.com/owncloud/client/pull/6131

**Comment by PVince81** [comment]
Does anyone has an idea what file types delta sync will actually make sense ?

@ahmedammar does delta sync / zsync also detect shifts in a file ? For example if I take a wav file (no compression) and delete a chunk of audio in the middle, will it still detect this or will it resync the whole file ?

**Comment by ahmedammar** [comment]
Technically zsync could detect moves, but my code doesn’t support that, all bytes moved will be resent, this was to make it easier to get something working quickly. I mentioned this as a future work area.

**Comment by DeepDiver1975** [comment]
> Technically zsync could detect moves, but my code doesn’t support that, all bytes moved will be resent, this was to make it easier to get something working quickly. I mentioned this as a future work area.

in which area are the adoptions neccessary to make this work? I'm trying to find out the impact - if bigger refactorings are necessary I question the current in depth review ...

**Comment by PVince81** [comment]
does the current impl at least help if appending stuff at the end of files ? In this case I expect that since the beginning's offset did not change it would only sync the appended block.

**Comment by PVince81** [comment]
did anyone here already test the feature ? if you did, please report where you saw improvements (file types, use case, etc)

**Comment by ahmedammar** [comment]
Appending will only send appended bytes. Regarding where the work needs to be done: 

1) zsync - code wasn’t designed with upload path in mind, I implemented that and use the path of least resistance, meaning dropping *moved* block support.
2) oC - again to support moved blocks we’d need a more complex upload path where moved chunks are processed somehow, this can be as simple as sending a file with moved block to:from and modifying assembly code to handle appropriately.

I recommend we don’t try to do this now but after current *simple* approach is well tested.

**Comment by ahmedammar** [comment]
Just wanted to clarify something, the above only applies to the *uploader*, the downloader will not redownload *moved* chunks.

**Comment by ckamm** [comment]
The feature is stabilizing in the `delta-sync` branch and test builds will become available around the time 2.5.0 is released. If things go smoothly it'll be in 2.6.0.

**Comment by KevinLeigh** [comment]
Is this issue currently being resolved? Would like to start resolving this issue but do not want to if someone else is.

**Comment by ahmedammar** [comment]
Yeah would be nice if this gets closed so I can claim the bounty?

**Comment by guruz** [comment]
@ahmedammar It will be in client 2.6.0
On Friday we released 2.5.0 beta1. So it's coming :)
I don't know how the bounty thing works, but i'll try to get that info.

**Comment by DeepDiver1975** [comment]
@guru was the PR finally merged? Yes? Close Ticket and we Trigger payment on Bountysource

**Comment by ahmedammar** [comment]
Thanks! Have submitted the bounty claim too ...

**Comment by curtiszimmerman** [comment]
@ahmedammar I don't use Owncloud anymore, but I was one of the contributors to the Bountysource bounty, and I just wanted to thank you for all this work. It was very interesting (and impressive) to read your status updates and commits. I hope you buy at least one beer from the bounty (or a nice dinner)!

**Comment by hodyroff** [comment]
Thanks @ahmedammar really appreciated your contribution and looking forward to your continued participation - as time fits. Delta sync will for sure help to bring ownCloud into new places and motivate people to contribute and use it! Privacy and security and a full concentration on file sync and share are so important in todays world. Again Thank You!

**Comment by trampi** [comment]
I know that one should not post off-topic comments in issues. However, I want to thank @ahmedammar and all other contributors in this issue. This is a really nice and long awaited feature. Well done, everyone!

**Comment by LoZio** [comment]
I also want to thank you @ahmedammar for you work. My first post above is from 5 years ago and I'll be happy to go back to OC if this works!

**Comment by warnerbryce** [comment]
@LoZio it’s gonna be merge to Nextcloud too.

**Comment by ahmedammar** [comment]
Hi all, thanks for all the kind words, much appreciated, it was a fun project and I had fun doing it, hope it stands the test of time. Would like to extend the thanks to all the oC devs who helped throughout the process and especially @ckamm who has so aptly continued the development where I left off, very nice! Thanks again all!

**Comment by guruz** [comment]
This feature will be in the upcoming 2.6 alpha release.
Meanwhile you can try it inside the daily builds 2.6.x https://download.owncloud.com/desktop/daily/

**Comment by bolandross** [comment]
So, let's say I wanted to experiment with this new feature. I just downloaded the 2.6.0alpha1 Desktop Client and enabled delta synchronisation. Unfortunately, without noticing any effect. So my question is: Which ownCloud server version is necessary for this to work as intended?

Thanks in advance and keep up the good work.

**Comment by michaelstingl** [comment]
@bolandross The server part is only in the master branch of the ownCloud server. I hasn't been released in a production version yet.

**Comment by chrisgraham** [comment]
Somebody needs to update the FAQ: https://owncloud.org/faq/#partialsyncing
