### ISSUE TITLE
Sync Status Icons in File Browser

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#1818]
Basic Concept: 
A small overlay icon that lies on top of files and folders inside the desktop client finder, explorer and equivalent app for Linux – something akin to the Box or Dropbox icons.

If the system is offline, there are no overlay icons present. BUT if a file has unsynced changes, the circular (static) icon remains as long as the system is offline indicating it is waiting to sync. Then it gets a circular icon spinning once it starts syncing when the system is online.

The icons for Folders are set like this:
-   Green Check – All files within the folder (all the way down the tree) are synced with the server, and there are no problems to report
-   Circular Icon – Some or all files and folders in the directory are waiting to sync or are actively syncing. Note this icon does not spin.
-   Yellow warning triangle – there is an error in syncing somewhere in the directory such as a path longer than 255 characters, or a bad character in a name, or a file firewall problem
-   Red error Icon – there is a fatal problem in the sync process that can’t be resolved, or no file can sync within the folder (it is possible that this folder is at the 255 character path length limit, so no file inside this folder can sync – thus this would be red). If there is a red folder icon deep in a tree all contining folders represent that red state all the way to the root folder.

All errors bubble up, so an error deep in a folder structure bubbles up to the top folder as per the rules above.

The icons for Files are set like this:
-   Green Check – This file has been synced with the server.
-   Blue circular icon – static – the file is currently waiting to sync, and they system is online
-   Blue spinning icon – moving – this file us currently syncing
-   Red error – the file is not syncing for whatever reason, perhaps a file firewall error, or a long path of bad character in the name

There are 4 related items for UX  / integration with the OS:
- Sync status icons (this)
- Shared icons (https://github.com/owncloud/mirall/issues/1743)
- Context menus - aka sharing from desktop (https://github.com/owncloud/mirall/issues/1444)
- Folder icons (https://github.com/owncloud/mirall/issues/296)
- ownCloud folder icon (https://github.com/owncloud/mirall/issues/455)

@jancborchardt

**Comment by VincentvgNn** [comment]
@dragotin @danimo 
I noticed that in the latest Google Drive release the number of overlay icons has been reduced to 3: GoogleDriveBlacklisted, GoogleDriveSynced and GoogleDriveSyncing.
And the big surprise is that they are now using 2 spaces in front of the names in the same way as ownCloud does!
They copied this method from ownCloud or they detect what to put in front in order to get their icons at the first positions.

**Comment by PurpleGab** [comment]
Placing spaces and " in front of what you want to be active is indeed dirty.

If MS is not able to solve the problem, all others should at least refain from flooding the registry.
The icons I really need are from tortoise, all the others are nice to have, but I don't care.

So now that I know where to edit the list, why does everybody try smuggle their "most valuable" 10 icons in every time I reboot or whatever.

This is more than ugly.

Gab
