### ISSUE TITLE
[OS X] [1.6rc3] Logging out should change icons in "Account" tab to grey

### ISSUE THREAD

**Issue by guruz** [owncloud/client#1821]
(Seen in 1.6 rc3)

Right now the icons will only become grey when I clock "Login".

**Comment by cdamken** [comment]
Any news?

**Comment by dragotin** [comment]
This problem is gone in the 1.8.0 client.  In preparation of the multi account feature, we do now have a static icon in the top bar, as there wont be *one* account any more in the future, but many.

**Comment by lmaestro** [comment]
Now it shows like that:
![screen shot 2015-02-09 at 2 06 54 pm](https://cloud.githubusercontent.com/assets/4689430/6106800/1a2d4252-b065-11e4-87b8-193b2f39a366.png)
