### ISSUE TITLE
Implement bandwidth limiting in the Qt propagator

### ISSUE THREAD

**Issue by guruz** [owncloud/client#1849]
* [x] Upload relative percentage
* [x] Upload absolute KB/sec
* [x] Download relative percentage
* [x] Download absolute KB/sec
* [x] Bring Qt patches into OBS
* [x] Activateable using environment variable
* [x] Activate (```usingLegacyPropagator()```) based on Qt version (OS, OBS-compiled etc..)

When this is done and working, we can eventually kill the old propagator code

**Comment by guruz** [comment]
@lmaestro FYI This can be tested when https://github.com/owncloud/client/issues/2699 is done..

**Comment by lmaestro** [comment]
It works fine in version 1.8.0-nightly20150129
