### ISSUE TITLE
Activity: order of columns

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#1851]
The »Action« column should be between the Time and File columns. So that you read:
* 17:41  deleted file.txt
* 16:34 uploaded bla.png

**Comment by ogoffart** [comment]
@jancborchardt but in case of error, the action column contains the error and can be quite big, forcing the action column to be very wide.

**Comment by jancborchardt** [comment]
Shouldn’t in case of error the action column still contain the action where the error occured? Or the text »error«? Having the whole error message in there seems inconsistent.

**Comment by lmaestro** [comment]
@ogoffart  any news?

**Comment by dragotin** [comment]
outdated
