### ISSUE TITLE
Linux client not able to open KDE wallet

### ISSUE THREAD

**Issue by leoarnold** [owncloud/client#1852]
At login time, the owncloud client would always ask me for my password, so I checked my KDE wallet "kdewallet" and found out:
- if the wallet is already opened, the owncloud client can save the password to it
- while the wallet is open, the owncloud client can retrieve the password from it, i.e. I can quit the client and start again without being asked for my password
- if the wallet is closed, the owncloud client fails to open the wallet (despite the fact that I "always allow"ed the client to access the wallet) and will again ask me for my password.
- On some laptops, the problem does not occur - most likely due to the use of NetworkManager, which opens the wallet first to retrieve the wifi password.

Tested on:
- OS: Kubuntu Desktop 12.04 to 14.04
- OC Linux clients 1.5.3 to 1.6.0

In the above text "password" refers to my owncloud user password. The issue might be related to #1501.

**Comment by danimo** [comment]
I think this is a race condition similar to https://github.com/owncloud/client/issues/1902. Let's track the issue there.
