### ISSUE TITLE
[OS X] Still having issues with self-signed cert on Owncloud sync client 1.6

### ISSUE THREAD

**Issue by polaris20** [owncloud/client#1864]
On the 1.6 Sync client, only on OS X (10.9.3), most recent version of Owncloud, PHP, MySQL, etc, with a self-signed certificate on a DDNS based server, I first get:

Could not connect securely. Do you want to connect unencrypted instead? (not recommended). 

Then, I get Failed to connect to Owncloud. 

And it doesn't proceed any further. Linux and Windows clients both work fine on the same server. 

On a separate but nearly identically configured server, the OS X client works fine. The only difference is that the second server has a third party signed SSL certificate. 

Thoughts?

**Comment by phrend** [comment]
I just installed Owncloud 8 on my shared hosting with a self signed cert. I can log in from the web just fine (https is forced via owncloud settings, and via .htaccess), but the OS X client (1.7.1 build 1655) is giving me these errors. (I did try removing my .htaccess to see if the behavior would be any different, but it was not.)

**Comment by guruz** [comment]
@phrend We use a different network library in 1.8.0beta2 (or the rc1 coming out today). Do you want to retry?

**Comment by phrend** [comment]
@guruz I'd be happy to try another version. I see those builds in the git repo, but do you have compiled versions available somewhere as well? I looked around, but didn't find any.

Thanks!

**Comment by RealRancor** [comment]
@phrend 
See the announcement mailing here:

http://owncloud.10557.n7.nabble.com/ownCloud-Client-1-8-0-RC1-available-td14744.html

**Comment by phrend** [comment]
@RealRancor Thanks!

I installed ownCloud-1.8.0.2122rc1.pkg and now I'm getting a different error... after entering my login creds, I get: Access forbidden by server. To verify that you have proper access, click here (link to my server) to access the service with your browser.

When I click the link, nothing happens.

When I right-click the link, and copy the link, it is a link to my server, and I am able to log in to the server with the creds that are not working from the desktop client. (cut&paste from the clipboard to avoid typos in the creds)

**Comment by guruz** [comment]
@phrend Could you create a new issue with screenshot? (And also link to the issue here..)

CC @ogoffart @danimo @ckamm @dragotin  Shib messup?

**Comment by phrend** [comment]
@guruz
I created the following issue: https://github.com/owncloud/client/issues/2957
