### ISSUE TITLE
overview 'recent changes' useless due to 'ignored' files

### ISSUE THREAD

**Issue by Ruud68** [owncloud/client#1865]
Hi,
as posted and described on forum: https://forum.owncloud.org/viewtopic.php?f=14&t=21731

issue is that list of ignored files keeps updating and actually synced files are not visible in recent changes list (owncloud desktop linux  client 1.6.0)
ignored files should be part of the activity stream but not part of the recent changes list (or there should be a setting allow to hide these ignored files from the list)

Hope this helps :)
![owncloud-ignored__](https://cloud.githubusercontent.com/assets/2733197/3229754/47e657f0-f09a-11e3-9461-468e41978e31.png)

**Comment by guruz** [comment]
@danimo Can this be closed?

**Comment by ckamm** [comment]
Hidden or ignored files are no longer shown in "Recent Changes" in 2.1.
