### ISSUE TITLE
SSL handshake failed

### ISSUE THREAD

**Issue by Luuk34** [owncloud/client#1866]
![2014-06-10 12_02_02-samples](https://cloud.githubusercontent.com/assets/7850737/3232452/42bbc570-f0b4-11e3-929a-a5cee33ce3a1.png)

see thread here:
https://forum.owncloud.org/viewtopic.php?f=26&t=21745&p=61727#p61727

When synchronizing a new account it all start fine, but before completion i get an 'SSL handshake failed'
Nothing weird found in logfiles, piece of wireshark attached.

server: linux (openSUSE x86_64 12.3) 
owncloud-server: 6.0.3
owncloud-client: Windows7; version 1.6.0 (build 3082)

how to upload a wire shark (how to attach a file?) here?

update 2014-07-12: This problem does not occur with owncloud 6.0.4.1, and client 1.6.1.3267

**Comment by guruz** [comment]
Please create a new bug if using a recent version (with OpenSSL 1.x) does not help.
