### ISSUE TITLE
linux client hangs after suspend resume

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#1880]
Sometimes it works, after suspend resume, sometimes not. Cannot yet reproduce.

Today, I failed to sync, but was still responsive on the desktop. I opened the GUI and pressed the pause button. Then 'resume'. It said resume syncing, but the icon continued to show the pause marks. In this state, the gui window became unresponsive, the process was hung in a futex call.  Only option: kill. Restart.

$ strace -p 1709
Process 1709 attached
futex(0x7fc2d2c, FUTEX_WAIT_PRIVATE, 1, NULL <unfinished ...>
+++ killed by SIGKILL +++

After that, it perfectly synced all the pending changes.

Is there a useful logging config to track this kind of problem? With just enabled logging via --logdir, I get 7MB of logfile for the startup and one file changed. This appears excessive.

**Comment by guruz** [comment]
I believe 1.8 fixes this, it uses a different network library for directory discovery.
Do you want to try a nightly build?

**Comment by guruz** [comment]
Please retry with 1.8rc1 and comment/reopen if the problem persists.
