### ISSUE TITLE
ownCloud client 1.6 on Windows 7 often says "Connection Timeout" and won't work until restarted.

### ISSUE THREAD

**Issue by frankuit** [owncloud/client#1893]
Hi Guys,

I have some users with Windows 7 on a bootcamp installation on a Macbook pro 13".
Reports are coming in since the latest release, that sometimes when the computer comes out of sleep mode, the ownCloud client cannot connect to the server.
User reports that closing the ownCloud client and starting it up again works as a workaround.

info:
server side, debian 7 wheezy, all the latest patches with apache2 and mysql.
oc 6.0.3

I've added a screenshot of the error the user is getting.
Please forgive the unsharpness as user took the pic with a phone.

![owncloudproblem](https://cloud.githubusercontent.com/assets/3750583/3354528/45a27bea-faa4-11e3-814e-36552e2690a8.png)

**Comment by enoch85** [comment]
I was also expiring this last night, syncing a 40 GB file with 1.7.1. Sorry, can't provide any stacktrace here since I removed the file to finished the sync. Reopen anyway.

**Comment by ogoffart** [comment]
That's because the server takes too much time to process.
Another case for  https://github.com/owncloud/core/issues/12097
