### ISSUE TITLE
Refactor Credential Handling

### ISSUE THREAD

**Issue by ogoffart** [owncloud/client#1897]
We have had a lot of regression in the handling of credentials. Issues with keychain, logins log off, shibboleth, interaction with the wizard, ...
We also want to support in the future multiple accounts and UI-less library for the command line client.
The code has become more complicated than it should be and some refactoring is needed.

**Comment by guruz** [comment]
Also related to https://github.com/owncloud/client/issues/43

**Comment by guruz** [comment]
@ogoffart @ckamm is this (partly?) done?

**Comment by ckamm** [comment]
Some of it is done, some if it might want to go into more specific tickets @ogoffart.
