### ISSUE TITLE
Distinguish 503 Storage not available from 503 Service unavailable

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#1923]
See https://github.com/owncloud/core/issues/9376

From the introduction of server to server sharing, it can happen that a specific mount point is not available so any operation on that folder would return "503 Storage not available".

Currently the sync client shuts down itself (gray) and stops syncing, believing that the whole server is down.

@ogoffart suggested this needs to be fixed in a later version of the sync client.

**Comment by ckamm** [comment]
I'm closing this ticket because we handle
* 503 Storage not available during discovery and
* regular 503 during connection pings

correctly now. 

A upgrade-induced 503 during discovery or up/downloads will lead to a sync failure. I'll make a new ticket to track and discuss that issue.
