### ISSUE TITLE
No 1.6.1-0  build for xUbuntu 12.04 ?

### ISSUE THREAD

**Issue by mp3tobi** [owncloud/client#1927]
Sorry, but there is no build for xUbuntu 12.04.
Can somebody build one package or fix the error that prevents building a new package?

Thank you.

**Comment by guruz** [comment]
I think this has been fixed meanwhile.
Right @dragotin @jnweiger  ?

**Comment by jnweiger** [comment]
Yes, fixed. But for 1.7.* -- not 1.6.*
