### ISSUE TITLE
Windows client notification of availalble update 

### ISSUE THREAD

**Issue by kenrob2** [owncloud/client#1942]
On resuming from a sleep state the Windows client's notification of an 
available update is a worthwhile feature, but it mustn't be anonymous.  Cautious users will (and are advised to) not click on anonymous pop-ups.  The Windows update notification from 1.54 to 1.61 is anonymous.
Title: New Update Ready
Text: A new update is about to be installed.  The updater may ask for additional privileges during the process.
![nur](https://cloud.githubusercontent.com/assets/648665/3488013/64e494a6-04be-11e4-8bd8-ea55019e9f70.png)

By contrast the "New Version Available" notification resulting from an updates check (in 1.54)
 is excellent - brimming with relevant information to confirm its legitimacy.
![nvr](https://cloud.githubusercontent.com/assets/648665/3488017/9bd2f1ec-04be-11e4-8558-82173b5c33e3.png)

Regards
Ken

**Comment by danimo** [comment]
We're now showing which application is triggering the popup.
