### ISSUE TITLE
Mac client crashes when you left it opened and unused for a long time when showing settings dialog

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#1947]
### Steps to reproduce
1. Open desktop client 
2. Leave it open and unused for a long time (1 hour)
3. Click on Settings

### Actual behavior
When you open setting window after leaving it for a long time, it looks like this:

![screen shot 2014-07-03 at 16 19 32](https://cloud.githubusercontent.com/assets/4689430/3494385/1c4df50e-05c5-11e4-85d8-6bede802e184.png)

And when you click on any tab it crashes. 

### Client configuration
Version 1.6.1 (build 359)

Operating system: Mac 10.9.3

**Comment by guruz** [comment]
Sorry @lmaestro I'll close your favorite issue until someone else reports it too.. :-)

**Comment by guruz** [comment]
@yan12125 your backtrace is from MacPreferencesWindow::event while @lmaestro 's is from toolButtonClicked
Please create a new issue, also with mentioning from which panel you are in and how many accounts you have.
I tried with my client and can't reproduce so far.
