### ISSUE TITLE
Upload updated local files first, then download updates from server

### ISSUE THREAD

**Issue by gadjou** [owncloud/client#1961]
### Expected behaviour
Upload updated local files first, then download updates from server 

### Actual behaviour
File from server are dowloaded before local files are uploaded.

### Steps to reproduce
I use owncloud has a backup solution.
Client1 uploaded a huge amount of photos.
Client2 start and creates importants files,: they won't be upload to the server (thus backedup) until the whole photos are downloaded (which can take hours)

### Server configuration
Ubuntu 14.04 / Apache 2 / Mysql / Php
ownCloud version: 1.7 beta

### Client configuration
client 1.6.1
Win 7 FR

**Comment by guruz** [comment]
Closing in favor of  https://github.com/owncloud/client/issues/1633
