### ISSUE TITLE
7.0 RC 2. Mac Client: "Requested Range Not Satisfiable" error

### ISSUE THREAD

**Issue by jameslbrown** [owncloud/client#1967]
After Upgrading server to 7.0 RC 2.

Mac Client (Version 1.6.1 build 359), Activity tab shows this error for each item:

9:53 pm   facts                                                           ownCloud       The item is not synced because of previous errors: Error downloading https://server.bordo.com.au:9100/owncloud/remote.php/webdav/facts - server replied: Requested Range Not Satisfiable          

Mac is running OS X 10.10 Yosemite (build14A283o)

**Comment by ogoffart** [comment]
Please re-open if the issue is still happenning with 1.7.1  (but i remember having fix some issues regarding ranges)
