### ISSUE TITLE
Client 1.6.1 on Windows XP sends corrupted xlt file

### ISSUE THREAD

**Issue by brozkeff** [owncloud/client#1969]
### Expected behaviour
When I create/edit an Excel (or ANY OTHER) file in a folder shared with Owncloud it always uploads the file correctly and does not upload and spread a corrupted version of such file

### Actual behaviour
Randomly (I don't know what exactly caused it) I experienced that a XLT template modified by Excel 2002 on a WinXP machine got garbled in Owncloud and was downloaded immediately by another computer login to same account (Linux Mint 13 MATE 1.8, 32bit, OC client 1.6.0) and also to a colleague (Win7, OC client 1.6.1) that has that folder shared (read-only). Instead of actual Excel template the file was a garbage unreadable both by Excel 2010 and LibreOffice. The filesize was OK. (176 128 bytes)
Deleting the file from the "master" (WinXP), waiting till OC client deleted it on server and other clients, and copying the file there again, eventually led to correct synchronization.

### Steps to reproduce
Seems random, cannot guarantee it happens always.
1. create Excel 2002 xlt file (size 176 128b), move it from Templates to OC shared directory
2. wait till it is uploaded to OC server
3. sometimes the file is transmitted as garbage

### Server configuration
Operating system: Ubuntu 14.04 server in a OpenVZ container

Web server: Apache 2.4.7-1ubuntu4

Database: MySQL 5.5.35+dfsg-1ubuntu1

PHP version: 5.5.9+dfsg-1ubuntu4

ownCloud version: 7.0RC1

Updated from an older ownCloud or fresh install: update via apt-get from 6.0.4

List of activated apps:
Activity
Deleted files
Documents
External user support
Owncloud dep.info
Pictures
Share files
Text editor
Updater
Versions
Video viewer

### Client configuration
Client version: 1.6.1 on Windows XP where I created the XLT files
1.6.0 on Linux Mint 13 32bit (connected to same account as the WinXP machine)
1.6.1 on Win7 64bit (connected to another account but had that folder with the XLT files shared readonly)

Operating system: WIndows XP Home 32bit SP3

OS language: Czech

Installation path of client:

### Logs

I had debug on and there are now hundreds of MB of logs and I don't have time now to parse it , remove all confidential info etc. If you need something tell me which strings to look for.

**Comment by ogoffart** [comment]
I'm closing this issue and we can continue the discussion on #2425

BTW, maybe 1.8 is better because we read the chunk in memory before sending them.
