### ISSUE TITLE
Client should prioritize user interaction over sync action

### ISSUE THREAD

**Issue by mpeterson** [owncloud/client#1981]
I've seen several edge cases where the client can create problems on the synchronization or inconsistency on the synch-ed folder that differs from what the user intended.

Examples are:

- You copy a new folder full of content to the ownCloud sync folder. Then rename it to something else. After that copy or create another folder with the same folder name as the original.
- Create files, delete them, move them, rename them. Do this "fast" and unexpected behavior can occur even the impossibility to do one of those actions. 
- Work on a big file. Save it. The sync process will start. Do a change on the file and save it again before the file was synch-ed and you'll notice that the file is locked for writing and so the saving will fail.

I think all this problems are related as to how the sync mechanism works and how it handles locking of files or "abortion" of synchs in progress. 

The intended behavior should be that the user interaction is prioritized over the synchronization so any changes on the folder/files that are currently synchronized cause the abortion of that sync action or some other action. 

One thing that could be interesting to do is that the client creates a 'stash' or staging folder where it copies all files pending of synchronization and then it syncs from that place. That way if there are multiple saves of the same file the client can send several versions and allow the user to have revisions of each file. I think this is how Dropbox handles the synchronization process.

Cheers
Michel

**Comment by ogoffart** [comment]
Is there still a problem?

**Comment by GMTA** [comment]
This:
> Work on a big file. Save it. The sync process will start. Do a change on the file and save it again before the file was synch-ed and you'll notice that the file is locked for writing and so the saving will fail.
Is still a big problem! Easily reproducable with large docx files.

**Comment by mpeterson** [comment]
Yes, it still is a problem


On Thu, Jan 8, 2015, at 11:44, Jelle Raaijmakers wrote:
> This:


>> Work on a big file. Save it. The sync process will start. Do a
>> change on the file and save it again before the file was synch-ed
>> and you'll notice that the file is locked for writing and so the
>> saving will fail.
>>
Is still a big problem! Easily reproducable with large docx files.

> — Reply to this email directly or view it on GitHub[1].

>

--
Michel Peterson




Links:

  1. https://github.com/owncloud/client/issues/1981#issuecomment-69187940

**Comment by lmaestro** [comment]
In version 1.8.0-nightly 20150122(build 1912) when the folder/file is syncing you can't rename or move it, an alert message is shown in OS X and Windows.

**Comment by ogoffart** [comment]
What is the exact message that is shown?
It worked fine for me.

**Comment by GMTA** [comment]
Locking files or preventing user interaction with them in other ways while syncing would be a Bad Thing, imho.

As I see it, the client should take care of three processes:
1. Keep track of file/dir mutations locally, so we know what the user has done.
2. Keep track of which files/directories have been and should be synced.
3. Actually synchronize to remote.

Process 3 should not lock anything or prevent any user interaction. If the user changes something during sync, processes 1 and 2 should be able to cope with that and process 3 must not block the change.

**Comment by ogoffart** [comment]
We try hard not to lock the file anymore.
In owncloud 1.8, we will just open the file for a short period of time and copy the chunk in memory before uploading it.

**Comment by GMTA** [comment]
Sounds great! Do you know the commit ID for this change? I couldn't find it myself.

**Comment by lmaestro** [comment]
You can download the latest version from here http://download.owncloud.com/desktop/daily/?C=M;O=D

**Comment by mpeterson** [comment]
Lucia, IMHO I think it's not a good behavior and goes against what it
was first reported.

The idea is not to alert the person and not to refuse him to do the
action he pretended; but, instead, the client should allow him to do the
action and record what the user did to allow the client to sync
correctly (the simplest and ineffective solution could be, if the user
did an action I delete the file from the server and upload it again).
But at least the user was not refused to do what he wanted and the data
is correct.


On Thu, Jan 22, 2015, at 08:22, Lucia wrote:
> In version 1.8.0-nightly 20150122(build 1912) when the folder/file is
> syncing you can't rename or move it, an alert message is shown in OS X
> and Windows.


> — Reply to this email directly or view it on GitHub[1].

>

--
Michel Peterson




Links:

  1. https://github.com/owncloud/client/issues/1981#issuecomment-71006434

**Comment by ogoffart** [comment]
So could you please tell me what is the exact problem now in the last daily version?  ( http://download.owncloud.com/desktop/daily/ )

@GMTA the commit sha1 is 3ec19ee35553aff4845bcd69add6d6ab60d54b9f

@lmaestro Where you trying to remove/rename the root folder or just a sub folder?  Removing the root sync'ed folder is not supported.  But removing a subfolder should normaly work.

**Comment by lmaestro** [comment]
@mpeterson Do you want to test the  beta version? you can download here: https://owncloud.org/install/#testing

**Comment by GMTA** [comment]
I've just tested the latest beta version for this issue. Great news: large files are no longer being locked by the OC client!

If you save the file, wait for it to sync, and save it again while OC is uploading the file, the status icon on the file turns to a red cross. The icon in the notification area stays green. After a while, another sync takes place and the file is uploaded correctly.

I haven't tried fiddling with renaming files or directories; someone should probably check whether that is still an issue.

**Comment by mpeterson** [comment]
I've tested and it seems to be resolved. Thanks


On Sun, Feb 22, 2015, at 20:45, Jelle Raaijmakers wrote:
> I've just tested the latest beta version for this issue. Great news:
> large files are no longer being locked by the OC client!


> If you save the file, wait for it to sync, and save it again while OC
> is uploading the file, the status icon on the file turns to a red
> cross. The icon in the notification area stays green. After a while,
> another sync takes place and the file is uploaded correctly.


> I haven't tried fiddling with renaming files or directories; someone
> should probably check whether that is still an issue.


> — Reply to this email directly or view it on GitHub[1].

>

--
Michel Peterson




Links:

  1. https://github.com/owncloud/client/issues/1981#issuecomment-75472442

**Comment by guruz** [comment]
Great! :)
