### ISSUE TITLE
Csync bad parameter. 400 Bad request

### ISSUE THREAD

**Issue by theclansmen** [owncloud/client#1983]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Csync Fatal parameter error. 400 Bad request on desktop client

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system: Win 7 / Mac OS

Web server: 

Database:

PHP version:

ownCloud version: 6.0.4

Storage backend:

### Client configuration
Client version: 1.6.1.3267 on PC
1.30 on Mac OS
Operating system: Win 7 & Mac OS

OS language: English

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`

2. Web server error log: 
Warning 	core 	isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception) 

3. ownCloud log (data/owncloud.log): 
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T22:55:26+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T22:57:25+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T22:57:27+00:00"}
{"app":"OC_USER_WEBDAVAUTH","message":"Invalid Url: \"\" ","level":3,"time":"2014-07-16T22:57:36+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T23:00:06+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T23:00:12+00:00"}
{"app":"search_lucene","message":"Cross-reference streams are not supported yet. Trace:\\n#0 \/home\/theclans\/cloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf\/Parser.php(460): Zend_Pdf_Parser->_loadXRefTable('116')\n#1 \/home\/theclans\/cloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf.php(318): Zend_Pdf_Parser->__construct('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...', Object(Zend_Pdf_ElementFactory_Proxy), false)\n#2 \/home\/theclans\/cloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf.php(255): Zend_Pdf->__construct('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...', NULL)\n#3 \/home\/theclans\/cloud\/apps\/search_lucene\/document\/Pdf.php(21): Zend_Pdf::parse('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...')\n#4 \/home\/theclans\/cloud\/apps\/search_lucene\/document\/Pdf.php(69): OCA\\Search_Lucene\\Document\\Pdf->__construct('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...', false, false)\n#5 \/home\/theclans\/cloud\/apps\/search_lucene\/lib\/indexer.php(94): OCA\\Search_Lucene\\Document\\Pdf::loadPdf('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...')\n#6 \/home\/theclans\/cloud\/apps\/search_lucene\/lib\/hooks.php(79): OCA\\Search_Lucene\\Indexer::indexFile('\/Juin 2014.pdf', 'leclouddesamour...')\n#7 [internal function]: OCA\\Search_Lucene\\Hooks::doIndexFile('{\"path\":\"\\\\\/Juin...')\n#8 \/home\/theclans\/cloud\/lib\/private\/backgroundjob\/legacy\/queuedjob.php(16): call_user_func(Array, '{\"path\":\"\\\\\/Juin...')\n#9 \/home\/theclans\/cloud\/lib\/private\/backgroundjob\/job.php(34): OC\\BackgroundJob\\Legacy\\QueuedJob->run(Array)\n#10 \/home\/theclans\/cloud\/lib\/private\/backgroundjob\/queuedjob.php(27): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#11 \/home\/theclans\/cloud\/cron.php(114): OC\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#12 {main}","level":3,"time":"2014-07-16T23:34:49+00:00"}
{"app":"Encryption library","message":"Could not get migration status for leclouddesamoureux, no record found","level":3,"time":"2014-07-16T23:35:03+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T23:35:46+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T23:42:54+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-16T23:45:00+00:00"}
{"app":"core","message":"isWebDAVWorking: NO - Reason: [CURL] Error while making request: error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol (error code: 35) (Sabre_DAV_Exception)","level":2,"time":"2014-07-17T07:42:03+00:00"}
{"app":"search_lucene","message":"Cross-reference streams are not supported yet. Trace:\\n#0 \/home\/theclans\/cloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf\/Parser.php(460): Zend_Pdf_Parser->_loadXRefTable('116')\n#1 \/home\/theclans\/cloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf.php(318): Zend_Pdf_Parser->__construct('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...', Object(Zend_Pdf_ElementFactory_Proxy), false)\n#2 \/home\/theclans\/cloud\/apps\/search_lucene\/3rdparty\/Zend\/Pdf.php(255): Zend_Pdf->__construct('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...', NULL)\n#3 \/home\/theclans\/cloud\/apps\/search_lucene\/document\/Pdf.php(21): Zend_Pdf::parse('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...')\n#4 \/home\/theclans\/cloud\/apps\/search_lucene\/document\/Pdf.php(69): OCA\\Search_Lucene\\Document\\Pdf->__construct('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...', false, false)\n#5 \/home\/theclans\/cloud\/apps\/search_lucene\/lib\/indexer.php(94): OCA\\Search_Lucene\\Document\\Pdf::loadPdf('%PDF-1.5\\r%\\xE2\\xE3\\xCF\\xD3\\r...')\n#6 \/home\/theclans\/cloud\/apps\/search_lucene\/lib\/hooks.php(79): OCA\\Search_Lucene\\Indexer::indexFile('\/Juin 2014.pdf', 'leclouddesamour...')\n#7 [internal function]: OCA\\Search_Lucene\\Hooks::doIndexFile('{\"path\":\"\\\\\/Juin...')\n#8 \/home\/theclans\/cloud\/lib\/private\/backgroundjob\/legacy\/queuedjob.php(16): call_user_func(Array, '{\"path\":\"\\\\\/Juin...')\n#9 \/home\/theclans\/cloud\/lib\/private\/backgroundjob\/job.php(34): OC\\BackgroundJob\\Legacy\\QueuedJob->run(Array)\n#10 \/home\/theclans\/cloud\/lib\/private\/backgroundjob\/queuedjob.php(27): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#11 \/home\/theclans\/cloud\/cron.php(114): OC\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#12 {main}","level":3,"time":"2014-07-17T07:42:05+00:00"}

Can't get the client on PC or MAC to work. i always got Csync error. 
File upload works perfectly with web browser and android app.

it was working very well a few weeks back.

**Comment by guruz** [comment]
@abelass The QNAM-patch is now merged into master (which will become 1.8). Do you want to try a nightly build? http://download.owncloud.com/desktop/daily/ (warning, this is not fully QAed and might be dangerous to use..)

**Comment by abelass** [comment]
@guruz , thanks. I don't have a real test environnement for this, so I d'rather wait a stable version

**Comment by guruz** [comment]
OK, then we have to see if 1.8 fixes the issue..

Did anyone in the meanwhile contact OVH?

**Comment by abelass** [comment]
Im did, but they need mire info about the technical server requirements to make this client work smoothly. Can you think of something usefulle for them?

**Comment by xluthi** [comment]
Hi,

I've also contacted OVH via the technical support.  They've asked: 

The technical prerequisite for this application
The exact URL causing the "HTTP 400 Bad Request" error.

I did not reply yet as I do not have the exact answer to these questions...

**Comment by xluthi** [comment]
Hi,

I've updated my server and my Linux laptop with nightly builds of the server and client.

  * My server is: 8.0 RC 2 (daily) Build:2015-02-06T04:18:14+00:00 0916d2ed6b6748f235b384e78df3e4dccbbdaefa 
  * My client is v 1.8.0, Built from Git revision eedb5d on Feb 7 2015.

I do not have the  `HTTP 400 Bad request` error anymore :+1: 

1.8 seems to solve this bug! Thanks a lot!

**Comment by RealRancor** [comment]
@xluthi
> 1.8 seems to solve this bug! Thanks a lot!

Have you upgraded both, the client and the server to the newer versions? Could be interesting if the client or the server update has fixed this problem for you.

**Comment by ochurlaud** [comment]
@RealRancor 

How safe is it to upgrade to 1.8?
I mean, how far is it from release?

**Comment by RealRancor** [comment]
@ochurlaud 
For this you're asking the wrong guy. (See that i don't have either an "Collaborator" nor an "Owner" sign at the right side of my user name.

**Comment by ochurlaud** [comment]
ok sry, Since I see your login often on the issues... =D 

I wait that someone else answers!

**Comment by xluthi** [comment]
@RealRancor : 

I've first upgraded my server, but the error was still there. After upgrading the client too, the error disappeared and the sync is now working correctly.

**Comment by guruz** [comment]
@xluthi Good to hear :)

btw, 1.8rc1 is out.
