### ISSUE TITLE
owncloud client on KDE SC 4.13 asks for password instead of waiting for KWallet

### ISSUE THREAD

**Issue by martin21** [owncloud/client#1991]
Actual results:
Owncloud Client 1.61 asks for password instead of waiting for KWallet to become available at login. If I then wait for another application to require master password for KWalletManager (usually Akonadi / KDEPIM), enter it and then press "Cancel" on Owncloud Client password prompt window, I get a KWalletManager password prompt window as well. If I don´t wait and press cancel, Owncloud Client fails authentification.

Expected results:
Owncloud Client waits for KWallet to become available and then uses it to get its password.

Reproducable:
Always.

Different findings:
On my Workstation at work Owncloud Client waits to KWallet. Might be timing differences. Laptop where this issue occurs is ThinkPadT520 mit Dual SSD BTRFS RAID 1. Laptop is older Intel i3 and Dual harddisk Ext4 RAID. It takes longer to bring up KDE session.

I submitted with core as: https://github.com/owncloud/client/issues does not seem to exist.

I found it quite difficult to find bug reporting page. owncloud.org doesn´t seem to mention it at a easily findable place.

**Comment by martin21** [comment]
Seems to work meanwhile. Thanks.

**Comment by daeavelwyn** [comment]
In the case problem still persists, some workaround are presented here :https://github.com/owncloud/client/issues/1902
