### ISSUE TITLE
Error 1060: XML parse error at line 2: Undeclared namespace prefix

### ISSUE THREAD

**Issue by jwm-evans** [owncloud/client#2003]
I am getting the above error when trying to sync files using the Linux client. 
* Client version 1.5.0
* Server version 7.0.0

There is nothing in my php log at all. In my apache error log for Owncloud there is nothing as well, but in the general apache log for Owncloud the following lines keep appearing:
```
<my IP address> - <my user name> [25/Jul/2014:08:38:52 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 394 "-" "Mozilla/5.0 (Linux) mirall/1.5.0"
<my IP address> - - [25/Jul/2014:08:38:55 +0200] "PROPFIND /remote.php/webdav HTTP/1.1" 207 2874 "-" "Mozilla/5.0 (Linux) csyncoC/0.91.4 neon/0.30.0"
```

There is a Windows PC that is also getting the same error. They are using version 1.6.1.3267 of the Windows client

**Comment by guruz** [comment]
Do you guys still get this with the latest nightly build? http://download.owncloud.com/desktop/daily/
(Beware, it didn't go through full QA..)

**Comment by guruz** [comment]
Please retry with client 1.8rc1 and server 8.0.2 and comment here if it still fails.
