### ISSUE TITLE
Silent installation owncloud client

### ISSUE THREAD

**Issue by Blisk** [owncloud/client#2006]
### Expected behaviour
Tell us what should happen

I have tried silent installation of owncloud but it doesn't work because a window opens and ask that some tasks are opened for program owncloud.exe and it needs to be closed before continue. And than, do you want to close those task? YES NO .And that happends all the time. I have windows 7 64

owncloud.exe /S

owncloud client 1.6.1.3267

### Client configuration
Client version:
owncloud client 1.6.1.3267
Operating system:
windows 7 64
OS language:
slovenian
Installation path of client:
default
C:\Program Files (x86)\ownCloud

**Comment by danimo** [comment]
This will be in 1.8

**Comment by lmaestro** [comment]
It works fine in version  1.8.0-nightly20150218 (build 4740)
