### ISSUE TITLE
Differing Storage Usage Amounts shown on Accounts Client Screen

### ISSUE THREAD

**Issue by MatthewVance** [owncloud/client#2014]
### Expected behaviour
The Storage Usage section on the Account tab of ownCloud settings should be accurate or at least be equal to or greater than the amount shown as currently uploaded. 

### Actual behaviour
The storage usage was reported as lower than the amount of data reported as currently uploaded. 

As shown in the included screenshot, when file 39 of 39 was being uploaded, the status showed 216 MB of 815 MB total had been uploaded. The file  shown as being uploaded was 808 MB, with 209 MB of it already uploaded. However, my storage used was  reported as 86 MB.

![quota](https://cloud.githubusercontent.com/assets/2671546/3738187/1341a304-173e-11e4-8d63-2f7b55c00fa3.jpg)

### Steps to reproduce
1. Add several files to the OwnCloud folder in Windows
2. Monitor the Account section of the ownCloud Settings window for storage space utilization inconsistencies 

### Client configuration
- **Client version:** 1.6 1ows (build 633); built from Git revision 40d765c73aa64de2fcf8503886f27c8da7b7d3d9 on Jul 16 2014, 16:13:20 using Qt 5.2.1.
- **Operating system:** Windows 8.1 Pro
- **OS language:** English
- **Installation path of client:** C:\Program Files (x86)\ownCloud

**Comment by guruz** [comment]
Still reproducable with 2.0.2 beta?

**Comment by Dianafg76** [comment]
I tested this issue, and it is working OK
Desktop v ownCloud-2.0.2.2750-nightly20150928.pkg 
Close
