### ISSUE TITLE
Windows Desktop Client and Option --confdir 

### ISSUE THREAD

**Issue by PepeN** [owncloud/client#2022]
Hi,
I install ownCloud-1.6.2.3463-setup.exe (system windows 2003)
I try to use ```"C:\Program Files\ownCloud\owncloud.exe" --confdir "%APPDATA%\ownCloud" ```
After I finished setting client shows that all the "OK"

But the folder ownCloud was created in
```C:\Documents and Settings\USERNAME\Local Settings\Application Data```  **%LOCALAPPDATA%**
Not in 
```C:\Documents and Settings\USERNAME\Application Data``` **%APPDATA%**

After I add ```"C:\Program Files\ownCloud\owncloud.exe" --confdir "%APPDATA%\ownCloud" --logwindow```
```
07-31 17:31:29:661 socketapi.cpp:55 SocketApi:  can't start server "\\.\pipe\" 
07-31 17:31:29:661 owncloudgui.cpp:101 No configured folders yet, starting setup wizard 
07-31 17:31:29:864 qiodevice.cpp:821 QIODevice::read: device not open
07-31 17:31:29:880 owncloudwizard.cpp:160 Current Wizard page changed to  0 
07-31 17:31:32:817 mirallaccessmanager.cpp:56 void Mirall::MirallAccessManager::slotProxyAuthenticationRequired(const QNetworkProxy&, QAuthenticator*) 3 
07-31 17:31:32:817 ocupdater.cpp:145 Failed to reach version check url:  "Proxy requires authentication" 
```

Of course if I move the folder ownCloud from %LOCALAPPDATA% to %APPDATA%, the settings are saved as necessary.

**Comment by danimo** [comment]
ownCloud purposefully stores configs in local app data, as the application does not roam, nor is it intended to do so. if %LOCALAPPDATA% is removed on reboot by a policy, I think a workaround like described above is perfectly acceptable.
