### ISSUE TITLE
owncloudcmd and owncloud.cfg need better documentation

### ISSUE THREAD

**Issue by ghost** [owncloud/client#2030]
The <a href="http://doc.owncloud.org/desktop/1.6/advancedusage.html#owncloud-commandline-client">documentation</a> for owncloudcmd and owncloud.cfg is insufficient to actually help set up and be able to sync using owncloudcmd.

Anyone who reads that documentation to try to sync with an owncloud server will likely not be able to.  The documentation doesn't even explain all the necessary steps to actually set up the local owncloud directory.  There is no information about where, if anywhere, the local owncloud directory is supposed to be specified in owncloud.cfg.

There is insufficient information about the auth process and whether its even possible to store the credentials in owncloud.cfg.  Also, if someone is trying to specify the auth credentials as command-line switches to owncloudcmd as in the example, what about complex passwords that are likely to contain characters such as *$%& which are likely to confuse BASH?  

Finally, there is no comprehensive listing of every available option for owncloud.cfg which there should be for reference purposes.

The closest information I could dig up on the web is the article "<a href="http://ossramblings.com/headless-owncloud-linux-sync">Headless Command Line Sync for ownCloud on Linux</a>" which also is not comprehensive enough and uses old options.

**Comment by naude** [comment]
I struggled implementing owncloudcmd on an ubuntu 14.04 headless server and finally got it working by importing the opensuse.org repositories from this page https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client 

Created an ownCloud directory in the headless server's user home dir and thanks to danimo updating the ownlcoudcmd not needing the confdir it then worked lovely doing this

$  owncloudcmd -u owncloudusername -p 'owncloudpass' /home/headlessuser/ownCloud/ https://ownclouddom/cloud/remote.php/webdav/
