### ISSUE TITLE
Connection timed out & Operation canceled  

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/client#2039]
Hi,
it seems the client is unable to sync some of the files on a new computer with the ownCloud client installed.
The same files are synced on another computer.
Client log:
09:43     myfolder/mysubfolder/file_1_of_2.iso   ownCloud       Operation canceled  
09:43     myfolder/mysubfolder/testfile2.202.iso  ownCloud       Operation canceled  
09:43     myfolder/mysubfolder/Info.txt          ownCloud       Connection Timeout  
09:37     myfolder/mysubfolder/file_1_of_2.iso   ownCloud       Operation canceled  
09:37     myfolder/mysubfolder/testfile2.202.iso  ownCloud       Operation canceled  
09:37     myfolder/mysubfolder/Info.txt          ownCloud       Connection Timeout  
09:32     myfolder/mysubfolder/file_1_of_2.iso   ownCloud       Operation canceled  
09:32     myfolder/mysubfolder/testfile2.202.iso  ownCloud       Operation canceled  
09:32     myfolder/mysubfolder/Info.txt          ownCloud       Connection Timeout  
09:26     myfolder/mysubfolder/testfile2.202.iso  ownCloud       Operation canceled  
09:26     myfolder/mysubfolder/Info.txt          ownCloud       Connection Timeout  
09:26     myfolder/mysubfolder/file_1_of_2.iso   ownCloud       Connection Timeout  
09:21     myfolder/mysubfolder/Info.txt          ownCloud       Operation canceled  
09:21     myfolder/mysubfolder/testfile2.202.iso  ownCloud       Operation canceled  
09:21     myfolder/mysubfolder/file_1_of_2.iso   ownCloud       Connection Timeout  
09:15     myfolder/mysubfolder/Info.txt          ownCloud       Operation canceled  
09:15     myfolder/mysubfolder/testfile2.202.iso  ownCloud       Operation canceled  
09:15     myfolder/mysubfolder/file_1_of_2.iso   ownCloud       Connection Timeout  
09:09     myfolder/mysubfolder/Info.txt          ownCloud       Operation canceled  
09:09     myfolder/mysubfolder/testfile2.202.iso  ownCloud       Operation canceled  
09:09     myfolder/mysubfolder/file_1_of_2.iso   ownCloud       Connection Timeout  
09:04     myfolder/mysubfolder/Info.txt          ownCloud       Operation canceled  
09:04     myfolder/mysubfolder/testfile2.202.iso  ownCloud       Operation canceled  
09:04     myfolder/mysubfolder/file_1_of_2.iso   ownCloud       Connection Timeout  
08:58     myfolder/mysubfolder/file_1_of_2.iso   ownCloud       Operation canceled  
08:58     myfolder/mysubfolder/testfile2.202.iso  ownCloud       Operation canceled  
08:58     myfolder/mysubfolder/Info.txt          ownCloud       Connection Timeout

@dragotin 
@danimo

**Comment by DACN** [comment]
I am having the same problem. Running Windows 8.1 on my laptop, with the owncloud client 1.7.1 (build 4382) with owncloud 7.0.4.  Trying to sync some 60,000 files and 60Gb of data to a server in my home network. Works fine apart from timeouts on large files. Installed with nginx and mysql.

As of now, some 50,000/60,000  files synced (mostly smaller files) and roughly 10Gb of the 60Gb of data synced.

One failure was a file 'word2011.exe' of about 600Mb. The interesting thing about the failure, was that it completely uploaded successfully into the correct directory - but then the final bits of the process of failed to complete - and it shows as being timed out.

Interestingly, have also had a timeout message on deleting a large file. In this case the file was of 2500Mb and it had uploaded without timeout messages. I deleted it this afernoon, and this evening during the syncronisation owncloud gave the message:

    'Could not read status line: connection timed out'

However, on checking via the web interface, this particular file has been moved to the set of deleted files.

David Nicol

**Comment by brunodegoyrans** [comment]
Hi

Same issue for us. Personnaly I dont have this problem but my collaborators have. They leave in a country where Internet is very bad. They obtain the errors messages with file size over few Mb.
Before owncloud, we were using google drive and didnt have this issue.
I hope I wont have to return to google drive.

Is there a solution?
