### ISSUE TITLE
Windows client setup does not detect client running (with different user account)

### ISSUE THREAD

**Issue by McNetic** [owncloud/client#2041]
The windows client setup does not recognize that the client is still running (with a different user account). The uninstall process runs without error, but the exe is still running and still present, so the install process fails until it is manually killed.
I know this is a rare scenario, but the uninstall should detect that the client is still running and stop it or prompt the user to stop it.

**Comment by Dianafg76** [comment]
I can't reproduce it. Can you try o reproduce in this version: ownCloud-1.8.2.5167-nightly20150609-setup.exe?
If you are able please reopen it

**Comment by McNetic** [comment]
No really?
![owncloud](https://cloud.githubusercontent.com/assets/1324685/8061267/60af0210-0eca-11e5-9d98-71c63f8059ae.JPG)
How often will I have to reopen this?
I'll describe how to reproduce: Install (not current version of) owncloud. Log in to windows with some user A. Right click the current owncloud installer, holding the shift key. Choose "Run as different user" ("Als anderer Benutzer ausführen" in german, NOT run as Administrator, A does not have administrative priviliges in this case). Enter credentials of user B (who has administrative privileges). Choose not to remove the old version prior to installing (is this option new? don't remember seeing it the last time). If it does not work like this, it might have to do with UAC being disabled on my machine (which will be default in most corporate environments).

**Comment by Dianafg76** [comment]
I can't reproduce it. Can you try to reproduce it in the latest version? If you are able please reopen it.
