### ISSUE TITLE
Developer version so the client can be tested more easily

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#2056]
Currently it is not possible for me to test the ownCloud client dev version on my laptop, since I already run a production version.

To make it easier for potential testers, we should have a dev version of the client which can be installed alongside the stable version. This can apparently be achieved by making a theme for it.

cc @dragotin @danimo @jnweiger

**Comment by guruz** [comment]
CC @nickvergessen

**Comment by nickvergessen** [comment]
Seems to work now, and thanks for removing the `documents/` limitation.

:+1:

**Comment by dragotin** [comment]
We have a client called testpilotclient. 

I just added a build into the common *isv:ownCloud:desktop* repository, it will take a while until its built, but finally everybody simply can install a package called testpilotcloud-client and use it in parallel with the "normal" client. 

Be aware that once we enter the beta phase again, the testpilotcloud client will be updated.
