### ISSUE TITLE
[1.6.2] Insufficient Storage Error When Syncing Large Number of Files

### ISSUE THREAD

**Issue by razyr** [owncloud/client#2061]
I was on site with a client today and tried to sync a shared folder which had approximately 5,000 files.  Total size was approx 900K.    Client quota was initially Default (5GB), then explicitly set to 5G then we tried 10GB just to entirely rule out quota issues.

Client machine was Windows 7 with 1.6.2 Mirall client.
Block/Volume storage on server is only 3% full.   Using Swift storage for user files and there are multiple terabytes of free space on Swift.
Server is OC 7.0.1 running on Ubuntu 12.0.4 LTS.

Error appears after +500MB of files have successfully uploaded.   Also note that the normal storage/quota information has been replaced with the message "Currently there is no storage usage information available".   Checking the Storage Usage information from another machine showed the expected "% of GB of server space in use" message.

![image001](https://cloud.githubusercontent.com/assets/8116645/3915748/6593e6a0-2367-11e4-973d-f7340492d3e2.png)

Server log showed the following error.   Actually 23,000 lines of similar messages from multiple attempts to sync.

```
{"app":"webdav","message":"Sabre\\DAV\\Exception\\InsufficientStorage: ","level":4,"time":"2014-08-13T19:08:42+00:00"}
```

Logging into the web UI and exploring through the file system somewhat, you can see a large number of files are copied OK but the later directories show many files with zero byte size and many folders/subfolders show the size as "pending" or zero bytes.

![image2](https://cloud.githubusercontent.com/assets/8116645/3915768/31976fba-2368-11e4-8687-0628e96db08e.png)

The client sits and waits for a bit then starts the entire sync process all over again with errors at the same place each time.   None of the missing or zero byte files ever seem to update on the server.

Since this is a shared folder, another workstation is successfully syncing the files down to that machine and is matching precisely what the server sees.   The problem is with the sync on upload.

I should mention that after these "insufficient storage" errors, I was able to run Duplicati and create a backup of the shared folder on another account on the same ownCloud instance and I was able to sync multiple GB of large files from my office computer.

**Comment by razyr** [comment]
Probably still related to this same bug, but I'm seeing 507 errors on a new OC 8.0.2 server with the 1.8.0 client.  The new server is also using Swift for backend storage.  There are Terabytes of available storage on the back end.  None of our users are over 50% of their quota.  All of the files being transferred are small.

Owncloud.log has an entry that looks like this about every 30 seconds from one of our users.

14.16.17.34 - user1@userdomain.com [23/Mar/2015:14:34:01 -0300] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 507

This user has a 50 GiB quota but the company has a whole has less that 25 GiB of data across all users.  They have approximately 7600 files, the largest of which is only 2 GiB.

We are also seeing failed syncs for uploaded files.   User2 in this case has a 300 GiB quota.  User3 has a 50 GiB quota.

14.16.17.34 - user2@userdomain.com  [23/Mar/2015:14:41:59 -0300] "PUT /remote.php/webdav/Long%20File%20Name_march2015.docx HTTP/1.1" 507 192
14.16.17.34 - user3@userdomain.com [23/Mar/2015:14:57:05 -0300] "PUT /remote.php/webdav/Foldername%20Desktop/Folder%20Name%20Long%20Long%20Folder%Name/File%20Name%20VSC.pdf HTTP/1.1" 507 192

Here is another example.  This error repeats 8 times over the course of about 6 minutes, then once more the next day.  In this case the file/folder naming is less complex.  This is the user with 275 GiB of unused quota.  The file is a one page PDF so whatever is going on has little to do with actual file sizes or available storage.

14.16.17.34 - user2@userdomain.com  [23/Mar/2015:16:10:14 -0300] "PUT /remote.php/webdav/Company%20Invoices/Sponsorship/ACME%20Invoice%202015.pdf HTTP/1.1" 507 192

**Comment by ogoffart** [comment]
This seems to be a server issue that can be tracked at https://github.com/owncloud/core/issues/15189
