### ISSUE TITLE
Licensecheck v1.7.0~alpha1

### ISSUE THREAD

**Issue by hefee** [owncloud/client#2068]
I fould following problems, the following files have a no copyright header or unclear what license:
* src/mirall/settingsdialogmac.(cpp|h) (created by Denis Dzyubenko, no other file mentions his name)
* shell_integration/MacOSX/LiferayNativityInjector/LiferayNativityInjector.m
* shell_integration/MacOSX/deploy.sh
* shell_integration/MacOSX/loadPlugin.sh
* shell_integration/nautilus/ownCloud.py (btw. don't mix tabs and spaces for indent)
* shell_integration/testclient/*
* shell_integration/windows/OCShellExtensions/OCUtilTest/* (no license information in folder or upper folder - i think these files are also by "Liferay, Inc. All rights reserved." LGPL v2.1)

no free software:
* shell_integration/MacOSX/LiferayNativityFinder/Finder/Finder.h
    Copyright 2010 Canvastudio Les Nie. All rights reserved.
* shell_integration/MacOSX/LiferayNativityInjector/LNStandardVersionComparator.h
    Copyright 2007 Andy Matuschak. All rights reserved.
* shell_integration/MacOSX/LiferayNativityInjector/LNStandardVersionComparator.m
     Copyright 2007 Andy Matuschak. All rights reserved.
* shell_integration/MacOSX/LiferayNativityInjector/LNVersionComparisonProtocol.h
     Copyright 2007 Andy Matuschak. All rights reserved.

**Comment by jnweiger** [comment]
@dragotin Licensing is not a packaging issue :-) A word from the autor would be great help.

**Comment by dragotin** [comment]
Answer from the author:
```
Looks like that header was pulled from Sparkle, which is licensed under MIT.
```
So that is MIT as the rest of the project. Fine.
