### ISSUE TITLE
Date-time wrong on downloaded files 

### ISSUE THREAD

**Issue by nneil** [owncloud/client#2076]
### Expected behaviour

Files synced between machines
### Actual behaviour

ZIP files in the collection did not get the correct date-time on machine B. Instead they got the time of download.
### Steps to reproduce
1. Upload 2,500 mixed files on Win 7 PC A
2. Wait for client on Win 7 PC B to download them
### Server configuration

Operating system: Centos 6.4

Web server: Apache

Database: MySQL

PHP version: 5.4

ownCloud version: 7.0.1

Storage backend: ???
### Client configuration

Client version: 1.6.4.3463

Operating system: Windows 7

I have two instances of the client running on Windows 7. I did an upload of around 2,500 mixed files from machine A to the server using the client. When the files were downloaded to client B by the routine sync, the ZIP files in the collection did not get the correct date-time on machine B. Instead they got the time of download.

**Comment by VBoudry** [comment]
Hi, 
I have had a similar problem:
- sync'ed a complete directory hierarchy
- at next restart of the Client (OSX10.10, v1.6.4 build 1195) all the files were downloaded with the time set to the download time.
  [I had to manually restore the files]

This seems to point out a bad handling of creation/modification time.
I personnally don't see any good reason not to keep the mod time across machines,
and this is a major issue preventing using the client.

Best regards,
Vincent Boudry.
