### ISSUE TITLE
Sync client UI hangs when VM cable unplugged during sync

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#2080]
### Steps to reproduce
1. Setup a VM with ownCloud on it (I used a bridge net adapter)
2. Upload a lot of files
3. Setup a local sync client and configure it to sync against the VM
4. While the sync client is loading, unplug the virtual network cable of the VM

### Expected result
Sync client detects failure and stops syncing.
If not possible to detect failure directly and needs a timeout, the UI should still be responsive.

### Actual result
UI hangs, not responsive.
Only after a few minutes when the network timeout occurs, the UI becomes responsive again.

### More info
Sync client versions 1.6.2 and 1.7.0alpha
OC 7 on stable7

**Comment by guruz** [comment]
This needs re-testing when we switched to Qt5 for Linux
https://github.com/owncloud/client/issues/2558

FYI @dragotin @ckamm @jnweiger

**Comment by dragotin** [comment]
@PVince81 still an issue with 2.0.1?

**Comment by dragotin** [comment]
Ok, @ogoffart said its legacy stuff and can be closed.
