### ISSUE TITLE
[1.6.2] Changed account settings were not saved because of a locked or unwritable owncloud.cfg file. [Suggestion] Add a check whether new settings could properly be saved.

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/client#2096]
* Windows 8
* OC Client 1.6.2
* OC Server 7.0.1

I changed the password of my owncloud server account (1), and also in the running client (2) via → Einstellungen → Konto bearbeiten. I reentered the server account data, but with the new password. This works, the currently running client is then syncing again 

But **after stopping and restarting the client**, and also after a Windows restart, I get - this is reproducible - a connection error (pictured). It **looks, as if the changed password (step 2) is not permanently saved**. I also tried to change the Settings after starting owncloud as Administrator → same problem, password appears not to be saved permanently.

[UPDATE]
Netwerk settings like Proxy or Bandwith limitations are also not saved.

These problems are not present on Linux, using the Linux client 1.6.2.

Please assist.

<img src="http://i.imgur.com/z6oIYgR.png">

**Comment by dragotin** [comment]
I assume this is fixed with subsequent versions. Let me know if not. Thx.
