### ISSUE TITLE
gitignore interpretation

### ISSUE THREAD

**Issue by karlito139** [owncloud/client#2097]
Having a few software projects, I would like not to have to sync all the files of a project at each compilation.

It would be nice to be able to automatically add the content of the .gitignore files to the list of ignored files in owncloud sync.

**Comment by wonook** [comment]
I agree. I also have a few folders using git repositories, and it's a burden unlinking them

**Comment by waterfoul** [comment]
I would love this too, or at least a .owncloudignore file which gets synced across all the machines

**Comment by mininao** [comment]
:+1:

**Comment by cruessler** [comment]
Would such a feature have a chance of getting accepted? If so, I might try to implement it.

**Comment by xn--nding-jua** [comment]
:+1:

**Comment by LouisMartin** [comment]
Same here with python virtual environments in git repositories.

**Comment by ogoffart** [comment]
We will not use the `.gitignore` file as this file is for git.
If anything, we could use a `.syncignore` file.

**Comment by ogoffart** [comment]
Actually, i think then this issue should be closed in favor of https://github.com/owncloud/client/issues/1558

**Comment by ogoffart** [comment]
This is not something we want.

Note: there is a pull request on the nextcloud repository: https://github.com/nextcloud/desktop/pull/745
(but the implementation as it is today looks like it would slow down the discovery a lot, so i do not recommand using that merge request in this state)
