### ISSUE TITLE
[OSX ] In the columns view the overlay icons are not shown 

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2107]
### Expected behaviour
Overlay icons are shown in all the finder views

### Actual behaviour
In the columns view overlay icons are not shown 

## Steps to reproduce
1. Instal the new version
2. Open desktop client
3. Open the Finder select columns view

### Client configuration
Version 1.7.0 nightly-2040826

Operating system: Mac 10.9.3

**Comment by dragotin** [comment]
We will move to the new Mac OSX 10.10 API at some point in the future.

**Comment by jturcotte** [comment]
Should be fixed by 0b461e227502d581ecebc7ab0ee759eacb3121c9

**Comment by lmaestro** [comment]
It is fixed in the latest version.
