### ISSUE TITLE
Add CrashReporter

### ISSUE THREAD

**Issue by dschmidt** [owncloud/client#2109]
Add Crash Reporter

- [x] Mirall: implement crash handler #2110 
     - [x] Add libcrashreporter-qt (Breakpad) as submodule
     - [x] Get rid of QApplication subclass to catch crashes on startup (Deferred, #2952)
- [x] Server:
    - [x] Acquire VM and install [Socorro](https://github.com/mozilla/socorro)
    - [x] Security Review (by @LukasReschke)
    - [x] Archive server to store all symbol dumps
    - [x] Discard old symbols of nightly builds after ~2 weeks
- [x] Deployment: build with RelWithDebInfo, extract debug symbols and upload them)
    - [x] Establish Upload debug symbols to Soccoro
    - [x] Windows (Rotor)
        - [x] Generate .sym files for binaries from OBS for Windows
        - [x] Generate .sym files for our own binaries (RelWithDebInfo!)
        - [x] Upload symbols
    - [x] Mac OS X
        - [ ] Generate .sym files for binaries from Homebrew (?)
        - [x] Generate .sym files for our own binaries (RelWithDebInfo!)
        - [x] Upload symbols
    - [x] Linux
        - [x] Decide if desired at all (Not ATM)

**Comment by LukasReschke** [comment]
> Security Review (by @LukasReschke)

Looks pretty good for me. Did some digging in the code as well and found nothing that would be a showstopper. Nice stuff :+1:

**Comment by lmaestro** [comment]
@danimo any news?

**Comment by dragotin** [comment]
Status here is that we ship the crashreporter only for Windows platfrom on 1.8.0. The infrastructural changes for Mac (and maybe linux) have to be pushed to 1.8.1: #2918

Setting this one to Ready-For-Test - @jturcotte could you help testing this? Thx.

**Comment by danimo** [comment]
Last issues sorted out.

**Comment by dragotin** [comment]
Closing this. @danimo pls. do another issue report reflecting the missing things for OSX.

**Comment by dschmidt** [comment]
:+1:
