### ISSUE TITLE
Reconciler/Propagator: Priorize resuming uploads/downloads

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2128]
... so we finish up work before starting new things.

Not sure how feasible this is because of the directory-based propagation

**Comment by guruz** [comment]
@mrow4a Just FYI..

**Comment by mrow4a** [comment]
Not sure what is the exact idea behind this issue? Could you gie more details @guruz ?

**Comment by ogoffart** [comment]
Closing old issue.
