### ISSUE TITLE
Windows shortcuts ".lnk" error

### ISSUE THREAD

**Issue by oscaroxy** [owncloud/client#2132]
When I create a link into a folder, then owncloud sync it.
If I delete the file assigment to link, without delete the link then owncloud client 1.6.2 don't work fine, that is it don't sync correctly.

when I delete the .lnk from client then the client give a error on lnk.
when I delete the .lnk from web then the .lnk are deleted, but after some seconds the files are re-created.

for resolve I've to delete the link's parent folder... 

Could you give me advice?
thanks

**Comment by ogoffart** [comment]
Closing old issue,  please reopen if it still happen in 1.8
