### ISSUE TITLE
Sync status in desktop

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#2137]
I talked to @ogoffart while at the event about an anomalous issue in the desktop client. This is new in 1.6.3 and it is that the desktop client uploads 3 files in parallel, but only shows the details of 1 in the upload status bar, but shows the upload MB in the summary of an upload shows the total – which is all three. So the summary of the status, and the actual status of an upload are impossible to rectify.

We should have a status bar – even a thin one would be ok – for each file as it uploads, even if in parallel. Then the interface makes a whole lot more sense.

@jancborchardt how would you update the current upload detail in the desktop client to show 3 files in parallel? Three short bars added up like bit torrent does, or three long ones stacked, or… I would love your thoughts.

![untitled](https://cloud.githubusercontent.com/assets/1818977/4097202/cd4a91d0-2fcf-11e4-9746-a7e461490d4c.png)

**Comment by guruz** [comment]
This is a bit better now, we don't show the path anymore, just the filename.
