### ISSUE TITLE
[OS X] [Windows] We ship too many Qt libaries

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2140]
QtQuick, QtPositioning, ....

**Comment by jturcotte** [comment]
I was able to shrink QtWebKit by 20MB and remove its runtime dependency to those smaller extra Qt modules by re-running qmake in qt5/ right after configure with the following argument:

    "WEBKIT_CONFIG-=build_webkit2 video webgl svg inspector geolocation 3d_rendering device_orientation orientation_events use_qt_multimedia use_3d_graphics use_graphics_surface"

But it turns out that we'd need to generate a separate MinGW OBS package for QtWebKit, which is not specific to ownCloud's distribution, and build it with those arbitrary switches. With this in mind, whether it's worth fixing or not is left to decide.

**Comment by guruz** [comment]
However regarding OBS:
```
<danimo> jturcotte: we can tell the webkit package to build twice: once in a builddir with app deps, and once without dependencies
<danimo> jturcotte: generating two conflicting packages "mingw32-libqt5-webkit" and "mingw32-libqt5-webkit-minimal"
<danimo> but having a minimal webkit is probably beneficial to others as well
```

**Comment by jturcotte** [comment]
"others" in that case would exclude QtQuick2's WebView and SVG support though.

**Comment by dschmidt** [comment]
:+1:  for additional minimal package.

Certainly beneficial to others, e.g. Tomahawk. :-)

**Comment by jturcotte** [comment]
The OSX nightly builds should now have the diminished dependencies (the installer is 22.8MB instead of 29MB).

For Windows we can maybe have a look during the next release, it's not as trivial for the reasons mentioned above.

**Comment by guruz** [comment]
Might not be as important anymore if we can get rid of QtWebKit when adding OAuth

**Comment by jnweiger** [comment]
not sev3, but p3, according to mstingl's definition.

Having a qtwebkit-minimal sounds like a good idea in general - but manybe will never gain an importance high enough to be finally done?

**Comment by jturcotte** [comment]
Why do we now have both "sev" and "p" flags? Can't we rename existing flags if you guys really want the "p" version?
As for qtwebkit, the ideal plan is now to just get rid of it as soon as possible.

**Comment by jnweiger** [comment]
This issue is in energy-saving mode.  :-)

**Comment by ogoffart** [comment]
Is this still an issue?
Now we do not need QtWebkit anymore.
