### ISSUE TITLE
Client does not reconnect after losing the connection to the server

### ISSUE THREAD

**Issue by nlurkin** [owncloud/client#2148]
### Expected behaviour

When I resume the computer from hibernate or lose the connection, I expect the client to reconnect to the server.
### Actual behaviour

After losing the connection to the server, the client dos not reconnect. It is not always, I don't really know when exactly this happens but it seems to be quite often when resuming windows from hibernate. I also noticed that when I'm using a captive portal to connect to internet, the client is not able to connect to the server (because it receives the portal page) but does not retry afterwards (or fails). To solve this I have to restart the client.
### Steps to reproduce
1. hibernate windows
2. resume
3. if the wifi is not immediately available, the client loses the connection and does not reconnect afterwards
### Client configuration

Client version:1.6.1 (build 3267)
Operating system: Windows
OS language: English
Installation path of client: C:\Program Files (x86)\ownCloud
### Logs

The relevant lines are these one, appearing when I click retry sync (using F12): 
syncjournaldb.cpp:870 Transaction Start  "checkConnect" 
09-02 14:43:38:739 syncjournaldb.cpp:346 Columns in the current journal:  ("phash", "pathlen", "path", "inode", "uid", "gid", "mode", "modtime", "type", "md5", "fileid") 
09-02 14:43:39:256 folderman.cpp:449 FolderMan: Syncing is disabled, no scheduling. 
09-02 14:43:39:259 folderman.cpp:449 FolderMan: Syncing is disabled, no scheduling. 
09-02 14:43:39:285 folderman.cpp:449 FolderMan: Syncing is disabled, no scheduling. 
09-02 14:43:39:289 folderman.cpp:449 FolderMan: Syncing is disabled, no scheduling. 
09-02 14:43:47:892 networkjobs.cpp:191 !!! Mirall::CheckServerJob created for  QUrl( https://cloud.nicolaslurkin.eu" )  querying "status.php" 
09-02 14:43:57:906 networkjobs.cpp:357 TIMEOUT virtual void Mirall::CheckServerJob::slotTimeout() 

I don't have logs of when the client actually loses the connection because it crashes after few minutes when I enable the log file (maybe because of a too big log file?)

**Comment by gerbsen** [comment]
we had something similar which was fixed by:

      proxy_http_version 1.1;
      proxy_buffering off;
      proxy_ignore_client_abort on;
