### ISSUE TITLE
unix man pages are not fully branded

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#2153]
genbranding.pl renames the man pages, but the contents always speaks of OWNCLOUD, ownCloud, owncloud. No templates apply.

**Comment by hodyroff** [comment]
oh mighty. @michaelstingl 
Honestly I would just have an option to delete those man pages if so desired, but I don't know if thats more difficult then putting $name or something into them ... there are some borders to branding maybe ;)

**Comment by michaelstingl** [comment]
@guruz Is it easy to add the branding variables here?

**Comment by guruz** [comment]
@michaelstingl afaik you need to replace it with a $FILENAME.in (or .cmake) file and then add a link in the CMakeFiles.txt to have cmake process the file when copying it.
You can look at how it is done for admin/osx/post_install.sh.cmake

**Comment by michaelstingl** [comment]
Who can fix it? @SamuAlfageme ?

**Comment by SamuAlfageme** [comment]
Yes, I can make a small patch to use the `$APPLICATION_EXECUTABLE`[`cmd`] in the manpages, and expand it with Sphinx, it should be that easy. 

But my real concern is that these are currently not being copied/linked to `/usr/[local/]share/man/man1/` in any [post]installation script (or at least I can't see where; also tried installing owncloud through APT in ubuntu and no luck with it).

btw, the pages seem to be a bit outdated/incomplete: 

* [**`owncloud(1)`**](https://github.com/owncloud/client/blob/master/doc/owncloud.1.rst)
* [**`owncloudcmd(1)`**](https://github.com/owncloud/client/blob/master/doc/owncloudcmd.1.rst)

**Comment by guruz** [comment]
I don't even think you need Sphinx, you can do it analog to what I described above: https://github.com/owncloud/client/issues/2153#issuecomment-265714410

**Comment by hodyroff** [comment]
If you like we can also get rid of the man pages completely ... but lets decide on one direction and get it done for 2.4.

**Comment by jnweiger** [comment]
Manpages to be removed ASAP
