### ISSUE TITLE
packaging files (spec, dsc, ...) require manuals synchronization

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#2163]
I've brought most of the _.spec files in sync manually, but we still have multiple sources, when generating new packages. 
All branded clients (including testdrivecloud-client) use templates found in administration/jenkins/obs_integration/templates/client/_ but all non branded clients don't have their packaging files only in OBS.

I am not sure how we can keep the obs scatter in sync with github. Suggestions welcome.

**Comment by ogoffart** [comment]
@jnweiger do you still care about this issue?

**Comment by jnweiger** [comment]
fixed.
