### ISSUE TITLE
Going for higher-precision mtime in 1.8 and beyond

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2169]
This is a discussion item right now, nothing decided yet.

@ckamm and @guruz think that the current 1-second-resolution mtime is not good enough, given issues like https://github.com/owncloud/mirall/issues/2167

Maybe as a first step we could have this optional and client side only by having an additional column in ```.csync_journal.db``` used for change detection.

This is additional to our plan to also have a new ```filesize``` column in the DB.

CC @dragotin @ogoffart @DeepDiver1975 @PVince81

**Comment by dragotin** [comment]
I think this one does not really make sense any more as we move towards checksums for corner cases.
