### ISSUE TITLE
Owncloud client crash when sync a network drive

### ISSUE THREAD

**Issue by Nico207** [owncloud/client#2177]
Hello,

I use the owncloud client  with local files succesfully, but when I try to add a network drive, he start synchronize the files and close suddenly...
After that it's not possible to simply restart the client. I need to rename the directory in the network drive, start the client, go quickly to the parameters and delete the share. If not, the client crash.

I have launch owncloud with `--logfile` parameter. Nothing suspect (for me) except at the end :
> 09-06 22:53:39:800 csync_update: Update detection for remote replica took 0,31 seconds walking 5 files.
> 09-06 22:53:39:800 csync_memstat_check: Memory: 434732K total size, 57300K resident, 36876K shared
> 09-06 22:53:39:801 <<#### Update end ####################################################  325 
> 09-06 22:53:39:801 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     file: FileTest1.zip
> 09-06 22:53:39:801 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     file: FileTest2.zip
> 09-06 22:53:39:801 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     file: FileTest3.zip
> 09-06 22:53:39:801 _csync_merge_algorithm_visitor: INSTRUCTION_NEW       dir: Nouveau dossier
> 09-06 22:53:39:801 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     file: FileTest4.zip
> 09-06 22:53:39:801 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     file: FileTest5.zip
> 09-06 22:53:39:801 csync_reconcile: Reconciliation for local replica took 0,00 seconds visiting 6 files.
> 09-06 22:53:39:801 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     file: FileTest1.zip
> 09-06 22:53:39:801 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     file: FileTest2.zip
> 09-06 22:53:39:801 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     file: FileTest3.zip
> 09-06 22:53:39:801 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     file: FileTest4.zip
> 09-06 22:53:39:801 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     file: FileTest5.zip
> 09-06 22:53:39:801 csync_reconcile: Reconciliation for remote replica took 0,00 seconds visiting 5 files.
> **09-06 22:53:39:805 Database Transaction is running, do not starting another one!**
> **09-06 22:53:44:829 ERROR committing to the database:  "cannot commit - no transaction is active Incapable de soumettre la transaction"**
> **09-06 22:53:44:829 Error "Create table metadata" "database is locked Impossible de récupérer la rangée"**
> **09-06 22:53:44:831 Failed to query the 'inode' for file  "/media/Programmes/Test/FileTest1.zip"**
> **09-06 22:53:44:831 ASSERT: "d" in file /usr/include/qt4/QtCore/qscopedpointer.h, line 112**

My config :
- Ubuntu 14.04 32bits (French)
- Owncloud client 1.6.3

Thanks

**Comment by dragotin** [comment]
The database locking problems in the client are solved.
