### ISSUE TITLE
mirral Linux client PROPFIND /owncloud/remote.php/webdav/ filling  up logs

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/client#2179]
My apache logs are being filled up by owncloud mirral client with the following messages:
==> apache2/error.log <==
[Sun Sep 07 13:28:40 2014] [error] [client 192.168.254.4] user "USER" not found: /webdav/

==> apache2/ssl_access.log <==
192.168.254.4 - "USER" [07/Sep/2014:13:28:40 -0300] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1302 "-" "Mozilla/5.0 (Linux) mirall/1.6.3"

Everything appears to be working fine on client side, files are being syncronized just fine. Any ideas in how to fix this ?

**Comment by guruz** [comment]
This must be from your webserver setup. Did you configure any authentication stuff seperately that collides with ownCloud's handling?
