### ISSUE TITLE
Upgrade overwrites exclusion file

### ISSUE THREAD

**Issue by ecikweise** [owncloud/client#2193]
I added a lot of extensions to exclude from my owncloud backup. After the latest client upgrade/update it seems my exclusion file was overwritten and default exclusions were back. This caused a ton of data that I did not want to get synced, and put me over the server limit. Upgrades should not overwrite user writeable files. Thanks!

**Comment by SamuAlfageme** [comment]
Since the `sync-exclude.lst` file is preserved along with other files (#5342) between installs/uninstalls, this is solved as a collateral of that. Tried updating and now these settings are preserved. Closing.
