### ISSUE TITLE
[OS X] Yosemite "Dark Mode" menubar icon stays black on dark background

### ISSUE THREAD

**Issue by StrangeNoises** [owncloud/client#2215]
OSX Yosemite has a "dark mode" for the user interface, in which the menubar background goes from light grey to dark grey and the text and most menubar app icons are white.

Owncloud with monochrome icons selected doesn't adapt to this. The icon stays very dark grey, rendering it almost invisible on the dark background.

(Obviously no background-colour awareness either when colour icons selected, but at least visibility isn't an issue then.)

Desired behaviour: Awareness of the configured foreground and background colours in the menubar in Yosemite, and changing the colour or inverting the palette of the monochrome icon to match. FWIW the newest Viscosity (1.5.1) does invert the palette as you'd expect when using its new default icons, so it's not just Apple's own components that know how and when to do it. :)

I tried restarting it, in case it only picks up the colours on startup, but it didn't help. (In fact, upgraded belatedly from 1.6.2 to 1.6.3 - that didn't help either.)

Screenshot shows the problem. You're in good company of course, if you check out the icon of the app next to the Owncloud one. ;-)

![screen shot 2014-09-16 at 23 23 22](https://cloud.githubusercontent.com/assets/1295001/4296051/fcf4ad4c-3df0-11e4-9951-6aa6454fc582.png)

I assure you the owncloud icon is there, in the middle, a very slightly lighter grey than its background.

**Comment by soDEVch** [comment]
I'm using dark mode on OS X 10.10 and I'm always having trouble finding the icon in the menubar. Would really be nice to have the white icon. As mentioned above owncloud isn't the only app still having this issue. How soon can we expect this to be fixed?

**Comment by leipert** [comment]
Corresponding qt bug report here: 
https://bugreports.qt.io/browse/QTBUG-42109

**Comment by AlexanderWillner** [comment]
Seems that the corresponding change in QT has been merged in July 2015: https://codereview.qt-project.org/#/c/115120/

**Comment by chesterdkat** [comment]
Just checked with Version 2.0.2rc1 (build 2790) and this bug is still present... 

THANK YOU!

**Comment by guruz** [comment]
@AlexanderWillner thanks for digging this patch out.. we will need to modify our ownCloud-Qt for OS X

@dragotin @danimo

**Comment by StrangeNoises** [comment]
confused now because I thought this had been fixed. Is for me anyway in 2.0.1 release. Is it a regression in 2.0.2 builds?

<img width="129" alt="screen shot 2015-10-19 at 10 58 43" src="https://cloud.githubusercontent.com/assets/1295001/10574838/77e2aa98-7650-11e5-9fac-9b4760cf46a7.png">

It does sometimes go completely invisible until prodded in some way, but only on my multi-monitor setup, that I've seen, and it's pretty rare it does that now.

**Comment by svkurowski** [comment]
I fixed this in [https://github.com/owncloud/client/pull/2393](this pull request), which got merged. However my solution did not use OSX's template images because the functionality was not available in Qt. According to [https://bugreports.qt.io/browse/QTBUG-42109](this bug report), it is now available. At the moment I don't have the time to work on this, maybe someone else is interested in making the tray icons use template images on OSX?

**Comment by StrangeNoises** [comment]
ah right, the difference between a fix-for-now and a proper fix. ;-)

**Comment by guruz** [comment]
Tested with Qt 5.6, it works properly there. Now we just need to switch the OS X builds to Qt 5.6 -> https://github.com/owncloud/client/issues/3449

**Comment by mcastroSG** [comment]
@StrangeNoises may you test again ¿? In case it fails please repone

**Comment by StrangeNoises** [comment]
It's looked fine for me for some time. Thought there was just some desire to do it a more 'proper' way or something! 😀

**Comment by chesterdkat** [comment]
Fixed for me for at least several weeks or more. THANKS!
