### ISSUE TITLE
[1.6.3] Windows 7 - No Date showing in aktivities

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#2223]
No date showing in aktivities in windows client 1.6.3. Date is only shown in popup! See my screenshot:
http://i.imgur.com/q6CRafP.png

I think date should be shown in the list too!

**Comment by ogoffart** [comment]
Yeah, the item are never refreshed once they exist.
So we could set the long format for all the items, or have some complicated logic to refresh them.

Notehowever that the date is part of the tooltip.

**Comment by MegaV0lt** [comment]
Still in 1.8beta: No date is shown in activities ;(

If showing date is too complicate mybe insert a line showing that a new day began as a optical barrier?
![2015-02-19 08_41_03-owncloud](https://cloud.githubusercontent.com/assets/2804301/6263200/6c239aa6-b813-11e4-89c8-0dde92de3ae6.jpg)

**Comment by moscicki** [comment]
I know you guys don't like +1s but I have to give mine… ;-)

Please, it is so utterly confusing (e.g. useless) without the date. Especially if you try to figure out what your sync client did between yesterday and today...

kuba

--
