### ISSUE TITLE
mirall-1.7.0-beta1 fails to compile on CentOS-6

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#2225]
Q_DECL_OVERRIDE=override causes errors in https://build.opensuse.org/package/live_build_log/isv:ownCloud:oem:testpilotcloud/testpilotcloud-client/CentOS_CentOS-6/x86_64 like this:

[  598s] In file included from /home/abuild/rpmbuild/BUILD/testpilotcloud-1.7.0beta1/src/mirall/syncengine.cpp:19:
[  598s] /home/abuild/rpmbuild/BUILD/testpilotcloud-1.7.0beta1/src/mirall/owncloudpropagator.h: At global scope:
[  598s] /home/abuild/rpmbuild/BUILD/testpilotcloud-1.7.0beta1/src/mirall/owncloudpropagator.h:105: error: expected ';' before 'override'
[  598s] /home/abuild/rpmbuild/BUILD/testpilotcloud-1.7.0beta1/src/mirall/owncloudpropagator.h:106: error: expected ';' before 'override'
[  598s] /home/abuild/rpmbuild/BUILD/testpilotcloud-1.7.0beta1/src/mirall/syncengine.cpp:962: error: expected ';' at end of input
[  598s] /home/abuild/rpmbuild/BUILD/testpilotcloud-1.7.0beta1/src/mirall/syncengine.cpp:962: error: expected '}' at end of input
[  598s] In file included from /home/abuild/rpmbuild/BUILD/testpilotcloud-1.7.0beta1/src/mirall/syncengine.cpp:19:
[  598s] /home/abuild/rpmbuild/BUILD/testpilotcloud-1.7.0beta1/src/mirall/owncloudpropagator.h:103: error: expected unqualified-id at end of input
[  598s] /home/abuild/rpmbuild/BUILD/testpilotcloud-1.7.0beta1/src/mirall/owncloudpropagator.h:103: error: expected '}' at end of input
[  598s] make[2]: *** [src/CMakeFiles/testpilotcloudsync.dir/mirall/syncengine.cpp.o] Error 1

An attempt to workaround this on the c++ command line yields to another error:
[   36s] <command-line>: warning: "Q_DECL_OVERRIDE" redefined
[   36s] <command-line>: warning: this is the location of the previous definition
[   36s] In file included from /home/abuild/rpmbuild/BUILD/testpilotcloud-1.7.0beta1/src/mirall/folderwizard.cpp:21:
[   36s] /home/abuild/rpmbuild/BUILD/testpilotcloud-1.7.0beta1/src/mirall/selectivesyncdialog.h: At global scope:
[   36s] /home/abuild/rpmbuild/BUILD/testpilotcloud-1.7.0beta1/src/mirall/selectivesyncdialog.h:47: error: ISO C++ forbids initialization of member '_inserting'
[   36s] /home/abuild/rpmbuild/BUILD/testpilotcloud-1.7.0beta1/src/mirall/selectivesyncdialog.h:47: error: making '_inserting' static
[   36s] /home/abuild/rpmbuild/BUILD/testpilotcloud-1.7.0beta1/src/mirall/selectivesyncdialog.h:47: error: ISO C++ forbids in-class initialization of non-const static member '_inserting'
[   36s] make[2]: *** [src/CMakeFiles/testpilotcloud.dir/mirall/folderwizard.cpp.o] Error 1

**Comment by ogoffart** [comment]
Is this problem still an issue with 1.7.1?

**Comment by jnweiger** [comment]
CentOS_7 done: http://s2.owncloud.com:83/test-reports/20150116-1117/data/install-pkg-client-log.html#s1-s5-s1-t2


I have no plans to work on CentOS_5.
