### ISSUE TITLE
error reporting: files deleted on the server should not be reported as errors

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2227]
Consider this: sync client builds a (long) list of files to download from the server. Some of these files are deleted before the client finished the sync. 

IMO this should not be reported as error to the user (red icon and a pile of filenames in red). This should be of course logged properly so that a user can get this information. So this should be rather a "warning" or information for the user but as such is a normal situation (not error).

**Comment by Dianafg76** [comment]
@ckamm I tested this issue and is OK, so I close
Thanks :-)
