### ISSUE TITLE
[OS X] When one folder is downloading, it shows the green tick overlay icon instead of the blue one

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2233]
### Expected behavior
When one folder is downloading , it shows the blue spinning overlay icon

### Actual behavior
When one folder is downloading, it shows the green tick overlay icon
![screen shot 2014-09-22 at 14 04 25](https://cloud.githubusercontent.com/assets/4689430/4355780/d7e01bd6-4250-11e4-8611-c14fc1b17f9d.png)

### Steps to reproduce
1. Instal the new version
2. Open desktop client 
3. The account is syncing, downloading  

### Client configuration
Version 1.7.0-nightly20140922

Operating system: Mac 10.9.3

**Comment by dragotin** [comment]
@lmaestro it should be fixed with 1.7.1 - can you verify please?

**Comment by lmaestro** [comment]
It is not fixed in the latest version 1.8.0-nightly20150121 (build 1903)
![screen shot 2015-01-21 at 9 59 30 am](https://cloud.githubusercontent.com/assets/4689430/5833527/7fbcb3de-a154-11e4-95a9-0b30542aec43.png)

**Comment by lmaestro** [comment]
It is still happening in version 1.8.0-beta1

**Comment by dragotin** [comment]
Fixed by the commit above.

**Comment by lmaestro** [comment]
@guruz Can you verify it? It is weird because sometime it works fine but others no.

**Comment by lmaestro** [comment]
Fixed in version 1.8.0-nightly20150312(build2120)
