### ISSUE TITLE
special charters

### ISSUE THREAD

**Issue by Blisk** [owncloud/client#2234]
Server configuration

I'm running the desktop client on Centos 6.5 x64.
The ownCloud sync client version is 1.6.3
Owncloud version 7.0.2

I have a problem right now with uploading some files over client to server.
if folder or file have special charter in it it doesn't work, "can not rename file to final destination."

if I uploade it from web site than it is ok.
probem is with čšćđž
Also preview that files doesn't work.
if I delete that charters from filename and folder than is also ok

**Comment by guruz** [comment]
Which PHP version were you guys using?

@PVince81 Does the above ring a bell?

**Comment by PVince81** [comment]
Not really. Most encoding issues I heard about were for people running OC on a Windows server.

Here it's CentOS. Maybe something wrong with the locale configuration ? Please make sure PHP is set to en_US.UTF_8

**Comment by ogoffart** [comment]
This was the same error as https://github.com/owncloud/client/issues/2779  So maybe this needs testing now against the server from master.

**Comment by guruz** [comment]
Yep, please retry with a newer client and server.
