### ISSUE TITLE
An internal error number 1061 happened.

### ISSUE THREAD

**Issue by hunasdf** [owncloud/client#2240]
Hi!

I use owncloud client v1.6.1 (build 359) on OSX Maverics. Everything was fine, but one day, I got this error "An internal error number 1061 happened.". I tried to looking for any solution, but I did not find anything. Here my log it is help for you.

Can you tell me any solution for this?

Thanks,
Asi

09-24 11:46:26:672 syncengine.cpp:412 #### ERROR during csync_update : "An internal error number 1061 happened." 
09-24 11:46:26:703 syncengine.cpp:675 CSync run took 23489 
09-24 11:46:26:848 folder.cpp:644 -> CSync Finished slot with error true warn count 0 
09-24 11:46:26:849 folder.cpp:385 Processing result list and logging took 0 Milliseconds. 
09-24 11:46:26:850 folder.cpp:403 OO folder slotSyncFinished: result: 2 
09-24 11:46:26:850 folder.cpp:656 *\* error Strings: ("An internal error number 1061 happened.") 
09-24 11:46:26:851 folder.cpp:658 \* owncloud csync thread finished with error 
09-24 11:46:26:852 owncloudgui.cpp:209 Folder in overallStatus Message: Mirall::Folder(0x7fc833e7f330) with name "ownCloud" 
09-24 11:46:26:853 owncloudgui.cpp:124 Sync state changed for folder "ownCloud" : "Error" 
09-24 11:46:26:853 socketapi.cpp:131 SocketApi: Broadcasting to 0 listeners: "UPDATE_VIEW" 
09-24 11:46:27:055 folderman.cpp:478 <===================================== sync finished for "ownCloud" 
09-24 11:46:27:257 folderman.cpp:453 XX slotScheduleFolderSync: folderQueue size: 0 
09-24 11:46:32:691 networkjobs.cpp:191 !!! Mirall::CheckQuotaJob created for QUrl( "http://my.url/owncloud" ) querying "/"

**Comment by killall5** [comment]
I've got that error again on client 1.7.0. OS X 10.10.2.

Can't get wrong file name from log file: https://gist.github.com/killall5/939d6442c074821ca62e

**Comment by johndiop** [comment]
hello might be late but to understand 1061 probleme do this:
create new file or folder give a name with this caractere (􀂅 ) yes this one into brackets  example:file􀂅s and sync it in your folder owncloud after that you have to rename your folder without char like that.

**Comment by ogoffart** [comment]
This issue is now tracked in https://github.com/owncloud/client/issues/2777

**Comment by guruz** [comment]
We have a 2.0 nightly available that should show a nice error with the failing filename
http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.2602-nightly20150805.pkg
