### ISSUE TITLE
Wrong estimate on error

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#2243]
### Steps to reproduce
1. Hack the ownCloud server to force it to return "400 Bad Request": edit `lib/private/connector/sabre/file.php` and inside the function `get()` add a row `throw new \Sabre\DAV\Exception\BadRequest('test bad request');`
This will simulate a "Bad request" response that might happen in various situations on download.
2. Upload a file with the web UI
3. Start the sync client and let it try and download the file

### Expected result
Don't show any estimate on error

### Actual result
Estimate shows a few years...

![blacklistestimate](https://cloud.githubusercontent.com/assets/277525/4391082/310a151a-4402-11e4-92ca-b971f2cbe271.png)

### Versions
ownCloud 7.0.2
Sync client 1.7.0 daily mirall-1.7.0nightly20140924

**Comment by ckamm** [comment]
I could reproduce this with 1.8 but not with my time-estimation patches applied #2328

**Comment by Dianafg76** [comment]
I tested this issue, and I closed because Don't show any estimate on error
