### ISSUE TITLE
Config directory should be derived Theme::appName(), and should respect XDG settings on linux

### ISSUE THREAD

**Issue by danimo** [owncloud/client#2245]
Currently it's derived from `appNameGui()`, however the idea was that `appNameGui()` can be chosen freely. Now the character set is limited by what any of the filesystems can represent.

Also we should put the config in ~/.config instead of ~/.local

We need to write a migration task that moves the config _before_ anything that accesses the configuration is being initialized.

**Comment by guruz** [comment]
@dragotin @ogoffart @danimo Is this something that should be done together with the other config migration tasks?
Multi-account config migration https://github.com/owncloud/client/issues/3084
Moving Linux config #1409

**Comment by dragotin** [comment]
absolutely, good catch @guruz
