### ISSUE TITLE
At download the original modification time can be lost with a 1% chance

### ISSUE THREAD

**Issue by VincentvgNn** [owncloud/client#2252]
### Description
Uploading many files at one client and downloading (synchronizing) them at other clients leads to the loss of the modification date and time. It get's changed to the current date and time of the download.
The affected files are different for the clients that are downloading. So the date and time on the OC server are OK and it can be verified via the web UI as well.
This kind of change happens to about 1% of the files when simultaneously uploading and downloading many files.

For me the modification time is an important parameter that may never change until there is an intended change by one of the connected users.

### Steps to reproduce
1. Connect 3 client PC's, each with their own account to the OC server and use the web interface to let the Admin share a r/w folder with them.
The server should be somewhere else on the internet, e.g. at some web-host.
2. Copy a large amount of data (e.g. 500 MB, 3000 files, 300 folders) into the shared folder at client 1.
The copying to the shared folder at client 1 will take about 10 minutes and meanwhile the uploading to the server will start.
From the beginning on client 2 and 3 will start downloading the available files from the OC server.
3. Due to quite some interrupts, a slow server and the large amount of files things can go wrong. The whole process might take about 5 hours. Deliberately disconnecting the home network from the internet can help to generate errors, but that is often not needed.
4. Use the home network and a file comparison tool like Beyond Compare to compare all files and folders with the original non-shared folder at client 1 where the the files were copied from. Next the results in the shared folders at all 3 clients can be checked for errors. I always use an independent comparison on CRC and modification time.
If client 2 and 3 do not have the same corrupted files, then the files are OK on the server.
5. For about 1% of the downloaded files at client 2 and 3 the file modification time will be corrupted and have the time of the moment of download. The affected files are quite random and different for client 2 and 3.

Example of an equal file and a changed modtime:
![4x new mod date on win8pc - small](https://cloud.githubusercontent.com/assets/7522929/4425085/ce551ac8-45a5-11e4-92e0-fe94fa7d5e6b.png)
 
### Expected behavior
The original modification time should never be changed by ownCloud.

### Client configuration
ownCloud version: 1.6.3
Operating system: Win XP, Win 7 or Win 8
Browser: Google Chrome (or Firefox or IE11)

### Server configuration
ownCloud version: 7.0.2 (stable)
List of activated apps: default apps + encryption
External storage: no
Encryption: yes

OC server installed at a Dutch webhosting company. 4-5 GB storage.
Control via DirectAdmin and installation by using Installatron.
Own (non-shared) IP and using https.
Operating system: Linux Hosting Package
Web server: Apache
Database: MySQL
PHP version: native, 5.5.

**Comment by guruz** [comment]
Moving to 1.8 while waiting for the server guys to reply.

**Comment by VincentvgNn** [comment]
@guruz 
On January 17th I found again an example of a file where the mtime was changed to the current time.

Meanwhile I'm using OC server 7.0.4 and OC client 1.8.0.4536-nightly20150108.

On the server I can also find some files like: "filename".ocTransferId1566750467.part. These remaining partial files are not cleaned-up. Maybe this is another issue?

**Comment by PVince81** [comment]
I just raised https://github.com/owncloud/core/issues/13498 to address this on the server side.

**Comment by VincentvgNn** [comment]
@PVince81 
Thanks a lot for moving ahead with this issue.

**Comment by PVince81** [comment]
Experimental fix here: https://github.com/owncloud/core/pull/13985

**Comment by ogoffart** [comment]
Closing the client issue, it is being tracked on the server: https://github.com/owncloud/core/issues/13498

**Comment by VincentvgNn** [comment]
@ogoffart 
OK to close it here.
I hope that issue 13498 will be solved in server 8.1 after introduction of the solution discussed at
https://github.com/owncloud/core/pull/13823 .
