### ISSUE TITLE
[OS X] Finder Overlay Icons in the list view are tiny

### ISSUE THREAD

**Issue by nemphys** [owncloud/client#2257]
Just installed the latest nightly and I am excited to see sync icons finally work on OS X (even though I am running Yosemite 10.10 DP8 and even Dropbox icons don't work!)

the only problem is that the icons are tiny and I am thinking that this might have something to do with the fact that I have a *Retina* Macbook pro (though connected to an external monitor).

Screenshot attached:
![screen-shot-2014-09-29-at-4 09 04-](https://cloud.githubusercontent.com/assets/739270/4442002/7c48aa24-47da-11e4-9d48-f60df700b7bc.jpg)

**Comment by guruz** [comment]
(Note: Might be unnecessary to do when switching to https://github.com/owncloud/client/issues/2340 )

**Comment by guruz** [comment]
Let's fix this as part of #2340
