### ISSUE TITLE
[1.6.3] Large file upload to SFTP external storage gives ConnectionTimeout

### ISSUE THREAD

**Issue by ser72** [owncloud/client#2260]
**Expected Behavior**
No error

**Actual Behavior**
CONNECTION TIMEOUT error though file is uploaded

**Steps**
1) Create a Large file (4GB for instance)
2) Sync to an SFTP External storage folder 
3) The progress bar completes, however, since reassembly takes so long on this scenario, the client gives an error "Connection Timeout"

![connection_timeout](https://cloud.githubusercontent.com/assets/5174383/4475740/aca871fe-496f-11e4-9845-18af9b194728.PNG)

Watching the SFTP server, the .part file continues to grow and the file eventually is assembled:
```
root@ubuntu:/home/ser72# ls -al
total 4195180
drwxr-xr-x 3 ser72 ser72       4096 Oct  1 09:27 .
drwxr-xr-x 3 root  root        4096 Aug 21 13:54 ..
-rw-rw-r-- 1 ser72 ser72 4294967296 Oct  1 09:27 5gig
```

But the user thinks the sync failed due to Connection Timeout error.

Client logs on S3   Support/github-issues/mirall/2260

**Comment by dragotin** [comment]
Closing this as this is nothing that can now be fixed on the client side. Lets focus on the progress in owncloud/core#12097 .
