### ISSUE TITLE
[OS X] Tray icon on top of menubar on small screens

### ISSUE THREAD

**Issue by childnode** [owncloud/client#2261]
soetimes, the client icon in the traybar on Mac OS X overlays the common application text menu.

This behavior cames and goes by time but always only the owncloud icon is affected, so I assume it's a client bug, not (only) an OS X Bug.

![screenshot overlay icon bug](https://owncloud.childno.de/index.php/apps/files_sharing/ajax/publicpreview.php?x=1482&y=790&a=true&file=%252F01_Bilder%252Fpublic_issues%252FownCloud%252Fmirall-issue-2261mirall_overlayBug.png&t=831713072ab117f66757d812fbecb333&scalingup=0)

https://owncloud.childno.de/public.php?service=files&t=831713072ab117f66757d812fbecb333

**Comment by hodyroff** [comment]
Please retest in master. Is this still happening?

**Comment by childnode** [comment]
didn't see this since a while ... so for me it's fixed, perhaps it has been automatically resolved by a QT update?!
