### ISSUE TITLE
[SSL] Client does not recheck new server certificate

### ISSUE THREAD

**Issue by a-schild** [owncloud/client#2262]
owncloud server 7.0.2, owncloud client 1.6.3 on Windows 7 64 Bit and OS-X

We have a wildcard certificate for our owncloud server on *.oncloud7.ch
We did replace the certificate 14 days before it expired.
When we did replace the certificate, all owncloud clients did stop sync, with a certificate error.
After restarting the owncloud client, they worked fine again.

It looks like the client does not handle a server ssl certificate change correctly.

Here the printscreens of the "stuck" client instances:

![server1](https://cloud.githubusercontent.com/assets/1441009/4487547/5b6bce96-49fe-11e4-88ce-e267b0e7817c.png)
![server2](https://cloud.githubusercontent.com/assets/1441009/4487548/5b73b138-49fe-11e4-9f1d-5dde1ba3e9d9.png)
![server3](https://cloud.githubusercontent.com/assets/1441009/4487549/5b79f8fe-49fe-11e4-99ea-b275052bcc6b.png)
![server4](https://cloud.githubusercontent.com/assets/1441009/4487564/ba2a1e6a-49fe-11e4-9c94-85253137fbfd.png)

Here the printscreen after restarting the client:
![aserver1](https://cloud.githubusercontent.com/assets/1441009/4487566/c135f346-49fe-11e4-97ed-8f8c5481af21.png)
![aserver2](https://cloud.githubusercontent.com/assets/1441009/4487567/c162422a-49fe-11e4-8858-a7bcac2932f6.png)
![aserver3](https://cloud.githubusercontent.com/assets/1441009/4487568/c162b6ec-49fe-11e4-961d-94292938d10b.png)
![aserver4](https://cloud.githubusercontent.com/assets/1441009/4487569/c16a418c-49fe-11e4-8a93-18acdaf177ee.png)

**Comment by guruz** [comment]
@danimo Why would the certificate check dialog not pop up again?

**Comment by dragotin** [comment]
This might have been failing for the same reason as described in #3283

@a-schild would you mind re-checking with the upcoming 1.8.2 release? Thanks

**Comment by minnesotags** [comment]
This is still a bug in 1.8.4. What is the work around?

**Comment by ogoffart** [comment]
I assume this is fixed.

**Comment by stockphrase** [comment]
I just created a new self-signed cert for my site. Afterward, I assumed that my Owncloud client would complain or otherwise challenge the fact that the cert had changed. But it didn't. It accepted the new cert and did nothing to indicate this. Personally, I'd really like to know if my certs got switched out without my knowledge.

**Comment by ckamm** [comment]
@stockphrase Can you tell us more about what happened? I've just retested the 2.2 branch in the following way:
* Use mitmproxy, set it up in the client interface
* Accept mitmproxy's certificate, check that sync works
* Restart mitmproxy, generating a new certificate for it
* The desktop client pops up a new certification verification dialog and refuses to talk to the server if it's canceled.
* Restarting the client pops up the cert dialog again

**Comment by stockphrase** [comment]
Hey, I'm really sorry. I seem to have somehow missed the authorization. I
tried to reproduce this again and failed several times. So sorry for the
inconconvenience. Everything seems to be working as expected.

**Comment by ckamm** [comment]
@stockphrase Thanks for testing again, I'm glad to hear this works as intended!
