### ISSUE TITLE
1.7.0 build 3920 - 0 storage usage 

### ISSUE THREAD

**Issue by kaplandani** [owncloud/client#2269]
I've just noticed this - and I think this bug was migrated from 1.6.3 but this client shows 0 storage usage on a 90 GB sync directory.

![owncloud1 7 0](https://cloud.githubusercontent.com/assets/7215011/4504350/4d1aa87a-4ae5-11e4-8f29-a7416cd45ffb.jpg)

My 2nd computer running the same client - has it right. (different user , same server: 7.0.2 on centos 7)

**Comment by ogoffart** [comment]
I think it is the server not reporting the right value.  The logs would be usefull to confirm that.

**Comment by enoch85** [comment]
@kaplandani Or have a look in https://example.com/index.php/settings/personal

**Comment by kaplandani** [comment]
Update - I've re installed both server and new client. everything was OK up to a point, in which the client resumed the same behavior - showing ZERO instead of the actual space taken. 
This is something that relates to a specific client folder/file structure (can't tell what exactly) as it doesn't happen on other clients of mine, having even larger repositories.

**Comment by kaplandani** [comment]
What should I look for in the log (which logs ? server or client ? )

**Comment by guruz** [comment]
@kaplandani Are you still having this?

**Comment by kaplandani** [comment]
Nope. Server 8.0.4 and latest client. Correct amount reported
