### ISSUE TITLE
rename of directory with many files triggers a long sqlite update process ~O(n) and leads to inconsistent state if interrupted

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2277]
When I rename linux-master to linux-master2 (50K files) then the client takes ~6 minutes to rename files (I guess it is updating the sqlite db one-by-one as there is not network activity). 

Could this process be made to be atomic and ~O(1) instead of ~O(n) ?

Now, here is the catch and the real reason why this should be made atomic: if this process is interrupted for some reason (I quit the client) then on the next sync run after the client came back the part of files which have not been updated in sqlite are still with old path in the metadata table and the client is tries to upload these files. So we end up with two copies and possible very long upload process.

**Comment by dragotin** [comment]
This is fixed with commit f30ac492 . It only performs one SQL statement to delete all the journal entries, this is way faster.
