### ISSUE TITLE
[OS X]The option "Open folder" is not available when you skip folder configuration

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2278]
### Expected behavior
When you click on tray icon, the option "Open folder" is available 

### Actual behavior
When you click on tray icon, the option "Open folder" is not shown

### Steps to reproduce
1. Install ownCloud dektop client 1.7 beta3
2. Fill in server,user and passwords
3. Click on "Skip folders configuration"
4. Click on "Add folder", select the local folder and the remotes folders

### Server configuration
{"installed":"true","version":"7.0.0.3","versionstring":"7.0 beta 1","edition":""}

### Client configuration
Version 1.7.0 beta3 (build 1064)

Operating system: Mac 10.9.3

**Comment by guruz** [comment]
Hi Lucia ;-)

Works for me now, I had refactored the tray menu stuff some time ago maybe that fixed it.
