### ISSUE TITLE
The window displays the directory tree shows arrows in the folders without subfolder randomly 

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2279]
### Expected behavior
The foler without subfolder doesn't show the arrow

### Actual behavior
When you click on a folder without subfolder the arrows disappear sometimes.
In the screenshot you can see two folder without subfolder, one shows the arrow and the other doesn't 
![screen shot 2014-10-07 at 2 00 06 pm](https://cloud.githubusercontent.com/assets/4689430/4541883/91f6255e-4e1a-11e4-9607-b0293e7d779d.png)

### Steps to reproduce
1. Install ownCloud dektop client 1.7 beta3
2. Fill in server,user and passwords
3. Click on "Choose what to sync"

### Server configuration
{"installed":"true","version":"7.0.2.3","versionstring":"7 Beta2","edition":"enterprise"}

### Client configuration
Version 1.7.0 beta3 (build 1064)

Operating system: Mac 10.9.3

**Comment by Dianafg76** [comment]
I tried again, and the result is the same

WEB Server 
{"installed":true,"maintenance":false,"version":"8.0.3.4","versionstring":"8.0.3","edition":"Enterprise"}

Version DESKTOP 
v 1.8.1 (build 2356)

Operating system: Mac Yosemite

**Comment by dragotin** [comment]
Closing as too old.
