### ISSUE TITLE
In ♪Activity♪, keep errors until solved

### ISSUE THREAD

**Issue by chiefbrain** [owncloud/client#2282]
After certain actions (e.g. restart the client), errors are not shown anymore eventhough they are not solved.
Users should be informed at every time about the current sync status. If no indication of errors is present, the user expects a file to be present and up to date. In case of a missing file, it only irritates while working on an old copy of a file leads to further syncing problems.

I had an empty error log and a disabled "retry sync" button after restarting the client eventhough i had a lot of e-tag errors before (https://github.com/owncloud/mirall/issues/1291).

If there is a dedicated section for error messages as proposed in https://github.com/owncloud/mirall/issues/1745, I would suggest to show active errors in this section while solved ones can be moved to the history section.

**Comment by guruz** [comment]
Thanks, will be solved by https://github.com/owncloud/client/pull/4083
