### ISSUE TITLE
[OS X] Dragging settings window from toolbar miscalculates cursor position

### ISSUE THREAD

**Issue by figureone** [owncloud/client#2293]
### Expected behaviour
On OS X, clicking and dragging on the title bar will successfully drag the settings window around the screen. Clicking and dragging within the toolbar area (but not on a toolbar icon: Account, Activity, General, Network icons) should have the same effect.

### Actual behaviour
Clicking and dragging within the toolbar area will cause the window to jump upwards about 200px. If this is higher than the system menu bar, the window will flicker.

### Steps to reproduce
1. Open the owncloud settings by clicking on the toolbar icon and choosing "Settings..."
2. Click and hold anywhere in the toolbar area to the right of the toolbar icons (Account, Activity, General, Network)
3. Drag the mouse and watch the window jump to a different position.

### Client configuration
Client version: 1.6.3

Operating system: OS X 10.9.5

OS language: en-us

Installation path of client: /Applications/owncloud

**Comment by guruz** [comment]
I cannot reproduce this with the 1.8 nightly builds..
I guess the Qt update fixed it.

http://download.owncloud.com/desktop/daily/
