### ISSUE TITLE
[beta 2] Files start syncing while still being written to the local directory

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#2310]
Is there already an issue for this one?

With Mirall, files start transferring before they are fully written to the local directory. This starts the sync process, and can create an error since the entire file is not yet in the directory on the desktop.

Synchronization
- File transfer seems to start while the file is still being written to the local directory, sometimes this confuses the client
- this problem is not new in the 1.7 client

Not an ownCloud 7 issue, but consistent in a large 100MB file transfer. The client tries to instantly sync to the cloud, but it could not finish the process and it gives an error. Then when the copy is complete, sync starts and it syncs fine. Seems it worked better the second time.

Also, when you copy a folder containing several thousand files, this takes a while (20 seconds or so). The ownCloud client recognizes late how many files there are exactly, so the progress bar changes the end state again and again.

**Comment by ogoffart** [comment]
Closing old issue that is probably fixed.
