### ISSUE TITLE
[1.7.0] OS X: PKG-based installer causes UX regression during update

### ISSUE THREAD

**Issue by danimo** [owncloud/client#2316]
As of 1.7, we have a pkg-based installer, rather than providing the app bundle in a disk image. We opted for a pkg-based installer because it seemed the simplest way of installing the extensions for Finder.

However, this affects update-scenarios:

Before: Updater downloads update and silently installs new version (might need admin password)
Now: Updater downloads update and launches pkg installer. User interaction required.

Alternatives:

* Accept complication
* Extend Sparkle's Package installer to support silent installation (@guruz would need to take a look)
* Switch back to dmg's. Find other way of installing the extensions.

/cc @craigpg

**Comment by guruz** [comment]
Closing this for now as no one anymore complained.
