### ISSUE TITLE
Connection timeout / syncronisation restarts but fails again and again

### ISSUE THREAD

**Issue by Rocologo** [owncloud/client#2323]
This bug is the same as #1893  (https://github.com/owncloud/mirall/issues/1893)

I got the errors over and over again on the same files... 

"Connection timeout"
"Operation canceled"
"Operation canceled"

While looking for a solution I noticed #1893 which is closed but never fixed. Developer Guruz asked to test if "enabling bandwidth" changed anything. And the answer is yes. It gave me a workaround, and now my syncronisation is running smoothly again. (with limited bandwidth)

**Comment by guruz** [comment]
Would have been improved by https://github.com/owncloud/client/issues/2976
