### ISSUE TITLE
Inconsistent icons -- tray vs. client GUI

### ISSUE THREAD

**Issue by AloisMahdal** [owncloud/client#2327]
Today I logged in to my machine after leaving it a few days alone and found owncloud client in a strange erroneous state:
 *  icon in sys tray (aka notification area) showed a gray-ish bubble with three dots as when connecting,
 *  in main window, there was a red error something like "this configuration cannot be used now",
 *  but both account icons showed green status.

Unfortunately I don't have screenshot / log --- hopefully the description will be enough for you to be able to guess how to reproduce the error.

One thing I did do before looking at the icon was that immediately as I came to the laptop I disconnected ethernet cable, having the system rely on wireless. (I keep it on eth+wlan when away as the wlan keeps failing lately.)

**Comment by AloisMahdal** [comment]
Hmm, sorry, I don't remember seeing it from that time. I was always using the Debian client. Also I don't connect via eth+wlan anymore, so if it did matter, I'm not likely to come across this issue.

**Comment by ogoffart** [comment]
owncloud 1.8 should be better.
