### ISSUE TITLE
time estimates shows wrong values

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2328]
Time estimates are very confusing in 1.7. See attached screenshot.

Several issues:

Estimated total time is smaller then estimated download of the current file. I guess it has to do with the parallel download.

Also the time estimate for the current file refreshes very quickly (and changes all the time=>completely unreliable) while the total time refreshes every second and seems more stable and reliable.

Also, Occasionally I saw some time estimates like 1y10month to complete (for very large directories, ~100K files). That was clearly wrong because in reality it took 1 hour or so.

![image](https://cloud.githubusercontent.com/assets/621965/4688503/abdd9bd0-567d-11e4-9e43-0cd9cb8ffe00.png)

After a while both time estimates got closer (still total<current file download time):

![image](https://cloud.githubusercontent.com/assets/621965/4688531/8c241fc0-567e-11e4-9d43-56d81627dbe9.png)

**Comment by ckamm** [comment]
Initial work for this has gone into the 'timing' branch.

**Comment by dark-eye** [comment]
I  found  a bug  in my implementation that  if  the user  connection  was slow for a long time  and  then it sped back up  it will  show  a very long estimate, for example:

if a user  transfer a 100Mb  file  and  it internet  slowed to 8kbs  for an hour  and then sped up  back again to 2Mbs   it will show   more then an hour up until 75% of the file was transferred. 

the reason for that it look at the past and see that it took 1 hour to transfer 35Mb so it should take 2.5 more  to transfer the rest  (even though  with 2mb/s it should actually take less then a minutes...

**Comment by ckamm** [comment]
Merged into master branch. There's a lot of improvements that could still be done to the time estimation code...

**Comment by Dianafg76** [comment]
I tested the bug, and the time estimates shows wrong values. So I close the bug
