### ISSUE TITLE
Client Install Fails on CentOs 7 due to dependency on libQtWebKit.so.4()(64bit)

### ISSUE THREAD

**Issue by Scriptgadget** [owncloud/client#2341]
### Expected behaviour
I expected to be able to install the Owncloud Client on CentOs 7 by following the CentOs 7 instructions at
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client (you'll find the instructions under the "Fedora" category rather than "CentOs" for some reason)

### Actual behaviour
yum install owncloud-client failed with a broken dependency on libQtWebKit.so.4()(64bit)

### Steps to reproduce

With a fresh CentOs 7, 64 Bit install, follow the instructions at
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

Which are as follows:

1. cd /etc/yum.repos.d/
2. wget http://download.opensuse.org/repositories/isv:ownCloud:desktop/CentOS_7/isv:ownCloud:desktop.repo
3.     yum install owncloud-client

### Server configuration

Operating system: N/A

Web server: N/A

Database: N/A

PHP version: N/A

ownCloud version: N/A

Storage backend: N/A

### Client configuration
Client version: owncloud-client.x86_64 0:1.6.3-20.1

Operating system: CentOs 7 

OS language: English

Installation path of client: Failed

### Logs
With the following result:

    yum install owncloud-client
    Loaded plugins: fastestmirror, langpacks
    Loading mirror speeds from cached hostfile
     * base: mirror.anl.gov
     * centosplus: mirror.supremebytes.com
     * extras: mirror.hmc.edu
     * updates: centos.lax.us.glomirror.com.au
    Resolving Dependencies
    --> Running transaction check
    ---> Package owncloud-client.x86_64 0:1.6.3-20.1 will be installed
    --> Processing Dependency: libowncloudsync0 = 1.6.3 for package: owncloud-client-1.6.3-20.1.x86_64
    --> Processing Dependency: owncloud-client-l10n for package: owncloud-client-1.6.3-20.1.x86_64
    --> Processing Dependency: libqtkeychain.so.0()(64bit) for package: owncloud-client-1.6.3-20.1.x86_64
    --> Processing Dependency: libowncloudsync.so.0()(64bit) for package: owncloud-client-1.6.3-20.1.x86_64
    --> Processing Dependency: libocsync.so.0()(64bit) for package: owncloud-client-1.6.3-20.1.x86_64
    --> Processing Dependency: libQtWebKit.so.4()(64bit) for package: owncloud-client-1.6.3-20.1.x86_64
    --> Running transaction check
    ---> Package libowncloudsync0.x86_64 0:1.6.3-20.1 will be installed
    --> Processing Dependency: libQtWebKit.so.4()(64bit) for package: libowncloudsync0-1.6.3-20.1.x86_64
    ---> Package libqtkeychain0.x86_64 0:0.4-4.1 will be installed
    ---> Package owncloud-client.x86_64 0:1.6.3-20.1 will be installed
    --> Processing Dependency: libQtWebKit.so.4()(64bit) for package: owncloud-client-1.6.3-20.1.x86_64
    ---> Package owncloud-client-l10n.x86_64 0:1.6.3-20.1 will be installed
    --> Finished Dependency Resolution
    Error: Package: libowncloudsync0-1.6.3-20.1.x86_64 (isv_ownCloud_desktop)
               Requires: libQtWebKit.so.4()(64bit)
    Error: Package: owncloud-client-1.6.3-20.1.x86_64 (isv_ownCloud_desktop)
               Requires: libQtWebKit.so.4()(64bit)
     You could try using --skip-broken to work around the problem
     You could try running: rpm -Va --nofiles --nodigest

**Comment by jnweiger** [comment]
cool. closing.

**Comment by labkode** [comment]
Same error here:

```
[root@amalia yum.repos.d]# yum install owncloud-client
Failed to set locale, defaulting to C
Loaded plugins: fastestmirror, langpacks
Loading mirror speeds from cached hostfile
 * base: ftp.cixug.es
 * extras: ftp.cixug.es
 * updates: ftp.cixug.es
Resolving Dependencies
--> Running transaction check
---> Package owncloud-client.x86_64 0:2.0.1-3.1 will be installed
--> Processing Dependency: libowncloudsync0 = 2.0.1 for package: owncloud-client-2.0.1-3.1.x86_64
--> Processing Dependency: owncloud-client-l10n for package: owncloud-client-2.0.1-3.1.x86_64
--> Processing Dependency: libqtkeychain.so.0()(64bit) for package: owncloud-client-2.0.1-3.1.x86_64
--> Processing Dependency: libowncloudsync.so.0()(64bit) for package: owncloud-client-2.0.1-3.1.x86_64
--> Processing Dependency: libocsync.so.0()(64bit) for package: owncloud-client-2.0.1-3.1.x86_64
--> Processing Dependency: libQtWebKit.so.4()(64bit) for package: owncloud-client-2.0.1-3.1.x86_64
--> Running transaction check
---> Package libowncloudsync0.x86_64 0:2.0.1-3.1 will be installed
--> Processing Dependency: libQtWebKit.so.4()(64bit) for package: libowncloudsync0-2.0.1-3.1.x86_64
---> Package libqtkeychain0.x86_64 0:0.5-4.1 will be installed
---> Package owncloud-client.x86_64 0:2.0.1-3.1 will be installed
--> Processing Dependency: libQtWebKit.so.4()(64bit) for package: owncloud-client-2.0.1-3.1.x86_64
---> Package owncloud-client-l10n.x86_64 0:2.0.1-3.1 will be installed
--> Finished Dependency Resolution
Error: Package: owncloud-client-2.0.1-3.1.x86_64 (isv_ownCloud_desktop)
           Requires: libQtWebKit.so.4()(64bit)
Error: Package: libowncloudsync0-2.0.1-3.1.x86_64 (isv_ownCloud_desktop)
           Requires: libQtWebKit.so.4()(64bit)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

The solution is to install Qt first ?

**Comment by RealRancor** [comment]
@labkode 

> and expect Users to pull their qtwebkit directly from epel, not from us.

from three comments above: https://github.com/owncloud/client/issues/2341#issuecomment-60004715
