### ISSUE TITLE
On second launch: Tell first instance to show settings dialog (via QSingleApplication socket)

### ISSUE THREAD

**Issue by strugee** [owncloud/client#2343]
If the user already has Mirall open, but doesn't know it, they may launch it for a second time and find that nothing happens. This is a very confusing experience.

One of two things should happen at this point:

* Open the ownCloud folder
* Open the Mirall settings window

This provides some feedback that the app is responding to the user's request.

**Comment by jturcotte** [comment]
Should already be fixed, see #2374

**Comment by ogoffart** [comment]
Fixed
