### ISSUE TITLE
When trying to sync a long folder desktop client gets blocked. 

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/client#2345]
### Steps to reproduce
1. Create a folder of 255 characters in the synced directory

### Expected behaviour
The directory shouldn't be created in the server because it's name it's too long.
If the server has a folder so long it would be discarded if it is too long.

### Actual behaviour
Directory is created in the server.
Desktop client gets blocked trying to sync it. 
The activity tab stops working, not showing any activity.

### Server configuration
**Operating system**:
 (Ubuntu)

**Web server:**
nginx/1.4.6

**Database:**

**PHP version:**
PHP/5.5.9-1ubuntu4.4

**ownCloud version:** (see ownCloud admin page)
{"installed":"true","version":"7.0.3.0","versionstring":"7.0.3 RC1","edition":"enterprise"}

**Are you using encryption:** no

### Client configuration
mac version 1.7.0 1148
windows version 1.7.0 4001

**Operating system:**
Mac OS 1.9.5
Windows 7

#### ownCloud log (data/owncloud.log)
https://gist.github.com/SergioBertolinSG/26a8056c463579988399#file-log_255_folder_download-txt

**Comment by ogoffart** [comment]
Closing because tracked in https://github.com/owncloud/core/issues/11690
