### ISSUE TITLE
[1.7.0 beta4] [OS X] Client does 2 full sync runs at start with 30 sec space, only then switches to 5 min interval

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2352]
Possibly we need to store the get&root Etag (e.g. could we get it from the ```csync_update``` run?)

**Comment by guruz** [comment]
With #2507 it is easily possible to get the root etag from the DiscoveryJob instead and thus avoiding the next sync.

**Comment by lmaestro** [comment]
It is fixed in version 1.8.0 build (1941).
