### ISSUE TITLE
[1.7.0 beta3] [WIN] Uninstall owncloud client make explorer crash

### ISSUE THREAD

**Issue by Prev-I** [owncloud/client#2353]
### Steps to reproduce
1. Install client beta 3
2. Uninstall client beta 3
3. Reboot

### Expected behaviour
When uninstalling the client all libraries must be unregistered and removed from system

### Actual behaviour
When uninstalling owncloud 1.7.0 beta3 a dll remain inside installation directory:
OCOverlays_x64.dll
The library is still registered in windows and loaded by explorer which start crashing randomly with error code  0xc0000005 in ntdll.dll
It's impossible to delete this file unless you do:
regsvr32 /u OCOverlays_x64.dll
Deleting the unregistered file resolve any issues in explorer

### Client configuration
Client version: 
1.7.0 beta3

Operating system: 
window 8

OS language: 
en-US

Installation path of client: 
C:\Programs File\Owncloud

**Comment by danimo** [comment]
Please retest with http://download.owncloud.com/desktop/daily/owncloud-1.8.0.4661-nightly20150129-setup.exe

**Comment by lmaestro** [comment]
I can't reproduce it the latest version 1.8, if anyone is able to reproduce please reopen it.

**Comment by ToeiRei** [comment]
Confirmed clean for Win7 32/64 and Win8.1 32/64.
