### ISSUE TITLE
1.7.0-beta4: exponential backoff for slowly written files?

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2355]
As an improvement to the solution implemented in #2210 I would propose to slow down the rate at which the upload of slowly written file is attempted. I have a wget running for 10 minutes now or so and every 4 seconds there is a "discover/upload attempt" loop - it heats up the CPU.

What about slowing down with time the retry rate (exponentiall backoff)? So for example during first minute it can have the current rate but then only every 30 seconds and maybe only every 2 minutes or so if it takes longer.

Also, my sync directory is rather small now, but wouldn't the "discover" phase try to scan all my files quasi-constantly if my sync folder was 10K files or so?

![image](https://cloud.githubusercontent.com/assets/621965/4725887/492b6cfa-595d-11e4-9630-f10696594a25.png)

![image](https://cloud.githubusercontent.com/assets/621965/4725956/e27e3afe-595d-11e4-99ca-0847c89fc37b.png)

**Comment by ckamm** [comment]
@lmaestro You can test this in several ways:
 * download a big file into a sync folder - during the downloads there should be increasingly long delays between sync runs (up to 1 min)
* after a long sync, there should be some pause before the next sync: copy a file into sync dir that takes about 1min to upload, copy another file in there during the upload phase. There should be about 12s pause between the first big upload sync and the second sync

**Comment by lmaestro** [comment]
I can't reproduce this issue in the latest version1.8.0-nightly20150122 (build 1925). If anyone is able to reproduce, please reopen it. Thx.
