### ISSUE TITLE
Remove csync_set_module_property, we can use the CTX directly nowadays

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2360]

**Comment by ckamm** [comment]
Maybe it's time to drop the legacy propagator entirely?

**Comment by guruz** [comment]
I attempted to do this but now agree with @ckamm 
Let's drop the legacy propagator for 2.2

**Comment by guruz** [comment]
https://github.com/owncloud/client/tree/kill_legacy_propagator
It disables the bandwidth limiting UI for Qt < 5.3.3

FYI @dragotin @ogoffart 

Waiting for the OK to have this in 2.1 actually

**Comment by guruz** [comment]
kill_legacy_propagator is merged
