### ISSUE TITLE
[Windows 1.7.0beta4] Desktop client isn't able to unlock synced folder while modifying account.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/client#2379]
### Steps to reproduce
1. Have a owncloud session correctly configured
2. Try to make a clean sync with a different user in the same directory which owncloud desktop was syncing.

### Expected behaviour
A clean sync starts in the same directory for a different user.

### Actual behaviour
Desktop client is unable to unlock the synced folder, even with all windows closed.

### Server configuration
**Operating system**:
 (Ubuntu)

**Web server:**
nginx/1.4.6

**Database:**

**PHP version:**
PHP/5.5.9-1ubuntu4.4

**ownCloud version:** (see ownCloud admin page)
{"installed":"true","version":"7.0.3.0","versionstring":"7.0.3 RC1","edition":"enterprise"}

**Are you using encryption:** no

### Client configuration
Windows version 1.7.0beta4

**Operating system:**
Windows 7

Client logs:
https://gist.github.com/SergioBertolinSG/0c73776e7f6c4f6d2697#file-logs_windows_lock_explorerexe-txt

Screenshot:
![screenshot_windows_locked](https://cloud.githubusercontent.com/assets/9048796/4754251/d790f7f2-5abc-11e4-9b48-6605173b4ec7.png)

**Comment by lmaestro** [comment]
Fixed in version 1.8.0-nightly20150202 (build 4670).
