### ISSUE TITLE
Translate cross-sync-folder Moving/Copying to a server side move

### ISSUE THREAD

**Issue by etiess** [owncloud/client#2384]
### Steps to reproduce
1. Set up two synced folders in Mirall: testA and testB
2. Put some files in testA
3. Let the sync be finished
4. Move files from testA to testB
### Expected behaviour

Mirall should detect that it's a move, and make this change without a lot of upload/download

I have the impression that this is done correctly when it is between subfolders of a synced folder. For example, test0 is set up in Mirall. testA and testB are subfolders of test0. Moving files from testA to testB doesn't trigger any upload. But it is still slow though, I don't understand if it download/upload something or not?
### Actual behaviour

Files are deleted in testA and then uploaded from testB
### Server configuration

Operating system: Ubuntu 14.04
Web server: Apache
Database: MySQL
ownCloud version: 7.0.2
### Client configuration

Client version: 1.6.4
Operating system: Windows 8.1
### Note

I read https://github.com/owncloud/mirall/issues/2062 but I have the impression that it's a different issue because in this current case, nothing is done on the web interface nor with shared folders.

**Comment by DeepDiver1975** [comment]
out of scope
