### ISSUE TITLE
Fix update documentation for Win64

### ISSUE THREAD

**Issue by r2evans** [owncloud/client#2398]
### Expected behaviour
Documentation should provide all possible registry locations (for Windows).

It might be nice to provide an option either in the config file or in the app itself to disable auto-updates, though I understand if you want to make it difficult to (accidentally?) disable them.

### Actual behaviour
The two suggested registry locations are not found on my OS (win7_64 pro):

* `HKEY_LOCAL_MACHINE\Software\ownCloud\ownCloud`
* `HKEY_LOCAL_MACHINE\Software\Policies\ownCloud\ownCloud`

One location (that appears to work, at least for me) is:

* `HKEY_LOCAL_MACHINE\Software\Wow6432\ownCloud\ownCloud`

There is no entry under `...\Policies` that I can find on my computer.

### Steps to reproduce
1. Open `regedit.exe`.
2. Search under `HKEY_LOCAL_MACHINE\Software` for ownCloud.

**Comment by carlaschroder** [comment]
Someone who speaks Windows needs to handle this-- it's been ages since I mucked with group policies and the windows Registry. I can review and test the solution.

**Comment by carlaschroder** [comment]
Closing; somewhere along the way the docs got updated.
