### ISSUE TITLE
[1.7.0-rc1]Error downloading <path_on_owncloud_server> - server replied: internal server error

### ISSUE THREAD

**Issue by PeterPablo** [owncloud/client#2401]
Hi!
I am running OwnCloud 7.0.2 on my Raspberry PI and the data is stored on an external HDD. The webinterface runs without problems and now I wanted to give the Mirall client a try on Mac OS X Yosemite. I pulled the current release candidate and would like to report the following problem:

My initial synchronisation is still running and files are happily synced TO my Raspberry PI. The log in the Mirall window is unfortunately full of errors:
'''Error downloading <path_on_owncloud_server> - server replied: internal server error'''
Though not all files give this error, others are synced without problem.

I checked my logs in apache. "error.log" is clean and "ssl_access.log" gives me:
```
IP - USER [26/Oct/2014:11:13:43 +0100] "PUT /owncloud/remote.php/webdav/PATH/image-21_4.jpg HTTP/1.1" 201 1028 "-" "Mozilla/5.0 (Macintosh) mirall/1.7.0"
IP - USER [26/Oct/2014:11:14:17 +0100] "PUT /owncloud/remote.php/webdav/PATH/image-22_3.jpg HTTP/1.1" 500 1077 "-" "Mozilla/5.0 (Macintosh) mirall/1.7.0"
```

As you can see "image-22_3.jpg" return error 500, whereas the very similar file "image-21_4.jpg" goes through without a problem. This matches the log in the Mirall Client window.

I then checked if both files were uploaded by looking directly on the storage. Both files were uploaded successfully (after downloading over a network share I can open them), though the "failed file" lost it's creation and modification timestamps on the Raspberry PI, whereas the file without problem has the original timestamps.

I consider this a bug. Hopefully my report gives you a starting point for investigating.

Thank you!

**Comment by guruz** [comment]
Please track https://github.com/owncloud/client/issues/2743
