### ISSUE TITLE
[1.7RC1] Mac install should restart client after successful install

### ISSUE THREAD

**Issue by craigpg** [owncloud/client#2410]
Install went fine, but when it was done, my 1.6.x client was still running.

I quit ownCloud, restarted it and then it was running 1.7.

I would expect the install to restart ownCloud at the end of the install process.

**Comment by guruz** [comment]
From 2.0, we're now opening Finder and select the new .app for the user. To be honest I believe this is even better UX than to just blindly run it because the user sees where he can always find it..
