### ISSUE TITLE
Enable the Windows desktop client shortcut icons to be created for all users during the installation

### ISSUE THREAD

**Issue by gig13** [owncloud/client#2413]
Allow the shortcuts for the Windows desktop clients to be installed for all users, since presently they are created for the specific user that installs the client.

@danimo - Thanks!
https://github.com/owncloud/mirall/pull/2412

**Comment by MorrisJobke** [comment]
@danimo Are there already builds that include your PR to be able to test the PR or isn't it ready yet

**Comment by danimo** [comment]
Implemented

**Comment by gig13** [comment]
@danimo @MTRichards 
Any expectation I can set for the release date on 1.8? One month, 2 months...?

**Comment by MTRichards** [comment]
Something like that, yes. I know we are working on a sharing api bug fix, not certain where we are with that and overall testing of 1.8 in the RC and beta cycle.

**Comment by lmaestro** [comment]
Fixed in version 1.8-nightly 20150302 (build 4798). It will be included in version 1.8 beta2
