### ISSUE TITLE
Certificate error after the server certificate renew

### ISSUE THREAD

**Issue by Rudi1977** [owncloud/client#2416]
After the update the certificate on the server I get the same error when the client appears: 

---

Warnungen zur aktuellen SSL-Verbindung
Das Zertifikat des Ausstellers eines lokal gefundenen Zertifikats konnte nicht gefunden werden
Das oberste Zertifikat der Zertifizierungsstelle ist für diesen Fall nicht vertrauenswürdig
## Keines der Zertifikate konnte verifiziert werden

Warnings about the current SSL connection 
The certificate of the issuer of the certificate could not be found locally found 
The top CA certificate is not trusted for this case 
## None of the certificates could be verified 

My Server: Debian Linux, apache 2.2 with startssl class 2 certificate 
ownCloud: 7.0.2 
ownCloud client (osx) 1.6.4 (Build 1195) 
or 
ownCloud client (win) 1.5.0 (Build 1913) 

The website does not show any errors with the certificate.
What can I do?

**Comment by atrias** [comment]
I have the same problem with my owncloud install and startcom certificate.
I have checked with ssllabs and all tests are fine (I get an A rating).

error is this:
Warnings about current SSL Connection:
The issuer certificate of a locally looked up certificate could not be found
The root CA certificate is not trusted for this purpose

There is option to check to "trust certificate anyway" but I believe that having a proper certificate should not produce this warning and the client should not require to force some certificate trust.

Owncloud 8.0.3 on debian wheezy
owncloud-client-1.8.1-5.1.x86_64 on Fedora 20

**Comment by atrias** [comment]
Hello again
After updating today to
owncloud-client-1.8.1-6.1.x86_64
the problem described above (warning for startcom certificate) is solved

(There were also some updates for Qt so maybe that was what solved the problem - I don't really know)
