### ISSUE TITLE
Hide *.tmp created by PowerPoint(?) via default ignore list

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/client#2424]
I had some trouble with a powerpoint file. Powerpoint is creating *.tmp files and this results in an error message in mirall because it is not accessable. I could solve it via adding *.tmp to the ignore list but it should be in the list by default.

**Comment by lmaestro** [comment]
Now, files *.tmp are shown in the list of ignored files but they are not selected. So this files are not going to be removed if you don't enable the checkbox.
This enhancement is included in version 1.8.0-nightly 20150125 (build 1939).

**Comment by guruz** [comment]
@pierrejochem Do you remember if those files are hidden files?

**Comment by pierrejochem** [comment]
I Think they are not, but i will try it tomorrow

**Comment by pierrejochem** [comment]
![2015-05-06_09-20-45](https://cloud.githubusercontent.com/assets/9192953/7488952/356c7d1c-f3d1-11e4-940b-6804d01bbeb5.png)

It is hidden and looks like this with Powerpoint 2013

**Comment by pierrejochem** [comment]
It I press save then this files are generated and an error occoured

![2015-05-06_09-22-24](https://cloud.githubusercontent.com/assets/9192953/7488977/8cfe77c4-f3d1-11e4-8f19-28039425ee6e.jpg)

**Comment by pierrejochem** [comment]
05-06 09:26:06:345 0x584a7b8 OCC::SocketApi::fileStatus: OO File  "C:/Users/jochem/sysmexCloud/A8605745.tmp"  is not existing
05-06 09:26:06:345 0x584a7b8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\jochem\sysmexCloud\A8605745.tmp"

**Comment by pierrejochem** [comment]
![2015-05-06_09-30-28](https://cloud.githubusercontent.com/assets/9192953/7489035/8f0c9572-f3d2-11e4-8738-9b43f3ec437f.png)

The build i used

**Comment by pierrejochem** [comment]
@guruz: I hope that helps you a bit

**Comment by guruz** [comment]
@pierrejochem Are you sure they are hidden? :)
Explorer shows hidden files with grey text (vs black text)

**Comment by pierrejochem** [comment]
The tmp file is not hidden

**Comment by guruz** [comment]
@pierrejochem We removed the exclude for now again (for 1.8.3) because of other issues.
You'll need to add it to your list manually..

**Comment by pierrejochem** [comment]
OK
