### ISSUE TITLE
[1.7.0-rc1] Unnecessary reupload of files

### ISSUE THREAD

**Issue by etiess** [owncloud/client#2431]
### Expected behaviour

Files which are already synced should not be uploaded again
### Actual behaviour

Files which were successfully synced with 1.6.4 (and then present both on desktop and server) are uploaded again. In a massive way (more than 600 MB for me)
### Steps to reproduce
1. Sync several folders with Mirall 1.6.4
2. Update to 1.7.0-rc1
3. Launch the sync
### Server configuration

Operating system: Ubuntu 14.10
Web server: Apache
Database: MySQL
ownCloud version: 7.0.2
### Client configuration

Client version: 1.7.0-rc1
Operating system: Windows 8.1
### Logs

Mirall log for one of the files which is re-uploaded: https://gist.github.com/etiess/63d5da5bd1a9007575d7

(I stopped Mirall while it was uploading it)

**Comment by etiess** [comment]
@ckamm @ogoffart I know this is an old issue, but I'm using 1.8 now, and as a new time change will happen this WE, I wonder if there's a risk to see this kind of issue come back?

**Comment by ogoffart** [comment]
We made some fixes, normaly if there is only one hour ±1 second difference, we do not sync the files again. The problem was hapenning on FAT file system. NTFS and other file system should work fine.

**Comment by etiess** [comment]
@ogoffart OK, I hope so ;)
But I confirm that this issue happened for me on a NTFS system, not FAT.
