### ISSUE TITLE
No documentation on how to remember password on Ubuntu

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/client#2434]
There is no documentation at all how I can tell Ubuntu to remember the password. Each time Ubuntu boots along with the owncloud client, it asks me for the password.

I ready vague comments about a keyring something, googled a lot, but nothing helped. What is exactly needed to make Ubuntu remember the password?

**Comment by leggewie** [comment]
Generally, it is a terrible idea to mix distro packages and those provided by upstream on a system you use productively, especially if packages are being built using the OpenSUSE build system.  All the packages I've seen so far that were using OBS and targeting Ubuntu or Debian were terribly broken and WILL screw up your system.  I hate to say it, but this includes the packages provided by upstream owncloud.  I maintain packages in Debian directly and I can tell you it needs skill and knowledge.  How do you expect upstream to know all the different distributions and their policies well enough not to screw up?  Are they actively and routinely coordinating with downstream packaging to prevent problems for users for all the different distributions out there?  Frankly, that's impossible.  Packaging and coding require a different skillset and it only seldomly overlaps in my experience.  My advice: stick with official packages and patch packages in a PPA for example if you know what you are doing.
