### ISSUE TITLE
Files from FAT32 volume are uploaded again after Daylight Saving Time (DST) change

### ISSUE THREAD

**Issue by VincentvgNn** [owncloud/client#2438]
### Description

I have 3 clients (3 different accounts) sharing a folder with 1200 files (400 MB).
- client 1 is on a Win 7 PC
- client 2 is on a Win 8.1 PC
- client 3 is on a Win XP PC and uses an USB stick for storing the files (FAT32 file system !)

In the weekend of the recent Daylight Saving Time (DST) change by 1 hour, client 3 got sync problems. After a restart of the OC client it started syncing again, i.e. it started uploading again all 1200 files  from client 3 to the OC server. Next client 1 and 2 started downloading all files that were considered by client 3 as "changed".

I further analysed the log files and found that the problem is in the way of storing the modification time as a local time on FAT32 volumes.
After the DST change OC detects a 1 hour change and doesn't ignore the 1 hour +/- 2 secs difference in the same way as many sync systems do to prevent these problems.

### Steps to reproduce
1. Wait until the next DST change ;-))
2. Change the time zone from CET to EET to get similar effects (similar but not all the same as a 1 hour DST offset).

### Expected behavior
After a DST change OC should ignore the 1 hour +/- 2 secs difference in modification time in the same way as many sync systems do.
This should at least be an option that can be selected by a check box in the General Settings.

### Client configuration
ownCloud version: 1.6.4
Operating system: Win XP, Win 7 or Win 8
Browser: Google Chrome (or Firefox or IE11)

### Server configuration
ownCloud version: 7.0.2 (stable)
List of activated apps: default apps + encryption
External storage: no
Encryption: yes

OC server installed at a Dutch webhosting company. 4-5 GB storage.
Control via DirectAdmin and installation by using Installatron.
Own (non-shared) IP and using https.
Operating system: Linux Hosting Package
Web server: Apache
Database: MySQL
PHP version: native, 5.5.

**Comment by VincentvgNn** [comment]
@ogoffart
I'm very sorry, but we have to reopen this issue.

I tested on OC version 1.8.0.4536-nightly20150108 and could verify that the +/- 3600 sec mtime ignorance works as expected.

But there is still the problem of "upload after download" when using a FAT32 storage.
About 50% of the files downloaded on the FAT volume are uploaded again because they get the mtime increased by +1 sec.
I expected that FAT32 had a 10 msec time resolution. But that's only true for the ctime. For the mtime the resolution is 2 sec! 
The best background stories can be found on: https://corengen.wordpress.com/2010/03/22/comparing-file-timestamps-on-ntfs-and-fat32/
http://en.wikipedia.org/wiki/File_Allocation_Table

So the mtime difference ignorance for OC in case of FAT32 should be +3600 sec, -3600 sec, +1 sec, +3601 sec and -3599 sec.

**Comment by ogoffart** [comment]
How exactly did you test?  By changng your timezone?

**Comment by VincentvgNn** [comment]
@ogoffart 

I changed the timezone on the Win 8.1 PC from the current UTC +01:00 to +02:00 (E.Europe), +03:00 (Moscow), +00:00 (London), -01:00 (Azores). At 1 hour difference there is no re-upload of all FAT stored files. At 2 hours or more difference all files will be re-uploaded due to the detected mtime difference.

The 1 sec difference problem arises independent from the time zone change.
Odd modification time values for the secs are changed to even values on the FAT32 formatted volume.
In a rough test on a FAT volume I could find files with an odd number of seconds for the creation time, but all had an even number of seconds for the modification time.

**Comment by VincentvgNn** [comment]
@ogoffart
I had a look at your new code.
If "a" is the database mtime and "b" is the FAT returned mtime, then for "b-a" the following values should be ignored for detecting it as a changed mtime: 0, +1, +3600, +3601, -3600, -3599 (6 cases)
I think that in your code does not ignore the +1 sec difference.
The nice formula with the abs values also let's pass -3601 and +3599. That's not needed because FAT rounds up by +1 in case of odd mtime values.
Without knowing the exact syntax, efficient coding and the correct order of "a" en "b" I suggest the following for the lines 115 and 119: 
```if (difftime(a, b) == 0 or 1 or 3600 or 3601 or -3600 or -3599) then true else false```

**Comment by ogoffart** [comment]
We want to take in account the changes if there is one second difference.

Normaly, the time should not change by one second, even if the precision is less than one second, because the rounding is always done the same way.

**Comment by VincentvgNn** [comment]
@ogoffart 
Thanks a lot!
Please give me a sign when I can test it in a next nightly client version.

The additional +/- 3600 sec and +1 sec ignorance is only for the sake of external HDD's and USB sticks which are FAT formatted by default.  It's up to you whether you "unhide" this "feature" by putting it under a check box in the user "General" menu. Personally I'm not fully confident about ignoring the +1 sec for all users and giving away some mtime precision.

**Comment by VincentvgNn** [comment]
@ogoffart
What will be the OC solution/policy?
FAT32 possible without problems yes or no?
If yes, can you then reopen this issue? Else it will disappear and never be solved.

I need to decide whether my clients can use standard FAT32 USB sticks or whether I should supply them NTFS formatted USB sticks.

**Comment by ogoffart** [comment]
FAT32 is only working with 1.8.  We were planing to release it earlier but it did not happen.

**Comment by VincentvgNn** [comment]
@ogoffart 
I tested FAT32 storage on client 1.8.0 (build 4847) and server 8.0.2.
I also tested the most recent client 1.8.0 (nightly build 4855).
The re-uploading due to rounding up the odd mtime seconds to even seconds is still there.

What can I expect on this issue?

**Comment by VincentvgNn** [comment]
@ogoffart 
I opened issue #3103 for the problem of the +1 sec mtime change on FAT32 and exFAT.
The DST problem is solved by accepting +3600 and -3600 secs for the mtime as a non-changed file.
Thanks for that.
