### ISSUE TITLE
Make sure you get a popup when you unzip the zip file inside the desktop client, saying that all the extracted files have synched

### ISSUE THREAD

**Issue by luciamaestro** [owncloud/client#2440]
### Expected behavior

 Make sure you get a popup saying that all the extracted files have synched and you can decide what to do.
### Actual behavior

There are not popup and when you remove it, you receive an infinite list of errors, one per file.
### Steps to reproduce
1. Open the desktop client
2. Create a zip file with many internal folders and files
3. Copy the zip file to the Desktop Client folder
4. Unzip the zip file inside the Desktop Client folder 
5. Delete the unzip folder 
### Server configuration

{"installed":"true","version":"7.0.3.1","versionstring":"7.0.3 RC2","edition":""}
### Client configuration

ownCloud Client Version 1.7.0-nightly20141103 (build 1315)

Operating system:Mac 10.9.5
### Logs

```
11-04 10:26:39:390 0x104a1fe30 socketapi.cpp:496 OO File  "/Users/lmaestro/owncloud-servers/stable7/intralinks/100folders1000docs/82/example12.file"  is not existing
11-04 10:26:39:390 0x104a1fe30 socketapi.cpp:320 SocketApi:  Sending message:  "STATUS:ERROR:/Users/lmaestro/owncloud-servers/stable7/intralinks/100folders1000docs/82/example12.file"
11-04 10:26:39:390 0x104a1fe30 socketapi.cpp:372 void Mirall::SocketApi::command_RETRIEVE_FILE_STATUS(const QString &, SocketType *) "/Users/lmaestro/owncloud-servers/stable7/intralinks/100folders1000docs/11/example53.file"
11-04 10:26:39:390 0x104a1fe30 socketapi.cpp:496 OO File  "/Users/lmaestro/owncloud-servers/stable7/intralinks/100folders1000docs/11/example53.file"  is not existing
```

**Comment by Dianafg76** [comment]
Still reprodution:
###Version Desktop
Version 1.8.1.2298

Web server:
{"installed":true,"maintenance":false,"version":"8.0.3.2","versionstring":"8.0.3 RC3","edition":"Enterprise"}
Checked with a server with permanent redirection

**Comment by ogoffart** [comment]
Closing old issue.
