### ISSUE TITLE
1.6.4: activity log does not show the operation type (download/upload/rename/delete)

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2443]
See screenshot. Is this a problem with 1.6.4 or with client branding of 1.6.4?

![image](https://cloud.githubusercontent.com/assets/621965/4914610/3598e01e-64c5-11e4-9320-ee9091d8df55.png)

**Comment by guruz** [comment]
@Dianafg76 This needs to be tested with a branded client(?)

**Comment by Dianafg76** [comment]
@guruz Yes.
@moscicki Could you try if is resolved the issue?

**Comment by Dianafg76** [comment]
I tested this issue and now i can see all the options
![screen shot 2016-01-12 at 16 56 34](https://cloud.githubusercontent.com/assets/12032058/12269030/ac4e9688-b94f-11e5-9a5c-187b8155a467.png)
Desktop v 2.1.1
Server v 8.2.2
Closed
