### ISSUE TITLE
Proposal: Add icon (from owncloud.exe) to explorer favorites shortcut in Windows 7-8.1 created via installer

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/client#2446]
**Proposal:**
Add icon (from owncloud.exe) to explorer favorites shortcut in Windows 7-8.1 created via installer.

_Currently it is only the default folder icon._

**Comment by AnrDaemon** [comment]
I'd rather prefer some combnation of the two icons.
But aye, something more telling definitely needed.
