### ISSUE TITLE
[1.7] Windows shortcut are sometimes marked with a yellow overlay icon

### ISSUE THREAD

**Issue by etiess** [owncloud/client#2447]
Windows shortcut (*.lnk) are sometimes marked with a yellow icon like in the screenshot below. Some are with the standard windows arrow. While standard files / folders are marked with the green icon.

Nothing special signaled in Mirall, sync is done successfully for all these files.

![capture](https://cloud.githubusercontent.com/assets/900280/4921755/79fb6e1a-650c-11e4-9337-293783ffff59.JPG)

[EDIT]
Server: 7.0.2 on Ubuntu 14.10
Client: 1.7.0-rc1 on Windows 8.1 x64

**Comment by dragotin** [comment]
@ckamm does your *.lnk fix maybe fix this problem as well?

**Comment by ckamm** [comment]
@dragotin Possibly. Some remaining lnk issues were reported in #2792. Will check it out on Wednesday. :)

**Comment by ckamm** [comment]
No, this still happens even with the #2792 fix applied.

**Comment by lmaestro** [comment]
Fixed in version 1.8.0beta2
