### ISSUE TITLE
1.6.4 : doc OWNCLOUD_CHUNK_SIZE

### ISSUE THREAD

**Issue by RalfWW** [owncloud/client#2449]
The usage of ENV-Variable OWNCLOUD_CHUNK_SIZE (https://github.com/owncloud/mirall/issues/766) needs to go to the documentation!

**Comment by ajasja** [comment]
@guruz 
I can do a pull request with the fixed documentation. Could you reopen this issue?

**Comment by guruz** [comment]
@ajasja Sure! thanks for doing it.

PS: Please sign/submit the contributor agreement

**Comment by settermjd** [comment]
@ajasja what was the PR number?

**Comment by tflidd** [comment]
For client version 2.3 it seems to be documented:
https://doc.owncloud.org/desktop/2.3/advancedusage.html#configuration-file

Can we close this issue?

**Comment by RalfWW** [comment]
HI,

I'm afraid not.

I can't find the description of setting a environment variable 
"OWNCLOUD_CHUNK_SIZE" within the documentation (link below).

There is a description how to set the chunk size within the config file.

Regards

Ralf



Am 18.03.2017 um 20:22 schrieb tflidd:

**Comment by ajasja** [comment]
@settermjd the PR is #5631. 

@RalfWW can you read through the added docs and check everything is fine?
The files is here https://github.com/ajasja/client/blob/env_doc/doc/envvars.rst

**Comment by RalfWW** [comment]
looks fine.

PS: I like the way the calculation of seconds, i.e. 24x60x60 for a day,
is shown :-) That makes it more clear instead of a big number, 86400 in
this case.

Will this integrated within the documentation (PDF, ...)?

Regards




Am 19.03.2017 um 00:18 schrieb Ajasja Ljubetič:

**Comment by guruz** [comment]
Thank you @ajasja for contributing
