### ISSUE TITLE
Button to view and copy the status of blacklisted files

### ISSUE THREAD

**Issue by VincentvgNn** [owncloud/client#2456]
### Description

Previously I reported about a blacklisting problem in issue #2247.
For analyzing the list of blacklisted files the user needs to install SQLite for reading the data from the DB-file file '''.csync_journal.db'''.
It would be nice if the user could get an overview of the blacklisted files in an easier way.
Info like time, file-name, the reason for blacklisting and the next retrial time is useful for debugging and for checking the status.

The list could be displayed in the "Actvity Log" window after pressing a toggle button like "View Activity Log i.o. Blacklisted Files". The button for copying  the "Activity Log" to the clipboard could then be used for copying all blacklisting data from the database.
Combining this option with the F12 function for logging would be another way do it.

### Expected behavior
The blacklist data can be viewed and copied to the clipboard.

### Client configuration
ownCloud version: 1.6.4
Operating system: Win XP, Win 7 or Win 8
Browser: Google Chrome (or Firefox or IE11)

### Server configuration
ownCloud version: 7.0.2 (stable)
List of activated apps: default apps + encryption
External storage: no
Encryption: yes

OC server installed at a Dutch webhosting company. 4-5 GB storage.
Control via DirectAdmin and installation by using Installatron.
Own (non-shared) IP and using https.
Operating system: Linux Hosting Package
Web server: Apache
Database: MySQL
PHP version: native, 5.5.

**Comment by ogoffart** [comment]
You can see the blacklist in the activity log because they show as error all the time.  Idealy there should be nothing in the blacklist anyway. The blacklist is just an implementation details. User should not need to see it.

**Comment by VincentvgNn** [comment]
@ogoffart 
OK to close.
Meanwhile blacklisting for ever has been solved by #2247 .
