### ISSUE TITLE
[1.6.x/1.7.0] Error in German translation when adding a new folder

### ISSUE THREAD

**Issue by Siedlerchr** [owncloud/client#2460]
Hi,
there is a little error in the German translation in the client, when you add a new folder:
![oclgerman](https://cloud.githubusercontent.com/assets/320228/4957909/0e28cb4e-66a9-11e4-800d-65adb25a330d.png)

First of all: **Warning** should be translated as **Warnung** 
And in the error message: Keinen gültigen **lokales** Ordner gewählt 
Here **lokales** should be **lokalen**  (lokales is wrong grammar in this case) 

Regards,
Siedlerchr

**Comment by guruz** [comment]
@DeepDiver1975 Would do it myself, but I don't have transifex permissions i think

**Comment by DeepDiver1975** [comment]
We are talking about the master branch - right?

**Comment by DeepDiver1975** [comment]
> Here lokales should be lokalen (lokales is wrong grammar in this case)

I just fixed this in de and de_DE

**Comment by DeepDiver1975** [comment]
> First of all: Warning should be translated as Warnung

as far as I can tell this is already properly translated on transifex - is 'Warning' properly marked as translatable string?
