### ISSUE TITLE
1.7.0: "choose what to sync" inconsistent behaviour if modified while files uploaded

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2462]
Create a large number of files in a folder and start syncing them.

"Choose what to sync" is available and may be modified. If you uncheck the folder which is being synced (uploaded files) this seems to be ignored. The folder is not deleted. 

Otherwise on a fully synced folder the "choose to sync" seems to delete the folder as advertised.

**Comment by ogoffart** [comment]
Choose what to sync only disable some remote folder.  And if there are modifications in the local folder, they won't be deleted.
