### ISSUE TITLE
[Feature request] Sync children folder even parent folder content was deselected for sync

### ISSUE THREAD

**Issue by godfuture** [owncloud/client#2464]
Think of the following folder setup:
The root folder (Parent) contains 3 folders (Child1/2/3 and some files File1/2). I would like to sync the content of Child1 and Child2, but not Child3 and not content in Parent itself (maybe because File1 and File2 are not in my interest or too big or should get synced later).

With Owncloud client 1.7 I do not have the chance to exclude content in the Parent, when at least one Child is being synced.

I think it would be very practical, if the content of Parent could be deselected, even Child1 and Child2 get synced.

**Comment by ogoffart** [comment]
Closing old issue.
This can be done by adding a sync folder connection
