### ISSUE TITLE
[Feature request] Provide selective sync configuration for local folders

### ISSUE THREAD

**Issue by godfuture** [owncloud/client#2465]
Selective sync seems to be applied only on folders that are already uploaded to server. I would appreciate a function that allows me to deselect the folders that should not be uploaded/synced to server when adding a new sync folder in client ("local-only folders").

**Comment by MTRichards** [comment]
I see. So, for example, if you want a;; files to sync all is good. If you set up a new local folder, but don't want a sub folder to sync up, but you want to sync the rest of the folder to sync, right now essentially that sub folder will be synced, and then deleted locally. That might now be the best option.
Right?

**Comment by bartatgithub** [comment]
Example: 
Because it's a more clear and better way of working for me, i want to choose my MacOS user "Documents" folder as sync folder. 
But i wan't only to sync the folders (in my "Documents" folder) that i need in the cloud, not all of them. 


"Choose what to sync" is an important function but it's only possible on the server side. 
A "Choose what to sync" function for files on the computer hard drive would be nice.

**Comment by scolebrook** [comment]
@bartatgithub You can accomplish this with the Add Folder feature. A sync folder should have all content within it synced on the server. Selective sync allows some content on the server to not be in the local sync folder, but everything in the local sync folder is always going to be on the server.

But the Add Folder feature allows you to have multiple sync folders which is what you're describing. You don't want to sync the Documents folder, you want to sync several folders within it. Is that correct?

**Comment by tobiasKaminsky** [comment]
@scolebrook This is indeed possible. But in my case I have a big folder and only one subfolder should not get synced. Also I create many new subfolders, which should get synced automatically.

So, I do think that this is an important feature.

**Comment by bartatgithub** [comment]
@scolebrook Yes, that's correct. I was just looking into the Add folder function. It is simple not clear enough that you can choose more then one folder. I try that out. 

Still, i also find that the "Choose what to sync" function for local folders is important and more clear.

**Comment by vtolkm** [comment]
I am very much in favor of a granular selection feature for sub folders/files on the local side/hard drive from within the OC sync client. And thus providing the user with highly granular control over which folders to sync. In particular, subfolder synchronization policies - selecting child folder(s)/file(s) for sync without syncing the entire parent. It would also minimize bandwidth consumption by only syncing the folders/files which need to be accessed remotely. A direction policy would nice too - 2 way sync, up-sync or down-sync.

@scolebrook The method you described is a bit of a cumbersome workaround, requiring to add/establish an extra folder and copy all files/folders for sync to it, as opposed to the native folder structure on the local side.

![subfolder_sync](https://cloud.githubusercontent.com/assets/13611490/9026956/5f945e38-394b-11e5-88b5-0a621f1b788c.png)

**Comment by vtolkm** [comment]
Is there anyway to a attract a developer to get this feature on the road? I would perhaps be willing to contribute financially, if that is the issue.

**Comment by godfuture** [comment]
Well, this feature aims at decreasing the total amount of sync folders on owncloud client.
The same result as described by achieving this feature could be managed by separate sync folders. But this would, as said, increase the total amount.

Example
Structure: Parent -> subfolder1 + subfolder2 + subfolder3
subfolder3 should not be synced!
* I could create a sync folder for subfolder1 and 2
* I could create a sync folder for Parent, and deselect subfolder3 for uploading (syncing) to server.

I guess, that the selective sync feature could gather all folders from remote (server) and local (client) and display them in one and the same dialog indicating the location of the folders.

**Comment by dragotin** [comment]
Sorry, we now took the server oriented approach, meaning in this case that the selection for selective sync is on what is on the server.
