### ISSUE TITLE
 owncloud-client dependencies broken

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/client#2466]
Just did an `apt-get update` and `apt-get upgrade` today and spotted this (did not happen yesterday):

```
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies.
 owncloud-client : Depends: libowncloudsync0 (= 1.6.4-0) but 1.7.0 is to be installed
 owncloud-client-l10n : Depends: owncloud-client (= 1.7.0) but 1.6.4-0 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```

On Ubuntu 14.10 here, using the latest owncloud client. PPA is set to http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.10/

**Comment by guruz** [comment]
Closing this. If there is more to solve, please create a new issue.

**Comment by milrak** [comment]
> I updated owncloud on three other machines and there the update works quite well. So I removed and installed the packages on the machine with the problem and this solves the problems:
> 
> ```
> sudo apt-get remove owncloud-client libowncloudsync0 owncloud-client-l10n
> sudo apt-get install owncloud-client libowncloudsync0 owncloud-client-l10n
> ```

Perfect!
To complete, install on Ubuntu 14.04 32-bit:

```
1- sudo apt-get remove owncloud-client libowncloudsync0 owncloud-client-l10n
2 - rm -r /var/lib/apt/lists
3- sudo wget -nv https://download.opensuse.org/repositories/isv:ownCloud:desktop:client-2.4.0/Ubuntu_14.04/Release.key -O "/etc/apt/trusted.gpg.d/isv:ownCloud:desktop:client-2.4.0.asc"
4- sudo apt update
5- sudo apt-get install owncloud-client libowncloudsync0 owncloud-client-l10n
```
