### ISSUE TITLE
[Feature request] Allow pause/resume action from client's taskbar menu (like dropbox behaviour)

### ISSUE THREAD

**Issue by pmalek** [owncloud/client#2468]
There is an option for pausing and resuming of synchronization through Right Click -> Settings -> Account -> Pause/Resume but it would be very convenient IMHO to add this button from client's taskbar menu ( just like dropbox client has it).

Client version: 1.7.0

Operating system: Ubuntu 14.04 64 bit

OS language: English

**Comment by danimo** [comment]
Duplicate of #1971. Please follow this one.
