### ISSUE TITLE
Proxy creates certificate - Login fails

### ISSUE THREAD

**Issue by Loris1123** [owncloud/client#2474]
In my current setup my proxy creates his own certificate for every SSL connection.
This means:

PC<---- Proxy Certificate ----> Proxy<-----Original Certificate-----> Owncloud

The original certificate is self-signed.
When I try to login with the desktop client (web works) I need to accept the certificate the proxy created. I can see that the signer has been changed. The rest is same to the original certificate. When I enter my login credentials my password won't be accepted.

You can read the log in the following pastebin link:
http://pastebin.com/ds5bETjC

**Comment by danimo** [comment]
Any update here?

**Comment by danimo** [comment]
I'll close this. Please reopen once you find a way to reproduce the issue.
