### ISSUE TITLE
Desktop sync client for Mac shows "CSync unspecified error"

### ISSUE THREAD

**Issue by boschma1** [owncloud/client#2475]
Hi there 

After a migration to the new version 1.7.0 I receive this meaningful error message with a red cross. The previous version worked like a charm.

![screen shot 2014-11-10 at 12 15 07](https://cloud.githubusercontent.com/assets/5564469/4975006/590e3bae-68d3-11e4-9468-7c7f3a4630c8.png)

I installed the exact same version on a different client (as well MacOSX 10.10) where it works and synchronizes the files and folders. Thusly, I am expecting nothing to be wrong with the server side.

Is there a way where I can access and see the log files that might give me a better idea than this error message on the UI?

Thank you.

**Comment by fnetto** [comment]
I am suddenly having the same issue with one of the clients.

Here are the lines with error:
02-08 10:42:12:841 0x7698c08 syncengine.cpp:518  #### ERROR during  csync_update :  "CSync unspecified error."
02-08 10:42:12:845 0x7698c08 syncengine.cpp:824 CSync run took  2962
02-08 10:42:12:848 0x7698c08 folder.cpp:836 -> SyncEngine finished with ERROR, warn count is 0
02-08 10:42:12:858 0x7698c08 folder.cpp:418 Processing result list and logging took  6  Milliseconds.
02-08 10:42:12:859 0x7726568 folderwatcher_win.cpp:88 void Mirall::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/carmen/Documents/.owncloudsync.log" action: 3
02-08 10:42:12:863 0x7698c08 folder.cpp:438 OO folder slotSyncFinished: result:  2
02-08 10:42:12:867 0x7698c08 folder.cpp:857   ** error Strings:  ("CSync unspecified error.")
02-08 10:42:12:871 0x7698c08 folder.cpp:859     * owncloud csync thread finished with error
02-08 10:42:12:874 0x7698c08 folder.cpp:879 the last 1 syncs failed

**Comment by guruz** [comment]
@fnetto In general, it would be useful to know the log _before_ the ```### ERROR``` to see what lead to it.
I'd suggest a nightly build of the soon to be released 1.8.0 http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.1997-nightly20150208.pkg

**Comment by fnetto** [comment]
O actually resolved the issue.  It was on a regular folder, and all i did was to compress it and delete.
After it worked i unzipped the folder and without any modification it still working, so i am not sure what actually caused the problem.

Thanks


Sent via the Samsung GALAXY S®4, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by guruz** [comment]
ok :) if it re-orccurs please post a new bug then we can investigate
