### ISSUE TITLE
No monochrome icon on OSX Lion v1.7.0 

### ISSUE THREAD

**Issue by mcnesium** [owncloud/client#2478]
Checking the "use monochrome icons" option does not do it. v1.7.0 still shows the colored icon in the menu bar on OSX Lion
![ieng4aum](https://cloud.githubusercontent.com/assets/476060/4989923/6158ac74-6980-11e4-8e6a-8f3a55a0eecc.png)

/edit: this seems to only affect the info-icon. Both the check- and the cross-icon are monochrome.

**Comment by ogoffart** [comment]
Is there still a problem with 1.8?

**Comment by cbartholomee** [comment]
Can confirm it is fixed.
During 'Discovering' fase nice monochrome icon is shown.
Thanks!

**Comment by mcnesium** [comment]
confirm
