### ISSUE TITLE
Warn user before wiping/re-syncing all files

### ISSUE THREAD

**Issue by jbtbnl** [owncloud/client#2483]
I've thought about this before, but now that a [similar idea](https://mailman.owncloud.org/pipermail/user/2014-November/000875.html) was sent to the owncloud-user mailing list I think it is time to propose the following idea:

Issue a warning to the user when the client is about to wipe and/or re-sync all files.

__Use case 1__
While I was still running oC 6, I created a testing setup with oC 7 and copied all my data to it. When oC 7 turned out to work just fine, I removed oC 6 and moved the oC 7 installation to the original path. Not taking into account that the created-on dates had changed due to me having made a copy of the data. It triggered a complete re-sync and took my computer several hours to catch up again.

__Use case 2__
The user (in any kind of way) mistakenly deletes all ownCloud data. The client happily syncs and therefore deletes all content from the HDD.

Wrapping up, the warning could have saved me and David quite some time and trouble. To prevent ownCloud from throwing the same warning on testing instances with only a couple of files, I'd propose a threshold of ~10 files for the warning.

cc @owncloud/designers

**Comment by ogoffart** [comment]
We show that kind of warning, yes.
