### ISSUE TITLE
[Ubuntu] Ignores HTTP SSL System Proxy settings

### ISSUE THREAD

**Issue by Patrick0815** [owncloud/client#2486]
Since last update:
The ownClound client on my ubuntu 14.04
does not use http proxy settings anymore.

**Comment by danimo** [comment]
@Patrick0815 ownCloud client only evaluated the `http_proxy` environment variable. Unless your Qt version was patched, this was never different.

**Comment by ogoffart** [comment]
What version of Qt is it using? Can you try with 1.8? What kind of proxy settings do you have?

**Comment by guruz** [comment]
The question is if using Qt5 with a Qt compiled with libproxy helps here
http://code.woboq.org/qt5/qtbase/src/network/kernel/qnetworkproxy_libproxy.cpp.html

Half related to https://github.com/owncloud/client/issues/2558 as the Qt libproxy backend only exists in Qt5

**Comment by ogoffart** [comment]
Closing old issue
