### ISSUE TITLE
[Windows] Overlay icons are not removed from registry after uninstall

### ISSUE THREAD

**Issue by VincentvgNn** [owncloud/client#2487]
### Description

In ownCloud 1.7 overlay icons are introduced to show the sync status.
In the Windows registry there are a limited number (max. 11-15) of free slots for these icons. If there are too many, the alphabetic ranking will determine which icons will work.So it can happen that the overlay icons from other programs will not work after installing ownCloud.
Therefore there is a check-box to omit the OC overlay icons at the installation.
But, as it is now, there is no way back for uninstalling the OC overlay icons, i.e. releasing the space that they occupy in the registry.
Uninstalling OC and restarting the PC does not remove the overlay icons from the registry!

The overlay icons can be viewed in the registry and can be manually removed at:
Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers

### Steps to reproduce
1. Install OC 1.7
2. Uninstall OC 1.7
3. Check the removal of the OC overlay icons in the registry after restarting the PC.

### Expected behavior
The OC overly icons should be removed from the registry after uninstalling.

### Client configuration
ownCloud version: 1.7.0
Operating system: Win XP, Win 7 or Win 8
Browser: Google Chrome (or Firefox or IE11)

### Server configuration
ownCloud version: 7.0.2 (stable)
List of activated apps: default apps + encryption
External storage: no
Encryption: yes

OC server installed at a Dutch webhosting company. 4-5 GB storage.
Control via DirectAdmin and installation by using Installatron.
Own (non-shared) IP and using https.
Operating system: Linux Hosting Package
Web server: Apache
Database: MySQL
PHP version: native, 5.5.

**Comment by dragotin** [comment]
@jturcotte can you help here?

**Comment by VincentvgNn** [comment]
I might be good to have a look at the free Barracuda Copy.
There installing and uninstalling the overlay icons works perfect and the setup structure seems to be quite similar to OC.

**Comment by guruz** [comment]
We think this is fixed for 2.0..
If you can still reproduce it, please re-open and comment with exact way on how to reproduce it.
