### ISSUE TITLE
[Howto] Build 1.7.0 for Mac

### ISSUE THREAD

**Issue by scolebrook** [owncloud/client#2490]
I've updated my build VM with brew update/upgrade, checked out 1.7.0 and can't build the Mac client successfully.

Here is the cmake command I'm using:
cmake -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_INSTALL_PREFIX=~/Desktop/mirall/install ~/Desktop/mirall/mirall

This is run from ~/Desktop/mirall/mirall-build. This part seems to work. The following make seems to compile successfully and mirall-build is full of stuff. But ../install is empty so the create_mac.sh script doesn't work.

Incidentally, the script says the install prefix dir comes first followed by build dir and the build documentation has it the other way around. I've tried both without success.
Unable to copy item at path '/Users/me/Desktop/mirall/mirall-build/../install/owncloud.app' because the item could not be found

I can see the correct path in mirall-build/cmake_install.cmake for CMAKE_INSTALL_PREFIX. But nothing gets copied to the install directory and the create_mac.sh clearly expects it to be populated with something.

Either something is missing in the documentation or this script has a bug of some kind.

**Comment by anx-mr** [comment]
I cannot find the problem ...

**Comment by guruz** [comment]
@anx-mr @mrauter  This commit might possibly help you: https://github.com/owncloud/client/issues/2627#issuecomment-69345507
