### ISSUE TITLE
client operation much slower on centos6 than on macosx

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2492]
The sync client 1.7.0 is much faster doing sqlite metadata ops on MacOSX than on Centos6.

You may see it like this:
 - create 1000 small files in directory A and sync
 - mv A B

There is only one remote move A->B but then 1000 local sqlite updates for each file.

On MacOSX I get: 100Hz
On Centos6: 10Hz

Is it possible that the sqlite version on Centos6 (SLC6) is performing so badly?

```
>ldd /opt/qt-4.8/bin/cernbox | grep sqlite
	libsqlite3.so.0 => /usr/lib64/libsqlite3.so.0 (0x0000003616800000)
>rpm -qf /usr/lib64/libsqlite3.so.0
sqlite-3.6.20-1.el6.x86_64
```

**Comment by guruz** [comment]
Did you see the sqlite3 version in the log?

**Comment by moscicki** [comment]
Hi,

Here is the sqlite version on redhat6:

sqlite3 version "3.6.20" 
sqlite3 journal_mode= "delete" 

kuba

--

**Comment by moscicki** [comment]
@guruz: Please reopen.

**Comment by guruz** [comment]
@dragotin Shall we reopen?
Maybe we should link with sqlite3.c like we do on Windows and Mac if Linux users prefer to have their libraries at old versions.

**Comment by guruz** [comment]
We bundle 3.8.6 1d5b3aadeaf6f0cfb49aa97176588bbbaee6c3c3

Current version is 3.8.8.1 https://sqlite.org/changes.html
