### ISSUE TITLE
Client 1.7.0 Final - Extremely Slow Speed

### ISSUE THREAD

**Issue by christianrj** [owncloud/client#2493]
### Expected behaviour

Files should sync at a resonable speed over local network
### Actual behaviour

Files are synchronizing at extremely slow speeds over local network.
### Steps to reproduce

Not aplicable
### Screenshot showing the problem

http://s16.postimg.org/ujyif3ap1/oc_client.png
Look at the screenshot above. A file copy via windows explorer at 17.5 MB/s and a sync in ownCloud client at 177 KB/s.
### Server configuration

Operating system: CentOS 6.5 x64

Web server: Apache 2.2.27

Database: MySQL 5.5.39

PHP version: 5.5.16

ownCloud version: 6.0.5

Storage backend: local HDD (7200 rpm)
### Client configuration

Client version: 1.7.0 Final

Operating system: Windows 7 Ultimate x64

OS language: Portuguese Brazilian

Installation path of client: default location
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`: not aplicable
2. Web server error log: not aplicable
3. ownCloud log (data/owncloud.log): not aplicable

**Comment by mauromi** [comment]
![screenshot from 2015-02-07 01 17 38](https://cloud.githubusercontent.com/assets/1806526/6089700/3f2a5b94-ae67-11e4-9273-64c6730a077c.png)

client version: 1.7.1
server version: 7.0.4-3
dbtype: sqlite3
