### ISSUE TITLE
Too many small log files when the "--logdir <file>" parameter is used

### ISSUE THREAD

**Issue by VincentvgNn** [owncloud/client#2497]
### Description

It can  happen that I have a sync run interrupt at about each minute.
From OC client 1.7.0 on, creating a log file by using the parameter ```--logdir <dir>``` results in many small files. Scrolling through the logging then means opening many individual files.

Can starting a new file be triggered by not only a new sync run, but also by the condition that the file must larger than e.g. 5 MB or was created more than e.g. 1 hour ago?

My current workaround:
I use the ```logfile <file>``` parameter or the F12 function.
This cannot be used for continuous logging and it requires manual action. 

### Steps to reproduce
1. Use the parameter ```--logdir <dir>``` to create log files.
2. Do not change any file. So there is nothing to update.
3. Have many sync interrupts.

### Expected behavior
A limited number of logging files. E.g. only a new file after each hour or 5 MB size.

### Client configuration
ownCloud version: 1.7.0
Operating system: Win XP, (Win 7 or Win 8)
Browser: Google Chrome (or Firefox or IE11)

### Server configuration
ownCloud version: 7.0.3 (stable)
List of activated apps: default apps + encryption
External storage: no
Encryption: yes

OC server installed at a Dutch webhosting company. 4-5 GB storage.
Control via DirectAdmin and installation by using Installatron.
Own (non-shared) IP and using https.
Operating system: Linux Hosting Package
Web server: Apache
Database: MySQL
PHP version: native, 5.5.

**Comment by ogoffart** [comment]
The logfiles are big because all the files always get an entry in the log files for every sync.  This is required for us to debug properly. `--logdir` is a debug function that should normaly not be used unless you want to track a problem. as it would make the client much slower.
