### ISSUE TITLE
OC 1.7 New default location for log files in Windows 7/8 difficult to find

### ISSUE THREAD

**Issue by VincentvgNn** [owncloud/client#2498]
### Description

From OC 1.6.4 to 1.7.0 the default location for the log files in Windows 7/8 has been moved from the Program Files folder to the more logical but hidden AppData folder.
The new path is difficult to find. Here it is:
C:\Users\"username"\AppData\Local\VirtualStore\Program Files (x86)\ownCloud

Can this be mentioned in the manual in the section "Saving Files Directly"?

**Comment by SamuAlfageme** [comment]
Since 1.7 log handling options have evolved and improved greatly: https://doc.owncloud.org/desktop/2.2/troubleshooting.html#log-files

I'm closing as this no longer applies.
