### ISSUE TITLE
When you have two ownCloud clients that are running at the same time only one shows overlay icons

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2505]
### Expected behavior
The two clients are running show their overlay icons in their local folders 

### Actual behavior
When you have two ownCloud that are running at the same time only one shows overlay icons

### Steps to reproduce
1. Open 2 desktop clients
2. Open their local folders

### Server configuration
{"installed":"true","version":"7.0.3.1","versionstring":"7.0.3 RC2","edition":""}

### Client configuration
ownCloud Client Version 1.7.0

Operating system: Windows 7
![no-icons](https://cloud.githubusercontent.com/assets/4689430/5069750/d05bb4ee-6e5e-11e4-9515-8684a13548c4.PNG)

**Comment by ckamm** [comment]
Isn't this "WONTFIX: Two clients at the same time are not supported?". Definitely not in scope for 1.8.1 I'd say.

**Comment by ogoffart** [comment]
WONTFIX
