### ISSUE TITLE
[OS X] "Choose What to sync" window is not resizable 

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2506]
## Expected behavior
 "Choose What to sync" window is resizable like settings window
 
### Actual behavior
"Choose What to sync" window is not resizable 
### Steps to reproduce
1. Open desktop clients
2. Click on "Choose what to sync"

### Server configuration
{"installed":"true","version":"7.0.3.1","versionstring":"7.0.3 RC2","edition":""}

### Client configuration
ownCloud Client Version 1.7.0

Operating system: OS X 10.9.5
![screen shot 2014-11-17 at 11 33 28 am](https://cloud.githubusercontent.com/assets/4689430/5070098/65aec294-6e63-11e4-8625-6abe15483921.png)
![screen shot 2014-11-17 at 11 33 21 am](https://cloud.githubusercontent.com/assets/4689430/5070102/698f9a28-6e63-11e4-9ec5-eb8381f1b4eb.png)

**Comment by guruz** [comment]
Needs to be re-evaluated in context of multi-account

**Comment by guruz** [comment]
Not relevant anymore with the new multi account UI in 2.0
