### ISSUE TITLE
Use QNAM for discovery phase

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2507]
We have some ideas (hooks, wait conditions, using ```PropfindJob``` etc) on how this can be done.
This would enable to get rid of ```csync_owncloud.c``` and ```neon```. It would then use the same socket for the whole syncing.
We also get some nice QNAM features for free (e.g. gzip compressed WebDAV responses)

**Comment by guruz** [comment]
(Note to self: also ask https://github.com/owncloud/client/issues/2003 and https://github.com/owncloud/client/issues/2090 to re-test when released)

**Comment by guruz** [comment]
Diagram for @dragotin ;-)

Right side is our sync thread (running csync_update), left thread is the main thread (with the QNetworkAccessManager)

![owncloud_client_2507](https://cloud.githubusercontent.com/assets/959327/5837169/07f4b080-a17d-11e4-9470-57fc891e2341.jpg)

**Comment by dragotin** [comment]
Yes, very good, we need this documented!

**Comment by guruz** [comment]
The functionality has been merged into master.
```neon``` is not "compiled out" yet, will do that in a follow up

**Comment by lmaestro** [comment]
I tested in version 1.8.0-nightly20150122 (build 1925) and it works fine.
