### ISSUE TITLE
[Windows] 1.7.0 reports "Unable to write" /  "Operation canceled"

### ISSUE THREAD

**Issue by actyler555** [owncloud/client#2512]
### Expected behavior
Tell us what should happen:
The ownCloud app should sync files without failing and throwing multiple pop-up warnings.

### Actual behaviour
Tell us what happens instead:

hello everyone. I am running Ubuntu server 14, MySQL 5.6, ownCloud 7.0.3, and the Windows client version 1.7.0 (build 4162).

I am noticing that I see certain files .vss, .msi, and .zip files thus far fail to sync and the client throws an error stating "Unable to write" in the activity log. After you will get the warning "Operation canceled."

the client icon then goes "offline" showing a greyed out icon in the windows tray. It comes back after a few minutes and tries the sync again. depending on the size of the file it will go through this multiple times before eventually succeeding. A 249 MB ZIP file took about 4 tries. Anyone seen this? Have ideas on what I can try to change to make this more smooth.? Thank you!

### Steps to reproduce
1. Move files into your Windows sync folder.  Wait for errors.  See description above.

### Server configuration
Operating system: Ubuntu Server 14

Web server: Apache

Database: MySQL 5.6

PHP version: PHP5

ownCloud version: 7.0.3

Storage backend: Direct attached (LVM) - VMware infrastructure

### Client configuration
Client version: 

Operating system: Windows 7 Pro SP1

OS language: English

Installation path of client: Default.

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

I need some direction on how to collect these logs.  Where is the "web server error log"?  I tried running the owncloud --logwindow command from the client, but owncloud is not a recognized command.  This should be run from the server?

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by dragotin** [comment]
Closing because outdated and inactive.

**Comment by VincentvgNn** [comment]
@dragotin
In this issue an interrupted upload of large files is mentioned.
It sounds similar to issue https://github.com/owncloud/core/issues/4997 (Febr. 13th 2015) where I reported "auto-kill for PHP processes at a broken connection" before finalizing the upload.
So for me no problem to close it here.

**Comment by raaomoka** [comment]
I'm still experiencing this issue with ownCloud Desktop Client v2.1.0 on my Windows PC. I always shows this error for ALL my files, it doesn't sync anything.

I currently have no files on my ownCloud server, just empty directories I want to sync with directories on my PC. I successfully authenticate with the server during account setup, no problem, but when I attempt syncing a folder, this irritating message as stated in the OP pops up. I still haven't been able to find a solution to this.

I'm using ownCloud Server v8.0.4 on a QNAP NAS and a Windows 8.1.1 PC

**Comment by Exoyds** [comment]
I have this error as well. It's weird it's so isolated.
