### ISSUE TITLE
Sync does not work with special characters and locale settings

### ISSUE THREAD

**Issue by bumblebee21** [owncloud/client#2518]
Hello,

I'm using OC 7.0.3,1.7 client and using Ubuntu 14.04 as OC server and on the computer which tries to sync. If I like to upload or create files in nautilus with characters like "ä" and so on it tries to sync but it fails and the files disappear.

After some tries to fix it on the client, I fixed it by setting the LC_ALL to de_DE.UTF-8 because crh_UA.UTF-8 did not work but it isn't that good solution because we use OwnCloud in our company and if someone in another country uses another language the issue will be there again and fixing it will be much more complicated.

Or did I do some other thing wrong?

**Comment by ogoffart** [comment]
Please try the version 1.8 of the client,  we had fixes regarding to that.
But an invalid locale will cause problem anyway.

**Comment by guruz** [comment]
Please retry with 1.8.3
