### ISSUE TITLE
[Windows] Progress: Font rendered too small/pixelish

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#2519]
Using version 1.7.0 (just installed)

The font in the user account tab is too small. It is barely readable. It is more pixels than letters. See screenshots.
I am not aware of any configuration or setting out of the ordinary. I am using Win7 with all visual effects disabled (XP style).

![unbenannt](https://cloud.githubusercontent.com/assets/2737900/5113426/e3905ff6-702f-11e4-9d49-5e8730481060.png)

![unbenannt2](https://cloud.githubusercontent.com/assets/2737900/5113508/7b27bd3c-7030-11e4-922a-f8611c79f0c9.png)

(Images are real size. 100%)

**Comment by jancborchardt** [comment]
@dragotin @danimo any comment on this? Is this reproducible, or do we use the standard values anyway?

**Comment by guruz** [comment]
@jturcotte @danimo Maybe better with a newer Qt?

**Comment by jturcotte** [comment]
The font size was last changed in eadcdab8e7e87ceb5f15bf9ddfc4c3ae4a44c5ce but it's usually still pretty readable. Maybe the Windows font size on this machine was set lower?

**Comment by Kawohl** [comment]
For me it was not reproducable on windows 10 with native ui settings. There was no new info in a long time also. Therefore close.

**Comment by LukeOwncloud** [comment]
Unfortunately on Win7 with oc client 2.2.3 it is still an issue:
![oc small font](https://cloud.githubusercontent.com/assets/2737900/20957249/e4215732-bc4e-11e6-9de6-2eeefa601759.png)

Resolution is 1024x768. Classic Windows design. DPI 100% (96ppi). Windows font size setting: 100%.

**Comment by guruz** [comment]
@LukeOwncloud 2.2.3 is not the current version 2.2.4 is.

Let's also try how this looks when the Windows build is switched to Qt 5.6.2
https://github.com/owncloud/client/issues/3449

**Comment by jturcotte** [comment]
@LukeOwncloud Nobody else have seen this bug in 2 years, is it possible that one of the fonts is messed up on your system? Do you have another machine available where you could try?

**Comment by guruz** [comment]
@LukeOwncloud Can you try a pre-release of 2.3 that uses a new Qt version? http://download.owncloud.com/desktop/daily/ownCloud-2.3.0.6652-nightly20170118-setup.exe

**Comment by LukeOwncloud** [comment]
@guruz Yes, problem still exists. But it is just a single machine. So don't worry.
