### ISSUE TITLE
Automatically set alias name when adding folder

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#2524]
When adding a folder the user has to pick both: folder to sync and an alias name.

If the user does it in this order it would be nice if the alias name was set automatically to the top most folder name (so everything what is behind the last (back)slash).

Using 1.7.0 build 4162 on Windows7 32bit.

**Comment by rullzer** [comment]
I looks like this is already the case in the current master branch, so this should be added fixed in the next release.

**Comment by LukeOwncloud** [comment]
You are correct. It was already silently fixed in version 1.7.1. Closing.
