### ISSUE TITLE
Add "Create Local Folder" when adding a new sync folder

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#2525]
When adding new folder for syncing which is remote already available, it is troublesome to first create an according local folder before being able to setup syncing:

![no create folder](https://cloud.githubusercontent.com/assets/2737900/5121537/790a5622-7094-11e4-98f6-4c531db12a0d.png)

It just says: "Warning: No valid local folder selected!". Here it would be nice to have a button "Create Local Folder".

**Comment by SamuAlfageme** [comment]
With the wizard now is a bit more complicated to choose a local folder that does not exist, however. If you try to manually input one, you end up with this message: 

![screen shot 2016-12-13 at 17 26 37](https://cloud.githubusercontent.com/assets/2644445/21148703/62411a94-c159-11e6-9401-b516f1f60b5a.png)

**Comment by LukeOwncloud** [comment]
@SamuAlfageme  I cannot reproduce what you write. Also this issue is solved. Non-existing folders are created automatically if entered manually (without choose dialog).

**Comment by SamuAlfageme** [comment]
@LukeOwncloud this is what I mean: 

![folder](https://cloud.githubusercontent.com/assets/2644445/21355627/0abbf138-c6cf-11e6-80ca-7a32b566595a.gif)

But I agree this is pretty minor & non-relevant. Closing.
