### ISSUE TITLE
Enhance the structure of the folders table layout

### ISSUE THREAD

**Issue by stephane84** [owncloud/client#2530]
The new version 1.7.0 interface has been greatly improved for the end user (especially the status line for each folder... Thank you to the team !!), but the main view is a bit "messy", and far from a nice table...

I would like to propose to re-locate the *same* information in a nicer way, in a sortable table. This can improve the following items : 

 - For now, the folders are synchronized in alphabetical order, but are listed not in this order (strange !)
 - The icon "syncing" is used for multiple state (e.g. syncing and witing for sync) (strange !)
 - The presentation of one folder on multiple line is not nice, especially when the list have more than 4 folders (which is, I suppose, the case of more than 50% of the users. I have 8 folders in total)

I would propose to use a sortable table, with one line for each folder, and several columns, in order to structure the presentation of the information.

I made the following picture in openoffice (hum) to explain what I have in mind

![Proposition image](http://s29.postimg.org/n395fu0jb/mirall.png)

Questions : 
 - What are all the status for the folders ? I'll be glad to propose a different icon for each of them ?
 - Should it be possible to edit the folder parameters (name, URL local and URL server) when clicking on the folder's name ?
 - Should it be possible to trigger the pause/resume for each folder by clicking on the folder icon ?

**Comment by guruz** [comment]
With the UI redesign in 1.9 this is potentially fixed.

**Comment by guruz** [comment]
For 2.0 we show current uploads/downloads in the UI
In 2.1 we will show more server information (acitivity list) https://github.com/owncloud/client/issues/3732
