### ISSUE TITLE
[Windows 7] Sync Activity window does not show seconds

### ISSUE THREAD

**Issue by VincentvgNn** [owncloud/client#2535]
1. From OC client 1.6.4 to OC client 1.7.0 the seconds in the Sync Activity window disappeared.
Within a minute many things can happen. So I prefer to have the seconds also visible in the Sync Activity window.

2. The column width settings in the Sync Activity window can be changed by dragging the column border in the title bar. Unfortunately these settings are not stored.
After each OC restart I have to set these border positions again.
Can these settings be stored and recovered at OC restart?

**Comment by guruz** [comment]
@VincentvgNn Does this work with a new nightly build?

**Comment by VincentvgNn** [comment]
@guruz 
I tested ownCloud-1.8.0.4933-nightly20150408 on WinXP, Win7 and Win8.1.
On WinXP the seconds display is still OK.
Now on Win 8.1 the seconds are displayed as well.
But on Win7 there are still no seconds displayed. Forgotten to change something more?

**Comment by guruz** [comment]
Are you 100% confident you use the latest build? Can you check the version sha1 in the settings dialog?

**Comment by VincentvgNn** [comment]
@guruz
Maybe not necessary, but I uninstalled the previous OC client again keeping the user settings.
To be sure I even restarted the Windows 7 PC.
For the installation I used the file ownCloud-1.8.0.4933-nightly20150408-setup.exe.
After the installation the build version 4933 is shown under the General Setting.
But again still no seconds in the Activity display.
Can you reproduce the problem?

I also checked the owncloud.cfg file to see whether there some second setting could be retained.
But under [Settings] and [Logbrowser] there are only lines about the the geometry.

**Comment by ckamm** [comment]
@VincentvgNn I can retest this on Win7. The patch should add seconds everywhere that has a HH:mm format for time. Could you post an example of how timestamps are displayed on Win7? (maybe also post the tooltip of the timestamp field)

**Comment by VincentvgNn** [comment]
@ckamm 
Tooltips work quite slow and do not give a good overview. I never saw them before ;-).
The tooltip info is OK.
Here is a picture with the missing seconds display:
![oc 1 8 0 win7 - no seconds](https://cloud.githubusercontent.com/assets/7522929/7071282/b73d440e-dee4-11e4-9fd1-979da651c284.jpg)
In this example the file was ignored and got an OC info icon in front of the timestamp.
One could think about adding an empty icon to align all time values. Or to put the icon after the time value.

**Comment by ckamm** [comment]
Huh, maybe the datetime format string is hh:mm and the fix only treats HH:mm...

**Comment by VincentvgNn** [comment]
I found the rootcause for the difference between Win7 and Win8.
In my Win 8.1 PC the short time format is HH:mm and the long time format is HH:mm:ss.
In my Win 7 PC the short time format is H:mm and the long time format is H:mm:ss.
When I change the short time format  from H into HH, quit the OC client and restart it, I get the seconds displayed again.
So obviously the OC client can handle the Windows HH:mm setting and not the H:mm setting.
Is some string operation cutting off the seconds when there is only one "H"?

**Comment by ckamm** [comment]
@VincentvgNn The only 'solution' for this issue I saw was to manually modify the locale's datetime format string, see ea985a85af61ddd59303e792aee8ded4db74d981. I'll update the code to also deal with hh and the single-char variants correctly.

**Comment by VincentvgNn** [comment]
@ckamm 
I just had a look at Win XP. There is no separate short and long time format, just  a single format.
My setting there is: H:mm:ss and ..... surprise, surprise, the OC client displays the seconds there!

I'm not so good in reading the code at https://github.com/owncloud/client/commit/ea985a85af61ddd59303e792aee8ded4db74d981. Anyhow I only see HH:mm and no H:mm. Is that an update that still has to come?

**Comment by ckamm** [comment]
It was fixed in 9d8fc4a, tomorrow's builds will have the fix.

**Comment by VincentvgNn** [comment]
@ckamm 
I tested ownCloud-1.8.0.4938-nightly20150411 and it works fine.
After an OC client restart the short time format settings H:mm, HH:mm, hh:mm tt (US) and h:mm tt (US) are OK. Thanks!
I'll close this issue.
