### ISSUE TITLE
[windows] Client does not resume connection to mapped network drive

### ISSUE THREAD

**Issue by FreeMinded** [owncloud/client#2537]
Hi,
we have the following setup:
Client 1.7.0 for Windows running on always logged-in virtual machine.
Client syncs from a mapped network drive (X:) to an owncloud instance (7.0.2)
Server hosting networked drive restarts every second day.

Problem:
The client seems unable to resume the connection to the mapped network drive after server restart. It claims unsufficient permissions. Additionally the client becomes unresponsive (lags about 10 seconds).
Restarting the client fixes the issue and sync works fine. Until the next server restart.

Workaround:
Restart sync client after server restart.

Expected behaviour:
Client can resume connection to mapped network drive once it's available again.

I'll happily provide additional information. Thanks for looking into it.

**Comment by icefresh89** [comment]
Hi. I have the exact same issue as well in version 1.7.1. Please let me know if you need any further information. Thanks

**Comment by dragotin** [comment]
now handled in #3716
