### ISSUE TITLE
Provide tests for propagator jobs

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#2540]
We need automatted tests for the QNAM based propagator jobs that can run through Jenkins. We also should test error conditions. Ideally the test would spit out a list of http error codes and their resulting reaction of the job, for example:

Error Code   |  Reaction |  Error Message
----------------|-------------|-------------------
200              | Ok           | -
402              | Soft error | Directory could not be created
500             | Hard error | Internal server error

That might require to have a special testing app for the ownCloud server. Also that might require a bit of C++ class redesign to make it better testable.

**Comment by dragotin** [comment]
This needs more discussion. We can not **easily** provide tests for the job classes, we need a server etc etc. We need to see how that than is different from tx.pl or smashbox.

**Comment by moscicki** [comment]
Yep. Ideally we would also like to do some fault injection like timeouts, connections interrupted, packets lost, etc.

**Comment by nickvergessen** [comment]
@orion1024 because you commented in https://github.com/owncloud/core/issues/24684

> Tests exist today but they are not automated (perl, smashbox), not comprehensive (linux-only support, no error-handling tests, no multiple clients/servers combo tests) and some are not available (smashbox) for an external contributor.

Just want to make sure:
1. Smashbox tests run on each daily and they are automated: https://ci.owncloud.org/view/smashbox/
2. They are available for "external contributor" since the repo is public: https://github.com/owncloud/smashbox

If you need further assistance on getting them running, feel free to poke

**Comment by orion1024** [comment]
@nickvergessen I wasn't aware of all that, thanks.
I read on the wiki that they were run manually for the client so I didn't dig deep enough.
From I saw Docker is used. Is it mandatory ? because it's neither free nor cheap.

**Comment by ogoffart** [comment]
@nickvergessen  AFAIK,  the smashbox tests are not running for development versions of the client.

**Comment by ogoffart** [comment]
There is now a sync engine test framework
