### ISSUE TITLE
Checksums to Verify Up- and Download

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#2542]
Some storage backends support hash sums of files. These could be used to ensure the files integrity when up- or downloaded between sync client and server. This adds another level of security.

The basic idea is to add a hashsum as HTTP header to GET or PUT and compare on the other communication side. If the numbers do not match, the transmission has to be an error.

@moscicki has drafted a specification: https://github.com/cernbox/smashbox/blob/master/protocol/checksum.md as discussed on a meeting with @DeepDiver1975 and @dragotin.

Tracked in core repo owncloud/core#12417

**Comment by guruz** [comment]
Another issue where this might help: https://github.com/owncloud/core/issues/13044

**Comment by guruz** [comment]
Related https://github.com/owncloud/client/issues/3018

**Comment by dragotin** [comment]
There is a client branch already: https://github.com/owncloud/client/tree/checksum_verify

**Comment by nekoal** [comment]
What about perfomance? Checksum calculation need very long time for large files. I tried earlier with using crc32 function in zlib.dll 1.2.3 for my project. Walking directory tree time became 3-4 times longer when checksum enabled for all files include files with size larger than 1 MiB. And I expect md5 hash need more time than crc32.

**Comment by moscicki** [comment]
@nekoal: let's see in practice what is the impact. For now I'd say that the choice is yours: screw performance or screw file contents ;-)

**Comment by guruz** [comment]
Shall we have this for 2.1 ?
Something to discuss on the contributor meetup..

CC @MTRichards

**Comment by moscicki** [comment]
@guruz: I assume this functionality is available (but must be explicitly activated in the configuration/branding) in all releases starting with 1.8.0, correct?

**Comment by guruz** [comment]
@moscicki If things didn't change yes. I just wanted to emphasize that i think the non-CernCloud should have this.. :)
Are you coming to the contributor summit?

**Comment by moscicki** [comment]
Cool. Yes!

**Comment by MTRichards** [comment]
@guruz Ok, to discuss. In general, I like.

However, I think we should take a look at real tested performance impact...and then depending on those results, make a more informed decision.

**Comment by dragotin** [comment]
This is outdated, client version 2.1.0 and later have checksums. See #3735
