### ISSUE TITLE
The width and the order of the columns in the the Sync Activity are not stored

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2543]
### Expected behavior
The column width settings in the Sync Activity window can be changed by dragging the column border in the title bar and these changes are stored.

### Actual behavior
The column width settings in the Sync Activity window can be changed by dragging the column border in the title bar. Unfortunately these settings are not stored.
After each OC restart I have to set these border positions again.

### Steps to reproduce
1. Open settings in the Sync Activity window
2. Change the column width and the order 
3. Restart the client

**Comment by Dianafg76** [comment]
With Desktop v 2.1.0 this option has changed
