### ISSUE TITLE
.owncloudsync.log: missing and incomplete timestamps

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2549]
I see often missing timestamps in .owncloudsync.log. Instead the lines start like this:

```
|0|......
```

This affects operations such as directory creation (MKCOL) and also in case of various file get/put problems (e.g. Connection Closed). I think you have several code paths which do not correctly report timestamps when the log entry is generated.

**Comment by guruz** [comment]
@dragotin FYI

The same cause where you today complained about the empty ```file_id```


Related https://github.com/owncloud/client/issues/3108

**Comment by ogoffart** [comment]
(I wonder how usefull is this .owncloudsync.log right now. I think those cryptic value in the log has no value.  It should probably be a more human readable log that reflects the activity tab.)

**Comment by ckamm** [comment]
All the local jobs don't set `_responseTimeStamp` and `_requestDuration` because there simply is no network job. That seems sensible but makes the log look inconsistent.

**Comment by hodyroff** [comment]
@pmaier1 for log definition

**Comment by michaelstingl** [comment]
For debugging, the log you get if you run the sync client with the `--logdir` parameter, is much more useful. I know there are improvements that have been done lately, or are planned.

What is the use case for the .`owncloudsync.log`?

**Comment by guruz** [comment]
> What is the use case for the .owncloudsync.log?

It's the always-on log of the last few sync runs. So users can try to understand what happened

The ```--log*``` option is if more for developers, but in case of problems the child already fell into the fountain ;-) and it might not be reproducable

**Comment by michaelstingl** [comment]
@guruz @pmaier1 What should be the next step here?
