### ISSUE TITLE
Desktop UI client review + support for multiple accounts (as in iOS app)

### ISSUE THREAD

**Issue by giovanisp** [owncloud/client#2551]
Taking inspiration from the ownCloud iOS App, I'd like to share with you some UI changes that could make the client easier to use and more powerful respect other "cloud" apps out there, by supporting multiple accounts sync.

1. Get rid of right panel. Settings and Ignored files could be moved to the left column (see 2.), and Pause/Stop sync can be placed next to each sync "folder job". Also, current "Activity", "Network" and "General" buttons on the left go to the bottom bar, opposed to the "Close" button:
![image](https://cloud.githubusercontent.com/assets/180794/5205201/a2684140-7595-11e4-9074-106288c39c82.png)

2. Review Left Sidebar - Add folder keeps its wizard to add new folders to the current account
![image](https://cloud.githubusercontent.com/assets/180794/5205297/5c60dd5a-7596-11e4-811b-f98adede2376.png)

3. Review Left Sidebar - Ignored Files are moved inside the left sidebar, with buttons to add/remove more extensions on top:
![image](https://cloud.githubusercontent.com/assets/180794/5205311/854bfb14-7596-11e4-993a-5f52770a16ec.png)

4. Review Left Sidebar - NEW Feature - Manage Accounts. Basically, as in the iOS app, it would allow to connect to more than one account on the same server or different servers. This would be managed similar to the way the iOS app does, with the UI enabling users to Add a new account (on top); and manage current accounts by activating/deactivating it, or clicking to edit it's login parameters (which opens a new wizard window):
![image](https://cloud.githubusercontent.com/assets/180794/5205361/d31154d4-7596-11e4-85b8-a0266f2bc63f.png)

![image](https://cloud.githubusercontent.com/assets/180794/5205367/df4e8d16-7596-11e4-9e91-e791a4d9d27e.png)

**Comment by ogoffart** [comment]
@giovanisp @jancborchardt :  you can have a look at the new ui in the 2.0 snapshot and give feedback on that.

**Comment by jancborchardt** [comment]
@ogoffart can we either have that build as the testpilotcloud-client or some screenshots? Because otherwise we can not install it side-by-side with a production client.

**Comment by ogoffart** [comment]
@danimo or @dragotin  is it possible to have a testpilotckoud-client build?

**Comment by jancborchardt** [comment]
cc @jnweiger as well ^

**Comment by guruz** [comment]
FYI http://download.owncloud.com/desktop/daily/ownCloud%20Testpilot%20Edition-2.0.0.2586-nightly20150731.pkg

**Comment by giovanisp** [comment]
Wow! Thanks. Will try it on monday!

**Comment by guruz** [comment]
And Windows http://download.owncloud.com/desktop/daily/testpilotcloud-2.0.0.5324-nightly20150801-setup.exe

**Comment by ogoffart** [comment]
I am closing this issue because multi-account is implemented.
Please re-open more issues with more specific problems if you find any.

**Comment by jancborchardt** [comment]
Great work folks! :)
