### ISSUE TITLE
[1.7.0] Confirmation required in desktop client when deleting all the files in a folder

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#2554]
### Expected behavior
When I delete all the files in a folder (in another device or web interface), it sould eliminate all the files in the local folder in an unattended computer.

### Actual behavior
When I delete all the files in a folder  (in another device or web interface), it comes up a message like this, asking for confirmation to eliminate all the files in the local folder.

This is a problem because it happens in an unattended machine, and there is no further file sync until you confirm that you want to eliminate or keep the files. Is there any parameter to suppress this confirmation?

00002138

**Comment by cdamken** [comment]
@dragotin I just checked the 1.7.1 build 4406 and the behavior is the same when you delete all the files.

@kaplandani  As I said, I need this part for unattended machine. maybe a parameter when the computer start could solve this situation

@kwillems Why did you close my case?

**Comment by kaplandani** [comment]
I did not. Someone else closed it.
Dani

**Comment by kwillems** [comment]
@cdamken Sorry, I don't remember this ticket at all :-)

**Comment by cdamken** [comment]
@MorrisJobke @dragotin  Any news?

**Comment by dragotin** [comment]
No. And I have to say that I am not in favour of building a switch to disable this behaviour. If it was me, this can be closed as we-do-not-do-this.

**Comment by cdamken** [comment]
@MTRichards  Can be done this as feature request?

@markviens @karlitschek @craigpg

**Comment by danimo** [comment]
Here are the cases why the error message is currently needed (please add):

- Account gets recreated on the server. In that case all files will be gone from the server and the client sync logic thinks it needs to replicate that state. We could probably check the root file id to detect that case.

- Somebody moved a shared folder, which resulted in the folder being deleted for everyone else. I think this has been fixed, but needs testing.

**Comment by MTRichards** [comment]
@danimo Agreed - and it is a good stop gap to keep customers from doing something by accident - which, with external storage, can be even worse (oops, deleted all of sharepoint?). So as a default, I think we need it.

However, we will need a mechanism to suppress the message in a remote wipe scenario anyway, right? How might we do that?

**Comment by cdamken** [comment]
@danimo 
>However, we will need a mechanism to suppress the message in a remote wipe scenario anyway, right?  How might we do that?

any news?
