### ISSUE TITLE
Hard links not supported

### ISSUE THREAD

**Issue by frarude** [owncloud/client#2557]
### Expected behaviour

Hard links should not irritate mirall, if a file is there only once in the synched tree. 
### Actual behaviour

mirall mocks about hard links not supported and does not touch those files.
### Steps to reproduce
1. Create a file outside the synched ownCloud tree
2. make a hard link from that file to a file inside the synched tree
3. let mirall try to synch
### Server configuration

Linux debian sid

Web server: 
apache 2.x 

Database:
mysql 5.5

PHP version:
php 5.6.x

ownCloud version:
7.0.3

Storage backend:
local
### Client configuration

Linux Desktop Client version 1.7.0

Operating system:
Linux openSuSE 13.1

OS language: DE

Installation path of client:
/usr/bin/owncloud
### Logs

```
11-28 13:55:58:564 0x18040b8 csync_walker: file: /home/frank/ownCloud/Bilder/papibilder/Photos/Urlaub/VORSCHAU.PS [inode=18612749 size=6306]
11-28 13:55:58:564 0x18040b8 _csync_detect_update: file: Bilder/papibilder/Photos/Urlaub/VORSCHAU.PS, instruction: INSTRUCTION_IGNORE <<=
11-28 13:56:22:225 0x131ba60 _csync_merge_algorithm_visitor: INSTRUCTION_IGNORE   file: Bilder/papibilder/Photos/Urlaub/VORSCHAU.PS
11-28 13:56:25:528 0x131ba60 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem&) "Bilder/papibilder/Photos/Urlaub/VORSCHAU.PS" 6 "Harte Verknüpfungen werden bei der Synchronisation nicht unterstützt." 
```
1. Web server error log:
2. ownCloud log (data/owncloud.log):

**Comment by iamwebrocker** [comment]
I can confirm that this seems to be a client issue: I have a "normal" file that is "seen" as a hard link by the client, which then refuses the sync. On another machine the same file syncs w/o problems. 
I've yet to find the diffences, since both machines have the same OS + client version.
OS X 10.9.5, Client 1.7.0 (build 1490)

    "14:52 :: cloud/container.tcr  :: ownCloud :: Harte Verknüpfungen werden bei der Synchronisation nicht unterstützt."

The only difference I can think of is that the "problem" machine has the complete hard drive under FileVault encryption, and the other the home-directory only (need to verify this, not 100% sure tho) -- could this result in the client "seeing" hard links instead of "real" files?
In terminal/console the file in question is a file. not a link:

    -rw-r--r--     2  me  staff  67108864  30 Nov 23:39  container.tcr
    -rw-r--r--@  1  me  staff  49706  30 Jul 14:52  test.png
    ...

The "test.png" syncs w/o problems, the "container.tcr" is seen as a "hard link" by the client.

**Comment by bbbco** [comment]
I have this same issue. I was trying to sync some mp3 files that are not hard links, and the client would not sync the files because of this error.

**Comment by ssieb** [comment]
@iamwebrocker That file definitely has a hard link to it somewhere.
> -rw-r--r--     2  me  staff  67108864  30 Nov 23:39  container.tcr

That 2 means the file is hard linked.

**Comment by iamwebrocker** [comment]
@ssieb ah, thx - do you know of a way to find/see where this link from? this would explain why, after overwriting the file with a copy from an external backup, it was again synced -- but only once, then again it was seen as hard linked. i suspect the disc encryption somehow, but I am at a loss how to verify this…

**Comment by bbbco** [comment]
Hmmm ... my files indicate the multiple links too, but I can't seem to find the alternate paths ...

**Comment by ssieb** [comment]
You can use the find command to search for what is linked.  I don't know how your filesystem is partitioned and I don't know OS/X, so I'm assuming the GNU utilities work the same there.  Do `df filename` and see the last value on the line is the mountpoint under "Mounted on".  Now do `find /mountpoint -xdev -samefile filename`.  That will search through the entire filesystem and find all the files linked to that inode.
See https://www.gnu.org/software/findutils/manual/html_node/find_html/Hard-Links.html for more details.

**Comment by iamwebrocker** [comment]
@ssieb thank you. :+1:

**Comment by iamwebrocker** [comment]
Hi, I just reproduced the problem.

1) ls --la with a working/syncing version of the file:

    -rwxrwxrwx   1 me  staff  67108864  8 Jan 18:44 container.tcr

2) open this file with truecrypt - which mounts the container in the OS X finder. Again ls -la:

    -rwxrwxrwx   2 me  staff  67108864 12 Jan 11:13 container.tcr

AHA. So truecrypt changes the file.

3) unmount container, exit truecrypt. Again ls -la:

    -rwxrwxrwx   2 tom  staff  67108864 12 Jan 11:13 koffer.tcr

The file stays hard linked. Now to the voodoo part, using the commands by @ssieb above:

    df ./container.tcr
    Filesystem 512-blocks      Used Available Capacity  iused    ifree %iused  Mounted on
    /dev/disk1  497783608 257733720 239537888    52% 32280713 29942236   52%   /
    sudo find / -xdev -samefile container.tcr
    /.MobileBackups/Computer/2015-01-12-105705/Volume/Users/Shared/me/ownCloud/container.tcr

Bam. So there's the culprit. Is this Time Machine interfering? :-/ Yes, seems so: http://www.classicyuppie.com/what-crap-is-this-os-xs-mobilebackups/

pfeeeww…

**Comment by bbbco** [comment]
Following @ssieb 's advice:

````
[bbbco@localhost CE06518106516C09]$ pwd
/mnt/CE06518106516C09
[bbbco@localhost CE06518106516C09]$ ls -al Music/Anberlin/Blueprints\ for\ the\ Black\ Market/01\ Readyfuels.mp3 
-rwxrwxrwx 2 root root 3487148 Oct 30  2008 Music/Anberlin/Blueprints for the Black Market/01 Readyfuels.mp3
[bbbco@localhost CE06518106516C09]$ df Music/Anberlin/Blueprints\ for\ the\ Black\ Market/01\ Readyfuels.mp3
Filesystem     1K-blocks      Used Available Use% Mounted on
/dev/sdb1      488383484 154204828 334178656  32% /mnt/CE06518106516C09
[bbbco@localhost CE06518106516C09]$ find /mnt/CE06518106516C09 -xdev -samefile Music/Anberlin/Blueprints\ for\ the\ Black\ Market/01\ Readyfuels.mp3
/mnt/CE06518106516C09/Music/Anberlin/Blueprints for the Black Market/01 Readyfuels.mp3
[bbbco@localhost CE06518106516C09]$ 

````
See? I don't know why my files are showing as having two hard links, but I can only find the one path. I'm using Fedora 19.
