### ISSUE TITLE
Qt5 everywhere. Drop legacy Qt4 support.

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#2558]
It would be very beneficial if we could build against Qt5 on all platforms that we support. That is no problem for MacOSX and Windows as we have to ship with the Qt. However on Linux, where we want to depend on the upstream packages, we need to double check. From which versions of the distros are Qt5 packages available in the main repositories?

| Distro | first (supported) version that provides Qt5 | has Webkit |
| --- | --- | --- |
| openSUSE | openSUSE 13.1, before in other repo | yes |
| Fedora | ? |  |
| Ubuntu | 14.04 LTS provides Qt5-default, earlier? |  |
| Debian | ? |  |
| CentOS 6/7 | Qt 5.4 via EPEL | yes |

Also, do the version provide Webkit?

https://github.com/owncloud/client/wiki/Qt-5-Dependency-on-Linux

**Comment by guruz** [comment]
Yes, please get all those technology-scared Linux users to a newer Qt version.

Another nice reason for using Qt5: We can use the function pointer signal slot syntax..

http://woboq.com/blog/new-signals-slots-syntax-in-qt5.html

Would easily fix issues as
https://github.com/owncloud/client/commit/b0dbb49ca84a42f701f75270334f3e1714de9074 https://github.com/owncloud/client/commit/12ac9f9aa9cd97d4331aa3c0d59d49defd4c5157 https://github.com/owncloud/client/commit/803cb5d015f998c9d60112d977f5b495730ed320

**Comment by dragotin** [comment]
For the upcoming 1.8.0 client: packages for openSUSE starting with 13.2 now build against Qt5. In 13.1 it uses Qt 5.3.x and thus neon is still required, but in Factory there (currently) is Qt 5.4.0 and we can build without neon.

Please help testing the packages from https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3Anightly&package=owncloud-client if possible.

If other distros have Qt5 packages in their default repositories available I am happy to integrate patches into our build service projects.

**Comment by dragotin** [comment]
Fedora 21 is also building against Qt5.

**Comment by danimo** [comment]
I have an experimental OBS build for CentOS 7 (soon 6) that depends on EPEL for Qt 5.4.

I'm looking for testers and input.

**Comment by danimo** [comment]
@moscicki Can you run this solution (Client on CentOS/SCL requiring EPEL) past your deployment guys? It would allow us to jump to Qt 5.

**Comment by moscicki** [comment]
@danimo: no problem, it would help us to get the CentOS 6 build to test first. Is that available already?

Also, please check with @dragotin and @jnweiger : our Linux team have prepared the "proper" (based on the mechanism of Software Collection) packaging scheme which will allow you to install the sync client in the completely standard and canonical way on Redhat-based systems. In particular the alternative versions of software which otherwise would collide with the baseline versions of software installed in the OS. They provided RPMs for 1.7 client. To be integrated with your OBS builds (I hope). Do you have feedback on this?

**Comment by jaroslawp** [comment]
As a part of that Linux team: I would be interested in the feedback too (client packaged as @moscicki  desribed is there: http://linuxsoft.cern.ch/tmp/owncloud-client/)

**Comment by jnweiger** [comment]
@jaroslawp Thanks for your detailled description! 
The URL is down today. I have saved a copy here: 
https://s3.owncloud.com/owncloud/public.php?service=files&t=dcd3c210435abcfda90b08aa45a84f92&download

**Comment by jaroslawp** [comment]
that URL is back again, sorry. (scheduled intervention ..)

**Comment by danimo** [comment]
@jaroslawp That's very cool actually. Going the SC route is the next logical step. Also our own SC would allow putting patching Qt to adopt it to our needs without bothering the system. This is something we already do for Windows and Mac OS on several occasions, even though we try to avoid it as much as possible. So thanks for doing that!

At the same time, I wonder how much work it would be to have an SC including Qt5 (which is a bit more complex to package). Have you looked into that?The good part is that it's already in EPEL, so an SC would "only" have to fork those packages and keep them in sync with upstream. On the upside, when adopting Qt from EPEL in the SC, we could lose neon and its dependencies. I think that's quite a benefit.

**Comment by jaroslawp** [comment]
@danimo: I should have some time to look at this (Qt5) next week, will keep you updated !

**Comment by guruz** [comment]
Also relevant for HiDPI https://github.com/owncloud/client/issues/2558

**Comment by moscicki** [comment]
@guruz:

I come to this discussion from this issue #3194. Let me share the enterprise point of view: the main function of software such as owncloud is to protect user data. All other functionality comes after. 

If you believe that using the packages provided by the OS assures the user data protection -- OK. But certainly obsolete and unmaintained code paths (such as #3194) -- do not. Hence if the obstacle to remove the dangerous code is unavailability of Qt5 in a given moment of time on a given platform then there must be a workaround. For example, ship the Qt 5 until the distribution provides it officially. Then remove it and align with your long term policy.

**Comment by dragotin** [comment]
@jaroslawp have you had any fun with qt5 yet?

**Comment by danimo** [comment]
Here is a list of features that we lose if a distro has a earlier version of Qt 5. Maybe we can convince packagers to upstream certain features/bug fixes:

Feature/fix                       | first added | Workaround | Backportable
---------------------------------| ---------------|------------------|------------------
Unity/Plasma systray support | Qt 5.5 | ? | ?
QNAM Bandwidth Limitier fix | Qt 5.4.0 (?) | ? | yes
QNAM Download Corruption fix | Qt 5.4.2 | ? | yes
QNAM Connection Closed fix | Qt 5.?.? | ? | yes

**Comment by guruz** [comment]
Also removable when we switch: https://github.com/owncloud/client/tree/master/src/3rdparty/qjson

http://doc.qt.io/qt-5/json.html

**Comment by jaroslawp** [comment]
@dragotin , @danimo : I haven't looked into packaging Qt5 as Software Collection for now (for RHEL6/7): I'm not sure how much interest there is in going that way ...

**Comment by dragotin** [comment]
@jaroslawp well, our interest is in a properly working solution with Qt5 as we want to drop Qt4 support from the sync client. And there was indeed some progress at least with Qt 5 on CentOS6 and CentOS7: 
https://build.opensuse.org/package/show/isv:ownCloud:devel/qt5-qtbase
https://build.opensuse.org/package/show/isv:ownCloud:devel/qt5-qtwebkit

These packages install to ```/opt/qt-54``` as the qt4 based packages did before. However, we haven't switched the official builds to the qt5 based packages yet, much more testing is needed. Your feedback on that would be welcome. 

About software collections: They are not supported in OBS by default, and I haven't investigated enough to understand the benefits the client installation would get from them. I am sure we can fix the OBS problem once we understood the benefits of the software collections.

**Comment by AdamWill** [comment]
There are Qt5 packages for EL 6 and 7 in EPEL, which is a very widely known and used repo containing extra packages maintained through the Fedora community:

https://fedoraproject.org/wiki/EPEL

I'm pretty sure anyone who wanted to run on EL would be fine with using EPEL, no need to reinvent wheels.

**Comment by danimo** [comment]
@AdamWill Unfortunately, this is where you are wrong. We have a lot of commercial users that refuse to install EPEL.

**Comment by AdamWill** [comment]
But they'll use an OBS repo? That seems...bizarre.

**Comment by guruz** [comment]
Note: Even 5.5.1 has some known annoying network bugs, so either 5.5.2 or 5.6 are the options for platforms where we don't ship Qt.

**Comment by guruz** [comment]
More reasons to switch to Qt5: https://github.com/owncloud/client/issues/4094

**Comment by ogoffart** [comment]
In more words: nobody is testing Qt4.  Our own QA tests only on Windows/Mac where it is only Qt5, and us developers are also using Qt5.

**Comment by jnweiger** [comment]
I'll give Qt5 a try: https://build.opensuse.org/package/show/isv:ownCloud:desktop:qt5/owncloud-client

**Comment by jnweiger** [comment]
How is that?:
Ubuntu_14.04$ ldd /usr/bin/owncloud | grep -i qt5
<pre>
	libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007feb23126000)
	libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007feb22de2000)
	libQt5WebKitWidgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5WebKitWidgets.so.5 (0x00007feb22b9f000)
	libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007feb22920000)
	libQt5Xml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5 (0x00007feb223c7000)
	libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007feb21d7a000)
	libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007feb216d4000)
	libqt5keychain.so.0 => /usr/lib/x86_64-linux-gnu/libqt5keychain.so.0 (0x00007feb20eb9000)
	libQt5WebKit.so.5 => /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5 (0x00007feb1d33f000)
	libQt5OpenGL.so.5 => /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5 (0x00007feb1d0db000)
	libQt5PrintSupport.so.5 => /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5 (0x00007feb1ce76000)
	libQt5Sensors.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Sensors.so.5 (0x00007feb1cc3a000)
	libQt5Quick.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5 (0x00007feb18c8a000)
	libQt5Qml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5 (0x00007feb18683000)
	libQt5Sql.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5 (0x00007feb18444000)
	libQt5Positioning.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Positioning.so.5 (0x00007feb1820e000)

</pre>

**Comment by jnweiger** [comment]
@danimo pieep, what about Unity and Icons?

**Comment by dragotin** [comment]
CentOS7 is moving to Qt5 with qt5 packages installing to /opt, see test build in isv:ownCloud:nightly. For other systems, I  do not see any engineering power to package our own Qt, but we need to wait until Qt5 is coming from upstream.

**Comment by vitaleon** [comment]
OpenSUSE's newest release of the stable distribution Leap 42.1 has Qt 5.5.0. But it's 0%{?suse_version} == 1315 is identical with  SLE 12 one. Could you please enable qt5 support for it checking 0%{?is_opensuse} in spec file.

**Comment by dragotin** [comment]
@vitaleon thanks for the hint. Added that to the spec file template. The soonish released 2.1.1 will build against Qt5.

**Comment by guruz** [comment]
For Ubuntu also see https://github.com/owncloud/client/issues/4334#issuecomment-176927306

**Comment by jnweiger** [comment]
When you say 1315 that made me curious. It should be 133x or so.
Here is what they did: Not exactly nice:

<table>
<tr>
<td> openSUSE_13.1 </td><td> suse_version = 1310 </td><td> is_opensuse = '%{is_opensuse}' </td>
</tr><tr>
<td> openSUSE_13.2 </td><td> suse_version = 1320 </td><td> is_opensuse = '%{is_opensuse}' </td>
</tr><tr>
<td> openSUSE_Factory </td><td> suse_version = 1330 </td><td> is_opensuse = 1 </td>
</tr><tr>
<td> openSUSE_Leap_42.1 </td><td> suse_version = 1315 </td><td> is_opensuse = 1 </td>
</tr><tr>
<td> SLE_12 </td><td> suse_version = 1315 </td><td> is_opensuse = '%{is_opensuse}' </td>
</tr>
</table>

**Comment by jnweiger** [comment]
Building 2.2.4 owncloud-client for Ubuntu 14.04 with Qt-5.2.1 here:
* https://build.opensuse.org/package/show/isv:ownCloud:desktop:qt5deb/owncloud-client
Is this vulnerable to file corruptions?

**Comment by michaelstingl** [comment]
A user reported about their oC client for Ubuntu 14.04:

> Qt4 network libraries don't work with our F5 load balancer

@guruz @crrodriguez What could be the solution there?

**Comment by ogoffart** [comment]
> Is [Qt-5.2.1] vulnerable to file corruptions?

Yes it is,  but Qt 4.8 is even worse, so no regressions there.

> Qt4 network libraries don't work with our F5 load balancer, What could be the solution there?

The package built with Qt5.

**Comment by ShalokShalom** [comment]
I guess this can be closed?

**Comment by guruz** [comment]
@ShalokShalom No, we're still supporting Qt 4 currently. We'll probably drop that next year. On Linux we use the system packages which sometimes are still based on Qt4.

**Comment by ShalokShalom** [comment]
Qt4 itself gets no maintenance anymore?

**Comment by moscicki** [comment]
> Is this vulnerable to file corruptions?

This sounds very worrying. Could someone please elaborate what it means?

**Comment by ogoffart** [comment]
@moscicki:  the corruption bug you investigated was fixed in Qt 5.4.2 only.   However we are working around it in the client by forcing connection reset with older version of Qt, so file corruption should not happen normally.

**Comment by guruz** [comment]
> Qt4 itself gets no maintenance anymore?

Qt4 is EOL by The Qt Company as far as I know.

> so file corruption should not happen normally.

...plus we send checksums to CernBox.

**Comment by ShalokShalom** [comment]
`Qt4 is EOL by The Qt Company as far as I know.

Thats what i mean. Is it safe, since that?

**Comment by jaroslawp** [comment]
@ShalokShalom : guess depends where from you take it (on RHEL7/CentOS7 we get qt 4.8.5 from Red Hat / CentOS: and according to their policies that version will be supported - including security fixes - still for quite long time - more than a  few years until support for 7 will be over)

**Comment by ShalokShalom** [comment]
I see.

**Comment by guruz** [comment]
Superseded by https://github.com/owncloud/client/issues/5470

**Comment by jnweiger** [comment]
See also https://bugreports.qt.io/browse/QTBUG-31762

**Comment by vladimiroff** [comment]
Now that Qt4 is no longer supported it might be worth removing those checks if QT_VERSION is 4.x.
```
--> grep -r "QT_VERSION [<=>]* QT_VERSION_CHECK(4" ./client 
5
```

**Comment by michaelstingl** [comment]
@vladimiroff ==> 2.3.1 (see https://github.com/owncloud/client/issues/5470)
