### ISSUE TITLE
Repeatable client failure, possibly architecture related

### ISSUE THREAD

**Issue by moaxey** [owncloud/client#2560]
I have server running 7.0.3 on wheezy and other clients on android, wheezy and mac all running smoothly.

## Problem description

A strange problem re-occurs on my 32bit atom eeepc client (3.2.0-4-686-pae)-- also running on wheezy. It began on the day I upgraded my server to 7.0.3

The client worked for a few hours until suddenly the settings window says not connected (see screenshot). When reconfiguring It lets me choose which folders to sync and gives repeated affirmative notifications about a successful sync but no files are synced, the icon is the the grey state and the processor is repeatedly hogged by owncloud. For a few weeks, no amount of purging, reinstalling or reconfiguring would have any effect. 

Today I reinstalled a new system, and for a few hours everything worked perfectly.

At the moment I turned on the Mac (it had a file to sync upwards) the behaviour described earlier began again. 

Reinstalling, purging and reconfiguring could not change the situation. I built the latest client from git and the situation remains the same.

These lines appear in the terminal during launch but do not appear in the log.
SocketApi:  creating "/ownCloud" false 
SocketApi:  can't start server "/ownCloud/socket" 

I have a log file, not sure what is the best way to attach it here. ~3600 lines. If anyone is interested I can probably capture a log of it first occuring by installing into a live cd session.

![screenshot from 2014-11-29 16 58 17](https://cloud.githubusercontent.com/assets/538598/5233673/5ede621e-77e9-11e4-81d1-6ea098aee747.png)

**Comment by guruz** [comment]
Please re-try this with a 1.8 build and without using sqlite3 as DB on the oC server.
