### ISSUE TITLE
[1.7.0] Ubuntu 14.04: new directories sometimes have mode 660 (not 770)

### ISSUE THREAD

**Issue by floe** [owncloud/client#2561]
On my Ubuntu machine, I sometimes see new directories being synced appearing with filemode 660 instead of 770. When I manually fix the permissions, everything works again after a short while. Before I fix the permissions, I get loads of "permission denied" errors in the log when the client tries to create files in the new directory.

**Comment by guruz** [comment]
Does this still happen with a recent client version or a newer ubuntu? If yes please re-open..
