### ISSUE TITLE
Shared directory sync ends with lots of empty files

### ISSUE THREAD

**Issue by sargue** [owncloud/client#2566]
I have two accounts on my owncloud server. One shares a big directory with the other one. After a while the client (1.6.4), which was online all along, starts downloading the new directory with about 10k files, 4k directories, 2.6 GB.

### Expected behaviour
After a while all directories and files inside the new share directory should be on the local drive.

### Actual behaviour
After a while all files and directories are on the local drive, but measuring just 488 MB. Upon further examination I see most files are zero bytes.

I check the client and I see there is a new one (1.7.0). I download and install the new one. Upon start the client enters discovery phase (long) and finally says we are in sync (green). The directory is kept the same (488 MB, lots of empty files).

### Steps to reproduce
It's the first time I notice this.

### Server configuration
Operating system: Debian Linux 64 bits, 3.10.23 kernel

Web server: Apache 2.2.22-13+deb7u3

Database: MySQL 5.5.40-0+wheezy1

PHP version: 5.4.35-0+deb7u2

ownCloud version: 7.0.3

Storage backend: Local drive, ext4 file system

### Client configuration
Client version: 1.6.4 first, 1.7.0 later

Operating system: Windows 8.1

OS language: Catalan

Installation path of client: D:\apps\ownCloud

### Logs

https://gist.github.com/sargue/5320680470221f348f74

I don't know how to proceed now. Maybe unsharing and sharing again? There is no "reindex" functionality that I am aware of.

**Comment by guruz** [comment]
#Please re-open the bug if this still happens with a recent server / client version. #
