### ISSUE TITLE
[Windows] [Installer] Startup as wrong user after installation

### ISSUE THREAD

**Issue by tps800** [owncloud/client#2568]
https://github.com/owncloud/mirall/issues/1228 seems to be the same error.

### Expected behaviour
Running client 1.7.0 syncing data

### Actual behaviour
Error: Unable to initialize a sync journal (German: Synchronisationsbericht konnte nicht initialisiert werden).

### Steps to reproduce
1. Install Windows Client 1.6.3 on Windows 7, Sync your data.
2. Upgrade to Windows Client 1.7.0, keep your data directory.
3. Synchronisation fails

### Server configuration
Operating system: Oracle Linux 6.6

Web server: Apache 2.2.4

Database: PostgreSQL 9.3

PHP version: PHP 5.5

ownCloud version: ownCloud 7.0.3

Storage backend: Filesystem

### Client configuration
Client version: 1.7.0

Operating system: Windows 7

OS language: German

Installation path of client: C:\Programme (x86)\ownCloud

### Solution

If you set "Start ownCloud Client after install", the ownCloud Client is started from the user SYSTEM who upgraded the old application to the new one. This user does not have access to the database of the user who started the upgrade -> Upgrading the database fails, synching fails.

Simple solution: quit ownCloud Client, then restart it. This time it runs as you, having access to the database -> Upgrading the database finishes successfully, synching starts.

Maybe get rid of "Start ownCloud Client after install"?

**Comment by danimo** [comment]
I have updated the UAC component which could be at fault. Please try with http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.5345-nightly20150803-setup.exe

**Comment by danimo** [comment]
@tps800 can you test, please?

**Comment by guruz** [comment]
@tps800 Any news from your side?

**Comment by rperezb** [comment]
@davitol can you please check this one?

**Comment by ogoffart** [comment]
I assume this is fixed.
