### ISSUE TITLE
[Windows Vista] Overlay icons don't work, cause Windows Explorer and other applications to hang

### ISSUE THREAD

**Issue by awnz** [owncloud/client#2576]
I've had this issue on an older Windows Vista PC.

Overlay icons failed to work, and the shell kept hanging on a number of file operations (like opening an attachment in MS Outlook, renaming a file, plus various others) until I manually removed the ownCloud overlay entries at HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers.

Once removed, the freezing issue went away completely and everything resumed running smoothly.

If this is more widespread than the one Vista PC I have access to, probably easiest to just not offer that feature on Vista.

**Comment by awnz** [comment]
Finally got to re-test - bug still present in v1.7.1 (build 4382).

Sorry for taking so long!

**Comment by ogoffart** [comment]
I was still unable to reproduce.

**Comment by clemenlg** [comment]
Hi, i've the same issue in a Windows Vista x32.
I've a new Vista installation, because the pc freezes sometimes.
This issue appears some weaks ago (before works ok).

**Comment by guruz** [comment]
We're about to release the beta1, please try with that..

**Comment by danimo** [comment]
As beta1 is delaying for organizational reasons, could you try http://download.owncloud.com/desktop/daily/owncloud-1.8.0.4676-nightly20150204-setup.exe?

**Comment by jturcotte** [comment]
This issue is now tracked by #2680

A prospective fix should be available in the next nightly build at http://download.owncloud.com/desktop/daily/
