### ISSUE TITLE
[Windows] 1.7.0 Conflict files created when save is initiated during sync

### ISSUE THREAD

**Issue by jkurelek** [owncloud/client#2577]
### Actual behaviour (I flipped this around, hope that's ok)
When working on a file within my owncloud repository, if a save is initiated while it is currently being synced, the file is reverted back to the previous version (from the db), while the current version (that is open) is labelled as a conflict file. Commonly happens when working on a MATLAB script or LaTeX document, since the file is saved every time the code is recompiled, but I've also observed this happening for ppt and doc files if you save repeatedly and quickly.

### Expected behaviour
If a save is initiated, I suppose the sync should be paused and only resumed once the save is completed? 

### Steps to reproduce
1. Modify a file within your owncloud repository while the desktop client is running
2. Once the desktop client identifies a change has occurred and begins to scan/sync the file (not sure exactly what the required timing is), re-save the file. 
3. A conflict file will be created.

### Server configuration
Operating system: Windows 7 x64

Web server: Apache

Database: SQLite

PHP version: 5.5.12

ownCloud version: 7.0.3

Storage backend:?

### Client configuration
Client version: 1.7.0

Operating system: Windows 7 x64

OS language: English

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
```
7:43 PM   dir/[filename].texownCloud       Not allowed to upload this file because it is read-only on the server, restoring; Restoration Failed: Error downloading https://[server_address]/owncloud/remote.php/webdav/dir/[filename].tex - server replied: Requested Range Not Satisfiable          
7:43 PM   dir/[filename].figownCloud       Error downloading https://[server_address]/owncloud/remote.php/webdav/dir/[filename].fig - server replied: Internal Server Error          
7:43 PM   dir/[filename].epsownCloud       Error downloading https://[server_address]/owncloud/remote.php/webdav/dir/[filename].eps - server replied: Internal Server Error          
7:43 PM   dir/[filename].outownCloud       Not allowed to upload this file because it is read-only on the server, restoring; Restoration Failed: Error downloading https://[server_address]/owncloud/remote.php/webdav/dir/[filename].out - server replied: Requested Range Not Satisfiable          
7:42 PM   dir/[filename].logownCloud       Not allowed to upload this file because it is read-only on the server, restoring; Restoration Failed: Error downloading https://[server_address]/owncloud/remote.php/webdav/dir/[filename].log - server replied: Requested Range Not Satisfiable          
7:42 PM   dir/[filename].blgownCloud       Not allowed to upload this file because it is read-only on the server, restoring          
7:42 PM   dir/[filename].bblownCloud       Not allowed to upload this file because it is read-only on the server, restoring          
7:42 PM   dir/[filename].auxownCloud       Not allowed to upload this file because it is read-only on the server, restoring; Restoration Failed: Error downloading https://[server_address]/owncloud/remote.php/webdav/dir/[filename].aux - server replied: Requested Range Not Satisfiable 
```

2. Web server error log: Can provided if needed

3. ownCloud log (data/owncloud.log):
```
{"app":"webdav","message":"Sabre\\DAV\\Exception\\RequestedRangeNotSatisfiable: The start offset (8586959) exceeded the size of the entity (8586959)","level":4,"time":"2014-12-03T19:41:45+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\RequestedRangeNotSatisfiable: The start offset (33638) exceeded the size of the entity (33638)","level":4,"time":"2014-12-03T19:42:49+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\RequestedRangeNotSatisfiable: The start offset (2461696) exceeded the size of the entity (2461696)","level":4,"time":"2014-12-03T19:42:50+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\RequestedRangeNotSatisfiable: The start offset (12180) exceeded the size of the entity (12180)","level":4,"time":"2014-12-03T19:42:50+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\RequestedRangeNotSatisfiable: The start offset (8586959) exceeded the size of the entity (8586959)","level":4,"time":"2014-12-03T19:44:54+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\RequestedRangeNotSatisfiable: The start offset (33638) exceeded the size of the entity (33638)","level":4,"time":"2014-12-03T19:46:06+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\RequestedRangeNotSatisfiable: The start offset (2461696) exceeded the size of the entity (2461696)","level":4,"time":"2014-12-03T19:46:07+00:00"}
{"app":"webdav","message":"Sabre\\DAV\\Exception\\RequestedRangeNotSatisfiable: The start offset (12180) exceeded the size of the entity (12180)","level":4,"time":"2014-12-03T19:46:08+00:00"}
```

**Comment by Chluz** [comment]
I'm having the same issue with the 1.8 sync client with Matlab files : if the file is saved whilst the sync is occurring, I get conflicts. At this point I'm having to turn off owncloud everytime I run simulations.

**Comment by rschiewer** [comment]
Having exactly the same issue with LaTeX files. The sync client tends to revert minor changes in my tex, aux and log files again and again, which sometimes creates conflict files and sometimes even results in undone modifications. Thus, if I add some new text content to my tex file, it may be overwritten during synchronization :/
Client is version 1.8.0, owncloud version is 8.0.2

**Comment by dragotin** [comment]
This sounds severe. Please provide us with a client logfile when that happens again, along with the file name for which it happened. Thanks.

**Comment by ckamm** [comment]
@Chluz @rschiewer Could you provide log files for these? (run with --logfile log.txt). I'm curious if your files also have these odd permissions.

**Comment by Chluz** [comment]
I will provide them as soon as possible. The files in question are my PhD thesis and matlab files, and I just need to do a few things before I can submit it. Before that I'm keeping owncloud off to avoid having to deal with conflicts :) Hopefully by tonight or tomorrow I should have logs for you

**Comment by Chluz** [comment]
Hum, I'm running a simulation now with the owncloud log file being outputted at the same time, and of course no conflicts for the moment. I'll keep an eye on it and tell you. I did update owncloud ubuntu package to the latest revision (so 8.0.2-2 to 8.0.2-7 I believe) in between, but I don't think that would have changed anything

**Comment by Chluz** [comment]
I've tried compiling the thesis latex document as well, recompiling whilst files were being uploaded (which created conflicts in the past) but no conflicts. Apart from the server side Ubuntu package update nothing changed, so I don't know what fixed it. 
In my case I would consider the issue solved (I don't know for the others in this thread though)

**Comment by ckamm** [comment]
@jkurelek @rschiewer Full log files would help tremendously for tracking this down.

Apart from these, I think this is the key problem I saw in @jkurelek's earlier log file:
* The second run detects a change in Mean.m and decides to upload it.
* It fails because Mean.m file has RDNVCK permissions. That makes no sense because C and K are for directories only. Additionally the W permission is missing, so the file is downloaded instead and a conflict is generated.

@ogoffart As far as I know permissions always come from the server. Any ideas why a file'd have these odd permissions (or whom to forward this to on the server side)?

**Comment by dragotin** [comment]
@DeepDiver1975 can you explain why the file has "CK" permission?

**Comment by jkurelek** [comment]
I've done some recent re-testing on this issue. Since my original post my client version is now 1.8.0 and ownCloud is 8.0.2

In repeating the steps that originally created the conflict files (in my tests I've been re-compiling a Latex document while the sync is running), I no longer get conflict files. Instead I get the client returning this error:  
![capture](https://cloud.githubusercontent.com/assets/5564064/7045520/e038b410-ddcc-11e4-8aa1-64f7dfe770b9.PNG)

Here is an accompanying log file for analysis: https://srb.no-ip.biz/owncloud/index.php/s/PvNPFqqQK22Plad (link expires in 2 days)

For scrubbing through the log file, the files in question are any that contain "ME 770 Paper Review - John Kurelek" (the .aux, .bbl, .log files etc..). 

As far as I can tell the issue is somewhat resolved. The sync tries to upload a file that has changed and stops itself, hence the error. Subsequent syncs then successfully upload the updated file (not capture in the log file since it gets quite long).

Please let me know if there's any other info I can provide to help. Cheers.

**Comment by ckamm** [comment]
@jkurelek Thank you for re-testing and for the log file. I'm glad the spurious conflict files no longer appear.

The errors you're seeing seem unrelated, so I'm closing this issue.

The "internal server error (could not rename part file to final file)" error you're seeing now seems server-related. Could you check the permissions of these files on the server filesystem?
