### ISSUE TITLE
Install Defaults and Sync size for Desktop Install Wizard

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#2580]
As a user of ownCloud, I would like to have the default selection "choose what I sync" when I install the client so that I don't start syncing 11GB (for example) of data to my desktop via external storage by default.

Acceptance Criteria:
- Have the default be "choose what I sync" (today it is sync everything)
- Have the total size and available disk size of the sync everything result be displayed for this user next to the "sync everything" with the heading "This will use XGB of your remaining YGB of free space".

@dragotin

**Comment by dragotin** [comment]
@DeepDiver1975 we need your help! A PROPFIND on a dir returns the entry 
```
DAV: quota-used-bytes = 8223121
```
That is the size of the dir, magically computed recursively, awesome stuff.

But how does that work with a shared dir? Can you confirm that it calculates the data size of the shared contents? That is important for this feature, and I remember there have been discussions about this.

**Comment by ogoffart** [comment]
The size is now shown (using the quota-used-bytes reported from the server)

**Comment by ogoffart** [comment]
So how do we know what is supposed to be sync'ed and what is no supposed to be sync'ed?

**Comment by dragotin** [comment]
@ogoffart In a mail about this @MTRichards says:
*"So, to solve this - what I propose here is a branded client option. A switch that allows the setup wizard to generate either: sync everything by default, or sync nothing."*

In a second chapter, @MTRichards says: 
*"When a customer is already syncing, if a large directory is added - then that will sync automatically. This same issue I intend to fix with shared directory warnings "Do you want to accept the share", then it will sync but at least people will know a new root folder is added."*
However I am not sure if that means that we should require user interaction to accept a new top level dir if it is large. 

Maybe rather these two things:
- If we detect in the update phase that a new top level dir is larger than lets say 200 MB we do not include it to the sync but set it to not selected in selective sync.
- If we sync a new toplevel dir we show a notification saying "A new toplevel dir with size of xx MB was added to the sync", or, we add a size information to our already existing notification.

**Comment by ogoffart** [comment]
The sync behaviour after the wizard is part of another issue ( #2707 )

So then would the theme (branding) contains a flag to unselect everything in the selective sync dialog?  and preselect that option?

**Comment by MTRichards** [comment]
Right - there are two problems:
1) initial setup - syncing everything by default (click, click, click user behavior) - we want them to have to think before accepting to sync everything - particularly when it will fill the local disk
2) after initial setup - these are a good idea:

>    If we detect in the update phase that a new top level dir is larger than lets say 200 MB we do not include it to the sync but set it to not selected in selective sync.
    If we sync a new toplevel dir we show a notification saying "A new toplevel dir with size of xx MB was added to the sync", or, we add a size information to our already existing notification.

**Comment by MTRichards** [comment]
@ogoffart that is the short term fix that has been requested, yes. To be able to have the default installer not sync everything by default on initial setup.

**Comment by ogoffart** [comment]
So i added Theme::wizardSelectiveSyncDefaultNothing.  Which theme do need this setting?

**Comment by ogoffart** [comment]
This can be tested using the testpilot theme.

**Comment by lmaestro** [comment]
@ogoffart  In version1.8.0-nightly20150126 (build 1941) the option "choose what I sync" is not the default option.

**Comment by ogoffart** [comment]
It is only the default in theme that have this option such as the testpilot theme

**Comment by lmaestro** [comment]
Waiting to a testpilot build to verify that the "choose what to sync" is the option by default.

**Comment by lmaestro** [comment]
@danimo Can you provide me the test  build?

**Comment by danimo** [comment]
Working on it

**Comment by lmaestro** [comment]
I tested testpilot theme and now when you launch the app after introduce the server and credentials, the pop-up of "Choose what to sync" opens but if you close it, the option chosen is "Sync everything from the server". Maybe the option by default when the pop-up is closed should be "Choose what to sync".

Also the pop said "Unchecked folder will be removed from your local...." and by default all the folder are unchecked. This message should be changed.

**Comment by ogoffart** [comment]
I change the wording.
It now reads: `Choose What to Sync: Select remote subfolders you wish to synchronize.` in this configuration.

But if you cancel that dialog, then it will sync everything because if you cancel the choose what to sync dialog it means everything is selected.

**Comment by lmaestro** [comment]
Now the message is :
![screen shot 2015-02-05 at 6 03 39 pm](https://cloud.githubusercontent.com/assets/4689430/6064893/560a84c6-ad61-11e4-8e19-12e3ae921c02.png)

In my opinion this feature is closed, if anyone don't think so, please reopen it.

**Comment by ogoffart** [comment]
Another option could have been to set a default remote folder in the theme (eg. `syncclient/`   And if the user wants to add a sharepoint folder he can add it using the add folder feature)
