### ISSUE TITLE
[1.7.0] Lost URL config in ownCloud.cfg, rest is still correct

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#2585]
I don't have steps to reproduce, but it happened to me only once when starting KDE today.
The sync client started and showed a popup asking for the OC URL.
After entering my kwallet password I manually restarted the sync client.
It still asked for the OC URL.

Looking at the config files, I saw that the URL was gone, this is the **full** ownCloud.cfg
```
[General]
optionalDesktopNotifications=true
```

Other files like folder config are still there.

### Versions
owncloud-client-1.7.0-6.1.x86_64
openSUSE 13.2 x86_64
KDE 4.14.3

@dragotin @ogoffart

**Comment by guruz** [comment]
@PVince81 Did it happen again?

**Comment by PVince81** [comment]
I haven't seen this happening any more

**Comment by dragotin** [comment]
Ok, closing this as it is supposed to be fixed with a more recent Qt version.
