### ISSUE TITLE
Allow to sync excluded sub folders 	separately

### ISSUE THREAD

**Issue by godfuture** [owncloud/client#2588]
When a folder was exculded, it cant be synced as a new sync folder, because a parent is already in sync.

**Comment by MorrisJobke** [comment]
cc @MTRichards @gig13 Because you requested this.

**Comment by bboule** [comment]
@MorrisJobke @MTRichards Do we need to do anything with this? or can we simply close this out?

**Comment by MorrisJobke** [comment]
I talked with @dragotin about this and he said, that there is a technical limitation for this and it's really hard to implement and nearly the whole sync algorithm needs to be redone to bring this feature in, which is a very special.

**Comment by MTRichards** [comment]
This is by design as it works today, so not planning on updating this anytime soon.

**Comment by bboule** [comment]
OK so it sounds like we can close this out as no action will be taken?

**Comment by MorrisJobke** [comment]
> OK so it sounds like we can close this out as no action will be taken?

Correct.

**Comment by ogoffart** [comment]
This is fixed in 2.5
