### ISSUE TITLE
Can't synchronise external hard drive on OS X due to "hard links"

### ISSUE THREAD

**Issue by stevage** [owncloud/client#2590]
I'm attempting to upload ~1TB of data on an external hard drive connected to a Mavericks MBP to an OpenStack object store using OwnCloud. Currently, only directories (but no files within) are synchronising, with the message that "sync is not supported for hard links" (or similar, I don't have it in front of me).

What I'm wondering (different from other related issues like #530):

1. What classifies as a "hard link"? From my shallow understanding of *nix file systems, all files are hard links - the only question is how many links point to the same inode.

2. Is there any workaround which would allow synchronising from this external hard drive? My hard drive isn't big enough to allow locally copying.

**Comment by guruz** [comment]
FYI @ogoffart
