### ISSUE TITLE
owncloudcmd silently ignores missing sync-exclude.lst

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#2592]
rm /etc/ownCloud/sync-exclude.lst
mkdir t 
strace -o tt owncloudcmd t https://daily.owncloud.com/stable7/owncloud
...
... sync completes correctly, no warnings, no error messages.
...

grep sync-exclude tt
<tt>
stat("/etc/ownCloud/sync-exclude.lst", 0x7fff22ea03f0) = -1 ENOENT (No such file or directory)
stat("/usr/bin/sync-exclude.lst", 0x7fff22ea03f0) = -1 ENOENT (No such file or directory)
open("/etc/ownCloud/sync-exclude.lst", O_RDONLY) = -1 ENOENT (No such file or directory)
</tt>

Also: searching the sync-exclude.lst in /usr/bin is probably not intended. Searching in the current working directory could make sense, though.

**Comment by guruz** [comment]
This should be done by now (1.8rc1)

cmd.cpp:
```
    if (loadedSystemExcludeList != 0 && loadedUserExcludeList != 0) {
        // Always make sure at least one list had been loaded
        qFatal("Cannot load system exclude list or list supplied via --exclude");
        return EXIT_FAILURE;
    }
```
