### ISSUE TITLE
"state-information" icon from the monochrome theme is not used

### ISSUE THREAD

**Issue by utack** [owncloud/client#2593]
When monochrome icons are enabled, the "state-information" icon from the color theme is used.
Can be reprocued by removing all sync folders, the client then shows "no sync folders configured". 
Tested with Client 1.7.0 on Arch Linux and Windows 7.

**Comment by danimo** [comment]
Fixed for 1.8.0.

**Comment by danimo** [comment]
Fixed for 1.8.0.

**Comment by lmaestro** [comment]
It works for me in version 1.8.0-nightly20150121 (build 4614)  in Windows. If anyone is able to reproduce in the latest version, please reopen it.
