### ISSUE TITLE
[Windows] File handles not closed when removing folder/repo

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#2594]
### Expected behaviour
After removing a folder from syncing, I expect the folder to be deletable and renamable.

### Actual behaviour
When renaming or deleting the folder which I just removed from syncing Windows tells me that "The action cannot be completed because the folder or file is [...] is open in another program.

Process Hacker shows that 4 .csync_journal.* are opened by owncloud.exe.

### Steps to reproduce
1. Add folder to sync.
2. Remove folder from sync.
3. Browse with explorer to folder and delete.

### Client configuration
Client version: 1.7.0
Operating system: Win7 32bit

**Comment by guruz** [comment]
Closing this, please reopen if the problem persists with a 1.8 nightly build
http://download.owncloud.com/desktop/daily/
