### ISSUE TITLE
Please back port install fix to 14.04

### ISSUE THREAD

**Issue by ornearius** [owncloud/client#2599]
new install 1.7.0cr1 on Ubuntu 14.10 fails to locate system sync-exclude.lst #2442 

If you look at this previous issue you will see that people are still having trouble.
It would be good to fix the 14.04 install as it is the long term support version.

Cheers,

**Comment by guruz** [comment]
Can this be closed?

**Comment by jnweiger** [comment]
Yes, closed here.
pre/post scripts are in place at https://build.opensuse.org/package/show/isv:ownCloud:desktop/owncloud-client
But see also https://github.com/owncloud/client/issues/2821
