### ISSUE TITLE
[Windows] Double-click on filename in activity tab does not always open Explorer

### ISSUE THREAD

**Issue by msrex** [owncloud/client#2601]
Win7 64bit professional
1.7.0 client

When you click on a filename in the activity tab it should open the Windows Explorer with the correct path. It only does so sometimes. I have been able to confirm that if the full path does not contain any spaces is always works. Space escaping not working?

**Comment by lmaestro** [comment]
It works fine in version 1.8.0-nightly20150211(build 4709)
