### ISSUE TITLE
Need to designate cloud or a device as owning the master source of files

### ISSUE THREAD

**Issue by nexuswest** [owncloud/client#2604]
I observe two different modes of cloud sync use: (1) cloud is the master source, and all other devices sync with that; (2) a device is the master source, and cloud is the backup. The Choose What to Sync button seems designed only to support (1), as it causes any items unchecked (excluded) to be removed from the local machine. Add Folder button seems built around the same assumption, not supporting the ability to select what on the local machine directory will be synced to the cloud. Disk-to-Disk sync clients resolve this by allowing the user to select items to sync on both "sides" at a finer level of granularity than the top level directory. Probably don't need to be that fancy. Simply by adding selectivity on the local machine side of the Add Folder process, and not assuming delete of local files on Choose What to Sync, I think this issue could be solved.

**Comment by te-online** [comment]
The point of (2) might be, that you have folders in your *local* owncloud-folder that won't get uploaded to the *remote* owncloud. On the one hand, this is a nice feature e.g. for having a documents folder on your computer and only *backup* a few files from this folder to your owncloud. On the other hand, it adds complexity to the client and for the user to configure it correctly.
