### ISSUE TITLE
Please either make F12 configurable or provide a button to open the log file

### ISSUE THREAD

**Issue by quantumchaos451** [owncloud/client#2610]
OS: Kubuntu 14.10
Owncloud Client Version: 1.7.0

[Yakuake](https://extragear.kde.org/apps/yakuake/) uses the global F12 key to open by default as well. It would be nice to either have the F12 configurable, or to have a Show Debug Log button (probably the easier).

**Comment by ogoffart** [comment]
Show log window is an advanced feature that is there only for debugging purpose.  
You can run  `owncloud --logwindow`  to see it.

(You can already "configure" it by changing the source code yourself. :-) )
(Or you can temporarly exit yakuake)
