### ISSUE TITLE
feature request AddFolder: free-text edit field to enter the name of the remote folder

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2613]
This is a feature request for the sync client Add Folder functionality: currently it is only possible to add the REMOTE folder by browsing the server-side folder dir tree [1]. We would like to send users by email a path that they can copy/paste so a free-text edit field would be helpful. 

I think this small enhancement for remote folder should be very easy to implement since such a field already exists defining the local folder without browsing [2]

[1]

![image](https://cloud.githubusercontent.com/assets/621965/5415029/5029866e-8224-11e4-89be-2fee98caf571.png)

[2]

![image](https://cloud.githubusercontent.com/assets/621965/5415020/3f2ebfb4-8224-11e4-8690-dac3d4346b9b.png)

**Comment by dragotin** [comment]
I am sorry, this can not be done for this milestone. It is a more complex task to map the entry field to the treeview than I expected. Pushing this on.

**Comment by moscicki** [comment]
Could you please propose some simple workaround, instead? We need to be able to add a remote sync folder without having to navigate to it. The problem in our case is that we want a user to be able to add a sync folder but he may not have access to it by traversing the directory tree. 

What would happen if I added a file into config/folders directory while the client is running? Would it pick it up? 

A correct solution to this problem requires probably more thought but we would like to have some simple workaround for the time being.

**Comment by michaelstingl** [comment]
@MorrisJobke Could you check the status for @moscicki 's feature request? Ideas for a workaround? See also: https://github.com/owncloud/client/issues/2783#issuecomment-73085562

00002549

**Comment by MorrisJobke** [comment]
@michaelstingl I also can't do more, than send you @dragotin comment: https://github.com/owncloud/client/issues/2783#issuecomment-73085562

**Comment by cdamken** [comment]
@MTRichards for your list of Feature request.

@dragotin  It's still for 1.8.1 milestone?

**Comment by MTRichards** [comment]
@cdamken please ensure that this is also in SFDC.
Thanks.

**Comment by cdamken** [comment]
@MTRichards SFCD: 00002549

**Comment by dragotin** [comment]
I created a test build with @ckamms patch: http://download.owncloud.com/desktop/projects/cernbox/CERNBox-1.8.0.2128-nightly20150313.pkg
@moscicki if you approve that it  works well for you, we can think of adding the patch to the 1.8.0 release planned for next week.

**Comment by ckamm** [comment]
Tested by @moscicki

**Comment by moscicki** [comment]
@ckamm, @dragotin, @MTRichards, @cdamken: thank you!

**Comment by MTRichards** [comment]
Great! Happy when we can make it work.
