### ISSUE TITLE
allow redirect on direct download link

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/client#2614]
refs https://github.com/owncloud/core/issues/12286#issuecomment-65437607

@guruz @dragotin  @danimo @ogoffart

**Comment by lmaestro** [comment]
It couldn't be tested from the client so I close it.

**Comment by DeepDiver1975** [comment]
I'm reopening as I think this is not yet done:
- [ ] change to different webdav propery name
- [ ] failover in case direct download fails

@guruz @ogoffart

**Comment by ogoffart** [comment]
Failover should already work.
What are the new webdav names?

**Comment by DeepDiver1975** [comment]
> What are the new webdav names?

the one you propoesed :speak_no_evil: ... let me check ...

**Comment by DeepDiver1975** [comment]
@ogoffart https://github.com/owncloud/core/pull/12854#issuecomment-67947914
