### ISSUE TITLE
Add Folder wizard: combine local and remote folder pair setup screens into one

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2619]
Combine both screens (local and remote selection) in one. I think it is more logical because it gives more feeling of defining a folder PAIR rather than some unrelated folders.

**Comment by jancborchardt** [comment]
Yeah, good call. @ogoffart @guruz let’s sit together tomorrow for some mockups.

**Comment by jancborchardt** [comment]
Discussed with @ogoffart and did some mockups. We’ll the dialog in one step instead of two, having the local folder on the left and the remote one on the right. Ideally with a list view for each directly in the dialog so it’s obvious and quick to choose.

**Comment by moscicki** [comment]
Another comment about current UI:  Add Folder in desktop sync client gives warning unnecessarily

If someone has sent me a shared folder to sync, I go to my desktop sync client to 'Add Folder'.
This then gives me a Warning "The local path xx\owncloud is already an upload folder. Please pick another one!"
This warning can be confusing for the user.
Ideally 'Add Folder' should come up empty. I would then proceed to fill in the fields.

**Comment by JetUni** [comment]
I agree that it was a bit confusing at first to have an 'alias' for the sync connections, but it's helpful after you understand it. Also, I don't like that I can choose the folders that I do or do not want downloaded from the server, but that I cannot choose what folders I want uploaded into a new, empty folder on the server.

For example, I have a drive A: that has a folder Music that I want to sync to ownCloud. Currently there is no music on my server, and I want to sync certain folders from A:\Music to the server, but not ALL of the folders in A:\Music. This isn't possible with the client, even though it WOULD be possible if there were already music uploaded to my server and I was downloading the music.

**Comment by jancborchardt** [comment]
> I agree that it was a bit confusing at first to have an 'alias' for the sync connections, but it's helpful after you understand it.

Sorry but that sounds like a recipe for disaster for first-time users. And it’s not good. If we’re having the alias-discussion again I’m out.

**Comment by ogoffart** [comment]
2.2 has no more alias

**Comment by jancborchardt** [comment]
Great to hear! :tada:  :)

**Comment by guruz** [comment]
See also https://github.com/owncloud/client/issues/5030

**Comment by michaelstingl** [comment]
In 2.3.2, it's a 3-step wizard:

<img width="2320" alt="napkin 09 06 17 6 38 47 pm" src="https://user-images.githubusercontent.com/214010/26985287-1ca7b378-4d43-11e7-832d-020a2d4898f3.png">

I think combining 1st and 2nd step makes the UI more cluttered:

<img width="557" alt="napkin 2 09 06 17 6 49 35 pm" src="https://user-images.githubusercontent.com/214010/26985611-8e8ed254-4d44-11e7-8505-a9bfdf417940.png">

**Comment by michaelstingl** [comment]
@felixboehm proposed to start with the remote folder, so the wizard can use the remote folder name as a default for the local folder name.

**Comment by jancborchardt** [comment]
Of course just combining the steps as they are in their current design makes the interface cluttered. :) That’s why it needs to be simplified.

On the left a local folder icon, with only the folder name / path relative from the current user to make it less technical. Clicking the path opens a popover to change the path via filepicker.

On the right the cloud favicon, with the remote folder path. Defaults to the local folder name and placement into the root. Clicking the name or favicon opens this »Select where you want the folder to be on the server« dialog.

**Comment by TheOneRing** [comment]
Not planned
