### ISSUE TITLE
Problems in Windows clients with long pathnames

### ISSUE THREAD

**Issue by benjaminfrombe** [owncloud/client#2635]
Also see forum post: http://forum.owncloud.org/viewtopic.php?t=25242&p=74973

I have a problem with some files failing syncing in the Windows clients:
The error I get is: The system cannot find the path specified.

I see that for the failed files a file exists in the folder which looks like a temporary file in format:

.%filename%.pdf.~593e

When I try to rename the file to .pdf I'm able to open the file without problems: so the files <b>ARE</b> getting synced allright

All failed path+filenames are longer then 294 characters.

When I try to rename the file to something shorter it also gets synced allright.
It is NOT an option to ask all users to use shorter paths / filenames so for my users this is a <b>blocking issue</b>

I do <b>NOT</b> get these errors on OSX clients only on windows clients.

I noticed that Dropbox and box.net had issues with this too in the past but they resolved not to long ago.

In the forum you will see that more users are coping with this exact same problem.

I'm trying this on the most recent version of the client (1.7.1) and server (7.0.4~rc1-1)
seem like a bug right ?

**Comment by gamicklisafisher** [comment]
You should check out ‘Long Path Tool’ it will help you fix the issues.
I had faced similar issue and this tool helped me to resolve this issue.
