### ISSUE TITLE
[Windows 8.1] [SSL] client crashes on  startup if ssl certificate is not trusted

### ISSUE THREAD

**Issue by zacharyTris** [owncloud/client#2636]
This happens on both my laptops (different hardware) that are running Win 8.1. Everytime I boot up the machine the client sw asks about the certificate and after confirming it is gone.
On Bootup of windows the client crashes if the certificate is not trusted.
Everything worked until I used my self-signed certificate. Which I have to use because one of my apps needs a FQDN of the certificate to be correct.
Since that time the message box pops up and after that the client crashes.

Reproduce:
Run on windows 8.1. Autostart owncloud sync on windows start.
After logon there is a message box that the certificate is self signed and not trusted.
check the box "continue anyway" and confirm with OK button.
The owncloud client is gone. I have to restart it manually. After that it works.
Problem: You don't notice that it is gone unless you check. Since it is a taskbar icon the icon will still be visible until you hover the mouse on it (windows standard behavior).

Expected:
Best: Only ask once to accept a certificate and then remember the choice. ANN: This certificate is installed on both computers.
Minimum expected behavior: don't crash or at least show a message box with errors to let user know it is not running as expected.

Actual:
See reproduce. The app crashes without notice (it is just gone).

EventViewer entries for the crash:
Exception code: 0xc0000005
erroroffset: 0x00000000

Server configuration
QNAP 419P+ NAS in my local network. Acting as a server. Everything installed there.
WebServer: Apache
DB: 5.1.36
PHP: 5.3.29
ownCloud: 7.0.4 updated from 7.0.2
Activated apps: Standard install. Using calendars and contacts and file sync.

contents of config.php:
'''
<?php
$CONFIG = array (
  'instanceid' => 'oc595d3bcd7f',
  'trusted_domains' => 
  array (
    0 => 'NasName',
    1 => 'NasName.routerName.routerSub',
  ),
  'datadirectory' => '/share/MD0_DATA/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '7.0.4.2',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'myAdmin',
  'dbpassword' => 'DBPassword',
  'installed' => true,
  'mail_from_address' => 'u.hafner',
  'mail_smtpmode' => 'smtp',
  'mail_domain' => 'inside-logic.net',
  'mail_smtpauthtype' => 'LOGIN',
  'mail_smtpauth' => true,
  'mail_smtphost' => 'myMailServer',
  'mail_smtpport' => '25',
  'mail_smtpsecure' => 'tls',
  'mail_smtpname' => 'myemail@myserver',
  'mail_smtppassword' => 'myPassword',
  'loglevel' => '2',
  'theme' => '',
  'maintenance' => false
);
'''
Encryption: No file encryption or owncloud encryption. https for transfers.

Client:
crashing app version: client 1.7.1 build 4382
browser: firefox
Operating System: Windows 8.1 (updated as of 22.Dec.2014)

Logfile is very long. The entries of today are:
{"app":"remote","message":"An exception occurred while executing 'INSERT INTO `oc_clndr_objects` (`calendarid`,`objecttype`,`startdate`,`enddate`,`repeating`,`summary`,`calendardata`,`uri`,`lastmodified`) VALUES(?,?,?,?,?,?,?,?,?)':\n\nSQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes","level":4,"time":"2014-12-22T08:16:51+00:00"}
{"app":"PHP","message":"Session has been closed - no further changes to the session as allowed at \/share\/MD0_DATA\/Web\/owncloud\/lib\/private\/session\/memory.php#80","level":3,"time":"2014-12-22T08:16:51+00:00"}
{"app":"PHP","message":"DateTimeZone::__construct() [<a href='datetimezone.--construct'>datetimezone.--construct<\/a>]: Unknown or bad timezone (W. Europe Standard Time) at \/share\/MD0_DATA\/Web\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Sabre\/VObject\/TimeZoneUtil.php#412","level":3,"time":"2014-12-22T08:16:51+00:00"}
{"app":"remote","message":"An exception occurred while executing 'INSERT INTO `oc_clndr_objects` (`calendarid`,`objecttype`,`startdate`,`enddate`,`repeating`,`summary`,`calendardata`,`uri`,`lastmodified`) VALUES(?,?,?,?,?,?,?,?,?)':\n\nSQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes","level":4,"time":"2014-12-22T08:17:04+00:00"}
{"app":"PHP","message":"Session has been closed - no further changes to the session as allowed at \/share\/MD0_DATA\/Web\/owncloud\/lib\/private\/session\/memory.php#80","level":3,"time":"2014-12-22T08:17:04+00:00"}
{"app":"PHP","message":"DateTimeZone::__construct() [<a href='datetimezone.--construct'>datetimezone.--construct<\/a>]: Unknown or bad timezone (W. Europe Standard Time) at \/share\/MD0_DATA\/Web\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Sabre\/VObject\/TimeZoneUtil.php#412","level":3,"time":"2014-12-22T08:17:04+00:00"}
{"app":"remote","message":"An exception occurred while executing 'INSERT INTO `oc_clndr_objects` (`calendarid`,`objecttype`,`startdate`,`enddate`,`repeating`,`summary`,`calendardata`,`uri`,`lastmodified`) VALUES(?,?,?,?,?,?,?,?,?)':\n\nSQLSTATE[08S01]: Communication link failure: 1153 Got a packet bigger than 'max_allowed_packet' bytes","level":4,"time":"2014-12-22T08:17:28+00:00"}
{"app":"PHP","message":"Session has been closed - no further changes to the session as allowed at \/share\/MD0_DATA\/Web\/owncloud\/lib\/private\/session\/memory.php#80","level":3,"time":"2014-12-22T08:17:28+00:00"}
{"app":"PHP","message":"DateTimeZone::__construct() [<a href='datetimezone.--construct'>datetimezone.--construct<\/a>]: Unknown or bad timezone (W. Europe Standard Time) at \/share\/MD0_DATA\/Web\/owncloud\/3rdparty\/sabre\/vobject\/lib\/Sabre\/VObject\/TimeZoneUtil.php#412","level":3,"time":"2014-12-22T08:17:28+00:00"}

**Comment by guruz** [comment]
Do you also have some entries from the _client_ log file before the crash?
You can start the client from ```cmd.exe``` with certain parameters to get that log. See the template here: https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

(Note to self: We suspect that using #2699 and #2507 could fix this)

**Comment by danimo** [comment]
I cannot reproduce this on master.
