### ISSUE TITLE
upload to shared folders impossible

### ISSUE THREAD

**Issue by sr2831** [owncloud/client#2637]
Uploads to shared folders fail: "Sabre\DAV\Exception\InsufficientStorage".

Testes with owncloud 7.04
client 1.7.1 on ubuntu 14.04

shared folder is in other owncloud installation (server-server sharing) or on GoogleDrive, makes no difference, 

storage quota is not exceeded

**Comment by guruz** [comment]
@sr2831 Sorry I have to ask you to report on https://github.com/owncloud/core where server issues are tracked.

CC @icewind1991 S2S(?)
