### ISSUE TITLE
[OS X] [Chinese] characters don't show up in settings dialog (OS X 10.10 only)

### ISSUE THREAD

**Issue by Tony-HSU** [owncloud/client#2640]
Mac OS X 10.10
Client 1.7.1(build 1655)
![2014-12-23 8 25 04](https://cloud.githubusercontent.com/assets/3013707/5537855/f6ed00bc-8ae3-11e4-973a-351c672d3e7d.png)

**Comment by danimo** [comment]
Let's check text codecs

**Comment by guruz** [comment]
One of the Qt developers (Gabriel) mentioned that 5.4 fixes this?

**Comment by guruz** [comment]
I'm using the same release and all is fine for me on 10.9.5

![chinese](https://cloud.githubusercontent.com/assets/959327/5815351/4c50f5d8-a095-11e4-9080-4676f7f7161a.jpg)

**Comment by guruz** [comment]
Another peculiar thing are those log messages: https://gist.github.com/guruz/4d33e54706e7ac07c861

**Comment by guruz** [comment]
I can confirm that using Qt 5.4 would fix this
#2699

**Comment by guruz** [comment]
@Tony-HSU @mktsai @WayneSan Do you want to try the latest 1.8 nightly release to see if it fixes this for you? http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.1940-nightly20150126.pkg

(Please note this should work fine but has not gone through full QA, so please have backups..)

**Comment by mktsai** [comment]
@guruz It seems not fixes.
![image](https://cloud.githubusercontent.com/assets/3986549/5903159/10961b88-a5bb-11e4-9468-2851c39e0bde.png)

**Comment by guruz** [comment]
Sorry, I missed something.
It seems this depends on https://github.com/owncloud/client/issues/2470
The translation file names have changed.

**Comment by danimo** [comment]
I checked and it should work, we still load translations called "mirall".

**Comment by lmaestro** [comment]
@guruz @danimo Is it ready to test? or something should be changed?

**Comment by lmaestro** [comment]
It is not fixed 
![2015-02-03 10 28 38](https://cloud.githubusercontent.com/assets/4689430/6017626/4174f0f0-ab90-11e4-9129-46b32f844f07.png)
![2015-02-03 10 28 57](https://cloud.githubusercontent.com/assets/4689430/6017629/4504df14-ab90-11e4-983a-e89280f00880.png)
![2015-02-03 10 28 21](https://cloud.githubusercontent.com/assets/4689430/6017630/47d7b784-ab90-11e4-8fa8-114270d5aaa5.png)
![2015-02-03 10 28 06](https://cloud.githubusercontent.com/assets/4689430/6017637/4be490cc-ab90-11e4-9d8e-65ea2bc1560b.png)

**Comment by danimo** [comment]
Yes, for some reasons, the translations are not being loaded. Looking at the code, it is not obvious as to why.

**Comment by danimo** [comment]
Fixed now

**Comment by mktsai** [comment]
It's work. 
Thanks.
![image](https://cloud.githubusercontent.com/assets/3986549/6075095/b0fb46d6-ae06-11e4-9f7b-29c729adaf3d.png)
