### ISSUE TITLE
Can't detect existing file

### ISSUE THREAD

**Issue by Tony-HSU** [owncloud/client#2641]
origin paste
https://github.com/owncloud/core/issues/12044#event-203460678

OS: Mac OS X 10.10
Server: 7.0.2
Client: 1.7.0
![2014-11-08 11 03 05](https://cloud.githubusercontent.com/assets/3013707/4963029/4f81548a-66f4-11e4-8d50-c72c8d02a2d5.png)
this file is really exist in the right path, but my owncloud client can't find it...
-rw-r--r--   1 tonypottera  staff    22K  1 21  2014 交換生3台大財金所碩三梁允綺.docx

### Steps to reproduce
1.create a microsoft office word file
2.rename it to "交換生3台大財金所碩三梁允綺.docx"

### Expected behaviour
it should be uploaded to owncloud server

### Actual behaviour
client said "No such file or directory"
(FileZilla generate same error too)

### Server configuration
**Operating system:**
Fedora 20

**Web server:**
httpd
Server version: Apache/2.4.10 (Fedora)
Server built:   Jul 23 2014 10:29:44

**Database:**
mysql  Ver 15.1 Distrib 5.5.39-MariaDB, for Linux (x86_64) using readline 5.1
**PHP version:**

**ownCloud version:** (see ownCloud admin page)
7.0.2

**Updated from an older ownCloud or fresh install:**
fresh install

**Are you using external storage, if yes which one:** local/smb/sftp/...
no

**Are you using encryption:** no

### Client configuration
**Browser:**
Desktop client 1.7.0

**Operating system:**
Mac OS X 10.10

**Comment by dragotin** [comment]
Closing this here, because we should really track it in the server repo under core #12044

**Comment by guruz** [comment]
> (FileZilla generate same error too)

FYI We think this is a server issue
