### ISSUE TITLE
[Linux] [Overlays] When child directory is full synchronized, parent directory doesn't have an icon

### ISSUE THREAD

**Issue by LEDfan** [owncloud/client#2643]
Nice work with the 1.7.0 release!

I'm running OpenSUSE 13.2 with ownCloud client 1.7.1 from the OBS. Note that I had the same problem with 1.7.0. 

# Excepted behavior

When having a directory, which is fully synchronized the parent directory should have an icon indicating that. Like this:
The child directory:
![untitled](https://cloud.githubusercontent.com/assets/2996275/5546522/ce712d3c-8b44-11e4-90f0-591ea41cea64.png)
The parent directory:
![untitled](https://cloud.githubusercontent.com/assets/2996275/5546529/e8ae9fb8-8b44-11e4-860a-600b926d378c.png)
The directory instantUpload has a mark that it is synchronized. 

# Actually behavior

This works for the InstantUpload directory, but not for my documents directory. However all files and directories inside that directory has the "synchronized" mark. But not the parent directory.

Thanks :)

**Comment by ckamm** [comment]
@LEDfan What you're saying is that you have two sync folders: ~/Downloads and ~/InstantUpload and both are fully synced. But in your file browser only InstantUpload gets the "fully synced" icon?

Does the problem persist across syncs, i.e. when you modify a file in Documents and the sync finishes, does the icon appear?

This is either a bug in the socket API or in the shell integration code. Could you check the notifications the client sends by running

    netcat -U /run/user/${UID}/ownCloud/socket | grep 'Documents/$'

before triggering a sync of Documents? You should be seeing REGISTER_PATH, STATUS and UPDATE_VIEW messages for ~/Documents/.

**Comment by dragotin** [comment]
@lmaestro could you please try to verify this problem?

**Comment by lmaestro** [comment]
I am not able to reproduce it using version 1.8beta1 in OpenSUSE 13.2.
@LEDfan Please use the latest version (https://owncloud.org/install/#testing) and if you are able to reproduce it, reopen it, thx.
