### ISSUE TITLE
Documentation: Notes box in troubleshooting.rst broken

### ISSUE THREAD

**Issue by ghost** [owncloud/client#2645]
Hi,

in the current https://github.com/owncloud/client/blob/master/doc/troubleshooting.rst the notes box for:

> Synchronizing the same directory with ownCloud and other

 is broken as you can also see here:

http://doc.owncloud.org/desktop/1.7/troubleshooting.html#isolating-other-issues

**Comment by RealRancor** [comment]
@danimo @carlaschroder Sorry to ask but how are new docs of the sync-client published?

https://github.com/owncloud/client/blob/master/doc/troubleshooting.rst

is updated but:

https://doc.owncloud.org/desktop/1.8/troubleshooting.html#isolating-other-issues

still shows this broken box. Strange that the 1.7 docs are correct:

https://doc.owncloud.org/desktop/1.8/troubleshooting.html#isolating-other-issues

**Comment by carlaschroder** [comment]
Hi @RealRancor, it's a little more complicated than the admin and user manuals because the client manual is integrated into the client build, so you work in a branch in owncloud/client. I've forgotten which branch to work in-- @danimo, help?

**Comment by RealRancor** [comment]
Thanks for the info. Had a look at the branches but wasn't really able to identify the needed branch.

**Comment by carlaschroder** [comment]
@RealRancor, they all look the same to me. Am I missing something? I'm looking at https://doc.owncloud.org/desktop/2.0/troubleshooting.html#isolating-other-issues in all three versions.

**Comment by RealRancor** [comment]
Sorry, its fine now. Stupid browser caching issue.

**Comment by carlaschroder** [comment]
:beer:
