### ISSUE TITLE
Failed sync after moving files around.

### ISSUE THREAD

**Issue by m1dnight** [owncloud/client#2647]
### Expected behaviour
A proper sync of moved/deleted files
### Actual behaviour
Error message and frozen sync client with message "Could not read status line: connection timed out. General: Could not read status line. Connection Timed out."

### Steps to reproduce
Not sure. I simply moved around some pdf files. Created a few new subdirectories and deleted a few subdirectories in the share.
### Server configuration
Operating system: Ubuntu 14.04.1 LTS
Web server: Apache/2.4.7 (Ubuntu)
Database: MySQL 5.5.40-0ubuntu0.14.04.1 
PHP version: PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10) 
ownCloud version: ownCloud 7.0.4 (stable)
Storage backend: Just /var/www/owncloud/data folder on main drive.

### Client configuration
Client version: 1.7.1

Operating system: Xubuntu 14.04.1 LTS

OS language: English

Installation path of client: Not sure.

### Logs
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
http://pastebin.com/raw.php?i=L5y7JXkM

2. Web server error log:
Cleared logs first (/var/log/apache2/error.log|access.log), does not create new log file (no entries then I presume?)

3. ownCloud log (data/owncloud.log):
http://pastebin.com/raw.php?i=rwm55X14

**Comment by PVince81** [comment]
When deleting files, the files are copied to the trashbin. If there are lots of files, it will be slow and can cause a timeout to occur. CC @schiesbn

**Comment by m1dnight** [comment]
There were not a lot of files. All pdf files and maximum 100 mb. However, I let it be for a while and it fixed itself after an hour or 2.

**Comment by dragotin** [comment]
I am closing this one. @m1dnight please create a new issue if you see that again.
