### ISSUE TITLE
"0xf47420 ERROR: Instruction 8 vs 8 for file" and crash when encountering file with invalid encodings

### ISSUE THREAD

**Issue by johanehnberg** [owncloud/client#2649]
Running owncloud client 1.7.1 from the opensuse build system on Ubuntu 14.04:
owncloud --logflush --logfile -

Example:
12-28 14:07:42:100 0xf47420 ERROR: Instruction 8 vs 8 for "Websidor/Skolrelaterat/skolbilder/r�varor" 
12-28 14:07:42:100 0xf47420 ASSERT: "!"Instructions are both unequal NONE"" in file /usr/src/packages/BUILD/src/mirall/syncengine.cpp, line 331
Aborted (core dumped)

This happens at least when reading files that were incorrectly moved from a cp1252 latin 1 filesystem to UTF-8, without actually translating the names. This happens at least with 'å' and 'ä' characters corrupted like this.

The error of course is in the filesystem and fairly rare, but as it may not be possible to control the clients' files, it may make sense to instead skip the file with a warning.

**Comment by guruz** [comment]
@johanehnberg The newest nightly should now report an error instead of assert?

**Comment by lmaestro** [comment]
@johanehnberg Can you tested in the lates build? https://software.opensuse.org/download/package?project=isv:ownCloud:community:nightly&package=owncloud 
I can't reproduce it in OS X.

**Comment by johanehnberg** [comment]
This is what VMs are for :). The solution is great, it refuses to sync the invalid encoding (removes the renamed folder after convmv is run) and gives a very visible warning on the status icon and account page. The client no longer crashes. I consider this bug fixed.
