### ISSUE TITLE
Bad UX: "Ignore Files" dialog

### ISSUE THREAD

**Issue by cjm51213** [owncloud/client#2650]
Hi Folks,

I've learned from a reliable source that the ownlcloud desktop client will actually delete files that match an "Ignore Files" pattern and the check box is checked. Deletion seems very un-ignore-ish. So either I misunderstand the "Ignore Files" feature, or I think it is dangerous and should be much more carefully deployed, or possibly re-worked. For example, the list of patterns appear to be "Enabled/Disabled" with the check-box, but I'm told that the check-boxes do NOT mean "Enable/Disable", which could be a disastrous misunderstanding.

On the face of it, I think "ignore" should be sufficient, and I don't see the need to delete anything from the client.

Let me give an example. I have a set of machines both Windows and Linux. Windows already has a multiple desktop sync feature, if they are members of a "Windows Domain", but it is much more problematic to extend that beyond a firewall or to a non-Windows desktop. So, owncloud to the rescue. If I sync my Windows profile (Documents, &c.) there are files that don't need to be sync'd -- for example, database files -- however that shouldn't be deleted either!

So, apparently I don't fully understand how "Ignore Files" works. This may either be a deficiency in the documentation or it may be a dangerous feature which is able to cause a great deal of accidental damage. In either case, I think a discussion is warranted.

Chris.

**Comment by guruz** [comment]
@jancborchardt Please advise a good UI. Thx

> So the feature has to be kept.

Ack.

**Comment by jancborchardt** [comment]
As discussed with @guruz the list should be sorted and the sections should have different headers:
* Default ignore patterns
* Default ignore patterns, deletable files (for the checked patterns)
* Custom ignore patterns (with an »Add ignore pattern« entry on the bottom)

(Ideally editing and adding ignore patterns will happen inline instead of in a popup dialog. But that’s a second step.)

**Comment by dragotin** [comment]
There are changes on the dialog, please try a nightly build.

**Comment by jancborchardt** [comment]
@dragotin @jnweiger would be good if there could be regular builds of the testpilotcloud-client so folks can test these things. : ) Also cause we just talked about the testpilots stuff today.

**Comment by Dianafg76** [comment]
@dragotin, @jancborchardt That's the change ? , As it should appear and where? . I need more information to prove

**Comment by guruz** [comment]
... not sure if @carlaschroder was notified here.
The UI has changed in 2.0 so the docs should update 
https://doc.owncloud.org/desktop/1.8/visualtour.html#ignoredfileseditor-label

**Comment by carlaschroder** [comment]
Is there a release date for 2.0? @guruz

**Comment by RealRancor** [comment]
@carlaschroder http://owncloud.10557.n7.nabble.com/Preliminary-Schedule-for-ownCloud-Client-2-0-0-td15552.html

**Comment by carlaschroder** [comment]
aha. And https://github.com/owncloud/client/wiki/ReleaseDates
