### ISSUE TITLE
Change 'Mirall' to 'client'?

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/client#2655]
There are some references to Mirall in the client manual, for example:
http://doc.owncloud.org/desktop/1.7/building.html

Should these be changed to 'client'?

**Comment by guruz** [comment]
I think danimo might have modified some things already.
Otherwise I'd say yes.. (except for some external things like brew where you'd need to check how their names are now)
@danimo Could we also have 1.8/master docs on doc.owncloud.org?

**Comment by carlaschroder** [comment]
It appears that both issues are fixed, so.. bye! :)
