### ISSUE TITLE
Local External Storage: display issue with files and folders with special characters (umlaut, accents) 

### ISSUE THREAD

**Issue by woutz** [owncloud/client#2657]
### Expected behaviour
External storage view of local files on Windows LAN in web client / browser should show files and folders, which contain special characters, incl. é,è,à,ö,ä,ü

### Actual behaviour
External storage view of local files on Windows LAN in web client / browser 
-	shows folders, which contain special characters (incl. é,è,à,ö,ä,ü) as ‘null’
-	doesn’t show files, which contain special characters (incl. é,è,à,ö,ä,ü)

### Steps to reproduce
1. define local external storage of Windows network / LAN folder structure (via enabling external storage app)
2. use internet browser as client and browse to ‘external storage’
3. folders with special characters are shown as ‘null’, files with special characters do not show at all

### Server configuration
Operating system: Windows XP SP3

Web server: Apache/2.4.9 (Win32, XAMPP 1.8.2) 

Database: MySQL (XAMPP 1.8.2, Database client version: libmysql - mysqlnd 5.0.10 - 20111026 - $Id: c85105d7c6f7d70d609bb4c000257868a40840ab $), 5.5.36 - MySQL Community Server (GPL)

PHP version: 5.4.27

ownCloud version: 7.0.4

Storage backend: Windows XP SP3, external USB hard disk FREECOM USB MEMORY DEVICE for external storage shared over Windows LAN

### Client configuration
Client version: web browser Mozilla Firefox, 34.0.5

Operating system: Windows 8

OS language: French

Installation path of client: Windows

**Comment by danimo** [comment]
This is a server bug, please report to https://github.com/owncloud/core/issues
