### ISSUE TITLE
 Connection timed out (compare closed issue #2039 )

### ISSUE THREAD

**Issue by DACN** [owncloud/client#2661]
I am having similar problems. Running Windows 8.1 on my laptop, with the owncloud client 1.7.1 (build 4382) with owncloud 7.0.4. Trying to sync some 60,000 files and 60Gb of data to a server in my home network. Works fine apart from timeouts on large files. Installed with nginx and mysql.

As of now, some 50,000/60,000 files synced (mostly smaller files) and roughly 10Gb of the 60Gb of data synced.

One failure was a file 'word2011.exe' of about 600Mb. The interesting thing about the failure, was that it completely uploaded successfully into the correct directory - but then the final bits of the process of failed to complete, and it reported as being timed out, and currently shows in the windows directory with a small red cross against it.

Interestingly, have also had a timeout message this evening on deleting a large file. In this case the file was of 2500Mb and it had uploaded without timeout messages. I later deleted it, and this evening during the synchronisation owncloud gave the message:

'Could not read status line: connection timed out'

However, on checking via the web interface, this particular file has been successfully moved to the set of deleted files.

David Nicol

**Comment by ckamm** [comment]
@DACN The first thing to check would be whether these are actual timeouts on the server. Do you have enough access to check the log files? Do you see timeouts involving apache/nginx calling owncloud's php code?

**Comment by guruz** [comment]
@DACN Also.. which DB do you use for your server installation? You should not use the sqlite3 one..

http://doc.owncloud.org/server/7.0/admin_manual/maintenance/convert_db.html

**Comment by DACN** [comment]
Have dug out all the logs which refer to this particular file word2011. This is what I can see..

LOTS OF LINES LIKE THE NEXT RE CHUNKING ...
access.log.17.gz:mm.mm.mm.mm - david.nicol [02/Jan/2015:12:54:10 +0000] "PUT /owncloud/remote.php/webdav/downloads/word2011.exe-chunking-2945636270-30-29 HTTP/1.1" 499 0 "-" "Mozilla/5.0 (Windows) mirall/1.7.1"
access.log.17.gz:mm.mm.mm.mm - - [02/Jan/2015:15:08:26 +0000] "GET /owncloud/index.php/apps/files/ajax/download.php?dir=%2Fdownloads&files=word2011.exe HTTP/1.1" 200 613999272 "https://zzzzzzzz.co.uk/owncloud/index.php/apps/files/?dir=%2Fdownloads" "Mozilla/5.0 (Windows NT 6.3; WOW64; rv:34.0) Gecko/20100101 Firefox/34.0"
error.log.16.gz:2015/01/02 07:04:01 [error] 2287#0: *44474 upstream prematurely closed connection while reading response header from upstream, client: mm.mm.mm.mm, server: zzzzzzzz.co.uk, request: "PUT /owncloud/remote.php/webdav/downloads/word2011.exe-chunking-2945636270-30-2 HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "zzzzzzzz.co.uk"

Also, am running mysql

**Comment by ckamm** [comment]
@DACN, that looks nginx's connection to the owncloud server was closed. Presumably that happened after the server fully accepted the file but before the response could be communicated back to the client - and thus the client thinks the upload failed.

I'm not sure what can be done here. Since the client didn't get an etag from the server it can't be sure the file on the server is the one that it just updated.

This seems to be a somewhat common error with slow servers. Maybe for large, failed uploads it'd make sense to query the server for the file afterwards and - if the mtime and size are correct - assume that the client's upload succeeded after all? 

@dragotin @ogoffart Thoughts?

**Comment by ogoffart** [comment]
I think the best thing that can be done is to make the server faster, or implementing assynchronous PUT:  https://github.com/owncloud/core/issues/12097

**Comment by ckamm** [comment]
@ogoffart Thanks for the link, I agree! I'm closing this issue since it's tracked elsewhere.
