### ISSUE TITLE
Client segmentation fault when modifying account

### ISSUE THREAD

**Issue by Robzz** [owncloud/client#2662]
### Expected behaviour
I tried to reconfigure my account for use outside of my LAN (using my domain name instead of my raspberri pi local IP address). The domain name wasn't in the trusted_domains list. This is important, because the crash stopped occurring after i added my domain to the trusted domain list via my web browser.
The server is HTTPS enabled and owncloud is set to force HTTPS connection.
Trying to connect over HTTPS showed a popup saying it could not open an encrypted connection and asked if it should try without encryption (this is misconfiguration on my end, added the domain to the trusted list, everything OK since). I hadn't figured out the problem so I tried it without encryption. This should obviously fail, but the expected behaviour would be to do so gracefully, printing an error message.

### Actual behaviour
Segmentation fault.

### Steps to reproduce
1. Connect to force-HTTPS owncloud server through untrusted domain.
2. It fails and a popup asks to try without encryption : say yes. URL is changed from https://... to http://...
3. Click next to retry. Wait a few seconds.
4. 'zsh: segmentation fault  owncloud'

Note : it DOES NOT crash if you try to connect via HTTP on your own, only if the client asks you to and you say yes.

This is perfectly reproducible on my setup. Just remove the trusted_domains line from the config.php and it'll crash, so I can help troubleshooting if you want.
I had a quick look through bugs mentioning segmentation faults, this does not seem to be a duplicate. Note that I use the client shipped in your apt repositories, I haven't tried building it from source.
Anyway, I doubt this is a critical bug since I couldn't trigger it when doing things that 'should work'.

### Client configuration
Client version: 1.7.0~beta1+really1.6.4+dfsg-1    (latest in the repo)

Operating system: Debian 8.0 (testing)

OS language: French/English

Installation path of client: /usr/bin/owncloud

### Logs
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
gist here : https://gist.github.com/Robzz/acc90fbb1e785031c38f
(i edited my domain name)

2. Web server error log:
Nothing in there. Last line was 5 minutes before my last crash. That's why I omitted the server configuration part, I doubt it's relevant.

3. ownCloud log (data/owncloud.log):
Is that one on the server? I didn't find it. I think it's because I haven't used the server yet, so there ain't much to log.

Bonus : the backtrace. Hope it's helpful.
```
#0  QNetworkReply::isFinished (this=0x0) at access/qnetworkreply.cpp:466
#1  0x00007ffff6b9c8d9 in QNetworkReply::isRunning (this=<optimized out>) at access/qnetworkreply.cpp:479
#2  0x00007ffff63ceb32 in Mirall::CheckServerJob::slotTimeout() () from /usr/lib/x86_64-linux-gnu/libowncloudsync.so.0
#3  0x00007ffff67ccf4c in QMetaObject::activate (sender=0xd4fa70, m=<optimized out>, local_signal_index=<optimized out>, argv=0x0)
    at kernel/qobject.cpp:3567
#4  0x00007ffff67d1513 in QObject::event (this=0xd4fa70, e=<optimized out>) at kernel/qobject.cpp:1253
#5  0x00007ffff72b629c in QApplicationPrivate::notify_helper (this=this@entry=0x7023e0, receiver=receiver@entry=0xd4fa70, 
    e=e@entry=0x7fffffffe220) at kernel/qapplication.cpp:4570
#6  0x00007ffff72bcda8 in QApplication::notify (this=0x7fffffffe560, receiver=0xd4fa70, e=0x7fffffffe220)
    at kernel/qapplication.cpp:4356
#7  0x00007ffff67b7f8d in QCoreApplication::notifyInternal (this=0x7fffffffe560, receiver=0xd4fa70, 
    event=event@entry=0x7fffffffe220) at kernel/qcoreapplication.cpp:955
#8  0x00007ffff67e9b6b in sendEvent (event=0x7fffffffe220, receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#9  QTimerInfoList::activateTimers (this=0x704860) at kernel/qeventdispatcher_unix.cpp:621
#10 0x00007ffff67e6bc9 in timerSourceDispatch (source=<optimized out>) at kernel/qeventdispatcher_glib.cpp:186
#11 idleTimerSourceDispatch (source=<optimized out>) at kernel/qeventdispatcher_glib.cpp:233
#12 0x00007ffff4edec5d in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff4edef48 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff4edeffc in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff67e74ed in QEventDispatcherGlib::processEvents (this=0x6ea790, flags=...) at kernel/qeventdispatcher_glib.cpp:425
#16 0x00007ffff735ab96 in QGuiEventDispatcherGlib::processEvents (this=<optimized out>, flags=...)
    at kernel/qguieventdispatcher_glib.cpp:204
#17 0x00007ffff67b6ae1 in QEventLoop::processEvents (this=this@entry=0x7fffffffe4a0, flags=...) at kernel/qeventloop.cpp:149
#18 0x00007ffff67b6e45 in QEventLoop::exec (this=this@entry=0x7fffffffe4a0, flags=...) at kernel/qeventloop.cpp:204
#19 0x00007ffff67bc8b9 in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1227
#20 0x00000000004334d2 in main ()
```

**Comment by ckamm** [comment]
@Robzz Thank you for the thorough report and particularly the backtrace!

The version string 1.7.0~beta1+really1.6.4+dfsg-1 is fun! The log indicates it is indeed 'really 1.6.4'. :)

It seems the problem with the null QNetworkReply was already fixed in versions >=1.7.0 by commit  7bad731ad2c0dca86576fe6f178f462dbef49a5b.
