### ISSUE TITLE
We can't see the folder to exclure

### ISSUE THREAD

**Issue by boogieplayer** [owncloud/client#2663]
I can't see the sub folder to exclure, or inclure, in the process "add folder". See the screen. Of course they are subfolders ;)

Windows 8 64bits home edition french
Client 1.7.1 french
![owncloud issue](https://cloud.githubusercontent.com/assets/10384993/5604197/ea31534c-93ac-11e4-9681-ec93c53eca4a.jpg)

![owncloud issue 2](https://cloud.githubusercontent.com/assets/10384993/5604205/58e21966-93ad-11e4-9f8b-a1c85af1d907.jpg)

**Comment by guruz** [comment]
I'm assuming you did not sync those folders to the server yet, so they are only client side? :)

CC @ogoffart @MTRichards ...

**Comment by boogieplayer** [comment]
Hi,

yes, those folders are only on the PC. I don't want to sync Debra's folder, only london's folder and all the files in the Images folder, and obisiouly the futures folders in Images folder. I hope to be understandable ;)

**Comment by boogieplayer** [comment]
Of course, I want to exclude the sub folder before to sync, because the debra's folder is too big.

**Comment by ogoffart** [comment]
![selectivesync](https://cloud.githubusercontent.com/assets/959326/6078836/c112bc24-adfd-11e4-956c-7531b922f09f.png)

This is how it looks now.  Is it any less confusing?
