### ISSUE TITLE
Cannot delete files

### ISSUE THREAD

**Issue by viruzx** [owncloud/client#2665]
Expected Behavior
When I delete a file from my local machine, it should delete it from the cloud. When I delete a file from the cloud, it should delete it on my local machine.

Actual Behavior
When I delete files from synced folders on my PC, owncloud client re-downloads them.
Additionally I get an "Error deleting file." when I try to delete any file via web interface.

Web Server
-Shared Hosting
-PHP Version: native (5.3)
-Database: MySQL (Not an old version but not the latest either)

OS
-Windows 10
-64 Bit
-English

Cause
After a bit of thinking, I think I know the cause of the issue. The client tells the web server to delete the files but it fails. Then it proceeds to sync with my local files hence downloading the deleted files.

**Comment by ogoffart** [comment]
Please provide more information.  You can follow the template: https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

What is the version of owncloud and the client?  What is the exact error? Do you have client log?

If you get also an error on the server, there might be a problem in the server, so the server log should also shpw what the problem really is.

**Comment by guruz** [comment]
If this persists with client 1.8rc2 and server 8.0.2 please re-open
