### ISSUE TITLE
Client issues

### ISSUE THREAD

**Issue by tekieinsocal** [owncloud/client#2668]
I got my owncloud server running at home and I can access it externally.  My owncloud server is a win 7 with WAMP running on it.  Everything is working smoothly until I installed the desktop client sync app.

I installed the app on my laptop (which connects via external address), HTPC with local access, I even installed it the same server.  On all three I noticed after boot up,my services on my bitdefender stop, slowness and lag creeps up.  From surfing the web on my browser internet addresses hang.  I ran malware bytes and bitdefender and found nothing. Switching between windows become more slow and getting worse.  I opened up task manager and saw my memory was 4/16gb used and CPU was no more than 10% at best.  Yet the performance was showing as if when the CPU and Memory are maxed out. 

I uninstalled the desktop app from my server and everything works fine how it was.  All of the issues I described went away and everything is running stable.  I thought what if it was something related to same computer desktop client installed on the  same server issues.  Nope, laptop and htpc showed the same symptoms.  I restarted and worked then symptoms surfaced.  I removed the sync app and now are all working and stable now.  

I also noticed the client would have issues with files and randomly disconnect and tried to reconnect and acting weird.  I really wanted this process to work out more smoothly, but seems I may have to go back to google drive and scrap this project.  Just letting you guys know of my findings.

**Comment by RealRancor** [comment]
Hi,

consider filling out the issue template provided here:

https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

as asked in the "guidelines for contributing" (linked in the box when creating a new issue) to provide more infos about your environment.

**Comment by tekieinsocal** [comment]
### Expected behaviour
App should run without causing overall issues to the system.

### Actual behaviour
Once the desktop sync app is installed onto Win 7.  There is tremendous hit on performance on the computers.  Extreme lag when switching between windows, minimizing anything.  When clicking on any menu you see the menu react with seconds of delay.  My Bitdefender AV service get stopped and my pc needs to reboot in order to fix it. I submitted an email to Bitdefender support as well and sent them a log to see if they can find anything.

### Steps to reproduce
1. Download and Installed Owncloud Desktop Sync App my 3 Windows Computers.  The server is running by itself fine with no issues.  Just added the client software onto my computers and bam all 3 performance hits and same behavior. 
2. Let the app sync to the server - Syncing is fine for the most part.  I did see a few times where the client disconnected without warning in the LAN.
3. Wait after a few minutes generally after 5 minutes, the slowness creeps up and then every minute after the pc becomes unusable and a hard reboot is required.  Reproduced it on 3 computers.
4. What fixed my issue was - Uninstalling the client app and pc is working normal without any issues.

### Server configuration
Operating system: Windows 7 Pro

Web server:  WAMP 2.5

Database: MySql 5.6.17

PHP version: 5.5.12

ownCloud version: 7.0.4

Storage backend:  A few 2TB WD RED Hard Drive(s)

### Client configuration
Client version: 1.7.1

Operating system: Windows 7 Pro

OS language: English

Installation path of client: C:\Program Files x86\Owncloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.5/troubleshooting.html#client-logfile )
Uninstalled Owncloud Client. Haven't re-installed it since my machine is working without it for now.  I don't have the client logs since I deleted the ownlcloud folder as well.  

2. Web server error log: 
[Sun Jan 04 16:10:35.308645 2015] [mpm_winnt:notice] [pid 7416:tid 372] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Sun Jan 04 16:10:37.308759 2015] [mpm_winnt:notice] [pid 4676:tid 248] AH00364: Child: All worker threads have exited.
[Sun Jan 04 16:10:37.362762 2015] [mpm_winnt:notice] [pid 7416:tid 372] AH00430: Parent: Child process 4676 exited successfully.
[Sun Jan 04 16:10:38.653836 2015] [mpm_winnt:notice] [pid 7376:tid 372] AH00455: Apache/2.4.9 (Win64) OpenSSL/1.0.1g PHP/5.5.12 configured -- resuming normal operations
[Sun Jan 04 16:10:38.653836 2015] [mpm_winnt:notice] [pid 7376:tid 372] AH00456: Apache Lounge VC11 Server built: Mar 16 2014 12:42:59
[Sun Jan 04 16:10:38.653836 2015] [core:notice] [pid 7376:tid 372] AH00094: Command line: 'c:\\wamp\\bin\\apache\\apache2.4.9\\bin\\httpd.exe -d C:/wamp/bin/apache/apache2.4.9'
[Sun Jan 04 16:10:38.655836 2015] [mpm_winnt:notice] [pid 7376:tid 372] AH00418: Parent: Created child process 6648
[Sun Jan 04 16:10:39.390878 2015] [mpm_winnt:notice] [pid 6648:tid 248] AH00354: Child: Starting 64 worker threads.
[Sun Jan 04 17:09:54.515220 2015] [mpm_winnt:notice] [pid 7376:tid 372] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Sun Jan 04 17:09:56.515334 2015] [mpm_winnt:notice] [pid 6648:tid 248] AH00364: Child: All worker threads have exited.
[Sun Jan 04 17:09:56.538336 2015] [mpm_winnt:notice] [pid 7376:tid 372] AH00430: Parent: Child process 6648 exited successfully.
[Sun Jan 04 17:09:57.273378 2015] [mpm_winnt:notice] [pid 2676:tid 372] AH00455: Apache/2.4.9 (Win64) OpenSSL/1.0.1g PHP/5.5.12 configured -- resuming normal operations
[Sun Jan 04 17:09:57.273378 2015] [mpm_winnt:notice] [pid 2676:tid 372] AH00456: Apache Lounge VC11 Server built: Mar 16 2014 12:42:59
[Sun Jan 04 17:09:57.273378 2015] [core:notice] [pid 2676:tid 372] AH00094: Command line: 'c:\\wamp\\bin\\apache\\apache2.4.9\\bin\\httpd.exe -d C:/wamp/bin/apache/apache2.4.9'
[Sun Jan 04 17:09:57.275378 2015] [mpm_winnt:notice] [pid 2676:tid 372] AH00418: Parent: Created child process 6372
[Sun Jan 04 17:09:57.995419 2015] [mpm_winnt:notice] [pid 6372:tid 248] AH00354: Child: Starting 64 worker threads.
[Mon Jan 05 13:21:54.148068 2015] [mpm_winnt:notice] [pid 2676:tid 372] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Mon Jan 05 13:21:56.150599 2015] [mpm_winnt:notice] [pid 6372:tid 248] AH00364: Child: All worker threads have exited.
[Mon Jan 05 13:21:56.175599 2015] [mpm_winnt:notice] [pid 2676:tid 372] AH00430: Parent: Child process 6372 exited successfully.
[Mon Jan 05 13:21:56.933111 2015] [mpm_winnt:notice] [pid 9136:tid 372] AH00455: Apache/2.4.9 (Win64) OpenSSL/1.0.1g PHP/5.5.12 configured -- resuming normal operations
[Mon Jan 05 13:21:56.933111 2015] [mpm_winnt:notice] [pid 9136:tid 372] AH00456: Apache Lounge VC11 Server built: Mar 16 2014 12:42:59
[Mon Jan 05 13:21:56.933111 2015] [core:notice] [pid 9136:tid 372] AH00094: Command line: 'c:\\wamp\\bin\\apache\\apache2.4.9\\bin\\httpd.exe -d C:/wamp/bin/apache/apache2.4.9'
[Mon Jan 05 13:21:56.935611 2015] [mpm_winnt:notice] [pid 9136:tid 372] AH00418: Parent: Created child process 6324
[Mon Jan 05 13:21:57.653122 2015] [mpm_winnt:notice] [pid 6324:tid 248] AH00354: Child: Starting 64 worker threads.
[Mon Jan 05 15:13:30.356285 2015] [mpm_winnt:notice] [pid 9136:tid 372] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Mon Jan 05 15:13:32.384289 2015] [mpm_winnt:notice] [pid 6324:tid 248] AH00364: Child: All worker threads have exited.
[Mon Jan 05 15:13:32.399889 2015] [mpm_winnt:notice] [pid 9136:tid 372] AH00430: Parent: Child process 6324 exited successfully.
[Mon Jan 05 15:17:49.959593 2015] [mpm_winnt:notice] [pid 4368:tid 372] AH00455: Apache/2.4.9 (Win64) OpenSSL/1.0.1g PHP/5.5.12 configured -- resuming normal operations
[Mon Jan 05 15:17:49.959593 2015] [mpm_winnt:notice] [pid 4368:tid 372] AH00456: Apache Lounge VC11 Server built: Mar 16 2014 12:42:59
[Mon Jan 05 15:17:49.959593 2015] [core:notice] [pid 4368:tid 372] AH00094: Command line: 'c:\\wamp\\bin\\apache\\apache2.4.9\\bin\\httpd.exe -d C:/wamp/bin/apache/apache2.4.9'
[Mon Jan 05 15:17:49.959593 2015] [mpm_winnt:notice] [pid 4368:tid 372] AH00418: Parent: Created child process 4260
[Mon Jan 05 15:17:50.724594 2015] [mpm_winnt:notice] [pid 4260:tid 248] AH00354: Child: Starting 64 worker threads.
[Mon Jan 05 17:10:46.742041 2015] [core:warn] [pid 2532:tid 372] AH00098: pid file C:/wamp/bin/apache/apache2.4.9/logs/httpd.pid overwritten -- Unclean shutdown of previous Apache run?
[Mon Jan 05 17:10:47.077042 2015] [mpm_winnt:notice] [pid 2532:tid 372] AH00455: Apache/2.4.9 (Win64) OpenSSL/1.0.1g PHP/5.5.12 configured -- resuming normal operations
[Mon Jan 05 17:10:47.077042 2015] [mpm_winnt:notice] [pid 2532:tid 372] AH00456: Apache Lounge VC11 Server built: Mar 16 2014 12:42:59
[Mon Jan 05 17:10:47.077042 2015] [core:notice] [pid 2532:tid 372] AH00094: Command line: 'c:\\wamp\\bin\\apache\\apache2.4.9\\bin\\httpd.exe -d C:/wamp/bin/apache/apache2.4.9'
[Mon Jan 05 17:10:47.082042 2015] [mpm_winnt:notice] [pid 2532:tid 372] AH00418: Parent: Created child process 6292
[Mon Jan 05 17:10:48.182043 2015] [mpm_winnt:notice] [pid 6292:tid 248] AH00354: Child: Starting 64 worker threads.
[Mon Jan 05 20:53:08.442014 2015] [mpm_winnt:notice] [pid 2532:tid 372] AH00422: Parent: Received shutdown signal -- Shutting down the server.
[Mon Jan 05 20:53:10.442045 2015] [mpm_winnt:notice] [pid 6292:tid 248] AH00364: Child: All worker threads have exited.
[Mon Jan 05 20:53:38.442475 2015] [mpm_winnt:notice] [pid 2532:tid 372] AH00431: Parent: Forcing termination of child process 6292

3. ownCloud log (data/owncloud.log): 
{"app":"PHP","message":"touch(): Unable to create file C:\/wamp\/www\/data\/owncloud.log because No such file or directory at C:\\wamp\\www\\lib\\private\\log\\owncloud.php#49","level":3,"time":"2015-01-01T00:12:44+00:00"}

**Comment by Sebastianv650** [comment]
I think I have exactly the same problem here, also nearly the same setup. Seems like Bitdefender doesn't like the client or in reverse.. I also already uninstalled owncloud client, but if it would help to find a solution I could try to geht logs in the next days? But I'm not shure if the logs would contain something useful, Bitdefender service is stopping, the client seems to keep running..

Server configuration

Operating system: Linux

Web server: LAMP

ownCloud version: 7.0.4

Storage backend: 16GB SDHC Card
Client configuration

Client version: 1.7.1

Operating system: Windows 7 64bit

OS language: German

Installation path of client: C:\Program Files x86\Owncloud

**Comment by vinz94f** [comment]
I have exactly the same problem mentioned above.
Since version 1.7.1, bitdefender antivirus stop running and pc is slow.
An incident was opened at bitdefender.
This problem occurs only on Windows 7 and my other PC under Windows 8.1 with the same configuration causes no problem.
Have you identified a problem in the code owncloud version 1.7.1 ?
I hope a quick resolution because it lasts for 1 month and a half.

**Comment by Sebastianv650** [comment]
I'm using 1.7.0 in the meantime, no problems with this version. But you have to disable autoupdate in registry, see my last post: http://forum.owncloud.org/viewtopic.php?f=14&t=25694

**Comment by ogoffart** [comment]
Is owncloud 1.8 any better?

**Comment by vinz94f** [comment]
Owncloud 1.8 is OK. No problem with bitdefender antivirus.
