### ISSUE TITLE
Restore deleted files and get 0 byes files

### ISSUE THREAD

**Issue by ilhay** [owncloud/client#2669]
Hello,

My employee move some of folder in shared folder to outside share folder. Files and folder are gone... then I check on "deleted files" I see these folder are there then, I click on "restore" to restore deleted files. The deleted files and folder are remove on "deleted files menu" and show on share directory but, files and folder have 0 byes.

how can I solve the issues?

ownCloud 7.0.4 (stable) 

P.S. Sorry in my English.

Thanks

**Comment by ilhay** [comment]
for more information

- PHP :  PHP 5.3.3 (cli) (built: Oct 30 2014 20:12:53)
- MySQL : mysql  Ver 14.14 Distrib 5.1.73, for redhat-linux-gnu (x86_64) using readline 5.1
- OS : CentOS 6.6 64bit
- Storage backend: Local drive, simfs file system, OpenVZ Virtualization on Proxmox

Thans

**Comment by guruz** [comment]
@ilhay Are you using the desktop client or webinterface?

**Comment by ogoffart** [comment]
What was the version of the client?
When someone remove (or move) file from a shared folder, the client will propagate the changes.
You should mark the folder as read only if you don't want the users to mess with it.

**Comment by guruz** [comment]
CC @PVince81 I think there was a bug that was fixed meanwhile?

**Comment by PVince81** [comment]
Note sure. It is also likely that files got auto-expired if too big which result in an empty folder.
