### ISSUE TITLE
[OS X] Generated Package is of 4MB only. Doesn't open when double clicked

### ISSUE THREAD

**Issue by supportreq** [owncloud/client#2670]
Hi,
I was able to compile and generate the pkg file for owncloud 1.7.1.. The generated package is of size only 4MB.

After installing the client doesn't open directly. It opens only through Terminal using :
./Applications/owncloud.app/Contents/MacOS/owncloud

Please advice.

**Comment by supportreq** [comment]
The app file has QT Libraries & Plugins are missing..

Please advice..

**Comment by supportreq** [comment]
Commands used : 
$mkdir mirall-buildn
$cd mirall-buildn
$cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DCMAKE_INSTALL_PREFIX=../install -DCMAKE_BUILD_TYPE=“Debug” ../mirall
$make install
$cd admin/osx
$./create_mac.sh ../../../install ../../../mirall-buildn

Output : https://gist.github.com/anonymous/fd187f06a41b0d3ee009

**Comment by supportreq** [comment]
@danimo any idea?

**Comment by guruz** [comment]
@supportreq Sorry, I think the best is you join #owncloud-client-dev on IRC on irc.freenode.net and ask there...

CC @kwillems
