### ISSUE TITLE
A simple typo

### ISSUE THREAD

**Issue by enoch85** [owncloud/client#2672]
https://github.com/owncloud/mirall/pull/1717/files#diff-f2d6e0a4d2b25efe708acce987058200R467

![1 years](https://cloud.githubusercontent.com/assets/4511254/5328522/b5e52644-7d82-11e4-8e98-384e60ed9459.png)

**Comment by danimo** [comment]
Yes, that needs to use the plural translation scheme: http://doc.qt.digia.com/qq/qq19-plurals.html
