### ISSUE TITLE
GUI client runs out of file descriptors while syncing

### ISSUE THREAD

**Issue by qris** [owncloud/client#2675]
Similar to #154 which @sciurius requested to reopen but is still closed. The cause might be different: it's not many instances of /dev/random that are open, but all manner of files that are being uploaded.

The error is still:

    GLib-ERROR **: Creating pipes for GWakeup: Too many open files Trace/Breakpoint triggered

However this happens while updating the GUI, and does not happen at the point where the error is, so the backtrace is not helpful. This merely shows that the 1024th open file was opened somewhere else and not closed yet.

It's difficult to debug because it appears to be somewhat random, only happens when uploading large numbers of files, and it takes a long time for the client to discover all local files before it starts syncing and hits the error and dies.

### Expected behaviour
Client does not run out of file handles when syncing large numbers of files.

### Actual behaviour
Client runs out of file handles when syncing large numbers of files.

### Steps to reproduce
1. Place ~260k files in your owncloud directory
2. Start client
3. Wait for it to start actual syncing, sometime after first instance of `OCC::PUTFileJob::PUTFileJob` is created.
4. Maybe it will open too many fds and crash.

If you run it in a debugger and use lsof when it's crashed, you can see many files still open. This is an example stopped before the crash but while fds were leaking:

    owncloud 5417 chris  414r   REG               0,30      4978 23996513 /home/chris/owncloud/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/django/forms/extras/widgets.py
    owncloud 5417 chris  415r   REG               0,30      5672 23996514 /home/chris/owncloud/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/django/forms/extras/widgets.pyc
    owncloud 5417 chris  416r   REG               0,30     44425 23996523 /home/chris/owncloud/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/django/forms/fields.py
    owncloud 5417 chris  417r   REG               0,30     49520 23996524 /home/chris/owncloud/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/django/forms/fields.pyc
    owncloud 5417 chris  418r   REG               0,30     23725 23996521 /home/chris/owncloud/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/django/forms/forms.py

Note that the last file is fd 418. There are about 360 files open that should have been uploaded and closed by now.

I can see in the logs that `OCC::PUTFileJob`s are created and finished for each file:

    01-07 17:04:57:821 0x739740 void OCC::BandwidthManager::registerUploadDevice(OCC::UploadDevice*) OCC::UploadDevice(0xa6cf440) 
    01-07 17:04:57:823 0x739740 !!! OCC::PUTFileJob created for  QUrl( "https://files.aptivate.org" )  querying "/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/ElementInclude.pyc" 
    ...
    01-07 17:04:58:334 0x739740 void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://files.aptivate.org/remote.php/webdav/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/ElementInclude.pyc" )  FINISHED WITH STATUS 0 "" QVariant(int, 201) QVariant(QString, "Created") 
    ...
    01-07 17:04:58:336 0x739740 void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem&) "testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/ElementInclude.pyc" 4 "" 

and the UploadDevice that was created is eventually destroyed, three jobs later:

    01-07 17:04:58:337 0x739740 void OCC::BandwidthManager::unregisterUploadDevice(OCC::UploadDevice*) OCC::UploadDevice(0xa6cf440) 

But somehow these files are not being closed. I assume that they must be closed at the end of the sync, otherwise everyone would be having massive problems with leaking file descriptors, so something must be hanging onto a reference and preventing them from being closed. But debugging this in gdb is hard when I can't inspect QFile objects.

### Client configuration
Client version: 1.8.0

Operating system: Ubuntu 12.04.5 LTS

OS language: English

Installation path of client: git checkout, not installed

### Logs

	01-07 17:04:57:821 0x739740 void OCC::BandwidthManager::registerUploadDevice(OCC::UploadDevice*) OCC::UploadDevice(0xa6cf440) 
	01-07 17:04:57:823 0x739740 !!! OCC::PUTFileJob created for  QUrl( "https://files.aptivate.org" )  querying "/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/ElementInclude.pyc" 
	01-07 17:04:57:823 0x739740 Num active jobs:  3 
	01-07 17:04:58:038 0x739740 void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://files.aptivate.org/remote.php/webdav/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml-3.3.5-py2.7.egg-info/top_level.txt" )  FINISHED WITH STATUS 0 "" QVariant(int, 201) QVariant(QString, "Created") 
	01-07 17:04:58:038 0x739740 OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem&, const QString&) "/home/chris/owncloud/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml-3.3.5-py2.7.egg-info/top_level.txt" Retrieved inode  24521545 (previous item inode:  24521545 ) 
	01-07 17:04:58:039 0x739740 "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13);" -4479211099373172508 122 "testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml-3.3.5-py2.7.egg-info/top_level.txt" 24521545 0 "1406289766" "0" "54ad67376f86c" "00012804oc15b6843311" "" 5 
	01-07 17:04:58:039 0x739740 "DELETE FROM uploadinfo WHERE path=?1" "testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml-3.3.5-py2.7.egg-info/top_level.txt" 
	01-07 17:04:58:039 0x739740 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "upload file start" and starting new transaction 
	01-07 17:04:58:041 0x739740 void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem&) "testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml-3.3.5-py2.7.egg-info/top_level.txt" 4 "" 
	01-07 17:04:58:042 0x739740 OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem&, const QString&) "/home/chris/owncloud/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml-3.3.5-py2.7.egg-info" Retrieved inode  24521542 (previous item inode:  24521542 ) 
	01-07 17:04:58:042 0x739740 "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13);" 8708726786940198804 108 "testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml-3.3.5-py2.7.egg-info" 24521542 0 "1420649490" "2" "54ad6412cf1aa" "00012595oc15b6843311" "RDNVCK" 0 
	01-07 17:04:58:042 0x739740 void OCC::BandwidthManager::unregisterUploadDevice(OCC::UploadDevice*) OCC::UploadDevice(0x143212e0) 
	01-07 17:04:58:044 0x739740 void OCC::BandwidthManager::registerUploadDevice(OCC::UploadDevice*) OCC::UploadDevice(0x11338a10) 
	01-07 17:04:58:047 0x739740 !!! OCC::PUTFileJob created for  QUrl( "https://files.aptivate.org" )  querying "/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/__init__.py" 
	01-07 17:04:58:047 0x739740 Num active jobs:  3 
	01-07 17:04:58:137 0x739740 void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://files.aptivate.org/remote.php/webdav/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/ElementInclude.py" )  FINISHED WITH STATUS 0 "" QVariant(int, 201) QVariant(QString, "Created") 
	01-07 17:04:58:137 0x739740 OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem&, const QString&) "/home/chris/owncloud/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/ElementInclude.py" Retrieved inode  24522585 (previous item inode:  24522585 ) 
	01-07 17:04:58:138 0x739740 "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13);" 4683590323694767641 105 "testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/ElementInclude.py" 24522585 0 "1406289455" "0" "54ad673788ec7" "00012805oc15b6843311" "" 7641 
	01-07 17:04:58:138 0x739740 "DELETE FROM uploadinfo WHERE path=?1" "testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/ElementInclude.py" 
	01-07 17:04:58:138 0x739740 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "upload file start" and starting new transaction 
	01-07 17:04:58:140 0x739740 void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem&) "testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/ElementInclude.py" 4 "" 
	01-07 17:04:58:141 0x739740 void OCC::BandwidthManager::unregisterUploadDevice(OCC::UploadDevice*) OCC::UploadDevice(0xf4f0830) 
	01-07 17:04:58:142 0x739740 void OCC::BandwidthManager::registerUploadDevice(OCC::UploadDevice*) OCC::UploadDevice(0xf4f0830) 
	01-07 17:04:58:144 0x739740 !!! OCC::PUTFileJob created for  QUrl( "https://files.aptivate.org" )  querying "/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/__init__.pyc" 
	01-07 17:04:58:144 0x739740 Num active jobs:  3 
	01-07 17:04:58:334 0x739740 void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://files.aptivate.org/remote.php/webdav/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/ElementInclude.pyc" )  FINISHED WITH STATUS 0 "" QVariant(int, 201) QVariant(QString, "Created") 
	01-07 17:04:58:334 0x739740 OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem&, const QString&) "/home/chris/owncloud/testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/ElementInclude.pyc" Retrieved inode  24522596 (previous item inode:  24522596 ) 
	01-07 17:04:58:334 0x739740 "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13);" 6482928685305138804 106 "testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/ElementInclude.pyc" 24522596 0 "1406289766" "0" "54ad6737a922f" "00012806oc15b6843311" "" 4948 
	01-07 17:04:58:334 0x739740 "DELETE FROM uploadinfo WHERE path=?1" "testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/ElementInclude.pyc" 
	01-07 17:04:58:335 0x739740 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "upload file start" and starting new transaction 
	01-07 17:04:58:336 0x739740 void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem&) "testfiles/360giving-demos/360giving/django/website/.ve/lib/python2.7/site-packages/lxml/ElementInclude.pyc" 4 "" 
	01-07 17:04:58:337 0x739740 void OCC::BandwidthManager::unregisterUploadDevice(OCC::UploadDevice*) OCC::UploadDevice(0xa6cf440)

**Comment by guruz** [comment]
Thanks for the report.

@ogoffart I remember the QFile is per sync item (not per chunk).
``` QSharedPointer<QIODevice> _device;```
 Does it really get closed properly? I don't see the relevant code..

**Comment by lmaestro** [comment]
I tried to reproduce this issue with 1.7.1 and it is not reproduce. 
When I tried to reproduce it with the latest version I have this error: "Error downloading server replied- unkonwn ()"

Logs 

```
01-19 15:03:25:276 0x104d14380 syncjournalfilerecord.cpp:135 blacklisting  "3/10/example64.file"  for  25 , retry count  1
01-19 15:03:25:276 0x104d14380 syncjournaldb.cpp:1123 set blacklist entry for  "3/10/example64.file" 1 "Error downloading http://daily.owncloud.com/stable7/owncloud/remote.php/webdav/3/10/example64.file - server replied: Unknown ()" 1421676205 25 1352378196 ""
01-19 15:03:25:276 0x104d14380 syncengine.cpp:772 void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem &) "3/10/example64.file" 2 "Error downloading http://daily.owncloud.com/stable7/owncloud/remote.php/webdav/3/10/example64.file - server replied: Unknown ()"
01-19 15:03:25:279 0x104d14380 socketapi.cpp:325 SocketApi:  Sending message:  "STATUS:ERROR:/Users/lmaestro/owncloud-servers/test2675/3/10/example64.file"
01-19 15:03:25:280 0x104d14380 bandwidthmanager.cpp:116 void OCC::BandwidthManager::unregisterUploadDevice(OCC::UploadDevice *) OCC::UploadDevice(0x10e4accb0)
01-19 15:03:25:280 0x104d14380 bandwidthmanager.cpp:89 void OCC::BandwidthManager::registerUploadDevice(OCC::UploadDevice *) OCC::UploadDevice(0x1109f4ee0)
01-19 15:03:25:281 0x104d14380 networkjobs.cpp:224 !!! OCC::PUTFileJob created for  QUrl( "http://daily.owncloud.com/stable7/owncloud" )  querying "/3/10/example67.file"
01-19 15:03:25:337 0x104d14380 bandwidthmanager.cpp:116 void OCC::BandwidthManager::unregisterUploadDevice(OCC::UploadDevice *) OCC::UploadDevice(0x1109f4ee0)
01-19 15:03:25:454 0x104d14380 networkjobs.cpp:158 void OCC::AbstractNetworkJob::slotFinished() 499 "Error downloading http://daily.owncloud.com/stable7/owncloud/remote.php/webdav/3/10/example65.file - server replied: Unknown"
01-19 15:03:25:454 0x104d14380 propagateupload.cpp:422 void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "http://daily.owncloud.com/stable7/owncloud/remote.php/webdav/3/10/example65.file" )  FINISHED WITH STATUS 499 "Error downloading http://daily.owncloud.com/stable7/owncloud/remote.php/webdav/3/10/example65.file - server replied: Unknown" QVariant(int, 507) QVariant(QString, "Unknown")
01-19 15:03:25:454 0x104d14380 propagateupload.cpp:446 "<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\InsufficientStorage</s:exception>
  <s:message></s:message>
  <s:sabredav-version>1.8.10</s:sabredav-version>

```

**Comment by guruz** [comment]
Check the exception... is your server disk full?

```Sabre DAV Exception InsufficientStorage```

**Comment by guruz** [comment]
@lmaestro This needs to be tested with 1.8.x not 1.7.1
