### ISSUE TITLE
One remotePollInterval per folder

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#2677]
Is it possible to configure individual remotePollInterval for each sync folder?
For my folder with working files I'd like to poll more frequently than a folder which only contains photos (which never change). So I think, this would be a nice enhancement.

**Comment by guruz** [comment]
No plan to do this at the moment.
The solution is to make the current polling mechanisms more efficient or not needing them at all.

We're looking into it..

CC @icewind1991 @ogoffart
