### ISSUE TITLE
[OS X] Files with folder-structure don't sync

### ISSUE THREAD

**Issue by zocker22** [owncloud/client#2679]
OSX, Yosemite, Sync-Client 1.7.1 (build 1655)

I have a file from [OmniGraffle](https://www.omnigroup.com/omnigraffle) in my sync folder. The file is named "_Grafiken" and won't sync.
When looking at the file with the shell, I recognized, its a folder that is called "_Grafiken.graffle". In that folder are three files: data.plist,image2.png,image3.png.

The SyncClient throws an error:
08:51     3_Semester/_Grafiken.graffle/image3.png             Docs            Nicht erlaubt, da Sie keine Rechte zum Hinzufügen von Dateien in diesen Ordner haben          
08:51     3_Semester/_Grafiken.graffle/image2.png             Docs            Nicht erlaubt, da Sie keine Rechte zum Hinzufügen von Dateien in diesen Ordner haben          
08:51     3_Semester/_Grafiken.graffle/data.plist             Docs            Nicht erlaubt, da Sie keine Rechte zum Hinzufügen von Dateien in diesen Ordner haben          

When I rename the so called file from "_Grafiken.graffle" to "Grafiken.graffle" everything works fine and syncs. 
Is this the expected behaviour?

**Comment by guruz** [comment]
I wonder if this is similar to those issues: https://github.com/owncloud/client/search?utf8=%E2%9C%93&q=%22hard+link%22&type=Issues

**Comment by zocker22** [comment]
I wonder too. I read the posts you referred to. What I don't understand: When I renamed the file (that acutally is a folder) it suddendly worked. If the problem was due to hard link issues, it still should not sync. Did I get this right?

**Comment by guruz** [comment]
That's indeed strange.
Do you think the ```_``` prefix is a problem?
Or would renaming it to ```______Grafiken.grafle``` also make it work by somehow changing the bundle properties?

**Comment by zocker22** [comment]
This is actually a very good question.
I duplicated the file (folder) and named it "_Grafiken.graffle", "__Grafiken.graffle", and "___Grafiken.graffle" and this time the upload worked fine. I neither can explain it nor am I able to reproduce the problem I had three weeks ago.
It seems you where right with your guess, that renaming the folder somehow changed the properties of the files inside.
I will keep a close eye on this but because I'm not able to reproduce it anymore I suggest closing this bug. Man that annoyes me :/

**Comment by guruz** [comment]
Possibly related https://github.com/owncloud/client/issues/2949

**Comment by guruz** [comment]
Transformed to https://github.com/owncloud/client/issues/3202
