### ISSUE TITLE
remotePollInterval and PROPFIND /remote.php/webdav/ 

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#2682]
http://doc.owncloud.org/desktop/1.7/advancedusage.html reads:

    remotePollInterval (default: 30000) – Specifies the poll time for the remote repository in milliseconds.

After guessing that this setting has to go into the ownCloud section, I set it to 5 minutes:

    [ownCloud]
    remotePollInterval=300000

However, the server logs show that there still is a PROPFIND every 30 seconds:

    PROPFIND /remote.php/webdav/ 

Note: Without any trailing folder. The folders are refreshed only every 5 minutes.

Why is there another PROPFIND and how can I configure its frequency?

Using: 1.7.1 on Windows

**Comment by LukeOwncloud** [comment]
I just checked what ```PROPFIND /remote.php/webdav/ ``` actually gives me:
Etags of all children. So there is actually everything I need to determine that nothing changed. Right?

So there should be only that PROPFIND every 5 minutes. And the correct question is:

Why are there every 5 minutes:

    PROPFIND /remote.php/webdav/folder1
    PROPFIND /remote.php/webdav/folder2
    PROPFIND /remote.php/webdav/folder3
    ...

??

**Comment by LukeOwncloud** [comment]
I just checked what ```PROPFIND /remote.php/webdav/ ``` actually gives me:
Etags of all children. So there is actually everything I need to determine that nothing changed. Right?

So there should be only that PROPFIND every 5 minutes. And the correct question is:

Why are there every 5 minutes:

    PROPFIND /remote.php/webdav/folder1
    PROPFIND /remote.php/webdav/folder2
    PROPFIND /remote.php/webdav/folder3
    ...

??

**Comment by ogoffart** [comment]
This might be the PROPFIND to check the quota...

**Comment by LukeOwncloud** [comment]
That doesn't make any sense at all: When I configure an interval of 5 minutes and it still connects every 30 seconds, what is this setting for? Even worse: When in this quota request all information about changes is already included (etags for all folders), why is that data not used?

**Comment by guruz** [comment]
I'm closing this issue as the quota request will be sent less often in the future:
https://github.com/owncloud/client/issues/2951

**Comment by LukeOwncloud** [comment]
"future" means version 1.9.0? With 1.8.0 the server log still looks very crowded.

**Comment by LukeOwncloud** [comment]
I am reopening this issue. With client 1.8.1 there are still too many PROPFINDs. See log below (client was minimized).
remotePollInterval is set to 5 minutes. It seems there are two 30-seconds-loops doing PROPFINDs.

Is it wanted that the configured poll interval no respected?

    IP - luke [12/Jun/2015:08:03:28 +0200] "PROPFIND /remote.php/webdav/shared HTTP/1.1" 207 10950 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:03:28 +0200] "PROPFIND /remote.php/webdav/luke HTTP/1.1" 207 5380 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:03:50 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1448 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:03:57 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1495 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:04:22 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1448 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:04:27 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1352 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:04:54 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 2718 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:04:57 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1352 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:05:26 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1448 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:05:27 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1352 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:05:57 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1495 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:05:58 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1305 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:06:27 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1495 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:06:30 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1305 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:06:58 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1495 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:07:02 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1305 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:07:28 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1495 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:07:34 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1448 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:07:58 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1495 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:08:06 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1448 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:08:28 +0200] "PROPFIND /remote.php/webdav/shared HTTP/1.1" 207 11093 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:08:28 +0200] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1495 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"
    IP - luke [12/Jun/2015:08:08:28 +0200] "PROPFIND /remote.php/webdav/luke HTTP/1.1" 207 5380 "-" "Mozilla/5.0 (Windows) mirall/1.8.1"

**Comment by LukeOwncloud** [comment]
Ah. Duplicate of https://github.com/owncloud/client/issues/1470. Closing.
