### ISSUE TITLE
Unable to launch owncloud client on Mac with the log feature

### ISSUE THREAD

**Issue by Rene33** [owncloud/client#2686]
I use owncloud 1.7.1 with Mac OS 10.9.5, and I have problems of crash (that will be another post). 
I tried to launch the client with the log feature, as explained here : (http://doc.owncloud.org/desktop/1.7/tro ... oting.html)
But I obtain an error message : 
>Macrene:~ rene$ /Applications/owncloud.app/Contents/MacOs/owncloud --logwindow
>This application failed to start because it could not find or load the Qt platform plugin "cocoa".
>
>Reinstalling the application may fix this problem.
>Abort trap: 6

I have tried to reinstall the client, but without success.

**Comment by guruz** [comment]
@Rene33 is the behaviour different if you do:
```
Macrene:~ rene$ (cd /Applications/owncloud.app/Contents/MacOs/ ; ./owncloud --logwindow
```

**Comment by Rene33** [comment]
I just tried,
It works !
so it might not be a bug, but just a need to indicate the trick in the manual...

**Comment by guruz** [comment]
Then it is still a bug, it means our Qt-packaging into the .app bundle does not work properly..

@danimo this is your area..

**Comment by guruz** [comment]
@Rene33 Did you compile from source?

**Comment by Rene33** [comment]
@guruz no, I used the .pkg available on the site.

**Comment by guruz** [comment]
I cannot reproduce this with the .pkg and also 10.9.5..
I don't know what is wrong here, let's reopen this if others report it.

**Comment by Rene33** [comment]
For me its OK, as you gave me the solution to run the client with the logging function. But from what I read, it seems that my problem is related to a bug in Qt : https://bugreports.qt.io/browse/QTBUG-29503 which has to do with a question of path...
thanks

**Comment by faisalna** [comment]
I tried this and still getting the error . 
bash-3.2$ (cd /Applications/owncloud.app/Contents/MacOs/ ; ./owncloud --logwindow)
This application failed to start because it could not find or load the Qt platform plugin "cocoa".

Reinstalling the application may fix this problem.

Note: I compiled the package from source and created a package using create_mach.sh
