### ISSUE TITLE
[1.7.0] "Remove all files" prompt

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#2687]
In which condition, is this prompt designed to show up?

When I pushed “enter (return)” mistakenly and deleted all the local files, but the next day, I saw all the files were recovered on ownCloud server.

Could you please explain why the files were recovered?

### How to reproduce it:

BEFORE THE TEST:
Local sync folder has the following file and sync to ownCloud server has been completed.
- three folders
- three dummy file which are 2GB in size.
- four pdf files
- four jpeg files
- one text file

First day:
I did the following to reproduce the issue “download just after upload” (https://github.com/owncloud/client/issues/1425).
On sync client setting, deleted sync folder.
Quit sync client.
Deleted *.db and *.log files from sync folder.
Logged into ownCloud server from browser and deleted all the files.

Started Sync-Client.
Added local folder as sync folder.
Sync started.
After a while, “operation canceled” error occurred.
Retry was done a couple of times, but still resulted in “operation canceled”.
Stop sync.

Logged into ownCloud server from browser.
No file or folder existed.

In the local folder, deleted one 2GB file (two other 2GB files were left).

On sync client setting, deleted sync folder.
Quit sync client.
Deleted *.db and *.log files from sync folder.

Started Sync-Client.
Added local folder as sync folder.
Sync started and it finished in 15 minutes.

While checking the files, "Remove all files” prompt suddenly appeared.
They selected to “leave files” at that time, but the prompt appeared again.
It was just the timing when the customer is pushing “enter (return)” in writing a email and so “remove all files” was selected.

Logged into ownCloud server from browser.
No file or folder existed.
In the local folder, no file or folder existed as well.

Second Day:
On sync client setting, deleted sync folder.
Quit sync client.
Deleted *.db and *.log files from sync folder.

Logged into ownCloud server from browser.
No file or folder existed.
Viewed history in Activity page.
Then return to Files page and found all the files were recovered.

I first thought NFS server which ownCloud is using as backend storage was not responding at that time.
However, I could not reproduce the behavior above by creating the situation on our lab that NFS server does not respond.
In that test case, ownCloud just stopped responding and the prompt did not appear.

### Logs:
S3-ownCloud\Shared\owncloud\support\github-issues\mirall\2687

@MorrisJobke 

00001944

**Comment by guruz** [comment]
FYI I remember 1.7.1 had changes regarding this by @ogoffart

**Comment by dragotin** [comment]
I think this has the same root cause as #2689 . Please fix that first, and if this problem continues to happen afterwards, please reopen. Thx.

**Comment by cdamken** [comment]
Just asking removal of all the files would not fix this issue at all…the customer had seen the prompt and selected “remove all files” mistakenly.
However, the files were reappeared somehow.  How can the behavior be explained?

**Comment by ogoffart** [comment]
The files are removed because the server told us that the file were removed.
It is a sever problem. Sometimes there is a connection problem wih the bckend and the server used to report no files instead of an error.

There is nothing we can do on the client. (Well, there is, we could detect that something is wrong if all files get suddenly deleted, which is why we show a warning)
The problem lies in the server.
