### ISSUE TITLE
Add a configuration password to lock desktop client settings

### ISSUE THREAD

**Issue by gig13** [owncloud/client#2688]
Use case:
Add a configuration setting to basically password protect the client configuration settings. This enterprise would like to install the branded client with specific drives and block the ability of users to change these settings. Setting the password in the ownbrander to be encoded into the executable would allow for this option. The option to set a password would be optional, so only users/enterprises that would want to lock the setting could.

@rperezb @MTRichards

**Comment by guruz** [comment]
@gig13 Is this Windows-only?
I think in that case also some Registry/Policy thingy could be used that only the Network admin can set..

**Comment by gig13** [comment]
Windows an Mac

**Comment by danimo** [comment]
Removed reference to private repo.

**Comment by danimo** [comment]
I don't think a user-visible password is the way to go. I agree that implementing this feature in terms of Group Policies is a better and more generic approach. Also, a password in the UI would still allow users to change the settings in the file system.

/cc @craigpg @dragotin

**Comment by craigpg** [comment]
Need a bit more information on the specific use case(s).  Is the ask to have a client that is preconfigured in such a way that the end-user is _not allowed_ to make changes to some settings (e.g. sync folders)?  Adding the ability to edit these protected settings after entering a password only further complicates this basic use case.

Keep in mind that folder settings, for example, are stored in a text file that the user can access outside of the ownCloud settings panel, so disabling or password protecting aspects of the settings panel is probably not sufficient.  We need to consider storing a crypto-hash of the settings files that are not to be edited or having the settings built-in to the client directly as part of branding or ...

Lots of issues to sort out once we get more details on the requirements.

**Comment by gig13** [comment]
@craigpg 
The user should be able to type in the desktop configuration password and then be able to modify the configurations. Only an administrative or power user would have this password and be able to access the config settings.

The point about modifying the config file directly is interesting too, this may complicate how existing enterprises are distributing and managing.

**Comment by MTRichards** [comment]
We have a concept of "locking" certain settings on the desktop client, which we need to iron out. This is a good baseline concept for the next release after 1.9, allowing locking of a desktop client.

**Comment by gig13** [comment]
@MTRichards @bboule 
Is this on the radar? Linking SF 00002365

**Comment by MTRichards** [comment]
Not at this time. We would tie this in with the concept of server side configuration setting and do it all at once. No sense locking desktop settings if you can't change them in the future.

**Comment by MTRichards** [comment]
Since it needs a server side component, probably not until Jan earliest.

**Comment by bboule** [comment]
@gig13 @MTRichards Is this dead?  @gig13 is this still an open issue with the customer?  How should we proceed, or is this a close out?

**Comment by gig13** [comment]
@bboule 
This was accepted, but always on the backlog. I could check with Luke to see if there was any communication recently -- no open cases or other indication that this is a critical requirement.

**Comment by MTRichards** [comment]
Considering it still for Q1, maybe Q2. It is part of the server control channel option, so hanging out there while we finalize 2.1 and look to 2.2.

**Comment by bboule** [comment]
@gig13 based on that can you set an expectation with the customer?

**Comment by gig13** [comment]
Reset Expectations with customer. awaiting feedback

**Comment by MTRichards** [comment]
2.2 is finalized, and this is not in. BUT, Q2 may still be possible.

**Comment by MTRichards** [comment]
But from what I read, the client side settings they want to lock are...all of them? Or just the paths and sync directories? Or the bandwidth settings? 
Trying to figure out how much needs to be locked.

**Comment by gig13** [comment]
@MTRichards 
Ideally the paths and sync directories.

**Comment by MTRichards** [comment]
Anyone else have this request? This has been open for a year and only had 1 request, so just looking for a reason to raise priority.

**Comment by gig13** [comment]
No other specific users raised this.

**Comment by martin-eqipe** [comment]
We have more and more medium size business customers asking for similar feature. Simple password protect (plattform independent) or even management of client settings from server side would be a really great feature. Or maybe somekind of setup control file for making settings (and password lock) even simple during unattended setup! Thanks, keep going on this great work!

**Comment by guruz** [comment]
@martin-eqipe I'd suggest getting a commercial license for oC so you can influence the development or even have this developed for you.

**Comment by ogoffart** [comment]
Closing old issue.
