### ISSUE TITLE
Client deletes all data from external storage on mount-error

### ISSUE THREAD

**Issue by obma** [owncloud/client#2690]
Just discovered the following problem:

The data on my server lies on a seperate RAID and the users mount their folders via SFTP into their owncloud. Tonight there occured a problem mounting the RAID. After I started my laptop (with owncloud-client in autostart) the client deleted all the data from the mounts on the laptop - without a prompt or anything - before I could read the notification mail about the mounting problem.

Would be good if the client pauses synchronisation for external mounts if they can not be mounted or asks the user what to do (delete locally?). Maybe this is a server issue?

Some data on my setup (irrelevant in my this case, I guess):
Server: Ubuntu, owncloud 7.0.4 stable
Client: Arch, 1.7.1

**Comment by guruz** [comment]
Yes, this is a server issue. Could you post it on https://github.com/owncloud/core/issues/new ? thanks

**Comment by dragotin** [comment]
The server should reply with 503 on the PROPFIND on the directory or files within.

**Comment by obma** [comment]
If I search for 503-errors in the apache logs I only find old errors from January 1st, not from tonight:
```shell
:~$ zgrep " 503 " /var/log/apache2/xxx-*
/var/log/apache2/xxx-access.log.1:127.0.0.1 - max [01/Jan/2015:22:38:05 +0100] "GET /owncloud/status.php HTTP/1.1" 503 8008 "-" "Mozilla/5.0 (Linux) mirall/1.7.1"
/var/log/apache2/xxx-access.log.1:127.0.0.1 - max [01/Jan/2015:22:38:37 +0100] "GET /owncloud/status.php HTTP/1.1" 503 8008 "-" "Mozilla/5.0 (Linux) mirall/1.7.1"
/var/log/apache2/xxx-access.log.1:127.0.0.1 - max [01/Jan/2015:22:39:09 +0100] "GET /owncloud/status.php HTTP/1.1" 503 8008 "-" "Mozilla/5.0 (Linux) mirall/1.7.1"
/var/log/apache2/xxx.log.1:127.0.0.1 - max [01/Jan/2015:22:39:41 +0100] "GET /owncloud/status.php HTTP/1.1" 503 8008 "-" "Mozilla/5.0 (Linux) mirall/1.7.1"
```

**Comment by dragotin** [comment]
@obma yes, that is fine. The problem in this case is probably that the external storage module on the server does **not** properly reply the 503 to indicate the client to not delete anything.

Please refer the server issue here. Thanks.

**Comment by obma** [comment]
As told before, I opened an issue in the server repo: https://github.com/owncloud/core/issues/13238
