### ISSUE TITLE
Download stalling for some files

### ISSUE THREAD

**Issue by simonspa** [owncloud/client#2691]
### Expected behaviour
owncloud client is started with an empty local folder, all files should be downloaded.

### Actual behaviour
The client fails to fetch some files (apparently only large files are problematic). That specific user has some 6 GB of data on the server, split into several thousand files. The problematic files are comparatively big (around 500 MB).

However, for test purposes I created another user and uploaded as well as downloaded files as large as 2 GB without problems, so the problem somehow seems to appear only for these specific files.

I do not get any message in the server log files during this process, neither in the owncloud log nor in the nginx error log - so it does not seem to be a server issue as far as I can tell.

### Server configuration
Operating system: Debian 7.6

Web server: nginx / FPM/FastCGI 

Database: MySQL

PHP version:  5.4.36

ownCloud version: 7.0.4

Storage backend: local storage

### Client configuration
Client version: 1.7.1

Operating system: Ubuntu 14.10 64bit

OS language: English

Installation path of client: /usr/bin/owncloud

### Logs

The owncloud client starts the sync and outputs the following log chunk when reaching one of the files in question:
```
01-11 13:37:40:972 0x17be5e8 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start2" and starting new transaction 
01-11 13:37:40:973 0x17be5e8 "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "my/big/file.ext" "my/big/file.ext.~7f6af5df" "54aff82d1eedc" 0 
01-11 13:37:40:973 0x17be5e8 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction 
01-11 13:37:41:693 0x17be5e8 Content encoding ist <empty> with status 200
01-11 13:37:53:049 0x12f3590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-11 13:37:57:354 0x12f3590 !!! Mirall::CheckQuotaJob created for  QUrl( "https://myurl.com/owncloud" )  querying "/" 
01-11 13:38:23:050 0x12f3590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-11 13:38:53:049 0x12f3590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-11 13:39:23:052 0x12f3590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-11 13:39:53:049 0x12f3590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-11 13:40:23:054 0x12f3590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-11 13:40:53:049 0x12f3590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-11 13:41:23:050 0x12f3590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-11 13:41:53:049 0x12f3590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-11 13:42:23:055 0x12f3590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-11 13:42:53:055 0x12f3590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-11 13:42:57:360 0x12f3590 Mirall::CheckQuotaJob(0x17c36e0) Timeout 
01-11 13:42:57:361 0x12f3590 void Mirall::AbstractNetworkJob::slotFinished() 5 "Operation canceled" 
01-11 13:42:57:364 0x12f3590 folder  "ownCloud"  Terminating! 
01-11 13:42:57:365 0x12f3590 void Mirall::SyncJournalDb::walCheckpoint() took 0 msec 
01-11 13:42:57:366 0x12f3590 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "All Finished."  
01-11 13:43:47:380 0x17be5e8 Neon error code was 1
01-11 13:43:47:382 0x17be5e8 bool Mirall::PropagateNeonJob::updateErrorFromSession(int, ne_request*, int) NE_ERROR "Sync was aborted by user." 0 0 
01-11 13:43:47:382 0x17be5e8 Error GET: Neon: 1
01-11 13:43:47:382 0x12f3590 CSync run took  381248 
01-11 13:43:47:390 0x12f3590 -> SyncEngine finished without problem. 
```

For the large files of the other user (download working fine) the log looks like the following:
```
01-10 18:19:20:604 0xebc1d8 "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "largefile.ext" ".largefile.ext.~1c69fb81" "54b153ce578b2" 0 
01-10 18:19:20:604 0xebc1d8 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction 
01-10 18:19:36:198 0xaec590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-10 18:19:36:682 0xaec590 !!! Mirall::CheckQuotaJob created for  QUrl( "https://myurl.com/owncloud" )  querying "/" 
01-10 18:20:06:197 0xaec590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-10 18:20:11:394 0xaec590 !!! Mirall::CheckQuotaJob created for  QUrl( "https://myurl.com/owncloud" )  querying "/" 
01-10 18:20:18:756 0xebc1d8 Content encoding ist <empty> with status 200
01-10 18:20:36:197 0xaec590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-10 18:20:48:243 0xaec590 !!! Mirall::CheckQuotaJob created for  QUrl( "https://myurl.com/owncloud" )  querying "/" 

[ repeats a few dozen times ]

01-10 18:45:06:197 0xaec590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-10 18:45:22:317 0xaec590 !!! Mirall::CheckQuotaJob created for  QUrl( "https://myurl.com/owncloud" )  querying "/" 
01-10 18:45:36:197 0xaec590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-10 18:45:54:136 0xaec590 !!! Mirall::CheckQuotaJob created for  QUrl( "https://myurl.com/owncloud" )  querying "/" 
01-10 18:46:06:197 0xaec590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-10 18:46:25:374 0xaec590 !!! Mirall::CheckQuotaJob created for  QUrl( "https://myurl.com/owncloud" )  querying "/" 
01-10 18:46:36:197 0xaec590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-10 18:46:56:157 0xaec590 !!! Mirall::CheckQuotaJob created for  QUrl( "https://myurl.com/owncloud" )  querying "/" 
01-10 18:47:06:197 0xaec590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-10 18:47:27:108 0xaec590 !!! Mirall::CheckQuotaJob created for  QUrl( "https://myurl.com/owncloud" )  querying "/" 
01-10 18:47:36:197 0xaec590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-10 18:47:58:312 0xaec590 !!! Mirall::CheckQuotaJob created for  QUrl( "https://myurl.com/owncloud" )  querying "/" 
01-10 18:48:06:197 0xaec590 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
01-10 18:48:26:743 0xebc1d8 Mirall::SyncJournalFileRecord::SyncJournalFileRecord(const Mirall::SyncFileItem&, const QString&) "/path/to/owncloud/largefile.ext" Retrieved inode  7081117 (previous item inode:  0 ) 
01-10 18:48:26:743 0xebc1d8 "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12);" -5767160252499301926 12 "largefile.ext" 7081117 0 "1406561609" "0" "54b153ce578b2" "00026504511a994fee2cc" "RDNVW" 
01-10 18:48:26:743 0xebc1d8 "DELETE FROM downloadinfo WHERE path=?1" "VTS_01_1.VOB" 
01-10 18:48:26:746 0xaec590 void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem&) "VTS_01_1.VOB" 4 "" 
```

Can anyone help me with this or give me some clues where to look for more information?
Thanks!

**Comment by simonspa** [comment]
One connected problem is that apparently this error condition is not caught and the full sync is stored as successfully finished, the client does not start another attempt to sync after such a problem:

```
01-11 13:42:57:366 0x12f3590 void Mirall::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "All Finished."  
```

**Comment by guruz** [comment]
> The problematic files are comparatively big (around 500 MB).
> However, for test purposes I created another user and uploaded as well as downloaded files as large as 2 GB without problems, so the problem somehow seems to appear only for these specific files.

Is that a shared file? Anything else which could be special?

**Comment by guruz** [comment]
@DeepDiver1975 FYI the quota job aborts the sync because the quota job times out.
@ckamm has seen this before, we were told the QuotaJob is cheap but maybe is not?

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 FYI the quota job aborts the sync because the quota job times out.

@guruz what request is used to query the quota? THX

**Comment by simonspa** [comment]
@guruz: nope, no shared file, no encryption, nothing special that I'm aware of.

What I also observed is that for large files it seems to take ages until the download actually starts - but then download speed is as expected.

**Comment by guruz** [comment]
@DeepDiver1975 https://github.com/owncloud/client/blob/0ae9055ea67d80354b17f5f4a8503edee8cf45cd/src/libsync/networkjobs.cpp#L597

**Comment by dragetd** [comment]
I can confirm a similar behavoir. Local owncloud client (1.7.1 Gentoo Linux) unable to sync a folder (shared external folder form a different owncloud)

Local log keeps saying:
02-26 20:21:23:152 0x1be4670 !!! Mirall::CheckQuotaJob created for  QUrl( "https://cloud.speciesm.net" )  querying "/" 
02-26 20:21:45:604 0x1be4670 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
02-26 20:21:53:820 0x1be4670 !!! Mirall::CheckQuotaJob created for  QUrl( "https://cloud.speciesm.net" )  querying "/" 
02-26 20:22:15:619 0x1be4670 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
02-26 20:22:24:438 0x1be4670 !!! Mirall::CheckQuotaJob created for  QUrl( "https://cloud.speciesm.net" )  querying "/" 
02-26 20:22:45:605 0x1be4670 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
02-26 20:22:54:938 0x1be4670 !!! Mirall::CheckQuotaJob created for  QUrl( "https://cloud.speciesm.net" )  querying "/" 
02-26 20:23:15:615 0x1be4670 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
02-26 20:23:25:399 0x1be4670 !!! Mirall::CheckQuotaJob created for  QUrl( "https://cloud.speciesm.net" )  querying "/" 
02-26 20:23:45:605 0x1be4670 void Mirall::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
…

Some timeout inccorectly abborting the sync with recoery?

**Comment by guruz** [comment]
Could you guys try the 1.8 beta?

**Comment by guruz** [comment]
Please try a new release.

**Comment by dragetd** [comment]
I tried the 1.8 release. No change whatsoever. The log still shows multiple slotEtagPollTimerTimeout() - could you confirm that this means the Client aborted the sync for this folder? - and my external storages are unable to sync.

Plus, the tray-icon shows a red cross first just like the main GUI when opened. But after closing it and a few seconds later, the tray-icon returns to a green checkmark, despite the sync is still failed or waiting.

This bug is not resolved.

**Comment by guruz** [comment]
@dragetd Please create a new issue with the first minute or so of log so we can see why it would not sync.
