### ISSUE TITLE
Unlock issue #179.

### ISSUE THREAD

**Issue by curtiszimmerman** [owncloud/client#2694]
[This issue about delta sync](https://github.com/owncloud/client/issues/179) is almost certainly OwnCloud's most requested feature and a very popular issue. It was locked earlier today by @LukasReschke under the guise of reducing clutter. If this particular popular issue is causing too much noise for a specific person, they can simply [unsubscribe from the thread](https://help.github.com/articles/unsubscribing-from-conversations/) and the rest of us can continue discussing the feature and how to implement it.

It is contradictory that this issue was locked to reduce clutter because Lukas suggests creating a new issue in order to discuss the feature. Why are we being told to open another issue when this issue already contains discussion of the feature and also has [over a thousand dollar bounty](https://www.bountysource.com/issues/905030-sync-only-the-file-change-not-entire-file) on BountySource. There is real discussion going on in this issue about implementing the feature, and creating another issue would introduce confusion and even more clutter instead of keeping the comments centralized in this one issue.

Please unlock this issue.

**Comment by LukasReschke** [comment]
>It is contradictory that this issue was locked to reduce clutter because Lukas suggests creating a new issue in order to discuss the feature.  

No. I suggested to create a new issue if somebody wants to discuss the actual implementation not to discuss the feature. I'm subscribed to the event stream at https://github.com/orgs/owncloud/dashboard where ignoring an issue will not help at all.

Honestly, already in 2013 people where asked to stop :+1:'d that issue as you can see at https://github.com/owncloud/client/issues/179#issuecomment-22621959

From my opinion that issue honestly contains nothing except some ideas which are worth nothing at all unless they are implemented. Sure, it is nice to talk about sync using some zsync / rsync / whatever library but we're getting nowhere with a discussion that repeats itself again and again.  In my opinion this is just a waste of time of a lot of people's time.

(Please notice that this is solely my opinion and does not necessarily match those of other peoples)

**Comment by danimo** [comment]
I agree with @LukasReschke. We're always welcoming people who want to approach this issue to use IRC (as suggested in the developer manual), or use a push request against a development branch as an ignition spark.

The last messages are all either repeating earlier proposals, are expressions of disbelief (which does not help at all) or +1's.

In my experience, features do not appear by talking, but by doing.

**Comment by curtiszimmerman** [comment]
Well, I think what you've done with that issue is wrong.
