### ISSUE TITLE
Automatic proxy settings not working when changing the network

### ISSUE THREAD

**Issue by danimo** [owncloud/client#2695]
### Steps to reproduce
1. connect to school network with proxy with 'automatic proxy settings'
2. connecting with android tethering or with home network => "Access denied"
3. connect to school network with proxy again => "Access denied"
4. fix: entering the proxy settings manually or restarting the client

### Expected behaviour
In all other Applications (Dropbox, Browser) the 'Automatic Proxy Settings' are working.

### Actual behaviour
"Access denied" after switching networks.

**Operating system:**
Windows 8.1

@MorrisJobke @danimo @dragotin

00002342

**Comment by danimo** [comment]
This is essentially caused by https://bugreports.qt.io/browse/QTBUG-3470

**Comment by danimo** [comment]
@michaelstingl It would be interesting to know how to switch between proxies / disable proxies. The only way I know ho is via a dirty hack that basically means writing a PAC file that relies on an IP address range. Can you clarify? That would help with an accurate fix.

**Comment by michaelstingl** [comment]
@danimo no hacks. Only regular user interface:
http://doc.owncloud.org/desktop/1.7/_images/settings_network.png

**Comment by danimo** [comment]
@michaelstingl I am referring to the windows proxy settings. Contrary to e.g. OS X, they cannot specify an alternate configuration, unless (WPAD)[http://de.wikipedia.org/wiki/Web_Proxy_Autodiscovery_Protocol] is used. Is that the case?

**Comment by danimo** [comment]
@michaelstingl I mean on the windows system settings

**Comment by michaelstingl** [comment]
@danimo I requested this information, but no answer yet.

**Comment by danimo** [comment]
Here is what happened and will happen:

- [x] Propose fix to Qt (https://codereview.qt-project.org/#/c/104616/). 
- [x] Backported (tentatively) accepted patch state to OBS
- [ ] Update build host with new qtbase package and provide a nightly build

Currently waiting for OBS to publish the package that includes the build.

**Comment by danimo** [comment]
http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.4650-nightly20150128-setup.exe should no longer have this issue. Please test.

**Comment by danimo** [comment]
This build has dependency problems, I'll provide a new one asap

**Comment by danimo** [comment]
http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.4651-nightly20150128-setup.exe works

**Comment by lmaestro** [comment]
@michaelstingl Can you verify that it is fixed?

**Comment by lmaestro** [comment]
@michaelstingl any news? Can you try to reproduce using beta1 https://owncloud.org/install/#testing?

**Comment by michaelstingl** [comment]
@lmaestro Sorry, no response from user yet.

**Comment by danimo** [comment]
@michaelstingl Provide him with beta1.

**Comment by michaelstingl** [comment]
@lmaestro @danimo no response from user yet, I closed the case for now.

**Comment by unclejamal3000** [comment]
Seems still not fixed
Example: I'm connected to the company network via VPN client. Here I have to go through a proxy to reach the internet. Then I disconnect the VPN client, now I'm in the hotel public network without proxy. The UI begins to freeze every 15 seconds for about 20 seconds and I loose the connection until restart of the client.

Logfile is here:
https://gist.github.com/unclejamal3000/5790d2dcee0755973662

Client is build 4857

**Comment by unclejamal3000** [comment]
New test with build 4864. OS is Windows 7 SP1, OC client is configured to use System-Proxy
For scenario see comment in logfile here:
https://gist.github.com/unclejamal3000/cccb333794745c5b439b

**Comment by guruz** [comment]
@unclejamal3000 The build 4846 just contains the new Qt Network DLL, not the additional fix from 4863 (which doesn't contain the new Qt Network DLL). So you need something which contains both.
@danimo Are the normal nightly builds set to use that new Qt Network DLL yet?

**Comment by guruz** [comment]
@unclejamal3000 Here you go, the above mentioned build: http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.4890-nightly20150326-setup.exe

**Comment by unclejamal3000** [comment]
Again I had the same problem today with build 4890 that the client want's to connect to a proxy even though I'm in a public network -> https://github.com/owncloud/client/issues/2993#issuecomment-85972521
I assume this happens when I was connected to my company VPN under some circumstances (which I do not know at this moment) and disconnect it later.

After a reboot of my machine currently it's working as it should (changing between wired LAN, WIFI, VPN with proxy without problem).

I will observe this during the next days until I say that it's solved.

**Comment by guruz** [comment]
If you (inside the client) sign out and sign in, will it still detect the system proxy?

**Comment by unclejamal3000** [comment]
Again I have the same problem today. Was connected to the VPN for about 15min then disconnected from VPN. Skype, Chrome reconnect without restart, OC client wants to connect to the proxy.

@guruz What do you mean with sign out and sign in? Open the connection assistant and repeat the account configuration?

For now the problem was solved after switching to "No Proxy" and back to "Use System-Proxy". No restart of the client was necessary.

**Comment by guruz** [comment]
@unclejamal3000 I meant the "Sign out" and then "Sign in" options in the right-click tray menu.
And could you also tell me if your oC client went offline properly?

I'll work on a fix for you.
@danimo ^^ FYI

**Comment by guruz** [comment]
@unclejamal3000 
Could you create a new log file with the latest build which I added more debug logging and a small logic change.
http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.4903-nightly20150327-setup.exe

If that still does not work (it works for me on OS X) we need to look into the Qt Windows proxy lookup code again..

**Comment by unclejamal3000** [comment]
I made a test with build 4903.
Seems to work now, but the client needed 10min after disconnection of the VPN client to reset the network connection.

See log:
https://gist.github.com/unclejamal3000/4c9fbbe3261123a8f467

**Comment by guruz** [comment]
@danimo why would it so long report "Setting QNAM proxy to be system proxy "3://172.28.12.5:8080"" ?

**Comment by unclejamal3000** [comment]
I didn't recognize this large delay, to restore the connection, in the last days. So maybe the root cause was not in the client but in the environment.

**Comment by guruz** [comment]
Thanks!
