### ISSUE TITLE
Owncloud Client 1.7.1 Crashing

### ISSUE THREAD

**Issue by pyutaros** [owncloud/client#2697]
I apologize if this has already been reported.  I searched and found no results.

### Expected behaviour
Owncloud should start and sync.

### Actual behaviour
Owncloud starts, icon turns gray, icon displays an exclamation point, then owncloud crashes and creates a crash report.  Relaunching will produce the same results minus the crash report.  Works fine on other Ubuntu 14.04 PC's connecting to the same server and running the same client version.

### Steps to reproduce
1a) Login to computer, any user profile.
1b) Launch application

### Server configuration
Operating system:
Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-43-generic x86_64)

Web server: 
Apache 2.4.7

Database:
mysql  Ver 15.1 Distrib 5.5.40-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

PHP version:
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies

ownCloud version:
ownCloud 7.0.4 (stable)

Storage backend:
ext4

### Client configuration
Client version:
1.7.1

Operating system:
Ubuntu 14.04 LTS (Runs okay from other client workstations running the same OS.)

OS language:
English

Installation path of client:
Default

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.5/troubleshooting.html#client-logfile )
<script src="https://gist.github.com/pyutaros/be9803b0df0fc08b6484.js"></script>

2. Web server ACCESS log (no relevant entries in error log):
107.10.35.53 - "" [13/Jan/2015:19:12:41 -0500] "GET /owncloud/status.php HTTP/1.1" 200 2782 "-" "Mozilla/5.0 (Linux) mirall/1.7.1"
107.10.35.53 - pyutaros [13/Jan/2015:19:12:42 -0500] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1362 "-" "Mozilla/5.0 (Linux) mirall/1.7.1"
107.10.35.53 - pyutaros [13/Jan/2015:19:12:45 -0500] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1322 "-" "Mozilla/5.0 (Linux) mirall/1.7.1"

3. ownCloud log (data/owncloud.log):
No entries during the relevant timeframe.

**Comment by danimo** [comment]
Please provide the client output from `owncloud --logwindow -` (paste on `gist.github.com`).

**Comment by pyutaros** [comment]
Isn't that the same as owncloud --logfile?  If so, I already did.

**Comment by pyutaros** [comment]
Hmm.  I don't know why this didn't get included originally.  Sorry.

https://gist.github.com/be9803b0df0fc08b6484.git

**Comment by danimo** [comment]
Something seems to be odd with your sqlite version:

`01-13 18:52:56:343 0x82f22c8 Sqlite prepare statement error: "" in "PRAGMA quick_check;" `

Any idea @dragotin?

@pyutaros What is the output of `dpkg -l libsqlite3-0`?  It returns `3.8.2-1ubuntu2` in the version column for me in 14.04.

**Comment by pyutaros** [comment]
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  libsqlite3-0:i 3.8.2-1ubunt i386         SQLite 3 shared library

**Comment by guruz** [comment]
@ckamm Since 40f44c23890dd5fca86928b0f7c0d3f4218b7fc4 is from you, do you have any insight on this?
Why would ```sqlite3_prepare_v2``` return ```!= SQLITE_OK``` ?

**Comment by ckamm** [comment]
@guruz No insights.

But what's clear is that SqlQuery::prepare() fails to properly fill _error based on the return code. That function should either somehow use SQLITE_DO or manually fill _error. Fixing that will give us a more useful error message.

**Comment by ckamm** [comment]
@pyutaros Could you try this again with a recent nightly to see what kind of error the SQL prepare statement actually returns?

**Comment by pyutaros** [comment]
Sure.  Can someone please provide a link to instructions for installing the
nightly build?

**Comment by ckamm** [comment]
@pyutaros Here: http://download.owncloud.com/desktop/daily/

**Comment by lmaestro** [comment]
@pyutaros Have you tested the nightly build?

**Comment by pyutaros** [comment]
Sorry, I have been very busy.  i will test it tonight.

**Comment by pyutaros** [comment]
Here is the result of <code>owncloud --logfile owncloud.txt</code>.

https://gist.github.com/pyutaros/4cad04069722ce5e7147/download

Thanks for your efforts and help.

**Comment by guruz** [comment]
```
...
02-03 22:13:26:120 0x9c1a2c8 csync_exclude_load: Adding entry: ~*.tmp
02-03 22:13:26:120 0x9c1a2c8 ==== added user defined ignore list to csync: "/home/user/.local/share/data/ownCloud/sync-exclude.lst" 
02-03 22:13:26:126 0x9c1a2c8 Sqlite prepare statement error: "unable to open database file" in "PRAGMA quick_check;" 
02-03 22:13:26:126 0x9c1a2c8 quick_check returned failure: "" 
02-03 22:13:26:126 0x9c1a2c8 Consistency check failed, removing broken db "/home/folder2/folder1/.csync_journal.db" 
02-03 22:13:26:126 0x9c1a2c8 sqlite3 version "3.8.2" 
02-03 22:13:26:127 0x9c1a2c8 sqlite3 journal_mode= "wal" 
02-03 22:13:26:251 0x9c1a2c8 Sqlite exec statement error: 14 "unable to open database file" in "CREATE TABLE IF NOT EXISTS metadata(phash INTEGER(8),pathlen INTEGER,path VARCHAR(4096),inode INTEGER,uid INTEGER,gid INTEGER,mode INTEGER,modtime INTEGER(8),type INTEGER,md5 VARCHAR(32),PRIMARY KEY(phash));" 
02-03 22:13:26:251 0x9c1a2c8 SQL Error "Create table metadata" "unable to open database file" 
02-03 22:13:26:251 0x9c1a2c8 ASSERT: "!"SQL ERROR"" in file /usr/src/packages/BUILD/src/libsync/syncjournaldb.cpp, line 104
```

**Comment by guruz** [comment]
Is there anything fishy with ```/home/folder2/folder1/.csync_journal.db``` ? permissions? mount? etc..

**Comment by pyutaros** [comment]
I will check the permissions and report them back here.

**Comment by pyutaros** [comment]
<code>user1@Kryptonic:/home/folder2$ ls -l
total 80
drwxrwsr-x    8 user1 group1   4096 Feb  4 00:27 folder1
drwxrwsr-x   10 user1 group2  4096 Dec 15 07:40 folder2
drwxrwsr-x 1687 user1 group1  69632 Feb  6 13:23 music
drwxrwsr-x    2 user1 group1   4096 Jul 31  2014 Shared

user1@Kryptonic:/home/folder2/folder1$ ls -al
total 72
drwxrwsr-x 8 user1 group1  4096 Feb  4 00:27 .
drwxr-xr-x 6 user1 group1  4096 Nov 27 13:45 ..
drwxrwsr-x 2 user1 group1  4096 Nov 28 11:40 Cards
-rw-r--r-- 1 user1 group1  1024 Feb  4 00:27 .csync_journal.db
-rw-r--r-- 1 user2   group1 32768 Feb  6 15:20 .csync_journal.db-shm
-rw-r--r-- 1 user1 group1     0 Feb  4 00:27 .csync_journal.db-wal
drwxrwsr-x 2 user1 group1  4096 Nov 28 11:41 Desktop
drwxrwsr-x 2 user1 group1  4096 Nov 28 11:41 Minecraft
drwxrwsr-x 4 user1 group1  4096 May  4  2014 OHVA
-rw-rw-r-- 1 user1 group1  1271 Nov 29 01:50 .owncloudsync.log
drwxrwsr-x 2 user1 group1  4096 Nov 28 11:42 pixmaps
drwxrwsr-x 6 user1 group1  4096 Nov 28 11:42 Speed Dial 2</code>

Folder1 is a shared directory owned by a group that I am a member of.  I also happen to be in this case the folder owner.  The file permissions are 0644, though the folder carries 2775 permissions.  I changed permissions on all files in these directories to 2770 (which suits my permissions scheme) and the error is gone and files are syncing.  No doubt this is due to me fiddling with the program in ways it is not intended to work.  Thanks to all of you for your help.

**Comment by ckamm** [comment]
@pyutaros Thanks for checking. It looks like the problem was that the db temporary .csync_journal.db-shm was only writable by user2 while the rest belonged to user1.

**Comment by pyutaros** [comment]
Yep.  Thanks again for your help.
