### ISSUE TITLE
Synching fails - SSL Handshake failed

### ISSUE THREAD

**Issue by SPQRInc** [owncloud/client#2698]
Hi,
since today I'm getting the following error-message:

14:05     9448132965_fehlermeldung_mail_02.jpg                            Downloads      Could not connect to server: Connection refused          
14:05     9448132965_fehlermeldung_mail.jpg                               Downloads      SSL handshake failed: Connection reset by peer          
14:03     9448132965_fehlermeldung_mail.jpg                               Downloads      Could not read status line: connection timed out          

What can I do here? https://cloud.example.com is reachable without any problems.

**Comment by guruz** [comment]
We can't help you if you provide no information. Please see https://github.com/owncloud/client/blob/master/CONTRIBUTING.md

**Comment by guruz** [comment]
Please retry with 1.8rc1
