### ISSUE TITLE
[Windows] [OS X] Ship 1.8 with Qt 5.4

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2699]
We want this so our code can activate the new bandwidth limiting code (https://github.com/owncloud/client/issues/1849) automatically.

Semi-related: https://github.com/owncloud/client/issues/2558

@danimo Says:
```
for mac: yes
for windows: I have almost all packages ready, but they need merging, and webkit is not yet behaving
```

**Comment by guruz** [comment]
FYI regarding the OS X deploy script
```
<fregl> guruz: libqtaccessiblewidgets.dylib was removed in 5.4 (merged into qtgui)
```

**Comment by guruz** [comment]
Related https://github.com/owncloud/client/issues/2140

**Comment by dragotin** [comment]
Its gold because we need it for the new bandwidth limiting.

**Comment by guruz** [comment]
Note: Also retry https://github.com/owncloud/client/issues/2648 with 5.4

**Comment by danimo** [comment]
Status: master OS X builds now can be done with Qt 5.4

**Comment by danimo** [comment]
Windows builds also build with Qt 5.4 now. Closing.

**Comment by guruz** [comment]
@danimo So all builds that use 1.8 are now by default using Qt 5.4 (and for Mac the linked SSL) ?

**Comment by danimo** [comment]
Yes
