### ISSUE TITLE
[Windows] Fix sqlite3 for sync folders on FAT(?) permissions

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2701]
We need to find out if WAL (that was activated for 1.7.0) is a problem and we'd need to detect FAT(?) or if there is another way.

Related:
* https://github.com/owncloud/client/issues/2693
* https://github.com/owncloud/client/issues/2673

"On Windows, Microsoft's documentation says that locking may not work under FAT filesystems if you are not running the Share.exe daemon. " https://www.sqlite.org/faq.html
A question is if setting the lock mode helps: https://www.sqlite.org/draft/pragma.html#pragma_locking_mode https://www.sqlite.org/draft/wal.html#noshm (according to someone on IRC in #sqlite no..)

I propose that for now when creating a new Journal, we'll use ```GetVolumeInformationW``` (http://msdn.microsoft.com/en-us/library/aa364993(v=vs.85).aspx) and check ```lpFileSystemNameBuffer``` if it contains ```ntfs```. If not, then we don't enable WAL.

**Comment by ogoffart** [comment]
I could not reproduce the problem with master and a FAT partition.

**Comment by guruz** [comment]
Are you using Windows 8.1 like the other reporters?

**Comment by guruz** [comment]
@ogoffart The reporter in https://github.com/owncloud/client/issues/2693 mentions ```exFAT```..

**Comment by ckamm** [comment]
Here are also two reports of issues with exFAT and sqlite:
http://stackoverflow.com/questions/13798826/android-sqlite-crash-with-exfat-filesystem
http://forum.xojo.com/13737-sqlite-table-on-exfat-file-system/0

**Comment by ckamm** [comment]
I tried with an exfat-formatted USB stick from linux and that worked fine. I will attempt the same from Windows later.

**Comment by ckamm** [comment]
I could not reproduce the issue when syncing an owncloud folder to an exFAT-formatted USB stick in a Windows 7 guest.

**Comment by ckamm** [comment]
@danimo and me just tried with exfat and Windows 8.1 and couldn't reproduce it either. Any other ideas?

**Comment by guruz** [comment]
@dragotin Shall we have Windows specific code that adds a special message when this error happens that we don't support exfat?
Alternatively we can add a message in the "Add folder" wizard.

@rudo54 and @andrewbridge had this issue, so at least for them it existed..

**Comment by ckamm** [comment]
@guruz I'm not convinced it's related to the WAL file, look at @andrewbridge's log in #2693. Maybe the DB really is corrupt - or there's a bug in quick_check on exFAT somehow?

**Comment by guruz** [comment]
Yes, I'm not convinced anymore either. It's just that it happened with 1.7.0
1) updating the sqlite3 version
2) when enabling WAL

@dragotin close issue?

**Comment by dragotin** [comment]
yes, I think we can close this one, as the investigations haven't lead to something. And we also remove the corrupted file so it gets recreated so I think its done.

**Comment by guruz** [comment]
(Although I remember one of the reporters mentioned having recreated the DB, tried a new sync dir etc..odd)

**Comment by soluxima-erik** [comment]
I know this is closed, but I could not find a solution in any of the posts. I have the following setup:

- Windows 10 (64)
- Latest OC client 2.1.0 (build 5683)
- Mounted exFAT drive as target (encrypted volume by DiskCryptor) 

But I get the same result as what started this thread, seams to be a locking issue.
![oc_sync_error](https://cloud.githubusercontent.com/assets/5697214/12036672/16eb680e-ae83-11e5-8889-dd7399065117.PNG)
Was the consensus just to not use exFAT target drives?

**Comment by guruz** [comment]
Have you also tried to contact DiskCryptor about this?

Does removing the ```.csync_journal*``` files change anything?

**Comment by soluxima-erik** [comment]
@guruz 
Yes, they said its standard exFAT partition with all permissions open. I tried with a standard exFAT partition (not spawned from DiskCryptor) and the same thing happens.
No, removing any of the files fixes nothing. A new file is made by the client with the same error.

For the record, selecting a directory in the standard NTFS partition works fine, the client works flawlessly as it should. Its just the exFAT partitions providing the spanner in the works.

**Comment by guruz** [comment]
@soluxima-erik Could you run with a logfile (see the manual on how to do that) and see if you get the log message https://github.com/owncloud/client/commit/5cdf448693193bb837f411d7554b1a28e71103ae#diff-0b6f105ffd4493a278873f32b7c170c1R116

FYI @ckamm

**Comment by AMDG2** [comment]
I get the same problem today. Here is my setup : 

- Windows 10 (32)
- Owncloud (2.1.0, build 5683, git rev. https://github.com/owncloud/client/commit/c0c9fb365da7ddc8b7367e5ffd6052db7806c75e)
- Installed on SD-Card
- Sync folder on SD-Card
- SD-Card format: exFat

Here is my log: https://owncloud.feildel.fr/index.php/s/I8ieqEK2jiAckWH

**Comment by guruz** [comment]
```
01-15 18:42:37:456 0x49a7cc0 OCC::SqlQuery::prepare: Sqlite prepare statement error: "disk I/O error" in "PRAGMA quick_check;"
01-15 18:42:37:456 0x49a7cc0 OCC::SqlDatabase::checkDb: quick_check returned failure: ""
01-15 18:42:37:456 0x49a7cc0 OCC::SqlDatabase::openOrCreateReadWrite: Consistency check failed, removing broken db "D:/baudouin/owncloud/.csync_journal.db"
01-15 18:42:37:471 0x49a7cc0 OCC::SyncJournalDb::checkConnect: sqlite3 version "3.9.1"
01-15 18:42:37:471 0x49a7cc0 OCC::SqlQuery::prepare: Sqlite prepare statement error: "disk I/O error" in "PRAGMA journal_mode=WAL;"
```

@AMDG2 Does it work when you set the ```OWNCLOUD_SQLITE_JOURNAL_MODE``` environment variable to ```DELETE``` when launching oC client?

**Comment by AMDG2** [comment]
Yes it works. I tried to delete csync journal from Owncloud sync folder before but it doesn't work. Was it an error ?

May I help to fix the issue in Owncloud Client ?

**Comment by guruz** [comment]
@AMDG2 We'll give you a new build next week to try. Something is wrong with the FAT detection.
Please stay tuned :)

**Comment by ckamm** [comment]
@guruz This might be a bug in the file system detection function:
```
QString drive = path.left(3);
if (! drive.endsWith(":\\"))
    return QString();
```
In the log, the path is "D:/..." so `/` vs `\`.

**Comment by ckamm** [comment]
@AMDG2 A potential fix is in `2.1` (it didn't make it into beta1). Could you try a new nightly from http://download.owncloud.com/desktop/daily/ tomorrow?

**Comment by AMDG2** [comment]
I will try it in the evening (GMT+2) or tomorrow. 
I let you know :) 

Le 19 janvier 2016 10:03:16 GMT+01:00, ckamm <notifications@github.com> a écrit :
>@AMDG2 A potential fix is in `2.1` (it didn't make it into beta1).
>Could you try a new nightly from
>http://download.owncloud.com/desktop/daily/ tomorrow?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/client/issues/2701#issuecomment-172781147

-- 
Envoyé de mon appareil Android avec K-9 Mail. Veuillez excuser ma brièveté.

**Comment by XianPalin** [comment]
I upgraded to ownCloud 8.2.0 server a while back and this issue started happening - I was no longer able to sync due to the csync error.  Tonight I downloaded ownCloud-2.1.1.5785-nightly20160120-setup.exe.  After uninstall of my previous version and an installation of the new version, ownCloud popped up and started syncing immediately. I am unfortunately getting 'Service Unavailable'...'Operation Canceled' errors upon sync, which may be an unrelated issue.

**Comment by guruz** [comment]
@XianPalin Sounds unrelated. Please try 8.2.1, if issue persists create a new issue.

**Comment by guruz** [comment]
@AMDG2 http://download.owncloud.com/desktop/daily/ownCloud-2.1.1.5785-nightly20160120-setup.exe @soluxima-erik

**Comment by Dianafg76** [comment]
@AMDG2 Could you try this: ownCloud-2.1.1.3067-nightly20160125.pkg, please?

**Comment by AMDG2** [comment]
@guruz this version was working. I didn't have time to try your version @Dianafg76

**Comment by guruz** [comment]
:+1:
