### ISSUE TITLE
Proper failure message on misspelled config option

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/client#2702]
It looks just weird if something like this happens:

```
$ owncloud --confdif /tmp/owncloud-config
SocketApi:  server started, listening at  "/run/user/1000/ownCloud/socket" 
==== added system ignore list to socketapi: "/etc/ownCloud/sync-exclude.lst" 
==== added user defined ignore list to csync: "/home/mjob/.local/share/data/ownCloud/sync-exclude.lst" 
setting remote poll timer interval to 30000 msec 
ownCloud version 1.7.1
File synchronisation desktop utility.

Options:
  -h --help            : show this help screen.
  --logwindow          : open a window to show log output.
  --logfile <filename> : write log output to file <filename>.
  --logdir <name>      : write each sync log output in a new file
                         in directory <name>.
  --logexpire <hours>  : removes logs older than <hours> hours.
                         (to be used with --logdir)
  --logflush           : flush the log file after every write.
  --confdir <dirname>  : Use the given configuration directory.

For more information, see http://www.owncloud.org

SocketApi:  dtor 
```

It looks like it started just fine, but it was a weird feeling. It took me 10 minutes and looking for some icons in my task bar, checking directory permissions, looking through running processes before I recognized the typo in the command. Is it possible to have a little message `confdif is not a valid config option`? That would help a lot. ;)

**Comment by guruz** [comment]
Thanks,

**Comment by Dianafg76** [comment]
@guruz could you tell me the steps to reproduce this issue, please?

**Comment by Dianafg76** [comment]
@guruz I tested this issue and I found this:
.- In MAC: it is working fine. If I write path / to / owncloud --lofile, I have this message "Unrecognized option --lofile". And  If I write path / to / owncloud --logfile, I have this message "log file is not specified " prove " ownCloud --help 'for more information"
Desktop v  ownCloud-2.0.0.2538-nightly20150715.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

.- In WIN: If I write path / to / owncloud --lofile, anything happens. And  If I write path / to / owncloud --logfile, anything happens
Desktop v ownCloud-2.0.0.5273-nightly20150715-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by guruz** [comment]
What do you mean anything happens?

**Comment by Dianafg76** [comment]
In Windows, If I write path / to / owncloud --lofile, anything happens. And If I write path / to / owncloud --logfile, anything happens. I don't have the same message with in MAC

**Comment by guruz** [comment]
Thanks, this is working as expected.
On Windows it does not show anything since we have ```owncloud``` (vs ```owncloudcmd```) not compiled as console app so Windows eats the output.
