### ISSUE TITLE
On windows when owncloud directory is set to a network share, "Open Folder" menu entry doesn't work

### ISSUE THREAD

**Issue by remixtj** [owncloud/client#2703]
In my windows environment folder redirection is used. The redirected folder is on a network share. The owncloud directory is inside this network share. When the user make right click on the icon and clics on the entry **Open Folder 'OC SYNC'** nothing happens.
I started the client with logging window and logging file enable and i've seen  this error entries:
> 01-14 15:29:13:683 0x6d51db8 owncloudgui.cpp:394 opening local url  "\\cifs.company.com\home\redirect\user\Application Data\OC SYNC/"
> 01-14 15:29:13:698 0x6d51db8 qwindowsservices.cpp:67 ShellExecute '%5C%5Ccifs.company.com%5Chome%5Credirect%5Cuser%5CApplication Data%5COC SYNC%5C' failed (error 2).

There is cleary an error on encoding the url. I explored the code around owncloudgui.cpp at line 394. I put inside some debug and found that the problem is a function call at [line 396](https://github.com/owncloud/client/blob/master/src/gui/owncloudgui.cpp#L396). While debugging i've seen this:

> 01-14 16:08:02:737 0x6721dc0 owncloudgui.cpp:394 opening local url  "\\cifs.company.com\home\redirect\user\Application Data\OC SYNC/"
> 01-14 16:08:02:737 0x6721dc0 owncloudgui.cpp:400  f->path()  "\\cifs.company.com\home\redirect\user\Application Data\OC SYNC/"
> 01-14 16:08:02:737 0x6721dc0 owncloudgui.cpp:403  url.setUrl  "\\cifs.company.com\home\redirect\user\Application Data\OC SYNC\"
> 01-14 16:08:02:737 0x6721dc0 owncloudgui.cpp:410 url ->   QUrl( "%5C%5Ccifs.company.com%5Chome%5Credirect%5Cuser%5CApplication Data%5COC SYNC%5C" ) 
> 01-14 16:08:02:752 0x6721dc0 qwindowsservices.cpp:67 ShellExecute '%5C%5Ccifs.company.com%5Chome%5Credirect%5Cuser%5CApplication Data%5COC SYNC%5C' failed (error 2).

This confirms my hypotesis.

I wrote a patch for this. I'll make a PR for merging.

**Comment by danimo** [comment]
Fixed by merging referenced issue to master.

**Comment by dragotin** [comment]
Reopen for @lmaestro

**Comment by lmaestro** [comment]
@remixtj Which version are you using? 1.7.1? And what windows do you have? I use a local folder which is on a network share without problems. Do you do something more? Which mean " folder redirection is used"?

**Comment by danimo** [comment]
@lmaestro I think he's referring to accessing a network share directly via the UNC namespace, i.e. `\\servername\sharename\folder`

**Comment by lmaestro** [comment]
For me it works in 1.7.1 on Windows 8

**Comment by remixtj** [comment]
@lmaestro both 1.7.0 and 1.7.1. We're using Windows 7. Our owncloud directories are on \\servername\share\personal_folder\owncloud like said by @danimo  

It's quite strange that you say it works on 1.7.1, since there's no code difference between the .0 and .1:
https://github.com/owncloud/client/blob/9cbe8bf5779abad0c2b5669d32d2adda504eb24b/src/mirall/owncloudgui.cpp#L403
https://github.com/owncloud/client/blob/17a4299f74f4db7fc82f4b90f1e501c81288697b/src/mirall/owncloudgui.cpp#L402

Logs that i reported when opening the issue confirmed that the issue really exists.

**Comment by remixtj** [comment]
I found that my actual configuration in %LOCALAPPDATA%\ownCloud\folders there is a file containing this config:

[IC4Sync]
localPath=\\\\server\\home\\redirect\\user\\Application Data\\IC4Sync
targetPath=/
backend=owncloud
connection=ownCloud
blackList=@Invalid()


How is your config file? contains the same escaping that is present on mine?

**Comment by lmaestro** [comment]
Ok, sorry I was using "Map network drive" instead of only config the path so now I can reproduce in 1.7.1.
And I tested that it is fixed in the latest version (1.8.0-nightly20150116 build 4590) . Thanks for the help.
