### ISSUE TITLE
[Mac] Updater does not work

### ISSUE THREAD

**Issue by danimo** [owncloud/client#2705]
We need to find out what's wrong and establish a way to diagnose Sparkle problems more reliably.

**Comment by craigpg** [comment]
@danimo, how broken is the Mac updater?

**Comment by guruz** [comment]
@lmaestro When trying to reproduce please also make sure to delete ```$HOME/Library/Preferences/com.owncloud.desktopclient.plist``` before installing the old version.
(this file might store the time of the last update check)

**Comment by lmaestro** [comment]
@dragotin @danimo Can you provide me 1.6.4 and 1.7.0 versions ?

**Comment by dragotin** [comment]
@lmaestro
```
http://download.owncloud.com/desktop/stable/ownCloud-1.7.0.1490.pkg
```
and 
```
http://download.owncloud.com/desktop/stable/ownCloud-1.6.4.1195.dmg
```

**Comment by lmaestro** [comment]
There no alert message to update. Logfile https://gist.github.com/lmaestro/cb5f499120fa753577e9

**Comment by guruz** [comment]
Your log contains another peculiar thing:
```
02-03 09:30:51:561 0x104a777a0 ownsql.cpp:146 Sqlite prepare statement error: "" in "SELECT inode, mode, modtime, type, md5, fileid, remotePerm FROM metadata WHERE phash=?1"
02-03 09:30:51:561 0x104a777a0 socketapi.cpp:428 Unable to prepare the query statement: 1
```

**Comment by guruz** [comment]
The log actually HAS updater related messages. 
When I run any version myself, the update check is coming:
```
02-05 15:15:54:914 sparkleupdater_mac.mm:107 virtual void Mirall::SparkleUpdater::backgroundCheckForUpdate() launching background check 
2015-02-05 15:15:54.954 owncloud[66140:507] Sparkle: ===== owncloud.app =====
02-05 15:15:54:955 sparkleupdater_mac.mm:34 -[DelegateObject updaterMayCheckForUpdates:] may check: YES
```

It seems to try to open https://updates.owncloud.com/client/?version=1.8.0.0&platform=macos&oem=ownCloud&sparkle=true which returns "version in wrong format"

**Comment by danimo** [comment]
Outch! my bad! I missed something in the updater meta data. It should work now.

**Comment by lmaestro** [comment]
Fixed.
