### ISSUE TITLE
owncloud-hoster disadvice owncloud-client

### ISSUE THREAD

**Issue by muetze-online** [owncloud/client#2712]
Hi,

I don't know, if this is the right address for my question. Feel free to delete this topic and tell me an address for my question.

I use the owncloud-client from version 1.4 until now and I see a big growing of its stability and overall usability. 
owncube.com as an owncloud-hoster disadvises its users to use the own cloud-client: https://owncube.com/syncapps-de.php. How can a provider, which earns his money with a product from this community place this on his homepage. Is the client so bad? I cannot think, that other clients work better together with the owncloud-server? Does owncube.com work together with the development-team of owncloud?

muetze

**Comment by LukasReschke** [comment]
>  Is the client so bad? 

No.

> I cannot think, that other clients work better together with the owncloud-server? Does owncube.com work together with the development-team of owncloud?

Also here: No, ownCube does neither work together with the development team nor is an officially supported supporter. 

@jospoortvliet We discussed this a while back ago and had some discussion via mail about this. – What is the status?

\cc @karlitschek FYI

**Comment by karlitschek** [comment]
As discussed owncube should be removed from the provider page. They clearly have no interest in working with the ownCloud community in a productive way.

**Comment by danimo** [comment]
That has already happend, so I'll close this issue.

**Comment by strugee** [comment]
> That has already happend, so I'll close this issue.

I still see it listed on owncloud.org/providers.

**Comment by danimo** [comment]
My bad, missed it. Fixed now.

**Comment by jospoortvliet** [comment]
They removed the negative note from their site so they will be re-added to owncloud.org/providers.

Not saying they are any nicer - there was quite some yelling about this. But they are entitled to their opinion...
