### ISSUE TITLE
external storage with several users never sync

### ISSUE THREAD

**Issue by kaneo-gmbh** [owncloud/client#2714]
Hello,

we encounterd a problem while using the external storage feature of owncloud.

We have a smb-folder configured with passing the ownCloud user/password for smb authentication. The folder is accessible read/write for several users.

If one user is adding or modifying a file, the file will sync as desired from the users desktop-client or the users web-interface to the server. This step works reliably.

Unfortunately none of the other users that have access to this smb-folder will ever receive this file while using the desktop client. The desktop client seems never to notice, that files have been changed on the external storage. When the user logs on to the web-interface, the desktop client suddenly notices the changes and starts to sync.

Our workaround is, to log on in parallel to the web-interface.

**Comment by danimo** [comment]
This seems to be a server problem then, @DeepDiver1975 ?

**Comment by DeepDiver1975** [comment]
> This seems to be a server problem then, @DeepDiver1975 ?

indeed a server issue .... let's move this over

**Comment by kaneo-gmbh** [comment]
For me this seems not to be really clear. It seems that the Web-UI is triggering to read / discover content of external storage by default. Mybe the desktop-clinet just needs to "send" the same command / request to the server as the Web UI does.

But I don't know any detail about the internals. It would be very nice to get a short explanation, could you help with that?

Thanks in advance, Andreas

**Comment by DeepDiver1975** [comment]
@kaneo-gmbh the situation needs to be analyzed first in details - but we had similar situations in the past. To me this looks like that the web ui is triggering a rescan on the folders an detects the changes - where as connections via the WebDAV interface don't do this.
