### ISSUE TITLE
Missing monochrome icon

### ISSUE THREAD

**Issue by stonerl** [owncloud/client#2715]
I'm running the client, v. 1.7.1 Build 1655, on OSX 10.10. In the settings I chose the monochrome icons, but one tray icon still remains colored.

![icon](https://cloud.githubusercontent.com/assets/2091312/5801232/061624a0-9fe9-11e4-8ea0-d10d99dc9abb.png)

**Comment by rullzer** [comment]
This seems the same as #2593 which will be fixed once pull request #2709 is merged.
