### ISSUE TITLE
[windows] When creating explorer favorite use more specific windows functions

### ISSUE THREAD

**Issue by remixtj** [owncloud/client#2719]
I'm experiencing problems with the creation of the favourite on Windows 7, using folder redirection. I made some research for the problem and found out that client tries to create a link on the wrong place. My "Links" directory is on a cifs share: \\server\homes\username\Links. This wrong behavior is caused by the function setupFavLink_private in [utility_win.cpp](https://github.com/owncloud/client/blob/master/src/libsync/utility_win.cpp)

At the moment in function _setupFavLink_private_ at  [line 24](https://github.com/owncloud/client/blob/master/src/libsync/utility_win.cpp#L24) the function

```
    SHGetSpecialFolderPath(0, path, CSIDL_PROFILE, FALSE);
```

is used.
[MSDN documentation](http://msdn.microsoft.com/en-us/library/windows/desktop/bb762204%28v=vs.85%29.aspx) says that [ShGetFolderPath](http://msdn.microsoft.com/en-us/library/windows/desktop/bb762181%28v=vs.85%29.aspx) should be used. But says also that ShGetFolderPath is deprecated. A note states:

> Note  As of Windows Vista, this function is merely a wrapper for SHGetKnownFolderPath. The CSIDL value is translated to its associated KNOWNFOLDERID and then SHGetKnownFolderPath is called. 
> New applications should use the known folder system rather than the older CSIDL system, which is supported only for backward compatibility.

Please note that SHGetKnownFolder is a function available only on Vista and later. But, you can also note that also favourites on explorer are available since that windows release.

I made a test and tried to print the path value that is returned by the function call:

```
    SHGetKnownFolderPath(FOLDERID_Links, 0, NULL, path);
```

and i get (correctly) the value of _\\server\homes\username\Links_.
I printed also the output of 

```
    SHGetSpecialFolderPath(0, path, CSIDL_PROFILE, FALSE);
```

and i got _C:\Users\username\_, that is correctly my profile home, but the path where the function will create the link is _C:\Users\username\Links_, that is wrong.

**Comment by remixtj** [comment]
@danimo what do you think about this new patch? better?

**Comment by jturcotte** [comment]
Reopening since we had to revert this in https://github.com/owncloud/client/pull/3562

**Comment by hodyroff** [comment]
Is this current in master? What exactly is the issue from a UX perspective?

**Comment by remixtj** [comment]
Hi,
this has been reverted. I had no possibility to have contributor terms signed, but since my company is a customer of owncloud, this patch is for sure interesting. 

The UX impact is that the user on windows, if using a Group Policy that sets its Links directory to a path different to %USERPROFILE%, the link to ownCloud directory on Explorer's Favourites is not available.

**Comment by guruz** [comment]
@remixtj Any news from your side?

**Comment by remixtj** [comment]
@guruz got a mail 3 months ago from @hodyroff and i replied saying that i can sign personally CLA if is not an issue from owncloud side since is a my own contribution, even if done during worktime.

If is ok, i can sign and then submit the patch again.

**Comment by hodyroff** [comment]
Works, thank you!

**Comment by remixtj** [comment]
@guruz PR is now available, with signed CLA

**Comment by SamuAlfageme** [comment]
Just tested current master and `ownCloud` shorcut is back in the Favorites 🎉 looks like we can cross one of https://github.com/owncloud/client/issues/455#issuecomment-266735590 items.

@remixtj would there be a way to set the folder icon to `owncloud.exe`'s?. I've read about `Desktop.ini` files but, doesn't seem elegant enough: 

```
[.ShellClassInfo]
IconFile=%ProgramFiles%\ownCloud\owncloud.exe
IconIndex=0
```

I'll repeat the test on W8.1 & 10 and close here if everything continues smooth there!

**Comment by remixtj** [comment]
Hello,

as far as i know, through QT is not possible to set the link icon, since that qt functions is cross platform and makes symlinks in linux and .lnk files in Windows.

I'll take a look if some other options are available

**Comment by SamuAlfageme** [comment]
👍
