### ISSUE TITLE
Miss the Chinese text font in version 1.7.1 on Mac.

### ISSUE THREAD

**Issue by WayneSan** [owncloud/client#2721]
After update to version 1.7.1, the Chinese characters cannot be shown as expected. (The locale is `zh_TW`.)

![screenshot](https://cloud.githubusercontent.com/assets/457527/5811316/b752df0a-a08f-11e4-9611-20a8faeaa875.png)

**Comment by guruz** [comment]
Thanks :)

Please subscribe to https://github.com/owncloud/client/issues/2640

Closing as dup.

**Comment by guruz** [comment]
This is OS X 10.10?
