### ISSUE TITLE
Adding the same account on repeat

### ISSUE THREAD

**Issue by offlinehoster** [owncloud/client#2722]
Everytime, i would like to use my owncloud client on my android phone, i have to re-enter all the account credentials, because the client don't save the credentials.

Android: 4.4.2 
Device Samsung S4
ownCloud Client version: 1.6.2

This happens after an client update too.

**Comment by danimo** [comment]
This is the desktop client bug tracker. Please file in https://github.com/owncloud/android/issues. Thanks!
