### ISSUE TITLE
Show file Thumbnail in Share dialog

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#2726]
The share dialog would look even more cool if it had a thumbnail of the file to share. It can be retrieved from the server using this api:
https://github.com/owncloud/core/blob/84bb4cc2e9013eb3db8d7114a0e6eb132a723adf/apps/files/appinfo/routes.php#L17-L20
by doing a GET on 
index.php/apps/files/api/v1/thumbnail/{x}/{y}/{filename}

**Comment by rullzer** [comment]
Ah that was the API I was looking for! I'll try to pick this up shortly.

**Comment by rullzer** [comment]
Initial commit is available. More checking needs to be done but it is working pretty well for now. But no rush since it only makes sense to create a pull request when owncloud 8 is out.

**Comment by DeepDiver1975** [comment]
@dragotin please get in touch with me to find proper solutions before using some crazy api existing somewhere . we are currently navigating into an api nightmare  because a hell of different apis are used - this will soon remain unmaintainable for us. THX

**Comment by DeepDiver1975** [comment]
> The share dialog would look even more cool if it had a thumbnail of the file to share. It can be retrieved from the server using this api:

The file is existing on the client as well - right?
Is there any possibility to generate the thumbnail local on the client?

Getting the thumbnail from the server will put additional load to the server.

THX

**Comment by DeepDiver1975** [comment]
In case you really want to grab it from the server we don't need no capabilites api.

In case thumbnails are disabled the api route simply will not exist and a request to it will return 404

**Comment by dragotin** [comment]
There is no easy way of creating thumbnails on the client at least for Linux, also no *easy* one on Win. And for the sake of consistency, it would be better to get it from server.

However, no rush here, that is very low priority IMO.

**Comment by rullzer** [comment]
@DeepDiver1975 yes that is true and it is how it is implented currently (well actually I check for 200). I'll create a PR for the client later tonight (it is pretty straight forward). We could just leave it like that for now and use the capabilities later when (if) that gets sorted out.

**Comment by DeepDiver1975** [comment]
> There is no easy way of creating thumbnails on the client at least for Linux, also no easy one on Win. And for the sake of consistency, it would be better to get it from server.

okay - understood - THX.

**Comment by DeepDiver1975** [comment]
> @DeepDiver1975 yes that is true and it is how it is implented currently (well actually I check for 200). I'll create a PR for the client later tonight (it is pretty straight forward). We could just leave it like that for now and use the capabilities later when (if) that gets sorted out.

@rullzer awesome - this is the way to got from my understanding - THX a lot

Please be aware that I need to review the server api - index.php/apps/files/api/v1/thumbnail/{x}/{y}/{filename}

I'm not truly happy with it ...

**Comment by rullzer** [comment]
See #2805 for a patch to retrieve the thumbnails.

**Comment by guruz** [comment]
Can this be closed or is there still work to be done?

thanks for the patch btw @rullzer

**Comment by rullzer** [comment]
@guruz If i'm not mistaken the patch was removed again since the API was/is not yet 100% stable..

**Comment by rullzer** [comment]
Merged in #3426
