### ISSUE TITLE
Translation correction

### ISSUE THREAD

**Issue by conradoqg** [owncloud/client#2727]
File mirall_pt_BR.ts, line 201: Change <translation>Descobrir &apos;%&apos;1&apos;</translation> to <translation>Descobrir &apos;%1&apos;</translation>.

Thank you

**Comment by ogoffart** [comment]
Thank you for your report.
Please go on https://www.transifex.com/projects/p/owncloud/ to update the translation.

**Comment by danimo** [comment]
I went ahead and fixed the string in transifex, thanks! That said, we always appreciate new contributors to the translations.
