### ISSUE TITLE
[OS X 10.9, 10.10] No notifications

### ISSUE THREAD

**Issue by webmatrixxxl** [owncloud/client#2728]
In december 2014 a was able to install ownCloud client v1.7.1 and notifications wear ok but from now on on every mac I install ownCloud 1.7.1 there no notifications. In fact in OS X notification center there is no ownCloud App. I reinstall it several time with no luck.

**Comment by guruz** [comment]
@lmaestro Can you confirm this?

**Comment by webmatrixxxl** [comment]
Yes. Reinstalled client v1.7.1 several times and there was no ownCloud in Settings->Notification Center. Yesterday I tried to run ownCloud-1.6.4.1195.dmg and ownCloud app now is avedible in Notification Center and notifications were working. But no notifications after running client 1.7.1 again.

**Comment by webmatrixxxl** [comment]
Today we have new mac in office so we installed client 1.7.1 and are no Notifications

**Comment by lmaestro** [comment]
Yes, I confirm that on yosemite with 1.7.1 or 1.8.0.

**Comment by guruz** [comment]
The problem is actually happening quite early in ```Folder::bubbleUpSyncResult()```. The ```createGuiLog``` is never(?) called with a ```count > 0```.

@ogoffart Can you review my commit? I don't understand why before it only checked for DOWN.. or on the other hand why it checks for DOWN but the ```_direction``` is not that?

**Comment by guruz** [comment]
@ogoffart OK hold on, so my patch is wrong because the notifications should not come for UP?

**Comment by guruz** [comment]
Everything works as expected, no need to fix anything..

@webmatrixxxl Possibly you have the notifications disabled in the client settings or OS X itself.

**Comment by danimo** [comment]
We need to be compatible with 10.7, that's why the official builds lack the feature. Investigating...

**Comment by webmatrixxxl** [comment]
@guruz  No my notifications in client are Enabled and OS X dont show owncloud client app in notification center as I said... even if I reinstall it several times.

**Comment by guruz** [comment]
@webmatrixxxl Do you want to test a 1.8 nightly build?
(note to have backups, nighltly builds didn't go through full QA)

http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.1997-nightly20150208.pkg

**Comment by webmatrixxxl** [comment]
ok... I think notifications are back now on 1.8

After notifications were back I downgrade to 1.7.1 again several times and notifications gone.

**Comment by lmaestro** [comment]
Notifications works fine in version 1.8.0-nightly20150209 (build 2001) .
@webmatrixxxl  Notifications are not working in 1.7.1 sorry.
