### ISSUE TITLE
QThread, QtConcurrent and QFileSystemWatcher -> Windows Multi-Core problems

### ISSUE THREAD

**Issue by OliverKohlDSc** [owncloud/client#2735]
Dear colleagues,

I've now watched various versions of the QT GUI application on various platforms regarding multi-threading and multi-core (parallelism).

The client is capable on Mac OS X (latest version) to use all the available cores when watching a folder or syncing. On Windows (7 and 8.1) the opposite is the fact.

The GUI application is only capable to use one CPU/Core on Windows, all the others are not used.

Application and CPU usage:

![untitled](https://cloud.githubusercontent.com/assets/8104064/5852327/2d93f614-a215-11e4-9161-49b1c85243c2.png)

Thanks

Oliver

**Comment by ogoffart** [comment]
Thanks for your bug report.

What is exactly the problem you are having?
The bottleneck is mostly IO and not so much CPU, so e don't think there would be so much gain in making things using more threads. Especially if it complicates the code.

Contributions are welcome however.

**Comment by OliverKohlDSc** [comment]
@ogoffart 

There are two cases when the problem occurs:

1)
The error occurs if there are quite a lot of exclusion patterns ...
![capture](https://cloud.githubusercontent.com/assets/8104064/6967671/195b3e22-d961-11e4-8fd3-1191b9351687.PNG)
![capture2](https://cloud.githubusercontent.com/assets/8104064/6967690/3adedd10-d961-11e4-9530-89f6f532b3cd.PNG)

On the other hand the problem shows up if you just rebooted the machine and the client starts the discovery and tries to compare the sync status with the server status for each file.
![capture3](https://cloud.githubusercontent.com/assets/8104064/6967760/b660d010-d961-11e4-87a9-fd111cef97aa.PNG)

![cpu](https://cloud.githubusercontent.com/assets/8104064/6967639/ded7597a-d960-11e4-825d-e391cfad392b.PNG)

Beside that there's one interesting thing for me. Nearly all the other tables are completly unsed - just the metadata table is used (beside the one entry in the version table for the oc client version).

The client scans through every row - i.e. starts a full table scan. I don't have a lot of files - just about 120.000 and I plan to increase the number of files. Don't you think so too that it would be an option to create a hash per folder, per parent folder or root folder to see in a second that there's no file to be synced at the moment? Another option would be multi-threading.

What do you think?

Thanks a lot

Cheers

Oliver

**Comment by OliverKohlDSc** [comment]
Dear @danimo 
I've just seen that you actually include that hashes of the folders, but there must be something wrong because it doesn't seem to work in both mentioned cases. 

![folders](https://cloud.githubusercontent.com/assets/8104064/6967957/52823fe6-d963-11e4-8786-3505979ad583.PNG)

Thanks again

**Comment by ogoffart** [comment]
Thanks for the details.

I am however still going to close this bug because it is not usefull to have such kind of meta bug "optimize".

Optimizing the discovery phase is on our list of TODO, but being able to process files in parallel implies huges refactoring and rewriting  (which we are planing to do eventually)

The activity list is also going to be revamped sooner or later.

**Comment by OliverKohlDSc** [comment]
ok, thanks anyway.
