### ISSUE TITLE
[regression] Setup: Shibboleth requires reauth 

### ISSUE THREAD

**Issue by danimo** [owncloud/client#2739]
When testing with shib, I noticed that during the wizard run the shib browser window pops up a second time. This may be related to @ckamm 's refactoring. I know that we already fixed this once, so this is a regression. I don't recall the fix though.

@ckamm Could you test this with test1.owncloud.com/oc7-shib?

**Comment by ckamm** [comment]
@danimo I tried this with a clean confdir and 'Modify Account' but couldn't reproduce it. Could you try it yourself again?

**Comment by ckamm** [comment]
I think @ogoffart fixed it with b0dbb49ca84a42f701f75270334f3e1714de9074

**Comment by danimo** [comment]
Ok, thanks.

**Comment by ogoffart** [comment]
This is not fixed.

**Comment by lmaestro** [comment]
It is fixed in the latest version version 1.8.0-nightly20150205 (build 1984)
