### ISSUE TITLE
Client upload the whole folder again and again

### ISSUE THREAD

**Issue by flewor** [owncloud/client#2740]
The problem I am facing is very simple but very annoying : instead of uploading only the modified files, the client upload the whole folder back again.

This happened me already three times during the last two weeks. Just after the startup, or just after loggin. The total upload time take about 10 hours.

Can someone explain me what I do wrong or where is the problem?

The folder is composed of  about 2k files and is about 30 GB. The desktop client is installed on two PCs, one with Windows 8.1 and the other with Windows 7.

Is it possible that one client destroy the synchronisation journal?

**Comment by ogoffart** [comment]
Thanks for your bug report.
Please use the issue template https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

What is the version of your client?  On what file system is your owncloud sync directory? 

Do you have the log from the client? It should reveal why the client believe he files have changed.

**Comment by guruz** [comment]
@flewor Do you have any special storage configured on the server?

Closing until more info comes up.
