### ISSUE TITLE
Rename shared folder delete folder's files.

### ISSUE THREAD

**Issue by webmatrixxxl** [owncloud/client#2741]
Hi guys.

When I share folder with files with and then I rename folder after some time files in that folder are deleted from my disk locally.

ownCloud 7.4
client 1.7.1

**Comment by LukasReschke** [comment]
Thanks a lot for reporting issues back to us!

We need some more information to properly support you with your issue!

Can I ask you to follow our guidelines for submitting bugs as described here: https://github.com/owncloud/client/blob/master/CONTRIBUTING.md

Thanks a lot!

**Comment by guruz** [comment]
@webmatrixxxl do you have any more info? what did you rename the folder to? from what? do you use different OS for the clients?

**Comment by guruz** [comment]
Closing this for now, I think there was a server bug that was fixed meanwhile.

CC @icewind1991 @PVince81 See issue above.

**Comment by PVince81** [comment]
Could be https://github.com/owncloud/core/issues/13391 if the folder contains lots of files.
Or https://github.com/owncloud/core/issues/15340 if it's about renaming the shared folder back to its original name as recipient.
