### ISSUE TITLE
[Linux] Better support for HiDPI

### ISSUE THREAD

**Issue by Skatox** [owncloud/client#2744]
I've some visual problems using Owncloud on Linux with a HiDPI screen, left column is small, some texts overlap and the tray icon is so small. Would be great to make this app to adapt or mantain proportion when using it at high resolutions screen.

My workaround is to increase font size, but it looks ugly as you can see in attached screenshot. (check icon and left menu).

![hidpi](https://cloud.githubusercontent.com/assets/177008/5887528/a7885bca-a3a7-11e4-8ac5-712269f7e724.png)

**Comment by danimo** [comment]
We will need to migrate to Qt 5.4 to fix that, which the distros usually do not provide...

**Comment by Skatox** [comment]
Thanks for the quick reply, I'll wait then.

**Comment by guruz** [comment]
@Skatox try to compile yourself?

**Comment by Skatox** [comment]
So, should i compile using recommended QT version? If I just compile the
application, it doesn't change. Because it's how the interface (or
library) is programmed.

On 01/26/2015 04:59 AM, Markus Goetz wrote:
> @Skatox <https://github.com/Skatox> try to compile yourself?
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/2744#issuecomment-71433582>.
> 

-- 
Miguel Ángel Useche Castro
migueluseche@skatox.com
@skatox
Visita http://www.skatox.com/  Blog de Informática, Desarrollo Web,
Mozilla, Software Libre, Linux, Videojuegos y mas....

**Comment by benwaffle** [comment]
bump

![oc](https://cloud.githubusercontent.com/assets/1713819/6708437/9a9ff972-cd46-11e4-97bd-945c118f4120.png)

**Comment by danimo** [comment]
@benwaffle This is waiting for improvements in Qt, afaik Qt 5.5. In the meantime, please check if ```QT_DEVICE_PIXEL_RATIO=2 owncloud``` 
does anything for you

**Comment by benwaffle** [comment]
yup just did that

**Comment by danimo** [comment]
@benwaffle ok. Auto-detection is still in the works I guess.

**Comment by danimo** [comment]
Can you post a screenshot of how it looks with HIDPI?

**Comment by benwaffle** [comment]
![oc](https://cloud.githubusercontent.com/assets/1713819/6708613/4ccf4002-cd48-11e4-923f-d367f2e01e38.png)

**Comment by Skatox** [comment]
I've compiled owncloud using qt5 libraries and launching the application with `QT_DEVICE_PIXEL_RATIO=2` and it works normal under a HiDPI screen. This is issue can be closed.
