### ISSUE TITLE
Files with a + sign in the name are not synchronized by Windows Client

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/client#2747]
Originally reported by @scs-tech at https://github.com/owncloud/core/issues/13665

> This appears to be the same error as reported (and closed) with bug owncloud/core#4568
Problem does not appear to be fixed (or has come back).
>
> Steps to Reproduce:
1) Create a file "file+name.txt" on windows client
2) Create a file "file-name.txt" on windows client
3) Copy both files to the synced folder.
>
> Expected behavior:
Both files should sync to OC
>
> Actual behavior:
'File-name.txt' will sync fine, 'file+name.txt' will not sync.
Error in client activity log is:
Error Downloading Https://my.domain.com/remote.php/webdav/file+name.txt - server replied: Not Found
>
> Environment:
 Fresh install
 Server: Windows 2012 R2, IIS 8.5, OwnCloud 7.0.4, PHP 5.6.0, MySQL 
>
> Client: Windows 2012 R2, OwnCloud Client 1.7.1 (build 4382)

**Comment by danimo** [comment]
Invalid. Server bug. See bug in core.
