### ISSUE TITLE
Shiboleth regression allow to connect with a different account

### ISSUE THREAD

**Issue by ogoffart** [owncloud/client#2751]
If logged with shiboleth, sign out, then sign in again but enter a different username.

This should not be allowed but it seems to work now.

in ShibbolethCredentials::slotUserFetched we check that, but it seems that the _user is no longer saved.

**Comment by ckamm** [comment]
I can reproduce it and will take a look.

**Comment by ckamm** [comment]
@ogoffart Could you test master? I stopped being able to reproduce the issue but think I got two very likely causes. (using skip folder config and failing to fetch the shib user)

**Comment by lmaestro** [comment]
I am trying to test it but I can't log in with a shibboleth server . 
@ckamm  Can you have a look at the logs ? 
https://gist.github.com/lmaestro/1ee75696bf3da076a139

**Comment by ogoffart** [comment]
I tested it and it works.
