### ISSUE TITLE
ownCloud Client complains about missing system tray under Plasma 5.2

### ISSUE THREAD

**Issue by egriffith** [owncloud/client#2754]
Running Fedora 21 KDE x64, I upgraded from KDE 4.x series to Plasma 5.2 through dvratil's Copr. On login the ownCloud client (version 1.7.0) complains about not being able to load a systray and that if im running XFCE I should follow some instructions. It complains... and yet the ownCloud system tray icon gets created just fine, updates just fine, and is working perfectly. 

False positive on ownCloud's systray detection code? Or is this maybe related to Plasma 5 removing xembed support from the systray? I'd link to mgraesslin's blog on that note but it appears to be down right now.

**Comment by dragotin** [comment]
@danimo can you elaborate about the xembed thing? Thx.

**Comment by egriffith** [comment]
I was able to grab cached pages of the relevant blog posts from mgraesslin' blog. 

Where are my systray icons? http://webcache.googleusercontent.com/search?q=cache:yhMoaPHeQ8QJ:blog.martin-graesslin.com/blog/2014/06/where-are-my-systray-icons/+&cd=1&hl=en&ct=clnk&gl=us

Systray in Plasma Next: http://webcache.googleusercontent.com/search?q=cache:lM7DK5gwCHIJ:blog.martin-graesslin.com/blog/2014/03/system-tray-in-plasma-next/+&cd=2&hl=en&ct=clnk&gl=us

**Comment by ckamm** [comment]
Master would not show the dialog because of @ogoffart's 3169833cd78335d23d2b5f08d8a0ca852998e070 which shows the warning only on xfce. It still means that QSystemTrayIcon::isSystemTrayAvailable() returns false, which may be an issue.

**Comment by dragotin** [comment]
Hmm, reading through https://lists.fedoraproject.org/pipermail/devel/2014-March/196343.html it might be the case that Fedora added a patch to display the tray icon properly but forgot the part to fix the Qt lib to actually consider that patch in QSystemTrayIcon::isSystemTrayAvailable()? Just guessing....

Please report this upstream with Fedora! Thanks.

**Comment by jeppebundsgaard** [comment]
The problem also appears in Kubuntu 15.04 alpha (Plasma 5.2).
