### ISSUE TITLE
Shared folder are not sync if no modification

### ISSUE THREAD

**Issue by Watchwolf** [owncloud/client#2756]
Hello,

I have created an issue #2618 but the issue was closed without being fixed.

When you share a folder from account1 to account2 (Linux client), the shared folder is not sync if no modification is made in the folder after the shared is set up.

Client Linux version 1.7.1
Server Linux version 7.0

I wait more than 30 sec and I try to stop/restart the client. The client say that the sync is done but it did'nt sync the new share.

Then I create a file in the shared folder and delete it immediately, the last change time of the folder become a few seconds.

After a few seconds the client sync the folder automatically.

**Comment by guruz** [comment]
Can you retry with a new version of the server?

**Comment by guruz** [comment]
Can this be the same as https://github.com/owncloud/core/issues/13333 ?

**Comment by Watchwolf** [comment]
No, this is not the same as #13333.

I am going to test with the Linux server 7.0.4.

**Comment by Watchwolf** [comment]
ok, with the version 7.0.4 the problem is fixed.

Thank you.
