### ISSUE TITLE
Provide Client Command to Pause/Start Sync

### ISSUE THREAD

**Issue by fathomssen** [owncloud/client#2760]
### Problem Description

As the ownCloud desktop client currently is using up quite some battery on a laptop, I would like to be able to set the client to pause whilst being on battery and to start the client again when I connect the plug.

### Proposed Solution

There are at least two quite simple ways to achieve such a behaviour:

1. The ownCloud client will be enhanced to provide a command line command to pause the client (e.g. `owncloud pause`) and start it again (e.g. `owncloud start`). Then, the user can (at least in Linux and OSX) configure the power management tools to start the corresponding command (pause/start). This would be quite uncomfortable at least for unexperienced users, of course.
    * It might generelly be a good idea to provide such command line commands to enable users to script the ownCloud client's behaviour.

2. The ownCloud client will be enhanced to provide an option to pause whenever the computer is running on battery power. This is very comfortable, but would mean a quite big change to the desktop client as it had to detect the current plug connection state. Furthermore, this seems not to be desired as of issue #468.

**Comment by fathomssen** [comment]
A simple workaround for propsed sulution 1 could be to pause the ownCloud client process on battery power and resume it when plugged in again. This has the disadvantage of rendering the ownCloud client (icon) unusable for the time being paused.

For example, in Ubuntu 14.10, I have created a script `/etc/pm/power.d/owncloud` (`chmod 755`) with the following content:

```
ac_power()
{
  killall -CONT owncloud
}

battery_power()
{
  killall -STOP owncloud
}

case "$1" in
  false) ac_power ;;
  true) battery_power ;;
esac
```

Works for me and for now - but any other solution would be better of course.

**Comment by danimo** [comment]
Folding this one into #1971.
