### ISSUE TITLE
[OS 10.10.1] Can't install ownCloud client 1.7.1

### ISSUE THREAD

**Issue by AdrienGiboire** [owncloud/client#2762]
This will be tricky cause I can't get to find any intel about what can be the source of the issue.

All I get is this:
![screen shot 2015-02-01 at 23 35 54](https://cloud.githubusercontent.com/assets/394860/5994221/2a4294a8-aa6b-11e4-8cff-900ca4cf036a.png)

And the console actually doesn't seem to provide more details.

My privacy settings are good as well.
![screen shot 2015-02-01 at 23 37 05](https://cloud.githubusercontent.com/assets/394860/5994222/3f853212-aa6b-11e4-9fe9-db076e4091c8.png)

Any hints?

**Comment by lmaestro** [comment]
I am using OS X 10.10.1 and I don't have any problem to install 1.7.1 from https://owncloud.org/install/ 
Can you check your "Console " maybe there are any error message?

**Comment by guruz** [comment]
Could you run ```Console.app``` and check if there are related messages?

**Comment by AdrienGiboire** [comment]
One thing more I can bring is that it fails at "Validating packages" step.

**Comment by guruz** [comment]
That's a mystery.
Are you willing to try the not-released-yet daily builds of 1.8 ?
(Make sure to have backups.. they should be safe but didn't go through full QA)

http://download.owncloud.com/desktop/daily/ (the .pkg file)

Although I don't see a reason why this one should work differently, it is the same installer

**Comment by AdrienGiboire** [comment]
You were right, it doesn't work differently :(

**Comment by guruz** [comment]
If you run ``` /sbin/md5``` in ```Terminal.app``` on a ```.pkg``` you download, what do you get?
(Also tell me the .pkg name).
Why would it not be able to validate the package..

**Comment by AdrienGiboire** [comment]
MD5 (ownCloud-1.7.1.1655.pkg) = 759f69e0572499209e12e975212979b8
MD5 (ownCloud-1.8.0.1970-nightly20150204.pkg) = 16b58d5d0f72c92a42abc7577a49bbc6

I have no clue of what could be wrong. I've never seen that before...

**Comment by AdrienGiboire** [comment]
For some reason, I gave it another shot today and it worked…
