### ISSUE TITLE
Error message when I try to use a server where the encryption is enabled but my account is not initialized

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2763]
### Expected behavior
As it happens on windows I can upload/ download files until I initialize my account with the encryption app. 

### Actual behavior
I am having an error in a server where the encryption is enabled but my account is not initialized because I am using it before the encryption was enabled. 
After the encryption was enable, I have this problem when I try to upload something.
![screen shot 2015-02-02 at 9 04 41 am](https://cloud.githubusercontent.com/assets/4689430/5997369/d9a7df9e-aaba-11e4-8a8b-a71042d8a545.png)

I don't have this problem when I upload files from server, they download on the desktop. correctly

### Steps to reproduce
1. Start to sync an account 
2. Enable Encryption app
3. Try to upload files from the local folder

### Client configuration
Version 1.8.0-nightly20150202(build 1963)

Operating system: OS X 10.10.1 and Windows 8.1

###Logs

https://gist.github.com/lmaestro/5166024ef607d73d199f

**Comment by lmaestro** [comment]
CC/ @guruz @dragotin

**Comment by dragotin** [comment]
@schiesbn can you help? Thanks

**Comment by lmaestro** [comment]
fyi, this may be related to https://github.com/owncloud/core/issues/13727

**Comment by ogoffart** [comment]
This looks like a server issue. Closing the client one.
@schiesbn  : maybe you want to open a server issue for this.
