### ISSUE TITLE
Allow Share link from the Desktop

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2764]
In order to divide https://github.com/owncloud/client/issues/1444

As a user I want to be able to click on a file, inside the local folder, and select share by link. I should be able to :

- Set a password 
- Set expiry date

**Comment by lmaestro** [comment]
The share link dialog should define the button: 

Windows:

![screen shot 2015-02-02 at 12 39 04 pm](https://cloud.githubusercontent.com/assets/4689430/6000049/21b1b5bc-aad9-11e4-9016-09181761616e.png)

OS X:
![screen shot 2015-02-02 at 12 41 06 pm](https://cloud.githubusercontent.com/assets/4689430/6000051/252775ba-aad9-11e4-93b3-2f2a0096de1b.png)

**Comment by lmaestro** [comment]
When you click on a file the option to show the share link dialog, is different 
- Windows: share
- OS X : Share with ownCloud

 From my pov it should shown "Share ownCloud Link"

**Comment by guruz** [comment]
@Azelphur @rullzer @dragotin What is the button in the dialog supposed to say/do?

Regarding the title of the share menu:
@jancborchardt What's your opinion for the title of the share-item in the right-click-menu in Explorer/Finder?
Regarding the Windows title: that's @ogoffart @danimo who need to change that, I thought @ogoffart did already.

**Comment by rullzer** [comment]
Ah yes the button. That is still on my todo list. It is supposed to copy the url. @Azelphur added it and i think it makes sense. It just does not display anything. If I have time I'll look into that later today.

**Comment by rullzer** [comment]
Ah it seems that we need to add it as a theme icon for Windows and OS X: http://doc.qt.io/qt-5/qicon.html#fromTheme

For now just adding the text: Copy url. Would probably do the trick

**Comment by lmaestro** [comment]
I agree with the idea of the button to copy the link.

**Comment by rullzer** [comment]
I just created PR #2771 
The copy button text is now set. And the button is actually connected to a slot.

**Comment by lmaestro** [comment]
We should have into account he state of the file, if it shows red/yellow/ or even blue overlay icon, you can't share it by link.  
At least at present we are not having this into account

**Comment by lmaestro** [comment]
In order to be clearer the issues found related to this feature, I will list them here and update its status (close when fixed):

- [ ] Password enforced, not possible to share link. https://github.com/owncloud/client/issues/2774

**Comment by dragotin** [comment]
#2775, #2800 and #2815 were postponed to 1.8.1, thus I mark them "checked" above.

**Comment by dragotin** [comment]
#2822 is also for milestone 1.8.1, checking above.

**Comment by dragotin** [comment]
A couple of others moved to 1.8.1 milestone, so all checked here, hence I close this one.
