### ISSUE TITLE
Present file conflicts more prominently in the GUI

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#2766]
Currently the Activity page lists conflict files as they are created. This information is easily overlooked, when many files change.
Assumption: There are users who ignore conflict files, as they do not know what they mean.

Suggested improvement:
- Create an own conflicts page, that lists current file conflicts, and gives hints how to resolve them. 
- Add documentation about conflicts, describe actions needed before sync is possible.
- The icon should not show the green checkmark, as long as a conflict exists somewhere.

@cdamken @dragotin

**Comment by cdamken** [comment]
@dragotin @jnweiger @danimo  Probably an overlay Icon who shows a "Disconnection" will help

**Comment by ckamm** [comment]
As @SamuAlfageme pointed out in #5273: Currently messages about new conflict files are only shown in the "Not synced" tab of the client until the folder is synced the next time. An overview of all pending conflicts should be permanently visible somewhere in the user interface!

**Comment by SamuAlfageme** [comment]
Happening in https://github.com/owncloud/client/pull/5894 🎉 

@guruz switch to 2.4 milestone?

**Comment by SamuAlfageme** [comment]
Can be closed by now. Present in 2.4alpha1 and tested with different conflict scenarios, including https://github.com/owncloud/client/pull/6038. Great UX improv!
