### ISSUE TITLE
Nightly update broken on Ubuntu 14.10

### ISSUE THREAD

**Issue by ornearius** [owncloud/client#2769]
Auto-update failed yesterday. When trying to see what is happening I get

sudo apt-get -f install owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
owncloud-client is already the newest version.
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 owncloud-client : Depends: libowncloudsync0 (= 1.8.0~nightly20150202-0) but 1.8.0~nightly20150201-0 is to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).

**Comment by dragotin** [comment]
You tried to downgrade the package from 1.8.0~nightly20150201-0 to 1.8.0~nightly20150202-0 for some reason. Maybe the package cache was not up to date.

I just verified the nightlies on Mint and it wokred ok. I'll close this one.

**Comment by ornearius** [comment]
Hmm, I didn't do anything. This is what came down on the update.
