### ISSUE TITLE
Error messages when file is open

### ISSUE THREAD

**Issue by pgspm** [owncloud/client#2770]
On windows 7 clients;
After upgrade to sync client 1.7.1 (from 1.6.3) users get a lot of sync error messages in system tray. When opening the client gui it looks like the attached image.
![image001](https://cloud.githubusercontent.com/assets/10829283/6019437/bf9a933a-aba0-11e4-961e-14961c53685f.png)

What the message say (in Norwegian) is that the sync process does not have permission to access the file because it's in use be another process. Well, the file is open, and that surely is a reason why it cannot be synced. But is there really any need to show error for that reason? Sync works fine when the file is closed. When this kind of message shows up very often, they get ignored. Then when there really is an error, that message will probably also get ignored.

I'd think a behavior where open files are ignored silently in the sync process will be better. And maybe have a check that if a file is open and cannot be synced for several days, then it's time to throw a warning.

My impression is that this happens to .xls and .xlsx files only, and I suspect it happens soon after the file is autosaved.

**Comment by danimo** [comment]
Please give http://download.owncloud.com/desktop/daily/owncloud-1.8.0.4672-nightly20150203-setup.exe a shot. We've been working on addressing these issues there.

**Comment by pgspm** [comment]
Thank you.
One user have used this for almost a full day. No problems to report so far.

**Comment by guruz** [comment]
Thanks! Closing
