### ISSUE TITLE
sync problem with custom share_folder

### ISSUE THREAD

**Issue by centredecalcul** [owncloud/client#2772]
Hi,

Syncing newly shared files don't work properly when use the share_folder parameter.
I can see the shared file in "Shared with you" section and with Webdav access, but nothing in my desktop.
It works without share_folder configuration, but I want to use it.

My config.php:
  'share_folder' => '/Partages',

Desktop client : 1.7.1 (build 4382)
Server : 7.0.4 (Centos 7, PHP 5.4.16, Apache 2.4.6)

User B use desktop client, with "sync all dirs" configuration
User B create or modify a file : sync success
User A share a file with user B : no synchronization :-1: 
User B modify a file in share_folder : sync success for the modified file only, not the user A file :-1: 
User B reboot : no synchronization :-1: 
User B create a file or a folder in share_folder (in desktop or web interface) : sync success : the user A file appear in the desktop

No error in log server nor desktop.

Regards,
Antoine

**Comment by avoine** [comment]
I suspect this bug is a duplicate of this one: https://github.com/owncloud/core/issues/13333

**Comment by centredecalcul** [comment]
Maybe yes.
This ticket is more like that one : https://github.com/owncloud/core/issues/13868
I think this is easily reproducible.
No matter, I'll try this: https://github.com/owncloud/core/issues/13333#issuecomment-71850509

**Comment by centredecalcul** [comment]
I don't have problem when I share a folder (test https://github.com/owncloud/core/issues/13868) but I have problem when I share a single file.

u1 share a single file with u2
u2 can see the new file in web interface, cadaver, etc
u2 "share_folder" Etag is not updated
u2 desktop client don't synchronise the new file

cadaver u2 : 
dav:/remote.php/webdav/> ls Partages
Listing collection `/remote.php/webdav/Partages/': succeeded.
Coll:   a                                      0  févr. 18 14:26
        simplefile1.txt                        1  févr. 18 14:28

dav:/remote.php/webdav/> propget Partages
Fetching properties for `Partages':
http://owncloud.org/ns id = 00478591ocb72c158477
http://owncloud.org/ns permissions = RDNVCK
DAV: getetag = "54e49321e32ef"
DAV: getlastmodified = Wed, 18 Feb 2015 12:44:15 GMT
DAV: resourcetype = <DAV:collection></DAV:collection>
DAV: quota-used-bytes = 0
DAV: quota-available-bytes = 10737418240

dav:/remote.php/webdav/> ls Partages 
Listing collection `/remote.php/webdav/Partages/': succeeded.
Coll:   a                                      0  févr. 18 14:26
        simplefile1.txt                        1  févr. 18 14:28
        single_file_share.txt                  7  févr. 18 14:35

dav:/remote.php/webdav/> propget Partages
Fetching properties for `Partages':
http://owncloud.org/ns id = 00478591ocb72c158477
http://owncloud.org/ns permissions = RDNVCK
DAV: getetag = "54e49321e32ef"
DAV: getlastmodified = Wed, 18 Feb 2015 12:44:15 GMT
DAV: resourcetype = <DAV:collection></DAV:collection>
DAV: quota-used-bytes = 0
DAV: quota-available-bytes = 10737418240

**Comment by PVince81** [comment]
@avoine @centredecalcul please tell me the full path of your shared file/folder that doesn't sync.

It seems that if it's on the first level:
- /shared: will sync fine
- /level1/shared: will sync fine
- /level1/level2/shared: will not detect changes
- /level1/level2/.../shared: will not detect changes

If your shared file/folder was deeper than level1 then please move over to https://github.com/owncloud/core/issues/14596#issuecomment-77397483

**Comment by centredecalcul** [comment]
My shared files are on the first level.

And my share folder is on the first level (config.php):
'share_folder' => '/Partages',

**Comment by centredecalcul** [comment]
Same problem with Owncloud 8.0.2 : etag of the "recipient" share_folder is not updated after sharing a file with this recipient.
However etag of the share_folder is updated when this file is modified after the file has been shared, and sync works at this time.

**Comment by centredecalcul** [comment]
Solved
