### ISSUE TITLE
Resetting to 'Discovering'

### ISSUE THREAD

**Issue by maxmitch** [owncloud/client#2773]
Hello,

I am having a problem where when syncing using the 1.7.0 version of the app, it suddenly falls back to 'Discovering'. Which takes a long time to discover all the directories!! And then it works perfectly. And this keeps happening the whole time at irregular intervals (estimate every 5-10 mins) ?

### Expected behaviour
It should stream sync uninterrupted 

### Actual behaviour
it suddenly falls back to 'Discovering' new directories

### Steps to reproduce
1. Open up owncloud desktop app
2. Run sync.

### Server configuration
Operating system: RASPBIAN

Web server: Apache2

Database: MYSQL

PHP version: Version 5.4.36-0+deb7u3

ownCloud version: 7.0.4

Storage backend: External Hard Drive

### Client configuration
Client version: 1.7.0

Operating system: OSX Yosemite

OS language: English (UK)

Installation path of client: /media/usbhdd

**Comment by danimo** [comment]
Hi, please read https://github.com/owncloud/client/blob/master/CONTRIBUTING.md and fill in the template mentioned there to help us gathering the required data to look into your issue.

**Comment by ogoffart** [comment]
1.7 does a full sync every 5 minutes.

The version 1.8 will do a full sync less often, as we have more trust in the file system watcher.

Anyway, discovering should ot take a too long time. How may files and folder do you have?  What operationg system?

**Comment by maxmitch** [comment]
Oh that makes sense!! I thought it was an error! I am just doing a sync of all my photos (90GB) I am also quite interested in optimising the speed of owncloud and my raspberry pi server!
