### ISSUE TITLE
When you enable the option of "Enforce password protection", you can't share by link from the desktop 

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2774]
### Expected behavior
You can share by link using password protection 

### Actual behavior
You can't share by link 

![captura de pantalla 2015-02-04 a las 9 02 03 am](https://cloud.githubusercontent.com/assets/4689430/6037632/20c6d64a-ac56-11e4-9005-98eef82de1d3.png)

### Steps to reproduce
1.  Enable the option  "Enforce password protection"  from the admin side
2. Try to share by link form the desktop 

### Client configuration
Version 1.8.0-nightly20150204(build 1971)

Operating system: OS X 10.10.1

**Comment by danimo** [comment]
Most likely a server issue. @schiesbn ?

**Comment by rullzer** [comment]
Ah yes I tought of this as well. However I did not yet have time to look into it.
The issue now is that we have no way of knowing if the server requires this. And we probably won't untill https://github.com/owncloud/core/pull/13692 is merged.

**Comment by rperezb** [comment]
cc @MTRichards realted to https://github.com/owncloud/ios/issues/283

**Comment by davivel** [comment]
We found the next condition in ownCloud server 7.0.4; the command to create a share 

```curl https://<domain>/ocs/v1.php/apps/files_sharing/api/v1/shares -u <user>:<pass> -X POST --data "path=<filepath>&shareType=3" ``` 

results in a response with error code 403 and message ```"You need to provide a password to create a public link"``` when ** the Sharing API is disabled** in the server. This is the response expected when password is enforced in the server side (not passed in the curl command), and makes both conditions undistinguishable.

In OC version 8.0 this problem does not exist. I don't know if the fix will be included in OC 7.0.5. @schiesbn , @PVince81 , is this familiar for any of you?

**Comment by dragotin** [comment]
I added some comments to https://github.com/owncloud/core/issues/13673 what the capabilities API for the sharing should contain. Based on that we can further refine our GUI.

**Comment by davivel** [comment]
Please, forget my previous comment. Seems this specific problem is already fixed in 7.0.4.2. Thanks,

**Comment by lmaestro** [comment]
Now the dialog requiere the password but the link doesn't appear although I introduce the password 

![screen shot 2015-02-09 at 1 51 22 pm](https://cloud.githubusercontent.com/assets/4689430/6106585/f465328e-b062-11e4-9198-0aebd3f8076f.png)

**Comment by MTRichards** [comment]
@carlaschroder We should have a release note that public links with required passwords will not work in 8.0.

**Comment by rullzer** [comment]
@lmaestro did you press return? Here it all seems to work.

**Comment by lmaestro** [comment]
@rullzer yes, it is needed for that reason I have created this issue https://github.com/owncloud/client/issues/2812
So it works in version 1.8.0-nightly build (2001)
