### ISSUE TITLE
Setting permissions to 16 (OCS_PERMISSIONS_SHARE) causes a sync error

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/client#2779]
(Starting with client  - not sure if this is ultimately a server issue.  I have log files for each step and will email them to @danimo )

### Steps to reproduce

1. Install owncloud 
2. create user1 and user2
3. Install owncloud client on a different system
4. Create a local .txt file, edit it to put in some content, and sync the file to the server

/usr/bin/owncloudcmd  --trust /jrm/smashbox/results/test_shareFile/sharer/ owncloud://user1:<pw>@x.x.x.x/owncloud/remote.php/webdav/

5. run a curl command to share the file with user 2, with only share permissions (I do not get this error when using "ALL" permissions)

curl -u <un>:<pw> --data "path=somefile.txt&shareType=0&shareWith=user2&permissions=16" http://<un>:<pw>@x.x.x.x/owncloud/ocs/v1.php/apps/files_sharing/api/v1/shares

6. user 2 Syncs

/usr/bin/owncloudcmd --trust /root/jrm/smashbox/results/test_shareFile/shareeOne/ owncloud://user2:<pw>@x.x.x.x/owncloud/remote.php/webdav/

7. User 2 edits the file locally and makes a change
8. User 2 syncs again

/usr/bin/owncloudcmd --trust /root/jrm/smashbox/results/test_shareFile/shareeOne/ owncloud://user2:<pw>@x.x.x.x/owncloud/remote.php/webdav/

The sync fails with an internal server error

9. User 2 syncs for a third time.  This time the the sync works.

### Expected behaviour

The file should be synced the first time after editing the file.

### Actual behaviour

The file fails to sync the first time after editing the file.

Server log file:

```

{"reqId":"a0d319d3ba7b57067f372f809c9c7481","remoteAddr":"x.x.x.x","app":"PHP","message":"fclose() expects parameter 1 to be resource, boolean given at \/var\/www\/html\/owncloud\/lib\/private\/files\/view.php#527","level":3,"time":"2015-02-04T19:46:15+00:00"}
{"reqId":"a0d319d3ba7b57067f372f809c9c7481","remoteAddr":"x.x.x.x","app":"webdav","message":"\\OC\\Files\\Filesystem::rename() failed","level":3,"time":"2015-02-04T19:46:15+00:00"}
{"reqId":"a0d319d3ba7b57067f372f809c9c7481","remoteAddr":"x.x.x.x","app":"webdav","message":"Exception: {\"Message\":\"Could not rename part file to final file\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(888): OC_Connector_Sabre_File->put(Resource id #527)\\n#1 [internal function]: Sabre\\\\DAV\\\\Server->httpPut('somefile.txt')\\n#2 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(474): call_user_func(Array, 'somefile.txt')\\n#3 \\\/var\\\/www\\\/html\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/Sabre\\\/DAV\\\/Server.php(214): Sabre\\\\DAV\\\\Server->invokeMethod('PUT', 'somefile.txt')\\n#4 \\\/var\\\/www\\\/html\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#5 \\\/var\\\/www\\\/html\\\/owncloud\\\/remote.php(54): require_once('\\\/var\\\/www\\\/html\\\/o...')\\n#6 {main}\",\"File\":\"\\\/var\\\/www\\\/html\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":142}","level":4,"time":"2015-02-04T19:46:15+00:00"}



```

### Server Host info:

Ubuntu 14.04
PHP 5.5.9
mysql

### Server configuration

ownCloud Enterprise Edition 8.0 beta 2 (daily) Build:2015-01-30T04:20:37+00:00 24fc1c751ac1521ef02540bbf6d4d8fefc393b39

### Client Configuration

owncloudcmd version 1.7.1

**Comment by jnfrmarks** [comment]
Just as an FYI, I ran the test a second time setting the permissions to 17 (
OCS_PERMISSION_READ  |  OCS_PERMISSION_SHARE) and got the same results.

See https://github.com/owncloud/core/issues/13867#issuecomment-72921474

**Comment by ckamm** [comment]
Sounds like a server bug. Sanitized server log messages:

```
fclose() expects parameter 1 to be resource, boolean given at /var/www/html/owncloud/lib/private/files/view.php#527

OCFilesFilesystem::rename() failed

Exception: {"Message":"Could not rename part file to final file","Code":0,"Trace":"#0
/var/www/html/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(888): OC_Connector_Sabre_File->put(Resource id #527)
n#1 [internal function]: SabreDAVServer->httpPut('somefile.txt')
n#2 /var/www/html/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(474): call_user_func(Array, 'somefile.txt')
n#3 /var/www/html/owncloud/3rdparty/sabre/dav/lib/Sabre/DAV/Server.php(214): SabreDAVServer->invokeMethod('PUT', 'somefile.txt')
n#4 /var/www/html/owncloud/apps/files/appinfo/remote.php(61): SabreDAVServer->exec()
n#5 /var/www/html/owncloud/remote.php(54): require_once('/var/www/html/o...')
n#6 {main}",
"File":"/var/www/html/owncloud/lib/private/connector/sabre/file.php","Line":142}","level":4,"time":"2015-02-04T19:46:15+00:00"}
```

**Comment by dragotin** [comment]
@PVince81 please

**Comment by PVince81** [comment]
Are you guys also setting 17 ? (READ + SHARE)

SHARE alone isn't enough, one needs to explicitly pass the "READ" permission, or else... here be dragons.

In general the API should either set READ automatically or throw 400 Bad request if it's missing. (CC @schiesbn)

**Comment by ogoffart** [comment]
Same error as in https://github.com/owncloud/client/issues/2234

**Comment by PVince81** [comment]
Are you guys passing 16 (SHARE alone) or 17 (READ + SHARE) ?
Please confirm.

**Comment by PVince81** [comment]
If it's about passing 16 (SHARE alone) it was fixed on master: https://github.com/owncloud/core/pull/14570
