### ISSUE TITLE
The build number is not shown in the linux packages 

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2781]
### Expected behavior
The build number is shown

### Actual behavior
The build number and the date are not shown as it happens in windows and os x
![linux](https://cloud.githubusercontent.com/assets/4689430/6058087/4f5955fe-ad24-11e4-940f-10ec26d72906.png)

### Steps to reproduce
1. Launch the app
2. Click on "General" tab

### Client configuration
Version 1.8.0

Operating system: ubuntu 14.04

**Comment by lmaestro** [comment]
Now I can the Git revision commit but the build is not shown but maybe it is not necessary. 
@dragotin What do you think?
![screen shot 2015-02-10 at 1 33 10 pm](https://cloud.githubusercontent.com/assets/4689430/6127289/868e45ee-b129-11e4-847f-41a8d1c41240.png)

**Comment by dragotin** [comment]
There is no build number on Linux. That is fine.
