### ISSUE TITLE
[Windows] Special characters in URL, no sync

### ISSUE THREAD

**Issue by Valdiralita** [owncloud/client#2782]
### Expected behaviour
The client can sync with the Server.

### Actual behaviour
I replaced the actual URL with something very similar.

My servers URL contains the special character 'ö'.
 I can connect to the server and log in with my account using the client. It says(translated): "Connected with special.charöurl.de as Valdiralita".
When it tries to sync it fails with: "Could not resolve hostname: "special.charöurl.de" The host is unknown."
The exact same thing happens when i try to connect to it using the escaped URL: "special.xn--charurl-d1a.de". It can connect to the server and log in but the URL gets replaced by "special.charöurl.de".

![Screenshot](https://cloud.githubusercontent.com/assets/1066165/6060761/ddfee71c-ad40-11e4-8ed9-0652f7714899.png)

### Steps to reproduce
1. Connect with the client to a server with a special character in the URL. Here: 'ö'
2. Authenticate with your username and password.
3. Click "Connect..."
4. See Error: "Host is unknown"

### Client configuration
Client version:
1.7.1 build 4382

Operating system:
Windows 7 x64 Professional and Ultimate

OS language:
German

Installation path of client:
"C:\Program Files (x86)\ownCloud"

### Logs

Client log:
https://gist.github.com/Valdiralita/7da5afd00cfd6b2a2796

**Comment by dragotin** [comment]
This is supposed to be fixed with the upcoming 1.8.0 client, please verify with pre release build:
http://download.owncloud.com/desktop/daily/owncloud-1.8.0.4688-nightly20150205-setup.exe

Keep in mind to have backups because this is not yet released. Thanks!

**Comment by Valdiralita** [comment]
Ok thanks, i can confirm this is fixed in the 1.8.0 nightly.
I couldn't find any closed issue though.
