### ISSUE TITLE
[qt5] Wrong tray icon image, same in folder list

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#2786]
Wrong tray icon image, same in folder list:
![ocqt5icon](https://cloud.githubusercontent.com/assets/277525/6070959/60805e50-ad91-11e4-8bce-d67b17b0f5bf.png)

I installed owncloud-client-qt5 on openSUSE Factory.
```
S | Name                     | Type    | Version   | Arch   | Repository          
--+--------------------------+---------+-----------+--------+---------------------
i | owncloud-client-qt5      | package | 1.7.1-1.2 | x86_64 | isv:ownCloud:desktop
i | owncloud-client-qt5-l10n | package | 1.7.1-1.2 | x86_64 | isv:ownCloud:desktop
```

I'm running Plasma 5.2.

Note: I observed the same issue when testing master (94e61c32056c470a68c773163d714b0003fddbe6)

**Comment by PVince81** [comment]
It is more a usability issue than just cosmetic: I usually have a glance at the systray icon to see whether it started syncing my last change and now all I see is that invalid icon :confused:

**Comment by guruz** [comment]
I saw this at @ogoffart 's installation too

**Comment by ogoffart** [comment]
I think that's because of https://bugs.kde.org/show_bug.cgi?id=342906

**Comment by dragotin** [comment]
I'll move that to the next milestone of the client to recheck.

**Comment by PVince81** [comment]
Note: I tried to put the SVG icons in the "scalable/apps" directory and renaming them, but it didn't solve the problem.

**Comment by ogoffart** [comment]
This is a plasma bug, and it should be tracked upstream:  https://bugs.kde.org/show_bug.cgi?id=342906

**Comment by PVince81** [comment]
I still wonder why there aren't more apps that have this issue.
Maybe there aren't enough Qt5 apps out there yet ? :smile:

**Comment by PVince81** [comment]
Ah, you fixed it upstream! Great job! Let's see when I get my hands on this.

**Comment by ogoffart** [comment]
KDE Frameworks 5.8.0 fixes it.

**Comment by PVince81** [comment]
I just upgraded to KDE 5.8.0 and indeed the issue is fixed, so happy to see the icon again :smile:
