### ISSUE TITLE
Sign our git tags with GPG

### ISSUE THREAD

**Issue by craigpg** [owncloud/client#2790]
For added security, we should sign our git tags using gpg: `git tag -u key-id -m "v1.8.0"`

To simplify verification, we should use a shared signing key (e.g. release-team@owncloud.com).

**Comment by danimo** [comment]
@craigpg I'd need access to the signing key (`key F6978A26: public key "ownCloud <info@owncloud.com>"`)

**Comment by craigpg** [comment]
@karlitschek, should we use an existing key or should we setup a new key to sign our tags?
