### ISSUE TITLE
"An error opening a directory happened" is shown when sync an account

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2794]
An strange error when I tried to sync an account 

![screen shot 2015-02-06 at 9 29 31 am](https://cloud.githubusercontent.com/assets/4689430/6104572/e539c9be-b04e-11e4-8a74-c56c29c07ada.png)

Logs : https://gist.githubusercontent.com/lmaestro/cfffe134bb71738f8954/raw/gistfile1.txt

Might be same as https://github.com/owncloud/client/issues/2795

**Comment by guruz** [comment]
@lmaestro Did you use the nightly from tonight? If you check the log, this is for the special character directory?

**Comment by lmaestro** [comment]
yes, it is the daily from tonight.

**Comment by guruz** [comment]
Did you try to recreate your sync folder and selective sync setup?

**Comment by guruz** [comment]
I create a folder ```+`´ç+`ç´ñññ``` (like @lmaestro ) in the webinterface and it syncs down fine. 
```
02-09 13:02:24:176 0x7f84cc807d40 syncengine.cpp:794 void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem &) "BB/+`´ç+`ç´ñññ" 4 ""
```

@lmaestro suspects it is related to https://github.com/owncloud/core/issues/13946

**Comment by lmaestro** [comment]
I recreate this folder again and it works fine. I think it depends on the server so I close this issue.
