### ISSUE TITLE
[1.8.x] Unnecessary DB queries when adding a new sync folder

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2796]
Although we know the DB has been newly created:

For local:
```
02-08 11:52:11:890 0x10eaf69f8 csync_walker: file: /Users/guruz/ownCloud/3rdparty/build-qtmacgoodies-Qt_desktop-Debug/.qmake.stash [inode=48364464 size=1307]
02-08 11:52:11:890 0x10eaf69f8 sqlite_profile: _SQL_ SELECT * FROM metadata WHERE phash=?1: 0
02-08 11:52:11:890 0x10eaf69f8 _csync_detect_update: Checking for rename based on inode # 48364464
02-08 11:52:11:890 0x10eaf69f8 sqlite_profile: _SQL_ SELECT * FROM metadata WHERE inode=?1: 0
02-08 11:52:11:890 0x10eaf69f8 _csync_detect_update: file: build-qtmacgoodies-Qt_desktop-Debug/.qmake.stash, instruction: INSTRUCTION_NEW <<=
```

For remote:
```
02-08 11:52:12:762 0x10eaf69f8 csync_walker: file: ownclouds:/xxx/remote.php/webdav/3rdparty/build-qtmacgoodies-Qt_desktop-Debug/.qmake.stash [file_id=0003219650db25ada54f3 size=1307]
02-08 11:52:12:762 0x10eaf69f8 sqlite_profile: _SQL_ SELECT * FROM metadata WHERE phash=?1: 0
02-08 11:52:12:762 0x10eaf69f8 sqlite_profile: _SQL_ SELECT * FROM metadata WHERE fileid=?1: 0
02-08 11:52:12:762 0x10eaf69f8 _csync_detect_update: file: build-qtmacgoodies-Qt_desktop-Debug/.qmake.stash, instruction: INSTRUCTION_NEW <<=
```

Although I don't know if this is in practice really a problem (maybe sqlite3 cached that the table is empty anyway?)
To test maybe one could benchmark by just removing the rename check.

**Comment by guruz** [comment]
Let's do this for 1.8.1, i have the suspicion it might cause discovery slowness.

**Comment by ckamm** [comment]
@guruz @dragotin I'll run a quick performance test of discovery with lots of small local files, with the rename check and without.

**Comment by ckamm** [comment]
For me, discovery of 200k files takes 21s with both queries and 20s if one is removed (linux). I don't think changing this is worth it.

**Comment by guruz** [comment]
What about removing both checks?
One check might still have something cache in memory or so which then applies to both checks?

**Comment by ckamm** [comment]
Good point! If I remove all csync_statedb calls it does indeed go down to 13s for discovery.

**Comment by dragotin** [comment]
hmm, which query is the one that only results in a one second win when removed?

**Comment by ckamm** [comment]
@dragotin In line 334, tmp = csync_statedb_get_stat_by_inode(ctx, fs->inode);. With the second try I commented out everything csync_statedb_*().

**Comment by ckamm** [comment]
In my test this patch speeds up the initial discovery for 200k files from 21s to 11s.

**Comment by guruz** [comment]
Works, thanks!
