### ISSUE TITLE
No such slot OCC::Folder::slotNetworkUnavailable()

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2797]
Adding this here since in https://github.com/owncloud/client/issues/69#issuecomment-73070175 it seems to go under.

@qknight @jdhoek

**Comment by ckamm** [comment]
I already took care of it in 51b9ec30a9d6d1bfe879c82a940d22a384d83536, the connect() snuck back in in a complex merge (ba8b1bbe06aacb02b00737968503dc9ca95ba23a).
