### ISSUE TITLE
[SSL] [Client certs] Actually display/parse HTML error message

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2799]
Seen this when testing https://github.com/owncloud/client/issues/69 some days ago. Might not be that important anymore since I think we show a dialog now in any case?

```
02-04 17:50:18:182 0x7fabfae05610 networkjobs.cpp:543 error: status.php replied  400 "<html>
<head><title>400 No required SSL certificate was sent</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>No required SSL certificate was sent</center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by jdhoek** [comment]
Yes, a dialog is shown when any `https` URL returns any error. Parsing the actual error message might be complicated if HTML is returned (how will you display it?), but perhaps it is sufficient to settle for the HTTP error code?

For example, when a `403` code is returned, add the canonical description for it in the error message presented to the user:

> Could not connect to https://owncloud.example.org/, the server said `403: Forbidden`.

That would at least tell the user something of the nature of the error.

**Comment by guruz** [comment]
@ogoffart would probably recommend to use a simple ```QRegExp``` to take everything in the body that is not a ```<tag>``` (or ```</tag>```)

**Comment by guruz** [comment]
PR is pending..
