### ISSUE TITLE
[OS X?] Bring 'Share' dialog to the very front

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2800]
It appears under the ```Finder``` window.
Might not be easy to fix ("Viel hilft viel" @dragotin )

CC @rullzer

**Comment by dragotin** [comment]
Seeing this problem on Linux as well somehow.

**Comment by jturcotte** [comment]
Improved the situation on Windows with a955defae5d272aeeff200bc860fc546906370a8

This will probably help on OSX and Linux as well.

**Comment by lmaestro** [comment]
It is still happening on Windows in the lates build (version1.8. build 4733)

**Comment by jturcotte** [comment]
We can't really fix it completely on Windows, but at least now you'll see a flashing item in the task bar to know that the window appeared there.

Windows doesn't allow an application to raise itself on top and grab keyboard focus to prevent popups. It does work if there were no other windows already opened but my research ended up with the conclusion that we can't really fix that.

**Comment by ogoffart** [comment]
Closing this issue, since it is not possible to do better
