### ISSUE TITLE
[1.8.0] Client uses old share URL when sharing files

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/client#2803]
Pre-ownCloud 8 URL: `http://localhost/core/public.php?service=files&t=34grKMpDGWxAU3h`
ownCloud 8 URL: `http://localhost/core/index.php/s/34grKMpDGWxAU3h`

Anyways, the old URL will also work on 8 as it has a redirect as fallback. URL looks just a little bit terribly long in the share dialog.

**Comment by rullzer** [comment]
PR #2813 makes the client use the new url if the server version is >= 8.

@LukasReschke it seems the OCS API still returns the old URL when creating a share..

**Comment by MegaV0lt** [comment]
Is it possible and/or useful ti integrate a kind of "shortener? Ther exist many like j.mp 
is it even possible to integrate a own one? (oc.dyndns.org/hE5hX) or similar?

**Comment by rullzer** [comment]
This should be fixed now.
The server now returns the new URL (which we use if available) and else we generate it ourself the new fancy url if the server is new enough.

**Comment by dragotin** [comment]
reopening for test. @Dianafg76

**Comment by Dianafg76** [comment]
I tested de issue and the server returns the new URL. I close the issue
Desktop v1.8.2 (build 2359)
