### ISSUE TITLE
Verify and document a safe solution for syncing same folder on dual boot machines

### ISSUE THREAD

**Issue by Morganlej** [owncloud/client#2806]
I have seen this question some places and of course interest exist.
It looks like some have failed, some suceeded.
Here it seemed to work: #70
Here is what i try out now: http://forum.owncloud.org/viewtopic.php?t=19672&p=53479#p78867
(I am Morgano there)

The thing i think may go wrong is if the clients databases which are stored in hidden files in the root of the synk job client folder are not compatible between versions (they cannot always be upgraded equally) and/or some paths differ depending on OS differences.  Also the user may have set things up in a conflicting way.

**I suggest**
1) some knowledgeable person design, test, and document a reliable method to include in the owncloud client user documentation
_and/or_
2) developer make it work reliably (i.e databases stored other place or named differently. (or if possible guaranteed to be used by either client even with different versions, OS, and conflicting setup...)

_Personally i want to easily share files of a current project to my laptop and some apps are only for windows, some only for linux, and i want to sync and acces all i share to it regardless of what OS is running at the moment. (and no virtual system does not suit purpose)_

**Comment by guruz** [comment]
If you use the same client versions my guess is it should work fine.

**Comment by Morganlej** [comment]
It is the guessing we need to eliminate  ;)
That said, it seem still to work in my setup as I linked to above.

**Comment by Jas2Ma** [comment]
Any progress here? Any statement from the developers?

**Comment by danimo** [comment]
No progress as you can see. And if you are looking for a general statement, I can only give you one from "the most active developers": We probably won't get to this anytime soon. That said, ownCloud is Open Source, and we're happy to discuss and accept contributions in this direction.

**Comment by Morganlej** [comment]
I never saw problems with my 1.8.3 clients on my dual boot windows/linux, but when i moved to 2. (both systems) there were problems so I i now do not sync same folder from more than one OS.
I guess it will work when in future the syncing is more intelligent, i.e compare files by content etc.

**Comment by ogoffart** [comment]
Closing an old issue.  This is not something we are working on.
