### ISSUE TITLE
Reliably persist cookies

### ISSUE THREAD

**Issue by danimo** [owncloud/client#2808]
So far, we only persist cookies if the shibboleth auth method is chosen. This has two downsides:

1) It does not handle accesses to remote resources that are queried before shib auth is chosen (i.e. `status.php`)
2) It is not implemented for the basic auth type (to be verified).

This is a disadvantage for setups using load balancers which track their clients through cookies. Those assuming that the cookie is retruned/persistent no matter which resource is being accesses.

**Comment by v6sa** [comment]
Hi, I was just digging through the cookie code to see what's going on. Even with the last Git commit OwnCloud sync client writes ~/.local/share/data/ownCloud/cookies.db upon exit, but ignores the contents at next launch and seeks for user password from the keychain instead. Even without Shibboleth I think it would be a good idea to primarily rely on cookies as leaked password from keyring has more potential for damage than leaked cookie.

**Comment by guruz** [comment]
CC @ckamm @ogoffart @LukasReschke

**Comment by ckamm** [comment]
We currently don't store session cookies in cookies.db. For Shibboleth we consider the cookie a secret that's stored in the keychain instead. We could reconsider that, and store session cookies in cookies.db or we could store the http session cookie in the keychain as well.

I also recently saw some oddities with loading and saving cookies.db and will look into that.

**Comment by ckamm** [comment]
cookies.db is now handled more reliably. I did not make any changes to the code that prevents session cookies to be read or written to cookies.db: that needs talks with @danimo @ogoffart @guruz .

**Comment by guruz** [comment]
@danimo Why would cookies not be always stored in they keychain?

**Comment by ogoffart** [comment]
The normal cookies are stored in the cookies database.
The session cookies are not stored because they are just session cookies and not supposed to be stored.
With the exception of the shiboleth session cookies which is stored in the keychain because it is sensitive data

**Comment by ckamm** [comment]
@danimo I'm unsure whether something needs to be done or tested here?

**Comment by Dianafg76** [comment]
I can't tested the bug because when you go in to shibboleth, appears the error:
![screen shot 2015-05-20 at 08 44 32](https://cloud.githubusercontent.com/assets/12032058/7720354/8fbda7ea-fecc-11e4-85e8-1679e8727a45.png)

**Comment by corneliusweiss** [comment]
sorry for responding to this old issue, but imho this is still open.

the client does not remember cookies after a restart. (at least with basic auth)
I can see that extra cookies are stored in the cookies.db but the client doesn't use it after restart

As @danimo described initially this is a problem e.g. for sticky load balancing.

**Comment by michaelstingl** [comment]
@corneliusweiss Could you open a new issue and provide some more information? What client version? What operating system? Steps to reproduce etc… So many things changed since 2015. Thanks!
