### ISSUE TITLE
Build owncloud client with qt5 (Gentoo)

### ISSUE THREAD

**Issue by ne0h** [owncloud/client#2809]
Hi,

when i am trying to build the owncloud client 1.7.1 at Gentoo Linux and qt5 i always get this error:

/home/ne0h/Downloads/mirall-1.7.1/src/mirall/theme.h:31:42: error: invalid use of incomplete type ‘class QObject’
 class OWNCLOUDSYNC_EXPORT Theme : public QObject
                                          ^
In file included from /usr/include/qt5/QtCore/qmetatype.h:45:0,
                 from /usr/include/qt5/QtCore/QMetaType:1,
                 from /home/ne0h/Downloads/mirall-1.7.1/src/mirall/syncfileitem.h:20,
                 from /home/ne0h/Downloads/mirall-1.7.1/src/mirall/syncresult.h:23,
                 from /home/ne0h/Downloads/mirall-1.7.1/src/mirall/theme.h:18,
                 from /home/ne0h/Downloads/mirall-1.7.1/src/mirall/theme.cpp:15:
/usr/include/qt5/QtCore/qobjectdefs.h:246:7: error: forward declaration of ‘class QObject’
 class QObject;
       ^
/home/ne0h/Downloads/mirall-1.7.1/src/mirall/theme.cpp: In constructor ‘Mirall::Theme::Theme()’:
/home/ne0h/Downloads/mirall-1.7.1/src/mirall/theme.cpp:156:5: error: type ‘QObject’ is not a direct base of ‘Mirall::Theme’
     QObject(0)
     ^
src/CMakeFiles/owncloudsync.dir/build.make:310: recipe for target 'src/CMakeFiles/owncloudsync.dir/mirall/theme.cpp.o' failed
make[2]: *** [src/CMakeFiles/owncloudsync.dir/mirall/theme.cpp.o] Error 1
CMakeFiles/Makefile2:403: recipe for target 'src/CMakeFiles/owncloudsync.dir/all' failed
make[1]: *** [src/CMakeFiles/owncloudsync.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2

Is this a problem with my system or does just owncloud client build with qt5?

Thanks in advance!

**Comment by ogoffart** [comment]
I don't know why it compiled for me and not for you.  I added the include anyway.

**Comment by ogoffart** [comment]
Can you try to compile again from the github repository?

**Comment by ne0h** [comment]
Of course i can :)
I cloned the client repository and tried to build it:

`$ git clone git@github.com:owncloud/client.git oc_client`
`$ cd oc_client`
`$ mkdir build`
`$ cd build`
`$ cmake -DCMAKE_BUILD_TYPE="Debug" ..`
`$ make`

No i get lots of error, starting with:

/home/ne0h/git/oc_client/src/libsync/cookiejar.cpp: In function ‘QDataStream& OCC::operator<<(QDataStream&, const QList<QNetworkCookie>&)’:
/home/ne0h/git/oc_client/src/libsync/cookiejar.cpp:31:12: error: ambiguous overload for ‘operator<<’ (operand types are ‘QDataStream’ and ‘const unsigned int’)
     stream << JAR_VERSION;
            ^
/home/ne0h/git/oc_client/src/libsync/cookiejar.cpp:31:12: note: candidates are:
In file included from /usr/include/qt5/QtCore/QVariant:1:0,
                 from /home/ne0h/git/oc_client/src/libsync/configfile.h:21,
                 from /home/ne0h/git/oc_client/src/libsync/cookiejar.cpp:16:
/usr/include/qt5/QtCore/qvariant.h:531:28: note: QDataStream& operator<<(QDataStream&, const QVariant&)
 Q_CORE_EXPORT QDataStream& operator<< (QDataStream& s, const QVariant& p);
                            ^
In file included from /usr/include/qt5/QtCore/qstring.h:41:0,
                 from /usr/include/qt5/QtCore/qobject.h:41,
                 from /usr/include/qt5/QtCore/QObject:1,
                 from /usr/include/qt5/QtNetwork/qnetworkcookiejar.h:37,
                 from /usr/include/qt5/QtNetwork/QNetworkCookieJar:1,
                 from /home/ne0h/git/oc_client/src/libsync/cookiejar.h:17,
                 from /home/ne0h/git/oc_client/src/libsync/cookiejar.cpp:14:
/usr/include/qt5/QtCore/qchar.h:558:28: note: QDataStream& operator<<(QDataStream&, QChar)
 Q_CORE_EXPORT QDataStream &operator<<(QDataStream &, QChar);
                            ^
/home/ne0h/git/oc_client/src/libsync/cookiejar.cpp:32:12: error: ambiguous overload for ‘operator<<’ (operand types are ‘QDataStream’ and ‘quint32 {aka unsigned int}’)
     stream << quint32(list.size());
            ^
/home/ne0h/git/oc_client/src/libsync/cookiejar.cpp:32:12: note: candidates are:
In file included from /usr/include/qt5/QtCore/QVariant:1:0,
                 from /home/ne0h/git/oc_client/src/libsync/configfile.h:21,
                 from /home/ne0h/git/oc_client/src/libsync/cookiejar.cpp:16:
/usr/include/qt5/QtCore/qvariant.h:531:28: note: QDataStream& operator<<(QDataStream&, const QVariant&)
 Q_CORE_EXPORT QDataStream& operator<< (QDataStream& s, const QVariant& p);
                            ^
In file included from /usr/include/qt5/QtCore/qstring.h:41:0,
                 from /usr/include/qt5/QtCore/qobject.h:41,
                 from /usr/include/qt5/QtCore/QObject:1,
                 from /usr/include/qt5/QtNetwork/qnetworkcookiejar.h:37,
                 from /usr/include/qt5/QtNetwork/QNetworkCookieJar:1,
                 from /home/ne0h/git/oc_client/src/libsync/cookiejar.h:17,
                 from /home/ne0h/git/oc_client/src/libsync/cookiejar.cpp:14:
/usr/include/qt5/QtCore/qchar.h:558:28: note: QDataStream& operator<<(QDataStream&, QChar)
 Q_CORE_EXPORT QDataStream &operator<<(QDataStream &, QChar);
                            ^
Should i poste the rest of the errors, too?

**Comment by danimo** [comment]
Please retry with 1.8.0beta1, and post the errors in a gist, along with the exact version of Qt and the compile flags for both Qt and the client.

**Comment by ne0h** [comment]
I downloaded the client realease 1.8.0beta1 and tried to compile without any non-default compile flags.
The gist is availible here: https://gist.github.com/ne0h/c58fec28d854e2754f69

Qt version is 5.3.1, compiled with Gentoo build flags:
[ebuild   R   *] dev-qt/qtcore-5.9999:5::qt  USE="icu systemd -debug {-test}" 0 KiB

Do you need more information about my system?

**Comment by guruz** [comment]
From your gist:
```
-- Using Qt 5.5.x
```

What does ```qmake -v``` say?

Since we don't get compile trouble I blame it on gentoo :-)
