### ISSUE TITLE
About ignore list documentation and defaults

### ISSUE THREAD

**Issue by Morganlej** [owncloud/client#2814]
Program or document or both need to be slightly adjusted

http://doc.owncloud.org/desktop/1.7/architecture.html#ignored-files-label state that the client per default ignore .csync_journal.db* .  However per default in the ignore list (client 1.7.1) that item is found without checkmark, and without the "*".

This rise some questions:
§ Is it ignoring .csync_journal.db* regardless of if it is set in sync-exclude-lst? So the program have some internal ignore rules? Then document that and do not keep in list. Maybe it per default ingore its own .csync_journal.db* and other of its own files from sync, but syncs them if such named files are found other places, if not active in the list?

§ or is the documentation wrong?

§ Maybe the cleanest is to not have internal ignore rules for owncloud housekeeping files, but put all in list and of course have them selected by default.

And what other files are in use by owncloud clinet?  In the list there is .csync_journal.db, .csync_journal.db.ctmp, *.csync_timedif.ctmp*, .owncloudsync.log and i have seen .csync_journal.db-shm, .csync_journal.db-wal while it is running.

While discussing ignore files: I see thera are some excludes for file sync program i.e *.unison* - good!
I suggest to add for my favourites .synkron.* ( program Synkron ) and .sync.ffs_db ( FreeFileSync ).  And i suggest make them all selected by default.  Not many users of programs understands why things may have gone wrong, even ledd find a fix easily.

* I got into reading about it because i use mire synchornisers than ownclous, and try dual boot owncloud: #2806 and viewtopic.php?f=14&t=19672&p=78867#p78867 *

**Comment by dragotin** [comment]
@carlaschroder that might be something for you

**Comment by carlaschroder** [comment]
Hi @Morganlej, if you follow the link in that section to https://doc.owncloud.org/desktop/1.7/visualtour.html#ignoredfileseditor-label, it explains that some of the defaults do not have their checkboxes enabled, but you must edit their source configuration files to change them. It is discouraged to edit these because it could lead to problems. 

I'm afraid I can't answer your other questions, so I will leave this open.

**Comment by razyr** [comment]
@carlaschroder   Just a thought, but it's not obvious to end users what do if the file they want to ignore is already on the list, but greyed out and not checked.

Let's take desktop.ini as an example.  I have a user who is complaining that her OwnCloud folder never synchs.  On investigation there is an desktop.ini buried down in a subfolder which is reported as locked open.

She tried to edit the ignored files list in the 1.8 client UI, but the entry for desktop.ini is locked by the sync-exclude.lst.   She assumed that it was impossible to ignore "desktop.ini".

If you open the sync-exclude.lst in Windows notepad, it lacks CR/LF so it's not practical to edit and even then, the notation is not obvious to the average user.

I instructed her to just add "desktop.ini" to the list through the UI as a new entry and ensure the box was checked.  I'm not entirely certain how one would un-ignore ".Trashes" for example.  Add it to the end of the list and leave the box unchecked?   These duplicate entries are counter-intuitive.

I can see pre-populating the list with common files/extensions that many users would want to have as defaults, but locking the entries from sync-exclude.lst seems counter-productive.

**Comment by guruz** [comment]
@razyr Have you had a look at a recent 2.0 nightly build? The UI has changed there (#2650) which probablu helps..

http://download.owncloud.com/desktop/daily/

**Comment by carlaschroder** [comment]
I believe this has been resolved, closing (see linked PRs).
