### ISSUE TITLE
When you enable the option of " Set default expiration date", you can share by link without knowing it

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2815]
### Expected behavior
You can share by link using set default expiration date from the admin side.
When you click on share by link the expiration date is enable by default.
When you enforced expiration date, you can't select more days than it is shown by default but you can select less.

### Actual behavior
You can share by link without knowing that there are an expiration date 
And when you enable the option "Set expiry date", an error is shown:
![screen shot 2015-02-10 at 3 24 11 pm](https://cloud.githubusercontent.com/assets/4689430/6128743/e558dc42-b138-11e4-8ef0-e49d04d49d19.png)

### Steps to reproduce
1.  Enable the option  "Set default expiration date"  from the admin side
2. Try to share by link form the desktop 

### Client configuration
Version 1.8.0-nightly20150209(build2001)

Operating system: OS X 10.10.1

**Comment by dragotin** [comment]
We can not fix this as long as the proper API is not in place, see https://github.com/owncloud/core/pull/13964
Moving to future milestone.

**Comment by guruz** [comment]
Looks like the server side API has been merged..

FYI @rullzer

**Comment by rullzer** [comment]
Yes it is. I'll make sure to work on the capabilities stuff tomorrow... should improve the UX!

**Comment by Dianafg76** [comment]
I try this Issue and is working fine, so I close the issue
Desktop v ownCloud-2.0.0.2555-nightly20150722.pkg
