### ISSUE TITLE
[ownBrander] Allow for Custom User Agent String

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#2818]
As an admin I want to be able to prevent standard ownCloud apps from connecting to my ownCloud server, I want my users to use the custom ownCloud apps I have designed.

The concept here is that a quick fix with a custom user agent string through ownBrander would enable a filter on "non-authorized" clients.

Not perfectly secure for a determined user, but ok as a quick fix.

**Comment by MTRichards** [comment]
For clarity, the ask is to prevent the case that a company has devices and laptops where policies are applied. However, just any old user can grab a PC at home (or mobile device) and get the standard ownCloud apps, and with their accounts sync all this data to unauthroized computers. This can be not only a policy violation, but a huge regulatory nightmare as data is now outside controls of the enterprise.

**Comment by shoeper** [comment]
That can't be a serious request. Install a firewall and force users to use a vpn client. That gives serious security and not something like a changed user agent.

**Comment by MTRichards** [comment]
Reminding myself for 1.9 consideration.

**Comment by dragotin** [comment]
@MTRichards the user agent string has a branding depending component now, it adds the branding app name as the mobile clients do. So filtering is possible. Do you think that is sufficient?

**Comment by MTRichards** [comment]
Yes. We just need to add this to ownBrander now as a branding option.
@rperezb for our ownBrander backlog

**Comment by MTRichards** [comment]
https://github.com/owncloud/ownbrander/issues/170

**Comment by MTRichards** [comment]
https://github.com/owncloud/ownbrander/issues/359

**Comment by guruz** [comment]
Done as per ec83295b99d67e28454ca303b922cd4514448793

**Comment by rperezb** [comment]
Got it @MTRichards thx

**Comment by MTRichards** [comment]
Need to add the $string component.

**Comment by dragotin** [comment]
@MTRichards add a $string where?

**Comment by rperezb** [comment]
at the end of the user agent,
For instance, on iOS, we have as default user agent:

```Mozilla/5.0 (iOS) ownCloud-iOS ```
In case it´s wanted the string it will be needed something as: ```Mozilla/5.0 (iOS) ownCloud-iOS $String ```

**Comment by MTRichards** [comment]
yup, as @rperezb said just like on Mobile. Thank you.

**Comment by danimo** [comment]
The current logic is

```
    if( appName != QLatin1String("ownCloud") ) {
        re += QString(" (%1)").arg(appName);
    }
```

is that not good enough?

**Comment by rperezb** [comment]
Well, if we take into account: the previous part

```
QByteArray Utility::userAgentString()
{
    QString re = QString::fromLatin1("Mozilla/5.0 (%1) mirall/%2")
            .arg(platform())
            .arg(QLatin1String(MIRALL_STRINGIFY(MIRALL_VERSION)));

    QLatin1String appName(APPLICATION_SHORTNAME);

    // this constant "ownCloud" is defined in the default OEM theming
    // that is used for the standard client. If it is changed there,
    // it needs to be adjusted here.
    if( appName != QLatin1String("ownCloud") ) {
        re += QString(" (%1)").arg(appName);
    }
```

yes  :+1:
