### ISSUE TITLE
Nautilus integration: restarting client breaks it 

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#2820]
When I use nautilus while the ownCloud client is running I see nice overlay icons.

However, when I restart the client, the overlay icons vanish and don't come back. This is what gets printed to stderr:
```
Server response: UNREGISTER_PATH:/home/kamm/ownCloud/
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] No such file or directory
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] No such file or directory
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] No such file or directory
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] No such file or directory
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Setting connected to False
```

I haven't looked at it in detail, but it looks like self._connected is False while SocketConnect._connected is True - and no one sets up a watcher on the newly created socket...

**Comment by dragotin** [comment]
thanks, I will take care.

**Comment by dragotin** [comment]
Thanks, tested this and works fine.

**Comment by vonflynee** [comment]
The error still persists.
When nautilus is started, it repeats error message every few seconds:

<code>
(nautilus:3749): Gtk-WARNING **: Failed to register client: GDBus.Error:org.gnome.SessionManager.AlreadyRegistered: Unable to register client
sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before import to ensure that the right version gets loaded.
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Socket File: /run/user/1000/ownCloud/socket                                                                                                           
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu                                                                          
Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket                                                                                           
Socket File: /run/user/1000/ownCloud/socket                                                                                                           
Could not connect to unix socket.[Errno 2] Nie ma takiego pliku ani katalogu</code>

The last information says "No such file or directory" in polish.

**Comment by petres** [comment]
Same for me:
- owncloud-client 2.0.2-1
- gnome-shell 3.18.3-1
```
Nov 21 23:24:29 karl gnome-session[795]: Could not connect to unix socket.[Errno 2] No such file or directory
Nov 21 23:24:29 karl gnome-session[795]: Socket: /run/user/1000/ownCloud/socket <=> /ownCloud/socket
Nov 21 23:24:29 karl gnome-session[795]: Socket File: /run/user/1000/ownCloud/socket
```
