### ISSUE TITLE
/etc/ownCloud/* should be flagged config files also in DEB packages.

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#2821]
@dragotin https://www.debian.org/doc/debian-policy/ap-pkg-conffiles.html

**Comment by jnweiger** [comment]
@dragotin 
please check https://build.opensuse.org/request/show/292492

**Comment by hefee** [comment]
On debian system all files are added as configfiles automatically if they are placed under /etc/. And adding these files to debian/conffiles will make linitian report about double conffig files. So please check with lintian if is really nessary and for what dists.

**Comment by ogoffart** [comment]
Closing old issue.
