### ISSUE TITLE
[1.8.0] Valgrind Session

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#2823]
Do a nice valgrind session with 1.8.0 to make sure not to catch memory f...ckups.

**Comment by ckamm** [comment]
I just ran the client through valgrind, running a couple of sync operations, used the share dialog and socketapi integration. I didn't see anything particularly suspicious about depending on uninitialized data or about definitely lost memory (there are a lot of reports though).

**Comment by ogoffart** [comment]
I ran massif, and it looks like it's not growing.  (I was connected to localhost and was running a script that touches files)

![massif](https://cloud.githubusercontent.com/assets/959326/6228640/c29883b2-b6ae-11e4-9289-31e70dfc2a56.png)

**Comment by dragotin** [comment]
Thanks! Closing this one.
