### ISSUE TITLE
Nautilus integration: overlay icons persist when client crashes

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#2830]
Discovered by @lmaestro:

Normally, when one closes the owncloud client, the overlay icons stop being displayed. However, when the client crashes or is killed with SIGKILL the overlay icons stay around.

To reproduce:
- Start nautilus and owncloud
- Check that overlay icons are visible
- pkill -9 owncloud
- Overlay icons are still visible

One approach for a fix would be to add a heartbeat to the communication between client and integration script.

**Comment by hodyroff** [comment]
Honestly, won't fix. When the client is deinstalled the icon's are away, right?

**Comment by ckamm** [comment]
@hodyroff Yes.
