### ISSUE TITLE
No sync when photos uploaded by Android client

### ISSUE THREAD

**Issue by fossxplorer** [owncloud/client#2831]
Lately i've noticed that my sync client 1.7.1 on Fedora 20 doesn't sync files (photos) uploaded by Android instant upload unless i manually restart the sync client on the desktop.

Android client version 1.5.7.

**Comment by dragotin** [comment]
sounds like the upload does not change the etag of the folder where its loaded into. @PVince81 or @DeepDiver1975 can you help?

**Comment by enoch85** [comment]
@fossxplorer Latest version of the Android app is 1.6.2. Try update. https://play.google.com/store/apps/details?id=com.owncloud.android&hl

**Comment by guruz** [comment]
@fossxplorer Did the new Android version fix the issue?

**Comment by fossxplorer** [comment]
@guruz Unfortunately it didn't.

**Comment by fossxplorer** [comment]
After a reboot of my desktop at work the sync works as it should. Closing the case.
