### ISSUE TITLE
Exiting the client mid-sync will prevent files from being synced for ever

### ISSUE THREAD

**Issue by jturcotte** [owncloud/client#2832]
To reproduce:

- Remove the folder syncing config
- Delete files on the client disk
- Re-add the folder
- While syncing (either while discovering or fetching, I did both and I'm not sure which one is causing the issue) restart the client

Expected result:
The client continues fetching missing files from that directory

Actual result:
The directory is left incomplete and the status says "done".
Restarting the client or the computer again doesn't fix the issue.

Relevant log entry from the log after resync:
02-12 12:41:34:421 0x824028c _csync_detect_update: Reading from database: client
02-12 12:41:34:421 0x824028c _csync_detect_update: file: client, instruction: INSTRUCTION_NONE <<=
02-12 12:41:34:421 0x824028c csync_statedb_get_below_path: 0 entries read below path client from db.

Environment:
Build 4687 on Windows 8.1

**Comment by ogoffart** [comment]
After investigation we found out that this happens only if you have something like  "directory"  and "directory-something"  
Because of the order:

directory
directory-foobar
directory/contents

**Comment by dragotin** [comment]
@ogoffart is this ready-to-test?

**Comment by nekoal** [comment]
My issue may be matches header, but I haven't solid proof now. After pause during sync 3 files shows in activity log "Operation canceled". After resume activity log has no new records about this files but some files downloaded from server (no other clients connected to this folder on server and I didn't change any files on server). I'll write result after re-check this files in folder and on server.
Client version: 1.8.0-nightly20150213 (4715)

**Comment by nekoal** [comment]
Re-check found 1 different timestamp after file downloaded from server. It's something wrong with logging: files with "Operation canceled" uploaded normally.

**Comment by jturcotte** [comment]
Can't reproduce this issue anymore. To clarify, the problem was actually quite difficult to hit, you had to have something like:

dir1/
dir1/<stuff>
dir1-foo/
dir1-foo/<stuff>

And you had to exit the client while dir1-foo/<stuff> was syncing, but before it went back to sync dir1/stuff. dir1/ would be left empty in that case.

@nekoal Please open a new issue if you can get clean repro steps, I'll close this one.
