### ISSUE TITLE
[ubuntu] symbol lookup error: owncloud

### ISSUE THREAD

**Issue by manuel-uberti** [owncloud/client#2833]
Hello. I am on Ubuntu 14.04 (amd64). I installed ```owncloud-client``` today following the instructions on the official website.

I get this error when trying to run the command ```owncloud```:
```
owncloud: symbol lookup error: owncloud: undefined symbol: _ZN6Mirall15HttpCredentials16staticMetaObjectE
```
If you need me to provide further informations to investigate the issue, please let me know.

**Comment by ckamm** [comment]
Unfortunately I cannot reproduce the problem. I extracted the Ubuntu 14.04 (amd64) packages for owncloud-client_1.7.1_amd64.deb and libowncloudsync0_1.7.1_amd64.deb and could run the owncloud client successfully.

Could you verify your installation works correctly? Here are my sha1sums of the binary and core shared libraries:
```
08ab346dbb02998a0bc0b964ac7a6d2c4b890195  /usr/bin/owncloud
1f3309c9adbe584325bb76459b3934897357791e  /usr/lib/x86_64-linux-gnu/libowncloudsync.so.1.7.1
a084f5719aa3f503578e1d259d40e1170cd2027a  /usr/lib/x86_64-linux-gnu/owncloud/libocsync.so.0.2.1
```

**Comment by boccaperta-it** [comment]
Same as mine sha1sums:
```
08ab346dbb02998a0bc0b964ac7a6d2c4b890195  /usr/bin/owncloud
1f3309c9adbe584325bb76459b3934897357791e  /usr/lib/x86_64-linux-gnu/libowncloudsync.so.1.7.1
a084f5719aa3f503578e1d259d40e1170cd2027a  /usr/lib/x86_64-linux-gnu/owncloud/libocsync.so.0.2.1
```

**Comment by ckamm** [comment]
@boccaperta-it Huh, odd!

Are the library symlinks set up correctly? Check

    ldd /usr/bin/owncloud | grep sync

and then

    ls -l /usr/lib/x86_64-linux-gnu/libowncloudsync.so.0 /usr/lib/x86_64-linux-gnu/owncloud/libocsync.so.0

do these point to the 1.7.1 and 0.2.1 version respectively?

**Comment by boccaperta-it** [comment]
This is what I got
```ldd /usr/bin/owncloud | grep sync
	libowncloudsync.so.0 => /usr/local/lib/libowncloudsync.so.0 (0x00007f3821a4e000)
	libocsync.so.0 => /usr/lib/x86_64-linux-gnu/owncloud/libocsync.so.0 (0x00007f38215ef000)
	libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007f3815ab2000)

ls -l /usr/lib/x86_64-linux-gnu/libowncloudsync.so.0 /usr/lib/x86_64-linux-gnu/owncloud/libocsync.so.0
lrwxrwxrwx 1 root root 24 Feb  6 20:05 /usr/lib/x86_64-linux-gnu/libowncloudsync.so.0 -> libowncloudsync.so.1.7.1
lrwxrwxrwx 1 root root 18 Feb  6 20:05 /usr/lib/x86_64-linux-gnu/owncloud/libocsync.so.0 -> libocsync.so.0.2.1
```

**Comment by ckamm** [comment]
Great, so we have exactly the same binary and shared libraries -- but it works for me and not for you. @danimo Any ideas?

**Comment by boccaperta-it** [comment]
It's even stranger because on another machine with Debian Jessie, the same client works fine.

**Comment by danimo** [comment]
How can you guys have the same sha sums? The packages should be different for 14.04 and 10.10, built with different compilers, etc. It's rather unlikely.

**Comment by boccaperta-it** [comment]
I could try to launch ```sha1sum``` again, if you need me to.

**Comment by ckamm** [comment]
@danimo We're both using the 14.04 packages, I think.

**Comment by ckamm** [comment]
@manuel-uberti I think the problem is this

    libowncloudsync.so.0 => /usr/local/lib/libowncloudsync.so.0

it should be using /usr/lib/x86_64-linux-gnu/libowncloudsync.so.0 instead. If you put it there yourself you could remove it and your installed version should start to work.

**Comment by manuel-uberti** [comment]
@ckamm thank you, removing ```/usr/local/lib/libowncloudsync.so.0``` fixed it.

**Comment by PasiC** [comment]
I got the same error today (while on wheezy the client runs correctly). I didn't try to reinstall packages (yet):

> /usr/bin/owncloud
/usr/bin/owncloud: symbol lookup error: /usr/lib/x86_64-linux-gnu/libowncloudsync.so.0: undefined symbol: _ZN9QKeychain15ReadPasswordJob6setKeyERK7QString
> ldd /usr/bin/owncloud | grep sync
        libowncloudsync.so.0 => /usr/lib/x86_64-linux-gnu/libowncloudsync.so.0 (0x00007fa8494c2000)
        libocsync.so.0 => /usr/lib/x86_64-linux-gnu/owncloud/libocsync.so.0 (0x00007fa849069000)
        libxcb-sync.so.1 => /usr/lib/x86_64-linux-gnu/libxcb-sync.so.1 (0x00007fa84180f000)

> cat /etc/lsb-release 
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.3
DISTRIB_CODENAME=rosa
DISTRIB_DESCRIPTION="Linux Mint 17.3 Rosa"
> dpkg -l | grep owncloud
ii  libowncloudsync0:amd64                                      2.1.1-2.1                                          amd64        the ownCloud sync library
ii  owncloud-client:amd64                                       2.1.1-2.1                                          amd64        The ownCloud sync client - github.com/owncloud/client
ii  owncloud-client-l10n                                        2.1.1-2.1                                          all          Internationalization files for ownCloud

**Comment by MichalSchwarz** [comment]
I got the same error today. For me helped to remove `http://download.opensuse.org` from sources list and install owncloud-client from debian repository.
```
$ lsb_release -da
LSB Version:	:base-4.0-amd64:base-4.0-noarch:core-4.0-amd64:core-4.0-noarch
Distributor ID:	CentOS
Description:	CentOS release 6.7 (Final)
Release:	6.7
Codename:	Final
```

**Comment by PasiC** [comment]
thx, finally i reinstalled from repo, AFTER cleaning the apt-cache (somehow it didn't recognize the new versions of libs :( ) so, its a package management issue on ubuntu based distro(s)

**Comment by chrisdelrey** [comment]
I've had owncloud client running on various clients for a few months now but on Ubuntu 14.04 I had a software update that seem to break the link. trying the suggestion above removing the link had no positive effects, remove the package and rinsing and re-installing worked for me
`sudo apt-get remove owncloud-client -y`
`sudo apt-get autoremove`
`sudo apt-get install owncloud-client -y`
