### ISSUE TITLE
Redirection error codes cause Shibboleth credential invalidation

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#2835]
Currently, any network call that returns a 302 status code will invalidate the shibboleth credentials. See ShibbolethCredentials::slotReplyFinished().

This can cause problems like #2834 where an authed request returned 302 without wanting to indicate that the user needed to log in again.

To solve this properly we need to be able to tell apart 302-because-auth-needed from regular 302 status codes.

**Comment by guruz** [comment]
FYI @danimo

**Comment by ogoffart** [comment]
Closing as shibboleth will be removed
