### ISSUE TITLE
[Windows] When I try to open the local folder it closes suddenly 

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2836]
### Actual behaviour
When I try to open the local folder it closes suddenly 

### Steps to reproduce
1. Launch the app
2. The account is synced
3. Click to "open local folder"

### Client configuration
Client version: 1.8.0-nightly20150213 (build 4717)

Operating system: Windows 8

### Logs
````
02-13 10:30:46:934 0x5a7a230 socketapi.cpp:170 SocketApi: New connection QLocalSocket(0x991d4c8)
02-13 10:30:46:934 0x5a7a230 socketapi.cpp:326 SocketApi: Sending message: "REGISTER_PATH:C:\Users\ASUS\Desktop\shib\"
02-13 10:30:47:645 0x5a7a230 networkjobs.cpp:227 !!! OCC::CheckQuotaJob created for QUrl( "https://test1.owncloud.com/oc7-shib" ) querying "/"
02-13 10:30:55:214 0x5a7a230 :0 Failed to resolve EGL function eglGetPlatformDisplayEXT (No se encontró el proceso especificado.)
02-13 10:30:55:219 0x5a7a230 :0 static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

02-13 10:30:55:220 0x5a7a230 :0 static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
02-13 10:30:55:274 0x5a7a230 :0 Failed to resolve EGL function eglGetPlatformDisplayEXT (No se encontró el proceso especificado.)
02-13 10:30:55:277 0x5a7a230 :0 static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

02-13 10:30:55:277 0x5a7a230 :0 static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
02-13 10:30:59:660 0x5a7a230 connectionvalidator.cpp:128 # Check whether authenticated propfind works.
02-13 10:30:59:662 0x5a7a230 networkjobs.cpp:227 !!! OCC::PropfindJob created for QUrl( "https://test1.owncloud.com/oc7-shib" ) querying "/"
02-13 10:31:03:347 0x5a7a230 folderman.cpp:664 void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("ownCloud")
02-13 10:31:03:349 0x5a7a230 folder.cpp:252 * Trying to check "ownCloud" for changes via ETag check. (time since last sync: 413 s)
02-13 10:31:03:353 0x5a7a230 folderman.cpp:512 Scheduling "ownCloud" to check remote ETag
02-13 10:31:03:355 0x5a7a230 networkjobs.cpp:227 !!! OCC::RequestEtagJob created for QUrl( "https://test1.owncloud.com/oc7-shib" ) querying ""
02-13 10:31:04:157 0x5a7a230 folder.cpp:311 * Compare etag with previous etag: last: ""54ddaceae47b9"" , received: ""54ddaceae47b9""
02-13 10:31:04:213 0x5a7a230 owncloudgui.cpp:257 Folder in overallStatus Message: OCC::Folder(0x72770f0) with name "ownCloud"
02-13 10:31:04:219 0x5a7a230 folderman.cpp:510 No more remote ETag check jobs to schedule.
02-13 10:31:05:630 0x5a7a230 :0 Failed to resolve EGL function eglGetPlatformDisplayEXT (No se encontró el proceso especificado.)
02-13 10:31:05:631 0x5a7a230 :0 static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

**Comment by ckamm** [comment]
I can't reproduce the problem. The client just calls QDesktopServices::openUrl() - so if there is a bug, it's likely to be in Qt or Explorer.

@lmaestro One thing: I'd have expected a log line ...opening local url... which I don't see above. What does it say?

**Comment by apg1980** [comment]
The 1.8.0 Client crash the explorer.exe after installation and reboot on windows 8.1. i can confirm that.

**Comment by redhell** [comment]
I've got the same Problem on Win 8.1 x64

**Comment by juerghoerner** [comment]
I've got the same Problem on Win 8.1 x64. The explorer filesystem is closed and startet again automaticaly. 1.7. version is OK. 
Maybe it has something to do with this (from shell viewer): 
Name der fehlerhaften Anwendung: explorer.exe, Version: 6.3.9600.17415, Zeitstempel: 0x54503a3a
Name des fehlerhaften Moduls: MSVCR120.dll, Version: 12.0.21005.1, Zeitstempel: 0x524f83ff
Ausnahmecode: 0xc0000409
Fehleroffset: 0x0000000000074a30
ID des fehlerhaften Prozesses: 0x520
Startzeit der fehlerhaften Anwendung: 0x01d0499f47955426
Pfad der fehlerhaften Anwendung: C:\windows\explorer.exe
Pfad des fehlerhaften Moduls: C:\windows\SYSTEM32\MSVCR120.dll
Berichtskennung: 57e98a67-b593-11e4-826f-e82aea09620c
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by MegaV0lt** [comment]
Same here. OCClient 1.8beta crashes Windows Explorere permamently
```
Name der fehlerhaften Anwendung: Explorer.EXE, Version: 6.1.7601.17567, Zeitstempel: 0x4d6727a7
Name des fehlerhaften Moduls: MSVCR120.dll, Version: 12.0.21005.1, Zeitstempel: 0x524f7ce6
Ausnahmecode: 0x40000015
Fehleroffset: 0x000a7676
ID des fehlerhaften Prozesses: 0x1ca8
Startzeit der fehlerhaften Anwendung: 0x01d049b7c59c21e9
Pfad der fehlerhaften Anwendung: C:\Windows\Explorer.EXE
Pfad des fehlerhaften Moduls: C:\Windows\system32\MSVCR120.dll
Berichtskennung: 2794310e-b5ab-11e4-8b37-00241dd5f3f0
```

**Comment by MegaV0lt** [comment]
wtf... i removed the 1.8 beta and installed the 1.71 again. 

Now the explorer imeadetly crashes and other programs also as soon the owncloud client is running!
the 1.8beta must have damafged something. 

when i quit the occlient everything runs fine! Help!

**Comment by plages** [comment]
I think this has to do with the vcredist installation required for explorer integration. If i install the 1.8.0 (beta) build 4720 without the explorer integration, there's no crash. If i install WITH the explorer integration explorer crashes as soon as i try to navigate to the local folder. But also on other actions. For instance when i open an MMC console. Maybe in abundance but her's my eventlog error:

Naam van toepassing met fout: explorer.exe, versie: 6.3.9600.17415, tijdstempel: 0x54503a3a
Naam van module met fout: MSVCR120.dll, versie: 12.0.21005.1, tijdstempel: 0x524f83ff
Uitzonderingscode: 0xc0000409
Foutmarge: 0x0000000000074a30
Id van proces met fout: 0x698
Starttijd van toepassing met fout: 0x01d04953e1c6e933
Pad naar toepassing met fout: C:\WINDOWS\explorer.exe
Pad naar module met fout: C:\WINDOWS\SYSTEM32\MSVCR120.dll
Rapport-id: 37f9fa4e-b547-11e4-8330-5c514f6297e1

**Comment by dragotin** [comment]
We discovered a problem in the build process with the build of the first beta1. We fixed that in this build:
https://download.owncloud.com/desktop/testing/ownCloud-1.8.0.4730beta1-setup.exe

Please, if you have seen the problem with a previous build (build number < 4730) it would be great if you could update to this build and verify the bug report. Thanks!

**Comment by lmaestro** [comment]
It works fine in this version version 1.8.0 build 4730.
If anyone is able to reproduce it in this build, please reopen it or if it is another problem, please open a new issue.

**Comment by plages** [comment]
Same here it works fine now

**Comment by plages** [comment]
I think i know what the issue is. I'm running a custom built client side by side the beta build. Now i notice only one of them has the explorer integration. The one that starts up first get the explorer integration.

**Comment by lmaestro** [comment]
@plages Yes it is a known issue https://github.com/owncloud/client/issues/2505

**Comment by MegaV0lt** [comment]
Last Beta is working here so far; no crash... But the shellintegration does not aper. No contextmenu inside the local oc folder. Do i have to reboot to make it work?

**Comment by danimo** [comment]
@MegaV0lt ack

**Comment by vat78** [comment]
I have same problem with ownCloud 1.8.0.4893 on Windows 7 SP 1. ownCloud client can't build a main window.
Previous build had worked fine.

04-21 12:30:55:195 0x452ea98 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Не найдена указанная процедура.)
04-21 12:30:55:196 0x452ea98 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001
04-21 12:30:55:196 0x452ea98 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
