### ISSUE TITLE
fatal error: openssl/pem.h while compiling under Ubuntu

### ISSUE THREAD

**Issue by vgezer** [owncloud/client#2838]
The dependencies (sudo apt-get build-dep owncloud-client) do not install libss-dev, but it seems this is required.

sudo apt-get install libssl-dev

Another problem is:

owncloud: error while loading shared libraries: libowncloudsync.so.0: cannot open shared object file: No such file or directory

this happens after `sudo make install` and calling "owncloud" from terminal.

**Comment by ogoffart** [comment]
This could be related to #2833

**Comment by dragotin** [comment]
which version are we talking about?

**Comment by wakeup** [comment]
This was during compilation of the git master branch.
