### ISSUE TITLE
Germaqn translation some "," are misplaced

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#2840]
In then UI of teh 1.8 beta Client under Windows 7 it looks liekr the "," are misplaced:
Screenshot: http://i.imgur.com/yJdfIt5.png
It should be:
```
Ordner, ein....
```
note: there should bei __NO__ space between __Ordner__ and __,__

**Comment by danimo** [comment]
Same here, there is no space. It just looks it due to bad font hinting for punctuation marks behind the 'r'. But that's not our bug :-)

**Comment by MegaV0lt** [comment]
Why not using a font that is working?

**Comment by danimo** [comment]
Simple: We use whatever the user/OS picks for us. Plus this is probably not a font bug, but one in the renderer (Either Halfbuzz or Windows' GDI).

**Comment by MegaV0lt** [comment]
I installed teh 1.7.1 client and surprise! the Text looks good here! See screenshot:
http://i.imgur.com/BCZ46R7.png
Something must have changed in 1.8 Client!
