### ISSUE TITLE
Misplaced "." in SyncClient 1.8beta UI

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#2841]
There is a misplaced "." in the german translated 1.8beta client in Windows7:
http://i.imgur.com/UjFn4oH.png

It should be
```
...verfügbar. Ihre...
```
__No__ Space between __verfügbar__ and __.__

**Comment by danimo** [comment]
Sorry to disappoint, but there is no space and never was :-)

Btw: you can easily verify in https://github.com/owncloud/client/blob/master/translations/client_de.ts, and if you see something, apply a fix right away by joining our transifex group: https://www.transifex.com/projects/p/owncloud/translate/#de_DE/client/

**Comment by MegaV0lt** [comment]
Thank you , but it is not solving the bad ui expirience. Why can you not use a font with good hinting ?
This way it looks everything else than a professional software

**Comment by danimo** [comment]
Again, this is the Windows system font (`Segoe UI` in your case). If anything, the hinter itself would be broken, and we cannot swap the hinter, it's part of the toolkit (and used by a lot of other apps as well). Hard-coding a particular font is not an option, as the app would look weird in another way (different than all other apps), and there is no gurantee that hinting would work correct with other fonts.

Nontheless, if we find that hinting works properly in other apps, we should work with upstream to resolve the problem, which means filing a bug at https://bugreports.qt.io using a minimal test case.

**Comment by danimo** [comment]
Quick test confirms that it's a bug in the Qt font rendering (which AFAIK uses Halfbuzz).

**Comment by MegaV0lt** [comment]
no idea what that means. Anything that can be done?
is it already the actual qt rendering using? if yes can someone who is knowing how to describe the problem file an bugreport?
