### ISSUE TITLE
variable chunk size

### ISSUE THREAD

**Issue by shoeper** [owncloud/client#2842]
Chunk size seems to be fixed at 20MB. I think one should be able to specify a chunk size. Not requireing that many request could save quite some overhead on server side. At least on local networks it would be helpful to set the chunk size to 100+ MB. In my case upload could easily be at 40 MB/s (that's what even Internet Explorer is able to upload via webinterface). So client should be able to push 80-100MB's via multiple connections. Currently maximum is at about 30MB's. That seems to be related to the small chunksize.

Furthermore - but that seems to be a server side issue, chunks are not saved in the target directory but first saved in the cache directory. That makes it quite slow when cache and target are on different drives.

**Comment by ogoffart** [comment]
You can already change the chunk size with the `OWNCLOUD_CHUNK_SIZE` environement variable.  (this is a value in bytes.)

The client 1.8 will do parallel chunk uploads and the size is now 5MiB.
The server is also going to improve with owncloud 8.1
