### ISSUE TITLE
[OS X] Mac client installer issue when picking target disk

### ISSUE THREAD

**Issue by sebastiennoir** [owncloud/client#2843]
### Expected behaviour
Open client installer package freshly downloaded from website, select target disk, install.
Installation completes with success and client can be launched.

### Actual behaviour
Installer opens, target disk can be selected. Installation starts. And stops near the end with error :
The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.

### Steps to reproduce
1. Download client from website
2. Open package
3. Try to install

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend:

### Client configuration
Client version: 1.7.1 and 1.8.0

Operating system: OS X 10.10.2

OS language: English

Installation path of client: -

### Logs
          14.02.15 22:07:52.839 Installer[49922]: The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.

2. Web server error log: none

3. ownCloud log (data/owncloud.log): none

**Comment by danimo** [comment]
Do you have any "non-standard" disk configuration perhaps?

**Comment by sebastiennoir** [comment]
I don't think so :
Hardware Overview:

  Model Name:	Mac Pro
  Model Identifier:	MacPro5,1
  Processor Name:	6-Core Intel Xeon
  Processor Speed:	2.66 GHz
  Number of Processors:	2
  Total Number of Cores:	12
  L2 Cache (per Core):	256 KB
  L3 Cache (per Processor):	12 MB
  Memory:	16 GB
  Processor Interconnect Speed:	6.4 GT/s
  Boot ROM Version:	MP51.007F.B03
  SMC Version (system):	1.39f11
  SMC Version (processor tray):	1.39f11
Main disk : 
Xeon:

  Available:	23.27 GB (23'270'522'880 bytes)
  Capacity:	499.42 GB (499'418'030'080 bytes)
  Mount Point:	/
  File System:	Journaled HFS+
  Writable:	Yes
  Ignore Ownership:	No
  BSD Name:	disk0s2
  Volume UUID:	DE5761F8-37FC-3A06-B77D-BE5FC5681E09
  Physical Drive:
  Media Name:	APPLE SSD TS512C Media
  Medium Type:	SSD
  Protocol:	SATA
  Internal:	Yes
  Partition Map Type:	GPT (GUID Partition Table)
  S.M.A.R.T. Status:	Verified

**Comment by guruz** [comment]
I can not reproduce this with a nightly from http://download.owncloud.com/desktop/daily/ and installing oC onto an SD card that is default-mounted at ```/Volumes/.../```
The oC client lands properly in ```/Volumes/.../Applications/owncloud.app```
