### ISSUE TITLE
Version 1.8.0 potential packaging dep issue

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#2844]
Install owncloud-client (non-qt5 version) on openSUSE Factory from the isv:ownCloud:community:testing repository.

These are the installed packages:
```
S | Name                 | Type    | Version         | Arch   | Repository                    
--+----------------------+---------+-----------------+--------+-------------------------------
i | libowncloudsync0     | package | 1.8.0~beta1-1.3 | x86_64 | isv:ownCloud:community:testing
i | owncloud-client      | package | 1.8.0~beta1-1.3 | x86_64 | isv:ownCloud:community:testing
i | owncloud-client-l10n | package | 1.8.0~beta1-1.3 | x86_64 | isv:ownCloud:community:testing
```

However I cannot start the client:
```
owncloud: error while loading shared libraries: libocsync.so.0: cannot open shared object file: No such file or directory
```

@dragotin last week I told you that the client worked for me, but today I noticed that I had "libowncloudqt5sync0" from "isv:ownCloud:desktop" still installed. I soon as I manually removed it, the client stopped working.

I think something might be wrong in the package dependencies / libraries. I'd expect "owncloud-client" from the non-qt5 version to not load the qt5 libraries (even if not explicitly required by the package).

CC @jnweiger

**Comment by PVince81** [comment]
Huh...hmmm what?!

I just uninstall "owncloud-client" and all occurrences of "libowncloud*sync0" then installed "owncloud-client" again, then it worked.

I suspect that having "libowncloudqt5sync0" and at the same time "libowncloudsync0" installed had file conflicts. Should these packages be made to exclude each other ?

**Comment by dragotin** [comment]
@PVince81 yes, indeed they should exclude each other. However, its probably best to change the build of the client to use Qt5 if available, and do not have the qt5 package.

**Comment by dragotin** [comment]
The normal client package from 1.8.0 on will use qt5 as available on the distribution. So this problem does not happen any more. The testing repository already contains the packages to test.
