### ISSUE TITLE
Syncronisation of small html-files fails over and over again.

### ISSUE THREAD

**Issue by Rocologo** [owncloud/client#2846]
Each time I syncronise my ownCloud files the client fails to syncronise the same files over and over again. The error description is: "Could not read response body; connection closed by server"

Its about 10 html files and they only contain one XML tag and it is the same tag in all the files! 

![mediadrm cryptosession html -owncloud-development-sdk-docs-reference-android-media - gedit_004](https://cloud.githubusercontent.com/assets/1008133/6227518/1ef5ff08-b6a1-11e4-8de1-345a87b4f695.png)
![owncloud_005](https://cloud.githubusercontent.com/assets/1008133/6227520/221c5cfe-b6a1-11e4-9dc2-98ddf846ec20.png)

My OS is Linux Mint 17.1, The ownCloud client is 1.7.1 and the ownCloud server is 7.0.4

**Comment by dragotin** [comment]
I can not reproduce that against owncloud server 8. @lmaestro can you check with an ownCloud 7 server? @PVince81 does that ring something for you? Apache mis-configuration?

**Comment by PVince81** [comment]
@Rocologo are you using encryption ?
Do all the files receive the exact same size or different sizes ?

**Comment by lmaestro** [comment]
I can't reproduce it against owncloud server 7 neither 8, using encryption and without it. 
@Rocologo if you want to try using the latest version, it's a beta version so please make a backup https://owncloud.org/install/#testing

**Comment by Rocologo** [comment]
No Im not using encryption and I can easily reproduce it, because it happens all the time.

**Comment by Rocologo** [comment]
I have now 1.8.0 Beta now, but it still fails.
![owncloud_006](https://cloud.githubusercontent.com/assets/1008133/6336460/07c84154-bba3-11e4-914b-bf023218b757.png)

**Comment by Rocologo** [comment]
I just grabbed a log when the error happens

![owncloud_007](https://cloud.githubusercontent.com/assets/1008133/6336687/a90c6300-bba4-11e4-9eae-f48862813c87.png)

I have placed the logfile here: 
https://dl.dropboxusercontent.com/u/36067670/owncloud/owncloud_error_23_02_2015_21_42

**Comment by guruz** [comment]
@Rocologo Are you saying only files with exactly this content fail?
But others suceeded?

**Comment by Rocologo** [comment]
Yes. All 10 files has the same content and fails. All other files are syncroniced. I syncronize ~ 200.000 files.

**Comment by ogoffart** [comment]
"Connection Closed" means that the remote server is closing the connection.
Perhaps there is a proxy that closes the connection.
Which HTTP server are you using, is there a proxy in between?  

(the dropbox link is not valid anymore)

**Comment by guruz** [comment]
If only files with the contents of the above screenshot fail I'd suspect a server configuration issue (weird compression, pagespeed or whatever modules? weird rewrite rules?)

**Comment by Rocologo** [comment]
1) There is no proxy, I only NAT through my firewall.

2) I don't do network compression. 

3) I don't know what you mean with "pagespeed"?

4) My nginx configuration is copied from examples I found on the Internet. I will find my configuration and post it, so you canncan tell if it is wierd?

**Comment by Rocologo** [comment]
I can see my nginx configuration is heavy its copied from the internet when my NAS software changed from Apache to Nginx and I had to get it up and running, without really understand Nginx. I might have made a bug???
 
server {
    listen [::]:8443 default_server ipv6only=off ssl deferred;
    ssl_certificate /etc/ssl/certs/openmediavault-e462d7d4-28ae-419c-a1f8-2f138$
    ssl_certificate_key /etc/ssl/private/openmediavault-e462d7d4-28ae-419c-a1f8$
    server_name owncloud;
    root /var/www/owncloud;
    index index.php;
    autoindex off;
    server_tokens off;
    sendfile on;
    large_client_header_buffers 4 32k;
    client_max_body_size 10G;
    error_log /var/log/nginx/owncloud_error.log error;
    access_log /var/log/nginx/owncloud_access.log combined;
    rewrite ^/caldav(.*)$ /remote.php/caldav$1 redirect;
    rewrite ^/carddav(.*)$ /remote.php/carddav$1 redirect;
    rewrite ^/webdav(.*)$ /remote.php/webdav$1 redirect;
    error_page 403 /core/templates/403.php;
    error_page 404 /core/templates/404.php;
    location = /robots.txt {
        allow all;
        log_not_found off;
        access_log off;
    }
    location ~ ^/(data|config|\.ht|db_structure\.xml|README) {
        deny all;
    }
    location / {
        # The following 2 rules are only needed with webfinger
        rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
        rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json$
        rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
        rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;
        rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;
        try_files $uri $uri/ index.php;
    }
    location ~ ^(.+?\.php)(/.*)?$ {
        try_files $1 = 404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$1;
        fastcgi_param PATH_INFO $2;
        # The following 2 rules are only needed with webfinger
        rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
        rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json$
        rewrite ^/.well-known/carddav /remote.php/carddav/ redirect;
        rewrite ^/.well-known/caldav /remote.php/caldav/ redirect;
        rewrite ^(/core/doc/[^\/]+/)$ $1/index.html;
        try_files $uri $uri/ index.php;
    }
    location ~ ^(.+?\.php)(/.*)?$ {
        try_files $1 = 404;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$1;
        fastcgi_param PATH_INFO $2;
        fastcgi_param HTTPS on;
        fastcgi_param PHP_VALUE "upload_tmp_dir = /media/ea21f108-b011-4381-9bf$
        fastcgi_pass unix:/var/run/php5-fpm-openmediavault-owncloud.sock;
        fastcgi_buffers 64 4K;
    }
    location ~* ^.+\.(jpg|jpeg|gif|bmp|ico|png|css|js|swf)$ {
        expires 30d;
        access_log off;
    }
    # PFS (Perfect Forward Secrecy)
    ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
    ssl_prefer_server_ciphers on;
    ssl_ciphers EECDH+ECDSA+AESGCM:EECDH+aRSA+AESGCM:EECDH+ECDSA+SHA384:EECDH+E$
}

**Comment by guruz** [comment]
Sorry, I suggest to ask on the forum if anyone has an idea.

**Comment by Rocologo** [comment]
Well, I can't see why rewrites should interact with syncronizeation of small files???

**Comment by Rocologo** [comment]
I have good news.
1) I compared my Nginx configuration with the example on www.owncloud.org. I was very close and no special rewrites or so...
2) I updated ownCloud 7 to owncloud 8, and now the files seems be syncronised...
