### ISSUE TITLE
Local data is removed when you sign in an empty server 

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2847]
### Expected behavior
 A dialog should be opened asking you if you want to remove all the files or upload them.

### Actual behavior
Local data is removed without asking

### Steps to reproduce

1. Sync your account in your local folder 
2. For some reason the data is removed from the server (delete the account and create it again)
3. The client is disconnected 
4. Connect the client agin (Sign in )

### Client configuration
Version 1.8.0-beta1

Operating system: Windows 8.1 and OS X 10.10

### Logs

https://gist.github.com/lmaestro/25f308f79b46641ea634

**Comment by lmaestro** [comment]
cc/ @ogoffart

**Comment by dragotin** [comment]
To prevent this we should store the fileid of the remote directory and compare before syncing. if it changed, something is wrong -> user question.

But no regression.

**Comment by lmaestro** [comment]
Fixed in version1.8.0-nightly20150218 (build 2033).
Now this pop-up is shown :
![screen shot 2015-02-18 at 2 39 39 pm](https://cloud.githubusercontent.com/assets/4689430/6248325/d7862a06-b77e-11e4-9db0-283f3499c2a0.png)
