### ISSUE TITLE
Interface quirks in desktop sharing dialogue/workflow

### ISSUE THREAD

**Issue by plages** [owncloud/client#2850]
In the Windows client when you right click and choose share with ownCloud, the screen that appears contains the "Share link" checkbox. I have to click it in order to be able to share the selected file/folder. In my opinion a checkbox  represents a choice so in this case it should not be there. Because if don't check it nothing will happen.

Furthermore i think the dialogue should contain "OK" and "Cancel" buttons. The OK button should launch a concept message in the default mail client or a webform which generates an e-mail according to the sharing template. 
The cancel button should undo the share.
Currently when i click the red X to cancel my sharing action, the file/folder still shows up as being shared in the web interface.

**Comment by dragotin** [comment]
@jancborchardt your turn please. 

I agree, the dialog needs at least a close button (if we do stay with the checkbox), but I also tend to agree that a checkbox is not optimal here. But how would we do it if we want to avoid the checkbox?

**Comment by plages** [comment]
I can imagine that the client would only provide share by link functionality. 
But in that case the checkbox can be removed and the actions invoked by the checkbox would then be invoked upon right clicking "Share with ownCloud". The easiest solution then would be to have the default mail client open an e-mail with the sharing link when the user clicks OK. The advantage of this is that te user can enter any message they want in the interface they know with their own signature, stationary and/ow disclaimer. Also contrary to the web interface the e-mail can be found in the users sent items folder and can be archived. I think this would provide a beautiful solution/workaround to a number of existing feature requests.

**Comment by rullzer** [comment]
The check box is there because initially we also had user and group sharing from the dialog. And we should have that again as soon as we get a list of possible share candidates from the server, which will hopefully be available in the 8.1 server. 

I think an OK button is a good idea. However, a cancel button is getting ourself in trouble since it suggest we can undo all changes. Assume we click share and the link is already shared and password protected, now you change the password but click cancel. We have no way of restoring the original password simply because we do not know it.

**Comment by plages** [comment]
Having user and group sharing as well would be great. In that case I would advise to mimic the web sharing dialogue. For the time being is think the checkbox should be removed to avoid confusion. The check box initially led me to believe user and group sharing was available.
The cancel button i.m.h.o. would simply cancel the whole dialogue and undo the whole sharing. Just like one would expect from a cancel button in any dialogue. Thus in the example you describe above the link (and it's password) would be removed completely.

**Comment by MegaV0lt** [comment]
I like the idea to have an "Mail" button in the share dialog as well as an button "Copy to clipboard. In my opinion two basic feeatures.

**Comment by plages** [comment]
I'm not shure if i'm stuffing too many issues in one topic here but i have a an opinion about fucntionality of the checkbox too.
I discovered that once a file/folder is shared the checkbox is already checked when you choose "Share with ownCloud" from the right click menu. unchecking ik also unshares the file/folder. While i think the idea of being able to unshare from the dialogue is great, I'm wondering how i can share a folder with different people, with different passwords and/or expiration dates.
In the web interface i can endlessly reshare a file/folder to different people each with different passwords and/or expiration dates. Shouldn't this be possible in the desktop client.
Shouldn't the desktop client show a clean dialogue each time it is invoked? Ofcourse the scenario with different users/passwords/expiration dates presents a new problem to the idea of unsharing.
If an unshare button/checkbox/option is provided, the user will heave to be presented a list of shares from which he/she can choose which one to undo.

**Comment by jancborchardt** [comment]
@plages 
> In the web interface i can endlessly reshare a file/folder to different people each with different passwords and/or expiration dates.

No, this is not possible.

**Comment by plages** [comment]
Ah i checked and (ofcourse) you're right. I can endlessly reshare the link but when the password and/or expiration date changes it it changed for all previous recipients of the link as well. Although this makes perfect sense technically i think that a warning of sorts should pop up when this happens because it could block out previous recipients of the share. the same goes for unsharing by unchecking the ckeckbox. I don't think users are aware that the are completely unsharing the file/folder. but besides that please ignore my previous post.

**Comment by jancborchardt** [comment]
@plages it has been like that since a few versions / years now and we haven’t ever had any reports of confusion about this.

**Comment by plages** [comment]
ok to be honest i've been using oc since version 5 and i've never run into any problems. But i never use passwords an usually i set expiration dates quite far into the future.
anyway  i agree development energy is probably spent better elsewhere.

**Comment by jancborchardt** [comment]
@plages good to hear that. :) But also good to always re-evaluate if we are doing it right.

**Comment by rullzer** [comment]
So, like I said adding the OK button is not that hard. And probably makes sense.

I'm still not sure if adding a cancel button is the right way to go since I think it should just cancel my edits and not remove a share if it already existed. @jancborchardt do you have an oppinion on this?

I'll look into a way to invoke your e-mail client to send an e-mail.

**Comment by plages** [comment]
Although it makes sense not to cancel an already existing share, i really think something should clarify the fact that as long as the checkbox is checked, the share is retained. Because while there's no cancel button there is a red X on the top right of the dialogue that suggests cancel functionality.
Retaining the settings makes sense for en existing share but it doesn't for a new 'unfinished' share.

suggestions:
-   labeling the checkbox 'share/unshare' 
Or
-   creating two context menu items in stead of one
      - 'share with ownCloud'
      - modify ownCloud Share
Or
a warning dialogue upon clicking cancel/the red X if the checkbox is checked.
personally i think the first one is the least intrusive

**Comment by dragotin** [comment]
I think the dialog should have a close button. I will add it and also change the label of the dialog as suggested by @plages

**Comment by plages** [comment]
I noticed that the desktop sharing takes over the default expiration time from the server. Which makes perfect sense to me. Does anyone agree therew should be feedback about this the first time i create a share? When i click 'Share with ownCloud'the second time on a share, the expiration date and the 'Set expiration data'checkbox are automatically populated. Maybe upon initial creation of the share someting like 'Default expiration time of %serversetting% applies' should appear in the dialogue. Or else the dialogue should display the same behaviour as when clicked for the second, third etc. time

**Comment by dragotin** [comment]
I enhanced the GUI a bit and added a close button  with the mentioned commit above.

**Comment by plages** [comment]
i'm assuming this will be in the next nightly build. As you can see i added some comments to this issue. Is this OK or should i create a new issue. I think it's all kind of interface polish.

**Comment by dragotin** [comment]
@plages yes, please open a new issue. Thanks for your help!

**Comment by plages** [comment]
@dragotin 
Tested and it's much clearer this way. But i think the checkbox should be checked by default as long as user/group sharing is not available. Why should the user have to click when we know beforehand the checkbox will have to be checked?

**Comment by lmaestro** [comment]
Fixed in version 1.8beta2.
