### ISSUE TITLE
Configurable "Host" in URL for generated sharing URLs

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#2855]
### Expected behaviour
When sharing files from desktopclient the lokal path of oc is used (eg. sheevaplug).
![2015-02-18 08_29_33-owncloud](https://cloud.githubusercontent.com/assets/2804301/6243747/d5eb1ec6-b748-11e4-8305-0e005d51a7b7.jpg)
__Should be possible to set the domain (eg. Darkwing.dyndns.org) that is reachable from outside!__
![2015-02-18 08_28_21-owncloud-freigabe](https://cloud.githubusercontent.com/assets/2804301/6243730/65a82230-b748-11e4-9d4a-a3b51cb5aaa3.jpg)

### Actual behaviour
It uses local domain. Every time i share a link i have to manualy edit:
![2015-02-18 08_28_21-owncloud-freigabe](https://cloud.githubusercontent.com/assets/2804301/6243730/65a82230-b748-11e4-9d4a-a3b51cb5aaa3.jpg)

### Steps to reproduce
1. Set up oc on local network
2. setup oc client on local network and use the local domain (hostname)
3. share a file via oc desktopclient

### Server configuration
Operating system: Debian 7.8

Web server: Apache 2

Database: MySQL

PHP version: 5.3...

ownCloud version: 8.0 stable

Storage backend: Sheevaplug (ARMv5) 

### Client configuration
Client version: 1.8beta

Operating system: Windows 7

OS language: German

Installation path of client: C.\Prog...

**Comment by pierrejochem** [comment]
Bad question, but why didn't you use the dyndns hostname in your client config?

**Comment by MegaV0lt** [comment]
Because of traffic. i think is better to use local name to not have the data routet over online. 
benefit 1: if you have a trafic limit, it is not used because transfer is local
benefit 2: if you have a defect dslline oir other issues it is still working, because the server is local.

**Comment by nekoal** [comment]
You always can edit local host file to link external server hostname to local ip address. But modern browsers have protection (HTML5 standart recomendations) which prevents access to local network from others domains. I don't know have owncloud such protection or not.

**Comment by MegaV0lt** [comment]
So the solution would be make it configurable. Should be easy to make an option in the client to override the lokal hostname.

**Comment by pierrejochem** [comment]
Because of traffic? You can add the dyndns hostname to your internal DNS Server and point it to the private IP. Then it is a local access ;-)

**Comment by MegaV0lt** [comment]
Where do i have to do this? i have a FritzBox 7270 (AVM) doing DHCP in my local network
Are you sure every home router is able to do that mapping?
Maybe ther should be a documentation for users like me that do not know too much about network...

**Comment by danimo** [comment]
@MegaV0lt The feature is called "hairpin NAT" and all good routers, including the fritz box, support it. The downside is that all traffic is being routed through the router.

The problem with supporting multiple addresses is that there is no safe way of detecting "your" home network. Usually people won't bother with HTTPS in their LAN, which makes it worse.

Anyway, the long term fix is IPv6.

**Comment by MegaV0lt** [comment]
I do not need that it wil be detected automaticly. i would wish to have an option wich allows me to override that local hostname.
you can make it an "exper" funktion with a warning text for exapmple. 
or make it an option to put in .ini file only (if available)

i am not sure how many oc installs a "local". But for all the local installations it is a good option in my view. You can make that option hidden if you want, so the user firsdt must agree (checkmark) that is visible

**Comment by guruz** [comment]
@LukasReschke @rullzer Maybe the full URL should be generated server-side and returned to the client?
(not sure which other things it breaks though..)

**Comment by rullzer** [comment]
@guruz that is what is happening when you use 8.2 ;)
