### ISSUE TITLE
[Windows] Share dialog - Use icon in context-menu

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#2856]
### Expected behaviour

if i use teh contextmenu from occlient i should get a menu with a oc icon
### Actual behaviour

there is no icon to see
![2015-02-18 08_41_33-](https://cloud.githubusercontent.com/assets/2804301/6243818/07c70c42-b74a-11e4-8924-6e2e9185dcaa.jpg)
### Steps to reproduce
1. install oc client 1.8 beta
2. right click in local oc folder a file 
3. context menu is showing no icon
### Client configuration

Client version: 1.8beta

Operating system: Windows 7

OS language: German

Installation path of client: default

**Comment by SamuAlfageme** [comment]
Closing as duplicate in favor of #2975
