### ISSUE TITLE
Deleting files and emptying trashbin not possible!

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#2858]
#### What users do:
1. users have large folders with a few thousands files
2. they try to delete folders in the client and it takes "forever"
3. they receive timeout after waiting "forever"

#### what happens after that:
1. files are deleted on the desktop client
2. files are NOT deleted in the web browser
-> files are still visible in the web browser

problems which occur after that:
1. files_trashbin folder is getting bigger and bigger because SAME files are being deleted over and over again but they are not removed from their original folder
2. users have over a million files in then files_trashbin folder
-> effect: trashbin cannot be used anymore
3. they are not able to remove files from trashbin folder anymore
-> every click on trashbin icon (in web browser) takes forever

4. now, for these users, deleting even a single file causes same
problem again:
-> file is basically never delete from folder
-> file is visible in the folder
-> file IS in trashbin TOO
-> it comes to timeout (see client log below)

this is one of these accounts:

cloud@server:~/html/data/user@SERVERNAME.COM $ du -sh *
331M cache
6.4G files
878G files_trashbin
494M files_versions
4.1M gallery
238M thumbnails

as you can see, their files_trashbin (878G) folder is big and it is
getting bigger and bigger because now deleting even a single file is not
possible and there are hundreds of copies of the same file in the
trashbin but the file is still not removed from the original folder.

one example of current behavior of this problem:

1. user uploaded file workflow_a0_sav.indd
2. user deleted this file
3. deletion takes forever
4. file is still visible in the original folder
5. there are currently 112 same copies of this deleted file in files_trashbin/files:

$ ls -l files_trashbin/files/workflow_a0_sav.indd* | more
-rw-r--r-- 1 cloud cloud 483328 Feb 14 19:33 workflow_a0_sav.indd.d1424038944
-rw-r--r-- 1 cloud cloud 483328 Feb 14 19:33 workflow_a0_sav.indd.d1424039258
-rw-r--r-- 1 cloud cloud 483328 Feb 14 19:33 workflow_a0_sav.indd.d1424080319
-rw-r--r-- 1 cloud cloud 483328 Feb 14 19:33 workflow_a0_sav.indd.d1424080661
-rw-r--r-- 1 cloud cloud 483328 Feb 14 19:33 workflow_a0_sav.indd.d1424080998
-rw-r--r-- 1 cloud cloud 483328 Feb 14 19:33 workflow_a0_sav.indd.d1424081337
-rw-r--r-- 1 cloud cloud 483328 Feb 14 19:33 workflow_a0_sav.indd.d1424081647

$ ls -l files_trashbin/files/workflow_a0_sav.indd* | wc -l
112

#### WHAT CAN WE DO?

1. can we delete all files (from the affected users) from files_trashbin on the command line:
```
$ cd files_trashbin/files
$ rm -rf *
```
we did that once on v6.0.3 and user was not able to open trashbin anymore.

2. if this is not a recommended/possible way to do this, what should we do?

### Log
```
19:57 Poster/e-Infra/workflow_a0_sav.indd SERVERNAME Could not read status line: connection timed out
19:47 Poster/e-Infra/workflow_a0_sav.indd SERVERNAME Could not read status line: connection timed out
19:36 Poster/e-Infra/~workflow_a0~f-5cl).idlk SERVERNAME Could not read status line: connection timed out
19:31 Poster/e-Infra/workflow_a0_sav.indd SERVERNAME Could not read status line: Connection reset by peer
19:21 Poster/e-Infra/workflow_a0_sav.indd SERVERNAME Could not read status line: connection timed out
19:10 Poster/e-Infra/workflow_a0_sav.indd SERVERNAME Could not read status line: connection timed out
19:00 Poster/e-Infra/workflow_a0_sav.indd SERVERNAME Could not read status line: connection timed out
18:49 Poster/e-Infra/workflow_a0_sav.indd SERVERNAME Could not read status line: connection timed out
18:38 Poster/e-Infra/workflow_a0_sav.indd SERVERNAME Could not read status line: connection timed out
18:28 Poster/e-Infra/workflow_a0_sav.indd SERVERNAME Could not read status line: connection timed out
18:17 Poster/e-Infra/workflow_a0_sav.indd SERVERNAME Could not read status line: connection timed out
18:12 Poster/e-Infra/workflow_a0_sav.indd SERVERNAME Could not read status line: connection timed out
18:06 Poster/e-Infra/workflow_a0_sav.indd SERVERNAME Could not read status line: connection timed out
18:00 Poster/e-Infra/workflow_a0_sav.indd SERVERNAME Could not read status line: connection timed out
```
### Client Version
1.7.0 (build 1385)
### Server Version
7.0.3.4

@MorrisJobke 

00002612

**Comment by danimo** [comment]
This is a server issue (deleting to trash is a copy, not a move in older versions) and fixed by upgrading to ownCloud 8.

**Comment by cdamken** [comment]
@MorrisJobke  If the fix is in oC8 is there a possiblitity to backport to oC7?

**Comment by MorrisJobke** [comment]
This is the PR that fixes this: https://github.com/owncloud/core/pull/13377

**Comment by MorrisJobke** [comment]
@cdamken I commented over there https://github.com/owncloud/core/pull/13377#issuecomment-75213136
