### ISSUE TITLE
Windows client path length issue?

### ISSUE THREAD

**Issue by zephyrus00jp** [owncloud/client#2860]
I am not sure if this is a "bug".

But let me report an issue that plagued me for the last several months.
Due to the sensitivity of the path name (that will reveal the parties involved which shall remain anonymous.), I cannot describe the path name exactly below
Suffice it to say that I received a data in USB memory stick some time ago and put them into
a local PC directory. The files and directories have rather longish names consisting of
a confernece/meeting and the author and his/her affiliations and time/date of the meeting, etc.

1. I then put the file into the directory managed by owncloud.
    Note: I am not exactly sure how I did it. I think I put the file into a local PC directory
    from which it is uploaded by windows client eventually into owncloud server that runs on linux.
    However, then, this is in contradiction to the issue I describe below.
    Maybe the windows client -> server may not see the path length issue.
   Or it may be that the early version of windows client did not have the issue below.

2 Anyway, after a few months of use, last summer, I noticed a persistent error of
windows owncloud client saying that  a certain file's path is not found in the Activity window.
When that message is visible in Activity window, there is a cross on the windows owncloud icon in the task tray that seems to indicate there was an error.

However, when I checked the path, the path seems to exist.
(And I don't *think* I had seen the error earlier..)

To make a long story short, I figured that it is a path length problem under windows.
By forcing the renaming of the long path name (including the intermediate directory path name, and the filename itself.) to a shorter one on linux owncloud server, 
I could remove the "path not found" error message displayed by windows client,  and windows client
synched the renamed files and all is well now.

Re rather limiting file path length under windows:
I noticed that there is a discussion of rather shorter limit of path length to 
some windows API regarding the handling of such file path in mozilla firefox/thunderbird bugzilla.mozilla.org.
This made me suspicious that the false error message  of  "path not found" actually
refers to the error of opening a long file path name under windows, and the forced renaming on
linux owncloud server side eliminated the error.

I think windows client ought to report this "too long pathname" failing some file I/O API calls
correctly instead of "path not found".

Thank you for the great package and I hope my report here makes it more user-friendly
under windows.

TIA

**Comment by nekoal** [comment]
It looks related to MAX_PATH. See more here #60.

**Comment by danimo** [comment]
Yes, duplicate.
