### ISSUE TITLE
Use Desktop Sharing OS X - Extension on 10.10

### ISSUE THREAD

**Issue by stonerl** [owncloud/client#2861]
I just tested the latest nightly-build 2034 for OS X and was wondering if it would be possible to add the Desktop Sharing functionality as Share Menu or Finder Extension.

![screen shot 2015-02-18 at 21 31 59](https://cloud.githubusercontent.com/assets/2091312/6256101/9dee9f94-b7b5-11e4-9fb2-d1143f709e49.png)
![screen shot 2015-02-18 at 21 30 36](https://cloud.githubusercontent.com/assets/2091312/6256078/69cc43d8-b7b5-11e4-8659-1763d5003547.png)

**Comment by danimo** [comment]
This should work already, but we are not using the official OS X 10.10 API (in order to make it work on OS X <= 10.9), which is why it's not showing up in those lists.

In the future we are looking into supporting the official API when installing the client on 10.10.

**Comment by guruz** [comment]
Duplicate https://github.com/owncloud/client/issues/2340
