### ISSUE TITLE
templates cannot handle branding with 1.8.0beta1

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#2864]
Test build https://build.opensuse.org/package/show/isv:ownCloud:community:testing:testpilotcloud/testpilotcloud-client

generates a spec file with 

name: -client

After fixing this, I run into this error:

[   66s] CMake Error in src/gui/CMakeLists.txt:
[   66s]   Cannot find source file:
[   66s] 
[   66s]     /home/abuild/rpmbuild/BUILD/testpilotcloud-1.8.0beta1a/testpilotcloud/theme.qrc
[   66s] 
[   66s]   Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp

due to further down in the spec file: 

  -DOEM_THEME_DIR=$PWD/../testpilotcloud/ \

which should be 

    -DOEM_THEME_DIR=$PWD/../testpilotcloud/mirall/ \

**Comment by jnweiger** [comment]
Here is the full diff manually applied on testpilotcloud-client.spec to make it compile
<pre>
--- testpilotcloud-client.spec  (revision 3)
+++ testpilotcloud-client.spec  (working copy)
@@ -33,10 +33,10 @@
 ## prerelease, base_version, tar_version are the interface into buildpackage.pl
 ## used in rotor.o.c job owncloud-client-linux
 ## define prerelease as %nil, if this is not a prerelease.
-%define prerelease %nil
+%define prerelease beta1a
 %define base_version 1.8.0
 %define tar_version %{base_version}%{prerelease}
-Name:           -client
+Name:           testpilot-client
 
 %if 0%{?centos_version} == 600 || 0%{?rhel_version} == 600 || 0%{?fedora_version} || "%{prerelease}" == ""
 # For beta and rc versions we use the ~ notation, as documented in
@@ -319,7 +319,7 @@
   -DLIB_SUFFIX=64 \
 %endif
 %if "%{name}" != "owncloud-client"
-  -DOEM_THEME_DIR=$PWD/../testpilotcloud/ \
+  -DOEM_THEME_DIR=$PWD/../testpilotcloud/mirall/ \
 %endif
   %cmake_args
 
@@ -374,7 +374,7 @@
 %endif
 
 %if %{?suse_version:1}0
-%suse_update_desktop_file -n 
+## %% suse_update_desktop_file -n 
 %endif
 
 %check
</pre>

It still fails due to more places, where the brandname was not substituted.

**Comment by danimo** [comment]
Looks good, except it sometimes is desktopclient and sometimes mirall, depeding on the theme (just in general).

**Comment by dragotin** [comment]
I did some fixes to genbranding.pl, should work better now. @jnweiger we still need to test this!

**Comment by jnweiger** [comment]
Testcase started:
1) deleted project isv:ownCloud:community:testing:testpilotcloud
2) running the magic script ./setup_all_oem_clients.pl v1.8.0-beta1a isv:ownCloud:community:testing testpilotcloud https://api.opensuse.org isv:ownCloud:desktop

**Comment by jnweiger** [comment]
Looks good, except obs sometimes is so slow (just in general).

**Comment by dragotin** [comment]
This is fixed.
