### ISSUE TITLE
Send requested properties in PROPFIND, do not use allprops

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#2865]
SabreDAV only allows these properties to be returned:
https://github.com/fruux/sabre-dav/blob/master/lib/DAV/PropFind.php#L50

In past OC versions we hacked Sabre to also include "oc:permissions", "oc:size", etc.

We are now upgrading to Sabre 2.1 (https://github.com/owncloud/core/issues/12876) and would like to remove the hack (which is actually not possible to use any more due to code changes in SabreDAV).

Please update the mobile client to explicitly request the properties.
A PROPFIND request could send a body that looks like this:
```
<?xml version="1.0"?>
<a:propfind xmlns:a="DAV:" xmlns:oc="http://owncloud.org/ns">
<a:prop><a:getcontenttype/></a:prop>
<a:prop><a:getetag/></a:prop>
<a:prop><oc:permissions/></a:prop>
<a:prop><oc:size/></a:prop>
...
</a:propfind>
```

As an added bonus: note that if you only want the mtime, then just request "a:getlastmodified". This way the server doesn't need to do extra work for properties that you don't want :smile: 

Please double check whether all PROPFIND calls in the desktop client already do that.
While debugging I had the feeling that it was already working, but best is to double check :smile:

**Comment by ckamm** [comment]
While there is mention of "allprop" in PropfindJob::start() that is never used in practice as we always specify the desired properties explicitly. I'll remove that fallback and then this issue can be closed.
