### ISSUE TITLE
Multiple PROPFIND on root with different props

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#2866]
While debugging SabreDAV with the sync client 1.8.0~beta1 I noticed that the client does multiple PROPFINDs on the WebDAV root.

There seem to be three separate calls on the root for:
- "getlastmodified" alone
- "getetag" alone
- the quota properties

The access log shows 5 calls, I didn't dig into the other ones.

Maybe a few of these can be put together inside a single PROPFIND call ?

**Comment by ogoffart** [comment]
From the top of my head: the quota is a separate job because it is global to the account and not to a specific folder.   The getetag job is relative to the folder and is used to know if we should sync.
I don't know what the getlastmodified is for.

**Comment by PVince81** [comment]
I guess the quota + etag could be combined if both operate on the root, if technically possible (based on how the client architecture is done). Unless you guys want to display/update the quota value more frequently than the etag check.

**Comment by nekoal** [comment]
When all folders in my client paused (1.8.0-nightly20150213 (4715)) I see quota job every 31 seconds in log window. Client reports 575 Gb free space. I want display quota less frequently 'cause no way 575 Gb will be used in 31 seconds.

**Comment by guruz** [comment]
Sorry, this is a WontFix for now :) 
@ckamm had fixed something for reducing some superflous requests at startup, maybe that was not in beta1 yet.

**Comment by ckamm** [comment]
We do requests for
* etag per folder, to check for remote changes
* quota per account, to get the quota, doh
* getlastmodified per account, as heartbeat

The path of the etag job depends on the folder's configuration, it's not necessarily the root folder. We can't combine the quota/getlastmodified jobs because in some situations the server needs quite some time to reply to quota requests.

**Comment by PVince81** [comment]
CC @icewind1991 FYI

I wonder why the quota call would be talking that long.
One possibility is that sometimes it needs to recompute the file sizes (especially on a server where the size propagation takes time).

Well, I guess that makes sense for now. I understand.

**Comment by PVince81** [comment]
I suppose you could maybe cancel/defer the heartbeat job if another call has been done already ?
What I observed is that all three calls were made almost at the same time.
