### ISSUE TITLE
Transient file detected but deleted before it could be copied generates File not found error

### ISSUE THREAD

**Issue by ernesttk** [owncloud/client#2867]
Client version: 1.7.1
Platform OS: Windows 7

Condition for error: A process which creates short lived files in the ownCloud directory.
If these files are detected but deleted before they are copied, the user sees a baffling File not found error.

From the activity log (only relevant error line):
13:05     Documents/aftn.trunk/prodd/ww/AFTN_Gateway.lk1                  ownCloud       No such file or directory          

Error is not fatal. It corrects itself in the next round. The only problem is that the user has to deal with a baffling error he has not control over and cannot prevent.

It would be nice if this condition could be detected and ignore (or just in the activity log)

**Comment by guruz** [comment]
@ernesttk Does client 1.8rc1 change anything here?

I'm a bit worried about changing this as it might mask other real errors.

**Comment by ernesttk** [comment]
I tried client 1.8 stable and I haven't been able to reproduce this issue. I tried multiple compilation followed and cleanups in a cycle. So this is looking much better. Thanks!
Note: with version 1.7.1 the warning did not happen every time either. It could be that the issue is still valid but just less frequent. Still it's looking good.

**Comment by ckamm** [comment]
This was indeed fixed for 1.8.0 by 3253cc38b219b5aa39c03e8793de8426d97b426d as part of #1981
