### ISSUE TITLE
syncstatehelper/owncloud.socket floods the Mac OSX console.log

### ISSUE THREAD

**Issue by rboele** [owncloud/client#2868]
27-01-2015 15:47 Boelens, Rolf: 
Bug in Surfdrive.app (nightly). The SurfDrive.app (SURF, Netherlands) is based on OwnCloud.
When I install OwnCloud, same problem. The report here was for SURF, but since in OwnCloud as well I report it here: it will likely affect more Mac OSX users.

System: Macbookpro, osx 10.8.5, fresh install
Description: syncstatehelper/owncloud.socket writes each 5s the following to my console.log file
e.g.
26/01/15 09:44:00,151 Finder[167]: Connect Socket to file://localhost/Users/boelens/Library/Caches/SyncStateHelper/ownCloud.socket
26/01/15 09:44:00,161 Finder[167]: Socket DISconnected!
26/01/15 09:44:00,161 Finder[167]: ERROR: No such file or directory
26/01/15 09:44:00,162 Finder[167]: clearFileNameCacheForPath:
26/01/15 09:44:00,162 Finder[167]: repaintAllWindows

After deleting the files installed by Surfdrive-1.7.0.1510-nightly20141127.pkg and ~/Library/Caches/SyncStateHelper plus a reboot, the problem is solved.
I noted this on OSX 10.8.5, my colleague using OSX 10.10.2 notes the same.

Greetings, Rolf

More detail:
System: Macbookpro, osx 10.8.5, fresh install
Description: syncstatehelper/owncloud.socket writes each 5s the following to my console.log file
e.g.
26/01/15 09:44:00,151 Finder[167]: Connect Socket to file://localhost/Users/boelens/Library/Caches/SyncStateHelper/ownCloud.socket
26/01/15 09:44:00,161 Finder[167]: Socket DISconnected!
26/01/15 09:44:00,161 Finder[167]: ERROR: No such file or directory
26/01/15 09:44:00,162 Finder[167]: clearFileNameCacheForPath:
26/01/15 09:44:00,162 Finder[167]: repaintAllWindows

The folder ~/Library/Caches/SyncStateHelper is empty (there is no file: ownCloud.socket).

After deleting the files installed by Surfdrive-1.7.0.1510-nightly20141127.pkg the problem is solved

After (a lengthy search) I note that the 'nightly' install of SurfDrive makes use of ownCloud.
The Mac Finder reports the following files as source of the console messages:
/Library/ScriptingAdditions/SyncStateFinder.osax/Contents/MacOS/SyncStateFinder
/Library/ScriptingAdditions/SyncStateFinder.osax/Contents/Resources/SyncStateFinder.bundle/Contents/MacOS/SyncStateFinder

Some detective work: these files agree in date (27/11/2014 13:56) with the files SyncStateFinder.osax from Surfdrive-1.7.0.1510-nightly20141127.pkg.

These files are very similar (the 'same') in SurfDrive.app and ownCloud.app. 
Latest OwnCloud van https://owncloud.com/download/#1, ownCloud-1.7.1.1655.pkg
contains files dates 18/12/2014 12:58.

When I install Owncloud.app (with a more recent SyncStateFinder.osax) initially the issue appears solved. When I removed this OwnCloud.app I get the same problem with each 5s ERROR on the console.log. 

When I delete all (surfdrive.app, owncloud.app, SyncStateFinder.osax AND ~/Library/Caches/SyncStateHelper) and reboot the Mac, the Log file remains clean.

I installed an older version of Surfdrive.app (1.6.3) now, that does not install SynStateHelper, now it stays OK.

**Comment by danimo** [comment]
@jturcotte this was fixed for 1.8, right?

**Comment by rboele** [comment]
it looks like the problem was solved, just tried on my Mac (osx 10.8.5), ownCloud-1.8.0.2014beta1.pkg
from https://owncloud.org/install/#testing

no console.log flooding anymore, at least for owncloud,
hope it will soon appear in a coming version of surfdrive as well

rolf

**Comment by rboele** [comment]
comment added:

it looks like the problem was solved, just tried on my Mac (osx 10.8.5), ownCloud-1.8.0.2014beta1.pkg

from https://owncloud.org/install/#testing

thx, rolf
