### ISSUE TITLE
Missing copyright header for some files in 1.8.0beta1

### ISSUE THREAD

**Issue by hefee** [owncloud/client#2869]
there are some files without a copyright header:
* src/gui/addcertificatedialog.cpp
* src/gui/addcertificatedialog.h
* src/gui/sharedialog.cpp
* src/gui/wizard/owncloudconnectionmethoddialog.cpp
* src/gui/wizard/owncloudconnectionmethoddialog.h

**Comment by dragotin** [comment]
@rullzer @nocteau @jdhoek please add your emails and names if you want.

**Comment by jdhoek** [comment]
@dragotin 
Sure. Just to verify: I consider my contribution to be utterly trivial, I take it you agree (so no Contributor Agreement needed right?).

**Comment by dragotin** [comment]
@jdhoek well, yes, yet, it might be better to send one in if you don't mind. Puts us all on the save side.

**Comment by jdhoek** [comment]
Not at all. Will do.

The files I've contributed were amended by others afterwards, should I submit a PR with the (now missing) default header as used in other files with just my name on it?

**Comment by rullzer** [comment]
done :)
