### ISSUE TITLE
Request for enhancment: Windows installer does not explain why creation of  qt5webkit.dll failed. 

### ISSUE THREAD

**Issue by zephyrus00jp** [owncloud/client#2870]
Hi, 

Thank you for the great package.

I have encountered a problem  while I tried to install Windows client on three Windows 7 PCs.

On a single PC, the installer fails with creation of qt5webkit.dll and  no 
meaningful  additional error message. I checked and there is 0-octet size qt5webkit.dll in
the installation directory.
On two other PCs there was no problem.

I searched the forum and searched the web, but I had no clue.

To make a long story short, I found out that I set the TEMP directory of the particular PC to a separate partition and that partition was filled up and did not have enough room to hold the qt5webkit.dll during uncompression.

It would be very nice that the Windows installer can
post a more easier to understand message when a problem like this occurs.
(Maybe it can simply pass the message generated by lha or unzip or whatever it uses underneath for uncompression?)
If the installer is a third party software, maybe it is a good idea to forward this post to the authors.

It took me several days to figure this out and I could not use owncloud  during that period :-(

Otherwise owncloud is working fine except for the issue  #60.

TIA

**Comment by dragotin** [comment]
As we use the NSIS installer framework for windows, I think that would be worth a bug report upstream in that project. We're not so much in that here.

**Comment by zephyrus00jp** [comment]
On 2015/02/25 23:36, Klaas Freitag wrote:
> Closed #2870 <https://github.com/owncloud/client/issues/2870>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/2870#event-241728774>.
>

I filed a bug report to NSIS installer's bug tracker.

TIA
