### ISSUE TITLE
sync doesn't start when the location of folders is on other partition on hard drive.

### ISSUE THREAD

**Issue by Nikhilkumar13** [owncloud/client#2871]
I am using owncloud desktop client version 1.7 on ubuntu 14.04.My owncloud folders which are meant for sync are on other(other than on what my OS is) partition on hard drive.whenever i start my system the sync doesn't start automatically.I have to once open that partition via some folder explorer.
So to make it work i have to restart owncloud client after opening that folder for once.

**Comment by ssieb** [comment]
The partition probably isn't mounted until you request it.  So the sync folder doesn't even exist when the owncloud client starts.  I suppose you could request that the client should check occasionally in that case.

**Comment by danimo** [comment]
Make sure your OS mounts the disk automaitcally:

http://ubuntuhandbook.org/index.php/2014/07/mount-partitions-automatically-ubuntu-14-04/
