### ISSUE TITLE
Confusing: 3 Add Folder buttons

### ISSUE THREAD

**Issue by Dominique-M** [owncloud/client#2873]
Experienced this in French but is the same in English.
In Settings, left menu Account, there is an (1) **Add Folder…** button at the upper right of the main panel. This means "begin here the process to choose one more folder to synchronize", and brings a Add Folder window to choose a local folder, with **Next** button. This brings a second Add Folder window to choose a destination folder. At the upper right a (2) **Add Folder** button happens to really mean "create a new destination folder if needed". At the bottom right a (3) **Add Folder** button does not mean "I want still another folder", but "I confirm the choice I made in the former window (local folder) and in the present window (destination)".
I not a specialist in GUI, but this is extremely confusing. In my opinion:
(1) Add Folder… is not too bad
(2) Add Folder should definitely be Create folder
(3) Add Folder, I leave to GUI specialists the choice between OK, Confirm or whatever.

**Comment by Dominique-M** [comment]
(2) Add Folder comes from images of the online documentation for client 1.7. Seems to be Create folder in real world.
The confusion between (1) and (3) remains.

**Comment by ogoffart** [comment]
Fixed by #2371
