### ISSUE TITLE
legitimate clients poking unauthenticated: PROPFIND gives 401

### ISSUE THREAD

**Issue by r-daneel** [owncloud/client#2875]
Since 15 Feb 2015, I am seeing oc clients poking at my server unauthenitcated.
This happens about once an hour per folder:
X.X.X.X - - [15/Feb/2015:12:11:21 -0500] "PROPFIND /owncloud/remote.php/webdav/documents HTTP/1.1" 401 6138 "-" "Mozilla/5.0 (Linux) csyncoC/0.91.5 neon/0.29.6"

These clients otherwise perform correctly authenticated request as these:
X.X.X.X - valid_user [15/Feb/2015:12:15:09 -0500] "PROPFIND /owncloud/remote.php/webdav/documents HTTP/1.1" 207 6362 "-" "Mozilla/5.0 (Linux) mirall/1.7.1"

It's as if the client got a token that expired and the 401 triggers a token renewal.

Is this the expected behaviour ?

Clients are Linux/Ubuntu12.04/14.04, Server is Linux as well

**Comment by dragotin** [comment]
Yes, that is expected, the session has a timeout, which is (AFAIR) configurable. Please seek for help (if needed) in forum, mailinglist or IRC. Thanks.
