### ISSUE TITLE
Files got deleted from a Shared folder without user interaction

### ISSUE THREAD

**Issue by mzaian** [owncloud/client#2876]
### Expected behaviour
The files should not be deleted

### Actual behaviour
My manager reported that some files "video & pdf" got deleted from a folder that  shared to him with full access, i reviewed the apache log files of owncloud and saw the actions as below:-
[22/Feb/2015:08:29:32 +0200] "DELETE /remote.php/webdav/Path-To-Dir/Path-To-File.mp4 HTTP/1.1" 204 756 "-" "Mozilla/5.0 (Windows) csyncoC/0.91.5 neon/0.30.1"

### Server configuration
Operating system:
Ubuntu 14.04 x86_64
Web server: 
Apache2 2.4.7
Database:
MYSQL 5.5.41
PHP version:
PHP 5.5.9
ownCloud version:
7.0.3
Storage backend:

### Client configuration
Client version:
1.7.0.4162 
Operating system:
Windows 7 Professional 
OS language:
English
Installation path of client:
Default
### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
Did not start with logging when the issue occured
2. Web server error log:
[22/Feb/2015:08:29:32 +0200] "DELETE /remote.php/webdav/Path-To-Dir/Path-To-File.mp4 HTTP/1.1" 204 756 "-" "Mozilla/5.0 (Windows) csyncoC/0.91.5 neon/0.30.1"
3. ownCloud log (data/owncloud.log):
-

**Comment by rullzer** [comment]
So what is the bug here?

It seems somebody deleted the file from the shared directory which then, by design, removed it for everybody that had that folder shared with him/her.

**Comment by dragotin** [comment]
Yes, what @rullzer says is true: If somebody else (not your manager) removed it from the Share, the deletion is propagated to all the people syncing that share. 

Please double check and reopen this issue in case that was **not** the case here. Thanks.
