### ISSUE TITLE
[Client] [Share from Desktop] Make Link usable for showing images directly

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#2877]
Links shared from desktopclient do not show up if used in html. Example in a forum to integrate a picture that is hosted in ownclud. Example: 
This Picture
https://darkwing.ddns.net/owncloud/public.php?service=files&t=CLqI8iBWgdDHkTy

![GitHub Logo](/images/logo.png) Format: ![Alt Text](https://darkwing.ddns.net/owncloud/public.php?service=files&t=CLqI8iBWgdDHkTy)

No picture is shown. 

This is working when i use dropbox-link:
https://dl.dropboxusercontent.com/u/1490505/2015-02-18%2008_41_33-.jpg

![GitHub Logo](/images/logo.png)
Format: ![Alt Text](https://dl.dropboxusercontent.com/u/1490505/2015-02-18%2008_41_33-.jpg)

**Comment by RealRancor** [comment]
Ref for a generated link which allows this: https://github.com/owncloud/core/issues/8180#issuecomment-50626870

**Comment by dragotin** [comment]
Not very much the problem of the desktop client as the link is generated by server code. Best would be if you open this issue in the issue tracker of the core repo. Thanks.

**Comment by LukasReschke** [comment]
Link by @RealRancor explains why we can't add that at the moment… Let me *finally* get write that blog post ;-)

**Comment by dragotin** [comment]
Ah ok. Closing this here.
