### ISSUE TITLE
Error when file modification date is in the future: "Local file changed during sync", file is not synced

### ISSUE THREAD

**Issue by BrentNewland** [owncloud/client#2880]
### Expected behaviour
Owncloud should sync the file

### Actual behaviour
Owncloud does not sync the file

### Steps to reproduce
1. Change the modification date/time on a file to a future date/time
2. Move that file to an Owncloud synced folder
3. Check Owncloud client activity log - file will say "Local file changed during sync" and will not sync

### Server configuration
Operating system: Windows Server 2008 R2

Web server: nginx 1.5.10

Database: MariaDB 5.5.36.4095

PHP version: 5.5.11

ownCloud version: 8.0

Storage backend: ?

### Client configuration
Client version:1.7.1 b4382

Operating system:Windows 7 SP1 x64 all updates

OS language: en-US

Installation path of client: c:\program files (x86)\owncloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.5/troubleshooting.html#client-logfile ) https://gist.githubusercontent.com/anonymous/2471eb24a5693eaf00b6/raw/gistfile1.txt

2. Web server error log: empty

3. ownCloud log (data/owncloud.log): empty

**Comment by MegaV0lt** [comment]
There should ala a warning logged about filedate in future

**Comment by ryantollefson** [comment]
This bug also exists in desktop client 1.7.1 (build 4382).
For me, file was created in a different time-zone and wouldn't sync properly.  If I open and re-save the file locally it syncs fine (once date is no longer in the future).

**Comment by lmaestro** [comment]
It is fixed in 1.8rc1
