### ISSUE TITLE
1.8.0-beta1: keeps notifying forever about the filename too long error

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2882]
The 1.8.-beta1 keeps on notifying me about an error with a file over and over again. I think it should stop after notifying once. Here is my particular error:

![image](https://cloud.githubusercontent.com/assets/621965/6329648/9aded984-bb72-11e4-968c-3b44c3bab71e.png)

The notification itself is also a bit unhelpful:

![image](https://cloud.githubusercontent.com/assets/621965/6329668/cb478fc6-bb72-11e4-9238-341bc465c185.png)

My platform is Mac OSX 10.8.5

Thanks!

**Comment by dragotin** [comment]
Yes, this error case should be blacklisted.

**Comment by dragotin** [comment]
and @moscicki you should consider more speaking filenames ;-)

**Comment by ckamm** [comment]
Currently local errors are never put onto the blacklist, see SyncJournalErrorBlacklistRecord::update. Note that the blacklist is more of a temporary error suppression list - items will be retried at least once per day.

Could we detect that the filename is too long earlier and then ignore the file instead?

**Comment by dragotin** [comment]
Hmm, where does the error message "File name too long" come from actually?

**Comment by dragotin** [comment]
@moscicki do you happen to have a logfile by chance?

**Comment by moscicki** [comment]
Looks like that the long filename may not be saved on the local fs due to length(?).

I am sending you the log file privately.

kuba


--

**Comment by moscicki** [comment]
If I understand correctly, this is an error from local open() -- but this specific one will never go away. There should be a way of telling a difference between local errors that are possibly temporary and permanent ones (like this).

**Comment by dragotin** [comment]
The problem is that HFS+ only allows only a maximum file length of 255 chars, see http://en.wikipedia.org/wiki/HFS_Plus

**Comment by dragotin** [comment]
@moscicki I added a fix that makes the files ignored. You might want to test.

**Comment by moscicki** [comment]
Thanks. When is the next beta expected?

**Comment by lmaestro** [comment]
@moscicki I can't reproduce it. If you are able to reproduce it in the latest version, please reopen it. Thx
