### ISSUE TITLE
Handle 503 reply code properly

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#2884]
There are two scenarios where the server replies 503:

1. Maintenance mode: the server is in maintenance mode, access to the root folder returns error code 503. In that case we silently need to disable access to the server at all, and keep calm with the "not signed in" icon. After 30 seconds we need to try again if the server is back again. With 1.8.0 beta1 we show an error message instead.
2. The PROPFIND on a specific folder also could return 503. That is the case if an external storage went away for whatever reason. The server detects that and returns 503 for that folder. The client has to IGNORE that directory, otherwise data loss on the local repo can happen.

We need to fix that.

**Comment by dragotin** [comment]
@ckamm I felt free to assign you here.

For case 1. (which can be easily tested by setting maintenance = true in servers config.php) the problem is that in object Folder and in Folderman the variable ```_csyncUnavail``` is true if the server returned 503, but that is not properly handled. No retries to connect happen.

**Comment by ckamm** [comment]
@dragotin Currently the behavior is that the 503 response will make the 'service unavailable' error appear in the UI and show the account as disconnected (AccountState goes to NetworkError). You're saying we should hide the error and silently try again?

We could do that for a bit, but I don't want to pretend to be connected while we can't actually sync anything for too long. The 503 response could have other causes too and be permanent. What's the problem we want to solve? Would trying again for a minute and then giving up be good?

I'll check out 2. now.

**Comment by ckamm** [comment]
About 2.: The commit fixes it. It'd be really nice if we could distinguish this 'maintenance mode!' and 'storage unavailable!' from regular 503 errors that could have other causes.

**Comment by guruz** [comment]
Refs https://github.com/owncloud/client/issues/1923

**Comment by ckamm** [comment]
What was done:
1. Receiving a 503 response due to server maintenance during connection validation disables sync scheduling etc, but keeps the green icon. Regular connection checking continues and restores the client to a 'connected' state once the 503 goes away.
2. Receiving a 503 Storage not available response during remote discovery will ignore the whole directory.

What was not done: A server-maintenance 503 during remote discovery will still abort the sync with an error.

**Comment by lmaestro** [comment]
Tested case 1 in version 1.8.0-nightly20150302 (build 2068). It is fixed.
