### ISSUE TITLE
[Windows] owncloud.cfg gone after automatic update

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#2886]
Tonight at 3 o'clock my Windows machine automatically installed KB3006137 (I left the machine on with owncloud running. Everything normal). This morning after logging in I noticed that owncloud lost its ```owncloud.cfg```. Instead it showed the window to setup the client. After restoring the config file everything was back to normal.

Did anyone encounter the same problem?

Windows 7 32bit
ownCloud 1.7.1

**Comment by dragotin** [comment]
That is a strange thing...

**Comment by dragotin** [comment]
Honestly, I think this has too little information to enable us to nail down the problem.

**Comment by LukeOwncloud** [comment]
Agreed. And since I am apparently the only one with this behavior, I close this issue.

**Comment by LukeOwncloud** [comment]
Again. Same problem after automatic installation of KB2952664 last night. No further information, unfortunately. Is it again just my machine?
