### ISSUE TITLE
Active syncs abort with an error when the server is unavailable due to an upgrade

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#2888]
When the server is upgraded, it returns 503 error codes while the upgrade is running. This can happen at any time. If it happens during a sync, that sync will abort with an error message.

This may not be what we want to happen. See #1923 and #2884 for related discussion.

**Comment by guruz** [comment]
@Dianafg76 What happens these days with 2.1 nightlies?

**Comment by Dianafg76** [comment]
Is working OK with v 2.1.0
