### ISSUE TITLE
Feedback on settings in sharing dialogue

### ISSUE THREAD

**Issue by plages** [owncloud/client#2889]
I noticed that the desktop sharing takes over the default expiration time from the server. Which makes perfect sense to me. Does anyone agree therew should be feedback about this the first time i create a share? When i click 'Share with ownCloud'the second time on a share, the expiration date and the 'Set expiration data'checkbox are automatically populated. Maybe upon initial creation of the share someting like 'Default expiration time of %serversetting% applies' should appear in the dialogue.
Or else the dialogue should display the same behaviour as when clicked for the second, third etc. time.
Also when expiration and password are mandatory on the server the checkboxes should be enabled by default in the sharing dialogue.

**Comment by rullzer** [comment]
I am working on the mandatory password and expiration date. However this requires changes in the server as well. But it is coming.

**Comment by dragotin** [comment]
Hmm,  I reworked the dialog for the final again, so some of the mentioned issues should have gone already.

**Comment by plages** [comment]
The default expiration time is set on a share when created but this is not reflected in the interface until the user clicks "share with ownCloud" the second time. But maybe this is due to the fact that i'm still on 7.0.4 on the server side.

**Comment by rullzer** [comment]
A fix for not displaying the expiration date is in PR #2989. This forces retrieval of the shares on share creation. Since we get much more info that way.

**Comment by plages** [comment]
Great that'll solve the issue. Is this also possible for the password checkbox in case the server has the password set to mandatory?

**Comment by rullzer** [comment]
That should already happen.

**Comment by Dianafg76** [comment]
Cheked for the password checkbox in case the server has the password set to mandatory
