### ISSUE TITLE
Moving directories during sync does not work

### ISSUE THREAD

**Issue by guettli** [owncloud/client#2891]
1. I shared folder "mypictures" with my son.
2. Folder "mypictures" was visible in the desktop client Ubuntu 14.04 (I could not find a more detailed version number in the GUI)
3. My son moved the "mypictures" directory with nautilus to a subfolder. The sync between son and server was still active.
4. the "mypictures" directory appeared again in the desktop client of my son.

I think this should not happen.

The user of a shared folder should be able to move the directory to a different place.

AFAIK Owncloud 1.7 (which I use) supports this.

Server version: {"installed":"true","version":"7.0.4.2","versionstring":"7.0.4","edition":""}

**Comment by dragotin** [comment]
In the next sync run, this should reorganize. Did it?

**Comment by guettli** [comment]
After the sync it is the same. I restarted the linux desktop client, and waited until the icon got green. But it is the same. There are now two folders:

  *  owncloud/mypictures 
  *  owncloud/subfolder/mypictures. 

The files are all there. Some are in the subfolder, the other files are in the OwnCloud directory.

**Comment by ogoffart** [comment]
you can find the version in the about section of the general tab.

Normally this is supposed to work fine, unless you are using a very old version of the client.

We would need to see the logs or be able to reproduce it.

**Comment by guettli** [comment]
Could you please give me the link where I can find the guideline "how to provide logs of owncloud desktop client". 

I will post them if I know how to get the logs.

**Comment by dragotin** [comment]
@guettli https://doc.owncloud.org/desktop/1.8/troubleshooting.html

**Comment by ogoffart** [comment]
This works well here.

**Comment by ogoffart** [comment]
Closing this old issue. I would supect this was done with an old version of the client.  Please ropen if you can still reproduce and have the logs
