### ISSUE TITLE
share dialog: can't create shares in directory with a & in name

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#2892]
With the nautilus integration on linux, sharing a file (say "foo.txt") in the folder "a&b" fails.

This happens because the body of the 'create share' request ends up being

    path=/a&b/foo.txt&shareType=3

Found by @lmaestro in #2881

**Comment by rullzer** [comment]
Nice catch!
Works over here.

**Comment by lmaestro** [comment]
It is fixed in the lates version. It will be included in 1.8.0beta2
