### ISSUE TITLE
Windows 8 64bit  client will not automatically reconnect 

### ISSUE THREAD

**Issue by haimiko** [owncloud/client#2895]
Version: 1.7.1 build 4383 

After my laptop comes out of standby, switch wifi APs or go from wireless to wired network the client will not automatically establish connection with the server.  Furthermore, manually selecting "Sign in" will not reconnect either.  I must exit the client and restart for it to reestablish connection.

**Comment by danimo** [comment]
Should be fixed in 1.8. Please test with a nightly build http://download.owncloud.com/desktop/daily/.

**Comment by haimiko** [comment]
Did not fix the issue.

**Comment by ckamm** [comment]
Similar to #2899. @haimiko could you provide client logs? Press F12 on the stuck client after the resume and wait for a minute or two to get at them.

**Comment by haimiko** [comment]
The log just keeps repeating the following until I restart the app.









*02-27 07:46:19:190 0x5a1a4a8 OCC::FolderMan::slotEtagPollTimerTimeout:
void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check
for the remote ETag02-27 07:46:23:246 0x5a1a4a8
OCC::AbstractNetworkJob::slotFinished: void
OCC::AbstractNetworkJob::slotFinished() 99 "Connection timed out"02-27
07:46:23:247 0x5a1a4a8 OCC::CheckServerJob::finished: error: status.php
replied  0 ""02-27 07:46:45:229 0x5a1a4a8 OCC::AbstractNetworkJob::start:
!!! OCC::CheckServerJob created for  QUrl( "https://somesite.com/owncloud
<https://somesite.com/owncloud>" )  querying "status.php"02-27 07:46:49:197
0x5a1a4a8 OCC::FolderMan::slotEtagPollTimerTimeout: void
OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the
remote ETag02-27 07:46:55:351 0x5a1a4a8
OCC::AbstractNetworkJob::slotFinished: void
OCC::AbstractNetworkJob::slotFinished() 99 "Connection timed out"02-27
07:46:55:353 0x5a1a4a8 OCC::CheckServerJob::finished: error: status.php
replied  0 ""02-27 07:47:17:232 0x5a1a4a8 OCC::AbstractNetworkJob::start:
!!! OCC::CheckServerJob created for  QUrl( "https://somesite.com/owncloud
<https://somesite.com/owncloud>" )  querying "status.php"02-27 07:47:19:202
0x5a1a4a8 OCC::FolderMan::slotEtagPollTimerTimeout: void
OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the
remote ETag*

**Comment by ckamm** [comment]
The client is trying to ping the server, but running into timeouts. It sounds like something's up with the Qt networking stack. Related but old: https://bugreports.qt.io/browse/QTBUG-10286 https://bugreports.qt.io/browse/QTBUG-13488 @guruz ?

**Comment by dragotin** [comment]
https://bugreports.qt.io/browse/QTBUG-13488 really sounds like what we see. @guruz go for it :-)

**Comment by ckamm** [comment]
@haimiko I just pushed a possible workaround. Could you try again with tomorrow's build from http://download.owncloud.com/desktop/daily/ ?

**Comment by haimiko** [comment]
Behavior was slightly different but still did not resolve the issue.  I
noticed now that after resuming from sleep, the owncloud status was still
"connected" even though I had completely disabled the network cards.  I
then re-enabled them and it went offline and never came back.  Attached is
the log.


On Thu, Mar 19, 2015 at 3:55 AM, ckamm <notifications@github.com> wrote:

> @haimiko <https://github.com/haimiko> I just pushed a possible
> workaround. Could you try again with tomorrow's build from
> http://download.owncloud.com/desktop/daily/ ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/2895#issuecomment-83504364>.
>

03-20 11:10:40:789 0x438a680 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
03-20 11:10:40:789 0x438a680 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for  QUrl( "https://someserver/owncloud" )  querying "/"
03-20 11:10:58:821 0x438a680 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag
03-20 11:11:12:844 0x438a680 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
03-20 11:11:12:844 0x438a680 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for  QUrl( "https://someserver/owncloud" )  querying "/"
03-20 11:11:28:867 0x438a680 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag
03-20 11:11:30:608 0x438a680 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 99 "Host unreachable"
03-20 11:11:30:608 0x438a680 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Connected" -> "Timeout"
03-20 11:11:30:608 0x438a680 OCC::AccountState::setState: AccountState state change:  "Connected" -> "NetworkError"
03-20 11:11:30:624 0x438a680 OCC::Application::slotAccountStateChanged: Disabling sync scheduler, terminating sync
03-20 11:11:30:624 0x438a680 OCC::Folder::slotTerminateSync: folder  "ownCloud"  Terminating!
03-20 11:11:30:624 0x438a680 OCC::SyncEngine::abort: void OCC::SyncEngine::abort() OCC::DiscoveryMainThread(0x8fd18f8)
03-20 11:11:30:624 0x438a680 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 5 "Operation canceled"
03-20 11:11:30:624 0x438a680 OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot: void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply*) "Operation canceled" 0 5
03-20 11:11:30:624 0x438a680 OCC::PropfindJob::finished: Quota request *not* successful, http result code is 0 ""
03-20 11:11:30:624 0x438a680 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 99 "Host unreachable"
03-20 11:11:30:624 0x438a680 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 99 "Host unreachable"
03-20 11:11:30:624 0x438a680 OCC::PropfindJob::finished: Quota request *not* successful, http result code is 0 ""
03-20 11:11:30:624 0x438a680 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 99 "Host unreachable"
03-20 11:11:30:624 0x438a680 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 99 "Host unreachable"
03-20 11:11:30:624 0x438a680 OCC::PropfindJob::finished: Quota request *not* successful, http result code is 0 ""
03-20 11:11:30:624 0x438a680 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 99 "Host unreachable"
03-20 11:11:30:624 0x438a680 OCC::PropfindJob::finished: Quota request *not* successful, http result code is 0 ""
03-20 11:11:30:624 0x438a680 unknown: QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.
03-20 11:11:30:624 0x438a680 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 99 "Host unreachable"
03-20 11:11:30:624 0x438a680 OCC::PropfindJob::finished: Quota request *not* successful, http result code is 0 ""
03-20 11:11:30:624 0x438a680 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 99 "Host unreachable"
03-20 11:11:30:624 0x438a680 OCC::PropfindJob::finished: Quota request *not* successful, http result code is 0 ""
03-20 11:11:30:639 0x438a680 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 99 "Host unreachable"
03-20 11:11:30:639 0x438a680 OCC::PropfindJob::finished: Quota request *not* successful, http result code is 0 ""
03-20 11:11:30:624 0x8fb2bfc OCC::DiscoveryJob::remote_vio_opendir_hook: static csync_vio_handle_t* OCC::DiscoveryJob::remote_vio_opendir_hook(const char*, void*) OCC::DiscoveryJob(0x902bcf0)  ...Returned from main thread
03-20 11:11:30:624 0x8fb2bfc OCC::DiscoveryJob::remote_vio_opendir_hook: static csync_vio_handle_t* OCC::DiscoveryJob::remote_vio_opendir_hook(const char*, void*) 5 when opening  msg= "Aborted by the user"
03-20 11:11:30:624 0x8fb2bfc csync_ftw: Aborted!
03-20 11:11:30:624 0x8fb2bfc csync_statedb_close: sqlite3_close=0
03-20 11:11:30:639 0x438a680 OCC::SyncEngine::handleSyncError:  #### ERROR during  csync_update :  "Aborted by the user Aborted by the user"
03-20 11:11:30:639 0x438a680 OCC::SyncEngine::handleSyncError: Update phase was aborted by user!
03-20 11:11:30:639 0x438a680 OCC::SyncEngine::finalize: CSync run took  102258
03-20 11:11:30:671 0x438a680 OCC::Folder::slotSyncFinished: -> SyncEngine finished without problem.
03-20 11:11:30:686 0x438a680 OCC::Folder::bubbleUpSyncResult: Processing result list and logging took  0  Milliseconds.
03-20 11:11:30:686 0x438a680 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result:  4
03-20 11:11:30:686 0x438a680 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\username\ownCloud\"
03-20 11:11:30:686 0x438a680 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:C:\Users\username\ownCloud\"
03-20 11:11:30:686 0x438a680 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "ownCloud" :  "Success"
03-20 11:11:30:695 0x438a680 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
03-20 11:11:30:686 0x66ebe78 OCC::WatcherThread::watchChanges: void OCC::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/username/owncloud/.owncloudsync.log" action: 3
03-20 11:11:30:696 0x438a680 OCC::FolderWatcher::pathIsIgnored: * Discarded as is hidden! "C:/Users/username/owncloud/.owncloudsync.log"
03-20 11:11:30:738 0x438a680 OCC::SocketApi::command_RETRIEVE_FILE_STATUS: void OCC::SocketApi::command_RETRIEVE_FILE_STATUS(const QString&, OCC::SocketType*) "C:\Users\username\ownCloud\"
03-20 11:11:30:739 0x438a680 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\username\ownCloud\"
03-20 11:11:30:896 0x438a680 OCC::FolderMan::slotFolderSyncFinished: <===================================== sync finished for  "ownCloud"
03-20 11:11:31:005 0x438a680 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\username\ownCloud\tax"
03-20 11:11:33:396 0x66ebe78 OCC::WatcherThread::watchChanges: void OCC::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/username/owncloud/.owncloudsync.log" action: 3
03-20 11:11:33:396 0x438a680 OCC::FolderWatcher::pathIsIgnored: * Discarded as is hidden! "C:/Users/username/owncloud/.owncloudsync.log"
03-20 11:11:44:872 0x438a680 OCC::Account::resetNetworkAccessManager: Resetting QNAM
03-20 11:11:44:872 0x438a680 OCC::CookieJar::save: "C:/Users/username/AppData/Local/ownCloud//cookies.db"
03-20 11:11:44:872 0x438a680 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for  QUrl( "https://someserver/owncloud" )  querying "status.php"
03-20 11:11:58:885 0x438a680 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag
03-20 11:12:16:905 0x438a680 OCC::Account::resetNetworkAccessManager: Resetting QNAM
03-20 11:12:16:905 0x438a680 OCC::CookieJar::save: "C:/Users/username/AppData/Local/ownCloud//cookies.db"
03-20 11:12:16:905 0x438a680 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for  QUrl( "https://someserver/owncloud" )  querying "status.php"
03-20 11:12:28:916 0x438a680 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("ownCloud")
03-20 11:12:28:916 0x438a680 OCC::Folder::slotRunEtagJob: * Trying to check "ownCloud" for changes via ETag check. (time since last sync: 58 s)
03-20 11:12:28:916 0x438a680 OCC::Folder::slotRunEtagJob: Not syncing.  : "ownCloud" false "NetworkError"
03-20 11:12:33:306 0x438a680 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (The specified procedure could not be found.)
03-20 11:12:33:306 0x438a680 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001
03-20 11:12:33:306 0x438a680 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
03-20 11:12:35:756 0x438a680 OCC::ownCloudGui::slotFolderOpenAction: opening local url  "C:/Users/username/ownCloud/"
03-20 11:12:41:488 0x438a680 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (The specified procedure could not be found.)
03-20 11:12:41:489 0x438a680 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001
03-20 11:12:41:490 0x438a680 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
03-20 11:12:47:610 0x438a680 OCC::ownCloudGui::slotShowSettings: void OCC::ownCloudGui::slotShowSettings()
03-20 11:12:48:934 0x438a680 OCC::Account::resetNetworkAccessManager: Resetting QNAM
03-20 11:12:48:935 0x438a680 OCC::CookieJar::save: "C:/Users/username/AppData/Local/ownCloud//cookies.db"
03-20 11:12:48:938 0x438a680 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for  QUrl( "https://someserver/owncloud" )  querying "status.php"
03-20 11:12:55:160 0x438a680 OCC::ownCloudGui::slotShowSettings: void OCC::ownCloudGui::slotShowSettings()
03-20 11:12:58:943 0x438a680 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("ownCloud")
03-20 11:12:58:945 0x438a680 OCC::Folder::slotRunEtagJob: * Trying to check "ownCloud" for changes via ETag check. (time since last sync: 88 s)
03-20 11:12:58:946 0x438a680 OCC::Folder::slotRunEtagJob: Not syncing.  : "ownCloud" false "NetworkError"
03-20 11:13:02:038 0x438a680 OCC::FolderMan::setupFolders: * Setup folders from  "C:/Users/username/AppData/Local/ownCloud/folders"
03-20 11:13:02:038 0x438a680 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UNREGISTER_PATH:C:\Users\username\ownCloud\"
03-20 11:13:02:038 0x438a680 OCC::SyncJournalDb::close: void OCC::SyncJournalDb::close() "C:/Users/username/ownCloud/.csync_journal.db"
03-20 11:13:02:038 0x438a680 OCC::SyncJournalDb::commitTransaction: No database Transaction to commit
03-20 11:13:02:069 0x438a680 OCC::FolderMan::setupFolderFromConfigFile:   ` -> setting up: "ownCloud"
03-20 11:13:02:069 0x438a680 OCC::FolderMan::setupFolderFromConfigFile:     -> file path:  "C:/Users/username/AppData/Local/ownCloud/folders/ownCloud"
03-20 11:13:02:069 0x438a680 OCC::Folder::checkLocalPath: Checked local path ok
03-20 11:13:02:069 0x438a680 OCC::FolderMan::setupFolderFromConfigFile: Adding folder to Folder Map  OCC::Folder(0x71a0ee8)
03-20 11:13:02:069 0x438a680 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "REGISTER_PATH:C:\Users\username\ownCloud\"
03-20 11:13:02:069 0x438a680 OCC::SocketApi::slotUpdateFolderView: Not sending UPDATE_VIEW for "ownCloud" because status() is 1
03-20 11:13:02:069 0x438a680 OCC::FolderMan::slotScheduleSync: Schedule folder  "ownCloud"  to sync!
03-20 11:13:02:069 0x438a680 OCC::FolderMan::startScheduledSyncSoon: Scheduling a sync in 2 seconds
03-20 11:13:02:069 0x438a680 OCC::SocketApi::slotUpdateFolderView: Not sending UPDATE_VIEW for "ownCloud" because status() is 1
03-20 11:13:02:069 0x438a680 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "ownCloud" :  "Not yet Started"
03-20 11:13:02:069 0x438a680 OCC::AccountState::setState: AccountState state change:  "NetworkError" -> "Disconnected"
03-20 11:13:02:069 0x438a680 OCC::Application::slotAccountStateChanged: Disabling sync scheduler, terminating sync
03-20 11:13:02:038 0x66ebe78 OCC::WatcherThread::watchChanges: void OCC::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/username/owncloud/.csync_journal.db" action: 3
03-20 11:13:02:053 0x66ebe78 OCC::WatcherThread::watchChanges: void OCC::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/username/owncloud/.csync_journal.db" action: 3
03-20 11:13:02:053 0x66ebe78 OCC::WatcherThread::watchChanges: void OCC::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/username/ownCloud/.csync_journal.db-shm" action: 2
03-20 11:13:02:053 0x66ebe78 OCC::WatcherThread::watchChanges: void OCC::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/username/ownCloud/.csync_journal.db-wal" action: 2
03-20 11:13:04:071 0x438a680 OCC::FolderMan::slotStartScheduledFolderSync: FolderMan: Syncing is disabled, no scheduling.
03-20 11:13:04:744 0x91b6890 OCC::WatcherThread::watchChanges: void OCC::WatcherThread::watchChanges(size_t, bool*) Found change in "C:/Users/username/owncloud/.csync_journal.db" action: 3
03-20 11:13:04:744 0x438a680 OCC::FolderWatcher::pathIsIgnored: * Discarded as is hidden! "C:/Users/username/owncloud/.csync_journal.db"
03-20 11:13:20:970 0x438a680 OCC::Account::resetNetworkAccessManager: Resetting QNAM
03-20 11:13:20:970 0x438a680 OCC::CookieJar::save: "C:/Users/username/AppData/Local/ownCloud//cookies.db"
03-20 11:13:20:970 0x438a680 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for  QUrl( "https://someserver/owncloud" )  querying "status.php"
03-20 11:13:28:978 0x438a680 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag

**Comment by ckamm** [comment]
@haimiko Thank you for testing!

The new resetting code is being run, but it doesn't help. The queries for status.php are still unsuccessful. (we don't see their results anymore because QNAM is reset every 30s while disconnected).

We should check if there are any more caches or queues we can clear but it's become very likely that we'll have to try to isolate and fix the problem in Qt. This is also a curious message:

    QNetworkReplyImplPrivate::error: Internal problem, this method must only be called once.

**Comment by ckamm** [comment]
@haimiko I'm wondering if this is related to Qt's DNS lookup cache. Could you try using your server's IP address instead of your domain name to connect and try again?

**Comment by guruz** [comment]
@haimiko Does your server listen on different IP depending on which network it is acessed from?

**Comment by haimiko** [comment]
No. the server is behind a NAT router on a single IP.

**Comment by tangix** [comment]
Having the same problem and currently testing nightly20150328 (build 4908).
One difference is that our server is located in the internal network (192.168.x.x) and with NAT from the external. However, hostname is the same in both cases due to pfsense's DNS Resolving doing host override for clients in the internal network.

**Comment by tangix** [comment]
We have now tested on two Windows 8.1 machines and it seems like nightly20150328 solves our problems with reconnecting the clients.

**Comment by haimiko** [comment]
Just updated to : 1.8.0 (build 4893).   Does that have the fix found in
nightly 20150328?

It was working properly for a few times, coming in and out of standby.
Then I put my laptop in standby a third time and when I came back it
refused to connect until I restarted the app.  Here is the log output after
initiating a "sign-in"

03-30 15:20:15:835 0x45187c0 OCC::FolderMan::setupFolders: * Setup folders
from  "C:/Users/someone/AppData/Local/ownCloud/folders"
03-30 15:20:15:845 0x45187c0 OCC::SocketApi::sendMessage: SocketApi:
Sending message:  "UNREGISTER_PATH:C:\Users\someone\ownCloud\"
03-30 15:20:15:848 0x45187c0 OCC::SyncJournalDb::close: void
OCC::SyncJournalDb::close() "C:/Users/someone/ownCloud/.csync_journal.db"
03-30 15:20:15:850 0x45187c0 OCC::SyncJournalDb::commitTransaction: No
database Transaction to commit
03-30 15:20:15:856 0x45187c0 OCC::FolderMan::setupFolderFromConfigFile:   `
-> setting up: "ownCloud"
03-30 15:20:15:858 0x45187c0 OCC::FolderMan::setupFolderFromConfigFile:
-> file path:  "C:/Users/someone/AppData/Local/ownCloud/folders/ownCloud"
03-30 15:20:15:859 0x45187c0 OCC::Folder::checkLocalPath: Checked local
path ok
03-30 15:20:15:860 0x45187c0 OCC::FolderMan::setupFolderFromConfigFile:
Adding folder to Folder Map  OCC::Folder(0x708d178)
03-30 15:20:15:864 0x45187c0 OCC::SocketApi::sendMessage: SocketApi:
Sending message:  "REGISTER_PATH:C:\Users\someone\ownCloud\"
03-30 15:20:15:865 0x45187c0 OCC::SocketApi::slotUpdateFolderView: Not
sending UPDATE_VIEW for "ownCloud" because status() is 1
03-30 15:20:15:866 0x45187c0 OCC::FolderMan::slotScheduleSync: Schedule
folder  "ownCloud"  to sync!
03-30 15:20:15:867 0x45187c0 OCC::FolderMan::startScheduledSyncSoon:
Scheduling a sync in 2 seconds
03-30 15:20:15:867 0x45187c0 OCC::SocketApi::slotUpdateFolderView: Not
sending UPDATE_VIEW for "ownCloud" because status() is 1
03-30 15:20:15:872 0x45187c0 OCC::ownCloudGui::slotSyncStateChange: Sync
state changed for folder  "ownCloud" :  "Not yet Started"
03-30 15:20:15:874 0x45187c0 OCC::AccountState::setState: AccountState
state change:  "NetworkError" -> "Disconnected"
03-30 15:20:15:879 0x45187c0 OCC::Application::slotAccountStateChanged:
Disabling sync scheduler, terminating sync
03-30 15:20:17:866 0x45187c0 OCC::FolderMan::slotStartScheduledFolderSync:
FolderMan: Syncing is disabled, no scheduling.
03-30 15:20:17:966 0x45187c0 OCC::AbstractNetworkJob::start: !!!
OCC::CheckServerJob created for  QUrl( "https://someware/owncloud" )
querying "status.php"
03-30 15:20:19:242 0x45187c0 OCC::FolderMan::slotEtagPollTimerTimeout: void
OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the
remote ETag
03-30 15:20:26:230 0x45187c0 unknown: Failed to resolve EGL function
eglGetPlatformDisplayEXT (The specified procedure could not be found.)
03-30 15:20:26:234 0x45187c0 unknown: static QWindowsEGLStaticContext*
QWindowsEGLStaticContext::create(): Could not initialize EGL display: error
0x3001

03-30 15:20:26:236 0x45187c0 unknown: static QWindowsEGLStaticContext*
QWindowsEGLStaticContext::create(): When using ANGLE, check if
d3dcompiler_4x.dll is available
03-30 15:20:27:957 0x45187c0 OCC::AbstractNetworkJob::slotFinished: void
OCC::AbstractNetworkJob::slotFinished() 99 "Connection timed out"
03-30 15:20:27:959 0x45187c0 OCC::AccountState::setState: AccountState
state change:  "Disconnected" -> "NetworkError"
03-30 15:20:27:965 0x45187c0 OCC::Application::slotAccountStateChanged:
Disabling sync scheduler, terminating sync
03-30 15:20:27:975 0x45187c0 OCC::CheckServerJob::finished: error:
status.php replied  0 ""

**Comment by ckamm** [comment]
@haimiko I don't think so. If it did, you'd see the message "OCC::Account::resetNetworkAccessManager: Resetting QNAM" in your log file.

**Comment by ckamm** [comment]
@haimiko You tried the workaround before and it didn't help for you - why are you trying again? Did you attempt using the server's IP in the configuration as suggested above?

**Comment by snkku** [comment]
Hi! Same problem, but without any standby mode, my laptop is on 24/7. When i'm login after night, my client is disconnected... Trying to 'Log in' .. no changes, got 'network error', but if i open requested url in browser, it works well...

04-10 09:16:51:573 0x44dc490 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for  QUrl( "https://owncloudserver/owncloud" )  querying "status.php"
04-10 09:16:51:585 0x44dc490 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 2 "Connestion closed"
04-10 09:16:51:586 0x44dc490 OCC::AccountState::setState: AccountState state change:  "Disconnected" -> "NetworkError"
04-10 09:16:51:590 0x44dc490 OCC::Application::slotAccountStateChanged: Disabling sync scheduler, terminating sync
04-10 09:16:51:596 0x44dc490 OCC::CheckServerJob::finished: error: status.php replied  0 ""

version 1.8.0 4893 OS Win 8.1 x64

**Comment by ckamm** [comment]
@snkku Do you see the "Resetting QNAM" message in the logs? Your error looks more like #2973 ("connection closed" instead of @haimiko's "connection timed out"). Could you also try using the server's IP instead of domain name to check whether it's related to Qt's host lookup cache?

**Comment by snkku** [comment]
No "Resetting QNAM" in log, will try ip address

**Comment by ckamm** [comment]
@snkku That's odd, could you provide the full log? Could you also post the Git revision that shows up in your 'General' tab?

**Comment by MegaV0lt** [comment]
No connection after resume here too! 
http://i.imgur.com/iu8jaI3.png

When closing the clien it also crashes (Repor sent)
Version is 4893 on Windows 7; 32 Bit

**Comment by snkku** [comment]
With IP address, works for 3 days and...
04-14 11:08:12:664 0x44dc490 OCC::AccountState::setState: AccountState state change:  "NetworkError" -> "Disconnected"
04-14 11:08:12:671 0x44dc490 OCC::Application::slotAccountStateChanged: Disabling sync scheduler, terminating sync
04-14 11:08:14:620 0x44dc490 OCC::FolderMan::slotStartScheduledFolderSync: FolderMan: Syncing is disabled, no scheduling.
git rev: 38ef52 (build: 4893)

**Comment by ckamm** [comment]
@snkku So does it keep working when using the IP address? You're using 1.8.0 which does not include the potential fix mentioned above.

@MegaV0lt Ditto. Could you try with a 1.8.1 build?

**Comment by MegaV0lt** [comment]
In teh meantime i already use 1.81beta1. But i will now install the #4962

**Comment by ckamm** [comment]
@MegaV0lt 1.8.1-beta1 has the patch.

**Comment by MegaV0lt** [comment]
Strange new effect now:
http://i.imgur.com/oilGBeJ.png
Client keeps saying syning, but nothing happens...

**Comment by MegaV0lt** [comment]
I deleted some data, but does not sync:
http://i.imgur.com/zhjWzyf.png

**Comment by ckamm** [comment]
@MegaV0lt That's strange. Could you give me a log file for either of those?

**Comment by MegaV0lt** [comment]
Sorry, dont know wehere to find exept on the logwindow... 
For now i hav the log since last start: https://dl.dropboxusercontent.com/u/1490505/ownCloud/after%20Restart.log

But no errors since restart.

Next time i will save the log befor closing the client.

**Comment by ckamm** [comment]
@MegaV0lt  Thank you! Please start the client with a flag to save the log to the file, otherwise it'll often end up truncated. See https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly for details.

**Comment by MegaV0lt** [comment]
Ok, made a separate icon on desktop, that satrts with lofiles for the last 48 hours...

**Comment by ckamm** [comment]
@MegaV0lt How has it been going?

**Comment by MegaV0lt** [comment]
No issues until today. currently have rc1 installed.

**Comment by ckamm** [comment]
Okay, then I'll close this. Please don't hesitate to reopen if it happens again.
