### ISSUE TITLE
Option to turn off the overlay on synced folders in the finder OS X

### ISSUE THREAD

**Issue by rtrevorclark** [owncloud/client#2897]
This is just a feature request.

I would like an option in the desktop app for ownCloud to turn off the finder integration( the syncing icons on files and folders as in the image) 

Dropbox has an a preference option to disable these.

I think this would be a great addition to the desktop app.

thanks!

![sync 20icons](https://cloud.githubusercontent.com/assets/11217294/6399507/16e94994-bdb0-11e4-94f5-ef6743ac4ec6.jpg)

This shows the options that drop box currently has
![drop](https://cloud.githubusercontent.com/assets/11217294/6399513/1a017a34-bdb0-11e4-937c-d5cb22c7e596.jpg)

**Comment by guruz** [comment]
Any reason why you would want it off?

**Comment by rtrevorclark** [comment]
It is just seems repetitive to have the sync icon on every file and folder that you sync. You already have the menu bar icon that indicates if everything is synced or not. I think it just gives a more minimal noninvasive feel.

**Comment by dragotin** [comment]
I see the point

**Comment by xelan** [comment]
:+1: 
I also think that the overlays should be configurable in Windows as well. Another reason is that they might conflict with the overlays by other installed software.

**Comment by guruz** [comment]
For client 2.0 and OS X 10.10 this will be possible thanks to #2340 

For Windows the only solution is to de-install and re-install without overlay extensions however this is pending bug #2487 :-|

**Comment by guruz** [comment]
Closing this as it is done in 2.0 for OS X 10.10
For Windows, you have to not install the Explorer extension

@danimo Is the explorer extension selection in the Windows installer preserved on updates?
FYI @jturcotte
