### ISSUE TITLE
Right-Click menu in main owncloud folder disappears after a few moments

### ISSUE THREAD

**Issue by ubersolo** [owncloud/client#2898]
On right-click while in the main owncloud folder (Windows 8.1) with client 1.8.0beta1 (build 4730) , the menu pops up and then instantly disappears. This happens with folders and files in the main owncloud folder only. I tried in subfolders and it works fine.

**Comment by guruz** [comment]
By main folder you mean sync folder in Explorer, right?

**Comment by ubersolo** [comment]
Right

**Comment by lmaestro** [comment]
I can'r reproduce it. @ubersolo Do you want to try the latest version https://owncloud.org/install/#testing and verify if it is still happening ? 
@jturcotte Can you reproduce it?

**Comment by ubersolo** [comment]
I just updated to the client 1.8.0beta2 (build 4806) and the issue is still
occuring for me same as before even after a reboot. I'm on Windows 8.1 Pro
x64

**Comment by jturcotte** [comment]
This looks like http://superuser.com/questions/659857/windows-explorer-folder-context-menu-closes-itself

Could you follow the instructions to:
- Get the ShellExView utility
- Disable the OCContextMenuHandler extension
- Click on Options/Restart Explorer

and tell us if this makes the problem go away?

**Comment by ubersolo** [comment]
Ok, I used ShellExView and disabled the OCContextMenuHandler extension, restarted explorer and it did make the problem go away, I re-enabled the shell extension and the problem came back.

**Comment by dragotin** [comment]
Hmm, not sure if we can fix this as the bug seems to be triggered by ShellExView.

**Comment by ubersolo** [comment]
ShellExView was just the diagnostic tool I used to find that the ownCloud context menu shell extension is the culprit and not another one. When I disabled the OCContextMenuHandler (the ownCloud righ-click shell extension) using ShellExView, the right-click menu was able to show up (without the share with ownCloud option in there). When enabling the ownCloud shell extension again, the right-click menu disappears again, and only in the main ownCloud sync folder.

**Comment by ubersolo** [comment]
It looks like @apg1980 also had this issue in issue #2851 (I didn't notice it before bec. disappear was spelled differently) and @lmaestro set it as a duplicate of #2836. I think this issue is different than #2836 as it relates to the right-click menu disappearing and not the explorer folder.

Another interesting thing I noticed is if there are two separate explorer windows open to the main sync folder, it only happens with the first one that was opened and not the second. If I right-click on a file in the second window I opened to the owncloud sync directory, the menu shows up there fine without disappearing but will still disappear if I right-click in the first explorer window opened.

**Comment by dragotin** [comment]
@ubersolo sorry for my mixup with ShellExView.

**Comment by apg1980** [comment]
latest rc1 same behaviour.
my folder Strukture:
d:\owncloud = main sync folder
on all folderd and files within the area d:\owncloud the right click dialoge didapears emediately. deeper it works.

**Comment by jturcotte** [comment]
Ok I couldn't reproduce it on 8.1 and thought it might be a corner bug, but I just got the latest Windows update and I can reproduce it every time. This is pretty bad.

**Comment by jturcotte** [comment]
@ubersolo Hi, could you try the next nightly build at http://download.owncloud.com/desktop/daily/ and tell if it fixes the issue for you?

I guess it should be available tomorrow.

**Comment by dragotin** [comment]
@ubersolo https://download.owncloud.com/desktop/daily/ownCloud-1.8.0.4837-nightly20150313-setup.exe is ready for you *now*

**Comment by ubersolo** [comment]
just installed the new nightly and it's now working fine! I'm just running a windows update now and restarting to see if its still ok. Thanks

**Comment by ubersolo** [comment]
Fixed for me.

**Comment by jturcotte** [comment]
Thanks for verifying!

**Comment by Bridgesltd** [comment]
works perfect for me, great stuff, thanks.

**Comment by jotschgl** [comment]
It seems to me, the issue appeared again. I am using version 5.0.0.12278 and experciencing the same issue as described above.
I checked what is causing the problem the way it is described here: https://superuser.com/a/660051
It was the "OCContextMenuHandler" which caused this issue. I only occures in the owncloud folder, not in another one.

**Comment by TheOneRing** [comment]
> It seems to me, the issue appeared again. I am using version 5.0.0.12278 and experciencing the same issue as described above. I checked what is causing the problem the way it is described here: https://superuser.com/a/660051 It was the "OCContextMenuHandler" which caused this issue. I only occures in the owncloud folder, not in another one.

Please open a new issue and fill in all information requested by the ticket.
