### ISSUE TITLE
[Windows] [1.8nightly 4759] No connection after resume of PC

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#2899]
usualy i only set my pc to power save mode. After resume on the next day the oc client does not connect:
![2015-02-27 07_50_09-log-ausgabe](https://cloud.githubusercontent.com/assets/2804301/6408510/3224a0f4-be56-11e4-84ea-2df6dea21c36.jpg)
When i exit oc client and start it again it is workinkg again

in 1.7.1 version that was working

**Comment by ckamm** [comment]
Thanks for the log! It shows that the client regularly runs a CheckServerJob which comes back with RemoteHostClosedError. It doesn't look like a client error... I'll try to reproduce it.

**Comment by ckamm** [comment]
Hm, I can't suspend or hibernate my Windows VM, someone else will need to try to reproduce this.

**Comment by MegaV0lt** [comment]
Note: when i close the client (Exit) and start it again it works! So i think it might be a client bug. I also was checking the owncloud.log. No specific errors in there.

**Comment by MegaV0lt** [comment]
Maybe dicannect from network and reconnect after some time could simulate it in the vm?

**Comment by ckamm** [comment]
@MegaV0lt Disconnecting and reconnecting the network works fine.

**Comment by danimo** [comment]
@ckamm just for reference, you can restrospectively enable hibernate: http://www.giannistsakiris.com/2009/04/08/how-to-enable-hibernate-in-windows-xp/

**Comment by MegaV0lt** [comment]
went out for shopping. standby was about one hour. client working normal. maybe a "overnight" issue ore time/date related?

**Comment by MegaV0lt** [comment]
Ok, today after aprox. 3 hours standby:
http://i.imgur.com/eG2nPsZ.png
The errormessage is differnet, but i think the same reason. The connection is to local server "sheevaplug"... Again, after restart of client ok. Nothing in owncloud.log

**Comment by ogoffart** [comment]
From the logs, as ckamm already said:  the client is querying to status.php to know if the server is there.  But we get an error  ( NetworkError::RemoteHostClosedError )

That's strange. Why would the server closes new connections after we resume from sleep?  And why would it work again when one restart the client.

**Comment by MegaV0lt** [comment]
the owncloud.log on teh server does not show any access at the time... maybe the request did not even leave the clientpc? Othe rnetworking apps still work normal at the same time (eg. dropbox, ff, tb, webradio). Must be something with the client in my poor opinion

**Comment by MegaV0lt** [comment]
Also no TCP-Connection to see in Process Explorer:
http://i.imgur.com/6a8sFKO.png

**Comment by ogoffart** [comment]
And if you wait for 10 minutes? does it still not work?

**Comment by MegaV0lt** [comment]
I try next time

**Comment by MegaV0lt** [comment]
As expected: Nothing after 15 minutes...
https://dl.dropboxusercontent.com/u/1490505/OCNBC.log

Sharing is also not working, because of teh no connection problem, so it is a dropbox-link

**Comment by dragotin** [comment]
The logfile shows this lines:
```
03-04 17:10:40:698 0x59ee6a0 OCC::Folder::slotRunEtagJob: * Trying to check "ownCloud" for changes via ETag check. (time since last sync: 2271 s)
03-04 17:10:40:699 0x59ee6a0 OCC::Folder::slotRunEtagJob: Not syncing.  : "ownCloud" false "NetworkError"
```
That means that we do NOT start the ETag job because the AccountState is *Network Error* rather than *Connected*.

**Comment by dragotin** [comment]
And other lines:
```
03-04 17:11:36:420 0x59ee6a0 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for  QUrl( "https://sheevaplug/owncloud" )  querying "status.php"
03-04 17:11:36:441 0x59ee6a0 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 2 "Verbindung beendet"
```
In the normal case, a succeeding CheckServerJob would reset the AccountState to Connected, and as a result the ETagJob from above would start. The CheckServerJob is actually started, but it fails reporting "Verbindung beendet". This job just tries to access status.php. Is it possible that there is any problem in your setup causing this?

**Comment by MegaV0lt** [comment]
What should this be? I have a local network-connection with the oc-server (sheevaplug). I use my self created ssl-certs. On my laptop is still version 1.7 of the client but usese dyndns as adress of course

what info ddo you need?

**Comment by dragotin** [comment]
Related: #2973 and #2895 ?

**Comment by MegaV0lt** [comment]
Mybe. At least the effect described in #2973 i also had one time with 1.8beta2. Today i installed the final 1.8 client. I give new feedback here, when it occurs next time.

**Comment by ckamm** [comment]
@MegaV0lt I just pushed a possible workaround. Could you try again with tomorrow's build from http://download.owncloud.com/desktop/daily/ ?

**Comment by MegaV0lt** [comment]
Of course i will test. Feedback follows as soon i have a result

**Comment by ckamm** [comment]
We got a built that includes the maybe-fix early: http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.4850-nightly20150319-setup.exe

**Comment by MegaV0lt** [comment]
Ok, i install 4850 now ;)

**Comment by ckamm** [comment]
@MegaV0lt Any news? Your symptoms looked identical to the ones in #2973 and there the patch seems to have helped.

**Comment by MegaV0lt** [comment]
Since teh #4850 bui. Seems working now. Thanks...

**Comment by ckamm** [comment]
Great, thanks for testing!

**Comment by MegaV0lt** [comment]
Again with occlient 4893: 
http://i.imgur.com/4iCYIKO.png

**Comment by guruz** [comment]
@MegaV0lt Have you seen my comment here: https://github.com/owncloud/client/issues/3969#issuecomment-155419445
