### ISSUE TITLE
Improve memory usage during discovery

### ISSUE THREAD

**Issue by tmanthey** [owncloud/client#2902]
After making some changes to local repository the client crashes repetitive while indexing.

Attached you see resource consumption chart.

![clipboard01](https://cloud.githubusercontent.com/assets/9221853/6411663/f42d2ecc-be7a-11e4-94a6-d2bc0192697e.jpg)

**Comment by guruz** [comment]
How many sync folders?
How big?
About how many files?
Did you try 1.8 beta1?
:)

**Comment by tmanthey** [comment]
60gb in 600k files in 500 folders

I tried beta 1.8 this seems work. But still I notice very high memory 
consumption. 1.1GB in the moment.

Am 27.02.2015 um 12:39 schrieb Markus Goetz:

**Comment by guruz** [comment]
@ogoffart You mentioned you had valgrinded 1.8.x ?

**Comment by tmanthey** [comment]
valigrinded? I have the 1.8 beta now downloaded here 
https://owncloud.org/install/ (at the bottom)

Am 27.02.2015 um 14:39 schrieb Markus Goetz:

**Comment by ckamm** [comment]
I looked at discovery-phase memory use a bit. With 20k files, none of them on the server, when propagation starts we use about:

* 7.0 MB for propagation jobs
* 5.4 MB for the vector of SyncFileItems
* 6.1 MB for the map of filenames to SyncFileItems
* 5.0 MB for the csync trees
* 1.6 MB for filename QStrings

If this scales linearly with the number of files, that's about 750 MB for 600k files. That's not quite what @tmanthey is seeing, but also quite a lot.

There are some easy gains!

* There's no reason to keep the map of SyncFileItems alive once it's been converted to the list.
* The same holds for the csync trees once the trees have been walked.

**Comment by dragotin** [comment]
I did another vagrind session with chunking with no loss.

@ckamm good analysis, however, that is clearly for 1.8.1

**Comment by tmanthey** [comment]
Here is what I see right now in 1.8 while ownCloud client is syncing.

Solid 1.2 GB mem usage. Similar things I saw on 1.7. 

![clipboard02](https://cloud.githubusercontent.com/assets/9221853/6416395/214b6808-bea6-11e4-8211-cde9433de52e.jpg)

**Comment by ckamm** [comment]
@dragotin Adding that _syncItemMap.clear(); should be entirely safe and already give about half of the benefit.

**Comment by guruz** [comment]
Another spot to free memory: ```DiscoveryJob::remote_vio_closedir_hook``` is done with a directory, the csync discovery phase will not go in that dir again.

**Comment by gvdijnsen** [comment]
FYI I am administering the server side of this setup so if you need any info from that side, please let me know...

**Comment by guruz** [comment]
@gvdijnsen @tmanthey You could try a nightly build of 1.8 which has the two above commits. (Note that this didn't go through full QA) 
http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.4801-nightly20150303-setup.exe

**Comment by tmanthey** [comment]
Tried the nightly build. Better but memory consumption is still showing dangerous chainsaw pattern with peaking around 1GB. What I notice during discovery is the client fully consumes 1 core. (here 8 core machine => 1 core is 12.5% CPU) . On 2 or 4 core machines this creates significant CPU load. This also indicates single thread implementation.
Other thing are some extreme IO Peaks. Must be several 100 MB/sec.
![cp](https://cloud.githubusercontent.com/assets/9221853/6462554/65966dda-c1aa-11e4-8ad9-a002d49dedaf.jpg)

**Comment by guruz** [comment]
So the small spike is the 1 GB?

@ckamm @ogoffart The small spike could probably be avoided by having https://github.com/owncloud/client/blob/fe574dbbf98b1f70911cb37812de13d43ae838fa/src/libsync/syncengine.cpp#L715 be iteratively filling the vector (and removing its own content). That probably means higher CPU / longer duration (blocking of main loop?) though.

**Comment by tmanthey** [comment]
"So the small spike is the 1 GB?"

Pretty much yes

**Comment by tmanthey** [comment]
Just checked. During download memory consumption is still a solid 1.2 GB with the nightly build. Also it is crashing sooner or later. Currently it is not possible to sync.

**Comment by dragotin** [comment]
It is critical to understand whats happening here, and of mainly to get behind the crash @tmanthey mentions.

I still do not understand the second diagram. There are two full sync runs with the high memory usage. But after that, especially the CPU shows very little activity, and also the memory seems to stay constant, even on a quite high level, but well, we learned that windows also has a bit of an unpredictable behaviour on how it assigns memory to processes and frees it. So in general, the pattern seems to be fine. 

@guruz if the peak is really the conversion from QMap to QVector, it does not seem to free a lot of mem, so maybe we would be better off to continue on the Map if possible.

@tmanthey the crash is critical. @danimo can't we benefit from the crash reporter here?

**Comment by tmanthey** [comment]
You can also provide me a version that writes a log file. I'll send you the log then. Based on my experience with app development I can confirm a crash reporter is extremely useful.

**Comment by danimo** [comment]
@tmanthey funny you should say that. the next version comes with a crash reporter. As for the log file, simply launch the client from the command line with `--logfile filename`. (see ``--help`` and the manual for details).

**Comment by tmanthey** [comment]
started with --logdir. 33MB in the first seconds. I let you know later.

Am 05.03.2015 um 09:19 schrieb Daniel Molkentin:

**Comment by tmanthey** [comment]
@dragotin second diagram is from a fully synced client. I think these are 2 discoveries, then it starts to idle because nothing to do.

We currently have 2 workstations with ownCloud still working. Here we incrementally added new files. But now we added a 3rd one that needs to sync the full set and that is currently not possible. Log files will be from the 3rd machine. That is currently 1.6GB in 2 logs. Have fun whoever is reading this. :-)

**Comment by tmanthey** [comment]
client not responsive for an hour. Shut it down.
Attached images are just before killing the process. You can see it got stuck while moving memory. This is from the Official Beta 1.8 but nightly build was the same. Please contact me at info at evotegra.de for the download link for the log files. 

![clipboard01](https://cloud.githubusercontent.com/assets/9221853/6503407/077f5a3e-c32d-11e4-8f66-ff4af487e71b.jpg)
![clipboard02](https://cloud.githubusercontent.com/assets/9221853/6503408/077fe9d6-c32d-11e4-939c-7009b9c4fe47.jpg)

**Comment by guruz** [comment]
@tmanthey Thanks, we're investigating some possibilities

**Comment by dragotin** [comment]
There have been a few patches (31e400973705e6713e15325c6cdafcc4faead034 and 8746914f3b5ca659b2726c609703597a81810af4) that will improve the situation now, more in the next version as tracked in #2929.

**Comment by guruz** [comment]
2.3.0 beta1 has huge memory improvements..
https://owncloud.org/changelog/desktop/
