### ISSUE TITLE
Windows explorer integration is deleting other explorer plugin images

### ISSUE THREAD

**Issue by tmanthey** [owncloud/client#2903]
After owncloud installation (1.7.1 and 1.8 beta1) other explorer plugins like Dropbox or TortoiseSVN do not show their explorer icons anymore.

**Comment by dragotin** [comment]
Yes, sorry, but read this:
http://superuser.com/questions/542116/why-are-icon-overlays-from-3rdparty-apps-not-showing-up-in-the-win8-explorer
