### ISSUE TITLE
Windows XP: function missed in msvcrt.dll

### ISSUE THREAD

**Issue by nekoal** [owncloud/client#2907]
Newest nightly builds can't run on Windows XP. They show error 'function _snwprintf_s missed in msvcrt.dll'
![oc_snwprintf](https://cloud.githubusercontent.com/assets/10899904/6433463/c393e44a-c0aa-11e4-8539-d916d2acab25.PNG)
Tested builds and results:
1.8.0.4764-nightly20150226 ok (45.6 MiB)
1.8.0.4776-nightly20150227 error (46.1 MiB) (builds at 01:32 am has larger size, is it designed?)
1.8.0.4788-nightly20150227 error (37.2 MiB)
1.8.0.4789-nightly20150228 error (46.1 MiB)
1.8.0.4791-nightly20150301 error (46.1 MiB)
OS: Windows XP SP3 (2600.xpsp_sp3_qfe.090714-1307)

**Comment by danimo** [comment]
We've identified the issue:

1. by accident, all plugins were build with the new crash reporter module
2. only some builds were stripped of debugging symbols (hence the difference in size)

The crash reporter module has a dependency on symbols that do not exist in Windows XP.
We will soon import a new version that works without those symbols. In the meanwhile,
I have ensured that the crash reporter module is only build if we explicitly request it.

the latest nightly should work for you again.

**Comment by lmaestro** [comment]
@nekoal Can you verify it in the latest version http://owncloud.org/install/#testing ?

**Comment by jturcotte** [comment]
The crash reporter has been reenabled, including a fix for this bug in build 4811 available at http://download.owncloud.com/desktop/daily/

If somebody could verify on XP with 4811 or later that it doesn't crash we could close this bug.

**Comment by nekoal** [comment]
I tested 1.8.0.4806-beta2. Client started without error. I'll test 4811 in an hour.

**Comment by lmaestro** [comment]
@nekoal Thanks to verify it, if you are able to reproduce, please reopen it. Thx
