### ISSUE TITLE
Android client crashed when scrolling

### ISSUE THREAD

**Issue by bremenpl** [owncloud/client#2908]
Hello there,
I am using the Android Owncloud client in lastest available on the google play version (1.7.0). I am using Samsung s3 with Cyanogen 11. I have a folder it owncloud where I have over 700 pictures. When I enter that folder in the android client and start to scroll through the pictures fast, the app crashes.

**Comment by danimo** [comment]
Hi! This is the bug tracker forr the desktop client, please reopen at https://github.com/owncloud/android.

**Comment by bremenpl** [comment]
My bad, sorry.
