### ISSUE TITLE
Do authentication using another valid WebDAV call instead of GET

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/client#2911]
As per https://github.com/owncloud/core/pull/14151 we removed the SabreDAV browser plugin for ownCloud 8.1 and replaced it with a dummy page showing a white page as the client is authenticating using `GET`.

As this is a work-around it would be good if the client would at some point of time switch to a  `PROPFIND` or some other valid WebDAV call for initial authentication.

@danimo @dragotin

**Comment by ogoffart** [comment]
What call are we talking about here?  I can't find it.
Is it in the wizard perhaps?

**Comment by ogoffart** [comment]
Ah, i think i found it in the wizard

**Comment by dragotin** [comment]
Why did we use GET rather than PROPFIND in the first place? We need to keep an eye on backwards compatibility, maybe there have been server which simply could not answer to PROPFIND on / ?

**Comment by ogoffart** [comment]
No reason i think.  I can trace back the get request to  c848ff4bdbdea60ecc540f744fbf455a9d6a30ac ,  so maybe you know a reason.

But we already do a PROPFIND on / in the ConnectionValidator anyway.

**Comment by lmaestro** [comment]
@LukasReschke Please reopen if you can reproduce it.
