### ISSUE TITLE
An error is shown when you sync a large local folder

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#2912]
### Actual behaviour
An error is shown in the UI
![screen shot 2015-03-03 at 10 51 52 am](https://cloud.githubusercontent.com/assets/4689430/6460021/0db0f6b4-c194-11e4-96de-59cda822983d.png)

### Steps to reproduce
1. Launch the app
2. Select to sync a large local folder

### Server configuration
{"installed":true,"maintenance":false,"version":"8.0.1.0","versionstring":"8.0.1","edition":"Enterprise"}

### Client configuration
Client version: version 1.8.-nightly20150303 (build 2072)

Operating system:OS X 10.10

### Logs
https://gist.github.com/lmaestro/b71e5aba24ef667fb6dc
````
03-03 10:21:57:166 0x116f99ca8 csync_statedb_close: sqlite3_close=0
03-03 10:21:57:167 0x104d076f0 OCC::SyncEngine::handleSyncError:  #### ERROR during  csync_update :  "CSync failed to access https://docker.solidgear.es:50013/remote.php/webdav/docker/test/test"
03-03 10:21:57:169 0x104d076f0 OCC::SyncEngine::finalize: CSync run took  33366
03-03 10:21:57:169 0x104d076f0 OCC::Folder::slotSyncFinished: -> SyncEngine finished with ERROR, warn count is 0
03-03 10:21:57:187 0x104d076f0 OCC::Folder::bubbleUpSyncResult: Processing result list and logging took  17  Milliseconds.
03-03 10:21:57:187 0x104d076f0 OCC::sendOsXUserNotification: void OCC::sendOsXUserNotification(const QString &, const QString &) "Sync Activity" "welcome.txt has been downloaded."
03-03 10:21:57:187 0x104d076f0 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result:  2
03-03 10:21:57:187 0x104d076f0 OCC::Folder::slotSyncFinished:   ** error Strings:  ("CSync failed to access https://docker.solidgear.es:50013/remote.php/webdav/docker/test/test")
03-03 10:21:57:187 0x104d076f0 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
03-03 10:21:57:187 0x104d076f0 OCC::Folder::slotSyncFinished: the last 3 syncs failed
03-03 10:21:57:187 0x104d076f0 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:/Users/lmaestro/owncloud-servers/BB/"

**Comment by guruz** [comment]
Do you have the lines before?

Is it possible to access ```docker/test/test``` in the web browser?

**Comment by lmaestro** [comment]
Added more logs https://gist.github.com/lmaestro/9ae8730f278d96f3d1a2

**Comment by guruz** [comment]
Thanks..

```
03-03 10:19:18:880 0x104d076f0 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 203 "Error downloading https://docker.solidgear.es:50013/remote.php/webdav/docker/test/test - server replied: Not Found"
```

What about the webinterface?

**Comment by lmaestro** [comment]
I can access to it using webinterface

**Comment by guruz** [comment]
@PVince81 help :-)

**Comment by PVince81** [comment]
What about the owncloud.log ?

If it's a large folder maybe you ran into a PHP timeout

**Comment by guruz** [comment]
@PVince81 no timeout, the timestamps are close together. Also I don't think that would produce a "Not found"

@lmaestro Can you access that directory using Cyberduck?

**Comment by dragotin** [comment]
I tested with the broken test server, found dirs with funny chars not syncing, and tried these dirs here locally, where they synced nicely.

Closing this as I think its a server setup problem.

**Comment by guruz** [comment]
@dragotin "/webdav/docker/test/test" that doesn't look too funny though..

@lmaestro Can you forward this info by @dragotin to your admins?

**Comment by lmaestro** [comment]
I have the same problem without encryption
