### ISSUE TITLE
An error when I try to edit a txt from the client with the encryption is enable 

### ISSUE THREAD

**Issue by luciamaestro** [owncloud/client#2914]
### Actual behaviour
An error when I try to edit a txt from the client
![screen shot 2015-03-03 at 1 44 12 pm](https://cloud.githubusercontent.com/assets/4689430/6462697/8cee5bc6-c1ab-11e4-939e-bb3ef61f0446.png)

Note: The encryption is enable 

### Steps to reproduce
1. Launch the app
2. Select to sync a local folder
3. Create a txt
4. Edit the txt from the client

### Server configuration
{"installed":true,"maintenance":false,"version":"8.0.1.0","versionstring":"8.0.1","edition":"Enterprise"}

### Client configuration
Client version: version 1.8.-nightly20150303 (build 2072)

Operating system:OS X 10.10

### Logs
https://gist.github.com/lmaestro/00928d8c20afc11a5788

**Comment by lmaestro** [comment]
The same problem when I try to upload a file .doc/.odt

**Comment by ogoffart** [comment]
The error is:

```
https://docker.solidgear.es:50013/remote.php/webdav/welcome.txt - server replied: Forbidden (Session does not contain a private key, maybe your login password changed?)
```

Did you change your password?

**Comment by lmaestro** [comment]
No, I didn't change it.

**Comment by lmaestro** [comment]
The same error that in this case https://github.com/owncloud/client/issues/2763

**Comment by ogoffart** [comment]
Maybe the server logs show what the problem is.

**Comment by ogoffart** [comment]
Yes, it's the same error as in #2763

**Comment by lmaestro** [comment]
But different steps an it is happening with the new server version.

**Comment by guruz** [comment]
CC @schiesbn

**Comment by ogoffart** [comment]
Closing old issue
