### ISSUE TITLE
Allow the client to be deterministically built

### ISSUE THREAD

**Issue by strugee** [owncloud/client#2916]
It would be nice if Mirall could be deterministically built. That means that if you use the same operating system, the same source code, and the same build toolchain as what the official binary uses, the binary that results from _your_ compilation will be bit-for-bit identical to the official distribution.

This is useful for things like security accountability. Being open source isn't enough if a binary that contains patches that do Bad Things can be distributed unnoticed.

At the Tor Project's blog you can find information on [why this is important](https://blog.torproject.org/blog/deterministic-builds-part-one-cyberwar-and-global-compromise) and [how they implemented it in the Tor Browser Bundle](https://blog.torproject.org/blog/deterministic-builds-part-two-technical-details).

I realize that this will probably be tagged "research" or somesuch, but I figure I'll file it anyway. Thanks!

**Comment by jalcine** [comment]
Realistically, ownCloud's designed afaik to have the server be the authorative source of all files. LAN Sync breaks this since there's no querying of the server about the status of the files updated. Now, if it was possible to ask the server what files have been changed from the last provided timestamp and use that to determine between local clients what to sync, that'd be dope. But again, authorization would have to be in the hands of the server. I'm assuming that a time-based key, not necessarily OATH but something like this can be issued to each client and used to identity each client to one another, thus (kind of) solving the issue of determining who's who. For the paranoid, an option can be provided to have the client get a new local sync token after a period of inactivity of local sync.

It's not an easy problem :wink:

**Comment by hefee** [comment]
debian has started already the aim to have deterministic builds. You can see the prograss for owncloud-client:

https://reproducible.debian.net/rb-pkg/sid/amd64/owncloud-client.html

**Comment by guruz** [comment]
Good idea.
How is OBS' support for that?

**Comment by strugee** [comment]
> How is OBS' support for that?

Glancing at the ToC of their docs, not great. Most of the work is done in the build process, but there's also some bits in the package generation, mostly due to embedded timestamps. I suppose you could use libfaketime to correct that, but it'd be nice to have it Just Work™.

Someone should file a bug against OBS, I guess.

**Comment by strugee** [comment]
Filed https://features.opensuse.org/318872.

**Comment by guruz** [comment]
BTW Does this interfere with https://github.com/owncloud/client/pull/6040 ?

**Comment by strugee** [comment]
Pretty sure most (all?) of Debian is built with those options and they have really good reproducible builds support, so presumably not

**Comment by hefee** [comment]
@guruz : Nope everything is fine with #6040 and determenistic builds.

Btw. the Debian build is deterministic: https://tests.reproducible-builds.org/debian/rb-pkg/buster/amd64/owncloud-client.html. The only patch i needed to add is to remove the usage of __DATE__ and __TIME__. See [0008-make-reproducable.patch](https://anonscm.debian.org/cgit/pkg-owncloud/owncloud-client.git/tree/debian/patches/0008-make-reproducable.patch) from debian repo. But this patch may not been needed in meanwhile for Debian.

**Comment by TheOneRing** [comment]
@dragotin @dschmidt if we remove __DATE__  and  __TIME__ we would reach that goal.
The information is basically only relevant for our ci builds, I'd suggest that we add date and time as a compile flag?

**Comment by dschmidt** [comment]
What does that solve?

I think the request is that builds should be reproducible so it can be verified the application is build from the public source. If we want to keep showing the build date and time we could either provide instructions on how to fake that time for verification builds or we move those into a small helper lib, that just exports functions returning those values. Then everything but the shared lib can be verified ...

**Comment by TheOneRing** [comment]
Not planned
