### ISSUE TITLE
Crashreporter for MacOSX

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#2918]
We added the crash reporter infrastructure to the client with 1.8.0, as described in #2109 However, in 1.8.0 it only works for Win32 platform.

Enhance that to also support MacOSX.

**Comment by jturcotte** [comment]
This was done in 1.8.0.

The official OSX builds had the flag enabled following 4c13992f5dc587883ae123df4b352859c44c9feb and 99f51998f2f07a43b81cd6f75ec5f65d54664b9d that fixed some issues.
