### ISSUE TITLE
Put back in codepath that uses all Etags in a directory instead of just the directory ETag for CheckEtagJob

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2922]
This was removed as part of the new discovery but @ogoffart says we need it back in because of buggy old ownCloud versions that don't change the (root) directory ETag if the contents change.

This might cause https://github.com/owncloud/client/issues/2479#issuecomment-77293425

CC @PVince81

**Comment by PVince81** [comment]
What old ownCloud versions are we talking about ? OC 5 ?

**Comment by guruz** [comment]
This was done, @ogoffart has reviewed the code.

https://github.com/owncloud/client/commit/3f712dce02d647124022f464a4fd06e65d0e2d83
