### ISSUE TITLE
Cant install on Centos 6

### ISSUE THREAD

**Issue by sdelvillar** [owncloud/client#2924]
Hi

i run "yum install own-cloud" but have this dependency error

Error: Package: owncloud-client-1.7.1-2.2.x86_64 (isv_ownCloud_desktop)
           Requires: oc-neon

Please if someone could help me???

Thanks

**Comment by guruz** [comment]
Note that 1.8 might not require neon anymore if you install it with qt5 (which might not be available on CentOS?)

**Comment by dragotin** [comment]
@sdelvillar could you retry? Indeed oc-neon hasn't been published, I apologize.
