### ISSUE TITLE
Ownclouds icon overlay spams Console log in Mac OS X

### ISSUE THREAD

**Issue by KarstenB** [owncloud/client#2925]
The new icon overlay in Mac OS X Finder does generate tons of Message of the following format:
05/03/15 13:50:02,002 Finder[222]: READ from socket (2422): <STATUS:ERROR:/Users/bla/ownCloud/Shared/XXX>
Those files are usually within ignored folders. And some Messages with this:
05/03/15 14:56:25,459 Finder[222]: READ from socket (2422): <STATUS:OK:/Users/bla/ownCloud/Shared>

Is there any way to reduce this logging?

**Comment by guruz** [comment]
Which client version?
Did you try 1.8beta2?

**Comment by KarstenB** [comment]
Sorry, I forgot. I am using Yosemite 10.10.2 with 1.7.1.
I just installed the 1.8 beta and from a first glance it appears as if the logging is gone. Will get back to it should I find it again.

**Comment by dragotin** [comment]
Yes, should be good with 1.8.0beta2. Let us know if you want us to reopen it. Thanks.
