### ISSUE TITLE
File Locking prevents Software to use Files

### ISSUE THREAD

**Issue by gdkags** [owncloud/client#2926]
The software I'm using does encounter file locks from the OCclient on a regular basis, retries several times and then fails starting a new file. It does state that Antivirus Software might be the culprit for the intrusive file lock, but as soon as I quit the OCclient everything works fine again. Seems to be only a problem on Windows8 only, my linux system does not happen to have the same problems.

I'd like to help clear up the issue and will try to answer questions.

Owncloud Client 1.7.1 build 4382 

[git rev 9cbe8b](https://github.com/owncloud/client/commit/9cbe8bf5779abad0c2b5669d32d2adda504eb24b)

**Comment by guruz** [comment]
Easiest solution: Check 1.8 beta2 first :-)

**Comment by gdkags** [comment]
looking good :D thank you!
