### ISSUE TITLE
using owncloud via juju (without overly-scrollbar)

### ISSUE THREAD

**Issue by Jas2Ma** [owncloud/client#2928]
Hi Guys,

I am trying to use owncloud-client at work, so with no root permissions at my workstation (ubuntu 14.04).
Therefore I use juju (https://github.com/fsquillace/juju) to run it. I can successfully install owncloud-client via pacman, but I can't access the settings window

    Gtk-Message: Failed to load module "overlay-scrollbar"
    Gtk-Message: Failed to load module "canberra-gtk-module"

Is there a possibility to access the settings window if the client is running?
I would like something similar to:
  1. starting owncloud-client: owncloud
  2. opening settings-window: owncloud --setting

**Comment by danimo** [comment]
Nope, this is an issue in Ubuntu with the way they handle the system tray.

**Comment by Jas2Ma** [comment]
Well, interpret my bug report as a request for command line support for control button functionality
