### ISSUE TITLE
not syncing because of characters in filename that are incompatible with some platforms

### ISSUE THREAD

**Issue by rensgr** [owncloud/client#2930]
Hello,
My linux desktop client refuses to sync all my screensnapshots, because they have a timestamp in the filename ( snap_20:58:45.jpg, for example )
':' is illegal in windows, because it has a meaning in drive assignment letters ( A: / C: etc)

Would it be possible to work around this by translating the illegal character(s) in the filename
for example into some kind of transcoding, like : becomes a coded number %##
(and the % in a filename should then be %%, of course.
The respective clients could then recode the characters,  apart from the ones  that are illegal for their particular platform.
It is a major headache for me, since I rely on having all my documents on phone, camera, laptop, desktop ......

**Comment by danimo** [comment]
This requires changes in the server that are being worked on, see #854
