### ISSUE TITLE
[OS X] updater installs in wrong place

### ISSUE THREAD

**Issue by hqx** [owncloud/client#2931]
Scenario: owncloud 1.7.0 installed and running in /Applications/Subdir/
The updater finds new 1.7.1 update, installs under /Applications and then restarts the old client in Subdir -> endless loop.

Expected Behaviour: Write Updated App in same Place where current App is, not hardcoded /Applications

**Comment by dragotin** [comment]
@guruz can you double check pls?

**Comment by dragotin** [comment]
Removing gold ticket state because this is not standard install, but install to Subdir.

**Comment by guruz** [comment]
The Sparkle code (```SUGuidedPackageInstaller```) does not seem to currently care to give the current running path to the ```.pkg``` installer: https://github.com/sparkle-project/Sparkle/blob/bc99dbd560356aab8de86d6d5548d29efd36d647/Sparkle/SUGuidedPackageInstaller.m#L79

Sparkle invokes ```/usr/sbin/installer``` to which you could give a ```customLocation```:
```
     The customLocation attribute can be set for a choice only if that choice explicitly allows a user-defined path. That is, if the choice would have a Location popup when viewed in the Cus-
     tomize pane of the Installer application, it can be set via customLocation.  (Otherwise, installation paths cannot be arbitrarily modified, since the package author must account for cus-
     tom install locations for the installation to work properly.)
```

So this will need a Sparkle patch and setting up our ```pkg``` so it can be installed everywhere.

**Comment by guruz** [comment]
...or we just don't launch the auto update code if the location of self is not where it is expected.
Much easier.

**Comment by guruz** [comment]
Done.
We won't auto-update now..

@dragotin @danimo please quick check commit for possible issues with branding..
