### ISSUE TITLE
[OS X Lion] v1.8beta2 Installation Error 

### ISSUE THREAD

**Issue by mcnesium** [owncloud/client#2932]
Trying to install v1.8beta2 on OSX Lion, but after the routine went through I get the following error:
![eeboo2ca](https://cloud.githubusercontent.com/assets/476060/6543733/1c22f196-c529-11e4-9319-2f78a1ffc4c3.png)
Console.app output:

    04.03.15 14:47:21,247 installd: PackageKit: Install Failed: Error Domain=PKInstallErrorDomain Code=112 "An error occurred while running scripts from the package “ownCloud-1.8.0.2077beta2.pkg”." UserInfo=0x7ff363877930 {NSFilePath=./preinstall, NSURL=file://localhost/Users/mcnesium/Downloads/ownCloud-1.8.0.2077beta2.pkg#ownCloud.pkg, PKInstallPackageIdentifier=com.ownCloud.client, NSLocalizedDescription=An error occurred while running scripts from the package “ownCloud-1.8.0.2077beta2.pkg”.} {
        NSFilePath = "./preinstall";
        NSLocalizedDescription = "An error occurred while running scripts from the package \U201cownCloud-1.8.0.2077beta2.pkg\U201d.";
        NSURL = "file://localhost/Users/mcnesium/Downloads/ownCloud-1.8.0.2077beta2.pkg#ownCloud.pkg";
        PKInstallPackageIdentifier = "com.ownCloud.client";
    }

**Comment by guruz** [comment]
But 1.7.1 installed fine on that machine?

**Comment by mcnesium** [comment]
I installed 1.7.0 via [homebrew cask](http://caskroom.io/) and that went well, except for the [high CPU issue](https://github.com/owncloud/client/issues/2479) which is the reason I went back to 1.6.4.

**Comment by guruz** [comment]
@mcnesium Could you retry with download.owncloud.com/desktop/daily/ownCloud-1.8.0.2129-nightly20150313.pkg ? I changed the return code of the pre-install script to always return success (6c4b7f1479eff4b4c90bab0c82d3e6a7c1bfc8ed)

**Comment by dragotin** [comment]
@mcnesium does the final install properly for you?
