### ISSUE TITLE
Moving files from external storage to main storage with missing quota results in empty file

### ISSUE THREAD

**Issue by dpeger** [owncloud/client#2933]
#### Description
Moving an existing file from an external storage location (e.g. local folder available through the external storage app) to the main storage using the desktop sync client results in an **empty** file in the main storage, if the user's quota is exceeded.

This seems to be a very critical issue as a user may not be aware of exceeding his quota when using the sync client and this error causes actual data loss.

#### Steps to reproduce
* Create an external storage location linked to a local folder and make it available to a user
* Upload any file to the external storage location as the user using the sync client or the web frontend
* Make sure the changes are synced to your desktop with the sync client
* Set user's quota to 0B
* Move the file from the external storage location to the owncloud main storage on your desktop PC
* After some time the file will be *updated* and will be empty in both location your desktop **and** the owncloud instance

I was able to reproduce this issue with the Mac OSX sync client

**Comment by guruz** [comment]
@dpeger Which version of the server did you use?

@icewind1991 @PVince81 Aware of such a server issue?

**Comment by dpeger** [comment]
I did a fresh install using the debian packages provided by the openSUSE build service. The server version currently seems to be 8.0.0-9.

13. März 2015 09:48 Uhr, "Markus Goetz"  schrieb:
	@dpeger (https://github.com/dpeger) Which version of the server did you use?

	@icewind1991 (https://github.com/icewind1991) @PVince81 (https://github.com/PVince81) Aware of such a server issue?

**Comment by PVince81** [comment]
This should be fixed in 8.0.2 as per https://github.com/owncloud/core/pull/14504

**Comment by guruz** [comment]
Thanks..

@dpeger Please report back in http://github.com/owncloud/core if the issue persists

**Comment by dpeger** [comment]
Thanks!

Is there any ETA for 8.0.2 to be available through the openSUSE build service?
