### ISSUE TITLE
[osx] Client drawing a lot of power due to constant Icon refreshs

### ISSUE THREAD

**Issue by ericbodden** [owncloud/client#2937]
I have been observing the OSX client to consume a lot of power, at least under Yosemite, apparently due to frequent icon refresh. OwnCloud causes the WindowServer to be at a constant CPU load of about 45%, as documented here:
http://apple.stackexchange.com/questions/153397/windowserver-high-cpu-on-yosemite

As soon as I close OwnCloud, WindowServer drops down to single-digit numbers.

**Comment by guruz** [comment]
Could you try this:

* Launch ownCloud client
* Check CPU load 
* If it is high, kill Finder (e.g. via terminal.app ```killall Finder```) (don't worry it will restart)
* Check CPU load again

**Comment by guruz** [comment]
Also, do you have the settings window open?

**Comment by ericbodden** [comment]
Hello.

> Also, do you have the settings window open?

No I did not. But a restart of OwnCloud actually seems to have helped. Strange...

Cheers,
Eric

**Comment by guruz** [comment]
@ericbodden Can you estimate how long you had it open?
And how often you browsed sync folders in Finder?

**Comment by ericbodden** [comment]
> @ericbodden Can you estimate how long you had it open?

Probably very long, several days. I barely ever reboot my Mac.

> And how often you browsed sync folders in Finder?

A couple of times per day maybe. Hard to tell...

**Comment by ckamm** [comment]
It's likely that this was solved with the patches for #2990. @ericbodden Could you reopen this if the issue still pops up with a recent build? (http://download.owncloud.com/desktop/daily/)
