### ISSUE TITLE
Disable parallel uploads for server versions <= 8.0.2

### ISSUE THREAD

**Issue by craigpg** [owncloud/client#2938]
A follow on to #2743.

We expect to be able to turn on parallel uploads for server version >= 8.0.3, but not before.  So, our code that checks for < 8 needs to updated a bit to disable parallel uploads if the server version is <= 8.0.2.

**Comment by lmaestro** [comment]
It works fine in the latest version1.8.0-nightly20150311(build 2117)

**Comment by Daimonion1980** [comment]
Is this function active? 
Where do i set the max uploads? cfg File? Which Parametername should i use?
