### ISSUE TITLE
missing icons in 1.8.0-beta2

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#2940]
The app icons are missing in the top bar and setting dialog box in 1.8.0-beta2. MacOSX 10.8.5. I have installed 1.8.0-beta1 beforehand which had the same problem. Later I reverted to 1.7.1 which worked again OK with icons.

![image](https://cloud.githubusercontent.com/assets/621965/6570595/91c14864-c6fd-11e4-89c5-4ad90d6d0646.png)

![image](https://cloud.githubusercontent.com/assets/621965/6570600/a26de352-c6fd-11e4-80e3-07280bf5a3ad.png)

**Comment by michaelstingl** [comment]
@dragotin thank you for taking care of it! /cc @cdamken 

00002694

**Comment by jturcotte** [comment]
Should be fixed by 94734d0a16fd45872d101f380f4c15bd43bee160 in customer-themes.

**Comment by lmaestro** [comment]
It is duplicated https://github.com/owncloud/client/issues/2746
