### ISSUE TITLE
Client fail indexing on a mac os x with remote home

### ISSUE THREAD

**Issue by sirio81** [owncloud/client#2944]
Hi, please have a look at this screencast: http://youtu.be/UIb06doLGCI
You can see the client is indexing something that looks exadecimal: two chipers.
This mac os x account has few files and also exluded the Library and all files starting by a dot.
It's costantly indexing.

This is a mac 10.9.5 and is a domain with a mac X serve.
The home folder is not stored localy but on the X serve.
I don't know if that matters at all.

Owncloud client version is 1.7.1.

**Comment by guruz** [comment]
I'm not sure I understand here.

Do you see those hexadecimal directories when you use the ownCloud webinterface?
How does your remote URL look like? How does your local sync folder path look like?

**Comment by sirio81** [comment]
> Do you see those hexadecimal directories when you use the ownCloud webinterface?
No

> How does your remote URL look like?
http://cloud.mydomain.com

> How does your local sync folder path look like?
it looks like this:
https://cloud.extensys.it/public.php?service=files&t=82a6d5cfb777c12ff044e66918fc0e55

**Comment by guruz** [comment]
Syncing your whole home folder is not supported, sorry.
There is too much files changing all the time.
You can sync a subfolder like ```Music```.

**Comment by sirio81** [comment]
I've been excluding Library and all files starting by .
The same thing works for a local user: syncing the whole home folder excluding Library and .*

**Comment by guruz** [comment]
If you want to find out which file is changing and triggering a sync you try to run the client from ```Terminal.app``` like this:

``` /Applications/owncloud.app/Contents/MacOS/owncloud --logfile -```
