### ISSUE TITLE
After a reboot users can't see their files

### ISSUE THREAD

**Issue by ohnotnow** [owncloud/client#2945]
I've got an install of owncloud 8 from the rpm repo running on CentOS 7 (owncloud update centre says it's up-to-date). The server seemed to be running fine, had been rebooted numerous times - then yesterday I had to shut it down again and when it came back up users could log in, but all they could see was the default documents/photos folders.

The data is all still there on disk and from a quick scan of the mysql tables things look ok there too (ie, no sign of strange/duplicate paths or anything). If the users upload new files those show up ok in the right place. Storage paths seem ok both in the web interface and the new uploaded files are going into the right user folders. The group information shows up ok in the Users list too.

Most users are coming in via LDAP, but there are local accounts too - all have the same problem. There's nothing leaping out at me in the logs either (there were initially a few out-of-memory crashes but had cleared up after allocating more memory via .htaccess).

Are there any pointer to places I could look? I'm wary of re-scanning the files before seeing if there's something else I can try...

**Comment by billybofh** [comment]
Oh - and for reference, it's CentOS 7, php-5.4.16, apache httpd-2.4.6-19.

**Comment by billybofh** [comment]
Oh - just noticed this has gone into the client area not the core one. It's been one of those days... I'll re-post it there.  Ignore and/or shoot me...

**Comment by ckamm** [comment]
@ohnotnow thanks for moving to core :)
