### ISSUE TITLE
Difference in number of .csync_journal files between empty and non-empty directories

### ISSUE THREAD

**Issue by jnfrmarks** [owncloud/client#2950]
### Steps to reproduce

1. Install 8.0.2 Server
2. Install 1.8 client from http://download.opensuse.org/repositories/isv:/ownCloud:/community:/testing/xUbuntu_14.10
3. Run smashbox test lib/test_slowwrite.py
4. The test fails due to there being a discrepancy in the number of files expected.
5. Run the same test using 1.7.1 client and it passes.

### Expected behaviour

The test should pass with both client versions

### Actual behaviour

1.8 client fails due to a discrepancy in the number of files expected.

When syncing an empty directory there is only:

.csync_journal.db

When syncing a directory with files in it, there are two new files created that are not present when syncing an empty directory:

.csync_journal.db
.csync_journal.db-wal
.csync_journal.db-shm

Is this expected behavior?  This is different from 1.7.1 clients.

### Server configuration

Ubuntu 14.04
PHP 5.5.9
MySQL DB
ownCloud Enterprise Edition 8.0.2 (stable)

### Client Configuration

owncloudcmd version 1.8.0

**Comment by guruz** [comment]
The -wal and -shm are expected files.
Possibly sqlite3 does not create them when nothing is written into the DB.

Maybe the solution would be to not count those 3 files and just expect the existance of .csync_journal.db

**Comment by jnfrmarks** [comment]
I agree that I won't count the .csysnc_journal files; I just wanted to be sure that the  additional files were expected.
