### ISSUE TITLE
Get rid of QApplication subclass to catch crashes on startup

### ISSUE THREAD

**Issue by danimo** [owncloud/client#2952]
See #2109

**Comment by jturcotte** [comment]
It won't be easy to split QtSingleApplication out of QApplication and I'm not sure it's worth doing it just to cover the few things that we initialise after the QApplication itself.

If we want to go that far we might as well decouple libcrashreporter-qt from QApplication and install the handler even before (this also won't be easy).

So anyway I'd propose postponing the rest of this task until we get users to complain about such uncaught early crashes or that we see concrete benefits for it somehow.

**Comment by dragotin** [comment]
Agree to what @jturcotte says. Other things benefit users more.

**Comment by ogoffart** [comment]
Not worth it.
