### ISSUE TITLE
Uploading files larger than 2GB fails on windows

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#2954]
When uploading a huge file the upload fails with "Unknown error" for chunk 410. Log:

```
03-12 06:58:57:378 0x4fb16c0 syncjournaldb.cpp:977 "INSERT OR REPLACE INTO uploadinfo (path, chunk, transferid, errorcount, size, modtime) VALUES ( ?1 , ?2, ?3 , ?4 ,  ?5, ?6 )" "F.iso" 410 -1597884786 0
03-12 06:58:57:378 0x4fb16c0 syncjournaldb.cpp:1290 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "Upload info" and starting new transaction
03-12 06:58:57:379 0x4fb16c0 bandwidthmanager.cpp:93 void OCC::BandwidthManager::registerUploadDevice(OCC::UploadDevice*) OCC::UploadDevice(0x74efba0)
03-12 06:58:57:379 0x4fb16c0 propagateupload.cpp:402 ERR: Could not prepare upload device:  "Unknown error"
03-12 06:58:57:380 0x4fb16c0 syncengine.cpp:831 void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem&) "F.iso" INSTRUCTION_NEW 3 "Unknown error"
```

The upload fails just as the chunk lies beyond the signed 32bit boundary.

```
409*5*1024*1024 = 2144337920
<
2^32/2 = 2147483648
<
410*5*1024*1024 = 2149580800
```

**Comment by ckamm** [comment]
QFile::seek() returns false with the big value.

**Comment by ckamm** [comment]
Disabling the Windows-specific code in openFileSharedRead() makes the seek() work.

**Comment by ckamm** [comment]
Worked around it by doing the seek natively on windows, testing now.

**Comment by cooper-42** [comment]
Hi, I have this issue with our server. If you are interested I could help test the fix.

**Comment by ckamm** [comment]
@cooper-42 That'd be nice. Grab tomorrow's snapshot build from http://download.owncloud.com/desktop/daily/ and give it a spin.

**Comment by danimo** [comment]
@cooper-42 What do you mean "with our server"? Syncing with large files against the server on Windows, or do you see problems with downloading/uploading/syncing big file at all?

**Comment by cooper-42** [comment]
ownCloud is running on an ubuntu server. I'm syncing it with a windows 2012 server. The large files are on the windows server. I can upload the with the webinterface with no problems. It's "just" the client that has problems.

**Comment by cooper-42** [comment]
Hi, I have sucessfully synced a 3,9 GB file with the new client! After the file reaches 100% it takes about 1 - 2 minutes for the transfer to complete, but after that, everything is fine.
If I can help you with some more testing, just let me know.

**Comment by ckamm** [comment]
@cooper-42 Thanks for testing! The time at the end is taken by the server assembling the final file.
