### ISSUE TITLE
Access forbidden by server... error when trying to log in to a site with a self-signed cert on OS X

### ISSUE THREAD

**Issue by phrend** [owncloud/client#2957]
I'm using OS X 10.8.5 and 10.10.2 and seeing the same behavior with the desktop client available here:
http://owncloud.10557.n7.nabble.com/ownCloud-Client-1-8-0-RC1-available-td14744.html

When configuring the desktop client to connect to my server, I enter my server address, accept my self-signed cert, then provide my user/pass, and try connect, and I get the following error:

![capturfiles-20150371_130393-redacted](https://cloud.githubusercontent.com/assets/1667900/6628096/fb1a4f36-c8bf-11e4-96c8-1debf4f7b76b.jpg)

> Access forbidden by the server. To verify that you have proper access, click here to access the service with your browser.

("click here" is a link to my site, however, clicking on it does not do anything.  If I right-click on the link, and copy the link, the URL is my site.)

I don't have any problem connecting to my site via the web interface with the same login creds.

Server version (from version.php) is:
$OC_Version = array(8,0,0,7);
$OC_VersionString = '8.0';
$OC_Channel = 'stable';
$OC_Build = '2015-02-07T02:34:55+00:00 df2808eec840c033b952e001ee8a063a93fae417';

The access logs from the login attempt look like:
xxx.xxx.xxx.xxx - - [12/Mar/2015:13:30:46 -0700] "GET /status.php HTTP/1.1" 200 2745 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.0"
xxx.xxx.xxx.xxx - - [12/Mar/2015:13:30:47 -0700] "GET /remote.php/webdav/ HTTP/1.1" 401 1154 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.0"
xxx.xxx.xxx.xxx - - [12/Mar/2015:13:31:19 -0700] "PROPFIND /remote.php/webdav/ HTTP/1.1" 401 2991 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.0"

**Comment by phrend** [comment]
After noticing that the logs were trying to do some webdav stuff, I started google'n and found this page:
http://wiki.dreamhost.com/OwnCloud (yes, they are my hosting company)

I added:
    RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization},L]

and tried again... and it worked!

...so, sorry for the false alarm. :hankey:

**Comment by rdsqc22** [comment]
A note to anyone else having the same problem- I came across this error, but the .htaccess change did not help. Instead, removing all spaces from my password made the error go away. It seems like a fairly generic error.

**Comment by clubbing80s** [comment]
FYI I got this error when moving to a new server. I had missed the Apache module mod_rewrite, installing this module fixed the issue for me.
