### ISSUE TITLE
Unable to upload files larger that 4 GB...

### ISSUE THREAD

**Issue by actyler555** [owncloud/client#2958]
It appears I am experiencing the same issue as described in this post:
https://github.com/owncloud/client/issues/2047

Unfortunately I wasn't able to get a clear answer on what the fix was from reading the conversation.  This particular build of ownClould started at 7.0.2 was upgraded to 7.0.5, and then again to 8.0.2..  the issue was present in all versions.  Basically as I am uploading I watch the "temp" file from an SSH session, once it gets to 4 GB, a new file is created which counts up to 4 GB (Sometimes 3.9GB) then the browser displays "internal Server error".  Any suggestions?  I have been over and over the online help with modifying the .htaccess file and php.ini files.

My server:
Ubuntu Linux 14.04
Apache2
MySQL

Tests with Windows 8/7 and Firefox
I have not tested the Windows client yet, but will shortly.

**Comment by actyler555** [comment]
Update as promised.  Uploading a 6 GB file via the Windows client was successful..  So this appears to be related to uploading large files via the web UI only.

**Comment by guruz** [comment]
Sorry, I have to forward you to https://github.com/owncloud/core
Can you find your issue there or create a new one?

This bugtracker is only for desktop sync client issues.

**Comment by actyler555** [comment]
Ok, I posted my question here:
https://github.com/owncloud/core/issues/14882
