### ISSUE TITLE
[OS X] Copied Links from share dialog appear in mail as SharedContact.vcf

### ISSUE THREAD

**Issue by raydoo** [owncloud/client#2959]
I am Using Client Version 1.8.0beta2 Build 2078 on MAC os 10.10.2 with Mail 8.2
when i create and Copy a Public Link in Finder, it becomes a PastedContact.vcf in Mail when pasted.

When i paste the link into Safari it works as normal, when i Copy/Paste the link from Safari, it also shows up as normal link in Mail.

**Comment by guruz** [comment]
FYI, Doesn't reproduce with Mail ```Version 7.3 (1878.6)``` on 10.9.5

**Comment by guruz** [comment]
We explicitely call ```setText``` on ```QClipBoard```. No idea why Apple would make a vcf out of it.

**Comment by rullzer** [comment]
@raydoo, can you paste the linke correctly into your webbrowser? Or any other program. Because then it most likely is an issue with the mail client. As stated by @guruz we just copy plain text so no idea why that would fail.

**Comment by raydoo** [comment]
When i paste the URL into Safari and textedit it looks normal. When i copy/paste the URL from Safari/Textedit again it works also in Mail.

**Comment by guruz** [comment]
@raydoo Just wondering if you updated to Yosemite yet or not?
Does this still happen?

**Comment by raydoo** [comment]
@guruz I am still using yosemite or do you mean el capitan? Problem still exists. I will try it again when i upgrade to el capital.

**Comment by guruz** [comment]
Let's continue in https://github.com/owncloud/client/issues/3300

**Comment by raydoo** [comment]
Problem still occurs with the new version

**Comment by guruz** [comment]
@raydoo Yes, this is a 2.1 fix not 2.0.x :)

@danimo @dragotin Should we switch the nightlies to 2.1?
