### ISSUE TITLE
[OS X] Add link to sync folder with ownCloud icon in Finder Sidebar

### ISSUE THREAD

**Issue by rgr101** [owncloud/client#296]
Just a nice-to-have with no priority: 

Have an Owncloud icon instead of the ordinary folder icon in Finder's Sidebar
(just like Dropbox does).

**Comment by jturcotte** [comment]
I looked at how to do this in relation with https://github.com/owncloud/client/issues/2340, there is an official way documented within the FinderSync doc in the "Adding a Sidebar icon":
https://developer.apple.com/library/mac/documentation/General/Conceptual/ExtensibilityPG/Finder.html#//apple_ref/doc/uid/TP40014214-CH15

This seems to rely on the FinderSync watched folder list (I didn't try yet) but fetches the icon from the wrapping application's own CFBundleIconFile .icns file. We'd need to replace the manual kdelibs logic in cmake/modules/AddAppIconMacro.cmake with an .iconset folder (containing extra sidebar_123x123.png files) and generate the .icns using iconutils instead.

The main problem I see with this though is that I'd have to change the structure of all the branding repository which fetches those files or create this .iconset directory on the fly in the build directory. I'm not sure yet if that amount of work is worth showing a fancier icon in the Finder sidebar, what do you think?

**Comment by rgr101** [comment]
I strongly believe this is an important part of visibility and brand generation, and so it'll  be worth the efforts by sure...

**Comment by jorgelbg** [comment]
This little features creates a lot of user value (from my point of
view) mainly due the fact that  increases the integration between the
application and the user environment.

**Comment by guruz** [comment]
@MTRichards @jancborchardt Please also discuss with regards to multi-account or multiple sync folders.
And see @jturcotte 's comment above.

**Comment by jancborchardt** [comment]
For multi-account, I’d say every local folder should have an entry in the sidebar. For multiple sync folders, not sure.

**Comment by MTRichards** [comment]
>For multi-account, I’d say every local folder should have an entry in the sidebar.

Yes, each root folder should get a shortcut on the finder menu, and in windows in explorer.

For multi account, the rule remains that root sync folders get left menu icons - but only one. So if a root folder is synced in two accounts, only 1 sidebar as it is the same folder.
If the root and a sub folder are synced to two different accounts, then that is like having 2 root folders, so two icons on the left.

@jancborchardt what do you think?

**Comment by jancborchardt** [comment]
@MTRichards sounds reasonable, yes.

**Comment by MTRichards** [comment]
Ok. Confirming 2.1 as the milestone then.

**Comment by Ark74** [comment]
Hi!, i see that this is an OSX related issue. Is there a Windows related one or i could be informed by watching this?

**Comment by guruz** [comment]
(At least currently the code to create a sidebar favorite seems not to be called at all because it is in a not possible anymore ```else``` branch.. check the wizard for ```Utility::setupFavLink( localFolder )```)

**Comment by guruz** [comment]
Some progress: https://github.com/owncloud/client/pull/5928#issuecomment-319015035 
\o/
