### ISSUE TITLE
owncloud-client 1.7.1-4 and ownCloud 8.0.2 & 6.0.x – Cannot sync "connection timed out" 

### ISSUE THREAD

**Issue by X4** [owncloud/client#2960]
I tried syncing with the ownCloud server with a 2GBit/s (up/down) line at work and with my own 100Mbit/5Mbit line at home without luck. I tried that with ownCloud Server 6.x, 7.x and currently with 8.0.2 Our server still has 1.1TB disk space available and is quite powerful, so this problem shouldn't happen due to missing space or a slow connection.

I think the isse in #1893 shouldn't have been close too early. Because my issue is probably the same, but on a different platform. I believe that the problem is not with the client, but with the ownCloud server. 
Do you have any recommendations? I have read the faq and disabled php output buffering already.

```ini,
php_flag output_buffering off
````

**Comment by enoch85** [comment]
Closing this in favor of #1893

**Comment by enoch85** [comment]
@X4 Could you describe your problem here instead?
