### ISSUE TITLE
Windows 1.7 client constantly re-syncing -- can't delete files without them re-syncing

### ISSUE THREAD

**Issue by gig13** [owncloud/client#2961]
**Expected behavior**
Files only sync when they are new or have changed

**Actual behavior**
Files are constantly being synced from the server. Even when I try to delete a folder or file, they are eventually re-synced to my desktop

**Steps to reproduce**
Not able to reproduce

**Environment details**
Windows desktop client 1.7 build 4382
OwnCloud Server 7.0.5
MySQL database
Ubuntu 14.4

**Client log**
https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fclient%2F2961

Can I try an advanced copy of 1.8 for testing?

**Comment by danimo** [comment]
Try 1.8.0-rc1: https://owncloud.org/install/#testing

**Comment by guruz** [comment]
Which storage backend does the server use?

Please note that .eml files are famous for somehow constantly changing: https://doc.owncloud.org/desktop/1.7/faq.html

**Comment by gig13** [comment]
@guruz 
They are using the default backend, and the storage is presented via an NFS mount.

**Comment by gig13** [comment]
@danimo 
Do you have a have a changelog of 1.8?

**Comment by dragotin** [comment]
@gig13 pls. talk to jennifer about the 1.8 release, she acts as release manager.

**Comment by lbarman** [comment]
Same here with client 1.7 / owncloud 7. Is it fixed in 1.8 ?

**Comment by dragotin** [comment]
nfs-mount... @gig13 you need special mount options for the nfs mount. I forgot which, but experiment with ```sync``` or ```ac / noac```.

**Comment by gig13** [comment]
@dragotin 
noacl ?
noacl — Turns off all ACL processing. This may be needed when interfacing with older versions of Red Hat Enterprise Linux, Red Hat Linux, or Solaris, since the most recent ACL technology is not compatible with older systems.

**Comment by gig13** [comment]
@dragotin @michaelstingl 
Could this be a symptom of the DST change?

**Comment by michaelstingl** [comment]
@dragotin we discussed this DST thing in Windows over lunch a few days ago.

**Comment by gig13** [comment]
@dragotin 
We have another case where the syncing is constantly occurring.
The data is on the local disk on the owncloud server.

ubuntu 12.04
uname -a
Linux i2-tbox-f001 3.13.0-46-generic #75~precise1-Ubuntu SMP Wed Feb 11
19:21:25 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

postgres 9.3
oc 6.0.5


Log file on:
https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fclient%2F2961

**Comment by guruz** [comment]
@gig13 In the case of this (https://github.com/owncloud/client/issues/2961#issuecomment-83116484) log you can see the ```INSTRUCTION_SYNC``` statement for shared directories.

Maybe @icewind1991 @PVince81 can point if there was an issue with shared directories changing their ETag which leads to them being re-discovered (and also triggering a local client re-discovery)

**Comment by gig13** [comment]
@guruz 
I only see it 4 times in the entire log for the Shared/ folder. 
Most have "INSTRUCTION_NONE     file: Shared/pathtofiles"

**Comment by dragotin** [comment]
@PVince81 you mentioned something on changing ETags on external storage recently. Can you enlighten us here?

**Comment by PVince81** [comment]
If this is about NFS, then the question is whether the mtime stored on NFS changes automatically (discussed here with steps to check it https://github.com/owncloud/client/issues/2579#issuecomment-73221156). If it does, then OC will think the files changed and it will adjust their etags.

The change detection can be disabled on the root/home storage with this: https://github.com/owncloud/core/blob/master/config/config.sample.php#L899
On external storage there will be a new option in 8.1 to disable change detection.
But that option is only suitable if the ext storage is used exclusively through OC (no outside changed)

**Comment by gig13** [comment]
@dragotin @PVince81 
No external storage is being using in this case.

**Comment by PVince81** [comment]
With "external storage" I always mean storages mounted using the external storage app (ex: SMB, FTP). If the data directory of OC is on an NFS mount, it does not qualify as external storage.

**Comment by bboule** [comment]
@gig13 is this a close out?  Just cleaning up old BT wondering if this is resolved

**Comment by gig13** [comment]
Symptom disappeared. Closing
