### ISSUE TITLE
error build-clients makewinlin.sh

### ISSUE THREAD

**Issue by mabith** [owncloud/client#2963]
hii, iam using script makewinlin.sh -win from https://github.com/owncloud/administration/tree/master/build-clients  and and I am getting this error, your help will be appreciate.

Run CPack packaging tool...
CPack: Create package using NSIS
CPack: Install projects
CPack: - Run preinstall target for: mirall
CPack: - Install project: mirall
CPack: Create package
CPack Error: Problem running NSIS command: "/usr/bin/makensis" "/home/mabith/Downloads/administration-1-master/build-clients/buildenv/windows/mirall-build/_CPack_Packages/unused/NSIS/project.nsi"
Please check /home/mabith/Downloads/administration-1-master/build-clients/buildenv/windows/mirall-build/_CPack_Packages/unused/NSIS/NSISOutput.log for errors
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: ownCloud
Makefile:106: recipe for target 'package' failed
make: *** [package] Error 1

----------NISIOutput.log--------------

SetOutPath: "$INSTDIR\platforms"
File: "qwindows.dll" 679644 bytes
SetOutPath: "$INSTDIR\accessible"
File: "/usr/i686-w64-mingw32/sys-root/mingw/lib/qt5/plugins/accessible\qtaccessiblewidgets.dll" -> no files found.
Usage: File [/nonfatal] [/a] ([/r] [/x filespec [...]] filespec [...] |
   /oname=outfile one_file_only)
Error in script "/home/mabith/Downloads/administration-1-master/build-clients/buildenv/windows/mirall-build/_CPack_Packages/unused/NSIS/project.nsi" on line 400 -- aborting creation process

**Comment by danimo** [comment]
Please build from the `v1.7.1-qt54` or `v1.7.1-signed` tag.
