### ISSUE TITLE
[OS X] Update Sparkle to 1.14

### ISSUE THREAD

**Issue by guruz** [owncloud/client#2965]
https://github.com/sparkle-project/Sparkle/releases

Most interesting:
```
Added SUUpdater delegate method for failures. (Benjamin Gordon)
```

**Comment by guruz** [comment]
@danimo says he has updated Sparkle on the macbuilder to version [FIXME]

**Comment by guruz** [comment]
@danimo Can you please verify we install at least at 1.14? We seem to have 1.13.1:
```
/Library/Frameworks/Sparkle.framework/Versions/Current/Sparkle:
	@rpath/Sparkle.framework/Versions/A/Sparkle (compatibility version 1.6.0, current version 1.13.1)
```

Because of https://github.com/owncloud/client/issues/4561

**Comment by guruz** [comment]
macbuilder has 1.14.0 now

**Comment by guruz** [comment]
Let's close this if it does not crash for @tflidd anymore

**Comment by tflidd** [comment]
I was able to install the testpilotcloud-2.2.0.3167-nightly20160309.pkg on my OS X 10.9.5 system. No problems so far. Thank you @guruz

**Comment by supportreq** [comment]
@guruz I am facing this issue for 2.2.4 when I was trying to re-compile with a custom theme.. I have kept the updateurl as http://www.google.com

Please advice..
