### ISSUE TITLE
Renamed folder cause syncrun stop on walking remote replica

### ISSUE THREAD

**Issue by nekoal** [owncloud/client#2967]
5 days ago I tried install owncloud on Windows Server 2008 R2 and sync folder with large number cyrillic-named files. Some of files have path length near MAX_PATH and exceed MAX_PATH after adding '.ocTransferId10000.part' for temporary file on server side. To prevent this I renamed folder to shorter name (syncrun was still in progress). On next syncrun in activity log was records about move files then about deleting files. In some syncruns client stoped. Crash reporter send some reports for build 4826. Then I tried 4842 with same result.
It seems as server error about handling cyrilic foldernames and dubling folders but I think client also needs some functionality to detect duplication of folders on server and correct it.

##Expected behavior
 Client detect folder was renamed and don't use old name.
 Client detect folder was dubled and correct it (For example ignore folder instance which return 'Not found' responce or delete it by fileid)

##Actual behavior
 Client try receive contents of folder by old name and stop sync when server report 'Not Found'. Sometimes client crashes.
On web interface parent folder showed twice and one of instances has child folder with old name.

##Environment details
 Windows desktop client 1.8.0-nightly builds 4826,4842
 OwnCloud Server 7.0.5 (unfortunately, 8.0.2 don't work for me)
 MySQL database
Windows Server 2008 R2 Standart

##Logs:
https://gist.githubusercontent.com/nekoal/88023e4275731c2fc989/raw/0bbad54decf54af8ee302e452182be02251f2bc9/client%20window%20messages

https://gist.github.com/nekoal/88023e4275731c2fc989/raw/b9dd452df46fc7337369241127843ba583a2da6d/.owncloudsync.log

**Comment by guruz** [comment]
Is PHP set to the UTF8 locale?

**Comment by LukasReschke** [comment]
Using Windows Server is discouraged and only community supported starting with ownCloud 8.

This is probably yet another problem with the file mapper as reported at https://github.com/owncloud/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22windows+server%22

Please use a LINUX server to host ownCloud. Thanks.

=> Backlog

cc @nickvergessen @DeepDiver1975

**Comment by LukasReschke** [comment]
Ref https://github.com/owncloud/core/pull/14540

**Comment by nekoal** [comment]
@guruz  I think PHP set to the UTF8 locale. Tell me please where I can check locale. Is it in php.ini? Originally php was installed with xampp-1.7.7 package. I see right names over web-interface and encoding in browser set to utf8. My own php pages in other directory uses utf8 and working properly.

I think problem with way owncloud store files in server. Any sequence of cyrillic characters in filenames replaced with '-' character. Typical path for It's work fine when number of file low. But with thousands of cyrillic names it don't work. Usually my national sites use transliteration (replacing to sound alike latin characters) to store cyriliic-named files on any web servers. Also temporary files can be uploaded to data folder root. This prevent hit MAX_PATH by temporary file when destination file path near MAX_PATH but don't exceeds MAX_PATH. Owncloud creates directory structure for store folders under data folder then data folder on same device as destination store folder.

Yes, I understand LINUX more valid for hosting and works faster. But I already have Windows server and I need syncronize only two or three document directories. Also I have some program which don't support Linux analogs. I think I spent much more time to install and learn and properly configure Linux server on Hyper-V than I spent to search program working with windows server.

**Comment by nekoal** [comment]
@LukasReschke @DeepDiver1975 I found in tables of MySql how 2 or more folders exist in the same directory tree - one of folders has normal path without trailing slash in oc_filecache. Other folder(s) have trailing slash (sequent slashes) in path.
First question: Are you sure this is only Windows server problem? Is Linux server make difference between folder path with/without trailing slash?
Second question: Can I delete this folders with sql command or deletion can cause more serious malfunction in owncloud?
Also I found slugified path value in logic_path column of oc_file_map. Is it designed?

**Comment by guruz** [comment]
Sorry, I don't think we support Windows server at this point.

**Comment by nekoal** [comment]
@guruz May I try correct owncloud core for myself and then report results? Or I need accept some agreement first?
I assume this is bug in calculation size for folder. This folders with trailing slash have positive values in size field. And folder without slash has zero or minus one in size field.

**Comment by guruz** [comment]
Feel free to modify yourself and create a patch :-)
If you want it to be included in oC you need to sign the contributors agreement.
