### ISSUE TITLE
1.7.1 hang on to files (files are locked and can't be deleted)

### ISSUE THREAD

**Issue by kaplandani** [owncloud/client#2969]
I've added a new folder for synchronization. ( a Large one)
Currnetly files are being uploaded to the server (I can see which file is being loaded right now)
Yet many other files are locked (already uploaded) and I can't delete them as owncloud client  "holds" them. 
It means the client keeps a lot of open file handles without releasing (memory...)
and it make it impossible to edit/delete the files....

client version 1.7.1 on win 8.1 machine. 
server is 8.0.2 on centos 7.

**Comment by dragotin** [comment]
The locking behaviour was completely changed for 1.8.0 to prevent this (and other) situations. Please check with the 1.8.0 rc1 that is available on https://owncloud.org/install/#testing or wait for the final release that comes soon. 

I am closing this one as I think it's fixed. Feel free to reopen if not. Thanks!
