### ISSUE TITLE
Can we build owncloud client windows in 32 bits machine 

### ISSUE THREAD

**Issue by waheni** [owncloud/client#2970]
I am using opensuse 13.1 in 32 bits machine 
i cant find    mingw32-cross-libqt5-qttools-5.4  for  32 bits machine 

it is possible to build the client in 32 bits  machine or we can do it only  in 64 bit one.

**Comment by guruz** [comment]
Hey, for build support please try on IRC on #owncloud-client-dev on irc.freenode.net

CC @dragotin @kwillems @danimo
