### ISSUE TITLE
CPack Error: Problem running NSIS command

### ISSUE THREAD

**Issue by waheni** [owncloud/client#2971]
Good day 
i have some problem when i execute the "make package" commande when building the windows  client  in opensuse 13.1 :
i got this error:
CPack Error: Problem running NSIS command: "/usr/bin/makensis" "/home/wael/build_malizia/mirall-build/_CPack_Packages/unused/NSIS/project.nsi"
Please check /home/wael/build_malizia/mirall-build/_CPack_Packages/unused/NSIS/NSISOutput.log for errors
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: ownCloud
make: *** [package] Erreur 1

when i check the log 
i find this error :

!include: closed: "/usr/share/nsis/Include/UAC.nsh"
!include: could not find: "nsProcess.nsh"
Error in script "/home/wael/build_malizia/mirall-build/_CPack_Packages/unused/NSIS/project.nsi" on line 100 -- aborting creation process

can  any one help  

Thanks

**Comment by danimo** [comment]
Please build from the 1.8 branch or install the mingw32-cross-nsis-plugin-nsprocess. master is currently not stable. Chances are that you want to build 1.8.
