### ISSUE TITLE
Version 1.8.0 - Sync problem with filenames using native characters ÆØÅæøå

### ISSUE THREAD

**Issue by osos** [owncloud/client#2972]
After upgrading to version Sync-Client 1.8.0 on Linux Mint 17.1 (aka Ubuntu 14.04), the sync fails with error: Filename encoding is not valid on several files containing the danish letters æøå

**Comment by dragotin** [comment]
@osos can you provide a logfile snippet?

**Comment by guruz** [comment]
Also, which server version etc?
Which file systems?

**Comment by osos** [comment]
Is this what you need?

03-17 14:37:36:284 0x19336f0   ** error Strings:  ("Studiet/2. år/Retslære/Andres/Lektion_1/H�ilund_eks.opg..doc: Filename encoding is not valid", "Studiet/2. år/Retslære/Andres/Lektion_1/Retf�rdighed.doc: Filename encoding is not valid", "Studiet/2. år/Retslære/Andres/Lektion_2/H�ilund_eks.opg..doc: Filename encoding is not valid", "Studiet/2. år/Retslære/Andres/Lektion_5/UfR_1974.952�(Sigvaldi).doc: Filename encoding is not valid", "Studiet/2. år/Retslære/Forelæsning/T�nketekster_til_realisme.html: Filename encoding is not valid", "Studiet/2. år/Strafferet/Andres/Hold 5/documents.zip_FILES/��_158_-_159_-_efter�r_2006.doc: Filename encoding is not valid", "Studiet/2. år/Strafferet/Andres/Hold 5/documents.zip_FILES/��_164_-_165_-_efter�ret_2006.doc: Filename encoding is not valid", "Studiet/2. år/Strafferet/Andres/Hold 5/documents.zip_FILES/��_180_-_182_-_efter�ret_2006.doc: Filename encoding is not valid", "Studiet/2. år/Strafferet/Andres/Hold 5/documents.zip_FILES/��_216_-_217_-_efter�ret_2006.doc: Filename encoding is not valid", "Studiet/2. år/Strafferet/Andres/Hold 5/documents.zip_FILES/��_244-250_&_252_-_253_-_efter�ret_2006.doc: Filename encoding is not valid", "Studiet/2. år/Strafferet/Andres/Hold 5/documents.zip_FILES/��_260_-261_&_266_-_efter�ret_2006.doc: Filename encoding is not valid", "Studiet/2. år/Strafferet/Andres/Hold 5/documents.zip_FILES/��_276_-_278_-_efter�ret_2006.doc: Filename encoding is not valid") 
03-17 14:37:36:284 0x19336f0     * owncloud csync thread finished with error 
03-17 14:37:36:284 0x19336f0 the last 2 syncs failed 



Actually I see that some of the foldernames contain å, like in "2. år".

**Comment by ogoffart** [comment]
The error was added because of bug #2649

what is your locale?  and what is the encoding of the file name on your file system?  Could it be different?

**Comment by osos** [comment]
Server version: 8.0.2 on Ubuntu 14.04 server
Locale: da_DK.UTF-8 - on both server and desktop
Not sure if file system could be different, however, with sync client 1.7.1 there was no problems.

**Comment by ogoffart** [comment]
`Studiet/2. år/Strafferet/Andres/Hold 5/documents.zip_FILES/��158-159-efter�r_2006.doc`

As you can see in this filename, the `2. år` in the path is properly encoded, but not the file name.
What is the real name of that file in the file system?
Ar the files in the server as well?

**Comment by osos** [comment]
Investigating it actually seems that these files were simply ignored by the 1.7.1 client (or at least it didn't throw an error in my face). The files are not present on the server or on backups. It actually seems that the filesystem has labelled these files with invalid encoding, however, not causing troubles until now.

It seems that ownCloud client actually handles this the right way after all. Sorry for the noise.
