### ISSUE TITLE
Get Connection Closed after a few hours

### ISSUE THREAD

**Issue by drsbaitso** [owncloud/client#2973]
Running the 1.8.0 rc1 on Windows 7 with OC 8.0.2 and after a couple hours the client just hangs and says Connection Closed.  If I exit and reopen the client it syncs right up again only to bomb out after a couple hours.

**Comment by drsbaitso** [comment]
Happens with 1.8.0 final as well.  I'll attach the log next time it happens.

**Comment by guruz** [comment]
Do you know if your PC goes to sleep in the meanwhile or anything else that is unusual?

**Comment by drsbaitso** [comment]
Well, I haven't gotten this since a reboot of the VM (around a day now).  The VM was not going to sleep so that wasn't the issue.  Might have been something else.

I think you can close this for the time being.  If it happens again I can post a log of it.

**Comment by drsbaitso** [comment]
I take that back, just crapped out.

```
03-18 12:14:07:370 0x44f0918 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag
03-18 12:14:18:914 0x44f0918 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for  QUrl( "https://example.com" )  querying "status.php"
03-18 12:14:18:914 0x44f0918 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 2 "Connection closed"
03-18 12:14:18:914 0x44f0918 OCC::CheckServerJob::finished: error: status.php replied  0 ""
```

I can browse to the server so it's not offline.  Also, if I restart the client right away it connects right up.

**Comment by nekoal** [comment]
I saw today something simular with client build 1.8 nightly 4827 on Windows 7 (OC 7.0.4). Usually my connection lost 'cause dynamic server ip changes and old value still in dns cache. But today connection was closed without ip changed. Sleep mode configured don't start automatically.

**Comment by ckamm** [comment]
@drsbaitso That sounds really similar to #2899 and #2895 with the bonus of not even needing to sleep to trigger it. It's likely a bug in Qt. We'll check if we can do something to fix it and/or work around it.

**Comment by ckamm** [comment]
@drsbaitso I just pushed a possible workaround. Could you try again with tomorrow's build from http://download.owncloud.com/desktop/daily/ ?

**Comment by drsbaitso** [comment]
@ckamm will do

**Comment by drsbaitso** [comment]
@ckamm haven't seen the issue through the past couple of days, so I think the workaround did it

**Comment by guruz** [comment]
@nekoal Can you also confirm it is fixed?

**Comment by nekoal** [comment]
I can't neither confirm nor deny such rare issue. For now it was 1 time in 12 days of using build 4827.

**Comment by ckamm** [comment]
@drsbaitso @nekoal Thanks for testing! It's somewhat surprising because it didn't help for #2895. But then the symptoms were also different (Connection closed here vs timeout there) even if the cause was the same.

Please reopen if you see this problem again!
