### ISSUE TITLE
[Linux] [DWM window manager] Status bar icon is not transparent

### ISSUE THREAD

**Issue by blaskovic** [owncloud/client#2974]
After update to version 1.8 I have ugly status bar icon which is not transparent anymore.

Running:

    owncloud-client-1.8.0-2.1.x86_64
    fedora-release-21-2.noarch

I have DWM as a window manager.

![screenshot](http://www.blaskovic.sk/data/screenshot-6039-1426605442.png)

**Comment by guruz** [comment]
Can you edit your bug and description to specify desktop environment etc?

**Comment by blaskovic** [comment]
Updated.

**Comment by ogoffart** [comment]
What is the Qt version used for the package?

**Comment by mrbanie** [comment]
Same problem here with i3wm.
I think it's using Qt 5.4

**Comment by blaskovic** [comment]
qt5 here

**Comment by ckamm** [comment]
I looked at it briefly and would guess it's an interaction of your wm with the systray code in Qt.

**Comment by blaskovic** [comment]
So, will it be fixed in owncloud client or should I file bug to my WM systray implementation?

**Comment by ckamm** [comment]
@blaskovic I can't tell for sure. There are a bunch of systray bugs (#2511, #2123) and the issues are usually related to the different tray standards (at least three by now) and issues with their implementation in Qt or the WM.

**Comment by blaskovic** [comment]
I am using DWM with this systray patch:
http://dwm.suckless.org/patches/systray

Maybe it will be helpful somehow :)

**Comment by guruz** [comment]
Possible fixes inside Qt:
```
<olivier> but yes, there is 38abd653774aa0b3c5cdfd9a8b78619605230726
<olivier> Task-number: QTBUG-31762
<olivier> also 2203d9d93e24e00d6e9bc9bda0e65a0c7f9923cc  (Task-number: QTBUG-35832) Fix transparent tray backgrounds with 24bpp tray visuals
```

**Comment by ogoffart** [comment]
Is it still a problem with Qt 5.5?

**Comment by ogoffart** [comment]
Closing issue  (this is most likely a Qt issue anyway)
