### ISSUE TITLE
FeatureRequest: Add icon for contextmenu entry in Windows explorer 

### ISSUE THREAD

**Issue by Siedlerchr** [owncloud/client#2975]
Hi,

thanks for the great work, I just installed 1.8.0 and I really like the new "share via owncloud" feature in contextmenu. However it would be better and easier to find, if you could add an icon, like other software does, for example winrar, tartoise svn.
Here is an example screenshot of my contextmenu on windows:

Edit// I just saw this was already posted: #2856

![oclsharecontextmenu](https://cloud.githubusercontent.com/assets/320228/6693287/1c8263dc-ccd2-11e4-9387-9165b38314c5.png)

Regards
siedlerchr

**Comment by guruz** [comment]
Note that this icon might need to be themed.

The OS X client already has a method to tell the Finder plugin where to find theme-specific icons.

**Comment by TheOneRing** [comment]
We plan to deprecate the shell extension and focus on the cloud file api.
I think https://github.com/owncloud/client/issues/7746 supersedes this issue now.
@michaelstingl

**Comment by michaelstingl** [comment]
Yeah, support limited to latest Win versions is okay. 👍
