### ISSUE TITLE
OSX Yosemite bar

### ISSUE THREAD

**Issue by l0ngestever** [owncloud/client#2977]
Please change the icon to the Yosemite theme, with black and white.

![schermafbeelding 2015-03-17 om 20 48 47](https://cloud.githubusercontent.com/assets/6254028/6696125/1a6ea96a-cce7-11e4-8186-e09d0a503e4c.png)

**Comment by blizzz** [comment]
You can change to monochrome icons in the settings.

**Comment by l0ngestever** [comment]
Awesome! Sorry for opening this issue!
