### ISSUE TITLE
Be able to move whole sync folder

### ISSUE THREAD

**Issue by timmie** [owncloud/client#298]
Owncloud creates the primary sync folder at 

~/owncloud

If I move it to /opt the program does not finde it any more.

I would love to see a folder administration option in the client menu.

Thanks

**Comment by Foggalong** [comment]
This is a feature I'd like too. Was there ever any progress on implementing such a thing?

**Comment by phil-davis** [comment]
I also had someone ask me about this last week. You can:
a) Stop syncing to /xyz/folder1
b) Move or rename the folder tree to be some new folder in a new place /abc/folder2
c) Setup the sync again, this time to /abc/folder2
It should find the existing files and work out that they are up-to-date without doing a full re-download.
An automated place to do this would be handy for the "mere-mortal" user.

**Comment by Foggalong** [comment]
You might actually be able to help me with my problem. As I've moved more and more of my things over to ownCloud my `~/` has just become mostly symlinks to folder in `~/ownCloud`. I figured for simplicities sake it would be nice to just have `~/` be my ownCloud folder directly.

![screenshot_2015-08-30_18-57-09](https://cloud.githubusercontent.com/assets/5920259/9568694/008e4a16-4f49-11e5-8eca-3113c5ebb049.png)

I'd like this to be what I see in `~/` with the addition of `~/Downloads` which I don't want to sync. I wouldn't want any of the hidden files or folders to sync either.

![screenshot_2015-08-30_18-57-21](https://cloud.githubusercontent.com/assets/5920259/9568693/0085cb20-4f49-11e5-8373-913a9087266d.png)

What would be the best way to set that up?

**Comment by SamuAlfageme** [comment]
Related to https://github.com/owncloud/client/issues/5387

**Comment by JacquesLeRoux** [comment]
Thanks " phil-davis commented Aug 30, 2015", works like a charm :)

**Comment by robin48gx** [comment]
> Hello,
> 
> you can tell the programm to sync the folder /opt/owncloud rather than ~/owncloud.
> 
> I know that dropbox is offering this feature. But if you have the folder initially in the right place there is no reason to move it to an other place. If it is required anyway you can remove the old sync and set up a new one with the new local directory...it just needs some time to download all the files from the server.
> 
> Did I understand your request correct or is it something else you would like to do?
> 
> Best regards
> 
> Martin

trouble is when you first get it going you maybe unaware of the location it intends to use as default. Esp if there was an old ownCloud folder in there (I assumed it would read config from the old one) . It would be nice to have an easy way to move the sync folder.

**Comment by michaelstingl** [comment]
Docs:
- https://doc.owncloud.com/desktop/5.0/faq.html#i-want-to-move-my-local-sync-folder

**Comment by DeepDiver1975** [comment]
https://doc.owncloud.com/desktop/5.3/faq.html#i-want-to-move-my-local-sync-folder
