### ISSUE TITLE
owncloud desktop 1.8

### ISSUE THREAD

**Issue by esquad18** [owncloud/client#2982]
I installed the new owncloud desktop 1.8 on Windows 7 Pro SP1.
But i don't see, when i right click on a file or a folder, the dialog "owncloud Sharing". 
The Owncloud server is version 7.04 (but it's the same when i test with the server "demo.owncloud.org").

thx

**Comment by strugee** [comment]
Please rename this issue. "owncloud desktop 1.8" is completely undescriptive as a title. The more specific and useful your issue title is, the faster ownCloud developers will be able to triage and fix your issue.

**Comment by RealRancor** [comment]
Also consider to restart your computer to get all needed dependencies loaded.

**Comment by esquad18** [comment]
it's ok after a reboot, thanks (and sorry for the issue name, do better next time).
