### ISSUE TITLE
Windows Client Crashes

### ISSUE THREAD

**Issue by paul-kelly** [owncloud/client#2991]
I have a new install of OwnCloud running on Centos and have tried to use the client in a Win7 and Win10 PC.  In both cases, asfter a few gb's, the client crashes.

I am trying to sync 40gb of data.

Error reports have been sent

**Comment by nekoal** [comment]
It seems simular to my case. But my owncloud hosted on other OS. Are you expirience other facts after client crash? Doubling folders in web interface? Deletion some files in folder which was syncronize in progress at crash time? At least, you need write client and server versions here.

**Comment by paul-kelly** [comment]
Hiya,

it is a brand new install, done yesterday, so running 8.0.1 (cant auto
upgrade to 8.0.2 due to error!)

On 21 March 2015 at 06:44, nekoal <notifications@github.com> wrote:

> It seems simular to my case. But my owncloud hosted on other OS. Are you
> expirience other facts after client crash? Doubling folders in web
> interface? Deletion some files in folder which was syncronize in progress
> at crash time? At least, you need write client and server versions here.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/2991#issuecomment-84266901>.
>



-- 

Paul
Skype: paul.kelly
Mobile: +44 (0)7850 350627

**Comment by guruz** [comment]
@paul-kelly @nekoal What's the amount of files you have? Can you use task manager to see if the clients memory usage is growing?

CC @jturcotte @ogoffart

**Comment by paul-kelly** [comment]
I am trying to move about 40gb.

There is enough capacity on the hard drive.

Does the client treat all of the files as one, in relation to upload limits
on the server/php settings?

On 23 March 2015 at 15:03, Markus Goetz <notifications@github.com> wrote:

> @paul-kelly <https://github.com/paul-kelly> @nekoal
> <https://github.com/nekoal> What's the amount of files you have? Can you
> use task manager to see if the clients memory usage is growing?
>
> CC @jturcotte <https://github.com/jturcotte> @ogoffart
> <https://github.com/ogoffart>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/2991#issuecomment-85039143>.
>



-- 

Paul
Skype: paul.kelly
Mobile: +44 (0)7850 350627

**Comment by guruz** [comment]
@paul-kelly I mean the amount of files not the size. You could find out for example with:
```find /path/to/your/owncloud/data/dir | wc -l```

**Comment by jturcotte** [comment]
From the few crash reports that I saw, this one was the only upload-related crash: #2984

The fix should be in the next 1.8 nightly at http://download.owncloud.com/desktop/daily/

It would be great if you could try again with the next build.

**Comment by paul-kelly** [comment]
Just tried again and it floats at about 130md of memory

On 23 March 2015 at 15:13, Paul Kelly <paul@kelly.eu.com> wrote:

> I am trying to move about 40gb.
>
> There is enough capacity on the hard drive.
>
> Does the client treat all of the files as one, in relation to upload
> limits on the server/php settings?
>
> On 23 March 2015 at 15:03, Markus Goetz <notifications@github.com> wrote:
>
>> @paul-kelly <https://github.com/paul-kelly> @nekoal
>> <https://github.com/nekoal> What's the amount of files you have? Can you
>> use task manager to see if the clients memory usage is growing?
>>
>> CC @jturcotte <https://github.com/jturcotte> @ogoffart
>> <https://github.com/ogoffart>
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/owncloud/client/issues/2991#issuecomment-85039143>.
>>
>
>
>
> --
>
> Paul
> Skype: paul.kelly
> Mobile: +44 (0)7850 350627
>



-- 

Paul
Skype: paul.kelly
Mobile: +44 (0)7850 350627

**Comment by nekoal** [comment]
My folder had size 55,1 Gib with 123742 files and 2898 subfolders. Then I move out 2 subfolders with more than 100 thousands small files (average size less 1KiB). Now folder have size 44,1 GiB with 17549 files and 1720 subfolders. I did't check client memory usage before crash 'cause system monitor shows about 5,5 GiB avaiable RAM when sync on pause.

**Comment by guruz** [comment]
@paul-kelly @nekoal Would you test this build: http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.4933-nightly20150408-setup.exe

**Comment by guruz** [comment]
I'm closing this for now, expecting that it is fixed with 1.8.1rc2 (or the release 1.8.1 tomorrow)
