### ISSUE TITLE
Permanent .conflict-files with Federated Folders

### ISSUE THREAD

**Issue by iprigger** [owncloud/client#2992]
Environment: Mac OS X 10.10.3 (Beta)
Macbook Pro 13" (Retina)
Sync Client Version: 1.8.0.

Issue:
When working on Microsoft Word docx or any other file, there are always generated .conflict files. The open file hereby is renamed to .conflict.

This is new since 1.8.0.

**Comment by guruz** [comment]
Because it was changed on the server in the meanwhile?

**Comment by iprigger** [comment]
Nope.


--
E = M * C^2 +/- 3db

**Comment by guruz** [comment]
We need more info here. Could you create a log file? https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

**Comment by dragotin** [comment]
I tried on Mac I could not reproduce it.

**Comment by iprigger** [comment]
Hi,

Have you tried with synced federated folder, too?

Tobias

--
E = M * C^2 +/- 3db

**Comment by ogoffart** [comment]
Maybe related to #2577 ?

**Comment by iprigger** [comment]
looks a bit like it - have experienced it with omnigraffle (flat)-Files and docx / xlsx files.

Tobias

--
E = M * C^2 +/- 3db

**Comment by guruz** [comment]
@iprigger Can't help you more for now if you don't provide any more info (not even server version)

CC @icewind1991 @PVince81 Possible issue with federated syncing, possibly not.

**Comment by guruz** [comment]
@iprigger Does it work when syncing directly to the target oC instance?

**Comment by iprigger** [comment]
yes, it does.

Tobias

--
E = M * C^2 +/- 3db

**Comment by PVince81** [comment]
@iprigger what ownCloud servers version are you using ? What is the version of the connecting server (yours) and the target server (the one that shared with you) ?

**Comment by iprigger** [comment]
both (now) 8.0.3

Tobias

--
E = M * C^2 +/- 3db

**Comment by PVince81** [comment]
@iprigger can you confirm that you are using the federation feature (through shares) and not external storage ? (there is an app called "external storage" that also allows you to mount remote ownClouds)

There is a known bug when using the backend "ownCloud" in external storage: https://github.com/owncloud/core/issues/15125

**Comment by iprigger** [comment]
... well, in that case: that may be the problem....

Tobias

--
E = M * C^2 +/- 3db

**Comment by PVince81** [comment]
Note that this doesn't affect federation, which works by sharing a file with link and as recipient clicking "Add to ownCloud"

**Comment by dragotin** [comment]
Anyway, this seems to be a server problem much more than a client issue. Please reopen this in the core issue tracker. Thanks & sorry!

**Comment by PVince81** [comment]
Actually it seemed to be broken for s2s folders too.

PR here https://github.com/owncloud/core/pull/15895
