### ISSUE TITLE
[Windows] Client unresponsive

### ISSUE THREAD

**Issue by StephaneDupont** [owncloud/client#2993]
The owncloud client is unresponsive, even when not syncing.

To be more accurate, it's unresponsive for about 10 seconds, then it's responsive again for a few seconds, then again unresponsive, etc.

Details :

- When I click on the icon in the windows notification area, it takes 4-5 seconds for the client to be displayed

- In the client, I've got 6 folders configured: if I click on a folder name, or switch to another tab (activity, network, ...), it takes 2-3 seconds for the folder to be selected or the tab to be displayed. Then, after something like 10 seconds, it become responsive and I can click on a folder or a tab without any delay. Then a few seconds later, it become unresponsive again. Then responsive. Then unresponsive. Etc. Sometimes, I even got the "the program has stopped responding" from windows. When unresponsive, the client doesn't even sync, it seems to do nothing.

- Windows 7 64bits, owncloud client v1.8.0, server v8.0.2, Windows performance indice: 7.5 (not a slow computer!)

- When it's not responsive, it doesn't use CPU (0~2% in the task manager)

**Comment by trampi** [comment]
I've got the same symptoms.

**Comment by unclejamal3000** [comment]
I have the same. Windows 7 SP1 and Windows 8.1
Client 1.8.0 (build 4847)

**Comment by guruz** [comment]
Just to get some more data here, can you provide information how big (how many files) are your sync folders and if you have any external storage configured on the server?
And everything else you think can influence this..

**Comment by unclejamal3000** [comment]
224 files, 11 folders in my account. No external storage, but a shared folder with a second user.
Server is Owncloud 8.0.2

Just installed the nightly build (b 4857) from today. No problems with this version up to now.

**Comment by dragotin** [comment]
Note: The nightly builds contain the QNAM reset that @ckamm added in  57c14a0ebab56c322fe2b42e33e557cc42a70781 Maybe that helps here.

**Comment by guruz** [comment]
@strehlst @trampi @StephaneDupont http://download.owncloud.com/desktop/daily/ Can you also try the nightly build? Can you also tell me your proxy settings?

**Comment by StephaneDupont** [comment]
I've got 6 folders, something like 30.000 files and a total of 190Go. No external storage.

I'll try the nightly build and keep you posted.

**Comment by StephaneDupont** [comment]
Nightly build didn't help.

**Comment by guruz** [comment]
@StephaneDupont And the proxy settings? What did you set in the oC configuration? Does your network  use a proxy?

**Comment by StephaneDupont** [comment]
Nope, no proxy.

**Comment by StephaneDupont** [comment]
Oh, I'll be damned, it seems to work now: the proxy settings was on "Use system default" (or something like that, my UI is not in english). I put it on "No proxy" and it works.

The strange thing is I don't think there's a proxy in my "system default"...

**Comment by guruz** [comment]
We'd need a log file from you guys to see where it is blocking the UI
https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

**Comment by guruz** [comment]
@strehlst @trampi Could you please try https://github.com/owncloud/client/issues/2993#issuecomment-85049804

**Comment by StephaneDupont** [comment]
Yes, I'm confirming it: I've got no proxy configured, but putting from "use system default" to "no proxy" seems to fix it. @trampi, @unclejamal3000 does that fix it for you too?

**Comment by strehlst** [comment]
@guruz Sorry, not possible right now.

**Comment by trampi** [comment]
I'll test it later today and post the log. Thanks for keeping us up to date and responding so fast!

**Comment by unclejamal3000** [comment]
My proxy settings are on "Use system default". I still have no problems anymore with this configuration in the company network (with proxy) as well as at home (no proxy).

**Comment by unclejamal3000** [comment]
My proxy settings are on "Use system default". I still have no problems anymore with this configuration in the company network (with proxy) as well as at home (no proxy).

**Comment by trampi** [comment]
https://github.com/owncloud/client/issues/2993#issuecomment-85049804 fixes the problem for me as well...

**Comment by guruz** [comment]
Thanks guys. Probably related to https://bugreports.qt.io/browse/QTBUG-27656

**Comment by guruz** [comment]
Could I ask you guys to switch to change your proxy detection settings _back to automatic_ and then try http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.4863-nightly20150325-setup.exe ?

**Comment by unclejamal3000** [comment]
With build 4863 I generally I have the problem that I get no connection to the OC server anymore. The client wants to connect to the proxy (which is our company proxy) although I'm currently in a public network without proxy (and the PAC file is not reachable). But no UI freeze ;-)

Logfile is here:
https://gist.github.com/unclejamal3000/f14c496f006da3f3a6b0

Proxy configuration is "Use System-Proxy"

**Comment by guruz** [comment]
@unclejamal3000 This is interesting because on line 73 you can see:
```
03-25 10:19:36:983 0x7620000 OCC::SystemProxyRunnable::run: virtual void OCC::SystemProxyRunnable::run() 1 proxies:  (HttpProxy ""172.28.12.5":8080" ["Tunnel Caching NameLookup"])
03-25 10:19:36:985 0x3fb3b0 OCC::ConnectionValidator::systemProxyLookupDone: void OCC::ConnectionValidator::systemProxyLookupDone(const QNetworkProxy&) Setting QNAM proxy to be system proxy HttpProxy  " "172.28.12.5" : 8080 "  [ "Tunnel Caching NameLookup" ]
```
How can it still detect that proxy?

**Comment by guruz** [comment]
@unclejamal3000 So when you moved away from the company network the client was still running?
Or that was with a freshly run client?
Does restarting the client fix it?

@danimo is working on providing a new ```QtNetwork``` DLL, the current one might have a glitch with the windows proxy lookup.

**Comment by unclejamal3000** [comment]
Yes that was also confusing me. I tried to download our PAC file (as it might be accessible over Internet by mistake), but that failed.
I have no problem with Chrome on the same machine which is also configured to use computer's system proxy settings.

@guruz I was already outside the company today when I updated to build 4863. So the client had a fresh start.  But before I was in a VPN connection and didn't reboot the machine in between. Restarting the client didn't fix it.

**Comment by guruz** [comment]
@unclejamal3000 Here it is: http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.4864-nightly20150325-setup.exe
Thanks @danimo

**Comment by StephaneDupont** [comment]
Yep, tried this build, seems to be fixed. Is this build stable for production use, or must I reverse to the stable version?

**Comment by danimo** [comment]
We will repackage 1.8.0 to include the updated 3rd party libs. This one is the same, i.e. it's stable.

**Comment by unclejamal3000** [comment]
I can also confirm, that the problem with the UI freeze is solved with build 4864. Also the problem with the cached proxy is solved with this build.

But I sill have problem with changing the network without restarting the client -> #2695

**Comment by guruz** [comment]
Thanks guys for testing!

**Comment by dragotin** [comment]
Out with an updated build. (build id 4893)
