### ISSUE TITLE
Add option for the dark/black monochrome icon

### ISSUE THREAD

**Issue by Aentfs** [owncloud/client#2994]
I'm under Plasma 5 and the new theme now mostly has black systray icons while the client monochrome icon defaults to white icons. The color of the monochrome icon should be a setting instead of default black for KDE as there are black themes as well. Even breeze the default theme for plasma 5 comes in bright and dark.

**Comment by danimo** [comment]
What should really be happening is described in #940. No more special hacks, sorry.
