### ISSUE TITLE
Regression: Needs to reenter password (Qt4 -> Qt5)

### ISSUE THREAD

**Issue by hefee** [owncloud/client#2996]
I updated from 1.7.1 to 1.8.0 and had to renenter my password for owncloud. I'm using KDE together with kwallet. I looked at kwallet and the entry was added:

old:
  USER:https//OWNCLOUDURL

new:
  USER:https//OWNCLOUDURL/

So i would think, that _account->url().toString() [src/libsync/creds/httpcredentials.cpp] changed it behaviour and now gives a suffix "/".

I quite sure that this is an issue of qt4 -> qt5 upgrade and is not an issue of (1.7.1->1.8.0).

**Comment by ogoffart** [comment]
AbstractCredentials::keychainKey is adding the '/' ad the end for a year now. I suppose the old key was from 1.6 or something.

**Comment by guruz** [comment]
@dragotin Is this the regression you talked about this morning?

**Comment by dragotin** [comment]
Maybe the trailing / does not come from ::keychainKey but from a folder that is added and is not empty as before, but "/".

**Comment by ogoffart** [comment]
As i said, the trailing slash is added by AbstractCredentials::keychainKey and is there for a long time.  So the entry without the slash must be very old.

**Comment by ogoffart** [comment]
Can this really be reproduce only by switching from Qt4 to Qt5?  or even switching from 1.7 to 1.8?

**Comment by hefee** [comment]
I was quite sure that is wan't an issue with a qt4 build, but there i havn't look deeply enough. It is right the tailing slash comes from AbstractCredentials::keychainKey and from a QUrl

**Comment by guruz** [comment]
Sorry, let's not complicate the code if we don't know for sure this comes with the Qt4->Qt5 update scenario..
