### ISSUE TITLE
Too excessive read of owncloud window client: x50 times as many as dropbox?

### ISSUE THREAD

**Issue by zephyrus00jp** [owncloud/client#3001]
Too excessive read of owncloud window client: x50 times as many as dropbox?

Thank you for making this great package available for user community.

I have noticed that owncloud client does excessive amount of read (and maybe write, too.)
under Windows.

During the reading, my PC slows down considerably, maybe due to its poor I/O capability.

Environment:

The local host is Windows 7, 64-bit.
Windows client is version 1.7.1 (build 4382)
The ownCloud server version: ownCloud 7.0.4+dfsg-2 (Debian) (stable) [on remote linux machine.]

Here is the data from the Windows task manager:

For comparison of the I/O traffic on local Windows7 PC,
I picked up the data for ownclud, dropbox and virtualbox, where I run linux
for some programs like emacs, etc. and where I generate most of new data and text files, 
that I put into Dropbox occasionally and
to owncloud much less frequently for archiving purposes.

My owncloud server, which runs on a remote linux PC, manages 31GB partion of which 15GB (48.4%) is used
according to the message I see in display of local owncloud client.
In comaprison, Dropbox manages 2GB (maximum for free account).

Now, one may be tempted to think that owncloud client generates about 8-16 times as many I/O 
as dropbox due to the managed amount of files.

You are dead *WRONG*.

Here is the data: 

name      |working memory|	I/O READ          | I/O write
----------|---------------|-----------------------|--------------------
owncloud  |	103,264K  |     1,878,921,719,004 |    18,048,116,707
dropbox	  |	 38,472K  |	    1,187,814,575 |  	  318,784,348
virtualbox|      70,220K  |         2,503,776,254 |     4,596,570,582

Ignoring the sub-MiB value, I get the following number after rounding:
owncloud: 1878922 MiB read, 18048 MiB write,
dropbox:     1188 MiB read,   319 MiB write.

Note the amount of read of owncloud
which is almost *1000 times* as many as that of dropbox 
(actually close to 2000 times).

(cf. I view the numbers for vitualbox reasonable since I do lots of 
editing and compile/test runs ofsome tools there. Testing generates lot of writes.)

Now, since my owncloud manages about 35GB of data as compared to
2 GB of dropbox (the free version), I would expect the I/O amount of I/O of owncloud 
to be x 20 at most. 
Considering this, owncloud does about x100 as many READ as my naive educated guess.
[And I don't change the data under owncloud directory that often. I think scanning
the whole directory after the power-up of the machine would be necessary, but after that
I have not changed much data at all...]

Isn't there a fundamental design flaw or
most likely an implementation flaw in the code to detect local changes on the window client?
(Like not using fnotify-like feature [available in linux] under Windows7? 
Isn't there a call-back like function in Windows7 that allows one to monitor 
the file system change without reading all the data or even the directory entries
in the managed directory?)

I am reporting this just so that everyone in the developer community is aware of this efficiency issue.

I just noticed that server 8.0.2 is available, and if the change of the server solves the issue,
I would be happy to take the trouble to change the server: a hassle to be sure, but will be worth it.
(But since this is an issue of "READ" under the windows client, I doubt the server change fixes the issue.)

If other people don't see this extraordinary amount of I/O (especially READ) under windows, I think
I need to dig deeper why I have this much extra I/O than others. 
Maybe some blacklisted files such as *~, etc.
are causing excessive read, for example [but I think 
these files are NOT read at all.]

 
TIA

PS: I checked  bug reports for the last three months, and  it is possible that this may be related to
https://github.com/owncloud/client/issues/2961
 Windows 1.7 client constantly re-syncing -- can't delete files without them re-syncing #2961 
(I don't have .eml files there: I don't store mail files there. Nor I don't seem to see
the deletion errors in the log.)

But I don't think my problem is related to "constantly re-syncing", but I am not sure how to determine exactly
whether my client is "constantly re-synching".

My impression is that ownCloud is behaving normally and it simply reads the files too often than necessary IMHO.

PPS: I would love to offer the log, but some filenames obviously represent product names and project names which I may have to keep confidential :-(
This is a growing pain: as soon as open source product is put into production, one is using it for important
real-life files, and sometimes it is difficult to offer logs. The filenames indicate quite well 
what one is up to in actual business activity :-(

**Comment by guruz** [comment]
(One of the theories for this bug is that using Qt's file iteration API will help since it uses the Windows native API and not the Windows POSIX API https://github.com/owncloud/client/issues/60#issuecomment-70245354 )

**Comment by zephyrus00jp** [comment]
I am sorry that I am not that familiar with Windows programming and can't offer help here, but
I was under the impression that 
 - Dropbox stores a meta data such as the hash of the content of the file that it once read (and when it was read) so that it does not have to read the file again if its modification time stamp is not changed locally. Thus Dropbox can avoid unnecessary read.

Does ownCloud do something similar on the client side?

Oh, I see, under Windows 7, I noticed
.csync_journal.db* files
They must play the role of Dropbox's client-side meta-data cache.

I have a question here: is it possible that the comparison of the file names stored in these
database and the scanned file's pathname at run-time may not match?

BACKGROUND:
I have seen the discussion that
under Windows there seem to be manner of representing
long pathfile in one way so that it won't trigger the pathname limit, etc.
If so, isn't there a chance that the runtime comparison is performed against  the pathname in one representation format in the meta data database and 
and another pathname (for the same file) but in the other represenatation [which is scanned off the directory tentatively], and owncloud client 
thinks that the file's metadata is not in the cached database, 
and decides to reads the file again and stores
the meta data with the pathname in THE OTHER representation,
later when it scans the directory  next time, not
finding the entry due to the mismatch of representation of the pathname, it tries to read the file again to create the meta data and stores it into the meta database in the other filename, etc.,  ad infinitum....

**Comment by guruz** [comment]
@zephyrus00jp BTW, we have nightlies of the 2.0 client available now. They have some possible improvements in this area (with more to come).
If you have backups you can try those nightly builds.

Would be interesting to see if things are improved for you..

http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.5264-nightly20150713-setup.exe

**Comment by massimoi** [comment]
+1

**Comment by zephyrus00jp** [comment]
Strange. I thought I left a comment in this bug thread yesterday that explains
that I have not seen the excessive I/O since around the beginning of July (or probably middle of June).

This may be explained by the slightly newer version of the client, and also,
I upgraded the owncloud server on the linux in mid-June, but I think the I/O volume decreased
even before that. 

So something in the client for Windows changed for the better.

I am monitoring this I/O volume issues still, and if I notice anything strange
I will report a follow-up article.

TIA

**Comment by dragotin** [comment]
@zephyrus00jp comparing Dropbox and ownCloud Client this way is not really feasible. We still do a rescan of the local repository at every sync run, which is not optimal, but identified and to be changed in the future, refer to #3408

How did you measure the I/O volume, would you share that with us? Thanks!

**Comment by zephyrus00jp** [comment]
Thank you for the pointer to #3408 
I think if some kind of file change notification works, then we should go for it.

>How did you measure the I/O volume, would you share that with us? Thanks!

I used Windows task monitor's process listing. 
I am attaching a screen shot: it is shown in Japanese locale,
 I added a few captions. In order to get the cumulative I/O, in this case, Input, i.e., read,
you have to select the column by [Display] -> [Selection of Column (not sure what the correct English menu is since mine shows Japanese menu.]. By default, it is not shown.
![Uploading dropbox-too-much-read.png…]()

**Comment by zephyrus00jp** [comment]
Hi, I have no idea if my attemp to attach the screen listing of the cumulative read amount succeeded or not. If someone is interested, please let me know. It is only less than 200KB since it is basically a listing of process names and numbers by characters.
TIA

**Comment by zephyrus00jp** [comment]
Sorry for small message spam. Considering that the amount of I/O is like x 40 of Dropbox  today, (and if my simple calculation based on Dropbox's size (2GB) vs ownCloud using about 16GB now, I would expect about x8 times as much I/O activity in the long run. So it is still way too large (x 5 times more than theoretically expected naive value), but it is much better than the number a few months ago (x50 times!).
This number may become worse as time goes by. This is because as was noted in the above, the entire file folder is read
if something changes, and so the number could become worse if I let Windows run without shutdown and this may be the reason for the very bad number a few weeks ago. I don't shutdown, but I let the PC to sleep.
Some ideas mentioned in #3408 really ought to be tried.
(I also have a feeling that owncloud seems to read Not only the directory entries are read, but the CONTENT of each file is read even if the file time stamp / size should suggest that it has not been modified since the last time it was read for generating some hash value to detect change on the server  (even if the size does not change), etc. And that hash value ought to have been already stored in the local DB and so the content should not be read at all if the modification time and
size has not change (I add size just in case the local OS is a flakey. if one of them changes, we definitely should re-scan the whole content of the file and produce a new hash value.).

I suspect that the check for early exitm such as the unmodified file and black-listed files based on file suffix pattern,  in a busy loop reading file directory entries may be placed in the wrong place. Just a wild guess.
