### ISSUE TITLE
Discovering outside the sync folder

### ISSUE THREAD

**Issue by jzachwieja** [owncloud/client#3006]
Client version: 1.7
Build: FreeBSD binary packages
Folder to sync: /home/$USER/owncloud

Problem description:
After setting the owncloud client (mirall) to sync one particular directory, I can see the client repeatedly is 'Discovering' my entire home directory. It's scanning /home/$USER even though it's told to scan /home/$USER/owncloud.

Expected behaviour:
The client should NOT scan, discover or otherwise touch anything outside the folder to sync.

Additional information:
My home directory is BIG. It contains LOTS of files and the 'Discovery' is abuse of resources since it's constantly churning in the background. I'm not going to set 'Ignore' lists for stuff outside the sync folder. That's just insane.

In words of our favourite airborne reptile avenger:

"I don't remember asking you to discover a god damn thing!"

Regards,
grok

**Comment by ogoffart** [comment]
Normaly it should only discover in the folder that are sync'ed.
Can you please provide the logs (press F12 or run with --logwindow)
Also you can try 1.8

**Comment by jzachwieja** [comment]
I've added a remote SFTP connection that happens to be my home directory.

I've pondered on it for a while and then closed the issue in shame.

PS. When all else fails, invoke UX: perhaps it would be better for the user to be able to tell the difference between remote filesystems connected to the OC instance and local stuff but I'm clutching at straws here. ;)
