### ISSUE TITLE
[OSX][1.8.0] High CPU Usage

### ISSUE THREAD

**Issue by mcnesium** [owncloud/client#3007]
As a follow-up of #2479 this is a chart for my v1.8 CPU usage:

![oc8](https://cloud.githubusercontent.com/assets/476060/6782464/9d9f50fa-d174-11e4-9658-c06886874364.png)

During that one hour the system was almost completely idle. No sync action has been necessary. The divergence between 3:14 and 3:20 is due to me waking the client up from idling by tapping the touchpad and entering the password. No further actions have been made.

This is still on the C2D 2,2Ghz MBP running OSX Lion and I think the ~60% CPU usage peaks are way too high for this background type of application. The system fan never turns off completely and that should not be the case.

**Edit:** I have 15 sync folders containing 2482 subfolders and 14313 files total. Will run oc with logfile parameter later today…

**Comment by guruz** [comment]
Could you edit your bug report to also state again how many sync folders with how many files you have configured?
Did you check the log (start client with ```/Applications/owncloud.app/Contents/MacOS/owncloud --logfile -```) if it does actual sync runs or if the CPU load is caused by something else?

Please feel free to send me part of the log (best the parts that don't do a sync but still cause CPU) to my nickname here on github @ owncloud.com

**Comment by guruz** [comment]
@mcnesium Nightly for you: http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.2204-nightly20150325.pkg

**Comment by mcnesium** [comment]
And heres the new CPU Usage:

![oc-1 8 0 2204](https://cloud.githubusercontent.com/assets/476060/6823714/1436f958-d2eb-11e4-906b-380ee8ab2986.png)

I don't se much of a difference there. The link to the log is in your mailbox.

**Comment by ckamm** [comment]
Maybe a9a24c96fc0195ef8017284bf729b8554464501a is related.

**Comment by guruz** [comment]
http://download.owncloud.com/desktop/daily/ownCloud-1.8.0.2220-nightly20150325.pkg
Contains the commit above and the comment @ckamm has commented.
Feel free to try, for me it frees up 200msec per sync folder per ETag job.

**Comment by ckamm** [comment]
@mcnesium The patches helped for the similar bug #2990 :)

**Comment by mcnesium** [comment]
that one looks *much* better! Check out the Y-axis:

![oc-1 8 0 2220](https://cloud.githubusercontent.com/assets/476060/6845188/1a7aa22a-d3b2-11e4-9b64-c3f20e7e0cc7.png)

I am not sure if I actually did syncable stuff on the system at x=36:30 but at least it is calm if I do *not* do anything. Thank you very much for that fix :+1:

**Comment by guruz** [comment]
Terrific :)
Thanks for the bug reports.

**Comment by qnxor** [comment]
I'm still experiencing high CPU usage at idle with spikes every 60 seconds as I posted here: https://github.com/owncloud/core/issues/14873#issuecomment-86922562

I could give this nightly a try.

**Comment by qnxor** [comment]
build 2230 seems much better:

![CPU usage](https://dl.dropbox.com/s/ty908519f0oa29e/oc7.png)

Log file: https://dl.dropbox.com/s/i9qrtz7a0bnrrzp/oc7.log

**Comment by derkostka** [comment]
I still see nearly 80% CPU on my C2D Macbook with the App 1.8.4 and OSX 10.7.

-> I´m having thousands of small files synced and see that the client is scanning nearl the wohle time. Is this related ? What can i do ? 

Thanks!
