### ISSUE TITLE
owncloud mirall dns

### ISSUE THREAD

**Issue by FanchTheSystem** [owncloud/client#3009]
It look like mirall use sometime ip adress instead of dns to access owncloud install.

I am not sure why, but here is what it look like in apache log : 

```log
123.345.256.145 - - [23/Mar/2015:19:45:01 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 507 "-" "Mozilla/5.0 (Linux) mirall/1.8.0"
```

most of other request use  dns name to access my owncloud instance as client work well 

please could you add un checkbox in configuration to disable this ?

my ownclood install is not accessible by it ip adress (as I use several virtual host on this server)

**Comment by danimo** [comment]
Unless you modified the log format, the first entry is the _client_ IP/host, not the server host. Some of them do not have a reverse host name and hence do not resolve.

We run several ownCloud instances in vhosts that would not work without mirall properly transmitting the vhost. Your problem, should you have any, is elsewhere.
