### ISSUE TITLE
Mobile phone app for Blackberry and Ubuntu Phone.

### ISSUE THREAD

**Issue by vDorst** [owncloud/client#3012]
I was very happy to see the Android port of ownCloud on the Blackberry World.
But I was thinking. I should not that hard to convert this QT client for Blackberry OS 10.3.1 and later Ubuntu Phone.
Which both using QT/QML as a native language.
But start a new repo like Android and iOS or using this one and add the mobile phone parts?

**Comment by RealRancor** [comment]
Hi,

i think the issue/feature tracker for the desktop sync client is the wrong place to request a port to other platforms. Its probably better to ask / look around for experienced developers able to do this on the developers mailinglist: https://mailman.owncloud.org/mailman/listinfo/devel

**Comment by guruz** [comment]
> I should not that hard to convert this QT client for Blackberry OS 10.3.1 and later Ubuntu Phone.

Although the support for Qt widgets on the mobile is not that good, it would probably need a QML UI
