### ISSUE TITLE
Windows: Hide settings window when share dialog is shown

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/client#3015]
Please set the OCContextMenu Window to top most (Windows)

**Comment by jturcotte** [comment]
Could you explain what you mean?

OCContextMenu doesn't have a window of its own, the explorer context menu is created by explorer and we only get asked which menu to insert. That menu should be already top-most.

**Comment by pierrejochem** [comment]
Okay the thing is a little bit tricky ;-) This only happens if the client settings are open, then the share dialog is in the background.

**Comment by guruz** [comment]
@jturcotte I think he means to put the share dialog on top of the settings dialog?

**Comment by pierrejochem** [comment]
Correct

**Comment by jturcotte** [comment]
Ah yes, it annoyed me quite a lot, and unfortunately the best I could was to let the task bar icon flash.

See http://stackoverflow.com/questions/6087887/bring-window-to-front-raise-show-activatewindow-don-t-work

The only alternative I could see would be to spawn the share dialog in a separate process than the ownCloud client.

**Comment by guruz** [comment]
Why not hide the settings dialog when the share window is invoked?

**Comment by jturcotte** [comment]
Personally I'm not in favour of hiding the settings window.

1. It's an intended (even though annoying) Windows behaviour that users already cope with
2. If we really want to care about details enough to fix this bug, we should make sure that it's a real step forward and closing the settings windows while the user didn't ask for this might be too big of a compromise.

Let me know how you see it.

**Comment by pierrejochem** [comment]
Today I tried it with OS X Yosemite and there is the same situation :-( It should be oben independed from the settings widget in my opinion

**Comment by guruz** [comment]
@jancborchardt Needs your decision.

**Comment by jancborchardt** [comment]
I agree with @jturcotte here. If we fix it, we should fix it correctly. Just hiding the settings window is strange and unexpected. Making sure the share dialog is always on top of the settings window (when that is open) is the correct fix.

**Comment by jturcotte** [comment]
There might be a way to fix the OS X behavior with some additional Cocoa magic, but for windows at least, the only way I see of having this properly fixed is to either:

- Implement the share dialog directly in the OCContextMenu (and require duplicating the implementation of other platforms in ugly Win32 code)
- Instantiate a separate ownCloud.exe process to show that dialog, which would itself then communicate with the main process through the SocketAPI to do the required server magic.

**Comment by dragotin** [comment]
Would it be an option to embed the sharing dialog into the settings dialog (as a new tab) in case the settings dialog is open? And if not, we display it as its now?

**Comment by danimo** [comment]
@dragotin The though of this happening scares me already from a usability. Why not simply reparent the dialogs. The would implictly enforce the stacking order (but also means that the sharing dialog would be modal for the settings dialog, which is probably not too bad)

**Comment by pierrejochem** [comment]
@dragotin @danimo I like both ideas :wink:

**Comment by guruz** [comment]
Should be fixed for OS X, not yet for Windows.

**Comment by phil-davis** [comment]
Just documenting the behaviour on Windows (10) as of Version 2.0.2-nightly20150929 (build 5500)

When the settings dialog is closed, use "Share with ownCloud" from the file explorer. The sharing dialog opens correctly in front of the file explorer window - good.

When the settings dialog is open, use "Share with ownCloud" from the file explorer. 
a) The sharing dialog opens behind the file explorer window and on top of the settings dialog. This makes it non-obvious for users to find.
b) The sharing dialog causes the settings dialog to be closed.

**Comment by guruz** [comment]
@Dianafg76 @pierrejochem Is this fixed on Windows?

**Comment by pierrejochem** [comment]
This is fixed with 2.1.0, but thre is still a small cosmetic issue. 

If you open the settings form and then open an windows file explorer which is in foreground so the settings windows is not visible. Then switch to the owncloud folder in the windows file explorer and click on share via cloud via context menu. 

The share form is not in top most state. You just see a blinking hint in the task tray. In my opinion it should be set to top most.

**Comment by danimo** [comment]
@pierrejochem That's not possible with the current architecture. the window would need to be a child dialog of Explorer, or its own app. Microsoft changed that behavior in the Window Manager when undesired pop-ups in IE became a problem.

**Comment by Dianafg76** [comment]
I tested this issue and is working OK
Desktop client ownCloud-2.1.1.5765-nightly20160112-setup.exe 
Server v 8.2.2
Windows 10
Closed

**Comment by pierrejochem** [comment]
@danimo: thanks and I understand. Just a cosmetic issue what I said :-)
