### ISSUE TITLE
[Qt4] "unknown errors" when changing bandwidth limit

### ISSUE THREAD

**Issue by cortopy** [owncloud/client#3016]
### Expected behaviour
When changing bandwidth limit in settings I would expect bandwith to be indeed limited. I'm not sure what "limit automatically" means, but changing bandwith to something fixed doesn't work either

### Actual behaviour
Sync doesn't work at all. At the moment I'm uploading a large number of files and about 99% of files give "unknown error" and sync never happen

### Steps to reproduce
1. Change limit bandwidth settings to either automatic or a set amount

### Server configuration
Operating system: Ubuntu 14.10

Web server: nginx

Database: mySQL

PHP version: 5..5.12

ownCloud version: 8.0.2

Storage backend: ?

### Client configuration
Client version: 1.8

Operating system: Ubuntu 14.10

OS language: English

Installation path of client: as per app-get

**Comment by guruz** [comment]
Can you run your client with parameter ```--logfile -``` and paste here some context on what causes the first errors?

**Comment by ogoffart** [comment]
What is your Qt version?

**Comment by cortopy** [comment]
Logs are very big and I'm not sure which bit is helpful. 

As examples:

```
03-25 13:43:43:523 0x1d74590 (+) Watcher: "/home/user/Pictures/Icons/material/maps" 
03-25 13:43:43:539 0x1d74590     `-> discarded: "/home/user/Pictures/Icons/material/maps/1x_ios" 
03-25 13:43:43:539 0x1d74590     `-> discarded: "/home/user/Pictures/Icons/material/maps/1x_web" 
```
It's like that for all files skipped and giving "unknown errors" in the client UI

```
Then, in the log there is also:
03-25 13:43:43:703 0x1d74590 Processing result list and logging took  1268  Milliseconds. 
03-25 13:43:43:703 0x1d74590 OO folder slotSyncFinished: result:  9 
03-25 13:43:43:741 0x1d74590   ** error Strings:  ("Graphic Design/Textures, Shadows and Backgrounds/webtreats-seamles-paper-patterns.zip: Unknown error.", "Icons/Font-Awesome/black/png/128/arrow-circle-o-up.png: Unknown error.", "Icons/Font-Awesome/black/png/128/arrow-circle-right.png: Unknown error.", "Icons/Font-Awesome/black/png/128/arrow-circle-up.png: Unknown error.",
```

**Comment by cortopy** [comment]
Qt version is 4.8.6

**Comment by guruz** [comment]
If you use >= Qt 5.4 then the new bandwidth code will be used. Could you try that?

Related https://github.com/owncloud/client/issues/2558

**Comment by cortopy** [comment]
How could I try that? I'm using 

```deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.10/```

and there isn't an updated version for the client.

**Comment by cortopy** [comment]
Should I report this in the related issue too?

**Comment by guruz** [comment]
@jnweiger Is there qt5-based packages already?

> How could I try that?
In worst case you need to compile it yourself :-)

**Comment by cortopy** [comment]
That's a shame. I thought that by using package manager I wouldn't miss on updates. Does this mean the client doesn't get updated regularly for Linux packages? If this is the case, then I'd switch to compiling, but I want to be sure first

**Comment by guruz** [comment]
@cortopy The problem is that right now we maintain Qt4 and Qt5 compiles.
In this particular case there are bugfixes inside Qt5 itself and we switch to a new codepath based on the Qt version..
https://github.com/owncloud/client/blob/fba9020950271f8ea5e594fa412f645fb0575636/src/libsync/owncloudpropagator.cpp#L372

FYI @dragotin @jnweiger
