### ISSUE TITLE
Debian based distros: Change location of configfile & translations

### ISSUE THREAD

**Issue by hefee** [owncloud/client#3017]
The debian owncloud team we discussed, that we want to make sure that configfiles and translations are in own directories to not mix up with the server. It would be great if same is done for the debian/ubuntu packages in OBS, to make it easier to switch between OBS  <-> distro. Or should I post them as pull requests?

Translation path: /usr/share/owncloud/i18n -> /usr/share/owncloud-client/i18n
config path: /etc/ownCloud -> /etc/owncloud-client

you find the patches available at the [debian git](http://anonscm.debian.org/cgit/pkg-owncloud/owncloud-client.git), [0007-move-translations.patch](http://anonscm.debian.org/cgit/pkg-owncloud/owncloud-client.git/tree/debian/patches/0007-move-translations.patch), [0006-move-configfile.patch](http://anonscm.debian.org/cgit/pkg-owncloud/owncloud-client.git/tree/debian/patches/0006-move-configfile.patch)
To move the old config see [owncloud-client.maintscript](http://anonscm.debian.org/cgit/pkg-owncloud/owncloud-client.git/tree/debian/owncloud-client.maintscript)

**Comment by DeepDiver1975** [comment]
starting with owncloud client 6 there are no linux packages provided via OBS :shrug:
