### ISSUE TITLE
How to implement hash sum to prefent duplicate download/upload

### ISSUE THREAD

**Issue by guettli** [owncloud/client#3018]
AFAIK the client does not use hash sums to check before download/upload.

This produces unneccessary network traffic. 

This has been reported before:

https://github.com/owncloud/client/issues/779#issuecomment-24270145

My question: 

How to get this done?

Does the server API provide a way to get hash sums of files?

Does the webDAV API use unique ETags which could be used?

**Comment by etiess** [comment]
@guettli I think it is discussed on core for now: https://github.com/owncloud/core/issues/11811

It is an old discussion in OC development: if you have ideas or suggestion, I would do it there ;)

**Comment by guettli** [comment]
The propsal at the end of owncloud/core#11811 is about  integrity. I want hashes to prevent useless up/downloads. These hashes should be used for ETags, too.

That's why I leave this ticket open.
 

@etiess  Nevertheless, thank you very much for the link to the core ticket.

**Comment by RealRancor** [comment]
Just a short quote from https://owncloud.org/faq/#syncspeed
> The downside of this is that it is hard use 'checksums' to see if files are changed: imagine doing that on terabytes of data on an external storage! What is fast for a few gigabyte or a few thousand files is would break entirely once you add a large movie- or music database, or start pumping scientific data through the system.

**Comment by guettli** [comment]
Yes, scalability is important. But for me the FAQ item is FUD.

PostgreSQL can handle tables with millions of rows very well. BTree indexes scale very well :-)

I am unsure if php is turing complete and could make it possible to make something like this optional.
Leaving it up to the admin if hashes should be used or not.

**Comment by guettli** [comment]
Is this issue solved now, or is it a duplicate of another still open issue?
