### ISSUE TITLE
Huge log files

### ISSUE THREAD

**Issue by bgeneto** [owncloud/client#3019]
I have enabled client log (using --logdir option with --logexpire 4) while trying to figure out why all my owncloud clients (v1.8.0 build 4847 Win7 x64, Server 8.0.2 Centos 7) always consume a great amount of my CPU resources and why the discovering process takes so long. 

To my surprise owncloud log files created in just a couple of hours account for more than 5GB! I'm lost while trying to debug such a huge log in order to find out what is happening to the client sync process! The discoverying stage takes several (dozens) minutes to complete. At the end only one or another file is downloaded or uploaded, that's the expected behavior, because only a few files have changed, but in this case why the client have to discover every file (>100k) in every folder (>9k) each time the client program starts and several times after? There are thousands of "_csync_detect_update",  "csync_ftw" and "csync_walker". Also thousands of "_csync_merge_algorithm_visitor: INSTRUCTION_NONE" for non changed (never touched files and folder). 

Could someone help me or guide me troubleshooting my log file (first lines in the link below) in order to find the root of my problem? What kind of message do I have to be concerned? Thanks.

https://drive.google.com/file/d/0ByZNd1p082pURnBJaDJIdGt5elk/view?usp=sharing

**Comment by guruz** [comment]
Related https://github.com/owncloud/client/issues/2497

**Comment by bgeneto** [comment]
Sorry but I don't think both issues are related. The actual log files produced are in fact huge, every "owncloud.log.xx" file has a size of 104MB and in a couple of hours dozens of files of that size are created in the "logdir" folder so they all account for more than 5 gigabytes of data. 

I don't even know if there is a sync problem with my clients because I'm lost debugging several huge log files. I think a "--verbose" option could be added to the client so every operation (csync_walker, _csync_detect_update, etc...) is logged while this option is present and without verbose logging only warnings and/or errors are logged. This should help debugging the client sync process a lot.  

ps.: the shared link to my log file is only the beginning (first lines) of the first log file, not the entire file.

**Comment by ogoffart** [comment]
Yes, the log files are huge because they contains lots of information.
It is now possible to remove some of the information with the
`QT_LOGGING_RULES` env variable.
