### ISSUE TITLE
owncloudcmd --trust doesn't ask for password

### ISSUE THREAD

**Issue by felicitus** [owncloud/client#3021]
When forcing owncloudcmd to trust the certificate, it never asks for username and password.

How to reproduce:

`owncloudcmd --trust <localurl> <remoteurl>`

Here are the relevant log lines:

```
03-25 15:51:46:159 oc_module: Call the csync callback for ownCloud
** Authentication required: 
Enter your username: 
** Authentication required: 
Enter your password: 
03-25 15:51:46:365 oc_module: Authentication required yes
```

The CLI doesn't stop when asking for username+password, but skips them. When not using --trust, it waits for the username and passwords.

**Comment by ogoffart** [comment]
What version of owncloudcmd were you using?

**Comment by ogoffart** [comment]
This should be fixed with 1.8

**Comment by guruz** [comment]
@felicitus Can you confirm this is fixed with rc2?
https://owncloud.org/install/#testing

**Comment by felicitus** [comment]
This works for me with the updated binaries.
