### ISSUE TITLE
Error when packaging for Windows

### ISSUE THREAD

**Issue by plages** [owncloud/client#3022]
When i call make package (after a succesfull make command) i get the following errors:

in the shell:
CPack Error: Problem running NSIS command: "/usr/bin/makensis" "/home/plages/mirall-build/_CPack_Packages/unused/NSIS/project.nsi"
Please check /home/plages/mirall-build/_CPack_Packages/unused/NSIS/NSISOutput.log for errors
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: kloud
make: *** [package] Error 1

in NSISOutput.log:
Invalid command: ${UAC.CallFunctionAsUser}
Error in script "/home/plages/mirall-build/_CPack_Packages/unused/NSIS/project.nsi" on line 247 -- aborting creation process

project.nsi is:
246   Function LaunchApplication
247      ${UAC.CallFunctionAsUser} LaunchApplicationAsUser
248   FunctionEnd

Any ideas as to how to fix this?

**Comment by danimo** [comment]
Don't build from master. Use 1.8.

**Comment by plages** [comment]
i did build from 1.8

**Comment by plages** [comment]
I used:
git clone -b 1.8 https://github.com/owncloud/client.git client
to clone the 1.8 branch then i modified some files in order to get my own theme.
Still i get the afore mentioned error. Could there be some dependency missing?
Help!

**Comment by pierrejochem** [comment]
Wrong UAC NSI Plugin

**Comment by pierrejochem** [comment]
sudo rpm --nosignature -i http://download.tomahawk-player.org/packman/mingw:32/openSUSE_12.1/x86_64/mingw32-cross-nsis-plugin-processes-0-1.1.x86_64.rpm

sudo rpm --nosignature -i http://download.tomahawk-player.org/packman/mingw:32/openSUSE_12.1/x86_64/mingw32-cross-nsis-plugin-uac-0-3.1.x86_64.rpm

**Comment by plages** [comment]
Thanks finally it worked.
