### ISSUE TITLE
File Manager Integration: Add more context-menu options

### ISSUE THREAD

**Issue by vascojdb** [owncloud/client#3024]
# What?

As a feature, it would be great to add several context menu options to provide a more efficient way of working with files
# How?

Adding a context menu, something like:

![owncloud_context](https://cloud.githubusercontent.com/assets/7009829/6837453/98107784-d34c-11e4-8422-fc8f44593aea.png)

With the following options (at least):

- [ ] **Open on browser**: Open the file in the browser
- [x] **Copy link**: Just copy the link to where the file is stored
- [x] **Share public link**: The same windows that already appears in v1.8.0 share menu
- [ ] **Show file version log**: THIS IS THE MOST IMPORTANT for this idea. It would be great to show a window similar to Tortoise SVN file history, where the user could just double click to open a specific version, or just revert the actual file to a point in the past.

![owncloud_log](https://cloud.githubusercontent.com/assets/7009829/6837535/968d325c-d34d-11e4-8829-dbaf472d42e2.png)

**View deleted files and folders here**: Would open a window showing files and folders that were deleted, with option to restore them.

# Why?

Sometimes using a web browser may not be very convenient, so it would be great to have such options on the context menu.

**Comment by pierrejochem** [comment]
What about share with internal users?

**Comment by michaelstingl** [comment]
Open link in browser: https://github.com/owncloud/client/issues/5903

**Comment by ogoffart** [comment]
There is more context menu options.

You can open in the browser, and access the versions from there.
