### ISSUE TITLE
Android Client : Uploads from device duplicated on Device

### ISSUE THREAD

**Issue by delbydev** [owncloud/client#3025]
Hello

So using the Android ownCloud client to upload photos to the server - absolute godsend but have decided to create an SSH Server on the android device and scp -

However - using the SSH session on Android device I noticed some overhangs of ownCloud that could be better - for storage efficiency on the client device 

The original files in DCIM were still there (expected)
But a duplicate copy of the uploaded file was stored in the owncloud "virtual area" (/owncloud/username@owncloudHostHASH/PhotoArea1/PhotoArea2.

Is this normal?  If I go ahead remove the files from the owncloud area on the device (to free up space) will this remove process sync on the server? (Believe not)

Apart from using SSH session on the phone to bulk remove- is there an automated routine in the ownCloud client to purge these surplus copies from the device after they have been uploaded ?

Or plans to?

Or do we need to create internal housekeeping mechanisms to purge these files?

Thanks

**Comment by danimo** [comment]
Sorry, this is the desktop client repository. Please reopen in https://github.com/owncloud/android/issues/
