### ISSUE TITLE
[SSL] Possible bugs in SSL client certificate code

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3027]
https://github.com/owncloud/client/blob/9d7cf6b8529769796aafc5992c91ef36a7d14d84/src/libsync/account.cpp#L367

This is a function with a return value
http://doc.qt.io/qt-5/qsslconfiguration.html#defaultConfiguration

----

Another one:
https://github.com/owncloud/client/blob/9d7cf6b8529769796aafc5992c91ef36a7d14d84/src/libsync/account.cpp#L299
The other functions have a call to ```request.setSslConfiguration```

----
All the code in https://github.com/owncloud/client/blob/9d7cf6b8529769796aafc5992c91ef36a7d14d84/src/libsync/account.cpp#L340 is possibly costly and should indeed be moved.

@ogoffart Do you think the credentials are a better place?

**Comment by guruz** [comment]
Refs https://github.com/owncloud/client/issues/69 https://github.com/owncloud/client/issues/2810

CC @danimo @qknight @dragotin @ogoffart

**Comment by ckamm** [comment]
I agree about these, in particular about not making a new QSslConfig for each request. I'll not work on it yet because I don't have a ssl-client-cert test server set up.

**Comment by qknight** [comment]
On 08.04.2015 12:03, ckamm wrote:
> I agree about these, in particular about not making a new QSslConfig for
> each request. I'll not work on it yet because I don't have a
> ssl-client-cert test server set up.

if you wish you can use mine. i've created a virtual machine using vbox

**Comment by ckamm** [comment]
@qknight That would be very helpful, thank you!

**Comment by ckamm** [comment]
@qknight Could I use your virtual machine? Maybe email me at kamm at incasoftware.de?

**Comment by guruz** [comment]
@qknight Hey :) I think I fixed the code in 1.9(!) branch but I haven't tested if it will break the client cert code.
