### ISSUE TITLE
[OSX] install/symlink owncloudcmd to /usr/bin or /usr/local/bin

### ISSUE THREAD

**Issue by stonerl** [owncloud/client#3028]
I think the title is self-explanatory. Would this be reasonable in your opinion? So the command-line-tool would be available outside the application folder.

**Comment by guruz** [comment]
I don't think we want to do that, you can add it into your ```PATH``` via ```.profile``` or similar.

**Comment by stonerl** [comment]
Shall I close this issue?

**Comment by stonerl** [comment]
I'm going to close this one.
