### ISSUE TITLE
Found owncloud.exe process(s) which need to be stopped .

### ISSUE THREAD

**Issue by waheni** [owncloud/client#3029]

**Comment by waheni** [comment]
Good day
I compiled owncloud 1.8.0  , it build it succefully but , when i try to open the exe file i got this message 
Can any one help me ?

**Comment by jturcotte** [comment]
@waheni Please refer to https://doc.owncloud.org/desktop/1.8/building.html

If you still have issues building it, please visit us at #owncloud-client-dev on freenode.
I'll close this issue assuming that it's related to your build environment, we can reopen it if you're hitting a real bug.
