### ISSUE TITLE
Add button to restart client after Crash

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/client#3030]
My client on OS X just crashed and the new fancy error reporter came up. It would be nice for the average user if after the report has been sent the client would get restarted or a button to restart it is available.

**Comment by guruz** [comment]
FYI @dschmidt

**Comment by dschmidt** [comment]
I'm not completely sure how to reasonably implement that, we probably need to to pass the path / the command to open the client to the reporter? Possibly even keeping command line args. I can imagine how to implement that for Linux and Windows, but I'm really clueless about app bundles and stuff on OSX.
How do you get the currently opened app bundle path?
