### ISSUE TITLE
linux desktop client not registering disk usage

### ISSUE THREAD

**Issue by Heetered** [owncloud/client#3032]
Using Ubuntu14.10 64bit latest client from the appstore
Server is Ubuntu14.04 64bit with Owncloud 8.0.2

Upgraded Owncloud to 8.0.2 from 7.0.4 using the occ manual method and now the client quit showing the right amount of storage usage. It does show the correct disk size, but not the amount of storage being used. Both the /data folder and the desktop sync'ed /owncloud folder has approx. 59gigs of data, but the status bar on the client only shows 7gigs. 

It used to work with previous versions of the server before 8.0.2.

Regards,

**Comment by guruz** [comment]
What does ```/index.php/settings/personal``` say?

**Comment by Heetered** [comment]
Hi

It says "You have used 7.2 GB of the available 805.1 GB", just like the desktop client

Regards

**Comment by tflidd** [comment]
Do you use the encryption app? I had some problems with it: https://github.com/owncloud/core/issues/14298

**Comment by Heetered** [comment]
Yes I did.

I looked over those github posts that you posted, sounds exactly like my situation.

I am the only user of the owncloud system. 

How about if I unecrypt and reencrypt the files?

regards,

**Comment by danimo** [comment]
Please follow the issue in core.
