### ISSUE TITLE
1.8.0 uploads synced (unchanged) file(s) again and doubles them

### ISSUE THREAD

**Issue by darf-L** [owncloud/client#3033]
Hey guys, 
(my first post here) <= don't know if i'm right here

hope you can help me with some problems about my owncloud client...

first of all my settings...

> running ownCloud 8.0.2 (stable)
    > on openmediavault 1.16 (Kralizec)
    > on a raspberry pi 2
    > owncloud has its working folder on usb ( /dev/sda2 ) fs = EXT4
> shared folders are imported over the "external storage" app and are placed on an usb hdd. fs = NTFS

> running owncloud desktop client 1.8.0 (build 4893)
    > on windows 7 x64
    > on womans notebook ;)
    > filesystem of local syncfolders: ntfs

so far everything seems to be fine

now i've seen that the client syncs existing (imho) unchanged files every morning i start up the notebook.
not enough in doubles the files (local and in cloud) for my suprise with EXACTLY the same filename (didn't know that this is possible (in windows))

now i have to change anything because i'm running out of space in some weeks ;)

here my logfile (hope its the right one, if not tell me where to find)

# timestamp | duration | file | instruction | dir | modtime | etag | size | fileId | status | errorString | http result code | other size | other modtime | other etag | other fileId | other instruction
#=#=#=# Syncrun started 2015-03-27T19:09:03 until 2015-03-27T19:37:39 (1715205 msec)
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3|INST_NEW|Up|1419942782||297032724||2|Error downloading https://192.168.2.10:8443/remote.php/webdav/Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3-chunking-149327803-57-56 - server replied: Gateway Time-out|0|0|0|||INST_NONE|
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Hörbuch.mp3|INST_NEW|Down|1419942782|be456b92df9474a42e69cde29ca20557|297032724||2|Error downloading https://192.168.2.10:8443/remote.php/webdav/Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Hörbuch.mp3 - server replied: Not Found|0|0|0|||INST_NONE|
18:25:09|6255|ownCloudUserManual.pdf|INST_NEW|Down|1427266494|cf1ccce9109449548c46fc260ad28b24|1747761||4||0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-03-27T19:38:39 until 2015-03-27T19:54:41 (961661 msec)
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3|INST_NEW|Up|1419942782||297032724||6|Continue blacklisting: Error downloading https://192.168.2.10:8443/remote.php/webdav/Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3-chunking-149327803-57-55 - server replied: Gateway Time-out|0|0|0|||INST_NONE|
18:38:05|364599|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Hörbuch.mp3|INST_NEW|Down|1419942782|6769c3e2c0599c8ae9ff24f596b217d6|297032724||4||0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-03-27T19:55:30 until 2015-03-27T19:55:36 (5638 msec)
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3|INST_NEW|Up|1419942782||297032724||6|Das Element ist aufgrund vorheriger Fehler nicht synchronisiert: Error downloading https://192.168.2.10:8443/remote.php/webdav/Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3-chunking-149327803-57-55 - server replied: Gateway Time-out|0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-03-27T19:58:29 until 2015-03-27T20:00:10 (100982 msec)
|0|Eigene Musik|INST_SYNC|Down|1419942782|5515a81f3ab52|0||0||0|8192|1426865487|5515a3593a692||INST_NONE|
|0|Eigene Musik/Fynn-Luca|INST_SYNC|Down|1419942782|5515a81f3dad1|0||0||0|16384|1427481895|5515a3593d0f2||INST_NONE|
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3|INST_NEW|Up|1419942782||297032724||3|Operation abgebrochen|0|0|0|||INST_NONE|
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Hörbuch.mp3|INST_SYNC|Down|1419942782|e69fdbb91d71900f84346a1278059f34|297032724||3|Operation abgebrochen|0|297032724|1419942782|6769c3e2c0599c8ae9ff24f596b217d6||INST_NONE|
#=#=#=# Syncrun started 2015-03-27T20:00:26 until 2015-03-27T20:13:54 (807849 msec)
|0|Eigene Musik|INST_SYNC|Down|1419942782|5515a81f3ab52|0||0||0|8192|1426865487|5515a3593a692||INST_NONE|
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3|INST_NEW|Up|1419942782||297032724||6|Continue blacklisting: Error downloading https://192.168.2.10:8443/remote.php/webdav/Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3-chunking-149327803-57-54 - server replied: Gateway Time-out|0|0|0|||INST_NONE|
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Hörbuch.mp3|INST_SYNC|Down|1419942782|e69fdbb91d71900f84346a1278059f34|297032724||2|Error downloading https://192.168.2.10:8443/remote.php/webdav/Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Hörbuch.mp3 - server replied: Gateway Time-out|0|297032724|1419942782|6769c3e2c0599c8ae9ff24f596b217d6||INST_NONE|
#=#=#=# Syncrun started 2015-03-27T20:14:54 until 2015-03-27T20:17:27 (153865 msec)
|0|Eigene Musik|INST_SYNC|Down|1419942782|5515a81f3ab52|0||0||0|8192|1426865487|5515a3593a692||INST_NONE|
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3|INST_NEW|Up|1419942782||297032724||6|Das Element ist aufgrund vorheriger Fehler nicht synchronisiert: Error downloading https://192.168.2.10:8443/remote.php/webdav/Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3-chunking-149327803-57-54 - server replied: Gateway Time-out|0|0|0|||INST_NONE|
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Hörbuch.mp3|INST_SYNC|Down|1419942782|e69fdbb91d71900f84346a1278059f34|297032724||6|Continue blacklisting: Error downloading https://192.168.2.10:8443/remote.php/webdav/Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Hörbuch.mp3 - server replied: Gateway Time-out|0|297032724|1419942782|6769c3e2c0599c8ae9ff24f596b217d6||INST_NONE|
#=#=#=# Syncrun started 2015-03-27T21:00:42 until 2015-03-27T21:12:45 (722618 msec)
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3|INST_NEW|Up|1419942782||297032724||6|Continue blacklisting: Error downloading https://192.168.2.10:8443/remote.php/webdav/Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3-chunking-149327803-57-53 - server replied: Gateway Time-out|0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-03-27T21:13:27 until 2015-03-27T21:13:38 (10545 msec)
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3|INST_NEW|Up|1419942782||297032724||6|Das Element ist aufgrund vorheriger Fehler nicht synchronisiert: Error downloading https://192.168.2.10:8443/remote.php/webdav/Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3-chunking-149327803-57-53 - server replied: Gateway Time-out|0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-03-28T09:01:36 until 2015-03-28T09:14:03 (747131 msec)
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3|INST_NEW|Up|1419942782||297032724||6|Continue blacklisting: Error downloading https://192.168.2.10:8443/remote.php/webdav/Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3-chunking-149327803-57-52 - server replied: Gateway Time-out|0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-03-28T09:14:48 until 2015-03-28T09:15:00 (12178 msec)
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3|INST_NEW|Up|1419942782||297032724||6|Das Element ist aufgrund vorheriger Fehler nicht synchronisiert: Error downloading https://192.168.2.10:8443/remote.php/webdav/Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3-chunking-149327803-57-52 - server replied: Gateway Time-out|0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-03-28T09:17:52 until 2015-03-28T09:26:36 (523927 msec)
|0|Eigene Musik|INST_SYNC|Down|1419942782|5516635f65744|0||0||0|8192|1426865487|5515b994e2711||INST_NONE|
|0|Eigene Musik/Fynn-Luca|INST_SYNC|Down|1419942782|5516635f68bd4|0||0||0|16384|1427486447|5515b994e5472||INST_NONE|
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3|INST_NEW|Up|1419942782||297032724||6|Das Element ist aufgrund vorheriger Fehler nicht synchronisiert: Error downloading https://192.168.2.10:8443/remote.php/webdav/Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3-chunking-149327803-57-52 - server replied: Gateway Time-out|0|0|0|||INST_NONE|
08:17:18|507379|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Hörbuch.mp3|INST_SYNC|Down|1419942782|706eff772b4269744f29a9ebe0d5c5b8|297032724||4||0|297032724|1419942782|6769c3e2c0599c8ae9ff24f596b217d6||INST_NONE|
#=#=#=# Syncrun started 2015-03-28T09:27:12 until 2015-03-28T09:27:18 (5580 msec)
|0|Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3|INST_NEW|Up|1419942782||297032724||6|Das Element ist aufgrund vorheriger Fehler nicht synchronisiert: Error downloading https://192.168.2.10:8443/remote.php/webdav/Eigene Musik/Fynn-Luca/Der _NORDPOL EXPRESS_ Ho?rbuch.mp3-chunking-149327803-57-52 - server replied: Gateway Time-out|0|0|0|||INST_NONE|

please help me

**Comment by nekoal** [comment]
It's bug in unicode using. Same character may be coded in different ways. Original file has character coded as base latin o character and combining character dieresis (shows as question mark in log). it looks for me as this two characters were sent to server and created record with 2 characters but in responce characters was converted to single o dieresis character (normalization form C). Possible reason: UTF-8 standart instruct using the shortest form of character.
Simplest way to fix it: force client rename files to shortest character form before uploading. Usually conversion national characters to Unicode uses shortest form too.

**Comment by darf-L** [comment]
hi,
you think because of the "ö" in the filename? 
and how to force the client doing this?

**Comment by nekoal** [comment]
hi, yes, I think so. Forcing rename it's suggest for developers team.
You can pause client and try rename file manually by deleting this character and retype it form keyboard (if keyboard layout have this character). If you set cursor after "ö" and press Backspace key you'll see different behavior, see 1) or 2). Better find file with 1) behavior.
1) For filename with shortest form it delete character "ö". Cancel renaming. If this file is not corrupted try delete other file and go 3). If file is corrupted then delete file and go 2).
2) For filename with combining form character "ö" turns character "o". Delete o and retype "ö" from keyboard.
3) Unpause client.

**Comment by darf-L** [comment]
hi,
i paused my client and like nekoal wrote, renamed both files (oe instead of ö) and deleted doubles.
now everything works fine.

while deleting charakter "ö" it changed to "o" like nekoal predicted...

ironically this happens to two of my 15k files.... and in owncloud i'm using utf8 DE i think
hmmm

**Comment by guruz** [comment]
I'm closing this issue here as you worked around it.
If this problem persists with a newer server version, please open a bug in https://github.com/owncloud/core (and link this issue to it too)
