### ISSUE TITLE
1.8 Windows client started to remove random files

### ISSUE THREAD

**Issue by bremenpl** [owncloud/client#3034]
Hello there,
Its hard for me to describe what happened exactly, but im sure this never happened before on client 1.7. Couple hours a go I have updated to 1.8 client. Just now I have noticed in the activity log that lots of my files were deleted! I then had to go to the website quickly and restore the deleted files, there were a lot of them (about 500). I gues there would be more if i wouldnt noticed it.
Has anyone else expirienced simmilar behaviour? Atm I have restarted my client and its on "discovering" part, I hope he will start downloading removed from the harddrive files.

**Comment by bremenpl** [comment]
When I recovered removed files, they were recovered to the main folder instead of the folders they resided in... This is a nightmare.

**Comment by MegaV0lt** [comment]
You should file a issue for the wrong recovered files too!

**Comment by rogerz00** [comment]
I had a possibly related experience yesterday. I installed the Mac OS X 1.8 client on 23 March. Everything worked well at first. Then on 29 March I noticed some activities on the client and upon checking the ownCloud directory had reduced from 4.3 GB to 674 MB. Most of the files were gone on the client. Interestingly everything was still there on the server. I checked to make sure I hadn't accidentally deleted the files, but I am very certain I didn't. I was able to recover the files from the server. For now I have uninstalled 1.8 and reinstalled 1.7.1. I am also using 1.8 on Windows and on Linux and things are fine there so far. Basically I have no idea what happened ...

**Comment by guruz** [comment]
This sounds bad.

Was there anything special about the files? Special characters? Remote storage on the server?
You only updated the client not the server?
Were all files in a single directory deleted or only some files in that directory?

**Comment by bremenpl** [comment]
In my situation the files were really random- pdfs, images, whole folder structures, documents... I have restored my data folder and mysql database because it was to messy with all the files outside their folders. At the moment I am downloading everything again using 1.8 client on my pc. Ill let know if anything weird happens again.

**Comment by bremenpl** [comment]
Okay half of my files were deleted again. The client simply started to remove files. Please tell me how can I generate some kind of log and send it over.

**Comment by guruz** [comment]
Check https://github.com/owncloud/client/blob/master/doc/troubleshooting.rst 
"Saving files directly".

**Comment by rogerz00** [comment]
In my case many files and directories disappeared. Once I noticed that some files were gone I turned off WiFi. The server seemed to be completely unaffected (all files are there). I previously had updated the server to 8.0.2, 16.1. I have an .owncloudsync.log and some .csync_journal.db* files if these are useful.

**Comment by dragotin** [comment]
The .owncloudsync.log is useful because we can see in it why the client thought it should delete the local files.

**Comment by bremenpl** [comment]
I have restored the owncloud system again and downloaded client in version 1.7. And I can tell you one thing for certain:
I have 22 GB of data in total uploaded to owncloud. After the discovering phase, in version 1.7 i see in downloading dialog (next to the progress bar) ie. 900 MB of 22 GB, which is legit. In the version 1.8 I have seen XX MB of 7.9GB for example. So its like- he thought he should download only 7.9 GB and remove the rest, or something?

**Comment by dragotin** [comment]
@bremenpl well, lets not speculate. Pls. try again with 1.8.0 with logfile generation. Also check your server logfiles (owncloud.log and apache error log). Do you use a proxy?

**Comment by bremenpl** [comment]
8.8.8.8 and 4.4.4.4 as alternative i think.

**Comment by rogerz00** [comment]
Okay, sure. How do I best get the files to you? Should I file a bug report?

**Comment by guruz** [comment]
Please mail the log or a link to the log to guruz@owncloud.com and olivier@owncloud.com .. Thanks

**Comment by guruz** [comment]
So the clent removed the files from the client and server, but you found them in the server trash bin?

**Comment by bremenpl** [comment]
For me they got removed on both sides. The files got moved to removed 
files. The problem is when i tried to restore the files, they got restored 
to the root folder instead of where they resided before.

**Comment by bremenpl** [comment]
I am trying to catch this behaviour again for 2 days now but it doesnt 
appear...

**Comment by dragotin** [comment]
If the files are in the deleted files section on the server, it is worth checking if you can find any DELETE commands in your servers access_log that came from a client. Check for a User Agent string like *Mozilla/5.0 (Linux) mirall/1.8.0*

If you can not find entries in access_log for the given time, it means the files were deleted from the server other than by the client. Do you have an external storage? Are these files in a shared directory?

**Comment by guruz** [comment]
Please re-open if this comes up again when using 1.8.1rc1

**Comment by taspac** [comment]
Hello,
I can confirm the same behavior with OC Client 1.8.1 (build 5050) on Win 7 Pro x64.
On Monday we've lost ~500 files as one of clients computer deleted some shared stuff on server, during normal sync operation. After that other clients "synced" as well..
In 1.7.1 version it was ok, then update came on 14.05.2015 with 1.8.1 and on 17.05.2015 we've got this accident.
No logs on server showed nothing - just Action tab on user account and client log with stuff like this: 

*06:17:18|3747|folder/file_1|INST_REMOVE|Up|1397046443|54412bec95ec3|0|00000576oc82828ff9e7|4||0|0|0|||INST_NONE|
06:17:18|3669|folder/file_2|INST_REMOVE|Up|1397823145|54412bece503d|0|00000586oc82828ff9e7|4||0|0|0|||INST_NONE|
06:17:18|3750|folder/file_3|INST_REMOVE|Up|1397826646|54412bed41713|0|00000575oc82828ff9e7|4||0|0|0|||INST_NONE|
06:17:21|2826|folder/file_4|INST_REMOVE|Up|1397729934|54412bed92161|0|00000582oc82828ff9e7|4||0|0|0|||INST_NONE|
..*

Few files were found in trashcan, others were removed completely..

Any ideas?

**Comment by taspac** [comment]
Please re-open this issue!
