### ISSUE TITLE
[Windows 1.8 #4850] Waiting for sync (after DST change?)

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#3036]
Today after the timechang from CET to CEST the occlient waits for syng:
![screen](http://i.imgur.com/pAipIhf.png)

I addes a testfile to local folder; and it does not sync it ;(

Can this because of the timechange? Can anyone confirm? PC was in hibernate over night

When i exit occlient the crashreporter started...
After restart of occlient it works like expected again...

**Comment by dragotin** [comment]
Since this is a bit unspecific and also mentions a crash, I doubt we will be able to fix that based on this bug report. Closing hence, sorry.
