### ISSUE TITLE
1.8 Client contex menu addon causes explorer crash

### ISSUE THREAD

**Issue by bremenpl** [owncloud/client#3037]
Hello there,
The new context menu addon from owncloud client 1.8, causes problems in Windows 7. When I right click on a file, explorer crashes. I had to remove the client (didnt want to remove the context menu addon from the registry) to be abble to right click on any file on my system.

**Comment by jturcotte** [comment]
Possibly the same as #2995

Could you try the latest nightly build from http://download.owncloud.com/desktop/daily/ ?

**Comment by jturcotte** [comment]
It it doesn't work please try giving us more info about the crash. It might be slightly different on Window 7 but you should be able to find a summary afterward by doing:
- Go in ControlPanel/AdministrativeTools/EventViewer
- Try to find an event related to the crash, possibly in "Windows Log/System"
- Right click on the event from the list, and do Copy/Copy Details as Text
- Paste it here as a comment
If you can't find the summary there, a screenshot of the error message would also be helpful.

**Comment by guruz** [comment]
Please re-open if it still happens with a nightly build
http://download.owncloud.com/desktop/daily/

(Make sure to restart your machine)

**Comment by kevinvalk** [comment]
I tested this with ownCloud-1.8.1.5007-nightly20150429-setup.exe.
For me it still hangs (eventually crashes), how to reproduce:
- I have quite some files to sync, so while it is scanning, nothing hangs
- However, as soon as ownCloud starts uploading files (1399 of 1456)
- I right click on a file or directory in explorer, then immediately ownCloud and that specific explorer window hangs.
- If you wait long enough you get an Assertion failed error (see attached)
![schermafdruk 2015-04-30 11 41 49](https://cloud.githubusercontent.com/assets/3524694/7411069/d2307a28-ef34-11e4-8701-967bbd6cea17.png)

**Comment by jturcotte** [comment]
I tried with build 5006 and even if I try to force info.shareMenuTitle to be empty, the assert doesn't trigger.

Could you check that the size of OCContextMenu_x64.dll is 85.5 KB (87,552 bytes) if you right click and chose "Properties" in explorer?

Also, how did you achieve to "disable the ownCloud explorer extension dll", did it involve restarting the computer at least once? If you install a new build of ownCloud, the old shell extension is likely to remain loaded by explorer until you restart.

About the hang during heavy uploads, it's a known issue that the main thread of the client won't be completely responsive during heavy syncs. Ideally we should move all the heavy lifting on a separate thread, but this is still work in progress. This should normally only affect the ownCloud share folder.

**Comment by guruz** [comment]
@kevinvalk Are you sure you rebooted after re-installing a newer version of the oC? Can you try 1.8.1rc2?
https://owncloud.org/install/#testing

**Comment by jturcotte** [comment]
@kevinvalk Also make sure that you keep the "Uninstall before installing" option when installing the new version. It's quite possible that the installer isn't able to properly install the new shell extension DLLs if it has to overwrite the file while they are in use by explorer. Uninstalling first might be working around that limitation somehow.

**Comment by Dianafg76** [comment]
I can not reproduce the issue. I tested in Desktop v1.8.2 (build 5077).
I close the issue
