### ISSUE TITLE
Client App crashes for unknown reason when left running on server

### ISSUE THREAD

**Issue by umuzidan** [owncloud/client#3038]
Application: x64 version 1.7.1.4382
OS: Serer 20012 R2 Standard
Roles: AD, DHCP, DNS, FS
OwnCloud Configuration: Files are being hosted in my web hosting account located in the cloud. Local files are placed onto a locally mapped iSCSI share.
Other Installed Applications: Dropbox, Veeam, Total Commander, PowerISO, CPUID, VMware Tools

Issue: When I log back into my server after several days, I am presented with an error that owncloud.exe has crashed. Upon inspection of my event logs, I find the following:

![image](https://cloud.githubusercontent.com/assets/11705408/6885256/56ab9abc-d5e5-11e4-9992-a9b78c18c086.png)

Faulting application name: owncloud.exe, version: 0.0.0.0, time stamp: 0x5492c052
Faulting module name: libstdc++-6.dll, version: 0.0.0.0, time stamp: 0x392a391b
Exception code: 0x40000015
Fault offset: 0x0001bfc8
Faulting process id: 0xff4
Faulting application start time: 0x01d06573188f16f4
Faulting application path: C:\Program Files (x86)\ownCloud\owncloud.exe
Faulting module path: C:\Program Files (x86)\ownCloud\libstdc++-6.dll
Report Id: 45a21900-d29c-11e4-80e6-000c29f9e284
Faulting package full name: 
Faulting package-relative application ID: 

I also found a Windows Error Reporting event too immediately after it. I'm not sure how much additional help this will be, but here is the contents:

Fault bucket 73743994839, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: owncloud.exe
P2: 0.0.0.0
P3: 5492c052
P4: libstdc++-6.dll
P5: 0.0.0.0
P6: 392a391b
P7: 40000015
P8: 0001bfc8
P9: 
P10: 

Attached files:
C:\Users\Administrator\AppData\Local\Temp\WER64C5.tmp.WERInternalMetadata.xml

These files may be available here:
C:\Users\Administrator\AppData\Local\Microsoft\Windows\WER\ReportArchive\AppCrash_owncloud.exe_395bcd2db87bdc5df0c2782bf8b6326a3ed9c46a_e2f91b87_1d6867f2

Analysis symbol: 
Rechecking for solution: 0
Report Id: 45a21900-d29c-11e4-80e6-000c29f9e284
Report Status: 0
Hashed bucket: ca21b7c146f1be25881047fdd6962b84

In the above report, two files were created. One of them doesn't exist anymore, but the last one done. Here is a copy/paste of the contents:

Version=1
EventType=APPCRASH
EventTime=130717265368740290
ReportType=2
Consent=1
UploadTime=130717265403962132
ReportIdentifier=45a21901-d29c-11e4-80e6-000c29f9e284
IntegratorReportIdentifier=45a21900-d29c-11e4-80e6-000c29f9e284
WOW64=1
NsAppName=owncloud.exe
Response.BucketId=ca21b7c146f1be25881047fdd6962b84
Response.BucketTable=1
Response.LegacyBucketId=73743994839
Response.type=4
Sig[0].Name=Application Name
Sig[0].Value=owncloud.exe
Sig[1].Name=Application Version
Sig[1].Value=0.0.0.0
Sig[2].Name=Application Timestamp
Sig[2].Value=5492c052
Sig[3].Name=Fault Module Name
Sig[3].Value=libstdc++-6.dll
Sig[4].Name=Fault Module Version
Sig[4].Value=0.0.0.0
Sig[5].Name=Fault Module Timestamp
Sig[5].Value=392a391b
Sig[6].Name=Exception Code
Sig[6].Value=40000015
Sig[7].Name=Exception Offset
Sig[7].Value=0001bfc8
DynamicSig[1].Name=OS Version
DynamicSig[1].Value=6.3.9600.2.0.0.272.7
DynamicSig[2].Name=Locale ID
DynamicSig[2].Value=1033
DynamicSig[22].Name=Additional Information 1
DynamicSig[22].Value=be9d
DynamicSig[23].Name=Additional Information 2
DynamicSig[23].Value=be9d94ed03e09a67718fdfac0f8887f7
DynamicSig[24].Name=Additional Information 3
DynamicSig[24].Value=a41c
DynamicSig[25].Name=Additional Information 4
DynamicSig[25].Value=a41c389cdfa67c144906293a88bbba48
UI[2]=C:\Program Files (x86)\ownCloud\owncloud.exe
UI[3]=owncloud.exe has stopped working
UI[4]=Windows can check online for a solution to the problem.
UI[5]=Check online for a solution and close the program
UI[6]=Check online for a solution later and close the program
UI[7]=Close the program
LoadedModule[0]=C:\Program Files (x86)\ownCloud\owncloud.exe
LoadedModule[1]=C:\Windows\SYSTEM32\ntdll.dll
LoadedModule[2]=C:\Windows\SYSTEM32\KERNEL32.DLL
LoadedModule[3]=C:\Windows\SYSTEM32\KERNELBASE.dll
LoadedModule[4]=C:\Program Files (x86)\ownCloud\libocsync.dll
LoadedModule[5]=C:\Windows\SYSTEM32\msvcrt.dll
LoadedModule[6]=C:\Program Files (x86)\ownCloud\libneon-27.dll
LoadedModule[7]=C:\Program Files (x86)\ownCloud\Qt5Core.dll
LoadedModule[8]=C:\Program Files (x86)\ownCloud\Qt5Gui.dll
LoadedModule[9]=C:\Program Files (x86)\ownCloud\Qt5Network.dll
LoadedModule[10]=C:\Program Files (x86)\ownCloud\Qt5Widgets.dll
LoadedModule[11]=C:\Program Files (x86)\ownCloud\Qt5Xml.dll
LoadedModule[12]=C:\Program Files (x86)\ownCloud\libgcc_s_sjlj-1.dll
LoadedModule[13]=C:\Program Files (x86)\ownCloud\libstdc++-6.dll
LoadedModule[14]=C:\Program Files (x86)\ownCloud\libowncloudsync.dll
LoadedModule[15]=C:\Windows\SYSTEM32\SHLWAPI.dll
LoadedModule[16]=C:\Program Files (x86)\ownCloud\libcrypto-10.dll
LoadedModule[17]=C:\Program Files (x86)\ownCloud\libintl-8.dll
LoadedModule[18]=C:\Program Files (x86)\ownCloud\libproxy.dll
LoadedModule[19]=C:\Program Files (x86)\ownCloud\libssl-10.dll
LoadedModule[20]=C:\Windows\SYSTEM32\WS2_32.dll
LoadedModule[21]=C:\Program Files (x86)\ownCloud\libxml2-2.dll
LoadedModule[22]=C:\Program Files (x86)\ownCloud\zlib1.dll
LoadedModule[23]=C:\Windows\SYSTEM32\ADVAPI32.dll
LoadedModule[24]=C:\Program Files (x86)\ownCloud\icui18n53.dll
LoadedModule[25]=C:\Program Files (x86)\ownCloud\icuuc53.dll
LoadedModule[26]=C:\Windows\SYSTEM32\ole32.dll
LoadedModule[27]=C:\Program Files (x86)\ownCloud\libpcre16-0.dll
LoadedModule[28]=C:\Windows\SYSTEM32\SHELL32.dll
LoadedModule[29]=C:\Windows\SYSTEM32\USER32.dll
LoadedModule[30]=C:\Program Files (x86)\ownCloud\libGLESv2.dll
LoadedModule[31]=C:\Windows\SYSTEM32\GDI32.dll
LoadedModule[32]=C:\Program Files (x86)\ownCloud\libpng16-16.dll
LoadedModule[33]=C:\Windows\SYSTEM32\CRYPT32.dll
LoadedModule[34]=C:\Windows\SYSTEM32\DNSAPI.DLL
LoadedModule[35]=C:\Program Files (x86)\ownCloud\Qt5WebKitWidgets.dll
LoadedModule[36]=C:\Program Files (x86)\ownCloud\libqt5keychain.dll
LoadedModule[37]=C:\Windows\SYSTEM32\combase.dll
LoadedModule[38]=C:\Program Files (x86)\ownCloud\libmodman.dll
LoadedModule[39]=C:\Windows\SYSTEM32\NSI.dll
LoadedModule[40]=C:\Windows\SYSTEM32\RPCRT4.dll
LoadedModule[41]=C:\Windows\SYSTEM32\sechost.dll
LoadedModule[42]=C:\Program Files (x86)\ownCloud\icudata53.dll
LoadedModule[43]=C:\Windows\SYSTEM32\d3d9.dll
LoadedModule[44]=C:\Windows\SYSTEM32\MSASN1.dll
LoadedModule[45]=C:\Program Files (x86)\ownCloud\Qt5WebKit.dll
LoadedModule[46]=C:\Program Files (x86)\ownCloud\Qt5OpenGL.dll
LoadedModule[47]=C:\Program Files (x86)\ownCloud\Qt5PrintSupport.dll
LoadedModule[48]=C:\Program Files (x86)\ownCloud\Qt5Sensors.dll
LoadedModule[49]=C:\Windows\SYSTEM32\SspiCli.dll
LoadedModule[50]=C:\Windows\SYSTEM32\VERSION.dll
LoadedModule[51]=C:\Windows\SYSTEM32\dwmapi.dll
LoadedModule[52]=C:\Program Files (x86)\ownCloud\libEGL.dll
LoadedModule[53]=C:\Program Files (x86)\ownCloud\Qt5Qml.dll
LoadedModule[54]=C:\Program Files (x86)\ownCloud\Qt5Quick.dll
LoadedModule[55]=C:\Program Files (x86)\ownCloud\Qt5Sql.dll
LoadedModule[56]=C:\Program Files (x86)\ownCloud\libjpeg-8.dll
LoadedModule[57]=C:\Program Files (x86)\ownCloud\libsqlite3-0.dll
LoadedModule[58]=C:\Program Files (x86)\ownCloud\libwebp-4.dll
LoadedModule[59]=C:\Windows\SYSTEM32\WINMM.DLL
LoadedModule[60]=C:\Program Files (x86)\ownCloud\libxslt-1.dll
LoadedModule[61]=C:\Windows\SYSTEM32\COMDLG32.DLL
LoadedModule[62]=C:\Windows\SYSTEM32\WINSPOOL.DRV
LoadedModule[63]=C:\Windows\SYSTEM32\CRYPTBASE.dll
LoadedModule[64]=C:\Windows\SYSTEM32\WINMMBASE.dll
LoadedModule[65]=C:\Windows\WinSxS\x86_microsoft.windows.common-controls_6595b64144ccf1df_5.82.9600.17415_none_7c5769eaaa0aa358\COMCTL32.dll
LoadedModule[66]=C:\Windows\SYSTEM32\bcryptPrimitives.dll
LoadedModule[67]=C:\Windows\SYSTEM32\cfgmgr32.dll
LoadedModule[68]=C:\Windows\SYSTEM32\DEVOBJ.dll
LoadedModule[69]=C:\Windows\SYSTEM32\SHCORE.DLL
LoadedModule[70]=C:\Windows\system32\IMM32.DLL
LoadedModule[71]=C:\Windows\SYSTEM32\MSCTF.dll
LoadedModule[72]=C:\Windows\SYSTEM32\profapi.dll
LoadedModule[73]=C:\Program Files (x86)\ownCloud\platforms\qwindows.dll
LoadedModule[74]=C:\Windows\SYSTEM32\OLEAUT32.dll
LoadedModule[75]=C:\Windows\SYSTEM32\kernel.appcore.dll
LoadedModule[76]=C:\Windows\system32\uxtheme.dll
LoadedModule[77]=C:\Windows\SYSTEM32\security.dll
LoadedModule[78]=C:\Windows\SYSTEM32\SECUR32.DLL
LoadedModule[79]=C:\Windows\SYSTEM32\msv1_0.DLL
LoadedModule[80]=C:\Windows\SYSTEM32\cryptdll.dll
LoadedModule[81]=C:\Program Files (x86)\ownCloud\imageformats\qgif.dll
LoadedModule[82]=C:\Program Files (x86)\ownCloud\imageformats\qico.dll
LoadedModule[83]=C:\Program Files (x86)\ownCloud\imageformats\qjpeg.dll
LoadedModule[84]=C:\Windows\SYSTEM32\CRYPTSP.dll
LoadedModule[85]=C:\Windows\system32\rsaenh.dll
LoadedModule[86]=C:\Windows\SYSTEM32\bcrypt.dll
LoadedModule[87]=C:\Windows\system32\winhttp.dll
LoadedModule[88]=C:\Windows\SYSTEM32\IPHLPAPI.DLL
LoadedModule[89]=C:\Windows\SYSTEM32\WINNSI.DLL
LoadedModule[90]=C:\Windows\SYSTEM32\dhcpcsvc6.DLL
LoadedModule[91]=C:\Windows\SYSTEM32\dhcpcsvc.DLL
LoadedModule[92]=C:\Windows\system32\mswsock.dll
LoadedModule[93]=C:\Windows\System32\rasadhlp.dll
LoadedModule[94]=C:\Windows\System32\fwpuclnt.dll
LoadedModule[95]=C:\Windows\SYSTEM32\DPAPI.dll
LoadedModule[96]=C:\Program Files (x86)\ownCloud\accessible\qtaccessiblewidgets.dll
LoadedModule[97]=C:\Windows\system32\napinsp.dll
LoadedModule[98]=C:\Windows\system32\NLAapi.dll
LoadedModule[99]=C:\Windows\System32\winrnr.dll
State[0].Key=Transport.DoneStage1
State[0].Value=1
FriendlyEventName=Stopped working
ConsentKey=APPCRASH
AppName=owncloud.exe
AppPath=C:\Program Files (x86)\ownCloud\owncloud.exe
NsPartner=windows
NsGroup=windows8
ApplicationIdentity=0C44F56AE8530FFEE14561CD824962BB

**Comment by guruz** [comment]
If you use 1.8 there is a crash reported which could help us to track this down..

**Comment by ogoffart** [comment]
Please try again with 1.8
This might be fixed already.
It looks like an assert. You could run it with `--logfile` to save the log in a file  which will show at the end where it asserts.

**Comment by guruz** [comment]
btw, 2.0 beta is coming out soon..
please re-test
