### ISSUE TITLE
Prioritise a folder sync over another

### ISSUE THREAD

**Issue by JakeCowton** [owncloud/client#3039]
I use owncloud to backup some large files from my main desktop, however, when I am doing this, I am also doing work which needs to be synchronised to my other computers.

It would be good if there was a way I could set a specific folder to have sync priority over others which will interrupt other syncing if new changes are detected.

**Comment by willchamberlain** [comment]
Per #3039 - would be a very useful feature.

**Comment by ogoffart** [comment]
2.5 (or was it 2.4?) has now a "force sync now"  option in the "..." menu.
