### ISSUE TITLE
Automatic update doesn't tell who it is

### ISSUE THREAD

**Issue by RobertRad** [owncloud/client#3040]
When I started up my computer, a dialog opened, telling my that an update is needed with only an OK-Box. After I clicked that, Windows UAC popped up and after that *something* happened.

In the whole process, it didn't tell which application it is about and which version is updated. The only advise is the icon in the upper left of the first dialog.

I feel fooled, when an applications needs installation rights, without knowing which application it is.

**Comment by danimo** [comment]
Apologies, that was oviously not intentional. Fixed now for 1.8.1, but will only become visible with the version after that one.
