### ISSUE TITLE
Desktop Sharing - link size differs

### ISSUE THREAD

**Issue by stonerl** [owncloud/client#3041]
When a file is shared the first time via Desktop Sharing the created link looks like this:
![screen shot 2015-03-30 at 10 45 23](https://cloud.githubusercontent.com/assets/2091312/6893056/ef4180b8-d6c9-11e4-8332-874645741a11.png)
When the sharing option is opened again e.g. to unshare the file or look up the link again the link is much shorter.
![screen shot 2015-03-30 at 10 45 34](https://cloud.githubusercontent.com/assets/2091312/6893057/f36e828a-d6c9-11e4-9048-7cee426c63ff.png)
Would it be possible to use the short link in the first place?

**Comment by stonerl** [comment]
Btw. "Set password" sits to close to the  checkbox.

**Comment by rullzer** [comment]
This is a know issue. The server returned the old link. This is already taken care of on the server side is master. And there also is a problem for master to make it more consistent. 

I assume you  run stable. So please verify once 8.1 is out.

**Comment by dragotin** [comment]
So this is fixed.
