### ISSUE TITLE
Crash in OCC::NetworkJobTimeoutPauser::NetworkJobTimeoutPauser

### ISSUE THREAD

**Issue by jturcotte** [owncloud/client#3047]
0  Qt5Core.dll!QObject::metaObject [qobject.cpp : 185 + 0x5]
        eip = 0x66b1c8c4   esp = 0x0028d30c   ebp = 0x0028d3a8   ebx = 0x66cfc2e4
        esi = 0x0803ed80   edi = 0x00000012   eax = 0x00000000   ecx = 0x006f0074
        edx = 0x0000000a   efl = 0x00210206
        Found by: given as instruction pointer in context
     1  Qt5Core.dll!QMetaObject::cast [qmetaobject.cpp : 331 + 0x8]
        eip = 0x66afea95   esp = 0x0028d310   ebp = 0x0028d3a8   ebx = 0x66cfc2e4
        esi = 0x0803ed80   edi = 0x00000012
        Found by: call frame info
     2  libowncloudsync.dll!OCC::NetworkJobTimeoutPauser::NetworkJobTimeoutPauser [qobject.h : 520 + 0x16]
        eip = 0x6a56bc04   esp = 0x0028d320   ebp = 0x0028d3a8   ebx = 0x0028d5c0
        esi = 0x0028d5f4   edi = 0x00000012
        Found by: call frame info
     3  libowncloudsync.dll!OCC::Account::slotHandleErrors [account.cpp : 443 + 0x18]
        eip = 0x6a546c94   esp = 0x0028d3b0   ebp = 0x0028d498   ebx = 0x0028d5c0
        esi = 0x0028d5f4   edi = 0x00000012
        Found by: call frame info
     4  libowncloudsync.dll!OCC::Account::qt_static_metacall [moc_account.cpp : 220 + 0x3c]
        eip = 0x6a5da04c   esp = 0x0028d4a0   ebp = 0x0028d508   ebx = 0x0028d5c0
        esi = 0x0028d5f4   edi = 0x00000012
        Found by: call frame info
     5  Qt5Core.dll!QMetaObject::activate [qobject.cpp : 3716 + 0x31]
        eip = 0x66b1ec62   esp = 0x0028d510   ebp = 0x0028d5d8   ebx = 0x0028d5c0
        esi = 0x0028d5f4   edi = 0x00000012
        Found by: call frame info
     6  Qt5Network.dll!QNetworkAccessManager::sslErrors [moc_qnetworkaccessmanager.cpp : 328 + 0xe]
        eip = 0x6d42889c   esp = 0x0028d5e0   ebp = 0x0028d748   ebx = 0x07eb5788
        esi = 0x0028d768   edi = 0x00000012
        Found by: call frame info
     7  Qt5Network.dll!QNetworkAccessManagerPrivate::_q_replySslErrors [qnetworkaccessmanager.cpp : 1325 + 0x12]
        eip = 0x6d4296e6   esp = 0x0028d610   ebp = 0x0028d748   ebx = 0x07eb5788
        esi = 0x0028d768   edi = 0x00000012
        Found by: call frame info
     8  Qt5Network.dll!QNetworkAccessManager::qt_static_metacall [moc_qnetworkaccessmanager.cpp : 155 + 0x12]
        eip = 0x6d42b474   esp = 0x0028d630   ebp = 0x0028d748   ebx = 0x0028d768
        esi = 0x0028d768   edi = 0x00000012
        Found by: call frame info
     9  Qt5Core.dll!QMetaObject::activate [qobject.cpp : 3716 + 0x31]
        eip = 0x66b1ec62   esp = 0x0028d680   ebp = 0x0028d748   ebx = 0x0028d730
        esi = 0x0028d768   edi = 0x00000012
        Found by: call frame info
    10  Qt5Network.dll!QNetworkReply::sslErrors [moc_qnetworkreply.cpp : 340 + 0xe]
        eip = 0x6d4d1174   esp = 0x0028d750   ebp = 0x0028d928   ebx = 0x0ccd2da0
        esi = 0x073bc64c   edi = 0x00000012
        Found by: call frame info
    11  Qt5Network.dll!QNetworkReplyHttpImplPrivate::replySslErrors [qnetworkreplyhttpimpl.cpp : 1252 + 0x8]
        eip = 0x6d44b62a   esp = 0x0028d780   ebp = 0x0028d928   ebx = 0x0ccd2da0
        esi = 0x073bc64c   edi = 0x00000012
        Found by: call frame info
    12  Qt5Network.dll!QNetworkReplyHttpImpl::qt_static_metacall [moc_qnetworkreplyhttpimpl_p.cpp : 234 + 0x26]
        eip = 0x6d4d2237   esp = 0x0028d7b0   ebp = 0x0028d928   ebx = 0x0cced3d8
        esi = 0x07e3ac30   edi = 0x00000012
        Found by: call frame info
    13  Qt5Core.dll!QMetaCallEvent::placeMetaCall [qobject.cpp : 485 + 0x1d]
        eip = 0x66b1c879   esp = 0x0028d820   ebp = 0x0028d928   ebx = 0x0cced3d8
        esi = 0x07e3ac30   edi = 0x00000012
        Found by: call frame info
    14  Qt5Core.dll!QObject::event [qobject.cpp : 1245 + 0x14]
        eip = 0x66b1fec9   esp = 0x0028d850   ebp = 0x0028d928   ebx = 0x07e3ac30
        esi = 0x0cced3d8   edi = 0x0451b9e0
        Found by: call frame info
    15  Qt5Widgets.dll!QApplicationPrivate::notify_helper [qapplication.cpp : 3722 + 0xa]
        eip = 0x03ddae9a   esp = 0x0028d930   ebp = 0x0028fe40   ebx = 0x07e3ac30
        esi = 0x0cced3d8   edi = 0x0451b9e0
        Found by: call frame info
    16  Qt5Widgets.dll!QApplication::notify [qapplication.cpp : 3505 + 0x17]
        eip = 0x03ddff77   esp = 0x0028d960   ebp = 0x0028fe40   ebx = 0x00000000
        esi = 0x00000401   edi = 0x0cced3d8
        Found by: call frame info
    17  Qt5Core.dll!QCoreApplication::notifyInternal [qcoreapplication.cpp : 932 + 0x1a]
        eip = 0x66af6c00   esp = 0x0028dad0   ebp = 0x0028db38   ebx = 0x0d3afe94
        esi = 0x0000002b   edi = 0x00000000
        Found by: call frame info
    18  Qt5Core.dll!QCoreApplicationPrivate::sendPostedEvents [qcoreapplication.h : 228 + 0x2a]
        eip = 0x66afb98e   esp = 0x0028db40   ebp = 0x0028dbf8   ebx = 0x0d3afe94
        esi = 0x0000002b   edi = 0x00000000
        Found by: call frame info
    19  Qt5Core.dll!QCoreApplication::sendPostedEvents [qcoreapplication.cpp : 1394 + 0x18]
        eip = 0x66afc157   esp = 0x0028dc00   ebp = 0x0028dce8   ebx = 0x0451bec0
        esi = 0x66b4bd90   edi = 0x00000000
        Found by: call frame info
    20  qwindows.dll!QWindowsGuiEventDispatcher::sendPostedEvents [qwindowsguieventdispatcher.cpp : 81 + 0x15]
        eip = 0x6dee972b   esp = 0x0028dc20   ebp = 0x0028dce8   ebx = 0x0451bec0
        esi = 0x66b4bd90   edi = 0x00000000
        Found by: call frame info
    21  Qt5Core.dll!qt_internal_proc [qeventdispatcher_win.cpp : 412 + 0x10]
        eip = 0x66b4c09f   esp = 0x0028dc40   ebp = 0x0028dce8   ebx = 0x00000000
        esi = 0x66b4bd90   edi = 0x00000000
        Found by: call frame info
    22  user32.dll + 0x162fa
        eip = 0x759462fa   esp = 0x0028dcf0   ebp = 0x0028dd20
        Found by: previous frame's frame pointer
    ...

Found 10 crash reports with this stack trace.

**Comment by danimo** [comment]
Debugged this with Jocelyn, and we concluded it has the the same cause as #2984.

See 3c9acdf724e3bc01be2da1ea0d6467a8f42c6ae6 which fixes it.
