### ISSUE TITLE
Crash in OCC::SslButton::updateAccountState

### ISSUE THREAD

**Issue by jturcotte** [owncloud/client#3048]
0  Qt5Network.dll!QSslCertificate::issuerInfo [qmap.h : 362 + 0x0]
        eip = 0x6d4bb2ab   esp = 0x0028cea0   ebp = 0x0028cfe8   ebx = 0x0cda97a1
        esi = 0x0cde133c   edi = 0x0028cf98   eax = 0x00000000   ecx = 0x0cda9b0c
        edx = 0x80092001   efl = 0x00010202
        Found by: given as instruction pointer in context
     1  owncloud.exe!OCC::SslButton::updateAccountState [sslbutton.cpp : 205 + 0x13]
        eip = 0x0047741f   esp = 0x0028cee0   ebp = 0x0028cfe8   ebx = 0x05ae3848
        esi = 0x0028d0ec   edi = 0x05ae3848
        Found by: call frame info
     2  owncloud.exe!OCC::AccountSettings::slotAccountStateChanged [accountsettings.cpp : 788 + 0x18]
        eip = 0x00408fe5   esp = 0x0028cff0   ebp = 0x0028d0c8   ebx = 0x05ae3848
        esi = 0x0028d0ec   edi = 0x05ae3848
        Found by: call frame info
     3  owncloud.exe!OCC::AccountSettings::setGeneralErrors [accountsettings.cpp : 255 + 0x17]
        eip = 0x0040adb6   esp = 0x0028d0d0   ebp = 0x0028d268   ebx = 0x05abeb94
        esi = 0x0028d0ec   edi = 0x05ae3848
        Found by: call frame info
     4  owncloud.exe!OCC::ownCloudGui::slotComputeOverallSyncStatus [owncloudgui.cpp : 238 + 0x1b]
        eip = 0x004453ab   esp = 0x0028d150   ebp = 0x0028d268   ebx = 0x0028d418
        esi = 0x0028d418   edi = 0x00000005
        Found by: call frame info
     5  owncloud.exe!OCC::ownCloudGui::slotSyncStateChange [owncloudgui.cpp : 176 + 0xc]
        eip = 0x004465f7   esp = 0x0028d270   ebp = 0x0028d308   ebx = 0x0028d418
        esi = 0x0028d418   edi = 0x00000005
        Found by: call frame info
     6  owncloud.exe!OCC::ownCloudGui::qt_static_metacall [moc_owncloudgui.cpp : 185 + 0xb]
        eip = 0x00499b3b   esp = 0x0028d310   ebp = 0x0028d3f8   ebx = 0x0028d418
        esi = 0x0028d418   edi = 0x00000005
        Found by: call frame info
     7  Qt5Core.dll!QMetaObject::activate [qobject.cpp : 3716 + 0x31]
        eip = 0x66b1ec62   esp = 0x0028d330   ebp = 0x0028d3f8   ebx = 0x0028d3e0
        esi = 0x0028d418   edi = 0x00000005
        Found by: call frame info
     8  owncloud.exe!OCC::FolderMan::folderSyncStateChange [moc_folderman.cpp : 243 + 0xe]
        eip = 0x00498204   esp = 0x0028d400   ebp = 0x0028d4c8   ebx = 0x0028d690
        esi = 0x0028d6c8   edi = 0x00000005
        Found by: call frame info
     9  owncloud.exe!OCC::FolderMan::setupFolders [folderman.cpp : 216 + 0x22]
        eip = 0x00426b20   esp = 0x0028d430   ebp = 0x0028d4c8   ebx = 0x0028d690
        esi = 0x0028d6c8   edi = 0x00000005
        Found by: call frame info
    10  owncloud.exe!OCC::Application::slotownCloudWizardDone [application.cpp : 317 + 0x7]
        eip = 0x0040b8c9   esp = 0x0028d4d0   ebp = 0x0028d558   ebx = 0x0028d690
        esi = 0x0028d6c8   edi = 0x00000005
        Found by: call frame info
    11  owncloud.exe!OCC::Application::qt_static_metacall [moc_application.cpp : 128 + 0x1a]
        eip = 0x0049a9fa   esp = 0x0028d560   ebp = 0x0028d5d8   ebx = 0x0028d690
        esi = 0x0028d6c8   edi = 0x00000005
        Found by: call frame info
    12  Qt5Core.dll!QMetaObject::activate [qobject.cpp : 3716 + 0x31]
        eip = 0x66b1ec62   esp = 0x0028d5e0   ebp = 0x0028d6a8   ebx = 0x0028d690
        esi = 0x0028d6c8   edi = 0x00000005
        Found by: call frame info
    13  owncloud.exe!OCC::OwncloudSetupWizard::ownCloudWizardDone [moc_owncloudsetupwizard.cpp : 330 + 0xe]
        eip = 0x004983b4   esp = 0x0028d6b0   ebp = 0x0028d788   ebx = 0x0cde8d78
        esi = 0x0ce57618   edi = 0x00000005
        Found by: call frame info
    14  owncloud.exe!OCC::OwncloudSetupWizard::slotAssistantFinished [owncloudsetupwizard.cpp : 457 + 0x15]
        eip = 0x0044dd0d   esp = 0x0028d6e0   ebp = 0x0028d788   ebx = 0x0cde8d78
        esi = 0x0ce57618   edi = 0x00000005
        Found by: call frame info
    15  owncloud.exe!OCC::OwncloudSetupWizard::qt_static_metacall [moc_owncloudsetupwizard.cpp : 242 + 0x1a]
        eip = 0x0049be0e   esp = 0x0028d790   ebp = 0x0028d818   ebx = 0x0cde8d78
        esi = 0x0ce57618   edi = 0x00000005
        Found by: call frame info
    16  Qt5Core.dll!QMetaCallEvent::placeMetaCall [qobject.cpp : 485 + 0x1d]
        eip = 0x66b1c879   esp = 0x0028d820   ebp = 0x0028d928   ebx = 0x0cde8d78
        esi = 0x0ce57618   edi = 0x00000005
        Found by: call frame info
    17  Qt5Core.dll!QObject::event [qobject.cpp : 1245 + 0x14]
        eip = 0x66b1fec9   esp = 0x0028d850   ebp = 0x0028d928   ebx = 0x0ce57618
        esi = 0x0cde8d78   edi = 0x0062b578
        Found by: call frame info
    18  Qt5Widgets.dll!QApplicationPrivate::notify_helper [qapplication.cpp : 3722 + 0xa]
        eip = 0x03e0ae9a   esp = 0x0028d930   ebp = 0x0028fe40   ebx = 0x0ce57618
        esi = 0x0cde8d78   edi = 0x0062b578
        Found by: call frame info
    19  Qt5Widgets.dll!QApplication::notify [qapplication.cpp : 3505 + 0x17]
        eip = 0x03e0ff77   esp = 0x0028d960   ebp = 0x0028fe40   ebx = 0x00000000
        esi = 0x00000401   edi = 0x0cde8d78
        Found by: call frame info
    20  Qt5Core.dll!QCoreApplication::notifyInternal [qcoreapplication.cpp : 932 + 0x1a]
        eip = 0x66af6c00   esp = 0x0028dad0   ebp = 0x0028db38   ebx = 0x063fa030
        esi = 0x0000002b   edi = 0x00000000
        Found by: call frame info
    21  Qt5Core.dll!QCoreApplicationPrivate::sendPostedEvents [qcoreapplication.h : 228 + 0x2a]
        eip = 0x66afb98e   esp = 0x0028db40   ebp = 0x0028dbf8   ebx = 0x063fa030
        esi = 0x0000002b   edi = 0x00000000
        Found by: call frame info
    22  Qt5Core.dll!QCoreApplication::sendPostedEvents [qcoreapplication.cpp : 1394 + 0x18]
        eip = 0x66afc157   esp = 0x0028dc00   ebp = 0x0028dce8   ebx = 0x0062c2c8
        esi = 0x66b4bd90   edi = 0x00000000
        Found by: call frame info
    23  qwindows.dll!QWindowsGuiEventDispatcher::sendPostedEvents [qwindowsguieventdispatcher.cpp : 81 + 0x15]
        eip = 0x6dee972b   esp = 0x0028dc20   ebp = 0x0028dce8   ebx = 0x0062c2c8
        esi = 0x66b4bd90   edi = 0x00000000
        Found by: call frame info
    24  Qt5Core.dll!qt_internal_proc [qeventdispatcher_win.cpp : 412 + 0x10]
        eip = 0x66b4c09f   esp = 0x0028dc40   ebp = 0x0028dce8   ebx = 0x00000000
        esi = 0x66b4bd90   edi = 0x00000000
        Found by: call frame info
    25  user32.dll + 0x162fa
        eip = 0x764062fa   esp = 0x0028dcf0   ebp = 0x0028dd20
        Found by: previous frame's frame pointer
    26  user32.dll + 0x16d3a
        eip = 0x76406d3a   esp = 0x0028dd28   ebp = 0x0028dd98
        Found by: previous frame's frame pointer
    27  user32.dll + 0x177c4
        eip = 0x764077c4   esp = 0x0028dda0   ebp = 0x0028ddf8
        Found by: previous frame's frame pointer
    28  user32.dll + 0x1788a
        eip = 0x7640788a   esp = 0x0028de00   ebp = 0x0028de08
        Found by: previous frame's frame pointer
    29  Qt5Core.dll!QEventDispatcherWin32::processEvents [qeventdispatcher_win.cpp : 806 + 0x9]
        eip = 0x66b4b6b7   esp = 0x0028de10   ebp = 0x0028fbf8
        Found by: previous frame's frame pointer
    30  qwindows.dll!QWindowsGuiEventDispatcher::processEvents [qwindowsguieventdispatcher.cpp : 73 + 0xc]
        eip = 0x6dee97b1   esp = 0x0028fc00   ebp = 0x0028fc88
        Found by: previous frame's frame pointer
    31  Qt5Core.dll!QEventLoop::exec [qeventloop.cpp : 128 + 0x14]
        eip = 0x66af5b68   esp = 0x0028fc90   ebp = 0x0028fd28
        Found by: previous frame's frame pointer
    32  Qt5Core.dll!QCoreApplication::exec [qcoreapplication.cpp : 1185 + 0x13]
        eip = 0x66afcd18   esp = 0x0028fd30   ebp = 0x0028fda8   ebx = 0x00000001
        esi = 0x0062ac38
        Found by: call frame info
    33  owncloud.exe!main [main.cpp : 121 + 0x10]
        eip = 0x004dbc3f   esp = 0x0028fdb0   ebp = 0x0028feb8   ebx = 0x00000001
        esi = 0x0062ac38
        Found by: call frame info
    ...

Found **139** crash reports with this stack trace.

**Comment by guruz** [comment]
In 1.8.1 that code should run on-demand (button click), then it has not a that big impact.

**Comment by danimo** [comment]
@guruz We already fixed that one anyway with 9c05150c121a06e58e172facf509fd188c35d59d.
