### ISSUE TITLE
OpenSUSE 13.2 - "zypper up" wants to replace owncloud-client by owncloud-client-qt5

### ISSUE THREAD

**Issue by cloudyql** [owncloud/client#3054]
May be an OpenSUSE problem or with the Owncloud repo.

I really don't know where this problem lies, but I have a newish OpenSUSE 13.2 desktop and added the Owncloud desktop repo, as usually Just Works.  "zypper in owncloud-client" does the job and version 1.8.0-4.1 is installed.  However, when I update the system with "zypper up" the following is reported:
----
    The following 3 NEW packages are going to be installed:
      libowncloudqt5sync0 owncloud-client-qt5 owncloud-client-qt5-l10n

    The following 3 packages are going to be REMOVED:
      libowncloudsync0 owncloud-client owncloud-client-l10n 
----

A "zypper info owncloud-client-qt5" results in this being version 1.7.1-1.2

But if I go with the flow and accept the recommendation, then the next time I run "zypper up" it flips back to the latest version, and so on ad infinitum. There is no way, as far as I can tell, of pinning versions with zypper as there is in apt, and I have failed to find any such issue after some hours of searching. Any helpful suggestions most welcome.  I asked in the forums where it was suggested that I file a bug report, and thinking about it, the problem may well be priorities in the the ownbcloud repository.

**Comment by cloudyql** [comment]
Apologies for the ludicrous formating. Not used to github reporting.

**Comment by danimo** [comment]
ownCloud Client with Qt5 is not yet moved to 1.8. Only the Qt 4 variant. (`owncloud-client`)

**Comment by cloudyql** [comment]
Understood, but what I'm puzzled about is why OpenSUSE wants to install the qt5 (1.7) version on an update when I already have 1.8 installed.

**Comment by danimo** [comment]
No idea, sorry.

**Comment by danimo** [comment]
The reason _could_ be that the spec says "obsoletes: owncloud-client". I think the assumption was that obsoletes acts like "conflicts", but it seems it doesn't.

/cc @dragotin 

FWIW, I've upgraded the owncloud-client-qt5 package to 1.8.0.

**Comment by danimo** [comment]
That said, upgrading should be fine, but since the changelog mentioned it's experimental, I think a silent replacement is not what we want here, and we need to make sure we always provide upgrades for both packages at the same time anyway. We'll let @dragotin be the judge of that.

**Comment by cloudyql** [comment]
Thanks for this - I started thinking it was something I had done on my installation, but it seemed unlikely, so I'm pleased you found a cause.

**Comment by danimo** [comment]
Looking into this a bit deeper, the owncloud-client-qt5 package is obsolete, because the owncloud-client package already uses Qt5 where possible with 1.8. I thus removed the owncloud-client-qt5 package.

**Comment by cloudyql** [comment]
Thanks
