### ISSUE TITLE
Conflict with overlay icons used by ownCloud client and TortoiseHG

### ISSUE THREAD

**Issue by gnotaras** [owncloud/client#3056]
Hello and thanks for developing this application.

Installing the latest versions of the ownCloud desktop client and TortoiseHG under Windows results in the overlay icons of mercurial repositories to disappear in Windows Explorer.

This problem has been reported again in #2555, which was closed as a duplicate of #2552 (which is hardly the case). Although #2552 has been fixed, the problem described in #2555 still exists.

I can understand the the fix would involve one of the following things:

* Come into an agreement with the Tortoise{HG,Git,SVN,Bzr,etc} developers and possibly make these icons an external library which you will all use. There is absolutely no valid reason to use different set of icons.
* Add some logic to the installer, which could detect the existence of TortoiseX overlay icons and offer the user the option to use them instead of installing its own. TortoiseX users are most probably experienced enough to understand what this is about.

Please make sure you resolve this as it is a pity to see two great pieces of open source software conflict. Does not make sense.

Thank you in advance.

**Comment by GMTA** [comment]
I would like to add to this discussion that the current behavior of OC client's installer to prepend two spaces to the registry keys in order to get prioritized when compared to other application's keys is a bit aggressive.

**Comment by gnotaras** [comment]
I agree. It is definitely not a behavior that represents open source development and more importantly not a good way to solve problems.

**Comment by danimo** [comment]
API wise there simply is no way to register more than 15 icons, that's correct. The problem is that they need to be registered _up front_ (i.e. the the first time explorer launches). So 'I'd rather have Tortoise in this folder, but ownCloud in that' is simply not possible.

**Comment by gnotaras** [comment]
Hello danimo, thanks for replying to this issue.

> "I'd rather have Tortoise icons in this folder, but ownCloud ones in that other"
You refuse to see the truth here. Noone is asking for something like the above.

Please re-open the issue and let discussion take place.

**Comment by danimo** [comment]
Discussion for what? As-is, there is no technical solution to the problem. The problem is known, and none of the options in the original bug reports are feasible.

**Comment by GMTA** [comment]
@danimo Part of the problem is that OC's client takes **priority** by prefixing it with two spaces. Like @gnotaras said, it would be preferred to cooperate with other projects such as the Tortoise* family in order to prevent the OC client from breaking those and possibly other application's integration in the shell.

Of course, you cannot fix this issue the way you would like, because the shell stops loading overlays after 15. But that does not mean there is no problem with how the current solution works.

**Comment by gnotaras** [comment]
As I see it, taking into account the limitations, the only solution that makes sense is cooperation. On the other hand, such a collaboration could involve technical problems which I might not be able to think of. So I am not going to insist.

On the other hand, IMHO, closing this or similar issues is not the most efficient way to deal with the situation. The problem still exists, there are possible or less possible solutions and people will want to discuss about them one way or another.

**Comment by gnotaras** [comment]
@danimo  I've been thinking about this again and every time I come to the same conclusion. If every popular project like ownCloud and the Tortoise family of tools starts shipping its own overlay icons and start prefixing them with spaces in the Windows registry, that would make no sense at all. The only way to resolve this is to collaborate.

Moreover, if such a collaboration effort does not start from popular projects like this or the Tortoise* tools, then it is very unlikely to happen.

Also, your negative attitude towards such a known issue is not very constructive. I'd suggest that you started a new issue/discussion and let people express their opinion and discuss the available options. Maybe a solution comes from the people that are affected by the way this issue is handled.

Kind Regards,
George

**Comment by dragotin** [comment]
@gnotaras I see your point of using a common set of icons on windows. I do not so much agree however on your statement "there is absolutely no reason to *not* share these icons." There is. Unfortunately these icons are an important part of the visual "identity" of a project, and this is a point where projects are very sensitive. For good reasons, it's the first thing a user normally realizes from a project.

That said, I do not say its impossible, but it will be hard. Why not you find the relevant people of the projects you think that are involved and talk to them? Propose your idea, try to push it! It's nothing we @owncloud/desktop-developers will spend effort on at the moment, but we will be open to discuss. But as it is in free software, if **you** want an idea to evolve, jump in and get s$&t done! 

@jancborchardt input?

**Comment by jancborchardt** [comment]
As far as I can see, the only icons we share between the projects are the »green checkmark« and the »red exclamation mark«. I don’t have Windows so I can’t check TortoiseHG, but they most probably do not have icons for »Sharing« which we definitely need. So the problem would still persist.

And as @dragotin said, icons are part of the visual identity of a project. As far as I can see from the screenshots, the TortoiseHG icons are too shiny and different from the ownCloud style for us to use them anyway.

Also cc @yuja from TortoiseHG to see if we can somehow resolve this conflict. :)

**Comment by GMTA** [comment]
@dragotin @jancborchardt As far as I know, the Tortoise* projects allow different icon sets to be used and by default they install a number of them. So you could offer a preferred default set while still allowing the user to select another icon set to its choosing. The visual identity can be retained.

But even if this is not the way to go, please expand as to why you force your own icons to the top of explorer's food chain. I'm not happy having to reopen regedit to fix the icon priorities everytime OC releases a client update...

**Comment by gnotaras** [comment]
@dragotin @jancborchardt I'd like to say that my initial intention when opening this ticket was to start a discussion about possible solutions for a problem that exists and which might have been resolved in a way that possibly is not the optimal and not waste the developers or anyone else's time. :)

I could get involved with this issue, but it would require a huge amount of time to get familiar with the projects and the current implementation of the overlay icons before I could contact either the owncloud or tortoise* devs about the technical details of a possible solution and know what I am talking about. This is not optimal. I have my own projects to take care of. For you, it's just a matter of writing a few lines to @yuja or anyone else who is involved with the tortoisehg project. So, I am going to wait until an owncloud or tortoise* dev finds the time to take a closer look at this.

The situation is like this: Two popular pieces of software use different overlay icons as visual representations of file statuses, while some of those statuses are or could be common, and end up competing for the order of the registry entries that are related to those overlay icons due to MS Windows' limitations and finally conflicting.

On the other hand, I guess we can say it's a matter of different taste of icon styles and end this discussion forever. I have no valid arguments if this is the case.

In either case, my suggestion is to leave the discussion open.

George

**Comment by Aikhjarto** [comment]
Tortoise has an option to deactivate some overlays. Maybe the owncloud client could have that option too?

**Comment by yuja** [comment]
Does "deactivate" remove icons from the `ShellIconOverlayIdentifiers` registry key?
If not, it won't help. I heard that the number of the registered overlay icons is limited.

**Comment by jancborchardt** [comment]
> Tortoise has an option to deactivate some overlays. Maybe the owncloud client could have that option too?

We won’t introduce that. The icons are elementary to letting people know the state of their files.


@gnotaras

> I have my own projects to take care of. For you, it's just a matter of writing a few lines to @yuja or anyone else who is involved with the tortoisehg project. So, I am going to wait until an owncloud or tortoise* dev finds the time to take a closer look at this.

You assume it’s easy for us but it’s not. It requires a bunch of time put into it which might better be spent on other things. This includes the text already written here. ;)

**Comment by Aikhjarto** [comment]
> We won’t introduce that. The icons are elementary to letting people know the state of their files.

Yes, the overlays made by the owncloud client are important. But so are the overlays from other projects like the tortoise apps.
IMHO it should be the users choice whats important to him/her and how to use the limited number of overlays. 
If a user wants to get rid of the overlay it's much safer for him/her (and the installation of the owncloud client) to have an option to deactivate the overlays instead of being forced to hassle around in the registry.
Of course, as default the overlays of should be activated.

**Comment by GMTA** [comment]
@jancborchardt Why does the OC client force itself to the top of the icon list by using two spaces in front of the keys' names?

It seems that this would be 2 minutes to fix.

**Comment by danimo** [comment]
@Aikhjarto That already exists -- as an option in the installer. @GMTA Because that's Best Practise (tm) to take precedence Otherwise, we'd be at the losing end. Microsoft's OneDrive client uses the same "technique", as do many others. Again, there is no good solution.

**Comment by danimo** [comment]
Locking that issue to reduce noise. We will happily accept a  _technically feasible_ solution (i.e. pull-request).
