### ISSUE TITLE
Cannot send e-mail or use ssh while sync ownCloud client

### ISSUE THREAD

**Issue by francesco1119** [owncloud/client#3058]
Hello,

I have ownCloud installed on a shared server and since the first day I cannot send e-mail or use ssh while owCloud client is active.
The problem suddently desapear if I shut down the client.
Am I the only one?

**Comment by guruz** [comment]
Do you mean ssh to that server and e-mail via that server?
What versions of client and server?

**Comment by ogoffart** [comment]
and what operating system are you running, which version?

**Comment by francesco1119** [comment]
I'm using OwnCloud client on a Debian Wheezy and the OwnCloud server is on a shared host on GreenGeeks. Since the first day, while I'm sync with OwnCloud, I cannot use SSH in order to connet to ANY server. Also I cannot send e-mail with Thunderbird.
All problems disappear as soon as I shut down OwnCloud on my laptop.

**Comment by guruz** [comment]
@francesco1119 Which versions of the oC client and the oC server are those? You can see the version of the client in the settings dialog.

**Comment by francesco1119** [comment]
OwnCloud Client version: 1.8.0
OwnCloud server version: 8.0

**Comment by ogoffart** [comment]
And why can't you ssh or send emails? What are the errors you get?

**Comment by francesco1119** [comment]
Fixed now!
The problem was that I had put a file of 1GB size and it could't upload it as it only can upload till 64MB. Deleted the file the problem has disappeared. But If I put a file of more than 64MB the problem still persist as it's unable to upload it.

QUESTION: wouldn't be possible to integrate the use of "split" command in both client and server in order to:
1) Split files of more than 64MB
2) upload them
3) recreate them on the server and destroying the pieces?

Thank you

**Comment by ogoffart** [comment]
We already split the files in chunks of 5MiB

**Comment by francesco1119** [comment]
...mmmm.... I've set the php maximum-size to 64MB (couldn't do more on a shared hosting) and this is the size that actually works. More than that, I promise you, will not upload. Something is limiting my upload server-side?

**Comment by guruz** [comment]
The files are sent in 5 MB chunks, the maximum size for PHP will never reach 64 MB.
Run the client with ```--logfile -``` to see what is happening.

**Comment by dragotin** [comment]
Maybe you 
- have not enough harddisk space left on the server?
- The provider is blocking your requests because they think the client does too much http requests?

**Comment by francesco1119** [comment]
The server has got infinite space and anyway now I'm trying with a 500MB video. The provider is still not blocking. I'm now trying to sync with the same account from a Windows 7 client. I will tell you in few hours if the problem exist under win

**Comment by francesco1119** [comment]
I confirm you that the problem persists on both Debian and Windows 7 clients:

Debian: Cannot upload big file (3GB) and after 12 hours is still sync; while this impossible to receive/send e-mail on Thunderbird and connect trough SSH

Windows 7: Impossible to upload big file (500MB) after 12 hours.

The problem is definetly not on the client but on the server side on Greengeeks hosting?

**Comment by danimo** [comment]
Yes.

**Comment by francesco1119** [comment]
Can you just suggest me an hosting that doesn't produce this error with a shared hosting.
Od is the shared hosting the problem?

**Comment by francesco1119** [comment]
WHAT A JOY: I've solved the problem and now I can upload files of any size both from Debian and Windows 7 client. The problem? I had to move the folder "/data" outside the OwnCloud main folder.

The problem with e-mail and SSH connection while sycronyzing still persist :(
