### ISSUE TITLE
Sync tags on OS X

### ISSUE THREAD

**Issue by letsgo008** [owncloud/client#3061]
Since OS X Mavericks, tagging is an integrated part of OS X file management, but since owncloud client does not sync the tags it is hard to use them consistently while using owncloud. 
(Dropbox supports syncing of tags (and other extended attributes) since forever ...)

Just another small push for this: Brett Terpstra, renowned blogger and developer, is writing a book on tagging in OSX. In his blog post [How to lose your tags] he hints that a section will be dedicated to tools and services that support or don't preserve tags.

http://brettterpstra.com/2014/07/04/how-to-lose-your-tags/

**Comment by guruz** [comment]
Duplicate https://github.com/owncloud/client/issues/1159
