### ISSUE TITLE
[Windows v1.8.0 / b4893] ShellIconOverlayIdentifiers space prefix breaks other applications

### ISSUE THREAD

**Issue by GMTA** [owncloud/client#3062]
The OC client installs its explorer icon overlays in the following registry path:

HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers

As far as I know, explorer supports a maximum of 15 defined overlays and loads these in alphabetical order. Now the OC client seems to install keys with two spaces "  " prefixed which causes OC's entries to be loaded first before any other application's entries.

I don't think this is proper behavior. You now have broken my TortoiseGit overlays, for example.

Suggested solution: keep this behavior for a simple install, but introduce information about this in the advanced options of the installer. You could show the currently defined icon overlays and offer a number of options to deal with this.

**Comment by guruz** [comment]
Duplicate https://github.com/owncloud/client/issues/3056
