### ISSUE TITLE
Move reconcilation to sync thread and slim down C/C++ mishmash

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3064]
`void SyncEngine::slotDiscoveryJobFinished(int discoveryResult)`

...since it can potentially take a quite long time (proportional to amount of files/folders) and then block the UI.

**Comment by guruz** [comment]
Also: Port csync_reconcile to C++ so we can remove the two ```csync_walk_local_tree``` calls and have ```csync_reconcile``` directly create ```SyncFileItem```.

**Comment by guruz** [comment]
I had quickly added ```Peak Memory``` tag here but that is wrong, the memory is already freed by then.
The peak should be after ```// The map was used for merging trees, convert it to a list:```

**Comment by guruz** [comment]
This is partly done.
Should still be moved to sync thread..

**Comment by ogoffart** [comment]
there is no more reconcile phase.
