### ISSUE TITLE
PC Client does not remember password

### ISSUE THREAD

**Issue by viper1vip** [owncloud/client#3074]
Can anybody fix my problem: I have PC client of OC. I was using it without any problems, but since 2 weeks it does not remember password to OC account. All settings OC remember, only password do not remember.
Why?

**Comment by danimo** [comment]
Thank you for your bug report, but we cannot help you if you do not provide details on your setup. Please fill in [this template](https://raw.github.com/owncloud/client/master/issue_template.md)

**Comment by guruz** [comment]
Please retry with 2.0 (beta coming out this week)
