### ISSUE TITLE
error extracting archive attempting to update client on OS X

### ISSUE THREAD

**Issue by blaiddwyn** [owncloud/client#3076]
3 times client reports update available (on different days).
3 times it reports failing to extract downloaded (24.3MB) archive.

Yosemite has been restarted, permissions repaired - all the usual.
Error persists.

**Comment by guruz** [comment]
@eagles051387 is that the same message you saw?

@blaiddwyn if you run ```Console``` on your Mac before launching the update, does it show any relevant detailed error message?

**Comment by nvadave** [comment]
Same issue. Looks like a DSA mismatch. Here's what console sees.

4/9/15 1:52:33.004 PM owncloud[76472]: Sparkle: Extracting /Users/dt/Library/Application Support/owncloud/.Sparkle/owncloud 1.8.0.2139/ownCloud-1.8.0.2139.pkg.tbz using 'tar -jxC "$DESTINATION"'

4/9/15 1:52:43.024 PM owncloud[76472]: Sparkle: DSA signature does not match. Data of the update file being checked is different than data that has been signed, or the public key and the private key are not from the same set.

4/9/15 1:52:47.958 PM owncloud[76472]: Sparkle: Error: An error occurred while extracting the archive. Please try again later. The update is improperly signed.

**Comment by guruz** [comment]
@dragotin Whatever the issue is, maybe we should even skip 1.8.0 update and give users the 1.8.1 in some weeks.

**Comment by danimo** [comment]
Fixed. Please retest

**Comment by nvadave** [comment]
That fix did not work, even after reboot. There is now a date related DSA mismatch. 

Console output:

4/9/15 2:09:16.160 PM owncloud[236]: Sparkle: Extracting /Users/dt/Library/Application Support/owncloud/.Sparkle/owncloud 1.8.0.2139/ownCloud-1.8.0.2139.pkg.tbz using 'tar -jxC "$DESTINATION"'

4/9/15 2:09:20.295 PM owncloud[236]: Sparkle: DSA signature does not match. Data of the update file being checked is different than data that has been signed, or the public key and the private key are not from the same set.

4/9/15 2:09:21.996 PM owncloud[236]: Sparkle: Error: An error occurred while extracting the archive. Please try again later. The update is improperly signed.

**Comment by danimo** [comment]
Now :)

**Comment by nvadave** [comment]
That did the trick. Thanks Daniel.

**Comment by eagles051387** [comment]
Issue was the connection I was on. I tried again yesterday at the office
and it was fine.

On Thu, Apr 9, 2015 at 11:30 PM, nvadave <notifications@github.com> wrote:

> That did the trick. Thanks Daniel.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/3076#issuecomment-91361183>.
>



-- 
Jonathan Aquilina
