### ISSUE TITLE
Change Background Color of Selected Folder in Windows Client

### ISSUE THREAD

**Issue by madmoneymike5** [owncloud/client#3081]
I'm wondering if it could be made possible that the background color of the selected folder is not dark blue? At present, the black font and dark blue background make it nearly impossible to read. Perhaps a light gray instead? The only fix currently is to click on a button in the client.

**Comment by danimo** [comment]
Screenshot, please.

**Comment by madmoneymike5** [comment]
It has something to do with the fact that I disable the "Aero" theme with transparency.

![client](https://cloud.githubusercontent.com/assets/11854243/7047823/a7fecf32-ddd4-11e4-8994-c04e7342b469.jpg)

**Comment by ogoffart** [comment]
Related to #2654 perhaps

**Comment by madmoneymike5** [comment]
...looks like the Windows client doesn't play well with themes other than Aero.

**Comment by nekoal** [comment]
I have simular view in Windows 7 with classic color scheme. Compare with Windows XP it seems for this used system brush for any selected item. I check it by selecting green color. I don't think it's need changes. More likely text color for selected folder needs set to same brush as in selected tabs text color (white or light-gray for active selected and black for not selected and inactive selected). I think it can resolve #2654 too.
![oc_green_set](https://cloud.githubusercontent.com/assets/10899904/7100769/01c512da-e067-11e4-8a2b-32562b897c77.jpg)
![oc_green](https://cloud.githubusercontent.com/assets/10899904/7100761/8275bb2e-e066-11e4-9f14-230a64c4454e.JPG)

**Comment by guruz** [comment]
Do you guys want to check out 2.0? We have a nightly build here that has the situation improved

http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.5404-nightly20150817-setup.exe

**Comment by ckamm** [comment]
I have checked this on Windows 7 with a high contrast theme. The 'Selected Items' color does not apply to the folder list.
