### ISSUE TITLE
Handle permanent redirects

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#3082]
On the call to status.php, there can happen a permanent redirect reply. The client needs to pick the url coming with that up, store it in the config and use it.

This should be a branding option, see also owncloud/enterprise#499

**Comment by ckamm** [comment]
I've tested this and looked at the code. It's already fully implemented.

AbstractNetworkJob has the followRedirects options which is enabled for CheckServerJob. It's instanceFound signal is then emitted with the redirected URL and that is what gets stored in the config file.

**Comment by dragotin** [comment]
The current implementation only works with redirects that return from the call to status.php. That is not sufficient, it needs to pick the redirect url up on the first authenticated call to the server.

**Comment by ckamm** [comment]
Works for me now!

**Comment by Dianafg76** [comment]
I have tested this on a mac and windows clients, a full regression test and everything is working just fine.
