### ISSUE TITLE
[Windows] recipe for target 'all' failed error while compiling.

### ISSUE THREAD

**Issue by annanttf** [owncloud/client#3091]
Hi, 
I get the following error while cross-compiling for windows (Client Version 1.8)

[  2%] Built target cstdlib
[ 10%] Built target ocsync
[ 11%] Automatic moc for target owncloudsync
[ 11%] Built target owncloudsync_automoc
[ 36%] Built target owncloudsync
[ 37%] Automatic moc for target updater
[ 37%] Built target updater_automoc
[ 39%] Built target updater
[ 40%] Automatic moc for target owncloud
[ 40%] Built target owncloud_automoc
Linking CXX executable ../../bin/owncloud
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::WritePasswordJob::setKey(QString const&)'
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::Job::error() const'
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::ReadPasswordJob::ReadPasswordJob(QString const&, QObject*)'
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::DeletePasswordJob::DeletePasswordJob(QString const&, QObject*)'
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::ReadPasswordJob::setKey(QString const&)'
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::Job::errorString() const'
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::ReadPasswordJob::textData() const'
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::Job::setInsecureFallback(bool)'
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::Job::settings() const'
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::DeletePasswordJob::setKey(QString const&)'
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::WritePasswordJob::staticMetaObject'
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::Job::start()'
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::WritePasswordJob::setTextData(QString const&)'
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::WritePasswordJob::WritePasswordJob(QString const&, QObject*)'
../libsync/libowncloudsync.so.1.8.0: undefined reference to `QKeychain::Job::setSettings(QSettings*)'
collect2: error: ld returned 1 exit status
src/gui/CMakeFiles/owncloud.dir/build.make:1647: recipe for target 'bin/owncloud' failed
make[2]: *** [bin/owncloud] Error 1
CMakeFiles/Makefile2:327: recipe for target 'src/gui/CMakeFiles/owncloud.dir/all' failed
make[1]: *** [src/gui/CMakeFiles/owncloud.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2

I don't know what went wrong.

**Comment by guruz** [comment]
Did you also compile QtKeyChain?

In general for compile help, it is better to join irc.freenode.net #owncloud-client-dev ..

**Comment by annanttf** [comment]
Yes, I did compiled QTKeyChain. But no luck.

**Comment by guruz** [comment]
Please try with 2.0 (current master branch) and a recent/matching QtKeychain.

if you need compile help please come on IRC (see above).. or poke @kwillems :)
