### ISSUE TITLE
Request - dont sync windows network drives by option in client

### ISSUE THREAD

**Issue by Froster** [owncloud/client#3093]
There should be an Option in the Client so that the user can decide to not sync shared drives from apps like "Windows Network Drive" by default

**Comment by ogoffart** [comment]
Could you please elaborate?  I am not familiar with the concept of "Windows Network Drive". I did not know you could find such things down in a hierarchy.

**Comment by Froster** [comment]
In ES version you can mount "Windows Network Drives" in administration or user menu.

https://doc.owncloud.org/server/8.0/admin_manual/enterprise_external_storage/windows-network-drive_configuration.html

As i tested, the client will sync this folders if they are not in exclusion list but i would be more practicable if this type of shares could by excluded by an option set in the client? also if we use software management systems to install it.

**Comment by Lbryson-lifesize** [comment]
I'd say, just change the default client behavior to not automatically sync all new content (like network drives) that are shared with the user.  The current behavior causes a lot of pain.

**Comment by guruz** [comment]
This is done in 2.3.1
