### ISSUE TITLE
Mac OS: "Fortsetzen" Button without function

### ISSUE THREAD

**Issue by martinbaeumler** [owncloud/client#3099]
Using the german version!!! After losing the connection hitting "Anhalten" (stop) pauses the action. Then the Anhalten Button changes to "Fortsetzen" (continue). This button is without function. Hitting causes no action.

**Comment by danimo** [comment]
Which version, which OS?

**Comment by danimo** [comment]
Please press "F12" (might need fn key on a Mac), which will open a log window. Move it aside and paste the output of what happens if you press "Resume" (Fortsetzen).

**Comment by martinbaeumler** [comment]
1.8.0 (build 2139) 

F12 + FN (or any other combination F12, CMD + F12, ...) don't open any log window. Other way to do that?

**Comment by danimo** [comment]
Are you in the settings dialog?

**Comment by martinbaeumler** [comment]
Yes.

2015-04-11 13:10 GMT+02:00 Daniel Molkentin <notifications@github.com>:

**Comment by danimo** [comment]
Alternatively, you can open the log window from the start:

```
/Applications/owncloud.app/Contents/MacOS/owncloud --logwindow
```

**Comment by guruz** [comment]
Please try with 2.0 nightl
