### ISSUE TITLE
[GNOME 3.14] Icon disappear when closing the notification message

### ISSUE THREAD

**Issue by MightyCreak** [owncloud/client#3100]
### Expected behaviour
The icon should stay in the notification bar, without any "new message" icon. Like this:

![1 no notification](https://cloud.githubusercontent.com/assets/6382548/7102658/55dd897c-e055-11e4-9d12-923ab447d4c6.png)

### Actual behaviour
The icon disappear (ownCloud still syncs apparently though).

### Steps to reproduce
Reproducibility: 100%

1. Wait for a notification on your desktop (add a file through the web client)

  ![2 notification icon](https://cloud.githubusercontent.com/assets/6382548/7102659/681ac596-e055-11e4-8b4e-2ae59f5a640a.png)

2. Open the notification message and close it using the close button on the top-right

  ![3 notification message](https://cloud.githubusercontent.com/assets/6382548/7102660/737fe7ea-e055-11e4-9917-f30f48fb75a5.png)

3. The icon disappear

  ![4 no icon](https://cloud.githubusercontent.com/assets/6382548/7102675/c040016e-e055-11e4-87bc-76c99574c14e.png)

### Server configuration
Operating system: Linux (Debian 7.5)

Web server: Nginx 1.2

Database: MySQL 5.5

PHP version: PHP 5.4

ownCloud version: 8.0 (stable)

Storage backend: MySQL

### Client configuration
Client version: 1.8

Operating system: Linux (Manjaro, GNOME 3.14)

OS language: French

Installation path of client: /usr/bin/owncloud

### Logs

1. Output of `owncloud --logwindow`

```
Sys Info size:  107
int main(int, char**) Already running, exiting...
```

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by MightyCreak** [comment]
I've just seen that it seems to be a common bug for all the applications in the notification bar. `pamac`, the icon right next to ownCloud in the screenshots, behave in the same way.

But these applications are "unofficial" GNOME apps, so it can still be an implementation problem (for instance, maybe the applications forgot to configure something correctly or to catch some message events, ending in hiding the icon by default).

**Comment by ogoffart** [comment]
What version of Qt is it?

**Comment by MightyCreak** [comment]
Seems to be the 4.8.6:

    $ yaourt -Qi qt4
    Nom                   : qt4
    Version               : 4.8.6-4

**Comment by guruz** [comment]
Does the problem go away with a mirall compiled with Qt 5.4.2?

See also #2558

**Comment by MightyCreak** [comment]
I'm using GNOME 3.16 now, so the notification system has changed a lot with this version, but I don't see any problem with the GNOME environment now.

**Comment by guruz** [comment]
Thanks, closing..
