### ISSUE TITLE
Client can't sync large files - Internal Server Error

### ISSUE THREAD

**Issue by enoch85** [owncloud/client#3101]
#### Expected behaviour

Big files should be able to upload without getting Internal Server Errror.

#### Actual behavior

I have to upload them to WebUI to get it working. The Client stops syncing the file due to some chunking error. Please see log for more info.

#### Steps to reproduce

1. Upload file to a folder that sync with ownCloud.
2. See what happens

#### PHP.ini

https://www.en0ch.se/owncloud_/increase-max-file-size/

#### Logs

**Sync log**
```
2015-04-11 22:46Wordpress VMDK/Wordpress_www.en0ch.se.rar                       ownCloud       Objektet kunde inte synkas på grund av tidigare fel: Error downloading https://en0ch.se/remote.php/webdav/Wordpress VMDK/Wordpress_www.en0ch.se.rar-chunking-1690968986-177-100 - server replied: Internal Server Error          
2015-04-11 22:37DirektUppladdning/Bilder övrigt/make money.png                  ownCloud       Uppladdad      29 KiB    
2015-04-11 21:03Wordpress VMDK/Wordpress_www.en0ch.se.rar                       ownCloud       Error downloading https://en0ch.se/remote.php/webdav/Wordpress VMDK/Wordpress_www.en0ch.se.rar-chunking-1690968986-177-176 - server replied: Internal Server Error884 MiB   
2015-04-11 20:55Wordpress VMDK/Wordpress_www.en0ch.se                           ownCloud       Raderad                  
2015-04-11 20:54Wordpress VMDK/Wordpress_www.en0ch.se/Wordpress_www.en0ch.se-flat.vmdkownCloud       Den lokala filen togs bort under synkronisering.20 GiB    
2015-04-11 20:45Wordpress VMDK/Wordpress_www.en0ch.se/Wordpress_www.en0ch.se.vmxfownCloud       Uppladdad      277 B     
2015-04-11 20:45Wordpress 
``` 
**owncloud.log**
```
Error	PHP	Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) at /var/www/owncloud/lib/private/files/storage/local.php#161	2015-04-11T20:38:47+00:00
Error	PHP	Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) at /var/www/owncloud/lib/private/files/storage/local.php#161
Error	PHP	Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) at /var/www/owncloud/lib/private/files/storage/local.php#161	2015-04-11T19:03:08+00:00
Error	PHP	Undefined index: /var/www/owncloud/data/[user]/files/Ny mapp at /var/www/owncloud/apps/files_locking/lib/lockingwrapper.php#140	2015-04-11T18:41:19+00:00
```
**error.log**
```
[Sat Apr 11 19:24:19.010517 2015] [mpm_prefork:notice] [pid 1538] AH00163: Apache/2.4.7 (Ubuntu) PHP/5.5.9-1ubuntu4.7 OpenSSL/1.0.1f configured -- resuming normal operations
[Sat Apr 11 19:24:19.010557 2015] [core:notice] [pid 1538] AH00094: Command line: '/usr/sbin/apache2'
[Sat Apr 11 21:03:08.552415 2015] [:error] [pid 2717] [client 192.168.1.1:58472] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) in /var/www/owncloud/lib/private/files/storage/local.php on line 161
[Sat Apr 11 21:04:22.706001 2015] [:error] [pid 2713] [client 192.168.1.1:58776] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) in /var/www/owncloud/lib/private/files/storage/local.php on line 161
[Sat Apr 11 22:38:47.880196 2015] [:error] [pid 3065] [client 192.168.1.1:59223] PHP Fatal error:  Allowed memory size of 536870912 bytes exhausted (tried to allocate 5251072 bytes) in /var/www/owncloud/lib/private/files/storage/local.php on line 161
[Sat Apr 11 23:26:37.329515 2015] [access_compat:error] [pid 3964] [client 127.0.0.1:52203] AH01797: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt
```

### Server configuration on both servers

Ubuntu Server 14.04

**Database:**
Server version: 5.5.41-0ubuntu0.14.04.1 - (Ubuntu)
**PHP version:**
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

**ownCloud version:** (see ownCloud admin page)
8.0.2
**Are you using encryption: yes/no**
No

### Client configuration

**Browser:**
Chrome 
**Operating system:**
Windows 8.1
**Sync Client**
1.8 stable
**Mobile app*
Android 1.7.1

**Comment by danimo** [comment]
We need the server logs (both `owncloud.log` and apache's `error.log`)

**Comment by enoch85** [comment]
@danimo Update the issue

**Comment by danimo** [comment]
"tried to allocate 5251072 bytes" is pretty clear. PHP is not able/allowed to create a 5 MB buffer. the webinterface might use a different chunk size and therefore work. Solution is to check your setup for limits (usual suspect: `memory_limit`). ownCloud does its best to override it via `.htaccess`, but that will not always work, esp. on non-apache.

**Comment by enoch85** [comment]
@danimo 5MB you say?

This is my `php.ini` setting
```
; Maximum amount of memory a script may consume (128MB)
; http://php.net/memory-limit
memory_limit = 512M
```

**Comment by danimo** [comment]
That may be true, but the error says something else. Maybe the webserver plainly runs out of memory? Either way, it is not a client issue.

**Comment by enoch85** [comment]
Just for the record, I have 16GB and 14GB is free. I open this issue in core instead.

**Comment by danimo** [comment]
Please first establish with a simple PHP script that you can allocate 5MB.

**Comment by enoch85** [comment]
@danimo Please provide me with one and I can try. Yet, I didn't run in to these issues before, and I haven't changed any settings.

**Comment by mcronce** [comment]
PHP Allowed memory size of **536870912** bytes exhausted (tried to allocate 5251072 bytes) at /var/www/owncloud/lib/private/files/storage/local.php#161 2015-04-11T20:38:47+00:00

Emphasis mine.

**Comment by bcutter** [comment]
I recently see a lot of those errors in owncloud.log:

```
Allowed memory size of 536870912 bytes exhausted (tried to allocate 3215851560 bytes) at /var/www/owncloud/lib/autoloader.php#183
```
I don´t know when or why it starts, especially file sync works fine. But everything else on the system (Raspberry Pi 2) stops working like Webmin or SSH.

Why does Owncloud want to allocate about 3 GB (!!!) of memory (where only 1 GB physically exists, no swap partition) for a 524 KB file??? I did NOT try to sync a large file.

**Comment by dragotin** [comment]
@DeepDiver1975 see above...
