### ISSUE TITLE
right click on a folder and share with owncloud

### ISSUE THREAD

**Issue by gillesdeloustal** [owncloud/client#3104]
I am Ubuntu 14.04 64 bits UEFI,with owncloud 8.02 on a mutual system OVH perso2014, oc-client 1.8.0 and owncloud-client-nautilus 1.8.0-2
My OVH server offers php 5.4 mysql 5.1, I have 100Go available
On this server, I also have a SPIP application, a wordpress site. My database hold both tables SPIP, wordpress and owncloud
I have an external storage dropbox.
I went through the forum https://forum.owncloud.org/viewtopic.php?f=14&t=27741&p=84861#p84861

When I right-click on a folder, it does'nt show "cloud storage - share" as said here : viewtopic.php?f=14&t=21996

**Comment by danimo** [comment]
The entry is called `Share with ownCloud...`, not 'cloud storage - share'. That must be a different plugin.

**Comment by gillesdeloustal** [comment]
It does'nt show share with owncloud... either

**Comment by danimo** [comment]
Did you restart nautilus (`nautilus -q`)? is the owncloud client running?

**Comment by gillesdeloustal** [comment]
I did'nt restart nautilus.
I restarted the machine.
owncloud was not running. I started it, but still does'nt show  share with owncloud..

**Comment by danimo** [comment]
Are you trying this from within a folder that syncs with owncloud?

**Comment by gillesdeloustal** [comment]
No the folder is in "documents" folder. I have no documents folder on the server.
Anyway, it's the same with any folder

**Comment by danimo** [comment]
That's what I am saying. It will only work inside synchronized folders. Did you verify that it also doesn't work there?

**Comment by gillesdeloustal** [comment]
That's the point : 
Files and folders synchronized have been created on the server. 
On my desktop, they are only located under owncloud folder created at installation time.
What I want to do is to synchronize a folder located on my desktop.

**Comment by danimo** [comment]
That functionality is not available from the context menu. You can only either sync _everything_ into a single folder (default), or define sync relations manually, see https://doc.owncloud.org/desktop/1.8/navigating.html#using-the-account-settings-window. You have to remove the default sync folder and then click "Add folder".

**Comment by gillesdeloustal** [comment]
Defining sync relations manually, shall I be able to sync several folders located  on my desktop ?

**Comment by danimo** [comment]
Yes.

**Comment by gillesdeloustal** [comment]
How can I, additionaly, sync folders located on the server ?

**Comment by danimo** [comment]
You always need to specify the the names of both ends. if one end already exists on the server, it will be synced down.

**Comment by gillesdeloustal** [comment]
OK I sync'ed 2 local folders with server, but now, I don't see how to sync a server's folder with the desktop.
