### ISSUE TITLE
[Windows] [HiDPi] Overlay-Icons of Desktop Client / Gray Border

### ISSUE THREAD

**Issue by danielkraffner** [owncloud/client#3105]
The "Green-Tick-Icon" of the Desktop-Client seems to have a grayish border around it. (1.8.0 build 4893)

See Screenshot:

![image](https://cloud.githubusercontent.com/assets/5311744/7107591/e2458b3e-e169-11e4-9548-488fec354879.png)

Nothing Critical, just grinds my gears everytime I see it :)

Maybe it's worth mentioning that i'm using 4k Resolution with a 200% UI-Scale. Maybe the border just appears due to upscaling of the icon.

Edit: Yes seems to be a 4k-Issue. On my Notebook the Icon looks way larger and no border is visible.

**Comment by danielkraffner** [comment]
Maybe it's worth mentioning that i'm using 4k Resolution with a 200% UI-Scale. Maybe the border just appears due to upscaling of the icon.

**Comment by guruz** [comment]
This is using which Windows version? :)

**Comment by danielkraffner** [comment]
Windows 8.1 64bit

**Comment by danimo** [comment]
Probably related to us not providing a hi-res icon (128px), because the png2ico tool cannot deal with that.

**Comment by Dianafg76** [comment]
I tested this issue and is working ok
Desktop v 2.1.1 beta1 (build 5780)
Server v 8.2.2
