### ISSUE TITLE
Windows Client continuously discovering

### ISSUE THREAD

**Issue by roymcclure** [owncloud/client#3106]
I'm using the windows client version 1.8.0 (build 4893). Server is 8.0.2 stable running on lubuntu. After it's walked through the whole discovery process, it will succesfully sync all files (except one*) and then start again a few seconds later - even when I have set remotePollInterval=1000000 in the [general] tab of c:\users\roymcclure\appdata\local\owncloud\owncloud.cfg - thus consuming a big chunk of the cpu time.

*  That file it always fails to sync throws an error message in the activity tab of the client: "Not able to upload this file because it is read-only on the server, restoring: Restoration failed: Error downloading .../not/especially/long/path/to/file/file.xml - server replied: Requested Range not satisfiable." I have checked the permissions for that file in the server and they are just the same as all the others that are being synced correctly, read-write for the owner (www-data), read for the rest.

**Comment by guruz** [comment]
@dragotin @ogoffart Shouldn't this go into the blacklist after 3 failed attempts?
Maybe recovery jobs don't use the blacklist?

**Comment by dragotin** [comment]
The  problem here is that the file tries to recover with a Range that does not work (IMO). @ogoffart can you have a look please?

**Comment by ogoffart** [comment]
Can you please send the client log?  (you can use `--logfile` or `--logwindow` option to get them)

**Comment by roymcclure** [comment]
The log file generated is massive, hundreds of megabytes. Can you tell me what specific part/s do you need or what can i exclude from the log?

**Comment by ogoffart** [comment]
You could filter all the lines that contains the name of the file in question.

I am interested in knowing what are the permission that the server gives us. (This is not the permission on the file as stored on the server, but the permisison which you have an an owncloud user to edit that file) Is it a shared file in a read only share?

Then i would like to understand why we always have an error and is it always the same error?

**Comment by roymcclure** [comment]
Ok there you go: https://gist.githubusercontent.com/roymcclure/2ebb0e6969d4d6395cba/raw/53ee23540330b12bf7891397594a9aa1836b368d/owncloud.winclient.error.log

**Comment by ogoffart** [comment]
Thanks a lot for the log, this is very usefull.

```
04-15 13:55:12:810 0x5b6ee38 OCC::SyncEngine::checkForPermission: checkForPermission: RESTORING "Projects/GamesSource/LeSwagAmongUs/src/nbproject/private/private.xml"
```

So the log don't tell us the exact permissions, but the client is thinking the file is read only and will attempt a resolution of the file. The way it restores the file is by sumulating a conflict and re-downloading the file from the server

```
04-15 13:55:38:473 0x5b6ee38 OCC::FileSystem::rename: FAIL: renaming file "C:/Users/Development/ownCloud/Projects/GamesSource/LeSwagAmongUs/src/nbproject/private/private.xml" to "C:/Users/Development/ownCloud/Projects/GamesSource/LeSwagAmongUs/src/nbproject/private/private_conflict-20150408-215213.xml" failed:  "Destination file exists"
```

After it downloaded the file, it tries to rename your modified version. Unfortunately this fails because apparently that file existed already.

The reason may be that we use the mtime from the server instead of the local mtime (because it is a restoration)

But then it gets worse:
For the size, we also have the size from the client and not the one from the server (because restoration) and then we try to use Range becasue we don't know that it is finished.

Which results in 

```
04-15 13:57:42:593 0x5b6ee38 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 299 "Error downloading http://10.42.0.1/owncloud/remote.php/webdav/Projects/GamesSource/LeSwagAmongUs/src/nbproject/private/private.xml - server replied: Requested Range Not Satisfiable"
```

And from that point, we will try to sync again. But this problem will repeat all the time.


So i'll try to find a way to solve this problem.

**Comment by roymcclure** [comment]
Glad I could help. The owncloud project is amazing so keep up the good work guys.

**Comment by guruz** [comment]
@roymcclure Does this still happen with rc2?
https://owncloud.org/install/#testing

**Comment by roymcclure** [comment]
I'm afraid it's still doing it. I will post the log soon.

**Comment by guruz** [comment]
@roymcclure ok, thanks

**Comment by ogoffart** [comment]
Do you have the logs?  Which build did you try?

**Comment by roymcclure** [comment]
Well this is embarrassing. It certainly seems to be working well now. For some reason it did several consecutive discoveries - not sure how many, but some - but it isn't doing it anymore. I can still post a log if you want but the behaviour seems to be correct at this point.

**Comment by Dianafg76** [comment]
I tested in Desktop v 1.8.2 (build 5111), it is working well, so I closed
