### ISSUE TITLE
Write .owncloudsync.log on the go, not at end of sync

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3108]
I classify this as a bug since a crash or client exit will not write the log entries.

**Comment by dragotin** [comment]
I was not doing it *on the run* to avoid performance drop by constant file I/O

**Comment by guruz** [comment]
@ckamm Also had the idea to log twice, once during discovery and once when propagating. (with different tags to distinguish).
Although this might mean huge log files in case of syncs that break/pause and restart.

**Comment by guruz** [comment]
We'll need to change the format a bit to show the duration only at the end on a new line
```
#=#=#=# Syncrun started 2015-11-25T12:21:46 until 2015-11-25T12:21:51 (5187 msec)
```
