### ISSUE TITLE
Synchronisation ending with Connection closed

### ISSUE THREAD

**Issue by aaujon** [owncloud/client#3109]
I have around 3000 files to sync with the 1.8 linux client.
After the discory part, sync fails after downloading some files (between 2 and 20) with Connexion closed error. After 5 minutes, the same scenario happens again.

Owncloud server 8.0.2
Owncloud linux client 1.8

I have more log if needed.

Client log ::
04-10 15:24:30:400 0x150e640 #### Propagation start #################################################### >> 
04-10 15:24:30:498 0x150e640 Folder in overallStatus Message:  OCC::Folder(0x17927a0)  with name  "Documents" 
04-10 15:24:30:499 0x150e640 Sync state changed for folder  "Documents" :  "Sync Running" 
04-10 15:24:30:525 0x150e640 virtual void OCC::PropagateDownloadFileQNAM::start() "User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Mémoire.odt" 0 
04-10 15:24:30:526 0x150e640 "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Mémoire.odt" "User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/.Mémoire.odt.~760d1f02" "54679f558b171" 0 
04-10 15:24:30:526 0x150e640 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction 
04-10 15:24:30:527 0x150e640 Retry with range  "bytes=3410188-" 
04-10 15:24:30:528 0x150e640 virtual void OCC::GETFileJob::start() OCC::BandwidthManager(0x28d4178) false false 
04-10 15:24:30:528 0x150e640 void OCC::BandwidthManager::registerDownloadJob(OCC::GETFileJob*) OCC::GETFileJob(0x2dc3850) 
04-10 15:24:30:529 0x150e640 !!! OCC::GETFileJob created for  QUrl( "https://OWNCLOUD_SERVEUR" )  querying "/User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Mémoire.odt" 
04-10 15:24:30:600 0x150e640 virtual void OCC::PropagateDownloadFileQNAM::start() "User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Mémoire.pdf" 1 
04-10 15:24:30:601 0x150e640 "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Mémoire.pdf" "User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/.Mémoire.pdf.~283769fe" "54679f6797a9c" 0 
04-10 15:24:30:602 0x150e640 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction 
04-10 15:24:30:602 0x150e640 Retry with range  "bytes=1010790-" 
04-10 15:24:30:603 0x150e640 virtual void OCC::GETFileJob::start() OCC::BandwidthManager(0x28d4178) false false 
04-10 15:24:30:604 0x150e640 void OCC::BandwidthManager::registerDownloadJob(OCC::GETFileJob*) OCC::GETFileJob(0x2baac60) 
04-10 15:24:30:604 0x150e640 !!! OCC::GETFileJob created for  QUrl( "https://OWNCLOUD_SERVEUR" )  querying "/User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Mémoire.pdf" 
04-10 15:24:30:622 0x150e640 virtual void OCC::PropagateDownloadFileQNAM::start() "User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Rapport de stage.odt" 2 
04-10 15:24:30:624 0x150e640 "INSERT OR REPLACE INTO downloadinfo (path, tmpfile, etag, errorcount) VALUES ( ?1 , ?2, ?3, ?4 )" "User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Rapport de stage.odt" "User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/.Rapport de stage.odt.~6440f441" "54679f6e8c739" 0 
04-10 15:24:30:625 0x150e640 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "download file start" and starting new transaction 
04-10 15:24:30:626 0x150e640 virtual void OCC::GETFileJob::start() OCC::BandwidthManager(0x28d4178) false false 
04-10 15:24:30:627 0x150e640 void OCC::BandwidthManager::registerDownloadJob(OCC::GETFileJob*) OCC::GETFileJob(0x3008b00) 
04-10 15:24:30:628 0x150e640 !!! OCC::GETFileJob created for  QUrl( "https://OWNCLOUD_SERVEUR" )  querying "/User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Rapport de stage.odt" 
04-10 15:24:30:630 0x150e640 * Discarded as is hidden! "/home/arnaud/Documents/User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/.Rapport de stage.odt.~6440f441" 
04-10 15:24:31:027 0x150e640 void OCC::GETFileJob::slotMetaDataChanged() Wrong content-range:  ""  while expecting start was 3410188 
04-10 15:24:31:029 0x150e640 * Discarded as is hidden! "/home/arnaud/Documents/User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/.MÃ©moire.odt.~760d1f02" 
04-10 15:24:31:161 0x150e640 void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag 
04-10 15:24:32:078 0x150e640 void OCC::GETFileJob::slotMetaDataChanged() Wrong content-range:  ""  while expecting start was 1010790 
04-10 15:24:32:080 0x150e640 * Discarded as is hidden! "/home/arnaud/Documents/User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/.MÃ©moire.pdf.~283769fe" 
04-10 15:24:35:519 0x150e640 void OCC::AbstractNetworkJob::slotFinished() 2 "Connexion fermée" 
04-10 15:24:35:520 0x150e640 void OCC::PropagateDownloadFileQNAM::slotGetFinished()  QUrl( "https://OWNCLOUD_SERVEUR/remote.php/webdav/User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Rapport de stage.odt" )  FINISHED WITH STATUS 2 "Connexion fermée" 
04-10 15:24:35:521 0x150e640 void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem&) "User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Rapport de stage.odt" INSTRUCTION_NEW 1 "Connexion fermée" 
04-10 15:24:35:524 0x150e640 void OCC::AbstractNetworkJob::slotFinished() 5 "Opération annulée" 
04-10 15:24:35:524 0x150e640 void OCC::PropagateDownloadFileQNAM::slotGetFinished()  QUrl( "https://OWNCLOUD_SERVEUR/remote.php/webdav/User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Mémoire.odt" )  FINISHED WITH STATUS 5 "Opération annulée" 
04-10 15:24:35:525 0x150e640 void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem&) "User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Mémoire.odt" INSTRUCTION_NEW 1 "Opération annulée" 
04-10 15:24:35:526 0x150e640 void OCC::AbstractNetworkJob::slotFinished() 5 "Opération annulée" 
04-10 15:24:35:527 0x150e640 void OCC::PropagateDownloadFileQNAM::slotGetFinished()  QUrl( "https://OWNCLOUD_SERVEUR/remote.php/webdav/User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Mémoire.pdf" )  FINISHED WITH STATUS 5 "Opération annulée" 
04-10 15:24:35:527 0x150e640 void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem&) "User/Backup_ordi_user/Documents/MASTER 2 IPCI/Mémoire/Mémoire.pdf" INSTRUCTION_NEW 1 "Opération annulée" 
04-10 15:24:35:538 0x150e640 void OCC::SyncJournalDb::walCheckpoint() took 0 msec 
04-10 15:24:35:539 0x150e640 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "All Finished."  
04-10 15:24:35:543 0x150e640 CSync run took  919149 
04-10 15:24:35:545 0x150e640 virtual OCC::BandwidthManager::~BandwidthManager() 
04-10 15:24:35:554 0x150e640 -> SyncEngine finished with ERROR, warn count is 1

**Comment by guruz** [comment]
> 04-10 15:24:31:027 0x150e640 void OCC::GETFileJob::slotMetaDataChanged() Wrong content-range: "" while expecting start was 3410188 

Your server looks broken.

**Comment by nekoal** [comment]
May it be related é character? Filename .MÃ©moire.odt.~760d1f02 look as wrong. Is all documents in folder which contain this character.

**Comment by aaujon** [comment]
I just remembered that after upgrading owncloud to version 8 and my php version to 5.5.23. I had this message in owncloud admin :  "PHP charset is not set to UTF-8. This can cause major issues with non-ASCII characters in file names. We highly recommend to change the value of 'default_charset' php.ini to 'UTF-8'. "

**Comment by aaujon** [comment]
@nekoal in the webapp, filename are displayed correctly (Mémoire.odt), and there is some other files in the same directory without any accents that haven't been synchronized. (maybe sync of the directory stopped after failing to download this file?)

**Comment by nekoal** [comment]
I wrote filename of temporary file, it's not file you see in web interface. Of course, it formed from file you see in web interface but it's different file. If name of temporary file formed wrong it may be sign of wrong coded name of original file (1) or wrong conversion from utf-8 charset to charset of your filesystem (2).
(1)My guess was this is partly simular to #3033 where issue was in handling "ö" character. Of course you use different OS and filesystem so effect different. Such characters may be coded in different ways (character e and character accent or single character e accent) which look identically but binary different. If you set cursor in rename field after é and press Backspace is character remove completely or turn to e?
 (2) "Ã©" has ascii hex codes C3 A9. It looks for me as utf-8 character bin-utf8(1100 0011 1010 1001)=bin-ascii(1110 1001)=ascii hex E9 and char with code E9 is... right, é. So filename encoded in utf-8 charset was not converted to charset of your filesystem. At least it's bug in logging. Or on second using this filename server may get double uft-8 encoded filename.

**Comment by aaujon** [comment]
@nekoal Thinks for your analysis, I will test and answer to your questions in a couple days

**Comment by aaujon** [comment]
I just had a look to the filename, it looks like correct UTF8 (and the file has now been synced..) So I guess the issue happened when my server changed it's default php charset.
I close the issue and I will reopened it if the same issue happens again.
Thanks !
