### ISSUE TITLE
"Sharing from desktop" not available after Update from 1.7 to 1.8

### ISSUE THREAD

**Issue by Froster** [owncloud/client#3110]
Hello,

"Sharing from Desktop" seems only available on fresh new installations. 

I tested it with 1.7 to 1.8 and i never have this Option in file - dialogs but if i install 1.8 fresh on a System it appears.

Kindly
Christian

**Comment by guruz** [comment]
Which OS?

**Comment by Froster** [comment]
@guruz Hi,

it's on WIndows 8.1.

**Comment by BuZZ-dEE** [comment]
+1 for Linux (AntergOS / Arch / GNOME 3.16)

**Comment by guruz** [comment]
@Froster Could I ask you to test this nightly build of 1.8.3 ?
http://download.owncloud.com/desktop/daily/ownCloud-1.8.3.5188-nightly20150612-setup.exe

**Comment by guruz** [comment]
(Note to select "Uninstall previous version", also a reboot might be necessary because of the Explorer DLL)
