### ISSUE TITLE
Folder size not sorted by size

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/client#3112]
Reported by @geek65535 in https://github.com/owncloud/core/issues/15618

> The desktop client has an option "choose what to sync," which presents the user with a tree of folders and their sizes. The folders can be sorted by size by clicking the column header. But the client sorts by ASCII value, rather than by size. For instance, it will sort 3.1GiB before 37KiB.
> 
> See attached screenshot for an example.
> ![screenshot_2015-04-14_10-27-43](https://cloud.githubusercontent.com/assets/1102057/7140612/d9451fb2-e291-11e4-8474-67800e75ad8c.png)

**Comment by danimo** [comment]
@ogoffart Please verify & close

**Comment by ogoffart** [comment]
Works for me now.

**Comment by geek65535** [comment]
Thanks so much! It's impressive to see an issue (even a minor on like this) fixed in less than 24 hours.
Is there a PPA that provides dailies so I can try the fix?

**Comment by PeterPablo** [comment]
@geek65535, have a look [here](http://download.owncloud.com/desktop/daily/).

**Comment by danimo** [comment]
@geek65535 For Linux, check out the [testing repo](https://build.opensuse.org/project/show/isv:ownCloud:community:testing/), which contains the fix already (1.8.1 beta1). If you want to stay up-to-date and like to live dangerously, there is also the [nightly build](https://build.opensuse.org/project/show/isv:ownCloud:community:testing/) repo.

**Comment by geek65535** [comment]
@PeterPablo & @danimo Thanks again, that's just what I was looking/hoping for.

Paul
