### ISSUE TITLE
[OS X] Add release step that verifies package signature and aborts on error

### ISSUE THREAD

**Issue by danimo** [owncloud/client#3114]
In the build process, we should verify that a signature was successful. As it stands, it seems that it can fail sometimes, and even slips testing with gatekeeper enabled (need to find out why as well).

**Comment by jturcotte** [comment]
Should be fixed now, I added the -e switch to both the main bash script, and when calling sign_app.sh. I also added an extra `codesign --verify` since `codesign -d` only displays without verifying.

**Comment by abraithwaite** [comment]
Thanks! :beers:
