### ISSUE TITLE
about 2000 files are deleted

### ISSUE THREAD

**Issue by JensHH** [owncloud/client#3116]
What I can see is that in my Folder (Windows 7) about 2000 Files are missing. This Folder  normaly has 5.000 files. In the logfile I see something like 
14.04.2015 05:29 file_xy downloaded 
There are nearly 2000 entries like this.  The last entry is something like
15.04.2015 15:13 file_ab operation aborted
Connection closed
On the Server I can find all my files. My question is what caused this trouble.
The ownCloud client is working for several months without problems
What is the best strategy to bring my files back?

**Comment by guruz** [comment]
Is it downloading the files again from the server?

Do you see any errors in the server's ```owncloud.log```? Do you see in your server's ```access.log``` if any PROPFIND requests returned HTTP 500 instead of HTTP 207?

**Comment by guruz** [comment]
Or in best case, could you mail us the full log file?

**Comment by JensHH** [comment]
I can send you both if you tell me how I can send it to you and where I find the ownCloud log. The access.log has thousands of PROPFIND 207 and 2  lines with 500. At 04:52:34 it starts with a lot of GET 200

**Comment by guruz** [comment]
The client log file I meant :-) you can send it to guruz@owncloud.com and klaas@owncloud.com and olivier@owncloud.com

The 2 lines with HTTP 500 are they for the directory you are missing files in?

The missing files were all directly in the same one folder? But other files in that folder are not missing?

So are the files automatically loaded back down or not?

The server's owncloud.log is in the ```data``` directory on the server.

**Comment by JensHH** [comment]
Do you have all the information you need and can I restart my computer?

**Comment by RealRancor** [comment]
Mhhh, couldn't this be also related to https://github.com/owncloud/client/issues/3102 ?

**Comment by JensHH** [comment]
yes

**Comment by guruz** [comment]
As per comment https://github.com/owncloud/client/issues/3102#issuecomment-93719660 :
@JensHH we'd need to know why it aborted the operation. 
This might or might not be related to how the files disappeared in the first place.
The real client log can be activated by this: https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly

(is there something in server owncloud.log?)

> What is the best strategy to bring my files back?

In this case if you quit the client, delete the ```.csync_journal.db``` and then re-start it, it should connect to the server and merge the contents of the local and the remote directories.

**Comment by guruz** [comment]
@JensHH Do you have the missing files still in the oC webinterface on the server? Or just in the file system?

**Comment by JensHH** [comment]
just sent you a new file

**Comment by JensHH** [comment]
The files are still in the oC webinterface

**Comment by guruz** [comment]
The 1.8.1rc1 should bring the files back automatically..
https://owncloud.org/install/#testing
Sorry for the trouble.
