### ISSUE TITLE
Share dialog not translated

### ISSUE THREAD

**Issue by christianlx** [owncloud/client#3121]
### Expected behaviour
I've installed the latest 1.8 client on a french Windows Pro Operating system. The client should be in french

### Actual behaviour
The general GUI is in french but the new share option GUI is in english

### Steps to reproduce
1.Install the latest 1.8 version 
2. Try to share, the options are in english
3. 

### Server configuration
Operating system:CentOS6.6

Web server: Apache

Database:mySQL

PHP version:5.5

ownCloud version:7.0.5

Storage backend:Local

### Client configuration
Client version:1.8

Operating system:Tested on Windows 8 and Windows 8.1

OS language:French

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.
No error in logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:
No errors in logs

3. ownCloud log (data/owncloud.log):
![english](https://cloud.githubusercontent.com/assets/10811230/7180708/8a4eec94-e444-11e4-8a01-82e0548eeb79.jpg)
![generalguiinfrench](https://cloud.githubusercontent.com/assets/10811230/7180709/8a4f0706-e444-11e4-9d8e-1f76e4e62e25.jpg)

No errors in logs

**Comment by danimo** [comment]
Strange: looks good here in the translation sources:

* [1.8.0 Release](https://github.com/owncloud/client/blob/v1.8.0/translations/client_fr.ts#L1765-L1975)
* [1.8 branch](https://github.com/owncloud/client/blob/1.8/translations/client_fr.ts#L1765-L1874)

**Comment by ogoffart** [comment]
The share dialog UI was re-done in the branch by @dragotin after the release and many strings were changed, and the changes are not yet in the translations

**Comment by danimo** [comment]
We updated to the wrong translation target. Transifex now has all strings and we expect them to be translated for the 1.8.1 release.
