### ISSUE TITLE
Change language in share dialog

### ISSUE THREAD

**Issue by plages** [owncloud/client#3123]
Hello,
I want to change the labels in the sharing dialog into Dutch. I thought i'd change the corresponding strings in the sharedialog.cpp. But i'm not sure i can change these without problems especially the values containing an ampersand (&). Can i please get some guidance on translating the dialog and on the connection between the .cpp .h an .ui files.
As i've seen the strings (like Set p&assword) in more then one file i'm guessing these cannot be changed without problems.

**Comment by danimo** [comment]
Don't change the translations in the source! There is a problem with the strings not being uploaded to our translation platform (reported as #3121), and we'll fix that -> Will be in 1.8.1.

**Comment by plages** [comment]
Thanks Danimo. I had a feeling this was not the way to go.
