### ISSUE TITLE
 owncloud dosnt sync git repository #15175 

### ISSUE THREAD

**Issue by treaki** [owncloud/client#3127]
hi,
as before, wrong by me, created as issue https://github.com/owncloud/core/issues/15175 in core repository;

to backup some git repositorys i did a ```clone --bare``` into the ownCloud folder. But it isnt syncing and there is no message about the status where it should be...

![screenshot from 2015-03-24 22 21 00](https://cloud.githubusercontent.com/assets/1477872/6813372/1feec094-d275-11e4-9942-1d5353796df5.png)

please help me out on this.

thanks

**Comment by guruz** [comment]
Did you try this with a recent linux nightly?
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3Anightly&package=owncloud-client


I believe @ckamm has made some changes regarding this.

**Comment by ogoffart** [comment]
closing old bug that might be fixed in more recent version
