### ISSUE TITLE
[Windows] New Folders on desktop locked

### ISSUE THREAD

**Issue by jason-vivid** [owncloud/client#3130]
I have a client running Windows 7 and ownCloud 1.8.0 when a folder is created it is created with a lock and unable to delete or put files into it.

As a workaround I used cygwin to chmod 777 the permissions.  It still shows up with a lock file but now it can be saved to and deleted.  

![image](https://cloud.githubusercontent.com/assets/10146532/7219555/ffcfd07e-e673-11e4-973f-c53a33867787.png)

**Comment by guruz** [comment]
If a file is created on the server and then synced down to the client?

**Comment by jason-vivid** [comment]
No. Created on the desktop. 

Jason

**Comment by guruz** [comment]
not sure i understand. if you create the folder on the desktop and then it has this lock symbol, then it's your fault?

**Comment by jason-vivid** [comment]
After a standard install of ownCloud on a Windows 7 PC here are the steps to reproduce:

In a windows explorer window:
1. Navigate into ownCloud top level and select shared folder
2. Click new folder (or right click and add new folder) within that shared folder
3. Rename folder ('New Folder' > 'Folder XYZ')
4. Rather than a standard folder icon one with a lock appears.
5. Before the chmod 777 workaround the user would be unable to enter or save to the newly created folder. Workaround allows saving to the folder but the lock icon still exists.

If other users create folders on their client. this PC syncs (downloads that folder) with the lock symbol as well.

Jason

**Comment by jason-vivid** [comment]
Folders which are created in the web interface also show up with the lock just like the ones created on the desktop client.

**Comment by Dianafg76** [comment]
@jason-vivid 
Could try the with the latest client version, v 1.8.2?
You may download it from: 
http://download.owncloud.com/desktop/daily/ownCloud-1.8.2.5133-nightly20150602-setup.exe

Thanks!!

**Comment by dragotin** [comment]
@jason-vivid you mentioned in the reproduction list: *"Navigate into oC top level and select shared folder"* I fail to understand that, are you talking about a shared ownCloud folder, or is that something about a windows function?

Please elaborate, thanks. Because: Sharing of new folders obviously works, and I just tested it again.

**Comment by ogoffart** [comment]
Is this still a problem with 2.0.2?
What kind of folder get locked?
AFAIK we don't try to lock folders from the owncloud client, so we must find a cause for this.
