### ISSUE TITLE
Access Denied Error - Moved Files/Folders to "Ignored" Directory

### ISSUE THREAD

**Issue by madmoneymike5** [owncloud/client#3132]
### Steps to reproduce

1. Download and install client.
2. Sync ALL files.
3. Once sync is complete, click "Choose What to Sync."
4. Select a folder to ignore.
5. In web client, move files that are not ignored by Windows client into folder that is ignored by the windows client.

### Expected behaviour
Windows client should detect that the files/folders were moved to a directory that it has been told to ignore, so it should just delete the files.

### Actual behaviour
Windows client detects that the files were moved and attempts to delete them, but fails with "Error removing 'C:\Users\\[username]\ownCloud\\[Folders]\\[File attempting to delete].[ext]': Access is denied.;"

### Server configuration
**Operating system**: Linux Ubuntu 14.04LTS

**Web server:** Apache2

**Database:** MySQL

**PHP version:** 5.5.9

**ownCloud version:** (see ownCloud admin page) 8.0.2

**Updated from an older ownCloud or fresh install:** Fresh Install

**List of activated apps:** Default apps, nothing else.

**The content of config/config.php:**

```
I don't believe this is relevant for this issue. I'll post it later if requested.
```

**Are you using external storage, if yes which one:** local/smb/sftp/... None

**Are you using encryption:** yes/no Yes, SSL SHA2

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/... No.

### Client configuration
**Browser:** Chrome 41.0.2272.118 m

**Operating system:** Windows 7 Home Premium

**Client Version:** 1.8.0 (build 4893)

#### Web server error log
```
No errors pertaining to this issue.
```

#### ownCloud log (data/owncloud.log)
```
No errors pertaining to this issues.
```

#### Browser log
```
No errors pertaining to this issue.
```
### Miscellaneous Notes

I have not attempted to recreate this issue on any other operating system client. I synced all files before ignoring a particular directory. I don't know whether or not this would still be an issue had I told the client to ignore this directory in the first place; this is a condition I am unable to test, but it might be worth it for a developer to try this in order to help pinpoint cause of the bug.

**Comment by ckamm** [comment]
@madmoneymike5 I've tried to reproduce it with 1.8.0 (build 4893) and server version 7.0.4.2 (which shouldn't matter) but did not run into problems. 

Could you check which process is locking the file (http://www.techsupportalert.com/content/how-find-out-which-windows-process-using-file.htm) and generate a client log file (https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly)?

**Comment by madmoneymike5** [comment]
Traveling this weekend. I'll report back next week.

**Comment by madmoneymike5** [comment]
I've been able to reproduce this error today on the same machine as before. On another machine, which has the same "ignore" list as the first machine, the client was successfully able to delete those files that had been moved on the web client. No errors were generated and the client is operating normally on that machine. So, I think this situation is perhaps related to this specific machine.

I generated a log file like you asked, but upon reviewing its contents, I am going to decline to upload it as it's 22MB full of personally identifiable information and proprietary information. I will, however, upload a few screenshots of the client giving similar information as found in the logs. Also, I used the Process Explorer application that you referenced. It seems to be identifying the locking application as Windows Explorer (explorer.exe).

I am logged in as adminstrator on both machines mentioned above (the one having issues and the one working fine), and both are running the same operating system (Windows 7 with Service Pack 1).

Hope this helps.

![image1](https://cloud.githubusercontent.com/assets/11854243/7352068/ee8dd96c-ecce-11e4-8839-5df5012a8509.jpg)
![image2](https://cloud.githubusercontent.com/assets/11854243/7352069/ee90933c-ecce-11e4-8256-243a1769341f.jpg)

**Comment by nekoal** [comment]
I think such screenshots not very helpful. At least, file extention of locked file not contain private information. About locking files by Explorer - it may be some shell extention (for example, providing preview of files or showing syncronization status). Preview may be generated for pictures, videos, pdf files. Settings of this extentions may be different even if OS version match. Unfourtunately, I can't see file extention on screenshots to suggest what shell extention used. You can see list of all dll files used be explorer.exe in Process Explorer. That list includes shell extentions so you can compare lists on both pc and detect possible reason.
Are you install owncloud client with enabled shell extention on both pc? If you wait some time after syncronize is locking released? If you close handle which locking file with help Process Explorer is locking restored in some seconds? If you restart computer and then try to sync changes? If you reinstall occlient without shell extention?

**Comment by ckamm** [comment]
@madmoneymike5 Thanks!

I agree with what @nekoal suggested: Why does explorer lock these files? Does it work if you close all explorer windows? If you restart the computer? What kind of file is it? What kind of shell extensions to you have installed? Do you use the OwnCloud sync icons shell extension?

**Comment by madmoneymike5** [comment]
Why does explorer lock these files?: I don't know. I see no reason why said files were locked in the first place.
Does it work if you close all explorer windows?: No, the problem persists.
If you restart the computer?: No, restarting the computer doesn't seem to change anything. The lock persists.
What kind of file is it?: All sorts of file types fail to be deleted; it doesn't appear to be specific to a certain type or types of files.
What kind of shell extensions do you have installed?: I think you're asking what kind of programs do I have installed that modify the menu that is displayed when I right-click in Explorer. If so: Dropbox, 7-Zip, and a couple more probably. I'm not at that computer today, so I'll have to check it later. Dropbox is set to monitor its own folder that is completely separate from ownCloud, so it's unlikely that Dropbox is a part of this problem.
Do you use the OwnCloud sync icons shell extensions?: Yes.

**Comment by nekoal** [comment]
I remember I used another sync client and it prevented my flash drives from dismount by locking. It was function for loading images from flash drives to cloud storage. I think different monitor folders can't be recognized as base for exclude Dropbox from possible reasons list.

**Comment by ckamm** [comment]
@madmoneymike5 Thanks for checking these things. Unfortunately it's still unclear what locks your file. Does anything change if you quit as many other applications and services as possible?

nekoal's suggestion of comparing DLLs used by explorer.exe between machines may also lead somewhere.

**Comment by dragotin** [comment]
Closing this as it looks very much like a local issue on that machine and long time no progress. Sorry.

**Comment by madmoneymike5** [comment]
Actually, I've been rather busy and haven't had a chance to post the new
information about this. It is happening on my home computer now, as well.
Any time I upload a file on a machine to a folder that is synced on both
machines, but then move the file to a folder on one machine that isn't
being synced on the other, I get this access denied error. It happens on
ALL my computers.
