### ISSUE TITLE
Build Process for Windows

### ISSUE THREAD

**Issue by tobitech** [owncloud/client#3133]
I am following the Appendix A documentation https://doc.owncloud.org/desktop/1.7/building.html for building the owncloud client on OpenSUSE when I get to the step 4 (for Windows section) and I try to add the plugin via the terminal i get an error that says
If 'mingw32-cross-nsis-plugin-processes' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf mingw32-cross-nsis-plugin-processes
I need help

**Comment by danimo** [comment]
Are you building from git? don't build off master. Use the 1.8 branch. Furthermore, you should use the 1.8 docs :)

**Comment by tobitech** [comment]
Sorry, I am new to git and Distros. I don't understand what you mean by 1.8 branch or 1.8 docs. More explanations please

**Comment by guruz** [comment]
1.8 branch: ```git checkout 1.8``` e.g. https://git-scm.herokuapp.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging
1.8 docs: https://doc.owncloud.org/desktop/1.8/

**Comment by tobitech** [comment]
To be specific, what I want to do to the source code is that when users install the desktop client, they would not need to enter a server address. I want to pass our server address to the desktop client automatically, so that other users that installs the compiled code will just be taken to the main page or dashboard straight up and start managing their storage. I would appreciate all helps

**Comment by dragotin** [comment]
This is the projects bug tracker, not suited for such kind of help. Please seek out on mailinglist or forum. Thanks.

**Comment by tobitech** [comment]
can I get a video tutorial or something very detailed on compiling this code for windows?

**Comment by pierrejochem** [comment]
Please have a look here:

https://github.com/owncloud/administration/tree/master/build-clients

**Comment by RealRancor** [comment]
@dragotin
We don't have any knowledge at the forums to answer such questions. :wink:
