### ISSUE TITLE
[Wizard] "Click here" link does nothing (it does not open a browser)

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3135]
### Steps to reproduce
1. Open your ownCloud desktop client
2. Fill in the server url
3. Fill in the user field with a non-existent user
4. An alert message view is shown, letting you know "Access forbidden by server.."

### Expected behaviour
If I click on "click here" a browser is open automatically

### Actual behaviour
If I click on "click here" nothing happens

### Version
Version 1.8.0 (Build 2139)

![captura de pantalla 2015-04-20 a las 13 32 06](https://cloud.githubusercontent.com/assets/12032058/7247262/fc6dda26-e807-11e4-8c6b-178168306a2d.png)

**Comment by guruz** [comment]
The .ui has 

```
     <property name="openExternalLinks">
      <bool>true</bool>
     </property>
```

I cannot get this error here, i'm getting a different one "There was an invalid response to an authenticated webdav request"

**Comment by guruz** [comment]
The URL behind the link is correct, if I invoke ```QDesktopServices::openUrl``` manually it also works..

**Comment by Dianafg76** [comment]
In windows happend the same Issue
### Server configuration
**Version DESKTOP**:
1.8.1.5007-nightly20150429
**Web server:**
{"installed":true,"maintenance":false,"version":"8.0.3.4","versionstring":"8.0.3","edition":"Enterprise"}

**Comment by gig13** [comment]
@guruz 
Can you clarify if this will be in the 1.8.1 client? Is it being pushed to the 1.8.2?

**Comment by guruz** [comment]
@gig13 Yes 1.8.2 possibly.
@ogoffart You're the QtWidget guy.

**Comment by Dianafg76** [comment]
I tested the issue and it still does not work.
Desktop v1.8.2.2367-nightly20150518

**Comment by ogoffart** [comment]
@Dianafg76  I tested both linux and the build 5083 on windows and it worked well.

Maybe it's a mac problem then?

**Comment by Dianafg76** [comment]
@ogoffart Maybe it's a Mac problem

**Comment by guruz** [comment]
I tested on my Mac and it works there too.
Can you verify what the "Built from Git revision ..." (which revision) it says?

**Comment by ogoffart** [comment]
And which label, precisely?

**Comment by Dianafg76** [comment]
@guruz, @ogoffart, I tested again and is work with MAC
DESKTOP v 1.8.2 (buil2369)
So if anybody has any problem , I close Issue
