### ISSUE TITLE
[Sharing Link] Error code: 400 when change the date set on server in "Set expiration date"

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3136]
### Steps to reproduce
1. Open your ownCloud web Client
2. Create a new folder, called a
3. Access to the folder a
4. Create a new text file
5. Go back to the root
6. Select share the folder a
7. "set expiration date" and select the date when you want it to expire
8. Open your ownCloud desktop client and log in to the same account
9. Go to Open Folder "ownCloud"
10. Right click on the folder a
11. Select share with ownCloud
12. From the sharing menu, select de check box "Set expiration date"
13. Change the date expiration, 

### Expected behaviour
The expiration date is updated to the new one

### Actual behaviour
When you change the date is appears "OCS API error code:400"

###Version
Version 1.8.0 (Build 2139)
![screen shot 2015-04-21 at 10 36 16](https://cloud.githubusercontent.com/assets/12032058/7249479/ec521554-e81a-11e4-819a-aeb4fe31c2bc.png)

**Comment by SergioBertolinSG** [comment]
Related with this PR https://github.com/owncloud/core/pull/14987

**Comment by SergioBertolinSG** [comment]
Using curl on a 8.1 server i can modify the expiration date without problems.

**Comment by PVince81** [comment]
Is it possible to set the expiration date with the client (initially set, not change) ?

@Dianafg76 what server version are you testing against ?

@rullzer does this issue ring any bells ?

**Comment by Dianafg76** [comment]
@PVince81 The tested version of the server is "8.0.3.1"

**Comment by ckamm** [comment]
I could not reproduce the problem with client 1.8 (60729f2bbd660a7232c3bb2dbc1faac6511cf4e9) and server 8.0.2.0.

**Comment by rullzer** [comment]
@PVince81 nope does not ring any bells. I'll look into it later today.

@Dianafg76 do you enforce the date on the server side.

**Comment by Dianafg76** [comment]
The date was not enforce on the server.

Indeed, no matter if you have set the expiration time on that file/folder previously on the web interface previously or not, it always fails.

Encryption is enable and LDAP

Logs desktop: 
```
04-22 10:53:21:552 0x7f9d83532640 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/Diana/ownCloud/share in/Photo-2015-01-22-18-16-54_0198.PNG"
04-22 10:53:29:061 0x7f9d83532640 OCC::SocketApi::command_SHARE: void OCC::SocketApi::command_SHARE(const QString &, QLocalSocket *) "/Users/Diana/ownCloud/sync folder1"
04-22 10:53:29:061 0x7f9d83532640 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE:OK:/Users/Diana/ownCloud/sync folder1"
04-22 10:53:29:062 0x7f9d83532640 OCC::ownCloudGui::slotShowShareDialog: void OCC::ownCloudGui::slotShowShareDialog(const QString &, const QString &, bool) Opening share dialog
04-22 10:53:29:065 0x7f9d83532640 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "https://qa.oc.solidgear.es" + ""
04-22 10:53:29:425 0x7f9d83532640 OCC::ShareDialog::slotSharesFetched: void OCC::ShareDialog::slotSharesFetched(const QString &) Status code:  404
04-22 10:53:29:425 0x7f9d83532640 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "https://qa.oc.solidgear.es" + ""
04-22 10:53:29:638 0x7f9d83532640 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "https://qa.oc.solidgear.es" + ""
04-22 10:53:29:818 0x7f9d83532640 OCC::ShareDialog::slotSharesFetched: void OCC::ShareDialog::slotSharesFetched(const QString &) Status code:  100
04-22 10:53:32:121 0x7f9d83532640 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "https://qa.oc.solidgear.es" + ""
04-22 10:53:32:301 0x7f9d83532640 OCC::ShareDialog::slotExpireSet: void OCC::ShareDialog::slotExpireSet(const QString &) Status code:  400
04-22 10:53:35:592 0x7f9d83532640 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("ownCloud")
04-22 10:53:35:593 0x7f9d83532640 OCC::Folder::slotRunEtagJob: * Trying to check "ownCloud" for changes via ETag check. (time since last sync: 57 s)
04-22 10:53:35:595 0x7f9d83532640 OCC::FolderMan::slotRunOneEtagJob: Scheduling "ownCloud" to check remote ETag
```
logs server
```
Error	hook	error while running hook (OCA\Files_Encryption\Hooks::postRenameOrCopy): Could not obtain lock type 1 on "/opt/owncloud/data/a79b7ba8-7215-1034-9a45-078ef03771d2/files_encryption/keys/Folder1/LUsgzq!0k02sek+szBqrzN5=R#UJpWql&rwhnYVb~Gh!l!/1 copy 5.txt".	2015-04-22T08:42:09+00:00
Error	PHP	fopen(/opt/owncloud/data/a79b7ba8-7215-1034-9a45-078ef03771d2/files_encryption/keys/Folder1/LUsgzq!0k02sek+szBqrzN5=R#UJpWql&amp;rwhnYVb~Gh!l!/1 copy 5.txt): failed to open stream: No such file or directory at /opt/owncloud/apps/files_locking/lib/lock.php#83
```

![screen shot 2015-04-22 at 10 56 20](https://cloud.githubusercontent.com/assets/12032058/7270671/3d0facea-e8de-11e4-9a1f-71a7492a3a9e.png)

**Comment by ckamm** [comment]
Could be the same as #3204, I think expireDate goes through updateShare() as well.

**Comment by ckamm** [comment]
Very likely caused by owncloud/firewall#95 and a patch like owncloud/core#16117 would help.

**Comment by ckamm** [comment]
@Dianafg76 I'm confident this will work fine with the firewall disabled or php >= 5.6.0. Feel free to close once verified.

**Comment by Dianafg76** [comment]
I re-tested and is OK
