### ISSUE TITLE
Propagate file permissions of Shares

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#3137]
If a read only share is synced, the files and directories on the local repository should be set accordingly to read only.

Attention must be payed for the root dir where we need write access to for the sync journal.

**Comment by dragotin** [comment]
cc @hodyroff

**Comment by guruz** [comment]
Only propagate them down, right?

For all OSes?

**Comment by dragotin** [comment]
Yes, only propagate down. The server side can not be changed if the share is read only. Yes, for all OSes.

**Comment by moscicki** [comment]
@dragotin: wouldn't this be almost equivalent to the "one-way sync (download)" feature?

**Comment by dragotin** [comment]
No, this is only to prevent people from changing content of readonly shares. Of course they still can, because it's on their local file system, but it will be a good hint to not change stuff, if it is read only.

**Comment by ckamm** [comment]
Closing this since #3244 is the same issue and includes more discussion.
