### ISSUE TITLE
Error when sharing in Windows 8.1 (custom client)

### ISSUE THREAD

**Issue by plages** [owncloud/client#3138]
I have built a branded client for Windows which works just fine in Windows 7 but on my laptop in Windows 8.1 i get the error below when i click share with ownCloud.

![20150421-000005](https://cloud.githubusercontent.com/assets/3436731/7252329/429a5da4-e834-11e4-8b7c-be3ac91897be.png)

Any ideas what could be the cause of this?

**Comment by rullzer** [comment]
Strange. Error code 0 should not be returned by the server.

Could you post the log of the client?

**Comment by plages** [comment]
There you go:


4-22 12:00:09:741 0x5998390 OCC::SocketApi::command_SHARE: void OCC::SocketApi::command_SHARE(const QString&, QLocalSocket*) "C:\kloud\20150218 concept vaststelling.doc"
04-22 12:00:09:741 0x5998390 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE:OK:C:\kloud\20150218 concept vaststelling.doc"
04-22 12:00:09:741 0x5998390 OCC::SocketApi::sendMessage: WARN: Could not send all data on socket for  "SHARE:OK:C:\kloud\20150218 concept vaststelling.doc
"
04-22 12:00:09:741 0x5998390 OCC::ownCloudGui::slotShowShareDialog: void OCC::ownCloudGui::slotShowShareDialog(const QString&, const QString&, bool) Opening share dialog
04-22 12:00:09:772 0x5998390 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for  QUrl( "https://kloud.kraaijvanger.nl" )  querying ""
04-22 12:00:09:772 0x5998390 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Kan opgegeven procedure niet vinden.)
04-22 12:00:09:772 0x5998390 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

04-22 12:00:09:772 0x5998390 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
04-22 12:00:09:803 0x5998390 OCC::SocketApi::onLostConnection: SocketApi:  Lost connection  QLocalSocket(0x8079450)
04-22 12:00:11:609 0x5998390 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 401 "Error downloading https://kloud.kraaijvanger.nl/ocs/v1.php/apps/files_sharing/api/v1/shares?path=%5C20150218 concept vaststelling.doc&format=json - server replied: Internal Server Error"
04-22 12:00:11:609 0x5998390 OCC::ShareDialog::checkJsonReturnCode: int OCC::ShareDialog::checkJsonReturnCode(const QString&, QString&) Failed to parse reply
04-22 12:00:11:609 0x5998390 OCC::ShareDialog::slotSharesFetched: void OCC::ShareDialog::slotSharesFetched(const QString&) Status code:  0
04-22 12:00:11:609 0x5998390 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for  QUrl( "https://kloud.kraaijvanger.nl" )  querying ""
04-22 12:00:13:375 0x5998390 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 401 "Error downloading https://kloud.kraaijvanger.nl/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json - server replied: Internal Server Error"
04-22 12:00:13:375 0x5998390 OCC::ShareDialog::checkJsonReturnCode: int OCC::ShareDialog::checkJsonReturnCode(const QString&, QString&) Failed to parse reply
04-22 12:00:18:159 0x5998390 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() The following folders need to check for the remote ETag: QSet("kloud")
04-22 12:00:18:161 0x5998390 OCC::Folder::slotRunEtagJob: * Trying to check "kloud" for changes via ETag check. (time since last sync: 5665 s)
04-22 12:00:18:165 0x5998390 OCC::FolderMan::slotRunOneEtagJob: Scheduling "kloud" to check remote ETag
04-22 12:00:18:167 0x5998390 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for  QUrl( "https://kloud.kraaijvanger.nl" )  querying ""
04-22 12:00:18:381 0x5998390 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""553694f815d9e""53b3c7aa37a49""52948624f0938""5294817652c7b""52948a47aece9""529483d66e3e4""53023559ae301""53c78488b39ec""529482dbf273c""53023559f18f6""5302355a409d1""537dc4001d49f""54f470304102e""540f23de56f08""5445212e7744d""550dcb1c91307""527238b0de6af""535929e184354""546cfc1948589""546cfd9466add""525151cc63339""52724b9eb1aed""55155a28aad65""51cc9b5362e34""54da56becefbd""54bfa41055a9c""54d0ed19b51e4""52950cc3abb93""52950cc48199a""53b54088f3e58""530b2ae7e39b9""5432e8f9be6c3""540368de936da""51f58d08b6513""51f58d19a9394""5283a267eea23""5280f52e9045a""532b256fb1e3c""52948e1030b0c""534ecf82d6c51""552035c2e7552""52852ebcd329d""549332efbc60a""52947f5c60739""529487b260bb5""52948d2be1297""5236cc3b3744c""552949515fba9""5294899b2091b""54b68e289b141""54d47254e7a19""54ad5250a2b92""54ae4c4c7b80a""5239a1f70e29b""52e03d8fdf20e""54bfa492a0573""524bcdb702f8c""51c82651162a2""522f742d56599""527238c275672""54ad5337c12a4""54ae4c4d61fd9""54ad52521b21b""54ae4c4d28517""519f1783e1a11""52e8dbb745c45""5487770e785de""529480a08458d""52947c816bfc0""54c24ee5b0254""52947c9ca32d0""552e1000de149""5255209a90082""52e7667304554""539958beefa5e""54b909d18eec6""513f90a333fb34.60087706""513f90a33582a9.43049245""5151f3e6e1fba8.16598553""54b51756a75fc""52947e5f3185d""551d28c391962""52fe1d75e50a3""52399ef290494""540f23dd35bff""540f23dfb49e6""516fd2c48616a""516fd2c4b6921""516d39ebd0977""516d39eb60c35""5379f8869d2ce""54c7e3cf784ce""52947b2bc4d0f""52947fdaaa6dd""52a7fb1580395""516fd2c4d3da5""516d39eb94a1b""516fd4de9087e""516fd2c42ab11""54fd9e3363dbb""5391a38fa6128""52a20f4969b95""542c12f11794c""54b68ab45af08""538cd28f31dd6""5107e3c9a70553.93336068""5283a2621f8a4""5447f1f24dce9""551bec8dacc2d""553694f800396""54b79fe00cddb""54b79f7839ce9""5511b9e3606d8""529482493e5c2""550557ec7d4ba""540f2404ac9a1""551c419b09268""551c41bd66c4d""549332e811cb3""551d28c43be03""540f5fd42cfc0""535929eed149d""52948c9adadaa""551d28c6874d7""546cfc3d5fc9a""516fd2c3dfb77""542c12f17a85d""527238a51a7fd""527238ab040a0""527238bc995ec""527238b6be035""549347ab57a04""52fd31b988abc""51d2e27c990f9""51d2e27c3db81""51d2e27b812f2""51d2e27be789a""5119ef6e2054b3.94810961""55354f9d1c84d""52e0388c35369""52e0388c33162""51b97ee0d3345""523ac1f885fdb""529486fe39178""542c12f1d00cc""52948be6463ed""551d28c39e368""5345952b5d02c""53b2810e095e1""53b28eb254fa1""52e0388c3c485""52494dcaae66a""523ac1f881a21""53bc4f70147fb""524f23114a2d0""54b6cdc41dc84""51f58cdf4fd17""522f742792b41""540447860382d""54f470271c8b1""51b70ac80cfb8""52e0388c31d59""52e0388c2abdd""54a156d4ca42a""529488d01ebb2""51b7163c70e3d""5140ebdd509f86.89404681""5140ebdd527212.36232048""535641df85cc6""53564251c8e05""531854d3d3d20""531854d3dc4d5""54ac417f5225f""54b6e69a8255e""552fcd628cf40""54a156e3e591a""5141ea6d573307.41761905""5141ea6d596106.39592908""535923550aabe""52947d15bbea2""53b2843ad8c9b""5332cc94b14cc""52e0d74976745""5444c41ad9aed""538e1ab1cbc0a""550977995c325""552fd50602b01""52f8a8519ebb8""52f8a8567f218""51f58d132181e""54de4ae316159""51922af266abb""523ae6a0af2ce""51b83ea1518f8""537d0c8ed995b""540eaa2425879""53459501e7fb1""534595016bdde""5492d66292ac3""54d4732d2aa29""54d473d50b42a""54d473d151b61""54d472660d861""53a1852270d3e""54dcc4106ac19""52947d44a2231""5444e45f8782a""5346794d276f7""523aa828e61d6""5240867e266cf""5294817def0c1""52948c0130444""542257e2e524a""54ee39af40312""546cfd8cd34a4""54b7a46699861""5452673a61440""533dadc78036f""53ad2e3fca407""5468f49d6b19e""5272388ee77df""54574bc1ba740"" , received: ""553694f815d9e""53b3c7aa37a49""52948624f0938""5294817652c7b""52948a47aece9""529483d66e3e4""53023559ae301""53c78488b39ec""529482dbf273c""53023559f18f6""5302355a409d1""537dc4001d49f""54f470304102e""540f23de56f08""5445212e7744d""550dcb1c91307""527238b0de6af""535929e184354""546cfc1948589""546cfd9466add""525151cc63339""52724b9eb1aed""55155a28aad65""51cc9b5362e34""54da56becefbd""54bfa41055a9c""54d0ed19b51e4""52950cc3abb93""52950cc48199a""53b54088f3e58""530b2ae7e39b9""5432e8f9be6c3""540368de936da""51f58d08b6513""51f58d19a9394""5283a267eea23""5280f52e9045a""532b256fb1e3c""52948e1030b0c""534ecf82d6c51""552035c2e7552""52852ebcd329d""549332efbc60a""52947f5c60739""529487b260bb5""52948d2be1297""5236cc3b3744c""552949515fba9""5294899b2091b""54b68e289b141""54d47254e7a19""54ad5250a2b92""54ae4c4c7b80a""5239a1f70e29b""52e03d8fdf20e""54bfa492a0573""524bcdb702f8c""51c82651162a2""522f742d56599""527238c275672""54ad5337c12a4""54ae4c4d61fd9""54ad52521b21b""54ae4c4d28517""519f1783e1a11""52e8dbb745c45""5487770e785de""529480a08458d""52947c816bfc0""54c24ee5b0254""52947c9ca32d0""552e1000de149""5255209a90082""52e7667304554""539958beefa5e""54b909d18eec6""513f90a333fb34.60087706""513f90a33582a9.43049245""5151f3e6e1fba8.16598553""54b51756a75fc""52947e5f3185d""551d28c391962""52fe1d75e50a3""52399ef290494""540f23dd35bff""540f23dfb49e6""516fd2c48616a""516fd2c4b6921""516d39ebd0977""516d39eb60c35""5379f8869d2ce""54c7e3cf784ce""52947b2bc4d0f""52947fdaaa6dd""52a7fb1580395""516fd2c4d3da5""516d39eb94a1b""516fd4de9087e""516fd2c42ab11""54fd9e3363dbb""5391a38fa6128""52a20f4969b95""542c12f11794c""54b68ab45af08""538cd28f31dd6""5107e3c9a70553.93336068""5283a2621f8a4""5447f1f24dce9""551bec8dacc2d""553694f800396""54b79fe00cddb""54b79f7839ce9""5511b9e3606d8""529482493e5c2""550557ec7d4ba""540f2404ac9a1""551c419b09268""551c41bd66c4d""549332e811cb3""551d28c43be03""540f5fd42cfc0""535929eed149d""52948c9adadaa""551d28c6874d7""546cfc3d5fc9a""516fd2c3dfb77""542c12f17a85d""527238a51a7fd""527238ab040a0""527238bc995ec""527238b6be035""549347ab57a04""52fd31b988abc""51d2e27c990f9""51d2e27c3db81""51d2e27b812f2""51d2e27be789a""5119ef6e2054b3.94810961""55354f9d1c84d""52e0388c35369""52e0388c33162""51b97ee0d3345""523ac1f885fdb""529486fe39178""542c12f1d00cc""52948be6463ed""551d28c39e368""5345952b5d02c""53b2810e095e1""53b28eb254fa1""52e0388c3c485""52494dcaae66a""523ac1f881a21""53bc4f70147fb""524f23114a2d0""54b6cdc41dc84""51f58cdf4fd17""522f742792b41""540447860382d""54f470271c8b1""51b70ac80cfb8""52e0388c31d59""52e0388c2abdd""54a156d4ca42a""529488d01ebb2""51b7163c70e3d""5140ebdd509f86.89404681""5140ebdd527212.36232048""535641df85cc6""53564251c8e05""531854d3d3d20""531854d3dc4d5""54ac417f5225f""54b6e69a8255e""552fcd628cf40""54a156e3e591a""5141ea6d573307.41761905""5141ea6d596106.39592908""535923550aabe""52947d15bbea2""53b2843ad8c9b""5332cc94b14cc""52e0d74976745""5444c41ad9aed""538e1ab1cbc0a""550977995c325""552fd50602b01""52f8a8519ebb8""52f8a8567f218""51f58d132181e""54de4ae316159""51922af266abb""523ae6a0af2ce""51b83ea1518f8""537d0c8ed995b""540eaa2425879""53459501e7fb1""534595016bdde""5492d66292ac3""54d4732d2aa29""54d473d50b42a""54d473d151b61""54d472660d861""53a1852270d3e""54dcc4106ac19""52947d44a2231""5444e45f8782a""5346794d276f7""523aa828e61d6""5240867e266cf""5294817def0c1""52948c0130444""542257e2e524a""54ee39af40312""546cfd8cd34a4""54b7a46699861""5452673a61440""533dadc78036f""53ad2e3fca407""5468f49d6b19e""5272388ee77df""54574bc1ba740""
04-22 12:00:18:402 0x5998390 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x746eac0)  with name  "kloud"
04-22 12:00:18:413 0x5998390 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
04-22 12:00:22:259 0x5998390 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Kan opgegeven procedure niet vinden.)
04-22 12:00:22:260 0x5998390 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

04-22 12:00:22:260 0x5998390 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
04-22 12:00:22:911 0x5998390 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
04-22 12:00:22:914 0x5998390 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for  QUrl( "https://kloud.kraaijvanger.nl" )  querying "/"
04-22 12:00:26:318 0x5998390 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for  QUrl( "https://kloud.kraaijvanger.nl" )  querying "/"

**Comment by pierrejochem** [comment]
It can't be Windows 8.1 related because I'm doing the same without any trouble.

Please check your webserver logs:

```
OCC::AbstractNetworkJob::slotFinished() 401 "Error downloading https://kloud.kraaijvanger.nl/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json - server replied: Internal Server Error
```

**Comment by dragotin** [comment]
Yes, server setup trouble. Thanks @pierrejochem

**Comment by plages** [comment]
I understand from te "internal server error" portion that we can conclude that this is a server issue. However i don't understand why this doesn't occur on other clients. The only difference being the OS version and connection via WiFi in stead of Ethernet.

**Comment by pierrejochem** [comment]
Only the Logs can Show the Problem in Detail

**Comment by plages** [comment]
Even though this issue is closed i'd thought i'd post an update.
The issue is related to the Storage Charts app. There were a lot of errors relating to this app.
I disabled it and now sharing works fune.

**Comment by pierrejochem** [comment]
Cool and how did you figured that out?

**Comment by plages** [comment]
- the desktop client did not have any problems before
- i hadn't made any changes to the client
- there were errors in the server log relating to the Storage Charts app
- i had installed the Storage Charts app somewhere in the past few weeks
So then it was just a matter of trial. De-installed  the Storage Charts app and voila the desktop client worked like a charm

**Comment by dragotin** [comment]
hmm, thats interesting. The author of the storage charts app should become aware of, can you ping her/him? thanks!

**Comment by plages** [comment]
Will do




Verzonden vanaf tablet

Klaas Freitag <notifications@github.com> schreef:

hmm, thats interesting. The author of the storage charts app should become aware of, can you ping her/him? thanks!

�

**Comment by mckaygerhard** [comment]
the ouwncloud API has some problems or the documentation are out of date i can see as search by myseflt and in OC api the method must be here:

http://api.owncloud.org/classes/OCP.Files.Storage.html#free_space

so the problem must be in the client! but of course, everybody will said "works for me"
