### ISSUE TITLE
when running out of local space the config files of the client are truncated to 0

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3144]
As a side effect of disk-full on /home I notice that the config files are truncated to 0 size in ~/.local/share/data

**Comment by moscicki** [comment]
I also noticed that as a side effect of disk full some files (5 out of 10K) have been downloaded for no reason. That could indicate that sqlite db was "corrupted" or incompletely commited,

**Comment by MTRichards** [comment]
We probably need to consider how to keep the oC client from corrupting itself if it sees that it is going to run out of disk space.

**Comment by MTRichards** [comment]
Moving to 2.0.1 So we can properly think through how to make this happen.

**Comment by ogoffart** [comment]
The config file problem was fixed in Qt 5.4

**Comment by ogoffart** [comment]
So what is left is only issue #2939  Closing this one as duplicated.
