### ISSUE TITLE
Smashbox: Create test that returns non-HTTP-207 for discovery for random folders

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3145]

**Comment by moscicki** [comment]
@guruz: do you have some implementation in mind already? After understanding the #3102  I was thinking of implementing a mini-server which would trigger all sorts of conditions, including incorrect, missing or scrambled responses, but also lower level such as cut connections etc.
I started looking into this: https://code.google.com/p/pywebdav/source/browse/pywebdav/

**Comment by guruz** [comment]
@moscicki no real idea yet, i'm not too familar with python.. 
definitely need all those cases you proposed..

CC @jnfrmarks

**Comment by moscicki** [comment]
@guruz, @dragotin, @jnfrmarks : I think we should extend this concept. Could you please brain storm with your teams to get the (as complete as possible) list of all possible runtime error conditions related to client-server communication (including obscure and infrequent errors). Things that you could image could possibly go wrong. I think this is really on the critical path for the QA.

**Comment by guruz** [comment]
https://en.wikipedia.org/wiki/Fuzz_testing :-)

**Comment by ogoffart** [comment]
`TestRemoteDiscovery::testRemoteDiscoveryError` does that
