### ISSUE TITLE
1.8.0 now seems to have *.tmp in the ignore list

### ISSUE THREAD

**Issue by dor4711** [owncloud/client#3149]
I think this is not a good decision. 

Some users have tmp files they want to sync.The earlier behavior of ignoring __~*.tmp__ files was better. Users can not edit the standard ignore list but can add item to the list. So anyone who wishes to ignore __*.tmp__ can do it.

**Comment by nekoal** [comment]
It was done to prevent errors. When Microsoft Office application save files at first it write new file with .tmp extention. Then if file saved successful Office application renames it from temporary name to target filename. If temporary file not in ignore list occlient try upload temporary file, fail then show errors in activity log. Unfourtunately, not all versions of Office applications use temporary filename covered wildcard ~*.tmp, sometimes filename have not ~ in beginning.
In my private opinion use *.tmp for something except temporary data and sync such files is rather bad taste 'cause this file extention don't specify anything about content. Also you can edit default exclude list by text editor but it will be overwritten after any client update.

**Comment by dor4711** [comment]
Which versions of MS Office applications do not have a ~ in the beginning of their temporary files? I haven't found any.

**Comment by nekoal** [comment]
Which method you use to look for it? It's practice fact: this files are relative rare but exist.

I made order in shared work folder of our department about month ago. For this task I wrote program for deleting old temporary files and logging names of recent temporary files. There were files in log with names `7A5D79DE.tmp`, `937D0CD1.tmp`. About 5 files without ~ and about 1000 with ~. We have MS Office 2007 or MS Office 2010 installed on different PC. I can't exactly say which of this versions made this files. It seems I tested this recent files and they were dubles of existing Word and Excel documents.

Wildcard in exclude list was changed on another issue where mentioned Power Point. May be for this naming behavior needs some specific conditions. Filename `7A5D79DE.tmp` look for me as generated by system function for making temporary file names. So I can suggest scenario: Word failed to generate "normal" name `~WRL*.tmp` by some reason and then used system function.

**Comment by dor4711** [comment]
ok. I just search Microsoft documents. As far as i can see the correct pattern should then be __8 Hex-Digits__ and then __.tmp__. Or when it is too hard to implement Hex-Digits it can be: __????????.tmp__ I Still think that __*.tmp__ as fix, for the regular user not editable pattern, is too much.

**Comment by nekoal** [comment]
I think if you can list examples when .tmp file not like ????????.tmp and contains useful information saved by some application it'll make stronger your point of view. You still can't be sure 8 Hex-Digits or wildcard ????????.tmp cover all possible filenames of Office temporary files. This needs additional investigation how temporary filename generated.

**Comment by guruz** [comment]
Originally this came via https://github.com/owncloud/client/issues/2424

What is the use case for syncing .tmp files?

**Comment by guruz** [comment]
Do you know if the powerpoint temporary files are hidden?
See https://github.com/owncloud/client/issues/2086

**Comment by dragotin** [comment]
Excluded again by 1fa5fa91a845227f0d46473202999a7209c024e2
