### ISSUE TITLE
Maximize client window

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#3150]
When opening the client window from the taskbar, ownCloud is a "normal" program showing a "normal" window. It should follow the "normal" design rules. That is, the user should be able to resize, maximize, and minimize the window. Not being able to do so without any obvious reason has been very frustating many times to me. I cannot see all synced directories at the same time.

Please enable default window behahavior for the owncloud client.

**Comment by danimo** [comment]
It's not a window, it's a dialog. Dialogs by definition are not maximizable. It has a taskbar entry because it lacks a parent window, and would otherwise be hard to find.

**Comment by LukeOwncloud** [comment]
Why is it a dialog?

**Comment by danimo** [comment]
Because it's not document centric, i.e. you have no benefit of horizontal maximization (the vertical one you can do manually, as the dialog remembers its size). Also you would usually not keep it open all the time, but rather set things or look things up, then close it again. If you constantly need to keep this dialog open, we've done something wrong.

**Comment by LukeOwncloud** [comment]
I have more than 4 synced directories. I can only see 2 1/2 at a time. If one fails I need to scroll through the list. That is annoying. (Indeed I do not need it to be open at all times.)

A dialog "is a small window that communicates information to the user and prompts them for a response." (from wikipedia). I do not think this is applicable for owncloud as the client shows all available options and settings. It even has tabs, so it is not small. Further, it does not require input from the user. IMO, the owcloud client should not be a dialog.

**Comment by danimo** [comment]
Again, what about simply resizing the window? It's a task you need to do exactly once.

**Comment by LukeOwncloud** [comment]
Sorry, yes, that works. So, my main issue is solved. However, I still think that it should not be a dialog window which is another issue, though.
