### ISSUE TITLE
1.8.0 recreates shared folder as "local" folder and looses sync-linkage

### ISSUE THREAD

**Issue by Omnimercador** [owncloud/client#3151]
### Expected behaviour, ### Actual behaviour

I'm having intermittent issues with random users in groups that sometime lose sync on individual shared folders. The synced folders turn into local folders, which are then synced to the server as that user's as own folder. 

If the shared folder had originally been shared with that user explicitly (not as part of a group), the share is no longer shown in the shared-list when clicking on the relevant shared folder's properties. 

If the shared folder had originally been shared with that user as part of a group, there is no way of resharing / refreshing the sync, unless the folder is reshared with that individual (not attractive when managing many folders on a group basis), or the share is removed for the whole group and recreated for the whole group (not satisfactory for 1GB folders...)
 
This error does not appear with 1.7.1.

### Steps to reproduce
none - unclear what specifically triggers the ownership change. Could be moving the folder, but it is unclear.

### Server configuration
Operating system:
Ubuntu 12.04.4

Web server: 
Apache 2.2.22 

Database:
MySQL5.5.43 

PHP version:

ownCloud version:
OwnCloud 7.01

Storage backend:

### Client configuration
Client version:
1.8.0 - this does not occur with the machines running 1.7.1

Operating system:
Windows 8.1

OS language:
English

Installation path of client:
C:\Program Files (x86)

### Logs
Don't know where to find the suitable entries, as this occurs randomly and would require trawling through weeks of logs....

**Comment by esprit-libre** [comment]
I encountered similar problem, maybe the same, with some users.
It appears on shared folder named "commun" by the owner, but named "commun (2)" on subscribers. I notice 2 times (on different users), that this shared folder "commun (2)" becomes a private folder (so upload starts) and "commun" is then downloaded as shared folder. No user action for this.
ownCloud client is 1.7.1, ownCloud server is 8.0.0. Nothing relevant found in logs.

**Comment by guruz** [comment]
FYI @icewind1991 @PVince81

**Comment by ogoffart** [comment]
@esprit-libre your problem looks like a server problem. I recommand you to report the problem on the core bug tracker.  It does not seem to be the same issue as this one because of the use of the 1.7.1 client.

@Omnimercador 
> the share is no longer shown in the shared-list when clicking on the relevant shared folder's properties.

What do you mean exactly by shared list and folder properties?  Do you mean that it is on the server?

> there is no way of resharing / refreshing the sync, unless the folder is reshared with that individual 

Normaly as the server notifies us of changes within the folder (via a change in the folder etag) the sync client should synchronize.  

There is maybe a bug in the server.

> This error does not appear with 1.7.1.

Are you sure this was the case?  Maybe you upgraded the server in the same time?

Is there a way i can try to reproduce the problem?

**Comment by esprit-libre** [comment]
@ogoffart Already looked server side, but I may have missed something. Users mostly migrate to 1.8.x client, and no more complain... so il will be difficult for me to reproduce now. Thanks for reply

**Comment by Omnimercador** [comment]
I've actually not been able to replicate it - it happens completely randomly. I know that is hardly useful for bug reporting, apologies.

It has now also happened a few times with 1.7.1 (I downgraded all clients), but seemingly less frequently.

I'll upgrade the server to 8.0.4 and hope for the best...

**Comment by ogoffart** [comment]
The client 1.8 does more thing in parallel which may explain why the client can get confused.  There are races condition in the server that are in process of being fixed.

**Comment by ogoffart** [comment]
Please re-open an issue on the server bug tracker (core) if you can reproduce this.
