### ISSUE TITLE
Show proper Proxy Error message

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#3153]
If the client starts without being able to reach its proxy, it does not show a proper error message, but:
![proxynotavail](https://cloud.githubusercontent.com/assets/1070214/7315980/dfd5d608-ea72-11e4-8726-ff2b8c14082d.png)
Technically that is of course true, but it would be cooler if it said something like *"The proxy under 192.168.178.65 is not available."* 

Can we do that?

**Comment by danimo** [comment]
I think that's a bug in Qt issuing the wrong error, but maybe there's a signal we're not catching that would tell us that.

**Comment by Dianafg76** [comment]
I tested again and everything is OK, so I close de issue
