### ISSUE TITLE
[new-ui] Progress reporting looks stuck when errors occur

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#3154]
In the new-ui branch I've seen the sync progress bar being stuck halfway when a sync finished with errors. It also showed ridiculous time estimates.

When a sync is finished, with or without errors, we don't need to show time estimates anymore. And the progress bar should either be full or be invisible.

**Comment by guruz** [comment]
btw @ckamm is it feasible to show the progress of all sync jobs at once?

**Comment by ckamm** [comment]
@guruz You mean whether we can show progress for each of the active jobs? That shouldn't be hard.

**Comment by guruz** [comment]
@ckamm Would sound nice to give users more feedback there..

**Comment by ckamm** [comment]
The progress info design changes have moved to #3403. The progress bar should no longer get stuck.

@Dianafg76 Unfortunately, I don't know how to reproduce the problem. :/

**Comment by Dianafg76** [comment]
@ckamm I tested this issue, and it is working fine, the synchronization progress bar no longer gets stuck halfway when synchronization finished with errors
Many thanks :-)
Desktop v  ownCloud-2.0.0.5255-nightly20150709-setup.exe
