### ISSUE TITLE
Invalid credentials in account setup wizard lead to incorrect error message

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#3155]
When using an incorrect password during account setup the error message "There was an invalid response to an authenticated webdav request" is shown instead of the correct "Access forbidden by...".

This regression is due to the new redirection handling. I added a new finishedWithError() slot and didn't realize networkError() may already have been emitted beforehand.

**Comment by guruz** [comment]
(Found as part of https://github.com/owncloud/client/issues/3135 )

**Comment by guruz** [comment]
Thanks, it works
