### ISSUE TITLE
data loss: a file created or modified locally while download gets overwritten

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3156]
This is for 1.7 and 1.8

This smashbox test describes and reproduces the bug: https://github.com/cernbox/smashbox/blob/master/lib/test_fileTinkerDownload.py

**Comment by moscicki** [comment]
@labkode: thanks for finding and reporting this!

**Comment by guruz** [comment]
(Similar but reverse: https://github.com/owncloud/core/issues/4511 ?)

**Comment by ckamm** [comment]
@guruz I think we should check mtime and size before the final rename of the downloaded file, similarly to how we only commit the upload if the local mtime and size are still what we expect.

**Comment by moscicki** [comment]
@ckamm: how comes you copy and paste my replies even before I finish typing ;-)

**Comment by moscicki** [comment]
There are two distinct cases: a file that is "new" and a file that your know about in the local sync db. For the moment the test only checks the new file but we will extend it.

**Comment by ckamm** [comment]
@moscicki The fix is in the 1.8 branch. It would be delightful if you could test it. :)

**Comment by Dianafg76** [comment]
I tested the issue, and is ok.
I close the Issue
