### ISSUE TITLE
SocketApi: Traverse job tree instead of iterating through list of sync items

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3158]
```SyncEngine::estimateState``` can possibly cause a lot of slow down on the main thread if the overlay plugins iterate over it.
A solution would be to use the job tree instead.

@ogoffart and @jturcotte disagree about the approach here.

Related https://github.com/owncloud/client/issues/3122

**Comment by jturcotte** [comment]
Let's close this for now since we have a possible resolution for #3122.
