### ISSUE TITLE
filenames containing a forward slash (and other characters)

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3162]
Out of all characters in the known universe forward slash "/" is the only one that Unix does not allow.

However, the sync client on Windows tries to upload filenames with forward slashes.

Should '/' be excluded from syncing on client platforms? It is a server-side limitation.

This is contrary to other characters which are currently excluded (such as ":" for example) which are the client-side limitation (mostly on Windows) and should be handled differently --> i.e. uploaded to the server but not downloaded to the client which do not support it.

**Comment by VincentvgNn** [comment]
@moscicki 
On Windows a forward slash is one of the characters that are not allowed in folder or file names.
![windows non-allowed chars in names](https://cloud.githubusercontent.com/assets/7522929/7428920/d301faca-eff8-11e4-8d59-3e21f78ae9cc.jpg)
So, is there any problem?

**Comment by guruz** [comment]
fun fact, on OS X the Finder lets you create a file with ```/``` but internally it is a ```:```

```
05-05 17:57:08:696 0x7fcfd06029c0 OCC::SyncEngine::slotJobCompleted: void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem &) "f:f" INSTRUCTION_IGNORE 6 "File contains invalid characters that can not be synced cross platform."
```

**Comment by dragotin** [comment]
@moscicki how do you create a file with a '/' in the name?

**Comment by moscicki** [comment]
I think I reported a wrong platform: the user was on Max (not Windows).

I suspect that the confusion came from the fact that the user's file (possibly created by the Finder) had the same prefix as the existing directory (so, "x/a" filename and "x" directory). 

The result was this error "File contains invalid characters that can not be synced cross platform."
I think this is totally fine.

Sorry for the noise.
