### ISSUE TITLE
1.8.0 Windows Client Crashing

### ISSUE THREAD

**Issue by Ghan04** [owncloud/client#3163]
Ever since upgrading the Windows desktop client to version 1.8.0 (build 4893), it crashes without fail shortly after starting to sync. The client will run for a few minutes, and then I get the window that says it crashed and to send an error report to the developers. I've tried uninstalling and reinstalling and that hasn't done anything. I don't see anything in the Windows event logs that seems to indicate what the issue is.
I posted this on the forums and they said it should go here. Let me know if there are any useful logs I can grab.

Thanks!

**Comment by RealRancor** [comment]
Hi,

the issue template provided here:

https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

shows some infos where you can get the needed logfiles of the sync client.

**Comment by guruz** [comment]
The 1.8.1 release candidate is coming out on Monday.. please re-try with that one too :)

**Comment by exmatrikulator** [comment]
:+1:

**Comment by danimo** [comment]
Please try RC1 now: https://owncloud.org/install/#testing

**Comment by guruz** [comment]
@Ghan04 @exmatrikulator Any success? :)

**Comment by exmatrikulator** [comment]
yes, it's working. Thanks!

**Comment by dragotin** [comment]
awesome, thanks @exmatrikulator !

**Comment by Ghan04** [comment]
Yep, working for me as well. Didn't realize there would be a new release so soon. Thanks! :)

**Comment by millemedium** [comment]
Yes! Perfekt! Now my client is workink! Thank You!
