### ISSUE TITLE
csync-0.50.0/src/std/c_string.c:360:22: error: 'iconv_to_native' undeclared

### ISSUE THREAD

**Issue by montyvesselinov** [owncloud/client#3165]

**Comment by RealRancor** [comment]
Hi,

could be useful if you're using the issue template provided here:

https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

as requested in the "guidelines for contributing" (Linked in the box shown when creating a new issue) to provide at least some informations about your issue.

**Comment by guruz** [comment]
We don't use csync 0.50 here, this is strictly for the ownCloud desktop sync client.
