### ISSUE TITLE
Allow to configure ignorelist individually for each directory

### ISSUE THREAD

**Issue by tushevorg** [owncloud/client#3166]
This would be very useful. Many users need some type of files in one directroy to be synced automatically, and vice versa in other directories.

Additionally this may help solve issue https://github.com/owncloud/client/issues/3149.

**Comment by fduraibi** [comment]
Yes please, something similar to `.gitignore` file

**Comment by guruz** [comment]
-> https://github.com/owncloud/client/issues/1558
