### ISSUE TITLE
If you delete a folder in the WEB that is inside another folder with the special character "%", when it's Synced in DESKTOP the folder is not delete

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3167]
### Steps to reproduce
1. Open your ownCloud desktop Client
2. Go  to Open Folder "ownCloud"
2. Create a new folder, called a
3. Acces to a folder a
4. Create a new folder with the special character "%" in the name, called %hola
5. Open your ownCloud web client and log in to the same account
6. Deleted the folder, called a
7. Wait for it to sync

### Expected behaviour
On the ownCloud desktop Client the folder has been deleted

### Actual behaviour
1. On the ownCloud web client has been deleted.
2. On the ownCloud desktop Client hasn't been deleted.

###Version Desktop
Version 1.8.1.2298

Web server:
{"installed":true,"maintenance":false,"version":"8.0.3.2","versionstring":"8.0.3 RC3","edition":"Enterprise"}
Checked with a server with permanent redirection

**Comment by ogoffart** [comment]
I tried to reproduce but i could not.

Can you specify exactly which step are done on the server and which step on the client?

**Comment by ogoffart** [comment]
Also, what platform is it?

**Comment by Dianafg76** [comment]
I can't reproduce again. So I close de issue
