### ISSUE TITLE
In DESKTOP fill the server URL REDIRECTED, if you don't accept the Certificate, always happend de Alert message, and does nothing 

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3168]
### Steps to reproduce
1. Open your ownCloud desktop client
2. Fill in the server url redirected
3. Press NEXT
4. Not Accepted Certificate, and press CANCEL
5. An alert message view is shown "Connection failed"
6. Press "Select a different URL"
7. Press again NEXT.
8. An alert message view is shown, letting you know "Failed to connetd to ..."

![screen shot 2015-04-28 at 11 16 22](https://cloud.githubusercontent.com/assets/12032058/7368068/e91ca3c4-eda4-11e4-9704-c777212876d5.png)

### Expected behaviour
If you click next you have to ask the user credentials

### Actual behaviour
If I click in NEXT nothing happens

###Version Desktop
Version 1.8.1.2298

Web server:
{"installed":true,"maintenance":false,"version":"8.0.3.2","versionstring":"8.0.3 RC3","edition":"Enterprise"}
Checked with a server with permanent redirection

**Comment by ckamm** [comment]
@Dianafg76 We can't ask for the user credentials because the user hasn't accepted the certificate. I think the expected behavior should be to ask to accept the certificate again. This seems unrelated to redirects, I can reproduce it with a regular server.

**Comment by ckamm** [comment]
@danimo From the code it looks like pressing 'Cancel' on the SSL certificate dialog intentionally treats ssl errors as failure from then on. What's the background? I'm considering to unset this flag for the Propfind that the account wizard sends, do you anticipate this being a problem?

**Comment by danimo** [comment]
@ckamm Not sure if I understand you correctly, but I'd say this is not intentional. If the URL in the wizard has changed, the ssl error state should be reset.

**Comment by ckamm** [comment]
@danimo @Dianafg76 In this test case 'Next' is pressed again without changing the URL. I think diana expected that it would pop up the certificate dialog again - maybe the first 'Cancel' was an accident or the user changed his mind.

**Comment by ckamm** [comment]
@Dianafg76 You should now get the certificate dialog again when clicking 'Next'.

**Comment by Dianafg76** [comment]
@ckamm just tested with the Desktop v ownCloud-1.8.1.2352-nightly20150508 and happend the same.
Checked with a server with permanent redirection and the php>5.6.8

**Comment by ckamm** [comment]
@Dianafg76 the patch probably hasn't reached the nightly builds yet

**Comment by Dianafg76** [comment]
@ckamm just tested with the Desktop v1.8.2.2359-nightly20150514, and happend the same

And if you cancel de window o click in "Retry unencrypted over HTTP (insecure), the URL is changed" 

###Step to reproduce:

1. Open your ownCloud desktop client
2. Fill in the server url redirected (HTTPS://......)
![screen shot 2015-05-14 at 11 00 57](https://cloud.githubusercontent.com/assets/12032058/7628916/acae37a0-fa28-11e4-9d38-cbfa2b9bfbb8.png)
3. Press NEXT
4. Not Accepted Certificate, and press CANCEL
5. An alert message view is shown "Connection failed"
6. Close the windown with de icon red
7. An alert message view is shown, letting you know "Failed to connetd to ..." and is changing the URL HTTP :

![screen shot 2015-05-14 at 11 03 21](https://cloud.githubusercontent.com/assets/12032058/7628955/f72ff00c-fa28-11e4-837d-a72ae5414cf2.png)

Happend the same if you Click  "Retry unencrypted over..." in the alert message view in shown "Connection falied"

**Comment by ckamm** [comment]
@Dianafg76 I just tried again and it works for me.

* Use redirected https url
* Don't accept certificate
* In the following dialog, click "select different url"
* don't change the url, just click next again
* -> the certificate is presented to the user again

And yes, clicking "Retry unencrypted..." replaces https with http in the URL, that's intentional. I think we should talk about this on IRC. :-)

**Comment by Dianafg76** [comment]
I tested again and is working
I close Issue
