### ISSUE TITLE
errors occurred ！！（Windows Installer Build (Cross-Compile)）

### ISSUE THREAD

**Issue by vechie** [owncloud/client#3169]
Hello, I have fresh installed OpenSUSE 13.2, and i have follow this steps to build owncloud desktop client 1.8 for Windows，and in the last step ,error occurred as following:
cmake -DCMAKE_BUILD_TYPE="Debug" ../client
-- Build of crashreporter disabled.
-- Found Qt5 core, checking for further dependencies...
-- Using Qt 5!
-- GIT_SHA1 ae17f58b80208df0e6318dbabbfabd7ae842332e
-- Using Qt 5.4.x
-- We would not require Neon in this setup, compile without!
-- Could NOT find INOTIFY (missing:  INOTIFY_INCLUDE_DIR) 
-- Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE) 
-- Could NOT find PdfLatex (missing:  PDFLATEX_EXECUTABLE) 
-- Using own sqlite3 from /root/client/src/3rdparty/sqlite3
-- Using own sqlite3 from /root/client/src/3rdparty/sqlite3
CMake Warning (dev) at /usr/i686-w64-mingw32/sys-root/mingw/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:224 (configure_file):
  configure_file called with unknown argument(s):

   COPY_ONLY

Call Stack (most recent call first):
  cmake/modules/QtVersionAbstraction.cmake:70 (qt5_add_resources)
  src/gui/CMakeLists.txt:7 (qt_add_resources)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/i686-w64-mingw32/sys-root/mingw/lib/cmake/Qt5Core/Qt5CoreMacros.cmake:224 (configure_file):
  configure_file called with unknown argument(s):

   COPY_ONLY

Call Stack (most recent call first):
  cmake/modules/QtVersionAbstraction.cmake:70 (qt5_add_resources)
  src/gui/CMakeLists.txt:12 (qt_add_resources)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at CMakeLists.txt:210 (configure_file):
  configure_file Problem configuring file

-- Configuring incomplete, errors occurred!
See also "/root/client/CMakeFiles/CMakeOutput.log".
See also "/root/client/CMakeFiles/CMakeError.log".
and I don't know what to do next , please help me !!

**Comment by danimo** [comment]
Sorry, this is an issue tracker and not a support forum. Please consult the developer mailing list.

**Comment by vechie** [comment]
oh, sorry,thank you ~
