### ISSUE TITLE
[1.8.1rc1] QObject::connect: Cannot queue arguments of type 'QNetworkProxy'

### ISSUE THREAD

**Issue by danimo** [owncloud/client#3170]
On Ubuntu 14.04, right on startup:

```
04-28 16:39:18:919 0x141f700 Checking server and authentication 
04-28 16:39:18:921 0x141f700 Trying to look up system proxy 
04-28 16:39:18:925 0x168e9d0 virtual void OCC::SystemProxyRunnable::run() Starting system proxy lookup 
04-28 16:39:18:925 0x168e9d0 QObject::connect: Cannot queue arguments of type 'QNetworkProxy'
(Make sure 'QNetworkProxy' is registered using qRegisterMetaType().)
04-28 16:39:20:700 0x141f700 FolderMan: Syncing is disabled, no scheduling. 
04-28 16:39:22:602 0x141f700 Client is on latest version! 
```

**Comment by guruz** [comment]
I had also gotten this some days ago on my mac, don't see it now

```04-28 15:49:26:219 0x7fd1d0600720 unknown: QObject::connect: Incompatible sender/receiver arguments
        QTcpSocket::error(QAbstractSocket::SocketError) --> QLocalSocket::_q_error(QAbstractSocket::SocketError)```

**Comment by guruz** [comment]
@danimo Could you fetch and retry? I don't have a Qt4 compile

**Comment by dragotin** [comment]
This is fixed by commit 4700c604b1ce336d0cdcfedc1d34e786ebc41a07

**Comment by ckamm** [comment]
Verified on Ubuntu 14.04.

**Comment by guruz** [comment]
With Qt4?                                                                                                                                                                                                                                                                                                                                        Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: ckammSent: Mittwoch, 6. Mai 2015 09:49To: owncloud/clientReply To: owncloud/clientCc: Markus GoetzSubject: Re: [client] [1.8.1rc1] QObject::connect: Cannot queue arguments of type 'QNetworkProxy' (#3170)Verified on Ubuntu 14.04.

—Reply to this email directly or view it on GitHub.

**Comment by ckamm** [comment]
Yes, with Qt 4.8.6 and the official rc2 package.
