### ISSUE TITLE
Error messages are confusing and it's difficult to judge their severity

### ISSUE THREAD

**Issue by jturcotte** [owncloud/client#3171]
At the moment, error messages appear in the sync status area in bright bloody red for 10 seconds, and the disappear. There is no way to know:

- What are all the errors, since they are cramped and feel like some are hidden?
- Should the user do something about them or not?
- When are they resolved?
- Are those errors (still) available in the activity list?

It could be nice to show errors as states instead of, or in addition to, events, and make that state visible in the UI. That could also mean showing the blacklist in the UI and make it more obvious to the user what are the effects of those errors, and if pressing the resync button helps or not.

**Comment by jturcotte** [comment]
cc @ogoffart @jancborchardt

What do you think, would it help or would it be more confusing?

**Comment by jturcotte** [comment]
I think that the current state is much better already, many error messages are still confusing, but it's at least possible for the user to find out if anything is still wrong.

**Comment by Dianafg76** [comment]
I tested this issue
Desktop v ownCloud-2.1.1.3016-nightly20160108.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}
Closed
