### ISSUE TITLE
Untranslated, possibly hardcoded strings

### ISSUE THREAD

**Issue by slsimic** [owncloud/client#3174]
There are few strings untranslated in latest client update altough translation is 100% done.
For now, I see "Close" button and also "Warning" string and "Cancel" "<Back" "Next>"  buttons  on Add Folder dialog. In previous, beta version, "Cancel" "<Back" "Next>"  buttons were OK
Screenshots are attached.
![close](https://cloud.githubusercontent.com/assets/12166655/7387480/cbca2788-ee5d-11e4-8351-31def7c21e02.png)
![warning-beta](https://cloud.githubusercontent.com/assets/12166655/7387481/cbd13910-ee5d-11e4-8eb5-43ba646e6ed9.png)
![warning-rc1](https://cloud.githubusercontent.com/assets/12166655/7387482/cbd2cbd6-ee5d-11e4-8108-543eba3dd0dd.png)

Client version: 1.8.1rc1  installed from official nightly repo
OS: Linux, Siduction, Debian unstable based

**Comment by slsimic** [comment]
Seems that this button things are QT related and not client related.
After opening/closing Add folder dialog few times buttons get it's translated names.
I've noticed that Next/Даље does not exist anywhere in ownCloud translations so it must be from QT

Warning string is still an issue and I think it's hardcoded somewhere.

**Comment by dragotin** [comment]
Yes, buttons and stuff are standard Qt translations. Maybe there is something fishy with your packages shipped by the distro?

**Comment by guruz** [comment]
@slsimic Checking ```client_ru.ts``` I don't see that in the file.
Also grepping the sources I don't see untranslated ```Warning```
Hmm

```
<context>
    <name>OCC::FormatWarningsWizardPage</name>
    <message>
        <location filename="../src/gui/folderwizard.cpp" line="46"/>
        <source>&lt;b&gt;Warning:&lt;/b&gt; %1</source>
        <translation>&lt;b&gt;Предупреждение:&lt;/b&gt; %1</translation>
    </message>
    <message>
        <location filename="../src/gui/folderwizard.cpp" line="48"/>
        <source>&lt;b&gt;Warning:&lt;/b&gt;</source>
        <translation>&lt;b&gt;Предупреждение:&lt;/b&gt;</translation>
    </message>
</context>
```

**Comment by slsimic** [comment]
Problem with "Warning" string seem to be gone in 1.8.2beta1 built from rev 5721d8 on May 25 2015

**Comment by guruz** [comment]
Great!
