### ISSUE TITLE
[Windows] Owncloud Client not showing on tray/taskbar

### ISSUE THREAD

**Issue by GPSHansl** [owncloud/client#3175]
### Expected behaviour
After clicking on the owncloud icon on desktop/start menu the client should show a window on screen
or an icon in taskbar.

### Actual behaviour
There is neither: no application as window, no taskbar icon.

### Steps to reproduce
1. installed any "ownCloud-1.8.0.4893-setup.exe" or "ownCloud-1.8.1.5006rc1-setup.exe" 
2. started owncloud client
3. checked screen and taskbar
4. on checking process explorer if found a process "owncloud.exe" ("C:\Program Files (x86)\ownCloud\owncloud.exe") which is not having any windows

### Server configuration
Operating system: Linux on cubietruck
Web server: nginx 1.2.1
Database: mysql 5.5.41
PHP version: PHP 5.4.39-0+deb7u2
ownCloud version: ownCloud 8.0.2 (stable)
Storage backend: ???

### Client configuration
Client version: both: "ownCloud-1.8.1.5006rc1-setup.exe" and "ownCloud-1.8.0.4893-setup.exe"
Operating system: Microsoft Windows 8.1
OS language: German
Installation path of client: C:\Program Files (x86)\ownCloud\owncloud.exe

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

04-29 11:23:43:937 0x406e918 OCC::Application::setupLogging: "################## ownCloud de_DE () 1.8.1rc1 (build 5006)"
04-29 11:23:43:953 0x406e918 OCC::Application::setupTranslations: void OCC::Application::setupTranslations() Using "de_DE" translation
04-29 11:23:43:953 0x406e918 OCC::SocketApi::SocketApi: SocketApi:  creating "//./pipe" false
04-29 11:23:43:953 0x406e918 OCC::SocketApi::SocketApi: SocketApi:  server started, listening at  "\\.\pipe\ownCloud"
04-29 11:23:43:953 0x406e918 OCC::SocketApi::slotReadExcludes: ==== added system ignore list to socketapi: "C:/Program Files (x86)/ownCloud/sync-exclude.lst"
04-29 11:23:43:953 0x406e918 OCC::SocketApi::slotReadExcludes: ==== added user defined ignore list to csync: "C:/Users/Jo/AppData/Local/ownCloud/sync-exclude.lst"
04-29 11:23:43:953 0x406e918 OCC::FolderMan::FolderMan: setting remote poll timer interval to 30000 msec
04-29 11:23:44:484 0x406e918 OCC::FolderMan::setupFolders: * Setup folders from  ""
04-29 11:23:44:484 0x406e918 OCC::FolderMan::setupFolderFromConfigFile:   ` -> setting up: "ownCloud"
04-29 11:23:44:484 0x406e918 OCC::FolderMan::setupFolderFromConfigFile:     -> file path:  "C:/Users/Jo/AppData/Local/ownCloud/folders/ownCloud"
04-29 11:23:44:484 0x406e918 OCC::Folder::checkLocalPath: Checked local path ok
04-29 11:23:44:484 0x406e918 OCC::FolderMan::setupFolderFromConfigFile: Adding folder to Folder Map  OCC::Folder(0x3fd9e50)
04-29 11:23:44:484 0x406e918 OCC::FolderMan::slotScheduleSync: Schedule folder  "ownCloud"  to sync!
04-29 11:23:44:484 0x406e918 OCC::FolderMan::startScheduledSyncSoon: Scheduling a sync in 2 seconds
04-29 11:23:44:484 0x406e918 OCC::ClientProxy::setupQtProxyFromConfig: Set proxy configuration to use system configuration
04-29 11:23:44:484 0x406e918 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
04-29 11:23:44:484 0x406e918 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

04-29 11:23:44:484 0x406e918 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
04-29 11:23:44:484 0x406e918 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
04-29 11:23:44:484 0x406e918 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

04-29 11:23:44:484 0x406e918 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available

**Comment by GPSHansl** [comment]
same issue described there: https://forum.owncloud.org/viewtopic.php?f=14&t=27897

**Comment by GPSHansl** [comment]
Further investigation:
- Client "ownCloud-1.7.1.4382-setup.exe" is working
- turning on or off "Explorer integration" in installer on "ownCloud-1.8.0.4893-setup.exe" or "ownCloud-1.8.1.5006rc1-setup.exe" won't change issue on those.

**Comment by guruz** [comment]
Maybe related https://github.com/owncloud/client/issues/3079

**Comment by guruz** [comment]
FYI @jturcotte @ckamm

**Comment by ckamm** [comment]
@GPSHansl is what you posted the whole log file? If so, maybe the client got stuck somewhere. You're saying the client main dialog never pops up? What happens if you kill that process and start the client again?

**Comment by sisu4u** [comment]
I have the same problem as @GPSHansl but for me a logfile is never created. When I kill the process and start again the process just appears again in the task manager. I created dump files of the process. Is it safe to upload them?

**Comment by ckamm** [comment]
@sisu4u Did you start the client with --logfile mylog.txt? See https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly . You could email your dumpfiles to me (kamm incasoftware de), but I'm not sure I'll get interesting data from them. If you could attach gdb (seems to be downloadable from http://www.equation.com/servlet/equation.cmd?fa=gdb) to the process when it's stuck and get a backtrace, that'd likely be super helpful.

**Comment by sisu4u** [comment]
okay I did, unfortunately now gdb is frozen, CTRL+C or backtrack does not work... but the output so far is:

```
Starting program: C:\Program Files (x86)\ownCloud\owncloud.exe
[New Thread 11816.0xe30]
warning: `C:\WINDOWS\SYSTEM32\ntdll.dll': Shared library architecture i386:x86-6
4 is not compatible with target architecture i386.
warning: `C:\WINDOWS\SYSTEM32\wow64.dll': Shared library architecture i386:x86-6
4 is not compatible with target architecture i386.
warning: `C:\WINDOWS\system32\wow64win.dll': Shared library architecture i386:x8
6-64 is not compatible with target architecture i386.
warning: `C:\WINDOWS\system32\wow64cpu.dll': Shared library architecture i386:x8
6-64 is not compatible with target architecture i386.
warning: Could not load shared library symbols for WOW64_IMAGE_SECTION.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for WOW64_IMAGE_SECTION.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for NOT_AN_IMAGE.
Do you need "set solib-search-path" or "set sysroot"?
warning: Could not load shared library symbols for NOT_AN_IMAGE.
Do you need "set solib-search-path" or "set sysroot"?
[New Thread 11816.0x2e80]
warning: Could not find " "owncloud_crash_reporter" " in ../libexec or applicati
on path

warning: m_crashReporterChar:  owncloud_crash_reporter

[New Thread 11816.0x20e4]
[New Thread 11816.0x2db8]
[New Thread 11816.0x1100]
[New Thread 11816.0x2c4c]
[New Thread 11816.0xa9c]
[Thread 11816.0x2c4c exited with code 0]
[Thread 11816.0xa9c exited with code 0]
```

**Comment by GPSHansl** [comment]
@ckamm: 
sure this is the whole logfile.
No matter how often I kill and start it, the client just sits within the processlist, not bothering to open any window.
Something must have been changed since client 1.7.1.4382. This version is working (right now, BTW).
I'd suspect the explorer integration, but it makes no difference, turning it off or on when installing the newer versions.

**Comment by ckamm** [comment]
@sisu4u Too bad you couldn't interrupt the process and get a backtrace, thanks for trying!
@GPSHansl My next log line is about the updater. Does anything different happen if you add `skipUpdateCheck=true` to the `ownCloud` section of your config file (probably in `C:\Documents and Settings\<myuser>\Local Settings\Application Data\ownCloud\owncloud.cfg`)?

**Comment by ckamm** [comment]
@sisu4u @GPSHansl Could you check if C:\Documents and Settings\<myuser>\Local Settings\Application Data\ownCloud\owncloud.cfg.lock exists? Delete it if it does.

**Comment by sisu4u** [comment]
It did fix the problem! However the correct path is:
C:\Users\<USER>\AppData\Local\ownCloud\owncloud.cfg.lock

Thanks for your help!

**Comment by ckamm** [comment]
@sisu4u That's excellent! Could I ask you to recreate the file and then try to start a client nightly build >=2015-05-09? There's a patch there that should automatically delete the file on startup. http://download.owncloud.com/desktop/daily/

**Comment by sisu4u** [comment]
@ckamm yes I used 5069 and it worked perfectly. It deleted the file on startup and then the tray icon symbol and the GUI was loaded. Thanks again for your help! :)

**Comment by ckamm** [comment]
@sisu4u Thanks for testing!
