### ISSUE TITLE
parsing href in propfind response is fragile (1.8)

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3176]
This does not affect version 1.7. This affects version 1.8. This may lead to data loss.

The parsing of href in propfind responses is fragile and does not handle the port/domain correctly.

I have a test server which returns these hrefs mixed in the PROPFIND Depth=1 response and the client is confused (and thinks the files do not exists and deletes them). 

href=http://localhost/remote.php/webdav
href=http://localhost.localdomain:80/remote.php/webdav/minitest

However these hrefs relate to the same host and port. If you suspect the href does not come from the host you are talking to (for example, DNS alias changed or entry in /etc/hosts changed) you should stop syncing this folder (but not assume that the item is deleted). It would be smarter to add these kind of consistency checks before taking any actions.

**Comment by moscicki** [comment]
http://en.wikipedia.org/wiki/Defensive_programming : this is especially important for a piece of software such as a sync client.

**Comment by guruz** [comment]
For the record, we do
```
            if (name == QLatin1String("href")) {
                currentHref = QUrl::fromPercentEncoding(reader.readElementText().toUtf8());
            } 
```

@moscicki Are you saying a regular(!!) ownCloud server could make the sync break?

**Comment by moscicki** [comment]
This is against my test server that is supposed to emulate different error conditions (following our discussion at #3145). Now, I am not sure what happens with the regular owncloud server but the client code should be able to handle such things gracefully. Please also check what happens against the regular server if you have the port number in the hrefs. I am not sure if this is handled correctly in 1.8.

**Comment by dragotin** [comment]
More code to come in 1.8.2

**Comment by guruz** [comment]
@dragotin review plz
@moscicki can you try your test server again? it should now fail the discovery for that dir.

**Comment by moscicki** [comment]
I will try later. For reference: https://github.com/cernbox/pywebdav/blob/master/pywebdav/server/fshandler.py#L109
