### ISSUE TITLE
All modified files generate conflicts

### ISSUE THREAD

**Issue by cortopy** [owncloud/client#3178]
***
EDIT: I just run it again now and behaviour is even weirder. Not all modified files generate conflict. A small number still sync ok. Conflicts generate on all the ones which have been generating conflicts and also some of the newly modified files.
***

I don't know if it's related, but after upgrading my laptop to Ubuntu 15.04 my sync client has stopped working properly. When I change a file locally, sync considers there is a conflict and reverts back to old version and creates new conflict file with all my changes. 

As reported below, problems seem to be with DB connection (server has not been upgraded and config has not changed), so it may just be a coincidence that this happens when I upgraded laptop. 

Things I've tried with no success:

- Scan all files using console.php
- Delete files conflicting in server with browser, save files again locally so that they are newer than the delete action, and sync again

This is my issue:

### Steps to reproduce
1. Modify a file
2. Use desktop sync 
3. Desktop sync only generates conflicts

### Expected behaviour
Sync should recognise that there have been changes locally. I'm the only user, so there is no conflict of multiple users changing shared files or anything of the kind. 

### Actual behaviour
Instead of syncing changes, conflict files are created. 
However, new files are uploaded as they should.

### Client configuration
**Operating system**:
Ubuntu 15.04

**Client version**:
1.8

### Server configuration
**Operating system**:
Ubuntu 14.10 

**Web server:**
Nginx

**Database:**
Percona

**PHP version:**
5.6

**ownCloud version:** (see ownCloud admin page)
8.0.2

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**
Activity, Deleted Files, File Locking, Versions

**The content of config/config.php:**

```
<?php
$CONFIG = array (
 *****
  'trusted_domains' => 
  array (
    *****
  ),
  'datadirectory' => '/home/owncloud/data',
  'overwrite.cli.url' => ****
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => ****
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' =>****
  'dbpassword' =>******
  'installed' => true,
  'logtimezone' => 'Europe/London',
  'logfile' => '/var/log/owncloud/owncloud.log',
  'loglevel' => 2,
  'forcessl' => true,
  'forceSSLforSubdomains' => true,
);
```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

**Are you using an external user-backend, if yes which one:** no

#### Web server error log
This is a large log, I'll give one example of file that generated conflict (could provide more details if required)

```
IP.ADD.RE.SS - user [29/Apr/2015:09:46:09 +0100] "GET /owncloud/remote.php/webdav/file.file HTTP/1.1" 200 1973 "-" "Mozilla/5.0 (Linux) mirall/1.8.0"
```

#### ownCloud log (data/owncloud.log)
Again this is a large file. For what I can see, there are quite a few problems with connecting to DB. 

So for example, there are a number of:
```
{"reqId":"***","remoteAddr":"***","app":"remote","message":"An exception occured in driver: SQLSTATE[HY000] [2002] Can't connect to local MySQL server through socket '\/var\/run\/mysqld\/mysqld.sock' (2)","level":4,"time":"2015-04-28T21:44:49+01:00"}
```
And similarly

```
{"reqId":"******","remoteAddr":"******","app":"index","message":"Exception: {\"Message\":\"An exception occurred while executing 'SELECT `fileid` FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ?' with params [\\\"1\\\", \\\"*****\\\"]:\\n\\nSQLSTATE[HY000]: General error: 2006 MySQL server has gone away\",
```

I should also mention that the problem was initially bigger, as there were a number of files without E tags. Switiching off gzip compression in nginx seemed to do the trick. Not sure if it's related

**Comment by dragotin** [comment]
As you can see in the logfiles your sever is not able to connect to the mysql database for some reasons.

In that case, the server should detect that and return a 503 to indicate temporar unavailability. Please check if there is already an issue in the server issue tracker, and add one if not. Thanks!

**Comment by cortopy** [comment]
@dragotin But it's not a problem with the db. New files are uploaded without a problem and some (although not many) of the modified files are sync ok too. 

Do you mean this is an issue for the server github page?

**Comment by RealRancor** [comment]
Hi,

> Do you mean this is an issue for the server github page?

i think that is what dragotin is trying to say. There is a similar post which could be related: https://github.com/owncloud/core/issues/15407
