### ISSUE TITLE
Win client connection terminated

### ISSUE THREAD

**Issue by andre-spindler** [owncloud/client#3179]
Hello,

for now about two weeks I have some strange connection problems with the windows client.

The setting:
Server is Community edition 7.0.5, running on php 5.4.33; max_execution_time is 43200 (12h), site is secured with ssl, access via https
I use the owncloud instance to sync data between two computers ans as online backup storage.
On computer 1, my desktop, owncloud client 1.8.0 is running on Win7 pro 64bit. All is fine here. No missing files, no connection errors, no timeouts.
On computer 2, the notebook, there is Win8.1 64bit running. Client was first 1.8.0, is now 1.8.1-5006.rc1. Account has been removed, old client installation completely removed (including data dir), new rc version installed, account setup and then one directory included.

But I always get the same errors on the notebook:
Client is syncing files, and then the connection is terminated. I cannot say that this is after the same time or data size. Client displays error message, then continues to check both remote and local directories and then continues syncing. As the same files which have benn aborted before are now successfully synced, this seems for me not to be related to some access restrictions or critical content of the files. Also both sirections are affected, up- and downloads.
Copying large files directly from one computer to another using the common wlan, there is no one single error, even when there are some gb of files. Seems like wlan is working fine. Also there are no internet connection problems, as on computer 1 has no errors in the owncloud client, and uses the same connection as computer 2 when erros occur here.

This are some snippets from the local log file:
[...]16:49:41|2445|Fotos/Italien 2010/100_1598.JPG|INST_NEW|Down|1281365092|54465c6f8d2f9|1435474|000846295246701675ce6|4||0|0|0|||INST_NONE|
16:49:41|2243|Fotos/Italien 2010/100_1601.JPG|INST_NEW|Down|1281375954|54465c6f86d14|1062786|000846015246701675ce6|4||0|0|0|||INST_NONE|
|0|Fotos/Italien 2010/100_1602.JPG|INST_NEW|Down|1281375964|54465c6f89b9f|730637|000846175246701675ce6|1|Operation abgebrochen|0|0|0|||INST_NONE|
|0|Fotos/Italien 2010/100_1603.JPG|INST_NEW|Down|1281375988|54465c6f865b0|1164586|000845985246701675ce6|1|Verbindung beendet|0|0|0|||INST_NONE|
|0|Fotos/Italien 2010/100_1604.JPG|INST_NEW|Down|1281376002|54465c6f87e45|743511|000846085246701675ce6|0||0|0|0|||INST_NONE|
|0|Fotos/Italien 2010/100_1606.JPG|INST_NEW|Down|1281516080|54465c6f86f88|918175|000846025246701675ce6|0||0|0|0|||INST_NONE|
[...]
|0|snapshot.png|INST_NEW|Down|1366417671|54465c6f128d5|2480245|000844005246701675ce6|0||0|0|0|||INST_NONE|
|0|typo3wallpaper.bmp|INST_NEW|Down|1156543256|54465c6f174e9|2414646|000844295246701675ce6|0||0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-05-01T18:50:06 until 2015-05-01T18:50:32 (26267 msec)
16:50:01|1186|Fotos/Italien 2010/100_1602.JPG|INST_NEW|Down|1281375964|54465c6f89b9f|730637|000846175246701675ce6|4||0|0|0|||INST_NONE|
16:50:01|1879|Fotos/Italien 2010/100_1603.JPG|INST_NEW|Down|1281375988|54465c6f865b0|1164586|000845985246701675ce6|4||0|0|0|||INST_NONE|
16:50:01|1561|Fotos/Italien 2010/100_1604.JPG|INST_NEW|Down|1281376002|54465c6f87e45|743511|000846085246701675ce6|4||0|0|0|||INST_NONE|
[...]
16:50:11|1633|Fotos/Italien 2010/100_1626.JPG|INST_NEW|Down|1281532428|54465c6f860bc|1173090|000845965246701675ce6|4||0|0|0|||INST_NONE|
|0|Fotos/Italien 2010/100_1627.JPG|INST_NEW|Down|1281532522|54465c6f85180|1449076|000845905246701675ce6|1|Operation abgebrochen|0|0|0|||INST_NONE|
16:50:13|3275|Fotos/Italien 2010/100_1628.JPG|INST_NEW|Down|1281532540|54465c6f88c9e|1659297|000846135246701675ce6|4||0|0|0|||INST_NONE|
16:50:13|3017|Fotos/Italien 2010/100_1629.JPG|INST_NEW|Down|1281532696|54465c6f87bd1|1755562|000846075246701675ce6|4||0|0|0|||INST_NONE|
|0|Fotos/Italien 2010/100_1630.JPG|INST_NEW|Down|1281532724|54465c6f8aef4|1668772|000846225246701675ce6|1|Verbindung beendet|0|0|0|||INST_NONE|
|0|Fotos/Italien 2010/100_1631.JPG|INST_NEW|Down|1281532734|54465c6f8795c|1411430|000846065246701675ce6|0||0|0|0|||INST_NONE|
[...]
error_log of the apache has no entries here.

**Comment by v0tary** [comment]
Check two things:

1) Apache KeepAlive On - We had the same issue on our systems and with a little research we found that Apache was terminating the connection and causing the client to constantly timeout when synchronizing a large set of files. By enabling this we are telling Apache to allow the use of KeepAlives.

2) Once we did this, the RAM usage went up a little. We decided to double the RAM the server had physically, and things are a lot smoother after this.

**Comment by Mr-Aloof** [comment]
on the server side there is no error.
Apache KeepAlive is On
the way operations work without any errors, but getting a larget set of files every stop about 2 minutes

**Comment by drdotti** [comment]
Same here, two notebooks Win7pro, both client 1.8.0, everthing is fine, one client autoupdates to client 1.8.1 (build 5050) and this one shows exactly the same problems as described further above.

**Comment by guruz** [comment]
Can you guys try this nightly build? 
http://download.owncloud.com/desktop/daily/ownCloud-1.8.2.5135-nightly20150602-setup.exe

It contains an updated Qt with fixes for the "Connection: closed"

FYI @dragotin

**Comment by Dianafg76** [comment]
@guruz I tested this issue, with the Desktop v ownCloud-1.8.2.5153-nightly20150605-setup.exe I can't reproduce the error "Connection: closed", maybe it is resolved
