### ISSUE TITLE
Conflict files and recurrent download of txt files

### ISSUE THREAD

**Issue by Jas2Ma** [owncloud/client#3180]
This bug is driving me crazy since some time and I found plenty of bug reports here, which seem to be very similar (which are closed reopend closed for a while). Since I can't decide which bug it might be, I'm opening a new bugreport.

For me, this Bug is only connected to *.txt files and initally was found for notes stored in Notes folder (from android app). But I now recognize it on all shared folders.

### Expected behaviour
Files are downloaded once - on change, they are uploaded.

### Actual behaviour
Files are downloaded on every sync. Changes at a different client then the one, which initially uploaded the file, leads to conflicts.
Files can only be updated by moving them in a different directory at the client, deleting the files in the web-interface, moving them back into sync-directory at the client.

### Steps to reproduce
It's only occurring at my .txt files. I just edit the file at a second client. Can't find anything special, sometimes it get's uploaded for a time, then the bug occurs.

### Server configuration
Operating system:
Ubuntu 14.04 LTS
Running in a docker environment.

Web server: 
 nginx/1.4.6 (Ubuntu)

Database:
mysql  Ver 15.1 Distrib 10.0.15-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

PHP version:
PHP 5.5.9-1ubuntu4.5 (cli) (built: Oct 29 2014 11:59:10)

ownCloud version:
atm 8.0.2, but I had this issue the versions before, too.

Storage backend:
what is meant by this? files are stored at a ext4 formated hdd.

### Client configuration
Client version:
All 1.8.0, but occurred since some 1.7.*

Operating system:
Linux Mint 17.1 Cinnamon 64-bit
Windows 8 64-bit

OS language:
German/English

Installation path of client:
'which owncloud' give no result.

### Logs

See https://gist.github.com/Jas2Ma/22024d6ef681cb5440a3

**Comment by Dianafg76** [comment]
Could try the with the latest client version, v 1.8.1?
You may download it from: download.owncloud.com/desktop/daily/ownCloud-1.8.1.2326-nightly20150504.pkg
Thanks!

**Comment by Jas2Ma** [comment]
Is there a guide how to install .pkg file on linux/windows? For me it seems to be an apple file format.

**Comment by PeterPablo** [comment]
@Jas2Ma, please look here for the current testing version:
https://owncloud.org/install/#testing-development

There you find links for all major operating systems.

**Comment by Jas2Ma** [comment]
I installed 1.8.1rc2 on Linux Mint.
The file had a conflict before installing new client. After installation it checked all directories, and downloaded 150 files again (mainly Dropbox share).

I changed the file (conflict file existed before) - no upload (client says "target file exists")
I deleted conflict file - client renamed file, downloaded old version of file from server (22:50:44)
next operation (22:51:10): Error downloading file "none of the specified the ETags matched."
I changed the files - no upload (client says "target file exists", because conflict file was not deleted).

So I don't think that this release candidate changed anything about my problem.

**Comment by Jas2Ma** [comment]
I now installed the new client on all devices, no recognizable improvement. Please tell me, if I can help you solving this. It's really annoying.

**Comment by guruz** [comment]
> But I now recognize it on all shared folders.

Are you saying it only happens for .txt files in shared folders, not in regular folders?

CC @PVince81

**Comment by PVince81** [comment]
Have you tried with 8.0.4 ? There was a fix for Dropbox recently.

**Comment by Jas2Ma** [comment]
@guruz 

With shared folders I mean folders which are synchronised on multiple devices, specificly files which are synchronised on linux and windows both or windows only.
I have a certain believe, that this error is connected to the way windows editor is saving txt-files, but I don't know how to prove that.

**Comment by Jas2Ma** [comment]
@PVince81 Dropbox has nothing to do with my error.

**Comment by guruz** [comment]
@Jas2Ma Please try 8.0.4, else we can not help you further. Thanks.

**Comment by Jas2Ma** [comment]
@guruz I don't want to be harsh, but this isn't the first time I'm told to update to the latest version. Actually you didn't help me yet... I will update my server and clients from time to time, that's what I can do without you telling me.
But thanks for you interest in the persistence of this bug.
I will write here as soon as I updated my server.

**Comment by Jas2Ma** [comment]
And please remove the "Needs info" label unless you tell me, what kind of information you need.

**Comment by Jas2Ma** [comment]
I now updated to 8.1.0 and this issue seams to be solved.
Thanks to all of you!

**Comment by guruz** [comment]
@Jas2Ma Great :) nice to hear
