### ISSUE TITLE
[Sharing link] The share link wizard is open more than once with the same file/folder

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3184]
### Steps to reproduce
1. Open your ownCloud desktop client 
2. Go to Open Folder "ownCloud"
3. Create a  new folder, called a
4. Right click on the folder a
5. Select share with ownCloud

### Expected behaviour
It would not have to open several windows at once

### Actual behaviour
You can share the same folder as often as you like. And you can have multiple windows open at once
![screen shot 2015-05-04 at 14 46 59](https://cloud.githubusercontent.com/assets/12032058/7453707/84c7911e-f26c-11e4-8028-98b084c3a484.png)

###Version Desktop
Version 1.8.1.2326-nightly20150504 

Web server:
{"installed":true,"maintenance":false,"version":"8.0.3.4","versionstring":"8.0.3","edition":"Enterprise"}
Checked with a server with permanent redirection
LDAP and Encryption enable

**Comment by Dianafg76** [comment]
Also happens in version 2.1.0 (build 2944)

**Comment by ckamm** [comment]
@Dianafg76 Is the problem that you click "Share with ownCloud..." once and multiple windows open up? Or is this report about the ability to open several sharing windows for the same folder by clicking "Share with ownCloud..." several times?

**Comment by Dianafg76** [comment]
@ckamm You can open multiple windows "Share with owncloud" on the same folder

**Comment by davitol** [comment]
:+1: WFM in Version 2.1.1-nightly20160122 (build 3053)
