### ISSUE TITLE
owncloud- client Linux upgraded to 1.8.1rc2 automatically, wrong repository

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#3187]
Hi, I was updating my owncloud client with apt-get update, apt-get upgrade.

```
Get:1 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/testing/xUbuntu_14.04/  owncloud-client-l10n 1.8.1~rc2-0 [270 kB]
Get:2 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/testing/xUbuntu_14.04/  owncloud-client 1.8.1~rc2-0 [840 kB]
Get:3 http://download.opensuse.org/repositories/isv:/ownCloud:/community:/testing/xUbuntu_14.04/  libowncloudsync0 1.8.1~rc2-0 [383 kB]
Fetched 1.493 kB in 1s (1.366 kB/s)   
```

I checked my repositories:

```
deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.04/ /
```
Funny, isn't it?

Now I have a nice rc2 running

@jnweiger @MorrisJobke

**Comment by danimo** [comment]
You also must have community/testing registered (probably for the server). That one takes precedence because it has a later version.

**Comment by cdamken** [comment]
Thanks @danimo What I meant with funny is that I didn't selected the testing before and today after the upgrade was checked.
