### ISSUE TITLE
Desk Top Client share by public link error " OCS API error code : 400"

### ISSUE THREAD

**Issue by iliyasbasir** [owncloud/client#3188]
#### Expected behavior
Able to share link 

### Actual behavior 
Can not share link " OCS API error code : 400"

### Step to reproduce
 1) Customer create folder oC web console
 2) Folder sync via desk top client 
 3) Folder placed at designated location by Desktop client at customer PC
 4) Now, customer go at folder location and by rightclisk oin folder try share folder via link 
 5) at setting password get error "OCS API error code : 400"

Note : Screen shot attached

### Server configuration
Web (1 server): 
- Operating system - Red Hat Enterprise Linux Server 7.1 (Maipo)
- Web server - Apache 2.4.6 (Red Hat Enterprise Linux)
- PHP version - 5.4.16
- ownCloud version - 8.0.2

Backend (1 server):
- Operating system - Red Hat Enterprise Linux Server 7.1 (Maipo)
- Database - 5.5.41-MariaDB MariaDB Server (Red Hat Enterprise Linux)
- Storage backend - 2TB xfs mount

Client:
- Operating system - Windows 7 Enterprise 64 bit
- OS language - English(US)
- Installation path of client - c:\Program Files (x86)\ownCloud\
- Client version - 1.8.0 (build 4893)
- Client configuration - see link
- Client log- see link

### Log : 
Log at S3 /Shared/owncloud/support/github-issues/client/3188

ScreenShot:
![images _1](https://cloud.githubusercontent.com/assets/10195796/7462561/825118ec-f280-11e4-94a3-18c6fb15c59a.png)

![image _2](https://cloud.githubusercontent.com/assets/10195796/7462571/8d9764c2-f280-11e4-8cb3-e5dd11c80767.PNG)

![image _3](https://cloud.githubusercontent.com/assets/10195796/7462578/968e4b7c-f280-11e4-8db1-bbc1012b466d.png)

![1](https://cloud.githubusercontent.com/assets/10195796/7462580/9c9c57ca-f280-11e4-9b87-5e2dfb402516.png)

![2](https://cloud.githubusercontent.com/assets/10195796/7462583/a22aebf2-f280-11e4-8b92-1e2596ad5032.png)

**Comment by ckamm** [comment]
This is very likely #3204: The sharing API does not work when one combines the firewall app with a PHP version older than 5.6.0. A fix for the server is in the works, see owncloud/firewall#95. Until then you can either disable the firewall app if you don't use it or update the PHP version, sorry for the inconvenience.

**Comment by bboule** [comment]
@iliyasbasir can you confirm that the firewall app is enabled and or can you work to upgrade to php 5.6?
