### ISSUE TITLE
[Sharing Link] The warning "Choose a password for the...." is cut

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3189]
### Steps to reproduce
1. Open your ownCloud desktop client 
2. Go to Open Folder "ownCloud"
3. Right click on the folder 1
4. Select share with ownCloud

### Expected behaviour
All the warning message should appear so that the user knows why he can't copy the link

### Actual behaviour
The warning message: "Choose a password for the...." is cut

![screen shot 2015-05-05 at 08 39 58](https://cloud.githubusercontent.com/assets/12032058/7467928/623e5240-f302-11e4-9602-cde5790b868c.png)

###Version Desktop
Version 1.8.1.2326-nightly20150504 MAC and WINDOWS

Web server:
{"installed":true,"maintenance":false,"version":"8.0.3.4","versionstring":"8.0.3","edition":"Enterprise"}
Checked with a server with permanent redirection
LDAP and Encryption enable

**Comment by guruz** [comment]
FYI @jancborchardt

**Comment by jancborchardt** [comment]
It’s too verbose. Should just say »Password«.

Also, where is the checkbox to enable the password? I assume this is on a server with password being forced to on? In which case it should show the »Password protect« label including the checkbox (checked and disabled) – _not_ just hide it. @guruz

**Comment by jancborchardt** [comment]
(Also, where’s the link next to the »Copy link« button?)

**Comment by Dianafg76** [comment]
I try again and everything is fine, so close the Issue
