### ISSUE TITLE
OC 7.0.4 and client 1.8.0 - connection timeout with big files

### ISSUE THREAD

**Issue by ngarafol** [owncloud/client#3191]
Hi,

I have trouble downloading 10GB file with client 1.8.0. I can upload it with web interface without problem, but client gets timeout trying to download it.

owncloud.log shows only GET request for file.
apache error log is empty.
owncloudsync log shows:

#=#=#=# Syncrun started 2015-05-05T09:04:28 until 2015-05-05T09:09:28 (300316 msec)
|0|10gb.out|INST_NEW|Down|1430743921|55476b711a14b|10485760000|02881415oc4f27b14845|1|Connection Timeout|0|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-05-05T09:10:17 until 2015-05-05T09:15:17 (300243 msec)
|0|10gb.out|INST_NEW|Down|1430743921|55476b711a14b|10485760000|02881415oc4f27b14845|1|Connection Timeout|0|0|0|||INST_NONE|

**Comment by guruz** [comment]
Can you check your local file system if there is a temporary file in that specific folder with (with a name similar to the 10gb.out)? If yes how big is it?

(Note the file might be hidden)

**Comment by ngarafol** [comment]
Yes  there is temporary file but size is 0.

**Comment by guruz** [comment]
If you exit the client, delete the file and restart the client it does it work?

**Comment by ngarafol** [comment]
Seems my problems are related to haproxy or apache. In test environment big files work fine. With haproxy setup, on big files apache starts to leak memory and thats why download never starts and client fails to download file. 

OS is centos 6, http 2.2.15-31, haproxy version 1.4.21. Any suggestions welcome. Haproxy responds with http 504 on big files...

**Comment by dragotin** [comment]
@felixboehm do you have an idea about haproxy?

**Comment by guruz** [comment]
If @felixboehm has no quick input I suggest to try forums/Google/core-bugtracker..

**Comment by guruz** [comment]
Does haproxy try to do some crazy caching?

**Comment by ngarafol** [comment]
If I strace httpd process (haproxy setup) there is about 2gb of memory in use, cpu 99% and strace shows read calls in bulk, and some brk calls. So no write calls visible. On test setup (no haproxy, works fine) there is read-write alternating calls on downloading file.

**Comment by felixboehm** [comment]
504 --> apache behind the haproxy throws a timeout
should not be related to haproxy

**Comment by ngarafol** [comment]
Could someone verify that it is related to sparse files? Try dd line above and upload and then download with apache. 
When using REAL data, there is no problem.

**Comment by dragotin** [comment]
Sorry, but that rather sounds like a setup problem than like a client bug. Closing for now, let us know if you have further findings.

**Comment by dragotin** [comment]
hrm, yes.
