### ISSUE TITLE
Creation time (CTIME) of a file is not synchronized

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#3192]
### Expected behaviour

The files should keep the creation time (CTIME) to manage when was it created between all synced clients
### Actual behaviour

Creation time (CTIME) is lost after syncing and modifications between different clients.
### Steps to reproduce
1. Create a file
2. Sync the file in other computers
3. Do some modifications
4. resync the file
5. CTIME is lost.

@MorrisJobke @dragotin

**Comment by guruz** [comment]
(The creation time was never every synced with ownCloud.)

**Comment by dragotin** [comment]
No, it was not yet, but maybe it makes sense? Same as extended file attributes?!

**Comment by MTRichards** [comment]
Ok, so a feature request then that the create time is synced across devices too. Got it.
When we add retention, the create time should be updated too - good to know.

**Comment by ogoffart** [comment]
the "ctime" is not the "creation time",  it is the "change time".

Anyway, this is part of the metadata, like the execute bit: https://github.com/owncloud/client/issues/3199

if the server had a concept of creation time, it would make sense to synchronize it.

**Comment by guruz** [comment]
https://en.wikipedia.org/wiki/Stat_(system_call)#ctime
