### ISSUE TITLE
[Legacy Propagator] Location response header in the MOVE wrongly interpreted by post_send_hook

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3194]
This is a bug that only affects the neon-based code (so 1.7 clients and possibly 1.8 legacy propagator). 

The post_send_hook() logic is broken because it assumes that if Location header is present in the response then the response is a redirect. As a result a legitimate and successful MOVE (201) is reported as "Neon error was 9" which is "redirect". The propagator code is then not robust (which is a problem on it own) and starts deleting files or moving files back to the original position (depending on the user actions).

Webdav is vague about Location header in the response to MOVE but http://www.webdav.org/specs/rfc4918.html#METHOD_MOVE gives an example of this (9.9.5 Example - MOVE of a Non-Collection). The client should definitely be robust to handle such nuances correctly.

I would think that the legacy propagator should be abandoned completely if such things exist in the code-base.

**Comment by guruz** [comment]
> I would think that the legacy propagator should be abandoned completely if such things exist in the code-base.

That's definitely what we want but #2558 is making trouble
(The new propagator only supports bandwidth limiting from a certain Qt 5 version..

**Comment by moscicki** [comment]
OK, if impossible to remove legacy propagator then it should be fixed in the interim ;-)

**Comment by guruz** [comment]
@MTRichards OK to remove the support for bandwidth limiting in the Qt4 based Linux deliveries we have?

**Comment by dragotin** [comment]
@MTRichards yes, please. Also, we need to talk about how we can drop support for Qt4.

**Comment by guruz** [comment]
Pending OK to merge..
https://github.com/owncloud/client/issues/2360#issuecomment-149615769

**Comment by guruz** [comment]
kill_legacy_propagator is merged
