### ISSUE TITLE
[Sharin Link] The button Copy Link is activated

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3195]
### Steps to reproduce
1. Open your ownCloud desktop client
2. Go to Open Folder "ownCloud"
3. Create a new Folder, called b
3. Right click on the folder b
4. Select share with ownCloud

### Expected behaviour
The button Copy Link must not be active until you click on it

### Actual behaviour
The button Copy Link is activated 
![screen shot 2015-05-05 at 13 53 17](https://cloud.githubusercontent.com/assets/12032058/7472013/37971af0-f32e-11e4-969d-ab9433f03f03.png)

###Version Desktop
Version 1.8.1.2329-nightly20150505 MAC 

Web server:
{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Comment by dragotin** [comment]
Well, as soon as the link is there, the button should be active. Looks like works as designed to me.
