### ISSUE TITLE
Is there a known issue with ownCloud client 4893 and Windows Server 2003?

### ISSUE THREAD

**Issue by aleishman01** [owncloud/client#3196]
We have been having random crashes of the client on our 2003 Server. The client does not recover and needs to be restarted. We have heavy volume (10-20 GB daily). This does not happen on our Windows 7 or 8.1 machines.

I tried enabling logging but the log files quickly grow to well over 100GB within an hour.  I looked for similar issues in GitHub but could not find one.

**Comment by danimo** [comment]
@aleishman01 The client does not officially support Windows Server. What's your use case for running it on a server? That said, Windows Server 2003 SP1 (I assume you have SP1 installed?) should be identical to XP SP3, which we support.

**Comment by aleishman01** [comment]
We use 2003 Server because we have 2003 server. I'm aware that we "should" replace these servers but that is not my decision, sadly. I will see if I can move the client to a 2008 server.  Thanks for your response.

**Comment by danimo** [comment]
@aleishman01 The question was more: Why do you use the client on a server? Is this for use with terminal services?

**Comment by danimo** [comment]
@aleishman01 btw: You are mentioning a large volume: Is the client on the server possibly syncing more than other clients? Or uploading more while the others just download? 1.8.0 had some unfortunate memory overhead that has been migitated in 1.8.1 (rc2 is currently available for testing at https://owncloud.org/install/#testing). //cc @guruz @ogoffart

**Comment by aleishman01** [comment]
Yes, the server is syncing as much as all the other clients combined (9 "in the field" clients). The server only downloads and deletes.  We get folders of images from 9 different locations around the nation to our Linux ownCloud Server. the Windows 2003 server pulls the images from the ownCloud server, processes them and then deletes them causing a cascading delete back to the clients.

I agree that it should be on a better machine but my hands are tied.

I have been considering running the daily build version to see if that would help.

**Comment by danimo** [comment]
Please try with rc2. I would really be surprised if this is a Windows specific problem.

**Comment by aleishman01** [comment]
I will do that and let you know how it goes. It could take a day before I'm sure it's working or not.

**Comment by aleishman01** [comment]
So far, Desktop Client 1.8.1 RC2 seems to be more stable on our Windows 2003 server. No problems with disconnects yet.  Thanks for your help.

**Comment by danimo** [comment]
Closing then. please reopen if you find more problems.
