### ISSUE TITLE
When you have shared the file / folder, change the icon to know that this shared, In the DESKTOP Client

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3197]
### Steps to reproduce
1. Open your ownCloud desktop client
2. Go to Open Folder "ownCloud"
3. Create a new Folder, called c
4. Right click on the folder c
5. Select share with ownCloud
6. Select one of the options
7. Click in "Close"

### Expected behaviour
When you have shared the file / folder, change the icon to know that this shared.
If I look ownCloud web Client, we know that folders are shared by the icon

### Actual behaviour
The file / folder has been shared , but the folder/file icon has not changed, it is the same for sync

###Version Desktop
Version 1.8.1.2329-nightly20150505 MAC, WINDOWS

Web server:
{"installed":true,"maintenance":false,"version":"8.1.0.4","versionstring":"8.1 alpha 3","edition":""}

**Comment by stonerl** [comment]
Isn't this a dup of #3043?

**Comment by Dianafg76** [comment]
Hey, not really on #3043 the icon shown is the one that it's a shared data with you. However, the one that I am mentioned to is that you have shared the data by link

**Comment by stonerl** [comment]
That's mentioned in #3043:
"...shared with other users or by link are not indicated..."

**Comment by Dianafg76** [comment]
Thanks @stonerl  lets follow its status on
