### ISSUE TITLE
Account and folder show 'connected' when service is unavailable

### ISSUE THREAD

**Issue by rperezb** [owncloud/client#3200]
STEPS TO REPRODUCE:
1.- Using the mac client, 1.8.0
2.- Connect to your ownCloud server
3.- The server is set to maintenance:mode --on

CURRENT BEHAVIOUR:
It is possible to access to your data
The desktop clients remain in "syncing" status on the wizard and on the laptop bar the error icon is shown
It is possible to modify a document and the document is shown as sycn

### Logs desktop
OCC::AbstractNetworkJob::slotFinished() 403 "Error downloading https://docker.oc.solidgear.es:50043/remote.php/webdav/ - server replied: Service Unavailable"
05-05 16:34:58:230 0x7ff6bbc24670 OCC::PropfindJob::finished: Quota request *not* successful, http result code is 503 ""

**Comment by rperezb** [comment]
cc/ @jnfrmarks

**Comment by ckamm** [comment]
@rperezb Did you see the account going to the "ServerMaintenance" state in your logs? What should be happening is that the client shows the signed out state and doesn't bother the user until the maintenance mode is switched off again.

**Comment by ckamm** [comment]
@rperezb Your input would be appreciated. :)

**Comment by ckamm** [comment]
I've tested this and it looks like the icon stays 'connected' on master.

**Comment by ckamm** [comment]
The tray icon should now show the disconnected icon in 'service not available' state.

**Comment by Dianafg76** [comment]
@ckamm 

Yes, the server shows: 
`07-03 14:25:47:291 0x5591098 OCC::CheckServerJob::finished: status.php returns:  QMap(("edition", QVariant(QString, "Enterprise") ) ( "installed" ,  QVariant(bool, true) ) ( "maintenance" ,  QVariant(bool, true) ) ( "version" ,  QVariant(QString, "8.1.0.8") ) ( "versionstring" ,  QVariant(QString, "8.1 RC2") ) )    0  Reply:  QNetworkReplyHttpImpl(0x737d3b8)`

(...)

```07-03 14:26:51:454 0x6f0b908 unknown: void QHttpNetworkConnectionChannel::close() QSslSocket(0x7382818) 0 QObject(0x0) 
07-03 14:26:51:454 0x6f0b908 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7382818) QObject(0x0)  0 false 3 16
07-03 14:26:51:457 0x5591098 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 403 "Error downloading https://docker.oc.solidgear.es:51102/remote.php/webdav/ - server replied: Service Unavailable"


07-03 14:26:51:458 0x5591098 OCC::FolderMan::slotAccountStateChanged: Account "diana@docker.oc.solidgear.es" disconnected, terminating or descheduling sync folders
07-03 14:26:51:458 0x5591098 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 503 ""
07-03 14:27:11:743 0x5591098 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (No se encontró el proceso especificado.)
07-03 14:27:11:745 0x5591098 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

07-03 14:27:11:746 0x5591098 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available``

Checked with the version2.0.0 build 5234

THe folder status is syncing, it would be great to have an error message, don't it?

On the other hand, if you modify a file, after saving the changes the file is shown as synced, when this is not true..

**Comment by rperezb** [comment]
@ckamm sorry for the delay :S
I have been with Diana checking it, anything you need,...reading

**Comment by ckamm** [comment]
@Dianafg76 What should be happening is this:
* When the server switches to maintenance and the client isn't syncing -> account goes offline, no further syncs are scheduled
* When the server switches to maintenance during a sync -> sync aborts, account goes offline etc.

It sounds like you tested the second case but I didn't understand what exactly happened then.

**Comment by rperezb** [comment]
@ckamm the thing is that the the desktop client shows the "sycn" mode, this is the icon shown.

If i understand correctly, it is expected to show the offline icon, is this right?

**Comment by ckamm** [comment]
@rperezb Do you mean the overall tray icon or the folder icon in the account settings dialog? I only fixed the folder icons today (ae69ff032b4d7a9faba5ba63e1eea66820dd23e7).

**Comment by ckamm** [comment]
@Dianafg76 @rperezb Could you re-test if you meant the folder icons?

**Comment by Dianafg76** [comment]
I test this issue, and is working fine.
I close this issue
