### ISSUE TITLE
[Sharing Link] Error code: 400 when select the Password protect and write the password

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3204]
### Steps to reproduce
1. Open your DESKTOP client
2. Go to Open Folder "ownCloud" 
3. Create a new folder, called sync folder
4. Right click on the folder sync folder
5. Select share with ownCloud
6. Click in "Password protect"
7. Write the password
8. Click on Enter

### Expected behaviour
The folder is shared

### Actual behaviour
It appears: "OCS API error code:400". 
![Uploading Screen Shot 2015-05-06 at 10.56.20.png…]()

But if you access to the Server Client the folder is shared

###Version Desktop
Version 1.8.1.2332-nightly20150506 MAC

Web server:
{"installed":true,"maintenance":false,"version":"8.0.3.4","versionstring":"8.0.3","edition":"Enterprise"}

**Comment by ckamm** [comment]
I couldn't reproduce it with server 8.0.2.0 and the 1.8 branch.

**Comment by ckamm** [comment]
The client sends
```
URL: http://server/ocs/v1.php/apps/files_sharing/api/v1/shares/32?format=json  
BODY: "password=foo"
```
and gets back
```
{"ocs":{"meta":{
  "status":"failure", "statuscode":400,
  "message":"Wrong or no update parameter given"},"data":[]}}
```

**Comment by ckamm** [comment]
@PVince81 @rullzer I get the same problem with a plain curl request: (against diana's 8.0.3.4)
```
$ curl -u user1 -X PUT 'http://SERVER/ocs/v1.php/apps/files_sharing/api/v1/shares/32?format=json' -d password=foo
{"ocs":{"meta":{"status":"failure","statuscode":400,"message":"Wrong or no update parameter given"},"data":[]}}
```

In fact it looks like `file_get_contents("php://input")` returns an empty string in `lib/private/api.php`...

**Comment by rullzer** [comment]
@ckamm what version of php are you running? 

There was an issue where php://input was read many times. This all goes well in php >= 5.5 but not in 5.4. But that never made it into any release as far as I know.

**Comment by ckamm** [comment]
@rullzer I think diana's server is using this version:
```
$ php --version
PHP 5.5.9-1ubuntu4.9 (cli) (built: Apr 17 2015 11:44:57)
```

And the problem is indeed about reading php://input multiple times. When I comment out all places where it might be read, it starts to work. ;)

What should be done about this?

**Comment by rullzer** [comment]
The ticket I was thinking of is https://github.com/owncloud/core/issues/14541
And it did not happen on php 5.6.. Do you have a possibility to check for that?

@LukasReschke @DeepDiver1975 seems like something that needs fixing in enterprise... if it is the same bug...

I'll make a clean install later to verify but my quick tests do not show it happening on the current master

**Comment by LukasReschke** [comment]
@Dianafg76 Please recheck in CE, if it is not reproducible then it is likely a bug in an EE application. If so provide us with a list of installed apps etc.

**Comment by LukasReschke** [comment]
Also try if disabling EE apps like Firewall etc. fixes this problem.

**Comment by ckamm** [comment]
@LukasReschke When I disable the Firewall app it starts to work correctly.

**Comment by LukasReschke** [comment]
@th3fallen THX

**Comment by LukasReschke** [comment]
My suspicion: The firewall instantiates a `IRequest`, the `IRequest` reads from `php://input` and then the API code tries to read manually again and fails hard as you can read only once from `php://input` in older versions than 5.6.

Probably easiest way to adjust the OCS OC_API handling…

**Comment by ckamm** [comment]
@LukasReschke After updating php to

    PHP 5.6.8-1+deb.sury.org~trusty+1 (cli) (built: May  2 2015 09:51:47)

it works even when the firewall app enabled.

**Comment by LukasReschke** [comment]
https://github.com/owncloud/firewall/blob/a6f95996ce9541709d79d1ab00acd7b3c4169443/lib/firewall.php#L76 calls https://github.com/owncloud/core/blob/df9de417674d176f884ddd92e30abac7f9aa9d65/lib/private/appframework/http/request.php#L269 which calls https://github.com/owncloud/core/blob/df9de417674d176f884ddd92e30abac7f9aa9d65/lib/private/appframework/http/request.php#L291-L309

Probably adjusting https://github.com/owncloud/core/blob/df9de417674d176f884ddd92e30abac7f9aa9d65/lib/private/api.php#L88-L92 to something like the following should work:

```php
if($_SERVER['REQUEST_METHOD'] == 'PUT') {
	$parameters['_put'] = \OC::$server->getRequest()->getParams();
} else if($_SERVER['REQUEST_METHOD'] == 'DELETE') {
	$parameters['_delete'] = \OC::$server->getRequest()->getParams();
}
```

@Dianafg76 Can you test this?

**Comment by LukasReschke** [comment]
PR is at https://github.com/owncloud/core/pull/16117

**Comment by ckamm** [comment]
@LukasReschke I've tested it with @Dianafg76's help with the old php and the change makes the OCS API work with the firewall app enabled.

**Comment by Dianafg76** [comment]
@LukasReschke, @ckamm, I tested with the php to >=5.6.0 and It not appears: "OCS API error code:400". 
But now It appears: "OCS API error code: 200"
![screen shot 2015-05-06 at 17 35 29](https://cloud.githubusercontent.com/assets/12032058/7496759/687f9014-f416-11e4-8aa6-a3809da7bcc6.png)

**Comment by LukasReschke** [comment]
200 seems expected as the sharing ID changes? Right, @rullzer? :see_no_evil:

**Comment by rullzer** [comment]
O that is a bug... 200 means everything is fine... so it should not display an error... I'll prepare a PR to fix that right away :P

**Comment by LukasReschke** [comment]
200 means everything is fine? – That should be 100 :see_no_evil: – OCS fun ;-)

**Comment by rullzer** [comment]
@LukasReschke you are right... I always mix them up...

@Dianafg76 can you test without the firewall enabled? I can't find in the CE where that 200 is thrown... So better to first make sure it is not that ;)

**Comment by Dianafg76** [comment]
@rullzer I tested with the firewall disabled and the php to >=5.6.0, everything, It not appears: "OCS API error code: 200". 
But if I tested with the firewall disabled and the php to <=5.6.0,  It appears: "OCS API error code: 200"

**Comment by ckamm** [comment]
@Dianafg76 @rullzer It looks like setting a password on that server with curl gives me a 100 response. Maybe the 200 is from a follow-up request? Will check.

**Comment by ckamm** [comment]
The 200 response only appeared because we were testing against a server that I had modified for debugging, doh. @Dianafg76 feel free to close this issue once you've re-tested, it's now tracked and in progress server-side.

**Comment by Dianafg76** [comment]
@rullzer @ckamm I re-tested with firewall enable and the php to >=5.6.0, everything, It appears: "OCS API error code: 400". If I change to the firewall disabled and the php to >=5.6.0, everything, It not appears: "OCS API error code: 200". 
And if re-tested with the firewall disabled or enabled and the php to <=5.6.0, It not appears: "OCS API error code: 200".

**Comment by Dianafg76** [comment]
I'm sorry guys, i'm change the simbol (<,>)
@rullzer @ckamm I re-tested with firewall enable and the php to <=5.6.0, everything, It appears: "OCS API error code: 400". If I change to the firewall disabled and the php to <=5.6.0, everything, It not appears: "OCS API error code: 200".
And if re-tested with the firewall disabled or enabled and the php to >=5.6.0, It not appears: "OCS API error code: 200".

**Comment by ckamm** [comment]
@Dianafg76 Thank you!

**Comment by Dianafg76** [comment]
I reopen the bug because appears again
DESKTOP v1.8.3 (build 2424)
SERVER v {"installed":true,"maintenance":false,"version":"8.0.3.4","versionstring":"8.0.3","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
It is the same if you select the option "Set expiration date"

**Comment by PVince81** [comment]
Did you try with 8.0.4 ? Wasn't this fixed there ?

**Comment by Dianafg76** [comment]
I tested with 8.0.4 and is fine.
I close the bug
