### ISSUE TITLE
block certain versions of the owncloud client

### ISSUE THREAD

**Issue by frankuit** [owncloud/client#3205]
Hi Guys,

for us the problem with the deletion of lots of files and folders isn't as easilly fixed as updating to a new client. Some clients will be unreachable for several weeks, and users will probably not update automatically.
is there some way i can prevent peoply with client version 1.8.0 to connect ? for instance, a setting in config.php on the server listing versions that are not allowed to connect ?

THanks,
Frank

**Comment by danimo** [comment]
Hi Frank. Please understand that we cannot do support through the bug tracker. You can block the client using standard web server techniques (i.e. http://httpd.apache.org/docs/2.2/howto/access.html#env, http://httpd.apache.org/docs/2.2/mod/mod_setenvif.html). you can match the partial string "mirall/1.8.0".

**Comment by frankuit** [comment]
Sorry for asking here and thanks for the pointers.

Regards,
Frank
