### ISSUE TITLE
enhancement: Activity Tab reporting remote move propagated locally

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3210]
Version 1.7:

It would be more meaningful to report where *from* the item was moved: currently the destination of the move is just reported twice:
 
![image](https://cloud.githubusercontent.com/assets/621965/7513629/f819cc0e-f4b5-11e4-9409-7688966fa74b.png)

**Comment by ckamm** [comment]
It should consistently report moves.

**Comment by Dianafg76** [comment]
I tested the bug, and the resoult is

![screen shot 2015-05-15 at 10 59 32](https://cloud.githubusercontent.com/assets/12032058/7649939/e8c19ac4-faf1-11e4-88ce-5567a18fb164.png)

Desktop v1.8.2 (build 2362)
Close the bug
