### ISSUE TITLE
minor cleanup: uneccessary debug output at the startup of the sync client

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3214]
This is a minor cleanup issue (1.7).

There is extra output on stdout/stderr at the startup of the client. Shouldthis be printed at all? Especially that I specified the --logfile option.

```
SocketApi:  server started, listening at  "/tmp/moscicki/runtime-moscicki/cernbox/socket" 
==== added system ignore list to socketapi: "/opt/etc/cernbox/sync-exclude.lst" 
==== added user defined ignore list to csync: "/home/moscicki/.local/share/data/CERNBox/sync-exclude.lst" 
setting remote poll timer interval to 30000 msec 
```

**Comment by ckamm** [comment]
I could reproduce the spurious output with 1.7 but not with 1.8. It must be already fixed there.
