### ISSUE TITLE
Owncloud Client not showing up in Debian 8 - Jessie

### ISSUE THREAD

**Issue by nllz** [owncloud/client#3215]
### Expected behaviour
Opening of Owncloud Client GUI

### Actual behaviour
The owncloud client is not showing up in Debian Jessie (with Gnome 3). I do get notifications, but I have no access to any GUI.

Everything worked before upgrade from Wheezy (Debian 7) to Jessie (Debian 8).

### Steps to reproduce
$ owncloud
Sys Info size:  96

### Server configuration
Operating system: Debian Wheezy
Web server:  Apache
Database:MySQL
PHP version:5.4
ownCloud version: 8.0.2

### Client configuration
Client version: 1.6.4
Operating system: Debian 8 Jessie 'stable'
OS language: EN_UK
Installation path of client: /usr/bin/owncloud

### Logs
$ owncloud --logfile logfile
Sys Info size:  96 
$ cat logfile
05-07 16:17:26:798 "################## ownCloud en_US (en_US) 1.6.4"

**Comment by guruz** [comment]
This is really everything in the log file?

**Comment by guruz** [comment]
Oh, client 1.6.4 is too old here anyway. 1.8.1 is out

**Comment by dragotin** [comment]
Yes, please test with 1.8.1 and reopen, if the problem still exists. Closing for now.

**Comment by nllz** [comment]
Case closed. This was due to an old version in the Debian repos, added owncloud repo from the Owncloud website and now it works. Thanks.
