### ISSUE TITLE
CSync failed to access directory error

### ISSUE THREAD

**Issue by jerrac** [owncloud/client#3216]
### Expected behaviour
Client Should sync all files

### Actual behaviour
Client runs discovery and sync processes, but then stops with this error:

    CSync failed to access https://owncloud.example.org/remote.php/webdav/path/to/git/project/.git/branches

I have seen this error appear for more than just one git project. 

I checked the server, and the branches directory exists and is chmodded to 755. Owner is www-data, group is www-data. The directory is empty, but that shouldn't cause problems.

I also ran ```occ files:scan username``` on the server. 

### Steps to reproduce
No idea...

### Server configuration
Operating system:
Ubuntu 14.04

Web server: 
Apache 2.4

Database:
Mysql 5.5

PHP version:
PHP 5.5

ownCloud version:
8.0.3

Storage backend:
NFS

### Client configuration
Client version:
1.8.1

Operating system:
Ubuntu 14.04

OS language:
English

Installation path of client:
Whereever the deb package puts it.

### Logs

I grepped out the directory in the error message and sanitized the results. See: https://gist.github.com/jerrac/4c7a61767a1cb5c831b9

**Comment by jerrac** [comment]
I tried deleting the git project from the original logs via the web ui, and the sync client gave me the same kind of error on another git project. See https://gist.github.com/abf027c49129e2a7b981.git Though this time it's the .git/logs dir, which is not empty.

**Comment by krschmidt** [comment]
Same issue, Mac client 1.8.1, build 2335

**Comment by ckamm** [comment]
@jerrac @krschmidt Hm, so the server replies with a 404 to that PROPFIND. I could not reproduce it locally. Can you make the problem appear by creating a .git/foo directory yourself?

Maybe also look at the server error log - do you see anything suspicious there?

**Comment by jerrac** [comment]
I tried creating a ownclouddir/0/.git/branches directory with nothing in it, but the sync client still errors on a different project.

Looking through my logs I see lots of complaints about apcu not existing, but I don't think that has anything to do with this issue.

I also see all the 404's for the .git/blah errors.

The only thing that really jumped out at me was a webdav error about no auth headers that shows up a LOT.

```
May  7 22:53:53 hostname ownCloud[20016]: {webdav} Exception: {"Message":"No basic authentication headers were found","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(126): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\n#1 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(106): OC_Connector_Sabre_Auth->auth(Object(OC_Connector_Sabre_Server), 'ownCloud')\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Auth\/Plugin.php(108): OC_Connector_Sabre_Auth->authenticate(Object(OC_Connector_Sabre_Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod('PROPFIND', '')\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(433): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(455): Sabre\\DAV\\Server->broadcastEvent('beforeMethod', Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Server.php(214): Sabre\\DAV\\Server->invokeMethod('PROPFIND', '')\n#7 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(61): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/owncloud\/remote.php(54): require_once('\/var\/www\/ownclo...')\n#9 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/Sabre\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":73}
```

But there's nothing in that message that make me sure it has something to do with our issue.

Note, I have my logs stored in elasticsearch and I'm searching them with Kibana. Owncloud logs to syslog, and it's been set to log everything since before I posted this issue.

**Comment by jerrac** [comment]
FYI, I had the OwnCloud server version number wrong earlier. Perils of working when you're not feeling well. It's 8.0.3 not 1.8.2....

I also just tested this on our test instance of owncloud and found the exact same behavior. Both servers are configured the same.

**Comment by krschmidt** [comment]
Manually adding .git to my list of ignored files on the client caused sync to start up for me again. Not what I want to do - it's nice not to need to pull when changing machines - but it's a workaround for now.

**Comment by ckamm** [comment]
@jerrac I tried uploading and downloading a couple of git repositories again, but didn't get any failures. To make debugging easier, could you try making a new user and then provoking the error by uploading one of the failing git repos there?

Can you reproduce the error without the owncloud client by doing

    curl -v -u <your user> -X PROPFIND 'http:<your server>/remote.php/webdav/<failing path>'

If you can, we'd know that this problem is unrelated to the client. Can you browse to the failing folder in the web ui?

**Comment by krschmidt** [comment]
I can. Here's part of the log from the client:
```
06-04 09:05:47:850 0x7ff21171acd0 OCC::Folder::setIgnoredFiles: ==== added system ignore list to csync: "/Applications/owncloud.app/Contents/Resources/sync-exclude.lst"
...skipping...
06-04 09:07:52:853 0x7ff21171acd0 OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot: void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWi
thErrorSlot(QNetworkReply *) "Error downloading https://ourserver.example/remote.php/webdav/Code/LinkChecker/.git/branches - server replied: Not Fou
nd" 404 203
06-04 09:07:52:853 0x7ff21171acd0 OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot: void OCC::DiscoveryMainThread::singleDirectoryJob
FinishedWithErrorSlot(int, QString) 2 "Error downloading https://ourserver.example/remote.php/webdav/Code/LinkChecker/.git/branches - server replied
: Not Found"
06-04 09:07:52:853 0x7ff217302720 OCC::DiscoveryJob::remote_vio_opendir_hook: static csync_vio_handle_t *OCC::DiscoveryJob::remote_vio_opendir_hook(co
nst char *, void *) OCC::DiscoveryJob(0x7ff217304220) Code/LinkChecker/.git/branches ...Returned from main thread
06-04 09:07:52:853 0x7ff217302720 OCC::DiscoveryJob::remote_vio_opendir_hook: static csync_vio_handle_t *OCC::DiscoveryJob::remote_vio_opendir_hook(co
nst char *, void *) 2 when opening Code/LinkChecker/.git/branches msg= "Error downloading https://ourserver.example/remote.php/webdav/Code/LinkCheck
er/.git/branches - server replied: Not Found"
06-04 09:07:52:853 0x7ff217302720 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handl
e_t *, void *) OCC::DiscoveryJob(0x7ff217304220) "/Code/LinkChecker/.git"
06-04 09:07:52:853 0x7ff217302720 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handl
e_t *, void *) OCC::DiscoveryJob(0x7ff217304220) "/Code/LinkChecker"
06-04 09:07:52:853 0x7ff217302720 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t *, void *) OCC::DiscoveryJob(0x7ff217304220) "/Code"
06-04 09:07:52:853 0x7ff217302720 OCC::DiscoveryJob::remote_vio_closedir_hook: static void OCC::DiscoveryJob::remote_vio_closedir_hook(csync_vio_handle_t *, void *) OCC::DiscoveryJob(0x7ff217304220) ""
06-04 09:07:52:854 0x7ff217302720 csync_statedb_close: sqlite3_close=0
```
And here's the response from running `curl -v -u <username> -X PROPFIND 'https://ourserver.example/remote.php/webdav/Code/LinkChecker/.git/branches'`

```
Enter host password for user '<username>':
* Hostname was NOT found in DNS cache
*   Trying <some ip>...
* Connected to ourserver.example (<some ip>) port 443 (#0)
* TLS 1.2 connection using TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384
* Server certificate: *.ourserver.example
* Server certificate: DigiCert SHA2 High Assurance Server CA
* Server certificate: DigiCert High Assurance EV Root CA
* Server auth using Basic with user '<username>'
> PROPFIND /remote.php/webdav/Code/LinkChecker/.git/branches HTTP/1.1
> Authorization: Basic <something>
> User-Agent: curl/7.37.1
> Host: ourserver.example
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Date: Thu, 04 Jun 2015 16:09:18 GMT
* Server Apache is not blacklisted
< Server: Apache
< Content-Length: 246
< Content-Type: text/html; charset=iso-8859-1
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /remote.php/webdav/Code/LinkChecker/.git/branches was not found on this server.</p>
</body></html>
* Connection #0 to host ourserver.example left intact
```
the folder, .git/branches does exist on the server, though it's empty
```
root@ourserver:/mounts/ws-data/filehost-data/prod/<username>/files/Code/LinkChecker/.git/branches# ls
```

**Comment by jerrac** [comment]
@ckamm I created new user. Then:

Connected to the new user's account and synced the default stuff down.

Copied a problematic git repo into the new users folder on my local machine.

All files outside of .git uploaded just fine.

The .git folder was created on the server, I can browse to it via the webui. 

But, the .git folder is empty.

In the Activity section of the settings window I'm seeing errors like:

    Continue blacklisting: Error downloading https://example.tld/remote.php/webdav/examplerepo/.git/COMMIT_EDITMSG - server replied: Not Found

    Error downloading https://example.tld/remote.php/webdav/examplerepo/.git/config - server replied: Not Found

    The item is not synced because of previous errors: Error downloading https://example.tld/remote.php/webdav/examplerepo/.git/ORIG_HEAD - server replied: Not Found

I do have a log file, but it's not easy to sanitize... So I'm looking for another way to demonstrate this problem.

**Comment by jerrac** [comment]
Ok, here we go.

I created yet another new user on the server. Started them syncing to a brand new directory. Then I copied this repo: https://github.com/lukas2/emberjs-example-pipeline into the new OwnCloud dir. And I ran into the exact same issues.

Here is a gist of the owncloud client log file: https://gist.github.com/jerrac/f7c7c31f9c5caf87e67c

**Comment by jerrac** [comment]
Oh, and if you look at the second file in the gist I just added, you can see the curl output. The .git/config file in the second call I manually uploaded via the webui.

**Comment by ckamm** [comment]
@krschmidt Thanks, that's very useful! Could you try another curl on the parent folder? I'm currently assuming it gets listed as a child on the parent but querying it directly leads to a 404.

    curl -v -u <username> -X PROPFIND 'https://ourserver.example/remote.php/webdav/Code/LinkChecker/.git' | grep -Po '<d:href.*?/d:href>'

If that's also 404, please try going another folder up.

**Comment by ckamm** [comment]
@jerrac Great, looks like you did exactly what I'd just asked @krschmidt for. :)

So .git exists on the server but .git/config does not. Can you verify that .git/config does exist on the servers file system and is visible in the web ui?

**Comment by ckamm** [comment]
@jerrac @krschmidt I think you need to check your webserver configuration!

The 404 message I would expect to see from the server's webdav implementation is:
```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File with name does-not-exist could not be located</s:message>
</d:error>
```

But instead both of you get an HTML response. Maybe your server rules don't forward this request to the ownCloud server correctly?

**Comment by jerrac** [comment]
So, we block access to .svn and .git repos with:

    RedirectMatch 404 (.*)/(.svn|.git)/(.*)

I removed it from our test server, and that let me upload the .git files.

I had totally forgotten I set that rule. Wow. Always the little things. 

Thanks for your help!

**Comment by Rezonansowy** [comment]
This also happens when there's a duplicated/wrong entry in external storage section. Removing it solved the problem in my case.
