### ISSUE TITLE
For Windows: If you share two folder, the second owncloud sharing window is appears in the background

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3218]
### Steps to reproduce
1. Open your ownCloud desktop client
2. Go to Setting...
3. Go to Open Folder "ownCloud"
4. Create a folders, call a and b
5. Right click on the folder b
6. Select share with ownCloud 
7. Right click on the folder a

### Expected behaviour
owncloud sharing window should appear in the foreground

### Actual behaviour
Owncloud share window appears in the background
![screen shot 2015-05-08 at 13 08 26](https://cloud.githubusercontent.com/assets/12032058/7535272/98e85948-f583-11e4-959a-430ce6daccf2.png)

### Server configuration
**Operating system**:

**Web server:**

**Comment by jturcotte** [comment]
This looks like a duplicate of #3015. It's also not trivial to fix from what I've tried, the solution would be to have those dialogs spawn by separate processes.

**Comment by Dianafg76** [comment]
Thanks @jturcotte lets follow its status on #3015
