### ISSUE TITLE
regression: not possible to run two clients concurrently anymore

### ISSUE THREAD

**Issue by Morganlej** [owncloud/client#3219]
Before, the user could start two clients with different configuration, to sync to two servers.
This is needed for example as we have one owncloud server local at work, and one at the ISP.
(work is underway to include this in version 2; #3084 but it is not here yet...)
Starting two instances have worked before, see: http://www.mosandl.eu/en/2014/04/start-owncloud-sync-client-twice/ , https://forum.owncloud.org/viewtopic.php?f=14&t=24750 .

The clients had to be started from two different folders/names, or it aborted regardless of different config dirs, so it seem developers try to avoid something going wrong, but it seem to have worked anyway.

Is there a real reason it should not work anymore, or is this just some carefulness gone wrong?

Today, after i have started the normal ownCloud client the default method, I then try to start a differently named client binary from another folder with another configuration folder:

    $ $HOME/bin/owncloud_second.bin --confdir $HOME/.local/share/data/ownCloud_second/
    ** Using custom config dir  "/home/morgan/.local/share/data/ownCloud_binero/"
    Sys Info size:  93
    int main(int, char**) Already running, exiting...

OwnCloud client: 1.8.0 built from git revision 38ef52
System: Linux 64bit Mageia5 KDE

**Comment by RealRancor** [comment]
See: https://github.com/owncloud/client/issues/1878#issuecomment-46085305

**Comment by Morganlej** [comment]
OK, so this was added to avoid starting same sync by mistake. I understand.  But still that "fix" killed an important feature that we already have had for long, and is not expected to return until 2.x !

I propose then a command line option --multi that simply suppress that check and thus give the feature back.
Reopen as enhancement please.

**Comment by RealRancor** [comment]
Hi,

i think it was clearly stated in the linked comment above that this was never a feature but a bug in the sync client which allowed this.

**Comment by Morganlej** [comment]
I think it was clearly stated in the links i gave that several persons have been sucessfully multisyncing that way and miss it.

I believe adding a command line option is an easy way to get back that feature for those who really want and care.  I know, careless people can shoot themself in the foot by syncing same folder, but we do not check for other syncronizers anyway so nothing is waterproof.  I can still with this current version run it as another user and sync other server but it take a bit of trick to acces the files as easily as same local user ( = more tedious and even more easily to shoot myself in the foot).

A command line option is easier and anyone who put it there do not do that by mistake.

When is 2.x due?

**Comment by RealRancor** [comment]
Hi,

let the developers of the software decide what they are supporting and what not. In the end they need to give support for problems which is caused by such an unsupported functionality.

**Comment by Morganlej** [comment]
Yes i realise now you are right.  Let it be and concentrate on going forward.
Probably someone some time would make a fancy setup for a friend who do not know implications and accidentally start two instances of same sync...
It is easy enough to create two launch icons with different --confdir and just close running OCclient and start the other when needed.
Thanks for the resistance :)
