### ISSUE TITLE
[1.6.x] Error message is not very clear when the desktop version is not allowed by server

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3220]
Previous, you need a 1.6.x desktop version

STEPS TO REPRODUCE:
1.- Using the 1.6.2 version
2.- Connect to a 8.1.0 ownCloud server, enter the server url
3.- Enter right credentials

EXPECTED BEHAVIOR:
An error message is shown letting you know that that client version is not allowed

CURRENT BEHAVIOR:
Wrong credentials message is shown

LOGS:
```
05-11 11:21:47:466 application.cpp:344 "################## highshare en_US () 1.6.2"
05-11 11:21:47:499 application.cpp:531 void Mirall::Application::setupTranslations() Using "en" translation
05-11 11:21:47:539 folderman.cpp:136 * Setup folders from  ""
05-11 11:21:48:711 socketapi.cpp:55 SocketApi:  can't start server ""
05-11 11:21:48:720 owncloudgui.cpp:101 No configured folders yet, starting setup wizard
05-11 11:21:48:796 owncloudwizard.cpp:160 Current Wizard page changed to  0
05-11 11:21:51:670 sparkleupdater_mac.mm:107 virtual void Mirall::SparkleUpdater::backgroundCheckForUpdate() launching background check
05-11 11:21:51:674 sparkleupdater_mac.mm:34 -[DelegateObject updaterMayCheckForUpdates:] may check: YES
05-11 11:22:08:540 cookiejar.cpp:119 "/Users/Diana/Library/Application Support/xxxx//cookies.db"
05-11 11:22:08:541 networkjobs.cpp:65 void Mirall::AbstractNetworkJob::setTimeout(qint64) 10000
05-11 11:22:08:593 networkjobs.cpp:191 !!! Mirall::CheckServerJob created for  QUrl( "http://docker.oc.solidgear.es:50108" )  querying "status.php"
05-11 11:22:08:722 networkjobs.cpp:417 status.php returns:  QMap(("edition", QVariant(QString, "Enterprise") ) ( "installed" ,  QVariant(bool, true) ) ( "maintenance" ,  QVariant(bool, false) ) ( "version" ,  QVariant(QString, "8.1.0.5") ) ( "versionstring" ,  QVariant(QString, "8.1 beta 1") ) )    0  Reply:  QNetworkReplyHttpImpl(0x7fc969c50eb0)
05-11 11:22:08:722 owncloudwizard.cpp:193 Setup-Log:  "<font color="green">Successfully connected to http://docker.oc.solidgear.es:50108/status.php: xxx version 8.1 beta 1 (8.1.0.5)</font><br/><br/>"
05-11 11:22:08:722 owncloudsetupwizard.cpp:172 void Mirall::OwncloudSetupWizard::slotOwnCloudFoundAuth(const QUrl &, const QVariantMap &)  was redirected to "http://docker.oc.solidgear.es:50108"
05-11 11:22:08:722 networkjobs.cpp:191 !!! Mirall::DetermineAuthTypeJob created for  QUrl( "http://docker.oc.solidgear.es:50108" )  querying ""
05-11 11:22:08:830 networkjobs.cpp:139 void Mirall::AbstractNetworkJob::slotFinished() 204 "Host requires authentication"
05-11 11:22:08:830 owncloudsetupwizard.cpp:474 virtual bool Mirall::DetermineAuthTypeJob::finished() ""
05-11 11:22:08:832 owncloudwizard.cpp:160 Current Wizard page changed to  1
05-11 11:22:17:056 owncloudsetupwizard.cpp:200 Connect to url:  "http://docker.oc.solidgear.es:50108"
05-11 11:22:17:056 cookiejar.cpp:119 "/Users/Diana/Library/Application Support/xxxx//cookies.db"
05-11 11:22:17:056 owncloudwizard.cpp:193 Setup-Log:  "Trying to connect to xxxx at http://docker.oc.solidgear.es:50108..."
05-11 11:22:17:099 networkjobs.cpp:191 !!! Mirall::ValidateDavAuthJob created for  QUrl( "http://docker.oc.solidgear.es:50108" )  querying ""
05-11 11:22:17:365 networkjobs.cpp:139 void Mirall::AbstractNetworkJob::slotFinished() 202 "Error downloading http://docker.oc.solidgear.es:50108/remote.php/webdav/ - server replied: Forbidden"
```

SERVER:
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}

DESKTOP: 1.6.2

Mac Yosemite

**Comment by Dianafg76** [comment]
I tested in Windows, and happend the same. The message is

![screen shot 2015-05-12 at 08 41 20](https://cloud.githubusercontent.com/assets/12032058/7581398/d71d2426-f882-11e4-8602-2a5b4ae1b597.png)

SERVER:
{"installed":true,"maintenance":false,"version":"8.1.0.5","versionstring":"8.1 beta 1","edition":"Enterprise"}
DESKTOP: 1.6.0
Mac Yosemite and Windows

**Comment by rperezb** [comment]
Related to https://github.com/owncloud/core/pull/15683

**Comment by guruz** [comment]
(note that we cannot fix 1.6 anymore, but we can change what 1.8.2 shows if 1.9 is minimum)

**Comment by Dianafg76** [comment]
Ey @guruz you are right, changing the server to allow 1.9.0 the error is:
![screen shot 2015-05-14 at 08 53 58](https://cloud.githubusercontent.com/assets/12032058/7627352/e0e190e2-fa16-11e4-9136-6553dd1b43e7.png)

**Comment by dragotin** [comment]
hmm, for some reason we do not show the custom error message that the server is sending: https://github.com/owncloud/core/pull/15683/files#diff-37526aa61cf9c214a55543f3dd832aa5R76

**Comment by ckamm** [comment]
Fixed for 1.8.2.

**Comment by danimo** [comment]
@ckamm what about when the server gets upgraded and the client reconnects?

**Comment by Dianafg76** [comment]
Ey @ckamm changing the server to allow 1.9.0 the error is ok, but one think, could you deleted the point to the end of paragraph, please 

![screen shot 2015-06-08 at 09 02 52](https://cloud.githubusercontent.com/assets/12032058/8029564/fe949fba-0dbe-11e5-9b59-165e5a31256d.png)

**Comment by Dianafg76** [comment]
I tested in MAC and WINDOS

**Comment by ckamm** [comment]
@Dianafg76 The server sends "Unsupported client version.". We could add code to drop a trailing dot, but I'd rather not modify the message since the client doesn't generally know what it means.
