### ISSUE TITLE
OS X client not syncing files in shared folder under certain conditions

### ISSUE THREAD

**Issue by benjaminpichler** [owncloud/client#3221]
OS X Yosemite version 10.10.3, ownCloud client v1.8.1 (build 2335).

There is probably a bug in the ownCloud client for Mac (recognized since several versions) that prohibits correct syncing of files within a shared folder. The client seems to believe that files are up to date (green check icon) even if sync client is restarted entirely and even if whole machine is restarted. Meanwhile the Windows client (logged in with same user) is updated just fine.

So here is my test environment to reproduce the error:
* User A is admin (in group "admin"). User U is in own group "Extern". Both having unlimited quota.
* User A has the following folder structure in its root directory: ./Externe/Createam
  * Folder "Externe" is shared with group "admin" - full access permissions.
  * Folder "Createam" is shared with user U - full access permissions.
* User A is running ownCloud client on Mac (with versions printed above).

Now, when user U is uploading a new file in folder "Createam", user A doesn't get notified about any change. The sync client permanently thinks everything is synced already, while still displaying old files/folders in Finder. So this seems to be a bug.

Additional info (for described scenario):
* User A can see everthing in the ownCloud WebGUI, so i guess everything is running fine on the server side.
* If user A is running the sync client under Windows everything is syncing immediatly without any problems.
* Manually restarting either sync, ownCloud client or entire Mac has no effect; but suddently on the next day the client is syncing the files modified/added the day before.
* According to our client that reported the issue to me, this problem exists since day one (we installed the servers about a year ago).
* If files are added by another user C (which is member of the "admin" group), everything is synced fine by user A.
* As soon as user A itself changes anything inside folder "Createam" (e.g. via WebGUI), the Mac ownCloud client recognizes the changes and resynchronizes everything (including files that where not modified since updloaded by user U)

**Comment by guruz** [comment]
CC @PVince81 this had been fixed in the server right?

**Comment by PVince81** [comment]
Yes, probably the etag propagation issue with shared sub-sub-folders: https://github.com/owncloud/core/issues/14726

**Comment by PVince81** [comment]
it should be fixed in 8.1

**Comment by guruz** [comment]
thanks!

**Comment by benjaminpichler** [comment]
Wow, thanks so far.

Since i reported this, i also recognized that the bug is affecting synchronization of Windows ownCloud clients. So is this still just ONE problem, or are we talking about two individual problems? (Because sometimes it seems to work just fine with Win client while not working with OSX client .. so i didn't asume this to be a server-side problem).

I am really suprised that ownCloud comes with such a huge bug, because in my opinion this is massively affecting the core purpose of this product: storing and sharing files... so i think this should be handled with highest severity ;)

Thank you!
