### ISSUE TITLE
Inform User about Conflict File creation

### ISSUE THREAD

**Issue by mlsbr** [owncloud/client#3222]
Hi,
Currently, when the conflict file is created, it is not synchronized with the server, and the user is not warned.
To prevent the user having to check every time you save a file (to check if it was synchronized), I suggest that a warning message is displayed to the user that the file was not synchronized and why.

Thanks!

**Comment by guruz** [comment]
CC @jancborchardt

**Comment by jancborchardt** [comment]
Well honestly I think we _should_ sync conflict files. I’m pretty sure this is what Dropbox does as well, and it’s just good practice to make sure you have all the files everywhere.

**Comment by PVince81** [comment]
Note that if conflict files are allowed to appear on the ownCloud server, this might open the door to other concepts like syncing files between external storage and the ownCloud server (instead of a direct connection). In such situation, conflicts could also occur: https://github.com/owncloud/core/issues/5225

**Comment by MTRichards** [comment]
Definitely an enhancement, and we need to think through this in detail.

**Comment by moscicki** [comment]
@jancborchardt: I definitely agree. The current situation is problematic because it is in practice easy for a user to overlook that some files are not synced -- and the conflict file contains local changes which are not saved anywhere. This may lead eventually to data loss (when user realizes it may be too late -- his laptop just fell off the table). But this requires some careful thinking, agreed @MTRichards .

**Comment by guruz** [comment]
In general, I think we need a way to have user notifications displayed (also in tray?) that are not associated to a ```SyncFileItem```
@dragotin @danimo

**Comment by guruz** [comment]
Linking https://github.com/owncloud/client/issues/4079

**Comment by dragotin** [comment]
Well. In the beginning we had the idea of overlaying the tray icon with a warning sign like
![warning 2x](https://cloud.githubusercontent.com/assets/1070214/13630315/08ee3270-e5df-11e5-9403-b43803b925fb.png) to indicate the user that there is something she should check. 

That was removed again as we agreed to not disturb the users.

**Comment by guruz** [comment]
Can we agree to a simple and doable solution for 2.2? @jancborchardt @dragotin 
One of those:

1. Display a desktop notification
2. Make the file show up in _Unsynced files_ as "Conflict file created" or something like that

**Comment by davitol** [comment]
> Display a desktop notification
> Make the file show up in Unsynced files as "Conflict file created" or something like that

Windows10 and owncloud-2.2.0.5855.
I could not get a notification after a conflict happened. @guruz could you please define some steps to get the notification

**Comment by dragotin** [comment]
@davitol Easiest is to stop the client, and change the same file on both the client- and server-side. If you restart the client, it tries to sync and will detect a conflict. 

You should see a tray notification about that.

**Comment by davitol** [comment]
:+1: WFM. A tray notification related to the conflict is shown.  Version 2.2.0-nightly20160411 (build 5985)

Note: After creating a conflict, the not sync advice disappears in this table but the tab still counts 1 file.

**Comment by dragotin** [comment]
I fixed the wrong issue count in the tab text.

**Comment by mcastroSG** [comment]
Hi hi:

@dragotin , after retest [https://github.com/owncloud/client/issues/3222#issuecomment-208262494](url) seems to be solved the problem about wrong count in the tab text.


**Windows**
Client Version: Version 2.2.0-nightly20160419 (build 6002)
Client OS: Windows 10
Server Version: 9.0.1
Server OS: Ubuntu

**MacOS**
Client Version: Version 2.2.0-nightly20160419 (build 3282)
Client OS: El Capitan 10.11.4
Server Version: 9.0.1
Server OS: Ubuntu

Regards

**Comment by dragotin** [comment]
Ok, thanks!
