### ISSUE TITLE
OS X Client 1.8.1 produces heavy traffic

### ISSUE THREAD

**Issue by stkjj** [owncloud/client#3224]
approx. every 10s:

xxx.xxx.xxx.xxx - - [12/May/2015:08:06:55 +0200] "PROPFIND /remote.php/webdav/ 
HTTP/1.1" 207 508 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.1" "-" 0 
cloud.mydomsin.de cloud.mydomsin.de 443

where xxx.xxx.xxx.xxx is my home-network ip and cloud.mydomain.de is my remote oC-Server running 8.0.2 (staple)

My traffic increased since installing the update ot v1.8.1 dramatically:
![bildschirmfoto 2015-05-12 um 09 24 21](https://cloud.githubusercontent.com/assets/832642/7581969/3a9fb6b6-f889-11e4-98d9-79491d3a7b64.png)

**Comment by dragotin** [comment]
@ckamm mind to clearify? 

@stkjj how many sync folders have you configured?

**Comment by stkjj** [comment]
1 Folder with approx. 100 MB in some subfolders. Most frequent updatet item is my 1Password-keychain file with about 33 MB

**Comment by guruz** [comment]
If you run the client with ```/Applications/owncloud.app/Contents/MacOS/owncloud --logfile -``` what do you see it doing?
How often do you see the "Discovering..." in the settings dialog?
What do you see in the activity log in the settings dialog?

**Comment by ckamm** [comment]
@stkjj I echo what @guruz asked above. The regular ping has been around since 1.7 and should not contribute significantly to the traffic. So any differences in discovery frequency or propagation would be interesting.

**Comment by stkjj** [comment]
Looks like that (only lines containing »discovery«):
![oc log copied lines](https://cloud.githubusercontent.com/assets/832642/7610274/d1a4c7de-f97b-11e4-927a-109ab54d45a4.jpg)

presently my hoster informed my about an error in his log-grep. Having corrected this it seems no longer ownCloud is responsible for the high traffic but a brute-force-attac driven from an AWS-Server … :-o

Pls appologize for the hustle caused.

**Comment by dragotin** [comment]
@stkjj ok, thanks for letting us know.
