### ISSUE TITLE
[1.8.1 Windows Client] Regular CPU spikes

### ISSUE THREAD

**Issue by Dark-Fenix** [owncloud/client#3227]
Hi,

I'm having big CPU spikes (about 50% CPU on a i5) every 2 or 3 minutes since the last owncloud client update I received.
I sync 10 folders with a 8.0.2 server (as far as I remember) for about 12500 files (50 GB) since 3 months. Everything was fine until the update, and now I just can't work : when the client run a sync, the CPU and the IO increase very high and my machine has sorts of lags and freezes. For example, I can't write a simple text because may caracters are not handled ! My mouse moves with difficulties and all I can do is close the client to have my PC back.

I also use the latest client version on Linut Mint 17.1, seems ok.

Is someone else having the same problem ? Can I bring some log files to help ?

Thanks in advance !

**Comment by guruz** [comment]
If you open the settings dialog to see what is happening, can you see what he is doing every 2 or 3 minutes?

Is it "Discovering..." ? Is it transfering a file?

Is this a regression from a previous client version?

**Comment by Dark-Fenix** [comment]
It seems to mainly occur while transfering data. Just right now I'm uploading some files and my PC slows immediately. But it's not 100% of the time, sometimes (but rarely) it works correctly.
I though about a network problem in my company, but I'm only experiencing this since the last update (I don't remember the versions I had before) and with no other software (I also tried a Dropbox client, and I use network-based tools to communicate with internal and externals machines without any problem).

**Comment by guruz** [comment]
But when you don't do any files changes, what happens with the load?

(Just to see if it is related to uploads/downloads or not).

How often does the "Discovering..." happen?

**Comment by Dark-Fenix** [comment]
When there are no changes, nothing special. The discovering never happens or is very quick (but I could have missed it), the load is ok.

It's only when there is a change, more specially in the upload way : I tried this morning putting an iso in one of my folders, after the discovering part (which runs smoothly, except some spikes nearby 25% CPU but without consequences) when the upload start... constant 25% CPU load, and PC unusable. I made an other test : uploading a file through the web interface and let it back into my folders with the client : no problem. It's not disk-related, as there are no strange I/O.

I run a Windows 7 Entreprise x64. It's the only Windows I use (and just for work), and unfortunately I can't disable the firewall or Symantec to make further tests (company rules).

**Comment by guruz** [comment]
> I also use the latest client version on Linut Mint 17.1, seems ok.

Are you saying rougly the same client version with the same amount of synced folders/files makes trouble on Windows but not Linux?

Could you try this nightly build (beware, nightly builds are not fully QAed)
http://download.owncloud.com/desktop/daily/ownCloud-1.8.2.5077-nightly20150515-setup.exe
Make sure to uninstall the old client version (especially to select to uninstall the Explorer shell extension) and reboot before doing this (as Explorer will still have the old extension loaded)

CC @jturcotte

**Comment by Dark-Fenix** [comment]
I just tried the nightly : same problem (clean uninstall, reboot, fresh install, but I didn't find any option to specifically ask the shell extension to be removed, does the uninstaller do it automatically ?).
But as I said, I can't try without my firewall/antivirus for corporate security reasons. I will try tonight from a fresh Win7 at home, with the stable client and if necessary the nightly.

**Comment by Dark-Fenix** [comment]
Yesterday on a fresh windows 7 64bits : everything is ok. So I really think it's related to my corporate environment, perhaps my antivirus.
But it is still strange : I didn't have any problem until this week.
Anyway, thanks for your time, I will try to migrate to Linux at work :p

**Comment by guruz** [comment]
@Dark-Fenix but is this the same amount of sync folders and folders/files in there?

**Comment by Dark-Fenix** [comment]
Yes, I tried with the same configuration. If I have enough time this week I'll make some tests at work, to be sure, but it is not the first time some tools fail to work properly with our policies...

**Comment by guruz** [comment]
ok, let's hope it doesn't come back:)

**Comment by massimoi** [comment]
I had the same problem (100% cpu all night, no particular task to do, 3 folders synced),

 i discovered the client was looping on 2 files which were conflicting and tried again and again to sync them (error: __the destination file exists__)
I reolved the conflict (deleted the files), and now the CPU fan is down.

Maybe developers can intercept such loops and "break" them.
Thanks a lot
Massimo
