### ISSUE TITLE
Files have been moved to Trashbin - without known user action

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#3229]
A user found a number of his directories removed. Searching them on the file-server, we found them in the trash bin directory and the user could restore them

The user has not knowingly deleted the files through the Web UI or on the client. What conditions will make this happen?

### Architecture 
Server 7.0.5
OwnCloud client software: Version 1.8.0 (build4893);
Operating system: Window 7, Window 8 , OS X Yosemite
synchronized with 3 different PC (with the above operating system), but usually have problem with the Window 7 installed one ( for the other two, I don’t remember since I don't usually look in the owncloud folder with these two PC)

### Logfiles
S3-ownCloud\Shared\owncloud\support\github-issues\client\3229

@MorrisJobke 

00003000

**Comment by dragotin** [comment]
@cdamken please find out the names of the removed files out, so that we can cross check with the logs. Thanks. Also: 1.8.1 is out, please let ask the customer to  update.

**Comment by guruz** [comment]
@cdamken In the current oC incarnations deletes by the client (via WebDAV) will not land in the server trash bin. I therefore suspect a server issue here.

FYI @icewind1991 @DeepDiver1975 @PVince81

**Comment by DeepDiver1975** [comment]
> Server 7.0.5

@guruz back then deleted files and folders have been moved to the trash

**Comment by cdamken** [comment]
@dragotin @guruz I'm still waiting for the information.

**Comment by MorrisJobke** [comment]
@PVince81 Wasn't there a fix that introduced "move to trashbin for webdav" recently? I can't find it anymore, but I remind something.

**Comment by PVince81** [comment]
There might have been some bugs that could cause files to be deleted to trash, but I cannot remember which one.

@MorrisJobke the fix you are thinking about is something different: basically webdav delete would bypass the trashbin on OC 8.0.x.

**Comment by MorrisJobke** [comment]
> @MorrisJobke the fix you are thinking about is something different: basically webdav delete would bypass the trashbin on OC 8.0.x.

Ah ... coorect. Sorry. Mixed this up.

**Comment by ogoffart** [comment]
There is another issue with more or less the same symtoms:  https://github.com/owncloud/client/issues/3206

But it just look as if the files were already removed on the client and the client is just propagating this change to the server.
There is nothing that indicates in the log or anything that it is the owncloud client that removed the files on the local system. Or what could have removed the files

**Comment by ogoffart** [comment]
I really do not know if there is a bug in the owncloud client. And without a way to reproduce or more information, i am unable to do anything.

**Comment by cdamken** [comment]
@ogoffart I have no new information, I will close it and as soon as I can provide some usable information I will reopen it.

**Comment by ogoffart** [comment]
This was cause by two bugs. One that was fixe din 1.8.0, an another fixed in commit e54253d
