### ISSUE TITLE
[1.8.x] (x>1) t2.pl uncovered concurrency issue with renames

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3230]
After https://github.com/owncloud/client/commit/79ac61684c8f20a393a629c815b2ad0610348f7b had been pushed this test in t2.pl started to fail:

```
##########################################################
#  8. Move a directory remotely with a changed file in it.
##########################################################
```

It will retrigger a sync (because of ```FileSystem::verifyFileUnchanged```) and have a conflict file created which is not expected.

According to @ogoffart the ```_csync_treewalk_visitor``` needs to be adjusted to also
fill the ```other``` pointer with the info it was renamed from, not only renamed to.

FYI @ckamm

**Comment by ogoffart** [comment]
Fixed with commit 505dba5b23a110d5ef91885c31d45676585a56f8
