### ISSUE TITLE
[Linux] [SSL] client fails certificate check

### ISSUE THREAD

**Issue by porjo** [owncloud/client#3231]
I'm getting this error with Linux desktop client and a Geotrust RapidSSL cert:

```
Warnings about current SSL Connection:
The issuer certificate of a locally looked up certificate could not be found
The root CA certificate is not trusted for this purpose
with Certificate RapidSSL SHA256 CA - G3
Organization: GeoTrust Inc.
Unit: <not specified>
Country: US
Fingerprint (MD5): 23:bb:07:5f:ac:fb:fb:02:69:35:b3:1f:b6:ee:06:3b
Fingerprint (SHA1): 0e:34:14:18:46:e7:42:3d:37:f2:0d:c0:ab:06:c9:bb:d8:43:dc:24

Effective Date: Fri Aug 29 21:39:32 2014
Expiration Date: Fri May 20 21:39:32 2022
Issuer: GeoTrust Global CA
Organization: GeoTrust Inc.
Unit: 
Country: US
```

I'm using Fedora 21 and RPMs from the OpenSuse repo: http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Fedora_21/

I've tested with openssl from the command line and the certificate chain looks ok - see here:  http://pastebin.com/u9gbz4dw

**Comment by MTRichards** [comment]
What client are you running?

**Comment by porjo** [comment]
I'm using RPMs from Opensuse. Currently: owncloud-client-1.8.2-7.1.x86_64

**Comment by danimo** [comment]
@porjo I cannot reproduce this on Ubuntu 14.04 using 1.8.4. Can you still reproduce it?

**Comment by porjo** [comment]
Yes, still an issue for me using 1.8.4 on Fedora 22. I tested by removing the OwnCloud client config e.g. `rm ~/.local/share/data/ownCloud -rf` and restarting the client, then stepping through the setup wizard. Same error as before.

```
$ dnf list owncloud-client
Installed Packages
owncloud-client.x86_64                                   1.8.4-2.1                                   @System             
```

**Comment by danimo** [comment]
I just installed Fedora 22 from scratch in VM, installed the latest 1.8.4 from our vendor repo (through build.opensuse.org), and tried to connect to `https://cloud2.creditworks.com.au`. That worked without an error. However, I _did_ receive an error with CentOS 6. But that's another story.

**Comment by guruz** [comment]
(Danimo says this is related to the ```setSslConfiguration``` call)

**Comment by danimo** [comment]
@porjo do you have the "ca-certificates" package installed?

**Comment by porjo** [comment]
@danimo  yes, `ca-certificates-2015.2.4-1.0.fc22.noarch`

**Comment by dragotin** [comment]
Tried with 2.0.1+git on windows, no problems.  @porjo have you had a chance to update to 2.0.1 yet?

**Comment by porjo** [comment]
@dragotin yes I'm using `owncloud-client-2.0.1-1.1.x86_64` now. The issue is no longer occurring for me :smiley:
