### ISSUE TITLE
MSI installer

### ISSUE THREAD

**Issue by crysman** [owncloud/client#3237]
According to this hint https://forum.owncloud.org/viewtopic.php?f=14&t=11197 I am asking if an MSI installer is planned?

My intention is to deploy it via GPO in our domain, therefore, I need a MSI package.

**Comment by dragotin** [comment]
#860 and #1462 tell you all you wanna know. 

No offense taken, but please try to search for existing issues before posting new ones, thanks!

**Comment by crysman** [comment]
No offense, but I've done that. No relevant results found. Searching for "MSI" has given me (right now, too) just 4 results regarding to some "shell_integration/icons/...."

Thanks for the linked issues. I do not know why I got no results like that.
