### ISSUE TITLE
Error uploading the same file 3 times when you removes the line network

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3238]
### Steps to reproduce
1. Open your ownCloud Desktop client
2. Go to Open Folder "ownCloud"
3. Create a new Folder, called a
4. Move a File (sice 1Gb)
5. Removes line network, after a few seconds, connect the line network (This process has to be done three times)

### Expected behaviour
The error must not appear

### Actual behaviour
The third time, appears this error

![screen shot 2015-05-15 at 14 19 36](https://cloud.githubusercontent.com/assets/12032058/7652493/7508dd7e-fb0d-11e4-84cf-f6c75347f255.png)

Logs:

```
05-15 14:18:21:053 0x7f82e1f44b00 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 401 "Error downloading http://xxxx/remote.php/webdav/1G.file copy-chunking-1848376562-205-35 - server replied: Internal Server Error"
05-15 14:18:21:054 0x7f82e1f44b00 OCC::PropagateUploadFileQNAM::slotPutFinished: void OCC::PropagateUploadFileQNAM::slotPutFinished() QUrl( "http://xxxx/remote.php/webdav/1G.file copy-chunking-1848376562-205-35" ) FINISHED WITH STATUS 401 "Error downloading http://xxxx/remote.php/webdav/1G.file copy-chunking-1848376562-205-35 - server replied: Internal Server Error" QVariant(int, 500) QVariant(QString, "Internal Server Error")
```

Other Log:

```
05-15 14:19:21:177 0x7f82e1f44b00 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 401 "Error downloading http://xxxx/remote.php/webdav/1G.file copy-chunking-1848376562-205-35 - server replied: Internal Server Error"
05-15 14:19:21:178 0x7f82e1f44b00 OCC::PropagateUploadFileQNAM::slotPutFinished: void OCC::PropagateUploadFileQNAM::slotPutFinished() QUrl( "http://xxxx/remote.php/webdav/1G.file copy-chunking-1848376562-205-35" ) FINISHED WITH STATUS 401 "Error downloading http://xxxx/remote.php/webdav/1G.file copy-chunking-1848376562-205-35 - server replied: Internal Server Error" QVariant(int, 500) QVariant(QString, "Internal Server Error")
```

### Server configuration
Desktop v 1.8.2 (build 2362) MAC

**Comment by dragotin** [comment]
Why do we see the internal server error? That should not happen, or is it a false friend? @Dianafg76 can you check the servers access_log file if that was really an internal server error? thx.

**Comment by Dianafg76** [comment]
@dragotin, the access_log
``82.159.139.58 - diana [19/May/2015:11:19:05 +0000] "GET /status.php HTTP/1.1" 200 841 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:19:05 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1220 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:19:05 +0000] "GET /ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 964 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:19:06 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1266 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:19:07 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 11146 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:18:16 +0000] "PUT /remote.php/webdav/1G.file%20copy-chunking-1970063934-205-6 HTTP/1.1" 400 901 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:19:08 +0000] "PUT /remote.php/webdav/1G.file%20copy-chunking-1970063934-205-3 HTTP/1.1" 201 695 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:19:08 +0000] "PUT /remote.php/webdav/1G.file%20copy-chunking-1970063934-205-4 HTTP/1.1" 201 695 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:19:08 +0000] "PUT /remote.php/webdav/1G.file%20copy-chunking-1970063934-205-2 HTTP/1.1" 201 694 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:19:24 +0000] "PUT /remote.php/webdav/1G.file%20copy-chunking-1970063934-205-7 HTTP/1.1" 500 9168 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:19:18 +0000] "PUT /remote.php/webdav/1G.file%20copy-chunking-1970063934-205-5 HTTP/1.1" 201 694 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:19:27 +0000] "PUT /remote.php/webdav/1G.file%20copy-chunking-1970063934-205-8 HTTP/1.1" 400 901 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:19:21 +0000] "PUT /remote.php/webdav/1G.file%20copy-chunking-1970063934-205-6 HTTP/1.1" 400 901 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:19:37 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1221 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:19:37 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1267 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:19:39 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 11146 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:20:07 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1267 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:20:09 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1220 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:20:10 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 1266 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"
82.159.139.58 - diana [19/May/2015:11:20:11 +0000] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 11146 "-" "Mozilla/5.0 (Macintosh) mirall/1.8.2"```

@dragotin, If i tested with DESKTOP v  ownCloud-1.8.2.2369-nightly20150519, I can not reproduce the error

**Comment by ckamm** [comment]
Looks like we really got a 500 reply from the server. I think showing the error is the correct behavior in that case? @dragotin 

I'll try to reproduce the issue to check if we can improve this, but if we don't detect the connection loss and only see a server "internal server error", there's probably little we can do. (we could silently retry even on 500?)

**Comment by ckamm** [comment]
I've tried to reproduce this without success. Since we do get a 500 from the server in this case what we're doing seems correct already.
