### ISSUE TITLE
Selective sync folder list name column too small

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/client#3239]
![bildschirmfoto vom 2015-05-15 14 55 37](https://cloud.githubusercontent.com/assets/213943/7653249/8e8e6a1e-fb14-11e4-9053-5ea9d2cf4a2b.png)

Also happens on the normal client. My language is german, maybe that is related some how.

OS: Linux Mint

**Comment by guruz** [comment]
@ogoffart Is that a Qt4 bug?

**Comment by ogoffart** [comment]
Yes, that's because   QHeaderView::setSectionResizeMode  is new in Qt5.  There is probably a way to do it in Qt4 as well tough. 
Shoud someone spend the time to do it for Qt4 as well?

**Comment by danimo** [comment]
@ogoffart As long as we have Qt4 based packages we need to address this.

**Comment by MTRichards** [comment]
If we can get rid of Qt4 by 2.0, then ok. BUT, I don't think we can. So this becomes a bug for 2.0.
