### ISSUE TITLE
"Hard link not supported" with NTFS on Linux

### ISSUE THREAD

**Issue by jamfx** [owncloud/client#3241]
Hi Everybody,
i am on an Xubuntu 15.04 with my OwnCloud 8.0.3 and the client 1.8.1.
MANY (and I really mean a lot) of my Files won't be sycned, becaue of the "Error" - "Hard links are not supported"

These Files are not copied anywhere. They are on an internal NTFS-Formatted Harddrive. 
It looks similar to this issue: https://github.com/owncloud/client/issues/2557
But not under the exact same circumstances. So please have a closer look to the OC-Client or did I do something wrong? Just to make it clear again: I don't have made any copies or hard links to this files by myself. What can I do against this? Like this my OC is unusable for me.
OK I found out (ls -la), that many of my files do have a second hard link. But I can not find out where and how to delete this... 

Thanks JamFX

**Comment by ogoffart** [comment]
Relates to #1143

**Comment by jamfx** [comment]
@ogoffart Are you sure it relates to this bug? Doesn't look quite similar. Although I used the following workaround:
a) stop OC Sync
b) Copy all OC-files to a "backup-Folder" like "OC-Backup" (and I copied really the whole OC because of so many files complaining)
c) Copy all Files back from "backup-Folder" to the original OC-Folder overwriting existing files
d) Start OC Sync again

Now the files got synced and only 1 conflict-File showed up! Lucky me?

**Comment by ogoffart** [comment]
I think NTFS are making hard links internaly, and owncloud will refuse to sync some of the files because of that.

We might need to change our policy regarding links

**Comment by grawlinson** [comment]
Hello, just chiming in to say that I've started to experience this issue.

I dual-boot Ubuntu & Windows 8 with a shared NTFS partition, which contains my ownCloud directory.

If I try and overwrite the affected files with copies, ownCloud will still not sync them.

**Comment by justlilpete** [comment]
Just to say I also am experiencing this issue. Dual booting Ubuntu 15.04 with Windows 8.1, ownCloud directory on a shared NTFS partition. A number of files, seemingly random spread of types (avi, jpg, exe, txt, zip) in a number of folders (and not all files in the folder) fail with this error.

**Comment by MTRichards** [comment]
From Nov 2014:
> "No, we neither plan to sync hard nor softlinks"
https://github.com/owncloud/client/issues/530#issuecomment-64792249

That said, if NTFS is making internal invisible hard links, then we need to investigate. Seems it is a dual boot problem, based on the evidence above, and that this is an internal link created in this scenario. Moving to 2.0.1

**Comment by ogoffart** [comment]
In 2.0 we will sync hard links.
Please test that it indeed solve the issues. I could not test myself since i do not have a dual boot windows/linux

**Comment by moscicki** [comment]
Wow, that sounds like a huge change. Is this general purpose or just a trick to solve this particular NTFS dual boot problem?

If I have a and b which are local hard-links what will I get on the server after upload: two separate remote files a and b? What if then they change independently?

**Comment by ogoffart** [comment]
This is a general purpose change. 

> If I have a and b which are local hard-links what will I get on the server after upload: two separate remote files a and b?

Two separate remote files a and be, yes.

> What if then they change independently?

When they are changend, the hard link will be broken and the files will not be hard link anymore.
That is the behaviour of most editor anyway. (for example if you edit with vim a file which is hard linked to the other and you save that file,  the hard link will be broken and the linked file will not be updated)

**Comment by dragotin** [comment]
In vim, the behaviour is actually configurable, said @jnweiger who by chance contributed this part to vim. To learn more, type ```:help writebackup``` in vim.

**Comment by moscicki** [comment]
So I guess on the server these will be two separate files and the hard link would not be propagated to another client, right?

**Comment by moscicki** [comment]
And for curiosity: in this particular NTFS scenario, if the client breaks hard links, what happens?

**Comment by ogoffart** [comment]
> So I guess on the server these will be two separate files and the hard link would not be propagated to another client, right?

correct
