### ISSUE TITLE
Windows Recipe Build Error

### ISSUE THREAD

**Issue by denzelfernando** [owncloud/client#3242]
hi!

Using Opensuse 13.2 with Latest source,
Following the cross-compiler instructions for Windows.

cmake -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_TOOLCHAIN_FILE=../client/admin/win/Toolchain-mingw32-openSUSE.cmake ../client

make

Results in,
CMakeFiles/owncloud.dir/objects.a(accountsettings.cpp.obj):accountsettings.cpp:(.text+0x5417): undefined reference to `OCC::ProgressInfo::Progress::completed() const'
....
..... bunch of link errors .
....
src/gui/CMakeFiles/owncloud.dir/build.make:1741: recipe for target 'bin/owncloud.exe' failed

Any inputs appreciated.

Regds

**Comment by RealRancor** [comment]
Hi,

this is an issue tracker of the sync client where bugs or feature requests are posted. I think such questions about building the client are better placed at the developers mailinglist https://mailman.owncloud.org/mailman/listinfo/devel or the IRC channels #owncloud-dev/#owncloud-client-dev at freenode.

**Comment by guruz** [comment]
@denzelfernando Wrong branch, switch to 1.8 branch.. :)

FYI @kwillems @ckamm

**Comment by guruz** [comment]
(Should be fixed now in master branch)

https://github.com/owncloud/client/commit/330b3520011bffffa0af04c859380da6ebb992eb
