### ISSUE TITLE
update  qtkeychain

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#3243]
There is a new version available at:
https://github.com/frankosterfeld/qtkeychain/commits/master

**Comment by dragotin** [comment]
qtkeychain 0.5 is now in isv:ownCloud:community:testing -> to be released with oCC 1.8.2 soon.

**Comment by dragotin** [comment]
@dschmidt maybe you wanna pick up...

**Comment by dschmidt** [comment]
Ah, nice. I'll look after whitsun

**Comment by dragotin** [comment]
windows:mingw:mingw32 has the packages with updated version.

**Comment by dragotin** [comment]
Tested the package from isv:ownCloud:community:testing on openSUSE, works.

@danimo once we release, we need to update the qtkeychain packages in the isv:ownCloud:desktop repos and must not forget that.

**Comment by MTRichards** [comment]
Can we move this to the 1.8.3 milestone, or 2.0 milestone? As this is about to release, nothing should be left in here.

**Comment by danimo** [comment]
We are using 0.5 now.
