### ISSUE TITLE
[Nautilus] [Overlays] Multiple status indicator icons overlaid on file/folder

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#3249]
Sometimes I see this:
![capture du 2015-05-19 17 23 01](https://cloud.githubusercontent.com/assets/925062/7706623/cef35260-fe4b-11e4-9c42-05ed963c8bf3.png)

And this
![capture du 2015-05-19 17 24 06](https://cloud.githubusercontent.com/assets/925062/7706664/1d2eeb9c-fe4c-11e4-89cf-69ceed52e3e9.png)

Even though the folder / file is perfectly synced. Shouldn’t we make sure that there is always only _one_ indicator on top of each file? Otherwise it’s really confusing and makes me not trust the app. cc @dragotin @danimo

**Comment by guruz** [comment]
Please edit the bug title to mention which file manager etc

**Comment by jancborchardt** [comment]
Sure, sorry. This is with:
* GNOME nautilus 3.14.2
* client 1.8.0
* ownCloud latest stable 7

**Comment by GuillaumeAmat** [comment]
Is anyone know if it will be fixed soon? I see this bug dozen times a day...

**Comment by sebastien-villemot** [comment]
Same here with GNOME nautilus 3.14.1 and ownCloud client 2.0.2.

**Comment by ckamm** [comment]
Pull request #4736

**Comment by mcastroSG** [comment]
Hi hi:

**Steps executed**

1. Create folder1 at Shared sync folder 
2. Copy inside folder1 several files 

**Results**

![doubleoverlay](https://cloud.githubusercontent.com/assets/18436398/14855480/74edcab8-0c94-11e6-9d3e-8d6588078e05.png)

Double overlay icons are shown. This situation remains till the sync is finished.

Client Version: 2.2.0nightly2016427 (build 1571)
Client OS: Ubuntu 14.04 LTE

**Comment by guruz** [comment]
Did you verify if the nightly really contains the merged commit?
Did you try to re-login?

**Comment by ckamm** [comment]
@mcastroSG Build 1571 didn't include the patch, but build 1573 does. I checked by looking at the .tag file in the nightly-build archive and then checking whether the merge of the pull request was included there.

**Comment by mcastroSG** [comment]
Hi hi:

It works finally.

Client Version: Version 2.2.0beta2 (build 1582)
Client OS: Ubuntu 14.04 LTE
