### ISSUE TITLE
owncloudcmd in 1.8.1 client package

### ISSUE THREAD

**Issue by lelik9** [owncloud/client#3250]
Hi.
When I install 1.8.1 client on CentOS 6.6, he not contain owncloudcmd binary.

**Comment by jnweiger** [comment]
It is installed as /opt/qt-4.8/bin/owncloudcmd

For CentOS_6 we have a wrapper script that makes owncloud appear as /usr/bin/owncloud -- but we never had one for owncloudcmd.

**Comment by dragotin** [comment]
Thanks, cool!
