### ISSUE TITLE
Automatically update http to https

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#3251]
In #3226 @studersi asked:

> After moving the site from http to https the client starts up as usual and simply shows the icon with the dots, indicating that the connection couldn't be established. Is this the correct behavior or should the client also redirect to https like the website?

Should this be done?

**Comment by guruz** [comment]
@SamuAlfageme @ogoffart I wonder if this is really still happening now that we follow redirects?

**Comment by ogoffart** [comment]
right, we follow redirects, so the server has to enable redirect.
