### ISSUE TITLE
[1.8.1] Connection closed / Aborting

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#3252]
### Architecture
Client windows 7 1.8.1
Server 6.0.6

The client stops and displays the error:
#### Connection closed / Aborting
Image in the folder

### Full log file:

S3-ownCloud\Shared\owncloud\support\github-issues\client\3252

@MorrisJobke 

00003186

**Comment by guruz** [comment]
How is this related to #3248 ?
The logs are the same but different screenshot.

**Comment by guruz** [comment]
How reproducably do you get this issue?
I believe that 06c889630cb9834a5060286b2a2dac2c3bbbb881 could improve this.
Could you try with a recent nightly?

**Comment by guruz** [comment]
This is an updated ```Qt5Network.dll``` with a small patch that fixes this for me. Could you please test? It should match the DLLs shipped with 1.8.1

https://cloud.molkentin.net/index.php/s/LUPHW89fEBPZpTA

**Comment by guruz** [comment]
Dup of https://github.com/owncloud/client/issues/3248
