### ISSUE TITLE
background linux packaging update does not notify end user in client

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#3253]
I have 1.8.0 running on opensuse 13.1 -- yast already installed 1.8.1 as online update in the background.

The 1.8.0 client keeps running and its General tab says 'no updates available'

I expect to see a notification saying e.g: 
  An update has been installed. Please restart your owncloud client to complete the update.

Workaround: logout or reboot frequently.

**Comment by guruz** [comment]
The client could check if the mtime of its ```argv[0]``` changed.

**Comment by MTRichards** [comment]
We need to figure a way to either notify, or force reboot the client after an update.

**Comment by MTRichards** [comment]
Sev 2 for security reasons. If this doesn't get addressed, it is possible to keep a security vulnerability running forever by accident.

**Comment by jnweiger** [comment]
How about executing argv0 --help to check for a changed version number?

<pre>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

unsigned char *argv0 = "/usr/bin/owncloud";

main()
{
  unsigned char *opt = " --help";  // "--help 2>&1"; to be prepared for usage via stderr some day
  unsigned char *buf = (unsigned char *)calloc(strlen(argv0)+strlen(opt)+1,1);
  strcat(buf, argv0); strcat(buf, opt);

  FILE *fp = popen(buf, "r");
  free((void *)buf); buf = (unsigned char *)malloc(1024);
  fgets(buf, 1024, fp);        // buf = "ownCloud version 1.8.2rc1\n"
  fclose(fp);

  buf[strlen(buf)-1] = '\0';    // zap trailing newline
  unsigned char *vers = strstr(buf, "version");
  if (!vers) vers = buf; else vers += strlen("version");  // skip past the word "version" if its there.
  while (*vers == ' ') vers++;  // skip leading whitespace
  fprintf(stderr, "VERSION: '%s'\n", vers);
  free((void *)buf);
}

</pre>

**Comment by ogoffart** [comment]
I do not think it is a good idea to have this feature.

No other Linux software have that.  Even chromium or firefox.

If there is a bug we have the risk that the client restarts too often. Or restart while the user is doing something in the config.

I think that's not really playing well with the linux ecosystem.

**Comment by danimo** [comment]
@ogoffart Of course chrome does this. Not sure about Chromium though. And yes, distributors might strip that feature out. But that's fair enough.

And there is no need to terminate the application. We can just use the same notification that e.g. the windows updater uses (`"A new version is available. [ Restart ]"`)

**Comment by jnweiger** [comment]
@ogoffart I did not suggest an automated restart while the user does something important.
I suggest that the user is notified about the new install, and is kindly asked to restart the client himself. 

Doesn't that make a difference?

**Comment by guruz** [comment]
@jnweiger He meant that https://github.com/owncloud/client/issues/3472 does an automatic restart of the client
(and I agree with @ogoffart )

**Comment by dragotin** [comment]
I can change the patch obviously to only show a notification. @MTRichards what do you think?

**Comment by MTRichards** [comment]
The issue at the core is that the client does not restart when it is updated, thus a security patch lives on. If we do the restart of the client, then it would be good to let the customer know (in a popup notification as you say) that the client was restarted. Nothing more intrusive than that though is necessary.

**Comment by dragotin** [comment]
Well, the intrusive thing is the restart itself, as @ogoffart and @guruz point out. So the question is: Do we do the automatic restart or not? @MTRichards

**Comment by guruz** [comment]
Can we move this to 2.1?

**Comment by MTRichards** [comment]
A restart of the app itself is not that intrusive. It just starts over...don't want to restart the desktop itself, just the ownCloud client. It is not like a browser that restarts when you open it...that is pretty intrusive and still gets done. So, I would restart the client.
