### ISSUE TITLE
Possible that conflict files get a too long file name

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3255]
Related: https://github.com/owncloud/client/issues/2789

**Comment by MTRichards** [comment]
Should be fixed alongside the path length issue as well. https://github.com/owncloud/client/issues/60

**Comment by dragotin** [comment]
should be ready to test, as #60 is.

**Comment by Dianafg76** [comment]
I try this issue and working OK
Desktop v ownCloud-2.0.0.2587-nightly20150801.pkg 
I close
