### ISSUE TITLE
MKCOL request in Cherokee needs 'Content-Length: 0'

### ISSUE THREAD

**Issue by binwiederhier** [owncloud/client#3256]
The MKCOL request is not understood by the Cherokee webserver without a 'Content-Length: 0' header. While this is a bug in Cherokee, adding the header does not violate the WebDAV spec and does not cause problems with other webservers (I only tested Apache, though).

```
MKCOL /owncloud/remote.php/webdav/SSH HTTP/1.1
Authorization: Basic XXXXXXXXXXXXXXXXXXX
User-Agent: Mozilla/5.0 (Linux) mirall/1.8.0
Cookie: XXXXXXXXXXXXXXXXXX
Connection: Keep-Alive
Accept-Encoding: gzip
Accept-Language: en-GB,*
Host: 10.0.123.47

HTTP/1.1 411 Length Required
Connection: close
Date: Mon, 18 May 2015 14:26:58 GMT
Server: Cherokee
Content-Length: 206
Content-Type: text/html
Cache-Control: no-cache
Pragma: no-cache
```

Adding the content length works:

```
$ echo -e "MKCOL /owncloud/remote.php/webdav/new HTTP/1.1\r\nHost: 10.200.1.162\r\nContent-Length: 0\r\nAuthorization: Basic XXXXXXXXXXXXXX==\r\n\r\n" | nc 10.200.1.162 80
HTTP/1.1 201 Created
Date: Wed, 20 May 2015 11:15:44 GMT
Server: Cherokee
X-Powered-By:XXXXXXXXXX
Set-Cookie: XXXXXXXXXXXXXXXX=XXXXXXXX; path=/owncloud; HttpOnly
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
X-XSS-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: Sameorigin
Content-Security-Policy:default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *
X-Robots-Tag: none
Set-Cookie: XXXXXXXX; path=/owncloud; HttpOnly
Set-Cookie: logout=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/
OC-FileId: XXXXXXXXXXxx
Content-type: text/html
Content-Length: 0
```

**Comment by guruz** [comment]
Fix in https://github.com/binwiederhier/client/commit/14cb9c3358d98a9bef32c36b02058ba136e28e82 looks good.
Can you sign the contributor agreement and send a merge/pull request?

**Comment by binwiederhier** [comment]
I have not (yet) signed the contributor agreement, but here is a fix:

https://github.com/binwiederhier/client/commit/14cb9c3358d98a9bef32c36b02058ba136e28e82
I hereby officially allow you to do whatever you want with this piece of code. Do I still need to sign an agreement?

**Comment by guruz** [comment]
Did you also test deleting files and moving files?

**Comment by binwiederhier** [comment]
Not yet. Will do later today.

**Comment by guruz** [comment]
@karlitschek Can you clarify the contributor agreement requirement? https://github.com/owncloud/client/issues/3256#issuecomment-103859319

**Comment by binwiederhier** [comment]
Pull. https://github.com/owncloud/client/pull/3257
Contributor agreement signed and sent to @karlitschek.

**Comment by karlitschek** [comment]
@binwiederhier Thanks you should get an github invite now.

**Comment by gig13** [comment]
@MTRichards @bboule

**Comment by guruz** [comment]
@bboule there is no .1 milestone, th is after the release.

**Comment by bboule** [comment]
Sorry for the screw up on the milestone  my fault!!

**Comment by bboule** [comment]
@gig13 you write ETA 2 weeks can I assume this resolves this for you?

**Comment by gig13** [comment]
@bboule 
This was communicated to @binwiederhier  to be available in 2 weeks, we just need to track and make sure it hits.

**Comment by gig13** [comment]
@craigpg 
When is 1.8.2 going to be available?

**Comment by gig13** [comment]
@danimo @MTRichards 
When will 1.8.2 be available for customers and branding

**Comment by MTRichards** [comment]
Once it is released. We can't brand RC or beta clients at this time.

I think we are 2-3 weeks from 1.8.2.
