### ISSUE TITLE
In the DESKTOP fill server URL with SHIBBOLETH, when you write the name/password and connect it is appears an ERROR

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3259]
### Steps to reproduce
1. Open your onwCloud Desktop client
2. Fill in the server url with shibboleth
3. Click NEXT
4. Write the User/password the shibboleth
5. Click NEXT
6. In Local Folder select for example “Start a clean sync”
7. Click CONNECT...
8. Appears an error

### Expected behaviour
You can connect with the user Shibboleth in OwnClound Deskopt

### Actual behaviour
It is appears an error
![screen shot 2015-05-20 at 14 00 38](https://cloud.githubusercontent.com/assets/12032058/7729717/9c084538-ff16-11e4-86a3-adcb83d611fc.png)

### Server configuration
OwnCloud DESKTOP v 1.8.2 (build 2372) MAC

**Comment by danimo** [comment]
As the error indicates, that's a server error (which I cannot reproduce). Works beautifully over here (1.8.1 and current 1.8 branch).
