### ISSUE TITLE
The blacklist table structure isn't migrated correctly

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#3260]
See owncloud/core#15189 where @razyr reports seeing this:

![74c33738-febe-11e4-8b73-bcf30cc3884a](https://cloud.githubusercontent.com/assets/833306/7743269/63a99f10-ff99-11e4-875b-ecd8589961b5.jpg)

The migration code should have added lastTryTime and ignoreDuration!

**Comment by ckamm** [comment]
My mistake, the blacklist improvements were only introduced with 1.8.0...

**Comment by moscicki** [comment]
Hi,
What is the consequence of this?
Does this mean that downgrading from 1.8 to 1.7 could be a problem?
