### ISSUE TITLE
Feature Request: Enable right click-mailto function for Links in the Windows client.

### ISSUE THREAD

**Issue by Kawohl** [owncloud/client#3261]
Windows client. A right click on a Link should open the dropdown context menu and display  "add this file to a new e-mail" and open the e-mail application and attach the link to the file.
@hodyroff

EDITED: Add  mail subject "$userName has shared $filename with you"

**Comment by Dianafg76** [comment]
@Kawohl Thanks for your feedback, cc @jancborchardt. Would this work for you?

**Comment by jancborchardt** [comment]
Instead of right-click which is hard to discover, this should be done with a button. Next to »Copy link«, there should be »Mail link« – which automatically opens the email app defined as standard and pastes the link into the message body, ideally with a predefined message (as we do in the mobile apps cc @rperezb @MTRichards)

**Comment by Kawohl** [comment]
@dragotin

**Comment by rperezb** [comment]
@jancborchardt being possible i'd add to prepolulate the mail subject in iOS we use:

"$userName has shared $filename with you"

@dragotin we talked about this in Nuremberg 😉

**Comment by dragotin** [comment]
@rperezb yes, but not all I talk about is implemented immediately.... unfortunately :o)

**Comment by dragotin** [comment]
@MTRichards something to consider for the next version maybe? Not too big effort.

**Comment by MTRichards** [comment]
Lol. I just put this on our sheet for discussions...

**Comment by jancborchardt** [comment]
@rperezb @dragotin yeah, sounds good, also with the predefined message.

**Comment by rperezb** [comment]
@Kawohl i edited your issue so that the mail subject criteria is not lost over the comments

**Comment by ckamm** [comment]
Pull request: #4961

**Comment by mcastroSG** [comment]
Hi:

**Steps Executed**
1.- Right click on a file at Shared Sync folder 
2.- Select Share with ownCloud option
3.- Click on Mail Link

**Results**
A new pop-up window appears associated to our default mail app. Subject and Body contains proper info.
