### ISSUE TITLE
Folder Blacklist not preserved on Reconfiguration

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#3262]
If you reconfigure an existing account, the selective sync blacklist is reset to empty. If the account is the same (url and user), the blacklist should be re-used.

**Comment by ogoffart** [comment]
This will be solved.  I am now storing the blacklist in the database for the confirm feature

**Comment by ogoffart** [comment]
https://github.com/owncloud/client/pull/3281

(note that it will not be possible to reconfigure existing account in the new version of the client due to multi account

**Comment by guruz** [comment]
Closing as I understand that this is fixed with 2.0
