### ISSUE TITLE
[Sharing] When you share a file with two users and unchecked the opcion EDIT, CREATE, DELETED and UPDATE, when you go to the DESKTOP you can create a new FILE, when is SYNC you have an error but the icon to the File sync

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3263]
### Steps to reproduce
1. Open your Owncloud Web client, with the user1
2. Create a new Folder, called bb
3. Share the Folder bb with other user (user2)
4. Unchecked the option 'Edit', 'Delete', 'Update', 'Create'
5. Open your Owncloud Desktop client, with the user2
6. Go to Open Folder "ownCloud"
7. Wait for it to sync
8. Create a File call cc into the Folder bb
9. Wait to sync

### Expected behaviour
The icon should be red

### Actual behaviour
When you Edit and Write the File cc with the user2, Is not sync, it is appears an error

![screen shot 2015-05-21 at 13 57 26](https://cloud.githubusercontent.com/assets/12032058/7748060/6aa66c9e-ffc1-11e4-9ea6-86d38e5af98d.png)

The firts time when you sync the icon to the file is red, but then the icon is blue all the time is sync the file

![screen shot 2015-05-21 at 14 00 14](https://cloud.githubusercontent.com/assets/12032058/7748096/bd870a36-ffc1-11e4-9ade-664758c4fa8f.png)

### Server configuration
DESKTOP v1.8.2 (build 2373) MAC
WEB SERVER: {"installed":"true","version":"7.0.1.1","versionstring":"7.0.1","edition":""}

**Comment by dragotin** [comment]
No, the icon should not be red. We do not want to annoy the user with this kind of problems. The main thing is that the read only data from the server is restored if the user changes it.

I think this is a wont-fix.

**Comment by dragotin** [comment]
Closing hence. Thanks

**Comment by Dianafg76** [comment]
@dragotin Thank you
