### ISSUE TITLE
[Share link] When I share a folder with two options ( password and expiry date ) on the desktop and then disable the password option , the expiration date is disable

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3265]
### Steps to reproduce
1. Open your ownCloud desktop client
2. Go to Open Folder "ownCloud"
3. Create a new Folder or Fiel, called dd
4. Right click on the folder dd
5. Select share with ownCloud
6. Select Password protect and Set expiration date
7. Click in "Close"
8. Right click on the folder dd, again
9. Disable the option Password protect

### Expected behaviour
Should not disable the expiration date of the option

### Actual behaviour
The option Expiration date is disabled

### Server configuration
DESKTOP v1.8.2 (build 2373) MAC
WEB SERVER: {"installed":"true","version":"7.0.1.1","versionstring":"7.0.1","edition":""}

**Comment by dragotin** [comment]
This is a server bug in the share API: The client sends two PUT requests to the server to update the share: One for the expire date (which is still the desired value), and one with an empty password. That is valid as the server only accpets one value to be changed with an update.

After the two PUTs  it GETs the information about the share back from the server, and the result has an null-expiration, which is wrong.

**Comment by dragotin** [comment]
tracked in https://github.com/owncloud/core/issues/16735

**Comment by rullzer** [comment]
This is already fixed in master (so 8.1). And PR https://github.com/owncloud/core/pull/16738 should fix it in stable8. Probably will be 8.0.5 before the fix is in.

**Comment by jnfrmarks** [comment]
@Dianafg76 

When I tested this with 1.8.3 client and 8.0.5, the Password Protect checkbox was not checked at step 8.

**Comment by Dianafg76** [comment]
@jnfrmarks, I tested again and happend the same.
###Steps to reproduce

   1. Open your ownCloud desktop client
   2. Go to Open Folder "ownCloud"
   3. Create a new Folder or Fiel, called dd
   4. Right click on the folder dd
   5. Select share with ownCloud
   6. Select Password protect and Set expiration date
![screen shot 2015-06-30 at 08 55 24](https://cloud.githubusercontent.com/assets/12032058/8425423/e4423d72-1f05-11e5-9d85-fb7bac3231ec.png)

   7. Click in "Close"
   8. Right click on the folder dd, again
   9. Disable the option Password protect
![screen shot 2015-06-30 at 08 55 39](https://cloud.githubusercontent.com/assets/12032058/8425432/f7b67ad0-1f05-11e5-9f5d-0b809febf6ad.png)

### Server configuration
DESKTOP v ownCloud-1.8.4.2475-nightly20150629.pkg  
SERVER v {"installed":true,"maintenance":false,"version":"8.0.5.0","versionstring":"8.0.5beta","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
I try this with ownCloud v Desktop - 2.0.0.2555 - nightly20150722.pkg and Server v { "installed ": true, "maintenance" : false, "version" , " 8.1.0.8 ", " versionstring ": " 8.1 RC2 " " edition " , " Company "} . And it happens the same

**Comment by dragotin** [comment]
I can not reproduce this here with mac nightly build from 23-07, with gold 8.1 server. The expiration date stays set if I disable the password.

**Comment by Dianafg76** [comment]
@dragotin, You are right. So I close the topic. So I close the issue
Many thanks :-)
Desktop v  ownCloud-2.0.0.2559-nightly20150723.pkg
