### ISSUE TITLE
Startup stalls sometimes

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#3266]
Sometimes with the current 1.8 branch the client takes 30s to connect to the server:

```
05-22 03:22:20:423 0x4f11758 networkjobs.cpp:625 status.php returns:  QMap(("edition", QVariant(QString, "enterprise") ) ( "installed" ,  QVariant(QString, "true") ) ( "version" ,  QVariant(QString, "6.0.6.1") ) ( "versionstring" ,  QVariant(QString, "6.0.6") ) )    0  Reply:  QNetworkReplyHttpImpl(0x66058a0)
05-22 03:22:20:423 0x4f11758 connectionvalidator.cpp:109 ** Application: ownCloud found:   QUrl( "https://SERVER" )   with version  "6.0.6" ( "6.0.6.1" )
05-22 03:22:20:423 0x4f11758 accountstate.cpp:179 ConnectionValidator already running, ignoring
05-22 03:22:52:219 0x4f11758 account.cpp:291 Resetting QNAM
05-22 03:22:52:221 0x4f11758 connectionvalidator.cpp:66 Checking server and authentication
```

I think this happens when the credentials are fetched after the status.php has been found. It used to be that another ConnectionValidator would immediately try the new credentials. With the change to have only one ConValidator running at a time it has to wait for the 32s interval to come around for the new credentials to be tested.

**Comment by Dianafg76** [comment]
I tested the issue, it is working fine. I closed
Desktop v 1.8.2 (build 2388)
Server v {"installed":true,"maintenance":false,"version":"8.1.0.6","versionstring":"8.1 beta 2","edition":"Enterprise"}
