### ISSUE TITLE
Try to Write Credentials to Keychain after User entered it

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#3268]
If the client can not find the credentials in qtkeychain, a popup comes up asking the user to enter the creds. If these authenticate successfully, it should be tried to write it to QtKeychain again. Otherwise, user will have to completely reconfigure the account to get the credentials into the Keychain.

Usecase: User configured the client and, while doing that, realizes that his kwallet/keyring does not work. She fixes it, but keychain does never again pick up the credentials.

Also, in the dialog that asks for the credentials a hint would be great that the keychain does not work, and could be fixed, in case that faulty keychain can be identified.

**Comment by ckamm** [comment]
@dragotin I don't quite understand. Currently, when a `queryPassword()`succeeds in `httpcredentials.cpp`, the new credentials are explicitly persisted.

I can definitely add an error hint to the password dialog if the keychain job fails with something else than EntryNotFound.

**Comment by ckamm** [comment]
@dragotin I just tested this by
* delete an account, delete the password in kwallet
* disable kwallet
* make a new account, verify that the password could not be saved
* enable kwallet
* once entered, the password gets saved in the keychain correctly

**Comment by dragotin** [comment]
Ok, maybe I saw that with an older client. Sorry for the noise. @Dianafg76 it would be great if you could verify.

**Comment by Dianafg76** [comment]
@ckamm Hello, I can't reproduce this issue, could you help me
