### ISSUE TITLE
Owncloud Client not syncing shares of newly added groups

### ISSUE THREAD

**Issue by shoelzle** [owncloud/client#3274]
### Steps to reproduce
Add user to a group which has shared folders/files

### Expected behaviour
I'd expect the owncloud client to sync the shares of the newly added group.

### Actual behaviour
Owncloud client is not syncing the shares of the newly added group.
However the newly added groups shares are listed and checked in the "Choose what to sync" dialog.
If I uncheck the shares in the "Choose what to sync" dialog, and check them again afterwards, the shares are synced.

### Server configuration
**Operating system**: openSUSE 13.2
**Web server:** apache2 2.4.10
**Database:** mysql 5.6.17
**PHP version:** 5.6.1
**ownCloud version:** 8.0.3
**Updated from an older ownCloud or fresh install:** updated from v7
**List of activated apps:** Activity, Calendar, Contacts, Deleted Files, First Run Wizard, PDF Viewer, Pictures, Share Files, Tasks, Text Editor, Updater, Versions, Video Viewer, WebDAV user backend

**The content of config/config.php:**
```
<?php
$CONFIG = array (
  'maintenance' => false,
  'instanceid' => 'xxxx',
  'passwordsalt' => 'xxxx',
  'trusted_domains' =>
  array (
    0 => 'oc.anonymox.net',
  ),
  'datadirectory' => 'xxx',
  'dbtype' => 'mysql',
  'version' => '8.0.2.0',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => 'xxx',
  'installed' => true,
  'forcessl' => true,
  'updatechecker' => false,
  'theme' => '',
  'share_folder' => '/Shared',
  'secret' => 'xxx',
  'loglevel' => '1',
);
```

**Are you using external storage, if yes which one:** no
**Are you using encryption:** no
**Are you using an external user-backend, if yes which one:** Webdav

### Client configuration
**Client version:** 1.8.1
**Operating system:** openSUSE 13.2
**OS language:** en
**Installation path of client:** /home/user/tmp/oc_test/syncfolder
### Logs
nothing interesting here, sorry

**Comment by Dianafg76** [comment]
@shoelzle 
Could try the with the latest client version, v 1.8.2?
You may download it from:
http://download.owncloud.com/desktop/daily/ownCloud-1.8.2.5138-nightly20150603-setup.exe

Thanks!!

**Comment by Dianafg76** [comment]
Closed for inactivity, if this is still a issue, please reopen

**Comment by shoelzle** [comment]
It's still an issue.
I tried the latest version, which is now 1.8.2.
I haven't tried the latest nightly build.

Any ideas how to debug this ?

**Comment by ogoffart** [comment]
Could you please provide the client log.  I suspect this is because the server does not change the directories etag or something similar

**Comment by MTRichards** [comment]
As we are touching this area in client 2.0 we should try to address this in that release.

**Comment by shoelzle** [comment]
Log is available on pastebin for 30 days from now: http://pastebin.com/EqfAnJY9
I added the user to a group with shared files about 20:32. Nothing happens long after the default polling intervall of 30 sec has passed.

**Comment by ogoffart** [comment]
Thanks for the log.  The problem is that the server did not report any etag changes. 
Please make an issue on the 'core'  bug tracker. This is a server issue.

**Comment by ogoffart** [comment]
The issue can now be tracked there: https://github.com/owncloud/core/issues/17301
