### ISSUE TITLE
WebClient doesnt load

### ISSUE THREAD

**Issue by philwe** [owncloud/client#3282]
Hi guys,

when I open owncloud I can see that the proccess is running, but there is no tray icon nor is owncloud working.

my logfile:
05-26 15:13:09:767 0x402e7f0 OCC::Application::setupLogging: "################## ownCloud de_DE () 1.8.1 (build 5050)"
05-26 15:13:09:767 0x402e7f0 OCC::Application::setupTranslations: void OCC::Application::setupTranslations() Using "de_DE" translation
05-26 15:13:09:767 0x402e7f0 OCC::SocketApi::SocketApi: SocketApi:  creating "//./pipe" false
05-26 15:13:09:767 0x402e7f0 OCC::SocketApi::SocketApi: SocketApi:  server started, listening at  "\\.\pipe\ownCloud"
05-26 15:13:09:767 0x402e7f0 OCC::SocketApi::slotReadExcludes: ==== added system ignore list to socketapi: "C:/Program Files (x86)/ownCloud/sync-exclude.lst"
05-26 15:13:09:767 0x402e7f0 OCC::SocketApi::slotReadExcludes: ==== added user defined ignore list to csync: "C:/Users/phil/AppData/Local/ownCloud/sync-exclude.lst"
05-26 15:13:09:767 0x402e7f0 OCC::FolderMan::FolderMan: setting remote poll timer interval to 30000 msec
05-26 15:13:10:033 0x402e7f0 OCC::FolderMan::setupFolders: * Setup folders from  ""
05-26 15:13:10:033 0x402e7f0 OCC::FolderMan::setupFolderFromConfigFile:   ` -> setting up: "SHARiNG"
05-26 15:13:10:033 0x402e7f0 OCC::FolderMan::setupFolderFromConfigFile:     -> file path:  "C:/Users/phil/AppData/Local/ownCloud/folders/SHARiNG"
05-26 15:13:10:033 0x402e7f0 OCC::Folder::checkLocalPath: Checked local path ok
05-26 15:13:10:033 0x402e7f0 OCC::FolderMan::setupFolderFromConfigFile: Adding folder to Folder Map  OCC::Folder(0x56ba7b8)
05-26 15:13:10:033 0x402e7f0 OCC::FolderMan::slotScheduleSync: Schedule folder  "SHARiNG"  to sync!
05-26 15:13:10:033 0x402e7f0 OCC::FolderMan::startScheduledSyncSoon: Scheduling a sync in 2 seconds
05-26 15:13:10:033 0x402e7f0 OCC::FolderMan::setupFolderFromConfigFile:   ` -> setting up: "own-sync"
05-26 15:13:10:033 0x402e7f0 OCC::FolderMan::setupFolderFromConfigFile:     -> file path:  "C:/Users/phil/AppData/Local/ownCloud/folders/own-sync"
05-26 15:13:10:033 0x402e7f0 OCC::Folder::checkLocalPath: Checked local path ok
05-26 15:13:10:033 0x402e7f0 OCC::FolderMan::setupFolderFromConfigFile: Adding folder to Folder Map  OCC::Folder(0x56baad0)
05-26 15:13:10:033 0x402e7f0 OCC::FolderMan::slotScheduleSync: Schedule folder  "own-sync"  to sync!
05-26 15:13:10:033 0x402e7f0 OCC::ClientProxy::setupQtProxyFromConfig: Set proxy configuration to use NO proxy
05-26 15:13:10:033 0x402e7f0 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
05-26 15:13:10:033 0x402e7f0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

05-26 15:13:10:033 0x402e7f0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
05-26 15:13:10:033 0x402e7f0 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
05-26 15:13:10:033 0x402e7f0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

05-26 15:13:10:033 0x402e7f0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
05-26 15:13:10:033 0x402e7f0 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
05-26 15:13:10:033 0x402e7f0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

05-26 15:13:10:033 0x402e7f0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
05-26 15:13:10:033 0x402e7f0 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
05-26 15:13:10:033 0x402e7f0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

05-26 15:13:10:033 0x402e7f0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available

**Comment by danimo** [comment]
We have resolved this already. Please try 1.8.2-beta1. https://owncloud.org/install/#testing-development
