### ISSUE TITLE
Sync client switches to SSL all by itself!

### ISSUE THREAD

**Issue by RobBentley** [owncloud/client#3284]
We have some SYNC clients on our local LAN where we do not wish to use SSL. For some reason however after a few hours, the sync client magically switches to using SSL without a full re-sync. Obviously we're unable to switch the client back to non-SSL easily, as changing the server address from https:// to http:// causes a full re-sync.

Any ideas why this might be? Server and Sync Client (on MAC) are both the latest version. We've seen this issue for months through various sync client and server updates.

**Comment by ckamm** [comment]
@RobBentley You are saying you observe the following?

* Configure account for http://my.server
* Sync operates normally via http
* After some time it silently switches to https
* When you click 'modify account' the url for the account is https://my.server

That's extremely surprising. I had a look at the code and don't have a theory on how that could happen yet. An account's URL is generally only set within the account wizard or when loading an account from settings.

Are you convinced it actually uses http at the start? Can you reproduce this with an account that has very few files and upload the sync client log file? (see https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly)

**Comment by RobBentley** [comment]
Hi

This is exactly the symptoms we are seeing, and we’ve been experiencing this for months. We have three separate offices which all connect to an own cloud server in a central data-centre. The odd thing is not ALL sync clients seem to switch and the time taken to switch varies. My own Mac Mini is still connected via HTTP absolutely fine after 3 months of usage, my Macbook Pro laptop has magically switched itself to using HTTPS (it did this after a number of weeks)… and I configured a new iMac for a colleague of mine a few weeks back, and within 2 days I noticed he was on HTTPS.

Kind Regards,

Rob Bentley
SynergyWorks Internet
www.synergyworks.co.uk<http://www.synergyworks.co.uk/>
Tel: +44 (0)1622 808456
Fax: +44 (0)1622 808457
Find us on Facebook: http://facebook.com/SynergyWorks<http://on.fb.me/bDlhEQ>
Follow us on Twitter: http://twitter.com/SynergyWorksKSP

** Signup to Service Status Updates: http://status.synergyworks.co.uk<http://status.synergyworks.co.uk/> **
** We are now peering on LONAP: http://as41659.peeringdb.com<http://as41659.peeringdb.com/> **

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message may contain confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. Warning: Although the company has taken reasonable precautions to ensure no viruses are present in this email, the company cannot accept responsibility for any loss or damage arising from the use of this email or attachments.Hi.

**Comment by ckamm** [comment]
I'll check again for whether there's something about restoring from settings that could cause this, but currently I just don't see a mechanism for how this could happen. Does it happen when you don't restart the client? Catching this in a log file would be great, but probably hard to do.

**Comment by RobBentley** [comment]
Hi.

I can’t say for sure if its restarting the clients that does this, but I would be inclined to say its not – as the iMAC that did this after only 2 days, I very much doubt it would have been restarted in that time. I’ll see if I can catch this in a log file, but it may be difficult.

As a side note, I have not tested this problem across platforms. We use exclusively MAC, so I don’t know if the problem occurs in a Windows sync client.

Kind Regards,

Rob Bentley
SynergyWorks Internet
www.synergyworks.co.uk<http://www.synergyworks.co.uk/>
Tel: +44 (0)1622 808456
Fax: +44 (0)1622 808457
Find us on Facebook: http://facebook.com/SynergyWorks<http://on.fb.me/bDlhEQ>
Follow us on Twitter: http://twitter.com/SynergyWorksKSP

** Signup to Service Status Updates: http://status.synergyworks.co.uk<http://status.synergyworks.co.uk/> **
** We are now peering on LONAP: http://as41659.peeringdb.com<http://as41659.peeringdb.com/> **

This email and any files transmitted with it are confidential and intended solely for the use of the individual or entity to whom they are addressed. If you have received this email in error please notify the system manager. This message may contain confidential information and is intended only for the individual named. If you are not the named addressee you should not disseminate, distribute or copy this e-mail. Please notify the sender immediately by e-mail if you have received this e-mail by mistake and delete this e-mail from your system. Warning: Although the company has taken reasonable precautions to ensure no viruses are present in this email, the company cannot accept responsibility for any loss or damage arising from the use of this email or attachments.

**Comment by ckamm** [comment]
Unfortunately we were unable to find the problem. :/
