### ISSUE TITLE
SSL handshake error with "SSLVerifyClient optional"

### ISSUE THREAD

**Issue by auxsvr** [owncloud/client#3287]
### Expected behaviour
The client should connect to the server. Using the browser works fine.

### Actual behaviour
The error message:

> Error while reading: error:140943F2:SSL routines:SSL3_READ_BYTES:sslv3 alert unexpected
> message, error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure

appears and no connection occurs. SSLv3 is disabled in the virtual host.

### Steps to reproduce
1. Set "SSLVerifyClient optional" in the vhost configuration.
2. Start the client

### Server configuration
Operating system: openSUSE 13.2

Web server: apache-2.4.10

Database: mysql-community-server-5.6.17

PHP version: 5.6.1

ownCloud version: 8.0.3

Storage backend:

### Client configuration
Client version:1.8.1

Operating system: openSUSE 13.2

OS language: en_US

Installation path of client: /usr/bin

### Logs
Output of owncloudcmd:
> !!! OCC::LsColJob created for "https://website.org/owncloud/" + ""
> void OCC::AbstractNetworkJob::slotFinished() 99 "Error while reading: error:140943F2:SSL routines:SSL3_READ_BYTES:sslv3 alert unexpected message, error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure"
> void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply*) "Error while reading: error:140943F2:SSL routines:SSL3_READ_BYTES:sslv3 alert unexpected message, error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure" 0 99
> void OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot(int, QString) 5 "Error while reading: error:140943F2:SSL routines:SSL3_READ_BYTES:sslv3 alert unexpected message, error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure"
> static csync_vio_handle_t* OCC::DiscoveryJob::remote_vio_opendir_hook(const char*, void*) OCC::DiscoveryJob(0xc8fd30)  ...Returned from main thread
> static csync_vio_handle_t* OCC::DiscoveryJob::remote_vio_opendir_hook(const char*, void*) 5 when opening  msg= "Error while reading: error:140943F2:SSL routines:SSL3_READ_BYTES:sslv3 alert unexpected message, error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure"
> [05/27 22:38:12.693470, 4] csync_ftw:  opendir failed for ownclouds://website.org/owncloud/remote.php/webdav - errno 5
> [05/27 22:38:12.695540, 6] csync_statedb_close:  sqlite3_close=0
 #### ERROR during  csync_update :  "An error occurred while opening a directory Error while reading: error:140943F2:SSL routines:SSL3_READ_BYTES:sslv3 alert unexpected message, error:140940E5:SSL routines:SSL3_READ_BYTES:ssl handshake failure"
> CSync run took  3052
> void OCC::SyncJournalDb::close() "/home/auxsvr/uoa/.csync_journal.db"
> No database Transaction to commit

Relevant output of the vhost error log:
> [ssl:error] [pid 6638] [client 127.0.0.1:45362] AH02261: Re-negotiation handshake failed: Not accepted by client!?

**Comment by guruz** [comment]
@auxsvr With which Qt was your client built? (you can see it in the log at beginning of sync run or in settings dialog). Maybe a Qt5 build works better?

FYI @richmoore @danimo

**Comment by auxsvr** [comment]
Qt 5.3.2, openssl 1.0.1i-fips 6 Aug 2014. I've also tried an old Qt4 version with the same result.

**Comment by Enoch247** [comment]
This also affects users who enable ```SSLVerifyClient required``` for folders on the same vhost, but not related to owncloud. See example apache config:

    # SSL client authentication 
    <Location "/foo)">
        SSLVerifyClient require
    </Location>

    # turn off SSL client authentication for owncloud
    <Location "/owncloud">
      SSLVerifyClient none
    </Location>

**Comment by guruz** [comment]
@Enoch247 SSL is per socket (per host:port, via SNI) not per directory

**Comment by Enoch247** [comment]
I don't understand all the particulars of SSL, but according to Apache's site, client certificates are per directory:
http://httpd.apache.org/docs/2.2/ssl/ssl_howto.html#arbitraryclients

**Comment by ogoffart** [comment]
The owcloud client does not support client certificate.
There is preliminary support for it but the implementation was never finished [https://github.com/owncloud/client/issues/69]

Other than that it looks like a configuration problem in the server and not a bug in the client.
