### ISSUE TITLE
Breakpoints are not getting hit, not working for client - 1.8.1

### ISSUE THREAD

**Issue by tusharh** [owncloud/client#3288]
Hi,
I was previously working on 1.5.4 code. I am shifting to 1.8.1. Build is successful, on clicking debug button application launches but breakpoints don't get hit, breakpoints aren't working. I tried this scenario on 3 machines. 2 opensuse 13.1 machines & 1 Mac 10.10. Everywhere on debugging client is launched but breakpoints aren't working. Same is the case with 1.7.

My Qt details:
Qt creator 3.3.1
Based on Qt 5.4.1 (GCC 4.6.1, 64 bit)
Built on Feb 20 2015

Machine details:
Linux linux-s17i 3.11.6-4-desktop #1 SMP PREEMPT Wed Oct 30 18:04:56 UTC 2013 (e6d4a27) x86_64 x86_64 x86_64 GNU/Linux

**Comment by tusharh** [comment]
SET(CMAKE_BUILD_TYPE Debug) added this line to CMakeLists.txt and now I am able to debug now. Breakpoints are getting hit properly :) This needs to be commited in the code.

**Comment by danimo** [comment]
@tusharh Nope, `cmake -DCMAKE_BUILD_TYPE=Debug` works just as well...

**Comment by tusharh** [comment]
Yes, correct - that is the best option. Thanks..!!
