### ISSUE TITLE
[Sharing Link] error code 404: with Folder (after the name leaves a space)

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3297]
### Steps to reproduce
1. Open your ownCloud desktop client
2. Go to Open Folder "ownCloud"
3. Create a new folder, called 321 and space in the end
4. Right click on the folder 321
5. Select share with ownCloud

### Expected behaviour
You can share the folder

### Actual behaviour
Is appears "OCS API error code:404". 
![screen shot 2015-06-01 at 10 00 47](https://cloud.githubusercontent.com/assets/12032058/7908452/74791262-0845-11e5-884f-4a9ea6380e06.png)

### Server configuration
DESKTOP v1.8.2 (build 2396) MAC

**Comment by Dianafg76** [comment]
I tested this issue with Desktop v ownCloud-2.0.0.2559-nightly20150723.pkg, and it is the same

**Comment by rullzer** [comment]
Ok I found the problem. The socket api trimms the string that it receives. So all trailing white space is also removed (even if it is part of the command). Lets see how we can fix this the easiest.

**Comment by guruz** [comment]
btw, files/folders with space at end are illegal on Windows anyway.

FYI @ogoffart

**Comment by ogoffart** [comment]
Socket API should not trim.

**Comment by Dianafg76** [comment]
I tested this issue, and is working OK. Now you can share with no problem
Desktop v ownCloud-2.1.0.2831-nightly20151027.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}
Closed
