### ISSUE TITLE
[1.8.1] [Discovery] XML "Premature end of document."

### ISSUE THREAD

**Issue by pako81** [owncloud/client#3298]
Customer is facing sync issues with their Linux and Mac clients. The sync clients just got stucked  at some point.

ownCloud Client Version: 1.8.1
ownCloud Server Version: 7.0.5

Below the most relevant lines in my opinion from the linux client and server log files.

Linux client:

(removed)

I have however included the whole log files and screenshots from the clients in:

S3-ownCloud\Shared\owncloud\support\github-issues\client\3298

@MorrisJobke @dragotin could you please help me out?

00003268

**Comment by dragotin** [comment]
Can somebody translate for us 
```
05-27 15:04:49:787 0x7f8223d139a0 OCC::SyncEngine::handleSyncError:  #### ERROR during  csync_update :  "Une erreur est survenue lors de l'ouverture d'un dossier. Erreur inconnue"
```

I bet this is *Connection cancelled* which will be fixed with 1.8.2.

**Comment by pako81** [comment]
That is:

"An error occured when opening a folder/file. Unknown error"

**Comment by michaelstingl** [comment]
@dragotin Thats why you shouldn't translate error messages in client log.

**Comment by ogoffart** [comment]
It seems we have a parse error of the PROPFIND reply:

```
05-27 15:04:49:457 0x7f8223d139a0 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://drive.switch.ch" + "/Bureau/Perso/archives/informatique/sites/newgem/GEM Folder/GEM/nuke/modules/Members_List"
05-27 15:04:49:784 0x7f8223d139a0 OCC::LsColXMLParser::parse: ERROR "Fin de document inattendue." ""
```

`Fin de document inattendue`  -> `unexpected end of the document`

So this seems to mean that there was an error while parsingthe xml answer, possibly because it stops too early but it could be another reason.

Does this problem is always reproducible? 

A traffic dump would be usefull or we would have to add more debug output to find out why we can't parse that.

**Comment by ogoffart** [comment]
Actually, we know the xml, and it is empty (that's the second string in the debug message).  But why would it be empty?

**Comment by jcfischer** [comment]
@pako81 please, please, please sanitze logfiles before uploading them. Usernames, filenames MUST be censored before you upload them

**Comment by jcfischer** [comment]
@ogoffart as far as I can tell the problem is reproducible. I will ask that specific and see if the problem persists.

Please note that we see quite a few of these XML parse errors / unexpected end of document cases.

**Comment by danimo** [comment]
@jcfischer Removed for now, this must not happen again. Sorry.

**Comment by jcfischer** [comment]
@danimo thanks!

**Comment by ogoffart** [comment]
Anyway, it would be nice if we could find a way to reproduce the problem.  Or have a wireshark capture of the sync when this error happens, to confirm that one of the reply to the PROPFIND is indeed empty while still having a valid 207 code. and find out why this happens.

**Comment by jcfischer** [comment]
I have just sent an email to support with one log file (Won't paste the link here, but if you need it I can send a PM)

**Comment by pako81** [comment]
Added this last log file named "SwitchDriveLog_Eschle_150604" to 
S3-ownCloud\Shared\owncloud\support\github-issues\client\3298

**Comment by guruz** [comment]
The OS X screenshots looks similar to #3318 ..
We have a nightly build of 1.8.3 in http://download.owncloud.com/desktop/daily/ownCloud-1.8.2.2422-nightly20150610.pkg .. can you test that?

We'll also have an Windows 1.8.3 candidate available in the next days..

**Comment by guruz** [comment]
Please try http://download.owncloud.com/desktop/daily/ownCloud-1.8.3.5188-nightly20150612-setup.exe for Windows or http://download.owncloud.com/desktop/daily/ownCloud-1.8.3.2432-nightly20150613.pkg for OS X

**Comment by guruz** [comment]
Client rc3 is out..

**Comment by enoch85** [comment]
1.8.3 is released. Close.

**Comment by schnidrig** [comment]
This is still not fixed.

I've got a customer who ran into the exact same problem with 1.8.4.

client log:
09-14 13:17:50:347 0x56ccd98 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://drive.switch.ch" + "[removed]"
09-14 13:17:50:624 0x56ccd98 OCC::LsColXMLParser::parse: ERROR "Premature end of document." ""

Nginx error log:

2015/09/14 13:17:49 [error] 2052#0: *41293172 readv() failed (104: Connection reset by peer) while reading upstream, client: [removed], server: drive.switch.ch, request: "PROPFIND [removed] HTTP/1.1", upstream: "fastcgi://unix:/var/run/php5-fpm.sock:", host: "drive.switch.ch"


I'll sent the full logs to oc support

**Comment by michaelstingl** [comment]
@guruz here you can download the new logs:
S3/Shared/owncloud/support/github-issues/client/3298/

00003820

**Comment by guruz** [comment]
@michaelstingl Did any other customer/user report this with another server? Can you privately send me the test credentials?
I see the ```Premature end of document``` and a broken or empty XML in the log you uploaded but I wonder where to look for the cause..

**Comment by michaelstingl** [comment]
@guruz I asked the user for a test account.

**Comment by michaelstingl** [comment]
@guruz Sorry, no test account available. I will ask to test with the branded 2.0.2…

**Comment by ogoffart** [comment]
Does this problem still happen with 2.0.2
This might be a valid error because the server return invalid XML or a proxy is cuting it.  If the error message is not explicit enough, we should change it.

**Comment by schnidrig** [comment]
Yes ist still happens with 2.0.2

**Comment by guruz** [comment]
@schnidrig How to reproduce this? Do you have a test account?
Which client platforms?
What server version?

**Comment by gsurrel** [comment]
I guess I am the customer whom reported the problem for the support. I moved to a Windows client and I got the error again, with ownCloud 2.0.2 (build 5569). Here is the latest log, filtered where the error occurs. 

```
11-03 10:56:49:401 0x4568fd8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://drive.switch.ch" + "/androidStudio_workspace/[...sanitized path...]/build/generated/source/buildConfig/androidTest"
11-03 10:56:49:752 0x4568fd8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList<OCC::FileStatPointer>&) Have 1 results for  "/androidStudio_workspace/[...sanitized path...]/build/generated/source/buildConfig/androidTest"
11-03 10:56:49:753 0x4568fd8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://drive.switch.ch" + "/androidStudio_workspace/[...sanitized path...]/build/generated/source/buildConfig/androidTest/debug"
11-03 10:56:50:157 0x4568fd8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList<OCC::FileStatPointer>&) Have 1 results for  "/androidStudio_workspace/[...sanitized path...]/build/generated/source/buildConfig/androidTest/debug"
11-03 10:56:50:158 0x4568fd8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://drive.switch.ch" + "/androidStudio_workspace/[...sanitized path...]/build/generated/source/buildConfig/androidTest/debug/org"
11-03 10:56:50:480 0x4568fd8 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList<OCC::FileStatPointer>&) Have 1 results for  "/androidStudio_workspace/[...sanitized path...]/build/generated/source/buildConfig/androidTest/debug/org"
11-03 10:56:50:481 0x4568fd8 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://drive.switch.ch" + "/androidStudio_workspace/[...sanitized path...]/build/generated/source/buildConfig/androidTest/debug/org/[username]"
11-03 10:56:50:731 0x4568fd8 OCC::LsColXMLParser::parse: ERROR "Premature end of document." ""
11-03 10:56:50:731 0x4568fd8 OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot: void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply*) "Unknown error" 207 0
11-03 10:56:50:731 0x4568fd8 OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot: void OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot(int, QString) 5 "Unknown error"
11-03 10:56:50:732 0x4568fd8 OCC::SyncEngine::handleSyncError:  #### ERROR during  csync_update :  "An error occurred while opening a folder Unknown error"
11-03 10:56:50:745 0x4568fd8 OCC::SyncEngine::finalize: CSync run took  147048
11-03 10:56:50:745 0x4568fd8 OCC::Folder::slotSyncFinished:  - client version 2.0.2 (build 5569)  Qt 5.4.0  SSL  OpenSSL 1.0.2d 9 Jul 2015
11-03 10:56:50:745 0x4568fd8 OCC::Folder::slotSyncFinished: -> SyncEngine finished with ERROR, warn count is 0
11-03 10:56:50:746 0x4568fd8 OCC::Folder::bubbleUpSyncResult: Processing result list and logging took  0  Milliseconds.
11-03 10:56:50:746 0x4568fd8 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result:  1
11-03 10:56:50:746 0x4568fd8 OCC::Folder::slotSyncFinished:   ** error Strings:  ("An error occurred while opening a folder Unknown error")
11-03 10:56:50:746 0x4568fd8 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
11-03 10:56:50:746 0x4568fd8 OCC::Folder::slotSyncFinished: the last 2 syncs failed
11-03 10:56:50:747 0x4568fd8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\[username]\ownCloud\"
11-03 10:56:50:747 0x4568fd8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\[username]\ownCloud\"
11-03 10:56:50:747 0x4568fd8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\[username]\ownCloud\"
11-03 10:56:50:747 0x4568fd8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:C:\Users\[username]\ownCloud\"
11-03 10:56:50:747 0x4568fd8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:C:\Users\[username]\ownCloud\"
11-03 10:56:50:747 0x4568fd8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:C:\Users\[username]\ownCloud\"
11-03 10:56:50:749 0x4568fd8 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "ownCloud" :  "Error"
```

I noticed it always happens on compiled files (in a 'build' directory), whether it's Android or low level C for micro-controller. I discovered that because I'm removing/compressing all the files/folders yielding problems trying to get a successful sync.

Would it be possible to have the sync continuing despite the sync error? To me it seems better to have a partial sync with some missing files (with a huge warning sign) rather no sync at all. I know it can be debatable.

**Comment by guruz** [comment]
@gsurrel This is a phase of the sync where it just queries the metadata of the files on the server, iterating through each remote directory that has changed since last sync. So no files syncing here yet..

So actually if you see it going further now it means that it fails at random directories..

Could I have a test account on that server? Maybe it's reproducable in all cases when you have a lot of directories? My mail is my nickname here @owncloud.com
(Still the question then if the bug is in the setup or in the client or client's libraries)

**Comment by gsurrel** [comment]
@guruz I have contacted the customer service, and here is their answer:

> Thanks for you interest in this topic. Unfortunately, it is not so easy for us
> to provide an account. The problem occurs relatively rarely. Only a handful of
> users run into it. So we cannot just create an account and give the developers
> access to it, since the account would not show the problem. Also we cannot give
> them access to real user's accounts since the data on those accounts belongs to
> those users an not to us.

So I don't know what to do now. I have asked them if they could try to find a common thing between the accounts. (Many files, deep directory structure, specially big files, big space usage, many files in a single directory, lot of binary files, several ownCloud clients syncing at the same time the account...). I currently have no other idea.

**Comment by guruz** [comment]
Yes, I don't want access to real account.
I'm fine with doing some stress testing with a test account, who knows maybe I can reproduce it after all?

But If they don't want help then I'll remove this for now from 2.1 milestone.
@cmonteroluque @dragotin

**Comment by schnidrig** [comment]
>Yes, I don't want access to real account.
>I'm fine with doing some stress testing with a test account, who knows maybe I can reproduce it after all?

Hm, do you, or do you not want an account? It would be an empty one not (or at least not yet) showing the problem.

**Comment by guruz** [comment]
@schnidrig Real account = Of an actual human that has this symptom when syncing. :-)

I meant maybe I can reproduce with an empty test account that I feel myself with data

**Comment by schnidrig** [comment]
@guruz How can I send you the credentials. I don't want to post them here.

**Comment by guruz** [comment]
@schnidrig My mail is my nickname here @owncloud.com

**Comment by guruz** [comment]
I was able to reproduce on OS X with Qt 5.5 branch with ```owncloudcmd```, deleting the ```.csync_journal.db``` and having 200 folders. I always need 3-4 attempts to reproduce and then it reproduces when discovering one of the folders (there is no pattern which folder it is, it can happen earlier or later, it is not at the HTTP Keep Alive requests border).

Although we had our fair share of oddities with Qt recently, I believe here the load balancer or server must be to blame(?)

(I annotated the Qt code to find this out about how it is stored inside the HTTP chunked encoding)
For a working directory, we get 1 to several chunks with XML Data and then the terminating 0-chunk.
For a non-working directory, I just get the terminating 0-chunk. The HTTP headers look fine.

```
"Server" "nginx"
"Date" "Mon, 09 Nov 2015 17:51:32 GMT"
"Content-Type" "application/xml; charset=utf-8"
"Transfer-Encoding" "chunked"
"Expires" "Thu, 19 Nov 1981 08:52:00 GMT"
"Cache-Control" "no-store, no-cache, must-revalidate, post-check=0, pre-check=0"
"Pragma" "no-cache"
"Strict-Transport-Security" "max-age=0"
"X-XSS-Protection" "1; mode=block"
"X-Content-Type-Options" "nosniff"
"X-Frame-Options" "Sameorigin"
"Content-Security-Policy" "default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *"
"X-Robots-Tag" "none"
"Vary" "Brief,Prefer"
"DAV" "1, 3, extended-mkcol, 2"
```

Note: I'll still need to verify that Qt is not the problem via WireShark or similar.

**Comment by butonic** [comment]
This smells like https://github.com/owncloud/core/issues/14187. What are the exact versions of the os, php, php-fpm, nginx, apcu and memcached if used? socket or tcp based fpm?

**Comment by schnidrig** [comment]
Ubuntu 14.04.3
php5                          5.6.13
php5-fpm                   5.6.13
php5-apcu                 4.0.6-1
nginx                         1.4.6
no memcached

php 5.6 packages are from http://ppa.launchpad.net/ondrej/php5-5.6/

**Comment by guruz** [comment]
@butonic Should there be something in any of the php-fpm logs too? (when set to verbose?)

**Comment by schnidrig** [comment]
@butonic Indeed. It does look very much like #14187.
However, I had upgraded to php 5.6 a long time ago and still have the problem. Setting pm.max_requests = 0 seems to help but causes new problems like ever growing php processes.

Maybe I'll have to consider ditching nignx :-(

I still need to ask some customers if their problem is really solved. I'll let you guys know...

**Comment by butonic** [comment]
@schnidrig TCP or socket based php fpm?

**Comment by schnidrig** [comment]
it was socket.

In the meantime I actually ditched nginx in favor of apache and our problem are gone.

**Comment by guruz** [comment]
:+1:
