### ISSUE TITLE
Client is created of wrong size

### ISSUE THREAD

**Issue by MayurPawecha** [owncloud/client#3299]
Hello,

Try creating mac owncloud client and has been successful in that using following steps:-

$cmake -DCMAKE_PREFIX_PATH=/usr/local/opt/qt5 -DCMAKE_INSTALL_PREFIX=../install DCMAKE_BUILD_TYPE=“Debug” ../client
$make install
$sh admin/osx/create_mac.sh /Users/System/Desktop/MacCode/client-1.8.1/install /Users/System/Desktop/MacCode/client-1.8.1/client-build

When try to run build in same machine it works but, when same build try in other machine its not working.
The .app file created from mac is of only 13 MB and .exe file created of same code from windows is of approx. 40 MB.

**Comment by danimo** [comment]
`make install` is no longer supported on OS X. See https://doc.owncloud.org/desktop/1.8/building.html

**Comment by MayurPawecha** [comment]
I try  $make also but result is same.

**Comment by danimo** [comment]
because make does not embed the dependent libraries. Please read the docs about `create_mac.sh`

**Comment by kwillems** [comment]
but https://doc.owncloud.org/desktop/1.8/building.html says 'make' should be used and as far as i can see 'create_mac.sh' has nothing to do with that.
It's a bit confusing.

**Comment by danimo** [comment]
@kwillems It works fine without it on the build machine (that's the responsibility of `make`). You just won't be able to distribute it, which why you need the script. I'd love to have replaced "make install" to run it, bu my cmake fu is not strong enough. That said, the docs could certainly be improved.

**Comment by kwillems** [comment]
@danimo well, i've tried with and without `make`, followed by `create_mac.sh`. Both with no succes.
