### ISSUE TITLE
Investigate problem with SSL error handling in QNAM

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#3304]
The problem that shows up with SSL error handling in QNAM as described in https://github.com/owncloud/client/pull/3301 should be investigate. Possibly a Qt upstream bug.

**Comment by MTRichards** [comment]
@dragotin If we were to triage this, is it Sev 1, 2 3 or 4? I tagged Sev 2 under the assumption that it happens a significant amount and breaks the client when it does happen.

**Comment by guruz** [comment]
I'm not sure what to say here.

We used the API in a wrong way IMHO, we should have called ```ignoreSslErrors(specific_errors)``` like done now in 89376e14d6135a6f39a6df99d54fde253573575c (@ckamm)

Please re-open if relevant @dragotin @ogoffart @danimo
