### ISSUE TITLE
Upload speed on windows is low

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#3305]
In my tests uploading new files to the server with the 1.8.1 windows client is *significantly* slower than with the 1.8.1 linux client. 

* server1: windows: 12 MB in 90s, linux: 12 MB in 15s
* server2: windows: 12 MB in >2min, linux: 12 MB in <20s

To reproduce, connect to the same server on windows and on linux. Pick a file. Try uploading it on windows and measure the time taken. Then do the same thing on linux.

Downloads see no significant speed difference.

**Comment by ckamm** [comment]
@dragotin does not see speed differences with the latest nightly or 1.8.1. I see the same slow speeds using 1.7.1 on Windows. It's likely a local issue.

**Comment by guruz** [comment]
https://serverfault.com/questions/447775/virtualbox-slow-upload-speed-using-nat ?
