### ISSUE TITLE
Connection Closed when syncing large structure.

### ISSUE THREAD

**Issue by borconi** [owncloud/client#3306]
Hi. 

I have struggle with this for a while, and it drives me up the wall.

Here is the setup:
<b>Server</b>: 
Software: Ubuntu 14.04
RAM: 32 GB RAM
CPU: Xeon E3 1245V2
OC: 7.0.1.1
WebServer: Lighttpd 1.4.33
PHP-FPM - 5.5.9
MySQL: 5.6

<b>Client:</b> 
Windows 1.8.1

One user shares a large directory with the group, about 29.000 files in loads of folders.

Take a fresh PC, set up owncloud and set it up to sync all the data (initial sync so all files should be downloaded from server).

Discovering takes ages, although it's going fast trough each folder, so I will blame this on the massive folder structure. 

Syncing starts but after a short while it stops, and I have to wait for another discovery and then it starts syncing again, then again it stops and so on and to sync the 10 Gb, of data can take more than 24 hours, with a 78Mb internet line.... 

<b>www.conf</b>
listen = /var/run/php5-fpm.sock
pm = ondemand
pm.max_children = 32
pm.max_requests = 0

<b>php-fpm status</b>
pool:                 www
process manager:      ondemand
start time:           04/Jun/2015:00:26:33 +0100
start since:          4906
accepted conn:        14278
listen queue:         0
max listen queue:     0
listen queue len:     0
idle processes:       3
active processes:     18
total processes:      21
max active processes: 24
max children reached: 0
slow requests:        0

<b>Debug log </b> from windows client can be found here: https://cloudstorage.e-systems.co.uk/public.php?service=files&t=101e0db79f8118a07fc4d0bb04352983

Eventually the sync will finish and after that this problem tends to disappear but whenever a new device is added in the mix this starts from the beginning.

**Comment by RealRancor** [comment]
Hi,

could be related to: https://github.com/owncloud/client/issues/3248 which seems to get fixed in 1.8.2. You could try a current testing/daily version like recommended here:

https://github.com/owncloud/client/issues/3248#issuecomment-106775439

**Comment by borconi** [comment]
Thanks, downloading and testing now.  Will update with results.....

**Comment by borconi** [comment]
Managed to sync the whole content without any disruption, seems to be a fixed bug. Thank you for the info
