### ISSUE TITLE
client connecting to wrong socket (MacOSX 10.10, overlay icons)

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3307]
Here is a problem with branded cernbox client 1.7.1 and 1.7.2. This problem was seen on Mac 10.10.3 and 10.10.4 (older Mac 10.8 does not seem to have this problem). The side effect of this is that overlay icons do not work (and logs files are hammered heavily).

    May 18 13:20:53 host Finder[6298]: Connect Socket to file:///Users/user/Library/Caches/SyncStateHelper/ownCloud.socket
    May 18 13:20:53 host Finder[6298]: Socket DISconnected!
    May 18 13:20:53 host Finder[6298]: ERROR: No such file or directory
    May 18 13:20:53 host Finder[6298]: clearFileNameCacheForPath:
    May 18 13:20:53 host Finder[6298]: repaintAllWindows

These messages repeat every five seconds…

However there exists another socket file:  ~/Library/Caches/SyncStateHelper/cernbox.socket

**Comment by ckamm** [comment]
@moscicki I'm pretty sure this was fixed by @guruz for 1.8.0 with 3a1501dea4da03043d1021b6e891153f49575ed2

**Comment by moscicki** [comment]
Okey, thank you. This patch silences the log file -- but does it also fix the problem that owncloud.socket is being looked for instead of cernbox.socket? I am not sure I understand the whole patch.

**Comment by ckamm** [comment]
@moscicki With the patch, the Finder plugin will open the newest socket in that folder. So it should indeed talk via cernbox.socket.

**Comment by moscicki** [comment]
Okey, thanks. We will check and report back.

**Comment by moscicki** [comment]
Ok. The fix to become effective after installing the new version requires Finder restart. The log messages are gone. :+1:
