### ISSUE TITLE
External Storage Errors Passed from Server to Desktop

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#3308]
As an ownCloud administrator, I would like a mechanism to pass external storage credential errors to the desktop (and mobile) clients so that users on their devices can address any problems with external storage, and continue to use ownCloud even after an error (in conjunction with: https://github.com/owncloud/core/issues/16306 )

Acceptance Criteria:
- The error needs to be able to identify a problem with external storage and pass an error that does not cause the client to delete the directory, rather a temporary error that notifies the user that the directory is not syncing
- All errors are assumed to be temporary network or credential issues, rather than permanent failures
  - If external storage is permanently affected, the admin will have to remove it (or the user, if it is a personal mount) to resolve the errors
- The error needs to specifically identify the kind of problem (such as a credentials error), server not found error, etc
- The error also needs to specify a path so that the error can be addressed by the clients (such as opening a browser to the appropriate URL) and then allowing the user to resolve the issue. The error cannot be assumed to be in the root directory, as external storage can be moved around inside owncloud

LONGER TERM:
- The desktop clients would provide a communications path for passing messages to and from ownCloud clients (such as a credentials error AND a built in login screen) - so a general class of error that can be reused would be a good concept here.
  Related: https://github.com/owncloud/core/issues/16772

**Comment by MTRichards** [comment]
@karlitschek @PVince81 @cmonteroluque

**Comment by ogoffart** [comment]
Now, an error 503 in the PROPFIND makes the client not delete the external storage.
We do not show an error with a link to the user,  but we'd need server support for that.
