### ISSUE TITLE
owncloud accepts invalid SSL certificates

### ISSUE THREAD

**Issue by gdamjan** [owncloud/client#3310]
OS: ArchLinux
Qt: 4.8.6
OpenSSL: 1.0.2a
OwnCloud-Client: 1.8.1 (#ee7102)

While testing sslsplit (a program that does man in the middle and creates fake certificates dynamically) I've noticed that owncloud doesn't check if the certificate is signed by a trusted CA. I.e it just silently accepts an invalid certificate.

![owncloud-ssl](https://cloud.githubusercontent.com/assets/81654/8021148/2a897144-0c94-11e5-8769-d5a6e21e5594.png)

**Comment by LukasReschke** [comment]
Thanks for reporting issues back to us.

Please report potential security sensitive issues **only** to security@owncloud.com instead of filing public issues as described in our contribution guidelines.

That said, we would appreciate it if you could provide step-by-step reproduction step from a clear instance. Alternatively please check if `/home/USERNAME/.local/share/data/ownCloud/owncloud.cfg` contains an entry `General\CaCertificates` and if that if the case try the 1.8.2-rc1 client which from https://owncloud.org/install/#testing-development (potential duplicate of https://github.com/owncloud/client/issues/3283 then)

cc @danimo @dragotin

**Comment by LukasReschke** [comment]
>  Alternatively please check if /home/USERNAME/.local/share/data/ownCloud/owncloud.cfg contains an entry General\CaCertificates

If so please post the entries as well here.

**Comment by gdamjan** [comment]
Here's the entry from owncloud.cfg:

    General\CaCertificates=@ByteArray(-----BEGIN CERTIFICATE-----\nMIIFbzCCA1egAwIBAgIJAKAw8v/ezFKGMA0GCSqGSIb3DQEBCwUAME4xCzAJBgNV\nBAYTAlVTMRMwEQYDVQQIDApDYWxpZm9ybmlhMRYwFAYDVQQHDA1TYW4gRnJhbmNp\nc2tvMRIwEAYDVQQKDAlQaGFzZWJvb2swHhcNMTUwNjA2MTgxMzA1WhcNMjAwNjA1\nMTgxMzA1WjBOMQswCQYDVQQGEwJVUzETMBEGA1UECAwKQ2FsaWZvcm5pYTEWMBQG\nA1UEBwwNU2FuIEZyYW5jaXNrbzESMBAGA1UECgwJUGhhc2Vib29rMIICIjANBgkq\nhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAsNUZHVJG2zul5UbZuj1Zf2jxVuBJGbA/\nP1daGIUEWed8Wf77oTo7WkNjlr5go/drLlly2+II7jH65US4uN1135gs7PEyB3Lz\n7ROYAuwjhy8R97QERdkq3mfZHZNQSoYqlj9SpPGAsRCjKTTNSbyL3bgh4zUbYdzy\nQ7LRWhg5FfRB7MCIPmvNlyP7qiFnRWnaIsKao71+dowCEzMuX2m9USLNFLGW4Vd5\nlL+m8AE/eeYLYXXzC+d9wgi3iwT+QQHFyI3yCyr5tEwFThAsfh31blpq+waRwRGt\noLfMbGJDmilvYTrD+mBlrFe1HAiqAVAVInrE41xFK4CYUGvBmv0nWJ+MpTrYWnpT\neIL47aNgLbTgs6j3SzxRQqWlYiWGgwS4pYfyF5fNgBoDeslBNEjDg2BPLbzNsXjZ\nY6qiIrFsi2H3XZphBvtdJgbf6TrZOMpctfKVraKK9Y/LaYaWkVXsdsqcH/9+ZoQd\ny4JSwyblD0nQZOYuRJejD+eUwowxJIlkw/rOOMx17SeNBoKSLWAXfl0EfLpABABI\nHdfFZBWS7RkQRdHnCLFIvALcmQS+xlzJE0PW/lqijkhzLLL0Wv8WYX9PuJr0JHgb\nDDISJYuuhc3fUhLwHWUJKuGt6ISv9IOs1XzuUjcu18qq3C+5g/w7qISRHiiIw8lG\nne2QsPtVJdsCAwEAAaNQME4wHQYDVR0OBBYEFGFHt8u0QKbUjQwGG6jTzf4RxrNB\nMB8GA1UdIwQYMBaAFGFHt8u0QKbUjQwGG6jTzf4RxrNBMAwGA1UdEwQFMAMBAf8w\nDQYJKoZIhvcNAQELBQADggIBALBOkF48Vlj4MFzU0TEkzyr1n7vgjAkwpyBc34kg\nceJPylr6/Nxv2av8ZCl30+BjrIQdksP/ScU/uVRmpmduEpuZtPCQWiQ/bo2Xb1wq\n9nMSClCVnijo9tDNjfU7BpdBT2tGxS/Hy9HRMDqFtNP7Bk3qAKylItsrN9ZkOe6h\nscecweqXYduzjBwESZugV1PMf+ybmAjy5joHWZXFKS6yveJMWW5RFR/o8WNxQixL\nTsAqpVLX7SyiBwRIOg6FPBPKf9nbBD1/qd5RTigNFt4Pu+xo2oNmGf4H9C1x0FV6\nacpu1wSOBlw0EFEhijzJSHqpu7AYI2KHlcxY9F2oFZLyMXEnAF0jwl+vkqFZ/xf/\n3r98eFtHFH0YeFw9Is9pQ0icCVoTUrTVlsOMTo3AjFOC7yLLn14VakSVLG46o0Mu\nMnvkBX3Acp7U/1YGNxNMLPlQ+0knZpZXkJmmvD2t7cYqpRQiuY/2ujW6loX1RW0+\n2JhgkuTKF6kK23fhnCmkePNfwFsKjPUVfqJIWUGA45uRosRP+KBu2VuhPoHvYnBT\ntx7FVN1euIKMaUE45jb1BkN1Pdgb/FTs2nVejOwchu/dRsVxlOi4X9dQNxNDDMuV\np9L0eUSgO7p+v+ZcehiFyyEYSoPzhZ9AeTb8VqJC3uQv7A6ATb0htZvFy/glClwQ\nAt8V\n-----END CERTIFICATE-----\n\n)

**Comment by LukasReschke** [comment]
The stored certificate equals to the one shown in the screenshot. Just to double-check, are you sure that you did not import this certificate somehow?

I'd appreciate if you could remove this entry from the client config, please close the client before this. After this start the client with `owncloud --logwindow` and report back whether you can reproduce this problem. If so please also provide the log output.

**Comment by gdamjan** [comment]
@LukasReschke thanks for the hint, retracing my steps, and I did have imported the certificate accidentally.
The problem was, at the time I was playing in chromium, when all of the sudden the dialog poped up.
I thought it was a chromium dialog and clicked on "import". As you can see on the attached image, there's no hint it's a ownlcoud dialog

Thanks again, and sorry for the noise … the only signal here is maybe, improved dialog titles :)

![owncloud-ssl1](https://cloud.githubusercontent.com/assets/81654/8021424/c8581cd0-0c9f-11e5-88fe-1120b281c84d.png)

**Comment by LukasReschke** [comment]
Thanks for the fast feedback, glad to hear. 

Agreed, we need to make this dialog more scary as well as make it clear that this affect oC. Let's close this issue in favour of the newly created https://github.com/owncloud/client/issues/3311 :)
