### ISSUE TITLE
Windows sync issues: Unintentional deleted (and usually recreated) files

### ISSUE THREAD

**Issue by alvar-freude** [owncloud/client#3312]
### Expected behaviour

For existing unmodified files, there should be happen nothing: no files deleted, no files created on the ownCloud server.

### Actual behaviour

I have an ownCloud Server, with a small number of users. 6 users are in a group, let's call it "team", and share >5000 Files (>3GB) between each other.

One user, let’s call him Netty, uses Windows 7 Professional and his ownCloud folder is stored on a shared network volume. The other 5 users store their files locally. *Update:* The files on the shared network volume are encrypted with [fideAS enterprise] (https://www.daten-verschluesselung.de/en/enterprise/), which encrypts all files (transparently) on the client. 

Yesterday one user (not Netty) complained, that a lot of files (but not all) were deleted. But Netty sees (all?) the files on his locally mounted network share. After analyzing this, I found the following situation:

From time to time Netty's ownCloud client deletes some files and usually recreates them later. In the activity log it looks like Netty deletes the files and recreates them. But in reality, user Netty does not delete the files, and does not notice any downtime of the network share.

When the files are deleted by Netty's ownCloud client, the files on all other users local folder are deleted too — seems obvious.

Usually the files are newly created later by Netty (or to be precise: his ownCloud client) and then re-synced to all group members.

~~The last time this happened, some files were lost and not recreated. But at the moment it is not clear, if this is because Netty shut down his computer before everything was synced or if they are really lost.~~ *Update:* Computer was shut down before all files are recreated; it seems that all files are recreated after next boot of this machine.

Maybe there are some anomalities with the shared Windows volume. But for the user everything works fine on the network volume and the whole team used it as shared storage before we switched to ownCloud.

### Steps to reproduce

unknown – not tested, can't test.

### Server configuration
Operating system: FreeBSD 10.1

Web server: Backend: Apache 2.4.12 with prefork MPM and mod_php
Frontend / Reverse Proxy: Apache 2.4.12 with Event MPM
Frontend handles SSL encryption, Compression, static files; mod_xsendfile enabled.

Database: PostgreSQL 9.4.2

PHP version: 5.5.25 

ownCloud version: 8.0.3 

Storage backend: Local file system (ZFS, with own filesystem for owncloud; compression lz4 enabled, time off, deduce off)

### Client configuration
Client version: 1.8.1

Operating system: Windows Professional 7

OS language: German

Installation path of client: unknown

### Logs

This happens with the example files too; here is a shortened summary from the table oc_activity in the ownCloud database, for the Squirrel picture in the default examples. User Netty never touched the image, but the client deleted and usually recreated it:

```
  SELECT TIMESTAMP WITH TIME ZONE'epoch' + timestamp * INTERVAL '1 second' AS readable_time,
         activity_id AS act_id,
         priority AS prio,
         type,
         'Netty' AS "user",
         messageparams,
         file
    FROM oc_activity
   WHERE "user" = affecteduser
     AND file LIKE '%Squirrel%'
ORDER BY timestamp DESC;

    readable_time      | act_id | prio |     type     | user  | messageparams |         file
------------------------+--------+------+--------------+-------+---------------+----------------------
2015-06-05 15:05:23+02 | 299179 |   40 | file_deleted | Netty | a:0:{}        | /Photos/Squirrel.jpg
2015-06-05 14:11:23+02 | 296793 |   40 | file_created | Netty | a:0:{}        | /Photos/Squirrel.jpg
2015-06-05 12:35:25+02 | 256475 |   40 | file_deleted | Netty | a:0:{}        | /Photos/Squirrel.jpg
2015-05-18 10:34:38+02 | 203730 |   40 | file_changed | Netty | a:0:{}        | /Photos/Squirrel.jpg
2015-04-27 17:09:17+02 | 136041 |   40 | file_created | Netty | a:0:{}        | /Photos/Squirrel.jpg
2015-04-27 16:13:14+02 | 114641 |   40 | file_deleted | Netty | a:0:{}        | /Photos/Squirrel.jpg
2015-04-22 14:56:27+02 |  94354 |   40 | file_created | Netty | a:0:{}        | /Photos/Squirrel.jpg
2015-04-22 13:42:36+02 |  59053 |   40 | file_deleted | Netty | a:0:{}        | /Photos/Squirrel.jpg
(8 Zeilen)

Zeit: 97,025 ms

```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
    I have no access to the ownCloud Client log at the moment. 

2. Web server error log:
    There is no error according to this issue.
    
    The access log shows the usual DELETE requests, like this:
    
    ```1.2.3.4 - - [05/Jun/2015:12:35:24 +0200] "DELETE /remote.php/webdav/Photos/Squirrel.jpg HTTP/1.1" 204 - "-" "Mozilla/5.0 (Windows) mirall/1.8.1" ````

3. ownCloud log (data/owncloud.log):

    My ownCloud logs to syslog, so it's in syslog format.
    It seems, that there are some related messages, i snippet some examples and added some context info:

    Log examples are here:
    https://gist.github.com/35598a6c9e33dc3c7cda.git

**Comment by guruz** [comment]
Thanks, this sounds indeed glitchy.
Can you try to create a client log file then we maybe see why the client thinks the file needs to be deleted. https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly

CC @dragotin @ogoffart

**Comment by alvar-freude** [comment]
I can try – it's a bit difficult, because it's a colleague in other location and all others are affected too etc; tomorrow we try to do some research.

**Comment by alvar-freude** [comment]
I updated two parts:
1. it seems that all files are back: they are stored on the network volume and ownCloud found any files and created them as new. Nevertheless this is not a good situation ;-)
2. The files are stored encrypted on the network volume, but with **local** encryption via [fideAS enterprise] (https://www.daten-verschluesselung.de/en/enterprise/) – there is a [german description] (https://www.daten-verschluesselung.de/enterprise/) too.

I guess, that this issue is in relation to fideAS and network volume usage and perhaps some network anomalies …

We try to produce a log; there is no option to enable the log via GUI or something else? We are not allowed to start cmd32 to start the client with parameter; but I can't provide details, because I work remote and not with Windows …

**Comment by guruz** [comment]
OK, this of course makes the setup quite a bit more exotic..
even though I agree it should still not mess up like this.

You can try F12 to open the log window.
Although then if it only happens seldomly I'm thinking it will be hard to not create a too huge log..

**Comment by alvar-freude** [comment]
Yes, more exotic …
Maybe this happens if the server goes away some seconds and the local encryption client gets some trouble …

The log window is open, but scrolls fast ;-) – is there a limit for the log window?

There are no erroneous deleted files today. I guess, that only log entries for deleted files are useful?

**Comment by alvar-freude** [comment]
I have some parts of the log. But since the log window is limited to 20000 rows, it's only a part.

I can't publish the whole log public (but maybe via PGP mail), some examples here.

Log starts while csync_reconcile is running; message at the end of this run is:

```
06-08 14:51:32:121 0x605ef88 csync_reconcile: Reconciliation for remote replica took 14.79 seconds visiting 9834 files.
06-08 14:51:32:126 0x605ef88 csync_statedb_close: sqlite3_close=0
06-08 14:51:32:126 0x605ef88 OCC::SyncEngine::slotDiscoveryJobFinished: <<#### Reconcile end ####################################################  331153
``` 

During the run, there are some delete messages, e.g:

```
06-08 14:51:25:032 0x605ef88 _csync_merge_algorithm_visitor: INSTRUCTION_REMOVE   file: Photos/Squirrel.jpg
``` 

It looks like there is no real order of all files (asynchronous?), most log lines in this section have INSTRUCTION_NONE, but a lot also INSTRUCTION_REMOVE.

A little bit later, there are some log lines from OCC::SocketApi::sendMessage:

```
06-08 14:51:35:562 0x605ef88 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:SYNC:X:\MdB_eskensa_verschluesselt\Büro\OwnCloud\Photos\Squirrel.jpg"
06-08 14:51:35:571 0x605ef88 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:SYNC:X:\MdB_eskensa_verschluesselt\Büro\OwnCloud\Photos\Squirrel.jpg"
06-08 14:51:35:571 0x605ef88 OCC::SocketApi::sendMessage: WARN: Could not send all data on socket for  "STATUS:SYNC:X:\MdB_eskensa_verschluesselt\Büro\OwnCloud\Photos\Squirrel.jpg
"
06-08 14:51:35:572 0x605ef88 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:SYNC:X:\MdB_eskensa_verschluesselt\Büro\OwnCloud\Photos\Squirrel.jpg"
```

That's everything in this section for the squirrel.

Three seconds later:

```
06-08 14:51:38:328 0x605ef88 OCC::SyncEngine::slotDiscoveryJobFinished: Permissions of the root folder:  "RDNVCK"
06-08 14:51:38:346 0x605ef88 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "post treewalk" and starting new transaction
06-08 14:51:38:354 0x605ef88 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "post stale entry removal" and starting new transaction
06-08 14:51:38:355 0x605ef88 OCC::OwncloudPropagator::start: Using QNAM/HTTP parallel code path
06-08 14:51:38:356 0x605ef88 OCC::SyncEngine::slotDiscoveryJobFinished: <<#### Post-Reconcile end ####################################################  337382
06-08 14:51:38:357 0x605ef88 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for "https://my-oc-server.tld" + "/"
06-08 14:51:38:357 0x605ef88 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
06-08 14:51:38:358 0x605ef88 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://my-oc-server.tld" + "/"
06-08 14:51:38:359 0x605ef88 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag
06-08 14:51:38:497 0x605ef88 OCC::Folder::slotSyncStarted: #### Propagation start #################################################### >>
06-08 14:51:38:501 0x605ef88 OCC::SocketApi::slotUpdateFolderView: Not sending UPDATE_VIEW for "ownCloud" because status() is 3
06-08 14:51:38:510 0x605ef88 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7544920)  with name  "ownCloud"
06-08 14:51:38:511 0x605ef88 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "ownCloud" :  "Sync Running"
```

But after this, some `OCC::SocketApi::sendMessage: SocketApi: ` still appear.

 I think that are the most relevant log lines; after this, there are some log entries about sending the message to the server, but I guess that's not that important – we know, that this works fine ;-)

I can send you more at best via GPG encrypted mail …


So, it looks like a problem in csync?!?

**Comment by alvar-freude** [comment]
Now we have some files and folders, which are deleted and NOT recreated later and locally deleted too. But the user says, that he did not deleted the files.

This SQL selects deleted files/folders, which are not recreated later:

   SELECT TIMESTAMP WITH TIME ZONE'epoch' + timestamp * INTERVAL '1 second' AS readable_time,
          activity_id AS act_id,
          priority AS prio,
          type,
          "user",
          messageparams,
          a.file
     FROM ( SELECT file, max(timestamp) AS ts FROM oc_activity WHERE type = 'file_deleted' GROUP BY file ) AS del,
          ( SELECT file, max(timestamp) AS ts FROM oc_activity WHERE type = 'file_created' GROUP BY file ) AS cr,
          oc_activity AS a
    WHERE del.file    = cr.file
      AND del.ts      > cr.ts
      AND a.file      = del.file
      AND a.timestamp = del.ts
      AND "user"      = affecteduser
      AND "user"      = 'netty'
 ORDER BY timestamp DESC;

**Comment by guruz** [comment]
(You can ignore the SocketApi messages, they are not relevant for the sync, just for the Explorer view.)

Not sure what to make out of this bug report.

The 2.0 client (see http://download.owncloud.com/desktop/daily/ or the beta coming out next week) will have a different way to iterate over local directories. Maybe this changes anything regarding the client deleting files?

**Comment by guruz** [comment]
@alvar-freude Would you want to try with the 8.1 server and the 2.0 client nightly builds?

**Comment by alvar-freude** [comment]
I'll install 8.1 server when the FreeBSD Port is updated (usually ports are updated fast, but OC hast still 8.04).

In our live environment I can't test the 2.0 beta client, sorry. 
We switched to use local drives for every one, and the problems are gone.

On my todo list is to write to the fideAS support, but it is still on Todo :-/. I guess that the problem is caused by this encryption tool.

**Comment by alvar-freude** [comment]
A suggestion for the new client: add an option "Ask if there are more then X files deleted" before delete them on the server. X configurable, maybe in absolute and percent?

But one folder containing 1000 files/folders should count as 1001, not as 1 ;-)

I guess that this would prevent a lot of unintentional deletes.

**Comment by guruz** [comment]
@alvar-freude Thanks, I'm closing this for now then.
Feel free to point their support to this issue, maybe we can get them to use/try oC ;-)
