### ISSUE TITLE
 Please tell us the the location of the  Client logs.

### ISSUE THREAD

**Issue by guettli** [owncloud/client#3315]
Docs: Please tell us the the location of the  Client logs.

https://doc.owncloud.org/desktop/1.8/troubleshooting.html#obtaining-the-client-log-file

The current docs only explain how to open the logs with the client GUI.

Thank you.

**Comment by RealRancor** [comment]
Hi,

if you read only a few lines below:

https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly

you can find the info that you need to specify a dir where the logfiles are saved.

**Comment by guettli** [comment]
I don't get this. Imagine I want to read the logs of the sync of yesterday:

Yesterday I started the owncloud desktop client without a command line argument.

How can I get to the log files of yesterday?

**Comment by RealRancor** [comment]
Simple answer: You can't

**Comment by dragotin** [comment]
That's not completely true. There is a file called ```.owncloudsync.log```. That is not a complete log but it logs a couple of very important data about every action the client did. With a bit of a trained eye you can read a lot from it.

Speaking about the full logs: I often thought about how to do it to keep the full logs from the recent syncs, but its not easy to do that really useful .Doable of course, but needs some work. That has not happened yet.

**Comment by RealRancor** [comment]
@dragotin 
Oh, good to know about such stuff like the ```.owncloudsync.log```. This is definitely something which should be documented.

**Comment by dragotin** [comment]
Yes. Well, actually that's a *half way* feature. I initial idea would be to use that as a source for the activity window that we have - to make that persist. Again: Has'nt happened yet. So much to do...

**Comment by guettli** [comment]
@dragotin for this ticket there is **not** much to do. This ticket is about this missing docs.

Please tell the truth in the docs: Simple answer: You can't get the logfiles of yesterday if you don't have started the client like described in my posted link.

In this ticket I don't ask for more. Just docs.

**Comment by guruz** [comment]
By default, there are no detail logs, only if you use the command line parameters.
If you think the docs should be enhanced, please send a merge request (along with contributor agreement)

**Comment by guettli** [comment]
For me this ticket is enough documentation. Google will show it, if other users want to know this. Thank you, I am happy.
