### ISSUE TITLE
Mac Client does not Sync

### ISSUE THREAD

**Issue by Necriz** [owncloud/client#3318]
Mac OS X 10.10.3
OC Client 1.8.2 (2416)
OC Server 8.0.3

Installed OC yesterday without problems.
Windows-Clients can sync files normally without problems.

On the OSX side the clients starts > discovery >  wants to start the sync and shortly after the error occurs.

![owncloud](https://cloud.githubusercontent.com/assets/12808723/8051594/c24278b4-0e7e-11e5-9afc-f43cb7d635ab.png)
```
09.06.15 07:46:59Business/Citrix/Citrix Receiver for Windows 3.4 Cumulative Update 3.zipownCloud       Operation abgebrochen73 MiB    
09.06.15 07:46:59Business/Citrix/XenApp 6.5 Adv/Citrix/Citrix_Scripts/Scripts/Tools/PsService.exeownCloud       Operation abgebrochen166 KiB   
09.06.15 07:46:59Business/Citrix/XenApp 6.5 Adv/Citrix/Citrix_Scripts/Scripts/Tools/PsInfo.exeownCloud       Verbindung beendet381 KiB   
09.06.15 07:46:57Business/Citrix/XenApp 6.5 Adv/Citrix/Citrix_Scripts/Scripts/Tools/PsLoggedon.exeownCloud       Heruntergeladen179 KiB   
09.06.15 07:43:58Business/Citrix/Citrix Receiver for Windows 3.4 Cumulative Update 3.zipownCloud       Operation abgebrochen73 MiB    
09.06.15 07:43:58Business/Citrix/XenApp 6.5 Adv/Citrix/Citrix_Scripts/Scripts/Tools/PsLoggedon.exeownCloud       Operation abgebrochen179 KiB   
09.06.15 07:43:58Business/Citrix/XenApp 6.5 Adv/Citrix/Citrix_Scripts/Scripts/Tools/PsInfo.exeownCloud       Verbindung beendet381 KiB   
09.06.15 07:43:57Business/Citrix/XenApp 6.5 Adv/Citrix/Citrix_Scripts/Scripts/Tools/PsList.exeownCloud       Heruntergeladen226 KiB   
```

 After that the discovery runs again

**Comment by dragotin** [comment]
@guruz any idea?

**Comment by guruz** [comment]
@Necriz Does it recover from that error?

**Comment by kcristiano** [comment]
@guruz I have the same error and it does not recover.   I tried uninstalling/reinstalling and even removing the sync and re-establishing.  Everything fails.

**Comment by guruz** [comment]
@kcristiano You have the error also only on OS X and Windows works? Which versions on client and server?

@kcristiano @Necriz Is it possible for you to create a test account on your oC and mail me the credentials? e-mail is _my-nickname-here_ @owncloud.com

**Comment by kcristiano** [comment]
@guruz I get the error on Mac OS X and Ubuntu 14.04  Both are 1.8.2 client.  Windows does work.

I would create a user, but it seems I cannot create any users on OwnCloud (v 8.0.3)

**Comment by Necriz** [comment]
@guruz mail sent with details for the test-account

the client won't recover - stays in a loop

**Comment by Necriz** [comment]
FYI: The error in the first post occurs on my Mac Mini

On my MacBook I got an older version (1.8.1 (2335)) and this seems to work fine.

**Comment by guruz** [comment]
Thanks, I am able to reproduce.
Looking into it..

**Comment by guruz** [comment]
We're preparing a nightly build for you guys to check out..

**Comment by guruz** [comment]
Can I ask you OS X guys to test http://download.owncloud.com/desktop/daily/ownCloud-1.8.2.2422-nightly20150610.pkg ?
Please test uploads and downloads and report back if it works.

**Comment by kcristiano** [comment]
@guruz I installed and was able to download all my personal files and uploads are working as well.

I'll leave it running and see if I encounter any problems.

Thanks for the quick attention to this.

**Comment by Necriz** [comment]
The error now occurs ab it later, but stays the same (as in the pic in the 1st post)

```
10.06.15 18:12:23 Privat/Bilder/Wallpaper/Desktop/71793.jpg                       ownCloud       Operation abgebrochen601 KiB   
10.06.15 18:12:22 Privat/Bilder/Wallpaper/Desktop/1639316.jpg                     ownCloud       Operation abgebrochen2 MiB     
10.06.15 18:12:22 Privat/Bilder/Wallpaper/Desktop/1770981.jpg                     ownCloud       Verbindung beendet568 KiB   
10.06.15 18:12:21 Privat/Bilder/Wallpaper/Desktop/211711696_74238f9b8d.jpg        ownCloud       Heruntergeladen142 KiB   
```

**Comment by guruz** [comment]
@Necriz There is another nightly out with a small change ownCloud-1.8.3.2423-nightly20150610.pkg ..
Are you 100% confident you tested the right version? (can you check the settings dialog)..

There is another confirmation that it works now on OS X in https://github.com/owncloud/client/issues/3313#issuecomment-110885218

**Comment by Necriz** [comment]
![screenshot_10_06_15_22_55](https://cloud.githubusercontent.com/assets/12808723/8093892/f64490ca-0fc3-11e5-94f4-d2ece5fbb180.png)

Will try 1.8.3.2423

**Comment by Necriz** [comment]
![owncloud](https://cloud.githubusercontent.com/assets/12808723/8094189/ae90c9ea-0fc5-11e5-87e9-4cdd91d2c03c.png)
![owncloud 2](https://cloud.githubusercontent.com/assets/12808723/8094192/b18a9d1a-0fc5-11e5-9662-65e0f15d31b0.png)

discovery - transfer - error - discovery - transfer - error

but for now, the remaining data to be transfered gets smaller; maybe if I just wait long enough it finishes.

------

5 minutes later...
![owncloud 4](https://cloud.githubusercontent.com/assets/12808723/8094319/9802c100-0fc6-11e5-9a00-7ea7134d00fc.png)

------

15 minutes later...
![owncloud](https://cloud.githubusercontent.com/assets/12808723/8094554/2f43d1ca-0fc8-11e5-8a82-6c6df272d48e.png)

I had a 300kb download-limit active which I deactivated to speed up the error... may that fixed it?

**Comment by guruz** [comment]
> I had a 300kb download-limit active which I deactivated to speed up the error... may that fixed it?

You mean when the error came you still had the limit activated?

**Comment by Necriz** [comment]
yep

as I deactivated the limit, the error didn't occur any more.
can be a coincidence or the root of the problem ;)

**Comment by Dianafg76** [comment]
I tested this issue, with DESKTOP ownCloud-1.8.3.2424-nightly20150611.pkg, SERVER v8.0.3, and the Bandwidth=No limit, the error no appears any more

**Comment by kcristiano** [comment]
ownCloud-1.8.3.2423-nightly20150610 is working for me with no download or upload limits

**Comment by Dianafg76** [comment]
I close the bug

**Comment by guruz** [comment]
bug still exists, reopening..

**Comment by guruz** [comment]
Another nightly to try: http://download.owncloud.com/desktop/daily/ownCloud-1.8.3.2430-nightly20150612.pkg

@kcristiano @Dianafg76 @Necriz Does this nightly still work for you?
There is an additional fix inside which only was relevant for Windows, but who knows what it might regress..

**Comment by kcristiano** [comment]
This does work for me.
