### ISSUE TITLE
ownCloud client 1.8.2.5166 breaks explorer on Windows

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3320]
Forum ref: https://forum.owncloud.org/viewtopic.php?f=14&t=28699
I had this on 2 computers that I installed with ownCloud 1.8.2. Both were Windows7 and in a domain (if that matters - don't know). The first was a virgin install of ownCloud client 1.8.2, the other had 1.8.1 already on it and I updated, including clicking through the screens to uninstall 1.8.1 first.
Everything looks fine in real-time. Then after rebooting, explorer crashes every time:

Faulting application name: Explorer.EXE, version: 6.1.7601.17567, time stamp: 0x4d6727a7
Faulting module name: ntdll.dll, version: 6.1.7601.18798, time stamp: 0x5507b3c6
Exception code: 0xc0000374
Fault offset: 0x000c3b93
Faulting process id: 0x81c
Faulting application start time: 0x01d0a35137b88e73
Faulting application path: C:\windows\Explorer.EXE
Faulting module path: C:\windows\SYSTEM32\ntdll.dll
Report Id: 762eac62-0f44-11e5-93af-6431507735ec

Because of this, there is no desktop, just a black screen with a cursor. No left or right-click brings up anything. The computer is dead to a GUI user!!!

To recover, I did:
a) ctrl-alt-del and then choose "Start Task Manager"
b) From Task Manager, File->New Task (Run...)
c) cmd

I tried just an uninstall of ownCloud 1.8.2 (cd down through Program Files\ownCloud and run the uninstall). No joy, after rebooting again still the same error.

d) Installed ownCloud 1.8.1 (including uninstalling 1.8.2 if it was still there) - you need the ownCloud 1.8.1 installer on something that you can access.

e) Reboot - the world is good again - explorer starts and so I have a desktop...

This is a VERY BAD THING. If it is at all common then 1.8.2 needs to be pulled from release immediately because it is not a simple and obvious thing to recover from.

**Comment by dragotin** [comment]
Reboot works good here on Win7. So at least no general problem. What's different?

**Comment by phil-davis** [comment]
Both my systems are Win7 Professional SP1 32-bit with all latest patches and in a domain. I don't have another system to try on right now. Maybe 32-bit is an issue?

**Comment by dragotin** [comment]
Maybe, my Win7 is 64 bit.

**Comment by f-s** [comment]
Same problem here, maybe related to a recent windows update.

**Comment by jpaechnatz** [comment]
We have the same problem, Windows 7 Professional 64bit German.
11 Clients wrecked and we stopped the rollout. We kept the other clients on 1.8.1 for this reason.
Only system restore worked, although it was quite difficult to manage restore points, only restoring via cmd/rstrui.exe worked. -> rstrui.exe is your friend ;-)

**Comment by phil-davis** [comment]
I had the problem yesterday after rebooting a desktop system for other reasons. Then today I got the June set of Windows updates and rebooted both the desktop and my laptop. Got the explorer crashing problem on the laptop also then. So it was just that the problem was waiting to be seen on the laptop when it was rebooted.
The windows updates made it no better or worse - it is the reboot that brings the problem to light.
On both systems I kept all Windows updates and installed ownCloud 1.8.1 then rebooted to recover.

**Comment by guruz** [comment]
@f-s What kind of Windows?

**Comment by f-s** [comment]
`The windows updates made it no better or worse - it is the reboot that brings the problem to light.`

I agree now (I checked the win updates its not associated)
We have the problem on both 32bit/64bit and it looks its an 1.8.1->1.8.2 upgrade issue, no problem with 1.8.2 install with previous 1.8.1 manual uninstall.

**Comment by dragotin** [comment]
@f-s when the client installer asked *do you want to remove the old version?* while updating to 1.8.2, what did you select?

**Comment by f-s** [comment]
@dragotin we did a silent install with "/S"

**Comment by jpaechnatz** [comment]
Dito. Wrecked Clients have been installed /s silent.

**Comment by danimo** [comment]
@f-s @jpaechnatz that's good hint. We will investigate problems with `/S`

**Comment by phil-davis** [comment]
I used the ordinary interactive installer, so it is not just and issue with "/s". But by the above reports it is not limited to just 32-bit. It doesn't seem obvious what is the real common underlying factor here! Hopefully a dev can find some combination that behaves like this, and if they fix 1 thing hopefully it fixes the root cause for all.
I suggest that everyone report
1) Windows version,
2) 32 or 64 bit,
3) in domain or standalone
4) installer mode used (/s or interactive or...)
5) did you select to uninstall previous version
By having that for all who report the problem it might become clear what is the critical thing.
Mine are both:
Windows 7 Professional, 32-bit, in domain, using installer interactively, uninstalled previous version during the install process.

**Comment by f-s** [comment]
Windows 7 Professional, 32-bit, in domain, using installer sliently, previous version 1.8.1 installed during process
Windows 7 Professional, 64-bit, in domain, using installer silently, previous version 1.8.1 installed during process

**Comment by jpaechnatz** [comment]
Windows 7 Professional 64bit German, in Domain, previous 1.8.1 installed, 1.8.2 via /s silent install.

**Comment by jturcotte** [comment]
We could reproduce the issue by not removing the old version before installing the new one. This would end up installing OCUtil_x64.dll, but would leave the old version of OCOverlay_x64.dll, which was using still using the old memory layout of interfaced objects.

This doesn't explain how @phil-davis could still get the crash by choosing to uninstall the previous version, so we will have to check if other conditions could have triggered the same situation somehow.

**Comment by danimo** [comment]
@phil-davis @f-s @jpaechnatz Please try http://download.owncloud.com/desktop/daily/ownCloud-1.8.2.5173-nightly20150610-setup.exe. It contains @jturcotte's fix

**Comment by phil-davis** [comment]
That build 5173 works fine on my laptop. I installed, letting the installer do an uninstall first. The uninstall said it was successful, but I still had the ownCloud icon in the icon box - how can that happen? Then during the install it complained about not being able to write owncloud.exe - at that point I did "Quit ownCloud" from the icon and then pressed retry in the installer and it continued happily. I know a sequence like that happened with the build 5166 install, which maybe contributed to the issue I first reported.
Logged out and in again - no problem.
Restarted Windows, logged in, all is fine, ownCloud has started and synched. Looks good.
Note that I also had not been able to get the context menu entry "Share with ownCloud" when running 1.8.1. Now the context menu entry is there and it works. That is even better!
Perhaps there should also be something in the installer to check if ownCloud is still running. In my case it was still running under my unpriv user account and the installer is running under my admin account. Maybe it will be a little tricky to check that?
At least a message at the beginning of the installer/uninstaller to "gently remind" dummies like me to "Quit ownCloud" first before continuing with the installer would be nice.
The desktop I also had trouble with is at work - I will try that in the morning and report.

**Comment by danimo** [comment]
@phil-davis The installer performs a check using the [Processes plugin-in](http://nsis.sourceforge.net/Processes_plug-in) and in fact reminds the user. Somehow that does not seem to work when other users are running `owncloud.exe`, but that's not a regression, so I'd rather not touch this at the moment.

Thanks for verifying the fix!

**Comment by phil-davis** [comment]
That nightly build 5173 installed fine on my desktop also.

**Comment by SergioBertolinSG** [comment]
Installed an old version and upgraded it to 1.8.3rc1 (build 5180) in windows server 2008.
Working fine. Rebooted, no problems.

But the interface looks a bit odd in this typography.

![screen shot 2015-06-11 at 18 16 12](https://cloud.githubusercontent.com/assets/9048796/8112540/9173fa64-1068-11e5-8127-5b8a5fa4df7c.png)

**Comment by Dianafg76** [comment]
Yesterday we tried this problem in Windows 7 Home Premium , Sevice Pack 1, 64-bit error is not happening.
Instaled an old version (1.8.1) and upgraded it to v 1.8.2 (the error is not happening)
v 1.8.2 upgraded to 1.8.3 the error is not happening

**Comment by Dianafg76** [comment]
I close the bug
