### ISSUE TITLE
[CernBox] 1.8.2-beta1 does not propagate directory renames/moves correctly

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3324]
Contrary to 1.7.2 which passes this test, the 1.8.2 client leaves the server in inconsistent state if the directory is renamed while files are added to it. This is a result against the cernbox server.

See:
https://github.com/cernbox/smashbox/blob/master/lib/test_concurrentDirMove.py

This effectively means that the sync is broken and cannot be reliably used in a multiuser environment.

**Comment by moscicki** [comment]
Also note, that this test also fails with the negative argument of concurrentMoveDir_delaySeconds (smash -t 3). This means that the move is not propagated correctly from the server to the client which only later adds the files.

**Comment by dragotin** [comment]
@jnfrmarks can you reproduce with your smashbox setup?

**Comment by ogoffart** [comment]
What's the version of the server?

**Comment by ogoffart** [comment]
Does the reply to the MKCOL command have a "OC-FileId" header.  (This header is new in owncloud 7.0.1 https://github.com/owncloud/core/issues/9000 )

If it does not have a header does it do a PROPFIND after the MKCOL?

**Comment by moscicki** [comment]
Thanks for the hint. No, the "OC-FileId" header is not returned in the response to MKCOL. I will investigate.

**Comment by moscicki** [comment]
Do you also expect the Etag header in response to MKCOL?

**Comment by ogoffart** [comment]
We do not need ETag header in response to a MKCOL.

But even without the FileId it should still work, it is just that it is a different codepath taken.  When the fileid is not there it should do a PROPFIND to fetch it. Can you see this PROPFIND in your log?

**Comment by moscicki** [comment]
I will let you know tomorrow.

**Comment by moscicki** [comment]
I am not really sure what I should be looking for. I see some propfinds after MKCOL. There is one PROPFIND asking just for ETAG of the newly clreated directory and then there is another general PROPFIND asking for the whole directory listing of this new directory. There is no specific PROPFIND asking for fileid of this directory. Is this what you expect?

**Comment by moscicki** [comment]
@ogoffart: do you need other pieces of information about this case?

**Comment by ogoffart** [comment]
`There is one PROPFIND asking just for ETAG of the newly clreated directory`

Are you sure this is not the one that require the fileid?  Is it comming directly after the MKCOL?
The FileId is called id as a webdav property, it looks like this in the XML:
`<id xmlns="http://owncloud.org/ns" />`

And if the server propertly reply with the file id, it should be able to track the moves.

**Comment by moscicki** [comment]
I am positively sure that it was asking just for the etag and not a fileid. This comes immediately after the mkcol. I think you should try this test against an older owncloud server version which does not provide fileid in the response of mkcol. Because it is not unlikely that there is a regression towards older servers which are still in production.

**Comment by moscicki** [comment]
Have you actually managed to reproduce this against older version of the oc server?

**Comment by moscicki** [comment]
Hi, I tested this against vanilla owncloud server 7.0.4 and the test also fail (for 1.8.3rc3). So you have a regression against older server version.

On top of that I tested against our server with FileId provided in reponse to MKCOL and it does not change anything.

@dragotin, @ogoffart : someone of your QA team should test this!

**Comment by moscicki** [comment]
@guruz: thanks for looking into this. Which release number does "next-bugfix-release" correspond to?

**Comment by ogoffart** [comment]
I could reproduce some problems with the owncloud 7 server, but it looks like the server is getting confused and do something wrong. 
Are you sure 1.7 was working?

**Comment by moscicki** [comment]
I am sure that 1.7 works fine and 1.8 does not. I don't know about owncloud 7 server, have you tried with owncloud 8 server? Maybe there is a bug in the owncloud server in addition to this bug on the client. 

If you need, ask Klaas to access our test account so you can remove the server bug from the loop. 

kuba

--

**Comment by ogoffart** [comment]
The bug report say:

> client leaves the server in inconsistent state if [...]

But whatever the client does, the server should never be in an inconsistent state.

Anyway, can you confirm that the client recieve the file-id of the disrectory.  And that on the next sync the directory that has changed name still ahs the same file-id?

Normaly what should happen is that:

 - When the directory is added, the client stores the entry for it in the database with the file-id present in the header, or as a reply to the PROPFIND done right after the MKCOL.   
 - Files are then uploaded.
 - When renaming the folder on the server, the client still tries to upload the file with the old name.   But as the folder no longer exists on the server, this mean that the server will error out for most of the files.
 - On the next sync, we see that the foldre has been renamed so we rename it as well on the client, and upload all the files that were missing.
 - Now everything should be fine.


I can  think about a problem if the following happen:
 - The client try to upload a folder called `folder1`
 - While uploading, one renames `folder1` -> `folder2` via the web interface
 - One create a new folder called `folder1`

In that case, the client will continue to upload the files to the new `folder1` But as a result, the files uploaded first will be in `folder2` and the files uploaded after that will be in `folder1` And the client will not detect the folder move because the original is still there. (so it will move some of the file)

But i'm afraid there is very little we can do against that....

**Comment by moscicki** [comment]
The "normal" scenario you describe is exactly what happens on 1.7 client (but does not happen on 1.8 client).

The other scenario is less likely anyway and I am not sure if needs addressing (users should understand a bit the limitations in order to use the system). If needed, a possible way to address this is to make PUT conditional on the inode number of the containing directory (but that could logically open path for some other nasty errors or inconsistencies).

**Comment by moscicki** [comment]
@dragotin: could we please classify this as a bugfix for next release?

@ogoffart: I have added a test for the scenario similar to the second one you describe (for the moment only on the client-side renames, not the server-side which will be a separate test).
https://github.com/cernbox/smashbox/blob/master/lib/test_localDirRenameRecreate.py

**Comment by moscicki** [comment]
Hello,

Any update on this, please? It is a regression from 1.7.2 and we would like to have it fixed in 1.8 line.

kuba

--

**Comment by ogoffart** [comment]
I have investigated this issue:
Here is what i see in wireshark for the client that does the move (same TCP connection)

```
HTTP/1.1 207 Multi-Status
Date: Wed, 29 Jul 2015 08:37:07 GMT
[...]
Connection: Keep-Alive
Transfer-Encoding: chunked
Content-Type: application/xml; charset=utf-8

2000
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/webdav/subdir/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getlastmodified>Wed, 29 Jul 2015 08:37:07 GMT</d:getlastmodified><d:getetag>"55b890b363c5b"</d:getetag><oc:id>00015656ocece2c41de3</oc:id>
[...]
```

We see that the file id of subdir is `00015656ocece2c41de3`
This is consistant with the previous call to MKCOL done much before and to what is in the local DB of all the clients. 

```
MOVE /remote.php/webdav/subdir HTTP/1.1
Destination: /remote.php/webdav/subdir2
User-Agent: Mozilla/5.0 (Linux) mirall/1.7.0
Cookie: ocece2c41de3=l6k8m9g7p562h6f1241niiems0
Connection: Keep-Alive
Accept-Encoding: gzip, deflate
Accept-Language: de-DE,en,*
Host: 127.0.0.1
Authorization: Basic ***censored***

```

```
HTTP/1.1 201 Created
Date: Wed, 29 Jul 2015 08:37:07 GMT
Server: Apache/2.4.16 (Unix) PHP/5.6.11
X-Powered-By: PHP/5.6.11
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
Pragma: no-cache
Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *; connect-src *
OC-FileId: 00015705ocece2c41de3
Content-Length: 0
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
X-Robots-Tag: none
X-Frame-Options: SAMEORIGIN
Keep-Alive: timeout=5, max=97
Connection: Keep-Alive
Content-Type: text/html; charset=UTF-8
```


The problem is that it returns a `OC-FileId: 00015705ocece2c41de3` which is different from before. 

@PVince81  Why would a MOVE change the file id?

**Comment by guruz** [comment]
@icewind1991 ^^

**Comment by PVince81** [comment]
The fileid shouldn't change on move.
There were cases pre < 8.1 where the fileid could change when moving between storages, but this was fixed in 8.1 (see https://github.com/owncloud/core/issues/13310)

Is this a plain simple MOVE or are shared folders involved ?

**Comment by PVince81** [comment]
@ogoffart what server version ?

**Comment by PVince81** [comment]
### Steps I tried on 8.1.0:

1. Login with cadaver
1. "mkdir subdir"
1. Check fileid of "subdir" in the database: 11
1. "mkdir subdir2"
1. "mv subdir subdir2"
1. Check fileid of "subdir2/subdir" in the database: still 11.

Let me check what happens when client 1.8.2-beta1 does the move.

**Comment by PVince81** [comment]
So now with server v8.1.0 and client v1.8.2-beta1:

1. Setup sync client, then locally:
1. Create folder "subdir2"
1. Create folder "subdir"
1. Wait for sync
1. Check fileid of "subdir" in server's database: 13
1. Still locally, move "subdir" into "subdir2"
1. Wait for sync
1. Check fileid of "subdir" in server's database: 13

The file id didn't change.

@ogoffart can you provide more info ?

**Comment by ogoffart** [comment]
@PVince81  The server is 8.1.0  there are two syncs in parallel. One is adding files into the folder that is being moved, and the other one is calling MOVE.

Indeed in the normal case the MOVE does not change the oc-fileid.  It is only in this case reproduced by the  test_concurrentDirMove.py  smashbox test that it seems to change the file id.

**Comment by PVince81** [comment]
@ogoffart ok then it's a case of concurrency.
Can you try setting "filesystem_check_changes" to 0 on the server ?

I suspect that the concurrent process triggers the scanner's discovery of new folders. There is a short time window where the folder is already renamed on disk but not yet on database. So if the scanner finds that unindexed folder, it will create a new cache entry for it and it will obviously get a new file id... This sounds a lot like https://github.com/owncloud/core/issues/13391.

The problem should disappear when transactional file locking is enabled in 8.1 where locks will prevent the scanner to index transient folders.

**Comment by PVince81** [comment]
Also due to the short time window, I expect that this bug isn't reproducible consistently so it is normal if you see different results between environments / runs.

**Comment by ogoffart** [comment]
One of the PUT made by the other worker ends up in a `500 internal server error`. 

Server log:

```
{"reqId":"53r6FEZvEgfbhU3qV3TH","remoteAddr":"127.0.0.1","app":"PHP","message":"filemtime(): stat failed for \/usr\/share\/webapps\/owncloud\/data\/smashbox\/files\/subdir\/65ffea05f409b048c65943addd4b4f70 at \/usr\/share\/webapps\/owncloud\/lib\/private\/files\/storage\/local.php#166","level":3,"time":"2015-07-29T08:37:07+00:00"}
{"reqId":"53r6FEZvEgfbhU3qV3TH","remoteAddr":"127.0.0.1","app":"PHP","message":"touch(): Unable to create file \/usr\/share\/webapps\/owncloud\/data\/smashbox\/files\/subdir\/65ffea05f409b048c65943addd4b4f70 because No such file or directory at \/usr\/share\/webapps\/owncloud\/lib\/private\/files\/storage\/local.php#177","level":3,"time":"2015-07-29T08:37:07+00:00"}
{"reqId":"53r6FEZvEgfbhU3qV3TH","remoteAddr":"127.0.0.1","app":"PHP","message":"Call to a member function getEtag() on boolean at \/usr\/share\/webapps\/owncloud\/lib\/private\/connector\/sabre\/file.php#239","level":3,"time":"2015-07-29T08:37:07+00:00"}
```

**Comment by ogoffart** [comment]
`filesystem_check_changes` set to 0 on the server fixes the problem!

**Comment by PVince81** [comment]
I wonder if we should set this to 0 by default, see discussion here https://github.com/owncloud/core/issues/16897

**Comment by moscicki** [comment]
@ogoffart: so now I understand that you also expect the OC-FileId response header from MOVE? And that was not the case in 1.7 client. Correct? Actually why do you need this response header -- logically it should never change, correct?

**Comment by ogoffart** [comment]
No, We are not expecting `OC-FileId` header in response to MOVE.  Normaly it should not change so we don't expect it changing.
But the server does put this header, and it is how i saw that there was something fishy on the server since the file id had changed in this particular case. (And later PRIPFIND sees the changed file id)

**Comment by moscicki** [comment]
If you don't use this response header in the client then it is not the cause of the problem. Or has the smashbox test succeeded after you have set filesystem_check_changes to 0 on the server? In the latter case it means that you use this response header in the client (hence question: why?).

As far as I remember our server does not return OC-FileId in response to MOVE at all and we see the problem. So I am confused.

kuba

--

**Comment by ogoffart** [comment]
The cause of the problem is that the file id changed.  It can be seen in the reply to the MOVE (where it is not yet a problem because the client don't care), but it can also be seen in the next PROFIND with another client (where it is a problem!)

Setting filesystem_check_changes to 0 fixes the smashbox test.

**Comment by moscicki** [comment]
Ok, that makes sense. I will check if id in our case changes or not (I strongly doubt it changes). Otherwise, I don't understand this issue and there must have been another protocol change between 1.7 and 1.8 client.

**Comment by moscicki** [comment]
@cmonteroluque, @dragotin: following up from conversation yesterday what should be "supported" in 1.8 branch and what not: I think *regressions* from previous client version with data handling should have a priority treatment, shouldn't they? If this issue is confirmed a client problem (which is yet to be seen) then this is not an existing problem (like 255 length limit on Windows) but a *regression* from previous version so I don't feel comfortable our users update 1.7 to 1.8 when I know it malfunctions here. What do you think?

**Comment by moscicki** [comment]
@ogoffart,@dragotin: I have evidence that your conclusion about filesystem_check_changes =>0 is not correct. And I re-iterate again that this is a client regression in 1.8 line as far as this test is concerned.

I re-did the test against owncloud server 8.1.0. The test succeeds indeed when filesystem_check_changes is set to 0 but not because there is not problem but because the server is quite slow and the default delaySeconds=3 in the test does not trigger the correct test sequence (so the test scenario is not parallel anymore but sequential). If you try running with increased delaySeconds parameter like below you will hit exactly the same problem I am hitting on our server (which is faster so smaller delay is OK):

bin/smash --verbose -o concurrentMoveDir_nfiles=20 -o concurrentMoveDir_delaySeconds=10 lib/test_concurrentDirMove.py

When a PUT is done towards a directory which does not exist (was moved for example) owncloud server returns 404. Our server returns 500 (which I take as a bug). Anyway, it seems that the correct return code by WebDAV should be 409 (http://www.webdav.org/specs/rfc4918.html#METHOD_PUT).

1.7 sync client is able to resolve the remove MOVE in the next sync cycle and manages to PUT the files to the new directory name on the server whereas 1.8 does not and insists on putting files into OLD directory name (MKCOL'ing it first). So probably you do not resolve the remove changes before resolving the local changes or something like that. 

As a side note: of course the interesting question becomes what happens if you have two moves at the same time (local and remote) -- which one should prevail. Do you have the answer? Predictable and understood handling of "directory conflicts" is desirable.

As a side note 2: @PVince81 may find it interesting but owncloud 8.1.0 server seems losing files in this scenario (with parameters specified as above).

**Comment by PVince81** [comment]
@moscicki you could try enabling transactional locking to avoid losing files: https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_experimental.html (it needs a redis server currentlly, but 8.2 will store the locks in the database as per https://github.com/owncloud/core/pull/17662)

**Comment by moscicki** [comment]
@PVince81: I am actually tracking what I think is a client regression 1.7->1.8. But if you can find this test useful to fix the owncloud server (which for syncing is less of priority for me) -- the better. Regards.

**Comment by ogoffart** [comment]
After a long investigation, i finaly fond what could be the problem:  the blacklist.

We blacklist the files because the PUT returns 404. all files goes on the blacklist for 25 seconds.
So what happens is that the files are not uploaded in the second sync of step 4 because they are on the blacklist.

It works in some cases because in some cases there are 3 sync made in step 4, because we get the "error"  ` "Local file changed during sync."`  which forces a re-sync.

We can find in the log `Item is on blacklist`   and `Local file changed during sync`.  If there is `Local file changed during sync` it works because there will be another sync. which let the time for items on the blacklist to expire.

This is a problem in the test but should not be a problem in practice.


So there is a first issue that there is a race condition in the server. And there is also the blacklist issue.

**Comment by moscicki** [comment]
I think 1.8 introduces several silent changes in the behaviour which this test case detected. I address the points you raised below (and add some new ones).

To go around blacklist effect I added a 25 second wait before doing a final sync by the adder:
  
       @add_worker
       def adder(step):
       ...
          sleep(25)
          step(5,'final check')
          run_ocsync(d)

I see in the logs that indeed the blacklist expired: /tmp/smashdir/test_concurrentDirMove/adder-ocsync.step05.cnt000.log 

```
blacklist entry for  "subdir/dfaa0e96d46bd138bfc31cd9a0e340ec"  has expired! 
blacklist entry for  "subdir/ff06b29d6b7db660f582d6051b74bca1"  has expired! 
blacklist entry for  "subdir/ebf9e9479f7c097efc162368705f57d6"  has expired! 
```

If your claim was correct after 25 seconds everything should work fine. However this is not the case.
The files are uploaded to old location (subdir) so the sync process on this worker must also create the non-existing directory (rather than correctly propagate remote rename of that directory). [[ side note: unfortunately HTTP requests (MKCOL) are not systematically logged by the client]]

I was also puzzled by the "Local file changed during sync" in the logs. That's not possible as there should be no local files or directories concurrently modified by two clients in this test. The two workers operate in their own, separate local directories. Else it is a bug in the testing framework. To verify that I added directory listing (with --full-time option):
```
@add_worker
def adder(step):
    ....
    list_files(d,recursive=True)
    run_ocsync(d,n=2)
    list_files(d,recursive=True)

```

It appears that 1.8 client rounds-up the mtime of the file while following remote renames (as if they were downloaded from the server but they are not!):

```
2015-08-07 16:26:36,429 - INFO - adder - stdout: /tmp/smashdir/test_concurrentDirMove/adder:
total 4
drwxr-xr-x. 2 root root 4096 2015-08-07 16:26:36.400013758 +0200 subdir

/tmp/smashdir/test_concurrentDirMove/adder/subdir:
total 80
-rw-r--r--. 1 root root 10 2015-08-07 16:26:33.829013757 +0200 065d28df6d2f27cb0ea5bccbfa82bcab
-rw-r--r--. 1 root root 10 2015-08-07 16:26:35.469013759 +0200 2af171bd5019a4b329b90fcd44e900c1
-rw-r--r--. 1 root root 10 2015-08-07 16:26:34.296013758 +0200 2e93e7b4ef64b4afaff6d4101f9ef344
-rw-r--r--. 1 root root 10 2015-08-07 16:26:36.168013757 +0200 33abcea076a4da1ab6bff13775103c4f
-rw-r--r--. 1 root root 10 2015-08-07 16:26:32.903013759 +0200 33accf4a7f7c0e5cb411de6d13e62f3a
-rw-r--r--. 1 root root 10 2015-08-07 16:26:31.973013759 +0200 3b3ec9fc71d7992467ee42dcb246d11b
-rw-r--r--. 1 root root 10 2015-08-07 16:26:32.672013759 +0200 4640d3f368fd196538cd8bd6dc307633
-rw-r--r--. 1 root root 10 2015-08-07 16:26:32.205013758 +0200 5483610c3752c69bdd44907af49b5b08
-rw-r--r--. 1 root root 10 2015-08-07 16:26:34.527013758 +0200 66a4534d9c7d9006589f9b31084d8b37
-rw-r--r--. 1 root root 10 2015-08-07 16:26:33.598013758 +0200 73d0cd570b4f3fb49587f350a9ec104a
-rw-r--r--. 1 root root 10 2015-08-07 16:26:35.002013757 +0200 7857006db97ed6673b56a54684c06a58
-rw-r--r--. 1 root root 10 2015-08-07 16:26:33.366013757 +0200 96d0a3d669c11f4037013bb349cb52e8
-rw-r--r--. 1 root root 10 2015-08-07 16:26:34.761013757 +0200 9cfc3b247845c7366ca5986bd6a4f3ad
-rw-r--r--. 1 root root 10 2015-08-07 16:26:35.702013759 +0200 9da935c1d4c9af956facd4ac217999f3
-rw-r--r--. 1 root root 10 2015-08-07 16:26:32.437013759 +0200 9f62f32fbf28dbbec595530d859c3729
-rw-r--r--. 1 root root 10 2015-08-07 16:26:36.400013758 +0200 a6a93e44f30af3efaf16ed5500ec7f4d
-rw-r--r--. 1 root root 10 2015-08-07 16:26:34.060013757 +0200 b0cf4e6af03e46dfffc959508f7a433f
-rw-r--r--. 1 root root 10 2015-08-07 16:26:35.236013758 +0200 b1cc496daecce7c5970caedabccad884
-rw-r--r--. 1 root root 10 2015-08-07 16:26:33.135013757 +0200 c006dd116fec7a81ebe33078365aaf55
-rw-r--r--. 1 root root 10 2015-08-07 16:26:35.935013758 +0200 c5d1136578f056039c9da2e4c8aac388

....


2015-08-07 16:26:44,953 - INFO - adder - sync finished: 0:00:00.469016
2015-08-07 16:26:44,953 - INFO - adder - running 'ls -lR --full-time /tmp/smashdir/test_concurrentDirMove/adder'
2015-08-07 16:26:44,958 - INFO - adder - stdout: /tmp/smashdir/test_concurrentDirMove/adder:
total 8
drwxr-xr-x. 2 root root 4096 2015-08-07 16:26:41.697013756 +0200 subdir
drwxr-xr-x. 2 root root 4096 2015-08-07 16:26:44.376013758 +0200 subdir2

/tmp/smashdir/test_concurrentDirMove/adder/subdir:
total 20
-rw-r--r--. 1 root root 10 2015-08-07 16:26:35.469013759 +0200 2af171bd5019a4b329b90fcd44e900c1
-rw-r--r--. 1 root root 10 2015-08-07 16:26:36.168013757 +0200 33abcea076a4da1ab6bff13775103c4f
-rw-r--r--. 1 root root 10 2015-08-07 16:26:35.236013758 +0200 b1cc496daecce7c5970caedabccad884
-rw-r--r--. 1 root root 10 2015-08-07 16:26:33.135013757 +0200 c006dd116fec7a81ebe33078365aaf55
-rw-r--r--. 1 root root 10 2015-08-07 16:26:35.935013758 +0200 c5d1136578f056039c9da2e4c8aac388

/tmp/smashdir/test_concurrentDirMove/adder/subdir2:
total 60
-rw-r--r--. 1 root root 10 2015-08-07 16:26:37.000000000 +0200 065d28df6d2f27cb0ea5bccbfa82bcab
-rw-r--r--. 1 root root 10 2015-08-07 16:26:37.000000000 +0200 2e93e7b4ef64b4afaff6d4101f9ef344
-rw-r--r--. 1 root root 10 2015-08-07 16:26:37.000000000 +0200 33accf4a7f7c0e5cb411de6d13e62f3a
-rw-r--r--. 1 root root 10 2015-08-07 16:26:37.000000000 +0200 3b3ec9fc71d7992467ee42dcb246d11b
-rw-r--r--. 1 root root 10 2015-08-07 16:26:37.000000000 +0200 4640d3f368fd196538cd8bd6dc307633
-rw-r--r--. 1 root root 10 2015-08-07 16:26:38.000000000 +0200 5483610c3752c69bdd44907af49b5b08
-rw-r--r--. 1 root root 10 2015-08-07 16:26:39.000000000 +0200 66a4534d9c7d9006589f9b31084d8b37
-rw-r--r--. 1 root root 10 2015-08-07 16:26:39.000000000 +0200 73d0cd570b4f3fb49587f350a9ec104a
-rw-r--r--. 1 root root 10 2015-08-07 16:26:39.000000000 +0200 7857006db97ed6673b56a54684c06a58
-rw-r--r--. 1 root root 10 2015-08-07 16:26:39.000000000 +0200 96d0a3d669c11f4037013bb349cb52e8
-rw-r--r--. 1 root root 10 2015-08-07 16:26:39.000000000 +0200 9cfc3b247845c7366ca5986bd6a4f3ad
-rw-r--r--. 1 root root 10 2015-08-07 16:26:39.000000000 +0200 9da935c1d4c9af956facd4ac217999f3
-rw-r--r--. 1 root root 10 2015-08-07 16:26:39.000000000 +0200 9f62f32fbf28dbbec595530d859c3729
-rw-r--r--. 1 root root 10 2015-08-07 16:26:39.000000000 +0200 a6a93e44f30af3efaf16ed5500ec7f4d
-rw-r--r--. 1 root root 10 2015-08-07 16:26:40.000000000 +0200 b0cf4e6af03e46dfffc959508f7a433f

2015-08-07 16:26:44,959 - INFO - adder - sleeping 25 seconds
```


About return codes: I think the server should return 409 Conflict in this case to be compliant with WebDav. This would allow you to make a smarter decision that blacklisting this particular case -- this indicates a change in the folder structure on the server -- so a potential remote move to follow locally. 

A question: Are files also black-listed upon receiving 500? So can I expect that (until we fix our server) there is no harm if we return 500 instead of 4xx class (hopefully 409 if you agree with the above).

With 1.7 client I *always* get the correct result (all files end-up in the final directory). With 1.8 I *always* get files split in two directories (old and new name).

**Comment by ogoffart** [comment]
Please add the 25 second delay between the two runs of ocsync. in step4.

> The files are uploaded to old location (subdir) so the sync process on this worker must also create the non-existing directory 

I could never observe that.
Could you upload (in a gist for example) the log `adder-ocsync.step04.cnt001.log`  when this happens?
Possibly as well as `adder-ocsync.step04.cnt000.log` and `adder-ocsync.step02.cnt000.log` 

> I think the server should return 409 Conflict in this case to be compliant with WebDav.

Maybe. But that's a server issue.

> A question: Are files also black-listed upon receiving 500?

Yes.  If a file is breaking the server and causing 500 error, it is added in the blacklist.

> So can I expect that (until we fix our server) there is no harm if we return 500 instead of 4xx class 

Correct.

**Comment by moscicki** [comment]
Ok, I added the extra 30 s delay:

```
    step(4,'sync the added files in parallel')
    if delaySeconds<0:
        sleep(-delaySeconds)

    list_files(d,recursive=True)
    run_ocsync(d,n=1)
    list_files(d,recursive=True)
    sleep(30)
    run_ocsync(d,n=1)
    list_files(d,recursive=True)

    step(5,'final check')
    run_ocsync(d)

```

Here are log files: https://cernbox.cern.ch/index.php/s/qPrUgiSh8OQcLVe
Access token: 3324

**Comment by ogoffart** [comment]
from `adder-ocsync.step02.cnt000.log`

```
"INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13);" -169737440194891699 6 "subdir" 13244 0 "1439194055" "2" "4093841:1439194055" "" "" 0 
```

Notice that the fileid is empty.  that's not normal.
The file id comes from the `http://owncloud.org/ns:id`  property returned by the PROPFIND.  Does your server return this property in the propfind?

**Comment by guruz** [comment]
I'm moving this to 2.0.1
If it is really a problem with 2.0 please comment asap

**Comment by ogoffart** [comment]
I'm closing this issue now.  Just re-open if you want to add anything.
