### ISSUE TITLE
Tray icon gone

### ISSUE THREAD

**Issue by k4r7u** [owncloud/client#3326]
The owncloud tray icon is gone since the last update.
"owncloud --logfile -" shows the following error:
![image](https://cloud.githubusercontent.com/assets/8782287/8087303/59a5a638-0f9a-11e5-9c75-d6b826c0204a.png)

OS: elementaryOS Freya
oc client version: 1.8.2

**Comment by ogoffart** [comment]
What's the Qt version, and what is your desktop?

**Comment by k4r7u** [comment]
Qt 4 with Pantheon as Desktop

**Comment by k4r7u** [comment]
If I am not mistaken, there has been a change in the way ownCloud uses the systemtrayicon.
Installing sni-qt brings the ownCloud trayicon back.
