### ISSUE TITLE
Remove the use of QtSingleApplication - deprecated semi-official QT4 API

### ISSUE THREAD

**Issue by dragetd** [owncloud/client#3327]
The use of QtSingleApplication is deprecated and comes from QT4. Even there it was a side-project and never really part of the official API.

See http://forum.qt.io/topic/22460/solved-qtsingleapplication-and-qt-5/4

Would also enable #2952 to be solved.

**Comment by ogoffart** [comment]
There is also a new version of it in the QtCreator source code: http://code.woboq.org/qt5/qt-creator/src/shared/qtsingleapplication/

However this one is Qt5 only, and we still need to support Qt4

**Comment by dragetd** [comment]
Since qt4 will deprecated at some point, I think this is no longer relevant. I hope it is okay if I close this one, then.
