### ISSUE TITLE
When trying to share a file too fast (before it’s synced) – sharing it is not possible anymore

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#3328]
I added a new file to the ownCloud folder. Then directly right clicked it to share. I was greeted with this:
![owncloud share too fast](https://cloud.githubusercontent.com/assets/925062/8103517/6b81c2a8-1029-11e5-9937-9765655de87d.png)
A very technical error. I don’t know what either »OCS«, »API« nor »404« is. These things should never be shown in the interface.
What rather needs to happen is that the file needs to be prioritized for syncing (if there are other files also being synced) and then a spinner should be shown as long as the share URL can not be returned. cc @dragotin @DeepDiver1975 

Ok so then I close the window again. Try right clicking it again after it was correctly synced to share it again:
![owncloud sharing issue](https://cloud.githubusercontent.com/assets/925062/8103518/6b83d0fc-1029-11e5-824c-8b6ea34df1e0.png)
And this error persists. I can not share the file after the initial error. I had to copy it and remove the original one.

**Comment by rullzer** [comment]
Should be fixed by https://github.com/owncloud/client/pull/4169

**Comment by rullzer** [comment]
As far as I can tell this is fixed. Please reopen if not..
