### ISSUE TITLE
error: ‘QScopedValueRollback’ was not declared in this scope

### ISSUE THREAD

**Issue by mckaygerhard** [owncloud/client#3330]
when building owncloud client 1.7.1 got that error:

```
error: ‘QScopedValueRollback’ was not declared in this scope
```

with qt 4.7.3 and gcc 4.5 on debian wheeze with long time support so debian stable too

**Comment by guruz** [comment]
Please don't report duplicate issues
https://github.com/owncloud/client/issues/3334

**Comment by mckaygerhard** [comment]
WTF? ok i'll use gmail with gdrive.. that's the reason why GPL software based are not used in enterprices.

i'm compiling in a small debvice, i cannot install qt5 it's too heavy in load!

the oc client has a command line that i was planned to use.. but now i can see how its the support.

**Comment by danimo** [comment]
@mckaygerhard Qt 4.8 is the minimum requirement. Sorry.

> i'm compiling in a small debvice, i cannot install qt5 it's too heavy in load!

Depending on what device that is, the desktop client might not be suitable anyway in its current form.

> that's the reason why GPL software based are not used in enterprices.

You realize that other competitors (e.g. Dropbox) that also use Qt simply ship their own, and also require at least Qt5? You also realize that if you want something that's not supported by the current maintainers, you have to step up yourself and volunteer? Neither "GPL" nor "Open Source" imply a free lunch.

**Comment by mckaygerhard** [comment]
the desktop are not necesari to run the client.. its now sense that u use more winbuntu like os .. do u already know that owncloud client has a command line opction client?

but dont worry i solved with tyhe most close competitor..

**Comment by danimo** [comment]
> o u already know that owncloud client has a command line opction client?

Yes. I co-maintain it. But it still links against the QtGui library, a dependency which we will get rid of for the next major release

> but dont worry i solved with tyhe most close competitor..

I'm not worried.

**Comment by LukasReschke** [comment]
@mckaygerhard Thanks for contributing issues back. I'd like to remind you of the [ownCloud Community Code of Conduct](https://owncloud.org/community/code-of-conduct/). Statements like "WTF", "do you already know" against one some of the most valued contributors can certainly *not* be considered as respectful nor collaborative.

If you're interested in building the client with fewer dependencies you are more than welcome to contribute back using a Pull Request. We're an open community and always happy to welcome new contributors. However, at the moment it feels that you're only complaining about the fact that a _free_ product cannot be compiled with Qt 4.7 and used on embedded devices.
