### ISSUE TITLE
  When Sync in Windows with Bandwith=80 KBytes (OC) and SO=100KBytes appears "error Operation canceled and connection closed"

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3332]
### Steps to reproduce
1. Desinstall the last version 1.8.2
2. Install the new version 1.8.3
3. Introduce the Server Address
4. Press NEXT
5. Accept the Certificate
6. Press OK
7. Introduce the Username/password
8. Press NEXT
9. In the Local Folder
10. Select Start a clean sync
11. Press CONNECT...
12. Press FINISH

### Expected behaviour
Should not appear "Error: Operation canceled and connection closed"

### Actual behaviour
Whe is SYNC a few minutes later appears "Error: Operation canceled and connection closed"

### Server configuration
DESKTOP v ownCloud-1.8.3.5178-nightly20150611-setup.exe 
SERVER v 8.0.3
And in OC, Bandwidth=80 KBytes
And SO, Bandwidth=100KBytes

**Comment by guruz** [comment]
Please try http://download.owncloud.com/desktop/daily/ownCloud-1.8.3.5188-nightly20150612-setup.exe :)

**Comment by Dianafg76** [comment]
I tested this bug with DESKTOP v ownCloud-1.8.3.5188-nightly20150612-setup.exe, SERVER v{"installed":true,"maintenance":false,"version":"8.0.4.1","versionstring":"8.0.4 RC2","edition":"Enterprise"}. Appears "Error: Operation canceled and connection closed"

**Comment by tps800** [comment]
Same here, with no bandwidth limiting. The client just closes connections after partly transfer of some files. Found this with only Windows, not Linux nor FreeBSD. Clients I'am seeing this bug:
* 1.8.0 (4847)
* 1.8.1 (5050)
* 1.8.2 (5166)

I'm seeing it with servers:
* 8.0.4 (stable)

Switching back to Client 1.7.x this bug vanishes.

![nc158v3_121_owncloud](https://cloud.githubusercontent.com/assets/702156/8258495/ab83265c-16b5-11e5-91d0-8ff728bfe21c.jpg)

Uploading and downloading may seem to hang at the very same files.

**Comment by tps800** [comment]
I've tested the new RC2-Client (1.8.3 (5204)): same problem, same files.

**Comment by guruz** [comment]
@tps800 The rc3 will have a new network DLL that fixes this.
If you want to drop-in replace it now: https://cloud.molkentin.net/index.php/s/pOLLIPKYBLQ38UV

**Comment by guruz** [comment]
@tps800 The rc3 is out, if nothing went wrong there it should also have the new DLL :-)

**Comment by Dianafg76** [comment]
@guruz I tested with the new .DLL, and the DESKTOP ownCloud-1.8.3.5212rc3-setup.exe and with Bandwith=80 (oC) and SO=100Bytes, no more "Error Operation canceled and closed connection "
I close the bug.
@guruz Thank you

**Comment by Dianafg76** [comment]
@tps800 Could you test with this version: ownCloud-1.8.3.5212rc3-setup.exe
Thanks

**Comment by tps800** [comment]
Can't download that:
![nc158v3_122_index of _desktop_daily - chromium](https://cloud.githubusercontent.com/assets/702156/8282770/3a263c02-18f3-11e5-8018-ce48d87caee4.jpg)

**Comment by danimo** [comment]
@tps800 Because it's not a nightly but an RC :). Sorry for the unclear communication. Try https://owncloud.org/install/#testing-development
