### ISSUE TITLE
When Sync in Windows with Bandwith=No Limit (OC) and SO=100KBytes appears "error connection closed"

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3333]
### Steps to reproduce
1. Desinstall the last version 1.8.2
2. Install the new version 1.8.3
3. Introduce the Server Address
4. Press NEXT
5. Accept the Certificate
6. Press OK
7. Introduce the Username/password
8. Press NEXT
9. In the Local Folder
10. Select Start a clean sync
11. Press CONNECT...
12. Press FINISH

### Expected behaviour
Should not appear "Error: connection closed"

### Actual behaviour
Whe is SYNC a few minutes later appears "Error: connection closed"

### Server configuration
DESKTOP v ownCloud-1.8.3.5178-nightly20150611-setup.exe 
SERVER v 8.0.3
And in OC, Bandwidth=No Limit
And SO, Bandwidth=100KBytes

**Comment by guruz** [comment]
Please try http://download.owncloud.com/desktop/daily/ownCloud-1.8.3.5188-nightly20150612-setup.exe :)

**Comment by Dianafg76** [comment]
I tested this bug with DESKTOP v ownCloud-1.8.3.5188-nightly20150612-setup.exe, SERVER v{"installed":true,"maintenance":false,"version":"8.0.4.1","versionstring":"8.0.4 RC2","edition":"Enterprise"}. Appears "Error: Operation canceled and connection closed"

**Comment by Dianafg76** [comment]
@guruz I tested with the new .DLL, and the DESKTOP ownCloud-1.8.3.5212rc3-setup.exe and with Bandwith=No Limit (oC) and SO=100Bytes, no more "Error Operation canceled and closed connection "
I close the bug.
@guruz Thank you
