### ISSUE TITLE
error: QScopedValueRollback: No such file or directory when build in embebed device

### ISSUE THREAD

**Issue by mckaygerhard** [owncloud/client#3334]
when building 1.7.1 client  in basberry i got that error:

```
src/mirall/selectivesyncdialog.cpp:28:32: error: QScopedValueRollback: No such file or directory
```

using gcc 4.5 and qt 4.7.3

**Comment by guruz** [comment]
Sorry, Qt 4.7.3 is way too old.

We recommend Qt 5.4.2

**Comment by mckaygerhard** [comment]
WTF? ok i'll use gmail with gdrive.. that's the reason why GPL software based are not used in enterprices.
