### ISSUE TITLE
Dont ask for Password when Server is in Maintenance mode

### ISSUE THREAD

**Issue by rtznprmpftl** [owncloud/client#3335]
When i put my owncloud Server (8.0.4) in Maintenance Mode, the Client (1.8.2) Asks for a New Password.

IMHO: The handling should be, that if the server is in Maintenance, the client should show a Yellow/Orange Icon Mit the Caption "Syncing is not Available due to server Maintenance"

**Comment by dragotin** [comment]
I can reproduce that this is not working as expected. I will investigate.

**Comment by dragotin** [comment]
Hmm, I suggest to take this patch: https://github.com/owncloud/client/commit/ce0736dbbfe3ce43c65060a9891ff1a5ba7cbc51

But that is only fixing the tray icon and the icon in the status dialog. 

I'd ask @ckamm to review and for ideas concerning the password question @rtznprmpftl sees. @rtznprmpftl are you running a keychain, like kwallet or gnome keychain?

**Comment by rtznprmpftl** [comment]
yes, its kwallet under KDE5

**Comment by dragotin** [comment]
ah, special case! The qtkeychain version 0.4 that we used so far does not support KF5. Can you check your qtkeychain version and update to version 0.5? Thanks!

**Comment by ckamm** [comment]
@rtznprmpftl I wasn't asked for a password after putting the server in maintenance mode with 1.8 or master. Could you upload a log file for me so I can check what's going on? (https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly - warning: logs have file names and server addresses)

**Comment by rtznprmpftl** [comment]
@dragotin i didnt get to upgrade the library (fedora aparently uses an older one) but this is still on my agenda
@ckamm  The log files dont show anything. The last line ist simple: 

```
06-17 14:47:40:448 0x1728bd0 csync_reconcile: Reconciliation for remote replica took 0,12 seconds visiting 6879 files.
06-17 14:47:40:448 0x1728bd0 csync_statedb_close: sqlite3_close=0
```
After that a new,empty logfile is created with no information about the password missmatch

**Comment by rtznprmpftl** [comment]
I had Time to play around with it a little and i discovered that this bug only effects accounts that use LDAP as a Backend, the internal accounts just show a "syncing" icon.

**Comment by MTRichards** [comment]
What this is requesting, I think, is that the server respond to the client with a maintenance mode flag, and the client respects this and doesn't trigger user/pw requests. 

Did I get that right?

**Comment by ckamm** [comment]
@rtznprmpftl @MTRichards Yes, exactly. In maintenance mode the LDAP auth backend replies with an auth failure and the client thinks something is wrong with the credentials. Please check and continue discussion in #2848.
