### ISSUE TITLE
[CernBox] infinite loop on Windows sync client 1.7.2

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3339]
I do not have many details but we have had a case of a sync client on Windows going into a infinite loop for a directory: it was constantly deleting and recreating this directory (and also one nested subdirectory). The user does not remember all the actions but there were several renames of the directories (so he got rid of spaces in the names of this and other directories).

Here is the log of the suspect windows client:
https://gist.github.com/moscicki/164b9ad104beb9dbb2ea

Has anything similar been reported before?

**Comment by moscicki** [comment]
BTW. Some renames were done on the server.

**Comment by ogoffart** [comment]
The log only say "Down" which means the client seems to be replicating what the server reports. Could it be that this directory appear and disapear on the server for some reason?

We had such problems in owncloud when an external storage is temporarily unavaliable and the server just act as if the files were deleted, so the client would delete the files and download them again when it's back. But it was not as frequent.

**Comment by moscicki** [comment]
Okey, but it also seems to create the directory locally.... doesn't it? I checked in the server logs and it seems we only have the activity from one client at that time (to rule out a situation of a ping-pong between the clients)...

**Comment by ogoffart** [comment]
It would be that the server says "The folder is not there" ... "The folder is there" ... "The folder is not there" ... "The folder is there" ...

And the client obeys and remove the folder locally, then recreate it (download it), then remove it....

There used to be a bug in which some errors while parsing the PROPFIND result would let believe the client that the folder was removed, and a further sync would add it again. But that was fixed a long time ago. It could be a similar problem.  Having the actual log from --logfile would help.

**Comment by ogoffart** [comment]
Do you have anything new regarding this issue. Do you think it is a bug in the client?

**Comment by moscicki** [comment]
Sorry, no logs. The issue is certainly there. As far as I can tell this is a client issue.

Side note. I think something should be done in order to make it easier to grab the log files by the end-users. Consider that users report problem a few days after they had seen it (they often spot a problem by chance, they never look into the status of the sync client, let alone the detailed status in the Settings page), their sync client was already possibly restarted or machine rebooted and in general they have no clue what to do to grab the logs.

**Comment by ogoffart** [comment]
But what should i do about this issue if i cannot reproduce it?

**Comment by moscicki** [comment]
For the moment I suggest to keep this in mind and next time it is reported by us or someone else we know that this has already been seen.
