### ISSUE TITLE
"Connection closed"-issue when synchronizing from Dropbox

### ISSUE THREAD

**Issue by KingCrunch** [owncloud/client#3341]
I use `owncloud-client` `1.8.2` on Arch-Linux. At all it works fine, but at some point synchronize simply stops and after some time it fails with "Connection closed". It was reproduceable and it were always the three same PDFs affected. When I looked into the logs I've seen this

    Error	
    files_external	
    Error: (461) This file is no longer available due to a takedown request under the Digital Millennium Copyright Act by Code School LLC.
    2015-06-14T21:02:13+00:00

On the other hand it seems, that the original Dropbox-client doesn't have any issue with this files.

**Comment by guruz** [comment]
So this does not appear on a non-Dropbox external storage?

Can you please report this in https://github.com/owncloud/core ?
Also make sure to use the latest server version..

**Comment by danimo** [comment]
Also I think the error message is pretty clear, and comes from DropBox. Did you try to actually download the file in question in the web interface?
