### ISSUE TITLE
libocsync.dll missing when running desktop client .exe

### ISSUE THREAD

**Issue by hamzaelfassi** [owncloud/client#3343]
After building the owncloud desktop client in Opensuse 13.1, i'm having an issue when i run the .exe saying that the libocsync.dll is missing.
Sorry for my english and thank you in advance.

**Comment by danimo** [comment]
You cannot just copy off the binaries and run them, you need to create an installer. and run that. Also, this gives far too little information. What version are you building? From tar ball or git? What are you trying to accomplish.

**Comment by hamzaelfassi** [comment]
I downloaded the binaries from git and built the installer (owncloud1.8.1.exe) with the command make

**Comment by hamzaelfassi** [comment]
i totally missed the command make package, thank you
