### ISSUE TITLE
German for "Copy link" should be "Link kopieren"

### ISSUE THREAD

**Issue by jondo** [owncloud/client#3345]
I am a native German speaker using `ownCloud-1.8.1.5050-setup.exe`. The context menu of synced files and folders contains an item `Via ownCloud teilen` (share via ownCloud). The resulting dialog has a button that says `Kopieren link`, which is the wrong way around and should say `Link kopieren` instead.

**Comment by jondo** [comment]
Additionally, the checkbox `Passwort geschützt` should be `Passwortgeschützt` (or `Mit Passwort schützen`, which would be the infinitive form like everywhere else).

**Comment by RealRancor** [comment]
Hi,

from what i know translations are handled in https://www.transifex.com/projects/p/owncloud/ where its recommended to submit such translation problems.

**Comment by danimo** [comment]
I fixed those issues now in transifex.
