### ISSUE TITLE
Desktop Client move issue

### ISSUE THREAD

**Issue by Grevous** [owncloud/client#3349]
So here is the issue, when moving a file in owncloud from a non admin client. There is a chance of duplicating the file.

I started by moving a test file to a sub folder (see duplication1.png), which resulted in a successful move.
![duplication1](https://cloud.githubusercontent.com/assets/12898260/8165392/5c48a97e-134d-11e5-9040-050cfde37635.png)

I then proceeded to move the image again to the folder try_moving_again (see duplication2.png).
![duplication2](https://cloud.githubusercontent.com/assets/12898260/8165397/6012c850-134d-11e5-8e31-2727f685d6c8.png)

This appears to show it moving successfully again waiting for the sync to occur. When it does duplication3.png occurs.
![duplication3](https://cloud.githubusercontent.com/assets/12898260/8165400/62f5a614-134d-11e5-8a57-cd00975143eb.png)

The file is synced in its current directory and waiting to sync in the folder i wished to move it to. It is still waiting to sync. The only way to finish it is to pause and resume the sync.

On one of these attempts I noticed the file contents itself where edited. See instanceOfDataLossOne and Two.
![instanceofdatalossone](https://cloud.githubusercontent.com/assets/12898260/8165402/67d609da-134d-11e5-8964-4d52a0bad900.png)

![instanceofdatalosstwo](https://cloud.githubusercontent.com/assets/12898260/8168731/31e3f98a-1362-11e5-9b14-be75cc90fc99.png)

Version 1.8.1(build 2335)

Any Ideas?

**Comment by moscicki** [comment]
Looks pretty bad. Did you wait until the client synchronized your changes (blue icon for a moment and then turning green again) before you proceeded with the next move operation? Or did you do it WHILE  or BEFORE the client was synchronizing the changes? How many files (in all subdirectories) do you have in your local sync directory tree?

**Comment by Grevous** [comment]
Waited for the sync to occur :(

**Comment by Grevous** [comment]
9 files, 5 folders,so a small test amount

**Comment by moscicki** [comment]
OK, then I cannot comment on 1.8.1 client (we use 1.7 line) . Are you able to reproduce it? I guess you do drag/drop via Finder, right? 

It would be great if developers could give you access to 1.7.1 client to see if you see the same problem. I think you should also specify the server version because maybe you have a buggy server too.

We programmatically test our client/server combination for such errors and it is fine. For example: https://github.com/cernbox/smashbox/blob/master/lib/test_fileMove.py, https://github.com/cernbox/smashbox/blob/master/lib/test_dirMove.py.

**Comment by Grevous** [comment]
Grabbed 1.7.1 from older versions download on site. Issue can be duplicated here as well, help section within webclient leads me to believe server info is 8.1.

**Comment by dragotin** [comment]
It would be helpful to actually have real information about it, which a logfile would provide.

**Comment by Grevous** [comment]
Any way to pull a nice log file out? I could not find one, or would you like the activity log?

**Comment by Grevous** [comment]
Er, sync activity

**Comment by dragotin** [comment]
here we go: https://doc.owncloud.com/desktop/1.8/troubleshooting.html

**Comment by RealRancor** [comment]
@Grevous 
This is also described in the issue template: https://raw.githubusercontent.com/owncloud/client/master/issue_template.md which should be reported for new issues anyway.

**Comment by Grevous** [comment]
Anything I can do to parce through this log file or trim it down for everyone? Got the logs for a successfull duplication, all the way to it actually syncing the duplicated file as well, but its 811 lines long.

**Comment by Grevous** [comment]
Hello, it appears as though the file locking that was enabled a couple days ago has finally decided to kick in (syncs are noticeably slower, only thing changed). I am no longer able to duplicate the issue. 

Thank you for showing me how to get to the log window/file, as well as the proper issue template. Most of all thank you for your time.
