### ISSUE TITLE
"OC Overlay Handler" causes crashes in Firefox/Chrome when displaying save dialog (1.8.2 build 5166)

### ISSUE THREAD

**Issue by jaakristioja** [owncloud/client#3352]
Using ShellExView, I tracked the problem to "OC Overlay Handler" i.e. OCOverlays_x86.dll. Disabling all 8 instances if it in ShellExView makes the crashes disappear.

**Comment by guruz** [comment]
@jaakristioja Can you try a recent 1.8.3 nightly build? http://download.owncloud.com/desktop/daily/

**Comment by jturcotte** [comment]
Which version of ownCloud did you use, on which version of Windows?

**Comment by jaakristioja** [comment]
The 32-bit Windows 7 installation (with latest updates) had 1.8.2 build 5166 installed. I will install and try out the nightly next time I get access to the machine. I can't do it immediately because it was not my own computer.

**Comment by jturcotte** [comment]
Ok thanks, most likely a dupplicate of #3320 but it's weird that it didn't crash explorer completely in your case, maybe you didn't restart yet? Let see if the 1.8.3 nightly helps.

**Comment by jaakristioja** [comment]
Same issue with 1.8.3-nightly20150620 (build 5207).

**Comment by jturcotte** [comment]
Could you confirm that you restarted Windows and still get the crash afterward? It won't have any effect otherwise.

**Comment by jaakristioja** [comment]
Are you sure? Unfortunately I can't restart the machine now, but maybe next week. Maybe... The ShellExView workaround still works thou.

**Comment by jturcotte** [comment]
Yes, since the old dll is still in use by exlorer.exe, the installer will decide to postpone the replacement and registration of the new shell extension DLLs until you re-login.

**Comment by guruz** [comment]
@jaakristioja Hi, we have 2.0 coming out soon. Could you try again? Make sure to uninstall previous version!

http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.5404-nightly20150817-setup.exe

**Comment by guruz** [comment]
@jaakristioja I'll close this for now, please re-open if you have this with 2.0

**Comment by jaakristioja** [comment]
I'm dropping this since my friend switched to Linux and I have no motivation to try to reproduce or debug this on Windows, even if I were to find a Windows machine I could use. No more Windows for me, thanks!
