### ISSUE TITLE
[Windows] Watch events for target directory of downloaded file

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3353]
(Placeholder)

When downloading a file /foo/x.txt the windows file watcher gets an event for /foo/x.txt and for /foo/ itself. The /foo/ itself directory tries to trigger a sync and fails because sync is running.

I was wondering how/if this impacts performance because of the several log messages created and the sync trying to be scheduled.
I guess the event happens because it is supposed to mean "the directory /foo/ has changed because a file has appeared in it"?

I don't know how to solve this, maybe an appearing file would generate an event in itself?
Or the events could be compressed (within a 5 sec period or so)

**Comment by ckamm** [comment]
I can reproduce the notifications. I also tested that adding a new file or deleting a file does indeed trigger a change notification for the particular file as well.

**Comment by guruz** [comment]
However you fix this, keep https://github.com/owncloud/client/issues/2297 as a future compatibility in mind :)

**Comment by ckamm** [comment]
I doubt it had any performance implications, but I've filtered out the unnecessary notifications now. :)
