### ISSUE TITLE
The tray icon is not always up to date

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#3354]
To reproduce:
* Start the master-based client while having one folder configured.
* Look at the tray icon.

It shows the sync icon and says "Folder ...: Waits to start syncing" even though the log shows that the sync has finished. The account settings window also shows the folder's sync status as green.

The icon updates once the next etag job for the folder finishes.

**Comment by Dianafg76** [comment]
I tested with Desktop v 2.0.0 (build 5232)
Sever v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}, and it is shown correctly

I close the issue
