### ISSUE TITLE
several folders are constantly syncing and the clients are logging error messages for these folders

### ISSUE THREAD

**Issue by gig13** [owncloud/client#3357]
### Steps to reproduce
Unable to reproduce

### Expected behaviour
Folders should complete a sync and error messages should not be appearing.

### Actual behaviour
The clients are constantly generating error messages for several folders that are displayed in the Windows explorer as constantly syncing. The error messages are "The filename, directory name, or volume label syntax is incorrect"

### Server configuration
**Operating system**: gathering info

**Web server:** Apache

**Database:** MySQL

**PHP version:** gathering info

**ownCloud version:**  OC8.0.3

**Updated from an older ownCloud or fresh install:** updated

**List of activated apps:** gathering info

**The content of config/config.php:** gathering info

**Are you using external storage, if yes which one:**  gathering info

**Are you using encryption:**  no

### Client configuration
**Browser:** n/a

**Operating system:** Windows with 1.8.1  and   Linux with 1.8.2

#### Web server error log
gathering info

#### ownCloud log (data/owncloud.log)
gathering info

**Comment by gig13** [comment]
@dragotin @danimo 
Actually there were two separate issues -- the SSL expiration is not gracefully handled by the client. A restart is a workaround for that.

The other issue which this github is for -- there are 4 directories that are constantly shown as "syncing" in the windows explorer. Performing a files:scan on the user sharing out folders, and upgrading to the latest desktop client 1.8.3. This has been an outstanding issue for months -- gathering additional logs and screen shots.

**Comment by ogoffart** [comment]
log informations and error would be more than helpfull.  Depending on the error message, it may also be a bug or a problem on the server.

**Comment by gig13** [comment]
@ogoffart 
I am awaiting the latest logs from testing with 1.8.3 client. The error message for the problem directories was "The filename, directory name, or volume label syntax is incorrect".

**Comment by gig13** [comment]
The user was able to remove the problematic folders and re-upload. The error messages and "constant syncing" behavior has disappeared. Unfortunately we do not know the exact cause. Closing since we do not have any additional information and syncing is working as expected.
