### ISSUE TITLE
Feature Suggestion: Integrate OC client with local encryption tools

### ISSUE THREAD

**Issue by tilllt** [owncloud/client#3358]
Hi, i got my OC server running on a debian box with the data folder being on a LUKS encrypted volume. All of that is good for the server part: when syncing my data, i got all the files unencrypted on my desktop computer. I don't want to use all-disk encryption on my desktop PC, but i would like to encrypt the OC sync folder.

I could disable OC Sync autostart, run i.e. truecrypt on startup, mount an encrypted volume, manually start OC sync and point it to that truecrypt mount and all would be good. what would be great though is if the OC sync app would have built in support for some kind of encryption, i.e. truecrypt. 

When running it could try to open a volume, if not mounted, request you to mount it (or run the necessary tool to mount it) and once available start the sync process. this would make things much easier and more failsafe, then manually having to take care that things are set up correctly every time you restart the computer.

**Comment by danimo** [comment]
Sorry, but this is currently out of scope of the current road map. That is of course unless someone comes along to add this feature.
