### ISSUE TITLE
Client reuploads the same files over and over again

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#3360]
I had owncloud 8.0.4 on my server.
I set it to maintenance mode but left the sync client 1.8.3-rc2 running.
During that time, I modified two files in my local sync dir.
Once owncloud 8.1.0 RC1 was in place on the server, the sync client resumed.

But then, even after restarting the sync client, I see that the two files are reuploaded over and over again.

Local system is openSUSE Factory x86_64.
Server is openSUSE 13.1 x86_64, ownCloud 8.1.0 RC1 with encryption enabled.

I'll try and provide logs and also check the etags later. Could be a server issue, or something that happened during the upgrade.

**Comment by PVince81** [comment]
This is the etag from the local DB after one of the syncs: 56780becba1e0e05000690cf0aa7de97
```
phash|pathlen|path|inode|uid|gid|mode|modtime|type|md5|fileid|remotePerm|filesize
6701603805584458402|14|work/times.txt|6020894|0|0|0|1434658332|0|56780becba1e0e05000690cf0aa7de97|00042574507a979be894f|RDNVW|8636
```

Using the inspector in the web UI shows me the following etag too: 56780becba1e0e05000690cf0aa7de97

Same with cadaver propget / propfind.

If the etag is the same, it should not reupload the file multiple times.

I'll capture a sync log.

**Comment by PVince81** [comment]
Ok I looked wrong. Obviously the etag on the server and client are the same at the end of the sync.

Then the next reupload happens, the etag changes on both databases.

The two files that reupload are called:
- work/times.txt
- dev/MtPuzzle-debug-nonlegacy.apk

I have another file called "work/pomodoro.txt".

Whenever I edit "work/pomodoro.txt" it will upload that file, but also reupload the two other files!
If I leave the client running it doesn't seem to reupload anything.

Could be a bug in update detection / inotify ?

Let's see what the sync log says.

**Comment by PVince81** [comment]
I see these:
```
06-18 22:38:11:338 0x2807270 csync_ftw: Uniq ID from Database: work/times.txt -> 56780becba1e0e05000690cf0aa7de97
06-18 22:38:11:338 0x2807270 csync_walker: file: /home/vincent/ownCloud/work/times.txt [inode=6020894 size=315]
06-18 22:38:11:339 0x2807270 _csync_detect_update: Database entry found, compare: 1434658332 <-> 1434658332, etag: 56780becba1e0e05000690cf0aa7de97 <-> 56780becba1e0e05000690cf0aa7de97, inode: 6020894 <-> 6020894, size: 315 <-> 8636, perms:  <-> RDNVW
06-18 22:38:11:339 0x2807270 _csync_detect_update: file: work/times.txt, instruction: INSTRUCTION_EVAL <<=
```

later it's INSTRUCTION_NONE:
```
06-18 22:39:42:181 0x31c6110 csync_ftw: Uniq ID from Database: work/times.txt -> 683e69c37dd4b89a451fc1856fab365f
06-18 22:39:42:181 0x31c6110 csync_walker: file: /home/vincent/ownCloud/work/times.txt [inode=6020894 size=315]
06-18 22:39:42:181 0x31c6110 _csync_detect_update: Database entry found, compare: 1434658332 <-> 1434658332, etag: 683e69c37dd4b89a451fc1856fab365f <-> 683e69c37dd4b89a451fc1856fab365f, inode: 6020894 <-> 6020894, size: 315 <-> 315, perms:  <-> 
06-18 22:39:42:181 0x31c6110 _csync_detect_update: file: work/times.txt, instruction: INSTRUCTION_NONE <<=
```

then
```
06-18 22:39:42:836 0x31c6110 csync_walker: file: ownclouds://owncloud.vincentpetry.net/remote.php/webdav/clientsync/work/times.txt [file_id=00042574507a979be894f size=8636]
06-18 22:39:42:836 0x31c6110 _csync_detect_update: Database entry found, compare: 1434658332 <-> 1434658332, etag: 683e69c37dd4b89a451fc1856fab365f <-> 683e69c37dd4b89a451fc1856fab365f, inode: 0 <-> 6020894, size: 8636 <-> 315, perms: RDNVW <-> 
06-18 22:39:42:836 0x31c6110 _csync_detect_update: Need to update metadata for: work/times.txt
06-18 22:39:42:836 0x31c6110 _csync_detect_update: file: work/times.txt, instruction: INSTRUCTION_NONE <<=
```

and once again:
```
06-18 22:41:39:002 0x2a95f60 csync_ftw: Uniq ID from Database: work/times.txt -> 683e69c37dd4b89a451fc1856fab365f
06-18 22:41:39:002 0x2a95f60 csync_walker: file: /home/vincent/ownCloud/work/times.txt [inode=6020894 size=315]
06-18 22:41:39:002 0x2a95f60 _csync_detect_update: Database entry found, compare: 1434658332 <-> 1434658332, etag: 683e69c37dd4b89a451fc1856fab365f <-> 683e69c37dd4b89a451fc1856fab365f, inode: 6020894 <-> 6020894, size: 315 <-> 8636, perms:  <-> RDNVW
06-18 22:41:39:002 0x2a95f60 _csync_detect_update: file: work/times.txt, instruction: INSTRUCTION_EVAL <<=
```

It looks like the size is oscillating between 315 and 8636.

The local file size is 315.
On the server it's 8636 encrypted size and 315 unencrypted size...

And there we have it:
```
dav:/remote.php/webdav/clientsync/work/> propget times.txt
Fetching properties for `times.txt':
DAV: getlastmodified = Thu, 18 Jun 2015 20:12:12 GMT
DAV: getcontentlength = 8636
DAV: resourcetype = 
DAV: getetag = "56780becba1e0e05000690cf0aa7de97"
DAV: getcontenttype = text/plain
```

=> encryption bug

@schiesbn

**Comment by PVince81** [comment]
Ok, and now I remember that I need to do the "encryption migration for 8.1".
Would be good to find a way to block the sync client before that migration is done.

**Comment by PVince81** [comment]
Raised here https://github.com/owncloud/core/issues/17035

**Comment by PVince81** [comment]
@guruz so this means if the sync client sees the same etag on server and client, but the client size is different, the local file wins and will be reuploaded ? (this seems to be what I observed)

**Comment by dragotin** [comment]
Yes, because that indicates a change on the local repo. Remember that local side changes are **not** indicated through ETag changes, but mainly through  modification time changes. However, because of the unlikely possibility that a file changes twice within the same second, the file size is also considered.

That's why. 

@PVince81 and thanks for the impressive analysis of the problem :-)
