### ISSUE TITLE
master-branch build broken

### ISSUE THREAD

**Issue by franpinsoro** [owncloud/client#3362]
I was compiling to windows when this error ocurr:
[ 93%] Building CXX object src/gui/CMakeFiles/owncloud.dir/__/3rdparty/qtsingleapplication/qtlocalpeer.cpp.obj
[ 93%] Building CXX object src/gui/CMakeFiles/owncloud.dir/__/3rdparty/qtsingleapplication/qtsingleapplication.cpp.obj
[ 94%] Building CXX object src/gui/CMakeFiles/owncloud.dir/__/3rdparty/qtsingleapplication/qtsinglecoreapplication.cpp.obj
[ 94%] Building CXX object src/gui/CMakeFiles/owncloud.dir/__/3rdparty/certificates/p12topem.cpp.obj
[ 95%] Building CXX object src/gui/CMakeFiles/owncloud.dir/__/3rdparty/qtlockedfile/qtlockedfile_win.cpp.obj
[ 96%] Building CXX object src/gui/CMakeFiles/owncloud.dir/owncloud_automoc.cpp.obj
Linking CXX executable ../../bin/owncloud.exe
CMakeFiles/owncloud.dir/objects.a(credentialsfactory.cpp.obj): In function `ZN3OCC16DummyCredentialsC1Ev':
/home/fran/mirall/src/gui/../libsync/creds/dummycredentials.h:22: undefined reference to `vtable for OCC::DummyCredentials'
CMakeFiles/owncloud.dir/objects.a(shibbolethcredentials.cpp.obj): In function `ZN3OCC21ShibbolethCredentials18syncContextPreInitEP7csync_s':
/home/fran/mirall/src/gui/creds/shibbolethcredentials.cpp:116: undefined reference to `OCC::handleNeonSSLProblems(char const*, char*, unsigned int, int, int, void*)'
collect2: error: ld returned 1 exit status
src/gui/CMakeFiles/owncloud.dir/build.make:1982: recipe for target 'bin/owncloud.exe' failed
make[2]: *** [bin/owncloud.exe] Error 1
CMakeFiles/Makefile2:307: recipe for target 'src/gui/CMakeFiles/owncloud.dir/all' failed
make[1]: *** [src/gui/CMakeFiles/owncloud.dir/all] Error 2
Makefile:136: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by guruz** [comment]
Which branch are you on?
Which git commit?

**Comment by TByte007** [comment]
Same here 
From git://github.com/owncloud/client
   01efba9..bf9bb26  1.8        -> origin/1.8
 * [new tag]         v1.8.3     -> v1.8.3
Already up-to-date.

Win7 , Qt 5.4, MinGW 4.9 32bit, OpenSSL 1.02c. If you need to know anything else please ask.

Regards.

**Comment by guruz** [comment]
@jturcotte Can you help me out here?

@TByte007 Maybe post the full cmake output you get

**Comment by jturcotte** [comment]
I never tried to build it in cygwin/msys, did it work before? Or are you cross-compiling?

**Comment by TByte007** [comment]
@jturcotte https://github.com/owncloud/client/blob/master/doc/building.rst using this HOWTO

**Comment by TByte007** [comment]
[ 22%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/propagateremotemove.cpp.obj
[ 23%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/propagateremotemkdir.cpp.obj
[ 23%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/syncengine.cpp.obj
[ 24%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/syncfilestatus.cpp.obj
[ 24%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/syncjournaldb.cpp.obj
[ 25%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/syncjournalfilerecord.cpp.obj
[ 25%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/syncresult.cpp.obj
[ 26%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/theme.cpp.obj
[ 26%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/utility.cpp.obj
[ 27%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/ownsql.cpp.obj
[ 27%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/transmissionchecksumvalidator.cpp.obj
[ 28%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/creds/dummycredentials.cpp.obj
[ 28%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/creds/abstractcredentials.cpp.obj
[ 29%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/creds/credentialscommon.cpp.obj
[ 30%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/creds/httpcredentials.cpp.obj
[ 30%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/__/3rdparty/qjson/json.cpp.obj
[ 31%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/__/3rdparty/certificates/p12topem.cpp.obj
[ 31%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/owncloudsync_automoc.cpp.obj
[ 32%] Linking CXX shared library ..\..\bin\libowncloudsync.dll
[ 32%] Built target owncloudsync
[ 33%] Automatic moc for target owncloud
Generating moc_QProgressIndicator.cpp
Generating moc_fancylineedit.cpp
Generating moc_qtlocalpeer.cpp
Generating moc_qtsingleapplication.cpp
Generating moc_qtsinglecoreapplication.cpp
Generating moc_accountmanager.cpp
Generating moc_accountsettings.cpp
Generating moc_accountstate.cpp
Generating moc_addcertificatedialog.cpp
Generating moc_application.cpp
Generating moc_authenticationdialog.cpp
Generating moc_httpcredentialsgui.cpp
Generating moc_shibbolethrefresher.cpp
Generating moc_shibbolethuserjob.cpp
Generating moc_shibbolethwebview.cpp
Generating moc_shibbolethcredentials.cpp
Generating moc_folder.cpp
Generating moc_folderman.cpp
Generating moc_folderstatusdelegate.cpp
Generating moc_folderstatusmodel.cpp
Generating moc_folderwatcher.cpp
Generating moc_folderwatcher_win.cpp
Generating moc_folderwizard.cpp
Generating moc_generalsettings.cpp
Generating moc_ignorelisteditor.cpp
Generating moc_logbrowser.cpp
Generating moc_networksettings.cpp
Generating moc_owncloudgui.cpp
Generating moc_owncloudsetupwizard.cpp
Generating moc_protocolwidget.cpp
Generating moc_quotainfo.cpp
Generating moc_selectivesyncdialog.cpp
Generating moc_settingsdialog.cpp
Generating moc_sharedialog.cpp
Generating moc_socketapi.cpp
Generating moc_sslbutton.cpp
Generating moc_sslerrordialog.cpp
Generating moc_systray.cpp
Generating moc_owncloudadvancedsetuppage.cpp
Generating moc_owncloudconnectionmethoddialog.cpp
Generating moc_owncloudhttpcredspage.cpp
Generating moc_owncloudsetuppage.cpp
Generating moc_owncloudshibbolethcredspage.cpp
Generating moc_owncloudwizard.cpp
Generating moc_owncloudwizardresultpage.cpp
[ 33%] Built target owncloud_automoc
[ 34%] Automatic moc for target updater
Generating moc_ocupdater.cpp
[ 34%] Built target updater_automoc
Scanning dependencies of target updater
[ 35%] Building CXX object src/gui/CMakeFiles/updater.dir/updater/ocupdater.cpp.obj
[ 35%] Building CXX object src/gui/CMakeFiles/updater.dir/updater/updateinfo.cpp.obj
[ 36%] Building CXX object src/gui/CMakeFiles/updater.dir/updater/updater.cpp.obj
[ 36%] Building CXX object src/gui/CMakeFiles/updater.dir/updater_automoc.cpp.obj
[ 37%] Linking CXX static library libupdater.a
[ 37%] Built target updater
[ 37%] Generating client_zh_TW.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_zh_TW.qm'...
    Generated 357 translation(s) (357 finished and 0 unfinished)
    Ignored 193 untranslated source text(s)
[ 37%] Generating qrc_client.cpp
[ 38%] Generating qrc_theme.cpp
[ 38%] Generating ui_accountsettings.h
[ 39%] Generating ui_folderwizardsourcepage.h
[ 40%] Generating ui_folderwizardtargetpage.h
[ 40%] Generating ui_generalsettings.h
[ 41%] Generating ui_ignorelisteditor.h
[ 41%] Generating ui_networksettings.h
[ 42%] Generating ui_protocolwidget.h
[ 42%] Generating ui_settingsdialog.h
[ 43%] Generating ui_sharedialog.h
[ 43%] Generating ui_sslerrordialog.h
[ 44%] Generating ui_owncloudsetuppage.h
[ 44%] Generating ui_addcertificatedialog.h
[ 45%] Generating ui_owncloudadvancedsetuppage.h
[ 46%] Generating ui_owncloudconnectionmethoddialog.h
[ 46%] Generating ui_owncloudhttpcredspage.h
[ 47%] Generating ui_owncloudsetupnocredspage.h
[ 47%] Generating ui_owncloudwizardresultpage.h
[ 48%] Generating client_ca.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_ca.qm'...
    Generated 467 translation(s) (467 finished and 0 unfinished)
    Ignored 83 untranslated source text(s)
[ 48%] Generating client_cs.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_cs.qm'...
    Generated 550 translation(s) (550 finished and 0 unfinished)
[ 49%] Generating client_de.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_de.qm'...
    Generated 550 translation(s) (550 finished and 0 unfinished)
[ 49%] Generating client_el.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_el.qm'...
    Generated 550 translation(s) (550 finished and 0 unfinished)
[ 50%] Generating client_en.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_en.qm'...
    Generated 0 translation(s) (0 finished and 0 unfinished)
    Ignored 550 untranslated source text(s)
[ 50%] Generating client_es.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_es.qm'...
    Generated 550 translation(s) (550 finished and 0 unfinished)
[ 51%] Generating client_es_AR.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_es_AR.qm'...
    Generated 317 translation(s) (317 finished and 0 unfinished)
    Ignored 233 untranslated source text(s)
[ 51%] Generating client_et.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_et.qm'...
    Generated 470 translation(s) (470 finished and 0 unfinished)
    Ignored 80 untranslated source text(s)
[ 52%] Generating client_eu.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_eu.qm'...
    Generated 382 translation(s) (382 finished and 0 unfinished)
    Ignored 168 untranslated source text(s)
[ 53%] Generating client_fa.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_fa.qm'...
    Generated 185 translation(s) (185 finished and 0 unfinished)
    Ignored 365 untranslated source text(s)
[ 53%] Generating client_fi.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_fi.qm'...
    Generated 428 translation(s) (428 finished and 0 unfinished)
    Ignored 122 untranslated source text(s)
[ 54%] Generating client_fr.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_fr.qm'...
    Generated 550 translation(s) (550 finished and 0 unfinished)
[ 54%] Generating client_gl.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_gl.qm'...
    Generated 550 translation(s) (550 finished and 0 unfinished)
[ 55%] Generating client_hu.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_hu.qm'...
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
    Generated 245 translation(s) (245 finished and 0 unfinished)
    Ignored 305 untranslated source text(s)
[ 55%] Generating client_it.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_it.qm'...
    Generated 550 translation(s) (550 finished and 0 unfinished)
[ 56%] Generating client_ja.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_ja.qm'...
    Generated 521 translation(s) (521 finished and 0 unfinished)
    Ignored 29 untranslated source text(s)
[ 56%] Generating client_nb_NO.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_nb_NO.qm'...
    Generated 550 translation(s) (550 finished and 0 unfinished)
[ 57%] Generating client_nl.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_nl.qm'...
    Generated 550 translation(s) (550 finished and 0 unfinished)
[ 57%] Generating client_pl.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_pl.qm'...
    Generated 478 translation(s) (478 finished and 0 unfinished)
    Ignored 72 untranslated source text(s)
[ 58%] Generating client_pt.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_pt.qm'...
    Generated 547 translation(s) (547 finished and 0 unfinished)
    Ignored 3 untranslated source text(s)
[ 58%] Generating client_pt_BR.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_pt_BR.qm'...
    Generated 550 translation(s) (550 finished and 0 unfinished)
[ 59%] Generating client_ru.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_ru.qm'...
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
    Generated 543 translation(s) (543 finished and 0 unfinished)
    Ignored 7 untranslated source text(s)
[ 60%] Generating client_sk.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_sk.qm'...
    Generated 535 translation(s) (535 finished and 0 unfinished)
    Ignored 15 untranslated source text(s)
[ 60%] Generating client_sl.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_sl.qm'...
    Generated 477 translation(s) (477 finished and 0 unfinished)
    Ignored 73 untranslated source text(s)
[ 61%] Generating client_sr.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_sr.qm'...
    Generated 550 translation(s) (550 finished and 0 unfinished)
[ 61%] Generating client_sv.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_sv.qm'...
    Generated 469 translation(s) (469 finished and 0 unfinished)
    Ignored 81 untranslated source text(s)
[ 62%] Generating client_th.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_th.qm'...
    Generated 185 translation(s) (185 finished and 0 unfinished)
    Ignored 365 untranslated source text(s)
[ 62%] Generating client_tr.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_tr.qm'...
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
    Generated 550 translation(s) (550 finished and 0 unfinished)
[ 63%] Generating client_TW.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_TW.qm'...
    Generated 257 translation(s) (257 finished and 0 unfinished)
    Ignored 92 untranslated source text(s)
[ 63%] Generating client_uk.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_uk.qm'...
    Generated 550 translation(s) (550 finished and 0 unfinished)
[ 64%] Generating client_zh_CN.qm
Updating 'G:/tmp/OCC/client-build/src/gui/client_zh_CN.qm'...
    Generated 497 translation(s) (497 finished and 0 unfinished)
    Ignored 53 untranslated source text(s)
Scanning dependencies of target owncloud
[ 65%] Building CXX object src/gui/CMakeFiles/owncloud.dir/main.cpp.obj
[ 66%] Building CXX object src/gui/CMakeFiles/owncloud.dir/qrc_client.cpp.obj
[ 66%] Building CXX object src/gui/CMakeFiles/owncloud.dir/qrc_theme.cpp.obj
[ 67%] Building CXX object src/gui/CMakeFiles/owncloud.dir/accountmanager.cpp.obj
[ 67%] Building CXX object src/gui/CMakeFiles/owncloud.dir/accountsettings.cpp.obj
[ 68%] Building CXX object src/gui/CMakeFiles/owncloud.dir/application.cpp.obj
G:\tmp\OCC\client\src\gui\application.cpp:274:2: warning: #warning is a GCC extension
 #warning FIXME: this should schedule a sync for the folders of the account that connected
  ^
G:\tmp\OCC\client\src\gui\application.cpp:274:2: warning: #warning FIXME: this should schedule a sync for the folders of the account that connected [-Wcpp]
G:\tmp\OCC\client\src\gui\application.cpp:313:2: warning: #warning is a GCC extension
 #warning FIXME: connection errors should be shown per account
  ^
G:\tmp\OCC\client\src\gui\application.cpp:313:2: warning: #warning FIXME: connection errors should be shown per account [-Wcpp]
[ 68%] Building CXX object src/gui/CMakeFiles/owncloud.dir/folder.cpp.obj
[ 69%] Building CXX object src/gui/CMakeFiles/owncloud.dir/folderman.cpp.obj
[ 69%] Building CXX object src/gui/CMakeFiles/owncloud.dir/folderstatusmodel.cpp.obj
[ 70%] Building CXX object src/gui/CMakeFiles/owncloud.dir/folderstatusdelegate.cpp.obj
[ 70%] Building CXX object src/gui/CMakeFiles/owncloud.dir/folderwatcher.cpp.obj
[ 71%] Building CXX object src/gui/CMakeFiles/owncloud.dir/folderwizard.cpp.obj
[ 71%] Building CXX object src/gui/CMakeFiles/owncloud.dir/generalsettings.cpp.obj
[ 72%] Building CXX object src/gui/CMakeFiles/owncloud.dir/ignorelisteditor.cpp.obj
[ 73%] Building CXX object src/gui/CMakeFiles/owncloud.dir/logbrowser.cpp.obj
[ 73%] Building CXX object src/gui/CMakeFiles/owncloud.dir/networksettings.cpp.obj
[ 74%] Building CXX object src/gui/CMakeFiles/owncloud.dir/openfilemanager.cpp.obj
[ 74%] Building CXX object src/gui/CMakeFiles/owncloud.dir/owncloudgui.cpp.obj
[ 75%] Building CXX object src/gui/CMakeFiles/owncloud.dir/owncloudsetupwizard.cpp.obj
[ 75%] Building CXX object src/gui/CMakeFiles/owncloud.dir/protocolwidget.cpp.obj
[ 76%] Building CXX object src/gui/CMakeFiles/owncloud.dir/selectivesyncdialog.cpp.obj
[ 76%] Building CXX object src/gui/CMakeFiles/owncloud.dir/settingsdialog.cpp.obj
[ 77%] Building CXX object src/gui/CMakeFiles/owncloud.dir/sharedialog.cpp.obj
[ 77%] Building CXX object src/gui/CMakeFiles/owncloud.dir/socketapi.cpp.obj
[ 78%] Building CXX object src/gui/CMakeFiles/owncloud.dir/sslbutton.cpp.obj
[ 78%] Building CXX object src/gui/CMakeFiles/owncloud.dir/sslerrordialog.cpp.obj
[ 79%] Building CXX object src/gui/CMakeFiles/owncloud.dir/syncrunfilelog.cpp.obj
[ 80%] Building CXX object src/gui/CMakeFiles/owncloud.dir/systray.cpp.obj
[ 80%] Building CXX object src/gui/CMakeFiles/owncloud.dir/accountmigrator.cpp.obj
[ 81%] Building CXX object src/gui/CMakeFiles/owncloud.dir/quotainfo.cpp.obj
[ 81%] Building CXX object src/gui/CMakeFiles/owncloud.dir/accountstate.cpp.obj
[ 82%] Building CXX object src/gui/CMakeFiles/owncloud.dir/addcertificatedialog.cpp.obj
[ 82%] Building CXX object src/gui/CMakeFiles/owncloud.dir/authenticationdialog.cpp.obj
[ 83%] Building CXX object src/gui/CMakeFiles/owncloud.dir/creds/credentialsfactory.cpp.obj
[ 83%] Building CXX object src/gui/CMakeFiles/owncloud.dir/creds/httpcredentialsgui.cpp.obj
[ 84%] Building CXX object src/gui/CMakeFiles/owncloud.dir/creds/shibbolethcredentials.cpp.obj
[ 84%] Building CXX object src/gui/CMakeFiles/owncloud.dir/creds/shibboleth/shibbolethwebview.cpp.obj
[ 85%] Building CXX object src/gui/CMakeFiles/owncloud.dir/creds/shibboleth/shibbolethrefresher.cpp.obj
[ 86%] Building CXX object src/gui/CMakeFiles/owncloud.dir/creds/shibboleth/shibbolethuserjob.cpp.obj
[ 86%] Building CXX object src/gui/CMakeFiles/owncloud.dir/wizard/abstractcredswizardpage.cpp.obj
[ 87%] Building CXX object src/gui/CMakeFiles/owncloud.dir/wizard/owncloudadvancedsetuppage.cpp.obj
[ 87%] Building CXX object src/gui/CMakeFiles/owncloud.dir/wizard/owncloudconnectionmethoddialog.cpp.obj
[ 88%] Building CXX object src/gui/CMakeFiles/owncloud.dir/wizard/owncloudhttpcredspage.cpp.obj
[ 88%] Building CXX object src/gui/CMakeFiles/owncloud.dir/wizard/owncloudsetuppage.cpp.obj
[ 89%] Building CXX object src/gui/CMakeFiles/owncloud.dir/wizard/owncloudshibbolethcredspage.cpp.obj
[ 89%] Building CXX object src/gui/CMakeFiles/owncloud.dir/wizard/owncloudwizardcommon.cpp.obj
[ 90%] Building CXX object src/gui/CMakeFiles/owncloud.dir/wizard/owncloudwizard.cpp.obj
[ 90%] Building CXX object src/gui/CMakeFiles/owncloud.dir/wizard/owncloudwizardresultpage.cpp.obj
[ 91%] Building CXX object src/gui/CMakeFiles/owncloud.dir/__/3rdparty/qjson/json.cpp.obj
[ 91%] Building CXX object src/gui/CMakeFiles/owncloud.dir/folderwatcher_win.cpp.obj
[ 92%] Building RC object src/gui/CMakeFiles/owncloud.dir/version.rc.obj
[ 93%] Building CXX object src/gui/CMakeFiles/owncloud.dir/__/3rdparty/fancylineedit/fancylineedit.cpp.obj
[ 93%] Building CXX object src/gui/CMakeFiles/owncloud.dir/__/3rdparty/QProgressIndicator/QProgressIndicator.cpp.obj
[ 94%] Building CXX object src/gui/CMakeFiles/owncloud.dir/__/3rdparty/qtlockedfile/qtlockedfile.cpp.obj
[ 94%] Building CXX object src/gui/CMakeFiles/owncloud.dir/__/3rdparty/qtsingleapplication/qtlocalpeer.cpp.obj
[ 95%] Building CXX object src/gui/CMakeFiles/owncloud.dir/__/3rdparty/qtsingleapplication/qtsingleapplication.cpp.obj
[ 95%] Building CXX object src/gui/CMakeFiles/owncloud.dir/__/3rdparty/qtsingleapplication/qtsinglecoreapplication.cpp.obj
[ 96%] Building CXX object src/gui/CMakeFiles/owncloud.dir/__/3rdparty/certificates/p12topem.cpp.obj
[ 96%] Building CXX object src/gui/CMakeFiles/owncloud.dir/__/3rdparty/qtlockedfile/qtlockedfile_win.cpp.obj
[ 97%] Building CXX object src/gui/CMakeFiles/owncloud.dir/owncloud_automoc.cpp.obj
[ 97%] Linking CXX executable ..\..\bin\owncloud.exe
CMakeFiles\owncloud.dir/objects.a(credentialsfactory.cpp.obj):credentialsfactory.cpp:(.text$_ZN3OCC16DummyCredentialsC1Ev[__ZN3OCC16DummyCredentialsC1Ev]+0x1a):
 undefined reference to `vtable for OCC::DummyCredentials'
CMakeFiles\owncloud.dir/objects.a(shibbolethcredentials.cpp.obj):shibbolethcredentials.cpp:(.text+0x50f): undefined reference to `OCC::handleNeonSSLProblems(cha
r const*, char*, unsigned int, int, int, void*)'
collect2.exe: error: ld returned 1 exit status
src\gui\CMakeFiles\owncloud.dir\build.make:1977: recipe for target 'bin/owncloud.exe' failed
mingw32-make[2]: *** [bin/owncloud.exe] Error 1
CMakeFiles\Makefile2:338: recipe for target 'src/gui/CMakeFiles/owncloud.dir/all' failed
mingw32-make[1]: *** [src/gui/CMakeFiles/owncloud.dir/all] Error 2
makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by TByte007** [comment]
Or do U mean even the lines without errors ?

**Comment by TByte007** [comment]
btw it is strange as I have windres

G:\tmp\OCC\client-build>windres --help
Usage: windres [option(s)] [input-file] [output-file]
 The options are:
  -i --input=<file>            Name input file
  -o --output=<file>           Name output file
...

**Comment by jturcotte** [comment]
Ah you're building master, if you want to build from source please use the 1.8 branch. We're merging all the unstable branches into master at the moment and it won't be usable for a few weeks before we branch it into a 2.0 branch.

**Comment by TByte007** [comment]
thank you :)

**Comment by guruz** [comment]
@TByte007 @franpinsoro Please update your build and re-try.
But as stated above, most probably the 1.8 branch is what you actually want.
