### ISSUE TITLE
Calendar Sharing : Firefox no share button (Safari OK)

### ISSUE THREAD

**Issue by LughI0** [owncloud/client#3363]
Client : OS X 10.9.5 (Mavericks)
Browser : Firefox 38.0.5 
Bug : No way to share a calendar on Firefox, the Share button is not present : 
![firefox_38](https://cloud.githubusercontent.com/assets/12976854/8266825/4d7a6d34-1743-11e5-89b8-f956c5eff47d.png)

On Safari 7.1.5 the button is present, all is ok :
![safari_715](https://cloud.githubusercontent.com/assets/12976854/8266826/5782305a-1743-11e5-9449-6310394fb56f.png)

**Comment by danimo** [comment]
Thank you for your report. This client repository is meant for bug reports to the native ownCloud desktop sync client. Reports for the web front end should go to the [core] (https://github.com/owncloud/core/issues) issue tracker.

**Comment by LughI0** [comment]
Ok. I'll do it.
