### ISSUE TITLE
"Choose what to sync" does not work

### ISSUE THREAD

**Issue by CloudJunkie** [owncloud/client#3364]
I have a folder unchecked in the clients "Choose what to sync" dialog to avoid those files will be uploaded from my notebook to the owncloud server. But: the files will be uploaded to the server at every change. (What is quite bad, since the folder contains a 25 GiB Outlook archive)

Any idea how to solve that?

Thanks

**Comment by guruz** [comment]
> Any idea how to solve that?

Not if you don't explain your setup (versions etc)
https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

**Comment by ogoffart** [comment]
Note that choose what to sync is about things that should not be downloaded.  (Not things that should not be uploaded)

Yet, it should mark the directory as an error and not try to upload it.
