### ISSUE TITLE
[Experimental Files Locking] error when you upload a big file and the same time remane the folder

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3366]
### Steps to reproduce
1. Open your ownCloud desktop client with MAC
2. Create a new folder, called abcd
3. Open your ownCloud desktop client with Windows
4. Wait for sync
5. In ownCloud desktop client with MAC upload a big file (1GB)
6. And the same time in ownCloud desktop with WIN remane the folder abcd by a

### Expected behaviour
the error should not appear

### Actual behaviour
In the ownCloud DESKTOP with MAC, It appears an error

![screen shot 2015-06-23 at 13 39 33](https://cloud.githubusercontent.com/assets/12032058/8305235/55e92318-19ad-11e5-9b43-3c33e6aa319e.png)

And rename  abcd by a

### Server configuration
Desktop v 1.8.3 build 2460 with MAC
Desktop v 1.8.3 build 5214 with WIN
SERVER v {"installed":true,"maintenance":false,"version":"8.1.0.7","versionstring":"8.1 RC1","edition":""} 
Experimental File locking app enable

**Comment by guruz** [comment]
@PVince81 @icewind1991 ?

**Comment by PVince81** [comment]
Please try again with master. Seems one of the most important fixes did not make it into RC1.

**Comment by Dianafg76** [comment]
@PVince81  Thanks!!

**Comment by ogoffart** [comment]
So this is a server bug which is probably already fixed?

**Comment by PVince81** [comment]
Yes, this should work properly when transactional file locking is enabled.
