### ISSUE TITLE
Directly changes in shared folder do not propagate

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/client#3367]
Expected behaviour
If i share a folder to someone, and after that i edit the file directly on owncloud server filesystem, after run the rescan manually, changes should be synced by both the owner and those the one shared the files with ( from now on i will call them 'guests');

Actual behaviour
Files are only synced to the owner. The 'guests'  will keep the old version of the files.

Steps to reproduce
Share a folder to PERSON1
ssh to the server
change any shared file, or add new ones
manually force owncloud rescan (/path/of/owncloud/console.php files:scan owner)
after rescan finishes runnning, the owncloud client will start to sync on the owner account, but it will never sync on guests account

Server configuration

Operating system: Ubuntu 14.04 LTS

Web server: apache 2.4

Database: mysql

PHP version: 5.5.9-1ubuntu4.9

ownCloud version: 8.0.2-8

Storage backend: disk
Client configuration

Client version: 1.8.2

Operating system: Linux Mint 17.1 rebecca

OS language: English

Installation path of client: /usr/bin/owncloud

**Comment by guruz** [comment]
I think this is a bug which is fixed in oC 8.0.4(?)
Could you try that?

CC @PVince81

**Comment by PVince81** [comment]
The major etag propagation rework will be in 8.1.

**Comment by guruz** [comment]
@jsalatiel https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule
Please re-open if bug persists with 8.1
