### ISSUE TITLE
[Windows] Update checker needs to check if the version it tries to silent-update to is still relevant to the current running version

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3368]
We had this when switching to an old version 1.8.0 which downloaded a 1.8.1
We then manually installed 1.8.3 on top and the auto updater silently forced the update to 1.8.1
Meaning we got an old version 1.8.1 even though we had manually installed 1.8.3 some minutes before.

As discussed with @dragotin and @danimo today..
Found out when QAing around with @Dianafg76

**Comment by danimo** [comment]
@Dianafg76 Please test with next one of the nightly builds on Windows. Howto: 

1. Download old version (e.g. 1.8.1). 
2. Wait until the update has downloaded (See "General" tab).
3. Quit the app
4. Manually install a nightly build that's newer than the released version (1.8.4), do not allow the installer to start the client.
5. Manually start the client. It should _not_ execute the update that it just downloaded.

**Comment by Dianafg76** [comment]
@guruz, @danimo  I tested this issue, and working fine
Many thanks, :-)
