### ISSUE TITLE
Investigate valgrind possible issues

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3369]
@dragotin had found some uninitialized memory spots in ```cookiejar.cpp```.

**Comment by ogoffart** [comment]
@dragotin:  can you please paste the backtrace?  i cannot test for uninitialized memory with valgrind because of openssl's too many false positive

**Comment by guruz** [comment]
Would https://rachelbythebay.com/w/2012/12/14/quiet/ help?
https://www.google.de/#safe=off&q=valgrind+ignore+openssl

**Comment by dragotin** [comment]
this as a reminder for a general valgrind check after beta1 is released

**Comment by guruz** [comment]
@ogoffart Close? Did you make a full sync run?

**Comment by ogoffart** [comment]
yes, many sync runs
