### ISSUE TITLE
[Elementary OS Freya] Owncloud notification icon missing

### ISSUE THREAD

**Issue by floxyz** [owncloud/client#3370]
### Expected behaviour
The Elementary OS should show an owncloud notification icon. Until a recent update it was working perfectly. It definitely vanished after an ownlcoud and not after a system update. Sadly I don't remember the last working version.

### Actual behaviour
No icon is shown - the owncloud client is running and can be started using the application menu. An icon would be very useful.

### Steps to reproduce
1. start the owncloud client.
2. no icon in the notification area.

### Server configuration
Operating system:
Ubuntu
Web server:
Apache
ownCloud version:
8.0.4

### Client configuration
Client version:
1.8.3
Operating system:
Elementary OS
OS language:
English/US
Installation path of client:
installed via ppa

**Comment by guruz** [comment]
Can you check the client settings dialog about which Qt version you are using?

**Comment by floxyz** [comment]
Qt 4.8.6
![owncloud-build](https://cloud.githubusercontent.com/assets/1648142/8350022/22ffdd54-1b22-11e5-8d87-bf2add96088c.png)

**Comment by lukitus** [comment]
I have the same problem, same OS:

rcalderon@RCALDERON:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	elementary OS
Description:	elementary OS Freya
Release:	0.3
Codename:	freya
rcalderon@RCALDERON:~$ uname -a
Linux RCALDERON 3.16.0-41-generic #57~14.04.1-Ubuntu SMP Thu Jun 18 18:01:13 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
rcalderon@RCALDERON:~$ 


![owncloud_009](https://cloud.githubusercontent.com/assets/13119525/8432276/b9a5cde6-1f04-11e5-8eef-854490e21632.png)

**Comment by juanhm** [comment]
Try to install sni-qt package

**Comment by lukitus** [comment]
Excellent!! it works now!
Thanks!!

![workspace 1_011](https://cloud.githubusercontent.com/assets/13119525/8505193/1e854aa0-21a5-11e5-9f7a-8944f14bc30c.png)

**Comment by guruz** [comment]
Great :-)
