### ISSUE TITLE
[6.0.9]The same folder/file you can't share in MAC but you can share in WIN

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3372]
### Steps to reproduce
In MAC
1. Open your ownCloud desktop client
2. Go to Open Folder "ownCloud"
3. Create a new folder/file, called 321 
4. Right click on the folder 321
5. Select share with ownCloud

In WIN
1. Open your ownCloud desktop client
2. Go to Open Folder "ownCloud"
3. Create a new folder/file, called 321
4. Right click on the folder 321
5. Select share with ownCloud

### Expected behaviour
1.- In MAC, The error should not appear

### Actual behaviour
1.- In MAC, appear this error:

![screen shot 2015-06-25 at 17 37 23](https://cloud.githubusercontent.com/assets/12032058/8358511/e2987ef8-1b60-11e5-8ca0-b99eb4571e9d.png).

"{"app":"PHP","message":"Invalid argument supplied for foreach() at \/opt\/owncloud\/apps\/files_sharing\/lib\/api.php#103","level":3,"time":"2015-06-25T15:13:51+00:00"}"

2.- In WIN you can share the folder (it is OK)

### Server configuration
DESKTOP:
1.- In MAC v ownCloud-1.8.3.2465-nightly20150625.pkg 
2.- In WIN v ownCloud-1.8.3.5219-nightly20150625-setup.exe 
SERVER v {"installed":"true","version":"6.0.9.0","versionstring":"6.0.9beta","edition":"enterprise"}

**Comment by dragotin** [comment]
I tried this with a normal folder, works for me on both Mac and Windows with nightly build from july 23.

Your screenshot indicates that the file you were trying to share was shared to you without sharing permission. In that case, the Mac behaviour would be correct.

@Dianafg76 could you verify please?

**Comment by Dianafg76** [comment]
@dragotin Is working fine. I close the issue
Desktop v ownCloud-2.0.0.2559-nightly20150723.pkg in Mac
Desktop v ownCloud-2.0.0.5297-nightly20150723-setup.exe in Windows
