### ISSUE TITLE
Client fails to upload files larger than 10mb

### ISSUE THREAD

**Issue by JohannesTress** [owncloud/client#3374]
I can't upload files larger then 10mb. The Client stops after it crossed the 10mb mark and I get an "server replied: internal server error". 
I'm running the linux client under Ubuntu 15.04 and Owncloud is installed on hosted webspace (strato germany). 
Is there anything I can do about it? 

Thanks indeed.

**Comment by dragotin** [comment]
sorry, this is obviously a server setup problem. There are tons of blogs out there discussing the problems with  these kind of providers, please check there. Thanks for your understanding.
