### ISSUE TITLE
Releases don't show build number anymore in log or settings dialog

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3375]

**Comment by dragotin** [comment]
Actually it shows the build number on Windows

**Comment by guruz** [comment]
Indeed, it shows it again for me (the releases 1.8.3 and 1.8.4)
Can it be that rcs or betas did not show it?

**Comment by dragotin** [comment]
@guruz I remember that it was missing, and I fixed it. 

I think we can close this one, right?
