### ISSUE TITLE
Implement update metadata job

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#3377]
To properly support changes to file metadata (like permissions #3244), we need to create two new jobs that propagate metadata changes in both directions.

When a file's metadata on the server changes, the parent directory's etag (recursively up to root) should change (see owncloud/core#16587). The client will do a shallow propfind, find files with changed metadata and should schedule a job to update the local file's metadata to match.

Similarly, when a local metadata change is detected, a different job should be scheduled to tell the server about it.

**Comment by ogoffart** [comment]
I think that is already what  `should_update_etag`  does.
Maybe this should be renamed `should_update_metadata`  because it is used for the etag, the permisisons and the file id.

**Comment by guruz** [comment]
@ckamm You mentioned we won't do this after all?

**Comment by ckamm** [comment]
Yes, the remote -> local update is instead handled during reconciliation, as before. I currently don't see where we would want to trigger a remote update due to a local file permission change. So I think this is solved as part of #3244
