### ISSUE TITLE
Folder scheduling needs to be multiaccount aware

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#3379]
Currently if *one* account disconnects, that will prevent *any* folders from being scheduled. Including the ones that belong to an account that's still connected.

Similarly, if an account reconnects, every folder from every account will be scheduled again. Even folders that belong to disconnected accounts.

This needs to be reworked. The logic for which folders to schedule should probably move from Application into FolderMan.

**Comment by ckamm** [comment]
Test notes: Create multiple accounts. Have one of them disconnected (switch to maintenance mode, switch off, ...). The other one should continue to sync changes.

**Comment by Dianafg76** [comment]
@ckamm If you sign out with one account, the other is not working. You need to log in sync account (https://github.com/owncloud/client/issues/3400)

**Comment by ckamm** [comment]
@Dianafg76 How do you sign out of one account? As far as I know you can only sign out of everything?

**Comment by Dianafg76** [comment]
@ckamm, I just try this bug and is working fine. Many thanks, ;-)
Desktop v ownCloud-2.0.0.5252-nightly20150707-setup.exe
