### ISSUE TITLE
[Desktop] Tray: Make "Open [...] in browser" URL themeable

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#3383]
User asked for ECP Shibboleth a long time ago (see https://github.com/owncloud/enterprise/issues/417), but we didn't implemented it yet. As a workaround, he would like to use LDAP authentication for clients and Shibboleth authentication only for the web login.

If a user click "Open ownCloud in browser" from menu/task bar, his browser opens the LDAP login. The user asked to override the "ServerUrl" to point the user to the Shibboleth login page instead.

@dragotin Could we make "Open ownCloud in browser" URL "themeable" in the client?

00002291

**Comment by dragotin** [comment]
I think this ties into https://github.com/owncloud/enterprise/issues/481 right? If we have the alternative URL for WebDAV, this problem will be fixed automatically because the link uses the one using shib.

**Comment by dragotin** [comment]
Moving this back to 2.0.2 milestone, as we need to test that. The part with the changed url is also already in 2.0.2

**Comment by dragotin** [comment]
@michaelstingl can you double check if this is fixed with the alternative webdav route feature?

**Comment by michaelstingl** [comment]
@dragotin I tested the full process and it worked great. Now, waiting for feedback from users…

**Comment by dragotin** [comment]
cool!

**Comment by michaelstingl** [comment]
@dragotin Sorry, I was confused with the issues. I tested only for https://github.com/owncloud/client/pull/3802 . Is the "Open [...] in browser" URL already themeable too? Which parameter do I have to use?

**Comment by dragotin** [comment]
args, I was hoping that it's fixed along, since you mentioned something like that yesterday. No, **this** one is not yet done.

**Comment by michaelstingl** [comment]
@dragotin I will ask my user if they want to solve this with the new shib stuff.

**Comment by Dianafg76** [comment]
@dragotin Hello, what it is the step to reproduce this?, I don't have  the server with this caracteristics
Thanks

**Comment by dragotin** [comment]
@Dianafg76 you do not need to test this at the moment, that was more for @michaelstingl

**Comment by Dianafg76** [comment]
@dragotin OK, Thanks

**Comment by ckamm** [comment]
@michaelstingl Can you give us a simplified example of what the desired theming is? Instead of opening `https://owncloud.example.com` you want to open `https//owncloud.example.com/shib/login`?

Would adding `QString Theme::webUrl(const QString& url)` already allow you to do what you want?

**Comment by michaelstingl** [comment]
@ckamm Put this on hold for the moment. I will discuss this with the user.

**Comment by michaelstingl** [comment]
@ckamm I discussed this with the user. We will first try if https://github.com/owncloud/client/pull/3802 could fix this too.
