### ISSUE TITLE
When install the new version 2.0 I can't see the part of "Storage usage"

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3393]
### Steps to reproduce
1. Install the new version Desktop client (v2.0)
2. Go to settings

### Expected behaviour
It should look like in other versions
![screen shot 2015-07-02 at 09 12 37](https://cloud.githubusercontent.com/assets/12032058/8471764/b7c9c0b6-209b-11e5-90b2-429ac8bd822a.png)

### Actual behaviour
I can't see the part of "Storage usage" this picture is the v2.0
![screen shot 2015-07-02 at 09 12 29](https://cloud.githubusercontent.com/assets/12032058/8471727/80098d64-209b-11e5-8239-86c3405c7dfe.png)

### Server configuration
Desktop client v 2.0.0 (build 5232)
Sever v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
@ckamm I close this issue. I tested with v ownCloud-2.0.0.5234-nightly20150703-setup.exe and I can see perfect
Thanks :-)

**Comment by stonerl** [comment]
With the Mac Client 2.0.0-nightly20150717 (build 2542) I still have issues with the storage usage chart. The font is cut on the upper and lower part.

![screen shot 2015-07-17 at 09 06 21](https://cloud.githubusercontent.com/assets/2091312/8742252/addbc9a4-2c63-11e5-9ed3-8d17158c9676.png)
