### ISSUE TITLE
When I install the new version 2.0 I can't see the "Certificate information"

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3394]
### Steps to reproduce
1. Install the new version 2.0
2. Go to settings
3. In the Account to Sync
4. Click on the Padlok for see the "Certificate information"

### Expected behaviour
You should see information about the Certificate (as before)

![screen shot 2015-07-02 at 09 58 16](https://cloud.githubusercontent.com/assets/12032058/8472414/69d57458-20a1-11e5-8a1e-4b7badd3eec4.png)

### Actual behaviour
Nothing happens

![screen shot 2015-07-02 at 09 57 54](https://cloud.githubusercontent.com/assets/12032058/8472372/f65f692a-20a0-11e5-8cad-6dc8f16afaaf.png)

### Server configuration
Desktop client v 2.0.0 (build 5232)
Sever v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by ckamm** [comment]
@Dianafg76 I can't reproduce this with master, the cert info shows up fine in my test case.

**Comment by Dianafg76** [comment]
@ckamm I tested in WIN

**Comment by ckamm** [comment]
@Dianafg76 I can indeed reproduce it on windows.

**Comment by Dianafg76** [comment]
@ckamm I close this issue. I tested with v ownCloud-2.0.0.5234-nightly20150703-setup.exe and I can see perfect
Thanks :-)
