### ISSUE TITLE
 New option for MODIFY the password for the account

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3395]
When installing the new version 2.0, you can delete the account. But you don't have the option MODIFY the password for the account, but can only change the password, because if you change the URL and the username is the same as a new account. 
In my opinion we need new option for Modify the password for the account

**Comment by ogoffart** [comment]
@jancborchardt 

The idea is that when the password is changed on the server, the client will prompt a dialog that asks for the password.

But if you want to change the URL or the username, you indeed need to create a new account.
This is already how this works in 1.8 and before. If you were to click on the "modify account" button, it would open the wizard that would re-create a new account and remove the previous one.

**Comment by jancborchardt** [comment]
Yeah – I mean what’s the use-case here? The case when the password was changed on the server is planned to be solved via a dialog as @ogoffart says.

Or do we want to make it possible to change the password via the client, meaning the password will then be changed on the server as well? I’m not really sure this is a good idea.

**Comment by dragotin** [comment]
We had complaints before that people wanted to have the functionality to set the password.

Usecase: You get forced to change passwd on the server. Its *8uzvVCx/_)lxzu* now and you're sure you never will remember that again..... better quickly change it in the client **now**.

**Comment by danimo** [comment]
The real fix is to make sure the server invalidates the session of course. Because than the popup would be instant. But yeah, that's not gonna happen soon...

**Comment by dragotin** [comment]
Please, let's add a "change password" button, that opens the dialog!

**Comment by ogoffart** [comment]
@dragotin You can log out and then log it.

**Comment by jancborchardt** [comment]
Well, I fear that people will think a »Change password« button is for changing the password on the server. Which it doesn’t do of course.

**Comment by moscicki** [comment]
Just my 2c: changing server-side password via the client is totally unfeasible in ldap-based environments (the password is not managed by owncloud server). Client UI should make sure there is no ambiguity for the user about that.

**Comment by ogoffart** [comment]
So should we close this issue then? or is there something to do?

**Comment by dragotin** [comment]
Well, before 2.0, people were complaining that they can not adjust the password and we pointed them to the modify-account functionality. Now that is gone, people can not adjust the password at all any more (except unintuitive workarounds). How will that be received?

If @jancborchardt insists we could close it, I still think we will need a "change password" button.

**Comment by ogoffart** [comment]
and what would a "change password" button would do?   Just a shortcut to log-out/ log-in ?

**Comment by dragotin** [comment]
just open the window to let the user enter a new password, store it to the keychain and use from now on.

**Comment by jancborchardt** [comment]
Well, just a guess at what will happen:
1. people click »change password« to change their password
2. enter new password, expecting it means it gets changed on the server
3. connection drops because the password isn’t the same as on the server

**Comment by ckamm** [comment]
I was wondering about the Sign in/sign out actions. You can currently only trigger them from the tray icon. But why do we have them in the first place? In a quick chat @ogoffart and me came up with:

1. Change the stored password through logout/login.
2. For security: Sign out so the password needs to be typed in before syncing can continue after reboot.
3. Temporarily pause syncs for all folders in the account.

The second seems to explicitly demand sign out/sign in, while 1. and 3. could be solved in other ways. We could improve support of 2. by having a never-save-password option.

Should I add a button for sign out/sign in in the account settings dialog, next to the "Delete" button? @jancborchardt @dragotin

**Comment by dragotin** [comment]
@jancborchardt so what is your decision? Have no change password possibility? What about @ckamms proposal above?

**Comment by ogoffart** [comment]
Closing old issue.
