### ISSUE TITLE
More information near to the sync folder: user and serverurl

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3396]
### Steps to reproduce
1. Install the new client version 2.0 and log as user 1
2. Go to Settings
3. Go to General
4. Click in "Add and account"
5. Create another account, user 2
6. Right click to the Oc Icon

### Expected behaviour
the user's name appears on the row, at the same level as the folder information, something such as:
'Open folder 'ownCloud', user@serverurl'

### Actual behaviour
I can see two sync folders "OwnCloud" and "ownCloud2", one per logged user
![screen shot 2015-07-02 at 11 28 54](https://cloud.githubusercontent.com/assets/12032058/8474030/daf0b722-20ad-11e5-9341-65510f95211c.png)
However, I do not know which user owns each folder

### Server configuration
Desktop client v 2.0.0 (build 5232)
Sever v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
If you create another account with the same name but in different serverurl. I do not know which user owns each folder

**Comment by ogoffart** [comment]
New builds should put the "open folder" items in a sub meny per accounts

**Comment by Dianafg76** [comment]
@ogoffart I just try this bug. Many thanks, ;-)
Desktop v ownCloud-2.0.0.5252-nightly20150707-setup.exe
