### ISSUE TITLE
Overlay icons stay green when account is disconnected

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3398]
### Steps to reproduce
1. Create two diferents account, for example 1 and 2
2. Closed one, for example 1

### Expected behaviour
should have the same icon 

### Actual behaviour
The icon for the oC is 
![screen shot 2015-07-02 at 14 34 21](https://cloud.githubusercontent.com/assets/12032058/8477066/8499ad10-20c7-11e5-89ed-9b69eb0a2dd0.png)
But if you go to see the folders have a diferent icon. 
![screen shot 2015-07-02 at 14 24 37](https://cloud.githubusercontent.com/assets/12032058/8477080/a93646f6-20c7-11e5-9ae3-4bd00be181db.png)
And if you go to the Settings, you have a diferent icon.
![screen shot 2015-07-02 at 14 42 18](https://cloud.githubusercontent.com/assets/12032058/8477202/a51012f4-20c8-11e5-8413-c5d09f5bc07b.png)

### Server configuration
Desktop client v 2.0.0 (build 5232)
Sever v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}
In WIN

**Comment by ckamm** [comment]
The folder icons should adjust if the account is disconnected as of ae69ff032b4d7a9faba5ba63e1eea66820dd23e7. I'll look at the socketapi status...

**Comment by ckamm** [comment]
@dragotin @jancborchardt What folder icon should we show when an account is disconnected? We currently show the green 'OK' icon, but that's confusing. I think arguments could be made for warning, error or no icon at all. What are your opinions?

**Comment by jancborchardt** [comment]
As long as the file was not modified locally, the icon should stay green. Otherwise this will result in confusion and panic of file loss on every small connection issue. As soon as it was modified locally, show the blue sync arrows, but only on that file/folder of course.

**Comment by ckamm** [comment]
Hm, currently we don't track the local 'needs sync' status when the account isn't connected. We could start doing that. I'll open another ticket for that suggested change.
