### ISSUE TITLE
In v2.0, When you click in Sign out, You do not know what has closed

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3399]
### Steps to reproduce
1. Install the v 2.0 with two diferents accounts, call Oc, and Oc1 for example
2. sync 
3. Right click to the Oc Icon
4. Press "Sign out"

### Expected behaviour
you need to know which account is to be closed

### Actual behaviour
When you click in Sign out, You do not know what has shut

### Server configuration
Desktop client v 2.0.0 (build 5232)
Sever v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}
In WIN

**Comment by ckamm** [comment]
Currently 'Sign out' signs you of of all accounts. I'm not sure that's intended behavior. Maybe the tray menu could have a submenu per account? Then that could have the "Sign in"/"Sign out" actions as well as the "Open in browser"/"Open folder" actions.

**Comment by ckamm** [comment]
@Dianafg76 As of 1a58e66 you can sign out of individual accounts as well as out of every account.

**Comment by Dianafg76** [comment]
@ckamm, I just try this bug. Many thanks, ;-)
