### ISSUE TITLE
In 2.0 Multiaccount: You only have to enter the password for the closed account

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3400]
### Steps to reproduce
1. Install the v 2.0 with two diferents accounts, call Oc, and Oc1 for example
2. Sync
3. Right click to the Oc Icon
4. Press "Sign out" (but you do not know which is closed)
5. Right click to the Oc Icon
6. Press "Sign in"

### Expected behaviour
You only have to enter the password for the closed account

### Actual behaviour
 you need to enter two passwords for the two accounts. But one is closed and the other is working

### Server configuration
**Operating system**:

**Web server:**

**Comment by ckamm** [comment]
@Dianafg76 I'm pretty sure 'sign out' signed you out of both accounts. See #3399

**Comment by ckamm** [comment]
One related issue here is that the password dialog only gives you the user name and doesn't indicate the full account. If you have the same user name on two different servers, you don't know which password is being asked.

**Comment by Dianafg76** [comment]
@ckamm Thanks :-)

**Comment by ckamm** [comment]
The password dialog text was updated by 7053f76d1e15ade6bb194331542a59ee4e7c48a4. The signin/signout behavior will be dealt with in #3399

**Comment by Dianafg76** [comment]
@ckamm, I just try this bug. Many thanks, ;-)
