### ISSUE TITLE
In v2.0 with MAC I can't very see well when you click in Settings option and I can't work with this option

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3401]
### Steps to reproduce
1. Install the New version 2.0 for Mac
2. Go to settings

### Expected behaviour
You should be able to see all options

### Actual behaviour
You can't see very well, and I can't work with this option
![screen shot 2015-07-03 at 08 18 50](https://cloud.githubusercontent.com/assets/12032058/8493612/fdf10a74-215c-11e5-8f36-8e4a889755ca.png)

### Server configuration
Desktop v ownCloud-2.0.0.2502-nightly20150703.pkg in MAC
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by guruz** [comment]
This is a known issue..
Please don't test Mac yet :)

https://github.com/owncloud/client/issues/3386

**Comment by Dianafg76** [comment]
@guruz OK, thanks

**Comment by Dianafg76** [comment]
I try with Desktop v ownCloud-2.0.0.2532-nightly20150714.pkg, and it's the same

**Comment by Dianafg76** [comment]
if a new installation is the same , but an update is working well

**Comment by guruz** [comment]
@Dianafg76 if you restart the client in the new installation it also displays fine, right?
the problem is when you add an account?

**Comment by Dianafg76** [comment]
@guruz Yes

**Comment by Dianafg76** [comment]
@guruz I tested this issue, and working fine
Many thanks, :-)
Desktop v ownCloud-2.0.0.2542-nightly20150717.pkg  
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}
