### ISSUE TITLE
[Win7] No more tray/desktop notifications in Windows Nightly 1.8.4 Build 5227

### ISSUE THREAD

**Issue by Siedlerchr** [owncloud/client#3402]
I am using the above Windows nightly (with the connection closed fix) and I noticed that I don't get any longer notifications in the tray area.
Normally the cilent showed notifications when I synced files (upload/download).

**Comment by dragotin** [comment]
hmm, that is something special with your installation I fear. We did not hear that from other users. Please excuse that I close it. Let us know if you have further findings.
