### ISSUE TITLE
Improve progress reporting UI

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#3403]
As discussed on IRC among @jancborchardt @guruz @ogoffart and me:
- Show less informaion, in particularly don't show text to the right **and** below the progress bar.
- Move information about all currently running jobs to the tooltip.
- Possibly reduce the thickness and width of the progress bar.
- Have a clear idea of how to display sync errors.

**Comment by jancborchardt** [comment]
Good call on directly opening an issue! We should see how to best do that as soon as we have the new layout in, which @ogoffart and I worked on.

**Comment by guruz** [comment]
@ckamm You mentioned something about not being able to change displayed tooltips. Maybe this helps: https://stackoverflow.com/a/13720606/2941

**Comment by guruz** [comment]
I've pushed a display change for master/2.0 ... Now all transfers will be shown with complete bandwidth (before only part was shown https://github.com/owncloud/client/issues/3095#issuecomment-128293269 thanks @ogoffart )

**Comment by ckamm** [comment]
Here's a current snapshot:
![progress](https://cloud.githubusercontent.com/assets/833306/9404547/e860ebec-47f0-11e5-89fa-2f6bab7e0738.png)

**Comment by jancborchardt** [comment]
I’d change the layout additionally to the following, cut it down to 3 lines:

> Syncing with local folder **ownCloud**
> (thin progress bar, like the storage space bar)
> 9:30 minutes left, X MB of X MB, file 1 of X

* cut the alias name
* adjust »syncing with local folder« sentence and put in one line
* shorten time display, fix singular/plural display as well
* no decimal places on the file sizes, except GB
* move detail info (the bottom line) like currently syncing file and exact sync speed to the tooltip (»sync is running« is not really a useful tooltip anyway ;)

Ok @ckamm? :)

**Comment by guruz** [comment]
I believe this is fixed with the recent changes done..

**Comment by jancborchardt** [comment]
@ckamm is it, according to my comment above?

**Comment by ckamm** [comment]
@jancborchardt No, a bunch of changes are left.

**Comment by jancborchardt** [comment]
@ckamm let me know if you need more review, and if there’s any screenshots please show them. :)

**Comment by dragotin** [comment]
@ckamm please do not strip the "syncing selected files" versus "syncing all files" as that is an important destinction. Also, I am very much against cutting the alias. If there are more than one sync connections the alias comes in very handy.

@jancborchardt hmm, I am not so happy about this review thing. We should really try to get stuff right in the first attempt, instead of reviewing afterwards and starting all over again. That had caused trouble in the past. Can we try that?

**Comment by phil-davis** [comment]
Here is a sample (happens to be Version 2.0.2-nightly20151004 (build 5510)) of multiple folder sync connections that sync to/from different folder pairs on the server and client. Those do not use the sentence "Syncing selected files in your account with...".
1) Maybe there is something to be made more common here? Anyway, this current difference needs to be taken into consideration when making more design decisions.
![multi-sync](https://cloud.githubusercontent.com/assets/1535615/10422692/a50ded48-70dd-11e5-8618-ec53c051739a.png)

2) If the "Syncing selected files" text is to be retained then I think it would be nice to say "Syncing all files" when that is actually the case (when there are not sub-folders unselected), and say "Syncing selected files" when the user has any sub-folder unselected.

**Comment by jancborchardt** [comment]
> If there are more than one sync connections the alias comes in very handy.

@dragotin as said before, the local folder name should just be used as the display name. From @phil-davis screenshot above it becomes clear that the name is just duplicated 3 times (alias, local path, remote path).

**Comment by phil-davis** [comment]
On the 2nd folder sync connection in the screen shot I did choose a completely different folder name on the client. And in the others the local client side path is inside a different folder on D:\ - so the local client-side path seems reasonable to show - it is often different enough that I find it handy to be able to see where in the heck I put it :)
Agreed - the alias duplicates data already in Remote Path.

**Comment by ckamm** [comment]
The sync folder default info is:
```
<b><remote path> without starting / if that's not empty else appNameUI<b>
"Remote path: <remote path>" if it's not / else "Syncing selected files in your account with"
<local path> with the homedir stripped
```

I think the local and remote paths should be displayed for a sync folder, that's the essence of the sync connection. The duplication of the remote path should be removed. "Syncing selected files in your account with" is currently fluff (we never show "Syncing all files"). I expect that the remote path will often be shorter than the local path.

Suggestion: remove the middle line. Keep the rest.

The progress information expands below that, and we could follow @jancborchardt's suggestion for it:
```
thin progress bar
10 minutes left, 13 MB of 234 MB, file 12 of 102
```
Information on running jobs goes to the tooltip.

@dragotin @phil-davis @jancborchardt

**Comment by ckamm** [comment]
I've made some tentative changes in this direction. @jancborchardt please review:
![progress2-1](https://cloud.githubusercontent.com/assets/833306/12478772/307575c4-c037-11e5-98ba-c96741f9024f.png)
![progress2-2](https://cloud.githubusercontent.com/assets/833306/12478775/323ff6d6-c037-11e5-8bda-dbd60bd77c1e.png)

**Comment by jancborchardt** [comment]
@ckamm looks much better already! :) Just a tiny wording change, I would say »folder« instead of »directory« since we mostly use »folder« everywhere as it’s simpler language.
