### ISSUE TITLE
Some image dimensions cause the sync status icons to not show

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#3407]
Observe the top right and bottom left image (both panoramas, one mega-wide):
![capture du 2015-07-04 01-16-22](https://cloud.githubusercontent.com/assets/925062/8505566/63611290-21ea-11e5-8bea-fb09497fd50f.png)

A sync status icon is worryingly absent. The files _are_ indeed synced, however it seems they are not (and I would have no idea why).

Happens on Ubuntu/Gnome with Nautilus. Both list view and grid view are affected.

**Comment by dragotin** [comment]
Please report that upstream. Our code just says: Please show this'n that icon. The actual drawing and stuff is done by the gnome nautilus integration. Thx.
