### ISSUE TITLE
Debian packages outdated, client 1.8.3 missing

### ISSUE THREAD

**Issue by schiesbn** [owncloud/client#3410]
I just noticed that 1.8.3 is missing in the Debian repository http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/ Ubuntu and othere repositories seems to be up-to-date

**Comment by RealRancor** [comment]
Seems the builds on Debian are failing:

https://build.opensuse.org/package/show/isv:ownCloud:desktop/owncloud-client

**Comment by jnweiger** [comment]
Debian introduced a new version of lintian, that needs some love in every package now...
Fixed in 1.8.3-1 rebuild.

**Comment by schiesbn** [comment]
Thanks! apt-get just pulled the 1.8.3 update :smile:  :+1:
