### ISSUE TITLE
Explorer Integration on Windows Terminal Server only for one user?

### ISSUE THREAD

**Issue by it64-markus** [owncloud/client#3411]
I have a Windows Server 2008 R2 as terminal server with about 20 Users. Some of them use the owncloud client (currently 1.8.3.5213). During installation process i double checked, that the Windows Explorer integration was activated.

But only the first user who starts the owncloud client gets the Explorer integration and can share files with a rightclick on a synced file or folder directly in the Windows Explorer. All other users on the same server don't have the integration.

To make things a bit clear assume we have user A, B and C. All three are using the owncloud client and it is configured to start at login. Let's say currently no users are logged in. User A logs in, the owncloud client gets started and she can use the Explorer integration right away. Then user B logs in, the owncloud client is also started, we see it in the tray. But she can't use the Explorer integration. The same is true for user C, when she logs in after A and/or B.

If User B and A close the owncloud client and B starts it manually after A closed it, then User B suddenly can use the Explorer integration. When A restarts the client after B, then she doesn't have the integration activated.

The users without the integration activated even don't see the green little additions to the folder- or file-icons in the explorer, showing whether the file is in sync with the server or not.

I already de- and re-installed the client numerous times so far.

Is there someone out there with the same issue? Any help possible? Is this targeted for a future release of the client?

**Comment by guruz** [comment]
Have you tried raising this via the enterprise/edu support (if you have a license)?
https://owncloud.org/support/

**Comment by it64-markus** [comment]
No, i have no license for owncloud. I wonder that i am obviously the only one that hits this issue.

**Comment by danimo** [comment]
Please try  https://download.owncloud.com/desktop/daily/ownCloud-2.2.0.6006-nightly20160420-setup-fix-3411.exe

**Comment by guruz** [comment]
@it64-markus Hi! Were you able to test the above .exe?

**Comment by it64-markus** [comment]
Sorry, i only have the production terminalserver of a client. I am sure you understand i can't install a nightly owncloud client there. Unfortunately i have no test environment for this currently.

**Comment by Bottswana** [comment]
I have a testing terminal server environment at work that I may be able to
try and reproduce this issue with if it is still open in a few days.
On 25 Apr 2016 10:07 p.m., "Markus Mann" <notifications@github.com> wrote:

Sorry, i only have the production terminalserver of a client. I am sure you
understand i can't install a nightly owncloud client there. Unfortunately i
have no test environment for this currently.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/owncloud/client/issues/3411#issuecomment-214522161>

**Comment by guruz** [comment]
@it64-markus Would you be willing to install a testpilot version? It's basically a rebranded client that uses a different config directory so it does not interfere with anything else.
(We'd just need to build one with the branch with @danimo 's fixes..)

**Comment by it64-markus** [comment]
Hi @Bottswana that would be great, if you could test this in your testing environment, thanks.

**Comment by mcastroSG** [comment]
Hi hi:

**Steps Executed**

1.- Install ownCloud Desktop Client as user1
2.- Create user2 as SO user
3.- Install ownCloud Desktop Client as user2
4.- Start Desktop Client at both sessions

**Results**

Both Shared sync folder shows overlay icons.

Client OS: Windows 8.1
Client Version:Version 2.2.0rc1 (build 6069)

**Comment by it64-markus** [comment]
Err, sorry, but that has nothing to do with my initial problem. The problem was: on a Windows Terminal Server only the first user who starts the owncloud client gets the Explorer integration (right click on a file in the Explorer to share it for example).

In my opinion it is still unclear whether this issue is still open or not.

**Comment by mcastroSG** [comment]
@it64-markus  to test this issue some extra info from @danimo  was needed to create a possible scenario and the closest approach to the situation you have defined is using a W8.1 VM using two different users logged at the same time and using ownCloud client at the same time. So, what we try to do is to check that in case of a second user start ownCloud desktop client he/she gonna have available Windows Explorer integration 😅 . 

My mistake not to include that "Share with ownCloud" menu option appears too , so full Windows Explorer integration seems to be available.

Anyway it will be great if you could install owncloud testpilot 2.2.0RC1 to make a test or @Bottswana to be completely sure.

[testpilotcloud 2.2.0RC1](https://download.owncloud.com/desktop/testing/testpilotcloud-2.2.0.6070rc1-setup.exe)
