### ISSUE TITLE
[windows] The tray icon tooltip text gets truncated

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3412]
### Steps to reproduce
1. Creates two accounts, call them user1 and user2
2. Sync
3. Right icon Oc
4. Click "Sing out everywhere"

### Expected behaviour
You should see the two accounts in the same. In this case, you can see "Account ........: Signed out"

### Actual behaviour
Go to Icon Oc , the information shown is incorrect , since in an account that is " Signed out " , but the other has not seen anything.

![screen shot 2015-07-07 at 10 05 05](https://cloud.githubusercontent.com/assets/12032058/8541916/e3fadcd4-2491-11e5-9201-7ea9c0d39936.png)

### Server configuration
Desktop v ownCloud-2.0.0.5252-nightly20150707-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by ogoffart** [comment]
This should have been fixed with the same fix as for #3413

**Comment by Dianafg76** [comment]
@ogoffart I tested this issue, and happend the same thing
Desktop v ownCloud-2.0.0.5255-nightly20150709-setup.exe

**Comment by ckamm** [comment]
@Dianafg76 I could not reproduce the problem. Could you re-test with a current build?

**Comment by Dianafg76** [comment]
@ckamm I tested this issue, and happend the same thing
Desktop v ownCloud-2.0.0.5273-nightly20150715-setup.exe

**Comment by ckamm** [comment]
@Dianafg76 Odd! This is on windows, right?

**Comment by ckamm** [comment]
The tooltip in your screenshot does contain an entry for both accounts, indicating that `isConnected()` was false for both of them. Looking at the code, I don't see how the half-finished line about the second account could be produced.

**Comment by Dianafg76** [comment]
@ckamm Yes , it is in Windows. And if I reopen the description does not go away

**Comment by ckamm** [comment]
@Dianafg76 I tried it on Windows: I think we're hitting a size limit for the tooltip! For me the last line looks like this: "Account foo@foo: Si". I'll check whether this is a per-line limit or an overall limit and adjust accordingly.

**Comment by ckamm** [comment]
Looks like there's a 128 character limit.

**Comment by Dianafg76** [comment]
@ckamm Ok, thanks

**Comment by ckamm** [comment]
@Dianafg76 In the next build of 2.0, the tooltip sizes will be reduced on windows.

**Comment by Dianafg76** [comment]
I tested this issue and it is working OK
Desktop vownCloud-2.0.0.5384-nightly20150811-setup.exe 
Many thanks
Closed
