### ISSUE TITLE
[Multiaccount] The botton "Sign in everywhere" it is not working very well

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3413]
### Steps to reproduce
1. You need two accounts (user1, user2)
2. Sync
3. Right click to the Icon Oc
4. Go to the account user1@.....
5. Close session
6. Right click to the Icon Oc
7. Click "Sign in everywhere"
8. Right click to the Icon Oc
9. Click "Sign in everywhere"

### Expected behaviour
7. The connection should not be closed to the user2.
9. It should synchronize the two accounts

### Actual behaviour
7. Asks password for user1 and is sync. But the connection is closed to the user2
9. Nothing happens

### Server configuration
Desktop v ownCloud-2.0.0.5252-nightly20150707-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by ogoffart** [comment]
I could reproduce and fix it.

**Comment by Dianafg76** [comment]
@ogoffart I tested this issue, and is working fine.
Many thanks, :-)
Desktop v ownCloud-2.0.0.5255-nightly20150709-setup.exe
