### ISSUE TITLE
Add HIDPI (high screen resolution, 4k +) support (at least in windows client)

### ISSUE THREAD

**Issue by McNetic** [owncloud/client#3414]
On Windows (in my case 8.1, older versions will probably behave worse), the client does not really handle very high screen resolutions (I have a 4K display, 3840x2160 px). It starts with the configuration wizard, whose dialogs are messed up. Sorry, did not do screenshots, but it is similar to the account configuration dialog that is attached. I think all dialogs suffer that problem. Also, the main windows is not set up very good, I think the icon row at the top is too small, I'm not sure about the overall dialog size (maybe I already resized this, but as in the second screenshot, the list of remote paths is imho to small), and the default columns widths on the activity tab are useless (see screenshot).
![editaccount](https://cloud.githubusercontent.com/assets/1324685/8542902/5e13f68e-2499-11e5-86d1-b99048227e43.png)
![columnwidths](https://cloud.githubusercontent.com/assets/1324685/8542903/5e1a5ede-2499-11e5-9a02-38b382460e5e.png)

PS: I hope this is not a duplicate; I tried various search terms but not find something suitable.

**Comment by guruz** [comment]
@danimo @jturcotte @dragotin Something related to "older" Qt version I'm guessing?

**Comment by jturcotte** [comment]
Qt 5.4 should handle the layout correctly according to http://doc.qt.io/qt-5/highdpi.html#operating-system-support

But I'm sure there might still be issues.

**Comment by guruz** [comment]
(btw, http://lists.qt-project.org/pipermail/development/2015-July/022339.html )

**Comment by dragotin** [comment]
If this causes bigger changes, please move to next milestone.

**Comment by guruz** [comment]
Possible related https://github.com/owncloud/client/issues/2587 ?

**Comment by McNetic** [comment]
Absolutely. This issue is more general, as all ui is affected.

**Comment by guruz** [comment]
@danimo With the commits you just pushed, is this fixed?
https://github.com/owncloud/client/commit/16030a61eb055733c5da1cf6c1bad4caef10a7f8

**Comment by danimo** [comment]
@guruz No!

1. We are not on 5.6 for Windows yet
2. Neither Windows or Mac OS styles are yet adopted to look 'correct'.

Please keep this issue open.

**Comment by jturcotte** [comment]
@danimo Is there anything we need to do, beside waiting for 5.6.0 or 5.6.1 and hope they got it working?

**Comment by danimo** [comment]
@jturcotte Try how bad the windows/mac styles look on HiDPI, and upgrade the Windows packages to 5.6.

**Comment by jturcotte** [comment]
Seems like we could at least use Fusion on Windows in that case (or always) instead of showing broken scaling: http://lists.qt-project.org/pipermail/development/2016-January/024234.html

**Comment by jturcotte** [comment]
OK so seems like this already works pretty OK with Qt 5.5, but unlike OS X, it's opt-in:

- In Qt 5.5 you have to set QT_DEVICE_PIXEL_RATIO=1
- In Qt >= 5.6 you have to set QT_AUTO_SCREEN_SCALE_FACTOR=1 (the code suggests that setting Qt::AA_EnableHighDpiScaling in the code also works, but this isn't documented and I haven't tried it)

In both cases, the style gets pixelated in some areas (like radio buttons) and the only way to make it right is to use the fusion style. So we lose the native-looking buttons, but high-contrast, etc. still seems to work . I can barely see the difference with the Windows style, maybe somebody would notice but I think it's still better than pixelated UI elements.

I'll try to see if I can set those flags/env var in the startup code.

**Comment by guruz** [comment]
@McNetic Would you test http://download.owncloud.com/desktop/daily/ownCloud-2.1.1.5764-nightly20160111-setup.exe ?

**Comment by michaelstingl** [comment]
@guruz Looks great on Win 8.1. Thanks!
