### ISSUE TITLE
Windows 8.1 Pro x64: "Launch on System Startup" not working

### ISSUE THREAD

**Issue by dergilb99** [owncloud/client#3417]
### Expected behaviour
Checking "Launch on System Startup" should launch OC client on system startup.

### Actual behaviour
Checking "Launch on System Startup" does not launch anything. I manually have to create a link in Windows' Startup folder.

### Steps to reproduce
For me it's rebooting.

### Server configuration
n/a

### Client configuration
Client version: 1.8.2

Operating system:
Windows 8.1 Pro x64

OS language:
English (US). 

Installation path of client:
C:\Program Files (x86)\ownCloud

### Logs

Well, it's not starting, so no logs...

**Comment by guruz** [comment]
@dergilb99  Could you please try 1.8.3?

@Dianafg76 Could you try to reproduce this?

**Comment by dergilb99** [comment]
@guruz: 1.8.2 says it's up-to-date. I will update manually and comment here again.

**Comment by dergilb99** [comment]
ARG. For what reason ever, OC client was disabled in Task Manager/Startup (that I do not use!). Sorry for wasting your time!
