### ISSUE TITLE
v2.0.0 Folder size not correctly displayed

### ISSUE THREAD

**Issue by calis2002** [owncloud/client#3420]
### Expected behaviour
On the account page of the desktop client gui, when you expand the account folder and you see the list of subfolders, you see the current size of each folder behind the folder name.

### Actual behaviour
Some folders show weird folder sizes e.g "-1,6e+09 B".

### Server configuration
ownCloud version: 8.1

### Client configuration
Client version: 2.0.0 build 5253

Operating system: Windows 8.1 Pro

### Logs
![2015_07_08-10_19_38](https://cloud.githubusercontent.com/assets/4539953/8566358/d536c754-255d-11e5-91ff-1f7bc3c71b4f.png)

**Comment by ogoffart** [comment]
Do you know the actual size of the folder?

**Comment by Dianafg76** [comment]
@ogoffart I trie with Desktop v ownCloud-2.0.0.5253-nightly20150708-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}, and is working fine

![screen shot 2015-07-08 at 11 08 43](https://cloud.githubusercontent.com/assets/12032058/8567190/9d9e9ff0-2563-11e5-8700-0812486fe3e7.png)

**Comment by ogoffart** [comment]
I suppose it depends on what the server returns.  Maybe the server returns negative value.  Or there is an overflow problem somewhere in the client.

**Comment by Dianafg76** [comment]
It is a Windows Server 2008 Enterprise

**Comment by ogoffart** [comment]
But it might depends on the sizes.  For example if there are folders that contains more than 4GiB or something.

Notice that the blider folder is 783 MiB, but it contains a folder that is 1GiB,  how can that be possible?

There is probably a bug there. Maybe an overflow in the client

**Comment by calis2002** [comment]
"HTC" is 2,55 GB
"Lea" is 2,28 GB
"Nexus" is 2,78 GB

My Server is a Debian 8.1 System.

**Comment by ogoffart** [comment]
The fix will be in the next build.  Thanks for the bug report.

**Comment by calis2002** [comment]
It's working. Thanks ;)
![2015_07_09-08_10_03](https://cloud.githubusercontent.com/assets/4539953/8589055/297bf4ce-2612-11e5-9ed6-eded1ba3c83c.png)

**Comment by Dianafg76** [comment]
@ogoffart I tested this issue, and is working fine.
Many thanks, :-)
Desktop v ownCloud-2.0.0.5255-nightly20150709-setup.exe
