### ISSUE TITLE
Cannot configure/use Linux client

### ISSUE THREAD

**Issue by jmssil** [owncloud/client#3423]
I get "Error: Wrong credentials." and in the log window:

07-08 16:51:24:263 Connect to url:  "https://my.domain/owncloud" 
07-08 16:51:24:264 Setup-Log:  "Trying to connect to ownCloud at https://my.domain/owncloud..." 
07-08 16:51:24:264 !!! Mirall::ValidateDavAuthJob created for  QUrl( "https://my.domain/owncloud" )  querying "" 
07-08 16:51:24:744 Mirall::ValidateDavAuthJob Error: "Error downloading https://my.domain/owncloud/remote.php/webdav/ - server replied: Forbidden" 

This has worked before.

**Comment by ogoffart** [comment]
What version do you use?  (server/client)
Can you connect with the same password on the web interface?

**Comment by jmssil** [comment]
I don't have access to it here, i'll check later, but it's the latest one
from linux mint (ubuntu).
Yes i can log in from the web interface.

**Comment by jmssil** [comment]
The versions are the following:
owncloud-client 1.5.0+dfsg-4ubuntu1
owncloud-server 8.1.0-1

**Comment by carlaschroder** [comment]
Hi @jmssil, you should use the official ownCloud client builds. Most distro builds are outdated. See https://owncloud.org/install/, section 2.

**Comment by jmssil** [comment]
Thanks. With version 1.8.3 from the openSUSE repositories it worked.

**Comment by carlaschroder** [comment]
@jmssil Good, thanks for letting us know :)

**Comment by guruz** [comment]
@LukasReschke @Dianafg76 I thought the client would display a more proper message like "old version please update". I thought that is sent by the server?

**Comment by Trader515** [comment]
@guruz I think the reason this message wasn't shown is that the client is only able to display this since 1.8.2 (see #3220)

**Comment by guruz** [comment]
@Trader515 thx!
