### ISSUE TITLE
Unclear String "Discovering 'ownCloud'" in account settings

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/client#3431]
It is very unclear what it means when the owncloud client is doing when it says "Discovering 'ownCloud'".
Is it looking through files in the local computer, is it waiting for the server?
![image](https://cloud.githubusercontent.com/assets/639487/8595129/e860ddac-2647-11e5-8d43-79a373cfc7ef.png)
I hope something more clear can be written.

**Comment by guruz** [comment]
@pascalBokBok "ownCloud" is the name of the sync folder you gave it in the UI. It is checking for server side changes in the root of the sync folder. You should not see this message for a long time, if you do there might be something wrong?

**Comment by dragotin** [comment]
Usually it should display the actual folder it is in. This looks like a connectivity issue in your network, or DNS or such. 

Closing this, please add a comment if you want to reopen. Thx.

**Comment by pascalBokBok** [comment]
It's there for about 20-30 seconds - perhaps due to dropbox and google drive external storage.
I would like to reopen since this issue is about a non-explanatory string (not about my network setup).

**Comment by guruz** [comment]
What's your proposal for a better string?

**Comment by pascalBokBok** [comment]
Well - I'm not in the clear about what exactly it is doing at that point but perhaps "Waiting for server" so it is clear that it's not a local bottleneck if it takes a long time.
Perhaps "Waiting for server to index files"

**Comment by dragotin** [comment]
@jancborchardt what do you think?

**Comment by guruz** [comment]
Why not ```Discovering remote "$foldername"``` and ```Discovering local "$foldername"```
(or server<->remote)

**Comment by pascalBokBok** [comment]
The word "Discovering" doesn't make sense to most people.

**Comment by guruz** [comment]
Discovering is a verb universally known :-)
```Waiting for server to index files``` is a lie because the server should already have them indexed :-)

**Comment by jancborchardt** [comment]
`Checking for local changes` and `Checking for server changes`?

**Comment by pascalBokBok** [comment]
@guruz Why would it discover files it has already indexed? (It's the same point - apparently you mean discovering changes). As I said above I have no idea what it is doing at this point - but "Discovering" by itself doesn't tell me much.
@jancborchardt That could definitely work. It should reflect what is actually going on so we don't get a lot of bug reports based on misunderstandings.

**Comment by pascalBokBok** [comment]
The "discovering" session is down to a second now that I removed my dropbox and google drive integration. 
Changing it to "Waiting for server to index files" could be a good replacement for Discovering.

**Comment by jancborchardt** [comment]
»Checking for server changes« is much simpler and easy to understand. We do not need to communicate every tiny technical detail in the interface. :)

**Comment by pascalBokBok** [comment]
Sounds good to me :smile:

**Comment by phil-davis** [comment]
Version 2.1.0-nightly20151024 (build 5579) - "Checking for changes in..." is now displayed.

**Comment by pascalBokBok** [comment]
@phil-davis Is it clear that the check is happening server-side and that essentially we are waiting?

**Comment by phil-davis** [comment]
It just says 
```
Checking for changes in "foldername"
```
The word "server" is not in the message. It is comparing between server and client using whatever file name/mtime/size... criteria it uses. So in a sense it is not particularly checking the "server" or "client" - it is checking both.
