### ISSUE TITLE
Repo issue with Windows (cross-compile) using OpenSUSE 12.2

### ISSUE THREAD

**Issue by ktWaran** [owncloud/client#3433]
There is no repositories such as 
zypper ar http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_12.22/windows:mingw:win32.repo
zypper ar http://download.opensuse.org/repositories/windows:/mingw/openSUSE_12.2/windows:mingw.repo

Therefore I have tried the path as below
zypper ar http://download.opensuse.org/repositories/windows:/mingw:/win32:/compat/openSUSE_12.2/windows:mingw:win32:compat.repo
zypper ar http://download.opensuse.org/repositories/windows:/mingw/openSUSE_Factory/windows:mingw.repo

Could any one help me please whether it will support the cross-compiler package installation in OpenSUSE12.2?

**Comment by danimo** [comment]
OpenSUSE 12.2 is end-of-live. Packages only exist for 13.1, 13.2 and factory at this point, see https://doc.owncloud.org/desktop/1.8/building.html.

**Comment by ktWaran** [comment]
Thanks Danimo!
