### ISSUE TITLE
Error during the installation the cross-compiler packages and the cross-compiled dependencies with OpenSUSE 12.2 VM

### ISSUE THREAD

**Issue by ktWaran** [owncloud/client#3434]
Could anyone  please help me out to figure this error?

This happened while install the packages and cross-compiled dependencies @ OpenSUSE VM.

Failed to mount cd:///?devices=/dev/disk/by-id/ata-VMware_Virtual_IDE_CDROM_Drive_10000000000000000001 on /var/adm/mount/AP_0xmhMEbd: Mounting media failed (mount: no medium found on /dev/sr1)

Thanks

**Comment by danimo** [comment]
We cannot provide support for setting up openSUSE, sorry.

**Comment by ktWaran** [comment]
Thanks! Support available for Ubuntu in that case?

**Comment by danimo** [comment]
Ubuntu doesn't even have cross compile packages for Win32...

**Comment by ktWaran** [comment]
Thanks OpenSUSE is set it up now.  I am trying build the owncloud client. 

Thanks for your quick replies.
