### ISSUE TITLE
[Gnome] [Qt4] Icon vanished after pressing ctrl+alt+del

### ISSUE THREAD

**Issue by gjelsas** [owncloud/client#3435]
On my Arch-Linux Desktop with Gnome pressing the keycombination ctrl + alt + del leads to the disappearance of the Desktop Client Icon. The client is still running and syncing fine it seems.

**Comment by guruz** [comment]
What about other applications?
Sure this is not a Gnome-bug?

**Comment by gjelsas** [comment]
Maybe its a gnome-bug, but it is just this Icon. Also the Desktop is frozen for about a minute. when pushing the keycombination. There are no helpful entries written to the log when starting the application with "owncloud --logfile". The systemlog can be found here http://pastebin.com/xY8qyhY6
Is the desktop client in anyway reakting to keystrokes or keycombinations?

**Comment by guruz** [comment]
Hm, the only idea i'd have is to see if compiling the client with a newer Qt version helps in any way.

**Comment by ogoffart** [comment]
What version of the client and what version of Qt is it using?

**Comment by gjelsas** [comment]
The Client has Version 1.8.3, qt4 is on
4.8.7-2, qt5 is on 5.4.2-1

**Comment by guruz** [comment]
@gjelsas But which one is the client using :-) See settings dialog

**Comment by gjelsas** [comment]
It is qt4  4.8.7

**Comment by guruz** [comment]
I believe ArchLinux has switched to Qt5, maybe that helps

**Comment by ogoffart** [comment]
Closing old issue.  We no longer support Qt4
