### ISSUE TITLE
Error: Wrong credentials after upgrading server to 8.1 (Błąd: złe poświadczenia.)

### ISSUE THREAD

**Issue by briiman** [owncloud/client#3436]
As in topic...
I try to reset configuration of client, it makes nothing.
I use client from Debian Jessie repo (version 1.6.4)

LOG:
<code>07-10 09:59:24:596 Mirall::Application::Application(int&, char**) Skipping update check 
07-10 09:59:24:597 SocketApi:  server started "/home/brii/.local/share/data/ownCloud/socket" 
07-10 09:59:24:678 Sys Info size:  96 
07-10 09:59:24:679 No configured folders yet, starting setup wizard 
07-10 09:59:24:684 Migrate: checking old config  "/home/brii/.local/share/data/ownCloud/owncloud.cfg" 
07-10 09:59:24:699 Current Wizard page changed to  0 
07-10 09:59:32:902 "/home/brii/.local/share/data//ownCloud//cookies.db" 
07-10 09:59:32:903 void Mirall::AbstractNetworkJob::setTimeout(qint64) 10000 
07-10 09:59:32:918 !!! Mirall::CheckServerJob created for  QUrl( "https://MY_SERVER/o/" )  querying "status.php" 
07-10 09:59:33:223 status.php returns:  QMap(("edition", QVariant(QString, "") ) ( "installed" ,  QVariant(bool, true) ) ( "maintenance" ,  QVariant(bool, false) ) ( "version" ,  QVariant(QString, "8.1.0.8") ) ( "versionstring" ,  QVariant(QString, "8.1.0") ) )    0  Reply:  QNetworkReplyImpl(0x15d2020) 
07-10 09:59:33:224 Setup-Log:  "<font color="green">Udane połączenie z https://MY_SERVER/o/status.php: ownCloud wersja 8.1.0 (8.1.0.8)</font><br/><br/>" 
07-10 09:59:33:225 void Mirall::OwncloudSetupWizard::slotOwnCloudFoundAuth(const QUrl&, const QVariantMap&)  was redirected to "https://MY_SERVER/o" 
07-10 09:59:33:225 !!! Mirall::DetermineAuthTypeJob created for  QUrl( "https://MY_SERVER/o" )  querying "" 
07-10 09:59:33:349 void Mirall::AbstractNetworkJob::slotFinished() 204 "Host wymaga autoryzacji" 
07-10 09:59:33:349 virtual bool Mirall::DetermineAuthTypeJob::finished() "" 
07-10 09:59:33:357 Current Wizard page changed to  1 
07-10 09:59:37:545 Connect to url:  "https://MY_SERVER/o/" 
07-10 09:59:37:545 "/home/brii/.local/share/data//ownCloud//cookies.db" 
07-10 09:59:37:546 Setup-Log:  "Próba połączenia z ownCloud w https://MY_SERVER/o/..." 
07-10 09:59:37:546 !!! Mirall::ValidateDavAuthJob created for  QUrl( "https://MY_SERVER/o" )  querying "" 
07-10 09:59:38:059 void Mirall::AbstractNetworkJob::slotFinished() 202 "Error downloading https://MY_SERVER/o/remote.php/webdav/ - server replied: Forbidden" 
</code>

Before server upgrade (from 8.0.4 -> 8.1) everything works perfectly.
WebDAV form other programs works correctly.

**Comment by guruz** [comment]
@LukasReschke Is this the old-version check?
@briiman The current client version is 1.8.3 https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

**Comment by briiman** [comment]
1.8.3 works fine, but 1.6.4 is default version in Debian Stable (Jessie).

**Comment by Pastafarianist** [comment]
1.7.0 also has this issue, and that's the default version in Kubuntu 15.04.

**Comment by yason** [comment]
Hi.
Same problem with 1.4.2 on OpenBSD. 1.8.x doesn't work on OpenBSD (yet) so it would be great to have a fix for owncloud-server.

**Comment by dragotin** [comment]
@yason what is the problem on openBSD? Can you tell me or who can we ask? We should make sure that at least 2..0 is again running on openBSD properly.

I am clueless about what we can do about the stone age versions on xUbuntu tough. It would be great if xUbuntu would support our third party repo better, so that the users can pick up our updated versions more easily if they want that.

**Comment by yason** [comment]
@dragotin owncloud-client-1.8.3 starts sync but then dumps core. No matter hom much data should be synced. This happens IIRC even on clean account with default files. I think I should start new issue about this.

**Comment by guruz** [comment]
@yason If you start a new issue can you provide a backtrace for that coredump? :)

Start the client with ```gdb owncloud```
Then on crash ```thread apply all where```

**Comment by yason** [comment]
@guruz sure. Should I recompile client with "-g" in cxxflags?

**Comment by RealRancor** [comment]
For anyone who wants to run such an ancient version please read the https://doc.owncloud.org/server/8.1/admin_manual/release_notes.html which contains the info how to allow older versions (with all their drawbacks).

Another ref: http://owncloud.10557.n7.nabble.com/oC-8-1-x-and-sync-client-from-debian-jessie-td15438.html

**Comment by guruz** [comment]
@yason Yes please :) thanks for opening #3456
@RealRancor thanks for the useful comments, as usual :)
@jnweiger @LukasReschke  FYI distro stuff ^^

**Comment by nopejpg** [comment]
I'd also like to add that I ran into this issue with Xubuntu 15.04 after updating to 8.1. I simply updated the client and the problem went away. I'm adding this comment because I imagine others may have ran into the same issue.

**Comment by AndreaGiardini** [comment]
Different error message, same solution:

After the server upgrade i got:

Error downloading $url - Server replies: Forbidden

Upgrading the client solved the problem
