### ISSUE TITLE
[OS X] Client always asks for trustworthiness of SSL connection

### ISSUE THREAD

**Issue by romris** [owncloud/client#3437]
I updated to owncloud client version 1.8.3 (build 2504) for Mac. After rebooting, the sync client always asks me if I trust my self-signed certificate. I check "Trust this certificate anyway", but after rebooting the client asks again if I trust this SSL connection. I never had this problem with earlier versions of the client. How can I tell the client that I trust the certificate so that it never asks me again?

**Comment by dragotin** [comment]
@romris if that problem still persists, can you please provide us with a logfile of the starting phase?

**Comment by romris** [comment]
This is strange. I started the client with Terminal to record the log and then the client did never ask me again if I trust my self-signed certificate, also after a reboot. This seems to solve the issue, although I don't know why this works.

**Comment by guruz** [comment]
Should be better now with https://github.com/owncloud/client/commit/38b8508f15f1e2790722c9c437e5cd3e6fd4dc4b
