### ISSUE TITLE
[Multiaccount] I can't add Folder to sync, because the button NEXT it is not activated

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3438]
### Steps to reproduce
1. We need install one or two account
2. Go to Settings
3. Select one account (user1@....)
4. Press in "ADD FOLDER TO SYNC"
5. Press SELECT
6. Create a new local folder for sync, call user3
7. Press NEXT
8. Press "Create Folder" and create a folder
9. Press OK.

### Expected behaviour
You can Add Folder to Sync

### Actual behaviour
 I have this warning: "You not yet are synchronized files.....".
![screen shot 2015-07-10 at 12 52 32](https://cloud.githubusercontent.com/assets/12032058/8617412/daafb91e-2703-11e5-8600-4b2034091696.png)

I hope to synchronize, but the button NEXT is not activated

### Server configuration
Desktop v ownCloud-2.0.0.5257-nightly20150710-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by ogoffart** [comment]
The reason NEXT is not activated is explained in the "advertencia"
You can only sync a folder once.

(Maybe we should remove this restriction?)

**Comment by dragotin** [comment]
I think the [add folder] button should be disabled if we already sync the entire ownCloud.

**Comment by ogoffart** [comment]
@dragotin disabled or removed?

**Comment by jancborchardt** [comment]
I'd say disabled, with a tooltip containing what currently the Advertencia part says. Then the stuff which belongs together is actually together.

**Comment by Dianafg76** [comment]
@ogoffart I tested this issue, and the [Add Folder to Sync] is disabled
Many thanks, :-)
Desktop v ownCloud-2.0.0.5273-nightly20150715-setup.exe
