### ISSUE TITLE
No auto-syncronisation [Windows Client 1.8.3]

### ISSUE THREAD

**Issue by mitpro** [owncloud/client#3440]
The windows client don't update the sync folders automatically.
An uploaded file only get sync after a local change.
Linux Client with same server works well!

Server OS: Ubuntu 14.04
OC-Version: 8.0.4.2
Webserver: Apache2

Client Version: 1.8.3 (build 5250)

**Comment by guruz** [comment]
I'm not sure what exactly you mean.

If there is a file change on the oC server, the Windows client does not download the changhed file?

**Comment by mitpro** [comment]
Yes
No new files and changed files would be update on windows client

**Comment by ogoffart** [comment]
normaly we poll the server every 30 seconds for changes.
Did you edit the config file to change the polling timeout?
Can you elaborate on which kind of files it is, and the exact step to reproduce?

**Comment by mitpro** [comment]
A new test today - works well.... no idea
Thx :)
