### ISSUE TITLE
Windows Install Path 

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#3445]
Theming:
The client installs the application binaries into ```c:\program files\owncloud\``` while the last component is depending on the theme.

It is defined in the client file ```OwnCloudCPack.cmake``` but uses the theming var ```APPLICATION_NAME``` but not ```APPLICATION_SHORTNAME``` as it should.

Other places, ie. ```CPACK_PACKAGE_INSTALL_REGISTRY_KEY``` do the same, needs some more validation.

**Comment by Kawohl** [comment]
![wrong directory](https://cloud.githubusercontent.com/assets/12275313/8649943/f802a9dc-296e-11e5-8783-1b4ef8ef50ba.png)


One of our Customers sees this as a major issue, we might want to take a look at this sooner.

**Comment by danimo** [comment]
@Kawohl How is that related to the tickets? The files are in the correct place...

**Comment by Kawohl** [comment]
@danimo sorry for being unclear.

the Customer says: the sync client data should be in an other directory.  I'm not sure id this is related.

**Comment by danimo** [comment]
@Kawohl Ah, no, that's unrelated. You might want to talk to @dragotin how we ended up putting them there.

**Comment by Kawohl** [comment]
@danimo thanks!

**Comment by dragotin** [comment]
Fixed by 951c9812f13e6dd5018190bda413a0af83152e41

@Dianafg76 Attention, this is a dangerous thing. Please refer to the testing wiki page on how to test this, thanks!

**Comment by Dianafg76** [comment]
@dragotin Ok, Thanks

**Comment by Dianafg76** [comment]
@dragotin, I can't reproduce this issue, I need the steps for reproduce this. 
if you upgrade to a new version (desktop v  ownCloud-2.0.0.5289-nightly20150720-setup.exe) the files they are in the same place, I don´t now if is correct o no. Or the files should be in another place

![screen shot 2015-07-20 at 14 03 59](https://cloud.githubusercontent.com/assets/12032058/8775400/39c9f95a-2ee8-11e5-9126-b9a5b9c85294.png)

**Comment by dragotin** [comment]
@Dianafg76 this is only testable with a branded client with a colon in the name. However, my fix now uses the SHORTNAME for the path, and the ownBrander policy does not allow a colon in the shortname, so we can consider this ok. 

@michaelstingl will have an eye on this and reporting back if that fails later.

**Comment by michaelstingl** [comment]
@Dianafg76 @dragotin this the related issue (with branding):
https://github.com/owncloud/ownbrander/issues/381
