### ISSUE TITLE
Client 1.8.3-5250 doesn't detect deletes in a usefull manner

### ISSUE THREAD

**Issue by tps800** [owncloud/client#3446]
### Steps to reproduce
1. Install OwnCloud, Configure OwnCloud, Configure LDAP access
2. Start synching a directory from the client
3. Delete files on client side -- watch them redownloaded from the server
4. Delete files on the server side -- watch them reuploaded from clients

Workaround: delete all files on *all* clients, after stopping sync, then delete files from *all* servers.
This might be practical for a few clients an one server, but not if you have lots of clients an some servers.

### Expected behaviour
Deleting a file on server or client syncs deletion to all clients, servers.

### Actual behaviour
File is resynced from any client or server having it available.

### Client configuration
**Operating system:** Ubuntu 14.04.2 LTS

**OwnCloud Client:** 1.8.3 (build 5250)

**Operating system:** Windows 7 Pro

**OwnCloud Client:** 1.8.3 (build 5250)

### Server configuration
**Operating system:** Oracle Linux 6.6

**Web server:** Apache 2.2.15-39.0.1

**Database:** PostgreSQL 9.3.9-1

**PHP version:** PHP 5.6.10-1

**ownCloud version:** 8.1.0-13.1

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**List of activated apps:**
* Enabled:
 - activity
 - files
 - files_pdfviewer
 - files_sharing
 - files_trashbin
 - gallery
 - imprint
 - ocusagecharts
 - password_policy
 - user_ldap

* Disabled:
 - external
 - files_encryption
 - files_external
 - files_locking
 - files_texteditor
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_webdavauth

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server1>.<local1>.<domain1>',
    1 => '<server2>.<local2>.<domain2>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '/owncloud',
  'secret' => '',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (stable)
 * lynx (from cygwin)
 * w3m (from cygwin)
* Linux (Debian, Ubuntu 12.04/14.04/14.10, Fedora 19/20/21, Oracle Linux 6.5/7.0)
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror (stable)
 * lynx (stable)
 * w3m (stable)

#### Web server error log
```
Web server log
```

#### ownCloud log (data/owncloud.log)
```
ownCloud log
```

#### Browser log
```
Browser log
```

**Comment by guruz** [comment]
@tps800 Is the file in a shared folder or external storage?

@PVince81 @DeepDiver1975 Is there any known server bug for this?

**Comment by tps800** [comment]
Does not matter, as long as the user has rw-rights on his or shared files. In case he has rw-rights, the files get redownloaded as soon as he deleted some. If he deleted them on the server they are reuploaded from any client holding these files, including his own client.

**Comment by tps800** [comment]
The Linux-Client seems to work as expected, at least on Ubuntu/Debian. I could not try fedora at the moment, because of other client problems on this platform – fedora 23 seems to have some libraries in newer versions than expected by the client and I didn't have fedora 21, 22 available.
The Windows client does have the bug.
The nightly seems to suffer too.

**Comment by PVince81** [comment]
I'm not aware of any such issues on the 8.1.

@tps800 can you elaborate a bit on what you mean with the "rw-rights" ? Did you manually change/chmod the permissions on the server's "data" folder to something different than the default ?
Usually the "data" folder and all its contents should be owned by the web server, for example:
```
drwxr-xr-x 2 wwwrun www 60 Jul 14 07:37 files
```

**Comment by ogoffart** [comment]
Normaly the client should delete the files in the other ends when the files gets deleted on the client or on the server.  So i can imagine a few reason why the client would re-upload or re-download the files

 - The directory is a read-only directory on the server.  In that case the client would re-download the deleted files on the client. But it should not attempt to upload the files
 - The client database is corrupted.  If the contents of the database does not match the etag on the server or mtime on the client, the files are re-up/downloaded.  But normaly we check the integrity of the database before a sync, and a lot of other things would also be broken.
 - There is two clients syncing the same directory. They would step on each-other feet and writing different stuff in the client database.

**Comment by tps800** [comment]
@PVince81 second install of the client on a Windows 7 system:
1. After install first sync: about 70GiB to download. Took hours, but was successful.
2. Now deleted some files on the server
3. Waiting on deletion of these files on the client, but: instead of deleting these files they are uploaded again!
4. Deleted some files from the clients sync directory.
5. Instead of these files deleted on server they are downloaded from the server!

Done the same on Linux (Ubuntu 14.04.2 LTS):
1. After install first sync: abuot 70GiB to download. Took hours, but was successful.
2. Now deleted some files on the server
3. Waiting on deletion of these files on the client. Success! They vanished!
4. Deleted some files from the clients sync directory.
5. Could watch these files being deleted from the server.

-> Windows 7: client doesn't detect deletions instead up-/downloads files deleted on other systems.
-> Linux: client detects deleted files, deleted them on server and vice versa.

If the user has rights to write to the sharing space of other users, his client will also sync files deleted by the owner of the shared files upwards. If the user does not have rights to write to shared spaces, the client will only keep files deleted on the server and just not delete them.

It is not necessary to fiddle with the file systems on the server directly -- and this was't done. The only thing done was:
- delete files on server -> resync from Windows clients
- delete files on Windows Clients -> resync from Server

While the Linux client does what is awaited, the latest Windows Client does not.

**Comment by guruz** [comment]
@tps800 did you mean to close this issue?
