### ISSUE TITLE
[Windows, OS X] Switch to Qt 5.6.2 for 2.3 client

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3449]
Right now we're based on 5.4.0+patches

https://github.com/qtproject/qtbase/blob/dev/dist/changes-5.4.1 (incomplete usually)
https://github.com/qtproject/qtbase/blob/dev/dist/changes-5.4.2 (incomplete usually)
https://github.com/qtproject/qtbase/blob/dev/dist/changes-5.5.0 (incomplete usually)
https://wiki.qt.io/New_Features_in_Qt_5.5

**Comment by dragotin** [comment]
I'd vote for staying with the current build that we had for 1.8.4 (5.4.0+patches) for 2.0.0 and go to hopefully 5.5.1 wtih the next bugfix release, ie. oCC 2.0.1. One moving target less.

**Comment by hefee** [comment]
for downstream it would be nice to to nail to newest qt version and don't bump the minimum version for no reason. 

And changing the minimum version within bugfix releases is really not a good thing, cause normally bugfix releases should be a minimal changeset and therefore the dependency shouldn't changed. 

For sure you can ship a new qt version within obs at any time - i'm just talking about the CMakefile.txt

**Comment by danimo** [comment]
There is no time for a 5.5 switch in the 2.0 timeframe. @hefee I don't think we'll soon drop support for older Qt versions, but e.g. 5.5. solves the systray issue. But that's a different conversation, since we can't have 5.5. everywhere in the forseeable future.

**Comment by guruz** [comment]
-> 2.1 then

**Comment by guruz** [comment]
5.5.1 is about-to-be-released..

**Comment by ogoffart** [comment]
5.5.1 was released

**Comment by dragotin** [comment]
This is the repo to update: https://build.opensuse.org/project/show/isv:ownCloud:toolchains:mingw:win32:stable
and this is how its done:
https://en.opensuse.org/openSUSE:Build_Service_Collaboration#How_do_I_contribute_my_changes_to_someone_else_packages.3F

**Comment by guruz** [comment]
5.6 (unreleased) has some network fixes, analyzing those now and then maybe we stay a bit on our patched 5.4 plus those patches..

**Comment by scolebrook** [comment]
Is the patched version of qt you use for official builds of ownCloud available anywhere? Or are the mentioned patches in the client repo and get applied during the build process?

I'd prefer to make sure that our build is as close as possible to being the same as yours (apart from branding of course).

**Comment by ogoffart** [comment]
@scolebrook We use the Qt build on OBS.  All the patches are already upstreamed.
https://build.opensuse.org/package/show/isv:ownCloud:toolchains:mingw:win32:stable/mingw32-libqt5-qtbase

**Comment by guruz** [comment]
@scolebrook With ownBrander you automatically get the correct Qt https://doc.owncloud.org/server/8.1/admin_manual/enterprise_clients/creating_branded_apps.html

**Comment by scolebrook** [comment]
@ogoffart So the patches discussed relate to win only? Stock qt for mac builds is fine?

@guruz We evaluated ownbrander back when it was first released. It didn't do a number of key things we needed and we had a conference call with @bboule, @gig13 and @MTRichards about it IRC. That was a while ago and I should probably re-evaluate as I believe there have been some improvements.

**Comment by guruz** [comment]
@danimo @dschmidt @dragotin FYI https://github.com/owncloud/client/commit/00708353307e236db071b1421ffe1f0a1e3457ee

**Comment by guruz** [comment]
@scolebrook We use the same Qt-patches-on-top for OS X and Windows builds

**Comment by dschmidt** [comment]
@guruz interesting. Thanks!

**Comment by dschmidt** [comment]
Any other thoughts on Qt 5.6? Wondering if it's worth trying to build it soon...

**Comment by guruz** [comment]
It looks like I need also
```
diff --git a/admin/osx/macdeployqt.py b/admin/osx/macdeployqt.py
index 60ff4b9..3a39d82 100755
--- a/admin/osx/macdeployqt.py
+++ b/admin/osx/macdeployqt.py
@@ -38,8 +38,10 @@ QT_PLUGINS = [
     'imageformats/libqgif.dylib',
     'imageformats/libqico.dylib',
     'imageformats/libqjpeg.dylib',
     'imageformats/libqsvg.dylib',
     'imageformats/libqmng.dylib',
+    'bearer/libqcorewlanbearer.dylib',
+    'bearer/libqgenericbearer.dylib'
 ]
 
 QT_PLUGINS_SEARCH_PATH=[
```

else I get "Network access is disabled". Although this is odd, I thought if the bearer plugins are not loaded it would just allow me to use the network no matter what 
FYI @lpotter

**Comment by lpotter** [comment]
thanks for the heads up. Patch must not have made it upstream.

https://bugreports.qt.io/browse/QTBUG-49267

**Comment by lpotter** [comment]
If Qt is configured for bearermanagement, it requires at least one backend plugin. 
QNAM will use QNetworkSession, which will never open a session when there is no backend available.

If you do not want to ship bearer plugins, configure Qt with -no-feature-bearermanagement

**Comment by lpotter** [comment]
That said, with this change:
https://codereview.qt-project.org/#/c/140116/
You wont need bearer plugins.

**Comment by guruz** [comment]
@danimo has prepared some things already.
Estimated release for 5.6.0 is 3rd of March 2016
https://wiki.qt.io/Qt-5.6-release

**Comment by dragotin** [comment]
Qt 5.6.0 is out now, right @danimo ? Are we going to switch? I think we should.

**Comment by guruz** [comment]
Something to keep in mind: https://github.com/owncloud/client/issues/4676

**Comment by dragotin** [comment]
We need to postpone that to one of the next versions. @danimo has no time.

**Comment by guruz** [comment]
Note for OS X: We have to get the patch https://codereview.qt-project.org/#/c/158358/ mentioned in https://github.com/owncloud/client/issues/4676#issuecomment-218171957

**Comment by guruz** [comment]
Win32: Work is ongoing in https://build.opensuse.org/project/monitor/isv:ownCloud:toolchains:mingw:win32:2.3

**Comment by guruz** [comment]
@jturcotte yesterday volunteered to look at the macbuilder/lexmacbuilder work to be done including jenkins integrations and making sure nothing break :)

I'll try to pick up the Windows part and switch from 5.6.1 to 5.6.2 (will ping @dragotin @jnweiger if i need help)

**Comment by guruz** [comment]
We have a Windows build! Thanks a lot @dragotin and @dschmidt 

https://rotor.int.owncloud.com/view/ownCloud-client/job/ownCloud-client-win32/6619/
@SamuAlfageme Can you give this a smoke test? It should mention 

Docker image: guruz/docker-owncloud-client-win32 from docker build https://github.com/guruz/docker-ownCloud-client-win32.git#2.3

client branch: win_562 (would need to be merged when changing Jenkins)

@jnweiger Do you want to tag this as real docker-owncloud-client-win32 ? You need to adapt the Jenkins configuration to check if it will really take the tagged docker-owncloud-client-win32 then for 2.3
The goal would be to have the Windows nightlies build with 5.6.2


@dschmidt will work on improving the currently a bit hacky 2.3 OBS repo. Possibly even considering https://github.com/owncloud/client/issues/2140 ?

(I'm gone until 12th this month)

**Comment by guruz** [comment]
macOS
* [ ] 10.11.5 the 2.3 nightly is using Qt 5.6.2 and works

Windows
* [ ] Windows 10 the 2.3 nightly is using Qt 5.6.2 and works

Maybe @SamuAlfageme has input on older Windows like Windows 7?

**Comment by SamuAlfageme** [comment]
@guruz I have been actually using the build from the new cross-compilation image for over a week now in all my tests in Win(7), so far, so good. 

Sometime this week, I would move to carry a full functionality/regression test of these builds.

**Comment by dschmidt** [comment]
Woohoo, that's good news that we have no obvious regressions :)
(We did a big jump in compiler versions e.g.)

**Comment by guruz** [comment]
Closing this as we implicitely test this :)
