### ISSUE TITLE
Mac OS 1.8.4.2527 client package keeps crashing 

### ISSUE THREAD

**Issue by jaal2001** [owncloud/client#3450]
Updated to 1.8.4.2527.
After update the App keeps crashing, only displays the option to send a bug report.

Deleted App.
Clean install, still the same issue.

Crash seems to happen before contacting the owncloud server, as I can't see any http(s) request on my owncloud server.

Mac: OS X Yosemite

Please let me know if I can send in any further details.

**Comment by nashinoki** [comment]
same thing here.

**Comment by hensiek** [comment]
1.8.4 crashed on me with yose:10.10.4. went back to mac-client 1.8.3 with smooth op.

**Comment by danimo** [comment]
We're looking into it. Halting the update for OS X for now.

**Comment by sbgraphic** [comment]
Same crash on OSX 10.8.5… 1.8.3 sync was suspended just before too.

**Comment by dirkpape** [comment]
same here 10.10.4 German

**Comment by danimo** [comment]
http://download.owncloud.com/desktop/daily/ownCloud-1.8.4.2530-nightly20150713.pkg works for me. Can you check? (might require a full uninstall of /Application/owncloud.app).

**Comment by dirkpape** [comment]
b2539-nightly works here. Thanks!

**Comment by rakekniven** [comment]
Build 2530 works well on 10.10.4.
The ones I got from autoupdater 15 minutes ago didn't.
I hadn't to uninstall first. Just ran your pkg and it works.

**Comment by throker** [comment]
Build 2530 worked for me as well. I didn't have to uninstall.

**Comment by danimo** [comment]
ok, build `2531` is the new 1.8.4 for Mac. Closing this. Please report back of you encounter any problems.

**Comment by rakekniven** [comment]
Can you give some detail of the changes you did to fix the issue?

**Comment by guruz** [comment]
afaik it was a binary incompatibility between the new OpenSSL and Qt
