### ISSUE TITLE
Client gets disconnected

### ISSUE THREAD

**Issue by blacky1707** [owncloud/client#3451]
If you are switching from WLAN to LAN on MacOS the client gets disconnected sometimes.

**Comment by guruz** [comment]
Which version? Did you try 1.8.4?

**Comment by ogoffart** [comment]
Do you have the log when this happens or the reason why it gets disconnected?

**Comment by blacky1707** [comment]
1.8.4 - yes

**Comment by blacky1707** [comment]
Where to find the log?

**Comment by blacky1707** [comment]
Found it by myself: https://forum.owncloud.org/viewtopic.php?f=17&t=6526 Will enable it, and send the log

**Comment by guruz** [comment]
Any news @blacky1707 ?

Please also note we have 2.0 nightlies (for OS X .pkg) available http://download.owncloud.com/desktop/daily/
