### ISSUE TITLE
libocsync.so missing for SLES 12  with sync client rpm 1.8.3-6.1.x86 64 rpm

### ISSUE THREAD

**Issue by CaptionF** [owncloud/client#3452]
Installation performed through owncloudcmd 
with RPM (http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/SLE_12/x86_64/owncloud-client-1.8.3-6.1.x86_64.rpm), but libocsync.so missing.

result: sync client on SLES 12 not working.

**Comment by jnweiger** [comment]
I get all dependencies right now. But I get 1.8.4 already.
Maybe your mirror updated itself, exactly while you tried to install?

Cannot reproduce, sorry.
<pre>
(1/6) Installation von: libQtWebKit4-4.8.6+2.3.3-1.106 ......................................................[fertig]
(2/6) Installation von: libqt4-sql-sqlite-4.8.6-2.11 ........................................................[fertig]
(3/6) Installation von: libqtkeychain0-0.5-4.1 ..............................................................[fertig]
(4/6) Installation von: libowncloudsync0-1.8.4-1.1 ..........................................................[fertig]
(5/6) Installation von: owncloud-client-1.8.4-1.1 ...........................................................[fertig]
(6/6) Installation von: owncloud-client-l10n-1.8.4-1.1 ......................................................[fertig]
</pre>

**Comment by jnweiger** [comment]
Please repopen, if this persists on your side.
