### ISSUE TITLE
Crash in QtNetwork when connecting to non-HTTP port

### ISSUE THREAD

**Issue by grexe** [owncloud/client#3453]
In the desktop sync client configuration (first start), I mistakenly entered a wrong port, so the client tried to connect to our youTrack instance instead,-)
This crashed the client, I'd prefer a more subtle error message...
I'm on KUbuntu Linux 15.04 x64, ownCloud server 8.0.4, latest sync client (works fine with the correct URL, there's no docker image for 8.1 yet).

**Comment by ogoffart** [comment]
What is the version of your client? 
Do you have a backtrace?

**Comment by ogoffart** [comment]
I could not reproduce any problem. Maybe there was something special about the URL like special character or anything like that?

**Comment by grexe** [comment]
No I just reproduced it - Server: ownCloud 8.1 on Linux/nginx, client 8.1 Linux (Ubuntu 15.04 64bit).
We have a dev server for our infrastructure, different apps are mapped to individual ports.
So if I accidentially specify the wrong port, I might wrongly access our YouTrack instance.
When this happens, the ownCloud client (Linux desktop client, in the account setup) hangs (spinner) and eventually crashes.

**Comment by guruz** [comment]
Can you launch the client in gdb to get a backtrace?

**Comment by guruz** [comment]
So what is a sample URL that crashes?

**Comment by grexe** [comment]
It's just an internal server with a special port 10001 (our youtrack instance, which is of course not suitable), ownCloud is on 10003.
Here's a stack trace, hth: 
```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff6b8dd38 in ?? () from /usr/lib/x86_64-linux-gnu/libQtNetwork.so.4

(gdb) info threads
  Id   Target Id         Frame 
  8    Thread 0x7fffe014a700 (LWP 20146) "QProcessManager" 0x00007ffff4fd2743 in select () at ../sysdeps/unix/syscall-template.S:81
  7    Thread 0x7fffdf673700 (LWP 20149) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  6    Thread 0x7fffde636700 (LWP 20150) "QThread" 0x00007ffff4fd08dd in poll () at ../sysdeps/unix/syscall-template.S:81
  5    Thread 0x7fffdd7ac700 (LWP 20151) "QThread" 0x00007ffff4fd08dd in poll () at ../sysdeps/unix/syscall-template.S:81
  4    Thread 0x7fffcffff700 (LWP 20154) "QThread" 0x00007ffff4fd08dd in poll () at ../sysdeps/unix/syscall-template.S:81
  3    Thread 0x7fffceffd700 (LWP 20157) "QThread" 0x00007ffff4fd08dd in poll () at ../sysdeps/unix/syscall-template.S:81
  2    Thread 0x7fffcf7fe700 (LWP 20155) "Thread (pooled)" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
* 1    Thread 0x7ffff7fb0800 (LWP 20140) "owncloud" 0x00007ffff6b8dd38 in ?? () from /usr/lib/x86_64-linux-gnu/libQtNetwork.so.4
```

**Comment by guruz** [comment]
A crash in QtNetwork..nice..
Thanks.

**Comment by guruz** [comment]
Might be better now with Qt 5.6.2

**Comment by ogoffart** [comment]
Closing old issue.
