### ISSUE TITLE
[1.7.1] high CPU usage

### ISSUE THREAD

**Issue by Germano0** [owncloud/client#3454]
I am experiencing an high CPU usage problem since mirall-1.5.4 version. Now I am using 1.7.1 but I am still experiencing this problem.
Fedora package mantainer is not responsive, then I have not been told how to retrieve useful debug infos.

https://bugzilla.redhat.com/show_bug.cgi?id=1175256

my system is Fedora 22 KDE Plasma 5

**Comment by dragotin** [comment]
yes, you should consider installing via https://owncloud.org/install/#install-client You will find packages of the latest released version there. The one from fedora is outdated unfortunately.
