### ISSUE TITLE
Different units are used to represent sizes

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#3457]
### Expected behaviour
Client uses same units for sizes as server (KB/MB/GB)

### Actual behaviour
Client uses "KiB"/"MiB"/"GiB"

### Client configuration
Client version:
1.8.3

Operating system:
Windows

OS language:
DE

Here is a related Issue:
https://github.com/owncloud/core/issues/13386

@MorrisJobke How can we explain this to our users?

00003498

**Comment by MorrisJobke** [comment]
> @MorrisJobke How can we explain this to our users?

? "Hey we now use proper decimal units!"? ;)

**Comment by jancborchardt** [comment]
Well, the server does it like popular systems such as Windows Explorer, OS X Finder, Dropbox and Google Drive (if it doesn’t, we need to adjust). And the client should do the same thing as the server – going rogue with this doesn’t make sense.

@ogoffart @dragotin

**Comment by ogoffart** [comment]
And does Finder, Dropbox and Google drive use base 1024 or base 1000?

**Comment by jancborchardt** [comment]
@ogoffart not sure, test it and let’s use what the most prominent ones do. But this discussion belongs in https://github.com/owncloud/core/issues/13386

**Comment by dragotin** [comment]
Fixed for 2.0.2 through changing back to JEDEC units.

**Comment by Dianafg76** [comment]
I tested this issue, and the client uses the units for the sizes (KB / MB / GB )
Desktop v ownCloud-2.0.2.5463-nightly20150915-setup.exe 
Closed
