### ISSUE TITLE
[NSIS Installer] In case of update, do NOT show the choice to remove the data folder.

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#3461]
If somebody gets an auto update, it's pretty obvious that she wants to continue to use ownCloud, and thus does not want to remove the data directory. Is there a way to not show the following installer page if the installer was started from the updater:

![rem_datafolder](https://cloud.githubusercontent.com/assets/1070214/8719217/34f9660e-2baa-11e5-92f2-443a30005e5f.png)

**Comment by danimo** [comment]
@dragotin please review

**Comment by Dianafg76** [comment]
@danimo, I tried this, and I have a doubt. If you have a Destokp v 2.0.0 (build 5230 ) and when actulizas 2.0.0 ( 5289 ) , this appears " Do you want to remove the data folder ownCloud ? " . This is correct?

**Comment by Dianafg76** [comment]
@danimo Hello, I tested this issue, and working fine
.- When upgrading a 2.0 pre ownCloud (applies to snapshots past 15.07.2015) to another one or 2.0 alpha, beta, rc or final, you should not see a page in the upgrade wizard offering to remove the application's AppData (see screenshot on original bug for reference). 
##### It is OK
.- When uninstalling 2.0, you should not see a page in the upgrade wizard offering to remove the application's AppData (see screenshot on original bug for reference). When upgrading from 1.8.x or earlier, to a 2.0 snapshot (applies to snapshots past 15.07.2015), alpha, beta, rc or final, you *should** see a page in the upgrade wizard offering to remove the application's AppData (see screenshot on original bug for reference). Reason: This dialog is provided by the already installed version.
##### It is OK

Desktop v ownCloud-2.0.0.5291-nightly20150721-setup.exe  

Many thanks, :-)
