### ISSUE TITLE
[Multiaccount] You can change the password in "Sign In" and you can deleted file/folder with the wrong password

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3462]
### Steps to reproduce
1. You need created two accounts
2. Right click in Icon oC
3. Go to one account (user1@....)
4. Click in SIGN OUT
5. Right click in Icon oC
6. Go to the same account (user1@...)
7. Click in SIGN IN
8. Deleted the password
9. Write othe password (for example: 111)
10. Click in OK
11. SYNC
12. Right click in Icon oC
13. Go to one account (user1@....)
14. Go to "Open Folder ..."
15. Deleted one Folder/File
16. In Desktop is deleted
17. Go to Server
18. Introduce the right password
19. Sync

### Expected behaviour
10. You can't introduce the different password
19. You can't delete the file because you've entered another Password
### Actual behaviour
10. The account is sync, but with different password.
19. The folder is deleted in the Server.

### Server configuration
Desktop v ownCloud-2.0.0.2540-nightly20150716.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by ogoffart** [comment]
I can reproduce.

It seems that log out do not forget the password.

**Comment by ogoffart** [comment]
or the cookie

**Comment by Dianafg76** [comment]
@ogoffart  I tested this issue, and working fine
Many thanks, :-)
Desktop v ownCloud-2.0.0.2542-nightly20150717.pkg

Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}
