### ISSUE TITLE
[Multiaccount][OS X] The ownCloud Extensions should be enabled by default after an install of the client

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3463]
### Steps to reproduce
1. You need install Multiaccount
2. Right click in Icon oC 
3. Go to one account (user1@....)
4. Got to "Open Folder 'owncloud...' "
5. Create a new Folder/File
6. Right click on the new Folder/File

### Expected behaviour
The option "Share with ownCloud" must be on the list

### Actual behaviour
The option "Share with ownCloud" is not listed 
![screen shot 2015-07-16 at 12 50 57](https://cloud.githubusercontent.com/assets/12032058/8721416/c15ee37a-2bba-11e5-9d20-82c7ceb561dd.png)

### Server configuration
Desktop v ownCloud-2.0.0.2540-nightly20150716.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by dragotin** [comment]
Indeed, daily build from july 20th does neither have the share context menu entry nor overlay icons.

**Comment by jturcotte** [comment]
Hi Diana, could you try to go in System Preferences / Extensions / Finder and check if "ownCloud Extensions" is disabled?

We might need to enable this programatically, especially since users seem to have to explicitly disable it to be able to uninstall ownCloud. The question is then how to make sure that they didn't want to really disable the extensions because they don't want it.

**Comment by Dianafg76** [comment]
@jturcotte The "ownCloud Extensions" is Not enabled

**Comment by jturcotte** [comment]
I guess this is the bug then, we have to make sure it is enabled without users having to dig their settings.

**Comment by Dianafg76** [comment]
If I activate, is working. 
![screen shot 2015-07-21 at 12 58 32](https://cloud.githubusercontent.com/assets/12032058/8799142/398eabf0-2fa8-11e5-954b-ee4c96f4eec5.png)

**Comment by guruz** [comment]
@Dianafg76 If you uninstall the client (http://www.corecode.at/uninstallpkg/) and then make sure there is no oC extensions in System Preferences / Extensions / Finder and then re-install the client (2.x) nightly, do you see it then in System Preferences / Extensions / Finder enabled by default?

**Comment by Dianafg76** [comment]
@guruz I can't uninstall the client (http://www.corecode.at/uninstallpkg/) appears this error
![screen shot 2015-07-22 at 17 36 03](https://cloud.githubusercontent.com/assets/12032058/8829668/2bbfdb70-3098-11e5-8e53-a2fc54b03828.png)

**Comment by Dianafg76** [comment]
I Uninstall com.ownCloud.finderPlugin an com.owncloud.client. and if I go to System Preferences oC / Extensions / Search no extensions oC. So , tomorrow morning I install the desktop client v 2.0.0 nightly

**Comment by Dianafg76** [comment]
@guruz I install the Desktop vownCloud-2.0.0.2559-nightly20150723.pkg and is enabled by default the option onwCloud Extensions.
Many thanks, :-)

**Comment by jturcotte** [comment]
Forced the activation of the extension after installing. In this case, there should be no way that the user is forced to activate the finder integration extension through SystemPreferences/Extensions.

**Comment by Dianafg76** [comment]
I close. If I restart my pc and appears.
Many thanks

**Comment by guruz** [comment]
This needs to be done properly for branded clients.
https://github.com/owncloud/client/commit/ed51358478c92ffe3790f8be576a87287ef82faf#diff-bf05b20fe33ddca7b7d265f58a62785bR13

**Comment by guruz** [comment]
@Dianafg76 Please re-test on Monday with testpilotcloud. It should enable the extension on install.

**Comment by Dianafg76** [comment]
@guruz I tried to testpilotcloud ownCloud v 2.0.0.2586 TestPilot Edition- - nightly20150731.pkg and see the option Share with...

**Comment by Dianafg76** [comment]
1. uninstall the v 2.0.0
2. Disable the ownCloud extension from the Extensions preference pane before moving it to the trash.
3. I installed the old v1.8.4
4. I update to version 2.0.0
5. Right click in Icon oC
6. Go to one account (user1@....)
7. Got to "Open Folder 'owncloud...' "
8. Create a new Folder/File
9. Right click on the new Folder/File

The option "Share with ownCloud" is not listed 
I need to go to Preferences iSystem OC / Extensions / Find messages XTensions oC oC activate the option for icons and the "Share with OC"

**Comment by guruz** [comment]
Do you mean you had 1.8.4 running while updating to 2.0?

**Comment by Dianafg76** [comment]
@guruz Yes

**Comment by guruz** [comment]
Are you 100% sure you used a current nightly? Which one did you use?

I don't think the 1.8.4 running matters.

I disabled the extension in Control Panel.
Then I install ownCloud-2.0.0.2592-nightly20150803.pkg 
I launch it and have it open the sync folder.
It shows overlay icons and "Share with ownCloud"/

**Comment by Dianafg76** [comment]
Yes I sure. 
I disabled the extension in Control Panel
I install the v1.8.4 (build 2564)
Then I update ownCloud-2.0.0.2592-nightly20150803.pkg 
I don't shows the overlay icons and "Share with ownCloud/"
![screen shot 2015-08-04 at 15 28 13](https://cloud.githubusercontent.com/assets/12032058/9061648/75b47d92-3abd-11e5-995f-22ca959e6c81.png)

But, If you activated the control panel extension. Appears the option "Share with ownCloud"

![screen shot 2015-08-04 at 15 31 19](https://cloud.githubusercontent.com/assets/12032058/9061725/f5069134-3abd-11e5-86fa-67667373512a.png)

**Comment by Dianafg76** [comment]
I disabled the extension in Control Panel
Then I install ownCloud-2.0.0.2592-nightly20150803.pkg 
and It shows overlay icons and "Share with ownCloud"/

**Comment by cdamken** [comment]
@Dianafg76 @guruz 

I tested again, you can't have overlay icons in both clients at the same time, only one will have it (I suppose the standard client, and the branded doesn't. 

About the share wit, in Windows does work even if you have 2 clients installed.

I hope it helps

**Comment by guruz** [comment]
@Dianafg76 Could you test with this nightly?
http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.2602-nightly20150805.pkg

@cdamken Hmm in theory that should work. Did you test with both versions 2.0?

**Comment by Dianafg76** [comment]
@guruz I tested this issue, and it is working OK
Many thanks
I close the issue

**Comment by cdamken** [comment]
@guruz Yes, it works with 2.0

**Comment by Dianafg76** [comment]
I reopen this bug, because if I install the Desktop v ownCloud-2.0.0.2668-nightly20150825.pkg, I don't shows the overlay icons and "Share with ownCloud/". If you activated the control panel extension. Appears the option "Share with ownCloud"

**Comment by Dianafg76** [comment]
If I reboot my Mac, is working fine
So I close the issue
