### ISSUE TITLE
[Multiaccount] [OS X] You have a old version (for example 1.8.4) and uploadd to the version 2.0.0. You can't use the SSL button if you have two accounts

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3464]
### Steps to reproduce
1. You have a old version (for example 1.8.4) and uploadd to the version 2.0.0
2. Right click in Icon oC 
3. Click in Settings

### Expected behaviour
You should see the certificate of the two accounts

### Actual behaviour
![screen shot 2015-07-20 at 12 45 26](https://cloud.githubusercontent.com/assets/12032058/8774336/45662d34-2edd-11e5-9665-90f1da60cf89.png)

I need to delete the account and select another account and now I can see the certificate information

### Server configuration
Desktop v ownCloud-2.0.0.2540-nightly20150716.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
@guruz The screen is not correct, sorry
 If you have 2 account, in the second account you can't see the certificate

**Comment by Dianafg76** [comment]
![screen shot 2015-07-20 at 12 10 49](https://cloud.githubusercontent.com/assets/12032058/8773898/787e697a-2ed8-11e5-8589-29884b87e714.png)

**Comment by guruz** [comment]
@Dianafg76 is the edit button in github visible for you?
you can remove the wrong screenshot

**Comment by Dianafg76** [comment]
That is the correct screen

**Comment by guruz** [comment]
I can only tackle this properly after the config migration is done properly so I can test exactly what happens here..
see https://github.com/owncloud/client/issues/2245#issuecomment-114925147

**Comment by guruz** [comment]
(Maybe #3528  fixed this)

**Comment by Dianafg76** [comment]
@ guruz I can not reproduce this problem . Because now I have Installed version 2.0.0 , and when I go to uninstall the 2.0.0 version looks like this:
![screen shot 2015-08-03 at 10 57 11](https://cloud.githubusercontent.com/assets/12032058/9034327/1031ced2-39cf-11e5-90cc-d4770e2a7fcf.png)
Only about MAC , because if I try to Windos is working

**Comment by guruz** [comment]
@Dianafg76 OK, meanwhile as a workaround before moving to trash do on Terminal ```killall Finder```

FYI @jturcotte

**Comment by jturcotte** [comment]
You can also disable the ownCloud extension from the Extensions preference pane before moving it to the trash.

**Comment by Dianafg76** [comment]
I've tried this, and now looks good screen
![screen shot 2015-08-03 at 12 39 08](https://cloud.githubusercontent.com/assets/12032058/9035934/d2515e4e-39dc-11e5-8a29-c00afa768c69.png)
