### ISSUE TITLE
File upload does not continue early after network error is gone again

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3466]
### Expected behaviour
After upload errors, file upload should try again in some "reasonable" period of time.

### Actual behaviour
After more than 30 minutes ownCloud client had done nothing and the file was still sitting in the client-side folder waiting to be uploaded.
![interrupted-file-upload](https://cloud.githubusercontent.com/assets/1535615/8722161/5fca20bc-2be1-11e5-964b-d96486299ec3.png)

### Steps to reproduce
1. Add a file to a folder in the client-side ownCloud. It happily starts uploading - good.
2. I pulled the network cable from my computer. Operation canceled error comes in the activity log - good.
3. Plug the network cable back in. The upload started again within a few seconds - good.
4. Pull the internet connection further upstream on the network (so that the client computer would not directly know in hardware about any network problem). After some time (30 seconds or so) the upload gives "aborting" and the activity log shows "Connection closed" - good.
5. Connect the upstream internet again. Confirm that internet is working on client computer.
I expected that within some "reasonable" time (5 minutes or so?) the ownCloud client would retry connection to the server, find that it could connect, and would starting syncing again.
After more than 30 minutes nothing had happened.
I created an empty folder in the client-side ownCloud folders and that triggered immediate upload of the new folder followed by upload of the file that had previously been interrupted.

Am I missing something here?
Do I really need to make another modification to the client-side folders to wake-up ownCloud client?
Is the retry timer even longer than I left it?

### Server configuration
ownCloud version: 8.0

### Client configuration
Client version: 1.8.4 (build 5267)

Operating system: Windows7

OS language: English

**Comment by ckamm** [comment]
@phil-davis Good catch, we should indeed remember that a folder is still dirty and retry sooner.

The delay for automatic sync runs is currently 2 hours. (see `ConfigFile::forceSyncInterval`)

**Comment by ckamm** [comment]
Huh, every folder of an account should already be scheduled for a sync when the account state becomes connected. I'll try to reproduce...

**Comment by ckamm** [comment]
@phil-davis This works correctly for me. Can you reproduce it and check the logs? As soon as an account becomes connected, the folders should be scheduled for syncing.

You can look for `*** Start syncing` in the logs. If you grep for `accountstate.cpp` you'll see the account's state transitions. Grepping for `folderman.cpp` is also often useful.

**Comment by phil-davis** [comment]
I tested with ownCloud client 2.0.0beta1 on Windows 10. Both scenarios work fine:
a) Disconnect the local cable on the client, or;
b) Disconnect a cable upstream somewhere
The upload in progress times out after 20 to 30 seconds.
After the cable is connected again in both scenarios the upload continues within 20 to 30 seconds.]
All good thanks.

**Comment by ckamm** [comment]
@phil-davis Thanks for verifying!
