### ISSUE TITLE
[Multiaccount] Long account names look strange in interface

### ISSUE THREAD

**Issue by stonerl** [owncloud/client#3471]
The current scheme for the account-name is user@server which can result in very long names e.g. john.doe@my.owncloud.server.somthing

You can see this in the pictures I attached. If it would be possible to edit the account names it would need less space in the tray-menu and the settings window.

![screen shot 2015-07-17 at 09 06 21](https://cloud.githubusercontent.com/assets/2091312/8742407/4e94f6f8-2c65-11e5-82e0-ccfc7ffafff7.png)

![screen shot 2015-07-17 at 09 17 19](https://cloud.githubusercontent.com/assets/2091312/8742426/88db495c-2c65-11e5-83d2-ce8bd3c32244.png)

**Comment by ogoffart** [comment]
@jancborchardt    We could introduce an "alias" like there is currently for the folders

**Comment by jancborchardt** [comment]
We don’t really need an alias, we simply need to ellipsize it after a reasonable length.

**Comment by dragotin** [comment]
@jancborchardt ...which easily results in ```drago....d.com``` if you want to shorten it to an reasonable length :worried:   What's wrong with an alias?

**Comment by guruz** [comment]
At least on OS X (should be same?) I can easily add a \n e.g. after the @ 
Shall we have that?

**Comment by ogoffart** [comment]
The \n instead of the @ breaks the layout on linux. (it break the css applied to the toolbar widget)  (but that may be fixed by doing some tweakings in the style)

**Comment by jancborchardt** [comment]
Yeah, the line break instead of @ sounds like good design. Maybe even put the front part / first line (the username) in bold and/or larger typeface to emphasize it. Depending on what’s possible and what looks good, of course.

Why no aliases you ask? Because it’s another thing people have to manually think about. It’s really something we can solve automatically instead of relying on custom stuff. Also, people could still choose a long alias (or complain if they can not … you know).

**Comment by dragotin** [comment]
Hmm, as long as the alias defaults to the user@host as now, not much to think about... But a solution that would work for people nicely.

**Comment by Dianafg76** [comment]
@stonerl Hi, could you try with this version: http://download.owncloud.com/desktop/daily/ownCloud-2.1.0.2821-nightly20151022.pkg.
Thanks

**Comment by guruz** [comment]
@stonerl Note that this is the 2.1 codebase which is quite untested currently, use with caution.

**Comment by stonerl** [comment]
@guruz  @Dianafg76 The only difference I see is, that the TLD is appended.

**Comment by guruz** [comment]
@stonerl For me there is a line break in the 2.1 codebase.
