### ISSUE TITLE
[Centos 6] Missing application icon in 1.8.4

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#3473]
### Expected behaviour
Desktop sync client should have an application icon in the Centos 6 application menu.

### Actual behaviour
Desktop sync client don't have an application icon in the Centos 6 application menu.

![cursor_and_centos_64-bit_6_6](https://cloud.githubusercontent.com/assets/214010/8756755/d617feee-2cd4-11e5-91e8-28c7a10dcef3.png)

### Steps to reproduce
1. Install ownCloud desktop sync client
2. Open Centos 6 application menu

### Client configuration
Client version:
1.8.4

Operating system:
Centos 6.6 64bit

OS language:
EN

@dragotin Who can bring back ownCloud desktop sync client icon in Centos 6 application menu? /cc @MorrisJobke 

In Centos 7, everything works as expected:

![cursor_and_centos_64-bit_7](https://cloud.githubusercontent.com/assets/214010/8756797/1ee16dfe-2cd5-11e5-9f03-b14a1cf196eb.png)

00003521

**Comment by guruz** [comment]
If you launch the client with ```--logfile -``` does it show the Qt version used in log?
(Alternatively see which Qt version is installed)

Is there a ```sni-qt-``` package for CentOS?

**Comment by jnweiger** [comment]
Guruz, I cannot find sni-qt anywhere.
sni-qt exists since fedora:21, but centos:7 correspond to fedora:19, they both don't have that.

Are you saying your see sni-qt on centos:7, but miss it only on centos:6?

If we need that package, the only option I see is to build it ourselves

**Comment by danimo** [comment]
@guruz this is not about the system tray icon, but simply about the location/name of the icon referenced by the desktop file. This is completely different in CentOS 6 and 7 due to the fact that we ship our own Qt wrapper.

**Comment by jnweiger** [comment]
I've set up a build environment for building sni-qt here:
https://build.opensuse.org/package/show/isv:ownCloud:desktop/sni-qt

It fails for CentOS6 with this error message:
"nothing provides kde4-filesystem, nothing provides pkgconfig(dbusmenu-qt),"

**Comment by danimo** [comment]
@jnweiger Forget qt-sni. It's not related to this problem. Please talk to me in case of questions.

**Comment by danimo** [comment]
@michaelstingl How did you install this? If I use the repository, it just works (tm).

**Comment by michaelstingl** [comment]
@danimo I installed with: https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client on a clean Centos 6.

![software_opensuse_org__install_package_isv_owncloud_desktop___owncloud-client](https://cloud.githubusercontent.com/assets/214010/8809407/c20ec7b8-2fe8-11e5-9eea-83b43cc8fbd5.png)

**Comment by danimo** [comment]
@michaelstingl after a restart of the desktop, is the icon still missing?

**Comment by michaelstingl** [comment]
@danimo yes, still missing

**Comment by jnweiger** [comment]
![centos6-syncing](https://cloud.githubusercontent.com/assets/1108546/9818213/9cc21112-58a7-11e5-8b03-fe47b37da98b.png)

Looks good with owncloud-client 2.0.2

**Comment by jnweiger** [comment]
Um and as a more relevant screenshot here, the icon is also in the Applications->Accessories menu
![centos6-menue-icon](https://cloud.githubusercontent.com/assets/1108546/9819084/3692a71c-58ac-11e5-9a12-4e9733022ac1.png)

**Comment by dragotin** [comment]
thanks for testing @jnweiger

**Comment by michaelstingl** [comment]
@dragotin @jnweiger A user reported, this is still not fixed in 2.0.2. @jnweiger & @danimo weren't able to reproduce this on their systems (https://github.com/owncloud/client/issues/3473#issuecomment-123429357 & https://github.com/owncloud/client/issues/3473#issuecomment-139579986). I tested the 1.8.4 on a very clean Centos 6 (https://github.com/owncloud/client/issues/3473#issuecomment-123434199).

**Comment by michaelstingl** [comment]
@dragotin @danimo Can this be fixed with the next release?

**Comment by dragotin** [comment]
Hm, if we can not reproduce, that will be hard. We need to find the differences. @michaelstingl do I understand you correctly that you **can** reproduce it?

**Comment by michaelstingl** [comment]
@dragotin I can reproduce in my VM on a minimal CentOS 6 with only the GUI installed. It looks like installing some other applications fixes the problem, but this is not the solution we should recommend.

**Comment by jnweiger** [comment]
Is there a way to inspect enumerate tray icon objects in Linux? Yesterday night the icon was missing on one of my machines.

**Comment by guruz** [comment]
@jnweiger This is about start menu icon not tray(?)

**Comment by MorrisJobke** [comment]
> Hm, if we can not reproduce, that will be hard. We need to find the differences. @michaelstingl do I understand you correctly that you can reproduce it?

Am I wrong or are you in the same office? ;) maybe you can simply go over in the other room and maybe check ;)

**Comment by michaelstingl** [comment]
@MorrisJobke I need to check again. I triggered a new branded build and I will check soon…

**Comment by michaelstingl** [comment]
@MorrisJobke It looks fixed now. I tested in the exact same environment a in my initial post (https://github.com/owncloud/client/issues/3473#issue-95740542) with the regular client:

![cursor_and_centos_64-bit_6_6](https://cloud.githubusercontent.com/assets/214010/11221505/cc19965e-8d65-11e5-9de3-4f980e616e3f.png)

I will ask the user to test with their branded client.
