### ISSUE TITLE
[Linux] File watchers fail to work on symlinked folder

### ISSUE THREAD

**Issue by Vectrex** [owncloud/client#3475]
OS: Ubuntu 14.04, Client 1.8.4, Nautilus extension 1.8.4, Server 8.1 (though it seems as if the server isn't even contacted), all proxy options tried:
- 800kB file copied to local owncloud folder
- Nautilus extension marks it as "not synced"
- client reports nothing under "last changes" ("letze Änderungen"), file just sits there forever (10min+)
- the .csync_* files and .owncloudsync.log files are left untouched
- logging and off in the client does the trick and file gets synced immediately
- deleting the file is again not recorded by the client and requires a restart or logout/login of the client
- a subsequent complete restart of the client **occassionaly** seems to solve the problem for a few minutes (or a few uploads), then it is back to waiting

Edit:
- the synced folder is a symlink - though it has been this way for quite some time and I didn't notice these issues with 1.8.3
- changing an already existing file exposes exactly the same behaviour - no syncing, no touching of .csync_* files; however, a .~lock.* file is created

**Comment by guruz** [comment]
if you start with ```owncloud --logfile -``` do you see any file watcher events triggered?
(Can also paste the log here if you need help interpreting..)

**Comment by Vectrex** [comment]
Upon start the log file is filled with all sort of sync information. Emptied it. Copied two files to the watched folder. Waiting... Log file stays empty. It might sync later - I'll report back (along with the log file produced during startup).

**Comment by guruz** [comment]
Which package of the client did you use?
On which kind of filesystem is the sync dir?

**Comment by Vectrex** [comment]
dpkg -s owncloud-client

Package: owncloud-client
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 1974
Maintainer: Jürgen Weigert <jw.com>
Architecture: amd64
Multi-Arch: same
Version: 1.8.4-1
Depends: libc6 (>= 2.14), libgcc1 (>= 1:4.1.1), libowncloudsync0 (= 1.8.4-1), libqt4-dbus (>= 4:4.5.3), libqt4-network (>= 4:4.5.3), libqt4-xml (>= 4:4.5.3), libqtcore4 (>= 4:4.8.0), libqtgui4 (>= 4:4.7.0~beta1), libssl1.0.0 (>= 1.0.0), libstdc++6 (>= 4.4.0), owncloud-client-l10n, libqt4-sql-sqlite
Description: The ownCloud sync client - github.com/owncloud/client
...

Build installed from download.opensuse.org
File system is ext4.

**Comment by ckamm** [comment]
@Vectrex Do you still experience the problem? I'd bet that "the synced folder is a symlink" is relevant. Maybe the client's file watchers fail to work correctly in that case. What exactly is your setup like? So ~/owncloud is a symlink to ~/otherfolder?

**Comment by ckamm** [comment]
Yes, I can reproduce the problem: when I symlink ~/ownCloud to ~/sym-owncloud the file watchers don't notice any changes.

**Comment by guruz** [comment]
FYI @danimo

**Comment by Dianafg76** [comment]
@Vectrex Could you try this version, http://download.owncloud.com/desktop/daily/ownCloud-2.1.1.3024-nightly20160112.pkg.tbz, please
Thanks

**Comment by Vectrex** [comment]
@Dianafg76 Sorry - Linux machine here; can't use OSX packages. If available I'd prefer a .deb-package.

**Comment by guruz** [comment]
@Vectrex https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3Anightly&package=owncloud-client
:)

**Comment by Dianafg76** [comment]
@guruz thanks and sorry :)

**Comment by Vectrex** [comment]
Smoke test looks good.
Tried a new upload with the 2.1.0 version and had the expected "no immediate reaction"; updated to 2.1.1; initial sync went well, adding a new file triggered immediate response. Same with deleting files.

**Comment by Dianafg76** [comment]
@Vectrex Thank you for the testing
