### ISSUE TITLE
owncloud desktop client v1.8.4 forgetting to sync

### ISSUE THREAD

**Issue by sagar-srivastava** [owncloud/client#3476]
I just upgraded my desktop client 2 days ago, to the latest version and initial sync worked fine- but client no more sync automatically when server has a file change. In past when I changed my files on the server, it automatically synced them within 15 seconds and now it does not sync at all until I press the 'pause' and 'resume' button. My server is v8.1.

I have noticed the client detects and syncs correctly if I add a file locally in owncloud folder.

**Comment by sagar-srivastava** [comment]
interestingly, i could not recreate this issue after a restart of the client. I am still pasting the data as per the format ( although without logs)
### Expected behaviour
when files are changed on the server through oc web interface, the desktop client should automatically detect the change in less  than a minute and sync - used to happen on previous version).

### Actual behaviour
owncloud desktop client v1.8.4 forgetting to sync- does not detect any change for hours. until 'pause' and 'resume' buttons are pressed

### Steps to reproduce
1. upgraded Desktop client to the newest version v1.8.4 (build 5267) 
2. 
3. 

### Server configuration
Operating system: Debian "8 (jessie)"

Web server: Apache/2.4.10 (Debian)

Database: mysql 5.5.43-0+deb8u1 (Debian)

PHP version: 5.6.9-0+deb8u1

ownCloud version: owncloud-8.1.0

Storage backend: local filesystem

### Client configuration
Client version: version v1.8.4 (build 5267)

Operating system: Windows 8.1 pro

OS language: US English

Installation path of client: C:\Program Files (x86)\ownCloud

**Comment by ogoffart** [comment]
Hi, I will need to have a log or a way to reproduce this problem.

**Comment by guruz** [comment]
@sagar-srivastava Do you remember if you sleep/hibernated your machine in between?
Changed networks?

**Comment by sagar-srivastava** [comment]
No I didn't hibernate

**Comment by wawshorty** [comment]
Hi I thick I have nearly the same problem. My prost from owncloud forum

I've already updated my cloud to 8.1. Now the desktop-client was updated form 1.8.3 to 1.8.4 automatically. Everything seems to be fine. I' have several clients (all on windows-systems). But one of the clients only seems to be fine. This client shows in taskbar an ok (green) but in application a busy (blue) icon. I changed data in cloud but the changes will not be synchronized. All other installed clients do that. So I reinstalled this client but the effect was the same. If I downgrade the client to 1.8.3 the data will be synchronized successfully. The only difference is, that the downgraded client is connected by using of a proxy.

I cannot attache the logfiles but by using this link you can download the files.
https://forum.owncloud.org/viewtopic.php?f=14&t=29424#p92244

**Comment by guruz** [comment]
@wawshorty @sagar-srivastava  Have you seen my comment here: https://github.com/owncloud/client/issues/3969#issuecomment-155419445
Maybe you can help out testing..

**Comment by sagar-srivastava** [comment]
I am sorry.since then, I have upgraded my server as well as my client and I
no more have this problem.So I cannot recreate this issue.

**Comment by guruz** [comment]
OK thanks!

@wawshorty if you follow up let's do it on https://github.com/owncloud/client/issues/3969#issuecomment-155419445

**Comment by wawshorty** [comment]
Oh sorry, I have olso upggraded my server and all my clients. After that no such problems occur.
