### ISSUE TITLE
sync client related operation files in wrong directory on windows

### ISSUE THREAD

**Issue by CaptionF** [owncloud/client#3478]
Sync client 1.8.4. 
Windows 7;

The operation files of the sync client are currently in the root directory of the sync folders.
![sync-client-operationfiles_wrong_place](https://cloud.githubusercontent.com/assets/10551219/8772075/f858bf52-2ec8-11e5-9b3b-a95a6a44e3fb.png)

On windows however, there is a standard for operation files to be separated from the data files.
The standard requires to put the files into 
C:\Users\<user_name>\AppData\Local\ownCloud\

This may be related to https://github.com/owncloud/client/issues/3445
but is a separate issue.

**Comment by ogoffart** [comment]
Because of the way the sync engine work, the database has to be in the sync folder.
