### ISSUE TITLE
After migrating server I get a lot of conflicts on files changed during migration

### ISSUE THREAD

**Issue by enricocanino** [owncloud/client#3480]
NB on the forum said me to post here the issue...

Hello everybody, I get a strange issue, during migrating an Owncloud server.

This is the scenario:
-owncloud server 8.0.4 at www.somehost.tld/cloud/
-owncloud client 1.8.4.5267 (but I have tested various other versions)

after the server migration, following step by step Owncloud documentation:
-put owncloud in maintenance mode
-backup all data directory
-backup all database
-setup new server
-install the same server version 8.0.4
-setup config.php only for server name that now is cloud.somehost.tld
-put the new server in maintenance mode
-restore data directory
-restore database

Well... accessing via web interface works all very very fine, but if I change the account on desktop client, it starts to download all files again and mark as conflict those files changed during the migration.

The only one thing that was changed is the hostname (obviously also the ip address).

I am confused... If I propagate this migration to all clients I will get a lot of traffic and a lot of file in conflict...

:-(

I have also tried to delete csync.db on client side.... whitout success, it syncs all again.

Any ideas?

Thanks in advance.

Best regards.

**Comment by guruz** [comment]
Did you make sure the mtime of the files in the new server are same as on old server?
(I wonder did the file system type change?)

**Comment by enricocanino** [comment]
Yes, I am sure, the mtime are the same.

**Comment by enricocanino** [comment]
Only for the directory, obviously, are not the same.

**Comment by enricocanino** [comment]
Filesystem type was changed because old server was in an hosting platform, new server is a linux centos

**Comment by guruz** [comment]
@enricocanino Is it really ALL files it wants to redownload?

The only explanation then I would have is that a different file system type leads the server to think that the file changed and then create a new Etag

CC @PVince81 @icewind1991 Is there something else with regards to ETag computation that could trigger this?

> If I propagate this migration to all clients I will get a lot of traffic and a lot of file in conflict...

btw, conflicts will only be created for files that differ

**Comment by enricocanino** [comment]
| btw, conflicts will only be created for files that differ

Yes, but if I have 50 users, and they will modify 50 files, I will get 2500 conflict to modify manually...

If any user has 5 GB, and will download all files... the traffic will be very big... estimated 250 GB at the same time.

**Comment by enricocanino** [comment]
Thanks to all, I will investigate and, probably, will let download all again...
Best regards.

**Comment by dragotin** [comment]
@enricocanino can you paste a few lines with files that got a conflict from the file  ```.owncloudsync.log``` That would tell us exactly why it was conflicting.

**Comment by enricocanino** [comment]
@dragotin 
Thank you, because I actually am investigating why file mtime differ by some seconds from the original installation, please, wait for a reply later.

Thanks again.
