### ISSUE TITLE
Mac client asks to updated immediately after installing the update

### ISSUE THREAD

**Issue by dwt** [owncloud/client#3481]
Hi there,

it seems your acceptance test suite is missing a test that checks that after installing an update, that same update is not tried to install again. Seeing that this bug has happened again in not too many months, now should be the time to add this test and ensure that this problem happens never again in the future.

This is Mac Desktop Sync client 1.7.1 (build 1655)

**Comment by danimo** [comment]
@dwt 1.7.1 is not the latest version. Are you sure it is not trying to offer a later version (it should offer 1.8.4)?

**Comment by danimo** [comment]
@dwt "it seems your acceptance test suite is missing a test that checks that after installing an update, that same update is not tried to install again."

Please describe exactly what happened.

**Comment by dwt** [comment]
Hi there,

> @dwt <https://github.com/dwt> "it seems your acceptance test suite is missing a test that checks that after installing an update, that same update is not tried to install again."
> Please describe exactly what happened.
> 
I had that version installed, then Owncloud offered me an update (on mac). After the update was installed, the version didn’t change, and the update was offered again.

I suspect you didn’t change the version field in the delivered binary, or the download path actually points to an old version. (or something else with similar outcome).

So, do you have an (automated) acceptance test that checks that the installer works correctly and that it doesn’t immediately try to install another update? If there is no automation, did you guys actually try to update a mac to the latest release via the integrated online updater?

Regards,
Martin

**Comment by dragotin** [comment]
@dwt: If the update fails it will obviously try to install it again. Let's find out why it fails. Can you provide us with a logfile?

**Comment by dwt** [comment]
> Am 23.07.2015 um 10:38 schrieb Klaas Freitag <notifications@github.com>:
> 
> @dwt <https://github.com/dwt>: If the update fails it will obviously try to install it again. Let's find out why it fails. Can you provide us with a logfile?
> 
Which log file would you like?

Regards,
Martin Häcker

**Comment by dragotin** [comment]
@dwt please start the client with ```--logfile filename``` and wait until it downloaded the new version and tried to install. Send that logfile please.

**Comment by dwt** [comment]
Sadly not reproducible anymore. I set the auto updater to skip this update to actually be able to work while the bug persists, but even removing the 'SUSkippedVersion' key from the preferences did not reproduce the behavior.

Did you already deploy a fix from somewhere else or do I need to remove another preferences key to reproduce this again?

**Comment by guruz** [comment]
Let's reopen this if it can be reproduced
