### ISSUE TITLE
[Multiaccount] In MAC, You can use the "Share with ownCloud " if you select the folder ROOT 

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3482]
### Steps to reproduce
1. Open your ownCloud desktop client
2. Go to Open Folder "ownCloud"
3. If you select the folder Root (onwCloud)
4. Right click

### Expected behaviour
You should not have the option "Share with ownCloud", realed con #3463 

### Actual behaviour
You have the option "Share with ownCloud"
![screen shot 2015-07-21 at 15 05 25](https://cloud.githubusercontent.com/assets/12032058/8801310/f234fe3c-2fb9-11e5-8de3-7048e7bb9af0.png)

### Server configuration
Desktop v ownCloud-2.0.0.2551-nightly20150721.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by rullzer** [comment]
Yes that should not be possible! Let me take a look.

**Comment by rullzer** [comment]
Quick fix in #3495
