### ISSUE TITLE
[Multiaccount] In MAC, You can use the "Share with ownCloud " if you select the folder ROOT and introduce de Password and Set, appears error 403

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3483]
### Steps to reproduce

  1  Open your ownCloud desktop client
  2  Go to Open Folder "ownCloud"
  3  If you select the folder Root (onwCloud)
  4  Right click on the Folder Root (onwCloud)
  5  Select "Share with ownCloud"
  6  Introduce de Password
  7  Press Enter

### Expected behaviour
You should not have the option "Share with ownCloud"

### Actual behaviour
Appears an error: OCS API error code: 403, related to #3463 

![screen shot 2015-07-21 at 15 22 00](https://cloud.githubusercontent.com/assets/12032058/8801623/51df3724-2fbc-11e5-898c-8fde39d59065.png)

### Server configuration
Desktop v ownCloud-2.0.0.2551-nightly20150721.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by rullzer** [comment]
Well it is not possible to share the root. So this should be fixed when #3483 is fixed.

**Comment by rullzer** [comment]
Quick fix in #3495

**Comment by rullzer** [comment]
Should be fixed by #3495
