### ISSUE TITLE
Choose what to sync: show also local, not syhchronized, content

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/client#3484]
Add a very huge huge folder with many subfolders.
Now try to disable some folders that are not yet synced: They are not there.
It is necessary to exclude these directories before the first sync to avoid that they are added at all.
So they should be kept locally but never ever being synced and therefore are not watched or discovered.

Or am i misunderstanding the function?

**Comment by guruz** [comment]
@tobiasKaminsky Is this a duplicate of https://github.com/owncloud/client/issues/2465 ?
if yes could you please comment there and close this issue here?

**Comment by tobiasKaminsky** [comment]
You are right. Although I have searched, I must have overlooked it...
Thank you!

**Comment by guruz** [comment]
OK :) Please also comment there to create some noise.
