### ISSUE TITLE
ownCloud client starts before Plasma desktop is ready

### ISSUE THREAD

**Issue by sudhirkhanger** [owncloud/client#3485]
On a new install of Fedora 22 Plasma desktop ownCloud client starts way too early. It starts disconnected and un-minimized. I am using the latest version from OBS.

Please do let me know if you need more information.

Thanks.

**Comment by danimo** [comment]
> On a new install of Fedora 22 Plasma desktop ownCloud client starts way too early

Plasma starts it at its own discretion. So it cannot start 'too early'.

> It starts disconnected.

Does it connect eventually? It should. Otherwise, it's a separate bug.

> and un-minimized.

That's a duplicate of #3273

**Comment by sudhirkhanger** [comment]
It does connect on its own. There's no functional problem. I suppose un-minimized start is the culprit that makes it noticeable.
