### ISSUE TITLE
[Mac OS X] [10.11]? [2.0.0] Wizard don't create default sync folder

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#3492]
### Expected behaviour

Wizard should be able to create default sync folder without further configuration.

### Actual behaviour

<img width="615" alt="cursor_and_os_x_10_11_ob_data" src="https://cloud.githubusercontent.com/assets/214010/8852512/fb80e012-3155-11e5-828e-3eeace8d2171.png">

### Steps to reproduce
1. Install ownCloud-2.0.0.2559-nightly20150723.pkg on Mac OS X 10.11
2. Run owncloud.app
3. Enter server URL and credentials

### Client configuration
Client version:
ownCloud-2.0.0.2559-nightly20150723

Operating system:
Mac OS X 10.11 Beta (15A226f)

OS language:
EN

Installation path of client:
default

**Comment by Dianafg76** [comment]
@ogoffart I tested this issues, and is working. 
Desktop v ownCloud-2.0.0.2573-nightly20150729.pkg , OS XY v 10.10.3

**Comment by Dianafg76** [comment]
I close the issue
