### ISSUE TITLE
Linux client 1.8.4 unknown error/operation canceled

### ISSUE THREAD

**Issue by cislo78** [owncloud/client#3493]
Fresh Fedora 22 install, owncloud client sync some files and then stops saying unknown error and operation canceled.
After a few minutes sync operation restart, sync a few files more and than gives same error.
I started the client with owncloud --logwindow and see this:

0x1582370 unknown: QIODevice::write: device not open

0x109c7c0 unknown: QString::arg: Argument missing:  "file path... file not synced due to errors. Check log for details." , 5

On a windows machine the client works without any issue.
Thanks

**Comment by guruz** [comment]
If you enable HTTP Keep-Alive on your webserver and set KeepAliveTimeout and MaxKeepAliveRequests to a high number, does it work?

**Comment by cislo78** [comment]
thanks for your reply, i'll do what you suggest on the server and i'll let you know.

**Comment by cislo78** [comment]
OMG! you did the trick!! Thank you so much for making me feel such a newbie... :-) :-)
Oh, right, i'm a newbie :-)
Anyway, I excluded the server from my problems because the windows client worked well but the fact is that i was awfully wrong!
Thank you again!

**Comment by guruz** [comment]
@cislo78 Hey, no, don't worry :-) it's still the clients (or let's say Qt, which the client is using) fault because it does not handle it. But good to hear the workaround works for you for now :)

**Comment by guruz** [comment]
FYI @dragotin @danimo
