### ISSUE TITLE
[Multiaccount] in MAC, the option "Edit Ignored Files" it is not working very well

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3496]
### Steps to reproduce
1. You have a file, call qa.txt with icon Green
2. Right click in Icon oC 
3. Click in "Settings..."
4. Click in "General"
5. Click in "Edit Ignored Files"
6. Click in "Add"
7. And write a new ignore pattern: *.txt
8. Click OK
9. Select the option "Allow Deletion" 
10. Click OK
11. Wait to sync

### Expected behaviour
The two icons should be changed to yellow

### Actual behaviour
The file call qa.txt continues with the icon green, and if you copy the same file the icon change to yellow
![screen shot 2015-07-24 at 10 52 45](https://cloud.githubusercontent.com/assets/12032058/8871042/a580547a-31f2-11e5-9a28-be27b02389a0.png)

### Server configuration
Desktop v ownCloud-2.0.0.2559-nightly20150723.pkg in MAC
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
I tested this issue, and the result is the same
![screen shot 2015-10-28 at 08 38 36](https://cloud.githubusercontent.com/assets/12032058/10782303/607a704c-7d4f-11e5-8722-c595615acc67.png)

Desktop v ownCloud-2.1.0.2833-nightly20151028.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

**Comment by ogoffart** [comment]
@Dianafg76  This works for me now on windows and linux.
Are you sure you only have one running client?

**Comment by Dianafg76** [comment]
@ogoffart if you wait a bit , the icons change to yellow both
![screen shot 2015-10-28 at 09 52 54](https://cloud.githubusercontent.com/assets/12032058/10783661/b231de3e-7d59-11e5-8179-6f7b5fd5800b.png)

Closed
