### ISSUE TITLE
Activity tab "copy"  => Log is not parseable

### ISSUE THREAD

**Issue by jzee** [owncloud/client#3498]
the log that is copied to the clipboard with the copy button is badly formatted:
there are no separators between fields and padding appears to happen with spaces.

Example:

24.07.15 18:52:0**3S**HARENAME/WITH/A/VERY/LONG/PATH/AND/FILENAME/THAT/STRETCHES/ON/FOR/A/WHILE.EX**To**wnCloud       Uploaded       18 KiB    

(missing separators in emphasized in **bold**)
This prevents parsing with scripts for error reporting or pasting into a spreadsheet

Expectation:
1) The fields should be comma-separated or at least, for human readability, use tab separators as spaces are allowed in filenames.
2) The separators should be consistent and independent from the path or filename length

**Comment by ckamm** [comment]
This now uses comma as a separator. I've also adjusted field widths a bit to be easier to read.

**Comment by Dianafg76** [comment]
I tested this issue and now the fields are separated by commas. But the separators should be consistent , we have a lot of space between commas             
```
mac1@XXXXXXXXXXX,      Thu Dec 10 08:13:29 2015 GMT,               /sharing folder,                                  You created sharing folder, share by link, new folder11 and 3 more, 
10/12/15 09:13:25,                                                             123,                           rc1,     Downloaded, 
```

**Comment by ckamm** [comment]
@Dianafg76 Someone had added the whitespace padding intentionally. I assumed this is the way it's intended to work, but added the separators. I think this is good enough.
