### ISSUE TITLE
Duplicate Quit entry in system tray menu

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#3500]
There are two "Quit" entries in the system tray menu:
![client-duplicate-quit](https://cloud.githubusercontent.com/assets/277525/8889013/31047196-32c7-11e5-94af-53825d128e62.png)

Both seem to close the client.

### Versions
owncloud-client-1.8.4-2.5.x86_64
openSUSE Factory x86_64
plasma5-workspace-5.3.2-91.6.x86_64

**Comment by ogoffart** [comment]
I've got only one quit entry.

**Comment by ogoffart** [comment]
ah ok, it's plasma who automaticaly add a quit entry

**Comment by dragotin** [comment]
hrm. What can we do about that?

**Comment by ckamm** [comment]
@ogoffart Do you have any idea where this could be happening? I looked at the dbusmenu-using code in plasma-workspace, but didn't see anything relating to it.

**Comment by dragotin** [comment]
Also, the plasma Quit asks back if the user *really* wants to quit.

**Comment by dragotin** [comment]
Upstream bug: https://bugs.kde.org/show_bug.cgi?id=354991

**Comment by PVince81** [comment]
I upgraded to plasma 5.4.3 and with sync client 2.1.0 the second entry is gone
