### ISSUE TITLE
"Recent changes" menu entry does nothing on Linux

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#3501]
### Steps
1. Change a local text file, wait for upload
2. Change a remote file over the web UI, wait for the client to download it
3. Right click on sys tray icon
4. Click "Recent changes"

### Expected result
Something happens, no idea what, I just discovered this today :smile: 

### Actual result
The menu closes, nothing happens.

### Versions
owncloud-client-1.8.4-2.5.x86_64
openSUSE Factory x86_64
plasma5-workspace-5.3.2-91.6.x86_64

**Comment by guruz** [comment]
(Note that if this was not done yet (because it was not for the SSLButton before we changed it) we should also change this to lazy creation)

**Comment by ckamm** [comment]
@PVince81 It works for me and looks like this:

![progress1](https://cloud.githubusercontent.com/assets/833306/10480265/84f47a8a-7269-11e5-8c1a-5461fc7f0813.png)

Maybe this is a tray issue again? Could you try again with the 2.0.2 rc?

**Comment by PVince81** [comment]
Seems there is still no package for 2.0.2rc in OBS:
```
i | owncloud-client             | package    | 2.0.1-3.5      | x86_64 | (System Packages)             
v | owncloud-client             | package    | 2.0.1-3.7      | x86_64 | isv:ownCloud:desktop          
v | owncloud-client             | package    | 2.0.0~rc2-1.10 | x86_64 | isv:ownCloud:community:testing
v | owncloud-client             | package    | 2.0.1-3.7      | i586   | isv:ownCloud:desktop          
```

I'll try with the git version instead.

**Comment by PVince81** [comment]
there is also no 2.0.2rc tag in github. Did you mean v2.0.2-beta1 ?

**Comment by PVince81** [comment]
I tried git master (05eee16959ab7cc485bee9c273392b84ba57eae8) and the submenu still doesn't show, same as before.

**Comment by dragotin** [comment]
@PVince81 we did not release a 2.0.2 RC yet. For getting the latest pre 2.0.2 version, please build the branch called 2.0.

**Comment by ogoffart** [comment]
This works for me with master.  (tested on linux and windows)

**Comment by guruz** [comment]
Possibly related: https://github.com/owncloud/client/issues/3889

**Comment by ckamm** [comment]
@PVince81 I don't know what's going on. I still believe this is related to the tray integration. Could you check what happens when you start your owncloud client while `XDG_CURRENT_DESKTOP=xfce` is set?

**Comment by ckamm** [comment]
@PVince81 ping

**Comment by PVince81** [comment]
With 8.2.1 the menu is still empty with Plasma 5. Well it's not even a submenu but just a single item.

However if I start it with XDG_CURRENT_DESKTOP=xfce there is a submenu.

So maybe something is wrong about the way how the submenu is registered in the case of a Plasma environment ?

**Comment by ckamm** [comment]
@PVince81 Yes, it seems like a bug either in Qt or in plasma with respect to how tray submenus are communicated. Do the other submenus (when you have multiple accounts configured) work?

**Comment by PVince81** [comment]
Oh, there are other submenus ? I never saw them.
So => no :frowning:

**Comment by ckamm** [comment]
@PVince81 :(
Then it's the same as #4135, that ticket links to a bug upstream.
