### ISSUE TITLE
Can't connect to server running on non-standard port (Linux)

### ISSUE THREAD

**Issue by davorb** [owncloud/client#3502]
### Expected behaviour
I should be able to connect to OwnCloud

### Actual behaviour
I get an error message saying "Error: wrong credentials".

### Steps to reproduce
1. Run the official docker image on port 81 by typing ```docker run -d -p 81:80 --name owncloud owncloud:latest```

2. Point your browser to ```http://1.2.3.4:81``` and finish setting up your account. (verify that you have the correct password by logging out and in again)
3. Start the owncloud client on linux and enter the server address. In my case it's ```http://192.168.1.13:81``` ![snapshot1](https://cloud.githubusercontent.com/assets/798427/8889767/12be4af6-32e8-11e5-8b65-f8a6d85dd0fb.png)
4. Enter your username and password and press next.
![snapshot1](https://cloud.githubusercontent.com/assets/798427/8889772/440b95e6-32e8-11e5-94e6-9f43835c52c5.png)

### Server configuration
I'm using the official Docker image ``owncloud:latest```.

### Client configuration
Client version:
```
ownCloud version 1.6.4
```
Operating system:
```Linux fatboy 3.19.0-22-generic #22-Ubuntu SMP Tue Jun 16 17:15:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux```

OS language: US English

Installation path of client:
```
▶ whereis owncloud
owncloud: /usr/bin/owncloud /usr/share/owncloud /usr/share/man/man1/owncloud.1.gz
```
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log: https://gist.github.com/davorb/6d9115f567f377bd71c3

3. ownCloud log (data/owncloud.log): https://gist.github.com/davorb/000572e2b7d6c3582bd9

**Comment by RealRancor** [comment]
Please fill out the issue template like described here: https://github.com/owncloud/client/blob/master/CONTRIBUTING.md#bug-reporting-guidelines (linked in the yellow box when creating a new issue).

**Comment by davorb** [comment]
@RealRancor done!

**Comment by RealRancor** [comment]
@davorb Thanks

> ownCloud version 1.6.4

Please upgrade to at least 1.7.0 and the error should be gone.

**Comment by davorb** [comment]
That fixed it. Thanks.
