### ISSUE TITLE
Windows sharing plugin should not allow sharing of sync root

### ISSUE THREAD

**Issue by rullzer** [owncloud/client#3506]
To extend #3495 the sharing plugin should not allow sharing of the remote root since the server does not allow that.

#3495 already makes sure the sharing dialog does not open but for better UX the menu entry should also not be clickable.

**Comment by jturcotte** [comment]
I don't see the option in the context menu on Windows, possibly since the REGISTER_PATH ends with a slash and the path we get in the extension doesn't, though I havent verified why.
