### ISSUE TITLE
Client windows long time too lauch with 85Go

### ISSUE THREAD

**Issue by Timo86** [owncloud/client#3510]
Hi,
I recently install the last version of owncloud 8.1.0 client (1.8.4) and i sync 85go off excel document. But now when i start the client it's take a long time to refresh list off file .... I'm asking if a solution exist to reduce this time ?
The long step is "preparing to sync"(more than 3hours), sync is pretty fast.

The server run in Intel Xeon 16Go (RAM), 2To RAID 1. No caching module, it's seem there are not a huge process run when i scan folder with the client.

I don't understand log (F12) so i paste some part of it :-1: 

07-28 11:57:08:216 0x3d4c790 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (La procédure spécifiée est introuvable.)
07-28 11:57:08:226 0x3d4c790 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

07-28 11:57:08:226 0x3d4c790 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
07-28 11:57:24:252 0x3d4c790 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
07-28 11:57:24:252 0x3d4c790 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://myURL.fr" + "/"
07-28 11:57:35:353 0x3d4c790 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for "https://myURL.fr" + "/"
07-28 11:57:35:968 0x3d4c790 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag
07-28 11:57:56:001 0x62514a0 csync_statedb_get_below_path: 26 entries read below path COMMANDE/CLIMASOL from db.
07-28 11:57:56:001 0x62514a0 csync_walker: directory: ownclouds://myURL.fr/remote.php/webdav/COMMANDE/CLIMAVENETA [file_id=00001929ocslokqp3tx1]
07-28 11:57:56:011 0x62514a0 _csync_detect_update: Database entry found, compare: 1255335182 <-> 1255335182, etag: 55773778e33a3 <-> 55773778e33a3, inode: 0 <-> 22435300, size: 0 <-> 0, perms: RDNVCK <-> RDNVCK
07-28 11:57:56:011 0x62514a0 _csync_detect_update: Reading from database: COMMANDE/CLIMAVENETA
07-28 11:57:56:011 0x62514a0 _csync_detect_update: file: COMMANDE/CLIMAVENETA, instruction: INSTRUCTION_NONE <<=
07-28 11:57:56:251 0x3d4c790 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
07-28 11:57:56:251 0x3d4c790 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://myURL.fr" + "/"

...

07-28 13:44:32:557 0x61e5520 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x61eadf8) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
07-28 13:44:32:557 0x61e5520 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x61eadf8) QObject(0x0)  0 false 3 0

If you need something else tell me.

**Comment by guruz** [comment]
What is 80Go or 85Go?

**Comment by Timo86** [comment]
85Go of data sorry

**Comment by tflidd** [comment]
Go is short for gigaoctet (octet=byte). 1Go = 1GB

**Comment by theCrazyBeard** [comment]
I too can confirm a similar issue.  I have approximately 17GB of data in my user folder and the sync client slows to a crawl after parsing through the first several folders.  As @Timo86 said, the sync itself happens rather quickly but the Discovery takes a long time.  Up to 30-40 minutes in my case.

**Comment by dragotin** [comment]
@theCrazyBeard @Timo86 could you guys count the number of files and directories that you sync and tell us?

**Comment by Timo86** [comment]
53 000 files and 11 000 folders

**Comment by theCrazyBeard** [comment]
28,161 Files, 1,891 Folders

**Comment by guruz** [comment]
Have you guys tried one of the 2.0 nightly builds?
We have a different directory discovery code there, maybe it helps?

http://download.owncloud.com/desktop/daily/

**Comment by theCrazyBeard** [comment]
Finally had a chance to get a nightly installed.  Crawling seems better but the actual syncing is still taking a long time to complete.  Most transfer speeds are running at less than 500 Bps.

**Comment by ogoffart** [comment]
the problem with the transfer speed is mostly a server problem.  
The version 2.1 further imrpoves the discovery speed. How long does it takes with the last daily?

**Comment by guruz** [comment]
@Timo86 Did you have a chance to test a daily/nightly build? How long does the discovery take? (with log disabled)

**Comment by guruz** [comment]
I'm closing this, please check if 2.1 is faster.

http://download.owncloud.com/desktop/daily/
