### ISSUE TITLE
Strange ".oC_bak" suffix on backup folder 

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#3512]
Just a small detail: When there was a previous ownCloud installation, during the setup process you are asked if you want to start anew (with backup) or merge local and server files. In the first case, the local ownCloud folder is backed up as `ownCloud.oC_bak`.

That is quite a technical name, and it would be cool to instead use ` (backup)` as suffix, making it `ownCloud (backup)`, or whatever the folder name was.

**Comment by Dianafg76** [comment]
I tested this issue, and is working
Desktop v ownCloud-2.0.0.2576-nightly20150730.pkg  
I close the issue

**Comment by jancborchardt** [comment]
@ogoffart thanks! :) (See the inline comment about the number for when a backup already exists.)
