### ISSUE TITLE
Instalation encoding problem and some missing translations

### ISSUE THREAD

**Issue by marcinmierzejewski1024** [owncloud/client#3514]
On attached image there is screen from installation owncloud from https://owncloud.com/download/#desktop-clients
![przechwytywanie](https://cloud.githubusercontent.com/assets/573420/8956184/86555bcc-35f3-11e5-906b-4c1954bb46f7.PNG)

there is encoding problem and also some untranslated strings, I'd happy to contribute and add them but in build directory all I found is some .qm binary files (builddir/share/owncloud/i18n/) and .ts xml files (sourcedir/translation), but when I changed polish translation file(client_pl.ts) and rebuild project
```
cmake...
make clean
make package
```
Installer doesn't change

**Comment by danimo** [comment]
The Windows installer translation is a different project: `/owncloud/client/admin/win/nsi/l10n` (creates po files). If you want to contribute translations though, please do not waste your time and contribute straight to https://www.transifex.com/projects/p/owncloud/translate/#de_DE/client-nsis, as we can only accept translations through transifex.

**Comment by marcinmierzejewski1024** [comment]
... but this not solve problem with encoding.

**Comment by danimo** [comment]
The installer is not yet UTF8, so we have a script which uses the respective windows codepage.

Please run `git cherry-pick 6d3f6073962ababee644e7cf113591ff5a231441`, then go to `admin/win/nsi/l10n` and run `bin/l10n.sh`

**Comment by marcinmierzejewski1024** [comment]
I also found missing polish language in nsis template file:
https://github.com/owncloud/client/blob/master/cmake/modules/NSIS.template.in

**Comment by danimo** [comment]
@marcinmierzejewski1024 db8b919099375af08744a91f3c0d303882c77079 has the fix, tonight's 2.0 daily build should have a polish translation (https://download.owncloud.com/desktop/daily/)

**Comment by danimo** [comment]
try https://download.owncloud.com/desktop/daily/ownCloud-2.0.0.5351-nightly20150804-setup.exe

**Comment by danimo** [comment]
I've verified with beta1 now and polish works.

**Comment by marcinmierzejewski1024** [comment]
ownCloud-2.0.0.5381-nightly20150810-setup.exe  - still problem with encoding.
propably this strings are not defined in project and comes from some nsi default translations.

![przechwytywanie](https://cloud.githubusercontent.com/assets/573420/9170443/2c8289ac-3f63-11e5-8868-e277cd315e14.PNG)
