### ISSUE TITLE
Test the branding migration with multi account

### ISSUE THREAD

**Issue by ogoffart** [owncloud/client#3515]
`accountmigrator.cpp`  do the migration from normal owncloud to the branded client.  It has not been tested with 2.0 yet. We need to make sure it still work, or  fix it, or get rid of the feature.

**Comment by dragotin** [comment]
I think we should try to keep it, it is useful if a branded version is rolled out but users had unbranded clients before.

**Comment by Dianafg76** [comment]
@ogoffart What are the steps to reproduce this?, Thanks

**Comment by ogoffart** [comment]
I don't really know.  It has something to do with installing some version of the cummunity client, then some version of the branding client and it should go and read the config of the community client and if the URL is the same it should import the account.

@dragotin must know what is the exact devliverable of the feature.

**Comment by guruz** [comment]
I think this was done once for @moscicki ?

**Comment by dragotin** [comment]
The feature is still missing in 2.0.0 - so nothing to test so far.

We're investigating if we still need it in 2.0.0

**Comment by rperezb** [comment]
If this were needed, please ping.
In the meantime, @davitol is going to check the upgrade of branded clients, from 1.8.4 to 2.0.0 with multiaccount enable and without it.

**Comment by dragotin** [comment]
There is no branding migration in 2.0.0 as @MTRichards agreed on.

**Comment by MTRichards** [comment]
right, no auto migration - but you should have to upgrade.

**Comment by davitol** [comment]
Upgrade 1.8.4 (single-account) :arrow_right: 2.0.0 (single-account) :white_check_mark: 
Upgrade 1.8.4 (single-account) :arrow_right: 2.0.0 (Multi-account) :white_check_mark:
