### ISSUE TITLE
Restriction in the theme for single account for branded client

### ISSUE THREAD

**Issue by ogoffart** [owncloud/client#3517]
Shoud some branded client have a restriction to avoid creating multiple accounts?

It can still make sens to have multiple accounts with a single server (several users on the same server)

Should we made it impossible to create account or delete account or edit account for some branded client?

@dragotin  @MTRichards

**Comment by MTRichards** [comment]
Let me repeat what you are saying so I understand it.

Multi-account should be something that can be turned off for branding, so only 1 account on 1 server was the design point. this of course works - right?

What I think you are asking is what about multiple accounts on a single server. I have not had that request so far to date from customers. This also seems a bit odd - I am sure I can think of a way for it to make sense, but I would wait until a customer makes the ask for it. So I would either enable multi account or disable it. nothing in the middle at this time.

>Should we made it impossible to create account or delete account or edit account for some branded client?

I think so, based on multi account being either on or off.

**Comment by phil-davis** [comment]
In my organization we have volunteers come for some number of years. They get a "personal" email account like phil.davis@example.com
Then they work in some job that has an email address for the job like hr.advisor@office.example.com
Then these email addresses also become ownCloud users. A typical person will want to put their own personal files in "phil.davis@example.com" account and their work stuff in "hr.advisor@office.example.com". This lets them separate their work and personal life, as well as making it easy to know what are the work files to hand over to the next person doing the job.
This is my use case for having multiple accounts set up in the client that actually go to the same ownCloud server.
I guess I don't care about branding, but maybe there will be other users who care about branding as well as this sort of use case.

**Comment by MTRichards** [comment]
@phil-davis Thanks for your use case. I love hearing about how this would be used in the field. 

I think this is a good example that should be handled by the desktop client as planned - I suppose I did not make that clear above. To be clear, you can choose to connect one client to two different accounts on the same ownCloud server, that should work no problem.

**Comment by ogoffart** [comment]
With the normal client (non-branded) you can, of course, create several account with different users on the same server.

This question is about branded client which have a restriction to one single server for example.

The current implementation of the multi account still let you create multiple accounts (but on the preconfigured server only).

The question is wether we need to add additional code to be able to restrict the number of account to 1 in the branding case.

**Comment by guruz** [comment]
* [ ] The toolbar (https://github.com/owncloud/client/issues/3516) needs to have the hostname part (second line) be left out if this branded option is enabled.

**Comment by rperezb** [comment]
I'd appreciate you ping me once this is implemented.
thx

**Comment by ogoffart** [comment]
There is now a Theme::singleAccount virtual function that can be overriden and set to true to hide the add account button.
