### ISSUE TITLE
[Windows installer] inconsistent use of newline ($\n) in translations

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#3519]
Most translations use "``$\n``" in "``$ConfirmEndProcess_MESSAGEBOX_TEXT``".

**German:**
https://github.com/owncloud/client/blob/v1.8.4/admin/win/nsi/l10n/German.nsh#L3
``StrCpy $ConfirmEndProcess_MESSAGEBOX_TEXT "${APPLICATION_EXECUTABLE} Prozess(e) gefunden, die gestoppt werden müssen.$\nWollen Sie, dass der Installer diese nun für Sie stoppt?"``

Some translations use "``\n``" or "``$\\n``" in "``$ConfirmEndProcess_MESSAGEBOX_TEXT``" which results in character artefacts in UI.

**Finnish:**
https://github.com/owncloud/client/blob/v1.8.4/admin/win/nsi/l10n/Finnish.nsh#L3
``StrCpy $ConfirmEndProcess_MESSAGEBOX_TEXT "Havaittiin sovelluksen ${APPLICATION_EXECUTABLE} prosessi (tai prosesseja) jotka pitäisi pysäyttää.\nHaluatko että asennusohjelma pysäyttää nämä puolestasi?"``

**Japanese:**
https://github.com/owncloud/client/blob/v1.8.4/admin/win/nsi/l10n/Japanese.nsh#L3
``StrCpy $ConfirmEndProcess_MESSAGEBOX_TEXT "${APPLICATION_EXECUTABLE} のプロセスを終了する必要があります。\nインストーラーがそのプロセスを停止してもよろしいですか？"
``

<img width="492" alt="client_uninstall_wizard_message" src="https://cloud.githubusercontent.com/assets/214010/8979400/9ddf292e-36a9-11e5-9454-15095030908d.png">

**Portuguese:**
https://github.com/owncloud/client/blob/v1.8.4/admin/win/nsi/l10n/Portuguese.nsh#L3
``StrCpy $ConfirmEndProcess_MESSAGEBOX_TEXT "Processos(s) ${APPLICATION_EXECUTABLE} em execução. Estes processos precisam de ser interrompidos.$\\nDeseja que o instalador os termine automaticamente?"``

**Thai:**
https://github.com/owncloud/client/blob/v1.8.4/admin/win/nsi/l10n/Thai.nsh#L3
``StrCpy $ConfirmEndProcess_MESSAGEBOX_TEXT "พบว่ากระบวนการ ${APPLICATION_EXECUTABLE} จะต้องหยุดทำงาน\nคุณต้องการติดตั้งเพื่อหยุดการทำงานเหล่านี้ของคุณ?"``

I volunteered for the Japanese language team in transifex to fix this, but this don't fix the general problem.

@dragotin found some documentation:
http://nsis.sourceforge.net/Docs/Chapter4.html#varstrings

@MorrisJobke 

00003607

**Comment by danimo** [comment]
@michaelstingl This needs to be fixed in transifex. And even if we do, tere is a good chance that translators will mess this up again.

@DeepDiver1975 Do we have some sort of LART for translators?

**Comment by MorrisJobke** [comment]
> @DeepDiver1975 Do we have some way to hint this to translators?

You can add a notice for translators like this:

```
// TRANSLATORS: text hint here
$l10n->t('text to translate');
```

That is how it works in PHP. I don't know if this is the same for C++.

**Comment by michaelstingl** [comment]
@danimo I fixed in Transifex. Will this fix make it into the next client release?

## Some feedback and suggestions for Transifex

1. There is a field for instructions [1] associated with source string and shared across all languages. This would be the perfect place to add hints to translators. 
2. The Transifex translation editor is not ideal. It hides the "``\n``" [2], which makes the orphaned "``$``" look very confusing.
3. I added some information as a comment [3], but this is not always visible.

<img width="1080" alt="owncloud___transifex_editor_and_skitch_and_core__irc_owncloud_com_" src="https://cloud.githubusercontent.com/assets/214010/9008228/13fbb614-3799-11e5-9f11-a4e3b9cb3084.png">

**Comment by DeepDiver1975** [comment]
> That is how it works in PHP. I don't know if this is the same for C++.

Qt has similar mechanisms: http://doc.qt.io/qt-5/i18n-source-translation.html section http://doc.qt.io/qt-5/i18n-source-translation.html

**Comment by DeepDiver1975** [comment]
> Will this fix make it into the next client release?

@danimo translation sync is operating on 1.8 branch for the installer - https://ci.owncloud.org/view/translation-sync/job/translation-sync-client-nsis

**Comment by danimo** [comment]
I fixed the source string that lacked the `$` prefix. Now while fixing the rest in transifex, the challenge seems to be to add a verbatim CR (carriage return). @DeepDiver1975 Any idea how to do that? The docs do not seem to provide a good answer.

**Comment by guruz** [comment]
@michaelstingl Did you try this? If not can we move this to 2.1.1?

**Comment by danimo** [comment]
This cannot be done in transifex, we need to enforce this after pulling the translations from there:

A script that prepends a `$` to `\n` and `\r` NOT preceded by a `$` will do nicely. the right path for that script is `owncloud/client/admin/win/nsi/l10n/bin`. Check the ci.owncloud.org translation job for the client for details: https://ci.owncloud.org/view/translation-sync/job/translation-sync-client-nsis/

**Comment by dragotin** [comment]
Yes, can do that. @cmonteroluque @mstingl ok to move it to next milestone?

**Comment by danimo** [comment]
+1 for moving. Fix should be simple simple, but I'd like a couple of nightly builds for assessing if it works as expected, and this does not justify to delay the release IMHO.

**Comment by cmonteroluque** [comment]
@dragotin @danimo Agreed, next milestone. Thank you

**Comment by dragotin** [comment]
Setting this to ReadyToTest, @michaelstingl volunteered to verify tomorrow. Thanks :)

**Comment by Dianafg76** [comment]
@michaelstingl Could you check this issue, please
Thanks

**Comment by michaelstingl** [comment]
still issues:


```
Searching 35 files for "\\"

/Users/Shared/ownCloud/Repositories/client/admin/win/nsi/l10n/bin/build_locale_nsi.py:
  103  
  104  def escapeNSIS(st):
  105:     return st.replace('\\', r'$\\')\
  106               .replace('\t', r'$\t')\
  107               .replace('\r', r'$\r')\
  108               .replace('\n', r'$\n')\
  109               .replace('\"', r'$\"')\
  110:              .replace('$$\\', '$\\')\
  111:              .replace('$\\n', r'$\n')
  112  
  113  

/Users/Shared/ownCloud/Repositories/client/admin/win/nsi/l10n/Portuguese.nsh:
    1  # Auto-generated - do not modify
    2  StrCpy $MUI_FINISHPAGE_SHOWREADME_TEXT_STRING "Mostrar notas de lançamento"
    3: StrCpy $ConfirmEndProcess_MESSAGEBOX_TEXT "Processos(s) ${APPLICATION_EXECUTABLE} em execução. Estes processos precisam de ser interrompidos.$\\nDeseja que o instalador os termine automaticamente?"
    4  StrCpy $ConfirmEndProcess_KILLING_PROCESSES_TEXT "A terminar os processos ${APPLICATION_EXECUTABLE}."
    5  StrCpy $ConfirmEndProcess_KILL_NOT_FOUND_TEXT "Não foi encontrado o processo a terminar!"

/Users/Shared/ownCloud/Repositories/client/admin/win/nsi/l10n/SpanishInternational.nsh:
    1  # Auto-generated - do not modify
    2  StrCpy $MUI_FINISHPAGE_SHOWREADME_TEXT_STRING "Mostrar notas de la versión"
    3: StrCpy $ConfirmEndProcess_MESSAGEBOX_TEXT "Se encontrarion ${APPLICATION_EXECUTABLE} proceso(s) que debe/n ser detenidos.$\"$\\n$\"¿Quiere que el instalador lo haga por usted?"
    4  StrCpy $ConfirmEndProcess_KILLING_PROCESSES_TEXT "Parando el proceso ${APPLICATION_EXECUTABLE}."
    5  StrCpy $ConfirmEndProcess_KILL_NOT_FOUND_TEXT "Proceso a detener no encontrado!"

7 matches across 3 files
```

**Comment by guruz** [comment]
@michaelstingl FYI if you want to re-test

**Comment by danimo** [comment]
@guruz That's just from merging 2.1 into master

**Comment by dragotin** [comment]
@michaelstingl can you verify this again with a recent 2.1.1 build? Thx.

**Comment by michaelstingl** [comment]
still the same issue:
(I tested https://github.com/owncloud/client/commit/54a278edb9c8108f72187cafd4c7ea1675698817)

```
Searching 35 files for "\\"

/Users/Shared/ownCloud/Repositories/client/admin/win/nsi/l10n/bin/build_locale_nsi.py:
  103  
  104  def escapeNSIS(st):
  105:     return st.replace('\\', r'$\\')\
  106               .replace('\t', r'$\t')\
  107               .replace('\r', r'$\r')\
  108               .replace('\n', r'$\n')\
  109               .replace('\"', r'$\"')\
  110:              .replace('$$\\', '$\\')\
  111:              .replace('$\\n', r'$\n')
  112  
  113  

/Users/Shared/ownCloud/Repositories/client/admin/win/nsi/l10n/Portuguese.nsh:
    1  # Auto-generated - do not modify
    2  StrCpy $MUI_FINISHPAGE_SHOWREADME_TEXT_STRING "Mostrar notas de lançamento"
    3: StrCpy $ConfirmEndProcess_MESSAGEBOX_TEXT "Processos(s) ${APPLICATION_EXECUTABLE} em execução. Estes processos precisam de ser interrompidos.$\\nDeseja que o instalador os termine automaticamente?"
    4  StrCpy $ConfirmEndProcess_KILLING_PROCESSES_TEXT "A terminar os processos ${APPLICATION_EXECUTABLE}."
    5  StrCpy $ConfirmEndProcess_KILL_NOT_FOUND_TEXT "Não foi encontrado o processo a terminar!"

/Users/Shared/ownCloud/Repositories/client/admin/win/nsi/l10n/SpanishInternational.nsh:
    1  # Auto-generated - do not modify
    2  StrCpy $MUI_FINISHPAGE_SHOWREADME_TEXT_STRING "Mostrar notas de la versión"
    3: StrCpy $ConfirmEndProcess_MESSAGEBOX_TEXT "Se encontrarion ${APPLICATION_EXECUTABLE} proceso(s) que debe/n ser detenidos.$\"$\\n$\"¿Quiere que el instalador lo haga por usted?"
    4  StrCpy $ConfirmEndProcess_KILLING_PROCESSES_TEXT "Parando el proceso ${APPLICATION_EXECUTABLE}."
    5  StrCpy $ConfirmEndProcess_KILL_NOT_FOUND_TEXT "Proceso a detener no encontrado!"

7 matches across 3 files
```

**Comment by dragotin** [comment]
The commit above fixes the wrong parts shown above. Closing hence. @michaelstingl fyi, feel free to reopen in case...

**Comment by michaelstingl** [comment]
Some things are still strange. Line breaks are missing in some languages.

```
Searching 41 files for "$$"

/Users/Shared/ownCloud/Repositories/client/admin/win/nsi/l10n/bin/build_locale_nsi.py:
  108               .replace('\n', r'$\n')\
  109               .replace('\"', r'$\"')\
  110:              .replace('$$\\', '$\\')\
  111               .replace('$\\n', r'$\n')\
  112               .replace('$\\\\n', r'$\n')

/Users/Shared/ownCloud/Repositories/client/admin/win/nsi/l10n/Italian.nsh:
   31  StrCpy $UNINSTALLER_REGISTRY_Detail "Scrittura delle chiavi di registro del programma di installazione"
   32  StrCpy $UNINSTALLER_FINISHED_Detail "Completato"
   33: StrCpy $UNINSTALL_MESSAGEBOX "Non sembra che ${APPLICATION_NAME} sia installato nella cartella '$INSTDIR'.$$\nVuoi continuare comunque (non consigliato)?"
   34  StrCpy $UNINSTALL_ABORT "Disinstallazione interrotta dall'utente"
   35  StrCpy $INIT_NO_QUICK_LAUNCH "Scorciatoia dell'avvio veloce (N/D)"

/Users/Shared/ownCloud/Repositories/client/admin/win/nsi/l10n/Japanese.nsh:
   31  StrCpy $UNINSTALLER_REGISTRY_Detail "ƒCƒ“ƒXƒg[ƒ‰[‚ÌƒŒƒWƒXƒgƒŠƒL[‚Ì‘‚«ž‚Ý"
   32  StrCpy $UNINSTALLER_FINISHED_Detail "I—¹"
   33: StrCpy $UNINSTALL_MESSAGEBOX "${APPLICATION_NAME} ‚Í'$INSTDIR'.$$@ ƒfƒBƒŒƒNƒgƒŠ‚ÉƒCƒ“ƒXƒg[ƒ‹‚³‚ê‚Ä‚¢‚Ü‚¹‚ñBƒGƒ‰[‚ð–³Ž‹‚µAi‚Ý‚Ü‚·‚© (”ñ„§)H"
   34  StrCpy $UNINSTALL_ABORT "ƒAƒ“ƒCƒ“ƒXƒg[ƒ‹‚ÍAƒ†[ƒU[‚É‚æ‚Á‚Ä’†Ž~‚³‚ê‚Ü‚µ‚½B"
   35  StrCpy $INIT_NO_QUICK_LAUNCH "ƒNƒCƒbƒN‹N“®ƒVƒ‡[ƒgƒJƒbƒg(N/A)"

/Users/Shared/ownCloud/Repositories/client/admin/win/nsi/l10n/Polish.nsh:
   30  StrCpy $UNINSTALLER_REGISTRY_Detail "Tworzê wpisy w rejestrze"
   31  StrCpy $UNINSTALLER_FINISHED_Detail "Zakoñczony"
   32: StrCpy $UNINSTALL_MESSAGEBOX "Nie wygl¹da na to ¿e ${APPLICATION_NAME} jest zainstalowane w katalogu '$INSTDIR'.$$ Kontynuowaæ mimo tego (nie zalecane)?"
   33  StrCpy $UNINSTALL_ABORT "Dezinstalacja przerwana przez u¿ytkownika"
   34  StrCpy $INIT_NO_QUICK_LAUNCH "Skrót na Pasku Zadañ (NIE DOTYCZY)"

/Users/Shared/ownCloud/Repositories/client/admin/win/nsi/l10n/Spanish.nsh:
   31  StrCpy $UNINSTALLER_REGISTRY_Detail "Escribiendo claves en el registro del instalador"
   32  StrCpy $UNINSTALLER_FINISHED_Detail "Terminado"
   33: StrCpy $UNINSTALL_MESSAGEBOX "Parece que ${APPLICATION_NAME} no está instalado en el directorio '$INSTDIR'.$$ ¿Continuar de todos modos? (No recomendado)"
   34  StrCpy $UNINSTALL_ABORT "Desinstalación cancelada por el usuario"
   35  StrCpy $INIT_NO_QUICK_LAUNCH "Atajo de inicio rápido (N/A)"

5 matches across 5 files
```

**Comment by michaelstingl** [comment]
I see also some (orphaned?) ``"$"`` without trailing ``"{"``  or ``"\"``.

**Comment by dragotin** [comment]
Well, now it becomes difficult, because these seem to be mistakes in the translation that should be fixed in transifex. Nothing we can do in the client I guess.

**Comment by michaelstingl** [comment]
That's why I suggested to add hints/comments for the translation community.

NSIS variables for line breaks etc don't work well in Transifex. They are not displayed properly. Could we use regular hidden characters and transform to NSIS syntax automatically later?

**Comment by dragotin** [comment]
@michaelstingl yes, we need to improve here. Lets discuss this, but please allow to close this ticket for the scope of 2.1.1 ;-)

We could have a new one, striving for a universal not destroyable newline pattern for NSIS.

**Comment by michaelstingl** [comment]
:+1:
