### ISSUE TITLE
Improved folder addition/selection workflow during installation and after

### ISSUE THREAD

**Issue by lbryson** [owncloud/client#3521]
Related to #3148 and #100: As a user, during install, there are too many steps and too complex a workflow to get to selective sync.  (I realized this while walking one of my server admins through the client install, and he was puzzled/confuzed.)  

The user has hundreds of GB or even TB shared with him. We don't want each new install of the client to result in all of that being synced to their client during client installation.  The current workflow is to Install the client, select “skip folder selection” during install, then go back and set up folder pairs.  …it presents the user first with a default "owncloud" destination folder. This could be improved graphically a lot.

Nearly the same folder selection/addition workflow should be present during installation and later when the user selects to "Add a folder":

Acceptance criteria:
* A radio selection to choose one of the following (with *no* default; the user has to choose)
  * "Sync an existing local folder to a new Owncloud folder"
  * "Sync an existing Owncloud folder to a new local folder”
  * "Merge and sync an existing local folder with an existing Owncloud folder”
  * “Sync all shared Owncloud data (give size!) to your local Owncloud folder”
* Selecting "Sync all shared Owncloud data" to the local Owncloud folder is problematic when a user selectively syncs existing Owncloud folders to existing local folders, and vice versa, so it should be mutually exclusive of the other options.
  * Either you "sync all", then selectively remove folders and/or get prompted when new top level data is shared, or you individually add and sync folders; but not both.
  * This causes me to wonder whether the Sync all (the current default behavior) makes sense at all: why should it treat all data that is shared with me, including perhaps entire network shares and easily many GBs, *ever* be grouped together with my own data.  Why not *always* require (or prompt) the user to actually accept/add those folders?
* Based on the radio selection, on the same screen, have a pane for the local folder selection on the left and the remote folder selection on the right, with a double arrow indicating that both will be synced.
  * Provide default folders based on which radio button is synced. e.g., 
    * If syncing an existing owncloud folder to a new local folder, then it should default the local folder name to a created sub-folder of the local owncloud\<shared-folder-name>.  
    * If it's a new local folder, default to a new folder with the same name as the existing synced Owncloud folder;
    * and vice versa.
    * merge and sync existing with existing will not have either folder selected as default
    * sync all shared owncloud content will default to the local "owncloud" folder and the remote root "owncloud" folder.
* After the user makes their selections and selects "next", present them with a confirmation "all content between these two folders (show folders below) will be synchronized now and on a continuing basis through the client" confirmation.
  * "Yes, and add another"
  * "No, go back and change it"
  * "No, leave selection dialogue"
  * "Yes, and leave selection dialogue"

…the point being that the user should be able to see, intuitively and on a single screen, that “this local folder and this remote folder will be synced”, and with better defaults.

Thoughts?

**Comment by guruz** [comment]
Have you tried the recent 2.0 builds? :)
http://download.owncloud.com/desktop/daily/

**Comment by lbryson** [comment]
Ah, I try to stick to the GA.  But I’m very excited, in that case.

Thanks for following up.

**Comment by MTRichards** [comment]
Yeah, in 2.0 a new feature "confirm sync of folders" was added. This means that if a new folder shows up on your account, you can set a threshold for size above which you are asked to confirm that you want the folder, and below which the folder is synced automatically.

**Comment by ogoffart** [comment]
closing since we have the confirm feature
