### ISSUE TITLE
[Multiaccount] I don't have the option "Copy link" if I share with ownCloud

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3526]
### Steps to reproduce
1. Install the v 2.0.0
2. Open your ownCloud Desktop client
3. Create a new folder, called 111
4. Right click on the folder 111
5. Select share with ownCloud

### Expected behaviour
The option should also appear "Copy link"

### Actual behaviour
You don't have the option "Copy link"

![screen shot 2015-07-31 at 11 25 59](https://cloud.githubusercontent.com/assets/12032058/9004521/fc708384-3776-11e5-9212-301a09c0efda.png)

The option "Copy link" appears when you introduce the password, and click in Set Password
![screen shot 2015-07-31 at 11 27 47](https://cloud.githubusercontent.com/assets/12032058/9004545/355dd8cc-3777-11e5-91db-13dd65efcd23.png)

### Server configuration
Desktop v ownCloud-2.0.0.2582-nightly20150731.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by phil-davis** [comment]
That is working OK for me on Windows7 and ownCloud client 2.0.0-nightly 20150731 (build 5317), so the Windows version is OK.
![owncloud-share-and-copy-link](https://cloud.githubusercontent.com/assets/1535615/9005413/bdc3a9e6-379d-11e5-95fd-4bc69db14180.png)

**Comment by Dianafg76** [comment]
With in my Widows Server 2008  R2 Enterprise, with Service Pack 1, it is not working.
Desktop v ownCloud-2.0.0.5317-nightly20150731-setup.exe 
![screen shot 2015-07-31 at 14 29 00](https://cloud.githubusercontent.com/assets/12032058/9007341/a0b7c27c-3790-11e5-8d8d-93910e8419be.png)

**Comment by guruz** [comment]
Do you see anything in the log output on OS X?

**Comment by rullzer** [comment]
@Dianafg76 do you enforce password protection? (looks like you do). Then you first need to set a password before the file is actually shared. So this is expected behaviour. 

Could you try without enforcing a password on the server?

**Comment by Dianafg76** [comment]
@rullzer When you select the opcion "Share with oC" appears this screen. I can only write the password

If I share the same folder on the Server, I don't have problem, is working ok. 
The problem is when you share from your desktop

**Comment by rullzer** [comment]
@Dianafg76 but your first screenshot

![screen shot 2015-07-31 at 11 25 59](https://cloud.githubusercontent.com/assets/12032058/9004521/fc708384-3776-11e5-9212-301a09c0efda.png)

It shows the text: ```public sharing requires a password``` which is only shown if the password is enforced. 

The capabilities are not yet refreshed periodicly. So if you change something in your server config the client will only pick up on it when you restart.

Could you tell me the sharing settings you have on the server so we can double check?

**Comment by Dianafg76** [comment]
@guruz, this is the Sharing setting in my server
![screen shot 2015-08-04 at 11 06 49](https://cloud.githubusercontent.com/assets/12032058/9057266/205b7270-3a99-11e5-9701-b91bdae6c387.png)

**Comment by danimo** [comment]
@ogoffart Why move this to 2.0.1?

**Comment by Dianafg76** [comment]
I try this issue in Desktop v 2.0.0.5372beta1 in WIN, and Desktop v 2.0.0.2613beta1, and the same thing happens

**Comment by danimo** [comment]
I see the same problem here. The spinner never disappears and the API returns a 404 if I check and uncheck the share checkbox.

**Comment by rullzer** [comment]
@Dianafg76 could you post the logs if you start the client and redo the steps?

**Comment by Dianafg76** [comment]
@rullzer please, check https://github.com/owncloud/client/issues/3526#issue-98352597

**Comment by rullzer** [comment]
@Dianafg76 I mean the log from the client if you start it from the command line

**Comment by Dianafg76** [comment]
@rullzer This is .log
´´´08-07 14:44:47:006 0x7fb1406043f0 OCC::SocketApi::command_SHARE: void OCC::SocketApi::command_SHARE(const QString &, QIODevice *) "/Users/Diana/user21beta1/Photos"
08-07 14:44:47:007 0x7fb1406043f0 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE:OK:/Users/Diana/user21beta1/Photos"
08-07 14:44:47:008 0x7fb1406043f0 OCC::ownCloudGui::slotShowShareDialog: void OCC::ownCloudGui::slotShowShareDialog(const QString &, const QString &, bool) Opening share dialog "//Photos" "/Users/Diana/user21beta1/Photos"
08-07 14:44:47:076 0x7fb1406043f0 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "https://docker.oc.solidgear.es" + ""
08-07 14:44:48:111 0x7fb142aeb0e0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fb140715c00) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-07 14:44:48:111 0x7fb142aeb0e0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fb140715c00) QObject(0x0)  0 false 3 0
08-07 14:44:52:236 0x7fb142a9aba0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fb14294c520) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-07 14:44:52:236 0x7fb142a9aba0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fb14294c520) QObject(0x0)  0 false 3 0
08-07 14:45:09:808 0x7fb1406043f0 OCC::Folder::slotRunEtagJob: * Trying to check "ownCloud" for changes via ETag check. (time since last sync: 50 s)
08-07 14:45:09:809 0x7fb1406043f0 OCC::Folder::slotRunEtagJob: * Trying to check "ownCloud1" for changes via ETag check. (time since last sync: 47 s)
08-07 14:45:09:810 0x7fb1406043f0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "ownCloud" to check remote ETag
08-07 14:45:09:810 0x7fb1406043f0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://docker.oc.solidgear.es" + ""
08-07 14:45:10:038 0x7fb1406043f0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55c48f360e380""55c46f48e1b25""55c46f4926d7b""fe2e8f917ce0f1bb20c390ca01c80f34"" , received: ""55c48f360e380""55c46f48e1b25""55c46f4926d7b""fe2e8f917ce0f1bb20c390ca01c80f34""
08-07 14:45:10:039 0x7fb1406043f0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7fb142865ab0)  with name  "ownCloud"
08-07 14:45:10:039 0x7fb1406043f0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7fb1405e85b0)  with name  "ownCloud1"
08-07 14:45:10:051 0x7fb1406043f0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "ownCloud1" to check remote ETag
08-07 14:45:10:051 0x7fb1406043f0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://docker.oc.solidgear.es" + "/"
08-07 14:45:10:279 0x7fb1406043f0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55c4a5262c010""55c46f8ce71df""166c1ecf3fa0e0439f41061277fc7bfa""55c46f8d25967""c89f608defc49e590c84fbea409d8fbd"" , received: ""55c4a5262c010""55c46f8ce71df""166c1ecf3fa0e0439f41061277fc7bfa""55c46f8d25967""c89f608defc49e590c84fbea409d8fbd""
08-07 14:45:10:279 0x7fb1406043f0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7fb142865ab0)  with name  "ownCloud"
08-07 14:45:10:280 0x7fb1406043f0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7fb1405e85b0)  with name  "ownCloud1"
08-07 14:45:10:293 0x7fb1406043f0 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
08-07 14:45:14:808 0x7fb1406043f0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-07 14:45:14:808 0x7fb1406043f0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://docker.oc.solidgear.es" + "/"
08-07 14:45:14:808 0x7fb1406043f0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-07 14:45:14:809 0x7fb1406043f0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://docker.oc.solidgear.es" + "/"
08-07 14:45:19:972 0x7fb142aeb0e0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fb140715c00) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-07 14:45:19:972 0x7fb142aeb0e0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fb140715c00) QObject(0x0)  0 false 3 0
08-07 14:45:19:972 0x7fb142a9aba0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fb14294c520) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-07 14:45:19:972 0x7fb142a9aba0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fb14294c520) QObject(0x0)  0 false 3 0
08-07 14:45:39:808 0x7fb1406043f0 OCC::Folder::slotRunEtagJob: * Trying to check "ownCloud" for changes via ETag check. (time since last sync: 80 s)
08-07 14:45:39:809 0x7fb1406043f0 OCC::Folder::slotRunEtagJob: * Trying to check "ownCloud1" for changes via ETag check. (time since last sync: 77 s)
08-07 14:45:39:809 0x7fb1406043f0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "ownCloud" to check remote ETag
08-07 14:45:39:809 0x7fb1406043f0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://docker.oc.solidgear.es" + ""
08-07 14:45:40:465 0x7fb1406043f0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55c48f360e380""55c46f48e1b25""55c46f4926d7b""fe2e8f917ce0f1bb20c390ca01c80f34"" , received: ""55c48f360e380""55c46f48e1b25""55c46f4926d7b""fe2e8f917ce0f1bb20c390ca01c80f34""
08-07 14:45:40:466 0x7fb1406043f0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7fb142865ab0)  with name  "ownCloud"
08-07 14:45:40:466 0x7fb1406043f0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7fb1405e85b0)  with name  "ownCloud1"
08-07 14:45:40:480 0x7fb1406043f0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "ownCloud1" to check remote ETag
08-07 14:45:40:481 0x7fb1406043f0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://docker.oc.solidgear.es" + "/"
08-07 14:45:40:713 0x7fb1406043f0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55c4a5262c010""55c46f8ce71df""166c1ecf3fa0e0439f41061277fc7bfa""55c46f8d25967""c89f608defc49e590c84fbea409d8fbd"" , received: ""55c4a5262c010""55c46f8ce71df""166c1ecf3fa0e0439f41061277fc7bfa""55c46f8d25967""c89f608defc49e590c84fbea409d8fbd""
08-07 14:45:40:714 0x7fb1406043f0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7fb142865ab0)  with name  "ownCloud"
08-07 14:45:40:714 0x7fb1406043f0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7fb1405e85b0)  with name  "ownCloud1"
08-07 14:45:40:721 0x7fb1406043f0 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
08-07 14:45:45:463 0x7fb142aeb0e0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fb140715c00) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-07 14:45:45:463 0x7fb142aeb0e0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fb140715c00) QObject(0x0)  0 false 3 0
08-07 14:45:45:715 0x7fb142a9aba0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fb14294c520) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-07 14:45:45:715 0x7fb142a9aba0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fb14294c520) QObject(0x0)  0 false 3 0
08-07 14:45:46:809 0x7fb1406043f0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-07 14:45:46:809 0x7fb1406043f0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://docker.oc.solidgear.es" + "/"
08-07 14:45:46:809 0x7fb1406043f0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-07 14:45:46:810 0x7fb1406043f0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://docker.oc.solidgear.es" + "/"
08-07 14:45:52:080 0x7fb142a9aba0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fb14294c520) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-07 14:45:52:080 0x7fb142a9aba0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fb14294c520) QObject(0x0)  0 false 3 0
08-07 14:45:52:087 0x7fb142aeb0e0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fb140715c00) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-07 14:45:52:087 0x7fb142aeb0e0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fb140715c00) QObject(0x0)  0 false 3 0
08-07 14:46:09:809 0x7fb1406043f0 OCC::Folder::slotRunEtagJob: * Trying to check "ownCloud" for changes via ETag check. (time since last sync: 110 s)
08-07 14:46:09:810 0x7fb1406043f0 OCC::Folder::slotRunEtagJob: * Trying to check "ownCloud1" for changes via ETag check. (time since last sync: 107 s)
08-07 14:46:09:811 0x7fb1406043f0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "ownCloud" to check remote ETag
08-07 14:46:09:811 0x7fb1406043f0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://docker.oc.solidgear.es" + ""
08-07 14:46:10:305 0x7fb1406043f0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55c48f360e380""55c46f48e1b25""55c46f4926d7b""fe2e8f917ce0f1bb20c390ca01c80f34"" , received: ""55c48f360e380""55c46f48e1b25""55c46f4926d7b""fe2e8f917ce0f1bb20c390ca01c80f34""
08-07 14:46:10:306 0x7fb1406043f0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7fb142865ab0)  with name  "ownCloud"
08-07 14:46:10:306 0x7fb1406043f0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7fb1405e85b0)  with name  "ownCloud1"
08-07 14:46:10:318 0x7fb1406043f0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "ownCloud1" to check remote ETag
08-07 14:46:10:318 0x7fb1406043f0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://docker.oc.solidgear.es" + "/"
08-07 14:46:11:419 0x7fb1406043f0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""55c4a5262c010""55c46f8ce71df""166c1ecf3fa0e0439f41061277fc7bfa""55c46f8d25967""c89f608defc49e590c84fbea409d8fbd"" , received: ""55c4a5262c010""55c46f8ce71df""166c1ecf3fa0e0439f41061277fc7bfa""55c46f8d25967""c89f608defc49e590c84fbea409d8fbd""
08-07 14:46:11:420 0x7fb1406043f0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7fb142865ab0)  with name  "ownCloud"
08-07 14:46:11:421 0x7fb1406043f0 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7fb1405e85b0)  with name  "ownCloud1"
08-07 14:46:11:432 0x7fb1406043f0 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
08-07 14:46:15:313 0x7fb142aeb0e0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fb140715c00) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-07 14:46:15:314 0x7fb142aeb0e0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fb140715c00) QObject(0x0)  0 false 3 0
08-07 14:46:15:949 0x7fb142a9aba0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fb14294c520) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-07 14:46:15:949 0x7fb142a9aba0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fb14294c520) QObject(0x0)  0 false 3 0
08-07 14:46:18:808 0x7fb1406043f0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-07 14:46:18:808 0x7fb1406043f0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://docker.oc.solidgear.es" + "/"
08-07 14:46:18:809 0x7fb1406043f0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-07 14:46:18:809 0x7fb1406043f0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://docker.oc.solidgear.es" + "/"
08-07 14:46:24:317 0x7fb142a9aba0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fb14294c520) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-07 14:46:24:318 0x7fb142a9aba0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fb14294c520) QObject(0x0)  0 false 3 0
08-07 14:46:24:320 0x7fb142aeb0e0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fb140715c00) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
08-07 14:46:24:320 0x7fb142aeb0e0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fb140715c00) QObject(0x0)  0 false 3 0´´´

**Comment by guruz** [comment]
I get the same spinning box..

```
08-12 17:26:21:620 0x7fd378721900 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 203 "Error downloading https://cloud.molkentin.net/index.php/apps/files/api/v1/thumbnail/150/150/inbox/bla.zip - server replied: Not Found" QVariant(int, 404)
08-12 17:26:21:620 0x7fd378721900 OCC::ShareDialog::slotThumbnailFetched: void OCC::ShareDialog::slotThumbnailFetched(const int &, const QByteArray &) Status code:  404
```

then nothing useful anymore as far as I see..

**Comment by guruz** [comment]
Ah this is just bad UX.
If you set a password then it will show the link.
I'll disable the spinner and think about how else this can be improved..

**Comment by guruz** [comment]
OK, let me know if this feels better now @Dianafg76

**Comment by Dianafg76** [comment]
@guruz Hi. I tested this issue and I still can't share by link.
1. Create a new folder/file
2. Right click on the folder 222
3. Select share with ownCloud

When I click in "Share whith ownCloud", I don't have the option Copy by link
![screen shot 2015-08-13 at 08 54 20](https://cloud.githubusercontent.com/assets/12032058/9244167/f117e8f2-4198-11e5-9f57-dcae71bef217.png)

I need write the Password, and Set password and then appears Copy by Link
![screen shot 2015-08-13 at 08 57 19](https://cloud.githubusercontent.com/assets/12032058/9244205/576b9c02-4199-11e5-9b8e-9db839901809.png)

Desktop v ownCloud-2.0.0.2625-nightly20150813.pkg

**Comment by guruz** [comment]
Is the server configured to require a password for link sharing?

**Comment by Dianafg76** [comment]
@guruz No, this is my configuration on the server
![screen shot 2015-08-13 at 09 11 34](https://cloud.githubusercontent.com/assets/12032058/9244427/5f250daa-419b-11e5-80a4-f3f61f8335c6.png)

**Comment by Dianafg76** [comment]
Log.
```
08-13 09:16:13:461 0x7fc80ae28690 OCC::SocketApi::command_SHARE: void OCC::SocketApi::command_SHARE(const QString &, QIODevice *) "/Users/Diana/user6/New Folder for share by link"
08-13 09:16:13:461 0x7fc80ae28690 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE:OK:/Users/Diana/user6/New Folder for share by link"
08-13 09:16:13:462 0x7fc80ae28690 OCC::ownCloudGui::slotShowShareDialog: void OCC::ownCloudGui::slotShowShareDialog(const QString &, const QString &, bool) Opening share dialog "//New Folder for share by link" "/Users/Diana/user6/New Folder for share by link"
08-13 09:16:13:468 0x7fc80ae28690 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "https://docker.oc.solidgear.es" + ""
08-13 09:16:13:737 0x7fc80ae28690 OCC::ShareDialog::slotSharesFetched: void OCC::ShareDialog::slotSharesFetched(const QVariantMap &) "8.1.1.2" Fetched 0 shares
08-13 09:16:13:738 0x7fc80ae28690 OCC::ShareDialog::slotCheckBoxShareLinkClicked: void OCC::ShareDialog::slotCheckBoxShareLinkClicked() true
08-13 09:16:18:771 0x7fc80aef3df0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fc80ad0a250) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
```

**Comment by guruz** [comment]
I've created a server side issue. https://github.com/owncloud/core/issues/18261

@DeepDiver1975

**Comment by guruz** [comment]
Thanks @nickvergessen https://github.com/owncloud/core/pull/18271

**Comment by Dianafg76** [comment]
I tested this issue and now I see the option "Copy Link"
Many Thanks
Closed

**Comment by Dianafg76** [comment]
I tested this issue, and I don't see again the option "Copy Link"
Desktop v ownCloud-2.0.0.2632beta2.pkg

**Comment by Dianafg76** [comment]
I need enter the Password for looking the option "Copy by Link"

**Comment by guruz** [comment]
@rullzer @Dianafg76 I'm assuming this is working correctly if the server is having @nickvergessen 's patch
