### ISSUE TITLE
[OS X?] Migrating from old version can bork accounts

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3528]
To reproduce, migrate from 1.8
Migrated account shows up nicely
Then close
Then re-open client. You will have an account ```@```.

**Comment by phil-davis** [comment]
Just to report that I upgraded from 1.8.4 to the 2.0 nightlies yesterday running on Windows7 and had no trouble in this respect. I ended up with the correct single account in V2.0 and it hasn't broken in this way after a number of client restarts. So it worked OK for me on Windows. Might help with the "?" after "OS X".

**Comment by guruz** [comment]
It seems the migrated account is shown nicely in the UI and also syncs, however in the ```cfg``` it only shows up as

```
[Accounts]
0\Folders\ownCloud\ignoreHiddenFiles=false
0\Folders\ownCloud\localPath=/Users/guruz/folder/
0\Folders\ownCloud\paused=false
0\Folders\ownCloud\targetPath=
```

**Comment by guruz** [comment]
@ogoffart ^^ Can you tell me why this is necessary?

**Comment by guruz** [comment]
I take this back, it did not fix it.

**Comment by guruz** [comment]
@ogoffart ^^ review?

**Comment by Dianafg76** [comment]
@ guruz I can not reproduce this problem . Because now I have Installed version 2.0.0 , and when I go to uninstall the 2.0.0 version looks like this:
![screen shot 2015-08-03 at 10 57 11](https://cloud.githubusercontent.com/assets/12032058/9034248/7089ab66-39ce-11e5-8985-9795162b6ab5.png)
Only about MAC , because if I try to Windos is working

**Comment by guruz** [comment]
Please see https://github.com/owncloud/client/issues/3464#issuecomment-127175785

**Comment by Dianafg76** [comment]
related #3539

**Comment by Dianafg76** [comment]
Desktop v ownCloud-1.8.4.2596-nightly20150804.pkg
Desktop v ownCloud-2.0.0.2592-nightly20150803.pkg

**Comment by guruz** [comment]
@Dianafg76 Are there screenshots missing for this comment above?
Let's close this because afaik the remaining issue is only https://github.com/owncloud/client/issues/3539

**Comment by Dianafg76** [comment]
@guruz ok, thanks
