### ISSUE TITLE
Clients stops syncing when an external storage in a synced subfolder is not properly configured

### ISSUE THREAD

**Issue by te-online** [owncloud/client#3533]
I don't know if this is an issue with the client or with the server and if this is specific to any external storage.

### Expected behaviour
Client syncs all data like it is supposed to, but skips folders that would contain an external storage which is not properly configured or not reachable (*red square* on admin page, section external storage).

### Actual behaviour
Client stops syncing any files at all and states that there is a problem with folder XY that is supposed to contain an external storage which is not properly configured. (**Important:** I needed weeks to figure out what the problem is. Because the client just stops at *discovering* this folder and shows the red x in front of the cloud.)

### Steps to reproduce
1. Create a folder for an external storage.
2. Configure e.g. a webdav external storage for the created folder, but give wrong credentials -> you see a red square instead of a green circle next to this storage entry.
3. Try to sync a folder that contains your created faulty-external-storage-folder.

### Server configuration
Operating system: Linux (Shared Hosting)

Web server: Apache

Database: MySQL (5.0.11 ?)

PHP version:  5.5.27

ownCloud version: 8.0.4

Storage backend:

### Client configuration
Client version: 1.8.4

Operating system: Mac OS 10.10.4

OS language: Deutsch

Installation path of client: Programs

### Logs

Client log says literally nothing. The *Activity* window stays empty.

ownCloud Log says
```
Error	files_external	Not authenticated
```

**Comment by guruz** [comment]
>  Because the client just stops at discovering this folder and shows the red x in front of the cloud.)

Was there no more detailed message?
Or something in the activity log?

**Comment by guruz** [comment]
@icewind1991 WebDAV external storage..

**Comment by te-online** [comment]
>Was there no more detailed message?

No, that is the strange thing. The sync-log window was entirely empty and there was no error message at all (not that I noticed). It only stopped at this particular folder and showed the "red x cloud". 

A long time I thought my installation of the client was damaged. But after I accidentally saw this wrong configured external storage on the admin-page and removed it, the client after a few minutes synced over 2gb of data that I created the last month or so.

Maybe I can restore this situation and provide you with a screenshot, if that is of help.

**Comment by te-online** [comment]
Sorry, I can't reproduce that. Maybe it was a one-time-thing. Or it only appears after the »faulty« storage is in the system for some time? What do you think?

**Comment by guruz** [comment]
OK :) Let's re-open this if you see it again.

**Comment by te-online** [comment]
Okay :-)
