### ISSUE TITLE
Show SSL version and cipher inside SslButton

### ISSUE THREAD

**Issue by vtolkm** [owncloud/client#3534]
a bit shocked seeing that the encrypted data between OC WIN sync client 1.84 and the OC server is being transmitted over SSL 2!

The server is supporting TLS 1.2 with PFS for the key exchange and as such is being utilized for the client authentication with the server, but then all ensuing encrypted data is being transmitted over SSL 2 only.

One thing is the server side encryption of the data, but utilizing SSL 2 for encrypted data transmission makes the data vulnerable whilst being out in the internet for anybody to intercept.

SSL 2 is rather a deprecated and most insecure protocol and has been retired from most applications connecting to the internet. Why is this still be in place with OC desktop sync client for WIN?

![ssl2](https://cloud.githubusercontent.com/assets/13611490/9026621/94f29bb0-393e-11e5-91f2-d2f664486d36.png)

**Comment by danimo** [comment]
Which client (OS, Version) is this? Note: the client depends on Qt, and Qt only disables SSLv2 in more recent versions (i.e. Qt 5), which is the default on Windows and OS X. On Linux, it depends on the distro. Anyway, it's the server's just to deny SSLv2.

**Comment by vtolkm** [comment]
That is OC client 1.8.4 on WIN 7 Pro 64bit, which trust is the most recent. Apparently SSL 2 is not disabled. 

Whilst disabling the server side SSL2/SSL3/TLS 1.0 is one way I would reckon such also be disabled in the client. And the client should not fall automatically back to SSL 2 for the transmission of the encrypted data when the server is offering TLS 1.2 in the first place - such policy does not makes sense but constitutes a broad attack vector to the unsuspecting user when the data is in its most vulnerable state.

If however disabling SSL2/SSL3/TLS 1.0 in the client is not a viable option then perhaps there should be something in the options of the client where the user could choose and thus being in control of the deployed protocol rather than not knowing and suspecting about the encryption level in the data stream.

**Comment by tflidd** [comment]
Client does a SSL downgrade attack itself! Consider as well that not all users can change the SSL settings (hosted environment, SSL proxy, ...) or use an old default configuration.

**Comment by danimo** [comment]
@tflidd I certainly does not run a downgrade attack. Can you give me the URL so I can check what's going on? if you don't want to posted it here, use danimo AT owncloud.com.

**Comment by vtolkm** [comment]
My suggestion to prevent downgrading in the SSL protocol something like this in the client settings, to make sure only the selected protocol type to be utilized by the client.

![ssl settings](https://cloud.githubusercontent.com/assets/13611490/9032261/70ac4030-39c5-11e5-8418-f481f310fbdb.PNG)

**Comment by danimo** [comment]
@vtolkm I first want to be able to reproduce the circumenstances under which you achived this. SSLv2 connects should simply not be possible with the Windows client.

**Comment by vtolkm** [comment]
@danimo you just need the URL or a guest login into the OC server?

**Comment by danimo** [comment]
@vtolkm yes, please

**Comment by vtolkm** [comment]
https://km.speicherbox.ch

guest / guest

then sync with the 1.8.4 client, as mentioned OS is WIN 7 64bit

used wireshark as packetsniffer

**Comment by vtolkm** [comment]
@danimo and please let me know when you are done so I can remove the guest account

**Comment by danimo** [comment]
@vtolkm Yes, which makes the whole test case mood. You can remove the account again.

**Comment by vtolkm** [comment]
@danimo sorry about that, but I wanted to get off the SSL2 stream asap

**Comment by vtolkm** [comment]
@danimo strange thing is that even with SSL2/SSL3 now off on the server wireshark is still showing SSL2 traffic from the sync client. Makes me wonder what is going on, whether wireshark gets it wrong somewhere or a 3rd party trying to inject SSL2 traffic into the stream or whether the client is trying (leaking) SSL2 attempts

![ssl2](https://cloud.githubusercontent.com/assets/13611490/9033009/6d3058ae-39cc-11e5-850f-f4044a293076.PNG)

**Comment by danimo** [comment]
@vtolkm "Encrypted data" implies that a connection has been established. As the server does not allow SSLv2 connects, you are either looking at something else, or wireshark is lying to you.

**Comment by vtolkm** [comment]
Got no other app connections with the OC server than the OC sync client. Would be willing to trying another packet sniffer to see whether wireshark is at fault - any recommendation for WIN 7?

![connections](https://cloud.githubusercontent.com/assets/13611490/9033237/02429d98-39ce-11e5-838f-e856a76ffe0e.png)

**Comment by danimo** [comment]
I just checked the code of the SSL stack we're using, and it defaults to `SecureProtocols` which is (in pseudo-code): `Any Protocol - (SSLv2 + SSLv3)`

**Comment by guruz** [comment]
Did you attempt to click one of the SSLv2 lines to see the detailed SSL info for that packet in the lower pane in Wireshark?

**Comment by vtolkm** [comment]
@guruz there is plenty of details, not sure what in particular you are looking for?

![wireshark stream details](https://cloud.githubusercontent.com/assets/13611490/9041077/b8f9465a-3a0e-11e5-8002-ab0161f1d143.png)

**Comment by danimo** [comment]
@vtolkm Your server does not support SSL 2.0 at all, and I think it never did. So unless this wireshark log is old, I claim wireshark misreports.

**Comment by danimo** [comment]
Which wireshark version is this?

**Comment by vtolkm** [comment]
@danimo Trusting your statement I hope you however understand that it raised me hackles seeing SSL2 in the stream, even more so that the server side has it disabled.

That wireshark is troubled in this case is a bit strange, since they are not  a new kid on the block. But suppose that no software is entirely free of bugs.

![wireshark version](https://cloud.githubusercontent.com/assets/13611490/9064912/7834e556-3ad7-11e5-8c5c-5f76553461b4.PNG)

**Comment by guruz** [comment]
We have a 2.0 nightly available that shows the SSL/TLS version in the SSL button.
http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.2602-nightly20150805.pkg

Can you test?

**Comment by guruz** [comment]
Just noticed you use Windows, still need to stay tuned for that nightly...

**Comment by guruz** [comment]
@vtolkm  http://dl-oc.owncloud.com/desktop/daily/ownCloud-2.0.0.5361-nightly20150806-setup.exe

**Comment by vtolkm** [comment]
@guruz Thanks, looking good

![client connection](https://cloud.githubusercontent.com/assets/13611490/9114211/4df9adcc-3c61-11e5-8ac7-dccc368881f5.png)

It is just irritating with wireshark declaring application data over TLS 1.2 and encrypted data as SSL2 and thus I was not sure what to make of that...

![wireshark irritation](https://cloud.githubusercontent.com/assets/13611490/9114358/1d0afcf6-3c62-11e5-8eb0-437ce4d70ac8.png)
