### ISSUE TITLE
"Unable to initialize a sync journal" on client 

### ISSUE THREAD

**Issue by mfassier** [owncloud/client#3535]
G'day ya'll. 

Sorry if this is a n00b issue, but I try to do my homework before asking for help... We had a machine running Win server 2008 foundation. It crashed and burned, so we hooked up with a brand new machine running Win Server 2012 Essentials. The ownCloud client that used to run smoothly on the old machine refuses to sync on this one. For the sake of clarity, this machine does not run OC. It's a Windows server on which I wish to run the sync client because it will make my life easier. Our OC is hosted on a remote VPS. I have run through most posts and forums and I can't see anything related to what I'm seeing here. I've poked it with a stick, but it just won't work. The closest bug I could find was with the user, but the instance runs under the proper user so that's likely not to blame. Reinstalled, rebooted, went to 1.8.0. Nada.

Any ideas ?

### Expected behaviour
Start and complete sync. Y'know, do the thing.

### Actual behaviour
Logs in OK with OC. Display remote folder for configuration. Once configured, client displays "Unable to initialize a sync journal" on all synced folders. 

### Steps to reproduce
1. Install client 1.8.4(5267) on Windows Server 2012 Essentials build 9200
2. Configure client with login info and remote and local folder
3. Observe miserable failure

### Server configuration
Operating system: Apache/2.2.27 (Unix) mod_ssl/2.2.27 OpenSSL/1.0.1e-fips DAV/2 mod_bwlimited/1.4
Web server: Apache

Database:MySQL 5.6.23

PHP version: 	5.4.31

ownCloud version: 7.0.4 

Storage backend: ?

### Client configuration
Client version: Windows 1.8.4 build 5267

Operating system:Windows Server 2012 Essentials build 9200

OS language: English

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log: 
Debug 	webdav 	Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found 	2015-08-03T03:02:29+00:00
Debug 	webdav 	Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found 	2015-08-03T02:59:49+00:00
Debug 	webdav 	Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found 	2015-08-03T02:57:09+00:00
Debug	webdav	Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found	2015-08-03T02:54:29+00:00
Debug	webdav	Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found	2015-08-03T02:51:49+00:00
Debug	webdav	Sabre\DAV\Exception\NotAuthenticated: No basic authentication headers were found	2015-08-03T02:49:09+00:00

3. ownCloud log (data/owncloud.log): empty

**Comment by guruz** [comment]
What kind of file system is this?
Is it remote or running on some SD card?

**Comment by mfassier** [comment]
How do you mean ? The machine running the client is all NTFS and are disks local. But I'm not sure that's what you're asking ?

**Comment by mfassier** [comment]
Well, I warned this might turn out to be n00bland after all. I double checked the user running the instance as it happens, the domain admin was but not the local. I'm guessing r/w permissions were amock so the client wouldn't sync. Not that it clearly told me it had a r/w issue, but still, we're done here. It works. Sorry for the noise.

**Comment by reylon** [comment]
SIMILAR PROBLEM. Owncloud desktop client 2.1.1 on linux machine debian jessie 8.3. Destination folder permission to the active user  uid=1000,gid=1000,umask=0007. I receive the messaje "unable to inizialize a sync journal". SERVER: raspberry PI2 B+ 1Gb, linux 7 wheezy, owncloud 8.2.2 stable. Attention. On client is running an owncloud 8.2.2 server also, that is not in connection with the client operation.

**Comment by guruz** [comment]
@reylon Please create a new issue for this. Also make sure to check if your system ```libsqlite3``` is recent.
