### ISSUE TITLE
[Multiaccount] in Mac, if you install the version 2.0.0 you can't use the SSL button

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3536]
### Steps to reproduce

  1. Install the ownCloud Testpilot Edition-2.0.0.2586-nightly20150731.pkg  
  2. Introduce the Server Address
  3. Click NEXT
  4. Accept the Certificate (SSL connection)
  5. Click OK
  6. Introduce the Username/password
  7. Click Connect... and Finish
  8. Right click in Icon oC
  9. Click in Settings

### Expected behaviour
You should be able to see the certificate information

### Actual behaviour
If you click the (SSL button) padlock to view the certificate , you see nothing, you do not see the certificate
![screen shot 2015-08-03 at 10 01 23](https://cloud.githubusercontent.com/assets/12032058/9033818/0792e698-39cb-11e5-91ab-4df5c108fc3a.png)

### Server configuration
Desktop v ownCloud Testpilot Edition-2.0.0.2586-nightly20150731.pkg  
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
It's the same in Desktop vownCloud-2.0.0.2592-nightly20150803.pkg

**Comment by guruz** [comment]
Could you test with this nightly?
http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.2602-nightly20150805.pkg

**Comment by Dianafg76** [comment]
@guruz, Hello. I tested this issue with Desktop v ownCloud-2.0.0.2602-nightly20150805.pkg, and I do not see the certificate
![screen shot 2015-08-06 at 08 35 46](https://cloud.githubusercontent.com/assets/12032058/9105279/944779da-3c16-11e5-9d7e-3b72b359af60.png)

**Comment by guruz** [comment]
Wow, how can this break so weirdly. Thanks for testing, I will have a look

**Comment by guruz** [comment]
There is something seriously broken here. If I restart the client, I get all information (sessionCipher, peerCertificate, peerCertificateChain) inside a ```metaDataChanged```.
If I remove the account and re-add it, I only get the above info but no peerCertificateChain inside a ```metaDataChanged```.
Then restarting the client I get all info again.

How can this be? Is there some timing issue going on inside QNetworkReply? Something overwriting something?

FYI @richmoore @peter-ha @danimo

**Comment by Dianafg76** [comment]
I tested this issue with Desktop v 2.0.0.2608beta1, and it's the same

**Comment by Dianafg76** [comment]
I install the v1.8.4 (build 2606)
Then I update v 2.0.0 (build 2608beta1) I see the certificate whit the first user
![screen shot 2015-08-07 at 12 34 58](https://cloud.githubusercontent.com/assets/12032058/9134059/0be5bee4-3d01-11e5-8ae2-37791662ee06.png)

But if you go to the second user and click in the SSL button you can't see the certificate

![screen shot 2015-08-07 at 12 35 50](https://cloud.githubusercontent.com/assets/12032058/9134070/19fb4d64-3d01-11e5-99b8-ef3b0e052c16.png)

**Comment by guruz** [comment]
@Dianafg76 
New nightly for Windows http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.5388-nightly20150811-setup.exe
OS X: http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.2622-nightly20150811.pkg

**Comment by Dianafg76** [comment]
@guruz It is working OK
Many Thanks
Closed
