### ISSUE TITLE
Feature request: Allow sharing with users on sync client

### ISSUE THREAD

**Issue by CaptionF** [owncloud/client#3537]
Prospect requires to be able to share not only through public link, but more importantly to LDAP users also from the sync client.

@MTRichards, just to capture all for the LDAP user sharing requirements
00003625

**Comment by danimo** [comment]
@CaptionF The feature exists in the client code, but is disabled because the server did not provide an auto-complation API at the time, and the feature is pointless without it. I doubt this has changed. /cc @DeepDiver1975

**Comment by danimo** [comment]
Changed title as this is not limited to LDAP at all.

**Comment by DeepDiver1975** [comment]
A topic we might want to address with 8.2 server code

**Comment by MTRichards** [comment]
Yes. This is a requirement for customer use case. Need to build the server API to make this possible.

**Comment by danimo** [comment]
@DeepDiver1975 @MTRichards Please create a ticket in core or link to an existing one so we can keep track of it here.

**Comment by DeepDiver1975** [comment]
The PR where the feature is developed in core: https://github.com/owncloud/core/pull/17749

**Comment by MTRichards** [comment]
Issue is here: https://github.com/owncloud/core/issues/16646

**Comment by rullzer** [comment]
I'm improving that PR. Should not be a lot of extra work. But it will probably be next weekend.

**Comment by DeepDiver1975** [comment]
> I'm improving that PR. Should not be a lot of extra work. But it will probably be next weekend.

THX a lot!

**Comment by dragotin** [comment]
@rullzer just a friendly remark that this feature has become important for the next release. Pls. let me know if you need help with it :)

**Comment by rullzer** [comment]
@dragotin Thanks. The shareeAPI has just been merged yesterday (https://github.com/owncloud/core/pull/18234). So I can now revive the old code. So I'll soon look into that. A lot of the logic is already there.

I'll keep you updated. And hope to have a somewhat working version soon.

**Comment by dragotin** [comment]
Now continued in #3737
