### ISSUE TITLE
[TestPilot Multiaccount] Appears the screen "Choose What to Sync" automatically

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3538]
### Steps to reproduce
1. Install the version TestPilot Multiaccount
2. Right click to Icon oC
3. Go to Settings..
4. Go to General
5. Click in Add an Account
6. Introcude the Server Address
7. Click in Next
8. Accept the SSL Connection
9. Click in OK
10. Introduce the Username/Password
11. Click in Next

### Expected behaviour
This option should not appear, if you don't select the option "Choose what to sync"

### Actual behaviour
Appears the screen "Choose What to Sync" automatically
![screen shot 2015-08-03 at 11 21 33](https://cloud.githubusercontent.com/assets/12032058/9034679/e31c4ae6-39d1-11e5-965d-8b30ccfa1fc7.png)
In other versions ,  it appears when you select the option "Choose what to sync"

### Server configuration
Desktop v ownCloud Testpilot Edition-2.0.0.2588-nightly20150801.pkg  
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by ogoffart** [comment]
That's because the Theme as the option    wizardSelectiveSyncDefaultNothing set.
And this is the expected behaviour.

```
    /**
     * When true, the setup wizard will show the selective sync dialog by default and default
     * to nothing selected
     */
```
