### ISSUE TITLE
New big folder not in list of folders to choose for sync

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3541]
### Expected behaviour
When there is a new shared folder on the server that is bigger than the confirmation limit then:
1) the client should notify the user
2) the user should be able to choose to sync or not sync the new folder

### Actual behaviour
1) The client notifies the user - good
2) The new folder does not appear in the dropdown list of known folders, so there is no way to select or unselect it for sync.
3) The "Apply" button seems the only thing the user can do at this point. After Apply is pressed the folder is synced down to the client. This rather defeats the whole point of this feature.
![owncloud-incoming-big-folder](https://cloud.githubusercontent.com/assets/1535615/9041617/b4a9dc58-3a28-11e5-9486-73bb22d75ff9.png)

### Steps to reproduce
1. Add a folder to the server with files in it greater than the confirmation limit.
2. Share the folder with the user
3. Let the client ind it and then the user can see the message about the new big folder...

### Server configuration
ownCloud version: 8.0

### Client configuration
Client version: 2.0.0-nightly 20150801 (build 5326)

Operating system: Windows10

OS language: English (US)

Installation path of client: default

**Comment by phil-davis** [comment]
It seems that there is nothing that triggers that dropdown list of folders to be refreshed with the new folder in it. If the dropdown list was refreshed then all would be good.

**Comment by phil-davis** [comment]
Note that the same sequence and issue happens if I make a new folder of my own with files in it on the server (or on another client). The source of the folder (own folder or folder shared by someone else) makes no difference to the issue.
Also when I have received some new small folders (that auto-downloaded) they do not appear in that dropdown list automagically. So there are a few events that need to trigger that list to refresh.

**Comment by phil-davis** [comment]
The workaround is to "Quit ownCloud" and then run the client again. It remembers the new folder that is waiting for a user decision and this time it appears in the list of folders to choose and the apply button will do good stuff according to the user's choice.
![owncloud-incoming-big-folder-after-client-restart](https://cloud.githubusercontent.com/assets/1535615/9043142/0cad813e-3a33-11e5-8411-40e39160b68d.png)

**Comment by guruz** [comment]
@ogoffart This is what I meant last week on IRC that the UX for this is still glitchy.
As @phil-davis pointed out, the drop down model should be updated and opened, else it is totally unclear that the ```Apply``` button does nothing.

**Comment by phil-davis** [comment]
And actually the Apply button does something - it accepts the new big folder for sync and the client immediately starts downloading it. That completely misses the whole point of having this feature;)

**Comment by guruz** [comment]
(OK, last time I checked some weeks ago or so the folders were not checked, so the Apply button did nothing.. :-)

**Comment by ogoffart** [comment]
Ah, i think the problem is that the view is not refreshed.

**Comment by guruz** [comment]
Please see the comment here https://github.com/owncloud/client/issues/3487#issuecomment-127725319 for a reason why I think the tree view should be dropped down and focus the folder.

Maybe we also need a call to action "Check the folders to have them downloaded"?

**Comment by phil-davis** [comment]
I agree, it will be really good if the folder tree is:
a) refreshed
b) opened (dropped down) and
c) focused on the relevant folder
when the user is notified about the new big folder.
That will mean nobody needs to train users in how to make the decision to sync (or not) a new big folder - it will be shown right in front of their nose.

**Comment by ogoffart** [comment]
That last commit made it refresh and automatically open.
It does no change the focus.

**Comment by phil-davis** [comment]
Sounds good. I will test when I see the next Windows installer build appear.

**Comment by phil-davis** [comment]
Still no Windows nightly build has appeared. There are various other builds for 6-Aug-2015. Is there some problem with the Windows (automatic) builder?

**Comment by Dianafg76** [comment]
In Mac for me with Desktop v ownCloud-1.8.4.2603-nightly20150806.pkg, it is working OK

**Comment by guruz** [comment]
@phil-davis Yes, sorry for that. And thanks a lot of being so active in testing.

@Dianafg76 Nice. let's wait for the windows build and @phil-davis testing+closing this.

**Comment by phil-davis** [comment]
Works for me also in Windows with 2.0.0.5359 build. Thanks.

**Comment by danimo** [comment]
@phil-davis Does that mean windows instalelrs wor kagain for you?

**Comment by phil-davis** [comment]
I have a home laptop running Windows10 Home not in a domain. The installer has always, and still does, work fine for that. So I can test ordinary stuff on my home laptop.

**Comment by danimo** [comment]
@phil-davis FYI, http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.5361-nightly20150806-setup.exe should work for all machines

**Comment by phil-davis** [comment]
Good stuff, 2.0.0.5361 installs on the domain computer. I commented on that issue: https://github.com/owncloud/client/issues/2616#issuecomment-128393654

**Comment by danimo** [comment]
:+1:
