### ISSUE TITLE
New empty folder downloads when confirmation limit is set to zero MB

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3542]
### Expected behaviour
Technically the confirmation limit is for folders larger than the limit.
There are a few users here with job-support type workflows where they would create a new folder for each job. The staff doing the jobs can set their confirmation limit to 0 MB. Then no new folders would be automatically downloaded. When the staff member wants to look at or work on the files in a job (folder) they can choose to sync it.

### Actual behaviour
In the case of a new empty folder, the empty folder is always downloaded. There is no way to set the confirmation limit so that empty folders are not downloaded.

### Steps to reproduce
1. Create and empty folder
2. Share it with someone who has their confirmation limit set to zero.
3. They get the new empty folder.

### Server configuration
ownCloud version: 8.0

### Client configuration
Client version: 2.0.0-nightly 201508101 (build 5326)

Operating system: Windows10

OS language: English (US)

Installation path of client: default

**Comment by phil-davis** [comment]
This can also be an issue if the workflow is that the central user creates new "job" folders that are empty for a few minutes and shares them. Those get auto-synced to ownCloud clients. Then a few minutes later they put a bunch of files in the folder. Since it has already been synced (when it was empty) the new files just added now all download.
IMHO it would be more convenient if the user could set the confirmation limit to 0 MB and that applied to new folders of size >=0 MB.
In a sense, an empty folder is already larger than 0MB - there must be some folder meta-data that takes some space, the non-empty folder name guarantees that the total size of (folder+file in the folder) is strictly > 0MB anyway.

**Comment by guruz** [comment]
Maybe a special handling of ```-1``` = "Don't download any folder without confirmation" or so would be interesting. Or just changing the meaning of 0.

**Comment by phil-davis** [comment]
Maybe just changing the limit comparison from "if >" to "if >=" will make this work. (I haven't looked in the code to see exactly what is done for the comparison, so pardon my guess if it is wrong).
I don't think anyone would complain if they set their limit to "larger than 20MB" but then got notified about a new folder that is exactly 20MB. In any case, users are not going to be sure if the limit is 20,000,000 bytes (decimal MB) or calculated internally as MiB anyway. So they are not really specifying a totally exact "to the byte" limit here.

**Comment by MTRichards** [comment]
Related https://github.com/owncloud/client/issues/3543

**Comment by MTRichards** [comment]
@phil-davis and of course your post about a delay on the sync interval to allow a filesystem to make a copy into a new folder before the filter is compared is relevant here.

@guruz I like the option to "Don't download a new folder without confirmation" that you proposed. It seems simple, and as a checkbox in settings allows the user to control their client behavior. At the same time, the default would be to have it off as 75% or more of users just want it to work that way from the start.

Can that work on the client side alone, or does it need server help?

**Comment by phil-davis** [comment]
Possible solution (the easiest thing to do - 1 character source code addition) https://github.com/owncloud/client/pull/3549

**Comment by guruz** [comment]
thanks @phil-davis !

**Comment by phil-davis** [comment]
Tested with 2.0.0.5363. I set the confirmation limit to 0 on the client, then added an empty folder on the server.
The client gives the "big folder" message and asks me to decide if I want the folder or not - all good.

**Comment by guruz** [comment]
Great :)

**Comment by MTRichards** [comment]
Awesome! Thanks @phil-davis
