### ISSUE TITLE
Folder created on Google Drive does not sync

### ISSUE THREAD

**Issue by jzee** [owncloud/client#3544]
To reproduce:
1. mount a google drive as external storage, have two random files in there, can be zero sized [OK]
2. verify it mounted fine in ownCloud, wait until the client synced [OK]
3. log in to google drive, create a folder, place a random file in there, can be zero sized [OK]
4. go back to ownCloud, navigate to the mounted google drive, verify the folder shows up [OK]
5. verify the locally synced folder, the new folder created underneath the google drive mount point is not there [NOT OK, expect the new subfolder to show up and sync]

furthermode:
6. go back to ownCloud, navigate to the mountpoint of google drive, create a file or folder there [OK]
7. verify the locally synced folder. Now the full Google Drive folder has synced almost instantly.

Corollary: 
When a folder is created on the external storage, the sync client fails to sync through even though the folder is well accessible and browsable through ownCloud's own webinterface

Verifiable 100% using 1.8.4-2531

**Comment by guruz** [comment]
Which server version?

**Comment by guruz** [comment]
CC @AdamWill

**Comment by AdamWill** [comment]
FWIW I don't use the OC client app at all, so I wouldn't have run into this one. Since the OC web UI displays it I'd *guess* this is a client issue, but I could of course just be saying that to get out of fixing it. ;)

**Comment by jzee** [comment]
server is 7.0.7

**Comment by guruz** [comment]
@jzee Did you find anything related in https://github.com/owncloud/core ? (this repo is for client issues which don't depend on specific storages)

**Comment by jzee** [comment]
@guruz, nope, didn't see anything. 
@AdamWill, I just double checked with dropbox, where the same scenario appears to be working just fine. Can you shed any insight on this?

**Comment by AdamWill** [comment]
Not off the top of my head, no. To be entirely honest I'm not super motivated to look into it either; I seem to have become The Google Guy just because I did the work to port the code to the latest version of the Google lib. I wasn't volunteering to own it forever. I don't even *use* Google Drive.

**Comment by PVince81** [comment]
This is probably the general remote changes detection issue with external storages: https://github.com/owncloud/core/issues/11797#issuecomment-61304871

**Comment by guruz** [comment]
OK, then please use a newer version of the server and if there is still an issue open an issue in the core tracker, not here :) thanks
https://github.com/owncloud/core
