### ISSUE TITLE
[Multiaccount] I can't uninstall the v2.0.0, appears an error

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3546]
### Steps to reproduce
1. You need installed the Desktop v 2.0.0 (build 5326)
2. Uninstall the version

### Expected behaviour
You should be able to uninstall the version

### Actual behaviour
When you uninstall the Desktop v 2.0.0 (build 5326), appears this error:
![screen shot 2015-08-04 at 08 51 02](https://cloud.githubusercontent.com/assets/12032058/9054913/15816f16-3a86-11e5-8586-ef0d2159f355.png)

### Server configuration
Desktop v2.0.0 (build 5326)
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
If I install the Desktop v ownCloud-2.0.0.5349-nightly20150804-setup.exe, appears the same error

**Comment by danimo** [comment]
@Dianafg76 please retest with build 3550 (should appear in a few minutes)

**Comment by Dianafg76** [comment]
@danimo, I tested with Desktop v  ownCloud-2.0.0.5351-nightly20150804-setup.exe. And is working OK
many thank :-)
I close the issue
