### ISSUE TITLE
[OS X] [10.10] Unload Finder bundle on exit

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3547]
See screenshot on https://github.com/owncloud/client/issues/3528#issuecomment-127169399

**Comment by jturcotte** [comment]
We can't unload it on exit without loading it on startup, which means that users can't reasonably disable the extension from the OS X system preferences.

The screenshot linked is only when trying to move the bundle to the trash manually, I don't get the error when unstalling the packages. Dropbox actually produces the same error for me, so I'm not sure what we can do about this issue.

**Comment by danimo** [comment]
If the right solution to uninstall is to use the package uninstaller, we can close this ticket.

**Comment by guruz** [comment]
@jturcotte Is the extension always loaded or only after oC start?
Because for the latter, the user can just logout/login..

**Comment by jturcotte** [comment]
No it's always loaded, but the list of directoryURLs will be empty so the extension is basically idle.

https://developer.apple.com/library/mac/documentation/FinderSync/Reference/FIFinderSyncController_Class/index.html#//apple_ref/occ/instp/FIFinderSyncController/directoryURLs
