### ISSUE TITLE
not possible to unshare in Windows client

### ISSUE THREAD

**Issue by Flexmaen** [owncloud/client#3550]
I noticed that the OwnCloud client for Windows is not able to unshare the folder. If you right click on the folder and remove the checker for "share", nothing will change. Directory still will be shared.

**Comment by danimo** [comment]
@rullzer, pls

**Comment by rullzer** [comment]
@Flexmaen mmm that is weird. Do you get error info in the bottom of the share dialog when this happens?

You can only unshare the link shares. Since we can't handle user/groups shares properly in the client yet.

Could you run wit logging (no clue how to do that on windows...)? And then try to unshare again and post the log here?

**Comment by Flexmaen** [comment]
I took a closer look now and noticed that I was misleaded by the confusing behaviour of the Windows client.

So: Unsharing a folder seems to work. But the problem is that the OwnCloud client automatically will create a share link once I right click on a folder and select "share via OwnCloud". So I won't be able to see the current status. But if the folder already is shared, it will retrieve and display the current share link. (Otherwise it will create a new one.)

So I guess it would be more logical if the client shows the current status, that means:
- showing the current share link if the folder is shared (like it does now)
- if the folder is not shared, the checkbox should be unchecked, so that you have to check it first instead of having it checked automatically

What do you think?

**Comment by rullzer** [comment]
That will be the behaviour once I can implement user/group sharing. :)
Currently we can only share by link so this seems logical.

But glad that it is not a bug.

**Comment by Flexmaen** [comment]
From the technical side it might look logical, from the user experience I'm not sure. Once you know it it's ok.
But sounds like this will be improved with the user/group sharing anyway.
Thanks for caring about this!
