### ISSUE TITLE
sharing with write-access not possible from client

### ISSUE THREAD

**Issue by Flexmaen** [owncloud/client#3551]
In the windows client it is not possible to share a directory with the allowance to edit it. The checkbox for "edit/write access" is missing.

Web-Version: Owncloud 8.1
Client 1.8.4 (build 5267)

**Comment by danimo** [comment]
@rullzer, pls

**Comment by rullzer** [comment]
Well, this is not implemented yet. So technically it is correct that is not shown yet ;)

But I'll add this to my TODO list.

**Comment by rullzer** [comment]
Server PR to make this happen in https://github.com/owncloud/core/pull/18320
