### ISSUE TITLE
WIN7x64: testpilotcloud-2.0.0.5348-nightly20150804-setup.exe: Installer fails during uninstall.

### ISSUE THREAD

**Issue by umgfoin** [owncloud/client#3557]
When trying to uninstall testpilotcloud-2.0.0.5348 on Win 7x64, setup fails with msgbox:
"Unable to elevate: error".

**Comment by danimo** [comment]
Yes, this is a known issue. Please install a more recent (or even older version) and choose not to uninstall the existing version during the process.
