### ISSUE TITLE
[Overlays] when you share a folder with other user the icon it is not working well

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3559]
### Steps to reproduce

1. Open your Owncloud Web client, with the user1
2. Create a new Folder, called Doc Word2007
2. Create a same Files into the Folder
3. Share the Folder aaa with other user (user2)
4. Unchecked the option 'Edit'
5. Open your Owncloud Desktop client, with the user2
6. Go to Open Folder "ownCloud"
7. Wait for it to sync (evething is OK)
8. Create a new File into the Folder (Doc Word2007)

### Actual behaviour
Appears an error because I don't have permission to add files in that directory ( OK)
But the icon in the Folder it is not Red
![screen shot 2015-08-05 at 16 44 10](https://cloud.githubusercontent.com/assets/12032058/9088633/5845edfc-3b91-11e5-92b7-aa58c06b80ae.png)

### Server configuration
Desktop v ownCloud Testpilot Edition-2.0.0.2593-nightly20150803.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.1.2","versionstring":"8.1.1 RC1","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
Windows icons are colored differently than in Mac , doing the same
![screen shot 2015-08-05 at 17 34 32](https://cloud.githubusercontent.com/assets/12032058/9090015/69201740-3b98-11e5-8833-de53a9144246.png)

Desktop v testpilotcloud-2.0.0.5348-nightly20150804-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.1.1.2","versionstring":"8.1.1 RC1","edition":"Enterprise"}

**Comment by ogoffart** [comment]
I suppose this is not related to the test pilot and happens with the normal owncloud too.

**Comment by Dianafg76** [comment]
@ogoffart Yes, happens with the normal owncloud

**Comment by Dianafg76** [comment]
If you:
1. Create a New Folder
2. Create one folder with 1GB
3. Wait to Sync
4. When the Sync is finished
The icons are of different colors
![screen shot 2015-08-06 at 13 50 35](https://cloud.githubusercontent.com/assets/12032058/9111001/eb37e334-3c42-11e5-957d-a5d8f3d6991e.png)

**Comment by guruz** [comment]
Moving this to 2.0.1 FYI @danimo

**Comment by rullzer** [comment]
Ah yes this is known. We need to properly set the permissions of files/folders. Currently this is just not done.

It is not related to the multiaccount stuff. It is just that we do not do anything with this information yet :P

**Comment by ckamm** [comment]
@Dianafg76 Can you still reproduce this after today's round of fixes? For me, both the file that can't be uploaded due to sharing permissions and the shared folder itself get a red icon.

**Comment by Dianafg76** [comment]
@ckamm I tested this issue with the new version and it is working OK
Desktop v ownCloud-2.1.0.2957-nightly20151210.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}
Closed
