### ISSUE TITLE
Upgradefrom 1.8 to 2.0 and big folder confirmation limit is enabled

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3561]
### Steps to reproduce
1. Install 1.8.4 client and set it up to sync with some server account.
2. Upgrade to 2.0.*
3. Check the big folder confirmation limit settings

### Expected behaviour
"Ask confirmation before downloading folders larger than" checkbox is off.

### Actual behaviour
"Ask confirmation before downloading folders larger than" checkbox is on with 500MB limit.
This changes the behavior for clients that are upgraded. Previously they would download anything that appeared on the server. After upgrade they will prompt the user when big folders appear.

Was it intentional to automatically turn on this new feature at upgrade?

### Server configuration

ownCloud version: 8.0

### Client configuration
Client version: 1.8.4 then 2.0.0.5351

Operating system: Windows10

OS language: English (US)

Installation path of client: default

**Comment by danimo** [comment]
Yes, adding the limit by default is intentional. //cc @MTRichards
