### ISSUE TITLE
[Multiaccount] Deleting the only account leaves the user with no clue how to add a new account

### ISSUE THREAD

**Issue by jturcotte** [owncloud/client#3564]
= Steps to reproduce:

- Install ownCloud, on the first startup setup your account, complete the wizard
- Figure out that you didn't pick the right one, press the "Delete" button to remove the account
- There is a 10 second timeout, but let's say that you press cancel on that popup

= Result:
The main view is left there, empty. Try to figure out how to re-add an account

= Expected:
The user should know how to re-add an account without having to dig into the UI.
Both moving the Delete button next to the Add Account button, or, showing an Add Account button on the main view would help.

**Comment by jturcotte** [comment]
cc @ogoffart, @jancborchardt

**Comment by jancborchardt** [comment]
Ehm – I mentioned this before in multiple places already, not sure where though:

If the last account is deleted, of course there should still be an account entry. It needs a nice centered empty content message like

> (icon of an account)
> No accounts connected yet
> [ Log in ] button

**Comment by ogoffart** [comment]
Normaly, when you delete all the accounts, the wizard pops up.

It takes ~15 seconds to pupup right now.  Perhaps it should popup directly.

**Comment by jancborchardt** [comment]
Yeah – 15 seconds is wayyy too much. Should be instant.

**Comment by Dianafg76** [comment]
I tested this issue, and it is working OK
Desktop v ownCloud-2.0.0.2613beta1.pkg in MAC
Desktop v testpilotcloud-2.0.0.5373beta1-setup.exe

Closed, Many thanks
