### ISSUE TITLE
[Multiaccount] Deleting an account isn't really deleted if you exit the application

### ISSUE THREAD

**Issue by jturcotte** [owncloud/client#3565]
= Steps

- Delete the account
- Restart the client

= Expected
The deleted account is still deleted and I'm possibly shown the new account wizard like on the first startup

= Actual result
The deleted account is undeleted and tries to sync

**Comment by guruz** [comment]
It's the 1.8 account from the config that gets migrated to the 2.0 format.
It's not the current account being recreated.

**Comment by guruz** [comment]
To clarify: This is to allow users to switch between 1.8 and 2.0 ..

We should probably have code in 2.1 to remove the 1.8 account?

**Comment by guruz** [comment]
FYI @ogoffart

**Comment by jturcotte** [comment]
Not sure how it works internally, but will this also be the case if you migrate from 1.8 to 2.0. Then two years later, after migrating to 2.3, will deleting all accounts bring back the 2 years old 1.8 account?

**Comment by ogoffart** [comment]
@jturcotte yes

**Comment by Dianafg76** [comment]
I tested this issue, and is working OK
Desktop v ownCloud-2.0.2.2713-nightly20150914.pkg 
Closed
