### ISSUE TITLE
[Multiaccount] Only one shibboleth account per server is currently supported

### ISSUE THREAD

**Issue by jturcotte** [owncloud/client#3566]
= Steps
- Empty owncloud.cfg
- Start ownCloud, add a shibboleth account
- Look in owncloud.cfg again

= Expected
Every account configuration is starting with "[0123...]\" in the [Accounts] section

= Actual result
The WritePasswordJob's "shibAssertion" configuration is written directly in the [ownCloud] section, without account number prefix

Does that mean that having two shibboleth account with different user names but the same server wouldn't properly store both keys?

**Comment by jturcotte** [comment]
cc @ogoffart

**Comment by ogoffart** [comment]
Yes, we can only have one shiboleth account per URL.

Not only because of the keychain key which is similar, but also the cookie jar is shared

**Comment by MTRichards** [comment]
@carlaschroder we need to document this in the client notes so that it is clear somewhere that this is the case. Possibly also in the shibboleth app documentation too.

**Comment by carlaschroder** [comment]
Any reason to leave this open?

**Comment by dragotin** [comment]
No, closing.
