### ISSUE TITLE
"Connection Refused"

### ISSUE THREAD

**Issue by mikew** [owncloud/client#3568]
Started happening out of nowhere, on Server 8.0.4 and Client 1.8.4. Users can go to "Modify Account", and obviously have access (they can choose what to sync and the proper folders show up). But once completing that step, the client still says "Connection Refused"

**Comment by guruz** [comment]
If it didn't happen on client or server update, then it sounds like a server/firewall issue..

**Comment by mikew** [comment]
How about when quitting the client fixes the issue ...

**Comment by guruz** [comment]
Which OS?

**Comment by mikew** [comment]
OSX 10.10 (10.10.4 on my machine, not sure which versions others are running, but it's all at least 10.10)

**Comment by mikew** [comment]
Probably worth also mentioning that while settings window / menubar icon displayed "Connection Refused", the client was still happy syncing all the changes that were happening on the server. So it seems something gets way out of sync in the client

**Comment by guruz** [comment]
Did you have more luck recently?
