### ISSUE TITLE
Progress bar causes folders for sync list to jump around

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3569]
### Steps to reproduce
1. Drop down the "folders to sync" tree in the client and start working on browsing the list and selecting/unselecting folders.
2. The client sync happens to wake up for whatever reason (timer, something changed on the server...)
3. Suddenly the "Discovering..." message and the progress bar are visible. The folders to sync list jumps down the screen.
4. When the sync finishes (e.g. if it is just a quick thing to download...) then the progress bar and text goes away and the folders to sync jumps back up the screen.

I was in the process of selecting folders to sync when this happened just as I was clicking - I unselected a folder that I did not intend to. The sync was quick and the progress bar went away, the folder list jumped back up. I was not really sure what I had unselected.

It would be nice if async variable elements of the UI did not disturb the position of user-data-entry elements of the UI.

This is somewhat related to the various comments in #3567 

### Server configuration
ownCloud version: 8.0

### Client configuration
Client version: 2.0.0.5363

Operating system: Windows 10

OS language: English (US)

Installation path of client: default

**Comment by ogoffart** [comment]
@jancborchardt  how can i solve this issue ?  Should the size of the item be constant and be always "bigger" even if the sync is not running?  Or do you have any idea on how to re-design the folder items in the account settings so it does not change size when the sync is running.

**Comment by jancborchardt** [comment]
We already had another issue about this with @ckamm. Can’t remember it atm, but the basic resolution was to show only 3 rows right next to the icon:

> folder name
> progress bar
> details about the progress

**Comment by ckamm** [comment]
@jancborchardt You're looking for #3403 :)

**Comment by ogoffart** [comment]
We could also make it animated. that would make the jump less bad

**Comment by jancborchardt** [comment]
Ideally the height doesn’ŧ change, with the changes proposed in #3403. Then we don’t need to animate it.

**Comment by Dianafg76** [comment]
I tested this issue on Windows 2008 and is working OK
Desktop v ownCloud-2.1.0.5584-nightly20151027-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

Closed

**Comment by phil-davis** [comment]
Version 2.1.0-nightly20151028 (build 5586)
Yes, I agree - there is no more jumping around of the folder tree view.
Thanks!
