### ISSUE TITLE
Folders to Sync list not refreshing in many situations

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3570]
### Steps to reproduce
1. Add a new folder to the client-side - e.g. T111 - with files in it if you like.
2. Wait for it to sync up to the server - works fine.
3. From the client UI, drop down the folder to sync tree

### Expected behaviour
The new folder should appear in the drop down folder tree (and be checked, because all new client-side folders are auto-synced up to the server).

### Actual behaviour
The new folder does not appear in the drop down folder tree.
This means the user cannot later unselect it for sync.

In order to trigger the folder list to refresh, I tried:
a) On the client delete a folder - folder delete is propagated to the server, but the folder is not removed from the folder list.
b) On the server delete a file - file gets deleted on the client but folder list does not refresh. This one should be OK, because a file deletion does not cause any change to the folder hierarchy.
c) On the server delete a folder - folder gets deleted on the client but folder list does not refresh.
d) On the server add a folder smaller than the confirmation limit - folder is synced to the client but folder list does not refresh.
e) On the server add a folder bigger than than the confirmation limit - folder is synced to the client and the folder list does refresh. In this case the user is prompted for action. The code to refresh in this situation was added only recently, fixing the "big folder arriving" workflow - good.
When the refresh happens at (e) it refreshes the whole list, which then reflects all the relevant changes from the other steps.

There is a general need to detect when a sync has happened that has a folder add/remove in either direction and to then refresh the "folders to sync" list.

### Server configuration
ownCloud version: 8.0

### Client configuration
Client version: nightly 2.0.0.5367

Operating system: Windows 10

OS language: English (US)

Installation path of client: default

**Comment by phil-davis** [comment]
I will politely ask if there is any progress on this?
I think it is a bug that will be quite annoying for users. After reorganizing a bunch of folders the drop-down folders-to-sync tree looks very different to the actual folders that exist on the server and client. That makes it difficult or impossible for the user to then sort out what folders to sync.
I was just trying to test some other stuff and ran up against this again, which reminded me to go looking for where I raised this bug report :)

**Comment by ogoffart** [comment]
It will now refresh the list if the sync succeed and that there are new or removed folder during the last sync.

**Comment by guruz** [comment]
New nightly: http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.5404-nightly20150817-setup.exe

**Comment by phil-davis** [comment]
I tried all the cases above and it works with that latest build - thanks.
