### ISSUE TITLE
debian lintian errors with owncloud-client 2.0.0~beta1

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#3572]
Lintian checks got much stronger with the lates OBS update from SUSE. 
We now have many errors that abort the build. (On s2 they are configured as warnings.)
I'll disable lintian checks  to get everything built, but here is the list for review:

osc rbl isv:ownCloud:community:testing/owncloud-client Debian_8.0           x86_64  | grep ' E: '

<pre>
[  569s] E: owncloud-client: arch-dependent-file-not-in-arch-specific-directory usr/bin/owncloud
[  569s] E: owncloud-client: binary-or-shlib-defines-rpath usr/bin/owncloud /usr/lib/x86_64-linux-gnu/owncloud
[  569s] E: owncloud-client: arch-dependent-file-not-in-arch-specific-directory usr/bin/owncloudcmd
[  569s] E: owncloud-client: binary-or-shlib-defines-rpath usr/bin/owncloudcmd /usr/lib/x86_64-linux-gnu/owncloud
[  569s] E: owncloud-client: copyright-should-refer-to-common-license-file-for-gpl
[  569s] E: owncloud-client: possible-gpl-code-linked-with-openssl
[  570s] E: owncloud-client-nautilus: copyright-should-refer-to-common-license-file-for-gpl
[  570s] E: libowncloudsync0: copyright-should-refer-to-common-license-file-for-gpl
[  570s] E: libowncloudsync0: possible-gpl-code-linked-with-openssl
[  570s] E: libowncloudsync-dev: copyright-should-refer-to-common-license-file-for-gpl
[  570s] E: owncloud-client-l10n: copyright-should-refer-to-common-license-file-for-gpl
[  570s] E: owncloud-client-l10n: description-synopsis-is-duplicated
[  570s] E: owncloud-client-doc: copyright-should-refer-to-common-license-file-for-gpl
</pre>

**Comment by hefee** [comment]
On debian the lintian error/warnings are fixed:
http://anonscm.debian.org/cgit/pkg-owncloud/owncloud-client.git

(only the rpath warning is not fixed)

**Comment by dragotin** [comment]
@jnweiger how to enable linitian on obs? I tried the current nightly packages on my machine but they so not seem to have lintian enabled. Somebody added lintian overrides files to the package, maybe that fixes it already?

**Comment by guruz** [comment]
@hefee Is it a solution to just copy over the lintian stuff from https://anonscm.debian.org/cgit/pkg-owncloud/owncloud-client.git/tree/debian?id=9f7b62296252d51b89584a67589d685fe3265d29 and close the issue here?

**Comment by hefee** [comment]
@guruz: I think this can be closed? Because it looks like the issue was fixed on obs.
