### ISSUE TITLE
Failing large file upload through L2TP IPSEC VPN tunnel

### ISSUE THREAD

**Issue by christiankral** [owncloud/client#3574]
# Server
 * Ubuntu 14.04 32 bit
 * ownCloud 8.1.0
 * PHP 5.5.27-1
 * MariaDB 5.5
 * HTTP connection (no HTTPS)

The server provides the following services

 * SAMBA (network drive)
 * SVN (subversion)
 * TRAC (issue tracking)
 * owncloud (newly installed)

# Client

The client always connects to the server through an L2TP IPSEC VPN connection.

 * Ubuntu 14.04 32 bit
 * ownCloud client 1.8.4-1
 * L2TP IPsec VPN Manager 1.0.9

# VPN router 

 * Zyxel ZyWALL USG 20W 

# Failure description
## General problem
 
When I tested to upload files to owncloud it works fine with smaller files. When reaching a file size von about 2-5MB the IPSEC connection dropped the connection for no obvious reason. The VPN client error message is stuff like

`check_control: Received out of order control packet on tunnel 48061`

The VPN router states

`IPSEC: Destroying tunnel ID 48061 due to no connectivity to its peer within 121s...`

## Other owncloud connections

However, I was able to upload 30MB through

 * owncloud web interface
 * WEBDAV
 * SAMBA
 
Those file transfers were no problem at all. 
 
## Parallel connections

I started the owncloud client with

`export OWNCLOUD_MAX_PARALLEL=1`

I tried to upload a 60MB file. The first attempt to upload this file failed after 40MB. I just re-tried the upload with the same settings and then it worked without failure. After that I tried to upload 150MB file and that failed after 100MB. 

This looks like there is a problem with parallel uploads when routed through an L2TP IPSEC VPN tunnel.

**Comment by phil-davis** [comment]
You could try the 2.0.0beta1 available at https://owncloud.org/install/#testing-development
an report if it also has the same issue.
Big transfers could also be impacted by MTU issues on a VPN link. If maximum-sized packets to not successfully traverse the VPN link then there will be trouble. But it sounds like your transfers are getting far enough that (at least some) big packets have made it through the VPN tunnel.

**Comment by guruz** [comment]
Are you sure the client is actually syncing through the VPN (and not via public IP or another route?)

> IPSEC: Destroying tunnel ID 48061 due to no connectivity to its peer within 121s...

**Comment by guruz** [comment]
Please try 2.1rc1 or other means of support
https://owncloud.org/support/
