### ISSUE TITLE
"Choose what to sync" does not show proper file sizes on S3

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/client#3575]
OS X 10.10 on the client beta. – Is this a known issue? 

(Note: The empty lines there are just redacted)
![2015-08-10_11-22-40](https://cloud.githubusercontent.com/assets/878997/9166271/619cf9ee-3f52-11e5-9ee3-f6101649e9c5.png)

**Comment by guruz** [comment]
@PVince81 Known issue with shared folder sizes?

**Comment by danimo** [comment]
@LukasReschke It's what the server reports... Known issue, and afaik supposed to be that way :/

**Comment by PVince81** [comment]
S3 is still on 8.0.2 ... please update first.

**Comment by LukasReschke** [comment]
@msrex

**Comment by msrex** [comment]
We will update in the next 3 weeks.

**Comment by ogoffart** [comment]
Is this still a problem?

**Comment by msrex** [comment]
s3 was updated to 8.2.0 last week. No idea if this is gone. We found a few other issues but they were unrelated to this one I think/hope.

**Comment by dragotin** [comment]
For me the sizes of s3 look very reasonable in the client, that would mean this is fixed for me.
