### ISSUE TITLE
[Aliases] Show something more useful in "Folder" column in activity tab

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/client#3576]
![](https://s3.owncloud.com/owncloud/index.php/s/kmpxDSykbinK8Dp/download)
![](https://s3.owncloud.com/owncloud/index.php/s/M5pQT9J9wu1DP6J/download)

**Comment by LukasReschke** [comment]
Also shown wrong in the overview:

![](https://s3.owncloud.com/owncloud/index.php/s/wdeiresJUKpphjn/download)

**Comment by ckamm** [comment]
@LukasReschke What exactly is the wrong thing that's shown? You're complaining about the alias name "ownCloud1" instead of the real folder name? We agree the alias name is unnecessary and it will be removed eventually, see #783.

**Comment by LukasReschke** [comment]
> @LukasReschke What exactly is the wrong thing that's shown? You're disliking that it shows the alias name "ownCloud1" instead of the real folder name? 

Yes. It is _really_ confusing.

> We agree the alias name is unnecessary and it will be removed eventually, see #783.

Set #738 to 2.0 and close this then?

**Comment by ckamm** [comment]
@LukasReschke We're already in bugfix-only mode for 2.0. Let's do it for 2.1!

**Comment by guruz** [comment]
Reopening, we could just show the local filename of the path there instead of the alias.

**Comment by ckamm** [comment]
Sure, but then you potentially have duplicate or ambiguous menu options.

**Comment by guruz** [comment]
In the latest nightly you should see the full folder in the tray menu.
In the main settings dialog you should not see the alias either.

Still missing: Show something instead of the alias in the activity list.

**Comment by Dianafg76** [comment]
@guruz Hi, I tested this issue, and now I see the real folder name
![screen shot 2015-08-13 at 10 46 25](https://cloud.githubusercontent.com/assets/12032058/9245970/989d10d4-41a8-11e5-948e-e662f55cbe76.png)

**Comment by jancborchardt** [comment]
@guruz can we remove the technical-looking folder prefixes and rename it to simply: `Open folder user5`? The `/Users/Diana/` and the last slash are not necessary when it’s just in the home folder.

**Comment by Dianafg76** [comment]
If you click en Remove Folder, could be changed the alias name "owncloud1" by the name of the actual folder ?
![screen shot 2015-08-13 at 14 34 20](https://cloud.githubusercontent.com/assets/12032058/9249876/0b2e3e6e-41c9-11e5-8dff-9bfff8629076.png)

**Comment by jancborchardt** [comment]
We should not show the »Alias« **anywhere**. It should be basically removed. Only use the local folder name pleae @guruz

**Comment by guruz** [comment]
I know I know.. that's why the issue is not ReadyToTest.. because the way the code is structured it's not that easy to get it done quickly.

**Comment by Dianafg76** [comment]
@guruz Many Thanks

**Comment by jancborchardt** [comment]
@guruz thanks! :) Just making sure

**Comment by ogoffart** [comment]
What should we show in the activity tab then?
The full local folder path? (that would be the only other thing that would not be ambiguous)

**Comment by jancborchardt** [comment]
Only the full local folder path if it’s needed. If it’s simply something in the users home folder, only show the folder / subfolder path from the home folder on.

**Comment by jancborchardt** [comment]
So if it’s `/var/www/blawhatever` show that. But if it’s `/home/jan/ownCloud/` only shown `ownCloud` (no slashes, no previous path.

**Comment by guruz** [comment]
Looks good!
