### ISSUE TITLE
Why is no domain shown in in the settings?

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/client#3577]
I really think we should show the domain as well. There are very legitimate use-cases for example with having a  `mycloud.ch` and also a `mycloud.com` with different content.

![](https://s3.owncloud.com/owncloud/index.php/s/fK8EDjUl1vjhSza/download)

cc @jancborchardt

**Comment by LukasReschke** [comment]
Also will lead to confusion with different ownClouds on the same domain. A common setup for SSL proxies (though they are anyways better to avoid…)

**Comment by MorrisJobke** [comment]
Why not reduce the font size of the domain and make it gray?

@jancborchardt

**Comment by MorrisJobke** [comment]
While at it you can also move the "Activity", "General" and "Network" entries to the right. Like it is on all other platforms. @dragotin and @michaelstingl already discussed this some time back and @jancborchardt is fine with it.

**Comment by LukasReschke** [comment]
OS X windows are auto-resizing, this would mean that the menu items are at a different place. IMHO not the best UX ;-)

(if the window needs more place it will get larger and the icons would then move right as well)

**Comment by guruz** [comment]
Every decision is always a compromise, see also https://github.com/owncloud/client/issues/3516
You see the full hostname and credentials in the tab itself..

Maybe we need a third line with the path ;-)

**Comment by jancborchardt** [comment]
Just for clarification: It was never in any design to cut the domain extension. When I saw it (I assume it was done by @guruz) I thought it was a neat idea to keep the domain short.

But I can see how it’s confusing. Just show the domain extension there. No – no greying, no newline (!), no subfolder. Just show the base domain with subdomain properly.
The full domain with subfolder will be shown in the details: »Connected to https://example.com/subfolder/blah as username«. k?

**Comment by guruz** [comment]
@jancborchardt That makes stuff too wide then, button-wise..
The current code cuts away "www." and I was thinking of also cutting "cloud." and "sync.". What do you think of that?
(The goal is to not cut other stuff because it might matter, e.g. "testinstance." or "beta."

**Comment by LukasReschke** [comment]
+1 for `cloud`, `owncloud`, `sync`, etc. Would make it more stringent at least ;-)

**Comment by jancborchardt** [comment]
@guruz yeah, that's ok. But cutting of a domain extension seems strange, no?
We need to ellipsize anyway, so stuff will be cut off then. The ellipsis is at least a hint that smth is missing.

**Comment by guruz** [comment]
So you'd elipsize everything to "...mydomain..."? How is that good?

**Comment by jancborchardt** [comment]
@guruz no, don’t act dumb please. :D It’s just regular text ellipsizing on the right. Like it will say:

> name
> example.com

and that’s short enough. But for longer domains like »somesubdomain.whateverthisdumbexampledomainislike.com« it will show:

> name
> somesubdomain.whateverthisd…

Or even ellipsize earlier.

**Comment by jancborchardt** [comment]
Another reason to not cut the extension (and maybe not even subdomains chosen by arbitrary keywords): For me it would then show:

> jan
> jancborchardt

Which just looks really strange. And that would happen for most self-hosted instances, which kind of is a big target audience.

**Comment by Dianafg76** [comment]
I tested this issue and now I can see th domain 
![screen shot 2015-11-17 at 14 26 38](https://cloud.githubusercontent.com/assets/12032058/11212637/5dda097c-8d37-11e5-9463-d3dbaa2f74e0.png)
Desktop v ownCloud-2.1.0.5630-nightly20151117-setup.exe on WINDOWS
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}
