### ISSUE TITLE
Upload speed can be a crazy high number

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3579]
ownCloud client 2.0.0beta1 on Windows 10.
Sometimes when uploading (and I think when downloading also) the speed calculation can go crazy high. Once that happens the calculation seems to stay high for the remainder of the upload progress bar displaying. I managed to get many TB/sec of upload on my 1Mbps link here in western Nepal - I wish it was true :)
![owncloud-crazy-speed](https://cloud.githubusercontent.com/assets/1535615/9170457/bd90ac70-3f82-11e5-8745-64e9a199033f.png)

**Comment by phil-davis** [comment]
Low priority - nothing actually goes wrong, it just makes me drool for the day when I have an internet connection this fast.

**Comment by ckamm** [comment]
This is surprising. The transfer speed update that happens every second is a simple exponential average:
```
bytesPerSec = s * bytesPerSec + (1-s) * (bytesCompleted - prevBytesCompleted)
prevBytesCompleted = bytesCompleted
```

For that term to jump to the TB range, the difference would have to be huge. I'll look at it some more.

**Comment by ckamm** [comment]
@phil-davis If this still happens, please let me know!

**Comment by guruz** [comment]
New nightly for Windows http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.5388-nightly20150811-setup.exe

**Comment by Dianafg76** [comment]
It is working OK
Many Thanks
Closed

**Comment by phil-davis** [comment]
I have also done a few tests of adding new folders on the client with various mixes of file sizes inside and I have not seen the issue any more.
