### ISSUE TITLE
[Multiaccount, Beta1] When you Create a New Folder, and wait to Sync, I see a duplicate entry in activity list

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3580]
### Steps to reproduce
1. Install the last version 2.0.0 (2.0.0.5381)
2. rigth click to the Icon oC
3. Select the user
4. Select the Open folder 'ownCloud'
5. Create a New Folder
6. Wait to Sync
7. Go to the Activity Option

### Expected behaviour
You should see a single line

### Actual behaviour
Once synchronization is complete , I see two equal lines
In Windows:
![screen shot 2015-08-10 at 14 40 22](https://cloud.githubusercontent.com/assets/12032058/9171656/c5ac144a-3f6d-11e5-9e0e-e8f4c44eab0c.png)
In Mac:
![screen shot 2015-08-10 at 14 42 59](https://cloud.githubusercontent.com/assets/12032058/9171724/304371c2-3f6e-11e5-9636-c419b3c741ee.png)

### Server configuration
Desktop v 2.0.0 (build 5381)
Desktop v 2.0.0beta1 (build 2613)
Server v {"installed":true,"maintenance":false,"version":"8.1.1.2","versionstring":"8.1.1 RC1","edition":"Enterprise"}

**Comment by ckamm** [comment]
I can reproduce this on linux.

**Comment by ckamm** [comment]
We've started to emit the completed() signal for PropagateDirectory jobs and that lead to spurious entries in the activity log. The patch makes the protocol widget skip them.

**Comment by Dianafg76** [comment]
@ckamm  It is working fine with Desktop vownCloud-2.0.0.2623-nightly20150812.pkg.
Many Thanks
Closed
