### ISSUE TITLE
Files on External storage (SMB) keep on downloading repeatedly

### ISSUE THREAD

**Issue by caguiar** [owncloud/client#3581]
ownCloud Client: 1.8.4 (Mac OS)
ownCloud Server:  8.1.0
Server OS: uBuntu Server 14.04.2 LTS

Lately (I would say since the upgrade of ownCloud server to 8.1) my desktop client repeatedly downloads files which are on my desktop already.
It seems that for no particular reason it just downloads all the files (and subfolders) of a particular folder.
This seems to happen only with files/folders which reside on SMB shares that are configured as External storage.

If you require any further details, please let me know.

**Comment by guruz** [comment]
Can I ask you to re-open this in https://github.com/owncloud/core ? (and link to the issue here)

Thanks.

FYI @PVince81
