### ISSUE TITLE
[Design] Top bar nearly unreadable in white-on-black color theme.

### ISSUE THREAD

**Issue by ftiede** [owncloud/client#3582]
I'm using the Desktop Client 1.8 currently and its top bar (for switching between different displays) defaults to a white background while using the current color theme's default foreground text color, which renders the icon texts nearly unreadable, see attached ![owncloud-client](https://cloud.githubusercontent.com/assets/13375435/9182096/10c662f6-3fa9-11e5-81b0-eedb36d390a5.png).

For version 2.0 I'm afraid the same might happen from the screenshots I saw.

So I am asking for the application to either use all colors from the current color theme or define all colors itself to avoid unreadable GUI.

**Comment by guruz** [comment]
CC @jturcotte @phil-davis 
https://github.com/owncloud/client/issues/2654#issuecomment-129411669

**Comment by guruz** [comment]
New nightly for Windows http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.5388-nightly20150811-setup.exe

**Comment by phil-davis** [comment]
Note some test results at https://github.com/owncloud/client/issues/2654#issuecomment-129846728
In Windows 10 the High Contrast 1 and High Contrast Black themes have some icons that are so dark grey that they can hardly be seen on the black background.
@ftiede Try the latest 2.0.0.* client on your system and theme and see what it is like.

**Comment by danimo** [comment]
Fixed

**Comment by phil-davis** [comment]
Works for me 2.0.0.5390 on Windows 10.
