### ISSUE TITLE
[Multiaccount] If you delete an account it stays in the accounts toolbar

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3583]
### Steps to reproduce
1. You need install the v2.0.0, with one user
2. Right click on icon oC
3. Select the Settings.. option
4. Select the option General
5. Click in Add an Account
6. Introduce the Server Address
7. Click in Next
8. Accept the Certificate
9. Introduce the Username/Password (eg user19)
10. Click in the option "Skip folders configuration"
11. Go to Settings.. option
12. Select the user19@.....
13. Select Delete
14. Click in YES

### Expected behaviour
should be removed the account

### Actual behaviour
The account with the name user19 it is not deleted
![screen shot 2015-08-11 at 09 56 11](https://cloud.githubusercontent.com/assets/12032058/9192890/589f8916-400f-11e5-8811-c43d998097fb.png)

### Server configuration
Desktop v 2.0.0 (build 5384)
Server v {"installed":true,"maintenance":false,"version":"8.1.1.2","versionstring":"8.1.1 RC1","edition":"Enterprise"}

**Comment by phil-davis** [comment]
I just tried "randomly" deleting one of the 4 accounts configured on my ownCloud client 2.0.0.5384.
The account icon remains in the top row, but actually when it is clicked on the screen area underneath does not change (it keeps displaying account state from the previously-selected account).
If I "Quit ownCloud" and run the client again it displays just the remaining 3 accounts. So the account has been deleted from the config. I guess it is just a refresh issue on the client UI - after a delete the list of account icons to display should be rebuilt.
![owncloud-after-account-delete](https://cloud.githubusercontent.com/assets/1535615/9193618/867e6134-4034-11e5-990e-cc5c21ba9350.png)

**Comment by guruz** [comment]
@Dianafg76 Did this always work on OS X?
(OS X is using a different settingsdialog code..)

**Comment by Dianafg76** [comment]
@guruz In OS X it is working OK

**Comment by guruz** [comment]
New nightly for Windows http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.5388-nightly20150811-setup.exe

**Comment by phil-davis** [comment]
ownCloud 2.0.0.5388 on Windows 10 - works for me now.

**Comment by ckamm** [comment]
@phil-davis Thanks for testing!
