### ISSUE TITLE
[Beta1, regression] In v 2.0.0 I don't have the Pause button

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3584]
### Steps to reproduce
1. You need install v 2.0.0
2. Upload a fiel/folder (1GB)
3. I want to Pause the upload

### Actual behaviour
In version 1.8.4 had the pause button , but no in v2.0.0

### Server configuration
Desktop v 2.0.0 (build 2621)

**Comment by guruz** [comment]
The only way to pause is right-click on the folder.
There is nothing in tray or UI.

**Comment by phil-davis** [comment]
Yes, I have been successfully using the right-click menu there to Pause and then Resume. It is a handy way to make the client immediately check sync again without waiting for something to happen.

**Comment by jancborchardt** [comment]
Design-wise, there should be a menu button (three dots for example) on the right of the entry of the sync folder in the list which also makes these actions accessible. We should never rely on right-click anywhere.

**Comment by Dianafg76** [comment]
I don't have the Resume Button, and the Remove button
In v1.8.4
![screen shot 2015-08-11 at 16 44 01](https://cloud.githubusercontent.com/assets/12032058/9200548/a7213bb4-4048-11e5-99b3-f48f7dabcea8.png)

In Beta1
![screen shot 2015-08-11 at 16 45 16](https://cloud.githubusercontent.com/assets/12032058/9200570/be6d646e-4048-11e5-8c45-fb152b1033b3.png)

**Comment by jancborchardt** [comment]
@Dianafg76 I know. What I was saying is that the intention is that it should be there. Meaning @dragotin @ogoffart please put it there. :)

**Comment by alichakery** [comment]
I have the same issue in both windows and Mac (the pause button issue)

Thank you

**Comment by ogoffart** [comment]
I added a little button to access the context menu:

![ocld](https://cloud.githubusercontent.com/assets/959326/9248204/22c82e04-41ba-11e5-82a0-98a4524bb749.png)

**Comment by Dianafg76** [comment]
@ogoffart I tested this issue and now i see the button access
But one thing, You can delete the triangle above the button ?, pleaseee
![screen shot 2015-08-13 at 13 18 32](https://cloud.githubusercontent.com/assets/12032058/9248693/382457c4-41be-11e5-8c09-04439ab40d26.png)

**Comment by Dianafg76** [comment]
Desktop vownCloud-2.0.0.2626-nightly20150813.pkg

**Comment by jancborchardt** [comment]
Nice @ogoffart! Can you make the menu open to the left as well? It looks very strange hanging out of the dialog.

**Comment by jancborchardt** [comment]
@ogoffart also, please sort it as we discussed:

* Open folder
* Pause sync
* Remove folder

The removal option should always be last.

**Comment by phil-davis** [comment]
client 2.0.0.5395
The triangle above the button is gone - good.
The options are in the required order - good.

**Comment by guruz** [comment]
@ogoffart The button is too low, it hangs into the progress display "file x of y"
I also wonder can you get rid of the hilight background color?

**Comment by ogoffart** [comment]
The way the tree view open is platform dependents and it is doing it the way every tree view open with double click and using the platform specific icon for the tree.
The position of the popup is also decided by Qt depending on where we click it shows the popup there.  when the windows in at the edge of the screen the popup is correctly placed.
