### ISSUE TITLE
Setup wizard: More whitespace between »Server« and »Local folder« rows

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#3588]
See:
![](https://owncloud.org/wp-content/uploads/2015/08/testpilot-1.png)

The server and local folder rows stick too much together. A bit of vertical whitespace would do a lot of good in helping people to separate the entries mentally.

@ogoffart maybe?

**Comment by Dianafg76** [comment]
@ogoffart I tried this problem and there are now a bit of vertical whitespace
![screen shot 2015-08-13 at 13 30 03](https://cloud.githubusercontent.com/assets/12032058/9248863/e5d46674-41bf-11e5-9bd5-8948e4a95edb.png)

Many thanks
Closed

**Comment by jancborchardt** [comment]
@ogoffart I was just asking about spacing between the rows of »Server« and »Local folder«. :) Now there’s also space between the server logo and the »Server« sentence« and between the Local folder icon and the »Local Folder« text and the radio buttons. Those ones should be removed again. :)

**Comment by ogoffart** [comment]
I did not change the spacing between the logo and the server sentence.
It's just that on the screenshot the layout is different because of the different checkboxes.  But I can also try to avoid the space there.

**Comment by jancborchardt** [comment]
Yeah, that would be cool :)

If you did it, can you supply another screenshot please? That makes it easier for every designer to review. Thanks!

**Comment by ogoffart** [comment]
![oooo1](https://cloud.githubusercontent.com/assets/959326/9250918/b3f5964e-41d0-11e5-8c82-11bad60c4d80.png)
![oooo2](https://cloud.githubusercontent.com/assets/959326/9250919/b3fa5b20-41d0-11e5-942a-9269af400932.png)

**Comment by jancborchardt** [comment]
@ogoffart much better! It would be cool to have the »Server« text a bit higher up, and the »Lokaler Ordner« text to be the same position in the first screenshot as it is in the second one.

**Comment by ogoffart** [comment]
![oooo3](https://cloud.githubusercontent.com/assets/959326/9273357/62278f22-428c-11e5-88f9-d9442e48da31.png)

**Comment by phil-davis** [comment]
Looks like that for me on Windows - Version 2.0.0beta2 (build 5397)
And it is very nice now to be able to select and copy the version text in General, About.

**Comment by jancborchardt** [comment]
@ogoffart looks good! Thanks

**Comment by Dianafg76** [comment]
closed
