### ISSUE TITLE
[Overlays] When you remove the Network the icon it is not working well

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3590]
### Steps to reproduce
1. You need install Desktop v 2.0.0beta1
2. Upload a fiel/folder (1GB)
3. Remove the Network

### Expected behaviour
All icons should appear in red

### Actual behaviour
the icon it is not working well
![screen shot 2015-08-11 at 17 13 43](https://cloud.githubusercontent.com/assets/12032058/9201388/241700a0-404d-11e5-82ad-016706925628.png)

### Server configuration
Desktop v 2.0.0beta1 (build 2613)
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
I tried esta problem with desktop v ownCloud - 2.0.2.2695 - nightly20150902.pkg and Al upload a large file (1 GB ) and remove the network, I have four different icons for the same account.
Which is correct?
![screen shot 2015-09-02 at 15 48 31](https://cloud.githubusercontent.com/assets/12032058/9633222/f6f9934e-518b-11e5-84d7-45ef10b53e5d.png)

**Comment by jturcotte** [comment]
Should be decided together with issue #3616.

**Comment by Dianafg76** [comment]
It is the same in Desktop v ownCloud-2.0.2.2752-nightly20150929.pkg

**Comment by ckamm** [comment]
I think #3616 includes this as a special case.
