### ISSUE TITLE
Better message (or no message at all?) than "Operation timed out" when you remove the Network 

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3591]
### Steps to reproduce
1. You need install Desktop v 2.0.0beta1
2. Upload a fiel/folder (1GB)
3. Remove the Network
### Expected behaviour

Tell us what should happen
### Actual behaviour

If you remove the Network, the second time appears "Operation timed out"
![screen shot 2015-08-11 at 17 13 52](https://cloud.githubusercontent.com/assets/12032058/9201616/3e7de188-404e-11e5-8d72-af1cbf3c2dcc.png)

Log:
`08-11 17:05:40:497 0x7f8845c17580 unknown: ERRORING CURRENT QHttpNetworkReply(0x7f88461768b0)  QUrl( "xxx/remote.php/webdav/1Gfile/1G.file-chunking-1117274722-205-40" ) 
08-11 17:05:40:498 0x7f8843766e30 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 99 "Operation timed out" QVariant(Invalid)
08-11 17:05:40:498 0x7f8843766e30 OCC::PropagateUploadFileQNAM::slotPutFinished: void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "xxx/remote.php/webdav/1Gfile/1G.file-chunking-1117274722-205-40" )  FINISHED WITH STATUS 99 "Operation timed out" QVariant(Invalid) QVariant(Invalid)
08-11 17:05:40:499 0x7f8843766e30 OCC::PropagateUploadFileQNAM::slotPutFinished: ""
08-11 17:05:40:499 0x7f8843766e30 OCC::PropagateUploadFileQNAM::abort: virtual void OCC::PropagateUploadFileQNAM::abort() OCC::PUTFileJob(0x7f8846161cd0) "1Gfile/1G.file"
08-11 17:05:40:499 0x7f8843766e30 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 5 "Operation canceled" QVariant(Invalid)
08-11 17:05:40:499 0x7f8843766e30 OCC::PropagateUploadFileQNAM::slotPutFinished: void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "xxx/remote.php/webdav/1Gfile/1G.file-chunking-1117274722-205-38" )  FINISHED WITH STATUS 5 "Operation canceled" QVariant(Invalid) QVariant(Invalid)
08-11 17:05:40:500 0x7f8843766e30 OCC::PropagateUploadFileQNAM::abort: virtual void OCC::PropagateUploadFileQNAM::abort() OCC::PUTFileJob(0x7f8845c2e860) "1Gfile/1G.file"
08-11 17:05:40:500 0x7f8843766e30 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 5 "Operation canceled" QVariant(Invalid)
08-11 17:05:40:501 0x7f8843766e30 OCC::PropagateUploadFileQNAM::slotPutFinished: void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "xxx/remote.php/webdav/1Gfile/1G.file-chunking-1117274722-205-39" )  FINISHED WITH STATUS 5 "Operation canceled" QVariant(Invalid) QVariant(Invalid)
08-11 17:05:40:501 0x7f8843766e30 OCC::SyncEngine::slotJobCompleted: void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem &) "1Gfile/1G.file" INSTRUCTION_NEW 1 "Operation timed out"
08-11 17:05:40:503 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:/Users/Diana/user2beta1/1Gfile/1G.file"
08-11 17:05:40:504 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:/Users/Diana/user2beta1/1Gfile/1G.file"
08-11 17:05:40:506 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:/Users/Diana/user2beta1/1Gfile/1G.file"
08-11 17:05:40:506 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:/Users/Diana/user2beta1/1Gfile/1G.file"
08-11 17:05:40:497 0x7f8845c17580 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7f8845c033d0) QObject(0x0)  0 false 3 16
08-11 17:05:40:500 0x7f8845c17580 unknown: void QHttpNetworkConnectionChannel::close() QSslSocket(0x7f8845ad6170) 2 QObject(0x0) 
08-11 17:05:40:500 0x7f8845c17580 unknown: QIODevice::write: device not open
08-11 17:05:40:500 0x7f8845c17580 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7f8845ad6170) QObject(0x0)  0 false 3 16 QAbstractSocket::ClosingState
08-11 17:05:40:501 0x7f8845c17580 unknown: void QHttpNetworkConnectionChannel::close() QSslSocket(0x7f8845cd83e0) 2 QObject(0x0) 
08-11 17:05:40:501 0x7f8845c17580 unknown: QIODevice::write: device not open
08-11 17:05:40:501 0x7f8845c17580 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::NetworkError QSslSocket(0x7f8845cd83e0) QObject(0x0)  0 false 3 16 QAbstractSocket::ClosingState
08-11 17:05:40:516 0x7f8843766e30 OCC::SyncEngine::slotJobCompleted: void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem &) "1Gfile" INSTRUCTION_SYNC 0 ""
08-11 17:05:40:518 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/Diana/user2beta1/1Gfile"
08-11 17:05:40:519 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/Diana/user2beta1/1Gfile"
08-11 17:05:40:520 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/Diana/user2beta1/1Gfile"
08-11 17:05:40:521 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/Diana/user2beta1/1Gfile"
08-11 17:05:40:544 0x7f8843766e30 OCC::SyncEngine::slotJobCompleted: void OCC::SyncEngine::slotJobCompleted(const OCC::SyncFileItem &) "" INSTRUCTION_NONE 0 ""
08-11 17:05:40:545 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/Diana/user2beta1/"
08-11 17:05:40:545 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/Diana/user2beta1/"
08-11 17:05:40:546 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/Diana/user2beta1/"
08-11 17:05:40:547 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/Diana/user2beta1/"
08-11 17:05:40:571 0x7f8843766e30 OCC::SyncJournalDb::walCheckpoint: void OCC::SyncJournalDb::walCheckpoint() took 0 msec
08-11 17:05:40:571 0x7f8843766e30 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString &, bool) Transaction commit  "All Finished." 
08-11 17:05:40:571 0x7f8843766e30 OCC::SyncEngine::finalize: CSync run took  42563
08-11 17:05:40:572 0x7f8843766e30 OCC::BandwidthManager::~BandwidthManager: virtual OCC::BandwidthManager::~BandwidthManager()
08-11 17:05:40:573 0x7f8843766e30 OCC::Folder::slotSyncFinished:  - client version 2.0.0beta1 (build 2613)  Qt 5.4.0  SSL  OpenSSL 1.0.2d 9 Jul 2015
08-11 17:05:40:574 0x7f8843766e30 OCC::Folder::slotSyncFinished: -> SyncEngine finished with ERROR, warn count is 1
08-11 17:05:40:574 0x7f8843766e30 OCC::Folder::bubbleUpSyncResult: Processing result list and logging took  0  Milliseconds.
08-11 17:05:40:575 0x7f8843766e30 OCC::sendOsXUserNotification: void OCC::sendOsXUserNotification(const QString &, const QString &) "Sync Activity" "1Gfile/1G.file could not be synced due to an error. See the log for details."
08-11 17:05:40:575 0x7f8843766e30 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result:  3
08-11 17:05:40:575 0x7f8843766e30 OCC::Folder::slotSyncFinished:   ** error Strings:  ("Operation timed out", "1Gfile/1G.file: Operation timed out")
08-11 17:05:40:575 0x7f8843766e30 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
08-11 17:05:40:576 0x7f8843766e30 OCC::Folder::slotSyncFinished: the last 2 syncs failed
08-11 17:05:40:576 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:/Users/Diana/user2beta1/"
08-11 17:05:40:577 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:/Users/Diana/user2beta1/"
08-11 17:05:40:577 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:/Users/Diana/user2beta1/"
08-11 17:05:40:578 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:/Users/Diana/user2beta1/"
08-11 17:05:40:579 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:/Users/Diana/user2beta1/"
08-11 17:05:40:579 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:/Users/Diana/user2beta1/"
08-11 17:05:40:580 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:/Users/Diana/user2beta1/"
08-11 17:05:40:580 0x7f8843766e30 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:/Users/Diana/user2beta1/"
08-11 17:05:40:581 0x7f8843766e30 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7f8845a4ec50)  with name  "ownCloud"
08-11 17:05:40:581 0x7f8843766e30 OCC::ownCloudGui::slotComputeOverallSyncStatus: Folder in overallStatus Message:  OCC::Folder(0x7f88434e0df0)  with name  "ownCloud1"
08-11 17:05:40:582 0x7f8843766e30 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "ownCloud1" :  "Error"
08-11 17:05:40:783 0x7f8843766e30 OCC::FolderMan::slotFolderSyncFinished: <===================================== sync finished for  "ownCloud1"
08-11 17:05:40:886 0x7f8845c17580 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7f8845ad6170) QObject(0x0)  0 false 2 16 QAbstractSocket::ClosingState`
### Server configuration

Desktop v 2.0.0beta1 (build 2613)
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by guruz** [comment]
What's the exact issue?

> If you remove the Network, the second time appears "Operation timed out"

Do you mean first "Network unreachable", then later "Operation timed out"?

**Comment by Dianafg76** [comment]
@guruz The first time you remove the network and it is appears "Network unreachable"--> OK
Connect network and remove the network again and it is appears "Operation timed out" --> This is correct?

**Comment by guruz** [comment]
but then afterwards it works?

**Comment by Dianafg76** [comment]
Yes

**Comment by ogoffart** [comment]
I think that's correct, If you cut the network as the request have started already, you will get a timeout.
What could we do better?

**Comment by phil-davis** [comment]
I tested a few of these combinations the other day, disconnecting the network at different physical places and doing it while sync was in progress. I thought that the "timeout" message was clear. What else can you say? The client was talking to the server, waited for a response and after some time it gave up. That is the meaning of "timeout".

**Comment by guruz** [comment]
@jancborchardt What do you think?

In theory if we should maybe not show anything because it might bother users when switching their network.

**Comment by Dianafg76** [comment]
It is the same in Desktop v ownCloud-2.0.2.2752-nightly20150929.pkg

**Comment by jancborchardt** [comment]
It seems mostly a wording issue. What about »Server unreachable«? Rather than »Network unreachable« and the very technical »Operation timed out«?

**Comment by TheOneRing** [comment]
Please re open if the issue still exists
