### ISSUE TITLE
[Beta1] I can't connect with HTTP

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3592]
### Steps to reproduce
1. You need install Desktop v2.0.0Beta1
2. Introduce the Server Address with HTTP

### Expected behaviour
You should be able to connect with HTTP

### Actual behaviour
Appears the error:
![screen shot 2015-08-11 at 18 00 09](https://cloud.githubusercontent.com/assets/12032058/9202593/e8ca0d16-4052-11e5-8e4b-93e89688d64a.png)

### Server configuration
Desktop v 2.0.0beta1 (build 2613)
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by danimo** [comment]
This also works for me with latest 2.0 snapshots. More details, pls

**Comment by guruz** [comment]
Does it work with another server?

**Comment by Dianafg76** [comment]
@danimo Sorry, I try this morning, and it is working OK
Closed
