### ISSUE TITLE
Underline of right navigation entries in settings dialog

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#3594]
Check this out, seems to happen since the username is two-line:
![capture du 2015-08-11 18-33-26](https://cloud.githubusercontent.com/assets/925062/9203467/a64e6f2c-4057-11e5-8889-828571242334.png)

cc @ogoffart @guruz

**Comment by danimo** [comment]
Fixed

**Comment by jancborchardt** [comment]
Thx!
