### ISSUE TITLE
Double-click ownCloud sync status area opens the wrong folder

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3595]
2.0.0.5390 Windows 10
All the account instances are now showing the "famous" alias name as just "ownCloud". Previously they showed "ownCloud1" "ownCloud2"...
When I double-click any that are not "the real original ownCloud aliased account", the folder for "the real original ownCloud aliased account" is opened, not the folder for the account in question.
Attachment gives an example:
![owncloud-open-associated-folder](https://cloud.githubusercontent.com/assets/1535615/9204517/87afe3c2-407d-11e5-85f1-ec0121af1d73.png)

**Comment by guruz** [comment]
Thanks a lot for spotting!
My bad..

**Comment by Dianafg76** [comment]
I tested with Desktop v ownCloud-2.0.0.2623-nightly20150812.pkg, the correct folder opens
Many thanks
Closed

**Comment by phil-davis** [comment]
Works for me also. ownCloud client 2.0.0.5391 Windows 10.
Note that all the accounts display the "alias" name as just "ownCloud" now. There has been discussion about that elsewhere and now it really is the case that this is a piece of useless text.
