### ISSUE TITLE
Notification for more permanent connection problems 

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#3596]
Connection problems such as some intermittent wifi issues should of course not result in an annoying desktop notification.

But if there is something where connectivity is broken and it likely needs manual work to fix, a notification is in order. This happens for example when the SSL certificate doesn’t work anymore or is expired.

**Comment by guruz** [comment]
Related https://github.com/owncloud/client/issues/3591

FYI @Dianafg76

**Comment by phil-davis** [comment]
Maybe:
a) If the client can work out that the computer has no network connection at the moment, then it could show something about that which is not "bad" or "green" - it is in a state where it just does not know if the client and server files are in sync. Some other icon and colour? What exactly to do here? Showing the green tick for a week while the laptop is off in a remote area is not really good - users who do not understand the realities of computers and networks will think that their files are synced on the server.
b) If there is a network connection but still the client cannot connect to the server, then it can show all the status that it does now.

**Comment by dragotin** [comment]
This is a bit unspecific. We display the "dot-dot-dot" icon if the client is not connected to proper network. But it does not know how long the problem will persist, and also not its exact reason. So I wonder if you could precise this issue? Closing for now.
