### ISSUE TITLE
file start with . doesn't synced automatically

### ISSUE THREAD

**Issue by changsijay** [owncloud/client#3597]
I have a file `.bowerrc` in my owncloud folder, I need to restart ownclould client to make it sync.
If I don't restart owncloud client, it never sync automatically.

However, other files can be synced normally.
MacOS X 10.10 + owncloud client 1.8.4

anyone have the same issue?

**Comment by changsijay** [comment]
just found it can sync automatically now.
so this issue only happen sometimes, I can not 100% reproduce it .

**Comment by guruz** [comment]
Can you try this build of what will become 2.0 and enable "sync hidden files" in "edit ignored files"?

http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.2622-nightly20150811.pkg

**Comment by changsijay** [comment]
Hi I am using `1.8.4`(build 2531).
After last time I restart the client, I can not reproduce the issue again.
Now it can sync `.bowerrc` automatically which is located at `~/ownCloud/projects/blog/.bowerrc`
I haven't tried the daily build you provided cause I don't know how to reproduce it :(

**Comment by guruz** [comment]
@changsijay Please re-open if you know how to reproduce.. maybe it somehow came via the server?
