### ISSUE TITLE
Exception: App can't be installed because it contains the true tag which is not allowed for non shipped apps

### ISSUE THREAD

**Issue by Thomanji** [owncloud/client#3598]
Hi, I upgrated to 8.1.1 and all worked fine from the rero. However the first time I go to the browser and access it it asks me to upgrade to 8.1.1 and if I click to start the upgrade I get the following:

Updating ownCloud to version 8.1.1, this may take a while.

Turned on maintenance mode
Checked database schema update
Checked database schema update for apps
Updated database
Updated "files" to 1.1.10
Exception: App can't be installed because it contains the true tag which is not allowed for non shipped apps
The update was unsuccessful. Please report this issue to the ownCloud community.

What Can I do to get this to complete? What does this error message mean?

Thank you for the help.

Best wishes,
Thomas

**Comment by danimo** [comment]
This is the issue tracker for the ownCloud desktop client. Please reopen it in the server tracker at https://github.com/owncloud/core/issues/new
