### ISSUE TITLE
Web client does not look up email for user name with capitalized letters

### ISSUE THREAD

**Issue by Isonite** [owncloud/client#3599]
I can log in to the web client (example.com/owncloud) and see my files using user name "Username", or I can use "username" (note the difference in capitalization) and both capitalizations log me in as the same user. However, when I click the link to reset password via email, user name "example" works, and user name "Example" returns the error dialog "Couldn't send reset email because there is no email address for this username. Please contact your administrator." The user name is listed on the admin page in all lower-case, as "username". This happens with every account I have on my server.

**Comment by danimo** [comment]
This is the bug tracker of the ownCloud Desktop Client. Web client issues should go to https://github.com/owncloud/core/issues.
