### ISSUE TITLE
Syncing Problem with Desktop Client App V.2 Beta 1

### ISSUE THREAD

**Issue by alichakery** [owncloud/client#3602]
### Expected behaviour
Syncing the old local folder after reinstallation 

### Actual behaviour
After removing , reinstalling the Client App and syncing the "OLD" local folder , it does not recognise the old files and it starts downloading all files from the server again.

### Steps to reproduce
1. Fully remove the previous version
2. Install the Beta 1
3. Specify the OLD local folder
4. Then it shows that it is finding the old files but after a while it starts downloading the whole files again.

### Server configuration
Operating system: CloudLinux

Web server:  LiteSpeed

Database: MardiaDB

PHP version: 5.4

ownCloud version: 8.1

### Client configuration
Client version: Beta 1

Operating system: OSX Yosemite (latest) / Windows 10 Home Edition (latest)

OS language: English

Installation path of client: Default

Thank you

**Comment by alichakery** [comment]
I tested the latest  Mac's  Nightly version (12 Aug) and it worked without any problem.

Thank you

**Comment by guruz** [comment]
@alichakery Great, thanks for testing.
I can close this then?

If the problem still persists we'd need to know more information about what you did in

> Fully remove the previous version

and also in

> Specify the OLD local folder

if you selected "new clean sync"..

**Comment by alichakery** [comment]
Well I think so because it worked on my Mac but I have not tested the latest version of Windows ....

I fully removed the previous version using this app : "CleanMyMac V3"

and Specifying the old folder means that I selected the old local folder to sync the file and No I did not opt the "new clean sync" option.

Thank you
