### ISSUE TITLE
Double notifications: folder updated,file downloaded

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/client#3613]
I receive two notifications if a file has been changed.
First: "InstantUpload has been updated"
Second: "InstantUpload/xx7x6x8.jpg has been downloaded"

I could really be more than fine with the second update.

**Comment by guruz** [comment]
Your bug report does not contain any version information.
Can you reproduce it with a nightly?
http://download.owncloud.com/desktop/daily/

**Comment by pascalBokBok** [comment]
Using client 1.8.4 against owncloud 8.1.1 but I've seen this behavior for at least some months.
I'm using Kubuntu 14.04 with KDE 4.13
I would prefer to not use a nightly with my production data and I do not have a test server.
You cannot reproduce the notifications?

**Comment by phil-davis** [comment]
2.0.0.5393 Windows 10
a) if I add a file to folder from a client elsewhere then when my client downloads it, I get a notification that the folder has been updated and a notification that the file has been downloaded - 2 notification. On 1.8.4 I am only seeing a single notification, but that might be because my 1.8.4 client is on Windows7 and the notification "speech bubble" is different to the way the notification messages just pop out in Windows 10.
b) If I update a file elsewhere, then I get a single notification of the form "FolderName and 1 other files have been updated". This is the same on 1.8.4.

So, I guess (a) could be combined into a single notification?

**Comment by pascalBokBok** [comment]
Yes, like you I only get two notifications when it is a new file.
I've made a separate issue #3615 to clarify the notification string when a file is updated.

**Comment by ogoffart** [comment]
Maybe a duplicated of #3580 ?

**Comment by phil-davis** [comment]
Not the same. I just tried with client 2.0.0.5394. I add a new file in a folder on the server web interface. The client downloads it. I get:
a) Notification about the change to the folder
b) Notification about the new file
c) A single entry in the Activity Log with Action "Downloaded" for the new file.

(c) is good,.
(a) and (b) could be just 1 notification. In fact I do not see the point of ever notifying about folder changes. So (a) notification could just be stopped.

New folders are interesting. But existing folders are just meta-data buckets that hold file names, time stamps... about the files in the folder. It is new/change/delete of the files themselves that is of interest to users.

**Comment by pascalBokBok** [comment]
I agree with @phil-davis, there doesn't seem to be any reason to notify the user that a folder has been updated - It's the content that matters (with the exception of new/delete folder)

**Comment by MTRichards** [comment]
The only real reason to notify a folder update is if it is moved, renamed or removed. If the folder is static, then the update should be for the content in the folder that has changed.

**Comment by pascalBokBok** [comment]
I just wanted to mention that the "X folder has been updated" still appears in client 2.0.0

**Comment by pascalBokBok** [comment]
@guruz why does this issue still have a "needs info" label?

**Comment by Dianafg76** [comment]
I tested this issue, and now it is working OK
Closed

**Comment by pascalBokBok** [comment]
@Dianafg76  from which version?

**Comment by Dianafg76** [comment]
Sorry, Desktop v ownCloud-2.0.2.2713-nightly20150914.pkg

**Comment by pascalBokBok** [comment]
thanks :smile:
