### ISSUE TITLE
[SSL] Accepted certificates only saved on real quit, not on ctrl+c (or shutdown/logout etc?)

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3617]

**Comment by guruz** [comment]
Maybe also relevant for other settings?
FYI @ogoffart

**Comment by guruz** [comment]
@Dianafg76 The fix itself i tested, but you can make sure there is no regression in adding / removing an account and or closing the client

**Comment by Dianafg76** [comment]
What are the steps to reproduce this issue ?
