### ISSUE TITLE
[Multi-account 2.0] Only 1 account syncs at a time

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3619]
An example use scenario:
I have a private family account my.name@myfamilycloud.example.org
I have a company account my.job@company.example.org
1. Add 100MB of family photos to the family account. It starts syncing those up to myfamilycloud. My link is not so fast - that will take 30 minutes.
2. Add a file to a folder in the company account.
3. The company account status changes to the blue "syncing" icon - good.
4. The sync of the company account does NOT happen until the sync of the family account is finished.
Note that there is a workaround that will at least be helpful for users to manually "prioritize" their syncs:
a) Pause the big sync that is in progress.
b) The waiting sync in the other account starts a few seconds later.
c) When the other account has finished sync, resume the first one.

I guess this is by design in the first multi-account release.
Is there any plan to support multi-account parallel sync?

**Comment by guruz** [comment]
@ogoffart @ckamm @jancborchardt  Can we easily show in the UI _"Waiting for other sync to finish..."_ for now?

We don't want to go parallel in the next major releases yet..

**Comment by phil-davis** [comment]
Yes, I can understand that multi-account parallel sync is not a "quickly patch it in thing".
For completeness I also observe that the interactions of the "Share with ownCloud" dialog work while a sync of any account is in progress. So various stuff like that does its thing independently of the file sync progress. I guess I expected/hoped that and it worked :)

**Comment by jancborchardt** [comment]
> Can we easily show in the UI "Waiting for other sync to finish …" for now?

Yeah, we could show exactly that below the progress bar. And we should also show it in the context menu of the tray icon maybe.

**Comment by MTRichards** [comment]
How hard is this to put in? Would be good for a smoother UX.

**Comment by MTRichards** [comment]
I should clarify, I mean to just put in the "waiting for another sync run to complete" so that it is clear to the user what is happening. 

Parallel sync runs should wait for a bit as mentioned above by @guruz .

**Comment by Dianafg76** [comment]
I tested this issue, and now when you have 2 accounts synced at a same time, 
one is synced, and the other appears "Waiting...",
Could it be added  "Waiting for another sync run to complete" ? as @MTRichards suggested

**Comment by ckamm** [comment]
@Dianafg76 Both messages exist. You see "Waiting..." when the client is in a pause state between sync runs. You should be seeing "Waiting for %n other folders(s)..." if another folder will sync first.

**Comment by Dianafg76** [comment]
@ckamm OK. I tried this problem and is working well OK
Desktop v ownCloud-2.0.2.2714-nightly20150915.pkg 
Closed
