### ISSUE TITLE
What to sync does not show folder names

### ISSUE THREAD

**Issue by awilisch** [owncloud/client#3629]
Installed the Debian 8 sync client and tried to do a selective sync, however it doesn't show the folder names just the size of the folders.

Fresh install of the client running on Debian Testing.
OS is a VM running in Vmware Fusion. 

Also seeing this problem on another Debian Testing install on a physical machine at my home. 

Have tried restarting the client with no success. 

See attached Screenshot
![screenshot from 2015-08-14 08-39-53](https://cloud.githubusercontent.com/assets/7795067/9274311/b0879b64-4262-11e5-808c-d4777f61b7e9.png)

**Comment by danimo** [comment]
Known bug in Qt4. Please resize the columns. Will be fixed once we can build all targets with Qt5.
