### ISSUE TITLE
osx desktop 1.8.4 client can't connect since last osx security update

### ISSUE THREAD

**Issue by sbgraphic** [owncloud/client#3631]
Hi, since last OSX security update today on OSX 10.8 and 10.10, I cannot connect with desktop client anymore, my password seems not recognized by the app. The app keeps asking it (in loop) while the password is correct. I've tested online and the user/credentials are fine.  (Try to deleted  app's preference etc. but it does not help)

Using ownCloud 8.1.0 (mutual server) with client 1.8.4.2531, three different Mac can't connect anymore.

![exemple](https://cloud.githubusercontent.com/assets/5297644/9274647/d419025e-4297-11e5-90a6-fab6a682f056.png)

**Comment by tflidd** [comment]
Here are the updates that were published today.
https://support.apple.com/en-us/HT201222
I might want to wait for my updates :smile: 

@sbgraphic Can you run your client with a logwindow: https://doc.owncloud.org/desktop/1.8/troubleshooting.html#log-files

**Comment by sbgraphic** [comment]
Yes for once i did not think about it...
Here is attached the last part of the log (just when I enter the password):

08-14 17:38:43:315 0x7fdb56c0b9e0 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found:   QUrl( "https://domain.com/owncloud/status.php" )   with version  "8.1.0" ( "8.1.0.8" )
08-14 17:38:43:316 0x7fdb56c0b9e0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
08-14 17:38:43:317 0x7fdb56c0b9e0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://domain.com/owncloud" + "/"
08-14 17:38:43:806 0x7fdb56c0b9e0 OCC::HttpCredentials::slotAuthentication: Stop request: Authentication failed for  "https://domain.com/owncloud/remote.php/webdav/"
08-14 17:38:43:807 0x7fdb56c0b9e0 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 5 "Operation canceled"
08-14 17:38:43:808 0x7fdb56c0b9e0 OCC::ConnectionValidator::slotAuthFailed: 5 "Operation canceled"
08-14 17:38:43:808 0x7fdb56c0b9e0 OCC::ConnectionValidator::slotAuthFailed: ******** Password is wrong!
08-14 17:38:43:809 0x7fdb56c0b9e0 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Undefined" -> "Credentials Wrong"
08-14 17:38:43:809 0x7fdb56c0b9e0 OCC::AccountState::setState: AccountState state change:  "Disconnected" -> "ConfigurationError"

Terminal send me back also the following:

    /Applications/owncloud.app/Contents/MacOS/owncloud --logwindow
    m_crashReporterChar:  /Applications/owncloud.app/Contents/MacOS/owncloud_crash_reporter
    2015-08-14 17:38:33.618 owncloud[1429:707] Sparkle: ===== owncloud =====

I also tried to update the mutual server app from 8.1.0 -> 8.1.1 but It's another issue 8.1.1 update won't install properly… waiting for more info from my hosting provider on this… I had to restore back in 8.1.0 but still no luck with the desktop client, damn osx security update !!

Thanks!

**Comment by guruz** [comment]
(Have not checked yet what apple did or updated my Mac..)

Can you run the ```Keychain Access``` app on your OS X and check the credentials saved for ```ownCloud```?

Do you use a proxy?

Does the log mention anything about keychain?

**Comment by sbgraphic** [comment]
Yes I did check the Keychain access, also delete everything related to owncloud.

I don't use proxy.

The system log does not show much, only these two lines:

    17.08.15 01:42:15.841 owncloud[1061]: GetDYLDEntryPointWithImage(/System/Library/Frameworks/AppKit.framework/Versions/Current/AppKit,_NSCreateAppKitServicesMenu) failed.
    17.08.15 01:42:16.379 owncloud[1061]: Sparkle: ===== owncloud =====

Here is about the 2015-006 security update:
https://support.apple.com/fr-ch/HT205031
In this document, there is something about 'OpenSSL' and 'Security' for both system concerned such as:

*(…) Description: Multiple vulnerabilities existed in OpenSSL versions prior to 0.9.8zg. These were addressed by updating OpenSSL to version 0.9.8zg. (…)*

*(…) Description: An issue existed in handling of user authentication. This issue was addressed through improved authentication checks. (…)*

Is it related? I'm not able to help very much!

**Comment by guruz** [comment]
Works fine for me (4 different accounts) with 10.10.5 (just updated 5 minutes ago from 10.10.4)

Can you reproduce this with a Windows or Linux client?

I'd suggest to have a look at your server's ```owncloud.log``` and webserver error log.

**Comment by sbgraphic** [comment]
well good then, still have the isse on both systems...

The owncloud admin log (from webinterface) show this error multiple times:

    {"reqId":"VdITHYBBwwkAAJngTagAAABD","remoteAddr":"MY.IP.ADR.ESS","app":"PHP","message":"set_time_limit() has been disabled for security reasons at \/home\/clients\/f1fa2c71f2b6a313f20083dc14303533\/web\/folder\/lib\/base.php#557","level":3,"time":"2015-08-17T17:00:17+00:00"} 

The web server show this error (when I try to login with the app):

    [Mon Aug 17 19:12:03 2015] [error] [client MY.IP.ADR.ESS] FastCGI: server "/home/clients/f1fa2c71f2b6a313f20083dc14303533/.config/apache/domain.com/.fpm/php5.external" stderr: PHP message: PHP Fatal error: Maximum execution time of 30 seconds exceeded in /home/clients/f1fa2c71f2b6a313f20083dc14303533/web/folder/lib/private/log/owncloud.php on line 122, referer: https://domain.com/owncloud/index.php/settings/admin

But this really came in since last security update. So you think this came from our mutual server?

**Comment by guruz** [comment]
@sbgraphic I still think the OSX security update is a coicidence (else a lot more users would report here.. also we ship our own OpenSSL)
Do you use shared folders with your users?
Do you use external storage in your oC server?

@thomsmits @PVince81 @rullzer Do you think this can be related to https://github.com/owncloud/core/issues/18325 ?

**Comment by sbgraphic** [comment]
Actually, at this time I mainly share public links with passwords, without dedicated accounts (except one admin and one user). I'm using a simple owncloud install provided by our hosting provider on a mutual server so I've no idea of the server setup. I don't use my own owncloud server/installation (so i've no idea about external storage).

If this is a coincidence it's really a strong one… I'll try to reinstall the osx security update manually.

I'll forward this issue to the hosting support again, because I have another issue with the update 8.1.1 which cannot be updated...

**Comment by sbgraphic** [comment]
#### 8.1.1 server update from 8.1
After requiring a support ticket to our hosting provider, they finally found that there was an issue from the installation software that prevented the one-click update install. Apparently this is now fixed and we are now using the 8.1.1 version

#### 1.8.4.253 desktop client osx 
Since updating the server version as mentioned above, our osx desktop client can login and sync without problem. As **guruz** commented, it is apparently not related to the last osx security update as i believed, at least not with the latest version of the server installed. *Thanks for your support*.
