### ISSUE TITLE
File types .EML | sync loop 

### ISSUE THREAD

**Issue by prilly** [owncloud/client#3633]
There seems to be a sync loop with filestypes .eml (mail) with the use of owncloud sync client.

if you store a email .eml file on the owncloud server and connect 2 sync clients (windows) to sync the folder containing this files they will upload/download the file in a loop.

clients wil alternate upload and redownload the files until the new dawn arises.

16.08.2015 13:44:54Dokumenter   ownCloud       Ignored because of the "choose what to sync" blacklist          
16.08.2015 13:44:45Dokumenter/Saksdokumenter/dokumentasjon/paypal/epost   'service@paypal.com' (service@paypal.com).emlownCloud       Uploaded       12 KiB    
16.08.2015 13:44:44Dokumenter/Saksdokumenter/dokumentasjon/paypal/epost   'service@paypal.com' (service@paypal.com).emlownCloud       Uploaded       13 KiB    
16.08.2015 13:44:28Dokumenter/Saksdokumenter/dokumentasjon/paypal/epost  PayPal (member@paypal.com).emlownCloud       Downloaded     12 KiB    
16.08.2015 13:44:28Dokumenter/Saksdokumenter/dokumentasjon/paypal/epost  PayPal (member@paypal.com).emlownCloud       Downloaded     11 KiB    
16.08.2015 13:44:28Dokumenter/Saksdokumenter/dokumentasjon/paypal/epost  'service@paypal.com' (service@paypal.com).emlownCloud       Downloaded     12 KiB    
16.08.2015 13:43:46Dokumenter/Saksdokumenter/dokumentasjon/paypal/epost via PayPal (member@paypal.com).emlownCloud       Uploaded       12 KiB    
16.08.2015 13:43:27Dokumenter/Saksdokumenter/dokumentasjon/paypal/epost  via PayPal (member@paypal.com).emlownCloud       Uploaded       11 KiB    
16.08.2015 13:43:22Dokumenter/Saksdokumenter/dokumentasjon/paypal/epost   'service@paypal.com' (service@paypal.com).emlownCloud       Uploaded       13 KiB    
16.08.2015 13:43:21Dokumenter/Saksdokumenter/dokumentasjon/paypal/epost  via PayPal (member@paypal.com).emlownCloud       Downloaded     12 KiB    
16.08.2015 13:43:20Dokumenter/Saksdokumenter/dokumentasjon/paypal/epost   'service@paypal.com' (service@paypal.com).emlownCloud       Uploaded       15 KiB    
16.08.2015 13:43:20Dokumenter/Saksdokumenter/dokumentasjon/paypal/epost   'service@paypal.com' (service@paypal.com).emlownCloud       Uploaded       12 KiB    
16.08.2015 13:43:12Dokumenter/Saksdokumenter/dokumentasjon/paypal/epost   'service@paypal.com' (service@paypal.com).emlownCloud       Uploaded       19 KiB    
16.08.2015 13:43:01Dokumenter/Saksdokumenter/dokumentasjon/paypal/epost  via PayPal (member@paypal.com).emlownCloud       Downloaded     11 KiB    
16.08.2015 13:43:01Dokumenter/Saksdokumenter/dokumentasjon/paypal/epost   'service@paypal.com' (service@paypal.com).emlownCloud       Downloaded     15 KiB

**Comment by RealRancor** [comment]
Seems thats already documented with a workaround here: https://doc.owncloud.org/desktop/1.8/faq.html

**Comment by prilly** [comment]
look at that.. That is not good (i hate windows).

i need to read the docs next time.

**Comment by guruz** [comment]
Glad you found it :)

Dup https://github.com/owncloud/client/issues/3235
