### ISSUE TITLE
Sync only when local external drive is connected to client

### ISSUE THREAD

**Issue by JH6** [owncloud/client#3635]
I'm have an external harddrive which sometimes is connected to the client and sometimes not. On this harddrive there is data which I want to sync to owncloud. However when I remove the harddrive or when it is having a different drive letter this is giving problems for the owncloud client. Instead I use GoodSync which is capable of handling a source directory on the client by the name of the drive and will only sync if this drive is present. Goodsync however gives problems with version controll on the server side.

In my opinion a nice feature to add to the owncloud client would be the possibility to use for example the drive name to identify an external harddrive (or another ID number which is unique to the drive, even when the drive letter changes) and have the owncloud client only syncing when this drive is present.

**Comment by SamuAlfageme** [comment]
Done in https://github.com/owncloud/client/pull/5381
