### ISSUE TITLE
Connection Wizard Sync everything does not show true total

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3636]
1. Create a new user on the server with the default initial files (2.5MB)
2. Add the user to a group that has lots of files shared with it.
3. Add the account on the sync client.
The connection wizard suggests "Sync everything from server (2.5MB)".
In the screenshot I remembered to click "Choose what to sync" and deselect the really big shared folders. When I click "Choose what to sync", that happily shows me the size of each of the folders, including the shared ones.
![owncloudinitialsync](https://cloud.githubusercontent.com/assets/1535615/9304431/e454593a-4507-11e5-8d3e-1c5158161043.png)

It would be nice if "Sync everything from server" showed a better estimate of the size. (Even if it does not show the size of external storages).

**Comment by ogoffart** [comment]
What version of the server is that?   I heard that this was fixed with newer server version.

**Comment by phil-davis** [comment]
Server 8.0 - I will search a bit to see if there is anything that seems good in 8.1 release notes or...

**Comment by phil-davis** [comment]
Connecting to an ownCloud 8.1.1 (stable) server, "Sync everything from server (nnn MB)" shows me the full size of everything on the server that would sync down by default - my own folders and files, stuff shared with me by other users and with me by the admin-created external storage.
So the server is indeed better at providing this data in 8.1
