### ISSUE TITLE
Slow csync_excluded_no_ctx   (lots of memory allocations takes 10% of the time)

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3638]
```
<ogoffart> I was profiling a bit the local discovery, and 10% of the time is spend
 in the allocations/free in csync_excluded_no_ctx  (because of c_direname and co.)
```

There are too many allocations ba1184f5aba2c9b7d4483c3d52f0dc897482f46e

FYI @dragotin @ogoffart

**Comment by ogoffart** [comment]
Why do we have to split again every directory. Normaly if a directory is ignored, we should not even go in that function.  Or is it used for the socket api?

Either way, the big amound of allocations done in this function takes a lot of time.

**Comment by dragotin** [comment]
Maybe the patch mentioned above helps. It does not use that c_basename functions any more. The test case ```check_csync_exclude``` runs successfully with it.

The semantics of the new implementation changed a bit compared to before, and I am not sure if that plays a role. Before, a path was splitted from its end, and in the loop the dir part was checked completely. Now each component is checked alone.

Example: Path a/b/c/d.txt
Prev. implementation would have checked each pattern against
```
a/b/c and d.txt
a/b and c
a and b
```
now it only checks a, b, c and d.txt (if needed) against the patterns. Not sure if that has a meaning.

Other question: Is the test case sufficient?

**Comment by ogoffart** [comment]
The question is why do we need to do that?
Why do we need to test the path at all?  
Since we do not recurse within the excluded directory,  is it not sufficient to just check for `d.txt`  ?

**Comment by dragotin** [comment]
Well, the function was (probably) implemented not assuming external circumstances like the one you mentioned (which is correct AFAIK).

However, the [usage from the socketapi](https://github.com/owncloud/client/blob/master/src/gui/socketapi.cpp#L581) can not make this assumption, right?

Given that a solution such as the proposed one should be more efficient I'd vote for keeping it as it was before, without using that external deps.

@ogoffart what do you think about the implementation? Can your benchmark proof that it is faster?

**Comment by dragotin** [comment]
lets consider this again for 2.0.1

**Comment by ckamm** [comment]
The three commits mentioned above (669f221, 658d104, e37199b) significantly speed up `csync_excluded` in general (3x) and introduce a new `csync_excluded_traversal` that can be used in the update phase and that's again significantly faster (7x). They also add more tests and a performance test.

**Comment by ckamm** [comment]
@ogoffart Verified it!
