### ISSUE TITLE
ownCloud Client on Win7x64 reports missing write privileges for folder

### ISSUE THREAD

**Issue by cmeh** [owncloud/client#3639]
I keep getting error messages by the ownCloud Desktop Client Version 1.8.4 (build 5267) on Windows 7 Ultimate 64 bit, according to which the client is unable to add files to the specified folder:

![owncloud_desktop_client_long_filenames](https://cloud.githubusercontent.com/assets/10512818/9309688/97a1b30e-450b-11e5-9c4b-eaf6cc323cdf.png)

The above is part of an experiment to build a unified Lightroom catalogue between a Macintosh and a Windows instance. My first assumption was the length of the path involved may have exceeded the Explorer-critical 256 characters, but it turns out there are not more than 200 characters, which shouldn't be a problem then. Any ideas?

**Comment by guruz** [comment]
The easiest would be to check out a nightly build of 2.0 to see if that changes anything..
http://download.owncloud.com/desktop/daily/ownCloud-2.0.0.5405-nightly20150818-setup.exe

**Comment by cmeh** [comment]
@guruz Thank you very much. I've now replaced my ownCloud Desktop Client Version 1.8.4 (build 5267) with the nightly version you've linked above (in other words 2.0.0 (build 5405 nightliy)). The error message however remains the same:

`Nicht erlaubt, da Sie keine Rechte zum Hinzufügen von Dateien in diesem Ordner haben`

On the ownCloud server, a Banana Pi with Bananian Linux manually upgraded to Debian Jessie by me, I've checked permissions of the directories the ownCloud Desktop Client allegedly has no sufficient permissions for to add files: They seem to be okay, owner-wise they're on `www-data:www-data` and permissions-wise they're on `755`.

`getconf PATH_MAX` displays "4096" for the filesystem, so I would expect path length not being an issue under the server's ext4 filesystem, either.

**Comment by cmeh** [comment]
Sorry, this was accidentally closed - I've reopened it now.

**Comment by guruz** [comment]
If you open the folder in the Windows explorer, do you see the permissions for the folder?
Is there a "lock" icon on the folder?

**Comment by ogoffart** [comment]
The message says you don't have the rights, so i guess that's the problem. 
Are you trying to download or upload the files? If trying to upload then the problem is likely a problem in the sever and you need to get the server logs. You are maybe trying to upload into a shared directory for which you do not have the rights.

If trying to download then there is something wrong on the filesystem.

I doubt that this is a bug in the client.

**Comment by dragotin** [comment]
Sorry, please try to get help on this issue in the forum or on the mailinglist. Thanks.
