### ISSUE TITLE
Update sync-exclude.lst

### ISSUE THREAD

**Issue by PortableTech** [owncloud/client#3640]
I would highly recommend adding the following two entries to the sync-exclude.lst file.

.symform
.symform-store

These are created by the Symform backup client and it uses it to track the status of what it has done and needs to do.  Unfortunatly, OwnCloud and Symform get caught in a violent loop where Symform adds a status file into the owncloud folder, OwnCloud updates the existence of the new file, other clients pick up on the change and update, Symform triggers a change and updates the file, and on and on, and it can bring a server to it's knees.

Adding those manually has resolved the issue on my end and there really is no issue to ever sync those folders.

**Comment by guruz** [comment]
Thanks @PortableTech
