### ISSUE TITLE
Release 2.0.0

### ISSUE THREAD

**Issue by danimo** [owncloud/client#3641]
Release-1 Week:
* [x] Check if we should update the bundled sqlite3 (https://github.com/owncloud/client/tree/master/src/3rdparty/sqlite3)
* [x] Check if we should update Sparkle on build machine (https://github.com/sparkle-project/Sparkle/releases)
* [x] Ensure up-to-date dependencies (e.g. [latest Qt version](http://qt-project.org/downloads#qt-lib) is installed on the machine and picked up (cmake output)
* [x] Check nightly builds are up and running, that is Jenkins jobs ownCloud-client-linux, ownCloud-client-osx and ownCloud-client-win32 all green.
* [x] Build branded clients through the scripting machine and smoke test one or two branded clients (especially with predefined url)
* [] Upload a nightly build of the windows version to virustotal.com
  * Contact AV vendors whom's engine reports a virus
* [x] Documentation should be online before the release http://doc.owncloud.org/desktop/1.X/
* [ ] QA goes over https://github.com/owncloud/mirall/wiki/Testing-Scenarios
* [x] Communicate the release schedule on mailinglist release-coordination@owncloud.com
* [ ] Give a high level overview of the upcoming new features, changes etc.
* [x] Make sure to have `client/ChangeLog` updated
 * use `git log --format=oneline v<lastrelease>...master` if your memory fails you
* [x] Ensure marketing is aware and prepared for the release (social, .com website, cust. communications)
* [x] Inform GCX knows the next version is about 1 week out (gcx@owncloud.com)

For beta1 (15.08.2015)
* [x] Branch off a release branch called <version>-rcX or <version>-betaX
* [x] Edit ```VERSION.cmake``` to set the suffix to beta1, beta2 etc. Commit the result to the release branch only
* [x] Create the beta tarball using Jenkins job ownCloud-client-source
* [x] Create build for Windows using rotor job owncloud-client-win32
* [x] Create build for Mac using rotor, job owncloud-client-osx 
* [x] Create Linux builds using rotor job owncloud-client-linux building both themes 'ownCloud' and 'testpilotcould'
* [x] Copy builds from ```daily``` to ```testing``` on download.owncloud.com, double check the download links.
* [x] Inform community mailinglists devel@owncloud.org and testpilots@owncloud.org
* [x] Inform internal mailinglist release-coordination@owncloud.com
* [x] Update the owncloud.org webpage, section testing, by providing a pull request to the https://github.com/owncloud/owncloud.org github repository.
* [x] Create a signed tag
* [ ] Remove the release branch (?)

For rc1 (18.08.2015):
* [x] Branch off a release branch called <version>-rcX or <version>-betaX
* [x] Edit ```VERSION.cmake``` to set the suffix to beta1, beta2 etc. Commit the result to the release branch only
* [x] Create the beta tarball using Jenkins job ownCloud-client-source
* [x] Create build for Windows using rotor job owncloud-client-win32
* [x] Create build for Mac using rotor, job owncloud-client-osx 
* [x] Create Linux builds using rotor job owncloud-client-linux building both themes 'ownCloud' and 'testpilotcould'
* [ ] Copy builds from ```daily``` to ```testing``` on download.owncloud.com, double check the download links.
* [ ] Inform community mailinglists devel@owncloud.org and testpilots@owncloud.org
* [ ] Inform internal mailinglist release-coordination@owncloud.com
* [ ] Update the owncloud.org webpage, section testing, by providing a pull request to the https://github.com/owncloud/owncloud.org github repository.
* [ ] Create a signed tag
* [ ] Remove the release branch (?)

Day before Release:
* [x] Check the translations coming from transifex: All synchronized?
* [x] Run the tx.pl scripts on the final code tag
* [x] Run ```make test```
* [ ] Run smashbox on the final code tag
* [x] Inform product management and marketing that we are 1 day out

On Release Day:
* [x] Branch off a release branch called <version>.
* [x] Double check ```VERSION.cmake```: Check the version number settings and suffix (beta etc.) to be removed. Commit change to release branch only!
* [x] Add last updates to Changelog in the client source repository, check if a release date is set!
* [x] Create tar ball (automated by `ownCloud-client-source` jenkins job)
* [x] Copy the source tarball from the daily to the stable dir on download.o.o 
* [x] Announce the source tarball on the packaging mailing list packaging@owncloud.org
* [x] Build Windows packages
* [x] Build Mac OS X packages
* [ ] Build Linux packages by running the jenkins job ownCloud-client-linux with proper parameters
 * Update [OBS repository](https://build.opensuse.org/project/show?project=isv%3AownCloud%3Adesktop) `isv:ownCloud:desktop` (or `isv:ownCloud:community:testing` for RC/Beta)
 * Check if patches still apply in the linux packages
* [ ] Trigger rebuild of the branding packages, inform juergen that a new tarball is available.
* [x] Check if the following packages are on download.owncloud.com/desktop/stable:
  * Windows binary package
  * Mac binary package
  * source tarballs
* [x] Re-download Win and Mac builds and check signature.
* [x] Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
  * If all is good, create a signed tag with build SHAs from the release branch
* Create an submitrequest to the owncloud.org repository to update the install page and the changelog on owncloud.org
* [x] Update ASCII Changelog on http://download.owncloud.com/download/changelog-client 
* [x] Keep the packaging mailinglist packaging@owncloud.org informed and announce the final sources.
* [x] Create git tags in github client repository.
* [ ] Update the updater script ```clientupdater.php```
* [ ] Send out Social (tweet, blog, other)
* [ ] Send out customer communication (if any)
* [ ] Inform GCX that the new version is released (gcx@owncloud.com)
* [ ] Take pride and celebrate!

**Comment by dragotin** [comment]
this is done.
