### ISSUE TITLE
[2.0RC1] Positive wording when removing an account

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#3643]
Currently, when removing an account there is a message:
````
Note: This will not remove the files from your client
````
This is correct. But: I did the error when reading quickly: "files - remove - client". Then I was confused and read it correctly. To avoid confusions, it's perhaps better to use a positive statement:
````
Note: The files will be kept on your client.
````

**Comment by guruz** [comment]
@tflidd Sounds nice.
@jancborchardt "client"? Why don't we use "computer"?

CC @ogoffart

**Comment by ckamm** [comment]
To me "The files will be kept on your client" has the confusing undertone of "As opposed to being kept in your oC account - in fact, we'll delete them from your account!". 

Counter-suggestion: "**Note**: This will **not** delete any files." @tflidd @jancborchardt

**Comment by jancborchardt** [comment]
I like @ckamm's suggestion. It also avoids the words computer/client/device.

**Comment by guruz** [comment]
:+1:

**Comment by tflidd** [comment]
I like this suggestion, so we avoid any confusion :+1:

**Comment by Dianafg76** [comment]
I tested this issue with Desktop v ownCloud-2.0.0.2668-nightly20150825.pkg. And is working fine, When you deleted the account appears "Note: This will not delete any files
Many thanks
Closed
