### ISSUE TITLE
[2.0RC1] quota info text size in interface

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#3644]
![screenshot](https://cloud.githubusercontent.com/assets/8111200/9342194/b07cbe9c-45fa-11e5-89fa-04e89e249983.png)
- Text under the storage usage ("Some folders, including ....") is too small to read.

**Comment by guruz** [comment]
@ogoffart FYI this looks fine on OS X. Small but nicely rendered.

**Comment by tflidd** [comment]
Do you have a retina display on OS X? On a standard screen it's hard to read.

**Comment by ckamm** [comment]
@tflidd @jancborchardt Currently the quota info label font size is 80% of the default text size. We could increase the size, but I wonder whether it should just be a tooltip instead.

**Comment by jancborchardt** [comment]
Yeah, honestly this small piece of text is really an off-case. I like @ckamm’s suggestion of making it a tooltip.

**Comment by ckamm** [comment]
Patch will go into 2.0 branch once 2.0.0 has branched off.

**Comment by Dianafg76** [comment]
@ckamm I tested this issue with ownCloud v Desktop - 2.0.0.2668 - nightly20150825.pkg and text under storage usage ( " Some folders , including .... ") has disappeared
![screen shot 2015-08-25 at 17 00 42](https://cloud.githubusercontent.com/assets/12032058/9470150/ef0f2f00-4b4a-11e5-811e-57827e48ca1c.png)

**Comment by jancborchardt** [comment]
Nice, as discussed. Looks much better.

**Comment by jancborchardt** [comment]
@ckamm can you remove the strange box around the Storage space info?

**Comment by guruz** [comment]
@ckamm Which box?

**Comment by jancborchardt** [comment]
@guruz the grey box which frames the storage space section. It’s not really necessary.

**Comment by ckamm** [comment]
@Dianafg76 The text was removed intentionally, it's now a tooltip. @jancborchardt It's the group box around the bar and label, I can experiment with it next time. :)

**Comment by jancborchardt** [comment]
@ckamm cool, thanks! We don’t really need it and it would make the look a lot cleaner. :) Vertical whitespace is enough to separate the elements.

**Comment by Dianafg76** [comment]
closed
