### ISSUE TITLE
[2.0RC1] Greyed "Add folder to Synchronize" button?

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#3645]
![screenshot](https://cloud.githubusercontent.com/assets/8111200/9342281/259bf0d0-45fb-11e5-8121-dbf5fef705e3.png)
- The "Add Folder to Synchronize" button is never active. Is it not used any more? Before I was able to sync a folder from my account to a different place on my filesystem. I can still add my account twice.

**Comment by phil-davis** [comment]
AFAIK when the whole root of the user's server folder tree is already being synced to the client then there is nothing more that can be synced, so "Add Folder to Synchronize" is disabled.
If you remove the root folder sync then you should be able to add individual sync of various folders to different place on the client.

**Comment by phil-davis** [comment]
I guess it is valid to support adding the same account twice to a multi-account client install. Then you can sync some combination of your files to client location A, and then in the 2nd (copy of same) account sync some different (and possibly overlapping) set of folders to a different place on the client.
I am struggling to think of a real use case for this - but I tried it just now and it works, so I also can't think of a reason to add code to prevent it.

**Comment by tflidd** [comment]
> AFAIK when the whole root of the user's server folder tree is already being synced to the client then there is nothing more that can be synced, so "Add Folder to Synchronize" is disabled.
> If you remove the root folder sync then you should be able to add individual sync of various folders to different place on the client.

That what was it like in the previous version. But even if I only choose a sub-folder to sync upon account creation:
![screenshot](https://cloud.githubusercontent.com/assets/8111200/9349221/02b0d1a6-4643-11e5-8ef1-e08efd7a2734.png)
but the subfolder-structure is always shown and all single files on the root-directory will be synced (the owncloud manual):
![screenshot2](https://cloud.githubusercontent.com/assets/8111200/9349253/6c86295a-4643-11e5-9f86-6cae359702fd.png)
So it seems that it is not possible any more, to sync directly the sub-folder. Or do I need to change something during the creation of the account?

**Comment by phil-davis** [comment]
See discussion of this at https://github.com/owncloud/client/issues/3632

**Comment by tflidd** [comment]
Thanks for pointing me to the other discussion. But with this behavior, it is impossible to create a case where the "Add Folder to Synchronize"-button will be active. Perhaps on upgrade from a previous version.

**Comment by phil-davis** [comment]
Here is an example. 
1. Create user "User2", with the default Documents and Photos folders.
2. Add it to the multi-sync client, let it sync somewhere. Then remove the sync folder (but not the account).
3. Select "Add folder to synchronize". Make a local folder somewhere on your computer (I made D:\Personal\ownCloud-User2A). Choose to sync that with Documents on the server.
4. Select "Add folder to synchronize". Make a local folder somewhere on your computer (I made D:\Personal\ownCloud-User2B). Choose to sync that with Photos on the server.
The account looks like this on the client:
![owncloudzuser2](https://cloud.githubusercontent.com/assets/1535615/9350170/d6f6cf4a-466d-11e5-97c4-b3d3b2dfbd81.png)
And it syncs the initial default files in those folders like this:
![owncloudzactivity](https://cloud.githubusercontent.com/assets/1535615/9350176/eb4a2956-466d-11e5-92fd-47bc08682cff.png)
In real life your computer might have various disks and partitions and you want to sync a bit of data from disk/partitionA-folderX up to the server, and also from disk/partitionB-folderY up to the server. Depending on the operating system, you might have "My Documents" already provided by the OS and you want to sync that to ownCloud server "Documents". Some other application on your computer might put files in some other special place and you sync from there up to ownCloud server "MySpecialApp" folder and...

**Comment by guruz** [comment]
@jancborchardt I had the same problem as @tflidd until I somehow hit the tooltip. I think this button is not intuitive if it is greyed out. Maybe we should not show it at all then?

**Comment by tflidd** [comment]
@guruz : That's it, you have to click on this little icon on the right to remove the folder
![screenshot](https://cloud.githubusercontent.com/assets/8111200/9350715/486bfe4a-4653-11e5-9db2-423f88497107.png)
That solves for me as well https://github.com/owncloud/client/issues/3632.

I would like to keep this feature but it needs to be more intuitive.
Instead of greying out or removing the button, can't you just keep it active? You could someone let add more folders and later they will perhaps delete the principal sync-point (to the root-folder).

Why do you have to remove the principal mount-point first? Maybe the button should be more precise to say "add another local folder" to sync or "add another mount point".

**Comment by jancborchardt** [comment]
Can we not make the tooltip also show on clicking the button? Or immediately show it instead of waiting for the standard tooltip timeout?

**Comment by guruz** [comment]
Let's opt for your first suggestion, then it's tablet compatible ;-)

**Comment by jancborchardt** [comment]
Cool, thanks!

**Comment by jancborchardt** [comment]
(Or maybe even both, if possible? People might not click the button if it’s disabled.)

**Comment by tflidd** [comment]
Other idea: instead of the tool-tip, couldn't we just put some symbols that are permanently shown? A small folder to open in the windows explorer, a pause-button and a trash-bin? On a mouse-over you can show a little description of each function.
Do you understand what I mean?

**Comment by jancborchardt** [comment]
@tflidd I also thought about this, but you really do not need these functions that often. And having only icons (with text shown only on mouse-over) is not good practice. So having the menu instead is a better way.

**Comment by tflidd** [comment]
My client runs in the background. So if there are no problems, I only need to open the interface to add  or change account settings.

**Comment by ckamm** [comment]
I'd like to suggest to move this to 2.0.1 or 2.1, I agree that it's confusing but it seems to big to fit in between RC and final.

**Comment by ckamm** [comment]
@jancborchardt The tooltip does now show on click when the button is disabled. As far as I can tell that's the agreement you came to?

**Comment by jancborchardt** [comment]
@ckamm yep, thanks!

**Comment by Dianafg76** [comment]
I tested this issue, and for my the button "Add Folder to Synchronize" is working OK
Desktop v ownCloud-2.1.0.2831-nightly20151027.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

Closed

**Comment by TDannhauer** [comment]
Above some of you questioned for a real use case. I have one and due to the above discussed mechanism I struggled - so I found this discussion.

Since there _IS_ a very valid use case you try to prevent, we should reopen the discussion.

My use case is simple: 
I have a Owncloud folder with ~.5 TB. On of the folders is <owncloud-root>/documents

My desired setup is:
a) Sync ALL (including in folders appearing in the future) data to my data storage "D:\Data" -> this is only possible by syncing the root node.
b) Sync <owncloud-root>/documents to C:\Users\Torben\Documents

As you can see, the above discussion/mechanism prevents this setup, since a) syncs the root note and prevents b) from being set up (grey out button). 

Since there IS a use case, I recommend to remove this mechanism completely. It should be up to the user to sync multiple folders of his choice to multiple destinations. 

A hint: Setting up a) as last step does the trick:
first setup b) and all other folders to sync. Last setup b) - then additionally folder syncs are blocked by the grey button.

**Comment by scolebrook** [comment]
@TDannhauer Add a second account with the same server address and user credentials. Don't sync the root node in that setup, just pair your documents folders. I do this to sync my root and everything in it with my regular folder, but to separately sync my ~/.ssh folder to a separate folder server side. I have that folder unselected in my main setup to avoid duplicated data. I can then keep my many keys and complex config file in sync across my computers and VMs, while also syncing my entire account. I also use this second account to pair other folders when needed.

From my observation, syncing the root node is all that 99.9% of users want or need to do. Any button that is enabled attracts clicks and disabling this button in this scenario prevents people who don't know any better from duplicating data. By having two accounts setup in the sync client, one to sync all content and the other to pair specific folders on both sides, you separate out the functionality for advanced users in a clear and simple way without creating an opportunity for less advanced users to do something they don't really want.

**Comment by TDannhauer** [comment]
@scolebrook Thanks for your Participation. Yes, I can do it in your way. But I can do it also in a single acount as described above. 
If you want to avoid distraction in the UX, you could hide the button instead of disabling it.

However, I still do not agree to folder aspect: Its perfectly fine that root node syncronisation is regarded as the default use case and therfore the default setup mechanism during desktop client installation. Everyone who desires exactly this setup wont go on exploring desktop client buttons or functionalities after initially setting up the desktop client. But a advanced user potentially wants to set up additional folders. Setting up multiple identical accounts is not as intuitiv and clearly presented as having multiple folders - may it be root folder or not - in a nice list of a single account.

What do the others think?

**Comment by SamuAlfageme** [comment]
Done in https://github.com/owncloud/client/pull/6032
