### ISSUE TITLE
[Windows] No overlay icon/Context menu in Testpilot and normal client at same time

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#3646]
After installing the testpilot does not show any overlay icons or context menu. After playing around a little bit, I got the overlay icons but as I got them on the Testpilot, they disappeared on the folder of my regular client.

Sync process is still working. If I can't have them on both clients at the same time, I'd prefer to keep the overlay icons and the context menu on the regular client.

Testpilot: 2.0.0rc1 (build 5408)
regular client: 1.8.4 (build 5267)
Win 7 (64-bit)

edit: context-menu stays with the regular client, even when overlay icons are shown on the testpilot.
Windows was not restarted.

**Comment by tflidd** [comment]
After reboot, the overlay icons and the context menu are only shown on the testpilot's sync folders.

**Comment by dragotin** [comment]
This is known behaviour, the overlays are only working exclusively. 

This will be fixed in a later release.

**Comment by guruz** [comment]
Dup https://github.com/owncloud/client/issues/2388 ?
