### ISSUE TITLE
[Linux] owncloud client will not open window

### ISSUE THREAD

**Issue by mlindley** [owncloud/client#3647]
After a system update my owncloud sync client will not open its settings window, help window, etc. Logs give the following:

Gtk-Message: Failed to load module "pantheon-filechooser-module"

Edit:
Not sure it matters but here is some more info.

$ uname -a
Linux elemos 3.16.0-46-generic #62~14.04.1-Ubuntu SMP Tue Aug 11 16:27:16 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

Owncloud was installed through the software center. I have tried reinstalling the client via software center with no improvement.

**Comment by guruz** [comment]
Which version?

What do you exactly get when running ```owncloud --logfile -```?

Did you check if the client is running already? ```ps waux | grep owncloud```

**Comment by mlindley** [comment]
user@elemos:~$ owncloud --logfile
Gtk-Message: Failed to load module "pantheon-filechooser-module"
Gtk-Message: Failed to load module "pantheon-filechooser-module"
ownCloud version 1.5.0


user@elemos:~$ ps waux | grep owncloud
user      1901  0.2  1.0 838152 81400 ?        Sl   16:05   0:00 /usr/bin/owncloud

**Comment by guruz** [comment]
```owncloud --logfile -```
With a dash..

The ```ps waux``` output means it is already running?
Try ```killall owncloud``` and then ```owncloud --logfile -```..

**Comment by mlindley** [comment]
Owncloud runs on startup. It's running icon is apparent in the elementary
os wingpanel. I can right click on the icon and the context menu pops up,
but nothing happens if I click any choices on that menu (for example,
clicking "Quit Owncloud" does nothing). I can kill the owncloud process via
the kill command.

user@elemos:~$ killall owncloud
user@elemos:~$ owncloud --logfile -
Gtk-Message: Failed to load module "pantheon-filechooser-module"
Gtk-Message: Failed to load module "pantheon-filechooser-module"
08-19 16:20:12:895 "################## ownCloud en_US () 1.5.0"
08-19 16:20:12:895 void Mirall::Application::setupTranslations() Using
"en_US" translation
08-19 16:20:12:895 Loading config:
"/home/user/.local/share/data//ownCloud/owncloud.cfg"  (URL is  "
https://x.x.x.x/owncloud" )
08-19 16:20:12:895 Loading config:
"/home/user/.local/share/data//ownCloud/owncloud.cfg"  (URL is  "
https://x.x.x.x/owncloud" )
08-19 16:20:12:900 Loading config:
"/home/user/.local/share/data//ownCloud/owncloud.cfg"  (URL is  "
https://x.x.x.x/owncloud" )
08-19 16:20:12:904 Loading config:
"/home/user/.local/share/data//ownCloud/owncloud.cfg"  (URL is  "
https://x.x.x.x/owncloud" )
08-19 16:20:12:904 * Setup folders from
"/home/user/.local/share/data//ownCloud/folders"
08-19 16:20:12:905 Loading config:
"/home/user/.local/share/data//ownCloud/owncloud.cfg"  (URL is  "
https://x.x.x.x/owncloud" )
08-19 16:20:12:910 SocketApi:  ctor:
"/home/user/.local/share/data/ownCloud/socket"
08-19 16:20:12:910 SocketApi:  server started
08-19 16:20:12:922 !!! Mirall::CheckServerJob created for  QUrl( "
https://x.x.x.x/owncloud" )  querying "status.php"
08-19 16:20:12:937 SSL-Warnings happened for url  "
https://x.x.x.x/owncloud/status.php"
08-19 16:20:12:943 Certs are already known and trusted, Warnings are not
valid.
08-19 16:20:12:988 status.php returns:  QMap(("edition", QVariant(QString,
"") ) ( "installed" ,  QVariant(bool, true) ) ( "maintenance" ,
QVariant(bool, false) ) ( "version" ,  QVariant(QString, "8.0.3.4") ) (
"versionstring" ,  QVariant(QString, "8.0.3") ) )    0  Reply:
QNetworkReplyImpl(0xad1c30)
08-19 16:20:12:988 ** Application: ownCloud found:   QUrl( "
https://x.x.x.x/owncloud/status.php" )   with version  "8.0.3" ( "8.0.3.4"
)
08-19 16:20:12:988 !!! Mirall::PropfindJob created for  QUrl( "
https://x.x.x.x/owncloud" )  querying "/"
08-19 16:20:12:988 # checking for authentication settings.
08-19 16:20:13:269 Connection Validator Result:  "Connected"
08-19 16:20:13:269 ######## Connection and Credentials are ok!
08-19 16:20:13:269 ######## connected to ownCloud Server!
08-19 16:20:13:908 !!! Mirall::CheckQuotaJob created for  QUrl( "
https://x.x.x.x/owncloud" )  querying "/"
08-19 16:20:44:070 !!! Mirall::CheckQuotaJob created for  QUrl( "
https://x.x.x.x/owncloud" )  querying "/"

**Comment by dragotin** [comment]
@mlindley is it true that you have client version 1.5.0? If so, please urgently update

**Comment by dragotin** [comment]
I can see the same symptom with 2.0.0 RC1 at the moment. No special log output or console warning.

**Comment by guruz** [comment]
@mlindley Could you tell us which Qt version the ```owncloud``` is using?

**Comment by mlindley** [comment]
@Klaas: Yes I had client version 1.5.0. I installed it through the
elementary OS software center. It looks like Ubuntu removed it but
elementary os did not. I have updated to 1.8.4-1 for ubuntu 14.04 following
the instructions linked below. Thank you.
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

@Markus: I cannot tell you what was listed for version 1.5.0 because I have
upgraded to 1.8.4-1, which lists Qt 4.8.6 on the general settings page.

Behavior after upgrading: Right clicking the owncloud icon in the wingpanel
tray (top right) brings up the context menu. Selections made from that menu
do not work. However, if I leave owncloud running and then attempt to open
it again via the applications menu (top left) or terminal the settings
window opens on the desktop and can be used. Throughout this all the right
click menu from the wingpanel remains useless. Also I have to re-trust my
server ssl certificate each time I run the program.

Terminal output of first execution:

user@elemos:~$ owncloud --logwindow
Gtk-Message: Failed to load module "pantheon-filechooser-module"
Gtk-Message: Failed to load module "pantheon-filechooser-module"

(owncloud:6655): Gtk-CRITICAL **: IA__gtk_widget_get_direction: assertion
'GTK_IS_WIDGET (widget)' failed

(owncloud:6655): Gtk-CRITICAL **: IA__gtk_widget_get_direction: assertion
'GTK_IS_WIDGET (widget)' failed



Logwindow output of first execution:

08-20 07:48:06:568 0x2220ab0 Checking server and authentication
08-20 07:48:06:569 0x2220ab0 Trying to look up system proxy
08-20 07:48:06:569 0x27e6d10 virtual void OCC::SystemProxyRunnable::run()
Starting system proxy lookup
08-20 07:48:06:571 0x2220ab0 void
OCC::ConnectionValidator::systemProxyLookupDone(const QNetworkProxy&)
Setting QNAM proxy to be system proxy "2://:0"
08-20 07:48:06:592 0x2220ab0 !!! OCC::CheckServerJob created for "
https://x.x.x.x/owncloud" + "status.php"
08-20 07:48:10:255 0x2220ab0 Client is on latest version!
08-20 07:48:22:239 0x2220ab0 SSL-Connection is trusted:  true
08-20 07:48:22:284 0x2220ab0 status.php returns:  QMap(("edition",
QVariant(QString, "") ) ( "installed" ,  QVariant(bool, true) ) (
"maintenance" ,  QVariant(bool, false) ) ( "version" ,  QVariant(QString,
"8.0.3.4") ) ( "versionstring" ,  QVariant(QString, "8.0.3") ) )    0
Reply:  QNetworkReplyImpl(0x281b5d0)
08-20 07:48:22:285 0x2220ab0 ** Application: ownCloud found:   QUrl( "
https://x.x.x.x/owncloud/status.php" )   with version  "8.0.3" ( "8.0.3.4"
)
08-20 07:48:22:302 0x2220ab0 Checking server and authentication
08-20 07:48:22:302 0x2220ab0 Trying to look up system proxy
08-20 07:48:22:302 0x27e6d10 virtual void OCC::SystemProxyRunnable::run()
Starting system proxy lookup
08-20 07:48:22:303 0x2220ab0 void
OCC::ConnectionValidator::systemProxyLookupDone(const QNetworkProxy&)
Setting QNAM proxy to be system proxy "2://:0"
08-20 07:48:22:303 0x2220ab0 !!! OCC::CheckServerJob created for "
https://x.x.x.x/owncloud" + "status.php"
08-20 07:48:22:334 0x2220ab0 status.php returns:  QMap(("edition",
QVariant(QString, "") ) ( "installed" ,  QVariant(bool, true) ) (
"maintenance" ,  QVariant(bool, false) ) ( "version" ,  QVariant(QString,
"8.0.3.4") ) ( "versionstring" ,  QVariant(QString, "8.0.3") ) )    0
Reply:  QNetworkReplyImpl(0x27a2b20)
08-20 07:48:22:334 0x2220ab0 ** Application: ownCloud found:   QUrl( "
https://x.x.x.x/owncloud/status.php" )   with version  "8.0.3" ( "8.0.3.4"
)
08-20 07:48:22:334 0x2220ab0 # Check whether authenticated propfind works.
08-20 07:48:22:335 0x2220ab0 !!! OCC::PropfindJob created for "
https://x.x.x.x/owncloud" + "/"
08-20 07:48:22:614 0x2220ab0 !!! OCC::JsonApiJob created for "
https://x.x.x.x/owncloud" + "ocs/v1.php/cloud/capabilities"
08-20 07:48:22:688 0x2220ab0 Server capabilities QVariant(QVariantMap,
QMap(("core", QVariant(QVariantMap, QMap(("pollinterval",
QVariant(qulonglong, 60) ) )  ) ) ( "files" ,  QVariant(QVariantMap,
QMap(("bigfilechunking", QVariant(bool, true) ) ( "undelete" ,
QVariant(bool, true) ) ( "versioning" ,  QVariant(bool, true) ) )  ) ) )  )
08-20 07:48:22:688 0x2220ab0 AccountState connection status change:
"Undefined" -> "Connected"
08-20 07:48:22:688 0x2220ab0 AccountState state change:  "Disconnected" ->
"Connected"
08-20 07:48:22:692 0x2220ab0 Enabling sync scheduler, scheduling all
folders
08-20 07:48:23:689 0x2220ab0 !!! OCC::CheckQuotaJob created for "
https://x.x.x.x/owncloud" + "/"
08-20 07:48:36:435 0x2220ab0 void
OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the
remote ETag
08-20 07:48:38:569 0x2220ab0 # Check whether authenticated propfind works.
08-20 07:48:38:570 0x2220ab0 !!! OCC::PropfindJob created for "
https://x.x.x.x/owncloud" + "/"

**Comment by mlindley** [comment]
Sorry guys. After updating as Klaas suggested and playing with things I can
say that this seems to be an elementary OS wingpanel problem, not an
owncloud problem.

The contexts menus for everything in the wingpanel tray open with either a
left or right click. After you open that menu, menu selections must be made
with the same mouse button. Open with right click, select with right click,
success. Open with left click, select with left click, success. Open with
right or left click, select with alternate click, failure.

I am used to right click open, left click select for context menus and that
doesn't work for wingpanel apparently.

And after successfully quitting owncloud via the context menu it is no
longer asking me to trust my server's ssl cert when I open owncloud.

Thanks and sorry to bother you!

**Comment by dragotin** [comment]
Ok, thanks for letting us know.
