### ISSUE TITLE
minor message edit

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3649]
Hi,

A minor improvement in 2.0rc -- what massaging this text a bit, sth like this:

Do you really want to remove the connection to the account xyz@abc.com?
Note: This will not remove files from your computer.

![image](https://cloud.githubusercontent.com/assets/621965/9355692/b483b2da-467b-11e5-9edb-367b4824269e.png)

**Comment by guruz** [comment]
FYI @ckamm @jancborchardt @tflidd

**Comment by ckamm** [comment]
Good point @moscicki

**Comment by rperezb** [comment]
@davitol can you please check this one?
@ckamm can you please point him to where to download the version which includes this fix

**Comment by jancborchardt** [comment]
Good point on the first line. The second line should be the one @ckamm suggested in another issue (can’t find it atm, @ckamm?).

The buttons also need to be properly labeled – »Yes« and »No« are not very intelligible. They should be changed instead to: »Remove connection« and »Cancel«.

**Comment by ckamm** [comment]
@jancborchardt Since changing the buttons is slightly more than a string change I'll make a different ticket for it and push it into 2.0.1.

**Comment by davitol** [comment]
:+1: to the above message shown:

Do you really want to remove the connection to the account

but below it is shown:

Note: This will not delete any files.

and the issue recommends

This will not remove the files from your client

**Comment by jancborchardt** [comment]
@davitol this was suggested by @ckamm in another issue and we agreed upon the sentence »Note: This will not delete any files.« – so that’s what we will use.

@ckamm cool, that works!
