### ISSUE TITLE
[2.0.1 RC1] 'Add Folder'-button glued to the top

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#3650]
If there is no folder definition defined the "Add Folder to Synchronize" button is very much glued to the top. It should have some margin, or even a bit of text around it, or background, dunno.  

![glued_folder](https://cloud.githubusercontent.com/assets/1070214/9356622/571f5c5a-4682-11e5-9073-1315a6980813.png)

@jancborchardt please advice.

**Comment by dragotin** [comment]
Same if there is a folder config.

![glued_folder1](https://cloud.githubusercontent.com/assets/1070214/9356736/180a4132-4683-11e5-99fd-d1a4a55a0dc4.png)

Just saying, I still think it would be better if the "Add Folder to Synchronize" button would be a normal button (same as the Delete-Button) underneath the tree view that displays the folder and selective sync. And the stuff that now appears underneath the listview should move into a box within the listview on the right, that only appears if there is an action required.

Sketch:
![scribble](https://cloud.githubusercontent.com/assets/1070214/9357627/584a69b6-4688-11e5-8c6f-bca612dbd6c3.png)

**Comment by ckamm** [comment]
@dragotin I'll look at the margin for 2.0.0 - could you make a new ticket / rename this one for your ui suggestion?

**Comment by rperezb** [comment]
@davitol can you please check this one?
@ckamm can you please point him to where to download the version which includes this fix

**Comment by jancborchardt** [comment]
Yup, just give the button a bit of top margin.

**Comment by ckamm** [comment]
@davitol Since this went in yesterday, the nightly 2015-8-20 should have the change: http://download.owncloud.com/desktop/daily/

**Comment by davitol** [comment]
:+:1 looks good in version 2.0.0-nightly20150820 (build 2651)

**Comment by phil-davis** [comment]
Version 2.0.0-nightly20150820 (build 5412)
The spacing looks better to me.
Note that if I hover anywhere around the "stripe" of vertical space above and with the button a strip highlights like this:
![owncloudaddfolder](https://cloud.githubusercontent.com/assets/1535615/9378513/c4b83a10-4741-11e5-807d-68f995211cd0.png)
The highlighted strip does not line up exactly with the button. To activate the action I need to click in the highlighted strip. If I click towards the bottom of the button, but below the highlighted strip, then nothing happens.

**Comment by jancborchardt** [comment]
@davitol why did you close this? The issue @phil-davis reported has to be fixed before.

**Comment by davitol** [comment]
@jancborchardt I thought I would be another issue not related with the first problem

**Comment by jancborchardt** [comment]
No, it’s related to this because the shift only apeared after moving the button.

**Comment by phil-davis** [comment]
Tested with Version 2.0.0-nightly20150821 (build 5413).
Looks good now in all cases (empty screen and existing folders with button at the end of the list).

**Comment by jancborchardt** [comment]
@phil-davis thanks for verifying! :)
