### ISSUE TITLE
[2.0RC1] Quota usage not readable

### ISSUE THREAD

**Issue by Helios07** [owncloud/client#3651]
![owncloud_testpilot_design](https://cloud.githubusercontent.com/assets/3447175/9357124/79605d98-4685-11e5-8e66-9facd45ebf7a.png)
The quota usage is not readable (black writing on dark blue background), if you upload significant amounts of data. It would be better if the colour of the text would turn to white on the blue background.

**Comment by guruz** [comment]
@ckamm @jancborchardt @ogoffart What can be done there? Is there a way to have a font display a small border around each glyph? Like a shadow?

**Comment by ckamm** [comment]
What if we don't write text into the progress bar? Instead make it very thin and add text above? May not be 2.0.0 material...

**Comment by guruz** [comment]
Last time I checked: It's also weird that we put a QLabel inside the QProgressBar instead of just using http://doc.qt.io/qt-4.8/qprogressbar.html#format-prop ?

**Comment by ckamm** [comment]
What I had in mind:
![storage](https://cloud.githubusercontent.com/assets/833306/9359655/7d3d0832-4692-11e5-963e-ecafbbebab32.png)

**Comment by guruz** [comment]
@ckamm @jancborchardt Use same thin style for download progress bar?

**Comment by jancborchardt** [comment]
@ckamm good call! I like your design-mindedness. :) And @guruz yep on the sync progress bar too. It doesn’t need to be that giant.

**Comment by ckamm** [comment]
The patch can go in once 2.0.0 is branched off.

@jancborchardt Since there's two lines of text to the right of the sync progress bar, making it thinner doesn't look good without also adjusting the text position (and maybe content). Let's discuss that in #3403.

**Comment by Helios07** [comment]
Hi there,

thank you for your fast reaction.

**Comment by Dianafg76** [comment]
I tested this issue with Desktop v ownCloud-2.0.1.2669-nightly20150826.pkg and is working OK.
Closed

**Comment by jancborchardt** [comment]
@ckamm I think I asked in a different issue as well but am not sure: Can you remove the grey box / border / line around the whole »Storage space« block?
