### ISSUE TITLE
Change buttons on confirmation messageboxes

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#3654]
From #3649 and @jancborchardt 

> The buttons also need to be properly labeled – »Yes« and »No« are not very intelligible. They should be changed instead to: »Remove connection« and »Cancel«.

This applies to the account and folder deletion confirmation box. Also double check other message boxes.

**Comment by ckamm** [comment]
The patch adjusts the "delete account" and "delete folder" confirmation message boxes. It can go in once 2.0.0 is branched.

**Comment by Dianafg76** [comment]
I tested this issue with Desktop v ownCloud-2.0.1.2669-nightly20150826.pkg and is working OK.
Closed

**Comment by jancborchardt** [comment]
@Dianafg76 so, close the issue? :)
