### ISSUE TITLE
Skip folders configuration option should be in another window

### ISSUE THREAD

**Issue by davitol** [owncloud/client#3655]
### Steps to reproduce
1. Configure a new account in the desktop client
2. Select the files/folders to sync
### Expected behaviour

The option of the Skip folders configuration should appear in the same window "Choose What to Sync"
Note: Maybe it would be also necessary to include in the button label something about that if you click this option, the app will start the sync; e.g  Skip folders configuration and connect
### Actual behaviour

The option of the Skip folders configuration appears in the Connect to ownCloud wizard
### Server configuration

**Operating system**:
 (Ubuntu)

**Web server:**
nginx/1.4.6

**Database:**

**PHP version:**
PHP/5.5.9-1ubuntu4.4

**ownCloud version:**

"version":"8.2.0.4","versionstring":"8.2 pre alpha"

**Are you using encryption:** no
### Client configuration

mac version V2.0.0. RC1

**Operating system:**
Mac OS 10.10.3

![choosefilesdsk](https://cloud.githubusercontent.com/assets/10596560/9378279/6aa3b2fa-4720-11e5-88a8-3c9dc0933157.png)

**Comment by guruz** [comment]
Opinions @pmaier1 @SamuAlfageme ?

**Comment by SamuAlfageme** [comment]
@guruz I think it's clear enough as it is; after all, the "Choose what to sync" modal is just an extension of that wizard's page (where the button is located) and there's no way not to go over that one page.

**Comment by pmaier1** [comment]
> I think it's clear enough as it is; after all, the "Choose what to sync" modal is just an extension of that wizard's page (where the button is located) and there's no way not to go over that one page.

Yes, I also don't see a reason to change this. Maybe @davitol can elaborate a bit on why this is suggested. For me hitting 'Choose what to sync' is already part of the "configuration process" so I need to be able to skip it before as it is now.

**Comment by ogoffart** [comment]
Now it's a radio button
