### ISSUE TITLE
[linux] Crash on context menu use

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#3656]
@dragotin found the issue where clicking the "Open ... in browser" action in the tray menu can cause a crash. Clicking the other actions has no effect. Since Qt 5.5.0. Valgind: https://cpaste.org/pzugpz3s1

@ogoffart found https://bugreports.qt.io/browse/QTBUG-46293 which likely is the cause. It seems to be related to items not being removed from `menuItemsByID` in http://code.woboq.org/qt5/qtbase/src/platformsupport/dbusmenu/qdbusplatformmenu.cpp.html#menuItemsByID

**Comment by dragotin** [comment]
problem report in upstream bugtracker: https://bugreports.qt.io/browse/QTBUG-47863

**Comment by dragotin** [comment]
@ckamm workaround was tested by me with the buggy Qt version (others do not show this problem anyway) and I could verify that the problem is fixed.
