### ISSUE TITLE
Options 'open in browser' and 'open folder' should be underneath

### ISSUE THREAD

**Issue by davitol** [owncloud/client#3657]
### Steps to reproduce
1. Configure a new account in the desktop client
 

### Expected behaviour

Options 'open in browser' and 'open folder' should be underneath

### Actual behaviour

The options are separated

Note: In 1.8.3. versions they were underneath so it was easily for the UX 

### Server configuration
**Operating system**:
 (Ubuntu)

**Web server:**
nginx/1.4.6

**Database:**

**PHP version:**
PHP/5.5.9-1ubuntu4.4

**ownCloud version:**

"version":"8.2.0.4","versionstring":"8.2 pre alpha"

**Are you using encryption:** no

### Client configuration
mac version V2.0.0. RC1

**Operating system:**
Mac OS 10.10.3

![optionsep](https://cloud.githubusercontent.com/assets/10596560/9379247/2552d624-4728-11e5-9758-087712d6350a.png)

**Comment by ckamm** [comment]
Why should they be directly next to each other? We could switch the positions of 'Sign in/out' and 'Open in browser'?

**Comment by guruz** [comment]
> We could switch the positions of 'Sign in/out' and 'Open in browser'?

If you want to move it, then "Sign out" should be the lowest option...

**Comment by jancborchardt** [comment]
Yes, most definitely the order should be:

> Open in browser
> List of folders
> Log out

(Note that it should be »Log out« instead of »Sign out« as that’s the wording we use in the web interface as well.)

**Comment by dragotin** [comment]
Fixed the wording *Sign in* to *Log in* in 5f660bf080a57172bab091007e0be0146b4ec918

Otherwise, the ordering of the menus is as described above.

**Comment by jancborchardt** [comment]
Thanks! :)

**Comment by Dianafg76** [comment]
I tested this issue, I tried this, and the order is the same as in previous versions:: 
![screen shot 2015-09-14 at 11 28 50](https://cloud.githubusercontent.com/assets/12032058/9846651/cf57f938-5ad3-11e5-87d5-1b0d29a20bf2.png)

**Comment by dragotin** [comment]
@Dianafg76 but isn't that what @jancborchardt wants? see https://github.com/owncloud/client/issues/3657#issuecomment-134116489

**Comment by jancborchardt** [comment]
@Dianafg76 See @davitol’s original screenshot in https://github.com/owncloud/client/issues/3657#issue-102091715 – this is about the order of the individual account section in the tray menu.

**Comment by Dianafg76** [comment]
I'm sorry , I confused screen
![screen shot 2015-09-14 at 15 06 53](https://cloud.githubusercontent.com/assets/12032058/9850460/0d33f544-5af3-11e5-9aec-07ced30f5863.png)

**Comment by jancborchardt** [comment]
Hm, Log out is still above the folder list there.

Also, »Log out everywhere« should be named »Log out of all accounts« instead.

**Comment by dragotin** [comment]
ah in the sub menu... ok. Anyway, no time left, will postpone to next MS

**Comment by jancborchardt** [comment]
Sure, only a detail anyway.

**Comment by Dianafg76** [comment]
I tested this, and now the "open in browser" option and "open folder " you can see bellow

Desktop v ownCloud-2.1.0.2821-nightly20151022.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}
Closed
