### ISSUE TITLE
(non-standard) port number should be included in the name shown in the account list

### ISSUE THREAD

**Issue by davitol** [owncloud/client#3658]
### Steps to reproduce

1. Configure a new account in the desktop client using a docker container
2. Configure another account using another container
 
### Expected behaviour

The port used by the docker container should be shown in the info of the available accounts in order to can differentiate from each container.

### Actual behaviour

The info about the port is not shown, so the accounts cannot be distinguished.

### Server configuration
**Operating system**:
 (Ubuntu)

**Web server:**
nginx/1.4.6

**Database:**

**PHP version:**
PHP/5.5.9-1ubuntu4.4

**ownCloud version:**

"version":"8.2.0.4","versionstring":"8.2 pre alpha"

**Are you using encryption:** no

### Client configuration
mac version V2.0.0. RC1

**Operating system:**
Mac OS 10.10.3

![nombrelargo](https://cloud.githubusercontent.com/assets/10596560/9380649/e29e6f00-4731-11e5-9245-b46ffe1d791d.png)

**Comment by danimo** [comment]
![image](https://cloud.githubusercontent.com/assets/1315934/9783500/f28adefc-57a4-11e5-932c-5c6286a56927.png)

**Comment by guruz** [comment]
@danimo FYI 1de4d96ab1978ea15724c6eaa955bac6b36650f3

**Comment by Dianafg76** [comment]
I tested this issue, and now The info about the port is shown
Closed
