### ISSUE TITLE
Leading slash should be shown in sharing with owncloud window

### ISSUE THREAD

**Issue by davitol** [owncloud/client#3659]
### Steps to reproduce

1. Configure a new account in the desktop client
2. Share a file or a folder located in root
 
### Expected behaviour

In the share window, after the Folder: it should appear  a slash '/'

### Actual behaviour

Nothing shown after Folder:

Note: If the file is not located in root, the info is shown OK with the leading slash included

### Server configuration
**Operating system**:
 (Ubuntu)

**Web server:**
nginx/1.4.6

**Database:**

**PHP version:**
PHP/5.5.9-1ubuntu4.4

**ownCloud version:**

"version":"8.2.0.4","versionstring":"8.2 pre alpha"

**Are you using encryption:** no

### Client configuration
mac version V2.0.0. RC1

**Operating system:**
Mac OS 10.10.3

![rootind](https://cloud.githubusercontent.com/assets/10596560/9381186/732d06c8-4735-11e5-9032-c9cfd59b6a02.png)

**Comment by rullzer** [comment]
I agree this looks weird. But then it should always show the ```/``` I think.

**Comment by ckamm** [comment]
Note that the change restores the behavior the existing code seemed to intend: Don't show "Folder: " at all in the root folder.

**Comment by Dianafg76** [comment]
I tested this issue, and now when you Share a file or a folder located in root, Nothing shown. 
![screen shot 2015-09-14 at 13 09 13](https://cloud.githubusercontent.com/assets/12032058/9848494/ed672774-5ae1-11e5-94c6-39cbd42d42c9.png)

And If the file is not located in root, you show 
![screen shot 2015-09-14 at 13 11 30](https://cloud.githubusercontent.com/assets/12032058/9848552/7c1fd894-5ae2-11e5-9f49-29945495933a.png)

Note: But now the / not shown

Desktop vownCloud-2.0.2.2713-nightly20150914.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.1.3","versionstring":"8.1.1","edition":"Enterprise"}

**Comment by ckamm** [comment]
@Dianafg76 What you see now is the original intended behavior that I restored. An alternative would have been to always show "Folder:" and keep the / prefix. Both work for me. @jancborchardt feel free to reopen if you feel strongly about this.

**Comment by Dianafg76** [comment]
@ckamm Ok, thanks

**Comment by jancborchardt** [comment]
Yep @ckamm correct.
* in any folder, show: »Folder: foldername« without preceding or appended slashes
* in root folder, show nothing at all. Ideally also vertically center the filename then with the icon @ckamm to account for the newly free space if that is possible.
