### ISSUE TITLE
Notifications show a confused information about folders

### ISSUE THREAD

**Issue by davitol** [owncloud/client#3660]
### Steps to reproduce

1. Configure a new account in the desktop client
2.  Access to a folder, the folder has a 5 level folders inside
3. Upload some files
 
### Expected behaviour

The notification shown should be referred only to the last subfolder, or indicate the complete root.

### Actual behaviour

The folders are 'consider as files' and it is only shown the name of the parent folder.

### Server configuration
**Operating system**:
 (Ubuntu)

**Web server:**
nginx/1.4.6

**Database:**

**PHP version:**
PHP/5.5.9-1ubuntu4.4

**ownCloud version:**

"version":"8.2.0.4","versionstring":"8.2 pre alpha"

**Are you using encryption:** no

### Client configuration
mac version 2.0.0-nightly20150820 (build 2651)

**Operating system:**
Mac OS 10.10.3

![notificationswr](https://cloud.githubusercontent.com/assets/10596560/9382149/41c2612e-473e-11e5-8fbf-2cc260ff4089.png)

**Comment by phil-davis** [comment]
Related https://github.com/owncloud/client/issues/3613 also discusses notifications of a mix of folder and file updates.

**Comment by davitol** [comment]
Then I'll close it and we'll focus on the other issue
