### ISSUE TITLE
[Windows] Installer hangs if setup is started twice

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#3667]
When starting the owncloud client setup on WIn 8.1 with a double click, you can accidently start two installer sessions and then it hangs with this screenshot:
![screenshot 4](https://cloud.githubusercontent.com/assets/8111200/9427688/759318f6-498a-11e5-9888-e036fd503185.png)

Surface Pro 3
Win 8.1
OC Client 1.8.4 installer

Via task manager, you have to close the second owncloud-setup.exe and vcredist_x64.exe, then the installer continues.

Is it possible to detect at startup if there is already an owncloud installer running?

**Comment by danimo** [comment]
Which version is that installer for? It should already be impossible to start two installers in parallel.

**Comment by tflidd** [comment]
It was 1.8.4 (the version is shown in the screenshot). The task-manager shows two processes of owncloud-setup.exe, I didn't see two windows.

**Comment by danimo** [comment]
That's a misconception: you see two instances because the installer starts another copy of itself, with elevated rights.

**Comment by tflidd** [comment]
Ok, I've seen the same on Windows7 (two instances in the task manager) where it was no problem. But on Win 8.1 that the installer hang and that I needed to kill the second instance to continue.

**Comment by danimo** [comment]
I cannot start the installer twice. Doing so will result in a message box telling me that the installer is already running.

**Comment by tflidd** [comment]
I thought so in the beginning because I've seen two processes in my task manager. I probably didn't start the client twice:
> That's a misconception: you see two instances because the installer starts another copy of itself, with elevated rights.

Hope that it is clearer now.

**Comment by danimo** [comment]
Ok, so that means the installer never returns from installing the visual studio runtime. How long did you wait? It takes a minute or two.

**Comment by tflidd** [comment]
I waited some time. 30s at least, maybe around a minute, could be that I didn't wait full 2 minutes. But why did it succeed when I killed the process, is this visual studio runtime not needed?

**Comment by danimo** [comment]
@tflidd It is, but oftentimes other applications have already installed it.

**Comment by tflidd** [comment]
Ok. It's not my computer, so I can't verify if I didn't wait long enough. It very likely because there are no other reports. I close it.
