### ISSUE TITLE
When clicking on a folder, nothing happens

### ISSUE THREAD

**Issue by StephaneDupont** [owncloud/client#3668]
I juste installed 2.0.0rc2, and in the list of folders, when we click on one folder, nothing happens.

I mean, everything works, a right click will give me contextual menu, a click on the arrow will open the list of subfolders, and a click on the "..." give me the same thing than a right click. But clicking on a folder name should do something! Even if it's only to have the "pale blue" applied to the folder row. But we must have a visual feedback, it is really strange for now.

**Comment by phil-davis** [comment]
Discussion about this at https://github.com/owncloud/client/issues/3585
For that issue various changes have been made that are in the 2.0 RC1 and RC2 - like the "..." was added.
Double-click opens the list of subfolders.
It is still being discussed about what single-click should do there, so I suggest you put your thoughts there.

**Comment by StephaneDupont** [comment]
OK, thank you, and sorry for the double post.

**Comment by guruz** [comment]
@ogoffart I guess it's not trivial to have the alias name be a "hover link" and then on click open the local folder?

**Comment by dragotin** [comment]
Let's close this and continue in #3585
