### ISSUE TITLE
Tabs are missing padding?

### ISSUE THREAD

**Issue by StephaneDupont** [owncloud/client#3669]
I juste installed 2.0.0rc2, and it's like the tabs are missing some padding or something. For now it is quite ugly:

![untitled-2](https://cloud.githubusercontent.com/assets/5102441/9429415/92c57172-49cf-11e5-9e67-dea6cb4a10bf.png)

**Comment by dragotin** [comment]
Is it that your user name is *steph* on a server called eluna.net, .com or whatever? Yes, I agree, a bit of a margin would be nice.

**Comment by dragotin** [comment]
@danimo, @ogoffart something that we still wanna patch?

**Comment by StephaneDupont** [comment]
Yes, username steph and eluna is part of my domain.

**Comment by danimo** [comment]
@jancborchardt please

**Comment by jancborchardt** [comment]
Yeah, there should be a min-width on all the entries. Is that possible? The spacing of »General« and »Network« look good in @StephaneDupont’s screenshot, can we have the min-width on each entry set so it looks like that?

**Comment by Dianafg76** [comment]
I tested this issue, and Now there is a minimum width of all entries
Desktop vownCloud-2.0.2.5447-nightly20150902-setup.exe  
Closed

**Comment by jancborchardt** [comment]
Awesome work! Great details :)
