### ISSUE TITLE
[2.0.0rc2] [Testpilot only] Client does not initially load remote content

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#3671]
### Steps

1. Setup OC v8.1.1
1. Upload a few files (I did not have any folders)
1. Create local folders "test/config" and "test/data"
1. Run `testpilotcloud --confdir ~/test/config --logfile ~/test/sync.log`
1. Enter URL "http://localhost/owncloud"
1. Select "~/test/data" for the sync dir
1. Confirm
1. Wait for sync

### Expected result
Client downloads the files from the server

### Actual result
Nothing happens.
If I create a file locally, it will upload it, but it ignores the remote file.
Sometimes I get the dialog "this would delete all files, keep local or delete all ?"

### Versions
ownCloud server 8.1.1
testpilotcloud-client-2.0.0~rc2-2.2.x86_64 from OBS

@guruz @ogoffart

**Comment by PVince81** [comment]
The same steps work fine with 1.8.4, for reference.

**Comment by ckamm** [comment]
@PVince81 I cannot reproduce it with ownCloud 8.1.0.8 with a files-only account and fresh settings. I'll try with 8.1.1 now.

**Comment by PVince81** [comment]
@ogoffart said on IRC that it might be that the test pilot cloud has selective sync not select anything by default. I didn't select anything, so only new files get auto-selected.
The final version would be different ?

**Comment by ckamm** [comment]
@PVince81 The suggestion about selective sync with the testpilot edition sounds good. (can't reproduce with 8.1.1)

**Comment by ckamm** [comment]
@PVince81: @ogoffart was correct the testpilot client is built with wizardSelectiveSyncDefaultNothing() set to true. The selective sync dialog should pop up during account creation and you need to explicitly select what should be synced. I'll also play with that now.

**Comment by ckamm** [comment]
I can reproduce the issue by enabling wizardSelectiveSyncDefaultNothing and then clicking 'cancel' on the selective sync dialog. That will keep a selective sync blacklist of '/', meaning nothing is synced.

**Comment by PVince81** [comment]
In my case I didn't have folders so the dialog told me there is nothing that can be selected, or something.

**Comment by ogoffart** [comment]
The cancel should indeed keep everything unselected. This is intentional (see https://github.com/owncloud/client/issues/2580#issuecomment-73063583 )

**Comment by ckamm** [comment]
@ogoffart I changed the behavior such that cancelling the dialog now leaves all top-level folders on the selective sync dialog. It would be easy to adjust it (and make the code simpler) to just have an empty blacklist on cancel.

**Comment by ckamm** [comment]
With the latest patch I no longer see the bug @PVince81 reported and the cancel button behaves in the way @ogoffart suggested (sync everything).

**Comment by ogoffart** [comment]
The cancel button should sync nothing

**Comment by guruz** [comment]
@Dianafg76 This is only relevant for the testpilot client.

**Comment by Dianafg76** [comment]
@guruz Hello, I can´t reproduce this issue. I tested with Desktop v Testpilot Edition-2.0.0.2665-nightly20150824.pkg. Server v {"installed":true,"maintenance":false,"version":"8.1.1.2","versionstring":"8.1.1 RC1","edition":"Enterprise"}

**Comment by guruz** [comment]
great!
