### ISSUE TITLE
[Windows] [Domain accounts] Passwords not saved

### ISSUE THREAD

**Issue by season-of-mist** [owncloud/client#3673]
After moving our user profiles from local to domain account, owncloud clients keeps asking for the user's password. If we log in on a local account, the client runs fine (without asking for the password). Please note that we're not using LDAP to authenticate our users.

### Steps to reproduce
1. Log in on a local user account
2. Run the client
2. Join a computer to an AD domain.
3. Log in on a domain user account.
4. Run the client.

### Server configuration
Operating system: Debian Wheezy
Web server: Apache v2.2.22
Database: MySQL v5.5.44
PHP version: 5.4.41
ownCloud version: v8.0.2

### Client configuration
Client version: v1.8.4
Operating system: Windows 7 and Windows 8.1
OS language: en_us
Installation path of client: C:\Program Files (x86)\ownCloud\owncloud.exe

### Logs
1. Client log: 
https://gist.github.com/season-of-mist/14443782a2360df53a15

2. Web server error log:
Nothing relevant

3. ownCloud log (data/owncloud.log): 
{"reqId":"0beab7d00357a2f62810360b9b9a3091","remoteAddr":"128.127.16.241","app":"core","message":"Login failed: 'gunnar' (Remote IP: '128.127.16.241', X-Forwarded-For: '')","level":2,"time":"August 24, 2015 15:42:53"}

**Comment by MTRichards** [comment]
@guruz Seems you know something I don't here. Are you saying this is a feature request?

**Comment by guruz** [comment]
@season-of-mist How are the home directories stored?
Is this a roaming profile?

**Comment by guruz** [comment]
@season-of-mist And is it just passwords but also sync folder configurations?
server URLs?

**Comment by guruz** [comment]
@frankosterfeld is this a known issue?

**Comment by frankosterfeld** [comment]
@guruz: Nope, haven't heard about this one yet. Do you know if there's any error returned by qtkeychain?

**Comment by danimo** [comment]
It works with a stock domain account, but there isn't an account by the same name on the local machine, so that must be the issue...

**Comment by guruz** [comment]
@danimo So what's the issue with regards to QtKeyChain? You mean it works if there is also a local account?

**Comment by ogoffart** [comment]
Closing old bug with missing information.

**Comment by season-of-mist** [comment]
Sorry for the late reply... I haven't received any notifications...

@guruz Yes it's just passwords. Configuration files are stored in C:\Users\%USERNAME%\AppData\Local\ownCloud. No roaming profiles. Home directories are stored locally.

I tried to delete the folder C:\Users\%USERNAME%\AppData\Local\ownCloud and run the client. The file owncloud.cfg doesn't store the password (should it be?)

**Comment by guruz** [comment]
@season-of-mist You might want to subscribe to https://github.com/owncloud/client/issues/4429

**Comment by season-of-mist** [comment]
@guruz Thank you
