### ISSUE TITLE
[Activity tab] Message too long when Virus was detected

### ISSUE THREAD

**Issue by stonerl** [owncloud/client#3676]
### Expected behaviour
The message shown in the Action-tab, when a Virus was detected, is way to long and does not fit in the window.

### Actual behaviour
Here is the message I get:
```
The item is not synced because of previous errors: Error downloading https://owncloud.example.org/remote.php/webdav/Music/test-virus - server replied: Unsupported Media Type (Virus Eicar-Test-Signature is detected in the file. Upload cannot be completed.)
```
### Steps to reproduce
1. Create a file with the Eicar-Test-Signature.
2. Place this file in a sync-folder
3. Wait for the sync.

### Client configuration
Client version: 2.0.0-nightly20150824 (build 2664)

Operating system: OSX 10.10.5

OS language: en-US

**Comment by guruz** [comment]
@ogoffart Can a tree view easily have multi-line text in one column?

**Comment by ogoffart** [comment]
maybe using QTreeView::setWordWrap

**Comment by ogoffart** [comment]
I tried and the message is ellided with a tooltip, and i think it is good engough for now.

Anyway. We will re-design the activity for 2.1 
https://github.com/owncloud/client/issues/3732
