### ISSUE TITLE
[1.8.0] The client has wiped clean all data from my computer

### ISSUE THREAD

**Issue by Pastafarianist** [owncloud/client#3681]
At `2015-08-25 21:56` I was running a script which was dumping some data in an SQLite database within my `ownCloud` folder. Suddenly, the IDE reported that it couldn't find the VCS root anymore. I checked the folder where only minutes ago the VCS resided, only to find out that it was practically empty. The only files which were left from the entire ownCloud installation was the aforementioned database and some screenshots which had weird characters in their names (like `~` and `|`).

![](https://cloud.githubusercontent.com/assets/1315874/9477305/4decb09a-4b7a-11e5-8431-5b40c9f78f38.png)

15 minutes later, the client announced (via a notification) that ".directory and 5xxxx other files were deleted".

It *looks like* the files on the server are unaffected. They are still in my `data/<username>/files` directory. I have no complete up-to-date backup though (the most recent is a day old), so I can't verify this easily. The client reports that it's "opening" a folder somewhere in my archive. The activity log in the web interface has nothing about the wipe.

`.owncloudsync.log` contains this:

    # timestamp | duration | file | instruction | dir | modtime | etag | size | fileId | status | errorString | http result code | other size | other modtime | other etag | other fileId | other instruction
    #=#=#=# Syncrun started 2015-08-25T21:58:15 until 2015-08-25T22:12:06 (830450 msec)
    |0|.directory|INST_REMOVE|Down|1436828337|db140290e900187708405d3271e866bb|59||4||0|0|0|||INST_NONE|
    < ... and the same INST_REMOVE for the rest of my files ... >

`.owncloudsync.log.1:`

    #=#=#=# Syncrun started 2015-08-25T21:50:53 until 2015-08-25T21:57:11 (378187 msec)
    |0|.directory|INST_REMOVE|Down|1436828337|db140290e900187708405d3271e866bb|59||4||0|0|0|||INST_NONE|
    < ... >

I have shut down the client since then.

How do I find out what exactly has happened, and how do I recover my installation?

**Comment by guruz** [comment]
@Pastafarianist The current version of the client is 2.0.0, please don't use 1.8.0
It should automatically re-download all data..
If you want to make 100% sure you can remove the ```.csync_journal.db```.

**Comment by guruz** [comment]
Closing this for now..
Please report back if 2.0 restores the data :)

**Comment by Pastafarianist** [comment]
The latest version in the Gentoo repositories is 1.8.4, so I've upgraded to that one. I have also wiped the remains of my `ownCloud` folder from my machine and recreated a new one from scratch. Then I fired up the client and let it do its job. It spent a couple of hours "opening folders" (building the directory tree in memory, I presume?) and then re-downloaded all my data.

Phew.
