### ISSUE TITLE
[NSIS] [Windows] [2.0.0] "The installer requires admin access" loop

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/client#3682]
We are not able to install Version 2.0.0 on *some machines* (Windows 7 Pro x64) We get this error:

![error](https://cloud.githubusercontent.com/assets/9192953/9487351/ffa17eaa-4bd0-11e5-9741-d0f15d7f4c16.png)

If we click on yes then it ends with an endless loop of trying it again. No will give the same error and is closing the installer.

**PS: We tried it with run as Administrator and with the Administrator account iself.**

**Comment by phil-davis** [comment]
Are you in a domain?
I had this trouble during the beta phase and various things were fixed for the domain install case. Obviously there is still some particular Windows configuration that has this issue.

**Comment by pierrejochem** [comment]
My computer is in a domain and there it works without problems (W 8.1 Pro x64). On a computer without domain it isn't working :-(

**Comment by phil-davis** [comment]
Note: some history of this problem at https://github.com/owncloud/client/issues/2616

**Comment by phil-davis** [comment]
I have installed 2.0.0 release version on Windows 10 Home 64-bit (no domain) just now. That does not help you on Windows 7, but is at least a data point to know that the installer works on some Windows out of the domain.

**Comment by pierrejochem** [comment]
I will check the history right now to see if there is a hint for us that could solve it maybe.

**Comment by pierrejochem** [comment]
Maybe a hint for you. I'm using this build:

https://github.com/owncloud/client/commit/2ad57ee8ab534945617ff94535e8bbf6f3840ee0

So the commit for Version 2.0.0

**Comment by phil-davis** [comment]
I found a laptop running Windows7 Professional Service Pack 1, 64-bit, not in any domain. This laptop just had a single user account that has admin privileges. ownCloud 2.0.0 installed fine on it. The UAC Yes/No prompt came up, I said Yes, and then the installer worked fine.
So the failure scenario is more involved than just Windows7 Professional 64-bit no-domain.
Can you think of anything else special about the system that fails to install?

**Comment by phil-davis** [comment]
Note: the 2.0 branch is the one that has been used the last couple of weeks for the 2.0.0 RC1, RC2 and now release (which has a 2.0.0 branch). So that is fine. At the moment "master" is actually "behind" and will catch up when someone merges all the recent work in 2.0 branch back to master.

**Comment by tflidd** [comment]
I had the Testpilot of 2.0.0RC1 on a Win 7 Pro 64 bit not in a domain and I didn't see this error. Doesn't help the OP but it's not this Windows version in general.

**Comment by pierrejochem** [comment]
We use a Windows 7 x64 POS Version

**Comment by guruz** [comment]
@pierrejochem It only happens in POS?

**Comment by pierrejochem** [comment]
Yes and a fresh Installation. Not added to domain. The password request is not shown only the endless Loop. We tried it with a User which is in the Admin Group an as real Administrator

**Comment by pierrejochem** [comment]
I have used this plugin Version:

mingw32-cross-nsis-plugin-uac-0.2.4-3.5

**Comment by danimo** [comment]
@pierrejochem Ah! so you built it yourself? which repo did you use? We switched repos to `https://build.opensuse.org/project/show/isv:ownCloud:toolchains:mingw:win32:stable`, using our own toolchain which contains less upstream-induced surprises. That one also has a fixed-up version of the UAC plugin (compared to `windows:mingw:win32`).

**Comment by danimo** [comment]
See also https://doc.owncloud.org/desktop/2.0/building.html.

**Comment by pierrejochem** [comment]
Yes correct and I use this commit: 2ad57ee8ab534945617ff94535e8bbf6f3840ee0 (Version Tag 2.0.0)

I will check my repos and let you know which one I used. I think I used the one you proposed but I will check it again.

**Comment by pierrejochem** [comment]
[windows_mingw_win32]
name=Cross-toolchain for 32-bit windows and 32-bit windows packages (openSUSE_13.2)
enabled=1
autorefresh=0
baseurl=http://download.opensuse.org/repositories/windows:/mingw:/win32/openSUSE_13.2/
.
.
.
So this is the wrong one :-( correct?

**Comment by danimo** [comment]
Yes, and explains all the trouble you're facing.

**Comment by pierrejochem** [comment]
Thank you!

**Comment by pierrejochem** [comment]
Result after changing to the new repo:

CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR: Found unsuitable version ".0.0`", but
  required is at least "1.0.0" (found
  /usr/i686-w64-mingw32/sys-root/mingw/lib/libssl.dll.a;/usr/i686-w64-mingw32/sys-root/mingw/lib/libcrypto.dll.a)
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:341 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake/Modules/FindOpenSSL.cmake:318 (find_package_handle_standard_args)
  CMakeLists.txt:146 (find_package)

**Comment by pierrejochem** [comment]
S | Name                  | Typ        | Version    | Arch   | Repository                                           
--+-----------------------+------------+------------+--------+------------------------------------------------------
i | mingw32-openssl       | Paket      | 1.0.2d-3.1 | noarch | Stable win32 toolchain based on MinGW (openSUSE_13.2)
    name: mingw32-openssl
  | mingw32-openssl       | Quellpaket | 1.0.2d-3.1 | noarch | Stable win32 toolchain based on MinGW (openSUSE_13.2)
    name: mingw32-openssl
i | mingw32-openssl       | Paket      | 1.0.2d-3.1 | noarch | (Systempakete)                                       
    name: mingw32-openssl
i | mingw32-openssl-debug | Paket      | 1.0.2d-3.1 | noarch | Stable win32 toolchain based on MinGW (openSUSE_13.2)
    name: mingw32-openssl-debug
i | mingw32-openssl-debug | Paket      | 1.0.2d-3.1 | noarch | (Systempakete)                                       
    name: mingw32-openssl-debug

**Comment by pierrejochem** [comment]
As far as I read the check script it is looking in the file: "${OPENSSL_INCLUDE_DIR}/openssl/opensslv.h" but that is not included in the mingw32-openssl package and there is no "devel" package where it could be

**Comment by pierrejochem** [comment]
Okay for everybody who has this problem add this to cmake:

-DOPENSSL_INCLUDE_DIR=/usr/i686-w64-mingw32/sys-root/mingw/include/openssl

**Comment by supportreq** [comment]
I installed the debug package yet the files are not to be seen.. any idea??

**Comment by nasprey** [comment]
Morning guys,

We have started to use OwnCloud over the last couple of weeks at our company (online qualifications) instead of our previous cloud system with DriveHQ. So far we have approx 20 students using the OwnCloud windows client without issues.

We did very early on have an issue with one student using Windows 7 Professional 32Bit who could not install the software and was getting the "This installer requires admin access" error message.

I found this Github thread and added the following to CMAKE to try and resolve the issue:

-DOPENSSL_INCLUDE_DIR=/usr/i686-w64-mingw32/sys-root/mingw/include/openssl

We have a software developer making some small alterations to the client software for us (since I know next to nothing about software dev myself) and he added the above to CMAKE and provided me with a new installer.

In the mean time however the student with the problem just went out and bought a whole new laptop, so I never got a chance to test if this issue was now resolved.

This morning however I received an email from another student also running Windows 7 Professional 32Bit who also is getting the very same error. I have remotely tried disabling UAC, Run as Administrator, Windows Updates, all no no avail.

Could anyone offer any advice on this one please?

Many thanks

**Comment by danimo** [comment]
Please tell your developer to the correct repository to build the client, as decribed in https://github.com/owncloud/client/issues/3682#issuecomment-135658129.

**Comment by nasprey** [comment]
Thanks very much!

**Comment by olahaye74** [comment]
Hi, I hit the problem with ownCloud client 2.1.0-5683 on windows 7 64bits (non admin account) when I want to upgrade from client interface (computer is in a windows domain).
A popup asks for admin account. I give .\local-admin with correct passwd and get:
Unable to elevate, error 5 (not 6)
The client has been installed with the local-admin account using right click, run as administrator (without running as Administrator, I hit the same problem. privilege dialog pops up asking for admin account and then I get the error 5 (not 6).
