### ISSUE TITLE
Add quiet selective sync option to not notify about new large folders

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3683]
Feature:
1) In the General tab, change the words "Ask confirmation before downloading folders larger than..." to:
"Do not automatically download folders larger than..."
2) Add a checkbox:
"Do not notify the user about new large folders"
Default is off.

The default behaviour would be the same as in 2.0.0 - when a new large folder comes on the server, then the client notifies the user and the user opens the client GUI and gets a red message about it and can select the folder for sync (or not).

If checkbox (2) is selected, then any new large folder would be auto-ignored - the client would unselect the large folder for sync without prompting the user.

Use cases:
a) The user has "specialist" devices for which they really do just want to sync down the folders they tell it (e.g. a music player, they sync a "Music" folder, a video player, they sync a "Videos" folder, they just want some of their photos on the client device...).
They would set the confirmation limit to 0 MB and check "Do not notify the user about new large folders". That will let them do "quiet selective sync".

b) In a work environment there is a "Support" folder with sub-folders "Job001", "Job002", "Job003"... The user selective syncs some of the "Jobnnn" folders of jobs they are working on. During the day there are lots of new job folders added. Every staff member does not want every job folder synced to them. Also it is annoying for every worker to be notified about every new "Jobnnn" folder and (mostly) press the "Apply" button to ignore the new folder for sync.
They would also want to use the same settings as (a) to make "quiet selective sync".
Then when they want to work a new job, they can select the appropriate folder to sync themselves.

c) Some staff have a group folder shared with them, but they are more junior staff (or whatever...) and actually they are not so much needing to have all the folders that are being created in their group. They really do not want to be bothered by the notifications about new folders, and they do not want or need the volume of stuff that is not really relevant to them. They can find and sync it later as they want/need.
They would set the confirmation limit to some low value of MB and check "Do not notify the user about new large folders".
That will again give them "quiet selective sync".

**Comment by scolebrook** [comment]
That is a great suggestion and very well explained and justified. Good job @phil-davis. It would meet several requests from our user base with similar use cases.

**Comment by MTRichards** [comment]
If I read this correctly, the change is largely a checkbox about notifications of new large folders?
Perhaps also a wording change, but the new feature is just that checbox?

**Comment by phil-davis** [comment]
Yes, the existing wording starts with the words "Ask confirmation..." - it would be confusing to then also have a checkbox for "Do not notify the user about new large folders". So I have suggested re-wording the current "Ask confirmation..." text (keeping exactly the same behaviour) and then just adding the new checkbox.
The back-end logical change is only to add a boolean setting and based on that setting the code decides whether to even bother notifying the user about the existence of a new large folder.

**Comment by MTRichards** [comment]
Ok, got it. Seems this would be a nice way to round this out for a lot of users. We can look at this for 2.1.

**Comment by phil-davis** [comment]
:+1:

**Comment by ckamm** [comment]
I agree that this seems like a good idea. We didn't manage to include it in 2.1, unfortunately.

**Comment by ogoffart** [comment]
I'm going to ask to @jancborchardt his opinion before adding a new option.
I also wondering what the wording should be.

**Comment by ogoffart** [comment]
@jancborchardt what do you say?

**Comment by ogoffart** [comment]
In my opinion the current way is not intrusive and does not require a new option.
