### ISSUE TITLE
unable to initialize a sync journal on Mac OS client 2.0

### ISSUE THREAD

**Issue by mishagithub** [owncloud/client#3684]
I'm getting this message: "unable to initialize a sync journal" when trying to sync using Mac OSX client version 2.0.

**Comment by guruz** [comment]
What kind of drive is that?
What kind of folder?
Does the folder exist?
Do you have permission to write there?

**Comment by phil-davis** [comment]
And is the drive full?

**Comment by mishagithub** [comment]
On Aug 27, 2015, at 2:19 AM, Markus Goetz <notifications@github.com> wrote:

> What kind of drive is that?
> 

I'm using ownCloud personal drive and on my laptop is a SSD drive. Does it answer your question?



> What kind of folder?
> 
Just a regular folder on my computer. It is size of 3.72Gb


> Does the folder exist?
> 
Yes


> Do you have permission to write there?
> 
> 

Yes

**Comment by mishagithub** [comment]
No the drive has plenty of free space on it

**Comment by mishagithub** [comment]
I have fixed the issue, thanks.

I have another question, how can I add more folders to already existing back up? maybe on the same level, not necessary sub folders.

Thanks,
Michael.

**Comment by dragotin** [comment]
Thanks for letting us know that the issue is fixed. For support, please consult the forum or the user mailinglist, not this bug tracking tool. Thanks!
