### ISSUE TITLE
[2.0.0] Remants of ownCloud1 ownCloud2 ... aliases

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3685]
A friend just kindly shared with me some huge folders and thankfully the 2.0.0 ownCloud client notified me and asked if I want to sync them. Sitting in a hotel room is not the time to sync about 100GB of data :)
I noticed that the red message text calls the new folders ownCloud6/SW and ownCloud6/LocalSW
![owncloud6](https://cloud.githubusercontent.com/assets/1535615/9525724/3b1d7c60-4d05-11e5-96d7-ac2b4dad015a.png)
I think we were trying to remove all user-side mention of these "alias" names. "ownCloud6" means nothing to me as a user. In the context where this message is displayed, it could just call the folders by their bare names, e.g. in this example "SW" and "LocalSW".

**Comment by Dianafg76** [comment]
I tested this issue, and now only appears the name of the folder followed by /
![screen shot 2015-09-14 at 13 36 39](https://cloud.githubusercontent.com/assets/12032058/9848896/aaffa218-5ae5-11e5-8386-b7c8cf9a51e2.png)

Closed
