### ISSUE TITLE
2.0.0 Client won't load in Mint 17.2 Cinnamon

### ISSUE THREAD

**Issue by mazate** [owncloud/client#3686]
I've been using the desktop client for quite some time without issue but I've been in process of changing my hosting provider for a couple of days so the client hasn't had any login info in it.  In any case, when the upgrade to 2.0 happened I noticed that the application is no longer in the tray in the lower right.  When booting up, I see it appear there for a split second and then disappears.  I'm not able to get it to open to configure it by using any means known to me.  I've double clicked the icon on my desktop, I've uninstalled and reinstalled and I just can't get it to respond.  If it install a prior version, it works fine.  (It was 1.5 so its too old to use but it does load.)  I would like to just install the prior version but the links to the prior sync client versions on the owncloud website don't actually take you to where you can download prior versions.  Any help on this is most appreciated.  I'm dead in the water until I can get this resolved.

**Comment by stonerl** [comment]
owncloud starts faster than the tray icon panel. You have to add a startup delay of at least 1 second.

**Comment by guruz** [comment]
For XFCE we loop 30 seconds to see if the tray becomes available.
Maybe that's a solution here too..

@mazate Can you confirm launching owncloud later will make it show the tray icon? 

@ogoffart @dragotin @jnweiger

**Comment by guruz** [comment]
> When booting up, I see it appear there for a split second and then disappears.

Maybe I misunderstood the issue.
Can you try to run it from a terminal?

For example in ```gdb``` with:
```
gdb owncloud
r --logfile -
``` 
maybe it is crashing.

Also use ```ps waux | grep owncloud``` to check if it is running

**Comment by stonerl** [comment]
@guruz I have had the same issue on Mint 17.2 owncloud is running. But as I stated in my last comment it is apparently starting too fast for the tray icon panel. The icon appears for a split second and then disappears. Adding a startup delay resolves this. I had to add this line to the autostart file:
```
X-GNOME-Autostart-Delay=1
```

**Comment by ogoffart** [comment]
What's the version of Qt?

**Comment by stonerl** [comment]
On the About page it says 4.8.6

**Comment by mazate** [comment]
Ok, strangely enough I restarted my computer (for an entirely different reason) and owncloud popped up and prompted me for the server login info.  It was very strange but its working fine now.  I did have the delay on during startup but it still wouldn't open.  All is ok now.  Very strange.

**Comment by guruz** [comment]
Thanks, I've added a timeout in the .desktop

@ogoffart @dragotin Maybe we need a solution in code too to re-try the tray availability in all desktop environments.. ?

**Comment by dragotin** [comment]
Thanks. Closing this.
