### ISSUE TITLE
2.0.0 where is the 'Modify Account' button?

### ISSUE THREAD

**Issue by tessus** [owncloud/client#3687]
The *Modify Account* button is missing in the 2.0.0 client.

Sidenote: Hiding the "Pause sync", "Remove folder", and "Open folder" makes the GUI less intuitive.

**Comment by phil-davis** [comment]
You can add more accounts using the "Add an Account" button in the General tab.
You can delete an account (still leaving the local files on the client) with the "Delete" button on the tab of the account.
I think "Modify Account" in 1.8.4 effectively did what delete+add does now.

**Comment by tessus** [comment]
I'm sorry, but this makes no sense to me. I have to delete and then re-add to modify the account?
This is illogical and bad UI design.

**Comment by danimo** [comment]
@tessus Which aspects of the account do you want to modify?

**Comment by ogoffart** [comment]
When one deletes the last account, the wizard automatically apears, so effectively doing the same thing as mofidy account.

**Comment by dragotin** [comment]
and if you change the password on the server the client will prompt you with a dialog to adjust it on the client. That was the most usecase for modify account in the past I guess. FYI @jancborchardt we talked about this...

**Comment by tessus** [comment]
I agree. if you change the password you get a prompt. That's fine. but I was still missing the modify button. There might be reasons to get rid of it, but I just didn't understand them.
In most cases you probably won't need it anyway, but it was just something I noticed right away.

**Comment by jancborchardt** [comment]
> In most cases you probably won't need it anyway, but it was just something I noticed right away.

Yeah, this is the case with most changes which remove something. Since we had a reason to remove the modify account button as mentioned above, is it ok for your that we just try out how it fares?

**Comment by danimo** [comment]
Let's try without, yes.
