### ISSUE TITLE
Don't auto-create local sync dir, except at setup time

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#3692]
### Steps

1. Create a folder "$HOME/subdir/ownCloud"
1. Configure the sync client to use that folder for syncing
1. Let it sync
1. Close the sync client
1. Rename "subdir" to "subdir2"
1. Open the sync client again

### Expected result
Sync client shows error that the target folder doesn't exist.

### Actual result
Sync client recreates "subdir/ownCloud" and redownloads everything.

The use case here I thought about here is that "subdir" could be a mount point, for example for an encrypted partition. If the partition isn't mounted at a given time, the sync client should fail instead of redownloading everything.

### Versions
Sync client 2.0.0

**Comment by ogoffart** [comment]
@jancborchardt do you agree it is better to show an error rather than re-create the directory.

If that's the case ->  https://github.com/owncloud/client/pull/3695

**Comment by dragotin** [comment]
I think back in the days we did that intentional to re-create a consistent sync state. But your point with the mount point is true. We should try to detect if it is still on the same device.

**Comment by guruz** [comment]
I also say let's just merge this..

@jancborchardt FYI

**Comment by jancborchardt** [comment]
Does this not mess with initial setup? Or when you removed the local folder?

**Comment by guruz** [comment]
@jancborchardt When you removed the local folder it should (and does?) error.
Initial setup - that's a good point though

**Comment by phil-davis** [comment]
During the Add Account dialog, if you use the chooser to select the Local Folder, then you have to create it anyway in the chooser to be able to choose it.
Same when adding a folder sync connection and using the chooser.
But if you accept the default (or in add folder sync connection you can type directly in the box without using the chooser) then it is possible that the target Local Folder does not exist yet. In those cases it needs to be automagically created.

**Comment by ogoffart** [comment]
This is _not_ about the initial setup or the folder configuration wizard. Those create the directories if they are not empty, and will always do.

The question is what happens when an already configured directory is suddently deleted.  
Currently, we recreate it and re-download everything.  But perhaps it would be better to show an error.  This is what @PVince81 wants and what https://github.com/owncloud/client/pull/3695 does.

**Comment by phil-davis** [comment]
@ogoffart  - Yes, I agree. I was just stating the few conditions where the code should create the Local Folder, so that it would be double-checked that those still work as expected. Given that it the case, as you say, all looks good to me here.

**Comment by Dianafg76** [comment]
I tested this issue, but If I follow the steps the Sync client recreates "subdir/ownCloud" and redownloads everything.
Sync client don't shows error that the target folder doesn't exist.

Desktop v ownCloud-2.0.2.2807-nightly20151020.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.2.0.10","versionstring":"8.2 RC2","edition":""}

**Comment by ogoffart** [comment]
that's strange.  I tested on linuw and windows with the 2.0.2-rc2 and it does show an error and do not sync everything.

**Comment by Dianafg76** [comment]
I tested this issue, and it does show an error and do not sync everything, so it is OK
Desktop v 2.0.2rc2 (build 5564)
