### ISSUE TITLE
Remove old-style shadow effect from app icon

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#3693]
@ogoffart @guruz can you let me know where the icon is stored? Then I will edit it and open a pull request.

**Comment by tomneedham** [comment]
<img width="163" alt="screen shot 2015-08-28 at 14 13 43" src="https://cloud.githubusercontent.com/assets/660805/9546007/341bbf8c-4d8f-11e5-9fa3-e936121683c2.png">

**Comment by ogoffart** [comment]
The png icons are in the theme/colored directory.  But i don't know where the original svg is.

**Comment by ogoffart** [comment]
Apparently, they were made by Achim Geissel

**Comment by jancborchardt** [comment]
Yeah, I’ll mail him.

**Comment by jancborchardt** [comment]
Or basically just do it manually. Which sizes are necessary?

**Comment by ogoffart** [comment]
all the size in that folders.

**Comment by danimo** [comment]
@jancborchardt I'm mailing with achim already. Is he aware what this issue is about?

**Comment by jancborchardt** [comment]
@danimo I guess if he takes a look at it or the icon (see @tomneedham's screenshot) then he will know what is meant, yes.

**Comment by danimo** [comment]
Testable with tomorrows' nightly builds.

**Comment by jancborchardt** [comment]
Great, thanks!

**Comment by Dianafg76** [comment]
I tested this issue, and now no shading effect appears from app icon
Desktop v ownCloud Testpilot Edition-2.0.2.2715-nightly20150915.pkg 
Closed

**Comment by jancborchardt** [comment]
Awesome, thanks to Achim and @danimo :)
