### ISSUE TITLE
Damaged folder names prevent completion of client 'discovering' step

### ISSUE THREAD

**Issue by mmccarn** [owncloud/client#3694]
<b>Proposed Enhancement</b>
If the sync client encounters an internal server error during the 'discovering' phase:
* (optional) close and reopen the connection and re-try the file or folder
* add the offending file or folder to the exclusions list
* generate a desktop notification (if desktop notifications are enabled)
* (optional) automatically expose the sync client exclusion list in order to prompt the user to resolve the problem
* (optional) set the sync client status icon to something indicating that there are unresolved automatic exclusions in place.  To be useful, this option would require UI changes to let the user confirm or retry the automatic exclusions, which would require tracking if an exclusion had been entered manually or generated automatically.

<b>History</b>
I am using Owncloud and the desktop sync client to sync my network users' 'Home' folder with their laptop computers.

Usually, everything works perfectly for both Windows & Mac users.  I have one Macbook user that is causing me significant grief.

Setting up this one user to sync the entire home folder fails during the 'discovering' phase, giving an 'internal server error'.  After a brief pause, the client returns to 'discovering'. The client never gets past 'discovering'.

By using exclusions to sync only a few sub-directories at a time I have discovered that the problem is caused by damaged folder names on my network server (windows 2003 mounted to owncloud using files_external).

<b>More Information</b>
The folders I've found and fixed so far all end in a space or some other non-printing character.

For example, one such folder is named  "ACC "

From a windows CMD prompt:
*  <b>Dir ACC[enter]</b>  returns 'file not found'
*  <b>Dir ACC[tab]</b> auto expands to <b>Dir "ACC "</b>, but pressing [enter] still returns 'file not found'
* The folder opens without problems in Windows Explorer or OS X Finder
* The folder name is corrected if I copy the entire folder to another location using Finder (mac) but gives the error 'Could not find this item' in Windows Explorer (Win 7 pro).
* I am unable to rename or delete the damaged folders from a WIndows CMD prompt, Windows Explorer, or OS X Finder.
* I <b>am</b> able to manipulate these folder names in a cygwin terminal window.
* I have not tried renaming the folders from a terminal shell on an OS X system, but I suspect that would work.

As I locate the damaged folders one-by-one I use cygwin from a windows box to rename them, after which they can be removed from the user's list of sync client exclusions and the sync will proceed (until it encounters the next damaged folder name).

**Comment by mmccarn** [comment]
I've discovered that folder names beginning with a space also fail, eg " 2010".

(For what it's worth, many of the damaged folders I'm seeing are related to activity from 2010, which makes me think that these problems may have been created by a bug in an old version of OS X)

**Comment by ogoffart** [comment]
What version of the client and the server are you using?

(There at least a fix about that in 2.0.0)

**Comment by mmccarn** [comment]
I was seeing the same behavior in 2.0.0 (I don't have that laptop any more to confirm the build number)  as well as 1.8.4 (build 2531).

The server is 8.1.1 (stable) running on Ubuntu 14.04

**Comment by ogoffart** [comment]
Ok, then we would need the log from the client.
https://doc.owncloud.org/desktop/2.0/troubleshooting.html#log-files

**Comment by mmccarn** [comment]
I created number of inappropriate files and folders in a samba folder on my network server.  The resulting folder looks like this:
```
$ find .


./ Test
./ Test/test.txt
./ Test 4.txt
./Test 2
./Test 2 /test2.txt
./Test 3 .txt
./Test5.txt
./Test6
./Test6/Test6.txt
```

From my mac, running owncloud client  2.0.1 (build 2694) my log file looks like this:
https://www.dropbox.com/s/3u7cs2qx8bm34dv/owncloud_client_3694_logfiles.txt?dl=0

Important:
My client is configured to sync with two accounts - cloud and vcloud.  vcloud is the account that contains the damanged file and folder names, and is configured to only sync one folder from within my "_Home"

**Comment by mmccarn** [comment]
Here's another logfile:
https://www.dropbox.com/s/nw1cuuu135sz2h4/owncloud_client_3694_win_log.txt?dl=0

Client:
Windows 7 64 bit Version 2.0.1 (build 5446)
The only folder selected for sync is "_Home/_Owncloud", containing the files & folders listed above

**Comment by mmccarn** [comment]
I believe this issue is related to this one:
https://github.com/owncloud/core/issues/17350
"Own cloud doesn't display files with names with spaces at the end #17350"

**Comment by dragotin** [comment]
sorry, but I think an **internal server error** is a reason to really hard break and stop. All kinds of problems can happen in this case and that has to be sorted by the server admin.

**Comment by mmccarn** [comment]
>
> ...an **internal server error** is a reason to really hard break and stop.
> 

I see your point, but **hard break and stop** is exactly what does NOT happen - the internal server error is repeated over and over and over as the damaged folder is re-scanned by the client every time the sync process restarts.
