### ISSUE TITLE
[2.0.1] [Sharing Link] Error coder: 400 when you write the password

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3696]
### Steps to reproduce
1. Open your ownCloud web Client
2. Create a new folder, called a
3. Access to the folder a
4. Right click to the folder
5. Select the option "Share with oC"
6. Check the option "Password protect"
7. Write the Password
8. Press Enter

### Expected behaviour
You must be able to share with password

### Actual behaviour
Appears the error 400 
![screen shot 2015-08-28 at 15 54 02](https://cloud.githubusercontent.com/assets/12032058/9547806/25d7f996-4d9d-11e5-86c9-05db3f0b034f.png)
Log:
´´´
08-28 15:43:18:273 0x7fe5e065bbb0 OCC::OcsShareJob::finished: Reply to "PUT"  QUrl( "https://docker.oc.solidgear.es:52017/ocs/v1.php/apps/files_sharing/api/v1/shares/6?format=json" )  (QPair("password","dfd")) has unexpected status code: 400 "{"ocs":{"meta":{"status":"failure","statuscode":400,"message":"Wrong or no update parameter given"},"data":[]}}"
´´´

### Server configuration
Desktop v ownCloud-2.0.1.2669-nightly20150826.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.2.0.4","versionstring":"8.2 pre alpha","edition":"Enterprise"}

**Comment by rullzer** [comment]
Seems that this is caused by a bug in core at the moment (https://github.com/owncloud/core/issues/18588)

Lets investigate further once that is fixed.

**Comment by rullzer** [comment]
@Dianafg76 could you retest. Server is fixed. And it seems to be working here.

**Comment by Dianafg76** [comment]
Is working OK.
Closed
