### ISSUE TITLE
[XFCE 4.12] [2.0.0] [Qt 5.4.x] tray icon goes missing

### ISSUE THREAD

**Issue by davleema** [owncloud/client#3697]
### Steps to reproduce

1. start ownclient 2.0.0 on a Slackware 14.1 x64 system

2. everything seems OK

3. after reboot, or logout/login, OC client system icon is gone 

After my problem in this forum post: https://forum.owncloud.org/viewtopic.php?f=14&t=30070, 
I now have another problem. The owncloud client system tray icon goes missing.
The owncloud process starts and appears to be running, but the icon is no longer visible.
It was visible initially, but after a reboot, it's gone, and stays gone.
This is with the OC-client, build using QT 5.4.1.
Is this a bug in QT 5.4.x ? My desktop env. is XFCE 4.12.

PS: When i revert to the OC-client 2.0 which was build using QT 4.8.x, the tray icon works as expected.

### Expected behaviour
owncloud client tray icon should stay visible in the system tray 

### Actual behaviour
owncloud client process appears to be running, but icon is not visible. Also no notifications. 

### Server configuration
**Operating system**:
Linux x64 Slackware

**Web server:**
Apache 2.4.16

**Database:**
MariaDB 5.5.45

**PHP version:**
5.5.24

**ownCloud version:** (see ownCloud admin page)
8.1.1

**Updated from an older ownCloud or fresh install:**
updated

### Client configuration
**Browser:**
Firefox 40.0

**Operating system:**
Slackware 14.1 x64

**Comment by guruz** [comment]
(I'm not a linux user so can't say much, but search around a bit in this issue tracker..)

**Comment by stonerl** [comment]
@davleema which Qt5-Version do you use exactly?

**Comment by stonerl** [comment]
@davleema Sorry just saw the you use 5.4.1. I'm using this Version on my Fedora 22 machine and I get the Stray icon. As far as I can recall there was a bug in a Version prior to this one that prevented the icon from appearing.

**Comment by stonerl** [comment]
#2511

**Comment by stonerl** [comment]
maybe related to this  autostart issue #3686

**Comment by davleema** [comment]
After upgrading to Qt 5.4.2 (and qtkeychain 0.5.0) the icon is back, and stays visble. So far, so good.
But now I'm facing again the original problem ("Unknown error" when trying to connect with some OC server), but I will open another issue for that one.

**Comment by dragotin** [comment]
ok, thanks.
