### ISSUE TITLE
Could not find mount point, can't keep encryption keys 

### ISSUE THREAD

**Issue by skillz-xx** [owncloud/client#3698]
hello

I am getting this error in my log files from a specific user, constantly when the user is editing files in a shared folder...

"app":"no app in context","message":"Could not find mount point, can't keep encryption keys","level":3,"time":"2015-08-28T18:50:16+00:00","method":"PUT","url":"\/remote.php\/webdav\

I cant figure out whats the problem..

I have not enabled server side encryption, but the encryption app is active. I have tried disabling the app, but no change

please help!

thx
dan

ps. I use the 8.1 version on a debian wheezy and the latest version of the client

**Comment by guruz** [comment]
This sounds more like a server issue.
Can you create an issue here: https://github.com/owncloud/core and link to the issue here so we can close it?

CC @schiesbn

**Comment by skillz-xx** [comment]
ok will do
