### ISSUE TITLE
[2.0.0][Windows][Theme] Could not use overrideServerUrl in own theme class

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/client#3699]
Since Version 2.0.0 I can not use **overrideServerUrl** in my own theme class. 

This is the result now:

![problem](https://cloud.githubusercontent.com/assets/9192953/9556067/23426722-4dd2-11e5-95c1-be69e14675ea.png)

It ignores my value completely. Is there something changed? **All other values are working like before.**

**Comment by pierrejochem** [comment]
Wow, perfect! Will try it right now :-)

**Comment by pierrejochem** [comment]
@guruz  && @ogoffart : You are doing a creat job! Works like a champ!

**Comment by guruz** [comment]
@pierrejochem Good to hear it works :-)

FYI @rperezb @dragotin

**Comment by guruz** [comment]
FYI @michaelstingl

**Comment by rperezb** [comment]
great to hear that it works!

@guruz is this the changed needed for branded clients?
