### ISSUE TITLE
Owncloud Client 2.0.0. on Windows does not allow not to produce share links without a password in the Win-Context menu - the options are greyed out

### ISSUE THREAD

**Issue by Niederfuchs** [owncloud/client#3703]
Windows Owncloud Sync Client Version 2.0.0.
Windows 10
Owncloud 8.1.1. (updated) with individual theme
Apache 2.4.10
PHP 5.6.12

# Steps to reproduce:
Open the Windows Context Menu on a file stored in the cloud - click the Share via Owncloud button.
The following boxes  are ticked inside the Share Section of the Administration Menu of the Owncloud Instance:
Share API Use allowed
Allow users to share content via links
Public Uploads allowed
Re-Shares allowed
In the Federated-Cloud-Sharing Menu both optins are ticked

Unticked are the following boxes:
Enforce Password
Allow Users to send Email for shared files
Set date for expiration
Limit users to share inside their group
Allow users to send emails for shared files to other users
Exclude groups from shares

# Expected Behaviour:
A fully functional Share Menu. With all options selectable...

# Actual Behaviour:
The "Public Shares require a Password" box is preselected and cannot be unticked. As well as the set a date section is unticked and cannot be ticked. You are required to set a password immedately.

**Comment by phil-davis** [comment]
Is the server set to enforce having a password on link shares?

**Comment by Niederfuchs** [comment]
No.

**Comment by rullzer** [comment]
This is known and fixed in the next releases of the server (see: https://github.com/owncloud/core/pull/18271 and https://github.com/owncloud/core/pull/18274).

Fix for now is to toggle all the settings on the webinterface... so enabled -> disabled -> enabled (and vice versa). So that we do not rely on the default.

**Comment by Niederfuchs** [comment]
Supercool your fix worked for me...! Thanks a bunch!

Sönke

Roeland Douma schrieb:
