### ISSUE TITLE
[2.0.0] Jump to folder in folderlist when "new folder too big" (in red) is shown

### ISSUE THREAD

**Issue by msrex** [owncloud/client#3704]
When you get the message "Folder was not added - folder too big" is shown in the account view it does not allow me to click on the folder and show it in the select-list above.

It would be great if by clicking on the folder name in the red text I could jump to that folder in the selection box above.

**Comment by dragotin** [comment]
Code for this in branch https://github.com/owncloud/client/tree/clickable_undecided

**Comment by Dianafg76** [comment]
I tested this issue is working OK, Clicking on the folder name in red text now goes to that folder in the previous selection .
Desktop v ownCloud-2.1.0.2855-nightly20151105.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

Closed
