### ISSUE TITLE
Directories misconfigured in 2.0.0 client

### ISSUE THREAD

**Issue by Ryux** [owncloud/client#3707]
Since the migration with the 2.0.0 version, some directories are not reachable.

The configuration file

[data__SLASH__commun]
localPath=/data/documents/commun
targetPath=documents/commun
backend=owncloud
connection=ownCloud

The Owncloud client seems to want synchronize the / (root) directory but does not find the synchronization journal

Some idea about this problem ?

Thanks

Ryu

**Comment by Ryux** [comment]
In the owncloud.cfg config file there is : 

[Accounts]
0\Folders\data\commun\ignoreHiddenFiles=true
0\Folders\data\commun\localPath=/data/documents/commun
0\Folders\data\commun\paused=false
0\Folders\data\commun\targetPath=documents/commun

**Comment by ogoffart** [comment]
this looks good to me.  What exactly is going wrong? It failed to convert the settings from the old client?

**Comment by Ryux** [comment]
I was on the 1.8.4. version and all was ok.
I updated to the 2.0.0 version and in the same time qt-base to 5.5. But this version is buggy and owncloud crash at startup. (See https://github.com/owncloud/client/issues/3672)
So, my client crashed many times before I downgraded to the qt-base 5.4.
With this version, I could run owncloud but now I have 2 of my sync repository which a

**Comment by ogoffart** [comment]
It's the first time i see such a thing.  

So there are two folders that did not got converted properly? 

I don't know how we can debug this. Do you still have he config file from before?
do you have files in ~.local/share/data/ownCloud/folders/  ?

**Comment by Ryux** [comment]
Yes, I have

[ryu@ryu ~]$ ll ~/.local/share/data/ownCloud/folders/
total 40
-rw-rw-r--. 1 ryu ryu 120 27 sept.  2013 data__SLASH__commun
-rw-rw-r--. 1 ryu ryu 125 27 sept.  2013 documents__SLASH__ryu
-rw-rw-r--. 1 ryu ryu  98 27 sept.  2013 musique
-rw-rw-r--. 1 ryu ryu  87 27 déc.   2014 photos
-rw-rw-r--. 1 ryu ryu  87 18 nov.   2014 videos

And the configuration file for the bad repositories :
[ryu@ryu ~]$ cat ~/.local/share/data/ownCloud/folders/data__SLASH__commun 
[data__SLASH__commun]
localPath=/data/documents/commun
targetPath=documents/commun
backend=owncloud
connection=ownCloud
[ryu@ryu ~]$ cat ~/.local/share/data/ownCloud/folders/documents__SLASH__ryu 
[documents__SLASH__ryu]
localPath=/data/documents/ryu
targetPath=documents/ryu
backend=owncloud
connection=ownCloud

And the full accounts configuration in owncloud.cfg
[Accounts]
0\Folders\data\commun\ignoreHiddenFiles=true
0\Folders\data\commun\localPath=/data/documents/commun
0\Folders\data\commun\paused=false
0\Folders\data\commun\targetPath=documents/commun
0\Folders\documents\ryu\ignoreHiddenFiles=true
0\Folders\documents\ryu\localPath=/data/documents/ryu
0\Folders\documents\ryu\paused=false
0\Folders\documents\ryu\targetPath=documents/ryu
0\Folders\musique\ignoreHiddenFiles=true
0\Folders\musique\localPath=/data/musiques/albums
0\Folders\musique\paused=false
0\Folders\musique\targetPath=musique
0\Folders\photos\ignoreHiddenFiles=true
0\Folders\photos\localPath=/data/photos
0\Folders\photos\paused=false
0\Folders\photos\targetPath=photos
0\Folders\videos\ignoreHiddenFiles=true
0\Folders\videos\localPath=/data/videos
0\Folders\videos\paused=false
0\Folders\videos\targetPath=videos

**Comment by ogoffart** [comment]
Does the  `__SLASH__`  means anything?

**Comment by ogoffart** [comment]
That __SLASH__ Is some escape pattern, that might be the reason.

**Comment by Ryux** [comment]
But the migrations seems to be correct. The owncloud.cfg is ok.
The files in the folder directory are no more used, no ?

**Comment by dragotin** [comment]
the __SLASH__ tag was used in the old configs to mask slashes.

**Comment by Ryux** [comment]
Maybe is it the 0\Folders\\**data\commun** path key which is invalid. 
I can try with 0\Folders\\**data__SLASH__commun** instead

**Comment by Ryux** [comment]
I confirm

I changed my repository name with : 
0\Folders\data__SLASH__commun\ignoreHiddenFiles=true
0\Folders\data__SLASH__commun\localPath=/data/documents/commun
0\Folders\data__SLASH__commun\paused=false
0\Folders\data__SLASH__commun\targetPath=documents/commun

and all is ok.

So, I guess that the migration replaces the __SLASH__ with / but it fails to read the configuration correctly.

**Comment by ogoffart** [comment]
The client 2.0.0 does not support folders with slashes in the aliasThe client 2.0.0 does not support folders with slashes in the alias.

This should now be fixed with the commit d853b4f, which will be in 2.0.2.

However i'm afraid that your config file is now corrupred and you should replace "data\commun" with "data__SLASH__commun" manyally everywhere.

**Comment by Ryux** [comment]
Good news !
No problem for my config file, it is already done.
Thanks for your work
