### ISSUE TITLE
[Ubuntu] apt-get build-depend owncloud-client conflicts with owncloud-client

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#3710]
according to: https://doc.owncloud.org/desktop/2.0/building.html
we do:

<pre>
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.04/ /' >> /etc/apt/sources.list.d/owncloud-client.list"
sudo apt-get update
sudo apt-get install owncloud-client
sudo apt-get build-dept owncloud-client
</pre>

we get an error message

<pre>
The following packages have unmet dependencies:
 libocsync-dev : Depends: libocsync0 (= 0.91.4-1) but it is not going to be installed
</pre>

workaround:

<pre>
apt-get purge owncloud-client
</pre>

Now we can install the build dependencies.

**Comment by jnweiger** [comment]
@monikae fyi

**Comment by dragotin** [comment]
what does ```apt-get purge``` do?

**Comment by jnweiger** [comment]
apt-get purge removes owncloud-client -- then libocsync0 can be installed via build-dep without any conflicts.

A brute force solution could be to add a 
```Build-Depends: !owncloud-client```
to owncloud-client. Horrible.

**Comment by ogoffart** [comment]
Closing old issue.
