### ISSUE TITLE
[2.0.1] The button "Add folder to sync" 

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3714]
### Steps to reproduce
1. Install the version 2.0.0, so that it includes Multiaccount
2. Introduce the Server Address
3. Click on Next
4. Introduce the Username and the Password
5. Click on Next
6. Select the option "Choose what to sync"
7. Unselect one folder (e.g. Documents)
![screen shot 2015-08-31 at 17 03 01](https://cloud.githubusercontent.com/assets/12032058/9581885/5093593e-5002-11e5-829f-5f1bef6e1f4d.png)

8. Click on OK
9. Click on Connect...
10. Click on Finnish
11. Right click on the Icon oC
12. Click in Settings...

### Expected behaviour
The button add new folder should be enable (you have not selected to have in sync de whole account), 

### Actual behaviour
You can't add another sync folder,  because the button is disable
![screen shot 2015-08-31 at 17 03 26](https://cloud.githubusercontent.com/assets/12032058/9581985/fa514120-5002-11e5-8412-e5764adb11e3.png)

### Note
However, If you follow the steps:
0. Having one folder synced on the desktop client
1. You remove folder.
2. Click on Stop sync
3. Click on "Add Folder Sync"
4. Click "Choose"
5. Create a new folder (eg. call www)
6. Click Create
7. Click Open
8. Click Continue
9. Select one Folder (e.g Documents)
10. Click Continue
11. Click Add Folder
![screen shot 2015-08-31 at 17 18 42](https://cloud.githubusercontent.com/assets/12032058/9582251/796227bc-5004-11e5-85e0-181e10957b67.png)

### Server configuration
Desktops Version 2.0.1-nightly20150826 (build 2669)
Server v{"installed":true,"maintenance":false,"version":"8.1.1.2","versionstring":"8.1.1 RC1","edition":"Enterprise"}

**Comment by tflidd** [comment]
There is already a small discussion about this: https://github.com/owncloud/client/issues/3645

**Comment by dragotin** [comment]
yes, lets continue the discussion there. Its teh same root cause.
