### ISSUE TITLE
sync client shows %1 instead of download limit

### ISSUE THREAD

**Issue by v1r0x** [owncloud/client#3715]
A picture is worth a thousand words ;)
![oc_ 1](https://cloud.githubusercontent.com/assets/9248714/9590876/b1fdd156-5037-11e5-940f-716bc0ad8ec2.png)

**Comment by pierrejochem** [comment]
https://github.com/owncloud/client/issues/3717

**Comment by pierrejochem** [comment]
;-)

**Comment by ckamm** [comment]
Thanks, let's move it to #3717, since that also has an extra suggestion.
