### ISSUE TITLE
[2.0.0] [Windows] Client does not resume after hibernation when sync folder is on network drive

### ISSUE THREAD

**Issue by raimund-schluessler** [owncloud/client#3716]
### Expected behaviour
Client should resume normal operation after the PC wakes from hibernation (suspend to disk, S4)

### Actual behaviour
The client does not resume normal operation, clicking the tray icon does not show the menu and the client does not show up. Client is shown as inactive in the task manager. After killing the client via task manager and restarting it, everything is back to normal.

### Steps to reproduce
1. Use windows (8, 8.1, 10) and install client (affected since version 1.7 and earlier I guess, still persistent in 2.0.0)
2. Setup client and sync, hibernate the PC
3. Client does not sync

It probably is also related to the fact that I sync to a network drive which might not be connected directly after awaking from S4?

### Server configuration
Operating system:
Debian Jessie 8.1/8.0/7.4

Web server: 
Apache 2.4/2.2

Database:
MySQL

PHP version:
5.6 I guess

ownCloud version:
8.1.1 (persists since 7.0 and earlier

Storage backend:
Directly mounted HDDs at the server side, network drive on client side

### Client configuration
Client version: 2.0.0

Operating system: Windows 8.1/8.0

OS language: German

Installation path of client: c:\Program Files (x86)\ownCloud\

### Logs

1. Client Log:
After resuming from hibernation
https://gist.github.com/raimund-schluessler/dc1b0cf8917b77e99e2a

2. Web server error log:
Will hand in later

3. ownCloud log (data/owncloud.log):
Will hand in later

**Comment by guruz** [comment]
> It probably is also related to the fact that I sync to a network drive which might not be connected directly after awaking from S4?

Do you want to try to either remove the sync relation on the network drive and setup a sync on a normal drive (with a subset of your files) and check if that works?

**Comment by raimund-schluessler** [comment]
I removed all sync relations and setup a sync to only a local drive. Syncing to this local drive seems to work without problems and the client works as expected after hibernation. Sadly, this is not an option for me.

**Comment by ogoffart** [comment]
But normaly it should start syncing again after 30 seocnds or so

**Comment by marlemion** [comment]
Same here on Linux (Plasma 5).

**Comment by dragotin** [comment]
Happens here with 2.1.0 pre version on linux. Relevant log:
```
12-05 18:54:25:105 1590 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
12-05 18:54:25:106 1590 OCC::AbstractNetworkJob::setTimeout: void OCC::AbstractNetworkJob::setTimeout(qint64) 27000
12-05 18:54:25:107 1590 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://xxy.net/owncloud" + "status.php"
12-05 18:54:25:108 1590 OCC::AbstractNetworkJob::setTimeout: void OCC::AbstractNetworkJob::setTimeout(qint64) 27000
12-05 18:54:25:109 1590 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "http://192.168.178.75/ocm" + "status.php"
12-05 18:54:25:115 1590 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(HostNotFoundError) "Host xxy.net not found" QVariant(Invalid)
12-05 18:54:25:116 1590 OCC::ConnectionValidator::slotNoStatusFound: void OCC::ConnectionValidator::slotNoStatusFound(QNetworkReply*) QNetworkReply::NetworkError(HostNotFoundError) "Host xxy.net not found"
12-05 18:54:25:117 1590 OCC::AccountSettings::showConnectionLabel: "Keine Verbindung zu ownCloud auf <a href=\"https://xxy.net/owncloud\">https://xxy.net/owncloud</a>\nHost xxy.net not found"
12-05 18:54:25:119 1590 OCC::FolderMan::slotAccountStateChanged: Account "kf@xxy.net" disconnected, terminating or descheduling sync folders
```
nslookup resolves the host properly.

**Comment by dragotin** [comment]
does not seem to be platform specific.

**Comment by guruz** [comment]
@raimund-schluessler Can you confirm this on Windows with 2.1? We have some Qt patches in there that influence this.

@marlemion @dragotin I blame the lacking Qt patches on Linux. With Qt 5.6 beta this should work?

**Comment by marlemion** [comment]
Well, I am on arch with qt 5.5. Since the upgrade to plasma 5.5 it is gone apparently.
