### ISSUE TITLE
[Translation] German translation in the "general config page" contains %1

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/client#3717]
![2015-09-01_11-14-46](https://cloud.githubusercontent.com/assets/9192953/9600322/d5d86646-509a-11e5-98c3-8fac3359b4f1.png)

**Comment by pierrejochem** [comment]
**Another thing:** My Proposal for "Forgeschritten" would be additionally "Erweitert"

**Comment by ogoffart** [comment]
The `MB` there can be translated  `MB heryntergeladen werden.`
And that part removed from the beginning.

**Comment by pierrejochem** [comment]
You mean "heruntergeladen" :stuck_out_tongue:

**Comment by guruz** [comment]
@DeepDiver1975 
"Your join request for the German (de) language has been submitted. You will receive a notification upon acceptance or denial."

**Comment by danimo** [comment]
I switched it to `Bestätigung für übergroße Ordner erfragen für Ordner größer als`

**Comment by LukeOwncloud** [comment]
Twice "Ordner". Equivalent for "download" missing.

Also @phil-davis's argument seems reasonable:
https://github.com/owncloud/client/issues/3814#issuecomment-139531305

How about: Make option simply:
`Large folder size: xxx MB`
Then use some tool tip or another line explaining what is special about large folders.

**Comment by Dianafg76** [comment]
@pierrejochem you could try this version: http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.2713-nightly20150914.pkg.
Thanks

**Comment by pierrejochem** [comment]
@Dianafg76: Yes, will do that as soon as I'm back from a business trip or give me a link for the windows version ;-)

**Comment by phil-davis** [comment]
Daily builds for all platforms are at http://download.owncloud.com/desktop/daily/

**Comment by Dianafg76** [comment]
@pierrejochem Sorry, for Windows: http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.5463-nightly20150915-setup.exe

**Comment by pierrejochem** [comment]
![owncloud_2015-09-18_08-46-27](https://cloud.githubusercontent.com/assets/9192953/9953519/c3551556-5de1-11e5-9eb6-ded28cf3beaa.png)

**Comment by danimo** [comment]
Works for me:

![image](https://cloud.githubusercontent.com/assets/1315934/10130634/7896c4ba-65ca-11e5-808f-a0dfb4fdb3da.png)

**Comment by Dianafg76** [comment]
@pierrejochem you could try this version: http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.5499-nightly20150928-setup.exe
Thanks

**Comment by rperezb** [comment]
@pierrejochem if this didn't work for you, please reopen
