### ISSUE TITLE
2.0.2 Having the server url fixed, if you delete the account you can't add the new account

### ISSUE THREAD

**Issue by rperezb** [owncloud/client#3718]
### Steps to reproduce
1. Install the version 2.0.2 with the server url hardcoded
2. Wait to Sync
3. Right click to icon oC
4. Click on Setting...
5. Click on Delete
6. Click on Remove connection
7. The server url is not requested (as expected)
8. Don't Introduce the Username and the Password
9. Click on the red button to cancel the view for entering the id and password
![screen shot 2015-09-01 at 12 27 13](https://cloud.githubusercontent.com/assets/12032058/9601952/0d1de4dc-50a5-11e5-9222-823ff8c61b4d.png)

### Expected behaviour
You should be able to add an account

### Actual behaviour
You have no option of adding an account
![screen shot 2015-09-01 at 12 31 00](https://cloud.githubusercontent.com/assets/12032058/9601998/6611f59c-50a5-11e5-8657-f5f0f1fc2ca3.png)

### Server configuration
Desktop Version 2.0.2-nightly20150831 (build 2688).
Server v {"installed":true,"maintenance":false,"version":"8.0.2.0","versionstring":"8.0.2","edition":"Enterprise"}

**Comment by ckamm** [comment]
I think the fix 7bfbc21 from #3721 might very well have fixed this too, will test.

**Comment by ckamm** [comment]
I can't reproduce it with the fix applied.

**Comment by Dianafg76** [comment]
I tried this, and now when I removed the account and if I go to the general option I see the Add an account button.
![screen shot 2015-09-18 at 10 44 35](https://cloud.githubusercontent.com/assets/12032058/9955573/4ed7da72-5df2-11e5-84d3-e2db52cf98cb.png)

Closed
