### ISSUE TITLE
[OS X] 2.0.2 Having a client with the server url hardcoded, the Activity Option is selected all the time

### ISSUE THREAD

**Issue by rperezb** [owncloud/client#3719]
### Steps to reproduce
1. Install the version 2.0.2 with the server url hardcoded
2. Wait to Sync
3. Right click to icon oC
4. Click on Setting...
5. Click on Delete
6. Click on Remove connection
7. The server url is not asked, as expected
8. Introduce the Username and the Password
9. Click on Next
10. Click on Connect...
11. Click on Finish
12. Right click on the icon oc
13. Click on Settings...
14. The Activity Option is selected
![screen shot 2015-09-01 at 10 55 28](https://cloud.githubusercontent.com/assets/12032058/9600004/91ce5638-5098-11e5-96a6-ca6ba83bd51f.png)
15. Click on the User account or General option, and the option activity has not been deselected
![screen shot 2015-09-01 at 10 31 42](https://cloud.githubusercontent.com/assets/12032058/9600115/6413a5b2-5099-11e5-8b58-27a31083b618.png)
![screen shot 2015-09-01 at 10 31 51](https://cloud.githubusercontent.com/assets/12032058/9600126/70366942-5099-11e5-9274-9e5dd402437b.png)

Note: If you click on Activity and after that you click in any of the other options, everything looks good
![screen shot 2015-09-01 at 11 37 02](https://cloud.githubusercontent.com/assets/12032058/9600864/e0d1472c-509d-11e5-8463-25e86e8d5b49.png)

### Server configuration
Desktop Version 2.0.2-nightly20150831 (build 2688).
Server v {"installed":true,"maintenance":false,"version":"8.0.2.0","versionstring":"8.0.2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
I tested this issue and is working OK
Desktop v 2.1.0 (build 2883)
Server v {"installed":true,"maintenance":false,"version":"8.2.0.12","versionstring":"8.2.0","edition":"Enterprise"}

Closed
