### ISSUE TITLE
Desktop sync client 2.0.0 not able to connect to oC 8.1.1 via Shibboleth

### ISSUE THREAD

**Issue by pako81** [owncloud/client#3724]
### Steps to reproduce
1. Trying to connect the Desktop sync client 2.0.0 to oC 8.1.1 via Shibboleth

### Expected behaviour
Desktop sync client should be able to connect and sync

### Actual behaviour
Desktop sync client is not able to connect and is reporting a "Service Unavailable" error message. After selecting "Skip configuring folders" and adding the same folder afterward, the
client starts syncing correctly until the next reboot of the user's system. Then the client is trying to sync again but after a while it will break the process.

### Server configuration
**Operating system**:
RHEL 6

**PHP version:**
5.4

**ownCloud version:** (see ownCloud admin page)
8.1.1

### Logs

owncloud.log, config files and relevant screenshots from Customer in S3\support\github-issues\client\3724

Maybe related to owncloud/client#3593 and owncloud/user_shibboleth#82?

**Comment by dragotin** [comment]
We tested 2.0.0 with Shibboleth and it worked. It's quite likely that this is a misconfiguration with this installation. @MorrisJobke can you help with that? @danimo FYI

**Comment by MorrisJobke** [comment]
> It's quite likely that this is a misconfiguration with this installation. @MorrisJobke can you help with that?

Disclaimer: I'm not really a Shibboleth expert.

@pako81 Can you check the webservers access logs if there is something useful in there. Maybe we can then find out if it is a shibboleth or an owncloud problem. Also the owncloud log is of interest here.

**Comment by pako81** [comment]
Just checked the webserver access log files but it seems there is nothing relevant in there..could be I am missing something anyway..
The apache config and log files and a new owncloud.log file can be found in S3\support\github-issues\client\3724\latest files as well as a short video recorded by the Customer while reproducing the issue.

**Comment by pako81** [comment]
Any news on this?

**Comment by danimo** [comment]
@pako81 This is fixed with https://github.com/owncloud/user_shibboleth/issues/82, i.e. it will only work with 8.1.4, as the fixed missed the 8.1.3 release.

@Dianafg76 This wa finally fixed in stable81. If possible, retest with a current stable81.

**Comment by pako81** [comment]
Ok, many thanks!

**Comment by Dianafg76** [comment]
@danimo I tested with stable81, and I and it's the same
![screen shot 2015-09-16 at 13 11 42](https://cloud.githubusercontent.com/assets/12032058/9903198/b24496c4-5c74-11e5-893b-e5ba2aba2464.png)

https://github.com/owncloud/core/commit/c736f5dcc4c47c1eb2ab443c23bb9d47e61e3c34

**Comment by Dianafg76** [comment]
@danimo I tested this issue with stable81, and with working OK
Dektop v ownCloud-2.0.2.2740-nightly20150924.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
Waiting for server version 8.1.4 (Octubre 27)

**Comment by rperezb** [comment]
There is no need to have this open since it´s been tested on stable8.1 and it works.

**Comment by rperezb** [comment]
Rechecked again using:

ownCloud Enterprise Edition 8.1.3 (daily) Build:2015-10-02T03:14:59+00:00 4a1246fa291974702b0bfb05ea973cd46bed48cd	
Desktop version 2.0.1 (production one) 
working fine
cc @cmonteroluque

**Comment by cmonteroluque** [comment]
@rperezb @Dianafg76 thank you!
