### ISSUE TITLE
ownCloud client wrongly forces password on public link sharing 

### ISSUE THREAD

**Issue by BenS89** [owncloud/client#3727]
Environment: 
ownCloud Server 8.1.1
ownCloud Client 2.0.1 on Windows 7

In the ownCloud admin-panel, "force password protection" is disabled

Steps to reproduce:
1. Right-click on a file or folder in the explorer--> share via ownCloud

Expected behavior:
You can share a file or a folder with a public link without setting a password

Actual behaviour
"Public sharing requires a password" is set in the client even though this is disabled in the ownCloud Server config. Therefore, you cannot share a file via public link without setting a password.

**Comment by dragotin** [comment]
@rullzer mind to check this?

**Comment by rullzer** [comment]
Yes, this is known. For a solution see https://github.com/owncloud/client/issues/3703#issuecomment-136152864.

It is caused by a bug on the server where the provisioning API takes the wrong default values.
