### ISSUE TITLE
For >= 8.1 servers: Use Depth:0 for EtagJob instead of Depth:1

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3730]
According to @PVince81 @nickvergessen @icewind1991 etc the non-changing root ETag problem is for sure fixed since this version.
Depth:0 has a lot better server performance.

**Comment by icewind1991** [comment]
Additionaly we can look into creating a custom, minimal endpoint that just gets the etag for a file by fileid which we can do without the vast majority of the bootstrap we otherwise need

**Comment by ogoffart** [comment]
minimal endpoint issue on the server: https://github.com/owncloud/core/issues/18776

**Comment by guruz** [comment]
This is done. Let's hope I got the logic right :-)

**Comment by Dianafg76** [comment]
@guruz, @ogoffart What are the steps to reproduce this issue?

**Comment by guruz** [comment]
@Dianafg76 Let's have @icewind1991 confirm this..

**Comment by Dianafg76** [comment]
OK, Thanks

**Comment by guruz** [comment]
Closing this for now..

Server guys: You should see this behaviour if you work on 2.1 nightlies or master branch
