### ISSUE TITLE
Move Desktop Activity Log to a New Button, Sync Log

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#3732]
As a user, I want the Activity tab on a new button in the General tab, and a new activity tab with a true activity feed from the server activity feed API

Acceptance Criteria:
-  A new button takes the current activity log and moves it to the general tab under “Advanced”, and adds a new button label “File Transfer Log” - including re size able columns and items already in the activity tab.
- The new activity feed tab looks the same as the current activity tab and is called “Activity”
- The activity feed from the server is listed here in reverse chronological order
- When online, server is queried for updates from the activity feed every 30 seconds.
- When a new file or folder is shared with a user, the activity will show that file or folder. The next important thing is to augment the pure activity stream for that file with a notification that the file or folder has been synced with the client. For example:
   MTRichards has shared file awesomesauce.txt with you
   awesomesauce.txt has been synced to the desktop
OR
   MTRichards has shared file awesomesauce.txt with you
   awesomesauce.txt has been not synced to the desktop for you due to your selective sync settings
OR
  MTRichards has shared folder “cooltextmessages” with you
  cooltextmessages has been synced to the desktop
- Clearly it is possible to have a file or folder not syncing, and to have updates to those files. The activity stream durifully reports 
- If no new activities are available on the server, the desktop client sleeps for another 30 seconds
- When the activity feed has been offline for a point in time, it downloads the last 24 hours of activity, see next as this value can be adjusted– but does not download the same activity alerts more than once.
- An option on the desktop client allows a user to set the expiration for the activity feed, the default is set to 24 hours – this is available on the activity tab at the bottom
- The desktop client activity feed follows the same rules set in the personal page on the server
-  If the activity feed is not enabled on the server, a message says “The administrator has disabled activity stream for this server”

Advanced:
- The activity feed includes a type ahead filter so users can see search for activity on specific files

**Comment by guruz** [comment]
Related https://github.com/owncloud/client/issues/1443

**Comment by jancborchardt** [comment]
That new true Activity feed should then be shown per-account. There need to be 2 tabs: Activity & Folders.

Folders will show what is currently shown in the box of the specific account, selective sync and adding new folders.

**Comment by ogoffart** [comment]
> When online, server is queried for updates from the activity feed every 30 seconds.

We were trying to oprimize the client so it sends as little requests to the server as possible when idle.   Is this request not going to have a big inpact on the server? (cc @icewind1991 )

**Comment by icewind1991** [comment]
Are we talking about the activity feed from the activities app?

**Comment by guruz** [comment]
@icewind1991 https://.../owncloud/ocs/v1.php/cloud/activity

**Comment by icewind1991** [comment]
I believe that is a fairly expense operation, you could try a system where the activity feed is updated on etag change after sync and every X min for non-write activity items.

**Comment by ogoffart** [comment]
After discussion with @dragotin, we decided to only query the activity after a sync.

**Comment by dragotin** [comment]
Pull request is #4083

**Comment by guruz** [comment]
> I believe that is a fairly expense operation

Still to be done after beta1: Do it only when showing the activity list. (check if this really works)
Problem is that a sync always happens on startup so on startup we always query the activtieis.

**Comment by guruz** [comment]
As discussed in the team meetings we have done this a bit differently for now. 

@Dianafg76 Please test :)
@jancborchardt Have a look at the beta1.. :)

**Comment by Dianafg76** [comment]
Conversation on the IRC, about this two questions:
1.- If the activity feed is not enabled on the server, a message says “The administrator has disabled activity stream for this server”: The answer was: we don't have jet
2.-  An option on the desktop client allows a user to set the expiration for the activity feed, the default is set to 24 hours – this is available on the activity tab at the bottom: The answer was: we don't have an expiry yet

**Comment by dragotin** [comment]
1. A message was added, see #4163 
2. We do not need that as the server does automatically expire the messages. And with our current way of displaying the messages (which is just showing what is on the server) that should be fine.

Setting this to ready-to-test.

**Comment by Dianafg76** [comment]
I tested this issue, and is working OK 
Desktop v ownCloud-2.1.0.2907-nightly20151125.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

Closed
