### ISSUE TITLE
Gracefully Handle Storage Limitations Errors

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#3736]
As an admin, I want filename characters (and other storage limitations) that are not allowed on certain ownCloud back end storage types to throw an error that the desktop client can understand, and then the desktop client notifies the user of the error
Example: certain special characters on SMB storage.

Acceptance Criteria:
- File names allowed in ownCloud may not be allowed in the backend storage a customer chooses.
- When a write operations is attempted to put the file to the backend storage, an error will be thrown and the file will not be synced with the backend.
- If a file cannot be synced, the error thrown by the server will be captured by the desktop client and written to the desktop log

**Comment by ogoffart** [comment]
We have been reporting in the user intefrace the errors from the server for a long time now.

Is there any specific example we need to test?  What is wrong with the current behaviour?

**Comment by MTRichards** [comment]
This was the outcome of our Berlin meetings, where the team said that we could stop checking for illegal characters on the client, and have the server do it instead. This would result in new errors, and that we were now in a place where the server could start to pass those along to the user so that we could tell them when, for example, illegal characters were not allowed to be synced because of a backend limitation. Until now, we have checked for those in the client and prevented sync, but the concept here is to try to sync with the server, and then the server lets the client know the errors based on what the backend tries to do, not a pre-set list in the client. If I recall correctly.

@DeepDiver1975 was involved in the specifics, as was @dragotin @danimo and others.

**Comment by Dianafg76** [comment]
I tested this issue:

With this characters (<, >, /, *, ?, '', |) on Winodws is working OK when you create a new Folder/File. If you go to Activity options you can see this message (The file name contains invalid characters that can not be ......)

BUT: With this character (\\) I can't create a Folder o File on Server (you can see "Could not create folder, File name contains at least one invalid character")

Desktop v ownCloud-2.1.0.5584-nightly20151027-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

**Comment by ogoffart** [comment]
> BUT: With this character (\) I can't create a Folder o File on Server (you can see "Could not create folder, File name contains at least one invalid character")

Yes, that's the expected error.

**Comment by Dianafg76** [comment]
Thanks
