### ISSUE TITLE
Desktop 2.1 Feature Summary

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#3738]
- File Firewall error handling - To ensure that permanent and non-permanent errors are handled properly in the sync run - https://github.com/owncloud/client/issues/3490
- Desktop Full Sharing - Allow full owncloud sharing from desktop - https://github.com/owncloud/client/issues/3737
- Disk Full - Handling disk full properly - https://github.com/owncloud/client/issues/2939
- File Transfer Log and Activities - start using server activity stream - https://github.com/owncloud/client/issues/3732
- Notifications - send notifications from the server to the desktop - https://github.com/owncloud/client/issues/3733
- Checksums - Start checking file transfers for corruption using checksums - https://github.com/owncloud/client/issues/3735
- File storage limitation handling - Handle new server error codes for storage backend limitations (9.0?) - https://github.com/owncloud/client/issues/3736

Other bugs:
- Handling 423 Locked Gracefully- https://github.com/owncloud/client/issues/3387

**Comment by MTRichards** [comment]
@dragotin @danimo @guruz @ogoffart @karlitschek @jancborchardt

**Comment by karlitschek** [comment]
very nice!

**Comment by pierrejochem** [comment]
:+1:  Especially: "Desktop Full Sharing"

**Comment by guruz** [comment]
2.1 will be released tomorrow.. :)
