### ISSUE TITLE
[Proposal] Show Avatar in client window

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/client#3741]
This is just an idea because the user avatars are available in the web interface if they are set. But I'm pretty sure that it is only possible with involving the core team.

![sysmexcloud_2015-09-03_16-42-23](https://cloud.githubusercontent.com/assets/9192953/9661479/33f8957c-525b-11e5-8304-e6c70f9a1de2.png)

Yellow marked are with gravatar. It would make the application more personal.

**Comment by danimo** [comment]
gravatar is a propritary service. the generic thing is called avatar :)

**Comment by pierrejochem** [comment]
Yes, you are right. Read that afterwards by my self :-P

**Comment by pierrejochem** [comment]
It must be a core app (mandatory) which is using the owncloud API classes to provide the image as base64 and if it is not set then show the default picture. So server side is not that hard because the existing codebase can be used for it.

**Comment by karlitschek** [comment]
interesting idea. This should be read from the server without direct avatar of course. The server has already an api for that.
@rullzer Can you point to the API ?

**Comment by pierrejochem** [comment]
And I'm pretty sure:

**/ocs/v1.php/cloud/user?format=json**

could be a good place for it ;-)

**Comment by karlitschek** [comment]
The API already exists as mentioned.

**Comment by pierrejochem** [comment]
I know ;-) because I have used it for an Outlook Plugin what I have developed :-D

**Comment by guruz** [comment]
@pierrejochem What's the outlook plugin doing? sounds interesting

**Comment by pierrejochem** [comment]
The addin can save attached files into the cloud and can also get them for new emails. I have also added a cloud note function. With other words I use the API from the note app and show a minimal Editor which is able to show, add, remove and edit notes. Next plan is to add a share function like iCloud where Outlook is creating a public share Link from a file and adding this to a new Email (share API like the Explorer Extension but inside Outlook)

**Comment by karlitschek** [comment]
@pierrejochem This sounds very cool. Can you tell a bit more about this project? Maybe we can collaborate with developing this?

**Comment by pierrejochem** [comment]
Yes sure, I will do that After the weekend ;-)

**Comment by rullzer** [comment]
Currently the url that can be used is:

<SERVER>/index.php/avatar/<UID>/<SIZE>

But keep in mind that we may want to move avatars to their own webdav endpoint. So in 9.0 this endpoint might start throwing 301 responses.

**Comment by pierrejochem** [comment]
@karlitschek: Should I descripe the project (Outlook AddIn) more in detail here or on an additional issue?

**Comment by pierrejochem** [comment]
@karlitschek 

![outlook cloud addin-1](https://cloud.githubusercontent.com/assets/9192953/9722021/c6b2039c-55a5-11e5-87f8-1e8ed1cf8011.png)
![outlook cloud addin-2](https://cloud.githubusercontent.com/assets/9192953/9722022/ca013522-55a5-11e5-9914-e8e579b01bd0.png)
![outlook cloud addin-3](https://cloud.githubusercontent.com/assets/9192953/9722026/cc1b9e6a-55a5-11e5-98b0-e53c1479f23f.png)
![outlook cloud addin-4](https://cloud.githubusercontent.com/assets/9192953/9722027/ce231d5a-55a5-11e5-8923-099c54944eb4.png)

**Comment by karlitschek** [comment]
@pierrejochem This looks interesting. Can you send me a mail to frank at owncloud org ?
Thanks a lot :-)

**Comment by karlitschek** [comment]
@MTRichards FYI

**Comment by MTRichards** [comment]
Indeed interesting.

**Comment by guruz** [comment]
Done in 2.4.0 :)
