### ISSUE TITLE
unique storage identifier to the remote top level sync directory

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#3742]
Think of persistent identifiers in RAID or unique filesystem labels. It is possible to detect configuration mismatches because there is a peristent and universally unique piece of information stored together with the data.

Maybe some of common misconfiguration problems for individual owncloud users could be solved if a sync client could query the server for a storage endpoint identifier which would be universally unique. For example, if there was a persistent uuid stored on the server in the top level sync directory and available as webdav property then a client could detect a silent reconfiguration of a server (which normally results in an empty folder and all files deleted on the server). Such identifier could be generated automatically in a unique way first time user creates the account. For larger deployments, it could maybe help in scenarios when we have test and production environments and sometimes we reconfigure the test proxy to talk to different underlying storage. In this case the server implementation of this identifier could be different but the principle would be the same: it would allow the sync client to find out if it is still talking to the same storage endpoint on the server or there was some kind of reconfiguration. It could result in a better handling of such situations.

Thoughts?

**Comment by guruz** [comment]
I label this as bug because I think this kind of checking is mandatory to do.

@moscicki I agree with you, we should save the root's ```FileId``` also in our ```.csync_journal.db``` and on mis-match throw an error.
The question is do we allow the user to then override the error?

@PVince81 @icewind1991 thoughts? Is ```FileId``` good to use?

Related https://github.com/owncloud/client/issues/2325

**Comment by moscicki** [comment]
@guruz: thanks! I am thinking about the sync protocol: shouldn't we be able to query the "unique storage id" as a webdav property for any directory (also to account for the fact that someone may be adding a sync folder inside the folder tree on the server rather than syncing everything via / ). So imagine that in the current server implementation you have all files in the localfilesystem on the server. I would guess that "unique storage id" would be a UUID stored somewhere in the data directory of the user (next to user/files) and that value could be served by PROPFIND for all directories which sit on this local filesystem. In the sync client you may combine UUID:FileId of the directory in question to uniquely identify a directory (this assumes that FileId never repeats which may be a good assumption for now but may not be a good assumption in the future [e.g. if you wanted to use real inodes as FileId -- but maybe we should not worry about this for now).

IMO FIleId alone is not good enough because if you start with a fresh database then the FileId counts again from zero and there is a possibility that the value repeats with what you have stored earlier.

**Comment by icewind1991** [comment]
> Is FileId good to use?

Yes

**Comment by ogoffart** [comment]
This won't help for #2325 since the restaured backup will have the same ID of course.

And what should happen if the file id  mismatch? a fatal error that prevent the sync? And then how would the user resolve this?

We already have the check that if all the files are changed, the user is asked if he wants to keep the files.

**Comment by guruz** [comment]
@moscicki Does https://github.com/owncloud/core/pull/24054 help you?

FYI @rullzer

**Comment by rullzer** [comment]
Yes https://github.com/owncloud/core/pull/24054 was added for this.
The plan is to have the client store the data-fingerprint. And if it changes the client knows a backup has happend.

The plan was then to halt syncing. Make conflict files of all the stuff that could be in conflict. And let the user resolve it manually.

**Comment by guruz** [comment]
👍 I'm closing this then. If there is more questions from @moscicki we can still continue the discussion. The client side will hopefully be implemented soon too.

**Comment by dragotin** [comment]
But do we have an issue to track the client task about this?

**Comment by guruz** [comment]
-> https://github.com/owncloud/client/issues/2325
