### ISSUE TITLE
[2.0.1] Different certificate fingerprint algorithms on different computers (same client version)

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/client#3743]
I noticed 

both computers run OC Linux client 2.0.1
one system is OpenSuse Tumbleweed,

that the one client shows SHA-1 and MD5 fingerprints, the other clients shows SHA-256 and SHA-1.

I am puzzled why the same client version uses different fingerprint algorithms.

**Comment by danimo** [comment]
Because some clients use Qt4, which does not yet support SHA256 calculations. Others use Qt5. We still want to give two algorithms, which is why we show MD5 instead. Not an issue since we're converging towards using Qt5 everywhere, and comparing two hash values is still safe.

**Comment by Wikinaut** [comment]
Ok, I understand. But it is strange, that the same OC client version (2.0.1) can show the different behaviour.
