### ISSUE TITLE
Owncloud Web Login: Asterisks fill blank Password Field in IE8

### ISSUE THREAD

**Issue by ncwolf** [owncloud/client#3744]
When logging into owncloud 8.1.1 on IE8, asterisks fill the blank password field. This is confusing to users b/c it looks like they are overwriting a password in the field to enter their own.

http://nicolewolfart.com/dir

### Expected behaviour
Password field should contain the word "password" (as in all other browsers.)

### Actual behaviour
Blank password field contains asterisks.

### Server configuration
**Operating system**: Linux

**Web server:** Apache

**Database:** MySQL

**PHP version:** 5.4.43

**ownCloud version:** 8.1.1

**Updated from an older ownCloud or fresh install:** Fresh Install

**List of activated apps:** None. Performed default install on 9/1/15.

**Comment by danimo** [comment]
This is the bug tracker for the desktop client. Please reopen in https://github.com/owncloud/core

**Comment by ncwolf** [comment]
Will do and sorry for wrong placement!
