### ISSUE TITLE
Problems with UNC Pathes

### ISSUE THREAD

**Issue by HiBit** [owncloud/client#3748]
Hello,
the new client 2.0 and 2.1 can't sync folders which are on a UNC path.
I've tested it with multiple computers and on every machine this error occours.

  
![owncloud](https://cloud.githubusercontent.com/assets/3921645/9679623/78940cd0-52f0-11e5-86d9-8873b2a21748.PNG)

**Comment by ckamm** [comment]
@HiBit This did work with previous versions, right?

**Comment by danimo** [comment]
I am assuming this is related to the switch to using native win32 instead of posix API on Windows. Which is surprising, because it should accept UNC pathes by default...

for reference: https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247(v=vs.85).aspx

**Comment by HiBit** [comment]
@ckamm 
On previous versions it work.

**Comment by danimo** [comment]
@HiBit What is your use case for syncing to UNC paths? Can you gurantee that there is no concurrent access to the location? No two clients must sync to the same location. I'm asking because UNC was never intentionally supported, mostly out of this consideration. Then again, we did not try to prevent it either.

**Comment by HiBit** [comment]
My use case? I sync my local profile with my server. I can gurantee that there is no other access to the location. With users i've the same problem.

**Comment by Dianafg76** [comment]
@HiBit you could try this version: http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.5463-nightly20150915-setup.exe
It works for me ok
Thanks

**Comment by vkykam** [comment]
Just downloaded 2.02.5463 and has solved the CSync error for me as well.

**Comment by danimo** [comment]
@vkykam Thanks for letting us know!
