### ISSUE TITLE
[2.0.1] connectLabel showing HTML (Dutch translation issue)

### ISSUE THREAD

**Issue by canihavesomecoffee** [owncloud/client#3749]
### Expected behaviour

Previous versions showed a clickable link to the OwnCloud installation

### Actual behaviour

The HTML code for the link is rendered as text instead.

### Steps to reproduce
1. Install the 2.0.1 client (I upgraded from 1.8.x)
2. Open the account view
3. View the result:

![cloud](https://cloud.githubusercontent.com/assets/7365586/9680849/1bb2a99a-52fa-11e5-9367-1da4606b19bb.png)

### Server configuration

N/A

### Client configuration
Client version: 2.0.1 (build 5446)

Operating system: Win 7 64-bit

OS language: Dutch

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

N/A

**Comment by phil-davis** [comment]
In English and Windows it is displaying fine for me.
Maybe this is a language string translation issue, and some of the HTML markup is going wrong in the Dutch translation?

**Comment by danimo** [comment]
The dutch translation has a stray newline in the text. The label class will try to look for a HTML tag only until the first newline to determine if it has to display richtext -> translation issue.

**Comment by canihavesomecoffee** [comment]
Is there a way for me to help fix the translation issue, or is there nothing that can be done from my side?

**Comment by guruz** [comment]
@canihavesomecoffee Can you try to join the Dutch owncloud team on transifex?

**Comment by canihavesomecoffee** [comment]
@guruz I made a request to join the Dutch team on transifex with an account with the same name as here on GitHub 2 days ago, so if it's accepted I can fix it :+1:

**Comment by danimo** [comment]
Fixed in transifex. Should show up in tomorrows nightly build.

**Comment by danimo** [comment]
![image](https://cloud.githubusercontent.com/assets/1315934/9783593/aecb0042-57a5-11e5-9e61-e1758a14fc24.png)

**Comment by canihavesomecoffee** [comment]
Looks good, feel free to close this issue when it's in the client :+1:
