### ISSUE TITLE
On the screen to enter the URL if it is closed with the red button again, the screen does not appear to enter the URL

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3750]
### Steps to reproduce
1. Delete the account
2. Click on Remove connection
3. Quit owCloud
4. Click on icon Desktop client
5. Setup oC server appears
4. Click on the Red Button for close the screen

### Expected behaviour
You should see the Setup screen to introduce the Server Address

### Actual behaviour
no setup screen appears URL

### Server configuration
Desktop Version 2.0.2-nightly20150903 (build 2701).
Server v {"installed":true,"maintenance":false,"version":"8.1.1.3","versionstring":"8.1.1","edition":"Enterprise"}

**Comment by ckamm** [comment]
@Dianafg76 red button = Close window button? If you close the wizard, it should only reappear when you click the tray icon again...

**Comment by ogoffart** [comment]
I think the current behaviour is good enough.
If you close the wizard, we should not re-open it automatically. The user want it gone.  He can get it back by clicking on the systemtray or by adding adding a new account.

Don't you agree?

**Comment by Dianafg76** [comment]
OK
closed
