### ISSUE TITLE
[OS X]Setup Wizard: Wizard should not have active green full screen button

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3751]
### Steps to reproduce
1. Delete the account
2. Click on Remove connection
3. Quit owCloud
4. Click on icon Desktop client
5. Setup oC server appears
6. Click on the Green button
### Expected behaviour

The application does nothing
### Actual behaviour

It should be full screen
### Server configuration

Desktop Version 2.0.2-nightly20150903 (build 2701).
Server v {"installed":true,"maintenance":false,"version":"8.1.1.3","versionstring":"8.1.1","edition":"Enterprise"}

**Comment by ckamm** [comment]
@Dianafg76 What green button?

**Comment by Dianafg76** [comment]
@ckamm 
![screen shot 2015-09-04 at 14 51 16](https://cloud.githubusercontent.com/assets/12032058/9683921/9551037c-5314-11e5-9c36-6fbbe37fc212.png)

**Comment by danimo** [comment]
It's a dialog, and therefor the green  button should not be active in the first place.

**Comment by ogoffart** [comment]
Closing old issue.
