### ISSUE TITLE
2.0.1 german translations incomplete

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#3753]
2.0.1 running with all locale elements set to de_DE.utf8
We currently six text lengthy texts in english on an otherwise german page:

![s3-sync-screenshot-201-blackened](https://cloud.githubusercontent.com/assets/1108546/9684695/6dd7c556-5319-11e5-95ea-2c7ba2ca62ed.png)

**Comment by jnweiger** [comment]
The line below the progress bar alternates between "Herunterladen .... (0 B von 807 kB)"
and "Syncing '....', '...' a SSASTS 262 kB/s"

The SSASTS part looks weird.

**Comment by tflidd** [comment]
Instead of SSASTS, I have to boxes:
![bildschirmfoto vom 2015-09-06 10 40 31](https://cloud.githubusercontent.com/assets/8111200/9703446/ca082566-5484-11e5-803d-fc0dd52f023b.png)
Version 2.0.1 (git: 58ea249) on Ubuntu 14.04 (from SuSE repo)

**Comment by MegaV0lt** [comment]
Same her in Win client 2.01
http://i.imgur.com/CKrkQLJ.png

**Comment by danimo** [comment]
I have now added all missing translations. Btw: We should really check why the German translation team has run away. Looking at the contextless translation in transifex I get an idea as to why...

**Comment by phil-davis** [comment]
@individual-it - your German is quite good :)

**Comment by individual-it** [comment]
I've build the client from the current master on Linux.
The newly build client does not pick up the German translation when started from "client-build/bin/. Anything fancy I have to do to make it change the language?
But I can copy the "client_de.qm" to "/usr/share/owncloud/i18n/client_de.qm" and start the 2.0.1 client

The translation is better but there should be an "arrow down" (\u2193) or "arrow up" (\u2191) where in windows it says "download" or "upload"
https://github.com/owncloud/client/blob/master/src/gui/folderstatusmodel.cpp#L794

That still does not work for me.

**Comment by danimo** [comment]
@individual-it That's mostly because the translation is only synced every 24 hrs

**Comment by danimo** [comment]
> The translation is better but there should be an "arrow down" (\u2193) or "arrow up" (\u2191) where in windows it says "download" or "upload"

Not sure what you mean but this is correct. Windows seems to not provide these unicode characters safely, so we use upload and download as a workaround instead.

**Comment by individual-it** [comment]
But it seems that Linux/Gnome also has a problem to display the unicode characters.  on my system it looks the same like in the screen shot of @tflidd  https://cloud.githubusercontent.com/assets/8111200/9703446/ca082566-5484-11e5-803d-fc0dd52f023b.png

**Comment by individual-it** [comment]
changing ````tr()```` to ````trUtf8()```` in 
https://github.com/owncloud/client/blob/master/src/gui/folderstatusmodel.cpp#L794
and
https://github.com/owncloud/client/blob/master/src/gui/folderstatusmodel.cpp#L802
did solve the problem for me
see my PR #3775

**Comment by Dianafg76** [comment]
@jnweiger you could try this version: http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.2713-nightly20150914.pkg.
Thanks

**Comment by guruz** [comment]
@DeepDiver1975 @danimo  @LukasReschke  I'm a bit confused on how transifex works.
For our client project:

German Untranslated 159
German (Germany) Untranslated 183

Is there a need for both? Should we merge this?
Is this someone done automatically by Qt?

Still it's weird in transifex since I'd have no idea to which one to contribute so my changes are visible.

**Comment by danimo** [comment]
Looks jolly good here:

![image](https://cloud.githubusercontent.com/assets/1315934/10130748/44ed8026-65cb-11e5-9aef-12cbbbbfd4be.png)

**Comment by danimo** [comment]
In ownCloud `de_DE` is formal German (Sie, default for enterprise edition), whereas `de` is informal (Du, default for community edition). In the client, we only use the formal version:

From `translations/.tx/config`:

```
# de_DE holds the formal translation which we want as default
trans.de_DE = client_de.ts
```

**Comment by Dianafg76** [comment]
@jnweiger could you try this version: http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.2750-nightly20150928.pkg
Thanks

**Comment by MegaV0lt** [comment]
@danimo 
But not the button!
http://i.imgur.com/iH926GK.png

**Comment by danimo** [comment]
@MegaV0lt I know, the translation is not 100% complete, but no translation is.

**Comment by dragotin** [comment]
I completed the german translation today in transifex. Should sync into the client git repo and be available with the nightly tomorrow.

**Comment by tflidd** [comment]
Looks good. Only one detail:
![unbenannt](https://cloud.githubusercontent.com/assets/8111200/10424134/bf14c146-70cc-11e5-8b49-fc8bcf16b075.png)
The `second(s)` in the remaining time.

**Comment by tflidd** [comment]
I updated to 2.0.2 and it looks good. You could close this topic from my point of view.
