### ISSUE TITLE
UI: choose what to sync dialog has no totals

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#3755]
I've removed my root folder connection 
and started a sync connection between a local and remote folder jw.
The 'choosw what to sync' dialog for this shows sizes of subfolders of 'jw', but not the total size of folder jw.
![201-choose-what-to-sync-has-no-total](https://cloud.githubusercontent.com/assets/1108546/9685860/1784929e-5321-11e5-833e-da9ed4f7fd18.png)

**Comment by Dianafg76** [comment]
I tested this issue, but the total size of the folder is not the total :
![screen shot 2015-10-22 at 13 08 25](https://cloud.githubusercontent.com/assets/12032058/10663789/728ece58-78be-11e5-9412-ef51a09d0648.png)

Desktop v ownCloud-2.1.0.2821-nightly20151022.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

**Comment by ogoffart** [comment]
This looks like the total to me.
