### ISSUE TITLE
Coin the term 'folder sync connection'

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#3757]
Currently we use different names to refer to a folder sync connection:

* In this error message, it is called an 'upload folder'.
![201-already-upload](https://cloud.githubusercontent.com/assets/1108546/9687060/7c0dd3a0-5327-11e5-9aca-215f02b2a3cd.png)

* The button [Add Folder to Synchronize] should say [Add Folder Sync Connection]

these are small improvements that could help coin the term.

**Comment by jancborchardt** [comment]
Yeah, »Folder sync connection« sounds good.

**Comment by phil-davis** [comment]
I looked at all the various warning messages that can be displayed in that Add Folder Sync Connection dialog. The wording of some was a bit hard to understand or mixed up, so I tried to standardize them all as well as use the "folder sync connection" terminology - https://github.com/owncloud/client/pull/3781

**Comment by phil-davis** [comment]
What about the title of the whole dialog box - it says "Add Folder".
Should it also say "Add Folder Sync Connection"?

**Comment by ogoffart** [comment]
I changed it in even more places.

(Personaly i don't like that term because `Sync` is an abbreviation and so it's not so nice.  But if jan insist, then so be it)

**Comment by Dianafg76** [comment]
I tested this issue, and I see the new name "Add Folder Sync Connection", "Used in a folder sync connection" .... So for my OK

Desktop v ownCloud-2.1.0.2831-nightly20151027.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

Closed
