### ISSUE TITLE
UI: Vertical alignment of checkboxes on general settings tab is not ok

### ISSUE THREAD

**Issue by rakekniven** [owncloud/client#3758]
See attached screenshot. There are two checkboxes on the left on the middle of the screen.
Vertical alignment is not ok.

![bildschirmfoto 2015-09-04 um 21 57 21](https://cloud.githubusercontent.com/assets/2069590/9693498/405a4026-5351-11e5-9b17-6e9f5e8e8950.png)
Should be an easy task.

btw. if someone is speaking german please have a look at the translation of first checkbox.
Let me know if I should open another issue regarding 1%.

Client version 2.0.1 on Mac OS X 10.10.5.

**Comment by phil-davis** [comment]
Note: %1 translation issue is already logged at https://github.com/owncloud/client/issues/3717

**Comment by guruz** [comment]
@Dianafg76 For testing this you need a build with auto updater enabled

**Comment by Dianafg76** [comment]
@rakekniven you could try this version: http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.2713-nightly20150914.pkg.
Thanks

**Comment by Dianafg76** [comment]
I tested this issue and It looks the same
![screen shot 2015-09-15 at 10 39 43](https://cloud.githubusercontent.com/assets/12032058/9871998/aa951dd8-5b96-11e5-8cf0-b99ed5e94d96.png)

**Comment by Dianafg76** [comment]
I tested this issue, and now the two check boxes on the left in the center of the screen. The
Vertical alignment is good.

Desktop v ownCloud-2.1.0.2824-nightly20151023.pkg (on MAC), wnCloud-2.1.0.5577-nightly20151023-setup.exe (on Windows)
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

Closed
