### ISSUE TITLE
Forbidden message when attempting to sync files to ownCloud server

### ISSUE THREAD

**Issue by gig13** [owncloud/client#3759]
### Steps to reproduce
1. Try to sync files from your desktop to the ownCloud server with the Windows desktop client

### Expected behaviour
Files should sync successfully without error,

### Actual behaviour
Receive a server side error
` No basic authentication headers were found` error message on the server, and .
Client side error 
`starwars.jpg - server replied: Forbidden" QVariant(int, 403) QVariant(QString, "Forbidden")`

### Server configuration
**Operating system**: CentOS 6.7 

**Web server:**: Apache (using Cpanel and easyApache)

**Database:** MySQL

**PHP version:** 5.5.8

**ownCloud version:** 8.1.1 

**Updated from an older ownCloud or fresh install:** New install

**List of activated apps:** Standard apps by default

**Are you using external storage, if yes which one:**  NO

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

### Client configuration
**Operating system:** Windows

#### ownCloud log (data/owncloud.log)
on s3 https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fclient%2F3759

#### desktop client log
on s3

@MorrisJobke @bboule

**Comment by MorrisJobke** [comment]
Looks a lot like wrong password. Or does the client sends a "cookie only" version of the request first and then sends the basic auth headers?

**Comment by gig13** [comment]
@MorrisJobke 
I have a test account and see the same behavior with the desktop client, it connects and the folders and files from the server are downloaded, but the uploads of new files fail. New folders are created successfully via the desktop client.

**Comment by gig13** [comment]
owncloud.log also writes the following:
```
Error 	PHP 	opendir(/root/tmp): failed to open dir: Permission denied at /home/omnivalv/public_html/cloud/lib/private/tempmanager.php#179 	2015-09-08T11:13:27+00:00
Error 	PHP 	opendir(/root/tmp): failed to open dir: Permission denied at /home/omnivalv/public_html/cloud/lib/private/tempmanager.php#179 	2015-09-08T11:13:14+00:00 
```

**Comment by MorrisJobke** [comment]
> opendir(/root/tmp): failed to open dir: Permission denied at

That means that "Permission is denied to use this directory" -> fix permissions and upload will work.

**Comment by MorrisJobke** [comment]
> opendir(/root/tmp):

And this looks a bit odd...why is `/tmp` in `/root/tmp`

**Comment by MorrisJobke** [comment]
Check you php.ini for wrongly configured tmp folder.

**Comment by gig13** [comment]
@MorrisJobke 
It uses easyApache and Cpanel so the php.ini needs to be modified that way -- not sure why /root/tmp is used.

Should I just change the upload_tmp_dir ?

**Comment by MorrisJobke** [comment]
> Should I just change the upload_tmp_dir

Configure how you want, but do it correctly. It says simply that the permissions are wrong -> set the correct permissions and this should be fixed, but it feels just wrong to have the `/tmp` inside of roots home folder.

**Comment by gig13** [comment]
@MorrisJobke @danimo 
I no longer see the tmp dir problem in the owncloud logs only:
```
Error	PHP	Array to string conversion at /home/BLAH/public_html/cloud/lib/private/template/functions.php#36	2015-09-08T17:02:27+00:00
```

New desktop client log on s3 called 20150908 Desktop Client Log

**Comment by gig13** [comment]
@cburnard

**Comment by cburnard** [comment]
@gig13 Can you get me access to this box please.

**Comment by MorrisJobke** [comment]
@gig13 what theme is used?

**Comment by gig13** [comment]
@MorrisJobke 
Standard Edition theme

**Comment by cburnard** [comment]
@gig13 @MorrisJobke 

Client's webdav was blocked by Apache.  Missing the below from httpd.conf.

        Order allow,deny
        Allow from all
        AllowOverride All

Working now.
