### ISSUE TITLE
[Linux] [2.0.1] wizard reruns every startup

### ISSUE THREAD

**Issue by rcomroe01** [owncloud/client#3761]
Various clients running on multiple machines flawlessly.  Linux client 2.0.1 running on more than one machine, but on one machine every startup it opens connection wizard without remembering the prior server connection.  Run the connection wizard through to FINISHED, but on next startup won't remember and connection wizard starts over.  Other workstations running same client work fine.

**Comment by rcomroe01** [comment]
Solved:

The machine that had this issue "I suspect" was simply because it is faster than the other computers (ASUS P6T7 WS, Xeon w3580, 12GB DDR3 1600 ECC, and importantly Samsung 840 SSD).  Of my other computers without issues, some of them were also running SSD's, but these are both slower SSD drives and slower processors + less RAM.

**It seems that the gnome-keyring service was not completely started by the time that the owncloud-client gets started.  Eg, that this is a race-condition of sorts.


--owncloud would intermittently (most of the time) either show a password prompt during login or cause a complete re-prompt for the server + credentials.
--Removing all startup points for owncloud and delaying the start of owncloud until after the keyring service has eliminated the issue.


For reference, that system is running Xubuntu 14.04 LTS.  The install is fairly stock (no custom repositories added) except that it's running kernel 4.1.6 and Xorg 1.17.1 (due to a need to run NVidia 355.11 drivers).

**Comment by guruz** [comment]
@rcomroe01 Could you (after the first run) check the ```owncloud.cfg``` and paste it here?
We need to see what is saved there.

**Comment by guruz** [comment]
@rcomroe01 Also start as ```owncloud --logfile -``` to possibly see some output that helps to track this down
