### ISSUE TITLE
Commit 699acc99e4875c9f5b09f12b084330f3f2020681 impedes BUILD_WITH_QT4 option

### ISSUE THREAD

**Issue by d1saster** [owncloud/client#3765]
The preprocessor safe-guarding that was removed in commit 699acc99e4875c9f5b09f12b084330f3f2020681 actually results in build errors when using Qt4. More specifically, the call to QMenu::platformMenu() does not exist in Qt4.

**Comment by guruz** [comment]
https://ci.owncloud.org/job/client-build-matrix-linux-2.0/compiler=g++,label=master,mirallBranch=2.0,qt=qt4/151/console

FYI @ckamm @ogoffart

**Comment by ckamm** [comment]
Will fix.

**Comment by guruz** [comment]
@d1saster Works for you?

**Comment by d1saster** [comment]
Works :) Thx.
