### ISSUE TITLE
Make some notifications clickable

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#3766]
I just got the notification that a folder has been added with more than 500 MB. Unfortunately I could not click on the notification for further actions.
System: Ubuntu 14.04
Version: 2.0.1 (git 58ea49) from SuSE repo

I don't know if there is something supposed to happen when clicking on the notifications (either bug or feature request). In this case it would be nice to open the client in order to make your decision.

**Comment by guruz** [comment]
Agreed, this should probably open the settings dialog..

FYI @danimo @dragotin @jancborchardt

**Comment by jancborchardt** [comment]
On Ubuntu, notifications are not clickable as far as I know?

**Comment by stonerl** [comment]
No in Ubuntu the notifications are not clickable, [see here](https://wiki.ubuntu.com/NotifyOSD).

On GNOME,though, you can add actions, [see here](https://wiki.gnome.org/Design/OS/Notifications).

**Comment by danimo** [comment]
@tflidd Are you using GNOME, KDE or Unity?

**Comment by tflidd** [comment]
It's Unity. Could be worth to consider switching to GNOME :smile:

**Comment by danimo** [comment]
Ok, closing then. Mr. Shuttleworth has decided that in his domain, notifications shall not be clickable....

**Comment by tflidd** [comment]
@danimo But on other desktops this could still be interesting. And other platforms (don't know if OS X or Win support this)?

**Comment by danimo** [comment]
@tflidd It should work there...
