### ISSUE TITLE
[KDE] Can't start the client minimized

### ISSUE THREAD

**Issue by dances-with-clouds** [owncloud/client#3771]
The client always starts with its window maximized, when starting a KDE session, even if the old session is saved and restored. The client's previous version did not behave this way: it stayed minimized inside KDE's system tray. 

I was able to adjust this by creating a KDE system rule, that forces this window to be started minimized. But I think the client should provide an option to be started minimized by itself.

**Comment by guruz** [comment]
Are you sure the client is not in startup items AND being restored from session at same time?

**Comment by dances-with-clouds** [comment]
I get your point, but this shouldn't be a problem, because there are a lot of other KDE programs and items that are restored and in startup items as well, and those programs behave different: when started for the first time, they go to the system tray, and when restored at the beginning of the next KDE session, they are not started a second time, they are just being restored.

So I think owncloud client should be capable of recognizing its previous state as well.

**Comment by dragotin** [comment]
The client starts minimized by default. This must be some configuration on your system. Sorry, closing.

**Comment by dragotin** [comment]
Well, maybe its the problem that you have enabled autostart in the client (see settings dialog) AND KDE is starting it through its session management.

Try either to remove the checkmark in the client, or add it to the list of applications excluded from sessions in https://userbase.kde.org/System_Settings/Startup_and_Shutdown#Session_Management

Does that help?

**Comment by dances-with-clouds** [comment]
dragotin: I think you have found the right solution. I unchecked the autostart in the client, and now the client is restored minimized. Thank you! :)

Although this problem is solved, I kindly recommend the authors of the program to take a look at this problem. I am not saying that it's the client's fault that this happens, but I believe that the program and KDE's session management must cooperate better, to prevent such things.

**Comment by guruz** [comment]
Guys, please subscribe to the issue https://github.com/owncloud/client/issues/3273 
Thanks :)

**Comment by dances-with-clouds** [comment]
Guruz: Thanks for the link to the other topic. I really didn't know about it, and I am not sure, I would have recognized it to be the cause of my problem for two reasons: the headline starts with "Plasma 5", which doesn't apply to my, as I am still using "old fashioned KDE4", and secondly, because I have not experienced such behaviour of any other program that I use. 

But yes, you're absolutely right: after reading the topic, I see that this is a bug that applies to both, KDE4 and 5.
