### ISSUE TITLE
[OS X] [10.7] Finder crash on share link

### ISSUE THREAD

**Issue by ToledoEM** [owncloud/client#3772]
### Expected behavior
Not crashing Finder when generating link to share a file.

### Actual behavior
Finder crash when owncloud is open and try to display menu over files to share.

### Steps to reproduce
1. Right click over files to share with owncloud.
2. Finder crash
3. 

### Server configuration
Operating system: OSX 10.7.5
Web server:  Apache/2.2.22 (Debian)
Database:mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (i686) using readline 6.2
PHP version: PHP 5.4.44-0+deb7u1 (cli) (built: Aug 26 2015 12:02:45)
ownCloud version: ownCloud 8.1.0 (production)
Storage backend: default

### Client configuration
Client version: Latest stable version: 2.0.1  (Changelog)
Operating system: OS X 10.7.5
OS language: English
Installation path of client: default

### Logs

https://gist.github.com/ToledoEM/6875f1aba4d6a2fac3e3

EDITED
````
PlugIn Identifier: com.owncloud.finder
OS Version:      Mac OS X 10.7.5 (11G63)
Crashed Thread:  0  Dispatch queue: com.apple.main-thread
Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
Exception Codes: KERN_INVALID_ADDRESS at 0x00000000000f7d54
````

**Comment by guruz** [comment]
> Operating system: OSX 10.7.5

Hmm..

**Comment by guruz** [comment]
Same crash: https://github.com/owncloud/client/issues/3774

**Comment by jturcotte** [comment]
Should be fixed by https://github.com/owncloud/client/commit/5e657aadeea9f856b6f1c3c7c8af94b13b16ac78

This report was earlier but let's track the issue at #3774 since it got more details.
