### ISSUE TITLE
[Windows] [2.0.1] Stops syncing after hibernating

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#3776]
Today morning after hibernat of Windows the Client is showing that sync is paused. No sync is done. A screenshot with Log: http://i.imgur.com/Qaghtis.png

Mainly this lines: 
09-08 08:53:34:218 0x553deb0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https:/xxx/owncloud" + "/"
09-08 08:53:34:594 0x553deb0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
09-08 08:53:34:595 0x553deb0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://xxx/owncloud" + "/"
09-08 08:53:39:693 0x70354b8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x67db6f8) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
09-08 08:53:39:693 0x70354b8 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x67db6f8) QObject(0x0)  0 false 3 0

**Comment by guruz** [comment]
So it never recovers at all? No more syncing?

**Comment by guruz** [comment]
Do you have a fuller log, including the time before your hibernate?
You can create one by starting the client with ```owncloud.exe --logfile c:/path/to/logfile.txt```

**Comment by guruz** [comment]
No more info from user..

**Comment by guruz** [comment]
@MegaV0lt Have you seen my comment here: https://github.com/owncloud/client/issues/3969#issuecomment-155419445

**Comment by MegaV0lt** [comment]
After installing the nightnly i do not have any connection anymore! See screenshot with some log (F12)
Also the client is checking the updateserver forever...

![Image of Yaktocat](http://i.imgur.com/1Y0Apxh.png)

**Comment by guruz** [comment]
New attempt: http://download.owncloud.com/desktop/daily/ownCloud-2.1.0.5619-nightly20151111-setup.exe (branch ```bearer_windows_dlls```)

**Comment by guruz** [comment]
@MegaV0lt Any news?

**Comment by MegaV0lt** [comment]
Not jet, just installed becuase i did not have time until now. Firt run after installing looks better. Connection seems ok...

Screen after first start
![Image of Yaktocat](https://i.imgur.com/LhSrO43.png)
