### ISSUE TITLE
Position of »Add account« function

### ISSUE THREAD

**Issue by drakanor** [owncloud/client#3778]
After searching for the "add account" feature (and missing it), I ended up posting in the owncloud forums for help.

That's why I'd like to recommend a better place for placing the "add account" button and where I would have expected it: in the main menu tabstrip next to the accounts. See attached image for reference (client is in german, but I'm sure you get the idea).

Maybe this is helpful for others as well.
![owncloud_add-account](https://cloud.githubusercontent.com/assets/5364367/9731617/485f700a-561e-11e5-8a38-f467f4266fba.jpg)

**Comment by danimo** [comment]
That was my first initiative but @jancborchardt said this was too prominent...

**Comment by drakanor** [comment]
Well, I think this position is common sense, I have seen it there in several similar clients. To hide it away from the accounts as a small button in a common config tab is not a good user experience imho.

**Comment by jancborchardt** [comment]
@danimo @dragotin @ogoffart @guruz we now talked about this several times. The alternatives are:

1. in the »General« tab like now: way too hidden
2. in the accounts tab bar: way too prominent – how often do you add a new account?
3. next to the »Delete« button of the current account. I know this might be nonstandard, but it’s related to accounts and isn’t either hidden or way overprominent.

So can it please be fixed that way? Thanks.

**Comment by danimo** [comment]
@jancborchardt This was your preferred solution! 3. does not work after you delete the last account. Currently all we have is the lame, time delayed opening of the wizard, which so far has managed to confuse everyone I've seen using it. So 2. may be a bit over-visible, but at least it's clear.

**Comment by tflidd** [comment]
This feature was requested so often, there is no reason to hide it!

I only "found" (looked for) it because it was announced in the change-logs. In the general section, you can do some customization of the client and most people will never go there. I would prefer the tabstrip until you figured out a better solution.

**Comment by jancborchardt** [comment]
> 3. does not work after you delete the last account.

@danimo I’m pretty sure I said it before: When the last account is deleted, of course in place of that there should be a nice empty content message (like for empty folders in the web interface) saying:

> (account icon)
> No account added yet
> [Add account]

Clear now?

**Comment by danimo** [comment]
@guruz @ogoffart Why did we implement it differently?

**Comment by danimo** [comment]
@jancborchardt like that?

![image](https://cloud.githubusercontent.com/assets/1315934/9778397/ff12d6fa-576f-11e5-9806-fbd57e777e40.png)

**Comment by phil-davis** [comment]
Just a suggestion to reduce the number of words:
If you do not wish to add an account now, no problem! You can define one at any time.

**Comment by phil-davis** [comment]
What happens after the first account has been added? Does the "Add Account" button stay in the top row, and the words change to remove "Before you can start..." and replace with other text about adding another account?

**Comment by danimo** [comment]
@phil-davis The idea is that it will go away, and that each account tab will have a [ + ] [ - ] type of button array instead (ideally we'd use text, but we need to be economical in terms of space here. Ideas welcome).

**Comment by pierrejochem** [comment]
:+1:

**Comment by jancborchardt** [comment]
@danimo yeah, very cool already! :) Just remove the 2nd paragraph as otherwise it’s a bit much text to read. And good on the friendly language! :)

**Comment by danimo** [comment]
@jancborchardt Does the `[ + ] [ - ]` solution work for you?

**Comment by jancborchardt** [comment]
@danimo I’m not 100% sure how that will look like. If it’s what we talked about before, an »Add new account« to the right next to the »Remove account« button, then yes that works.

**Comment by danimo** [comment]
@jancborchardt There is not enough space for text there, hence we could only have symbols if we keep the buttons at that location.

**Comment by jancborchardt** [comment]
Right, good point. Maybe then just »Remove« and »+ Account«? We need to ellipsize the full address of the ownCloud anyway (tooltip on hover) because that can potentially be superlong.

**Comment by ogoffart** [comment]
Closing old issue.  The add account is now in the account menu.
