### ISSUE TITLE
Password to start ownCloud Client

### ISSUE THREAD

**Issue by sndbbbl** [owncloud/client#3779]
Suggest a new feature: Password Protect the starting of the ownCloud Cient.

**Comment by guruz** [comment]
Which OS?
What do you want to achieve?
You don't want to save the server password or you want to completely stop the starting?
Your local files anyway are accessible from the file manager.

**Comment by sndbbbl** [comment]
@guruz 

MacOS and/ or WINDOWS…

Purpose: I have ownCloud installed in an office environment. I don’t want individual users change the settings of the synchronization.

**Comment by guruz** [comment]
So it should still synchronize folders and you would deploy the configuration (owncloud.cfg) via other means?
Should it show the tray icon and overlay icons?

FYI @MTRichards

**Comment by sndbbbl** [comment]
@guruz 
Question 1: Yes, it still should synchronize
Question 2: That's a good question. I suggest it should still be visible to let the system admin know it is running. Overlay Icons also are good to have. It should not be a secret that the files are synched. If password is enabled - exiting the program should also require the PW if that is possible feature.

Purpose: ownCloud is installed in an office environment with many users. Users should not be able to "tamper" with the ownCloud synchronisation after it is set-up by the administrator. Neither share links, nor change synchronisation settings, etc. The Link Sharing feature can be controlled in the user set-up control. So that is solved. But the user still can add folders, remove folders, exit the program, etc.

**Comment by stonerl** [comment]
@sndbbl so you wan't the app's settings and shutdown to be password protected?

Sharing links can be disabled on the server BTW.

**Comment by sndbbbl** [comment]
@stonerl 
1) Correct. as I wrote before: Users should not be able to "tamper" with the ownCloud synchronisation after it is set-up by the administrator...
2) Sharing Links - understood. Already mentioned this above.

**Comment by danimo** [comment]
This is somewhat of a silly feature in the current state of the client. The application runs in the context of the current user and as such can always be terminated without the administrators consent. This feature might make sense once it runs as a privileged service and the UI is decoupled from it, but not that's not the case right now and won't be for quite some time. It's simply not realistically enforceable at this point. Closing for now.
