### ISSUE TITLE
Language Selection of ownCloud Client

### ISSUE THREAD

**Issue by sndbbbl** [owncloud/client#3780]
New feature suggestion: Let the user select the language of the ownCloud Client from within the client settings.

**Comment by danimo** [comment]
What's the use case?

**Comment by phil-davis** [comment]
Not essential for me, but as an example I like to run my overall Windows profile in English (my native language) and be able to switch individual apps into Nepali (where I live at the moment). Switching the whole of my desktop into Nepali would twist my brain too much.
But I am not sure that there are many people working in a multilingual environment who want to choose a different language for each app.
The other use is just for testing - e.g. if I could switch ownCloud client to German or... then I could see what the translations looked like without switching my whole desktop to German.

**Comment by tflidd** [comment]
If a switch is too much, you could just take the language the user has chosen in his profile (of owncloud). Then it is easy to change it yourself (for demonstration, debugging, ...) and you don't need to provide another switch in the client.

**Comment by danimo** [comment]
For demonstration and debugging it's enough to have LANG (windows) or LANGUAGE (unix) in your environment.

i.e. `LANGUAGE=de owncloud` gives me a german owncloud client.

**Comment by sndbbbl** [comment]
@danimo 
If you work on a Chinese Environment, but the system administrator is from another language, it is useful to help set-up the clients - just an example.

**Comment by danimo** [comment]
That's all solved with above variable setting. It may not be as convenient, but it works all right and you have to admit that this _really_ is an edge case. Closing.
