### ISSUE TITLE
[10.10] [OS X] Desktop Client Share Feature opening in background when settings dialog is open and other Window covers settings dialog

### ISSUE THREAD

**Issue by ajpdmiv** [owncloud/client#3783]
The Share with own cloud does not pop up a dialog box. I am currently using: iMac (21.5-inch, Late 2009), OS X 10.10.5

**Comment by guruz** [comment]
@ajpdmiv But you have the menu item in the menu?
Do you see the green/yellow/red overlay icons over files though?

**Comment by stonerl** [comment]
@guruz I observed something similar on OSX.

1. Open the ownCloud Settings Window.
2. Don't close the Window but switch to another application that covers the Settings Window completely.
3. Open Finder, select a file and click on "Share with ownCloud".
4. No Sharing Window appears.

In fact the sharing Windows gets opened, but in the Background. When on goes back to the ownCloud Settings Window and uses the App Exposé you can see the ownCloud Settings Window and the Sharing Window.

This doesn't happen when the Settings Window is closed. But there is a general problem with the sharing Window. As soon as you click another Window the Sharing Window vanishes in the background. One cannot CMD-TAB to get it back. The only way to get this window back is through Mission Control.

**Comment by dragotin** [comment]
Seems to be a fail of `ownCloudGui::raiseDialog( QWidget *raiseWidget )` on MacOSX. @jturcotte ideas?

**Comment by jturcotte** [comment]
I haven't investigated OS X throughly, but my guess is that the window manager protects the user from background applications taking the front without the user asking. And this is what happens in this case, we cheat by having Finder asking the ownCloud client to show a popup to the user through a socket rather than a normal input event handler of the process currently having the user's focus.

See https://github.com/owncloud/client/issues/3015 for a similar issue on Windows.

Still worth verifying on OS X though. http://stackoverflow.com/a/2767236/56315 mentions that we could also try [window setLevel:NSFloatingWindowLevel]; in addition to activateIgnoringOtherApps and makeKeyAndOrderFront, but that would make the dialog always floating and the user wouldn't be able to put anything in front of that dialog.

**Comment by Dianafg76** [comment]
I can't reproduce.
@stonerl, @ajpdmiv you could try this version: http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.2722-nightly20150918.pkg
Thanks

**Comment by stonerl** [comment]
Downloaded the nightly. And the first part is fixed. The sharing window won't open in the background when the settings window is open.

The second part is still there somehow, but since the window accessible through Mission Control, now it isn't that kind of a problem anymore.

**Comment by Dianafg76** [comment]
@stonerl Thanks

**Comment by stonerl** [comment]
@Dianafg76 You're welcome.

**Comment by ajpdmiv** [comment]
thanks to everyone.


*Autry J. Pruitt* - Creative Director & Founder
urrepublic.com |1205 Rio Grande Street |Austin, TX 78701 | 202.888.7864
facebook.com/urrepublic | twitter.com/autry |twitter.com/urrepublicmedia

*THIS MESSAGE AND ANY ATTACHMENTS ARE CONFIDENTIAL, PROPRIETARY, AND MAY BE
PRIVILEGED. If this message was misdirected, UrRepublic, Inc. and its
subsidiaries, ("UrRepublic") does not waive any confidentiality or
privilege. If you are not the intended recipient, please notify us
immediately and destroy the message without disclosing its contents to
anyone. Any distribution, use or copying of this e-mail or the information
it contains by other than an intended recipient is unauthorized. The views
and opinions expressed in this e-mail message are the author's own and may
not reflect the views and opinions of UrRepublic, unless the author is
authorized by UrRepublic to express such views or opinions on its behalf.
All email sent to or from this address is subject to electronic storage and
review by UrRepublic. Although UrRepublic operates anti-virus programs, it
does not accept responsibility for any damage whatsoever caused by viruses
being passed.*


On Fri, Sep 18, 2015 at 2:21 AM, Dianafg76 <notifications@github.com> wrote:

> I can't reproduce.
> @stonerl <https://github.com/stonerl>, @ajpdmiv
> <https://github.com/ajpdmiv> you could try this version:
> http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.2722-nightly20150918.pkg
> Thanks
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/3783#issuecomment-141368516>.
>

-- 
THIS MESSAGE AND ANY ATTACHMENTS ARE CONFIDENTIAL, PROPRIETARY, AND MAY BE 
PRIVILEGED. If this message was misdirected, UrRepublic, Inc. and its 
subsidiaries, ("UrRepublic") does not waive any confidentiality or 
privilege. If you are not the intended recipient, please notify us 
immediately and destroy the message without disclosing its contents to 
anyone. Any distribution, use or copying of this e-mail or the information 
it contains by other than an intended recipient is unauthorized. The views 
and opinions expressed in this e-mail message are the author's own and may 
not reflect the views and opinions of UrRepublic, unless the author is 
authorized by UrRepublic to express such views or opinions on its behalf. 
All email sent to or from this address is subject to electronic storage and 
review by UrRepublic. Although UrRepublic operates anti-virus programs, it 
does not accept responsibility for any damage whatsoever caused by viruses 
being passed.
