### ISSUE TITLE
[Windows][2.0.1] Share Folder Link - Allow editing not available

### ISSUE THREAD

**Issue by RubenGarcia2081** [owncloud/client#3784]
When sharing a folder via context menu in Windows explorer (Share with ownCloud), the option "Allow editing" is not available. In the web interface this option is available. And it looks like, that the needed flag is as well available in the OCS Share API -> publicUpload.

Would be great, if "Allow editing" can be directly set from the "Share with ownCloud" dialogue.

Many thanks in advance for your support!

**Comment by rullzer** [comment]
PR already available for review #3661

**Comment by rullzer** [comment]
PR is merged so closing this.

**Comment by buergerjochen** [comment]
Hello,
Allow Editing Link is available but with such a link only upload and download is possible.
Thank You for supporting.
