### ISSUE TITLE
[Windows][2.0.1] Explorer Integration not working

### ISSUE THREAD

**Issue by seligmanns** [owncloud/client#3785]
I'm running owncloud server 8.1.1 and installed 5 Windows clients.
On one of these Windows 7 machines (x64 - Enterprise) I'm not able to get the explorer extensions working: No icon overlays - no context menu entries.
I checked the Windows eventlogs and found nothing. Restarts and fresh installations in any combination did not work on this machine.
Are there any further logs I could check?

**Comment by guruz** [comment]
Did you check the registry if other applications are using "too many" overlay icons?

Should be in ```Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers``` I think

**Comment by seligmanns** [comment]
I found some entries not needed anymore (aerofs, tortoisesvn) and removed them. This didn't change anything (reinstalled owncloud client afterwards). As I mentioned the context menu functionality is missing too.
It seems as if the owncloud client is not able to assure windows that this is a owncloud folder
![shelloverlayicons](https://cloud.githubusercontent.com/assets/14193724/9807395/f1cddde4-5852-11e5-9a40-e7aff7a2bef5.PNG)

**Comment by guruz** [comment]
Did you try running owncloud with log file to see if something is going on there (keyword is "socketAPI")

**Comment by seligmanns** [comment]
Every time I'm rightclicking a folder these lines are logged:

10-20 15:15:38:137 0x798258 OCC::SocketApi::slotNewConnection: SocketApi:
New connection QLocalSocket(0xa910580)

10-20 15:15:38:137 0x798258 OCC::SocketApi::sendMessage: SocketApi: Sending
message: "REGISTER_PATH:D:\Users\seligmanns\ownCloud\"

10-20 15:15:38:138 0x798258 OCC::SocketApi::sendMessage: SocketApi: Sending
message: "SHARE_MENU_TITLE:Via ownCloud teilen"

10-20 15:15:38:187 0x798258 OCC::SocketApi::onLostConnection: SocketApi:
Lost connection QLocalSocket(0xa910580)

2015-10-20 14:58 GMT+02:00 Markus Goetz <notifications@github.com>:

> Did you try running owncloud with log file to see if something is going on
> there (keyword is "socketAPI")
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/owncloud/client/issues/3785#issuecomment-149560188>.
>



-- 
Stefan Seligmann
---
Alpenblickstraße 13
D-83679 Sachsenkam
tel: +49 8021 90505
fax: +49 8021 90548
mobil: +49 177 3041967

**Comment by dragotin** [comment]
hmm, seems like the connection via socket is not working properly. Do have anything  running that prevents that? Maybe Firewalls or "Security Software" does that? I don't know.

**Comment by seligmanns** [comment]
Symantec Endpoint Protection is installed (Antivirus only).
Windows Firewall.

**Comment by guruz** [comment]
@seligmanns So if you disable those, reboot and try again, does it work or not?

**Comment by seligmanns** [comment]
no, it doesn't

**Comment by guruz** [comment]
Have you tried 2.1beta1?

**Comment by ogoffart** [comment]
And does the "share with owncloud" option work?
Please try 2.1

**Comment by tipichris** [comment]
I have the same issue. The "Share with ownCloud" option does work, but I see no overlay icons and the OC folder is difficult to find, not given a prominent position in Explorer as Dropbox and OneDrive are. The registry entries look odd—there is a leading space in front of each key name, eg 
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers\  OCOK`
Looking at the screengrab above, the same appears to be true there. This is 2.1.0 (build 5683) on Windows 10, one installation on W10 Home, one on W10 Pro.

**Comment by Dianafg76** [comment]
@tipichris Could you please try 2.1.1 (rc2 or the release which come today). Thanks
I tested this issue and I can see the overly icons
![win10v211rc2](https://cloud.githubusercontent.com/assets/12032058/12941154/00545b46-cfd0-11e5-969c-e08028c8a2b7.PNG)
Desktop v 2.1.1rc2
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}

**Comment by tipichris** [comment]
Oddly, this seemed to resolve spontaneously on both Windows machines I have OC on. Sometimes the overlay icons are slow to appear and I may just have been being impatient. I have just installed 2.1.1 on one machine.

There are some minor issues. Where a synced folder is pinned to the Quick Access area no overlay icon appears. Also, the "Share with ownCloud" context menu option is not available for the top level of a Folder Sync Connection. For example, I have one connection that syncs /Templates on the server with C:\Users\myname\MyTemplates. The "Share with ownCloud" option is not available on C:\Users\myname\MyTemplates, but is available on individual files in that folder, and on subfolders of it.
