### ISSUE TITLE
Owncloud Sync no Folder-Content in "(do-t)hidden" folder 

### ISSUE THREAD

**Issue by belerofon** [owncloud/client#3786]
Hi,
since a couple of day, the content of an holder where not sync. The Name of de folder begin with a "." (dot). If i rename it, all content will be sync. If I create an new "."-Folder only the folder will be created on the server, but this folder is on the server-side empty (so the Problem is reproducible).

Currently I use the Client Version 2.0.1 (build 2694)

**Comment by dragotin** [comment]
The clients handling of dot files (hidden files) has changed with 2.0.0, they're not longer synced by default. BUT there is a setting where you can switch it on in the settings dialog.
