### ISSUE TITLE
Win 2.0.1 (5446) - network UNC path broken (CSync error accessing \\SERVER\SHARE)

### ISSUE THREAD

**Issue by giobatta** [owncloud/client#3788]
Latest version breaks UNC functionality in Win Client. I do not know if CSYNC patch of 5 days ago introduces or sorts the issue out.

**Comment by giobatta** [comment]
I refer to : csync io: Fix UNC path conversion on Win #3748

**Comment by danimo** [comment]
Duplicate of #3748

**Comment by danimo** [comment]
@giobatta It fixes the issue

**Comment by giobatta** [comment]
ok
