### ISSUE TITLE
[10.10][OSX] Finder Plugin popup window issues

### ISSUE THREAD

**Issue by mcnesium** [owncloud/client#3791]
![bildschirmfoto 2015-09-09 um 16 53 39](https://cloud.githubusercontent.com/assets/476060/9765366/36220334-5714-11e5-81e2-6053c92d8106.png)

* OSX 10.10
* oc client 2.0.1

Steps to reproduce: right-click on a file in a synced folder and choose "share via owncloud"
* no "share with [user]" option
* "share link" is always checked
* there is no link to be copied anywhere
* its not possible to uncheck the password option
* if that window is cmd-tabbed to the background, it is gone and has to be recreated using right-click procedure again
* if "share link" is unchecked, the following error message appears: 

![bildschirmfoto 2015-09-09 um 17 04 50](https://cloud.githubusercontent.com/assets/476060/9765529/f47945ae-5714-11e5-9e30-15200be90f51.png)

**Comment by guruz** [comment]
What error (if any) you see if you run the client with ```/Applications/owncloud.app/Contents/MacOS/owncloud --logfile -``` ?
Which server version?

**Comment by guruz** [comment]
@mcnesium For the window issue you can subscribe to https://github.com/owncloud/client/issues/3783 :)

**Comment by guruz** [comment]
@mcnesium  Have you tried the workaround described in https://github.com/owncloud/client/issues/3703#issuecomment-136152864 ?

**Comment by guruz** [comment]
@mcnesium Any luck?

**Comment by mcnesium** [comment]
@guruz From that comment I can't see what settings exactly to toggle. But after upgrading the server to 8.1.3 and rebooting the client system, it looks like it's working properly. Thank you :+1:
