### ISSUE TITLE
UI: Delete the Error message?

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#3793]
This screenshot shows a problem: 
![err_msg_delete](https://cloud.githubusercontent.com/assets/1070214/9766492/7b8d734a-5719-11e5-820e-bbf88c9e24b0.png)

The problem is that the Delete-Button gives the impression that one could delete the error message. However, the button would delete the entire account, *not* the error message.

@jancborchardt

**Comment by jancborchardt** [comment]
The button should be correctly labeled »Remove account« or »Remove sync connection«.
