### ISSUE TITLE
[Windows] Scroll arrows on settings dialog toolbar does nothing

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3795]
1) Add a few accounts to the ownCloud client (I have 4 in my example)
2) Reduce the width of the GUI window so the account icons plus "Activity" "General" and "Network" do not all fit.
3) A nice little >> appears on the right hand side. It looks like it should scroll (or do something):
![topscroll](https://cloud.githubusercontent.com/assets/1535615/9766901/200af502-573b-11e5-9281-a8fe748226ec.png)
4) Click the >> widget.
Expected behaviour: maybe the top row of icons will scroll across or?
Actual behaviour: Nothing happens

**Comment by phil-davis** [comment]
To get to the "Network" settings you have to widen the display. I wonder what happens if you have 20 accounts and they just do not fit across the screen at all.

**Comment by danimo** [comment]
Our collection of neat little hacks is slowly comming to an end I guess. We could see about using a proxy style instead of the CSS hacks and manual work-arounds. Opinions, @jturcotte @ogoffart ?

**Comment by ogoffart** [comment]
Should be fixed by 42a6b242c770d46dbd650b7f314f3bb8a65d1233

**Comment by phil-davis** [comment]
Version 2.1.0-nightly20151027 (build 5584) on Windows10
When I make the window narrow, it shows just the icons that it can. Others "to the right" are not visible. There is no scrolling facility that I can see.
Is there something else that should be seen and tested?

**Comment by Dianafg76** [comment]
On Windows 2008 to also
Desktop v ownCloud-2.1.0.5584-nightly20151027-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

**Comment by ogoffart** [comment]
For some reason, the little arrow (that looked like `»` in your first screenshot)  is now only looking like `.` on windows.  (But for me on linux it works)

**Comment by phil-davis** [comment]
After cleaning my screen I can see that it is not just a fleck of dust ;)
Yes, clicking the "dot" shows a list of the not visible items, from which I can successfully select.
![owncloudx](https://cloud.githubusercontent.com/assets/1535615/10758109/54c7a86e-7cd7-11e5-98d7-314ac56e6a39.png)

**Comment by ogoffart** [comment]
A adjusted the stylesheet and now it should show the extension for all style again.

**Comment by phil-davis** [comment]
Version 2.1.0-nightly20151028 (build 5586) on Windows10
Works now, thanks.
![owncloudx1](https://cloud.githubusercontent.com/assets/1535615/10778155/04faba78-7d4b-11e5-85eb-472719b658c8.png)
