### ISSUE TITLE
UI: "Could not read system exclude file" message too subtle since 2.0.0

### ISSUE THREAD

**Issue by alfski** [owncloud/client#3796]
Hi, the sync error message "Could not read system exclude file" is displayed very differently the Mac client and the Windows client.

I'm sure we can agree the Mac alert is much superior for troubleshooting purposes!

![syncerror-winvsmac](https://cloud.githubusercontent.com/assets/979009/9778074/fae01d92-57ae-11e5-89ff-c031b40a5ae1.jpg)

**Comment by danimo** [comment]
@alfski This is not about Windows vs Mac, but 1.8.x (on Mac) vs 2.0.0/2.0.1 (Windows). Please check the versions in the General tab.

**Comment by alfski** [comment]
Hi, thanks @danimo I wasn't able to reproduce this error on a Mac device, so I just pinched a screenshot from an old forum post and made a poor guess that it was Mac vs Windows UI thing. I presume these types of sync errors/alerts now not-in-your-face on ALL platforms.

**Comment by danimo** [comment]
@jancborchardt pls

**Comment by jancborchardt** [comment]
Indeed that is not sufficient as error feedback. The error message should be in red type and same size as the other text above. Also, the progress bar doesn’t need to show then, right?

**Comment by guruz** [comment]
Low prio as this looks like a unlikely installation-caused issue.

**Comment by jancborchardt** [comment]
@guruz so the other crucial errors are more presently visible?

**Comment by guruz** [comment]
yep, should for sure be :)

**Comment by guruz** [comment]
@jturcotte You got that error message now after fix for https://github.com/owncloud/client/commit/2e7a3f9e379ab237105116f6bcf50df269baf62f right?

**Comment by jturcotte** [comment]
Yes, but before that commit the error message was just completely absent. The bug report is older than the commit that introduced the regression.

I wouldn't say that other error message look any better though:
![screen shot 2016-01-04 at 18 44 34](https://cloud.githubusercontent.com/assets/839935/12096100/5ba8a224-b313-11e5-9af0-1c049b4b7862.png)

**Comment by jancborchardt** [comment]
Yeah, especially with the whole URL there (unnecessary) and the overly technical language:

> Server replied: Bad request

We need to use more understandable language and maybe even offer people a pointer on what to do now.

> Server could not be reached.

Or

> File could not be downloaded.


Also

> System exclude file could not be read

– but what does that exactly mean? Is this a grave error? What is the exclude file – the one the ownCloud client provides? Why could it not be read then?

**Comment by jturcotte** [comment]
Errors should look like in the "Better" screenshot again now.

**Comment by Dianafg76** [comment]
I tested this issue and now the error message appears in red type and same size as the other text above
Desktop v ownCloud-2.1.1.3014-nightly20160107.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}

Closed
