### ISSUE TITLE
[OS X 10.11] Settings window has black tool bar from time to time

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/client#3798]
### Expected behaviour

Settings window should be displayed correctly on OS X 10.11
### Actual behaviour

The menu of the settings window looks garbled on OS X 10.11 from time to time. Restarting the client helps.

![2015-09-10_11-55-50](https://cloud.githubusercontent.com/assets/878997/9785480/042a86c2-57b3-11e5-985f-d22904b99d95.png)
### Steps to reproduce

Not sure. It only happens from time to time.
### Client configuration

Client version: 2.0.1

Operating system: OS X 10.11

OS language: English

Installation path of client: /Applications/owncloud.app

**Comment by guruz** [comment]
@lmaestro is this your eternal bug? What was the number? :)

**Comment by lmaestro** [comment]
@guruz Of course it is. 
@LukasReschke  it's duplicated https://github.com/owncloud/client/issues/1947

**Comment by saphirblanc** [comment]
Hello!

I do have the same problem. How can I help to solve this bug ?
Thank you,

Yann

<img width="565" alt="owncloud_and__os_x_10_11__settings_window_has_black_tool_bar_from_time_to_time_ _issue__3798_ _owncloud_client" src="https://cloud.githubusercontent.com/assets/16269066/11762928/27051472-a0f7-11e5-82fa-7cebd430b8bd.png">

**Comment by MorrisJobke** [comment]
@guruz I have this also quite often - feel free to provide me with steps to help you solving this :)

**Comment by hodyroff** [comment]
still happening with 2.3?

**Comment by MorrisJobke** [comment]
@hodyroff I haven't seen this for a while so it seems to be fixed now. 👍
