### ISSUE TITLE
Update client documentation for 2.0.2

### ISSUE THREAD

**Issue by danimo** [owncloud/client#3804]
Sorry Carla, we have made quite some adjustments to the new UI as it wasn't as user friendly as we had hoped. Could you revisit the UI during the next week or so? (i.e. not right now, as we're still making changes).

**Comment by carlaschroder** [comment]
Aye capn Dan!

**Comment by danimo** [comment]
:+1:

**Comment by phil-davis** [comment]
Things that come to mind right away are:
- Add Account has a whole new/different starting point the first time.
- Sign in/out -> Log in/out
- The Delete button for deleting an account changed
- Remove folder -> Remove sync

**Comment by carlaschroder** [comment]
Not sure why this is still open, or has a sev1-critical label. AFAIK everything is in the manual is current.

**Comment by carlaschroder** [comment]
@danimo

**Comment by phil-davis** [comment]
https://doc.owncloud.org/desktop/2.0/navigating.html
"The little button with three dots that sits to the right of the sync status bar offers three additional options:"
Actually it has 4 options - it also has "Choose what to sync".
I will make a pull request to fix that...

**Comment by carlaschroder** [comment]
Ha. They sneaked that in later, @phil-davis
