### ISSUE TITLE
ocupdater.h meaning of comment

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3809]
https://github.com/owncloud/client/blob/master/src/gui/updater/ocupdater.h#L163
"The implementation does how show popups"

What is that intended to mean?
"The implementation does now show popups" == "The implementation shows popups"
or
"The implementation does not show popups"
or
???

**Comment by guruz** [comment]
Try ```git blame src/gui/updater/ocupdater.h``` :-)

**Comment by phil-davis** [comment]
Good thought - in a previous version it used to say:
"Does not do popups"

**Comment by guruz** [comment]
Thanks, closing this in favor of your PR
