### ISSUE TITLE
Error "CSync failed to access" after update to 2.0.1

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#3811]
### Steps to reproduce
1. Update an existing ownCloud 1.8.4 installation to version 2.0.1

### Expected behaviour
Sync should still work.

### Actual behaviour
The GUI signals "failed" for 5 of 8 folders. Error message: `CSync failed to access` (German: `CSync-Zugriff fehlgeschlagen`)

#### ownCloud client log
For each failed folder for I see a log entry like this:
```
09-11 12:45:35:226 0x3b7900 OCC::FolderMan::addFolderInternal: Adding folder to Folder Map  OCC::Folder(0x6710150)
09-11 12:45:35:226 0x66e9130 OCC::WatcherThread::watchChanges: void OCC::WatcherThread::watchChanges(size_t, bool*) Failed to create handle for "f:\owncloud\Media\/" , error: 123
```
Maybe also relevant:
```
09-11 12:45:38:559 0x3b7900 OCC::SyncEngine::handleSyncError:  #### ERROR during  csync_update :  "CSync-Zugriff fehlgeschlagen f:\owncloud\Media\"
09-11 12:45:38:559 0x3b7900 OCC::SyncEngine::finalize: CSync run took  14
09-11 12:45:38:559 0x3b7900 OCC::Folder::slotSyncFinished:  - client version 2.0.1 (build 5446)  Qt 5.4.0  SSL  OpenSSL 1.0.2d 9 Jul 2015
09-11 12:45:38:559 0x3b7900 OCC::Folder::slotSyncFinished: -> SyncEngine finished with ERROR, warn count is 0
09-11 12:45:38:575 0x3b7900 OCC::Folder::bubbleUpSyncResult: Processing result list and logging took  2  Milliseconds.
09-11 12:45:38:575 0x3b7900 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result:  2
09-11 12:45:38:575 0x3b7900 OCC::Folder::slotSyncFinished:   ** error Strings:  ("CSync-Zugriff fehlgeschlagen f:\owncloud\Media\")
09-11 12:45:38:575 0x3b7900 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
09-11 12:45:38:575 0x3b7900 OCC::Folder::slotSyncFinished: the last 1 syncs failed
09-11 12:45:38:575 0x3b7900 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:F:\owncloud\Media\"
09-11 12:45:38:575 0x3b7900 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:F:\owncloud\Media\"
09-11 12:45:38:575 0x3b7900 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:F:\owncloud\Media\"
09-11 12:45:38:575 0x3b7900 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:F:\owncloud\Media\"
09-11 12:45:38:575 0x3b7900 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "Media" :  "Error"
09-11 12:45:38:775 0x3b7900 OCC::FolderMan::slotFolderSyncFinished: <===================================== sync finished for  "Media"
```

Note: All my other folders are also stored at same location (`f:\owncloud`).

**Comment by LukeOwncloud** [comment]
Found the problem:

All failed folders were configured with traling backlash `\`

E.g. `%localappdata%\ownCloud\folders\Media`

```
[Media]
localPath=f:\\owncloud\\Media\\
...
```

Removing the (double) backslash at end of path, solves the problem.

**Comment by LukeOwncloud** [comment]
Found something interesting:

All failed folders were configured with traling backlash `\`

E.g. `%localappdata%\ownCloud\folders\Media`

```
[Media]
localPath=f:\\owncloud\\Media\\
...
```

Removing the (double) backslash at end of path, however, does NOT solve the problem.

**Comment by dragotin** [comment]
@LukeOwncloud how about changing the path to `f:/owncloud/Media` in the config files?

**Comment by LukeOwncloud** [comment]
I just noticed that in `owncloud.cfg` that are also paths (like `0\Folders\Media\localPath=...`). I removed the trailing backslashes here as well. Now it works!

**Comment by guruz** [comment]
@ogoffart Didn't you mention something about this in the last days?

**Comment by ogoffart** [comment]
Peraps duplicated of https://github.com/owncloud/client/issues/3707

**Comment by LukeOwncloud** [comment]
@ogoffart Yes and no, that issue is also about a misconfigured `owncloud.cfg`, however, in that case - as I understand - the update process made some bad changes. I my case - I am pretty sure - the paths already had trailing backslashes before updating to 2.0.1.

PS: IMO it would be best, to accept only normalized path when creating a new sync folder using the GUI. I my case, I just copied a path from TotalCommander (which uses trailing backslashes for folders) to the path text field (I did thus not use the choose dialog). This path was accepted as is causing the late side effects.
This would not solve my problem right now, but it would prevent others having similar problems in the future.

**Comment by ckamm** [comment]
@LukeOwncloud Could you describe what kind of change you did precisely to your owncloud.cfg?

`0\Folders\Media\localPath=f:/owncloud/media//` to `0\Folders\Media\localPath=f:/owncloud/media/` ? We could add code that fixes up bad configuration on startup, but I'm not yet sure I understand the problem fully.

**Comment by ckamm** [comment]
Ah, I can reproduce it. In a path with actual backslashes, having a trailing backslash is a problem.

**Comment by Dianafg76** [comment]
Update an existing ownCloud 1.8.4 installation to version 2.0.2 (ownCloud-2.0.2.2722-nightly20150918.pkg) it is working OK for my

**Comment by LukeOwncloud** [comment]
Second confirmation: My old (previously broken config file) works with `ownCloud-2.0.2.5474-nightly20150918-setup.exe`.
