### ISSUE TITLE
[Windows] client wont synchronise if My Documents folder contains symbolic links

### ISSUE THREAD

**Issue by blanik** [owncloud/client#3813]
### Expected behaviour
Upgraded windows client from 1.8.3 to 2.0.1 , expected to sync as before.

### Actual behaviour
Client discovers messages, then stops with a red X. Nothing in activity log.

### Steps to reproduce
1. Upgrade/Install? windows client, point local folder to 'My Documents', sync fails if symlinks exist in this folder.
removing symlinks as per https://forum.owncloud.org/viewtopic.php?t=30115&p=95204 resolves the issue.

### Client configuration
Client version: 2.0.1

Operating system: Windows 10

OS language: English UK

Installation path of client: C;/program files/owncloud

**Comment by danimo** [comment]
@ogoffart Please take a look.

**Comment by neopaws** [comment]
I have the same problem. had to:
 junction.exe -d "%HOMEPATH%/Documents/My Music"

but doing this on every machine where the client is installed is annoying and unnecessary.

**Comment by dragotin** [comment]
@neopaws sure, we're seeing a bug here that needs to be fixed.

**Comment by guruz** [comment]
So you are deleting the symlinks _inside_ the directory you want to sync?

I guess this is related to the new 2.0 Windows vio..

**Comment by blanik** [comment]
I deleted the 3 symlinks that I knew existed in the root 'My Documents'
folder, I don't believe there were any symlinks in the sub folders.

1.8.3 & 1.8.4 were working OK under Windows 10, so it soes look like the
upgrade to 2.0.1 caused this issue.

**Comment by ckamm** [comment]
@neopaws Are you also on Windows 10?

Do older windows versions also have these standard junction points (?) in 'My Documents'?

**Comment by phil-davis** [comment]
In Windows XP and earlier (My) Documents contained real folders (My) Music, (My) Pictures and (My) Videos.
In Vista these 3 folders were moved to be siblings of (My) Documents. And at some point "My " was removed from the actual real names of the folders.
Along the way, shortcuts were provided in Documents to Music, Pictures and Videos for the convenience of old WinXP users.
I checked on a Windows7 system and it has no shortcuts in the Documents folder.
But on my Windows 10 system I have Music, Pictures and Videos shortcuts in the Documents folder.
So I am not sure what comes from upgrading and old policies and... and what is the standard default for Windows7 and Wimdows10.
In any case, there will be people on Vista, Win7, Win8/8.1 and Win10 who have these shortcuts - either by default or they put them there themselves.

**Comment by blanik** [comment]
I just checked a Windwos 8.1 machine and there are no symlinks in the
Documents folder, but not sure if this is the default or they have been
previously removed. All the other computers have been updated to W10 so
can't check any others.

**Comment by learningdaily** [comment]
I've got about 20 users on Windows 7 which were affected by the 2.0.X client and the symlinks (junction) issue.  All had 'My Music', 'My Videos', 'My Pictures', junction links within their 'Documents' (or junction 'My Documents' folder).  I was checking by running the following within a command window on that directory:

<code>c:\users\username\documents>dir /AL /S</code>

At the very least, ownCloud should still be able to sync the directory containing the symlink(junction) but maybe it could give a warning that the directory contains 'symlinks or junctions which will not be synced'

**Comment by phil-davis** [comment]
I tried to replicate this outside of "My Documents". I did:
1) mklink /D       (makes a directory symlink)
2) mklink /J        (makes a directory junction point)
3) Paste an ordinary shortcut
into an ordinary folder that is in an ordinary folder sync connection.

For items (1) and (2), the folder syncs to the server including any files in the folder it links to. Item (3) the shortcut syncs up to the server as a *.lnk file - no following of the link (that is OK). Other files in the parent folder continue to sync.

So there is something more special about the junction point symlinks that are in My Documents.

**Comment by ckamm** [comment]
Thanks for trying to reproduce this @phil-davis, I may also have time to investigate tomorrow.

**Comment by phil-davis** [comment]
@ckamm I will need to mess around at work tomorrow where I have test systems I can play with. Currently I do not have a sync connection using My Documents, and I am a bit reluctant to mess up my home settings.
Anyone else who wants to try "mklink /D" and "mklink /J" in My Documents and sync it - feel free!

**Comment by neopaws** [comment]
@ckamm I am on Windows 8.1 Pro.  

And all though I do NOT see the symlinks in explorer even with "Show hidden folders," running junction fixed my issue.

**Comment by phil-davis** [comment]
I can't replicate this even on my Documents folder on Windows10. I have some junction points already in there (I now realise how they came - this profile on our domain comes from some time ago when we had a group policy that maintained backward-compatibility with the WindowsXP way). They look like:
```
C:\Users\phil.davis\Documents>dir /AL
 Volume in drive C has no label.
 Volume Serial Number is 2E77-964A

 Directory of C:\Users\phil.davis\Documents

07/31/2015  07:32 PM    <JUNCTION>     My Music [C:\Users\phil.davis\Music]
07/31/2015  07:32 PM    <JUNCTION>     My Pictures [C:\Users\phil.davis\Pictures]
07/31/2015  07:32 PM    <JUNCTION>     My Videos [C:\Users\phil.davis\Videos]
               0 File(s)              0 bytes
               3 Dir(s)  45,716,201,472 bytes free
```
I added a folder sync connection between a folder on the server and C:\Users\phil.davis\Documents
The Documents folder tree synced up to the server fine. The Activity Log just has the expected informational messages about $RECYCLE.BIN desktop.ini and the Junction points themselves. All the ordinary files sync fine.
I have tried adding files and folders both on the server and client and they promptly sync to the other.
![a](https://cloud.githubusercontent.com/assets/1535615/9957942/5b3a34ae-5e24-11e5-90dd-1ecec684b0a1.png)
Version 2.0.2-nightly20150918 (build 5474)
Hmmm - what to do next. I can't help fault-find if I can't even replicate this on my Windows10 laptop.

**Comment by blanik** [comment]
Just upgraded another windows 10 computer from 1.8.4 to 2.0.1 and the
problem has happened again.

dir /AL /S gives...

 Volume in drive C has no label.
 Volume Serial Number is 6C2D-CF77

 Directory of C:\Users\Martin\Documents

01/02/2015  17:22    <JUNCTION>     My Music [C:\Users\Martin\Music]
01/02/2015  17:22    <JUNCTION>     My Videos [C:\Users\Martin\Videos]
               0 File(s)              0 bytes

     Total Files Listed:
               0 File(s)              0 bytes
               2 Dir(s)  24,890,339,328 bytes free


So can see no difference from Phil! apart from him apparently using 2.0.2

All the computers I've have updated to 2.0.1 were originally updated from
from W7 to W10.
I'll go and try one that was updated from W8.1 to W10 to see if the same
thing happens.

Is there a debug mode that I can turn on to try and help narrow down this
issue.

Martin

**Comment by ckamm** [comment]
@phil-davis I get similar behavior on Windows 7: There are three junction points in the directory, but the client just ignores them.

@blanik Yes, a log file would be helpful. See https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly (start with --logfile mylog.txt) Currently we don't know what exactly is going wrong.

**Comment by phil-davis** [comment]
My laptop was also upgraded from W7 to W10. And I don't see anything in recent 2.0.2 changes since 2.0.1 that would have fixed this issue. So it is still a mystery as to exactly what are the necessary set of conditions to trigger this.

**Comment by blanik** [comment]
I'd rather not publish the full log, but I think the relevant bit is pasted
below.

12:42:02:042 0x8f418b0 csync_ftw: Uniq ID from Database: My Music ->
559bc4f96f841
09-18 12:42:02:042 0x8f418b0 csync_walker: directory:
C:/Users/Martin/Documents/My Music [inode=46714]
09-18 12:42:02:042 0x8f418b0 _csync_detect_update: Database entry found,
compare: 1440911586 <-> 1436271865, etag: 559bc4f96f841 <-> 559bc4f96f841,
inode: 46714 <-> 46714, size: 0 <-> 0, perms:  <-> RDNVCK, ignore: 0
09-18 12:42:02:042 0x8f418b0 _csync_detect_update: file: My Music,
instruction: INSTRUCTION_EVAL <<=
09-18 12:42:02:043 0x8f418b0 csync_ftw: opendir failed for
C:/Users/Martin/Documents/My Music - errno 0
09-18 12:42:02:044 0x8f418b0 csync_statedb_close: sqlite3_close=0
09-18 12:43:59:874 0x4557648 OCC::SyncEngine::handleSyncError:  #### ERROR
during  csync_update :  "Success."
09-18 12:43:59:882 0x4557648 OCC::SyncEngine::finalize: CSync run took
 196915

If I go into explorer, or in dos, I cannot see My Music in a directory
listing for Documents. But c:\users|Martin\Music exists!

**Comment by blanik** [comment]
downgraded to 1.8.4 on the same computer - log entries now look like it can follow the symlink to 'my music' which is empty, and 'my pictures', and the sync is completing successfully.

If anyone wants me to look at the junction points in detail on this machine let me know any commands they want me to run.

09-19 10:36:12:763 0x6f03e40 csync_walker: directory: owncloud://xxxxxx/owncloud/remote.php/webdav/My Music [file_id=00020585oc52jdt6si77]
09-19 10:36:12:763 0x6f03e40 _csync_detect_update: Database entry found, compare: 1436271865 <-> 1436271865, etag: 559bc4f96f841 <-> 559bc4f96f841, inode: 0 <-> 46714, size: 0 <-> 0, perms: RDNVCK <-> RDNVCK
09-19 10:36:12:763 0x6f03e40 _csync_detect_update: Reading from database: My Music
09-19 10:36:12:763 0x6f03e40 _csync_detect_update: file: My Music, instruction: INSTRUCTION_NONE <<=
09-19 10:36:12:775 0x6f03e40 csync_statedb_get_below_path: 0 entries read below path My Music from db.
09-19 10:36:12:776 0x6f03e40 csync_walker: directory: owncloud://xxxxxxx/owncloud/remote.php/webdav/My Pictures [file_id=00020586oc52jdt6si77]
09-19 10:36:12:776 0x6f03e40 _csync_detect_update: Database entry found, compare: 1436703424 <-> 1436703424, etag: 55be2245e44a4 <-> 55be2245e44a4, inode: 0 <-> 49858, size: 0 <-> 0, perms: RDNVCK <-> RDNVCK
09-19 10:36:12:776 0x6f03e40 _csync_detect_update: Reading from database: My Pictures
09-19 10:36:12:776 0x6f03e40 _csync_detect_update: file: My Pictures, instruction: INSTRUCTION_NONE <<=
09-19 10:36:12:946 0x6f03e40 csync_statedb_get_below_path: 283 entries read below path My Pictures from db.

**Comment by bivanecon** [comment]
I have the similar issue, although, I'm not sure the same.
Client Version 2.0.1 (build 5446) on Windows 7 Enterprise (both 32 & 64 bit)
I can't get syncing the folders when local folder to sync is "Documents",  and remote is root (/) of the owncloud folder on server (subfolders leads the same error).   
![error](https://cloud.githubusercontent.com/assets/14369762/9980472/1747bede-5fa4-11e5-961a-57be961ad6e2.jpg).
It seems to be a bug, since I've checked it on different PCs with different users - always the same error. (Others local folders, for example "Owncloud" or "Downloads", are syncing just fine, as expected).
Thank you in advance,
Ivan

**Comment by dragotin** [comment]
ok, here are some findings: The junctions are not accessible and report back "Permission denied" to the discovery code. That alone lead to breaking of the sync with 2.0.1, but *not* longer with 2.0.1+git because we fixed that misbehave with df534753b171f0b714221397e15a0f8e094bdeaf

But why aren't the junctions not discovered as sym links, that we properly ignore to sync? Because of the bug that we forgot to open these in win32 vio_local_stat. 

e7e0e5b57fe0315c79c2f71e428280d74c759304 should fix that.

**Comment by blanik** [comment]
Let me know if you want me to user test the solution, if you can point me to a download link.

**Comment by guruz** [comment]
Please try http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.5493-nightly20150925-setup.exe ?

**Comment by bivanecon** [comment]
Thank you dragotin, blanik and guruz.
Unfortunately I can't check the solution on the same PCs I've observed "misbehaving", until middle next week. But I've reproduced the problem on my home PC. Indeed, nightly build 5493 has solved the specific issue. I do not receive the error as I've described above. Probably, this specific issue can be closed.
But, in order to reproduce the error I configured synchronization as follow:
local folder: c:\Users\user (there is no "junctions" in "My Documents" on my home PC, only in user's profile folders) 
remote folder (actually, subfolder in root of owncloud): test_user (I've created especially to upload user's profile into it)
Although, such configuration is unusual, it should work, I think so.
Eventually, I get another misbehaving of the client (5493):

![1](https://cloud.githubusercontent.com/assets/14369762/10116971/e2cf50cc-644e-11e5-90e6-4202b9ba772d.jpg)

3 folders in red rectangle, I've expected to see inside the folder "user_test". As you can see, client created them directly in owncloud root folder on the server. There is only 3 folder, because I've stopped the syncing immediately after I've discover the problem. I've reconfigured the client, twice, but get the same result. Also this issue, I will be able to reproduce on other computers only next week.

Ivan

**Comment by blanik** [comment]
Updated 1.8.4 to 2.0.2.5493 - all OK.

Now performs the same as the 1.8 version, any files in the 'broken' symlinks are ignored, as are the symlink folders themselves, other files are now syncing normally.

There is a message in the activity tab "symbolic links are not supported in syncing",

Just wondering about the message, it kind of suggests that all symlinks will be ignored, not an issue for me. But is that true, or is it just that broken symlinks are ignored?

**Comment by dragotin** [comment]
ALL symlinks are ignored. As I said before elsewhere: Symlinks are a source of evil.

**Comment by dragotin** [comment]
...when it comes to syncing ;-)

**Comment by Dianafg76** [comment]
I tested this issue and for my with WIN 10 it is working OK
Update 1.8.4 to ownCloud-2.0.2.5499-nightly20150928-setup.exe 
Closed
