### ISSUE TITLE
Client 2.0.1 build 5446 doesn't sync anymore

### ISSUE THREAD

**Issue by netro** [owncloud/client#3815]
Hello,
It's a kind of desesperate message...

I'm using owncloud since it's begining and today i'm quite tired to see that despite your great success (and I hope it will continue !) there are still almost always bugs in your major updates ;-(

My client auto-updated from 1.8.4 to 2.0.1 easily but now syncing a big folder doesn't work anymore..
I get this message "sucess" but nothing is syncing anymore and nothing appears in the activity tab about that failure 
![d2cb42c3c5](https://cloud.githubusercontent.com/assets/1595901/9812639/ee2a95a2-587e-11e5-993d-d24127f74abd.png)

The server is in 8.1.1 stable php5, apache2, Debian

**Comment by netro** [comment]
The only option i have is "pause sync" but the owncloud.exe process consume 0.1% CPU

**Comment by danimo** [comment]
In order to help and track down the problem we need information as described in https://github.com/owncloud/client/blob/master/CONTRIBUTING.md. Especially the log file is important.

**Comment by phil-davis** [comment]
Do you have symlinks in your Documents folder?
Like https://github.com/owncloud/client/issues/3813

**Comment by netro** [comment]
Ok i've tried and it's the same behavior as #3813 ! I removed the hidden symlinks created by default by Windows ("Pictures", "Movies" and "Music") and the sync worked again !
Thanks @phil-davis ! I didn't found this issue :/

**Comment by phil-davis** [comment]
The problem reported in #3813 will still have to be looked at, but at least there is a workaround for those who are happy to remove those symlinks.

**Comment by danimo** [comment]
Thanks @phil-davis, closing this as a duplicate then.
