### ISSUE TITLE
synch files over network-path/unc not work

### ISSUE THREAD

**Issue by awdrfunk** [owncloud/client#3817]
client-version ownCloud-2.0.1.5446
its not possible to synch files over network-path/unc (for example a synlogy-directory like \\SYNODISKSTATION\Daten-Transfer).

with version ownCloud-1.8.4.5267 it works fine without problems.

this issue is under win7, win10 home and win 10

**Comment by RealRancor** [comment]
Hi,

thats very likely a dup of https://github.com/owncloud/client/issues/3788 and https://github.com/owncloud/client/issues/3748. According to https://github.com/owncloud/client/issues/3748 it will be fixed in 2.0.2
