### ISSUE TITLE
[Windows 10] Client doesn't save part of Configuration and does not save password

### ISSUE THREAD

**Issue by Lordi999** [owncloud/client#3820]
I#ve Installed the newest version of the Windows Client (2.0.1.5446) an the Login works, my Files are being downloaded and synced. 

After a Reboot, the Client asks me again for the configuration, it simply doesn't store them...

The same Client on a Windows 7 Professional System works fine...

Client: 
- Windows 10 Pro x64
- oC-Client 2.0.1.5446 (form owncloud.com)

Server:
- Ubuntu 14.04.3 LTS
- oC-Server 8.1.1.3

**Comment by danimo** [comment]
Is this a private installation or are you running on Company setup?

**Comment by Lordi999** [comment]
Private Installation

**Comment by guruz** [comment]
Can you after having set up and syncing check the contents of ```owncloud.cfg```?

**Comment by Lordi999** [comment]
[General]
optionalDesktopNotifications=true


thats all...

**Comment by guruz** [comment]
Is there anything special about where the owncloud.cfg is stored on the windows10 system?
roaming profile? network drive?

**Comment by Lordi999** [comment]
No, im a local Admin on my system, i don't think there is something special on the profile...

**Comment by ckamm** [comment]
@Lordi999 Could you
* Quit Client
* Delete config file
* Start client and configure an account
* Quit Client
* Check if any data got written to the config file?

**Comment by andrewfister** [comment]
I can make another ticket if requested, but I'm experiencing the same thing on my client version 2.0.1 in Ubuntu. The server is the same setup as @Lordi999 has.

**Comment by Dianafg76** [comment]
I'm seeing the same
Desktop v ownCloud-2.0.2.5466-nightly20150916-setup.exe

**Comment by ckamm** [comment]
@andrewfister Thanks for the note, I don't think it's necessary. Hopefully it's the same bug.

**Comment by ckamm** [comment]
Maybe it's related to QSettings file locking not working for some reason? Do you see a hidden .lock file next to the config file after closing the owncloud client?

**Comment by ckamm** [comment]
@andrewfister Which version of Qt are you using? (`owncloud --logfile - | grep 'Using Qt'`)

**Comment by Lordi999** [comment]
@ckamm 

I've tried that, but there is no config-File after that.
The owncloud.cfg is written and also deleted within 1 second...

**Comment by ckamm** [comment]
@Lordi999 How do you know it is deleted? That's very interesting!

**Comment by ckamm** [comment]
There's a new build available that has some extra debug logging: http://download.owncloud.com/desktop/daily/ >=5471. Please try that while generating a logfile (`--logfile my.log`) and look for lines that contain "Saved" - do some of them show a non-zero status?

**Comment by Lordi999** [comment]
I see the File in the folder appering and disappering ^^

I don't know why, but i can't generate a log File..?
I'm starting the Client with ""C:\Program Files (x86)\ownCloud\owncloud.exe" --logfile C:\temp\oclog.log"

But i found a Workaround: Starting the Client for configuration as Administrator and then the Config-File will be created...

**Comment by andrewfister** [comment]
@ckamm The Qt version isn't showing up in the log. However, I can give you the versions installed on Ubuntu 15.04. Also Qt4 is the default chosen by Ubuntu.

Qt4: 4.8.6
Qt5: 5.4.1

**Comment by ckamm** [comment]
Possibly related http://stackoverflow.com/questions/15427095/qsettings-iniformat-file-gets-empty-after-restart

**Comment by ckamm** [comment]
@Lordi999 Try starting the client like this for the log file
```
cd "C:\Program Files (x86)\ownCloud"
owncloud.exe --logfile C:\temp\oclog.log
```

So the config file gets written when you run as administrator? Sounds like there's a permissions issue then! 
* Normally, you see the config file appear briefly in your `$USER\AppData\Local\ownCloud`?
* Can you manually create new files there? 
* When you run as admin, the client writes a file into this folder?
* Can you edit the file normally after the admin-client has created it?

**Comment by Lordi999** [comment]
1.) yes, if i start the client normally, i see the config File appering in this Folder. After that, it's gone
2.) Yes, I can manually create Files there
3.) Yes
4.) Yes

**Comment by dragotin** [comment]
@Lordi999 can you reproduce that? Is it really *never* saving your configs?

**Comment by Lordi999** [comment]
@dragotin Yes, I can reproduce that.
It Just saves my Config on First Startup when i start the Client as Local Administrator

**Comment by ckamm** [comment]
@Lordi999 I'm afraid we still have little idea of what goes wrong. Here are some more questions:
* Once the config file has been created when running as admin, do further saves to the file work when you run as your normal user? (i.e. start as admin, verify config file exists, start as user, add another account or folder, quit, start again - did the change persist?)
* Would you be up for tracing what happens to the config file with the Process Monitor tool (https://technet.microsoft.com/en-us/sysinternals/bb896645) if I give you detailed instructions?

**Comment by ckamm** [comment]
@Lordi999 Could you
* make a new folder C:\Users\<Username>\owncloud-testconf
* make a new shortcut to owncloud.exe
* edit its properties and append `--confdir "c:\users\<Username>\owncloud-testconf"` after owncloud.exe in the "Target" box on the "Shortcut" page?
* run this and observe the files in "owncloud-testconf" at the same time? Does the same thing happen?

**Comment by ckamm** [comment]
@Lordi999 Instructions for Process Monitor:
* Download and install from https://technet.microsoft.com/en-us/sysinternals/bb896645
* Start it
* Go to Filter/Filter... if it didn't pop up automatically
* Set "Path" "contains" "owncloud.cfg" then "include", then click "Add"
* Make sure events are being captured (File/Capture Events is on)
* Start owncloud, the account wizard should come up
* Quit owncloud
* Disable "Capture Events"
* "File/Save...", "Events displayed using current filter"
  once as "Native Process Monitor Format" and once as "Extensible Markup Language"
* Upload these files here

**Comment by andrewfister** [comment]
This issue seems to have resolved for me. What I noticed in my case was that I was registered to the Owncloud PPA for Ubuntu 14.10. I changed it to 15.04 and there was an update available. After installing, owncloud was able keep its configuration.

**Comment by guruz** [comment]
@Lordi999 Hi, any news from you?

@andrewfister Do you see the Qt version in the client settings dialog? That's a good way to check for sure which version it uses (and maybe it switched to Qt5?)

**Comment by Lordi999** [comment]
@ckamm I've tried it with the alternate Config- Folde but the behavior remains.
I cannot attach the Log Files, but here they are: http://cloud.die-stengers.com/index.php/s/pa9hc5jW6ejaCYO

**Comment by ckamm** [comment]
@Lordi999 Great, thanks for those log files!

Preliminary findings:
* The client accesses `Local\oC_test\owncloud.cfg` and `Local\ownCloud\owncloud.cfg`. That's sounds like an unrelated bug. Most of the accesses deal with the path specified in `--confdir`.
* The `owncloud.cfg.lock` file is accessed and created successfully.
* The same goes for the temporaries like `owncloud.cfg.Hp9132`
* However, renaming these to `owncloud.cfg` fails with "Access Denied"!

```
<Operation>SetRenameInformationFile</Operation>
<Path>C:\Users\Lordi\AppData\Local\oC_test\owncloud.cfg.gq9132</Path>
<Result>ACCESS DENIED</Result>
<Detail>ReplaceIfExists: True, FileName: C:\Users\Lordi\AppData\Local\oC_test\owncloud.cfg</Detail>
```

I don't know why that happens. owncloud.cfg does not seem to exist and `Local\oC_test` was created explicitly for this test by @Lordi999. I'm not around this week - any ideas @ogoffart @danimo?

**Comment by ckamm** [comment]
@Lordi999 Unfortunately we've got no idea what's going on and no other reports of this kind have come in. It seems likely that it's an environment issue... Please reopen if you find out more.

**Comment by guruz** [comment]
@Lordi999 FYI please check what is mentioned here: https://github.com/owncloud/client/issues/3914#issuecomment-154446819
