### ISSUE TITLE
maximum nice priority value to not slow down other processes

### ISSUE THREAD

**Issue by guettli** [owncloud/client#3828]
The owncloud desktop client is a background job.

Most other activities (browsing the web, reading mails, watching videos) are more important for the user.

Please run the owncloud desktop client with the max. nice value (at least on linux).

**Comment by danimo** [comment]
IMHO we can't do that by default for several reasons:

1. The client is currently not separated into GUI and worker processes. Therefore setting any priority on will will have a direct impacts on the other. Splitting this is a long time goal, but not happening soon.
2. `nice` only has impact on CPU resources, whereas usually the issues are IO bound (which means influencing the IO scheduler, not the CPU scheduler). We may be able to call `setPriority()` on the threads, but without much success (@ogoffart might know more)
3. This is your use case, we have other users who run the client in situations where they _do_ want maximum performance.

**Comment by guettli** [comment]
On my system (ubuntu desktop 14.04) the owncloud client uses 100% CPU often. That's why I had the idea to create this issue. Here `nice` would help. Setting `ionice` in the same step would be useful.

What do you guess: Looking at al running owncloud deskopt clients. How many are running in background and how many get used interactively. I guess 98% run in background in 2% are actively used. For me the use case is clear: Good background operation is more important. Let's set nice, even if 2% might operate a bit more slow.

You say that there are users who want maximum performance. Yes, I understand that. Up to now the client does create load peaks. I guess they happen before the network transfer. I guess that the overall network transfer won't be slowed down by setting the process nice level. The bottleneck is the network. The nice value would just reduce the CPU load peak.

**Comment by blanik** [comment]
Similarly with the Windows client, it can be quite CPU intensive at times affecting normal use of the laptop. I have installed processtamer to reduce it to low priority but I think it would be good to have a priority option on the settings page.

**Comment by guettli** [comment]
A priority option would be nice. For me sane defaults are more important. For me this is maximum nice and ionice.

**Comment by guettli** [comment]
I looked at this issue again, quoting danimo:

> IMHO we can't do that by default right now for several reasons:

>The client is currently not separated into GUI and worker processes. Therefore setting any priority on will will have a direct impacts on the other. Splitting this is a long time goal, but not happening soon.

Please implement the default use case: the sync process runs in background. How often do you touch the GUI and how often does the sync work in background: I guess using the GUI is around 1% or even less.

Even if you set maximum nice and ionice the GUI is still usable :-) You won't see a difference, except your systems is close to its limit.


>    nice only has impact on CPU resources, whereas usually the issues are IO bound (which means influencing the IO scheduler, not the CPU scheduler). We may be able to call setPriority() on the threads, but without much success (@ogoffart might know more)

There is ionice on linux. AFAIK this works for the whole process, not need to set it on threads. Any reason not to do so?


>    This is your use case, we have other users who run the client in situations where they do want maximum performance.

Please implement the default use case first. In 99% of the time you want to use your computer for other stuff (answering github issues, writing mails, watching videos) and the sync happens in background. Using ionice would not show an impact in most cases, except there is a second process doing noticeable io.

**Comment by guruz** [comment]
The 2.3 client sets the discovery priority lower, maybe this helps already.
#5017

FYI @ckamm 

See also https://github.com/owncloud/client/issues/4268

**Comment by guruz** [comment]
@guettli https://central.owncloud.org/t/desktop-client-2-4-0-alpha1-released/9837

This version should greatly improve the CPU load. Can you try?
