### ISSUE TITLE
Is it possible to restrict access to standard folder?

### ISSUE THREAD

**Issue by Turukano** [owncloud/client#3830]
Hello, we want to install the owncloud client in a Windows domain environment and we do not want users to sync randomly and thereby overextend our storage. We can do this by excluding the owncloud standard-path from the domain profile. 

What I want to ask is this: Is it possible to deny users to add new paths in the sync client?

Thanks, Turu

**Comment by guruz** [comment]
Please comment also on https://github.com/owncloud/client/issues/2688
