### ISSUE TITLE
[Windows] Silent install of ownCloud Client 2.0.1 exits with error code 1223

### ISSUE THREAD

**Issue by feltel** [owncloud/client#3831]
Running setup ownCloud Client for Windows 2.0.1 in silent mode (/S switch) returns error code 1223 upon completion of setup. 2.0.0 setup produces the same error. ownCloud Client 1.8.4.5267 was the last version with working silent setup.

Other than previous versions of ownCloud client I´m not able to do an silent install without getting error code 1223. The install seems to be complete and usable (all files are installed, start menu entries, ...) but running the setup with /S ends with this:

    C:\Users\some.user>echo %errorlevel%
    0
    
    C:\Users\some.user>start /wait w:\owncloud-client\CLIENT_DATA\setup\ownCloud-setup.exe /S
    
    C:\Users\some.user>echo %errorlevel%
    1223

In the above example I´m running the setup while I´m logged in into my workstation (Win 8.1 x64). OPSI, my software deployment tool of choice runs installations as SYSTEM user but installing latest ownCloud client produces the same setup error.

**Comment by phil-davis** [comment]
Note for reference: https://msdn.microsoft.com/en-us/library/windows/desktop/ms681383%28v=vs.85%29.aspx
Windows system error code 1223 is:
ERROR_CANCELLED
    1223 (0x4C7)
    The operation was canceled by the user.

**Comment by dragotin** [comment]
Hmm, ok, thanks.

**Comment by danimo** [comment]
@dragotin Why close? If the operation is silent it was by definition not closed by the user...

**Comment by CroniC-** [comment]
Same problem here. Is there any workaround?

**Comment by Jofagi** [comment]
I have the same problem on Win10 x64.

I get the error regardless of whether I'm overwriting an existing installation or uninstalling first and then running the installer.

I have another system with Win7 x64 where I don't recall having these problems.

**Comment by danimo** [comment]
@Jofagi This is not a Windows 10 issue. We did some changes in the installer recently. This may be a bug in those changes.

**Comment by danimo** [comment]
Please test with nightly builds >= 523

**Comment by Jofagi** [comment]
It's fixed for me. Thank you very much!

    start /wait ownCloud-2.0.2.5523-nightly20151007-setup.exe /S
    >echo %errorlevel%
    0

**Comment by Dianafg76** [comment]
I tested this issue, and for my is not working, when I write the command (start /wait c:\......\ownCloud-2.0.2.5523-nightly20151007-setup.exe /S), I see this error
![screen shot 2015-10-08 at 08 53 25](https://cloud.githubusercontent.com/assets/12032058/10359559/14e15d22-6d9a-11e5-873c-7b474883d9a8.png)

I try with this version ownCloud-2.0.2.5513-nightly20151005-setup.exe, and ejecute the command, I can't see the error. But if I ejecute the command:
>echo %errorlevel%
1223

**Comment by Dianafg76** [comment]
On WINDOWS 10 it is working OK

**Comment by dragotin** [comment]
@Dianafg76 are you sure about the nightly build version in your Win8 test? @danimo said *Please test with nightly builds >= 5523* but you mentioned an older version in https://github.com/owncloud/client/issues/3831#issuecomment-146438901

**Comment by Dianafg76** [comment]
@dragotin, @danimo I try with those two version ownCloud-2.0.2.5523-nightly20151007-setup.exe and ownCloud-2.0.2.5524-nightly20151008-setup.exe, and it is not working

**Comment by danimo** [comment]
so we need to enable magic defines after all, ARG...

**Comment by feltel** [comment]
I can confirm that using the latest nightly build silent setup is now working as expected and does not produce error 1223 anymore.

**Comment by danimo** [comment]
@Dianafg76 Please try build 5529 (about to show up).

**Comment by Dianafg76** [comment]
@danimo I tested this issue with Desktop v ownCloud-2.0.2.5529-nightly20151009-setup.exe and is not working
I see the same error
![screen shot 2015-10-09 at 14 44 25](https://cloud.githubusercontent.com/assets/12032058/10393972/51da727c-6e94-11e5-817e-89e9ea572788.png)

**Comment by danimo** [comment]
@Dianafg76 Please retry with 5531.

**Comment by Dianafg76** [comment]
@danimo I tested again this issue on WINDOWS 8 with Desktop v ownCloud-2.0.2.5533-nightly20151010-setup.exe, and v ownCloud-2.0.2.5538-nightly20151013-setup.exe and is not working :(

![screen shot 2015-10-13 at 09 13 18](https://cloud.githubusercontent.com/assets/12032058/10448134/f10e2caa-718a-11e5-8de6-dc0ca3d1bd32.png)

**Comment by Dianafg76** [comment]
@danimo I tested this issue with different version:
#### WINDOWS version


Windows version    | OK | NOK |
-------------------|----|-----|
Windows 7 Home Premium | OK   |    |
Windows 8.1 Pro | OK   |    |
Windows 2008 R2 Enterprise |    |   NOK |
Windows 10 | OK   |    |

**Comment by CroniC-** [comment]
Tested on Win7 Pro x64

![2015-10-15 08_13_06-administrator_ c__windows_system32_cmd exe - start _wait owncloud-2 0 2 5542-ni](https://cloud.githubusercontent.com/assets/6624442/10506150/03386f4a-7315-11e5-83f5-fb80fd2030d4.jpg)

The "Unable to elevate" error

**Comment by Dianafg76** [comment]
I tested again this issue with Desktop v ownCloud-2.0.2.5544-nightly20151015-setup.exe, on Windows 2008 and it installed OK

**Comment by dragotin** [comment]
build ownCloud-2.0.2.5544-nightly20151015-setup.exe contains a patch that fixes this problem for @Dianafg76 test cases. @CroniC- if you could verify that would be great.

**Comment by Dianafg76** [comment]
@CroniC- Can you test with this version: http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.5544-nightly20151015-setup.exe, please?
Thanks

**Comment by CroniC-** [comment]
Tested again on Win7 Pro x64 - It's working now!
![2015-10-15 10_42_53-administrator_ c__windows_system32_cmd exe](https://cloud.githubusercontent.com/assets/6624442/10508818/a548a822-7329-11e5-93b4-0ad486847a79.jpg)

**Comment by Dianafg76** [comment]
@CroniC- Thanks !!!
