### ISSUE TITLE
2.0.2: In the DESKTOP fill server URL with SHIBBOLETH, Error appears when trying to access

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3833]
### Steps to reproduce
1. Open your onwCloud Desktop client
2. Fill in the server url with shibboleth
3. Accept the certificate
4. Click OK
5. Write the User/password the shibboleth
6. Click Login
7. In Local Folder select for example "Start a clean sync"
8. Click CONNECT

### Expected behaviour
You can connect with the user Shibboleth in oC Desktop
If I make the test with a client SHIB connects correctly

### Actual behaviour
It is appears an error
![screen shot 2015-09-15 at 14 11 50](https://cloud.githubusercontent.com/assets/12032058/9876108/cad7a5ee-5bb3-11e5-8659-9fe200449c9a.png)

### Server configuration
Desktop v ownCloud-2.0.2.2716beta1.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.2.1","versionstring":"8.1.2","edition":"Enterprise"}

**Comment by danimo** [comment]
That's the old issue that we already saw in the tests for 2.0.0 and turned out to be a bug in 8.1.0 server. Please re-test against 8.1.3.

**Comment by Dianafg76** [comment]
I tested with Server v {"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"}, and It appears the same error

**Comment by Dianafg76** [comment]
related https://github.com/owncloud/user_shibboleth/issues/82

**Comment by danimo** [comment]
@Dianafg76 This wa finally fixed in stable81. If possible, retest with a current stable81.

**Comment by danimo** [comment]
Actually, let's move this to #3724
