### ISSUE TITLE
Document OCC_UPDATE_URL

### ISSUE THREAD

**Issue by danimo** [owncloud/client#3834]
This value can be set in the environment of the client to let the client choose a different update URL for testing purposes. Affects both branded and unbranded clients.

**Comment by carlaschroder** [comment]
What do you mean by environment of the client? Is this a setting in the configuration file, or applied with owncloudcmd?

**Comment by guruz** [comment]
@carlaschroder It's the local shell environment.. ```export OCC_UPDATE_URL=https://...``` I guess
It's just for testing, I don't know why @danimo would want it documented :-)

**Comment by danimo** [comment]
@guruz @carlaschroder Because customers would like to use it to check their deployment settings on selected clients first.

**Comment by carlaschroder** [comment]
okee dokee!

**Comment by gig13** [comment]
@LukasReschke @bboule @MTRichards 
Can we review this as a potential security risk?

It seems that if an attacker could set this environment variable and restart the owncloud client, they could have it download their own executable via the update mechanism. This executable could contain anything extra they wanted including code to send username and password somewhere, code to download and install other executables and so on.

**Comment by LukasReschke** [comment]
If an attacker can set environment variables there are far worse things they can do. If an attacker can modify the environments variables how he likes this equals anyways an arbitrary code execution.

I do therefore consider this expected behaviour and not a security risk. Yes, it can be abused that way. But once an attacker is that far they can also execute an evil binary on their own to modify the ownCloud client :)

**Comment by LukasReschke** [comment]
A simple example: 

```
➜  master git:(master) ✗ export PAGER="less;ls -lah"
➜  master git:(master) ✗ man man
➜  master git:(master) ✗ man man
total 1008
drwxr-xr-x     13 root  wheel   442B Sep 14 11:45 .
drwxr-xr-x     47 root  wheel   1.6K Jun 15 20:49 ..
drwxr-xr-x   1631 root  wheel    54K Sep 11 09:47 man1
drwxr-xr-x    241 root  wheel   8.0K Sep 11 09:19 man2
drwxr-xr-x  13114 root  wheel   435K Sep 11 09:19 man3
drwxr-xr-x     39 root  wheel   1.3K Sep 11 09:47 man4
drwxr-xr-x    202 root  wheel   6.7K Sep 11 09:47 man5
drwxr-xr-x      3 root  wheel   102B May 10 07:43 man6
drwxr-xr-x     52 root  wheel   1.7K Sep 11 09:47 man7
drwxr-xr-x    474 root  wheel    16K Sep 11 09:47 man8
drwxr-xr-x     23 root  wheel   782B May 28 05:15 man9
drwxr-xr-x    680 root  wheel    23K Sep 11 09:21 mann
-rw-r--r--      1 root  wheel   502K Sep 14 11:45 whatis
```

**Comment by cmonteroluque** [comment]
https://github.com/owncloud/client/issues/3834#issuecomment-140498701

I agree.

**Comment by moscicki** [comment]
I think that the update mechanism should use a trusted channel over https. Does it do in this way or does it allow to download from arbitrary URL over http? Is the downloaded package digitally signed or can it be anything? For example, in my environment I would require that the packages are downloaded from the server which presents certain certificate, for instance, the same certificate that is used for regular connection (for which I established trust relationship as a user).

**Comment by danimo** [comment]
@moscicki: The URL is HTTPs by default. If you chose to specify a HTTP URL for testing via the variable, that is fine.

The package is supposed to be digitally signed. On Mac, it is additionally secured by a DSA signature (feature of Sparkle) and the package itself is signed, which is checked by GateKeeper before execution. On Windows, The binary is not signed independently, but carries a Authenticode signature. If not, the OS will warn the user.

We do not employ certificate pinning in the client yet. While likely, It is not reasonable to assume that the same cert is being used for both the ownCloud service and the download servers.

**Comment by carlaschroder** [comment]
master: 9036136916a4891f6f2e0baffccb2efaa064b70
stable8.2: ecf8fc68ac87f60a224fe38201ac7459241b598a
stable8.1: 6efb95fceb558e8d97d30e801d7877e2255f3fe1
stable8: 290098d00c7df7ba7be54689916c064f91412f4d

**Comment by carlaschroder** [comment]
oh phooey. Here, have some URLs:
master: https://github.com/owncloud/documentation/commit/9036136916a4891f6f2e0baffccb2efaa064b70f
stable8.2: https://github.com/owncloud/documentation/commit/ecf8fc68ac87f60a224fe38201ac7459241b598a
stable8.1: https://github.com/owncloud/documentation/commit/6efb95fceb558e8d97d30e801d7877e2255f3fe1
stable8: https://github.com/owncloud/documentation/commit/290098d00c7df7ba7be54689916c064f91412f4d
