### ISSUE TITLE
Publicly sharing files with no password doesnt work.

### ISSUE THREAD

**Issue by boschma1** [owncloud/client#3835]
With the current client 2.0.1 for Mac , I can no longer share publicly file from my finder app. Even though the settings in the web app show that public sharing is allowed with no password, the local desktop client doesn't and requires a pw (see screen shot).

Please advise.

![2015-09-15_15-54-18](https://cloud.githubusercontent.com/assets/5564469/9887599/bea21902-5bf0-11e5-865f-ae2ee1fbaacb.png)

**Comment by danimo** [comment]
Please try with 2.0.2 beta1 from https://owncloud.org/install/#testing-development.

**Comment by boschma1** [comment]
Problem is still existing after installation of Beta 1. Sorry.

**Comment by guruz** [comment]
Please try the workaround: https://github.com/owncloud/client/issues/3703#issuecomment-136152864
