### ISSUE TITLE
Parse "maintenance" value in status.php

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3836]
The server 8.1.x does not seem to return HTTP 503 for WebDAV in maintenance mode(?).
For me it returned ```HTTP/1.1 401 Unauthorized``` for a ```PROPFIND```.
We should look at the ```maintenance``` value in ```status.php``` and behave differently if the value is ```true```.

I'm still unsure what exactly happens, but we pop up an authentication dialogue which we shouldn't.

CC @PVince81 @icewind1991 @danimo

**Comment by danimo** [comment]
@guruz well, the server should keep returning 503...

**Comment by danimo** [comment]
Server issue. We won't do a workaround unless it's absolutely necessary.
