### ISSUE TITLE
Show "Unchecked folders will be removed ..." only when relevant

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3839]
Timing:
* It should only show after the list result has been received from server (important for slow connections)

Usefulnes:
* It should only show if there is at least 1 subfolder

FYI @jancborchardt @ogoffart @phil-davis

**Comment by phil-davis** [comment]
That seems quite fussy. That message text only appears when you open the folders to sync tree view. For me the message is there for maybe 1 second until the folder tree appears (client in Nepal to server in Germany).
That said, it wouldn't hurt to only display the message text when the folder tree is actually being displayed - someone has to do the code and testing though.

**Comment by jancborchardt** [comment]
@guruz I totally agree. Thought I had openend an issue about that already, but maybe it was just a comment in an issue.

What I would add is that it should only be shown once there have been changes made in the list which need to be applied – either checking or unchecking.

**Comment by Dianafg76** [comment]
I tested this issue, and I see only the "Unchecked folders will be removed ..." only when relevant.
Only I see when I go to "Choose what to sync" or when you expand the selective sync tree

Desktop v ownCloud-2.1.0.2821-nightly20151022.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}
Closed
