### ISSUE TITLE
Always show checked checkbox with generic file icon and "All files" text in selective sync on each tree level

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3840]
This would make it clear to users that the files in a directory are always synced.
We had quite some confusion here on the issue tracker and other places.

@jancborchardt @MTRichards  How does it sound?

**Comment by MTRichards** [comment]
Do you have an example of what this might look like? Is it just "all files" in addition to the folders inside a given tree level? I think that makes sense, but not sure I understand what you mean entirely.

**Comment by jancborchardt** [comment]
I can see why theoretically this might be useful. However it will be very confusing what »All files« means. Also, when you uncheck it, only the files directly in the parent folder are stopped to sync. Which is really quite strange.

It introduces a new level of complexity to selective sync which I’m not sure we should implement.

**Comment by guruz** [comment]
@MTRichards Yes!

@jancborchardt Should have made that more clear: it should be greyed out/disabled. When you select the folder in any of its direct or indirect subdirectories it gets checked. So that it is implicit to the user that his action will also make him get the files in the parent directories (that's still how the selective sync works right?)

**Comment by jancborchardt** [comment]
Aaah ok. Yeah, that sounds reasonable as feedback. Maybe instead of »All files« it should be labeled »Files directly in this folder« (if that’s not too long).

> So that it is implicit to the user that his action will also make him get the files in the parent directories

About »the user« and »him« – people using ownCloud are many, and not only female. ;)

**Comment by TheOneRing** [comment]
Not planned
