### ISSUE TITLE
Client 2.0.1 (build 5446) loses settings on Windows 10

### ISSUE THREAD

**Issue by nelwa** [owncloud/client#3841]
The client should retain server URL, user name password settings and synced directory settings etc.

Actual behaviour:
After shutdown last night, this morning when I booted, all settings was wiped out.

Steps to reproduce:
I have not tried to reproduce this issue, I locked the config files (removed write permission) as suggested as a temporary fix on other threads.

**Comment by danimo** [comment]
@nelwa Is this reproducible?

**Comment by nelwa** [comment]
I don't know.  I haven't tried to reproduce it, and haven't got time to test it at the moment.  All I know is what happened as posted above.  I googled the problem and found the problem was around in client 1.4.0 as well.  By the way, this is the first time this happened to me.

**Comment by ckamm** [comment]
@nelwa  Thanks for the report! This is also being discussed in #3820
