### ISSUE TITLE
[2.0.2 Crash] You have 2 accounts, upload a file in 1 account, Remove Account, click on Sign out the ownCloud Crashed

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3843]
### Steps to reproduce
1. Having two accounts configured (e.g user10, user11)
2. Right click on oC icon
3. Go to "Open folder user10"
4. Upload a file (e.g 1GB)
5. Waiting to Sync
![screen shot 2015-09-16 at 09 48 06](https://cloud.githubusercontent.com/assets/12032058/9899282/187f7cfe-5c59-11e5-92db-2fcadb453d9a.png)
6. Click on Remove Account (user10)
7. So, there is only one account  registered (user11)

### Expected behaviour
No file is being uploaded

### Actual behaviour
The account (user11) is Waiting for Sync, an upload is on progress. This upload is the one that was started with the account user10
![screen shot 2015-09-16 at 09 49 47](https://cloud.githubusercontent.com/assets/12032058/9899372/9d680346-5c59-11e5-9f3a-86f3012e13dd.png)

NOTE:
Once the app is on this status, if you click on sign out, the client crash

### Server configuration
Desktop v ownCloud-2.0.2.2719-nightly20150916.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.1.3","versionstring":"8.1.1","edition":"Enterprise"}

**Comment by guruz** [comment]
What do you mean? During sync you remove the account?

**Comment by Dianafg76** [comment]
@guruz During sync you remove the account?: Yes

**Comment by ckamm** [comment]
I have not been able to reproduce the crash. 

But removing an account while a folder is syncing does indeed mess with sync scheduling: The account's folders are removed from the folder manager before the currently active folder finishes. And then the syncFinished() signal won't reach the folder manager and it won't schedule the next folder.

**Comment by ckamm** [comment]
@Dianafg76 Can you show what's in the log file just before the crash and ideally provide a backtrace?

**Comment by Dianafg76** [comment]
I tested this issue and now is working OK
Desktop v ownCloud-2.0.2.2730-nightly20150921.pkg
Close
