### ISSUE TITLE
[Wizard] Different size for the same window when clicking back

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3846]
### Steps to reproduce
1. Install the new version 2.0.2 (ownCloud-2.0.2.2719-nightly20150916.pkg)
2. Introcude de Server Address
3. Click on Next
4. Introduce the User/password. The screen look:
   ![screen shot 2015-09-16 at 11 22 41](https://cloud.githubusercontent.com/assets/12032058/9901153/e1732582-5c65-11e5-94bd-f7137a8a0a52.png)
5. Click on Next
6. Click Local Folder
7. Create a new Folder
8. Click on Open
9. Click on < Back
### Expected behaviour

it should see the same size 
### Actual behaviour

And the size screen is different, is big
![screen shot 2015-09-16 at 11 23 22](https://cloud.githubusercontent.com/assets/12032058/9901211/60aff992-5c66-11e5-8653-6a8984fe5ac8.png)
### Server configuration

Desktop v ownCloud-2.0.2.2719-nightly20150916.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"}

**Comment by guruz** [comment]
Does this only happen when clicking "back"? Then you can move it to later milestone, I don't think it's that important :)

**Comment by hodyroff** [comment]
Please reproduce with 2.3

**Comment by SamuAlfageme** [comment]
@hodyroff yep, It does reproduce. Not to be considered a "bug" being strict though.
