### ISSUE TITLE
File is not synchronized to the client - Broken webserver returning empty content length for non-empty file on resume

### ISSUE THREAD

**Issue by raivisdejus** [owncloud/client#3848]
I have several files that are on the server but that I can not get to download.
Downloading from web interface the download fails
Downloading via Sync client for windows I get the following error - Broken webserver returning empty content length for non-empty file on resume

I have this defect with several files. All files are small. < 1MB

The server is running OwnCloud 8.1.1 on a shared hosting.

**Comment by guruz** [comment]
> on a shared hosting

Ask your hoster is using any funky firewalls, webserver modules etc.
This is nothing we can help you with, sorry.

**Comment by raivisdejus** [comment]
I guess the shared hosting is the issue. 
BUT
Has anyone had similar problems? Maybe you can point me to some place where I can read more about this.

Maybe there is some configuration that works better on shared hostings?

When I copy some larger folder some file will always get corrupted. Most of the files will be copied ok, but some file will always fail. Different files each time.

**Comment by raivisdejus** [comment]
Seems that server guys did some magick (eg. updated the php version and configuration) and now everything works fine :)
