### ISSUE TITLE
[Windows 10] The buttons Max (green icon) and Close (red icon) are missing

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3849]
### Steps to reproduce
1. Install v 2.0.2 on Windows 10
2. On the screen Setup oC server 

### Expected behaviour
On Mac
![screen shot 2015-09-16 at 15 07 09](https://cloud.githubusercontent.com/assets/12032058/9908583/9f63cbae-5c94-11e5-9bec-25d4136ebfc9.png)

### Actual behaviour
The buttons Max and Close are missing with WIN10
![screen shot 2015-09-16 at 15 07 00](https://cloud.githubusercontent.com/assets/12032058/9908417/d52e039a-5c93-11e5-8a51-7f32bf6ecac2.png)

### Server configuration
Desktop v  ownCloud-2.0.2.5466-nightly20150916-setup.exe 
Server v{"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"}

**Comment by danimo** [comment]
The wizard is a dialog. Dialogs are not reziable or minimizable (no yellow/green button) and the red button is the X on the other side.
