### ISSUE TITLE
[Windows 10] Wizard back-button should be hidden/disabled

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3851]
### Steps to reproduce
1. Install v 2.0.2 on Windows 10
2. Create one account (e.g User21)
3. Waiting for sync
4. Right click on the oC icon
5. Click on Settings...
6. Click on Remove sync
7. Click on Stop sync
8. Click on Add Folder Sync Connection
### Actual behaviour
1. The button Go Back is missing
   ![screen shot 2015-09-16 at 18 02 34](https://cloud.githubusercontent.com/assets/12032058/9910511/a5c1e054-5c9d-11e5-9b30-3d60a8b4e8e0.png)
2. In Mac have two buttons (Cancel, Continue), and in WIN 10 the button Continue is called NEXT
### Server configuration

Desktop v ownCloud-2.0.2.5466-nightly20150916-setup.exe
Server v{"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"}

**Comment by danimo** [comment]
As per Windows Interface guidelines, the back button is the grey little arrow next to the cloud icon on the top left.

**Comment by Dianafg76** [comment]
ok, thanks

**Comment by Dianafg76** [comment]
@danimo If you click on the litle arrow on the top left, is not working

**Comment by phil-davis** [comment]
Yes, same here. I guess on the first screen of a sequence like that, the back button is effectively the same function as the close "red x" in the top right-hand corner.
I wonder what the Windows Interface guidelines are for that - should the back-arrow be visible but greyed-out and disabled (the current case), or not visible at all, or active and close the dialog?

**Comment by guruz** [comment]
@danimo Although the difference is that on OS X the "Go back" is disabled/greyed.
So to make this analogous, the Windows10 back-button in the top left should be hidden or disabled.

**Comment by TheOneRing** [comment]
We now use the windows style wizard on all paltforms
