### ISSUE TITLE
Public Sharing Requires Password

### ISSUE THREAD

**Issue by ToddyNZ** [owncloud/client#3853]
Hi,

Since updating to 2.0.1, sharing links using the "Share with owncloud" windows right click option I am now asked to set a password before it provides me a link.

Is this something set from the server or is this an update to the client that cannot be changed?

Previously it would just give me the shared link to the file and ask if I wanted to set a password or expiry date as an optional field.

Now I HAVE to set a password before it will provide me a link, I then have to go back and remove the password.

Can someone please look in to this for me?

Regards.

**Comment by phil-davis** [comment]
Read https://github.com/owncloud/client/issues/3703 and https://github.com/owncloud/client/issues/3760
and try the workaround: https://github.com/owncloud/client/issues/3703#issuecomment-136152864

**Comment by ToddyNZ** [comment]
Thanks phil, #3703 looks to be exact issue I am encountering.

Have escalated for my I.T support team to action.

**Comment by RealRancor** [comment]
@ToddyNZ As its a dup of #3703 feel free to close here to avoid having several open issues here.

**Comment by ToddyNZ** [comment]
Apologies.
