### ISSUE TITLE
"Choose What to Sync" - sorting by size is wrong

### ISSUE THREAD

**Issue by yonas** [owncloud/client#3854]
![sync-sort](https://cloud.githubusercontent.com/assets/110130/9922072/3afd1508-5cb2-11e5-9818-cfdfa5c2a31b.png)

### Expected behaviour
Sizes should sort largest to smallest or smallest to largest.

### Actual behaviour
It's sorting by the first digit, completely ignoring the actual sizes.

### Steps to reproduce
1. Activate the "Choose what to sync" dialog
2. Click on the Size column to sort
3. See that the items are not sorted by size properly (see screenshot)

### Server configuration
Operating system: 
FreeBSD 9.2

Web server: 
Apache/2.4.10 (FreeBSD) OpenSSL/0.9.8y PHP/5.4.32

PHP version:
5.4.32

ownCloud version:
8.0.2 (stable)

### Client configuration
Client version:
1.8.0

Operating system:
FreeBSD desktop 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 15:26:37 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by phil-davis** [comment]
Please use the issue template https://github.com/owncloud/client/blob/master/issue_template.md to help report all relevant details. In particular, what ownCloud client version and OS.
I happen to be using a recent nightly build of 2.0.2 - Version 2.0.2-nightly20150916 (build 5466) - on Windows10 and the sort by size works there:
![sizesort](https://cloud.githubusercontent.com/assets/1535615/9922709/731ca116-5d0b-11e5-9515-9df586ca7491.png)

**Comment by yonas** [comment]
### Expected behaviour
Sizes should sort largest to smallest or smallest to largest.

### Actual behaviour
It's sorting by the first digit, completely ignoring the actual sizes.

### Steps to reproduce
1. Activate the "Choose what to sync" dialog
2. Click on the Size column to sort
3. See that the items are not sorted by size properly (see screenshot)

### Server configuration
Operating system: 
FreeBSD 9.2

Web server: 
Apache/2.4.10 (FreeBSD) OpenSSL/0.9.8y PHP/5.4.32

PHP version:
5.4.32

ownCloud version:
8.0.2 (stable)

### Client configuration
Client version:
1.8.0

Operating system:
FreeBSD desktop 10.2-RELEASE FreeBSD 10.2-RELEASE #0 r286666: Wed Aug 12 15:26:37 UTC 2015     root@releng1.nyi.freebsd.org:/usr/obj/usr/src/sys/GENERIC  amd64

**Comment by phil-davis** [comment]
1.8.0 is an old client. It would be worth confirming this on a newer client version 2.0.1 release or the recent 2.0.2 beta from https://owncloud.org/install/#testing-development

**Comment by yonas** [comment]
Thanks, I've asked the FreeBSD port maintainer to upgrade to v2.0.1:

https://bugs.freebsd.org/bugzilla/show_bug.cgi?id=203167

**Comment by guruz** [comment]
Thanks Phil & Mr. Beans.. let's close this for now.

If it's not fixed with 2.x on FreeBSD then maybe Qt4 vs Qt5 could be another thing to look t.

**Comment by yonas** [comment]
Thanks Phil, guruz, upgrading to v2 fixed it.
