### ISSUE TITLE
[Windows 10] When you start Win 10 all the time the desktop client asks for the Certificate. 

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3855]
### Steps to reproduce
1. You need install v2.0.2 on Win 10
2. Click on oC icon
3. Click on Log out
4. Shut down Win 10
5. Start Win 10

### Expected behaviour
It should not ask for the certificate

### Actual behaviour
When you start Win 10 all the time the desktop client asks for the Certificate. 

### Server configuration
**Operating system**:

**Web server:**

**Comment by ckamm** [comment]
@Dianafg76 It's pretty likely that this is related to the general config-storing problems #3747 #3820. Are the other settings saved correctly? Do you need to restart windows to manifest the issue? Restarting only the client doesn't trigger it?

**Comment by Dianafg76** [comment]
@ckamm And if you upload on v ownCloud-2.0.2.5468-nightly20150917-setup.exe, The same thing happens

**Comment by Dianafg76** [comment]
Close this issue because now it is working OK. Sorry

**Comment by ckamm** [comment]
@Dianafg76 So you still see the issue? Are the other settings saved correctly? Do you need to restart windows to manifest the issue? Restarting only the client doesn't trigger it?

**Comment by Dianafg76** [comment]
I tested this issue, and it is working OK
Desktop client v ownCloud-2.0.2.5484-nightly20150923-setup.exe 
Closed
