### ISSUE TITLE
Sync client must MOVE when update permission was given

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#3856]
See https://github.com/owncloud/core/issues/18933#issuecomment-141025262

The "update" permission allows for renames, but the sync client (2.0.1) interprets the lack of "delete" permission as a lack of rename permission, which is wrong.

So far share permissions were always a bit mysterious, I hope this test case can help clear them out a bit: https://github.com/owncloud/smashbox/blob/master/lib/oc-tests/test_sharePermissions.py#L111

**Comment by PVince81** [comment]
On a side-note, I'd love to simplify share permissions, see https://github.com/owncloud/core/issues/12970

**Comment by ckamm** [comment]
@PVince81 Currently the client checks for 'N' permission for renames and 'V' permission for moves. https://doc.owncloud.org/desktop/1.8/architecture.html#custom-webdav-properties 

Is that a different thing? How does the update permission relate to these two?

**Comment by PVince81** [comment]
Argh, permission hell.
Let me check the source code: https://github.com/owncloud/core/blob/master/lib/private/connector/sabre/node.php#L235

Looks like "W" is updatable when it's a file, and "CK" for a folder... not easy.

Maybe the server needs to be updated to reflect them ?

Is there a reason why the permissions were not mapped one to one ? @DeepDiver1975 @guruz

**Comment by ogoffart** [comment]
@PVince81 yes, we needed this granularity for another server.
I believe it should be simple to add 'N' if the file is updatable.
