### ISSUE TITLE
[2.0.2] If you Modify the Folder Sync Limit, When synchronization has ended it does not appear the warning

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3858]
### Steps to reproduce
1. Install v 2.0.2
2. Right on oC icon
3. Click on Settings...
4. Click on General Option
5. Modify the Folder Sync Limit (e.g. 100 MB)
6. Open the Web Server
7. Create a new folder (e.g. More than 100 MB)
8. Upload a file more than 100 MB size
9. Go to Desktop client
10. Wait to sync

### Expected behaviour
You should see the warning

### Actual behaviour
When synchronization has ended it does not appear the warning:
![screen shot 2015-09-17 at 14 15 24](https://cloud.githubusercontent.com/assets/12032058/9932746/95503bfe-5d46-11e5-9974-5bc51d9ef62d.png)

### Server configuration
Desktop v ownCloud-2.0.2.2721-nightly20150917.pkg  
Server v {"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"}

**Comment by phil-davis** [comment]
I tried a similar thing just now with Version 2.0.2-nightly20150916 (build 5466) and it worked fine. But I first pause sync on the client, then add the folder plus files on the server, then resume sync on the client.
I suspect that in this problem report the client has first synced the new folder during the time while the big file was still uploading (when the folder seemed to be 0 bytes). Then when the big file appeared, it was synced down inside the already-existing folder on the client.
Does it work if you:
1) pause sync on the client
2) create the new folder and upload the big file in it
3) resume sync on the client
?

**Comment by Dianafg76** [comment]
If you pause sync on the client.... is working

**Comment by phil-davis** [comment]
I expect the problem is like scenario A described in https://github.com/owncloud/client/issues/3543
Nobody has thought of a good way around this yet.

**Comment by ckamm** [comment]
I agree that this seems like a case of #3543. We'll not address this for 2.0.2.
