### ISSUE TITLE
[Windows 10]Folder sync connection context menu always opens folder tree view

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#3859]
Version 2.0.2-nightly20150916 (build 5466) on Windows10.
1) Open the client UI and select any account
2) Click the "..." folder sync connection context menu and select any of "Open folder", "Pause sync" or ("Remove sync" followed by Cancel).

The relevant action happens, but also the folder tree view opens for choosing folders to sync.

The folder tree view should not open for these 3 actions.

**Comment by guruz** [comment]
It's a side effect of the code to open the tree on single click.
Since we're not using QML yet we can't easily put a button into the tree view, so we fake-paint one.
We could work around this if other people think it's critical.

**Comment by phil-davis** [comment]
This commit https://github.com/owncloud/client/commit/23b5a74c17f5ad300fe118e262f1738d844f1ef8 seems to address this issue. That is working in Version 2.1.0-nightly20151024 (build 5579)

However, when I first click on each account and the list of Folder Sync Connections is displayed, the Folders to Sync selection tree is auto-magically opened for the first Folder Sync Connection associated with the account.
![owncloud21a](https://cloud.githubusercontent.com/assets/1535615/10709953/5756e7fc-7a61-11e5-8c53-06be1197742a.png)

**Comment by guruz** [comment]
@phil-davis Thanks for testing.. I have added the auto-open because people didn't notice it was a tree view. it's more obvious now I think.

Thanks for fixing @ogoffart
