### ISSUE TITLE
[2.0.2] Error shown after logging out and then click on "Choose What to Sync"

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3860]
### Steps to reproduce
1. Install v 2.0.2 
2. Right click on oC icon
3. Select one account (e.g user24)
4. Click on Log out
5. Right click on oC icon
6. Click on Settings...
7. Select the account user24
8. Click on Choose What to Sync

### Actual behaviour
1. Clicking choose which Sync, you can see the screen to enter the password.
2. The folders open , but you can see an error ( error loading the list of folders on the server )
![screen shot 2015-09-17 at 17 23 53](https://cloud.githubusercontent.com/assets/12032058/9937891/f830d47e-5d62-11e5-8fb3-ee736ec67436.png)

### Server configuration
Desktop v ownCloud-2.0.2.2721-nightly20150917.pkg this happens on the MAC client and on the Windows too
Server v {"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
@dragotin I tested this issue and you still see the same error
![screen shot 2015-09-28 at 12 47 16](https://cloud.githubusercontent.com/assets/12032058/10133672/6b2fe4e0-65df-11e5-972e-3e861311ad56.png)
 

Desktop v ownCloud-2.0.2.2750-nightly20150928.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"}

**Comment by dragotin** [comment]
Ok, I forgot to disable the actions of the context menu. The previous patch does that, please retest. Thanks!

**Comment by Dianafg76** [comment]
Now it is working OK
Desktop v ownCloud-2.0.2.2756-nightly20150930.pkg
