### ISSUE TITLE
Feature Request: Add Maximize & Minimize buttons to Title Bar

### ISSUE THREAD

**Issue by nelwa** [owncloud/client#3862]
Hi,

Please add maximize & minimize buttons to the windows client.  The window can be resized by dragging on the corners, so I don't know why the maximize & minimize buttons have been removed.

Thanks

**Comment by danimo** [comment]
We've had this discussion time and again: It's a (temporary) dialog, not a Window that's open all of the time. Dialogs by definition have no fullscreen/minimize functionality. Plus it will remember its size, so you have to resize it exactly once.
