### ISSUE TITLE
[2.0.1] [Windows] The client does not register that files have changed if the folder is junction (link)

### ISSUE THREAD

**Issue by Auxink** [owncloud/client#3865]
### Steps to reproduce
1) Create folder junction inside owncloud sync folder pointing outside the owncloud sync folder with command line command: mklink /j &lt;link-name&gt; &lt;target-path&gt;
2) Create some files inside the folder
3) Edit files few times
4) Have a look at log

### Expected behaviour
Register that files have been changed and synchronize them.

### Actual behaviour
Nothing happens. The client does register that files have been changed.

### Client configuration
Client version: 2.0.1 (build 5446)
Operating system: Windows 7 64 bit, Windows 10 64 bit
OS language: English

**Comment by guruz** [comment]
What happens if you restart the client?
Does it error on sync?
Does it ignore the files on sync?
Does it succeed?

**Comment by Auxink** [comment]
Every time there is full sync, it finds all non-synced files, which is every 2 hours or after client restart.
There is no sync when I change any file, so there is no error, no log, nothing.

**Comment by guruz** [comment]
I asked because I was thinking it triggers https://github.com/owncloud/client/issues/3813 ?

**Comment by Auxink** [comment]
I wasn't sure if it's the same problem, but if it is, you can close it as duplicate.

**Comment by guruz** [comment]
Do you want to try http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.5493-nightly20150925-setup.exe ?

**Comment by dragotin** [comment]
No, junktions are equivalent to sym links. We do not sync the contents behind sym links. Sym links are ignored.

**Comment by Auxink** [comment]
this: "Symbolic links are not supported in syncing." might be nice for some but for me it completely disables syncing.

**Comment by Auxink** [comment]
"Windows doesn't propagate file system events to both ends of the symlink."  would be atleast nice answer to the problem. I have found it when you made me to search for different programs.

**Comment by danimo** [comment]
@Auxink what is the problem in your case?

**Comment by Auxink** [comment]
Because there is no sync for multiple folders I had to create symlinks (junctions) to folders I want to sync. So there is not a single folder in ownCloud sync folder, everyone of them are symlinks. And the FileSystemWatcher does not work through symlinks (which I found out 5 hours ago). Therefore it synces my files only every 2 hours and not with every change.

**Comment by phil-davis** [comment]
You can make multiple folder sync connections in the client to sync between a folder tree on the server and a folder tree somewhere on the client. So you can sync different parts of the files on the server to different places around the client file system. It sounds like you could do this, rather than create multiple [symlinks|junction points] in a single place on the client.

**Comment by dragotin** [comment]
Syncing sym-links is like juggling with scissors. Better don't do.

**Comment by Auxink** [comment]
@phil-davis I didn't know you could do that. And it looks somewhat better. Thank you.
Just one more thing. It probably isn't possible to move owncloud files (database, log and such) somewhere else?

@dragotin I Don't see a problem with syncing symlinks as long as you don't create loops with them in filesystem.

**Comment by phil-davis** [comment]
AFAIK the ownCloud sync database files are created in the top level folder of each sync connection and have to stay there. But I have a feeling others have asked about this before and maybe there was some discussion about being able to put them somewhere else.

**Comment by dragotin** [comment]
@Auxink well, aren't we discussing one here? Apart from that: Think harder :smile_cat:
