### ISSUE TITLE
German local not complete

### ISSUE THREAD

**Issue by fishermans** [owncloud/client#3867]
Some German locals are not translated, yet. I would improve that but my request to join the translation group on transifex has not been accepted.

So my question: How to add missing translation and how to replace some "odd" translations?

Cheers
Fishermans

**Comment by fishermans** [comment]
e.g.:
```xml
    <message>
        <location filename="../src/gui/folderstatusmodel.cpp" line="727"/>
        <source>Discovering &apos;%1&apos;</source>
        <translation>„%1“ wird entdeckt</translation>
    </message>
```
should be:
```xml
    <message>
        <location filename="../src/gui/folderstatusmodel.cpp" line="727"/>
        <source>Discovering &apos;%1&apos;</source>
        <translation>„%1“ wird untersucht</translation>
    </message>
```

**Comment by guruz** [comment]
Could you try to join again?
I accepted someone and it might be you.

**Comment by tflidd** [comment]
@guruz I tried to join some time ago (some months) via my github account. I tried to join the german translation but I never received a reply. You can't join twice for the same language on the same project (I still could join German(Austria)).

**Comment by fishermans** [comment]
@guruz: Thanks but nothing changed. I also used my github account to login to transiflex.

**Comment by dragotin** [comment]
I fixed the translation problems mentioned above.

**Comment by dragotin** [comment]
Checked if it has arrived for RC1.
