### ISSUE TITLE
[OS X] ownCloud Testpilot Edition-2.0.2.2717beta1 : no overlay icon ... 

### ISSUE THREAD

**Issue by Claire75** [owncloud/client#3870]
![capture d ecran 2015-09-19 a 14 18 30](https://cloud.githubusercontent.com/assets/14247476/9976122/9cb813a0-5ed9-11e5-8495-919de8092d25.png)
I've already mention this https://github.com/owncloud/client/issues/3819 ( and the way i fixed it ) 

this morning,  I just install ownCloud Testpilot Edition-2.0.2.2717beta1.pkg and ... no overlay icons for my new folder for this version. ( nuage is the owncloud folder with 2.0.1 - testpilot the folder with 2.0.2 )

**Comment by guruz** [comment]
Which OS X version do you use?

**Comment by Claire75** [comment]
10.11 
As said before , i fixed it but in a quite long way ;)  ( see  #3819 )
