### ISSUE TITLE
Client "exploring" unselected folders

### ISSUE THREAD

**Issue by s24195** [owncloud/client#3872]
Hi,

I am using version 2.0.1 of the windows sync client and I am syncing my lightroom catalogue to a local OC server.
Lightroom creates previews of every photo you have in your catalogue and saves them in a lot of directories. 
In my case these are 15 GB in 52'000 directories holding 120'000 files.

I have deselected these subfolders from the sync, but the client is always exploring them.
As this process is quite CPU intensive and takes a while the complete, all other folders are not synced in time any more.

Please let me know if you need more information.

**Comment by guruz** [comment]
@ogoffart I was under the assumption that non-selective-synced-folders are ignored?

**Comment by ckamm** [comment]
@ogoffart I think selective sync folders are only ignored for remote discovery (csync_update.c:193) - why is that?

**Comment by ogoffart** [comment]
The idea is that when you uncheck something, it deletes it localy.
The way it deletes it is by doing a normal sync, seeing that the files are in the locale and not in the remote, and then delete it.

This means that it will only go on these directory once, then delete them.
And it should not take so long normaly. Especially with owncloud 2.1.

**Comment by guruz** [comment]
@s24195 do you still have this with 2.1.x?
