### ISSUE TITLE
client errors during sync of google drive

### ISSUE THREAD

**Issue by ferdiga** [owncloud/client#3873]
![google drive sync](https://cloud.githubusercontent.com/assets/6248560/9986882/02de6e22-6042-11e5-8562-011ae64b865a.png)

### Steps to reproduce
1. configure google drive external storage
2.
3.

### Expected behaviour
Tell us what should happen
should sync or handle errors more gracefully

### Actual behaviour
many error massages see screenshot
in the browser a lot of files (google documents?)  have no file extensions and no size 

### Server configuration
**Operating system**:
Debian 8

**Web server:**
apache2 2.4.10-10+deb8u

**Database:**
mariadb-server 10.0.20-0+deb8u1
**PHP version:**
PHP 5.6.13-0+deb8u1 (cli) (built: Sep  7 2015 13:38:37)

**ownCloud version:** (see ownCloud admin page)
8.0.3

**Updated from an older ownCloud or fresh install:**
updated 7
**List of activated apps:**
Enabled:
 - activity
 - bookmarks
 - calendar
 - contacts
 - documents
 - external
 - files
 - files_external
 - files_locking
 - files_pdfviewer
 - files_sharing
 - files_texteditor
 - files_trashbin
 - files_versions
 - files_videoviewer
 - firstrunwizard
 - galleryplus
 - search_lucene
 - updater

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**
<?php
$CONFIG = array (
  'instanceid' => 'ocde8d3204fb',
  'passwordsalt' => '',
  'datadirectory' => '/var/www/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '8.0.3.4',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncloud',
  'dbpassword' => '',
  'installed' => true,
  'enable_previews' => true,
  'forcessl' => true,
  'theme' => '',
  'maintenance' => false,
  'mail_smtpmode' => 'smtp',
  'mail_smtphost' => 'localhost',
  'mail_smtpport' => '25',
  'mail_smtptimeout' => 10,
  'loglevel' => 3,
  'share_folder' => '/Shared',
  'trusted_domains' =>
  array (
    0 => 'service.chricar.at',
  ),
  'mail_from_address' => 'xenon',
  'mail_domain' => 'strakosch.at',
  'secret' => '',
  'singleuser' => false,
  'forceSSLforSubdomains' => true,
);

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...no
local, google drive

**Are you using encryption:** yes/no
no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
On ownCloud 7+ with access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

On ownCloud 6 with access to your command line run e.g.:
sqlite3 data/owncloud.db or mysql -u root -p owncloud
then execute:  select * from oc_appconfig where appid='user_ldap';

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query above.

Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**
ubuntu 15.04

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

{"reqId":"4c568be4a860366c76bc94c5108e2d72","remoteAddr":"80.110.66.25","app":"PHP","message":"Undefined offset: 4 at \/var\/www\/owncloud\/lib\/private\/files\/stream\/dir.php#29","level":3,"time":"2015-09-21T07:32:38+00:00"}
{"reqId":"4c568be4a860366c76bc94c5108e2d72","remoteAddr":"80.110.66.25","app":"remote","message":"Error calling PUT https:\/\/www.googleapis.com\/upload\/drive\/v2\/files\/1ECYeAJvxb1w64HLQN2pyW6jDkHE9XDCLPiQ55HF5XZ4?uploadType=multipart: (400) The requested conversion is invalid.","level":4,"time":"2015-09-21T07:32:40+00:00"}

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by guruz** [comment]
> ownCloud version: (see ownCloud admin page)
> 8.0.3

I'd definitely try a newer version..

Also, this is better on the server bugtracker, not client :)
https://github.com/owncloud/core/issues/

**Comment by ppanek** [comment]
With ownCloud 8.1.3 and client 2.0 - errors in desktop client during sync of Google Drive files:

Broken webserver returning empty content length for non-empty file on resume -2B 

Files created with Google apps (docs, sheets, etc)  have 0 bytes size. It's because they are not included in Google account storage.

With ownCloud Files app you can see they have Pending caption in Size column. Desktop client is failing to sync them and complains on broken server which is not true in this case.

**Comment by ferdiga** [comment]
Please is this fixed or open ?

**Comment by ppanek** [comment]
IMO this is an issue still and upgrading to latest stable doesn't fix the problem.
