### ISSUE TITLE
Mac: Contextual Menu Not Showing Share on OwnCloud Option

### ISSUE THREAD

**Issue by petervcook** [owncloud/client#3874]
### Expected & Actual behaviour
Since upgrading from v 1.8.4 to v 2.0.1 of the Mac client, the contextual menu setting for sharing the folder on OwnCloud has gone missing. No other changes were made either to the server install or client OS version.

### Steps to reproduce
I have confirmed the issue with 2 other co-workers who did not upgrade, but installed v 2.0.1 as their first ownCloud desktop client. The contextual menu item is not there as they right-click

### Server configuration
Operating system:
Mac OS X Server

ownCloud version:
6.0.1

FYI: Connecting via HTTP

### Client configuration
Client version:
2.0.1

Operating system:
Running Mac OS X Yosemite 10.10.5

OS language:
English
Installation path of client:
/Applications/owncloud.app

**Comment by petervcook** [comment]
A colleague found the solution. User's have to go to "System Preferences" -> "Extensions" -> "Finder" and check the tick box for "ownCloud Extensions". Perhaps a prompt to the user after installing the desktop client could be added to let users know the required steps.

Now that we see that feature, a new feature request would be to provide a way to share with other users, as opposed to just sharing via a public link

**Comment by phil-davis** [comment]
Now that we see that feature, a new feature request would be to provide a way to share with other users, as opposed to just sharing via a public link - see https://github.com/owncloud/client/issues/3737

**Comment by meisterleise** [comment]
I have a mac running OS 10.9.5. There is no "Extensions" ind System Prefs.
Any idea how to fix this problem under 10.9.5?

**Comment by jturcotte** [comment]
@meisterleise 10.9 and before are still using the old extensions, the plugin is installed but it requires

1. Finder to be restarted after the installed (if not you might have to restart OS X)
2. An apple script message is sent by the ownCloud client when it starts to activate the extension.

If that doesn't work, could you open a new bug report and describe since when the problem occurs (2.0.0?) and other details that might be particular to your setup?

**Comment by meisterleise** [comment]
@jturcotte 
thanks for response.
1. I did bevore. Did not help
2. dont understand. can I do anything?

**Comment by MariusLaurinaitis** [comment]
Hello, nextcloud 15, MacOS app 2.5.1.
I have problem, after reinstalation  nextcould apps works fine, until reboot my Mac, contextual menu setting for sharing the folder on Nextcloud has gone missing.

**Comment by guruz** [comment]
@MariusLaurinaitis Download the latest rc please https://github.com/owncloud/client/releases/tag/v2.5.4-rc1

**Comment by MariusLaurinaitis** [comment]
But th

> @MariusLaurinaitis Download the latest rc please https://github.com/owncloud/client/releases/tag/v2.5.4-rc1
Ok, but this is owncloud, not nextcloud. Do I need this?
