### ISSUE TITLE
OwnCloud causes MacBook Pro fan to run fast and noisily during sync

### ISSUE THREAD

**Issue by wadedugas** [owncloud/client#3875]
Client version: Version 2.0.1 (build 2694)
Server: ownCloud 8.1.3 (stable)

The fan on my mid 2015 MackBook Pro runs loud enough to be annoying while ownCloud is syncing. The client seems to take up to 100% of one processor at times and still enough at other time so the fan runs fast enough that the noise is very annoying.

I believe the ownCloud client should not consume so many resources that it causes this or alternatively there should be a setting to set the amount of CPU it can consume by making the sync more or less aggressive. I know there is a bandwidth setting for throttling, but no setting for throttling the sync in general. It would be better if it were a background process which is not noticed.

**Comment by guruz** [comment]
@wadedugas Can you check the settings windows if this only happens while it says "Discovering"?
Or also while doing actual file uploads/downloads?
Can you tell us a bit about the amount of sync folders and files you have?

**Comment by wadedugas** [comment]
@guruz It seems to be only during discovery. The folder is 17GB with 61,187 files.

The discovery seems to check all files and folders whenever just a single file is changed. For instance, I have a single file which I update regularly in the root directory. Instead of seeing activity of discovering and synching the single file, the client seems to discover all files and folders and then just syncs the single file. 

I did change the ask confirmation before downloading folders size limit as this was not asking confirmation, but rather blocking the synchronization of one of my folders which was larger than the default 500 MB. Perhaps it should actually notify instead of block. The client seemed to discover this folder every time it did discovery and then not sync it. Perhaps this is part of the issue. Even if it is, the client should be able to discover large directories and not consume 100% of 1 core to do it.

**Comment by tombou** [comment]
I've got a similar problem on a 2 years old Sony Vaio using the same config. The database is 47GB with 144 500 files. It seems to have a delay of about 1h10 between 2 cycles. During a cycle, the fan goes up for about 10 minutes and one core is filled used during discovery. I've configured also another smaller database on the same computer and it runs normally.

**Comment by dragotin** [comment]
resolved by #3408

**Comment by wadedugas** [comment]
https://github.com/owncloud/client/issues/3408 is stated for Windows only. If you are going to close this one, then please update 3408 to include OS X
