### ISSUE TITLE
ownCloud for Ubuntu 15.04 build stuck at 2.0.0-rc2

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/client#3880]
I had some issues with 2.0.0-rc2 and wanted to try release version (there is even 2.0.1), but it is not present in repository. Can anyone trigger build or whatever else is needed to release it?

**Comment by jnweiger** [comment]
https://build.opensuse.org/package/binaries/isv:ownCloud:desktop/owncloud-client?repository=Ubuntu_15.04

has 2.0.1 since its release on September 15th.

@nazar-pc are you waiting for the package elsewhere?

**Comment by nazar-pc** [comment]
Of course, I'm looking here: http://download.opensuse.org/repositories/isv:/ownCloud:/community:/testing/xUbuntu_15.04/
As per download page https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

**Comment by nazar-pc** [comment]
Sorry, I'm using testing repository indeed. But weirdly, it doesn't contain latest stable version.

**Comment by dragotin** [comment]
I added a note to our release checklist to not to forget to update the testing repo to the latest stable. Will happen from the next version on.

Thanks!
