### ISSUE TITLE
Changes done by another windows client are not triggering a sync

### ISSUE THREAD

**Issue by a-schild** [owncloud/client#3883]
Client 1: Windows 8.1, Owncloud 2.0.1 (Build 5446)
Client 2: Windows 10, Owncloud 2.0.1 (Build 5446)
Server 8.1.1 under Debian 8.0

Client 1 & 2 have a sync setup for the folder "IBZ"
At 2015-09-24 arround 23:00 changes have been done on the Client 2, which are sent to the server

Client 1 did not pick up the new files on the server.
At 2015-09-25 at 09:29 I did add a new file to the folder on Client 1
At that moment it triggered a sync and doenloaded all changes present on the server

Here the sync log of Client 1:
```
10:44:14|5318|Kursunterlagen/Webtechnologien/WT3_2015/IBZ_Bestellformular_Kopierauftrag_150520.pdf|INST_NEW|Up|1442832242||577889||4||201|0|0|||INST_NONE|
#=#=#=# Syncrun started 2015-09-23T17:40:13 until 2015-09-23T17:41:23 (69998 msec)
|0|Schultage|INST_SYNC|Down|1442950857|5601aeccb1f07|0|0004739450a4d1d37147d|0||0|4096|1441966241|55fd53d85c532||INST_NONE|
|0|Schultage/2015 Sommersemester|INST_SYNC|Down|1442950857|5601aeccb20b7|0|0023994350a4d1d37147d|0||0|4096|1429285878|55fd53d85c758||INST_NONE|
|0|Schultage/2015 Sommersemester/TI6 Bern|INST_SYNC|Down|1442950857|5601aeccb2223|0|0024533550a4d1d37147d|0||0|4096|1442815550|55fd53d85c8ba||INST_NONE|
15:41:23|94|Schultage/2015 Sommersemester/TI6 Bern/Notenliste.ods|INST_SYNC|Down|1442950789|9892dda9658b902c7ab04fec81ab30c0|14767|0024533850a4d1d37147d|4||0|14782|1442665352|dc6f0696c92af82b8079256bd252ec9f||INST_NONE|
#=#=#=# Syncrun started 2015-09-23T21:01:06 until 2015-09-23T21:01:16 (9529 msec)
#=#=#=# Syncrun started 2015-09-24T02:30:42 until 2015-09-24T02:30:51 (9406 msec)
#=#=#=# Syncrun started 2015-09-25T09:29:00 until 2015-09-25T09:31:07 (127202 msec)
|0|Schultage/2015 Sommersemester/TI5 Aarau/Casestudy/Angelo Florian Ali|INST_NEW|Down|1443120880|560446f0ee40d|0|0073847950a4d1d37147d|4||0|0|0|||INST_NONE|
07:29:36|199|Schultage/2015 Sommersemester/TI5 Aarau/Casestudy/Angelo Florian Ali/CS_Arbeitsjournal_AG_AH_FH.pdf|INST_NEW|Down|1442513317|d75f7b542f51aac37a18da8a6094768a|266074|0073848450a4d1d37147d|4||0|0|0|||INST_NONE|
07:29:36|468|Schultage/2015 Sommersemester/TI5 Aarau/Casestudy/Angelo Florian Ali/CS_Projekt_Zeitplanung_AG_AH_FH.pdf|INST_NEW|Down|1442513284|ac1b296deb07f5513f19aaf9a9301551|714394|0073848550a4d1d37147d|4||0|0|0|||INST_NONE|
07:29:37|834|Schultage/2015 Sommersemester/TI5 Aarau/Casestudy/Angelo Florian Ali/CS_S5_Webtechnologie_AG_AH_FH.pdf|INST_NEW|Down|1442514494|e226b1b6daab9d06352a3ec35e72e4bf|1687668|0073848650a4d1d37147d|4||0|0|0|||INST_NONE|
07:29:38|151|Schultage/2015 Sommersemester/TI5 Aarau/Casestudy/Angelo Florian Ali/CS_Wirtschaftlichkeitsanalyse_AG_AH_FH.pdf|INST_NEW|Down|1442513370|32c84182edb35c111d7e6224d51438c2|247169|0073848750a4d1d37147d|4||0|0|0|||INST_NONE|
|0|Schultage/2015 Sommersemester/TI5 Aarau/Casestudy/Angelo Florian Ali/DB local|INST_NEW|Down|1443120593|560445d1e96ad|0|0073848850a4d1d37147d|4||0|0|0|||INST_NONE|
|0|Schultage/2015 Sommersemester/TI5 Aarau/Casestudy/Angelo Florian Ali/DB local/DB ver 17-09 final|INST_NEW|Down|1443120592|560445d1e98a5|0|0073848950a4d1d37147d|4||0|0|0|||INST_NONE|
```

**Comment by ckamm** [comment]
@a-schild Can you reproduce this situation?

The second client should be querying the server regularly to check whether new data is available. It sounds like something went wrong there. If you can reproduce it, it'd be very useful to see a client log (https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly), in particular the lines that contain etag (ignoring case).

@Dianafg76 Does this work for you correctly on Win10? (start client 1,2; upload on client 1; client 2 automatically downloads after <2min)

**Comment by a-schild** [comment]
@ckamm Yes, did happen today again. Will try to get a client log with the ETag

**Comment by benmichael** [comment]
I am observing this exact problem.  I will try to reproduce and get logs for you tomorrow.

**Comment by OoTBDS** [comment]
I've been experiencing the same problem.
PC A : Shares files -> Uploaded to server
PC B-C-D : Receives files from server -> Edit's files -> Uploaded to server
PC A : Doesn't see changes (Log in to server and the changes are there)
PC A : Create random .txt file (Client Sync's and Pulls B-C-D's Changes)

I experienced this with Client 1.8.1 and now with 2.0.1

Here is a part of the log where I created the .txt file:
> |0|HSAS Workflow|INST_SYNC|Up|1443772320|5601579312594|4096||0||0|0|1442928528|5601579312594|00018279ocr4fnd90nu3|INST_NONE|
> 07:52:07|491|HSAS Workflow/New Text Document.txt|INST_NEW|Up|1443772320||0||4||201|0|0|||INST_NONE|
> #=#=#=# Syncrun started 2015-10-02T09:52:07 until 2015-10-02T09:52:09 (2087 msec)
> |0|HSAS Workflow|INST_SYNC|Down|1443772320|560e37a8343af|0|00018279ocr4fnd90nu3|0||0|4096|1443772320|5601579312594||INST_NONE|
> 07:52:13|554|HSAS Workflow/Management.xlsx|INST_SYNC|Down|1443765912|65006651cea72eda30cc98b948672840|13286|00018280ocr4fnd90nu3|4||0|13265|1443686426|36f072efb8d4082da98a3c662113ab20||INST_NONE|
> 07:52:14|812|HSAS Workflow/Work Flow - D.xlsx|INST_SYNC|Down|1443767883|7276e5ee659133d3666bb1ebf6c9d1dc|20149|00018536ocr4fnd90nu3|4||0|19916|1443595022|fe401932785757f63c5b26025ff6cdc3||INST_NONE|
> 07:52:14|1173|HSAS Workflow/Work Flow - J.xlsx|INST_SYNC|Down|1443765994|996c0dca900f54f8920a6300bd9f3402|30625|00018544ocr4fnd90nu3|4||0|30462|1443687723|9d17101b134bbfeda64514774201911c||INST_NONE|
> #=#=#=# Syncrun started 2015-10-02T09:52:12 until 2015-10-02T09:52:13 (1220 msec)
> |0|HSAS Workflow|INST_SYNC|Up|1443772329|560e37a8343af|4096||0||0|0|1443772320|560e37a8343af|00018279ocr4fnd90nu3|INST_NONE|
> 07:52:17|534|HSAS Workflow/New Text Document.txt|INST_RENAME|Up|1443772320|b1309d50992000fae5d29cb4348d8021|0|00035964ocr4fnd90nu3|4||201|0|0|||INST_NONE|
> #=#=#=# Syncrun started 2015-10-02T09:52:18 until 2015-10-02T09:52:19 (809 msec)
> #=#=#=# Syncrun started 2015-10-02T09:52:22 until 2015-10-02T09:52:22 (813 msec)
> 07:52:27|422|HSAS Workflow/1.txt|INST_REMOVE|Up|1443772320|b1309d50992000fae5d29cb4348d8021|0|00035964ocr4fnd90nu3|4||204|0|0|||INST_NONE|
> #=#=#=# Syncrun started 2015-10-02T09:52:27 until 2015-10-02T09:52:27 (879 msec)

**Comment by OoTBDS** [comment]
I just found that Pausing, and then Resuming Synchronization forces the client to pull from the server. Is there any way we could fix this?

**Comment by a-schild** [comment]
This night it did sync as it should, not sure what else is needed to trigger the problem.
But I can confirm that pausing & resuming sync on the client does then retrieve the changes from the server.

**Comment by OoTBDS** [comment]
After setting force sync in configfile.cpp to True, I have found that the syncing isn't the issue, the client connects when it should and does what it should. The issue has to do with the client not being able to find that the edited file is actually different.

So I ran a Log and located a file that I've been using for testing:

Test.xlsx was created on machine A and Shared with User B
On User B's machine it was edited and saved.
User A's Client doesn't pickup the change (Yet I can see the update on the server). Because as you can see in this log it see's that there is no change. Both etags are identical **etag: 705464020b71310cc40f44042b280c2b <-> 705464020b71310cc40f44042b280c2b**

` 10-07 14:17:27:752 0x26e3db0 csync_ftw: Uniq ID from Database: HSAS Workflow/Work Flow - Test.xlsx -> 705464020b71310cc40f44042b280c2b
10-07 14:17:27:752 0x26e3db0 csync_walker: file: C:/Users/Darren White/H&S/HSAS Workflow/Work Flow - Test.xlsx [inode=185157 size=10702]
10-07 14:17:27:752 0x26e3db0 _csync_detect_update: Database entry found, compare: 1444211035 <-> 1444211035, etag: 705464020b71310cc40f44042b280c2b <-> 705464020b71310cc40f44042b280c2b, inode: 185157 <-> 185157, size: 10702 <-> 10702, perms:  <-> RDNVW, ignore: 0
10-07 14:17:27:752 0x26e3db0 _csync_detect_update: file: HSAS Workflow/Work Flow - Test.xlsx, instruction: INSTRUCTION_NONE <<= `

**Comment by benmichael** [comment]
If we're talking etags, it looks like we may have [this issue] (https://github.com/owncloud/core/issues/11098) all over again, this time affecting windows clients.

That ticket was labeled **sev2-high** and was given a golden ticket as a **showstopper**.  So we may want to look into this urgently.

**Comment by dragotin** [comment]
@OoTBDS well done, that is exactly how to tackle this issue. No ETag change means no sync. Clear server issue.

**Comment by OoTBDS** [comment]
We solved this this issue by upgrading the server from 8.0.2 to 8.1.3. Thanks @dragotin for pointing us in the right direction, I was under the impression at first that the sync client was to blame.

**Comment by dragotin** [comment]
Ok, seems it's solved server side. Thanks!
