### ISSUE TITLE
[2.0.2] If you share a folder with another user , and then rename the folder on the desktop does not change the name

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3885]
### Steps to reproduce
1. Install v 2.0.2 with 2 accounts (user1, user2)
2. Go to Server client with user1
3. Create a new folder (e.g call Share with)
4. Click on Share
5. And share with user2
6. Go to Desktop client with user2
7. Wait sync (you can see the folder (Share with)
8. Go to Server client with user1
9. Rename the Folder "Share with" to "Share with user2"
10. Go to Desktop client with user2
11. Wait sync 

### Expected behaviour
the folder name must change

### Actual behaviour
the folder name has not change

### Server configuration
Desktop v  ownCloud-2.0.2.2744-nightly20150925.pkg on MAC
Desktop v  ownCloud-2.0.2.5490-nightly20150925-setup.exe  on WIN
Server {"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"}

**Comment by dragotin** [comment]
IIRC this is intended behaviour. If you get a share, the name of the top directory that appears in your file list is "yours". It can be changed, and changes to the name of the original directory are not propagating through. @PVince81

**Comment by dragotin** [comment]
@PVince81 can you enlighten us? Thanks

**Comment by PVince81** [comment]
Yes.
The shared folder is actually a virtual mount point for all recipients, so renaming it doesn't affect all recipients. Only the **contents** of it will be visible for anyone.

Works as expected.
