### ISSUE TITLE
Unable to initialize a sync journal (2.0.0-rc2+)

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/client#3887]
### Expected behaviour
ownCloud syncronization just works (as it did with 1.8.1)

### Actual behaviour
All directories are synced properly (including federated from other servers), except directory called `ownCloud` (one of root directories).

### Steps to reproduce
1. Have ownCloud server and user profile there
2. Create `ownCloud` directory (literally) in the root and some other
3. Have ownCloud client 1.8.1
4. Configure `ownCloud` directory to be synced somewhere and other directory (-ies) also in different place
5. Upgrade to ownCloud 2.0.0-rc2+
6. `ownCloud` directory in client will become red with message `Unable to initialize a sync journal`
7. When you click arrow on the left you can see that all root directories are now there, namely `ownCloud` now corresponds to `/` on server, rather than `/ownCloud` as it was previously configured

### Server configuration
Operating system: Ubuntu 14.04.3 LTS x64 (Docker container)

Web server: Nginx

Database: MariaDB 10.0.7

PHP version: 5.6.10

ownCloud version: 8.1.3 (same was on 8.1.1, so server doesn't seem to be an issue here)

Storage backend: Local

### Client configuration
Client version: 2.0.1 stable (happened on 2.0.0-rc2 as well, but not on 1.8.1).

Operating system: Ubuntu 15.10 x64

OS language: Ukrainian

Installation path of client: Default deb package installation

#### ~/.local/share/data/ownCloud/folders/ownCloud
> [ownCloud]
backend=owncloud
connection=ownCloud
localPath=/home/nazar-pc/ownCloud/
targetPath=/ownCloud

Seems to be correct, namely `targetPath=/ownCloud`, but is treated as `/` indeed

**Comment by nazar-pc** [comment]
Also client takes 2.7 GiB of RAM and quite a lot of time to start (while I can afford that much RAM, it is not suitable for majority of people), but I expect it to be result of this current issue.

**Comment by guruz** [comment]
2.0 has the folder directly in ```owncloud.cfg``` not in the ```folders``` subdir.
Could you remove the new entries from ```owncloud.cfg``` and retry with a nightly build?
This might have been fixed already..

http://download.owncloud.com/desktop/daily/

**Comment by nazar-pc** [comment]
From `owncloud.cfg`:
> 0\Folders\ownCloud\ignoreHiddenFiles=false
0\Folders\ownCloud\localPath=/home/nazar-pc/ownCloud/
0\Folders\ownCloud\paused=false
0\Folders\ownCloud\targetPath=ownCloud

Nightly builds are weird `*.pkg` files, no deb/rpm builds.

**Comment by guruz** [comment]
@nazar-pc Sorry, didn't see you were using Linux.

Yes, remove the section that contains that.

Then try the nightly from : https://build.opensuse.org/project/show/isv:ownCloud:community:nighly/

Then see if it works now.

FYI @ckamm @dragotin

**Comment by nazar-pc** [comment]
Removed that section and tried nightly - fast start, everything seems to work fine and memory use is just 42.3 MiB.

As I understand now I can remove `folders` subdirectory, which sections in `owncloud.cfg` are also unnecessary now? (I like to keep system clean)

**Comment by guruz** [comment]
@nazar-pc Great to hear!
Yes, you can remove ```folders``` directory. No idea about the sections...
