### ISSUE TITLE
[OS X] [2.0.x] Tray menu "Recent Changes" don't always update

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3889]
Sometimes they get updated, sometimes no.
Sometimes the last updates are deleted and it just shows "No changes"
(5 accounts active)

Reprodued by both me and @jturcotte

**Comment by guruz** [comment]
Also seen https://github.com/owncloud/client/issues/2236 by @tessus

**Comment by Dianafg76** [comment]
I tested this issue and for my is working OK
Desktop v ownCloud-2.1.0.2875-nightly20151113.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}
Closed
