### ISSUE TITLE
SSLv3 on OSX Sync Client v2.0.1

### ISSUE THREAD

**Issue by ZiiX** [owncloud/client#3890]
Is there a reason why my Mac OSX sync client with this v# is connecting with SLLv3 and not a better TLS like TLS1.2? I do not think the client should be allowed to use a different TLS/cipher suite than what I personally am comfortable with. My server config w cert doesn't allow SSLv3 at all on login via the webclient so why is this forcing v3? When I click on the green lock icon in my mac osx sync client it only says SSLv3 RSA DH AES(256).  Thanks for all the great work - just inquiring concerning forcing the best TLS we can use on all apps. I don't know how to check which version my iOS app is using but this is obviously a concern too. ...random question too but is my data being sent through an owncloud server and this is why?

**Comment by danimo** [comment]
Check `Settings -> General -> About` and check the OpenSSL version. It _should_ show version 1.0.2x. Does it?

**Comment by ZiiX** [comment]
Yes, it shows: 1.0.2d Jul 2015.

**Comment by danimo** [comment]
@ZiiX and your server is really capable of SSLv3? We have reports of misreported SSL versions.

**Comment by ZiiX** [comment]
No, it shouldn't that I'm aware of...  my config file says no -SSL should be used at all. Only +TLS1

**Comment by danimo** [comment]
@ZiiX This would mean that the SSL version is reported incorrectly. Can you still run ssllabs.com nontheless?

**Comment by ZiiX** [comment]
Update: Comodo's ssl analyzer AND SSLLabs test on my domain confirms SSL not supported at all still - hence my confusion/submission. Thank you for your attention & time today.

**Comment by danimo** [comment]
@ZiiX if you could reveal your installation to me (danimo AT owncloud DOT com), I'd like to check why the reporting goes wrong.

**Comment by guruz** [comment]
@ZiiX Which client version?

@danimo Maybe related/fixed with the Qt fix I did last week?

**Comment by danimo** [comment]
@guruz Can point me to the patch again?

**Comment by ZiiX** [comment]
Client Says: Built from Git revision 58ea49 on Sep 1 2015, 16:36:52 using Qt 5.4.0, OpenSSL 1.0.2d 9 Jul 2015 on production OwnCloud 8.1.3

**Comment by guruz** [comment]
Could be a glitch fixed by https://codereview.qt-project.org/#/c/126271/ https://codereview.qt-project.org/#/c/141490/

**Comment by guruz** [comment]
@ZiiX How is the situation with 2.1.1?

**Comment by ZiiX** [comment]
@guruz/@danimo, sorry for slow reply; traveling for work. All works and shows best SSL/TLS avail. Awesome work & appreciated.

**Comment by guruz** [comment]
:+1:
