### ISSUE TITLE
[OS X] client/csync/src/std/c_string.c:289:23: error: use of undeclared identifier 'iconv_from_native' 

### ISSUE THREAD

**Issue by EamonnDH** [owncloud/client#3891]
### Expected behaviour
Client build successfully on OSX.

### Actual behaviour
Partially completes (1%). Throws two errors:
client/csync/src/std/c_string.c:289:23: error: use of undeclared identifier 'iconv_from_native' 
client/csync/src/std/c_string.c:321:24: error: use of undeclared identifier 'iconv_to_native' OSX 

then fails.

### Steps to reproduce
1. https://doc.owncloud.org/desktop/2.0/building.html Following OSX instructions, steps 1-3 followed. (There is no step 4?)
2. Follow generic build instructions, with "cmake -DCMAKE_BUILD_TYPE="Debug" -CMAKE_PREFIX_PATH=/usr/local/opt/qt5/  ../client
3. Call make.

### Client configuration
Client version: Latest git (master), as of 27/09/15

Operating system: OS X 10.10.2 14C1510

OS language: UK English

### Logs

``[  1%] Building C object csync/src/std/CMakeFiles/cstdlib.dir/c_string.c.o
/Users/eamonn/client/csync/src/std/c_string.c:289:9: warning: implicit
      declaration of function 'c_iconv' is invalid in C99
      [-Wimplicit-function-declaration]
  dst = c_iconv(wstr, iconv_from_native);
        ^
/Users/eamonn/client/csync/src/std/c_string.c:289:23: error: use of
      undeclared identifier 'iconv_from_native'
  dst = c_iconv(wstr, iconv_from_native);
                      ^
/Users/eamonn/client/csync/src/std/c_string.c:321:24: error: use of
      undeclared identifier 'iconv_to_native'
    dst = c_iconv(str, iconv_to_native);
                       ^
1 warning and 2 errors generated.
make[2]: *** [csync/src/std/CMakeFiles/cstdlib.dir/c_string.c.o] Error 1
make[1]: *** [csync/src/std/CMakeFiles/cstdlib.dir/all] Error 2
make: *** [all] Error 2``

**Comment by LukasReschke** [comment]
@ogoffart Any idea? :-)

**Comment by LukasReschke** [comment]
Ref https://github.com/owncloud/client/issues/3165 and https://github.com/owncloud/client/issues/3164 which were closed by @guruz due to missing information but have the same error message

**Comment by guruz** [comment]
Maybe it's trying to use some iconv from ```/usr/local/``` instead of ```/usr/lib/``` ?

**Comment by guruz** [comment]
Also note ```master``` is not used at the moment, use branch ```2.0```

**Comment by EamonnDH** [comment]
> Maybe it's trying to use some iconv from /usr/local/ instead of /usr/lib/ ?
How can I tell?

**Comment by guruz** [comment]
```
guruz@mgmacbookpro buildmirall $ cat CMakeCache.txt |grep iconv
ICONV_LIBRARY:FILEPATH=/usr/lib/libiconv.dylib
...
```

Check your ```cmake``` output too.

**Comment by EamonnDH** [comment]
INCONV_LIBARY:FILEPATH=/opt/local/lib/libiconv.dylib
How can I change this?

**Comment by guruz** [comment]
You don't. Delete ```CMakeCache.txt``` and run ```cmake``` with good parameters.

**Comment by EamonnDH** [comment]
>You don't. Delete CMakeCache.txt and run cmake with good parameters.

'Good' parameters? All I've got to go off is what I'm given in the build instruction page.

**Comment by dragotin** [comment]
Sorry, please get build support from forum or mailinglist. This is a bug tracker.

**Comment by gojkokbc** [comment]
I have same problem, did you found solution?

**Comment by linamu** [comment]
I also have this error did you fix it ?

**Comment by danimo** [comment]
Uninstall iconv from brew/ports.

**Comment by linamu** [comment]
where to find brew/ports !

**Comment by linamu** [comment]
what's brew/ports ?!

**Comment by guruz** [comment]
@linamu Which OS are you on? Which git branch?

**Comment by linamu** [comment]
@guruz i'm building it on openwrt

**Comment by linamu** [comment]
@guruz i'm building it on openwrt

master and i try 2.0 and it's the same

**Comment by danimo** [comment]
@linamu OpenWRT does probably not provide iconv as part of its libc implementation, so you'll need it as a separate library. Note that you will most likely not succeed building the client for OpenWRT until someone removes the QtGui dependency from the core lib.
