### ISSUE TITLE
[OS X ] [1.8.1] macdeployqt doesn't add all qt frameworks to .app file in OSX 10.10.4

### ISSUE THREAD

**Issue by tusharh** [owncloud/client#3894]
I am using 1.8.1 version. After running cmake & make, I tried running the macdeployqt.py & also tried running macdeployqt from it's location. whenever I run it, I get errors but the strings are empty. It doesn't specify the path or files for which it is getting errors. Here is the output - 

tushar-iMac:bin tushar$ macdeployqt /Users/tushar/Documents/Repo/Sync/trunk/client-1.8.1/client-build/bin/owncloud.app
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""
ERROR: no file at ""

**Comment by guruz** [comment]
Did you try ```make install``` instead?

**Comment by tusharh** [comment]
Yeah. I did cmake, make, macdeployqt & then make install.
In order to run the .app on other machine we need to run macdeployqt to add required frameworks.

**Comment by guruz** [comment]
```make install``` does that for you.
It generates a proper ```.app``` in the install dir with all dylibs properly set, I just checked my own ```owncloud``` with ```otool -L```.

**Comment by tusharh** [comment]
Can you check the size? If you run only cmake,make,make install generated .app file is only 13.5 MB. Where as if you download the client from https://owncloud.org/install/#install-clients and install it in Applications folder, it has size around 70 to 80 MB. Because it has all required dylibs bundled in it. You need macdeployqt for this reason, to bundle required frameworks/libs,etc

**Comment by guruz** [comment]
```
guruz@mgmacbookpro buildmirall $ du -sh ../install/owncloud.app/
 84M	../install/owncloud.app/
```

Check the output of ```make install``` maybe it mentions some hint on what is wrong?

**Comment by guruz** [comment]
Let's use IRC (#owncloud-client-dev on freenode) or forum for build help

**Comment by tusharh** [comment]
Hi, 

Got the reason why it wasn't building the app properly. On firing brew install $(brew deps owncloud-client) it installed qt5.5.0. I checked the 1.8.1 oc client downloaded earlier by me. On seeing Owncloud-->General-->About it said OC client was built using QT 5.4.0 for 1.8.1 client. I downgraded to 5.4.1 & now the app builds perfectly.

Thanks for your time.
