### ISSUE TITLE
[2.0.1] [Shibboleth] No relogin window

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#3895]
### Expected behaviour

The desktop sync client should show the login (WebKit) window after the Shibboleth session terminates.

### Actual behaviour
The desktop sync client won't open a WebKit pop up after the terminated Shibboleth session

### Steps to reproduce
1. Login with Shibboleth
2. Wait for Shibboleth session termination

### Client configuration
Client version:
2.0.1 (branded)

Operating system:
Windows, Mac OS X

@dragotin Who can help here? /cc @MorrisJobke 

00003904, 00003885

**Comment by dragotin** [comment]
@Dianafg76 can you try to reproduce that? You would need a shib instance with very short session lifetime...

**Comment by Dianafg76** [comment]
@dragotin I tested this issue and I can reproduce If you change the session length to 120 seconds and 120 seconds when passed , the client desktop synchronization WebKit does not open a pop -up after the session ends Shibboleth.

Desktop v ownCloud-2.0.2.2750-nightly20150928.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
@michaelstingl Could you try: ownCloud-2.0.2.2750-nightly20150928.pkg
Thanks

**Comment by dragotin** [comment]
@michaelstingl we tested on all platforms, Mac, Win and Linux, and the re-login dialog appeared with the current beta version of 2.0.2

**Comment by dragotin** [comment]
Tested even without folder configuration, works, window pops up.

**Comment by Dianafg76** [comment]
@michaelstingl Could you try: http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.2750-nightly20150928.pkg
Thandks

**Comment by Dianafg76** [comment]
You need change the lifetime and the timeout
Sessions lifetime="120" timeout="120", and is working

if this didn't work for you, please reopen
Thanks
