### ISSUE TITLE
Debian Release.key not available in secure way

### ISSUE THREAD

**Issue by kuking** [owncloud/client#3897]
Following the guide in located in:
```https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client ```
(direct link form ```https://owncloud.org/install/```)

It instructs me to download the file ```Release.key``` from an unsecure source (```download.opensuse.org``` does not have a SSL/HTTPS site).

Can the key be installed into my system in a secure way? I have noticed, it can be done in Ubuntu (as described in a forum). but I'm not sure in Debian and I couldn't find anything in the documentation. I'm not an expert with OwnCloud but I believe the key should be distributed in a secure way, at least from the Download link in the homepage.

I love OwnCloud, Thanks for it!

Apologies if not the right bugtracker but you have so many different bugtrackers that it is difficult to understand.

**Comment by guruz** [comment]
FYI @hefee

**Comment by danimo** [comment]
@guruz OBS is not really @hefee's issue...

**Comment by jnweiger** [comment]
We use opensuse infrastructure to deploy keys and packages. The key was created by the opensuse build service. I don't have any other way to retireve the key than through http. 

A (weaker) verification would be to consult the mirrors listet at the bottom of e.g.
```
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/Packages?mirrorlist
```
And retrieve the Release.key from there and compare.

**Comment by kuking** [comment]
You can just upload the key to your https domain, or at least put a hash of the file in the installation description -which happens to be in an opensuse https domain-

Checking mirrors is "false security" IMHO.

**Comment by jnweiger** [comment]
@kuking You are right. Checking mirrors is weak. 
We cannot edit the installation description at software.opensuse.org -- this is fully auto-generated on their side. We have keys available via HTTPS on owncloud.org, but I am not sure the the key linked with packages is helpful when checking packages. Maybe it is a subkey or signs some other key. But it differs, from what we use in obs. Opened https://github.com/owncloud/owncloud.org/issues/724

**Comment by kuking** [comment]
Thanks for all the details! I just wanted to make you aware that for the common guy installing in Debian; the installation process is a bit 'weak' from a security perspective. I can close the ticket if you want, but bear in mind another random guy might come after me mentioning the same issue.

tl/dr I'm happy with the support, I was able to verify my key; but I would sugguest you to streamline a bit the security for Debian client installation.

**Comment by jnweiger** [comment]
We have uploaded the key to our https domain, linked it from the installation web page. https://owncloud.org/wp-content/themes/owncloudorgnew/assets/files/obs-release-signing.gpg is available in a secure way and can be used to verify the packages. This solves the issue from my perspective.

Do you have further improvement suggestions?

**Comment by guruz** [comment]
Please comment if there is more to do, thanks :)

**Comment by kuking** [comment]
Hi sorry, here. It solved my problem, thanks for it. Perhaps I would link that gpg pubkey from the 'Download' page but no need for me. Thanks for everything.
