### ISSUE TITLE
Windows 8 \ 8.1 - Map owncloud driver as network drive

### ISSUE THREAD

**Issue by eranag** [owncloud/client#3900]
Hello,

When I map an Owncloud drive as WebDAV drive in windows 8 \ 8.1 it prompt for username and password every time that I am trying to open a PDF \ Office file. 

There is a KB from Microsoft that described the problem and fix it, but it is for windows 7 only: 

https://support.microsoft.com/en-us/kb/943280

Prompt for Credentials When Accessing FQDN Sites From a Windows Vista or Windows 7 Computer

The bypass that I found is to do a local share for the folder that Owncloud client sync and then map this drive as a network drive. 

Can this feature of share and map can be added to the owncloud client?

Thank You,
Eran Agmon 
System Engineer
• OMC Computers and Communications LTD

**Comment by dragotin** [comment]
I can not understand what the bug or even feature request you exactly talk about here. Can you be more specific and use the bug report template? Thanks.

**Comment by eranag** [comment]
I think it is  feature request  and not a bug because currently you the client software does not include an option to map the sync folder as a network drive.

**Comment by danimo** [comment]
This is an issue with between ownCloud Server and Windows. Is not related to the ownCloud sync client, which this is issue tracker for. Closing hence.
