### ISSUE TITLE
When server files with invalid paths are ignored, the error is only visible in the activity tab

### ISSUE THREAD

**Issue by hmcs** [owncloud/client#3902]
Hi,

Via Web it is possible to create a directory-name ending with a space like "my folder " (tested on owncloud Server 8.1.3).
The Windows-client (Version 2.0.1) has problems syncing this folder because spaces at begining or ending are not allowed in windows. Nasty, it generates no error in log.

I assume, this apply also to files but not tested.

regards,

henry

**Comment by Dianafg76** [comment]
Hello
1. Go to the Server Web with user2
2. Create new folder (e.g. call "File with space ")
3. Go to the Desktop Client with user2
4. Wait for Sync
5. You can see the folder "File with space "
![screen shot 2015-09-29 at 12 45 06](https://cloud.githubusercontent.com/assets/12032058/10161986/111c23fa-66a8-11e5-98dc-ebdeca2045b4.png)
6. If you open the folder c:/....../user2, you can't see the folder "File with space "
![screen shot 2015-09-29 at 12 47 44](https://cloud.githubusercontent.com/assets/12032058/10162014/55b7189e-66a8-11e5-9e38-8d4beb5b8da9.png)
7. On the Desktop Client if you click on Settings...
8. Click ib Activity option, you can see: 
![screen shot 2015-09-29 at 12 49 40](https://cloud.githubusercontent.com/assets/12032058/10162051/a5873bb0-66a8-11e5-9489-c21c8388f61f.png)

**Comment by Dianafg76** [comment]
I tested on WIN 10
Desktop v ownCloud-2.0.2.5499-nightly20150928-setup.exe

**Comment by Dianafg76** [comment]
And If you create a new folder on the desktop client is created without problem

**Comment by hmcs** [comment]
shouldn't begining/ending "spaces" be not allowed in web-interface?

**Comment by Mistress-Anna** [comment]
Leading/trailing whitespace is generally a user typo anyway, which can be easily trimmed.

File and folder names shouldn't end with spaces or periods on windows:

> Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not. However, it is acceptable to specify a period as the first character of a name. For example, ".temp".

https://msdn.microsoft.com/en-us/library/windows/desktop/aa365247%28v=vs.85%29.aspx#naming_conventions

This also means "foobar..." is not an acceptable folder name on windows.

**Comment by ckamm** [comment]
So
* We might want to evaluate whether the client should produce a louder error when it's ignoring server files that are not valid on the current system. I think this is low-priority and not for 2.0.2.
* The web interface should not allow creating files or folders with leading/trailing spaces.

I'll create a new ticket against the server for the second part and adjust this ticket for first.

**Comment by ogoffart** [comment]
The hiding of them in the selective sync tree was fixed in #3876

The fact that ignored files/directories should be made more visible is another problem and there are other issues about that.
