### ISSUE TITLE
Misleading Dialog in Ignored Files Selection

### ISSUE THREAD

**Issue by JKawohl** [owncloud/client#3904]
### Expected behaviour

The settings should be enabled  by default  for all hidden files, to delete the directories they are in.
Also the dialogue itself is to complex for non-technical users.
### Actual behaviour

![bildschirmfoto 2015-09-30 um 11 13 49](https://cloud.githubusercontent.com/assets/12275313/10189199/23e480dc-6765-11e5-9640-18f477ab928d.png)
### Steps to reproduce
1. Go to owncloud client settings Mac OSX Windows and Linux 
### Client configuration

Client version: 2.0.1

Operating system:OSX, Linux Windows

@hodyroff
@dragotin

**Comment by TheOneRing** [comment]
Hidden files are not synced for reasons.
The ignored files dialog is an advanced setting and only meant for advanced users.
