### ISSUE TITLE
[Selfcompiled] Windows Shell Extensions dont show the icon

### ISSUE THREAD

**Issue by supportreq** [owncloud/client#3905]
I compiled the Owncloud client using the cross compile opensuse method, the windows shell extension and even the windows app is coming without the icons.. any idea?

Thanks!

**Comment by supportreq** [comment]
It worked after i installed kdewin-png2ico package... I guess we should have this updated in our build document..

**Comment by pierrejochem** [comment]
https://github.com/danimo/docker-ownCloud-client-win32 :wink:
