### ISSUE TITLE
Make sqlite errors fatal

### ISSUE THREAD

**Issue by guruz** [owncloud/client#3906]

**Comment by dragotin** [comment]
Not sure what you mean with fatal, or which Sqlite errors you mean, but @ogoffart will find out :-)

**Comment by ogoffart** [comment]
sqlite errors are already fatal (SyncJournalDb::sqlFail asserts)

**Comment by guruz** [comment]
We had this discussion before: Assert is not fatal in release mode.

**Comment by guruz** [comment]
Also why does ```sqlFail``` do ```commitTransaction();```?

**Comment by ogoffart** [comment]
But we do not want to crash in release mode, we want to show proper error.

**Comment by guruz** [comment]
Closing in favor of https://github.com/owncloud/client/issues/4632
