### ISSUE TITLE
OwnCloud sync on windows client issue. 

### ISSUE THREAD

**Issue by vijaykumar0690** [owncloud/client#3907]
Hi Team,

When i try to upload or create a new directory and upload files in to the owncloud. The sync is not working as expected and its failing with an error message
Continue blacklisting: Error downloading https://cloud.weh.com/remote.php/webdav/bizruntime/Vijay/Amazon EC2 and Microsoft Windows Server 2012.mp4-chunking-3890005629-5-0 - server replied: Internal Server Error

I am attaching the log file. My server is running as expected.
Need help on the above issue.

My server is running on aws, Ubuntu server 12.04
Database is mysql.

Regards,
Vijay
![sync_error](https://cloud.githubusercontent.com/assets/10925174/10222230/8d0a0aa8-6870-11e5-88c7-d63118f361d8.jpg)

**Comment by dragotin** [comment]
Sorry, but you have an server issue, which "Internal Server Error" is a clear indication. Please check with your server.

**Comment by vijaykumar0690** [comment]
But my server is up and running fine.
cloud.weh.com is my owncloud server.

regards,
Vijay

**Comment by dragotin** [comment]
No, otherwise it would not report an internal server error. Check the web servers error log.
