### ISSUE TITLE
OCC::LsColXMLParser::parse: ERROR with encoding (invalid bytes in WebDAV property)

### ISSUE THREAD

**Issue by philippeVerney** [owncloud/client#3908]
Since this morning (I did not change any version), I face an issue with owncloud sync desktop on windows.
I use owncloud 8.1.3 on server side and Version 2.0.1 (build 5446) on client side.

Looking at the server log, I have no problem. For information, I can go on the web interface without any problem at all.
Looking at the client log, I can see that the first error is : OCC::LsColXMLParser::parse: ERROR "Du contenu avec un encodage incorrect a été rencontré."
which means something like 'The encoding of the content is incorrect'

After this error, I can see the XML response which is : 
```
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns">
<d:response><d:href>/owncloud/remote.php/webdav/Documents/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getlastmodified>Thu, 01 Oct 2015 14:16:22 GMT</d:getlastmodified><d:getetag>"560d4036d3df5"</d:getetag><oc:id>00000117ocrs04auguic</oc:id><oc:permissions>RDNVCK</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/><oc:downloadURL/><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response>
<d:response><d:href>/owncloud/remote.php/webdav/Documents/Example.odt</d:href><d:propstat><d:prop><d:resourcetype/><d:getlastmodified>Thu, 01 Oct 2015 14:16:22 GMT</d:getlastmodified><d:getcontentlength>36227</d:getcontentlength><d:getetag>"5cbac5b840e7318425394e90a8f32e07"</d:getetag><oc:id>00000118ocrs04auguic</oc:id><oc:downloadURL>PV????&#13;</oc:downloadURL><oc:permissions>RDNVW</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat>
</d:response>
</d:multistatus>
```

Any idea of what has happened?

**Comment by guruz** [comment]
The XML Response looks OK to me and I can't find what could cause this.
Is there anything in server's ```owncloud.log```?

**Comment by philippeVerney** [comment]
I am going to put log in Debug mode on server side. In default mode, there is nothing in owncloud.log.
I was thinking the string value in <oc:downloadURL> XML tag in the second response element tag could be an encoding issue.

**Comment by philippeVerney** [comment]
In debug mode, I have some new items in owncloud.log

EException: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Code":0,"Trace":"#0 \/home\/secret\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(149): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#1 \/home\/secret\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(122): OC\\Connector\\Sabre\\Auth->auth(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#2 \/home\/secret\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/home\/secret\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/home\/secret\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#6 \/home\/secret\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/home\/secret\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#8 \/home\/secret\/www\/owncloud\/remote.php(132): require_once('\/home\/secret\/...')\n#9 {main}","File":"\/home\/secret\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70}

then (probably the same)

Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Code":0,"Trace":"#0 \/home\/secret\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(149): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#1 \/home\/secret\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(122): OC\\Connector\\Sabre\\Auth->auth(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#2 \/home\/secret\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/home\/secret\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/home\/secret\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#6 \/home\/secret\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/home\/secret\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n#8 \/home\/secret\/www\/owncloud\/remote.php(132): require_once('\/home\/secret\/...')\n#9 {main}","File":"\/home\/secret\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70}

**Comment by guruz** [comment]
I must have been blind :-)
```<oc:downloadURL>�PV????�&#13;</oc:downloadURL>``` is of course bogus.
This should be empty / 404..

This is a server bug. Was anything else related updated possibly, maybe the PHP version?

@PVince81 @DeepDiver1975 @icewind1991 can you help?

**Comment by philippeVerney** [comment]
Since I am using a shared host (OVH which is a big one in Europe), there could have been update which I don't know on the server side.
phpinfo tells me I am using PHP 5.6.6

**Comment by philippeVerney** [comment]
I just woke up today and it works back.
No idea of what has happened. Probably something on server side from my host.

**Comment by philippeVerney** [comment]
I still have the same issue.
It occurs rarely (about one day per month) and I would say "randomly".

I upgraded to owncloud 8.2 and owncloud client 2.0.2. Here are the log messages

Owncloud client
----------------------------
11-03 11:24:37:651 0x7266188 csync_ftw: URI without fuzz for ownclouds://www.mydomain.com/owncloud/remote.php/webdav is ""
11-03 11:24:37:651 0x7266188 OCC::DiscoveryJob::remote_vio_opendir_hook: static csync_vio_handle_t* OCC::DiscoveryJob::remote_vio_opendir_hook(const char*, void*) OCC::DiscoveryJob(0x7c339f8)  Calling into main thread...
11-03 11:24:40:326 0x4487b70 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://www.mydomain.com/owncloud" + ""
11-03 11:24:41:570 0x4487b70 OCC::LsColXMLParser::parse: ERROR "Du contenu avec un encodage incorrect a été rencontré." "<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/owncloud/remote.php/webdav/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getlastmodified>Fri, 30 Oct 2015 14:18:39 GMT</d:getlastmodified><d:getetag>"56337c4081c90"</d:getetag><oc:id>00000116ocrs04auguic</oc:id><oc:permissions>RDNVCK</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/><oc:downloadURL/><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/2014/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getlastmodified>Tue, 06 Oct 2015 17:15:37 GMT</d:getlastmodified><d:getetag>"561401b9b5f8c"</d:getetag><oc:id>00000129ocrs04auguic</oc:id><oc:permissions>RDNVCK</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/><oc:downloadURL/><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/2015/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getlastmodified>Fri, 30 Oct 2015 14:18:39 GMT</d:getlastmodified><d:getetag>"56337c4083001"</d:getetag><oc:id>00000130ocrs04auguic</oc:id><oc:permissions>RDNVCK</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/><oc:downloadURL/><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/banque/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getlastmodified>Mon, 12 Oct 2015 09:25:54 GMT</d:getlastmodified><d:getetag>"561b7ca2b74ae"</d:getetag><oc:id>00000681ocrs04auguic</oc:id><oc:permissions>RDNVCK</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/><oc:downloadURL/><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/facturationRapide/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getlastmodified>Fri, 02 Oct 2015 07:33:13 GMT</d:getlastmodified><d:getetag>"560e3339ddcac"</d:getetag><oc:id>00000683ocrs04auguic</oc:id><oc:permissions>RDNVCK</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/><oc:downloadURL/><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/graphicDesign/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getlastmodified>Fri, 02 Oct 2015 07:33:19 GMT</d:getlastmodified><d:getetag>"560e333f69eb3"</d:getetag><oc:id>00000727ocrs04auguic</oc:id><oc:permissions>RDNVCK</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/><oc:downloadURL/><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/impots/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getlastmodified>Fri, 02 Oct 2015 07:33:28 GMT</d:getlastmodified><d:getetag>"560e3348a390f"</d:getetag><oc:id>00000728ocrs04auguic</oc:id><oc:permissions>RDNVCK</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/><oc:downloadURL/><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/kbis.pdf</d:href><d:propstat><d:prop><d:resourcetype/><d:getlastmodified>Mon, 24 Nov 2014 15:36:30 GMT</d:getlastmodified><d:getcontentlength>25781</d:getcontentlength><d:getetag>"201a4a1db7584d2484d7e4cdd2507138"</d:getetag><oc:id>00000736ocrs04auguic</oc:id><oc:downloadURL>??(???&#13;</oc:downloadURL><oc:permissions>RDNVW</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/keePassDatabase.kdbx</d:href><d:propstat><d:prop><d:resourcetype/><d:getlastmodified>Mon, 26 Oct 2015 12:50:31 GMT</d:getlastmodified><d:getcontentlength>38270</d:getcontentlength><d:getetag>"7fbf3a8bf6365ba83c93581b1f20b548"</d:getetag><oc:id>00000738ocrs04auguic</oc:id><oc:downloadURL>??(???&#13;</oc:downloadURL><oc:permissions>RDNVW</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/notesDeFrais/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getlastmodified>Fri, 30 Oct 2015 12:55:37 GMT</d:getlastmodified><d:getetag>"563368ca8117c"</d:getetag><oc:id>00000737ocrs04auguic</oc:id><oc:permissions>RDNVCK</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/><oc:downloadURL/><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/prevoyance/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getlastmodified>Fri, 02 Oct 2015 07:33:36 GMT</d:getlastmodified><d:getetag>"560e3350b36d1"</d:getetag><oc:id>00000740ocrs04auguic</oc:id><oc:permissions>RDNVCK</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/><oc:downloadURL/><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/registreUniqueDuPersonnel.txt</d:href><d:propstat><d:prop><d:resourcetype/><d:getlastmodified>Tue, 24 Mar 2015 09:42:24 GMT</d:getlastmodified><d:getcontentlength>657</d:getcontentlength><d:getetag>"fe6b8d607be01e28c56c76c956b07dd4"</d:getetag><oc:id>00000765ocrs04auguic</oc:id><oc:downloadURL>??(???&#13;</oc:downloadURL><oc:permissions>RDNVW</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/sante/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getlastmodified>Wed, 14 Oct 2015 08:49:31 GMT</d:getlastmodified><d:getetag>"561e171bbf2c0"</d:getetag><oc:id>00000767ocrs04auguic</oc:id><oc:permissions>RDNVCK</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/><oc:downloadURL/><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/signature.png</d:href><d:propstat><d:prop><d:resourcetype/><d:getlastmodified>Fri, 11 Apr 2014 12:55:38 GMT</d:getlastmodified><d:getcontentlength>3969</d:getcontentlength><d:getetag>"eaf2ab64f0387acd4e97b7a22ef17c19"</d:getetag><oc:id>00000771ocrs04auguic</oc:id><oc:downloadURL>??(???&#13;</oc:downloadURL><oc:permissions>RDNVW</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/tampon.png</d:href><d:propstat><d:prop><d:resourcetype/><d:getlastmodified>Fri, 11 Apr 2014 12:53:04 GMT</d:getlastmodified><d:getcontentlength>28829</d:getcontentlength><d:getetag>"2812ac7d7bea199bf4f665fc336984f3"</d:getetag><oc:id>00000778ocrs04auguic</oc:id><oc:downloadURL>??(???&#13;</oc:downloadURL><oc:permissions>RDNVW</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/tamponSigne.png</d:href><d:propstat><d:prop><d:resourcetype/><d:getlastmodified>Fri, 11 Apr 2014 12:57:14 GMT</d:getlastmodified><d:getcontentlength>34448</d:getcontentlength><d:getetag>"8f34ce8f10a0f702c1d308a2bda82ee2"</d:getetag><oc:id>00000779ocrs04auguic</oc:id><oc:downloadURL>??(???&#13;</oc:downloadURL><oc:permissions>RDNVW</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response><d:response><d:href>/owncloud/remote.php/webdav/salaries/</d:href><d:propstat><d:prop><d:resourcetype><d:collection/></d:resourcetype><d:getlastmodified>Thu, 15 Oct 2015 09:29:36 GMT</d:getlastmodified><d:getetag>"561f7200c2d46"</d:getetag><oc:id>00000023ocrs04auguic</oc:id><oc:permissions>SDNV</oc:permissions></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat><d:propstat><d:prop><d:getcontentlength/><oc:downloadURL/><oc:dDC/></d:prop><d:status>HTTP/1.1 404 Not Found</d:status></d:propstat></d:response></d:multistatus>
"
11-03 11:24:41:642 0x4487b70 OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot: void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply*) "Erreur inconnue" 207 0
11-03 11:24:41:643 0x4487b70 OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot: void OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot(int, QString) 5 "Erreur inconnue"
11-03 11:24:41:646 0x7266188 OCC::DiscoveryJob::remote_vio_opendir_hook: static csync_vio_handle_t* OCC::DiscoveryJob::remote_vio_opendir_hook(const char*, void*) OCC::DiscoveryJob(0x7c339f8)  ...Returned from main thread
11-03 11:24:41:646 0x7266188 OCC::DiscoveryJob::remote_vio_opendir_hook: static csync_vio_handle_t* OCC::DiscoveryJob::remote_vio_opendir_hook(const char*, void*) 5 when opening  msg= "Erreur inconnue"
11-03 11:24:41:646 0x7266188 csync_ftw: opendir failed for ownclouds://www.mydomain.com/owncloud/remote.php/webdav - errno 5
11-03 11:24:41:649 0x7266188 csync_statedb_close: sqlite3_close=0
11-03 11:24:41:678 0x4487b70 OCC::SyncEngine::handleSyncError:  #### ERROR during  csync_update :  "Une erreur est survenue lors de l'ouverture d'un dossier Erreur inconnue"
11-03 11:24:41:681 0x4487b70 OCC::SyncEngine::finalize: CSync run took  4379
11-03 11:24:41:682 0x4487b70 OCC::Folder::slotSyncFinished:  - client version 2.0.2 (build 5569)  Qt 5.4.0  SSL  OpenSSL 1.0.2d 9 Jul 2015
11-03 11:24:41:684 0x4487b70 OCC::Folder::slotSyncFinished: -> SyncEngine finished with ERROR, warn count is 0
11-03 11:24:41:703 0x4487b70 OCC::Folder::bubbleUpSyncResult: Processing result list and logging took  10  Milliseconds.
11-03 11:24:41:705 0x4487b70 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result:  2
11-03 11:24:41:706 0x4487b70 OCC::Folder::slotSyncFinished:   ** error Strings:  ("Une erreur est survenue lors de l'ouverture d'un dossier Erreur inconnue")
11-03 11:24:41:707 0x4487b70 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
11-03 11:24:41:709 0x4487b70 OCC::Folder::slotSyncFinished: the last 1 syncs failed
11-03 11:24:41:712 0x4487b70 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:\Users\Philippe\ownCloud\"
11-03 11:24:41:712 0x4487b70 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "UPDATE_VIEW:C:\Users\Philippe\ownCloud\"
11-03 11:24:41:720 0x4487b70 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "ownCloud" :  "Error"
11-03 11:24:41:740 0x4487b70 OCC::FolderWatcher::pathIsIgnored: * Discarded as is hidden! "C:/Users/Philippe/ownCloud/.owncloudsync.log"
11-03 11:24:41:923 0x4487b70 OCC::FolderMan::slotFolderSyncFinished: <===================================== sync finished for  "ownCloud"
11-03 11:24:46:495 0x7b71a28 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7b71a98) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
11-03 11:24:46:496 0x7b71a28 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7b71a98) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
11-03 11:24:46:496 0x7b71a28 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7b71a98) QObject(0x0)  0 false 3 0
11-03 11:24:46:585 0x4487b70 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (La procédure spécifiée est introuvable.)
11-03 11:24:46:588 0x4487b70 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

11-03 11:24:46:590 0x4487b70 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
----------------------------

Owncloud server
----------------------------
{"reqId":"VjiORgoARRYAAExPRuoAAAAF","remoteAddr":"78.250.32.122","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/home\\\/secret\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(148): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/home\\\/secret\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(121): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/home\\\/secret\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/home\\\/secret\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/home\\\/secret\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/home\\\/secret\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/home\\\/secret\\\/www\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/home\\\/secret\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/home\\\/secret\\\/...')\\n#9 {main}\",\"File\":\"\\\/home\\\/secret\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2015-11-03T10:36:55+00:00","method":"PROPFIND","url":"\/owncloud\/remote.php\/webdav\/"}
----------------------------

**Comment by guruz** [comment]
Again bogus stuff in the ```oc:downloadURL``` property.

Did you research if PHP 5.6.6 has any known bugs that could somehow be related to this? Current PHP 5.6 is at 5.6.15

I guess @evert would not know either how bogus bytes could end in an empty property... ?

**Comment by philippeVerney** [comment]
Unfortunately I don't understand enough about the bug to even be able to know what to research except "OCC::LsColXMLParser::parse: ERROR"....
I don't know a lot owncloud, I don't know a lot php, I don't know a lot webdav. I am quite a basic owncloud user.

The good point is that I am nearly sure, the bug will be auto fixed tomorrow... The bug looks to auto fix after a while but keep remaining some days after for a while etc...

**Comment by evert** [comment]
Never seen this before. This is pretty weird

**Comment by philippeVerney** [comment]
As I expected, the bug has been auto fixed during the night. Everything is working fine this morning.
I don't really know what to do with this ticket : close, let opened, .... ?

**Comment by guruz** [comment]
@philippeVerney Let's leave it open, maybe someone else has the issue too and has an idea.

**Comment by guruz** [comment]
Did you manage to have this fixed?
Linux update? PHP update? Firewall update? oC update?

**Comment by philippeVerney** [comment]
I did not do anything but the bug did not come back.. I don't know at all why.... (but I am happy)
Since I am using ovh shared host, I don't do any update but OVH can do some even without noticing me.
