### ISSUE TITLE
Folders not getting deleted from webfrontend.

### ISSUE THREAD

**Issue by vijaykumar0690** [owncloud/client#3909]
Hi Team,

When i try to delete the shared folders from web console the files are not getting deleted and it remains the same.Where as when i try to delete it from Owncloud client it gets deleted and it works as expected. not sure what is causing the issue.

When i check on data folder i do not see the folders there. its actually been deleted. But in web console it still appears to be there.

Regards,
Vijay

**Comment by guruz** [comment]
Hi, please try on this tracker, not in the client tracker:
https://github.com/owncloud/core/issues
Also make sure to use the issue template
