### ISSUE TITLE
Delete remote share folder: Internal Server Error

### ISSUE THREAD

**Issue by felixboehm** [owncloud/client#3911]
### Expected behaviour
Local delete of a remote shared folder should behave like "normal" shared folder:
Delete a shared folder on the server does remove the share (for me), but does not delete the folder for other users / the user who shared

### Actual behaviour
Sync client shows ![bildschirmfoto 2015-10-02 um 17 02 48](https://cloud.githubusercontent.com/assets/1204907/10249819/8d48bbe2-6927-11e5-8bb7-6534ea12eaae.png) and error message: "Lokale Dateien und Freigabeordner wurden entfernt"

After this sync error, in web frontend the folder is visible, but opening the folder results in error "Speicher nicht verfügbar".

### Steps to reproduce
1. create a remote share (I tried on same instance)
2. wait for sync client to finish sync of that remote share folder
3. delete the folder on the local machine (used finder on mac)

### Server configuration
ownCloud version: 8.1.1

### Client configuration
Client version: 2.0.1

Operating system: Mac Os X

### Logs

https://gist.github.com/felixboehm/2d78d29f3551954d7d47

**Comment by guruz** [comment]
```
10-02 15:09:21:817 0x61000001d0d0 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 401 "Error downloading http://127.0.0.1/ownClouds/demo-enterprise-8.1.1/remote.php/webdav/RemoteSharedFolder  - server replied: Internal Server Error" QVariant(int, 500)
10-02 15:09:21:817 0x61000001d0d0 OCC::PropagateRemoteDelete::slotDeleteJobFinished: void OCC::PropagateRemoteDelete::slotDeleteJobFinished()  QUrl( "http://127.0.0.1/ownClouds/demo-enterprise-8.1.1/remote.php/webdav/RemoteSharedFolder " )  FINISHED WITH STATUS 401 "Error downloading http://127.0.0.1/ownClouds/demo-enterprise-8.1.1/remote.php/webdav/RemoteSharedFolder  - server replied: Internal Server Error"
```

> Internal Server Error

DELETE failing? FYI @icewind1991 @DeepDiver1975

**Comment by icewind1991** [comment]
@felixboehm are you able to delete the remote share from the web interface?

**Comment by dragotin** [comment]
I am not sure if I understand the term "remote share" here? If that is a share that was shared to you by another user, the behaviour is exactly how it is designed: If you delete the shared folder locally, it just removes the share.

**Comment by felixboehm** [comment]
remote share = federated cloud shared = share between instances

You are right, can't delete the remote share in web either. 
@cdamken said this should be fixed in server 8.1.3.

So I close this, test again and reopen if needed.

**Comment by felixboehm** [comment]
It is still an issue with 8.1.3 - but I will stick to core repo

**Comment by felixboehm** [comment]
https://github.com/owncloud/core/issues/18360
