### ISSUE TITLE
[1.8.4] Sync-Client keeps connected even if the user does not have access over LDAP

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#3912]
### Expected behavior
User is removed from the LDAP privileges to access ownCloud, and the client should not sync anymore.

### Actual behavior
User is removed from the LDAP privileges to access ownCloud, but the synclient keeps syncing.

### Steps to reproduce:
1.- Access over the Desktop and sync normally an LDAP User
2.- Remove the privileges to access to the user.
3.- Test the user over the webUI --- User can not access anymore.
4.- Synclient still syncing without problems.

@MorrisJobke 

00003501

**Comment by guruz** [comment]
Are you sure this is not a server WebDAV issue?

FYI @blizzz @icewind1991 @PVince81

**Comment by MorrisJobke** [comment]
> User is removed from the LDAP privileges to access ownCloud, but the synclient keeps syncing.

This is because the user still has an active session. Correct @DeepDiver1975 @LukasReschke 

Ref https://github.com/owncloud/core/issues/18410

**Comment by cdamken** [comment]
Any news?

**Comment by MorrisJobke** [comment]
> Any news?

See:

> This is because the user still has an active session. Correct @DeepDiver1975 @LukasReschke

**Comment by bboule** [comment]
Guys do we understand how to resolve this??  Next steps?

**Comment by MorrisJobke** [comment]
> Guys do we understand how to resolve this?? Next steps?

Wait for https://github.com/owncloud/core/issues/18410 to be implemented to be able to invalidate the session.

**Comment by bboule** [comment]
OK so it looks like best case this will not get done until 9.1 (based on the milestone set for core 18410) @cdamken what is the temp of the customer is this a critical issue for them?  Do we need to push to move a fix up?

**Comment by cdamken** [comment]
@bboule Well, we have to fix this and https://github.com/owncloud/core/issues/18410

The customer didn't ask for news, but I think the milestone was 9.1.

**Comment by MorrisJobke** [comment]
This is a server issue and is covered by https://github.com/owncloud/core/issues/18410 -> closing this here.
