### ISSUE TITLE
[OS X] [2.0.1] does't sync since a few days (OC 8.1.3.) when using https

### ISSUE THREAD

**Issue by UkeFan** [owncloud/client#3917]
### Actual behaviour
Since I updated OC to 8.1.3 my Mac client doesn't sync properly. It kinda connect's but shows the red cross and can't sync data. The Android apps plus the web-surface are alright.

### Steps to reproduce
1. Deinstall the client
2. Reinstall the client
Same with deleting and resetting the account within the client

### Server configuration
Operating system: Linux?!

Web server: apache  (kasserver.com "All Inkl" Germany)

Database: Mysql 5.6.24

PHP version: 5.5 cgi/fpm

ownCloud version: 8.1.3

Storage backend: no

### Client configuration
Client version: 2.0.1

Operating system: OS x Mavericks

OS language: German

Installation path of client: Hackint.....HD/Programs/

### Logs
see also here:https://forum.owncloud.org/viewtopic.php?f=21&t=30782&p=98143#p98143
    10-03 21:03:04:883 0x600000005730 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://xx.xxxxxx.xx" + "/"
    10-03 21:03:07:150 0x608000014030 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x608000007fa0) QObject(0x0) 0 false 3 0 QAbstractSocket::ConnectedState
    10-03 21:03:07:151 0x608000014030 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x608000007fa0) QObject(0x0) 0 false 3 0 QAbstractSocket::ConnectedState
    10-03 21:03:07:151 0x608000014030 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x608000007fa0) QObject(0x0) 0 false 3 0

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

2. Web server error log:
no entries!

3. ownCloud log (data/owncloud.log):
{"reqId":"VhDFSVUNgA4AAGwvP0kAAAAK","remoteAddr":"85.13.128.137","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/wxxxxxx\/oc.xxxxxx.xx\/lib\/private\/tempmanager.php#179","level":3,"time":"2015-10-04T08:20:57+02:00"}
{"reqId":"VhDFVlUNgA4AAFo8BOsAAAAA","remoteAddr":"85.13.128.137","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/wxxxxxx\/oc.xxxxxx.xx/lib\/private\/tempmanager.php#179","level":3,"time":"2015-10-04T08:21:10+02:00"}
{"reqId":"VhDO3FUNgA4AAEH@aZoAAAAU","remoteAddr":"85.13.128.137","app":"PHP","message":"opendir(\/tmp): failed to open dir: Permission denied at \/www\/htdocs\/wtdocs\/wxxxxxx\/oc.xxxxxx.xx/lib\/private\/tempmanager.php#179","level":3,"time":"2015-10-04T09:01:48+02:00"}

**Comment by UkeFan** [comment]
When I add the same OC-Account as "http://.." instead of "https://.." ist works and shows the SSL-Connection nevertheless. So anyting around the certificate oder SSL-Socket (whatever that is) might be wrong. Is it a missetting on my behalf?!

**Comment by guruz** [comment]
Which error does it show in the UI when the red icon appears?

> shows the SSL-Connection nevertheless

You use the HTTP URL but it shows the SSL certificate dialog?

**Comment by UkeFan** [comment]
As far as I remember it toggled between "unknown error" and "connection error". The activity tab was blank. Data were not synchronized. 
@ http connection: no. No dialogue. It shows the professional certificate of my SIP. Why that and not my self-signed one I don't understand neither. But now: everything's working fine PLUS everything looks like https. Strange ?!

**Comment by guruz** [comment]
@UkeFan Could you check your ```owncloud.cfg``` on desktop?
But yes sounds all a bit server/provider related?

**Comment by Dianafg76** [comment]
I tested this issue and for my is working OK
Desktop v ownCloud-2.0.2.2766-nightly20151005.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.3.0","versionstring":"8.1.3","edition":"Enterprise"}

**Comment by guruz** [comment]
Please try the 2.1 nightlies (have backups!) and see if that fixes it
http://download.owncloud.com/desktop/daily/
