### ISSUE TITLE
[OS X 10.11 El Capitan] No menu item in when having "Auto hide menu bar" 

### ISSUE THREAD

**Issue by dejongac** [owncloud/client#3918]
After installing the new version of OSX version 10.11 El Capitan (Fresh install).
I installed the OwnCloud client ownCloud-2.0.1.2694-2, it installed correctly but no menu item.
if you move your arrow onto a empty space and click it reacts, so apparently the Icon is gone but the product is working.

**Comment by guruz** [comment]
@dejongac Do you mean the icon in the menu bar on the top?
So if you click the empty space you get the usual drop down menu?

**Comment by dejongac** [comment]
Hello markus,

yes that is correct, the field is there but the icon is missing.



Met vriendelijke groet / With kind regards,

Albert de Jong

Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Markus Goetz <notifications@github.com>
Datum: 04-10-2015 21:58 (GMT+01:00)
Aan: owncloud/client <client@noreply.github.com>
Cc: Albert de Jong <albert.dejong@aimkl.com>
Onderwerp: Re: [client] No menu item in OSX 10.11 El Capitan (#3918)


@dejongac<https://github.com/dejongac> Do you mean the icon in the menu bar on the top?
So if you click the empty space you get the usual drop down menu?

-

**Comment by guruz** [comment]
What is your screen size (pixels?)
Do you have a screenshot?
I can not reproduce this on my 10.11 machine.

**Comment by dejongac** [comment]
My screen is set to default display, also tried other scaled but same result.

As you can see on the print screen no icon




Met vriendelijke groet / With kind regards,

Albert

From: Markus Goetz
Reply-To: owncloud/client
Date: Sunday 4 October 2015 at 23:13
To: owncloud/client
Cc: A de Jong
Subject: Re: [client] No menu item in OSX 10.11 El Capitan (#3918)


What is your screen size (pixels?)
Do you have a screenshot?
I can not reproduce this on my 10.11 machine.

**Comment by guruz** [comment]
@dejongac Can you attach the screenshot via web?
I can't see it from e-mail

**Comment by dejongac** [comment]
I attached it as a jpg
will send it tonight again via web.


Met vriendelijke groet / With kind regards,

Albert de Jong

Verzonden vanaf mijn Samsung Galaxy-smartphone.


-------- Oorspronkelijk bericht --------
Van: Markus Goetz <notifications@github.com>
Datum: 05-10-2015 08:52 (GMT+01:00)
Aan: owncloud/client <client@noreply.github.com>
Cc: Albert de Jong <albert.dejong@aimkl.com>
Onderwerp: Re: [client] No menu item in OSX 10.11 El Capitan (#3918)


@dejongac<https://github.com/dejongac> Can you attach the screenshot via web?
I can't see it from e-mail

-

**Comment by dejongac** [comment]
![screen shot 2015-10-04 at 23 29 01](https://cloud.githubusercontent.com/assets/14966691/10275454/db7a8db4-6b47-11e5-9357-cac77fe88838.jpg)

**Comment by dejongac** [comment]
Picture is uploaded to the web, as comment to my original item.

Met vriendelijke groet / With kind regards,

Albert

From: Markus Goetz
Reply-To: owncloud/client
Date: Monday 5 October 2015 at 08:52
To: owncloud/client
Cc: A de Jong
Subject: Re: [client] No menu item in OSX 10.11 El Capitan (#3918)


@dejongac<https://github.com/dejongac> Can you attach the screenshot via web?
I can't see it from e-mail

**Comment by ekiselyov** [comment]
I have same problem — Retina 15" (mid 2015)
<img width="381" alt="screenshot 2015-10-05 15 20 51" src="https://cloud.githubusercontent.com/assets/12184502/10280301/d64ca20a-6b74-11e5-91a9-d4eb842e7377.png">

**Comment by dragotin** [comment]
sorry, this is neither gold nor in the scope of 2.0.2

**Comment by dejongac** [comment]
? What do you mean this is not Gold or in scope.

This should be basic functionality and should have been working from start.
You start a client but cannot see if it is working or not because you are missing a vital part.

**Comment by danimo** [comment]
@dejongac before we cannot reproduce the issue, we can't fix it. It also means that not everyone seems to be affected. Given that 2.0.2rc1 will be out any day now (and already behind schedule), which implies that the branch is deep-frozen, we have to move this to 2.0.3 or 2.1.

**Comment by dejongac** [comment]
That is a different answer than what dragotin just said and i understand that you are not able to work on it now but will address in the future.

But it is strange that after a clean install of OSX 10.11 and own cloud client this problem appears.
If you what to test i will be happy to do so.

**Comment by danimo** [comment]
> That is a different answer than what dragotin just said and i understand that you are not able to work on it now but will address in the future.

It's exactly the same meaning :). Gold tickets block a release, and are there for regressions in our code base. I have tested with El Capitain from the first developer beta, and it worked fine. However, I preformed an upgrade from 10.11, and gradually transitioned through the betas. My upgrade to the final version is still pending, through @guruz already seems to run on the final version.

@dejongac Do you run on a retina display? My machine's is not.

**Comment by dejongac** [comment]
Yes i run on a retina display and apparently so does ekiselyov, see comment above.

**Comment by echosa** [comment]
I'll jump in on this as well. I see this same behavior after upgrading to El Capitan (not a clean install). I'm using the dark menu bar in OS X, and tried the monochrome OwnCloud icon and the color icon. Neither show up, but I can click the blank space. Default resolution on a MacBook Pro (Retina, 15-inch, Mid 2014). In case it matters, I'm using the new "hide menu bar" setting.

<img width="1440" alt="screen shot 2015-10-06 at 10 25 17 am" src="https://cloud.githubusercontent.com/assets/133786/10313290/921c2b1e-6c14-11e5-92e1-2eef068a21e7.png">

**Comment by idallas** [comment]
I am seeing the same missing icon behavior in El Capitan and am also using the "hide menu bar" setting.  After unhiding the menu bar, the icon comes back after about 5 seconds.  Hiding the menubar makes the icon disappear again, also after a few seconds.  I'm on a mid-2012 13" Macbook Air.

**Comment by pierrejochem** [comment]
Me too

**Comment by Dianafg76** [comment]
@dejongac, @echosa, @ekiselyov, @idallas, @pierrejochem Could you test with this v http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.2772-nightly20151008.pkg, please?

Thanks!!

**Comment by echosa** [comment]
@Dianafg76 That doesn't seem to have fixed the issue for me. Note that all I did was install the pkg. I didn't uninstall, reboot, or anything else. If there's anything else I need to do, let me know, and I will. 

Also, should I continue to use this nightly build, or remove it and reinstall the official stable release again?

**Comment by Dianafg76** [comment]
@echosa Thanks for try
And reinstall the official stable release, please

**Comment by stonerl** [comment]
This Bug only appears when one uses the "Automatically hide and show the menu bar".
![screen shot 2015-10-13 at 13 07 11](https://cloud.githubusercontent.com/assets/2091312/10453347/b208fd16-71ab-11e5-800d-c5379f0171f8.png)

**Comment by guruz** [comment]
@AlexanderWillner has mentioned  https://codereview.qt-project.org/#/c/115120/

https://github.com/owncloud/client/issues/2215#issuecomment-147299615

**Comment by ekiselyov** [comment]
stonerl, thanks! its work

**Comment by dragotin** [comment]
so this sounds like we need the Qt upstream patch either in our Qt, or wait for the upstream release. @danimo ?

**Comment by guruz** [comment]
Upstream bug: https://bugreports.qt.io/browse/QTBUG-48960

**Comment by torarnv** [comment]
Try https://codereview.qt-project.org/146216

**Comment by guruz** [comment]
@torarnv tack :)
@danimo I can confirm the Qt patch fixes the issue.

**Comment by guruz** [comment]
Should be in  http://download.owncloud.com/desktop/daily/ownCloud-2.1.1.3039-nightly20160118.pkg
@jturcotte is testing..

**Comment by jturcotte** [comment]
Works :+1:
