### ISSUE TITLE
Main client window opens on every login

### ISSUE THREAD

**Issue by RalfJung** [owncloud/client#3926]
Each time I log in, the ownCloud client main window appears. I don't see how this is useful, and consider it fairly annoying. The client should sit in the background and silently do its work, without bragging for attention whenever I log in.

This is on Debian testing, owncloud-client 2.0.0, Qt 5.5, using Cinnamon as my desktop.

**Comment by guruz** [comment]
This is a bug with X11 session resuming.
Can you try a nightly build?

**Comment by RalfJung** [comment]
> This is a bug with X11 session resuming.

Are you sure? No window of any other application is getting restored on login. I don't think Cinnamon even does X11 session restore.

> Can you try a nightly build?

I did. (They were called "Daily", but I assume that's what you meant). It did not help. The only thing that changed is that the "Close" button went away - but since the window is still marked as a dialogue or whatever, there's also no "X" in the top-right corner, so I have to use the task bar to close it.

**Comment by guruz** [comment]
It seems Qt's ```isSessionRestored``` was not reliable..
Maybe it works now?
https://github.com/owncloud/client/commit/e1c634d000271a0a1c64a51596edeba784be9829

**Comment by RalfJung** [comment]
When can I assume that commit to be included in the packages at <http://download.opensuse.org/repositories/isv:/ownCloud:/community:/nightly/Debian_8.0/>?

**Comment by dragotin** [comment]
@RalfJung latest tomorrow, oct. 17

**Comment by RalfJung** [comment]
The bug is still present in today's daily build.
