### ISSUE TITLE
Manual File Copying Across Device(s) Not Recognized

### ISSUE THREAD

**Issue by ZiiX** [owncloud/client#3927]
I had to do a reinstall on another device:
- one windows and one mac
- but when I placed the exact files and exact directory from PC that was up-to-date with the owncloud server on my mac laptop it didn't simply recognize the files / file structure... The mac sync app had to re-download everything. Is there a setting or hidden log file that should be copied? Is this a nuance with server-side encryption enabled? Ideally, it would be great to replicate manually sometimes if one computer goes down and the clients know all files match.
  Thanks for all the great work.

**Comment by Computences** [comment]
+1
I'm setting up a new owncloud server from existing structures of files (that where not already "ownclouded").

It would have been useful to initialize owncloud "files" directory by direct copy, rather than client syncing (remaining duration 2 months, frequent "error downloading", ...)

**Comment by Akuukis** [comment]
+1
I have two PCs that have partly the same content. I added first and it uploaded everything nicely. When I added second PC it downloaded all files, including exact copies. For exact copies in activity log it reads "Downloaded, renamed conflicting file", but in filesystem there's the same file with the same modified date, with no conflicting file.
Client: 2.0.2 (on debian), Server: 8.2.0 (stable)

**Comment by guruz** [comment]
This should at some point be fixed by checksum support..

@DeepDiver1975 @dragotin

**Comment by ckamm** [comment]
If you start syncing a folder that already has the exact same files as the server expects nothing will be downloaded and that behavior has been in place for a long time.

I suspect copying the files to OSX changed their mtime. Different metadata is currently always considered a conflict and will cause downloads. 

But we could indeed also do the file hash check to potentially skip downloading even when the mtimes don't match up. If my guesses about the situation here are correct, that would have helped.

**Comment by guruz** [comment]
@ckamm We went away from considering mtimes safe already when Etags were introduced. The combination of size&(reasonably-safe-hash-or-checksum) weighs to be stronger than missing ETags.

**Comment by ckamm** [comment]
In master we adjusted the 'skip download' check to not be so picky about mtimes. e694ffcd03d91ed2a4203d6cf874a8efdddcb4e5

**Comment by guruz** [comment]
@ZiiX @Computences @Akuukis  Do you want to try 2.5.0 alpha1? https://github.com/owncloud/client/releases

**Comment by Akuukis** [comment]
Sorry can't do that, I have moved to nextCloud some time ago. I hope this works well!

**Comment by guruz** [comment]
@Akuukis The Nextcloud client is mostly a copy of the code of the ownCloud client. So you can try the ownCloud 2.5.0 alpha1 client to test this now if you want.

**Comment by Computences** [comment]
Problem solved for me, I installed a cron : occ files:scan --all
