### ISSUE TITLE
[OS X CAPITAN] Sync Client v. 2.01 shows error when "Choose what to sync"

### ISSUE THREAD

**Issue by chesterdkat** [owncloud/client#3928]

**Comment by chesterdkat** [comment]
OS X Sync Client v. 2.0.1 will not show the folder hierarchy of "What to Sync" but instead errors. Thinking a possible issue with my server I checked my wife's MacBook Air and version 1.8.4 (build 2531) works perfectly. I deleted version 2.0.1 from my Retina MacBook Pro and reverted to 1.8.4 (build 2531) which works correctly.

**Comment by Dianafg76** [comment]
@chesterdkat I need more information for reproduce this issue
Can you write the steps, please?
Thanks

**Comment by chesterdkat** [comment]
I have a Debian 7 server running ownCloud 8.1.3 (stable). My wife and I have 4 Mac's syncing to ownCloud:

1- iMac i3 w/ 12 GB's of RAM ownCloud sync client version 2.0.1, user jovad
1- MacBook Air i7 4 GB's of RAM ownCloud sync client version 1.8.4, user jovad
1- Mac Mini Server i7 16 GB's of RAM ownCloud sync client version 2.0.1, user dovad
1- Retina MacBook Pro i7 8 GB's or RAM ownCloud sync client version 1.8.4 downgraded from 2.0.1, user dovad

Both the Mac Mini Server and the Retina MacBook Pro while running sync client 2.0.1 and when clicking on the "Choose What to Sync" button would display the error "Error while loading the list of folders from the server".

I noted that the MacBook Air which is running sync client version 1.8.4 did not display that error and did in fact show the folders that were chosen for syncing.

I uninstalled sync client version 2.0.1 from the Retina MacBook Pro and installed version 1.8.4 and now the above error no longer displays and I can again see the files/folders chosen for synchronization.

Note: all machines were running OS X Yosemite initially with the above issues. I have since upgraded the Mac Mini Server and the Retina MacBook Pro to El Capitan. The issue followed from Yosemite to El Capitan, so both OS versions displayed the same problem.

Please let me know if you need any additional information, I'd be glad to help in any way that I can.

**Comment by Dianafg76** [comment]
@chesterdkat Thanks you for the information

**Comment by chesterdkat** [comment]
FYI, with OS X El Capitan's "Dark Mode" for the top menu bar the ownCloud sync client is invisible. You'll need to add an optional white or other light colored theme to the available colors so that it is again visible. Right now it looks like a blank spot on the menu bar.

**Comment by danimo** [comment]
@chesterdkat already reported in https://github.com/owncloud/client/issues/3918

**Comment by Dianafg76** [comment]
@chesterdkat Could you test with this v http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.2772-nightly20151008.pkg, please?

Thanks!!!

**Comment by chesterdkat** [comment]
No dice! See screenshot.

**Comment by ckamm** [comment]
@chesterdkat This looks similar to #3524?

**Comment by chesterdkat** [comment]
I just installed Version 2.0.2-nightly20151013 (build 2781) and this problem still 
![screen shot 2015-10-17 at 10 17 33](https://cloud.githubusercontent.com/assets/11929234/10559181/562b5fa6-74b8-11e5-84f1-e8ea33cbd035.png)
persists. Again only 1.8.4 allows my synced folders to show.

**Comment by chesterdkat** [comment]
I just installed Version 2.0.2-nightly20151013 (build 2781) and this problem still persists. Again, only version 1.8.4 works properly and displays my synced folders.
![screen shot 2015-10-17 at 10 18 26](https://cloud.githubusercontent.com/assets/11929234/10559186/932c4de8-74b8-11e5-88e9-94677d726bfa.png)

**Comment by phil-davis** [comment]
The timeout for that folder sync tree display was increased to 60 seconds only recently - https://github.com/owncloud/client/commit/745cf55abb3eeea81e2469ea951fbe53999f370e - that commit is part of 2.0.2-rc1 so you could try with the 2.0.2-rc1 at https://owncloud.org/install/#testing-development
The longer timeout will help while it is waiting for the server, assuming the underlying problem here is similar to mine - where the true issue is that the server is taking an unexpectedly long time to build the folder list and reply.

**Comment by chesterdkat** [comment]
GREAT! It seems that you have this bug squashed! I can now see my synced and un-synced folders again with Version 2.0.2rc1 (build 2790)! One last bug however. With OS X El Capitan set with the menubar in night mode the ownCloud icon is invisible and just shows as a blank spot on the menubar.

THANK YOU!
Dave
