### ISSUE TITLE
OSX will not build. "use of undeclared identifier 'preferencePanelCount'"

### ISSUE THREAD

**Issue by EamonnDH** [owncloud/client#3929]
### Expected behaviour
Client build successfully on OSX.

### Actual behaviour
Partially completes (86%).
Throws errors relating to 'preferencePanelCount', 'insertPreferencesPanel', 'removePreferencesPanel'.

### Steps to reproduce
1. https://doc.owncloud.org/desktop/2.0/building.html Following OSX instructions, steps 1-3 followed. (There is no step 4?)
2. Follow generic build instructions, with "cmake -DCMAKE_BUILD_TYPE="Debug" -CMAKE_PREFIX_PATH=/usr/local/opt/qt5/  ../client"
3. Call make.

### Client configuration
Client version: Latest git (2.0.2-beta1), as of 07/10/15

Operating system: OS X 10.10.2 14C1510

OS language: UK English

### Logs

client/src/gui/settingsdialogmac.cpp:109:26: error: 
      use of undeclared identifier 'preferencePanelCount' 
    setCurrentPanelIndex(preferencePanelCount() - 1 - 2); 
                         ^ 
client/src/gui/settingsdialogmac.cpp:119:5: error: 
      use of undeclared identifier 'insertPreferencesPanel' 
    insertPreferencesPanel(0, accountIcon, displayName, accountSettings); 
    ^ 
client/src/gui/settingsdialogmac.cpp:130:13: error: 
      use of undeclared identifier 'removePreferencesPanel' 
            removePreferencesPanel(p); 
            ^

**Comment by bofmog** [comment]
Please change your Qt version to 5.4.

**Comment by EamonnDH** [comment]
Changed to Qt 5.4. No change :'(

**Comment by guruz** [comment]
Did you init/update the submodules?
Did you checkout 2.0 branch?

**Comment by EamonnDH** [comment]
Just redownloaded and redid all the init/update/checkout, and I did get it to build, but when I try to run it I get:
dyld: Library not loaded: /usr/local/opt/qt5/lib/QtCore.framework/Versions/5/QtCore
  Referenced from: /usr/local/lib/libqt5keychain.0.dylib
  Reason: image not found
What did I miss?

**Comment by guruz** [comment]
Did you install qt5keychain library? :)
Did you do make install?
In any case, we can help you on #owncloud-client-dev on irc.freenode.net ..

This is a tracker for bugs / feature requests.
