### ISSUE TITLE
[Proposal][Windows] Add files list to a name space tree (Namespace Extensions)

### ISSUE THREAD

**Issue by pierrejochem** [owncloud/client#3930]
I think it would be a great benefit to add the files list to an own name space tree like onedrive is doing it in the windows explorer. Here is an example to show you what I mean in detail:

![onedrive_2015-10-07_16-40-16](https://cloud.githubusercontent.com/assets/9192953/10340829/2ada8faa-6d12-11e5-8406-52a4f2be1ef8.png)

http://www.codeproject.com/Articles/1649/The-Complete-Idiot-s-Guide-to-Writing-Namespace-Ex

This would make it possible to implement an Online/Offline feature but that would be an additional proposal ;-)

@MTRichards + @karlitschek

**Comment by pierrejochem** [comment]
@guruz ;-)

**Comment by pierrejochem** [comment]
Example Code: 

http://www.viksoe.dk/code/flickrdrive.htm

**Comment by guruz** [comment]
Related https://github.com/owncloud/client/issues/4341
