### ISSUE TITLE
Reset blacklist attempt counter when chunks succeeded after failed attempts

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#3934]
@guruz: I had a chat with @stonerl on IRC and he told me that he had a resumable situation. Basically chunks fail from times to times but the second time it works. But if within the same transfer several chunks failed, the file still gets blacklisted. @guruz does that match the current implementation of the client ?

If yes I'd say the client should discard the blacklist counter value as soon as there is a successful chunk. Only if the same chunk fails over and over again, then blacklist the file. 
Unless you are able to track on a chunk to chunk basis instead of transfer basis, but that might be overkill.

**Comment by ckamm** [comment]
Doing this seems very easy, just call `journal->wipeErrorBlacklistEntry()` when a chunk downloaded successfully.

**Comment by PVince81** [comment]
Just to clarify, this was an upload situation, not download.
So you mean "uploaded" ?

**Comment by guruz** [comment]
Done for uploads for 2.0.2

Although @ogoffart is worried that it voids the use of a blacklist in the first place.. let's see.

**Comment by PVince81** [comment]
The blacklist would still kick in if a single chunk could not be uploaded several times due to network errors. But yeah, it might happen less often.

**Comment by stonerl** [comment]
Is this in the current nightly? If so I'm going to test this.

**Comment by guruz** [comment]
@stonerl should be, please test :)

**Comment by guruz** [comment]
@stonerl And by current I mean please test the one from today (19th)

**Comment by PVince81** [comment]
2.0.2 is out already, is this fix in ?

**Comment by guruz** [comment]
@PVince81 yes, see milestone and commit above

**Comment by Dianafg76** [comment]
@stonerl could you install this version: http://download.owncloud.com/desktop/daily/ownCloud-2.1.0.2875-nightly20151113.pkg, please
And try again
Thanks

**Comment by stonerl** [comment]
Does not work. The second failed chunk still blacklists the file, even if other chunks have been uploaded successfully.

```
Error downloading https://example.tld/remote.php/webdav/Documents/cm-12.1-20151103-NIGHTLY-bacon-1.zip-chunking-1852184230-60-6 - server replied: Bad Request (expected filesize 5242880 got 0)

Continue blacklisting: Error downloading https://example.tld/remote.php/webdav/Documents/cm-12.1-20151103-NIGHTLY-bacon-1.zip-chunking-1852184230-60-9 - server replied: Bad Request (expected filesize 5242880 got 0)
```

**Comment by guruz** [comment]
@stonerl Wait, you mean even if a chunk _after_ a failed chunk suceeds?

**Comment by stonerl** [comment]
@guruz 

Yes, chunk 6 failed first. The client continued uploading later  and was able to upload chunk 6 and 7. While it was uploading chunk 8 and 9 chunk 9 failed and the file got blacklisted (as you can see from the activity-log).

**Comment by ckamm** [comment]
@stonerl The remaining problem was about error reporting. The blacklist entry was correctly wiped and you got a fresh 25s blacklist entry the second time a chunk failed - but got the "Continue blacklisting" message. With the new patch this should be better.

**Comment by stonerl** [comment]
OK, thank you for clarification.

**Comment by Dianafg76** [comment]
@stonerl could you install this version: http://download.owncloud.com/desktop/daily/ownCloud-2.1.0.2907-nightly20151125.pkg, please

Thanks

**Comment by stonerl** [comment]
:+1 works great. Thanks to all of you.
