### ISSUE TITLE
Make owncloudcmd return code depend on sync result

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/client#3936]
Smashbox currently has code (added from cern) that ignores the returncode on the sync.
After speaking with @guruz it should be checked, so the return code is reliable and we can notify the user when the returncode is not-successful.

**Comment by moscicki** [comment]
Yes. Definitely a good idea. The question is what it means that the sync failed. I guess it only means for example that the client failed to connect to the server (so there was a critical error which prevented the sync to run). But probably a sync run for which there was an error downloading one file out of 100  is OK. Or isn't it?

**Comment by dragotin** [comment]
@moscicki yes, that's a fine line. I think I agree with what you said above, as the fail of  a sync might be part of an successful sync.

**Comment by nickvergessen** [comment]
Okay at least the return codes of --help and --version should be changed.
They currently return 1 instead of non-zero

also multiple options can't be combined appearantly? I tried `--trust --version`:
```
nickv@nickv-think ~ $ /usr/bin/owncloudcmd --trust --version
Source dir '--trust/' does not exist.
```

**Comment by ogoffart** [comment]
After a sync it always return 0.  It doe snot matter if the sync success or fails.

We could change that, but under which criterias?
Is any SoftError a failure? or is failures oinly FatalError?

**Comment by schnidrig** [comment]
What about this:
0: no error at all. All files synchend and up to date.

Then if some kind of error occurs, use specific values to indicate what it was. 
For example: 
10: connection error
11:  server gave us some 5XX http return code

20: some files failed to download

30: some files failed to upload

40: ... you name it

**Comment by SamuAlfageme** [comment]
I'm playing around with #5669, and noticed that network errors do not stop the program after they happen:

e.g.: Authentication Failed: 

```
$ cmd_return_codes owncloudcmd . demo.owncloud.com
Please enter user name: asdasd
Password for user asdasd: !!! OCC::JsonApiJob created for "http://demo.owncloud.com" + "ocs/v1.php/cloud/capabilities" ""
Redirecting "GET" QUrl("http://demo.owncloud.com/ocs/v1.php/cloud/capabilities?format=json") QUrl("https://demo.owncloud.com:443/ocs/v1.php/cloud/capabilities?format=json")
Stop request: Authentication failed for  "https://demo.owncloud.com:443/ocs/v1.php/cloud/capabilities?format=json"
void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(OperationCanceledError) "Operation canceled" QVariant(Invalid)
Network error:  "ocs/v1.php/cloud/capabilities" "Operation canceled" QVariant(Invalid)
Server capabilities QVariant(Invalid)
Set proxy configuration to use NO proxy
[9] csync_exclude_load  Adding entry: *~
[...]

There are 71058518016 bytes available at "/Users/salfageme/Downloads/cmd_return_codes/" and at least 50000000 are required
===== new sync (no sync journal exists)
"===== Using Qt 5.6.2 SSL library OpenSSL 1.0.2j  26 Sep 2016 on macOS Sierra (10.12)"
sqlite3 version "3.16.1"
sqlite3 journal_mode= "wal"
bool OCC::SyncJournalDb::checkConnect() possibleUpgradeFromMirall_1_5 detected!
void OCC::SyncJournalDb::commitInternal(const QString &, bool) Transaction commit  "checkConnect" and starting new transaction
[...]
void OCC::SyncJournalDb::commitInternal(const QString &, bool) Transaction commit  "checkConnect End"
void OCC::SyncEngine::startSync() ====NOT Using Selective Sync
#### Discovery start #################################################### >>
=====Server "" "rootEtagChangesNotOnlySubFolderEtags=0"
[...]

Redirecting "PROPFIND" QUrl("http://demo.owncloud.com/remote.php/webdav/") QUrl("https://demo.owncloud.com:443/remote.php/webdav/")
Stop request: Authentication failed for  "https://demo.owncloud.com:443/remote.php/webdav/"
void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(OperationCanceledError) "Operation canceled" QVariant(Invalid)
void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply *) "Operation canceled" 0 QNetworkReply::NetworkError(OperationCanceledError)
void OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot(int, const QString &) 5 "Operation canceled"
OCC::DiscoveryJob(0x7f9c8d7076a0)  ...Returned from main thread
5 when opening  msg= "Operation canceled"
[4] csync_ftw  opendir failed for  - errno 5
[6] csync_statedb_close  sqlite3_close=0
 #### ERROR during  csync_update :  "An error occurred while opening a folder Operation canceled"
void OCC::SyncJournalDb::close() "/Users/salfageme/Downloads/cmd_return_codes/._sync_758e987b5cb0.db"
No database Transaction to commit
CSync run took  895
void OCC::SyncEngine::abort() QObject(0x0)
void OCC::SyncJournalDb::close() "/Users/salfageme/Downloads/cmd_return_codes/._sync_758e987b5cb0.db"
No database Transaction to commit 

$ echo $?
1
```

Instead of stopping when the first Network error pops up, it continues with the sync, even creating an empty sync journal; @ogoffart could this be prevented? 

Also @schnidrig proposal on https://github.com/owncloud/client/issues/3936#issuecomment-157342759 could be very useful for triaging when using `owncloudcmd` for automated tests

**Comment by ogoffart** [comment]
@SamuAlfageme  i'm not sure what's the issue here.  1 means error.
And the program stops when the sync stops.

But yes, it's true that a failure to query the capabilities could abort earlier  But that's another issue.

**Comment by SamuAlfageme** [comment]
@ogoffart yeah, I was not talking about an issue with the return code itself but the program's flow after the error occurred, sorry if I wasn't clear and it didn't belong here. 

Thanks for opening the new issue! I'll close this one after testing out a couple more scenarios.
