### ISSUE TITLE
Access folder from public share link

### ISSUE THREAD

**Issue by daandres** [owncloud/client#3938]
Hi, 

I have an enhancement request to owncloud client for mobile and desktop. 

I use often public share links to share my files with others, who don't have an owncloud account at my server. 
Is it possible t use the owncloud client to download and upload the files from a public share link (with password)? 
The others do not want an own account, as this would complicate the usage. They only want a share link, but with the possibility to use a mobile app or an extra application on desktop. 

Possible features for both, desktop and mobile client:
- synchronize the shared folder to local (down- and uplaoding) by entering the link in the client
- support for link passwords
- no deletions
- if no uploading is allowed only downloading
- if the share has expired or is removed, the files that were downloaded shouldn't be deleted locally. The client should only mark the share as expired. 

Thank you much for help

**Comment by jospoortvliet** [comment]
See also https://github.com/owncloud/core/pull/19402#issuecomment-152156128 - on the server side, this should not be problematic.

**Comment by jospoortvliet** [comment]
A usecase I heard last weekend:
(small) company wants to make a large and frequently changing number of files available to a bunch of clients. The clients should not be making any changes.

Current work-around: created an account which has a read-only folder with the data shared and giving out the (same!) account data to all clients, asking them to please not share the login details.

Giving them a publicly shared link (protected by password) would be a nicer, cleaner solution.

Of course, if the server could create multiple shared links per share, so the usage of each client could be tracked, things would be even nicer. @PVince81 is that something we have a request for already, perhaps? I couldn't find anything.

**Comment by PVince81** [comment]
@jospoortvliet I'm pretty sure there was one but also cannot find it any more

**Comment by jospoortvliet** [comment]
Well at least it's part of the Sharing 2.0 proposal: https://github.com/owncloud/core/issues/19331

So it will come.

**Comment by daandres** [comment]
i close this as @jospoortvliet mention it is already covered in the new sharing 2.0 and hopefully coming with the new Owncloud 9.0

**Comment by jospoortvliet** [comment]
Actually this will also require changes on the client, I'm pretty sure, to be able to add a shared link as sync connection, without account (but password, if the shared link is protected). I'd leave it open to track this feature!

**Comment by daandres** [comment]
are there any news on this feature? 
Is the sharing 2.0 proposal getting this work?

thank you for help!

**Comment by jospoortvliet** [comment]
@daandres the sharing 2.0, integrated in ownCloud 9, would make it possible for the client devs to make it work, I think. But they still need to do it and it isn't planned yet. Somebody will have to volunteer and we all know 'somebody' is hugely overworked ;-)

**Comment by daandres** [comment]
ok. 
I know the trouble with being overworked and volunteering. 
But I have still hope

**Comment by qw3ry** [comment]
Would this be overly complicated to implement?
If I get a few hints where to start I would consider implementing this (if I find the time...).

**Comment by jospoortvliet** [comment]
@ogoffart @guruz perhaps you guys can give a few hints! This is a nice feature to have...

**Comment by PVince81** [comment]
I thought about this for setting up the sync client for less computer-savvy family members to share pictures.
There is an alternative, a bit more complicated to setup but would do: create a local user with a generated password. Then go to the admin page and generate an application password and set that to the sync client (it's also some kind of token). Then share stuff with that person (read-only if you want to avoid deletion). This almost feels like a guest account, but instead of the token being a public share token it's actually an "application password" or "device password". Let the client save that password.
Then since you have the main password for that account, you can always revoke the device password to prevent them to access the account.

Now thinking even further, if you create multiple device passwords you could even give access to the same OC account for several family members. Hmmm, not sure if that's a good idea 😄

**Comment by PVince81** [comment]
not a good idea: because these people would get access to the admin page and could revoke each other's passwords...

**Comment by qw3ry** [comment]
@PVince81 While I'm not entirely sure what you were proposing, I've another idea: _Maybe_ one could do a share URL like `https://hostname/id-of-the-share/username/password` or similar, and automatically create a no-login user with these credentials. The changes of the client would be UI only. But this would be a server side implementation, and not client side, so I guess discussing this here is quite pointless. Furthermore it feels a bit like a hack and I'm not sure if this would be easier at all.

**Comment by daandres** [comment]
i think the easiest to use qould be to have the same url like the share url `https://hostname/id-of-the-share/`. This url and the share password would be entered in the client instead of a `username/password` combination. Then all client sync features works as "normal". 
Therefore the share id has to be an anonymous user. 

I think non password shares would be more difficult.

**Comment by PVince81** [comment]
Or guest accounts: https://github.com/owncloud/core/issues/9568

**Comment by hodyroff** [comment]
As far as I see this will be accomplished with guest accounts which are part of 10.0 indeed. Please test with the first Beta and if things are still missing, please open a concrete request for that. Don't see us implementing this with public links at this time.

**Comment by daandres** [comment]
thanks. 
I will think about if guest accounts fulfill our requirement. If not, I will open a new more specific issue. 
Thanks for your help
