### ISSUE TITLE
OS X, Desktop Client 2.0.1 no "Share with ownCloud" menu item in Finder

### ISSUE THREAD

**Issue by andrey-str** [owncloud/client#3939]
### Expected behaviour
"Share with ownCloud" menu item appears when you click on file in local owncloud folder
Also no indicators in Finder that file is synced or not.
### Actual behaviour
It isn't there.

### Steps to reproduce
1. Put file to local owncloud folder
2. No indication in Finder that file is unsynced
3. Wait while it uploaded to the server
4. No indication in Finder that file is sync
5. Right click on this file
6. No desired menu item.

### Server configuration
Operating system:
Ubuntu 14.04 amd64

Web server: 
Apache 2.4.7
Database:
Not sure, I believe it is MySql. 

PHP version:
5.5.9

ownCloud version:
8.1.3

Storage backend:

### Client configuration
Client version:
2.0.1

Operating system:
OS X 10.5.5

OS language:
English

Installation path of client:
/Applications

### Logs
10-11 20:49:27:230 0x61000001cb40 OCC::Application::setupLogging: "################## ownCloud en_US (en) 2.0.1 (build 2694)"
10-11 20:49:27:231 0x61000001cb40 OCC::ownCloudGui::slotShowSettings: void OCC::ownCloudGui::slotShowSettings()
10-11 20:49:27:642 0x618000216db0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x61000001d2f0) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
10-11 20:49:27:642 0x618000216db0 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x61000001d2f0) QObject(0x0)  0 false 3 0
10-11 20:49:36:494 0x61000001cb40 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
10-11 20:49:36:494 0x61000001cb40 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://anse.me/owncloud" + "/"
10-11 20:49:40:493 0x61000001cb40 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://anse.me/owncloud" + "/"
:

**Comment by RealRancor** [comment]
Have a look at https://github.com/owncloud/client/issues/3874#issuecomment-142371453

**Comment by andrey-str** [comment]
Duplicate of #3874

**Comment by andrey-str** [comment]
RealRancor, thanks, it worked.
