### ISSUE TITLE
[Overlays] [OS X] Files with SoftErrors have red overlay icon

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#3944]
In #3387 we saw that the "423 Locked" error was treated as a SoftError but nevertheless lead to a red overlay icon for the affected folder on Mac. On Linux/nautilus the correct blue icon was displayed.

The underlying bug is in how the client reports completed sync jobs via the socket api. Currently any non-success leads to `ERROR` messages for the file or folder - even when a subsequent `RETRIEVE_FILE_STATUS` command would return a different status for it.

**Comment by ckamm** [comment]
Currently the socket api is a bit confused when it comes to sync errors on files: The moment a sync item fails with anything but success, we communicate "ERROR" to the clients. But `RETRIEVE_FILE_STATUS` has no idea about that and bases its decision solely on whether the file needs syncing (so erroring files will be shown as "EVAL").

I think we would like to show the error overlay for files with important sync errors. To do that, we'd need to cache which files are affected in this way somewhere. Then fileStatus queries and status broadcasts could be consistent.

@dragotin Do you agree with this?

**Comment by ckamm** [comment]
Actually, this error cache already exists in Folder, it's just buggy.

**Comment by Dianafg76** [comment]
I tested this issue and now is working ok
Desktop v ownCloud-2.1.0.5699-nightly20151211-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}
Closed
