### ISSUE TITLE
[OS X CAPITAN] Owncloud client under OS X sync-problem (stops)

### ISSUE THREAD

**Issue by peterporta** [owncloud/client#3945]
Hi,
after upgrading my OS X to El Capitan 10.11 The sync-client begins to sync and than stops after some time showing the red circle with the white cross. 
In the meantime I updated the by hosteurope hosted owncloud to 8.1.3 (from 8.0.2) without success. The sync-client can be started but stops after some time. 

I got the error:
Error	no app in context	Error while running background job: Backends provided no user object for	
Error	files	Backends provided no user object for
Error	PHP	Array to string conversion at /is/htdocs/.../lib/private/template/functions.php#36

One more note: It seems to be something with the external files from another owncloud. Removing the connection the sync works fine.

**Comment by Dianafg76** [comment]
I tested this issue, and I can't reproduce 
Desktop v ownCloud-2.0.2.2786-nightly20151015.pkg  
Server v {"installed":true,"maintenance":false,"version":"8.2.0.9","versionstring":"8.2 RC1","edition":""}

**Comment by peterporta** [comment]
Since i closed the connection to the second owncloud, it works fine. The first owncloud is hosted by hosteurope (php 5.5) and the second (fetched owncloud) is hosted at allinkl.com <http://allinkl.com/> (at the moment 5.3.28).
--
Viele Grüße

Peter Wienczny
Unter dem Holzweg 28
32457 Porta Westfalica
0571-7989416

**Comment by guruz** [comment]
Sorry, please submit this to the _server_ issue trakcker.

https://github.com/owncloud/core/

**Comment by peterporta** [comment]
Sorry - how can i do that? 
--
Viele Grüße

Peter Wienczny
Unter dem Holzweg 28
32457 Porta Westfalica
0571-7989416

**Comment by phil-davis** [comment]
Go to the core repo https://github.com/owncloud/core and then create an issue there.
