### ISSUE TITLE
2.0.x client not working with Windows 8

### ISSUE THREAD

**Issue by macckone** [owncloud/client#3948]
### Expected behaviour
2.0.x client syncing with the server

### Actual behaviour
2.0.x client not syncing with the server
uninstall and reinstall did not fix the issue.
deleting account on server and creating a new account did not solve the issue.
using the 1.8.4 client works but it is attempting to reinstall the newer client.

### Steps to reproduce
1. Run windows 8 
2. use the 2.0.1 client
3. There may be patch levels on windows 8 that effect this.

### Server configuration
Operating system: Linux

Web server: Apache

Database: MySQL

PHP version: 5.4.43

ownCloud version: 8.0.5

Storage backend: local device storage

### Client configuration
Client version: 2.0.1

Operating system: Windows 8

OS language: English

Installation path of client: default

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

not available as I backgraded to 1.8.4 and it is now working

2. Web server error log:

none. client side issue

3. ownCloud log (data/owncloud.log):

none. I backgraded to 1.8.4 and now working.

See similar issue in forum:

https://forum.owncloud.org/viewtopic.php?f=14&t=30896&p=98669#p98669

**Comment by dragotin** [comment]
Sorry, but we will have a hard time to help you if can not provide any logfiles.

**Comment by guruz** [comment]
Let's continue discussion in https://github.com/owncloud/client/issues/3967 if they are related
