### ISSUE TITLE
Modify the installer to allow installation without shortcuts

### ISSUE THREAD

**Issue by crysman** [owncloud/client#3949]
In our company, I am deploying ownCloud via GPO as an MSI package I create using [WIX wrapper](https://github.com/pennmanor/wix-wrapper). I would need to install ownCloud clients **without shortcuts** being created on desktops.

In order to be able to do so, I need that the original installer included the option to not to install shortcuts. Many installers allow users to select if they wish shortcuts or not, it is nothing extraordinary.

So? Could you please make it?

**Comment by danimo** [comment]
This is not possible with NSIS, and, consequently, not with the WiX-Wrapper. We'll have to wait until #860 happens. Please add the option that you need there.
