### ISSUE TITLE
[Qt4] [RedHat] [Linux] Crash on QNetworkReplyImplPrivate::resumeNotificationHandling

### ISSUE THREAD

**Issue by Germano0** [owncloud/client#3960]
Upstream bugreport of https://bugzilla.redhat.com/show_bug.cgi?id=1272729

Version-Release number of selected component:
owncloud-client-2.0.1-1.fc22

Additional info:
reporter:       libreport-2.6.2
backtrace_rating: 4
cmdline:        /usr/bin/owncloud
crash_function: QNetworkReplyImplPrivate::resumeNotificationHandling
executable:     /usr/bin/owncloud
global_pid:     5443
kernel:         4.1.10-200.fc22.x86_64
runlevel:       N 5
type:           CCpp
uid:            1000

Truncated backtrace:
Thread no. 1 (10 frames)
 #0 QNetworkReplyImplPrivate::resumeNotificationHandling at access/qnetworkreplyimpl.cpp:444
 #1 QNetworkReplyImplPrivate::finished at access/qnetworkreplyimpl.cpp:796
 #2 QNetworkAccessBackend::finished at access/qnetworkaccessbackend.cpp:324
 #3 QNetworkAccessHttpBackend::replyFinished at access/qnetworkaccesshttpbackend.cpp:754
 #4 QNetworkAccessHttpBackend::qt_static_metacall at .moc/release-shared/moc_qnetworkaccesshttpbackend_p.cpp:95
 #5 QObject::event at kernel/qobject.cpp:1222
 #6 QApplicationPrivate::notify_helper at kernel/qapplication.cpp:4565
 #7 QApplication::notify at kernel/qapplication.cpp:4351
 #8 QCoreApplication::notifyInternal at kernel/qcoreapplication.cpp:953
 #9 sendEvent at kernel/qcoreapplication.h:231

you can find more logs in the mentioned bugzilla URL

**Comment by guruz** [comment]
@Germano0 Which Qt version is the client using? You should see that in the settings dialog or when running client with ```owncloud --logfile -```

@dragotin Maybe the client should ship its own Qt on Linux like on OS X and Windows?

**Comment by guruz** [comment]
@Germano0 Any info?

**Comment by Germano0** [comment]
@guruz I just pinged the bugreporter. Let's wait for a reply

**Comment by guruz** [comment]
@dragotin @jnweiger Do we have Qt5-based RedHat packages somewhere lying around as alternative for @Germano0 ?

**Comment by dragotin** [comment]
@guruz our packages for Fedora 22 compile against Qt5: https://build.opensuse.org/package/live_build_log/isv:ownCloud:desktop/owncloud-client/Fedora_22/x86_64

**Comment by guruz** [comment]
@Germano0 Does it work with those packages?

**Comment by Germano0** [comment]
@guruz What do you mean exactly?

**Comment by guruz** [comment]
@Germano0 We think this is a Qt4 problem.
We also have Qt5-based ownCloud client packages for Fedora22
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adesktop&package=owncloud-client

**Comment by Germano0** [comment]
@guruz I am still waiting for a reply from the Fedora bugreporter

**Comment by Germano0** [comment]
Another user experienced the problem. I asked him to show me the installed qt libs. Hereunder his reply:
============
Yes, but I remember now that I have done a "dnf upgrade" during this session, so this may be inaccurate:

$ rpm -qa qt\* | sort
qt-4.8.7-3.fc23.x86_64
qt-at-spi-0.3.1-9.fc23.x86_64
qt-common-4.8.7-3.fc23.noarch
qt-gstreamer-1.2.0-8.fc23.x86_64
qt-mobility-common-1.2.2-0.21.20140317git169da60c.fc23.x86_64
qt-mobility-location-1.2.2-0.21.20140317git169da60c.fc23.x86_64
qt-mobility-sensors-1.2.2-0.21.20140317git169da60c.fc23.x86_64
qt-mysql-4.8.7-3.fc23.x86_64
qt-settings-23-7.fc23.noarch
qt-x11-4.8.7-3.fc23.x86_64
qt4-style-oxygen-5.4.2-1.fc23.x86_64
qt5-qdbusviewer-5.5.0-4.fc23.x86_64
qt5-qtbase-5.5.0-18.fc23.x86_64
qt5-qtbase-common-5.5.0-18.fc23.noarch
qt5-qtbase-gui-5.5.0-18.fc23.x86_64
qt5-qtdeclarative-5.5.0-2.fc23.x86_64
qt5-qtgraphicaleffects-5.5.0-1.fc23.x86_64
qt5-qtlocation-5.5.0-2.fc23.x86_64
qt5-qtmultimedia-5.5.0-2.fc23.x86_64
qt5-qtquickcontrols-5.5.0-2.fc23.x86_64
qt5-qtscript-5.5.0-2.fc23.x86_64
qt5-qtsensors-5.5.0-2.fc23.x86_64
qt5-qtsvg-5.5.0-2.fc23.x86_64
qt5-qttools-5.5.0-4.fc23.x86_64
qt5-qttools-common-5.5.0-4.fc23.noarch
qt5-qttools-libs-designer-5.5.0-4.fc23.x86_64
qt5-qtwebkit-5.5.0-3.fc23.x86_64
qt5-qtx11extras-5.5.0-2.fc23.x86_64
qt5-qtxmlpatterns-5.5.0-2.fc23.x86_64
qt5-style-oxygen-5.4.2-1.fc23.x86_64
qtkeychain-0.5.0-1.fc23.x86_64
qtlockedfile-2.4-18.20150629git5a07df5.fc23.x86_64
qtscriptbindings-0.2.0-10.fc23.x86_64
qtsingleapplication-2.6.1-23.fc23.x86_64
qtsoap-2.7-11.fc23.x86_64
qtwebkit-2.3.4-8.fc23.x86_64


dnf update log (may contain old qt lib versions https://bugzilla.redhat.com/attachment.cgi?id=1091089 )

**Comment by guruz** [comment]
@Germano0 This does not help. It's fine for a system to have both qt4 and qt5 installed.
What you need is an ownCloud client with Qt5 and then see if that is fixed.

**Comment by guruz** [comment]
@Germano0 Does this still occur with your Qt5 based Fedora package?

**Comment by Germano0** [comment]
Hi @guruz , I just asked to the person who filled the Fedora bugreport. Soon I wil receive a feedback

**Comment by Germano0** [comment]
On Fedora bugzilla the bug is marked as fixed due missing feedback from bugreport creator. I assume it as fixed even here
