### ISSUE TITLE
client 2.0.1 doesn´t propagate changes on federated cloud shares

### ISSUE THREAD

**Issue by BenS89** [owncloud/client#3962]
Environment: 
ownCloud Server 8.1.3
ownCloud Client 2.0.1 on Windows 7

Steps to reproduce:
1. Create a directory in ownCloud web-interface 
2. Create a federated share on this directory (read and write) (e.g. maxmustermann@myowncloud.com)
3. Change files and folders within the shared directory as maxmustermann within his own webinterface

Expected behavior:
The client recognizes the changes and will sync the changes 

Actual behaviour
Nothing happens.

**Comment by guruz** [comment]
@BenS89 You mean changing the contents on the webinterface of the ownXloud of the federated share?

**Comment by BenS89** [comment]
@guruz I mean changing the contents in the "remote"-cloud 

Here is an example: 
User 1 creates a folder in ownCloud 1
User 1 creates a federated share for user 2, who has its ownCloud 2

user 2 logs into his ownCloud 2 and can see the federated share (which is located in ownCloud 1)
user 2 makes changes within the federated share in ownCloud2 (using the webinterface of ownCloud 2)

Those changes should be propagated by both desktop clients (for user 1 and 2), but nothing happens.

**Comment by icewind1991** [comment]
This is part of the more general "external storage changes are not detected" problem, we currently don't have a system to detect changes made to external storages in the background and thus they are not synced until the user visits the changed folder in the web interface

**Comment by guruz** [comment]
@icewind1991 But then why does the client discovery "take a long time" (according to other reports) if the user has mounted an external storage? The server must be doing something remotely after all?

**Comment by BenS89** [comment]
Even if I visit the updated folder on the webinterface, the client does not sync any changes.

**Comment by icewind1991** [comment]
> But then why does the client discovery "take a long time" (according to other reports) if the user has mounted an external storage? The server must be doing something remotely after all?

The first time after mount we detect that we don't know what's in the external storage so we scan it which takes a while.
After that we only check for updates if something directly asks for meta data on the external storages

This means that the external storage will be at least partly checked for updates if you configure that folder with the sync client.

> Even if I visit the updated folder on the webinterface, the client does not sync any changes.

Ok, that's a bug with etag propagation on the server which I will look into

**Comment by icewind1991** [comment]
> Even if I visit the updated folder on the webinterface, the client does not sync any changes.

I can't reproduce that issue, the change is properly detected after I visit the external share from the webinterface for me

Do the changes made to the external share show properly in the webinterface?

**Comment by BenS89** [comment]
Yes, the webinterface recognizes all changes made in federated shares. But if I visit the federeated share using the ownCloud webinterface of the folder-owner (ownCloud 1), nothing happens on the client-side.

**Comment by BenS89** [comment]
I just want to bump this issue up. Since ownCloud introduced Federated Cloud Sharing, the ownCloud client should be able to recognize changes made on the federated shares. Are there any plans for that?

**Comment by guruz** [comment]
afaik yes.
@icewind1991 from which Version? :) please post and close

**Comment by BenS89** [comment]
@guruz  @icewind1991 Any news on this?

**Comment by mathisdt** [comment]
I don't know if it helps, but I can report that ownCloud Client 2.1.1 on Linux didn't recognize the newly added federated directory **at all**. I waited for about an hour: nothing, even though I opened the folder in the web interface as some advise to. Then I restarted the client and after that it synced correctly.

**Comment by Helios07** [comment]
This seems to be linked to https://github.com/owncloud/core/issues/20329

**Comment by guruz** [comment]
@Helios07 Thanks. oc 8.2 issue then. Please subscribe to https://github.com/owncloud/core/issues/20329
