### ISSUE TITLE
When you create a folder with 5 subfolders and go to the option Recent Changes Near to the Folder Name you can see (Unknown...)

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3963]
### Steps to reproduce
1. Install v 2.0.2RC1 (build 2790)
2. Create a new account for user1
3. Right Click on the oC icon
4. Click on the User1
5. Click on the Open folder
6. Create a folder with 5 subfolders
7. Right Click on the oC icon
8. Click on Recent Changes

### Expected behaviour
It is should see (Uploaded or Donwnloaded)

### Actual behaviour
You can see this:
![screen shot 2015-10-19 at 10 27 16](https://cloud.githubusercontent.com/assets/12032058/10572982/2935033a-764d-11e5-9c56-6aa5f78d0ab5.png)

Near to the Folder Name you can see (Unknown...)

Desktop v 2.0.2RC1 (build 2790)
Server v {"installed":true,"maintenance":false,"version":"8.2.0.10","versionstring":"8.2 RC2","edition":""}

**Comment by phil-davis** [comment]
Version 2.0.2 (build 5569) on Windows 10
I can get similar by doing folder creation or deletion. About 30 seconds after the folder concerned is uploaded or the delete is done to the server, the sync client wakes up again and seems to do another sync scan/check of some sort. At that time I get a couple of "Unknown" entries in the Recent changes list.
The Activity Log has just the expected real Uploaded and/or Deleted actions.
I guess the code to add things to the Recent changes list is a bit over-zealous about what underlying "actions" it thinks constitute a change.
![unknown](https://cloud.githubusercontent.com/assets/1535615/10701011/425b46a2-79e1-11e5-9832-ecde3612ec57.png)

**Comment by guruz** [comment]
@ckamm @ogoffart Weren't one of you making some changes regarding the tray/progress notifications that influenced or fixed this?
I don't find the commit now

**Comment by ckamm** [comment]
@guruz I don't think so.

**Comment by ckamm** [comment]
It's the folder metadata update...

**Comment by Dianafg76** [comment]
I tested this issue and is working ok
Desktop v ownCloud-2.1.0.5619-nightly20151111-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}
Closed
