### ISSUE TITLE
Files with | (vertical bar) or / (slash) are not synced without warning about that

### ISSUE THREAD

**Issue by paul-schulze** [owncloud/client#3965]
I work in a small office and we use ownCloud as our "Dropbox" solution. On HFS+ on a Mac you can create files which include a slash or a vertical bar in their name. Recently a colleague was puzzled about missing files. I investigated the problem and found out that the missing files are not even existing on the server itself. So I started inspecting the ownCloud client of the creator of the files and then I realized that the missing files have these characters in their names. But the ownCloud client did not warn that these files weren't synced. So of course my colleagues expected everything to be ok and in sync.

Maybe there are more characters which are involved with that bug. It is very important that a user sees the correct sync status of his/her files.

Maybe this is the same as #3902 I am not totally sure.

**Comment by guruz** [comment]
@paul-schulze Did you see the filenames in the activity tabs?

FYI @dragotin @danimo @jancborchardt

**Comment by paul-schulze** [comment]
@guruz Problem is the activity log in the client only showed todays' changes. Wasn't in there.

**Comment by jancborchardt** [comment]
Yeah, we need to fix this problem. I also had it before. 3 things:

* the files need a »red x« label
* the errors in the activity log need to stick to the top until they are solved, see https://github.com/owncloud/client/issues/1745
* when a file can’t be synced, there should be a desktop notification about that. Clicking it (on operating systems which bind clicking to an action) should open the Activity view with the error visible

Ok?

**Comment by ogoffart** [comment]
Should be fixed with 91525a7d33c531c04772376e833ed0238a8ee510

**Comment by jancborchardt** [comment]
@ogoffart can we also have the errors stickied on top, should there be any?

**Comment by ogoffart** [comment]
are they not?  or where do you want to put the errors?

**Comment by jancborchardt** [comment]
In the Activity list – errors do not stay on top. If there’s syncs after it, they just move down in the list. See https://github.com/owncloud/client/issues/1745

**Comment by Dianafg76** [comment]
I tested this issue, and now the Files with | (vertical bar) or / (slash) are synced 
Desktop v ownCloud-2.1.0.2829-nightly20151026.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

Closed
