### ISSUE TITLE
Locally deleted files are re-synced

### ISSUE THREAD

**Issue by gig13** [owncloud/client#3970]
### Steps to reproduce
1. A user deletes a local file
2. The file is re-synced

### Expected behaviour
When a user deletes a file locally, it should be deleted on the server and be deleted for other users that it was shared with.

### Actual behaviour
A user locally deletes a file and sometimes the file is re-synced to the local desktop.

### Server configuration
**Operating system**: Ubuntu

**Web server:** Apache

**Database:** MariaDB Galera Cluster

**PHP version:** 5.5.9-1ubuntu4.7

**ownCloud version:** 8.1.1.3

**Updated from an older ownCloud or fresh install:** Updated

**List of activated apps:** see config report
https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fclient%2F3970

**The content of config/config.php:**

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** NO

**Are you using an external user-backend, if yes which one:** NO

#### ownCloud log (data/owncloud.log)
See s3 https://s3.owncloud.com/owncloud/index.php/apps/files?dir=%2FShared%2Fowncloud%2Fsupport%2Fgithub-issues%2Fclient%2F3970

@tariqsiddiqui @MorrisJobke

**Comment by MorrisJobke** [comment]
This looks like a problem on server side. I would suspect wrong time on the server/storage side. This could be explain, why it thinks that something that is older has a newer timestamp. cc @icewind1991 is this possible? Or is this handled completely different.

**Comment by gig13** [comment]
@MorrisJobke 
Do you want me to open in core?

**Comment by MorrisJobke** [comment]
> @MorrisJobke 
> Do you want me to open in core?

I think this is the place where this needs to go.

**Comment by gig13** [comment]
account username that experience the most problem is "hlavallee"

**Comment by MorrisJobke** [comment]
> Could this be related to the default file locking mechanism in OC 8.1 and data concurrency ?

I don't think so. Because the file locking in 8.1 is only about locking a file to a single process that can write to it on the physical disk. Having concurrency here would block the concurrent update and the client would need to redo it.

**Comment by gig13** [comment]
New files on s3 -- sync client logs and owncloud logs from 20151014. Please see the 20151021 README

**Comment by gig13** [comment]
Log shows a time out for the file that was deleted.
```
Line 3: "2015-10-14T12:16:10.000Z"," 2015/10/14 12:16:10 [error] 15421#0: *17329484 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 24.200.24.52, server: , request: ""MOVE
```

**Comment by MorrisJobke** [comment]
Weird - a MOVE(rename), then a PUT (upload of new file)

```
"2015-10-14T12:16:10.000Z"," IP - USERNAME [14/Oct/2015:12:16:10 +0000] ""MOVE /remote.php/webdav/Shared/path/to/file.pdf HTTP/1.1"" 504 176 ""-"" ""Mozilla/5.0 (Windows) mirall/2.0.1 (highshare)""\n","server-name-02"
"2015-10-21T12:49:32.000Z"," IP - USERNAME [21/Oct/2015:12:49:32 +0000] ""PUT /remote.php/webdav/Shared/path/to/file.pdf HTTP/1.1"" 423 245 ""-"" ""Mozilla/5.0 (Windows) mirall/2.0.1 (highshare)""\n","server-name-01"
```

What also could be a problem is, that the MOVE was done on server1 and the PUT on server2 (if I interpret the log correctly)

@guruz @dragotin Can you find anything suspicious in the client log?

**Comment by MorrisJobke** [comment]
And the MOVE has 504 (Gateway timeout) and the PUT 423 (Locked) as response code. I think this is somehow the problem.

cc @icewind1991 for locking stuff

**Comment by StopTrain** [comment]
I just ran into this issue after an upgrade to the latest stable release of the desktop sync client and ownCloud server.   Turns out it was a permissions issue in the user's account on a specific file.  it was owned root.root... OC couldn't do anything with it... so the client would sync the delete, get denied on the server, and resync to the client.

**Comment by gig13** [comment]
Permissions are correct, so its not that.

@MorrisJobke @icewind1991 
Any thoughts on the locking?

**Comment by gig13** [comment]
@MorrisJobke @icewind1991 
Any other thoughts

**Comment by MorrisJobke** [comment]
> @MorrisJobke @icewind1991 @bboule 
> Any other thoughts

Not really. @icewind1991 @PVince81 Do you have any theory why this can happen?

**Comment by PVince81** [comment]
Does this happen in any folder, also outside of the shared folder ? Does it happen for any file or just a particular file ?

Usually I'd think external storage, but I guess there is no external storage here @gig13 ?

**Comment by gig13** [comment]
>Does this happen in any folder, also outside of the shared folder ?

So far, it seems to happen only in the shared folder and in the users folders. But, considering that they work mostly in shared folders, I can't say for certain if it is related or not to it.


>Does it happen for any file or just a particular file ?

It happens to any file and not just a particular file.


>Is there any external storage being used?

If you are talking about the external storage feature in ownCloud, no we are not using it. But, if you are talking about external storage on the server side, we are using GlusterFS.

**Comment by PVince81** [comment]
In general to avoid confusion, when I say "external storage" I always mean the ownCloud feature :smile: 

Thanks for the infos, needs further research.

**Comment by PVince81** [comment]
@MorrisJobke regarding the weird move https://github.com/owncloud/client/issues/3970#issuecomment-150274983, did you notice that the first call returns "504 Gateway timeout" ? Not sure how load balancers work, but maybe that would cause it to somehow make it use another server ?

Still not clear why there's a MOVE in the first place.

**Comment by PVince81** [comment]
Ha, and the second call received "423 Locked" as response. So maybe the file is locked for some reason. Still, if this is about deleting a file, it has nothing to do with PUT.

Does the log contain a matching "DELETE" statement ?

**Comment by PVince81** [comment]
@gig13 I read the README but it doesn't mention anything related to "locally deleted files are re-synced". It mentions a file that has disappeared from the server for unknown reasons which was then restore from trashbin.

Or maybe this resync issue is happening for that restored file. Is someone trying to purposefully delete that file locally and the server doesn't delete it but resyncs it ?

**Comment by MorrisJobke** [comment]
> Does the log contain a matching "DELETE" statement ?

Not for this file.

**Comment by gig13** [comment]
>Q: Is it possible that maybe this resync issue is happening for only restored files. 

A: It happens on existing but not restored files.

>Q: Is someone trying to purposefully delete that file locally and the server doesn't delete it but resyncs it ?

A: Yes, the user tries to delete the file by deleting it locally on its computer, but keeps being resynced, like the file is locked on the server side. From what the user told me, hs is the only one working (renaming, editing, deleting) on these files. Other user might have these folder synced, but don't work on the files in these directories.

>Q: Do you know if this is only happening for files in the trashbin (but then are subsequently restored)?

A: For now, they restore the files manually from another separate backup, in case of file disappearing, so I mostly sure this isn't related to the trashbin or the restore feature from ownCloud.

**Comment by PVince81** [comment]
Since this is 8.1, I suspect they might still be using the old files_locking app. Not sure why it would permanently lock that file.

**Comment by gig13** [comment]
Are you suggesting disabling the file lock app?

**Comment by PVince81** [comment]
That could do, yes, as a workaround.

**Comment by gig13** [comment]
@PVince81 
Any negative impacts of disabling the app?
My understanding is that their is a very very unlikely chance that data corruption could occur.

**Comment by PVince81** [comment]
files_locking doesn't protect very well against data corruption.
Best is to disable it and enable the new transactional locking: https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_transactional.html

**Comment by felixboehm** [comment]
several deadlocks per hour in ownCloud log:
```
"2015-11-23T16:43:16.775Z","mycloud","ownCloud","user-level","2"," {webdav} Exception: {
        ""Message"":""An exception occurred while executing 'UPDATE oc_appconfig SET configvalue = ? WHERE appid = ? AND configkey = ?' with params [
                1448296993.9141,
                \""files_sharing\"",
                \""5932\""
        ]:\n\n
        SQLSTATE[40001]: Serialization failure: 1213 Deadlock found when trying to get lock; try restarting transaction"",
        ""Code"":0,
        ""Trace"":""
                #0 \/home\/drive.highshare.com\/public_html\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n
```

also on {core} and {hook},

**Comment by PVince81** [comment]
Is it always on "oc_appconfig" with "files_sharing" ? As far as I remember this is used to defer etag propagation until the user (5932 is probably the storage id) in question is setup again, so the propagation is done at this time. If this value is updated concurrently several times it's probably due to people modifying many files inside a shared folder. Hmmm...

Is transactional locking enabled ? https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_transactional.html

**Comment by gig13** [comment]
@PVince81 
They are now using Transactional File locking

**Comment by MorrisJobke** [comment]
@gig13 We didn't cover this case in the call today. Is this not an issue anymore or was it just forgotten?

**Comment by gig13** [comment]
@MorrisJobke 
They are waiting for additional feedback from users, so for now this appears to be gone.

**Comment by bboule** [comment]
I assume we are waiting for feedback but assuming this is positive we can close?

**Comment by gig13** [comment]
This can be closed due to an update and not seeing the issue after additional testing. To re-open if required.
