### ISSUE TITLE
Client does not detect owncloud instance being in maintenance mode, ask for password instead

### ISSUE THREAD

**Issue by McNetic** [owncloud/client#3971]
### Expected behaviour
Client should detect maintanance mode, pause it's sync activity and probably display a corresponding notification when opened.

### Actual behaviour
Client pops up password dialog.

### Steps to reproduce
1. Have client running
2. Set owncloud in maintanance mode
3. wait for password dialog to pop up

### Server configuration
Operating system: Ubuntu > 12.04 (unknown)

Web server: Apache 2

Database: Mysql

PHP version: 5.5.9

ownCloud version: 8.1.1

Storage backend: filesystem

### Client configuration
Client version: 1.8.4

Operating system: Windows 7 x64

OS language: german

Installation path of client: default

### Logs

not applicable

**Comment by dragotin** [comment]
Thanks for your report, but please fill out the issue template as described here: 
https://raw.github.com/owncloud/client/master/issue_template.md

**Comment by guruz** [comment]
Should be fixed in newer server versions? https://github.com/owncloud/core/issues/19073

FYI @nickvergessen @danimo
