### ISSUE TITLE
Windows 7 sync client in continual "Discovery" mode

### ISSUE THREAD

**Issue by rlbyrd** [owncloud/client#3973]
I've been using my OC 8.1.3 setup for a couple of months now and am quite happy with it. My server hosts several shares--some are local disk, others are NFS mounts to my NAS, others are SCP mounts to external servers, some are CIFS mounts. The entire setup works flawlessly so far.

I opted to share out one directory (local share) on one of the locally-shared disks to one particular laptop. Set up Windows Sync for the c:\work directory on that laptop and it synced fine.

However, I note now that while sync is running on the laptop, it's never actually getting around to syncing anything. It looks as if the sync client on the laptop is "discovering" every single item that is shared on the server, rather than just the directory I have set up to sync. Any way around this? (See attachment)

![syncscreen](https://cloud.githubusercontent.com/assets/15219934/10618880/4451a4fe-7727-11e5-89db-97711e8fc0f9.png)

**Comment by guruz** [comment]
So it is not doing any uploads/downloads?
And the discovery is triggered how often? Every 30-60 sec?

I'm not sure I totally understand what is synced into ```c:\work``` (or ```c:\working\sync```?)
It is a local share from the same ownCloud to the same ownCloud different user, so no remote storage involved?

Which client version? :)

thanks

**Comment by rlbyrd** [comment]
Further details:
On my OC server, I have, among other things, the share "Work."  Within that share is a directory, ActiveClients, and within *that* directory, another named "SHB."

On the remote laptop, I have OC sync client installed, and have it configured to sync the Work/ActiveClients/SHB folder to c:\working\sync on the laptop.  Worked fine on initial sync.

There are a number of other shares available on the OC server, but I'm not referencing them in any way from the laptop or the sync client.  Nonetheless, the files/folders that are showing up in the "Discovering..." text on the client in the screen I pasted in above seem to be other folders in the Work/ActiveClients tree (e.g., Work/ActiveClients/OtherCompanyA, Work/ActiveClients/OtherCompanyB, etc.)

Here's the client information:

Version 2.0.1 (build 5446). For more information visit owncloud.com
By Klaas Freitag, Daniel Molkentin, Jan-Christoph Borchardt, Olivier Goffart, Markus Götz and others.
Copyright ownCloud, Inc.
Licensed under the GNU General Public License (GPL) Version 2.0
ownCloud and the ownCloud Logo are registered trademarks of ownCloud, Inc. in the United States, other countries, or both.
Built from Git revision 58ea49 on Sep 1 2015, 14:37:16 using Qt 5.4.0, OpenSSL 1.0.2d 9 Jul 2015

**Comment by rlbyrd** [comment]
Oh, and the "Discovering..." messages seem to be continuous, with the discovered entity changing about once per second.

**Comment by rlbyrd** [comment]
I eventually implemented a workaround with a judicious use of a symbolic link on the server-side.  Imperfect solution, but works for now.

Now the problem is I'm running in to the "Unable to write" message from the client when syncing large files as documented here: https://github.com/owncloud/core/issues/4997

Bottom line is that as badly as I want the sync mechanism to be dependable and self-healing, it's just not ready for prime-time yet, which is very disappointing.  :-(

**Comment by ogoffart** [comment]
So you confirm that the server is using ownCloud  8.1  (and not 8.2)
It the text saying `Discovering temp`  changing? (I mean is the name of the folder changing)

Would you be able to provide client logs ? (press F12)

**Comment by phil-davis** [comment]
Because your screenshot shows:
ownCloud
Syncing selected files in your account with
C:\Working\Sync

That means that the Folder Sync Connection is syncing the whole of the user's ownCloud folder tree on the ownCloud server into C:\Working\Sync

From your explanations, I thought that you wanted to sync just some sub-folder-tree like Work/ActiveClients/SHB on the server to the client location. For that you would remove the current folder sync connection and then add a new one with just the sub-folder (tree) on the server that you want to sync.

Hope I help here and do not further obfuscate the thread :)

**Comment by guruz** [comment]
@rlbyrd Also, what do you see in the server's error log and ```owncloud.log``` for large files? How large are the files?
We'd need this information to be able to tell the server guys on what to improve there.

**Comment by shinshuri** [comment]
I'm experiencing the same issue. 

We upgraded to the new version 8.2. Since the upgrade we have been unable to get our clients Windows and Mac to sync files. The clients are in a constant stage of Preparing for sync for more then 3 days now. Quite annoying.

I pulled the log file. I need help getting this resolved. Any help is appreciated.

Thanks,
Shinshuri

**Comment by rlbyrd** [comment]
I've not been at the keyboard today, but will pull logs and attach them to
the issue in the morning.  Happy to help.

r

**Comment by guruz** [comment]
@shinshuri We need to look for a common(?) pattern here between you guys. Do you use external storage on the server? anything else which is suspicious?

**Comment by ogoffart** [comment]
One thing i notcied is that ownCloud 8.2.0 is much slower, and that the PROPFIND takes a long time. But @shinshuri and @rlbyrd  problems might be different.  Please provide the logs so we can investigate what the problem is.

**Comment by shinshuri** [comment]
@guruz I am not using any external storage on the server. It is a dedicated server. @ogoffart I tried to upload the log file but it won't let me post to this thread.

**Comment by shinshuri** [comment]
@ogoffart here is a link to download the log file from my dropbox.

https://www.dropbox.com/s/22l63th84607k8g/log_10-25-15b.txt?dl=0

**Comment by shinshuri** [comment]
I'm getting reports now from other users that their files are not syncing for their accounts from the cloud to their the hard drive. Everything got deleted and only a few files have shown back up. Same thing on my end. It appears the sync mechanism for owncloud has been affected by the new version 8.2 upgrade.How soon will we get a resolution. It makes it difficult to get any work done. Can we use owncloud without upgrading on every release until the new version upgrades are stable.

**Comment by shinshuri** [comment]
Hi:

I'm finding more errors with the client and syncing of files. See linked images below.
![owncloud_syncerror](https://cloud.githubusercontent.com/assets/13647535/10775070/e6264708-7cc2-11e5-9404-be8899706c0e.png)
![owncloud_syncerror](https://cloud.githubusercontent.com/assets/13647535/10775072/e9084c32-7cc2-11e5-8e7a-02cf4e582fd0.png)

**Comment by ogoffart** [comment]
@shinshuri 

From the log: 

```
10-25 14:06:38:613 0x4ca7810 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://scloud.shinshuri.com" + "/1_shinshuri/clients/6_pedageo/castacademy/site/wp-content/plugins/formidable/js"
10-25 14:06:43:165 0x4ca7810 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList<OCC::FileStatPointer>&) Have 2 results for  "
```

Looking at the timestamps, we see it takes 5 seconds per PROPFIND query,  and we need to do that for all the changed directory, which might be a lot. (when changes are in deep directory, that includes one call for each parents)

Also the error clearly shows there is an internal server error on the owncloud server.

So this is not a bug in the client. But a problem in the server.
I heard that 8.2.1 might fix the speed regressions from 8.2.
I suggest you report a bug in the 'core' bugtracker regarding the error.

**Comment by shinshuri** [comment]
What is the link for me to use?

**Comment by ogoffart** [comment]
https://github.com/owncloud/core/issues then click on  "new issue"

**Comment by PVince81** [comment]
The discovery issue is unlikely to be related to the "database is locked" issue, but that latter issue can be investigated separately through https://github.com/owncloud/core/issues/20164

**Comment by PVince81** [comment]
@ogoffart that error in the log is only valid for 8.2, not 8.1. It doesn't explain why the issue existed in 8.1.
I posted a workaround here https://github.com/owncloud/core/issues/20164#issuecomment-152474997 for the locking issue.

**Comment by PVince81** [comment]
>Everything got deleted and only a few files have shown back up.

@shinshuri are you saying that the sync client deleted the local files instead of syncing ? Or were files deleted on the server ?

**Comment by shinshuri** [comment]
@PVince81 I apologize for the delay in responding back. I have lots of questions before I can follow up on this owncloud core post.

1. I have been requested to fill out the issue template with steps, logs, and clarifying explanations.

2. What do you mean by "database is locked" issues?

3. Does my issue encompass the "database is locked" issues? In other words, is it possible I may have two things going? If so, should I make an attempt to follow up and investigate the 20164 post and comments you have shared?

4. In response to your last question above. The sync client is deleting files on the server and my local disk as well.

**Comment by PVince81** [comment]
@shinshuri 

The issue template is here: https://raw.githubusercontent.com/owncloud/core/master/issue_template.md
Mostly used for server related issues.

2. The error message "database is locked" can be seen on your screenshot here: https://github.com/owncloud/client/issues/3973#issuecomment-151668502

3. I think your issue does not encompass the "database is locked" issue. The screenshot refers to a table that did not exist in 8.1.3. Hmm, now I realize that the original report was not from you but from @rlbyrd. @shinshuri did you have the "continual discovery mode" issue with 8.1.3 before upgrading to 8.2 ?

4. I'm mostly trying to make sense of all the different symptoms mentioned in this ticket. Mostly is starts with "continuous discovery mode" but then "deleted files" was mentioned. Might or might not be related.

**Comment by shinshuri** [comment]
@PVince81 No I did not have the continual discovery mode with 8.1.3 prior to upgraded. The client simply would not connect prior to the 8.2 upgrade. I submitted and Owncloud/core ticket. with issue ticket have not heard back yet. Files are still deleting. We are unable to use owncloud since the upgrade. at this point our operations is impacted and upgrading to redis,PHP 5.5+, with APCu appears to be a possible issue based on what IT has told me about our web server. You can see the ticket here:

https://github.com/owncloud/core/issues/20164#issuecomment-152422308

I would love to get some answers soon on this issue so we know the best course of action based on our current issue.

One question I have is can we revert back to an earlier stable version of owncloud if we are unable to get a resolution on this major roadblock?

**Comment by guruz** [comment]
@rlbyrd was this resolved?

**Comment by guruz** [comment]
We believe this is a server issue (especially given the oc_* SQL exception).
Please report if you have more info.
https://github.com/owncloud/core
