### ISSUE TITLE
[2.0.1] [centos 6 linux package] error in owncloudcmd script 

### ISSUE THREAD

**Issue by toddpfaff** [owncloud/client#3976]
### Expected behaviour

running the command owncloudcmd should run the script /usr/bin/owncloudcmd which should in turn run the program at /opt/qt-4.8/bin/owncloudcmd

### Actual behaviour

running the command owncloudcmd runs the script /usr/bin/owncloudcmd which in turn runs the program at /opt/qt-4.8/bin/owncloud

### Steps to reproduce
1. install owncloud-client-2.0.1-3.9.x86_64
2. run owncloudcmd
3. wonder why gui is running when command line program was expected
which owncloudcmd
file /usr/bin/owncloudcmd
cat /usr/bin/owncloudcmd
aha!  see patch below.

### Server configuration
Operating system:
Web server: 
Database:
PHP version:
ownCloud version:
Storage backend:

### Client configuration
Client version:
2.0.1

Operating system:
centos 6 linux

OS language:

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

-- /usr/bin/owncloudcmd.orig 2015-10-14 07:14:05.000000000 -0400
+++ /usr/bin/owncloudcmd 2015-10-20 14:50:28.614604431 -0400
@@ -5,6 +5,6 @@
source /opt/qt-4.8/bin/qt-4.8-env.sh
source /opt/neon-0.30.0/oc-neon-env.sh

-exec /opt/qt-4.8/bin/owncloud "$@"
+exec /opt/qt-4.8/bin/owncloudcmd "$@"

# end

... better yet, change to this:

exec /opt/qt-4.8/bin/basename $0 "$@"

in both owncloud and owncloudcmd scripts and then link one to the other.

tp

**Comment by sdellenb** [comment]
I didn't want to create another issue, because it's already described in full here.

The same bug is now present in [owncloud-client-2.1.0-1.1.x86_64.rpm](http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/CentOS_7/x86_64/owncloud-client-2.1.0-1.1.x86_64.rpm) for __CentOS 7__, where 2.0.2 was working fine.

The above patch solves it as well.

**Comment by jnweiger** [comment]
Already fixed in 2.1.1
