### ISSUE TITLE
[KDE Plasma5] No menu appears when clicking on Plasma 5 tray icon

### ISSUE THREAD

**Issue by DemoFreak** [owncloud/client#3977]
Description:

When owncloud-client is started, the tray icon appears, but no menu appears when clicking on KDE's Plasma 5 tray icon. The GUI isn't visible.
When the owncloud-client is started again, the GUI becomes visible. The tray icon remains "dead".
The file sync function is working, the tray icon always shows the client state.

* owncloud-client 2.0.1
* plasma-desktop 5.4.1

The strace output shows something like that:
[pid  9192] sendmsg(17, {msg_name(0)=NULL, msg_iov(2)=[{"l\3\1\1#\0\0\0$\0\0\0W\0\0\0\4\1s\0(\0\0\0org.free"..., 104}, {"\36\0\0\0No such object path '/MenuBar"..., 35}], msg_controllen=0, msg_flags=0}, MSG_NOSIGNAL) = 139

Google finds an ArchLinux bug: https://bugs.archlinux.org/task/46126

**Comment by guruz** [comment]
Did you search this bugtracker for duplicates?

**Comment by DemoFreak** [comment]
Erm... yes.
Did I overlook some duplicate?

**Comment by jospoortvliet** [comment]
I don't see a duplicate. Can only share that here, openSUSE Tumbleweed, Plasma 5.4.1, Qt5.5.0, things work ok. It might be a Plasma or Qt bug too, btw, Plasma 5.4 with Qt 5.5 has been surprisingly buggy (as 5.3 with Qt 5.4 was great).

**Comment by dragotin** [comment]
We even saw a tray icon related bug with Qt 5.5.0 which made us not updating for the last release.

**Comment by DemoFreak** [comment]
What should I say... with the last update of openSUSE Tumbleweed (Owncloud client 2.0.2, Plasma 5.4.1, Qt 5.5.0) all works as expected.
So possibly this issue could be closed, as obviously I was the only one with problems.

**Comment by jospoortvliet** [comment]
Things work fine here, slightly more up to date Tumbleweed. I vote for close. And will do so.

**Comment by marco44** [comment]
I had an update from QT 5.5.0 to 5.5.1 today (archlinux), and the problem disappeared. Thought it would be interesting to let you know...

**Comment by jospoortvliet** [comment]
Yeah, Qt 5.5.0 had quite some issues, 5.5.1 should help a lot in many areas including this...
