### ISSUE TITLE
[2.0.1] [Windows] sometimes no link for sharing is created/displayed

### ISSUE THREAD

**Issue by ntpeak** [owncloud/client#3979]
Hi @ all
I've got the problem, that on a Win7 machine, running Version 2.0.1 (build 5446)
Just sometimes, no sharing link is created or shown.
![oc-2 0 1-no-link](https://cloud.githubusercontent.com/assets/15229645/10634211/847c3494-77f0-11e5-9248-a31ae590890f.png)

In most cases it's working fully fine, so I assume that this is a bug.
Please let me know if I'll have to provide additional information or logs.

Best Regards

Rainer

**Comment by guruz** [comment]
If you enter a password and press "Set password", does it create the link?

Which server version?

**Comment by ntpeak** [comment]
Hi,

i will try to do so the next time this happens and let you know.
I'm running 8.1.1 on the server side.

Best Regards

Rainer

**Comment by guruz** [comment]
@ntpeak OK.. I think this might be a server issue because the server tells us wrongly that it needs a password. If you toggle all the settings for sharing in the server or update to a newer version it should be OK. I'll close here meanwhile :)
