### ISSUE TITLE
Feature Request: Auto (Screenshot) Sharing

### ISSUE THREAD

**Issue by maprambo** [owncloud/client#3981]
Hey client developers!

I suggest to add an option to automatically upload new items in a specified folder and then provide a public link via the clipboard.
Dropbox (at least for Mac) for example gives you a link for screenshots. Very handy, but dropbox.
With this feature you could simply let all your screenshots be saved to this specific folder. It could also be used to rapidly "drop-and-share" docs, the are many possibilities and the user can decide how to use this folder. I'm sure many users would appreciate this as it would shorten and simplify most people's workflow!

Have a nice day,
maprambo

**Comment by guruz** [comment]
Thanks. Please comment this on https://github.com/owncloud/client/issues/1811
