### ISSUE TITLE
OSX 10.6.8 desktop client

### ISSUE THREAD

**Issue by screwballl** [owncloud/client#3984]
I am unable to install either of the current owncloud desktop clients (1.8.4 nor 2.0.x) on my OSX system. It is a Core Duo 1.83GHz (Late 2006) Mac Mini with 2GB DDR2. It is not that I will not update the OS, the problem is I CANNOT update to any newer OSX. There needs to be the older 1.5.4 version of the owncloud desktop client software made available for these systems that cannot be upgraded beyond 10.6.8, since this is the primary generation of Macs and Minis around that is available, still in use, still fast enough for daily use, but cannot be upgraded. Most of the prior 10.5 and older units are either too slow or have already been scrapped. 
Please make the 1.5.4 pkg or dmg files available again so we have an option, and do not have to go with insecure or unsupported options, or be left in the dark. Please help, there are still a lot of these systems in use and would greatly benefit from that 1.5.4 version made available again (even if all the disclaimers are posted in big yellow banners saying "UNSUPPORTED VERSION" and "only for use with OSX 10.6"), let us make the choice and have that option for our older systems.

**Comment by danimo** [comment]
1.5.4 has known security issues and bugs known to lead to data loss. We will therefore not make it available again. Please use WebDAV access on the affected machines instead: https://doc.owncloud.org/server/8.2/user_manual/files/access_webdav.html#accessing-files-using-mac-os-x.

**Comment by RealRancor** [comment]
@screwballl You also should note:

> Support status
> Unsupported as of February 25, 2014, though the last security update happened in September 2013.

from https://en.wikipedia.org/wiki/Mac_OS_X_Snow_Leopard
