### ISSUE TITLE
Windows client lets you share things before they're uploaded to the server

### ISSUE THREAD

**Issue by strugee** [owncloud/client#3985]
Steps to reproduce:

1. Add a new file to the desktop client while e.g. the client is still "discovering"
2. Right-click on the file and select "Share with ownCloud"
3. Notice the error in the share pane (HTTP 404)

The issue here is that the file hasn't been uploaded yet, but the client is already offering to share.

**Comment by Dianafg76** [comment]
I tested this issue, with Desktop v ownCloud-2.1.0.2829-nightly20151026.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

This is the Log:

´´´
10-26 15:34:44:058 0x7f8088e21f40 OCC::SocketApi::command_SHARE: void OCC::SocketApi::command_SHARE(const QString &, QIODevice *) "/Users/Diana/ownCloud/some folders/example.file 3"

10-26 15:34:44:060 0x7f8088e21f40 OCC::SocketApi::sendMessage: SocketApi: Sending message: "SHARE:OK:/Users/Diana/ownCloud/some folders/example.file 3"

10-26 15:34:44:062 0x7f8088e21f40 OCC::ownCloudGui::slotShowShareDialog: void OCC::ownCloudGui::slotShowShareDialog(const QString &, const QString &, bool) Opening share dialog "//some folders/example.file 3" "/Users/Diana/ownCloud/some folders/example.file 3"

10-26 15:34:44:070 0x7f8088e21f40 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "https://..." + "ocs/v1.php/apps/files_sharing/api/v1/shares"

10-26 15:34:44:071 0x7f8088e21f40 OCC::AbstractNetworkJob::start: !!! OCC::ThumbnailJob created for "https://..." + "index.php/apps/files/api/v1/thumbnail/150/150///some folders/example.file 3"

10-26 15:34:44:292 0x7f8088e21f40 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 203 "Error downloading https://.../index.php/apps/files/api/v1/thumbnail/150/150/some folders/example.file 3 - server replied: Not Found" QVariant(int, 404)

10-26 15:34:44:293 0x7f8088e21f40 OCC::ShareDialog::slotThumbnailFetched: void OCC::ShareDialog::slotThumbnailFetched(const int &, const QByteArray &) Status code: 404

10-26 15:34:44:349 0x7f8088e21f40 OCC::ShareDialog::slotSharesFetched: void OCC::ShareDialog::slotSharesFetched(const QVariantMap &) "8.1.4.0" Fetched 0 shares

10-26 15:34:44:349 0x7f8088e21f40 OCC::ShareDialog::slotCheckBoxShareLinkClicked: void OCC::ShareDialog::slotCheckBoxShareLinkClicked() true

10-26 15:34:44:349 0x7f8088e21f40 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "https://..." + "ocs/v1.php/apps/files_sharing/api/v1/shares"

10-26 15:34:44:648 0x7f8088e21f40 OCC::OcsJob::finished: Reply to "POST" QUrl( "https://docker.oc.solidgear.es:53166/ocs/v1.php/apps/files_sharing/api/v1/shares" ) (QPair("path","//some folders/example.file 3"), QPair("shareType","3")) has unexpected status code: 404 "{"ocs":{"meta":{"status":"failure","statuscode":404,"message":"wrong path, file\/folder doesn't exist."},"data":[]}}"

10-26 15:34:46:945 0x7f8088e21f40 OCC::PropagateUploadFileQNAM::slotPutFinished: void OCC::PropagateUploadFileQNAM::slotPutFinished() QUrl( "https://docker.oc.solidgear.es:53166/remote.php/webdav/some folders/example.file 14-chunking-1624668332-4-2" ) FINISHED WITH STATUS 0 "" QVariant(int, 201) QVariant(QString, "Created")
´´´

**Comment by rullzer** [comment]
Fix in https://github.com/owncloud/client/pull/4169

**Comment by rullzer** [comment]
PR is merged. Please test :)

**Comment by strugee** [comment]
@rullzer I assume you mean ownCloud QA, not me?

**Comment by Dianafg76** [comment]
I tested this issue and now it is working OK
Desktop v ownCloud-2.1.1.5755-nightly20160107-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}
Closed

**Comment by dieselsolutions** [comment]
Hello, do we have an ETA when ownCloud-2.1.1.5755-setup.exe or newer that resolved the file will be available to download?
Version 2.1.0 (build 5683) is being extremely trouble with complaint discussed here!!!!!!!!!!!!!

**Comment by dieselsolutions** [comment]
ownCloud-2.0.1.5446-setup.exe worked beautifully and deleted files instantly once ushered!

**Comment by danimo** [comment]
@dieselsolutions The release is being delayed by a signing-related circumstance that we have no influence on. We're doing everything to speed up the process.
