### ISSUE TITLE
[2.1] Settings... and select the user, you see all the files with 0 B

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3986]
### Steps to reproduce
1. Install the version 2.1 with user 1
2. Right click on oC icon
3. Click on Settings...
4. Go to the user1

### Expected behaviour
You should see the folders with the size

### Actual behaviour
You see all the files with 0 B
![screen shot 2015-10-22 at 10 16 43](https://cloud.githubusercontent.com/assets/12032058/10660274/22a36c72-78a6-11e5-835b-29d72aea09e2.png)

### Server configuration
Desktop v ownCloud-2.1.0.2821-nightly20151022.pkg

Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

**Comment by guruz** [comment]
Does the old version (from other computer or same computer) with same server show other numbers?
I very much think this is a server issue

**Comment by Dianafg76** [comment]
Let me test with Server v 8.2

**Comment by Dianafg76** [comment]
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

**Comment by guruz** [comment]
I can confirm this is a regression in 2.1/master, independant of the server.

**Comment by Dianafg76** [comment]
I tested this issue, and now is working OK
Desktop v ownCloud-2.1.0.2829-nightly20151026.pkg
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

Closed
