### ISSUE TITLE
Changes to authentication in 2.0.1 and 2.0.2 result in "No basic authentication headers were found"

### ISSUE THREAD

**Issue by marcindobija** [owncloud/client#3987]
After upgrade of Windows client from 1.8.4 to 2.0.1 or 2.0.2 I can no longer sync files, as the client is not able to authenticate against OC. owncloud log entries say "No basic authentication headers were found" for webdav. Downgrade to 1.8.4 results in full functionality working again. Obviously I'm using good password in both cases.

**Comment by guruz** [comment]
What exact error does the client say?

**Comment by marcindobija** [comment]
client keeps popping up with password prompt and never logs in. Each attempt to provide a password generates 4 lines in the server owncloud.log saying "No basic authentication headers were found"

**Comment by guruz** [comment]
Do you use a proxy? (fixed or automatic system proxy)
Do you use any strange apps or webserver modules?
Did you try to connect with a normal WebDAV client?

**Comment by marcindobija** [comment]
ad1. same behavior on multiple clients, both directly LAN connected and accessing OC via reverse proxy (Microsoft TMG)
ad2. default install, nothing added
ad3. not sure how?

**Comment by guruz** [comment]
Pick one :) https://www.google.com/#safe=off&q=windows+webdav+client
https://doc.owncloud.org/server/8.0/user_manual/files/access_webdav.html

**Comment by marcindobija** [comment]
it works fine with firefox, it errors out with IE. Is it is because IE (and new version of owncloud) apparently uses NTLM and passes my username with the domain to OC, while firefox passes just username?

**Comment by guruz** [comment]
@marcindobija I'm talking about WebDAV access to the oC, not about accessing the ownCloud HTML web interface..

But yes, sounds like something with your server is set up wrongly. The owncloud client can only use Shibboleth or HTTP Basic Auth.

**Comment by marcindobija** [comment]
Cool. I've found the root cause. I'm running OC on Windows and I needed to remove NTLM from authentication providers in IIS. Now both clients 1.8.4 and 2.0.2 work fine. Thanks a lot!

**Comment by guruz** [comment]
BTW, I have bad news here
https://owncloud.org/blog/owncloud-server-8-1-will-not-support-windows-as-server-platform-natively/
