### ISSUE TITLE
Client never syncs a folder bigger than the threshold

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/client#3989]
1. having a folder that is bigger than the threshold of folders that should not be synced
2. client show a notice like "there are new folders that were not synchronized because they are too big: path/abc"
3. the user selects the folder to have it synced
4. go to step 2.

### expected

The folder gets synced

### actual

The folder gets never synced and the user is asked again and again.

Client version Version 2.0.1 (build 2694).

**Comment by MorrisJobke** [comment]
Also filed as a comment here: https://github.com/owncloud/client/issues/3560#issuecomment-144336239

**Comment by MorrisJobke** [comment]
cc @feli74

**Comment by dragotin** [comment]
@MorrisJobke sure that the  user pressed the ok button?

**Comment by ogoffart** [comment]
Could we have a client log of the sync?

**Comment by feli74** [comment]
Most of the times the client instantly forgets that I have confirmed with 'Ok' (client syncs and checkmarks are gone). However, sometimes it keeps the checkmarks for a couple of minutes and then forgets them..

**Comment by ogoffart** [comment]
You need to click the "apply" button otherwise the changes are not saved

**Comment by MorrisJobke** [comment]
> @MorrisJobke sure that the user pressed the ok button?

The button is called "Anwenden" (Apply).



> Could we have a client log of the sync?


I will try.

**Comment by MorrisJobke** [comment]
Mhh .... I tried it multiple times, but it is not reproducible anymore -.- -> closing this then.

**Comment by mdieterich** [comment]
I'm having this exact same issue, running owncloud client 2.0.2-3 against server version 8.1.3. I've capture some client logs, how can I get them to you? I'd prefer to go direct to a developer, if I can, to save from needing to sanitize everything.

Thanks!

Mark

**Comment by ogoffart** [comment]
There is anoher issue about it:  (#4018)

**Comment by mibadim** [comment]
I have the same problem. Even if I hit the checkbox and click "Apply", ownCloud refuses to sync folders bigger than ~900 MB. 
![bildschirmfoto - 11 12 2015 - 17 25 48](https://cloud.githubusercontent.com/assets/5670523/11749245/e93f1234-a02c-11e5-932a-05d15c0fb2e8.png)
![bildschirmfoto - 11 12 2015 - 17 26 16](https://cloud.githubusercontent.com/assets/5670523/11749247/e968967c-a02c-11e5-9afb-89e7b3502040.png)
This is really annoying. Just updated to the latest version (client and server).
BTW: There is a space missing between the colon and the folder name.

**Comment by vinyll** [comment]
Same issue here on a Mac with client version 2.2 and server version 9.1

**Comment by MarcusWolschon** [comment]
Same problem here on MacOS, German locale. Also 2.2 and 9.1

"Einige neue Ordner konnten nicht synchronisiert werden, da sie zu groß sind:<folder1>,<folder2>"
("There are new folders that were not synchronized because they are too big:<folder1>,<folder2>")
Abbrechen (abort),  Anwenden (apply)

apply what?
It doesn't ask for any kind of change to apply but makes a fatual statement.

It has a setting:
<source>Ask &amp;confirmation before downloading folders larger than</source>
<translation>&amp;Bestätigung erfragen, bevor große Ordner heruntergeladen werden. Grenze:

However with this wording that setting only applies to DOWNLOADS, not to UPLOADS.

**Comment by vinyll** [comment]
@MarcusWolschon: check your ownCloud client > settings > general > advanced settings > "[√] ask confirmation before downloading folder larger than [500 MB]".
I unchecked that box and it would sync afterwards.

**Comment by dragotin** [comment]
If  a new folder in the synchronization exceeds the limit that is configured in the "Advanced Settings", it is not automatically synced. The idea is to not flood users harddisk. If you want to have it synced anyway, just click the checkbox before the red folder and click on Apply. 

What @vinyll suggests does also work but it disables the limitation completely.

**Comment by MarcusWolschon** [comment]
Then this is a wording error and needs to be changed in ALL TRANSLATIONS.

The string should read "ask confirmation before SYNCHRONIZING folder larger than" not "before downloading" because it affects downloads and uploads.

**Comment by ogoffart** [comment]
It only affects downloads.  Uploads are not concerned.
