### ISSUE TITLE
[Mac/Win] Upgrade from a version 2.0.2 to 2.1, the account is not automatically synchronized and you need click on SIGN IN

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#3990]
### Steps to reproduce
1. Upgrade from a version 2.0.2 to 2.1

### Expected behaviour
The account is automatically synchronized and you should only have to enter the password

### Actual behaviour
There is a warning "You need to re-login to continue using the target account user1@....."
Next steps:
1. Right click on the oC icon
2. Click on Settings...
3. Select the account (e.g. user1)
4. You can see the new button (SIGN IN)
5. Click on SIGN IN
6. And you can see the screen for entering the Password
![screen shot 2015-10-23 at 09 55 30](https://cloud.githubusercontent.com/assets/12032058/10687289/41e465fc-796c-11e5-8317-d894d7071e0d.png)

### Server configuration
Desktop v ownCloud-2.1.0.2824-nightly20151023.pkg (on MAC), wnCloud-2.1.0.5577-nightly20151023-setup.exe (on Windows)
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}

**Comment by guruz** [comment]
@cdamken @michaelstingl did you experience this too?

**Comment by jlord87** [comment]
I've experienced also this in Ubuntu 15.04 (can't remember if upgrading from 1.8.4 to 2.0 or from 2.0.0/2.0.1 to 2.0.2 wich is the version I'm running now..)

**Comment by michaelstingl** [comment]
@guruz Not in my cases.

**Comment by itmands** [comment]
I am experiencing the same fault with 2.1 after update. Running on LMDE.
Removed owncloud profile, removed software. Reinstalled software, recreated account. Still have the same issue saying I need to re-login to authenticate

**Comment by guruz** [comment]
@itmands What happens if you click "Sign in" in the tray menu?
What do you see if you start the client as ```owncloud --logfile -```

If the password dialog comes up all the time I actually more suspect an issue with the server or with qtkeychain. Maybe related: https://github.com/frankosterfeld/qtkeychain/issues/55 )

**Comment by itmands** [comment]
Its not the server. I have another computer running same version of LMDE syncing with a non updated version of the client, and 2 windows computers syncing with a non updated version of the client.

I had another thought. The server is using version 6.0.6 and the client is version 2.1.0beta1 whereas the other computers are using version 1 software. Could that have any bearing?

**Comment by guruz** [comment]
@itmands What is version 1 software? server 6? Sorry, too old.

**Comment by guruz** [comment]
btw, It looks like this message "You need to re-login"... was added by @jturcotte in 6d027ebd40c85f5732eba74583a9eace08842524 for #3350

I don't know in which cases this happens, I wiped the entry for a server from my OS X keychain, then installed 2.0.2 and configured it. It saves entry as "ownCloud".
Then I quit it and run 2.1 and it runs nicely without having me re-enter the password.

@dragotin Can we close this and accept it as a small disturbance if the dialog happens for someone?

**Comment by dragotin** [comment]
Agree to @guruz opinion.

**Comment by itmands** [comment]
@gurus sorry, version 1 software was owncloud-client v 1.8.
I once again removed owncloud-client, removed the owncloud logs from the shared folder, removed owncloud from ~/.local/share/data/ownCloud, restarted computer, re-installed ownCloud-client via apt-get. It is v 2.1.0beta1
After this, I am still having the same problem continually asking me to sign in. 
I have logged onto the owncloud server to confirm username and password.

Can anyone confirm it is NOT an issue between owncloud server 6.0.6 and owncloud-client 2.0.1?

**Comment by guruz** [comment]
@itmands Ah you mean asking _in a loop_ for you to sign in? Do you mean it never signs in?
Could you please check if you are using gnome-keyring and which version?

**Comment by itmands** [comment]
using version gnome-keyring 3.8.2, it appears to sign in, then disconnects and asks for password again

**Comment by guruz** [comment]
Check out https://github.com/owncloud/client/issues/3726 https://github.com/owncloud/client/issues/4140
