### ISSUE TITLE
Syncing of Cyberduck.app fails

### ISSUE THREAD

**Issue by marbetschar** [owncloud/client#3991]
### Steps to reproduce
1. Download Cyberduck.app from the cyberduck website
2. Put Cyberduck.app in an ownCloud directory
3. Wait for the sync to fail

### Expected behavior
Every *.app file is an actual application in OS X and looks like a single file. Therefore I'd expect the file to behave like every other single file (like a *.zip for example).

### Actual behavior
The sync client throws an error, saying that symlinks can't be synced.

### Server configuration
**Operating system**:
OSX El Capitan v10.11

**Web server:**
NGINX

**Database:**
MySQL

**PHP version:**
5.6.14-1

**ownCloud version:** (see ownCloud admin page)
8.1

**Updated from an older ownCloud or fresh install:**
Fresh install

**List of activated apps:**

```
Enabled:
 - activity: 2.0.2
 - files: 1.1.10
 - files_locking:
 - files_pdfviewer: 0.7
 - files_sharing: 0.6.2
 - files_texteditor: 0.4
 - files_trashbin: 0.6.3
 - files_versions: 1.0.6
 - files_videoviewer: 0.1.3
 - firstrunwizard: 1.1
 - gallery: 0.6.0
 - provisioning_api: 0.2
 - templateeditor: 0.1
 - updater: 0.6
Disabled:
 - encryption
 - external
 - files_external
 - user_external
 - user_ldap
 - user_webdavauth
```

**The content of config/config.php:**

```
$CONFIG = array (
  'trusted_domains' =>
  array (
    0 => 'drive.mandelkind.pizza',
  ),
  'datadirectory' => '/var/www/owncloud/data',
  'overwrite.cli.url' => 'http://owncloud.mandelkind.coffee',
  'dbtype' => 'mysql',
  'version' => '8.1.3.0',
  'logtimezone' => 'UTC',
  'installed' => true,
  'theme' => 'mandelkind'
);
```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** yes/no
No - how to enable encryption?

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
No

**Comment by guruz** [comment]
Could you comment this on https://github.com/owncloud/client/issues/3202 and close this issue here? thanks
