### ISSUE TITLE
Client does not automatically sync "big" folders

### ISSUE THREAD

**Issue by marbetschar** [owncloud/client#3994]
As you can see on the following screenshot the ownCloud client refused to automatically sync the folder "biz" - saying it's 534MB in size:

<img width="912" alt="bildschirmfoto 2015-10-23 um 10 36 38" src="https://cloud.githubusercontent.com/assets/392542/10689020/7c923024-7978-11e5-9f7f-1c34ca962f8b.png">

How to automatically sync all files & folders - regardless of their size?

**Comment by danimo** [comment]
Check "General" (Allgemein) and untick the respective option:

![image](https://cloud.githubusercontent.com/assets/1315934/10689086/f700dc34-7978-11e5-8de1-9a84e088b5f9.png)

**Comment by marbetschar** [comment]
Doh! Thank you!!!!!
