### ISSUE TITLE
Client syncs .fuse_hidden* files

### ISSUE THREAD

**Issue by Pastafarianist** [owncloud/client#3999]
I am running ownCloud client `2.0.1` under Kubuntu 15.04. The `ownCloud` directory is stored on an NTFS partition, mounted with the following line in `/etc/fstab`:

    UUID=<some long id> /mnt/win-d      ntfs    defaults,umask=007,gid=46 0       0

*(As far as I remember, if this was mounted via `ntfs-3g`, the file system would say `ntfs-3g` instead of `ntfs`. These are the standard settings for mounting NTFS volumes created by the Kubuntu installer. I'm curious, what is it using?)*

At least once the client synced to the server a filed called `.fuse_hidden0002824000000003`. Inside, there was a copy of one of the other files in that directory.

The list of ignored files should probably be expanded.

**Comment by guruz** [comment]
Do you have a source or explanation somewhere that explains why those files should not be synced?
(Logically it makes sense to not sync some internal files but still..)

**Comment by Pastafarianist** [comment]
A quick search reveals: https://askubuntu.com/questions/493198/what-is-a-fuse-hidden-file-and-why-do-they-exist

**Comment by ogoffart** [comment]
You can configure your client not to sync hidden file.

**Comment by Pastafarianist** [comment]
Of course I can, but I created this issue specifically because I think this should be done by default. What do you think?

**Comment by ogoffart** [comment]
Hidden files are ignored by default.

**Comment by Pastafarianist** [comment]
Nevertheless, this particular file was synced and appeared on a different machine, where the `ownCloud` folder is stored on an `ext4` partition.

**Comment by guruz** [comment]
Thanks, ignored by default now..
