### ISSUE TITLE
 File is not synchronized to the client - Broken webserver returning empty content length for non-empty file on resume 

### ISSUE THREAD

**Issue by J-A-M** [owncloud/client#4000]
I have the same issue as #3848 (closed without a resolution)

Server has about 50000 files, between 2 and 4 of then never sync to the Windows client regardless of size.  Smallest is a few k, largest is 1.5G.  On different clients the files that won't sync are not always the same, though one file (a .EXE) has never synced on any client.

This is a guess, but it seems to me it's some sort of data escaping corruption.

Log is full of "Broken webserver returning empty content length for non-empty file on resume"
Server is Ubuntu 14.04.3 LTS
OwnCloud is 8.1.1 (older versions did the same)
Apache is 2.4.7-1ubuntu4.8
PHP is 5.5.9-1ubuntu4.13 (cli)
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
Desktop Client is Version 2.0.1 (build 5446)

**Comment by guruz** [comment]
Like the issue you linked my bet is here also on a server/configuration/proxy/servermodule/firewall issue.

**Comment by RealRancor** [comment]
> (closed without a resolution)

There was a solution posted there which fixed the issue for this user:

> Seems that server guys did some magick (eg. updated the php version and configuration) and now everything works fine :)

**Comment by ogoffart** [comment]
I made a change so it is a soft error rather than a normal error.  Because this just mean you can't resume files, so it will restart from scratch on next sync.

Otherwise, nothing can be done client side, this is not a client bug.

**Comment by J-A-M** [comment]
I don't think it is a client error.  I think it's a server error.  The server log is full of thousands of closed connection messages.  
There is no proxy the server is directly internet connected.
There is another related issue, but I am not using versioning. https://github.com/owncloud/core/issues/20234
A computer which is connected to the internet via NAT always fails on the same files and never resumes past those files, so a 100% sync is never achieved.

**Comment by guruz** [comment]
Is this shared hosting?

In any case, I'd recommend going to a higher version of ownCloud and PHP/Apache etc..

FYI @PVince81 in case you have seen this..

**Comment by PVince81** [comment]
Are we talking about uploading or downloading ?

Seeing the keyword "resume" I guess it might be about resuming a failed download ?

Could indeed be an issue with PHP modules that interfere with the response.
Best would be to first upgrade to 8.1.4 just in case, and if the problem persists, check your PHP modules.

**Comment by J-A-M** [comment]
Updated to latest 8.1.3 (STABLE)
Problems persists (after update I also got the OC_DEFAULT_MODULE is missing bug, even though I am not using encryption)
I can't sync (oc_server->client) any files at all now, please escallate this is serious. Owncloud is now write only memory.
This is a private server on an OpenVZ
PHP is 5.6.14.1
Apache is 2.4
Client is 2.0.2
The log on the windows sync client 2.0.2 is always the same:
"Broken webserver returning empty content length for non-empty file on resume" followed by "Connection Closed" then two instances of "Operation Cancelled"
It is difficult to sync the owncloud internal log in time, as it's messy and difficult to read, but as far as I can tell there are no messges in the server log related to this.

**Comment by guruz** [comment]
Possibly the OpenVZ port forwarding or whatever you might have there has an issue.

> please escallate this is serious

Information about further support options can be found here https://owncloud.org/support/
