### ISSUE TITLE
Is it possible to rename the server address without resyncing everything ?

### ISSUE THREAD

**Issue by patrickjohncollins** [owncloud/client#4002]
Given that I am connected to "https://mycoolserver.com/owncloud" as "jimbob", I would like to connect to "https://sameservernewname.com/owncloud" as "jimbob".  It's the same server, just with a different name.  I don't want to have to resync all my files.  I don't mind edit configuration files manually if needed, assuming that this action is impossible through the UI.  Any suggestions ?  For the record, I'm using MacOS.

**Comment by guruz** [comment]
It should work by editing ```owncloud.cfg``` (while client is closed).
You might need to re-enter your password (which is stored in OS X Keychain)

**Comment by patrickjohncollins** [comment]
Thanks !  Where do I find that file ?

On 26 Oct 2015, at 11:44, Markus Goetz <notifications@github.com<mailto:notifications@github.com>> wrote:


It should work by editing owncloud.cfg (while client is closed).
You might need to re-enter your password (which is stored in OS X Keychain)

**Comment by dragotin** [comment]
@patrickjohncollins its mentioned in the https://doc.owncloud.org/desktop/2.0/

**Comment by patrickjohncollins** [comment]
Yes, I read that document.  However, I can’t find : $HOME/Library/Application Support/ownCloud

I could find /Library/Application Support/ and there are a bunch of folders for other apps there, but no ownCloud...


On 26 Oct 2015, at 12:04, Klaas Freitag <notifications@github.com> wrote:

@patrickjohncollins its mentioned in the https://doc.owncloud.org/desktop/2.0/

**Comment by guruz** [comment]
Run ```Terminal```, type ```echo $HOME``` :-)
