### ISSUE TITLE
Renaming synced files in windows folder

### ISSUE THREAD

**Issue by gpi11** [owncloud/client#4006]
### Expected behaviour
File is renamed in windows folder. (eg. file1.txt becomes file2.txt)

### Actual behaviour
There are 2 files after renaming: file with a new name and file with an old name (eg. file1.txt and file2.txt).

### Steps to reproduce
1. Rename file in windows folder

Does not happen always. It seems that old file is downloaded when renaming.
Files are synced from external storage using SMB/CIFS with "Session credentials".

### Server configuration
Operating system: CentOS Linux 7

Web server: Apache/2.4.6 (CentOS)

Database: mysql  Ver 15.1 Distrib 5.5.44-MariaDB, for Linux (x86_64) using readline 5.1

PHP version: 5.4.16

ownCloud version: 8.2.0 

Storage backend:

### Client configuration
Client version:2.0.2 (build 5569)

Operating system: Windows 7 Professional

OS language: EN

Installation path of client: C:\Program Files (x86)\ownCloud

**Comment by ogoffart** [comment]
This sounds a bit like a server bug.
Would you have the logs?

**Comment by gpi11** [comment]
Here are the logs from ownCloud and client: https://gist.github.com/gpi11/c8359540c687c1b7de78.
The last time this happend was when file3.txt was renamed to file4.txt

**Comment by ogoffart** [comment]
From the log:


Previously, file2.txt was moved to file3.txt without error:
We then save the new file3.txt to the database with the previous etag: `562f2fa8703a1`

```
10-27 09:10:10:379 0x3a9cb8 OCC::PropagateRemoteMove::slotMoveJobFinished: void OCC::PropagateRemoteMove::slotMoveJobFinished()  QUrl( "http://condorsync.inea.corp/owncloud/remote.php/webdav/Projekti/Test/file2.txt" )  FINISHED WITH STATUS 0 ""
10-27 09:10:10:380 0x3a9cb8 OCC::SyncJournalDb::deleteFileRecord: "DELETE FROM metadata WHERE phash=?1" -3674188474004950458 "Projekti/Test/file2.txt"
10-27 09:10:10:382 0x3a9cb8 OCC::SyncJournalFileRecord::SyncJournalFileRecord: OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem&, const QString&) "C:/Users/puh/ownCloud/Projekti/Test/file3.txt" Retrieved inode  926 (previous item inode:  0 )
10-27 09:10:10:383 0x3a9cb8 OCC::SyncJournalDb::setFileRecord: "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14);" 4867775337648552844 23 "Projekti/Test/file3.txt" 926 0 "1445932981" "0" "562f2fa8703a1" "00000464ocier2shrpun" "MDNVW" 0 0
10-27 09:10:10:385 0x3a9cb8 OCC::SyncJournalDb
```

At a later sync, local discovery finds file4.txt and detects it is a rename.
```
10-27 09:10:18:539 0x77281f8 _csync_detect_update: file: Projekti/Test/file4.txt, instruction: INSTRUCTION_EVAL_RENAME <<=
```

But remove discovery sees that file3.txt was modified on the server and need to redownloads it. Indeed, it now has a new etag: `562f316258514`

```
10-27 09:10:19:854 0x77281f8 csync_walker: file: owncloud://condorsync.inea.corp/owncloud/remote.php/webdav/Projekti/Test/file3.txt [file_id=00000464ocier2shrpun size=0]
10-27 09:10:19:854 0x77281f8 _csync_detect_update: Database entry found, compare: 1445933423 <-> 1445932981, etag: 562f316258514 <-> 562f2fa8703a1, inode: 0 <-> 926, size: 0 <-> 0, perms: MDNVW <-> MDNVW, ignore: 0
10-27 09:10:19:855 0x77281f8 _csync_detect_update: file: Projekti/Test/file3.txt, instruction: INSTRUCTION_EVAL <<=
```

The conflict resolution will then abort the rename and consider that file4 is simply a new file and that file3 need to be downloaded because it was modified.


The question is why the etag changed on the server.  Move are supposed to preserve the etag.

**Comment by ogoffart** [comment]
Closing old issue that is liekly to be a server bug.

If the problem persists, please report a problem on the server bug tracker.
