### ISSUE TITLE
OC9.0 will come with an additional WebDAV endpoint ....

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/client#4007]
..... which would be great if the client could make use of.

``` sh
deepdiver@alien:~/Development/ownCloud/master [master]$ cadaver http://localhost:8080/remote.php/dav
Authentication required for ownCloud on server `localhost':
Username: admin
Password: 
dav:/remote.php/dav/> ls
Listing collection `/remote.php/dav/': succeeded.
Coll:   files                                  0  Okt 26 17:12
Coll:   principals                             0  Okt 26 17:12
dav:/remote.php/dav/> cd files/admin
dav:/remote.php/dav/files/admin/> ls
Listing collection `/remote.php/dav/files/admin/': succeeded.
Coll:   a b c                                  0  Okt 21 15:04
Coll:   litmus                                 0  Okt 23 12:34
Coll:   test                                   0  Okt 21 15:04
        IMG_2003.JPG                      218414  Okt  8 12:38
        IMG_2004.JPG                      238147  Okt  8 12:38
        IMG_2020.JPG                      109440  Okt  8 12:38
        IMG_2021.JPG                       92282  Okt  8 12:38
        IMG_2033.JPG                      139402  Okt  8 12:38
        IMG_2034.JPG                      261785  Okt  8 12:38
        IMG_2035.JPG                      279182  Okt  8 12:38
        IMG_2110.JPG                      107861  Okt  8 12:38
        IMG_2148.JPG                      249447  Okt  8 12:38
        IMG_2165.JPG                      208738  Okt  8 12:38
        New text file.txt                      0  Okt 12 14:04
        import.ics                        187203  Okt 12 14:03
        test-import.ics                      237  Okt 13 14:33
        welcome.txt                          163  Okt  5 17:18
dav:/remote.php/dav/files/admin/> 
```

**Comment by DeepDiver1975** [comment]
... more resources will come

**Comment by guruz** [comment]
Return it as part of the capabilities call then we try to favor it over the default endpoint?

**Comment by DeepDiver1975** [comment]
> Return it as part of the capabilities call then we try to favor it over the default endpoint?

In the first place I need this as a config option to some degree to start testing the endpoint.
especially on the cmd client for smashbox'ing.

The decision to enable it could be done on server version at the end from my understanding

**Comment by ogoffart** [comment]
It can be configured in the theme already  (in Theme::webDavPath).  Is that enough for you?
But the best would be to put that as a property in the capabilities and then we just use that. if present.

**Comment by DeepDiver1975** [comment]
> It can be configured in the theme already (in Theme::webDavPath). Is that enough for you?

using a theme will not work because I don't want to maintain my own branded client build.
In addition there is the need to pass in the user name into the dav url.

**Comment by DeepDiver1975** [comment]
> But the best would be to put that as a property in the capabilities and then we just use that. if present.

If this helps you - sure - why not

**Comment by DeepDiver1975** [comment]
Is it possible to get the dav url changed via pure configuration?

For the very first try I'd be fine if I have to explicitly set the principal name in the url - THX

@dragotin @guruz

**Comment by NvanAdrichem** [comment]
Would a CLI option --datapath , -dp [DavPath Postfix] that defaults to Theme::webDavPath() but uses the configured davpath postfix otherwise be a good solution? Or perhaps an option --add-davpath, that defaults to True that calls Theme::webDavPath if True, but accepts the configured URL as full URL when False?

**Comment by dragotin** [comment]
The new webdav endpoint will contain the user name, or rather the *principal*. That is not neccessarily the user. That means that the client needs to query the principal at startup, before accessing any webdav resources.

**Comment by MTRichards** [comment]
Need to add to this issue:
New chunking algorithm. This new algorithm will need to be implemented in client with the new endpoint on the server. Setting to 2.2 for release roughly in time with oC 9.0.

@dragotin for additional technical details please.

**Comment by dragotin** [comment]
By now, the branch with the new server implementation was not yet merged, and its not sure if it will for 9.0.
We will work on implementing against the pull request https://github.com/owncloud/core/pull/20118 in the 2.2.0 codebase to enable testing the system (smashbox tests etc.).

**Comment by dragotin** [comment]
Branch is not merged, milestone removed.

**Comment by guruz** [comment]
Status: (AFAIK) Waiting for server capability returned

**Comment by guruz** [comment]
@ogoffart How is this issue vs the new chunking?
Completely seperate?

**Comment by guruz** [comment]
https://github.com/owncloud/client/pull/5332 has been merged.
@SamuAlfageme This is about testing with new endpoint on the new server version.
