### ISSUE TITLE
Notify users if their client is outdated

### ISSUE THREAD

**Issue by jospoortvliet** [owncloud/client#4008]
Saturday at ubucon I talked to a sysadmin who had trouble: one of his users could not connect to the ownCloud server and he could absolutely not figure out why that was.

I asked if she was running the latest ownCloud Client. Turned out: 1.5 was what she had running.

It would be nice if, rather than a generic error, the client would simply say that it is too old (or new) to work with the ownCloud Server in question.

Note that the admin assumed that the user, running Ubuntu, would be up-to-date, but our Debian/Ubuntu repositories are release-specific and thus, after moving to a newer Ubuntu release a few times, her client stopped updating at some point.

**Comment by guruz** [comment]
@LukasReschke @jospoortvliet I think the newer client versions actually display a proper message. Feel free to try..

**Comment by LukasReschke** [comment]
That's what currently is shown: 
![2015-10-26_17-28-32](https://cloud.githubusercontent.com/assets/878997/10735168/fc1f1970-7c06-11e5-8791-f620aaae38ed.png)

**Comment by guruz** [comment]
https://github.com/owncloud/client/blob/419d18c1284fc2560ca781d9f42a8a9c2c32b7e4/src/libsync/connectionvalidator.cpp#L170

Also related: https://github.com/owncloud/client/issues/3794

**Comment by guruz** [comment]
Closing in favor of https://github.com/owncloud/client/issues/3794

**Comment by jospoortvliet** [comment]
Thanks, it's already a big improvement - provided the user relays this to the sysadmin, he/she should get the point just fine.
