### ISSUE TITLE
[2.0.1] Sync Hung

### ISSUE THREAD

**Issue by omnitec** [owncloud/client#4009]
Just had to do another round of "delete/reconnect" clients on two machines due to the sync process not running.

 * The client was running (shown by ps);
 * The client showed that sync status was OK (green check);
 * Adding a file never caused it to be uploaded to the server!

What would cause the hang?

Let me know if I can assist in troubleshooring.

**Comment by guruz** [comment]
We have no idea how to help you without any information about the client version, your OS, your server version, your client's file systems etc..

**Comment by guruz** [comment]
Also note that 2.0.2 is current client version :)

**Comment by ogoffart** [comment]
Please use the template: https://raw.githubusercontent.com/owncloud/client/master/issue_template.md
