### ISSUE TITLE
Not possible to use selective sync or pause sync when no connection exists

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#4010]
When the app is offline or has connection problems, I’m faced with this:
![capture du 2015-10-27 18-19-39](https://cloud.githubusercontent.com/assets/925062/10750517/2d2c779a-7cdb-11e5-902c-ffa3de4fde67.png)

There’s no real reason why the two options of »Choose what to sync« and »Pause sync« are greyed out.

(The use-case is that I’m in a very slow network with wifi access codes which have a limit of 50MB so I want to pause ownCloud before it eats my quota.)

**Comment by danimo** [comment]
`Choose what to sync` requires a server connection, so greying out is correct. I don't know exactly why `Pause sync` is greyed out. Need to look at the state machine there. @ogoffart @guruz Does anyone know out of hand?

**Comment by guruz** [comment]
Which version is that? Note that in the nightlies (2.1 based) things might have changed a bit again

**Comment by ogoffart** [comment]
I made sure "pause" is always enabled.  But selective sync needs a connection.

**Comment by jancborchardt** [comment]
Cool, thanks!

Yeah, nevermind the selective sync, I forgot that a network connection is needed for that.
