### ISSUE TITLE
Windows Client 2.0.2 didnt sync symbolic links

### ISSUE THREAD

**Issue by tuschy** [owncloud/client#4013]
Hello, part of my sync plan was that i create in my local owncloud folder some symbolic links that are linked to my data in my lokal filesystem. So i didnt need to change my way to store my files locally. After the update to Version 2.0.2 the client tells me that symbolic links are not allowed. is there a way to allow symbolic links? That would be nice.

**Comment by dragotin** [comment]
No, we currently do not sync symbolic links.
