### ISSUE TITLE
Upgrade notification does not mention ownCloud

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#4020]
When I start the sync-client I receive a notification message:

![update](https://cloud.githubusercontent.com/assets/7264495/10792820/a69be9c2-7d8e-11e5-907c-f5f97c79b552.png)

could we add that the app who has the update is ownCloud client (or the branded name)

Other apps like Thunderbird or Firefox  mention that they need attention.

@MorrisJobke @michaelstingl

**Comment by MorrisJobke** [comment]
cc @dragotin

**Comment by dragotin** [comment]
heh, yes. Absolutely.

**Comment by danimo** [comment]
Reopen for testing

**Comment by rperezb** [comment]
@danimo can this be tested with the nighlty builts?

**Comment by Dianafg76** [comment]
@cdamken Could you try with v2.0.1 beta1?

**Comment by michaelstingl** [comment]
@Dianafg76 @cdamken is OOTO. He is back in December.

**Comment by Dianafg76** [comment]
@cdamken Could you try with v 2.1.0 RC1, please?
