### ISSUE TITLE
Qt5 for CentOS6 and CentOS7

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4021]
In `isv:ownCloud:devel` we have builds of qt5-qtbase and qt5-qtwebkit already building and installing to /opt. 

We have to make the client build against these libs and finally move everything to `isv:ownCloud:desktop` and ownBrander.

**Comment by dragotin** [comment]
The packages in isv:ownCloud:nightly build against a opt-version of Qt5 for CentOS7.

**Comment by danimo** [comment]
@dragotin works nicely with the CentOS 7 live CD, with the usual problems related to detectability of systray icons in Gnome 3 and the missing GTK 3 look (which will be fixed with Qt 5.6 or 5.7). Nice work.

**Comment by dragotin** [comment]
Packages for centos7 are on Qt5. CentOS6 uses Qt4 as it did before.
