### ISSUE TITLE
Windows Client 2.x.x cannot access NAS folders

### ISSUE THREAD

**Issue by pauloeduardogodoy** [owncloud/client#4024]
In my home computer I configured several folders in my NAS to be my main folders like Documents, Videos, Pictures and Music...

Inside the Documents folder I created an ownCloud folder where I store everything I want in the cloud.

When I was using the Windows Client version 1.8.x, everything was ok and running flawless, but in the moment I upgraded to version 2.0.0 (and after to 2.0.1), the client stopped to "find" my folder...

This is the network path for my ownCloud folder:
\\\diskstation\Arquivos\Documentos\ownCloud

ownCloud Server: v8.1.3

Take a look the attached pictures for more details…

![1 8 4-01](https://cloud.githubusercontent.com/assets/15366336/10797620/a5bc0a18-7d8a-11e5-99ed-2735d40f0765.jpg)
Windows Client v1.8.4

![1 8 4-02](https://cloud.githubusercontent.com/assets/15366336/10797625/aca2e7f2-7d8a-11e5-86b2-b71ef9792ea1.jpg)
Windows Client v1.8.4

![1 8 4-03](https://cloud.githubusercontent.com/assets/15366336/10797630/b1fad4c6-7d8a-11e5-9d25-85175653b2dd.jpg)
Windows Client v1.8.4

![2 0 1-01](https://cloud.githubusercontent.com/assets/15366336/10797633/b5ff723e-7d8a-11e5-8330-f2c87d9a36eb.jpg)
Windows Client v2.0.1

![2 0 1-02](https://cloud.githubusercontent.com/assets/15366336/10797880/eb0cfc48-7d8b-11e5-85f1-ac1e046d5c54.jpg)
Windows Client v2.0.1

**Comment by RealRancor** [comment]
@pauloeduardogodoy It worth to always run the latest available version which is currently 2.0.2. According to this issue: https://github.com/owncloud/client/issues/3748 such Network / UNC stuff should be fixed there.

**Comment by pauloeduardogodoy** [comment]
Just downloaded and installed version 2.0.2. Now it's working perfectly!
Thanks @RealRancor!
