### ISSUE TITLE
owncloudcmd: Custom WebDAV path

### ISSUE THREAD

**Issue by NvanAdrichem** [owncloud/client#4025]
At my work, where in this case I am just a user, not an administrator, we use OwnCloud with Shibboleth authentication. In order to work with regular WebDAV cliens we use the special "remote.php/nonshib-webdav/" folder with alternative password generation as explained in subsection "WebDAV Support" in https://doc.owncloud.org/server/8.0/admin_manual/enterprise_user_management/user_auth_shibboleth.html . This works quite well.

However, if I want to use `owncloudcmd` from CLI on my server to synchronize a folder, it tries to access "remote.php/webdav/" which initially accepts my nonshib password and starts to synchronize (note that I cannot use my Shibboleth credentials as it requires a web page pop-up to our Single-Sign-On environment). However, it will fail after trying to sync the first file in a subdirectory.

This problem is solved in the source code by changing the following:
```
> diff --git a/src/libsync/theme.cpp b/src/libsync/theme.cpp
> index 709d4c3..404f1e2 100644
> --- a/src/libsync/theme.cpp
> +++ b/src/libsync/theme.cpp
> @@ -409,7 +409,7 @@ bool Theme::wizardSelectiveSyncDefaultNothing() const
 
> QString Theme::webDavPath() const
> {
> -    return QLatin1String("remote.php/webdav/");
> +    return QLatin1String("remote.php/nonshib-webdav/");
> }>
> 
> } // end namespace client
```

However, I expect this to break regular installations that do not have Shibboleth authentication. I tried fixing it by introducing an option `nonShibWebDAV` or `-ns` from CLI defaulting to False to choose URLs, but I got stuck on getting it through the class pointer pattern at Account::create() as my knowledge of Qt at this point is not up-to-par.

Is using an additional option the right way to go and, if yes, how to get the new parameter through the class pointer pattern? If not, do you have any other suggestions that could be implemented?

**Comment by guruz** [comment]
Maybe you want to work together with @DeepDiver1975 on https://github.com/owncloud/client/issues/4007

**Comment by DeepDiver1975** [comment]
@NvanAdrichem what you are trying to achieve can already be done by compiling the client with a custom theme - but maybe having it as pure config option would be a good idea.

@guruz and yes - to some extend this is related to #4007 because we need for configure the dav url

**Comment by NvanAdrichem** [comment]
@DeepDiver1975 that would be an option, but I like to get updates through the repository, which would be a bit harder then.

I consider making an option --davpath, -dp defaulting to Theme::webDavPath() so one can change it manually. Auto-detection does not really make sense, as people who use Non Shibboleth authentication need to keep in mind that they use their Non Shibboleth autentication anyway, so adding --nonshib makes in the CLI makes sense. Perhaps an option --nonshib defaulting to False is better, that calls a new function Theme::webDavPathNonShib() instead of Theme::webDavPath() when True.

What do you think?

**Comment by jospoortvliet** [comment]
I'm guessing this is related to https://github.com/owncloud/client/issues/3938 - allowing the client to sync publicly shared links without an account?

**Comment by NvanAdrichem** [comment]
Fixed in https://github.com/owncloud/client/pull/4060
