### ISSUE TITLE
[Overlays] [OS X] Propagate sync status directory upwards

### ISSUE THREAD

**Issue by qleo** [owncloud/client#4026]
Hi,
If I upload a file in a sub-directory, I would expect all parent directories to show the sync status as "synching" and not as "synched". (With "synching" I mean the blue, with "synched" the little white / green arrow symbol next to the file/dir name) However, this is not the case with ownCloud client 2.0.2 on Mac. Is this on purpose?

I don't expect the server version to be relevant for this, but just in case I am still using version 7.0.4.

Thanks for looking into this,
Leonard

**Comment by ckamm** [comment]
This works as expected on linux: When I modify `a/b/c/file` the file and all parent folders get the blue sync icon.

**Comment by jturcotte** [comment]
This works for me as well with the latest 2.1 dev branch. Are you at least using OS X 10.10?

**Comment by Dianafg76** [comment]
I tested this issue, and is working OK on my OS X v10.11.2
Desktop ownCloud-2.1.1.3014-nightly20160107.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}
Closed

**Comment by astroleo** [comment]
Sorry for my late answer. Yes, it works on my Mac now, too. Thanks for fixing.
