### ISSUE TITLE
Need GUI to prevent owncloud client from auto-update

### ISSUE THREAD

**Issue by danlu01** [owncloud/client#4027]
There need to be an option in settings menu to stop auto-update for Windows.  Why is that user have to edit registry to make this happen?

**Comment by danimo** [comment]
Because we want people to not stick with old versions, suffering from old bugs and potential security holes. Sysadmins who deploy with tools prefer the registry version, because it's more easy to deploy. That was actually the use case.

**Comment by danlu01** [comment]
The latest upgrade caused all sync folder to disappear.  I rather bugs are not pushed to users automatically.

**Comment by danimo** [comment]
Calculated risk really. The alternative is to never have those people auto-upgrade ever again, as the bug is in their previously running version, not the new one. Plus it doesn't happen in all cases. I'd rather have people at a version that stops showing this behavior.
