### ISSUE TITLE
[Debian] [Gnome]'Delete All Files Dialog' broken?

### ISSUE THREAD

**Issue by butonic** [owncloud/client#4028]
I was presented with this Modal dialog from the client v2.0.1 while working in my IDE:
![bildschirmfoto von 2015-10-29 09 20 12](https://cloud.githubusercontent.com/assets/956847/10813362/eb98d6ee-7e1e-11e5-99b3-1697ccd400d2.png)

I can copy the text message:

> Dieser Synchronisationsvorgang würde alle Dateien in dem lokalen Ordner 'ownCloud' entfernen.
> Vielleicht wurde der Ordner neu konfiguriert, oder alle Dateien wurden händisch gelöscht.
> Sind Sie sicher, dass sie diese Operation durchführen wollen?

But I have no other way of interacting with the dialog. I guessed and tried `Ctrl` or `Alt` and `C` (cancel), `A` (abort?), `N` (no?) but got no reaction. I deliberately did not try with `O` (ok?).

`Esc` and `F12` also yielded nothing. Right clicking the tray icon will only focus the modal dialog and bring it to front. so ... I have no way of providing additional information. More important: I have no way of canceling this.

Hm ... I will leave the client running in the background. Ping me on IRC if you need more info.

**Comment by guruz** [comment]
FYI @ogoffart

**Comment by ogoffart** [comment]
What's the client version and the Qt version?  have you seen similar problem with other dialog box (such as the one that asks confirmation to remove folders or accounts?)

**Comment by butonic** [comment]
```
$ owncloud --version
Failed to initialize instances shared memory:  "QSharedMemory::handle: UNIX key file doesn't exist" 
ownCloud version 2.0.1
$ dpkg -l '*libqt*' | grep ii
ii  libqt4-core                        4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        transitional package for Qt 4 core non-GUI runtime libraries
ii  libqt4-dbus:amd64                  4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 D-Bus module
ii  libqt4-dbus:i386                   4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 i386         Qt 4 D-Bus module
ii  libqt4-declarative:amd64           4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 Declarative module
ii  libqt4-designer:amd64              4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 designer module
ii  libqt4-dev                         4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 development files
ii  libqt4-dev-bin                     4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 development programs
ii  libqt4-gui                         4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        transitional package for Qt 4 GUI runtime libraries
ii  libqt4-help:amd64                  4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 help module
ii  libqt4-network:amd64               4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 network module
ii  libqt4-network:i386                4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 i386         Qt 4 network module
ii  libqt4-opengl:amd64                4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 OpenGL module
ii  libqt4-opengl:i386                 4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 i386         Qt 4 OpenGL module
ii  libqt4-qt3support:amd64            4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 3 compatibility library for Qt 4
ii  libqt4-script:amd64                4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 script module
ii  libqt4-scripttools:amd64           4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 script tools module
ii  libqt4-sql:amd64                   4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 SQL module
ii  libqt4-sql-mysql:amd64             4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 MySQL database driver
ii  libqt4-sql-sqlite:amd64            4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 SQLite 3 database driver
ii  libqt4-svg:amd64                   4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 SVG module
ii  libqt4-test:amd64                  4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 test module
ii  libqt4-webkit                      4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        transitional package for Qt 4 WebKit module
ii  libqt4-xml:amd64                   4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 XML module
ii  libqt4-xml:i386                    4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 i386         Qt 4 XML module
ii  libqt4-xmlpatterns:amd64           4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 XML patterns module
ii  libqt4-xmlpatterns:i386            4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 i386         Qt 4 XML patterns module
ii  libqtassistantclient4:amd64        4.6.3-6                              amd64        Qt Assistant client library (runtime)
ii  libqtcore4:amd64                   4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 core module
ii  libqtcore4:i386                    4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 i386         Qt 4 core module
ii  libqtdbus4:amd64                   4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 D-Bus module library
ii  libqtdbus4:i386                    4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 i386         Qt 4 D-Bus module library
ii  libqtgui4:amd64                    4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 amd64        Qt 4 GUI module
ii  libqtgui4:i386                     4:4.8.6+git64-g5dc8b2b+dfsg-3+deb8u1 i386         Qt 4 GUI module
ii  libqtkeychain0                     0.5                                  amd64        Cross platform password store library
ii  libqtwebkit4:amd64                 2.3.4.dfsg-3                         amd64        Web content engine library for Qt
ii  libqtwebkit4:i386                  2.3.4.dfsg-3                         i386         Web content engine library for Qt
```
stock debian 8.2.

I had problems with quassel and had to start with `QT_GRAPHICSSYSTEM="opengl"` because the text was garbled. skype also seemed to have problems until I started with `QT_GRAPHICSSYSTEM="native"`. Nevertheless, those applications only had text rendering issues, I could still interact with them, chatting with people on skype or irc. So Keyboard input does not seem to be a problem.

**Comment by butonic** [comment]
I killed the client and started with `QT_GRAPHICSSYSTEM="native" owncloud --logwindow`.  Now the dialog pops up again looking like this:
![bildschirmfoto von 2015-10-29 13 33 04](https://cloud.githubusercontent.com/assets/956847/10818433/c515d616-7e41-11e5-9a41-3957115ea20a.png)
Pressing `Esc` does nothing, and the Buttons obviously do not have any shortcuts attached.

So I guess my real issue is that the buttons have no shortcuts I can use to blindly choose an option.

**Comment by ogoffart** [comment]
so do you have the QT_GRAPHICSSYSTEM defined somewhere?
Anyway, this looks like a Qt rendering issue.  I guess you can still click on the button even if they are invisible?

**Comment by butonic** [comment]
```
$ set | grep QT
$ export | grep QT
$
```
I only set `QT_GRAPHICSSYSTEM` after this occured. And then not via export but just for the command.

I could not click on anything. The text was so big the buttons seem to have been outside the visible frame. Is it not resized dynamically?

**Comment by guruz** [comment]
I don't think it's very useful debugging this when an old Qt version is used.

We need to switch to Qt 5... @dragotin @jnweiger @hefee ..

https://github.com/owncloud/client/issues/2558
