### ISSUE TITLE
No packages for Ubuntu 15.10

### ISSUE THREAD

**Issue by tribut** [owncloud/client#4029]
Wily has been released a week ago but there are [no builds available](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client) yet for this platform.

**Comment by danimo** [comment]
As usual, we need to wait for new distributions to become available in OBS. This has only happened yesterday, and I've just scheduled packages in `isv:ownCloud:desktop`, `isv:ownCloud:testing`, and `isv:ownCloud:daily` to build 15.10 packages. Note, even if those packages build, they are not QAed. However I'd appreciate if you could try in a couple of hours and see if it works.

//cc @jnweiger  for the server

**Comment by danimo** [comment]
It seems that the man page directory is nonger created for the default build environment, or has changed location: https://build.opensuse.org/package/live_build_log/isv:ownCloud:community:nightly/owncloud-client/xUbuntu_15.10/i586. @jnweiger, please take a look.

**Comment by jnweiger** [comment]
The /usr/share/man folder is autocreated up to Ubuntu_15.04, but no longer is 15.10 
We don't populate any files there anyway.

**Comment by jnweiger** [comment]
Fixed by adding one empty doc directory, and not packaging an non-existant man directory.
Fixed in desktop and nightly.

https://build.opensuse.org/package/rdiff/isv:ownCloud:desktop/owncloud-client?linkrev=base&rev=137
https://build.opensuse.org/package/rdiff/isv:ownCloud:community:nightly/owncloud-client?linkrev=base&rev=153

**Comment by jnweiger** [comment]
Reverted. It causes https://github.com/owncloud/client/issues/4041

**Comment by jnweiger** [comment]
besides *.install files, there are also *.dirs files, that should help 15.10 without breaking the rest.

**Comment by amenk** [comment]
My current Workaround: Use the 15.04 package - seems to work okay so far.

**Comment by nazar-pc** [comment]
15.04 package works perfectly fine even on 16.04 (yes, I'm there already).

**Comment by jnweiger** [comment]
Adding a file debian.owcloud-client-doc.dirs has no effect. :-(

**Comment by jnweiger** [comment]
https://build.opensuse.org/package/rdiff/isv:ownCloud:desktop/owncloud-client?linkrev=base&rev=140#

Workaround: Generating an empty owncloud-client-doc package does the trick for now. It never carried any documentation on DEB platforms anyway. Not a big loss, but still ugly.

Download of 15.10 is now included here, please test:
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adesktop&package=owncloud-client

**Comment by amenk** [comment]
Works for me :+1:

**Comment by jnweiger** [comment]
We run with libqtwebkit4, as ubuntu-15.10 does not come with qt5 by default. That is a bit disappointing, but works fine for me too. Thanks for testing!

**Comment by nazar-pc** [comment]
Works fine, thanks

**Comment by jnweiger** [comment]
See https://github.com/owncloud/client/issues/4236 for some progress with Qt5
