### ISSUE TITLE
You can not install the client on the PC-BSD 10.2

### ISSUE THREAD

**Issue by AGARTY** [owncloud/client#4031]
Sorry for English, i am use translator.

Unfortunately, the customer can not be put on the PC-BSD (freebsd) 10.2. At the time of installation of the ports get an error:

pkg-static: ghostscript9-base-9.06_11 conflicts with ghostscript9-9.06_10 (installs files into the same place). Problematic file: / usr / local / bin / dvipdf
*** Error code 70
Stop.
make [7]: stopped in / usr / ports / print / ghostscript9-base
*** Error code 1
...
Stop.
make: stopped in / usr / ports / deskutils / owncloudclient

There is a conflict with an already installed package. OK. Then put in the repository:

 / usr / ports / deskutils / owncloudclient% sudo pkg install owncloudclient
Updating pcbsd-major repository catalogue ...
pcbsd-major repository is up-to-date.
All repositories are up-to-date.
Checking integrity ... done (2 conflicting)
Checking integrity ... done (0 conflicting)
198 The following package (s) will be affected (of 0 checked):

Installed packages to be REMOVED:
        k3b-2.0.2_23
        pcbsd-base-1425064224
        kde-workspace-4.11.14_2
        kcm-polkit-kde-0.0.20121008_3
        polkit-kde-0.99.1_3
        kdelibs-4.14.3
        plexhometheater-1.4.1_1
        ruby20-korundum-4.14.3
        marble-4.14.3
        mupdf-1.7,1
        libkdcraw-4.14.3_1
        kdegraphics-thumbnailers-4.14.3
        libkexiv2-4.14.3
        cs-kde-l10n-4.14.3
        kde-l10n-4.14.3
        es-kde-l10n-4.14.3
        hu-kde-l10n-4.14.3
        is-kde-l10n-4.14.3
        ko-kde-l10n-4.14.3
        ru-kde-l10n-4.14.3
        fi-kde-l10n-4.14.3
        hi-kde-l10n-4.14.3
        kk-kde-l10n-4.14.3
        de-kde-l10n-4.14.3
        nds-kde-l10n-4.14.3
        da-kde-l10n-4.14.3
        fa-kde-l10n-4.14.3
        he-kde-l10n-4.14.3
        sk-kde-l10n-4.14.3
        ja-kde-l10n-4.14.3
        uk-kde-l10n-4.14.3
        ug-kde-l10n-4.14.3
        pa-kde-l10n-4.14.3
        et-kde-l10n-4.14.3
        fr-kde-l10n-4.14.3
        it-kde-l10n-4.14.3
        lv-kde-l10n-4.14.3
        hr-kde-l10n-4.14.3
        el-kde-l10n-4.14.3
        gl-kde-l10n-4.14.3
        nn-kde-l10n-4.14.3
        tr-kde-l10n-4.14.3
        id-kde-l10n-4.14.3
        sl-kde-l10n-4.14.3
        nb-kde-l10n-4.14.3
        zh_TW-kde-l10n-4.14.3
        bs-kde-l10n-4.14.3
        eu-kde-l10n-4.14.3
        bg-kde-l10n-4.14.3
        km-kde-l10n-4.14.3
        ca-kde-l10n-4.14.3
        ro-kde-l10n-4.14.3
        zh_CN-kde-l10n-4.14.3
        ga-kde-l10n-4.14.3
        ia-kde-l10n-4.14.3
        en_GB-kde-l10n-4.14.3
        ar-kde-l10n-4.14.3
        pt_BR-kde-l10n-4.14.3
        wa-kde-l10n-4.14.3
        lt-kde-l10n-4.14.3
        mr-kde-l10n-4.14.3
        pt-kde-l10n-4.14.3
        sv-kde-l10n-4.14.3
        sr-kde-l10n-4.14.3
        nl-kde-l10n-4.14.3
        pl-kde-l10n-4.14.3
        ca_valencia-kde-l10n-4.14.3
        kde-runtime-4.14.3
        smokekde-4.14.3
        libkscreen-1.0.5_1
        kde-baseapps-4.14.3
        kate-4.14.3
        kactivities-4.13.3
        nepomuk-core-4.14.3_1
        kdepimlibs-4.14.3_1
        pcbsd-i18n-1420819571
        kfilemetadata-4.14.3_1
        kdeplasma-addons-4.14.3
        plasma-applet-panelspacer-0.2_12
        okular-4.14.3_1
        kdegraphics-mobipocket-4.14.3
        kdegraphics-strigi-analyzer-4.14.3
        kdegraphics-4.14.3
        kdegraphics-svgpart-4.14.3
        py27-pykde4-4.14.3
        kremotecontrol-4.14.3
        pcbsd-meta-kde-1429798531
        kdebindings-4.14.3
        py27-pykdeuic4-4.14.3
        p5-perlkde-4.14.3
        kolourpaint-4.14.3
        superkaramba-4.14.3
        kdeutils-4.14.3
        kcalc-4.14.3
        ktimer-4.14.3
        kwalletmanager-4.14.3
        kdf-4.14.3
        ark-4.14.3_1
        baloo-4.14.3
        baloo-widgets-4.14.3
        kio-audiocd-4.14.3
        libkcompactdisc-4.14.3
        libkcddb-4.14.3_1
        gwenview-4.14.3
        libkonq-4.14.3
        konsole-4.14.3
        libkipi-4.14.3
        ksnapshot-4.14.3
        print-manager-4.14.3
        kgpg-4.14.3
        sweeper-4.14.3
        filelight-4.14.3
        kfloppy-4.14.3
        kcharselect-4.14.3
        ruby20-krossruby-4.14.3
        py27-krosspython-4.14.3
        kdeadmin-4.14.3
        kcron-4.14.3
        kuser-4.14.3
        ksystemlog-4.14.3
        kdeartwork-4.14.3
        plasma-scriptengine-ruby-4.11.14
        plasma-scriptengine-python-4.11.14
        kactivitymanagerd-4.13.3
        kde-wallpapers-4.14.3
        kde-base-artwork-4.14.3
        plasma-applet-daisy-0.0.4.26_4
        kde4-style-qtcurve-1.8.18
        plasma-applet-simpleweatherforecast-1.3_7
        gtk-qt-engine-1.1_12
        ksaneplugin-4.14.3
        libksane-4.14.3
        kcolorchooser-4.14.3
        kruler-4.14.3
        kgamma-4.14.3
        kamera-4.14.3
        virtualbox-ose-4.3.30
        libvncserver-0.9.9_11
        krdc-4.14.3
        pcbsd-meta-virtualbox-1429971087
        pcbsd-i18n-qt5-1440016667
        x11vnc-0.9.13_2

New packages to be INSTALLED:
        owncloudclient: 2.0.1
        qtkeychain-qt5: 0.5.0

Installed packages to be UPGRADED:
        p5-Net-SSLeay: 1.70 -> 1.72
        libressl: 2.2.2 -> 2.3.0
        xorg-server: 1.14.7_5,1 -> 1.14.7_6,1
        ruby: 2.0.0.645,1 -> 2.0.0.647,1
        curl: 7.43.0_2 -> 7.44.0
        libgit2-glib: 0.22.8 -> 0.23.4
        libgit2: 0.22.3 -> 0.23.1
        libssh2: 1.4.3_6,2 -> 1.6.0_1,2
        libtorrent-rasterbar: 1.0.4 -> 1.0.6
        libarchive: 3.1.2_3,1 -> 3.1.2_4,1
        gnome-control-center: 3.16.3 -> 3.16.3_1
        git: 2.4.6 -> 2.6.0
        cyrus-sasl: 2.1.26_9 -> 2.1.26_12
        evolution-data-server: 3.16.4_1 -> 3.16.5
        openldap-client: 2.4.41 -> 2.4.42_2
        lftp: 4.6.3a -> 4.6.4
        libssh: 0.7.0 -> 0.7.2
        unrar: 5.21_1,5 -> 5.30,5

Installed packages to be DOWNGRADED:
        stunnel: 5.19 -> 5.14
        postgresql93-client: 9.3.10 -> 9.3.9
        apache24: 2.4.17 -> 2.4.16_1
        freetds: 0.95.65,1 -> 0.95.19,1
        php56-ftp: 5.6.14 -> 5.6.13
        php56-openssl: 5.6.14 -> 5.6.13
        php56-snmp: 5.6.14 -> 5.6.13
        net-snmp: 5.7.3_11 -> 5.7.3_9

Installed packages to be REINSTALLED:
        ptlib-2.10.10_3
        python27-2.7.10
        python34-3.4.3_1
        trousers-tddl-0.3.10_7 (needed shared library changed)
        wget-1.16.3 (needed shared library changed)
        liboauth-1.0.3_2
        heimdal-1.5.3_4 (needed shared library changed)
        apr-1.5.2.1.5.4
        gnome-vfs-2.24.4_4
        serf-1.3.8 (needed shared library changed)
        w3m-0.5.3_4 (needed shared library changed)
        pulseaudio-6.0_2
        qca-2.1.0_3
        qjson-0.8.1
        neon-0.30.1 (needed shared library changed)
        opusfile-0.6_1 (needed shared library changed)
        freerdp-1.2.0_5 (needed shared library changed)
        librtmp-2.4.20130923 (needed shared library changed)
        py27-cryptography-0.8.2 (needed shared library changed)
        libevent2-2.0.22_1
        tor-0.2.6.9 (needed shared library changed)
        liblrdf-0.5.0_7 (needed shared library changed)
        py27-curl-7.19.5.1 (needed shared library changed)
        nginx-1.8.0_3,2 (options changed)
        libmicrohttpd-0.9.37_1 (needed shared library changed)
        libshairport-1.2.0.20310_2 (needed shared library changed)
        rdesktop-1.8.3 (needed shared library changed)
        socat-1.7.3.0_2 (needed shared library changed)

The operation will free 2 GiB.

In fact, when you install the package, you must remove a lot of work for a full KDE and all system PC-BSD. Is it possible to somehow fix it? Or wait for a version that requires less dependency than the current one? With version 1.8 installation issues were not, but it, unfortunately, I have to find and could not.

Thank you.

**Comment by danimo** [comment]
This is the upstream bug tracker. I'm afraid we cannot help with ports-related issues. Please report this to the ports maintainer.
