### ISSUE TITLE
Selective sync dialog comes up when switching account tabs

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#4035]
* Have two accounts configured with a folder each
* Make sure both folders are collapsed, the selective sync interface is not visible
* Switch between the accounts in the settings ui

For me, when I switch to an account where  the selective sync interface was hidden when I left it, the folder expands and it shows it. It shouldn't do that.

**Comment by phil-davis** [comment]
In https://github.com/owncloud/client/issues/3859 I mentioned this. @guruz said it has been intentionally added.
Now for the discussion if it is "a good thing" or not...

**Comment by ckamm** [comment]
@guruz I think this is odd because the 'Cancel' and 'Apply' buttons appear - and that suggests that user action is required.

**Comment by ckamm** [comment]
I've made the buttons only pop up when changes are made to the selective sync list in 7e564083317e54362cdd8a1b9245863f35352e5c
