### ISSUE TITLE
[Linux/Windows] The client always starts on the 'Activity' tab and no tab is selected

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#4036]
When I start the client
* I always see the activity tab. I think it used to show the first account tab until recently?
* Even though I see the  'Activity' tab, the 'Acitivy' button isn't highlighted, making it look odd.

**Comment by MTRichards** [comment]
Really? What OS? 2.0.2 ? It always starts for me on the accounts tab.

**Comment by phil-davis** [comment]
2.0.2 starts on the accounts tab
2.1 starts on the activity tab

**Comment by guruz** [comment]
Might be a Linux-only issue then?
For me it's also on the account on OS X

@ogoffart

**Comment by Dianafg76** [comment]
I tested this issue and the client starts on the accounts tab
Desktop v ownCloud-2.1.0.5619-nightly20151111-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.1.4.0","versionstring":"8.1.4 RC1","edition":""}
Closed

**Comment by guruz** [comment]
@jancborchardt @MTRichards @dragotin  Isn't it actually _good_ to start on the activity tab? That's what i am much more interested (daily) than selective sync (one-time).

**Comment by MTRichards** [comment]
What I really want to see most of the time is the detailed status of the sync. Is it discovering? Is it syncing? Is the sync finished? That is why I like it starting on the accounts tab. 
The activity tab is changing for 2.1, but even that doesn't really meet my primary question for checking the client window - the state of the sync.

**Comment by jancborchardt** [comment]
@guruz @dragotin and exactly that is one reason why I’d like to combine the account view and the respective activity tab. Both visible at a glance is the most useful info.
