### ISSUE TITLE
[Packaging] owncloud-client_2.0.2-1_amd64.deb seems broken. Can't Install.

### ISSUE THREAD

**Issue by Akhenaton** [owncloud/client#4041]
The new release owncloud-client_2.0.2-1_amd64.deb doesn't install on my linux/ubuntu and broke the previous version.

Seems again a packaging issue... Anyone else ?

P.S. Automatic repos update http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.04/amd64/

**Comment by mageroya** [comment]
yep, me too. apt-get upgrade just broke my installation, seems the /usr/bin/owncloud file is missing somehow. manually installed from the VERY bottom of this page: https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client (open binary packages) and got it back working.

**Comment by nazar-pc** [comment]
Yes, package is around 5 MiB smaller and doesn't contain binaries O_o.
My installation is broken entirely:(

**Comment by nazar-pc** [comment]
Nightly is broken as well:(

**Comment by mfauvain** [comment]
Same here..

**Comment by MrsAngelD** [comment]
I'm having this issue as well :(

**Comment by tps800** [comment]
Same here. There was an older package working, the one provided since today does not. Seems all pacakges only hold doc files, but no binaries:

[code]
ii  libowncloudsync0:amd64                                      2.0.2-1                                             amd64        ownCloud sync library.
ii  owncloud-client:amd64                                       2.0.2-1                                             amd64        The ownCloud sync client - github.com/owncloud/client
ii  owncloud-client-l10n                                        2.0.2-1                                             all          Internationalisation files for ownCloud
ii  owncloud-client-nautilus                                    2.0.2-1                                             all          ownCloud nautilus plugin
[/code]

[code]
⟫ for i in libowncloudsync0:amd64 owncloud-client:amd64 owncloud-client-l10n owncloud-client-nautilus; do echo; echo $i; dpkg -L $i; done

libowncloudsync0:amd64
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/libowncloudsync0
/usr/share/doc/libowncloudsync0/changelog.Debian.gz
/usr/share/doc/libowncloudsync0/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/libowncloudsync0
/etc/ownCloud/sync-exclude.lst

owncloud-client:amd64
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/owncloud-client
/usr/share/doc/owncloud-client/changelog.Debian.gz
/usr/share/doc/owncloud-client/copyright
/usr/share/lintian
/usr/share/lintian/overrides
/usr/share/lintian/overrides/owncloud-client

owncloud-client-l10n
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/owncloud-client-l10n
/usr/share/doc/owncloud-client-l10n/copyright
/usr/share/doc/owncloud-client-l10n/changelog.Debian.gz

owncloud-client-nautilus
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/owncloud-client-nautilus
/usr/share/doc/owncloud-client-nautilus/copyright
/usr/share/doc/owncloud-client-nautilus/changelog.Debian.gz
[/code]

**Comment by tps800** [comment]
This seems to be for all supported linux distributions. I've tested:
- Ubuntu,
- Fedora

**Comment by jerrac** [comment]
Just ran into this myself. apt claimed the owncloud-client was installed, but /usr/bin/owncloud did not exist. So, just to be sure, I purged and reinstalled.

    root@Ubuntu1404Desktop:~# apt-get purge owncloud-client
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      libowncloudsync0 libqtkeychain0
    Use 'apt-get autoremove' to remove them.
    The following packages will be REMOVED:
      owncloud-client* owncloud-client-l10n*
    0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
    After this operation, 87.0 kB disk space will be freed.
    Do you want to continue? [Y/n] y
    (Reading database ... 812538 files and directories currently installed.)
    Removing owncloud-client:amd64 (2.0.2-1) ...
    Removing owncloud-client-l10n (2.0.2-1) ...
    root@Ubuntu1404Desktop:~# apt-get purge owncloud
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages were automatically installed and are no longer required:
      libowncloudsync0 libqtkeychain0
    Use 'apt-get autoremove' to remove them.
    The following packages will be REMOVED:
      owncloud*
    0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
    After this operation, 191 kB disk space will be freed.
    Do you want to continue? [Y/n] y
    (Reading database ... 812531 files and directories currently installed.)
    Removing owncloud (6.0.1+dfsg-1ubuntu1.2) ...
    Purging configuration files for owncloud (6.0.1+dfsg-1ubuntu1.2) ...
    apache2_invoke owncloud postrm: No action required
    root@Ubuntu1404Desktop:~# apt-get autoremove
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following packages will be REMOVED:
      libowncloudsync0 libqtkeychain0
    0 upgraded, 0 newly installed, 2 to remove and 0 not upgraded.
    After this operation, 229 kB disk space will be freed.
    Do you want to continue? [Y/n] y
    (Reading database ... 812518 files and directories currently installed.)
    Removing libowncloudsync0:amd64 (2.0.2-1) ...
    Removing libqtkeychain0 (0.5) ...
    Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
    root@Ubuntu1404Desktop:~# apt-get install owncloud-client
    Reading package lists... Done
    Building dependency tree       
    Reading state information... Done
    The following extra packages will be installed:
      libowncloudsync0 libqtkeychain0 owncloud-client-l10n
    The following NEW packages will be installed:
      libowncloudsync0 libqtkeychain0 owncloud-client owncloud-client-l10n
    0 upgraded, 4 newly installed, 0 to remove and 0 not upgraded.
    Need to get 42.7 kB/89.6 kB of archives.
    After this operation, 316 kB of additional disk space will be used.
    Do you want to continue? [Y/n] y
    Get:1 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.04/  libqtkeychain0 0.5 [42.7 kB]
    Fetched 42.7 kB in 1s (40.3 kB/s)         
    Selecting previously unselected package libqtkeychain0.
    (Reading database ... 812511 files and directories currently installed.)
    Preparing to unpack .../libqtkeychain0_0.5_amd64.deb ...
    Unpacking libqtkeychain0 (0.5) ...
    Selecting previously unselected package libowncloudsync0:amd64.
    Preparing to unpack .../libowncloudsync0_2.0.2-1_amd64.deb ...
    Unpacking libowncloudsync0:amd64 (2.0.2-1) ...
    Selecting previously unselected package owncloud-client-l10n.
    Preparing to unpack .../owncloud-client-l10n_2.0.2-1_all.deb ...
    Unpacking owncloud-client-l10n (2.0.2-1) ...
    Selecting previously unselected package owncloud-client:amd64.
    Preparing to unpack .../owncloud-client_2.0.2-1_amd64.deb ...
    Unpacking owncloud-client:amd64 (2.0.2-1) ...
    Setting up libqtkeychain0 (0.5) ...
    Setting up libowncloudsync0:amd64 (2.0.2-1) ...
    Setting up owncloud-client:amd64 (2.0.2-1) ...
    Setting up owncloud-client-l10n (2.0.2-1) ...
    Processing triggers for libc-bin (2.19-0ubuntu6.6) ...
    root@Ubuntu1404Desktop:~# ls /usr/bin/owncloud
    ls: cannot access /usr/bin/owncloud: No such file or directory

So, this is fun....

(Not sure why I had the owncloud package installed, maybe left over from testing something a while back?)

**Comment by rtiangha** [comment]
It's not just the 64-bit version, it's the same with the 32-bit version as well (i.e. no binaries, just the doc files).

**Comment by joede** [comment]
The direct downloads seems to contain the binaries in the packet. But these binaries uses the shared library packet with is still broken.

**Comment by grandiego** [comment]
Another one bitten by this bug.

I'm trying to extract the previous packages from my squid-deb-proxy.

**Comment by brycekottke** [comment]
having the same problem here as well. have tested the following:

Ubuntu 14.04
Debian 8

**Comment by Diceroll** [comment]
Same here (Mint 17) owncloud-client installed from opensuse.org repositories but no binaries to launch.

**Comment by floxyz** [comment]
I have the same problem with Elementary OS (based on Ubuntu 14.04). The behavior is exactly the same - I can not start it and can not install it...

**Comment by anthonymasset** [comment]
Same problem for me on Ubuntu 15.10 64bit.

**Comment by RealRancor** [comment]
@jnweiger

**Comment by enaoweb** [comment]
Same problem here with Debian 8 and linux mint 17.2, can't launch the app...

**Comment by guruz** [comment]
(btw, if you're motivated and can live with beta-quality, we're always happy if people build from git https://doc.owncloud.org/desktop/2.0/building.html ..)
(master branch == future 2.1 client)

**Comment by danimo** [comment]
@guruz No, this is clearly people with production issues. let them have production binaries.

**Comment by guruz** [comment]
Yes, I understand that. Maybe should have told that only to @nazar-pc here https://github.com/owncloud/client/issues/4041#issuecomment-152357372 :-)

**Comment by jnweiger** [comment]
rebuilding without the ubuntu 15.10 fix.

**Comment by amenk** [comment]
@jnweiger Which Ubuntu 15.10 is that?

**Comment by jnweiger** [comment]
@tps800 please double check Fedora. No changes there.

**Comment by giancarlobir** [comment]
Same here with Ubuntu 14.04.
I temporary solved downloading .deb package and installing it manually.
After this client is ok but you don't have to make any apt-get update while package is broken.

**Comment by amenk** [comment]
@jnweiger When will the package be available at the repository?

**Comment by jnweiger** [comment]
@amenk https://build.opensuse.org/package/show/isv:ownCloud:desktop/owncloud-client shows that most builds are already succeeded.
But we have no control on how long publishing to the download mirrors will take. Anything between 5 min and a day is normal for obs. sorry.

**Comment by MrsAngelD** [comment]
@jnweiger is there anyway to download the packages manually without waiting for them be published to the mirrors?

**Comment by amenk** [comment]
@jnweiger but 15.10 is broken, right?

**Comment by jnweiger** [comment]
@MrsAngelD If you are logged into the build service, you can use links like
https://api.opensuse.org/build/isv:ownCloud:desktop/Ubuntu_14.04/x86_64/owncloud-client/owncloud-client_2.0.2-3_amd64.deb (seen in https://build.opensuse.org/package/binary/isv:ownCloud:desktop/owncloud-client?arch=x86_64&filename=owncloud-client_2.0.2-3_amd64.deb&repository=Ubuntu_14.04)

For anonymous download, there is probably no workaround.

@amenk 15.10 is broken now. Fixes welcome at https://github.com/owncloud/client/issues/4029

**Comment by jnweiger** [comment]
14.04 is being pushed to the mirrors right now!

**Comment by MrsAngelD** [comment]
Thank you @jnweiger

**Comment by jnweiger** [comment]
@MrsAngelD could you test if we are back to normal?

**Comment by mvvvmd** [comment]
On Ubuntu 14.04 installing the new packages fails. I tried fixing the dependency problem I ended up with by doing `apt-get -f install` but I get the error below.

`Preparing to unpack .../libowncloudsync0_2.0.2-3_amd64.deb ...
ln: failed to create symbolic link ‘/etc/ownCloud/sync-exclude.lst.dpkg-tmp’: File exists
dpkg: error processing archive /var/cache/apt/archives/libowncloudsync0_2.0.2-3_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Errors were encountered while processing:
 /var/cache/apt/archives/libowncloudsync0_2.0.2-3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)`

**Comment by vsefer** [comment]
@mvvvmd: rm /etc/ownCloud/sync-exclude.lst.dpkg-tmp

**Comment by achennu** [comment]
How do I see that the updated package is available? After running apt-get update:

aptitude show owncloud-client
Package: owncloud-client                 
New: yes
State: installed
Automatically installed: no
Multi-Arch: same
Version: 2.0.2-1
Priority: optional
Section: devel
Maintainer: Jürgen Weigert <jw@owncloud.com>
Architecture: amd64
Uncompressed Size: 61.4 k

This is in my /etc/apt/sources.list.d/owncloud-client.list
deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/ /

It still seems a 60 kb package with build 1 on the v2.0.2.

**Comment by mvvvmd** [comment]
@vsefer works, tnx :)

For the "normal" desktop user this will be a problem though.

**Comment by MrsAngelD** [comment]
@jnweiger I was able to install on Ubuntu 14.04 and it's working now. However I had some issues installing libowncloudsync0_2.0.2-3_amd64 after the failed install previously I had to run the following commands to get the install to take. 

```
sudo rm /etc/ownCloud/sync-exclude.lst.dpkg-new && sudo rm /etc/ownCloud/sync-exclude.lst.dpkg-tmp
```
I could not install libowncloudsync0_2.0.2-3_amd64 through the package manager. I had to download the deb and install it.

So I completely removed all owncloud client packages using synaptic package manager then manual installed

```
sudo dpkg -i libowncloudsync0_2.0.2-3_amd64.deb

``

Once that was done I was able to install the rest of the packages.

**Comment by vsefer** [comment]
working on debian jessie via opensuse repo ! tnx :)

**Comment by Akhenaton** [comment]
Got it on 14.04. Works !

@MrsAngelD Didn't have the problem you mentioned with "libowncloudsync0_2.0.2-3_amd64"

**Comment by MrsAngelD** [comment]
@Akhenaton Might have just been something wonky on my system. As I said though it's up and running for me now.

**Comment by achennu** [comment]
Works on debian jessie too. Required that I aptitude purge owncloud-client and remove the symlinks in /etc/ownCloud though

Thanks for the fix!

**Comment by marcorighi** [comment]
some time ago, if you tried to install OwnCloud on Ubuntu 14.04 LTS, you got a message that was reporting something like "owncloud has important bugs so we have removed it by repository". Is owncloud team resolving this bug?

**Comment by Akhenaton** [comment]
@marcorighi That's not the point here ! And it's not what you call a bug. Ubuntu has long ago dropped ownCloud....

**Comment by RealRancor** [comment]
@marcorighi It you want some background info please read: https://owncloud.org/blog/linux-distributions-and-open-source-projects/

Nothing what needs to be resolved by the ownCloud team.

**Comment by jerrac** [comment]
I just ran apt-get update and apt-get install owncloud-client. It installed 2.0.2-3, and everything is working again. Thanks for fixing this, OwnCloud devs. :)

**Comment by jnweiger** [comment]
Thanks @jerrac and all for confirming success. Closing.

**Comment by enaoweb** [comment]
Thanks to the devs for fixing this bug quickly :+1

**Comment by vladimir-vb** [comment]
The amd64 packages for 2.0.2-3 for Ubuntu starting from 14.04 to 15.10 are still not installable on my system. For all of them libowncloudsync0 is reported as missing (dependency not satisfiable to be exact). Please, repair it.

**Comment by brycekottke** [comment]
@vladimir-vb. I am having the exact same issue still. Here is what i have tried, and still no luck.

#### Linux Mint Release:
```
bryce@spartan ~ $ cat /etc/lsb-release
DISTRIB_ID=LinuxMint
DISTRIB_RELEASE=17.2
DISTRIB_CODENAME=rafaela
DISTRIB_DESCRIPTION="Linux Mint 17.2 Rafaela"
```

Still unable to install owncloud-client. Have tried installing from both ubuntu 14.04 and debian 8 lists. Have done a full removal / clean before each install. However, have had to use **dpkg** when doing the removal. Here is some detail in regards to everything.

#### Step 1: Clean / Remove Existing Owncloud Packages:

  - clean / remove existing owncloud packages

```
sudo apt-get remove owncloud-client

bryce@spartan ~ $ sudo apt-get remove owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
You might want to run 'apt-get -f install' to correct these:
The following packages have unmet dependencies:
 owncloud-client-l10n : Depends: owncloud-client (>= 2.0.2-3) but it is not going to be installed
                        Depends: libowncloudsync0 but it is not going to be installed
E: Unmet dependencies. Try 'apt-get -f install' with no packages (or specify a solution).
```
  - Since using **apt-get** to remove the owncloud-client doesnt work. I have successfully removed it this way.

```
dpkg -r owncloud-client
dpkg -r owncloud-client-l10n

bryce@spartan ~ $ sudo dpkg -l |grep owncloud
bryce@spartan ~ $

bryce@spartan ~ $ sudo apt-get autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  libqtkeychain0
0 upgraded, 0 newly installed, 1 to remove and 5 not upgraded.
After this operation, 178 kB disk space will be freed.
Do you want to continue? [Y/n] y
(Reading database ... 279674 files and directories currently installed.)
Removing libqtkeychain0 (0.5) ...
Processing triggers for libc-bin (2.19-0ubuntu6.6) ...

bryce@spartan ~ $ sudo apt-get purge owncloud-client owncloud-client-l10n libqtkeychain0 libowncloudsync0
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package 'libowncloudsync0' is not installed, so not removed
Package 'owncloud-client' is not installed, so not removed
Package 'owncloud-client-l10n' is not installed, so not removed
The following packages will be REMOVED:
  libqtkeychain0*
0 upgraded, 0 newly installed, 1 to remove and 5 not upgraded.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
(Reading database ... 279670 files and directories currently installed.)
Removing libqtkeychain0 (0.5) ...
Purging configuration files for libqtkeychain0 (0.5) ...
```
  - Okay, successfully removed everything related to owncloud. lets clean apt-cache

```
bryce@spartan ~ $ sudo apt-get clean all
```

#### Step 2: Installing via Debian 8 / Ubuntu 14.04 apt list:

  - Update apt cache

```
bryce@spartan ~ $ sudo apt-get update
```

  - Reinstall owncloud-client (have also tried with **apt-get install -f owncloud-client**)

```
bryce@spartan ~ $ sudo apt-get install owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following extra packages will be installed:
  libowncloudsync0 libqtkeychain0 owncloud-client-l10n
The following NEW packages will be installed:
  libowncloudsync0 libqtkeychain0 owncloud-client owncloud-client-l10n
0 upgraded, 4 newly installed, 0 to remove and 5 not upgraded.
Need to get 1,629 kB of archives.
After this operation, 5,997 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/  libqtkeychain0 0.5 [42.4 kB]
Get:2 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/  libowncloudsync0 2.0.2-3 [388 kB]
Get:3 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/  owncloud-client-l10n 2.0.2-3 [323 kB]
Get:4 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/  owncloud-client 2.0.2-3 [876 kB]
Fetched 1,629 kB in 18s (88.0 kB/s)                                            
Selecting previously unselected package libqtkeychain0.
(Reading database ... 279671 files and directories currently installed.)
Preparing to unpack .../libqtkeychain0_0.5_amd64.deb ...
Unpacking libqtkeychain0 (0.5) ...
Preparing to unpack .../libowncloudsync0_2.0.2-3_amd64.deb ...
ln: failed to create symbolic link ‘/etc/ownCloud/sync-exclude.lst.dpkg-tmp’: File exists
dpkg: error processing archive /var/cache/apt/archives/libowncloudsync0_2.0.2-3_amd64.deb (--unpack):
 subprocess new pre-installation script returned error exit status 1
Selecting previously unselected package owncloud-client-l10n.
Preparing to unpack .../owncloud-client-l10n_2.0.2-3_all.deb ...
Unpacking owncloud-client-l10n (2.0.2-3) ...
Selecting previously unselected package owncloud-client:amd64.
Preparing to unpack .../owncloud-client_2.0.2-3_amd64.deb ...
Unpacking owncloud-client:amd64 (2.0.2-3) ...
Processing triggers for hicolor-icon-theme (0.13-1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Errors were encountered while processing:
 /var/cache/apt/archives/libowncloudsync0_2.0.2-3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

  - tried pulling **libowncloudsync0** and installing first, then re-installing, still no luck.

**Comment by brycekottke** [comment]
@vladimir-vb 

I was able to resolve my issue finally by doing the following.

```
$ sudo mv /etc/ownCloud /etc/ownCloud.old
$ sudo apt-get clean all
$ sudo apt-get update
$ sudo apt-get install owncloud-client
```

It appears doing a **sudo apt-get purge owncloud-client** does not remove / rename the **/etc/ownCloud** directory. After manually moving that directory, i was able to install owncloud-client again.

**Comment by vladimir-vb** [comment]
Thank you "brycekottke". Your procedure worked for me too.
Notes: I found that my system was rejecting to install the package libowncloudsync-dev_2.0.2-3_amd64.deb even though e.g. gdebi reported before install that everything is OK, then installation was run and package was not installed without a warning.

**Comment by jesselsteele** [comment]
$ sudo mv /etc/ownCloud /etc/ownCloud.old
$ sudo apt-get -f purge
$ sudo apt-get update
$ sudo apt-get install owncloud-client

Had to do this on ubuntu. Thanks for inspiration @brycekottke

I am resisting the temptation to troll. Keep going guys. This client is really useful. ;-)

**Comment by pabloheigvd** [comment]
> @vladimir-vb
> 
> I was able to resolve my issue finally by doing the following.
> 
> ```
> $ sudo mv /etc/ownCloud /etc/ownCloud.old
> $ sudo apt-get clean all
> $ sudo apt-get update
> $ sudo apt-get install owncloud-client
> ```
> 
> It appears doing a **sudo apt-get purge owncloud-client** does not remove / rename the **/etc/ownCloud** directory. After manually moving that directory, i was able to install owncloud-client again.

I don't know why but this worked for me on Pop!_OS 20.04 LTS x86_64

I'm free from dropbox now!
