### ISSUE TITLE
missing icon in the top bar in ubuntu 14.04

### ISSUE THREAD

**Issue by richardcz** [owncloud/client#4043]
I have removed the icon and I want it back. I can't get it. I've tried to reinstall it, but it did not help.

**Comment by guruz** [comment]
Please try to ask in the forum.

Do you see it when you launch the client from terminal/console via
```owncloud --logfile -```
?

**Comment by richardcz** [comment]
I have no ownclient command. I do not know ho to solve it, I've tries:

apt-get purge owncloud-client
apt-get install owncloud-client

But this did not help. Package info

dpkg -s owncloud-client
Package: owncloud-client
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 47
Maintainer: Jürgen Weigert <jw@owncloud.com>
Architecture: amd64
Multi-Arch: same
Version: 2.0.2-1

**Comment by guruz** [comment]
Now I'm wondering if this is a duplicate of https://github.com/owncloud/client/issues/4041 ?

**Comment by richardcz** [comment]
I've solved an issue here http://askubuntu.com/questions/692035/missing-icon-in-the-top-bar-in-ubuntu-14-04
