### ISSUE TITLE
Owncloud client disappeared after security update (Kubuntu)

### ISSUE THREAD

**Issue by yan-** [owncloud/client#4044]
This morning Kubuntu notified me about an available security update for the owncloud client, which I installed immediately. After that, the client disappeared. Trying to start it via terminal I get the following (translated by me from the original output in German):

    $ owncloud
    The application »owncloud« is currently not installed. You can install it through the following input:
    sudo apt-get install owncloud-client

I then try to (re)install it:

    $ sudo aptitude install owncloud-client 
    [sudo] password for [user]: 
    No packages will be installed, updated or removed.
    0 packages updated, 0 installed, 0 removed, and 0 not updated.
    0 B of files need to be downloaded. After decompression 0 B will be used additionally.

But then again:

    $ owncloud
    The application »owncloud« is currently not installed. You can install it through the following input:
    sudo apt-get install owncloud-client

I'm using Kubuntu 14.04 and as source for the client I use http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.04/.

**Comment by tflidd** [comment]
dup https://github.com/owncloud/client/issues/4041
