### ISSUE TITLE
Spanish (generic) translation for "Quit %1" & "Log out" are confusing

### ISSUE THREAD

**Issue by josebagar** [owncloud/client#4045]
Hi,

The Spanish (generic) translation for "Quit %1" and "Log out" are quite confusing when shown together.
* "Quit %1" [is translated as "Salir de %1"] (https://github.com/owncloud/client/blob/master/translations/client_es.ts#L2886), which seems fine.
* "Log out" [is translated as "Salir"] (https://github.com/owncloud/client/blob/master/translations/client_es.ts#L2823), which is not ideal since it's confusing when presented side by side with the "Salir de %1" option, since a rough translation for both can be "Quit". A better translation could be "Cerrar la sesión", which is similar to the message used in the Spanish (argentinian) translation.

Below you can see how the tray icon menu looks like in Spanish.
![owncloud_client](https://cloud.githubusercontent.com/assets/5106830/10843126/45661f46-7ef7-11e5-8ace-009175771ede.png)

Thanks for your hard work,
Joseba

**Comment by guruz** [comment]
Thanks :)

@Dianafg76 @josebagar Maybe one of you could join the Spanish team on https://www.transifex.com/owncloud_robot/owncloud/language/es/ and fix it directly there?

**Comment by josebagar** [comment]
Hi guruz,

I'm not home for the weekend, but I'll try to get it done by Monday.

Kind regards,
Joseba

**Comment by josebagar** [comment]
I have updated the translation in Transifex, so I'm guessing the code will automatically get updated at some point...

**Comment by phil-davis** [comment]
Changes should automagically come each day, like this tx-robot commit yesterday: https://github.com/owncloud/client/commit/3f8569439438d352258ca738c6d8416ba34d5e11
The translation changes are dropping in to 2.0 branch at the moment. So they would automatically end up in the next 2.0.* series release, and later be merged forward into master for 2.1 ...

**Comment by josebagar** [comment]
Great to know :)
I'm glad to be helpful.

**Comment by guruz** [comment]
Thanks @josebagar 

@danimo Change transifex to use 2.1 branch from now on?

**Comment by simbus82** [comment]
Same confusing translation for Italian: "Esci" and "Esci da Owncloud". For "Logout" action i think in italian should remain the same or use "Disconnetti". Thanks

**Comment by phil-davis** [comment]
@simbus82 You will need to make your suggested translation changes on Transifex.

**Comment by simbus82** [comment]
Of course, I have already requested access to translations. Thanks

**Comment by danimo** [comment]
@guruz Done. I also merged the 2.x translations up to master. @simbus82 @josebagar Please try the upcoming nighly build (should be up in ~20 mins)

**Comment by josebagar** [comment]
Just tested the testpilotcloud-2.1.0.5603-nightly20151104-setup.exe build from http://download.owncloud.com/desktop/daily/ and everything is much better now, thanks a lot!
![testpilot](https://cloud.githubusercontent.com/assets/5106830/10940380/50a079ac-8306-11e5-8de3-021fb001b239.png)

I also added a translation for that "Checking for changes in..." which can be seen in the image.
