### ISSUE TITLE
OwncloudClient cant connect if character '<' is in password 

### ISSUE THREAD

**Issue by pollopolea** [owncloud/client#4046]
I checked this error with clients on Linux (1.6.4), Mac (2.0.2) and Windows (2.0.2), and owncloud server 6.0.4 . If the character '<' ( character '>'  works fine) is present in the password, user will not login.

For example prueba< is an invalid password.  Spanish error message is "Error: Credenciales erróneas"

I tried with user in ldap, and with users created directly in owncloud server.

Login through owncloud server web works.

**Comment by ogoffart** [comment]
This works for me. (tested with owncloud 8.2)

Any error in the logs?

@DeepDiver1975  are you aware of an bug on the server that was fixed?

**Comment by phil-davis** [comment]
I tried with client 2.1 and server 8.1.1 and it worked fine with "<" at the end of the password.
ownCloud server 6.0.4 is old.

**Comment by danimo** [comment]
Agreed, please update.
