### ISSUE TITLE
No /usr/bin/owncloud on owncloud-client 2.0.2-1

### ISSUE THREAD

**Issue by gitkrax** [owncloud/client#4048]
I updated owncloud to client version 2.0.2-1 on Ubuntu 12.04 and can no longer figure out how to start it. The install does not come with a bin, no shortcuts are installed along the current version and I cannot start it from the command line. I tried re-installing, but still no bin.

**Comment by RealRancor** [comment]
Please install 2.0.2-3 instead of 2.0.2-1 which has already fixed that issue: https://github.com/owncloud/client/issues/4041

**Comment by gitkrax** [comment]
Updating solved the problem. Thanks.
