### ISSUE TITLE
Handling sync/ignore of git repos (all directories of a certain kind/application)

### ISSUE THREAD

**Issue by KloolK** [owncloud/client#4054]
I use owncloud to sync all my documents. This folder contains several git repos which I'd like to exclude from sync. I know about the ignore settings, but I'd have to add every single repo to the ignore list and take good care not to oversee any.

I searched for similar issues and found #3857 and owncloud/core#2470 . Some people don't want to exclude all git repos so just ignoring folders containg a `.git` subfolder won't be enough.

A list in the settings GUI showing all git repos could be used. With a checkbox for every repo whether to ignore it or not.

I'd be happy to work on this, provided it is considered useful.

**Comment by ogoffart** [comment]
Dusplicate of https://github.com/owncloud/client/issues/2097
