### ISSUE TITLE
[Linux] [Fedora] Client does not accept Let's Encrypt certificates

### ISSUE THREAD

**Issue by rbarlow** [owncloud/client#4062]
I am experiencing this error message when I start the OwnCloud client, configured to connect to my server with a Let's Encrypt certificate:

```
Warnings about current SSL Connection:
The issuer certificate of a locally looked up certificate could not be found
with Certificate electronsweatshop.com
Organization: <not specified>
Unit: <not specified>
Country: <not specified>
Fingerprint (MD5): 02:d5:6b:f9:2c:23:b1:05:e7:e2:f9:fb:d7:e2:60:64
Fingerprint (SHA1): 09:71:46:51:df:2a:e3:99:5e:5f:6a:5d:f6:a2:4a:a7:24:05:98:de

Effective Date: Sun Nov 1 03:15:00 2015
Expiration Date: Sat Jan 30 03:15:00 2016
Issuer: Let's Encrypt Authority X1
Organization: Let's Encrypt
Unit: 
Country: US
```

I am confident that I have configured the httpd server correctly (using the correct key, certificate, and CA chain) as the following clients accept the certificate without issue: Firefox, Seamonkey, curl, openssl s_client, Miredo, Psi, and Conversations (Android).

There are a couple possible explanations for this issue:

0) The client cannot use certificate chains.
1) The client does not trust the DST Root CA X3, which has cross signed the Let's Encrypt certificate. This would be surprising, since DST is a widely trusted certificate authority and every other program on my computer does not have any issue with trusting it.

I don't have an easy way to diagnose these two possibilities, but I do know that the OwnCloud client has a few issues where it does not trust system certificate stores:

https://github.com/owncloud/client/issues/2964
https://github.com/owncloud/client/issues/3739

I am running version 1.8.0 on Fedora Rawhide:

```
% rpm -q mirall
mirall-1.8.0-3.fc23.x86_64
```

Let me know if you require any more information!

**Comment by danimo** [comment]
All the client does is use the distributions root certificates through Qt and OpenSSL. We have seen other reports (e.g. #3739), but I was not able to reproduce. Anyway, my DST-signed letsencrypt domain works on Ubuntu and Windows. I need to setup Fedora once of these days. Any chance that you can try with the packages that we provide, or ask Fedora to upgrade Rawhide to 2.0.2?

**Comment by danimo** [comment]
Note that Fedora and Debian/Ubuntu have different ways of looking up certificates. This is the only difference I see.

**Comment by agilob** [comment]
Have the same problem, on ArchLinux and windows certificate is recognized. On Ubuntu 15.04 with firefox cert is not recognized.

**Comment by danimo** [comment]
@agilob You mean that also firefox does not recognize it?

**Comment by agilob** [comment]
Yes, firefox on ubuntu 15.04. I joined beta and deployed LE on https://agilob.net/ 

Tested on firefox 41 on Sunday, firefox didn't accept cert.

**Comment by danimo** [comment]
@agilob and how is that related to the ownCloud client? Same behavior? Also failing?

**Comment by agilob** [comment]
Sorry I found the same issue twice, I was going to report this in LetsEncrypt :D

**Comment by rbarlow** [comment]
@danimo I have filed a downstream bug, where I suggested that they bump to 2.0.2 as you suggested:

https://bugzilla.redhat.com/show_bug.cgi?id=1278494

I will report back here once they have done that whether it solves the issue or not. I know for certain that version 1.8.0 does not trust the system certificate store in Fedora (which is why I reported the other bug) so that might be the issue. It's possible that this is entirely a downstream issue. If you don't mind, I'd like to keep this open until we can determine whether the issue is downstream or upstream. Thanks for the suggestion!

@agilob I am confident that it is not a server-side issue, as all other clients trust my OwnCloud server (clients such as curl, wget, openssl s_client, firefox, seamonkey, midori, etc.) What version of the OwnCloud client are you using? FYI, Firefox always uses its own certificate store on every OS, so that's something to be aware of. However, the Mozilla certificate store does contain the DST root on the OSes I've tried (Fedora, CentOS, Gentoo, Cyanogenmod, Android, and OSX), so LE certificates are trusted by Firefox in my experience.

**Comment by rbarlow** [comment]
It turns out that Fedora had renamed the package from mirall to owncloud-client, and that version 2.0.1 was available with that new package. After updating to that version, this issue was resolved for me. Apologies for the noise!

**Comment by rloutrel** [comment]
Config: Ubuntu 15.04
Repos: deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_15.04/ /

I am sorry to bump this, but I am using the owncloud client 2.1.1 (freshly updated today) and it seems that let's encrypt is not recognized.
It was already present on 2.1.0

Info about the certifcate:
https://www.sslshopper.com/ssl-checker.html?host=owncloud.systemsaviour.com#hostname=owncloud.loutrel.eu

It is accepted by Firefox and chromium (I do not have chrome, IE or safari). But it seems to come from the desktop client and not the server configuration.

If required I can try to compile, install and test but definitely not fix it myself.

Optional question:
- Is there an easy way to remove a manually accepted certificate (for testing purpose)?
