### ISSUE TITLE
Warning for symbolic links or bogus filenames

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#4064]
As we know, the client does not sync all files (for instance: no symbolic links or files with the following symbols: : ; ? * " > < | in file-name). However, if symbolic links are not synced, the systray icon remains green (see status-incorrect1.jpg).
Also within the Settings it says: Syncing selected files in your account with "name of the cloud"  (shown as synced). This is confusing since not all the files that the user tried to sync are actually synced.

Advanced users are able to find this out via the activity screen, but the majority of users will just assume that there files are all synced and will perceive ownCloud as unstable when they miss certain files.
Therefore, we would like to see some kind of error message or warning to users who try to sync files that cannot be synced due to build-in restrictions.

@MorrisJobke 

00004066

**Comment by MorrisJobke** [comment]
@jancborchardt Any good idea how to communicate this to the user?

**Comment by cdamken** [comment]
IMO, a different icon could be shown in the folder and pop-up a window or switch to activity  tab where the warning are shown... but I'm not the expert.

**Comment by dragotin** [comment]
In the beginning, there was a little warning sign in the tray icon to indicate that there were warnings. But that I had to remove to not annoy people. The current state of how it is is the result of long discussions.

**Comment by guruz** [comment]
Related:
https://github.com/owncloud/client/issues/3902

**Comment by guruz** [comment]
@cdamken Is this specifically about 2.0 ? Because there was also a change with regards to symbolic links on Windows, maybe this is the actual root cause?

**Comment by cdamken** [comment]
I'll aks

**Comment by dragotin** [comment]
related: #4083

**Comment by cdamken** [comment]
@guruz 
> @cdamken Is this specifically about 2.0 ? Because there was also a change with regards to symbolic links on Windows, maybe this is the actual root cause?

Same behaivor with 1.8.4

The customer experience:
```
I just re-installed 1.8.4, but I got the same issue (see enclosure). In
addition, it is on Mac. The main problem here is that the message the
client gives is not wrong, but user-unfriendly: It does not indicate
that syncing went wrong (incomplete due to symbolic links and / or other
symbols).
```

Only if you go to the activity tab you notice (if you have luck to see it after a large list) that it says symlinks are not supported.

**Comment by MorrisJobke** [comment]
@jancborchardt Can you have a look at this use case UX wise? Thanks :)

**Comment by guruz** [comment]
Easiest would be to merge it with the unsynced-items from https://github.com/owncloud/client/pull/4083#issue-115504177

I'd also recommend to switch the default tab to the "Activity" tab..

**Comment by dragotin** [comment]
Please check 2.1.0 beta1 if that fits the needs.

**Comment by cdamken** [comment]
The changes look fine, I will confirm it with the customer and I let you know.

Thanks

**Comment by cdamken** [comment]
No new comments from the customer. @guruz you can close the ticket if you want

**Comment by cdamken** [comment]
@guruz The customer reopen the issue:

```
I discussed it with a colleague and we were wondering if instead of
'activity --> server activity' you could make 'activity --> not synced'
the home-screen? With SURFdrive we have 'server activity' disabled so
this screen for us not of any use. In addition, users will click mostly
on this to verify if the sync worked correctly. Therefore, for us,
'activity --> not synced' would be the preferred home-screen.
```

If the Activity app is disable, the sync client should not show the tab, or better, the local activity.

**Comment by guruz** [comment]
@cdamken Do they also want the "Activity" menu bar entry on the top as the default? (vs having the sync  folder selective sync & progress) as home?
2.1.1 or 2.2?

**Comment by dragotin** [comment]
I agree that if there is no account having the activities enabled, we should not show the Activity tab

**Comment by MTRichards** [comment]
Back to the top on these issues, does the client recognize a symbolic link and ignore it? @dragotin @danimo 

This would qualify to me as a red x for these files (since they did not sync) and then they show up in the sync issue tab.

**Comment by cdamken** [comment]
> @cdamken Do they also want the "Activity" menu bar entry on the top as the default? (vs having the sync folder selective sync & progress) as home?
> 2.1.1 or 2.2?

The activity app is disabled in the server and the activity tab does not show what happens locally. It would be good to know, if the server activity app is not available or installed, that the client provided the information what is the client doing .

**Comment by dragotin** [comment]
Sure, symbolic links are ignored as they always were. And that is mentioned in the *not synced* tab of course.

@cdamken If the activity app is not enabled, it says so in the client on the empty activity. The sync activity tough is in the tab with the same name.

**Comment by cdamken** [comment]
@dragotin Thanks.

**Comment by dragotin** [comment]
![nosynced](https://cloud.githubusercontent.com/assets/1070214/14633050/0c933a08-061c-11e6-891a-aa17f92fb4ce.png)

We also show the number of the not synced items in the tab in 2.2.0.  So I think this is fine. Please reopen if not.
