### ISSUE TITLE
[Linux Mint ] "File name contains invalid characters..." Is coming soon repair?

### ISSUE THREAD

**Issue by JukkaWallin** [owncloud/client#4066]
![kuvakaappaus 2015-11-03 16 56 38](https://cloud.githubusercontent.com/assets/14910989/10915617/3f0700b8-8260-11e5-8952-ec90436070d9.png)

also write-protected file system?
![kuvakaappaus 2015-11-03 19 13 04](https://cloud.githubusercontent.com/assets/14910989/10916175/cf9566c2-8262-11e5-938e-2df30b901c17.png)

Why is the program claims "File name contains invalid characters that can not be synchronized platform independent" or "internal server error" 
Or is this just a problem in the Finnish language? The program recognizes the problem of such alphabet with special characters, such as the Nordic languages!!

**Comment by JukkaWallin** [comment]
also write-protected file system?

**Comment by JukkaWallin** [comment]
![kuvakaappaus 2015-11-03 19 13 04](https://cloud.githubusercontent.com/assets/14910989/10915791/0b2db704-8261-11e5-8beb-ac2ba0fa26d4.png)

**Comment by guruz** [comment]
Which version of the client and server are you using?
Do you use the ```;``` in the filename I see on the screenshot?

**Comment by JukkaWallin** [comment]
Desktop Client is 2.0.2

**Comment by RealRancor** [comment]
@JukkaWallin oC 7.0.3 is fairly old. Maybe try to at least 7.0.11 to see if this is solving the internal server error problem.

**Comment by JukkaWallin** [comment]
I do not know how to zyxel owncloud will be updated to a newer version. The NSA program is the latest version. As I recall, the older owncloud desktop version was equally the same mistakes as in the current in the current version.

**Comment by RealRancor** [comment]
@JukkaWallin Thats probably something you should clarify with the creator of the Zyxel packages or a Zyxel community. You should note that oC7 will reach End-of-Life in Q1/2016: https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule and so no bugfixes and security updates are provided.

**Comment by danimo** [comment]
"File name contains invalid characters" is already fixed for 2.1 in 0fde7f0e6bde80d5d57902f4bacd54ae01e3338f. For the server error, please discuss the update to OC 8 with ZyXel or its community.

**Comment by ogoffart** [comment]
right, it needs the client 2.1  and the server 8.1 to support the ':' as a charachter in filenames.

**Comment by JukkaWallin** [comment]
Thanks info 😊
