### ISSUE TITLE
Activities tab: Hide files in ignore list (or provide checkbox)

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#4069]
The activities view shows every not-sync of ignored files. This is for me as a user not important. On the contrary it clutters the list very much:

![ignored](https://cloud.githubusercontent.com/assets/2737900/10934314/59035e74-82df-11e5-9d44-300ca58c3f0b.png)

To me it seems that this information is only relevant for debugging and setting up but not for everyday use.

So I suggest:
 - Either do not show ignored files in activities tab.
 - Or provide checkbox to allow hiding them.

@jancborchardt What do you think?

**Comment by guruz** [comment]
There was also the proposal by @cloo to be able to filter
https://github.com/owncloud/client/issues/4067

**Comment by LukeOwncloud** [comment]
Kind of, however, that issue (in particular https://github.com/owncloud/client/issues/1745) is about showing and easily finding errors. My point is to **ignore** *ignored files*.

**Comment by phil-davis** [comment]
Yes, there is something to be said for being able to tell the software to be silent about all the things it has been told NOT to do.
It didn't launch a satellite, it didn't drive you to Munich, it didn't sync all the other files spread all over your computer and it didn't sync the files that you told it to ignore - at least an option for it not to tell you about any of these is useful :)

**Comment by LukeOwncloud** [comment]
Fix with 2.1.0 ("GUI: Added a separate view for not synced items, ignores, errors").
