### ISSUE TITLE
[File Firewall] If you create a Rule Request Type is Public share link, on Desktop client you don't have any information about the rule

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4074]
### Steps to reproduce
1. Install on Desktop v 2.1.0 with differents users (user1, user2, user3....)
2. Go to the Server Web with Admin
3. Go to Admin/administrator
4. Go to File Firewall option
5. Create this Rule 
![screen shot 2015-11-04 at 15 46 01](https://cloud.githubusercontent.com/assets/12032058/10941332/34018138-830b-11e5-90df-64efac811a13.png)
6. When you save the Rule and go to the Desktop client
7. Create a New folder (e.g. Hello)
8. Rigth click on the folder Hello
9. Click on Share with oC
10. Click on the URL (https://.........). You can see this
![screen shot 2015-11-04 at 15 43 39](https://cloud.githubusercontent.com/assets/12032058/10941452/c1d4f206-830b-11e5-85b3-5a3ad8496b19.png)

### Actual behaviour
But, on Desktop client you don't have any information about the rule

### Server configuration
Desktop v ownCloud-2.1.0.2851-nightly20151104.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.0.12","versionstring":"8.2.0","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
related #3490

**Comment by nickvergessen** [comment]
Well that is just how it is supposed to work. The desktop client can not know that.

Just combine the rule with "device type" and the client is always blocked/passed and can not check it.
Also only "Request type" is no use case.
