### ISSUE TITLE
[Sharing Link] On the option Set Expiration date you can see the date wrong (01/01/00)

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4075]
### Steps to reproduce
1. Open your ownCloud desktop client
2. Go to Open Folder "ownCloud"
3. Create a new folder, called a
4. Right click on the folder a
5. Select share with ownCloud

### Expected behaviour
You should see the day when you are

### Actual behaviour
On the option Set Expiration date you can see 01/01/00
![screen shot 2015-11-04 at 16 21 23](https://cloud.githubusercontent.com/assets/12032058/10942379/2e1ba9ce-8310-11e5-943c-fde251bb833a.png)

### Server configuration
Desktop v ownCloud-2.1.0.2851-nightly20151104.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.0.12","versionstring":"8.2.0","edition":"Enterprise"}

**Comment by dragotin** [comment]
@rullzer can you check this one? Thx..

**Comment by Dianafg76** [comment]
I tested this issue and now is working OK
Desktop v ownCloud-2.1.0.2871-nightly20151111.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

Closed

**Comment by Dianafg76** [comment]
I reopen this bug because On the option Set Expiration date you can see 01/01/00
![screen shot 2015-11-13 at 08 26 29](https://cloud.githubusercontent.com/assets/12032058/11140924/49a2a054-89e0-11e5-8cb4-0134b9949c0b.png)

Desktop v ownCloud-2.1.0.2875-nightly20151113.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
This problen is when the Shari API is disabled
![screen shot 2015-11-13 at 11 26 57](https://cloud.githubusercontent.com/assets/12032058/11143970/7fb9c988-89f9-11e5-8385-8aa14c80862a.png)

**Comment by ckamm** [comment]
@Dianafg76 That's odd, as far as I remember it should adjust the date on dialog construction. You're saying that when the sharing api is disabled, the date is wrong?

**Comment by ckamm** [comment]
Ah, no - you're right. If fetching share information failed completely the date field isn't updated.

**Comment by Dianafg76** [comment]
I tested this issue and is working OK
When you disable tha sharing API, you can see this error: "The server does not allow sharing"
![screen shot 2015-11-24 at 09 32 38](https://cloud.githubusercontent.com/assets/12032058/11361520/5a4baeda-928e-11e5-9ea9-e5977f000017.png)
