### ISSUE TITLE
Master does not compile on Qt4 for Coverity

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/client#4076]
https://travis-ci.org/owncloud/client/builds/89266620

**Comment by dragotin** [comment]
@rullzer seems to be in the new sharing code, can you check?

**Comment by rullzer** [comment]
Already fixed by @danimo in https://github.com/owncloud/client/commit/5fccc25f36ea5f990812215aa4759f459a687ce9 thanks :)

https://travis-ci.org/owncloud/client/builds/89298869
