### ISSUE TITLE
Automatic Client update - windows removes all sync folders

### ISSUE THREAD

**Issue by kaplandani** [owncloud/client#4077]
After last update (which was done automatically) the client lost all the synced folders.(2.0.2 b. 5569)
I am not sure what will happen if I add them again (I have one version on my computer and another on the server....)

**Comment by phil-davis** [comment]
Read https://github.com/owncloud/client/issues/4015 https://github.com/owncloud/client/issues/3747 and a few other issues reported about the same thing. If you have any additional questions or have an idea how we can help prevent this problem for existing installs, then comment there.

**Comment by guruz** [comment]
@kaplandani Yes, it's an unfortunate side effect of a unavoidable bug in the updater code as far as I understood it.
If you re-add them, everything should be fine.
