### ISSUE TITLE
Client 2.0.2 (build 5569), 2.1.0 (build 5569) does not sync files (upload) with server, while directory tree is synced if it does not contain any files

### ISSUE THREAD

**Issue by tps800** [owncloud/client#4078]
The client stops syncing as soon as it finds a file within the directory tree. The connection is terminated the file is not synced. All remaining items are not synced either.

Downloading files seems to work as expected. Only uploading does not work the way I'd expect it.
I am seeing this with an ownCloud server version 8.1.4 and only with windows 7/8/10.

I can upload files using the web-gui from windows.

### Steps to reproduce
1. Install OwnCloud, Configure OwnCloud, Configure LDAP access
2. Install OwnCloud Client 2.0.2 build 5569
3. Start syncing, create various directories
4. copy files into these directories

### Expected behaviour
Client syncing all: directories and files up to the server

### Actual behaviour
Client is syncing only directories, termination at the first file it finds. Before the connection terminates there is a constant amount of data transferred, then the connection is terminated by the client.

### Client configuration
**Operating system:** Ubuntu 14.04.5 LTS

**OwnCloud Client:** 2.0.2 (build 5569)

**Operating system:** Windows 7 Pro

**OwnCloud Client:** 2.0.2 (build 5569)

### Server configuration
**Operating system:** Oracle Linux 6.7

**Web server:** Apache 2.2.15-47.0.1

**Database:** PostgreSQL 9.3.10-1

**PHP version:** PHP 5.6.14-1

**redis version:** redis-2.4.10-1

**ownCloud version:** owncloud-8.1.4-12.1

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**List of activated apps:**
* Enabled:
 - activity
 - files
 - files_pdfviewer
 - files_sharing
 - files_trashbin
 - files_texteditor
 - files_versions
 - gallery
 - imprint
 - ocusagecharts
 - password_policy
 - user_ldap

* Disabled:
 - external
 - files_encryption
 - files_external
 - files_locking
 - files_videoviewer
 - firstrunwizard
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_webdavauth

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server1>.<local1>.<domain1>',
    1 => '<server2>.<local2>.<domain2>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '/owncloud',
  'secret' => '',
  'redis' => array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'proxy' => 'proxy-lb:8080',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (stable)
 * lynx (from cygwin)
 * w3m (from cygwin)
* Linux (Debian, Ubuntu 12.04/14.04/14.10, Fedora 19/20/21, Oracle Linux 6.5/7.0)
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror (stable)
 * lynx (stable)
 * w3m (stable)

#### Web server error log
```
Web server log
```

#### ownCloud log (data/owncloud.log)
```
ownCloud log
```

#### Browser log
```
Browser log
```

**Comment by guruz** [comment]
This sounds like a server configuration issue.
Try to run the Linux client with ```--logfile -``` to see some output that might help to track it down

**Comment by tps800** [comment]
The Linux Client is working. The Windows Client is not working. I've ran the Windows Client with logging. I do have three files not syncing. I can upload these files using a web-browser. I can copy those files to an other Windows System -- they wont sync there too. I can copy those files to a Linux System and they WILL sync from this system up to the server.

Windows 7,8.x: client does not sync these files.
Linux: client does sync these files (sometimes).

Since the log is 43MiB in size, I cant attach it.
Since the files in question are 90MiB, 80MiB and 1KiB in size, I could only attach the last one. I've decided to upload them to the server USING A BROWSER. Since this works. I'd like to send you the link to the log and files via eMail (don't like the idea a whole lot of people having access to this link, downloading these files).

**Comment by tps800** [comment]
Since a lot people migrated now to 2.0.2 clients on windows. I've seeing a wide variety of files terminating server connections. Some are quite small, some are quite large. Some files hold utf-8 characters, some do not. But in all cases: its all times the same file or set of files. You may wipe them from the client then all is OK again. Copying them again into the synced tree -- they'll stop syncing again: terminated connection on these files. Moving these files from one client to an other may make them sync! You may even get them synced by removing all informations including the synced directory tree, then copying all files in again, installing the client and start syncing. In most cases the files will then upload.

**Comment by tps800** [comment]
Same with 2.1.0.5632-nightly. And 2.1.0

**Comment by tps800** [comment]
Same with 2.2.0.5635-nightly.

**Comment by danimo** [comment]
@tps800 2.2 is master, which is currently identical to (or behind) 2.1 branch.

**Comment by RaghdaMorsy** [comment]
My windows client does not sync too , after the latest update :(

**Comment by tps800** [comment]
Since I moved on hoping the newer version would solve issues:

### Client configuration
**Operating system:** Ubuntu 14.04.5 LTS

**OwnCloud Client:** 2.1.0-1 (build 5569)

**Operating system:** Windows 7 Pro

**OwnCloud Client:** 2.1.0 (build 5683)

**Operating system:** Windows 10 Pro

**OwnCloud Client:** 2.1.0 (build 5683)

### Server configuration
**Operating system:** Oracle Linux 6.7

**Web server:** Apache 2.2.15-47.0.1

**Database:** PostgreSQL 9.3.10-1

**PHP version:** PHP 5.6.16-1

**redis version:** redis-2.4.10-1

**ownCloud version:** owncloud-8.2.1-1.1

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**List of activated apps:**
* Enabled:
 - activity
 - files
 - files_pdfviewer
 - files_sharing
 - files_trashbin
 - files_texteditor
 - files_versions
 - gallery
 - imprint
 - ocusagecharts
 - password_policy
 - user_ldap

* Disabled:
 - external
 - files_encryption
 - files_external
 - files_locking
 - files_videoviewer
 - firstrunwizard
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_webdavauth

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server1>.<local1>.<domain1>',
    1 => '<server2>.<local2>.<domain2>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '/owncloud',
  'secret' => '',
  'redis' => array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'proxy' => 'proxy-lb:8080',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (stable)
 * lynx (from cygwin)
 * w3m (from cygwin)
* Linux (Debian, Ubuntu 12.04/14.04/14.10, Fedora 19/20/21, Oracle Linux 6.5/7.0)
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror (stable)
 * lynx (stable)
 * w3m (stable)

**Comment by tps800** [comment]
Both clients fail after syncing some files. The failour is permanent: without user interaction no further syncs are tried. In all cases the client terminates the connection.

**Comment by guruz** [comment]
What is the error message in the UI?

My e-mail is My username here @owncloud.com :)

Is there anything obvious in the server's error.log or owncloud.log?

**Comment by ogoffart** [comment]
And does the client report an error?  What is the error that is shown?  (the log files should contain such information)

**Comment by ogoffart** [comment]
This sounds like a configuration problem rather than a bug in the client.  Please ask for help on the forums or support channel: https://owncloud.org/support/
