### ISSUE TITLE
Bandwidth setting "limit automatically" ineffective with small files

### ISSUE THREAD

**Issue by cloo** [owncloud/client#4081]
When uploading lots of small files with bandwidth setting "limit automatically", uploading becomes unreasonably slow.

To describe the difference, with this setting off, about 10 similar files are uplaoded per second (10-50 kb in size), and with this setting on - it takes one to two seconds per file.

Maybe available bandwidth is measured after each individual file and happens way too often - or something like that.

**Comment by guruz** [comment]
@cloo Besides bandwidth measuring/limiting, the parallelism is going down from 3 to 1 parallel request. For small files, the network latency and ownCloud server per-request slowness will decide on your speed.

Which server version do you use?

**Comment by cloo** [comment]
I'm using server version 8.2.

**Comment by guruz** [comment]
Please note that vanilla 8.2 has some performance regressions, especially if you don't use the Redis locking. The update will fix this.

https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_transactional.html
https://github.com/owncloud/core/issues/19888#issuecomment-153696788 (and others)

**Comment by guruz** [comment]
@cloo btw, have you tried meanwhile with a newer server and the redis locking?

**Comment by hodyroff** [comment]
No answer in regards of newer version of the server and redis. Closing for now.
