### ISSUE TITLE
[OS X] Force re-sync after error

### ISSUE THREAD

**Issue by sbliven** [owncloud/client#4084]
After a connection error there is no easy way to tell the client to restart syncing. For instance, sync is disabled by SSL handshake errors (e.g. after connecting to a public wifi network which requires login). The client stays in the red-X error state until either the client is restarted or syncing is manually paused and then restarted from settings.

I would like to see a menu option or button in the account settings to force re-syncing with the server after an error.

### Client configuration
Client version: Version 2.0.2 (build 2818)

Operating system: Mac OSX

**Comment by guruz** [comment]
(Tested 2.0.2 release) For me on 10.9 it reconnects nicely if I turn off the WiFi for some minutes, all accounts disconnect, then I reconnect the WiFi and the client reconnects.
How long did you wait?

Maybe I should somehow test a captife portal (SSL handshake errors)

**Comment by sbliven** [comment]
@guruz I'll pay more attention to the timing of the problem next time it happens, but I have the feeling that it didn't recover on its own, even after logging in to the captive portal. I didn't try turning off wifi, but that also seems like a poor workaround.

**Comment by guruz** [comment]
(Very possibly caused by same cause as https://github.com/owncloud/client/issues/4097 let's wait the test result there and bring the OS X Qt with that patches too )

**Comment by guruz** [comment]
Could you try http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.2884-nightly20151116.pkg please ?

**Comment by guruz** [comment]
Sorry, ignore that. Will create a new build soon.

**Comment by guruz** [comment]
http://download.owncloud.com/desktop/daily/ownCloud-2.0.2.2885-nightly20151116.pkg
Could you please try? :)

**Comment by guruz** [comment]
2.1 beta1 is out:
https://owncloud.org/install/#testing-development

**Comment by sbliven** [comment]
@guruz I'm trying out beta1 now, and I should be able to reproduce the problem during my commute tomorrow.

I did want to mention that in 2.0.2, turning wifi off and on doesn't fix the problem. The error simply changes to 'Host ... not found' and then back to 'SSL handshake failed'. Restarting the client successfully connects. Part of the problem might be that my server uses a self-signed cert, although that is ignored for normal operation.

I'll report back with the beta1 results.

**Comment by guruz** [comment]
@sbliven We have even better code (I think) with latest nightly of 2.1:
http://download.owncloud.com/desktop/daily/testpilotcloud-2.1.0.2906-nightly20151124.pkg

**Comment by guruz** [comment]
Sorry, I meant:
http://download.owncloud.com/desktop/daily/ownCloud-2.1.0.2905-nightly20151124.pkg

**Comment by guruz** [comment]
@sbliven Any news from you?

@dragotin removing gold status..

**Comment by guruz** [comment]
@sbliven Have you tried 2.1rc1 or the nightly I sent?

**Comment by sbliven** [comment]
@guruz Yes, I have tried it and it correctly syncs after a few seconds. Fixed!
