### ISSUE TITLE
Client Logfile (Window) on Mac

### ISSUE THREAD

**Issue by thetrial** [owncloud/client#4085]
I would suggest, that there is a dedicated button in the client to open a logwindow. F12 usually defaults to Exposé on most (?) Mac systems. Or, at least there should be a possibility to make an own shortcut. Usually one can create shortcuts per application via OSX system preferences, but due to the Client app does not have an own menue, this does not work.

As an alternative I would (symbolic) link the main log to where logfiles usually ar located on a Mac system to read it via the console. But I have not understand if there is a main log per default or not.

For now I have to quit the client so I can start it via cli. To restart a running instance (as mentioned) does not work here. It would be nice to make it possible to acces a main log. And if this does not exist, maybe to –once– adjust that, so it gets created. Maybe via ini/pref-file.

Another idea would be to integrate to log window itself into the client, maybe?

**Comment by dragotin** [comment]
The logfile that we currently have is not useful for anything else than debugging the sync core algorithm. That is the reason why we do not want it to expose to users.

Please contribute to #3518
