### ISSUE TITLE
Add option to disable update notification

### ISSUE THREAD

**Issue by morxa** [owncloud/client#4087]
Starting with owncloud client 2.0.1, the owncloud client shows a notification if a more recent version exists. It should be possible to disable the notification. On most Linux distributions, the client is updated by the package manager, and people generally don't build their own package just because there is a more recent upstream release.

### Expected behaviour
As an example, Fedora 22 currently ships owncloud client 2.0.1. Every time I log in, a notification is shown which states that a more recent version is available. I do not intend to build the package myself and therefore would like to disable the notification.

### Actual behaviour
I cannot disable the update notification.

**Comment by danimo** [comment]
We recommend that distros do not package the client themselves, as it will be outdated in no time. If they still do it, they should provide the latest version.

**Comment by RealRancor** [comment]
@morxa Have you tried https://doc.owncloud.org/desktop/2.0/autoupdate.html#preventing-automatic-updates-in-linux-environments ?

**Comment by morxa** [comment]
@RealRancor thanks, that's what I was looking for.
