### ISSUE TITLE
Can't Compile Client-1.7 on windows7 :Cmake Error:package Neon not found .

### ISSUE THREAD

**Issue by kongxiaowang** [owncloud/client#4089]
E:\ownCloud study\owncloud development build\client-build>cmake -G "MinGW Makefi
les" ../client-1.7
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: E:/QT_MinGW_build_location/Tools/mingw492_32/bi
n/gcc.exe
-- Check for working C compiler: E:/QT_MinGW_build_location/Tools/mingw492_32/bi
n/gcc.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: E:/QT_MinGW_build_location/Tools/mingw492_32/
bin/g++.exe
-- Check for working CXX compiler: E:/QT_MinGW_build_location/Tools/mingw492_32/
bin/g++.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found Qt5 core, checking for further dependencies...
-- Using Qt 5!
-- Found PkgConfig: E:/QT_MinGW_build_location/Tools/mingw492_32/bin/pkg-config.
exe (found version "0.23")
-- Checking for module 'neon'
--   Package 'neon' not found
CMake Error at E:/ownCloud study/owncloud development build/cmake/cmake build lo
cation/CMake/share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:148 (me
ssage):
  Could NOT find Neon (missing: NEON_LIBRARIES NEON_INCLUDE_DIRS)
Call Stack (most recent call first):
  E:/ownCloud study/owncloud development build/cmake/cmake build location/CMake/
share/cmake-3.4/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_
MESSAGE)
  cmake/modules/FindNeon.cmake:43 (find_package_handle_standard_args)
  CMakeLists.txt:110 (find_package)

-- Configuring incomplete, errors occurred!
See also "E:/ownCloud study/owncloud development build/client-build/CMakeFiles/C
MakeOutput.log".
-------------------I'm a Chinese student, I try to compile client-1.7 on windows7 , and  I don't know how to configure the package 'Neon' on Windows7,I will be appreciate it if someone can help me,thank you!

**Comment by RealRancor** [comment]
@kongxiaowang Questions like this are better placed at https://mailman.owncloud.org/mailman/listinfo/devel. The issue tracker here is used for reporting bugs and feature requests.

Please also note that you're trying to compile an ountdated and unsupported version of the sync client.

**Comment by danimo** [comment]
Please use the latest tar ball to compile (which is 2.0.2), and closely follow https://doc.owncloud.org/desktop/2.0/building.html.
