### ISSUE TITLE
Change default option for delete all files dialogue box to "Keep files"

### ISSUE THREAD

**Issue by davidjericho** [owncloud/client#4091]
This may be related to #1408, but it's not strictly a duplicate as far as I can tell. The discussion in #1408 is sensible, but it doesn't address the UX of the default option.

The default order for the remove all files dialogue in Folder::slotAboutToRemoveAllFiles() is to remove all local files. I suggest it should be "Keep files" to prevent accidental deletion. 

We've had numerous cases of users typing documents, the pop up appears on a shared folder sync, the window appearing over the top of the current application. Without realising, the user has pressed Enter, selected the default and purged their local copy of data none-the-wiser until their network link becomes congested with a resync, or a they look for a file. 

There are cases when this has occurred despite the upstream server being problem free. Man-In-The-Middle SSL inspection or other network middle-boxes have caused this, as an example.

**Comment by guruz** [comment]
Are you on Windows?
If yes this was probably fixed as #3824 bd39c64798426180cf22055325dafc3deb5d4f45

You can try to test this with a daily build: http://download.owncloud.com/desktop/daily/

**Comment by davidjericho** [comment]
Thanks @guruz , yes, it appears to be the same issue. I didn't find that when searching. 

Consider this fixed, and a duplicate.
