### ISSUE TITLE
Problem With Space Characters in Folders

### ISSUE THREAD

**Issue by adrianconde** [owncloud/client#4092]
Hello, I've an issue that i can't resolve it.
When my folders inn ftp external storage does have a spave character, the content inside of it will be allways empty with the message "No files in here" . And when the same folder I replace the spae character with an "_" all goes to work fine. When i connect directly to the ftp folder using an FTp client the files where show perfectly but in owncloud (web, pc sync,....) nothin on it.

Anybody coult help me please?

**Comment by RealRancor** [comment]
@adrianconde Please fill out the issue template:

https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

as asked in the "guidelines for contributing" (linked in the yellow box when creating a new issue).

**Comment by ogoffart** [comment]
This looks like an issue on the server side anyway, not a bug in the client. (this is the client's bug tracker)
(Syncing files with space is workinf 

You can get help in the owncloud forums checkout https://owncloud.org/support/
