### ISSUE TITLE
Naming conflicted version of files can be confusing

### ISSUE THREAD

**Issue by KRens** [owncloud/client#4095]
Hi,

What happened?
I yesterday noticed the owncloud icon on Windows 10 client was grayed out.
I opened the settings page and I noticed that under accounts my account could not be accessed (even though I haven't changed any credentials or url, it's local network).
I didn't have a retry button, the only thing I could do was remove my owncloud account.

I then added the same again with exactly the same credentials, it asked me whether I wanted to KEEP my local data, which I selected.
It then started synching.
Now this morning I noticed a lot of files have been reverted to the old version that was stored in owncloud, instead of the newer versions on my computer.

Owncloud did not keep my local, newer, files, but overwrote them with the old one.
I again lost everything, but this time my disk recovery tool cannot retreive the previous version :(
Now I am totally screwed.

Update:  owncloud just renamed the old files to "conflicted".
Nothing is lost.

Just fyi: First time:
https://github.com/owncloud/client/issues/3824
I managed to recover most of the files, but several of them are damaged and cannot be opened.
Half my disk is now filled with damaged flles and no way to know which ones to clean them up...

**Comment by ogoffart** [comment]
I believe in this case, there should have been conflict files created with your changes.  Was there not conflict files?

As for the gray icon, was it a real error or a temporary error?  We do network test every 30 seconds to check that it is online. Was resterting the owncloud client not helping?

**Comment by KRens** [comment]
Hi,

1) I did not try restarting the owncloud client, I should have tried that.
I really recommend to put a retry button.
Then I would have tried that first.

2) You are my hero.
I found conflict files.

However: they are named:
filename_conflict-20151021-233529
I would expect the filename to be the date of yesterday or at least the last changed date.
Now I did not look at the conflict file as it seemed like a very old version.
Using the correct date of the conflict file might help.

3) I also recommend informing the user better if a conflict file is created.
Now I did not knew and I wouldn't have bothered you ;-)

So pfieuw, I have the most important files back.
Thank you.

**Comment by dragotin** [comment]
@KRens sorry for the shock you had to go through. Even though I very much feel with you, and feel sorry, I have to tell you that this completely correct and documented behaviour. ownCloud syncs the server version of the file into your home dir, and moves your local changes aside as a conflict file. That is by convention, there are already issues asking to change this behaviour.

Glad that nothing serious happened after all, may I ask you to be so kind to change the subject of this issue report to something not so much catastrophic? Thanks :-)

**Comment by KRens** [comment]
Thank you, renamed.
