### ISSUE TITLE
Tray icon tooltip uses internal folder 'alias' instead of something more user friendly

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#4096]
The popup message on the tray icon tells me that on both sync folders the sync succeeded.
It mentions Ordner ownCloud and Ordner ownCloud1. but I use the folders ownCloud and fablab-oc
as sync folders. The activity window show the correct name.
![bildschirmfoto vom 2015-11-09 18 29 49](https://cloud.githubusercontent.com/assets/1108546/11041192/9db0c63a-8710-11e5-984e-98934e622c9f.png)

**Comment by ckamm** [comment]
It now uses `aliasGui()`, which is the local filesystem folder name (if unique).

**Comment by Dianafg76** [comment]
I tested this issue on Windows 2008 and is workin OK 
Desktop v ownCloud-2.1.0.2875-nightly20151113.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

Closed
