### ISSUE TITLE
Syncing sub directory of sync folder to different server than parent directory

### ISSUE THREAD

**Issue by lazyfrosch** [owncloud/client#4101]
I have a question regard multi instance handling in the later version of the client.

I want to have a sync situation like this:
- owncloud.company.com
  - local: $HOME/Documents/COMPANY
  - remote: Documents
- cloud.myself.com
  - local: $HOME/Documents
  - remote: Documents

The idea is to sync/backup the same data with two ownCloud instances, currently I'm still doing this with two locally running clients, one for each server.

I never had problems, since the state files are excluded by the client that sync the parent folder.

The error "The local folder %1 is already contained in a folder used in a folder sync connection." is blocking me, and I'm not sure why this error is required.

Of course, it will cause problems to sync the same folder, but sub-folders should work fine.

Your thoughts on this:question:

**Comment by phil-davis** [comment]
From a sync database point of view, that should work OK. And if the upstream ownCloud servers are different then there will be no "double parallel sync" of the same file to the same place.
I wonder what the file watcher behavior is? When the operating system file watcher API notifies ownCloud client that a file in subdir has changed, will ownCloud client be able to realise that the file is contained in multiple folder sync connections for multiple accounts? Or will a sync be triggered to the first account folder sync connection it matches and the other "forgotten" until there is some other reason for it to do a full scan?

**Comment by guruz** [comment]
I think this issue is quite exotic, we're not planning on supporting this.
I'll leave it open as a discussion point though..

**Comment by lazyfrosch** [comment]
So basically the problem you see is how the client handles file watches, to trigger the actual synching of the directory?

TBH, that should be easy to fix. I could have a look onto it, when there is interest of accepting such a change.

**Comment by guruz** [comment]
Note that there are 2-3 file watcher implementations (Windows, Linux, OS X) that behave differently.
So if you suddenly change the relation (each dir belongs to exactly one configured folder) code might get more complicated.

**Comment by lazyfrosch** [comment]
@guruz ok

**Comment by TheOneRing** [comment]
Not planned
