### ISSUE TITLE
Spurious uploads when hidden files are synced again

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#4103]
In #4023 @raimund-schluessler wrote

> When I enable "Sync hidden files" again, all hidden files are uploaded again, although nothing has 
> changed during the period when they where not synced. @ckamm Is this an expected behavior?

This is a tricky situation since the local database has no information on these files. But I think since local and remote discovery should *both* see these files, our existing 'what if the db is deleted' code should resolve these conflicts without a new upload when size and mtime agree.

**Comment by raimund-schluessler** [comment]
> But I think since local and remote discovery should both see these files, our existing 'what if the db is deleted' code should resolve these conflicts without a new upload when size and mtime agree.

This would be the best solution, I guess.

**Comment by phil-davis** [comment]
A fix for this could also help people who "seed" their client-side folders with stuff that is already on the server and then startup/resume the client. A file that appears "new' on the client side does not have to be assumed to be new to the server and uploaded - the server might already have it.

**Comment by ckamm** [comment]
@raimund-schluessler @phil-davis Can you reproduce this behavior? I tried it on linux with the current 2.1 branch and I don't get any spurious uploads when I go from "don't sync hidden files" to "sync hidden files". The client correctly figures out that server and client already have the same data.

**Comment by ogoffart** [comment]
A log would be usefull but normaly the client resolve the conflict automatically if the size and mtime of the file are the same on the server and the client. (which should be the case here)

**Comment by ckamm** [comment]
Feel free to reopen this issue if the problem still exists in 2.1.
