### ISSUE TITLE
[Kubuntu] [Qt 4.8.6] Hide on system startup

### ISSUE THREAD

**Issue by pascalBokBok** [owncloud/client#4104]
I'm using the option "Launch on System Startup". That's great, but I don't want to see the owncloud window every time I start my computer - I just wan't it to sync the files in the background. Can we add a "Don't show window on system startup" or can it see that it has been started as a part of the startup procedure?

**Comment by guruz** [comment]
You always submit issues without any information about the version or distro you are using. Please add this information.

**Comment by pascalBokBok** [comment]
@guruz It's a feature request - why do you need to know this information?
Owncloud 8.1.3 with Owncloud client 2.0.2 on Kubuntu 14.04.3 LTS
Built from Git revision 78d782 on Oct 30 2015, 11:49:18 using Qt 4.8.6, OpenSSL 1.0.1f 6 Jan 2014

**Comment by guruz** [comment]
@pascalBokBok No, it's a bug which was supposed to be fixed via e1c634d000271a0a1c64a51596edeba784be9829 and previous issues.

However you could try the workaround that @cruessler described in https://github.com/owncloud/client/issues/3273#issuecomment-152814708 and following and tell us if that fixes it for you.

**Comment by guruz** [comment]
From the other issue https://github.com/owncloud/client/issues/3273#issuecomment-152814708:

> On a second machine that is already at Qt 5.4, the issue is not present.

FYI @dragotin @jnweiger https://github.com/owncloud/client/issues/2558

**Comment by guruz** [comment]
Please try with a newer Qt

Dup of https://github.com/owncloud/client/issues/3273

**Comment by pascalBokBok** [comment]
If you mean that I should install some extra software, then what about the other million users using Kubuntu 14.04? (including a lot of my family and friends)
I don't understand #3273 - will there be a fix out that works with Kubuntu 14.04 version of QT?
