### ISSUE TITLE
Add support for parallel downloading from multiple hostnames

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/client#4105]
This is not an issue, it is a feature request. It would be very nice if we could  setup owncloud client to do parallel download from different hostnames. Let me explain one use case.
Lets say i have 3 10MBps uplinks, which point to the same owncloud server, right now i am limited to at most 10Mbps download sync speed in the client. If i could say owncloud client  to use 3 different hostnames during sync, i could achieve close to 30Mbps sync speed.

**Comment by jsalatiel** [comment]
Maybe the owncloud-core itself could return a header containing the alternative hostnames.

**Comment by guruz** [comment]
For uploads for a single file (because we upload chunks in parallel) we might support that if you can make your DNS return a random IP. 

For downloads we can balance the same way only for different files.

**Comment by jsalatiel** [comment]
For each file is there a dns query ?
It would be nice if we could also manually add different hostnames. There are cases where configure the same dns for multiple IPs is not an option. 
Anyway, thanks !

**Comment by danimo** [comment]
Sorry, this is too rare a use case and will probably never get implemented.
