### ISSUE TITLE
When the update is finished , I get the following error: "Failed to connect to ownCloud at https:/.... Network access is disabled" for Windows 2008 and Windows 10

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4112]
### Steps to reproduce
1. New installation or upgrade of these two versions (ownCloud-2.1.0.5618-nightly20151111-setup.exe and ownCloud-2.1.0.5615-nightly20151110-setup.exe)

### Expected behaviour
It should be updated without problem

### Actual behaviour
When the update is finished , I get the following error: "Failed to connect to ownCloud at https:/.... Network access is disabled" 
### Server configuration
Desktop v ownCloud-2.1.0.5618-nightly20151111-setup.exe and ownCloud-2.1.0.5615-nightly20151110-setup.exe for Windows 2008 Entreprise, and Windows 10

**Comment by Dianafg76** [comment]
![screen shot 2015-11-11 at 13 57 17](https://cloud.githubusercontent.com/assets/12032058/11091581/3b9adcac-887c-11e5-9ed1-3f884286ae9e.png)

**Comment by guruz** [comment]
Yes, this is currently broken. This build should work: http://download.owncloud.com/desktop/daily/ownCloud-2.1.0.5619-nightly20151111-setup.exe

**Comment by Dianafg76** [comment]
I tested this issue and is working ok
Desktop v ownCloud-2.1.0.5619-nightly20151111-setup.exe

Closed
