### ISSUE TITLE
Write fails on shares if quota exceeded 

### ISSUE THREAD

**Issue by felixboehm** [owncloud/client#4114]
### Expected behaviour
Should be possible to edit / write to a file shared with me.
Even if my quota is exceeded.
Works in web, not in Client. 

### Actual behaviour
Client doesn't sync file and throw error:
```
Error downloading http://champ.local/ownClouds/demo-enterprise-8.1.3/remote.php/webdav/new.txt - server replied: Insufficient Storage
```
### Steps to reproduce
1. Users: admin (quota unlimited), guest (quota 0B)
2. admin shares file new.txt with user guest, permissions for edit / write
3. user guest: edit new.txt in web --> Works
4. user guest: sync files, and edit new.txt on local system --> Client: "Insufficient Storage"

### Server configuration
Web server: apache
Database: mysql
PHP version: 5.4
ownCloud version: 8.1.3

### Client configuration
Client version:  2.0.2 (build 2818)
Operating system: mac
OS language: de

### Logs

Client log: https://gist.github.com/felixboehm/8e9a5e6f5619549a6fc3

Server Log: 
```
{"reqId":"pSWC1Ov679LQJKJdw/kq","remoteAddr":"192.168.78.1","app":"PHP","message":"Undefined index: user-time at /Users/felix/Sites/ownCloud/deployment/systems/demo-enterprise-8.1.3/apps/firewall/rules/regex.php#64","level":3,"time":"2015-11-11T15:08:15+00:00","method":"PUT","url":"/ownClouds/demo-enterprise-8.1.3/remote.php/webdav/new.txt"}
{"reqId":"pSWC1Ov679LQJKJdw/kq","remoteAddr":"192.168.78.1","app":"webdav","message":"Exception: {
        "Message":"HTTP\/1.1 507 Insufficient Storage",
        "Code":0,
        "Trace":"
                #0 [internal function]: OC\\Connector\\Sabre\\QuotaPlugin->checkQuota('new.txt', Object(OC\\Connector\\Sabre\\File), Resource id #297, false)\n
                #1 \/Sites\/ownCloud\/demo-enterprise-8.1.3\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
                #2 \/Sites\/ownCloud\/demo-enterprise-8.1.3\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1085): Sabre\\Event\\EventEmitter->emit('beforeWriteCont...', Array)\n
                #3 \/Sites\/ownCloud\/demo-enterprise-8.1.3\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(501): Sabre\\DAV\\Server->updateFile('new.txt', Resource id #297, NULL)\n
                #4 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
                #5 \/Sites\/ownCloud\/demo-enterprise-8.1.3\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n
                #6 \/Sites\/ownCloud\/demo-enterprise-8.1.3\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n
                #7 \/Sites\/ownCloud\/demo-enterprise-8.1.3\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n
                #8 \/Sites\/ownCloud\/demo-enterprise-8.1.3\/apps\/files\/appinfo\/remote.php(83): Sabre\\DAV\\Server->exec()\n
                #9 \/Sites\/ownCloud\/demo-enterprise-8.1.3\/remote.php(132): require_once('\/Users\/felix\/Si...')\n
                #10 {main}","File":"\/Sites\/ownCloud\/demo-enterprise-8.1.3\/lib\/private\/connector\/sabre\/quotaplugin.php","Line":108}",
        "level":4,
        "time":"2015-11-11T15:08:15+00:00",
        "method":"PUT",
        "url":"/ownClouds/demo-enterprise-8.1.3/remote.php/webdav/new.txt"}
```

**Comment by felixboehm** [comment]
@danimo

**Comment by dragotin** [comment]
@felixboehm that is clearly a server bug. I thought the client does a calculation before uploading?

**Comment by danimo** [comment]
>        "Message":"HTTP\/1.1 507 Insufficient Storage",

Server bug?!

**Comment by ogoffart** [comment]
We don't do calculation before uploading.

2.1 will do a calculation before downloadig checking that we don't fill the harddrive. (thanks @ckamm )  
But we don't do the same while uploading.

**Comment by danimo** [comment]
@PVince81 pls

**Comment by PVince81** [comment]
@felixboehm can you confirm that your user has an explicit quota set ?

There is a difference between reaching the quota and having the actual disk space running out.

In the case of quota, uploading the file will create a part file before doing the overwrite, but that one should not count in the quota.

However if the disk space (not quota) is really running low, then it can happen that there is no more space left for the part file (and chunk files).

**Comment by felixboehm** [comment]
I have set the quota to 0B.

**Comment by ogoffart** [comment]
So 0B means nothing can be added?

**Comment by felixboehm** [comment]
A 0B quota means, I can create 0B files and folders.
I can't write content to a file.

**Comment by ogoffart** [comment]
So then the client behave as expected,  right?  There is no bug

**Comment by phil-davis** [comment]
If user1 has 0 quota on the server (or has used up their quota on the server) then they should still be able to write to a file (or folder) shared with them by another user2. That file (or folder) uses quota of user2. The upload should only fail if user2 as run out of quota.
The OP is reporting that it fails when user1 has run out of quota.
I will try with my server/client and replicate...

**Comment by felixboehm** [comment]
@MorrisJobke

**Comment by MorrisJobke** [comment]
server: current master, client 2.0.2

* having two users "userA" (no quota) and "userB" (0 Byte quota)
* share folder "abc" from "userA" to "userB"
* userB cannot update "welcome.txt" in it's root, but userB can upload stuff to "abc" (received share from userA) - this works in the web UI and in the client (uploading abc/testfile.txt succeeded and welcome.txt failed)

![bildschirmfoto 2015-11-23 um 15 08 48](https://cloud.githubusercontent.com/assets/245432/11338487/b4aa03d0-91f4-11e5-884b-15f8c100984b.png)

I will retry with older server versions.

**Comment by MorrisJobke** [comment]
Ah. I just realized that this is for a file share and not for a folder share.

I just checked and my steps above also work on stable8.1.

**Comment by MorrisJobke** [comment]
Clearly a server issue -> migrated to https://github.com/owncloud/core/issues/20686
