### ISSUE TITLE
Package Ubuntu 14.04 Size mismatch

### ISSUE THREAD

**Issue by ungenannter** [owncloud/client#4115]
### Expected behaviour
the package should upgrade

### Actual behaviour
the package does not upgrade

### Steps to reproduce
install updates: apt-get upgrade 

### Client configuration
Client Proxy: with cache for packages

Operating system: Ubuntu 14.04

### Logs

>E: Failed to fetch http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/./amd64/owncloud-client_2.0.2-3_amd64.deb  Size mismatch

**Comment by jnweiger** [comment]
A size mismatch may happen any time when a new build gets pubished there. 
That probably was a rebuild without incrementing the build release number. It should be 2.0.2-4 by now.

**Comment by ungenannter** [comment]
addition: "it happened 2 or 3 times by now"

**Comment by dragotin** [comment]
Yes, we need to increment the build number manually. That is error prone, but only happens on exceptions.
