### ISSUE TITLE
[Discovery] Immediatly poll ETag again after we have downloaded some changes because more might be waiting

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#4116]
After changes have been synced FROM the server I suggest to do a poll for remote changes immediately afterwards. Because the chance is high that new updates are waiting on the server already. For example, consider a case when someone uploads many files and the other client downloads them. 

So the idea is to do remote one update check immediately after a sync loop was finished IF there were remote changes. If there were no remote changes then go into the wait-30-seconds cycle as usual.

**Comment by ckamm** [comment]
Good idea!

**Comment by guruz** [comment]
@moscicki  Did you manage to test this?

**Comment by moscicki** [comment]
@giorgosalex could you please have a look and test this?

**Comment by giorgosalex** [comment]
Sure. I'll check tomorrow.
Which client version should i install to check this?

**Comment by guruz** [comment]
2.4.0 rc1 will be out by tomorrow :)

**Comment by guruz** [comment]
https://owncloud.org/changelog/desktop/

**Comment by giorgosalex** [comment]
Tested it and it seems to work fine! After sync client finish, it restarts immediately if there are new files waiting to be updated.

**Comment by guruz** [comment]
Great!
