### ISSUE TITLE
Do parallel local and remote discovery at the same time

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#4117]
One could consider to ask for remote and local changes at the same time -- these two actions do not need to happen in sequence. Or maybe it already is done like that?

**Comment by ckamm** [comment]
Absolutely. We discussed this when talking about speeding up the discovery phase and agree that it makes a lot of sense to do remote and local discovery in parallel.

Ideally we could trust our file watchers enough to run the local discovery - the slowest part if the sync folder is big - only once per sync client lifetime.

**Comment by guruz** [comment]
This came up also in @ogoffart 's https://github.com/owncloud/client/wiki/New-Discovery-Reconcile-Algorithm

**Comment by ogoffart** [comment]
Done in 2.6

**Comment by guruz** [comment]
\o.
