### ISSUE TITLE
Discuss 2FA, tokens and alternernative authentication schemes

### ISSUE THREAD

**Issue by danimo** [owncloud/client#4118]
Right now, we support authentication through HTTP Basic Authentication and Shibboleth only. Both authentication schemes require adjustments throughout the entire client which increases efforts when it comes to new auth schemes: HTTP Basic Auth uses a header, while shibboleth works through cookies and occasional redirects. Other authentication schemes will have similar quirks.

Now it so happens that we need to come to terms on how we want to integrate the clients into new authentication schemes to be supported by the server, as outlined by PR https://github.com/owncloud/core/pull/19752. The main issue I see is that every authentication scheme will be a bit different, and each of them will have subtle side effects on the sync engine. We've seen that in the past with Shibboleth, which required an unproportional increase in our QA efforts.

So we should find a solution that separates the authentication schemes completely separate from the sync logic. There is a good solution to the problem, which requires a change in semantics of the sync client: Instead of considering it yet anther active frontend which requires constant authentication, we should treat it for what it is: a background service. So how about supporting new authentication schemes via tokens only? This basically kills two birds with one stone: We get the semantics right, and a good abstraction.

This is what the workflow would be lile:
1. (As part of the client setup procedure) the user logs in on once with specific authentication scheme. This needs to be adjusted depending on the authentication we support.
2. owncloud server assigns token, and remembers token in token db (possibly along with an optional client ID)
3. (and henceforth after the inital setup) Client only authenticates through the token that it received from the server.

/cc @MTRichards

**Comment by MTRichards** [comment]
@karlitschek @LukasReschke possibly to make the most out a plugable server side auth mechanism?

**Comment by karlitschek** [comment]
thanks guys. just to be clear. we are overloaded with  9.0 features already. so not yet clear if we find the time to do something herein the nearterm.

**Comment by ogoffart** [comment]
We have support for Oauth2 now

**Comment by michaelstingl** [comment]
2FA works perfectly fine with OAuth 2.0
