### ISSUE TITLE
[Share with users, groups] The folder name is not aligned with the folder

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4119]
### Steps to reproduce
1. Install the Desktop v 2.1.0 with user1
2. Open your ownCloud desktop client
3. Go to Open Folder "ownCloud"
4. Create a new folder, called aaa
5. Right click on the folder aaa
6. Select share with ownCloud

### Actual behaviour
The folder name is not aligned with the folder

![screen shot 2015-11-12 at 08 47 41](https://cloud.githubusercontent.com/assets/12032058/11113101/21158168-891a-11e5-95c3-65141ff007c8.png)

### Server configuration
Desktop v ownCloud-2.1.0.2871-nightly20151111.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
related with #3737

**Comment by guruz** [comment]
I think it's on purpose because the names can be quite long?

@rullzer @jancborchardt

**Comment by jancborchardt** [comment]
No, that’s not on purpose. The reason is that a path can be below it. However I agree (and reported it in the past) that if the folder or file is in the root, the name should be vertically centered. Also, do not bold it please. :)

**Comment by Dianafg76** [comment]
I tested this issue, and now the folder name is aligned with the folder
![screen shot 2015-11-25 at 09 11 38](https://cloud.githubusercontent.com/assets/12032058/11391695/adb443f4-9354-11e5-9189-5e82ef014713.png)

Desktop v ownCloud-2.1.0.2907-nightly20151125.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

Closed

**Comment by jancborchardt** [comment]
Thank you @ckamm!
