### ISSUE TITLE
[Share with users, groups] You must click Search to find all users that begin with the letter d, it is not automatic

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4120]
### Steps to reproduce
1. Install the Desktop v 2.1.0 with user1
2. Open your ownCloud desktop client
3. Go to Open Folder "ownCloud"
4. Create a new folder, called aaa
5. Right click on the folder aaa
6. Select share with ownCloud
7. Introduce the first letter for the user to share (e.g. d)

### Expected behaviour
When you introduce one letter (e.g. d) All users start with the same letter should appear automatically

### Actual behaviour
You must click Search to find all users that begin with the letter d, it is not automatic

### Server configuration
Desktop v ownCloud-2.1.0.2871-nightly20151111.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
related with #3737

**Comment by ogoffart** [comment]
Fixed in commit 0d21503ee59dcf8fdd91bdfac4ddec9835d49ce9

**Comment by Dianafg76** [comment]
I tested this issue and is working OK
Desktop v ownCloud-2.1.0.5630-nightly20151117-setup.exe on WINDOWS
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}
