### ISSUE TITLE
[Share with users, groups] The option that is next to the username is unintuitive

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4121]
### Steps to reproduce
1. Install the Desktop v 2.1.0 with user1
2. Open your ownCloud desktop client
3. Go to Open Folder "ownCloud"
4. Create a new folder, called aaa
5. Right click on the folder aaa
6. Select share with ownCloud
7. Write the name of the user to share
8. Click on Search
9. Select the option that is next to the username
![screen shot 2015-11-12 at 09 42 39](https://cloud.githubusercontent.com/assets/12032058/11114037/cf28ce16-8921-11e5-8b9e-96c6c633b5ef.png)

### Expected behaviour
This option is for Unshare users, groups but is unintuitive

### Actual behaviour
Desapear the Permissions Option

![screen shot 2015-11-12 at 09 22 09](https://cloud.githubusercontent.com/assets/12032058/11113710/478778ec-891f-11e5-9270-e0689c66ee41.png)

 
### Server configuration
Desktop v ownCloud-2.1.0.2871-nightly20151111.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
related with #3737

**Comment by Dianafg76** [comment]
On Windows is unintuitive
![screen shot 2015-11-17 at 10 47 17](https://cloud.githubusercontent.com/assets/12032058/11207996/d4ec90e4-8d18-11e5-8c68-ce9844cde449.png)

Desktop v ownCloud-2.1.0.5630-nightly20151117-setup.exe

**Comment by dragotin** [comment]
@jancborchardt please help. beta1 is out!

**Comment by rullzer** [comment]
Ah yes that was already on the list me and @jancborchardt set up. It is the delete button (which we should have) but we need to have an icon for that. Does QT provide native icons that we can use for it?

**Comment by jancborchardt** [comment]
You can use the delete icon from core: https://github.com/owncloud/core/blob/master/core/img/actions/delete.png (SVG in the same folder.) Please use it at 50% opacity.

**Comment by Dianafg76** [comment]
I tested this issue and now is intuitive the button deleted on Windows and Mac
![screen shot 2015-11-24 at 10 42 58](https://cloud.githubusercontent.com/assets/12032058/11363132/3380c790-9298-11e5-861a-c1e55a064b65.png)
Desktop v ownCloud-2.1.0.2905-nightly20151124.pkg, ownCloud-2.1.0.5649-nightly20151124-setup.exe 

Closed

**Comment by jancborchardt** [comment]
@rullzer the »More« button should have the 3-dot icon instead of the text, just like for the folder list in the settings. Also, »can share/edit« should be lowercased.
