### ISSUE TITLE
[Share with users, groups] Different permissions on the Desktop Client than Server Web

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4122]
### Steps to reproduce
1. Open your ownCloud desktop client
2. Go to Open Folder "ownCloud"
3. Create a new folder, called aaa
4. Right click on the folder aaa
5. Select share with ownCloud
6. Write the name of the user to share
7. Click on Search

### Expected behaviour
The desktop client should have the same options as the server web

### Actual behaviour
On Permissions option I have only 4 options (Delete, Create, Update, Share), and if you go to the Server Web have 5 options (Can share, Can edit, Create, Change, Delete)

### Server configuration
Desktop v ownCloud-2.1.0.2871-nightly20151111.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
related with #3737

**Comment by rullzer** [comment]
Should be fixed with https://github.com/owncloud/client/pull/4133

**Comment by rullzer** [comment]
They could look nicer. but at least there is more info now.
