### ISSUE TITLE
[Share with users, groups] You should see all the users with letter (e.g us), not just those beginning with (e.g us)

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4123]
### Steps to reproduce
1. Open your ownCloud desktop client
2. Go to Open Folder "ownCloud"
3. Create a new folder, called aaa
4. Right click on the folder aaa
5. Select share with ownCloud
 I have 3 differents users (user1, user2, - user)
6. Write the name of the user to share (e.g us)
7. Click on Search

### Expected behaviour
You should see all the users with letter (e.g us), not just those beginning with (e.g. us). In my case, I have 3 users (user1, user2, - user)

### Actual behaviour
You can see only 2 user name (user1, user2), but you can't see the - user
![screen shot 2015-11-12 at 10 27 31](https://cloud.githubusercontent.com/assets/12032058/11114912/3fefdcb0-8928-11e5-97b1-841374f719bb.png)

### Server configuration
Desktop v ownCloud-2.1.0.2871-nightly20151111.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
related with #3737

**Comment by rullzer** [comment]
Ah mmm yes. Let me check if this is a problem of the sharee API (server side) or the client side (the way we do copletion).

**Comment by ogoffart** [comment]
Are you perhaps already sharing this file with that user?

**Comment by ckamm** [comment]
I think this is an issue in the client.

**Comment by ckamm** [comment]
Fixed, but requires Qt >= 5.2.0

**Comment by Dianafg76** [comment]
I tested this issue and now is working OK
Desktop v ownCloud-2.1.0.2907-nightly20151125.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

Closed
