### ISSUE TITLE
[Share with users, groups] If the Sharing API is disabled, on the Desktop client you should see an error when you shared with users/groups

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4126]
### Steps to reproduce
1. Go to the Server web with Admin
2. Click on Admin/admin
3. Disable the option Share API
![screen shot 2015-11-12 at 13 41 47](https://cloud.githubusercontent.com/assets/12032058/11118575/281ce612-8943-11e5-9f5d-bd239b6b822d.png)
4. Open your ownCloud desktop client with user1
5. Go to Open Folder "ownCloud"
6. Create a new folder, called aaa
7. Right click on the folder aaa
8. Select share with ownCloud
9. Write the name of the user to share (e.g - user1)
10. Click on Search

### Expected behaviour
You should see an error because the API is disabled

### Actual behaviour
Nothing happens

### Server configuration
Desktop v ownCloud-2.1.0.2871-nightly20151111.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
related with #3737

**Comment by rperezb** [comment]
Expected behavior:
Perhaps, the expected behavior should be that providing the Api share is disable, share link option should not be shown
cc @MTRichards

**Comment by MTRichards** [comment]
Agreed - Step one would be to show an error, step two is to not display the option in the first place - just like we do on mobile.

@danimo @dragotin

**Comment by ogoffart** [comment]
What's the API to know that sharing is disabled?
Is it in the capabilities? (because we look at the capabilities already, but i guess it's not there or it should be working)

**Comment by Dianafg76** [comment]
I tested this issue, and now when I disable the Share API, on the Desktop you can see the error "The server does not allow sharing" 
Desktop v ownCloud-2.1.0.2896-nightly20151120.pkg  
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

Closed

**Comment by Dianafg76** [comment]
![screen shot 2015-11-20 at 09 52 11](https://cloud.githubusercontent.com/assets/12032058/11295534/72202786-8f6c-11e5-9cc6-f57c60517b0c.png)

**Comment by Dianafg76** [comment]
I open this issue because with this version ownCloud-2.1.0.2904-nightly20151123.pkg, No appear the error because the API is disabled

**Comment by Dianafg76** [comment]
I tried again and is working with this v ownCloud-2.1.0.2905-nightly20151124.pkg
