### ISSUE TITLE
Repository on openSuse build service for Ubuntu 14.04 not available

### ISSUE THREAD

**Issue by lmm-git** [owncloud/client#4129]
### Expected behaviour
This link http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/ should contain the packages for Ubuntu 14.04 of the ownCloud client.

### Actual behaviour
The link produces a 404 error. Also the Ubuntu 14.04 repo is not showing up on the overview site of the openSuse build service of the ownCloud client.

**Comment by unkilbeeg** [comment]
All the xUbuntu repos were removed, but the Ubuntu repos were supposedly retained.  Unfortunately, for some reason whoever is managing the repos must not have gotten the word that 14.04 is the LTS.  They've removed 14.04 but kept 14.10, who knows why.

**Comment by RealRancor** [comment]
@jnweiger from http://owncloud.10557.n7.nabble.com/Repository-Cleanups-in-isv-ownCloud-desktop-td16056.html
> Yes, 14.04 should not be deleted. Re-adding....

**Comment by jnweiger** [comment]
opensuse build service is slow in publishing. It will take several hours to re-appear. sorry for that.

**Comment by RealRancor** [comment]
@jnweiger Is the issue reported here: https://github.com/owncloud/client/issues/4115 also related to that removal? If yes i think that one could be closed.

**Comment by lmm-git** [comment]
Do you want to keep the new old repo at the old name with a leading x? At the moment I am seeing only a 14.04 repo with a leading x.

**Comment by lmm-git** [comment]
Now it looks good. Thanks @jnweiger!
