### ISSUE TITLE
Syncing many files and folders takes extremely long

### ISSUE THREAD

**Issue by fhdummy** [owncloud/client#4130]
### Expected behaviour
I am currently syncing 22000 files, 4500 folders, 10 GB from my owncloud-server to the desktop client. It should start syncing after some time.

### Actual behaviour
I am already waiting for 30 minutes and the client only says: Discovering '...'
It didn't even start actually syncing the 10GB already.

### Steps to reproduce
1. Add the stated amount of data to your storage and link it to a newly created user account.
2. Download the desktop client.
3. Log in with the newly created user account and start syncing the data.

### Server configuration
Operating system: Ubuntu 14.04 (Kernel 3.19.0-33-generic)

Web server: Apache/2.4.7

Database: Mysql 5.5

PHP version: PHP 5.5.9-1ubuntu4.14 (cli)

ownCloud version: 8.2.0

Storage backend: External storage with SMB

### Client configuration
Client version: 2.0.2

Operating system: Windows 7

OS language: English

Installation path of client: C:\Program Files (x86)\ownCloud

**Comment by Dianafg76** [comment]
I can not reproduce the problem , in my case it is working OK.
I tested on Windows 2008, with version 2.0.2
Could you look for an error in the Desktop Logs
Thank you

**Comment by rullzer** [comment]
@fhdummy please retry with server version 8.2.1. The locking mechanism is improved significantly which should allow for faster syncing with lots of files and folders.

**Comment by dragotin** [comment]
The problem is that the discovery takes long on the server, probably because you use external smb storage. Please find help on how to enhance that via https://owncloud.org/support/
