### ISSUE TITLE
How to add an EOL banner to obsolete client manuals?

### ISSUE THREAD

**Issue by carlaschroder** [owncloud/client#4131]
The user, admin, and dev manuals for oC 5 & 6 now have banners warning "This documents an older, unsupported version of ownCloud. Please see our installation page for information on current ownCloud versions, and ownCloud Documentation for the current ownCloud manuals." (Like here: https://doc.owncloud.org/server/6.0/admin_manual/) This helps users who land on obsolete manual pages from Web searches.

I'm thinking this would be good for the sync client manuals as well. There are many more obsolete versions:
https://doc.owncloud.org/desktop/1.2/
https://doc.owncloud.org/desktop/1.3/
https://doc.owncloud.org/desktop/1.4/
https://doc.owncloud.org/desktop/1.5/
https://doc.owncloud.org/desktop/1.6/
https://doc.owncloud.org/desktop/1.7/

Two questions:
1. Do you agree this is a good idea?
2. Where to configure this warning banner? I've been all through the source files and I don't see where to edit the theme.

This is how it was done for oC 6: https://github.com/owncloud/documentation/pull/1877

**Comment by dragotin** [comment]
I think it's a good idea to have that.

**Comment by carlaschroder** [comment]
Git submodules are so fun... see https://github.com/owncloud/documentation/pull/1900. Please review @danimo @dragotin @LukasReschke

**Comment by carlaschroder** [comment]
I have spent a lot of time trying to build the client, and so far I have sadly failed. So I'm flying blind here.

**Comment by carlaschroder** [comment]
Done up to 8.0.
