### ISSUE TITLE
[Linux] Client crashes every time after Cloud URL is not available anymore

### ISSUE THREAD

**Issue by jmaschtaler** [owncloud/client#4132]
Hi Team,

client crashes every time after cloud URL is not available anymore.

Steps to reproduce:
- Make owncloud available via https://example-only.com/owncloud (with self signed certificate)
- Connect to remote ownCloud and sync.
- Make the ownCloud URL unavailable.
- Restart client.

Client crashes with
+++ killed by SIGSEGV (core dumped) +++
Segmentation fault (core dumped)

$ strace owncloud  # shows many messages like this:
recvmsg(6, 0x7ffffbea23d0, 0)           = -1 EAGAIN (Resource temporarily unavailable)

Infos of client:
OS: Ubuntu 14.04.3 LTS 64bit

$ dpkg -s owncloud-client
Package: owncloud-client
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 2102
Maintainer: Jürgen Weigert <jw@owncloud.com>
Architecture: amd64
Multi-Arch: same
Version: 2.0.2-3

Best,
Jörg

**Comment by guruz** [comment]
Does the Qt5-based package from https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adesktop%3Aqt5&package=owncloud-client work?
