### ISSUE TITLE
Account Action Menu misses Log out 

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4134]
In the Account settings window there is the button on the right providing the action menu with stuff like "open folder", "pause sync", "remove sync" and such.

In that menu, "Log out from Account" is missing as an action. It is available in the tray menu, yet nowadays as people start to work without tray menu, it should be there too.

**Comment by phil-davis** [comment]
Those actions are all per-folder-sync-connection actions.
"Log out of Account" is an action that effects all folder sync connections - like the "Remove Account" button. So should "Log out of Account" appear somehow near "Remove Account", or should that be made into another "..." menu of account-actions? Or?

**Comment by dragotin** [comment]
Thanks @phil-davis you're absolutely right. The menu is the wrong place.

**Comment by dragotin** [comment]
Yes, maybe the "Remove Account" button should also be a ".." menu with Account actions like 
' Log off
* Remove Account
* Add a new Account

**Comment by Dianafg76** [comment]
I tested this issue and is working Ok
Desktop v Desktop v ownCloud-2.1.0.2896-nightly20151120.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.2","versionstring":"8.2.1 RC3","edition":"Enterprise"}
Closed
