### ISSUE TITLE
[Plasma 5] Tray Menu does not have Sub Menu

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4135]
If two or more accounts are configured in the ownCloud Client, the tray menu normally has a sub menu for every configured account. 

The sub menus are not displaying in the Plasma 5 window manager.

Upstream bug: https://bugs.kde.org/show_bug.cgi?id=355282

**Comment by ckamm** [comment]
In #5251 @toehold had this workaround:
>I removed the package: appmenu-qt5 see bug reports: https://bugs.launchpad.net/ubuntu/+source/appmenu-qt5/+bug/1307619 and https://bugs.launchpad.net/ubuntu/+source/qtbase-opensource-src/+bug/1612767 and now all is working again.

**Comment by guruz** [comment]
Please re-open if this still happens
