### ISSUE TITLE
No obvious way to close main window

### ISSUE THREAD

**Issue by RalfJung** [owncloud/client#4136]
As you can see in the screenshot, since version 2.0.2, the ownCloud client no longer poffers an obvious way to close the window:

![screenshot from 2015-11-13 13-03-26](https://cloud.githubusercontent.com/assets/330628/11145610/5378aeda-8a07-11e5-90d5-4b994596f2ed.png)

This is using Cinnamon 2.6 as desktop environment. I have to right-click the item in the taskbar to close the window, or click on the ownCloud icon in the systay. The latter is not always present (see #3926 - that may be a bug in Cinnamon, but that doesn't help me). In any case, both of these are completely detached from the actual window I want to close. I have never before seen a program that did not, within its own main window (including the title bar), offer a way to close that window.

**Comment by danimo** [comment]
This has already been fixed for the next version. In the meanwhile, ESC should work.
