### ISSUE TITLE
[Linux] QtKeyChain does not store passwords for multiple users in gnome-keyring 

### ISSUE THREAD

**Issue by schuerg** [owncloud/client#4140]
I have multiple accounts configured in my owncloud client.

**The problem is that owncloud-client only stores the user password of one user in gnome-keyring.**
At each start of the client I have to type the paswords of the other accounts.

I'm using...
Fedora 23
Kernel 4.2.5-300.fc23.x86_64
owncloud-client 2.0.2
gnome-keyring 3.18.1

**Comment by guruz** [comment]
BTW FYI @frankosterfeld :)

Is this also related? https://github.com/frankosterfeld/qtkeychain/issues/55

**Comment by guruz** [comment]
@schuerg Any news? Does it work meanwhile?

**Comment by ogoffart** [comment]
Closing this old issue.  PRobably fixed in 2.3 or 2.4  Please re-open if not fixed.
