### ISSUE TITLE
Ubuntu: 404 in apt-get update

### ISSUE THREAD

**Issue by binarykitchen** [owncloud/client#4142]
```
W: Failed to fetch http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_15.10/Packages  404  Not Found [IP: 195.135.221.134 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
```

Source is:

```
# michael-heuberger at M1 in /etc/apt/sources.list.d [17:35:09]
$ cat owncloud-client.list
deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_15.10/ /
```

**Comment by RealRancor** [comment]
@binarykitchen Repositories have changed according to:

http://owncloud.10557.n7.nabble.com/Repository-Cleanups-in-isv-ownCloud-desktop-td16056.html

So you can update your repository setup and close here.

**Comment by binarykitchen** [comment]
yep, removing the `x` worked

but i think in the future such rad changes should be announced somewhere

**Comment by RealRancor** [comment]
@binarykitchen It was announced above at the users mailinglist :-)

**Comment by binarykitchen** [comment]
that's good. but what about on the official owncloud page and on social medias i am following?

**Comment by RealRancor** [comment]
Maybe on heise and spiegel? :-)

**Comment by binarykitchen** [comment]
i get your message - ignore me then :)

**Comment by RealRancor** [comment]
Nothing to ignore :-). Its partly a lack of communication again like happened often in the past. But i think you can't communicate each single change everywhere, especially as this is only affecting the Ubuntu repositiories.

But i think User mailinglist and forums https://forum.owncloud.org/viewtopic.php?f=9&t=31470 are good to announce such stuff.
