### ISSUE TITLE
Ignore message for folder says "file ignored"

### ISSUE THREAD

**Issue by LukeOwncloud** [owncloud/client#4143]
occlient is win 5619

If a folder is ignored, its sync actvitiy log entry says "file ignored." This is a bit ambiguous. (e.g. reason for issue https://github.com/owncloud/client/issues/4141)

I'd expect to either distinghuish file and folder or write "file/folder ignored".

![ignore file is folder](https://cloud.githubusercontent.com/assets/2737900/11181101/e92e81d4-8c5f-11e5-8bb1-4511a53ae2a8.png)

(In this sample `.ipk Dateien installieren` is a folder.)

**Comment by ckamm** [comment]
Closing... trivial change.
