### ISSUE TITLE
libowncloudsync label wording details

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#4145]
Just details:

![capture du 2015-11-06 08-14-03](https://cloud.githubusercontent.com/assets/925062/11183612/188e5414-8c73-11e5-822c-617f2929ae36.png)
Instead of

> OwnCloud sync library.

the label should be

> ownCloud sync library

(lowercase o, no dot at the end)

Also, Internationalization should be with a z as we use American English everywhere else as well.

**Comment by jnweiger** [comment]
fixed 'Internationailzation'. No idea where the OwnCloud comes from. French locale?
Actually I wonder why there are so little dots at the ends. The English package descriptions have a dot at the end everywhere.

**Comment by jancborchardt** [comment]
It’s not really translated (»library«) so I guess it doesn’t relate to the locale.

And are you sure there should be dots? They are only labels and not sentences.

**Comment by jnweiger** [comment]
in RPM world the dots are forbidden and cause a build error. in DEB world the dots are allowed, so everybody does them.

**Comment by jnweiger** [comment]
The package summary for owncloud-client-l10n.rpm says "Localisation for ownCloud"
Should that also be a 'z' in there?

**Comment by jancborchardt** [comment]
Yep, should also be a z. Thanks! :)

**Comment by jnweiger** [comment]
done. https://github.com/owncloud/administration/commit/68db28664538984e2b80a09964e9cc5c618b54ee

**Comment by jancborchardt** [comment]
Cool! So the capitalization and punctuation of »OwnCloud sync library.« is still unclear where to change?

**Comment by ogoffart** [comment]
Why is there even an option not to install that (or to install it separatly?)  Should it not be part of the ownCloud client package, without asking the user?

**Comment by jancborchardt** [comment]
I guess it’s a hard dependency and it’s not possible to install the client package without that.

**Comment by jnweiger** [comment]
@ogoffart libowncloudsync is a package on its own, but it is a hard dependency of the client. I don't know a reason why it is not part of the main owncloud-client package. But I don't suggest a merge either. It causes usually a lot of unneeded havoc, if we do structural changes.

**Comment by jnweiger** [comment]
My assumption is that some gui installer randomly decides to capitalize the description.
Removing all trailing dots, in the hope that the capitalization magic looks for these.

Fixed ca 20 locations in various desktop, testing, nightly projects in both build services. fixed all templates.
Branded clients untouched.
