### ISSUE TITLE
icon background is white, should be invisible

### ISSUE THREAD

**Issue by nbbn** [owncloud/client#4146]
Hello, I'm using ubuntu 15.10, i3-wm, and ownCloud version 1.8.1 from official repo.
As you can see on the picture, background of icon looks inconsistently.

![screenshot](https://cloud.githubusercontent.com/assets/7264317/11184835/083d9280-8c7a-11e5-909c-cdc98ca64c48.png)

**Comment by guruz** [comment]
Thanks, 1.8.1 is outdated.
We're at 2.0.2 now.
https://owncloud.org/install/#install-clients
