### ISSUE TITLE
[Share with users, groups] They Should appear selected all the permissions

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4152]
### Steps to reproduce
1. Open your ownCloud desktop client
2. Go to Open Folder "ownCloud"
3. Create a new folder, called aaa
4. Right click on the folder aaa
5. Select share with ownCloud
6. Introduce the first letter for the user to share (e.g. u)
7. Select the user (e.g. user)

### Expected behaviour
They should appear selected all the permissions

### Actual behaviour
When you select the user (e.g user1), All permissions are not selected
![screen shot 2015-11-17 at 10 59 33](https://cloud.githubusercontent.com/assets/12032058/11208511/e867dba8-8d1b-11e5-876c-e863c284f9d6.png)

### Server configuration
Desktop v ownCloud-2.1.0.5630-nightly20151117-setup.exe on WINDOWS
Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

**Comment by ogoffart** [comment]
What should be the default permissions from the desktop?
CF also https://github.com/owncloud/core/issues/11707

CC: @LukasReschke  @jancborchardt  @MTRichards

**Comment by jancborchardt** [comment]
All permissions should be set, just as with the server. Only when the server changes behavior, this should change.

**Comment by ogoffart** [comment]
But since the client and the server does not have the same release schedule, this is hard to do.
What should be done for 2.1?

**Comment by jancborchardt** [comment]
Definitely enable all by default since 8.2 and every version before that behaves this way.

**Comment by ogoffart** [comment]
Actually that's easy because when we don't specify the permission, the server applies the default permission.  So now the default permissions are the same than on the server.

**Comment by guruz** [comment]
@LukasReschke ^^ Not sure if this is well thought through with regards to https://github.com/owncloud/core/issues/11707

**Comment by rullzer** [comment]
I agree with @ogoffart, if we don't specify permissions we will fall back to the server defaults. So once we change default behaviour on the server the client will follow automatically. Seems like the most elegant and future proof solution.

**Comment by Dianafg76** [comment]
I tested this issue, and now when you Share with users and groups and select the user, all permissions are selected
Desktop v ownCloud-2.1.0.2896-nightly20151120.pkg

Server v {"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

Closed

**Comment by guruz** [comment]
So this is done when the share is created, so we create it and get back the server defaults and then show that in the UI?
All good then
