### ISSUE TITLE
[2.0.2] [OS X] [Windows] Connection Closed

### ISSUE THREAD

**Issue by MarkusAmshove** [owncloud/client#4153]
Hi everybody!

I recently downloaded the latest version (2.0.2 as of this writing) and I can't connect to my server with neither the Windows or MacOS client.

Everytime I try to connect it says "Connection closed" (Verbindung beendet) without any further error message.
Also the owncloud.log on the server doesn't seem to show anything.

If I connect via Windows Networkshare (Windows Explorer) directly to the Webdav URL it's working.
If I use the owncloud Desktop Client version 1.8.4 it's working, but it's always trying to update to 2.0.2.

Best regards!

**Comment by guruz** [comment]
@MarkusAmshove Are you willing to test http://download.owncloud.com/desktop/daily/ownCloud-2.1.0.2889-nightly20151117.pkg (OS X) ? This will might become 2.1 beta1 soon.

**Comment by guruz** [comment]
@MarkusAmshove The betas for Windows and OS X are out, please test
https://owncloud.org/install/#testing-development

**Comment by MarkusAmshove** [comment]
Hello guruz, thank you for taking care of this issue!

Sadly the beta doesn't resolve this issue, it still just says "Connection closed".

I now see this in the log (dunno if it's related):

    {
       "reqId":"dHVpf9Q0+Og7AYRnH4pz",
       "remoteAddr":"myip",
       "app":"webdav",
       "message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/vhosts\\\/myurl.tld\\\/httpdocs\\\/cloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(148): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/var\\\/www\\\/vhosts\\\/myurl.tld\\\/httpdocs\\\/cloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(121): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/var\\\/www\\\/vhosts\\\/myurl.tld\\\/httpdocs\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/var\\\/www\\\/vhosts\\\/myurl.tld\\\/httpdocs\\\/cloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/var\\\/www\\\/vhosts\\\/myurl.tld\\\/httpdocs\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/var\\\/www\\\/vhosts\\\/myurl.tld\\\/httpdocs\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/var\\\/www\\\/vhosts\\\/myurl.tld\\\/httpdocs\\\/cloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/var\\\/www\\\/vhosts\\\/myurl.tld\\\/httpdocs\\\/cloud\\\/remote.php(137): require_once('\\\/var\\\/www\\\/vhosts...')\\n#9 {main}\",\"File\":\"\\\/var\\\/www\\\/vhosts\\\/myurl.tld\\\/httpdocs\\\/cloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}",
       "level":0,
       "time":"2015-11-17T16:11:04+00:00",
       "method":"PROPFIND",
       "url":"\/cloud\/remote.php\/webdav\/"
    }

**Comment by MarkusAmshove** [comment]
I tested with "testpilotcloud-2.1.0.5634beta1-setup.exe"

**Comment by guruz** [comment]
Please try with the OS X release (of the real client not testpilot) and run with:

```
/Applications/owncloud.app/Contents/MacOS/owncloud --logfile -
```

and see what is happening before.

Can you set the owncloud server log to verbose?
Which server version?
Which apps installed?
Do you use any strange web firewalls or modules?

**Comment by MarkusAmshove** [comment]
- Loglevel is set to 0 (DEBUG),
- Version of server is ownCloud 8.2.0 (stable) 

	    SELECT appid FROM `oc_appconfig` WHERE configkey='enabled' AND configvalue='yes'
	    
	    appid 	
	    bookmarks
	    calendar
	    contacts
	    files
	    files_locking
	    files_pdfviewer
	    files_sharing
	    files_texteditor
	    files_trashbin
	    files_versions
	    files_videoviewer
	    firstrunwizard
	    notifications
	    provisioning_api
	    tasks
	    templateeditor
	    updater

- No firewalls or modules

My tester for MacOS is @Duffed :-)

**Comment by MarkusAmshove** [comment]
Still getting 
    Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":

but at least we have a log now :-)

**Comment by guruz** [comment]
Server 8.2.1 is being released at the moment..should be in the next minutes.

Did you check the webserver error log too?

I think the ```No basic authentication headers were found``` might be a false lead, maybe we could get rid of that, I see it in so many bugreports? ( @PVince81 )

**Comment by MarkusAmshove** [comment]
Ah sorry, that was the server log. 
@Duffed is the guy who needs to test it on MacOS with logging enabled, since I don't own a Mac myself.

**Comment by Duffed** [comment]
Hey I used --logfile when I run the file. Terminal output:
`
11-17 19:01:24:081 0x7fdcb35038a0 OCC::OwncloudWizard::appendToConfigurationLog: Setup-Log:  "Verbindungsversuch mit ownCloud unter https://amshove.org/cloud/…"
11-17 19:01:24:081 0x7fdcb35038a0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://amshove.org/cloud" + "/"
11-17 19:01:29:708 0x7fdcb58f0770 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7fdcb36642d0) QHttpNetworkReply(0x7fdcb3615a10) 0 false 3 8 QAbstractSocket::ConnectedState
11-17 19:01:29:708 0x7fdcb58f0770 unknown: ERRORING CURRENT QHttpNetworkReply(0x7fdcb3615a10)  QUrl( "https://amshove.org/cloud/remote.php/webdav/" ) 
11-17 19:01:29:708 0x7fdcb35038a0 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 2 "Verbindung beendet" QVariant(Invalid)
11-17 19:01:29:708 0x7fdcb58f0770 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7fdcb36642d0) QObject(0x0)  0 false 3 16
11-17 19:01:29:709 0x7fdcb35038a0 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 0 „"
`

**Comment by guruz** [comment]
2.1rc1 is out..

**Comment by MarkusAmshove** [comment]
Hi guruz sorry for the late reply, didn't have the time to update ownCloud.

I'm now using the "ownCloud 8.2.1 (stable)" server version and the "2.1.0-rc1" Windows Desktopclient.

I'm getting the same error as before, something about "No basic authentication headers were found".
It's the only log entry on the server side :/

**Comment by guruz** [comment]
Are you guys using the encryption app on the server?
There's not much I think I can help anymore except looking for similar bugs or checking https://owncloud.org/support/

**Comment by guruz** [comment]
https://github.com/owncloud/client/issues/4047#issuecomment-165486607

**Comment by MarkusAmshove** [comment]
I'll check that out. Note that I didn't use any server side encryption other than SSL for the transfer

**Comment by guruz** [comment]
@MarkusAmshove Did you have any luck?

**Comment by MarkusAmshove** [comment]
That script is either looping or taking really long, I'm running it.

If it's not working I'm going to check some files by hand

**Comment by guruz** [comment]
Is there anything in the webserver's error log?
Is there anything in the server's owncloud.log?
Are there HTTP 401 or 403 in the access log before the failing request?

**Comment by guruz** [comment]
Let's track in https://github.com/owncloud/client/issues/4326#issuecomment-169282743 for now. It's a combined core/client issue IMHO.

**Comment by MarkusAmshove** [comment]
Hey @guruz,

I was finally able to resolve the issue.

It had nothing to do with the OC-Client but with the php version (or mode?) in which owncloud was running.

I updated php and then my domain was running in CGI-mode.
This was a suggestion by @srissel here https://github.com/owncloud/core/issues/21371#issuecomment-167224548

I'm now running FPM-mode and the client is working again :+1: 

I don't know anything about these modes as I have nothing to do with php, but isn't it strange that an earlier version of the desktop client was working?
