### ISSUE TITLE
preview mode after upgrade to 9.1

### ISSUE THREAD

**Issue by itsenseug** [owncloud/client#4154]
dear oc team,

After updating our IPAD's from version 8.4.x to 9.1 we have a BUG with the preview of documents. Before the update a finger-tap on a document that was open by OC-Client (3.4.5) the document get fullscreen and the left side menu bar was hidden. One more finger-tap somewhere on the document bring the left side menu bar back on screen. After upgrading our IPAD's to Version 9.1 this doesn't work anymore. We tested with several documents without success. Please check this bug and fix it asap, we love your service!

BR,
Matthias

**Comment by guruz** [comment]
Please check in https://github.com/owncloud/ios/issues or http://owncloud.org/support
You are in the desktop bugtracker
