### ISSUE TITLE
Make "Add Folder" dialog resize nicely

### ISSUE THREAD

**Issue by butonic** [owncloud/client#4157]
I hate having to scroll through lists. My monitor is big enough, so I resize most dialogs to see more of what is there. There is one thing that makes me furious: modal dialogs that cannot be resized or moved, preventing me from looking at another window of the application. In this case I could resize the window, but it then looked like this:

![bildschirmfoto von 2015-11-18 09 33 57](https://cloud.githubusercontent.com/assets/956847/11236236/46b59648-8dd8-11e5-989b-d59d935fe4af.png)

Now ... this might be debian being debian again ... I just thought I would let you guys now. And please don't just make it a fixed size dialog. Thx

**Comment by danimo** [comment]
Qt dialogs always resize. In this case, the layout is broken. We don't do fixed size dialogs.

**Comment by guruz** [comment]
@butonic Wanna check the nightly?
