### ISSUE TITLE
[translation] [de] Download rate not displayed

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#4158]
An user reported a bug with the download rate in the 2.0.2 client:

![transferrate](https://cloud.githubusercontent.com/assets/214010/11242684/97c23ec6-8e03-11e5-9890-64b030f302c9.png)

This is probably caused by a syntax error in the translation file.

https://github.com/owncloud/client/blob/v2.0.2/translations/client_de.ts#L719-L723
```
    <message>
        <location filename="../src/gui/folderstatusmodel.cpp" line="792"/>
        <source>download %1/s</source>
        <translation>Download %s</translation>
    </message>
```

I fixed it in [Transifex](https://www.transifex.com/owncloud_robot/owncloud/translate/#de_DE/client/54561622):

![owncloud___transifex_editor_and_client_client_de_ts_at_v2_0_2_ _owncloud_client_and_inbound_email_message___salesforce_-_enterprise_edition](https://cloud.githubusercontent.com/assets/214010/11242560/c7fe0706-8e02-11e5-98fc-a01254818873.png)

@dragotin Will this be included in the next release? /cc @MorrisJobke 

I highly recommend to add hints in Transifex as discussed in https://github.com/owncloud/client/issues/3519#issuecomment-126256148. Translation strings with variables are very fragile.

00004161

**Comment by guruz** [comment]
Can you reproduce in 2.1beta1?

**Comment by ogoffart** [comment]
(If the change was made a few hour ago, it will not be in 2.1)

Anyway, i added comments for the translators now.

**Comment by michaelstingl** [comment]
@ogoffart You are my hero!

@DeepDiver1975 How do the hints find their way back to Transifex?

**Comment by MorrisJobke** [comment]
> @DeepDiver1975 How do the hints find their way back to Transifex?

In core we add following syntax:

```php
// TRANSLATORS: text here
...
```

then this is shown in transfex as info box on top of the translations ;)

**Comment by phil-davis** [comment]
And in the gettext doco http://www.gnu.org/software/gettext/manual/gettext.html search fro "TRANSLATORS:" and you will see examples of giving hints in comments that get auto-extracted into the files that the translators are given to work with.

**Comment by michaelstingl** [comment]
@MorrisJobke @phil-davis There are now comments in the *.ts files:

```
    <message>
        <location filename="../src/gui/folderstatusmodel.cpp" line="874"/>
        <source>%1 %2 (%3 of %4)</source>
        <extracomment>Example text: &quot;uploading foobar.png (2MB of 2MB)&quot;</extracomment>
        <translation>%1 %2 (%3 von %4)</translation>
    </message>
```

But I don't see them in the Transifex web UI yet.

**Comment by ogoffart** [comment]
If it is in the .ts file it should be in transifex,  because it is the job that update transifex that creates the ts files.

---

For reference, in C++ it's differnt than PHP. It is

```cpp
//: text here  
foobar->setText(tr("more text"));
```

cf http://doc.qt.io/qt-5/i18n-source-translation.html#translator-comments

**Comment by ckamm** [comment]
The fixed text is in `client_de.ts`, so I assume nothing more needs to be done.
