### ISSUE TITLE
owncloudcmd fails smashbox due to "number of retries reached" in 2.1.0beta1

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/client#4160]
Since the update last night smashbox execution fails.

Example basicSync Smashbox test from cern:
https://github.com/owncloud/smashbox/blob/master/lib/test_basicSync.py

1. Creator creates files and syncs
2. Winner syncs
3. Winner lists files (only welcome.txt is there)

Regression from https://github.com/owncloud/client/commit/16c078963b375fac4cb820ff9f3703c80711d3a2 for #4037 @ogoffart 

The problem is that (although it's just the initial sync) the client takes 10+ retries until it successfully download and uploads the files.

---

Question: Is it intended that the client needs more than 3 syncs (default) for downloading 1 file and uploading 3? In the tests I did it was between 10 and 15 all the time

**Comment by nickvergessen** [comment]
Sync protocol sample https://gist.github.com/nickvergessen/9129ecc6b23020daa9c0

**Comment by ogoffart** [comment]
The error is:  `Local file changed during sync.`

the reason is that we consider that if a file is newer than 2 seconds, we don't want to sync that file because it's too recent.

So this means we should add a 2sec pause before starting the smashbox jobs.

**Comment by nickvergessen** [comment]
oh, that's ... bad I guess? It slows us down quite heavily with tests.
Is this only after creating files, or even after sync + modify?

**Comment by ogoffart** [comment]
Even after sync + modify

We could change this time value with an environement variable for example.

**Comment by nickvergessen** [comment]
Or with a parameter to the cmd call (like with number of retries)? That would be easiest for us.

**Comment by ogoffart** [comment]
Next build will not check for too recent files.

Note: there might be smashbox tests that were relying on several syncs to be run which hapenned because of these recent files. 
Maybe these will start failing. In that case this either mean that the client should be fixed to request a new sync in that case,  or that the test must manually run the sync several times.

**Comment by nickvergessen** [comment]
Smashing atm and looks promising :hourglass_flowing_sand:

**Comment by nickvergessen** [comment]
:white_check_mark: works and smashbox is passing again
