### ISSUE TITLE
Fedora 23 ships qt-5.5.0

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#4161]
Client 2.0.2 builds against the Fedora_23 target using their qt5-qtbase-5.5.0-18.fc23 and friends.
@danimo @dragotin can we somehow test if their 5.5.0 is good?

logfile
https://build.opensuse.org/build/isv:ownCloud:desktop/Fedora_23/x86_64/owncloud-client/_log

**Comment by dragotin** [comment]
IIRC in 5.5.0 there was a tray (icon?) issue

**Comment by jnweiger** [comment]
@dragotin suggested test: install on a fedora23 vm, confirm the icon is in the toolbar thing and works.
right?

**Comment by jnweiger** [comment]
@danimo Are you sending the tray-icon patch for 5.5.0 to fedora upstream?

**Comment by dragotin** [comment]
yes

**Comment by danimo** [comment]
Can't find the fix. @ogoffart? @guruz?

**Comment by guruz** [comment]
qt-everywhere-opensource-src-4.8.6-systemtrayicon.patch
http://pkgs.fedoraproject.org/cgit/qt.git/tree/qt.spec
http://pkgs.fedoraproject.org/cgit/qt.git/plain/qt-everywhere-opensource-src-4.8.6-systemtrayicon.patch

Note: I'm not a Fedora user this is just a guess

**Comment by danimo** [comment]
@guruz nope. something in Qt5 caused apps not to show submenus in the systray menu.

**Comment by ogoffart** [comment]
We worked around the system tray icon bug in the code of the client.

**Comment by dragotin** [comment]
Ok, so this is a non issue. Thx @ogoffart
