### ISSUE TITLE
[Activity View] If you disable the Activity app you can't see the message " The administrator has disabled the activity for this server"

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4163]
### Steps to reproduce
1. Open your ownCloud desktop client with the new v 2.1.0, with user
2. Disable Activity app in the server.
4. Go to the Desktop client
5. Go to Open Folder "ownCloud"
6. Create a new folder, called aaa
7. Right click on the folder aaa
8. Select share with ownCloud
9. Share with other user (e.g. user1)
10. Wait to sync

### Expected behaviour
It should appear the message " The administrator has disabled the activity for this server"

### Actual behaviour

No message appears "The administrator has disabled the activity for this server"
Related #3732 

### Server configuration
Desktop 2.1.0 (build 2889)
Server v {"installed":true,"maintenance":false,"version":"9.0.0.2","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Comment by nickvergessen** [comment]
The problem I see with this is when you have multiple accounts in your client, we still need to show the activities for the other accounts, so that may not be easily possible

**Comment by Dianafg76** [comment]
@nickvergessen I'll try with one account

**Comment by Dianafg76** [comment]
With one account does not appear
LOG:
```
11-19 10:32:10:400 0x7fa17852d170 OCC::SocketApi::command_SHARE: void OCC::SocketApi::command_SHARE(const QString &, QIODevice *) "/Users/Diana/activity_feed/one"
11-19 10:32:10:401 0x7fa17852d170 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE:OK:/Users/Diana/activity_feed/one"
11-19 10:32:10:403 0x7fa17852d170 OCC::ownCloudGui::slotShowShareDialog: void OCC::ownCloudGui::slotShowShareDialog(const QString &, const QString &, bool) Opening share dialog "//one" "/Users/Diana/activity_feed/one"
11-19 10:32:10:406 0x7fa17852d170 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "http://docker.oc.solidgear.es" + "ocs/v1.php/apps/files_sharing/api/v1/shares"
11-19 10:32:10:407 0x7fa17852d170 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "http://docker.oc.solidgear.es" + "ocs/v1.php/apps/files_sharing/api/v1/shares"
11-19 10:32:10:629 0x7fa17852d170 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap &) "9.0.0.2" Fetched 0 shares
11-19 10:32:10:630 0x7fa17852d170 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap &) Sending  0 shares
11-19 10:32:10:695 0x7fa17852d170 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap &) "9.0.0.2" Fetched 0 shares
11-19 10:32:10:696 0x7fa17852d170 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap &) Sending  0 shares
11-19 10:32:10:697 0x7fa17852d170 OCC::ShareLinkWidget::slotSharesFetched: void OCC::ShareLinkWidget::slotSharesFetched(const QList<QSharedPointer<OCC::Share> > &) "9.0.0.2" Fetched 0 shares
11-19 10:32:15:616 0x7fa17852d170 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareeJob created for "http://docker.oc.solidgear.es" + "ocs/v1.php/apps/files_sharing/api/v1/sharees"
11-19 10:32:15:633 0x7fa17a9748b0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QTcpSocket(0x7fa17ab387f0) QObject(0x0)  0 false 3 0 QAbstractSocket::UnconnectedState
11-19 10:32:18:574 0x7fa17852d170 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "http://docker.oc.solidgear.es" + "ocs/v1.php/apps/files_sharing/api/v1/shares"
11-19 10:32:18:916 0x7fa17852d170 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "http://docker.oc.solidgear.es" + "ocs/v1.php/apps/files_sharing/api/v1/shares"
11-19 10:32:19:044 0x7fa17852d170 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap &) "9.0.0.2" Fetched 1 shares
11-19 10:32:19:045 0x7fa17852d170 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap &) Sending  1 shares
11-19 10:32:24:048 0x7fa17a9748b0 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QTcpSocket(0x7fa17aa52370) QObject(0x0)  0 false 3 0 QAbstractSocket::UnconnectedState
```

**Comment by nickvergessen** [comment]
I didn't say it appears with one account, I just said that it's hard to keep track of this in a multi case scenario

**Comment by Dianafg76** [comment]
Ok, I did not understand well, sorry

**Comment by Dianafg76** [comment]
I tested this issue, and is not working for my
If the server does not have the activities app enabled, No message appears "The administrator has disabled the activity for this server"

Desktop v  ownCloud-2.1.0.2896-nightly20151120.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.3","versionstring":"8.2.1 RC4","edition":"Enterprise"}

**Comment by dragotin** [comment]
@Dianafg76 works here:
![actviityview](https://cloud.githubusercontent.com/assets/1070214/11364884/4ae7ec64-92a3-11e5-84a1-0b42a0017798.png)

**Comment by Dianafg76** [comment]
I tested this issue, and is working OK 
![screen shot 2015-11-25 at 09 56 43](https://cloud.githubusercontent.com/assets/12032058/11392567/ebac2ff4-935a-11e5-9633-1988f1754403.png)
Desktop v ownCloud-2.1.0.2907-nightly20151125.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

Closed
