### ISSUE TITLE
[Activity View] On Activity option/Server Activity you can't see some buttons (Ok, Cancel)

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4164]
### Steps to reproduce
1. Open your ownCloud desktop client with the new v2.1.0
2. Right click to the oC icon
3. Click on Settings
4. Clikc on Activity option
5. Click on Server Activity

### Actual behaviour
If you see the issue #4083, you can see some buttons: OK, Cancel.
But with this version you can't see those buttons
![screen shot 2015-11-19 at 10 14 11](https://cloud.githubusercontent.com/assets/12032058/11266893/40ac18c8-8ea8-11e5-9007-9c0883f7f0fa.png)

### Server configuration
Desktop 2.1.0 (build 2889)
Server v {"installed":true,"maintenance":false,"version":"9.0.0.2","versionstring":"9.0 pre alpha","edition":"Enterprise"}

**Comment by dragotin** [comment]
On linux there is one Close button. I am not sure about Mac @guruz 

But in any case there should not be an Ok/Cancel button group, but only Close, if that is needed on Mac.

**Comment by guruz** [comment]
Didn't we agree to not put Close buttons at all except on Linux!?
@danimo @ogoffart

**Comment by ogoffart** [comment]
Reference:  https://github.com/owncloud/client/issues/3713

The decision from danimo is too keep the close button.

The settingsdialog has a close button.  The settingsdialog_mac  does not.

**Comment by guruz** [comment]
@ogoffart Do you see the OK/Cancel buttons on Linux that @Dianafg76 mentioned about https://github.com/owncloud/client/pull/4083 ? Should they not be called "Close" then?

**Comment by ogoffart** [comment]
Not OK/Cancel.     Just Close

**Comment by guruz** [comment]
@Dianafg76 Then it's normal, thankfully no Close button on OS X. I have no idea why @danimo and @dragotin think they need this button on Windows.
(I understand the Linux-WM reasons)
