### ISSUE TITLE
owncloudcmd copies hidden files even without -h flag

### ISSUE THREAD

**Issue by johanehnberg** [owncloud/client#4166]
owncloudcmd synchronizes hidden files by default. This makes it impossible to turn on or off that feature from the command line, since there is no negative flag.

From the command line help:
-h                     Sync hidden files,do not ignore them

as an example I use .profile , grepping lines containing only that from the output.

When syncing:
[11/19 21:32:51.438779, 9] csync_walker:  file: /home/johan/.profile [inode=17039364 size=675]
[11/19 21:32:51.438827, 8] _csync_detect_update:  file: .profile, instruction: INSTRUCTION_NEW <<=
[11/19 21:32:51.707298, 8] _csync_merge_algorithm_visitor:  INSTRUCTION_NEW      client file: .profile
!!! OCC::PUTFileJob created for "https://owncloud.molnix.com/" + "maas/.profile" 
void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://maas:SjNznlIqaWNY9wQHx5Y25H0kCAtBvayQ@owncloud.molnix.com/remote.php/webdav/maas/.profile" )  FINISHED WITH STATUS 0 "" QVariant(int, 201) QVariant(QString, "Created") 
OCC::SyncJournalFileRecord::SyncJournalFileRecord(const OCC::SyncFileItem&, const QString&) "/home/johan/.profile" Retrieved inode  17039364 (previous item inode:  17039364 ) 
"INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7,  ?8 , ?9 , ?10, ?11, ?12, ?13, ?14);" 8248587146411616198 8 ".profile" 17039364 0 "1418111595" "0" "3a61408e2c6436d89dbea3bc73ebfaf0" "00869519oc761iupfq18" "" 675 0 
"DELETE FROM uploadinfo WHERE path=?1" ".profile" 
void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) ".profile" INSTRUCTION_NEW 4 "" 
[11/19 21:34:51.785678, 8] csync_ftw:  Uniq ID from Database: .profile -> 3a61408e2c6436d89dbea3bc73ebfaf0
[11/19 21:34:51.785699, 9] csync_walker:  file: /home/johan/.profile [inode=17039364 size=675]
[11/19 21:34:51.785768, 8] _csync_detect_update:  file: .profile, instruction: INSTRUCTION_NONE <<=
[11/19 21:34:52.036474, 9] csync_walker:  file: ownclouds://owncloud.molnix.com/remote.php/webdav/maas/.profile [file_id=00869519oc761iupfq18 size=675]
[11/19 21:34:52.036525, 9] _csync_detect_update:  file excluded because it is a hidden file: .profile
[11/19 21:34:52.036557, 8] _csync_detect_update:  file: .profile, instruction: INSTRUCTION_IGNORE <<=
[11/19 21:34:52.671298, 9] _csync_merge_algorithm_visitor:  INSTRUCTION_NONE     client file: .profile
[11/19 21:34:52.673224, 8] _csync_merge_algorithm_visitor:  INSTRUCTION_IGNORE   server file: .profile
void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) ".profile" INSTRUCTION_IGNORE 6 "File is ignored because it's hidden." 

Yet it turns up in the web interface.

**Comment by johanehnberg** [comment]
As a workaround until this behaviour may change, use an exclude file containing '.*' with --exclude.

**Comment by Akuukis** [comment]
On Debian ownCloud client 2.0.2 **uploads** hidden files without "Sync hidden files" ticked. When I add account on second PC, hidden files that exists in server **are ignored** but those with different name, aka new files, are **uploaded**. Hidden files are **not downloaded**. After adding ".*" to ignore list hidden files are **not uploaded**.

**Comment by ckamm** [comment]
@Akuukis Thanks for the precise bug description. I've tried to reproduce this unintendend upload with 2.1 but it seems to work fine there. Could I ask you to test as well?
@johanehnberg You could also test with the 2.1 owncloudcmd

**Comment by Akuukis** [comment]
@ckamm Thanks! I downloaded and installed ownCloud 2.1.0 on Ubuntu 14.10 that has not-uploaded `.test` test file since previous post, because it had `.*` in ignore list.

After restarting ownCloud 
- it uploaded 5 random files that *maybe* weren't synced before but for sure should be synced.
- then failed on another 4 files with `Forcing job abort on HTTP connection reset with Qt < 5.4.2.`
- but they succeeded 10 seconds later.
- Everything is up to date.
- I remove `.*` from ignore list
- ownCloud rescans everything
- (... 8 minutes later after 40-50 GB)
- Nothing uploaded/downloaded, success!

In *Activity* > *Not Synced* tab I see that `.test` file have action `File is ignored because it's hidden.` For me it works like expected. 

Nice tabs with useful info, I like that!

**Comment by ckamm** [comment]
@Akuukis Thanks for verifying!

**Comment by johanehnberg** [comment]
I can also verify this is fixed in 2.1.0.
