### ISSUE TITLE
Protocol / Activities: Double click on row should open local file manager of that folder (if existing)

### ISSUE THREAD

**Issue by guruz** [owncloud/client#4168]
... and possibly select the file

**Comment by dragotin** [comment]
It does that actually on single click, that is how we do it with the sync protocol as well.

However, note that it happens more often with the **activities** that the file is not synced to local. I try to detect that. Please double check.

**Comment by ckamm** [comment]
@guruz This also works for me. Where did you see this not working?

**Comment by guruz** [comment]
Works for me neither on Windows nor OS X with a file that is "You created .."

Also why should it be on single-click, single click should just select the table row? (and does that for me)

For hilighting the file in Finder on OS X see also: https://github.com/owncloud/client/blob/master/admin/osx/post_install.sh.cmake#L7

@Dianafg76 what about you?

**Comment by Dianafg76** [comment]
@guruz This also works for me, on Mac and Windows

**Comment by guruz** [comment]
^^ FYI

**Comment by Dianafg76** [comment]
I tested this issue, and is working OK
Desktop v ownCloud-2.1.0.2907-nightly20151125.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

Closed
