### ISSUE TITLE
[Share with users, groups] If you have disabled the Share API in the server, the desktop client you should see the error "The server does not allow sharing"

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4170]
### Steps to reproduce
1. Go to the Desktop client with v2.1.0 with user1
2. Go to Open Folder "..."
3. Create a new folder (e.g. kkk)
4. Right click on the folder kkk
5. Select the option Shared with oC
6. You can share with user2
7. Go to the Server Web with Admin
8. Click on Admin/admin
9. Disable the option Share API 
![screen shot 2015-11-20 at 09 45 51](https://cloud.githubusercontent.com/assets/12032058/11296773/761156fa-8f74-11e5-925e-1c4b11df8b8d.png)
10. Go to the Desktop cliente with user1
11. Create a New Folder (e.g lll)
12. Right click on the folder lll
13. Select the option Share with oC

### Expected behaviour
on the two users should see the error "The server does not allow sharing"

### Actual behaviour
And I can share with other user 
![screen shot 2015-11-20 at 10 54 27](https://cloud.githubusercontent.com/assets/12032058/11296886/1d6a4448-8f75-11e5-86a2-28bdd3c3be84.png)

But, If I go to the Desktop client for the user2, I created a new folder (e.g. nkj) and I go to Share with user and groups I can't share. I see this error
![screen shot 2015-11-20 at 10 25 33](https://cloud.githubusercontent.com/assets/12032058/11296899/3acb3024-8f75-11e5-8109-762f649e518a.png)

### Server configuration
Desktop v ownCloud-2.1.0.2896-nightly20151120.pkg
Server v{"installed":true,"maintenance":false,"version":"8.2.1.1","versionstring":"8.2.1 RC2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
related #4126

**Comment by rullzer** [comment]
Does it work if you restart the client?

This could be related to the fact that we query the capabilities on login.

**Comment by Dianafg76** [comment]
When I restart the client is working OK, Thanks you @rullzer 

Desktop v ownCloud-2.1.0.2907-nightly20151125.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

Closed
