### ISSUE TITLE
owncloudcmd loops forever if stderr is redirected

### ISSUE THREAD

**Issue by johanehnberg** [owncloud/client#4171]
In an attempt to script with owncloudcmd I stumbled upon three challenges:
1) owncloudcmd's -s is still very noisy, and no more silence levels are available
2) owncloudcmd sends its activity output to stderr rather than stdout
3) owncloudcmd loops forever, creating a huge (~1MB/sec) "logfile" if stderr redirection is used

While 1) and 2) may be features, I believe 3) is an unintended issue. And together they make a sysadmin pull his hair out :)

So, focusing on 3), to test it out, run:
owncloudcmd --non-interactive -u USERNAME -p PASSWORD TESTDIR https://YOUROWNCLOUD/remote.php/webdav/TESTDIR 2> log

This will never finish, and the log file keeps growing. In between the runs, the following messages are found in the log:
void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "All Finished."  
CSync run took  95 
virtual OCC::BandwidthManager::~BandwidthManager() 
Restarting Sync, because another sync is needed 
void OCC::SyncJournalDb::close() "/home/johan/.csync_journal.db" 
No database Transaction to commit 
Set proxy configuration to use system configuration 

Without '2> log' it finishes after one run with ~250 lines of output with a few files in the test directory.

**Comment by lipido** [comment]
I have the same issue, but if I remove the 2> log, the infinite loop does not stop either.

**Comment by johanehnberg** [comment]
It would seem owncloudcmd 2.1.0 fixes this issue.

**Comment by ckamm** [comment]
@johanehnberg Thanks for following up on this! Feel free to reopen if you still experience the problem.
