### ISSUE TITLE
Sync items disappeared after client update

### ISSUE THREAD

**Issue by sasagit** [owncloud/client#4172]
After updating to version 2.0.2 folder sync items were removed

**Comment by RealRancor** [comment]
@sasagit Known bug which was already fixed: https://github.com/owncloud/client/issues/3747 , https://github.com/owncloud/client/issues/4012 , https://github.com/owncloud/client/issues/4015

https://forum.owncloud.org/viewtopic.php?f=14&t=31191

I think you can close this issue on your own.

**Comment by guruz** [comment]
Also closing as dup of https://github.com/owncloud/client/issues/4173 by @sasagit
