### ISSUE TITLE
[Windows] Automated syncing of new and changed files in subfolders of syncing directory is not working on network drives and windows client

### ISSUE THREAD

**Issue by wondalfo** [owncloud/client#4175]
Things to reproduce
0.) Windows desktop client and local folder on Network drive with drive letter
1.) create a subfolder in the local folder --> subfolder is synced to cloud
2.) create a file in subfolder --> file is synced
3.) shutdown client
4.) start client and wait until first syncronisation is done
5.) create a new file in subfolder --> file is not synced, but should be
6.) wait some minutes
7.) create a file in the local folder (root) --> file is synced and additionally all new and changed files in subfolders are synced, too

**Comment by guruz** [comment]
Which version of the client?

@danimo File watching?
