### ISSUE TITLE
pause sync menu item triggers selective folders open/close

### ISSUE THREAD

**Issue by r2evans** [owncloud/client#4176]
It's a simple UI bug, but is it possible to *not* open/close the folder sync list when pausing/resuming sync?

### Expected behaviour
When pausing/resuming sync, it should not affect other UI elements.

### Actual behaviour
... it opens/closes the selective-folder sync list.

### Steps to reproduce
1. Open the desktop window, select an account.
2. Click on the `...` and click on "Pause sync" (or "Resume sync").
3. The selective-folder-sync portion toggles state.

### Client configuration
Client version: 2.0.2 (build 5569)

Operating system: win10_64

OS language: EN

Installation path of client: `c:\Program Files (x86)\ownCloud\ownCloud.exe`

**Comment by guruz** [comment]
I believe we changes quite some code here for 2.1beta1. Could you try that?

**Comment by ckamm** [comment]
@r2evans I'm pretty sure i fixed that for 2.1, could you test?

**Comment by r2evans** [comment]
Yes you did, thanks!
