### ISSUE TITLE
Add Pause-Entry to tray icon context menu

### ISSUE THREAD

**Issue by hannesN** [owncloud/client#4177]
HI,

I'm pausing the syncronization, while I am working on data. Right now, I have to open the window and use the context menu of the account. It would be nice to have a context menu, where it is possible to toggle the pause state.
Somthing like:

    Accounts -> Pause Account-Name
    Accounts -> Sync Account-Name

**Comment by guruz** [comment]
Dup of https://github.com/owncloud/client/issues/3829#issuecomment-158693658 with nice screenshot from @r2evans
