### ISSUE TITLE
Ubuntu: size mismatch libqtkeychain0  - Add this bash script to a tutorial how to install owncloud-client on ubuntu 

### ISSUE THREAD

**Issue by codebucketdev** [owncloud/client#4178]
Hello,

I had a problem over the last 2 weeks how to run owncloud-client on a Ubuntu 14.04 LTS machine and every time I tried to install the packages, I got a size mismatch from the package libqtkeychain0. So finally I found out how to install libqtkeychain0 from the Debian unstable repository and wrote a script to make the installation easier. Now I want to share it with you guys, as it would help many users to fix their problem with the installation of the latest version of owncloud-client.

Here is the script (runs well on every Ubuntu version):
```
#!/bin/bash
if [ "$(id -u)" != "0" ]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi
 
MACHINE_TYPE=$(uname -m)
if [ ${MACHINE_TYPE} == 'x86_64' ]; then
   OS_ARCH='amd64'
else
   OS_ARCH='i386'
fi
 
echo ':: Downloading libqtkeychain0'
wget -O /tmp/libqtkeychain0_0.5.0-1.deb 'http://ftp.de.debian.org/debian/pool/main/q/qtkeychain/libqtkeychain0_0.5.0-1_'$OS_ARCH'.deb'
 
echo ':: Installing libqtkeychain0'
dpkg -i /tmp/libqtkeychain0_0.5.0-1.deb
 
OS_VERSION=$(lsb_release -sr)
 
echo ':: Installing repo key'
wget -O- 'http://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_'$OS_VERSION'/Release.key' | apt-key add -
 
echo ':: Adding repo entry'
echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_'$OS_VERSION'/ /' > /etc/apt/sources.list.d/owncloud-client.list
 
echo ':: Updating lists'
apt-get update
 
echo ':: Installing packages'
apt-get install owncloud-client -y
 
echo ':: Performing cleanup'
rm /tmp/libqtkeychain0_0.5.0-1.deb
rm -R /var/cache/apt/archives/*
apt-get autoclean
apt-get clean
 
owncloud&
```

Have a nice day,
David aka. Codebucket

**Comment by guruz** [comment]
@dragotin @jnweiger Maybe we should bundle libqtkeychain instead?

FYI @frankosterfeld

**Comment by codebucketdev** [comment]
@guruz Thanks for adding it as a Known Issue / Workaround :+1:

**Comment by edvapp** [comment]
@codebucketdev: 
Thanks for finding the error and providing your script. 
Costed me one day of searching and trying.
I could install owncloud-client on a Kubuntu 15.10, but on Ubuntu 14.04 no chance, even when trying all repositories.
@guruz:
Will the repository at "deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.04/" be repaired?

**Comment by codebucketdev** [comment]
@edvapp:
No problem, it took me 2 weeks on the university to find a solution, because we work on machines with Ubuntu as a live system, so we can use root and install what we want or need, but after a reboot everything is gone. So after I found a fix, I made this script and put it into .bash_rc and now everytime I log in, the ownCloud client will be installed properly and started :smile:

I already sent a mail to the openSUSE repositoty maintainers, but they haven't replied yet.

@guruz:
I think a better solution would be to bundle owncloud-client with the needed libraries or to create an own apt repository with these packages. I would like to have a owncloud repository instead of the broken and badly maintained openSUSE repository.

```
deb http://apt.owncloud.org/repositories/xUbuntu14.04/ debian stable
```
Or something like that :)

**Comment by dragotin** [comment]
So I think this issue was (or is) caused by a broken libqtkeychain package on any of the mirrors of the openSUSE infrastructure. That can happen, but is rare.  We can notify the mirror maintainers to remove the broken package and let is resync. But that is no conceptional weakness, but an temporary error.

Setting up our own apt repo seems like a solution but its not. We neither have people nor hardware to maintain that.

What, however, would help: If there was somebody volunteering from the community to maintain the client package in an ppa on launchpad, that would be a more natural way probably. But so far nobody has stepped up.

**Comment by dragotin** [comment]
@jnweiger FYI

**Comment by edvapp** [comment]
@codebucketdev:
2 weeks! That really hurts.
It looks like you are interested in scripts. 
I "collected" a lot of scripts to handle automated ubuntu installations for servers and clients in: 
https://github.com/edvapp/networkbox
https://github.com/edvapp/autoinstall

**Comment by jnweiger** [comment]
I suggest we use DEBTRANSFORM-RELEASE as described in 
https://github.com/openSUSE/open-build-service/issues/745 and
https://github.com/openSUSE/obs-build/pull/147

**Comment by jnweiger** [comment]
I've manually incremented the buildrelease numbers of our isv:ownCloud:desktop/{owncloud-client,qtkeychain,qt5keychain} packages.

@codebucketdev this should flush the caches of your mirrors eventually. 
The next apt-get update should give you qtkeychain 0.5-1 (instead of 0.5-0) 
As soon as you see this, owncloud should be installable again.

**Comment by edvapp** [comment]
@jnweiger:
Tested repository for Ubuntu 14.04 amd and it is WORKING!
Repository is not ignored any more.
@codebucketdev:
We will miss a nice script, which we do not need any more :-( (at the moment ;-)
