### ISSUE TITLE
[Share link] If you disallow users to share via link on the Server, on the Desktop client you can select the option Share link

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4179]
### Steps to reproduce
1. Go to the Desktop Client with v 2.1.0 with user1
2. Go to the Server web with admin
3. Go to the Admin/Sharing
4. Disallow users to share via link
![screen shot 2015-11-23 at 10 56 44](https://cloud.githubusercontent.com/assets/12032058/11333837/f4e212b8-91d0-11e5-9055-154e796e0c37.png)
5. Go to the Desktop Client with user1
6. Create a new folder (eg. disallow share via link)
7. Right click on the folder "disallow share via link"
8. Select the option Share with oC

### Expected behaviour
The Share link option should not see

### Actual behaviour
You can select the option "Share link"
And You can seethis screen

![screen shot 2015-11-23 at 10 51 30](https://cloud.githubusercontent.com/assets/12032058/11333976/175d3ca4-91d2-11e5-959d-42ef95cb944d.png)

### Server configuration
Desktop v ownCloud-2.1.0.2904-nightly20151123.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.2.1.3","versionstring":"8.2.1 RC4","edition":"Enterprise"}

**Comment by ckamm** [comment]
The 'Share link' checkbox should now be disabled if the link-share capability is disabled.

**Comment by Dianafg76** [comment]
I tested this issue and I can see the same screen
![screen shot 2015-11-25 at 08 45 18](https://cloud.githubusercontent.com/assets/12032058/11391217/04ba6ccc-9351-11e5-8636-4fa178ea7486.png)

![screen shot 2015-11-25 at 08 46 40](https://cloud.githubusercontent.com/assets/12032058/11391225/14aca6d6-9351-11e5-9f70-18d1c69d1464.png)

**Comment by ckamm** [comment]
@Dianafg76 Since it works for me: Did you restart the client after you changed the server settings? The client reads the account capabilities only once.

**Comment by Dianafg76** [comment]
@ckamm I tested again, and now when I restart the client is working OK
Thank you

Desktop v ownCloud-2.1.0.2907-nightly20151125.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

Closed
