### ISSUE TITLE
broken webserver returning empty content length for non-empty file on resume

### ISSUE THREAD

**Issue by GCC01Rwichmann** [owncloud/client#4181]
Hello,
we get the error message above during sync.
Owncloud is 8.14.
Plese see the screeshot, any idea?
thanks
roland
![bildschirmfoto 2015-11-23 um 10 58 16 2](https://cloud.githubusercontent.com/assets/15978911/11334951/d465d67a-91d8-11e5-8b42-e899ee174b90.png)

**Comment by terokorp** [comment]
I have same problem. I'm not absolutely sure, but I think this problem appears when when merging folders where is same files. Only way to "fix" this problem (as user) is move problematic file outside of sync folder, wait for deletion and then put it back.

**Comment by guruz** [comment]
Which version are you using?
Please check the duplicates, most likely a problem with encryption

https://github.com/owncloud/client/search?q=Broken+webserver&type=Issues&utf8=%E2%9C%93
