### ISSUE TITLE
Rebuilding client database (F5) downloads ignored files/folders

### ISSUE THREAD

**Issue by terokorp** [owncloud/client#4182]
### Expected behaviour
When using selective sync and pressing F5 to rebuild client database, client supposed to rebuild database, no downloads because everything is already on sync.

### Actual behaviour
When using selective sync and pressing F5 to rebuild client database, clients rebuilds database and starts download ignored files and folders.
Expanding folder selections and pressing apply will stop sync and deleting ignored files.

### Steps to reproduce
1. Create folder and add something to it
2.  Wait for sync
3.  add created folder to "choose what to sync" blacklist
4. wait for deletion
5. Press F5 on client to start database rebuild
6. Now client downloads blacklisted folder. This doesn’t supposed to happen.
7. Open selective sync folder selection, make edit and undo it to enable "apply" button
8. Click apply
9. Now client deletes that blacklisted folder which doesn’t supposed to be there anyway.

### Server configuration
Operating system:
Debian 8.2

Web server: 
Apache 2.4

Database:
mysql  Ver 14.14 Distrib 5.5.44, for debian-linux-gnu (x86_64) using readline 6.3

PHP version:
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 01:34:46) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with Xdebug v2.2.3, Copyright (c) 2002-2013, by Derick Rethans

ownCloud version:
ownCloud 8.2.1 (stable)

Storage backend:
local, with encyption, APCu and Redis

### Client configuration
Client version: Version 2.0.2 Git-revision 78d782 Nov 19 2015, 11:29:57 käyttäen Qt:n versiota 4.8.6, OpenSSL 1.0.1f 6 Jan 2014

Operating system: 
Linux Mint 17.2. 'Rafaela'

OS language:
FI

Installation path of client:
default with apt-get

### Logs
http://pastebin.com/x8dpQ66F

**Comment by guruz** [comment]
I suspect this is because of the list being also stored in the DB?

**Comment by ogoffart** [comment]
F5 should never be pressed.

It was there to work around issue that happened some years ago but are now long fixed.

I guess we should remove this shortcut to avoid people pressing it by mistake.  @dragotin , what do you think?

**Comment by guruz** [comment]
Not a bug then, removing from milestone

**Comment by ogoffart** [comment]
The feature is removed in 2.2
