### ISSUE TITLE
If the URL you define user and password should not be possible to change the password  If a user enters a server URL in the form of https://user:pass@example.com/, the user/pass should not be possible to change on the screen Enter user credentials

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4183]
### Steps to reproduce
1. Go to the Desktop client v2.1.0
2. Right click on the oC icon
3. Click on Settings...
4. Select one account
5. Click on Account
6. Click on Add new
7. Add the Server address (https://user:pass@example.com/)
8. Click on Next

### Expected behaviour
It should not be possible to change the password

### Actual behaviour
![screen shot 2015-11-23 at 15 28 10](https://cloud.githubusercontent.com/assets/12032058/11338882/e7029ed0-91f6-11e5-8fa7-c652547c2a51.png)
You can change the name and the Password
![screen shot 2015-11-23 at 15 29 19](https://cloud.githubusercontent.com/assets/12032058/11338898/03a95358-91f7-11e5-8fbc-752def360667.png)

### Server configuration
Desktop v ownCloud-2.1.0.2904-nightly20151123.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.2.1.3","versionstring":"8.2.1 RC4","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
related #4100

**Comment by guruz** [comment]
I don't think I agree. Is that a requirement @MTRichards @rperezb ?

**Comment by MTRichards** [comment]
Not from me, not sure if / where it comes from.
If you do the URL entry I would think that it should just pre-populate, not lock the username password....

**Comment by rperezb** [comment]
Not, this is not a requirement.
@Dianafg76 is checking this feature and thought it could be the expected behavior.
Agreed from my end, it should be possible to edit, as it is
