### ISSUE TITLE
[Cinnamon Mint] tray icon missing after logout/login

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#4184]
I have installed 2.0.2 on MintLinux,with cinnamon desktop.

After logging out the user and logging in again, the owncloud client is automatically restarted. I can see a new pid in the ps listing.
The parent process ID of owncloud is cinnamon-session in this case. Most often, the tray icon is missing then. To verify that there is a race condition, I replaced /usr/bin/owncloud with a shell script like this:
<pre>
#! /bin/sh
echo $0: delay 3 seconds...
sleep 3
exec /usr/bin/owncloud.bin "$@"
</pre>

With this workaround, I reliably get a tray icon.

**Comment by mlopezcoria** [comment]
It's not just a Linux Mint bug, but a Cinnamon desktop one. I use Fedora 23 Cinnamon Spin and also have the same issue.

**Comment by ogoffart** [comment]
What's the version of Qt?  and what's the protocol used for the systemtray there? is it the X11embed or is it a dbus protocol, which one?

**Comment by mlopezcoria** [comment]
qt-4.8.7-5 
I don't kwow how to get the protocol information you ask. I use Fedora 23 Cinnamon Spin
Thanks

**Comment by dragotin** [comment]
hm, please work with downstream on this topic, either with Fedora or the Cinnamon people. Thanks!
