### ISSUE TITLE
[Share with users, groups] error OCS API error code: 0, when the server connection is down

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4185]
### Steps to reproduce
1. Access to the Desktop client
2. Select to share a file
3. The server connection is down
4. Select to look for the user
5. Share the folder/file with user win

### Expected behaviour
the error should not appear

### Actual behaviour
You can this error: OCS API error code: 0,
![screen shot 2015-11-24 at 11 33 07](https://cloud.githubusercontent.com/assets/12032058/11364272/9bb63118-929f-11e5-947e-1aac82141af7.png)

### Server configuration
Desktop v ownCloud-2.1.0.5649-nightly20151124-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

**Comment by dragotin** [comment]
If the server connection is down, we should not provide the sharing functionality at all.

**Comment by rullzer** [comment]
PR with fix in #4493

**Comment by Dianafg76** [comment]
I tested this issue and now is working ok. When the server connection is down the error does not appear
![screen shot 2016-03-01 at 08 49 12](https://cloud.githubusercontent.com/assets/12032058/13420971/0003c1de-df8b-11e5-8a43-72a360da644d.png)
