### ISSUE TITLE
[Share with users, groups] If you enable the "Exclude action groups " option and add a group works differently on Windows than on Mac

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4186]
### Steps to reproduce
1. Go to the Server web with Admin
2. Click on Admin/admin
3. Enable the option "Exclude groups from sharing"
4. Introduce  the name of the group (e.g numbers and letters ( on the group include the user 1a)
5. Go to the desktop client with user 1a
6. Create a new folder/file
7. Right click on the new folder
8. Click on Share with oC

### Actual behaviour
On Windows you can share the folder 
![screen shot 2015-11-24 at 12 28 06](https://cloud.githubusercontent.com/assets/12032058/11365716/8da927f2-92a8-11e5-9ba0-f8249fedb864.png)
But on MAC you can't share the folder
![screen shot 2015-11-24 at 12 28 15](https://cloud.githubusercontent.com/assets/12032058/11365741/d6e827c4-92a8-11e5-8c33-e6070ab5e519.png)

### Server configuration
Desktop v ownCloud-2.1.0.5649-nightly20151124-setup.exe, ownCloud-2.1.0.5649-nightly20151124-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

**Comment by rullzer** [comment]
Mmmm I do not get why they would behave differently.

Did you start the windows client perhaps before you made the changes in the webinterface?

**Comment by Dianafg76** [comment]
@rullzer Did you start the windows client perhaps before you made the changes in the webinterface? No, I start the windows first

**Comment by ckamm** [comment]
@Dianafg76 I think you might accidentally be using different client versions here: one shows the folder the target folder is in and the other doesn't. Can you verify they are identical?

**Comment by Dianafg76** [comment]
@ckamm 
It's the same with version Desktop v ownCloud-2.1.0.2956-nightly20151209.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

**Comment by ogoffart** [comment]
If you started first, it might have been started before the change was made in the web interface.  Can you try again?

**Comment by Dianafg76** [comment]
@ckamm @ogoffart It's the same with v ownCloud-2.1.1.2983-nightly20151223.pkg, ownCloud-2.1.1.5722-nightly20151223-setup.exe

I see this Logs on my Windows
```
12-23 08:56:32:310 0x44e1430 OCC::SocketApi::command_SHARE: void OCC::SocketApi::command_SHARE(const QString&, QIODevice*) "C:\Users\Administrador\nuevofolder\BUG4186"
12-23 08:56:32:326 0x44e1430 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE:OK:C:\Users\Administrador\nuevofolder\BUG4186"
12-23 08:56:32:326 0x44e1430 OCC::ownCloudGui::slotShowShareDialog: void OCC::ownCloudGui::slotShowShareDialog(const QString&, const QString&, bool) Opening share dialog "/\BUG4186" "C:\Users\Administrador\nuevofolder\BUG4186"
12-23 08:56:32:326 0x44e1430 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "https://docker.oc.solidgear.es" + "ocs/v1.php/apps/files_sharing/api/v1/shares"
12-23 08:56:32:326 0x44e1430 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "https://docker.oc.solidgear.es" + "ocs/v1.php/apps/files_sharing/api/v1/shares"
12-23 08:56:32:341 0x44e1430 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (No se encontró el proceso especificado.)
12-23 08:56:32:341 0x44e1430 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

12-23 08:56:32:341 0x44e1430 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
12-23 08:56:32:357 0x44e1430 OCC::SocketApi::onLostConnection: SocketApi:  Lost connection  QLocalSocket(0xa0aa330)
12-23 08:56:32:560 0x44e1430 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap&) "8.2.2.2" Fetched 0 shares
12-23 08:56:32:560 0x44e1430 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap&) Sending  0 shares
12-23 08:56:32:560 0x44e1430 OCC::ShareLinkWidget::slotSharesFetched: void OCC::ShareLinkWidget::slotSharesFetched(const QList<QSharedPointer<OCC::Share> >&) "8.2.2.2" Fetched 0 shares
12-23 08:56:32:654 0x44e1430 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap&) "8.2.2.2" Fetched 0 shares
12-23 08:56:32:654 0x44e1430 OCC::ShareManager::slotSharesFetched: void OCC::ShareManager::slotSharesFetched(const QVariantMap&) Sending  0 shares
12-23 08:56:37:560 0x9ef1418 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x9ef1528) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
```

**Comment by dragotin** [comment]
ok,  so this means there was a network error somehow:
```
12-23 08:56:37:560 0x9ef1418 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x9ef1528) QObject(0x0)  0 false 3 0 QAbstractSocket::ConnectedState
```
@guruz do you have an idea? Or is it just a normal network temporary fail?

**Comment by guruz** [comment]
```Fetched 0 shares``` ?

@dragotin Yep, not an error. We still need to remove this debug from the Qt builds.

**Comment by rullzer** [comment]
> ```Fetched 0 shares``` ?

Yes that can be if there are no shares ;)

**Comment by rullzer** [comment]
I still have no idea why this is happening...

**Comment by rullzer** [comment]
@Dianafg76 can you verify this is still happening... I have just looked trough the code again and I can find not a single reason why windows would fail.

**Comment by Dianafg76** [comment]
@rullzer I tested again the issue, and now is working OK
Desktop v 2.1.1 (build 5765)
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}
