### ISSUE TITLE
"Choose what to sync" does not expand folder

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#4187]
When I click "Choose what to sync" in the folder context menu, the selective sync folder list briefly comes up but hides again immediately.

Single-clicking a folder also no longer expands it, but I'm not sure whether that's intentional or not.

**Comment by Dianafg76** [comment]
I tested this issue and now when you are click on "Choose what to sync" the folder is expands
Desktop v ownCloud-2.1.0.2907-nightly20151125.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

Closed
