### ISSUE TITLE
If you have configured 5 or more accounts, you can't see the ACTIVITY option

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4188]
### Steps to reproduce
1. Go to the Desktop client with v2.1 with user1
2. Go to Setting options
3. Click on the user1
4. Click on ACCOUNT
5. Click on ADD NOW
6. Add five more accounts (e.g. user2, user3, user4...)
7. Click on >>

### Expected behaviour
You shoulb see the ACTIVITY option

### Actual behaviour
You can't see the ACTIVITY option
![screen shot 2015-11-24 at 13 10 53](https://cloud.githubusercontent.com/assets/12032058/11366342/04091570-92ad-11e5-8306-bf5eb93103e8.png)

### Server configuration
Desktop v ownCloud-2.1.0.5649-nightly20151124-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

**Comment by guruz** [comment]
So it is not in the little menu? Strange..

Also compare to https://github.com/owncloud/client/issues/3795

**Comment by Dianafg76** [comment]
I tested this issue, and now is working OK
Desktop v ownCloud-2.1.0.5662-nightly20151127-setup.exe
Closed

**Comment by Dianafg76** [comment]
Sorry, is not working
Desktop v ownCloud-2.1.0.5662-nightly20151127-setup.exe

**Comment by ckamm** [comment]
I can reproduce it on linux

**Comment by Dianafg76** [comment]
I tested this issue and now is working ok
Desktop v ownCloud-2.1.0.5699-nightly20151211-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}
Closed
