### ISSUE TITLE
[Share with users, groups] You can see a little line when you click on the Delete Button

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4189]
### Steps to reproduce
1. Install the Desktop v 2.1.0 with user1
2. Open your ownCloud desktop client
3. Go to Open Folder "ownCloud"
4. Create a new folder, called aaa
5. Right click on the folder aaa
6. Select share with ownCloud
7. Write the name of the user to share (e.g user2)
8. Click on the Delete Button

### Expected behaviour
You should see the little line

### Actual behaviour
You can see a little line when you click on the Delete Button (On Windows)
![screen shot 2015-11-24 at 13 28 02](https://cloud.githubusercontent.com/assets/12032058/11366706/464f15e0-92af-11e5-8f36-bd6eb20c7df4.png)
On MAC also
![screen shot 2015-11-24 at 13 46 49](https://cloud.githubusercontent.com/assets/12032058/11367123/f373d376-92b1-11e5-9fbc-cf243487e98a.png)

### Server configuration
Desktop v ownCloud-2.1.0.5649-nightly20151124-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

**Comment by ckamm** [comment]
This seems to be a Qt drawing bug. The widget is deleted correctly and doing something like resizing the window will make the spurious line go away.

**Comment by Dianafg76** [comment]
I tested this issue, and now is working OK
Desktop v ownCloud-2.1.0.5655-nightly20151126-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

Closed
