### ISSUE TITLE
Owncloud client sync folders lost after updating to 2.0.2 windows client

### ISSUE THREAD

**Issue by haroldsnippert** [owncloud/client#4190]
20 out of 22 owncloud clients lose their sync folders after autoupdate.

I administer 3 owncloud servers, approximately 200 users.
Most of them connect using webdav (mostly ipads running goodreader, iannotate) 
a couple also are using the owncloud app.

Around 20 people use the owncloud client on windows pc.
All of those clients experienced update problems. hardly no exception, just 2 clients went ok..
After automated owncloud client update to 2.0.2, the sync folders where gone.
Most of those users don't use the standard owncloud folder location.

Clients are on windows 7, 8.1 and 10. Language Dutch and English.
Clients came from 1.8.4, 2.0 and 2.1
5 clients have connected their owncloud client to multiple owncloud servers, alle accounts missed their folders

Owncloud servers are running on ubuntu, all are on version 8.1.3
clients are on latest ms updates, 60% using eset antivirus, the rest microsoft defender.

I tried to check the problem further, did manual update from within the client.
made backup from client config first
Updated a client from 1.8.5 tot 2.0.2, no folders after update. before, it had 30 sync folders configured.
restored version 1.8.5, including config files, working immediately, including sync folders
now updated tot 2.0, sync folders in place, updated tot 2.0.2, folders gone.
restores 2.0 client, restored config, working immediately
then updated to 2.0.2, all folders working. finally.

i did check the owncloud server to see which clients hadn't synchronized their files lately.
did check with those users, all of them had sync clients with broken config. no sync folders.
the account are working, just no folders.
i fixed almost all of the clients, had at least 12 users with problems, some 8 to go.

problem is also that there's no red exclamation mark, just a bit greyed out mark.
so users are not aware that there sync is not working.

so i can reproduce. how to procede?

**Comment by danimo** [comment]
This was an unavoidable issue in the updater code related to incomplete flush of config files during upgrades. We've already fixed this in 2.0.2, so the next upgrades will not suffer from this problem.
