### ISSUE TITLE
choose what to sync menu slow

### ISSUE THREAD

**Issue by animalillo** [owncloud/client#4191]
When you click on any of the remote folder selectors, the dialog takes ages to load the remote folder list.

I've tried it on windows and ubuntu.

My latest try was with ubuntu 15.10 client version: 1.8.1+dfsg+1ubuntu1 (git ee71024496d25e1392080a5ad2a17113bcd2e27a)

**Comment by guruz** [comment]
Which server version?
Do you use external storage on the server?

**Comment by guruz** [comment]
Also 1.8.1 is way too old.

Please check https://owncloud.org/support/ for further support options.

**Comment by animalillo** [comment]
I've updated to V 2.0.2 and I still have the same issue (Revisión Git 78d782 en Nov 19 2015, 11:34:31 compilada usando Qt 4.8.6, OpenSSL 1.0.2d 9 Jul 2015)

Server version: 8.1.1 (stable)

**Comment by danimo** [comment]
@animalillo All the client does is asking the server for its top level folder structure. This is likely caused by slow folders. Are you using external storage?

**Comment by animalillo** [comment]
No, no external storage module is in use

**Comment by danimo** [comment]
@animalillo What about the amount of folders, structure, etc?  Please use a webdav client and try to list the directory that the client tries to list (ususally the user's root dir). Check if the times are comparable.

**Comment by guruz** [comment]
The server is at 8.1.4 for the 8.1 series
https://owncloud.org/changelog/

**Comment by animalillo** [comment]
Yes, it seems to be slow accessing via webdav too.

I have 6007 directories, including subdirectories in this account. The root folder  has just 37 directories on it.

**Comment by danimo** [comment]
@animalillo Ok, people file the issue with the core component then. There is nothing we can do to improve the situation in the client.
