### ISSUE TITLE
Access is denied error on sync

### ISSUE THREAD

**Issue by acwatkins** [owncloud/client#4192]
### Expected behaviour
Should push files up to the server and report synced

### Actual behaviour
Files are uploaded to the server, however, a random set of files reports an error that wont go away by itself, Access is denied.  Removing the folder removes the error, readding the folder causes a random other subset of files to report the problem (not the same number all the time.)

Workaround:
Delete the files complained about and their hidden counterparts and it pulls down the ones on the server and stops complaining.

### Steps to reproduce
1. Upload large folder (1152 files, combination of pictures and xmps)
2. Wait for it to sync most and fail on others
3. ...

### Server configuration
Operating system:
Server: Debian Linux 8
Client: Windows 10

Web server: 
Apache2

Database:
MySql

PHP version:
5.6.14

ownCloud version:
Server: 7.0.4+dfsg-4~deb8u3 (Debian stable package)

Storage backend:
BTRFS

### Client configuration
Client version:
2.0.2 (build 2818)

Operating system:
Windows 10

OS language:
English

Installation path of client:
C:\Program Files (x86)\ownCloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )
Pictures/archive/2014/2014-05-10/20140510-366.CR2 | ownCloud | Access is denied | 22 MB

2. Web server error log:

3. ownCloud log (data/owncloud.log):
No errors on the server /var/log/owncloud.log

**Comment by danimo** [comment]
7.0.4 is no longer supported Please update to a current server version, see https://owncloud.org/install/#instructions-server
