### ISSUE TITLE
Sync client worker threads(?) attempt to upload same file twice = SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry

### ISSUE THREAD

**Issue by ljsjl** [owncloud/client#4196]
There are a few issues in core concerning this error, but the cause in this case looks to be different.

### Expected behaviour
Files are uploaded without error messages. Seems so simple doesn't it ;)

### Actual behaviour
Every so often, say once every 3000 files or so, the client pops up a message like "Error downloading <URL> server replied: Internal Server Error (An exception occurred while executing 'INSERT INTO `oc_filecache` (`mimepart`,`mimetype`,`mtime`,`size`,`etag`,`storage_mtime`,`permissions`,`parent`,`path_hash`,`path`,`name`,`storage`) SELECT ?,?,?,?,?,?,?,?,?,?,?,? FROM `oc_filecache` WHERE `storage` = ? AND `path_hash` = ? HAVING COUNT(*) = 0' with params ["9", "57", 1448423841, 37383, "d056fe16ddd069fde5eb4e453d5c3a99", 1448423841, 27, "26366541", "745d490480d9b770da927482a8d9d171", "files\/random\/Aa8tlt\/bdHdiY\/HIzDsF\/Ho2Fvv\/cltzQt\/d8ECmO\/IofnoK\/12", "12", "15", "15", "745d490480d9b770da927482a8d9d171"]: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '15-745d490480d9b770da927482a8d9d171' for key 'fs_storage_path_hash')37 KB

### Steps to reproduce
1. Generate 10,000-20,000 (or more!) small files (<64KiB in this case, but same behaviour with larger files) in a random directory tree (in this case depth up to 8 and branching factor up to 15, but that doesn't really matter)
2. Kick off the sync client

## More info
The file generating the error is in fact uploaded correctly, and the correct database entry exists in oc_filecache. This SQL error is generated if you attempt to insert a row with the same key id as an existing row and a unique key constraint is in place, so that made me think maybe the client was attempting to upload the same file twice in quick succession.  So I turned on the mysql general log.

Looking in the sql log I can see two concurrent connections from the sync client that both attempt to upload the same file. Their queries are intermingled and they both attempt to insert a row for the file in question into oc_filecache.

I'm guessing that the sync client uses a queue of some sort and worker threads to handle uploads, and it seems there's some sort of race or inadequate locking in there somewhere, where another worker can grab a queued upload before the previous worker (which also acquired that upload) can remove it from the queue? I'm not familiar with the actual plumbing in the client.

### Server configuration
Operating system:  Ubuntu 14.04.3

Web server: HAProxy +Nginx + PHP-FPM w/ APCu & Redis

Database: MariaDB 5.5 w/ Galera

PHP version: 5.5.9

ownCloud version: 8.1.4 w/ transaction locking enabled

Storage backend: GlusterFS

### Client configuration
Client version: 2.0.2

Operating system: Ubuntu 14.04.3

OS language: English

Installation path of client: /usr/bin/owncloud

### Logs

https://gist.github.com/ljsjl/2200c7aaecaedfcbc52a#file-gistfile1-txt

**Comment by guruz** [comment]
Hi,
Please submit this at the ```core``` bugtracker. 
https://github.com/owncloud/core/issues/ (look for duplicates first)

FYI @icewind1991 @PVince81 ``` Integrity constraint violation: 1062 Duplicate entry '15-745d490480d9b770da927482a8d9d171' for key 'fs_storage_path_hash')```
