### ISSUE TITLE
Credentials Dialog too wide 

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4197]
The dialog that asks for the password that comes up if the keychain could not be opened looks ugly because it is very wide. The error message is not folded.

Code: `HttpCredentialsGui::askFromUserAsync()`, _fetchErrorString needs to have newlines added.

**Comment by Dianafg76** [comment]
@ogoffart I tested this issue and on my windows is working OK
Desktop v ownCloud-2.1.1.5722-nightly20151223-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}
