### ISSUE TITLE
Test Windows 10 Treshold 2 update

### ISSUE THREAD

**Issue by danimo** [owncloud/client#4200]
There are reports that Windows 10 Treshold 2, the first update to Windows 10, performs a copy of the users home directory, but does not include the ownCloud data directory. This needs verification.

The following scenario needs testing.

* Obtain a goldmaster ISO of Windows 10 final
* Install ownCloud Client
* Update to Treshold 2
* Check if the user directory has been copied (``C:\users\user.000``) and the ownCloud data directory is part of that copy.

**Comment by guruz** [comment]
@danimo Maybe even 2.1.1-next?

**Comment by guruz** [comment]
@danimo I'll close this as we haven't heard any complaints (and threshold 2 is out)
