### ISSUE TITLE
Mac text clippings don't get synced

### ISSUE THREAD

**Issue by DavidJameson** [owncloud/client#4203]
I mentioned this on the forums a while back but no response there.

I've discovered that the content of Mac text.clippings don't get sync'd. In particular, a file with the correct name shows up on other machines but it always has 0 bytes in it.

Latest OwnCloud server, latest OwnCloud client, at the time of writing this.

**Comment by guruz** [comment]
Could you find out if this a resource fork or bundle and then commet on https://github.com/owncloud/client/issues/3202 or https://github.com/owncloud/client/issues/3497
