### ISSUE TITLE
'Share with owncloud' option should not be shown if sharing is not available

### ISSUE THREAD

**Issue by davitol** [owncloud/client#4205]
If  sharing is not allowed, it would be better to hide 'Share with owncloud' when right-clicking on a file instead of let select this option and disable the content of sharing window.

![screen shot 2015-11-26 at 18 47 42](https://cloud.githubusercontent.com/assets/10596560/11428740/0a9046b6-946f-11e5-856a-2be7ebf4b8b3.png)

**Comment by Dianafg76** [comment]
'Share with owncloud' option should not be shown if sharing is not available, and when you have this option enable
![screen shot 2016-02-12 at 10 47 36](https://cloud.githubusercontent.com/assets/12032058/13003495/27b9ba12-d176-11e5-8abc-d458ac550f3b.png)

Desktop v ownCloud-2.2.0.3112-nightly20160211.pkg
Server v 8.2.2

**Comment by SamuAlfageme** [comment]
Closed with https://github.com/owncloud/client/pull/6330 - ref:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/38661151-2d3b0a6c-3e30-11e8-8a8b-0bf4e71f6c5c.png"/>
</p>
