### ISSUE TITLE
[OS X] [Activity View] Could you move the Copy button to the left 

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4207]
### Steps to reproduce
1. Open your ownCloud desktop client with the new v2.1.0
2. Right click to the oC icon
3. Click on Settings
4. Clikc on Activity option
5. Click on Sync Protocol

### Expected behaviour
Could you move the Copy button to the left , so that it is aligned with the other screens (Server Activity, Not Synced)
![screen shot 2015-11-27 at 09 38 57](https://cloud.githubusercontent.com/assets/12032058/11437062/cf6fcb2a-94ea-11e5-9458-2e54b0a112f1.png)

### Server configuration
Desktop v ownCloud-2.1.0.2916-nightly20151127.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
related #4083

**Comment by ckamm** [comment]
On linux it's aligned to the right.

**Comment by Dianafg76** [comment]
@ckamm it is only with Mac, with Windows it is aligned to the right too

**Comment by Dianafg76** [comment]
I tested this issue and now I can see the Copy button on the left
Desktop v ownCloud-2.1.1.3014-nightly20160107.pkg 
Closed
