### ISSUE TITLE
Weird behaviour after trying to share a file via link with a password that not fit with password policy pattern

### ISSUE THREAD

**Issue by davitol** [owncloud/client#4209]
Desktop Client version: Version 2.1.0-nightly20151127 (build 2916) (OSX)

Steps to reproduce:
1. Share via link a file
2. Try to set a password that does not fit with password policy pattern

Expected behaviour

A message should be shown warning about password policy

Actual behaviour

The spinner keeps loading and the desktop client turns into a weird behaviour

logs:
{"status":"failure","statuscode":403,"message":"Password is too short. Minimum 6 characters are required."},"data":[]}}"

![screen shot 2015-11-27 at 11 33 46](https://cloud.githubusercontent.com/assets/10596560/11439731/92431b22-94fd-11e5-880e-bee03321a90f.png)

**Comment by dragotin** [comment]
Well, I think this is a rather minor problem and can be moved to the next release.

**Comment by ckamm** [comment]
@davitol Which password policy app were you using? I tried https://apps.owncloud.com/content/show.php/Password+Policy+Enforcement?content=167207 but that didn't seem to apply the policy to link-share passwords.

**Comment by davitol** [comment]
@ckamm Tested again with Version 2.1.1-nightly20160122 (build 3053) for MacOSX and it is NOT fixed :-1:

**Comment by ckamm** [comment]
@davitol Thanks for testing, it worked for me, but I'll test again.

**Comment by ckamm** [comment]
@davitol It works for me. 

1. I click "Share link"
2. Since a password is required, keyboard focus jumps to the password dialog. (no spinners are moving at this point)
3. I enter a password that doesn't fit the policy and hit enter.
4. An error message appears, telling me that there are too few numbers in the password. Keyboard focus stays on the password field.
5. I enter a correct password and the share is created.

I think there's a good chance the build you were using didn't include the fix, I'll try to figure that out. 

In case it's really unfixed: What password policy settings are you using exactly? How, precisely, can you reproduce it?

**Comment by davitol** [comment]
@ckamm I set 8 characters as pwd policy in my 8.2.2 oC server. Then

**Comment by ckamm** [comment]
@danimo verified that the build you are using does indeed include my change. :/

**Comment by davitol** [comment]
@ckamm also tested in client Version 2.1.1-nightly20160122 (build 5791) for Windows and the bug also happens :-\

**Comment by ckamm** [comment]
@davitol Could you explain again how to reproduce the problem? I'm also using the >=8 character password policy.

**Comment by ckamm** [comment]
We talked on IRC: The problem is fixed when passwords are required but still fails when passwords are optional.

**Comment by davitol** [comment]
@ckamm Even when pwd is mandatory,there are other scenarios that fail.

1) Set a pwd that fit with the pwd policy
2) Check Allow editing & Set expiration date checkboxes
3) Modify again the pwd but now with one that doesn't match with the pwd policy pattern

The bug is reproduced

**Comment by ckamm** [comment]
@davitol The next nightly should have the additional fixes.

**Comment by Dianafg76** [comment]
I tested this issue and now is working OK
Desktop v ownCloud-2.1.1.3067-nightly20160125.pkg
Server v 8.2.2
@davitol Thanks!
@ckamm Thanks!
