### ISSUE TITLE
.netrc file is ignored by owncloudcmd

### ISSUE THREAD

**Issue by Wurzelmann** [owncloud/client#4210]
I'm using owncloud-cnd and cannot get netrc to work with it... I created a netrc file with the following content:

    machine <url of my owncloud>
    login <username>
    password <password>

This should be sufficient in my opinion and according to the man page. I can sync my owncloud fine when using this syntax:

    owncloudcmd -s <sourcedir> <owncloud_url>

It then prompts for my user name and password, which works fine.

However, when trying it with the "-n" flag, it just ignores it and also prompts me for user name and password. Is there anything I forgot? :-(

**Comment by ckamm** [comment]
@Wurzelmann It works for me.
* Did you put the file into `~/.netrc`?
* it should be `machine <host>`, it doesn't work with the full url

**Comment by scottjl** [comment]
@ckamm could you please provide an example that works? Everything I've tried with the machine/url doesn't work for me either.

**Comment by scottjl** [comment]
I finally got it working, turns out I was still using the owncloud:// syntax. Here's what I got to work

command line:

owncloudcmd --non-interactive -s -h --unsyncedfolders ~/.config/owncloud_nosync -n /transfer/owncloud "https://www.myowncloudinstance.org/owncloud/"

.netrc:

machine www.myowncloudinstance.org
     login username
     password mypassword

~/.config/owncloud_nosync
Directory_1
directory_2
Dropbox
GoogleDrive
somefile
someotherfile

I use the nosync file to not sync over local copies of attached storage, I don't need my Dropbox and Google Drive also copied over to my linux box.

There really should be better examples in the help/documentation.

**Comment by ckamm** [comment]
@scottjl I'm glad to hear it works. I agree about the documentation, let's keep this ticket for the doc improvement.

**Comment by Wurzelmann** [comment]
I'm sorry, but this does not work for me... I changed my credentials in the .netrc file like @scottjl suggested, but it does not use it...

I tried this:

    owncloudcmd <sourcedir> <owncloud-url>

which works fine, but prompts me for my username and password. If "-n" is used additionally, it just gives me this output:

    owncloudcmd - command line ownCloud client tool.

    Usage: owncloudcmd <sourcedir> <owncloudurl>

    A proxy can either be set manually using --httpproxy or it
    uses the setting from a configured sync client.

    Options:
      --silent               Don't be so verbose
      --confdir = configdir: Read config from there.
      --httpproxy = proxy:   Specify a http proxy to use.
                         Proxy is http://server:port
      --trust                Trust the SSL certification.

I don't know why it does not work... :-(

**Comment by Wurzelmann** [comment]
Okay, I upgraded my owncloudcmd via jessie-backports and it seems the "n" flag is only now available... regardless, using the "n" flag does nothing, it ignores my .netrc file and keeps asking for credentials. It is possible to parse the user name via "u" flag, but that's it...

**Comment by Wurzelmann** [comment]
Okay, I got it. The problem were the space characters in my password... after trying everything, I created a new user, chose a different password and it is working flawlessly now. Thank you, everyone for your help!
