### ISSUE TITLE
Allow editing option in sharing window should be hidden for files in share window instead of disabling it.

### ISSUE THREAD

**Issue by davitol** [owncloud/client#4211]
Desktop Client version: Version 2.1.0-nightly20151127 (build 2916) (OSX)

This checkbox should be hidden for sharing files. That is the server's browser behaviour.

![screen shot 2015-11-27 at 13 33 07](https://cloud.githubusercontent.com/assets/10596560/11441451/65eb808c-950c-11e5-8728-3f755d230247.png)

**Comment by Dianafg76** [comment]
I tested this issue, and now is working OK
Desktop v ownCloud-2.1.0.2956-nightly20151209.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}
Closed
