### ISSUE TITLE
Compilation failing on Coverity

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/client#4214]
https://travis-ci.org/owncloud/client/builds/93794447

**Comment by danimo** [comment]
You were testing the (currently dead) master branch. I've done two things

1.) merged 2.1 to master (for good measure)
2.) force-pushed 2.1 branch to coverity_scan

It will probably fail again, but this then at least I'm fixing the right things :)

**Comment by danimo** [comment]
Fixed.
