### ISSUE TITLE
Create permission is shown when sharing a file with a user

### ISSUE THREAD

**Issue by davitol** [owncloud/client#4216]
The create permission appears in the dropdown sharing a file with a user.

It should only be shown whe we share a folder; sharing files should only let 3 permission:
- Can share
- Can edit
- Can change

![screen shot 2015-11-30 at 10 34 27](https://cloud.githubusercontent.com/assets/10596560/11468313/cb9314c4-974e-11e5-90cf-03eeb9bf9207.png)

**Comment by rullzer** [comment]
So yeah. This is actually a bug in the old sharing code. Since it does not make any sense (server side). And the new sharing code will not allow it.

However, I just mimicked the webinterface (where it is also shown).

Anyway, long story short. Let me fix this.

**Comment by Dianafg76** [comment]
I tested this issue and now is working OK
![screen shot 2015-12-01 at 08 52 46](https://cloud.githubusercontent.com/assets/12032058/11495144/0e3261e4-9809-11e5-8951-30703b1f3381.png)

Desktop v ownCloud-2.1.0.2924-nightly20151201.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

Closed
