### ISSUE TITLE
Allow syncing of lock file as an option

### ISSUE THREAD

**Issue by AceSlash** [owncloud/client#4220]
At the moment lock files like "_.~_" are excluded from syncing without any way to remove them from the default exclude list (or am I missing something?).

I understand that lock files can be problematic but I would like an option to sync them anyway. This can help avoid multiple users editing the same file without knowing.

**Comment by nikosnikos** [comment]
This is not possible on the graphical interface but you can edit excluded files in /etc/ownCloud/sync-exclude.lst (on linux).

By the way I don't understand why is it problematic to sync theses lock files.

**Comment by dragotin** [comment]
I think this can be closed as outdated.
