### ISSUE TITLE
[2.0.2] ownCloud client crashes when you syncing with one accound and add new one

### ISSUE THREAD

**Issue by kayrus** [owncloud/client#4221]
Steps to reproduce:

* Configure new existing owncloud account and don't wait until it sync
* Configure another owncloud account, press finish, then press on owncloud icon and it will crash.

OS: Kubuntu 14.04.3
Version: 2.0.2
Server version: 8.1.2 first and 8.2.1 second

**Comment by dragotin** [comment]
Can you try to generate a backtrace using gdb?

**Comment by kayrus** [comment]
fixed typo in OS version. 12.04 -> 14.04

**Comment by kayrus** [comment]
will try little bit later

**Comment by ckamm** [comment]
I can reproduce the problem in the 2.1 branch.

**Comment by ckamm** [comment]
I think the problem is calling `FolderMan::setupFolders()` when the account wizard finishes. (it wipes and recreates all folders) I don't see why we do that.

**Comment by Dianafg76** [comment]
I tested this issue and is working OK
Desktop v ownCloud-2.1.0.2957-nightly20151210.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}
Closed
