### ISSUE TITLE
Public HTTP upload folder javascript error on file selection (ownCloud 8.2.0 (stable))

### ISSUE THREAD

**Issue by rendezvousIY** [owncloud/client#4223]
I was attempting to create a password protected public upload folder, but when I go to select files with the file picker I receive the following javascript error and the file fails to upload:
Web Developer toolbar in Firefox:
Error: TypeError: OCA.Files.App is undefined
Source File: http://<domain>/apps/files/js/file-upload.js?v=cc9ae143a9d1f620fb6b615cca3d1a1b
Line: 185
Javascript console in Chrome:
Uncaught TypeError: Cannot read property 'fileList' of undefined
(OC.Upload.checkExistingFiles	@	file-upload.js?v=cc9ae143a9d1f620fb6b615cca3d1a1b:185)

This issue only occurs when not logged in, I have used the web interface successfully many times without issues. 

Affected browsers:
Mozilla Firefox for Ubuntu - canonical-1.0 V42
Google Chrome in Ubuntu Version 46.0.2490.86 (64-bit)
Reproduced in another non-linux environment by requesting another user attempt to upload a file

This appears to be limited to a javascript error, there were no errors in the apache2 error logs.

It looks like I'm currently one release behind (8.2.0 vs 8.2.1 due to errors with the updater script) but I'm willing to update if that will help testing/reproduction.

Let me know if I can provide any more useful information. Thanks team!

**Comment by LukasReschke** [comment]
Please update to 8.2.1, this should be fixed.
