### ISSUE TITLE
owncloud client 2.1rc1 windows7 crashes during installation

### ISSUE THREAD

**Issue by khschmidt** [owncloud/client#4225]
yesterday I wanted to test the new client if the problem with git directories ist fixed.
PC with windows 7, owncloud client 2.02 running, user has admin privileges.
Start of the installation:
first the installation was stopping the running client process, then I confirmed to uninstall the old client.
after a few seconds the installation was copying the files and then the last windows asked to start the client after installation. I confimed the start of the client.
Then the start of the client was hanging. I was waiting for several minutes, nothing changed on the behavior. The last window was on the screen, the finish-button was gray. I looked in the task-manager. three or four owncloud prozesses were running. I could not stop the processes in the task manager. Shut down of windows was not possible. Only the reset of the PC could help. After the restart of the PC the owncloud client was visible in the task manager, but it was not running. Then I disabled the client in the autostartlist. After a reboot, I tried to uninstall the client. This was not possible. Then I tried to erase the owncloud directory on the PC. This was not successful, because the three *.dll were used by windows. The only way I found to delete the directory was to start with a second windows on another harddisk and delete the files.

**Comment by guruz** [comment]
Did you try 2.1?

**Comment by guruz** [comment]
Sounds bad, however you seem to be the only one reporting this. So maybe you can retry with 2.1 and then we see? Please reopen then.

**Comment by khschmidt** [comment]
I have installed now 2.1 and testet with one git-project. No problems till now, issue seems to be fixed :)

 

Von: Markus Goetz [mailto:notifications@github.com] 
Gesendet: Dienstag, 5. Jänner 2016 17:56
An: owncloud/client <client@noreply.github.com>
Cc: khschmidt <kh.schmidt@aon.at>
Betreff: Re: [client] owncloud client 2.1rc1 windows7 crashes during installation (#4225)

 

Sounds bad, however you seem to be the only one reporting this. So maybe you can retry with 2.1 and then we see? Please reopen then.

—
Reply to this email directly or view it on GitHub <https://github.com/owncloud/client/issues/4225#issuecomment-169060090> .  <https://github.com/notifications/beacon/AJCa9JnRR5gI_-iSf98JRH8cSjNsyqSBks5pW-04gaJpZM4GsEYh.gif> 



---
Diese E-Mail wurde von Avast Antivirus-Software auf Viren geprüft.
https://www.avast.com/antivirus

**Comment by guruz** [comment]
:+1:
