### ISSUE TITLE
"Restrict users to only share with users in their groups" option enabled, all users are shown in the searchbox for sharing with users.

### ISSUE THREAD

**Issue by davitol** [owncloud/client#4226]
### Steps to reproduce
1. As admin user, in the server configuration check the option "Restrict users to only share with users in their groups"
2. Using the Desktop client try share a file with a user that does not belong to the group

### Expected behaviour

The user should not appear in the users searchbox for sharing. (Same behaviour than in sharing)

### Actual behaviour

The user appears when it is searched in the searchbox
Note: It is not possible to share with the user (right behaviour)

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**ownCloud Enterprise Edition 8.2.1 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```


```
### Client configuration
Version 2.1.0-nightly20151201 (build 2924) for OSX

**Comment by guruz** [comment]
@blizzz @nickvergessen @rullzer 

As far as I see we use a server API ```ocs/v1.php/apps/files_sharing/api/v1/sharees``` for listing the users. Is there a way to have it filtered when this setting is active?

**Comment by nickvergessen** [comment]
It should be, if it is not, please raise an issue in core

**Comment by blizzz** [comment]
Here it checks for the config switch: https://github.com/owncloud/core/blob/master/apps/files_sharing/api/sharees.php#L123

But for a *single* user it may be circumvented here: https://github.com/owncloud/core/blob/master/apps/files_sharing/api/sharees.php#L172

**Comment by nickvergessen** [comment]
Oh right, will take care of it

**Comment by nickvergessen** [comment]
Fix is here: https://github.com/owncloud/core/issues/20900 feel free to test

**Comment by blizzz** [comment]
@guruz @davitol  can you verify the fix? ^

**Comment by MorrisJobke** [comment]
Fix is in 9.0 and will be backported to 8.2.2
