### ISSUE TITLE
[ownBrander] The aplication is Crashed when you remove the account

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4230]
### Steps to reproduce
1. Install the new Desktop v 2.1.0, with user Admin
2. Right click on oC icon
3. Go to Settings.. option
4. Click on Account
5. Click on Remove option
6. Select the option Remove connection

### Actual behaviour
The aplication is Crashed
![screen shot 2015-12-01 at 13 11 14](https://cloud.githubusercontent.com/assets/12032058/11500857/1b88d41e-9830-11e5-9340-df67d3cf5c3f.png)

### Server configuration
Desktop v: ownCloud-2.1.0.2924-nightly20151201.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

**Comment by guruz** [comment]
For me it crashes already when launching the app..

```
12-01 15:02:50:435 0x104699330 OCC::AbstractNetworkJob::start: !!! OCC::DetermineAuthTypeJob created for "https://docker.oc.solidgear.es" + ""
12-01 15:02:50:582 0x104699330 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 204 "Host requires authentication" QVariant(int, 401)
12-01 15:02:50:582 0x104699330 OCC::DetermineAuthTypeJob::finished: virtual bool OCC::DetermineAuthTypeJob::finished() ""
m_crashReporterWChar: /Applications/diana.app/Contents/MacOS/diana_crash_reporterDump file was written to: /var/folders/qn/s5d9n8sd45g4sbts7_0m8qxw0000gn/T/436F2DF5-56B8-46E9-A793-5B4E0F6584EB.dmp
```

**Comment by rperezb** [comment]
this is the same one as https://github.com/owncloud/client/issues/4229

**Comment by guruz** [comment]
Wow, now when making another build with ```Debug``` build type and without crash reporter it does not crash when launching the app.. @_@


@danimo heh..
