### ISSUE TITLE
Can share permission should not be visible when 'Allow resharing' option is not enabled in oC server

### ISSUE THREAD

**Issue by davitol** [owncloud/client#4231]
### Steps to reproduce
1. As admin user, in the server configuration uncheck the option Allow resharing
2. Using the Desktop client  share a file with a user

### Expected behaviour

Can Share permission should not appear (Same behaviour as in server browser)

### Actual behaviour

Can Share permission appears and it can be checked
Note: Even the checkbox is marked, the file cannot really be reshared

### Server configuration
**Operating system**:
Ubuntu 14.04

**Web server:**
Apache

**Database:**
MySQL

**PHP version:**
5.5.9

**ownCloud version:**ownCloud Enterprise Edition 8.2.1 (stable)

**Updated from an older ownCloud or fresh install:**
Fresh

**List of activated apps:**

**The content of config/config.php:**

```

```

**Are you using external storage, if yes which one:** local/smb/sftp/...
No

**Are you using encryption:** 
No

**Logs**
```


```
### Client configuration
Version 2.1.0-nightly20151201 (build 2924) for OSX

![permisohare](https://cloud.githubusercontent.com/assets/10596560/11501826/65318b7c-9837-11e5-9e1a-2470d3279e87.gif)

**Comment by Dianafg76** [comment]
I tested this issue, and now is working OK
Desktop v ownCloud-2.1.0.2956-nightly20151209.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}
Closed
