### ISSUE TITLE
On the Network option if you select the option "Specify proxy" ... and select "SOCKS5..." you can see a blue line

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4233]
### Steps to reproduce
1. Install the Desktop new v 2.1.0 with user1
2. Right click on the oC icon
3. Click on Settings... option
4. Click on the Network option
5. Select the option "Specify proxy manually as"
6. Select "SOCKS5 proxy"
### Expected behaviour

The blue line should not appear
### Actual behaviour

You can see the blue line 
![screen shot 2015-12-01 at 16 35 05](https://cloud.githubusercontent.com/assets/12032058/11505347/3ff1acf8-984a-11e5-81c9-b413b918c2cb.png)
### Server configuration

Desktop v ownCloud-2.1.0.2924-nightly20151201.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

**Comment by guruz** [comment]
I can not reproduce this here on my Mac 10.10.5 ..

**Comment by guruz** [comment]
I think I can reproduce it :)

**Comment by ckamm** [comment]
@guruz I can't. :) Maybe mac only?

**Comment by Dianafg76** [comment]
@guruz, @ckamm Yes, is only on MAC
![screen shot 2015-12-09 at 11 33 00](https://cloud.githubusercontent.com/assets/12032058/11683040/af904dac-9e68-11e5-9afe-e8cc6315e55d.png)

![screen shot 2015-12-09 at 11 33 48](https://cloud.githubusercontent.com/assets/12032058/11683063/cef8203e-9e68-11e5-8102-681fa5292b23.png)

**Comment by SamuAlfageme** [comment]
Seems fixed on 2.3 w/Qt5.6.2
