### ISSUE TITLE
Tooltip of searchbox for sharing says you can share with remote users

### ISSUE THREAD

**Issue by davitol** [owncloud/client#4234]
The tooltip of the searchbox showd the option to share with remote users; even more, it appears (remote) when adding an @ at the end of the user name. This is a wrong behaviour due to federated sharing is not developed in Desktop version 2.1.0

![screen shot 2015-12-01 at 17 18 29](https://cloud.githubusercontent.com/assets/10596560/11506672/e80a237e-9850-11e5-8403-82df24b690cb.png)

![screen shot 2015-12-01 at 17 23 53](https://cloud.githubusercontent.com/assets/10596560/11506675/ee1d9f3e-9850-11e5-970c-c53fa6f7e491.png)

**Comment by guruz** [comment]
@dragotin @MTRichards Still change or not? if we change it, the translations might not be picked up until tomorrow when we wanted to release..

**Comment by MTRichards** [comment]
Well, it is a bug and leads to non-functional behavior, right? 

Then we need to try to change it. Subsequent patch releases will have it no matter what.

**Comment by guruz** [comment]
@MTRichards This is just about removing "or remote users" from the string

**Comment by MTRichards** [comment]
That is simpler. Just remove it then please. Translations will catch up...

**Comment by davitol** [comment]
The tooltip of the searchbox is fixed

> even more, it appears (remote) when adding an @ at the end of the user name.

This behaviour still happening as it was shown in the second screenshot. Not sure if with the first fix is good enough.

**Comment by rullzer** [comment]
Wait, federated sharing should work. I tested it when writing it. Federated shares are initiated in the same way as regular shares.

**Comment by rullzer** [comment]
Basically this is also what happens on the web interface

**Comment by Dianafg76** [comment]
@rullzer, @davitol, @guruz I tested the following:

TestID | Test Case | Expected Result | Result | Related Comment
------------ | ------------- | -------------- | ----- | ------
1 | Sharing with Federated users  |  1.- Create a new folder on one server (server1) 2.- Click on Share with oC  3.- On "Share with users or groups", enter a user on another server (server2)(e.g. admin@xxx.xxxx.xxx) 4.- Click Enter 5.- Go to the server web with server2 6.- Accept the screen Add Remote share 7.- Go to the Desktop client with server2, and you can see the folder shared| **P(MAC,WIN)** |
2 | Sharing with Federated users  |  1.- Go to the server1 and no selections the option "Allow users on this server to send sahres to other server" 2.- Go to the Desktop client with server1 3.-Create a new folder 4.- Click on Share with oC  5.- On "Share with users or groups", enter a user on another server (server2)(e.g. admin@xxx.xxxx.xxx) 5.- You can't share with the federated user| **P(MAC, WIN)** |
3 | Sharing with Federated users  |  1.- Go to the server1 and no selections the option "Allow users on this server to recive shares form other servers" 2.- Go to the Desktop client with server2 3.-Create a new folder 4.- Click on Share with oC  5.- On "Share with users or groups", enter a user on another server (server2)(e.g. admin@xxx.xxxx.xxx) 6.- You can't share with the federated user 7.- Go to the Server web with server1, and you can see this Error "Error while sharing....."| **P(MAC,WIN)** |
4 | Sharing with Federated users. One account is with SHIB (with HTTPS) and the other is with normal account (HTTP) |  1.- On the Desktop client, create a new folder with the Shib server 2.- Click on Share with oC  3.- On "Share with users or groups", enter a user on normal server(e.g. admin@xxx.xxxx.xxx) 4.- Click Enter 5.- Go to the normal server web 6.- Accept the screen "Add Remote share" 7.- Go to the Desktop client with Shib server, and you can see the folder shared| :X: | https://github.com/owncloud/client/issues/4287 |
5 | Sharing with Federated users. One account is with LDAP and the other is with normal account  |  1.- On the Desktop client, create a new folder with the Shib server 2.- Click on Share with oC  3.- On "Share with users or groups", enter a user on normal server(e.g. admin@xxx.xxxx.xxx) 4.- Click Enter 5.- Go to the normal server web 6.- Accept the screen "Add Remote share" 7.- Go to the Desktop client with LDAP server, and you can see the folder shared| **P(MAC,WIN)**  |  |
6 | Sharing with Federated users. One account is with Redirected server and the other is with normal account  |  1.- On the Desktop client, create a new folder with the Redirected server 2.- Click on Share with oC  3.- On "Share with users or groups", enter a user on normal server(e.g. admin@xxx.xxxx.xxx) 4.- Click Enter 5.- Go to the normal server web 6.- Accept the screen "Add Remote share" 7.- Go to the Desktop client with Redirected server, and you can see the folder shared| :X: | https://github.com/owncloud/client/issues/4287 |

**Comment by guruz** [comment]
@rullzer, @davitol, @ogoffart Do I see it correct that we can close this issue as the related linked issue was closed with "see issue in core bugtracker"?

**Comment by rullzer** [comment]
@guruz  Yes I think so
