### ISSUE TITLE
Enforce expiration date in server: Disabling 'expiration date' checkbox in desktop client throws an error

### ISSUE THREAD

**Issue by davitol** [owncloud/client#4235]
Steps to reproduce:
1. Enforce expiration date in server
2. Using the desktop client, share a file via link
3. Uncheck expiration date checkbox

Expected behaviour

The expiration date checkbox should be disable.

Actual behavior

The user can uncheck the 'expiration date ' checkbox and 404 is shown

12-01 18:12:50:695 0x7ff6c044fa20 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareJob created for "--------------------" + "ocs/v1.php/apps/files_sharing/api/v1/shares/61"
12-01 18:12:50:915 0x7ff6c044fa20 OCC::OcsJob::finished: Reply to "PUT"  QUrl( "http:/--------------------/ocs/v1.php/apps/files_sharing/api/v1/shares/61" )  (QPair("expireDate","")) has unexpected status code: 404 "{"ocs":{"meta":{"status":"failure","statuscode":404,"message":"Cannot clear expiration date. Shares are required to have an expiration date."},"data":[]}}"

Client

OSX: Version 2.1.0-nightly20151201 (build 2924)

![screen shot 2015-12-01 at 18 11 14](https://cloud.githubusercontent.com/assets/10596560/11508811/f72364ba-985a-11e5-83df-5166e197226a.png)

**Comment by Dianafg76** [comment]
I tested this issue, and now is working OK
Desktop v ownCloud-2.1.0.2956-nightly20151209.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}
Closed
