### ISSUE TITLE
Ubuntu 14.04: ownCloud client keeps losing configuration

### ISSUE THREAD

**Issue by kyrofa** [owncloud/client#4236]
I'm sorry for the lack of specificity here... this is a frustrating and confusing issue.

Quite some time ago I updated the ownCloud client on Ubuntu 14.04 to find that it lost its configuration. In other words, when I rebooted and logged in it was asking me for the server URL again, and I had to re-add all the folders that were syncing. This despite the fact that ~/.local/share/data/ownCloud seemed correct (all the folder config files were present, etc.). I thought it was some simple programming mistake and moved on, but it's happened several times since then, and the last time I updated it was well over a week ago, and had no problems. Yet just now, I rebooted, and ownCloud is now asking me for the server address again. Like its config file got garbled somehow. All the folder configs are there, but the main ownCloud config file is mostly encoded so I don't know.

For what it's worth, this was after a hard reboot.

**Comment by guruz** [comment]
Which version of the client?
What does it say in the settings dialog of the client about the Qt version?
Have you tried 2.1rc1?

**Comment by ckamm** [comment]
@kyrofa Note that the individual folder configuration files are no longer used since 2.0.0 - the folder configs are also stored in owncloud.cfg. Could you make a backup of the file when the client is working well and compare both the next time the config is lost?

**Comment by kyrofa** [comment]
@guruz version 2.0.2, sorry for not specifying. The settings dialog says "Built from Git revision 78d782 on Nov 19 2015, 11:31:29 using Qt 4.8.6, OpenSSL 1.0.1f 6 Jan 2014."

@ckamm yes I can do that, but I'm not sure how helpful it will be since the client just seems to store bytes in there. Thoughts?

**Comment by kyrofa** [comment]
Interesting. I just re-configured the client after backing up the old config directory, and it's NOT all garbled other than the geometry. So maybe the hard reboot is what's doing this? The client is in the middle of writing it for some reason and I reboot = a garbled config file? I mean, the old config file even had groups like "[%16%60%24%00y%A4D]" which really doesn't seem right.

**Comment by ckamm** [comment]
@kyrofa Huh. owncloud.cfg should be in ini-file format, i.e. plain text with newline-separated entries. On a working config file you should be seeing at least a `[General]` section and a `[Accounts]` section. Are you using some kind of branded client?

If you aren't, this sounds like the config file gets corrupted somehow. It'll be very hard for me to help you track this down, since it's most likely either a bug in Qt or a problem on your end. Did you do a hard reset every time the configuration is lost?

Also: What Qt version are you using to run the client (I see it was built against 4.8.6 in your message above)? You can figure this out either by running `owncloud --version` (>=2.1 only) or with `ldd $(which owncloud) | grep Qt` and then checking one of the library symlinks. (example: I get /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 and see that is symlinks to libQt5Widgets.so.5.2.1)

**Comment by kyrofa** [comment]
@ckamm no, I'm using the vanilla client. And indeed, with the client running smoothly I have `[General]`, `[Accounts]`, `[ActivityListHeader]` and `[Settings]`, no unexpected gobbledygook.

Yesterday flash froze on my media center (also Ubuntu, same version of everything) requiring a hard reset as well, and the exact same thing happened there. I think we can safely assume this is a result of the hard reset, and it's a config file corruption.

Regarding the version:

    $ owncloud --version
    ownCloud version 2.1.0
    Using Qt 4.8.6

So I figure the config file can only be corrupted if the client is writing to it... but why would it be writing it during regular operations? It's not like I tried to save changes and pulled the plug at the same time-- this was running normally in all cases.

**Comment by ckamm** [comment]
@kyrofa I think Qt - at least newer versions - use a "write temporary, then move" process for writing to config files, so write corruption shouldn't happen. I don't know whether that was already the case in 4.8.6 though.

**Comment by kyrofa** [comment]
@ckamm but why is the client writing to the config file at all during normal operation?

**Comment by Gifftron** [comment]
I have the exact same thing happening on a Windows 10 Pro Machine running owncloud 2.0.1. Every time the computer restarts the folders settings need to be done again. I just had it happen when I quit owncloud as well, even without a restart.

**Comment by guruz** [comment]
@kyrofa I think that is a Qt4 bug.. have you tried Qt5-based packages?

@Gifftron 2.0.1 is known to have a problem there on Windows. It is fixed in 2.0.2.
(Latest release is 2.1)

**Comment by ogoffart** [comment]
The QSettings bug was fixed in Qt 5.4.
And the bug while upgrading was only upgrading from 2.0.0 or 2.0.1.

**Comment by kyrofa** [comment]
@guruz @ogoffart the build-deps for the owncloud client is still qt4. Are you saying it should "just work" building against qt5?

**Comment by jnweiger** [comment]
Apparently the Ubuntu 14.04 setup at https://obs.int.owncloud.com/package/show/desktop/owncloud-client
tries both. Currently it falls back to QT4. Is this intended?

<pre>
[   54s] -- Could not find Qt5, searching for Qt4 instead...
...
[   56s] -- Found Qt4: /usr/bin/qmake (found suitable version "4.8.6", minimum required is "4.7.0") 
<pre>

**Comment by jnweiger** [comment]
@kyrofa The trick for "building against qt5" is mainly getting the build-deps straight.
Started long ago, I took he liberty to complete a first draft today:

<pre>
wget -nv http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/qt5deb/Ubuntu_14.04/Release.key -O - | apt-key add -
echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/qt5deb//Ubuntu_14.04/ /' >> /etc/apt/sources.list.d/owncloud-client.list
echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/ /' >> /etc/apt/sources.list.d/owncloud-client.list
apt-get -q -y update && apt-get -q -y -V install owncloud-client
</pre>

This pulls in many qt5 components, but no qt4.
<pre>
# ldd /usr/bin/owncloudcmd  | grep -i qt
        libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f2521d82000)
        libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f25213c4000)
        libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f251fc71000)
        libqt5keychain.so.0 => /usr/lib/x86_64-linux-gnu/libqt5keychain.so.0 (0x00007f251f66e000)
        libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f251f021000)
        libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007f251d3c9000)
# ldd /usr/bin/owncloud  | grep -i qt
        libQt5Widgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5 (0x00007f7eef0a7000)
        libQt5Network.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Network.so.5 (0x00007f7eeed63000)
        libQt5WebKitWidgets.so.5 => /usr/lib/x86_64-linux-gnu/libQt5WebKitWidgets.so.5 (0x00007f7eeeb21000)
        libQt5DBus.so.5 => /usr/lib/x86_64-linux-gnu/libQt5DBus.so.5 (0x00007f7eee8a2000)
        libQt5Xml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Xml.so.5 (0x00007f7eee34e000)
        libQt5Gui.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Gui.so.5 (0x00007f7eedd01000)
        libQt5Core.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Core.so.5 (0x00007f7eed65b000)
        libqt5keychain.so.0 => /usr/lib/x86_64-linux-gnu/libqt5keychain.so.0 (0x00007f7eece44000)
        libQt5WebKit.so.5 => /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5 (0x00007f7ee92ce000)
        libQt5OpenGL.so.5 => /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5 (0x00007f7ee906a000)
        libQt5PrintSupport.so.5 => /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5 (0x00007f7ee8e05000)
        libQt5Sensors.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Sensors.so.5 (0x00007f7ee8bca000)
        libQt5Quick.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5 (0x00007f7ee4e4a000)
        libQt5Qml.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Qml.so.5 (0x00007f7ee4843000)
        libQt5Sql.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Sql.so.5 (0x00007f7ee4604000)
        libQt5Positioning.so.5 => /usr/lib/x86_64-linux-gnu/libQt5Positioning.so.5 (0x00007f7ee43cf000)

</pre>

**Comment by herrdeh** [comment]
The same problem on ubuntu 16.10, OC client 2.2.4.
Whenever I do "system reboot", I will be asked for login and password afterwards, owncloud.cfg is corrupted. Using a backed up version and restarting OC will resolve it.

**Comment by guruz** [comment]
@herrdeh See above, try a Qt5 based build

**Comment by herrdeh** [comment]
Certainly I won't build anything - enough trouble here....
Hopefully, some day there will be a solution.

**Comment by binarykitchen** [comment]
Having this issue too with Ubuntu 16.10 and owncloud client v2.3.0 - constantly looses all my settings and account after restart. Always have to set up server over and over again :(

**Comment by herrdeh** [comment]
I'm saving a backup file of the ~/.local/share/data/ownCloud/owncloud.cfg.
In the case of a crash, I just trash the corrupted file (on my machine it's some byte only) rename the backup to "owncloud.cfg" and restart the OC daemon. Then it's fine again without all the reconfig trouble.
HTH.

**Comment by binarykitchen** [comment]
I see. I would do the same if I had a valid owncloud.cfg file. The current one seems weird and has some invalid characters in it it seems ...

**Comment by herrdeh** [comment]
Well. Once again create a vaild configuration, then back up the file - and you have got one (-;

**Comment by guruz** [comment]
@herrdeh Would you please also try our packages with Qt 5.6.2 and see if they improve the situation?
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client

**Comment by mgagliol** [comment]
Is there a way to solve this issue without upgrading qt4 to qt5? thanks

**Comment by guruz** [comment]
@mgagliol The above link https://github.com/owncloud/client/issues/4236#issuecomment-287729807 won't upgrade your Qt.
It will install an ADDITIONAL SEPARATE Qt.
