### ISSUE TITLE
[OS X] When you create two or more accounts you can see the screen duplicate

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4237]
### Steps to reproduce
1. Install on Desktop Client the new version 2.1.0 with win1
2. Rigth click on the oC Icon
3. Click on Settings... option
4. Click on the user win1
5. Click on Account
6. Click on Add New
7. Create a new account (e.g win2)
8. Rigth click on the oC Icon
9. Click on Settings... option

### Expected behaviour
Tell us what should happen

### Actual behaviour
You can see the screen duplicate
![screen shot 2015-12-02 at 09 25 55](https://cloud.githubusercontent.com/assets/12032058/11526034/e2d4bd74-98d7-11e5-8dc1-afe7da4dd709.png)
And the focus is on those two accounts (Win1 and Win2)

### Server configuration
Desktop v wnCloud-2.1.0.2934-nightly20151202.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

**Comment by guruz** [comment]
Is this with some branding options?
I can't reproduce it with unbranded client..
What are the versions (from "General" tab)

**Comment by dragotin** [comment]
Also not reproduceable on linux for me

**Comment by danimo** [comment]
@dragotin I guess it's a problem with settingsdialogmac anyway -> platform specific

**Comment by Dianafg76** [comment]
@guruz The version on "General" tab
![screen shot 2015-12-02 at 15 51 51](https://cloud.githubusercontent.com/assets/12032058/11533983/c757f054-990c-11e5-8194-c0805407626b.png)

**Comment by Dianafg76** [comment]
@guruz is with normal Desktop client

**Comment by guruz** [comment]
I can indeed reproduce with the build from rotor but not with my local build.

@danimo thinks the Qt version is to be blamed..

**Comment by guruz** [comment]
... or the qtmacgoodies..

**Comment by Dianafg76** [comment]
I tested this issue, and now is working OK
Desktop v ownCloud-2.1.0.2940-nightly20151202.pkg

Closed
