### ISSUE TITLE
Desktop client harcoded, the option Add new account disappears when you created a new account

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4238]
### Steps to reproduce
1. Install on Desktop client v2.1.0 Harcoded with user Admin
2. Right click on oC icon
3. Click on Settings options
4. Select the user Admin
5. Click on Account option
6. Click on Add new
7. Create a new account (e.g mac1)
8. Go to settings options
9. Select the user Admin
10. Click on Account, is only appears 2 options (Sign out, Remove)

### Expected behaviour
The option "Add new" should not disappear

### Actual behaviour
1. Click on Account, is only appears 2 options (Sign out, Remove)
![screen shot 2015-12-02 at 09 23 38](https://cloud.githubusercontent.com/assets/12032058/11527599/3400efce-98e2-11e5-9d2f-486fb4bc69b3.png)

2. If you click on user Mac1, and click on Account option, is appears 3 options (Add new, Sign out, Rename)
![screen shot 2015-12-02 at 09 23 49](https://cloud.githubusercontent.com/assets/12032058/11527761/20da4412-98e3-11e5-9825-eb3dbb5463f1.png)

### Server configuration
Desktop v ownCloud-2.1.0.2934-nightly20151202.pkg, ownCloud-2.1.0.5676-nightly20151202-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

**Comment by guruz** [comment]
@rperezb @danimo @Dianafg76 What does "hardcoded" admin mean? Is this the themeing where you are supposed to have only 1 account?

**Comment by Dianafg76** [comment]
@guruz The Desktop client is harcoded, and the user is Admin or the user you want (e.g. Admin, mac1, mac2...)

**Comment by Dianafg76** [comment]
In my opinion, should not desappear the Add new option. if you have a Desktop client with normal users, the Add new option is not desappear

**Comment by rperezb** [comment]
I *think* that this is about to be fixed, just in case, harcoded means that the server url is fixed.
````
   QString overrideServerUrl() const { return QLatin1String("xxx"); }   
```

**Comment by dragotin** [comment]
I tested with a couple of combinations of `overrideServerUrl()` and `multiAccount()` and it works correctly now for me. @rperezb @Dianafg76 please verify.

**Comment by Dianafg76** [comment]
### Branded parameters:
```
 QString overrideServerUrl() const { return QLatin1String("xxxx"); } 
 bool multiAccount() const { return false; }
 QString defaultServerFolder() const { return QLatin1String("üla üla"); }
```
Test folder used: testsRaquel

### Current behavior
It´s not possible to add any account,
If you click on the "account" button, the options shown are: 
- Sign out
- Remove

Checked with this change: 
![screen shot 2015-12-02 at 17 08 18](https://cloud.githubusercontent.com/assets/12032058/11536110/5850b320-9917-11e5-84ee-2910bac13022.png)
Client last commit: https://github.com/owncloud/client/commit/770ad54229656245347a42b588802a0b67a1a29f

**Comment by dragotin** [comment]
@Dianafg76 but if in branding the `multiAccount()` is false it is fine that you can not add an account, because you only can have one.

**Comment by Dianafg76** [comment]
@dragotin I tested this issue, and now is working OK
Closed
