### ISSUE TITLE
Don't use CMAKE_INSTALL_PREFIX for RPATH

### ISSUE THREAD

**Issue by comzeradd** [owncloud/client#4239]
Hi,

This was fixed and merged a long time ago at #2104, but I can still see it on source. Was it reverted and why?

Thanks

**Comment by guruz** [comment]
I can ask you the same: Why is it an issue? :-)

FYI @dschmidt

**Comment by ogoffart** [comment]
It was reverted in  commit 2943b4a85a8fb78709a45d7356bd7ea5548720e8  
I suppose for a reason.  @dragotin

**Comment by ogoffart** [comment]
Can we have a description of what exactly is the bug and why it should be fixed?

**Comment by dschmidt** [comment]
I don't remember why this was relevant

**Comment by guruz** [comment]
@comzeradd ?

**Comment by comzeradd** [comment]
I'm also trying to figure out why :) There is this patch on Fedora's owncloud-client package from the previous maintainer and I'm trying to understand if it's still needed. I'll try to build the package without out.

But I guess there was some reasoning on your part too for accepting the patch initially.

**Comment by guruz** [comment]
OK, please reopen when we find more info

**Comment by dschmidt** [comment]
Sorry for warming this up, I just stumbled upon this ticket again:
Looking at it again, I assume `${LIB_INSTALL_DIR}` contained the absolute Path already (maybe only in CPack, who knows) and thus `${CMAKE_INSTALL_PREFIX}/${LIB_INSTALL_DIR}` was obviously wrong. Younger me should have definitely documented why he wanted this change. Sorry for that :-(
