### ISSUE TITLE
2.1.0rc1 "Sign out" does not sign out user

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#4241]
There is this new option for the account to "sign out":
![screenshot](https://cloud.githubusercontent.com/assets/12032058/11527761/20da4412-98e3-11e5-9825-eb3dbb5463f1.png)

If you click to sign out, you can easily enable the account without giving your password. Question: You sign out from what? Does it something different than pausing all sync processes?

And it would be nice to make disabled/paused accounts show differently (greyed out, pause symbol, ...)

**Comment by danimo** [comment]
@dragotin can you take a look?

**Comment by guruz** [comment]
Funny: With the tray menu "Log out" it works
I'll check

**Comment by guruz** [comment]
I pushed something for 2.1 so it will re-show the credentials dialog. For 2.1.1 we should clean this in a nicer way.

@ckamm @ogoffart I think one of you added the keep-old-password-as-****-in-password-dialog. Would it make sense to remove it in case the user explicitly logged out?

@tflidd I think the difference to pausing is that here you can also change to a new password, pausing is more like toggling the sync on and off.

FYI @jancborchardt @MTRichards

**Comment by jancborchardt** [comment]
Btw @guruz can you rename it to »Log out« there as well to be in line with the tray menu and the web interface? I thought I mentioned this before. :)

**Comment by ckamm** [comment]
@guruz Yes, we could clear the password on user-triggered "Log Out". I think we decided the keep the password because we also enter the "SignedOut" state programmatically on auth error.

**Comment by ckamm** [comment]
@jancborchardt the renaming was done in d92c8bec8603ac74a41a7b0c49949a784c2ee91d

**Comment by jancborchardt** [comment]
@ckamm thank you! :)

**Comment by Dianafg76** [comment]
I tested this issue and is working OK
Desktop v ownCloud-2.1.0.2957-nightly20151210.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}
Closed
