### ISSUE TITLE
[2.0.2] QList<QPrinter::PageSize>::QList (this=0x7ffff014f578 <QPrinterInfoPrivate::shared_null+24>) at ../../src/corelib/tools/qlist.h:121

### ISSUE THREAD

**Issue by Germano0** [owncloud/client#4242]
I was trying compiling and installing Owncloud client 2.0.2 with Qt5 on Fedora 23. Actions that have been successfully completed, but when I try to run the software, I get a segmentation fault. I was wondering if it was my fault or not.
Here the messages

$ gdb owncloud
GNU gdb (GDB) Fedora 7.10-29.fc23
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from owncloud...Reading symbols from /usr/lib/debug/usr/bin/owncloud.debug...done.
done.
(gdb) run
Starting program: /usr/bin/owncloud 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".

Program received signal SIGSEGV, Segmentation fault.
QList<QPrinter::PageSize>::QList (this=0x7ffff014f578 <QPrinterInfoPrivate::shared_null+24>) at ../../src/corelib/tools/qlist.h:121
121         inline QList() : d(&QListData::shared_null) { d->ref.ref(); }
(gdb) backtrace
#0  0x00007fffef609204 in _GLOBAL__sub_I_qprinterinfo.cpp(void) (this=0x7ffff014f578 <QPrinterInfoPrivate::shared_null+24>) at ../../src/corelib/tools/qlist.h:121
Python Exception <class 'RuntimeError'> maximum recursion depth exceeded while getting the str of an object: 
#1  0x00007fffef609204 in _GLOBAL__sub_I_qprinterinfo.cpp(void) (name=..., this=0x7ffff014f560 <QPrinterInfoPrivate::shared_null>) at painting/qprinterinfo_p.h:71
#2  0x00007fffef609204 in _GLOBAL__sub_I_qprinterinfo.cpp(void) (__initialize_p=1, __priority=65535) at painting/qprinterinfo.cpp:35
#3  0x00007fffef609204 in _GLOBAL__sub_I_qprinterinfo.cpp(void) () at painting/qprinterinfo.cpp:163
#4  0x00007ffff7deb79a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffde28, env=env@entry=0x7fffffffde38) at dl-init.c:72
#5  0x00007ffff7deb8ab in _dl_init (env=0x7fffffffde38, argv=0x7fffffffde28, argc=1, l=<optimized out>) at dl-init.c:30
#6  0x00007ffff7deb8ab in _dl_init (main_map=0x7ffff7ffe148, argc=1, argv=0x7fffffffde28, env=0x7fffffffde38) at dl-init.c:120
#7  0x00007ffff7ddccba in _dl_start_user () at /lib64/ld-linux-x86-64.so.2
#8  0x0000000000000001 in  ()
#9  0x00007fffffffe188 in  ()
#10 0x0000000000000000 in  ()

**Comment by dragotin** [comment]
Sorry, this kind of problems with self compiled bins can not be helped in the bug tracker. Please seek out for help on the devel mailinglist or the forum.

**Comment by Germano0** [comment]
It was a backtrace I got while I was trying to move the Fedora owncloud client from Qt4 to Qt5 (I am the package co-maintainer).
I have just sent an e-mail to the devel mailinglist
