### ISSUE TITLE
client 2.0.2 - local files/directories are not deleted if unchecked

### ISSUE THREAD

**Issue by ferdiga** [owncloud/client#4244]
### Steps to reproduce
1. install owncloud client on ubuntu 15.04
2. sync desktop
3. uncheck external file system  

### Expected behaviour
the unchecked external file system/directory should be removed (at least the client says this)

### Actual behaviour
the directory is not deleted

### Server configuration
**Operating system**:
Debian 8
**Web server:**
apache2                               2.4.10-10+deb8u1
**Database:**
mariadb-server                        10.0.22-0+deb8u1

**PHP version:**
php5                                  5.6.14+dfsg-0+deb8u1 
**ownCloud version:** (see ownCloud admin page)
8.2.1
**Updated from an older ownCloud or fresh install:**
updated from 8.1.1
**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```
Enabled:
  - activity: 2.1.3
  - bookmarks: 0.6
  - calendar: 0.8.1
  - documents: 0.11.0
  - external: 1.2
  - files: 1.2.0
  - files_external: 0.3.0
  - files_pdfviewer: 0.7
  - files_sharing: 0.7.0
  - files_texteditor: 2.0
  - files_trashbin: 0.7.0
  - files_versions: 1.1.0
  - files_videoviewer: 0.1.3
  - files_w2g: 0.8.1.0
  - firstrunwizard: 1.1
  - galleryplus: 14.3.0
  - notifications: 0.1.0
  - provisioning_api: 0.3.0
  - updater: 0.6
Disabled:
  - encryption
  - gallery
  - templateeditor
  - user_external
  - user_ldap

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system --public
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```
-- public keyword is unknown in 8.2.1

{
    "system": {
        "instanceid": "ocde8d3204fb",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "datadirectory": "\/var\/www\/owncloud_data",
        "dbtype": "mysql",
        "version": "8.2.1.4",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "enable_previews": true,
        "forcessl": true,
        "theme": "",
        "maintenance": false,
        "mail_smtpmode": "smtp",
        "mail_smtphost": "localhost",
        "mail_smtpport": "25",
        "mail_smtptimeout": 10,
        "memcache.local": "\\OC\\Memcache\\Redis",
        "memcache.locking": "\\OC\\Memcache\\Redis",
        "redis": {
            "host": "\/var\/run\/redis\/redis.sock",
            "port": 0,
            "timeout": 0
        },
        "loglevel": 3,
        "share_folder": "\/Shared",
        "trusted_domains": [
            "service.chricar.at"
        ],
        "mail_from_address": "xenon",
        "mail_domain": "strakosch.at",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "singleuser": false,
        "forceSSLforSubdomains": true,
        "trashbin_retention_obligation": "auto",
        "filelocking.enabled": "false"
    }
}

**Are you using external storage, if yes which one:** local/smb/sftp/...
local, Google Drive
**Are you using encryption:** yes/no
no
**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...
no

### Client configuration
**Browser:**
Chrome current
**Operating system:**
Ubuntu 15.04
#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by guruz** [comment]
Please try 2.1 which was released some hours ago.

**Comment by ferdiga** [comment]
in 2.1.0 the local files are deleted, but not (all) directories

**Comment by ckamm** [comment]
@ferdiga Thanks for checking with 2.1.0. It sounds like there's still a problem. Which directories aren't removed? How can I reproduce the issue?

**Comment by ferdiga** [comment]
I found this for google drive synced directories
now on another laptop, files AND directories are not deleted, although the complete tree is unchecked.

**Comment by guruz** [comment]
No error in the UI?
Do you see anything obvious when running client as
```owncloud --logfile -```
?

**Comment by ogoffart** [comment]
It probably contains ignored files which prevent deletion of the directory.  This is by desing in order to avoid loosing data.

**Comment by dragotin** [comment]
@ferdiga do you agree on @ogoffart s comment above? If not, please speak up and we can reopen this issue. Thanks.

**Comment by ferdiga** [comment]
the text explaining what uncheck does is not true if @goffoart comment is correct.
![owncloud](https://cloud.githubusercontent.com/assets/6248560/12203862/73c5a80e-b631-11e5-8252-f1f151562399.jpg)
BTW it's both important 
* to not allow data loss,
* to provide a possibility to remove synced directories.
to reproduce:
I activated the sync of a Google Drive - with errors  shown here
![owncloud1](https://cloud.githubusercontent.com/assets/6248560/12204249/4bea18fe-b633-11e5-99e3-3bece124edf3.jpg)
and tried to exclude this  Google Drive again, this time it worked.
08.01.16 18:15:04GD FGF                                                          ownCloud       Deleted
