### ISSUE TITLE
Windows Client 2.1.0 doesn't stop syncing

### ISSUE THREAD

**Issue by kisppaul** [owncloud/client#4248]
I have 4 accounts configured in one Windows Desktop Client version 2.1.0 (I upgraded just now).
I deleted a large number of small files (27000 files = 9 GB) using Windows Explorer (no error of mine). When I tried to stop the Client from syncing in order to let Windows delete faster, the Client continued deleting files on the server. 
operating system: Windows 10
ownCloud server version: 8.2.1
desktop Client upgraded from 2.0.2
In order to test it's behaviour I stopped the Client completely (system tray > exit) and restarted the Client; same problem

**Comment by guruz** [comment]
How did you "stop the Client from syncing"?

> same problem

If you delete files locally, the client will delete them from the server

**Comment by kisppaul** [comment]
Stop client from syncing as found in the manual (https://doc.owncloud.org/desktop/2.0/ownCloudClientManual.pdf)
"The little button with three dots that sits to the right of the sync status bar offers four additional options: • Pause Sync / Resume Sync"

The client pauses for a short while and then resumes syncing. 
"The yellow overlay icon with the parallel lines tells you your synchronization has been paused"
No, it keeps on deleting files on server

**Comment by ogoffart** [comment]
Hi,  This is a bug tracker.  If you want to ask for help, please use the forums https://owncloud.org/support/
If you want to report a bug, please use the issue template: https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

I tried to pause while file were deleted and it worked as expected for me.
