### ISSUE TITLE
Select sync Root Folder, but uncheck all existing subfolders

### ISSUE THREAD

**Issue by jonesints** [owncloud/client#4250]
I have a folder of +260GB with more than 100 subfolders of all sizes (some over 15GB). I share this Root Folder with colleagues so any time there's a new folder, we all get the new work synced.

Problem: As it's such a big Root Folder, we have to de-select ALL subfolders, one by one, unless we need them locally! It's v time consuming.  To complicate things in what seems a recent client bug (which I need to report) the main Root Folder keeps unselecting, so we all need to re-deselect all 100+ subfolders to make sure our process of adding new subfolders are synced for everyone.

A simple design solution could be having a 3rd option when ticking a Root Folder box: 

1) -- Unselected: nothing inside syncs
2) -- Selected: everything inside syncs
3) -- Third option: JUST Select sync Root Folder, but uncheck all existing subfolders

Any other suggestions people might have to tackle the problem?

**Comment by guruz** [comment]
Which OS?
Don't the subfolders deselect automatically when you unselect the root folder? (here on OS X)

**Comment by jonesints** [comment]
I'm on OS X Mavericks.

I want to deselect all but still keep the root folder syncable. If somebody
adds a new subfolder and the root folder is unselected,  won't it prevent
this new folder from syncing?

**Comment by ckamm** [comment]
@jonesints Which version are you using? 

I've tried to do what you want with 2.1: When you create a new folder sync connection, uncheck the root folder. All subfolders will be unchecked and the root folder will be partially checked. That should lead to no existing, but all future subfolders being synced. Does that already do what you want?

In the account-settings-page selective sync ui, there's no easy way to deselect all subfolders of the root folder.

**Comment by ogoffart** [comment]
You don't need to sync the root folder.  You can use the "add folder to sync" to only select few folder you want to sync.

**Comment by jonesints** [comment]
Ok think I've worked it out:

1) If I **uncheck** FOLDER-X containing many subfolders, new subfolders created by others aren't synced. (expected behaviour)
2) If I **check** FOLDER-X, all subfolders are synced (expected behaviour)
3) If I want to sync only new subfolders and leave the hundreds of existing subfolders unsynced, as a workaround I need to a) uncheck the main folder, b) check **one subfolder** and then c) uncheck it again. This produces the (-) state on the main folder and only new material is now synced.

Except every time someone signs into a new client machine, they need to be aware of this otherwise they believe they need to manually untick hundreds of subfolders to achieve the same as 3)

So the workaround works well, but isn't clear. Would it be easier for users to tick on just the main folder 3 times to achieve the 3rd state? Any other suggestions?

  _This affects mac client 2.2.2 and all previous releases to my knowledge._
