### ISSUE TITLE
[2.1.0] Settings Dialog: Some text is suddenly not translated to German

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#4255]
In 2.1.0 windows client there is some text not translated:
![2015-12-05 10_12_22-owncloud](https://cloud.githubusercontent.com/assets/2804301/11607082/6404aa72-9b39-11e5-8fd4-c68accdd6731.png)

**Comment by MicBoucinha** [comment]
In my case, only the first word of the Server activity tab (Created, Changed words) changed to Portuguese. The rest is in English (as I really prefer to stay as I have everything in English).

**Comment by guruz** [comment]
Can you please both try with a nightly build and check if things look better now?
http://download.owncloud.com/desktop/daily/

**Comment by MegaV0lt** [comment]
No, still untranslated:
![2016-01-05 19_03_09-owncloud](https://cloud.githubusercontent.com/assets/2804301/12123116/5b99b198-b3df-11e5-84de-d13ba263eb99.jpg)
Testet with Windows 8.1 64 Bit

**Comment by MicBoucinha** [comment]
I tried the 5751 build. The issue I described earlier maintains. Only on the Server activity tab and the only the first word (action Created, Changed). The rest of the information in each line is in English

**Comment by danimo** [comment]
Will be fixed in the next nighly, and in time for 2.1.1.

**Comment by Dianafg76** [comment]
@MegaV0lt Could you try with this version: http://download.owncloud.com/desktop/daily/ownCloud-2.1.1.3014-nightly20160107.pkg? , thanks

**Comment by MegaV0lt** [comment]
pkg i can not use on Windows. I try 5755 instead...

**Comment by Dianafg76** [comment]
@MegaV0lt sorry, try with this: http://download.owncloud.com/desktop/daily/ownCloud-2.1.1.5755-nightly20160107-setup.exe

**Comment by MegaV0lt** [comment]
#5755 looks good now!
![2016-01-07 14_12_08-owncloud](https://cloud.githubusercontent.com/assets/2804301/12171306/0159a042-b549-11e5-81ae-210c39be7e6b.png)

Thanks a lot!

**Comment by MicBoucinha** [comment]
Hi,

I tried the 5755 and in my case I still have the Created/Changed words in the Server Activity tab in Portuguese. The rest of those sentences is in English though (as the rest of the interface).

**Comment by danimo** [comment]
@MicBoucinha That's a matter of portoguese translators not catching up, nothing we can do. But you can sign up on transifex to fix the matter!

**Comment by danimo** [comment]
Closing this ticket, since the original report was solved, and we cannot excercise this for every language.

**Comment by MicBoucinha** [comment]
I understand that... actually, I prefer all my software in English, not in Portuguese. I only found it strange that from that build that was mentioned in this topic, only that specific part was translated. Thanks.
