### ISSUE TITLE
Fedora packages obsolete themselves.

### ISSUE THREAD

**Issue by CRCinAU** [owncloud/client#4256]
Noticed this for a while - but finally got around to writing a report about it....

It seems there are somewhat overzealous Obsoletes in the owncloud-client package:

<code>Obsoleting Packages
owncloud-client.i686                                                              2.1.0-1.1                                                        isv_ownCloud_desktop 
    owncloud-client.x86_64                                                        2.1.0-1.1                                                        @isv_ownCloud_desktop
owncloud-client.x86_64                                                            2.1.0-1.1                                                        @isv_ownCloud_desktop
    owncloud-client.x86_64                                                        2.1.0-1.1                                                        @isv_ownCloud_desktop
owncloud-client.x86_64                                                            2.1.0-1.1                                                        isv_ownCloud_desktop 
    owncloud-client.x86_64                                                        2.1.0-1.1                                                        @isv_ownCloud_desktop</code>

Can we please fix these silly obsoletes?

**Comment by CRCinAU** [comment]
![image](https://cloud.githubusercontent.com/assets/3992884/11608294/5051b54e-9bb9-11e5-89c1-43a8f906d0ae.png)

**Comment by dragotin** [comment]
@GermanoO any ideas?

**Comment by dragotin** [comment]
@jnweiger did you add the line on purpose?
