### ISSUE TITLE
[Transifex] [nl] Typo in Dutch translation

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#4257]
An user reported typos in the Dutch translation:

> The translation in nl_NL: "Deze url is NIET veilig omdat versleuteling omntbreekt.? We adviseren deze site niet te gebruiken."

> This should be: "Deze url is NIET veilig omdat versleuteling **ontbreekt**.? We adviseren deze site niet te gebruiken."

This could be easily fixed in Transifex, but I haven't got permissions to help with the Dutch translation yet:
![owncloud___transifex_editor](https://cloud.githubusercontent.com/assets/214010/11623412/0a01b9f8-9ccd-11e5-971c-87e0a365824d.png)
(Source: https://www.transifex.com/owncloud_robot/owncloud/viewstrings/#nl/client/40319160?q=url%20is%20NOT%20secure)

**client/translations/client_nl.ts**:
```
    <message>
        <location filename="../src/gui/wizard/owncloudsetuppage.cpp" line="127"/>
        <source>This url is NOT secure as it is not encrypted.
It is not advisable to use it.</source>
        <translation>Deze url is NIET veilig omdat versleuteling omntbreekt.
We adviseren deze site niet te gebruiken.</translation>
    </message>
```
(Source: https://github.com/owncloud/client/blob/master/translations/client_nl.ts#L1643-L1644)

@MorrisJobke Who can help here? /cc @dragotin @DeepDiver1975 

00004336

**Comment by MorrisJobke** [comment]
cc @rullzer @icewind1991 Maybe? :D

**Comment by MorrisJobke** [comment]
Or @jospoortvliet ;)

**Comment by michaelstingl** [comment]
Fixed in Transifex:
![owncloud___transifex_editor 2](https://cloud.githubusercontent.com/assets/214010/11623885/2b9105da-9cd0-11e5-8215-0e6c8f176452.png)

**Comment by jospoortvliet** [comment]
:+1: indeed, fixed...
