### ISSUE TITLE
OwnCloud Sync client needs unique User-agent header

### ISSUE THREAD

**Issue by IvanUgrin** [owncloud/client#4261]
Can you please, change the OwnCloud Sync client's User-agent header to be OwnCloud-spefic. I am implementing a WebDAV server which should also work with OwnCloud, so to do the OwnCloud-specific magic I need to determine somehow that the client is actually OwnCloud.

**Comment by danimo** [comment]
Change? it's already unique... `Mozilla/5.0 (<OS>) mirall/<version>` is the identifier for the desktop version. The iOS versions will identify as `Owncloud iOs Client/3.2.0 (Some internal details)`, the Android as `Mozilla/5.0 (Android) ownCloud-android/1.9.0`.

**Comment by IvanUgrin** [comment]
But isn't this also Firefox's User-agent?

**Comment by danimo** [comment]
No. `Mozilla/5.0` is only there to deceive stupid firewalls. Everyone does that. if you filter for that, it's meaningless.

**Comment by IvanUgrin** [comment]
OK thank, can you add an alternative OwnCloud-specific header in every request beucase right now there are some in the PUT but this doesn't go for GET?

**Comment by danimo** [comment]
@IvanUgrin again, the occurence of "mirall", "Owncloud iOs Client" and "ownCloud-android" is indicative of an ownCloud client. It's used with any HTTP verb.

**Comment by IvanUgrin** [comment]
Oh, OK didn't catch that. So "mirall" is the one I should be looking for to identify OwnCloud Desktop Client. Thanks! :+1:
