### ISSUE TITLE
OwnCloud service available through browser, but unavailable to desktop client

### ISSUE THREAD

**Issue by dstolz** [owncloud/client#4262]
Hello,

I posted this error on the ownCloud.org forum and it was suggested that I post the question here.

(original post: https://forum.owncloud.org/viewtopic.php?f=14&t=31882&p=102894#p102621)

I am running ownCloud 8.2.1 on Ubuntu 14.04, PHP v 5.5.28, and desktop client v2.0.2 on a Windows 8 pro system.  When I run the desktop client, it will search and compare files and directories as usual, however, the desktop client will eventually stop and throw an error.  I have no trouble syncing other computers and accounts.  This problem only started after upgrading my desktop client to v2.0.2.  I tried uninstalling and reinstalling a fresh download of the desktop client.

Here are a few errors from the desktop client log that I thought might be pertinent:

12-07 16:23:07:961 0x4577aa8 OCC::Folder::slotSyncFinished: -> SyncEngine finished with ERROR, warn count is 884
    .
    .
12-07 16:29:41:822 0x107ab958 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QTcpSocket(0x79f67d8) QObject(0x0)  0 false 3 0 QAbstractSocket::UnconnectedState
12-07 16:29:58:587 0x4577aa8 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (The specified procedure could not be found.)
12-07 16:29:58:588 0x4577aa8 unknown: static QWindowsEGLStaticContext\* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001
    .
    .
12-07 16:30:02:492 0x4577aa8 OCC::FolderMan::slotRunOneEtagJob: No more remote ETag check jobs to schedule.
12-07 16:30:07:491 0x107ab958 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QTcpSocket(0x79f67d8) 

It was suggested in the forum that the "RemoteHostClosedError" was strange.  I do not know where to go from here.  Any help resolving this would be very much appreciated!

Thanks,
Dan

**Comment by daandres** [comment]
i have the same issue on a linux machine with latest client and server installed.

**Comment by danimo** [comment]
Did you try with 2.1? https://owncloud.org/install (soon available through auto-updater)

**Comment by daandres** [comment]
i tried it right now with the newest version available on owncloud.org (2.1.0, build 3.12), but still it doesn't work. 
which log files could help here?

**Comment by dstolz** [comment]
I tried 2.1.0 (build 5683) and it still doesn't work.  The odd thing with my situation is that the desktop clients sync just fine on my other computers with different accounts or even with the same account as the one that is not currently working.

I am not certain that daandres is experiencing the same problem.  I do not receive any message that credentials are wrong.  I do not receive any message, just the ownCloud sync client searches for changed files and eventually stops with the logged error messages I copied into my first post. After some time, ownCloud sync client will begin searching again and repeats the error.

Any thoughts?

**Comment by Hakker** [comment]
As suggested on the forum I have the similar issues both with 2.0.2 and with 2.1.0 clients.

**Comment by daandres** [comment]
i had an other issue. i had a deeper look in my configuration and tried with pure webdav. it also didn't work. Therefore I checked what else I had chenged since I upgraded to the neweset OC Server version. 
My problem was simple, but I don't understand the reason. If I execute PHP as FastCGI application OC webdav works, with PHP as FPM it doesn't. 
but now i know this and for me it works again.

**Comment by Hakker** [comment]
If that would be the case Nginx users are screwed for the time being since they rely on php-fpm

**Comment by dstolz** [comment]
Ok, so I closed my issue too soon.  I have the latest versions of ownCloud desktop client and server, but I still eventually receive:  

some/file/name.ext - server replied: Service Unavailable.

I tried deleting the files the program stopped on with this message, but to no avail.  A new file will be found to throw this error.

Any suggestions?

**Comment by dstolz** [comment]
So I decided to tried downgrading to an older version of desktop sync client (v2.0.0 build 5423) and now everything works just fine for me.  This must have been something with newer versions.

For those interested, here's how to prevent ownCloud from automatically updating: https://doc.owncloud.org/desktop/2.0/autoupdate.html

**Comment by Hakker** [comment]
then why close it? The bug is still there that an older version doesn't have it doesn't mean it's solved. It just confirms the bug actually.

**Comment by dstolz** [comment]
There were no responses to my messages, so I gave up.  But you're right, I will leave it open.

**Comment by guruz** [comment]
> 12-07 16:23:07:961 0x4577aa8 OCC::Folder::slotSyncFinished: -> SyncEngine finished with ERROR, warn count is 884

What is important are the messages _before_ that

>  server replied: Service Unavailable.

This is a server issue. Have you checked the server's ```owncloud.log``` (in debug mode) and error log?

**Comment by dstolz** [comment]
Hi guruz. I will look at my server log, but this is from my desktop sync client.  Please not that I was forced to upgrade to v2.1.0 even though I added the registry keys to prevent this from happening.  The following message repeats over and over again in the desktop log.  Also, please note that I have at least 6 other machines with desktop v2.1.0 that currently have no trouble syncing with the server.  One of those other machines which is working fine even syncs to the same account as the the one that is throwing the following error:

```
12-17 10:01:21:003 0x48d7ca0 OCC::Folder::slotRunEtagJob: * Trying to check "CloudServer" for changes via ETag check. (time since last sync: 250 s)
12-17 10:01:21:004 0x48d7ca0 OCC::FolderMan::slotRunOneEtagJob: Scheduling "CloudServer" to check remote ETag
12-17 10:01:21:004 0x48d7ca0 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "http://my.server.add.ress/owncloud" + "/"
12-17 10:01:21:043 0x48d7ca0 OCC::Folder::etagRetreived: * Compare etag with previous etag: last: ""5672cc0b30f02"" , received: ""5672cc0b30f02""
12-17 10:01:26:045 0x756ddc8 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QTcpSocket(0x756df38) QObject(0x0)  0 false 3 0 QAbstractSocket::UnconnectedState
```

**Comment by guruz** [comment]
Any news from you here?
Any more log you can give from client and server side?

**Comment by dstolz** [comment]
Hello Guruz,

I had to move on from this issue and I have just been using the web interface which works fine.  Just to reiterate, the desktop client works just fine on several other computers, just not the one.  Since my server log file is massive (~1.3 GB), I've only copied a few fatal errors from the log after the sync client gives up (see below).  I do not have a clue if they are related to this issue.

Thanks for looking into this.

Dan

```
Fatal 	webdav 	Exception: {"Message":"HTTP\/1.1 503 Encryption not ready: Module with id: OC_DEFAULT_MODULE does not exist.","Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(82): OC\\Connector\\Sabre\\File->get()\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#7 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":273} 	2016-01-06T18:27:02+00:00 
Error 	PHP 	Array to string conversion at /var/www/owncloud/lib/private/template/functions.php#36 	2016-01-06T18:21:47+00:00 
Error 	PHP 	reset() expects parameter 1 to be array, null given at /var/www/owncloud/apps/files_versions/lib/storage.php#733 	2016-01-04T14:22:33+00:00 
Error	PHP	Array to string conversion at /var/www/owncloud/lib/private/template/functions.php#36	2016-01-06T18:21:47+00:00
Error	PHP	reset() expects parameter 1 to be array, null given at /var/www/owncloud/apps/files_versions/lib/storage.php#733	2016-01-04T14:22:33+00:00
Error	PHP	ksort() expects parameter 1 to be array, null given at /var/www/owncloud/apps/files_versions/lib/storage.php#732	2016-01-04T14:22:33+00:00
Error	PHP	Invalid argument supplied for foreach() at /var/www/owncloud/apps/files_versions/lib/storage.php#709	2016-01-04T14:22:33+00:00
Error	PHP	Undefined index: by_file at /var/www/owncloud/apps/files_versions/lib/storage.php#709	2016-01-04T14:22:33+00:00
Error	PHP	Undefined index: all at /var/www/owncloud/apps/files_versions/lib/storage.php#707	2016-01-04T14:22:33+00:00
Fatal	webdav	Exception: {"Message":"HTTP\/1.1 400 expected filesize 3726 got 0","Exception":"Sabre\\DAV\\Exception\\BadRequest","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1087): OC\\Connector\\Sabre\\File->put(Resource id #27)\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(501): Sabre\\DAV\\Server->updateFile('Consulting\/Naga...', Resource id #27, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#7 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#8 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":139}	2015-12-28T16:21:23+00:00
Fatal	webdav	Exception: {"Message":"HTTP\/1.1 400 expected filesize 802 got 0","Exception":"Sabre\\DAV\\Exception\\BadRequest","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1087): OC\\Connector\\Sabre\\File->put(Resource id #27)\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(501): Sabre\\DAV\\Server->updateFile('Consulting\/Naga...', Resource id #27, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#7 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#8 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":139}	2015-12-28T16:21:23+00:00
Fatal	webdav	Exception: {"Message":"HTTP\/1.1 400 expected filesize 16330 got 0","Exception":"Sabre\\DAV\\Exception\\BadRequest","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1087): OC\\Connector\\Sabre\\File->put(Resource id #27)\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(501): Sabre\\DAV\\Server->updateFile('Consulting\/Naga...', Resource id #27, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#7 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#8 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":139}	2015-12-28T16:21:23+00:00
Fatal	webdav	Exception: {"Message":"HTTP\/1.1 400 expected filesize 886 got 0","Exception":"Sabre\\DAV\\Exception\\BadRequest","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1087): OC\\Connector\\Sabre\\File->put(Resource id #27)\n#1 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(501): Sabre\\DAV\\Server->updateFile('Consulting\/Naga...', Resource id #27, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#7 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#8 {main}","File":"\/var\/www\/owncloud\/lib\/private\/connector\/sabre\/file.php","Line":139}	

```

**Comment by guruz** [comment]
Any news from you?
Did you try with newer client/server versions?
Did you try with Apache vs nginx?

**Comment by dstolz** [comment]
Sorry for the delayed response.... but I have since upgraded to server v9.0.2 and migrated from SQLite to MySQL thinking that may have been the issue, but it persists.  Using desktop client v2.1.1 (build 5837).  Using Apache v2.4.16. 

But I have isolated the error to this:

`Fatal	webdav	Exception: {"Message":"HTTP\/1.1 503 Encryption not ready: Module with id: OC_DEFAULT_MODULE does not exist.","Exception":"Sabre\\DAV\\Exception\\ServiceUnavailable","Code":0,"Trace":"#0 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(83): OCA\\DAV\\Connector\\Sabre\\File->get()\n#1 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(55): Sabre\\DAV\\Server->exec()\n#6 \/var\/www\/owncloud\/remote.php(138): require_once('\/var\/www\/ownclo...')\n#7 {main}","File":"\/var\/www\/owncloud\/apps\/dav\/lib\/connector\/sabre\/file.php","Line":311,"User":"dstolzbe"}`

Any thoughts on what might be causing this error.

Thank you.
Dan

**Comment by guruz** [comment]
You might have luck trying in the forums...

CC @schiesbn

**Comment by dstolz** [comment]
Hi Guruz. The forum directed me here: https://forum.owncloud.org/viewtopic.php?f=14&t=31882&p=102894#p102621

**Comment by guruz** [comment]
@dstolz Apparanetly https://github.com/owncloud/core/pull/24676#issuecomment-219748993 might help.

**Comment by hodyroff** [comment]
Assuming it is solved, since.
