### ISSUE TITLE
Client do not sync a folder with a space at the end

### ISSUE THREAD

**Issue by Nemofly** [owncloud/client#4263]
If you make a folder e.g. test with a space behind, the client did not sync this folder.
Client Version 2.1 
OC Version 8.2.1.4 
Apache 2.4
PHP 5.6+

**Comment by danimo** [comment]
@Nemofly which OS is the client running on?

**Comment by Nemofly** [comment]
It is Running on Windows 10.
But first the folder exists in the cloud.
There was a space and it was not synced.
Then i did away the space and suddenly the folder and all files were syncronising.


Von meinem iPhone gesendet

**Comment by danimo** [comment]
This is by design. Windows cannot represent Files with a space in the end. Those files are therefore excluded from syncing.
