### ISSUE TITLE
SSL Certificate issue with 2.1.0

### ISSUE THREAD

**Issue by mcnesium** [owncloud/client#4264]
Running my owncloud server with an (allegedly insecure) CAcert.org-Certificate, Client v2.1.0 seems to have problems to identify the certificate. When starting up the client, the warning popup is empty:
![bildschirmfoto 2015-12-09 um 01 24 17](https://cloud.githubusercontent.com/assets/476060/11672869/6222f4ba-9e14-11e5-8b83-4f996fe8d474.png)
Checking "trust anyway" does not help, there is no connection to the server possible after upgrade to v2.1.0:
![bildschirmfoto 2015-12-09 um 01 32 46](https://cloud.githubusercontent.com/assets/476060/11672930/fb4e25a6-9e14-11e5-847c-b94063eb20bc.png)

**Comment by danimo** [comment]
Please provide an analysis of ssllabs.com for this website.

**Comment by mcnesium** [comment]
After a short chat session with @danimo I managed to reconfigure my nginx server by adding

    ssl_client_certificate /etc/ssl/certs/class3.pem;
    ssl_verify_client optional;
    ssl_verify_depth 2;

to the existing SSL configuration. Thank you for the help and for making ownCloud!
