### ISSUE TITLE
You do not have the option of adding new account, if you don't introduce the Server Address and clicking the Red Button

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4266]
### Steps to reproduce
1. Install on Desktop Client v 2.1.0
2. Don't introduce the Server Address
3. Click on the Red button (
![screen shot 2015-12-09 at 10 58 50](https://cloud.githubusercontent.com/assets/12032058/11682268/f739a72a-9e63-11e5-909e-49061310c6f0.png))

### Expected behaviour
You should be able to add an account

### Actual behaviour
You do not have the option of adding new account

### Server configuration
Desktop v ownCloud-2.1.0.2956-nightly20151209.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

```
12-09 10:59:02:578 0x7fa66b51ae40 OCC::OwncloudWizard::slotCurrentPageChanged: Current Wizard page changed to  -1
12-09 10:59:02:600 0x7fa66b51ae40 OCC::OwncloudSetupWizard::slotAssistantFinished: Rejected the new config, use the old!
12-09 10:59:02:615 0x7fa66b51ae40 OCC::Account::~Account: Account "@" deleted
12-09 10:59:02:616 0x7fa66b51ae40 OCC::SocketApi::slotNewConnection: SocketApi:  New connection SocketApiSocket(0x7fa66b404e70)
12-09 10:59:02:617 0x7fa66b51ae40 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Share with ownCloud"
12-09 10:59:02:648 0x7fa66b51ae40 OCC::SocketApi::slotNewConnection: SocketApi:  New connection SocketApiSocket(0x7fa66d9f8fe0)
12-09 10:59:02:649 0x7fa66b51ae40 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Share with ownCloud"
12-09 10:59:02:664 0x7fa66b51ae40 OCC::SocketApi::slotNewConnection: SocketApi:  New connection SocketApiSocket(0x7fa66db22e20)
12-09 10:59:02:665 0x7fa66b51ae40 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Share with ownCloud"
12-09 10:59:02:686 0x7fa66b51ae40 OCC::SocketApi::slotNewConnection: SocketApi:  New connection SocketApiSocket(0x7fa66db27480)
12-09 10:59:02:687 0x7fa66b51ae40 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Share with ownCloud"
12-09 10:59:02:702 0x7fa66b51ae40 OCC::SocketApi::slotNewConnection: SocketApi:  New connection SocketApiSocket(0x7fa66b72edc0)
12-09 10:59:02:703 0x7fa66b51ae40 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Share with ownCloud"
12-09 10:59:02:719 0x7fa66b51ae40 OCC::SocketApi::slotNewConnection: SocketApi:  New connection SocketApiSocket(0x7fa66d9d1840)
12-09 10:59:02:720 0x7fa66b51ae40 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Share with ownCloud"
12-09 10:59:04:095 0x7fa66b51ae40 -[DelegateObject updaterDidNotFindUpdate:]: -[DelegateObject updaterDidNotFindUpdate:]
```

**Comment by Dianafg76** [comment]
And If you have one account and click on the Account option and Remove. You don't have the option of adding new account, also

Log:
```
12-09 11:12:05:885 0x7f9822f127f0 OCC::OwncloudWizard::slotCurrentPageChanged: Current Wizard page changed to  -1
12-09 11:12:05:900 0x7f9822f127f0 OCC::OwncloudSetupWizard::slotAssistantFinished: Rejected the new config, use the old!
12-09 11:12:05:914 0x7f9822f127f0 OCC::Account::~Account: Account "@" deleted
```

**Comment by ckamm** [comment]
@Dianafg76 If you cancel the initial wizard, you should not be seeing the account settings page at all. When you try to open the owncloud window, the wizard should pop up again.

I agree that deleting the last account can be confusing. The account wizard pops up, but when you close it you'll still be left with the account settings window and no way to create a new account.

What I'll do: When you delete the last account, hide the account settings window. That way, the state will be identical to the state you are in when you close the account wizard on first start.

**Comment by Dianafg76** [comment]
I tested this issue and is working OK
Desktop v ownCloud-2.1.0.2957-nightly20151210.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}
Closed
