### ISSUE TITLE
disable use of kwallet

### ISSUE THREAD

**Issue by sloth1** [owncloud/client#4267]
Is there a way to disable the use of kwallet? As much as I like KDE, i don't like kwallet. Owncloud apparently has to have it now.

**Comment by guruz** [comment]
What about ```gnome-keyring```?

**Comment by sloth1** [comment]
I'll have to try that. Apparently some kind of 3rd party password management must be present, is that correct?

**Comment by guruz** [comment]
Yes, unfortunately..

**Comment by dragotin** [comment]
I am not sure. If none is available, the client should ask.
