### ISSUE TITLE
Client should run with low priority

### ISSUE THREAD

**Issue by ferdiga** [owncloud/client#4268]
should run a s background task with low priority (nice)

can be done manually from the command line.
nice owncloud &

**Comment by danimo** [comment]
@ferdiga Are you seeing an increase in system resources. If so, we should fix that, rather than hiding the problem.

**Comment by ferdiga** [comment]
yes CPU usage is high during, probably because of large ? number of files 
75000 to be synced to the client 
145000 on the server

**Comment by guruz** [comment]
The 2.3 client sets the discovery priority lower, maybe this helps already.
https://github.com/owncloud/client/issues/5017

FYI @ckamm
