### ISSUE TITLE
[Share with users, groups] Search is case-sensitive and does not lookup login-ids

### ISSUE THREAD

**Issue by stonerl** [owncloud/client#4269]
### Expected behaviour

I want to share a file with the following User.
login-id: john
full name: John Doe
group: Users

When I enter "john" or "users" in lowercase, I want to be able to share the file with the user.

### Actual behaviour
When I enter the name or group in lowercase the client does not find the User. I have to enter either "John" for the User or "User" for the group. Also it seems that the client only searches for the full name but not the login-id (is this intended?).

### Server configuration
Operating system: Ubuntu 14.04.3 LTS

Web server: Apache/2.4.7

Database: mysql Ver 14.14

PHP version: PHP 5.5.9-1ubuntu4.14

ownCloud version: 8.2.1

### Client configuration
Client version: 2.1.0 (build 2944)

Operating system: OSX 10.10

OS language: en-US

Installation path of client: /Applications

**Comment by ckamm** [comment]
@stonerl We aim to make the sharee search behave similarly to the web interface. It searching case-dependently and not searching for the username is indeed a bug.

**Comment by Dianafg76** [comment]
I tested this issue and now is working ok
Desktop v ownCloud-2.1.0.5699-nightly20151211-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}
Closed

**Comment by stonerl** [comment]
:+1:

**Comment by etiess** [comment]
I just opened 2 new issues for accent sensitivity:
New client issue: https://github.com/owncloud/client/issues/4286
New server issue: https://github.com/owncloud/core/issues/21212
