### ISSUE TITLE
ownCloud client upsyncs file, deletes it local, downsyncs file, deletes it on server, upsyncs it again

### ISSUE THREAD

**Issue by tps800** [owncloud/client#4272]
I have noticed something really obscure:
following scenario:

  * about 40'000 files sized from 100kB to 2 MB
  * ownCloud server 8.2.1
  * ownCloud client 2.1.0 (regardless Linux or Windows)
  * not to fast connections (ADSL speed is ok)

  1. Start your ownCloud client
  2. Wait until it starts syncing
  3. push those 40'000 files in, about 1 every 2 seconds
  4. watch your ownCloud client start uploading files

all OK -- until at some time later you'll see your client *deleting local* files just uploaded, starting immediately after downloading the very same file! After the file successfully downloaded, the file is deleted on the server, and the client again uploads it.
I've tried one of the latest ownCloud clients, but even these showed this behaviour. It is not harmfull, if there is only one client connected syncing files. It is harmfull, if there are at least one additional client syncing: in this case, files may go haywire. If it is only one client, it doesn't really matter -- except bandwidth wasting uploading/downloading some files twice.

It was in no case a problem to sync a few files, pushing them one by one into your sync aria every two or three seconds. As soon, as you go over a magic border, you'll see the effect. You've to push some 1'000 files to confuse the client.

I am testing a client versioned 2.2.0-nightly20151118 (build 5635) at now. Seems even this client has this bug. As soon as I am home again I'll add information about my linux client here.

### Client configuration
**Operating system:** Ubuntu 14.04.5 LTS

**OwnCloud Client:** 2.1.0-1 (build 5569)

**Operating system:** Windows 7 Pro

**OwnCloud Client:** 2.1.0 (build 5683)
**OwnCloud Client:** 2.2.0 (build 5635) (tried this one because of the higher version number)

**Operating system:** Windows 10 Pro

**OwnCloud Client:** 2.1.0 (build 5683)

### Server configuration
**Operating system:** Oracle Linux 6.7

**Web server:** Apache 2.2.15-47.0.1

**Database:** PostgreSQL 9.3.10-1

**PHP version:** PHP 5.6.16-1

**redis version:** redis-2.4.10-1

**ownCloud version:** owncloud-8.2.1-1.1

**Updated from an older ownCloud or fresh install:** Upgrade from 6.5

**List of activated apps:**
* Enabled:
 - activity
 - files
 - files_pdfviewer
 - files_sharing
 - files_trashbin
 - files_texteditor
 - files_versions
 - gallery
 - imprint
 - ocusagecharts
 - password_policy
 - user_ldap

* Disabled:
 - external
 - files_encryption
 - files_external
 - files_locking
 - files_videoviewer
 - firstrunwizard
 - provisioning_api
 - templateeditor
 - updater
 - user_external
 - user_webdavauth

**The content of config/config.php:** 

```
<?php
$CONFIG = array (
  'instanceid' => 'oc692ddacb52',
  'passwordsalt' => '',
  'trusted_domains' =>
  array (
    0 => '<server1>.<local1>.<domain1>',
    1 => '<server2>.<local2>.<domain2>',
  ),
  'datadirectory' => '/data/owncloud/data',
  'dbtype' => 'pgsql',
  'version' => '7.0.1.1',
  'dbname' => 'owncloud',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'owncld',
  'dbpassword' => '',
  'installed' => true,
  'ldapIgnoreNamingRules' => false,
  'theme' => '',
  'maintenance' => false,
  'loglevel' => '0',
  'mail_smtpmode' => 'php',
  'mail_smtpname' => 'admin',
  'mail_smtppassword' => '',
  'overwritewebroot' => '/owncloud',
  'overwrite.cli.url' => '/owncloud',
  'secret' => '',
  'redis' => array (
    'host' => 'localhost',
    'port' => 6379,
    'timeout' => 0,
    'dbindex' => 0,
  ),
  'memcache.local' => '\\OC\\Memcache\\APCu',
  'memcache.distributed' => '\\OC\\Memcache\\Redis',
  'proxy' => 'proxy-lb:8080',
);

```

**Are you using external storage, if yes which one:** no

**Are you using encryption:** no

### Client configuration
**Browser:**
* Windows XP/7/8:
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (stable)
 * lynx (from cygwin)
 * w3m (from cygwin)
* Linux (Debian, Ubuntu 12.04/14.04/14.10, Fedora 19/20/21, Oracle Linux 6.5/7.0)
 * Chrome (stable, beta, snapshot)
 * Chromium (stable, continuous)
 * Firefox (stable, nightly)
 * Opera (last available)
 * Konqueror (stable)
 * lynx (stable)
 * w3m (stable)

**Comment by guruz** [comment]
This sounds odd for sure.
Do you have a client log for this?
Anything obvious in server owncloud.log?
What is show in the sync protocol in the UI?

**Comment by tps800** [comment]
No, I do not have a log. I've accidentally overwrote my log with an other.

In server logs you'll find the same as within the client log:
1. File upload
2. File download
3. File delete
4. File upload

In Client logs it looks like:
1. File upload
2. File delete
3. File download
4. File upload

I could only notice this synching some thousand files. The cron job started all 10 minutes then lasts longer and may be started twice (bailing out with "already started"). If the client finishes sync, but starts a new sync before the cron job ended I can watch it misbehave.
I did not test what would be if the cron job never ran. Maybe interesting!

**Comment by kaplandani** [comment]
I've also noticed owncloud windows client downloads file (which should not occur as the folder is only synced once to the server)

**Comment by dragotin** [comment]
Sorry, closing this as the required logs can not be provided. Please speak up if this can be reproduced with logs somehow.
