### ISSUE TITLE
[KDE4] "You need to reconnect" on startup when kwallet starts slowly

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#4274]
### Order of events
1. Log in to KDE4
2. Sync client starts, shows message "You need to reconnect your account"
3. A few seconds later, kwallet prompt appears
4. Enter password in kwallet
5. Wait a long time / edit a file in sync folder to nudge sync client
### Expected behavior

Sync client tries again and succeeds
### Actual result

Sync client does not react, gave up already. The dialog still says I need to reconnect my session.
If I restart the sync client it will then properly use the existing kwallet session.
### Versions

openSUSE 13.2 x86_64
owncloud-client-2.1.0-1.1.x86_64 (from our official repos)
libqt5keychain0-0.5-4.1.x86_64
libqtkeychain0-0.5-8.1.x86_64
kwalletmanager-14.12.3-16.1
kdelibs4-4.14.9-24.2.x86_64

Please note that on my desktop machine I have a HDD that seems to be slow to start, so I hear it rattling for a while after logging in. This might cause the slow down and sometimes makes the kwallet password dialog appear too late after the sync client needed it.

**Comment by guruz** [comment]
I wonder how does this behave with qtkeychain 0.6.1?

**Comment by PVince81** [comment]
I haven't seen this in a while. But it could also be because I upgraded to Leap + Plasma 5 and it seems to boot up faster. It also means that I don't have the environment to reproduce this any more. :frowning:

**Comment by PVince81** [comment]
@guruz unless you want to keep this open for further research, I'd suggest to simply close it.
If other people still report the issue, then reopen it ?

**Comment by guoyunhe** [comment]
I can reproduce this in openSUSE Leap 42.1 with KDE Plasma 5. When I didn't type Kwallet password quickly enough, owncloud will popup a password dialog. Here are something like "Kwallet...DBus NoReply" in the dialog.

**Comment by guoyunhe** [comment]
This is what I got:

![spectacle ej5199](https://cloud.githubusercontent.com/assets/5836790/15272650/9ebb320c-1a88-11e6-9622-6a68fedefcfb.png)

**Comment by TheOneRing** [comment]
Should be fixed by https://github.com/owncloud/client/pull/6525
