### ISSUE TITLE
Use of silent switch "/S" on client 2.1.0 5683 still requires interaction from user

### ISSUE THREAD

**Issue by f-s** [owncloud/client#4276]
Hi,

using the native SYSTEM account of Windows 7 Pro, for silent deployment of the said client, when updating the client from 1.8, still requires user-interaction and gives an empty "interactive services detection message". The process causing the message is "apparently" the vcredist (supplied with the client setup).

When changing to said SYSTEM user desktop and viewing the message, no message is displayed.

It looks like the oc-client setup cannot successfully silence the vcredist component of its setup in all circumstances.

Please investigate.

Thanks!

**Comment by danimo** [comment]
Please give an exact way to reproduce this. On an admin console runing psexec, the installer executes smoothly and returns successfully (error code 0). The following commandline was used to execute the 2.1.0 installer located in the current directory:

`psexec -s %CD%\ownCloud-2.1.0-5683.exe`

**Comment by guruz** [comment]
Please try 2.1.1 rc1 and give more info.

**Comment by f-s** [comment]
I deployed this one today (2.1.1-5837) @Win7pro 32bit  and same error :-( Please reopen issue!

![bgdbdecd](https://cloud.githubusercontent.com/assets/7151788/13662946/7aefb0f0-e69e-11e5-8ade-bb05f93fc3d4.png)

**Comment by guruz** [comment]
-> https://github.com/owncloud/client/issues/4563
