### ISSUE TITLE
Cannot "Unsync" readonly file in selective sync

### ISSUE THREAD

**Issue by O-Meyer** [owncloud/client#4277]
If I sync a folder containing a readonly file, the file becomes readonly in my local system. 
If I then select to not sync the folder, that contains the file, the client fails to remove the local copy.

I think this is a side effect of #3244.

I propose that the client gets enabled (somehow) to delete the filel, or that #3244 gets rolled back.

I am using Windows 7 and ownCloud 2.1.0.5683 -- build on 2015/12/03 at 9:27 AM

I am wondering also, how to get out of this situation? If I delete the file on my local machine, might that deletion be progated to the server upon sync and the file is gone? If I remove the write protection, the file gets deleted on the next sync. Yet, does the changed permisson get synched to the file on the server? Thus rendering the whole read-only handling useless?

BTW: I am only assuming that the file is write-protected on the server side. What I experience is, that I find a read-only file on my local disc.

**Comment by Gordmax** [comment]
Hey. I have similar problem with this client. I lose privilige to change file or his permissions, even if I copy it to different location. On ealier version of client i don't have this problem.

**Comment by Dianafg76** [comment]
I tested this issue and is working OK for my
Desktop v ownCloud-2.1.1.5755-nightly20160107-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}
Closed
