### ISSUE TITLE
[Windows] [2.1] "Host not found" in Wizard

### ISSUE THREAD

**Issue by albheart** [owncloud/client#4279]
Hello,

Recently installed ownCloud Windows client (ownCloud-2.1.0.5683-setup) and it won't function.

Everything works fine in my Android devices and via browsers on the same system the Windows or Linux desktop sync client won't work. In this case Windows 7 and Ubuntu 14.04 LTS. It says:

"Failed to connect to ownCloud at http:// xxxxxxxxxxxx . com/owncloud/status.php:
Host xxxxxxxxxxxxx.com not found"

See picture attached.

This is the result of the status.php from the browser.
" {"installed":true,"maintenance":false,"version":"8.2.0.12","versionstring":"8.2.0","edition":""} "

Searched for an answer but found nothing.

Is there any solution for this issue?
![841d8b68-9ff7-11e5-9f5f-efec7cafd4e1](https://cloud.githubusercontent.com/assets/16253725/11782305/9399c202-a270-11e5-9a78-c0ee4512e899.jpg)

**Comment by guruz** [comment]
How are you connected to the network? Cable? WiFi?
Does it work after a reboot?

**Comment by albheart** [comment]
It is hosted in a shared host service, managed through cpanel. My Windows and Ubuntu machines are connected through wifi.

**Comment by albheart** [comment]
I think this might be the fault of any .htaccess file configuration which I am not finding out. At least I was told so. 

Is this possible?

**Comment by guruz** [comment]
"host ... not found" means it can not even find the machine (before even attempting HTTP/HTTPS).
Have you tried to ping the host on command line?

**Comment by guruz** [comment]
-> https://owncloud.org/support/
