### ISSUE TITLE
[HiDPi] save/preserve sub-dialog size and position

### ISSUE THREAD

**Issue by martin-rueegg** [owncloud/client#4281]
(client: Version 2.1.0 (build 5683). Windows.)

dialog boxes, like the **add folder wizzard** or the **edit ignored files** dialog, are basically too small. having a small default size is acceptable, since other devices might have a lower screen resolution.

but if the size (and position) of the dialog could be saved and reused when re-opening, that would make the user experience much easier.

exemples:
<img width="261" alt="new_folder_sync" src="https://cloud.githubusercontent.com/assets/6409516/11783429/2e41c4e6-a26f-11e5-85c2-8bd6d10e6711.png">
<img width="230" alt="new_folder_sync" src="https://cloud.githubusercontent.com/assets/6409516/11783489/7dc1ab4e-a26f-11e5-8028-791e44d8baf8.png">

see also #4280.

**Comment by guruz** [comment]
(Possibly related https://github.com/owncloud/client/search?q=HiDpi&type=Issues&utf8=%E2%9C%93 ?

**Comment by martin-rueegg** [comment]
my screen resolution is 3200x1800. so yes, could be #3414. yet, the same dialog as shown there looks fine on my computer:
<img width="311" alt="oc" src="https://cloud.githubusercontent.com/assets/6409516/11786094/a4061846-a27c-11e5-88a5-dbf8315f3c93.png">

**Comment by ogoffart** [comment]
Is this still a problem in Owncloud 2.5 ?
Some work has been done in Qt and in the client over the last years regarding HDPI

**Comment by HanaGemela** [comment]
2.6.1-daily20191127 (build 12791), macOS 10.15.1
2.6.1daily20191127 (build 12732), Winodws 10
The size (and position) of the dialog is not saved and reused when re-opening

**Comment by TheOneRing** [comment]
We only save the geometry of the Settings dialog and the Sharing dialog.
But restoring the position seems to be broken....

**Comment by TheOneRing** [comment]
Hm there are a few fishy things about how the dialog is used... I'll investigate.

@michaelstingl the other dialogs, which should save their geometry?

**Comment by michaelstingl** [comment]
> @michaelstingl the other dialogs, which should save their geometry?

I don't get it. How can I help?

**Comment by michaelstingl** [comment]
@TheOneRing Could you elaborate on the behaviour?

**Comment by guruz** [comment]
>  are basically too small. 

IMHO: We should fix the size (maybe already fixed with new Qt version) and just center all the dialog(s) each time they are started?

**Comment by TheOneRing** [comment]
The dialogues are displayed correctly in size.
We only save the geometry for the settings and the share dialogue and we will keep it that way.
Qt seems to center  our dialogues anyhow independent  of the saved geometry so we already archive that behaviour
