### ISSUE TITLE
per-folder sync time limit

### ISSUE THREAD

**Issue by martin-rueegg** [owncloud/client#4282]
(client: Version 2.1.0 (build 5683). Windows.)

since multiple folders can be synced (which is fantastic!), adding a new folder pair with a huge data set (currently uploading 100GB through a 2Mbit/s line, takes something over a week) causes all the other folders to be blocked (at least until a connection time-out or write error occurs :-)).

a new setting should thus be introduced, which could be global or per account (?) that specifies the maximum amount of time one single folder synch is allowed to run. after exceeding this limit, the sync is paused and control given to the other folder pairs. after all other sync have run through, or reached the time limit on their own, the sync is resumed. preferably without doing a rescan, unless an error occurs due to e.g. a removed remote folder.

**Comment by guruz** [comment]
hmm i think we could instead better do multiple syncs at once

**Comment by TheOneRing** [comment]
Not planned
