### ISSUE TITLE
[Multiple sync folders in an account] when selecting an account tab, the first folder sync's selected folder list is opened

### ISSUE THREAD

**Issue by martin-rueegg** [owncloud/client#4283]
(client: Version 2.1.0 (build 5683). Windows.)

##### way to reproduce
- having 2+ folder syncs set up, the first is collapsed, the second open, e.g. currently syncing.
- switching to e.g. activity tab and back

##### expected behaviour
the UI looks the same as when i left it (except for the progress! :-) )

##### actual behaviour
the first folder gets automatically expanded, pushing the second folder (which i'm observing) down in the UI. having many subfolders in the first folder, the second folder disappears. the user needs to scroll down.

**Comment by martin-rueegg** [comment]
btw: this case also applies when the main window is closed and re-opened from the tray icon, even though the account tab is/was already open. (on Windows)

**Comment by ckamm** [comment]
I also don't like the auto-expansion of the first folder. It was added intentionally, I think, to make the selective sync functionality more visible. I'd either remove it or add a check "don't expand if there's more than one sync folder" @guruz?

**Comment by guruz** [comment]
@ckamm OK, then don't do it if people have multiple folders for the account.
If they're so advanced, they'll also discover the selective sync there. (or know it from having 1 folder)

**Comment by martin-rueegg** [comment]
sounds reasonable. thanks!

**Comment by guruz** [comment]
@martin-rueegg Is this fixed with 2.1.1?

**Comment by martin-rueegg** [comment]
unfortunately not (v2.1.1 on windows).

i'm not sure, how it was in v2.1.0, but i believe to remember that the folder-conent always scrolled to the top every time. this does not happen in 2.1.1. however, the first folder is always expanded, unless it was already expanded.

**Comment by guruz** [comment]
This works for me with a recent nightly. If there is 2 folders, we don't auto-expand.

**Comment by martin-rueegg** [comment]
:+1: https://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5878-nightly20160302-setup.exe is ok

thanks!
