### ISSUE TITLE
The federated sharing with SHIBB and Redirected server is not working, you can't share

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4287]
### Steps to reproduce
You new two differents server (one with SHIB (with HTTPS) (e.g user Myself), other normal sever (with HTTP) (e.g user Admin)
1. Go to the Desktop Client with SHIB
2. Create a new folder (e.g. aaa)
3. Click on Share with oC
4. On "Share with users or groups" enter a user on normal server (e.g. admin@xxxxxxxx)
5. Click Enter
6. Go to the Server web with the user Admin
7. Accept the screen "Add Remote Share"
![screen shot 2015-12-15 at 10 54 38](https://cloud.githubusercontent.com/assets/12032058/11807942/8cb8458c-a31d-11e5-9692-e9412e90c4ec.png)

### Expected behaviour
You should see the shared folder

### Actual behaviour
When you accept the screen and go to the Desktop Client with the user Admin,  you can't see the folder aaa to share

### Server configuration
Desktop client v ownCloud-2.1.0.2967-nightly20151215.pkg 
Server v {"installed":true,"maintenance":false,"version":"8.2.1.4","versionstring":"8.2.1","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
related #4234

**Comment by Dianafg76** [comment]
with Redirected server also

**Comment by rullzer** [comment]
Do you see the folder in the webinterface?

**Comment by Dianafg76** [comment]
@rullzer I can't see the folder in the webinteface

**Comment by rullzer** [comment]
Ah mmm then this is a server issue. Client can't sync folders if the server doesn't have them. Could you open a ticket in server repo?

**Comment by Dianafg76** [comment]
@rullzer OK, thanks

**Comment by Dianafg76** [comment]
open issue in Core #21252

**Comment by ogoffart** [comment]
Closing the client issue. The issue can be tracked on the core bugtracker.
