### ISSUE TITLE
owncloud windows client - sync-exlude.lst

### ISSUE THREAD

**Issue by brumle80** [owncloud/client#4288]
if you remove sync-exlude.lst from the owncloud client directory and restart the owncloud client the client gets stuck on waiting to sync.

sync should not fail at this point though or at least give a reasonable error message...
sync-exlude.lst should also be editable in client.

**Comment by guruz** [comment]
As far as I know there is an error message if the exclude file can't be loaded.

Can you try to start the client with ```--logfile -``` ? (with the - dash)

**Comment by ogoffart** [comment]
The error message i get in that case is "Could not read system exclude file".
I believe the error message is explicit enough.

P.S. please use the issue template when reporting bugs:  https://raw.githubusercontent.com/owncloud/client/master/issue_template.md
