### ISSUE TITLE
The linux client does not print build number and date. Only Version appended by "git"

### ISSUE THREAD

**Issue by tps800** [owncloud/client#4289]
While the Windows client writes out in "About":
```
Version 2.1.0-nightly20151215 (build 5706)
```

The linux client only writes (Ubuntu and RHEL-Versions):
```
Version 2.1.0git
```

I'd expect them behaving identically -- both writing out
```
Version 2.1.0-nightly20151215 (build 5706)
```

**Comment by ogoffart** [comment]
The varialbe `MIRALL_VERSION_SUFFIX` and `MIRALL_VERSION_BUILD`  need to be passed to cmake while building

**Comment by dragotin** [comment]
I changed the spec file template to pass the two variables. Still it will only show 'git' probably, as either genbranding.pl or even the jenkins scripts pass that.

**Comment by jnweiger** [comment]
This probably belongs into genbranding.pl where the template engine is located.
@dragotin please review https://github.com/owncloud/client/issues/4289

**Comment by dragotin** [comment]
Nice. I pushed some minor fixes, but now the build ID is added in the spec. Thx.
