### ISSUE TITLE
minimize & maximize buttons

### ISSUE THREAD

**Issue by patefoniq** [owncloud/client#4291]
Is there an option to add two buttons on owncloud's main screen in Windows and Linux client? I mean minimize and maximize. Now, there is only one way to do that: using arrows on the edges of window and stretch the window. It's very unconfortable. :) Thank You and sorry for my bad english.

**Comment by guruz** [comment]
@patefoniq Hi! You mean changing the size of the window, right?

@ogoffart @danimo @dragotin Another argument for our dialog-discussion..

**Comment by patefoniq** [comment]
Yes, my english is not so good :)

**Comment by patefoniq** [comment]
Is there any chance to add this buttons to forms? :-)

**Comment by danimo** [comment]
We've had that discussion a couple of times already: This is not a main window, therefore it should not have maximize, let a lone minimize. You should not need to look at it constantly. You can freely resize the window, and it will remember its size.
