### ISSUE TITLE
If mount point with sync folder gets umount 'ed (USB disk), files get deleted

### ISSUE THREAD

**Issue by diezorg** [owncloud/client#4293]
The problem (on linux - don't know, if windows is affected too):

If you store your synced folders on a portable device, like a usb hdd, and remove this device, all the folders get deleted, because the mount point is released and the underlying filesystem do not store those files. 

This is surely expected behaviour, but don't you think there could be a failsafe for such an event?

**Comment by ckamm** [comment]
@diezorg How exactly can I reproduce the problem? 

Here's what I tried:
1. Sync ~/ownCloud.
2. Pause the sync client
3. Delete and recreate ~/ownCloud to mimic a fs being unmounted there
4. Unpause the sync client -> Error about missing sync journal
5. Restart sync client -> the data is re-downloaded into ~/ownCloud.

**Comment by guruz** [comment]
Closing this until we get more info.

@diezorg Did you mount a directory _inside_ a sync directory? This is indeed not supported.
