### ISSUE TITLE
[Windows] [OS X] Wi-Fi poor performance every 10-12 seconds, high CPU load

### ISSUE THREAD

**Issue by sigxcpu76** [owncloud/client#4294]
The last few days I've started to investigate a network issue at home on wireless with a period of 10-12 seconds, 3-4 seconds each drop:

- bandwidth drops from ~600 Mbit to ~100 Mbit (802.11ac)
- lost packets with *ping -f*
- the most annoying is ssh lagging

First clue was that these happened when Wi-Fi was scanning for networks. Killing ```airportd``` process brought back lost performance.
Second clue was this message in *Console.app* :

```17/12/15 12:04:26,270 airportd[8705]: WARNING: owncloud (483) is not entitled for com.apple.wifi.scan, temporarily allowing request with background priority —— all entitlement requirements will be strictly enforced in a future release```

Killing ownCloud client restores performance, so I have the following question: why is *ownCloud* requesting a Wi-Fi scan each 10-12 seconds?

P.S. I have 3 Mac laptops at home. Two of them have this issue, both running ownCloud.

**Comment by danimo** [comment]
@guruz Looks like the bearer plugin...

**Comment by guruz** [comment]
@sigxcpu76 How is the situation if you remove the plugins in /Applications/owncloud.app/Contents/PlugIns/bearer ?

You can run Terminal and try:
```
sudo rm /Applications/owncloud.app/Contents//PlugIns/bearer/libqcorewlanbearer.dylib
sudo rm /Applications/owncloud.app/Contents//PlugIns/bearer/libqgenericbearer.dylib
```

**Comment by sigxcpu76** [comment]
@guruz: it fixes the issue. I cannot observe anymore symptoms described above with the application open.

**Comment by guruz** [comment]
2.1 release, 10.10.5 OS X:
I'm connected via WiFi and don't have ```Console.app``` messages. I however notice that in ping every ~10-12 sec there is indeed a latency spike from 25msec to 110-150msec.
If I connect via Ethernet/USB I don't have this ping latency spike.

@dragotin @jturcotte Could you help confirming this behaviour? Do you have ```Console.app``` messages?

@sigxcpu76 Are you using 2.1 release?

**Comment by sigxcpu76** [comment]
@guruz: 2.1, indeed. Maybe the security in 10.11 is tighter, but the real issue is the Wi-Fi scanning triggered by ownCloud. If the applet in menubar does it, it has the same impact, but the applet does it on request (i.e. clicking on it), not in the background.

**Comment by jturcotte** [comment]
I see this in Console.app, under "Diagnostics and Usage messages":

```
17/12/15 16:52:31,473 airportd[63]: com.apple.message.domain: com.apple.wifi.internal.scanning
com.apple.message.error: No Error
com.apple.message.duration: 3
com.apple.message.process_name: owncloud
com.apple.message.mac_address: xxxxxxxxxxxxx
SenderMachUUID: 44FF74B9-5D74-3E30-9BB2-1D67FA1E6495
```

And I do see ping www.google.com jumping right after each message (every ~10 seconds or so too). Stoping ownCloud also stops the ping from going crazy.

**Comment by sigxcpu76** [comment]
Good spot! I have exactly 13 seconds between those messages (10 seconds delay + 3 seconds of actual scanning). I was looking in "All Messages" and I've seen the warning only.

**Comment by batZen23** [comment]
Exact the same thing is happening with the 2.1.0 client under windows 10. With that client i have every 10-12 sec lag spikes. With an older client or owncloud closed that lagspikes dissapear.

**Comment by guruz** [comment]
@batZen23 Did you also check if renaming the ```bearer``` directory fixes this?

**Comment by guruz** [comment]
I can confirm that removing/renaming ```bearer``` directory also fixes this on Windows

**Comment by batZen23** [comment]
i can confirm that renaming the `bearer` directory fixes the problem

**Comment by guruz** [comment]
Commit for 2.1.1 is in https://github.com/owncloud/client/commit/0ef9bd9e2399801e1e9098ecec841a5cee44b7ac

@danimo

**Comment by guruz** [comment]
Upstream patch (not needed when just removing the plugins) is in https://bugreports.qt.io/browse/QTBUG-34641

**Comment by Dianafg76** [comment]
I tested this issue, and it is working OK
Desktop v ownCloud-2.1.1.3014-nightly20160107.pkg, ownCloud-2.1.1.5755-nightly20160107-setup.exe 
Closed

**Comment by lsc36** [comment]
0ef9bd9 seems to fix newly installed clients only, auto-updated clients still activate the `bearer` plugin until the user manually renames/removes the directory. Shouldn't relevant code be modified/removed as well?

**Comment by guruz** [comment]
@lsc36 that patch is for Windows and OS X, which one do you see the problem? Can you create your comment as a new issue?

**Comment by lsc36** [comment]
Created #4543.
