### ISSUE TITLE
File renaming notification shows the new filename twice.

### ISSUE THREAD

**Issue by Bubu** [owncloud/client#4295]
Client version: 2.1.0
Server version: 8.2.1

When renaming  or moving a file on another device or through the web interface:
### Expected behaviour ###
Notification shows: File1 has been renamed to File2

### Actual Behaviour ###
Notification shows:
File2 has been renamed to File2

**Comment by guruz** [comment]
Which OS?

**Comment by Bubu** [comment]
Linux & WIndows

**Comment by Dianafg76** [comment]
@ogoffart I tested this issue and on my windows is working OK
Desktop v ownCloud-2.1.1.5722-nightly20151223-setup.exe 
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
@ogoffart I tested this issue and on my windows is working OK
Desktop v ownCloud-2.1.1.5722-nightly20151223-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}
