### ISSUE TITLE
CPack Error: Problem running NSIS command

### ISSUE THREAD

**Issue by Niahm** [owncloud/client#4297]
i have some problem when i execute the "make package" command when building the windows client in opensuse 13.2 following this guide:     https://doc.owncloud.org/desktop/2.0/building.html

Run CPack packaging tool...
CPack: Create package using NSIS
CPack: Install projects
CPack: - Run preinstall target for: client
CPack: - Install project: client
CPack: Create package
CPack Error: Problem running NSIS command: "/usr/bin/makensis" "/home/prime/CLIENT/client-build/_CPack_Packages/unused/NSIS/project.nsi"
Please check /home/prime/CLIENT/client-build/_CPack_Packages/unused/NSIS/NSISOutput.log for errors
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: ownCloud
Makefile:61: recipe for target 'package' failed
make: *** [package] Error 1

in "NSISOutput.log" i got this:

Function: "LaunchApplication"
!insertmacro: UAC_AsUser_ExecShell
!insertmacro: macro named "UAC_AsUser_ExecShell" not found!
Error in script "/home/prime/CLIENT/client-build/_CPack_Packages/unused/NSIS/project.nsi" on line 250 -- aborting creation process

Can any one help ?
Thanks.

**Comment by guruz** [comment]
Please check https://doc.owncloud.org/server/8.2/admin_manual/enterprise_clients/creating_branded_apps.html

**Comment by Niahm** [comment]
thanks.
Any solution for the opensource client ?

**Comment by guruz** [comment]
Not really sorry. Might have luck on irc (freenode) #owncloud-client-dev or in the forums..

**Comment by junkings** [comment]
Do you have solved it？

**Comment by astrosys** [comment]
i have the same trouble, do you have solved it @Niahm  ? thank you
