### ISSUE TITLE
[ArchLinux] Not starting: symbol lookup error: owncloud-bin: undefined symbol: _ZN3OCC21handleNeonSSLProblemsEPKcPcmiiPv

### ISSUE THREAD

**Issue by 0nse** [owncloud/client#4298]
I'm running Arch Linux 4.2.5 and the error occurred on [owncloud-client 2.1.0-2](https://www.archlinux.org/packages/community/x86_64/owncloud-client/) as well as [owncloud-client-git 2.1.0-1](https://aur.archlinux.org/packages/owncloud-client-git/). When launching owncloud from terminal, I get:
```
owncloud-bin: symbol lookup error: owncloud-bin: undefined symbol: _ZN3OCC21handleNeonSSLProblemsEPKcPcmiiPv
```

Using `gdb`:
```
Starting program: /usr/bin/owncloud-bin --logfile -
/usr/bin/owncloud-bin: symbol lookup error: /usr/bin/owncloud-bin: undefined symbol: _ZN3OCC21handleNeonSSLProblemsEPKcPcmiiPv
[Inferior 1 (process 2070) exited with code 0177]
```

For testing purposes, I have removed `$HOME/.local/share/data/ownCloud` but the error remained the same.

I also tried reinstalling multiple times.

SHA sums:
```
52b8e2c021d29372191cc00833221de40639824a  /usr/lib64/libownclouddolphinpluginhelper.so
a0cb84b6acc4aeb0fc8e4ecd6c342b77093113f9  /usr/lib64/libowncloudsync.so
7e531caa4954b086a650451022b450c81f41c529  /usr/lib64/owncloud/libocsync.so
ed2a81e383026d01f80e4968eda48cc4964e735e  /usr/bin/owncloud
b581cd81fdd127b3c7b2d8caecf0c014ad94bdbd  /usr/bin/owncloud-bin
f6623b5af885fc6f59e32962d705f6158ae7c912  /usr/bin/owncloudcmd
```

**Comment by guruz** [comment]
The symbol ```handleNeonSSLProblems``` was removed for the 2.1 release, it does not even exist anymore in the source. https://github.com/owncloud/client/search?utf8=%E2%9C%93&q=handleNeonSSLProblems

You might have a broken installation/package?

**Comment by 0nse** [comment]
Thank you for the hint. The binary was indeed heavily outdated. After replacing it with the most recent version, it works again. The bug was solely local and thus no fixes from your side are needed.
