### ISSUE TITLE
[PHP-FPM] "Connection closed" in client, "(104: Connection reset by peer) while reading upstream" in server

### ISSUE THREAD

**Issue by sbani** [owncloud/client#4299]
### Expected behaviour
Mac client should connect to server.

### Actual behaviour
Mac client can't connect to server. Throws "Verbindung beendet" which means "Connection ended (or closed)" in german. Seems to be a SSL problem?! But I'm not sure and don't know what to do next.

WebDAV connection works fine with Mac Finder.
OwnCloud WebUI works fine too

### Server configuration
Operating system: Ubuntu
Web server: nginx http2, ssl (let's encrypt)
```
  ssl off;
  ssl_certificate /etc/letsencrypt/live/xxx.com/fullchain.pem;
  ssl_certificate_key /etc/letsencrypt/live/xxx.com/privkey.pem;
  ssl_trusted_certificate /etc/letsencrypt/live/xxx.com/chain.pem;
  ssl_session_cache shared:SSL:10m;
  ssl_protocols TLSv1.1 TLSv1.2;
  ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDS$
  ssl_prefer_server_ciphers on;
  ssl_stapling on;
  ssl_stapling_verify on;
```
Database: mariadb
PHP version: php 7.0
ownCloud version: ownCloud 8.2.1 (stable)

### Client configuration
Client version: Version 2.1.0 (build 2944)
Operating system: Mac
OS language: German

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
http://ur1.ca/oclm2

2. Web server error log:
````
2015/12/17 20:11:31 [error] 2983#2983: *237 readv() failed (104: Connection reset by peer) while reading upstream, client: 185.17.207.249, server: cloud.mucvpn.com, request: "PROPFIND /remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://unix:/run/php/php7.0-fpm.sock:", host: "cloud.mucvpn.com"
```
3. ownCloud log (data/owncloud.log):
Empty!

**Comment by tflidd** [comment]
Some ideas to investigate:
https://serverfault.com/questions/543999/nginx-errors-recv-failed-104-connection-reset-by-peer-while-reading-respon
https://stackoverflow.com/questions/32977180/nginx-error-readv-failed-104-connection-reset-by-peer-while-reading-upstrea
https://stackoverflow.com/questions/10393203/error-readv-failed-104-connection-reset-by-peer-while-reading-upstream
https://github.com/owncloud/core/issues/14187
http://howtounix.info/howto/104-connection-reset-by-peer-error-nginx

You can also verify your ssl settings:
https://www.ssllabs.com/ssltest/analyze.html?d=cloud.yourserver.com

**Comment by guruz** [comment]
"Verbindung beendet" = "Connection Closed"
So some more ideas to investigate: https://github.com/owncloud/client/issues/4047#issuecomment-165486607

**Comment by guruz** [comment]
> ownCloud log (data/owncloud.log): Empty!

Did you set the log mode to verbose?

Is there anything in the php-fpm log?

**Comment by sbani** [comment]
php-fpm logs are empty for the time of trying.

> Did you set the log mode to verbose?
nope. I will check and retry later.

**Comment by sbani** [comment]
Found this one:
> Exception: {"Message":"HTTP\/1.1 401 No basic authentication headers were found","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(154): Sabre\\DAV\\Auth\\Backend\\AbstractBasic->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#1 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/auth.php(127): OC\\Connector\\Sabre\\Auth->auth(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#2 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php(118): OC\\Connector\\Sabre\\Auth->authenticate(Object(OC\\Connector\\Sabre\\Server), 'ownCloud')\n#3 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#6 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(55): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/owncloud\/remote.php(137): require_once('\/var\/www\/ownclo...')\n#9 {main}","File":"\/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Backend\/AbstractBasic.php","Line":70}

**Comment by sbani** [comment]
Thanks @tflidd, but your possible solution don't work for me. But don't know why. very strange thing's going on

**Comment by sbani** [comment]
Solved.

Thanks @tflidd and @guruz for your help. 

This php-fpm configuration worked for me:
```
pm.max_children = 100
pm.start_servers = 20
pm.min_spare_servers = 5
pm.max_spare_servers = 30
pm.max_requests = 500
```

Coming from owncloud/core#14187 and @donSchoe (thanks to him too)

**Comment by sbani** [comment]
Okay guys. Found the **real** issue here. Checked if owncloud is working on another computer yesterday and worked fine (as you can see), but **had nothing to do with the php-fpm configuration**!

I  had changed the SSL certificate to the letsencrypt one. And that caused the error **on my OSX**:

**The old certificate had been saved to the osx keychain and I needed to delete it**

**Comment by guruz** [comment]
:+1: grrreat

**Comment by Berndinox** [comment]
I've got the same Problem with an new Windows Client. OS is completly fresh installed. I tried it with the letsencrypt certificate aswell as with an comodo cert. Always "connection closed" while connceting for the first time.
