### ISSUE TITLE
Add a multi-account feature

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/client#43]
I refer to the Windows Client 1.1.1 .

Problem:

I want to synchronise different Users' directories, on a same or different ownCloud installations.
* https://server1/owncloud-path-i (UserA)
* https://server1/owncloud-path-ii (UserA)
* https://server1/owncloud-path-iii (UserB)
* https://server2/owncloud-path-iv (UserC)

Currently, I do not see a possibility to achieve this in the current version and suggest this as improvement. Please correct me if I am wrong.

Remark: 

In the current version, the following appears to be implemented (single user, single server, plurality of directories)
* https://server1/owncloud-path-i (UserA)
* https://server1/owncloud-path-ii (UserA)

**Comment by TheNodi** [comment]
I've got a simple workaround for those who need to sync multiple accounts (even with multiple owncloud instances) using owncloudcmd.exe, you can find my article here:
http://leonardosite.altervista.org/owncloud-multiaccount-client-workaround/

**Comment by mosandlt** [comment]
Hello,

i wrote for me a small wordpress site, see - http://www.mosandl.eu/2014/04/start-owncloud-sync-client-twice/

cheers

**Comment by danimo** [comment]
Note that all the workarounds will cause issues, such as overlay icons not working reliably.

**Comment by mosandlt** [comment]
for me, tested in mac and windows i have no issues right now

**Comment by jospoortvliet** [comment]
Thanks @mosandlt and @TheNodi for sharing how to do this - it might have issues but if it helps people, that's great!

**Comment by MaverickVG** [comment]
are there any news concerning this awesome feature? We are really looking forward for this.

**Comment by danimo** [comment]
We know, but it's scheduled for 1.9, and we are still working on 1.8. That said all code changes are being developed with multi account in mind already.

**Comment by mamayer** [comment]
+1 I could really use that feature. The workarounds are not that comfortable.

**Comment by lokimo** [comment]
+1

**Comment by Teots** [comment]
+1

**Comment by danimo** [comment]
Guys, the feature is scoped and being worked on. Every time you post a +1 not only does God kill a kitten, but _every_ developer gets a mail that he needs to process, taking more time from completing features like this. For now, it seems I'll have to lock this issue :-(

**Comment by ogoffart** [comment]
New issue to track progress:   https://github.com/owncloud/client/issues/3084
