### ISSUE TITLE
[WINDOWS] .lnk files (shortcut) are reuploaded and/or create conflict files

### ISSUE THREAD

**Issue by etiess** [owncloud/client#4300]
### Expected behaviour
Shortcut files are synced in the same way as standard files.

### Actual behaviour
Some .lnk files (shortcut files in Windows) are reuploaded several times a day, and sometimes create conflict files.

I looked for similar issues with .lnk files but they are all closed: https://github.com/owncloud/client/issues/2792, https://github.com/owncloud/client/issues/2447, https://github.com/owncloud/client/issues/2132. This one looks very similar: https://github.com/owncloud/client/issues/1307

### Steps to reproduce
1. Download the attached archive: [Test2.zip](https://github.com/owncloud/client/files/66418/Test2.zip)
2. Unzip it in a synced folder
3. Trigger a sync: the files are reuploaded again and again

### Server configuration
Ubuntu 15.04
Server version: Apache/2.4.10 (Ubuntu)
Server built:   Jul 24 2015 17:25:18
PHP 5.6.4-4ubuntu6.4 (cli) (built: Oct 28 2015 01:21:29)
mysql  Ver 14.14 Distrib 5.6.27, for debian-linux-gnu (x86_64) using  EditLine wrapper
ownCloud version:8.2.1

### Client configuration
Client version:  2.1.0 (build 5683)
Operating system: Windows 10
OS language: French
Installation path of client: "C:\Program Files (x86)\ownCloud\owncloud.exe"

### Logs

owncloud Windows: look at this file for example : "Test2/putty - Raccourci.lnk"  in 
https://gist.github.com/etiess/7d3204a75be30daf42ae

owncloud client log: https://gist.github.com/etiess/3df0b319e3319eb7e167

**Comment by bcutter** [comment]
I can confirm this. *.lnk files not usable at the moment, small bug with horrible impact.

**Comment by ogoffart** [comment]
are the lnk files changing really. Or only its medata?

**Comment by ogoffart** [comment]
I found out what the problem was

**Comment by Dianafg76** [comment]
@ogoffart I tested this issue and on my windows is working OK
Desktop v ownCloud-2.1.1.5722-nightly20151223-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}

**Comment by etiess** [comment]
Ip updated my client to 2.1.1 (build 5837). Is the patch integrated in this version?

The problem is still present.

@Dianafg76 Is it working OK for you with this version?

owCloud Server: 8.2.2

**Comment by ogoffart** [comment]
yes, 2.1.1 should have fixed the problem.  maybe you need to wait for a sync for everything to stabilize in the DB.  If the problem persist then than mean there was another problem.

**Comment by etiess** [comment]
@ogoffart : I did. I even restarted my computer. The problem persists.

![upload](https://cloud.githubusercontent.com/assets/900280/12982693/25a71d2c-d0e6-11e5-9f8f-4184e4a093a8.png)

(Téléversé = uploaded)

**Comment by etiess** [comment]
I just figured out something: These shortcuts are in a tool bar, in my Windows taskbar (see picture below). They are re-uploaded each time I click on them to launch the program.

![taskbar](https://cloud.githubusercontent.com/assets/900280/12982917/4b2e5b68-d0e7-11e5-9bc2-49e10978ad44.JPG)

I tried to copy these links on my Desktop (which is also synced by my ownCloud client). And they are not re-uploaded, even if I launch the program.

The files in the tool bar (in the "Quick Launch" folder) are in fact modified by Windows: I see that the modification date is changed each time I click on it. I don't know why...

**Comment by etiess** [comment]
For the record, this issue was not due to owncloud, but to Windows. There is a workaround here: http://answers.microsoft.com/en-us/windows/forum/windows_10-files/unnecessary-date-modified-update-from-toolbar-link/16e89ef6-84d7-4c00-b35d-24b51931e0dd

To prevent it, right-click on the shortcut and click Properties. In the General tab, enable "Read-only" attribute and click OK.

To enable "Read-only" attribute for all shortcuts in the MyToolbar folder.
- SHIFT + Right-click the folder that contains the shortcuts, and click "Open command window here".
- In the Command Prompt window, type: attrib +R *.lnk
- Type exit
