### ISSUE TITLE
RTL translations broken with Qt 5 / Qt Translation issues

### ISSUE THREAD

**Issue by danimo** [owncloud/client#4301]
### Expected behavior

Interface inverts for RTL languages

### Actual behavior

Interface does not invert

Check e.g. with LANGUAGE=fa owncloud

Sidenotes: This is a bug in Qt < 5.5, as the `QT_LAYOUT_DIRECTION` translation lacks a context. We still use 5.4 for Windows and Mac OS. The most simple workaround there is to add the following line after setting the translators:

```
setLayoutDirection(QApplication::tr("QT_LAYOUT_DIRECTION") == QLatin1String("RTL") ? Qt::RightToLeft : Qt::LeftToRight);
```

Klaas reports that it still not working well for him on Qt 5.5.1, but this might be a setup issue. Needs debugging. Making him the initial assignee hence.

**Comment by danimo** [comment]
I've added two workarounds: the aforementioned one and one that will will make more efforts to look up Qt translations (5487fc1f9cfa3091e3dc60fbb8a31f7ca1723d3c). Let's see if this works on all platforms in the next nightly build.

**Comment by Dianafg76** [comment]
@danimo What are the steps to reproduce the issue?

**Comment by guruz** [comment]
@ogoffart and me have tried on Linux and OS X and it looked OKish when starting with ```-reverse```.
Moving issue to 2.2.

Input from someone using the Arabian oC client would be nice.

**Comment by davitol** [comment]
Using in OSX, changing my system to arabic language, the client app is not translated to arabic :-1:

Version 2.2.4-nightly20160921 (build 3690)

**Comment by ogoffart** [comment]
There is no arabic translation of owncloud.
There is one in farsi and it works here on linux.
As mentioned by danimo it is a problem with Qt 5.4 which should be fixed as we upgrade Qt on mac and windows.
