### ISSUE TITLE
Directory not syncing if a file with an identical name previously existed

### ISSUE THREAD

**Issue by sukosevato** [owncloud/client#4302]
So I ran into the following issue.

I had a text file named: "A1" (assignment 1).
I wanted to move it into a folder named "A1" because I got more files belonging to the same assignment. So I renamed this file temporarily so I could create a folder name A1 and moved the file into it together with the new files. This all synced without a problem with owncloud.

However, when I started owncloud on another computer, I got syncing errors.

"Not a directory" is the error message that I get. And all files that I had moved into the directory fail to sync. So I renamed the file "A1" into "A1_old" and then got the error messages "No such file or directory" due to the directory "A1" still not existing. I then manually created a folder named "A1" and then owncloud did sync succesfully.

Sounds like a bug to me.

Both system that run the owncloud client are:
- Linux 4.2.5-1-ARCH 2015 x86_64 GNU/Linux
- Owncloud client 2.1.0, Built from Git revision c0c9fb on Dec 8 2015, 12:35:25 using Qt 5.5.1, OpenSSL 1.0.2e 3 Dec 2015

The owncloud server is running: 
- FreeBSD 10.2
- Apache24-2.4.17
- Php55-5.5.30 
- OwnCloud 8.2.1 (stable)

All of them use ZFS as file system.

**Comment by ckamm** [comment]
I can reproduce this with 2.1 as you described:
* Have a file A1 synced to two clients
* Pause one.
* On the other: `mv A1 A1-tmp && mkdir A1 && mv A1-tmp A1/A1 && touch A1/new-file`
* Wait for sync, then unpause the other

The error is "Not a directory" for A1/A1 and A1/new-file.

From the logs, A1 is SYNC, A1/A1 is NEW (move detection works), A1/new-file is NEW

**Comment by ckamm** [comment]
An analogous problem happens when going from A1/A1 back to A1.

**Comment by ckamm** [comment]
As a simpler test case, change something from file to directory or back on one client and check what the other client does (the entity doesn't change type)

**Comment by dragotin** [comment]
Is the problem that the second client sees A1 still as a file, even though it changed to directory meanwhile? This might be because the discovery information is read from the journal.

**Comment by ckamm** [comment]
Current state:
1) foo/ -> foo: update: EVAL/EVAL, reconcile: NONE/SYNC, downloads foo but can't rename it to final name
2) foo -> foo/: update: EVAL/EVAL, reconcile: NONE/NONE, no action

**Comment by ckamm** [comment]
@ogoffart I've polished and revised yesterday's patches, could you review again? In particular the second one.

**Comment by ckamm** [comment]
While writing smashbox tests I noticed the following related bug:
1. Have a directory (can be empty) fully synced.
2. Pause sync.
3. Delete the directory and add a file of the same name.
4. Enable sync: Failure.

There are several layers to this bug:
1. The file gets deleted and replaced by a directory. (the directory handling in createJob() should probably only trigger if direction == Down)
2. During reconcile, the remote pass *overrides* the direction with None. (the first pass correctly detects that a file upload is necessary)
3. This probably needs to execute a directory DELETE on the server before the PUT can succeed...

A similar problem might occurr if a file is replaced with a directory.

**Comment by Dianafg76** [comment]
@sukosevato Could you try this version, http://download.owncloud.com/desktop/daily/ownCloud-2.1.1.3024-nightly20160112.pkg.tbz, please
Thanks

**Comment by Dianafg76** [comment]
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3Anightly&package=owncloud-client

**Comment by sukosevato** [comment]
I can't install that package on Arch Linux. I'm very short on time until January 28 due to exams. After the 28th I'll go figure out how to check out this specific branch / build the package.

**Comment by Dianafg76** [comment]
I tested this issue en Windows and Mac and is working OK.
@sukosevato When you have time, can you test it, please?
Thanks

**Comment by dragotin** [comment]
@ckamm pls. consider and review #4396
