### ISSUE TITLE
Owncloud windows client will not load after auto-update

### ISSUE THREAD

**Issue by kaplandani** [owncloud/client#4303]
Error message box:
csync_set_auth_callback could not be located at the dynamic link library libocsync.dll

(not sure about version number, as I can't load the client to check. update happened  yesterday (Dec 20th)

**Comment by guruz** [comment]
Could you check the file modification times of the DLLs and .exes in your owncloud directory?
Maybe the update somehow mixed different versions?

Did you try to relogin since maybe the updater installer needs that?

**Comment by kaplandani** [comment]
Downloading the client and reinstalling solved this.
Probably a bug in updater.
Dani
