### ISSUE TITLE
constant crash

### ISSUE THREAD

**Issue by prophoto** [owncloud/client#4304]
Owncloud desktop client crashes with a C++ runtime error. Not sure how to give more info, please help!

**Comment by guruz** [comment]
> Not sure how to give more info

You did not even mention which OS or version you are using :-) 

https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

**Comment by prophoto** [comment]
Win10 x64.

**Comment by prophoto** [comment]
### Expected behaviour
Client should sync files

### Actual behaviour
Client crashes

**Comment by prophoto** [comment]
### Server configuration
Operating system: FreeNAS Jail, installed as plugin.

**Comment by prophoto** [comment]
### Client configuration
Client version: 2.1.0

Operating system: Win10 x64

OS language:En

Installation path of client: default

**Comment by guruz** [comment]
And at which point does it crash? On startup? When you click something?

Does it ask you to send a crash report? (Did you send it?)

**Comment by prophoto** [comment]
Crashes when trying to sync folder of music files. (127GB, 30k files)
Does not offer crash report.

**Comment by guruz** [comment]
Do you mean by crash that the settings dialog is closing and the ownCloud icon disappears from system tray?

Do you get any dialog message box when the crash happens?

**Comment by prophoto** [comment]
Still not sure why the crash was happening but it hasn't done it in a couple of days and the folder seems to have synced completely without issue. I'll update at a future date if it happens again. Thanks!
