### ISSUE TITLE
2.1.0 Client on OS X 10.11.1 consumes 100 % cpu for 10 sec every 20 sec

### ISSUE THREAD

**Issue by regnauld** [owncloud/client#4305]
I have about 6100 files synced and until the recent upgrade, I never noticed ownCloud running in the background. After upgrading to 2.1.0, the CPU temp, never goes below 65, and the fans spin up to audible level. Immediately after quitting

Top shows 100% hard CPU use by owncloud for roughly 10 seconds, every 20 seconds.

After quitting the owncloud client, CPU temp is 55% and fans have quieted down (2000 rpm instead of 5000)

**Comment by regnauld** [comment]
This is somewhat related to https://github.com/owncloud/client/issues/4294 as moving the bearer plugin out of the way and restarting owncloud fixes the issue.

**Comment by guruz** [comment]
Thanks, closing as duplicate

FYI @dragotin
