### ISSUE TITLE
[Linux] Client ignores files without obvious reason

### ISSUE THREAD

**Issue by egore** [owncloud/client#4306]
When syncing files the owncloud client ignores a couple of files without telling why they were ignored (e.g. which rule caused it).

![no_reason](https://cloud.githubusercontent.com/assets/835951/11920460/cd478624-a770-11e5-9e1d-caba6da77ba7.png)

From a quick look at syncengine.cpp the variable "_errorString" is set for a couple of cases (but not all of them) but is not shown in the UI at any place. Maybe this could be a starting point?

**Comment by dragotin** [comment]
Can you at least make the file names visible? Or better provide a log file...? Thanks

**Comment by guruz** [comment]
What do you see when clicking "Edit ignored files" in the settings?

**Comment by egore** [comment]
This isn't about this particular issue with my files, it's about how we could improve the UX for telling the user why files are ignored.

Nonetheless I started to dig around why it might fail and found the following cause:

*Files with no modification timestamp are not synchronized*

$ ls -l
-rw-r--r-- 1 cbrill users 668967 May  1  2009 DSC00041.JPG
-rw-r--r-- 1 cbrill users 706684 Jan  1  1970 DSC00042.JPG

DSC00041.JPG properly syncs, DSC00042.JPG does not. The following command causes the sync to finally happen:

$ touch DSC00042.JPG

**Comment by dragotin** [comment]
@egore that is interesting, DSC00042.JPG has a "broken" modification time, it is 0 (zero), which translates to 1.1.70. How come?

Equally interesting why the file has this mod time is why the client does not properly handle that. We need to investigate that.

**Comment by guruz** [comment]
Dup https://github.com/owncloud/client/issues/1603

But yes, it should report with a better reason.
