### ISSUE TITLE
Working Build instructions for Raspberry Pi?

### ISSUE THREAD

**Issue by withit** [owncloud/client#4307]
apt-get installs 1.7.0~beta1+really1.6.4+dfsg-1+deb8u1 for Debian on a Raspberry Pi, but I'd like to install the current client if possible (i.e., 2.1.0).

```
pi@host ~ $ cat /etc/*-release
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

The instructions for building the client in the [Owncloud Client Manual] (https://doc.owncloud.org/desktop/2.1/building.html#) fail at **apt-get build-dep owncloud-client** with 
```
E: Unable to find a source package for owncloud-client
```
Meanwhile, the instructions by sgripon at [Building owncloud client for Raspberry pi's raspbian] (https://wiki.sgripon.net/doku.php?id=building_owncloud_client_for_raspberry_pi) are only for the 1.7.0 client, and the [wget] (http://download.owncloud.com/download/mirall-1.7.0.tar.bz2) at step two fails with 404.

Is there a working set of instructions available for building the client on a Raspberry Pi?

**Comment by RealRancor** [comment]
Hi,

this is a bugtracker where bugs and features requesrs are reported. If you have trouble following the available build instructions you should ask for support at https://mailman.owncloud.org/mailman/listinfo/devel

**Comment by withit** [comment]
So I should add the following?
```
echo 'deb-src http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/ /' >> /etc/apt/sources.list.d/owncloud-client.list 
```

**Comment by danimo** [comment]
@withit Yes.

**Comment by carlaschroder** [comment]
Like this?

echo 'deb-src http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/ /' >> /etc/apt/sources.list.d/owncloud-client.list
apt-get update
apt-get build-dep owncloud-client

**Comment by RealRancor** [comment]
@carlaschroder Yes, that should work. https://doc.owncloud.org/desktop/2.1/building.html#linux only mentions "Add the ownCloud repository from OBS." (which doesn't contain the deb-src line) and "Debian/Ubuntu: apt-get update; apt-get build-dep owncloud-client"

**Comment by carlaschroder** [comment]
Closing, as the instructions on https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client need to be updated with the deb-src line. I'll ping Juergen.

**Comment by carlaschroder** [comment]
Oh duh, why are we doing this the hard way. Get the source tarball from

**Comment by carlaschroder** [comment]
OK, I see source packages on OBS. Kicking over to Juergen to update the instruction on OBS.

**Comment by jnweiger** [comment]
Ah, that is next to impossible. sorry.

The instructions at https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client are not under our control.
The instructions are generated at opensuse.org as part of their build service.

@digitaltom do you provide source links elsewhere?

See also: https://github.com/owncloud/client/issues/4349
We already have pending obvious bugs there: Wrong order of instructions, CentOS_7 inside Fedora, ...

**Comment by jnweiger** [comment]
Ah, the software download page presents the sources as binaries. 

You find it when you look for 'Grab binary packages directly' after selecting a Platform. 

For Fedora, I see the src.rpm literally hiding between the binary RPMs.

<pre>
Packages for Fedora 23: 	
    owncloud-client-2.1.1-1.1.i686.rpm
    owncloud-client-2.1.1-1.1.src.rpm
    owncloud-client-2.1.1-1.1.x86_64.rpm
....
</pre>

**Comment by digitaltom** [comment]
You can change the content of those pages here: https://github.com/openSUSE/software-o-o/tree/master/app/views/download
Greetings!

**Comment by carlaschroder** [comment]
PR for client manual: https://github.com/owncloud/client/pull/4509
