### ISSUE TITLE
Sharing with Federated users is not working on WIN

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4311]
# Tests Desktop Client v2.1.0 with oC Server v8.2.2 (stable) with WINDOWS 2008 R2 Enterprise

TestID | Desktop v | Server v | | Result
------------ | ------------- | -------------- | ----- | ------
1 | 2.1.0 |  8.2.2 | 1. Two differents certificated servers (HTTPS) 2. Create a new folder 3. Share with users and groups with one certificate server | **F(WIN), P(MAC)**|
2 | 2.1.0 |  8.2.2 | 1. Two differents certificated servers (HTTP) 2. Create a new folder 3. Share with users and groups with one certificate server | **F(WIN), P(MAC)**|
3 | 2.1.0 |  8.2.2RC1 | 1. Two differents servers (HTTP) 2. Create a new folder 3. Share with users and groups with normal server | **F(WIN), P(MAC)**|

Logs with two differents certificated servers (HTTPS):
```
12-22 11:11:55:332 0x4481430 OCC::OcsJob::finished: Reply to "POST"  QUrl( "https://xxxxxx/ocs/v1.php/apps/files_sharing/api/v1/shares" )  (QPair("path","/\aaa"), QPair("shareType","6"), QPair("shareWith","admin@xxxxxx”)) has unexpected status code: 403 "{"ocs":{"meta":{"status":"failure","statuscode":403,"message":"Se fall\u00f3 al compartir \\aaa. No se pudo hallar admin@xxxxx, quiz\u00e1s haya un problema de conexi\u00f3n con el servidor."},"data":[]}}"
12-22 11:11:55:503 0x4481430 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareeJob created for "https://docker.oc.solidgear.es" + "ocs/v1.php/apps/files_sharing/api/v1/sharees"
```

**Comment by Dianafg76** [comment]
cc/ @PVince81 @cmonteroluque @DeepDiver1975 @davitol @rullzer

**Comment by Dianafg76** [comment]
Logs with two differents certificated servers (HTTP)
```
12-22 11:29:41:397 0x4481430 OCC::OcsJob::finished: Reply to "POST"  QUrl( "http://xxxxxxxx/ocs/v1.php/apps/files_sharing/api/v1/shares" )  (QPair("path","/\jesus"), QPair("shareType","6"), QPair("shareWith","admin@xxxxxxxx”)) has unexpected status code: 403 "{"ocs":{"meta":{"status":"failure","statuscode":403,"message":"Sharing \\jesus failed, could not find admin@xxxxxx, maybe the server is currently unreachable."},"data":[]}}"
12-22 11:29:41:475 0x4481430 OCC::AbstractNetworkJob::start: !!! OCC::OcsShareeJob created for "http://xxxxxxxxx” + "ocs/v1.php/apps/files_sharing/api/v1/sharees"
12-22 11:29:46:600 0xf511040 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QTcpSocket(0xb6167b0) QObject(0x0)  0 false 3 0 QAbstractSocket::UnconnectedState
12-22 11:29:52:209 0x4481430 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (No se encontró el proceso especificado.)
12-22 11:29:52:209 0x4481430 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001
```

**Comment by rullzer** [comment]
Can you share with that user from the webinterface?

**Comment by cmonteroluque** [comment]
it works, as per @davitol

**Comment by guruz** [comment]
Are you sure there is a behaviour difference between trying to share via Windows and trying to share via Mac?
The log message sounds like the server can't reach the other server?

**Comment by Dianafg76** [comment]
@guruz On MAC it is working ok, but on WIN is not working

**Comment by Dianafg76** [comment]
@guruz I tested again on Win and you can see the same error
```
12-22 13:52:26:179 0x4481430 OCC::OcsJob::finished: Reply to "POST"  QUrl( "https://xxxxxx/ocs/v1.php/apps/files_sharing/api/v1/shares" )  (QPair("path","/\new folder share"), QPair("shareType","6"), QPair("shareWith","admin@xxxxxx”)) has unexpected status code: 403 "{"ocs":{"meta":{"status":"failure","statuscode":403,"message":"Se fall\u00f3 al compartir \\new folder share. No se pudo hallar admin@xxxxx, quiz\u00e1s haya un problema de conexi\u00f3n con el servidor."},"data":[]}}"
```

**Comment by rullzer** [comment]
I don't really get where that `/\` is coming from. Maybe it is a windows encoding issue?

**Comment by Dianafg76** [comment]
I tested this issue and now it is working OK
# Tests Desktop Client v2.1.0 with oC Server v8.2.2 (stable) with WINDOWS 2008 R2 Enterprise


TestID | Desktop v | Server v | | Result
------------ | ------------- | -------------- | ----- | ------
1 | 2.1.1 |  8.2.2 | 1. Two differents certificated servers (HTTPS) 2. Create a new folder 3. Share with users and groups with one certificate server | **P(WIN)**|
2 | 2.1.1 |  8.2.2 | 1. Two differents certificated servers (HTTP) 2. Create a new folder 3. Share with users and groups with one certificate server | **P(WIN))**|

Desktop v ownCloud-2.1.1.5755-nightly20160107-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}

Closed
