### ISSUE TITLE
Certain files are not uploaded successfully by Windows Owncloudclient

### ISSUE THREAD

**Issue by Franz47** [owncloud/client#4313]
I noticed that certain files cannot be synchronized with the Windows client at my owncloud at owncloud provider owncube.com
At first I noticed it with about 20 MB sized pdf-files, which the client could not upload. Via owncloud-webinterface the same files could be uploaded manually.
As a test I have tried whether the client synchronizes a 720 MB mp4 video file. The owncloud windows client fails again.
The relevant error messages of the client about unsynchronized files contain always the word "chunking" and "internal server error". 
Typical error messages are
23.12.2015 08:34:07Test/SOKO Köln-Blutige Abrechnung-2047040431.mp4                D:\Onlinespeicher\jussiowncubeBlacklisting fortsetzen: Error downloading https://********.owncube.com/remote.php/webdav/Test/SOKO Köln-Blutige Abrechnung-2047040431.mp4-chunking-4066447186-145-2 - server replied: Internal Server Error
23.12.2015 08:30:51Test/SOKO Köln-Blutige Abrechnung-2047040431.mp4                D:\Onlinespeicher\testowncube Error downloading https://**********.owncube.com/remote.php/webdav/Test/SOKO Köln-Blutige Abrechnung-2047040431.mp4-chunking-4066453154-145-0 - server replied: Internal Server Error
The same video file could be uploaded without problem at my owncloud at hoster world4you.com.
Client version 2.1.0 (build 5683)
I tried to get support from owncube.com but they do not support the owncloud own syncing client but suggest to user other generic sync clients and would not give support for the owncloud client.
Any idea?

**Comment by xshadow** [comment]
Sounds like the problem I reported yesterday #4312

Could you try to setup a local proxy like [https://www.charlesproxy.com/](charlesproxy)

Enable SSL Proxying in charles and configure your owncloud client to use this local proxy? 

Maybe the authentication header is also missing.

**Comment by guruz** [comment]
What is in the server ```owncloud.log```?

**Comment by Franz47** [comment]
https://www.dropbox.com/s/wu82nctj21l25y5/owncloud20151224_1207.log?dl=0 is the link to the log file from my admin webinterface set to give  maximal info content. I could not find a separate "error" log.
I have also uploaded the same file here after attaching the extension txt
[owncloud20151224_1207.log.txt](https://github.com/owncloud/client/files/71683/owncloud20151224_1207.log.txt)

**Comment by Franz47** [comment]
@xshadow  - I have installed the charles proxy and (I think) it is working with the client. I have four owncloud servers configured in the client, but have only activated the one with the problems. I will let it try to synchronize vor a while. What can I do to use info the proxy collects?

**Comment by xshadow** [comment]
@Franz47 you have to set in the owncloud -> network settings -> specify proxy manually as -> HTTP(S) Proxy -> 127.0.0.1 : 8888

Then you should enable SSL proxy in charles: Proxy --> SSL Proxy Settings --> Enable SSL Proxying 

You upload a big file , that will be chunked and you have to look into the remote.php/webdav folder with charles. There should be an error. Click on it and look into Request (overhead) / Headers (below).

Paste a screenshot of working and not working chunk. Blur at least the Authorization Line!

**Comment by Franz47** [comment]
@xshadow thanks for the instructions. I have created a separate testuser area in my owncloud just for this purpose, where I will try to synchronize mainly files whicht could not be uploaded earlier. I have stopped synchronization of all other owncloud instances in the windows client so the error messages should only come from the testarea sync processes. So there should not be any problem with privacy? I have configured charles to save data every 5 minutes. I can put the files which have an error message into a dropbox link. Will that be informative?

**Comment by Franz47** [comment]
@xshadow 
Here the screenshots I presume to be relevant. 
![syncproblem1](https://cloud.githubusercontent.com/assets/5449616/12002890/a672cdac-ab0c-11e5-93bf-8c7e3964ccbe.png)
![syncproblem2](https://cloud.githubusercontent.com/assets/5449616/12002891/ad324e42-ab0c-11e5-93cd-b751f86b45dd.png)
![syncproblem3](https://cloud.githubusercontent.com/assets/5449616/12002892/ad578284-ab0c-11e5-9f45-ba56dc4eb044.png)
![syncproblem4](https://cloud.githubusercontent.com/assets/5449616/12002893/ad5cee68-ab0c-11e5-9bf1-f707b7780353.png)

**Comment by Franz47** [comment]
![syncproblem5](https://cloud.githubusercontent.com/assets/5449616/12002928/12026e3c-ab0e-11e5-885d-c02dbd46cc36.png)
![syncproblem6](https://cloud.githubusercontent.com/assets/5449616/12002932/2dfa77e2-ab0e-11e5-8246-4d35f6d9ba4e.png)

**Comment by guruz** [comment]
That server side logfile contains a lot of messages like
```
Class 'OC_FileChunking' not found at .....\/public_html\/lib\/private\/connector\/sabre\/objecttree.php#82
```
@PVince81  ?

It however does _NOT_ contain the ```No basic authentication headers were found``` message that @xshadow reported.

**Comment by guruz** [comment]
@xshadow Thanks a ton for the initial clue. Let's track in https://github.com/owncloud/client/issues/4326#issuecomment-169282743 !
