### ISSUE TITLE
[Fedora upstream packages] Linux Client suddenly disconects with a "connection reset by peer"

### ISSUE THREAD

**Issue by JustDevZero** [owncloud/client#4316]
Hi,

I was installing Owncloud for a friend and found something that it bugs me a little and I'm not able to detect how to solved.

There is a Nginx Server installed in a ARM machine (not raspberry, but cubieboard), compiled with web_dav support.

The config is attached.

When you try to use the client from owncloud-client found in fedoras repos, it just fails, throwing a conection reset by peer, the same happen with client from:
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

What is strange is that the (I think old package), Mirall client just works, but then suddenly without any reason it fail agains, bugging that message:

"An internal error number 1060 happend. Could not read chunk size: Secure connection truncated. 

Anyway, the error in nginx logs is always the same as for the error since begining, and for the suddenly disconnection with Mirall client.

2015/12/25 03:55:46 [error] 1312#0: *42 readv() failed (104: Connection reset by peer) while reading upstream, client: 192.168.1.131, server: home.localdomain, request: "PROPFIND /remote.php/webdav HTTP/1.1", upstream: "fastcgi://unix:/var/lib/php5-fpm/web8.sock:", host: "home.localdomain"

[php.conf.txt](https://github.com/owncloud/client/files/72012/php.conf.txt)
[nginx-cloud.conf.txt](https://github.com/owncloud/client/files/72013/nginx-cloud.conf.txt)

**Comment by RealRancor** [comment]
Hi,

i think thats mostly caused by timeouts happening on server site. Either within your webservers config or within your PHP environment.

Are you able to see differences between small files not taking a long time and larger files?

**Comment by JustDevZero** [comment]
I just put more execution_time on server just in case, watching if there is any difference between large and small files but still nothing.

Indeed it appears to happen no matter size, there were "large files" (1MB) that weren't stuck and others lesser than 100KB that stucks.

As for the mirall log:
http://ur1.ca/ocyjt

Owncloud log in verbose:
http://ur1.ca/ocyk1

In the owncloud log blames all time about:
HTTP\\\/1.1 401 No basic authentication headers were found

Maybe it's losing it's authentification somewhere?

**Comment by guruz** [comment]
> There is a Nginx Server installed in a ARM machine (not raspberry, but cubieboard), compiled with web_dav support.

ownCloud server has its own WebDAV code, you should/must not configure the web server with WebDAV too!

Did you have a look at https://doc.owncloud.org/server/8.2/admin_manual/installation/nginx_configuration.html ?


> As for the mirall log:
> http://ur1.ca/ocyjt

I believe this is log output from an old client version. Could you provide log with 2.1?

**Comment by JustDevZero** [comment]
Indeed @guruz  the log was from Mirall 1.X, because the new client wasn't able to connect.

I removed the webdav conf code as you sugest from nginx but still nothing.

BUT something had changed in someway in the owncloud-client package update from today, cause just after updating it it's uploading things by his own. Maybe was there some kind of mix problem? Server and client side?

Anyways, for now it seems to work with this client:
ownCloud version 2.1.0
Using Qt 5.5.1

Repo:
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

The one from Fedora's default repo doesn't work :(

**Comment by brozkeff** [comment]
Isn't the old client using the old Qt which has the bug that caused the file corruptions (https://github.com/owncloud/client/issues/2425) and so there is a workaround in the clients using such Qt to cancel the connections that were identified as being problematic? The client log should contain the line "Forcing job abort on HTTP connection reset with Qt < 5.4.2." in such case.
