### ISSUE TITLE
Feature Request: Update notification for ownCloud Server

### ISSUE THREAD

**Issue by MeCias** [owncloud/client#4317]
Hi,

I think it might be useful to get an update notification as long you are linked with an admin account and there is a new version of ownCloud available.

The issue I see is that, if you not all day long on github or the ownCloud forum or even in your own ownCloud server, you might miss that there is a new Version available and if you skip one or two versions you might run in update troubles.

**Comment by guruz** [comment]
@MeCias nice idea. I think there is also a mailing list for announcements you can subscribe to.. @jospoortvliet

 @PVince81 @LukasReschke this could be exposed in the capabilities API.

**Comment by jospoortvliet** [comment]
Yeah, there's https://mailman.owncloud.org/pipermail/announcements/ but perhaps the client could also ping about this.

**Comment by LukasReschke** [comment]
> @PVince81 @LukasReschke this could be exposed in the capabilities API.

What do you need? Only a boolean (`isUpdateAvailable => false`) or some more information? Also we would obviously only show this for admins. For regular users it would always return `false`.

**Comment by guruz** [comment]
This is done these days with the announcements app
