### ISSUE TITLE
Android Client: Duplication of data fills phone storage

### ISSUE THREAD

**Issue by thorsig** [owncloud/client#4319]
When the OwnCloud client is used to auto-upload pictures and videos taken on an Android phone, it creates duplicates of said pictures and videos when it synchronizes back. It should not do this. Instead it should create a symbolic link for the uploaded image/video so that storage may be preserved - especially since by default OwnCloud uses the internal storage which may be small even though the camera application uses the external storage.

In my case I had to stop using the OwnCloud Android client since duping 7.some GB wasn't going to work on my device. Very unfortunate.

**Comment by RealRancor** [comment]
@thorsig This is the issue tracker of the Desktop Client for Windows, Linux and Mac OS X. The issue tracker of the android client is located here:

https://github.com/owncloud/android/issues

There you can find an existing issue about this problem: https://github.com/owncloud/android/issues/819 which seems to be solved with one of the upcoming android client versions.
