### ISSUE TITLE
Support to-SSL-redirect (HTTP 302)

### ISSUE THREAD

**Issue by nille02** [owncloud/client#4320]
My Initial OC Configuration was http only (lack of a trusted CA and now Lets Encrypt). After forceing SSL/TLS (Redirect to ssl/tls in the Webserver config) the Windows Sync Client stopped working and i had to delete and create the connection new. 

The Android Version (The File Sync and the News Client) don't have a problem like this.

**Comment by guruz** [comment]
What kind of redirect are you doing? 301? 302?

**Comment by nille02** [comment]
Its 301 permanent.

**Comment by ogoffart** [comment]
Duplicate of one of the many issues in  #2791
