### ISSUE TITLE
[OS X] [2.1] Sync Error "Connection Closed"

### ISSUE THREAD

**Issue by TheOtterslider** [owncloud/client#4322]
Here's some details:

Client - 2.1.0. build 2944 (Mac 10.11.3)
Server - Upgraded yesterday to 8.2.2 (on CentOS)

Pre upgrade, I had been running CLient 1.7.1 (on Mac 10.11.3) and Server 8.. Sorry I don't remember.

I had been running Client 1.7.1 because of this issue: owncloud/client#3313 and owncloud/client#3248

Here's what happens. My Sync client tries to sync and immediately (without trying to sync) disconnects with an error "Connection Closed",

I've got a log file made ready to send it. I'd love to email it to someone. The thing is about 47MB big and there's several different errors in it. I'm not real sure where to start.

If you want more information, see https://github.com/owncloud/core/issues/21380 (reported it in the core...not here)

**Comment by guruz** [comment]
From what I've seen, a lot can influence this.
What is your webserver and php setup?
Could the SSL library or enabled cryptos on the server influence this?
Do you have anything in the webserver's error.log or in php-fpm.log or in owncloud.log?
If those files have nothing suspicious, we can try to look at the client log file (you can e-mail it or e-mail me a owncloud public share link)

**Comment by guruz** [comment]
It would be interesting to try to completely switch your setup just for testing.

Apache with mod_php <-> nginx with php-fpm
SSL <-> no SSL
ownCloud encrypted storage <-> ownCloud plain storage

**Comment by TheOtterslider** [comment]
Here's some info:
Server configuration

Operating system: CentOS release 6.6 (Final)

Web server:Server version: Apache/2.2.15 (Unix)

Database: MySQL 5.1.73 Source distribution

PHP version:PHP 5.6.11 (cli)

ownCloud version: 8.2.2

Updated from an older ownCloud or fresh install: upgrade

List of activated apps:

If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
[xxxx@xxxx ~]# sudo -u apache php /var/www/html/owncloud/occ app:list
Enabled:

activity: 2.0.1
calendar: 0.8.1
contacts: 0.5.0.0
documents: 0.11.0
files: 1.1.9
files_external: 0.2.3
files_pdfviewer: 0.7
files_sharing: 0.6.2
files_texteditor: 2.0
files_trashbin: 0.6.3
files_versions: 1.0.6
files_videoviewer: 0.1.3
firstrunwizard: 1.1
gallery: 0.6.0
templateeditor: 0.1
updater: 0.6
Disabled:

admin_dependencies_chk
bookmarks
calendar_old
contacts_old
encryption
external
files_encryption
files_locking
notifications
provisioning_api
search_lucene
user_external
user_ldap
user_webdavauth
The content of config/config.php:

If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder
[xxxx@xxxx ~]# sudo -u apache php /var/www/html/owncloud/occ config:list system
{
    "system": {
        "instanceid": "oc8e61b24903",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "MYDOMAIN"
        ],
        "datadirectory": "\/DATADIR",
        "overwrite.cli.url": "https:\/\/MYDOMAIN\/owncloud",
        "dbtype": "mysql",
        "version": "8.2.2.2",
        "dbname": "owncloud",
        "dbhost": "localhost",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "installed": true,
        "forcessl": true,
        "mail_from_address": "admin",
        "mail_smtpmode": "php",
        "mail_domain": "MYDOMAIN",
        "theme": "",
        "maintenance": false,
        "secret": "***REMOVED SENSITIVE VALUE***",
        "singleuser": false,
        "loglevel": 0
    }
}

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
Are you using external storage, if yes which one: local/smb/sftp/...
NO

Are you using encryption: yes/no
NO

Are you using an external user-backend, if yes which one: LDAP/ActiveDirectory/Webdav/...
NO

**Comment by TheOtterslider** [comment]
Nothing interesting that I saw in the apache error log.

>Could the SSL library or enabled cryptos on the server influence this?
Could be.  I have my setup tweaked out a bit so there are some things I don't support (like XP or IE 6).  I'm still learning alot about managing crypto.  Any suggestions on things I could look at?  I can do the leg work to figure out how to actually do it....

I never thought about testing with no ssl.  Unfortunately, that isn't an option at the moment.  It will be 4 months before I can test that  :(  But, this is a longstanding issue....if it still happens then, I'll test it.

**Comment by guruz** [comment]
> Nothing interesting that I saw in the apache error log.

And in ```owncloud.log``` in the owncloud dir?

Are you using modphp or fastcgi? 

What about https://github.com/owncloud/core/search?q=%22Connection+closed%22&state=open&type=Issues&utf8=%E2%9C%93 ?

**Comment by TheOtterslider** [comment]
Thanks.  i'll look into those and get some more info over tonight or tomorrow.

I don't remember off-hand, but I think I'm using modphp.  It will be tomorrow or tonight before I can look at it.

**Comment by guruz** [comment]
@TheOtterslider Did you find the time? :)

**Comment by guruz** [comment]
> Are you using encryption: yes/no
> NO

In your app list I see the encryption apps though..

Have you checked out what @PVince81 @schiesbn wrote in https://github.com/owncloud/client/issues/4047#issuecomment-158889946 ?

**Comment by guruz** [comment]
> In your app list I see the encryption apps though..

Sorry, it was in the "Disabled" list. Did you ever have it enabled?

**Comment by guruz** [comment]
Let's track in https://github.com/owncloud/client/issues/4326#issuecomment-169282743 for now. It's a combined core/client issue IMHO.

**Comment by TheOtterslider** [comment]
Even though this is closed, I'll give some details:

No, I never had encryption enabled.
I'm looking into this; however, in with this, I had to do a total redo of my computer (long story).  I did a clean install of the newest client 2.1.0 build 2944.  So far, the sync has been running with no issues.  I'm going to let it finish syncing (150GB of stuff) and see what happens.
