### ISSUE TITLE
Client timeout when filename contains newline character

### ISSUE THREAD

**Issue by BobJonkman** [owncloud/client#4323]
Client timeout when filename contains newline character. Workaround: Removing the newline allowed the file to sync
### Expected behaviour

The file should be synced, the client should issue a warning about unusual and cross-platform incompatible filename
### Actual behaviour

Client times out, and synchronization stops, no useful client error message.
### Steps to reproduce
1.  Create filename with a newline character
2.  Begin client sync process
### Server configuration

Operating system:
# : uname -a

Linux irving 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt11-1+deb8u6 (2015-11-09) x86_64 GNU/Linux
# : lsb_release -a

No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 8.2 (jessie)
Release:    8.2
Codename:   jessie

Web server: 
Server Version: Apache/2.4.10 (Debian)
Server MPM: prefork
Server Built: Aug 28 2015 16:28:08

Database:  sqlite (default installation of server)

PHP version:
PHP 5.6.14-0+deb8u1 (cli) (built: Oct  4 2015 16:13:10) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies

ownCloud version:
ownCloud 8.2.2 (stable) 

Storage backend:
local storage
### Client configuration

Client version:
Version 2.1.0

Operating system:
$: uname -a
Linux zelazny 3.11-2-amd64 #1 SMP Debian 3.11.8-1 (2013-11-13) x86_64 GNU/Linux
Mon Dec 28 15:46:54

$: lsb_release -a
No LSB modules are available.
Distributor ID: LinuxMint
Description:    LMDE MATE Edition
Release:    1
Codename:   debian

OS language:
English (US)

Installation path of client:
$: which owncloud
/usr/bin/owncloud
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   (2 lines of log, looks like 4 lines because of embedded newline in filenames)
   12/28/15 1:37:58 PMbob jonkman gpc/RADIO/Politicians Off Air 
   Michael Harris, Kitchener-Conestoga MPP chats with Bob Jonkman,the Green Party candidate for Kitchener-Conestoga between interviews.jpgShared                        Connection Timeout
   12/28/15 11:42:20 AMbob jonkman gpc/RADIO/Politicians Off Air 
   Michael Harris, Kitchener-Conestoga MPP chats with Bob Jonkman,the Green Party candidate for Kitchener-Conestoga between interviews.jpgShared                        Operation canceled
2. Web server error log:
3. ownCloud log (data/owncloud.log):
   {"reqId":"gc8kUuQOQ9WrxYPRqAOC","remoteAddr":"192.168.1.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 400 File name contains at least one invalid character\",\"Exception\":\"OC\\Connector\\Sabre\\Exception\\InvalidPath\",\"Code\":0,\"Trace\":\"#0 \\/var\\/www\\/owncloud\\/lib\\/private\\/connector\\/sabre\\/lockplugin.php(71): OC\\Connector\\Sabre\\ObjectTree->getNodeForPath('Shared\\/bob jonk...')\n#1 [internal function]: OC\\Connector\\Sabre\\LockPlugin->getLock(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#2 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#3 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(456): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#4 \\/var\\/www\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \\/var\\/www\\/owncloud\\/apps\\/files\\/appinfo\\/remote.php(56): Sabre\\DAV\\Server->exec()\n#6 \\/var\\/www\\/owncloud\\/remote.php(137): require_once('\\/var\\/www\\/ownclo...')\n#7 {main}\",\"File\":\"\\/var\\/www\\/owncloud\\/lib\\/private\\/connector\\/sabre\\/objecttree.php\",\"Line\":112}","level":4,"time":"2015-12-28T18:33:45+00:00"}

**Comment by guruz** [comment]
@DeepDiver1975 Blacklist such filenames server side?
I don't think it's worth to try to support this client side..

**Comment by ogoffart** [comment]
Closing old issues which is most likely to be a server issue anyway.
