### ISSUE TITLE
Discovering really slow

### ISSUE THREAD

**Issue by MarcGro** [owncloud/client#4324]
Hi, 
discovering changes is really slow. It takes about 1 or 2 hours for 6Gb of data. I've looked here:
https://github.com/owncloud/client/issues/3510

and installed the last version Versie 2.1.1-nightly20151229 (build 2996), but it is still slow. It takes a few seconds for every folder to scan, also if there are only a few documents in a folder. 

Does caching on the server help? I'll have to check, I don't think caching is enabled at the moment. Any other solutions? 
thanks
Marc

**Comment by guruz** [comment]
You are using OS X?
In general the discovery speed is dependant on the number of requests to server (which is the amount of folders on the server) and the speed of each request.
You can check if a single request is slow e.g. by launching the client like this (in ```Terminal.app```) and then seeing how fast each request is:
```/Applications/owncloud.app/Contents/MacOS/owncloud --logfile -```
(with the -)

Did you let the discovery run through completely? In general, only the initial discovery will take some time.

**Comment by MarcGro** [comment]
Hi Guruz, 
yes I'm using OSX.  For 
264.981.535 bytes (266 MB on disk schijf) for 545 items
it takes like 9 secs:
12-29 11:23:25:265 0x7fad5d41f7f0 csync_walker: directory: /**n [inode=1876008]
12-29 11:23:25:344 0x7fad5d41f7f0 csync_ftw:  <= Closing walk for /***n with read_from_db 0

Yes, I let the discovery run through, after that it started syncing (it appeared that syncing itself was slower in this version, like what was reported in #3510). I've aborted syncing to start up with the logfile.

I know that it is only the initial discovery, but everytime I make a change on the shared disk (for example adding a shared folder with a new user group), it starts syncing all the clients entirely from the start. This causes a lot of problems (around 10 users)

Furthermore, sometimes during the discovery time something goes wrong (e.g. connection problem) and it starts from the beginning again.

**Comment by guruz** [comment]
For measuring the request time I meant the sequences which look like this:

```
12-29 12:19:45:601 0x7fc0a255c850 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x7fc0a5324990)  Calling into main thread...
12-29 12:19:45:601 0x7fc0a0439ce0 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://www....." + ""
12-29 12:19:47:202 0x7fc0a0439ce0 OCC::DiscoveryMainThread::singleDirectoryJobResultSlot: void OCC::DiscoveryMainThread::singleDirectoryJobResultSlot(const QList<OCC::FileStatPointer> &) Have 625 results for  ""
12-29 12:19:47:202 0x7fc0a255c850 OCC::DiscoveryJob::remote_vio_opendir_hook: OCC::DiscoveryJob(0x7fc0a5324990)  ...Returned from main thread
```

I think you pasted from the local discovery.

> Furthermore, sometimes during the discovery time something goes wrong (e.g. connection problem) and it starts from the beginning again.

https://github.com/owncloud/client/issues/2976 (@dragotin )

**Comment by guruz** [comment]
@MarcGro Also if you use the latest server version make sure to have the correct locking app and Redis configured.
https://doc.owncloud.org/server/8.1/admin_manual/configuration_files/files_locking_transactional.html

**Comment by MarcGro** [comment]
ok thank you. We haven't got time to look at it, but we definitely will

**Comment by ogoffart** [comment]
Whats the version of the owncloud server?
Are we talking about the local or the remote discovery?
What are the logs saying?
Please use the issue template while reporting bugs: https://raw.githubusercontent.com/owncloud/client/master/issue_template.md

I suspect this is simply due to the server being slow.

**Comment by guruz** [comment]
ok, let's have this reopen if there is more info
