### ISSUE TITLE
[Share options] I want to decide whether share with users is shown or not

### ISSUE THREAD

**Issue by rperezb** [owncloud/client#4325]
AC:
- Include a variable that defines whether the share with user option is shown or not.
- In case it´s set not to be shown, on the UI it won't be shown the "share with users or groups" field

Bonus track:
- For parity with mobile apps it would be great to have another variable to define whether the share with link option is shown, being both of them independent. 

Reference:
https://github.com/owncloud/ownbrander/issues/483

**Comment by MTRichards** [comment]
Need to add share with link as well, and then enable one, the other or both to be enabled.

**Comment by MTRichards** [comment]
So to be clear:
1) admin can turn a setting on or off, in ownBrander, and sharing is allowed.
2) admin can turn a setting on or off, in ownBrander, and share links are allowed.

It is possible that both are off, so sharing is not possible form the desktop client, or that one or the other is on or off.
