### ISSUE TITLE
Don't interrupt sync if a server error is encoutered

### ISSUE THREAD

**Issue by strugee** [owncloud/client#4328]
My ownCloud server occasionally denies requests to certain resources with various HTTP errors. (Don't have any examples on hand, sorry.) There are some different things going on here - some are probably bugs in core and some are probably misconfigurations on my end.

In any case, when the client encounters these errors, it immediately treats them as fatal. This means that my sync will complete up to a certain point, and then never work again unless I manually intervene and disable syncing of the misbehaving directories. This shouldn't happen, because the rest of the server is functioning just fine.

**Comment by guruz** [comment]
You need to give more detail which errors, especially which HTTP code they send. HTTP 50x errors should for example not stop the sync.

**Comment by strugee** [comment]
@guruz I'll double-check to make sure but IIRC I was getting 503 Service Unavailable when syncing my Dropbox connection.

**Comment by strugee** [comment]
@guruz I can't seem to reproduce this anymore. I'll report back if I end up seeing it again, but I'm 99% sure that was the error I got.

**Comment by guruz** [comment]
Ok, just reopen then :)
