### ISSUE TITLE
Client overwrites permissions (group ownership) of file on syncing down

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#4330]
I have an admittedly strange-use case which leaves me with this issue, see https://github.com/owncloud/core/issues/21414 (TL;DR dogfooding ownCloud, it’s for a good cause)

Basically, the permissions of a file are user:www-data, and need to stay that way. The initial state is:
```
-rw-rw-r-- jan www-data Testnote.txt
```
Then I change something on my remote ownCloud installation. When it syncs down to my laptop, this happens for a split second:
```
-rw-rw-r-- jan www-data Testnote.txt
-rw-rw-r-- jan jan      .Testnote.txt.~4e848539
```
And then the new state is this:
```
-rw-rw-r-- jan jan      Testnote.txt
```
Note the `jan:jan` permissions as opposed to the `jan:www-data` from before. This causes the file being not editable anymore from my local development instance, rendering the experiment useless.

Now the question: Is it necessary to change the permissions here? Don’t the user permissions suffice to change the file? This does _not_ happen when a local file with these modified permissions is synced up to the remote ownCloud server – hence I assume it’s not necessary for the client to mess with the permissions.

**Comment by Yamakasi** [comment]
I have seen that files were changed from rw-r-r to r-r-r

Need to check if it happens again as I don't know what the default ones were, but as it was a config file it was for sure not r-r-r. This happened on a OSX Client.

**Comment by ckamm** [comment]
@jancborchardt The client currently tries to preserve the file permissions but does not attempt to preserve the group ownership. Improving that seems like a good idea. (there's more metadata we might want to preserve, like acls?)

@Yamakasi That's different. The client should remove write permissions of files that the server announces as read-only. Any change would be reverted during the next sync anyway. If there's a bug with that, could you make a new issue?
