### ISSUE TITLE
  access denied error for deleted files

### ISSUE THREAD

**Issue by kgpd123** [owncloud/client#4333]
I have OC 8.2.2 installed on CentOS7. web access and linux client syncing are ok. However I'm having the following syncing issue on windows clients (version 2.1.0). I have tried multiple PCs with different accounts and the same problem exists. Problem isn't there for the same user with linux client.

1. user1 gives only 'can share' access for a folder to user2
2. user2 sees the folder and contents synced using the windows client
3. user1 deletes a file inside this folder
4. user2's sync client reports access denied error for the deleted file and it never gets deleted from his PC
5. error disappears if one of the following is done
- user1 gives 'can edit' permission to user2 for the folder
- user2 manually deletes the file on the PC

**Comment by guruz** [comment]
Is this related to https://github.com/owncloud/client/issues/4308 ?

**Comment by kgpd123** [comment]
I think this is related to 4308 where modifications cannot be synced back to a windows user who has read only permission.

**Comment by ckamm** [comment]
This looks like it's fixed as a consequence of #4277. Could you test it with a nightly build? https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/owncloud-client

**Comment by kgpd123** [comment]
Sorry, I couldn't find a build for windows?

**Comment by ckamm** [comment]
@kgpd123 Sorry, the windows nightlies are at http://download.owncloud.com/desktop/daily/

**Comment by kgpd123** [comment]
Unfortunately problem is still there with the Version 2.1.1-nightly20160105 (build 5749).
![access_denied](https://cloud.githubusercontent.com/assets/16539093/12112150/9942624e-b392-11e5-99cf-4c0d0c4559e6.JPG)

**Comment by guruz** [comment]
@kgpd123 FYI https://github.com/owncloud/client/issues/4308#issuecomment-168965117

**Comment by ckamm** [comment]
@kgpd123 Thanks for testing! I did indeed address a bunch of related problems. Does build 5750 at http://download.owncloud.com/desktop/daily/ work better for you?

**Comment by kgpd123** [comment]
build 5750 works. Thanks! When will this be available as a release?

**Comment by ckamm** [comment]
@kgpd123 Thanks, I'm glad that helped. I don't really know about the release. Probably soon since there've been a lot of useful fixes and there are no serious unresolved gold tickets...

**Comment by davitol** [comment]
Tested in Version 2.1.1-nightly20160122 (build 3053) and it also worked for me

**Comment by boyan-sharic** [comment]
I had the exact same problem
oC version 8.2.2
client 2.1.0
I just updated with version 2.1.1.5835 and it seams just fine - problem 'Access denied' is gone.
