### ISSUE TITLE
[Fedora] [abort] [Qt5] owncloud-client: QXcbWindow::setParent(): owncloud killed by SIGSEGV when clicking on SSL button

### ISSUE THREAD

**Issue by Germano0** [owncloud/client#4335]
Hi, I am the Fedora's owncloud-client co-maintainer. I just received a bugreport from an Owncloud user
https://bugzilla.redhat.com/show_bug.cgi?id=1295966
the kind of crash reminds me Qt bug https://bugreports.qt.io/browse/QTBUG-50081
Do you confirm that is a Qt bug and that it is not an owncloud-client bug?
Thank you very much

**Comment by ogoffart** [comment]
I cannot reproduce the problem on my Qt 5.5.1
What's the Qt version in fedora?

**Comment by ckamm** [comment]
@ogoffart His DSO list shows Qt 5.5.1 being loaded.

**Comment by ogoffart** [comment]
What are the steps to reproduce?

**Comment by ogoffart** [comment]
Yes, this is probably https://bugreports.qt.io/browse/QTBUG-50081 n in there they mention that fedora backported the changes to Qt that causes the crash.

**Comment by Germano0** [comment]
Ok thank you very much for your support
