### ISSUE TITLE
Cannot talk to server. "401 No basic authentication headers were found" and "Connection closed"

### ISSUE THREAD

**Issue by bhcopeland** [owncloud/client#4339]
When I try connect my client to the server, I get "connection closed". My client is Arch Linux, 2.1.0-2.

I have tried this on a Mac OS X client too. I also tried the nightly build from https://github.com/owncloud/client/issues/4326, but issue was still there.

Server:
Arch Linux
PHP 7 FPM
NGINX
NGINX CONF ( https://gist.github.com/bhcopeland/ca8857927c4cad44fbb5 ) 
REDIS

```
[error] 12128#12128: *1 readv() failed (104: Connection reset by peer) while reading upstream, client: 10.0.0.243, server: xxx request: "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:
```
owncloud.log
```
{"reqId":"LilhSsib0aOlInxrSyGc","remoteAddr":"10.0.0.243","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 401 No basic authentication headers were found\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\NotAuthenticated\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(154): Sabre\\\\DAV\\\\Auth\\\\Backend\\\\AbstractBasic->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#1 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/auth.php(127): OC\\\\Connector\\\\Sabre\\\\Auth->auth(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#2 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Plugin.php(118): OC\\\\Connector\\\\Sabre\\\\Auth->authenticate(Object(OC\\\\Connector\\\\Sabre\\\\Server), 'ownCloud')\\n#3 [internal function]: Sabre\\\\DAV\\\\Auth\\\\Plugin->beforeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#4 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#5 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#6 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#7 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#8 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/remote.php(137): require_once('\\\/usr\\\/share\\\/weba...')\\n#9 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Auth\\\/Backend\\\/AbstractBasic.php\",\"Line\":70}","level":0,"time":"2016-01-07T12:36:17+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/"}
```

**Comment by guruz** [comment]
@bhcopeland Can you make 100% sure that you have the build installed that is mentioned in https://github.com/owncloud/client/issues/4326#issuecomment-169298832 ? You can see the build number in the settings dialog.

Regarding Arch Linux: You need to have the patch mentioned in https://github.com/owncloud/client/issues/4326#ref-commit-ef9483c else it won't work.

**Comment by bhcopeland** [comment]
Thanks for the reply @guruz 

My MacBook laptop is running 2.1.1-nightly20160106 build 3013. But when adding server, it still says connection closed. 

As for Arch Linux, was a bit of a pain in the arse as I had to compile the client as there are no nightly Arch Linux builds. (FYI my [PKGBUILD](https://gist.github.com/3d7079d64a5c7575f814).

```
owncloud --version
ownCloud version 2.1.1git
Using Qt 5.5.1
```

Client log file:

```
01-07 14:54:14:903 20052 OCC::Application::setupLogging: "################## ownCloud en_GB () 2.1.1git"
01-07 14:54:14:903 20052 OCC::Application::setupTranslations: void OCC::Application::setupTranslations() Using "en_GB" translation
01-07 14:54:14:903 20052 OCC::SocketApi::SocketApi: SocketApi:  server started, listening at  "/run/user/1000/ownCloud/socket"
01-07 14:54:14:903 20052 OCC::FolderMan::FolderMan: setting remote poll timer interval to 30000 msec
01-07 14:54:14:903 20052 OCC::FolderMan::setupFoldersMigration: * Setup folders from  "/home/ben/.local/share/data//ownCloud/folders" (migration)
01-07 14:54:14:904 20052 OCC::ClientProxy::setupQtProxyFromConfig: Set proxy configuration to use system configuration
01-07 14:54:14:979 20052 OCC::Updater::getSystemInfo: Sys Info size:  93
01-07 14:54:15:081 20052 OCC::ownCloudGui::slotOpenSettingsDialog: No configured folders yet, starting setup wizard
01-07 14:54:15:096 20052 OCC::OwncloudWizard::slotCurrentPageChanged: Current Wizard page changed to  0
01-07 14:54:18:251 20052 OCC::PassiveUpdateNotifier::backgroundCheckForUpdate: virtual void OCC::PassiveUpdateNotifier::backgroundCheckForUpdate()
01-07 14:54:18:251 20052 OCC::OCUpdater::backgroundCheckForUpdate: virtual void OCC::OCUpdater::backgroundCheckForUpdate() checking for available update
01-07 14:54:18:251 20052 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
01-07 14:54:18:706 20052 OCC::PassiveUpdateNotifier::versionInfoArrived: Client is on latest version!
01-07 14:54:21:887 20052 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
01-07 14:54:21:887 20052 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://xxx" + "status.php" "OCC::OwncloudSetupWizard"
01-07 14:54:24:897 20052 OCC::SslErrorDialog::trustConnection: SSL-Connection is trusted:  true
01-07 14:54:24:899 20052 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(ContentNotFoundError) "Error downloading https://xxxx/status.php - server replied: Not Found" QVariant(int, 404)
01-07 14:54:24:899 20052 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
01-07 14:54:24:900 20052 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://xxxx" + "owncloud/status.php" "OCC::OwncloudSetupWizard"
01-07 14:54:24:900 20052 OCC::CheckServerJob::finished: Retrying with QUrl("https://xxxx/owncloud/status.php")
01-07 14:54:25:012 20052 OCC::CheckServerJob::finished: status.php returns:  QMap(("edition", QVariant(QString, ""))("installed", QVariant(bool, true))("maintenance", QVariant(bool, false))("version", QVariant(QString, "8.2.2.2"))("versionstring", QVariant(QString, "8.2.2")))   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x19c77c0)
01-07 14:54:25:012 20052 OCC::OwncloudWizard::appendToConfigurationLog: Setup-Log:  "<font color=\"green\">Successfully connected to https://xxxx/owncloud/status.php: ownCloud version 8.2.2 (8.2.2.2)</font><br/><br/>"
01-07 14:54:25:013 20052 OCC::OwncloudSetupWizard::slotOwnCloudFoundAuth: void OCC::OwncloudSetupWizard::slotOwnCloudFoundAuth(const QUrl&, const QVariantMap&)  was redirected to "https://xxxx/owncloud"
01-07 14:54:25:013 20052 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
01-07 14:54:25:013 20052 OCC::AbstractNetworkJob::start: !!! OCC::DetermineAuthTypeJob created for "https://bcc.linaro.org/owncloud" + "" "OCC::OwncloudSetupWizard"
01-07 14:54:25:124 20052 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(AuthenticationRequiredError) "Host requires authentication" QVariant(int, 401)
01-07 14:54:25:124 20052 OCC::DetermineAuthTypeJob::finished: virtual bool OCC::DetermineAuthTypeJob::finished() ""
01-07 14:54:25:126 20052 OCC::OwncloudWizard::slotCurrentPageChanged: Current Wizard page changed to  1
01-07 14:54:29:063 20052 OCC::OwncloudSetupWizard::slotConnectToOCUrl: Connect to url:  "https://bcc.linaro.org"
01-07 14:54:29:063 20052 OCC::OwncloudWizard::appendToConfigurationLog: Setup-Log:  "Trying to connect to ownCloud at https://bcc.linaro.org..."
01-07 14:54:29:064 20052 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://bcc.linaro.org/owncloud" + "/" "OCC::OwncloudSetupWizard"
01-07 14:54:29:064 20052 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
01-07 14:54:29:269 20052 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(RemoteHostClosedError) "Connection closed" QVariant(Invalid)
01-07 14:54:29:270 20052 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 0 ""
01-07 14:54:30:415 20052 OCC::OwncloudWizard::slotCurrentPageChanged: Current Wizard page changed to  -1
01-07 14:54:30:415 20052 OCC::OwncloudSetupWizard::slotAssistantFinished: Rejected the new config, use the old!
```

**Comment by guruz** [comment]
Your log output seems to be from git ```master``` branch, can you ```git checkout 2.1``` and recompile?

**Comment by bhcopeland** [comment]
We talking client right? 

"setupLogging: "################## ownCloud en_GB () 2.1.1git""

I install it from http://download.owncloud.com/desktop/daily/owncloudclient-2.1.1git.tar.xz

**Comment by bhcopeland** [comment]
I found a error in my server config which I fixed, now syncs.

I tried the old client and doesn't work, so the newer 2.1.1 did fixed my issue too.

Thanks!

Please push the fix ASAP ;-)

**Comment by guruz** [comment]
@bhcopeland Interesting, what was wrong in the config?
In case other people have the same issue..

**Comment by bhcopeland** [comment]
I had a problem with redis not working properly due to PHP 7.0 upgrade. 

There was a issue with the client too, as I can only get it to sync with the 2.1.1git version.

I am getting lots of "Unable to load dynamic library '\│n reset by peer) while reading upstream, client: 10.0.0.203, server: xxxx, request: "PUT /owncloud/remote.php/webdav/
/usr\/lib\/php\/modules\/posix.so" 

Looked at phpinfo and posix seems to be loaded:
```
posix

Revision	$Id: 547e93e58ead98dbbb1d44dbaf86513eb08ace3f $
```

However doesn't seem to be affecting syncing and is probably another issue. 

Thanks and sorry for the noise!

**Comment by bhcopeland** [comment]
I still can't fully sync: :(

```{"reqId":"pGaP1Ddudh3Ekx55WMIB","remoteAddr":"10.0.0.245","app":"webdav","message":"Exception: {\"Message\":\"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\\\"files\\\\\\\/a900c1b08acf39e035f6b3a43e7ab763\\\", 1, 1452255715, \\\"files\\\\\\\/a900c1b08acf39e035f6b3a43e7ab763\\\"]:\\n\\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\\\/a900c1b08acf39e035f6b3a43e7ab763' for key 'lock_key_index'\",\"Exception\":\"Doctrine\\\\DBAL\\\\Exception\\\\UniqueConstraintViolationException\",\"Code\":0,\"Trace\":\"#0 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/DBALException.php(116): Doctrine\\\\DBAL\\\\Driver\\\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException))\\n#1 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Connection.php(996): Doctrine\\\\DBAL\\\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOMySql\\\\Driver), Object(Doctrine\\\\DBAL\\\\Driver\\\\PDOException), 'INSERT INTO `oc...', Array)\\n#2 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(203): Doctrine\\\\DBAL\\\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\\n#3 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/db\\\/adapter.php(93): OC\\\\DB\\\\Connection->executeUpdate('INSERT INTO `oc...', Array)\\n#4 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/db\\\/connection.php(242): OC\\\\DB\\\\Adapter->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\\n#5 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/lock\\\/dblockingprovider.php(111): OC\\\\DB\\\\Connection->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\\n#6 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/lock\\\/dblockingprovider.php(156): OC\\\\Lock\\\\DBLockingProvider->initLockField('files\\\/a900c1b08...', 1)\\n#7 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/common.php(635): OC\\\\Lock\\\\DBLockingProvider->acquireLock('files\\\/a900c1b08...', 1)\\n#8 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(572): OC\\\\Files\\\\Storage\\\\Common->acquireLock('files\\\/linaro\\\/li...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#9 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(572): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/linaro\\\/li...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#10 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/files\\\/storage\\\/wrapper\\\/wrapper.php(572): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/linaro\\\/li...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#11 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1802): OC\\\\Files\\\\Storage\\\\Wrapper\\\\Wrapper->acquireLock('files\\\/linaro\\\/li...', 1, Object(OC\\\\Lock\\\\DBLockingProvider))\\n#12 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/files\\\/view.php(1902): OC\\\\Files\\\\View->lockPath('\\\/linaro\\\/linaro-...', 1)\\n#13 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/node.php(260): OC\\\\Files\\\\View->lockFile('\\\/linaro\\\/linaro-...', 1)\\n#14 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/lockplugin.php(77): OC\\\\Connector\\\\Sabre\\\\Node->acquireLock(1)\\n#15 [internal function]: OC\\\\Connector\\\\Sabre\\\\LockPlugin->getLock(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#16 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#17 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(456): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#18 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#19 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#20 \\\/usr\\\/share\\\/webapps\\\/owncloud\\\/remote.php(137): require_once('\\\/usr\\\/share\\\/weba...')\\n#21 {main}\",\"File\":\"\\\/usr\\\/share\\\/webapps\\\/owncloud\\\/3rdparty\\\/doctrine\\\/dbal\\\/lib\\\/Doctrine\\\/DBAL\\\/Driver\\\/AbstractMySQLDriver.php\",\"Line\":66}","level":4,"time":"2016-01-08T11:21:56+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/linaro\/linaro-its-tools\/ansible-playbooks\/per-service\/publishing\/roles\/common\/tasks\/main.yml"}```

**Comment by danimo** [comment]
@bhcopeland This looks like a problem with your database and locking. Please report this problem in the core issue tracker.
