### ISSUE TITLE
Add "blacklisted_files" to sync-exclude.lst

### ISSUE THREAD

**Issue by LukasReschke** [owncloud/client#434]
With oC 5.0 we gave the admin the possibility to configure the blacklisted files (e.g. to sync .htaccess or deny other files which was an often asked feature)
(https://github.com/owncloud/core/blob/master/config/config.sample.php#L35)

Could we sync this list with the client by exposing the list via status.php - what do you think @dragotin @danimo?

Additionally we should remove the hardcoded .htaccess from sync-exclude.lst

**Comment by nickvergessen** [comment]
Could be done via capabilities?

**Comment by ogoffart** [comment]
capabilities, or any other api call.
(you probably don't want the reply to capabilities to become too big)

**Comment by guruz** [comment]
> Additionally we should remove the hardcoded .htaccess from sync-exclude.lst

Why? because now it comes via blacklisted_files capabilities?

**Comment by nickvergessen** [comment]
> Why? because now it comes via blacklisted_files capabilities?

Yes it would then come from the server. If the server is not apache but nginx, there is no real reason to block `.htaccess`, it is just like any other hidden file then.

**Comment by nickvergessen** [comment]
value has been added to capabilities for 9.1+

**Comment by HanaGemela** [comment]
# Tested
Tested on macOS with 2.6.0-daily20190426 (build 11674)
sync-exclude.lst is synchronized with a client
sync-exclude.lst doesn't include .htaccess
