### ISSUE TITLE
Sync Client 2.2.0 Master Feature List

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#4342]
Current Master Plan for Next Client Feature Release:
- :exclamation:  New Chunking: In association with the new server WebDAV Endpoint, the client would implement a new chunking algorithm to match: #4007 
- :exclamation:  Transport Checksums: Test checksums between the client and server over the old and new webdav endpoints: #3735 
- :exclamation: Activities API Update: Updating the Activities API view to combine sync protocol with activity stream: #4208 
- [x] Desktop Client Notifications: Implement the new OCS notification API for system level messages to clients: #3733 
- :exclamation: Windows Roaming Profile Support: Investigate and implement windows roaming profile support. #684
- [x] Sharing Completion: Complete some of the UX questions around right click sharing from the desktop.
#3737 
- [x] Virtual Filesystem: Research into how to show a single interface to all files for a user anywhere in ownCloud. #4341

@karlitschek @cmonteroluque @dragotin @danimo @guruz @ogoffart @ckamm @Dianafg76

**Comment by rullzer** [comment]
The new chunking is not in 9.0

**Comment by rullzer** [comment]
Transport checksums are not implemented server side since we never verify them (https://github.com/owncloud/client/issues/3735#issuecomment-190104308)

**Comment by rullzer** [comment]
Sharing issue (https://github.com/owncloud/client/issues/3737) is done. All other stuff that pops up is either a new bug or new features to implement from my POV

**Comment by dragotin** [comment]
The new activity API is also not in place in 9.0.

**Comment by dragotin** [comment]
For windows roaming support, we lack input, see #684
