### ISSUE TITLE
[Windows XP] owncloud stops synchronizing in my netbook

### ISSUE THREAD

**Issue by estudioapa** [owncloud/client#4343]
I have in my netbook:
Server: 7.0.5
Client: 1.8.4
SO: XP

When I sync (root folder) in my netbook, synchronize well the first time  and then when try to re-sync,  displays "Operation canceled by user". The folder is 7 GB.

Attached a piece of log:

OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for "http://XXXXXXXXXX/cloud" + "/"
01-06 17:16:23:410 0x41fc7e0 OCC::FolderMan::slotEtagPollTimerTimeout: void OCC::FolderMan::slotEtagPollTimerTimeout() No folders need to check for the remote ETag
01-06 17:16:35:692 0x41fc7e0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
01-06 17:16:35:692 0x41fc7e0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "http://XXXXXXXXXX/cloud" + "/"
01-06 17:16:37:270 0x41fc7e0 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (No se encontró el proceso especificado.)
01-06 17:16:37:302 0x41fc7e0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

01-06 17:16:37:302 0x41fc7e0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
01-06 17:16:44:427 0x41fc7e0 OCC::AbstractNetworkJob::start: !!! OCC::CheckQuotaJob created for "http://XXXXXXXXXX/cloud" + "/"

**Comment by guruz** [comment]
We unfortunately don't support 1.8.4 anymore.
You can download a soon-to-be-2.1.1beta1 from http://download.owncloud.com/desktop/daily/ownCloud-2.1.1.5757-nightly20160108-setup.exe

In any case, you need to look for the error which is not "Operation canceled" (only the other transfers get cancelled)
