### ISSUE TITLE
Crash on Windows 10 clean install v2.1.0.5683 (server failure)

### ISSUE THREAD

**Issue by cscashby** [owncloud/client#4346]
OwnCloud client crashes not long after startup - fairly large client dataset around 170 GB - against Server version 8.3.

Some errors in server log:

Exception: {"Message":"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\"files\\\/1c21f1a5699694d9f93f26edf2121bb3\", 1, 1452534262, \"files\\\/1c21f1a5699694d9f93f26edf2121bb3\"]:\n\nSQLSTATE[23000]: Integrity constraint violation

And PHP errors:
unlink(FILENAME-chunking-1167022733-27): No such file or directory at /var/www/owncloud/lib/private/files/storage/local.php#190 

Note - the owncloud server has an NFS r/w automounted as a data source.

Reboot of server attempted and has not fixed the issue

Win10 Event log:

Log Name:      Application
Source:        Application Error
Date:          11/01/2016 16:44:53
Event ID:      1000
Task Category: (100)
Level:         Error
Keywords:      Classic
User:          N/A
Computer:      angela-laptop
Description:
Faulting application name: owncloud.exe, version: 2.1.0.5683, time stamp: 0x00000000
Faulting module name: libstdc++-6.dll, version: 0.0.0.0, time stamp: 0x3ea83ea3
Exception code: 0x40000015
Fault offset: 0x00021d32
Faulting process ID: 0x74c
Faulting application start time: 0x01d14c8f07623c39
Faulting application path: C:\Program Files (x86)\ownCloud\owncloud.exe
Faulting module path: C:\Program Files (x86)\ownCloud\libstdc++-6.dll
Report ID: 6b80937f-70dc-4983-9bb7-9e938dcc1d2f
Faulting package full name:
Faulting package-relative application ID:
Event Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Application Error" />
    <EventID Qualifiers="0">1000</EventID>
    <Level>2</Level>
    <Task>100</Task>
    <Keywords>0x80000000000000</Keywords>
    <TimeCreated SystemTime="2016-01-11T16:44:53.487165900Z" />
    <EventRecordID>888</EventRecordID>
    <Channel>Application</Channel>
    <Computer>angela-laptop</Computer>
    <Security />
  </System>
  <EventData>
    <Data>owncloud.exe</Data>
    <Data>2.1.0.5683</Data>
    <Data>00000000</Data>
    <Data>libstdc++-6.dll</Data>
    <Data>0.0.0.0</Data>
    <Data>3ea83ea3</Data>
    <Data>40000015</Data>
    <Data>00021d32</Data>
    <Data>74c</Data>
    <Data>01d14c8f07623c39</Data>
    <Data>C:\Program Files (x86)\ownCloud\owncloud.exe</Data>
    <Data>C:\Program Files (x86)\ownCloud\libstdc++-6.dll</Data>
    <Data>6b80937f-70dc-4983-9bb7-9e938dcc1d2f</Data>
    <Data>
    </Data>
    <Data>
    </Data>
  </EventData>
</Event>

**Comment by guruz** [comment]
Did you send in the crash with the client's crash reporter?

In general server errors like the exception above should be reported to https://github.com/owncloud/core :)

**Comment by cscashby** [comment]
Ah apologies, I'll look into that.  In terms of client crash reporter, I don't think it gave the option but I will reproduce. Thanks

**Comment by ogoffart** [comment]
Do you have a backtrace or step to reproduce?

**Comment by guruz** [comment]
Please try with a 2.2 nightly
http://download.owncloud.com/desktop/daily/
