### ISSUE TITLE
CentOS 7 missing on software.opensuse.org

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#4349]
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client only provides information how to install on **CentOS 6** and **RHEL 7**

The RHEL 7 instructions only install the 2.0.2 client. (http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/RHEL_7/x86_64/)

There is a Centos 7 folder with 2.1.0 builds, but this folder isn't accessible from the main page:
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/CentOS_7/x86_64/

**Comment by michaelstingl** [comment]
Centos 7 instructions are available in the Fedora section of the download page:

![software_opensuse_org__install_package_isv_owncloud_desktop___owncloud-client](https://cloud.githubusercontent.com/assets/214010/12294326/bfdf255a-b9f9-11e5-9162-f91af36bef28.png)

**Comment by dragotin** [comment]
@digitaltom can you help with that? Its on the openSUSE infrastructure. Thanks!

**Comment by jnweiger** [comment]
Updated the config of RHEL7 to match CentOS7. This should build an identical package now for both targets.

**Comment by jnweiger** [comment]
Publishing was off since November. Enabled.

**Comment by digitaltom** [comment]
@ancorgs do you still maintain that page and can check why centos ended up in the fedora description?

**Comment by danimo** [comment]
@jnweiger problem persists.

**Comment by jnweiger** [comment]
https://bugzilla.novell.com/show_bug.cgi?id=937021

**Comment by jnweiger** [comment]
We already have our own donwload-page implementation at owncloud.com and owncloud.org where we fix install instructions and other issues.

This only affects packages hosted at suse.

**Comment by michaelstingl** [comment]
Why do we point our users to [software.opensuse.org](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client) on https://owncloud.org/install/#install-clients ?

**Comment by jnweiger** [comment]
All our server downloads have already moved away from suse infrastructure.
It appears this issue is automatically resolved when we do the same for the client downloads.
@dragotin any thoughts on this move?

**Comment by jnweiger** [comment]
Got a hint from SUSE.
If I interpret this correctly, a workaround on my side is possible. Evaluating...

**Comment by jnweiger** [comment]
Fixed. 
![bildschirmfoto - 16 03 2016 - 15 11 16](https://cloud.githubusercontent.com/assets/1108546/13815177/d10e3412-eb89-11e5-89d5-bb62790924bd.png)

**Comment by SteveCliff** [comment]
For info, I can't see the fixed changes above yet for CentOS 7 - not sure if it's still propagating? Also, if I type in the instructions above after downloading the desktop.repo I get "No package owncloud-client available" ?

**Comment by jnweiger** [comment]
CentOS_7 now fails to rebuild. We have opt-qt5-qtbase-devel but it is looking for qt5-qtbase-devel. Sigh.

**Comment by jnweiger** [comment]
Fixed the build. Not sure what the opt confusion caused. This config is unchaged. 
Anyway, it should be back, as soon as the openSUSE publisher kicks in.
