### ISSUE TITLE
owncloudcmd return unrecognized option

### ISSUE THREAD

**Issue by paoloB132** [owncloud/client#4351]
owncloudcmd --version
ownCloud version 2.1.0
Using Qt 5.4.2

calling it from command line in order to manually sync, returns all time unrecognized option like:

owncloudcmd /root/mydir https://mycloud.mydomain
Unrecognized option '/root/mydir'
Try 'owncloud --help' for more information

I want to sync manually and no interactive ... any hints ?

Regards,
Paolo.

**Comment by guruz** [comment]
You accidently run ```owncloud``` instead of ```owncloudcmd```

**Comment by paoloB132** [comment]
not really


[root@cloud ~]# /usr/bin/owncloudcmd  /root/mydir https://mycloud.mydomain
Unrecognized option '/root/mydir'
Try 'owncloud --help' for more information

**Comment by guruz** [comment]
> Try 'owncloud --help' for more information

Weird symlinks?
Broken installation?
it should say ```owncloudcmd```
