### ISSUE TITLE
Faulting module: OCUtil_x64.dll

### ISSUE THREAD

**Issue by Phantis** [owncloud/client#4356]
I have been using Directory Opus for Windows (a file manager and explorer replacement) for a while. Directory Opus has a built in FTP feature that was not working for me since (probably) the 1.8. version of OC client. A notice has poped up today prompting me to report a problem to you - that's what I'm doing here. I'm including the popup notice screen capture.

![faulting_module](https://cloud.githubusercontent.com/assets/5699759/12304771/3bf0559c-b9ff-11e5-95d3-bf64c6d8551d.JPG)

**Comment by guruz** [comment]
FYI @jturcotte @danimo

**Comment by jturcotte** [comment]
I removed the only code we had using Winsock, it wasn't used. I haven't tested with your application but I'm pretty sure this should fix it.
