### ISSUE TITLE
You can't resharing with a third user

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4357]
### Steps to reproduce
1. Install the version 2.1.0 on Desktop Client
2. Create 3 accounts (user1, user2, user3)
3. Go to user1
4. Create a New folder (Share with user2)
5. Right click and Share with owncloud
6. Share with user2, but only with the permission CAN SHARE
7. Go to user2
8. You can the folder (Share with user2)
9. With the same folder (Share with user2)
10. Right click and Share with owncloud
11. Share with user3

### Expected behaviour
You should be able to share with a third user

### Actual behaviour
You can't resharing with a third user
LOG
```
MAC:
01-14 13:11:42:360 0x7fbdc942ba70 OCC::OcsJob::finished: Reply to "POST"  QUrl( "https://XXXXXXXXXXX/ocs/v1.php/apps/files_sharing/api/v1/shares" )  (QPair("path","//hello"), QPair("shareType","0"), QPair("shareWith","user3")) has unexpected status code: 403 "{"ocs":{"meta":{"status":"failure","statuscode":403,"message":"Sharing 432 failed, because the permissions exceed permissions granted to di"},"data":[]}}"

WINDOWS 10:
01-14 13:11:42:360 0x7fbdc942ba70 OCC::OcsJob::finished: Reply to "POST"  QUrl( "https://XXXXXXXXXXX/ocs/v1.php/apps/files_sharing/api/v1/shares" )  (QPair("path","//hello"), QPair("shareType","0"), QPair("shareWith","user3")) has unexpected status code: 403 "{"ocs":{"meta":{"status":"failure","statuscode":403,"message":"Sharing 319 failed, because the permissions exceed permissions granted to di"},"data":[]}}

```

### Server configuration
Desktop v ownCloud-2.1.1.3024-nightly20160112.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}

**Comment by Dianafg76** [comment]
I tested with the Server Web and on it is working ok,  you can resharing with a third user (user3)

**Comment by Dianafg76** [comment]
cc/ @davivel

**Comment by rullzer** [comment]
Same as in #4358, basically it is a permission issue.

**Comment by Dianafg76** [comment]
I tested this issue and is working OK
Desktop v 2.2.0 build 3111
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}
