### ISSUE TITLE
Windows client does not delete local files in read-only shares

### ISSUE THREAD

**Issue by speedxy** [owncloud/client#4360]
### Expected behaviour
After deleting a file, this should be correctly synced to all desktop clients so the file is deleted even on client's datastorage.

### Actual behaviour
After deleting a file via web interface in a shared folder (read-only), a synced windows client is not able to delete this file and ends up with "access denied" ("Zugriff verweigert").
Mac client seems to have no problems with this.

### Steps to reproduce
1. Create a folder with user1
2. Share this folder with user2, read-only
3. Place some files in the folder with user1
4. Sync that folder with windows desktop client, v.2.1.0
5. Delete a file from that folder with user1
6. Wait for sync on the desktop client of user2. It will fail with "Access Denied"

### Server configuration
**Operating system:** Debian 8.2

**Web server:** nginx/1.6.2

**Database:** MySQL 5.5.46-0+deb8u1

**PHP version:** PHP 5.6.14-0+deb8u1

**ownCloud version:** 8.2.2

**Storage backend:** MySQL

### Client configuration
**Client version:** 2.1.0

**Operating system:** Win10, but even with Win7

**OS language:** DE

**Installation path of client:** [Win10] C:\Program Files (x86)\ownCloud

#### Client Log
```
01-14 20:01:46:054 0x4ae7770 OCC::PropagateLocalRemove::start: "C:/Users/User/OwnCloud/testfile.txt"
01-14 20:01:46:055 0x4ae7770 OCC::OwncloudPropagator::localFileNameClash: CaseClashCheck for  "C:/Users/User/OwnCloud/testfile.txt"
01-14 20:01:46:059 0x4ae7770 OCC::SyncJournalErrorBlacklistRecord::update: This error is not blacklisted  0 false
01-14 20:01:46:060 0x4ae7770 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "testfile.txt" INSTRUCTION_REMOVE 2 "Zugriff verweigert
"
01-14 20:01:46:062 0x4ae7770 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:ERROR:C:/Users/User/OwnCloud/testfile.txt"
```

**Comment by Dianafg76** [comment]
I can't reproduce the issue
When the file is scyn with user 2, I can't delete the file on the Web server, appear this message (Could not delete.....), so I can't reproduce the issue
Windows 10
Desktop client v ownCloud-2.1.1.5765-nightly20160112-setup.exe
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}

**Comment by speedxy** [comment]
You're right. Now I tested with Version 2.1.1-nightly20160112 (build 5765) and the synchronisation seems to work correctly.
