### ISSUE TITLE
Sync client context menu issue with Directory Opus 11

### ISSUE THREAD

**Issue by randomessence** [owncloud/client#4364]
If I right click to access the context menu I often see this error from Directory Opus.

![owncloud](https://cloud.githubusercontent.com/assets/1331201/12376910/4777abee-bd02-11e5-8ba0-e3edaa50fa21.png)

**Comment by guruz** [comment]
Dup https://github.com/owncloud/client/issues/4356#event-515003212
This should be fixed in 2.1.1beta1 coming out soon.

@jturcotte
