### ISSUE TITLE
Unable to sync files with < or > in file name

### ISSUE THREAD

**Issue by ArneBajse** [owncloud/client#4366]
Syncing files containing < or > in their file name causes the server to show the file twice in the web gui and the Client Version 2.1.0 to show error upon sync, complaining about duplicate files. 

This error surfaced after the upgrade to 2.1.0 with files that have existed well over six years and thus being successfully synced before.

**Comment by guruz** [comment]
Which OS?
Which server version?

**Comment by ogoffart** [comment]
Earlier version of the client did not sync files with special character. 2.1 does and let the server throw an error if the version  IF the server is 8.1 or newer.

Files with < and > works fine for me.

Please provide the log files.
This might also be a server bug.

**Comment by ArneBajse** [comment]
Client : OSX 10.9.5
Server : Debian  8.1.5-12.1

In my attempts to get rid of the error I renamed the files and the deleted the one containing < or > on the server using the web-gui. After refreshing the browser the deleted files shows up again. Renaming them gives an error "Cannot rename because the file is deleted". Client sync works with out error though.

**Comment by ogoffart** [comment]
This looks like a server problem rather than a client bug.
Please open a bug report on the [core] bug tracker.  Or asks for help in the forum https://owncloud.org/support/
