### ISSUE TITLE
Client preventing system updates on OS X

### ISSUE THREAD

**Issue by FoxBJK** [owncloud/client#4367]
I'm running OS X 10.10.3 (public beta), and 2.1.0 of the Owncloud client. I've been seeing notifications from the system that updates were prevented because the Owncloud client is running. Why? The client's not syncing anything when this happens, and it seems like a bug that the client is preventing system updates even when it's not syncing.

**Comment by guruz** [comment]
@FoxBJK Do you have a screenshot of this notification/error? Does it work if you quit the client? Does it work if you type ```killall Finder``` in Terminal? (no worries, Finder will auto-restart..)

@jturcotte @dragotin I suspect the Finder bundle. Adding to 2.1.2

**Comment by guruz** [comment]
@FoxBJK Do you really mean OS X 10.10.3?

**Comment by FoxBJK** [comment]
Hi,

Most likely yes it's just "10.10.3" (build 15D13b) but sine I'm in the public beta program it's always listing the word "beta" always.

If I quit the client, the updates work just fine. Haven't ever tried to force quit the finder for this, but I can try that this evening to see if the update works

**Comment by guruz** [comment]
I'll close this for now. I think this should work by now, we're not installing the legacy finder extension anymore since 2.1.1 and 10.10.3 will use the new finder extension.
Please report back if this is still a problem.

**Comment by FoxBJK** [comment]
So.... this error just popped up again last night with the latest Public Beta. I don't know whether or not I have the legacy plugin installed.

One thing I've noticed with the last couple of times this has happened is that my instance of the client was not connected to my server. Does that matter?

**Comment by guruz** [comment]
Are you syncing any system directories or just things inside ```/Users/``` ?

**Comment by FoxBJK** [comment]
Just a couple of things inside of my home directory. I haven't modified the list of ignored files either, so I'd hope no system files are being touched. Any way to check?

**Comment by guruz** [comment]
Can we close this issue?

**Comment by FoxBJK** [comment]
Yea go ahead and close. Whenever 10.12 gets its first update I'll come back an re-test. Thanks!

**Comment by guruz** [comment]
great :)
