### ISSUE TITLE
2.1.1 final: Find out why OS X complains about "unidentified developer" when starting installer

### ISSUE THREAD

**Issue by guruz** [owncloud/client#4368]

**Comment by jturcotte** [comment]
Should be fixed by 110f371 and 5092243

**Comment by Dianafg76** [comment]
@guruz, @jturcotte What are the steps to reproduce this problem? Thanks

**Comment by jturcotte** [comment]
@Dianafg76 Normally just make sure that you have "Mac App Store and identified developers" accepted as allowed downloaded apps to run in you SystemPreferences/Security&Privacy, and then try to run the installer.

**Comment by Dianafg76** [comment]
@jturcotte  ok , I'll try. Thanks

**Comment by Dianafg76** [comment]
I tested this issue, and is working OK
Desktop cliente v 2.1.1rc1 (build 3069)
Server v 8.2.2
