### ISSUE TITLE
[2.1.1 beta1] [Windows] Font drawing issue in themed button-drawing in selective sync

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#4373]
Caracters are cut off because linehigh is too small. (Chars like g, y, j, ...)

![2016-01-19 14_32_47-owncloud](https://cloud.githubusercontent.com/assets/2804301/12420008/0b9d7aea-beba-11e5-941d-377aac5ef0c1.png)

Picture from 2.21 beta1 under windows 7 32 Bit - German

**Comment by Dianafg76** [comment]
I tested this issue and is working OK
![issue_4373](https://cloud.githubusercontent.com/assets/12032058/12453072/d7de8b1c-bf91-11e5-83df-d83e932fcf3a.PNG)
Desktop v ownCloud-2.1.1.5785-nightly20160120-setup.exe
Server v 8.2.2
