### ISSUE TITLE
You don't see the hidde file on Activity/Not synced on Windows

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4374]
### Steps to reproduce
1. Install Desktop v 2.1.1. Beta1
2. Create a new hidden file 
3. Sync

### Actual behaviour
On Mac, if you go to the Activity option/Not synced, you can see the file 

On Windows you don't see the file on the same option

### Server configuration
Desktop v ownCloud-2.1.1.3045-nightly20160119.pkg (on Mac)
Desktop v 2.1.1beta1 (build 5780) (on Windows 10)
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}

**Comment by ogoffart** [comment]
Works for me.

Where and how do you create the hidden file?   do you have the "sync hiden files" option unchecked?

**Comment by Dianafg76** [comment]
In my Mac, I create a new hidden file and when is sync, appears on activity/not Synced. But If I go with the same user on Windows 10 and waiting to sync I can´t see the hidden file

**Comment by ogoffart** [comment]
well, if the file is not sync'ed from the mac, it's not on the server, so the windows computer does not know its existence, since it's not sync'ed.

**Comment by Dianafg76** [comment]
Ok, thanks
