### ISSUE TITLE
LDAP OwnCloud share

### ISSUE THREAD

**Issue by volure** [owncloud/client#4376]
Searching for shares from the desktop client are case sensitive.

**Comment by ckamm** [comment]
@volure What do you mean by "searching for shares"? I assume you mean the user-search functionality in the share dialog. The case-sensitivity there was fixed for 2.1.1 in #4269.

Feel free to reopen if you meant something else.

**Comment by volure** [comment]
Yes, that is what I meant. It appears that my client is 2.1.0 which is apparently a revision behind.

I guess that means this client should update any day now ? Does that sound correct ?
