### ISSUE TITLE
OSX Client fails to sync large files

### ISSUE THREAD

**Issue by wmcgit** [owncloud/client#4377]
Hi there,

I am using the current version of OwnCloud (8.2.2 via Apache, PHP v. 5.6).

My main MacBook does sync all files without any problems (because they were uploaded via this device).
It runs on 2.1.0. (build 2944).

However, my other two devices (client version 2.1.0.) cannot download large files (eg. .zip, .mov) they report "Connection closed", but do not give a further description.

What shall I do?
Is this is a common error?

Best regards,
Peter

[owncloud.logfile.txt](https://github.com/owncloud/client/files/98854/owncloud.logfile.txt)

**Comment by guruz** [comment]
Please try 2.1.1 beta1 and report back if that works!
Thank you

https://owncloud.org/install/#testing-development

**Comment by wmcgit** [comment]
Hi Guruz,

currently I have ownCloud 8.2.2 (beta) 
Would this version fix that error, too?

If not: is it possible to downgrade?

Thank you

**Comment by guruz** [comment]
@wmcgit I mean client not server version :-)

**Comment by wmcgit** [comment]
Ah, ok!

Thanks again for that hint.

I´ll keep you up to date.

**Comment by wmcgit** [comment]
@guruz Thank you very much again for your help.

Unfortunately using your suggested beta-version did not solve the problem. I still receive the same error while downloading large files.

Do you have another solution on that?
