### ISSUE TITLE
'Add folder Sync Connection button' is always disable for folders located in root

### ISSUE THREAD

**Issue by davitol** [owncloud/client#4381]
When we 1st sync, we do not select to sync all the folders located in the root. It should be possible to add them later via this button, but it is not active.

![screen shot 2016-01-21 at 13 16 54](https://cloud.githubusercontent.com/assets/10596560/12480734/ca73c510-c044-11e5-8438-d2372a93f635.png)

**Comment by guruz** [comment]
Hm, the tooltip is not explanation enough?

**Comment by davitol** [comment]
That's the reason why I made the screenshot with the tooltip. I'm not syncing all the files. Sure I have understood the tooltip in a wrong way :crying_cat_face:

**Comment by rperezb** [comment]
I checked this with the current version, 2.1.0

## Button not enable steps

1.- Log in
2.- Select to sync 1 folder stored on the root (there are more folders on the root - see the image)
3.- button is not enable to add more folders

## Button enable steps

1.- Log in
2.- Select to sync 1 folder stored inside another folder (Documents/test - select test) (there are more folders on the root - see the image)
3.- button is enable to add more folders

**Comment by SamuAlfageme** [comment]
Closing with the same reason as #5328: expected behavior.
