### ISSUE TITLE
Put toolchain to isv:ownCloud:toolchains:mingw:win32:2.1

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4382]
isv:ownCloud:toolchains:mingw:win32:2.1 is a copy of the :stable project that we are using, now also with the changes to the qtbase package copied from :devel as required.

If all packages build, we can switch the docker to use that repo. And RETEST.

IF that works, we have to copy back the qtbase package to :stable, remove the current :devel and rename :stable to :devel.

In the future we create a release repo for each stable release by copying it from :devel.

@danimo

**Comment by danimo** [comment]
The toolchain still does not build, skipping this for rc1.

**Comment by danimo** [comment]
Toolchain is now in place.
