### ISSUE TITLE
[Win 7 64bit] Unable to initialize a sync journal when syncing whole HD "h:\"

### ISSUE THREAD

**Issue by nakashe** [owncloud/client#4385]
Im trying to synchronize the whole HDD - like all files in L:\ on my desktop pc..
The owncloud client is telling me  "unable to initialize a sync journal".
Please help me :)

**Comment by guruz** [comment]
You did not mention which client Version. Could you download 2.1.1 beta1 (from "testing" section in Downloads)

Is this a USB stick or similar with a FAT fs? Then this might be fixed already.

**Comment by nakashe** [comment]
No, it is a regular partition on NTFS hdd..
Im using the latest version of client 2.1.
Can you pls send me a link where I can find this testing section? I cant find it anywhere :(

**Comment by carlu93** [comment]
https://owncloud.org/install/#testing-development

At the bottom you'll find the Desktop Clients 2.1.1 beta1 section.

**Comment by nakashe** [comment]
Thanks. Beta version installed. Still the same problem :(

**Comment by guruz** [comment]
@nakashe sorry, Need a newer Version even https://github.com/owncloud/client/issues/2701#issuecomment-172781147

**Comment by nakashe** [comment]
there is no way.. easy solution is move all the files to one folder and sync this folder.. that's working..
The best way for me is sync the whole HDD, but it is not the best way for Owncloud :D

**Comment by guruz** [comment]
Now I understand the issue.

**Comment by ckamm** [comment]
@nakashe I've tested this on Win7 and there was no problem syncing my whole `G:\`. Maybe this is a permissions problem? Are you allowed to create files on your `L:\` drive?

If this works, could you provide a log file? https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly

**Comment by ckamm** [comment]
Feel free to reopen if this still happens.
