### ISSUE TITLE
[Pot. Show Stopper] openssl 1.0.2f upgrade required?

### ISSUE THREAD

**Issue by danimo** [owncloud/client#4390]
The OpenSSL Team has announced 1.0.2f which contains a critical security fix. Unfortunately, we do not know much about its nature yet. If it affects the client side (or our use case), this ticket is a show stopper for 2.1.1 final.

The release is due on Thursday, which coincides with our projected release date for 2.1.1 final. This means we'll have a last minute chance to pull the plug on the release and update packages.

See https://mta.openssl.org/pipermail/openssl-announce/2016-January/000058.html for details.

**Comment by MTRichards** [comment]
ok, so this is something we have to put in 2.1.1, date can slide to make this. Please also ensure this has adequate test coverage.

**Comment by danimo** [comment]
@MTRichards This is already scheduled for 2.1.1.

**Comment by MTRichards** [comment]
Great, sure, but are you telling me you are going to release 2.1.1 on the same day as the openssl is released, with no testing?
That is a big red flag.
Of course I could have missed something.

**Comment by danimo** [comment]
@MTRichards The projected release date was Thursday. Now that we know that OpenSSL is releasing on the same day, we will scrub the release in case the issue in OpenSSL turns out to be of importance for us. In this case, I'd like to shift the release, with an RC2 on Thursday on Friday including the patch, and a final release on Monday or Tuesday.

**Comment by MTRichards** [comment]
Great, I like that idea. Good chance to test.

**Comment by cmonteroluque** [comment]
@danimo @MTRichards that makes sense.

**Comment by danimo** [comment]
Done for Mac OS and Windows.

**Comment by Dianafg76** [comment]
@danimo What are the steps to reproduce this issue ?, thanks

**Comment by dragotin** [comment]
@Dianafg76 reproduction happens through version compare in the final build, I think the version of the bundled openssl is printed on the general tab.

**Comment by Dianafg76** [comment]
@dragotin, @danimo I tested this issue and is working OK
![screen shot 2016-02-08 at 11 12 30](https://cloud.githubusercontent.com/assets/12032058/12884172/c6319a56-ce5c-11e5-8a4b-f14309a622f5.png)

I tested with different servers

# NEW OpenSSL
## Testing 
Desktop Client v ownCloud-2.1.1.3100-nightly20160208.pkg (MAC), ownCloud-2.1.1.5830-nightly20160208-setup.exe (WINDOWS)


TestID | Server | MAC | WINDOWS | Related Comment
------------ | ------------- | -------------- | ----- | ------
1| signed server | :white_check_mark: |:white_check_mark:|
2| S3 | :white_check_mark: |:white_check_mark:|
3| SHIB | :white_check_mark: |:white_check_mark:|
4| owncloud.solidgear.es | :white_check_mark: |:white_check_mark:|
