### ISSUE TITLE
OwnCloud Sync client suddenly stops sending Authentication Header to server

### ISSUE THREAD

**Issue by IvanUgrin** [owncloud/client#4391]
Hi,

I am trying to implement OwnCloud-like WebDAV door in my JavaEE server. I have success using my server with OwnCloud Sync client and everything works fine , files synchronise and get uploaded. Suddenly the client stops sending Authentication header with a random PUT/DELETE request and continues to do it for every other request after that. Maybe you can explain this behaviour but I think that the client should send the auth header with every request except the GET requests to status.php,capabilities, activity etc. config endpoints.

This is an example of a DELETE request after which the sync starts to fail because of the Authentication Header:
New request target:/remote.php/webdav/disk/flower2.jpg
Time: 2016-01-25T13:55:50+01:00
Method:DELETE
Headers:
User-Agent : Mozilla/5.0 (Macintosh) mirall/2.1.0
Connection : keep-alive
Host : localhost:2881
Accept-Encoding : gzip, deflate
Accept-Language : en-US,*
Paramteres:

Regards,
Ivan

**Comment by guruz** [comment]
@IvanUgrin I believe this is fixed with 2.1.1 beta1 (testing section on download site).
Can you confirm and Close this issue?

BTW, you should debug print out the TCP Connection in your Server, then you'll notice it is for new TCP Connections.

We're curious, what Kind of Server do you plan to do?

FYI @karlitschek

**Comment by karlitschek** [comment]
interesting. Thanks

**Comment by IvanUgrin** [comment]
Yes, I've tested and I think it's OK in the version you pointed out.
I am adapting an already implemented WebDAV door to work with OwnCloud Sync client. The project is open source it's called dCache and I believe my patches we soon go live.

**Comment by guruz** [comment]
Nice :)
Please blog about this or something and contact us if something breaks..
