### ISSUE TITLE
Owncloud.exe dekstop stoped working

### ISSUE THREAD

**Issue by K4nape** [owncloud/client#4392]
Hello,
I have problem, everytime, whats the solution? 
![screenshot 2016-01-26 13 26 59](https://cloud.githubusercontent.com/assets/10292911/12579814/7f814864-c433-11e5-9e21-ac11fcb4ac09.png)

**Comment by danimo** [comment]
Please describe exactly what happened, how you got the error and which version you are using.

**Comment by guruz** [comment]
@K4nape Did you not receive an offer to send this to the Crash Reporter?

**Comment by K4nape** [comment]
@danimo i got error, when sync 111gb, and everytime after sync again and error to. Photo 
![screenshot 2016-01-26 23 43 59](https://cloud.githubusercontent.com/assets/10292911/12596048/fe1408bc-c486-11e5-871b-97b1fcb54733.png)

@guruz No :/

**Comment by K4nape** [comment]
No answer ?

**Comment by guruz** [comment]
@k4nape 2.1.1rc1 is already out (testing section in downloads), it should send something to the crash reporter if it crashes?

**Comment by guruz** [comment]
I'll close this, please try 2.1.1 rc1 and send the crash report to the crash reporter

**Comment by K4nape** [comment]
@guruz Rc1? sorry i don't understand this reply. But newest 2.1.0

**Comment by K4nape** [comment]
@guruz Okey, I am looking forward to a good time to get out a new version

**Comment by danimo** [comment]
@K4nape See https://owncloud.org/install/#testing-development

**Comment by K4nape** [comment]
@danimo as I saw yesterday. Sry
