### ISSUE TITLE
[2.1.0] opcache interaction with sync client

### ISSUE THREAD

**Issue by stephengraf** [owncloud/client#4393]
I have run into a very strange problem with the Windows sync client and php opcache.

When opcache is enabled on the web server the sync client fails on a login attempt and works  if opcache is disabled.

The environment is:
Windows 10 with sync client 2.1.0 
and 
openBSD 5.8, openBSD httpd server, php 5.6 with Zend opcache module, ownCloud 8.2.2.

The problem shows as a "Bad Request" on the client login page and the webserver log shows a 400 error, or unrecognizable packet.  There are no further errors on the server as the packet is never propagated.  The client log shows the error also.

To trace the problem I had to implement an http version of the web server for ownCloud and use Wireshark on the PC to capture the interaction.

The client logs and the text of the Wireshark traces are included.

It would appear that the bad packet (highlighted in yellow) from the client has some xml data stuck on the front end, and the extra data should have been attached to the previous packet from the client.  This behavior is very repeatable, yet for the life of me I do not understand how opcache on the server can affect what the client is sending.

With opcache enabled, ownCloud shows no problems and android caldav and carddav work and Outlook WebDAV to publish calendars also works.  Windows sync client 1.8.4 also works with opcache enabled, but version 2.0.0 exhibits the problem.  I have had to turn off opcache on my production system to keep the sync client working.

I have the raw Wireshark traces, but they can not be uploaded because they are binary files.

[sync_log_failed.TXT](https://github.com/owncloud/client/files/105623/sync_log_failed.TXT)
[sync_log_working.TXT](https://github.com/owncloud/client/files/105624/sync_log_working.TXT)
[test_dump_failed.docx](https://github.com/owncloud/client/files/105738/test_dump_failed.docx)
[test_dump_working.docx](https://github.com/owncloud/client/files/105744/test_dump_working.docx)

**Comment by guruz** [comment]
Would you test a nightly build from today from http://download.owncloud.com/desktop/daily/ ?

I haven't looked at your traces yet, while your conclusion might be valid it could also be related to recent Connection Code fixes in the Client. thanks

**Comment by stephengraf** [comment]
Thank you for your response.

I tested successfully with: 
ownCloud-2.1.1.5804-nightly20160127-setup.exe

I went back and forth between 2.1.0 and 2.1.1 and finally put https back on the server all the while opcache was enabled. Version 2.1.0 always failed and 2.1.1 always worked.

I know you won't have time to respond, but I have to wonder how opcache on the server can affect the client in such a way.

**Comment by guruz** [comment]
It must be some interaction with how HTTP Keep-alive was done.
I can't explain it either.

What was broken in 2.1.0 fixed in 2.1.1 is that we always send an authentication Header with username and Password (in Addition to Cookies). I guess the data flow there (with PHP sending a HTTP 401) confused one of the modules on the Server side(?)
