### ISSUE TITLE
Owncloud client needs a setting to switch server addresses

### ISSUE THREAD

**Issue by jschwalbe** [owncloud/client#4394]
I'm a recent convert to OC. I've noticed that there isn't an established way to switch the server address. For instance: I have a development server that I try things on to see if I like them before making a commitment and installing on my regular servers. Enter owncloud. So I set up owncloud on my mac with the development server address - now when I want to transfer all my stuff to the actual server I'm going to have to delete the owncloud settings on my mac and try to reestablish them somehow. The alternative I'm proposing is allowing the client's server address setting to be edited so that the preferences associated with that server (synced folders, which to ignore, etc) won't have to be deleted. I understand it's a fairly small issue that only affects a small subset of people, but it's important to me so I thought I'd post it. :)
Great app. I'm looking forward to using it more! Thanks for all the hard work from the devs.

**Comment by guruz** [comment]
@jschwalbe At the Moment I can only recommend editing owncloud.cfg while Client is closed.

**Comment by jancborchardt** [comment]
And since this is such an edge-case I would recommend we do not overextend here with implementation in the GUI.

Alternatively you could just use the multi-account functionality. But as far as I understood, both servers have the same data.

**Comment by jschwalbe** [comment]
ok thanks for the thoughts!
