### ISSUE TITLE
"Updates" section on "General" tab shouldn't be displayed when updates are disabled by config file or Win registry

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#4397]
I disabled updates in the Win registry according the [docs](https://doc.owncloud.com/desktop/2.1/autoupdate.html#preventing-automatic-updates-in-windows-environments). The message I see is quite confusing:

![cursor_and_ie11_-_win8_1](https://cloud.githubusercontent.com/assets/214010/12616261/998e06ac-c50a-11e5-80e8-017643b69fb1.png)

@dragotin Would it be possible hide the "Updates" section when updates are disabled?

**Comment by MorrisJobke** [comment]
I tested this and it doesn't work with the branded client 2.1.0:

<img width="1025" alt="bildschirmfoto 2016-02-01 um 16 50 38" src="https://cloud.githubusercontent.com/assets/245432/12722303/92e9a04c-c904-11e5-8c2e-159e1e4677ad.png">


Works with the unbranded client:

<img width="1023" alt="bildschirmfoto 2016-02-01 um 16 59 09" src="https://cloud.githubusercontent.com/assets/245432/12722434/36d9efa4-c905-11e5-8e76-eb55920f7ae4.png">


It seems that the regedit entry also needs the branded string. I will try

**Comment by MorrisJobke** [comment]
Works if you use Application Vendor and Application Name: https://github.com/owncloud/client/blob/639301e9e986aa7d12c178a486773ed9449e1361/cmake/modules/NSIS.template.in#L766

**Comment by guruz** [comment]
Is this ticket blue or not?
Removing out if it is not..

**Comment by michaelstingl** [comment]
@guruz I'm pretty sure this will become blue after https://github.com/owncloud/enterprise/issues/1075 is fixed.

**Comment by ckamm** [comment]
@danimo Could you review 93de378?

**Comment by danimo** [comment]
Looks good!

**Comment by guruz** [comment]
Cherry picked https://github.com/owncloud/client/commit/93de378fb21e934d324d621f66eec98e53f1637a into master.
