### ISSUE TITLE
ownCloud client connection error

### ISSUE THREAD

**Issue by sokorn** [owncloud/client#4398]
I'm having an similar problem like https://github.com/owncloud/client/issues/3967

# Expected behaviour

log in via client to server with given credentials

# Actual behaviour

ownCloud client can't log in user with given credentials.
When credentials typed in, it says "connection ended".

# Steps to reproduce

1. start ownCloud Client
2. connect to server
3. type in credentials

# Server configuration

Operating system: Linux

Web server: nginx 1.8.1

Database: MariaDB 10.1.10

PHP version: 7.0.2

ownCloud version: 8.2.2 (git)

Storage backend: local device storage

# Client configuration

Client version: 2.1.0 (build 5683)

Operating system: Windows 10

OS language: German

Installation path of client: default

# Logs
https://gist.github.com/sokorn/258fab2668b9a74f29e2#file-error_log-L23
At line 23 I'm submitting the credentials to the server

There is no error in the webserver or ownCloud server logs.

**Comment by RealRancor** [comment]
@sokorn Can you try the RC1 of 2.1.1:

https://owncloud.org/install/#testing-development

mentioning fixes for "connection closed" errors in its changelog:

https://github.com/owncloud/client/blob/2.1.1-rc1/ChangeLog

**Comment by jball5** [comment]
I can confirm the same issue on my US Windows 10 machine. I get an error when the owncloud client tries to load.

Faulting application name: owncloud.exe, version: 2.1.0.5683, time stamp: 0x00000000
Faulting module name: libocsync.dll, version: 0.0.0.0, time stamp: 0x3f4f3f47
Exception code: 0xc0000005
Fault offset: 0x0008199e
Faulting process id: 0x1090
Faulting application start time: 0x01d1593b0b00107c
Faulting application path: C:\Program Files (x86)\ownCloud\owncloud.exe
**Faulting module path: C:\Program Files (x86)\ownCloud\libocsync.dll**
Report Id: 68f1fda6-af21-4cfb-9ab5-7ad3a818719a
Faulting package full name: 
Faulting package-relative application ID:

**Comment by sokorn** [comment]
@RealRancor I tried the RC1 and can confirm, that the problem is gone.
Many thanks for the help!

When will the stable version 2.1.1 be released?

**Comment by RealRancor** [comment]
@jball5 Picked out an wrong issue or how is a crash of the client related to this?

@sokorn Have a look at https://github.com/owncloud/client/issues/4390#issuecomment-174539187
