### ISSUE TITLE
.lnk files not synced properly; conflicted/unusable.

### ISSUE THREAD

**Issue by anothervictim** [owncloud/client#4399]
I'm running ownCloud 8.2.2.2 and, synced, .lnk files are conflicted; properly named, synced, files are unusable. Running Windows 10 Build 1511 w/ ownCloud client Version 2.1.0 (build 5683). This issue has been ongoing for the last few months.

**Comment by guruz** [comment]
Could you please try 2.1.1 rc1?
https://owncloud.org/install/#testing-development

**Comment by anothervictim** [comment]
Guruz, this is working beautifully. It even updated the invalid lnk with a valid and complete version. I haven't seen it work that way in months! Thank you. Let me know if you need any additional info for testing purposes.

**Comment by guruz** [comment]
:+1: 

great!
