### ISSUE TITLE
Tray icon not matching sync status when having multiple sync folders in one account

### ISSUE THREAD

**Issue by ouafnico** [owncloud/client#4401]
Hello

It seems, when you got multiple synchronization folders in owncloud client (windows), the tray icon is not refresh with blue sync icon, when the folder currently synchronizing is not the first on the list.

![sans titre](https://cloud.githubusercontent.com/assets/807350/12642595/1842493e-c5b7-11e5-8434-aa4a8b6387fe.png)

**Comment by guruz** [comment]
Thank you. Have you checked if this is also the case with 2.1.1 rc1? (testing section of download page)

**Comment by ouafnico** [comment]
It seems to works on this RC version :)
