### ISSUE TITLE
[Login view] Buttons "back" and "next" are not aligned

### ISSUE THREAD

**Issue by rperezb** [owncloud/client#4402]
See attached images, buttons back and next are not aligned when entering your userid and password

Mac version: Version 2.1.1rc1 (build 3070). 

![screen shot 2016-01-27 at 13 39 08](https://cloud.githubusercontent.com/assets/1846927/12644231/b92bfd5e-c5c1-11e5-8957-fcda46d35a14.png)

**Comment by guruz** [comment]
closing in favor of https://github.com/owncloud/client/issues/5083
