### ISSUE TITLE
Unable to start latest stable and RC1 clients on Windows 10 insider preview build 14251

### ISSUE THREAD

**Issue by pauljmelia** [owncloud/client#4405]
I've just updated to the latest Windows 10 insider preview build and the Owncloud client will no longer start:

Faulting application name: owncloud.exe, version: 2.1.0.5683, time stamp: 0x00000000
Faulting module name: libocsync.dll, version: 0.0.0.0, time stamp: 0x3f4f3f47
Exception code: 0xc0000005
Fault offset: 0x0008199e
Faulting process id: 0x2d94
Faulting application start time: 0x01d159c786c7ce16
Faulting application path: C:\Program Files (x86)\ownCloud\owncloud.exe
Faulting module path: C:\Program Files (x86)\ownCloud\libocsync.dll
Report Id: b6b6666d-8b85-4a95-a4f0-4a17cbb2f6a8
Faulting package full name: 
Faulting package-relative application ID: 

I've tried the 2.1.1 RC1 as well with the same result.

**Comment by guruz** [comment]
Did it offer you to send a Crash Report on next start?
Did the Insider preview build break any other applications?

**Comment by pauljmelia** [comment]
Hi there.
There was no offer to send a crash report, in fact trying to launch the other executables in the owncloud directory caused the same error.
I also noticed a similar access violation being logged repeatedly by Git when I was using Visual Studio, and the faulting module in that case was ntdll.dll; so it looks like build 14251 is quite buggy.
I've ended up flattening my laptop and going back to version 1511 as there was also a major problem with Entity Framework code-first migrations which had been in for 3 insider preview builds and I've lost about a weeks worth of dev time trying to work around it. Breaking owncloud and git was the last straw...

**Comment by danimo** [comment]
http://windowsreport.com/windows-10-preview-build-14251-problems/, so I'd say it's their bug, not ours. Even though I am subscribed to the fast ring and a preview user, I don't see the update yet. Still I'd rather wait for the next build before we spend time debugging this.

**Comment by danimo** [comment]
Better approach: Lets keep this open as "Known issue" and close it once the next Windows build fixes it.

**Comment by PeteHardy** [comment]
This problem is resolved by Windows Insider Preview Build 14257.

**Comment by danimo** [comment]
Thanks for letting us know.
