### ISSUE TITLE
Selective sync folder list should be closed by default on settings dialog open

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#4408]
Currently every time you open the settings dialog, the selective sync folder list is expanded.

Instead, by default it should be closed to only show the necessary info. It should only be expanded in two cases:
- when it was expanded the last time, so remember the setting
- when some folders are not synced, that is the selective sync settings are modified

**Comment by guruz** [comment]
I've speak to several People that said the selective sync is not discoverable. They did not know it is a tree view at all and can be expanded.

This is why it is auto-expanded now. Having it not do that is not a solution.

**Comment by jancborchardt** [comment]
Ok, sounds good.
