### ISSUE TITLE
[Password Policy] Windows Desktop Client does not adhere to the expiration date rules set in the share link password policy

### ISSUE THREAD

**Issue by pako81** [owncloud/client#4409]
### Steps to reproduce
1. Set an expiration date in the share link password policy
2. From the Windows Desktop client generate a public shared link with an expiration date
3. The expiration date for the Desktop generated public link can be set beyond the one set in the share link password policy (need however to verify if the public link generated from Desktop is still accessible after the expiration date set in the share link password policy)

Customer communication as side note (see screenshot below):

> the Windows Desktop Client does not adhere to the rules that are set in the "share link password policy" app. We've set the link to expire after 3 days without secure password and to 14 days with a secure password.
But in the Desktop Client, you can also create a link without password expiring after 14 days.

### Expected behaviour

Windows Desktop Client should adhere to the rules set in the share link password policy

### Actual behaviour

See above

### Server configuration
**Operating system**:

SLES 12

**Web server:**

Apache 2.4

**ownCloud version:** (see ownCloud admin page)

8.2.2

**Updated from an older ownCloud or fresh install:**

Updated from 8.2.1

### Client configuration

**Operating system:**

Windows

**Sync client version:**

branded version 2.1.0 build 452

![unbenannt2](https://cloud.githubusercontent.com/assets/12248713/12681870/f9cffb90-c6b0-11e5-89a3-31e522c209f8.PNG)

**Comment by danimo** [comment]
Can you take a look please, @rullzer?

**Comment by rullzer** [comment]
Ah mmm so this is most likely an issue with the app. PR already in https://github.com/owncloud/password_policy/pull/29

Basically the desktop client has no idea that app is running on the server.

**Comment by rullzer** [comment]
@pako81 I think this is fixed with the recent merge to the password_policy app. (Note 8.x is still broken...).

Could you verify against 9.0?

**Comment by pako81** [comment]
@rullzer probably I am doing something wrong but now expiration date rules for public share links seem to not match those indicated in the share link password policy app also for the WebUI (for pre-9.0 releases the date was automatically set back to the defined expiration date when trying to set dates not matching the rules in the app). Now it seems to be possible, same thing on the client side.
Tested with oC 9.0.0 and Windows Client 2.1.1.

**Comment by rullzer** [comment]
@pako81 I think this is a glitch of the UI's.
If you reload the page (or open and close the sharing dialog) the 'proper' date should be shown.

**Comment by pako81** [comment]
@rullzer thanks. This seems indeed to be a glitch of the UI's, taking some action on the page will make the correct date to be shown. However, it is still possible to set an expiration date which does not adhere to the rules of the app (no automatic set of the date back to the expiration when a date in the far future is selected), both from the Web UI and Windows Client..is this the expected behaviour?

**Comment by rullzer** [comment]
@pako81 as discussed I agree. I'll take care of the client side (will be in the next release). And also create a server side ticket.

**Comment by pako81** [comment]
@rullzer many thanks!

**Comment by rullzer** [comment]
Server ticket in https://github.com/owncloud/core/issues/23688

**Comment by michaelstingl** [comment]
related? https://github.com/owncloud/enterprise/issues/1168

**Comment by rullzer** [comment]
PR in #4700
