### ISSUE TITLE
Sync client unable to start on Windows 10 Pro Insider Preview

### ISSUE THREAD

**Issue by mrneilsy** [owncloud/client#4411]
owncloud.exe - The application was unable to start correctly (0xc0000142) Click OK to close the application.

Windows 10 Pro Insider Preview - Build 14251.rs1_release.160124-1059

**Comment by RealRancor** [comment]
Very likely a duplicate of https://github.com/owncloud/client/issues/4405 and https://github.com/owncloud/client/issues/4413
