### ISSUE TITLE
[2.1.0] [OS X] UI: Erroneous percent decoding when having a filename with printf encoding syntax

### ISSUE THREAD

**Issue by tuomassalo** [owncloud/client#4412]
I have a file called `5ol5o8sWRcSdQm3%x0lmng`.

In the client UI, the name is shown as if it contained an invalid UTF-8 sequence:

![owncloud-escaping](https://cloud.githubusercontent.com/assets/189964/12701094/5737def0-c806-11e5-8de7-cf0ba834f83b.png)

I'm using ownCloud client 2.1.0 on OSX 10.10. Server version is 8.1.5.

**Comment by Dianafg76** [comment]
@tuomassalo 2.1.1rc1 is already out (testing section in downloads), Could you try with this version, please?

**Comment by hodyroff** [comment]
Please retest with 2.3.1 otherwise closing in one week.
