### ISSUE TITLE
[Activity View] You can see different information if you click on Copy 

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4417]
### Steps to reproduce
1. Access to Activity Tab
2. Click on Server Activity you can see some information
3. Click on Copy

### Actual behaviour
And paste in a document, you can see more information than in the Server Activity
user1@XXXXXXXXXXXXXXXXXX,       Mon Feb 1 11:47:08 2016 GMT,               /Archivo oculto,                        You created Archivo oculto, Excel2*.xls and Folder_user1_rename/new_folder_2, 
admin@XXXXXXXXXXXXXXXXXX,       Mon Feb 1 11:42:37 2016 GMT,    /Folder_user1/new_folder_2,                                                             user1 created Folder_user1/new_folder_2,   

### Server configuration
Desktop v 2.1.1rc1 (build 3069)
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}

**Comment by ogoffart** [comment]
Is that really an issue?  What is the expected behaviour?

**Comment by guruz** [comment]
I think that's fine
