### ISSUE TITLE
not syncing hidden files breaks the file recall functionality

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#4420]
For the file recall functionality to work, the .sys.admin#recall# file needs to be downloaded from the server. Currently this is not the case because hidden files are not synced by default. When I switch to syncing hidden files then the recall functionality works as expected.

**Comment by moscicki** [comment]
Possible solutions: make exception for this file even if hidden (preferable) or change the file pattern to avoid leading dot (replace by an underscore or two)

**Comment by ogoffart** [comment]
2.1.1 should be fixed.

**Comment by Dianafg76** [comment]
I tested this issue and is working OK
Desktop v ownCloud-2.1.1.3104-nightly20160209.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}
