### ISSUE TITLE
[CentOS 7] Cannot install package owncloud-client-2.1.0-11.1.x86_64

### ISSUE THREAD

**Issue by chillyjim** [owncloud/client#4422]
After following the instructions in issue 4400 I get 

`No Presto metadata available for isv_ownCloud_desktop
(1/2): qt5-qtbase-gui-5.5.1-2.el7.x86_64.rpm        | 5.4 MB   00:00     
owncloud-client-2.1.0-11.1.x86 FAILED                                          
http://download.opensuse.org/repositories/isv%3A/ownCloud%3A/desktop/CentOS_7/x86_64/owncloud-client-2.1.0-11.1.x86_64.rpm: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.
To address this issue please refer to the below knowledge base article 
https://access.redhat.com/articles/1320623
If above article doesn't help to resolve this issue please create a bug on https://bugs.centos.org/
Error downloading packages:
  owncloud-client-2.1.0-11.1.x86_64: [Errno 256] No more mirrors to try.`

I found the package but when I try to install it directly I get: 

`Examining owncloud-client-2.1.0-11.1.x86_64.rpm: owncloud-client-2.1.0-11.1.x86_64
Cannot install package owncloud-client-2.1.0-11.1.x86_64. It is obsoleted by installed package owncloud-client-2.0.2-8.1.x86_64
Error: Nothing to do`

Please advise. Thank you.

**Comment by jnweiger** [comment]
@chillyjim Hmm, an old version obsoleting a new version sounds like a confused package manager. Would
`` apt-get install -f ``
get you going?

**Comment by chillyjim** [comment]
Forcing always concerns me :) I'll take the route tonight and report back. Thanks.

**Comment by chillyjim** [comment]
rpm -F worked. Thanks.

**Comment by jnweiger** [comment]
Sorry,  rpm is of course the right tool here. I have too much Ubuntu these days.
