### ISSUE TITLE
[2.1.1 RC][OS X] Connection closed and Operation canceled

### ISSUE THREAD

**Issue by jodlajodla** [owncloud/client#4423]
Last few months I'm having problems with uploading and downloading Android project files to ownCloud folder. If project is built and there are files with extensions bin, class, dex, ... and may contain $ in file name then for sure there will be sequence of errors when uploading/downloading files:
Connection closed
Operation canceled
Operation canceled

Here's the log (Projects is the folder where those files are located):
`02/02/16 11:48:29	.../apps/.../.gradle/2.4/taskArtifacts/fileSnapshots.bin
Projects                      Operation canceled
02/02/16 11:48:29	.../apps/.../app/build/intermediates/dex/debug/classes.dex
Projects                      Operation canceled
02/02/16 11:48:29	.../apps/.../app/build/intermediates/classes/debug/si/.../.../AnotherFragment$2.class
Projects                      Connection closed

02/02/16 11:44:34	.../apps/.../.gradle/2.4/taskArtifacts/fileSnapshots.bin
Projects                      Operation canceled
02/02/16 11:44:34	.../apps/.../app/build/intermediates/dex/debug/classes.dex
Projects                      Operation canceled
02/02/16 11:44:34	.../apps/.../app/build/intermediates/classes/debug/si/.../.../AnotherFragment$2.class
Projects                      Connection closed

02/02/16 11:40:44	.../apps/.../.gradle/2.4/taskArtifacts/fileSnapshots.bin
Projects                      Operation canceled
02/02/16 11:40:44	.../apps/.../app/build/intermediates/dex/debug/classes.dex
Projects                      Operation canceled
02/02/16 11:40:44	.../apps/.../app/build/intermediates/classes/debug/si/.../.../AnotherFragment$2.class
Projects                      Connection closed

02/02/16 11:36:33	.../apps/.../.gradle/2.4/taskArtifacts/fileSnapshots.bin
Projects                      Operation canceled
02/02/16 11:36:33	.../apps/.../app/build/intermediates/classes/debug/si/.../.../model/Channel.class
Projects                      Operation canceled
02/02/16 11:36:33	.../apps/.../app/build/intermediates/classes/debug/si/.../.../AnotherFragment$2.class
Projects                      Connection closed`

My webserver is nginx and I think it's correctly configured since I don't have any other problem then this one. I noticed this problem in all versions I was using (I think the first one was 2.0 or something like that). Here is screenshot of client when error happened:
![ownCloud 2.1.1 RC OS X](http://i.imgur.com/59HLFfd.png)

and images of server logs:
![Server logs for .dex](http://i.imgur.com/TA0OgZa.png)
![Server logs for .class](http://i.imgur.com/gNnhjia.png)

All other files in other folders are uploaded/downloaded without errors. The problem "Connection closed and Operation canceled" exists only when build files of Android project are in queue for upload/download.

P.S.: The problem also exists on Linux version of client.

**Comment by guruz** [comment]
If it only happens on certain files/filenames it is probably related to the server.
Have you checked the server's owncloud.log file?
Does it behave differently if you switch the client bandwidth limiting to "automatic"?

**Comment by jodlajodla** [comment]
I checked all possible configuration files if there's any file type denied and didn't find anything. The configuration of webserver is created accordingly to the administration manual. The problem is that along bin, dex, class files sometimes connection is closed when png file must be uploaded/downloaded - in other directories png files are normally transferred - I will try to create bin, dex and class files in some other directories and post what will be the output. In owncloud.log I don't see anything weird except `{..."app":"files_locking","message":"INFO: Incrementing lock type 1 count for...}` which is logged for all files (along the other) which are also shown on all attached pictures. In all ownCloud clients I don't have any bandwidth limitations, the only limitation is file size (default 500 MB).

**Comment by guruz** [comment]
Still I think you should try with bandwidth limit activated since it sets the concurrency to 1 and might influence this.

Or is this fixed with a newer server version and can be closed?

**Comment by guruz** [comment]
@dragotin @PVince81 FYI
