### ISSUE TITLE
[Linux] Add "Restart" to system tray menu because client fails to connect

### ISSUE THREAD

**Issue by guoyunhe** [owncloud/client#4425]
I hope ownCloud client can add a new action "Restart" to system tray menu.

![1](https://cloud.githubusercontent.com/assets/5836790/12776974/a7dc06b6-ca62-11e5-86ad-7f1f06f595e6.png)

The client often fails to connect the server and never try again. Restarting client is the most effective way I can use.

**Comment by guruz** [comment]
What error message do you get? When does it fail? Why? (network change? suspend? proxy?)
thanks

**Comment by guruz** [comment]
We had known bugs for Linux where it helps to change to a newer Qt version e.g. 5.6 beta.
Which Qt?

**Comment by guoyunhe** [comment]
Qt 5.5, When boot, login, suspend, reconnect network.

**Comment by guruz** [comment]
We now have a 'force sync now' menu entry in the '...' button of a sync folder
