### ISSUE TITLE
[Password Policy] If you introduce the Ñ uppercase the folder/file is not shared and the user is warned

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4430]
### Steps to reproduce
1. Having a password policy of Uppercase letters
![screen shot 2016-02-04 at 09 51 21](https://cloud.githubusercontent.com/assets/12032058/12810203/f20eb090-cb24-11e5-8301-8de1c9fb4333.png)

2. Go to the Desktop Clien v 2.1.1 RC1
3. Create a new folder/file (e.g. aaa)
4. Share with ownCloud
5. Check Share link option
5. Select Password protect option
6. Introduce the letter the uppercase Ñ
7. Press Set password or enter

### Actual behaviour
Appears this error
![screen shot 2016-02-04 at 09 56 30](https://cloud.githubusercontent.com/assets/12032058/12810293/9c719b6a-cb25-11e5-9912-1172aca2ae26.png)
Log:
```
02-04 09:47:51:555 0x7ff87b442ca0 OCC::OcsJob::finished: Reply to "PUT"  QUrl( "https://XXXXXXXXXXXXXXXX/ocs/v1.php/apps/files_sharing/api/v1/shares/1" )  (QPair("password","/?22Ñ")) has unexpected status code: 403 "{"ocs":{"meta":{"status":"failure","statuscode":403,"message":"Password holds too less uppercase characters. Minimum 1 uppercase characters are required."},"data":[]}}"
02-04 09:47:51:556 0x7ff87b442ca0 OCC::ShareLinkWidget::slotServerError: Error from server 403 "Password holds too less uppercase characters. Minimum 1 uppercase characters are required."
02-04 09:47:51:639 0x7ff87b442ca0 OCC::OcsJob::finished: Reply to "PUT"  QUrl( "https://XXXXXXXXXXXXXXX/ocs/v1.php/apps/files_sharing/api/v1/shares/1" )  (QPair("password","/?22Ñ")) has unexpected status code: 403 "{"ocs":{"meta":{"status":"failure","statuscode":403,"message":"Password holds too less uppercase characters. Minimum 1 uppercase characters are required."},"data":[]}}"
02-04 09:47:51:640 0x7ff87b442ca0 OCC::ShareLinkWidget::slotServerError: Error from server 403 "Password holds too less uppercase characters. Minimum 1 uppercase characters are required."
```
NOTE: If you introduce other uppercase letter (e.g T) the folder/file is shared correctly
### Server configuration

**Operating system**:
Desktop v 2.1.1RC1 (build 3069) MAC, 2.1.1RC1 (build 5800) WINDOWS
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}

**Comment by rullzer** [comment]
This is not a desktop bug but a could be an issue in the password policy app.

@rperezb @jesmrec could you verify? And if so open an issue in the password_policy repo?
