### ISSUE TITLE
[Share via link] check the option Enforce password protection, go to the Desktop Client and share via link you can see the warning but in spanish

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4433]
### Steps to reproduce
1. Go to the Server Web with Admin
2. Go to Admin/admin
3. Go to Sharing option, and select "Enforce password protection"
![screen shot 2016-02-04 at 11 35 25](https://cloud.githubusercontent.com/assets/12032058/12812655/7fd5128a-cb33-11e5-9abb-5115cb4ee249.png)
4. Go to the Desktop client v 2.1.1RC1
5. Create a new folder/file (e.g 444444)
6. Share with ownCloud

### Actual behaviour
You can see the warning in Spanish 
![screen shot 2016-02-04 at 11 23 40](https://cloud.githubusercontent.com/assets/12032058/12812706/cdcf4a0a-cb33-11e5-96dc-65a76fe063c3.png)

### Server configuration
Desktop v 2.1.1RC1 (build 3069) MAC, 2.1.1RC1 (build 5800) WINDOWS
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}

**Comment by rullzer** [comment]
Is the user you are trying to share as configured in spanish?

**Comment by Dianafg76** [comment]
No, in English

**Comment by rullzer** [comment]
Is the installation itself in spanish then?

Since we get that message from the server and just display it in the client.

**Comment by Dianafg76** [comment]
The installation is in English

**Comment by Dianafg76** [comment]
I tested this issue and now is working Ok
![screen shot 2016-02-11 at 13 28 08](https://cloud.githubusercontent.com/assets/12032058/12976306/5d9ef48e-d0c3-11e5-98bc-7f0a2328f342.png)

Desktop v ownCloud-2.2.0.3112-nightly20160211.pkg
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}
