### ISSUE TITLE
Mac OSX Client 2.1.0 does not install

### ISSUE THREAD

**Issue by ricksbrown** [owncloud/client#4434]
On El Capitan.
Trying to install `ownCloud-2.1.0.2944.pkg`

Installer window title is "Install DISTRIBUTION_TITLE" which doesn't look right.
Proceed through installation, fails at the end with summary:
>The Installer encountered an error that caused the installation to fail. Contact the software manufacturer for assistance.

I then tried to install `ownCloud-2.0.2.2818.pkg` which worked fine. Still can't install `ownCloud-2.1.0.2944.pkg`.

**Comment by guruz** [comment]
Please try 2.1.1 rc1
https://owncloud.org/install/#testing-development

**Comment by ricksbrown** [comment]
Yep that one installs and the window title is "Install ownCloud Client" which is reassuring.
