### ISSUE TITLE
Sync client not able to finish discovery on large folders "Server error"

### ISSUE THREAD

**Issue by davidjericho** [owncloud/client#4435]
### Expected behaviour

The sync client should be able to discover a very wide and very deep folder structure of substantial size, while being able to download from the server.
### Actual behaviour

Discovery never completes, so a sync of a wide and deep large folder structure never starts.
### Steps to reproduce
1. Create a tree structure with thousands of directories and tens to hundreds of thousands of files.
2. Connect a sync client at the folder root, and try to sync. 
### Server configuration

Operating system: Confirmed on Linux, OS X and Windows. It seems to happen at smaller depths and widths on OS X, but I haven't confirmed to certainty.

Web server: RHEL6 Apache 2.2 using php-fpm, and fastcgi.

Database: MariaDB 10.1 with Galera and MaxScale.

PHP version: 5.6 from the Remi repo. 

ownCloud version: 8.1.5

Storage backend: Local file system with flash ZIL and L2ARC
### Client configuration

Client version: 2.1.0 in all cases

Operating system: Confirmed on Linux, OS X and windows

OS language: English 

Installation path of client: Default
### Logs

I have not seen anything in any logs that would indicate a problem beyond "Server error", despite there being no server error logged in either owncloud.log, the web server log, or the php-fpm log. 

Due to the extreme size of the data sets (the most recent report being 80,000 files in 8,000 directories, 189GB), I'll need to send the logs via some other mechanism than pastebin or the like.

**Comment by guruz** [comment]
On which file/directory does it report ```Server error```? Which HTTP code? Can't we deduce the maximum depth from that filename/directoryname?

It would indeed be good if we jump over the error and just not go into those folders. (which we do for some other errors).

(In general about failing discovery: https://github.com/owncloud/client/issues/2976 )

**Comment by davidjericho** [comment]
I have asked the appropriate support person for the logs of the failing syncs.

In testing, if we have the remote user setup the sync to run multiple sync folders, being each individual top level folder, reducing the depth and breadth of each singular sync, the sync works. 

If we setup a single sync, at the root folder, for the directory tree, this is when it fails. The data never syncs, as discovery never finishes. Uploads and downloads never occur.

There's nothing wrong with the folder that the sync stops at, as confirmed by setting up a sync on that folder alone, which completes successfully.

**Comment by hodyroff** [comment]
Still happening with 2.3.1 and oC 9.1.4? How deep those the tree go?
