### ISSUE TITLE
Missing qt-54-env.sh file on CentOS 7 x86_64 with owncloud-client-2.1.0-11.1.x86_64

### ISSUE THREAD

**Issue by TheVillux** [owncloud/client#4441]
### Expected behaviour
owncloud starts

### Actual behaviour
> /bin/owncloud: line 2: /opt/qt-5.4/bin/qt*-env.sh: No such file or directory

### Client configuration
CentOS Linux release 7.2.1511 x86_64
libowncloudsync0-2.1.0-11.1.x86_64
owncloud-client-l10n-2.1.0-11.1.x86_64
owncloud-client-2.1.0-11.1.x86_64

### Workaround
I'm able to solve this issue by creating a _/opt/qt-5.4/bin/qt54-env.sh_ file with the following content:
`
#!/bin/bash

QT_BASE_DIR=/opt/qt54
export QTDIR=$QT_BASE_DIR
export PATH=$QT_BASE_DIR/bin:$PATH

if [[ $(uname -m) == "x86_64" ]]; then
  export LD_LIBRARY_PATH=$QT_BASE_DIR/lib/x86_64-linux-gnu:$QT_BASE_DIR/lib:$LD_LIBRARY_PATH
else
  export LD_LIBRARY_PATH=$QT_BASE_DIR/lib/i386-linux-gnu:$QT_BASE_DIR/lib:$LD_LIBRARY_PATH
fi

export PKG_CONFIG_PATH=$QT_BASE_DIR/lib/pkgconfig:$PKG_CONFIG_PATH

TEST=`echo $0 | grep wrapper`
if [ "$TEST" != "" ]; then
   exec `echo $0 | sed s/-wrapper//` $*
fi
`

### Notes
I wasn't able to successfully locate which rpm the above file is supposed to be packaged with, so it might be a simple packaging error, or maybe it's something specific to my install.

**Comment by dragotin** [comment]
I think this is fixed already.

**Comment by TheVillux** [comment]
Great, thank you.

**Comment by jnweiger** [comment]
Should be in the package owncloud-client, if needed for the platform. The /usr/bin/owncloud script should have a conditional to check for its presence.

Would an empty script also work for you? I am surprised you come up with that complex solution.

**Comment by TheVillux** [comment]
I won't be able to test that for a little bit, since I don't have that machine immediately available. However, I just pulled the above script from some Google searching; I bet an empty one might work just as well...probably should have tried that first.

**Comment by jnweiger** [comment]
The fix existed in 2.1.1 only. Backport now deployed.
Upcoming owncloud-client-2.1.0-12.1 should have this fixed.
Thanks for pointing this out!
