### ISSUE TITLE
The best choice for windows

### ISSUE THREAD

**Issue by K4nape** [owncloud/client#4442]
Hello guys,
I have windows 8.1 server. And i need your help in choosing. 
What to use? 
What programs?
Maybe use "wamp" ? or other programs?
What is the best way?

**Comment by danimo** [comment]
1. This is the the bug tracker for the ownCloud client. It will run natively, no server required.
2. The server no longer supports Windows natively. Please see https://doc.owncloud.org/server/8.2/admin_manual/installation/system_requirements.html#supported-platforms for a list of supported Operating Systems.
3. This bug tracker is for bugs only. For general support, please see https://owncloud.org/support.

**Comment by K4nape** [comment]
@danimo but i can instal in windows "Webserver: Apache 2" ?

**Comment by K4nape** [comment]
windows no have program?

**Comment by LukasReschke** [comment]
As @danimo stated:

> This bug tracker is for bugs only. For general support, please see https://owncloud.org/support.

And no, Windows Server is not supported.

**Comment by K4nape** [comment]
@LukasReschke thx. Maybe i can use "VirtualBox" ?

**Comment by LukasReschke** [comment]
Yes. But:

> This bug tracker is for bugs only. For general support, please see https://owncloud.org/support.
