### ISSUE TITLE
Document Local Disk Space Policy

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4443]
@carlaschroder do you think it makes sense to add a little documentation on how the client handles low local disk space situations, and how that can be influenced?

There are two values: The **freeSpaceLimit** and the  **CriticalFreeSpaceLimit**.

If a download would cause that the available local diskspace goes below the **freeSpaceLimit** this particular download is handled as an individual file error, with repeating and blacklisting. Other downloads are continued.

If the available space falls below the **CriticalFreeSpaceLimit** the whole sync process is stopped with an critical error ("Red X").

The **freeSpaceLimit** defaults to 250 MB and the **CriticalFreeSpaceLimit** defaults to 50 MB. Both values can be influenced at runtime through environment variables `OWNCLOUD_CRITICAL_FREE_SPACE_BYTES` and `OWNCLOUD_FREE_SPACE_BYTES`.

@ckamm please verify, thanks.

**Comment by carlaschroder** [comment]
Yes @dragotin, definitely. Is this user-configurable?

**Comment by ckamm** [comment]
@dragotin This is correct, see https://github.com/owncloud/client/wiki/Testing-Scenarios-2.1 .
@carlaschroder Usually users shouldn't need to override the defaults. The environment variables dragotin managed can be used to configure it if need be.

**Comment by carlaschroder** [comment]
Thanks @dragotin and @ckamm

**Comment by ckamm** [comment]
@carlaschroder I've written some basic documentation, please review 1c74448

**Comment by carlaschroder** [comment]
Can this be closed? Do you need anything from me? @dragotin @ckamm

**Comment by ckamm** [comment]
@carlaschroder If you're fine with this, it could be closed.

**Comment by carlaschroder** [comment]
ok. happy weekend all, and thanks for writing this up @ckamm
