### ISSUE TITLE
[OS X] [2.1.0] Crash when trying to start

### ISSUE THREAD

**Issue by felixbello** [owncloud/client#4444]
OSX El Capitan: 10.11.3
Client Version: "ownCloud version 2.1.0 (build 2944)"

./owncloud --logfile -
m_crashReporterChar:  /Applications/owncloud.app/Contents/MacOS/owncloud_crash_reporter
02-08 11:54:28:204 0x7fdb52c2b480 OCC::Application::setupLogging: "################## ownCloud en_US () 2.1.0 (build 2944)"
02-08 11:54:28:205 0x7fdb52c2b480 OCC::Application::setupTranslations: void OCC::Application::setupTranslations() Using "en" translation
02-08 11:54:28:210 0x7fdb52c2b480 OCC::SocketApi::SocketApi: SocketApi:  server started, listening at  "9B5WD74GWJ.com.owncloud.desktopclient.socketApi"
02-08 11:54:28:211 0x7fdb52c2b480 OCC::FolderMan::FolderMan: setting remote poll timer interval to 30000 msec
02-08 11:54:28:212 0x7fdb52c2b480 OCC::AccountManager::restoreFromLegacySettings: Migrate: checking old config  "/Users/felix/Library/Application Support/ownCloud/owncloud.cfg"
02-08 11:54:28:213 0x7fdb52c2b480 OCC::FolderMan::setupFoldersMigration: * Setup folders from  "/Users/felix/Library/Application Support/ownCloud/folders" (migration)
02-08 11:54:28:213 0x7fdb52c2b480 OCC::ClientProxy::setupQtProxyFromConfig: Set proxy configuration to use system configuration

**Comment by guruz** [comment]
2.1.1 rc2 is out, could you please try that one?
Did it offer you to send the report to the crash reporter?

**Comment by felixbello** [comment]
so i've tryed it right now.. the same:

"m_crashReporterChar:  /Applications/owncloud.app/Contents/MacOS/owncloud_crash_reporter
02-09 15:07:48:359 0x7f9880706280 OCC::Application::setupLogging: "################## ownCloud en_US () 2.1.1rc2 (build 3102)"
02-09 15:07:48:361 0x7f9880706280 OCC::Application::setupTranslations: void OCC::Application::setupTranslations() Using "en" translation
02-09 15:07:48:363 0x7f9880706280 OCC::SocketApi::SocketApi: SocketApi:  server started, listening at  "9B5WD74GWJ.com.owncloud.desktopclient.socketApi"
02-09 15:07:48:363 0x7f9880706280 OCC::FolderMan::FolderMan: setting remote poll timer interval to 30000 msec
02-09 15:07:48:363 0x7f9880706280 OCC::AccountManager::restoreFromLegacySettings: Migrate: checking old config  "/Users/felix/Library/Application Support/ownCloud/owncloud.cfg"
02-09 15:07:48:363 0x7f9880706280 OCC::FolderMan::setupFoldersMigration: * Setup folders from  "/Users/felix/Library/Application Support/ownCloud/folders" (migration)
02-09 15:07:48:364 0x7f9880706280 OCC::ClientProxy::setupQtProxyFromConfig: Set proxy configuration to use system configuration
"

No it don't offer to send the report

**Comment by guruz** [comment]
@felixbello Maybe as a workaround you can try removing the config files in ```"/Users/felix/Library/Application Support/ownCloud/```

Does it still crash? Need to reconfigure the client then though.

**Comment by guruz** [comment]
@danimo suspects this is related to the proxy PAC parsing. So setting the client to not use the system proxy might fix this (should be the default when resetting the config)

**Comment by felixbello** [comment]
@guruz I've just tryed it.. removing the owncloud.cfg but.. still the same.
how can i reconfigure the client?
it's there an CLI method?

**Comment by guruz** [comment]
If you add this (or change existing value) in ```owncloud.cfg``` does it work then?

```
[Proxy]
type=2
```

**Comment by felixbello** [comment]
@guruz i've just added this line to the owncloud.cfg and the result is now:

"m_crashReporterChar:  /Applications/owncloud.app/Contents/MacOS/owncloud_crash_reporter
02-10 10:07:05:443 0x7fac234300d0 OCC::Application::setupLogging: "################## ownCloud en_US () 2.1.1rc2 (build 3102)"
02-10 10:07:05:444 0x7fac234300d0 OCC::Application::setupTranslations: void OCC::Application::setupTranslations() Using "en" translation
02-10 10:07:05:449 0x7fac234300d0 OCC::SocketApi::SocketApi: SocketApi:  server started, listening at  "9B5WD74GWJ.com.owncloud.desktopclient.socketApi"
02-10 10:07:05:449 0x7fac234300d0 OCC::FolderMan::FolderMan: setting remote poll timer interval to 30000 msec
02-10 10:07:05:986 0x7fac234300d0 unknown: Error receiving trust for a CA certificate
02-10 10:07:05:988 0x7fac234300d0 unknown: Error receiving trust for a CA certificate
02-10 10:07:05:991 0x7fac234300d0 unknown: Error receiving trust for a CA certificate
02-10 10:07:05:993 0x7fac234300d0 unknown: Error receiving trust for a CA certificate
02-10 10:07:05:995 0x7fac234300d0 unknown: Error receiving trust for a CA certificate
02-10 10:07:06:472 0x7fac234300d0 unknown: QIODevice::read: device not open
02-10 10:07:06:474 0x7fac234300d0 OCC::FolderMan::setupFolders: * Setup folders from settings file
02-10 10:07:06:474 0x7fac234300d0 OCC::ClientProxy::setupQtProxyFromConfig: Set proxy configuration to use NO proxy"

**Comment by felixbello** [comment]
just an update...
i've tryed to start it with an other profile on this machine.. was okay.. now i ve deletet my old profile and created an new one.. and now it works fine how expected!

thanks for help!

**Comment by guruz** [comment]
@felixbello Good to hear. Also you might want to consider to update to 2.1.1

**Comment by jorgelbg** [comment]
I'm facing the same issue with the updated release v2.1.1 (build 3107) same output on the terminal, and deleting the folder doesn't have any effect.

**Comment by guruz** [comment]
Does the trick mentioned in https://github.com/owncloud/client/issues/4444#issuecomment-182237517 change anything?

You might also want to delete everything which has ```ownCloud``` in the name in ```Library//Preferences/``` and also check ```Library//Caches/com.owncloud.desktopclient```

**Comment by jorgelbg** [comment]
Actually it was an unrelated issue with owncloud, the delay was coming from a attempt to connect a to a remote AFP folder on a different Mac that was not accessible at the time, for some reason when owncloud gets started it tries to connecto to the remote folder. As far as I can see this is totally unrelated to owncloud itself but its kind of odd that the conection attempt happens at all.

**Comment by TheLalaMan** [comment]
@jorgelbg : I can confirm this! Had the same problem and my Mac was configured to connect to an SMB share on startup. Disconnected the shared directories and hey pronto- ownCloud was working again :-) I have removed the shares from my startup items and hope this is the end of it.
