### ISSUE TITLE
Access denied error on shared folders

### ISSUE THREAD

**Issue by RealGeeman** [owncloud/client#4447]
We us a Shared Folder in our company which is shared read-only for everyone.
The folder gets updated from "root" only. This includes deletion/adding/renaming of folders and files.

Since the last? update everyone gets error message when there is an update. For example an excerpt of logfile:

#=#=#=# Syncrun started 2016-02-08T00:42:57 until 2016-02-08T00:42:58 (1573 msec)
|0|Richtlinien_externe_Dokumente|INST_SYNC|Down|1454888577|56b7d68146d93|0|0000000351e4e89fdffd9|0||0|0|1454888574|||INST_NONE|
|0|Richtlinien_externe_Dokumente/AMA-Biosiegel|INST_SYNC|Down|1454888554|56b7d66baa424|0|0031619251e4e89fdffd9|0||0|0|1454888558|||INST_NONE|
|0|Richtlinien_externe_Dokumente/AMA-Biosiegel/Checklisten Verarbeiter|INST_SYNC|Down|1454888540|56b7d65e8ca08|0|0031619751e4e89fdffd9|0||0|0|1454888550|||INST_NONE|

File is correct on the server and online in my personal owncloud, but not on the local/client-side its an old version.

I am using ownCloud 8.2.2 (production) with client Version 2.1.0 (build 5683). 

This affects nearly 300 people - Thank you

**Comment by guruz** [comment]
Which error message do you get?

In general for commercial setups we recommend the enterprise license for support.

Have you tried if it works with 2.1.1 rc2?

**Comment by RealGeeman** [comment]
Error is just "Access denied" / "Zugriff verweigert". Systray is red.

Unfortunately we are not able to compile the sources here.

**Comment by guruz** [comment]
@RealGeeman 2.1.1 is released :)

**Comment by RealGeeman** [comment]
Its fixed in 2.1.1 :+1:
