### ISSUE TITLE
[Win64] [Sync Client 2.1.0] unreasonable memory usage or leak

### ISSUE THREAD

**Issue by xraxra** [owncloud/client#4449]
**Expected Behavior**
Memory usage shouldn't increase when idle

**Actual behavior**
Left PC running a couple days, noticed owncloud client memory usage up to 1.5 GB and slowly rising. CPU usage is repeatedly spikes to 17%, affecting Windows performance.
I haven't changed any files or synced new ones, it is just sitting idle in the taskbar like Dropbox or similar.

**Comment by guruz** [comment]
How often does the CPU usage spike? Do you mean it is syncing all the time? (check the settings dialog).

**Comment by xraxra** [comment]
It was spiking maybe every 10 to 20 seconds, sorry I don't have exact information. 

I ended up killing the process and relaunching the owncloud sync client. The memory usage is at 76mb currently, after about 7 hours (started at around 50mb). Might be normal, it has slowly risen to that over the day. 

It isn't using any CPU (or strange spikes) at the moment, so it seemed like that was only when I was in the 1.5 gb memory usage range. 

I don't think it is syncing all the time, at least from checking the Activity tabs, it has only had activity when I've moved or delete a few files.

I have noticed in the Not Synced tab, there are a couple files it is having trouble with, one is a png and one is a jpg. There are a lot of "File has changed since discovery"

Those two files both have what looks like a temporary file associated with them, for example:
.28025401.jpg.~79c0
and 
.Df459.png.~2d1e

I'm not sure why it thinks the two files have changed, they haven't been modified since the original copy into my owncloud folder. I tried deleting those 2 temporary files but they were recreated again, likely coinciding with the log of "File has changed since discovery"

I'll keep an eye on the memory usage and see if it increases when I leave it running overnight.

**Comment by guruz** [comment]
@ckamm @ogoffart I was thinking that error message was for uploads not downloads?

**Comment by ckamm** [comment]
@guruz That message means the sync client thinks the local file has changed between now and the discovery and will not overwrite it with the downloaded temporary file. It checks the mtime and size of the file.

**Comment by ogoffart** [comment]
Can you try again with 2.1.1?  There was an bug in 2.1.0 with some locales in which we would get the wrong mtime for some files which could cause this problem.  This might have fixed the problem of  "File has changed since discovery".

But I don't know about the memory usage. How many files do you have and how many directories?

**Comment by xraxra** [comment]
there's 7,876 files and 104 directories (basically moved my baracuda Copy account over since they are shutting down...)

No weird memory / CPU usage today, left the computer on overnight

Yesterday I cut & pasted the files the client kept thinking had changed (copying them outside the shared folder), and it redownloaded them, after doing so there hasn't been any new logs in the Not Synced tab.

It might have been that mtime bug, the client had been running for several days before I noticed the large memory usage. 
I will update the client and keep an eye on it!

**Comment by guruz** [comment]
Thanks. please re-open if you find something.
