### ISSUE TITLE
[OS X] [2.1.0] Local files are read-only regardless of permissions on server

### ISSUE THREAD

**Issue by jrtilson** [owncloud/client#4450]
### Expected behaviour

Files with 'can edit' permissions are writable locally by user

### Actual behaviour

Files are all read-only

### Steps to reproduce

1. ownCloud user has access to shared folder, with can edit permissions
2. Install/open owncloud client for the first time
3. Set server url and authenticate
4. Accept all defaults (sync everything)
5. Sync begins
6. Files are read-only

```  
pwd
/Users/user/ownCloud/Shared/Technology
ls -lha
total 8
drwxr-xr-x  3 user  staff   102B  9 Feb 14:18 ./
drwxr-xr-x  4 user  staff   136B  9 Feb 14:18 ../
-r--r--r--  1 user  staff     4B  8 Feb 11:12 document.txt 
```

### Server configuration
Operating system: Ubuntu 12.04 LTS

Web server: Apache2

Database: MySQL

PHP version: 5.4.x

ownCloud version: 6.0.4.1

Storage backend: 

### Client configuration
Client version:  2.1.0 (build 2944)

Operating system: OS X 10.11.2

OS language: English

Installation path of client: /Applications/ownCloud

### Logs

Client log here:

https://gist.github.com/jrtilson/5f06e35994d7fdc63834

**Comment by guruz** [comment]
Could you please try 2.1.1 (rc2 or the release which comes today/tomorrow)

**Comment by jrtilson** [comment]
I tried installing v 2.1.1, the issue persists on a fresh setup.

**Comment by jrtilson** [comment]
Just an update/note: I tried a (very) old ownCloud client (v 1.5.0) and the files were read-write as was expected.

**Comment by marijnkortstra** [comment]
We're experiencing the exact same problem as @jrtilson.

**Comment by guruz** [comment]
@marijnkortstra Which version? Which OS? Did you try a clean re-sync?

**Comment by ckamm** [comment]
The problem here is that remotePerm is "":
> OCC::SyncJournalDb::setFileRecord: "INSERT OR REPLACE INTO metadata (phash, pathlen, path, inode, uid, gid, mode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote, contentChecksum, contentChecksumTypeId) VALUES (?1 , ?2, ?3 , ?4 , ?5 , ?6 , ?7, ?8 , ?9 , ?10, ?11, ?12, ?13, ?14, ?15, ?16);" 5003461902563014693 30 "Shared/Technology/document.txt" 49081894 "1454947973" "0" "56b8be8e15f81" "00040118oc7449ebb679" "" 4 0 "" "" 0

So probably there's a bug in the version you use on the server (6.0.4.1). We should add a patch to not adjust permissions for servers this old.

**Comment by guruz** [comment]
Server 6 is too old.

@marijnkortstra Which server version do you have?

**Comment by ckamm** [comment]
@guruz Is server 6 among the versions we support with client 2.1?

**Comment by guruz** [comment]
@ckamm Versions 7 to 9 of the server are supported
https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule

( @LukasReschke correct me if i'm wrong)

**Comment by ckamm** [comment]
The file permissions will now only be changed when the server version is 7.0.0 or newer.

**Comment by dragotin** [comment]
@ckamm awesome

**Comment by ckamm** [comment]
We talked about this on IRC and agreed we need to do something about unsupported server/client combinations. The discussion and plan is in #4523.

**Comment by ckamm** [comment]
Closing this because the fix is small and we're not planning to actively support interaction with unsupported server versions anyway.
