### ISSUE TITLE
Error in make package.. When I try to create .exe

### ISSUE THREAD

**Issue by diogosantos89** [owncloud/client#4451]
Hi,
I'm getting an error when i execute the command make package.
There are some dll files that i say that cannot find.
they are:
icudata53.dll
icui18n53.dll
icuuc53.dll
libwebp-4.dll

on the atachments is a print of the error.

can you help me out?

i follow the tutorial:
https://doc.owncloud.org/desktop/1.8/building.html

and the link from youtube
https://www.youtube.com/watch?v=ncpu7YGdHaM

![321](https://cloud.githubusercontent.com/assets/16138441/12943903/21610094-cfdc-11e5-8631-4c27d51f3cd1.jpg)

Someone can help me?

**Comment by danimo** [comment]
Don't use the guide on building 1.8 when you're not. Use https://doc.owncloud.org/desktop/2.1/building.html.

**Comment by diogosantos89** [comment]
Thanks for the answer.

It would be possible to describe the steps should I follow?

Thank you

**Comment by danimo** [comment]
@diogosantos89 All steps are described in the manual. We cannot offer support beyond that.

**Comment by diogosantos89** [comment]
![docker](https://cloud.githubusercontent.com/assets/16138441/12953420/44a7570c-d012-11e5-8c9a-e625e5bf3f41.JPG)


You can give me some tips?

**Comment by diogosantos89** [comment]
I ran this command on:

root of the ownCloud Client’s source tree  /admin/win/docker

**Comment by hanhuakai880101** [comment]
you can run command as follows:
docker build -t owncloud-client-win32:2.1.0 . 
@diogosantos89
