### ISSUE TITLE
Server does not support X-OC-MTime

### ISSUE THREAD

**Issue by Pisoko** [owncloud/client#4452]
Hey all,
I can't find any info to the error of my Sync-Client Version 2.1.0 (build 5683):

**Server does not support X-OC-MTime**

Any ideas?

**Comment by RealRancor** [comment]
Seems two of you guys have now reported this at different places:

https://github.com/owncloud/core/issues/22268

**Comment by nickvergessen** [comment]
2.1.1 has been released yesterday, mind testing if that helps?
https://owncloud.org/install/#install-clients

**Comment by Xilentura** [comment]
Maybe we can close this issue and move to [this X-OC-MTime Topic](https://github.com/owncloud/core/issues/22268), so we don't have double posts?
