### ISSUE TITLE
[Windows] [2.1.1] Sync Engine: symlinked syn directories; doesn't work!?

### ISSUE THREAD

**Issue by RalfWW** [owncloud/client#4453]
Hi,

I "decrypt" the note "Sync Engine: symlinked syn directories " in the relase notes as:
"is syncing symlinked directories -again-".
Am I wrong?

I've tested this with 2.1.1 build 5837 under Win 7 prof 64bit and it is not working.

If made a symlink (test) within the owncloud directory to a "outside" directory.

The client still shows "Symbolische Verknüpfung werden bei der Synchronisation nicht unterstützt" (symlinks are not supported...)

Thanks

Ralf

**Comment by guruz** [comment]
@RalfWW We only support if the sync directory itself is a symlink. Symlinks inside are not supported.

I didn't follow the discussion there, @dragotin and @ckamm might have.

**Comment by ckamm** [comment]
@RalfWW Yes, the adjustment was only for the case when the sync directory itself was a symlink.
