### ISSUE TITLE
Verify Sync Protocol Specification

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4455]
https://github.com/cernbox/smashbox/blob/master/protocol/protocol.md is a document containing the sync protocol specification. 

This issue is about checking if there were changes between one of the last commit to the document https://github.com/cernbox/smashbox/commit/b4b90863b080f3b366438b70da903648036bf83d and now,

@ogoffart @ckamm your help on this please.

**Comment by dragotin** [comment]
https://github.com/owncloud/client/commit/dd89ab59e4ef223112d712e4d04379fa2f6ce359 is a candidate that needs to be updated probably.

**Comment by LukasReschke** [comment]
Probably also https://github.com/owncloud/core/pull/22834

cc @rullzer

**Comment by dragotin** [comment]
Created https://github.com/cernbox/smashbox/pull/62
