### ISSUE TITLE
[ownBrander] Disable Proxy 

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#4458]
As an ownCloud admin, I would like to disable the proxy settings in the desktop sync client so that I can pre-configure a proxy configuration for accessing ownCloud, and users can't change the settings to bypass the proxy.

Acceptance Criteria:
- Settings are made in ownBrander 
- ownBrander updates a config file for ownCloud that deactivates the proxy setting options
- Proxy setting options can be seen, just not adjusted (input fields are gray)

![56442e02-c50b-11e5-9cea-8b5a605ff775](https://cloud.githubusercontent.com/assets/1818977/12952446/7e855484-cfe4-11e5-8438-da9b96bdea1f.png)

This is a late add for 2.2, but if we can make it part of that release, great.

**Comment by MTRichards** [comment]
/cc @dragotin @rperezb

00004666

**Comment by guruz** [comment]
Easiest would be if ownBrander spits out something we just need to 1:1 write into ```owncloud.cfg``` on first start.

**Comment by dragotin** [comment]
Branding option in `theme.h` please.

**Comment by rperezb** [comment]
yes, in  `theme.h` as other options

**Comment by MTRichards** [comment]
- Labeling this Gold so it doesn't get lost as we work on 2.2.

**Comment by danimo** [comment]
@MTRichards What about proxies that require username and password?

**Comment by MTRichards** [comment]
Then the admins wouldn't be able to lock it on ownBrander. Or rather they would, but it would not be smart.

**Comment by ogoffart** [comment]
Tested and added documentation. Works as expected: settings are grayed.

Note: Any reason why the settings should be disabled (grayed) rather than hidden? IMHO it's not really user friendly to have settings there that can never be touched. I would think hidding it would be a better idea.

**Comment by guruz** [comment]
Thanks @ogoffart for testing. I was also wondering but this is how it was specified. Maybe it's also good to see then that the proxy is set to system proxy, not to some other value.
