### ISSUE TITLE
Connection closed "Verbindung beendet"

### ISSUE THREAD

**Issue by Artain** [owncloud/client#4462]
Client can't connect to server. After entering the URI and accepting the certificate you get to the login screen. After submitting the login data a red box appears with the text "Verbindung beendet" which means connection closed. 

I got an error in the Nginx log:
`2016/02/08 09:48:14 [error] 368#0: *563 readv() failed (104: Connection reset by peer) while reading upstream, client: xxx.xxx.xxx.xxx, server: owncloud.xxx.xxx, request: "PROPFIND /remote.php/webdav/ HTTP/1.1", upstream: "fastcgi://unix:/run/php-fpm/php-fpm.sock:", host: "owncloud.xxx.xxx"`

In php I got nothing

Client log
`02-09 10:05:26:255 0x897808 OCC::OwncloudSetupWizard::slotConnectToOCUrl: Connect to url:  "https://owncloud.xxx.xxx"
02-09 10:05:26:256 0x897808 OCC::OwncloudWizard::appendToConfigurationLog: Setup-Log:  "Verbindungsversuch mit ownCloud unter https://owncloud.xxx.xxx"
02-09 10:05:26:256 0x897808 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://owncloud.xxx.xxx" + "/"
02-09 10:05:26:472 0x7f11370 unknown: void QHttpNetworkConnectionChannel::_q_error(QAbstractSocket::SocketError) QAbstractSocket::RemoteHostClosedError QSslSocket(0x7f112f0) QHttpNetworkReply(0x806f418) 0 false 3 8 QAbstractSocket::ConnectedState
02-09 10:05:26:472 0x7f11370 unknown: ERRORING CURRENT QHttpNetworkReply(0x806f418)  QUrl( "https://owncloud.xxx.xxx/remote.php/webdav/" ) 
02-09 10:05:26:474 0x897808 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 2 "Verbindung beendet" QVariant(Invalid)
02-09 10:05:26:474 0x897808 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 0 ""
02-09 10:05:26:472 0x7f11370 unknown: void QHttpNetworkConnectionChannel::_q_disconnected() 0 QSslSocket(0x7f112f0) QObject(0x0)  0 false 3 16`

My configuration is the same as in the arch wiki
@https://wiki.archlinux.org/index.php/OwnCloud#Nginx

I tested with curl the PROPFIND and got a valid answer. I also tried a wrong login data and it seems it doesn't even check if they exist.

Versions server:
Arch Linux
2016.02.01
Kernel: 4.3.3

PHP:
PHP 7.0.3 (cli) (built: Feb  2 2016 18:23:27) ( NTS )
Zend Engine v3.0.0,

Nginx:
nginx/1.8.1

Client:
Version 2.1.0 (build 5683) 
Windows 10 1511

Also the android and blackberry client works.

**Comment by RealRancor** [comment]
Hi,

either this is already fixed with the upcoming 2.1.1 (should be released a few hours ago) or a possible duplicate of https://github.com/owncloud/client/issues/4423 / https://github.com/owncloud/client/issues/3382

**Comment by Artain** [comment]
Just tested version 2.1.1 everything seems to be working now. Thank you.

**Comment by jnweiger** [comment]
|| Linux Package Installation Report |
|-|-|
|date| Thu Jun 10 13:48:11 CEST 2021
|repourl| http://195.201.128.253/client/ocfablabnbg-258/ocfablabnbg-2.8.2.4362-linux
|package| ocfablabnbg-client

<details><summary>Test details (click to view)</summary>

|Platform|Test|Result|
|-|-|-|
|centos:7|01_cmd_vers.sh|	2.8.2 (build 4362) Jun 10 2021 08:38:44
|centos:8|01_cmd_vers.sh|	2.8.2 (build 4362) May 28 2021 12:06:08
|debian:9|01_cmd_vers.sh|	2.8.2 (build 4362) May 28 2021 12:06:08
|debian:10|01_cmd_vers.sh|	2.8.2 (build 4362) May 28 2021 12:06:08
|fedora:31|01_cmd_vers.sh|	2.8.2 (build 4362) May 28 2021 12:06:08
|fedora:32|01_cmd_vers.sh|	2.8.2 (build 4362) May 28 2021 12:06:08
|fedora:33|01_cmd_vers.sh|	2.8.2 (build 4362) May 28 2021 12:06:08
|fedora:34|01_cmd_vers.sh|	2.8.2 (build 4362) May 28 2021 12:06:08
|ubuntu:18.04|01_cmd_vers.sh|	2.8.2 (build 4362) May 28 2021 12:06:08
|ubuntu:20.04|01_cmd_vers.sh|	2.8.2 (build 4362) May 28 2021 12:06:08
|ubuntu:20.10|01_cmd_vers.sh|	2.8.2 (build 4362) May 28 2021 12:06:08
|ubuntu:21.04|01_cmd_vers.sh|	2.8.2 (build 4362) May 28 2021 12:06:08
|opensuse/leap:15.1|01_cmd_vers.sh|	2.8.2 (build 4362) May 28 2021 12:06:08
|opensuse/leap:15.2|01_cmd_vers.sh|	2.8.2 (build 4362) May 28 2021 12:06:08
|opensuse/leap:15.3|01_cmd_vers.sh|	2.8.2 (build 4362) May 28 2021 12:06:08
|centos:7|10_key_expiry.sh|	<oem@s2.owncloud.com> expires: 2022-03-16
|centos:8|10_key_expiry.sh|	<oem@s2.owncloud.com> expires: 2022-03-16
|debian:9|10_key_expiry.sh|	<oem@s2.owncloud.com> expires: 2022-06-10
|debian:10|10_key_expiry.sh|	<oem@s2.owncloud.com> expires: 2022-06-10
|fedora:31|10_key_expiry.sh|	<oem@s2.owncloud.com> expires: 2022-03-16
|fedora:32|10_key_expiry.sh|	<oem@s2.owncloud.com> expires: 2022-03-16
|fedora:33|10_key_expiry.sh|	<oem@s2.owncloud.com> expires: 2022-03-16
|fedora:34|10_key_expiry.sh|	<oem@s2.owncloud.com> expires: 2022-03-16
|ubuntu:18.04|10_key_expiry.sh|	<oem@s2.owncloud.com> expires: 2022-06-10
|ubuntu:20.04|10_key_expiry.sh|	<oem@s2.owncloud.com> expires: 2022-06-10
|ubuntu:20.10|10_key_expiry.sh|	<oem@s2.owncloud.com> expires: 2022-06-10
|ubuntu:21.04|10_key_expiry.sh|	<oem@s2.owncloud.com> expires: 2022-06-10
|opensuse/leap:15.1|10_key_expiry.sh|	<oem@s2.owncloud.com> expires: 2022-03-16
|opensuse/leap:15.2|10_key_expiry.sh|	<oem@s2.owncloud.com> expires: 2022-03-16
|opensuse/leap:15.3|10_key_expiry.sh|	----------- NO OUTPUT ------------
|centos:7|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|centos:8|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|debian:9|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|debian:10|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:31|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:32|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:33|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:34|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:18.04|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:20.04|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:20.10|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:21.04|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|opensuse/leap:15.1|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|opensuse/leap:15.2|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|opensuse/leap:15.3|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|centos:7|20_qttrans_de.sh|	OK
|centos:8|20_qttrans_de.sh|	OK
|debian:9|20_qttrans_de.sh|	OK
|debian:10|20_qttrans_de.sh|	OK
|fedora:31|20_qttrans_de.sh|	OK
|fedora:32|20_qttrans_de.sh|	OK
|fedora:33|20_qttrans_de.sh|	OK
|fedora:34|20_qttrans_de.sh|	OK
|ubuntu:18.04|20_qttrans_de.sh|	OK
|ubuntu:20.04|20_qttrans_de.sh|	OK
|ubuntu:20.10|20_qttrans_de.sh|	OK
|ubuntu:21.04|20_qttrans_de.sh|	OK
|opensuse/leap:15.1|20_qttrans_de.sh|	OK
|opensuse/leap:15.2|20_qttrans_de.sh|	OK
|opensuse/leap:15.3|20_qttrans_de.sh|	OK
|centos:7|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.0.2k-fips  26 Jan 2017
|centos:8|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1g FIPS  21 Apr 2020
|debian:9|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.0l  10 Sep 2019
|debian:10|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1d  10 Sep 2019
|fedora:31|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1g FIPS  21 Apr 2020
|fedora:32|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1k  FIPS 25 Mar 2021
|fedora:33|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1k  FIPS 25 Mar 2021
|fedora:34|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1k  FIPS 25 Mar 2021
|ubuntu:18.04|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1  11 Sep 2018
|ubuntu:20.04|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1f  31 Mar 2020
|ubuntu:20.10|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1f  31 Mar 2020
|ubuntu:21.04|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1j  16 Feb 2021
|opensuse/leap:15.1|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.0i-fips  14 Aug 2018
|opensuse/leap:15.2|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1d  10 Sep 2019
|opensuse/leap:15.3|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1d  10 Sep 2019
|centos:7|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst
|centos:8|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst
|debian:9|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst
|debian:10|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst
|fedora:31|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst
|fedora:32|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst
|fedora:33|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst
|fedora:34|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst
|ubuntu:18.04|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst
|ubuntu:20.04|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst
|ubuntu:20.10|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst
|ubuntu:21.04|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst
|opensuse/leap:15.1|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst
|opensuse/leap:15.2|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst
|opensuse/leap:15.3|50_sync_excl.lst.sh|	418 /etc/ocfablabnbg/sync-exclude.lst

</details>

Generated via client/linux-docker-install/run_tests.sh

----
