### ISSUE TITLE
[Qt] Desktop client trusts SHA1 signed server certs created after 1/1/2016 and expiring after 1/1/2017.

### ISSUE THREAD

**Issue by jamincollins** [owncloud/client#4463]
I recently found that the desktop client accepted server certificates that browsers would not.  Digging into this, I found that the server certificates were SHA1 signed and the reason the browsers were not accepting them is that SHA1 has been scheduled for deprecation.  It would probably be a good idea for the desktop client to follow the same deprecation model.

For more information:
https://blogs.windows.com/msedgedev/2015/11/04/sha-1-deprecation-update/
https://cs.auscert.org.au/news/deprecation-of-sha1-certificates/
https://blog.qualys.com/ssllabs/2014/09/09/sha1-deprecation-what-you-need-to-know

**Comment by danimo** [comment]
While I generally agree I am not sure if it's the client's task to implement this policy (which is not a mandated standard by far, but just:

1. This implementation belongs with the Qt network stack (more general purpose), and it's difficult to do in the client itself (no direct access to the required information).
2. If you setup your own ownCloud instance, browsers will already reject old certificates, so your instance is no good anyway. (but I see the value of uniform behavior)

/cc @richmore for how to proceed in Qt, and @MTRichards on whether we should follow.

**Comment by guruz** [comment]
FYI @LukasReschke @peter-ha

**Comment by fmoc** [comment]
It is very unlikely for us to maintain such security policies. We rely on Qt for this. And we don't support ancient Qt versions any more since we depend on features from more recent ones, security policies should be updated more often, too.
