### ISSUE TITLE
[windows10][Steam][CS:GO] oC client lags game performance

### ISSUE THREAD

**Issue by felipeyonehara** [owncloud/client#4465]
Hi. When playing counter strike global offensive and owncloud daemon is running, the game lags about the time deamon refreshes the file updater, I presume. So everytime i launch my game I have to close owncloud daemon to play smoothly. I discovered this a couple months ago.

**Comment by guruz** [comment]
Interesting.. is this still the case when using 2.1.1?

**Comment by felipeyonehara** [comment]
Gonna try
Em 12/02/2016 01:53, "Markus Goetz" <notifications@github.com> escreveu:

**Comment by felipeyonehara** [comment]
Im using 2.1.0
Em 14/02/2016 00:40, "Felipe Yonehara" <felipeyonehara@gmail.com> escreveu:

**Comment by altintorr** [comment]
Hello, same problem... when new OC client is launched, I get so many lags :
![ping](https://cloud.githubusercontent.com/assets/17279264/13088497/c41f88ae-d4ec-11e5-8ba9-5ee796a0fd31.jpg)

OC client version : 2.1.0 build 5683 on Win10

**Comment by altintorr** [comment]
OC client version 2.1.1 seems to fix the problem for me.

**Comment by guruz** [comment]
:+1: 

Root cause is https://github.com/owncloud/client/issues/4294
