### ISSUE TITLE
[OS X] [Yosemite] Installer error that gets fixed by restarting system

### ISSUE THREAD

**Issue by sector7gp** [owncloud/client#4466]
related by post https://forum.owncloud.org/viewtopic.php?f=14&t=32871

The instaler did not list the hard drive to start the instalation. I had to restar the system twice. After that the installer recognised the drive.

**Comment by guruz** [comment]
Which version is that? Let's see it as a temporary glitch until more people report it

**Comment by sector7gp** [comment]
Ok, thanks!
ownCloud-2.1.0.2944.pkg

**Comment by Dianafg76** [comment]
@sector7gp could you try to reproduce with v 2.1.1?, thanks

**Comment by sector7gp** [comment]
Perfect! the installer changed, really?
maybe was something related with the issue #4424 ?

Thanks a lot great work!!! (server and clients)
