### ISSUE TITLE
[Linux] [Ubuntu] Client does not accept Let's Encrypt certificates

### ISSUE THREAD

**Issue by rloutrel** [owncloud/client#4467]
This issue is similar to: https://github.com/owncloud/client/issues/4062

Config: Ubuntu 15.04
Repos: deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_15.04/ /

I am sorry to bump this, but I am using the owncloud client 2.1.1 (freshly updated yesterday) and it seems that let's encrypt is not recognized as root certificate.
It was already failing on 2.1.0

Info about the certifcate:
https://www.sslshopper.com/ssl-checker.html?host=owncloud.systemsaviour.com#hostname=owncloud.loutrel.eu

It is accepted by Firefox and chromium (I do not have chrome, IE or safari). Therefore it seems to come from the desktop client and not the server configuration.

If required I can try to compile, install and test but definitely not fix it myself.

Optional question:
- Is there an easy way to remove a manually accepted certificate (for testing purpose)?
--> I assume that emptying 0\General\CaCertificates= variable in the config file will do what I want

**Comment by LukasReschke** [comment]
Setup problem on your side. https://www.ssllabs.com/ssltest/analyze.html?d=owncloud.loutrel.eu&latest 

Configure all intermediates. You're doing it wrong :tm:

**Comment by rloutrel** [comment]
Thanks for the quick feedback. 
I will investigate on the problem.

Can you please edit your answer to remove the website.

**Comment by danimo** [comment]
@rloutrel done.

**Comment by rloutrel** [comment]
@LukasReschke : Thank you for the link (I solved other problems and the site is A+)
@danimo : Thank you
"Indeed, I was doing it wrong" :tm:

**Comment by rloutrel** [comment]
For the record, you from the future, which came here, look into this direction to find a solution:
Based on this LE client: https://github.com/diafygi/letsencrypt-nosudo

= What I did (tolerated by the browsers) =
[x] I concatenated the keys (like described in [this](https://github.com/diafygi/letsencrypt-nosudo#how-to-use-the-signed-https-certificate) chapter)
[x] I adapted the configuration because I have an ubuntu server and the apache configuration is a bit different. In **/etc/apache2/sites-available/mysite.conf**:
```shell
SSLCertificateFile      /etc/ssl/certs/chained.pem
SSLCertificateKeyFile /etc/ssl/private/domain.key
```
= What I forgot (tolerated by the browsers, not by owncloud desktop client, and this is good so) =
[] provide the intermediate:
```shell
SSLCertificateChainFile /etc/apache2/ssl.crt/lets-encrypt-x1-cross-signed.pem
```

Do not forget:
1. To copy the 3 files at the correct places
2. For **security reasons**:
```shell
chmod 640 /etc/ssl/private/domain.key
chown root:ssl-cert /etc/ssl/private/domain.key
```
me from the pas

**Comment by manngo** [comment]
Thanks, rloutrel, for including your fix. It also solved my problem after I migrated from an older certificate to letsencrypt. It was find for the browser, but no the client (running on MacOS in my case).

In my case it was:

	SSLCertificateKeyFile	/…/privkey.pem

to get it working.
