### ISSUE TITLE
Document "Allow changeable upload chunk size in owncloud.cfg"

### ISSUE THREAD

**Issue by RealRancor** [owncloud/client#4468]
Hi,

https://owncloud.org/changelog/desktop/

lists "Allow changeable upload chunk size in owncloud.cfg" for 2.1.1. This is currently not documented how this can be configured in the owncloud.cfg

**Comment by RealRancor** [comment]
PR in https://github.com/owncloud/client/pull/4470

**Comment by guruz** [comment]
Closing in favor of PR
