### ISSUE TITLE
[Share with users, groups] already shared user is visible for a tenth of second

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4469]
### Steps to reproduce
1. Go to Desktop v2.2.0 with user1
2. Create a new folder
3. Share with ownCloud
4. Introduce on Share with users or groups... the user3
5. Click Enter
6. Introduce on Share with users or groups, very fast the same user (e.g. user3)

### Expected behaviour
Tell us what should happen

### Actual behaviour
You can see this warning
![screen shot 2016-02-12 at 10 59 50](https://cloud.githubusercontent.com/assets/12032058/13004050/51d1753a-d179-11e5-9fa2-36defa52fb5c.png)

LOG´s:
```
02-12 10:59:44:206 0x7f9e79c26cb0 OCC::OcsJob::finished: Reply to "POST"  QUrl( "https://xxxxxxxxxxxxx/ocs/v1.php/apps/files_sharing/api/v1/shares" )  (QPair("path","/oooooo"), QPair("shareType","0"), QPair("shareWith","user3")) has unexpected status code: 403 "{"ocs":{"meta":{"status":"failure","statuscode":403,"message":"Sharing 1570 failed, because this item is already shared with user3"},"data":[]}}"
02-12 10:59:44:207 0x7f9e79c26cb0 OCC::ShareUserGroupWidget::displayError: Error from server 403 "Sharing 1570 failed, because this item is already shared with user3"
02-12 10:59:50:056 0x7f9e79c26cb0 OCC::Folder::slotRunEtagJob: * Trying to check "https://xxxxxxxxx/remote.php/webdav/" for changes via ETag check. (time since last sync: 283 s)
´´´

### Server configuration

Desktop v ownCloud-2.2.0.3112-nightly20160211.pkg
Server 8.2.2

**Comment by rullzer** [comment]
Ah yes we should block the sharee input...

**Comment by rullzer** [comment]
PR in #4497

**Comment by Dianafg76** [comment]
I tested this issue and now is working OK.
Desktop v 2.2.0 (build 3148)
Server v {"installed":true,"maintenance":false,"version":"8.2.2.2","versionstring":"8.2.2","edition":"Enterprise"}
