### ISSUE TITLE
[Linux] EncFS file changes not detected by file watcher (works on OS X)

### ISSUE THREAD

**Issue by vomout** [owncloud/client#4471]
I'm trying using encfs on top of ownCloud to store files on a server that I don't trust enough to store my unpublished work on unencrypted. With the Mac client there seems to be no problem, but the Linux client of ownCloud does not seem to sync changes made in the encfs hierarchy until I change some other file (touch ~/ownCloud/foobar) on ownCloud, outside the encfs hierarchy, that triggers the sync of the encrypted files as well.

Linux version: Ubuntu 14.04
ownCloud version: 2.1.1.
encfs version: 1.7.4

**Comment by guruz** [comment]
@vomout So if you start the client in a terminal with ```--logfile -``` you don't see any message triggered when a file changes? Does the mtime or size of the encrypted file(s) change?

@danimo You did some work on Linux file watching which might be related? Was that merged?

**Comment by vomout** [comment]
@guruz No there's nothing in the log about the file having changed, only occasional communication with the server that are not timed at all with the file changes and keep repeating (below). That's all. If I just 'touch foobar' outside the encfs portion, there is immediately a flood of log entries.

02-15 12:13:01:347 0xec9460 * Trying to check "https://.../remote.php/webdav/" for changes via ETag check. (time since last sync: 293 s) 
02-15 12:13:01:347 0xec9460 Scheduling "https://.../remote.php/webdav/" to check remote ETag 
02-15 12:13:01:348 0xec9460 !!! OCC::RequestEtagJob created for "https://..." + "/" "OCC::Folder"

**Comment by guruz** [comment]
Could you guys check if the mtime of a changed file (the mtime of the encrypted version) changes when you modify the file?

**Comment by vomout** [comment]
The mtime does indeed change upon modification. Also worth noting is that the ownCloud client does not even detect completely new files within the encfs portion.

**Comment by guruz** [comment]
Is this with a lot of files/folders?
What if you ```touch``` something very high up in the hierarchy?
Can you ```cat /proc/sys/fs/inotify/max_user_watches``` and give us the value?
Then try to ```echo 65536 >  /proc/sys/fs/inotify/max_user_watches``` and restart the client..

**Comment by vomout** [comment]
I already tried setting max_user_watches high before even filing the bug report, but it did not help.

~$ find ownCloud|wc -l
7059
~$ cat /proc/sys/fs/inotify/max_user_watches 
500000

My current workaround is this crontab hack which indeed causes sync every hour:

13  11-20  *   *   1-5     date -Iminutes > ~/ownCloud/.linux_encfs_sync_hack

**Comment by vomout** [comment]
Just a thought: what kind of buffer length ownCloud uses for inotify? One way that encfs differs from other files on ownCloud is that the encrypted file names are relatively long. The maximum length of the entire absolute path (find|wc -L) of files in ~/ownCloud/.encfs is 314, with typical lengths around 200.

**Comment by vomout** [comment]
Interestingly, the client just started syncing a couple of days ago, presumably after some Ubuntu (14.04 LTS) update. Unfortunately I cannot tell whether it was an updated ownCLoud client, or some system component that seems to have fixed the problem--for now at least. I'll keep monitoring.

**Comment by dragotin** [comment]
@vomout maybe a client update to 2.2.1 ?

**Comment by guruz** [comment]
Great to hear

**Comment by vomout** [comment]
Yes, 2.2.1 is the current version installed.
