### ISSUE TITLE
[2.1.1 Windows] No .EXE meta data in Binary File

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#4473]
Looking in taskmanager i can not see any description to the oc client. Screen is from Windows 7 64 Bit:
https://www.dropbox.com/s/p3qxj543cjcj2xp/2016-02-14%2009_36_32-Eigenschaften%20von%20owncloud.exe.png?dl=0
It also says Lang is english, but Client is in German

**Comment by guruz** [comment]
@MegaV0lt thanks!

@danimo something related to the build scripts / signing?

**Comment by danimo** [comment]
@guruz Nope, not related to signing. It should work, as @jturcotte added support for it last year. However, the language will probably never be shown corectly, as the client's locale is adjusting dynamically.

**Comment by danimo** [comment]
Please try with nightly build https://download.owncloud.com/desktop/daily/testpilotcloud-2.2.0.5854-nightly20160215-setup.exe. Should show up soonish.

**Comment by danimo** [comment]
@MegaV0lt ping?

**Comment by MegaV0lt** [comment]
Still missing description. At least company name is shown now:
https://i.imgur.com/ywzeCYK.png

**Comment by guruz** [comment]
@MegaV0lt BTW, you can drag/drop pictures into the comment edit field on github, no need to upload them somewhere else.

**Comment by MegaV0lt** [comment]
i know, but sometimes i get a fatal error when i do this...
See: https://i.imgur.com/bu6NK6h.png

**Comment by danimo** [comment]
This is the properties view as of https://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5860-nightly20160217-setup.exe:

![image](https://cloud.githubusercontent.com/assets/1315934/13115957/4258167a-d59a-11e5-8063-e09728dc81a4.png)

**Comment by MegaV0lt** [comment]
Confirmed! Now shows the name in Taskmanager and propertys ;)

**Comment by guruz** [comment]
:+1:
