### ISSUE TITLE
X-OC-MTime gives wrong modification time

### ISSUE THREAD

**Issue by IvanUgrin** [owncloud/client#4475]
I am using OwnCloud client version 2.1.1(build 3107).
I have a problem with the mtime header. It gives 
1453295674 milliseconds = Sat Jan 17 1970 20:41:35 GMT+0100 (CET)
When the real date of the file modification in my local file system is January 20, 2016 at 14:14

**Comment by dragotin** [comment]
The "big number" is in seconds, not milliseconds. And if you put that number into a online unix time converter, you get exactly the time of your local fs.

**Comment by IvanUgrin** [comment]
Sorry for that! :) And thank you for the quick answer!
