### ISSUE TITLE
[OS X] Use https for Sparkle updates

### ISSUE THREAD

**Issue by frjo** [owncloud/client#4477]
I noticed that the ownCloud client on OS X doesn’t use https for updates via Sparkle. Hopefully this is an easy fix.

Sparkle documentations says “We strongly encourage you to use HTTPS URLs for the AppCast.”.

**Comment by danimo** [comment]
The update URL for the client is `https://updates.owncloud.com/client/` What tells you otherwise?

**Comment by frjo** [comment]
Bad logic in my test script.
