### ISSUE TITLE
New shares are not synchronized

### ISSUE THREAD

**Issue by BaSche** [owncloud/client#4479]
### Expected behaviour
When a new Folder is shared by someone else, the folder should be synchronized to all Clients.

### Actual behaviour
New Folders are not synchronized. There is a workaround to create a new file in the shared folders. That will trigger the synchronization but it is somehow clumsy.

### Steps to reproduce
1. Share a new folder with user A
2. Check synchronized folder at user B (it is not synched yet)
3. Create a new dummy-file at User B to trigger the synchronization
4. Delete the dummy-file
5. Now everything is synched properly

### Server configuration
Operating system: ?
Web server: ? 
Database: ?
PHP version: ?
ownCloud version: 7.0
Storage backend: ?

### Client configuration
Client version: 2.1.0 build 2683
Operating system: Windows 7
OS language: english
Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )
no entries 30 minutes before or after my test (see logs below)
2. Web server error log:

3. ownCloud log (data/owncloud.log):
`#=#=#=# Syncrun started 2016-02-16T11:14:59 until 2016-02-16T11:15:01 (1590 msec)
|0|Shared|INST_SYNC|Up|1455288424||0||0||0|0|1455551514|56c1f41fec94c|0248799651c080c4e7111|INST_NONE|
|0|Shared/Other|INST_SYNC|Up|1455617697||0||0||0|0|1455551514|56c1f41ff0191|0160609051c080c4e7111|INST_NONE|
10:14:59|1143|Shared/Other/test.txt|INST_NEW|Up|1455617697||0||4||201|0|0|||INST_NONE|
#=#=#=# Syncrun started 2016-02-16T11:15:04 until 2016-02-16T11:15:16 (12339 msec)
|0|Shared|INST_SYNC|Down|1455617697|56c2f6a4ea3e9|0|0248799651c080c4e7111|0||0|0|1455288424|||INST_NONE|
10:15:09|586|Shared/Other/test.txt|INST_RENAME|Up|1455617697|56c2f6a4d6786|0|0252425951c080c4e7111|4||201|0|0|||INST_NONE|
|0|Shared/new_share|INST_NEW|Down|1455123807|56bb6d60037e4|0|0245304851c080c4e7111|4||0|0|0|||INST_NONE|
|0|Shared/new_share/stuff|INST_NEW|Down|1452607636|56a8e2d9bf356|0|0245313051c080c4e7111|4||0|0|0|||INST_NONE|
|0|Shared/new_share/stuff|INST_NEW|Down|1452607636|56a8e2d9c68c8|0|0245332551c080c4e7111|4||0|0|0|||INST_NONE|
10:15:10|241|Shared/new_share/stuff/stuff to dev & test.docx|INST_NEW|Down|1452778912|56a8e2d5b8cd1|16334|0245338451c080c4e7111|4||0|0|0|||INST_NONE|
[...]
#=#=#=# Syncrun started 2016-02-16T11:15:22 until 2016-02-16T11:15:24 (1784 msec)
10:15:23|862|Shared/Other/test.txt|INST_REMOVE|Up|1455617697|56c2f6a4d6786|0|0252425951c080c4e7111|4||204|0|0|||INST_NONE|
#=#=#=# Syncrun started 2016-02-16T11:16:10 until 2016-02-16T11:16:11 (739 msec)
`

**Comment by guruz** [comment]
Sorry, Your server version (7.x) is too old. If you need support for that, please try the enterprise support.

Thanks.

PS: Client is at 2.1.1.
