### ISSUE TITLE
After deleting an user, previously shared data is still visible on the desktop

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4483]
### Steps to reproduce
1. Go to the desktop client with user1(server1) and user2(server2)
2. Create a new folder/file with user1(server1)
3. Share with ownCloud
4. Share the folder with user2(server2)
5. Go to the Server Web with Admin(server2)
6. Delete the user2(server2)
7. Go to the Desktop client

### Expected behaviour
If the user is not exit on the server, and you have create a new file/folder, it should  appears an error

### Actual behaviour
The user2(server2) are not sync (the icon is grey)
![screen shot 2016-02-18 at 08 35 13](https://cloud.githubusercontent.com/assets/12032058/13136566/e7ff49d8-d61a-11e5-8130-f6aa7f8cea88.png)
![screen shot 2016-02-17 at 18 17 05](https://cloud.githubusercontent.com/assets/12032058/13136584/1816ec5c-d61b-11e5-9b86-d9534e357a65.png)
But if you click on "Open folder ............"
The icons are green
![screen shot 2016-02-17 at 18 17 19](https://cloud.githubusercontent.com/assets/12032058/13136616/5c1ff2f4-d61b-11e5-95f6-4668ea889418.png)

NOTE: You can create a new folder on the user2(server2)
![screen shot 2016-02-18 at 08 44 42](https://cloud.githubusercontent.com/assets/12032058/13136670/e2d7e5e0-d61b-11e5-8ed2-3b62a6701a2d.png)
 

### Server configuration
Desktop v 2.1.1
Server v {"installed":true,"maintenance":false,"version":"9.0.0.11","versionstring":"9.0 beta 1","edition":""}

**Comment by Dianafg76** [comment]
@rullzer

**Comment by rperezb** [comment]
This bug doesn't apply
