### ISSUE TITLE
If you set to maintenance mode, on the Desktop It could say that the server is down for maintenance

### ISSUE THREAD

**Issue by Dianafg76** [owncloud/client#4485]
### Expected behaviour

It could say that the server is down for maintenance

![screen shot 2016-02-18 at 10 34 31](https://cloud.githubusercontent.com/assets/12032058/13139209/b7e28402-d62b-11e5-88eb-9b82fa6945d4.png)
### Actual behaviour

You can see the Admin user with grey icon
![screen shot 2016-02-18 at 10 33 25](https://cloud.githubusercontent.com/assets/12032058/13139100/27ab2db2-d62b-11e5-900d-5b575c2aef43.png)
### Steps to reproduce
1. Go to the Desktop with Admin
2. Go to the Server web with Admin
3. Set to maintenance mode
4. Go to the Desktop with Admin
5. Go to Seeting
6. Select the Admin user
### Server configuration

Desktop v 2.2.0

**Comment by SamuAlfageme** [comment]
Maintenance mode support is about to get introduced in the mobile apps; https://github.com/owncloud/ios/pull/821 and https://github.com/owncloud/android/issues/1722

iOS maintenance mode error message for uniformity: https://github.com/owncloud/ios/blob/1cbb881ba2e010e22fcaeda9a124a3fccb66c7ec/Owncloud%20iOs%20Client/SupportingFiles/Languages/en.lproj/Localizable.strings#L111

**Comment by SamuAlfageme** [comment]
Also regarding maintenance mode operation on the client: https://github.com/owncloud/client/issues/5738

**Comment by ckamm** [comment]
Pull request: https://github.com/owncloud/client/pull/5755
