### ISSUE TITLE
Desktop sync not working by itself - needs to be triggered

### ISSUE THREAD

**Issue by Memes11** [owncloud/client#4489]
### Configuration
- Owncloud server 8.2.2 (downloaded yesterday) 
- Ubuntu server 15.04
- nginx webserver / PHP-FPM / SSL activated
- a folder from a SMB share added as External storage by Admin, then shared between users by group policy
- different user, all on Win10 with desktop client

### Expected behaviour
User1 creates a file on his PC, in the Owncloud local folder, desktop client upload to Owncloud server, User2 desktop client downloads on User2 PC without action from User2

### Actual behaviour
User1 creates a file on his PC, desktop client upload to server, User2 desktop client DOES NOT downloads on User2 PC unless User2 does trigger the sync with an action in the Owncloud local folder (for instance open a file, create a file), then the sync is launched and sync properly.

### extra behaviour 
on some PC, after the initial trigger, it works, on some other it needs to be triggered each time (this behaviour not yet totally understood)

**Comment by guruz** [comment]
Which ownCloud client version?
Does it work if the external storage is not a SMB share?

**Comment by Memes11** [comment]
Owncloud client version : 2.1.0 build 5683

Add a local folder as external storage, share it with all users, the folder is synced to all user. from User1PC, create a file in this folder, synced properly to server, but again, not to User2 PC (at least not until he does some changes in the folder on his PC) => so, same behaviour

**Comment by Memes11** [comment]
one more test, from the web interface, I created a blank txt file. it took about a minute or so to sync with my desktop folder. but User2 still has nothing on his PC.

**Comment by guruz** [comment]
You could use occ to scan for changes https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/occ_command.html#file-operations

You can use https://doc.owncloud.org/server/9.1/admin_manual/enterprise_external_storage/windows-network-drive_configuration.html#smb-notifications to avoid this.
