### ISSUE TITLE
Differentiate between zero KB and pending file size in folder overview

### ISSUE THREAD

**Issue by MorrisJobke** [owncloud/client#4491]
* having a folder that has the file size not determined yet (in Web UI this is shown as pending)
* the PROPFIND returns a quota-used-bytes of 0 for this folder - `<d:quota-used-bytes>0</d:quota-used-bytes>`
* the PROPFIND returns a size of -1 for this folder - `<oc:size>-1</oc:size>`
* the client then also shows 0 kB instead pending (this is also the case for the folder overview in the client window and not only in the folder setup):

![bildschirmfoto 2016-02-19 um 16 52 55](https://cloud.githubusercontent.com/assets/245432/13180652/9f4d7e84-d729-11e5-9ff7-f5ad028969e4.png)

I tested this on v8.2.2 and master of the server.

Was noticed while debugging 00004617.

I add bug and enhancement label, because I'm unsure - this is up to the client devs I guess.

cc @MTRichards

**Comment by MorrisJobke** [comment]
Ref https://github.com/owncloud/core/issues/22532

**Comment by MorrisJobke** [comment]
I tested this with the 2.1.1 client on OS X and Windows 10.

**Comment by ogoffart** [comment]
In 2.2, we will use oc:size (https://github.com/owncloud/client/issues/4459)
But i guess now we will print "-1 B".
So maybe best not showing anything in this case,  or?

**Comment by ogoffart** [comment]
How can y reproduce?

**Comment by MorrisJobke** [comment]
> How can y reproduce?

Set it in the database for a folder and some subfolders to -1 and don't browse the web interface.

**Comment by ogoffart** [comment]
Now it won't show any size if the server report negative sizes

**Comment by ckamm** [comment]
I've verified it by setting a folder size to -1 in the server database. It shows up without a size in the client then.
