### ISSUE TITLE
[Linux]  [2.1.0] [Qt 5.5.1] Segfault on startup in QtDBUS

### ISSUE THREAD

**Issue by johncant** [owncloud/client#4495]
### Expected behaviour

_Please forgive the pseudo-cucumber!_
When I start the Owncloud client
And I add many small files # ~40Gb of tiny files
And I pause the transfer
And I exit the Owncloud desktop client
And I start the Owncloud desktop client
Then I should not see "Seg"
### Actual behaviour

Owncloud pauses for several minutes, then segfaults without ever opening a GUI window.
### Steps to reproduce
1. Transfer a large number of files
2. Pause the Owncloud desktop client
3. Exit the Owncloud desktop client
4. Try to start it again from the command line
### Server configuration

Operating system: Raspbian Wheezy

Web server: Apache

Database: MySQL

PHP version:

``` bash
$ php -v
PHP 5.4.39-0+deb7u1 (cli) (built: Mar 22 2015 16:53:32) 
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
```

ownCloud version: 8.0.2

Storage backend: Local
### Client configuration

Client version:

``` bash
owncloud --version
ownCloud version 2.1.0
Using Qt 5.5.1
```

Operating system: Arch Linux

OS language: `en_GB.UTF-8`

Installation path of client: /usr/bin/owncloud
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   (On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
   (See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )
   https://gist.github.com/johncant/a51026f49132a2009257
2. Web server error log:
   https://gist.github.com/johncant/83ac6bf00119c4d69daf
3. ownCloud log (data/owncloud.log):
   https://gist.github.com/johncant/aed735742224274278ec
4. gdb

```
$ gdb /usr/bin/owncloud        
GNU gdb (GDB) 7.10.1
Copyright (C) 2015 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/owncloud...(no debugging symbols found)...done.
(gdb) 
(gdb) c
The program is not being run.
(gdb) run
Starting program: /usr/bin/owncloud 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7fffe5a0d700 (LWP 23779)]
[New Thread 0x7fffdcad3700 (LWP 23780)]


[New Thread 0x7fffd6b50700 (LWP 23876)]

Program received signal SIGPIPE, Broken pipe.
0x00007ffff54a61cd in write () from /usr/lib/libc.so.6
(gdb) 
(gdb) 
(gdb) bt
#0  0x00007ffff54a61cd in write () from /usr/lib/libc.so.6
#1  0x00007fffe6ed5928 in ?? () from /usr/lib/libICE.so.6
#2  0x00007fffe6ed9fe8 in _IceWrite () from /usr/lib/libICE.so.6
#3  0x00007fffe6eda0c4 in IceFlush () from /usr/lib/libICE.so.6
#4  0x00007fffe7569301 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#5  0x00007fffe756958a in ?? () from /usr/lib/libQt5XcbQpa.so.5
#6  0x00007fffe756a011 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#7  0x00007fffe756abb4 in ?? () from /usr/lib/libQt5XcbQpa.so.5
#8  0x00007fffe70eec38 in _SmcProcessMessage () from /usr/lib/libSM.so.6
#9  0x00007fffe6ede46c in IceProcessMessages () from /usr/lib/libICE.so.6
#10 0x00007ffff6b7431a in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#11 0x00007ffff6bf421e in QSocketNotifier::activated(int, QSocketNotifier::QPrivateSignal) () from /usr/lib/libQt5Core.so.5
#12 0x00007ffff6b80e3b in QSocketNotifier::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#13 0x00007ffff758c9ac in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#14 0x00007ffff7591e86 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#15 0x00007ffff6b45bab in QCoreApplication::notifyInternal(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#16 0x00007ffff6b9ca1d in ?? () from /usr/lib/libQt5Core.so.5
#17 0x00007ffff2021dc7 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#18 0x00007ffff2022020 in ?? () from /usr/lib/libglib-2.0.so.0
#19 0x00007ffff20220cc in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#20 0x00007ffff6b9c54f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#21 0x00007ffff6b4357a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#22 0x00007ffff6b4b53c in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#23 0x00000000004671a0 in main ()
(gdb)
```
### Related issues

https://github.com/owncloud/core/issues/22036 - Though the client still shouldn't crash.

**Comment by guruz** [comment]
I'm not sure the SIGPIPE is a problem http://ahlamnote.blogspot.de/2006/12/gdb-ignore-sigpipe.html

Can you try with 2.1.1?

Can you try ```thread apply all backtrace``` to get a full backtrace?

**Comment by johncant** [comment]
EDIT - just realised that I'm still on 2.1.0. Will generate a backtrace for 2.1.1 and/or master tomorrow. Here it is anyway, for 2.1.0. I've also tried changing the server config to lift the size limit to 2Gb, but haven't verified this new limit. Here's an updated paste which should hopefully contain the actual SIGSEGV in v2.1.0:

https://gist.github.com/johncant/b26022474e9d3fcaab2c

**Comment by johncant** [comment]
Now with v2.1.1 . Took 2 attempts to crash it with SIGSEGV this time:

https://gist.github.com/johncant/f4c04c6a9f2349ce2caf

**Comment by guruz** [comment]
Is there an upstream Qt bug for this QtDBUS crash?

**Comment by johncant** [comment]
Not a clue - sorry, I don't plan on getting involved too heavily with Qt or Owncloud development at the moment or going too far down this particular rabbit hole, but I'm happy to help debug this particular case. Thankyou for your time.

**Comment by guruz** [comment]
Does this still happen?

**Comment by hodyroff** [comment]
No info provided closing. Please comment if still existing in 2.3.
