### ISSUE TITLE
Feature Request: Adding support for placeholder files?

### ISSUE THREAD

**Issue by surashu** [owncloud/client#4499]
### Expected behaviour
Instead of syncing the actual files, there will be a "placeholder" in its place which just works as a pointer for the file on the server. Kinda like Windows 8's OneDrive implementation. This can be an optional feature so that people who don't want it aren't forced to use it.

### Actual behaviour
Currently ownCloud downloads the files itself.

### Client configuration
Client version: 8.2.2

Operating system: Windows 10 Pro Build 10586.104

**Comment by guruz** [comment]
Thanks. Closing this as part of investigation of https://github.com/owncloud/client/issues/4341
@dragotin @jturcotte

**Comment by surashu** [comment]
Thanks! Didn't think it can also be called Virtual Filesystem.
