### ISSUE TITLE
Already synced file still shows up in »Not synchronized« section of sync protocol

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#4504]
### Expected behaviour

As soon as a previously »Not synchronized« file gets synchronized and shows up in the »Sync protocol« tab, it should be removed from the »Not synchronized« list. Because that information is outdated and this file is now synced.
### Actual behaviour

An already synced file still shows up in the »Not synchronized« list and I am confused as to what the state is now.

**Comment by ckamm** [comment]
@jancborchardt Do you have a way of reproducing the problem? I've tried and then read the code for master: The 'Not synchronized' list is wiped every time a sync starts.

**Comment by jancborchardt** [comment]
That’s strange. Was it fixed recently @guruz @dragotin? I’m on 2.1.1

**Comment by dragotin** [comment]
No, not they I would know. Actually, the Not-Synchronized list is wiped before the sync starts since ages.

**Comment by dragotin** [comment]
@jancborchardt can you still reproduce your initial problem?

**Comment by jancborchardt** [comment]
I can still reproduce though. It seems the list is only wiped every regular 5-minute-sync run? Not when a file had an error syncing and then a few seconds later was synced?

**Comment by jancborchardt** [comment]
Screenshots from just the other day:

![capture du 2016-03-25 15-23-43](https://cloud.githubusercontent.com/assets/925062/14168607/82385f7a-f723-11e5-9135-29ddebf10b00.png)
Look at the …134824.jpg for example – showed up as synced above, but when switching to the other tab, it still shows as not synced:
![capture du 2016-03-25 15-23-55](https://cloud.githubusercontent.com/assets/925062/14168608/82396e74-f723-11e5-9e86-f0e3c136a7be.png)

**Comment by guruz** [comment]
@jancborchardt Can you try with a recent nightly?
@dragotin has changed a lot in this area.

**Comment by jancborchardt** [comment]
Just occured again.

**Comment by jancborchardt** [comment]
That is, with 2.1.1git – probably not a nightly? But I’m not using nightlies in production. ;D

**Comment by dragotin** [comment]
yes, 2.1.1git is a version pre 2.1.1 release. Please install 2.2.0 beta1.

**Comment by guruz** [comment]
Please comment if this really happens still
