### ISSUE TITLE
[2.1.0] Client File Sync Problem - Wrong File Size

### ISSUE THREAD

**Issue by catborise** [owncloud/client#4505]
### Expected behaviour
Sync a file. Same file size  with server 

### Actual behaviour
Whenever sync a file with owncloud Windows Client there are some problems. 
First one is while syncing file size is different with orjinal file.
For example while i sending 200MB file, client shows it as 600MB while syncing.
Second one ise after completion, when i check the file from browser. Browser shows that file as 5MB. No matter how big it is. Always file's size is 5MB

### Steps to reproduce
1. Copy a file to owncloud sync folder
2. Check sync operation
3. Check browser 

### Server configuration
Operating system: RHEL7.2

Web server: nginx 1.8

Database: Mariadb + Galera

PHP version: 7.0.3

ownCloud version: 8.2.2.2.

Storage backend: Gluster

### Client configuration
Client version: 2.1.0

Operating system: Win 8.1

OS language: TR/EN

Installation path of client: default

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log: no error

3. ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
What do you have in the server's ```owncloud.log```?
Is there no error shown in any tab in the client UI?

**Comment by guruz** [comment]
Can you also try 2.1.1 please?

**Comment by catborise** [comment]
there isn't any change;

I installed 2.1.1 tried again with a file:c7200-advipservicesk9-mz.122-33.SRE6.image : 66MB
Result;
On server, the file size is 5MB!
while syncing client shows file size 639MB (but actually 66MB)

and logs are like 
`{"reqId":"sBt7GAPAV1z\/c3n4aF6t","remoteAddr":"10.0.1.101","app":"PHP","message":"filemtime(): stat failed for \/media\/owncloud\/data\/muhammet.sag\/cache\/c7200-advipservicesk9-mz.122-33.SRE6.image-chunking-79700946-5 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#156","level":3,"time":"2016-02-24T13:58:10+02:00"}
{"reqId":"sBt7GAPAV1z\/c3n4aF6t","remoteAddr":"10.0.1.101","app":"PHP","message":"filemtime(): stat failed for \/media\/owncloud\/data\/muhammet.sag\/cache\/c7200-advipservicesk9-mz.122-33.SRE6.image-chunking-79700946-1 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#156","level":3,"time":"2016-02-24T13:58:10+02:00"}
{"reqId":"sBt7GAPAV1z\/c3n4aF6t","remoteAddr":"10.0.1.101","app":"PHP","message":"filemtime(): stat failed for \/media\/owncloud\/data\/muhammet.sag\/cache\/c7200-advipservicesk9-mz.122-33.SRE6.image-chunking-79700946-3 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#156","level":3,"time":"2016-02-24T13:58:10+02:00"}
{"reqId":"sBt7GAPAV1z\/c3n4aF6t","remoteAddr":"10.0.1.101","app":"PHP","message":"filemtime(): stat failed for \/media\/owncloud\/data\/muhammet.sag\/cache\/c7200-advipservicesk9-mz.122-33.SRE6.image-chunking-79700946-8 at \/var\/www\/owncloud\/lib\/private\/files\/storage\/local.php#156","level":3,"time":"2016-02-24T13:58:10+02:00"}
{"reqId":"jdcVpuGvjaY\/xAqKIMDY","remoteAddr":"10.0.1.101","app":"PHP","message":"Array to string conversion at \/var\/www\/owncloud\/lib\/private\/template\/functions.php#36","level":3,"time":"2016-02-24T13:58:56+02:00"}
`

**Comment by guruz** [comment]
```Permission denied``` :)
This is a local setup problem. Please try to check your setup (maybe check the doc).

Further support see
https://owncloud.org/support/

**Comment by catborise** [comment]
while syncing client shows file size wrong. a screenshot link: [http://i.hizliresim.com/rMm2gz.jpg](url)

i am copying a file which size is 124MB but client reads that value as 5242880KB. error gives like below.
i think real problem logs;
`{"reqId":"itP1IR7H0sE6YeFjKOvn","remoteAddr":"10.0.1.101","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 5242880 got 0\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(101): OC\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #36)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(115): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #36)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('Belgeler-090920...', Resource id #36)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('m\\\/Belgeler-0909...', Resource id #36, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/media\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/media\\\/owncloud...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":361}","level":4,"time":"2016-02-24T15:11:54+02:00"}
{"reqId":"7WwKveSrzUl1dVsV8pjN","remoteAddr":"10.0.1.101","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 expected filesize 5242880 got 1349873\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\BadRequest\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php(101): OC\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #36)\\n#1 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/directory.php(115): OC\\\\Connector\\\\Sabre\\\\File->put(Resource id #36)\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1053): OC\\\\Connector\\\\Sabre\\\\Directory->createFile('Belgeler-090920...', Resource id #36)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(513): Sabre\\\\DAV\\\\Server->createFile('m\\\/Belgeler-0909...', Resource id #36, NULL)\\n#4 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(469): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(254): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#8 \\\/media\\\/owncloud\\\/apps\\\/files\\\/appinfo\\\/remote.php(56): Sabre\\\\DAV\\\\Server->exec()\\n#9 \\\/var\\\/www\\\/owncloud\\\/remote.php(137): require_once('\\\/media\\\/owncloud...')\\n#10 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/connector\\\/sabre\\\/file.php\",\"Line\":361}","level":4,"time":"2016-02-24T15:11:54+02:00"}
`
