### ISSUE TITLE
win10 client wont create "folderWith:doubledot"

### ISSUE THREAD

**Issue by homelessgamer** [owncloud/client#4507]
i create an folder "name:withdoubledot" in the synched owncloud folder on linux. owncloud synches the created folder on my win10 pc. my win pc will show the blue "synchronizing" symbol. but the folder wont be created. 
a friend created such a folder too, using his mac. same here. the ios client can display doubledot folders.

### Steps to reproduce
1. create a folder using a doubledot ":" within foldername on linux
2. pray it will be synched to win10 client
3. it wont. every normal folder gets synched

### Server configuration
Operating system: ubuntu 14.04

Web server: apache2

Database: mysql

PHP version: PHP 5.5.9-1ubuntu4.14

ownCloud version: 8.1.5 (stable) 

Storage backend: ? hdd of server ?

### Client configuration of my win10 client
Client version: Version 2.1.0 (build 5683)

Operating system: Windows 10

OS language: de German

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs
`
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
02-24 17:22:22:813 0x4c47640 OCC::Application::setupLogging: "################## ownCloud de_DE (de_DE) 2.1.0 (build 5683)"
02-24 17:22:22:813 0x4c47640 OCC::Application::slotParseMessage: Running for 10216.3 sec
02-24 17:22:22:813 0x4c47640 OCC::ownCloudGui::slotShowSettings: void OCC::ownCloudGui::slotShowSettings()
02-24 17:22:31:058 0x4c47640 OCC::SocketApi::slotNewConnection: SocketApi:  New connection QLocalSocket(0x7b35c78)
02-24 17:22:31:058 0x4c47640 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "REGISTER_PATH:C:\Users\peter\ownCloud\"
02-24 17:22:31:058 0x4c47640 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Via ownCloud teilen"
02-24 17:22:31:108 0x4c47640 OCC::SocketApi::onLostConnection: SocketApi:  Lost connection  QLocalSocket(0x7b35c78)`

**Comment by dragotin** [comment]
https://doc.owncloud.org/desktop/2.1/architecture.html#ignored-files gives you an idea why. Files with colons can not live on windows.
