### ISSUE TITLE
Installer doesn't work on Windows Vista

### ISSUE THREAD

**Issue by mcorteel** [owncloud/client#4510]
### Expected behaviour
The Windows installer should be executed.

### Actual behaviour
It does not do anything.

### Steps to reproduce
1. Download the current installer on Windows Vista
2. Execute

### Client configuration
Client version: tested 2.0.0, 2.1.0 and 2.1.1

Operating system: Windows Vista

### Notes
Sorry, but I can't give you much more information as it happened on a computer which is now inaccessible... But I can tell you that the installer for 1.7.0 and the auto-upgrade worked (which did the trick).

**Comment by guruz** [comment]
Thanks. Let's reopen this if there is more info.
The auto update is also just running the installer as far as i know..

FYI @danimo maybe there is a big difference between 1.7.0 and later versions..
