### ISSUE TITLE
[Linux] Justify icon width in setting window

### ISSUE THREAD

**Issue by guoyunhe** [owncloud/client#4516]
Just think maybe justified icon width will be better. Every icon take up 25% of window width. Currently it seems not well organized.
![spectacle h20673](https://cloud.githubusercontent.com/assets/5836790/13348451/41a52626-dc7c-11e5-958b-6e5d1ee33ce3.png)

**Comment by jancborchardt** [comment]
The other icons (Activity, Settings, Network) should be at least as wide as they are high. Otherwise it looks a bit strange like now.

@guruz is that possible?
