### ISSUE TITLE
[2.1.1] Large file upload error

### ISSUE THREAD

**Issue by EpeR1** [owncloud/client#4517]
### Expected behaviour

Desktop Client (both Linux and Windows) replies internal server error when large (>15MB) file is begins to syncing. 
Then the client blacklists for 2-8 minutes, and at the next try is successful, without errors.
The error is when client uploads the first 3 chunk of the file.
If the first two chunk is over 15Mb the error is occours.
If the Internet connection is slower than 10Mbit/s the error disappears.
I tried at 1Gbit/s connection to the server, the error is occurred immediately.

Is there a configuration option to slow the network speed for the first chunk or to reduce chunks size?

I think it is related to #51747 Apache2 Bug. 
(https://bz.apache.org/bugzilla/show_bug.cgi?id=51747)
### Server configuration

OwnCloud server version: 8.2.2
Owncloud Desktop client: 2.1.1 (Compiled from eeec89 Git revision)

OS: Debian 8.2
Server: HP Proliant DL360, 24GB RAM, 4TB hdd.
Apache 2.4 (2.4.10-10+deb8u4)
PHP: 5.6 (5.6.17+dfsg-0+deb8u1)
Fastcgi: 1:2.3   (1:2.3.9-1+b1)
SuExec:  2.4.10-10+deb8u4

Note: PHP is running under apache's php-fcgid module, using by SuExec!

Some configuration setting from the apache config:
<IfModule mod_fcgid.c>
    FcgidProcessLifeTime 5400
    FcgidMaxRequestLen  1207959552
    FcgidMaxRequestInMem 50331648 
    FcgidIOTimeout 720  
    FcgidBusyTimeout 720
    FcgidIdleTimeout 300  
</IfModule>
### Logs

Some from Apache errorlog:
[Fri Feb 26 20:31:42.851453 2016] [fcgid:info] [pid 18828] (32)Broken pipe: [client 10.10.1.8:58398] mod_fcgid: error writing data to FastCGI server
[Fri Feb 26 20:48:13.397807 2016] [fcgid:info] [pid 1566] (32)Broken pipe: [client 10.10.1.8:58818] mod_fcgid: error writing data to FastCGI server
[Fri Feb 26 20:48:13.437728 2016] [fcgid:info] [pid 3643] (32)Broken pipe: [client 10.10.1.8:58817] mod_fcgid: error writing data to FastCGI server

Some Apache accesslog:
10.10.1.8 - - [26/Feb/2016:20:31:42 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 3657 "-" "Mozilla/5.0 (Linux) mirall/2.1.1"
10.10.1.8 - - [26/Feb/2016:20:31:42 +0100] "PUT /remote.php/webdav/New%20folder/random512.iso-chunking-1160651913-103-2 HTTP/1.1" 500 3464 "-" "Mozilla/5.0 (Linux) mirall/2.1.1"
10.10.1.8 - - [26/Feb/2016:20:31:42 +0100] "PUT /remote.php/webdav/New%20folder/random512.iso-chunking-1160651913-103-0 HTTP/1.1" 201 732 "-" "Mozilla/5.0 (Linux) mirall/2.1.1" 
10.10.1.8 - - [26/Feb/2016:20:31:42 +0100] "PUT /remote.php/webdav/New%20folder/random512.iso-chunking-1160651913-103-1 HTTP/1.1" 201 3292 "-" "Mozilla/5.0 (Linux) mirall/2.1.1"
10.10.1.8 - - [26/Feb/2016:20:31:45 +0100] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 6217 "-" "Mozilla/5.0 (Linux) mirall/2.1.1"

More Log:
https://gist.github.com/EpeR1/93a1bb461bb1a13911d9

**Comment by guruz** [comment]
@icewind1991 @PVince81 Is ```Exception: {"Message":"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\"files\\\/0c1ed9e08db731030``` a known server bug?

@EpeR1 I'd think it's besser you try another setup than ```mod_fcgid``` if you think this is the cause..

**Comment by EpeR1** [comment]
I forgot to write: The database is: MariaDB 10.0 ( 10.0.23+maria-1~jessie)
The random512.iso was generated by "dd if=/dev/urandom of=random512.iso bs=1M count=512"
If I trying from home (my upload speed is ~1 Mbit/sec) I can upload 4GB randomfile without any error.
There are some other small websites hosted on this server, so mod_suexec separate them from each other, then mod_fcgid ensures the php running opportunity.

**Comment by guruz** [comment]
@EpeR1 Does the ```An exception occurred while executing ``` corelate with the upload? (appear at same time for each time you upload)

**Comment by EpeR1** [comment]
If I copied these files: rand12M_0.iso, rand12M_1.iso, rand12M_2.iso, rand12M_3.iso, rand12M_4.iso, rand12M_5.iso to the sync folder, the sync was good, without any error.

If I copied rand24M_0.iso ... rand24M_5.iso to the sync folder the rand24M_0.iso made error, then _1.iso ... _5.iso synced without error, and the _0.iso also was snychronized correctly for the second try.

If I copied rand128M_0.iso ... rand128M_5.iso to the sync folder the rand128M_0.iso, rand128M_1.iso, rand128M_2.iso made errors, then _3.iso, _4.iso, _5.iso synced without error, and  _0.iso, _1.iso, _2.iso were snychronized correctly for the second try, and the same were with rand512M... iso-s.

BUT

If I close totally the sync app first, then I perform copying, all  24M.iso-s will be synced correctly at first time, and 128M.iso-s made less errors.

If I tried when upload speed was ~1Mbit/s, all 12M.iso, 24M.iso, 128M.iso were synched correctly, just 512M.iso made errors.

At the web interface I can upload any files from _12M.is to _512M.iso correctly, without error.
(My php.ini upload limit is 512MB)


Max_Filesize option ?

It will be a very good option, if I could set the maximal file size in the owncloud server config for globally, because:
- When I try upload a file which is greater than 4GB, the ClamAV will scan only the first 4GB of the file, (the maximal size limit is 4GB for ClamAV on 32/64bit systems (yet)).
- When I tried upload a 4GB file from Machine1, then couldn't download on Machine2 by the sync app, moreover I couldn't download or delete from the OC own web interface!  
- So I could limit the global filesize, because Windows Internet explorer, or any 32bit systems can handle only 2GB correctly, while in this moment there aren't any option to limit the sync app filesize below 2 or 4GB.

Like:
https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=uploading%20big%20files#uploading-big-files-512mb



PUT or PUSH ?
I recognized, the sync app is using PUT (http) method instead of POST. 
I think using POST method would be better, because POST method is correctly implemented (and tested for many years) in Apache's mod_fcgid/php_cgi module, while these errors with PUT are pointing a memory usage error in apache's fcgi module.
Like:
https://doc.owncloud.org/server/8.2/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=uploading%20big%20files#apache-with-mod-fcgid

**Comment by Akuukis** [comment]
I think I have the same problem although for me it looks that file never gets synced.

Little files do sync good.
Big files don't sync with errors like here: https://gist.github.com/Akuukis/b6d02b94b2e6f9250e71
It seems that borderline between 'small'and 'big' for me is around 7MB, because the smallest file I can find and don't sync is 7 517 073 bytes.

I use Ubuntu 14.04 with owncloud client 2.1.0. Updated to 2.1.1. but with no success.

**Comment by guruz** [comment]
@Akuukis From your log: ```server replied: Internal Server Error```
You are using owncube which is known for having odd configurations sometimes, you should contact the support there.

**Comment by Akuukis** [comment]
@guruz thank you. Sorry, since last comment I contacted them and they changed something at their end and this error was solved.

**Comment by guruz** [comment]
Great to hear :)
