### ISSUE TITLE
PHP Timeout when in Discovery Phase for New Client

### ISSUE THREAD

**Issue by MTRichards** [owncloud/client#4520]
### Expected behaviour
A new sync client is added to my existing account. When I set it up, all files should just sync automatically to the desktop.

### Actual behaviour
My client goes into discovery, then times out after an hour of discovery and no files are downloaded. Then, it starts again...and again. In the end, nothing syncs.

### Steps to reproduce
1. Start with an existing account on ownCloud (52k files, 6100 directories, 62G of data)
2. Install a desktop client on a new laptop; log in and sync everything during the install
3. watch the server discovery for a while, then timeout and start again

### Server configuration
Operating system: opensuse

Web server: apache

Database: mysql

PHP version: 7

ownCloud version: 8.2.2

Storage backend: local attached

### Client configuration
Client version: 2.1.1

Operating system: Win 7

OS language: English

Installation path of client: default

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

**Comment by MTRichards** [comment]
Update: We were able to get it to work within the php timeout (which was extended to 60 min) by selectively removing about 30% of the discovery folders, then the remaining 70% synced, then went back and added these folders back again.

**Comment by danimo** [comment]
@MTRichards Just to clarify: Is this a regression?

**Comment by MTRichards** [comment]
Um. I don't recall, to be honest. I would think that perhaps we didn't test quite such a large set of files? 
Also, to be fair - I witnessed this as an observer to a new client hitting S3 (rex). Making sure the issue gets filed.

**Comment by dragotin** [comment]
On discovery we do one PROPFIND request per directory. This would mean that a PROPFIND of a single directory takes more than 60 minutes. That is mysterious.

It would be good to get server log files (access_log and also a check of owncloud.log). Maybe these happens because the tables are locked for some reasons and we accumulate timeouts on the server or so? Just a wild guess....
@PVince81 ideas?

**Comment by PVince81** [comment]
Currently our PHP transactional locking doesn't wait.
So if it takes that long, maybe it's a DB-level lock.

The logs might help to find out.

**Comment by danimo** [comment]
@PVince81 what am i looking for. there are no 500s in response to PROPFINDs.
@MTRichards can you tell me round about when you tested this?
