### ISSUE TITLE
[Windows] Not recognising changes to files that have occured

### ISSUE THREAD

**Issue by ctg-owncloud** [owncloud/client#4522]
### Expected behaviour
Files that have been changed on the server by DESKTOP A, should be updated on the Desktop client of other devices - such as DESKTOP B

### Actual behaviour
The changed files will be synchronised to the server from DESKTOP A, but will not be updated on DESKTOP B.  If you change a file within the directory on DESKTOP B, the files will then be synchronised.

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system: 

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend:

### Client configuration
Client version:  2.1.1

Operating system: Windows 7

OS language: English

Installation path of client: Default installation

### Logs

(WILL NEED TO PROVIDE WHEN I CAN LOGIN TO REMOTE USER) - Chris G 01/03/2016

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by felixboehm** [comment]
same user using two desktop clients on different machines?
or two user accounts and shared files?

Both cases work for me very well, can you please provide details on how to reproduce this.

**Comment by ctg-owncloud** [comment]
Different user on 2 different machines - Machines are both Windows 7

Files are stored on a Windows 2012 file server with Active Directory integration

**Comment by felixboehm** [comment]
Shared files in ownCloud or do they have common access on a smb / cifs share?
I assume this is not client related, as the server is probably not discovering the changes as you expect it.
So the client just shows you what the server is telling.

**Comment by ctg-owncloud** [comment]
They have common access on a smb share

The server is recognising the changes, as when we go to the web GUI the files from DESKTOP A are on the server

DESKTOP B is not synchronising the files from the server

If we create a new file on DESKTOP B, the files then synchronise

**Comment by ctg-owncloud** [comment]
How often does DESKTOP B check for changed files?

As per a post on forum.owncloud.org we added the following

"I have solved my problem by rescanning the OC filecache periodically, using a cronjob, by running this command:
CODE: SELECT ALL
php /var/www/localhost/htdocs/cloud/console.php files:scan admin

This way the DB table is in sync with the actual files, and this is noticed by the client too. There is some delay, but that doesn't really bother me."

**Comment by guruz** [comment]
Which server version?
I believe there have been fixes in recent (possibly unreleased) server versions.

CC @icewind1991

**Comment by felixboehm** [comment]
yes, several fixes in 8.2.3.

**Comment by ctg-owncloud** [comment]
Hi there, does this fixes in the server version relate to the issues we are facing?

**Comment by ctg-owncloud** [comment]
The server version we are running is

ownCloud 8.2.2 (stable)

**Comment by ctg-owncloud** [comment]
Where do I download version 8.2.3, is it stable enough to install in a production environment?

**Comment by ctg-owncloud** [comment]
[Uploading owncloud.txt…]()

**Comment by ctg-owncloud** [comment]
The settings were set to Authentication\Session credentials

For a test, i have changed them to Username/Password - i am waiting for feedback from the End User

![image](https://cloud.githubusercontent.com/assets/17565258/13450052/7103bcfe-e085-11e5-8b7c-aacc30376699.png)

**Comment by felixboehm** [comment]
8.2.3 is not yet released. Stay tuned. It might need more research on your system to find the exact reasons. The smb integration is doing scans of changes for the users and this needs proper configuration related to the exact use case.

**Comment by ctg-owncloud** [comment]
Thanks for this, can you please provide me guidance of the proper configuration required to suit what we want to achieve?

**Comment by ctg-owncloud** [comment]
Hi there, we are still having this problem with this installation.  What information is required to assist us.

**Comment by guruz** [comment]
@ctg-owncloud I suggest to try the commercial/enterprise support -> https://owncloud.org/support/ or https://owncloud.help/

**Comment by ctg-owncloud** [comment]
Hi there, I have attempted to contact commercial/enterprise support, but have not received any feedback thus far.  I really need assistance with this installation, and would appreciate further assistance in this matter.  Has anybody else had this issue with SMB shares and this release of ownCloud.  Please help.

**Comment by hodyroff** [comment]
We are in contact. Please close.
