### ISSUE TITLE
Deal with old, unsupported server versions

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#4523]
Currently one can try to use the client with arbitrary old and unsupported server versions (see https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule). 

Since we don't even notify users about potential problems, they assume everything works. Then, when something breaks, the assumption is that the client has a bug.

Instead, we should be very upfront about potential problems (and dangers! it's untested!) of using a new client with an outdated server. There should be a persistent warning on such accounts. We should initially pause accounts like that too. Then users have to explicitly enable them and are aware of the potential problems.

**Comment by dragotin** [comment]
Lets create a red warning pane on the activity view, pause the account and show a tray notification.

@ckamm I can do the one in the activity view along with my work on the notification stuff.

**Comment by ckamm** [comment]
@dragotin Ok. As long as users will actually see the message before they can reactivate their folders that's fine with me.

**Comment by ckamm** [comment]
Pull request: #4531

**Comment by guruz** [comment]
Merged..

**Comment by marcushall42** [comment]
Why is it necessary to notify *every* single time the client starts up??  Just let me tell the client that I'm happy with my server and from then on don't worry about it!  OwnCloud server keeps adding features that I don't care about, so it's a pain to keep updating it, but the current server works completely fine.  Now, every time we start up we have to manually tell the client that everything is alright.  May have to search for a different client instead then, or back up the client version and freeze on that.
