### ISSUE TITLE
[Activity View] If you disable the Activity app you should not see the server activity tin the activity tab

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#4533]
### Steps to reproduce
1. Open your ownCloud desktop client 2. Disable Activity app in the server.
4. Go to the Desktop client
5. Go to Open Folder "ownCloud"
6. Create a new folder, called aaa
7. Right click on the folder aaa
8. Select share with ownCloud
9. Share with other user (e.g. user1)
10. Wait to sync

### Expected behavior
The activity tab should not be shown (hidden). (If multi-account if all the servers are disabled)

### Actual behavior

No message appears "The administrator has disabled the activity for this server"
Related #3732 #4163 

@MorrisJobke @dragotin 
00004066

**Comment by dragotin** [comment]
This needs testing!

**Comment by SergioBertolinSG** [comment]
Not sure what is expected here.

This message "The administrator has disabled the activity for this server" doesn't appear.

But activity tab dissapears and appears correctly.

In OS X I cannot test it (at least following the exact steps), it is blocked by https://github.com/owncloud/client/issues/4650

**Comment by dragotin** [comment]
I think it is fine that there is just no tab if the activity tab is disabled. The message will appear if there is a *notification* and thus the Activity Tab appears.

**Comment by mcastroSG** [comment]
Hi hi:

**Steps executed**

1. As admin, disable Activity app in the server.
2. Wait for sync.
3. Open your ownCloud desktop client to check that Server Activity tab disappears. 
4. As admin, generate a new notification with Notification App.
5. Wait for sync.

**Results**

Server Activity tab is not shown at Settings > Activity  until server generates a new notification and client sync. At that moment Server Activity tab appears showing notification and the message "Accout XXXX@XXXXX:XXXX does not have activities enabled" appears at the bottom. After closing the notification and wait for next sync Server Activity tab disappears again. 

**MacOS**
Client Version: Version 2.2.0-nightly20160420 (build 3284)
Client OS: MacOS X El Capitan 10.11.4
Server Version: 9.1 Alpha
Server OS: Ubuntu

**Windows**
Client Version: Client Version: Version 2.2.0-nightly20160420 (build 3284)
Client OS: Windows 10
Server Version: 9.1 Alpha
Server OS: Ubuntu

Regards

**Comment by mcastroSG** [comment]
@cdamken is the current behaviour ok?


Results

Server Activity tab is not shown at Settings > Activity until server generates a new notification and client sync. At that moment Server Activity tab appears showing notification and the message "Accout XXXX@XXXXX:XXXX does not have activities enabled" appears at the bottom. After closing the notification and wait for next sync Server Activity tab disappears again.
```

**Comment by cdamken** [comment]
@mcastroSG  Looks good for me :+1:  Thanks
