### ISSUE TITLE
[OS X] Auto-update cannot be triggered

### ISSUE THREAD

**Issue by mtiersch** [owncloud/client#4534]
### Expected behaviour
When a new version of the OS X owncloud client is available, the auto-update should prompt to download the new version.

### Actual behaviour
It has been more than 2 weeks since the ownCloud client release 2.1.1 (Februrary 10th 2016) and the current client 2.1.0 still does not auto-update (today is March 3rd). Also, the update cannot be triggered manually from the ownCloud client. Restarting the client does not trigger the auto-update either.

### Client configuration
Client version: 2.1.0

Operating system: OS X

**Comment by guruz** [comment]
@mtiersch The auto updater was enabled 4 days ago. What happens if you trigger manually?

@danimo Can you check the logs to verify there is no auto-updater-triggered downloads from OS X clients?

**Comment by mtiersch** [comment]
@guruz Thanks for the prompt reply! How is the update triggered manually? There is no button to do this in the settings dialog or menus of the client.

Restarting the client _multiple_ times eventually triggers the software auto-update. Not sure this is a bug anymore, because the delay in enabling the auto-update on the server side seems to be intentional.
The missing "please check for updates"-function or a message "Last checked on <date>" somewhere in the settings is rather a missing feature.

**Comment by danimo** [comment]
@mtiersch We're currently currently not allowing 100% of the update requests to succeed to handle the load on our CDN. We're gradually increasing this value.

**Comment by guruz** [comment]
:+1:
