### ISSUE TITLE
[Windows] [HiDPi] "add account" dialog box' text not wrapping

### ISSUE THREAD

**Issue by martin-rueegg** [owncloud/client#4535]
similar to #4280 and #3414 there's an issue with the text wrapping (see second option on local folder):

![ownCloud Verbindungsassistent](https://cloud.githubusercontent.com/assets/6409516/13492569/b07753ae-e130-11e5-81fb-c557d3bfaac0.JPG)

on windows 8.1 with [Version 2.2.0-nightly20160302 (build 5878)](https://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5878-nightly20160302-setup.exe)

**Comment by guruz** [comment]
https://owncloud.org/changelog/desktop/ 2.3 is out which might fix this

**Comment by martin-rueegg** [comment]
Yes, however the dialog is now way to wide ...

![image](https://cloud.githubusercontent.com/assets/6409516/23557221/3bc34e70-0027-11e7-83e5-77876a9d7b02.png)

... and cannot be narrowed more than this.

**Comment by guruz** [comment]
We have a 2.5 daily build (=testing quality) at http://download.owncloud.com/desktop/daily/ownCloud-2.5.0-daily20180328.MSVC.106.msi .. this has a new Qt version that might fix it.
Please note that 2.5 is unreleased to far, so use at your own risk!

**Comment by ogoffart** [comment]
Looks good according to my test with 2.5

**Comment by guruz** [comment]
@martin-rueegg Do you want to try 2.5.0 alpha1? https://github.com/owncloud/client/releases

**Comment by SamuAlfageme** [comment]
This is how the dialogue looks like in a Win10 VM on 1920 x 1080: 

![wizard_dialog](https://user-images.githubusercontent.com/2644445/41219717-8018bbe0-6d5f-11e8-98ee-4c3b7c2a2e81.png)

I'd say it's solved as it wraps and not in a too-wide way.
