### ISSUE TITLE
[Linux] [VirtualBox] [2.1.1] "unable to initialize a sync journal"

### ISSUE THREAD

**Issue by reylon** [owncloud/client#4536]
### Expected behaviour
The owncloud client has to sync a server remote folder on the client

### Actual behaviour
The owncloud client connect but not start to sync and give the error "unable to initialize a sync journal". 

### Steps to reproduce
1. install a linux client 2.1.1 on a debian 8 jessy 64bit virtualbox system
2. connect user to owncloud server
3. config a personal folder to sync with server - the folder has user permission access

### Server configuration
Operating system:
linux 7 wheezy on raspberry B+ 1Gb ram - system on the HHD
Web server: 
apache 2.2.22 32bit
Database:
mysql 5.5.47+deb7u1
PHP version:
5.4.45-0+deb7u2
ownCloud version:
8.2.2 stable
Storage backend:
HHD

### Client configuration
Client version:
linux owncloud desktop 2.1.1
Operating system:
virtual box server debian jessy 8.3
OS language:
english
Installation path of client:

### Logs
empty because never started to sync

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:
no error reported
![err](https://cloud.githubusercontent.com/assets/9552749/13497048/151fd22e-e15c-11e5-8905-e0d550759ebb.jpg)

3. ownCloud log (data/owncloud.log):
\/VG3i7tCeZnv","remoteAddr":"89.36.20.22","app":"files","message":" Backends provided no user object for ","level":3,"time":"2016-03-03T12:40:56+00:00"}
{"reqId":"iMgVYJET\/VG3i7tCeZnv","remoteAddr":"89.36.20.22","app":"no app in context","message":"Error while running background job: Backends provided no user object for ","level":3,"time":"2016-03-03T12:40:56+00:00"}
{"reqId":"lPa3gyAuSvSemIqSBEqx","remoteAddr":"89.36.20.22","app":"files","message":" Backends provided no user object for ","level":3,"time":"2016-03-03T12:41:14+00:00"}
{"reqId":"lPa3gyAuSvSemIqSBEqx","remoteAddr":"89.36.20.22","app":"no app in context","message":"Error while running background job: Backends provided no user object for ","level":3,"time":"2016-03-03T12:41:14+00:00"}
{"reqId":"odAlPGJuysBKGCVVgKvM","remoteAddr":"89.36.20.22","app":"files","message":" Backends provided no user object for ","level":3,"time":"2016-03-03T12:41:21+00:00"}
{"reqId":"odAlPGJuysBKGCVVgKvM","remoteAddr":"89.36.20.22","app":"no app in context","message":"Error while running background job: Backends provided no user object for ","level":3,"time":"2016-03-03T12:41:21+00:00"}

**Comment by guruz** [comment]
On the client:
What is the sqlite version?
What is the file system type?

**Comment by reylon** [comment]
mysql server version 5.5.47-0+deb8u1
File system type? It is a virtualbox machine with debian jessy 8.3. What you mean, I don't understand sorry.

**Comment by dragotin** [comment]
hmm, is this still happening? I assume not. If so, let me know and we reopen this issue. Best would be to have a logfile snippet, it might tell what happens.
