### ISSUE TITLE
Build problem

### ISSUE THREAD

**Issue by gojkob** [owncloud/client#4539]
Hi, i am trying to build 2.1 version of owncloud for windows. I followed this tutorial:
https://doc.owncloud.org/desktop/2.1/building.html
Build was succesifly finished. 
When i run following command:
docker run owncloud:2.1 -v "$PWD:/home/gojkob/client" \
 admin/win32/docker/build.sh $(id -u)

I got this error:

INFO[2412] POST /v1.21/containers/create                
INFO[2413] POST /v1.21/containers/f0b9151084433c05746845430354ae05f49beab10144f410dd109e6d73b9d60f/attach?stderr=1&stdout=1&stream=1 
INFO[2413] POST /v1.21/containers/f0b9151084433c05746845430354ae05f49beab10144f410dd109e6d73b9d60f/start 
exec: "-v": executable file not found in $PATH
WARN[2413] exit status 1                                
WARN[2414] failed to cleanup ipc mounts:
failed to umount /var/lib/docker/containers/f0b9151084433c05746845430354ae05f49beab10144f410dd109e6d73b9d60f/shm: invalid argument
failed to umount /var/lib/docker/containers/f0b9151084433c05746845430354ae05f49beab10144f410dd109e6d73b9d60f/mqueue: invalid argument 
ERRO[2414] Handler for POST /v1.21/containers/f0b9151084433c05746845430354ae05f49beab10144f410dd109e6d73b9d60f/start returned error: Cannot start container f0b9151084433c05746845430354ae05f49beab10144f410dd109e6d73b9d60f: [8] System error: exec: "-v": executable file not found in $PATH 
ERRO[2414] HTTP Error                                    err=Cannot start container f0b9151084433c05746845430354ae05f49beab10144f410dd109e6d73b9d60f: [8] System error: exec: "-v": executable file not found in $PATH statusCode=500
Error response from daemon: Cannot start container f0b9151084433c05746845430354ae05f49beab10144f410dd109e6d73b9d60f: [8] System error: exec: "-v": executable file not found in $PATH

**Comment by guruz** [comment]
Please try the forums or ownBrander. Alternatively there is the Windows native build.

https://owncloud.org/support
https://doc.owncloud.org/server/8.2/admin_manual/enterprise_clients/creating_branded_apps.html

**Comment by RealRancor** [comment]
Forums won't help here. We're lacking people having such knowledge to help with such topics.

**Comment by junkings** [comment]
I have this problem, two

**Comment by RealRancor** [comment]
@junkings Please read above that the issue tracker is not the place to ask for support on how to build the client. Please follow the resources here:

https://doc.owncloud.org/desktop/2.1/building.html
https://doc.owncloud.org/server/8.2/admin_manual/enterprise_clients/creating_branded_apps.html

or ask for support at the developers mailinglist:

https://mailman.owncloud.org/mailman/listinfo/devel

**Comment by junkings** [comment]
@RealRancor I have builded the client in windows.
But now, I want to solve a problem that how to  package the source and generate a installation file for windows.

**Comment by RealRancor** [comment]
Quoting again:

>  Please read above that the issue tracker is not the place to ask for support
