### ISSUE TITLE
High pings (2 seconds) while running Owncloud Client 2.1.1

### ISSUE THREAD

**Issue by undauntedspirit** [owncloud/client#4541]
### Expected behaviour
I would expect even pings while owncloud is running and not transferring any files.

### Actual behaviour
Every 2-3 seconds pings spike to just under 2 seconds, which makes ssh sessions or gaming nearly impossible or very aggravating.  This bug was already marked as "fixed" and it seems to have improved as there are very few completely lost packets now.

### Steps to reproduce
1. Make sure owncloud is running.

### Client configuration
Client version:
8.1.1
Operating system:
Windows 8.1
OS language:
en-us
Installation path of client:
C:\Program Files (x86)\ownCloud
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

Reply from 192.168.1.100: bytes=32 time=1920ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=2ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=4ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1889ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64
Reply from 192.168.1.100: bytes=32 time=1ms TTL=64

**Comment by guruz** [comment]
Did you install normally or via auto-update?
Did you select "Uninstall previous version before installing"?

**Comment by undauntedspirit** [comment]
Full uninstall and reinstall corrected the issue.   

I did use the automatic update, apparently it didn't quite update everything.  Not a coincidence thought, I have multiple computers updating using the built in updater that also had this problem.

Thanks very much!  I can finally use owncloud again!  You guys are awesome!

**Comment by guruz** [comment]
Good to hear :) On https://github.com/owncloud/client/issues/4541 @lsc36 also said she used the default option. Hmm. So maybe we need to force the re-install in the installer..
