### ISSUE TITLE
Pdf Files not syncing from client to server

### ISSUE THREAD

**Issue by bitsavvy** [owncloud/client#4542]
### Expected behaviour

Adding pdf files to the sync folder on Mac should upload and sync the to owncloud.
### Actual behaviour

pdf files are not uploaded/synced to owncloud.
### Steps to reproduce
1. Add pdf files to sync folder on Mac
### Server configuration

Operating system:
Mac 
El Capita 10.11.3

Web server:  Apache
Database: MySQL 5.5
PHP version: PHP 5.5
ownCloud version: 8.2.2
Storage backend:
### Client configuration

Client version: Version 2.1.1 (build 3107)
Operating system: OSX
OS language: OSX

[apache_phpstack-11844-34322-86255.cloudwaysapps.com.access.log.2.zip](https://github.com/owncloud/client/files/160360/apache_phpstack-11844-34322-86255.cloudwaysapps.com.access.log.2.zip)

Installation path of client:
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   (On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
   (See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )
2. Web server error log:
3. ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
Without more info we cannot help you.

What do you mean by not uploaded? Not even attempted?
What do you see in the UI?
Which error is displayed?

**Comment by bitsavvy** [comment]
Hi Marcus,

Thanks for getting back, sorry for the lack of info ;(

Herewith more info as requested:

What do you mean by not uploaded? Not even attempted? 
I placed a .numbers file and a .pdf copy of the .numbers file in the sync folder on my local machine (Mac). .numbers file was synced and uploaded to Owncloud. Not the .pdf's -- they do show in the sync folder though.
What do you see in the UI?
In owncloud, .numbers files but no pdf's
On local client .numbers files and .pdf's

Which error is displayed?
The file could not be synced due to an error
Latest logfile: 
[apache_phpstack-11844-34322-86255.cloudwaysapps.com.access.log.zip](https://github.com/owncloud/client/files/161185/apache_phpstack-11844-34322-86255.cloudwaysapps.com.access.log.zip)

Regards
Francois Wessels

**Comment by eillarra** [comment]
Similar problem here: Mac Client (Version 2.1.1 (build 3107)) + El Capitan.

Some PDFs do get uploaded, but most of them not. I have tried removing everything and uploading again, but the **same files** get stuck, with a `Method Not Allowed` error logged.

Also, uploading using the website works for **almost** all files. If 15 were stuck using the local client, 2 keep giving errors online. The error I get online is different: `Upload failed. Could not find uploaded file`.

All the files that get stuck are PDF files.

**Comment by guruz** [comment]
@PVince81 @DeepDiver1975 might know something about PDF files not syncing?

**Comment by ckamm** [comment]
@eillarra Does the client sucessfully upload one of the files if you rename it to `.pdf2`?

**Comment by eillarra** [comment]
@ckamm No, but this time returns `Continue blacklisting: Error downloading - server replied: Internal Server Error (Could not write file contents)`

**Comment by guruz** [comment]
@eillarra This blacklist should be be wiped once a day so this "Continue blacklisting" should go.. HOWEVER if the file continously fails with this Internal Server Error then you'll continue to get this. Hmm.

Have you guys also checked if there is something in the core bugtracker at https://github.com/owncloud/core ?

**Comment by eillarra** [comment]
@guruz Any news regarding this issue? Compressing the PDF file to a ZIP file is how we are solving this right now, at least to be able to share the files with some consistency.

**Comment by guruz** [comment]
I can only recommend to also submit this at the core bugtracker or go via the support. The problem should be in the server somewhere. Sorry.

https://owncloud.org/support

**Comment by eillarra** [comment]
For the record: I was running a Scientific Linux 6 server (RHLE 6), so I migrated everything to a brand new Scientific Linux 7.2 server (RHLE 7). The problem with the PDFs persists :(

**Comment by serge-vk** [comment]
Similar behaviour in Mac OS 2.3.0 beta1 tested with NextCloud 11. After downloading a pdf file from Google Docs into a synced folder the client started reporting the file 'could not be synced due to an error: connection closed' (this continued for quite some time). Checking through the web interface, this file was created on the server with zero length. I tried syncing a new re-saved version of the same file and it went fine, but the initial file still reported problems. There were no particularly suspicious entries in the NextCloud log or nginx error log.

After quitting the client it kept crashing on start (two reports sent) until I manually deleted the zero-length file from the server through the web interface. After that, it seems to be Ok for the moment.

**Comment by SamuAlfageme** [comment]
@serge-vk For that problem, see https://github.com/owncloud/core/issues/26797

**Comment by serge-vk** [comment]
Thank you. Just to be more precise, I did not use any Google Docs syncing. The file in question was downloaded from a link with FireFox directly into a local folder synced by the client. I am not sure if it makes any difference.

**Comment by hodyroff** [comment]
Can this be reproduced with 2.3 and oc Server 9.1.4?

**Comment by guruz** [comment]
@bitsavvy @eillarra Are you using Google Drive external storage in this case in your ownCloud?

**Comment by guruz** [comment]
Are you using PHP-FPM?

**Comment by eillarra** [comment]
@guruz In our case the problem was a wrong configuration in Apache. PDF problems were solved when we cleaned up the Apache configuration.

**Comment by ogoffart** [comment]
Closing this old issue as this is unlikely to be a bug in the client.
