### ISSUE TITLE
[Windows] WiFi performance fix not working for auto-updated clients

### ISSUE THREAD

**Issue by lsc36** [owncloud/client#4543]
The fix for #4294 (0ef9bd9) seems to fix newly installed clients only, auto-updated clients still activate the plugin until the user manually renames/removes the directory.

Windows client version 2.1.1 (build 5837), installed and auto-updated since last December (before 0ef9bd9).

**Comment by guruz** [comment]
I guess when auto-updating you did not select "Uninstall previous version before installing"?

**Comment by lsc36** [comment]
I didn't notice such an option, I guess default setting is used.

**Comment by guruz** [comment]
For OS X, the installer removes the bearer plugins.

For Windows, I can confirm that the auto-update installing does _NOT_ remove the bearer plugins (tried updating from 2.1.0 to 2.1.1)

**Comment by guruz** [comment]
To test this: Make sure you still have the ```bearer/``` directory, then run a nightly installer with ```/S /LAUNCH``` to pretend to be the silent updater.

**Comment by mcastroSG** [comment]
Hi Hi:

**Steps Executed**

1. Make a clean installation of 2.1.0 Desktop client.
2. Check `bearer/´ content
3. Launch a new installation of nightly (2.2.0) installer with `/S /LAUNCH´

**Results**

We have checked that after installing ´bearer´content is deleted. Updated from 2.1.X to nightly 2.2.0.

**Windows**
Client Version: Version 2.2.0-nightly20160420 (build 6003)
Client OS: Windows 10
