### ISSUE TITLE
[Feature] Versioning on client

### ISSUE THREAD

**Issue by ouafnico** [owncloud/client#4544]
Hello

I do not have understand the best way to create a feature in "pull requests"..

Is it planned to add the versionning management on the owncloud sync client? To allow users to restore an old version directly with the client?

Also, is it possible to add the trashbin on the client ?

Thanks,

**Comment by danimo** [comment]
> I do not have understand the best way to create a feature in "pull requests"..

You work on a feature using a fork of the repo. Once you're happy with it, you can create a pull request. See https://yangsu.github.io/pull-request-tutorial/ for details

> Is it planned to add the versionning management on the owncloud sync client? To allow users to restore an old version directly with the client?

AFAICT, there are no plans for such a feature.

> Also, is it possible to add the trashbin on the client ?

There is an incomplete pull request at https://github.com/owncloud/client/pull/1874. It needs a lot of work and we're not finally sure if we want it, as it will fill up the local trash rather quickly depending on the semantics and implementation.

**Comment by ouafnico** [comment]
ok thanks for your quick answer.
