### ISSUE TITLE
Missing account name on "Delete all files" confirmation dialog (shows old aliasname instead)

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/client#4545]
### Steps to reproduce
1. Step up ownCloud and upload files
2. Step up sync client
3. Reset ownCloud (reinstall)

### Expected behaviour
Client shows an confirmation dialog that something strange happens :white_check_mark: 
The error message gives enough information about the issue :x: 

### Actual behaviour
The error message does not give any information which account this is about.
I suspect this is because the error is older then the accounts feature?

![bildschirmfoto vom 2016-03-07 12 25 40](https://cloud.githubusercontent.com/assets/213943/13568562/4fb01c38-e462-11e5-8015-d318e85866b0.png)

### Server configuration
Operating system: Linux Mint

Web server: Apach

Database: MySQL

PHP version: 5.5.32

ownCloud version: 8.2.3-rc1

Storage backend: Local

### Client configuration
Client version: git: 2.1 branch

Operating system: Linux Mint

OS language: German

Installation path of client: ~/ownCloud/Desktop/client-build/

**Comment by danimo** [comment]
Fix in https://github.com/owncloud/client/pull/4549
