### ISSUE TITLE
HTTPS redirect fails with "Untrusted certificate"

### ISSUE THREAD

**Issue by marbetschar** [owncloud/client#4546]
### Expected behaviour
HTTPS redirect from alternative domains should not produce a "untrusted certificate" error if all certificates are valid for their domain.

### Actual behaviour
I got a server redirect from https://drive.mandelkind.pizza to https://drive.mandelkind.cloud. Both domains have a trusted and valid certificate configured.

Unfortunately the client throws a "Untrusted certificate" for drive.mandelkind.pizza if the redirect is configured.

### Steps to reproduce
1. Add two sites to your webserver (drive.mandelkind.pizza, drive.mandelkind.cloud)
2. Configure both with a valid SSL certificate
3. Configure a web server redirect from https://drive.mandelkind.pizza to https://drive.mandelkind.cloud
4. Set drive.mandelkind.cloud as the ownCloud trusted domain in config/config.php
5. Try to connect from the desktop client

### Server configuration
Operating system: Ubuntu 14.04

Web server: NGINX

Database: Maria DB

PHP version: 5.6

ownCloud version: 8.2.2

Storage backend:

### Client configuration
Client version: 2.1.1 (3107)

Operating system: OS X

OS language: German

**Comment by marbetschar** [comment]
### Workaround for mobile

I've found a workaround for the iOS App - but this does not work for the desktop client either.

Configure the following redirects:
- **https**://drive.mandelkind.pizza
- **http**://drive.mandelkind.cloud$request_uri
- **https**://drive.mandelkind.cloud$request_uri

**Comment by guruz** [comment]
Thanks.. this is indeed planned: https://github.com/owncloud/client/issues/2791#issuecomment-170584575
