### ISSUE TITLE
Client synchronizing new folders inside a shared folder even if not selected previously

### ISSUE THREAD

**Issue by mihail-minkov** [owncloud/client#4547]
### Expected behaviour

We have a main folder, which is shared with everyone and it weighs about 850 GB and has hundreds of thousands of files. Naturally no one has all the folders synced, just the one they currently need to work on. It is something like this
- Customers (partially checked)
  - Folder 1 (checked)
  - Folder 2 (checked)
  - Folder 3 (unchecked)

So, when we add Folder 4, say, to Customers, I expect it to just be there and update my folder list and get downloaded when I need it, not automatically when it's added. 
### Actual behaviour

When we add a new Folder in our Customers folder it gets downloaded automatically even if we don't have the whole parent folder checked.
### Steps to reproduce
1. Create a main folder in the root of ownCloud.
2. Share it with someone.
3. Create 2-3 folders inside the main folder.
4. The person you shared it with opens its client and selectively syncs the main folder, selecting some of the folders but not all.
5. You add a new folder inside the main folder.
6. The client of the person you shared it with downloads the new folder automatically.
### Server configuration

Operating system: Ubuntu 14.04.4 LTS

Web server: Apache/2.4.18

Database: MySQL 5.5.47-0ubuntu0.14.04.1

PHP version: PHP 5.6.18-1+deb.sury.org~trusty+1 (cli)

ownCloud version: ownCloud 8.2.2 (stable)

Storage backend: 
### Client configuration

Client version: ownCloud Version 2.1.1 (build 5837)

Operating system: Windows 10 Enterprise x64

OS language: English

Installation path of client: C:\Program Files (x86)\ownCloud
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   03-07 13:53:06:334 0x4cc7a78 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (The specified procedure could not be found.)
   03-07 13:53:06:337 0x4cc7a78 unknown: static QWindowsEGLStaticContext\* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001
   03-07 13:53:06:338 0x4cc7a78 unknown: static QWindowsEGLStaticContext\* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
2. Web server error log:
3. ownCloud log (data/owncloud.log):

**Comment by mihail-minkov** [comment]
I don't know if this is done like this on purpose or it's a bug.

**Comment by rullzer** [comment]
This is by design.. Else you would not know there are new (potentially) interesting files. Basically the selection list is opt out. Not opt in currently.

**Comment by mihail-minkov** [comment]
When will there be an option to select whether I would prefer opt in or opt out?

**Comment by dragotin** [comment]
@mihail-minkov once somebody sends a pull request that is accepted by the team.

**Comment by mkln** [comment]
I would also like an option to avoid syncing files not in a folder.
i.e. if I select folder B for syncing, and B is child of A, I'd like to be able to specify if I want files in A to be synced, or not.

By default now it's syncing, but I'm having issues with syncing as there are multiple large files ouside of B but inside of A, and not inside any other folder. they get synced but I dont want them on my pc.

**Comment by michaelstingl** [comment]
Clients now have a setting to not download big folder automatically:
https://doc.owncloud.org/desktop/latest/navigating.html#general-window

Setting the value to "0" should prevent downloading new folders at all. User need to always confirm.
