### ISSUE TITLE
[Discovery] Fix possible issue with retrieval of permissions from the server

### ISSUE THREAD

**Issue by guruz** [owncloud/client#4548]
Detected by @nickvergessen in https://github.com/owncloud/smashbox/pull/134#issuecomment-192215807

**Comment by ckamm** [comment]
I have verified the code that reads `remotePerm` from the database. The `csync_file_stat_t` is nulled correctly and a `NULL` db value leads to an empty `remotePerm`, as expected.

**Comment by ckamm** [comment]
Relevant lines from the logs at https://gist.github.com/nickvergessen/8f5b8ea746a32a7a934b:
```
step03:
SyncJournalFileRecord("owner_worker/dir") 
"INSERT OR REPLACE INTO metadata (remotePerm) VALUES ("")

step05:
csync_walker:  directory: owner_worker/dir
_csync_detect_update:  Database entry found, compare:   <-> RDNVW
```

**Comment by ckamm** [comment]
@nickvergessen This is still confusing. It looks like step03 writes NULL, but step05 reads "RDNVW". Could you verify that this is what's going on by running the test only after step03 and then checking the database?

Use something like sqlitebrowser on .csync_journal.db in the sync directory and then look for the "dir" row in the metadata table. What's the value of the remotePerm column?

**Comment by nickvergessen** [comment]
The permissions are saved as `RDNVW` in the DB after step 3.
Running `oc_sync` a second time would fix the faulty permissions.

**Comment by ckamm** [comment]
@nickvergessen Thanks!

**Comment by ckamm** [comment]
I think the problem is this code in `SqlQuery::bindValue`
```
                // unbound value create a null entry.
                res = SQLITE_OK;
```
i.e. we don't call `sqlite3_bind_null()` when we want to produce a null table entry. Since bindings are *not* cleared by `sqlite3_reset()` the previous file's bindings are inadvertantly written to the database.

I'll try to reproduce the problem and will then fix it.

**Comment by nickvergessen** [comment]
I just built a new master client, so it includes 7bd4f95b8c200e0fc2d5eff2bc5ab2428356a2ba

Fixed the issue and my locking test finally passes in all cases :+1:

**Comment by dragotin** [comment]
great finding @ckamm and @nickvergessen thanks!
