### ISSUE TITLE
File Managers: ownCloud folder icon

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#455]
(Similar to #296 but not the same)

The icon of the ownCloud folder (currently clientsync) is just a regular folder. Would be cool to have that be the ownCloud logo to be able to quickly identify it.

**Comment by MattiJoh** [comment]
The example of icon: http://sc20k1.deviantart.com/art/ownCloud-Icon-492615985
![owncloud](https://cloud.githubusercontent.com/assets/8496953/5812785/74378f9a-a026-11e4-9433-00d86ab8b380.png)

**Comment by bezin** [comment]
MattiJoh

**Comment by danimo** [comment]
@jturcotte Is there anything you need from the art department in order to get this forward?

**Comment by jancborchardt** [comment]
@jturcotte if there is, best shoot a mail to Achim. :)

**Comment by g4b0** [comment]
+1 It would be nice to have a custom icon instead of the flat one

**Comment by bitbonk** [comment]
Please note that under OSX we'd also need an icon for the sidebar in finder.
![osx finder sidebar](https://cloud.githubusercontent.com/assets/418030/14474518/d1487d64-00fd-11e6-8844-9cde072c82f8.png)

**Comment by antoinehenrich** [comment]
+1

**Comment by guruz** [comment]
Just leaving this link here: Windows - Integrate a Cloud Storage Provider

https://msdn.microsoft.com/en-us/en-en/library/windows/desktop/dn889934(v=vs.85).aspx

**Comment by MegaV0lt** [comment]
Propably also related the Nextcloud Icon i made for Windows 7. See there.
https://help.nextcloud.com/t/folder-icon-for-desktop-client-windows7/6188

**Comment by guruz** [comment]
(At least currently the code to create a sidebar favorite seems not to be called at all because it is in a not possible anymore ```else``` branch.. check the wizard for ```Utility::setupFavLink( localFolder )```)
