### ISSUE TITLE
[webdav] [Windows] Client sync issue with "+" "&" symbols in foldernames

### ISSUE THREAD

**Issue by xraynt8** [owncloud/client#4550]
### Expected behaviour
Sync Folder with name "Test+Results" on OwncloudClient 2.1.1 5837
Access Folder and Files with webDAV

### Actual behaviour
Sync on client fails with FileNot Found.
WebDav Folder is empty.
Accessing through webinterface no issues.

### Steps to reproduce
1. Create Folder with a "+" or "&" in its name
2. Try to upload a file to that folder using webDAV or owncloudClient
3. Try to access files on that folder with webdac or owncloudClient

### Server configuration
Operating system: Debian Jessie

Web server: Apache

Database: MySQL

PHP version: PHP5

ownCloud version: 8.2.2

Storage backend: externalStorge-Plugin on smb share

### Client configuration
Client version: 2.1.1 5837

Operating system: Windows 10

OS language: German

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

1. #=#=#=# Syncrun started 2016-03-08T16:20:12 until 2016-03-08T16:20:12 (632 msec)
|0|test+results|INST_SYNC|Up|1457450351||0||4||0|0|1457450340|56deed64dd688|00020742ocrx61e8vcyb|INST_NONE|
|0|test+results/bla.txt|INST_NEW|Up|1457450349||0||6|Blacklisting fortsetzen: Error downloading https://xxxxx/remote.php/webdav/test+results/bla.txt - server replied: Not Found|404|0|0|||INST_NONE|

**Comment by guruz** [comment]
Sounds like a problem with your webserver / setup.

**Comment by guruz** [comment]
@davitol Can you confirm this?

**Comment by davitol** [comment]
Tested with the following combinations and no problems where found:

[ ] oC server version: 8.2.7.1","versionstring":"8.2.7","edition":"Enterprise" and Desktop ClientVersion 2.1.1 (build 5837

[ ] oC server version: 8.2.7.1","versionstring":"8.2.7","edition":"Enterprise" and Desktop Client Version 2.1.0 (build 5683)

[ ] "8.2.2.2","versionstring":"8.2.2","edition":"" and Desktop Client Version 2.1.0 (build 5683)

so I can`t reproduce it

**Comment by guruz** [comment]
Thanks!

@xraynt8 Please also update to 2.2.3
