### ISSUE TITLE
Updating an install base of the client?

### ISSUE THREAD

**Issue by mjmunger** [owncloud/client#4555]
I need to be able to automatically update the client in a Windows domain environment. I do not see an MSI published, so I am thinking that I can just do a direct file copy from the newest version to our windows clients.

Does the installer do anything other than copy files for an update?

**Comment by guruz** [comment]
@DrDamnit You should run the installer in a way so that it uninstalls the previous version first, else you might run into https://github.com/owncloud/client/issues/4543

**Comment by DrDamnit** [comment]
Yes, but I can't do that via GPO, because it's an exe installer. Thoughts?

**Comment by guruz** [comment]
https://github.com/owncloud/client/issues/860
