### ISSUE TITLE
CentOS 6 client package is missing dep on opt-libqt4-x11

### ISSUE THREAD

**Issue by LaHaine** [owncloud/client#4560]
### Expected behaviour
owncloud should start

### Actual behaviour
/opt/qt-4.8/bin/owncloud: symbol lookup error: 
/usr/lib64/libQtOpenGL.so.4: undefined symbol: 
_ZN14QObjectPrivate15checkWindowRoleEv

### Steps to reproduce
Fresh install of CentOS 6.6: add owncloud for CentOS6.6 repository and install owncloud-client

### Client configuration
Client version: 2.1.1-1.1

Operating system: CentOS 6.6

OS language: en_US.UTF-8

**Comment by jnweiger** [comment]
@LaHaine  on my CentOS-6.7 test system, I correctly get opt-libqt4-x11-4.8.6-2.4 installed as a dependency. Is that issue persisting for you?

**Comment by LaHaine** [comment]
@jnweiger: You didn't have KDE installed. The problem is not fixed, I have qt-x11-4.6.2-28.el6_5.x86_64 installed, this satisfies the qt dep of the owncloud-client package on a rpm level but not on the ABI level, see the error in the original report.

**Comment by jnweiger** [comment]
@dragotin do you know if our /opt/qt-4.8/bin/owncloud should be compatible with  qt-4.6 -- I only know about 4.8. 
From a packaging perspective, the only thing I can do is make the 4.8 dependency more explicit, so that it fails earlier. Probably not what you ask for.

**Comment by dragotin** [comment]
No, not compatible. 

The package should depend on our opt-qt-4.8. It wont work with the qt4.6

**Comment by jnweiger** [comment]
Checking my test system again:

rpm -qa | grep qt
opt-libqt4-4.8.6-2.4.x86_64
opt-libqt4-x11-4.8.6-2.4.x86_64
qt-sqlite-4.6.2-28.el6_5.x86_64
opt-libqtkeychain0-0.5-7.2.x86_64
opt-libqt4-sql-4.8.6-2.4.x86_64
qt-4.6.2-28.el6_5.x86_64
qt-x11-4.6.2-28.el6_5.x86_64

With the client up and running, I see that it links nothing from the hosts qt-4.6 
<pre>
lsof -p 10154 | grep qt
owncloud 10154 root  txt    REG             0,3755  1903080    11938 /opt/qt-4.8/bin/owncloud
owncloud 10154 root  mem    REG               0,32             11938 /opt/qt-4.8/bin/owncloud (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12083 /opt/qt-4.8/share/qt4/translations/qt_de.qm (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12036 /opt/qt-4.8/lib64/qt4/plugins/imageformats/libqtiff.so (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12035 /opt/qt-4.8/lib64/qt4/plugins/imageformats/libqtga.so (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             11994 /opt/qt-4.8/lib64/libQtSvg.so.4.8.6 (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12034 /opt/qt-4.8/lib64/qt4/plugins/imageformats/libqsvg.so (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12033 /opt/qt-4.8/lib64/qt4/plugins/imageformats/libqmng.so (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12032 /opt/qt-4.8/lib64/qt4/plugins/imageformats/libqjpeg.so (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12031 /opt/qt-4.8/lib64/qt4/plugins/imageformats/libqico.so (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12030 /opt/qt-4.8/lib64/qt4/plugins/imageformats/libqgif.so (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12016 /opt/qt-4.8/lib64/qt4/plugins/bearer/libqnmbearer.so (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12015 /opt/qt-4.8/lib64/qt4/plugins/bearer/libqgenericbearer.so (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12014 /opt/qt-4.8/lib64/qt4/plugins/bearer/libqconnmanbearer.so (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12008 /opt/qt-4.8/lib64/libqtkeychain.so.0.5.0 (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             11955 /opt/qt-4.8/lib64/libQtCore.so.4.8.6 (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             11979 /opt/qt-4.8/lib64/libQtNetwork.so.4.8.6 (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             11991 /opt/qt-4.8/lib64/libQtSql.so.4.8.6 (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12003 /opt/qt-4.8/lib64/libQtXml.so.4.8.6 (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             11958 /opt/qt-4.8/lib64/libQtDBus.so.4.8.6 (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             11970 /opt/qt-4.8/lib64/libQtGui.so.4.8.6 (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12006 /opt/qt-4.8/lib64/libQtXmlPatterns.so.4.8.6 (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12000 /opt/qt-4.8/lib64/libQtWebKit.so.4.9.3 (path dev=0,3755)
owncloud 10154 root  mem    REG               0,32             12129 /opt/qt-4.8/share/qt4/translations/qtkeychain_de.qm (path dev=0,3755)

</pre>

We have /opt/qt-4.8/bin/qt-4.8-env.sh hooked into the /usr/bin/owncloud wrapper to make sure that we pull all our dependencies from /opt/qt-4.8
That seems to work fine here. @LaHaine please compare the above with your system.

**Comment by LaHaine** [comment]
@jnweiger 
# rpm -qa |grep qt
opt-libqtkeychain0-0.5-7.2.x86_64
qt-x11-4.6.2-28.el6_5.x86_64
qt-mysql-4.6.2-28.el6_5.i686
qt3-3.3.8b-30.el6.x86_64
qt3-devel-3.3.8b-30.el6.x86_64
qt5-qtbase-gui-5.5.1-11.el6.x86_64
qt3-devel-3.3.8b-30.el6.i686
qt-4.6.2-28.el6_5.x86_64
qt-mobility-1.1.3-2.el6.i686
qt-sqlite-4.6.2-28.el6_5.i686
poppler-qt4-0.12.4-4.el6_6.1.x86_64
qt-doc-4.6.2-28.el6_5.noarch
qt-devel-4.6.2-28.el6_5.i686
qt5-qtbase-5.5.1-11.el6.x86_64
qt3-MySQL-3.3.8b-30.el6.x86_64
qt3-PostgreSQL-3.3.8b-30.el6.i686
qt3-3.3.8b-30.el6.i686
qt-postgresql-4.6.2-28.el6_5.i686
opt-libqt4-4.8.6-2.4.x86_64
qt-sqlite-4.6.2-28.el6_5.x86_64
libqtkeychain0-0.20130221-7.1.x86_64
qt3-ODBC-3.3.8b-30.el6.x86_64
qt-x11-4.6.2-28.el6_5.i686
qt3-ODBC-3.3.8b-30.el6.i686
qt-mysql-4.6.2-28.el6_5.x86_64
qtwebkit-2.1.1-1.el6.i686
qtwebkit-2.1.1-1.el6.x86_64
qt-4.6.2-28.el6_5.i686
qt-odbc-4.6.2-28.el6_5.x86_64
qt-devel-4.6.2-28.el6_5.x86_64
qt3-MySQL-3.3.8b-30.el6.i686
qt-mobility-1.1.3-2.el6.x86_64
qt5-qtbase-common-5.5.1-11.el6.noarch
qt-odbc-4.6.2-28.el6_5.i686
opt-libqt4-sql-4.8.6-2.4.x86_64
qt-postgresql-4.6.2-28.el6_5.x86_64
qt3-PostgreSQL-3.3.8b-30.el6.x86_64

As you can see, nothing pulled in opt-libqt4-x11 as no package has a dep on opt-libqt4-x11. If I install it manually it is picked up by owncloud, so the wrapper script is fine, the deps of the package are not.

**Comment by jnweiger** [comment]
Thanks for the details. 
Dependencies to our own bundled packages added. Will show up with next release. Meanwhile your workaround (manual install opt-libqt4-x11) applies.
