### ISSUE TITLE
[Windows] Use of silent switch "/S" on client 2.1.1 5837 still requires interaction from user

### ISSUE THREAD

**Issue by f-s** [owncloud/client#4563]
Hi,

using the native SYSTEM account of Windows 7 Pro, for silent deployment of the said client, when updating the client from e.g. 1.8, still requires user-interaction and gives an empty "interactive services detection message". The process causing the message is "apparently" the vcredist (supplied with the client setup).

When changing to said SYSTEM user desktop and viewing the message, no message is displayed.

It looks like the oc-client setup cannot successfully silence the vcredist component of its setup in all circumstances.

Please investigate.

Thanks!

![bgdbdecd](https://cloud.githubusercontent.com/assets/7151788/13663028/feaa2664-e69e-11e5-9ad8-c7391f087855.png)

**Comment by guruz** [comment]
Is this for a commercial setup? Then I recommend asking via https://owncloud.org/support/

**Comment by danimo** [comment]
Please provide details on how you run setup as system authority.

**Comment by danimo** [comment]
For reference, a `psexec -i -s -d ownCloud-2.0.2.5569-setup.exe /S` went through without any ado. PSExec is part of Sysinternals.

**Comment by hodyroff** [comment]
No info provided. Closing.
