### ISSUE TITLE
Grayed out network options in Ubuntu 15.10

### ISSUE THREAD

**Issue by FMuro** [owncloud/client#4564]
### Expected behaviour
The options related to bandwidth should be available

### Actual behaviour
They are grayed out.

### Steps to reproduce
1. Open client settings.
2. Click on Network.
3. Check the bandwidth options.

### Server configuration
Not sure about this, I'm not the admin, although I think I've heard they have some Red Hat server with Owncloud 8.0.3. Anyway, I'd say my issue is just about the client.

Operating system: ??

Web server: ??

Database: ??

PHP version: ??

ownCloud version: ??

Storage backend: ??

### Client configuration
Client version: 2.1.1.

Operating system: Ubuntu 15.10.

OS language: English.

Installation path of client: It's scattered throughout /usr. I've installed from the official Owncloud repos following the instructions in https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by danimo** [comment]
This is expected behavior. Bandwidth Management requires the Client to be built against Qt 5.4 or better. This is not possible on Ubuntu due to a missing integration with Unity which is only available in Ubuntu with Qt 4 (due to a custom patch) and Qt 5.6 (which does not ship with Ubuntu 15.10).

**Comment by FMuro** [comment]
Thanks danimo! Is this expected to improve in 16.05 (with Unity)?

**Comment by danimo** [comment]
@FMuro We cannot test 16.05 yet, because it's not in not on OBS at this point.
