### ISSUE TITLE
[Linux] should use the new Cloud Providers API for file manager integration

### ISSUE THREAD

**Issue by micahilbery** [owncloud/client#4566]
### Expected behaviour

Client should integrate with file manager.
### Actual behaviour

It uses an indicator icon instead.
### Suggestion

For integration with linux file managers you can use the Cloud Providers API shown <a href="https://csorianognome.wordpress.com/2015/07/07/cloud-providers/" target="blank">here</a>

**Comment by dragotin** [comment]
It would be good if you could be a bit more elaborated on which ways of integration you see. @jancborchardt fyi

**Comment by TraumaD91** [comment]
Right now you have an indicator where the status of sync & interactions take place. If I understand it correctly using this API would allow the same information/interactions but instead through the sidebar of file manager. It basically acts the same way but is more universal and doesn't rely on indicators.

**Comment by jancborchardt** [comment]
@dragotin check out the blogpost linked above: https://csorianognome.wordpress.com/2015/07/07/cloud-providers/
