### ISSUE TITLE
[OSX] Icon\r files are synchronised in spite of the line in sync-exclude.lst

### ISSUE THREAD

**Issue by xoolive** [owncloud/client#4568]
Referring to https://github.com/owncloud/client/blob/master/sync-exclude.lst#L6

This obviously doesn't work under OSX. `Icon$'\r'` files are pushed to owncloud anyway.
I found a workaround which is to manually edit the `sync-exclude.lst` file in the application bundle:
- get to the line, trash `\r*`
- input the real character (with vim in insertion mode, the magic combination would be `Ctrl-V + x + 0D`)

I filed an issue rather than open a PR because I am not sure how things would go on a cross-platform point of view. This works well because I add a Windows-style end of line in a Unix-encoded file, but it should be investigated further whether no side effects appear on other OS.

**Comment by guruz** [comment]
This might be a regression from optimizing/rewriting the exclude parse code and then not using format-style functions anymore..

**Comment by ckamm** [comment]
@guruz Yes. The escape patterns directly use `fnmatch()` from glibc and the docs say the backslash is used for simple escaping only: `\r` means `r`.

**Comment by dragotin** [comment]
So the pattern would have to be `Icon$'\\r'` ? @xoolive can you try please?

**Comment by ckamm** [comment]
@dragotin I don't think so, that'd match files that are literally called `Icon$'\r'. One currently can't express the \r character in exclude patterns. According to the code in csync_exclude.c the literal \r that @xoolive inserted will just get treated as an exclude pattern delimiter. 

If we want to support \r, we need to preprocess the strings we read from the exclude list before passing them to fnmatch.

**Comment by ckamm** [comment]
(that title edit was unnecessary, I didn't realize what you meant by `$'\r'`....)

**Comment by dragotin** [comment]
Hmm ok, that's right. BTW - what is the '$' in the pattern? Is that for the line ending? In this case, no, we do not support strong regexp here.  To change that we'd need to go away from `fnmatch()` which is not currently in scope.

**Comment by ckamm** [comment]
@dragotin That also confused me. The current pattern string is literally `Icon\r*`. I'll add code to expand the escape correctly.

**Comment by xoolive** [comment]
@dragotin  `Icon$'\r'` is the way to access the file from your terminal. However, the result of the `ls` is different...

```sh
prompt> ls Icon$'\r'
Icon?
``

**Comment by guruz** [comment]
@xoolive Could you try a recent nightly? http://download.owncloud.com/desktop/daily/ownCloud-2.2.0.3199-nightly20160321.pkg

**Comment by xoolive** [comment]
@guruz Thank you for the build. I just tried and it works like a charm! :+1:

**Comment by guruz** [comment]
Great! :)

Thanks @ckamm for fixing..
