### ISSUE TITLE
can't build the owncloud client for windows 

### ISSUE THREAD

**Issue by junkings** [owncloud/client#4569]
### Expected behaviour
Tell us what should happen

Hi all,
       I download the source of client. And then, According tutorial “https://github.com/owncloud/client/issues/2999”  and “https://www.youtube.com/watch?v=ncpu7YGdHaM” , I build the owncloud client.
      But I got the linux's executable file, not windows....

      So, which step is wrong?

  
thank you!

**Comment by danimo** [comment]
Just follow the guide for the latest version with the tar ball for the latest version: https://doc.owncloud.org/desktop/2.1/building.html#windows-installer-build-cross-compile

**Comment by junkings** [comment]
I'm doubt this “using the MinGW cross compiler”. 
How to install the MinGW cross compiler?

Sorry, i'm a beginner。

Could you explain it more in detail？

**Comment by danimo** [comment]
It would help to know what you're planning to do. Maybe a native developer environment is easier for you?
