### ISSUE TITLE
[Gentoo/Linux] Plasma 5: overlay icon & share action missing

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/client#4570]
### Expected behaviour

With plasma 5 and newest client I expect to see overlay icons and the share action.
### Actual behaviour

No overlay icon, but "owncloud actions" in dolphin -> configure dolphin -> services
### Steps to reproduce
1. open dolphin and navigate to synced folder
### Server configuration

Operating system: Gentoo

Web server: Apache

Database: Mysql

PHP version: 5.5

ownCloud version: 8.2
### Client configuration

Client version: 2.1.1

Operating system: Gentoo

OS language: German

Installation path of client:/usr/bin/owncloud

**Comment by dragotin** [comment]
depends on #4456

The code is there, however it needs to be packaged for your distro. I have no idea how that works in Gentoo.

**Comment by tobiasKaminsky** [comment]
Gentoo is building its package from source code.
Maybe you can explain the manual way of building it and I can try to adopt this to gentoo?
Currently I have no clue what to do with the files/templates in #4456 ;)

**Comment by dragotin** [comment]
Ok, you need to have the devel packages of KDE Frameworks KIO with minimal version 5.16 installed. With that, cmake will automatically build the plugin. 

Check the output of cmake!

**Comment by tobiasKaminsky** [comment]
You are refering to this directory: https://github.com/owncloud/client/tree/master/shell_integration/dolphin ?
As this https://github.com/owncloud/administration/tree/master/jenkins/obs_integration/templates/client/v2_2_0 which is mentioned in #4456 seems to be only templates?

**Comment by dragotin** [comment]
Yes, but we do not have build instructions for Gentoo. Do not confuse *package building* with building the client from source. Its sometimes confusing.

**Comment by tobiasKaminsky** [comment]
No no, I know the difference ;)
The lib is installed in /usr/lib64/kde4/plugins/ownclouddolphinactionplugin.so and /usr/lib64/kde4/plugins/kf5/overlayicon/ownclouddolphinoverlayplugin.so . 
$QT_PLUGIN_PATH is: /usr/lib64/kde4/plugins. 
Neither dolphin nor owncloud-client shows a relevant info on konsole.

(First I try it with manual building and after everything is working I would modify the ebuild to enhance the package building. But the first step is not working...)

**Comment by dragotin** [comment]
Oh, you should build against Qt5! And the overlay icons only work with KDE Frameworks 5

**Comment by tobiasKaminsky** [comment]
It is. Apparently the prefix is just pointing to kde4:

configure:
`-- Found Qt5 core, checking for further dependencies...
-- Using Qt 5!
....
-- Found KF5KIO: /usr/lib64/cmake/KF5KIO/KF5KIOConfig.cmake (found version "5.19.0") 
-- Found KF5: success (found suitable version "5.19.0", minimum required is "5.16") found components:  KIO 
-- Found KF5CoreAddons: /usr/lib64/cmake/KF5CoreAddons/KF5CoreAddonsConfig.cmake (found version "5.19.0") 
-- Found KF5: success (found suitable version "5.19.0", minimum required is "5.16.0") found components:  CoreAddons KIO`

But also:
`CMake Warning (dev) at /usr/share/ECM/modules/ECMFindModuleHelpers.cmake:120 (message):
  Your project should require at least CMake 2.8.12 to use FindKF5.cmake
Call Stack (most recent call first):
  /usr/share/ECM/find-modules/FindKF5.cmake:52 (ecm_find_package_version_check)
  shell_integration/CMakeLists.txt:11 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.`

`CMake Warning at /usr/share/ECM/kde-modules/KDEInstallDirs.cmake:595 (message):
  KDE_INSTALL_BINDIR, KDE_INSTALL_LIBDIR and KDE_INSTALL_INCLUDEDIR should
  either all be absolute paths or all be relative paths.
Call Stack (most recent call first):
  shell_integration/dolphin/CMakeLists.txt:22 (include)`

Built against QT5 and KF5: 
`$ldd /usr/lib64/libownclouddolphinpluginhelper.so
        linux-vdso.so.1 (0x00007fff995e1000)
        libQt5Network.so.5 => /usr/lib64/libQt5Network.so.5 (0x00007ff1faab1000)
        libQt5Core.so.5 => /usr/lib64/libQt5Core.so.5 (0x00007ff1fa625000)
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6 (0x00007ff1fa315000)
        libc.so.6 => /lib64/libc.so.6 (0x00007ff1f9f7a000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007ff1f9d5e000)
        libz.so.1 => /lib64/libz.so.1 (0x00007ff1f9b47000)
        libssl.so.1.0.0 => /usr/lib64/libssl.so.1.0.0 (0x00007ff1f98d1000)
        libcrypto.so.1.0.0 => /usr/lib64/libcrypto.so.1.0.0 (0x00007ff1f9490000)
        libicui18n.so.55 => /usr/lib64/libicui18n.so.55 (0x00007ff1f9031000)
        libicuuc.so.55 => /usr/lib64/libicuuc.so.55 (0x00007ff1f8ca3000)
        libpcre16.so.0 => /usr/lib64/libpcre16.so.0 (0x00007ff1f8a40000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007ff1f883b000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007ff1f8502000)
        librt.so.1 => /lib64/librt.so.1 (0x00007ff1f82fa000)
        libm.so.6 => /lib64/libm.so.6 (0x00007ff1f7ffd000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1 (0x00007ff1f7de6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007ff1fae63000)
        libicudata.so.55 => /usr/lib64/libicudata.so.55 (0x00007ff1f632e000)`

`$ldd /usr/lib64/plugins/kf5/overlayicon/ownclouddolphinoverlayplugin.so
        linux-vdso.so.1 (0x00007fffe3bff000)
        libKF5KIOWidgets.so.5 => /usr/lib64/libKF5KIOWidgets.so.5 (0x00007f63abddb000)
        libownclouddolphinpluginhelper.so => /usr/lib64/libownclouddolphinpluginhelper.so (0x00007f63abbd5000)
        libQt5Core.so.5 => /usr/lib64/libQt5Core.so.5 (0x00007f63ab74a000)
        libstdc++.so.6 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libstdc++.so.6 (0x00007f63ab43a000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f63ab09e000)
        libKF5KIOCore.so.5 => /usr/lib64/libKF5KIOCore.so.5 (0x00007f63aad35000)
        libKF5JobWidgets.so.5 => /usr/lib64/libKF5JobWidgets.so.5 (0x00007f63aab0d000)
        libKF5Service.so.5 => /usr/lib64/libKF5Service.so.5 (0x00007f63aa873000)
        libQt5Network.so.5 => /usr/lib64/libQt5Network.so.5 (0x00007f63aa716000)
        libKF5Completion.so.5 => /usr/lib64/libKF5Completion.so.5 (0x00007f63aa4dd000)
        libKF5IconThemes.so.5 => /usr/lib64/libKF5IconThemes.so.5 (0x00007f63aa29f000)
        libKF5WindowSystem.so.5 => /usr/lib64/libKF5WindowSystem.so.5 (0x00007f63aa053000)
        libKF5ConfigWidgets.so.5 => /usr/lib64/libKF5ConfigWidgets.so.5 (0x00007f63a9dff000)
        libattr.so.1 => /lib64/libattr.so.1 (0x00007f63a9bf9000)
        libKF5WidgetsAddons.so.5 => /usr/lib64/libKF5WidgetsAddons.so.5 (0x00007f63a98ab000)
        libKF5I18n.so.5 => /usr/lib64/libKF5I18n.so.5 (0x00007f63a9657000)
        libKF5ConfigGui.so.5 => /usr/lib64/libKF5ConfigGui.so.5 (0x00007f63a9436000)
        libKF5ConfigCore.so.5 => /usr/lib64/libKF5ConfigCore.so.5 (0x00007f63a91d7000)
        libQt5DBus.so.5 => /usr/lib64/libQt5DBus.so.5 (0x00007f63a915a000)
        libKF5CoreAddons.so.5 => /usr/lib64/libKF5CoreAddons.so.5 (0x00007f63a8ec8000)
        libQt5Widgets.so.5 => /usr/lib64/libQt5Widgets.so.5 (0x00007f63a883f000)
        libQt5Gui.so.5 => /usr/lib64/libQt5Gui.so.5 (0x00007f63a8384000)
        libm.so.6 => /lib64/libm.so.6 (0x00007f63a8087000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f63a7e6b000)
        libz.so.1 => /lib64/libz.so.1 (0x00007f63a7c54000)
        libicui18n.so.55 => /usr/lib64/libicui18n.so.55 (0x00007f63a77f6000)
        libicuuc.so.55 => /usr/lib64/libicuuc.so.55 (0x00007f63a7468000)
        libpcre16.so.0 => /usr/lib64/libpcre16.so.0 (0x00007f63a7205000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007f63a7000000)
        libglib-2.0.so.0 => /usr/lib64/libglib-2.0.so.0 (0x00007f63a6cc7000)
        librt.so.1 => /lib64/librt.so.1 (0x00007f63a6abf000)
        libgcc_s.so.1 => /usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/libgcc_s.so.1 (0x00007f63a68a7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f63ac350000)
        libQt5Xml.so.5 => /usr/lib64/libQt5Xml.so.5 (0x00007f63a686b000)
        libKF5DBusAddons.so.5 => /usr/lib64/libKF5DBusAddons.so.5 (0x00007f63a6659000)
        libacl.so.1 => /lib64/libacl.so.1 (0x00007f63a6450000)
        libQt5X11Extras.so.5 => /usr/lib64/libQt5X11Extras.so.5 (0x00007f63a644c000)
        libssl.so.1.0.0 => /usr/lib64/libssl.so.1.0.0 (0x00007f63a61d5000)
        libcrypto.so.1.0.0 => /usr/lib64/libcrypto.so.1.0.0 (0x00007f63a5d94000)
        libQt5Svg.so.5 => /usr/lib64/libQt5Svg.so.5 (0x00007f63a5d3e000)
        libKF5ItemViews.so.5 => /usr/lib64/libKF5ItemViews.so.5 (0x00007f63a5b03000)
        libX11.so.6 => /usr/lib64/libX11.so.6 (0x00007f63a57c9000)
        libxcb.so.1 => /usr/lib64/libxcb.so.1 (0x00007f63a55a9000)
        libxcb-keysyms.so.1 => /usr/lib64/libxcb-keysyms.so.1 (0x00007f63a53a5000)
        libKF5Codecs.so.5 => /usr/lib64/libKF5Codecs.so.5 (0x00007f63a516b000)
        libKF5Auth.so.5 => /usr/lib64/libKF5Auth.so.5 (0x00007f63a4f57000)
        libKF5GuiAddons.so.5 => /usr/lib64/libKF5GuiAddons.so.5 (0x00007f63a4d3b000)
        libdbus-1.so.3 => /usr/lib64/libdbus-1.so.3 (0x00007f63a4af4000)
        libpng16.so.16 => /usr/lib64/libpng16.so.16 (0x00007f63a48bf000)
        libharfbuzz.so.0 => /usr/lib64/libharfbuzz.so.0 (0x00007f63a4659000)
        libGL.so.1 => /usr/lib64/libGL.so.1 (0x00007f63a43c1000)
        libicudata.so.55 => /usr/lib64/libicudata.so.55 (0x00007f63a2909000)
        libXau.so.6 => /usr/lib64/libXau.so.6 (0x00007f63a2705000)
        libXdmcp.so.6 => /usr/lib64/libXdmcp.so.6 (0x00007f63a24fe000)
        libfreetype.so.6 => /usr/lib64/libfreetype.so.6 (0x00007f63a223d000)
        libgraphite2.so.3 => /usr/lib64/libgraphite2.so.3 (0x00007f63a200f000)
        libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007f63a1de5000)
        libglapi.so.0 => /usr/lib64/libglapi.so.0 (0x00007f63a1bb7000)
        libXext.so.6 => /usr/lib64/libXext.so.6 (0x00007f63a19a4000)
        libXdamage.so.1 => /usr/lib64/libXdamage.so.1 (0x00007f63a17a1000)
        libXfixes.so.3 => /usr/lib64/libXfixes.so.3 (0x00007f63a159b000)
        libX11-xcb.so.1 => /usr/lib64/libX11-xcb.so.1 (0x00007f63a1398000)
        libxcb-glx.so.0 => /usr/lib64/libxcb-glx.so.0 (0x00007f63a1180000)
        libxcb-dri2.so.0 => /usr/lib64/libxcb-dri2.so.0 (0x00007f63a0f7b000)
        libxcb-dri3.so.0 => /usr/lib64/libxcb-dri3.so.0 (0x00007f63a0d77000)
        libxcb-present.so.0 => /usr/lib64/libxcb-present.so.0 (0x00007f63a0b74000)
        libxcb-randr.so.0 => /usr/lib64/libxcb-randr.so.0 (0x00007f63a0966000)
        libxcb-xfixes.so.0 => /usr/lib64/libxcb-xfixes.so.0 (0x00007f63a075e000)
        libxcb-render.so.0 => /usr/lib64/libxcb-render.so.0 (0x00007f63a0554000)
        libxcb-shape.so.0 => /usr/lib64/libxcb-shape.so.0 (0x00007f63a0350000)
        libxcb-sync.so.1 => /usr/lib64/libxcb-sync.so.1 (0x00007f63a0149000)
        libxshmfence.so.1 => /usr/lib64/libxshmfence.so.1 (0x00007f639ff46000)
        libXxf86vm.so.1 => /usr/lib64/libXxf86vm.so.1 (0x00007f639fd40000)
        libdrm.so.2 => /usr/lib64/libdrm.so.2 (0x00007f639fb30000)
        libbz2.so.1 => /lib64/libbz2.so.1 (0x00007f639f920000)`

**Comment by abulak** [comment]
On (my) gentoo overlay icons, etc works however I have to set
QT_PLUGIN_PATH=/usr/lib64/qt5/plugins:/usr/lib64/kde4/plugins:/usr/lib64/plugins
otherwise dolphin can not find the plug-in;
This is probably more of an ebuild (ie packaging) issue

**Comment by guruz** [comment]
@abulak @tobiasKaminsky If this is a gentoo packaging issue, would you try to fix the upstream packages so we can close this out here?

**Comment by tobiasKaminsky** [comment]
Created a bugreport on bugs.gentoo.org: https://bugs.gentoo.org/show_bug.cgi?id=580752

**Comment by fmoc** [comment]
Downstream has apparently fixed the issue, see the above link. Therefore closing here.
