### ISSUE TITLE
Debian/Ubuntu source packages

### ISSUE THREAD

**Issue by rabauke** [owncloud/client#4571]
I am unable to download Debian/Ubuntu source packages for the owncloud client via apt-get on Ubuntu 16.04. My apt configuration:

    $ cat /etc/apt/sources.list.d/owncloud-client.list
    deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_15.10/ /
    deb-src http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_15.10/ /

Attempting to download gives the following errors:

    $ apt-get source owncloud-client
    Reading package lists... Done
    Skipping download of file 'owncloud-client_2.1.1.orig.tar.gz' as requested hashsum is not available for authentication
    Skipping download of file 'owncloud-client_2.1.1-2.1.diff.gz' as requested hashsum is not available for authentication
    Need to get 794 B of source archives.
    Get:1 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_15.10  owncloud-client 2.1.1-2.1 (dsc) [794 B]
    Fetched 794 B in 0s (12.4 kB/s)         
    dpkg-source: warning: extracting unsigned source package (owncloud-client_2.1.1-2.1.dsc)
    dpkg-source: error: cannot fstat file ./owncloud-client_2.1.1.orig.tar.gz: No such file or directory
    Unpack command 'dpkg-source -x owncloud-client_2.1.1-2.1.dsc' failed.
    Check if the 'dpkg-dev' package is installed.
    E: Sub-process dpkg-source returned an error code (1)

Probably there are some hashes missing or possibly wrong in the repository. As a workaround missing files can be downloaded via wget, afterwards the sources can be extracted with

    $ dpkg-source --no-check -x owncloud-client_2.1.1-2.1.dsc

It would be great if this issue could be fixed.

**Comment by DaCryptor** [comment]
When will this issue be resolved? The error messages from the Mint update center starts to get annoying after several days...

**Comment by lemmingzshadow** [comment]
The repository for Ubuntu 14.04 seems also broken:

> W: Failed to fetch http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.04/Packages  404  Not Found [IP: 195.135.221.134 80]

**Comment by jnweiger** [comment]
@lemmingzshadow This is a different issue. Please try http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/Packages without the 'x'.

**Comment by lemmingzshadow** [comment]
@jnweiger That seems to work. Gracias!

**Comment by jnweiger** [comment]
I have currently no solution. sorry. Last week, apt-get source php5-libsmbclient worked fine for me.

**Comment by jnweiger** [comment]
@DaCryptor Would pulling binaries through the update center work for you?

**Comment by DaCryptor** [comment]
Yes, everything is allright now. Deleted some bad ppa-entries.
