### ISSUE TITLE
old version of OpenSSL (1.0.1f)

### ISSUE THREAD

**Issue by DaCryptor** [owncloud/client#4572]
### Expected behaviour
I believe a more up-2-date-version of OpenSSL should be used.

### Actual behaviour
Currently, the client uses just OpenSSL 1.0.1f, which is full of security issues, even Heartbleed!
Why not switch to 1.0.1s or 1.0.2g?

### Steps to reproduce
1. Start OC-client, settings, general (about section)
2. 
3. 

### Server configuration
Operating system: Linux Mint Cinnamon 17.3 x64 

Web server: 

Database:

PHP version:

ownCloud version: 2.1.1

Storage backend:

### Client configuration
Client version:

Operating system:

OS language:

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by danimo** [comment]
> Why not switch to 1.0.1s or 1.0.2g?

Because we're dynamically linking against whatever your distribution ships. And that is 1.0.1f. We only issue the OpenSSL version for debugging purposes.

(Yes, of course: distributions do apply security updates, but they won't bump version numbers :)
