### ISSUE TITLE
[2.1.1] no logout button

### ISSUE THREAD

**Issue by zanglerecke** [owncloud/client#4578]
Missing logout button, but login is there (when i am still loged in)
(i used just a german version of the client) (Ausloggen is not there)

### Steps to reproduce
1. just login in an account
2. try to logout, -> no logout button, but a login button wich acts as an logout.

Client Version 2.1.1 (build 5837)

Operating system: Win7 64

OS language: DE

**Comment by guruz** [comment]
Do you have a screenshot? (you can drag it into this bugreport).

I have a logout possibility both in the tray icon menu and on the "Account" button of the account.

**Comment by zanglerecke** [comment]
i just saw that it is just ok, if i realy logged in, but if the login fails... the system is in an 3ed state, ....
![logoff](https://cloud.githubusercontent.com/assets/5063778/13848797/c0e7c678-ec53-11e5-8212-5678fc92d702.png)
![login](https://cloud.githubusercontent.com/assets/5063778/13848798/c0ec06de-ec53-11e5-80f1-af6475ebe29b.png)

**Comment by zanglerecke** [comment]
i just saw that in the tray icon, the correct status is displayed, as there is an "abmelden" button.

**Comment by ckamm** [comment]
@zanglerecke I can reproduce the problem. The label of the button is set incorrectly.

**Comment by guruz** [comment]
@zanglerecke Can you please check with http://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5956-nightly20160330-setup.exe ?

(This is a nightly, so please be cautious.. I recommend to try it there, report back and then switch back to a released version)

**Comment by zanglerecke** [comment]
so far i this client works, but!!!! 
our server was fixed too, so i cant tell if that update fixed the button, but i think so.
