### ISSUE TITLE
PDF Data synced down as 0 byte file

### ISSUE THREAD

**Issue by pjrobertson** [owncloud/client#4583]
### Expected behaviour
Desktop client should correctly download synced files from the server
This is a follow on from #1218 since I am still having this problem with the latest software. 

### Actual behaviour
Synced files are downloaded, but have a 0 byte filesize and are empty.

### Steps to reproduce
Unknown 

### Server configuration
Operating system: CentOS 7
Linux 3.10.0-327.4.5.el7.x86_64

Web server: 
Apache 2.4, Owncloud 8.2.3

Database:
MySQL
PHP version:
7.0.3

ownCloud version:
8.2.3

Storage backend:
local

### Client configuration
Client version:
2.1.1

Operating system:
OS X 10.11

### Logs

Client:
Files with 0 bytes is `Paddy工作.pdf` and `护照.pdf`

Here are the relevant logs:
```
03-18 17:18:04:648 0x7fd3b3c45b00 csync_walker: file: /path/Paddy工作.pdf [inode=31548281 size=0]
03-18 17:18:04:648 0x7fd3b3c45b00 _csync_detect_update: Database entry found, compare: 1458285394 <-> 1458285394, etag: (null) <-> 2067f5bbefe4cd83835092bffc761d47, inode: 31548281 <-> 31548281, size: 0 <-> 0, perms:  <-> RDNVW, ignore: 0
03-18 17:18:04:648 0x7fd3b3c45b00 _csync_detect_update: file: path/Paddy工作.pdf, instruction: INSTRUCTION_NONE <<=
[...snip...]
03-18 17:21:39:196 0x7fb4eabc35b0 csync_walker: file: path/护照.pdf [inode=31431473 size=0]
03-18 17:21:39:196 0x7fb4eabc35b0 _csync_detect_update: Database entry found, compare: 1458123862 <-> 1458123862, etag: (null) <-> aa89e77bf74806c8f318ace2c11ed623, inode: 31431473 <-> 31431473, size: 0 <-> 0, perms:  <-> RDNVW, ignore: 0
03-18 17:21:39:196 0x7fb4eabc35b0 _csync_detect_update: file: path/护照.pdf, instruction: INSTRUCTION_NONE <<=
[...snip...CLIENT]
03-18 17:21:42:281 0x7fb4e84215d0 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     client file: path/护照.pdf
[...snip...]
03-18 17:21:42:872 0x7fb4e84215d0 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     client file: path/Paddy工作.pdf
[...snip...SERVER]
03-18 17:21:43:721 0x7fb4e84215d0 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     server file: path/Paddy工作.pdf
[...snip...]
03-18 17:21:43:197 0x7fb4e84215d0 _csync_merge_algorithm_visitor: INSTRUCTION_NONE     server file: path/护照.pdf
```

**Comment by guruz** [comment]
Without log files (server and client) we can't help you.
We need to see where/who thinks a file has 0 bytes.

The client log will for example show if the server claims a size of 0 bytes or if there is a mistake during download.

**Comment by pjrobertson** [comment]
Sorry, I've updated the original message

**Comment by guruz** [comment]
@pjrobertson That part ```file: /```  is from the local discovery with the file already existing locally..
Would you have the remote discovery too? it shows the file with https URL..
(we can focus on one file..)

Although here it looks like too late already because the file had been synced down with 0 bytes already.

If you try to ```PROPFIND``` the ```path``` with curl, what do you get? example here http://stackoverflow.com/a/26676902/2941

Is it always PDF files that are a problem?

And they show up fine in the web?

**Comment by pjrobertson** [comment]
Yep the file is already synced, and I can't predict when it's going to happen again.
Looking through the files - yes I think it's only ever happened with PDFs, and it seems to be a recent thing.

We have 1 client that is using Windows, and I first saw the problem with her client. I re-downloaded the file directly from the server and put it on the Windows client and everything looked fine. A few hours later some (different) files were incorrectly synced on my computer.

Here's the response from the curl command:

```
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/webdav/path/Paddy%e5%b7%a5%e4%bd%9c.pdf</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 18 Mar 2016 07:16:34 GMT</d:getlastmodified><d:getcontentlength>571167</d:getcontentlength><d:resourcetype/><d:getetag>"2067f5bbefe4cd83835092bffc761d47"</d:getetag><d:getcontenttype>application/pdf</d:getcontenttype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>

<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/webdav/path/%e6%8a%a4%e7%85%a7.pdf</d:href><d:propstat><d:prop><d:getlastmodified>Wed, 16 Mar 2016 10:24:22 GMT</d:getlastmodified><d:getcontentlength>0</d:getcontentlength><d:resourcetype/><d:getetag>"aa89e77bf74806c8f318ace2c11ed623"</d:getetag><d:getcontenttype>application/pdf</d:getcontenttype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
```

**Comment by pjrobertson** [comment]
Yep the file is already synced, and I can't predict when it's going to happen again.
Looking through the files - yes I think it's only ever happened with PDFs, and it seems to be a recent thing.

We have 1 client that is using Windows, and I first saw the problem with her client. I re-downloaded the file directly from the server and put it on the Windows client and everything looked fine. A few hours later some (different) files were incorrectly synced on my computer.

Here's the response from the curl command:

```
<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/webdav/path/Paddy%e5%b7%a5%e4%bd%9c.pdf</d:href><d:propstat><d:prop><d:getlastmodified>Fri, 18 Mar 2016 07:16:34 GMT</d:getlastmodified><d:getcontentlength>571167</d:getcontentlength><d:resourcetype/><d:getetag>"2067f5bbefe4cd83835092bffc761d47"</d:getetag><d:getcontenttype>application/pdf</d:getcontenttype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>

<?xml version="1.0" encoding="utf-8"?>
<d:multistatus xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns" xmlns:oc="http://owncloud.org/ns"><d:response><d:href>/remote.php/webdav/path/%e6%8a%a4%e7%85%a7.pdf</d:href><d:propstat><d:prop><d:getlastmodified>Wed, 16 Mar 2016 10:24:22 GMT</d:getlastmodified><d:getcontentlength>0</d:getcontentlength><d:resourcetype/><d:getetag>"aa89e77bf74806c8f318ace2c11ed623"</d:getetag><d:getcontenttype>application/pdf</d:getcontenttype></d:prop><d:status>HTTP/1.1 200 OK</d:status></d:propstat></d:response></d:multistatus>
```

**Comment by guruz** [comment]
For the second file ```%e6%8a%a4%e7%85%a7.pdf``` it claims ```<d:getcontentlength>0</d:getcontentlength>``` for the first one however not.
Hmm. You can also run the ```curl``` command on the directory by the way but you might need to specify ```Depth: 1``` as HTTP header too.

Note that @eillarra @bitsavvy also had problems with PDF files on https://github.com/owncloud/client/issues/4542

**Comment by guruz** [comment]
...and what's the file size on the server hdd?

**Comment by pjrobertson** [comment]
> ...and what's the file size on the server hdd?

Yeah, I was just going to check that. So it seems the `%e6%8a%a4%e7%85%a7.pdf` file (护照.pdf) does have a filesize of 0 bytes on the server HDD, `Paddy%e5%b7%a5%e4%bd%9c.pdf` (Paddy工作.pdf) is listed correctly as 571167 bytes. I'm assuming that some client has re-synced the 0 byte file to the server.

So I tried a few more things to experiment this morning:

I deleted the 0 byte `Paddy工作.pdf` file off my local machine, and saw it got deleted off the server correctly. Putting it back on my local machine meant the 0 byte file was put back on the server.
There are no versions listed for either of the files, so I cannot roll back to the non-0 byte file. I found a `Paddy工作.pdf.d1458285424` in `files_trashbin` on the server and downloaded that (SCP) then reuploaded it using the client. The server now has the actual file synced correctly. I will keep the client log running today and see if it syncs back to 0. If so I can post the logs here.

**Comment by guruz** [comment]
Yes please. For now I'm assuming this is a ownCloud server or setup issue.. :-|

@PVince81 @icewind1991

**Comment by ogoffart** [comment]
> file (护照.pdf) does have a filesize of 0 bytes on the server HDD, Paddy%e5%b7%a5%e4%bd%9c.pdf (Paddy工作.pdf) is listed correctly as 571167 bytes. I'm assuming that some client has re-synced the 0 byte file to the server.

If the client had re-synced the 0 byte file to the server, the size would still be consistant (0) in the server database.
So the only explainaition is that the file has been corrupted on the server and the client downladed the corrupted file as served by the server.

We currently do not check after downloading that the file size is the same as what the PROPFIND returns (we check it is the same as the content lenght) because we assume that it might have changed between the PROPFIND and the download and that it is not a problem.
Maybe we could check only for file that have a size of 0

**Comment by pjrobertson** [comment]
I am still frequently seeing this issue.

Since upgrading to owncloud 9 (I think?) I can see the activity for each file.
For the 0 byte files it says “Changed by XX” in the sidebar showing which user ‘broke’ the file.
I can go to ‘versions’ and restore the file back to its former self without any problems, but the client *does not* re-download the correct file. Instead it sticks with the 0 byte file.

**Comment by ogoffart** [comment]
in 2.2, the client will nor erase a file with a empty file if the server says it should not be empty.

Now, the reason why it was corrupted on the server is still an unkown which is mist likely a server issue.  But as this is not a client issue i close the bug here.  
Another bug should be opened in the server bug tracker with all required information.

**Comment by mvysny** [comment]
This is definitely bot a client and a server issue: client shows a warning that the file downloaded 0-sized yet server said that it should be 4 mb long, yet it happily downloads the file. The server database is apparently screwed:
![screenshot from 2016-10-05 08-59-14](https://cloud.githubusercontent.com/assets/254091/19102629/6835bdc0-8ada-11e6-8835-945600ac6ee7.png)
