### ISSUE TITLE
owncloudcmd test problem: smashbox test_slowwrite.py fails

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#4586]
The CLI owncloudcmd 2.1.1 seems not to check for recently updated files before deciding to PUT: https://github.com/owncloud/client/blame/25baa995ec75f88f050cc4924d0311762a75a836/src/libsync/propagateupload.cpp#L301

When I run the smashbox slowwrite test (which keeps on modifying the file while it is considered for sync: https://github.com/cernbox/smashbox/blob/master/lib/test_slowwrite.py) incomplete file is uploaded. This is a regression comparing to our previous production version (1.7.2) which works as expected and leaves this trace in the logs:

Using QNAM/HTTP parallel code path 
void Mirall::SyncEngine::slotJobCompleted(const Mirall::SyncFileItem&) "81f3f11c9c8107d79161b5ae0ede2f1e" 3 "Local file changed during sync." 

To my surprise the applet version of the client correctly detects this condition. It looks like the owncloudcmd does not behave the same way as owncloud applet client. This is a problem because we rely on automatic testing.

Are some code paths missed in the non-gui version of the client?

**Comment by guruz** [comment]
One difference would be the lack of file watcher in owncloudcmd but I'm not sure if that can explain it..

https://github.com/owncloud/client/blob/51a2e6c5800526e99814a28138e882d373a677bb/src/gui/folderwatcher.cpp#L76

That is before the sync is triggered. The ```Local file changed during sync``` is if the file changes between discovery and propagate or even during propagate itself..

**Comment by ogoffart** [comment]
I think the difference might be that the older owncloudcmd was re-syncing indefinitively when geting this error. While the new limit to 3 syncs.
This can be changed by using `--max-sync-retries 20`  or so.

**Comment by moscicki** [comment]
Thank you, this is indeed a good suggestion. Applied here: https://github.com/cernbox/smashbox/commit/bc38eb799d8927faa103be20e471df66c9f95ab8
