### ISSUE TITLE
Allow specific subfolders to not be synced

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#4589]
### Expected behaviour
I have a development project which has builds folders in which temporary build files are stored. I would like to specifically just exclude these folders from being synced. I cannot do this solely based on the folder name such as "lib" and "obj", because this name is a legit folder name to be synced in another directory (e.g. many pre-compiled libraries are shipped in a "lib" folder, and "obj" can also refer to a folder containing 3D graphics objects).

Sometimes it may also be nice to have a folder-specific ignore list, e.g. I may want to ignore .bak files in one directory but not another.

### Actual behaviour
As far as I can see, there is only a way to exclude folders based on their name but not on their entire location.

### Server configuration
ownCloud version: 9.0.0

### Client configuration
Client version: 2.1.1

Operating system: Windows 7

**Comment by dragotin** [comment]
you can specify the path with the exclude pattern, ie. `devel/my_project/obj` should work, ie. exclude the obj directory in the path.

**Comment by guruz** [comment]
...or uncheck the checkbox https://doc.owncloud.org/desktop/2.1/_images/client6.png

**Comment by sagamusix** [comment]
@guruz: Unchecking that checkbox warns me that the file will be deleted locally, which is the opposite of what I want.
@dragotin: Thanks, I tried it. OwnCloud has not reached the folders in question yet for syncing, but I tried a few combinations and the sub folders "lib" and "obj" are still marked as "to be synced". Do I have to use forward or backward slashes on Windows, or are both okay? What about full absolute path names, do those work too? Sadly the UI is not very clear about this.

**Comment by guruz** [comment]
@sagamusix Yes, right, sorry.
Another thing would be to configure your IDE to do a "shadow build": Have the build directory with lib, obj etc in a completely different folder outside your sync directory.

**Comment by sagamusix** [comment]
Of course that would "work", but it would mean that I had to manually edit the project file of every project I compile, which is not really a feasible solution.

**Comment by sagamusix** [comment]
I tried adding the following rule: "Autosave\*.AutoSave.*.*" but e.g. "Autosave\mega80s-13.it.AutoSave.20160324.000322.it" is still synced.

**Comment by sagamusix** [comment]
I tried adding both "build/obj" and "build\obj" to my ignore list but the build files still got synced. This feature does not seem to work as intended.

**Comment by sagamusix** [comment]
Okay, I finally managed the folders to be ignored. In case anyone else stumbles into a similar problem, specifying */build/obj (rather than build/obj) works.
