### ISSUE TITLE
[windows] Error downloading https://.../status.php - server replied: Service Unavailable

### ISSUE THREAD

**Issue by elfuegobiz** [owncloud/client#4590]
### Expected behaviour
The client should successfully connect to the server.

### Actual behaviour
The client has successfully connected to the server (8.0.3 or so), before upgrading.
When I upgraded it to 8.1.5, the web interface works fine, the client reports:
Error downloading https://.../status.php - server replied: Service Unavailable
While actually the https://.../status.php returns this:
{"installed":true,"maintenance":false,"version":"8.1.5.2","versionstring":"8.1.5","edition":""}

### Steps to reproduce
1. Start client.
2. See the error message.

### Server configuration
Operating system: CentOS 6.7

Web server: apache 2.2

Database: sqlite, postgresql 8.4.20

PHP version: 6.5

ownCloud version: 8.1.5

Storage backend:

### Client configuration
Client version: 2.1.1 (build 5837).

Operating system: Windows 7

OS language: russian

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

Empty.

**Comment by dragotin** [comment]
Please check the servers config.php and see the entry `maintenance`. Probably it is set to true.

**Comment by elfuegobiz** [comment]
If it would be so simple.
But I checked the actual output of the https://.../status.php, and it returns this:
{"installed":true,"maintenance":false,"version":"8.1.5.2","versionstring":"8.1.5","edition":""}

**Comment by elfuegobiz** [comment]
Although the web interface wouldn't work as well, but it works fine.

**Comment by dragotin** [comment]
hmm, do you have a proxy in between that might cache that?

**Comment by elfuegobiz** [comment]
Nope.
And I restarted the client, and the machine containing client, and the VPS containing the server, multiple times each.

**Comment by guruz** [comment]
Restarting the client did not help?

Can you run the client [with logfile enabled](https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly) and paste us that log up to until receiving the error?

**Comment by elfuegobiz** [comment]
I did.
It looks ilke the client uses some cache and it gives an old page version (while actually it doesn't use any cache).

[ow1.txt](https://github.com/owncloud/client/files/182726/ow1.txt)

Mb the client caches the server reply somewhere? Or my apache caches it?

**Comment by elfuegobiz** [comment]
The page reads "PostgreSQL >=9 is required, Update database".
Actually I have tried to upgrade OW to version 9, and this content really was there, but it required new DB version, so I reverted it back to 8.1.5, but the client keeps taking the wrong content.
Mb it makes sense to reinstall the client?

**Comment by elfuegobiz** [comment]
It seems I fixed the problem, but it looks quite weird to me.
For some reason Google Chrome showed the web-interface well, but IE showed only "PostgreSQL >=9 required". The client worked as like as IE. When I fixed this check for PG >=9,everything's get worked.
But I still don't understand, why Chrome showed the web-interface.
