### ISSUE TITLE
[Windows] Sync client 2.1.1 (5837) - Does not update local directory list

### ISSUE THREAD

**Issue by ZSasha** [owncloud/client#4592]
### Expected behaviour
Desctop sync client should pick up all remote changes like creating new directories etc.

### Actual behaviour
Once remote folder was created from Android sync client, it appeared on the server but local windows client did not see the folder and did not synchronize.

### Steps to reproduce
**I have selective sync feature activated - only a subset of remote folders are sync-ed to the local PC.**
This is probably the reason BUT I would expect the client to notify the user that the new folder has been found on the server, otherwise it is not possible to syn the new folder.
**UPDATE**: I can manually PAUSE and UNPAUSE the sync, in that case the new folder is picked up and sync-ed.

1. Open ANDROID Dropbox app
2. Find a file you want to copy to ownCloud account
3. Click on the file and select "Export"
4. Select ownCloud app
5. Enter ownCloud PIN 
6. Create a new folder there
7. Upload the file to the folder
8. Close the app
9. Windows sync client does not see that new folder

### Server configuration
Operating system:
Linux alexcloud 3.10.92 #1 SMP PREEMPT Tue Nov 17 00:15:24 BRST 2015 armv7l armv7l armv7l GNU/Linux

Web server: 
nginx version: nginx/1.9.9

Database:
mysql  Ver 14.14 Distrib 5.5.47, for debian-linux-gnu (armv7l) using readline 6.3

PHP version:
PHP 5.5.9-1ubuntu4.14 (cli) (built: Oct 28 2015 02:04:26)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
    with XCache v3.1.0, Copyright (c) 2005-2013, by mOo
    with Zend OPcache v7.0.3, Copyright (c) 1999-2014, by Zend Technologies
    with XCache Optimizer v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Cacher v3.1.0, Copyright (c) 2005-2013, by mOo
    with XCache Coverager v3.1.0, Copyright (c) 2005-2013, by mOo

ownCloud version:
8.2.2 (stable)

Storage backend:

### Client configuration
Client version:
2.1.1 (build 5837)

Operating system:
Windows 7 x64

OS language:
English

Installation path of client:
C:\Program Files (x86)\ownCloud

### Logs
Alex@alexcloud.flooter.info,      Mon Mar 21 21:45:07 2016 GMT,/Music/Сергей Калугин И _оргия Праведников_ - Танец Казановы [с сайта www.ololo.fm].mp3,  You created Music/Сергей Калугин И _оргия Праведников_ - Танец Казановы [с сайта www.ololo.fm].mp3,                                                       
   Alex@alexcloud.flooter.info,      Mon Mar 21 21:45:07 2016 GMT,/Music/Сергей Калугин И _оргия Праведников_ - Танец Казановы [с сайта www.ololo.fm].mp3,  You created Music/Сергей Калугин И _оргия Праведников_ - Танец Казановы [с сайта www.ololo.fm].mp3,                                                       
   Alex@alexcloud.flooter.info,      Mon Mar 21 21:44:55 2016 GMT,/Music/nol-chelovek_i_koshka.mp3,                                                         You created Music/nol-chelovek_i_koshka.mp3,                                                       
   Alex@alexcloud.flooter.info,      Mon Mar 21 21:44:55 2016 GMT,/Music/nol-chelovek_i_koshka.mp3,                                                         You created Music/nol-chelovek_i_koshka.mp3,                                                       
   Alex@alexcloud.flooter.info,      Mon Mar 21 21:44:25 2016 GMT,   /Music/08 Вечная любовь.mp3,                                                              You created Music/08 Вечная любовь.mp3,                                                       
   Alex@alexcloud.flooter.info,      Mon Mar 21 21:44:25 2016 GMT,   /Music/08 Вечная любовь.mp3,                                                              You created Music/08 Вечная любовь.mp3,                                                       
   Alex@alexcloud.flooter.info,      Mon Mar 21 21:44:13 2016 GMT,                        /Music,You created Music, CameraUpload/20160322_084859.jpg, CameraUpload/20160322_084903.jpg and CameraUpload/20160322_084857.jpg,                                                       
   Alex@alexcloud.flooter.info,      Mon Mar 21 09:03:50 2016 GMT,/Job/Job Searching/Alexander Rikmanis Cover Letter.doc,                                   You changed Job/Job Searching/Alexander Rikmanis Cover Letter.doc,
### 
 ...

**Comment by guruz** [comment]
@ZSasha Do you use external storage on your ownCloud server? Do you use oC file encryption?

@PVince81 Is this a known issue with 8.2.2? ETag update stuff?

**Comment by PVince81** [comment]
No etag problems if no exernal storage

**Comment by dragotin** [comment]
@ZSasha can you reproduce that? If yes, please create a client log file with one failing file.

**Comment by ZSasha** [comment]
Hm... that's strange.
Now I CAN NOT reproduce the issue. Tried all possible ways - everything worked like a charm.
I should say I upgraded my ownCloud server from 8.2.2 to 8.2.3 (stable) just yesterday.
Sorry about that.
I assume this case could be closed now.

Thank you.

**Comment by dragotin** [comment]
@ZSasha thanks for reporting back.
