### ISSUE TITLE
Owncloud client should not sync file write-opened files

### ISSUE THREAD

**Issue by lchanouha** [owncloud/client#4593]
Hello,
Sorry for my English....

### Expected behaviour
owncloud client should never sync file while it is written.

### Actual behaviour
Owncloud client tries to sync file while it's still written by audacity (complete creation in 3 minutes in my case).
At the end I get a conflit file with the proper size and the original file has a size of few mb.
ex, at the end of the export i got: 

export.mp3 3mb <= true name, wrong size
export_conflict[...].mp3 150mb <= wrong name, true size/file

### Steps to reproduce
1. Write directly on a file for several times (ex 3 minutes) on a owncloud synchonized directory 
2. Ex : Audacity / mp3 audio export / 3 minutes

### Server configuration
Operating system:Debian 8
Web server: 2.4.7
Database:5.5.47
PHP version:5.5
ownCloud version: 8.2.3
Storage backend:

### Client configuration
Client version:2.1.1
Operating system: W10
OS language: French
Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

I can provide them but i think there a  this bug is easily reproductible (i got it on my 2 PC). Tell me if i should.

I can add that i never get this problems fews week ago, this bug appeared in an recent client update i think (not server related).

Thanks for your support.

**Comment by guruz** [comment]
This is interesting, we're actually checking if a file is changing size or mtime while we upload it and if yes we abort that upload and try later..

Also it should not create a conflict..

**Comment by ckamm** [comment]
@lchanouha I can't reproduce the problem. For me, continuing to write to a file will abort the file upload. And the fact that you get a *conflict* file hints at something else going wrong.

Could you provide a client log file? https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly

**Comment by ckamm** [comment]
For the record, I tried this on linux and Windows 7. In Windows, I used
```
for /l %x in (1, 1, 180) do ( echo %x >> growme & timeout /t 1 )
```
to gradually grow a file over 180 seconds. The file only got uploaded at the end, once it was no longer written to every second.

**Comment by ckamm** [comment]
I've also tried saving a large file with audacity on Windows 7 without triggering this kind of issue.

**Comment by lchanouha** [comment]
Crap.
On the first use case, i think the situation is different because the file is open/closed each time you loop. So the mtime is altered at each iteration. I don't know well how Windows handle the modifed time of file being written.

But if you tried with audacity....

I'm pretty sure i have a standard setup. I will try it this evening or tomorrow and send you the logs, because i have this problem each time i export with audacity (perfectly reproductible so).

Thanks for your investigation.

**Comment by lchanouha** [comment]
OK
I made some tests.
I think i have two problems.

I couldn't reproduce the bugs with some test files until i noted that my files were named x_2016_XX_XX.mp3 (date at the end). And the conflict file is created only on theses cases..

Exact name : test_2016_04_04.mp3 <= creates a conflict files (test_2016_04_04_conflict-20160331-214324)
Exact name : test.mp3 => does not create a conflict file

Howewer i still have the problem that** i file is uploaded when still writin**g, according to the picture where i'm exporting my project to "Drop Your Sound test.mp3"
![dl](https://cloud.githubusercontent.com/assets/16241429/14188663/084df5f0-f78a-11e5-8a3b-ce18e2000722.png)

I will send some logs when i found a way to select interessing lines (10k  genereted in 3 min...).

**Comment by ogoffart** [comment]
I would be very surprised that the file name has anything to do with the bug.
The log would indeed be interesting.

Maybe audacity is doing something special so the mtime is not changed as they write?

But in this case there is nothing we can do.

We currently wait for 2 seconds before uploading a file.  What else can we do to detect that a file is still getting modified?

**Comment by dragotin** [comment]
I tried that again with a big mp3 file called *Crossroad Hop.mp3* that I export during sync.
In the logs I can see the following:

In syncrun number 2:
- A new file `Crossroad Hop0.mp3` is detected. (Mind the zero in the name) => INSTRUCTION_NEW
- It is detected as being renamed from `Crossroad Hop.mp3`.
- Later, the upload of `Crossroad Hop0.mp3` is interrupted because it is detected that the size changed, however, the mtime stays the same.

In syncrun number 3:
- File `Crossroad Hop0.mp3` is detected as unchanged => INSTRUCTION_NONE
- File `Crossroad Hop.mp3` is changed but the upload is interrupted for same reason: Size changed, but mtime is the same.

In syncrun number 4:
- File `Crossroad Hop.mp3` is uploaded successfully.
- File `Crossroad Hop0.mp3` should be deleted, but is not existing anymore. It's gone. IT seems that a pot. rename from `Crossroad Hop0.mp3` -> `Crossroad Hop.mp3` is not detected.

I can not produce a conflict. For that to happen, there would have to be a change on the server I guess.
