### ISSUE TITLE
Share dialog checks "share link" check box independently of previous state

### ISSUE THREAD

**Issue by diesl** [owncloud/client#4597]
### Expected behaviour
The **share link** check box should not be automatically checked, but represent the current state. If the file/folder is already shared, have it checked, and leave it unchecked otherwise.

With its current user interface, the dialog is misleading in another way. It should have an **Ok** button and a **Cancel** button instead of the **Close** button. The **Close** button saves the new state even if you only want to have a look at the current share status. The same happens with the red close button in the upper right corner.

### Actual behaviour
The file/folder gets shared because the **share link** check box gets checked automatically. As a result, the current share state can not be resolved by the user.

### Steps to reproduce
1. Create file/folder
2. Click **share via owncloud** in the context menu of the file/folder
3. Click **Close** button
4. The file/folder is shared

### Server configuration
ownCloud version: 7.0.2

### Client configuration
Client version: 2.1.1 build 5837

Operating system: Windows 10

OS language: German

Installation path of client: C:\Program Files (x86)\ownCloud

**Comment by guruz** [comment]
@diesl Are you sure this is not for a file which you already shared? (in the webinterface or anywhere else..)

**Comment by rullzer** [comment]
What is your ownCloud server version?

Starting from 8.2 (when user/group sharing was introduced). We do no default action.
If no user/group sharing is enabled then this is the default behaviour.

Also note that all actions are direct. Else error reporting would be very weird if only actions were executed on pressing OK. If there is an error how will you explain to the users what went wrong. Which of his changes etc.

**Comment by diesl** [comment]
I added the owncloud version to the issue description

@guruz: Yes I checked this and tried with newly created files too. In the web interface, I can see the files and folders marked with a *shared x minutes ago*.

@rullzer: Are you sure it was 8.2? Because I can use the sharing feature in 7.0. I get your point with the direct action. The **Close** button itself is ok, but problematic when the current state gets modified when bringing up the dialog. So what happens is this: The share dialog window opens, the spinning wheel appears and shortly afterwards the options are displayed, with the **share link** option checked.

**Comment by rullzer** [comment]
@diesl Yes I'm sure. Only in 8.2 can you share with users/groups. Before that only links.

There was some dicsussion as how to handle the links only (which was available earlier). And eventually it was decided that if only link sharing is available opening the share dialog will create a share. As most of the time this is what the user want to do.

**Comment by diesl** [comment]
I can share files with other users using the web interface. Maybe we mean two different things or the user sharing feature has been extended in 8.2?

Well if this has been decided then that's it. Although I still think this is not a good decision because of the mentioned problem with either a missing cancel button or losing/not knowing the previous state.

**Comment by rullzer** [comment]
I mean from the client. From the web you can indeed.

Ok lets close this then. Your problem will be solved once you upgrade owncloud ;)
