### ISSUE TITLE
Lock requests initiated from the web client are not respected on Windows

### ISSUE THREAD

**Issue by chaoscommencer** [owncloud/client#4598]
### Expected behaviour
Files should be locked (no write access permitted including visual cue) so they cannot be edited remotely.

### Actual behaviour
After initiating a lock from the web client, someone working on Windows can still go and change the file, and it will sync (even though it's supposed to be locked).

### Steps to reproduce
1. Open Web Client.
2. Lock a file.
3. Change that file from a synced machine and save it.

[Will try to post an update with missing information later, but this was tested last week, so this issue likely exists in the most recent version of the software]

### Server configuration
Operating system: 

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend:

### Client configuration
Client version:

Operating system: Windows 10

OS language:

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by chaoscommencer** [comment]
### Update
This "bug" is related to the Workin2gether plugin for the server, which allows users to "lock" files via the web client.

To clarify on the goals, I think we would need the client to provide an interface to hook into a pre-upload/pre-sync call.  Plugins for the client would then be able to run checks/other processes prior to uploading (such as the ability to check if the files that need to be uploaded are already locked on the server by another user).  Is such a hook already available?

**Comment by rullzer** [comment]
Well there is really nothing the client can do here.
The plugin is kind of a hack. And does not do actual locking. On top of that we don't export this kind of locking info via webdav so there is no way for the client to know.

**Comment by danimo** [comment]
Works as expected. Quoting https://apps.owncloud.com/content/show.php/Workin2gether+(Lock+files+in+WebUI)?content=164016: "This feature is webinterface only."
