### ISSUE TITLE
Syncing files too fast causes the connection to close

### ISSUE THREAD

**Issue by Redsandro** [owncloud/client#4599]
When down- or uploading many small files on a fast internet connection, the server chokes and all connections are closed.

On a slow internet connection, everything keeps going smoothly.

I'm sure I'm not the only one with this problem. The server is http://stackstorage.com so I cannot touch that. My connection is 1000 Mbit.

Is there a way to add a small delay between every up- or download, or another existing solution to this problem?

### Expected behaviour
Don't go creating or accessing files remotely faster than the server can handle.
If the connection closes anyway, don't wait 20 seconds and don't rescan everything; just wait a second and retry where we left off.

### Actual behaviour
After syncing for a couple of seconds, this happens:

![image](https://cloud.githubusercontent.com/assets/1702193/13971511/1a3c9e42-f091-11e5-9ed9-9c90acfc37ac.png)

Then it is 'waiting' for a long time before trying again. Repeat.

It gets the job done eventually, but all this waiting and rescanning takes a lot of time. Manually pause and resume syncing every time speeds this up.

### Client configuration
Client version: `2.1.1`

Operating system: `Ubuntu 14.04.3 3.19.0-32-generic`

OS language: English

**Comment by guruz** [comment]
We had those "Connection Closed" issues for different reasons for a while..
Can you check the settings dialog which Qt version is used by your client?

If you set bandwidth limiting to "automatic" does it work then?

**Comment by Redsandro** [comment]
> Can you check the settings dialog which Qt version is used by your client?

`Built from Git revision eeec89 on Mar 14 2016, 13:33:22 using Qt 4.8.6, OpenSSL 1.0.1f 6 Jan 2014`

> If you set bandwidth limiting to "automatic" does it work then?

Those settings are greyed out. (?)

**Comment by dragotin** [comment]
Yeah, ok. That is a too old Qt version, it contains a bug that causes this problem. 
We recommend to use Qt5.

**Comment by guruz** [comment]
Is Stackstorage providing an ownCloud account for you? Or a hosted ownCloud?
They should also make sure to check their setup.

**Comment by Redsandro** [comment]
> Is Stackstorage providing an ownCloud account for you? Or a hosted ownCloud?

They provide an ownCloud account. Except they call it Stack. And they have a Stack client. Which is just a rebranded ownCloud client. I tried the Stack client too. Looks the same and has the same problem.

> Yeah, ok. That is a too old Qt version, it contains a bug that causes this problem. We recommend to use Qt5.

It's the default in Ubuntu 14.04 LTS. I don't want to go against the distro defaults because that's one sure way to break every other package. But more importantly, isn't Qt a widget toolkit? How does the way widgets are drawn break a connection? It sounds very much like a server problem to me, one that can be prevented by limiting the amount of files per second that are accessed or created on the server. (The problem is not bandwidth. Big files have no problem and go lightning fast.)

**Comment by guruz** [comment]
> How does the way widgets are drawn break a connection? It sounds very much like a server problem to me, one that can be prevented by limiting the amount of files per second that are accessed or created on the server. (The problem is not bandwidth. Big files have no problem and go lightning fast.)

https://doc.qt.io/qt-5/qtnetwork-programming.html
You can doubt what I write, but then you won't get help from me. So that's not a strategy I would advise :)

Setting bandwidth limiting to automatic changes the parallelism to 1. Please try it and report back.
(In general, we recommend going to Qt 5.6)

**Comment by Redsandro** [comment]
I've learned that for me it's more often than not profitable to trust my semi-educated gut-feeling first and accept unexplained statements from strangers second. I try to be polite about it though. :angel: 

> Setting bandwidth limiting to automatic changes the parallelism to 1. Please try it and report back.

Well as I said before, those settings are greyed out. :speak_no_evil:  The Download and Upload bandwidth settings on the Network page are greyed out. How can I enable them? Or are these settings available somewhere else?

> In general, we recommend going to Qt 5.6.

4.8 is the default in Ubuntu 14.04 LTS. It is ill-advised to go against the distro defaults because that's one sure way to break every other package. So since all 14.04 users will have this problem, and the OwnCloud Client is coming from a [14.04-specific repo](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client), can that version be compiled against the recommended QT in stead of requiring that version to be installed?

**Comment by jospoortvliet** [comment]
@Redsandro so, just to be sure, you use the ownCloud client from our 14.04 repository, which as far as I can tell should be built with Qt 5.5 or so and you have this problem?

Or do you use a third-party built client for 14.04?

**Comment by Redsandro** [comment]
Yes, I was under the impression that I was using the one from the 14.04 repo. But since you say it should be built with Qt 5.5, something else might be going on here. Perhaps I'm getting ownCloud from the official Ubuntu repository. That's the only other source. Let me doublecheck my sources.

**Comment by Redsandro** [comment]
```
$ dpkg -s owncloud-client
Package: owncloud-client
Status: install ok installed
Priority: optional
Section: devel
Installed-Size: 2315
Maintainer: Jürgen Weigert <jw@owncloud.com>
Architecture: amd64
Multi-Arch: same
Version: 2.1.1-2.1
Depends: libc6 (>= 2.14), libgcc1 (>= 1:4.1.1), libowncloudsync0 (= 2.1.1-2.1), libqt4-dbus (>= 4:4.5.3), libqt4-network (>= 4:4.7.0~beta1), libqt4-xml (>= 4:4.5.3), libqtcore4 (>= 4:4.8.0), libqtgui4 (>= 4:4.7.0~beta1), libqtkeychain0, libqtwebkit4, libssl1.0.0 (>= 1.0.0), libstdc++6 (>= 4.4.0), libqt4-sql-sqlite, owncloud-client-l10n
Description: The ownCloud sync client - github.com/owncloud/client
 .
 ownCloud client enables you to connect to your private
 ownCloud Server. With it you can create folders in your home
 directory, and keep the contents of those folders synced with your
 ownCloud server. Simply copy a file into the directory and the
 ownCloud Client does the rest.
 .
 ownCloud gives your employees anytime, anywhere access to the files
 they need to get the job done, whether through this desktop application,
 our mobile apps, the web interface, or other WebDAV clients. With it,
 your employees can easily view and share documents and information
 critical to the business, in a secure, flexible and controlled
 architecture. You can easily extend ownCloud with plug-ins from the
 community, or that you build yourself to meet the requirements of
 your infrastructure and business.
 .
 ownCloud - Your Cloud, Your Data, Your Way!  www.owncloud.com
 .
 Authors
 =======
 Duncan Mac-Vicar P. <duncan@kde.org>
 Klaas Freitag <freitag@owncloud.com>
 Daniel Molkentin <danimo@owncloud.com>
```

```
$ dpkg -s owncloud-client | grep Version
Version: 2.1.1-2.1

$ $ apt-cache showpkg owncloud-client | grep 2.1.1-2.1 | grep status
2.1.1-2.1 (/var/lib/apt/lists/download.opensuse.org_repositories_isv:_ownCloud:_desktop_Ubuntu%5f14.04_Packages) (/var/lib/dpkg/status)

$ cat /etc/apt/sources.list.d/owncloud-client.list 
deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/ /
```

Verified. This is from that repo. 

`Built from Git revision eeec89 on Mar 14 2016, 13:33:22 using Qt 4.8.6, OpenSSL 1.0.1f 6 Jan 2014`

**Comment by danimo** [comment]
@jospoortvliet 14.04 comes with Qt 5.1, which is too old.

**Comment by jospoortvliet** [comment]
Ah ok, so we just can't deliver anything on 14.04 that works as their libs are too old. Well, sad answer, but an answer. 'pick a newer platform' might not be an option but it's the only option...

And hope that Snappy becomes the default package handling in Ubuntu ;-)

**Comment by Redsandro** [comment]
> @jospoortvliet: built with Qt 5.5
> @danimo: comes with Qt 5.1

So.. the client can not be statically linked?

**Comment by danimo** [comment]
@dragotin We need to fix this somehow, or remove Ubuntu 14.04 from the supported distro list. Ubuntu 14.04 is still offcially supported.

**Comment by danimo** [comment]
@Redsandro No, Qt on the desktop doesn't lend itself to static compilation. All we can do is roll our own like we do for centos, but that has proven to be very error prone.

**Comment by Redsandro** [comment]
> @Redsandro No, Qt on the desktop doesn't lend itself to static compilation.

Shoot. Is that a limitation of the client code? Because Qt itself can be built statically.

> or remove Ubuntu 14.04 from the supported distro list.

Well that's a bit drastic. This only sucks for the initial sync of many small files on a fast network. After that, everything works fine.

It's a bug, but not a lets-remove-the-repo kind of bug, right?

**Comment by danimo** [comment]
> Shoot. Is that a limitation of the client code? Because Qt itself can be built statically.

No, I know, but only at the sacrifice of certain desktop integration features. Most of us have a certain history with Qt :)

> It's a bug, but not a lets-remove-the-repo kind of bug, right?

More like a "final drop" kind of issue.

**Comment by Redsandro** [comment]
> Most of us have a certain history with Qt :)

Yeah, obviously. Didn't mean to sound disrespectful. Just curious. Thanks for telling me why. :smiley:

**Comment by guruz** [comment]
@Redsandro Another idea would be to run the client with

```OWNCLOUD_MAX_PARALLEL=1 owncloud --logfile -```

That way it should sync only 1 file per time.

**Comment by guruz** [comment]
@Redsandro Did my suggestion help you?

**Comment by Redsandro** [comment]
@guruz I thank you for the suggestion but I couldn't answer yet. Everything has been synced now so I haven't experienced syncing big amounts of files yet. Or payed attention when perhaps I was. Ubuntu 16.04 will be out soon and I guess it will have a non-buggy Qt release. I was meaning to get back to this. But for now I'll close the issue and re-open when I actively see your suggestion not working.
