### ISSUE TITLE
Update sync-exclude.lst to exclude Linux trash

### ISSUE THREAD

**Issue by Redsandro** [owncloud/client#4600]
Trash can end up everywhere, depending on what software is used and what is mounted how. On Linux (Ubuntu/Debian/Mint/Elementary), files are moved to a directory called `.Trash-<user_id>`, e.g. `.Trash-1000`

I would recommend adding entry for that to [`sync-exclude.lst`](https://github.com/owncloud/client/blob/master/sync-exclude.lst):

* `.Trash-*`

There is already an entry for OSX (i.e. `.Trashes`).

**Comment by guruz** [comment]
Done for 2.2.x :)
