### ISSUE TITLE
Files with unknown dates are not synced.

### ISSUE THREAD

**Issue by Redsandro** [owncloud/client#4602]
I saw logs of the same files being ignored again and again every minute.

![image](https://cloud.githubusercontent.com/assets/1702193/13985073/afd1263a-f0fa-11e5-95fd-2be373588125.png)

__Problem 1:__ There is no indication as of why they are being ignored. The log doesn't mention anything, just `Syncrun started`.

Until finally I noticed that - for some reason unknown to me and I don't even know how to reproduce this - these files have unknown dates.

![image](https://cloud.githubusercontent.com/assets/1702193/13985048/8a5bad6c-f0fa-11e5-8d71-da283fab204d.png)

### Expected behaviour
Sync the files anyway. I don't know how to handle this technically, but if the file is not on the server, sync the file. 

Non-exhaustive list of things that the user doesn't quite care about:

* File name has profanity in it
* File extension rhymes with splif
* File date coincides with the birthday of a former German dictator
* File date is unknown

Sync the file, at least if it doesn't exist yet.

### Actual behaviour
Files are ignored.

### Client configuration
Client version: `2.1.1`

Operating system: `Ubuntu 14.04.3`

**Comment by Redsandro** [comment]
Note that these "unknown" dates are shown as `Jan  1  1970` on the console. The start of an era.

\> _* Epoch! *_
< _Bless you!_

**Comment by guruz** [comment]
Thanks :) Please subscribe to https://github.com/owncloud/client/issues/1603
