### ISSUE TITLE
Linux Client sets file permissons to read-only

### ISSUE THREAD

**Issue by somehowdifferent** [owncloud/client#4603]
Hi,

I noticed recently, my file sync on Linux introduces strange artifacts. When syncing a file between different machines, the 'listening' machine, i.e. the computer where no changes have been made to the file, gets the updated version of the file by the owncloud sync client, but with read-only status. Hence after syncing, file permissions need to be reset manually. That's a bit annoying. That wasn't the behaviour in the first place. I guess some owncloud client update introduced this issue.

### How to reproduce:

1. Set up file syncronization on a machine with the linux client. See in client config for details.
2. Create a new file "New-file.txt" in one of the synced folders with the webfrontend of the owncloud server
3. File is synced correctly to your computer.
4. Check permissions on this computer with
`
user@computer:~\Documents$ ls -l New-file.txt
`

### Actual behaviour
`
-r--r--r-- 1 user group 0 Mär 23 12:00 New-file.txt
`
Hence, you have no write permissions anymore. I would have expected something like this:

### Expected behaviour 
`
-rw-rw-r--  1 user group  0 Mär 23 12:00 New-file.txt
`

The sync client shouldn't touch the permissions anyways.

I have 4 different linux machines setup to sync with one account. This used to work normally. Now, I have this read-only behavoir on every of this computers when syncing from another.

### Client configuration
Client version: owncloud-client 2.1.1-1.1
Client operating system: Ubuntu 14.04.4 LTS 64-Bit
Long time ago, on Setup, I configured the client manually via ~/.local/share/data/owncloud/owncloud.cfg by adding the folders at the end

> 
[General]
optionalDesktopNotifications=true
monoIcons=false
> 
[ownCloud]
url=https://some-owncloud-instance.com
http_user=username
authType=http
user=username
http_certificatePasswd=
http_certificatePath=
> 
[Settings]
geometry="@ByteArray(\x1\xd9\xd0\xcb\0\x1\0\0\0\0\x1\xda\0\0\0\xc7\0\0\x5G\0\0\x3\x46\0\0\x1\xe4\0\0\0\xed\0\0\x5=\0\0\x3<\0\0\0\0\0\0)"
> 
[ActivityListHeader]
geometry=@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x3\x30\0\0\0\x5\x1\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x5\0\0\0\xb7\0\0\0\x1\0\0\0\0\0\0\0\xb4\0\0\0\x1\0\0\0\0\0\0\0\x64\0\0\0\x1\0\0\0\0\0\0\0\xe5\0\0\0\x1\0\0\0\0\0\0\0|\0\0\0\x1\0\0\0\0)
> 
[Accounts]
0\Folders\Documents\localPath=/home/user/Documents/
0\Folders\Documents\targetPath=/Documents
0\Folders\Documents\paused=false
0\Folders\Documents\ignoreHiddenFiles=true
0\url=https://some-owncloud-instance.com
0\http_certificatePasswd=
0\http_certificatePath=
0\http_user=username
0\user=username
0\authType=http
version=2
0\Folders\texmf\localPath=/home/user/texmf/
0\Folders\texmf\targetPath=/texmf
0\Folders\texmf\paused=false
0\Folders\texmf\ignoreHiddenFiles=true

This was neccessary, since some new version of the client changed the file structure when selecting the synced folders in the clients GUI. That means instead of syncing the content of /home/user/Documents, a new sublevel was introduced by the client and syncing was applied to /home/user/Documents/Documents. This could be solve by the lines

> 
0\Folders\Documents\localPath=/home/user/Documents/
0\Folders\Documents\targetPath=/Documents

and worked nicely for quite some time. But I guess due to some clients update, now file permissions are affected on syncing. Do I need to add here something?

### Server configuration
Operating system: N/A
Web server: N/A
Database: N/A
PHP version: N/A
ownCloud version (see ownCloud admin page): ownCloud 6.0.3 (stable)
Updated from an older ownCloud or fresh install: N/A
ownCloud log (data/owncloud.log): N/A

Thank you very much for any ideas.

bla

**Comment by guruz** [comment]
Are you sure all machines are on 2.1.1?

Is the directory an ownCloud share that was shared read-only to the listener?

**Comment by guruz** [comment]
Oh. I just see you are using ```ownCloud 6.0.3 (stable)```.
We recently did a fix for such old server versions for this bug. But for this you have to use a nightly build or wait for 2.2..

https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3Anightly&package=owncloud-client

Please comment if that does not fix it.

**Comment by somehowdifferent** [comment]
As proposed, I installed a nightly build from the repo given in your link. I know have version 2.2.0~git-37.1
Creating a file in the webfrontend of the owncloud server is now synced correctly and write permissions are preserved on one client. I need to check the inter-client sync the next days.

Thank you very much. Do you have an idea when v2.2. is going to be published?
bla

PS: This old owncloud instance is the central hosting by our university :-(

**Comment by guruz** [comment]
> Do you have an idea when v2.2. is going to be published?

Unfortunately not. My guess would be end of April / beginning of may.

> PS: This old owncloud instance is the central hosting by our university :-(

Oh, annoying then. Which university is that?

FYI @hodyroff

**Comment by somehowdifferent** [comment]
https://speicherwolke.uni-leipzig.de/
