### ISSUE TITLE
Right-click »Share with ownCloud« not available on folders which have not synced 100% yet

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#4608]
Version 2.1.1

I have a folder with some vacation pictures I want to share with my friends. I just added some new ones which are syncing.

Now I want to right-click and share the link to that folder already, because that’s possible on the web interface as well and there’s really no reason not to. But it’s not possible, the entry is not there in the menu.

For fully synced folders it works.

cc @rullzer

**Comment by guruz** [comment]
(not that it might matter but..) Which plugin do you use? Nautilus?

**Comment by rullzer** [comment]
I remember adding this on purpose... let me think about why again...

**Comment by jancborchardt** [comment]
It’s in Nautilus.

@rullzer even when it’s on purpose in some cases, this where many of the files are already synced is most definitely a case where generating the link should be possible.

**Comment by rullzer** [comment]
Ah, I remember. It was to avoid erros with files. Because you can't share files before they are properly synced. So we need different file and folder handling. Agreed.

**Comment by jancborchardt** [comment]
Even for files though I would say it should be possible to share it when it’s still about to sync. It’s a slightly different issue, but syncing might just take a few seconds or minutes, while the person actually opening the link might take minutes to hours or days.

**Comment by ogoffart** [comment]
We need to make sure that if the file, or folder, is not fully sync'ed, the user rxperience should be as good as possible.

**Comment by ckamm** [comment]
I tested this and it works after minor further adjustments.

**Comment by jnweiger** [comment]
@ckamm can you please re-check....

**Comment by jnweiger** [comment]
# linux mint tara
daily client 20181014 beta1
![grafik](https://user-images.githubusercontent.com/1108546/44100576-ac1c1832-9fe5-11e8-93a2-0245d34bdfe6.png)

BAD
Unchanged: Still seen in 2.5.0daily20181014: The 'Share and 'create public link' entries are not there, when the folder is still doing its initial sync.

**Comment by ckamm** [comment]
This must be an odd corner case, I'm looking into it. The code intends for this ui state to only be shown if the file: is on the server, does have permissions set, and does not have the reshare permission bit.

**Comment by ckamm** [comment]
@jnweiger Works for me now!

**Comment by michaelstingl** [comment]
LGTM

![cursor_and_item-0_and_applevolumeextra_and_airportextra_and_displaysextra](https://user-images.githubusercontent.com/214010/44998359-4e283780-afb5-11e8-9727-3f8afa223904.png)
