### ISSUE TITLE
"Shared" folder in selective sync dialog not sorted

### ISSUE THREAD

**Issue by karlitschek** [owncloud/client#4612]
If you open the selective sync dialog in the client then all the folders are sorted. Except the Shared folder.
Would it be possible to do a sort in the client?
The alternative would be to do a sort on the server side of all WebDAV responses. But I would avoid that for performance reasons.

@msrex FYI

**Comment by guruz** [comment]
We just take what the server gives us.. :)

I don't know how you piece together the info from the DB to generate the WebDAV response, maybe adding ```ORDER BY name``` would really not hurt so much. But I think the "Shared" folder is special?

I'd say we can do this, but isn't the special "Shared" folder legacy anyway..

**Comment by ckamm** [comment]
This seems to apply to more than the "Shared" folder. If someone else shares a folder with a user, that folder is also listed last. I'll look at sorting these directories in the client.

**Comment by mcastroSG** [comment]
Hi hi:

**Steps Executed**

1. As user1 share folder1 with user2
2. Log as user2 at Desktop Client
3. Check at Desktop Client main tab folders order

**Results**

Folder1 appears in a proper order at the tab.

OS X
Client OS: 10.11.4 El capitán
Client Version:  Version 2.2.0beta2 (build 3326)

OS W
Client OS: W10
Client Version:Version 2.2.0beta2 (build 6044).

OS Linux
Client OS: Ubuntu 14.04 LTE
Client Version:Version 2.2.0beta2 (build 1582)

Server OS: Ubuntu 
Server Version: 9.1.0 Alpha
