### ISSUE TITLE
[Windows] No share link in current nightlies

### ISSUE THREAD

**Issue by aronovgj** [owncloud/client#4613]
Not sure if I'm supposed to report issues with nightlies:

![oc](https://cloud.githubusercontent.com/assets/10271770/14063644/1a0b2176-f3db-11e5-92a2-737b7bf5e8fc.PNG)

When right clicking a file and sharing a file I think there should be a check box that you can click to share the link. Has been gone for several versions.

Currently I'm on ownCloud-2.2.0.5949-nightly20160327

**Comment by rullzer** [comment]
Yeah this was a tiny bug. Already fixed by @ckamm
