### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by NykauToutcourt** [owncloud/client#4614]
Hi,

I'm looking for a caching feature for owncloud more than synchronizing. The problem with owncloud and its clones is that the client must have the space required to store all files selected for synchronization, whereas I would like to store way more data than clients can handle and get owncloud to retrieve files upon request and store them temporarily on the local storage. If space is lacking then, just like a cache, the synchronization client would just discard the least-recently/frequently used file from the client's cache in order to satisfy the request.

The feature I look for is actually closer to what proposes coda (https://en.wikipedia.org/wiki/Coda_%28file_system%29) or openAFS (http://openafs.org/). The former doesn't seem to be maintained anymore and the latter lacks support for disconnected operations and their folk redirected me to owncloud. I realize this feature request is (very) far from trivial, but who knows what will come out of this report..

**Comment by RealRancor** [comment]
@NykauToutcourt Right after i had directed you here i remembered that something similar exists in https://github.com/owncloud/client/issues/4341 and is already planned. Maybe this is exactly what you're looking for?

**Comment by danimo** [comment]
That's exactly what the VFS proposal entails. Closing as duplicate.

**Comment by NykauToutcourt** [comment]
Yeah, that is a very good match. I hope this can be implemented in owncloud
