### ISSUE TITLE
Problem on building owncloud client !

### ISSUE THREAD

**Issue by yavama** [owncloud/client#4617]
dhouha@dhouha:~/client-build$ cmake -DCMAKE_BUILD_TYPE="Debug" /home/dhouha/client
-- Build of crashreporter disabled.
-- Found Qt5 core, checking for further dependencies...
CMake Error at cmake/modules/QtVersionAbstraction.cmake:22 (find_package):
  By not providing "FindQt5WebKitWidgets.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5WebKitWidgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5WebKitWidgets"
  with any of the following names:

    Qt5WebKitWidgetsConfig.cmake
    qt5webkitwidgets-config.cmake

  Add the installation prefix of "Qt5WebKitWidgets" to CMAKE_PREFIX_PATH or
  set "Qt5WebKitWidgets_DIR" to a directory containing one of the above
  files.  If "Qt5WebKitWidgets" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:54 (include)

-- Configuring incomplete, errors occurred!
See also "/home/dhouha/client-build/CMakeFiles/CMakeOutput.log".

i'm working on ubuntu 14.04

**Comment by yavama** [comment]
@pierrejochem Help plz :)

**Comment by ogoffart** [comment]
You need QtWebkit dev packages.

**Comment by yavama** [comment]
@ogoffart  how to install it plz

**Comment by yavama** [comment]
@ogoffart i have libqt5webkit5 installed and i still have the same message

**Comment by danimo** [comment]
@yavama First of all, you need the -dev package. Secondly, you cannot build the client with Qt 5.1.0 that comes with 14.04. It has too many issues. That's the reason why the official packages still build with 4.8.

**Comment by yavama** [comment]
@danimo what do you mean with the -dev package plz ? 
what should i do exactlyyy

**Comment by yavama** [comment]
i now got this :

dhouha@dhouha:~/client-build$ cmake -DCMAKE_BUILD_TYPE="Debug" /home/dhouha/client
-- Build of crashreporter disabled.
-- Found Qt5 core, checking for further dependencies...
-- Using Qt 5!
CMake Warning at cmake/modules/QtVersionAbstraction.cmake:75 (find_package):
  By not providing "FindQt5LinguistTools.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5LinguistTools", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5LinguistTools"
  with any of the following names:

    Qt5LinguistToolsConfig.cmake
    qt5linguisttools-config.cmake

  Add the installation prefix of "Qt5LinguistTools" to CMAKE_PREFIX_PATH or
  set "Qt5LinguistTools_DIR" to a directory containing one of the above
  files.  If "Qt5LinguistTools" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  CMakeLists.txt:54 (include)


-- GIT_SHA1 80bd86a305f594c3846822c780f28edd3c860ba2
-- If possible compile me with Qt 5.4 or higher.
CMake Error at /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR) (Required is at least version "1.0.0")
Call Stack (most recent call first):
  /usr/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-2.8/Modules/FindOpenSSL.cmake:313 (find_package_handle_standard_args)
  CMakeLists.txt:147 (find_package)


-- Configuring incomplete, errors occurred!
See also "/home/dhouha/client-build/CMakeFiles/CMakeOutput.log".

**Comment by danimo** [comment]
@yavama Do not waste your time. The Qt 5 package provided with Ubuntu 14.04 is too old. You can fix each of these problems, but it will not help you a single bit. Please follow https://doc.owncloud.org/desktop/2.1/building.html#linux.

**Comment by yavama** [comment]
i'm following this in fact !!

i have a question if you could help me with i would be appreciative : i want to develop on owncloud client 
i need to remove the GUI from it i let only the owncloudcmd (it's for a different use) 
could you guide me how to start developing on ?

**Comment by yavama** [comment]
@danimo 
i've tried with ubuntu 15.10 and i have now this 
i couldn't found the rest of the missing packages
any help ? 

ubuntu@ubuntu-VirtualBox:~/client-build$ cmake -DCMAKE_BUILD_TYPE="Debug" ../client
-- Build of crashreporter disabled.
-- Found Qt5 core, checking for further dependencies...
-- Using Qt 5!
-- GIT_SHA1 98995f45e618a192fe33b3c78060550e2195e632
-- Could NOT find INOTIFY (missing:  INOTIFY_LIBRARY_DIR) 
-- Found SQLite3: /usr/lib/i386-linux-gnu/libsqlite3.so (Required is at least version "3.8.0") 
CMake Warning (dev) at cmake/modules/CheckPrototypeDefinition.cmake:43 (if):
  Policy CMP0054 is not set: Only interpret if() arguments as variables or
  keywords when unquoted.  Run "cmake --help-policy CMP0054" for policy
  details.  Use the cmake_policy command to set the policy and suppress this
  warning.

  Quoted variables like "HAVE_ICONV_CONST" will no longer be dereferenced
  when the policy is set to NEW.  Since the policy is not set the OLD
  behavior will be used.
Call Stack (most recent call first):
  cmake/modules/FindIconv.cmake:55 (check_prototype_definition)
  csync/CMakeLists.txt:22 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found SQLite3: /usr/lib/i386-linux-gnu/libsqlite3.so;/usr/lib/i386-linux-gnu/libsqlite3.so (Required is at least version "3.8.0") 
CMake Warning at shell_integration/CMakeLists.txt:11 (find_package):
  By not providing "FindKF5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "KF5", but
  CMake did not find one.

  Could not find a package configuration file provided by "KF5" (requested
  version 5.16) with any of the following names:

    KF5Config.cmake
    kf5-config.cmake

  Add the installation prefix of "KF5" to CMAKE_PREFIX_PATH or set "KF5_DIR"
  to a directory containing one of the above files.  If "KF5" provides a
  separate development package or SDK, be sure it has been installed.


Dolphin plugin disabled: KDE Frameworks 5.16 not found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/ubuntu/client-build

**Comment by danimo** [comment]
They do not exist in 15.05. Dolphin on there is too old. But you can build without them. Just run make.

It would really be helpful to explain your motivation. What are you trying to achieve and why?

**Comment by yavama** [comment]
i need to make some modification on owncloud client, to remove the GUI part and let only owncloudcmd works.
to mount it to a different electronic card (it's for my end of studies project)
it it possible ?

**Comment by danimo** [comment]
I'd simply fork https://build.opensuse.org/package/show/isv:ownCloud:desktop/owncloud-client and move `/usr/bin/owncloudcmd` to a package of its own (`owncloud-client-cmd`), which only depends on libowncloudsync.

However, that will not remove the X11 library dependency. Getting rid of that is much less trivial, because it requires a refactor of libowncloudsync, which currently backs both the GUI and cmd client and contains X11-dependent classes.

**Comment by yavama** [comment]
could you explain me more what to do ? 
and is there another way ?

**Comment by danimo** [comment]
Sorry, but we cannot provide individual support here. You might try to find us on IRC for a more interactive chat, see https://owncloud.org/support/.
