### ISSUE TITLE
[2.1.1-win7_64] Upload not working: stat failed, CreateFileW failed while Word is running

### ISSUE THREAD

**Issue by faramir** [owncloud/client#4624]
### Expected behaviour
After a while, a file should be synced with server or there should be button/menu item to "force sync".

### Actual behaviour
File is in "Not Synced" tab and will not be synced until ownCloud client restarts.

### Steps to reproduce
1. Open doc synced file in Microsoft Word
2. Modify file and save file without closing Word
3. Modify it again

### Server configuration
Operating system: CentOS

Web server: Apache/2.4.6

Database:

PHP version: 5.4.16

ownCloud version: 8.2

Storage backend:

### Client configuration
Client version: 2.1.1

Operating system: Windows 7 Professional 64-bit

OS language: Polish

Installation path of client: C:\Program Files (x86)\ownCloud\

### Logs

```
03-30 11:36:33:230 0x731b620 csync_vio_local_stat: CreateFileW failed on C:/<OWNCLOUD_DATA>/<PATH>/<FILE_NAME>.doc
03-30 11:36:33:230 0x731b620 csync_vio_stat: Local stat failed, errno 0
03-30 11:36:33:230 0x731b620 _csync_detect_update: <PATH>/<FILE_NAME>.doc excluded  (7)
03-30 11:36:33:230 0x731b620 _csync_detect_update: file: <PATH>/<FILE_NAME>.doc, instruction: INSTRUCTION_IGNORE <<=
```

**Comment by guruz** [comment]
Which version of Word is that?

**Comment by faramir** [comment]
Microsoft Word 2010 (14.0.7167.5001) SP2 MSO (14.0.7166.5000)
part of Microsoft Office Professional Plus 2010

**Comment by dragotin** [comment]
Does it sync after you closed word?

**Comment by faramir** [comment]
No. It sync only after client restart.

**Comment by dragotin** [comment]
ok, that is a regression. While word keeps the file open, syncing is not possible, we know that. But once Word is closed, it should sync it. 

Another question: if you close Word (and the file is not synced) and you copy (for test purposes) another file to the same directory of the word file (to make the client start syncing there) does it pick up the changed word file, too?

**Comment by faramir** [comment]
I haven't see any problems with modifying docx file - looks like the file is synced. 
When I create new file (even empty txt file) after closing Word, both (txt and doc) files are synced. Without closing Word - only txt file is synced.

**Comment by dragotin** [comment]
Are you telling me that there is a *difference* between certain file formats Word is saving? Pls. elaborate.

Ok, the problem that the client has here is that it does not get notified about the fact that Word has released it's lock on the file after Word was closed.

**Comment by faramir** [comment]
Yes, the problem with not syncing file is not present when I'm using docx file. I have been doing the same thing with both formats, and docx file works great, doc file not. I have do the same test 3 times, and every time syncing docx was OK, but with doc file was not.

**Comment by guruz** [comment]
@faramir Could you try 2.2.2?
We've made some changes regarding detection of Office files.

**Comment by faramir** [comment]
After upgrading to 2.2.2, I am not able to reproduce the bug - seems like the bug is fixed now.
