### ISSUE TITLE
owncloudcmd --version : non-zero exit status

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#4626]
Currently on linux this command returns 1:

owncloudcmd --version

Is there any reason for this? It confuses smashbox which assumes 0 = no problem (according to usual convention).

**Comment by guruz** [comment]
For me on OS X this works (also according to the source code I checked)

```
guruz@mgmacbookpro buildmirall $ ./bin/owncloudcmd --version
owncloudcmd version 2.2.0git
guruz@mgmacbookpro buildmirall $ echo $?
0
```

@ogoffart what is it on your Linux?

**Comment by ogoffart** [comment]
returns 0 for me.

**Comment by hodyroff** [comment]
still an issue?

**Comment by guruz** [comment]
I think @SamuAlfageme mentioned that based on the sync return it could return
