### ISSUE TITLE
sync-exclude.lst not working with full folder patterns

### ISSUE THREAD

**Issue by kaeser-sosae** [owncloud/client#4628]
### Expected behaviour

The "Music/iTunes/Album Artwork" folder should be excluded from Sync.
### Actual behaviour

The "Music/iTunes/Album Artwork" folder is synced, including it's entire contents.
### Steps to reproduce
1. Add the following lines to the ~/Library/Application Support/ownCloud/sync-exclude.lst file:

`]*iTunes/Album Artwork/`
`]iTunes/Album Artwork`
`]iTunes/Album Artwork/*`
`]iTunes/Album Artwork/`
`]*iTunes/Album Artwork*`
`]*iTunes/Album Artwork/*`
### Server configuration

Operating system: Ubuntu 14.04.4

Web server: Apache 2.4.7

Database: MySQL 5.5.47

PHP version: 5.5.9

ownCloud version: 9.0.0

Storage backend: SMB
### Client configuration

Client version: 2.1.1 Build 3107

Operating system: OS X 10.10.5

OS language: English

Installation path of client: /Applications/owncloud.app
### Logs

I haven't included any logs, as the folders simply sync and are not excluded.

It's entirely possible that I'm doing something wrong, but the documentation here: https://doc.owncloud.org/desktop/2.1/navigating.html#using-the-ignored-files-editor is not specific enough (for me!).

Cheers

**Comment by guruz** [comment]
What if you just put ```Album Artwork```?

**Comment by dragotin** [comment]
rather `Album Artwork/` to make it only match directories.

**Comment by kaeser-sosae** [comment]
Because I only want the Album Artwork folder inside the iTunes folder to be excluded.

I might have a folder called ~/Desktop/Album Artwork that I want synced. If I do as you suggest, any folder called Album Artwork could be excluded.

Remember that this folder is one example of the Sync not working.

**Comment by guruz** [comment]
@kaeser-sosae Yes, we know that. We want to find out if you have a general exclude problem or only this specific pattern with '/'

**Comment by dragotin** [comment]
Can it be a problem with the space in "Album Artwork"? Does a directory without space in between work as expected?

**Comment by dragotin** [comment]
@kaeser-sosae you need to add the pattern in `sync-exclude.lst` it with a leading slash:
```
/Music/iTunes/Album Artwork
```
will do it. Tested here: If you skip the leading slash, it fails, with it works.

Keeping the issue open because it might make sense to fix that to also work without slash.

**Comment by tuxayo** [comment]
Just to add another case where this feature would be useful: I have a folder named "cargo" inside of a "target" one, the two folder names are too common to safely exclude them.

Actually, in this case the whole "target" folder should be excluded, I would have to exclude "target/cargo" and all the other big folders inside. But that would be a huge improvement anyway.
Another potential solution to handle this case would be to put an `.owncloud-exclude` or `.sync-exclude` file in the folder to exclude. Would that be simpler?
