### ISSUE TITLE
[Linux] owncloud client not authorized after logout

### ISSUE THREAD

**Issue by tincturaginseng** [owncloud/client#4629]
### Actual behaviour
ownCloud client not authorized after logout. Delete and re-add account work fine until you logout. After logout I can't login

### Steps to reproduce
1. Add new account
2. Make sure that the data are synchronized
3. Log out from the account
4. Try to log in again

### Client configuration
Client version: 2.1.1-2
Libs version: qtkeychain 0.6-2
Operating system: Arch Linux x86_64
OS language: ru_RU.UTF-8

### Logs
https://gist.github.com/tincturaginseng/145a40f651ade488ffd2da69e33fbf23

### Links
Bug on bugs.archlinux.org - https://bugs.archlinux.org/task/48764

**Comment by kay-inge** [comment]
I can confirm that it's not necessary to logout and re-login. This issue is also there by simply quit the Client and restart.

**Comment by protist** [comment]
Same here. Updated to qtkeychain 0.6-2 and owncloud-client 2.1.1-2 (on Arch Linux), and I cannot log in with the Owncloud client any more. Error log [here](https://gist.github.com/protist/1258be35d2e97575d1f0e062c84feb9c). Can confirm that deleting the account and re-adding fixes it… until the next log out or quit.

**Comment by EmberQuill** [comment]
Same here, also on Arch. Any time the client gets logged out, either through the UI, restarting the client, restarting the computer, etc., it fails to connect until I delete and re-add the account. Then the same thing happens the next time it logs out.

**Comment by tptb** [comment]
Deleting the stored password from the kde wallet has the same effect as re-adding the account.

**Comment by tincturaginseng** [comment]
Downgrade to qtkeychain 0.5-2 and owncloud-client 2.1.1-1 restores efficiency of owncloud-client

**Comment by blizzz** [comment]
Same when rebuilding from source. Apparently incompatibilities brought by the qtkeychain release.

**Comment by ogoe** [comment]
qtkeychain 0.6.1-1 was just released. It seems to fix the problem. At least for me.

**Comment by EmberQuill** [comment]
Yep, the latest qtkeychain fixed it for me, too.

**Comment by xxdochousexx** [comment]
I don't know if it's the right place but the windows client has the same issue. I use Atch Linux and Windows 10 as well... whilest for Linux that qtkeychain seems to have solved the problem it still persists on windows.

**Comment by tincturaginseng** [comment]
Confirm. Update [qtkeychain] to 0.6.1-1 fix this problem for me.
