### ISSUE TITLE
Add "pause sync" action to the context menu (right click menu) of docked desktop client

### ISSUE THREAD

**Issue by arkascha** [owncloud/client#4634]
One of the often used functions for the desktop client is to pause the sync action. Various reasons, for example to prevent a big download from being delayed, playing an online game, receiving some multimedia stream, doing network analysis, ...

### Expected behaviour
I expect a frequently used function to be easily available. 
The intuitive place from a UX point of view obviously is the context menu (right click menu) of the docked client. 

### Actual behaviour
The option is not offered at that intuitive place. 
Instead it is buried deep inside the settings dialog behind non description "dots icon".

**Comment by dragotin** [comment]
@jancborchardt please

**Comment by arkascha** [comment]
OK, looks like this was missing in version 2.1 but has already been implemented in current master? 
This probably is the PR: https://github.com/owncloud/client/issues/3829
Saw this in the source code when I checked where to implement that myself :-)

So will this be part of version 2.2?

**Comment by guruz** [comment]
Already implemented :)
nightly builds are at http://download.owncloud.com/desktop/daily/
