### ISSUE TITLE
Executable not found on QT

### ISSUE THREAD

**Issue by yavama** [owncloud/client#4636]
I've built the client on ubuntu 15.10 and now i have problem with QT 
I couldn't compile the project because of the missing executable 
how to compile it ?

**Comment by guruz** [comment]
Hi, this is an issue tracker for bugs/feature requests, not compile help.
Please try the forum or the IRC channel #owncloud-client-dev on freenode
https://doc.owncloud.org/desktop/2.1/building.html
https://owncloud.org/support/
