### ISSUE TITLE
Missing opt-qt5-webkit in RHEL_7 repo

### ISSUE THREAD

**Issue by jshaeffer9** [owncloud/client#4642]
After doing the following:
```
cd /etc/yum.repos.d/
wget http://download.opensuse.org/repositories/isv:ownCloud:desktop/RHEL_7/isv:ownCloud:desktop.repo
yum install owncloud-client
```
I receive the following error:
```
Error: Package: owncloud-client-2.1.1-2.5.x86_64 (isv_ownCloud_desktop)
           Requires: opt-qt5-qtwebkit
```

**Comment by jnweiger** [comment]
When following the CentOS_7 instructions on 
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adesktop&package=owncloud-client
I get opt-qt5-qtwebkit       x86_64 5.4.2-2.3    installed as a dependency.
Looks good on my side.

@jshaeffer9 can you please recheck, if that was a temporary outage?

**Comment by jnweiger** [comment]
Please re-open, if it happens again. I cannot reproduce the issue.

**Comment by jshaeffer9** [comment]
The opt-qt5-webkit package is missing in the RHEL_7 repo...
[http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/RHEL_7/x86_64/](http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/RHEL_7/x86_64/)

**Comment by jnweiger** [comment]
the packagage built fine, but failed to to publish.
It showed a gear instead of a van saying 'build job exists'
https://build.opensuse.org/package/binaries/isv:ownCloud:desktop/qt5-qtwebkit?repository=CentOS_7

Wiping package, retriggering build. Now it says building. Maybe that helps to convince obs that it should do a complete job.

**Comment by jnweiger** [comment]
The build for RHEL_7 completed successfully. OBS says published, but I still cannot see it in the download repo.

**Comment by jshaeffer9** [comment]
The opt-qt5-webkit package is there now.
