### ISSUE TITLE
How to change logo in owncloud windows client with my own? 

### ISSUE THREAD

**Issue by stoilyanchev** [owncloud/client#4643]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend:

### Client configuration
Client version:

Operating system:

OS language:

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by LukasReschke** [comment]
This is a bug tracker. owncloud.org/support

**Comment by danimo** [comment]
This tracker is designated to track issues with the ownCloud desktop client. It is not a support forum. Please check http://owncloud.org/support. In particular, ownCloud Inc offers easy branding as part of their enterprise subscription.
