### ISSUE TITLE
Sync client stopped syncing after i connected an OFFLINE smb share to the ownCloud server

### ISSUE THREAD

**Issue by ghost** [owncloud/client#4644]
### Expected behaviour

The client should see if there are any differences with the files on the pc and the server and if there are differences it should sync with the server.
### Actual behaviour

The client looks for any differences and it stops working.
### Steps to reproduce
1. connect the share with the owncloud server.
2. Restart the client because it won't see any differences with the server.
3. Client doesn't sync anymore

if i remove the smb shares it starts working again.
### Server configuration

Operating system: Ubuntu server 14.04

Web server: apache2

Database: mysql

PHP version: 5.5.9

ownCloud version: 8.1.6

Storage backend:
### Client configuration

Client version: 2.1.1

Operating system: Windows 10

OS language: Dutch

Installation path of client: C:\Program Files (x86)\ownCloud
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   (On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
   (See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

Shows nothing
1. Web server error log: 

https://gist.github.com/thibodelanghe/9988efb24e582fcc1118d2109a88713e
1. ownCloud log (data/owncloud.log):

Exception: {"Message":"Unknown error","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(345): Icewind\SMB\Connection->read()\n#1 \/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Share.php(120): Icewind\SMB\Share->execute('allinfo \"\"')\n#2 \/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(109): Icewind\SMB\Share->stat('\/')\n#3 \/var\/www\/owncloud\/apps\/files_external\/lib\/smb.php(279): OC\Files\Storage\SMB->getFileInfo('')\n#4 \/var\/www\/owncloud\/lib\/private\/files\/storage\/common.php(90): OC\Files\Storage\SMB->filetype('')\n#5 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(98): OC\Files\Storage\Common->is_dir('')\n#6 \/var\/www\/owncloud\/lib\/private\/files\/storage\/wrapper\/wrapper.php(98): OC\Files\Storage\Wrapper\Wrapper->is_dir('')\n#7 \/var\/www\/owncloud\/lib\/private\/files\/cache\/watcher.php(90): OC\Files\Storage\Wrapper\Wrapper->is_dir('')\n#8 \/var\/www\/owncloud\/lib\/private\/files\/view.php(1187): OC\Files\Cache\Watcher->checkUpdate('', Array)\n#9 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/objecttree.php(148): OC\Files\View->getFileInfo('Server 03 ( Bac...')\n#10 \/var\/www\/owncloud\/lib\/private\/connector\/sabre\/custompropertiesbackend.php(101): OC\Connector\Sabre\ObjectTree->getNodeForPath('Server 03 ( Bac...')\n#11 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/PropertyStorage\/Plugin.php(86): OC\Connector\Sabre\CustomPropertiesBackend->propFind('Server 03 ( Bac...', Object(Sabre\DAV\PropFind))\n#12 [internal function]: Sabre\DAV\PropertyStorage\Plugin->propFind(Object(Sabre\DAV\PropFind), Object(OC\Connector\Sabre\Directory))\n#13 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#14 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1016): Sabre\Event\EventEmitter->emit('propFind', Array)\n#15 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(936): Sabre\DAV\Server->getPropertiesByNode(Object(Sabre\DAV\PropFind), Object(OC\Connector\Sabre\Directory))\n#16 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(327): Sabre\DAV\Server->getPropertiesForPath('', Array, 1)\n#17 [internal function]: Sabre\DAV\CorePlugin->httpPropfind(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#18 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#19 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(469): Sabre\Event\EventEmitter->emit('method:PROPFIND', Array)\n#20 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#21 \/var\/www\/owncloud\/apps\/files\/appinfo\/remote.php(83): Sabre\DAV\Server->exec()\n#22 \/var\/www\/owncloud\/remote.php(132): require_once('\/var\/www\/ownclo...')\n#23 {main}","File":"\/var\/www\/owncloud\/apps\/files_external\/3rdparty\/icewind\/smb\/src\/Connection.php","Line":48}

**Comment by thibodelanghe** [comment]
Found what the problem is! when an smb share is offline the server doesn't sync with the client

**Comment by ogoffart** [comment]
Closing this old issue as it does not seem to be a client bug.
Please open a bug in the core repository, or ask for support in https://owncloud.org/support/
