### ISSUE TITLE
[Linux->Windows cross compile] Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES

### ISSUE THREAD

**Issue by kramer65** [owncloud/client#4647]
### Expected behaviour
I've installed openSUSE 42.1 and followed all the steps outlined in the [cross compile windows installer build instructions](https://doc.owncloud.org/desktop/2.0/building.html#windows-installer-build-cross-compile). When finally running the following command:

    cmake -DCMAKE_BUILD_TYPE="Debug" ../client -DCMAKE_TOOLCHAIN_FILE=../client/admin/win/Toolchain-mingw32-openSUSE.cmake

I expect it to build properly

### Actual behaviour
But instead of building properly I get the following error:

> CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
>   Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
>   system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
>   OPENSSL_INCLUDE_DIR) (Required is at least version "1.0.0")

I found [this issue](https://github.com/owncloud/client/issues/3455), which listed running `sudo zypper install mingw32-openssl-devel` as a solution, but unfortunately I get the following error:

    Package 'mingw32-openssl-devel' not found.

Does anybody know what I could be doing wrong here? And most importantly, does anybody know how I can solve this? All tips are welcome!

### Server configuration
Operating system: openSUSE Leap 42.1

### Client configuration
Client version: last git commit

**Comment by guruz** [comment]
Hi, this is an issue tracker for bugs/feature requests, not compile help. You could also try to compile natively on Win32.

Please try the forum or the IRC channel #owncloud-client-dev on freenode
https://doc.owncloud.org/desktop/2.1/building.html
https://owncloud.org/support/
https://doc.owncloud.org/server/8.2/admin_manual/enterprise_clients/creating_branded_apps.html

**Comment by kramer65** [comment]
@guruz - Ah, excuse me for that. Thanks for the links. I'll try it there.
