### ISSUE TITLE
phantom filesystem | sync  - only upload 

### ISSUE THREAD

**Issue by indianamorlock** [owncloud/client#4649]
### Expected behaviour

I wish the client would make a replica of the whole SERVER directory and files but as a representation, so I could actually move around objects on my clients without having to sync all of them.

Usability... .For instance:

CHANGING STRUCTURE
If you would like change the directory structure from your ownCloud client on your OS and not from the Server (web), you should be syncing all the complete tree with all the files involved.

UPLOADING CONTENT from DIFFERENT COMPUTERS (using different internet connections):
If you would want to only upload files to a new folder inside an already existing folders where there are files already, you should be able to UPLOAD without having to download content first

[NOTE
When setup an existing account on your desktop client, the client retrieves the server folders and shows the complete tree directory and its size as you expand each child, but you don't now whether there are files...]
### Actual behaviour

Instead, if I want to upload new content from my clients, I have to be really careful to sign in from the web, make all necessary changes on the folder structures so I don't have files laying around in order to only sync a new empty SUB-directory where I woulde be syncing/UPLOADING new files to.
### Steps to reproduce
1.  Create a FOLDER, put some files in it
2.  Create a SUBFOLDER, put some files in it
3.  Create a SUB-SUBFOLDER, put some files in it
4. Now try to upload "A_Bunch_Of_Files" to a >NEW_FOLDER< that would be located under:

Example1:
![github_owncloudevidence2](https://cloud.githubusercontent.com/assets/11155021/14358862/4923f300-fcc5-11e5-951e-99369f3f9319.png)

Example2
![github_owncloudevidence3](https://cloud.githubusercontent.com/assets/11155021/14358870/53fc462e-fcc5-11e5-9964-38fba4be16b8.png)

5) . In order to UPLOAD content to a NEW_FOLDER I would have to sync all their father, IMAGINE if you had GBs of DATA you don't want... even worst if you  bandwidth is lame.

For instance, I have attached an image  of my sync client to to show what I mean:

I have the MI3w Galery where I put my phones pictures and videos, and I sync from whichever computer I have at hands:

So I in order to put new items in, i had to move all the pictures and movies to a folder I named "Ordernar" and added a new folder where I would sync UPLOAD the new content.
![github_owncloudevidence](https://cloud.githubusercontent.com/assets/11155021/14358685/749ea616-fcc4-11e5-98fa-cb045937954b.png)
### Server configuration

Operating system:  Linux
Web server: Apache
Database: MySQL 5.4
PHP version: 5.4.x
ownCloud version: 8.2.3
### Client configuration

Client version: 2.1.0 (build 5683)
Operating system: Windows 7 Enterprise Edition x64
OS language: English

**Comment by guruz** [comment]
Would this be https://github.com/owncloud/client/issues/4341 ?

**Comment by indianamorlock** [comment]
> "The selective sync UI currently only allows excluding files. If you have the structure a/b/c, and you want the directory a/b/c/d1, but not a/b/c/d2, the UI will allow you to deselect d2, but if d3 appears it will be synced by default. There is no way to say that you just want a/b/c/d1, you can only say I don't want all other files, and you need to update this list every time a new folder appears."

> "We could provide a way to include and exclude folders, so that you can exclude a/b/c, but override this by then including only its a/b/c/d1 child, thus also excluding d3 by default when it appears. The control panel for the indexing service on Windows is an example of a UI that allows this. It's a bit more complicated, but allows to have both an include and exclude hierarchy."

It sort of is... So maybe I could break it down to 3 different features:

1) Being able to only get the selected child items/folders
2) Be able to ONLY UPLOAD
3) To accomplish the above 2, I would get a symbolical representation of all structure/files (0 byte?), and have them visually appearing transparent - Grayed (like hidden files in windows), visually you know they are like ghosts, thus, integrating a shell extension or having a pop-up windows so that you could "Sync - Selected". 
3a) So initially you'd get this "ghost" server replica locally, and with it you could already manipulate files from here to there without involving downloads or uploads, things would happen on the server side and refreshed on the client.

I think this would really improve usability, like you could easily make logical changes on the way you organize your files and folders doing it from the client OS, like, for instance, Ok... where do I have all the *.pdf files ?? ---> and take some action, so where are the *.mp3.. etc etc... Tidy.

I have like 500GBs I need to reorder for example because I just have been backing up from different sources (computers) so I would want to re.group, categorize, organize... but doing if from the web is not the safest way to re-arrange files (move, rename, delete)

At your disposition!

Best Regards!

**Comment by indianamorlock** [comment]
2 years later I still think that there no competitor that would do such a thing.. and it would be a feature that no one else provides out there... it's like having a replica of the database for your users locally, and then replicating those changes (whether they be only structural or both: data & structure) to the server!

**Comment by guruz** [comment]
Since the ownCloud server supports acting as a WebDAV server, maybe you can find a good WebDAV client to do this?

**Comment by indianamorlock** [comment]
-touché!- so moving around items through WebDav interface would act as desired? for example re-ordering (moving folder & files) between distinct directory trees ? ... I feel so dumb now... hahah. I love you!

**Comment by guruz** [comment]
:-)))
And I feel dumb for not suggesting this earlier. I hope it can solve the issues you had..

**Comment by indianamorlock** [comment]
![image](https://user-images.githubusercontent.com/11155021/60318895-0bbc5680-994b-11e9-8a82-f6ce4c6b8531.png)

Actually this is what I was talking about! <3  I haven't tried it yet... I see there are a lot of erros around it still

**Comment by guruz** [comment]
@indianamorlock Which version is that screenshot from? A beta1 should come out soon that has even better support for this :)

**Comment by indianamorlock** [comment]
![image](https://user-images.githubusercontent.com/11155021/60670648-961f2180-9e47-11e9-8ff0-d4efc9b36bc7.png)

Oh im on the stable release!
