### ISSUE TITLE
[OS X El capitán] Overlay icons and option share with owncloud missing.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/client#4650]
## Steps to reproduce

Having connected a server to the client do:
1. In the systray right click, open owncloud folder.
2. Right click on a folder.

## Expected behaviour
There is an option called Share with owncloud. There are overlay icons.

## Observed behaviour
No overlay icons, and no option in contextual menu.

![screen shot 2016-04-08 at 09 56 16](https://cloud.githubusercontent.com/assets/9048796/14377825/23eb0ada-fd72-11e5-9fff-badf521b7014.png)

**Client Version**
Version 2.2.0-nightly20160408 (build 3250). 

**Operating system**
OS X  El capitán 10.11.

**Comment by stonerl** [comment]
I'm using ``Version 2.2.0-nightly20160411 (build 3255)`` on ``OSX 10.11.4``and I see the overlay icons and also have the sharing option.

**Comment by guruz** [comment]
i don't know what is special about @SergioBertolinSG  's machine 
we tried to debug it a bit.. in his System Preferences->Extensions the Finder extension is enabled.. so that's not it. Maybe he can check again?
@SergioBertolinSG maube you can run client with ```--logfile -``` and see if someone connects to the client's socketAPI (which is used by the Finder extension)

**Comment by SergioBertolinSG** [comment]
@mcastroSG I guess you are using el capitán, could you check if overlay icons and menu option appear with last desktop version?

**Comment by mcastroSG** [comment]
@SergioBertolinSG , I´ve tested with  OS X El capitán 10.11. and Version 2.2.0-nightly20160411 (build 3255) - testPilot as well as with the production version (2.1.1)

I have the same issue as you, the overlay icons are not shown.

Checking the log file I have not found any evidence of error so any ideas about what could we look for ?  @guruz @stonerl

**Comment by guruz** [comment]
It works for me with one of my custom brandings but not with Version 2.2.0-nightly20160411 (build 3255)...

@mcastroSG Can you double check the System Preferences setting I mentioned above?

**Comment by guruz** [comment]
OK it also works with the nightly if I restart Finder.
If you type ```killall Finder``` on the shell or relogin does it work then?

**Comment by mcastroSG** [comment]
Hi hi:

@guruz , I´ve tested: System Preferences->Extensions the Finder extension is enabled. And after a double check, it works. 

This was the only way to make it works again , restart or relogin does not work fine .

Regards

**Comment by guruz** [comment]
@mcastroSG Could you try to remove the ownCloud client, relogin, make sure it does not show up in System Preferences, then re-install and check if the icons will appear?

**Comment by mcastroSG** [comment]
Hi hi:

@guruz 

**Steps:**

1.- Remove ownCloud client.
2.- Relogin.
3.- Check that ownCloud finder extension is not shown at System Preferences > Extensions.
4.- Re-install ownCloud client and check that overlay and Sharing Menu is shown.

Version 2.1.1 (build 3107) --> Works fine
Version 2.2.0-nightly20160415 (build 3268) --> Did not work

Regards

**Comment by guruz** [comment]
> 3.- Check that ownCloud finder extension is not shown at System Preferences > Extensions.

Was it not _shown_ or not _checked_ ?

**Comment by mcastroSG** [comment]
Not _shown_ , after uninstall ownCloud, client extension is not shown at System Preferences > Extensions. 

Regards

**Comment by guruz** [comment]
On install:
```
15/04/16 15:18:32,082 pkd[277]: UNINSTALLED:com.owncloud.desktopclient.FinderSyncExt com.owncloud.desktopclient.FinderSyncExt(1.0) D71A711F-DB21-4A7F-925E-E522DBDE8BA0 /Applications/owncloud.app/Contents/PlugIns/FinderSyncExt.appex
15/04/16 15:18:32,083 lsd[255]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
15/04/16 15:18:32,086 pkd[277]: INSTALLED:com.owncloud.desktopclient.FinderSyncExt com.owncloud.desktopclient.FinderSyncExt(1.0) <__NSConcreteUUID 0x7fe6cca253d0> C72B35AC-8AB9-4EF0-9FE9-0896A0995808 /Applications/owncloud.app/Contents/PlugIns/FinderSyncExt.appex
15/04/16 15:18:32,135 lsd[255]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
15/04/16 15:18:32,137 pkd[277]: UNINSTALLED:com.owncloud.desktopclient.FinderSyncExt com.owncloud.desktopclient.FinderSyncExt(1.0) C72B35AC-8AB9-4EF0-9FE9-0896A0995808 /Applications/owncloud.app/Contents/PlugIns/FinderSyncExt.appex
15/04/16 15:18:32,139 pkd[277]: INSTALLED:com.owncloud.desktopclient.FinderSyncExt com.owncloud.desktopclient.FinderSyncExt(1.0) <__NSConcreteUUID 0x7fe6ccb0d870> 5781FFD0-8FA5-4F73-8686-CE506E325FCF /Applications/owncloud.app/Contents/PlugIns/FinderSyncExt.appex
15/04/16 15:18:32,220 lsd[255]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
15/04/16 15:18:32,230 pkd[277]: UNINSTALLED:com.owncloud.desktopclient.FinderSyncExt com.owncloud.desktopclient.FinderSyncExt(1.0) 5781FFD0-8FA5-4F73-8686-CE506E325FCF /Applications/owncloud.app/Contents/PlugIns/FinderSyncExt.appex
15/04/16 15:18:32,231 pkd[277]: INSTALLED:com.owncloud.desktopclient.FinderSyncExt com.owncloud.desktopclient.FinderSyncExt(1.0) <__NSConcreteUUID 0x7fe6cb57c390> E241CE05-352A-4E19-B2CA-B95467BCEFA3 /Applications/owncloud.app/Contents/PlugIns/FinderSyncExt.appex
15/04/16 15:18:32,234 lsd[255]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
15/04/16 15:18:32,240 lsd[255]: LaunchServices: Could not store lsd-identifiers file at /private/var/db/lsd/com.apple.lsdschemes.plist
15/04/16 15:18:32,941 pkd[277]: UNINSTALLED:com.owncloud.desktopclient.FinderSyncExt com.owncloud.desktopclient.FinderSyncExt(1.0) D23057A5-270B-4751-9CCC-03077FEA7DB8 /Applications/owncloud.app/Contents/PlugIns/FinderSyncExt.appex
```

Seems our code in ```post_install.sh``` does not work anymore..
Even if I install multiple times (keeping the extension registered) it does not enable it (in System Preferences, you need to click somewhere else e.g. "Today" and then back to "Finder" to see changes).

If I call ``` pluginkit -e use -i com.owncloud.desktopclient.FinderSyncExt``` manually on the shell it works. Heh.

**Comment by guruz** [comment]
@mcastroSG When testing this make sure the checkbox is removed/unchecked (also try to switch between "Today" and "Finder") before installing.. thx :)
Would be good if @SergioBertolinSG tries it too so we have multiple machines testing.

**Comment by stonerl** [comment]
Just one question. Does Dropbox display the overlay icons on your machines?

**Comment by SergioBertolinSG** [comment]
Hi, @guruz retested with last build (3278). No overlay icons appear. I've shared some logs with you on S3.

**Comment by stonerl** [comment]
Maybe another program is blocking the icons e.g. GoogleDrive. See here: https://www.dropboxforum.com/hc/en-us/community/posts/205084383-Desktop-not-showing-file-sync-progress

**Comment by SergioBertolinSG** [comment]
> Just one question. Does Dropbox display the overlay icons on your machines?

Just tried, yes It shows its icons:

<img src="https://cloud.githubusercontent.com/assets/9048796/14597835/732e728c-054f-11e6-8aa7-8a369c80370c.png" width="48">

**Comment by stonerl** [comment]
I think the problems could that you have either GoogleDrive or ownCloud .tespilot installed parallel. Here is what I observed With Google Drive and ownCloud. I disable both Extensions from the System Prefrences are shown. Then I enable the ownCloud extension; the icons appear for owncloud. I leave ownCloud enabled and enable the GoogleDrive Extension; the GoogleDrive icons appear and I can still see the ownCloud Icons.

Then I disabled both extensions and enabled the GoogleDrive Extension first; the icons appear. The I enabled the ownCloud Extension and no icons appeared. After disabling the GoogleDrive Extension the ownCloud Icons appeared. 

I think the problem could be the following. Here is Apples Guidline for the Property List [1]:

```
    <key>NSExtension</key>
    <dict>
        <key>NSExtensionAttributes</key>
        <dict/>
        <key>NSExtensionPointIdentifier</key>
        <string>com.apple.FinderSync</string>
        <key>NSExtensionPrincipalClass</key>
        <string>$(PRODUCT_MODULE_NAME).FinderSync</string>
    </dict>
```
Here is GoogleDrives Info.plist
```
	<key>NSExtension</key>
	<dict>
		<key>NSExtensionAttributes</key>
		<dict/>
		<key>NSExtensionPointIdentifier</key>
		<string>com.apple.FinderSync</string>
		<key>NSExtensionPrincipalClass</key>
		<string>FinderSync</string>
	</dict>
```
And this is ownClouds and ownCloud-testpilot:

```
	<key>NSExtension</key>
	<dict>
		<key>NSExtensionAttributes</key>
		<dict/>
		<key>NSExtensionPointIdentifier</key>
		<string>com.apple.FinderSync</string>
		<key>NSExtensionPrincipalClass</key>
		<string>FinderSync</string>
	</dict>
```
ownCloud, ownCloud-testpilot and GoogleDrive use the same ```NSExtensionPrincipalClass``` and Apple expects you to use ```$(PRODUCT_MODULE_NAME).FinderSync```.

So maybe, because three programs use the same value this strange behavior happens. 

[1] https://developer.apple.com/library/ios/documentation/General/Conceptual/ExtensibilityPG/Finder.html

**Comment by SergioBertolinSG** [comment]
I never had google drive client installed. ownCloud official client was uninstalled before testing with testcloudpilot.

**Comment by guruz** [comment]
@stonerl Thanks for digging into this, but we found the cause is another one..

@dragotin @danimo it failed because the testpilot-builds are not signed (normal ownCloud builds are). If we create a signed build it works for @mcastroSG and me ..
I'll work with @danimo later to change the signing default..

**Comment by stonerl** [comment]
@guruz 

What about the problem with GoogleDrive, shall I open a new Issue.

**Comment by guruz** [comment]
@stonerl Yes please, sorry.
Please also clarify if you're talking about having GoogleDrive client and ownCloud client on the _same_ sync directory (because we don't officially support/test that)

**Comment by guruz** [comment]
@SergioBertolinSG @mcastroSG Nightlies of testpilot are out.. http://download.owncloud.com/desktop/daily/testpilotcloud-2.2.0.3282-nightly20160419.pkg
They should be signed and then icons should work.

**Comment by mcastroSG** [comment]
@guruz  works fine  ;)

**Comment by SergioBertolinSG** [comment]
Works 👍
