### ISSUE TITLE
Notifications are not shown when activity app is disabled in the server.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/client#4651]
## Steps to reproduce

Having connected a server to the client do:
1. Disable activity app in the server.
2. Enable announcements app in the server.
3. Run cron.php in the server.
4. Sync desktop client using admin user.
5. Create a notification with another user "admin2" included in admin group.
6. Open desktop client. Look for notifications.

## Expected behaviour
You find somewhere the notifications. 

## Observed behaviour
Notifications are not there.

(They would be in activity tab if it were enabled in the server).

**Client Version**
Version 2.2.0-nightly20160408 (build 3250). 

**Operating system**
OS X  El capitán 10.11.
Windows 10.

**Comment by nickvergessen** [comment]
Side note, many bigger installations have activities disabled due to the performance slow done it causes for actions on shared files

**Comment by ckamm** [comment]
Testing:
* The `Server Activity` tab did appear when a notification was received
* When I have a single account to a server that has `activity` disabled, the `Server Activity` tab is still shown. It goes away when I click it.

**Comment by ckamm** [comment]
Closing this through the commit was unintentional, but I am done testing this.
