### ISSUE TITLE
[Linux] Checking for changes takes too long

### ISSUE THREAD

**Issue by Firzen7** [owncloud/client#4652]
### Expected behaviour
ownCloud client shoud detect changes in filesystem quickly, and should use full potential of client machine.

### Actual behaviour
After delete of single folder with source codes (2729 files, 47 MiB total) ownCloud client started to check every file in my ownCloud folder where is stored about 40000 files (19 GiB total) with speed of about 4 folders per second, and that is just too slow. It took about 10 minutes to finally notice what changed and delete the folder. My machine has Core i5 CPU and 8 GiB of RAM, but ownCloud client probably uses only one thread, I see no extensive CPU use (only about 10% on every core/thread). It really seems that sync client could detect changes in filesystem by using more resources. For comparison, Dropbox client is able to notice similar change in less than one minute.
Sync client also could have some setting where user could choose how intensively will resources be used.

### Steps to reproduce
I am not very sure how exactly repeat this, but you can try this:
1. Install Debian with many packages.
2. Copy contents of /usr folder to ownCloud folder.
3. Wait for initial sync.
4. Choose random folder and delete it.

### Server configuration
Operating system: Bananian Linux 8 (basically Debian 8 Jessie), kernel: 3.4.108-bananian, arch: armv7l
Web server: apache2 (2.4.10)
Database: mysql (5.5.47)
PHP version: 5.6.19
ownCloud version: 9.0.0 (stable)
Storage backend: Local

### Client configuration
Client version: 2.1.1
Operating system: Debian GNU/Linux 8.3, kernel 3.16.0-4-amd64 (64-bit)
OS language: en_US
Installation path of client: /usr/bin/owncloud

### Logs
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`: http://pastebin.com/c1vsWAED
2. Web server error log: http://pastebin.com/9ttenPtd
3. ownCloud log (data/owncloud.log): nothing useful i think (and only 1 line)

#### Continue your great job and thanks in advance!

**Comment by guruz** [comment]
Just curious: Do you have a SD or HDD?

**Comment by ProjectInfinity** [comment]
@guruz I can confirm similar experience on Linux, Windows and OS X, all running on SSDs.

**Comment by guruz** [comment]
Basically the solution we plan to do is this one: https://github.com/owncloud/client/issues/2297

Please subscribe there.
