### ISSUE TITLE
[Linux] Pause sync via panel applet menu

### ISSUE THREAD

**Issue by keunes** [owncloud/client#4653]
It'd be nice to have a 'pause sync' entry in the top panel applet (?)

Use case: Working on mobile data plan and don't want my pics to be uploaded automatically (I'll resume sync when I'm on cable connection).

### Client configuration
Client version: 2.1 (according to the url when clicking the 'help')
Operating system: Ubuntu 14.04

---
Obviously, this is a feature request :P
Thanks for providing the great system!

**Comment by guruz** [comment]
Thanks, this is done already in 2.2.x

https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3Anightly&package=owncloud-client

**Comment by keunes** [comment]
@guruz Thanks, any idea on when it will end up in the [main repository](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client) (as linked to from the owncloud website)?
