### ISSUE TITLE
Context menu for uploading file and sharing it (files outside sync folder)

### ISSUE THREAD

**Issue by mightyCelu** [owncloud/client#4654]
I use my owncloud often to share arbitrary files. I.e.: I upload the file to a subdirectory ("uploads") and create a share link via the webinterface. 
This use-case could be made easier with a action in a file manager's context menu. It could be implemented in a way that allows to use the (configurable) default behavior without any additional input from the user and copy the share-URL (if any) to the clipboard.

The parameters would be the destination on the server and the sharing parameters, as accessible on the webinterface. The default for me would be: upload to "uploads", and share it (by URL, no password, expires in a week).

I don't know about other users that are looking for a feature like this but it would help me a lot.

**Comment by SamuAlfageme** [comment]
Duplicated of https://github.com/owncloud/client/issues/2732
