### ISSUE TITLE
[Linux] ignores changes to some files (.git folder): when the client is restarted it notices the changed files and uploads them OK

### ISSUE THREAD

**Issue by joysfera** [owncloud/client#4655]
### Expected behaviour
Whenever a file is modified locally it is uploaded to server

### Actual behaviour
Changes in files (in a .git folder) are sometimes ignored

### Steps to reproduce
1. commit something to a local git repository
2. notice that files changed in the .git folder are not being uploaded to server, not even after two hours of waiting to see if the owncloud-client catches up
3. happens sometimes only, started like 4 days ago, before it's been working fine for 3 months, AFAIK

### Server configuration
Operating system: Ubuntu 12.04 LTS

Web server: Apache

Database: MySQL

PHP version: 5.4.45

ownCloud version: 8.2.2-1.1

Storage backend: filesystem

### Client configuration
Client version: 2.1.1-2.1

Operating system: Ubuntu 14.04 LTS

OS language: Czech

Installation path of client: from your debian package

### Logs
I don't have logs yet as the client is running without logs now and it seems that for capturing log to a file I'd have to restart it - and **when the client is restarted it notices the changed files and uploads them OK** so such log wouldn't help.

What I can observe is that the last owncloud client upload happened at 8:43:51 even though there have newly modified files since then, see below:
```
$ LC_ALL=C ls -lt .git
total 140
-rw-rw-r--   1 joy joy  4463 Apr 11 09:09 gitk.cache
drwxrwxr-x   8 joy joy  4096 Apr 11 09:09 ./
-rw-rw-r--   1 joy joy   643 Apr 11 09:09 index
drwxrwxr-x 135 joy joy 20480 Apr 11 09:09 objects/
drwxrwxr-x   4 joy joy  4096 Apr 11 08:43 ../
```
Please notice that this happens irregularly and I don't know if it is related to the particular .git folder only - I just noticed it here first.

**Comment by guruz** [comment]
@ckamm file watcher issue somehow?

**Comment by dragotin** [comment]
@joysfera could you check the setting of the checkbox "Sync hidden files" in your client? See https://doc.owncloud.org/desktop/2.1/navigating.html#using-the-ignored-files-editor

**Comment by joysfera** [comment]
@dragotin it's of course enabled. It sometimes syncs the .git folder so it's not a settings issue (and it did sync it everytime in the past three months). I hope it answered also eventual question about having .git in the ignore list (no, it's not there).

**Comment by ckamm** [comment]
I'll try to reproduce it later.

**Comment by joysfera** [comment]
Any suggestion for me how to help debugging this? Perhaps I can try 'touch'ing inside and outside of the affected folder to see if the file watcher notices newly created files? Or I could try modifying the at-that-moment ignored files manually. Anything else?

**Comment by ckamm** [comment]
@joysfera Thanks for the offer! You could look at what happens to the logfile (--logfile myfile.txt) when you touch something in the .git folder. Look for messages from `folderwatcher`.

**Comment by ckamm** [comment]
I can reproduce the problem. It seems the "sync hidden" flag is only respected during the initial sync. I get `.git: File/Folder is ignored because it's hidden.` in my "Not Synced" list.

**Comment by joysfera** [comment]
Then I must have been lucky for previous three months, probably due to putting my computers to sleep (suspend) often. When they wake up they probably do the initial sync thus resynced my .git folders.

Glad you reproduced it, @ckamm. Looking forward to getting this fixed in owncloud-client. Though I never had the .git in not synced list, IIRC.

**Comment by ckamm** [comment]
Pull request: #4664

**Comment by joysfera** [comment]
That was quick, thanks a lot!

**Comment by guruz** [comment]
@ckamm is this in the nightly build? Then @joysfera could try that one..

**Comment by ckamm** [comment]
@guruz I don't think so, https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/owncloud-client still looks like there are problems.

**Comment by mcastroSG** [comment]
Hi hi:

**Steps executed**

1. Include a new hidden file at Shared sync folder.
2. Modify this hidden file
3. Move this file to another folder inside Shared sync folder
4. Modify this hidden file on it´s new location

**Results**

It seems to work. Any change that affects that hidden file is detected by Desktop Client and the file is synced.

Server OS: Ubuntu 
Sever Version: 9.1.0 Alpha
Client OS: Ubuntu 14.04 LTE
Client Version: Version 2.2.0nightly2016421 (build 1557)

@joysfera  may you test again ?  ;-)

**Comment by joysfera** [comment]
I'm on Xenial (16.04) now. Will you have a nightly/regular build for 16.04 soon? Or is it safe to install say 15.10?

**Comment by ckamm** [comment]
@joysfera I don't know. @danimo What's your guess for betas / nightlies for 16.04?

**Comment by joysfera** [comment]
I've been using 15.10 nightlies for some time now and it seems to be working fine. I suppose this issue can be closed as resolved. Thank you all!

**Comment by mcastroSG** [comment]
@joysfera  tk 😄
