### ISSUE TITLE
Allow to use the character & on the Application Name

### ISSUE THREAD

**Issue by rperezb** [owncloud/client#4657]
### Expected behaviour
I'd like to use the character "&" on the APPLICATION_NAME  variable so that i can call my app "Raquel & cia" :wink: https://github.com/owncloud/client/blob/d7bd1300a8397c2782e8d75cf7c595b1ada70d88/OWNCLOUD.cmake#L1

### Actual behaviour
There is a compilation error

````
** BUILD SUCCEEDED **

[ 99%] Built target legacy_mac_overlayplugin
[100%] icons
/bin/sh: V Cloud: command not found
make[2]: *** [shell_integration/MacOSX/CMakeFiles/mac_overlayplugin] Error 127
make[1]: *** [shell_integration/MacOSX/CMakeFiles/mac_overlayplugin.dir/all] Error 2
make: *** [all] Error 2
````

cc @jturcotte 

related to https://github.com/owncloud/ownbrander/issues/581

**Comment by guruz** [comment]
The problem in the shell is easy to fix by adding " but then then ```Info.plist``` is broken because ```&``` is not valid in XML..
checking how to escpae this..

**Comment by guruz** [comment]
PR: https://github.com/owncloud/client/pull/4683

**Comment by rperezb** [comment]
works! thx
![screen shot 2016-05-10 at 12 52 22](https://cloud.githubusercontent.com/assets/1846927/15144186/1b43a2b6-16ae-11e6-806f-a62e51f59c0c.png)
