### ISSUE TITLE
using standalone rsync on mac os x

### ISSUE THREAD

**Issue by julou** [owncloud/client#4661]
Hello,

Because my organization has not yet deployed owncloud on our servers, I'm trying to use csync to synchronise a few directories between my laptop and my remote account (following the recommandation of one of our sysadmins). Unfortunately, the available csync is broken on mac: https://open.cryptomilk.org/issues/40 (NB this issue has been opened and undressed for **10 months**!).

Although this might not be the most relevant board, I dare to ask to the own cloud community:
- whether it's possible to use owncloudcmd to sync between local and a sftp directory?
- whether I'm correct thinking that csync development now happens within the owncloud client?
- whether a standalone version of csync for mac (or at leat build instructions) are available?

Thank you in advance for your help!

**Comment by guruz** [comment]
Wwe forked the csync completely and removed the abstracting VIO layer. So now owncloudcmd can only sync between local files and owncloud. Sorry.

The development of upstream csync from csync.org is not within our scope currently.

**Comment by guruz** [comment]
Closing issue, but feel free to still comment.

FYI @dragotin
