### ISSUE TITLE
"File/Folder is ignored because it's hidden" even though "sync hidden files" set

### ISSUE THREAD

**Issue by tessus** [owncloud/client#4666]
### Expected behaviour
Client should sync hidden files.

### Actual behaviour
Messages show up under Activity -> Not Synced that tell me:
File/Folder is ignored because it's hidden.

### Steps to reproduce
1. Run client
2. Messages show up automatically

### Server configuration
Operating system: Linux 64bit

Web server: Apache 2.4.20

Database: Mysql 5.6.25

PHP version: 5.6.20

ownCloud version: 8.2.3

Storage backend: file system

### Client configuration
Client version: Version 2.2.0-nightly20160408 (build 3249)

Operating system: OSX 10.11.4

OS language: us-en

Installation path of client: /Applications/owncloud.app

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`

2. Web server error log: no errors

3. ownCloud log (data/owncloud.log): no errors

**Comment by tessus** [comment]
After stopping the client and starting it with `./owncloud --logfile log.tx` to collect logs, the client also synced the hidden files.

`./owncloud --logwindow` showed the network tab in the GUI, but no log window.

Anyway, since the error disappeared after the restart of the client, I will close this issue again.

**Comment by guruz** [comment]
Also @ckamm might have fixed this in an even more recent nightly. Try that too if it happens again.
