### ISSUE TITLE
Convert "lnk" files to symlinks transparently

### ISSUE THREAD

**Issue by bronger** [owncloud/client#4671]
### Expected behaviour
Tell us what should happen

If I sync on a POSIX system, symbolic links created under Windows should survive

### Actual behaviour
Tell us what happens instead

The symlinks are visible as "lnk" files.

### Steps to reproduce
1. Create a link on a Windows computer in a directory synced with owncloud
2. Sync to a Linux computer
3. Visit the directory

### Server configuration

The owncloud deployment that we use is https://www.sciebo.de/en/

### Client configuration
Client version: 2.1.1

Operating system:

OS language: German

Installation path of client: /usr/bin/owncloud

**Comment by dragotin** [comment]
hmm, I wonder how that is possible. The lnk files are actually "only" files, and only useful on Windows, because of a different file system structure and stuff. 

You need to elaborate please, maybe I do not understand correctly.

**Comment by bronger** [comment]
If I say "file foobar.lnk", it says

```
foobar.lnk: MS Windows shortcut, Item id list present, Points to a file or directory, Has Relative path, Has Working directory, Archive, ctime=Tue Apr  5 06:15:18 2016, mtime=Wed Apr 13 09:22:06 2016, atime=Wed Apr 13 09:22:06 2016, length=112024, window=hide
```

Especially this "Has Relative path" nurtured my hope that it can be made working -- at least in this case.  The relative path is contained in the "lnk" file.  If one can find a way to extract it, it should be possible to do the conversion even transparently, reliably, and bi-directional.  E.g. the "lnk" file may stay, just a symbolic link without the ".lnk" is added.  But there are more elegant possibilities, too.  Whatever is feasible.

**Comment by danimo** [comment]
A lnk file is _not_ the same as a link on Linux. That's what symlink reparse points are. We should not mess with lnk files as they have a different semantic (can carry metadata such as an icon that POXIS links cannot carry).

**Comment by bronger** [comment]
@danimo FWIW, it would help me a lot to see where my collegues point to.  When the original information carried in the lnk was stored in owncloud internally, no information would get lost.  And, this behaviour could be optional.

**Comment by 9662** [comment]
> We should not mess with lnk files as they have a different semantic (can carry metadata such as an icon that POXIS links cannot carry).

Sounds a lot like `.desktop` files?
