### ISSUE TITLE
ownCloud Dolphin Plugin: does not work without XDG_DATA_DIRS and QT_PLUGIN_PATH set

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4674]
### Expected behaviour
Start dolphin and see overlay icons. 

### Actual behaviour
Dolphin only shows overlay icons when started with the command line
```
XDG_DATA_DIRS=$XDG_DATA_DIRS:/usr/share QT_PLUGIN_PATH=/usr/lib64/plugins dolphin 
```

The package containing the overlay plugin installs to 
```
[kf:~/owncloud.com/mirall] master(+3/-3)+* 15s rpm -ql owncloud-client-dolphin
/usr/lib64/libownclouddolphinpluginhelper.so
/usr/lib64/plugins
/usr/lib64/plugins/kf5
/usr/lib64/plugins/kf5/overlayicon
/usr/lib64/plugins/kf5/overlayicon/ownclouddolphinoverlayplugin.so
/usr/lib64/plugins/ownclouddolphinactionplugin.so
/usr/share/kservices5/ownclouddolphinactionplugin.desktop
```
This is built on openSUSE Leap with updates, so that  KDE Frameworks 5.20 is available. I need to check on tumbleweed.

### Steps to reproduce
1. Install owncloud-client-dolphin from isv:ownCloud:community:nightly repository 
2. try to start dolphin with overlay icons.

The current cmake install commands are in https://github.com/owncloud/client/blob/master/shell_integration/dolphin/CMakeLists.txt#L38

It looks like the plugins are installed to the wrong place, as most qt5/kf5 plugins seems to live in `/usr/lib64/qt5/plugins/` in openSUSE. 

### How can this be solved?

1. Add the pathes to XDG_DATA_DIRS and QT_PLUGIN_PATH for all users
2. Install the plugins to the right locations on openSUSE which probably would require a fix to the cmake modules that are used to install?!

**Comment by dragotin** [comment]
I added the cmake switch `-DKDE_INSTALL_USE_QT_SYS_PATHS=1` which changed the package to 
```
[kf:~/pack … unity:nightly/owncloud-client] 14s $ rpm -ql owncloud-client-dolphin
/usr/lib64/libownclouddolphinpluginhelper.so
/usr/lib64/qt5/plugins/kf5/overlayicon
/usr/lib64/qt5/plugins/kf5/overlayicon/ownclouddolphinoverlayplugin.so
/usr/lib64/qt5/plugins/ownclouddolphinactionplugin.so
/usr/share/kservices5/ownclouddolphinactionplugin.desktop
```
looks more like common plugin dirs, but no success with dolphin either.

**Comment by dragotin** [comment]
Update: Adding the cmake switch actually helped, Dolphin overlays now work on openSUSE Tumbleweed, which seems to be the only distro that we support with a suitable KDE Frameworks version. :guitar:

**Comment by rperezb** [comment]
checked by @dragotin thx
