### ISSUE TITLE
[Windows] ownCloud-2.1.1.5837-setup.exe drops shell file icons

### ISSUE THREAD

**Issue by digip** [owncloud/client#4677]
### Expected behavior
Normal windows explorer shell folder icons with mini overlay sync icons in sync folders

### Actual behavior
All folder icons, when client is started, turn to generic windows shell icons adn can not distinguish between folders and files when generic icon is loaded in sync folders. When client is disconnected/off, the shell icons return to normal windows folder icons. I suspect something in the last update changes/blocks desktop.ini when client is loaded and is preventing the shell icons to show while the client is open. After exiting the client, the icons revert to normal, and only shows the icons in the attached image when the client is actually up and running. This issue arose after updating to the latest stable client. Reverting to older client does not fix the issue either.
![owncloud](https://cloud.githubusercontent.com/assets/18443903/14496227/83fccf16-0160-11e6-9184-a822e42d9f36.png)
 

### Steps to reproduce
1. Install latest stable windows desktop client
2. Start client
3. Navigate to synced folders, observe missing icons

Operating system: Windows 7 Enterprise, SP1
Client version: ownCloud-2.1.1.5837-setup.exe
Installation path of client:

### Logs

4/13/2016 10:09:25 AM,                                                     desktop.ini,E:\FILES_TO_MOVE_TO_OWNCLOUD\,File is listed on the ignore list.

**Comment by guruz** [comment]
Maybe you could try a nightly build and see if it happens there too?

http://download.owncloud.com/desktop/daily/ownCloud-2.2.0.5988-nightly20160412-setup.exe

FYI @jturcotte

**Comment by digip** [comment]
I had actually tried ownCloud-2.2.0.5988-nightly20160412-setup.exe before 
posting my comments on the icon bug, and even reverted to previous client 
ownCloud-1.8.4.5267-setup.exe to test, which the older client did not fix 
the icon issue once the new client was installed. The 
ownCloud-2.2.0.5988-nightly20160412-setup.exe client version crashes each 
time the client starts up, so nightly doesn't seem to work on my system, 
curious if anyone else has this issue on win7 enterprise, sp1. Asks to send 
report, which I did.  I eventually put it back to the latest stable, but 
icons are still borked when client is open.

-----Original Message-----

**Comment by digip** [comment]
Managed to get the icons back. Changed my folder settings to show hidden and system files, deleted the desktop.ini file(s) and rebooted. Icons are now restored. Not sure how that works, but hopefully anyone else who runs into this finds as an easy fix.
![owncloud-icons-fixed](https://cloud.githubusercontent.com/assets/18443903/14506422/c17a71b0-018b-11e6-9e69-66bc41743fae.png)

**Comment by guruz** [comment]
Hm, the nightly should work also on Windows 7.. maybe you want to try again when the beta is released
