### ISSUE TITLE
Confusing ui when trying to share something that can't be reshared

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#4679]
While working on #4383 I noticed that the UI behavior isn't neat when trying to share something that one doesn't have reshare permission for.

* Share by link: Clickable, but then fails. Final state has "Share by link" checked, but disabled. An error message is shown.
* Share with user: One can still type a username. Failure message appears once sharing is attempted.

We could stop early and not show things that look like sharing might work.

**Comment by mcastroSG** [comment]
[https://github.com/owncloud/client/issues/4383#issuecomment-215705233](url)

Everthing seems to work fine :)
