### ISSUE TITLE
[Nautilus? [Dolphin?] [2.2.pre] SocketAPI (new): If folder is paused, Sync status is not updated

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4681]
### Expected behaviour
If a folder is paused, the overlay icons should reflect the local status of a file: If it was touched locally during the sync connection paused, it should show the sync icon rather than the ok icon. 

### Actual behaviour
It shows the ok icon, even if it was touched.

### Steps to reproduce
1. Have a folder in sync.
2. Pause it.
3. Work on files in the sync folder
4. See that the icon does not change. (Tested on Linux nautilus and dolphin).

**Comment by ckamm** [comment]
@dragotin It's not straightforward and there's a good chance we weren't doing it correctly before either.

* When sync is paused, does it make sense to show the green icon? The version on the server may have changed days ago.
* We could track touched files and mark them with the blue sync icon - I think that's what we did before. But if we don't persist this information, it'll revert to the green icon when the client is restarted.

It may be less confusing to disable icons for paused folders. (Same for disconnected / logged out accounts?)

**Comment by ckamm** [comment]
@dragotin dff74a6 is a short patch that restores much of the old behavior - but it's definitely far from correct. Check the above comment.

**Comment by jturcotte** [comment]
The question that we need to answer first is: Does the sync icon means that the file is scheduled for syncing? Or does it mean that it's not in sync with the server?

Personally I always thought that it meant syncing, as it is more consistent with the tray icon. With that in mind I find it misleading to show a sync icon for a file if the tray icon shows paused or OK.

**Comment by dragotin** [comment]
Yes, good questions. I think we valued the status of the individual file in the file manager over the "compatibility" with the tray icon. I  understand the status should reflect either: Yes, the file is in sync with the server, it is not in sync, there was an error, or it is ignored.

The tray is more high level over all accounts and indicates the activity at all, or an error condition. In the tray we only have: Not active == Ok, Actively syncing, or Error.

**Comment by guruz** [comment]
A green icon gives the user the impression "hey, all good, synced to server, i can close my machine and go home". We must not give this impression if it is not true (e.g. there was a local change).
This was the intention of the tainted files/dirs. 

I like the @ckamm approach if hooking directly into the watcher (although we must make sure to not mix up stuff if the change actually was originated from the client, e.g. if a file was downloaded.)

**Comment by dragotin** [comment]
We decided to show **no** icons if a sync was paused or disconnected because of performance and simplicity reasons. 

In the next version we will show different icons for pausing and/or disconnect but that is not longer in scope of 2.2.0.

**Comment by dragotin** [comment]
@jturcotte fyi
