### ISSUE TITLE
[OS X] [2.2pre] [Overlays]: Sync activity does not propagate up to root folder

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4682]
### Expected behaviour
If a file is added to `foo/bar/baz/long/folder`, the client starts to sync and shows a sync overlay for that file. All parent folders up to the local root directory should also show the sync icon.

### Actual behaviour
It seems that the parent folders are only updated after the sync finished. They do not show a "progress" icon.

Tested on Mac with current nightly.

### Steps to reproduce
1. In a synced folder, create a somewhat deep folder structure.
2. Have the root sync dir open in finder and see the overlay icon
3. Put a file into the deep structure, and see that the folder in the root does not change the icon.

**Comment by dragotin** [comment]
This is fixed by 361ebf5464077ce08049ea9e1f834e6fe56cade9 once pr #4689 is merged.

**Comment by guruz** [comment]
As discussed on https://github.com/owncloud/client/pull/4689#issuecomment-213445513

Maybe something like this works (untested):
```
diff --git a/src/gui/socketapi.cpp b/src/gui/socketapi.cpp
index 91887f0..eb102b1 100644
--- a/src/gui/socketapi.cpp
+++ b/src/gui/socketapi.cpp
@@ -211,9 +211,13 @@ void SocketApi::slotUpdateFolderView(Folder *f)
                 f->syncResult().status() == SyncResult::Error   ||
                 f->syncResult().status() == SyncResult::SetupError ) {
 
+            if (f->syncResult().status() == SyncResult::SyncPrepare) {
+                broadcastMessage(QLatin1String("STATUS"), f->path() ,
+                                 "SYNC");
+            } else {
             broadcastMessage(QLatin1String("STATUS"), f->path() ,
                              f->syncEngine().syncFileStatusTracker().fileStatus("").toSocketAPIString());
-
+            }
             broadcastMessage(QLatin1String("UPDATE_VIEW"), f->path() );
         } else {
             qDebug() << "Not sending UPDATE_VIEW for" << f->alias() << "because status() is" << f->syncResult().status();
```

**Comment by guruz** [comment]
See also discussion at https://github.com/owncloud/client/issues/4726

**Comment by mcastroSG** [comment]
Hi hi:

**Steps Executed**

1. In a synced folder, create a somewhat deep folder structure.
2. Have the root sync dir open in finder and see the overlay icon
3. Put a file into the deep structure

**Results**

Overlay icon on root folder is updated to "Blue sync" in a proper way till sync ends. After sync is finished is updated to "Green check" again so it works fine.

Client OS: OS X El capitán 10.11.4
Client Version: Version 2.2.0-nightly20160504 (build 3331)
