### ISSUE TITLE
A file that is stored on the server is not synced to the client

### ISSUE THREAD

**Issue by Pastafarianist** [owncloud/client#4685]
I have a file that used to be stored in the `ownCloud` directory under `backups/backup`. Currently this file has a size of 0 bytes on my machine.

```
$ ls -l backups/backup 
-rw-r--r-- 1 user user 0 ago 15  2015 backups/backup
```

However, this file is present on the server under `data/user/files/backups/backup`:

```
# ls -l backups/backup 
-rw-r--r-- 1 www-data www-data 4294967296 Aug 15  2015 backups/backup
```

The client reports that it has synced everything.
### Steps to reproduce

No idea. I just noticed this spontaneously.
### Server configuration

Please see the detailed information at https://github.com/owncloud/contacts/issues/359 .
### Client configuration

Client version:

```
$ eix -I owncloud
[I] net-misc/owncloud-client
     Available versions:  (~)2.0.0 (~)2.0.1 (~)2.0.2 (~)2.1.0 (~)2.1.1 {doc dolphin nautilus qt4 +qt5 samba +sftp test}
     Installed versions:  2.1.1(22:48:08 16/02/16)(qt5 sftp -doc -dolphin -nautilus -qt4 -samba -test)
     Homepage:            http://owncloud.org/
     Description:         Synchronize files from ownCloud Server with your computer
```

Operating system:

```
$ uname -srv
Linux 4.1.15-gentoo-r1 #6 SMP Tue Mar 1 15:44:57 MSK 2016
```

OS language:

```
$ locale
LANG=es_ES.UTF-8
LC_CTYPE="es_ES.UTF-8"
LC_NUMERIC="es_ES.UTF-8"
LC_TIME="es_ES.UTF-8"
LC_COLLATE="es_ES.UTF-8"
LC_MONETARY="es_ES.UTF-8"
LC_MESSAGES="es_ES.UTF-8"
LC_PAPER="es_ES.UTF-8"
LC_NAME="es_ES.UTF-8"
LC_ADDRESS="es_ES.UTF-8"
LC_TELEPHONE="es_ES.UTF-8"
LC_MEASUREMENT="es_ES.UTF-8"
LC_IDENTIFICATION="es_ES.UTF-8"
LC_ALL=
```

Installation path of client:

```
$ which owncloud
/usr/bin/owncloud
```
### Logs

There is nothing related to this file in any of the logs.

**Comment by guruz** [comment]
that's exactly 4 gibibyte..
Hard to tell exactly what is going on without the logs..
What is in your ```.owncloudsync.log``` in your local sync dir with regards to that file?

**Comment by Pastafarianist** [comment]
@guruz nothing.

    $ cat .owncloudsync.log | grep backup
    <no output>

**Comment by dragotin** [comment]
@Pastafarianist your server config tells about armlv7. AFAIK that is a 32 bit platform. If that does not have special support for large files in PHP you wont be able to have large files. Can you check that?

**Comment by Pastafarianist** [comment]
@dragotin how can I do that?

**Comment by dragotin** [comment]
@Pastafarianist check the linux distro that is running on the server. Try to create a big file larger than 4GB would be a good start. What distro do you use there? Which PHP version?

**Comment by Pastafarianist** [comment]
@dragotin the server is Debian Jessie ARM, built using the script from [here](https://github.com/tomuta/debian-mini-odroid-c1). I linked to the server config in the first post, here is the relevant part:

### Server configuration
**Operating system**: fully upgraded Debian Jessie ARM:

```
$ uname -srv
Linux 3.10.80 #1 SMP PREEMPT Sat Jun 20 10:47:49 GMT 2015
```
**Web server:** `Server version: Apache/2.4.17 (Debian)`

**Database:** `mysql  Ver 15.1 Distrib 10.0.23-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2`

**PHP version:**

```
$ php --version
PHP 5.6.19-0+deb8u1 (cli) (built: Mar 25 2016 05:58:21) 
Copyright (c) 1997-2016 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2016 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2016, by Zend Technologies
```

**Comment by dragotin** [comment]
Thanks, but unfortunately I do not know enough details. Would you mind asking on the devel mailinglist with a  link to this issue asking if anybody can shed light if this distro/PHP is supposed to support big files? That would be great.

**Comment by Pastafarianist** [comment]
Here's what I have done:

```
~ $ fallocate -l 4200MB dummy
~ $ du -h --summarize dummy
4,0G    dummy
~ $ mv dummy ownCloud/
```

Waiting until it uploads.

**Comment by tflidd** [comment]
The documentation says the client should be able to upload larger files (so it's not sure what happens for downloads):
https://doc.owncloud.org/server/9.0/admin_manual/configuration_files/big_file_upload_configuration.html?highlight=big%20file
There is/was a problem on 32-bit php versions, can you check the filesize in you filecache-table?

**Comment by Pastafarianist** [comment]
@tflidd do you mean in MySQL?

**Comment by tflidd** [comment]
@Pastafarianist Yes, the oc_filecache-table in your mysql-database.

**Comment by Pastafarianist** [comment]
@tflidd, the size is correct in the database.

```
$ mysql -u root -p
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 14127
Server version: 10.0.23-MariaDB-0+deb8u1 (Debian)

Copyright (c) 2000, 2015, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> use owncloud;
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Database changed
MariaDB [owncloud]> select * from oc_filecache where path like '%backups/backup%';
+--------+---------+-------------------------------------------+----------------------------------+--------+--------------------+----------+----------+------------+------------+---------------+-----------+------------------+----------------------------------+-------------+----------+
| fileid | storage | path                                      | path_hash                        | parent | name               | mimetype | mimepart | size       | mtime      | storage_mtime | encrypted | unencrypted_size | etag                             | permissions | checksum |
+--------+---------+-------------------------------------------+----------------------------------+--------+--------------------+----------+----------+------------+------------+---------------+-----------+------------------+----------------------------------+-------------+----------+
| 104763 |       1 | files/backups/backup                      | 56c4637f0dd42f500e508b4e5fa12cfc |  23258 | backup             |       10 |        3 | 4294967296 | 1439598700 |    1439598700 |         0 |                0 | f766a764494f82620eda2b255f38687c |          27 | NULL     |
| 182713 |       1 | files_versions/backups/backup.v1357217243 | 77681c88b1ae31a17b63793e8da88f45 | 112964 | backup.v1357217243 |       10 |        3 | 2147483647 | 1458174388 |    1458174388 |         0 |                0 | 2c3272d19cf8c403067b1851c3f418bf |          27 | NULL     |
+--------+---------+-------------------------------------------+----------------------------------+--------+--------------------+----------+----------+------------+------------+---------------+-----------+------------------+----------------------------------+-------------+----------+
2 rows in set (0.00 sec)
```

**Comment by Pastafarianist** [comment]
I have two more machines running an ownCloud client.

The first one runs Gentoo and has `backups/backup` with a size of 0 bytes and `backups/backup_conflict-<date>` with a size of 2147483647 bytes.

The second one runs Kubuntu and has `backups/backup` with a size of 4294967296 bytes.

**Comment by tflidd** [comment]
So gentoo should get synced the backups/backup file with 4 GiB as well. In the filesystem on gentoo you can handle files larger than 4 GiB (especially not FAT-32)?

**Comment by Pastafarianist** [comment]
@tflidd, `ext4` is everywhere.

**Comment by Pastafarianist** [comment]
I have downloaded the file from the server manually (from `data/user/files/backups/backup`) and put it into the ownCloud folder on one of the client machines (the first one, which runs Gentoo). Now the client refuses to sync it to the server with the error "maximum waiting time exceeded" (not sure about the exact wording, I'm translating from Spanish). On the server, however, there is an error in `owncloud.log`:

    {"reqId":"2NrvuInD\/DI7FP6o5qaP","remoteAddr":"192.168.1.1","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 423 \\\"backups\\\/backup\\\" is locked\",\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\FileLocked\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(490): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->convertToSabreException(Object(OCP\\\\Lock\\\\LockedException))\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php(103): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->createFileChunked(Resource id #38)\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/directory.php(134): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->put(Resource id #38)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(1036): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Directory->createFile('backup-chunking...', Resource id #38)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(523): Sabre\\\\DAV\\\\Server->createFile('backups\\\/backup-...', Resource id #38, NULL)\\n#5 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpPut(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#6 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#7 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:PUT', Array)\\n#8 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#9 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#10 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#11 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":546,\"User\":\"pastafarianist\"}","level":4,"time":"2016-05-02T20:18:54+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav\/backups\/backup-chunking-779319150-820-819","user":"pastafarianist"}

**Comment by domitor1927** [comment]
Do you have solved the problem? i have the same problem in one raspberry pi 2

**Comment by Pastafarianist** [comment]
@domitor1927 I don't remember what happened then, but right now this file is still on my Gentoo machine and the client is not reporting any errors.

**Comment by guruz** [comment]
I'm closing this. @domitor1927 does this still happen for you with a recent ownCloud server and client?
