### ISSUE TITLE
owncloudcmd doesn't support spaces in .netrc password field

### ISSUE THREAD

**Issue by callmemagnus** [owncloud/client#4691]
### Expected behaviour
I can use a password with a space in the .netrc
```
machine owncloud-server
login bob
password my password with spaces
```

### Actual behaviour
when running
```
$ owncloud -s -n directory https://owncloud-server/remote.php/webdav
```
I get the following:
```
...
Stop request: Authentication failed for  "https://bob:my@owncloud-server/remote.php/webdav/" 
...
```

I tried with quote or + or %20 without success.

### Steps to reproduce

As described above

### Server configuration
Operating system: debian
Web server: nginx
Database: mysql
PHP version: 5.4
ownCloud version: 9.0.0
Storage backend: fs

### Client configuration
Client version: 2.1.1
Operating system: debian 8
OS language: en_us
Installation path of client: /usr/bin

### Logs

See above.

**Comment by danimo** [comment]
Fixed for 2.2.0

**Comment by callmemagnus** [comment]
Yeah!

**Comment by mcastroSG** [comment]
Hi hi:

**Steps Executed**

1.- Create a new user at server setting 1 2 3 as password
2.- Configure .netrc file setting as password 1 2 3
3.- execute `owncloudcmd -s -n folder http://machine.es/remote.php/webdav`

**Results**

`Authentication failed for  "http://Miguel:1@`

@danimo any ideas ¿?

**Comment by danimo** [comment]
@mcastroSG You need to quote a passwort with spaces, see the test cases.

**Comment by mcastroSG** [comment]
Hi hi:

Steps Executed

1.- Create a new user at server setting 1 2 3 as password
2.- Configure .netrc file setting as password "1 2 3"
3.- execute owncloudcmd -s -n folder http://machine.es/remote.php/webdav

Results

It works fine. Thanks @danimo 🙇
