### ISSUE TITLE
Use QtWebEngine instead of QtWebKit?

### ISSUE THREAD

**Issue by flocke** [owncloud/client#4692]
QtWebKit was deprecated in Qt version 5.5 (https://wiki.qt.io/New-Features-in-Qt-5.5#Deprecated_Functionality). So it would be a good idea to switch to QtWebEngine when using Qt5.

I might look into it myself and send you a pull request if I find the time.

Could you tell me where QtWebKit is used that I have some idea where to start looking.

**Comment by danimo** [comment]
The class that needs porting is primarily [ShibbolethWebView](https://github.com/owncloud/client/blob/master/src/gui/creds/shibboleth/shibbolethwebview.cpp):

The problem is that QtWebEngine does not offer the same functionality last time we looked:

* QtWebEngine does not use the Qt Network stack, and we cannot set the user agent
* We cannot shift cookies between QtWebEngine and the Qt Network stack.

**Comment by danimo** [comment]
Updating myself:

* Setting a user agent is possible since 5.5: http://doc.qt.io/qt-5/qwebengineprofile.html#setHttpUserAgent

* Accessing the cookie jar is possible since 5.6: http://doc.qt.io/qt-5/qwebenginecookiestore.html

**Comment by flocke** [comment]
If I find the time tomorrow I will start to look into it, but I don't have a lot experience with C++, so it might take a while. Feel free to look into it yourself if you have the time/are interested, it might be quicker. ;)

**Comment by guruz** [comment]
Not sure if relevant: https://www.phoronix.com/scan.php?page=news_item&px=QtWebEngine-Mess-Debian

**Comment by danimo** [comment]
@guruz Not really relevant, because `QtWebKit` is out as well. Distros need to deal with it, as explained in the article.

**Comment by jturcotte** [comment]
Just to clarify, as stated in the #4798 issue, we're still not sure if QtWebEngine is what we want to use on all platforms. At the moment QtWebEngine is only a last resort solution.

**Comment by guruz** [comment]
@ogoffart @DeepDiver1975 Can this be closed?
You are working on the external-browser-based login for the client right? Then we avoid any QtWeb* dependency

**Comment by ogoffart** [comment]
Yes, one can compile the client with `-DNO_SHIBBOLETH` To disable shiboleth support and then we don't need webkit.
OwnCloud server from 9.1 supports already application password.  I don't know if this works with shibboleth tough.

**Comment by dragotin** [comment]
Worth a check, maybe @michaelstingl can help or investigate?

**Comment by guruz** [comment]
I'm not talking about application passwords, i'm talking about https://github.com/owncloud/core/issues/24794
which is about opening an external browser.

**Comment by ogoffart** [comment]
owncloud/core#24794 is not yet in the current server. But application password are,  and i believe they should work with shiboleth.  And in 2.3 you get a link to request the application password.

**Comment by michaelstingl** [comment]
As far as I know, there is no connection between application password and shibboleth app. @butonic Can you confirm?

**Comment by butonic** [comment]
Making shibboleth work with desktop clients that use token based auth is a webserver (and probably firewall) configuration issue. The webdav endpoint needs to be accessible without a shibboleth session.

What are application passwords? The session tokens a user can now create?

**Comment by guruz** [comment]
@butonic Interesting point, something to discuss in https://github.com/owncloud/client/issues/4798
So there needs to be some kind of server side shibboleth

application passwords = session tokens that can be generated in the user config UI, indeed
