### ISSUE TITLE
"Add sync folder connection" wizard still has an edit field for "Directory alias name"

### ISSUE THREAD

**Issue by guruz** [owncloud/client#4695]
We agreed to remove that right?
@jancborchardt @dragotin

**Comment by dragotin** [comment]
I am not happy to remove it. Only do it if @jancborchardt insists.

**Comment by jancborchardt** [comment]
Yeah, I insist since quite some time already. The name is already there, and it’s the folder name (in case of collisions, path name).

**Comment by mcastroSG** [comment]
Hi hi:

*Steps Executed**

1.- Add a new Folder Sync Connection

**Results**

Add Folder Sync Connection Wizard does not show Directory Alias name . So it works fine.

OS X
Client OS: 10.11.4 El capitán
Client Version: Version 2.2.0beta2 (build 3326)

OS W
Client OS: W10
Client Version:Version 2.2.0beta2 (build 6044).

OS Linux
Client OS: Ubuntu 14.04 LTE
Client Version:Version 2.2.0beta2 (build 1582)

Server OS: Ubuntu 
Server Version: 9.1.0 Alpha

**Comment by guruz** [comment]
@mcastroSG @rperezb Testing this on only one OS is fine... :) It's cross platform code.

**Comment by rperezb** [comment]
@guruz yes, however, in some design issues i'd say that it's a good idea to check, at least win and mac
however, @mcastroSG hehe 4...omg!
