### ISSUE TITLE
Windows 10 Explorer - continually refreshing

### ISSUE THREAD

**Issue by TerryHewitt** [owncloud/client#4702]
On Windows 10 I have set up a number of folders to synchronise.

One of them contains an application database (Lightroom.lrcat). So whilst I'm running lightroom its database file is open and locked.

That now appears to be causing Windows 10 explorer to continually refresh. Anything I try to do in explorer takes a long time. Notice in the attached image - folder documents is listed multiple times. It expands and contracts continuously!

Note: I have moved "Documents" (and Desktop, Downloads and Pictures) from c:\users\documents" to "D:\users\documents" etc. using the standard Windows 10 features to do this (right click on Documents, then properties, then Location and then click on move...

If I stop or suspend synchronisation Owncloud client - problem disappears
If I stop Lightroom - problem disappears

Both client and server are up to date.

Is there anything I can do to user owncloud client and Lightroom at the same time?

Best wishes

Terry

[2016-04-19_11-25-47.pdf](https://github.com/owncloud/client/files/225691/2016-04-19_11-25-47.pdf)

Client configuration
Client version: 2.1.1
Client operating system: Windows 10

Server configuration
Operating system: Ubuntu 14.04
Web server: apache2
Database: Mysql
PHP version: 5.5.9-1ubuntu4.14
ownCloud version (see ownCloud admin page): 9.0.1 
Updated from an older ownCloud or fresh install: updated
ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
Thank you, I'm closing this in favor of https://github.com/owncloud/client/issues/4329
