### ISSUE TITLE
Could NOT find Qt5Keychain

### ISSUE THREAD

**Issue by Rimehch** [owncloud/client#4703]
this is what i got when i try to compile owncloud client
how to fix plz ?

-- Build of crashreporter disabled.
-- Found Qt5 core, checking for further dependencies...
-- Using Qt 5!
-- GIT_SHA1 80bd86a305f594c3846822c780f28edd3c860ba2
CMake Error at /home/dhouha/openwrt/staging_dir/host/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:91 (MESSAGE):
  Could NOT find Qt5Keychain (missing: QTKEYCHAIN_LIBRARY
  QTKEYCHAIN_INCLUDE_DIR)
Call Stack (most recent call first):
  /home/dhouha/openwrt/staging_dir/host/share/cmake-2.8/Modules/FindPackageHandleStandardArgs.cmake:252 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindQt5Keychain.cmake:35 (find_package_handle_standard_args)
  CMakeLists.txt:151 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by guruz** [comment]
Please read https://doc.owncloud.org/desktop/2.1/building.html

For build support try https://owncloud.org/support or #owncloud-client-dev on freenode IRC.

FYI @dragotin
