### ISSUE TITLE
[OS X] Overlay is not updated after share a file: FinderSyncExt[5869]: SyncState: Unknown command SHARE 

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4705]
### Expected behaviour
Overlay icon should be updated with Shared after share a file.

### Actual behaviour
Overlay icon is not updated and remains as a green check instead of shared icon.

### Steps to reproduce
1. Right click over a file or folder at ownCloud shared folder.
2. Choose option Share with ownCloud and select user and grants.

After those steps overlay icon should be updated with shared icon after sync. We have the rest of the process remains working, at server file or folder appears as shared and final user has access to the file or folder as shared with you. Just the icon is not updated.

### Server configuration

Operating system: Linux Ubuntu
ownCloud version: 9.0.1

### Client configuration

Client version: Version 2.2.0-nightly20160420 (build 3284).
Operating system:MacOS El Capitán 10.11.4

### Logs

At Console.app : `20/04/16 08:36:38,224 FinderSyncExt[5869]: SyncState: Unknown command SHARE
`

**Comment by guruz** [comment]
```
    if(canBeShared && _sharedWithMe) {
        statusString += QLatin1String("+SWM");
    }
```

hmmm "Shared with me"

**Comment by guruz** [comment]
The ```SyncState: Unknown command SHARE``` is actually just a warning from the share dialog's reply to the OS X extension, not the actual sharing..

Two things we'd need to do:
* Trigger a sync after share to update permissions
* The remote permissions coming from server (in next sync) actually don't contain ```S``` flag so we'd not display this icon. 


Dup https://github.com/owncloud/client/issues/3043
@dragotin Removing from milestone, this is a long standing server limitation
