### ISSUE TITLE
[Enhancement] Add startup to tray option

### ISSUE THREAD

**Issue by PureTryOut** [owncloud/client#4711]
When having the ownCloud client startup at login, the window pops up (and at the same time steal focus of whatever I was doing, since it starts with a bit of a delay). Since I have no need for the window at login, I would like to have an option to start ownCloud to tray.

**Comment by guruz** [comment]
We can't help you without more info about your system. Which OS? Desktop? Window manager? Qt version?
Which client version?

**Comment by PureTryOut** [comment]
Woops sorry.

Arch Linux (but applies to every distro basically), XFCE (but applies to every DE with a system tray basically), XFWM, and I didn't even know that there was a different version then Qt, so Qt.

Client 2.1.1

**Comment by dragotin** [comment]
That is an indicator that your DE does start the client twice: The first attempt just starts it, the second pops up the window. 

Please check your General settings if you have the "start at startup" enabled. Please disable that.

**Comment by danimo** [comment]
@dragotin We need to integrate with session management better, but IIRC there already is an issue for that.

**Comment by PureTryOut** [comment]
@dragotin 

Well ownCloud sets it self to the Xfce application autostart list when checking the "launch on system startup" and when I uncheck it it removes itself again. I can however not find any other place where it launches itself.
