### ISSUE TITLE
please sync hidden files by default

### ISSUE THREAD

**Issue by steckerhalter** [owncloud/client#4719]
### Expected behaviour

Important directories/files like `.password-store` are synced by default to ensure people do not lose data in any case.
### Actual behaviour

Important directories like `.password-store` are synced only after having enabled the option in the client. I was quite surprised today when I found that this folder had not been synced at all (and therefore wasn't backed up as well).

Since hidden files are already synced according to an exclusion list, why is this disabled by default? Suppose I would have found that out _after_ my disk was broken or something and all my passwords would have been lost.

I didn't even _consider_ that such a folder could be excluded from the sync by default.
### Client configuration

Client version: 2.1.1

Operating system: Debian

Installation path of client: /usr/share/owncloud-client

**Comment by MTRichards** [comment]
This one is dependent on the hidden file display magic on the server. It would be best to first get https://github.com/owncloud/core/pull/23952 released in 9.1 (the current path forward)

and then consider such a change in default on the client. Note: we will also have to add a show/hide hidden files on mobile.

**Comment by pmaier1** [comment]
As owncloud/core#23952 is merged I would not see a real reason for not changing the default behavior except that we don't have the option on mobile yet and the reasoning above makes sense.

- [ ] Change the default to sync hidden files

Furthermore, then it would make sense to provide reasonable recommendations (are the defaults on the current exclude list reasonable?)
- [ ] Enable editing the exclude list in the GUI (except the hard ones like .part, see https://github.com/owncloud/documentation/issues/2832)
- [ ] Provide a switch to restore defaults

**Comment by fmoc** [comment]
Since the server defaults to not show the hidden files, the client should do the same. Therefore closing this issue.

**Comment by et304383** [comment]
> Since the server defaults to not show the hidden files, the client should do the same. Therefore closing this issue.

"Show" is not the same as "Sync.  This is ridiculous reasoning.  This has to do with not syncing hidden files from the client to the server by default.  I've been burned too many times on new installations where I was not syncing important hidden files and then when I turned it on I have to deal with conflicts.
