### ISSUE TITLE
Perl test scripts : status and on how to use them ?

### ISSUE THREAD

**Issue by orion1024** [owncloud/client#4722]
Hello,

I just started using the perl scripts (https://github.com/owncloud/client/tree/master/csync/tests/ownCloud).
The issue I have is that the current master branch fails them.
The 2.1 branch succeeds so I think my setup is fine.

My questions are the following : 
* are these scripts still maintained  (last commit several months ago, but it might mean nothing) ?
* if yes, is the master branch supposed to succeed them at all times ?

I assumed yes to both questions, so i have been developing on top of master and rebasing on it regularly, but if keeping too much up-to-date means having the tests failing, I might rebase less often...
or maybe master is not considered *the* stable branch to develop on ?

Thanks for your help

@dragotin

**Comment by ckamm** [comment]
I think the tests should be passing. Looking at it now.

It seems the oC auth realm changed from ownCloud to sabre/dav and that the client got better at detecting non-conflicts.

**Comment by ckamm** [comment]
@orion1024 I fixed the tests in the 2.2 branch, they all work for me again. Give it a try! :)

**Comment by orion1024** [comment]
@ckamm : t8 & t9 are now working fine, but t6.pl still failed. But this time it was one my side ; CURL was not installed.
Since the error message I got in the first place was not so helpful, I submitted a PR to have a better one : #4769

Closing this issue, thanks for your help

**Comment by orion1024** [comment]
I talked too soon.
t8 is failing on the test below (tried both master as of now and your specific commit).

```
# Check that only one of the two file was synced.
# The one that exist here is undefined, the current implementation will take the
# first one alphabetically,  but the other one would also be fine. What's imporant
# is that there is only one.
assert( -e localDir() . 'dir/HELLO.dat' );
assert( !-e localDir() . 'dir/Hello.dat' );
```
In my case, Hello.dat is the file existing, so it fails. I'm not sure whether it's the test that needs some change or the code. The comment is a bit ambiguous about whether the client has deterministic behavior or not.

**Comment by rperezb** [comment]
Removing the label readyToTest Following @orion1024 comment,

**Comment by ckamm** [comment]
@orion1024 You're saying that when you switch the asserts around, the full test passes?

I'd be surprised if the client doesn't act deteriministically and I don't remember random t8 failures. Maybe something else is up? Are you using OS X?

**Comment by orion1024** [comment]
@ckamm 
I ran more tests and I'm actually seeing random behavior.
The test will fail either on line 63, 109, or (rarely) complete successfully.
Most of the time it fails on line 63 though.

More information :
System is Debian 8
Both Qt4.8.6 and Qt5.3 builds yields the same results.
I don't have KF5 installed on my build slaves.

**Comment by dragotin** [comment]
This can be closed.
