### ISSUE TITLE
[Overlays] Clarify UPDATE_VIEW for all platforms

### ISSUE THREAD

**Issue by guruz** [owncloud/client#4726]
In https://github.com/owncloud/client/pull/3531/commits/dcf7e8a6318aa34f306b47ba3f764dd938b56624 this was removed for OS X.
@jturcotte what is the state for removing it for other OSes, especially Windows? Can we just do it and it should work?

One thing when we remove it I think we need to do is to push the state of the sync folder / root item (https://github.com/owncloud/client/pull/4689#issuecomment-213445513) (e.g. if the engine starts we want to force a blue icon)

FYI @dragotin

**Comment by guruz** [comment]
Plugins actually don't need special handling because the socket api pushes all changes down the socket anyway.
Currently only Nautilus and Windows still listen/act on UPDATE_VIEW.

**Comment by guruz** [comment]
@jturcotte Can you comment quickly and potentially close the issue here if you think it's fine by now? thanks

**Comment by jturcotte** [comment]
Nautilus seems to still be using it.

**Comment by fmoc** [comment]
`UPDATE_VIEW` is still used by the Nautilus plugin. I don't think there is anything to be done in the near future about it. Long term, the API might be replaced entirely anyway.
