### ISSUE TITLE
2.2.0 beta1 fails to build with qt4

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#4729]
At https://build.opensuse.org/package/show/isv:ownCloud:community:testing/owncloud-client
all builds with qt4 fail, only builds with qt5 succeed.

I see two solutions:
a) fix the build issues with qt4:
<pre>
/usr/src/packages/BUILD/src/3rdparty/qtokenizer/qtokenizer.h:145:9: error: 'class QSharedPointer<QTokenizerPrivate<QString, const QChar*> >' has no member named 'reset'
d.reset(new QTokenizerPrivate<T, const_iterator>(string, delimiters));
src/cmd/CMakeFiles/owncloudcmd.dir/netrcparser.cpp.o
</pre>

b) abondon qt4, move forward to qt5 as available here:
https://build.opensuse.org/project/show/isv:ownCloud:desktop:qt5deb

**Comment by ogoffart** [comment]
Fixed with commit 4e7c09de83e855ebbc0b8014175d1f0bd20632b6
