### ISSUE TITLE
[Overlays] Investigate if we need file watcher based changing of icons

### ISSUE THREAD

**Issue by guruz** [owncloud/client#4730]
@ckamm has made a WiP here: https://github.com/ckamm/owncloud-client/commit/dff74a626cefc3d10117a6812d741cbc2bff23ed

While discussing with @ogoffart and @dragotin we think that it could be that this is not necessary because the file managers will re-request overlay icons if they themselves (via their own watchers) detect a file change.

Important to consider is us acting on our own modifications, we might not want that (timing issues etc..)

FYI @dragotin @jturcotte

**Comment by ckamm** [comment]
@dragotin @jturcotte 

From the discussion in #4681 I gather that we want the blue icon to mean something like "file was was changed locally and no sync run finished yet; or file is currently syncing".

Here is my current impression of what we want:
1. File watcher changes turn a file blue (this ticket).
2. As soon as we detect a file needs changes during a sync run, turn it blue. We might already do this well enough. This is discussed in #4731.
3. File is also blue while it's being propagated. Pretty sure we do that.
4. After a sync run it's no longer blue.

@guruz Why does file managers re-requesting the icon help? If they did that immediately, before the sync run has finished discovery, the client would reply with the green icon. From what I understood we'd like to see the blue icon immediately, without being dependent on a sync run.

We could do this like suggested in ckamm@dff74a6.

**Comment by guruz** [comment]
>  If they did that immediately, before the sync run has finished discovery, the client would reply with the green icon. From what I understood we'd like to see the blue icon immediately, without being dependent on a sync run.

Yes we want to see the blue icon immediatly. I was under the assumption we had code that (when querying a file status from the file manager plugin) queries the DB mtime and compares it to the fs mtime and if not match then it returns the blue icon.
But I think that was removed for performance reasons (which is fine with me..)

**Comment by guruz** [comment]
About your patch https://github.com/ckamm/owncloud-client/commit/dff74a626cefc3d10117a6812d741cbc2bff23ed : You clean the dirty paths before actually syncing (good). But what about new dirty watches during the sync? E.g. the OS might notify you 1 sec after you think you're finished with downloading a new file. And then you think the file is dirty/blue again?

**Comment by ckamm** [comment]
@guruz Yes, that's not addressed yet. We could use the same mechanism we use for preventing that stray self-caused notifications trigger a sync. (see Folder::slotWatchedPathChanged)

**Comment by ckamm** [comment]
Pull request: #4739

**Comment by mcastroSG** [comment]
Hi hi:

### Test 1

**Steps Executed**

1.- Include a new file.txt at Sync shared folder
2.- Wait till sync is done
3.- `touch file.txt`

**Results**

Once touch is done overlay icon changes from "green check" to "blue sync" till a new sync ends uploading again the file. Once change is detected Desktop Client check for next scheduled.

### Test 2

**Steps Executed**

1.- Include a file.txt at Sync shared folder
2.- Wait till sync is done
3.- `mv file.txt filemoved.txt`

**Results**

Desktop Client detects movement and  update overlay icon to "blue sync" . Once a new sync is done it´s updated again to "green check"

Server OS: Ubuntu
Server  Version: 9.1.0 Alpha

Client OS: OS X El capitán 10.11.4
Client Version: Version 2.2.0rc1 (build 3346)

Client OS: Ubuntu 14.04 LTE
Client Version: Version 2.2.0nightly2016511 (build 1602)

Client OS: W81
Client Version: Version 2.2.0rc1 (build 6069)
