### ISSUE TITLE
[Overlays] Investigate if pushing all state in aboutToPropagate() is a performance problem

### ISSUE THREAD

**Issue by guruz** [owncloud/client#4732]
Something like that was mentioned by @dragotin @ckamm 

For a new sync (or a sync with a lot of changes) we'd push a ton of data down the socket API.
But at least there should be no bidirectional communication (with sqlite DB access) be involved since we just push the state from the `SyncFileItem`

FYI @jturcotte @ogoffart

**Comment by guruz** [comment]
One way to fix this is if the ```SocketApi``` would remember all paths for which the file manager plugin ever actively _requested_ a status. If a path is not in that set, we'd not push it down the socket.

**Comment by guruz** [comment]
We'll wait to see if there are users reporting issues. Right now the plugins should just read-and-ignore the paths they're not interested in.

(I don't know if the plugins will cache each item and possibly use a lot of memory.. on OS X the plugin is loaded by each process)

**Comment by jturcotte** [comment]
Seems like you were right, let's track this in #5361
