### ISSUE TITLE
Ubuntu_16.04 cannot build with qt4webkit

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#4733]
This change happend:

* Ubuntu 15.10 and before: libqtwebkit-dev_2.3.2-0ubuntu10_amd64.deb is in main
* Ubuntu 16.04: libqtwebkit-dev_2.3.2-0ubuntu11_amd64.deb is in Universe.

openSUSE build service does not provide Packages from Universe. Only Main.

Thus we currenlty cannot build 2.2.0 beta1 for the hottest Ubuntu ever.

**Comment by guruz** [comment]
I guess it is not an option to build without shib for now?

FYI @jturcotte

**Comment by dragotin** [comment]
@guruz that would be a false friend, because as soon as one customer wants Shib we will have that problem on our desk again.
@jnweiger can we import the webkit and build it ourselfes?

**Comment by jnweiger** [comment]
We don't yet have a debian build environment for webkit. Whatever number of dependencies we'll find that will define the needed effort. Plus debugging.

Note that qt5webkit is currently also not an option, it was moved to universe, so OBS does not offer it nor any of its dependencies. Just checked qttools5-dev -- also in universe now.

**Comment by danimo** [comment]
@jnweiger Can't we simply create a new repo that only holds the dependencies for Ubuntu and import the required packages from universe there, maybe in agreement with the OBS team? AFAICT, universe is not being imported for legal reasons but the packages surrounding QtWebKit should be uncritical.

**Comment by jnweiger** [comment]
https://bugzilla.novell.com/show_bug.cgi?id=977234

**Comment by guruz** [comment]
For a future idea to not need any WebKit: https://github.com/owncloud/client/issues/4798

CC @LukasReschke

**Comment by jnweiger** [comment]
Building sucessfully with qt5 at https://build.opensuse.org/package/show/isv:ownCloud:community:testing/owncloud-client.

Please test!
