### ISSUE TITLE
owncloudcmd doesn't accept options

### ISSUE THREAD

**Issue by AnnoyingTechnology** [owncloud/client#4734]
When provided with any option, the command line tool only provides the Usage and doesn't run as expected. 

Example:
```
~# owncloudcmd --confdir=/etc/owncloud/ /home/owncloud/ ownclouds://some.thi.ng
owncloudcmd - command line ownCloud client tool.

Usage: owncloudcmd <sourcedir> <owncloudurl>
[…]
```

This doesn't work either
```
~# owncloudcmd -u user -p password /home/owncloud/ https://some.thi.ng
owncloudcmd - command line ownCloud client tool.

Usage: owncloudcmd <sourcedir> <owncloudurl>
[…]
```

Without option, this works (in interactive mode). 
```
owncloudcmd /home/owncloud/ https://come.thi.ng
```
But I need have it in non-interactive with a cronjob. Which should be expected for a command line utility.

### Client configuration
Operating system: Debian 8.4 AMD64
3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2 (2016-04-08) x86_64 GNU/Linux
owncloud-client-cmd installed from apt

**Comment by guruz** [comment]
Which version of the ownCloud client?
The distro packages might be outdated/bad ... Please install from https://owncloud.org/install/

**Comment by AnnoyingTechnology** [comment]
I'd happily tell you the version but `owncloudcmd -v` and `owncloudcmd --version` only gives the Usage.
Thanks, I'll install from https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client and update the issue afterwards.

**Comment by AnnoyingTechnology** [comment]
Ok this one works. The one available on vanilla debian is broken.

**Comment by guruz** [comment]
FYI @hefee
