### ISSUE TITLE
[Overlays] Two icons displayed in nautilus

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#4735]
Reproduced this way:
* Open a folder in nautilus
* Modify a file that had a green status icon

While the sync is running, I see two sync icons. The green one stays and an *addidional* blue icon is added. After syncing, the blue icon goes away.

**Comment by ckamm** [comment]
The relevant log from the nautilus extension isn't very helpful. Here are all messages about the file that was changed:
```
Server response: STATUS:OK:/home/kamm/ownCloud2/foofile2
Server response: STATUS:OK:/home/kamm/ownCloud2/foofile2
Server response: STATUS:SYNC:/home/kamm/ownCloud2/foofile2
Server response: STATUS:OK:/home/kamm/ownCloud2/foofile2
Server response: STATUS:OK:/home/kamm/ownCloud2/foofile2
```

**Comment by guruz** [comment]
Closing in favor of https://github.com/owncloud/client/issues/3249
