### ISSUE TITLE
Client does not show a spinner when search for users might take longer

### ISSUE THREAD

**Issue by butonic** [owncloud/client#4740]
opening an issue as reported in https://github.com/owncloud/core/issues/22652#issuecomment-212309038

If I am incorrect pleaso tick the corresponding box in https://github.com/owncloud/core/issues/22652#issuecomment-211354727

**Comment by dragotin** [comment]
@butonic I made that purple, I hope you agree...

**Comment by rullzer** [comment]
I'll check this out... and add the spinner... lets get this into 2.2 as well

**Comment by rullzer** [comment]
PR  in #4764

**Comment by mcastroSG** [comment]
Hi hi:

**Steps Executed**

1. Right click over a file at Sync shared folder and select "Share with ownCloud"
2. Fill UsersOrGroups field with a generic value

**Results**

While searching is done a spinner is shown.

OS X: 

Client OS: OS X El capitán 10.11.4
Client Version: Version 2.2.0-nightly20160504 (build 3332)

OS Linux

Client OS: Ubuntu 14.04 LTE
Client Version: Version 2.2.0nightly201654 (build 1587)

Server OS: Ubuntu
Server Version: 9.1 Alpha
