### ISSUE TITLE
Provide the option in the Sync client to sync on demand instead of everything

### ISSUE THREAD

**Issue by michae1ho11ey** [owncloud/client#4742]
### Expected behaviour
With a lot of people putting their lives in ownClound then buying low cost computers with limited drive space it would be nice to enable on those installs a features that allows seeing all files in ownCloud but only downloading/sync files on demand.

Basically the same functionality in iOS/Android clients. This is a coming feature to Dropbox as well: https://blogs.dropbox.com/business/2016/04/announcing-project-infinite/

### Actual behaviour
When a sync client is connected to an ownCloud install all files available to that user is downloaded/synced to the local computer.

### Server configuration
Operating system: Ubuntu 14.04 (via Docker)
Web server: Apache2
Database: MySQL
PHP version: 5.6
ownCloud version: 9
Storage backend: ZFS

### Client configuration
Client version: 2.1.1
Operating system: Mac 10.11.4
OS language: English
Installation path of client: /Aplications

**Comment by guruz** [comment]
Thanks, please click a 👍 to https://github.com/owncloud/client/issues/4341
