### ISSUE TITLE
visual improvement: tree focus in select remote folder window

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#4745]
When I copy/paste a full path, the tree opens and gets selected but the view should also be centered around the selection. Currently it is not the case, as you can see in the screenshot below (there is a very long list of directories to scroll before reaching my path for further inspection):

![image](https://cloud.githubusercontent.com/assets/621965/14845060/1e1cf822-0c5c-11e6-88d6-cec4b4197439.png)

**Comment by mcastroSG** [comment]
Hi hi:

**Steps Executed**

1. Add Folder Sync Connection
2. Select a local folder
3. Paste a path at remote destination folder

**Results**

After paste the view is centred at the selected path.

OS X 
Client OS: OS X El capitán 10.11.4
Client Version:Version 2.2.0beta2 (build 3326).

OS W
Client OS: W10
Client Version: Version 2.2.0-nightly20160503 (build 6048)
