### ISSUE TITLE
visual improvement: error reporting in select remote folder window

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#4746]
The error reporting is not consistent. I have a directory for which the server replies Method Not Allowed on PROPFIND.

When I try to open it using the tree browser I get the error:
![image](https://cloud.githubusercontent.com/assets/621965/14845145/aa59adf8-0c5c-11e6-8683-fd7056ace12e.png)

When I type in the path I do not see any error but you can see in the logs that the error was reported by the server:

![image](https://cloud.githubusercontent.com/assets/621965/14845250/3d807206-0c5d-11e6-9a88-a9ca8eb12032.png)

Also the error message a bit too verbose for the end user: just "Method Not Allowed" (in red or in bold) and the path in question would be sufficient instead of full URL (and "downloading...")

**Comment by ckamm** [comment]
@moscicki It shows all errors but 404 errors now. I think that leads to the nicest user experience, because otherwise the error message popped up in a lot of situations when you didn't expect it (like partially typed paths). It's still clear to a user whether a given path is valid or not (Next button and selection in the tree widget).

**Comment by moscicki** [comment]
That's fast - thank you :-)

What about simplifying the error message? Something like for example:
Failed to list "/shared" folder: Method Not Allowed.

About 404: yes I agree. On the other hand, maybe you can consider to wait 1 or 2 seconds since the last character was entered and then display 404? I am not sure how complex that is in Qt so maybe it is not worth doing it...

**Comment by mcastroSG** [comment]
Hi hi:

**Steps Executed**

1. Add a new Shared sync folder
2. Select local folder
3. Write path for remote folder.

**Results**

Continue Button is not enabled until a valid path is set. In this way there is no error shown anymore while typing a proper path.

Client OS: OS X El capitán 10.11.4
Client Version: Version 2.2.0-nightly20160428 (build 3312)

Client OS: W7
Client Version : Version 2.2.0-nightly20160428 (build 6035)

Server OS: Ubuntu
Server Version : 9.1.0 Alpha
