### ISSUE TITLE
 Critical extension is unavailable 

### ISSUE THREAD

**Issue by heliasanaz** [owncloud/client#4749]
Hi,

i have installed OWNCLOUD 9 with centos7.in my UI there is error:
	ldap_control_paged_result_response(): Result is: Critical extension is unavailable (12) at /var/www/html/owncloud/apps/user_ldap/lib/ldap.php#70 

please help me.
Thank you

**Comment by guruz** [comment]
Please try on https://github.com/owncloud/core

**Comment by heliasanaz** [comment]
Thank you.but what shall i do.
