### ISSUE TITLE
[MultiOS][Shared branding On/Off]  Desktop client shows wrong options at "Shared with owncloud" contextual menu

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4750]
### Expected behaviour
After compile a new build setting:

userGroupSharing
linkSharing

with proper values Desktop Client should show sharing options according to values defined at those variables.

### Actual behaviour

**userGroupSharing --> False**
**linkSharing --> True**

Works fine 

Client configuration
Client version: Version 2.2.0-nightly20160426 (build 3302).
Operating system: OS X 10.11.4

Client configuration
Client version: Version 2.2.0-nightly20160426 (build 6025)
Operating system: W7/W81

Does not work at W10, there is no "Share with ownCloud" option at contextual menu.

**userGroupSharing --> False**
**linkSharing --> False**

Works but something has to be reviewed, "Share with ownCloud" appears at contextual menu , but in case we select this option nothing happens, may be and alert should be raised in case or even disable this option at contextual menu.

OS X
 
Client configuration
Client version: Version 2.2.0-nightly20160428 (build 3315)
Operating system: OS X 10.11.4

Windows 

Client configuration
Client version: Version 2.2.0-nightly20160428 (build 6033)
Operating system: W7/W81/W10

**userGroupSharing --> True
linkSharing --> False**

Works fine.

OS X

Client configuration
Client version: Version 2.2.0-nightly20160428 (build 3316)
Operating system: OS X 10.11.4

Windows 

Client configuration
Client version: Version 2.2.0-nightly20160428 (build 6035)
Operating system: W7/W81/W10

### Steps to reproduce
1. Install proper version of Desktop client

### Server configuration
Operating system: Ubuntu
ownCloud version: 9.1.0 Alpha

**Comment by rullzer** [comment]
Mmmmm I'll look into this (probabaly on friday)

**Comment by mcastroSG** [comment]
Finally tested again and working fine.
