### ISSUE TITLE
Don't skip uploads when checksum is unchanged

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#4754]
We enabled content checksum based upload skipping in #4375. Now we're concened that not updating mtimes on the server might break some customer use cases.

We want to revert the behavior to apply the "skip upload" workaround only for *.eml files, as before.

There'll be a different ticket to move this forward again (by including a PROPSET that updates the server mtime and possibly skipping unnecessary downloads if only the metadata changed).

**Comment by mcastroSG** [comment]
Works fine, just for eml files downloads are skipped.

[Tests](https://github.com/owncloud/client/issues/3735#issuecomment-218386511)
