### ISSUE TITLE
Activity tab entry in the system-tray menu?

### ISSUE THREAD

**Issue by nickvergessen** [owncloud/client#4759]
I catch myself running into that multiple times a day.
When I want to check if something happened in an instance, I click on the system tray, then on the profile. Then I check the sub menu, can't find activity and then I remember, that I have to go via Settings (Einstellungen), which is really not very obvious to me, because you don't change anything, you want to see something.

![bildschirmfoto vom 2016-04-28 14 58 30](https://cloud.githubusercontent.com/assets/213943/14886606/e6794000-0d51-11e6-8d43-a2ce794ac612.png)

I guess that is, because the activity tab is not split per instance, but I think it would still be good to have it as an entry in the menu

**Comment by guruz** [comment]
Do you have a dubt about the changes menu is not up to date?
Maybe there should be an easier way to reach the activities from the tray.

> I guess that is, because the activity tab is not split per instance

I'm not sure it will ever be split unfortunately. See also https://github.com/owncloud/client/issues/4716

FYI @jancborchardt @dragotin

**Comment by nickvergessen** [comment]
> Do you have a dubt about the changes menu is not up to date?

Well that is only for syncs right? So non-file activities are not listed there, also with multiple instance in the sync client the small number of entries does not help me, because the active instance always is on top.

Okay I just know found the "Details" link on the "Last Changes" which leads to the activity tab. I guess that also works then, just have to get used to it.

**Comment by dragotin** [comment]
Actually I agree we should have an entry to the activities in the menu. But I a worm. @jancborchardt should know.

**Comment by ckamm** [comment]
"Recent Changes -> Details..." brings up the activity tab for me.

**Comment by jancborchardt** [comment]
Yeah, as @ckamm noted that’s the shortcut. Otherwise well … there’s the improved tray menu concept ;) https://github.com/owncloud/client/issues/1748

**Comment by ckamm** [comment]
@nickvergessen Does that work for you?

**Comment by nickvergessen** [comment]
Yeah I gues with #1748 it's fine with the current state
