### ISSUE TITLE
[Windows] [2.2.0 beta1] OS notification when conflict happens during synchronisation

### ISSUE THREAD

**Issue by robinschu** [owncloud/client#4761]
Build: ownCloud desktop client release version 2.2.0 beta1 (Windows)

### Expected behaviour

When creating a conflict - e.g. 

1. User A works on "test.txt" in local folder - adds a few lines
2. User B works simultaneously on "test.txt" in local folder - adds a few lines too
3. User A saves and sychronises "test.txt" 
4. User B saves and synchronises too - "test.txt" shows in Tab "not synchronized" in the GUI

A toast message should appear at the tray-icon that shows the user a message like "conflict when syncing file "test.txt""

### Actual behaviour
Everything works fine. But no Toast-Message appears and User does not get notified, only noticable in GUI.

### Steps to reproduce

see above

### Client configuration
Client version: ownCloud desktop client release version 2.2.0 beta1 (Windows)

Operating system: Win 8.1

OS language: German

Installation path of client: C:\Program Files (x86)\ownCloud

**Comment by dragotin** [comment]
This should be fixed, see 52a52341227bb9dc31af74bae0645d96b8ece469

**Comment by mcastroSG** [comment]
Hi hi 

**Steps Executed**

1. User A works on "test.txt" in local folder - adds a few lines
2. User B works simultaneously on "test.txt" in local folder - adds a few lines too
3. User A saves and sychronises "test.txt"
4. User B saves and synchronises too - "test.txt" shows in Tab "not synchronized" in the GUI

**Results**

It works, a new toast message appears.

Server OS: Ubuntu
Server Version: 9.1.0
Client OS: Windows 8.1
Client Version:Version 2.2.0-nightly20160509 (build 6062)
