### ISSUE TITLE
Login with user from user_sql plugin not reliable

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/client#4763]
### Expected behaviour
User can login

### Actual behaviour
"unknown error" is displayed after entering username and password.

### Steps to reproduce
1. create new account
2. enter server url, username & password
3. sometimes "unknown error", if not successfull, restart client until it works

### Server configuration
Operating system: Linux

Web server: Apache

Database: Mysql

PHP version: 5.6.18

ownCloud version: 8.1.3

Storage backend:

### Client configuration
Client version: 2.1.0

Operating system: Gentoo/Linux

OS language:

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.
Client failing to sync files:
04-29 07:56:05:432 0x18c44d0 void OCC::PropagateDownloadFileQNAM::slotGetFinished()  QUrl( "https://SERVERURL/remote.php/webdav/Photos/Paris.jpg" )  FINISHED WITH STATUS 2 "Verbindung beendet" 0 219808 228761 0 "" "" 
04-29 07:56:05:434 0x18c44d0 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "Photos/Paris.jpg" INSTRUCTION_CONFLICT 1 "Verbindung beendet" 
04-29 07:56:05:443 0x18c44d0 void OCC::AbstractNetworkJob::slotFinished() 99 "Unbekannter Fehler" QVariant(, )

**Comment by guruz** [comment]
> Verbindung beendet

Sounds like the typical "Connection Closed" bug we've seen a lot. Can you check the Qt version? Should be somewhere in the log.
Also make sure you have HTTP Keep Alive enabled in your webserver..

**Comment by danimo** [comment]
We need the server log (`owncloud.log`), as well as the access log.

**Comment by tobiasKaminsky** [comment]
Evereything is working if I am not in the intranet.
So closing for now.

Sorry for the inconvenience.
