### ISSUE TITLE
Improvements in Brazilian translation

### ISSUE THREAD

**Issue by brunno18** [owncloud/client#4767]
Some issues in client 2.1.1 and previous versions.

1: The close button is not translated.
![issueoneo](https://cloud.githubusercontent.com/assets/4140037/14927583/315099f2-0e29-11e6-99a8-0b55ecb25307.png)

2: typo in general tab: space not used. Missing space between two words “visite” and “owncloud.com” .
![issuetwo](https://cloud.githubusercontent.com/assets/4140037/14927593/39899d26-0e29-11e6-93bc-992f5248f147.png)

3: Layout problem in general tab in "Restart and Update" button. The button size is disproportionate towards the text .
![issuethree](https://cloud.githubusercontent.com/assets/4140037/14927596/3ed86c3a-0e29-11e6-8c2f-86cb976d3c5a.png)

**Comment by MTRichards** [comment]
Good catch, thank you. Hopefully we can roll these in.

**Comment by dragotin** [comment]
Please contribute to the translations in transifex. We can not fix that here.

**Comment by ogoffart** [comment]
1. The close button label is part of the Qt translation. Maybe Qt translations are not properly loaded?
2. Need to be reported on transifex.
3. I could not reproduce this problem, perhaps it was fixed already
