### ISSUE TITLE
Client unable to sync files from encrypted external storage

### ISSUE THREAD

**Issue by TecJon** [owncloud/client#4768]
I am setting up webdav MagentaCloud as an external storage with encryption. Files appear in the oc web interface and encrypted on the external storage. The client, however, could not sync the files on the external storage.
### Expected behaviour

Windows Client syncs files from external storage.
### Actual behaviour

Client syncs folders of the external storage but is unable to download a file created in the web interface. (It is also unable do upload files copied to the folder in Windows).
### Steps to reproduce
1. Successfully enable external storage (and encryption) in admin panel
2. Use client to sync to windows.
### Server configuration

Operating system: Ubuntu 14.04

Web server: nginx

Database: MySQL

PHP version: PHP 5.5.9-1ubuntu4.14 (fpm-fcgi) (built: Oct 28 2015 01:38:24)

ownCloud version: 9.0.1.3
### Client configuration

Client version: 2.1.1

Operating system: Windows 10 64Bit

OS language: EN

Installation path of client: C:\Program Files (x86)\ownCloud
### Logs
1. Output of owncloudsync.log
   ```#=#=#=# Syncrun started 2016-04-29T23:11:03 until 2016-04-29T23:11:09 (6179 msec)
   |0|MagentaCloud|INST_NEW|Down|1461962071|b-3-531a590288f72|0|00084372oc8ab27a8968|4||0|0|0|||INST_NONE|
   |0|MagentaCloud/test|INST_NEW|Down|1461962071|19-3-531a590d72827|0|00084399oc8ab27a8968|4||0|0|0|||INST_NONE|
   |0|MagentaCloud/test/test.txt|INST_NEW|Down|1461962071|1a-20a0-531a591f86d22|48|00084406oc8ab27a8968|2|Error downloading https://cloud.example.com/remote.php/webdav/MagentaCloud/test/test.txt - server replied: Internal Server Error|500|0|0|||INST_NONE|
   # =#=#=# Syncrun started 2016-04-29T23:12:07 until 2016-04-29T23:12:13 (5865 msec)
   
   |0|MagentaCloud|INST_SYNC|Down|1461962071|b-3-531a590288f72|0|00084372oc8ab27a8968|4||0|0|1461964268|||INST_NONE|
   |0|MagentaCloud/test|INST_SYNC|Down|1461962071|19-3-531a590d72827|0|00084399oc8ab27a8968|4||0|0|1461964269|||INST_NONE|
   |0|MagentaCloud/test/test.txt|INST_NEW|Down|1461962071|1a-20a0-531a591f86d22|48|00084406oc8ab27a8968|6|Continue blacklisting: Error downloading https://cloud.example.com/remote.php/webdav/MagentaCloud/test/test.txt - server replied: Internal Server Error|500|0|0|||INST_NONE|```
2. Web server error log:
   `2016/04/29 23:12:18 [error] 12382#0: *65628 access forbidden by rule, client: XXX.XXX.XXX.XX, server: cloud.example.com, request: "GET /data/.ocdata HTTP/1.1", host: "cloud.example.com"`
3. ownCloud log (data/owncloud.log):
   `{"reqId":"QbEqfxUt7Z3XPzjF9\/sj","remoteAddr":"XXX.XXX.XXX.XX","app":"webdav","message":"Exception: {\"Message\":\"Missing Signature\",\"Exception\":\"OC\\\\HintException\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(527): OCA\\\\Encryption\\\\Crypto\\\\Crypt->hasSignature('---------------...', 'AES-256-CTR')\\n#1 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php(460): OCA\\\\Encryption\\\\Crypto\\\\Crypt->splitMetaData('---------------...', 'AES-256-CTR')\\n#2 \\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/encryption.php(363): OCA\\\\Encryption\\\\Crypto\\\\Crypt->symmetricDecryptFileContent('---------------...', '?{?p?x???py8??...', 'AES-256-CTR', 2, '0end')\\n#3 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(459): OCA\\\\Encryption\\\\Crypto\\\\Encryption->decrypt('---------------...', '0end')\\n#4 \\\/var\\\/www\\\/owncloud\\\/lib\\\/private\\\/files\\\/stream\\\/encryption.php(290): OC\\\\Files\\\\Stream\\\\Encryption->readCache()\\n#5 [internal function]: OC\\\\Files\\\\Stream\\\\Encryption->stream_read(8192)\\n#6 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/Wrapper.php(83): fread(Resource id #96, 8192)\\n#7 \\\/var\\\/www\\\/owncloud\\\/apps\\\/files_external\\\/3rdparty\\\/icewind\\\/streams\\\/src\\\/CallbackWrapper.php(91): Icewind\\\\Streams\\\\Wrapper->stream_read(8192)\\n#8 [internal function]: Icewind\\\\Streams\\\\CallbackWrapper->stream_read(8192)\\n#9 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/http\\\/lib\\\/Sapi.php(78): stream_copy_to_stream(Resource id #99, Resource id #101, '48')\\n#10 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(470): Sabre\\\\HTTP\\\\Sapi::sendResponse(Object(Sabre\\\\HTTP\\\\Response))\\n#11 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#12 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#13 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#14 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/encryption\\\/lib\\\/crypto\\\/crypt.php\",\"Line\":562,\"User\":\"admin\"}","level":4,"time":"2016-04-29T21:12:13+00:00","method":"GET","url":"\/remote.php\/webdav\/MagentaCloud\/test\/test.txt","user":"admin"}`

**Comment by SamEliotFisher** [comment]
After trying to open the file in the web interface I get a `File Not Found error`.
The log from the admin panel shows several entries like this:
`Cannot modify header information - headers already sent by (output started at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php:80) at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#63`
Directly accessing the external storage shows that the file is still there.

As this may seem a problem with encryption I had the error of the client not syncing external storage before when I wasn't using encryption.

**Comment by MTRichards** [comment]
>As this may seem a problem with encryption I had the error of the client not syncing external storage before when I wasn't using encryption.

Was this error fixed previously?

**Comment by SamEliotFisher** [comment]
No, it was an early version of external storage (and owncloud) and known to have issues with Telekom's "Mediencenter"-Cloud so I simply disabled it again.

**Comment by SamEliotFisher** [comment]
### Additional Behavior
1. Create empty text file on client side
2. It is successfully synced 
2. Add content on client side.
3. Get second conflicted file and owncloudsynclog output

`21:00:36|573|MagentaCloud/test/clientside.txt|INST_SYNC|Down|1462050030||9||7|Not allowed to upload this file because it is read-only on the server, restoring|0|0|1462049982|1b-2000-531ba0a4e4a17|00084450oc8ab27a8968|INST_NONE|`

**Comment by guruz** [comment]
Does this still happen with a newer server version?

**Comment by hodyroff** [comment]
No reaction. If there is new info, please just comment and we will reopen.
