### ISSUE TITLE
[Win] [2.2.0 beta1] Server messages in share view too pale

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#4773]
@dragotin The error message is nearly invisible:

![c988db4a-0d33-11e6-9edf-02f231289337 2](https://cloud.githubusercontent.com/assets/214010/14952115/e184bca0-105d-11e6-86cc-d56fb7cd3a34.png)

Text color switches to black after the user clicks to another application window.

**Comment by ogoffart** [comment]
What are the step to reproduce this error?  My server accept any password.  How do i configure password restrictions?

**Comment by rullzer** [comment]
@ogoffart password_policy app

**Comment by dragotin** [comment]
@ogoffart that is a generic error message. It can be any reply message from the server I guess.

**Comment by ogoffart** [comment]
yes, i'm just trying to get one of these message from the server

**Comment by mcastroSG** [comment]
Tested at OS X and Ubuntu and works .. but blocked by [https://github.com/owncloud/client/issues/4781](url) for W testing

**Comment by mcastroSG** [comment]
Tested at W10 also and working fine
