### ISSUE TITLE
[Arch Linux] [kwallet] owncloud client still asking for a password

### ISSUE THREAD

**Issue by hnykda** [owncloud/client#4777]
Hello,

I am experiencing quite common bug again. It's probably because of different key-chains. I have `qtkeychain 0.6.1-1` installed. I am experiencing this on several machines. When I tried to install `kwallet` on the other machine, it still doesn't work (the error message is different, though... Nevertheless, it should work even without that, no?).

### Expected behaviour
Booting up my computer and owncloud client would start without asking me for my password

### Actual behaviour
Asks me for my password with the following:
![image](https://cloud.githubusercontent.com/assets/2741256/14963505/3165539c-10a4-11e6-8dc6-54b3853ea32b.png)

### Steps to reproduce
1. Boot up archlinux
2. Wait till client starts

### Server configuration
Operating system: Arch Linux 

Web server: 
owncloud.cesnet.cz

ownCloud version:

### Client configuration
Client version: `owncloud-client 2.1.1-3`

Operating system: `Arch Linux `, `linux 4.5.1-1` 

OS language: EN

Installation path of client:
```
owncloud-client /etc/
owncloud-client /etc/ownCloud/
owncloud-client /etc/ownCloud/sync-exclude.lst
owncloud-client /usr/
owncloud-client /usr/bin/
owncloud-client /usr/bin/owncloud
owncloud-client /usr/bin/owncloudcmd
owncloud-client /usr/include/
owncloud-client /usr/include/owncloudsync/
owncloud-client /usr/include/owncloudsync/creds/
owncloud-client /usr/include/owncloudsync/creds/abstractcredentials.h
owncloud-client /usr/include/owncloudsync/creds/httpcredentials.h
owncloud-client /usr/include/owncloudsync/mirall/
owncloud-client /usr/include/owncloudsync/mirall/account.h
owncloud-client /usr/include/owncloudsync/mirall/configfile.h
owncloud-client /usr/include/owncloudsync/mirall/networkjobs.h
owncloud-client /usr/include/owncloudsync/mirall/progressdispatcher.h
owncloud-client /usr/include/owncloudsync/mirall/syncengine.h
owncloud-client /usr/include/owncloudsync/mirall/syncfileitem.h
owncloud-client /usr/include/owncloudsync/mirall/syncjournaldb.h
owncloud-client /usr/include/owncloudsync/mirall/syncresult.h
owncloud-client /usr/lib/
owncloud-client /usr/lib/libownclouddolphinpluginhelper.so
owncloud-client /usr/lib/libowncloudsync.so
owncloud-client /usr/lib/libowncloudsync.so.0
owncloud-client /usr/lib/libowncloudsync.so.2.1.1
owncloud-client /usr/lib/owncloud/
owncloud-client /usr/lib/owncloud/libocsync.so
owncloud-client /usr/lib/owncloud/libocsync.so.0
owncloud-client /usr/lib/owncloud/libocsync.so.2.1.1
owncloud-client /usr/lib/qt/
owncloud-client /usr/lib/qt/plugins/
owncloud-client /usr/lib/qt/plugins/kf5/
owncloud-client /usr/lib/qt/plugins/kf5/overlayicon/
owncloud-client /usr/lib/qt/plugins/kf5/overlayicon/ownclouddolphinoverlayplugin.so
owncloud-client /usr/lib/qt/plugins/ownclouddolphinactionplugin.so
...truncated...
```

#### Logs
This is the only thing what I see in console:
`Gkr-Message: secret service operation failed: The name org.freedesktop.secrets was not provided by any .service files`

**Comment by ogoffart** [comment]
Are you running KDE Plasma?
What are the value of the environement variable `XDG_CURRENT_DESKTOP` and `KDE_SESSION_VERSION` ?   They need to be equal to `KDE` and `5`respectively for qtkeychain to use kwallet.

It seems qtkeychain detects that you are using the gnome keyring instead.
Please fill a bug in qtkeychain. because that's qtkeychain responsability to use the right backend.

**Comment by guruz** [comment]
-> https://github.com/frankosterfeld/qtkeychain/issues

**Comment by hnykda** [comment]
@ogoffart OK, thank you for your help. I am not running KDE Plasma, but i3. Non of those env variables are set. I installed gnome-keyring, now the error message is different but it is still asking for a password. Will submit that as an issue on qtkeychain. 
Thanks and sorry for that
