### ISSUE TITLE
[Windows] Client and taskbar icon report different sync status

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#4778]
### Expected behaviour
When a sync runs, I see in the opened client window the green progess bar and the statement that it is syncing. The icon in the taskbar should also report the correct sync status
![image](https://cloud.githubusercontent.com/assets/3321281/14978093/ba369e54-1119-11e6-81e6-6bf0447f42f2.png)

### Actual behaviour
The icon in the taskbar reports waiting...
![image](https://cloud.githubusercontent.com/assets/3321281/14978138/0cf158dc-111a-11e6-8097-c330268151d0.png)

### Steps to reproduce
1. Sync data
2. Check client sync status
3. Hover over the taskbar icon to see the status

### Server configuration
Operating system: Ubuntu 14.04

Web server: nginx

Database: mysql

PHP version: 5.5.9

ownCloud version: ownCloud 9.0.2 RC1 (daily) Build:2016-04-28T03:03:12+00:00 795f321a1985b682bff584f252dd6f2fd95dad65

Storage backend:

### Client configuration
Client version: 2.1.1 (build 5837)

Operating system: W7x64

OS language: German

Installation path of client: standard

**Comment by dragotin** [comment]
Could you please try with our new Beta version of the next client, to be downloaded from https://owncloud.org/install/#testing-development ? It works fine here for me with that version on Linux.

**Comment by mmattel** [comment]
Downloaded, checked and is fixed with the beta. Messages are in sync now.
When will this version be released?

**Comment by dragotin** [comment]
@mmattel thanks for confirmation. The release is planned for mid of May.
