### ISSUE TITLE
[Overlay][Windows] No "Share with Owncloud" menu option appears

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4781]
### Expected behaviour
An overlay icon should appear at any file or folder synced at share sync folder. Also after right click over one of these folders or files "Share with ownCloud" option should appear.

### Actual behaviour
No overlay icon or "Share with ownCloud" option is shown

### Steps to reproduce
1. Open Shared sync folder
2. Right click on one file or folder

### Server configuration
Operating system: Ubuntu
ownCloud version: 9.1.0 Alpha

### Client configuration
Client version: Version 2.2.0beta2 (build 6044)
Operating system: W10 / W81 / W7

**Comment by guruz** [comment]
@mcastroSG Also after relogin/reboot?

FYI @jturcotte @danimo

**Comment by mcastroSG** [comment]
@guruz Also after reboot.

**Comment by guruz** [comment]
Let's test ```ownCloud-2.2.0.6048-nightly20160503-setup.exe``` .. this might possibly be fixed by https://github.com/owncloud/client/issues/4762

**Comment by mcastroSG** [comment]
Tested with `ownCloud-2.2.0.6048-nightly20160503-setup.exe` , after reboot overlay icons are shown but still no "Share with ownCloud" option.

**Comment by guruz** [comment]
I don't see ``` OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Share with ownCloud"``` in the log.. could this be the cause @jturcotte @danimo  ?

I also see an ```assert(!info.shareMenuTitle.empty());``` in our code.. although ad5620efb5dbd2d78e39d1bf31abb7eea16557f8 disables the assert..
But maybe an empty menu item would not be created anyway.

**Comment by guruz** [comment]
I think the problem is @danimo 's pipename. i can try to fix..

https://github.com/owncloud/client/blob/d7bd1300a8397c2782e8d75cf7c595b1ada70d88/shell_integration/windows/OCContextMenu/OCClientInterface.cpp#L39

**Comment by danimo** [comment]
@guruz Indeed :(. So much for shared code.

**Comment by guruz** [comment]
TBD: Rebuild the MSVC project in getusername_windows_context branch and push to getusername_windows_context branch, then have it tested.

**Comment by mcastroSG** [comment]
Hi hi:

After some test with Version 2.2.0-nightly20160510 (build 6066):

**W81, W7:** Uninstall, install and reboot: Show overlay icons and share with ownCloud option

After click over share with ownCloud option nothing happends, there is no popup to share the file or folder.

**W10:** Uninstall, intall and reboot: Does not show overlay icon or share with ownCloud option

**Comment by guruz** [comment]
```
05-10 13:48:57:219 0x3877d0 OCC::SocketApi::slotNewConnection: SocketApi:  New connection QLocalSocket(0x8f79a48)
05-10 13:48:57:219 0x3877d0 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "REGISTER_PATH:C:\Users\woboq\ownCloud"
05-10 13:48:57:219 0x3877d0 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Share with ownCloud"
05-10 13:48:57:344 0x3877d0 OCC::SocketApi::onLostConnection: SocketApi:  Lost connection  QLocalSocket(0x8f79a48)
```

It immediatly loses the connection after i click the right mouse button and the menu is shown

**Comment by jturcotte** [comment]
Maybe it doesn't have the permission to write to the pipe, or something like that?
Could also be that the COM object gets unloaded because of some error.

**Comment by mcastroSG** [comment]
Hi hi:

Tested with Version 2.2.0-nightly20160510 (build 6067) at W7, W81 and W10 and working.
