### ISSUE TITLE
Windows 7  right button of the mouse, file cannot be shared

### ISSUE THREAD

**Issue by plantie** [owncloud/client#4783]
### Expected behaviour
Tell us what should happen
Windows 7  right button of the mouse, share file 
### Actual behaviour
Tell us what happens instead
hello
on  Windows 7
I do not succeed to share files with the the right button of the mouse.
Message :
The file cannot be shared because it has been shared with no permission of re-sharing

(in french "Le fichier ne peut pas être partagé car il a été partagé sans permission de repartage.")
can you help me to share files with windows and the right button of the mouse ?
thanks
Michel Plantié
### Steps to reproduce
1. right button clic on mouse
2. share with own cloud
3. share as a link

### Server configuration
Operating system:
windows seven
Web server: 
https://webpartage.mines-ales.fr
Database:
?
PHP version:
?
ownCloud version:
6.0
Storage backend:
?
### Client configuration
Client version:
2.1.1
Operating system:
windows 7
OS language:
french
Installation path of client:
"C:\Program Files (x86)\ownCloud\owncloud.exe"
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
Your ownCloud server is too old, sorry.

It might be that we have a workaround in 2.2.0 (see the "testing" section on https://owncloud.org/install/ ) but I'm not 100% sure.

FYI @rullzer @ogoffart @ckamm

**Comment by rullzer** [comment]
As far as I know nope... you need to upgrade. Also ownCloud 6 is already end of life for some time!
