### ISSUE TITLE
[Overlay] Once a file or folder is shared overlay icon is not updated

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4785]
### Expected behaviour
Once a file or folder is shared overlay icon should be updated to a "green shared" icon

### Actual behaviour
Once a file or folder is shared the same "green check" icon remains

### Steps to reproduce
1.  Right click over a file or folder
2. Select "Share with ownCloud" option 
3. Pick an user or group and share with it the file

### Server configuration

Server OS: Ubuntu 
Server version: 9.1.0 Apha

### Client configuration

OS X
Client OS: OS X El capitán 10.11.4
Client Version: Version 2.2.0-nightly20160504 (build 3331)

OS Linux
Client OS: Ubuntu 14.04 LTE
Client Version: Version 2.2.0nightly201654 (build 1587)

**Comment by dragotin** [comment]
The share icon only indicates that a file was shared **with** me but currently not if it was shared **by** me.

**Comment by rperezb** [comment]
@dragotin not sure, about it

If we have a look at the web:

- when you share something with another user
![screen shot 2016-05-04 at 13 31 40](https://cloud.githubusercontent.com/assets/1846927/15012958/d55fa89a-11fc-11e6-8303-c55249793bc4.png)

- when someone shares something with you
![screen shot 2016-05-04 at 13 33 59](https://cloud.githubusercontent.com/assets/1846927/15012970/ec419d5c-11fc-11e6-9a0f-3be8c0e7c4a6.png)

I mean, there are icons in both cases. Plus on the mobile side we follow this approach too

It'd be great if the desktop follows the same, as part of the parity goal 😃 

Certainly, this is an enhancement for next versions, not the following one

@owncloud/designers @MTRichards @cmonteroluque what do you think?

**Comment by dragotin** [comment]
I see. And I agree. But see explanation in  owncloud/core#10247 

How do the mobile clients query the information?

**Comment by jancborchardt** [comment]
Also agree that the icon should definitely show in both cases.

cc @davivel @javiergonzper how do the mobipe clients do this, see @dragotin's question above.

**Comment by rperezb** [comment]
@dragotin we take advantage of the Share api to get those data shared BY YOU (https://doc.owncloud.org/server/8.2/developer_manual/core/ocs-share-api.html)

In the case of data shared with you it's taken from the propfind

**Comment by davivel** [comment]
We make an extra call to the share API every time a folder is refreshed, calling ```GET [server]/ocs/v1.php/apps/files_sharing/api/v1/shares?path=[folder]&reshares=false&subfiles=false```

This is done only when the user is browsing through the folders tree. In background refresh (full account sync in Android) updates of shares are ignored.

**Comment by dragotin** [comment]
ok, that wont work for us directly in the share api, but maybe we can store the share-by-me in the journal as a result of the discovery jobs. 

Unfortunately that is nothing we can fix in the scope of 2.2.0. 
@mcastroSG please create a feature request for improving this. Thanks!

**Comment by mcastroSG** [comment]
@dragotin @rperezb [https://github.com/owncloud/client/issues/4788](url)

**Comment by jancborchardt** [comment]
Link somehow doesn't work, here's the correct one: #4788
