### ISSUE TITLE
[Notifications] Announcements generated by Announcement App does not appear at Desktop Client

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4786]
### Expected behaviour
In case of as admin a new announcement is generated at desktop client should appear this announcement at Server activity tab.

### Actual behaviour
Announcementes made from Announcement app does not appear at desktop client.

### Steps to reproduce
1. As admin generate a new announcement and wait till Announced appears
2. At client desktop wait till a new sync is completed

### Server configuration

Server OS: Ubuntu
Server Version: 9.1.0 Alpha

### Client configuration

Client OS : OS X El Capitán 10.11.4
Client Version: Version 2.2.0-nightly20160504 (build 3331)

**Comment by dragotin** [comment]
How long did you wait for it to appear?

**Comment by dragotin** [comment]
The default check interval is fife minutes.

**Comment by mcastroSG** [comment]
@dragotin  at least 20 minutes

**Comment by guruz** [comment]
FYI @nickvergessen

**Comment by dragotin** [comment]
@mcastroSG can you check with wget to access the API directly like this:
```
wget http://<user>:<password>@your-owncloud/ocs/v2.php/apps/notifications/api/v1/notifications
```
Strangely enough it does not work here any more as well. I also do not see new announcements. @nickvergessen

**Comment by dragotin** [comment]
@mcastroSG do you see the notification icon blinking in the webapp?

**Comment by dragotin** [comment]
Hmm, logging in with a different user (not the admin) it shows 2 out of four announcements in the web view.

**Comment by nickvergessen** [comment]
Notifications are triggered via background jobs since the last release, so make sure there is no OCA\AnnouncementCenter\BackgroundJob entry in the oc_jobs table

**Comment by mcastroSG** [comment]
@dragotin i´ve been testing again and both Linux and OSX client works fine. So closing this issue.
