### ISSUE TITLE
[Overlay] Update overlay icon in case of files/folders you are sharing

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4788]
**Expected behaviour**

Once a file or folder is shared overlay icon should be updated to a "green shared" icon

**Actual behaviour**

Once a file or folder is shared the same "green check" icon remains

**Steps to reproduce**
1. Right click over a file or folder
2. Select "Share with ownCloud" option
3. Pick an user or group and share with it the file

**Comment by stonerl** [comment]
@mcastroSG See this bugreport #3043

**Comment by MTRichards** [comment]
As I understand it, the symantecs of the share icon are to be those items that are shared WITH you, not those that are shared by you. This becomes a question of design, really, and there isn't enough real estate on the desktop icons to convey more information.

The question then becomes, what is the desired behavior on all platforms...

@jancborchardt since I know we spent a lot of time writing this up, and I think it was implemented as designed - just confirming.

**Comment by jancborchardt** [comment]
The share icon should show up for any shared file, no matter if it's shared _with_ or _by_ you. The point of the indicator is to state that others have access or can modify.

**Comment by jancborchardt** [comment]
(Pretty sure we specced it this way since that's also exactly how it works in the web interface and mobile apps.)

**Comment by MTRichards** [comment]
Ok. Then we have an update we need to make - either in the API or in the client to get that information. Leaving this here for tracking, and assigning bug status.

**Comment by ckamm** [comment]
Summarizing discussion from #3043 and my current understanding of this issue: The client currently only looks at the "S" permission: "is this shared *with* you?". A new webdav property "share-types" was added (servers >= 9.0.1) that allows the client to easily tell whether something "is shared *by* you". 

If we wanted to show the icon when something is shared, regardless of whether it's *with* the user or *by* the user, we need to query the state of the property from the server, store it in the database and adjust the socket api logic to use that flag.

**Comment by jancborchardt** [comment]
@ckamm just for clarification on the intended design: Yes, we want to show the icon when something is shared, regardless of whether it's with the user or by the user. :)

**Comment by ogoffart** [comment]
Was reverted in commit  efa7821 because this would overload the server to query the shared state.

However maybe this could be un-reverted because of https://github.com/owncloud/core/pull/27284

@PVince81 ?  Would we need a version check?

**Comment by PVince81** [comment]
version check yes, 10.0

**Comment by SamuAlfageme** [comment]
@ogoffart see comments in https://github.com/owncloud/client/issues/6098#issuecomment-337538355 - It still takes a client restart to get the right overlay after you share a file (+ to trigger discovery on that file after actions were performed in it locally - i.e. create a share)

**Comment by ckamm** [comment]
Tested #6098 and works.
