### ISSUE TITLE
owncloudcmd not syncing file attributes in linux.

### ISSUE THREAD

**Issue by hradec** [owncloud/client#4789]
### Expected behaviour

files should be synchronized respecting file attributes stored in owncloud and vice-versa, just like owncloud GUI client does.
### Actual behaviour

owncloudcmd client downlodas/uploads files with standard 644 umask.
owncloud gui client works as expected
### Steps to reproduce
1. owncloudcmd <local folder>  <owncloud server>
### Server configuration

Operating system:
Linux version 4.5.1-1-ARCH (builduser@tobias) (gcc version 5.3.0 (GCC) ) #1 SMP PREEMPT Thu Apr 14 19:36:01 CEST 2016 (x86_64)

Web server: 
apache 2.4.20

Database:
sqlite 3.12.2

PHP version:
php 7.0.6

ownCloud version:
owncloud 9.0.1

Storage backend:
Standard Ext4 partition on SATA 3 disk
### Client configuration

Client version:
owncloud-client 2.1.1

Operating system:
Linux version 4.5.1-1-ARCH (builduser@tobias) (gcc version 5.3.0 (GCC) ) #1 SMP PREEMPT Thu Apr 14 19:36:01 CEST 2016 (i686)

OS language:
English CA

Installation path of client:
/usr/bin/
### Logs

https://gist.github.com/hradec/221560a2aacae9966af3687ddd18dfb4

**Comment by guruz** [comment]
Do you mean that a folder shared to you as read only is synced with r in GUI client but 644 with owncloudcmd?

FYI @ogoffart

**Comment by ogoffart** [comment]
What do you mean by file attributes? Are we talking about marking share folder read only? Or syncing special permissions?
Both the GUI and owncloudcmd should do the same. The owncloud server does not store special file attributes so it's not possible to sync them.  But we mark the files as read only on the file system if they come from read only shares.

**Comment by hradec** [comment]
I mean standard file permissions.

**Comment by ckamm** [comment]
@hradec Standard file permissions are currently not synced. There are talks about how to do this in the future, but no concrete roadmap yet.

What specifically is the difference between the owncloud gui and owncloudcmd that you observe?
