### ISSUE TITLE
server replied: Service Unavaliable/Operation Canceled

### ISSUE THREAD

**Issue by ranaur** [owncloud/client#4790]
### Expected behaviour

Sync the file. I noticed that there the file in the data directory (/Library/WebServer/Documents/f/data/ranaur/files/Documents/@Projetos/20160503 Jogo das Falácias/1.png) does not exist ... and that is strange ...
### Actual behaviour

Can't sync (this error shows on the client)
### Steps to reproduce
1. Just let it syns
### Server configuration

Operating system: MacOSX El Captain

Web server: Apache (native)

Database: sql-lite

PHP version:
PHP 5.5.31 (cli) (built: Feb 20 2016 20:33:10) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies

ownCloud version: 9.0.1 (latest)

Storage backend: 
### Client configuration

Client version: 

ersion 2.1.1 (build 3107). For more information visit owncloud.com
By Klaas Freitag, Daniel Molkentin, Jan-Christoph Borchardt, Olivier Goffart, Markus Götz and others.
Copyright ownCloud, Inc.
Licensed under the GNU General Public License (GPL) Version 2.0
ownCloud and the ownCloud Logo are registered trademarks of ownCloud, Inc. in the United States, other countries, or both.
Built from Git revision eeec89 on Feb 9 2016, 16:22:20 using Qt 5.4.0, OpenSSL 1.0.2f 28 Jan 2016

Operating system:
MacOSX and Windows

OS language:
English

Installation path of client:
~/ownCloud
### Logs
1. Output of `owncloud --logwindow
   [owncloud-client.log.txt](https://github.com/owncloud/client/files/249884/owncloud-client.log.txt)
2. Web server error log:

[access_log.txt](https://github.com/owncloud/client/files/249894/access_log.txt)
[error_log.txt](https://github.com/owncloud/client/files/249895/error_log.txt)
1. ownCloud log (data/owncloud.log):

[owncloud.log.txt](https://github.com/owncloud/client/files/249891/owncloud.log.txt)

**Comment by guruz** [comment]
```Service Unavailable``` is a message from the server

```{"reqId":"iFy0oqZsozc+UAbSkZdI","remoteAddr":"177.133.254.208","app":"PHP","message":"fopen(\/Library\/WebServer\/Documents\/f\/data\/ranaur\/files\/Documents\/@Projetos\/20160503 Jogo das Fal\u00e1cias\/5.png): failed to open stream: No such file or directory at \/Library\/WebServer\/Documents\/f\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"2016-05-05T02:33:48+00:00","method":"GET","url":"\/f\/remote.php\/webdav\/Documents\/@Projetos\/20160503%20Jogo%20das%20Fal%C3%A1cias\/5.png","user":"ranaur"}
{"reqId":"iFy0oqZsozc+UAbSkZdI","remoteAddr":"177.133.254.208","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/Library\\\/WebServer\\\/Documents\\\/f\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/Library\\\/WebServer\\\/Documents\\\/f\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/Library\\\/WebServer\\\/Documents\\\/f\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/Library\\\/WebServer\\\/Documents\\\/f\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/Library\\\/WebServer\\\/Documents\\\/f\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/Library\\\/WebServer\\\/Documents\\\/f\\\/remote.php(138): require_once('\\\/Library\\\/WebSer...')\\n#7 {main}\",\"File\":\"\\\/Library\\\/WebServer\\\/Documents\\\/f\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/file.php\",\"Line\":306,\"User\":\"ranaur\"}","level":4,"time":"2016-05-05T02:33:48+00:00","method":"GET","url":"\/f\/remote.php\/webdav\/Documents\/@Projetos\/20160503%20Jogo%20das%20Fal%C3%A1cias\/5.png","user":"ranaur"}
{"reqId":"y1pjgw9jYqC1JVZVCIYP","remoteAddr":"177.133.254.208","app":"PHP","message":"fopen(\/Library\/WebServer\/Documents\/f\/data\/ranaur\/files\/Documents\/@Projetos\/20160503 Jogo das Fal\u00e1cias\/3.png): failed to open stream: No such file or directory at \/Library\/WebServer\/Documents\/f\/lib\/private\/files\/storage\/local.php#247","level":3,"time":"2016-05-05T02:33:48+00:00","method":"GET","url":"\/f\/remote.php\/webdav\/Documents\/@Projetos\/20160503%20Jogo%20das%20Fal%C3%A1cias\/3.png","user":"ranaur"}
```

CC @PVince81 @DeepDiver1975 @icewind1991

**Comment by guruz** [comment]
Your server runs on OS X? This is actually not supported by ownCloud.

**Comment by ranaur** [comment]
Well, it is working (more or less). After all it is running on apache over
OSX. I have no linux machine left at home. :-)

I copied the missing files and things are working right now. I get some
zero-lenght files when I sync at work (my home connection is a crap for
outside uploads). But this don't happens when I sync locally. I'm still
figuring out why, but my educated guess is that some connection timout is
the culprit (and probably a dull error handling routine). I'll try to mess
with this values a little to figure out if it is the case.
