### ISSUE TITLE
Show all users from LDAP in sharing menu

### ISSUE THREAD

**Issue by gmkrab** [owncloud/client#4791]
### Expected behaviour
Show all users from LDAP

### Actual behaviour
Nothing

### Steps to reproduce
1. Download ownclound mobile/desktop client (for android,ios,windows,linux)
2. Select file and try sharing
3. Press button : "Add user or group" and in search menu press space ( _ ). No result. But in web-client it`s work and show all users in ldap.

### Server configuration
Operating system:
SMP Debian 3.16.7-ckt25-1 (2016-03-06) x86_64 GNU/Linux

Web server: 
apache2                        2.4.10-10+deb8u4 

Database:
mysql-server                   5.5.49-0+deb8u1 

PHP version:
5.6.20-0+deb8u1

ownCloud version:
9.0.1

Storage backend:

### Client configuration
Client version:
Owncloud for Android 
version 2.0.0

Operating system:
Android

OS language:
Russian

**Comment by guruz** [comment]
This is the desktop bugtracker. Unfortunately I have to ask you to check if https://github.com/owncloud/android/issues has this issue already and if not post it there?
