### ISSUE TITLE
[Windows] [Overlay] In case of error at sync, overlay icon is not updated to :x:

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4792]
### Expected behaviour
In case of error trying to sync a file an eye-catching red X.

### Actual behaviour

 Blue cycling icon is not updated with eye-catching red X.

### Steps to reproduce

1. As admin define 50 MB quota for user1 at server
2. As user1 copy some files to exceed defined quota

### Server configuration

Server OS: Ubuntu
Server Version: 9.1.0 Alpha

### Client configuration

Client OS: W81
Client Version:  Version 2.2.0-nightly20160505 (build 6054)

**Comment by mcastroSG** [comment]
After some test finally it works but takes too long to change from blue cycling to red X, update has to be set at the same moment the error is raised.

**Comment by dragotin** [comment]
@jturcotte could you check this?

**Comment by jturcotte** [comment]
That's what #4784 was about, did the PR make it to a build yet? If so, @mcastroSG could you retry?

**Comment by mcastroSG** [comment]
Hi hi: 

Retested withVersion 2.2.0-nightly20160509 (build 6062).

Quota error and bad file name included at shared sync folder works fine so closing this Issue. Still remains this problem in case of another errors returned [#4811](https://github.com/owncloud/client/issues/4811)
