### ISSUE TITLE
Investigate a possibility to regenerate Private Key from mobile client 

### ISSUE THREAD

**Issue by gmkrab** [owncloud/client#4794]
So we have a couple of problems:
1. User should generate Private Key every time when his password changed.
2. Normally to generate Private Key user has to do it manually from web->username->Personal.
3. iOS/android APIs not provide this functionality
4. iOS/android APIs not provide handle of error (when user should to regenerate Private Key manually before getting any respons from server), just common handle like UNHANDLED_HTTP_CODE | UNKNOWN_ERROR

**Comment by danimo** [comment]
This is the tracker for the ownCloud desktop client. Please file issues at https://github.com/owncloud/ios and https://github.com/owncloud/android

**Comment by gmkrab** [comment]
Good. Sorry.
