### ISSUE TITLE
[Overlays] Don't rely on hierarchical SyncFileItems to propagate OK statuses to parent folders during sync

### ISSUE THREAD

**Issue by jturcotte** [owncloud/client#4797]
At the moment we rely on the fact that the SyncEngine will emit itemCompleted for all child tasks before completing parent directory tasks to be able to change those parent status from SYNC to OK.

This has a few problems:
- If the parent folder needs to be created as well, it will have another itemCompleted signal of its own, meaning that the new folder will be in OK state even though its children are still propagated.
- If another child of a parent has an ERROR, the parent will switched to WARN (IGNORE) even though its children aren't done propagating
- For RETRIEVE_FILE_STATUS messages, especially problematic in bulk following an UPDATE_VIEW message, we have to do a O(n) search of the file in the SyncFileItem vector to know if the file is currently syncing and this can slow down the sync for very large initial syncs.

A solution would be to ignore CSYNC_INSTRUCTION_NONE items in SyncFileStatusTracker, and do the child sync tracking directly there with a more adapted data structure to speed up the lookup.

**Comment by jturcotte** [comment]
Idea for an implementation before I forget it:
- Keep a "sync count" for each directory path relative to the folder root in a QHashMap. A file being discovered as needing propagation increases the count of its parent, on completion it reduces the count
- Don't increase the count for all parents to avoid large directory structures being too heavy to process. Instead, increase the count of a directory's immediate parent directory only if the directory's count was 0 (first increase), possibly until the root. And when we decrease from 1 to 0 (last decrease), also reduce the immediate parent, and so on.
- When a directory goes from 0 to 1, send a SYNC status. When it goes from 1 to 0, send an OK status (considering errors that should bubble up, etc).
- A directory that needs propagation for itself (mkdir) increases/decreases its own count following the same rules.
- We can then ignore all INSTRUCTION_NONE items that we receive in SyncFileStatusTracker

**Comment by SamuAlfageme** [comment]
@jturcotte the solution seems to be working after the fix. However, there's some minor delays/glitches in the propagation, see these gifs as example:

* Parents take a bit to change the status in a sync:

![propagation](https://cloud.githubusercontent.com/assets/2644445/20176983/b0da163e-a74a-11e6-88cf-a8add8ff228e.gif)

* A parent appears synced before its children: 

![propagation2](https://cloud.githubusercontent.com/assets/2644445/20177020/e004cfc6-a74a-11e6-98c1-8b202f80616a.gif)

I'm removing the bug tag but letting this open to let some room for improvement.

**Comment by jturcotte** [comment]
Hi, you have quite an eye 😜 

The "Parents take a bit to change the status in a sync" part is because we take a shortcut when the OS tells us that a file was modified. We don't currently take this into account for parent invalidation since this is approximate information, but we could. Do you think it's worth it?

The "A parent appears synced before its children" looks more dirty, could you share some detail how to reproduce it? I think I haven't seen that one before, but maybe I haven't looked hard enough.

**Comment by SamuAlfageme** [comment]
Hi Jocelyn! 👋

For the first one, I'd say that I understand the shortcut in case of the modification (e.g. a document being opened and modified only partially doesn't have to trigger the overlay changes in the whole folder hierarchy). But if there's a way to pull apart which signals are because of a new file upload and which are because of a minor change, I'd take it.

To replicate the second, try the following: 

* Desktop **Client: OC Version 2.3.0-nightly20161109 (build 3806)** - OS X 10.11.6
* Server: **OC EE 9.1.1.3** - Ubuntu 16.04
* Steps: Just drag and drop the entire `Child 1.1.2` folder to a similar dir. structure as the one in the gif.

These are the random files (and their sizes) in that folder:
![screen shot 2016-11-10 at 14 08 26](https://cloud.githubusercontent.com/assets/2644445/20177877/47a62fcc-a74f-11e6-96d8-34f7aea8a5dc.png)

**Comment by SamuAlfageme** [comment]
I'm not familiar enough yet with the log output, but I believe this is happening because the last line should be the first to appear, right?

```
11-10 14:23:59:516 0x7fdd0bd17c50 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/salfageme/ownCloud/Parent/Child 1/Child 1.1/Child 1.1.2"
11-10 14:23:59:518 0x7fdd0bd17c50 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/salfageme/ownCloud/Parent/Child 1/Child 1.1"
11-10 14:23:59:521 0x7fdd0bd17c50 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/salfageme/ownCloud/Parent/Child 1"
11-10 14:23:59:523 0x7fdd0bd17c50 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/salfageme/ownCloud/Parent"
11-10 14:23:59:525 0x7fdd0bd17c50 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/salfageme/ownCloud"
11-10 14:23:59:527 0x7fdd0bd17c50 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/salfageme/ownCloud/Parent/Child 1/Child 1.1/Child 1.1.2/Other.exe"
```

**Comment by jturcotte** [comment]
Sounds about right :)

**Comment by SamuAlfageme** [comment]
Behavior is super nice and smooth now, tested both cases with the original file structure I did back in https://github.com/owncloud/client/issues/4797#issuecomment-259680409 and both cases...

- [x] Parents take a bit to change the status in a sync.
- [x] A parent appears synced before its children.

... are working 🎉🎉
