### ISSUE TITLE
Implement token-based authentication with opening URL in external browser

### ISSUE THREAD

**Issue by jturcotte** [owncloud/client#4798]
QtWebKit is now deprecated and the clock is ticking as Qt 5.6 is going to be the last release that we can rely on it working reliably on all our platforms.

There is the option to switch to QtWebEngine (#4692), but this would triple the size of our binary packages and might not be available on all linux distributions.

Having a custom authentication between the ownCloud client and server would also mean that we don't limit the authentication method supported by the server based on what the client can do.

The general idea would be:
- The user enters the server URL in the client's wizard
- The client asks the server to generate an authentication token
- The client opens the desktop browser passing this token as a GET parameter
- The user authenticates the token by signing in in the ownCloud web application using the configured server auth (user/pass, shibboleth, etc) and then confirm that he wants the client to have access
- The client, meanwhile polling the server for the status of the token, gets told that it was associated with the account xyz through the browser

This will need infrastructure in the server, so we will need to keep using QtWebKit until we can require a server that supports this method.

**Comment by dragotin** [comment]
owncloud/core#23458 and owncloud/core#12102 related

**Comment by dragotin** [comment]
@MTRichards @cmonteroluque @LukasReschke FYI, please consider for quickly on the roadmap, as we (apart from striving for a cool solution) have a problem described in #4692

**Comment by MTRichards** [comment]
OK. I like this idea. But not sure how it integrates with what we have planned...need to connect the dots. @LukasReschke does this complement the plan we discussed for a new auth core in ownCloud?

**Comment by cmonteroluque** [comment]
let's talk later this week

**Comment by dragotin** [comment]
A little image to show how it could work:

![auth_ne](https://cloud.githubusercontent.com/assets/1070214/15319978/42356686-1c2e-11e6-8593-e066a76d24ea.jpg)

**Comment by rullzer** [comment]
Related to #4877

**Comment by rullzer** [comment]
COPIED IN:

In order to support proper 2 factor support on the client we want to change the way you log in.

In order to do this properly with supporting all 2 factor providers out there we figured it is easy to move the auth entirely to the server.

So the workflow:

1. First client start, user enters URL
2. Server reports back that there is 2FA
3. Client registers temp token with server
4. Client opens https://<SERVER>/..../<TEMPTOKEN>
5. Users logs in via web
6. Client gets a real token via its temp token
7. All is well in the world

**Comment by guruz** [comment]
FYI @ChristophWurst

**Comment by ChristophWurst** [comment]
thanks @guruz. Is this what we talked about in the call? cc @danimo

**Comment by rullzer** [comment]
@ChristophWurst yes it is. And what we will discuss in a bit more detail on monday (with the others as well). Basically how to handle 2 factor on the client.

**Comment by butonic** [comment]
https://github.com/owncloud/oauth2 is avalable in 9.1, see https://github.com/owncloud/core/pull/26742
