### ISSUE TITLE
[2.2.0 beta2] [Windows] When sync is paused, folders ar shown as (0B) in size

### ISSUE THREAD

**Issue by oparoz** [owncloud/client#4801]
### Expected behaviour

Folders size should be accurate at all times
### Actual behaviour

Folder size is shown at 0B, probably because incomplete
### Steps to reproduce
1. Sync a folder which contains other folders
2. Pause sync
### Server configuration

Operating system: Ubuntu Core 16.04-pre

Web server: Apache 2.4.20

Database: MySQL 5.7

PHP version: 7.0.5

ownCloud version: 9.0.1

Storage backend:
### Client configuration

Client version: 2.2 beta2

Operating system: Win10

OS language: English

Installation path of client:
### Logs

I don't think they're relevant in this case, but can provide them if needed

**Comment by guruz** [comment]
For me it shows the proper folder size no matter if paused or not.
It will show the _remote_ folder size. Are you sure the folder uploaded already to the server?

**Comment by oparoz** [comment]
The folder was partially uploaded, yes, but it could be related to #4803 and `core` is reporting 0 bytes because a folder with the same name is in the bin.

**Comment by guruz** [comment]
Please comment if this still happens with a recent oC server/client
