### ISSUE TITLE
[Notifications] Include reciever for federated sharing notifications 

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4802]
### Expected behaviour

For those notifications related to federated sharing, a good enhancement could be that reciever appears at notification. Right now if we have configurated several accounts at the same desktop client we are not able to know for who are the sharing we are receiving, just sender and file appears at notification. Notifications appears at Server Activity tab that is common for any account configured so it will be nice to have that extra info available.
### Actual behaviour

For federated sharing notifications just sender and file or folder are included at notification.
### Steps to reproduce
1. Configure two accounts (user1 connected to server1 , user 2 connected to sever2) at a desktop client 
2. As user1 share a file using federated sharing with user2
3. A new notification will appear at server activity tab.

**Comment by TheOneRing** [comment]
@michaelstingl  fixed with https://github.com/owncloud/client/commit/9ed55c9e0586d9ee25ce8f59710be0996a4b0adb ?

**Comment by michaelstingl** [comment]
I think so 👍
