### ISSUE TITLE
File count is inaccurate after sync is paused

### ISSUE THREAD

**Issue by oparoz** [owncloud/client#4803]
### Expected behaviour

File count should be accurate and always show 14187 files

### Actual behaviour

File count is inaccurate and is now telling me that it's syncing 27921 files. This probably also affects the ETA.

### Steps to reproduce
1. Sync a folder containing thousands of files. Mine had 14187 files
2. Pause sync
3. Resume sync

### Server configuration
Operating system: Ubuntu Core 16.04-pre

Web server: Apache 2.4.20

Database: MySQL 5.7

PHP version: 7.0.5

ownCloud version: 9.0.1

Storage backend:

### Client configuration
Client version: 2.2 beta2

Operating system: Win10

OS language: English

Installation path of client:
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`

These commands do nothing

2. Web server error log:

Nothing

3. ownCloud log (data/owncloud.log):

Nothing

**Comment by oparoz** [comment]
Some additional info. I did the following prior to syncing files

1. Create folder1
1. Sync folder1
1. Remove relationship in client
1. Delete ownCloud files in the folder on the desktop
1. Rename folder1 to folder-old
1. Delete folder-old in the GUI
1. Create a new relationship with the sample folder and called the remote folder folder1

The total number of files in the system is 27725, so maybe the client picked up both the files in the new and old folder?

**Comment by guruz** [comment]
> Delete folder-old in the GUI

You mean in the oC webinterface?
In general what you are doing is tricky, deleting configuration files/DB while the client is still running.

**Comment by oparoz** [comment]
>You mean in the oC webinterface?

Yes

>In general what you are doing is tricky, deleting configuration files/DB while the client is still running.

OK, but it shouldn't be too unusual. The client is running a 100% of the time and a user may login to perform other actions in his account from time to time.

But the problem could be in `core`. The bin has a reference to a folder with the same name, but with potentially different content and maybe `core` is not counting files properly?

**Comment by oparoz** [comment]
Just tried again with another cloud which is still on 8.2.3. I did not make any modifications in the web GUI this time.
I just paused a transfer of 6 files. when resuming the client said there were 8 files and the size indicated was double what was being transferred.

**Comment by guruz** [comment]
@ogoffart @ckamm Didn't you work on this?

**Comment by guruz** [comment]
@mcastroSG This might be fixed by https://github.com/owncloud/client/pull/4872 .. please check on Monday..

**Comment by ckamm** [comment]
Yes, that's very likely. After a pause the sync is restarted. And if the progress info isn't reset at that time, you would get bad file counts.

**Comment by mcastroSG** [comment]
@guruz @ckamm this seems to work on a proper way

**Steps executed**

1.- On a clear Shared sync folder include a folder (folder1) that contains one hundred files
2.- Wait till sync ends
3.- Pause Sync
4.- Include a new folder (folder2) at Shared sync folder that contains one hundred files
5.- While Sync is working pause it
6.- Resume Sync

**Results**
Any time I resume sync process the progress bar is restarted and takes not pending files as total. I.e:

 | Total files shown | Uploaded files   | Pending 
|:----:|:------------- |:-------------------|:-------------|
First Resume | 100 | 15 | 85 
Second Resume | 85 | 30 | 55 
Third Resume | 55 | 20 | 35

**Comment by ckamm** [comment]
@mcastroSG Thanks for testing!

**Comment by jnweiger** [comment]
|| Linux Package Installation Report |
|-|-|
|date| Tue Nov 23 13:00:37 CET 2021
|repourl| https://download.owncloud.com/desktop/ownCloud/testing/2.9.2-rc5.6113/linux/
|package| owncloud-client

<details><summary>Test details (click to view)</summary>

|Platform|Test|Result|
|-|-|-|
|centos:7|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:21:45
|centos:8|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|rockylinux/rockylinux:8|01_cmd_vers.sh|	----------- NO OUTPUT ------------
|debian:9|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|debian:10|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|debian:11|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|fedora:31|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|fedora:32|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|fedora:33|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|fedora:34|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|fedora:35|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|ubuntu:18.04|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|ubuntu:20.04|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|ubuntu:20.10|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|ubuntu:21.04|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|ubuntu:21.10|01_cmd_vers.sh|	----------- NO OUTPUT ------------
|opensuse/leap:15.1|01_cmd_vers.sh|	----------- NO OUTPUT ------------
|opensuse/leap:15.2|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|opensuse/leap:15.3|01_cmd_vers.sh|	2.9.2rc5 (build 6113) Nov 22 2021 15:03:38
|centos:7|02_integration.sh|	(2.3.3-1.el7): nemo (2.9.2\~rc5-6113): nautilus
|centos:8|02_integration.sh|	(2.9.2\~rc5-6113): nautilus
|rockylinux/rockylinux:8|02_integration.sh|	----------- NO OUTPUT ------------
|debian:9|02_integration.sh|	(2.9.2\~rc5+oc-6113): dolphin nemo nautilus caja
|debian:10|02_integration.sh|	(2.9.2\~rc5+oc-6113): dolphin nemo nautilus caja
|debian:11|02_integration.sh|	(2.9.2\~rc5+oc-6113): dolphin nemo nautilus caja
|fedora:31|02_integration.sh|	(2.9.2-0.rc5.6113): dolphin nemo nautilus
|fedora:32|02_integration.sh|	(2.9.2-0.rc5.6113): dolphin nemo nautilus
|fedora:33|02_integration.sh|	(2.9.2-0.rc5.6113): dolphin nemo nautilus
|fedora:34|02_integration.sh|	(2.9.2-0.rc5.6113): dolphin nemo nautilus
|fedora:35|02_integration.sh|	(2.9.2-0.rc5.6113): dolphin nemo nautilus
|ubuntu:18.04|02_integration.sh|	(2.9.2\~rc5+oc-6113): dolphin nemo nautilus caja
|ubuntu:20.04|02_integration.sh|	(2.9.2\~rc5+oc-6113): dolphin nemo nautilus caja
|ubuntu:20.10|02_integration.sh|	(2.9.2\~rc5+oc-6113): dolphin nemo nautilus caja
|ubuntu:21.04|02_integration.sh|	(2.9.2\~rc5+oc-6113): dolphin nemo nautilus caja
|ubuntu:21.10|02_integration.sh|	dpkg-query: no packages found matching \*-client-\*
|opensuse/leap:15.1|02_integration.sh|	----------- NO OUTPUT ------------
|opensuse/leap:15.2|02_integration.sh|	(2.9.2\~rc5-6113): dolphin nemo nautilus
|opensuse/leap:15.3|02_integration.sh|	(2.9.2\~rc5-6113): dolphin nemo nautilus
|centos:7|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|centos:7|05_xvfb_run.sh|	0x200005 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0 0x20000c "ownCloud Connection Wizard": ("owncloud" "ownCloud") 720x630+30+0 +30+0
|centos:7|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|centos:8|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|centos:8|05_xvfb_run.sh|	0x200005 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0 0x20000c "ownCloud Connection Wizard": ("owncloud" "ownCloud") 720x630+30+0 +30+0
|centos:8|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|debian:9|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|debian:9|05_xvfb_run.sh|	0x200003 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0
|debian:9|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|debian:10|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|debian:10|05_xvfb_run.sh|	0x200003 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0
|debian:10|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|debian:11|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|debian:11|05_xvfb_run.sh|	0x200003 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0
|debian:11|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|fedora:31|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|fedora:31|05_xvfb_run.sh|	0x200005 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0 0x20000c "ownCloud Connection Wizard": ("owncloud" "ownCloud") 720x630+30+0 +30+0
|fedora:31|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|fedora:32|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|fedora:32|05_xvfb_run.sh|	0x200005 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0 0x20000c "ownCloud Connection Wizard": ("owncloud" "ownCloud") 720x630+30+0 +30+0
|fedora:32|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|fedora:33|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|fedora:33|05_xvfb_run.sh|	0x200005 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0 0x20000c "ownCloud Connection Wizard": ("owncloud" "ownCloud") 720x630+30+0 +30+0
|fedora:33|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|fedora:34|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|fedora:34|05_xvfb_run.sh|	0x200005 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0 0x20000c "ownCloud Connection Wizard": ("owncloud" "ownCloud") 720x630+30+0 +30+0
|fedora:34|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|fedora:35|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 24: xvfb-run: command not found
|fedora:35|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|fedora:35|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 35: xvfb-run: command not found
|fedora:35|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 38: xwininfo: command not found
|fedora:35|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 38: xwininfo: command not found
|fedora:35|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 38: xwininfo: command not found
|fedora:35|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 38: xwininfo: command not found
|fedora:35|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 38: xwininfo: command not found
|fedora:35|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 56: convert: command not found
|fedora:35|05_xvfb_run.sh|	
|fedora:35|05_xvfb_run.sh|	settings window did not open.
|ubuntu:18.04|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|ubuntu:18.04|05_xvfb_run.sh|	0x200003 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0
|ubuntu:18.04|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|ubuntu:20.04|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|ubuntu:20.04|05_xvfb_run.sh|	0x200003 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0
|ubuntu:20.04|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|ubuntu:20.10|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|ubuntu:20.10|05_xvfb_run.sh|	0x200003 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0
|ubuntu:20.10|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|ubuntu:21.04|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|ubuntu:21.04|05_xvfb_run.sh|	0x200003 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0
|ubuntu:21.04|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|opensuse/leap:15.2|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|opensuse/leap:15.2|05_xvfb_run.sh|	0x200005 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0 0x200009 "ownCloud Connection Wizard": ("owncloud" "ownCloud") 720x630+30+0 +30+0
|opensuse/leap:15.2|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|opensuse/leap:15.3|05_xvfb_run.sh|	/mnt/05-xvfb-run.sh: line 26: /root/.config/\*/ownCloud.cfg: No such file or directory
|opensuse/leap:15.3|05_xvfb_run.sh|	0x200005 "ownCloud": ("owncloud" "ownCloud") 800x700+0+0 +0+0 0x200009 "ownCloud Connection Wizard": ("owncloud" "ownCloud") 720x630+30+0 +30+0
|opensuse/leap:15.3|05_xvfb_run.sh|	WARN: client quit button click did not end the X-Session
|centos:7|08_appimage.sh|	/usr/bin/client.appimage: line 1: syntax error near unexpected token `newline'
|centos:8|08_appimage.sh|	/usr/bin/client.appimage: line 1: syntax error near unexpected token `newline'
|rockylinux/rockylinux:8|08_appimage.sh|	/usr/bin/client.appimage: line 1: syntax error near unexpected token `newline'
|debian:9|08_appimage.sh|	/usr/bin/client.appimage: 2: /usr/bin/client.appimage: Syntax error: newline unexpected
|debian:10|08_appimage.sh|	----------- NO OUTPUT ------------
|debian:11|08_appimage.sh|	----------- NO OUTPUT ------------
|fedora:31|08_appimage.sh|	/usr/bin/client.appimage: line 1: syntax error near unexpected token `newline'
|fedora:32|08_appimage.sh|	/usr/bin/client.appimage: line 1: syntax error near unexpected token `newline'
|fedora:33|08_appimage.sh|	/usr/bin/client.appimage: line 1: syntax error near unexpected token `newline'
|fedora:34|08_appimage.sh|	/usr/bin/client.appimage: line 1: syntax error near unexpected token `newline'
|fedora:35|08_appimage.sh|	WARNING: xvfb-run missing, no version check.
|fedora:35|08_appimage.sh|	/usr/bin/client.appimage: HTML document, ASCII text
|ubuntu:18.04|08_appimage.sh|	/usr/bin/client.appimage: 2: /usr/bin/client.appimage: Syntax error: newline unexpected
|ubuntu:20.04|08_appimage.sh|	/usr/bin/client.appimage: 2: Syntax error: newline unexpected
|ubuntu:20.10|08_appimage.sh|	/usr/bin/client.appimage: 2: Syntax error: newline unexpected
|ubuntu:21.04|08_appimage.sh|	/usr/bin/client.appimage: 2: Syntax error: newline unexpected
|ubuntu:21.10|08_appimage.sh|	/usr/bin/client.appimage: 2: Syntax error: newline unexpected
|opensuse/leap:15.1|08_appimage.sh|	/usr/bin/client.appimage: line 1: syntax error near unexpected token `newline'
|opensuse/leap:15.2|08_appimage.sh|	/usr/bin/client.appimage: line 1: syntax error near unexpected token `newline'
|opensuse/leap:15.3|08_appimage.sh|	/usr/bin/client.appimage: line 1: syntax error near unexpected token `newline'
|centos:7|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|centos:8|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|debian:9|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-11-22
|debian:10|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-11-22
|debian:11|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-11-22
|fedora:31|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|fedora:32|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|fedora:33|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|fedora:34|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|fedora:35|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|ubuntu:18.04|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-11-22
|ubuntu:20.04|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-11-22
|ubuntu:20.10|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-11-22
|ubuntu:21.04|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-11-22
|opensuse/leap:15.2|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|opensuse/leap:15.3|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|centos:7|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|centos:8|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|debian:9|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|debian:10|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|debian:11|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:31|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:32|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:33|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:34|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:35|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:18.04|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:20.04|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:20.10|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:21.04|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|opensuse/leap:15.2|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|opensuse/leap:15.3|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|centos:7|20_qttrans_de.sh|	OK 14
|centos:8|20_qttrans_de.sh|	OK 14
|debian:9|20_qttrans_de.sh|	OK 13
|debian:10|20_qttrans_de.sh|	OK 13
|debian:11|20_qttrans_de.sh|	OK 13
|fedora:31|20_qttrans_de.sh|	OK 14
|fedora:32|20_qttrans_de.sh|	OK 14
|fedora:33|20_qttrans_de.sh|	OK 14
|fedora:34|20_qttrans_de.sh|	OK 14
|fedora:35|20_qttrans_de.sh|	OK 14
|ubuntu:18.04|20_qttrans_de.sh|	OK 13
|ubuntu:20.04|20_qttrans_de.sh|	OK 13
|ubuntu:20.10|20_qttrans_de.sh|	OK 13
|ubuntu:21.04|20_qttrans_de.sh|	OK 13
|opensuse/leap:15.2|20_qttrans_de.sh|	OK 14
|opensuse/leap:15.3|20_qttrans_de.sh|	OK 14
|centos:7|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.0.2k-fips  26 Jan 2017
|centos:8|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1k  FIPS 25 Mar 2021
|debian:9|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.0l  10 Sep 2019
|debian:10|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1d  10 Sep 2019
|debian:11|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1k  25 Mar 2021
|fedora:31|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1g FIPS  21 Apr 2020
|fedora:32|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1k  FIPS 25 Mar 2021
|fedora:33|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1l  FIPS 24 Aug 2021
|fedora:34|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1l  FIPS 24 Aug 2021
|fedora:35|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1l  FIPS 24 Aug 2021
|ubuntu:18.04|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1  11 Sep 2018
|ubuntu:20.04|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1f  31 Mar 2020
|ubuntu:20.10|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1f  31 Mar 2020
|ubuntu:21.04|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1j  16 Feb 2021
|opensuse/leap:15.2|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1d  10 Sep 2019
|opensuse/leap:15.3|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1d  10 Sep 2019
|centos:7|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|centos:8|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|debian:9|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|debian:10|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|debian:11|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|fedora:31|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|fedora:32|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|fedora:33|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|fedora:34|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|fedora:35|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|ubuntu:18.04|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|ubuntu:20.04|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|ubuntu:20.10|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|ubuntu:21.04|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|opensuse/leap:15.2|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|opensuse/leap:15.3|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst

</details>

Generated via client/linux-docker-install/run_tests.sh

----
