### ISSUE TITLE
[Linux] Tray icon silently fails with fluxbox, works perfectly with KDE/Plasma/xfce4

### ISSUE THREAD

**Issue by yeupou** [owncloud/client#4807]
Hi,

With fluxbox, owncloud just do not do anything. In logfile, there are plenty of:

05-07 11:13:34:697 3177 unknown: QSystemTrayIcon::setVisible: No Icon set
05-07 11:13:34:698 3177 unknown: QSystemTrayIcon::setVisible: No Icon set

It would show as if it was just a problem of system tray but no update is done at all. BTW, there is a system tray within fluxbox (wicd or pidgin use it with no problem).

Starting owncloud never show the interface

The same version of the client with the exact same config works perfectly within KDE/Plasma (hence no configuration issue, no server issue).

Package info:

Version: 2.1.1+dfsg-1

-- System Information:
Distributor ID:	Devuan
Description:	Devuan GNU/Linux 2.0 (ascii)
Release:	2.0
Codename:	ascii
Architecture: x86_64

Kernel: Linux 4.5.0-1-amd64 (SMP w/6 CPU cores)
Locale: LANG=fr_FR.UTF-8, LC_CTYPE=fr_FR.UTF-8 (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: sysvinit (via /sbin/init)

Versions of packages owncloud-client depends on:
ii  libc6                 2.22-7
ii  libgcc1               1:5.3.1-14
ii  libowncloudsync0      2.1.1+dfsg-1
ii  libqt5core5a          5.5.1+dfsg-16+b1
ii  libqt5dbus5           5.5.1+dfsg-16+b1
ii  libqt5gui5            5.5.1+dfsg-16+b1
ii  libqt5keychain0       0.5.0-1
ii  libqt5network5        5.5.1+dfsg-16+b1
ii  libqt5sql5-sqlite     5.5.1+dfsg-16+b1
ii  libqt5webkit5         5.5.1+dfsg-2+b1
ii  libqt5widgets5        5.5.1+dfsg-16+b1
ii  libqt5xml5            5.5.1+dfsg-16+b1
ii  libssl1.0.2           1.0.2g-2
ii  libstdc++6            5.3.1-14
ii  owncloud-client-l10n  2.1.1+dfsg-1

**Comment by yeupou** [comment]
It also work with xfce4.

**Comment by guruz** [comment]
Have you tried to check on the internet or on https://bugreports.qt.io/ if you can find this kind of bug?

**Comment by yeupou** [comment]
Hello, 

So it is a nknown issue and there is workaround = which are, exactly?

**Comment by yeupou** [comment]
"Have you tried to check on the internet or on https://bugreports.qt.io/ if you can find this kind of bug"

No, I dont any problem related to Qt on my system that I am aware off. Only owncloud exhibits troubles.

**Comment by guruz** [comment]
@yeupou ownCloud is using Qt for the tray integration, that's why your log says ```QSystemTrayIcon```

**Comment by yeupou** [comment]
Still, as said,  "I dont any problem related to Qt on my system that I am aware of. Only owncloud exhibits troubles", maybe there is "No Icon set" and uQSystemTrayIcon sending an error. 

Problem is it is not only missing an icon. It is not doing anything. 

Funny enough, I can have in the fluxbox tray any KDE/Qt apps (kmix, etc) or GTK+ (Pidgin).

Fact is I can leave without the tray for owncloud. Whatever. But I'd still need the sync, which is really what the client is about.

Can you make it so the client can be used on any X system, tray or not? If not, why not?

**Comment by yeupou** [comment]
adding NO WORKAROUND to the title until a real workaround is provided. 
(please understand that: using KDE is not a workaround for the report  "Tray icon silently fails with fluxbox, works perfectly with KDE/Plasma/xfce4"

**Comment by yeupou** [comment]
After a system upgrade (including owncloudclient upgrade), the tray icon is back and everything is working.

I wont spend time to understand exactly what went wrong and I'll surely remember how was this bug report handled (tagging  "Known Issue / Workaround" while not providing any actual workaround or pointer to a know issue). Not so great.

**Comment by guruz** [comment]
Great to hear it works with a system upgrade!
In general: I think contacting your Linux distribution is also a good way for the bugs that are related to your desktop integration.
