### ISSUE TITLE
Don't sync when device is on cellular/mobile connection

### ISSUE THREAD

**Issue by dryo** [owncloud/client#4808]
Tablets sometimes have mobile broadband onboard. The client should not sync over such connections or even better let the user define that.

IMO it would be best if the client asked upon detecting an unknown connection whether to automatically sync, not sync at all or ask every time for this network. This should be regardless of connection type (LAN, WiFi, Mobile, …) because some USB broadband devices emulate a LAN connection.

This would also solve #4309 and partially solve #1971

**Comment by danimo** [comment]
How would the client know that?

**Comment by stonerl** [comment]
Maybe, if possible only sync when connected to specific networks. I don't know whether or not this is doable.

On Android, the Podcatcher Antennapod has an option that let's the user specify the WiFi-Networks over which sync is allowed.

But to do such a check the ownCloud-client would have to know with which network it is connected. Is this even possible on OSX/Linux/Windows?

**Comment by jaykay2342** [comment]
On linux most distributions use the Network Manager. You can talk to it via a socket to know which connection is in use. Alternatively it would be nice if there is a way to do it the other way around. A interface (socket/cmd) i can talk to the ownCloud client to tell it to pause syncing, that would help to write a small plugin for the network manager to pause syncing when certain connections are in use.

**Comment by mikedolx** [comment]
This feature is for me more than an enhancement. I use a cellular modem in my laptop and due to the client i regulary wipe my data plan. This occurs very often to me. Of course, i regulary pause synching, but when I'm home i resume synching. Afterwards i forget it and my data plan is gone - its only 750MB.

I know at least in Windows 10 it is possible to define any network connection as "clocked" (thats the translation from german, i don't know how it's called on an english windows 10).

I wonder if the client could use this information and automatically pause synching when on a "clocked" network in windows 10.

**Comment by dragotin** [comment]
Utilizing this function https://msdn.microsoft.com/en-us/library/windows/desktop/aa384702(v=vs.85).aspx we could detect at least if we are connected via LAN. With that, we could have a checkbox 

* [ ] Only sync when connected via LAN

however, we probably would like to include WLAN in that too, right? I wonder why the API does not allow that....

**Comment by mikedolx** [comment]
I use my laptop on ethernet when i'm home, so such kind of checkbox would be sufficient for me.

**Comment by pako81** [comment]
@pmaier1 [00006690](https://na25.salesforce.com/5003100000iLnmh)

**Comment by hodyroff** [comment]
@SamuAlfageme Please check for the API to be used on the Windows side for that. What about MAC?

**Comment by phil-davis** [comment]
In Windows10 you can set a network connection as "metered". Windows will use that setting to not download updates... over a "metered" connection. The selection choice is shown in the UI for WiFi and directly-mobile connections, but not for network devices that look like a wired LAN.
For wired-LAN-looking devices you have to make a registry setting, instructions here that have worked for me:
http://www.windowscentral.com/how-set-ethernet-connection-metered-windows-10
In my case, I had and old iPhone3GS that plugged directly into my laptop to give internet to the laptop, but of course that looked like a LAN to Windows10 and it downloaded a heap of stuff automagically, using up my mobile data quota.
It seems this feature was added in Windows8, so for Windows8 and above, it would be possible to check if the connection is marked as "metered". So would not work for Windows7.

**Comment by SamuAlfageme** [comment]
@hodyroff the support reference that @phil-davis links in his comment is a great place to start understanding the options that allow this behavior in Windows:  it's a global OS option that wouldn't add logic to the client.

As for today; the convergence in Microsoft's OS (mobile and desktop) is making them the only folks offering [these kind of options](https://support.microsoft.com/en-nz/instantanswers/633571e5-3591-437d-bf6a-071a243305a7/metered-connections-in-windows-10 ) (Apple is almost always assuming his users on the move are working with iOS, which conveniently offers a comprehensive API for this).

There exist many apps designed to do this globally and establish some kind of while/black-list of apps that can access the network under some conditions. But they all still rely in the user input (selecting those networks/profiles and apps that are targeted). Some examples to see how they implement this behavior, are:

* [Tripmode](https://www.tripmode.ch/)
* [LittleSnitch](https://www.obdev.at/products/littlesnitch/index.html)
* [Hands Off](https://www.oneperiodic.com/products/handsoff/tutorials/basics.html)

**Manually selecting networks that are known to be mobile/tethered is the most effective way to do this**. It would be even possible to give the *illusion* of doing this automatically with some workarounds: e.g. switching between different [OS X profiles](https://support.apple.com/profile-manager) and Firewall settings to limit the traffic of the application when connecting to specific networks, trying the [low level path](http://android.stackexchange.com/a/48408) and detect tethering in the bottom layers of the packages (e.g. checking the manufacturer part of the MAC address, etc.). But all these options add complexity to the client while not being 100% reliable. 

At the end of the day there must be **always some kind of user input** about which networks/SSIDs are cellular connections (or need to be seen as such).

**Comment by michaelstingl** [comment]
Using **Tripmode** would also be my recommended workaround. Works on Win and Mac and is only US$7.99.

**Comment by pmaier1** [comment]
For desktop we should suggest using a tool like @SamuAlfageme and @michaelstingl proposed since every other possibility will either require user input (which amounts to roughly the same as configuring such a tool) or won't be 100% reliable. Can we close here?

**Comment by sagamusix** [comment]
None of the suggested alternatives are free software or at least free (plus they require extra trust for doing questionable modifiactions to your operating system), and older Windows versions which are still supported do not have metered connections (but are aware of mobile broadband connections).

**Comment by hodyroff** [comment]
For me it sounds like the right approach is to do this outside of the ownCloud Desktop Client then. When users want to do this, its likely that oC is not the only application they should worry about. If there is currently no free tool, encouraging to develop one seems the best way, rather then try to put this into the ownCloud Client. We have plenty of corner cases to worry about first. We also have the "pause" as a workaround. If strong, new points come up, please don't hesitate to comment further.

**Comment by sagamusix** [comment]
> When users want to do this, its likely that oC is not the only application they should worry about

Not really - ownCloud is pretty much the only application that can single-handedly create hundreds of MB of traffic without asking the user. This just happened to me last week, I accidentally used up 70% of my monthly mobile data quota in a few minutes because I didn't realize that ownCloud was running. In that case, "pause" is not a work-around, because at that point it's already too late.

**Comment by hodyroff** [comment]
I am getting that point - still can think of quite some other applications.
But which magic shall allow the Desktop Client to know that and react correctly?

**Comment by michaelstingl** [comment]
@sagamusix Shouldn't it be possible with firewall configuration? Blocking the oC desktop sync client  when connected within the IP range from the mobile provider? As far as I know, this is what _Little Snitch_ does with a fancy UI.

**Comment by sagamusix** [comment]
@hodyroff On a very basic level, this could be implemented in the way @dragotin suggested, at least on Windows. There are probably similar APIs on other platforms.

@michaelstingl Interesting idea, I guess on a more simple level I could block ownCloud from accessing public networks, which is not quite the same but a good approximation (and possibly the only way in Windows 7: https://serverfault.com/questions/229545/how-to-configure-different-firewall-rules-on-2-different-network-cards-in-window). That way, I do not have to rely on specific IP ranges which could change without further notice.

**Comment by guruz** [comment]
I'll keep this open as a request / known issue after all.

**Comment by guruz** [comment]
https://docs.microsoft.com/en-us/windows/communitytoolkit/helpers/networkhelper IsInternetOnMeteredConnection
https://stackoverflow.com/questions/16122432/how-can-i-tell-if-the-connection-is-metered
https://stackoverflow.com/questions/32845625/windows-10-uwp-detect-if-the-current-internet-connection-is-wifi-or-cellular
https://stackoverflow.com/questions/49949860/winform-find-if-network-connection-is-metered-network-cost

**Comment by mihovilkolaric** [comment]
I would really appreciate the feature also for the Linux client - most desktops-linuxes are using NetworkManager which provides the information whethter a connection is metered using DBUS:
https://developer.gnome.org/NetworkManager/unstable/gdbus-org.freedesktop.NetworkManager.html#gdbus-property-org-freedesktop-NetworkManager.Metered
resp. there seems to be an API for Qt: https://api.kde.org/frameworks/networkmanager-qt/html/classNetworkManager_1_1Device.html

**Comment by paultjevdh** [comment]
Hi,
I agree this feature is sorely missed. Yesterday owncloud ate 1 GB of my dataplan while commuting. I don't want this to happen every day.
The competition (onedrive) immediately paused when I connected to my phone hotspot. I was disappointed that owncloud doesn't even offer the feature.

Paul

**Comment by michaelstingl** [comment]
> owncloud ate 1 GB of my dataplan while commuting

Do you use VFS feature? Then it shouldn't eat so much data?

**Comment by paultjevdh** [comment]
Hi,
Since the purpose of owncloud is to have the same files available on each client device, the files must all be available on the server. I therefore assume the VFS feature will not limit uploads. 
It must have been an upload that caused the data usage since there is only 1 device that I sync with owncloud. Therefore I doubt that VFS solves this specific problem.
Instead I let owncloud ignore the specific file (a large 250MB database that has copies elsewhere anyway).
I prefer a global solution over a file-specific solution (which may not be valid in all cases).

Best regards,
Paul

**Comment by michaelstingl** [comment]
Also good feedback in the community forums:
https://central.owncloud.org/t/pause-sync-on-metered-connections/32959/3

**Comment by erikjv** [comment]
Implementation wise it'd probably be a good idea to look at Qt6's QNetworkInformation and copy some of it's interface. That'd make migration to Qt6 easier.

**Comment by doozerjg** [comment]
I would like to push that up. I think it is one of those features where many users might not be aware that this is possible and just deal with the consequences.

Since windows has this specific setting for metered connections,.it would be really great if the owncloud client could make use of that (could be optional setting, although I would suggest that it makes sense to have that as default).

I'm aware of the current limitations but with LTE and 5G, syncing is so fast that if you do not immediately think about pausing sync while on a metered connection, it will already have used up a lot of date (for me just now: 2gb, because someone uploaded new files in a shared folder I had synced).

Thanks!

**Comment by GrendelWWU** [comment]
Uh... a seven year old discussion. I think, the owncloud developers should take the feet from brakes! What's the problem? Some people really need this feature, cause mobile charges are still really expensive in Germany!

**Comment by michaelstingl** [comment]
> Implementation wise it'd probably be a good idea to look at Qt6's QNetworkInformation and copy some of it's interface. That'd make migration to Qt6 easier.

New with [Qt 6.3:](https://doc.qt.io/qt-6/whatsnew63.html#qt-network-module)
- [QNetworkInformation](https://doc.qt.io/qt-6/qnetworkinformation.html) also learned [`isMetered`](https://doc.qt.io/qt-6/qnetworkinformation.html#isMetered-prop). A property that returns whether the network is metered.

**Comment by TheOneRing** [comment]
> > Implementation wise it'd probably be a good idea to look at Qt6's QNetworkInformation and copy some of it's interface. That'd make migration to Qt6 easier.
> 
> New with [Qt 6.3:](https://doc.qt.io/qt-6/whatsnew63.html#qt-network-module)
> 
>     * [QNetworkInformation](https://doc.qt.io/qt-6/qnetworkinformation.html) also learned [`isMetered`](https://doc.qt.io/qt-6/qnetworkinformation.html#isMetered-prop). A property that returns whether the network is metered.

Aslo https://doc.qt.io/qt-6/qnetworkinformation.html#transportMedium-prop

**Comment by TheOneRing** [comment]
Add new setting to the netwroking section to enable/disable upload when connection is metered.



![Image](https://github.com/owncloud/client/assets/200626/8c60d503-db6f-47f4-b829-18cea1b45611)

**Comment by erikjv** [comment]
Note: when a user forces a sync, pop up a dialog to confirm. (Forced syncs have a higher priority in the scheduler.)

**Comment by erikjv** [comment]
Test steps are in the PR.

**Comment by michaelstingl** [comment]
In macOS Sonoma 14.1, users have the option to set a network connection to "Low data mode". Could this be respected?

![CleanShot 2023-11-09 at 13 06 57@2x](https://github.com/owncloud/client/assets/214010/e55584e7-3403-426b-88a5-72e451cc30e5)

**Comment by erikjv** [comment]
> In macOS Sonoma 14.1, users have the option to set a network connection to "Low data mode". Could this be respected?

@michaelstingl  I cannot find any documentation on how to query/listen for this. I could post a question on the dev forums, but we should probably open a separate ticket to track that.

**Comment by michaelstingl** [comment]
> @michaelstingl I cannot find any documentation on how to query/listen for this. I could post a question on the dev forums, but we should probably open a separate ticket to track that.

Works for me.

**Comment by michaelstingl** [comment]
Please update the docs issue with the supported platforms:
- https://github.com/owncloud/docs-client-desktop/issues/535
