### ISSUE TITLE
[2.1.1] Owncloud.exe windows crash

### ISSUE THREAD

**Issue by nerdsite** [owncloud/client#4809]
Owncloud has run fine for months. There was a new updates to the windows desktop client so I installed the latest. Now everything fails to run (crashes at startup):

Event logs:
Faulting application name: owncloud.exe, version: 2.1.1.5837, time stamp: 0x00000000
Faulting module name: owncloud.exe, version: 2.1.1.5837, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x000f89ee
Faulting process id: 0x1964
Faulting application start time: 0x01d1a8e0ec475134
Faulting application path: C:\Program Files (x86)\ownCloud\owncloud.exe
Faulting module path: C:\Program Files (x86)\ownCloud\owncloud.exe
Report Id: 2b0338f3-14d4-11e6-a6ef-8c89a513eff5

I've uninstalled it several times, reinstalled, rebooted, uninstalled & rebooted, cleared all registry keys, removed owncloud directory, reinstalled older version (which now no longer run). Not sure what to. The ONLY thing that changed was installing a new version of the client software. I just got done w/ a sync and wanted to try the new version.

Any suggestions on this one?

owncloud server 8.2.2, apache, mysql

Also: I get no output from --logwindow or --logfile options. Just the Report.wer report.

**Comment by guruz** [comment]
@nerdsite So is this even before it asks you to send that crash report to us?

FYI @jturcotte

**Comment by guruz** [comment]
@nerdsite Would you try the 2.2beta2? https://owncloud.org/install/#testing-development

**Comment by nerdsite** [comment]
Fails also. Does the WERxxx file give you any glimpse into the error?

**Comment by nerdsite** [comment]
BTW, this one asked to send a crash report to MS. Is that what you meant by "before it asks you to send that crash report to us"? I was hoping it would create a log file but it also did not.

**Comment by guruz** [comment]
>  I get no output from --logwindow or --logfile options.

There is no output for this on Windows unfortunately. Can you still check if the logfile was created and what it contains?

**Comment by nerdsite** [comment]
No logfile created. Not sure why.

**Comment by nerdsite** [comment]
I'm pretty much dead in the water. No preview versions work either. No logs created just a MS crash event. I renamed the owncloud config director in case something was screwy there; however, it never gets to the point of creating it. owncloud.exe --help doesn't even display a help; it doesn't get that far. What can I try?

**Comment by guruz** [comment]
Did you try running the uninstaller and reinstalling a nightly version?
http://download.owncloud.com/desktop/daily/ownCloud-2.2.1.6109-nightly20160524-setup.exe

**Comment by nerdsite** [comment]
No luck. Any version I've tried does the same thing now. Something got introduced that makes it fail; It was introduced on the last "official" update. It just doesn't get too far at startup. It does manage to try to send a crash report to MS.

**Comment by danimo** [comment]
@nerdsite Why version of Windows is this? I take it's 64 bits?

**Comment by dragotin** [comment]
You could try to disable the overlay icons when installing and see if that works.

**Comment by danimo** [comment]
@dragotin effectively our custom crash reporter should kick in before that.

**Comment by nerdsite** [comment]
It's 64 bit

**Comment by danimo** [comment]
@nerdsite yes, but which Windows version?

**Comment by nerdsite** [comment]
Win7 Professional 64

**Comment by guruz** [comment]
Is this still a problem with 2.2.1 which came out some days ago?

**Comment by nerdsite** [comment]
Still fails. I don't know what else to try.

**Comment by nerdsite** [comment]
Faulting application name: owncloud.exe, version: 2.2.1.6146, time stamp: 0x00000000
Faulting module name: owncloud.exe, version: 2.2.1.6146, time stamp: 0x00000000
Exception code: 0xc0000005
Fault offset: 0x0010bf8e
Faulting process id: 0x1028
Faulting application start time: 0x01d1c724faff0626
Faulting application path: C:\Program Files (x86)\ownCloud\owncloud.exe
Faulting module path: C:\Program Files (x86)\ownCloud\owncloud.exe
Report Id: 38c35ec9-3318-11e6-866d-8c89a513eff5
