### ISSUE TITLE
Some tweaks to make corporate roaming users Happy

### ISSUE THREAD

**Issue by rrignier** [owncloud/client#481]
Hi, from yopla on freenode irc.
As requested, I file a bug to things that need some thinking.

Goal is to store config file and folders in Windows %appdata% instead of %localdata% So that roaming users (multiple users can login on mutiiple different machines) dont have to configure their sync folder each time, and sync some folder to their private shared directory.

Tricky thing is to make some check to avoid conflicts 
- same user could have open multiple sessions on different computers which could be bad thing if they point on same shared private folder. (We try to prevent this but it is still possible)
- make sure a bad configuration (some folder missing or old ones) doesn't delete files server side.

Thank you for your help

**Comment by dragotin** [comment]
Lets get more specific in #684
