### ISSUE TITLE
Bad file name renaming

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4811]
### Expected behaviour

In case of rename an already synced file at a local folder to a bad file name an error is generated with a little briefing about it.
### Actual behaviour

A general error is returned and overlay icon is not updated till several retries are done to a red X.
### Steps to reproduce
1. Rename a bad file name at Share sync folder (i.e :smile:.jpg )
2. Wait till sync starts
### Server configuration

Server OS: Ubuntu
Server Version: 9.1.0 Alpha
### Client configuration

Client OS: OSX El capitán 10.11.4
Client Version: Version 2.2.0-nightly20160504 (build 3331)

Client OS: Ubuntu 14.04 LTE
Client Version: Version 2.2.0nightly201654 (build 1587)

Client OS: Windows 81
Client Version: Version 2.2.0-nightly20160506 (build 6057)

**Comment by dragotin** [comment]
What is the bad filename? It is not `asdf` I hope ;-)

**Comment by mcastroSG** [comment]
':smile:.txt' for example, I´ve been checking with some mojis included at filename to generate some errors 🙈

**Comment by jturcotte** [comment]
The problem is that ideally we should rely on the server to give us errors about invalid filenames. But maybe we aren't encoding the filenames properly (or at all)?

/cc @ogoffart

**Comment by rperezb** [comment]
Ideally, errors in invalid filenames management rely on the server so that "special cases" such  as some External storages are handled properly

**Comment by guruz** [comment]
Should be better with 2.3\4
