### ISSUE TITLE
[IgnoreList] After include a pattern to ignore list we are not able to sync some data.

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4812]
### Expected behaviour
In case we include a pattern to ignore list that affects to existing files at Shared sync folder, any file included at any path should be synced.

### Actual behaviour
In case we include a pattern to ignore list that affects to existing files, once we sync again files at the same path that we are ignoring are not synced.

### Steps to reproduce
1. Create a new "folder1".
2. Create a new called "ttt.ttt" inside "folder1"
3. Wait till desktop client syncs
4. Add a pattern to ignore list that match i.e "*ttt*"
5. Wail till desktop client syncs
6. Delete "ttt.ttt" file from "folder1". (At server side "ttt.ttt" file will remain) 
7. Delete "folder1" from Shared sync folder  (At server side "folder1" will remain)
8. Create at server side a new text file inside "folder1" and check that after sync there is no text file at Shared sync folder, just at server side.

### Server configuration

Server OS: Ubuntu
Server Version: 9.1.0 Alpha

### Client configuration

Client OS: OS X El capitán 10.11.4
Client Version: Version 2.2.0-nightly20160504 (build 3331)

**Comment by ckamm** [comment]
@mcastroSG I don't understand this problem yet. I do follow up until step 6 and the behavior still looks good to me.

Can you give me more details on that shared sync folder and who's syncing? When you delete "folder1", why does it remain server-side? If it's not a share itself, it should be removed! Is that the bug?

**Comment by mcastroSG** [comment]
@ckamm  I´ve been testing this again and the main argument to raise has disappear. In case I include a new file at server side to the folder that I´ve previously deleted at client side, desktop client create the folder and includes the file I´ve created at server side.

Just one more thing about this issue

![screen shot 2016-05-20 at 13 16 34](https://cloud.githubusercontent.com/assets/18436398/15426180/1fc8cf8c-1e8d-11e6-9e38-8a89500f50b7.png)

As could be seen at the snapshot in case i delete "untitled folder" from client side, still remains at selective sync dialog. Also remains at server side. Is this right? .. or may be selective sync dialog should represent folders that are sync at local shared folder instead ?

**Comment by ckamm** [comment]
@mcastroSG What exactly are you doing where deleting a folder on the client does not remove it from the server?

In my tests, the folder that's removed locally is also removed from the server and the selective sync dialog folders are updated. The selective sync dialog must include server-only folders, because deselected folders won't appear locally.

**Comment by mcastroSG** [comment]
Retested again and its working.  In case I add a new file from server side to folder1 desktop client recreates folder1 on my computer and syncs the new file.

Client Version: Version 2.2.2 (build 3472)
Client OS : OSX El capitán 10.11.5

Server Version: 9.1.0 beta 2
Server OS: Ubuntu 14.04
