### ISSUE TITLE
Conflict Files: Consider to add a Notification about them

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4813]
### Expected behaviour

If there is a conflict file, the user should be informed about. That happens through a toast message and an entry in the _Not synced_ list.  #3222

However, with the next sync run, the _Not synced_ list is wiped, so that the conflict entries are lost. The next sync can happen quite soon after the conflict happened.

Maybe the conflicts should become **notifications** which only go away after the user clicked on "Close", similar to the notifications that we get from the server if a remote share happens.

Alternatively we could add code which lets the conflict entry not go away for a certain time span. 
### Actual behaviour

Currently, if a conflict happens, a tray notification pops up and in the _Not synced_ list appears an entry. The problem is that this one can disappear quickly.
### Steps to reproduce
1. create a conflict file
2. check that the conflict entry is in the _not synced_ list 
3. See how it vanishes from there with the next sync.

**Comment by guruz** [comment]
Also check https://github.com/owncloud/client/issues/4079

**Comment by guruz** [comment]
Isn't this done already?
https://github.com/owncloud/client/commit/52a52341227bb9dc31af74bae0645d96b8ece469

@mcastroSG ?

**Comment by guruz** [comment]
Actually @dragotin wants more persistent notifications: https://github.com/owncloud/client/issues/4697

**Comment by mcastroSG** [comment]
@guruz Conflict file alerts  have not been included as notifications in the same way than Announcements or remote federated sharing files but it will be 😄

**Comment by ckamm** [comment]
We now have a persistent list of conflicts in the issues tab. I think that's mostly equivalent to showing them in the notifications view - @dragotin agreed?

**Comment by guruz** [comment]
@ckamm Maybe you mean a different thing by 'notifications'? We mean https://support.apple.com/en-us/HT204079

**Comment by ckamm** [comment]
@guruz Oh. I thought server notifications that are displayed in the "Server activity" tab were meant. We don't have these fancy notifications anywhere yet, do we?

**Comment by guruz** [comment]
OK..
then this is partly solved by your issues tab and partly handled by https://github.com/owncloud/client/issues/4697

Closing
