### ISSUE TITLE
Clearify copyright for  src/3rdparty/qtokenizer

### ISSUE THREAD

**Issue by hefee** [owncloud/client#4817]
I start to review the 2.2~beta tarball for debian and stumbled around that  src/3rdparty/qtokenizer has a strange copyright. It tells, that it is part of QNetwork, but I can't find this file at qt side. On the otherside it tells me that the copyright holder is @danimo. This do not really match together. Can you point me the exact upstream source?

**Comment by danimo** [comment]
https://github.com/danimo/qtplayground/tree/master/qtokenizer

**Comment by danimo** [comment]
It was supposed to go into Qt, but I hadn't had time to pursue this any further.

**Comment by hefee** [comment]
@danimo ok i fould also your github but thoufght this was a copy of any qt internal code.

But this clearifies it, that is going in the other direction...
