### ISSUE TITLE
[Windows][Checksum][Overlay] In case of upload skipped due to cksum unaltered, overlay icon is not updated and remains as "blue sync"

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4819]
### Expected behaviour

In case we have an .eml file and by any reason its date is updated overlay icon is not updated to "green check" after sync

### Actual behaviour

After a date modification at an eml file Desktop client skips upload due to cksum has not been altered but does not update overlay icon to "green check" and "blue sync" remains after sync.

### Steps to reproduce
1.- Connect desktop client to a server with checksum capabilities enabled
2.- Add an eml file to Share sync folder
3.- Wait till sync ends
3.- `copy /b file.eml +,,` at cmd
4.- Wait till next sync ends

### Server configuration

Server OS: Ubuntu 
Server Version: 9.1.0 Alpha modified to enable checksum capabilities

### Client configuration

Client OS: W81. W10
Client Version:Version 2.2.0rc1 (build 6069)

**Comment by ckamm** [comment]
This should not not depend on a server supporting checksums - the 'skip upload' decision for eml files is done purely based on the local checksums.

I can't reproduce this on Linux/nautilus. With that setup, the eml file becomes blue for the duration of the sync and turns green again afterwards.

**Comment by ckamm** [comment]
@mcastroSG I've tried this with ownCloud-2.2.0.6073-nightly20160512 on Windows 7 but can't reproduce it! Could you re-check that it's reproducible for you?

**Comment by mcastroSG** [comment]
@ckamm Checked at W7 with Version 2.2.0-nightly20160512 (build 6073) and but have to include some extra info to get to the issue. In case of including a single file to Shared Sync folder any time I "touch" the file overlay icon is finally updated in a proper way, so what I ´ve tested is:

**Steps executed**

1.- Connect desktop client to a server with checksum capabilities enabled
2.- Add an eml file to Share sync folder (file1.eml)
3.- Wait till sync ends
4.- Add a second eml file to Share sync folder (file2.eml)
5.- `copy /b file2.eml +,,`
6.- Wait till next sync ends

**Results**

Overlay icon at file2.eml is not updated from "blue sync" to "green check"

**Comment by ckamm** [comment]
@mcastroSG I've tried exactly that with the nightly20160527 on W7, but file1.eml and file2.eml's icons turned green. Does it still reproduce with a newer nightly for you?

**Comment by mcastroSG** [comment]
@ckamm  I´ve made some test on W10 with Versión 2.2.1-nightly20160530 (build 6123)  and seems to be working now. @ckamm  tk a lot

**Comment by rperezb** [comment]
just curious, is the milestone correctly set? probably this will be in 2.2.1 ? just for tracking purposes

**Comment by danimo** [comment]
Makes no sense really, since we do not know what fixed it or if it was truely fixed. But rather 2.2.1 than 2.3 now that it's closed.
