### ISSUE TITLE
Allow opening client folders when you've opened the settings. 

### ISSUE THREAD

**Issue by nneul** [owncloud/client#4824]
Currently, if you open the client by clicking on it - there is then no quick/easy way to open one of the folders like you can if you right click on the toolbar icon instead of left clicking. This seems like a completely trivial UI element that should be there. Either an 'open folder' button/icon next to the folders in the listing on settings - or an 'open ownCloud folder' toolbar icon on the settings window.

**Comment by ckamm** [comment]
The only thing that I see that one currently can do from the tray menu that's impossible from the account settings ui is openening the ownCloud account in a browser. That option could be added to the menu of the 'Account' button.

**Comment by nneul** [comment]
I now see that there is a ... dropdown on the folder listing... Completely missed that. You can probably close this. 

Thanks in both cases.

**Comment by mcastroSG** [comment]
Hi:

The "Open Folder" option appears on account menu, but as @nneul said before don´t know if it´s necessary. @ckamm What do you think ¿?

**Comment by ckamm** [comment]
@mcastroSG You should be able to open folders by right-click or in the '...' menu on them. What's new is the 'open in browser' action in the 'Account' menu in the account settings ui.

**Comment by mcastroSG** [comment]
@ckamm ok I can see the option added and it´s working fine. Still don´t know if this is really needed.
![openinbrowser](https://cloud.githubusercontent.com/assets/18436398/16679718/10ad0b7a-44ea-11e6-91bd-d556b6c50ada.png)

**Comment by ckamm** [comment]
You're right, I didn't remember one can click the link, that's much nicer. I'll remove the option again.
