### ISSUE TITLE
Owncloud client at Debian Jessie doesn't connect to server

### ISSUE THREAD

**Issue by pascalin** [owncloud/client#4826]
### Expected behaviour
Tried using both the GUI client and the command owncloudcmd, but neither of them connects to my account.

### Actual behaviour
The gui client shows a message during the setup, after introducing hostname, username and password, which says that my credentials are invalid. I tried the command line client, and, although it seems to connect it displays some errors and doesn't sync the remote files, even when I can check the same files using the very same webdav paths using my browser.

### Steps to reproduce
1. Install package owncloud-client in Debian Jessie.
2. Try to setup the GUI client or try to use the program owncloudcmd

### Server configuration
Web server:
Tried two servers: ownCloud 8 at the same machine and owncloud 9 at a i86 machine

Database:
MySQL

PHP version:
5.6
### Client configuration
Client version:
ownCloud version 1.6.4

Operating system:
Debian Jessie for armhf (Kernel Linux localhost 3.14.60-fslc-imx6-sr #1 SMP Wed Mar 16 15:29:56 UTC 2016 armv7l GNU/Linux)

OS language:
Linux

Installation path of client:
/usr/bin/owncloud

### Logs

owncloudcmd log:
https://gist.github.com/pascalin/4f4bf8d8d3202d8b1dfd122f5d982750

**Comment by dragotin** [comment]
Sorry, but version 1.6.4 is way too old. Please update to version 2.2.0 to be released today. 

Please reopen if the problem remains.
