### ISSUE TITLE
Can't install ownCloud Client 2.2.0 on kubuntu 14.04 due to libqt5core5a being at 5.2.1 and not 5.3 

### ISSUE THREAD

**Issue by kylejvrsa** [owncloud/client#4830]
### Expected behaviour

I have a default kubuntu 14.04 install and when I try to update the client it complains about the libqt5core5a being at 5.2.1 and it needs 5.3 as a minimum.
### Steps to reproduce

On a default kubuntu 14.04:
1. Install/Update owncloud using owncloud repo with sudo aptitude
### Client configuration

Client version: 2.2.0

Operating system: Kubuntu 14.04

OS language: eng

Installation path of client: default

**Comment by RealRancor** [comment]
Should be fixed after the 14.04 packages are correctly built against QT4 instead of QT5 as requested here: https://github.com/owncloud/client/issues/4828#issuecomment-218875414

**Comment by allmyfavoriteusernamesaretaken** [comment]
Same here on Ubuntu 14.04:

```
$ sudo apt-get install owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud-client : Depends: libowncloudsync0 (= 2.2.0-2.2) but it is not going to be installed
                   Depends: libqt5core5a (>= 5.3.0) but 5.2.1+dfsg-1ubuntu14.3 is to be installed
                   Depends: owncloud-client-l10n but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Is there an expected release date for the Qt4 recompile?

**Comment by danimo** [comment]
No, but it's a long holiday weekend where most devs work.

**Comment by dances-with-clouds** [comment]
I respect your holidays, but I need that client. Synaptic has erases the old package and the new one won't install. Is there anything I can do, except working without OwnCloud synchronisation in the next few days? I am using Ubuntu Trusty. Can I get the source code and compile the package myself?

**Comment by lchigami** [comment]
Any updates with this issue?
Having problems installing owncloud-client package with a fresh Ubuntu 14.04 Install.

**Comment by jforce** [comment]
Here the same insue :-(

**Comment by dances-with-clouds** [comment]
OC client 2.2.1 is out and available, and that version does install and work on Ubuntu 14.x. :-)

**Comment by jforce** [comment]
OC client 2.2.1 avaible?
where?

**Comment by dances-with-clouds** [comment]
I am using Mint 17.3, which is bases on Ubuntu 14.4, and I am using this repository:

deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_15.04/

**Comment by mcastroSG** [comment]
I have created a new VM with a fresh Ubuntu 14.04 and 2.2.2 client is working fine after sudo apt-get update and sudo-apt-get upgrade.

**Comment by dances-with-clouds** [comment]
Thanks! I was just offered the update by my system as well. Now I am running OC Client 2.2.2 on Mint 17.3. :-)

**Comment by SamuAlfageme** [comment]
Closing as direct consequence of https://github.com/owncloud/client/issues/5470
