### ISSUE TITLE
[2.2.0]Upload speed and remaining upload time is not shown correctly

### ISSUE THREAD

**Issue by Daimonion1980** [owncloud/client#4832]
### Expected behaviour
Tell us what should happen
Tooltip should show the upload speed. Remaining Upload time gives adequate values.

### Actual behaviour
Tell us what happens instead
Tooltip shows 4kb/s upload although the upload is more than 200kb/s
Remaining upload time shows years on remaining upload although it is just hours

### Steps to reproduce
1. upload a file with client 2.2.0

### Server configuration
Operating system:
debian
Web server: 
apache2
Database:
---
PHP version:
----
ownCloud version:
8.2.4
Storage backend:
----
### Client configuration
Client version:
2.2.0

Operating system:
Win10 x64 prof
OS language:
german
Installation path of client:
---
### Logs
see screenshots below

First screenshot shows the owncloud clietn windows with visible tooltip. second screenshot shows the router upstream where you can see it's fully occupied.
![zwischenablagebild 4](https://cloud.githubusercontent.com/assets/12880413/15239650/9323bbda-18e4-11e6-81e7-6789b36de78a.jpg)
![zwischenablagebild 5](https://cloud.githubusercontent.com/assets/12880413/15239651/9326350e-18e4-11e6-891d-003e041ac7b7.jpg)

**Comment by enoch85** [comment]
I can confirm this. 

**PHP**
7

**MySQL**
5.7

**Server OS**
Ubuntu 16.04

**Client**
2.2.0

**ownCloud version**
9.0.2

**Comment by guruz** [comment]
Are you uploading 350 files as the UI text claims?
If you move the mouse does the tooltip change?

**Comment by enoch85** [comment]
> If you move the mouse does the tooltip change?

Yes.

In my case I upload 1 file and the time left says everything between 5 seconds to 1000 years...

**Comment by enoch85** [comment]
@guruz Can it have something to do with you changing the chunking? Maybe the "time-left-code" needs an update?

**Comment by Daimonion1980** [comment]
In my case 10 files are uploaded. The tooltip changes and shows the files which are uploaded. Double checked this with the logs.

**Comment by guruz** [comment]
@ckamm and @ogoffart think this is because of the way the ignored files are counted(?)

**Comment by ckamm** [comment]
* The remaining time estimate was completely wrong because of #4856, that is fixed for 2.2.1.
* There are issues with remaining-time estimation, see #4428. That's not in scope for 2.2.1.
* The upload speed being estimated completely incorrectly is new. I don't think that is related to the other issues, I'll check that out.

**Comment by ckamm** [comment]
@Daimonion1980 I've tried to reproduce the problem on linux without success so far, I'll now try Windows 7. From the code I don't see how we'd end up with a upload bandwidth estimate that stays orders of magnitude below the true value for a long period of time.

You can reproduce this every time you upload a single large file?

**Comment by danimo** [comment]
I'll move this out of 2.2.1 for now.

**Comment by Daimonion1980** [comment]
@ckamm 

After you referenced #4856 i tried the latest nigthly and with this version upload speed is shown correctly. Upload limiting works also correct. So, this case seems to be solved. Tested with Version 2.2.1-nightly20160523 (build 6107)


Regarding estimated upload time it seems it was displayed not correctly because of wrong calculating the upload speed. So at the moment the estimated upload time is not that far away in the future (Just 21 days and it seems that this value is correct. 
At the moment i can't upload my big files because of https://github.com/owncloud/core/pull/24691 but when this patch is online and working i will take a closer look to upload time estimation.

**Comment by ckamm** [comment]
@Daimonion1980 Thanks for checking, please definitely reopen this if your tests continue showing the problem!
