### ISSUE TITLE
Interface broken on client 2.2.0 and Ubuntu 16.04

### ISSUE THREAD

**Issue by Michaelvilleneuve** [owncloud/client#4833]
### Expected behaviour
Interface should look normal even under a hidpi screen (apparently, it happens also on normal displays)

### Actual behaviour
Interface is broken, some elements are huge and pixelized while texts are too small

### Steps to reproduce
1. Install Ubuntu 16.04
2. Install owncloud 2.2.0
3. Check owncloud interface

### Client configuration
Client version: 2.2.0

Operating system: Ubuntu 16.04

OS language: French

![capture du 2016-05-13 09-00-46](https://cloud.githubusercontent.com/assets/4990201/15240466/1c5a6066-18ea-11e6-9979-0228f90306d8.png)

![image](https://cloud.githubusercontent.com/assets/4990201/15240486/3fe16016-18ea-11e6-8b24-ec7df7ae95f9.png)

**Comment by piratenpanda** [comment]
Even on non HiDPI screens it looks this way for me XPS13 FHD here

**Comment by Michaelvilleneuve** [comment]
@piratenpanda  Ok, I updated the issue, thanks

**Comment by piratenpanda** [comment]
I am on Arch + GNOME but I guess it doesn't really matter

**Comment by guruz** [comment]
I'm closing this in favor of https://github.com/owncloud/client/issues/4840
Can you guys please comment there, also mentioning the Qt version used (see client settings dialog).
Also please comment if this is a regression.

FYI @danimo @dragotin
