### ISSUE TITLE
remote share: accept action in client windows fails 

### ISSUE THREAD

**Issue by thommierother** [owncloud/client#4834]
### Expected behaviour
When a notification for a remote share is received and displayed, It should be possible to accept the share
 
### Actual behaviour
a click on "accept" only shows error message "Akzeptiere Anfrage ... fehlgeschlagen"

### Steps to reproduce
1. create remote share on different owncloud instance (both OC instances are OC 9.02). 
2.  click on "accept" button in the server activity window

### Server configuration
Operating system: Ubuntu 14.04 LTS

Web server: 
Apache 2.4.x
Database: MySQL

PHP version: 5.5.x

ownCloud version: 9.02

Storage backend: ext4

### Client configuration
Client version: 2.2.0

Operating system: OpenSuse Leap 42.1

OS language: german

Installation path of client:/usr/bin/owncloud

### Logs
no log entry in .owncloudsync.log

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by mcastroSG** [comment]
@thommierother may you try to start owncloud client as : `owncloud --logwindow` any time you click on accept button a server answer should appear at log window that could be helpful to solve this issue.

**Comment by thommierother** [comment]
unfortunately this is not possible at the moment due to a broken 2.2.x client, see #4829

I noticed the same error in the web interface so the root cause is on the server side, not the client
