### ISSUE TITLE
[2.2.0]Upload Quota flushes Logfile

### ISSUE THREAD

**Issue by Daimonion1980** [owncloud/client#4837]
### Expected behaviour
On limit the uplod to a specific bandwith the logwindow should post upload quota only from time to time.

### Actual behaviour
Upload Quota log entry flushes the logfile

### Steps to reproduce
1. quote the upload bandwith
2. open the ligfile on windows by hitting F12
3. see the log entries every 100ms

### Server configuration
Operating system:
---
Web server: 
---
Database:
---
PHP version:
---
ownCloud version:
---
Storage backend:
---
### Client configuration
Client version:
2.2.0
Operating system:
win10 x64
OS language:
german
Installation path of client:
c:\
### Logs
https://gist.github.com/Daimonion1980/0e06a81e35904f8c15d496e1ff656b2b

Here are also 2 screenshots:
![zwischenablagebild 6](https://cloud.githubusercontent.com/assets/12880413/15254105/6696c8cc-1935-11e6-8c10-d6bcd84e8e5c.jpg)
![zwischenablagebild 7](https://cloud.githubusercontent.com/assets/12880413/15254106/669a13f6-1935-11e6-981e-c98ec4c750f6.jpg)

**Comment by Daimonion1980** [comment]
Maybe this issue corresponds with the issue i posted this morning:

https://github.com/owncloud/client/issues/4832

As seen in the codelisting:
https://github.com/owncloud/client/blob/5479aaeb5bf2994fb7fd14edf3811b90af27d38b/src/libsync/propagateupload.cpp#L399

the debug message is fired when maxlen <= 0 

If the upload bandwith is not calculated correctly this if query can run amok...

**Comment by guruz** [comment]
Thank you, i will remove this message.
