### ISSUE TITLE
[2.2.0] Upload Big Files Throws Error

### ISSUE THREAD

**Issue by protree** [owncloud/client#4843]
### Expected behaviour
Upload of big files should work without any errors

### Actual behaviour
Upload of big files throws errors (see below) and takes much longer than expected, but still finishes

### Steps to reproduce
1. Upload a big file (e.g. > 500 mb) via Desktop Client on Mac

### Server configuration
Operating system:
Ubuntu 14.04

Web server: 
Apache

Database:
MySQL

PHP version:
5.5.9-1ubuntu4.16

ownCloud version:
9.0.2

Storage backend:

### Client configuration
Client version:
2.2.0

Operating system:
OSX 10.11.4

OS language:
German

Installation path of client:

### Logs

```<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\BadRequest</s:exception>
  <s:message>expected filesize 10000000 got 0</s:message>
</d:error>```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
FYI @PVince81

**Comment by Daimonion1980** [comment]
i can confirm this!

**Comment by guruz** [comment]
Might actually be fixed by  https://github.com/owncloud/core/pull/24676

**Comment by danimo** [comment]
Will be fixed with the next server release.
