### ISSUE TITLE
Windows:mingw32-make not found ownCloud.rc

### ISSUE THREAD

**Issue by chongjibo** [owncloud/client#4846]
Hi,everyone:
I follow  https://github.com/owncloud/mirall/blob/master/doc/building.rst：Windows Development Build，
But i get the error at mingw32-make:
[ 29%] Built target owncloud_automoc
[ 30%] Automatic moc for target updater
[ 30%] Built target updater_automoc
[ 32%] Built target updater
**[ 32%] Generating ownCloud.ico, ownCloud.rc
D:/owncloud_build/src/gui/ownCloud.rc: No such file or directory
src\gui\CMakeFiles\owncloud.dir\build.make:405: recipe for target 'src/gui/ownCl
oud.ico' failed
mingw32-make[2]: *** [src/gui/ownCloud.ico] Error 1
CMakeFiles\Makefile2:338: recipe for target 'src/gui/CMakeFiles/owncloud.dir/all
' failed
mingw32-make[1]: *** [src/gui/CMakeFiles/owncloud.dir/all] Error 2
makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2**
When I use Cmake3.5.2(cmake-gui),I dont konw what is the :PNG2ICO_ECECUTABLE,What should I fill in？I found some solutions,what is the "kedwin-png2ico"? where can I get it?

My English is not good，sorry.

**Comment by dragotin** [comment]
I am sorry, this is a bug tracker, not a support forum. Please go there, or to the developers mailing list.
