### ISSUE TITLE
Avoid syncing all files

### ISSUE THREAD

**Issue by nawrasg** [owncloud/client#4847]
Hi,

I'm using ownCloud to sync my files across multiple computers but depending on the PC, I don't need to sync all files.
Is it possible to sync only files "signatures" and then choose which files I want to download/fully sync?

Thanks,

**Comment by danimo** [comment]
Not yet. This is being discussed as part of #4341. Generally, please use this as an issue tracker. For general support please refer to http://owncloud.org/support.

**Comment by nawrasg** [comment]
Thank you :)
