### ISSUE TITLE
[2.2] libssl-dev missing in package dependencies

### ISSUE THREAD

**Issue by hbcramboll** [owncloud/client#4848]
I tried to build the client from source - mainly because I am interested in the owncloudcmd tool.

I followed the general instructions on the [Owncloud Client Manual page](https://doc.owncloud.org/desktop/1.8/building.html). Particularly, `apt-get build-dep owncloud-client` was done.

Running cmake ../produced this error
```
CMake Error at /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:136 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_LIBRARIES
  OPENSSL_INCLUDE_DIR) (Required is at least version "1.0.0")
Call Stack (most recent call first):
  /usr/share/cmake-3.0/Modules/FindPackageHandleStandardArgs.cmake:343 (_FPHSA_FAILURE_MESSAGE)
  /usr/share/cmake-3.0/Modules/FindOpenSSL.cmake:328 (find_package_handle_standard_args)
  CMakeLists.txt:132 (find_package)
```
Fetching the libssl-dev package solves the problem.
`apt-get install libssl-dev`

This leads me to believe that the dependency to libssl-dev is missing. 

### System configuration
Operating system: Bananian 16.04 r1, port of Debian GNU/Linux 8 (jessie)
`>uname -a`
`Linux bananapi 3.4.111-bananian #5 SMP PREEMPT Fri Mar 25 17:24:42 UTC 2016 armv7l GNU/Linux `

**Comment by guruz** [comment]
Something for @hefee @jnweiger

**Comment by jnweiger** [comment]
libssl-dev is listed both in the control and dsc file as Build-Depends:
<pre>
grep -B1 libssl-dev *
 debian.control-Build-Depends: debhelper (>= 9), cmake, sed, doxygen,
 debian.control:	libsqlite3-dev, python-sphinx | python3-sphinx, libssl-dev,
 --
 owncloud-client.dsc-Build-Depends: debhelper (>= 9), cmake, sed, doxygen,
 owncloud-client.dsc:	libsqlite3-dev, python-sphinx | python3-sphinx, libssl-dev,
</pre>

Could anybody please enlighten me, what extra steps are needed to make ```apt-get build-dep``` work? I believe it should, as is.

**Comment by jnweiger** [comment]
I cannot check the details with bananian, though. 

@hbcramboll please review my diagnostics above and reopen if needed.
