### ISSUE TITLE
v2.2.0 Linux puts dash icon in upper-left corner, on top of window close button

### ISSUE THREAD

**Issue by livewyer** [owncloud/client#4849]
### Expected behaviour
Normally the dash icon appears in the upper-left with the other dash icons, such as battery, network, time, etc.

### Actual behaviour
Since upgrading to 2.2.0, the icon is all the way to the left and covers up the close window button for maximized windows.  Starting client from command line produced same behavior.
![owncloud-dash-upper-left](https://cloud.githubusercontent.com/assets/1088354/15308587/925a6d8a-1ba4-11e6-8830-74caf33fbf54.png)

### Steps to reproduce
1. Upgrade to v2.2.0
2. Look in upper-left corner
3. 

### Server configuration
n/a

### Client configuration
Client version: 2.2.0%nil (build 1605)

Operating system: Ubuntu 14.04

OS language: English US

Installation path of client: /usr/bin/owncloud

**Comment by fr00x** [comment]
I am on the same version and can't see the dash icon anymore - I see a strange green rectancle on my secondary monitor, upper left though.

**Comment by jeanlepaul** [comment]
I have the same problem (icon on the left) with the same build, on Ubuntu 14.04 as well with OS Language: French

**Comment by yowell** [comment]
Duplicate: #4828

**Comment by mcastroSG** [comment]
Closing this issue plz follow up this on [#4828](https://github.com/owncloud/client/issues/4828)

Thanks @yowell

**Comment by livewyer** [comment]
@mcastroSG @yowell Thanks.  Did a search before creating this issue and didn't find #4828 .
