### ISSUE TITLE
docker based win installer build broken

### ISSUE THREAD

**Issue by butonic** [owncloud/client#4852]
I am trying to buld the client as per the documentation

### Expected behaviour
Following the build instuctions in https://doc.owncloud.org/desktop/2.2/building.html should give me a win installer

### Actual behaviour
```console
~/Repositories/client$ docker run owncloud-client-win32:2.2 -v "$PWD:/home/jenkins/client" admin/win32/docker/build.sh $(id -u)
docker: Error response from daemon: Container command '-v' not found or does not exist..
~/Repositories/client$ docker run -v "$PWD:/home/jenkins/client" owncloud-client-win32:2.2 /home/jenkins/client/admin/win/docker/build.sh $(id -u)
su: warning: cannot change directory to /home/user: No such file or directory
-bash: line 1: cd: /home/user/1000: No such file or directory
mkdir: cannot create directory 'build-win32': Permission denied
-bash: line 4: cd: build-win32: No such file or directory
-bash: line 5: ../admin/win/download_runtimes.sh: No such file or directory
CMake Error: The source directory "/" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
make: *** No targets specified and no makefile found.  Stop.
make: *** No rule to make target 'package'.  Stop.
Test project /
Cannot create directory //Testing/Temporary
Cannot create log file: LastTest.log
No tests were found!!!
```

At this point looking at build.sh ... I can only guess `s/user/jenkins/g` or something like that ... 
### Steps to reproduce
1. fix doc as in https://github.com/owncloud/client/pull/4851
2. follow documentation

### Server configuration
```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
$ docker -v
Docker version 1.11.1, build 5604cbe
```

### Client configuration
Client version: 2.2

**Comment by linucksrox** [comment]
I ran into this same issue. I don't understand why an issue like this has a milestone... so you won't tell us how to build the client until a later version? Someone is able to build it... What am I missing?

**Comment by ckamm** [comment]
The build instructions have been updated by @ogoffart in 8b5f71f49eb2c1527092a584f017fc914b4bd06b

**Comment by hanhuakai880101** [comment]
when I run command:
docker run -v "$PWD:/home/user/client" owncloud-client-win32:2.3 /home/user/client/admin/win/docker/build.sh client/  $(id -u)

output as follows:
useradd: UID 0 is not unique
su: user user does not exist

why occure this error, @ckamm  thanks~

**Comment by SamuAlfageme** [comment]
@hanhuakai880101 for a step by step guide on how I usually do this, you can read my answer in: https://central.owncloud.org/t/error-using-docker-to-build-the-windows-client/5107/4

**Comment by ckamm** [comment]
@hanhuakai880101 I don't know about this, sorry.

**Comment by hanhuakai880101** [comment]
@ckamm  @SamuAlfageme 
thanks for reply , I have made owncloud client for Windows success
client/admin/win/docker/build.sh  
useradd user -u ${2:-1000}    -->  useradd user -o -u ${2:-1000} 

I use client 2.2.4 release code to build 
git clone git://github.com/owncloud/client.git
git reset --hard f1e2e42d99ccc221eeeaa612ef3550c82363354b
