### ISSUE TITLE
[2.2.0] hour(s), minute(s), second(s) not translated in progress bar

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#4855]
<img width="800" alt="os_x_10_11" src="https://cloud.githubusercontent.com/assets/214010/15332598/864ab3ac-1c66-11e6-9c70-f1f37fce3ad6.png">

### Expected behaviour
String for time units should be translatable.

### Actual behaviour
This string isn't translated in German and Dutch, and I didn't found it in Transifex.

### Steps to reproduce
1. run ownCloud client in German or Dutch language
2. upload files and check progress bar

### Server configuration
ownCloud version:
oC 9.0.2

### Client configuration
Client version:
2.2.0

Operating system:
Mac OS X 10.11.1

OS language:
German/Dutch

Installation path of client:
/Applications/owncloud.app

@dragotin Could you check if this string is translatable in the sources? (I checked the current master too)

00005497

**Comment by ogoffart** [comment]
It might take some time for the translations to adjust.

**Comment by michaelstingl** [comment]
@ogoffart Where can i find this string in the sourcecode?

**Comment by ogoffart** [comment]
in utility.cpp

**Comment by ogoffart** [comment]
(The link to the commit that fixes the issue:  30c8fa1c93744afb8f8a7005717e142c69f51d9d )

**Comment by michaelstingl** [comment]
@ogoffart Thanks, very cool! Let's wait for the strings in Transifex…

**Comment by frank9999** [comment]
The fix doesn't seem to work. I changed the translations myself to test this patch:

diff --git a/translations/client_nl.ts b/translations/client_nl.ts
index 18ae6cd..59d4936 100644
--- a/translations/client_nl.ts
+++ b/translations/client_nl.ts
@@ -3570,32 +3570,32 @@ We adviseren deze site niet te gebruiken.</translation>
     <message>
         <location filename="../src/libsync/utility.cpp" line="314"/>
         <source>%n year(s)</source>
-        <translation type="unfinished"/>
+        <translation>%n ja(a)r(en)</translation>
     </message>
     <message>
         <location filename="../src/libsync/utility.cpp" line="315"/>
         <source>%n month(s)</source>
-        <translation type="unfinished"/>
+        <translation>%n maand(en)</translation>
     </message>
     <message>
         <location filename="../src/libsync/utility.cpp" line="316"/>
         <source>%n day(s)</source>
-        <translation type="unfinished"/>
+        <translation>%n dag(en)</translation>
     </message>
     <message>
         <location filename="../src/libsync/utility.cpp" line="317"/>
         <source>%n hour(s)</source>
-        <translation type="unfinished"/>
+        <translation>%n u(u)r(en)</translation>
     </message>
     <message>
         <location filename="../src/libsync/utility.cpp" line="318"/>
         <source>%n minute(s)</source>
-        <translation type="unfinished"/>
+        <translation>%n minu(u)t(en)</translation>
     </message>
     <message>
         <location filename="../src/libsync/utility.cpp" line="319"/>
         <source>%n second(s)</source>
-        <translation type="unfinished"/>
+        <translation>%n seconde(n)</translation>
     </message>
     <message>

The text in the progress bar is still half translated. X hour(s), where all other parts are dutch.
Is there something wrong with my translation patch?

**Comment by michaelstingl** [comment]
@frank9999 Thank you for your feedback!

**Comment by frank9999** [comment]
Is there any progress on this issue? We are willing to test any new patches as soon as you have them

**Comment by danimo** [comment]
@frank9999 Yes, the current nighly builds have the fix. https://download.owncloud.com/download/nightly/

**Comment by michaelstingl** [comment]
@danimo thanks!

**Comment by frank9999** [comment]
The nightly builds are not based on https://github.com/owncloud/client/commits/2.2 ? I'm not seeing any new fixes after I tested this issue.

**Comment by ogoffart** [comment]
For some reason, the problem seems to be that transifex does not generate corectly the plural form that is required for strings with %n 
It works fr other strings.  I don't know what's so special about this one

**Comment by ogoffart** [comment]
I found the bug:  https://bugreports.qt.io/browse/QTBUG-3945
I'll work around the problem.
It might take some time for the translations to adjust

**Comment by frank9999** [comment]
The fix seems to work for me! Thanks!

**Comment by mcastroSG** [comment]
Seems to be solved in Spanish too. @michaelstingl  may we close this ¿?
