### ISSUE TITLE
[2.2.0 Ubuntu] Status window not appearing anymore

### ISSUE THREAD

**Issue by maxxer** [owncloud/client#4857]
As already reported [on the forum](https://forum.owncloud.org/viewtopic.php?p=116776&sid=03f02c270b9b0b1932938d313828c844#p116767):

I installed ownCloud desktop client 2.2 as soon as the Ubuntu package was ready for 15.10.

At first I experienced gui weirdness, somehow as already reported on #4840 and other bugs.
After some open and close of the client (I was on a dual monitor at the moment) I'm now unable anymore to show the main ownCloud dialog. The tray icon is stuck into the scanning status (not sure), I can pop the option menu, I can pause and restore sync, exit and relogin to the account, open local folder and remote website, but when I click *Settings...* the window won't show.

I tried removing ~/.local/share/data/ownCloud but even with an unconfigured client the window would not show.

Is there anything I can check to provide more informations?

Package owncloud-client:amd64 2.2.0-4.1 (from official packages)
Ubuntu 15.10 amd54

**Comment by guruz** [comment]
FYI @jnweiger @dragotin @danimo 

Does https://github.com/owncloud/client/issues/4693#issuecomment-215944779 help?

**Comment by maxxer** [comment]
No, I don't even see the tray icon that way

**Comment by ogoffart** [comment]
Could be a crash.  Can you open it from the conole?
Is the owncloud process running or not?

**Comment by maxxer** [comment]
I don't know what you mean by *running*. I can see the tray icon, but it's not syncing if this is what you meant. Strangely I can pause and restore sync, logout and relogin, but cannot see anything else.

After running `owncloud --logwindow` I managed somehow to make it run again, and it's syncing! But setting window is screwed up, which goes back to #4840 

![image](https://cloud.githubusercontent.com/assets/240201/15395998/6541557e-1dda-11e6-8134-7b74bb18af36.png)

**Comment by maxxer** [comment]
I don't know if you want to do further investigation, otherwise the bug can be closed
