### ISSUE TITLE
[Linux] [2.2.0] [openSUSE 13.1] Client crash on start: undefined symbol: _ZN9QKeychain3Job6setKeyERK7QString

### ISSUE THREAD

**Issue by wollir72** [owncloud/client#4860]
### Expected behaviour
Client running and icon is visible

### Actual behaviour
The client crash at start

### Steps to reproduce
1. Start client
2. Client crash

### Server configuration
Operating system: openSUSE 13.2

ownCloud version: 8.1.7 (stable)

### Client configuration
Client version: 2.2.0

Operating system: openSUSE 13.1

OS language: German

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`

wolli@darkpenguin:~> owncloud --logfile log.txt
owncloud: symbol lookup error: /usr/lib64/libowncloudsync.so.0: undefined symbol: _ZN9QKeychain3Job6setKeyERK7QString

Content of log.txt:
05-18 20:21:18:608 0xbd87a0 "################## ownCloud de_DE () 2.2.0" 
05-18 20:21:18:608 0xbd87a0 void OCC::Application::setupTranslations() Using "de_DE" translation 
05-18 20:21:18:608 0xbd87a0 SocketApi:  server started, listening at  "/run/user/1000/ownCloud/socket" 
05-18 20:21:18:608 0xbd87a0 setting remote poll timer interval to 30000 msec 
05-18 20:21:18:650 0xbd87a0 * Setup folders from settings file 
05-18 20:21:18:650 0xbd87a0 Checked local path ok 
05-18 20:21:18:650 0xbd87a0 ==== adding system ignore list to csync: "/etc/ownCloud/sync-exclude.lst" 
05-18 20:21:18:650 0xbd87a0 ==== adding user defined ignore list to csync: "/home/wolli/.local/share/data/ownCloud/sync-exclude.lst" 
05-18 20:21:18:650 0xbd87a0 Adding folder to Folder Map  OCC::Folder(0xdc64e0) "ownCloud" 
05-18 20:21:18:650 0xbd87a0 (+) Watcher: "/home/wolli/ownCloud/" 
05-18 20:21:18:800 0xbd87a0 * Ignoring file "/home/wolli/ownCloud/Bilder/Cars/G270CDI/.Thumbnails" 
05-18 20:21:18:800 0xbd87a0 * Not adding "/home/wolli/ownCloud/Bilder/Cars/G270CDI/.Thumbnails" 
....
05-18 20:21:18:865 0xbd87a0 Schedule folder  "ownCloud"  to sync! 
05-18 20:21:18:865 0xbd87a0 Folder is not ready to sync, not scheduled! 
05-18 20:21:18:865 0xbd87a0 Set proxy configuration to use system configuration 
05-18 20:21:18:876 0xbd87a0 Starting Notification refresh timer with  300  sec interval 
05-18 20:21:18:903 0xbd87a0 Sys Info size:  372 
05-18 20:21:18:960 0xbd87a0 Object::connect: No such signal OCC::FolderStatusModel::dataChanged(QModelIndex,QModelIndex,QVector<int>)
05-18 20:21:19:020 0xbd87a0 sqlite3 version "3.7.17" 
05-18 20:21:19:020 0xbd87a0 sqlite3 journal_mode= "wal" 
05-18 20:21:19:020 0xbd87a0 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect" and starting new transaction 
05-18 20:21:19:020 0xbd87a0 Columns in the current journal:  ("phash", "pathlen", "path", "inode", "uid", "gid", "mode", "modtime", "type", "md5", "fileid", "remotePerm", "filesize", "ignoredChildrenRemote", "contentChecksum", "contentChecksumTypeId") 
05-18 20:21:19:020 0xbd87a0 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add inode index" and starting new transaction 
05-18 20:21:19:021 0xbd87a0 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add path index" and starting new transaction 
05-18 20:21:19:021 0xbd87a0 Columns in the current journal:  ("path", "lastTryEtag", "lastTryModtime", "retrycount", "errorstring", "lastTryTime", "ignoreDuration") 
05-18 20:21:19:021 0xbd87a0 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect End"  
05-18 20:21:19:055 0xbd87a0 Checking server and authentication 
05-18 20:21:19:055 0xbd87a0 Trying to look up system proxy 
05-18 20:21:19:055 0xdbbd70 virtual void OCC::SystemProxyRunnable::run() Starting system proxy lookup 
05-18 20:21:19:057 0xbd87a0 No system proxy set by OS 
05-18 20:21:19:058 0xbd87a0 Object::connect: No such signal QNetworkReplyImpl::encrypted()
05-18 20:21:19:058 0xbd87a0 !!! OCC::CheckServerJob created for "https://192.168.4.14/owncloud" + "status.php" "OCC::ConnectionValidator" 
05-18 20:21:19:496 0xbd87a0 Saving account "https://192.168.4.14/owncloud" 
05-18 20:21:19:497 0xbd87a0 Saving  3  unknown certs. 
05-18 20:21:19:497 0xbd87a0 Saving cookies. 
05-18 20:21:19:497 0xbd87a0 "/home/wolli/.local/share/data//ownCloud//cookies.db" 
05-18 20:21:19:498 0xbd87a0 Saved account settings, status: 0 
05-18 20:21:19:579 0xbd87a0 status.php returns:  QMap(("edition", QVariant(QString, "") ) ( "installed" ,  QVariant(bool, true) ) ( "maintenance" ,  QVariant(bool, false) ) ( "version" ,  QVariant(QString, "8.1.7.2") ) ( "versionstring" ,  QVariant(QString, "8.1.7") ) )    0  Reply:  QNetworkReplyImpl(0xe12810) 
05-18 20:21:19:579 0xbd87a0 ** Application: ownCloud found:   QUrl( "https://192.168.4.14/owncloud/status.php" )   with version  "8.1.7" ( "8.1.7.2" ) 
05-18 20:21:19:579 0xbd87a0 AccountState connection status change:  "Undefined" -> "Credentials Wrong"

**Comment by guruz** [comment]
Did you try reinstalling a current version of QtKeychain?

**Comment by lemmingzshadow** [comment]
Same behavior on Xubuntu 14.04. Client crashes with the following error:

owncloud: symbol lookup error: /usr/lib/x86_64-linux-gnu/libowncloudsync.so.0: undefined symbol: _ZN9QKeychain3Job6setKeyERK7QString

**Comment by wollir72** [comment]
After reinstalling QtKeychain client start, ask me for password and running. Thank you :-)

**Comment by wollir72** [comment]
Issue fixed by reinstalling QtKeychain.
