### ISSUE TITLE
Current owncloud-client library:libqtkeychain0 breaks Tomahawk-Player

### ISSUE THREAD

**Issue by DroWnThePoor** [owncloud/client#4862]
### Expected behaviour
Both pieces of software should work fine while relying on same library.

### Actual behaviour
Tomahawk Player does not open if owncloud-client is installed.

### Steps to reproduce
1. Install Tomahawk and open.
2. Install ownCloud-Client and update.
3. "Try" to open Tomahawk.
4. Disable owncloud-client repository.
5. Remove libqtkeychain0.
6. Re-install Tomahawk.
7. Run Tomahawk as before.

### Server configuration
Operating system: Ubuntu 14.04.

Web server: Apache 2.4

Database: Mysql 5.5.49

PHP version: 5.5.9

ownCloud version: 8.8.9

Storage backend: N/a

### Client configuration
Client version: 2.2

Operating system: Elementary OS Freya(ubuntu 14.04)

OS language: English

All of this started on my main workstation,
but was confirmed and tested via a virtual machine.
See:
https://github.com/tomahawk-player/tomahawk/issues/509
For the output from Tomahawk.

**Comment by guruz** [comment]
@dschmidt @jnweiger

**Comment by dschmidt** [comment]
Not sure, what I'm to say here. As pointed out several times by now already, it's a distribution issue and thus neither ownCloud's nor Tomahawk's fault

**Comment by dschmidt** [comment]
Are you maybe using ownCloud repositories? Those of course might break things ... Can you get us a list of your enabled repositories?

**Comment by DroWnThePoor** [comment]
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.04/ 

When this repo is enabled it does an upgrade to libqtkeychain0 with any install/update of ownCloud-Client.

To me this appears to be from the ownCloud repository yes, because if I disable this repo, do an uninstall/re-install of libqtkeychain0, Tomahawk will open and run properly.

I noticed this because Tomahawk was running fine until the upgrade of oc-client,
You then pointed out from my output that it was a libqtkeychain0 issue, and I saw that it 
was a dependency for both programs. One of the other members in the #Tomahawk irc 
channel suggested I let owncloud-client devs know about this.

**Comment by dschmidt** [comment]
Yes, this is definitely an owncloud packaging issue. If you need to build a newer qtkeychain I recommend to bump the soversion and have the package named accordingly, so you dont break other packages depending on the original qtkeychain0

**Comment by danimo** [comment]
@dschmidt even worse: it's an upstream issue: https://github.com/frankosterfeld/qtkeychain/issues/73

**Comment by dschmidt** [comment]
Ah, of course. I just didnt remember qtkeychain was a proper library, not a codedump like libcrashreporter-qt :D

**Comment by danimo** [comment]
We have fixed this in the nightly repository. Please give that a try. see https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/qt5keychain and https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/qtkeychain

**Comment by DroWnThePoor** [comment]
How should I go about using this? Is this packaged with the fixed owncloud-client? Or do I need to wget this specific package?

**Comment by DroWnThePoor** [comment]
@danimo Got the nightly build up and running with the new libs(thanks to:@dschmidt) so this completely solves my problem, thank you both so much.

**Comment by e-alfred** [comment]
Hello,

will this be solved in the stable version as well? Currently the problem still exists using this version.
