### ISSUE TITLE
[2.2.0]chunked upload does not end (upload in the loop)

### ISSUE THREAD

**Issue by Daimonion1980** [owncloud/client#4868]
### Expected behaviour

Chunks of big files will upload only one time and file wil be build on the server correctly. Even when the upload of chunks is disrupted in case of a internet disconnect.
### Actual behaviour

Chunks will be upload a second or even a third time and the file will not be build correctly. Etag not available failure appears, once the server or the client thinks chunk upload is fully completed in the middle of the chunk list. 
### Steps to reproduce
1. upload big files with a slow connection (DSL Connection)
2. it happens that the connection is broken ( DSL reconnect, Server down, Standby of client pc, in my case manual diconnect and reconnect to reproduce the failure)
3. after the last chunk is uploaded the upload starts over with chunk 0
4. sometimes it happens that the chunking stops in the middle of the chunklist, but then the server replies with E-Tag not available - See log message below
### Server configuration

Operating System:
Debian GNU/Linux 8.4 (jessie)
WebServer:
Apache 2.4.10 (2.4.10-10+deb8u4)
Database:
MySQL 5.5 (5.5.49-0+deb8u1)
PHP:
PHP 5.6.20 (5.6.20+dfsg-0+deb8u1 )
owncloud Server: 
8.2.5
### Client configuration

Client version:
2.2.0
Operating system:
Win10 Pro x64
OS language:
German
Installation path of client:
c:\Programms.....
### Logs

https://gist.github.com/Daimonion1980/e86b15260305660216de9b84ebb9eeb4#file-chunked-upload-does-not-work

http://owncloud.10557.n7.nabble.com/wanted-behaviour-on-chunking-big-files-and-upload-them-td17249.html

As described in the mailing list and now reproduceable confirmed on my system i am not able to upload big files over a slow connection when the connection is broken for a small time.

In my example i tried to upload a 1,95 GB File over my dsl upload and as in reality sometimes happen i reconnected my internet connection manually. This event disrupted the upload and a failure appeared to the 3 uploaded chunks at this moment in the logfile: "Schreibvorgang konnte nicht ausgeführt werden"
https://gist.github.com/Daimonion1980/e86b15260305660216de9b84ebb9eeb4#file-chunked-upload-does-not-work-L606

After the connection was restablished the upload starts by resuming the aborted chunks

https://gist.github.com/Daimonion1980/e86b15260305660216de9b84ebb9eeb4#file-chunked-upload-does-not-work-L1709

So long so good. But as the client reaches the end of the file he started over at chunk 0 although this chunk was still uploaded:

https://gist.github.com/Daimonion1980/e86b15260305660216de9b84ebb9eeb4#file-chunked-upload-does-not-work-L3072

In reality there not only one file. In my case i'm trying to upload 600GB of files, each 2 - 8 GB through this slow connection ( i know this is really stupid but it's the best way to get the data automaticcally and ongoing out of my house to the server from my brother in law. Nad when the initial upload is ready it doesn't take mor data...)
Furthermore i have to handle more bugs which are already filed here at issuetracker
https://github.com/owncloud/client/issues/4843
https://github.com/owncloud/client/issues/4856

When the client (or the server, i don't know) thinks upload is finished in the middle of the chunking list (in this case by finish uploading chunk 65) the server tries to build the file but dows not find any etag information and replies:

05-19 23:38:13:011 0x5008de0 OCC::AbstractNetworkJob::start: !!! OCC::PUTFileJob created for "https://homer.tld.de/cld" + "/Backup/Moiner/Userdata_full_b1_s1_v45.tib-chunking-2982076973-210-65" ""
05-19 23:38:16:487 0x5008de0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
05-19 23:38:16:489 0x5008de0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://homer.tld.de/cld" + "/" "OCC::ConnectionValidator"
05-19 23:38:37:023 0x5008de0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://homer.tld.de/cld" + "/" "OCC::QuotaInfo"
05-19 23:38:48:486 0x5008de0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
05-19 23:38:48:487 0x5008de0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://homer.tld.de/cld" + "/" "OCC::ConnectionValidator"
05-19 23:38:50:048 0x5008de0 OCC::PropagateUploadFileQNAM::slotPutFinished: void OCC::PropagateUploadFileQNAM::slotPutFinished()  QUrl( "https://homer.tld.de/cld/remote.php/webdav/Backup/Moiner/Userdata_full_b1_s1_v45.tib-chunking-2982076973-210-65" )  FINISHED WITH STATUS 0 "" QVariant(int, 201) QVariant(QString, "Created")
05-19 23:38:50:051 0x5008de0 OCC::SyncJournalErrorBlacklistRecord::update: blacklisting  "Backup/Moiner/Userdata_full_b1_s1_v45.tib"  for  25 , retry count  1
05-19 23:38:50:054 0x5008de0 OCC::SyncJournalDb::updateErrorBlacklistEntry: set blacklist entry for  "Backup/Moiner/Userdata_full_b1_s1_v45.tib" 1 "Der Server hat den letzten Block nicht bestätigt. (Der E-Tag war nicht vorhanden)" 1463693930 25 1462130590 ""
05-19 23:38:50:056 0x5008de0 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "Backup/Moiner/Userdata_full_b1_s1_v45.tib" INSTRUCTION_NEW 2 "Der Server hat den letzten Block nicht bestätigt. (Der E-Tag war nicht vorhanden)"

I reproduced this behaviour with 2.1.1 and 2.2.0

I hope you/we will find a solution for this!

Regards Daimonion

**Comment by conturNDE** [comment]
Hi all,
I'm the brother in law. If there are any questions about the server side, feel free to contact me...

kind regards,
conturNDE

**Comment by guruz** [comment]
Did you have any luck with a newer server version?

**Comment by Daimonion1980** [comment]
We switched to Owncloud 9.xx and the ulpoad worked flawlessly. Later we switched to nextcloud and also there the uploads are working great.
