### ISSUE TITLE
[Linux] [2.1.1] [openSUSE 13.2] Client crash on start: undefined symbol: _ZN9QKeychain15ReadPasswordJob6setKeyERK7QString

### ISSUE THREAD

**Issue by wollir72** [owncloud/client#4871]
### Expected behaviour
Client running and icon is visible

### Actual behaviour
The client crash at start

### Steps to reproduce
1. start client
2.  client crash

### Server configuration
Operating system: openSUSE 13.2

ownCloud version: 8.1.7 (stable)

### Client configuration
Client version: 2.1.1

Operating system: openSUSE 13.2

OS language: de

Installation path of client:

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`

wolli@linux-g5x3:~> owncloud --logfile log.txt
owncloud: symbol lookup error: /usr/lib64/libowncloudsync.so.0: undefined symbol: _ZN9QKeychain15ReadPasswordJob6setKeyERK7QString

log.txt:
05-20 09:42:25:002 0x1723710 application.cpp:338 "################## ownCloud de_DE () 2.1.1"
05-20 09:42:25:002 0x1723710 application.cpp:542 void OCC::Application::setupTranslations() Using "de_DE" translation
05-20 09:42:25:002 0x1723710 socketapi.cpp:109 SocketApi:  server started, listening at  "/run/user/1000/ownCloud/socket"
05-20 09:42:25:003 0x1723710 folderman.cpp:57 setting remote poll timer interval to 30000 msec
05-20 09:42:25:070 0x1723710 folderman.cpp:195 * Setup folders from settings file
05-20 09:42:25:070 0x1723710 folder.cpp:157 Checked local path ok
05-20 09:42:25:070 0x1723710 folderman.cpp:788 Adding folder to Folder Map  OCC::Folder(0x1974450)
05-20 09:42:25:070 0x1723710 folderwatcher_linux.cpp:92 (+) Watcher: "/home/wolli/ownCloud/"
05-20 09:42:25:137 0x1723710 folderwatcher_linux.cpp:122     `-> and 383 subdirectories
05-20 09:42:25:138 0x1723710 folderman.cpp:488 Schedule folder  "ownCloud"  to sync!
05-20 09:42:25:138 0x1723710 folderman.cpp:492 Folder is not ready to sync, not scheduled!
05-20 09:42:25:138 0x1723710 clientproxy.cpp:78 Set proxy configuration to use system configuration
05-20 09:42:25:195 0x1723710 updater.cpp:73 Sys Info size:  132
05-20 09:42:25:520 0x1723710 syncjournaldb.cpp:157 sqlite3 version "3.8.6"
05-20 09:42:25:520 0x1723710 syncjournaldb.cpp:171 sqlite3 journal_mode= "wal"
05-20 09:42:25:521 0x1723710 syncjournaldb.cpp:1591 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect" and starting new transaction
05-20 09:42:25:521 0x1723710 syncjournaldb.cpp:640 Columns in the current journal:  ("phash", "pathlen", "path", "inode", "uid", "gid", "mode", "modtime", "type", "md5", "fileid", "remotePerm", "filesize", "ignoredChildrenRemote", "contentChecksum", "contentChecksumTypeId")
05-20 09:42:25:521 0x1723710 syncjournaldb.cpp:1591 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add inode index" and starting new transaction
05-20 09:42:25:521 0x1723710 syncjournaldb.cpp:1591 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add path index" and starting new transaction
05-20 09:42:25:521 0x1723710 syncjournaldb.cpp:640 Columns in the current journal:  ("path", "lastTryEtag", "lastTryModtime", "retrycount", "errorstring", "lastTryTime", "ignoreDuration")
05-20 09:42:25:521 0x1723710 syncjournaldb.cpp:1591 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect End" 
05-20 09:42:25:682 0x1723710 connectionvalidator.cpp:69 Checking server and authentication
05-20 09:42:25:682 0x1723710 connectionvalidator.cpp:75 Trying to look up system proxy
05-20 09:42:25:682 0x1dbf8d0 clientproxy.cpp:132 virtual void OCC::SystemProxyRunnable::run() Starting system proxy lookup
05-20 09:42:25:686 0x1723710 connectionvalidator.cpp:95 No system proxy set by OS
05-20 09:42:25:686 0x1723710 abstractnetworkjob.cpp:229 !!! OCC::CheckServerJob created for "https://wrosiak.de/owncloud" + "status.php" "OCC::ConnectionValidator"
05-20 09:42:26:201 0x1723710 accountmanager.cpp:140 Saving account "https://wrosiak.de/owncloud"
05-20 09:42:26:201 0x1723710 accountmanager.cpp:173 Saving  1  unknown certs.
05-20 09:42:26:201 0x1723710 accountmanager.cpp:187 Saving cookies.
05-20 09:42:26:242 0x1723710 cookiejar.cpp:103 "/home/wolli/.local/share/data//ownCloud//cookies.db"
05-20 09:42:26:243 0x1723710 accountmanager.cpp:147 Saved account settings, status: 0
05-20 09:42:26:342 0x1723710 networkjobs.cpp:463 status.php returns:  QMap(("edition", QVariant(QString, "") ) ( "installed" ,  QVariant(bool, true) ) ( "maintenance" ,  QVariant(bool, false) ) ( "version" ,  QVariant(QString, "8.1.7.2") ) ( "versionstring" ,  QVariant(QString, "8.1.7") ) )    0  Reply:  QNetworkReplyHttpImpl(0x18eb0f0)
05-20 09:42:26:343 0x1723710 connectionvalidator.cpp:117 ** Application: ownCloud found:   QUrl( "https://wrosiak.de/owncloud/status.php" )   with version  "8.1.7" ( "8.1.7.2" )
05-20 09:42:26:343 0x1723710 accountstate.cpp:203 AccountState connection status change:  "Undefined" -> "Credentials Wrong"

On my second openSUSE 13.2 PC, the client version is also 2.1.1, the QtKeychain version is older and the client is running.

It was similar issue on openSUSE 13.1, Reinstall QtKeychain solved the issue.
With openSUSE 13.2 same problem.
I removed owncloud, removed repository path and installed owncloud client again.
The owncloud version is still 2.1.1 (I expected the new 2.2)
Reinstalled QtKeychain, but the client still crash.
On my second openSUSE 13.2 PC, the client version is also 2.1.1, the QtKeychain version is older and the client is running.

**Comment by guruz** [comment]
@wollir72 had also reported this for 13.1 https://github.com/owncloud/client/issues/4860

@jnweiger @dragotin could you help out here?

@dragotin Maybe we should link qtkeychain statically.

**Comment by jnweiger** [comment]
2.2.0 did not build for openSUSE 13.2 due to unclear errors with the dolphin plugin.
But qtkeychain 0.6.2 did succeed for openSUSE 13.2 thus we had an inconsistent situation for automatic updates. Users got the new and incompatible keychain package, but not the matching update of the client.

**Comment by dragotin** [comment]
The "unclear errors" stem from the fact that the KDE framework is too old in openSUSE 13.2 to build the overlays for dolphin.

The dolphin overlays can and should be disabled for 13.2

**Comment by jnweiger** [comment]
done.

**Comment by dragotin** [comment]
ok, can we close this?

**Comment by jnweiger** [comment]
Templates and :desktop project are now in sync. Rebuild triggered. 

@wollir72 we cannot recreate your 2.1.1 with a fixed qtkeychain dependency. Instead we now have 2.2.0 fixed for your opensuse-13.2
please try an upgrade, if possible. Reopen here, if you still have issues.
