### ISSUE TITLE
Connection Closed

### ISSUE THREAD

**Issue by okcomputerik** [owncloud/client#4874]
I've been running my owncloud for years without any major issues on another host with server version 5.0.28 (which was the latest I could install there, due to the PHP version available) and different clients. I decided to install a more recent server version (9.0.2) on my new host because I started to get the following message in my Linux client (not on the Mac, though): "The server version 5.0.28 is old and unsupported! Proceed at your own risk," which made me uneasy.

I've been trying to get my new setup running smoothly for a week without any luck.

That said...

---
### Expected behaviour

Files should sync
### Actual behaviour

The sync starts and right when the file is about to finish syncing, I get the"Connection closed" message. The file is obviously not synced, so then the client starts retrying endlessly... Both with Mac and Linux clients.
### Steps to reproduce
1. Put a file (bigger than 3-4 Mb) in local folder
2. Start sync
### Server configuration

Operating system:
Linux (I don't know exactly what distro)

Web server: 
Apache

Database:
MySQL (libmysql - mysqlnd 5.0.11-dev - 20120503)

PHP version:
5.6.21-pl0-udmedia

ownCloud version:
9.0.2 (stable)
### Client configuration

Client version:
Linux: 2.2.0-9.1.x86_64 (Built from Git revision 49a678 on May 17 2016, 17:39:40 using Qt 5.4.1, OpenSSL 1.0.1k-fips 8 Jan 2015)
Mac: 2.1.1 (build 3107)

Operating system:
Linux: Korora 4.4.9-200.fc22.x86_64
Mac: 10.10.5 (Yosemite)

OS language:
English (Linux) & Spanish (OS X)
### Logs
1. Output of `owncloud --logfile log.txt`:
   05-20 15:01:12:958 2172 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
   05-20 15:01:13:364 2172 unknown: QObject::connect: Cannot connect (null)::stateChanged(QNetworkSession::State) to QNetworkReplyHttpImpl::_q_networkSessionStateChanged(QNetworkSession::State)
2. Web server error log:
   There's apparently no log related to the "Closed connection" error, only this (which I know has to do with something else, that I can't fix either :-P ):
   
   is_readable(): open_basedir restriction in effect. File(/dev/urandom) is not within the allowed path(s): (/var/www/udXX_XXX:/usr/share/php) at /var/www/udXX_XXX/html/XXX/owncloud/3rdparty/paragonie/random_compat/lib/random.php#66 
3. ownCloud log (data/owncloud.log):
   |0|TNS.pdf|INST_NEW|Up|1444129338||4281043||1|Connection closed|0|0|0|||INST_NONE|
   # =#=#=# Syncrun started  until  (0 msec)
   
   |0|Dic/Littre|INST_REMOVE|Up|1463350369|5738f461c3ed8|0|00000028ocdcap9qjcf9|3|Error downloading https://xxxxxxxxxx.net/owncloud/remote.php/webdav/Dic/Littre - server replied: Locked|423|0|0|||INST_NONE|
   |0|TNS.pdf|INST_NEW|Up|1444129338||4281043||1|Connection closed|0|0|0|||INST_NONE|
   # =#=#=# Syncrun started  until  (0 msec)
   
   |0|Dic/Littre|INST_REMOVE|Up|1463350369|5738f461c3ed8|0|00000028ocdcap9qjcf9|3|Error downloading https://xxxxxxxxx.net/owncloud/remote.php/webdav/Dic/Littre - server replied: Locked|423|0|0|||INST_NONE|
   |0|TNS.pdf|INST_NEW|Up|1444129338||4281043||1|Connection closed|0|0|0|||INST_NONE|
   # =#=#=# Syncrun started  until  (0 msec)
   
   |0|Dic/Littre|INST_REMOVE|Up|1463350369|5738f461c3ed8|0|00000028ocdcap9qjcf9|3|Error downloading https://xxxxxxxxxxxx.net/owncloud/remote.php/webdav/Dic/Littre - server replied: Locked|423|0|0|||INST_NONE|
   |0|TNS.pdf|INST_NEW|Up|1444129338||4281043||1|Connection closed|0|0|0|||INST_NONE|
   # =#=#=# Syncrun started  until  (0 msec)
   
   |0|Dic/Littre|INST_REMOVE|Up|1463350369|5738f461c3ed8|0|00000028ocdcap9qjcf9|3|Error downloading https://xxxxxxxx.net/owncloud/remote.php/webdav/Dic/Littre - server replied: Locked|423|0|0|||INST_NONE|
   |0|TNS.pdf|INST_NEW|Up|1444129338||4281043||1|Connection closed|0|0|0|||INST_NONE|
   # =#=#=# Syncrun started  until  (0 msec)
   
   |0|Dic/Littre|INST_REMOVE|Up|1463350369|5738f461c3ed8|0|00000028ocdcap9qjcf9|3|Error downloading https://xxxxxxxx.net/owncloud/remote.php/webdav/Dic/Littre - server replied: Locked|423|0|0|||INST_NONE|
   # =#=#=# Syncrun started  until  (0 msec)
   
   |0|Dic/Littre|INST_REMOVE|Up|1463350369|5738f461c3ed8|0|00000028ocdcap9qjcf9|3|Error downloading https://xxxxxxxx.net/owncloud/remote.php/webdav/Dic/Littre - server replied: Locked|423|0|0|||INST_NONE|
   # =#=#=# Syncrun started  until  (0 msec)

The "locked file" thing is yet another issue... I can't seem to be able to delete this folder from the webserver, even though it's not on any of my clients. Every time I try I get an "Error deleting Liitre file".

---

I know the "Closed connection" issue has been a recurrent one for some time now and with different webservers and clients. I've tried to read everything I've found (like issues [#1293](https://github.com/owncloud/core/issues/12193) and #4326, and also in the forums [for instance](https://forum.owncloud.org/viewtopic.php?f=29&t=25197), but haven't found anything that works for me.

Other useful information (I think):
- I'm on a shared server, so don't have access to the Apache settings, (which seems to be a solution in most cases). However, I have contacted my hosting provider (udmedia.de) and they told me KeepAlive is activated and Timeout is set to the default Apache setting. They suggested the problem might have to do with the HTTP request or PHP application running in the background longer than my hosting package allows, which is 60 seconds.

And that's it, I guess...Any help would be much appreciated!

Cheers!

**Comment by guruz** [comment]
@okcomputerik The ```owncloud.log``` is in ```data/``` on the _server_. :)

**Comment by guruz** [comment]
> ```server replied: Locked```

Not sure what to make out of this one... FYI @PVince81

**Comment by okcomputerik** [comment]
Hi @guruz, here's the log: https://gist.github.com/okcomputerik/0bc05d6aa3265cd9629f27157ada2659

Do let me know if you need anything else.

Thanks for looking into this!

**Comment by guruz** [comment]
@okcomputerik Looks OK actually (except for those ```FileLocked ``` exceptions.)
Maybe you can ask your admin to lessen those open basedir restrictions though.

@PVince81 might know more..

**Comment by PVince81** [comment]
Locked files are normal in a concurrent environment. Sometimes there are stray locks (known issue) but they should expire after a day.

Regarding the error "The server version 5.0.28 is old and unsupported! Proceed at your own risk", @nickvergessen told me today that some older servers have a string instead of boolean for the "installed" value in their config.php

@okcomputerik can you post your config.php (and remove sensitive values).
Thanks

**Comment by nickvergessen** [comment]
> @nickvergessen told me today that some older servers have a string instead of boolean for the "installed" value in their config.php

No, I said that some people have the config as a string....

**Comment by okcomputerik** [comment]
Hi @PVince81, the "locked file" issue has been going on for about a week now. Is that still considered normal?

My config.php does have a boolean for "installed". It looks like this:

<?php
$CONFIG = array (
  'instanceid' => '53037b65f10ee',
  'passwordsalt' => ',
  'datadirectory' => '/var/www/vhosts/xxxxxxx.net/httpdocs/owncloud/data',
  'dbtype' => 'mysql',
  'version' => '5.0.28',
  'dbname' => 'xxxxxxxxx_OC',
  'dbhost' => 'localhost',
  'dbtableprefix' => 'oc_',
  'dbuser' => 'xxxxxxxx_OC',
  'dbpassword' => '',
  'installed' => true,
  'forcessl' => true,
  'loglevel' => '1',
  'maxZipInputSize' => 838860800,
  'allowZipDownload' => true,
);

Cheers!

**Comment by okcomputerik** [comment]
Hi again everybody,

The locked file issue just doesn't go away and I still can't sync files larger than a couple MBs. It's getting kind of tiring. 

These are the latest error logs:

2/7/16 9:06:41, AT, /run/media/ik/u/R/OC,Error downloading https://xxxxxxxxxx.net/owncloud/remote.php/webdav/AT - server replied: Locked
2/7/16 9:06:40, Dic/Littre, /run/media/ik/u/R/OC,Error downloading https://xxxxxxxxxx.net/owncloud/remote.php/webdav/Dic/Littre - server replied: Locked
2/7/16 9:06:40,TNAE_2015.pdf, /run/media/ik/u/R/OC,The item is not synced because of previous errors: Error downloading https://xxxxxxxxxx.net/owncloud/remote.php/webdav/TNAE_2015.pdf - server replied: Internal Server Error (An exception occurred while executing 'UPDATE `oc_file_locks` SET `lock` = -1, `ttl` = ? WHERE `key` = ? AND `lock` = 1' with params [1467446678, "files\/3977c58797ecf771e55d2ef10ffb1652"]:
SQLSTATE[HY000]: General error: 2006 MySQL server has gone away)

The last line (SQLSTATE) is new though...
-------------------------------------------------------------------------------

I tried installing a second instance of the owncloud server in case it was a problem with the installation and I get yet another error:

2/7/16 9:22:57,TNAE_2015.pdf,/run/media/ik/u/R/owncloud9,Continue blacklisting: Error downloading https://xxxxxxxxxx.net/owncloud9/remote.php/webdav/TNAE_2015.pdf - server replied: Internal Server Error (An exception occurred while executing 'UPDATE `oc_file_locks` SET `lock` = -1, `ttl` = ? WHERE `key` = ? AND `lock` = 1' with params [1467447777, "files\/3977c58797ecf771e55d2ef10ffb1652"]:

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away)

2/7/16 9:20:58, TNAE_2015.pdf,/run/media/ik/u/R/owncloud9,Error downloading https://xxxxxxxxxx.net/owncloud9/remote.php/webdav/TNAE_2015.pdf - server replied: Internal Server Error (An exception occurred while executing 'UPDATE `oc_file_locks` SET `lock` = -1, `ttl` = ? WHERE `key` = ? AND `lock` = 1' with params [1467447658, "files\/3977c58797ecf771e55d2ef10ffb1652"]:

SQLSTATE[HY000]: General error: 2006 MySQL server has gone away)

---------------------------------------------------------------------------------------------

This is the owncloud.log: https://gist.github.com/okcomputerik/522c79663e20991d57e9772977ec2496

Any  help would be much appreciated!

**Comment by PVince81** [comment]
Looks like your MySQL doesn't want to cooperate: `General error: 2006 MySQL server has gone away`
This error usually appears whenever OC was able to use the SQL connection but then for some reason MySQL closed the connection. Maybe it crashed ? Maybe check your MySQL logs.
