### ISSUE TITLE
Dynamic chunk sizing with new bigfile chunking

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4875]
Do dynamic chunk sizes with the new bigfile chunking related #4019

**Comment by cmonteroluque** [comment]
Network Traffic Improvements (for 2.3, would spend a day anazlying this to see if there is something to do)
- Ongoing excercise to make it better and faster on the network
- This includes dynamic chunk sizing and HTTP2 which was already discussed above
- Wanted to do a wireshark trace to analyze http, tcp traffic flow to see if we need to patch Qt
- It seems good, but not critical
- Then we need to provide a set of upstream patches to Qt

**Comment by guruz** [comment]
Let's move to 2.4..

**Comment by ckamm** [comment]
Dynamic chunking is in and happens in practice.
