### ISSUE TITLE
Create a clear error message for folders with trailing spaces 

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4878]
If a folder has a trailing space in the name the client should clearly state why that is ignored. The error message is too generic currently.

There is a blue ticket about that.

**Comment by ckamm** [comment]
The concrete error message (on Windows only) when attempting to upload or download a file with trailing spaces is "Filename contains invalid characters that can not be synced cross platform.".

**Comment by ckamm** [comment]
@dragotin I went with a simple "Filename contains trailing spaces." now. Feel free to suggest a longer message. "... which is not supported well on Windows"?

**Comment by mcastroSG** [comment]
Hi hi:

Tested and working on Master branch.
