### ISSUE TITLE
An option to hide the system tray icon

### ISSUE THREAD

**Issue by almostearthling** [owncloud/client#4879]
It might be useful to have the option to disable the system tray icon under certain circumstances: for example, I recently discovered that the Nautilus integration module allows decoration icons on synchronized folders (which are available by default on Windows and presumably on Mac too), and if the user relies on this to know whether or not a synchronization was successful, the tray icon could even be considered somewhat redundant. Of course this is not something that everyone would choose, so I think that it should have to be sort of a "power setting", not available in the configuration dialog box: having the possibility to disable the icon in the configuration dialog could lead to the unexpected disappearance of the only entry point to the UI in case of a mistakenly checked (or unchecked) option, and this could confuse end users. However, if the option were available through the configuration file, the user could only *knowingly* hide the icon and would also probably know how to roll back to the normal behavior.

I tried to sketch a possible (oversimplistic, and maybe completely buggy due to my ignorance regarding QT) implementation in [very few lines of code](https://github.com/owncloud/client/compare/master...almostearthling:master), but couldn't even try to compile it because the requirements are not met:

```
franz@bob-plant:~/.../client$ sudo apt-get build-dep owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages have unmet dependencies:
 libocsync-dev : Depends: libocsync0 (= 0.91.4-1) but it is not going to be installed
```

(on Ubuntu `libowncloudsync0` is provided instead of `libocsync0`).

Although I actually ended up thinking that this would be an interesting feature because of issue #4828, it might result useful in other cases too, for instance with users that prefer a less cluttered interface.

**Comment by danimo** [comment]
We are considering to split off the syncing part of owncloud into a daemon (see #2002). If that is done, the systray becomes optional. Right now, this is technically not possible, since the nautilus integration lacks important settings (as you say). Also, we want to keep this understandable for average users.
