### ISSUE TITLE
[Qt4] Qt error when building client from Git

### ISSUE THREAD

**Issue by simopal6** [owncloud/client#4881]
### Expected behaviour
I clone the client git repository, run `cmake`, run `make`, and the client binary is built.

### Actual behaviour
Running `cmake` goes fine, although it warns me that "If possible compile me with Qt 5.4 or higher", and I have Qt 4.8.7.
Running `make` complains about `QStringList::sort(Qt::CaseSensitivity)`, of which apparently my compiler knows only the 0-argument version. Maybe the requested version of the function was introduced in Qt5?

### Steps to reproduce
1. Clone the client git repository.
2. Run `cmake`.
3. Run `make`.

### Client configuration
Client version: commit 567fe87e98f19cdce6b9398ece8b6b56a02920d3

Operating system: Slackware 14.1, Linux 3.10.17

OS language: English

Installation path of client: none

### Logs
 
Error encountered by `make`:

```
[ 24%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/utility.cpp.o
/usr/src/owncloud-client-latest/src/libsync/utility.cpp: In function ‘void OCC::Utility::sortFilenames(QStringList&)’:
/usr/src/owncloud-client-latest/src/libsync/utility.cpp:556:39: error: no matching function for call to ‘QStringList::sort(Qt::CaseSensitivity)’
     fileNames.sort(Qt::CaseInsensitive);
                                       ^
/usr/src/owncloud-client-latest/src/libsync/utility.cpp:556:39: note: candidate is:
In file included from /usr/lib64/qt/include/QtCore/qdir.h:47:0,
                 from /usr/lib64/qt/include/QtCore/QDir:1,
                 from /usr/src/owncloud-client-latest/src/libsync/utility.cpp:24:
/usr/lib64/qt/include/QtCore/qstringlist.h:152:13: note: void QStringList::sort()
 inline void QStringList::sort()
             ^
/usr/lib64/qt/include/QtCore/qstringlist.h:152:13: note:   candidate expects 0 arguments, 1 provided
make[2]: *** [src/libsync/CMakeFiles/owncloudsync.dir/utility.cpp.o] Error 1
make[1]: *** [src/libsync/CMakeFiles/owncloudsync.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by guruz** [comment]
Can you compile the 2.2 branch?

**Comment by simopal6** [comment]
Apparently the working version I'm running now, which I compiled is 2.3.0. Here is the content of the "About" section in the client:

> **Version 2.3.0git**. For more information visit owncloud.com
> By Klaas Freitag, Daniel Molkentin, Jan-Christoph Borchardt, Olivier Goffart, Markus Götz and others.
> Copyright ownCloud, Inc.
> Licensed under the GNU General Public License (GPL) Version 2.0
> ownCloud and the ownCloud Logo are registered trademarks of ownCloud, Inc. in the United States, other countries, or both.
> **Built from Git revision 5479aa on Apr 29 2016, 16:48:59 using Qt 4.8.7**, OpenSSL 1.0.1s 1 Mar 2016

**Comment by simopal6** [comment]
Just to be sure, I downloaded the stable 2.2 client source (https://download.owncloud.com/desktop/stable/owncloudclient-2.2.0.tar.xz), and it compiles fine.

**Comment by guruz** [comment]
@simopal6 Please don't use 2.2.0, it has a known memory leak.
```git checkout 2.2```
Switch your git to the 2.2 branch (which will become 2.2.1).

**Comment by simopal6** [comment]
Mh ok, but what about the compilation problem?

**Comment by guruz** [comment]
@simopal6 Switch to 2.2 branch and compile with Qt 5.x

**Comment by simopal6** [comment]
Thanks, so I do need Qt5 to compile? Then cmake should complain about me not having it.
