### ISSUE TITLE
OwnCloud Client 2.22.0.6076 for Windows crashes sometimes (at Windows 10)

### ISSUE THREAD

**Issue by likov** [owncloud/client#4883]
I have a fresh installed OwnCloud server appliance and a couple of Windows 10 PCs with clients.

After I've placed my photoalbums (~15000 files, ~50Gb) into the ownCloud folder, the Client is started crashing. 

After a day of struggling, I've downgraded clients to ver.2.1.1.5837 and it still works well and, surprisingly, much faster.

Steps to reproduce
1. Install ownCloud-2.2.0.6076-setup.exe
2. Point it to the folder with thousands of files
3. Wait for an hour approx.

OwnCloud Appliance (ESXi 5): Turnkey Linux Owncloud 14.1 amd64 / 3Gb / 1Tb of disk space

Debian 8.4
Apache/2.4.10 (Debian)
PHP 5.6.20-0+deb8u1 (cli) (built: Apr 27 2016 11:26:05)
mysql  Ver 14.14 Distrib 5.5.49
owncloud 'version' => '7.0.4.2'

Piece of log from the server:

Warning 	core 	Login failed: 'admin' (Remote IP: '109.172.15.15', X-Forwarded-For: '') 	2016-05-21T11:43:36+00:00
Fatal 	webdav 	Sabre\DAV\Exception\BadRequest: expected filesize 2918109 got 589824 	2016-05-21T11:06:08+00:00
Fatal 	webdav 	Sabre\DAV\Exception\BadRequest: expected filesize 2899112 got 868352 	2016-05-21T11:06:08+00:00
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 2871859 got 393216	2016-05-21T11:06:08+00:00
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 2878359 got 2195456	2016-05-21T11:06:08+00:00
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 669121 got 0	2016-05-21T09:33:59+00:00
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 2039826 got 1245184	2016-05-21T09:33:55+00:00
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 2210727 got 1409024	2016-05-21T09:33:55+00:00
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 2059650 got 720896	2016-05-21T09:33:55+00:00
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 1941496 got 1228800	2016-05-21T09:33:55+00:00
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 2277829 got 0	2016-05-21T09:33:55+00:00
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 2205918 got 2129920	2016-05-21T09:33:55+00:00
Fatal	webdav	Sabre\DAV\Exception\BadRequest: expected filesize 2098859 got 1392640	2016-05-20T17:24:29+00:00

**Comment by guruz** [comment]
There's two things to do this:
1. Client wise, please try a nightly build which has a memory fix: http://download.owncloud.com/desktop/daily/ownCloud-2.2.1.6107-nightly20160523-setup.exe
2. About the ```expected filesize x got y``` (y > 0) problem: If the client fix does not prevent this by not aborting the upload, possibly @PVince81 has an idea.

**Comment by guruz** [comment]
@likov Did you try the nightly build mentioned above?

**Comment by guruz** [comment]
@likov Did you try with a 2.2.1rc1?

**Comment by guruz** [comment]
@likov Did you have a chance to test the nightly build?
http://download.owncloud.com/desktop/daily/ownCloud-2.2.1.6135-nightly20160603-setup.exe

**Comment by likov** [comment]
hello! i was offline. will test it now.

**Comment by likov** [comment]
i am testing it on an overpopulated folder with a lots of small files (my php dev home). right now ownCloud client has synced 10000 files and still working well. it seems the bug is terminated. thank you!

**Comment by guruz** [comment]
Great :)
