### ISSUE TITLE
[OSX] client 2.2.0 excessive use of CPU

### ISSUE THREAD

**Issue by ovirtanen** [owncloud/client#4887]
### Expected behaviour
Repeated changes in a few kB text file does not eat up a single core for 2-10 s.

### Actual behaviour
After saving a file sync client to starts to check for changes in seemingly unrelated directories (as seen in sync activity) and the CPU utilization jumps up (close to 100% for a single core) for several seconds. Removing and reconfiguring the sync connection or a fresh install removes this problem for a short while but then it comes back. During the initial sync after reestablishing the sync connection the client scans for differences at local machine and server but the CPU utilization stays low (few percent).

### Steps to reproduce
1. Install sync client 2.2.0
2. Sync a folder with many subdirectories and files
3. Do changes to small files in rapid manner (modify - save, modify - save .. ) few times.

### Server configuration
Operating system: Debian Jessie

Web server: Apache 2.4.

Database: MySQL 5.5.

PHP version: 7.0.6.

ownCloud version: 9.0.2

### Client configuration
Client version: 2.2.0

Operating system: OS X 10.11.5.

OS language: Finnish

Installation path of client: /Applications

**Comment by guruz** [comment]
Is this improved with a recent nightly build?
http://download.owncloud.com/desktop/daily/ownCloud-2.2.1.3387-nightly20160522.pkg

**Comment by ovirtanen** [comment]
Yes, looks like the CPU utilization is lower in the nightly. 

On my machine the same operation as above takes now about 30% of a single core for 2-3 s.

**Comment by guruz** [comment]
Thanks!

FYI @ogoffart

**Comment by ovirtanen** [comment]
@guruz We celebrated too soon; after using the nightly build for a day, the performance problem is back. Any synchronization activity takes up 100% of a single core for several seconds.

**Comment by guruz** [comment]
Hm, sounds like a duplicate of https://github.com/owncloud/client/issues/2297 then.

FYI @dragotin @ckamm
