### ISSUE TITLE
Way to disable/tune "Download would reduce free disk space below X"

### ISSUE THREAD

**Issue by Nowaker** [owncloud/client#4889]
![screenshot_20160522_224228](https://cloud.githubusercontent.com/assets/611746/15459784/932051d4-206e-11e6-9a20-b521920a4d1e.png)

This is annoying due to the fact I'm always running low on space and I **want** owncloud to download whatever there is to be downloaded. So either let me disable this altogether or specify the threshold below which owncloud won't download anything.

Client version 2.2.0.

**Comment by ckamm** [comment]
@Nowaker You can tweak it with environment variables, check out https://doc.owncloud.org/desktop/2.2/advancedusage.html#low-disk-space .

**Comment by Nowaker** [comment]
@ckamm Why not expose it in the UI?

**Comment by ckamm** [comment]
@Nowaker I'd be fine with it being exposed in the UI, but am not going to do it myself. Patches are very welcome, as usual. :)
