### ISSUE TITLE
[2.2.0] Client is not showing available space on server

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#4890]
### Expected behaviour
Client should display totaly available space on server (Ex. 4,3GB of 34 GB used )

### Actual behaviour
Client only says 4,3 GB used

### Steps to reproduce
1. Open Client

### Server configuration
Operating system: Debian 8.4 64 Bit
Web server: Apache 2
Database: Mysql
ownCloud version: 9.0
Storage backend: 40Gb SSD

### Client configuration
Client version: 2.2.0 Stable
Operating system: Windows 7 64 Bit
OS language: German

### Screenshot
![2016-05-23 08_53_58-owncloud](https://cloud.githubusercontent.com/assets/2804301/15462667/85274424-20c4-11e6-936a-761038b2bc3b.png)

What can be the reason? Output on server:
```
[~] # ll /var/
...
lrwxrwxrwx  1 root root    28 Mai 11  2015 www -> /mnt/usbdrive/rootfs/var/www

[~] # df -h /var/www
Dateisystem    Größe Benutzt Verf. Verw% Eingehängt auf
/dev/sdc1        37G     15G   21G   41% /mnt/SSDSA2CT040G3

´´´

**Comment by danimo** [comment]
We now only show the total size if a quota was really set. Seeing the remaining disk space was confusing to users of ownCloud hosting providers, especially those who subscribed to "unlimited" plans or those where provider over-provisioned their disks. See https://github.com/owncloud/client/issues/3940 for details. Do you use quotas? If not, please close.

**Comment by MegaV0lt** [comment]
No i do not use quota. Would it be possible to make it an option in the client to show free space on server?

**Comment by danimo** [comment]
No, the server no longer report total values for unquota'ed accounts. Anyway, that's what server monitoring tools are for.
