### ISSUE TITLE
OC-client release > 1.7.0 for RHEL6 (CentOS6/SL6/..  32bits) to sync with OCserver release > 8.0

### ISSUE THREAD

**Issue by domcars0** [owncloud/client#4892]
Hi,
As described on this page : https://doc.owncloud.org/server/8.1/adm ... notes.html
"Due to various technical issues, by default desktop sync clients older than 1.7 are not allowed to connect and sync with the ownCloud server" release > 8.0 .
I've updated my server to the 8.1 release but have some RHEL6 (CentoS6/SL6) 32bits clients which are running the owncloud-client release 1.6.3-20.1. It looks like there is nor more update for the RHEL6 32bits oc-client on the opensuse repo (http://download.opensuse.org/repositori ... HEL_6/i686)??

Is there any alternative repo where I can find oc-client recent release for RHEL6 32bits?

Thanks for your help.

**Comment by danimo** [comment]
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/CentOS_6/i686/ has 2.2.0.

**Comment by domcars0** [comment]
Thank you very much!
(and sorry for not checked the CenTOS repo :-( )
