### ISSUE TITLE
Sync not working for files changed through webdav

### ISSUE THREAD

**Issue by Aesculapius** [owncloud/client#4893]
### Expected behaviour

During the day I'm using my owncloud account at work, by mapping the root folder using webdav. This - kinda - works (security restrictions seem strict at my work so every once in a while it cannot connect). But overall I can browse through files as if they were local. I can add files and create folders.

I'd expect the files to be in perfect sync so when I'm heading home I should be able to continue working on those files.
### Actual behaviour

Some of the files which were added or update through webdav, are not synced to the workstation at home (using win10 and sync client 2.2.0 build 6067). I can then force a sync by just creating an empty directory in that folder, and then everything is being corrected for that folder. But that's cumbersome as I don't know exactly when to do this.
### Steps to reproduce
1. Create a file through a mapped webdav share (windows 7)
2. Look at the client for this file (windows 10)
3. Force the sync client to sync changes by creating a new folder inside the specific directory.
### Server configuration

Operating system: Ubuntu 14.04.3 LTS

Web server: Apache 2.4.7

Database: MySQL 5.0.12

PHP version: 7.0.1

ownCloud version: 9.0.2

Storage backend: Local ZFS file share
### Client configuration

Client version: 2.2.0

Operating system: Windows 10

OS language: English

Installation path of client: C:\Program Files (x86)\ownCloud
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   doesn't create log.txt after this command?
2. Web server error log:no errors
3. ownCloud log (data/owncloud.log):

**Comment by danimo** [comment]
This looks like a server issue. @PVince81 pls.

**Comment by PVince81** [comment]
@Aesculapius can you reopen this ticket in the https://github.com/owncloud/core repo ?

Also add the following information:
- web server access log from the time where the files were created/modified through the Windows 7 mount (likely a bunch of PUT statements)

To test further, you could try the following with the CLI tool "cadaver":
1. Start `cadaver` for your ownCloud server
1. `set namespace DAV:`
1. `propget . getetag`, write down the etag value
1. Then upload a single file with your Win7 client
1. `propget . getetag`, compare the value with the previous one

After uploading a file, the etag value must change.
You should also check whether the etag of the parent directories of that file changed.
So if you uploaded a file into "/some/folder" on ownCloud, do these before and after the upload:
- `propget some/folder getetag`
- `propget some getetag`
- `propget . getetag`

After the upload, the etag of all of these must have changed for the sync client to be able to find the change.

If the etag did not change, then there's a bug in the server.

**Comment by Aesculapius** [comment]
will do.

**Comment by guruz** [comment]
Can this be closed?

**Comment by ogoffart** [comment]
Closing this old issue.
