### ISSUE TITLE
Bogus downgrade error message

### ISSUE THREAD

**Issue by APTX** [owncloud/client#4894]
### Expected behaviour
ownCloud should load as usual

### Actual behaviour
The following error is shown:
Downgrading is not supported and is likely to cause unpredictable issues (from 9.0.2.2 to 9.0.1.3)
Downgrading is not supported and is likely to cause unpredictable issues (from 9.0.2.2 to 9.0.1.3)

### Steps to reproduce
1. I do not know how to reproduce this issue

### Server configuration
Operating system: Gentoo Linux
Web server: Nginx (php-fpm)
Database:Postgresql
PHP version: 7.0.6
ownCloud version: 9.0.2
Storage backend: local filesystem only

### Client configuration
Client version: Latest Firefox on windows

ownCloud updated successfully to 9.0.2 and worked for a few days.
I tried a different browser and it does not display the error message. ownCloud code verification passes.

**Comment by danimo** [comment]
This is the bug tracker for the ownCloud Desktop Client. Please report issues with the server to https://github.com/owncloud/core/issues.

**Comment by APTX** [comment]
Yes, I'm sorry I wasn't aware there are multiple bug trackers for ownCloud. I created a new report: https://github.com/owncloud/core/issues/24793
