### ISSUE TITLE
[Packaging][Upgrade] [Linux] 2.1.1 client does not start

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4895]
### Expected behaviour
After install client from this repo that has been created to test upgrade process [2.1.1 Repo](https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adesktop%3Aclient-2.1.1&package=owncloud-client),  Desktop Client should work fine on any OS.

### Actual behaviour
2.1.1 Desktop Client shows error on start due to `owncloud: symbol lookup error: /usr/lib64/libowncloudsync.so.0: undefined symbol: _ZN9QKeychain15ReadPasswordJob6setKeyERK7QString`

### Steps to reproduce
1.  Install 2.1.1 Desktop Client

### Client configuration

Client OS: OpenSuseLeap42
ClientVersion: 2.1.1

**Comment by danimo** [comment]
@mcastroSG make sure you don't have a newer version of qtkeychain in your repositories. Also make sure all installed versions are removed. Downgrading the client will not downgrade qtkeychain.

**Comment by jnweiger** [comment]
Same issue seen here on a Ubuntu 14.04 where several keychain versions accumulated over time:

<pre>
dpkg -l | grep keychain
ii  libqt5keychain0                                             0.5-4.1                                             amd64        Cross platform password store library
ii  libqtkeychain0                                              0.6.2-1.1                                           amd64        Cross platform password store library
ii  qt5keychain-dev                                             0.5-4.1                                             amd64        Cross platform password store library (development files)
</pre>

**Comment by mcastroSG** [comment]
@jnweiger @danimo  tk a lot!!
