### ISSUE TITLE
INotify search fails if library is called libinotifytools.so

### ISSUE THREAD

**Issue by simopal6** [owncloud/client#4896]
### Expected behaviour
On my system, Slackware 14.1, the .so file for the inotify library is called libinotifytools.so. I would expect that when running cmake, it is able to detect that I have inotify installed.

### Actual behaviour
cmake doesn't find inotify. I fixed the problem by modifying the `cmake/modules/FindINotify.cmake` and changing `find_library(INOTIFY_LIBRARY inotify PATH_SUFFIXES lib/inotify)` to `find_library(INOTIFY_LIBRARY inotifytools PATH_SUFFIXES lib/inotify)`.

### Steps to reproduce
1. If you don't have a libinotify.so library, try and compile a client (I tried with 2.2 branch from git).

### Client configuration
Client version: git 2.2 branch

Operating system: Linux Slackware 14.1

**Comment by danimo** [comment]
`libnotifytools` is different from the inotify interface/library, which is provided by glibc. It may be a good idea to use it, but as long as we don't, we should require inotify directly. Makesure that you have the glibc development headers in place.

**Comment by simopal6** [comment]
Ok, got it, thanks. I thought they were the same thing with different names. Anyway, FWIW, `libinotifytool` is working fine here.
