### ISSUE TITLE
Bandwidth Limiting settings disabled 

### ISSUE THREAD

**Issue by TheBudda** [owncloud/client#4899]
[owncloud.log.zip](https://github.com/owncloud/client/files/280060/owncloud.log.zip)

### Expected behaviour: 
Tell us what should happen Bandwidth Limiting settings window should not be greyed out (see screenshot)

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. Install owncloud-client on Debian Jessie 8.4
2. 
3. 

### Server configuration
Operating system: Debian Jessie 8.4

Web server: Apache/2.4.10 (Debian)

Database: libmysql - 5.5.49

PHP version: 5.6.20-0+deb8u1

ownCloud version: 9.0.2 (stable)
![bandwidth limiting](https://cloud.githubusercontent.com/assets/16983376/15513287/dfb07a9c-21db-11e6-8068-9360f769fc0b.png)
![bandwidth limiting](https://cloud.githubusercontent.com/assets/16983376/15513304/ea56136c-21db-11e6-8aa2-114a43d6114e.png)

Storage backend:

### Client configuration
Client version:

Operating system: Debian Jessie 8.4

OS language: English

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/1.8/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
Dup of https://github.com/owncloud/client/issues/4334
Debian is shipping an old Qt version.
