### ISSUE TITLE
Client, Account Pause - Design Question

### ISSUE THREAD

**Issue by felixboehm** [owncloud/client#4906]
After pausing accounts, I still can see PROPFINDs going out to the server. (via mitmproxy)
- Is this as designed / intended? 
- I found lots of issues regarding "pause" and those requests might be necessary, then I would like to understand what exactly these requests are used for.
- My user expectation on pressing pause is, and it might make sense to also provide the possibility, to completely shutdown an account (without deleting it).

Answers, after we sorted out, would perfectly fit into documentation.

**Comment by danimo** [comment]
If it's a Propfind to '/', this works as expected. See

https://github.com/owncloud/client/blob/master/src/libsync/connectionvalidator.cpp#L173-L181.

What exactly would you like to see documented?

**Comment by guruz** [comment]
@felixboehm Do you still see them if you click 'logout'?
