### ISSUE TITLE
 delete files from owncloud

### ISSUE THREAD

**Issue by Marvo2011** [owncloud/client#4909]
### Expected behaviour
The system should delete a simple file.

### Actual behaviour
OwnCloud client asks whether to delete all because the sync folder has modified.

### Steps to reproduce
1. Upload a file to owncloud (with sync client or webinterface)
2. Delete a file from owncloud (with sync client or webinterface [same issue])

### Server configuration
Operating system: Debian Jessie (8)

Web server: Apache 2.2

Database: MySQL

PHP version: 7.0

ownCloud version: 9.0.2

### Client configuration
Client version: 2.2.0 (build 3358) 
Same issue at:  2.2.1-nightly20160526 (build 3396)

Operating system: OS X 10.11.2

OS language: German

Installation path of client: ~/Applications/owncloud.app

### Logs

ownCloud Client Log: https://gist.github.com/Marvo2011/529614e1b190d8d90cf02e68571f68f2

**Comment by danimo** [comment]
The ownCloud client will ask if all files have been removed, even if it is only one file. This is a safeguard against server misconfiguration and exists intentionally. It will not generally occur on any delete, just if the filecount suddenly drops to zero.

**Comment by Marvo2011** [comment]
Oh thank you. I will test it with several files.
