### ISSUE TITLE
client ui does not show on CentOS7 (XcbConnection: XCB error: 3 (BadWindow))

### ISSUE THREAD

**Issue by erikm87** [owncloud/client#4912]
### Expected behaviour
Expected to see the ownCloud client graphical interface.

### Actual behaviour
ownCloud graphical interface does not start. Nothing happens, seems to hang.

### Steps to reproduce
1. Install CentOS7 default installation with GNOME
2. Install ownCloud client with yum
3. Try to start ownCloud 

### Server configuration
Operating system: 
CentOS Linux release 7.2.1511 (Core)

ownCloud version:
[root@server yum.repos.d]# rpm -qa | grep owncloud
owncloud-files-9.0.2-2.1.noarch
owncloud-deps-php5-9.0.2-2.1.noarch
owncloud-9.0.2-2.1.noarch

### Client configuration
Client version: owncloud-client 2.2.0-9.1
Operating system: CentOS Linux release 7.2.1511 (Core)
OS language: English
Installation path of client: /opt/qt-5.4/bin/owncloud (/usr/bin/owncloud)

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

[root@server ~]# cat /home/admin/log.txt
05-27 16:07:08:987 0xf250a0 OCC::Application::setupLogging: "################## ownCloud en_US () 2.2.0"
05-27 16:07:08:987 0xf250a0 OCC::Application::setupTranslations: void OCC::Application::setupTranslations() Using "en_US" translation
05-27 16:07:09:025 0xf250a0 OCC::SocketApi::SocketApi: SocketApi:  server started, listening at  "/run/user/1000/ownCloud/socket"
05-27 16:07:09:025 0xf250a0 OCC::FolderMan::FolderMan: setting remote poll timer interval to 30000 msec
05-27 16:07:09:025 0xf250a0 OCC::AccountManager::restoreFromLegacySettings: Migrate: checking old config  "/home/admin/.local/share/data/ownCloud/owncloud.cfg"
05-27 16:07:09:025 0xf250a0 OCC::FolderMan::setupFoldersMigration: * Setup folders from  "/home/admin/.local/share/data//ownCloud/folders" (migration)
05-27 16:07:09:037 0xf250a0 OCC::ClientProxy::setupQtProxyFromConfig: Set proxy configuration to use system configuration
05-27 16:07:09:808 0xf250a0 OCC::ActivitySettings::setNotificationRefreshInterval: Starting Notification refresh timer with  300  sec interval
05-27 16:07:09:851 0xf250a0 OCC::Updater::getSystemInfo: Sys Info size:  0
05-27 16:07:09:851 0xf250a0 unknown: QIODevice::read: device not open
05-27 16:07:10:549 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 221, resource id: 25165828, major code: 2 (ChangeWindowAttributes), minor code: 0
05-27 16:07:10:549 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 222, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:549 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 223, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:549 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 224, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:549 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 226, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:549 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 227, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:549 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 228, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 232, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 236, resource id: 25165828, major code: 2 (ChangeWindowAttributes), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 237, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 238, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 239, resource id: 25165828, major code: 20 (GetProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 242, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 243, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 244, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 245, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 249, resource id: 25165828, major code: 2 (ChangeWindowAttributes), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 250, resource id: 25165828, major code: 2 (ChangeWindowAttributes), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 251, resource id: 25165828, major code: 20 (GetProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 252, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 253, resource id: 25165828, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 254, resource id: 25165828, major code: 20 (GetProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 255, resource id: 25165828, major code: 19 (DeleteProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 256, resource id: 25165828, major code: 19 (DeleteProperty), minor code: 0
05-27 16:07:10:550 0xf250a0 OCC::ownCloudGui::slotOpenSettingsDialog: No configured folders yet, starting setup wizard
05-27 16:07:10:639 0xf250a0 unknown: QIODevice::read: device not open
05-27 16:07:10:641 0xf250a0 OCC::OwncloudWizard::slotCurrentPageChanged: Current Wizard page changed to  0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 259, resource id: 25165834, major code: 2 (ChangeWindowAttributes), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 260, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 261, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 262, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 264, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 265, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 266, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 267, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 271, resource id: 25165834, major code: 2 (ChangeWindowAttributes), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 272, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 273, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 274, resource id: 25165834, major code: 20 (GetProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 277, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 278, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 279, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 280, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 281, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 282, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 283, resource id: 25165834, major code: 12 (ConfigureWindow), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 284, resource id: 25165834, major code: 2 (ChangeWindowAttributes), minor code: 0
05-27 16:07:10:656 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 285, resource id: 25165834, major code: 2 (ChangeWindowAttributes), minor code: 0
05-27 16:07:10:657 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 286, resource id: 25165834, major code: 20 (GetProperty), minor code: 0
05-27 16:07:10:657 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 287, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:657 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 288, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:657 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 289, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:657 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 290, resource id: 25165834, major code: 20 (GetProperty), minor code: 0
05-27 16:07:10:657 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 291, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:657 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 292, resource id: 25165834, major code: 18 (ChangeProperty), minor code: 0
05-27 16:07:10:657 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 293, resource id: 25165834, major code: 8 (MapWindow), minor code: 0
05-27 16:07:10:657 0xf250a0 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 295, resource id: 25165834, major code: 12 (ConfigureWindow), minor code: 0
05-27 16:07:13:746 0xf250a0 OCC::PassiveUpdateNotifier::backgroundCheckForUpdate: virtual void OCC::PassiveUpdateNotifier::backgroundCheckForUpdate()
05-27 16:07:13:746 0xf250a0 OCC::OCUpdater::backgroundCheckForUpdate: virtual void OCC::OCUpdater::backgroundCheckForUpdate() checking for available update
05-27 16:07:14:286 0xf250a0 OCC::PassiveUpdateNotifier::versionInfoArrived: Client is on latest version!

2. Installation of owncloud client:

Installed:
  owncloud-client.x86_64 0:2.2.0-9.1

Dependency Installed:
  compat-libxcb.x86_64 0:1.9-1.el7                libowncloudsync0.x86_64 0:2.2.0-9.1        mesa-libGLES.x86_64 0:10.6.5-3.20150824.el7        opt-libqt5keychain0.x86_64 0:0.6.2-1.1        opt-qt5-qtbase.x86_64 0:5.4.2-4.2
  opt-qt5-qtbase-gui.x86_64 0:5.4.2-4.2           opt-qt5-qtwebkit.x86_64 0:5.4.2-2.4        owncloud-client-l10n.x86_64 0:2.2.0-9.1            xcb-util-image.x86_64 0:0.4.0-2.el7           xcb-util-keysyms.x86_64 0:0.4.0-1.el7
  xcb-util-renderutil.x86_64 0:0.3.9-3.el7        xcb-util-wm.x86_64 0:0.4.1-5.el7

Complete!

**Comment by mcastroSG** [comment]
@ckamm  on a fresh installed Centos 7 VM, i´m getting this error too. I´ve updated OS and tested with 2.2.0 and 2.1.1 nightly with the same result.

**Comment by danimo** [comment]
Do not start the client as root. That is not supported.

**Comment by mcastroSG** [comment]
Getting the same error executing with another user

**Comment by erikm87** [comment]
I tried to run the application as admin and an another non-root user.

**Comment by mcastroSG** [comment]
After bring some configuration from another installa on ubuntu no QIO errors appear at log file, just QXcbConnection errors remain.

**Comment by dragotin** [comment]
The client needs to be started by the same user who started the desktop environment for a valid test.

**Comment by mcastroSG** [comment]
I´ve tested starting as root or any other user, the same problem. Could be related to Qt current version on CentOs 5.4 ?

**Comment by guruz** [comment]
Have you tried looking in https://bugreports.qt.io/browse/QTBUG-40820?jql=text%20~%20%22QXcbConnection%22 ?

**Comment by mcastroSG** [comment]
@erikm87 try with nightly build, I´ve tested it and is working.

`cd /etc/yum.repos.d/`
`wget http://download.opensuse.org/repositories/isv:/ownCloud:/community:/nightly/CentOS_7/isv:ownCloud:desktop.repo`
`yum install owncloud-client`

**Comment by erikm87** [comment]
Thanks! It works.

**Comment by mcastroSG** [comment]
@erikm87 Thanks!! Closing

**Comment by xenithorb** [comment]
``` 
06-30 16:05:10:699 4263 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 487, resource id: 37748740, major code: 12 (ConfigureWindow), minor code: 0
```
Getting this on Fedora 24 now. 

qt5-qtbase-5.6.0-21.fc24.x86_64

Did not matter if I completely removed ~/.local/share/data/ownCloud 

(btw why data/owncloud? why not .config/owncloud or ... just why the extra data folder?)

**Comment by xenithorb** [comment]
Just in rawhide atm. I compiled a 2.2.2 build and all is well, and also poked the maintainer to upgrade to 2.2.2 as well.
