### ISSUE TITLE
[Windows 7] Freeze after shut-down from tray icon

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#4914]
### Expected behaviour
I close ownCloud from the tray icon's context menu. With the intention of going mobile with my laptop, I remove the LAN cable while doing so. ownCloud should just shut down normally now.

### Actual behaviour
Now, ownCloud seems to be stuck while trying to disconnect from the server. It freezes completely, which also freezes the Explorer extension. As a consequence, right-clicking any file freezes that particular Explorer window.

### Steps to reproduce
1. Close from context menu
2. Close internet connection while the tray icon is still visible
3. Notice how the icon remains visible and ownCloud does not shut down.

### Client configuration
Client version: 2.1.1

Operating system: Windows 7

OS language: German

Installation path of client: C:\Program Files (x86)\ownCloud

**Comment by guruz** [comment]
Could you try a nightly build of 2.2.1?
http://download.owncloud.com/desktop/daily/ownCloud-2.2.1.6123-nightly20160530-setup.exe

**Comment by sagamusix** [comment]
The problem persists in v2.2.1. Reproducing it is as simple as closing the client from the Tray Icon and removing the LAN cable while the tray icon is still visible.

**Comment by sagamusix** [comment]
Observing the issue further, it does not only happen when unplugging the ethernet cable too early, but also when closing ownCloud and staying connected. Sometimes, the client even crashes while shutting down. You should have received about three such automatic error reports in the last few days.

**Comment by sagamusix** [comment]
For what it's worth, this seems to no longer happen in 2.2.3-nightly, as far as I can tell.
