### ISSUE TITLE
Windows client crash

### ISSUE THREAD

**Issue by Mati24** [owncloud/client#4917]
Hi,

I use the Windows Client on a Windows Server 2012 R2 and it crashs every time after 2-3 minutes of synchronisation.
The last log entry if a PUTFileJob created but never on the same file.

Do you know where I can find the error ?

Thank you

**Comment by danimo** [comment]
@Mati24 Please provide us with details: which version.etc. We have a known mem leak in 2.2.0, which will be fixed through 2.2.1, a nightly build of which you can try at download.owncloud.com/download/nightly/.

**Comment by Mati24** [comment]
No crash anymore, thank you
