### ISSUE TITLE
There is no "Add folder" option

### ISSUE THREAD

**Issue by fenollp** [owncloud/client#4919]
### Expected behaviour
I should be able to sync multiple folders on my laptop to my owncloud account.
Maybe expected: showing a dialog as described in https://forum.owncloud.org/viewtopic.php?t=16817#p95706.

### Actual behaviour
Instead I only see [this](http://i.imgur.com/XE5ijET.png) which says `Adding a folder is disabled because you are already syncing all your files. If you want to sync multiple folders, please remove the currently configured root folder.`, also showing a disabled button `Add Folder Sync Connection`.

### Steps to reproduce
1. Fresh install of both [server](https://github.com/jchaney/owncloud#docker-compose-support) and [client](https://download.owncloud.com/desktop/stable/ownCloud-2.2.0.3358.pkg)
2. Create account on server, login on client, pick a folder in `~/Public/Owncld` to sync
3. In the client go to settings: leftmost tab.

### Server configuration
Operating system: debian 8

Web server: nginx

Database: MySQL

PHP version: 5

ownCloud version: 9.0.2

Storage backend: mysql

### Client configuration
Client version: 2.2.0

Operating system: OSX 10.11.5

OS language: EN-us

Installation path of client: /Applications/owncloud.app

**Comment by fenollp** [comment]
Seems related to https://github.com/owncloud/client/issues/4381 but the replies there made no sense to me. That tooltip makes no sense too.

Could someone explain it to me?
I'm trying to mirror a couple folders from `~/`

**Comment by RealRancor** [comment]
@fenollp I think you can continue in #4381 as it makes no sense to keep two issues about the same question open.

**Comment by fenollp** [comment]
I believe it isn't the same issue.
I am reporting about missing `Add Folder…` option ([top left button here](https://cloud.githubusercontent.com/assets/621965/5501173/897fb452-8755-11e4-8efe-a88ab9cdb67d.png)).

This issue makes it impossible to sync ~/Desktop or ~/Documents.
I tried syncing my whole home folder to then pick only the folders I am interested in but the client crashes on me (too many files, not enough RAM I guess).

This is really weird as from what I read everywhere I am the only one not having that `Add Folder…` option!

**Comment by fenollp** [comment]
Maybe that's what happened? https://github.com/owncloud/client/issues/3756

**Comment by fenollp** [comment]
Okay from what I grep-ed on the repo & what I just tried I was stupid / victim of bad UX.

What I actually needed was the `Add Folder Sync Connection…` button.

**Comment by dragotin** [comment]
@fenollp now that you went through that: I agree that that is not the best UX. Do you have ideas or suggestions how we could solve this problem better? I'd be eager to hear your input. Thx.

**Comment by fenollp** [comment]
I liked the idea suggested elsewhere to merge the 2 wizard screens into one (the Select a local folder screen and the Select a distant folder screen).
BTW that local folder selection default to `/Applications`; I think defaulting to `~` would be better (on OSX at least).

I guess I was confused because I was looking for `Add Folder…` and thought `Add Folder Sync Connection…` was too special/advanced & didn't even consider clicking it. That or the button was disabled too…
Maybe replacing it with a big `+` button could help here?

The UI does not have the best looks.

The folder sync list may be too big in height: after adding 7 connections it gets difficult to list and find the synced folder I'm looking for.
For this I would suggest collapsed one-liners with just the state & folder name (or parent-folder+folder if multiple synced folders have the same name) and a search bar with a cmd+F shortcut.
