### ISSUE TITLE
[Windows] Extrem lag on my connexion when sync large files

### ISSUE THREAD

**Issue by Mati24** [owncloud/client#4920]
Hi,

When I sync my owncloud folder with large files or a lot of files, my internet connection become very slow, my ping to google goes from 20 ms to 900 and I lost about 10%.
I have the same problem on 2 Windows clients, 1 on the stable 2.2.0 (build 6076) and one on the last nightly build.

I see this issue https://github.com/owncloud/client/issues/4294 but I don't find the "bearer" directory.

Thanks

**Comment by danimo** [comment]
What kind of internet connection do you have? Did you try to enable "automatic bandwidth limiting?"

**Comment by Mati24** [comment]
Automatic is not better better, il I set 10 KB/s it seems to be good, but even at 30 KB/s I have lags.

**Comment by Mati24** [comment]
I try the stable 1.8.4 version (build 5267) and this is slightly better, ping is around 400 ms, I lost 2,3% of them. I my upload is on my max (190 KB/s).

**Comment by guruz** [comment]
Can you try the 2.2.1rc1 coming out today? Thanks.

**Comment by Mati24** [comment]
Hi, it works like the 1.8.4 : the upload speed is good, no crash, but my ping is about 400 ms. Thank you

**Comment by guruz** [comment]
@mat813 Any chance this is related to your internet connection instead of related to oC?

**Comment by Mati24** [comment]
When I try with hubiC, it uses the best of upload speed, and my ping is about 60 instead of 20.

**Comment by guruz** [comment]
Do you still have this issue with 2.2.3? :)

**Comment by Mati24** [comment]
Hi, I find the problem without OwnCloud when I upload, sorry it's not the
fault of OwnCloud

**Comment by guruz** [comment]
Great, thanks.
Do you want to describe it quickly? maybe it helps someone else..

**Comment by Mati24** [comment]
My Internet modem doesn't work as expected if I use all my bandwidth, I have to change it. Thank you
