### ISSUE TITLE
Owncloud client starts and completes a new sync after pausing sync

### ISSUE THREAD

**Issue by oneup40** [owncloud/client#4921]
### Expected behaviour

When a user right-clicks a folder sync connection in the client and clicks "Pause sync", no more syncing should occur until the user chooses to "Resume sync".
### Actual behaviour

When a user right-clicks a folder sync connection in the client and clicks "Pause sync", the client changes to show a "paused" icon, but continues to sync when files are updated.
### Steps to reproduce
1. Open Owncloud client
2. Add a folder sync connection
3. Right-click the connection
4. Click "pause sync"
5. Change files locally
6. Switch back to Owncloud client window
7. Observe client continuing to sync
### Server configuration

Operating system: Linux

Web server: Nginx

Database: mysql

PHP version: 7.0.6

ownCloud version: 9.0.2

Storage backend: ? default
### Client configuration

Client version: 2.1.1 build 5837 git revision eeec89 Feb 9 2016, 15:14:47 using Qt 5.4.0, OpenSSL 1.0.2f 28 Jan 2016

Operating system: Windows

OS language: English

Installation path of client: C:\Program Files (x86)\ownCloud
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   (On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
   (See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

Command opened Owncloud general settings tab, no log visible.
1. Web server error log:

No errors reported.
1. ownCloud log (data/owncloud.log):

No "data" directory in the Owncloud client install directory.

![image](https://cloud.githubusercontent.com/assets/7097256/15637915/5046e772-25e8-11e6-829c-ad513d78f009.png)

![image](https://cloud.githubusercontent.com/assets/7097256/15637918/570a4cde-25e8-11e6-87e9-18f7ccf1aedc.png)

**Comment by oneup40** [comment]
This appears to have been a bug for over 6 months now, see #4248

**Comment by ckamm** [comment]
@oneup40 I can't reproduce the problem unfortunately. When you followed your steps, was the paused folder shown as non-syncing for some time and then started to sync anew?

**Comment by Epithumia** [comment]
I noticed the same issue on OSX with the 2.2.2 client (server: 8.2.3). While the client is syncing, I'll hit pause (either in the account's "..."-> pause or from the oc menu to pause all), and after a few seconds, the client will launch a discover phase of the remote folders, then resume the sync, ignoring the paused state.

**Comment by oneup40** [comment]
@ckamm IIRC it never showed as non-syncing, but it was in the middle of syncing recently changed files when I attempted to pause it but it kept going.

**Comment by SamuAlfageme** [comment]
I think this might have been solved by https://github.com/owncloud/client/issues/5290

**Comment by hodyroff** [comment]
@oneup40 please check with 2.3
