### ISSUE TITLE
2.2.0 client not availalable for 32-bit Ubuntu_16.04

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#4924]
### Expected behaviour
2.2.0 client should be availalable for 32-bit Ubuntu_16.04

### Actual behaviour
2.2.0 client is missing in http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/i386/

### Steps to reproduce
1. check http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/i386/

@jnweiger Can this be added? /cc @cmonteroluque 

00005551

**Comment by jnweiger** [comment]
Build succeeds at https://build.opensuse.org/package/live_build_log/home:jnweiger:ownCloud/owncloud-client/Ubuntu_16.04/i586

but the same still fails at https://build.opensuse.org/package/isv:ownCloud:desktop/owncloud-client/Ubuntu_16.04/i586 -- investigating.

**Comment by jnweiger** [comment]
Build success:
@Kawohl  https://build.opensuse.org/package/show/isv:ownCloud:community:testing/owncloud-client 
needs testing on Ubuntu_16.04 for both x86_64 and (if possible?) i386

**Comment by Kawohl** [comment]
Confirming:

Runs on x86_64

@michaelstingl 
can you confirm for i386?

**Comment by Kawohl** [comment]
confirmed and closed....

**Comment by michaelstingl** [comment]
> can you confirm for i386?

Yes, works very well!
