### ISSUE TITLE
Clean up Qt Patch set.

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#4925]
### Expected behaviour

The patches in the admin directory in git must match the patch set that is used for the windows and mac builds of Qt
### Actual behaviour

It's a mess ;-(

Check https://build.opensuse.org/project/show/isv:ownCloud:toolchains:mingw:win32:2.2 to find the actual patch set, which is the same as in the patches, but with different names. 

Most awesome would be a little script that
- analyzes the spec file about patches applied
- calc MD5 sums of the patches
- compare the sums with the patches in the admin dir (which might contain a file with a list of patches that need to be applied to windows and Mac respectively).
- Say "ok" if all is not a mess.

**Comment by dragotin** [comment]
@guruz FYI

**Comment by guruz** [comment]
We won't need most of the patches with the Qt 5.6 based build
https://github.com/owncloud/client/issues/3449

**Comment by guruz** [comment]
qtbase cleaned up by @dragotin at https://build.opensuse.org/package/show/isv:ownCloud:toolchains:mingw:win32:2.3/mingw32-libqt5-qtbase

FYI @dschmidt

**Comment by jturcotte** [comment]
The thing is that https://build.opensuse.org/project/show/isv:ownCloud:toolchains:mingw:win32:2.2 contains patches for MinGW cross-building. None of those patches are related to ownCloud and I think it should stay that way.

I've rebased all patches on top of 5.6 and all of them are macOS-specific, so the OBS list of patches is correctly not including any ownCloud patch. If we add new patches that should affect windows in admin/ we should then add them to OBS.

I'll close it as I think it's not as bad as it looks after the rebase.
