### ISSUE TITLE
[W10][Overlay]Overlay icon is not properly updated in case of sync files uploaded to the server

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4927]
### Expected behaviour
In case I upload a file to the server on browser, Desktop Client should show a proper overlay icon on that file once its synced.

### Actual behaviour
Once Desktop client has synced a file previously uploaded to the server, blue icon remains instead of green check.

### Steps to reproduce
1. On a fresh install set a new Shared sync folder
2. Wait till Desktop client ends sync
3. Use browser to upload a file to the folder synced
4. Wait till Desktop Client ends this new sync

Blue icon remains on uploaded file

### Server configuration
Server OS: Ubuntu
Server Version: 9.1.0 RC1

### Client configuration

ClientOS: W10. Unable to reproduce it for W81 or W7
Client Version: Versión 2.2.1-nightly20160531 (build 6128) also tested for v2.2.1-rc1 branch

**Comment by rperezb** [comment]
having in mind the timing and how critic this is, I'd suggest to move to the next version, how does it sound @mcastroSG ?

**Comment by mcastroSG** [comment]
Sure @danimo @dragotin @ogoffart , what do you think ¿?

**Comment by ogoffart** [comment]
The problem is that the file system watcher sees a change.

**Comment by guruz** [comment]
@ogoffart Did you see my commit yesterday for OS X?

I also remember @ckamm had implemented a grace period somewhere for "own changes" so they are not re-detected

**Comment by ogoffart** [comment]
The "own change" step is only working while the OwnCloudPropagator is still alive.  But apparently we get these notifications after that.  From the log i have:

```
06-03 09:45:49:780 0x375e8 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::Pr
opagatorJob&) "folder2/wait_il.cur" INSTRUCTION_NEW 4 ""
06-03 09:45:49:785 0x375e8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK+SWM:C:\Users\pepin\ownCloud\folder2\wait_il.c
[...]
06-03 09:45:49:824 0x375e8 OCC::SyncEngine::finalize: CSync run took  1026
06-03 09:45:49:825 0x375e8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:C:\Users\pepin\ownCloud\"
06-03 09:45:49:825 0x375e8 OCC::BandwidthManager::~BandwidthManager: virtual OCC::BandwidthManager::~BandwidthManager()
06-03 09:45:49:835 0x375e8 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("C:/Users/pepin/ownCloud/folder2/wait_il.cur")
06-03 09:45:49:836 0x375e8 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:SYNC:C:\Users\pepin\ownCloud\folder2\wait_il.cur
"
```

The filesystem watcher notifications happens 50 ms after the file was considered finished. 10ms after the propagator was destroyed.

 The change in macosx is irrelevant since this is about windows 10.


Maybe a solution would be to check the DB to know if the mtime is actually different

**Comment by mcastroSG** [comment]
It´s working fine with 2.2.1-nightly20160603 (build 6138)

**Comment by ckamm** [comment]
@ogoffart I think in addition we should do the 'own changes' tracking in the Folder or SyncEngine to avoid losing the data when the sync ends.

**Comment by guruz** [comment]
Re-opening for re-evaluation by @ckamm

**Comment by ckamm** [comment]
Pull request: #4946
