### ISSUE TITLE
[Windows][Overlay] Overlay icon does not appear on favorites

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4931]
### Expected behaviour

In case my Shared sync folder is included on Favorites section on Windows Explorer , overlay icon should appear.

### Actual behaviour

There is no overlay icon on that folder at Favorites section. This issue is just for W81 and W7, for W10 it is working fine

### Steps to reproduce
1.  Add Shared sync folder to Favorites on Windows Explorer

### Server configuration

Server OS: Ubuntu
Server Version: 9.1.0 Beta1
### Client configuration

Client OS: W81/W7
Client Version:Version 2.2.1rc1 (build 6125)

**Comment by ogoffart** [comment]
Is it working with competition like dropbox or turtoiseSVN?   I would assume this is just not possible with older windows. That windows just don't show this icon.
Regardless, this is not a high severity issue.

**Comment by mcastroSG** [comment]
Tk for review
