### ISSUE TITLE
[2.2.1] Regressive tests

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4932]
[https://github.com/owncloud/client/wiki/Testing-Scenarios-2.2](https://github.com/owncloud/client/wiki/Testing-Scenarios-2.2)

## Test with new credential store on Windows

<br>
 
Test Case ID | Test case     | Steps   | Expected behaviour | Result | Related Comments
|:----:|:------------- |:-------------------|:-------------|:-------------:|:----------
1 | Test with new credential store on Windows - Update client | 1.- Update current installation from 2.2.0 to last version <br> 2.- Start Desktop Client | No credentials are required and start finish successfully | ✅ 

## Notifications

<br>
 
Test Case ID | Test case     | Steps   | Expected behaviour | Result | Related Comments
|:----:|:------------- |:-------------------|:-------------|:-------------:|:----------
1 | Notifications - Remote share | 1.- As user1 share a folder with user2 using federated sharing <br> | At desktop client connected as user2 a new notification is shown | ✅ 
2 | Notifications - Announcement | 1.- As admin enable Announcement Center App <br> 2.- As admin access to Announcements menu and write a new announcement.<br>| At any client desktop connected to this sever a new notification is shown. | ✅  | 

## Overlay Icons

OSX

<br>
 
Test Case ID | Test case     | Steps   | Expected behaviour | Result | Related Comments
|:----:|:------------- |:-------------------|:-------------|:-------------:|:----------
1 | Overlay Icons - First start | 1.- Install for the first time Owncloud Desktop Client | Green check overlay icons are shown at Shared sync folder  <br> | ✅ 
2 | Overlay Icons - Add new file | 1.- Add a new file to Shared sync folder <br> | Green check overlay icon are shown over this new file after sync process is completed <br> | ✅ 
3 | Overlay Icons - Add new folder | 1.- Add a new folder to Shared sync folder <br> | Green check overlay icon are shown over this new folder after sync process is completed <br> | ✅ 
4 | Overlay Icons - Blacklist file | 1.- Set at blacklist a new file as not shared <br> | A "Yellow Warning" is shown over that file <br> | :x: | Pending raise issue
5 | Overlay Icons - Disable blacklist file | 1.- Remove from blacklist a file <br> | "Green check" overlay icon is shown over the file <br> | :x:  | Pending raise issue
6 | Overlay Icons - Shared file enable | 1.- Share a file with a user  <br> | Overlay icon is updated with a "Shared" icon <br> | :soon: | Delayed to 2.3.0
7 | Overlay Icons - Shared folder enable | 1.- Share a folder with a user  <br> | Overlay icon is updated with a "Shared" icon <br> | :soon:  | Delayed to 2.3.0
8 | Overlay Icons - Shared file disable | 1.- Disable share a file with a user <br> | Overlay icon is updated with a "Green check" icon <br>  | :soon: | Delayed to 2.3.0
9 | Overlay Icons - Shared folder disable  | 1.- Disable share a folder with a user <br> | Overlay icon is updated with a "Green check" icon <br> | :soon: | Delayed to 2.3.0
10 | Overlay Icons - Warning  | 1.- Generate a warning i.e a folder that could not be synced <br> | Overlay icon is updated with a "Yellow warning" icon <br> | ✅
11 | Overlay Icons - Error  | 1.- Generate an error i.e exceed quota allowed <br> | Overlay icon is updated with a "Red error" icon <br> | ✅ |
12 | Overlay Icons - Solve warning  | 1.- Generate a warning i.e a folder that could not be synced <br> 2.- Solve the problem  <br>| Overlay icon is updated with a "Green check" icon <br> | ✅
13 | Overlay Icons - Solve error  | 1.- Generate an error i.e exceed quota allowed <br> 2.- Solve the problem  <br>| Overlay icon is updated with a "Green check" icon <br> | ✅
14 | Overlay Icons - Folder hierarchy warning  | 1.- Generate a warning i.e a folder that could not be synced <br> | Overlay icon at parent folder is a "Green check" <br>  |  ✅
15 | Overlay Icons - Folder hierarchy error  | 1.- Generate an error i.e exceed quota allowed <br> | Overlay icon at parent folder is "Yellow warning" icon <br> | ✅
16 | Overlay Icons - Syncing | 1.- Copy at least one hundred files and folders to Shared sync folder <br> | Overlay icon is updated with "Blue sync" icon until the process finish <br> | ✅
17 | Overlay Icons - Shared file with you | 1.- As user1 share with user2 a file <br> | As user2 the file shared should appear and a "green shared" overlay icon must appear | ✅ 
18 | Overlay Icons - Shared folder with you | 1.- As user1 share with user2 a folder <br> | As user2 the folder shared should appear and a "green shared" overlay icon must appear | ✅

## Overlay Icons

W

<br>
 
Test Case ID | Test case     | Steps   | Expected behaviour | Result | Related Comments
|:----:|:------------- |:-------------------|:-------------|:-------------:|:----------
1 | Overlay Icons - First start | 1.- Install for the first time Owncloud Desktop Client | Green check overlay icons are shown at Shared sync folder  <br> | :x: |  [4762#](https://github.com/owncloud/client/issues/4762)
2 | Overlay Icons - Add new file | 1.- Add a new file to Shared sync folder <br> | Green check overlay icon are shown over this new file after sync process is completed <br> |  ✅ 
3 | Overlay Icons - Add new folder | 1.- Add a new folder to Shared sync folder <br> | Green check overlay icon are shown over this new folder after sync process is completed <br> | ✅ 
4 | Overlay Icons - Blacklist file | 1.- Set at blacklist a new file as not shared <br> | A "Yellow Warning" is shown over that file <br> | :x: | Pending raise issue
5 | Overlay Icons - Disable blacklist file | 1.- Remove from blacklist a file <br> | "Green check" overlay icon is shown over the file <br> | :x:  | Pending raise issue
6 | Overlay Icons - Shared file enable | 1.- Share a file with a user  <br> | Overlay icon is updated with a "Shared" icon <br> | :soon: | Delayed to 2.3.0
7 | Overlay Icons - Shared folder enable | 1.- Share a folder with a user  <br> | Overlay icon is updated with a "Shared" icon <br> | 🔜   | Delayed to 2.3.0
8 | Overlay Icons - Shared file disable | 1.- Disable share a file with a user <br> | Overlay icon is updated with a "Green check" icon <br>  | 🔜   | Delayed to 2.3.0
9 | Overlay Icons - Shared folder disable  | 1.- Disable share a folder with a user <br> | Overlay icon is updated with a "Green check" icon <br> | 🔜  | Delayed to 2.3.0
10 | Overlay Icons - Warning  | 1.- Generate a warning i.e a folder that could not be synced <br> | Overlay icon is updated with a "Yellow warning" icon <br> | ✅
11 | Overlay Icons - Error  | 1.- Generate an error i.e exceed quota allowed <br> | Overlay icon is updated with a "Red error" icon <br> | ✅  | 
12 | Overlay Icons - Solve warning  | 1.- Generate a warning i.e a folder that could not be synced <br> 2.- Solve the problem  <br>| Overlay icon is updated with a "Green check" icon <br> | ✅
13 | Overlay Icons - Solve error  | 1.- Generate an error i.e exceed quota allowed <br> 2.- Solve the problem  <br>| Overlay icon is updated with a "Green check" icon <br> | ✅
14 | Overlay Icons - Folder hierarchy warning  | 1.- Generate a warning i.e a folder that could not be synced <br> | Overlay icon at parent folder is a "Green check" <br>  |  ✅
15 | Overlay Icons - Folder hierarchy error  | 1.- Generate an error i.e exceed quota allowed <br> | Overlay icon at parent folder is "Yellow warning" icon <br> | ✅
16 | Overlay Icons - Syncing | 1.- Copy at least one hundred files and folders to Shared sync folder <br> | Overlay icon is updated with "Blue sync" icon until the process finish <br> | ✅
17 | Overlay Icons - Shared file with you | 1.- As user1 share with user2 a file <br> | As user2 the file shared should appear and a "green shared" overlay icon must appear |  ✅
18 | Overlay Icons - Shared folder with you | 1.- As user1 share with user2 a folder <br> | As user2 the folder shared should appear and a "green shared" overlay icon must appear | ✅  |

## Overlay Icons

Linux

<br>
 
Test Case ID | Test case     | Steps   | Expected behaviour | Result | Related Comments
|:----:|:------------- |:-------------------|:-------------|:-------------:|:----------
1 | Overlay Icons - First start | 1.- Install for the first time Owncloud Desktop Client | Green check overlay icons are shown at Shared sync folder  <br> | ✅  | 
2 | Overlay Icons - Add new file | 1.- Add a new file to Shared sync folder <br> | Green check overlay icon are shown over this new file after sync process is completed <br> |  ✅ 
3 | Overlay Icons - Add new folder | 1.- Add a new folder to Shared sync folder <br> | Green check overlay icon are shown over this new folder after sync process is completed <br> | ✅ 
4 | Overlay Icons - Blacklist file | 1.- Set at blacklist a new file as not shared <br> | A "Yellow Warning" is shown over that file <br> | :x: | Pending raise issue
5 | Overlay Icons - Disable blacklist file | 1.- Remove from blacklist a file <br> | "Green check" overlay icon is shown over the file <br> | :x:  | Pending raise issue
6 | Overlay Icons - Shared file enable | 1.- Share a file with a user  <br> | Overlay icon is updated with a "Shared" icon <br> | 🔜 : | Delayed to 2.3.0
7 | Overlay Icons - Shared folder enable | 1.- Share a folder with a user  <br> | Overlay icon is updated with a "Shared" icon <br> | 🔜 :  | Delayed to 2.3.0
8 | Overlay Icons - Shared file disable | 1.- Disable share a file with a user <br> | Overlay icon is updated with a "Green check" icon <br>  | 🔜 :  | Delayed to 2.3.0
9 | Overlay Icons - Shared folder disable  | 1.- Disable share a folder with a user <br> | Overlay icon is updated with a "Green check" icon <br> | 🔜 : | Delayed to 2.3.0
10 | Overlay Icons - Warning  | 1.- Generate a warning i.e a folder that could not be synced <br> | Overlay icon is updated with a "Yellow warning" icon <br> | ✅
11 | Overlay Icons - Error  | 1.- Generate an error i.e exceed quota allowed <br> | Overlay icon is updated with a "Red error" icon <br> | ✅ |
12 | Overlay Icons - Solve warning  | 1.- Generate a warning i.e a folder that could not be synced <br> 2.- Solve the problem  <br>| Overlay icon is updated with a "Green check" icon <br> |  ✅
13 | Overlay Icons - Solve error  | 1.- Generate an error i.e exceed quota allowed <br> 2.- Solve the problem  <br>| Overlay icon is updated with a "Green check" icon <br> | ✅
14 | Overlay Icons - Folder hierarchy warning  | 1.- Generate a warning i.e a folder that could not be synced <br> | Overlay icon at parent folder is a "Green check" <br>  |  ✅
15 | Overlay Icons - Folder hierarchy error  | 1.- Generate an error i.e exceed quota allowed <br> | Overlay icon at parent folder is "Yellow warning" icon <br> | ✅
16 | Overlay Icons - Syncing | 1.- Copy at least one hundred files and folders to Shared sync folder <br> | Overlay icon is updated with "Blue sync" icon until the process finish <br> | ✅
17 | Overlay Icons - Shared file with you | 1.- As user1 share with user2 a file <br> | As user2 the file shared should appear and a "green shared" overlay icon must appear | ✅ 
18 | Overlay Icons - Shared folder with you | 1.- As user1 share with user2 a folder <br> | As user2 the folder shared should appear and a "green shared" overlay icon must appear | ✅

**Comment by rperezb** [comment]
@mcastroSG it's great to see the status of the regression test, thanks!
I was wondering whether you have included any smoke test regarding SSO auth as well as external storage

**Comment by mcastroSG** [comment]
@rperezb  sure, I´ll add some shib conection test and also external storage

**Comment by mcastroSG** [comment]
###Login

TestID | Test Case | Steps to reprouce |Expected Result |Result| Related Comment
------------ | ------------- | ------------- | ------- | ----- | ------
1 | Update Installation | 1. You need to have installed a previous version 2. Update the new version || ✅ | | Tested from 2.2.1 and 2.2.0 on OSX, W and L(Ubuntu 14.04/16.04)
2 | Install the new version (with url: HTTPS) | 1. Delete the previous version 2. Install the new version ||  ✅  |Tested from 2.2.1 and 2.2.0 on OSX, W and L(Ubuntu 14.04/16.04) |
3 | Install version with SHIB  | 1. Install version 2. Introduce the user account with SHIB  |All the account is sync with the User SHIB| ✅ | |
4 | Install the new version with LDAP Server | 1. Install the new version with LDAP server || ✅ | |
5 | Install the new version with Active Directory server | 1. Install the new version with Active Directory server || ✅ | |

**Comment by rperezb** [comment]
@mcastroSG ☺️ about the SSO did you try the 2 approachs, sso and autoprovisioning mode?

**Comment by mcastroSG** [comment]
@rperezb both tk for reminder 😅

**Comment by mcastroSG** [comment]
Closing
