### ISSUE TITLE
Update: Page not found

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#4934]
### Steps to reproduce
Client version 2.1.0 shows a button to restart and update the client. Then a Window opens that a new client is available (2.1.1 build 5837), I have the choice between skipping this version, skipping this time and run the update. So I choose: Run the update.

### Expected behaviour
Update is run.

### Actual behaviour
Webpage https://owncloud.org/sync-clients opens with message:
````
Sorry, but the page you were trying to view does not exist.
````

Finally I downloaded the version myself.

**Comment by danimo** [comment]
Fixed.
