### ISSUE TITLE
Client removes characters from owncloud.cfg on first run

### ISSUE THREAD

**Issue by muzzol** [owncloud/client#4937]
We prepopulate configuration for all our network users with a logon script similar to this one:

```
if exist "%USERPROFILE%/owncloud" goto endoc

md "%LOCALAPPDATA%/ownCloud"
echo [General] > "%LOCALAPPDATA%/ownCloud/owncloud.cfg"
echo optionalDesktopNotifications=true >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"
echo. >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"
echo [Accounts] >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"
echo version=2 >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"
echo 0\Folders\ownCloud\localPath=%USERPROFILE%\ownCloud >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"
echo 0\Folders\ownCloud\targetPath=/ >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"
echo 0\url=https://XXX.YYY.net >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"
echo 0\Folders\ownCloud\paused=false >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"
echo 0\http_certificatePasswd= >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"
echo 0\Folders\ownCloud\ignoreHiddenFiles=true >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"
echo 0\http_certificatePath= >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"
echo 0\http_user=%USERNAME% >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"
echo 0\authType=http >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"
echo 0\user=%USERNAME% >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"

md "%USERPROFILE%/ownCloud"

:endoc

```

So when the user executes client for first time only the password is required to input.
This is the created file:
```
[General] 
optionalDesktopNotifications=true 
 
[Accounts] 
0\Folders\ownCloud\localPath=C:\Users\test1\ownCloud\
version=2 
0\Folders\ownCloud\targetPath=/ 
0\url=https://XXX.YYY.net 
0\Folders\ownCloud\paused=false 
0\http_certificatePasswd= 
0\Folders\ownCloud\ignoreHiddenFiles=true 
0\http_certificatePath= 
0\http_user=test1
0\authType=http 
0\user=test1

```

### Actual behaviour
On first client execution the cfg is messed up and we get a line like this:
`0\Folders\ownCloud\localPath=C:sersest1wnCloud`

It seems that client is interpreting backslashes as escape characters and tries to parse them.

I've tried with something like
```echo 0\Folders\ownCloud\localPath=%SystemDrive%/Users/%USERNAME%/ownCloud >> "%LOCALAPPDATA%/ownCloud/owncloud.cfg"```

And it works great, so I can confirm backslashes are the problem.

### Steps to reproduce
1. Create a cfg file with prepopulated data before client execution
2. Execute client
3. Check cfg file

### Client configuration
Client version: 2.1.1

Operating system: Windows 7

OS language: ES

Installation path of client: C:\Program Files (x86)\ownCloud

**Comment by ogoffart** [comment]
back slashes need to be escaped in the config files.   But anyway, it is best to use forward slashes for filenames.
So you will have to fix your script to either escape the backslashes, or use forward slashes.

Either way, this is not a bug in the client.
