### ISSUE TITLE
Invalid character in filename halts sync and gives a cryptic error

### ISSUE THREAD

**Issue by davad** [owncloud/client#4941]
### Expected behaviour
A user should be warned that a filename contains an invalid character and told which file it is. The client should then continue to sync valid files.

### Actual behaviour
Client stops syncing and gives the message `An error occurred while opening a folder Connection refused`.  In the client setting window, there is a red box that fills with the messages:
```
Connection closed
Connection closed
Connection closed
...
Operation canceled
Operation canceled
Operation canceled
...
```

### Steps to reproduce
1. Create a couple files with an invalid character in the filenames
2. Wait for client to scan and attempt to upload that file

### Server configuration
Operating system:
Ubuntu 15.10

Web server: 
Apache 2, v2.4.12

Database:
MySQL, v5.6.30

PHP version:
5.6.30

ownCloud version:
9.0.2

Storage backend:
Local disk

### Client configuration
Client version:
2.2.0

Operating system:
Ubuntu 16.04

OS language:
English

Installation path of client:
/usr/bin/owncloud

### Logs

I think this is the relevant bit from the client log:
```
|0|$PATH/^A.png|INST_NEW|Up|1464889266||247579||1|Connection closed|0|0|0|||INST_NONE|
|0|$PATH/^B.png|INST_NEW|Up|1464889266||28206||6|Continue blacklisting: Error downloading https://$SERVER/owncloud/remote.php/webdav/$PATH/%02.png - server replied: Bad Request (File name contains at least one invalid character)|400|0|0|||INST_NONE|`
```

Apache access log for this request (nothing shows up in the error log)
```
$IP - $OWNCLOUD-USER [02/Jun/2016:16:02:40 -0400] "PUT /owncloud/remote.php/webdav/$PATH/%02.png HTTP/1.1" 400 1178 "-" "Mozilla/5.0 (Linux) mirall/2.2.0%nil (build 1605)"
```

ownCloud log:
```
{"reqId":"NHTgpe1gTmu2jSs2ylXH","remoteAddr":"$IP","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 400 File name contains at least one invalid character\",\"Exception\":\"OCA\\\\DAV\\\\Connector\\\\Sabre\\\\Exception\\\\InvalidPath\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/lockplugin.php(58): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\ObjectTree->getNodeForPath('$PATH...')\\n#1 [internal function]: OCA\\\\DAV\\\\Connector\\\\Sabre\\\\LockPlugin->getLock(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(446): Sabre\\\\Event\\\\EventEmitter->emit('beforeMethod', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(55): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(138): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/connector\\\/sabre\\\/objecttree.php\",\"Line\":126,\"User\":\"$OWNCLOUD-USER\"}","level":4,"time":"2016-06-02T20:02:40+00:00","method":"PUT","url":"\/owncloud\/remote.php\/webdav$PATH\/%02.png","user":"$USER"}
```

**Comment by davad** [comment]
On Fri, Jun 3, 2016 at 4:08 AM, Olivier Goffart <notifications@github.com>
wrote:

> Don't you see Bad Request (File name contains at least one invalid
> character) in the UI?
>

I didn't. I only saw the error messages I mentioned. Is it also supposed to
print that in the 'Settings" window? There were a number of files with
invalid characters, and it wouldn't let me scroll to the bottom of the
error messages.


-- 
David Landry

**Comment by guruz** [comment]
@davad Scroll where? The UI should show it in the normal progress area or the sync protocol

**Comment by davad** [comment]
The "Settings" window where you can select which folders are synced from
each server showed the "Connection Closed....Operation Canceled" message
with a red background. When I hovered over the tray icon, I think that's
where I saw the message "An error occurred while opening a folder..."

On Fri, Jun 3, 2016 at 8:41 AM, Markus Goetz <notifications@github.com>
wrote:

> @davad <https://github.com/davad> Scroll where? The UI should show it in
> the normal progress area or the sync protocol
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/owncloud/client/issues/4941#issuecomment-223568369>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AALns7G17ZaK3gZqTJ12O1_56N4_4_0qks5qICEFgaJpZM4Is9Yj>
> .
>



-- 
David Landry

**Comment by davad** [comment]
I don't know this codebase, and C/C++ isn't a strength of mine, so take this with a grain of salt. I dug through a bit and might have found the problem:

It looks like the invalid character error is supposed to be raised [here](https://github.com/owncloud/client/blob/159535fe9002c2325101ccf64d03ee99f736a7a3/csync/src/csync_update.c#L747). In that while loop, dirent->name is set [here](https://github.com/owncloud/client/blob/d7bd1300a8397c2782e8d75cf7c595b1ada70d88/csync/src/vio/csync_vio_local_unix.c#L106) for unix clients. Looking [here](https://github.com/owncloud/client/blob/d7bd1300a8397c2782e8d75cf7c595b1ada70d88/csync/src/std/c_string.c#L263) for the function definition, it looks like unix machines basically cast from `mbchar_t*` to `char*`. And on unix machines, `mbchar_t` and `char` are equivalent ([link](https://github.com/owncloud/client/blob/d7bd1300a8397c2782e8d75cf7c595b1ada70d88/csync/src/std/c_private.h#L131).

I might be wrong. I haven't worked with iconv before, and I don't know if that's compiled into the linux client or not.

I'll try to come up with something to help people reproduce the problem.

**Comment by davad** [comment]
I came up with a script to make similar invalid files, and I got the right error message this time. Closing until I can come up with a way to reproduce it :)

**Comment by Gerii** [comment]
Same issue here. I get the following error message:
Connection closed
Operation canceled
Operation canceled
filename
filename: Operation canceled
filename: Operation canceled

Not sure what the invalid character is though. It only contains - _ and . (can't copy the exact error message, but the path is quite long, maybe that's an issue?) Would be nice if the client would also tell me which characters are invalid. The client retries syncing this folder over and over again instead of just skipping these files.

**Comment by Gerii** [comment]
Okay so I think found the offending file/folder:
One file had a newline in its name and was only reported in the client log: Implementation of General Semaphores Using Binary%0ASemaphores.pdf
The other one was shown in the client itself but without any hint about the problem - the folder had a trailing 0x20 in its name.
All other files which were reported by the client are probably fine (especially as these changed with each try). Will report back when the sync is done.

**Comment by jonnyt886** [comment]
+1 I am getting this too on (server: 12.0.0 on Linux, client 2.2.4 build 1 on MacOSX Sierra).

Client reports a handful of "Operation Cancelled"s on red background, and in the Activity/Not Synced tab, "This item is not synced because of previous errors: Error downloading <filename>.... replied: Bad Request".

The server log shows:

```
OCA\DAV\Connector\Sabre\Exception\InvalidPath: HTTP/1.1 400 File name contains at least one invalid character
/usr/share/webapps/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 1163: OCA\DAV\Connector\Sabre\ObjectTree->getNodeForPath('backup/Document...')
/usr/share/webapps/nextcloud/3rdparty/sabre/dav/lib/DAV/CorePlugin.php - line 590: Sabre\DAV\Server->createCollection('backup/Document...', Object(Sabre\DAV\MkCol))
[internal function] Sabre\DAV\CorePlugin->httpMkcol(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/usr/share/webapps/nextcloud/3rdparty/sabre/event/lib/EventEmitterTrait.php - line 105: call_user_func_array(Array, Array)
/usr/share/webapps/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 479: Sabre\Event\EventEmitter->emit('method MKCOL', Array)
/usr/share/webapps/nextcloud/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/usr/share/webapps/nextcloud/apps/dav/appinfo/v1/webdav.php - line 71: Sabre\DAV\Server->exec()
/usr/share/webapps/nextcloud/remote.php - line 162: require_once('/usr/share/weba...')
{main}
```

The server log has debug logs turned on but around that fatal error message (there are half a dozen of them) there are no other debug or related messages, just the fatals. Irritatingly I cannot see which file is actually causing the problem as the mention of `getNodeForPath(...)` shows only the first part of the filename.

**Comment by guruz** [comment]
@jonnyt886 The current client version is 2.3.2, not 2.2.4
https://owncloud.org/changelog/desktop/
