### ISSUE TITLE
[Ubuntu16]Main windows is not shown after click on Account > Add new  button

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4944]
### Expected behaviour
In case we try to add a new account to Desktop Client, after fill Server address and Username/Pwd dialog, main window should be shown in case we click Tray Icon > Settings.
### Actual behaviour
In case we click on Account > Add new , a new dialog is shown but does not matter we complete the dialog or cancel, main window is not shown anymore
### Steps to reproduce
1. Click on Account > Add new
2. Fill server/username/pwd or not 
3. Click on Tray Icon > Settings

### Server configuration
Server OS: Ubuntu 14
Server Version: 9.1.0 Beta

### Client configuration
Client OS: Ubuntu 16.04 LTE
Client Version: Version 2.2.1nightly201663 (build 1666) , tested on 2.2.0 too

**Comment by ckamm** [comment]
@mcastroSG I can bring up the main settings dialog while the new account wizard is active and after it's been closed, but I'm not using that particular ubuntu version. Can you verify it's specific to stock ubuntu 16.04?

**Comment by ckamm** [comment]
@mcastroSG I got a Ubuntu 16.04 VM and can reproduce.

**Comment by ckamm** [comment]
I think this may be yet another context menu bug. "Quit OwnCloud" has no effect either :(

**Comment by ckamm** [comment]
Pull request: #4947

**Comment by mcastroSG** [comment]
Tested and working fine:

Server OS: Ubuntu 14.04
Server Version : 9.1.0 Beta

Client OS: Ubuntu 16.04
Client Version: Version 2.2.1nightly2016616 (build 1695)
