### ISSUE TITLE
ownCloud sync client for Windows 10 is crashing with Visual C++ Runtime error

### ISSUE THREAD

**Issue by BlackNebulaR** [owncloud/client#4945]
### Expected behaviour
I expect that the sync app syncs my data into my cloud.

### Actual behaviour
The program is crashing almost every 5 minutes after restarting it. The error screen says:
[Error "Visual C++ Runtime Library"](https://blacknebular.de/grafiken/ownCloud%20stürzt%20ab.PNG)

### Steps to reproduce
1. start it
2. wait
3. get the error

### Server configuration
Operating system: Debian 8 64-bit

Web server: Apache 2

Database: MySQL

PHP version: PHP 5

ownCloud version: 9.0.2

Storage backend: ?

### Client configuration
Client version: 2.2.0 build 6076

Operating system: Windows 10 (64-bit)

OS language: German

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

[Error log from the client](https://gist.github.com/BlackNebulaR/f62bd42e07a3b85c3c70448c7f5b75a7) The problem is, that I have no chance to get a log from the program, after it crashed.

I don't know where to find the other ones.

I hope you can help :)

**Comment by tmaex** [comment]
Exactly the same problem here.

Starting client -> client prepares sync -> client starts to sync -> RAM usage explodes -> runtime error

**Comment by danimo** [comment]
Please try https://owncloud.org/install/#testing-development (2.2.1 RC1)

**Comment by tmaex** [comment]
Seems to solve the problem, Thanks!

Installed and syncing stable for 5min now.

**Comment by wsamirmr** [comment]
No encuentro el instalador de la versión 2.2.1 RC1 para probar la solución al error, alguien lo puede compartir?

**Comment by crrodriguez** [comment]
@wsamirmr por favor utiliza un cliente actualizado 2.2.4 o superior. descargalo del sitio web de owncloud. 
Saludos.

**Comment by wsamirmr** [comment]
Gracias por tu respuesta, pero es justo la versión que estoy usando en windows 10 ahora, pero sigue arrojando el mismo error como resultado al tratar de sincronizar con el servidor, ya probe instalando la version 2015 de las librerias del runtime para visual C++ y el problema reaparece a los 5 minutos como maximo.

**Comment by wsamirmr** [comment]
Solucionado, se instala Visual C++ Redistributable para Visual Studio 2015 y se desinstala las versiones del runtime anteriores a 2010, con esto he eliminado el error de apertura y sincronización del cliente de owncloud en Windows 10

**Comment by wsamirmr** [comment]
y usando ademas la version 2.2.2 del cliente de sincronizacion https://owncloud.org/changelog/desktop/

**Comment by guruz** [comment]
For help in Spanish please try https://central.owncloud.org/
This is a bugtracker.
You can also try 2.3pre1 https://download.owncloud.com/desktop/daily/ownCloud-2.3.0.6659pre1-setup.exe
