### ISSUE TITLE
Browsers different behavior

### ISSUE THREAD

**Issue by DJManas** [owncloud/client#4952]
### Expected behaviour
In every browser it should work the same way

### Actual behaviour
In Safari, everything seems to work
In Chrome, user’s can’t create calendar events (that is what they have found, there may be more problems)
In Firefox, we can’t even login into OC through web interface

### Steps to reproduce
1. Install OC
2. Login and work under different browsers (except Safari where it looks like it is working)

### Server configuration
Operating system: OSX, Windows 7, Windows 10

Web server: 
nginx-1.10.1,2

Database:
mysql57-server-5.7.12_1

PHP version:
php56-5.6.22

ownCloud version:
owncloud-9.0.2

Storage backend:
FreeBSD 10.3-RELEASE FreeBSD 10.3-RELEASE #10 r297612:

### Client configuration
Client version:
N/A

Operating system:
N/A

OS language:

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:
2016/05/22 23:31:36 [error] 61208#100112: *172 open() "/usr/local/www/owncloud/favicon.ico" failed (2: No such file or directory), client: 192.168.210.113, server: XXX, request: "GET /favicon.ico HTTP/1.0", host: XXX, referrer: "https:/XXX/"
2016/06/03 10:48:59 [error] 85127#100197: *9102 open() "/usr/local/www/owncloud/favicon.ico" failed (2: No such file or directory), client: 192.168.210.113, server: XXX, request: "GET /favicon.ico HTTP/1.0", host: „XXX", referrer: "https://XXX/remote.php/webdav/"

3. ownCloud log (data/owncloud.log):
Can I send it „privately“?

**Comment by danimo** [comment]
This is the tracker for the ownCloud Desktop sync client. The Calendar issue tracker is located at https://github.com/owncloud/calendar/issues. For basic server issues, there is https://github.com/owncloud/core/issues. However, Firefox not being able to log in is very likely a setup issue.

**Comment by DJManas** [comment]
Ok, I have found calendar issue here, I was searching for browser names instead of calendar, my bad. https://github.com/owncloud/calendar/issues/563

Setup issue for OC, webserver or Firefox? I am just wondering if it is not working in firefox, how come it is working in every other browser?
