### ISSUE TITLE
[debian] owncloudcmd not syncing after update

### ISSUE THREAD

**Issue by filipsPL** [owncloud/client#4955]
I'm using `owncloudcmd` on the Debian Testing. After system update last week the client stopped working.

### Expected behaviour
The sync of the folder should be performed

### Actual behaviour
After issuing the command `owncloudcmd ./destDir/ ownclouds://username:password@url/remote.php/webdav/`

I get the message:

```
Set proxy configuration to use system configuration
Cannot load system exclude list or list supplied via --exclude
Przerwane
```
After adding  a fake exclude and proxy parameters `owncloudcmd --exclude exclude.txt --httpproxy "" ...` I get:
```
Cannot load system exclude list or list supplied via --exclude
Przerwane
```

### Server configuration

ownCloud version: `ownCloud 8.0.4 (stable) `

### Client configuration

Client version: 2.2.0

Operating system: Debian GNU/Linux testing

OS language: pl-PL

Installation path of client: default

### Logs

Client log:

```
Set proxy configuration to use system configuration
Cannot load system exclude list or list supplied via --exclude
Przerwane
```

**Comment by danimo** [comment]
@jnweiger exclude file is in wrong location

**Comment by filipsPL** [comment]
@danimo can/should I do anything about that? Also giving the full path to the exclude file (which is an empty file as I don't want to exclude anything) doesn't help.

**Comment by jnweiger** [comment]
do you have a sync-exclude.lst file in the usual place?

ls -la /etc/ownCloud/sync-exclude.lst
-rw-r--r-- 1 root root 362  6. Jun 10:50 /etc/ownCloud/sync-exclude.lst

**Comment by filipsPL** [comment]
> `strace -o xxx.log owncloudcmd ...` 

there was a line: `stat64("/etc/owncloud-client/sync-exclude.lst", 0xbff3d4ec) = -1 ENOENT (No such file or directory)`

Creating this directory and touching the file **solved the problem**!

(previously there was no `/etc/ownCloud/` and `sync-exclude.lst` and the clinet worked fine)

Thanks for quickly solving the issue!

**Comment by jnweiger** [comment]
The --exclude option only adds an exclude file to the system exclude file, both are effective then. Adding an empty exclude file has no effect in any case. There is no option to suppress entries from /etc/ownCloud/sync-exclude.lst except editing the file directly.

**Comment by jnweiger** [comment]
I am curious: did you create an /etc/owncloud-client/ folder, or did you create an /etc/ownCloud/ folder to solve the issue?

**Comment by filipsPL** [comment]
> I am curious: did you create an /etc/owncloud-client/ folder, or did you create an /etc/ownCloud/ folder to solve the issue?

I've created `/etc/owncloud-client/` folder and it solved the problem.

**Comment by jnweiger** [comment]
Okay thanks. I am still somewhat puzzled why it is /etc/owncloud-client/ for you. I am pretty sure, when you update your client to 2.2.1 the path will be /etc/ownCloud  -- and I am also pretty sure it was /etc/ownCloud for earlier releases. Probably something spooky with 2.2.0 ...

I am saying this, so that you are aware when you update your client. Closing here, as we effectiviely fixed the issue.

**Comment by ivoruetsche** [comment]
Just install the client part: apt-get install owncloud-client

After this, it runns on my side

gruss ivo

**Comment by fbartels** [comment]
Came here after I got the message `Cannot load system exclude list or list supplied via --exclude` after installing `owncloud-client-cmd` on Ubuntu 18.04 (from the Ubuntu repos, not the Owncloud ones). Had to create `/etc/owncloud-client/sync-exclude.lst` manually to be able to use owncloudcmd.

**Comment by guruz** [comment]
CC @hefee

**Comment by guruz** [comment]
@hefee I don't know how your packages are structured but maybe sync-exclude.lst  needs to be in a package that both owncloud-client-cmd and owncloud-client depend on

**Comment by jkldgoefgkljefogeg** [comment]
owncloud-client-cmd 2.4.1+dfsg-1 on Ubuntu 18.04.3 LTS

`01-03 01:43:08:343 [ fatal default ]:   Cannot load system exclude list or list supplied via --exclude`

This is so counter-intuitive. Why does it try to read a file that doesn't exist and crashes when the fix is to supply it an empty file...
