### ISSUE TITLE
Rebuild Debian packages fails with missing patches

### ISSUE THREAD

**Issue by rldleblanc** [owncloud/client#4957]
### Expected behaviour
Downloading and building the Debian source package should produce an installable Debian package.

### Actual behaviour
Failed package build.

The patches are not included in owncloud-client-2.2.1-5.1.dsc. Also, debian/rules should not reference patches outside of the relative path as a non-root user may not have access to write/read from that location. I'm unable to find these patches to apply them to successfully build the package.

For the moment, I'm just going to build the package without the tray-patch.patch and highdpi-6ccd9e8.patch so that I can get my client running again.

As an alternative, if owncloud-client was built for Stretch, I would not have to re-build it since Stretch has libssl1.0.2 and the current Jessie package wants libssl1.0.0.

### Steps to reproduce
1.  apt-get source owncloud-client
2. cd owncloud-client-<version number>
3. dpkg-buildpackage

### Client configuration
Client version: 2.2.1

Operating system: Debian Stretch

OS language: English

Installation path of client: N/A

### Logs

$ dpkg-buildpackage 
dpkg-buildpackage: info: source package owncloud-client
dpkg-buildpackage: info: source version 2.2.1-5.1rleblanc1
dpkg-buildpackage: info: source distribution UNRELEASED
dpkg-buildpackage: info: source changed by Robert LeBlanc <rleblanc@rleblanc-pc>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build owncloud-client-2.2.1
 fakeroot debian/rules clean
dh clean
   dh_testdir
   dh_auto_clean
   dh_clean
        rm -f debian/debhelper-build-stamp
        rm -f debian/owncloud-client.substvars
        rm -f debian/owncloud-client.*.debhelper
        rm -rf debian/owncloud-client/
        rm -f debian/owncloud-client-doc.substvars
        rm -f debian/owncloud-client-doc.*.debhelper
        rm -rf debian/owncloud-client-doc/
        rm -f debian/owncloud-client-l10n.substvars
        rm -f debian/owncloud-client-l10n.*.debhelper
        rm -rf debian/owncloud-client-l10n/
        rm -f debian/libowncloudsync0.substvars
        rm -f debian/libowncloudsync0.*.debhelper
        rm -rf debian/libowncloudsync0/
        rm -f debian/libowncloudsync-dev.substvars
        rm -f debian/libowncloudsync-dev.*.debhelper
        rm -rf debian/libowncloudsync-dev/
        rm -f debian/owncloud-client-nautilus.substvars
        rm -f debian/owncloud-client-nautilus.*.debhelper
        rm -rf debian/owncloud-client-nautilus/
        rm -f debian/owncloud-client-nemo.substvars
        rm -f debian/owncloud-client-nemo.*.debhelper
        rm -rf debian/owncloud-client-nemo/
        rm -rf debian/.debhelper/
        rm -f debian/*.debhelper.log
        rm -f debian/files
        find .  \( \( \
                \( -path .\*/.git -o -path .\*/.svn -o -path .\*/.bzr -o -path .\*/.hg -o -path .\*/CVS \) -prune -o -type f -a \
                \( -name '#*#' -o -name '.*~' -o -name '*~' -o -name DEADJOE \
                 -o -name '*.orig' -o -name '*.rej' -o -name '*.bak' \
                 -o -name '.*.orig' -o -name .*.rej -o -name '.SUMS' \
                 -o -name TAGS -o \( -path '*/.deps/*' -a -name '*.P' \) \
                \) -exec rm -f {} + \) -o \
                \( -type d -a -name autom4te.cache -prune -exec rm -rf {} + \) \)
        rm -f *-stamp
 dpkg-source -b owncloud-client-2.2.1
dpkg-source: warning: no source format specified in debian/source/format, see dpkg-source(1)
dpkg-source: info: using source format '1.0'
dpkg-source: info: building owncloud-client using existing owncloud-client_2.2.1.orig.tar.gz
dpkg-source: info: building owncloud-client in owncloud-client_2.2.1-5.1rleblanc1.diff.gz
dpkg-source: info: building owncloud-client in owncloud-client_2.2.1-5.1rleblanc1.dsc
 debian/rules build
dh build
   dh_testdir
   dh_update_autotools_config
   debian/rules override_dh_auto_configure
make[1]: Entering directory '/home/rleblanc/code/owncloud-client-2.2.1'
if grep -q ' 12.04 LTS ' /etc/issue; then \
  patch -p0 < /usr/src/packages/SOURCES/neon27_ubuntu1204_compat_csync.diff; \
  sed -i.orig -e 's/OVERRIDE=override/OVERRIDE=/' cmake/modules/QtVersionAbstraction.cmake; \
fi
patch -p1 < /usr/src/packages/SOURCES/tray-patch.patch
/bin/bash: /usr/src/packages/SOURCES/tray-patch.patch: No such file or directory
debian/rules:22: recipe for target 'override_dh_auto_configure' failed
make[1]: *** [override_dh_auto_configure] Error 1
make[1]: Leaving directory '/home/rleblanc/code/owncloud-client-2.2.1'
debian/rules:19: recipe for target 'build' failed
make: *** [build] Error 2
dpkg-buildpackage: error: debian/rules build gave error exit status 2

**Comment by jnweiger** [comment]
@dragotin Please review https://github.com/owncloud/administration/commit/22b3df64f87c3e535571a8d214df5fb51b89ccc6 
is this what you just tested?

**Comment by rldleblanc** [comment]
I just rebuilt without the patches since I could not find them.

**Comment by jnweiger** [comment]
I am sending all the fixes to :desktop --> rebuilds should appear in https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adesktop&package=owncloud-client soon.
With some luck, we even get Ubuntu-16.04 packages this time.

**Comment by danimo** [comment]
Moving. Please close if no longer applicable.

**Comment by dragotin** [comment]
Patch is in obs, closing hence.
