### ISSUE TITLE
Sync-Client: can't upload files in new folder

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#4959]
### Expected behaviour
Files should upload

### Actual behaviour
I created a new folder and copied files around. Getting error `Not allowed because you don't have permission to add files to that folder`.

### Steps to reproduce
1. Create a new folder on the client (there is no such folder on the server)
2. Copy files from a different folder into that one
3. Folder is created on the server but the files aren't put there

What is strange, I've done this numerous times before. Other files/folder sync perfectly, just this folder. I tried `system proxy` and `no proxy`. On the webinterace, I can see the empty folder.

### Server configuration
Operating system: Debian 8

Web server: Apache

Database: MariaDB

PHP version: 7.0.x (dot-deb)

ownCloud version: 8.2.5

Storage backend: server main storage, no external storage

### Client configuration
Client version: 2.1.1 (I updated to 2.2.1 hoping the error would dissappear)

Operating system: OS X 10.9.5

OS language: english

Installation path of client: /Applications/owncloud.app/...

### Logs
client:
````
06-09 23:20:15:020 0x7fd670413e60 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result:  3
06-09 23:20:15:020 0x7fd670413e60 OCC::Folder::slotSyncFinished:   ** error Strings:  ("xxxx/houmault/annonce.pdf: Not allowed because you don't have permission to add files in that folder", "xxxx/houmault/houmault.docx: Not allowed because you don't have permission to add files in that folder")
06-09 23:20:15:021 0x7fd670413e60 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
06-09 23:20:15:021 0x7fd670413e60 OCC::Folder::slotSyncFinished: the last 1 syncs failed
````
owncloud.log
````
{"reqId":"Mz4M7Z2JNaCOvRgpoGcD","remoteAddr":"ip","app":"no app in context","message":"Current user is not logged in","level":0,"time":"June 09, 2016 21:29:14","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/folders"}
{"reqId":"BiGsZDP7XE52z+eqWoBI","remoteAddr":"ip","app":"no app in context","message":"Current user is not logged in","level":0,"time":"June 09, 2016 21:29:14","method":"GET","url":"\/owncloud\/index.php\/apps\/news\/feeds"}
{"reqId":"nQudzbwRTkvS6tMuSBun","remoteAddr":"ip","app":"no app in context","message":"Current user is not logged in","level":0,"time":"June 09, 2016 21:29:14","method":"GET","url":"\/owncloud\/index.php\/apps\/notifications"}
````
permission of the folder:
````
3934365 4.0K drwxr-xr-x+  2 www-data www-data 4.0K Jun  9 17:08 houmault
3016578 4.0K drwxr-xr-x+  2 www-data www-data 4.0K Feb 25 16:15 working_folder
````

The apache-logs don't show anything particular. This one perhaps (not sure if related):
````
ip - username [09/Jun/2016:21:39:21 +0000] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 500 991 "-" "Mozilla/5.0 (Macintosh) mirall/2.2.1 (build 3427)"
````

**Comment by tflidd** [comment]
I just created a textfile inside the folder via webinterface. The file was downloaded from the client and then the files from the client were uploaded.

**Comment by guruz** [comment]
Those ```Current user is not logged in``` messages come for each operation that fails? (seen from the client)

**Comment by tflidd** [comment]
With chrome on this computer I have the problem that it often terminates the session when I'm using the news-app (Firefox doesn't) but that's a different problem. However, I was aware of this and I had closed chrome at the moment I was running the tests. Unfortunately, I'm not in that state to verify and I don't want to point you in the wrong direction (perhaps there was some unfinished process running).

Some more details about the folder: In OS X:
1. Create new folder in parent folder
2. then move this folder into a subfolder
3. open it and paste some files into it (1 word document 103 kB, 1 PDF 1.1 MB)

I did similar operations several times yesterday and only the last time I had this problem.

I first thought, it could be the file-locking but normally that should result in a different error and I don't know if locks are done on a folder-basis? What is strange though, it happened at work and the problem still existed 1-2 hours late when I reconnected my laptop. I use redis.
To test this, I created an empty textfile in the folder via webinterface which somehow solved the problem. I didn't check the entry in the filecache-table before.

I will try to reproduce this error today, but I'm not too optimistic to make it happen.

**Comment by dragotin** [comment]
Note that this is about a comparably old server (8.2.5) which might not have all the permission kung fu that newer ones have. @PVince81 can you comment?

**Comment by PVince81** [comment]
Locks can be set on folders when folders are renamed/moved to prevent people uploading/downloading in such folders. But you're right that it would have been a different error.

I can't think of any issue or behavior pattern that could prevent you uploading in a new folder.
It also can't be an old stray lock that just expired since it's about a new folder.

**Comment by PVince81** [comment]
The message "Not allowed because you don't have permission to add files to that folder" means that the "oc_filecache" entry for the current folder contained permissions that do not allow you to upload.
The question is why these permissions have been set wrong in the first place.

**Comment by ogoffart** [comment]
As Pvince81 said, ""Not allowed because you don't have permission to add files to that folder" happens only if the permission that the client recieve from the server are set to read-only  (usually this is only the case for shared folder).

So why does it happen in this case? It could be a bug in the server, that the server sends wrong permissions (which i'd say is the most probable hypothese). Or a bug in the client which does not read or save the permission correctly.

What would help is:  A full log, which includes the log at which the folder permissions are recieved from the server.
What permissions are on the database for this folder? (you can open the local database `.csync_journal.db` with sqlite3 utility tool and do  ` SELECT path,remoteperm FROM metadata WHERE path='houmault';`

**Comment by tflidd** [comment]
Thanks for the hints. I haven't been able to reproduce this problem so far. I keep trying...
