### ISSUE TITLE
 garbled text when installing client in traditional Chinese Windows OS.

### ISSUE THREAD

**Issue by leo-yip** [owncloud/client#4960]
when Traditional Chinese OS, it display garbled text.
![image](https://cloud.githubusercontent.com/assets/19850742/15954350/7054e720-2f08-11e6-89a2-1cae6d8397d7.png)

but display properly in Simplified Chinese.

![image](https://cloud.githubusercontent.com/assets/19850742/15954414/5dfd922e-2f09-11e6-94a5-966d729e7e60.png)

I have tried from Version 1.8 to 2.2.1

**Comment by guruz** [comment]
@leo-yip This is only the installer?
Or also in the client later?

**Comment by leo-yip** [comment]
only in installer.

**Comment by guruz** [comment]
On 2.2.1?

**Comment by danimo** [comment]
@guruz may be due to using the wrong code page.

**Comment by danimo** [comment]
(NSIS is not unicode-based yet)

**Comment by leo-yip** [comment]
I tried from version 1.8 to 2.2.1
All display garbled text.

**Comment by guruz** [comment]
With 2.5 we plan to use MSI.

**Comment by guruz** [comment]
@leo-yip Hi! Could you try the MSI-based installer? https://github.com/owncloud/client/releases
