### ISSUE TITLE
Windows access?

### ISSUE THREAD

**Issue by joshk03** [owncloud/client#4962]
RealRancor referred me here for a feature request from: https://forum.owncloud.org/viewtopic.php?f=14&t=37241

Notice how Dropbox and OneDrive are not in sub-folders? How do I do that with ownCloud?
![opendialog](https://cloud.githubusercontent.com/assets/18041557/15974254/2bf4ccee-2f0d-11e6-8376-925643947368.jpg)

**Comment by danimo** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/dn889934(v=vs.85).aspx explains how to do it. Patches welcome :)

**Comment by joshk03** [comment]
Holy *.  I have't started using ownCloud yet so I will just search for a competitor.  Nevermind.

**Comment by danimo** [comment]
@joshk03 Err, I wasn't trying to be offensive. ownCloud adds a folder link (next to "Downloads", etc). But if you want a direct folder in the root it's simply not there yet. We will be working on it, but I gave you a work around. As its an open source project and some people are actually motivated to help out, I was trying to invite you to do so. Sorry if that came across differently.

**Comment by joshk03** [comment]
I wasn't offended, I was overwhelmed.  It seams SeaFile might be more my speed, researching that now.
