### ISSUE TITLE
[Arch Linux]client runs out of memory and crashes (on computer with 32GB of RAM)

### ISSUE THREAD

**Issue by gregmuellegger** [owncloud/client#4965]
### Expected behaviour

I want to synchronize my music collection with about 25000 files. This should work smoothly.

### Actual behaviour

The ownCloud client (2.2.1 on Arch Linux) starts syncing but after about 500 successfully synced files, the memory usage exceeds the memory and swap of my computer, which is 32 GB of RAM and 1GB of swap. The computer freezes, the client crashes, the memory is freed up. After the client crashed, only ~3GB of RAM is used.

This happens predictably on my computer. I tried it about 10 times now.

### Server configuration
Operating system: Official OwnCloud 9 Docker Image
ownCloud version: 9

### Client configuration
Client version: 2.2.1
Operating system: Arch Linux
OS language: german

### Logs

I will post a log after the owncloud client crashes next time.

**Comment by dragotin** [comment]
@ogoffart @jturcotte could you try to investigate again? Thx.

**Comment by guruz** [comment]
@gregmuellegger Are you sure this is the 2.2.1 release and not some nightly build?
By syncing do you mean the client downloads those files or uploads them?

**Comment by jturcotte** [comment]
Even though it will run much slower, if you could give us a [massif](http://valgrind.org/docs/manual/ms-manual.html) trace with a build of the client where you have debug symbols, this would be the most efficient way to investigate the issue. There is probably no need to get it to crash, if you see it growing to 500-1000Mb this should already point to something in the trace.

**Comment by guruz** [comment]
@gregmuellegger Any news from you?

**Comment by gregmuellegger** [comment]
I had no time since the report to try it further. I will get back with the
log and compile with debug symbols next week. Probably around Thursday.

Thanks for the active replies so far :)

**Comment by guruz** [comment]
@gregmuellegger FYI, the current 2.2 git branch contains even more possible memory leak fixes. I don't know how easy it is for you to try that one.

**Comment by gregmuellegger** [comment]
I have updated my client to the latest version provided natively by Arch Linux (which is 2.2.2  https://www.archlinux.org/packages/community/x86_64/owncloud-client/) and the syncing seems to be A LOT smoother now. The 20000 files (~100 GB) have synced now in about 2 hours, instead of the ~14 days that the 2.2.1 version showed me as time estimation.

The memory rose steadily during the sync to about ~330 MB, which seems ok to me.

I see this problem for me as beeing resolved. The solution was to update to a newer version. 2.2.1 had the memory leak issues, 2.2.2 has solved them for me.
