### ISSUE TITLE
Desktop Client display enhancements

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#4966]
![capture-for klaas](https://cloud.githubusercontent.com/assets/7264495/16076559/1be9ce40-32f4-11e6-9b80-b9ee6f08afc2.PNG)

When you sync the home folder (e.g.: c:\Users\carlos)  it is not folder shown: syncing with ....

The used space message, with 2.9 and 5,268 may confuse, both in GB but, one is coma and the other is point (5 TB free space)

**Comment by cdamken** [comment]
@dragotin

**Comment by dragotin** [comment]
this should go to #4329

**Comment by ckamm** [comment]
@dragotin If I understand correctly this issue is about the description of the folder saying "Syncing selected files in your account with ", without specifying the target. In what way does it relate to #4329?
