### ISSUE TITLE
Excessive CPU usage ownCloud 2.2.1

### ISSUE THREAD

**Issue by jabdoa2** [owncloud/client#4967]
### Expected behaviour
When I change one file, ownCloud should synchronise that file. CPU usage should stay low.

### Actual behaviour
When I change one file, ownCloud starts to scan the sync folder and uses 100% of CPU for about some seconds. If you changed another file in the meantime it rescans right away and stays at 100% CPU for minutes. This is annoying if you keep editing files (which is not uncommon).

This did not happen in older clients (at least they were not keeping the CPU at 100% all the time).

### Steps to reproduce
1. Start OwnCloud client
2. Edit a file in the sync folder

### Server configuration
Operating system: Ubuntu 14.04

Web server: Apache

Database: MySQL

PHP version: 5.6

ownCloud version: 8.2.5

Storage backend: Files

### Client configuration
Client version: 2.2.1

Operating system: (L)Ubuntu 14.04

OS language: DE

Installation path of client: /usr/bin/owncloud

### Logs

1. Output of `owncloud `
```
06-15 13:44:26:513 0x22e2460 detected changes in paths: QSet("/folder/xxx.myfile")
06-15 13:44:26:513 0x22e2460 Schedule folder  "ownCloud"  to sync!
06-15 13:44:26:514 0x22e2460 Sync state changed for folder  "https://url.xx/remote.php/webdav/" :  "Not yet Started"
06-15 13:44:26:514 0x22e2460 void OCC::ServerNotificationHandler::slotFetchNotifications(OCC::AccountState*) Account "xxx@url.xx" does not have notifications enabled.
06-15 13:44:26:514 0x22e2460 Scheduling a sync in 2 seconds
[...]
06-15 13:44:39:859 0x22e2460 No database Transaction to commit
06-15 13:44:39:878 0x22e2460 CSync run took  11355
```
2. Web server error log: No errors

3. ownCloud log (data/owncloud.log): No problem here

**Comment by guruz** [comment]
@jabdoa2 This is interesting. We always rescan all paths if a single file changes and on startup, this is nothing that changed over the different versions.

How many files/folders do you have? It should not be at 100% for minutes, maybe for some seconds?

**Comment by jabdoa2** [comment]
Maybe it did it less efficient/less often before? As you see in the log it takes about 13s for one run. On this machine some folders are excluded. I got about 62k files to synchronise:
```
$ find | wc -l
62025
```

**Comment by ogoffart** [comment]
If you don't enable any logging flags (which is also slowing down the sync),
most of the time during the discovery is spent in analysing the exclude list.

We indeed added a few entries to the exclude list.

**Comment by jabdoa2** [comment]
I always disabled the exclusion list in the client (because i want to synchronise dot files for example). As long as there are no hidden exclusions, it should be empty. System runs on a SSD and an i7 (mobile 2 cores + HT).

I noticed the issue because the fan of my notebook started to run permanently when I use my IDE to edit stuff. This did not happen before. Also it only happens when you edit stuff. Average system load is at about 2 and its mostly caused by the ownCloud client (it takes 2 out of 4 HT cores).

**Comment by Instinct64** [comment]
Windows 10 x64 - OwnCloud Client 2.2.1

I'm seeing similar behaviour, OwnCloud is regularly taking several minutes scanning and consuming between 10-20% CPU, even when no files have changed. Once the scan is completed, it seems to wait for about ~30 seconds and then repeats the scan.

Our company uses OwnCloud for filesharing between clients and we have a few hundred folders in total. This is problematic for laptop users like myself for example, where constant background CPU drains battery very quickly.

**Comment by patrickhafner** [comment]
OS X 10.11.5
ownCloud Client 2.2.1
ownCloud 8.2.5

Excessive CPU usage as well while scanning my sync folders for changes. The process is running at 100% CPU load on one core then. Hidden files won't sync.

You can see the high CPU usage twice in this graph (every time, ownCloud is looking for changes):
![bildschirmfoto 2016-06-16 um 00 18 04](https://cloud.githubusercontent.com/assets/552011/16126666/6ab89c44-33f9-11e6-8fa0-3ca3eae33f31.png)

**Comment by sagamusix** [comment]
I can also confirm that ownCloud almost constantly eats a whole CPU core here on Windows 7, and with a dual-core setup things get sluggish very quickly if some other application also does some CPU-intensive work. If you're not already doing so, the scan thread should probably work at one of the lowest possible thread priorities. Manually changing the entire process priority via Task Manager to something lower than default seems to make Windows more responsive again, so I guess that the client might not reduce the thread priority at the moment.

**Comment by guruz** [comment]
@sagamusix @patrickhafner @Instinct64  Do you guys think the previous client versions were better in this regard?

**Comment by Instinct64** [comment]
I've reverted to 2.1.1 in order to test this. I see that OwnCloud only ramps up it's CPU usage for a few seconds, rather than the near continuous ~20% usage I see on my machine with 2.2.1.

**Comment by FlorentCoppint** [comment]
Same issue as @Instinct64, client is using 100% of one core, stops a few minutes, then using 100% again...

**Comment by dragotin** [comment]
@Instinct64 @FlorentCoppint do you use overlay icons in a file manager?

**Comment by Instinct64** [comment]
@draotin Owncloud applies it's own overlay icons in Windows Explorer. I dont have any other apps applying overlay icons in the Owncloud folders.

**Comment by FlorentCoppint** [comment]
@dragotin I'm on Ubuntu 16.04 and I don't see any overlay icons of owncloud. Some time ago, I did.

**Comment by guruz** [comment]
About the syncs happening permanentely in a loop:
Please run the client with logfile, e.g. ```owncloud --logfile -``` on Linux or ```/Applications/owncloud.app/Contents/MacOS/owncloud --logfile -``` on OS X.
That way you should see what triggers the "next sync". Please provide us with this information.

About 2.2.1 using more CPU than 2.1.2:
if you trim down (exit the client, copy the file to a backup, remove a few of the exotic entries) the exclude list in ```sync-exclude.lst``` does it still produce so much CPU load?

**Comment by patrickhafner** [comment]
@guruz 

> @sagamusix @patrickhafner @Instinct64 Do you guys think the previous client versions were better in this regard?

Yep, because my fans were noiseless during sync until i installed the 2.2.1 update of the client. Now I can hear, when ownCloud is syncing my files :-D

**Comment by rawbertp** [comment]
Way better with 2.1.1 than 2.2.1. CPU usage back to normal with 2.1.1

**Comment by ckamm** [comment]
I did some profiling and see significantly more time spent in `csync_excluded_*` in 2.2 (47% of stack traces) vs in 2.1 (15%) in my test case. I'll investigate whether that's only due to the additions to the ignore file or for other reasons.

**Comment by guruz** [comment]
@jabdoa2 Could you please verify your sync log if you really have an empty exclude list? You should not see something like this:
```
06-02 18:09:55:829 186297 OCC::Folder::setIgnoredFiles: ==== adding system ignore list to csync: "/Users/guruz/woboq/owncloud/client/buildmirall/bin/owncloud.app/Contents/Resources/sync-exclude.lst"
06-02 18:09:55:829 0x105536b80 csync_exclude_load: Adding entry: *~
06-02 18:09:55:829 0x105536b80 csync_exclude_load: Adding entry: ~$*
06-02 18:09:55:829 0x105536b80 csync_exclude_load: Adding entry: .~lock.*
06-02 18:09:55:829 0x105536b80 csync_exclude_load: Adding entry: ~*.tmp
06-02 18:09:55:829 0x105536b80 csync_exclude_load: Adding entry: ]*.~*
*6-02 18:09:55:829 0x105536b80 csync_exclude_load: Adding entry: ]Icon
06-02 18:09:55:829 0x105536b80 csync_exclude_load: Adding entry: ].DS_Store
06-02 18:09:55:829 0x105536b80 csync_exclude_load: Adding entry: ].ds_store
06-02 18:09:55:829 0x105536b80 csync_exclude_load: Adding entry: ._*
06-02 18:09:55:829 0x105536b80 csync_exclude_load: Adding entry: ]Thumbs.db
06-02 18:09:55:829 0x105536b80 csync_exclude_load: Adding entry: desktop.ini
...
```

**Comment by jabdoa2** [comment]
@guruz looks like this:
```
06-20 14:04:34:096 0x268b460 ==== adding system ignore list to csync: "/etc/ownCloud/sync-exclude.lst"
06-20 14:04:34:096 0x268b460 ==== adding user defined ignore list to csync: "/home/xxx/.local/share/data/ownCloud/sync-exclude.lst"
06-20 14:04:34:096 0x268b460 Adding folder to Folder Map  OCC::Folder(0x2a7b9b0) "ownCloud"
06-20 14:04:34:096 0x268b460 (+) Watcher: "/home/xxx/cloud/"
06-20 14:04:35:125 0x268b460     `-> and 8644 subdirectories
```

**Comment by ckamm** [comment]
Pull request: #4988

**Comment by ckamm** [comment]
In my profiles the core problem was that the exclude list grew with each sync run. Thus each follow-up sync run took more and more time. The pull request addresses the problem by fixing the specific issue and also generally ensuring that the exclude list never contains duplicate entries.

**Comment by ckamm** [comment]
@guruz I'm pretty sure the odd lock by @jabdoa2 is from Folder construction (hence the Folder watcher message) and suspect we don't see any "Adding entry" lines because csync logging isn't properly set up at that time.

**Comment by ckamm** [comment]
@guruz Pull request to set up logging earlier: #4991

**Comment by jabdoa2** [comment]
I checked the file which are references above: /home/xxx/.local/share/data/ownCloud/sync-exclude.lst is indeed empty. However, /etc/ownCloud/sync-exclude.lst is not empty. Thus, I assume that my ignore list is also not empty.

Is that intended? I checked "Sync hidden files". Why is it still ignoring some files?

**Comment by guruz** [comment]
Everyone: 2.2.2 will be released in the next hours. Please try with that.

@jabdoa2 it is probably ignoring the files because they are still in the exclude list?

**Comment by jabdoa2** [comment]
@guruz I restarted the client. What do you mean by "still in the exclude list"? I checked "Sync hidden files" to tell the client that it should sync everything. Also how should the client (runs as user) modify /etc/ownCloud/sync-exclude.lst which is owned by root? I don't understand why there is an additional exclude list which is apparently used but not displayed and cannot be changed/viewed by the user.

**Comment by ckamm** [comment]
@jabdoa2 There is an extra exclude list that contains patterns like "*.~*" or "Thumbs.db" to skip files that people usually don't want to sync, even if they want to sync other hidden files. You can see and edit the list in General/Advanced/Edit Ignored Files.

**Comment by sagamusix** [comment]
Using the nightly build linked above, ownCloud remains using up an entire core here. I am not entirely sure if it used to be like this in 2.1.1.

**Comment by Instinct64** [comment]
I've been trying ownCloud-2.2.2.6187-nightly20160620 (Windows) for the last couple days and it seems to have resolved the issue I was seeing.

**Comment by patrickhafner** [comment]
The 2.2.2 Stable (build 3472), downloaded from official website is working for me on OS X as well. Thank you for this patch!

**Comment by dragotin** [comment]
Kudos to @guruz and @ckamm - and everybody who tested :-)
