### ISSUE TITLE
client takes roughly 24 seconds to start (show GUI or systray icon) on windows

### ISSUE THREAD

**Issue by ArthurChiao** [owncloud/client#4977]
### Expected behaviour
Client takes few seconds to launch (show GUI or systray icon) on windows.

### Actual behaviour
Clients takes roughly 24 seconds to launch (show systray icon), which seems to be abnormal.  The owncloud process is created rightly, which could be seen in windows task manager.

### Steps to reproduce
1.  Install windows client, version 2.2.1.6146
2. Double click to launch client

### Client configuration
Client version: 2.2.1.6146

Operating system: Windows 7, 64 bit

OS language: Chinese

Installation path of client: `C:\Program Files (x86)\ownCloud`

### Debug
I debugged into source code, and found that line 108 **takes 22 seconds to return**, in file `src/gui/socketapi.cpp`,
```c
 106     QFileInfo info(socketPath);
 107     if (!info.dir().exists()) {
 108         bool result = info.dir().mkpath(".");
 109         DEBUG << "creating" << info.dir().path() << result;
 110         if( result ) {
 111             QFile::setPermissions(socketPath,
 112                                   QFile::Permissions(QFile::ReadOwner+QFile::WriteOwner+QFile::ExeOwner));
 113         }
 114     }
```
it tries to create a file `\\.\pipe\ownCloud\<user name>` on windows, then creates a `QLocalServer` to listen on this file/address. And although the return result is always `false`, my client (at least seemingly) works well. 

If i hard code this line to `bool result = false;`, client will launch in 2 seconds, and everything seems fine. My question is: **what does this local socket used for? and this is a problem needs to be fixed?**

**Comment by guruz** [comment]
FYI @danimo @jturcotte @ogoffart

**Comment by guruz** [comment]
Thanks for digging so far.

I know that @danimo added another directory component in e833d01288b40ab72de9559755b05a327e923f50

Did you use previous ownCloud client versions where this did not happen?

**Comment by guruz** [comment]
@ArthurChiao The SocketApi is used for communication between the DLLs in the Explorer for showing the sync overlay icons. 

The question is indeed why does it behave like this on your machine.
Do you have any firewalls/antivirus that could cause this?

**Comment by ArthurChiao** [comment]
@guruz thanks for detailed reply!

My windows firewall is turned off and i think i have no antivirus softwares installed. I'll try more previous versions tomorrow. 

And one more question: according to the log, `bool result = info.dir().mkpath(".");` always returns `false`, but the subsequent local socket which is created to listen on this pipe returns OK,  how does this happen?

**Comment by ArthurChiao** [comment]
i tested the following history versions:

*  `ownCloud-1.7.0.4162-setup.exe`
* `ownCloud-1.8.0.4893-setup.exe`
* `ownCloud-2.0.0.5423-setup.exe`

they are all OK.

One common place of those history versions is that the `socketPath` doesn't contain the `username` part, old versions:

```cpp
socketPath = QLatin1String("\\\\.\\pipe\\") + QLatin1String("ownCloud");
```

version 2.2.1:
```cpp
socketPath = QLatin1String("\\\\.\\pipe\\") + QLatin1String("ownCloud") +
    QString::fromLocal8Bit(qgetenv("USERNAME"));
```

this was introduced in [e833d01](https://github.com/owncloud/client/commit/e833d01288b40ab72de9559755b05a327e923f50) that you've mentioned above.

If I remove `+ QString::fromLocal8Bit(qgetenv("USERNAME"))` in current source code and re-compile it, the problem will disappear.

**Comment by ckamm** [comment]
@ArthurChiao Interesting, thanks for investigating! What's `USERNAME` if I may ask? Is there something peculiar about it?

**Comment by ArthurChiao** [comment]
@ckamm , this is the booting log,
```shell
06-21 18:28:22:284 0x60ce160 OCC::Application::setupTranslations: void OCC::Application::setupTranslations() Using "zh_CN" translation
06-21 18:28:44:289 0x60ce160 OCC::SocketApi::SocketApi: SocketApi:  creating "//./pipe/ownCloud" false
06-21 18:28:44:289 0x60ce160 OCC::SocketApi::SocketApi: SocketApi:  server started, listening at  "\\.\pipe\ownCloud\zhao_yn"
```

where `zhao_yn` the `username`, but both my windows account and owncloud account use this name,  so i'm not sure which account name this variable refers to. I think it refers to windows account.

As you can see, time elapsed 22 seconds between the first line log and the second line, which is consumed by creating the pipe file folder.

More interesting parts are:

* If i change `\\` to `-`, as you advised, `bool result = info.dir().mkpath(".");` returns `false`, takes little time; where the pipe folder is not created;

* If i change the `socketPath` to `QLatin1String("E:\\.\\pipe\\") + QLatin1String("ownCloud") + '\\' QString::fromLocal8Bit(qgetenv("USERNAME"));`, it also returns directly, the result is `true`; and the pipe folder is created.

**Comment by guruz** [comment]
@ArthurChiao But it's not supposed to be on ```E:\```, it's a special Windows specific thing, it needs to match with https://github.com/owncloud/client/search?utf8=%E2%9C%93&q=DefaultPipePath
Those components connect to each other..

You can only have it working if you see the overlay icons in the Explorer..

So just ```zhao_yn```, no Kanji or similar characters?

**Comment by ckamm** [comment]
Yes, it's important that the path is a valid named pipe name on Windows (https://msdn.microsoft.com/en-us/library/windows/desktop/aa365783(v=vs.85).aspx). 

@danimo: That documentation says the pipe name mustn't include a backslash. Maybe owncloud-$username would be safer to use on Windows. It looks like creating a directory in `\\.\pipe` can take a while.

**Comment by ArthurChiao** [comment]
@guruz , the username is just `zhao_yn`, no Kanji or any other Chinese characters.

And I rarely see ovelay icons in the Explorer (accasionally i could see) in the Explorer. And further more, i built a native client binary on Ubuntu and starts it, the pipe (socket) was created correctly and returns fast, but i could not seen overlay icons in the Ubuntu synch folder, too.

**Comment by ArthurChiao** [comment]
Thanks for your links to `windows pipe`.

@guruz @ckamm I changed the `USERNAME` part to an arbitrary string, it still took 22 seconds, so it seems it's correlated to the backslash part, not the `USERNAME` part:
```
06-22 14:32:31:187 0x5e7e160 OCC::Application::setupTranslations: void OCC::Application::setupTranslations() Using "zh_CN" translation
06-22 14:32:53:203 0x5e7e160 OCC::SocketApi::SocketApi: SocketApi:  creating "//./pipe/ownCloud" false
06-22 14:32:53:203 0x5e7e160 OCC::SocketApi::SocketApi: SocketApi:  can't start server "\\.\pipe\ownCloud\justTest"
```

**Comment by ckamm** [comment]
I've tentatively created #4997 but it needs review and testing by someone more involved with the Windows SocketAPI, @jturcotte @danimo .

**Comment by guruz** [comment]
@ArthurChiao Can you also confirm your Windows Explorer shows overlay icons in your sync folders? (might need a reboot)

**Comment by guruz** [comment]
Ah just saw the comment that overlays don't work still for https://github.com/owncloud/client/pull/5007#issuecomment-228938769 ..

@ArthurChiao Did you try a reboot?
You can use https://technet.microsoft.com/en-us/sysinternals/bb896653.aspx to attach to Explorer.exe and check which OC* DLLs it loads.

You can also start the client with a ```--logfile c:\path\to\logfile.txt``` and check what it says about ```SocketApi``` (this is what it uses for overlays)

**Comment by ArthurChiao** [comment]
@guruz thanks, I'll verify this, share progress to you later.

**Comment by ArthurChiao** [comment]
A reboot doesn't work. I'm trying `process explorer`.

**Comment by guruz** [comment]
(I'm closing this because your original issue is fixed, we can still continue talking here..)

**Comment by mcastroSG** [comment]
@ArthurChiao  have you tried to uninstall, install and reboot. This works for me with [testpilotcloud-2.2.3.6210-nightly20160628-setup.exe](https://download.owncloud.com/desktop/daily/testpilotcloud-2.2.3.6210-nightly20160628-setup.exe)

**Comment by ArthurChiao** [comment]
@mcastroSG , i've tried the testpilotcloud you suggested, but still didn't work.

I guess it may be caused by some security softwares/settings on my computer, although i've turned off all i could find.

**Comment by mcastroSG** [comment]
@ArthurChiao don´t look for another cause.. It´s something related to testpilotcloud version that you have installed. I´ve tested it on W10 but with W81 or W7 overaly icons are not shown, my apologies. We need to open a new issue to follow up this new issue

**Comment by ArthurChiao** [comment]
@mcastroSG OK, thank you for preventing me from heading to the wrong direction. Let's dig into it. Any progress, i will let you know.

**Comment by mcastroSG** [comment]
Follow up overlay icons problem on [5015#](https://github.com/owncloud/client/issues/5015)
