### ISSUE TITLE
[2.2.3] [Windows XP] Progress bar not displayed properly

### ISSUE THREAD

**Issue by scriptPilot** [owncloud/client#4982]
Progress bar is not displayed properly.

ownCloud client v2.2.0, build 6076.
Windows XP

![bild 37](https://cloud.githubusercontent.com/assets/19615586/16171223/f428e6ac-3569-11e6-93f2-af05111044be.png)

**Comment by guruz** [comment]
Could you please try a nightly build of 2.2.2?
http://download.owncloud.com/desktop/daily/ownCloud-2.2.2.6182-nightly20160620-setup.exe

**Comment by scriptPilot** [comment]
Thanks, I will do so when I am back at a XP machine, hope so next week.

**Comment by scriptPilot** [comment]
After latest check yesterday with current client version, the issue still exists.

**Comment by scriptPilot** [comment]
Any news to this issue?

**Comment by guruz** [comment]
Sorry, Low in priority until some more people report it or it happens with Win8/8.1/10.

Could also be an issue in your graphics driver (or possibly remote display connection?)

**Comment by hodyroff** [comment]
Please reproduce with 2.3
