### ISSUE TITLE
MacBookPro Arbeitsspeicher 

### ISSUE THREAD

**Issue by IngoHMK** [owncloud/client#4984]
### Expected behaviour
Guten Tag,

mein Macbook Pro mit 16 GB Arbeitsspeicher kommt alle paar Minuten richtig in Stress um die Daten mit der Wolke zu synchronisieren. Es gibt aber gar nicht viel zu tun. Die Daten an sich sind alle aktuell. Es geht nur um die wenigen Änderungen.

Dummerweise ist dann der Lüfter richtig laut. Wenn ich die Synchronisation pausiere ist alles wieder gut.

Haben Sie eine Idee, wie ich das ändern kann?

Vielen Dank
Ingo Klingelheller

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system: OS X 10.11.5

Web server: 

Database:

PHP version:

ownCloud version: Version 2.2.1 (build 3427)

Storage backend:

### Client configuration
Client version:

Operating system:

OS language: deutsch

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by RealRancor** [comment]
Might be related / a duplicate: https://github.com/owncloud/client/issues/4965

**Comment by guruz** [comment]
@IngoHMK Aber nur wenn wirklich eine Datei hochgeladen/runtergeladen wird? Oder auch so alle paar Minuten wenn garnichts gesynct wird?

> Dummerweise ist dann der Lüfter richtig laut. Wenn ich die Synchronisation pausiere ist alles wieder gut.

@RealRancor I think it's more a duplicate of https://github.com/owncloud/client/issues/4967 

@IngoHMK Kannst du auf #4967 kommentieren falls du weisst ob das bei einer Vorgaengerversion noch nicht so war? Danke

**Comment by IngoHMK** [comment]
Hallo Markus,

vielen Dank für Deine Antwort

da #4967 auf englisch ist, kann ich damit nur wenig anfangen.

ja, alle paar Minuten, eher alle paar Sekunden. Egal ob ich eine Datei ändere oder nicht.
Ich nutze owncloud erst ein paar Wochen. Aber das Problem besteht von Anfang an. 
Wobei ich anfangs dachte, es liegt daran, daß ja erstmal alle Dateien hochgeladen werden müssen.

Auf meinem Windowsrechner läuft Owncloud völlig Problemlos. 

Du kannst dich auch  gerne per Teamvierer o.ä. mal auf mein MacBook schalten…

Herzliche Grüße
Ingo Klingelheller

**Comment by IngoHMK** [comment]
Danke für die Antwort.

probiere ich gleich mal aus.

nur einen folder mit vielen! Dateien. Steht irgendwo wie viele?

im Prinzip alle meine Dateien.

**Comment by IngoHMK** [comment]
habe ich probiert,
es wird damit leider nicht besser :-(

**Comment by guruz** [comment]
@IngoHMK Uff, dann hilft dir der build wohl noch nicht. Sorry.
Der war wenn man mehrere sync folder konfiguriert hat.
Momentan ist es leider noch so dass wir alle files scannen muessen auch wenn sich nur 1 geaendert hat.
Das zu fixen wird erst in Zukunft kommen -> https://github.com/owncloud/client/issues/2297

**Comment by IngoHMK** [comment]
Schade.
Gerade mache ich es so, daß ich owncloud nur mal am Abend anmache um alles zu synchronisieren. Das ist sehr lästig. Aber immerhin eine vorübergehende Lösung.
Ich hoffe also auf ein Update.
Oder könnte es helfen, wenn ich owncloud komplett neu installiere? also auch die dauen aus der library lösche?

**Comment by guruz** [comment]
@IngoHMK Du kannst den sync-folder in ownCloud client entfernen (evtl. musst du noch die ```.csync_journal.db``` Dateien im sync verzeichnis loeschen, ich glaube aber nicht).
Wenn du dann andere Unterverzeichnisse (und nur die) loeshchen willst, kannst du nur die als sync folder anlegen

**Comment by dragotin** [comment]
@IngoHMK es wäre super, wenn du den sync client mit dem Kommandozeilenparamter --logfile starten könntest, damit ein Logfile geschrieben wird, das wir dann angucken können.

Das geht zb. indem du den laufenden Client beendest und dann in einem terminal eingibst: 
```
/Applications/owncloud.app/Contents/MacOS/owncloud --logfile $HOME/owncloud.log 
```
und den Client wenige Minuten laufen lässt.

Die enstandene Datei `owncloud.log` in deinem Homeverzeichnis würde uns dann sagen, was passiert, wenn du die mit uns teilst.

**Comment by IngoHMK** [comment]
wow. Danke daß Ihr Euch so toll kümmert.

@KlaasFreitag Was meinst Du mit ’in einem Terminal’ ? ; sorry bin zwar nicht ganz doof was IT angeht, aber vieles von dem was Ihr schreibt verstehe ich selbst auf deutsch kaum :-(
