### ISSUE TITLE
sync mutiple small files from windows client to server, slow and every time 3 files uploaded

### ISSUE THREAD

**Issue by joeyjy** [owncloud/client#4986]
### Expected behaviour
upload smoothly as single file

### Actual behaviour
upload slow and every time 3 objects uploaded (according to the log)

### Steps to reproduce
1. move a folder contains 100 small files to owncloud sync dir

### Server configuration
Operating system: centos7.0

Web server: apache 2.4

Database: MariaDB 5.5

PHP version: PHP 5.4.16 (cli)

ownCloud version: 9.0.1 (with encryption)

Storage backend: ceph object storage

### Client configuration
Client version: 2.2

Operating system: window7 basic

OS language: Chinese

Installation path of client: C:\Program Files (x86)

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

Hi OC team,

I want to know if the encryption process is simultaneous when handling multiple files? or it only encrypts file one by one?
I notice that when sync big file, it uses chunk uploading, 10M for each chunk and send the chunk to object storage first, when all  the file is uploaded, OC gets all the chunks from object storage, combines them, encrypts the file, finally sends the complete to object storage.

**Comment by guruz** [comment]
Each file is an independent HTTP request (for small files). So it indeed happens one by one.

Does this answer your question?

**Comment by joeyjy** [comment]
@guruz thank you for reply!
I see, so, multiple REQUESTS will be sent to the server at one time, can we config the number?

**Comment by guruz** [comment]
@joeyjy You can increase it to a maximum of 5 with the environment variable ```OWNCLOUD_MAX_PARALLEL=5```.

Note to self: Maybe we should do the auto-scaling also for uploads in 2.3 (https://github.com/owncloud/client/pull/4529)

**Comment by joeyjy** [comment]
@guruz Thanks! I also noticed that "if !max max = 3" in the client source code.

**Comment by fossxplorer** [comment]
@joeyjy 
btw, as to your comment "I notice that when sync big file, it uses chunk uploading, 10M for each chunk and send the chunk to object storage first, when all the file is uploaded, OC gets all the chunks from object storage, combines them, encrypts the file, finally sends the complete to object storage".
The reason you are seeing the chunks being sent to the object storage is that the default cache folder where chunks are temporarily stored reside inside data/<username>/cache. This can be specified in the config.php to be a different path, e.g on a faster SSD. Look inside config.php.sample for the config directive name.

Also, i'm very curious about the CEPH storage backend you use with oC. Can you provide more details about it? :) My email is fossxplorer@gmail.com. Thx!

**Comment by joeyjy** [comment]
@fossxplorer Hi! Thanks for the explanation! I'm consider changing my local disk to SSD now.

What details about CEPH can I shared to you? My CEPH is a general cluster which contains 3 servers.
looking forward to hearing from you :)
