### ISSUE TITLE
Cannot build owncloud-client-l10n for Fedora23 and Ubuntu 16.04

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#4987]
This worked for Fedora21 Fedora22. With Fedora23 we have 

<pre>
nothing provides qt5-linguist = 5.5.0-4.fc23 needed by qt5-qttools-devel, nothing provides qt5-qhelpgenerator = 5.5.0-4.fc23 needed by qt5-qttools-devel, nothing provides qt5-designer = 5.5.0-4.fc23 needed by qt5-qttools-devel
</pre>

After workarounding this issue, cmake detects there is no Qt5LinguistTools and we end up without localization.

Fedora23 currently build without localization so that we can build at all.

Suggested fix: build the localization files at commit time, not at packaging time.
@dragotin @danimo @michaelstingl

**Comment by jnweiger** [comment]
https://github.com/owncloud/administration/commit/6616b277129ac10e5303761ab0a2a44e95dfc748

**Comment by jnweiger** [comment]
Same Issue seen on Ubuntu 16.04
There we provide a dummy english localization. 
https://github.com/owncloud/administration/commit/3d8815b3d4a8c004ed8927a748c4e9e514f08330

**Comment by jnweiger** [comment]
Workaround: we ship a prebuilt l10n.zip archive.

**Comment by michaelstingl** [comment]
@jnweiger Does this require any user interaction?

**Comment by jnweiger** [comment]
no. same files end up in same places than before.

**Comment by michaelstingl** [comment]
sounds great

**Comment by jnweiger** [comment]
Note to self: Fedora 23 *can* build localization, if we *dont* BuildRequires:  qt5-qttools-libs-designercomponents qt5-qttools-libs-designer

**Comment by jnweiger** [comment]
Localization works again with Fedora 25
