### ISSUE TITLE
[Win][v2.2.2][Regression] HiDPI not working

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#4994]
### 2.1.1

<img width="711" alt="211-server" src="https://cloud.githubusercontent.com/assets/214010/16230436/b9ce3872-37c1-11e6-99ac-6f38a4108959.png">
<img width="726" alt="211-credentials" src="https://cloud.githubusercontent.com/assets/214010/16230437/b9cf8222-37c1-11e6-81c2-17e0ee75dfc4.png">

### 2.2.2

<img width="464" alt="221-server" src="https://cloud.githubusercontent.com/assets/214010/16230448/c8d8fdac-37c1-11e6-9b49-dbe4d8f1058a.png">
<img width="433" alt="221-credentials" src="https://cloud.githubusercontent.com/assets/214010/16230449/c8d95edc-37c1-11e6-87d4-f19700d72f06.png">

### Expected behaviour
HiDPI under Windows would be very beautiful

### Actual behaviour
HiDPI seems to not work

### Steps to reproduce
1. Run Win VM (modern.ie) in VMware Fusion 8.1.1 on Retina MBP 15"
2. Install ownCloud-2.2.2.6192-setup.exe
3. Start ownCloud client and configure account

### Client configuration
Client version:
v2.2.2

Operating system:
Win 8.1 32-bit

OS language:
eng

**Comment by guruz** [comment]
@danimo removed the ```qputenv("QT_DEVICE_PIXEL_RATIO", "auto");``` call in 0194ebb2229adc33f5b9790231a3384b46474bde
This was for https://github.com/owncloud/client/issues/4840 which only is reported on Linux?

The patch 6ccd9e872d53f5a7b3ce2d82be0c0e2d99c013f7 by @ogoffart might not matter (even though the comment at the ```#endif``` is wrong)

**Comment by ckamm** [comment]
@michaelstingl Do you get the correct behavior if you set the `QT_DEVICE_PIXEL_RATIO` environment variable to `auto`?

**Comment by michaelstingl** [comment]
@ckamm I've only little Windows experience. Where/how can I set the QT_DEVICE_PIXEL_RATIO environment variable to auto?

**Comment by ckamm** [comment]
@michaelstingl I think this is one way: Run `cmd`.
```
$ set QT_DEVICE_PIXEL_RATIO=auto
$ "C:\Program Files (x86)\ownCloud\owncloud.exe"
```
The actual path to the owncloud binary may be different for you.

**Comment by michaelstingl** [comment]
@ckamm cool, after setting environment variable and starting owncloud.exe from Command Prompt, it looks better:

<img width="745" alt="downloads_and_ie11_-_win8_1" src="https://cloud.githubusercontent.com/assets/214010/16274663/df8ab5fa-38a6-11e6-98f1-4597f774e45a.png">

Starting it with doubleclick from the desktop makes it broken again.

**Comment by ckamm** [comment]
@danimo  Pull request: https://github.com/owncloud/client/pull/4998

**Comment by guruz** [comment]
Fixed as per https://github.com/owncloud/client/pull/4998#issuecomment-228993213
thanks @ckamm 

Also tested OS X on my MBP Retina, looks fine.
