### ISSUE TITLE
[FedShare] Can share permission are not granted for folders by default in case of FedShare

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#4996]
### Expected behaviour
"Can Share" permission should be granted by default in case of fedshare for folders

### Actual behaviour
To grant "Can Share" permission, we have to uncheck and check "can edit" checkbox. 

### Steps to reproduce
1. As user A connected to server A right click over folder1 on Shared sync folder
2. Choose "Share with owncloud" option
3. Type userb@serverb and wait till operation ends
4. As user B connected to server B right click over folder1 that has been previously synced from server
5. Choose "Share with owncloud" option

A new message saying that you are not able to reshare is shown

### Server configuration

Server OS: Ubuntu 14.04
Server Version: 9.1.0 Beta

### Client configuration

Client OS: OSX El capitán 10.11.5
Client Version: Version 2.2.2 (build 3472)

**Comment by ckamm** [comment]
My current analysis is: due to https://github.com/owncloud/core/issues/22122#issuecomment-185637344 we explicitly removed reshare permissions in e4ec09dd874bd84e913d7e22c801b691537d4297. But then https://github.com/owncloud/core/pull/23918 happened and now we might need to send reshare permissions again. Needs more testing.

**Comment by ckamm** [comment]
I've tested this with 9.1.0beta1 and the server does indeed create federated shares that /include/ the reshare permission. @rullzer Do we need to preserve the 9.0 behavior of not creating federated shares with reshare permissions?

**Comment by SergioBertolinSG** [comment]
cc @PVince81

**Comment by PVince81** [comment]
From what I remember, in OC < 9.0 we didn't want to introduce a change of behavior, so there the permissions were "automatic" and not really CRUDS.

Then in 9.1 with https://github.com/owncloud/core/pull/23918 we introduced CRUDS for federated shares. When you share in the web UI with a user user1@localhost/owncloud, you have the ability to set CRUDS permissions, including reshare. This means the permissions are explicit.

The clients should align on that for 9.1.

**Comment by PVince81** [comment]
Okay, I'm starting to remember... it's a bit messy.

From my understanding the clients would need to do as follows:
- if OC < 9.1: send 1 for readonly permissions, or 7 for readwrite (others will be rejected by the API)
- if OC >= 9.1: send more granular permissions as needed: readonly 1, readwrite 15, readonly + share 17, readwrite + share 31. Not sure what options the GUI shows ?

Also see https://github.com/owncloud/core/issues/24868#issuecomment-227776832

**Comment by PVince81** [comment]
and this is for federated shares.

For link shares it's another story I'm still trying to figure out in https://github.com/owncloud/core/issues/24868#issuecomment-227768360...

@rullzer would be good if you could help clarify a bit

**Comment by PVince81** [comment]
Since we are only talking about federated shares, see https://github.com/owncloud/core/issues/22122#issuecomment-227793183

**Comment by ckamm** [comment]
@PVince81 Proposal: 
* I won't touch the way the client talks to <9.1 servers for federated shares, even though I think it sends 1 (readonly) or 3 (for files, read+update) or 15 (for folders, read+update+create+delete).
* When talking to a 9.1 server, I'll expose the full permissions again and also include the reshare permission by default.

**Comment by rullzer** [comment]
Yes I limited them explicitly because that was the server behaviour in 9.0 as well. 9.1 server should behave better and there federated shares are the exact same (for the client) as normal shares.

**Comment by PVince81** [comment]
@ckamm ok I agree with what you said in https://github.com/owncloud/core/issues/22122#issuecomment-228028647

Also see https://github.com/owncloud/core/issues/22122#issuecomment-228028647 for making mobile consistent with this

**Comment by ckamm** [comment]
Pull request: https://github.com/owncloud/client/pull/5001

**Comment by mcastroSG** [comment]
Have made some test and seems to be working but still some extra reg test has to be made to be sure nothing is broken with this change

**Comment by mcastroSG** [comment]
### Desktop Client FedShare Reg

Client Version: 2.2.3

<br>
 
Test Case ID | Test case     | Steps   | Expected behavior | Result | Related Comments
|:----:|:------------- |:-------------------|:-------------|:-------------:|:----------
1 | Fed Share reg - Share a folder "can share" | 1.- As user1 connected to server A share a folder with a user2 that exists at server B granting "can share"<br>2.- As user2 connected to server B accept shared folder<br>3.- As user2 right-click on shared folder <br> 4.- Select "Share with ownCloud" option <br> 5.- Fill user field with user3@serverC and select <br> | "can share" checkbox is available | ✅ 
2 | Fed Share reg - Share a folder "can edit" | 1.- As user1 connected to server A share a folder with a user2 that exists at server B granting "can edit" and "can share"<br>2.- As user2 connected to server B accept shared folder <br>3.- As user2 right-click on shared folder <br> 4.- Select "Share with ownCloud" option <br> 5.- Fill user field with user3@serverC and select | "can edit" checkbox is available |  ✅ 
3 | Fed Share reg - Share a folder unchecked "can share" | 1.- As user1 connected to server A share a folder with a user2 that exists at server B unchecking "can share"<br> 2.- As user2 connected to server B accept shared folder <br> 3.- As user2 right-click on shared folder <br>4.- Select "Share with ownCloud" option <br> | An error message appears because you are not able to reshare the file |  ✅ 
4 | Fed Share reg - Share a folder unchecked "can edit" | 1.- As user1 connected to server A share a folder with a user2 that exists at server B unchecking "can edit" and checking "can share"<br>2.- As user2 connected to server B accept shared folder <br> 3.- As user2 right-click on shared folder <br> 4.- Select "Share with ownCloud" option <br> | "can edit" checkbox is not available  |  ✅  |
5 | Fed Share reg - Share a file "can share" | 1.- As user1 connected to server A share a file with a user2 that exists at server B granting "can share"<br>2.- As user2 connected to server B accept shared file <br> 3.- As user2 right-click on shared file <br> 4.- Select "Share with ownCloud" option <br> 5.- Fill user field with user3@serverC and select <br> | "can share" checkbox is available | ✅
6 | Fed Share reg - Share a file "can edit" |1.- As user1 connected to server A share a file with a user2 that exists at server B granting "can edit" and "can share"<br>2.- As user2 connected to server B accept shared file <br>3.- As user2 right-click on shared file <br> 4.- Select "Share with ownCloud" option <br> 5.- Fill user field with user3@serverC and select | "can edit" checkbox is available |  ✅
7 | Fed Share reg - Share a file unchecked "can share" | 1.- As user1 connected to server A share a file with a user2 that exists at server B unchecking "can share"<br> 2.- As user2 connected to server B accept shared file <br> 3.- As user2 right-click on shared file <br>4.- Select "Share with ownCloud" option <br>  | An error message appears because you are not able to reshare the file |  ✅
8 | Fed Share reg - Share a file unchecked "can edit" |  1.- As user1 connected to server A share a file with a user2 that exists at server B unchecking "can edit" and checking "can share"<br>2.- As user2 connected to server B accept shared file <br> 3.- As user2 right-click on shared file <br> 4.- Select "Share with ownCloud" option <br> |  "can edit" checkbox is not available  |  ✅


Client OS: OSX 10.11.5 El capitán
Client Version:Version 2.2.3-nightly20160630 (build 3495)

Client OS: Windows10
Client Version: 2.2.3-nightly20160630 (build 6215)

Client OS: Ubuntu 16.04 LTE
Client Version: Version 2.2.3nightly2016630 (build 1731)

Servers OS: Ubuntu 14
Servers Version: 9.1.0 beta 2
