### ISSUE TITLE
QT_AUTO_SCREEN_SCREEN_SCALE_FACTOR is explicitly set and it should not be

### ISSUE THREAD

**Issue by davidedmundson** [owncloud/client#5000]
#if QT_VERSION >= QT_VERSION_CHECK(5, 6, 0)
    qputenv("QT_AUTO_SCREEN_SCALE_FACTOR", "1");
#endif

You can't rely on screen DPI there are a huge bunch of samsung monitors that get mm and inches swapped so the auto DPI is huge. I do the Plasma High DPI and we don't use this because the feedback we got is that it simply doesn't work.

Also it messes with Plasma which manually sets the scale factor based on the user's settings. 

There is an alternate method to acheive the same result for you.
qApp->setAttribute(Qt::AA_EnableHighDpiScaling, true);

This will act the same as the above line *if and only if* no other env vars are set.

**Comment by davidedmundson** [comment]
Edit. that was in an Q_OS_WINDOWS.. and I still have problems... 

Closing, sorry for the noise.

**Comment by guruz** [comment]
FYI we just merged https://github.com/owncloud/client/pull/4998

**Comment by davidedmundson** [comment]
Ack. It did fix the problem.

I managed to git pull between starting and finishing writing the report.

Thanks.
