### ISSUE TITLE
client does not distinguish 8.2 from 9.0 regarding server notifications api

### ISSUE THREAD

**Issue by butonic** [owncloud/client#5002]
The 2.2.2 client always uses ocs/v2.php/apps/notifications/api/v1/notifications?format=json to fetch notifications regardless of server version. That endpoint is not available in 8.2, leading to this error in the client log:
```
OCC::JsonApiJob created for "https://hostname.tld/owncloud" + "ocs/v2.php/apps/notifications/api/v1/notifications" "OCC::ServerNotificationHandler" 
06-22 12:52:04:404 0x7057a98 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 401 "Error downloading https://hostname.tld/owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json - server replied: Internal Server Error" QVariant(int, 500) 
06-22 12:52:04:406 0x7057a98 OCC::JsonApiJob::finished: Network error: "ocs/v2.php/apps/notifications/api/v1/notifications" "Error downloading https://hostname.tld/owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json - server replied: Internal Server Error" QVariant(int, 500)
```

The capabilities returned by the call to ocs/v1.php/cloud/capabilities:
```
8.2: ( "notifications" ,  QVariant(QVariantMap, QMap(("endpoints", QVariant(QVariantList, (QVariant(QString, "get") ,  QVariant(QString, "delete") ) ) ) ) ) ) )
9.0: ( "notifications" ,  QVariant(QVariantMap, QMap(("ocs-endpoints", QVariant(QVariantList, (QVariant(QString, "list") ,  QVariant(QString, "get") ,  QVariant(QString, "delete") ) ) ) ) ) ) )
```
Both announce 'notifications' but with different values.

@ckamm @dragotin Maybe the client does not check the 'ocs-endpoints' key?

**Comment by dragotin** [comment]
Correct analysis, client 2.2.2 reads from the constant url:
https://github.com/owncloud/client/blob/master/src/gui/servernotificationhandler.cpp#L49

That's uncool. @ogoffart @ckamm can you fix that? Thanks.

**Comment by ogoffart** [comment]
What endpoint should we query in 8.2, if any?

**Comment by ckamm** [comment]
Isn't this the same as #5033 which danimo adressed in 8a1a2eb by making `notificationsAvailable()` false for 8.2?

**Comment by guruz** [comment]
^^ @ckamm 's question

**Comment by ogoffart** [comment]
Yes it's the same,  hence the ReadyToTest

**Comment by mcastroSG** [comment]
Hi hi:

I´m able to reproduce this issue with current 2.2.2 version. In new versions it seems to be solved because there is no trace about Network Error.

Client OS: W10
Client Version: 2.2.3-nightly20160714 (build 6247)

Client OS: OSX El capitán 10.11.5
Client Version: Version 2.2.3-nightly20160714 (build 3525)

**Comment by guruz** [comment]
thanks for testing :)
