### ISSUE TITLE
Update the Linux repo for Fedora 24

### ISSUE THREAD

**Issue by Paviluf** [owncloud/client#5003]
Hello,

Is it possible to update the Linux repo for Fedora 24 please ?

https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

Thanks !

**Comment by jnweiger** [comment]
Added Fedora24 to :nightly :testing: :desktop projects. Packages should appear later today.
Thanks.
Removed Fedora21 -- no longer supported in OBS.

**Comment by jnweiger** [comment]
We have a build error:
[  376s] error: File not found: /home/abuild/rpmbuild/BUILDROOT/owncloud-client-2.2.2-13.1.x86_64/usr/lib64/qt5/plugins/*dolphinactionplugin.so

**Comment by dragotin** [comment]
That means that the package can not buidl the dolphin plugin but it thinks it should. 

Either the KDE Frameworks version is smaller than 5.16 OR the according KDE frameworks packages are not installed in the build environment.

**Comment by jnweiger** [comment]
Fedora 24 has KF5 5.22 -- we need minimum 5.16 for the dolphin plugin. So it "could" be the first Fedora release featuring a dolphin plugin! Investigating.

Nevertheless, I'll trigger a build with dolphin disabled, to check for other issues meanwhile.

**Comment by jnweiger** [comment]
Fixed with https://github.com/owncloud/administration/commit/688133b1879512e5ce30c691e2c3c546bd006854

**Comment by Paviluf** [comment]
Thank you very much !
