### ISSUE TITLE
[Windows] [2.2.2] ownCloud stops synchronisation when uploading a file, with a long file name, fails: "Connection Closed"

### ISSUE THREAD

**Issue by N-ik05** [owncloud/client#5004]
### Expected behaviour
Desktop client warning about length of file and stop synchronising that file and continue with the other files.

Or fail synchronisation of the one file and then first continue with the other files before trying again.

### Actual behaviour
Keeps trying to synchronise file with a too long name but fails.
"Connection closed" on the file that fails and "Operation cancelled" on remaining files.
Others files don't get synchronised.

### Steps to reproduce
1. Copy multiple files to the synchronised directory of which one or more have a file name length of 150 or more.

### Server configuration
TransIP Stack, sorry now idea what they are running.

### Client configuration
Client version:
2.2.2 (build 6192)

Operating system:
Windows 10 64bit

OS language:
English

Installation path of client:
D:\ownCloud\

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
https://gist.github.com/N-ik05/3d793371488f22a94ec763bbdbd34d82

2. Web server error log: 
no access too

3. ownCloud log (data/owncloud.log):
I hope this is the correct one
https://gist.github.com/N-ik05/3d793371488f22a94ec763bbdbd34d82

**Comment by guruz** [comment]
Which server version?
You should contact TransIP about this, it's probably a configuration/server issue.

**Comment by N-ik05** [comment]
Looks like they got a custom server, which has a filename character limit of 148. And the server closes the connection when uploading a file that goes over that limit.

I expect that handling the order of uploading file can not be changes when getting such an error. So I will close the issue.

Thank you

**Comment by guruz** [comment]
Good to hear. Ideally they should send a 403 error though, maybe you could tell them that.
