### ISSUE TITLE
upload large file to owncloud cluster using client

### ISSUE THREAD

**Issue by joeyjy** [owncloud/client#5005]
### Expected behaviour
upload smoothly

### Actual behaviour
when upload finished, process were combining chuncks, client pops out an error says like "can not find last part of the file, can not find E-tag"

### Steps to reproduce
1. mv a large file bigger than 2GB into sync folder

### Server configuration
Operating system: centos 7.0

Web server: apache 2.4

Database: mysql 

PHP version: 5.4

ownCloud version: 9.0.1

Storage backend: Ceph

### Client configuration
Client version: 2.2.1

Operating system: window 7 basic

OS language: Chinese

Installation path of client: 

Hi OC,

I set up owncloud on two servers, these two server are in same cluster (load balance), When I use client to sync large file, after uploading finished ,it wait for several seconds then gives an error, saying something like "can not find last part of the file, can not find E-tag", need your help...

**Comment by guruz** [comment]
The ownCloud servers need to share DB, PHP session storage and underlying storage for the ```.part``` files.

You should try to get support via https://doc.owncloud.org/server/9.0/admin_manual/operations/scaling_multiple_machines.html and https://owncloud.org/support

Please close this issue if this helps.

**Comment by joeyjy** [comment]
@guruz Thanks for reply! Is **'underlying storage for the .part files'** means php file uploading tmp folder on my two servers also need to be shared?

**Comment by joeyjy** [comment]
@guruz I have db shared, redis session shared, so I need /tmp (php default upload temp folder) to be  nowshared, am I right？

**Comment by guruz** [comment]
I think it's more like the one specified in https://github.com/owncloud/core/blob/master/config/config.sample.php#L971

**Comment by joeyjy** [comment]
@guruz I already use Ceph rgw for all the storage, users' cache folder is also on Ceph, this error occurred when uploading is finished, client waiting for server completing combining chunks into one file, if I pause sync in client at that moment, and then turn on sync after server combining process completed, erverything is ok, no error pop out anymore, can you give some advice？Thank you very much！
