### ISSUE TITLE
Error loading file, popup display %1 instead of filename

### ISSUE THREAD

**Issue by effemmeffe** [owncloud/client#5006]
### Expected behaviour
Display the file name with problem

### Actual behaviour
The popup displays %1 instead of the filename

### Steps to reproduce
1. pu a bunch of files on some folder on your PC
2. wait for them to be loaded by the desktop app
3. pop up shows displaying %1 instead of the filename: http://i.imgur.com/sP8yXhD.png

### Server configuration
Operating system:
ubuntu 14.04 TLS

Web server: 
apache 2

Database:
MySQL

PHP version:
5.5.9-1ubuntu4.17

ownCloud version:
9.0

Storage backend:

### Client configuration
Client version:
2.2

Operating system:
windows 19

OS language:
ITA

Installation path of client:
C:\Program Files (x86)\ownCloud

**Comment by guruz** [comment]
> Client version: 2.2

Please retry with 2.2.2 and re-open if needed.
