### ISSUE TITLE
[OS X 10.11.5] Darkmode - toolbar with weird dark background

### ISSUE THREAD

**Issue by Marvo2011** [owncloud/client#5012]
### Expected behavior
When the OS X darkmode is activated, then the Client will have a black head.

### Steps to reproduce
1. activate OS X darkmode 
2. start OwnCloud client

### Client configuration
Client version: 2.2.1-nightly20160530
Operating system: OS X 10.11.5 
OS language: German

![bildschirmfoto 2016-06-28 um 12 19 07](https://cloud.githubusercontent.com/assets/6094055/16412106/cce807d0-3d2a-11e6-8fab-b8367f0224ec.png)

**Comment by guruz** [comment]
@luciamaestro reminds me of something..

**Comment by guruz** [comment]
I'm still on 10.11.5, maybe something for @jturcotte ?

**Comment by mcastroSG** [comment]
I´m on 10.11.5 and I´m not able to reproduce the issue with latest build. @Marvo2011 could you please retest with [testpilotcloud-2.2.3.6210-nightly20160628-setup.exe](https://download.owncloud.com/desktop/daily/testpilotcloud-2.2.3.6210-nightly20160628-setup.exe)

**Comment by dragotin** [comment]
checking this will need the mac osx build:
https://download.owncloud.com/desktop/daily/testpilotcloud-2.2.3.3489-nightly20160628.pkg

**Comment by mcastroSG** [comment]
@dragotin sure (facepalm) 😓

**Comment by Marvo2011** [comment]
It works with 2.2.2 (build 3472). https://download.owncloud.com/desktop/daily/testpilotcloud-2.2.3.3489-nightly20160628.pkg is not installable.

**Comment by mcastroSG** [comment]
@Marvo2011 may you try with [testpilot](https://download.owncloud.com/desktop/daily/testpilotcloud-2.2.3.3495-nightly20160630.pkg) ¿?

**Comment by Marvo2011** [comment]
It also works with 2.2.3-nightly20160630. Thanks. 
The Issue seems fixed with 2.2.2
