### ISSUE TITLE
Read-only state change between Mac OS X Yosemite and Windows 7

### ISSUE THREAD

**Issue by cdellafera** [owncloud/client#5018]
### Expected behaviour

I would expect that when I change the read-only status of a file on the file system of one of my computers, either Mac OS X (Yosemite) system or Windows 7, that this status would be correctly set on the other platform's file system.
If this is the expected behavior, I at least need a mechanism to properly resync the two platforms when they have become out of sync as they are now.
### Actual behaviour

I seem to be in a read-only status war. When I set the read-only status for a file on one file system, it flips the state on the other. For example, I would like to clear the read-only status for a set of files on one system (e.g., Mac OS X Yosemite) and have it also clear the read-only status on the other system (Windows 7).
### Steps to reproduce
1. Change a file on one system (e.g., Mac OS X Yosemite) to read-only
2. Note that the file on the other system (e.g. Windows 7) has been flipped to the other state.
3. Note that this isn't respecting the desire for "read-only" versus "not read-only"
### Server configuration

Operating system:
- Window Server ??

Web server: 
- Unknown 
- Firefox 47.0.1
- IE 11.0.31

Database:
- Unknown

PHP version:
- Unknown

ownCloud version:
- Version 6.0.5.1

Storage backend:
- Unknown
### Client configuration

Client version:
- 2.2.2.6192

Operating system:
- Window 7
- Mac OS X Yosemite

OS language:

Installation path of client:
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   (On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
   (See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
2. Web server error log:
3. ownCloud log (data/owncloud.log):

**Comment by hodyroff** [comment]
Please reproduce with client 2.3 and server 9.1.4+
