### ISSUE TITLE
States of the lock icon

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#5020]
![client6 2](https://cloud.githubusercontent.com/assets/214010/16483179/89a4558e-3eb3-11e6-8bd0-537db54bd5c7.png)

What are the possible states of the lock icon and what does they mean?

I found 2 different lock icons in the resources folder:

![lock-http 2x](https://cloud.githubusercontent.com/assets/214010/16483333/40d52c88-3eb4-11e6-8d8b-4f9adf68733d.png)

![lock-https 2x](https://cloud.githubusercontent.com/assets/214010/16483332/40d3a08e-3eb4-11e6-8662-ff40bbfe29ff.png)

@dragotin Could you help?

00005783

**Comment by danimo** [comment]
![](https://cloud.githubusercontent.com/assets/214010/16483333/40d52c88-3eb4-11e6-8d8b-4f9adf68733d.png) -> Unencrypted

![](https://cloud.githubusercontent.com/assets/214010/16483332/40d3a08e-3eb4-11e6-8662-ff40bbfe29ff.png) -> Encrypted

Like in any browser.

**Comment by danimo** [comment]
Btw: If you hover over the icon will will explain it to you :)

**Comment by michaelstingl** [comment]
@danimo Thanks! I just wanted to make sure there are no other states I'm not aware of.

**Comment by dasong** [comment]
Thanks @danimo @michaelstingl
