### ISSUE TITLE
[TokenAuth] We need some documentation about Token Auth on Desktop Client Side

### ISSUE THREAD

**Issue by mcastroSG** [owncloud/client#5021]
Pending get documentation for Token Auth

**Comment by settermjd** [comment]
@PVince81 @DeepDiver1975 can you provide further information please?

**Comment by PVince81** [comment]
This is partly obsolete because we decided to go with OAuth2 instead of the proprietary token auth we currently have.

https://github.com/owncloud/core/issues/10400
