### ISSUE TITLE
Share link in share dialog does not use proper http:// vs https://

### ISSUE THREAD

**Issue by bah0071** [owncloud/client#5022]
when in the owncloud share folder we should  be able to share directly by rightclicking "share with owncloud"
this option is no longer available since update 2.2.2

also the icons showng sync (green check and blue dot) no longer appear... the folder looks like a regular folder

also i noticed before that with 2.2.1 when i was sharing with owncloud by link it would constantly give me an HTTPS link while my server was not set up for it...should have the option to make the link https or not (in the application general setting and int he share window)
### Actual behaviour

no option available
### Steps to reproduce
1. right click on folder/file
2. 
3. 
### Server configuration

Operating system: 

Web server: apache

Database: mysql

PHP version:

ownCloud version: 9.2

Storage backend:
### Client configuration

Client version: 2.2.2

Operating system:windows 10 64 bit

OS language:english

Installation path of client: 
### Logs

n logs on this issue

**Comment by dragotin** [comment]
Have you rebooted?

**Comment by bah0071** [comment]
Ah OK now it works :)

But the share link is still in https...

Gets annoying as I need to remove the s all the time


On June 30, 2016 11:40:22 AM EDT, Klaas Freitag <notifications@github.com> wrote:
>Have you rebooted?
>
>---
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/client/issues/5022#issuecomment-229698684

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by ckamm** [comment]
@bah0071 I tested the share link with a server that doesn't use SSL. For me, the share link correctly says "http://...".

The client uses the share link that the server reports for the share. Is your server configured for a "https://" url?

**Comment by bah0071** [comment]
my server is configured for http

here is the sharel link on the website itself


but on the ownlcoud share



also another note, when sharing docx files with %20 in the name it does 
not create a download link


--
Benjamin-Avi Hadid

On 7/5/2016 6:32 AM, ckamm wrote:
>
> @bah0071 <https://github.com/bah0071> I tested the share link with a 
> server that doesn't use SSL. For me, the share link correctly says 
> "http://...".
>
> The client uses the share link that the server reports for the share. 
> Is your server configured for a "https://" url?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/owncloud/client/issues/5022#issuecomment-230443759>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AMXcgbfG9A5iTaC1NE-nKLRlgmx7maauks5qSjK2gaJpZM4JCSQp>.
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by ckamm** [comment]
@bah0071 It looks like parts of your message got lost! :/  Could you repeate yourself?

**Comment by hodyroff** [comment]
No further info provided, no further reports of the issue. https should be used anyway. Closing.
