### ISSUE TITLE
Problem with quota and parallel chunked uploads

### ISSUE THREAD

**Issue by daorte** [owncloud/client#5027]
### Steps to reproduce
1. Limit the disk quota for user "test" to 45MB
2. Put 3 files of 42MB in synced folder
### Actual behaviour
1. The Desktop application starts the upload of the 3 files simultaneously in chunked pieces of 10MB
2. When one of the files ends its own upload (last chuck processed) the available quota is updated and then the other two files are rejected with InsufficientStorageException, but at this point, the desktop application sents a lot of chunked pieces of the rejected files, consuming resources for failed uploads.
3. If two or more files sends its last chunk at the exact same time, they can break the limit and get uploaded completely.
4. Extrapolates this situation for a 10GB user quota and 3 files of 9.8GB each, is a lot of resources wasted for failing uploads

![captura](https://cloud.githubusercontent.com/assets/1828874/16520628/9df628b2-3f91-11e6-9a87-ee28e08d4fcb.PNG)
### Expected behaviour
- Maybe the Desktop client can notify OwnCloud  with all pending files and its sizes, and the core accept or reject files of that list, and start the sync process only for the accepted ones.
### Server configuration

Web server: Apache 2.4
Database: MySQL
PHP version: 7
OwnCloud: 9.0.2.2
### Client configuration

Client version: 2.2.1 (Mozilla/5.0 (Windows) mirall/2.2.1 (build 6146))
Operating system: Windows 8.1
OS language: Spanish

**Comment by mcastroSG** [comment]
@daorte I´m agree with you , but designers has to take this in to consideration :question: @guruz @dragotin

**Comment by daorte** [comment]
@mcastroSG of course, the proposed behavior is that, just a proposal.
But the upload of the 2 files exceeding the quota IMHO is a bug, that's why i attached the picture

**Comment by fmoc** [comment]
The file uploading has been changed since and there is a chance this issue has been solved a while ago. If not, please don't hesitate to reopen this issue.
