### ISSUE TITLE
[2.2.2] Gnome shell freeze during sync

### ISSUE THREAD

**Issue by ArthurGarnier** [owncloud/client#5028]
### Expected behaviour
Sync must be unnoticeable for user experience

### Actual behaviour
On each sync all my screen (except the mouse) freeze. All come back after few second. I have to pause the sync to avoid this behavior. 

### Steps to reproduce
Don't know... 
I thought that fs.inotify.max_user_watches was in fault but after a restore to default (50000 -> 8192) still not work. 

### Server configuration
Operating system: Debian Jessie, Kernel 4.5.2

Web server: Apache 2.4.20

Database: Postgres 9.5.3

PHP version: 7.0.7

ownCloud version: 9.0.2

Storage backend: HDD Local, RAID 1

### Client configuration
Client version: 2.2.2

Operating system: ArchLinux Kernel 4.6.3

OS language: Fr

Installation path of client: /usr/bin/owncloud

### Logs

1. Logs are about 60Mo so I have to host the file : https://arthurgarnier.fr/owncloud/s/dEUTHQ60XopoNyv

2. Web server error log: No problem here

3. ownCloud log (data/owncloud.log): No problem here

**Comment by guruz** [comment]
How many files/folders are there in each sync folder?

FYI @jturcotte @dragotin

**Comment by ArthurGarnier** [comment]
~38000 files in total on the computer concerned

**Comment by ArthurGarnier** [comment]
Still here in 2.2.3 with Gnome Shell 3.20

I catch a new log with less useless information and just keep what happened during the freeze at 14:20:40 : http://pastebin.com/cSHsfS3E

In fact seem due to lot's of ignored files 

```
08-22 14:20:40:061 7330 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "IUT/A2/S3/Complément Java/Projets/.git" INSTRUCTION_IGNORE 6 "Le fichier est dans la liste des fichiers à ignorer."
```

In english ~="The file is in the ignore files list"

This instruction appears lot of times (1441 times for one sync !)

**Comment by jturcotte** [comment]
> This instruction appears lot of times (1441 times for one sync !)

This could mean that something opened 1441 connection through the socket API! I'm not sure how to disable overlay icons for nautilus, but could you try that?

Maybe @ckamm has an idea.

**Comment by jturcotte** [comment]
Wait no, strike that, it's different files, they're all ignored, and we'll send all those messages to the nautilus plugin regardless of whether the status changed or not (was ignored, stayed ignored, we shouldn't re-send the status). Would be nice to confirm if disabling the overlay icon helps, it could also be the tray icon update that causes the blocking.

**Comment by ArthurGarnier** [comment]
I tried to disable the Nautilus API (uninstall python2-nautilus), no effect

But I don't know how to disable the overlay icon ? In owncloud-client I can just set "monochrome"  icon. 
But indeed, when the UI freeze, the Icon disappear and when the UI answers again, the icon back...

**Comment by jturcotte** [comment]
When you say "overlay icon", do you mean the tray icon?

(what we call overlay icons is usually icons on top of file icons in nautilus).

**Comment by ArthurGarnier** [comment]
My bad, I mixed up overlay and tray... So the overlay was disabled after I uninstalled python2-nautilus but the problem was still here !

**Comment by jturcotte** [comment]
OK thanks! Assigning ckamm to have a look since I guess he's the most competent person in the gnome tray stuff.

**Comment by ckamm** [comment]
@ArthurGarnier If it's not about the overlay icons, then maybe it's about the tray icon. We've had performance issues in some implementations before (#4990 #4985) and the problem should be fixed for 2.3 by https://github.com/owncloud/client/commit/88cd5421bfcfafa9f4aaa46cff6166dfce1f516d.

Could you check whether it's indeed related to the system tray by setting the environment variable `OWNCLOUD_MINIMAL_TRAY_MENU` to `1` before starting the owncloud client? E.g. quit the client and then do something like this in a shell:
```
$ OWNCLOUD_MINIMAL_TRAY_MENU=1 /path/to/owncloud-client
```

Do you still observe the freezes then?

**Comment by guruz** [comment]
@ArthurGarnier Did you manage to try?

**Comment by guruz** [comment]
The client nightlies for tomorrow should be based on 2.3

**Comment by ArthurGarnier** [comment]
I'll try as soon as possible (probably this week), I'll keep you updated

**Comment by ArthurGarnier** [comment]
I tried and I works now ! Really nice :)

**Comment by guruz** [comment]
nice..!
