### ISSUE TITLE
First repo always expands when opening main window

### ISSUE THREAD

**Issue by LukeOwlclaw** [owncloud/client#5029]
### Expected behaviour

When I close the client window I expect the expand/closed state of all repos to be saved. 
### Actual behaviour

The first repository is always expanded when opening the client. (All other expand/close states are remembered and set correctly.)
### Steps to reproduce
1. Open client.
2. Minimize all repositories in first tab.
3. Close client window.
4. Open client via tray icon.
### Client configuration

Client version: 2.1.1 (build 5837)

Operating system: Win10 64bit

**Comment by guruz** [comment]
I think this was because of my change long time ago to make the selective sync more discoverable because people did not know it was a tree view.
