### ISSUE TITLE
[Ubuntu 12.04] package removed from repo - Can't update client

### ISSUE THREAD

**Issue by brentfincham** [owncloud/client#5032]
**Is 12.04 no longer supported?**

### Expected behaviour
Ubuntu Update Manager tells me there is an update available for Owncloud sync client and I select the client and its dependencies and select "Install Updates" and the client updates to the most recent version.

### Actual behaviour
When I select the client and its dependencies in Update Manager and select "Install Updates". Update Manager shows an error: 
>
> **Requires installation of untrusted packages**
> 
> The action would require the installation of packages from not authenticated sources.
> 

apt-get update says this:

> W: Failed to fetch http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_12.04/Packages  404  Not Found

### Steps to reproduce
1. Run Update Manager GUI or apt-get update
2. Select owncloud client and dependencies
3. Click "Install Updates"

### Client configuration
Client version: Version 2.2.0%nil (build 1605)

Operating system: Ubuntu 12.04

OS language: English

Installation path of client: default

**Comment by guruz** [comment]
Which Qt version does this Ubuntu ship with or can be updated to?

**Comment by danimo** [comment]
This is correct. With the release of Ubuntu 16.04, Ubuntu 12.04 is no longer supported. 2.2.0 was not intended to ever be built for 12.04. We are trying to make things more transparent with this document which is under discussion right now: https://github.com/owncloud/client/wiki/OS-Support-Policy
