### ISSUE TITLE
[Windows] Owncloudcmd doesn't work when using relative path for local folder to sync

### ISSUE THREAD

**Issue by rouge-zz** [owncloud/client#5035]
### Expected behaviour
Tell us what should happen

e:
cd \

this fails : owncloudcmd -u $user - p $password folder http://owncloud.mydomain.com/owncloud/remote.php/webdav/folder
( csync_ftw:  Permission denied. 
and
 #### ERROR during  csync_update :  "CSync failed due to unhandled permission denied.")

while this works 
e:
cd \
owncloudcmd -u $user - p $password e:\folder http://owncloud.mydomain.com/owncloud/remote.php/webdav/folder

### Actual behaviour
Tell us what happens instead

good fix :
owncloudcmd should be able to manage relative paths.

Quick and easy
Specify in "owncloudcmd --help" that the path to the local folder must be an absolute path

### Steps to reproduce
1.  see above
2. 
3. 

### Server configuration
Operating system:
ubuntu 14.04

Web server: 
apache 2.4

Database:
mysql 5.5

PHP version:
php 5.5

ownCloud version:

Storage backend:

### Client configuration
Client version:
2.2.2 

Operating system:
windows

OS language:
french

Installation path of client:
c:\program files (x86)\owncloud

#### Discovery start #################################################### >>
=====Server "" "rootEtagChangesNotOnlySubFolderEtags=0"
void OCC::SyncEngine::startSync() "sauvegarde/"  QUrl( "owncloud://owncloud.mydomain.fr/owncloud/remote.php/webdav/sauvegarde/" )
[07/04 13:45:27.749380, 8] csync_update:  Journal: test/.csync_journal.db
[07/04 13:45:27.753381, 6] csync_statedb_load:  sqlite3 version "3.13.0"
[07/04 13:45:27.755381, 6] csync_statedb_load:  Success
[07/04 13:45:27.757381, 5] csync_ftw:  Permission denied.
[07/04 13:45:27.847386, 6] csync_statedb_close:  sqlite3_close=0
 #### ERROR during  csync_update :  "CSync failed due to unhandled permission denied."
void OCC::SyncJournalDb::close() "test/.csync_journal.db"
No database Transaction to commit
CSync run took  129
void OCC::SyncEngine::abort() QObject(0x0)
void OCC::SyncJournalDb::close() "test/.csync_journal.db"
No database Transaction to commit

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by ckamm** [comment]
It works on linux, will try to reproduce on windows.

**Comment by mcastroSG** [comment]
Tested on W10 and works fine.

Client OS: Windows 10
Client Version: 2.3.0-nightly20160705 (build 6227)
Server OS: Ubuntu 14.04 LTE
Server OS: 9.1.0 beta 1
