### ISSUE TITLE
Refresh action

### ISSUE THREAD

**Issue by neokeats** [owncloud/client#5038]
Hi, 
is it possible to have a refresh action : right click refresh this directory.

We're using owncloud to provide files to an application that consume them.
User 1 set files in a specific directory named DO : 
file1, file2, file3
The app consume them then move them to a directory named DONE.
The user still see the files in the DO directory until he goes on the client untick the DO directory, hit apply, then tick the DO directory, now the directory is refreshed.

thanx.

**Comment by guruz** [comment]
This should not happen, the client checks for changes on the server every 30 seconds.

Do you use external storage on the server?

Which server version? Which client version? Which client OS? etc.

Please check the issue template that appears when doing https://github.com/owncloud/client/issues/new

**Comment by neokeats** [comment]
server ubuntu : ownCloud 8.2.5 (stable) 
client windows 10 version 2.2.2(build 6192)

The files are moved manually by the app on the server side directly from de data dir. Maybe that's the cause ?

**Comment by danimo** [comment]
@neokeats Yes, The data dir is assumed to be exclusively under owncloud's access. That'd be your problem then. Closing this report hence.

**Comment by guruz** [comment]
-> https://doc.owncloud.org/server/8.2/admin_manual/configuration_server/occ_command.html#file-operations-label

**Comment by neokeats** [comment]
@danimo Ok no solution then, the refresh action could still remove the fact to have to do to tick/ok/untick/ok.
Since owncloud doesn't have a server client (no graphical interface). 
We can only alter files manually on servers.
@guruz i tried php occ files:scan --path="server/files/IMPORTS" -vvv
it doesn't update the clients side, only the tick/untick thing works. 
Maybe then having something like 
php occ files:delete 
php occ files:add
php occ files:move 
could solve the issue

**Comment by danimo** [comment]
@neokeats Do not use occ in normal operation! use files_external with local storage instead.
