### ISSUE TITLE
OS X client won't sync

### ISSUE THREAD

**Issue by cashew90** [owncloud/client#5040]
I used the current version of owncloud desktop client, as well as the previous one - same result. It 'discovers'/inspects the files for a while... and just stops. It always says that the server replied with an internal server error. No more information. Same reaction on my macbook and my mac mini.

Thank you in advance!

**Comment by jonesints** [comment]
What version of the server are you running? Do you have access to the owncloud admin account or the server to look at the logs?

**Comment by cashew90** [comment]
I have no access to the admin account. Just a normal account for the files. But I mounted it as Webdav and it works for me. Nevertheless, would be great if I could use the official app.

**Comment by danimo** [comment]
@cashew90 Yes, but this seems to be an issue on the other end, so please get in touch with the administrator first. The client usually does not directly cause server errors in normal operation. My best guess is that there is a problem on the server side that needs fixing. WebDAV working unfortunately is not a positive indication, just the baseline.

If you find its not a installation issue, please reopen this issue.
