### ISSUE TITLE
Share dialog does not work when file names contain %20

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#5042]
Try sharing a file with a name that literally contains "%20" (spaces are fine). Found by @bah0071 in #5022 .

The problem seems to be that QUrl::setQueryItems() doesn't percent encode the file path parameter properly. A file name like "foo%20" leads to a GET request for shares with the query parameter "path=foo%20" instead of "path=foo%2520".

Suggestion: Use QUrl::toPercentEncoding manually and then use QUrl::setEncodedQueryItems instead.

**Comment by ckamm** [comment]
@ogoffart @guruz Potentially a bug in Qt?

**Comment by ckamm** [comment]
Pull request: https://github.com/owncloud/client/pull/5043

**Comment by mcastroSG** [comment]
Hi hi:

I´m able to reproduce the problem on Windows and Mac 2.2.2 version. I´ve made some test with nightly and works fine.

Client OS: OSX El capitán 10.11.5
Client Version: 2.2.3-nightly20160714 (build 3525)

Client OS: W10
Client Version: 2.2.3-nightly20160714 (build 6247)
