### ISSUE TITLE
Overlay sync icon in Windows Explorer / Mac Finder showing green tick prematurely

### ISSUE THREAD

**Issue by sharcslife** [owncloud/client#5044]
### Expected behaviour
Green tick overlay icon should appear once entiry content of folder has been synced

### Actual behaviour
Green tick overlay icon appears once sub-folder struture has been synced

### Steps to reproduce
1. Create folder containng several subfolders an files
2. Start client
3. Copy folder to owncloud sync folder
4. Check your file explorer to see overlay icon behaviour

### Client configuration
Client version: 2.2.2 for Mac and PC
Operating system: Mac OSx newest version, Windows 10 64bit all updated
OS language: German
Installation path of client: standard

![pastedgraphic-4 1](https://cloud.githubusercontent.com/assets/3924964/16710327/b3ea354c-462a-11e6-9d1c-59d9a3f52803.png)

**Comment by guruz** [comment]
FYI @jturcotte .. is there any fix not in 2.2.2 but in 2.2.3?

**Comment by jturcotte** [comment]
No, this would be the same issue as described in #4797 if I understand the issue correctly. The problem at the moment is that if the folder is new, we get an itemCompleted for the folder creation even though we should wait for all children to be complete. But this doesn't happen for touching files in existing directories.

**Comment by sharcslife** [comment]
I can confirm that I have not come accross the issue with folder that had already been synced.
That doesn't mean that it does not occur in that case, thoug.

**Comment by guruz** [comment]
Making https://github.com/owncloud/client/issues/4797 a bug and closing this. Thank you.
