### ISSUE TITLE
Progress Calculcations should have a maximum value to be displayed

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/client#5046]
### Expected behaviour
Having a progress indicator telling the user that is will take hundreds of thousands of year to up/download has zero value from my pov

see https://www.facebook.com/photo.php?fbid=976914802406122&set=o.366301826358&type=3&theater

![13592161_976914802406122_2971566735647043855_n](https://cloud.githubusercontent.com/assets/1005065/16721299/6ed715d2-473e-11e6-85d7-b30046150164.jpg)

**Comment by dragotin** [comment]
whats the version? There were fixes for 2.2.2 IIRC

**Comment by DeepDiver1975** [comment]
> whats the version? There were fixes for 2.2.2 IIRC

I just asked for the version information ....

**Comment by DeepDiver1975** [comment]
2.2.2 according to the reporter on facebook

**Comment by ckamm** [comment]
Pull request setting a 5kb/s lower limit on the bandwidth estimate: https://github.com/owncloud/client/pull/5066

**Comment by ckamm** [comment]
@dragotin @guruz @ogoffart To continue the discussion from the pull request: If we wanted to hide the time estimate sometimes, what exactly would be a sensible criterion?
* "If the estimated time is longer than N days" -> What if users want to upload TBs of data and it genuinely takes that long?
* "If the bandwidth drops below a critical threshold" -> Unfortunately bandwidth often drops to shockingly small values when a lot of small files are uploaded or downloaded, or many files are moved or deleted.

The current code already tries to detect cases where the remaining time isn't dominated by bandwidth but by per-request overhead. But it doesn't seem to have caught the particular case that's being reported.

Suggestion: Hide the time estimate when the current estimate is way above (>100x) the optimistic estimate (which is calculated using the highest files-per-second and bandwidth values that were observed so far).

**Comment by davitol** [comment]
@ckamm Which is supposed to be the maximum value that can be displayed?

**Comment by ckamm** [comment]
@davitol There is no fixed limit. Time estimates are displayed as long as the estimate isn't larger than 100x the optimistic estimate (which uses the highest-ever seen files-per-second and bytes-per-second values).

This means you should be able to reproduce this, for example, when uploading a large file. Start out normal and then throttle your bandwidth severely (few bytes per second). After a while (a minute?) the current-bandwidth based time estimate should become huge and the time estimate should stop being displayed.

**Comment by davitol** [comment]
@ckamm Thanks for the hints. Tested in oC 2.3.0-nightly20160929 (build 3715) using Network Link Conditioner in OSX and time estimate stops being displayed.
:+1:
