### ISSUE TITLE
[COMODO AntiVirus] [Windows] Randomly updating modification date of DLL JS CMD and BAT files

### ISSUE THREAD

**Issue by mleluca** [owncloud/client#5047]
Client version: 2.2.2 - build 6192
OS: Windows 7 64 bit PL

Server: Linux Debian
Database MySQL

Client is randomly updating modification date of all dll, js, cmd and bat files. Then Client is updating those files on server. So there is non stop synchronization with specified above files.

**Comment by ogoffart** [comment]
Please provide the logs.
My best guess is that there is another program that is doing theses modificatons.  Then of course, the client will upload the files as this is the way we detect changes.
Maybe you are infected by a virus.

**Comment by mleluca** [comment]
Thank You very much for Your answer.
I prepare directory called TEST and put there four DLL file. Below I attached the logfile
https://gist.github.com/mleluca/2e2ed302f64b989f8f76ecc3bb80430e

In first step I don't know why client Was downloading files form server. Files are only on desktop and server, Nothing Was changed and then client download file form server - modification time - one minute before download time - so maybe server is changing modification time? Next thing I don't understand I downland files from server at 13:02:05, at next sync run I'm uploading them why? Nothing Was changed.

I have hundreds of dll files on my drive, on the same drive but not synchronised, and their modification date is stable. I have problem only with file which are synchronized.

**Comment by ogoffart** [comment]
That looks wierd indeed.
If you can reproduce, can you check the log by pressing F12 in the client.

**Comment by andyboeh** [comment]
I've got the same problem on one of my windows machines. As soon as I start synchronizing this machine (it's the only Windows 7 machine, btw), DLLs are constantly synched back and forth. There are other Windows machines (running Windows 10) that do not have this problem.

All machines have "COMODO AntiVirus" running.

**Comment by guruz** [comment]
@mleluca Do you also have COMODO AntiVirus?

**Comment by mleluca** [comment]
Yes I have COMODO AV.

**Comment by fmoc** [comment]
Has not seen activity in years, likely resolved in the meantime. If not, please don't hesitate to reopen this issue.
