### ISSUE TITLE
windows client can not handle ß

### ISSUE THREAD

**Issue by Simonstroe** [owncloud/client#5048]
Trying ti connect the windowsclient with my owncoud under cloud.simonströßer.de
Everything works in the browser
It allways says that the connection to owncloud http://cloud.simonströßer.de/status.php could not be done.
In german: Die Verbindung zu ownCloud auf http://cloud.simonströßer.de/status-php:
Host cloud.simonströßer.de konnte nicht gefunden werden konnte nicht hergestellt werden
At first i typed cloud.simonströßer.de in but the client always changed ß with ss so i tried http://cloud.xn--simonstrer-d4a9y.de, then in the error it is written correctly but still can not connect

connecting with the demo server works fine

### Server configuration
Operating system: Lnux

Web server: Apache

Database: MySQL

PHP version: 5.5

ownCloud version: 9.0.1

Storage backend: ?

### Client configuration
Client version: 2.2.2

Operating system: WIndows 10

OS language: German

Installation path of client: "C:\Program Files (x86)\ownCloud"

Greetings Simon

**Comment by ogoffart** [comment]
If this is a bug at all, it is a bug in Qt,

```
QUrl("http://cloud.simonströßer.de").toEncoded();  
```

Gives http://cloud.xn--simonstrsser-cjb.de  which is also what i get if i type http://cloud.simonströßer.de/ on chrome.
But interestingly, firefox convert it as you said.

**Comment by ogoffart** [comment]
ß should convert to ss according the table B.2 of https://tools.ietf.org/html/rfc3454#appendix-B.2
And chrome and this online converter agrees https://www.punycoder.com/

So this is not a bug in the owncloud.  Your domain name is wrongly encoded.

**Comment by ogoffart** [comment]
It turns out there is a difference in IDNA2008 and IDNA2003, Qt is still based in IDNA2003.

See also:  https://blogs.msdn.microsoft.com/shawnste/2010/12/08/idna-is-it-fussball-or-fuball/

**Comment by ogoffart** [comment]
(In other words: you should register both domains)
