### ISSUE TITLE
own Cloud Mac OS X version

### ISSUE THREAD

**Issue by badredaha** [owncloud/client#5049]
### Expected behaviour
Application build succes but not started !!! and its crash every where !!! can i have verison stable !!

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend:

### Client configuration
Client version:

Operating system:

OS language:

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by dragotin** [comment]
https://owncloud.org/install/#install-clients

**Comment by badredaha** [comment]
i download source code for building into xCode project !! i found a lot of behavior when i started application.

I follow installation step by step but not work
