### ISSUE TITLE
[Windows 10] "Share with owncloud" not showing in 2.2.2

### ISSUE THREAD

**Issue by Shadwstorm** [owncloud/client#5051]
### Expected behaviour
When in the owncloud share folder, I should be able to share directly by right clicking "share with owncloud." I no longer have this option since update 2.2.2

also the icons showing sync (green check and blue dot) no longer appear... the folder looks like a regular folder

(This issue was repeated by someone else, but was attributed to an http/https issue which I don't have. https://github.com/owncloud/client/issues/5022)

### Actual behaviour
no option available

### Steps to reproduce
1. right click on folder/file t
2. 
3. 

### Server configuration
Operating system: linux

Web server: apache

Database: mysql

PHP version: 5.5.30

ownCloud version: 9.0.3

Storage backend:

### Client configuration
Client version: 2.2.2

Operating system:10 64 bit

OS language: English

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`

No Log Output. Nothing.

**Comment by guruz** [comment]
Did you try a reboot?

Please wait for https://github.com/owncloud/client/pull/5025 to be merged, thanks. Then we can provide you a nightly for testing.
(Note: Might also be the subfolder in the socket path)

**Comment by Shadwstorm** [comment]
I'm out of my league here, guruz, I'm just writing it as I see it.

I don't own server. I'm on shared server.
If you meant my computer, I uninstalled and reinstalled client.

**Comment by dragotin** [comment]
Ok, great. Thanks for letting us know.
