### ISSUE TITLE
Typo in docs for  MAC OS X configuration file location?

### ISSUE THREAD

**Issue by RealRancor** [owncloud/client#5052]
https://doc.owncloud.org/desktop/2.2/advancedusage.html#configuration-file

currently has the following entry:

```
On MAC OS X systems:
    $HOME/Library/Application Support/ownCloud
```

Shouldn't this be:

```
On MAC OS X systems:
    $HOME/Library/Application Support/ownCloud/owncloud.cfg
```

similar to the windows and linux examples above it?

**Comment by guruz** [comment]
Merci @RealRancor .. fixed
