### ISSUE TITLE
[Windows 8.1] [9.0.2] When renaming a file in a shared folder ownCloud desktop client redownloads it with the old name

### ISSUE THREAD

**Issue by sxdxfan** [owncloud/client#5054]
### Expected behaviour

After renaming a file the desktop client should just 'move' it
### Actual behaviour

After a while it actually redownloads the file with its previous name, so we have a duplicate file
### Steps to reproduce
1. Share folder with somebody
2. Rename a file in Windows Explorer in this folder
3. In a few seconds the client syncs the file and then redownloads it with the previous name
### Server configuration

Operating system: CentOS Linux release 7.2.1511 (Core)

Web server: Apache/2.4.6 (CentOS)

Database: mysql  Ver 15.1 Distrib 5.5.47-MariaDB, for Linux (x86_64) using readline 5.1

PHP version: PHP 5.5.36 (cli) (built: May 28 2016 12:05:32)

ownCloud version: 9.0.2
### Client configuration

Client version: 2.2.2

Operating system: Windows 8.1

OS language: Russian

Installation path of client: standard
### Logs
1. ownCloud log (data/owncloud.log):

{"reqId":"V4SlVyOJUxDnTBNryXyfmQAAAA8","remoteAddr":"172.18.10.41","app":"user_ldap","message":"Turned off SSL certificate validation successfully.","level":0,"time":"2016-07-12T11:07:51+03:00","method":"PUT","url":"\/remote.php\/webdav\/%D0%90%D0%BA%D1%81%D0%B5%D0%BB%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%20%D0%A4%D0%A0%D0%98%D0%98\/%D0%A0%D0%B5%D0%B3%D0%B8%D0%BE%D0%BD%D1%8B\/%D0%9D%D0%90%D0%A8%D0%98%20%D0%9C%D0%95%D0%A0%D0%9E%D0%9F%D0%A0%D0%98%D0%AF%D0%A2%D0%98%D0%AF\/hse%7Bsun%7D%202016\/%20hse%7Bsun%7D%202016\/%D0%BF%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B8%20%D1%81%D0%BF%D0%B8%D0%BA%D0%B5%D1%80%D0%BE%D0%B2\/%D0%B4%D0%B5%D0%BD%D1%8C%204%20-%208%20%D0%B8%D1%8E%D0%BB%D1%8F\/%D0%9E%D1%86%D0%B5%D0%BD%D0%BA%D0%B0%20%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D0%B2%D1%8B%D1%85%20%D1%80%D0%B8%D1%81%D0%BA%D0%BE%D0%B2%20-%20%D0%A5%D0%B0%D1%80%D0%B8%D1%82%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0%20%D0%9B..pdf","user":"_4952"}
{"reqId":"V4SlVyOJUxDnTBNryXyfmQAAAA8","remoteAddr":"172.18.10.41","app":"user_ldap","message":"initializing paged search for  Filter <blahblah_sensitive_data> attr Array\n(\n    [0] => \n)\n limit 500 offset 0","level":0,"time":"2016-07-12T11:07:51+03:00","method":"PUT","url":"\/remote.php\/webdav\/%D0%90%D0%BA%D1%81%D0%B5%D0%BB%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%20%D0%A4%D0%A0%D0%98%D0%98\/%D0%A0%D0%B5%D0%B3%D0%B8%D0%BE%D0%BD%D1%8B\/%D0%9D%D0%90%D0%A8%D0%98%20%D0%9C%D0%95%D0%A0%D0%9E%D0%9F%D0%A0%D0%98%D0%AF%D0%A2%D0%98%D0%AF\/hse%7Bsun%7D%202016\/%20hse%7Bsun%7D%202016\/%D0%BF%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B8%20%D1%81%D0%BF%D0%B8%D0%BA%D0%B5%D1%80%D0%BE%D0%B2\/%D0%B4%D0%B5%D0%BD%D1%8C%204%20-%208%20%D0%B8%D1%8E%D0%BB%D1%8F\/%D0%9E%D1%86%D0%B5%D0%BD%D0%BA%D0%B0%20%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D0%B2%D1%8B%D1%85%20%D1%80%D0%B8%D1%81%D0%BA%D0%BE%D0%B2%20-%20%D0%A5%D0%B0%D1%80%D0%B8%D1%82%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0%20%D0%9B..pdf","user":"_4952"}
{"reqId":"V4SlVyOJUxDnTBNryXyfmQAAAA8","remoteAddr":"172.18.10.41","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-07-12T11:07:51+03:00","method":"PUT","url":"\/remote.php\/webdav\/%D0%90%D0%BA%D1%81%D0%B5%D0%BB%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%20%D0%A4%D0%A0%D0%98%D0%98\/%D0%A0%D0%B5%D0%B3%D0%B8%D0%BE%D0%BD%D1%8B\/%D0%9D%D0%90%D0%A8%D0%98%20%D0%9C%D0%95%D0%A0%D0%9E%D0%9F%D0%A0%D0%98%D0%AF%D0%A2%D0%98%D0%AF\/hse%7Bsun%7D%202016\/%20hse%7Bsun%7D%202016\/%D0%BF%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B8%20%D1%81%D0%BF%D0%B8%D0%BA%D0%B5%D1%80%D0%BE%D0%B2\/%D0%B4%D0%B5%D0%BD%D1%8C%204%20-%208%20%D0%B8%D1%8E%D0%BB%D1%8F\/%D0%9E%D1%86%D0%B5%D0%BD%D0%BA%D0%B0%20%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D0%B2%D1%8B%D1%85%20%D1%80%D0%B8%D1%81%D0%BA%D0%BE%D0%B2%20-%20%D0%A5%D0%B0%D1%80%D0%B8%D1%82%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0%20%D0%9B..pdf","user":"_4952"}
{"reqId":"V4SlVyOJUxDnTBNryXyfmQAAAA8","remoteAddr":"172.18.10.41","app":"user_ldap","message":"readAttribute: <blahblahblah> found","level":0,"time":"2016-07-12T11:07:51+03:00","method":"PUT","url":"\/remote.php\/webdav\/%D0%90%D0%BA%D1%81%D0%B5%D0%BB%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%20%D0%A4%D0%A0%D0%98%D0%98\/%D0%A0%D0%B5%D0%B3%D0%B8%D0%BE%D0%BD%D1%8B\/%D0%9D%D0%90%D0%A8%D0%98%20%D0%9C%D0%95%D0%A0%D0%9E%D0%9F%D0%A0%D0%98%D0%AF%D0%A2%D0%98%D0%AF\/hse%7Bsun%7D%202016\/%20hse%7Bsun%7D%202016\/%D0%BF%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B8%20%D1%81%D0%BF%D0%B8%D0%BA%D0%B5%D1%80%D0%BE%D0%B2\/%D0%B4%D0%B5%D0%BD%D1%8C%204%20-%208%20%D0%B8%D1%8E%D0%BB%D1%8F\/%D0%9E%D1%86%D0%B5%D0%BD%D0%BA%D0%B0%20%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D0%B2%D1%8B%D1%85%20%D1%80%D0%B8%D1%81%D0%BA%D0%BE%D0%B2%20-%20%D0%A5%D0%B0%D1%80%D0%B8%D1%82%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0%20%D0%9B..pdf","user":"_4952"}
{"reqId":"V4SlVyOJUxDnTBNryXyfmQAAAA8","remoteAddr":"172.18.10.41","app":"user_ldap","message":"initializing paged search for  Filter <blahblahblah_again> attr Array\n(\n    [0] => \n)\n limit 500 offset 0","level":0,"time":"2016-07-12T11:07:51+03:00","method":"PUT","url":"\/remote.php\/webdav\/%D0%90%D0%BA%D1%81%D0%B5%D0%BB%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%20%D0%A4%D0%A0%D0%98%D0%98\/%D0%A0%D0%B5%D0%B3%D0%B8%D0%BE%D0%BD%D1%8B\/%D0%9D%D0%90%D0%A8%D0%98%20%D0%9C%D0%95%D0%A0%D0%9E%D0%9F%D0%A0%D0%98%D0%AF%D0%A2%D0%98%D0%AF\/hse%7Bsun%7D%202016\/%20hse%7Bsun%7D%202016\/%D0%BF%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B8%20%D1%81%D0%BF%D0%B8%D0%BA%D0%B5%D1%80%D0%BE%D0%B2\/%D0%B4%D0%B5%D0%BD%D1%8C%204%20-%208%20%D0%B8%D1%8E%D0%BB%D1%8F\/%D0%9E%D1%86%D0%B5%D0%BD%D0%BA%D0%B0%20%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D0%B2%D1%8B%D1%85%20%D1%80%D0%B8%D1%81%D0%BA%D0%BE%D0%B2%20-%20%D0%A5%D0%B0%D1%80%D0%B8%D1%82%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0%20%D0%9B..pdf","user":"_4952"}
{"reqId":"V4SlVyOJUxDnTBNryXyfmQAAAA8","remoteAddr":"172.18.10.41","app":"user_ldap","message":"Ready for a paged search","level":0,"time":"2016-07-12T11:07:51+03:00","method":"PUT","url":"\/remote.php\/webdav\/%D0%90%D0%BA%D1%81%D0%B5%D0%BB%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%20%D0%A4%D0%A0%D0%98%D0%98\/%D0%A0%D0%B5%D0%B3%D0%B8%D0%BE%D0%BD%D1%8B\/%D0%9D%D0%90%D0%A8%D0%98%20%D0%9C%D0%95%D0%A0%D0%9E%D0%9F%D0%A0%D0%98%D0%AF%D0%A2%D0%98%D0%AF\/hse%7Bsun%7D%202016\/%20hse%7Bsun%7D%202016\/%D0%BF%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B8%20%D1%81%D0%BF%D0%B8%D0%BA%D0%B5%D1%80%D0%BE%D0%B2\/%D0%B4%D0%B5%D0%BD%D1%8C%204%20-%208%20%D0%B8%D1%8E%D0%BB%D1%8F\/%D0%9E%D1%86%D0%B5%D0%BD%D0%BA%D0%B0%20%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D0%B2%D1%8B%D1%85%20%D1%80%D0%B8%D1%81%D0%BA%D0%BE%D0%B2%20-%20%D0%A5%D0%B0%D1%80%D0%B8%D1%82%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0%20%D0%9B..pdf","user":"_4952"}
{"reqId":"V4SlVyOJUxDnTBNryXyfmQAAAA8","remoteAddr":"172.18.10.41","app":"user_ldap","message":"readAttribute: <blah> found","level":0,"time":"2016-07-12T11:07:51+03:00","method":"PUT","url":"\/remote.php\/webdav\/%D0%90%D0%BA%D1%81%D0%B5%D0%BB%D0%B5%D1%80%D0%B0%D1%82%D0%BE%D1%80%20%D0%A4%D0%A0%D0%98%D0%98\/%D0%A0%D0%B5%D0%B3%D0%B8%D0%BE%D0%BD%D1%8B\/%D0%9D%D0%90%D0%A8%D0%98%20%D0%9C%D0%95%D0%A0%D0%9E%D0%9F%D0%A0%D0%98%D0%AF%D0%A2%D0%98%D0%AF\/hse%7Bsun%7D%202016\/%20hse%7Bsun%7D%202016\/%D0%BF%D1%80%D0%B5%D0%B7%D0%B5%D0%BD%D1%82%D0%B0%D1%86%D0%B8%D0%B8%20%D1%81%D0%BF%D0%B8%D0%BA%D0%B5%D1%80%D0%BE%D0%B2\/%D0%B4%D0%B5%D0%BD%D1%8C%204%20-%208%20%D0%B8%D1%8E%D0%BB%D1%8F\/%D0%9E%D1%86%D0%B5%D0%BD%D0%BA%D0%B0%20%D0%BF%D1%80%D0%B0%D0%B2%D0%BE%D0%B2%D1%8B%D1%85%20%D1%80%D0%B8%D1%81%D0%BA%D0%BE%D0%B2%20-%20%D0%A5%D0%B0%D1%80%D0%B8%D1%82%D0%BE%D0%BD%D0%BE%D0%B2%D0%B0%20%D0%9B..pdf","user":"_4952"}

**Comment by guruz** [comment]
Did your configure/use any external storage in your server?

Are you using encryption?

FYI @PVince81

**Comment by sxdxfan** [comment]
No, we don't use any external storage, no encryption too

**Comment by PVince81** [comment]
@sxdxfan does it happen for any file or just this specific one ?

I wonder if the file name is too long, but then the owncloud.log should show an error.

**Comment by sxdxfan** [comment]
It's not that long actually, logs show Russian letters in unicode. This behavior is reproducible with other files. It all began with the upgrade of the Windows client to the latest version.

**Comment by ogoffart** [comment]
Do you actually have the premission to rename that file?

**Comment by sxdxfan** [comment]
The file that is being renamed is in a folder shared by the other user with a group that contains the user, who is trying to rename the file. All permissions (share, create, change, etc) are granted.

**Comment by PVince81** [comment]
are there any reshares involved ? is the file shared over multiple groups ? (to rule out double folder issue https://github.com/owncloud/core/issues/24575)

**Comment by sxdxfan** [comment]
Actually the file is shared with a group AND some separate users that are already in this group, but not with the user that renames the file.

**Comment by sxdxfan** [comment]
Probably a group member renames the file, then oC client finds the file with the old name in another user's (the one who has this file both as a separate user and as a group member) folder, uploads it as a newly added file and finally our group member's client downloads it. Well, at least I will try to remove duplicate user shares and see if it helps.

**Comment by PVince81** [comment]
@sxdxfan hmm, that sounds like a plausible scenario

**Comment by sxdxfan** [comment]
Fixed the issue by deleting extra user shares. You may find this interesting:

MariaDB [owncloud_db]> select * from oc_share where uid_owner = "user1" and file_target = "/shared_folder";
+-------+------------+------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+----------------------------------+-------------+------------+----------+------------+-------+-----------+
| id    | share_type | share_with | uid_owner | uid_initiator | parent | item_type | item_source | item_target | file_source | file_target                      | permissions | stime      | accepted | expiration | token | mail_send |
+-------+------------+------------+-----------+---------------+--------+-----------+-------------+-------------+-------------+----------------------------------+-------------+------------+----------+------------+-------+-----------+
| 17872 |          0 | user2  | user1 | user1     |   NULL | folder    | 735115      | /735115     |      735115 | /shared_folder                |          31 | 1454503508 |        0 | NULL       | NULL  |         1 |
| 17873 |          1 | group      | user1 | user1     |   NULL | folder    | 735115      | /735115     |      

735115 | /shared_folder                |          31 | 1454503517 |        0 | NULL       | NULL  |         0 |
| 17874 |          2 | user2  | user1 | NULL          |  17873 | folder    | 735115      | /735115     |      735115 | /shared_folder                |          31 | 1454503517 |        0 | NULL       | NULL  |         0 |

When I deleted share with user2 via Web interface the entry 17872 dissappeared, but 17874 stayed. So I manually deleted the entry from oc_share. What does share_type = 2 even mean? Perhaps, this caused the issue.

**Comment by hodyroff** [comment]
still an issue here? Please retest with 9.1.4 and client 2.3 ...
