### ISSUE TITLE
Selective sync default when new shared folder presnt

### ISSUE THREAD

**Issue by andreas-p** [owncloud/client#5060]
### Expected behaviour

I like to sync folders selectively. When I get access to a new shared folder, it will download immediately, i.e. the sync is assumed enabled by default. I'd like to have this as "default off" or maybe configurable using preferences.
### Actual behaviour

Syncing a freshly shared folder starts immediately.
### Steps to reproduce
1. Let somebody share a folder with you
2. syncing will start immediately
### Server configuration

Operating system:
Debian 8

Web server: 
Apache

Database:
pgsql

PHP version:
5
ownCloud version:
9

Storage backend:
std
### Client configuration

Client version: 2.2.2.3472

Operating system:
OSX 10.11.5

OS language:
de

**Comment by ogoffart** [comment]
This was implementezd in 2.4 or 2.3
There is an option to ask for confirmation before syncing mounted folders.
