### ISSUE TITLE
translations: has the translations for Chinese (Simplified) been stopped?

### ISSUE THREAD

**Issue by ArthurChiao** [owncloud/client#5061]
hi,

I noticed that it has been a long time (at least several months) since the last update of the Chinese (Simplified, zh_CN) translation, I've reported some mistakes in #4870, and has been applied to join the Chinese translation team on [transifex](https://www.transifex.com/owncloud-org/owncloud/), but never got any response. 

So I want to know the process of the translation team, and whether I can contribute to.

BRs

**Comment by DeepDiver1975** [comment]
The translation is at 98%

![bildschirmfoto von 2016-07-18 08-37-41](https://cloud.githubusercontent.com/assets/1005065/16907315/f1eac7c8-4cc2-11e6-8d3d-93bb3ea981a9.png)



> and has been applied to join the Chinese translation team on transifex, but never got any response.

will add you ...

**Comment by ArthurChiao** [comment]
@DeepDiver1975 thanks, i've pushed fixups of the translation mistakes i found.

**Comment by DeepDiver1975** [comment]
https://github.com/owncloud/client/commit/5672557a84361a67fedf1433ea8bcd3ccbddee4f#diff-e1fab3eb1117242d781c958b7c4297a7
