### ISSUE TITLE
[Windows] [Version 2.2.2. (build 6192)]  No connection to ownCloud at <SERVERNAME>. Operation canceled

### ISSUE THREAD

**Issue by MarvKara** [owncloud/client#5062]
### Expected behaviour
ownCloud client should make connection to server and sync files

### Actual behaviour
client cannot establish connection with server. I receive error message: "No connection to ownCloud at <SERVERNAME>. Operation canceled" This exact Setup works when i install version 2.1 of the client. As soon as i update to latest it stops working. Have reproduced this multiple times. The log says the credentials are wrong, but i can assure you they are not.

### Steps to reproduce
1. Setup server with latest owncloud version via docker
2. download latest client version for windows
3. observe this

![2016-07-17 20_26_03-](https://cloud.githubusercontent.com/assets/4380382/16902394/96fae916-4c5d-11e6-8954-d2b27dfed56b.png)

### Server configuration
Operating system:
Antergos

Web server: 
-

Database:
SQLite

PHP version:
-

ownCloud version:
9.0.3.2

Storage backend:
-

### Client configuration
Client version:
2.2.2 (build 6192)

Operating system:
Windows 10

OS language:
EN

Installation path of client:
C:\Program Files (x86)\Syncronization\ownCloud

### Logs

1. Client log: https://gist.github.com/MarvKara/385c46c6f777d0b20591edb28ce89576

2. Webserver log (how do i get this with docker?)

3. ownCloud log (how do i get this with docker?)

**Comment by dragotin** [comment]
Are you using dyn dns? The log seems to indicate that.

@guruz

**Comment by MarvKara** [comment]
I do use dyn dns, correct. does that matter?

**Comment by guruz** [comment]
This is a configuration issue. There is a network timeout:
```
07-17 20:33:24:740 0x4e97b18 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
...
07-17 20:33:51:745 0x4e97b18 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 5 "Operation canceled" QVariant(Invalid)
07-17 20:33:51:745 0x4e97b18 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 0 ""
```

You are using http instead of https, I'm assuming something in your network (wifi access point, proxy, firewall, virus scanner) is interfering. 

I don't know why it works with earlier versions, but I suggesto try with https

**Comment by guruz** [comment]
Did you try?

**Comment by MarvKara** [comment]
> Did you try?
No, I have not had the time yet.
Although, I must say I highly doubt it has anything to with https, as it worked with previous versions.
It makes no sense to me.
