### ISSUE TITLE
OS X client always crashes on startup, after upgrading to 2.2.2

### ISSUE THREAD

**Issue by tuomassalo** [owncloud/client#5063]
### Expected behaviour

When launching the ownCloud desktop client, the client should start up and I should see the icon in the notification area.

### Actual behaviour

I immediately get a "Sorry! ownCloud crashed. [...]" error.

### Steps to reproduce
1. Somehow get the client to a state where this crash occurs
2. Upgrade the desktop client from 2.1.1 to 2.2.2
3. Start owncloud
4. Get the error.

### Server configuration

(Shouldn't matter here - the client doesn't open a TCP connection to the server before crashing.)

Operating system: Ubuntu Linux 16.04

Web server: Apache 2.4 

Database: MySQL

PHP version: 5.5.9

ownCloud version: 8.1.8

Storage backend: default

### Client configuration
Client version: 2.2.2

Operating system: OS X 10.10.5

OS language: US English

Installation path of client: default (`/Applications/owncloud.app/`)

### Logs

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

```
$ /Applications/owncloud.app/Contents/MacOS/owncloud --logwindow
m_crashReporterChar:  /Applications/owncloud.app/Contents/MacOS/owncloud_crash_reporter
m_crashReporterWChar: /Applications/owncloud.app/Contents/MacOS/owncloud_crash_reporterDump file was written to: /var/folders/9s/y3l0_pgn4q3bq3w_4cb9_hh80000gn/T/43DF36CE-1D08-4833-93DB-A137F7669402.dmp
```
2. Web server error log:

N/A

3. ownCloud log (data/owncloud.log):

N/A

How to debug this problem? I already tried removing `ownCloud/.csync_journal.db`. Are there some other ways to reset the client state? (Without starting the client, because that doesn't work...)

**Comment by tflidd** [comment]
The referred dump-file `/var/folders/9s/y3l0_pgn4q3bq3w_4cb9_hh80000gn/T/43DF36CE-1D08-4833-93DB-A137F7669402.dmp` could be interesting for the developers (it it hasn't been sent automatically).

**Comment by tuomassalo** [comment]
I clicked "Send this report" (just now, accidentally twice), so another dump should be visible to someone who can read those reports, with this timestamp. Would that help?

**Comment by olerichter** [comment]
Same here, first downgrading to 2.1.1 helped but not anymore.

**Comment by guruz** [comment]
How is it with 2.2.3?

**Comment by olerichter** [comment]
At the moment it is more stable at least for me (it crashes very rarely), I dont know why and it was independent from updating to 2.2.3 which also crashed in the beginning. The only possible expanation I can come up with that it is dependent on the network settings or that it colides with openVPN connections. Sorry that I cant be more helpfull.

**Comment by tuomassalo** [comment]
For me, upgrading to 2.2.3 seemed to help.

**Comment by guruz** [comment]
Great!
