### ISSUE TITLE
Redesign of ownCloud Setup Wizard

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#5064]
Subject of this issue is the redesign **of the setup wizard** as described in #5030. Let's track this here to not clutter the overview there.

Open Questions/considerations:
- Brandings must look the same as they do now. Branding can only be expanded a bit.
- HiDpi screens
- Free fonts

**Comment by dragotin** [comment]
FYI @madeinffm

**Comment by jancborchardt** [comment]
Just a few points for now:

- The free font to use should ideally be Open Sans, which we use in the web interface everywhere.
- If we want to go forward with that (and if it’s possible), it would be cool to make it similar like the log in / installation view in the web interface, where there’s a full-window background image. Then the logo up top and the boxes below. Very similar to what @madeinffm mocked up, but including the nice background image.

**Comment by danimo** [comment]
First approximation:

![image](https://cloud.githubusercontent.com/assets/1315934/17147366/d18177d8-5362-11e6-9d62-dd35216dc6e9.png)

**Comment by dragotin** [comment]
:-1: for the strange mountain background, that is hard to determine as mountain  (both for client and server) if it was me.

**Comment by danimo** [comment]
@dragotin it's consistent with the server UI. We have to find a common ground. It's easy to swap anyway.

**Comment by dragotin** [comment]
Yes, and, I forgot to mention, apart from the image: awesome!

**Comment by madeinffm** [comment]
Hey everyone,

sorry to be so absent, we were busy all week (plus it's holiday season). 
I agree, that we should use Open Sans (we already did in the sketches). As for the mountains (as for images in general), I would ask if it add something to the user experience. If not, then I would suggest to leave it out. Why show mountains? Are server stored in mountains? The more direct connection would be a picture of a cloud, which is rather dull in my opionion ;) I would go for simplicity and clarity.

cheers
florian

**Comment by jancborchardt** [comment]
Well, two simple reasons for the mountain background:
- it’s the same in the web interface, so keeping consistent
- it looks pretty awesome while keeping in the background – way nicer than a bland dark blue


I’d just make 2 modifications:
- Instead of »What is your server’s address?«, the field should have either a greyish placeholder or a smaller title above which says: »Server address https://…« so it’s clear what needs to be put in. We do the same in the Android app.
- »Welcome to ownCloud!« is a a bit too big, looks unbalanced in comparison to the logo. Should ideally be the text size of »What is your server’s address?« now. (While reducing the size of that.)

**Comment by jancborchardt** [comment]
(@madeinffm btw since you are based in Frankfurt maybe you wanna meet with @AndyScherzinger who works on the Android app! :)

**Comment by AndyScherzinger** [comment]
There's a meetup in FFM? 0_o 
Never realized that (or found it)

**Comment by madeinffm** [comment]
we're based in Frankfurt, so we could do a mini-meetup ;)

**Comment by danimo** [comment]
> Instead of »What is your server’s address?«, the field should have either a greyish placeholder or a smaller title above which says: »Server address https://…« so it’s clear what needs to be put in. We do the same in the Android app.

I can have a hint like that, however the field gets the focus by default, so the hint will never be visible unless the user shifts the fokus away by default. This is unlike mobile touch interfaces which do not have a strict concept of a focus.

**Comment by danimo** [comment]
New state, with and without background image:

![image](https://cloud.githubusercontent.com/assets/1315934/17178523/12f59b28-5416-11e6-94e5-bd0402d876d1.png)

![image](https://cloud.githubusercontent.com/assets/1315934/17178594/6209faf6-5416-11e6-9392-d01e05a79eb5.png)

**Comment by danimo** [comment]
Also: how would we display errors in this view? Like "Server does not exist." "Could not find an ownCloud server at this address." etc.

**Comment by scolebrook** [comment]
Will this be brandable? It'd be good to have the choice to have an image or just a solid color. I assume the blue hue to the image is in the image itself, not some kind of filter or semi-transparent layer?

**Comment by danimo** [comment]
@scolebrook The idea is to keep the image optional for branding.

**Comment by jancborchardt** [comment]
@danimo 
- Is it not possible to have the placeholder still be displayed when the field is focused?
- The errors should be displayed directly below the input field (just like on Android)
- The spacing was a bit better before – whitespace above the logo, and no space between »what’s the address« and the input.

**Comment by danimo** [comment]
@jancborchardt 

* It is, I've done this now.
* It was like that before, just no errors implemented yet :)
* I'm back to the spacing in the mockup

**Comment by danimo** [comment]
Progress

![image](https://cloud.githubusercontent.com/assets/1315934/17269814/8490f734-5653-11e6-9436-5623daaae5b8.png)

Checks will now be done in place, and HTTPS validity, URL validity, etc will be indicated in place.

**Comment by jancborchardt** [comment]
Nice, going forward very well! :)

Text-wise it’s still a bit too much. I would say cut the giant »Welcome!« message which also repeats the logo / brand unnecessarily. And reword the »What is your server’s address?« to »Connect to your server«.

Then in the bottom 3-points bar, only capitalize the first word of each thing as we do everywhere else (in headings etc): »Server address« with lowercase a and »Sync options« with lowercase o.

And in the first step, there’s no need to show the back button at all, not even greyed out.

Is it also possible to make the bottom bar part of the main container with background blue and white text? Would look much nicer and more integrated that way.

**Comment by danimo** [comment]
> And in the first step, there’s no need to show the back button at all, not even greyed out.

We're not down to that level of details in the implementation yet, as it needs to  be generic. so I want the workflow working first.

> Is it also possible to make the bottom bar part of the main container with background blue and white text? Would look much nicer and more integrated that way.

Not sure I understand. Do you want the ownCloud blue everywhere?

**Comment by jancborchardt** [comment]
> We're not down to that level of details in the implementation yet, as it needs to be generic. so I want the workflow working first.

Sure sure, just thought I bring that up directly when I see it.

> Not sure I understand. Do you want the ownCloud blue everywhere?

Yep, the whole window should have one uniform background. That reduces lines and shapes and makes the process seem much simpler. Very important to not overwhelm people as this is the first thing they see of the desktop app.

**Comment by madeinffm** [comment]
Hey @danimo,

we'd like to suggest a decrease in spacing between the letters to the standard-value. Things will look much more "compact" then.

Another question: How are things going with owncloud in the future? Do we swap no Nextcloud? Are there different guidelines? To be honest, we're a bit concerned about the spin off and all the news lately regarding this topic.

cheers
florian from made in

**Comment by danimo** [comment]
@madeinffm I'm still working on it. I've also no intentions to move anywhere. As it stands there is only one desktop client, and one team making it. Don't worry :-).

Btw: you really should attend the ownCloud conference: https://conference.owncloud.org.

**Comment by madeinffm** [comment]
Alrighty, the thing is also, to be honest, that we have quite some problems with the client. Syncing is not that reliable unfortunately and sometimes the clients scan for hours and hours (and doesn't sync in that time). Also large files are problematic and causing errors. So we have to consider our options at the moment. 

Nevertheless it's good to put some ideas into the client designwise ;)

Cheers,
florian

**Comment by danimo** [comment]
@madeinffm Please post the details about your issues at central.owncloud.org. This is where we can help you best in that regard. How large are your files?

**Comment by jancborchardt** [comment]
@madeinffm the whole ownCloud / Nextcloud is indeed a bit confusing. :) I for example switched working full-time from ownCloud to Nextcloud but still help design-wise on the desktop client here as before. Like Daniel said there’s only one desktop app.

**Comment by madeinffm** [comment]
thanks for the clarification. We have certain files >2gb, which cause problems. Also in other cases the client doesn't sync (on multiple computers). We already tried a few things including a fresh install, but no luck, so I consider asking again in the forums, thanks.

Main thing is, that if the client crashes on certain files, it scans everything again, which takes a couple of hours. In that time nothing syncs and thats a problem ;)

cheers and a great weekend to you all!
florian

**Comment by Kawohl** [comment]
@dragotin @danimo @guruz is there anything i could pick up from here?

**Comment by guruz** [comment]
@danimo Any news?

**Comment by ogoffart** [comment]
@danimo   would you mind pushing your work in progress in some branch somewhere so we can continue from there?

**Comment by fmoc** [comment]
Released in 3.x.
