### ISSUE TITLE
Edit account's server URL 

### ISSUE THREAD

**Issue by schittli** [owncloud/client#5065]
### Expected behaviour

It would be great if the user could just change the account settings in the Windows Client, e.g. the password or the owncloud URL / Port.
### Actual behaviour

It Looks like Users have to create a new Desktop Client account if the Password or the URL changes.
### Steps to reproduce
1. Change the Owncloud Server Port or a users Password
2. Users can no longer connect to owncloud
### Server configuration

Operating system: ubuntu
ownCloud version: 9.0.2.2
### Client configuration

Client version: 2.2.2 6192
Operating system: Windows 10
OS language: English

**Comment by schittli** [comment]
Hi ckamm
Thank you very much for your answer!, 

I've just tested changing the password using log out / log in and it works :-)

Changing the local Config File worked, too :-), but it's a dangerous solution for non technical users.

Our Background is, that we had to change the Owncloud Connection Port because of "external forces", but I think it's not so unusual to refactor the IT and move some services. Just 1 year ago, we merged with another company and therefore the domain changed...

Therefore editing the Account could be a real life saver.

**Comment by ckamm** [comment]
@schittli My concern is that people might accidentally use an "Edit server url" feature inappropriately and lose data. Changing the server url is fine when the *same* server is now reachable under a different url. But it's dangerous when it's accidentally used to point an existing configuration to a different server.

If one synced ones data to a server, then changed the url to point to a fresh installation, nearly all local data would be deleted. 

So if we added this feature it'd need text like this: "**Warning**: Change the server url **only** if the **same** server is now reachable under a different address. Connecting an existing account to a different server **will result in files being deleted**."

**Comment by yan12125** [comment]
As a reference for others, I have to re-enter my password after changing the server URL. That's because I save my password in gnome-keyring and owncloud includes the server URL in the "username" field for the keyring. I guess it's time for GNOME to allow changing username in keyring entries lol.

**Comment by ogoffart** [comment]
See discussion in https://github.com/owncloud/client/issues/6376
