### ISSUE TITLE
http/2 support investigation

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5068]
This is a thread about http/2 for the sync client.

Investigation of http/2 support in the sync client relies on Qt. What is the current status of Qt support for http/2?

Has this been integrated into Qt production releases: https://codereview.qt-project.org/#/c/145762/ ?

@guruz

**Comment by danimo** [comment]
@moscicki No, not yet

**Comment by guruz** [comment]
-> https://github.com/owncloud/client/issues/3146
