### ISSUE TITLE
ownCloud Server 9.1.0 with sync client 2.2.2 (build 6192)

### ISSUE THREAD

**Issue by danielpetrovic** [owncloud/client#5070]
### Expected behaviour

Sync a file through Windows (10) sync client
Uploading files through webpage works fine and as expected
### Actual behaviour

  21-7-2016 12:48:03,                Continue blacklisting: Error downloading https://****_/remote.php/webdav/**_***/HARDWARE/Cluster 2016 Q3_.xlsx - server replied: Insufficient Storage (Sabre\DAV\Exception\InsufficientStorage)

***\* so you don't see what my server name is
### Steps to reproduce
1. try syncing any file, even new empty .txt
2. try editing file
### Server configuration

Operating system:
CentOS Linux Core 7.2.1511

Web server: 
Server version: Apache/2.4.6 (CentOS)
Server built:   Jul 18 2016 15:30:14

Database:
Server version: 5.5.47-MariaDB MariaDB Server

PHP version:
PHP 7.0.8 (cli) (built: Jun 23 2016 16:24:08) ( NTS )

ownCloud version:
9.1.0
Storage backend:
### Client configuration

Client version:
2.2.2 build 6192
Operating system:
Windows 10 Pro x64
OS language:
English 
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   (On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
   (See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
2. Web server error log:
3. ownCloud log (data/owncloud.log):
   {"reqId":"V5ClFI1qaV4B7uhlCblj0gAAAAA","remoteAddr":"****_","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\/1.1 507 Insufficient Storage\",\"Exception\":\"Sabre\\DAV\\Exception\\InsufficientStorage\",\"Code\":0,\"Trace\":\"#0 [internal function]: OCA\\DAV\\Connector\\Sabre\\QuotaPlugin->checkQuota('\\/PADACO-Managem...', Object(OCA\\DAV\\Connector\\Sabre\\File), Resource id #159, false)\n#1 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(1068): Sabre\\Event\\EventEmitter->emit('beforeWriteCont...', Array)\n#3 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/CorePlugin.php(511): Sabre\\DAV\\Server->updateFile('PADACO-Manageme...', Resource id #159, NULL)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/event\\/lib\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#7 \\/var\\/www\\/html\\/owncloud\\/3rdparty\\/sabre\\/dav\\/lib\\/DAV\\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \\/var\\/www\\/html\\/owncloud\\/apps\\/dav\\/appinfo\\/v1\\/webdav.php(56): Sabre\\DAV\\Server->exec()\n#9 \\/var\\/www\\/html\\/owncloud\\/remote.php(164): require_once('\\/var\\/www\\/html\\/o...')\n#10 {main}\",\"File\":\"\\/var\\/www\\/html\\/owncloud\\/apps\\/dav\\/lib\\/Connector\\/Sabre\\/QuotaPlugin.php\",\"Line\":108,\"User\":\"Daniel@padaco.nl\"}","level":4,"time":"2016-07-21T12:33:57+02:00","method":"PUT","url":"\/remote.php\/webdav\/PADACO-Management\/HARDWARE\/Cluster%202016%20Q3.xlsx","user":"**_******"}

**Comment by danielpetrovic** [comment]
Server is not responding anymore. HTTP 500 error...
Will revert to a back-up which was running 9.0.3 or 9.0.4

**Comment by reneneee** [comment]
We're experiencing the same client errors on all Windows machines (Windows 7) with client version 2.2.2 and server version 9.1. No HTTP 500 errors though ...

**Comment by danielpetrovic** [comment]
Probably the HTTP 500 error was my own fault, I tried tinkering with some config settings. As I saw some old threads stating it could have to do with filelocking. After remove the lines for APCu it caused an error in the database I think.

So for now will stay on 9.0.3 until the issue is fixed in the sync client.

**Comment by reneneee** [comment]
We narrowed down the issue a bit. The problem only occurs in the following scenario on owncloud 9.1 and Windows client 2.2.2

- User A has a quota set (e.g. 40 GB)
- User A shares a folder with user B
- User B is adding or modifying a file to the shared folder

User B will see the "Insufficient Storage" error message in the client even if all files stored in owncloud are less than 10GB.

Workarounds until the bug is fixed:

1. user B uses the web-frontend (or a different OS ... )
1. Quota of user A is set to unlimited

**Comment by ckamm** [comment]
@reneneee It's surprising to me that this problem would occur with the windows client but not with the linux client. They talk to the server in the same way and if there's a bug that makes the server say "InsufficientStorage" when it shouldn't, that should be the same on all clients.

**Comment by reneneee** [comment]
Right, now that you say it. In our setup all users using the Linux client were in "User A" situations (in my example above). So that lead us on the wrong path in the beginning ("It's working on Linux and failing on Windows").

So, in order to have a reproducable bug report, I'll summarize my scnario again:

The problem only occurs in the following scenario on owncloud 9.1 and client 2.2.2

  -  User A has a quota set (e.g. 40 GB)
  -  User A shares a folder with user B
  -  User B is adding or modifying a file to the shared folder

User B will see the "Insufficient Storage" error message in the client even if all files stored in owncloud are less than 10GB.

Workarounds until the bug is fixed:

  -  user B uses the web-frontend
or
  -  Quota of user A is set to unlimited

**Comment by ckamm** [comment]
@reneneee Thanks for the clarification and clear report!

**Comment by danielpetrovic** [comment]
Ah that explains it. These are all shared folders of User A yes, as we only work with shared folders in this setup. For now will stay on 9.0.3 until this is fixed on either client or server side.

**Comment by mcastroSG** [comment]
Hi hi:

I´m doing some extra test and getting the same error trying to include new files on shared with me folders on any OS and version. Right now the workaround that works for me was commented by @reneneee on https://github.com/owncloud/client/issues/5070#issuecomment-234478250

**Comment by mcastroSG** [comment]
Same behaviour for mobile clients

**Comment by vasyakrg** [comment]
>> Quota of user A is set to unlimited

confirm, did the same - it worked

**Comment by klausguenter** [comment]
Same problem here with oc 9.1 and Windows-client 2.2.2

user B can upload in a shared folder of user A via web-frontend, but not via windows-client.
Downloading works fine.

tried to upload 3MB photo on 200GB free space... :-)

**Comment by dragotin** [comment]
the cause here might be owncloud/core#25582

**Comment by bjornstromberg** [comment]
i've had same issue on ownCloud 9.1.0 (stable) 
running on 
centos 7 server with 3.10.0-327.4.4.el7.centos.plus.x86_64 kernel
PHP 5.4.16 (php-fpm) and nginx/1.6.3 

the client is 
arch linux with 4.4.19-1-lts kernel
owncloud client 2.2.3 (arch linux repo version 2.2.3-1)

error in client:
server replied: Insufficient Storage (Sabre\DAV\Exception\InsufficientStorage)

and it was solved by setting user A to unlimited Quota, then user B could upload to User A's shared folder.

so it is also giving problems on arch linux not only windows client.

**Comment by ogoffart** [comment]
Closing this old issue which is unlikely to be a client bug.
Please re-open a bug on the core bug tracker. Or ask for support on https://owncloud.org/support/
