### ISSUE TITLE
ADFS on mac client throws error, blank webkit window

### ISSUE THREAD

**Issue by felixboehm** [owncloud/client#5071]
### Expected behaviour

Authenticating with SAML, webkit should show the IDPs login 
### Actual behaviour

webkit opens with a blank screen

```
OCC::AbstractNetworkJob::start: !!! OCC::DetermineAuthTypeJob created for "https://cloud.xxx.de" + "" "OCC::OwncloudSetupWizard"
OCC::DetermineAuthTypeJob::finished: virtual bool OCC::DetermineAuthTypeJob::finished() "https://login2.xxx.de/adfs/ls/?SAMLRequest=fZFfT4MwFMW%2FCun7KGXKsBkkuD24ZCoZ6IMvptBu1JQWe4t%2Fvr1sOJ2J2fM959xzf3cOrFUdzXrX6I147QU476NVGuhhkKDeamoYSKCatQKoq2mR3a5p6Ae0s8aZ2ijkZQDCOmn0wmjoW2ELYd9kLR426wQ1znVAMa6V6bm%2F6198LnDRyKoySrjGBzB4nxni%2FL4okbccSkjN9nG%2FZmV2UodHN%2BNbwAow8lbLBD2TMJxO4wvBeRDxeBZf1duqjsgVI5GISRQNMoBerDQ4pl2CwoBEk2A2CUkZzCi5pEHwhLz8%2B5xrqbnUu%2FO3V6MI6E1Z5pOx%2BKOwcCg9CFA63xOkh8X2hOn5WHYEidJ%2FscEPtjk%2ByR%2BXdfRuCFwtc6Nk%2FellSpn3hRXMiQQRhNPR8vfb6Rc%3D&RelayState=ss%3Amem%3A75e82767f8bf0545acad0b7051adf747e2dfa64dc94528a42edf90ee1cd25729"
OCC::PostfixLineEdit::setFullText: "https://cloud.xxx.de"
QIODevice::read: device not open
```
### Steps to reproduce

I can't reproduce this on my mac,
reproducible on users computer. 
- tried owncloud reinstall
- link to https://login2.xxx.de/adfs/ls/... works in browser
### Server configuration

Operating system: Mac

**Comment by felixboehm** [comment]
@ogoffart

**Comment by ogoffart** [comment]
In order to debug the problem, we can use the inspector.
It can be enabled by setting the "OWNCLOUD_SHIBBOLETH_DEBUG"  environment variable to "1"  before starting the client.
Then right click on the view should allow to open the inspector.

**Comment by felixboehm** [comment]
Debug mode doesn't allow me to open Inspector

**Comment by felixboehm** [comment]
Webkit error handling for ssl issues ?
http://stackoverflow.com/questions/8362506/qwebview-qt-webkit-wont-open-some-ssl-pages-redirects-not-allowed

**Comment by michaelstingl** [comment]
@felixboehm Could this be a problem with unsupported cipher suites? (see https://github.com/owncloud/enterprise/issues/1370)

**Comment by felixboehm** [comment]
Could, thanks for the hint. This page needs to be called with the webkit browser, to check supported ciphers:
https://cc.dcsec.uni-hannover.de/

Extra little program? Button in debug mode?

**Comment by dragotin** [comment]
Ok, I tried this patch:
```c++
--- a/src/gui/creds/shibboleth/shibbolethwebview.cpp
+++ b/src/gui/creds/shibboleth/shibbolethwebview.cpp
@@ -60,11 +60,15 @@ ShibbolethWebView::ShibbolethWebView(AccountPtr account, QWidget* parent)
     setAttribute(Qt::WA_DeleteOnClose);
 
     QWebPage* page = new UserAgentWebPage(this);
+    page->setNetworkAccessManager( account->networkAccessManager() );
+
     connect(page, SIGNAL(loadStarted()),
             this, SLOT(slotLoadStarted()));
     connect(page, SIGNAL(loadFinished(bool)),
             this, SLOT(slotLoadFinished(bool)));
 
+    connect( account->networkAccessManager(), SIGNAL(sslErrors(QNetworkReply*,QList<QSslError>)),
+             this, SLOT(slotSSLError(QNetworkReply*,QList<QSslError>)) );
     // Make sure to accept the same SSL certificate issues as the regular QNAM we use for syncing
     QObject::connect(page->networkAccessManager(), SIGNAL(sslErrors(QNetworkReply*,QList<QSslError>)),
             _account.data(), SLOT(slotHandleSslErrors(QNetworkReply*,QList<QSslError>)));
@@ -91,6 +95,11 @@ ShibbolethWebView::ShibbolethWebView(AccountPtr account, QWidget* parent)
     restoreGeometry(settings.value(ShibbolethWebViewGeometryC).toByteArray());
 }
```
to make the webview use the same QNAM as the Account object, and also installed an (additional probably) ssl error handler, but to no success. When I load the guj website through mitmproxy on linux, the WebView page stays blank instead of displaying the login form.

@jturcotte @ogoffart what I do not understand: It looks like as if the webview already uses the same QNAM as the Account, even without the patch above. Where is that set?

**Comment by ogoffart** [comment]
I don't think they share the QNAM, but they share the CookieJar  (set in ShibbolethWebView::ShibbolethWebView )

**Comment by guruz** [comment]
I remember doing something related to this but I can't find the commit anymore. Strange.

I had discussions with people in the team about why they don't use the same QNAM but I don't remember why..

**Comment by dragotin** [comment]
@felixboehm can you please ask the user to try 
https://download.owncloud.com/desktop/daily/ownCloud-2.2.3.3549-nightly20160725.pkg
and let him start it with the environment variable `OWNCLOUD_SHIBBOLETH_DEBUG=1` defined?

It will show an new additional window opened in webkit that displays the cipher information. Maybe that gives us new information. At best he replies with a screenshot.

**Comment by guruz** [comment]
> Then right click on the view should allow to open the inspector.

@jturcotte maybe it could be auto-opened..

**Comment by danimo** [comment]
Which OS X version is the affected user on?

**Comment by dragotin** [comment]
Pull request: #5080

**Comment by guruz** [comment]
@felixboehm Tomorrow's nightly will automagically open a window when setting ```OWNCLOUD_SHIBBOLETH_DEBUG``` and then adding a shib account (or in general having the shib web view opened).

**Comment by dragotin** [comment]
@felixboehm news here?

**Comment by felixboehm** [comment]
Did not get response from customer.
link to the special client not working  anymore ...

**Comment by guruz** [comment]
@felixboehm The 2.2.3 release should have this ```OWNCLOUD_SHIBBOLETH_DEBUG```.
(The 2.3 nightlies maybe only from tomorrow..)

**Comment by guruz** [comment]
I'm assuming this is fixed? :)
