### ISSUE TITLE
Problem when reverting file version

### ISSUE THREAD

**Issue by cleristononline** [owncloud/client#5073]
### Expected behaviour
When I revert a file version, the correct is just return file on my pc to older version

### Actual behaviour
The reversion is happening but the message below is show during next synchronisation.
This sync would reset the files to an erlier time in the sync folder 'ownCloud'.
This might be because a backup was restored on the server.
Continuing the sync as normal will cause all your files to be overwritten by an older file in an earlier state. Do you want to keep your local most recent files as conflict files?

### Steps to reproduce
1. Create a new file, for example test.xlsx
2. After 1 minute, change the file
3. after 1 minute, try to rever file version (on webpage of ownCloud)
4. You will se the message above.
5. The sync occurs, but the message insists on being presented.

### Server configuration
Operating system: Cent OS 7 with all updates

Web server: httpd-2.4.6-40.el7.centos.4.x86_64

Database: mariadb-server-5.5.47-1.el7_2.x86_64

PHP version: php55-php-5.5.21-4.el7.x86_64

ownCloud version: 9.0.4

Storage backend: loca disk (SAS 15k) 60 GB disk free, XFS or EXT3

### Client configuration
Client version: Version 2.2.2 (build 3472)

Operating system: MAC 10.11.5 (15F34) (same error on Windows 7)

OS language: English

Installation path of client: Default path /Applications/owncloud.app

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

Cleristons-MacBook-Air:ownCloud cleriston$ tail -15 .owncloudsync.log 
#=#=#=# Syncrun started  until  (0 msec)
12:43:58|208|Logs/owncloudsync.log|INST_NEW|Up|1469104959||126327||4||201|0|0|||INST_NONE|
#=#=#=# Syncrun started  until  (0 msec)
12:44:19|225|untitled folder|INST_NEW|Up|1469105050||68||4||201|0|0|||INST_NONE|
#=#=#=# Syncrun started  until  (0 msec)
#=#=#=# Syncrun started  until  (0 msec)
12:52:45|216|untitled folder|INST_REMOVE|Up|1469105059|5790c3a378a7a|0|00006560ocsoyurvoemy|4||204|0|0|||INST_NONE|
#=#=#=# Syncrun started  until  (0 msec)
#=#=#=# Syncrun started  until  (0 msec)
12:59:09|215|untitled folder|INST_NEW|Up|1469105947||68||4||201|0|0|||INST_NONE|
#=#=#=# Syncrun started  until  (0 msec)
#=#=#=# Syncrun started  until  (0 msec)
#=#=#=# Syncrun started  until  (0 msec)
14:22:37|246|untitled folder|INST_REMOVE|Up|1469105949|5790c71d6bc66|0|00006719ocsoyurvoemy|4||204|0|0|||INST_NONE|
#=#=#=# Syncrun started  until  (0 msec)

2. Web server error log:
[root@brspocsrv01 httpd]# tail -15 error_log 
[Wed Jul 20 22:37:22.840271 2016] [lbmethod_heartbeat:notice] [pid 15138] AH02282: No slotmem from mod_heartmonitor
[Wed Jul 20 22:37:22.866622 2016] [mpm_prefork:notice] [pid 15138] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.5.21 configured -- resuming normal operations
[Wed Jul 20 22:37:22.866656 2016] [core:notice] [pid 15138] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Jul 20 22:41:44.760953 2016] [mpm_prefork:notice] [pid 15138] AH00170: caught SIGWINCH, shutting down gracefully
[Wed Jul 20 22:41:45.816763 2016] [suexec:notice] [pid 15413] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 20 22:41:45.842633 2016] [auth_digest:notice] [pid 15413] AH01757: generating secret for digest authentication ...
[Wed Jul 20 22:41:45.843402 2016] [lbmethod_heartbeat:notice] [pid 15413] AH02282: No slotmem from mod_heartmonitor
[Wed Jul 20 22:41:45.876328 2016] [mpm_prefork:notice] [pid 15413] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.5.21 configured -- resuming normal operations
[Wed Jul 20 22:41:45.876364 2016] [core:notice] [pid 15413] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Wed Jul 20 22:55:39.371153 2016] [mpm_prefork:notice] [pid 15413] AH00170: caught SIGWINCH, shutting down gracefully
[Wed Jul 20 22:55:40.429031 2016] [suexec:notice] [pid 16091] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Wed Jul 20 22:55:40.452075 2016] [auth_digest:notice] [pid 16091] AH01757: generating secret for digest authentication ...
[Wed Jul 20 22:55:40.452637 2016] [lbmethod_heartbeat:notice] [pid 16091] AH02282: No slotmem from mod_heartmonitor
[Wed Jul 20 22:55:40.476596 2016] [mpm_prefork:notice] [pid 16091] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.1e-fips PHP/5.5.21 configured -- resuming normal operations
[Wed Jul 20 22:55:40.476623 2016] [core:notice] [pid 16091] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'

3. ownCloud log (data/owncloud.log):
[root@brspocsrv01 data]# tail -20 owncloud.log 
{"reqId":"V4-VnTVZXoOsTTEGk1hXdAAAAAE","remoteAddr":"10.0.5.10","app":"PHP","message":"file_put_contents(\/var\/www\/html\/owncloud\/data\/.htaccess): failed to open stream: Permission denied at \/var\/www\/html\/owncloud\/lib\/private\/setup.php#485","level":3,"time":"2016-07-20T19:48:45+00:00","method":"GET","url":"\/owncloud\/index.php","user":"--"}
{"reqId":"V4-V0elgNb1DZBn3gbrzEgAAAAQ","remoteAddr":"10.0.5.10","app":"PHP","message":"file_put_contents(\/var\/www\/html\/owncloud\/data\/.htaccess): failed to open stream: Permission denied at \/var\/www\/html\/owncloud\/lib\/private\/setup.php#485","level":3,"time":"2016-07-20T19:49:37+00:00","method":"POST","url":"\/owncloud\/index.php","user":"--"}
{"reqId":"V4-V0elgNb1DZBn3gbrzEgAAAAQ","remoteAddr":"10.0.5.10","app":"PHP","message":"mkdir(): Permission denied at \/var\/www\/html\/owncloud\/lib\/private\/setup.php#287","level":3,"time":"2016-07-20T19:49:37+00:00","method":"POST","url":"\/owncloud\/index.php","user":"--"}
{"reqId":"V4-WIqFwMZ-Z3@9bj4W6HQAAAAs","remoteAddr":"10.0.5.10","app":"PHP","message":"file_put_contents(\/var\/www\/html\/owncloud\/data\/.htaccess): failed to open stream: Permission denied at \/var\/www\/html\/owncloud\/lib\/private\/setup.php#485","level":3,"time":"2016-07-20T19:50:58+00:00","method":"GET","url":"\/owncloud\/index.php","user":"--"}
{"reqId":"V4-WTqB4teAbhCoxnRCm2QAAAAY","remoteAddr":"10.0.5.10","app":"PHP","message":"file_put_contents(\/var\/www\/html\/owncloud\/data\/.htaccess): failed to open stream: Permission denied at \/var\/www\/html\/owncloud\/lib\/private\/setup.php#485","level":3,"time":"2016-07-20T19:51:42+00:00","method":"POST","url":"\/owncloud\/index.php","user":"--"}
[root@brspocsrv01 data]#

**Comment by ckamm** [comment]
@cleristononline The message exists to allow users to double check that they'll not be losing data due to the backup being restored on the server. Is the problem that the message pops up several times? It should pop up once only.

**Comment by cleristononline** [comment]
Hi @ckamm Yes You're totally correct. The message is important, but just one time. I did some tests here. When I close the ownCloud Desktop App and open again the message stops to appear.

**Comment by guruz** [comment]
FYI @ogoffart

**Comment by ogoffart** [comment]
That's the expected behavior.  We only use heuristics to detect this condition, and we might get it wrong.
