### ISSUE TITLE
files with unsupported characters on Windows silently ignored (2.1)

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5076]
A file with unsupported character on Windows (such as a colon) is completely silently ignored by owncloud sync client 2.1. They are not appearing in "Ignored files" list.

This is misleading. These cases should be reported with a reason description in the "Ignored files" list.

**Comment by guruz** [comment]
The current version is 2.2.2.
What is the behaviour with this version?

**Comment by guruz** [comment]
@moscicki Did you have a chance to try with 2.2.3?

**Comment by moscicki** [comment]
Not yet, sorry. We will give it a try at the next version build for us.

Shouldn't this test be automated somehow or put into the testing mechanism before release?

**Comment by ogoffart** [comment]
the latest client show the file as not sync'ed

![screenshot_20161011_163224](https://cloud.githubusercontent.com/assets/959326/19274437/69fd4ba0-8fd0-11e6-9561-51218586a48e.png)

**Comment by moscicki** [comment]
Hello,

There appears to be a regression in 2.2.4 and 2.3.1. Files with colon are silently ignored.

kuba
