### ISSUE TITLE
Update copyright

### ISSUE THREAD

**Issue by rperezb** [owncloud/client#5079]
Update Copyright to 👍 
```
@copyright Copyright (c) 2016, ownCloud GmbH. 
```

Related to: https://github.com/owncloud/core/pull/25518

**Comment by hefee** [comment]
Not done completly:
$ grep -r 'ownCloud.*Inc' src

src/libsync/theme.cpp:    re += tr("<p>Copyright ownCloud, Incorporated</p>");
src/libsync/owncloudtheme.cpp:               "<p>Copyright ownCloud, Inc.</p>"

**Comment by ckamm** [comment]
@hefee I think you were checking in the 2.2 branch. @danimo had merged his change to the master branch. No more releases are planned from the 2.2 branch as far as I am aware.
