### ISSUE TITLE
[OS X] Buttons are not aligned in 'Enter user credentials' page of the wizard

### ISSUE THREAD

**Issue by davitol** [owncloud/client#5083]
### Expected behaviour

The buttons should be aligned
### Actual behaviour

The buttons are not right located

![screen shot 2016-07-26 at 17 44 47](https://cloud.githubusercontent.com/assets/10596560/17172463/8c02de66-53f5-11e6-826d-ab044807f5c8.png)

Version 2.2.3-nightly20160726 (build 3550).

**Comment by guruz** [comment]
I guess this will be fixed with https://github.com/owncloud/client/issues/5064

**Comment by guruz** [comment]
@ogoffart Funny, another margin bug that only happens on OS X?

**Comment by guruz** [comment]
Still happening with Qt 5.6.2

**Comment by guruz** [comment]
Still a problem with Qt 5.10.1

**Comment by TheOneRing** [comment]
Still exists

**Comment by erikjv** [comment]
In the 2.9 branch, this issue cannot be reproduced anymore. This might have to do with the removal of a hidden wizard page, or with the fact that now no buttons/widgets are added/removed to the QHBoxLayout containing those buttons.

When looking into this issue on the Qt side, I noticed that there are mac-specific margins for that box layout. Setting those to 0 (zero) also removes the issue. So my guess is that for new buttons some margins are applied twice.
