### ISSUE TITLE
Missing update section in general tab using OS X

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/client#5085]
### Expected behaviour

Update section included in general tab suggesting to update if needed.
### Actual behaviour

It does not appear

![screen shot 2016-07-28 at 09 52 19](https://cloud.githubusercontent.com/assets/9048796/17205070/5c9bf234-54a9-11e6-8f7f-a8ce6afbc923.png)
### Steps to reproduce

Using OS X client do:
1. Go to general tab.
### Client configuration

Client version:
2.2.3beta1 (build 3556)

Operating system:
OS X El Capitan 10.11

OS language:
English

**Comment by SergioBertolinSG** [comment]
cc @guruz

**Comment by guruz** [comment]
Thx. We should investigate why.. Because I saw Sparkle debug messages in console still.

**Comment by guruz** [comment]
@danimo Is this because of Sparkle?

**Comment by danimo** [comment]
@guruz yes, expected behavior. We don't have a dialog integration with sparkle.
