### ISSUE TITLE
Linux 2.2.2 client segfaults when Gnome auto-proxy setting used

### ISSUE THREAD

**Issue by danmac-uk** [owncloud/client#5086]
### Expected behaviour
Fire up client, sync files, have fun.

### Actual behaviour
Fire up client, experience segfault seconds after appearance of the GUI, no fun.

### Steps to reproduce
1. Install a totally fresh copy of owncloud client. (unconfigured)
2. Set up an "automatic" proxy in Gnome network settings. (mine is set to a WPAD file I'm happy to provide on request)
3. Start owncloud client.
4. Wait a few seconds for it to segfault. (it will fire up the GUI then die seconds later)

or

1. Install and configure owncloud client just fine without having an auto proxy configured.
2. Disable proxy within owncloud client settings.
3. Reinstate the auto proxy settings within Gnome.
(owncloud client at this point will be perfectly happy)
4. Set owncloud client back to "Use system proxy".
5. Within seconds it will segfault.

(does not seem to be affected if Gnome is set to manual proxy config)

### Client configuration
Client version: Client 2.2.2 w/ Qt 5.7.0

Operating system: Manjaro Gnome stable branch (Gnome 3.20.2)

OS language: English

Installation path of client: /usr/bin

### Logs

(attached, suffice it to say this appears to happen the first time any HTTP comms is attempted, including the update notifier)

[owncloud-client-log.txt](https://github.com/owncloud/client/files/388058/owncloud-client-log.txt)

**Comment by guruz** [comment]
You need to report this upstream, possibly it's fixed already though.

https://github.com/owncloud/client/issues/5128#issuecomment-242678393

**Comment by danmac-uk** [comment]
I am at a loss what "report this upstream" would entail. Qt? GNOME? Distro? FYI the ownCloud client is the only application in which I have experienced this behavior.

Nor am I familiar with how to report something like this to either of those projects.

Happy to re-test with my currently updated setup. But, you know, throw me a bone here bud.

**Comment by guruz** [comment]
@danmac-uk ... if it is the same crash, which i had assumed because we had several people reporting it :)
You could run the client in gdb and then run ```thread apply all bt``` and give us this output on crash.

Then we could see if it is the same crash.
According to comments I've heard it was already fixed.
