### ISSUE TITLE
Client 2.2.2 crashes on OS X 10.9.5

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#5094]
### Expected behaviour
ownCloud client should run.

### Actual behaviour
ownCloud client crashed. Report was sent.

The last client versions, the client worked very reliably. However, this week I had two crashes of the OS X client. One was directly after wake-up in a network with a splash-screen for mobile use (not sure if it is related): 
````
Sat Jul 30 11:46:47.383 <airportd[90]> _doAutoJoin: Already associated to “BNF”. Bailing on auto-join.
Sat Jul 30 11:47:24.988 <airportd[90]> _handleLinkEvent: Got an error trying to query WiFi for power. Resetting state variables.
````
The other time was completely unexpected (no larger sync, no network change, nothing). Each time a report was sent. After that, the client could be restarted without problems.

Question: Do these automatic reports contain enough information for you to figure out what happened? Logging is a bit difficult, because it would have to be enabled constantly and become kind of large. And I can't reproduce this error.

**Comment by guruz** [comment]
We're getting crash reports and can have a look.
However 2.2.3beta1 has quite some crash fixes, you should use that one..

**Comment by guruz** [comment]
(I'm closing this, I don't know what else to do with it. I didn't ever see that airport message being rekated)

**Comment by tflidd** [comment]
> We're getting crash reports and can have a look.
> However 2.2.3beta1 has quite some crash fixes, you should use that one..

perfect. it was no serious issue for me. I will soon upgrade.
