### ISSUE TITLE
[Linux] [2.2.?] operation canceled 

### ISSUE THREAD

**Issue by ypxie** [owncloud/client#5099]
### Expected behaviour
Tell us what should happen
Should synchronize the file correctly

### Actual behaviour
Tell us what happens instead
Does not synchronize the file correctly. Only reports operation canceled and stop synchronizing
### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system:
ubuntu 14.04
Web server: 

Database:
sql 
PHP version:

ownCloud version:

Storage backend:
local hard drive
### Client configuration
Client version:
latest version
Operating system:

OS language:
English
Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
Which version do you exactly use? 2.2.2 or 2.2.3beta1?
Do you have any other error message than ```Operation Canceled```? They often come together with others.
Maybe you can start the client with ```owncloud --logfile -``` on terminal to see more output.

**Comment by guruz** [comment]
@ypxie Any input from you?

**Comment by ypxie** [comment]
Hi I have solved this problem by update the server to version 8. (version 9 does not work for some reasons.)

**Comment by RealRancor** [comment]
@ypxie If there is an issue between 8.2 and 9.0 you probably should create a new issue at the core bugtracker: https://github.com/owncloud/core/issues
