### ISSUE TITLE
Sorting of selective sync list

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#5101]
### Expected behaviour
Should be sorted case insensitive.

### Actual behaviour
The list of folders is sorted case sensitive.

### Client configuration
Client version: 2.2.2

Operating system: Linux

OS language: German

**Comment by dragotin** [comment]
@hodyroff your bug!

**Comment by guruz** [comment]
Please try 2.3.0, i think @ckamm might have had done this already?

https://github.com/owncloud/client/pull/4864

**Comment by guruz** [comment]
@hodyroff Did you try a 2.3 nightly?

**Comment by davitol** [comment]
:+1: Tested in 2.3.0 nightly
