### ISSUE TITLE
Backup Detected message with no accompaning data

### ISSUE THREAD

**Issue by mgaman** [owncloud/client#5109]
Every now & then I get a message pop-up "Backup Detected" due to date conflicts and given a choice between keeping the local file or allowing the sync to go forward.

![untitled](https://cloud.githubusercontent.com/assets/3582286/17460543/2735fc34-5c74-11e6-94e3-36c7706b950b.png)

The pathname of the offending file is not given, so I can't make an informed decision as how to act.
### Server configuration

Operating system:

Web server: 
Linux DietPi 4.4.13-v7+ #894 SMP Mon Jun 13 13:13:27 BST 2016 armv7l GNU/Linux
Database:
Mysql

PHP version:
PHP 5.6.24-0+deb8u1 (cli) 

ownCloud version:
8.1.9

Storage backend:
### Client configuration

Client version:
Version 2.2.2 (build 6192)
Operating system:
Window 10 64 bit

OS language:

Installation path of client:
C:\Program Files (x86)\ownCloud>
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   (On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
   (See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

No ouput
1. Web server error log:
   /var/log/apache2/error.log is empty
2. ownCloud log (data/owncloud.log):
   {"reqId":"Q\/jga\/a221ql6y7bMiMN","remoteAddr":"79.177.220.46","app":"core","message":"imagecreatefrombmp: imagecreatetruecolor failed for file \"\/var\/www\/owncloud\/data\/henryd\/files\/Photos\/mumpics\/Scan.BMP\" with dimensions 466x-663","level":2,"time":"2016-08-07T04:44:46+00:00"}
   {"reqId":"R8d5qBKgi0HzBFI9OWch","remoteAddr":"79.177.220.46","app":"PHP","message":"imagecreatetruecolor(): Invalid image dimensions at \/var\/www\/owncloud\/lib\/private\/image.php#700","level":3,"time":"2016-08-07T04:44:47+00:00"}
   {"reqId":"R8d5qBKgi0HzBFI9OWch","remoteAddr":"79.177.220.46","app":"core","message":"imagecreatefrombmp: imagecreatetruecolor failed for file \"\/var\/www\/owncloud\/data\/henryd\/files\/Photos\/mumpics\/Scan-042.BMP\" with dimensions 1178x-616","level":2,"time":"2016-08-07T04:44:47+00:00"}
   {"reqId":"HwXCb7bqcKxzmHHSSkFR","remoteAddr":"79.177.220.46","app":"PHP","message":"imagecreatetruecolor(): Invalid image dimensions at \/var\/www\/owncloud\/lib\/private\/image.php#700","level":3,"time":"2016-08-07T04:44:48+00:00"}
   {"reqId":"HwXCb7bqcKxzmHHSSkFR","remoteAddr":"79.177.220.46","app":"core","message":"imagecreatefrombmp: imagecreatetruecolor failed for file \"\/var\/www\/owncloud\/data\/henryd\/files\/Photos\/mumpics\/Scan-001.BMP\" with dimensions 861x-1311","level":2,"time":"2016-08-07T04:44:49+00:00"}
   {"reqId":"KYLJfk2uhrToKrCKeG6M","remoteAddr":"79.177.220.46","app":"PHP","message":"imagecreatetruecolor(): Invalid image dimensions at \/var\/www\/owncloud\/lib\/private\/image.php#700","level":3,"time":"2016-08-07T04:44:49+00:00"}
   {"reqId":"KYLJfk2uhrToKrCKeG6M","remoteAddr":"79.177.220.46","app":"core","message":"imagecreatefrombmp: imagecreatetruecolor failed for file \"\/var\/www\/owncloud\/data\/henryd\/files\/Photos\/mumpics\/4\/Scan-045.BMP\" with dimensions 680x-979","level":2,"time":"2016-08-07T04:44:49+00:00"}
   {"reqId":"3EMWGdm7yz1p5ujcuCPD","remoteAddr":"79.177.220.46","app":"PHP","message":"imagecreatetruecolor(): Invalid image dimensions at \/var\/www\/owncloud\/lib\/private\/image.php#700","level":3,"time":"2016-08-07T04:44:50+00:00"}
   {"reqId":"3EMWGdm7yz1p5ujcuCPD","remoteAddr":"79.177.220.46","app":"core","message":"imagecreatefrombmp: imagecreatetruecolor failed for file \"\/var\/www\/owncloud\/data\/henryd\/files\/Photos\/mumpics\/4\/Scan-015.BMP\" with dimensions 774x-1105","level":2,"time":"2016-08-07T04:44:50+00:00"}
   {"reqId":"jLMCQ\/gcvFT0toiJDN+F","remoteAddr":"79.177.220.46","app":"PHP","message":"imagecreatetruecolor(): Invalid image dimensions at \/var\/www\/owncloud\/lib\/private\/image.php#700","level":3,"time":"2016-08-07T04:45:01+00:00"}
   {"reqId":"jLMCQ\/gcvFT0toiJDN+F","remoteAddr":"79.177.220.46","app":"core","message":"imagecreatefrombmp: imagecreatetruecolor failed for file \"\/var\/www\/owncloud\/data\/henryd\/files\/Photos\/mumpics\/3\/Scan-001.BMP\" with dimensions 901x-568","level":2,"time":"2016-08-07T04:45:01+00:00"}

**Comment by RealRancor** [comment]
@mgaman Could you try with 2.2.3 which has https://github.com/owncloud/client/pull/5104 listed in its changelog: https://owncloud.org/changelog/desktop/

**Comment by mgaman** [comment]
I installed 2.2.3 4 days ago and there hasn't been a single occurrence of the problem.
Job Done! Thanks

**Comment by msilversides** [comment]
I have a couple of user upgraded to 2.2.3 and we're still seeing this issue - 2 users upgraded yesterday and the error is displaying on files that they have access to but are not using.

**Comment by mgaman** [comment]
My installation is fine. I have determined which files were affected in
2.2.2 and the problem does not recur with 2.2.3

**Comment by msilversides** [comment]
What did you do with these files & was there a specific issue with them? I can identify them easily enough as they're in the error log. So far I've been removing them form the sync list.

**Comment by mgaman** [comment]
I did nothing special. What was your response to the 'backup detected'
message? sync or leave the original? In my case the problem files were
gnucash transactions so by choosing 'sync' my transactions were lost and
the original file came back. Thats how I spotted what was going on.

**Comment by msilversides** [comment]
I've tried both options but the problem has kept repeating itself. We're using it in an environment with circa 40 users, but restricting access rights to files/directories on a needs basis. Different users report different files prompting the error & it also seems to be limited to a small number of files. My solution to date has been to uncheck the file(s) in the sync list as they're not critical once and can still be access via the browser if necessary. The issue only started appearing when we upgraded to client 2.2.2. It's an annoyance more than anything else.

**Comment by paulmelis** [comment]
I'd like to add a UX issue for this dialog: the problem is that it shows up suddenly with focus on my MATE desktop and if you happen to be typing at that moment you can accidentally pick one of the options when pressing enter. This is horrible. It would be better to turn the message into a notification and force the user to got into the settings window to make the choice.

**Comment by MONMMK** [comment]
Hi I am facing same issue. 
My OC version is 8.1.9 on Linux 14.04.3.
Any solution please?

**Comment by ragokin** [comment]
Hi - I've had this happen since a team member added a folder called "Backup" If you remove or Unsync this folder, does this solve the issue for you - I * Think * That solved my issue.

**Comment by LukasRo** [comment]
I have the same problem, using v2.2.4 build 6408.

I run the client on a windows server to sync the folrders and access it via smb.
That's why I don't see this "backup detected" message.... tha bad thing the whole sync stops until I click on one of the two offered options. Is there a possibility to automastically skipü this message with the "keep files"-choice?!

**Comment by pierreozoux** [comment]
Hi!

I'm hitting the same issue with a team of 10 people.
They get this pop up every hour or so.
I don't see any strange logs on the server.
I have a normal filesystem as data backend (raid mirror)

Server is Nextcloud 10.0.1 and client is 2.2.4 on Linux.

Let me know if we can do anything to help debug this!

**Comment by pierreozoux** [comment]
@guruz could you change mileston please, as it doesn't seem to be solved by 2.2.4?

**Comment by guruz** [comment]
@LukasRo You are in the wrong issue, this issue is about the dialog box having more data
@pierreozoux You are in the wrong bugtracker, this is for the ownCloud client. Your problem sounds like a server issue.

**Comment by pierreozoux** [comment]
@guruz I don't understand why it would be a server issue in my case?
Maybe it is, but we don't understand why there is this message.
And the message is wrong as I didn't restore a backup.

So either the client is lying or the server is telling the client there is a backup.

But from my point of view, I don't know. I just know that the client is lying to me :)

**Comment by RealRancor** [comment]
@pierreozoux Sure, there might be something wrong. But the issue here is to discuss / report that the message is not telling the path of the file which got restored. :-)

**Comment by pierreozoux** [comment]
@RealRancor ok get it, sorry for the noise, should I open a new issue?

**Comment by RealRancor** [comment]
There is a new thread about that at central: https://central.owncloud.org/t/a-backup-was-restored-on-the-server/3446

Will see if @guruz thinks a new bugreport should be reported instead.

**Comment by guruz** [comment]
-> https://github.com/owncloud/client/issues/5260

:)

**Comment by vsaso** [comment]
Hi, we have same issue - 20+ users who use desktop client.

Until there comes a fix, what is the solution? Do we choose Normal sync or Keep local files? Please provide us best step-by-step solution, because that is obviously a bug.
I am not in favor of keeping local files as conflict because that means hours of comparing and editing files. I am also not in favor of normal sync if that means we are going to lose last versions of  files.

**Comment by RealRancor** [comment]
@vsaso You're in the wrong issue as explained in https://github.com/owncloud/client/issues/5109#issuecomment-255371391

Workaround is currently to downgrade to 2.2.0: https://central.owncloud.org/t/a-backup-was-restored-on-the-server/3446/8?u=realrancor

**Comment by ogoffart** [comment]
If there was no backup restored. the Normal sync should be preffered as it will not create conflict files.

**Comment by ogoffart** [comment]
This message is no longer shown for recent server (>=9.1).  So i consider that this issue can be closed.

**Comment by CorneelDragon** [comment]
@ogoffart  Could this fix be backported or fixed client-side as well? We are running an ownCloud instance with 20.000 users and 100 mil files and we did a downgrade from 9.0.x to 8.2.x since 9.0.x gave a lot of issues. So it will take some time before we do another upgrade.

**Comment by guruz** [comment]
@CorneelDragon The patch linked above also adds a 2h difference heuristic independant of the server version. This should help you too.
You can try a 2.3 nightly if you want. https://owncloud.org/install/#testing-development

**Comment by CorneelDragon** [comment]
Thanks for the suggestion, I will distribute this version with my colleagues who tested the issues earlier.

**Comment by parisilocker** [comment]
We have a user using ownCloud en_US (en_US) 2.2.4 (build 6408) sync client on Windows 10 x64 and is getting "

`---------------------------
Backup detected
---------------------------
This sync would reset the files to an erlier time in the sync folder 'ownCloud'.
This might be because a backup was restored on the server.
Continuing the sync as normal will cause all your files to be overwritten by an older file in an earlier state. Do you want to keep your local most recent files as conflict files?
---------------------------
Keep Local Files as Conflict   Normal Synchronisation   
---------------------------
`

Note erlier is spelled wrong.

Running ownCloud 9.1.2 (stable) on Ubuntu 16.0.4.

The files are on a SMB share.

I have attached a large log file.

[log - Copy.zip](https://github.com/owncloud/client/files/625704/log.-.Copy.zip)

What to do?

**Comment by RealRancor** [comment]
Reading previous comments like https://github.com/owncloud/client/issues/5109#issuecomment-264145287 before posting might help.

**Comment by yasuoiwakura** [comment]
Downngraded the client to 2.2.0 (6076), still get the message.
using OC 9.1.4 and 8.1.7 (not sure wich one throw the message)

**Comment by guruz** [comment]
Try the 2.3.0 beta1 or rc1..
https://owncloud.org/install/#testing-development

**Comment by yasuoiwakura** [comment]
no more problems at the moment, build 6752

**Comment by yasuoiwakura** [comment]
Got the message again after moving to another timezone (and moving some data).
client 2.3.2 build 6928 @  ownCloud 8.1.7 (stable)

Still no accompaning data
