### ISSUE TITLE
Installation failure due to unmet repositories - Ubuntu 

### ISSUE THREAD

**Issue by LKgY** [owncloud/client#5110]
### Expected behaviour

Being able to install and use OC. 
### Actual behaviour

Installation not possible due to supposed unmet repositories. Version 1.8 was working fine, yet I was looking to install version 2.2. When I could not get version 2.2 to run for some reason, I went to install version 1.8 without first removing version 2.2. At one point I also installed an OC version for the wrong version of Ubuntu (version 16). Since then I have been unable to install OC (see below installation log).
### Steps to reproduce
1. 
2. 
3. 
### Server configuration

Operating system:
Hosted server - unknown

Web server: 
Hosted server - unknown

Database:
Hosted server - unknown

PHP version:
Hosted server - unknown

ownCloud version:

Storage backend:
### Client configuration

Client version:
Various 

Operating system:
Zorin OS 11 (Ubuntu 15.10)

OS language:
English

Installation path of client:

> > Reading package lists... Done
> > Building dependency tree 
> > Reading state information... Done
> > Some packages could not be installed. This may mean that you have
> > requested an impossible situation or if you are using the unstable
> > distribution that some required packages have not yet been created
> > or been moved out of Incoming.
> > The following information may help to resolve the situation:
> 
> The following packages have unmet dependencies.
> owncloud-client : Depends: libowncloudsync0 (= 2.2.2-19.1) but it is not going to be installed
> Depends: libqt5core5a (>= 5.5.0) but 5.4.2+dfsg-2ubuntu9 is to be installed
> Depends: libqt5keychain1 but it is not going to be installed
> Depends: owncloud-client-l10n but it is not going to be installed
> E: Unable to correct problems, you have held broken packages.

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   (On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
   (See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
2. Web server error log:
3. ownCloud log (data/owncloud.log):

Thanks in advance!

**Comment by cdamken** [comment]
@jnweiger

**Comment by guruz** [comment]
Where did you download the packages from?
I recommend getting the 2.2.3rc1 from https://owncloud.org/install/#testing-development

**Comment by jnweiger** [comment]
@LKgY going backwards from Ubuntu 16.04 to Ubuntu 15.10 is an unknown path. 
Best is to remove all owncloud-client packages and subpackages first, then install from fresh.

    sudo apt-get purge owncloud-client libowncloudsync0 owncloud-client-l10n libqtkeychain0 
    sudo apt-get purge libqt5keychain1
    sudo apt-get purge libqt5keychain0
    sudo apt-get install -f

Then make sure there is only one (correct repository registered):

    grep -i owncloud /etc/apt/sources.list.d/*

and install from scratch.

**Comment by LKgY** [comment]
Thanks Jürgen for your detailed instructions! 

It looks like there are two repositories installed: 

/etc/apt/sources.list.d/owncloud-client.list:deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_15.10/ /
/etc/apt/sources.list.d/ownCloud-client.list:deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/ /

@guruz Aside from opensuse.org I also downloaded one version from owncloud.org
