### ISSUE TITLE
[Windows] Standard and Full type of install are the same

### ISSUE THREAD

**Issue by davitol** [owncloud/client#5111]
### Expected behaviour

Only 'standard' or 'full' type of install should be shown, due to they are the same. 
### Actual behaviour

Both options appear.

![screen shot 2016-08-08 at 09 11 49](https://cloud.githubusercontent.com/assets/10596560/17471947/31ea1104-5d48-11e6-8b51-45b33aff8085.png)
### Client configuration

Client version: Version 2.2.3-nightly20160805 (build 3592)

Operating system: Windows

**Comment by TheOneRing** [comment]
We stopped providing the nsis installer years ago.
