### ISSUE TITLE
User-Agent in 2.2.3 for Windows

### ISSUE THREAD

**Issue by daorte** [owncloud/client#5113]
### Actual behaviour
User-Agent still in beta phase
User-Agent: Mozilla/5.0 (Windows) mirall/2.2.3beta1 (build 6274)

### Client configuration
Client version: 2.2.3
Operating system: windows
OS language: en

**Comment by danimo** [comment]
The release build of the final version is https://download.owncloud.com/desktop/stable/ownCloud-2.2.3.6307-setup.exe. The automatic updater is not serving 2.2.3 yet, so if you are on a pre-release version, you need to update manually for now.

**Comment by daorte** [comment]
Hi @danimo i just downloaded manually from the site, please see the image and the published link

![captura](https://cloud.githubusercontent.com/assets/1828874/17508761/d276a65e-5e16-11e6-97d7-7bfb194b9520.PNG)

Regards,

**Comment by RealRancor** [comment]
@daorte Seems got fixed with https://github.com/owncloud/owncloud.org/commit/45747e0e59aa868863a6232a8dc385ad065eac05

**Comment by daorte** [comment]
Yes, this issue is already closed, nothing more to do :)
