### ISSUE TITLE
UX suggestion: Split the concepts of file synchronization and file deletion

### ISSUE THREAD

**Issue by stefanmohl** [owncloud/client#5118]
For new users, it is quite difficult to sort out the file deletion and synchronization relations, at times resulting in the contents of the local original folder getting deleted with resulting data loss. A suggestion is to simply make deletion and synchronization separate concepts.

1. A file that is synchronized will stay in sync, i.e. files get deleted on server and all clients if they are deleted at either end. Note: This requires the user to perform an actual deletion operation on either the server or a client for the file to get deleted.
2. When synchronization for a file is turned off, that is all that happens. The file status between server and client is no longer kept in sync, and nothing is changed on either end. In particular nothing gets deleted as a result of turning off synchronization.

For turning on synchronization:

1. When synchronization is turned on, files that are missing at either end are copied to the other end, but nothing is deleted.
2. When synchronization is turned on, files that differ by checksum are marked as different and do not get synchronized. If the file is deleted at either end, synchronization for the file gets turned on again and the remaining version of the file gets copied to both sides.
 2. For files that differ at both ends and therefore do not get synchronized, it would be nice if some easily accessible diff command were added to the UI, as well as a force push to server or pull from server option were added. This would overwrite one version of the file and enable synchronization.
3. When synchronization is turned on, the creation date is updated to the oldest creation date (the file has to have been at least that old). The modification date gets updated to the newest of the modification time (it was modified at least that late).

The effect is that nothing gets deleted unless the user manually performs a delete at either end; something that seems quite important if you are using OwnCloud as a backup solution.

**Comment by danimo** [comment]
Thanks you for your poposal. However there are two reasons why I'll have to close this:

1. ownCloud is not, and never will be a backup solution, also from a server perspective. It's simply not its design goal and it would be a bad advise to use it as such.
2. The UI would grow even more complex, with no way to reflect this sync state (especially on Windows, where we are already out of display states due to OS constraints).

**Comment by stefanmohl** [comment]
I have updated my suggestion, is it more acceptable this way?

**Comment by danimo** [comment]
I'm not sure I understand how this changes the problems mentioned.

**Comment by stefanmohl** [comment]
You mentioned that OwnCloud is not a backup solution, and the we are out of display states on Windows; so I limited my suggestion to only the part pertaining to deleting files. As the suggestion now stands, OwnCloud will never delete files that are not synchronized, i.e. when a file is being synchronized between server and client, a deletion will be synchronized. However when synchronization is turned off, nothing happens; the file simply remains on both server and client.
