### ISSUE TITLE
[OS X] No Overlay Icons because of Google Drive

### ISSUE THREAD

**Issue by glannes31** [owncloud/client#5119]
### Expected behaviour

Green Icon Sync for synchronised directories
### Actual behaviour

No Icon Sync
### Steps to reproduce
1. Update to 2.2.3 version
2. Icons sync disappear
### Client configuration

Client version:2.2.3
Os Language : French
Operating system: Windows 7 

Hello everybody , It is normal that the icon sync disappear in 2.2.3 client version ?    I test on two Windows 7 Pcs

**Comment by glannes31** [comment]
It's a bug because the downgrade on 2.2.2 version solved this issue

**Comment by ckulesa** [comment]
I am also experiencing this behavior in OS X 10.11.5.

**Comment by glannes31** [comment]
@guruz @dragotin it's very urgent to solve this because it's a risk to delete synchronised files( directories)

**Comment by guruz** [comment]
@glannes31 have you tried rebooting Windows after the installation? Usually this is needed.

@ckulesa Could you check ```System Preferences``` -> ```Extensions``` -> ```Finder``` and report back please?

FYI @jturcotte

**Comment by glannes31** [comment]
Hello @guruz , i'ts ok after reboot .

**Comment by ckulesa** [comment]
@guruz The finder extension is installed and enabled but there are still no status icons in the ownCloud folder. I have rebooted and uninstalled/reboot/installed all with no effect. Client version 2.2.2 does not have this issue.

**Comment by protree** [comment]
Same Problem here

**Comment by glannes31** [comment]
do you have restart your computer?

Envoyé depuis Yahoo Mail pour Android 
 
  Le ven. j sept. PM à 12:22, protree<notifications@github.com> a écrit :   
Same Problem here

**Comment by protree** [comment]
Yes I did restart my Computer. Still no Overlay-Icons

**Comment by glannes31** [comment]
Okay, @guruz another issue from Mac user ...

**Comment by guruz** [comment]
Can you guys run console.app (just search for it with spotlight) and check if there is any output coming about FinderSync or similar?

**Comment by guruz** [comment]
Any news from you guys?
It would also be good to check the other end, e.g. the ownCloud client. 
You can do that by quitting the client, then opening terminal.app and running ```/Applications/owncloud.app/Contents/MacOS/owncloud --logfile -``` (including the last -)

**Comment by protree** [comment]
I'm not at home atm. I can send you some logs in about a week.

**Comment by jturcotte** [comment]
We just found out that the Google Drive finder sync extension seems to register the disk root as its own, and this will result in overlay icons of other extension not to appear if they are configured with a lower priority.

To work around the issue: make sure that the ownCloud finder extension is higher in the list of extension in [System Preferences / Extensions / Finder], where you can use the mouse to drag the "ownCloud Exensions" at the top of the list, or drag "Google Drive" at the bottom.
You have to be in the "Finder" list and not "All" of the Extensions pane in order to be able to set the priority, tested on 10.11.

If anybody could confirm that this is also helping for them, it would be great.

**Comment by guruz** [comment]
I posted this on https://productforums.google.com/forum/#!topic/drive/5udboDa6ZS4;context-place=forum/drive

**Comment by protree** [comment]
I can confirm that my problem is somehow related. I noticed that I installed the "Synology Photo Uploader" App that has a Finder Plugin, too. Moving the ownCloud Finder Plugin to the top of the list fixed the issue for me.

**Comment by fmoc** [comment]
Looks like the issue is caused externally and not controlled by the desktop client. Also, the issue has not seen activity in years. Please feel free to reopen it should the issue persist.
