### ISSUE TITLE
[2.2.3] [openSUSE 42.1] crash inside QNetworkProxy

### ISSUE THREAD

**Issue by shoelzle** [owncloud/client#5121]
### Expected behaviour
The application should continue running.

### Actual behaviour
The owncloud client terminates:
Program received signal SIGSEGV, Segmentation fault.

### Steps to reproduce
1. Run the owncloud client binary
2.  Wait about 2 seconds until the application segfaults

### Client configuration
Client version: 2.2.3-1.1

Operating system: openSUSE 42.1

OS language: English

Installation path of client: /usr/bin/owncloud

### Logs

Nothing in the owncloud client's logs. I guess the owncloud client crashes before anything is written to the logs.

### Additional information

* Used OpenSUSE repo: https://build.opensuse.org/package/show?project=isv%3AownCloud%3Adesktop&package=owncloud-client
* GDB output and backtrace: https://gist.github.com/shoelzle/02fb4dd5d21a1a0f5d861cc62571eb94
* Complete list of installed packages on client: https://gist.github.com/shoelzle/97aa823ac0cda6572340e837d75b4552

**Comment by guruz** [comment]
This is the same crash as described in https://github.com/owncloud/client/issues/4525

Is it fixed if change your proxy settings in ```owncloud.cfg``` to off?
e.g. ```type=2``` in ```[Proxy]```

Please report back..

FYI @danimo

**Comment by shoelzle** [comment]
@guruz : Indeed, your suggestion works.
Thanks :)

**Comment by guruz** [comment]
great! :)
