### ISSUE TITLE
Last button in config account views is misaligned.

### ISSUE THREAD

**Issue by SergioBertolinSG** [owncloud/client#5124]
### Steps to reproduce

1.- Configure a new account.

### Observed behaviour:

![screen shot 2016-08-17 at 18 32 42](https://cloud.githubusercontent.com/assets/9048796/17744706/3e088c6e-64a9-11e6-9574-7b336160ad18.png)

![screen shot 2016-08-17 at 18 18 35](https://cloud.githubusercontent.com/assets/9048796/17744712/4382b868-64a9-11e6-85ea-2ad559975f1b.png)

### Version

Mac OS X El Capitán:

Version 2.2.3-nightly20160817 (build 3620).

**Comment by guruz** [comment]
Thanks!
-> https://github.com/owncloud/client/issues/5083
