### ISSUE TITLE
Keep retrying in background if certificate from the server has changed

### ISSUE THREAD

**Issue by jsalatiel** [owncloud/client#5127]
### Expected behaviour
Tell us what should happen
When we are behind a captive portal,  when the portal forces reauthentication after a few hours, owncloud client will correctly shows a big dialog saying that something changed on the server's certificate, but it should should keep retrying the connection in background and auto close this dialog if the connection is successfully.  Why ? you may ask! I can reauthenticate to the portal from my android device or any other device in the network, but the owncloud client running on my desktop won't resume until i manually close it and reopen it.
IMHO, it would be better instead of that big dialog, just show the the 'broken' icon in the systray icon and the dialog would show after clicking there, so it could seamless keep retrying in background.
### Actual behaviour
Tell us what happens instead
Owncloud client wont reconnect until it is closed and reopened.
### Steps to reproduce
1. Try some captive portal or change the server certificate
### Client configuration
Client version: 2.2.2-19.1
Operating system: mint 18

**Comment by ckamm** [comment]
@jsalatiel Just to summarize:
* You're using the owncloud client behind a captive portal, all is working.
* Somehow the portal authentication expires, leading the certificate to change and the client pops up the cert dialog
* You reauthenticate with the portal.
* This reestablishes the old certificate, but the client doesn't continue syncing because it's still showing the dialog.

Does it fail to continue syncing if you approve or reject the altered certificate? That may be a bug! I think if you rejected the portal's certificate, the client should keep trying to connect?

**Comment by jsalatiel** [comment]
Somehow the portal authentication expires == The captive portal expires automatically every 12 hours. =)
I always reject the certificate, but after reauthenticate on captive portal , owncloud client wont reconnect until i close and open it again. 

Of course i think that it should keep trying to reconnect in background even if the dialog is already shown and close the dialog if the connection goes successfully. Or even better, do not pop up that dialog =)

**Comment by ckamm** [comment]
@jsalatiel I just reproduced the situation with mitmproxy. If I switch from certificate A to B I do get the dialog as expected. Then I switch back to A and hit cancel on the dialog and the client reconnects to the server just fine. Could you try to reproduce again?

**Comment by guruz** [comment]
(Wondering if related to https://github.com/owncloud/client/issues/5093 or https://github.com/owncloud/client/issues/5096 )

**Comment by jsalatiel** [comment]
@ckamm  i have tested. The only difference i see is that i click in cancel before reauthenticate to the captive portal ( to get rid of the dialog )

**Comment by ckamm** [comment]
@jsalatiel You're saying you tested again and it *doesn't* reconnect for you? I've also tested again and it does for me (after <30s), even if I click 'Cancel' before switching back to the old certificate. 

Could you run with "--logfile mylog.txt" and reproduce the problem if possible? (potentially pause all sync folders before to keep the log file small) As is, I don't see how this could be happening.

**Comment by jsalatiel** [comment]
Hi @ckamm , sorry the delay, i was on a trip.
Unfortunatelly i left the hotel , so no more captive portal to test it. I tried with burp proxy as MITM at home, and it worked as expected. Maybe there were some wrong with the hotel's captive portal.
Thanks!

**Comment by ckamm** [comment]
@jsalatiel Thanks for checking again. Feel free to reopen when you see something like this again and we'll continue debugging it.
