### ISSUE TITLE
[2.2.3] [Linux] Segmentation fault at startup

### ISSUE THREAD

**Issue by Jguilbaud** [owncloud/client#5128]
Hello,
Since few weeks owncloud client doesn't start, when launching it in commande line, i get a single "segmentation fault" error
if i start from GUI with a clean linux user, the configuration window appear but disappear after near 5 seconds

### Steps to reproduce
1. Launch owncloud client from command line or GUI

### Client configuration
Client version:
ownCloud version 2.2.3
Using Qt 5.7.0
installed from repository : http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/openSUSE_Leap_42.1_Update/

Operating system: openSUSE Leap 42.1 x86_64 (uptodate) under KDE (Plasma5)

OS language: fr_FR

Installation path of client:  /usr/bin/owncloud

### Logs

valgrind : https://gist.github.com/Jguilbaud/f16e22f78ff534b871534da572e59e01
gdb : https://gist.github.com/Jguilbaud/297789870b97782d6777060803913e47

ask me if you need more informations :)

thanks !

**Comment by ckamm** [comment]
@Jguilbaud Unfortunately the problem isn't clear. Could you check whether you can install kde debug packages (optional) and then run gdb again, typing 'bt' at its prompt to get a full backtrace? Right now it looks like the crash is in `libkdecore.so.5`, which could hints at an environment or external issue...

**Comment by guruz** [comment]
Please run ```thread apply all bt```

**Comment by Jguilbaud** [comment]
(gdb) thread apply all bt
(gdb) run
The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /usr/bin/owncloud 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
[New Thread 0x7fffe4034700 (LWP 4440)]
[New Thread 0x7fffd6daf700 (LWP 4447)]
[New Thread 0x7fffd65ae700 (LWP 4448)]
Detaching after fork from child process 4449.
Detaching after fork from child process 4466.
[New Thread 0x7fffc7fff700 (LWP 4470)]
[New Thread 0x7fffc77fe700 (LWP 4471)]

Thread 5 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffc7fff700 (LWP 4470)]
**QHash<QString, KAuth::ActionWatcher*>::QHash (this=0x7fffc6ffd9b0 <KAuth::s_watchers>) at /usr/include/QtCore/qhash.h:281
281     /usr/include/QtCore/qhash.h: Aucun fichier ou dossier de ce type.**

**Comment by guruz** [comment]
Ouch, a crash in libproxy again. Ideally you report this with the libproxy people.

Workaround:
https://github.com/owncloud/client/issues/5121#issuecomment-240107886
https://github.com/owncloud/client/issues/4525

Does the workaround help?

**Comment by Jguilbaud** [comment]
KDE/ Plasma 5 proxy is already configured to off
and in my owncloud.cfg :
[proxy]
type=2

**Comment by Jguilbaud** [comment]
i found a solution
You're right, it's a bug in libproxy
i have installed  libproxy 0.4.12 from unstable repo opensuse/GNOME/factory (instead of the 0.4.11 installed from official repo) and it works :)

**Comment by guruz** [comment]
Great to here..
