### ISSUE TITLE
[Windows] Prevent accidental deletion of whole root folders in connected folder

### ISSUE THREAD

**Issue by pke** [owncloud/client#5131]
### Steps to reproduce
1. Connect a folder
2. Let it finish sync
3. Drag one of the root folders from the connected folder to the Windows Desktop
4. Watch all content of your owncloud/nextcloud being deleted
### Expected behaviour

The client should install a Windows Explorer ICopyHook to prevent such operations.

See https://msdn.microsoft.com/en-us/library/windows/desktop/cc144063(v=vs.85).aspx

It could request the user to confirm the operation. If the user is made aware of the DELETE operation to happen the copyhook handler can let the OS continue with its operation, otherwise `IDCANCEL` the whole MOVE operation.
It could also notify the user about useless COPY operations, since wherever you copy the content of the nextcloud folder it will not be kept in sync.
### Actual behaviour

The folder was deleted without further confirmation.
### Client configuration

**Operating system:**

Windows 8/10

**Comment by guruz** [comment]
This sounds to me like a nextcloud bug. Please try at https://help.nextcloud.com/

**Comment by pke** [comment]
No, this is a client bug. They are using the owncloud client (for now). The owncloud client needs to take of this issue, even for owncloud users.

**Comment by guruz** [comment]
If you _move out a folder_ out of the sync folder to somewhere else (e.g. your Desktop) then it will not be in the sync folder anymore.
Therefore, the client will delete it on the own/next - cloud server.

**Comment by dragotin** [comment]
That works as designed. You can not let the user confirm any delete operation. That would really contradict the whole point of syncing.

**Comment by pke** [comment]
Yes. That is a usage *bug*. As I described in my OP. The client should at least ask the user if that is her intention. Software should not allow such fatal mistakes in the first place.

@dragotin I showed you guys how this can be prevented/intercepted (at least) in Windows. Its not interfering with any syncing. Its happening before the sync engine even sees the "move" operation.

The default drag&drop operation in Windows is "move". Without knowing that (most Windows users don't know or care) that means if the users intention was just to place some (root) folders from the owncloud sync folder to her desktop she accidentally just removed all those folders from everybody elses sync folder too.

**Comment by dragotin** [comment]
Yes, I understand. But would you ask the user only in the case when a folder was dragged out of the sync dir? 
I think it makes more sense to just do the delete, and let the user restore the data in case that was not intentional, which is possible if the versions app is enabled on the server, yet we do not have an integration on the client yet unfortunately, see #4556.

**Comment by pke** [comment]
Yes when a folder was dragged out/Cut from the sync folder. I have seen this happening now multiple times and restoring the fallout of this operation while others in the meantime have upsynced, intentionally removed/moved files is a nightmare.
The client should prevent such fatal operations as good as it can. Windows copy hooks allow exactly that. And it will prevent the action in case of drag&drop or `cut` operations.

**Comment by ckamm** [comment]
I can imagine this being a useful warning.

Should it apply to anything that's moved out a sync folder, or only folders, or only root folders? It'd probably need a "Stop warning me about this, I know what I'm doing!" check box.

**Comment by pke** [comment]
I think it should apply to every MOVE operation targeting outside the sync folder.
And for sure a checkbox to opt-out of this warning should be provided.

**Comment by pke** [comment]
Closing this as no-one seems to have an issue with it and I don't use owncloud/nextcloud software myself.
