### ISSUE TITLE
folder download limit is applied to directories moved server-side but it should not

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5132]
Version 2.1.1.

I had two sync clients fully synchronized.

I moved a bunch of large directories on the server (actually via sync client 1).

Sync client 2 complained about these directories exceeding 500MB threshold and I had to check them manually to enable sync. Once I did this, the local directories were instantly moved -- as expected --  no download was involved.

I do not think that max folder size download limit should apply to such directories in case of move. Disk usage is exactly the same.

**Comment by ckamm** [comment]
I've started looking at it and find it surprising: The new folder hook is only triggered if it's not a rename. I'll have to try to reproduce to figure out how your problem appears.

**Comment by ckamm** [comment]
@moscicki I can't reproduce it yet. Here's what I tried
* Create a /big folder on the server
* Accept it in the client, fully sync it
* Move it on the server to /new/big
* Sync

And I did not get a warning about the folder in the client when it was moved. Can you reproduce it somehow?

**Comment by ckamm** [comment]
@moscicki Please reopen if still relevant.
