### ISSUE TITLE
Uploading 22gb file fails

### ISSUE THREAD

**Issue by therudnick** [owncloud/client#5134]
### Expected behaviour

Client uploads the file to the web server.
### Actual behaviour

File uploads over and over again, never actually stays uploaded to the server.
### Steps to reproduce
1. 22gb .zip file is placed in ownCloud folder on Desktop.
2. Client begins syncing, wait however long it takes with your internet connection.
3. Observe that the file "fully uploads" but doesn't actually "stick".
### Server configuration

Operating system:
Linux
Web server: 
Namecheap shared hosting
Database:
MySQL
PHP version:
5.4
ownCloud version:
9.1
### Client configuration

Client version:
2.2.3 (build 3601)
Operating system:
Mac OS 10.11.6
OS language:
English
Installation path of client:
/Applications/ownCloud.app
### Logs
1. Client logfile:
   https://gist.github.com/therudnick/9e6b6c6c2b93ad3f3cd2c2b7874bf9e3
2. Web server error log:
   https://gist.github.com/therudnick/9e9d3e96585b56687de3786ec44dafc1
3. Server logfile:
   https://gist.github.com/therudnick/bb24d57163782286bc45cbd3a053caa4

**Comment by dragotin** [comment]
In the client log file, I can find:
```server replied: Locked ("spencer/bigger file.zip" is locked```

@DeepDiver1975 how can these server logs be checked and/or released?

**Comment by guruz** [comment]
@therudnick Can you check the ```oc_file_locks``` table on the server?
Maybe with something like ``` select * from oc_filecache where path in (select path from oc_file_locks)``` too?

FYI @PVince81

**Comment by PVince81** [comment]
@guruz no, the path is md5'd in oc_file_locks, so can't directly map it to filecache unfortunately.

The TTL for stray locks is an hour. If after an hour it's still not released, it means that either cron doesn't run properly or some other process is recreating the lock repeatedly. Stray locks usually happen in the case of PHP timeouts. Without timeout, locks are normally released at the end of the request.

**Comment by therudnick** [comment]
oc_file_locks.sql:
https://gist.github.com/therudnick/ce8bcc9c940db8caba6901c40e653af9

results of your requested query on oc_filecache.sql:
https://gist.github.com/therudnick/597bc297dc942c43fae239551055377a

--
Spencer Rudnick

**Comment by dragotin** [comment]
@therudnick pls. check what @PVince81 said in his last comment.

**Comment by therudnick** [comment]
@PVince81 I don't understand what @dragotin means. Is there something different I need to check?

**Comment by PVince81** [comment]
@therudnick is the lock automatically freed after an hour ? Does your cron work properly ?

**Comment by therudnick** [comment]
@PVince81 I do not know what that means...

I'm very new to all this, where would I look to find if my lock is freed? What is cron?

**Comment by PVince81** [comment]
@therudnick go to the admin page and search for the word "cron" and tell us which of the radio button is checked. Also see https://doc.owncloud.org/server/9.1/admin_manual/configuration_server/background_jobs_configuration.html?

Since you are asking what cron is, it is likely that it is using the default "ajax cron" mode, which is known to not run often enough to properly clear stray locks, see https://github.com/owncloud/core/issues/20380

**Comment by therudnick** [comment]
I checked the documentation and followed instructions to switch from "ajax cron" mode to "cron" mode.

Cron.php ran twice over the next half hour, but after that it hasn't worked.

Here's the cron job entry I added in cPanel:

15	*	*	*	*	crontab -u www-data -e */15 * * * * php -f /public_html/webdrive/cron.php

**Comment by PVince81** [comment]
Check `select * from oc_jobs`. Maybe there are still lots of old pending jobs that need executing before it reaches the stray lock one. You might want to run cron manually a few times.

**Comment by therudnick** [comment]
results from `select * from oc_jobs`:

1	OCA\Files_Versions\BackgroundJob\ExpireVersions	null	1472188636	1472188636	0
2	OCA\UpdateNotification\Notification\BackgroundJob	null	1472126341	1472200426	0
3	OCA\Federation\SyncJob	null	1472239406	1472239406	0
4	OCA\Files\BackgroundJob\ScanFiles	null	1472246968	1472246968	0
5	OCA\Files\BackgroundJob\DeleteOrphanedItems	null	1472256946	1472256946	0
6	OCA\Files\BackgroundJob\CleanupFileLocks	null	1472304393	1472304393	0
7	OCA\DAV\CardDAV\Sync\SyncJob	null	0	1472200426	1472200426
8	OCA\Files_Sharing\DeleteOrphanedSharesJob	null	1472304406	1472304406	0
9	OCA\Files_Sharing\ExpireSharesJob	null	1472304656	1472304656	0
10	OCA\Files_Trashbin\BackgroundJob\ExpireTrash	null	1472476811	1472476811	0
11	OCA\Activity\BackgroundJob\EmailNotification	null	1472476827	1472476827	0
12	OCA\Activity\BackgroundJob\ExpireActivities	null	1472105744	1472185974	0
13	\OC\Authentication\Token\DefaultTokenCleanupJob	null	1472188625	1472188625	0

**Comment by therudnick** [comment]
I switched to "AJAX" and reloaded the page to run cron manually. Should I switch back to "Cron"? Is  the url `/public_html/webdrive/cron.php` I used inappropriate?

**Comment by guruz** [comment]
Please comment if this still happens with a recent oC server/client

**Comment by guruz** [comment]
Sorry we can't help without more info
