### ISSUE TITLE
[Ubuntu 12.04] please provide the last deb generated even if it is old

### ISSUE THREAD

**Issue by ycawidro** [owncloud/client#5135]
Hello,

I know that support has been dropped for ubuntu 12.04 but unfortunately I still have to install and use ubuntu 12.04 version.
Would it be possible to look through your deb archive and put the latest deb you have made for ubuntu 12.04 on the download server for both 32 and 64 bits ?
My guess is latest generated version deb are : 2.1.0-1.1

This would be really appreciated :)
Thanks
Yanik

**Comment by burgerga** [comment]
Is this does not seem to get a lot of attention, I found a solution, I was browsing the repository and found
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/client-2.1.1/Ubuntu_12.04/
So if you use this in the installation instructions it works!

PLEASE DO NOT REMOVE THIS REPOSITORY!
Our IT-department is incompetent, and we're still on 12.04 for at least half a year.

**Comment by jnweiger** [comment]
There is also a repository for 2.2.1 -- no need to go back to 2.1.1 :
https://build.opensuse.org/package/binaries/isv:ownCloud:desktop:client-2.2.1/owncloud-client?repository=Ubuntu_12.04



To be on the safe side: Please branch the obs repo to have it under your control. Or better make a local copy of the download repository.

The bad news is: I am surpised openSUSE.org still offers Ubuntu 12.04 as a build target. 
WONTFIX. sorry.

**Comment by burgerga** [comment]
Thanks for the update, the comment on https://github.com/owncloud/client/issues/5032 made me think 2.1.1 was the last one. Will look into branching 2.2.1.
