### ISSUE TITLE
[Windows] [2.2.3] Files/Folders missing on desktop client

### ISSUE THREAD

**Issue by Shigerux** [owncloud/client#5136]
### Expected behaviour

Connecting the Client to the cloud to get all files and folder synchronised to the computer.
### Actual behaviour

Files and Folders are missing in the desktop client but they appear in the webclient and webdav folder. 
They are missing if you select to sync all files and folder but also if you want to manually choose the folder, it's already missing there.
### Steps to reproduce
1. Connect the Desktop Client to the owncloud server.
2. Choose to download all files and folder
3. Compare the result with the website

![7](https://cloud.githubusercontent.com/assets/19669326/17967582/636a7db2-6ac8-11e6-8817-c46a224a9fdb.JPG)
![8](https://cloud.githubusercontent.com/assets/19669326/17967583/6460bc04-6ac8-11e6-9344-d19851f3f4ee.JPG)
### Server configuration

Operating system: Ubuntu 14.04.3 LTS

Web server: Apache 2.4.7

Database: mysql 5.5.50-0

PHP version: 5.5.9

ownCloud version: 9.0.1(.3)

Storage backend (external storage): No external storage
### Client configuration

Client version: 2.2.3 build 6307

Operating system: Windows 10 (14393) Pro 

OS language: German

Installation path of client: "C:\Program Files (x86)\ownCloud"
### Logs

This is the log output from the client when I'm in the wizard to select the folders I want to synchronize (there they are already missing)
1. Client logfile: 
   0x997e50 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://cloud.xxxxx.de" + "" "OCC::SelectiveSyncTreeView"
   0x997e50 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
   0x997e50 unknown: static QWindowsEGLStaticContext\* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

0x997e50 unknown: static QWindowsEGLStaticContext\* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
0x997e50 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://cloud.xxxxx.de" + "2147 - XXXXXX 119, FFM" "OCC::SelectiveSyncTreeView"
0x997e50 OCC::AbstractNetworkJob::start: !!! OCC::LsColJob created for "https://cloud.xxxxx.de" + "2147 - XXXXXX 119, FFM/07 Mietverhältnisse" "OCC::SelectiveSyncTreeView"
0x997e50 OCC::ownCloudGui::slotOpenSettingsDialog: No configured folders yet, starting setup wizard
0x997e50 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (Die angegebene Prozedur wurde nicht gefunden.)
0x997e50 unknown: static QWindowsEGLStaticContext\* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001
0x997e50 unknown: static QWindowsEGLStaticContext\* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available

EDIT:
Just tested with an old 1.X client. It was working fine in this version.
The first time I run a fresh installed 2.2.3 version it also showes me the missing folders in the sync selection screen. But after completing the first run wizard the folders are not visible anymore.
Maybe it has to do with the way the 2.2.3 is including the directorys? Maybe a problem with the german "ß" key in the folder name?
It looks like the 1.X client has the configuration to ignore folder XYZ while the 2.X explicity saves which folders to synchronize.

**Comment by ckamm** [comment]
@Shigerux Do the folders appear in the list in Activity/Not Synced? If so, what's the error displayed there? I think it's not unlikely that it's due to unsupported characters, though an ß should be fine.

**Comment by Shigerux** [comment]
@ckamm Unfortunately not. After adding the folders to the synchronisation list they immediatly disappear  from the selection. Here are another two screenshots. 

Here I can select those Folders:
![15](https://cloud.githubusercontent.com/assets/19669326/18006301/3cbfe350-6b9f-11e6-905d-ec9770889598.JPG)
on the next screen, they are not available anymore.
![16](https://cloud.githubusercontent.com/assets/19669326/18006309/49662376-6b9f-11e6-981f-623ffbfb84b8.JPG)
The "Activity/Not Synced" is empty.

**Comment by ckamm** [comment]
@Shigerux I'd still guess that this is related to the subfolder file names. Could you give me an example name of a folder that's not synced and doesn't show up in the selective sync folder list?

It could be a trailing space or dot, unsupported characters in the path, or the name matching one of your configured exclude patterns. (check the patterns in General/Edit Ignored Files)

**Comment by guruz** [comment]
Is this still an issue?

**Comment by guruz** [comment]
@Shigerux  Sorry we can't help without more info
