### ISSUE TITLE
Run Client like AWS Storage Gateway-Cached Volume

### ISSUE THREAD

**Issue by qops1981** [owncloud/client#5137]
**Run Sync Client like AWS Storage Gateway-Cached Volume**

https://aws.amazon.com/storagegateway/

1st, I tried looking for this as an enhancement request and just as a feature that might already exist, but I didn't find anything. My internet Foo may not be strong, so I apologize if this already exists. I could have swore I liked a previously submitted request but I couldn't find that either.

I have seen a lot of information about people asking for Selective Sync and the like. But What I would really like to see is the client act more like a cached extension of a remote volume.

Example: My husband is Graphic Artist and he has a very large volume of old content. I would love for him to have access to this kind of content through a syncing cloud like drive. The problem is the content is way to large to place on his laptop. There is plenty of room for his current projects, but the whole size of his total collected works is quite large.

Now Yes, there are "work-arounds" but my goal with this post is to provide what I think is a holistic solution to many different problems that people are individual asking for separate features.

The idea is that I would have my 40TB OwnCloud Server, My husband would connect to that server with the client. 
- Whatever content My husband placed in the directory for the client would be synced over to the server.
- As time passes; content not access for a period of time would begin to fade or atrophy from his personal computer, but would remain on the server.
- When selecting a file whose content has atrophied; His client would poll the server to fill it back.

Files whose content has faded would merely be place holders. Faded or atrophied could be a couple things. The files could be chopped up and individual chunks could be removed OR is could simply be a complete removal of the content.

The idea of not removing all of the data would be to help sync back content faster over slower connections. Example: My husband is at a clients house with slow internet and needs to pull some not so old but atrophied content. Only the missing pieces would need to be download.

**Comment by guruz** [comment]
Thanks, this is interesting.
I'd say this is mostly related to https://github.com/owncloud/client/issues/4341

**Comment by hodyroff** [comment]
https://github.com/owncloud/client/issues/4341 is the discussion thread. Closing this as duplicate.
