### ISSUE TITLE
Account wizard shibboleth path is broken

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#5138]
When trying to create a new account on a server using Shibboleth the HttpAuth wizard page is shown. The log contains lines like this: 
```
0x2391180 abstractnetworkjob.cpp:234 !!! OCC::DetermineAuthTypeJob created for "https://docker...." + "" "OCC::OwncloudSetupWizard" 
0x2391180 abstractnetworkjob.cpp:161 SslHandshakeFailedError:  "SSL handshake failed"  : can be caused by a webserver wanting SSL client certificates 
```

Instead, it should show the shib login page in a webview. This works correctly in the 2.2 branch but fails in the master branch.

**Comment by ckamm** [comment]
Reverting bb5c2cbfa571e0d557853fec8d548f4b6d53a698 restores correct behavior.

**Comment by guruz** [comment]
Nice catch!

**Comment by davitol** [comment]
Tested in Version 2.3.0-nightly20160829 (build 3644) and works 👍
