### ISSUE TITLE
No action/warning is shown when clicking in Mail Link button and there is no email client configured

### ISSUE THREAD

**Issue by davitol** [owncloud/client#5142]
### Steps to reproduce

1. Try to share a file via link by mail without having any email client configured

### Expected behaviour
A warning advice related to no email client is configured should be shown or maybe Mail app should be opened.

### Actual behaviour
Clicking on Mail link button does not show any action.

### Server configuration
Operating system: Ubuntu 14.04

Web server: Apache

Database: MySQL

PHP version: 5.5.9

ownCloud version: 9.1.0

Storage backend (external storage):

### Client configuration
Client version: 2.2.3

Operating system: Windows 10

OS language: English

Installation path of client: C:\Program Files (x86)\ownCloud

**Comment by ckamm** [comment]
We currently just use `QDesktopServices::openUrl` with a "mailto:" link to launch the email program. Let's check if the return value gives us any information (the documentation is unclear on that).

**Comment by ckamm** [comment]
Yes, this does return `false` on Windows, when no email client is configured!

**Comment by ckamm** [comment]
@davitol Please test (but it's not urgent)

**Comment by davitol** [comment]
Tested with Version 2.3.0-nightly20160922 (build 6394) and  the email program is launched and it says that no account has been configured yet. So I think is far enough and it's better than before, when no action seemed to happen
