### ISSUE TITLE
Feature Request for Combining smaller and fragmenting bigger files

### ISSUE THREAD

**Issue by ClundXIII** [owncloud/client#5143]
Hi all, I have a detailed feature request:

server side:
The owncloud server should be able to recieve and send packages with are:
1) more then one file combined
2) fragmented for bigger files

The reason is:
1) If you have a lot of small files down-/uploading them one by one takes a lot of time. Combining them might be a huge improvement for performance
2) If you have large files you might now be able to finish the download within one session. Splitting the file and therefore not aborting upload would make a lot of sense.

The idea is to add 2 options to the client:
1) approx. upload size where the client can send fragments to the server (between 10 and 100MB, depending on the connection)
2) approx. download size where the client will tell the server how big the fragments should be (between 100MB and 1GB)

The server should also be able to cap the size at a maximum if there are restrictions in the serverconfig. This would be really useful for hosts who are using shared hosting and who are not able to raise the up-/download limit. I experienced issues with uploading bigger files when the max_post_size was too small.

**Comment by guruz** [comment]
We're already fragmenting uploads :) Since many hears. We call it chunking. https://github.com/owncloud/smashbox/blob/master/protocol/protocol.md#chunked-file-upload

For small files we're already thinking about this too.. https://github.com/owncloud/core/issues/11588

**Comment by ClundXIII** [comment]
Ok. I didn't know about this. Thank you :)
Still, a way to control this size would make a lot of sense.

I might submit a bug report later that adresses the upload issue I posted above. (If I can reproduce it).

**Comment by ckamm** [comment]
@ClundXIII The chunk size that the ownCloud client uses for uploads is 10 MB in 2.3 and automatically adjusts itself between 1 and 100 MB in master. Was your `max_post_size` below 10 MB?

**Comment by ClundXIII** [comment]
I believe not.

You can close this request if you want.

**Comment by ckamm** [comment]
@ClundXIII Ok, but feel free to reopen if you can reproduce or have more information about the issue.
