### ISSUE TITLE
[Mac OS X] [2.2.3] StartCom "Untrusted Certificate" ?

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#5145]
@cdamken renewed the StartCom SSL certificates, but Mac OS X client 2.2.3 is complaining about "Untrusted Certificate". This also happens with a fresh installed client, but only on Mac OS X, not with Win 10.

![screen shot 2016-08-29 at 21 39 43](https://cloud.githubusercontent.com/assets/214010/18065103/c3165e9e-6e32-11e6-99e9-5522371fdac1.png)

![screen shot 2016-08-29 at 21 40 31](https://cloud.githubusercontent.com/assets/214010/18065126/d3120ca8-6e32-11e6-9988-83b4d3cd81e2.png)

![screen shot 2016-08-29 at 21 39 55](https://cloud.githubusercontent.com/assets/214010/18065130/d6c109da-6e32-11e6-82c5-ce448c58a437.png)

### Expected behaviour
Mac OS X client should be happy

### Actual behaviour
Mac OS X client 2.2.3 is complaining about "Untrusted Certificate"

### Steps to reproduce
1. Connect Mac OS X client 2.2.3 with http://cloud.damken.com/

### Server configuration
Operating system:
Ubuntu 16.04

Web server: 
Apache

Database:
MySQL

PHP version:
7

ownCloud version:
8.2.7

Storage backend (external storage):
NFS

### Client configuration
Client version:
2.2.3

Operating system:
Mac OS X 10.11.6

OS language:
en

Installation path of client:
/Applications/owncloud.app

**Comment by danimo** [comment]
Your SSL chain is misconfigured. It lacks the intermediate, but sends unrelated certs: https://www.ssllabs.com/ssltest/analyze.html?d=cloud.damken.com
