### ISSUE TITLE
Keeps asking password on Guest Account

### ISSUE THREAD

**Issue by maverick74** [owncloud/client#5146]
### Expected behaviour
OwnCloud client should start on account login and start syncing

### Actual behaviour
OwnCloud client starts on account login but asks for account password. No matter how many time i set the password, everytime the client starts it asks  for the password. On version 2.1.1 it was working fine and did not ask the password

### Steps to reproduce
1. Get to the basement and find an old Window XP machine
2. Turn the Guest Account ON
3. Install the client on the Admin account (or from the Guest install it as Admin)
4. Configure everything.
5. Log out and then Log in (on client startup it will ask you for the account password) 

### Server configuration
Operating system:
Windows XP SP3

### Client configuration
Client version: 2.2.3

Operating system:Windows XP SP3

OS language: PT

Installation path of client: Default

### Logs

1. Client logfile: Had to install 2.1.1. So can't get log ATM (if really needed, please ask)

**Comment by danimo** [comment]
We have switched to a new version of libqtkeychain which uses thededicated Windows API for storing credentials, rather than trying to store it on its own within the ownCloud config file. With a guest account, Windows seesm to treat credentials as volatile objects, which makes sense from a security modelling POV. Since the library does not offer the old way anymore, and the new behavior is more correct from a security standpoint, I'm afraid we can't revert the behavior.

**Comment by danimo** [comment]
Also note that Windows XP is no longer officially supported by either Microsoft nor ownCloud.

**Comment by maverick74** [comment]
Yes, i'm aware XP is no longer supported by neither. However we don't have any other solution for the moment. We really need to stick with this machine. Is there any workaround we can try, beside being stuck in 2.1.1?

**Comment by danimo** [comment]
Use a normal account, not a guest account, and create a cleanup tasks that cleans only the things that you want cleared.

**Comment by maverick74** [comment]
There's no way to keep using the Guest Account? It's really useful for the job/post in question...

**Comment by danimo** [comment]
As I said: the previous implementation only worked by chance. The general expectation is that credentials are not kept in guest accounts. Given that the library doesn't give us a way back, I don't think we can support your use case.
