### ISSUE TITLE
Windows client freezes when trying to manage accounts

### ISSUE THREAD

**Issue by oparoz** [owncloud/client#5147]
### Expected behaviour

I should be able to remove accounts and folders
### Actual behaviour

Client freezes and cannot be stopped without a forced shutdown.
The menu is transparent and detached from its parent window.
### Steps to reproduce
1. Install client
2. Copy config from another installation
3. Always execute as standard user
4. Cancel all requested password entry
5. Try to use the menu to remove either folders or accounts
### Client configuration

Client version: 2.2.3

Operating system: Windows 10 Pro (Hyper-V enabled)

OS language: English

Installation path of client: Default (x86)
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   (On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
   (See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

Those commands don't do anything. There doesn't seem to be any log anywhere

**Comment by oparoz** [comment]
And the config ends up corrupt which prevents the client from starting

**Comment by guruz** [comment]
> Import config

What does this mean?

**Comment by oparoz** [comment]
That means copying the config from another installation in order to be able to synchronize with the same clouds

**Comment by guruz** [comment]
What are you copying? Just owncloud.cfg?
If you run cmd.exe and cd into the ownCloud exe directory, then for sure ```owncloud --logwindow``` should do somethng :)

**Comment by oparoz** [comment]
>What are you copying? Just owncloud.cfg?

Yes, just owncloud.cfg.

>If you run cmd.exe and cd into the ownCloud exe directory, then for sure owncloud --logwindow should do somethng :)

It does absolutely nothing. As long as the client is running no more windows can be displayed on screen.

**Comment by oparoz** [comment]
```
>taskkill /f /im owncloud.exe
ERROR: The process "owncloud.exe" with PID 14768 could not be terminated.
Reason: There is no running instance of the task.
ERROR: The process "owncloud.exe" with PID 248120 could not be terminated.
Reason: There is no running instance of the task.
```

And I forgot to add that this happens on 4K screens.

**Comment by oparoz** [comment]
More information:

1. Paste the config
1. Reboot

At this stage, the app will ask for the passwords

1. a) Either wait and do nothing. At some point the window will freeze
or 
b) Click cancel for all accounts

1. If you have access to the settings, try to access the menus

1. a) If the app is responsive, quit
or 
b) If the app freezes, kill the process

1. Start the app

At this stage, there will be nothing in the tray, but the process is there. It's impossible to "naturally" get the app back without a reboot

1. Delete the config file
1. Launch the app
1. Don't add an account
1. Quit the app
1. Replace the empty config with the one you have from a previous install
1. Launch the app from the command line using `--logwindow`

This time, it should launch properly again and the logs are working.

I've noticed this interesting bit:
```
09-04 22:39:29:660 0x8b78e0 unknown: Failed to resolve EGL function eglGetPlatformDisplayEXT (The specified procedure could not be found.)
09-04 22:39:29:661 0x8b78e0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): Could not initialize EGL display: error 0x3001

09-04 22:39:29:661 0x8b78e0 unknown: static QWindowsEGLStaticContext* QWindowsEGLStaticContext::create(): When using ANGLE, check if d3dcompiler_4x.dll is available
```

**Comment by guruz** [comment]
@oparoz Are you saying the app freeze only happens when connected to a 4k screen?
If ```--logwindow``` does not work, try ```--logfile path_to_some_logfile.txt```. We'd need to see what happens before the freeze.
If you recreate the same config manually by clicking in the UI, do you also get the freeze?

@jturcotte This EGL log mesages are not relevant I guess?

**Comment by oparoz** [comment]
>Are you saying the app freeze only happens when connected to a 4k screen?

I haven't tried on other screens yet, but that's a possibility if you can't reproduce it on other setups. That would maybe be because of the scaling taking place. I'm just mentioning it because this problem seem to be GUI related.

`logwindow` does work with the process I've described above.
I saw that EGL error and the standard messages about accounts not having passwords and folders not being mountable because not available yet.
Once I was able to insert my passwords, then I didn't have any issues any more with the app. Crossing my fingers.

**Comment by hodyroff** [comment]
still happening with 2.3? Do we support copy of config files?!
