### ISSUE TITLE
[Nextcloud 2.2.3.4 Mac OS] Initial connexion fails ('connection closed') with strong ciphers

### ISSUE THREAD

**Issue by serge-vk** [owncloud/client#5148]
### Expected behaviour
When setting up a NextCloud account, after typing in the server address (https) in the 'Set up NextCloud server' dialogue and clicking 'next', the 'Enter user credentials' dialogue should be displayed.

### Actual behaviour
A pop-up 'Connection failed' is shown with the message 'Failed to connect to the secure server address https://my.nextcloud.server/nextcloud. How do you wish to proceed?' If I click 'Select a different URL', I see the error message 'Failed to connect to Nextcloud at https://my.nextcloud.server/nextcloud/status.php: connection closed'.

OwnCloud client v. 2.2.2 (build 3472) works normally.

### Steps to reproduce
1. Install Nextcloud Mac OS client
2. Start Nextcloud client application
3. Try to connect to a server

### Server configuration
Operating system: FreeBSD 10.3 p7
Web server: Nginx 1.11.3
Database: MariaDB 10.1.16
PHP version: 7.0.10
NextCloud version: 10.0 stable
Storage backend (external storage): ZFS data set (no external storage)

I think that this problem may be related to the cipher suite I configured in the web server. I have included the relevant lines from nginx.conf:
```
ssl_protocols TLSv1.1 TLSv1.2;
ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
ssl_ecdh_curve secp384r1;
ssl_prefer_server_ciphers on;
```

### Client configuration
Client version: 2.2.3 (build 4)
Operating system: Mac OS X 10.10.5, Mac OS X 10.9.5 (two test cases)
OS language: English UK
Installation path of client: /Applications/nextcloud.app

### Logs
1. Client log (the lines appended after clicking 'next'):
```
08-31 09:51:01:988 0x600000015640 OCC::PostfixLineEdit::setFullText: "https://"
08-31 09:51:19:041 0x600000015640 unknown: QIODevice::read: device not open
08-31 09:51:19:045 0x600000015640 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://srv.addr/nextcloud" + "status.php" "OCC::OwncloudSetupWizard"
08-31 09:51:19:069 0x600000015640 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() 2 "Connection closed" QVariant(Invalid)
08-31 09:51:19:070 0x600000015640 OCC::CheckServerJob::finished: error: status.php replied  0 ""
08-31 09:51:19:090 0x600000015640 OCC::PostfixLineEdit::setFullText: "https://srv.addr/nextcloud"
08-31 09:51:30:630 0x600000015640 OCC::PostfixLineEdit::setFullText: "https://srv.addr/nextcloud"
08-31 09:52:33:889 0x600000015640 OCC::SocketApi::slotNewConnection: SocketApi:  New connection SocketApiSocket(0x608000639560)
08-31 09:52:33:891 0x600000015640 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "SHARE_MENU_TITLE:Share with Nextcloud"
08-31 09:52:37:546 0x600000015640 -[DelegateObject updaterDidNotFindUpdate:]: -[DelegateObject updaterDidNotFindUpdate:]
```

2. Nginx error log (after clicking 'next')
```
2016/08/31 09:17:16 [info] 42607#100990: *2241 SSL_do_handshake() failed (SSL: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol) while SSL handshaking, client: my.server.ip, server: 0.0.0.0:443
2016/08/31 09:17:16 [info] 42607#100990: *2242 SSL_do_handshake() failed (SSL: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol) while SSL handshaking, client: my.server.ip, server: 0.0.0.0:443
2016/08/31 09:17:16 [info] 42607#100990: *2243 SSL_do_handshake() failed (SSL: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol) while SSL handshaking, client: my.server.ip, server: 0.0.0.0:443
2016/08/31 09:17:16 [info] 42607#100990: *2244 SSL_do_handshake() failed (SSL: error:140760FC:SSL routines:SSL23_GET_CLIENT_HELLO:unknown protocol) while SSL handshaking, client: my.server.ip, server: 0.0.0.0:443
```
3. NextCloud log: No entries at the time of attempted connexion

**Comment by danimo** [comment]
This is the ownCloud client bug tracker. Please address issues with the Nextcloud client with the nextcloud team.

**Comment by serge-vk** [comment]
Sorry about that. I must have misunderstood the Nextcloud request to post in this tracker.

**Comment by danimo** [comment]
They might have done that, but it's their software. If SSL clients fail, it's either a misconfiguration of your server OR a bug in the way the client has been built. Since we did not build the NC client, and hence do not know the exact version of components involved, we cannot assist you.

**Comment by serge-vk** [comment]
Well, I certainly have no complaints about yours :). Owncloud client is running just fine with my server. Thanks for your time.
