### ISSUE TITLE
admin recall renames the file instead of copying them

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5150]
At present the admin recall feature renames the recalled files. The side effect of this is that the original file disappears and it is removed from the server and other sync clients -- so it messes up with user's files directly. On top of that, renaming a file open by applications may be other unwanted side effects.

Here is the rename line: https://github.com/owncloud/client/blob/d2bde5489f2eff505c75062b3a34711b354456b1/src/libsync/propagatedownload.cpp#L641

The original prototype of this feature made a copy of the recalled files: https://github.com/owncloud/client/pull/3086/files#diff-f835340f15cbf9d4a063b12f58f4899eR1000

Is there any reason why copy was changed into rename? The only downside of the copy may be the lack of physical space on local device to make the copy (which should be handled gracefully). Otherwise the rename is really undesired as explained above.

Could we please change it to copy files instead?

**Comment by dragotin** [comment]
It was this commit https://github.com/owncloud/client/commit/2662203f by @ckamm -  @ckamm could you check pls?

**Comment by ckamm** [comment]
@dragotin That was unintentional, will do. How do you know it was that commit? Bisect?

**Comment by davitol** [comment]
:+1: WFM in Version 2.3.0-nightly20160929 (build 3715) for OSX
