### ISSUE TITLE
OBS key expired 2016-08-26

### ISSUE THREAD

**Issue by manulari** [owncloud/client#5156]
### Expected behaviour
apt-get update should complete without warning messages on Debian jessie

### Actual behaviour
apt-get update gives the following warning:
```
Reading package lists... Done
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org  Release: The following signatures were invalid: KEYEXPIRED 1472205884

W: Failed to fetch http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/Release  

W: Some index files failed to download. They have been ignored, or old ones used instead.
```

### Further information

Operating system: Debian jessie

```
root@isoveli:~# apt-key list
/etc/apt/trusted.gpg
--------------------
[...]

pub   1024D/BA684223 2012-02-08 [expired: 2016-08-26]
uid                  isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>
```

owncloud-related entries in /etc/apt/sources.list
```
#deb http://download.owncloud.org/download/repositories/9.0/Debian_8.0/ /
#deb-src http://download.owncloud.org/download/repositories/9.0/Debian_8.0/ /
deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/ /
```
(Had the first two in there but just verified that the message still shows up without them.)

### Steps to reproduce
1. run apt-get update on a Debian installation after having followed the instructions at https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

I tried redownloading the key there and it seems the same expired key is still being served.
Also, it would be nice to have at least an https download of the package signing key on the owncloud.org website.

**Comment by RealRancor** [comment]
@manulari 

> pub   1024D/BA684223 2012-02-08 [expires: 2017-04-19]
      Key fingerprint = F9EA 4996 7473 10AE 7947  4F44 977C 43A8 BA68 4223
uid                  isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>

so just re-import the already renewed key for now until the suggestion here is implemented: https://github.com/owncloud/client/issues/5055#issuecomment-245062679

**Comment by crrodriguez** [comment]
Fixed together with https://github.com/owncloud/enterprise/issues/1617
