### ISSUE TITLE
OPENSSL_INCLUDE_DIR

### ISSUE THREAD

**Issue by maimalash** [owncloud/client#5157]
$ cmake -DCMAKE_BUILD_TYPE="Debug" ../client
-- Build of crashreporter disabled.
-- GIT_SHA1 c97d8aa8fd710e4077de21a8e1a11dbc54b189de
CMake Error at /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_INCLUDE_DIR) (Required
  is at least version "1.0.0")
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.6.1/share/cmake/Modules/FindOpenSSL.cmake:380 (find_package_handle_standard_args)
  CMakeLists.txt:144 (find_package)

-- Configuring incomplete, errors occurred!

**Comment by guruz** [comment]
For build help try IRC (freenode #owncloud-client-dev) or https://central.owncloud.org/
