### ISSUE TITLE
[2.3] [OS X] [Qt bug] Since 2.3, the account tray menu seems broken, it does not have the submenu for each account

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5158]
Probably because of @ckamm 's changes, will have a look

**Comment by ckamm** [comment]
Thanks for checking this out!

**Comment by guruz** [comment]
It is not ```aboutToShow```, it is because of ```setupContextMenuIfVisible```
Could be https://bugreports.qt.io/browse/QTBUG-54845

**Comment by davitol** [comment]
WFM Let's close it 👍
