### ISSUE TITLE
Windows client shows sync error because of missing etag since 9.0 / nginx with gzip off

### ISSUE THREAD

**Issue by tobika** [owncloud/client#5159]
### Expected behaviour
Windows client should sync files

### Actual behaviour
Shows error that e-tag is missing since version 9.0, also 9.1

Under linux client no problem

### Steps to reproduce
1. Upgrade owncloud 8 to 9.0
2. Upgrade owncloud 9.0 to 9.1
3. Try to sync with windows client

### Server configuration
Operating system: Ubuntu 14.04

Web server: nginx 1.4.6

Database: mysql 5.5.49

PHP version: PHP 5.5.9-1ubuntu4.17

ownCloud version: 9.1

### Client configuration
Client version: 2.2.3

Operating system: Windows 7

OS language: French

Installation path of client: standard

I read all the posts about the e-tag problem with nginx, but i have gzip off; and no pagespeed module installed, that's why I really don't know what to try anymore

Thanks if someone knows something

**Comment by guruz** [comment]
Why would this be a client issue if it works with your Linux client but not your Windows client?
I'd guess that your Windows has a firewall / security app / virus scanner installed that could influence this.

**Comment by tobika** [comment]
thanks for your feedback, actually I installed it now on another windows machine to test again and it works here, so you might be right with the assumption that something else on this installation impacts the client, even though it worked before 9.0
