### ISSUE TITLE
Cannot get sync client working in Ubuntu 14.04

### ISSUE THREAD

**Issue by nephilim75** [owncloud/client#5161]
### Expected behaviour
Client logs me on

### Actual behaviour
It does not.

### Steps to reproduce
1. Installed the oC client using app manager in Ubuntu 14.04 and started the application
2. added server address and pressed "next"
3. typed in user credentials but client returns "Error: wrong login credentials"

### Server configuration
Operating system:
CentOS (Shared host)

Web server: 
Apache

Database:
mysql 10.0.27

PHP version:
5.6.25

ownCloud version:
nc10

Storage backend (external storage):
n/a

### Client configuration
Client version:
owncloud-client 1.5.0+dfsg-4ubuntu1

Operating system:
Ubuntu 14.04

OS language:
DE

Kind regards
//nephilim

**Comment by guruz** [comment]
For general support, we'd recommend to try https://central.owncloud.org/c/help/desktop-file-sync

Current client version is at 2.2.3, your 1.5 is too old.

https://owncloud.org/install/#install-clients

**Comment by nephilim75** [comment]
Thank you. This worked perfectly fine.
