### ISSUE TITLE
wizardUrlPostfix returning URL as <name>.url/owncloud/status.php

### ISSUE THREAD

**Issue by supportreq** [owncloud/client#5162]
I am adding a postfix in the URL setup as abc.com. While adding a new account it is asking me to enter the subdomain name instead of connecting directly to the subdomain.abc.com it is redirecting to subdomain.abc.com/owncloud/status.php

Please advice why is it adding owncloud folder to it and how can we disable it..

**Comment by guruz** [comment]
Please ask this via the support channels or use ownBrander
https://owncloud.org/support/
