### ISSUE TITLE
Plan potential 2.2.4 release

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#5168]
We might want to do a 2.2.4 release based on the 2.2 branch.

Looking at the master branch, I'd include the following patches:
* [x] a83c5598e850730c277f365e38a2348b825351a9 - ownCloud GmbH
* [x] 524220d0907713408298a36df18bd04635ce5563 - request loop selective sync
* [x] b541fea793a1249d6833474765e2b7a6574e492c - share link password
* [x] af9c4d0e2fe1a42e1faf14779ca5ef1088bd1314 - recall copies, not moves
* [x] 34650248985914523f0684c597f0c366b703f8d7 - fix leak
* [x] 98268d102fb343c103cbb4fb28dedd390f3c9ecf - ignore file casing in excluded files early-out
* [x] bd7ec196443202501d76f12db5f243e1efb7cf57 - discovery thread priority

And the following patches could be investigated:
* [x] 39e93768ea85ed0199ac4d95f511a4fb3e240da2 - back button in account wizard
* [x] 2d110540ee5a67d2c014fcf4258840d3aaf538ac - dolphin fix (minor)

We're not doing these:
* c2cb729fee51d9d45888c6fdb781e4a1a7b28edf aa5d3055be1c339fdd5c8acdfbbe795f529d0fa3 - excludes with non-canonical paths
* 87b4693a9db6e7d6812b257d3af072f653b87aae and eadecc5802977651e39968639c5b1c0eb6187eac - trailing space error message
* 88cd5421bfcfafa9f4aaa46cff6166dfce1f516d - only if tray on mac is fixed #5158 
* 82ef1bcfe0093d2191f0943fe90001c2bbfc1b9b - socket api parents of blacklisted items
* https://github.com/owncloud/enterprise/issues/1542 - potential issue in 1.8.x to 2.2.3 account migration

Finally:
* [x] Look at open pull requests, maybe some of these fix critical bugs.

**Comment by ckamm** [comment]
@ogoffart Do you think the data fingerprint change belongs to 2.2.4? I guess not?
@jturcotte Is the socket api "parents of blacklisted item" change a critical bugfix for 2.2.4?

Any  other comments on the "maybe" patches?

**Comment by guruz** [comment]
TODO: Also add @ogoffart 's patch on top of the new exclude check stuff

**Comment by guruz** [comment]
TODO: Add https://github.com/owncloud/client/pull/5186 when merged

**Comment by ogoffart** [comment]
We should be conservative in the patches.  So i'd say, maybe means no.
(these are not fixing regressions from previous versions)

**Comment by ckamm** [comment]
I think this may want to go into 2.2.4: #5181?

**Comment by guruz** [comment]
-> https://github.com/owncloud/client/issues/5206
