### ISSUE TITLE
Wrong wording for folder-size setting and corresponding error message

### ISSUE THREAD

**Issue by MarcusWolschon** [owncloud/client#5169]
String #1
ownCloud client > settings > general > advanced settings > "[√] ask confirmation before downloading folder larger than [500 MB]".

This setting applies to downloads AND UPLOADS. The wording must be changed into "ask confirmation before SYNCHRONIZING folder larger than"

String #2
"There are new folders that were not synchronized because they are too big:,"
With this message the user is shown an "apply" and "cancel" button.
However the message does not state what the user is supposed to apply or cancel.

"There are new folders not synchronized because they are too big.\n
Exclude and thus delete them from the local hard drive? "

**Comment by MarcusWolschon** [comment]
As a bug in a string resource, this needs to be fixed in all translations.

**Comment by ogoffart** [comment]
Regarding #1:  the current message is correct. It is only checking against server-side size of new folder before downloading them.

The second point is valid.

**Comment by MarcusWolschon** [comment]
@ogoffart are you sure?
As I was advised in #3989 changing this setting suddenly made it upload my >500MB folders .

**Comment by ckamm** [comment]
@MarcusWolschon Yes, if the big-folder limit applied to uploads, that would be a bug. Can you reproduce this problem somehow?

**Comment by ckamm** [comment]
@ogoffart What about this wording?
```
tr("There are new folders that were not synchronized because they are too big. "
   "If you want them synchronized, mark them and click \"Apply\": ") + msg;
```

**Comment by ogoffart** [comment]
Fixed by https://github.com/owncloud/client/pull/5204
