### ISSUE TITLE
Fedora 23 builds fail

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#5176]
qtkeychain (a dependency of the client) fails for Fedora23.
https://obs-new.int.owncloud.com/package/show/desktop/qt5keychain
strange enough it happily builds for Fedora22 and Fedora24.
This happends while trying to use qt5-qttools from the distribution.

Workaround: use our own opt-qt5-qttools
and massage project config with Prefer statements, so that any resulting have choice errors are handled.

**Comment by jnweiger** [comment]
Beware: our opt-qt5 packages are still at qt-5.4 where Fedora23 ships qt-5.5 packages normally. Not sure if mixing theirs and ours is a good idea...

**Comment by crrodriguez** [comment]
qt5keychain build correctly in internal obs
