### ISSUE TITLE
[Windows 7] [Installer] Unable to elevate, error: 5

### ISSUE THREAD

**Issue by olahaye74** [owncloud/client#5178]
Issue similar to issue #2616 but with error 5 (not 6). Installer is unable to elevate privileges despite the correct admin login and pasword has been provided to the popup window.
### Expected behaviour

Installer can elevate privileges once admin password is provided.
### Actual behaviour

privilege elevation fails with error 5
### Steps to reproduce
1. login as a active directory user with no privilege at all.
2. Either start the installer (or, if already installed, request upgrade)
3. when prompted, give a local administrator account (.\local-admin) and the correct password
4. Error raises: "Unable to elevate, error: 5"

=> If I runas the installer with the .\local-admin, it works, but if I run it as simple active directory user and gives the local-admin login and password, it fails with error 5.

OS: 
Some security policies are in place, but I don't know which ones. Any parameter that I could give to the installer to have more output about the error 5? (BTW, I can't understand why in 2016 we still have numbers for errors instead of meangfull messages. In the pas it was usefull to same memory, but eighties are over, now we have enough disk and ram to have full error messages (even translated)).
### Client configuration

Client version:
2.2.3.6307 (same problem on previous versions)

Operating system:
Windows 7 Enterprise Service Pack 1 64bits

OS language:
fr (French)

Installation path of client:
C:\Users<domain_user>\Downloads\ownCloud-2.2.3.6307-setup.exe
### Logs

Unfortunately no output from installer except the error popup. Even when starting the installer from a cmd.exe, no /v switch will help.

**Comment by guruz** [comment]
We're using NSIS, maybe check their error message mappings

**Comment by olahaye74** [comment]
After a lot of goggling, it seems that error 5 is related to "access denied". To what? I can't tell.
Looking around in our windows setup,, the UAC is enabled to the max.

When running secpol.msc, the security setup is the following (using my french to english translation :-/ )
- UAC: use secure desktop when elevation request: activated
- UAC: permit UIAccess application to request elevation without using secure desktop: disabled
- UAC: requester behavior for admin using admin auth mode: request ack
- UAC: elevation requester behavior for normal user: request admin login using secure desktop
- UAC: detect app install and ask for elevation: enabled
- UAC: only elevate app UIAccess installed in secure paths: enabled
- UAC: only elevate signed executable: disabled
- UAC: run admin account in admin approbation mode: enabled
- UAC: view file and registry write failures in user defined places: Enabled

Aside that, I can't help more :-/

**Comment by olahaye74** [comment]
Maybe this has something related to this issue: https://candritzky.wordpress.com/2012/08/28/uac-elevation-and-the-default-administrator-account/

**Comment by ogoffart** [comment]
Is this still a problem with recent version? (2.4)

**Comment by olahaye74** [comment]
Had the error when I upgraded to 2.3.4.
where can I download the 2.4 version to test it?

**Comment by olahaye74** [comment]
Tested ownCloud-2.4.0.8784rc1-setup.exe starting it from simple domain user and typing .\admin-local and correct password when prompted => Unable to elevate, error: 5
right click + run as administrator, giving .\admin-loca and correct password on the installer exe and it works.

**Comment by guruz** [comment]
CC @dschmidt @danimo maybe..

**Comment by ogoffart** [comment]
Closing old issue.
2.5 has a new installer.

**Comment by Neemma** [comment]
Still got the same issue in 2024.

My FIX:  Run the .exe file as Administrator. 


<img width="560" alt="Run as Admin" src="https://github.com/owncloud/client/assets/91252960/4dfe906f-2a6c-47bc-9529-bdcafcdd2cb3">
