### ISSUE TITLE
Licence incompatibilities

### ISSUE THREAD

**Issue by XRevan86** [owncloud/client#5180]
src/3rdparty/QProgressIndicator/ is licensed under LGPLv3+ which [cannot mix](https://gnu.org/licenses/gpl-faq.en.html#AllCompatibility) with GPLv2 (different from GPLv2+).

There are multiple GPLv2 licensed files in src/cmd/, src/libsync/, src/gui/ and src/3rdparty/certificates/,
you can see them when using `grep -R "version 2 of the License\."` in the tree root (dot at the end means there's no "`, or (at your option) any later version.`" afterwards).

GPLv2 is also a problem for src/3rdparty/libcrashreporter-qt/ which is GPLv3+ licensed.

**Comment by michaelstingl** [comment]
@jnweiger @hodyroff ?

**Comment by jnweiger** [comment]
This was not intentional. 
I suggest to correct the situation by  broadening the LGPL-V2 license declaration to always say LGPL-V2+ instead.

**Comment by hodyroff** [comment]
Approved. Need to add to the dependency list. libcrashreporter-qt is only used in the Windows built and if needed could be taken out. Any other GPL code included needs special approval.
