### ISSUE TITLE
Update information related to ownCloud Inc in the about section of general settings

### ISSUE THREAD

**Issue by davitol** [owncloud/client#5181]
Licensed under the GNU General Public License (GPL) Version 2.0
ownCloud and the ownCloud Logo are registered trademarks of ownCloud, Inc. in the United States, other countries, or both.

![screen shot 2016-09-14 at 11 30 16](https://cloud.githubusercontent.com/assets/10596560/18507049/fc1d20fe-7a6e-11e6-81e5-d36b08fa9c51.png)

Desktop Client: Version 2.3.0-nightly20160913 (build 3674)

@dragotin

**Comment by davitol** [comment]
Not sure if maybe it could be possible to have this fix for 2.2.4 milestone as we have already included this commit https://github.com/owncloud/client/commit/a83c5598e850730c277f365e38a2348b825351a9 related to gmbH info in 2.2.4 version

**Comment by ckamm** [comment]
@danimo @dragotin Does this string also need to change? Is this something we should block 2.2.4 on?

**Comment by hodyroff** [comment]
@ckamm Yes. No.

**Comment by guruz** [comment]
Done for 2.3, we don't do it for 2.2.4 because of transifex delays..
