### ISSUE TITLE
[2.2.3] [Overlays] File collision of nautilus-plugin for branded clients

### ISSUE THREAD

**Issue by olifre** [owncloud/client#5183]
The code in 
https://github.com/owncloud/client/blob/master/shell_integration/nautilus/CMakeLists.txt#L22
always installs the resulting file as "syncstate.py". 
This creates a file collision if both the vanilla client and a branded client are installed. 

Suggested fix:
```
-    install(FILES ${CMAKE_CURRENT_BINARY_DIR}/syncstate.py DESTINATION ${DATADIR}/nautilus-python/extensions)
-    install(FILES ${CMAKE_CURRENT_BINARY_DIR}/syncstate_nemo.py DESTINATION ${DATADIR}/nemo-python/extensions RENAME syncstate.py)
+    install(FILES ${CMAKE_CURRENT_BINARY_DIR}/syncstate.py DESTINATION ${DATADIR}/nautilus-python/extensions RENAME syncstate-${APPLICATION_SHORTNAME}.py)
+    install(FILES ${CMAKE_CURRENT_BINARY_DIR}/syncstate_nemo.py DESTINATION ${DATADIR}/nemo-python/extensions RENAME syncstate-${APPLICATION_SHORTNAME}.py)
```

### Expected behaviour
Native client and branded client can be installed in parallel, nautilus integration works. 

### Actual behaviour
File collision. 

### Client configuration
Operating system: Gentoo Linux x86_64

**Comment by ckamm** [comment]
The suggestion looks good to me. @dragotin do you think newer packages including syncstate-ownCloud.py instead of syncstate.py will be a problem? If it is, we could only add the postfix if APPLICATION_SHORTNAME isn't ownCloud...

**Comment by ckamm** [comment]
@olifre I've applied your patch since it looked good to me.

**Comment by olifre** [comment]
@ckamm Thanks a lot, just to confirm, I tested your patch on top of the fresh 2.2.4 release and it works fine, as expected.

**Comment by ckamm** [comment]
@olifre Thanks for testing!
