### ISSUE TITLE
Files of unchecked parent folders are synchronized

### ISSUE THREAD

**Issue by scriptPilot** [owncloud/client#5191]
ownCloud Client 2.1.1, Windows 7:

I select only folder /owncloud/main/**sub** for synchronization.
But all files in /owncloud and /owncloud/main are synchronized as well.
Files in /owncloud/otherMain or /owncloud/main/otherSub are not synchronized (as expected).

Expected behaviour : Only folder /owncloud/main/sub and containing files are synchronized.

**Comment by ogoffart** [comment]
That's by design:  Unchecked works ike a blacklist.

If you wish to only sync a sub directory, you should add a new folder only for this directory.

**Comment by scriptPilot** [comment]
Okay, thank for that reply.
