### ISSUE TITLE
Could not find a package configuration file provided by "Qt5WebKitWidgets"

### ISSUE THREAD

**Issue by maimalash** [owncloud/client#5193]
C:\Users\Mai.SCOPEIS\client-build>cmake -G "MinGW Makefiles" ../client
-- Build of crashreporter disabled.
-- GIT_SHA1 524220d0907713408298a36df18bd04635ce5563
-- Could NOT find INOTIFY (missing:  INOTIFY_INCLUDE_DIR INOTIFY_LIBRARY_DIR)
-- Could NOT find Sphinx (missing:  SPHINX_EXECUTABLE)
-- Could NOT find PdfLatex (missing:  PDFLATEX_EXECUTABLE)
-- Using own sqlite3 from C:/Users/Mai.SCOPEIS/client/src/3rdparty/sqlite3
-- Could NOT find ZLIB (missing:  ZLIB_LIBRARY ZLIB_INCLUDE_DIR)
-- Using own sqlite3 from C:/Users/Mai.SCOPEIS/client/src/3rdparty/sqlite3
-- Found Qt5 core, checking for further dependencies...
CMake Error at cmake/modules/QtVersionAbstraction.cmake:25 (find_package):
  By not providing "FindQt5WebKitWidgets.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "Qt5WebKitWidgets", but CMake did not find one.

  Could not find a package configuration file provided by "Qt5WebKitWidgets"
  with any of the following names:

    Qt5WebKitWidgetsConfig.cmake
    qt5webkitwidgets-config.cmake

  Add the installation prefix of "Qt5WebKitWidgets" to CMAKE_PREFIX_PATH or
  set "Qt5WebKitWidgets_DIR" to a directory containing one of the above
  files.  If "Qt5WebKitWidgets" provides a separate development package or
  SDK, be sure it has been installed.
Call Stack (most recent call first):
  src/CMakeLists.txt:8 (include)

-- Configuring incomplete, errors occurred!
See also "C:/Users/Mai.SCOPEIS/client-build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/Mai.SCOPEIS/client-build/CMakeFiles/CMakeError.log".

am using windows 8.1 64

**Comment by dragotin** [comment]
You need to install the QtWebKit devel packages.

Please abstain from using the bugtracker for build help, rather ask on central. Thx.
