### ISSUE TITLE
owncloudcmd - silent mode doesn't work 

### ISSUE THREAD

**Issue by TKLCZ** [owncloud/client#5196]
### Expected behaviour
Minimal command output with -s or --silent parameter 

### Actual behaviour
The same outputs with and without -s or --silent parameter

### Steps to reproduce
1. Install the last version of ownCloud client on linux (Ubuntu 16.04 for example)
2. Run the command "owncloudcmd -s /home/user/folder/ https://owncloud.server/remote.php/webdav/folder" from terminal
3. Check the command output and compare with output without -s

### Server configuration
Operating system:
Debian Wheezy
Web server: 
Apache 2.2.22
Database:
MySQL 5.4.52
PHP version:
5.4.45
ownCloud version:
8.0.3
Storage backend (external storage):

### Client configuration
Client version:
2.2.3
Operating system:
Ubuntu 16.04
OS language:
Czech
Installation path of client:
/usr/share/owncloud
/usr/bin

**Comment by ogoffart** [comment]
I see, we ignore csync message, but not qDebug

**Comment by davitol** [comment]
:+1: WFM "Minimal" command output with -s or --silent parameter. There's different outputs running the command with and without the -s parameter
