### ISSUE TITLE
[2.2.4] Checkboxes for the permissions are no longer available if you uncheck and check can edit permissions sharing with a group

### ISSUE THREAD

**Issue by davitol** [owncloud/client#5197]
### Steps to reproduce
1. Share a file via owncloud with a **group that contains the own user.**
2. Uncheck can edit permission
3. Check again can edit permission

### Expected behaviour

In the screen the checkboxes for the permissions should be enabled

### Actual behaviour

The checkboxes for the permissions are no longer available. If you close the share window and you reopen it again, 'can edit' option is unchecked

### Server configuration

Operating system: OSX 10.10.5 (14F1909) client; Ubuntu 14.04 server

Web server: Apache

Database: MySQL

PHP version: 

PHP 5.5.9

ownCloud version:

"9.0.5.2","versionstring":"9.0.5","edition":"

![desktopbugedit](https://cloud.githubusercontent.com/assets/10596560/18740150/79a5d40a-80a8-11e6-996a-90283aa6e96d.gif)

@owncloud/desktop-developers

**Comment by ckamm** [comment]
I think this is an error handling problem. I see the log message
```
OCC::OcsJob::finished: Reply to "PUT" QUrl("http://localhost/ocs/v1.php/apps/files_sharing/api/v1/shares/207") (QPair("permissions","19")) has unexpected status code: 404 "{\"ocs\":{\"meta\":{\"status\":\"failure\",\"statuscode\":404,\"message\":\"Cannot increase permissions\"},\"data\":[]}}"
```
and will investigate further.

**Comment by ckamm** [comment]
I think the server incorrectly replies "Cannot increase permissions" here, because because in this case this is both an incoming and an outgoing share for the user. And there's code in the server that checks that one cannot increase the permissions of incoming shares.

**Comment by jesmrec** [comment]
Checked with iOS mobile client, the bug is reproduceable:

[increase_permissions.zip](https://github.com/owncloud/client/files/487035/increase_permissions.zip)

**Comment by davitol** [comment]
solved with https://github.com/owncloud/core/pull/26187
