### ISSUE TITLE
When the "new big folder" warning pops up, pressing "Cancel" doesn't dismiss the selective sync ui

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#5202]
* Create a big folder on the server
* Get the selective sync with the red text on the client.
* Press "Cancel". 
* It closes the folder list, but the red text and the "Cancel" / "Apply" buttons stay visible!
* They also stay there after a restart of the client.

**Comment by guruz** [comment]
What about 2.2.x?

**Comment by ckamm** [comment]
I see the same behavior in 2.2.3, it's not a regression.

**Comment by ckamm** [comment]
Fixed by removing the "Cancel" button in this case :)

**Comment by davitol** [comment]
> removing the "Cancel" button

:+1: WFM
