### ISSUE TITLE
Useless help button appears in Desktop Client for Windows [2.2.4]

### ISSUE THREAD

**Issue by davitol** [owncloud/client#5203]
In the upper part of the share window, a '?' button appears and clicking on it, no help or action are displayed 

![screen shot 2016-09-23 at 11 47 08](https://cloud.githubusercontent.com/assets/10596560/18781788/97981cb2-8183-11e6-9fe0-09bfd73fe501.png)

**Comment by guruz** [comment]
Which Windows version?

**Comment by davitol** [comment]
Windows 10 Enterprise 64-bits

**Comment by ckamm** [comment]
I can reproduce on Windows 7.

**Comment by davitol** [comment]
Tested in Version 2.3.0-nightly20160929 (build 6415) and WFM :+1:
