### ISSUE TITLE
Nightlies went from 2.3.0 to 2.2.4 again

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/client#5205]
It seems odd, but nightlies that already switched to 2.3.0 are now at 2.2.4 version again: http://download.opensuse.org/repositories/isv:/ownCloud:/community:/nightly/xUbuntu_16.04/
Shouldn't it always go forward?

**Comment by guruz** [comment]
It will go forward again sometime the next days..

-> https://github.com/owncloud/client/issues/5168

**Comment by guruz** [comment]
Are you saying it downgraded your client version to 2.2.4?

**Comment by nazar-pc** [comment]
No, newer version is smaller, so it wasn't downgraded

**Comment by guruz** [comment]
ok good :)
