### ISSUE TITLE
[Linux] Use 2-digit month and day numbers in nightly builds

### ISSUE THREAD

**Issue by nazar-pc** [owncloud/client#5207]
Currently I'm having nightly version from September 22nd: `2.3.0~nightly2016922-1.1`.
But I'll not be able to update automatically to the version from October 1st: `2.3.0~nightly2016101-1.1` because technically it is considered to be smaller by package manager.
However, `2.3.0~nightly20161001-1.1` is indeed bigger than `2.3.0~nightly20160922-1.1`, so it is better to always put leading `0` even for days/months whose numbers are < 10.

**Comment by crrodriguez** [comment]
@dragotin Do you know where all this stuff is generated ?

**Comment by jnweiger** [comment]
@crrodriguez Found it: 
https://github.com/owncloud/administration/blob/master/jenkins/obs_integration/genbranding.pl#L556

**Comment by crrodriguez** [comment]
@jnweiger got it. So, two issues. first ..it  ought to be gmtime.. not localtime.. second.. the month should be my $month = sprintf '%02d' , $m + 1;

**Comment by jnweiger** [comment]
same with day. should be $day = sprintf "%02d", $d
or similar....

**Comment by crrodriguez** [comment]
Should be fixed by https://github.com/owncloud/administration/commit/be7494b9ba3606332e852003a88e9fb0b055a8e9 
Thanks for your report
