### ISSUE TITLE
[2.2.4] [Windows] Wrong size of a button in the configuration wizard

### ISSUE THREAD

**Issue by davitol** [owncloud/client#5209]
![screen shot 2016-09-27 at 12 51 49](https://cloud.githubusercontent.com/assets/10596560/18870817/bee7ce48-84b2-11e6-8e0e-d8cc1df01763.png)

oC Desktop Version 2.2.4 (build 6408) running on Windows 10 EE

**Comment by ogoffart** [comment]
I submitted a change that might fix the issue.  Altouh i was not able to reproduce on my windows 10

**Comment by davitol** [comment]
@ogoffart Tested in TestPilot Version 2.3.0-nightly20161011 (build 6441) and the issue is still happening

**Comment by ogoffart** [comment]
I can't reproduce using the same build.  Here is what i see: 

![screenshot_20161011_112635](https://cloud.githubusercontent.com/assets/959326/19265499/aabbd47a-8fa5-11e6-8f00-dba69d4162cb.png)

**Comment by davitol** [comment]
@ogoffart Tested in other Windows 10 Pro Versión: 1511 and it works fine. It seems to happen only in my VM of Windows so IMHO let's close it and if someone has the same behaviour in the future, feel free to reopen it
