### ISSUE TITLE
Prevent installation directory and synchronization directory from overlapping

### ISSUE THREAD

**Issue by Erlkoenig90** [owncloud/client#5214]
### Expected behaviour

When during installation the user attempts to synchronize a directory inside the directory into which the client was installed or vice-versa, an error message should be displayed.
### Actual behaviour

The client copies its own program files (exe and dll files) to the OwnCloud server.
### Steps to reproduce
1. Install OwnCloud client to C:\OwnCloud
2. Select C:\OwnCloud as synchronization directory
### Server configuration

Operating system: Ubuntu Linux 16.04

Web server: Apache 2.4.18

Database: MySQL 5.7.15

PHP version: PHP 7.0.8

ownCloud version: 9.1.1

Storage backend (external storage): None
### Client configuration

Client version: 2.2.4.6408

Operating system: Windows 10

OS language: German

Installation path of client: C:\OwnCloud

**Comment by TheOneRing** [comment]
Just don't  do that

**Comment by Erlkoenig90** [comment]
Some non-tech savvy users don't know they shouldn't do that. That's why an error message telling them to not do that would be helpful.
