### ISSUE TITLE
[2.2.4] OpenSuse KDE and XFCE Sync: Segfault on start

### ISSUE THREAD

**Issue by jjanarnava** [owncloud/client#5218]
OPensuse LEAP 42.1

As i need it for a productive system some tips would be greatly appreciated. (Because of the Inability to upload folders with the web client)

Thank you!
Bret

### Expected behaviour
file should run

### Actual behaviour
 osiris kernel: Thread (pooled)[5931]: segfault at 7f758cf87570 ip 00007f7567fe4f8e sp 00007f7569612368 error 7 in libkdecore.so.5.14.24[7f7567f46000+2b0000]

### Steps to reproduce
After my last distribution update the owncloud sync client 2.2.4.13.2 x86_64 does not start anymore: Memory Access Error

    xxx@osiris:~> owncloud

    (owncloud:4399): GLib-GObject-WARNING **: The property GtkSettings:gtk-fallback-icon-theme is deprecated and shouldn't be used anymore. It will be removed in a future version.
    Speicherzugriffsfehler
    xxx@osiris:~>

This is the same for KDE or XFCE-Desktop environment. I tried to downgrade to 2.2.4.1.1 x86_64 but same problem.

the packages are from: build.opensuse.org/isv:ownCloud

### Server configuration
It is not Server related as it does not come to a connection...

### Client configuration
Client version:
2.2.4.13.2 x86_64
Operating system:
LEAP42.1
OS language:
German Deutsch
Installation path of client:
/usr/lib64/owncloud
### Logs
osiris kernel: Thread (pooled)[5931]: segfault at 7f758cf87570 ip 00007f7567fe4f8e sp 00007f7569612368 error 7 in libkdecore.so.5.14.24[7f7567f46000+2b0000]

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
xxx@osiris:~> owncloud --logwindow

(owncloud:7205): GLib-GObject-WARNING **: The property GtkSettings:gtk-fallback-icon-theme is deprecated and shouldn't be used anymore. It will be removed in a future version.
Speicherzugriffsfehler
xxx@osiris:~> ^C

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
Can you run the client in gdb?
```
gdb owncloud
```
Then on crash:
```
thread apply all bt
```
paste that here.

**Comment by jjanarnava** [comment]
Hallo guruz,

thanks for your answer. Here the results

(1) running as a user or root (same result): 
```
user@osiris:/usr/bin> gdb owncloud
GNU gdb (GDB; openSUSE Leap 42.1) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-suse-linux".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://bugs.opensuse.org/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from owncloud...Reading symbols from /usr/lib/debug/usr/bin/owncloud.debug...done.
done.
(gdb) thread apply all bt
(gdb) 

```
and 
```

user@osiris:/usr/bin> owncloud

(owncloud:4502): GLib-GObject-WARNING **: The property GtkSettings:gtk-fallback-icon-theme is deprecated and shouldn't be used anymore. It will be removed in a future version.
Speicherzugriffsfehler
user@osiris:/usr/bin> 

```
I made shure all versions are to 2.2.4.1.1 as for 2.2.4.13.3 no debug info youd be found in the repository.

**Comment by guruz** [comment]
@jjanarnava Sorry, i missed an essential part. You need to actually run it

```
r --logfile -
```
should do it (after being in gdb)

**Comment by jjanarnava** [comment]
an enable logging before...

> (gdb) thread apply all bt                                                                                                                                                         
>                                                                                                                                                                                   
> Thread 5 (Thread 0x7fffc0979700 (LWP 8563)):                                                                                                                                      
> #0  0x00007ffff213abfd in poll () at /lib64/libc.so.6                                                                                                                             
> #1  0x00007fffefa29e64 in  () at /usr/lib64/libglib-2.0.so.0                                                                                                                      
> #2  0x00007fffefa29f7c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0                                                                                              
> #3  0x00007ffff3787f4b in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5                                             
> #4  0x00007ffff373789b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5                                                                
> #5  0x00007ffff357e02a in QThread::exec() () at /usr/lib64/libQt5Core.so.5                                                                                                        
> #6  0x00007ffff3582859 in  () at /usr/lib64/libQt5Core.so.5                                                                                                                       
> #7  0x00007ffff17410a4 in start_thread () at /lib64/libpthread.so.0                                                                                                               
> #8  0x00007ffff214302d in clone () at /lib64/libc.so.6                                                                                                                            
>                                                                                                                                                                                   
> Thread 4 (Thread 0x7fffd65ac700 (LWP 8537)):                                                                                                                                      
> #0  0x00007ffff213abfd in poll () at /lib64/libc.so.6                                                                                                                             
> #1  0x00007fffefa29e64 in  () at /usr/lib64/libglib-2.0.so.0                                                                                                                      
> #2  0x00007fffefa29f7c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0                                                                                              
> #3  0x00007ffff3787f2c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5                                             
> #4  0x00007ffff373789b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5                                                                
> #5  0x00007ffff357e02a in QThread::exec() () at /usr/lib64/libQt5Core.so.5                                                                                                        
> #6  0x00007ffff3582859 in  () at /usr/lib64/libQt5Core.so.5                                                                                                                       
> #7  0x00007ffff17410a4 in start_thread () at /lib64/libpthread.so.0                                                                                                               
> #8  0x00007ffff214302d in clone () at /lib64/libc.so.6                                                                                                                            
>                                                                                                                                                                                   
> Thread 3 (Thread 0x7fffd6dad700 (LWP 8536)):                                                                                                                                      
> #0  0x00007ffff213abfd in poll () at /lib64/libc.so.6                                                                                                                             
> #1  0x00007fffefa29e64 in  () at /usr/lib64/libglib-2.0.so.0                                                                                                                      
> #2  0x00007fffefa29f7c in g_main_context_iteration () at /usr/lib64/libglib-2.0.so.0                                                                                              
> #3  0x00007ffff3787f2c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5                                             
> #4  0x00007ffff373789b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib64/libQt5Core.so.5                                                                
> #5  0x00007ffff357e02a in QThread::exec() () at /usr/lib64/libQt5Core.so.5
> #6  0x00007ffff792b465 in  () at /usr/lib64/libQt5DBus.so.5
> #7  0x00007ffff3582859 in  () at /usr/lib64/libQt5Core.so.5
> #8  0x00007ffff17410a4 in start_thread () at /lib64/libpthread.so.0
> #9  0x00007ffff214302d in clone () at /lib64/libc.so.6
> 
> Thread 2 (Thread 0x7fffe4032700 (LWP 8535)):
> #0  0x00007ffff213abfd in poll () at /lib64/libc.so.6
> #1  0x00007fffeb9eb422 in  () at /usr/lib64/libxcb.so.1
> #2  0x00007fffeb9ed00f in xcb_wait_for_event () at /usr/lib64/libxcb.so.1
> #3  0x00007fffe678f469 in  () at /usr/lib64/libQt5XcbQpa.so.5
> #4  0x00007ffff3582859 in  () at /usr/lib64/libQt5Core.so.5
> #5  0x00007ffff17410a4 in start_thread () at /lib64/libpthread.so.0
> #6  0x00007ffff214302d in clone () at /lib64/libc.so.6
> 
> Thread 1 (Thread 0x7ffff7f91780 (LWP 8534)):
> #0  0x00007fffbb9d2f8e in  () at /usr/lib64/libkdecore.so.5
> #1  0x00007ffff7dea8ea in call_init.part () at /lib64/ld-linux-x86-64.so.2
> #2  0x00007ffff7dea9d3 in _dl_init_internal () at /lib64/ld-linux-x86-64.so.2
> #3  0x00007ffff7deeb08 in dl_open_worker () at /lib64/ld-linux-x86-64.so.2
> #4  0x00007ffff7dea7a4 in _dl_catch_error () at /lib64/ld-linux-x86-64.so.2
> #5  0x00007ffff7dee2fb in _dl_open () at /lib64/ld-linux-x86-64.so.2
> #6  0x00007fffebc0102b in dlopen_doit () at /lib64/libdl.so.2
> #7  0x00007ffff7dea7a4 in _dl_catch_error () at /lib64/ld-linux-x86-64.so.2
> #8  0x00007fffebc015dd in _dlerror_run () at /lib64/libdl.so.2
> #9  0x00007fffebc010c1 in dlopen@@GLIBC_2.2.5 () at /lib64/libdl.so.2
> #10 0x00007fffe8704f25 in libmodman::module_manager::load_file(std::string, bool) () at /usr/lib64/libmodman.so.1
> #11 0x00007fffe87052b3 in libmodman::module_manager::load_dir(std::string, bool) () at /usr/lib64/libmodman.so.1
> #12 0x00007fffec4efe06 in  () at /usr/lib64/libproxy.so.1
> #13 0x00007fffec4f09bb in px_proxy_factory_new () at /usr/lib64/libproxy.so.1
> #14 0x00007ffff3c47589 in QNetworkProxyFactory::systemProxyForQuery(QNetworkProxyQuery const&) () at /usr/lib64/libQt5Network.so.5
> #15 0x00007ffff3c3f471 in  () at /usr/lib64/libQt5Network.so.5
> #16 0x00007ffff3c3ec44 in  () at /usr/lib64/libQt5Network.so.5
> #17 0x00007ffff3c3f09a in QNetworkProxyFactory::proxyForQuery(QNetworkProxyQuery const&) () at /usr/lib64/libQt5Network.so.5
> #18 0x00007ffff3bedb60 in  () at /usr/lib64/libQt5Network.so.5
> #19 0x00007ffff3c12e14 in  () at /usr/lib64/libQt5Network.so.5
> #20 0x00007ffff3c14980 in  () at /usr/lib64/libQt5Network.so.5
> #21 0x00007ffff3c14cbb in  () at /usr/lib64/libQt5Network.so.5
> #22 0x00007ffff3c154d8 in  () at /usr/lib64/libQt5Network.so.5
> #23 0x00007ffff3bef182 in QNetworkAccessManager::createRequest(QNetworkAccessManager::Operation, QNetworkRequest const&, QIODevice*) () at /usr/lib64/libQt5Network.so.5
> #24 0x00007ffff4e98e4c in OCC::AccessManager::createRequest(QNetworkAccessManager::Operation, QNetworkRequest const&, QIODevice*) (this=
>     0xb5c630, op=QNetworkAccessManager::GetOperation, request=..., outgoingData=0x0) at /usr/src/debug/owncloudclient-2.2.4/src/libsync/accessmanager.cpp:72
> #25 0x00007ffff3beb934 in QNetworkAccessManager::get(QNetworkRequest const&) () at /usr/lib64/libQt5Network.so.5
> #26 0x0000000000561f56 in  ()
> #27 0x0000000000e98510 in  ()
> #28 0x00007fffffffcea0 in  ()
> #29 0x0000000000e8cb80 in  ()
> #30 0x00007fffffffce90 in  ()
> #31 0x00007fffffffcea0 in  ()
> #32 0x00000000005614af in  ()
> #33 0x0000000000e98510 in  ()
> #34 0x00007ffff2067020 in  () at /lib64/libc.so.6
> #35 0x000000000125b9a0 in  ()
> #36 0x0000000000e8cb80 in  ()
> #37 0x0000000000c54ec0 in  ()
> #38 0x00007ffff7df01e5 in _dl_runtime_resolve () at /lib64/ld-linux-x86-64.so.2
> #39 0x00000000005618a1 in  ()
> #40 0x000000000126dbb0 in  ()
> #41 0x0000000000000001 in  ()
> #42 0x0000000000e98510 in  ()
> #43 0x00007fff00000001 in  ()
> #44 0x0000000000ce2570 in  ()
> #45 0x00007fff00000001 in  ()
> #46 0x000001b900000002 in  ()
> #47 0x00000000005de4a8 in  ()
> #48 0x00000000005deb00 in  ()
> #49 0x0000000000569d26 in  ()
> #50 0x00007fffffffcf8f in  ()
> #51 0x00007fffffffcfc0 in  ()
> #52 0x0000000000000000 in  ()
> (gdb) 
>

**Comment by guruz** [comment]
(You forgot to paste the part of the gdb output that says which thread crashed :-)

Most likely a dup of https://github.com/owncloud/client/issues/4525

Can you check the workarounds there? Ideally, also comment on there again which distro you have and which workaround or library update helped you.

**Comment by jjanarnava** [comment]
this one?

> Thread 1 "owncloud" received signal SIGSEGV, Segmentation fault.
> 0x00007fffbb9d2f8e in ?? () from /usr/lib64/libkdecore.so.5
> Missing separate debuginfos, use: zypper install Mesa-debuginfo-11.0.8-151.1.x86_64 Mesa-libGL1-debuginfo-11.0.8-151.1.x86_64 Mesa-libglapi0-debuginfo-11.0.8-151.1.x86_64 breeze5-style-debuginfo-5.7.95-124.1.x86_64 fontconfig-debuginfo-2.11.0-5.1.x86_64 kimageformats-debuginfo-5.26.0-96.1.x86_64 kio-core-debuginfo-5.26.0-145.1.x86_64 kio-debuginfo-5.26.0-145.1.x86_64 kservice-debuginfo-5.26.0-120.1.x86_64 kwayland-debuginfo-5.26.0-94.1.x86_64 libFLAC8-debuginfo-1.3.0-9.2.x86_64 libHalf11-debuginfo-2.1.0-4.2.x86_64 libICE6-debuginfo-1.0.9-3.1.x86_64 libIex-2_1-11-debuginfo-2.1.0-4.2.x86_64 libIlmImf-Imf_2_1-21-debuginfo-2.1.0-6.2.x86_64 libIlmThread-2_1-11-debuginfo-2.1.0-4.2.x86_64 libKF5Archive5-debuginfo-5.26.0-97.1.x86_64 libKF5Attica5-debuginfo-5.26.0-101.1.x86_64 libKF5Auth5-debuginfo-5.26.0-111.1.x86_64 libKF5Bookmarks5-debuginfo-5.26.0-98.1.x86_64 libKF5Codecs5-debuginfo-5.26.0-99.1.x86_64 libKF5Completion5-debuginfo-5.26.0-101.1.x86_64 libKF5ConfigCore5-debuginfo-5.26.0-113.1.x86_64 libKF5ConfigGui5-debuginfo-5.26.0-113.1.x86_64 libKF5ConfigWidgets5-debuginfo-5.26.0-100.1.x86_64 libKF5CoreAddons5-debuginfo-5.26.0-114.1.x86_64 libKF5DBusAddons5-debuginfo-5.26.0-95.1.x86_64 libKF5GlobalAccel5-debuginfo-5.26.0-105.1.x86_64 libKF5GuiAddons5-debuginfo-5.26.0-99.1.x86_64 libKF5I18n5-debuginfo-5.26.0-123.1.x86_64 libKF5IconThemes5-debuginfo-5.26.0-1.1.x86_64 libKF5ItemViews5-debuginfo-5.26.0-93.1.x86_64 libKF5JobWidgets5-debuginfo-5.26.0-99.1.x86_64 libKF5Notifications5-debuginfo-5.26.0-109.1.x86_64 libKF5Solid5-debuginfo-5.26.0-104.1.x86_64 libKF5SonnetCore5-debuginfo-5.26.0-105.1.x86_64 libKF5SonnetUi5-debuginfo-5.26.0-105.1.x86_64 libKF5Style5-debuginfo-5.26.0-111.1.x86_64 libKF5TextWidgets5-debuginfo-5.26.0-93.1.x86_64 libKF5WidgetsAddons5-debuginfo-5.26.0-106.1.x86_64 libKF5WindowSystem5-debuginfo-5.26.0-116.1.x86_64 libKF5XmlGui5-debuginfo-5.26.0-116.1.x86_64 libLLVM-debuginfo-3.7.0-2.2.x86_64 libQt5Core5-debuginfo-5.7.0-268.1.x86_64 libQt5DBus5-debuginfo-5.7.0-268.1.x86_64 libQt5Gui5-debuginfo-5.7.0-268.1.x86_64 libQt5Network5-debuginfo-5.7.0-268.1.x86_64 libQt5OpenGL5-debuginfo-5.7.0-268.1.x86_64 libQt5Positioning5-debuginfo-5.7.0-52.1.x86_64 libQt5PrintSupport5-debuginfo-5.7.0-268.1.x86_64 libQt5Sensors5-debuginfo-5.7.0-71.1.x86_64 libQt5Sql5-debuginfo-5.7.0-268.1.x86_64 libQt5Svg5-debuginfo-5.7.0-84.1.x86_64 libQt5WebChannel5-debuginfo-5.7.0-25.1.x86_64 libQt5WebKit5-debuginfo-5.7.0-141.1.x86_64 libQt5WebKitWidgets5-debuginfo-5.7.0-141.1.x86_64 libQt5Widgets5-debuginfo-5.7.0-268.1.x86_64 libQt5X11Extras5-debuginfo-5.7.0-82.1.x86_64 libQt5Xml5-debuginfo-5.7.0-268.1.x86_64 libQtQuick5-debuginfo-5.7.0-123.1.x86_64 libSM6-debuginfo-1.2.2-5.1.x86_64 libX11-6-debuginfo-1.6.3-3.1.x86_64 libX11-xcb1-debuginfo-1.6.3-3.1.x86_64 libXau6-debuginfo-1.0.8-6.1.x86_64 libXcomposite1-debuginfo-0.4.4-10.1.x86_64 libXcursor1-debuginfo-1.1.14-6.1.x86_64 libXdamage1-debuginfo-1.1.4-9.1.x86_64 libXext6-debuginfo-1.3.3-3.1.x86_64 libXfixes3-debuginfo-5.0.1-5.1.x86_64 libXi6-debuginfo-1.7.5-1.1.x86_64 libXrender1-debuginfo-0.9.9-1.1.x86_64 libXxf86vm1-debuginfo-1.1.4-1.1.x86_64 libacl1-debuginfo-2.2.52-8.1.x86_64 libattr1-debuginfo-2.4.47-5.4.x86_64 libbz2-1-debuginfo-1.0.6-32.1.x86_64 libdbus-1-3-debuginfo-1.8.16-7.1.x86_64 libdbusmenu-qt5-2-debuginfo-0.9.3+15.10.20150604-27.8.x86_64 libdouble-conversion1-debuginfo-2.0.1-5.2.x86_64 libdrm2-debuginfo-2.4.65-1.1.x86_64 libdrm_amdgpu1-debuginfo-2.4.65-1.1.x86_64 libdrm_nouveau2-debuginfo-2.4.65-1.1.x86_64 libdrm_radeon1-debuginfo-2.4.65-1.1.x86_64 libelf1-debuginfo-0.158-9.5.x86_64 libexpat1-debuginfo-2.1.0-17.1.x86_64 libffi4-debuginfo-5.3.1+r233831-6.1.x86_64 libfreetype6-debuginfo-2.5.5-8.2.x86_64 libgcc_s1-debuginfo-5.3.1+r233831-6.1.x86_64 libgcrypt20-debuginfo-1.6.1-32.1.x86_64 libglib-2_0-0-debuginfo-2.44.1-2.3.x86_64 libgmodule-2_0-0-debuginfo-2.44.1-2.3.x86_64 libgobject-2_0-0-debuginfo-2.44.1-2.3.x86_64 libgpg-error0-debuginfo-1.13-3.6.x86_64 libgraphite2-3-debuginfo-1.3.1-3.1.x86_64 libgstapp-1_0-0-debuginfo-1.8.3-74.1.x86_64 libgstaudio-1_0-0-debuginfo-1.8.3-74.1.x86_64 libgstpbutils-1_0-0-debuginfo-1.8.3-74.1.x86_64 libgstreamer-1_0-0-debuginfo-1.8.3-77.2.x86_64 libgsttag-1_0-0-debuginfo-1.8.3-74.1.x86_64 libgstvideo-1_0-0-debuginfo-1.8.3-74.1.x86_64 libharfbuzz0-debuginfo-1.0.3-4.1.x86_64 libicu52_1-debuginfo-52.1-10.3.x86_64 libjasper1-debuginfo-1.900.1-164.1.x86_64 libjbig2-debuginfo-2.0-3.2.x86_64 libjpeg8-debuginfo-8.0.2-31.3.x86_64 libjson-c2-debuginfo-0.12-4.2.x86_64 libkdecore4-debuginfo-4.14.24-36.18.x86_64 liblcms1-debuginfo-1.19-19.1.x86_64 liblzma5-debuginfo-5.0.5-3.5.x86_64 libmng1-debuginfo-1.0.10-3.2.x86_64 libmodman1-debuginfo-2.0.1-17.1.x86_64 libncurses5-debuginfo-5.9-53.4.x86_64 libogg0-debuginfo-1.3.0-3.2.x86_64 libopenssl1_0_0-debuginfo-1.0.1i-18.1.x86_64 liborc-0_4-0-debuginfo-0.4.24-6.1.x86_64 libphonon4qt5-debuginfo-4.9.0-5.2.x86_64 libpng16-16-debuginfo-1.6.8-7.1.x86_64 libproxy1-config-kde4-debuginfo-0.4.11-13.2.x86_64 libproxy1-debuginfo-0.4.11-13.2.x86_64 libpulse-mainloop-glib0-debuginfo-7.0-5.1.x86_64 libpulse0-debuginfo-7.0-5.1.x86_64 libqt4-debuginfo-4.8.6-13.1.x86_64 libqt5-qtimageformats-debuginfo-5.7.0-68.1.x86_64 libsndfile1-debuginfo-1.0.25-24.1.x86_64 libspeex1-debuginfo-1.2~rc2-1.1.x86_64 libsqlite3-0-debuginfo-3.8.10.2-7.1.x86_64 libstdc++6-debuginfo-5.3.1+r233831-6.1.x86_64 libtiff5-debuginfo-4.0.6-6.1.x86_64 libtxc_dxtn-debuginfo-1.0.1-4.1.x86_64 libudev1-debuginfo-210-95.1.x86_64 libuuid1-debuginfo-2.25-15.2.x86_64 libvorbis0-debuginfo-1.3.3-3.7.x86_64 libvorbisenc2-debuginfo-1.3.3-3.7.x86_64 libwayland-client0-debuginfo-1.12.0-2.1.x86_64 libwebp5-debuginfo-0.4.3-7.1.x86_64 libwebpdemux1-debuginfo-0.4.3-7.1.x86_64 libxcb-dri2-0-debuginfo-1.11.1-1.1.x86_64 libxcb-dri3-0-debuginfo-1.11.1-1.1.x86_64 libxcb-glx0-debuginfo-1.11.1-1.1.x86_64 libxcb-icccm4-debuginfo-0.4.1-3.1.x86_64 libxcb-image0-debuginfo-0.4.0-1.1.x86_64 libxcb-keysyms1-debuginfo-0.4.0-1.1.x86_64 libxcb-present0-debuginfo-1.11.1-1.1.x86_64 libxcb-randr0-debuginfo-1.11.1-1.1.x86_64 libxcb-render-util0-debuginfo-0.3.9-3.1.x86_64 libxcb-render0-debuginfo-1.11.1-1.1.x86_64 libxcb-shape0-debuginfo-1.11.1-1.1.x86_64 libxcb-shm0-debuginfo-1.11.1-1.1.x86_64 libxcb-sync1-debuginfo-1.11.1-1.1.x86_64 libxcb-util1-debuginfo-0.4.0-1.1.x86_64 libxcb-xfixes0-debuginfo-1.11.1-1.1.x86_64 libxcb-xinerama0-debuginfo-1.11.1-1.1.x86_64 libxcb-xkb1-debuginfo-1.11.1-1.1.x86_64 libxcb1-debuginfo-1.11.1-1.1.x86_64 libxkbcommon-x11-0-debuginfo-0.5.0-5.2.x86_64 libxkbcommon0-debuginfo-0.5.0-5.2.x86_64 libxml2-2-debuginfo-2.9.1-19.1.x86_64 libxshmfence1-debuginfo-1.2-5.3.x86_64 libxslt1-debuginfo-1.1.28-8.1.x86_64 libz1-debuginfo-1.2.8-6.4.x86_64 plasma5-integration-plugin-debuginfo-5.7.95-25.1.x86_64 systemd-debuginfo-210-95.1.x86_64
> (gdb) thread apply all bt
