### ISSUE TITLE
Can't install client in fedora 24

### ISSUE THREAD

**Issue by jbtrystram** [owncloud/client#5219]
### Expected behaviour
Installation works fine

### Actual behaviour
installation fail : 
```
The public key for libqt5keychain1-0.7.0-9.1.x86_64.rpm is not insatlled.
Failing package is: libqt5keychain1-0.7.0-9.1.x86_64
 GPG Keys are configured as: http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Fedora_24//repodata/repomd.xml.key
```

### Steps to reproduce
1. dnf config-manager --add-repo http://download.opensuse.org/repositories/isv:ownCloud:desktop/Fedora_24/isv:ownCloud:desktop.repo
2. dnf install owncloud-client
### Client configuration
Client version:

Operating system: Fedora 24 (4.7.4-200.fc24.x86_64)

OS language: French

**Comment by scolebrook** [comment]
I was able to install it by using a browser to go to the repository and find the url to that specific rpm. I then did `sudo yum install http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Fedora_24/x86_64/libqt5keychain1-0.7.0-9.1.x86_64.rpm` (haven't learned dnf yet) and that package installed successfully. I could then redo the `sudo dnf install owncloud-client` command and that completed successfully.

Not a solution to the root problem, but a viable workaround to get you going. You'll also want to install the topicons gnome extension to see the owncloud icon.
https://extensions.gnome.org/extension/495/topicons/

**Comment by jbtrystram** [comment]
@scolebrook Thanks !! It worked :)

**Comment by xZise** [comment]
Hello it seems that I have a similar problem on Fedora 24. I added the repo and it is able to verify all packages  except the `libqt5keychain1`.

It seems like that package is actually using a different key than the other three:
```
$ rpm -K /var/cache/dnf/isv_ownCloud_desktop-a05a87a841c5edec/packages/*
/var/cache/dnf/isv_ownCloud_desktop-a05a87a841c5edec/packages/libowncloudsync0-2.2.4-1.1.x86_64.rpm: rsa sha1 (md5) pgp md5 OK
/var/cache/dnf/isv_ownCloud_desktop-a05a87a841c5edec/packages/libqt5keychain1-0.7.0-9.1.x86_64.rpm: ((SHA1) DSA) sha1 md5 (GPG) NOT OK (MISSING KEYS: (SHA1) DSA#ba684223 GPG#ba684223) 
/var/cache/dnf/isv_ownCloud_desktop-a05a87a841c5edec/packages/owncloud-client-2.2.4-1.1.x86_64.rpm: rsa sha1 (md5) pgp md5 OK
/var/cache/dnf/isv_ownCloud_desktop-a05a87a841c5edec/packages/owncloud-client-l10n-2.2.4-1.1.x86_64.rpm: rsa sha1 (md5) pgp md5 OK
```

But when I run the installation it warns me that the package uses key `ba684223` and that hasn't been found. So it suggests to you to actually install the key, but that is using different ID (`0x557BEFF9`), which is actually installed (and required by the other three packages):
```
warning: /var/cache/dnf/isv_ownCloud_desktop-a05a87a841c5edec/packages/libqt5keychain1-0.7.0-9.1.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID ba684223: NOKEY
Importing GPG key 0x557BEFF9:
 Userid     : "isv:ownCloud OBS Project <isv:ownCloud@build.opensuse.org>"
 Fingerprint: 1B07 204C D71B 690D 409F 57D2 4ABE 1AC7 557B EFF9
 From       : http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Fedora_24//repodata/repomd.xml.key
Is this ok [y/N]: 
```

These are the keys which are used to sign the different packages:
```
$ rpm -q --qf '%{NAME} %{SIGPGP:pgpsig}\n' -p /var/cache/dnf/isv_ownCloud_desktop-a05a87a841c5edec/packages/*
libowncloudsync0 RSA/SHA256, Tue 27 Sep 2016 11:36:32 CEST, Key ID 4abe1ac7557beff9
warning: /var/cache/dnf/isv_ownCloud_desktop-a05a87a841c5edec/packages/libqt5keychain1-0.7.0-9.1.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID ba684223: NOKEY
libqt5keychain1 (none)
owncloud-client RSA/SHA256, Tue 27 Sep 2016 11:36:33 CEST, Key ID 4abe1ac7557beff9
owncloud-client-l10n RSA/SHA256, Tue 27 Sep 2016 11:36:33 CEST, Key ID 4abe1ac7557beff9
$ rpm -qpi /var/cache/dnf/isv_ownCloud_desktop-a05a87a841c5edec/packages/libqt5keychain1-0.7.0-9.1.x86_64.rpm | grep Signature
warning: /var/cache/dnf/isv_ownCloud_desktop-a05a87a841c5edec/packages/libqt5keychain1-0.7.0-9.1.x86_64.rpm: Header V3 DSA/SHA1 Signature, key ID ba684223: NOKEY
Signature   : DSA/SHA1, Wed 14 Sep 2016 20:23:03 CEST, Key ID 977c43a8ba684223
```

**Comment by crrodriguez** [comment]
Fixed together with https://github.com/owncloud/enterprise/issues/1617
