### ISSUE TITLE
[Win7][Fedora 24][2.2.4] 0 octets displayed

### ISSUE THREAD

**Issue by glannes31** [owncloud/client#5220]
https://github.com/owncloud/client/issues/5026

### Expected behaviour
Size appearing on the three in client

### Actual behaviour
0 octets is displaying  ( File size 7 Mb in directory)

### Server configuration
Operating system:Linux

Web server: Apache

Database:MariaDB

ownCloud version:ownCloud 9.2.0 pre alpha

Storage backend (external storage):

### Client configuration
Client version:2.2.3 and 2.2.4

Operating system: Windows 7 / Fedora 24 

OS language: French

Installation path of client:C:\Program Files (x86)\ownCloud

![issue](https://cloud.githubusercontent.com/assets/20032648/18994805/c5cdfc9a-8729-11e6-8abd-e5977d74c30a.JPG)

**Comment by glannes31** [comment]
@danimo @mcastroSG

**Comment by guruz** [comment]
Is ```Test``` a shared directory?
External server storage?

**Comment by glannes31** [comment]
Test is a normal directory

Envoyé depuis Yahoo Mail pour Android 
 
  Le sam. j oct. PM à 18:33, Markus Goetz<notifications@github.com> a écrit :   
Is Test a shared directory?
External server storage?

**Comment by guruz** [comment]
FYI @PVince81

**Comment by PVince81** [comment]
@glannes31 does the web UI also show 0 bytes for that folder ? Because that should be the same value that the client is using.

> ownCloud 9.2.0 pre alpha
Would be good to know the build version or commit id.

**Comment by glannes31** [comment]
Hello,

It's Okay now . I have the good size displayed. Tks  for your time  !

**Comment by bseclier** [comment]
What did you do to resolve this bug @glannes31 ?
Regards

**Comment by glannes31** [comment]
Because with a 7 mo folder. The client display 7 Mo.

Envoyé depuis Yahoo Mail pour Android 
 
  Le mer. j oct. AM à 11:59, Benjamin SECLIER<notifications@github.com> a écrit :   
What did you do to resolve this bug @glannes31 ?
Regards

**Comment by bseclier** [comment]
Yes, but 18 days ago "0 octets" was displayed, did you do something to make "7 Mo" appears ?

**Comment by glannes31** [comment]
No, i juste put a 7 Mb file in a folder .
 Très cordialement, Guillaume Lannes-Lacrouts 

    Le Mercredi 19 octobre 2016 12h13, Benjamin SECLIER <notifications@github.com> a écrit :
 

 Yes, but 18 days ago "0 octets" was displayed, did you do something to make "7 Mo" appears ?—
