### ISSUE TITLE
Files not synced (download) not listed.

### ISSUE THREAD

**Issue by dergilb99** [owncloud/client#5221]
If there is an error when downloading files, there should be information in Activity: "Not Synced" about that. More than just a few seconds. Files were not downloaded, but the cloud check mark in the tray was green. The files not being synced (Download could not be completed) are only displayed for a short amount of time. Then the list is cleared.

### Expected behaviour
Files not being downloaded for whatever reason are listed in "Not Synced".

The check mark in the tray symbol should not be green!

### Actual behaviour
The files not being downloaded because of an error just pop up there sometimes (rescan?) for a short amount of time. Then the list is being cleared. The files not being sync because they are on the ignore list are constantly there.

The check mark in the tray symbol is green.

### Steps to reproduce
Having files not downloading properly. In my case, that's having ownCloud 9.

### Server configuration
**Operating system**:
Solaris Unix (Hosted by Strato)

**Web server:**
Apache 2.2

**Database:**
MySQL 5.6.31

**PHP version:**
5.6.262.0

**ownCloud version:** (see ownCloud admin page)
9.1.1

Storage backend (external storage):
No.

### Client configuration
Client version:
2.2.3 (build 6407)

Operating system:
Windows 10 Pro (64 bit)

OS language:
English (US)

Installation path of client:
C:\Program Files (x86)\ownCloud

**Comment by ckamm** [comment]
This sounds suspiciously like #5190 #5242. @dergilb99 This should already be fixed for the next release, could you test with a nightly build here http://download.owncloud.com/desktop/daily/ ?

**Comment by davitol** [comment]
:+1: Tested with a 2.3.0 nightly build and WFM
