### ISSUE TITLE
Option to share image without embeded web page, i.e. share original

### ISSUE THREAD

**Issue by rahlquist** [owncloud/client#5222]
Please, consider a check box on the ownCloud Sharing screen to share "Original Image" that would instead of providing a page embedded image would provide a link directly to the original photo.  

Reason: When sharing large screen shots to someone with a smaller screen, the preview image used by own cloud can be restrictive, especially for the visually impaired.

**Comment by ktiedt** [comment]
Even for the non visually impaired, the default preview image is often unusable due to its small size.

**Comment by RealRancor** [comment]
Thats an question / topic for ownCloud and not the client which was thoroughly discussed here: https://github.com/owncloud/core/issues/16470 and mostly denied for security reasons: https://github.com/owncloud/core/issues/16470#issuecomment-155356185

**Comment by ckamm** [comment]
Looks like an owncloud/core issue that was discussed elsewhere.
