### ISSUE TITLE
[Windows] Issues with bitlocker drive

### ISSUE THREAD

**Issue by Schaussi** [owncloud/client#5223]
If you have your local ownCloud directory on a bitlocker drive, ownCloud does not recognize the local folder if has been already running before you entered your Bitlocker password in Windows.
Example:
1. Windows Partition "D:\" is encrypted with Bitlocker. Local ownCloud sync files are store on that drive.  
2. Windows Login, ownCloud client is starting
3. Client shows an error because it cannot access D:\, which is OK at that moment.
4. After e.g. 5 minutes, I need files from D:\, so I enter Bitlocker password and the drive can be accessed.
5. Sometimes ownCloud realizes after some seconds it can now access its folders, but most of the time the client has to be restarted.

**Comment by guruz** [comment]
How does it show the error? Do you have a screenshot?

Why do you need to restart it if it realizes it has access now?

Does syncing down a file from the server work (file changed on server)?

Are locally changed files recognized and synced up?

**Comment by Schaussi** [comment]
I could isolate the issue a bit. After unlocking the Bitlocker drive, Owncloud does not sync until I create or modify a local file.

After Windows login:
![oc1](https://cloud.githubusercontent.com/assets/4758559/19192054/20ddcefa-8ca5-11e6-8c38-27a8a038ddbb.PNG)

Bitlocker drive:
![oc2](https://cloud.githubusercontent.com/assets/4758559/19192074/34efd5a0-8ca5-11e6-8636-aaa70e6969c1.PNG)

After creating or modifying a file:
![oc3](https://cloud.githubusercontent.com/assets/4758559/19192080/3c584e1c-8ca5-11e6-8d41-b2d6c3cd769d.PNG)

**Comment by ignacioinnovo** [comment]
Hi Schaussi!

Let me ask you if you close session before shuting down the computer, because if not the user can specify another folder to owncloud download complete data again, outside your encrypted bitlocker container.

Thank you in advanced!

**Comment by Schaussi** [comment]
Hi,
I do not close ownCloud manually before shutting down, but I do not think this affects my issue.
At the moment, I use this as a workaround:
If ownCloud stays disconnected after unlocking the bitlocker partition, I start creating a new file link via Windows Explorer context menu, then cancel the dialog. Afterwards, ownCloud starts to sync.

**Comment by guruz** [comment]
FYI 2.3 is out https://owncloud.org/changelog/desktop/

**Comment by ignacioinnovo** [comment]
Thank you very much!

 

Best regards,

Ignacio.

 

De: Markus Goetz [mailto:notifications@github.com] 
Enviado el: viernes, 3 de marzo de 2017 12:13 p. m.
Para: owncloud/client <client@noreply.github.com>
CC: Ignacio - Innovo <ignacioelfi@gmail.com>; Comment <comment@noreply.github.com>
Asunto: Re: [owncloud/client] [Windows] Issues with bitlocker drive (#5223)

 

FYI 2.3 is out https://owncloud.org/changelog/desktop/

**Comment by SamuAlfageme** [comment]
Most likely fixed by https://github.com/owncloud/client/issues/5317, will test and report back.

**Comment by SamuAlfageme** [comment]
Just checked the behavior with bitlocker w/ Win7 and now it includes the drive back transparently after some seconds. 🎉
