### ISSUE TITLE
Rename a folder downloads entire content again

### ISSUE THREAD

**Issue by daorte** [owncloud/client#5224]
### Expected behaviour

When renaming a folder, it should remember the sync configuration of its subfolders and not download everything again.
### Steps to reproduce
1. Create a folder 'ParentFolder'
2. Create two subfolders of 'ParentFolder', 'SubFolderOne' and 'SubFolderTwo'
3. Put any content on both subfolders
4. Sync with the desktop application
5. At this point, in the Desktop Application main screen, you should have 'ParentFolder' and all its subfolders with marked sync checks
6. Uncheck 'SubFolderTwo'
7. The Desktop Application deletes the folder from your local disk
8. Go to OC Web, login with your account and rename 'ParentFolder' to 'ParentFolderRenamed'
9. The Desktop Application renames 'ParentFolder' to 'ParentFolderRenamed' and download again 'SubFolderTwo'
### Server configuration

Operating system: Ubuntu 16.04
Web server: Apache 2.4
Database: MySQL
PHP version: 7
ownCloud version: 9.1.1
Storage backend (external storage): NO
### Client configuration

Client version: 2.2.3
Operating system: Windows 8.1
OS language: Spanish
Installation path of client: C:\Program Files (x86)\ownCloud

**Comment by ogoffart** [comment]
Right,  the entries in the selective sync black list are not renamed.  This is actually a bug.

**Comment by daorte** [comment]
Tested on Windows Client Version 2.2.4 (build 6408)

does not work...

**Comment by SamuAlfageme** [comment]
Not happening anymore. Tested on [Windows Client Version 2.3.0 (build 6501)](http://download.owncloud.com/desktop/daily/ownCloud-2.3.0.6501-nightly20161110-setup.exe) 
![img](http://i.imgur.com/wFzBRWl.gif)

**Comment by SamuAlfageme** [comment]
👍
