### ISSUE TITLE
ownCloud desktop client from nightly repository not installable on Debian Testing i686 because of  missing installation candidate for libssl1.0.0

### ISSUE THREAD

**Issue by thackert** [owncloud/client#5225]
Hello @ll,

### Expected behaviour

The desktop client should be installable with a newer libssl version than libssl1.0.0.

### Actual behaviour
while trying to find a solution for #5055, I added the nightly repository to my /etc/apt/sources.list. But running "apt-get install owncloud-client" spits out
<quote>
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud-client : Depends: libowncloudsync0 (= 2.2.4~nightly2016927-1.1) but 2.2.2+dfsg-1 is to be installed
                   Depends: libssl1.0.0 (>= 1.0.0) but it is not installable
E: Unable to correct problems, you have held broken packages.
</quote>

A short search reveals, that there is no libssl1.0.0 for Debian Testing. On my 64bit system however (which was first installed last year or so, whereas my 32bit system is a fresh install of Debian) I have it installed.

### Steps to reproduce
1.  Add the nightly repository to /etc/apt/sources.list
2.  download the key for it and add it via "apt-key add..."
3.  try to install the desktop client via "apt-get install owncloud-client"

### Client configuration
Client version: 2.2.2+dfsg-1 

Operating system: Debian Testing i686

OS language: de_DE

Installation path of client: /usr/bin/owncloud

Sorry for the inconvenience
Thomas.

**Comment by RealRancor** [comment]
I think that is expected as only Debian 7.0 and 8.0 packages are provided and supported by the OpenSUSE build service (see https://en.opensuse.org/openSUSE:Build_Service_supported_build_targets and https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client)

**Comment by crrodriguez** [comment]
There is no support for debian testing in the openSUSE buildservice atm. packages work only in debian 7.0 and 8.0.. you could get an old openssl release installed but that may break something else. 
Sorry, we can't help you further atm, if the OBS adds working debian testing targets then we will, until then please use a supported OS.

**Comment by jnweiger** [comment]
Our friends at openSUSE did some magic, and now we were able to add a Debian_Next_ga build target to the owncloud-client downloads at https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adesktop&package=owncloud-client

@thackert can you please check, if that works?

**Comment by RealRancor** [comment]
@jnweiger Nice. Just tested that and works here. Installing of owncloud-client on Debian testing is working without installing libssl-1.0.0 from jessie-backports.

For my installed owncloud-client from Debian 8.0 i had to "downgrade"  from 2.2.4-1.3 to 2.2.4-1.1

**Comment by jnweiger** [comment]
@RealRancor Thanks for the positive feedback!
The reset build release number suffix of -1.1 is a well known nuisance, but cannot be avoided at openSUSE OBS.

**Comment by RealRancor** [comment]
> The reset build release number suffix of -1.1 is a well known nuisance, but cannot be avoided at openSUSE OBS.

Absolutely no problem. Just wanted to note this as you won't get the package with the updated dependency if you had the Debian 8 package installed and don't downgrade to the mentioned new package. :-)
