### ISSUE TITLE
Mac OS ownCloud Client CSync unknown error

### ISSUE THREAD

**Issue by zisuu** [owncloud/client#5226]
### Expected behaviour

ownCloud Client should sync & update local and server files
### Actual behaviour

ownCloud Client does not sync & update local and server files, stops with error message: "CSync unknown error"
### Steps to reproduce
1. start ownCloud Client on Mac with the specific user, it only happens with this account.
### Server configuration

Operating system: Debian 8

Web server: Nginx 1.10

Database: mariadb 10.1.18

PHP version: PHP 5.6.24-0+deb8u1

ownCloud version: 9.0.5

Storage backend (external storage): NFS Server
### Client configuration

Client version: 2.2.4

Operating system: Mac OS X El Capitan (Version 10.11.6)

OS language: German

Installation path of client:/ Applications/owncloud.app
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   (On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
   (See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

https://gist.github.com/zisuu/46ccb2e2e17c19b84bdff1c999670b40#file-clientlogfile-txt
1. Web server error log:
   no errors in Web server log
2. Server logfile: ownCloud log (data/owncloud.log):

https://gist.github.com/zisuu/f544d9897c8244388cdce7ea39daa994#file-owncloud-log

![csyncerror](https://cloud.githubusercontent.com/assets/11134301/19114625/11b4f184-8b0f-11e6-8f0d-8f5e01463dd6.png)

**Comment by guruz** [comment]
Hm. That's really minimal.
```
32d2b5f0 OCC::SyncEngine::startSync: =====sync with existing DB
10-05 13:50:21:183 0x7f9d32d2b5f0 OCC::SyncEngine::startSync: =====Using Qt 5.4.0
10-05 13:50:21:183 0x7f9d32d2b5f0 OCC::SyncEngine::startSync: =====Using SSL library version OpenSSL 1.0.2h  3 May 2016
10-05 13:50:21:184 0x7f9d32d2b5f0 OCC::SyncEngine::startSync: void OCC::SyncEngine::startSync() ====NOT Using Selective Sync
10-05 13:50:21:184 0x7f9d32d2b5f0 OCC::SyncEngine::startSync: #### Discovery start #################################################### >>
10-05 13:50:21:184 0x7f9d32d2b5f0 OCC::SyncEngine::startSync: =====Server "9.0.5.2" "rootEtagChangesNotOnlySubFolderEtags=1"
10-05 13:50:21:185 0x7f9d32d2b5f0 OCC::SyncEngine::startSync: void OCC::SyncEngine::startSync() "/"  QUrl( "https://primavista.unicocloud.ch/remote.php/webdav/" ) 
10-05 13:50:21:259 0x7f9d32d2b5f0 OCC::SparkleUpdater::backgroundCheckForUpdate: virtual void OCC::SparkleUpdater::backgroundCheckForUpdate() launching background check
10-05 13:50:21:282 0x7f9d32d2b5f0 -[DelegateObject updaterMayCheckForUpdates:]: -[DelegateObject updaterMayCheckForUpdates:] may check: YES
10-05 13:50:21:360 0x7f9d32d2b5f0 OCC::SyncEngine::handleSyncError:  #### ERROR during  csync_update :  "CSync unbekannter Fehler."
10-05 13:50:21:361 0x7f9d32d2b5f0 OCC::SyncJournalDb::close: void OCC::SyncJournalDb::close() "/Users/alinezuercher/ownCloud/.csync_journal.db"
10-05 13:50:21:361 0x7f9d32d2b5f0 OCC::SyncJournalDb::commitTransaction: No database Transaction to commit
10-05 13:50:21:362 0x7f9d32d2b5f0 OCC::SyncEngine::finalize: CSync run took  178
10-05 13:50:21:363 0x7f9d32d2b5f0 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:OK:/Users/alinezuercher/ownCloud/"
10-05 13:50:21:364 0x7f9d32d2b5f0 OCC::Folder::slotSyncFinished:  - client version 2.2.4 (build 3709)  Qt 5.4.0  SSL  OpenSSL 1.0.2h  3 May 2016
10-05 13:50:21:365 0x7f9d32d2b5f0 OCC::Folder::slotSyncFinished: -> SyncEngine finished with ERROR, warn count is 0
10-05 13:50:21:365 0x7f9d32d2b5f0 OCC::Folder::bubbleUpSyncResult: Processing result list and logging took  0  Milliseconds.
10-05 13:50:21:366 0x7f9d32d2b5f0 OCC::Folder::bubbleUpSyncResult: OO folder slotSyncFinished: result:  2
10-05 13:50:21:366 0x7f9d32d2b5f0 OCC::Folder::slotSyncFinished:   ** error Strings:  ("CSync unbekannter Fehler.")
10-05 13:50:21:367 0x7f9d32d2b5f0 OCC::Folder::slotSyncFinished:     * owncloud csync thread finished with error
10-05 13:50:21:367 0x7f9d32d2b5f0 OCC::Folder::slotSyncFinished: the last 1 syncs failed
```

However somewhere before I see:
```
10-05 13:50:19:057 0x7f9d32d2b5f0 OCC::SyncJournalDb::getFileRecord: No journal entry found for  "3.prima-vista_Back Office" Error:  "database disk image is malformed"
```

Can you quit the client, delete the ```.csync_journal.db``` file in your sync directory and then try again?

**Comment by zisuu** [comment]
Hi guruz

Thank you for your investigation. Yes, when i delete the .csync_journal.db file it starts to sync again and the error disappears for a week or more, then this Problem occurs again. Is this may because there is a huge stress on the client? There are five shares this users provides to 20 other ownCloud users and all of them are working inside this shares at the same time.

**Comment by guruz** [comment]
Are you willing to try this nightly build?
http://dl-oc.owncloud.com/desktop/daily/ownCloud-2.3.0.3746-nightly20161011.pkg

It has an updated sqlite version and better error handling in our SQL code. Maybe it shows a better error message?

**Comment by zisuu** [comment]
Thanks guruz. I installed this nightly build. I will let you know, if the .csync_journal.db becomes malformed again.

**Comment by ckamm** [comment]
@zisuu Did you see the problem again so far?

**Comment by zisuu** [comment]
@ckamm The error did not occur again so far. If I would let you know it again on this issue page. Thanks
