### ISSUE TITLE
Network access is disabled error

### ISSUE THREAD

**Issue by Dassadar** [owncloud/client#5232]
### Expected behaviour
ownCloud automatically connecting

### Actual behaviour
No connection to ownCloud on https://framadrive.org. Network access is disabled.
=> see capture: 
![capture du 2016-10-08 22-48-07](https://cloud.githubusercontent.com/assets/11810481/19215868/fa58c982-8da9-11e6-90f5-fef5e7ce81d5.png)

### Steps to reproduce
ownCloud client is launched at Linux startup. I didn't touch it - it remains unconnected.

### Server configuration
https://framadrive.org (I cannot tell more, but there is no problem when connecting to my drive on the web)

### Client configuration
Client version: Version 2.1.1+dfsg-1ubuntu1.1

Operating system: Linux Mint

OS language: french
 
Installation path of client: ?

**Comment by guruz** [comment]
> Client version: Version 2.1.1+dfsg-1ubuntu1.1

Please download 2.2.4 from https://owncloud.org/install/
