### ISSUE TITLE
Client Synchronizes Great folders and then delete and resynchronize alone

### ISSUE THREAD

**Issue by alviegas** [owncloud/client#5236]
### Expected behaviour

After synchronization of files the client should not delete them without user operation files.
### Actual behaviour

We have 08 folders containing a total of 4 GB of used space. We share this folder for about 04 users. Synchronize with the client OwnClound Desktop 2.2.4.
You synchronize all folders, but at a certain time the client deletes all folders and performs the synchronization again.
### Steps to reproduce
1. Installed Client Desktop OwnCloud 2.2.4.
2. Configuring access to the server
3. The problem occurs intermittently. Especially with large folders.
### Server configuration

Operating system: Ubuntu 16.04.1 LTS

Web server: apache2 2.4.18-2ubuntu3.1

Database: mysqld  Ver 5.5.49-0ubuntu0.14.04.1 for debian-linux-gnu on x86_64 ((Ubuntu))

PHP version: PHP 7.0.8-0ubuntu0.16.04.3 (cli) ( NTS )

ownCloud version: ownCloud 9.1.1 (stable)

Storage backend (external storage): nfs-common 1:1.2.8-9ubuntu12. cat /etc/fstab [X.Y.Z.W:/dados /nfsDataOwncloud nfs  proto=tcp,nfsvers=3,noexec 0  0]
### Client configuration

Client version: 2.2.4

Operating system: Ubuntu 16.04.1 LTS

OS language: Portuguese

Installation path of client: Default
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   (On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
   (See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

10-10 15:14:50:592 2413 OCC::SyncJournalDb::checkConnect: sqlite3 version "3.11.0"
10-10 15:14:50:592 2413 OCC::SyncJournalDb::checkConnect: sqlite3 journal_mode= "wal"
10-10 15:14:50:593 2413 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect" and starting new transaction
10-10 15:14:50:593 2413 OCC::SyncJournalDb::tableColumns: Columns in the current journal:  ("phash", "pathlen", "path", "inode", "uid", "gid", "mode", "modtime", "type", "md5", "fileid", "remotePerm", "filesize", "ignoredChildrenRemote", "contentChecksum", "contentChecksumTypeId")
10-10 15:14:50:594 2413 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add inode index" and starting new transaction
10-10 15:14:50:594 2413 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add path index" and starting new transaction
10-10 15:14:50:595 2413 OCC::SyncJournalDb::tableColumns: Columns in the current journal:  ("path", "lastTryEtag", "lastTryModtime", "retrycount", "errorstring", "lastTryTime", "ignoreDuration", "renameTarget")
10-10 15:14:50:596 2413 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect End" 
10-10 15:14:50:597 2413 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "https://server.owncloud/remote.php/webdav/" :  "Success"
10-10 15:14:50:798 2413 OCC::FolderMan::slotFolderSyncFinished: <===================================== sync finished for  "https://server.owncloud
1. Web server error log:

192.168.112.18 - alberto [10/Oct/2016:10:09:54 -0300] "GET /remote.php/webdav/Shared/3%20-%20TI%20e%20Administra%C3%A7%C3%A3o/1%20-%20TI/B%20-%20Arquitetura%20Corporativa/1%20-%20TOGAF/6%20-%20Study%20Materials/N112.PDF HTTP/1.1" 200 1970564 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
192.168.112.18 - alberto [10/Oct/2016:10:09:56 -0300] "GET /remote.php/webdav/Shared/3%20-%20TI%20e%20Administra%C3%A7%C3%A3o/1%20-%20TI/B%20-%20Arquitetura%20Corporativa/1%20-%20TOGAF/6%20-%20Study%20Materials/TOGAF-V91-F13-Certification.pdf HTTP/1.1" 200 525331 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
192.168.112.18 - alberto [10/Oct/2016:10:09:56 -0300] "GET /remote.php/webdav/Shared/3%20-%20TI%20e%20Administra%C3%A7%C3%A3o/1%20-%20TI/B%20-%20Arquitetura%20Corporativa/1%20-%20TOGAF/6%20-%20Study%20Materials/TOGAF-V91-M0-Course-Intro.pdf HTTP/1.1" 200 630633 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
192.168.112.18 - alberto [10/Oct/2016:10:09:54 -0300] "GET /remote.php/webdav/Shared/3%20-%20TI%20e%20Administra%C3%A7%C3%A3o/1%20-%20TI/B%20-%20Arquitetura%20Corporativa/1%20-%20TOGAF/6%20-%20Study%20Materials/TOGAF-V91-B1-Intro-to-TOGAF9.pdf HTTP/1.1" 200 8847277 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
192.168.112.18 - alberto [10/Oct/2016:10:09:57 -0300] "GET /remote.php/webdav/Shared/3%20-%20TI%20e%20Administra%C3%A7%C3%A3o/1%20-%20TI/B%20-%20Arquitetura%20Corporativa/1%20-%20TOGAF/6%20-%20Study%20Materials/TOGAF-V91-M3-Intro-ADM.pdf HTTP/1.1" 200 1301914 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
192.168.112.18 - alberto [10/Oct/2016:10:09:56 -0300] "GET /remote.php/webdav/Shared/3%20-%20TI%20e%20Administra%C3%A7%C3%A3o/1%20-%20TI/B%20-%20Arquitetura%20Corporativa/1%20-%20TOGAF/6%20-%20Study%20Materials/TOGAF-V91-M1-Management-Overview.pdf HTTP/1.1" 200 6838681 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
192.168.112.18 - alberto [10/Oct/2016:10:09:59 -0300] "GET /remote.php/webdav/Shared/3%20-%20TI%20e%20Administra%C3%A7%C3%A3o/1%20-%20TI/B%20-%20Arquitetura%20Corporativa/1%20-%20TOGAF/6%20-%20Study%20Materials/U098.PDF HTTP/1.1" 200 10511 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
192.168.112.18 - alberto [10/Oct/2016:10:09:59 -0300] "GET /remote.php/webdav/Shared/3%20-%20TI%20e%20Administra%C3%A7%C3%A3o/1%20-%20TI/B%20-%20Arquitetura%20Corporativa/1%20-%20TOGAF/6%20-%20Study%20Materials/W160.PDF HTTP/1.1" 200 3283973 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
192.168.112.18 - alberto [10/Oct/2016:10:09:56 -0300] "GET /remote.php/webdav/Shared/3%20-%20TI%20e%20Administra%C3%A7%C3%A3o/1%20-%20TI/B%20-%20Arquitetura%20Corporativa/1%20-%20TOGAF/6%20-%20Study%20Materials/TOGAF-V91-M2-TOGAF9-Components.pdf HTTP/1.1" 200 12000877 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
192.168.112.18 - alberto [10/Oct/2016:10:09:59 -0300] "GET /remote.php/webdav/Shared/3%20-%20TI%20e%20Administra%C3%A7%C3%A3o/1%20-%20TI/B%20-%20Arquitetura%20Corporativa/1%20-%20TOGAF/6%20-%20Study%20Materials/TOGAF-V91-M7-Metamodel.pdf HTTP/1.1" 200 11059959 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
1. Server logfile: ownCloud log (data/owncloud.log):
   Oct 10 10:09:03 LNXCLOUDWEB ownCloud[53114]: {PHP} InvalidArgumentException: Jail rootPath is null at /var/www/owncloud/lib/private/Files/Storage/Wrapper/Jail.php#55
   Oct 10 10:09:10 LNXCLOUDWEB ownCloud[52761]: {files}  Backends provided no user object for ca263936-c379-1035-9f8b-75202ddda69a
   Oct 10 10:09:10 LNXCLOUDWEB ownCloud[52761]: {no app in context} Exception: {"Exception":"OC\User\NoUserException","Message":"Backends provided no user object for ca263936-c379-1035-9f8b-75202ddda69a","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(99): OC\Files\Filesystem::initMountPoints('ca263936-c379-1...')\n#1 \/var\/www\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(448): OC\Files\Storage\Shared->init()\n#2 \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(485): OC\Files\Storage\Shared->getWrapperStorage()\n#3 \/var\/www\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(122): OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage('\\OC\\Files\\Stora...')\n#4 \/var\/www\/owncloud\/lib\/private\/legacy\/util.php(148): OC\Files\Storage\Shared->instanceOfStorage('\\OC\\Files\\Stora...')\n#5 \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/StorageFactory.php(100): OC_Util::{closure}('\/49508132-ebc6-...', Object(OC\Files\Storage\Shared), Object(OCA\Files_Sharing\SharedMount))\n#6 \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/StorageFactory.php(82): OC\Files\Storage\StorageFactory->wrap(Object(OCA\Files_Sharing\SharedMount), Object(OC\Files\Storage\Shared))\n#7 \/var\/www\/owncloud\/lib\/private\/Files\/Mount\/MountPoint.php(137): OC\Files\Storage\StorageFactory->getInstance(Object(OCA\Files_Sharing\SharedMount), '\\OC\\Files\\Stora...', Array)\n#8 \/var\/www\/owncloud\/lib\/private\/Files\/Mount\/MountPoint.php(160): OC\Files\Mount\MountPoint->createStorage()\n#9 \/var\/www\/owncloud\/lib\/private\/Files\/View.php(1356): OC\Files\Mount\MountPoint->getStorage()\n#10 \/var\/www\/owncloud\/lib\/private\/Files\/Node\/Root.php(180): OC\Files\View->getFileInfo('\/49508132-ebc6-...')\n#11 \/var\/www\/owncloud\/lib\/private\/Files\/Node\/Root.php(342): OC\Files\Node\Root->get('\/49508132-ebc6-...')\n#12 \/var\/www\/owncloud\/lib\/private\/Server.php(809): OC\Files\Node\Root->getUserFolder('49508132-ebc6-1...')\n#13 \/var\/www\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/ServerFactory.php(127): OC\Server->getUserFolder()\n#14 [internal function]: OCA\DAV\Connector\Sabre\ServerFactory->OCA\DAV\Connector\Sabre\{closure}(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#15 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#16 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\Event\EventEmitter->emit('beforeMethod', Array)\n#17 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#18 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(56): Sabre\DAV\Server->exec()\n#19 \/var\/www\/owncloud\/remote.php(164): require_once('\/var\/www\/ownclo...')\n#20 {main}","File":"\/var\/www\/owncloud\/lib\/private\/Files\/Filesystem.php","Line":405}
   Oct 10 10:09:29 LNXCLOUDWEB ownCloud[52761]: {files}  Backends provided no user object for ca263936-c379-1035-9f8b-75202ddda69a
   Oct 10 10:09:29 LNXCLOUDWEB ownCloud[52761]: {no app in context} Exception: {"Exception":"OC\User\NoUserException","Message":"Backends provided no user object for ca263936-c379-1035-9f8b-75202ddda69a","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(99): OC\Files\Filesystem::initMountPoints('ca263936-c379-1...')\n#1 \/var\/www\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(448): OC\Files\Storage\Shared->init()\n#2 \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(485): OC\Files\Storage\Shared->getWrapperStorage()\n#3 \/var\/www\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(122): OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage('\\OC\\Files\\Stora...')\n#4 \/var\/www\/owncloud\/lib\/private\/legacy\/util.php(148): OC\Files\Storage\Shared->instanceOfStorage('\\OC\\Files\\Stora...')\n#5 \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/StorageFactory.php(100): OC_Util::{closure}('\/444430e4-ebc6-...', Object(OC\Files\Storage\Shared), Object(OCA\Files_Sharing\SharedMount))\n#6 \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/StorageFactory.php(82): OC\Files\Storage\StorageFactory->wrap(Object(OCA\Files_Sharing\SharedMount), Object(OC\Files\Storage\Shared))\n#7 \/var\/www\/owncloud\/lib\/private\/Files\/Mount\/MountPoint.php(137): OC\Files\Storage\StorageFactory->getInstance(Object(OCA\Files_Sharing\SharedMount), '\\OC\\Files\\Stora...', Array)\n#8 \/var\/www\/owncloud\/lib\/private\/Files\/Mount\/MountPoint.php(160): OC\Files\Mount\MountPoint->createStorage()\n#9 \/var\/www\/owncloud\/lib\/private\/Files\/View.php(1356): OC\Files\Mount\MountPoint->getStorage()\n#10 \/var\/www\/owncloud\/lib\/private\/Files\/Node\/Root.php(180): OC\Files\View->getFileInfo('\/444430e4-ebc6-...')\n#11 \/var\/www\/owncloud\/lib\/private\/Files\/Node\/Root.php(342): OC\Files\Node\Root->get('\/444430e4-ebc6-...')\n#12 \/var\/www\/owncloud\/lib\/private\/Server.php(809): OC\Files\Node\Root->getUserFolder('444430e4-ebc6-1...')\n#13 \/var\/www\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/ServerFactory.php(127): OC\Server->getUserFolder()\n#14 [internal function]: OCA\DAV\Connector\Sabre\ServerFactory->OCA\DAV\Connector\Sabre\{closure}(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#15 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#16 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\Event\EventEmitter->emit('beforeMethod', Array)\n#17 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#18 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(56): Sabre\DAV\Server->exec()\n#19 \/var\/www\/owncloud\/remote.php(164): require_once('\/var\/www\/ownclo...')\n#20 {main}","File":"\/var\/www\/owncloud\/lib\/private\/Files\/Filesystem.php","Line":405}
   Oct 10 10:09:40 LNXCLOUDWEB ownCloud[53109]: {files}  Backends provided no user object for ca263936-c379-1035-9f8b-75202ddda69a
   Oct 10 10:09:40 LNXCLOUDWEB ownCloud[53109]: {no app in context} Exception: {"Exception":"OC\User\NoUserException","Message":"Backends provided no user object for ca263936-c379-1035-9f8b-75202ddda69a","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(99): OC\Files\Filesystem::initMountPoints('ca263936-c379-1...')\n#1 \/var\/www\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(448): OC\Files\Storage\Shared->init()\n#2 \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(485): OC\Files\Storage\Shared->getWrapperStorage()\n#3 \/var\/www\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(122): OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage('\\OC\\Files\\Stora...')\n#4 \/var\/www\/owncloud\/lib\/private\/legacy\/util.php(148): OC\Files\Storage\Shared->instanceOfStorage('\\OC\\Files\\Stora...')\n#5 \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/StorageFactory.php(100): OC_Util::{closure}('\/49508132-ebc6-...', Object(OC\Files\Storage\Shared), Object(OCA\Files_Sharing\SharedMount))\n#6 \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/StorageFactory.php(82): OC\Files\Storage\StorageFactory->wrap(Object(OCA\Files_Sharing\SharedMount), Object(OC\Files\Storage\Shared))\n#7 \/var\/www\/owncloud\/lib\/private\/Files\/Mount\/MountPoint.php(137): OC\Files\Storage\StorageFactory->getInstance(Object(OCA\Files_Sharing\SharedMount), '\\OC\\Files\\Stora...', Array)\n#8 \/var\/www\/owncloud\/lib\/private\/Files\/Mount\/MountPoint.php(160): OC\Files\Mount\MountPoint->createStorage()\n#9 \/var\/www\/owncloud\/lib\/private\/Files\/View.php(1356): OC\Files\Mount\MountPoint->getStorage()\n#10 \/var\/www\/owncloud\/lib\/private\/Files\/Node\/Root.php(180): OC\Files\View->getFileInfo('\/49508132-ebc6-...')\n#11 \/var\/www\/owncloud\/lib\/private\/Files\/Node\/Root.php(342): OC\Files\Node\Root->get('\/49508132-ebc6-...')\n#12 \/var\/www\/owncloud\/lib\/private\/Server.php(809): OC\Files\Node\Root->getUserFolder('49508132-ebc6-1...')\n#13 \/var\/www\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/ServerFactory.php(127): OC\Server->getUserFolder()\n#14 [internal function]: OCA\DAV\Connector\Sabre\ServerFactory->OCA\DAV\Connector\Sabre\{closure}(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#15 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#16 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\Event\EventEmitter->emit('beforeMethod', Array)\n#17 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#18 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(56): Sabre\DAV\Server->exec()\n#19 \/var\/www\/owncloud\/remote.php(164): require_once('\/var\/www\/ownclo...')\n#20 {main}","File":"\/var\/www\/owncloud\/lib\/private\/Files\/Filesystem.php","Line":405}
   Oct 10 10:09:54 LNXCLOUDWEB ownCloud[53105]: {PHP} InvalidArgumentException: Jail rootPath is null at /var/www/owncloud/lib/private/Files/Storage/Wrapper/Jail.php#55
   Oct 10 10:09:59 LNXCLOUDWEB ownCloud[52855]: {files}  Backends provided no user object for ca263936-c379-1035-9f8b-75202ddda69a
   Oct 10 10:09:59 LNXCLOUDWEB ownCloud[52855]: {no app in context} Exception: {"Exception":"OC\User\NoUserException","Message":"Backends provided no user object for ca263936-c379-1035-9f8b-75202ddda69a","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(99): OC\Files\Filesystem::initMountPoints('ca263936-c379-1...')\n#1 \/var\/www\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(448): OC\Files\Storage\Shared->init()\n#2 \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(485): OC\Files\Storage\Shared->getWrapperStorage()\n#3 \/var\/www\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(122): OC\Files\Storage\Wrapper\Wrapper->instanceOfStorage('\\OC\\Files\\Stora...')\n#4 \/var\/www\/owncloud\/lib\/private\/legacy\/util.php(148): OC\Files\Storage\Shared->instanceOfStorage('\\OC\\Files\\Stora...')\n#5 \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/StorageFactory.php(100): OC_Util::{closure}('\/444430e4-ebc6-...', Object(OC\Files\Storage\Shared), Object(OCA\Files_Sharing\SharedMount))\n#6 \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/StorageFactory.php(82): OC\Files\Storage\StorageFactory->wrap(Object(OCA\Files_Sharing\SharedMount), Object(OC\Files\Storage\Shared))\n#7 \/var\/www\/owncloud\/lib\/private\/Files\/Mount\/MountPoint.php(137): OC\Files\Storage\StorageFactory->getInstance(Object(OCA\Files_Sharing\SharedMount), '\\OC\\Files\\Stora...', Array)\n#8 \/var\/www\/owncloud\/lib\/private\/Files\/Mount\/MountPoint.php(160): OC\Files\Mount\MountPoint->createStorage()\n#9 \/var\/www\/owncloud\/lib\/private\/Files\/View.php(1356): OC\Files\Mount\MountPoint->getStorage()\n#10 \/var\/www\/owncloud\/lib\/private\/Files\/Node\/Root.php(180): OC\Files\View->getFileInfo('\/444430e4-ebc6-...')\n#11 \/var\/www\/owncloud\/lib\/private\/Files\/Node\/Root.php(342): OC\Files\Node\Root->get('\/444430e4-ebc6-...')\n#12 \/var\/www\/owncloud\/lib\/private\/Server.php(809): OC\Files\Node\Root->getUserFolder('444430e4-ebc6-1...')\n#13 \/var\/www\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/ServerFactory.php(127): OC\Server->getUserFolder()\n#14 [internal function]: OCA\DAV\Connector\Sabre\ServerFactory->OCA\DAV\Connector\Sabre\{closure}(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#15 \/var\/www\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Object(Closure), Array)\n#16 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\Event\EventEmitter->emit('beforeMethod', Array)\n#17 \/var\/www\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#18 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(56): Sabre\DAV\Server->exec()\n#19 \/var\/www\/owncloud\/remote.php(164): require_once('\/var\/www\/ownclo...')\n#20 {main}","File":"\/var\/www\/owncloud\/lib\/private\/Files\/Filesystem.php","Line":405}
   Oct 10 11:10:09 LNXCLOUDWEB ownCloud[55719]: {user_ldap} Turned off SSL certificate validation successfully.
   Oct 10 11:10:09 LNXCLOUDWEB ownCloud[55633]: {user_ldap} Turned off SSL certificate validation successfully.
   Oct 10 12:10:09 LNXCLOUDWEB ownCloud[59589]: {user_ldap} Turned off SSL certificate validation successfully.

**Comment by ogoffart** [comment]
I can spot nothing wrong in the logs.

What kind of folder gets deleted?  Are the folder deleted in the server? What does the client show in the activity tab?

**Comment by alviegas** [comment]
**Hello Goffart, thanks for the feedback.**

The big problem is that the folders are removed from the client side. On the side of the server is intact. When is the removal of the files, the client begins to resynchronize. Yesterday happened again. The following part of the log:

|0|Shared/1 - Direito|INST_REMOVE|Down|1476104943||4096||4||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal|INST_REMOVE|Down|1476104931||4096||0||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/1 - TCU|INST_REMOVE|Down|1476104922||4096||0||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/1 - TCU/1 - Acórdãos do TCU|INST_REMOVE|Down|1476104923||4096||0||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/1 - TCU/1 - Acórdãos do TCU/ATA Nº 14, DE 05 DE MAIO DE 2010.PDF|INST_REMOVE|Down|1445436393||9148697||0||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/1 - TCU/1 - Acórdãos do TCU/ATA Nº 29 DE 20 DE JULHO DE 2011.pdf|INST_REMOVE|Down|1445436097||3474447||0||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/1 - TCU/1 - Acórdãos do TCU/Informativo de Jurisprudência sobre Licitações e Contratos nº 01.pdf|INST_REMOVE|Down|1445436428||4454248||0||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/1 - TCU/1 - Acórdãos do TCU/Informativo de Jurisprudência sobre Licitações e Contratos nº 15.pdf|INST_REMOVE|Down|1445436253||122312||0||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/1 - TCU/Lei-de-Licitações-Entendimento-TCU.pdf|INST_REMOVE|Down|1458231065||6623263||0||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/10 - Ministérios|INST_REMOVE|Down|1476104922||4096||0||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/10 - Ministérios/1 - Planejamento|INST_REMOVE|Down|1476104923||4096||0||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/10 - Ministérios/1 - Planejamento/1-o-ciclo-da-compra-sustentavel.pdf|INST_REMOVE|Down|1462386406||1019510||0||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/10 - Ministérios/1 - Planejamento/Carta de Serviços ao Cidadão - guia metodológico.pdf|INST_REMOVE|Down|1458232492||3866807||0||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/10 - Ministérios/2 - MCT|INST_REMOVE|Down|1476104922||4096||0||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/10 - Ministérios/2 - MCT/Processo de contratação de serviços|INST_REMOVE|Down|1476104922||4096||0||0|0|0|||INST_NONE|

...
...
...

|0|Shared/Plano de ação para a melhoria da Governança de TIC no Governo de PE - Detalhamento - 22.12.2015.xls|INST_REMOVE|Down|1451391763||143872||4||0|0|0|||INST_NONE|
|0|Shared/Projeto_Inteiro_Excel.xls|INST_REMOVE|Down|1457551147||1592320||4||0|0|0|||INST_NONE|
#=#=#=# Syncrun started  until  (0 msec)
#=#=#=# Syncrun started  until  (0 msec)
#=#=#=# Syncrun started  until  (0 msec)
|0|Shared|INST_SYNC|Down|1476106366|7fd1f95b0a93eb4a6e5c84bd6dcc5011|0|00079052ocwm3az89ho2|4||0|4096|1476107153|||INST_NONE|
|0|Shared/1 - Direito|INST_NEW|Down|1475861482|57f7dbeab6fed|0|00121201ocwm3az89ho2|4||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal|INST_NEW|Down|1475861482|57f7dbeab6989|0|00121208ocwm3az89ho2|4||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/1 - TCU|INST_NEW|Down|1467922440|577eb80832a11|0|00121214ocwm3az89ho2|4||0|0|0|||INST_NONE|
|0|Shared/1 - Direito/1 - Governo Federal/1 - TCU/1 - Acórdãos do TCU|INST_NEW|Down|1467922440|577eb80831fdb|0|00121219ocwm3az89ho2|4||0|0|0|||INST_NONE|
13:50:44|3390|Shared/1 - Direito/1 - Governo Federal/1 - TCU/1 - Acórdãos do TCU/ATA Nº 14, DE 05 DE MAIO DE 2010.PDF|INST_NEW|Down|1445436393|97ea55e1b37db9db30c5f38165ee367b|9148697|00121259ocwm3az89ho2|4||0|0|0|||INST_NONE|
13:50:44|1185|Shared/1 - Direito/1 - Governo Federal/1 - TCU/1 - Acórdãos do TCU/ATA Nº 29 DE 20 DE JULHO DE 2011.pdf|INST_NEW|Down|1445436097|be178b2218454bea9daf088a9c3a6695|3474447|00121232ocwm3az89ho2|4||0|0|0|||INST_NONE|
13:50:45|3369|Shared/1 - Direito/1 - Governo Federal/1 - TCU/1 - Acórdãos do TCU/Informativo de Jurisprudência sobre Licitações e Contratos nº 01:

**Comment by ogoffart** [comment]
`INST_REMOVE|Down` 
Seems to indicate that the file was first removed on the server. Maybe the server does not report the file as being there in some cases. Is there anything particular about the storage on the server? I see in the description it is a NFS mount. Maybe the server was not available for some reason?

**Comment by alviegas** [comment]
The files remain intact on the server side. They are simply removed in the local folder on the client side.

We use a part server which is shared by NFS within a virtualized environment by VMware. We did not record problem accessing the network.

The problem only happens with "Files / Folders" shared. My personal synchronized files are intact. I take to remember that this same problem occurs when using the Client for Windows.

Thanks!

**Comment by ckamm** [comment]
@alviegas What @ogoffart is saying is that the logs indicate that the client thought the server said "this file does not exist anymore, please delete it". It's unlikely to be caused by a bug, most probably the server actually "forgot" about the files briefly.

* Is there a way to monitor whether the NFS mount occasionally has short outages?
* A full client log of the deletion happening would also show us what's going on exactly (https://doc.owncloud.org/desktop/1.8/troubleshooting.html#saving-files-directly)

**Comment by alviegas** [comment]
Thanks for the Tip "Ogoffart" and "Ckamm". I will focus on the NFS server to see if you have any instability. Once you have a result, I update here!

**Comment by joaquimferraz** [comment]
In config.php change the "filesystem_check_changes" 1 parameter to 0. We are monitoring. Does it help?

**Comment by ogoffart** [comment]
This might be a bug in the server and the way it handle NFS mount.

**Comment by ogoffart** [comment]
I don't think this is a bug in the client.
You can try to ask for help on owncloud central.
