### ISSUE TITLE
date not reported in the logs and journal (symptom of other serious issues?)

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5241]
NOTE:
I am reporting this issue with date in the journal because I suspect it may be connected to some wierd behaviour of 2.2.4 client that I am currently investigating: after update 2.1.1->2.2.4 the client started downloading directories which were excluded from sync previously (but not immediately but after a while). I am not clear on yet what triggered this behaviour (could be a timezone change). I would report this separately.

Date is not reported in .owncloudsync.log in version 2.2.4. When I switch back to version 2.1.1 the date is reported correctly. It looks like this:

     $ grep started .owncloudsync.log.1 | tail
     #=#=#=# Syncrun started  until  (0 msec)
     #=#=#=# Syncrun started  until  (0 msec)
     #=#=#=# Syncrun started  until  (0 msec)
     #=#=#=# Syncrun started  until  (0 msec)
     #=#=#=# Syncrun started  until  (0 msec)
     #=#=#=# Syncrun started  until  (0 msec)
     #=#=#=# Syncrun started  until  (0 msec)
     #=#=#=# Syncrun started 2016-10-11T07:33:06 until 2016-10-11T07:33:13 (7165 msec)
     #=#=#=# Syncrun started  until  (0 msec)
     #=#=#=# Syncrun started 2016-10-11T07:37:30 until 2016-10-11T07:38:17 (47432 msec)

**Comment by ckamm** [comment]
I can reproduce the problem with the log file in 2.2.4. It seems to already have been adressed in master.

**Comment by ckamm** [comment]
It looks like this was an accident in 2d2c7bc9, but the surrounding changes look okay.

It'd be very interesting to hear about the other sync issues you're seeing!
