### ISSUE TITLE
Address issues created by bug that made files considered synced incorrectly

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#5242]
The bug was discovered with the help of @kliess in #5190, was probably introduced via 2f355c473acec71e77c0499bd55c26a634471263 and thus affects 2.1.1 to 2.2.4.

Summary: When there is an error during syncing a file down from the server, that error marks the folder as not having synced successfully and its etag isn't updated. But this error state isn't properly propagated to parent folders, so their etags in the database are updated even though they shouldn't be. That means that syncing the file will not be attempted again. 
This can silently create out-of-date files on a user's system. Downward sync errors do commonly happen in conjunction with file locks on Windows, when the file can't be overwritten by the download temporary.

Suggestion: Do a full remote discovery at least once when first having installed the next version, to catch any local files that are out of date due to this problem. We might even want to extend this to doing a full remote discovery at regular intervals (weekly?).

**Comment by ogoffart** [comment]
>  Do a full remote discovery at least once when first having installed the next version,

This is easy, search for `forceRemoteDiscovery` in syncjournaldb.cpp

> We might even want to extend this to doing a full remote discovery at regular intervals (weekly?).

We could for robustness.  We should then store the date of the last time we did it in the database or in the folder config.

**Comment by jturcotte** [comment]
For the record, 2f355c473acec71e77c0499bd55c26a634471263 has been reverted in 2.3.x by efb6b8c2c9a8dd3f25f6ddb5f67701f28ec7440a.

**Comment by ckamm** [comment]
Pull request: https://github.com/owncloud/client/pull/5243
