### ISSUE TITLE
Client Fails to upload files 

### ISSUE THREAD

**Issue by tur-ium** [owncloud/client#5244]
### Expected behaviour

Client detects newly created files in sync directory and uploads them from local client to server
### Actual behaviour

The web interface works perfectly (upload and download is good) and the client DOWNLOADS anything already on the server successfully

The client creates directories on the server (there has been some spurious behaviour, but I have not been able to properly test it), but does not actually upload any files

Very similar behaviour to the unclosed discussion: https://forum.owncloud.org/viewtopic.php?t=30115
### Steps to reproduce
1. Download most recent client on two machines running Linux Mint (from repo) and Windows 10 respectively
2. Set folder to synchronise
3. Try to sync
4. Fails => Remove synchronisation and create it again -> Fails again
### Server configuration

Operating system: ?? Shared host

Web server: Apache 

Database: SQL

PHP version: 5.6

ownCloud version: 9.1

Storage backend (external storage): ?
### Client configuration

Client version: 2.2.4

Operating system: Linux Mint 18 and Windows 10
### Logs
1. Here is a snippet of owncloud client log (from F12)

https: [SERVER ADDRESS]/remote.php/webdav/Documents/Example.odt - server replied: Forbidden" 
10-12 10:45:26:005 0x1516460 void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&)
"Documents/[PATH_TO_FILE]" INSTRUCTION_ERROR 6 "The item is not synced because of previous errors: Error downloading_
1. Server error log:
   grep "[FILE_TO_UPLOAD]" owncloud.log gives nothing!

**Comment by guruz** [comment]
>  server replied: Forbidden

@PVince81 ?

**Comment by PVince81** [comment]
@tur-ium please add your ownCloud version in the issue template.
This is important because since OC >= 9.0 the web UI also uses Webdav and you said the web UI upload works...

**Comment by tur-ium** [comment]
@PVince81 Updated, it's v9.1

**Comment by PVince81** [comment]
@tur-ium thanks.

Hmmm, so this means downloading files with the web UI works but downloading the same files with the sync client gets 403 forbidden ?

You could check the web server's access log and compare the request URL from the web UI download to the one from the sync client download. I don't think they're really different so I don't see why the server would decide to return 403. Could that 403 be from the web server and not from OC ?

**Comment by tur-ium** [comment]
Hmmm good call, but the server access log show the same path as above
<IP_HERE> - - [12/Oct/2016:03:43:07 -0600] "MKCOL /owncloud/remote.php/webdav/Documents/[PATH_TO_FILE] HTTP/1.1" 201 803 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"
<IP_HERE> - - [12/Oct/2016:03:43:09 -0600] "PUT /owncloud/remote.php/webdav/Documents/[PATH_TO_FILE] HTTP/1.1" 403 75532 "-" "Mozilla/5.0 (Linux) mirall/2.2.4"

**Comment by guruz** [comment]
@tur-ium Are we really talking about that it does MKCOL (which is for paths) on the same as the PUT (which is for a file)?

**Comment by guruz** [comment]
[PATH_TO_FILE] really being the same for the two lines you show from the server access log?

**Comment by tur-ium** [comment]
Ok, I have run it again with a dummy setup of a Test Folder and 1 .docx document. Here are all the logs:
CLIENT log:
# timestamp | duration | file | instruction | dir | modtime | etag | size | fileId | status | errorString | http result code | other size | other modtime | other etag | other fileId | other instruction
#=#=#=# Syncrun started  until  (0 msec)
|0|Example Document.docx|INST_NEW|Up|1476478330||159265||2|Error downloading https://<domain>.com/owncloud/remote.php/webdav/TestFolder/Example Document.docx - server replied: Forbidden|403|0|0|||INST_NONE|

OWNCLOUD SERVER log:
{"reqId":"WAFGuK3@HD0AACZqUJ4AAAHF","remoteAddr":"<IP>","app":"core","message":"No update found at the ownCloud appstore for app 166049","level":0,"time":"2016-10-14T20:57:30+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"WAFGuK3@HD0AACZqUJ4AAAHF","remoteAddr":"<IP>","app":"core","message":"No update found at the ownCloud appstore for app 166051","level":0,"time":"2016-10-14T20:57:31+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}
{"reqId":"WAFGuK3@HD0AACZqUJ4AAAHF","remoteAddr":"<IP>","app":"core","message":"No update found at the ownCloud appstore for app 166055","level":0,"time":"2016-10-14T20:57:31+00:00","method":"GET","url":"\/owncloud\/cron.php","user":"--"}

SERVER log
**<IP> - - [14/Oct/2016:14:53:02 -0600] "PUT /owncloud/remote.php/webdav/TestFolder/Example%20Document.docx HTTP/1.1" 403 161831 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
<IP> - - [14/Oct/2016:14:53:53 -0600] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 1206 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
<IP> - - [14/Oct/2016:14:53:55 -0600] "PROPFIND /owncloud/remote.php/webdav/TestFolder HTTP/1.1" 207 1506 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
**<IP> - - [14/Oct/2016:14:53:56 -0600] "PUT /owncloud/remote.php/webdav/TestFolder**/Example%20Document.docx HTTP/1.1" 403 161830 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
<IP> - - [14/Oct/2016:14:53:59 -0600] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1166 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
<IP> - - [14/Oct/2016:14:54:23 -0600] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 1206 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
<IP> - - [14/Oct/2016:14:54:31 -0600] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 1166 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
<IP> - - [14/Oct/2016:14:54:53 -0600] "PROPFIND /owncloud/remote.php/webdav/TestFolder HTTP/1.1" 207 1296 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
<IP> - - [14/Oct/2016:14:55:24 -0600] "PROPFIND /owncloud/remote.php/webdav/TestFolder HTTP/1.1" 207 1334 "-" "Mozilla/5.0 (Windows) mirall/2.2.4 (build 6408)"
<IP> - - [14/Oct/2016:14:55:44 -0600] "GET /owncloud/ HTTP/1.1" 302 6320 "-" "Mozilla/5.0 (Windows NT 10.0; WOW64; rv:49.0) Gecko/20100101 Firefox/49.0"

**Comment by guruz** [comment]
But could you paste the line with the MKCOL too?
Or is the MKCOL actually not relevant?

So the server just replies 403 and there is for sure no file or folder at the same place with name ```Example%20Document.docx ```?

**Comment by tur-ium** [comment]
I didn't find any MKCOL lines involving Example%20Document.docx in the log and double checking I see no file either (although the folder Test Folder was created!!)

**Comment by tur-ium** [comment]
Are there any more tests I could do to help diagnose this?
Should I add this to the forum post?

**Comment by ckamm** [comment]
@tur-ium Does this happen also to files that don't have a space in them? Maybe try with Example.docx? Possibly the server is not configured correctly for these urls?

**Comment by tur-ium** [comment]
@ckamm Good idea. I tried a different file Example.docx and got the error in the client:
 01/11/2016 22:41:34,                                                    Example.docx,               sync\TestFolder,Error downloading https://turium.com/owncloud/remote.php/webdav/TestFolder/Example.docx - server replied: Forbidden
 01/11/2016 22:41:33,                                                   ~$xample.docx,               sync\TestFolder,File is listed on the ignore list.

**Comment by ckamm** [comment]
Unfortunately I have no further ideas about why this would happen. @ogoffart do you have any?

**Comment by ckamm** [comment]
@tur-ium Are you using http auth? Could you try a manual PUT from the command line with curl on your linux machine?
```
curl -v -u yourusername -X PUT -insecure 'https://turium.com/owncloud/remote.php/webdav/TestFolder/Example.docx' -d test
```

**Comment by guruz** [comment]
@tur-ium Any news?

**Comment by guruz** [comment]
Sorry we can't help without more info
