### ISSUE TITLE
remote folder full scan

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5246]
Is there any particular reason that the sync client does a full remote folder tree scan on restart?

This is not so efficient for high-latency/shaky networks, where it results in hundreds of PROPFIND calls. Currently in my case I am 160ms away from the server and it takes 2.5s per request and I have around 1000 directories to walk. Any network glitch is likely to restart this process.

If the reason is that server-side etag propagation mechanism is not trusted then I would propose some improvements:
 - make it a server capability, so when a server gets fixed clients will not need to do this
 - after a couple of requests you can already foresee how long it will take and if it is going to take longer than some absolute time (say 1m) then you may want to skip it
 - you may want to add a possibility for the server admin a mechanism where they can trigger such a full rescan as a recovery mechanism in case of any server problems (idea similar to the file recall feature)

**Comment by moscicki** [comment]
Investigating deeper I think this was triggered by the change of the ignore file list (which I am investigating for another problem).

Could you please confirm that this is the only time full sync is forced? Code seems to confrm this assumption:

    $ grep forceRemoteDiscoveryNextSync -r . 
    ./src/gui/ignorelisteditor.cpp:        folder->journalDb()->forceRemoteDiscoveryNextSync();

**Comment by moscicki** [comment]
BTW. This particular use-case of excluding a specific folder from sync via "Ignored Files" should be in reality done via (revamped) Selective Sync. Then, you would maybe not even have to force the discovery on the full space but only on affected sub-tree. Yet another reason to integrate it into Selective Sync, isn't it @ckamm ?

**Comment by ogoffart** [comment]
Yes, we need to do a full discovery after the ignored list is changed. The reason is that there might be files that were ignored before which are no longner ignored. But we don't know because ignored files are not in the database. Therefore we need to query the server.

**Comment by moscicki** [comment]
Okey, thx.
