### ISSUE TITLE
Constant download and subsequent upload of the same file types

### ISSUE THREAD

**Issue by johenning** [owncloud/client#5250]
### Expected behaviour

When the owncloud client downloads a file from the server, the file should have the same modification date/creation date as on the server. Furthermore, unless the file is changed, the owncloud client should not upload the file to the server.
### Actual behaviour

Every time I start the client, it re-downloads (as far as I can tell) all .exe, .dll, .bat and .js files. The modification/creation date is set to the moment of the download. After it has downloaded all these files, it starts uploading all of them, presumably because it thinks they changed. 
It seems that this cycle restarts constantly when 2 clients on different machines are running at once.
### Steps to reproduce

I am not entirely sure what steps led to this behaviour. The folder was originally copied, but when the client was setup it downloaded/uploaded almost everything. I have deleted subfolders and uploaded them from scratch, this did not change anything. I have also deleted the entire folder and completely downloaded it through the client again.
1. Start owncloud client
2. Have .exe files in the owncloud folder
3. Client downloads all .exe, etc files from server
4. Client uploads all files it just downloaded
5. Start second client
6. Second client does the exact same thing and in the process triggers the other client to do the same.
### Server configuration

Operating system: Ubuntu 14.04.5 LTS

Web server: nginx/1.4.6

Database: mysql  Ver 14.14

PHP version: PHP 5.5.9-1ubuntu4.20

ownCloud version: ownCloud 9.1.1 

Storage backend (external storage): local storage
### Client configuration (both)

Client version: 2.2.4 (build 6408)

Operating system: Windows 8.1

OS language: English

Installation path of client: C:\Program Files (x86)\ownCloud\
### Logs
1. Client logfile: 
   Sync Activity:
   12.10.2016 21:23:14,                             Tools/SysinternalsSuite/Procmon.exe,                   C:\Owncloud,     Downloaded,      2 MB
   [...]
   12.10.2016 21:34:57,                             Tools/SysinternalsSuite/Procmon.exe,                   C:\Owncloud,       Uploaded,      2 MB

Log File (every line that references Procmon.exe): https://gist.github.com/johenning/014ef4c0fdf7973feb561b471fc46ff9
1. Web server error log: 
   2016/10/12 10:11:46 [error] 1285#0: *31184 directory index of "/var/www/owncloud/core/doc/user/_static/" is forbidden, client: [Redacted], server:[Redacted] , request: "GET /core/doc/user/_static/ HTTP/1.1", host: "[Redacted]", referrer: "https://[Redacted]/core/doc/user/index.html"
   2016/10/12 10:12:14 [error] 1285#0: *31181 access forbidden by rule, client: [Redacted], server: [Redacted], request: "GET /data/htaccesstest.txt?t=1476259933940 HTTP/1.1", host: "[Redacted]"
   2016/10/12 19:57:18 [error] 1285#0: *55618 upstream prematurely closed connection while reading response header from upstream, client: 192.168.1.100, server: [Redacted], request: "GET /remote.php/webdav/Dokumente/My%20Notebook/Quick%20Notes.one HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "[Redacted]"
2. Server logfile: ownCloud log (data/owncloud.log): 
   {"reqId":"7pEzA9Vc\/Or\/N+AqfgIT","remoteAddr":"[Redacted]","app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2016-10-12T19:10:20+00:00","method":"GET","url":"\/remote.php\/webdav\/[Redacted]\/makesystable.exe","user":"[Redacted]"}
   {"reqId":"lTDRfIWPWBmxCRXj8T5d","remoteAddr":"192.168.1.100","app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2016-10-12T19:19:18+00:00","method":"GET","url":"\/remote.php\/webdav\/[Redacted]\/vcredist_x86.exe","user":"[Redacted]"}
   {"reqId":"YKAhUsHiieHIzGeWWSMC","remoteAddr":"192.168.1.100","app":"PHP","message":"Comments starting with '#' are deprecated in Unknown on line 1 at Unknown#0","level":3,"time":"2016-10-12T19:34:52+00:00","method":"PROPFIND","url":"\/remote.php\/webdav\/","user":"[Redacted]"}

**Comment by guruz** [comment]
> .exe, .dll, .bat and .js 

This is typical behaviour of virus scanners (on your Windows or on the server).
Can you verify this and then close this issue?

**Comment by johenning** [comment]
The download followed by upload without modification happens on a system without any virus scanner running. I can test whether anti virus software on the second client plays a factor later today.

The server is not running any anti virus software that I am aware of.

**Comment by guruz** [comment]
Maybe you can tail -f the HTTPd access log to check what the other client is doing?

**Comment by johenning** [comment]
There is only one client running at the moment. It is doing the up/downloading all on its own.

**Comment by johenning** [comment]
Disabling the virus scanner on the second client doesnt change anything either.

**Comment by ckamm** [comment]
@johenning Your log file excerpt is interesting. Could you give us a couple of lines around `csync_walker` and `csync_detect_update` at 21:28:19:503? Probably it just tells us that the client thinks the mtime of the local file has changed, but it might also be helpful.

**Comment by johenning** [comment]
@ckamm Here is everything with that timestamp, the most relevant line probably being:
`10-12 21:28:19:503 0x734e638 _csync_detect_update: Database entry found, compare: 1476300194 <-> 1476298967, etag: (null) <-> b0b5f67bda091b6e90f4192c9a6fe304, inode: 117000 <-> 117000, size: 2510528 <-> 2510528, perms:  <-> RDNVW, ignore: 0`
```
10-12 21:28:19:503 0x734e638 _csync_detect_update: file: Tools/SysinternalsSuite/procdump.exe, instruction: INSTRUCTION_EVAL <<=
10-12 21:28:19:503 0x734e638 csync_walker: file: C:/Owncloud/Tools/SysinternalsSuite/procexp.chm [inode=106333 size=72154]
10-12 21:28:19:503 0x734e638 _csync_detect_update: Database entry found, compare: 1350303818 <-> 1350303818, etag: (null) <-> 3cf0387f0390470c13a0f15ec24a4655, inode: 106333 <-> 106333, size: 72154 <-> 72154, perms:  <-> RDNVW, ignore: 0
10-12 21:28:19:503 0x734e638 _csync_detect_update: file: Tools/SysinternalsSuite/procexp.chm, instruction: INSTRUCTION_NONE <<=
10-12 21:28:19:503 0x734e638 csync_walker: file: C:/Owncloud/Tools/SysinternalsSuite/procexp.exe [inode=118715 size=2925760]
10-12 21:28:19:503 0x734e638 _csync_detect_update: Database entry found, compare: 1476300254 <-> 1476298982, etag: (null) <-> e4e18f200fc314a86787294a5ecb0e05, inode: 118715 <-> 118715, size: 2925760 <-> 2925760, perms:  <-> RDNVW, ignore: 0
10-12 21:28:19:503 0x734e638 _csync_detect_update: file: Tools/SysinternalsSuite/procexp.exe, instruction: INSTRUCTION_EVAL <<=
10-12 21:28:19:503 0x734e638 csync_walker: file: C:/Owncloud/Tools/SysinternalsSuite/procmon.chm [inode=106326 size=63582]
10-12 21:28:19:503 0x734e638 _csync_detect_update: Database entry found, compare: 1322477202 <-> 1322477202, etag: (null) <-> 81e19535089510d592991964056564d9, inode: 106326 <-> 106326, size: 63582 <-> 63582, perms:  <-> RDNVW, ignore: 0
10-12 21:28:19:503 0x734e638 _csync_detect_update: file: Tools/SysinternalsSuite/procmon.chm, instruction: INSTRUCTION_NONE <<=
10-12 21:28:19:503 0x734e638 csync_walker: file: C:/Owncloud/Tools/SysinternalsSuite/Procmon.exe [inode=117000 size=2510528]
10-12 21:28:19:503 0x734e638 _csync_detect_update: Database entry found, compare: 1476300194 <-> 1476298967, etag: (null) <-> b0b5f67bda091b6e90f4192c9a6fe304, inode: 117000 <-> 117000, size: 2510528 <-> 2510528, perms:  <-> RDNVW, ignore: 0
10-12 21:28:19:503 0x734e638 _csync_detect_update: file: Tools/SysinternalsSuite/Procmon.exe, instruction: INSTRUCTION_EVAL <<=**
10-12 21:28:19:503 0x734e638 csync_walker: file: C:/Owncloud/Tools/SysinternalsSuite/PsExec.exe [inode=130349 size=396480]
10-12 21:28:19:503 0x734e638 _csync_detect_update: Database entry found, compare: 1476300188 <-> 1476298967, etag: (null) <-> 06ecec6f097262f27cee6c29249e03f2, inode: 130349 <-> 130349, size: 396480 <-> 396480, perms:  <-> RDNVW, ignore: 0
10-12 21:28:19:503 0x734e638 _csync_detect_update: file: Tools/SysinternalsSuite/PsExec.exe, instruction: INSTRUCTION_EVAL <<=
10-12 21:28:19:503 0x734e638 csync_walker: file: C:/Owncloud/Tools/SysinternalsSuite/psfile.exe [inode=106351 size=105264]
10-12 21:28:19:503 0x734e638 _csync_detect_update: Database entry found, compare: 1476300250 <-> 1476298982, etag: (null) <-> 9d9e9cc766398131088c10def0be9962, inode: 106351 <-> 106351, size: 105264 <-> 105264, perms:  <-> RDNVW, ignore: 0
10-12 21:28:19:503 0x734e638 _csync_detect_update: file: Tools/SysinternalsSuite/psfile.exe, instruction: INSTRUCTION_EVAL <<=
10-12 21:28:19:503 0x734e638 csync_walker: file: C:/Owncloud/Tools/SysinternalsSuite/PsGetsid.exe [inode=129581 size=333176]
10-12 21:28:19:503 0x734e638 _csync_detect_update: Database entry found, compare: 1476300191 <-> 1476298967, etag: (null) <-> eeeb5c947344e3745a66dc028e073646, inode: 129581 <-> 129581, size: 333176 <-> 333176, perms:  <-> RDNVW, ignore: 0
10-12 21:28:19:503 0x734e638 _csync_detect_update: file: Tools/SysinternalsSuite/PsGetsid.exe, instruction: INSTRUCTION_EVAL <<=
10-12 21:28:19:503 0x734e638 csync_walker: file: C:/Owncloud/Tools/SysinternalsSuite/PsInfo.exe [inode=116110 size=390520]
10-12 21:28:19:503 0x734e638 _csync_detect_update: Database entry found, compare: 1476300195 <-> 1476298968, etag: (null) <-> 6b037a8966a19f6df8af4b9de551bc57, inode: 116110 <-> 116110, size: 390520 <-> 390520, perms:  <-> RDNVW, ignore: 0
10-12 21:28:19:503 0x734e638 _csync_detect_update: file: Tools/SysinternalsSuite/PsInfo.exe, instruction: INSTRUCTION_EVAL <<=
```

My feeling was, that the client does not correctly update the modification time after downloading and instead has the download-time as modification time, which it detects as an update. What function does the client use to modify time-stamps? 

It should be unrelated, but perhaps it is of interest that I have UAC disabled.

**Comment by ckamm** [comment]
@johenning The data would be consistent with the mtime not being set correctly on download:
* mtime stored in the db: 1476298967 (Mi 12. Okt 21:02:47 CEST 2016)
* mtime detected on the filesystem: 1476300194 (Mi 12. Okt 21:23:14 CEST 2016) - same second as the download

However, this usually works and we don't have any other reports of this kind of problem. The fact that this happens only to ".exe, .dll, .bat and .js" files is *very* suggestive of a virus scanner or other program of that kind. Could you double check nothing like that is running?

The `utimes` function is used to set the mtime.

What happens if you manually rename a .exe file? Is the mtime changed to the current time?

**Comment by johenning** [comment]
@ckamm 
> The fact that this happens only to ".exe, .dll, .bat and .js" files is very suggestive of a virus scanner or other program of that kind. Could you double check nothing like that is running?

That definitely seems like the most logical explanation, but I did check. Both systems have virus scanners installed. On one system its F-Secure, but its not running, none of its executables are in the process list and I can rename its directory. So I am pretty sure its not running.
The second system has ESET NOD32, which I have paused and still observed the reupload.
Also, I can change the modification time of .exe files via powershell (LastWriteTime=...) just fine.

>What happens if you manually rename a .exe file? Is the mtime changed to the current time?

The mtime doesn't change when I rename a file.

>The utimes function is used to set the mtime.

Could you point me to the source file? I found SetFileTime(), which seems to be used somewhere for setting the modification and access time. I wrote a small c-program to test it and it also works just fine.

**Comment by ckamm** [comment]
@johenning Unfortunately I'm at a loss for what's going on. I hope you can unearth more evidence about this suspicious behavior on your own.

The call to set mtimes goes through src/libsync/filesystem.cpp which uses `c_utimes` which is in turn defined in csync/src/std/c_time.c.

**Comment by johenning** [comment]
I am not sure what I changed, but I could not reproduce the problem with my self compiled client and it hasn't occurred with the normal client since then either.

I can only guess that a virus-scanner was still running somehow without my knowledge or while paused and that this was only fixed by uninstalling it.
