### ISSUE TITLE
[2.2.4] [Linux] no more menus: open browser or open OC in File Manager

### ISSUE THREAD

**Issue by toehold** [owncloud/client#5251]
When clicking on the OC Icon in the bar for each account a submenu appeared in previous versions:
- Open Browser
- Open File Manager

Now this submenu in version 2.2.4 disappeared!

Was this intentionally?

**Comment by guruz** [comment]
Which file manager?
Which packages did you use?
Which distro?

**Comment by toehold** [comment]
On 14/10/16 11:48, Markus Goetz wrote:
> Which file manager?
nautilus
> Which packages did you use?
ii  owncloud-client:amd64                                 2.2.4-1.3
                                                 amd64        The
ownCloud sync client - github.com/owncloud/client
> Which distro?
Ubuntu 16.04.1 64bit

**Comment by ckamm** [comment]
I'm pretty sure this is #4135 - my test Ubuntu 16.04 doesn't get submenus with 2.2.2 or 2.2.4 or master. @toehold Would you be up for downgrading to 2.2.2 to verify that this is really related to the 2.2.4 upgrade?

**Comment by toehold** [comment]
Yes not problem! Where can I find the 2.2.2 version for download?

**Comment by toehold** [comment]
https://github.com/owncloud/client/issues/5114

**Comment by ckamm** [comment]
@toehold Thanks for testing! I'll post your workaround on the other ticket!
