### ISSUE TITLE
Selective sync malfunction

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5253]
Client version 2.2.4 on MacOSX 10.10.5

I have a folder called 2ARCHIVE.tmp.test excluded from sync (unchecked):

![image](https://cloud.githubusercontent.com/assets/621965/19378598/4cd46c92-91a2-11e6-9040-d6e370d32f15.png)

However all over sudden files in this folder were downloaded:

![image](https://cloud.githubusercontent.com/assets/621965/19378629/849dfff8-91a2-11e6-97ee-24b90f09a18a.png)

I looked at sqlite but the table was empty:

```
sqlite> select * from selectivesync;
```

I ticket and unticked that folder in selective sync and checked the table again:

```
sqlite> select * from selectivesync;
2ARCHIVE.tmp.test2/|1
ARCHIVE.tmp.test/|1
tmp/|1
```

The folder appeared (and other folders which were also removed from sync via selective sync).

The client deleted then 2ARCHIVE.tmp.test but this is not reported in activity log (normally it should be).

There is something fishy with selective sync and operation of this version of client in general.

```
$sqlite3 --version
3.8.5 2014-08-15 22:37:57 c8ade949d4a2eb3bba4702a4a0e17b405e9b6ace
```

**Comment by guruz** [comment]
@ogoffart What could have changed there?

**Comment by guruz** [comment]
@moscicki And you are sure this did not happen because of you playing with the SQL DB in the other issue?
https://github.com/owncloud/client/issues/5248

**Comment by moscicki** [comment]
I did not use any update/delete statements (just reading with select). Would a mere fact to have sqlite session open impact writes from the cernbox process? I do not know for sure but I would not expect it.

**Comment by ogoffart** [comment]
Do you have logs or steps to reproduce?

**Comment by ogoffart** [comment]
It is very strange that the selectivesync entry gets lost. I don't see how this can happen.  I'm afraid i cannot do anything if i cannot reproduce it.

**Comment by ckamm** [comment]
I'm pretty sure #5357 is the follow up ticket to this one, right @moscicki?
