### ISSUE TITLE
Software repository for Ubuntu 16.10

### ISSUE THREAD

**Issue by armaccloud** [owncloud/client#5255]
The 13th of october, Ubuntu 16.10 has come out, the latest respository version of the Owncloud Client is for Ubutuntu 16.04.

https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

**Comment by crrodriguez** [comment]
A new build target will be available as soon as such repository is provided by the opensuse buildservice..

**Comment by armaccloud** [comment]
The repository is now available [here](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client). Closing.
