### ISSUE TITLE
Backup Detected message - Client stops working until selection

### ISSUE THREAD

**Issue by LukasRo** [owncloud/client#5260]
Hello. From time to time I get an error message "Backup Detected" while syncing files. Here I can choose "Keep Local Files as Conflict" or "Normal Sync". I can guarantee there was no backup or other tasks that resyncs "old" files, so this seems to be an error.

The bigger problem here is, that the client stops working until I choose one of the options above.

I've installed the client on a Windows Server where it runs and puts the data into a shared folder. When the sync stops because of the message I doesn't get a notice on one of my other clients.. and thats why I have to check the server several times a day.

Maybe there is a hidden config-key like _promptBackupMessage=false_ or sth like this?!
### Expected behaviour

Synching files instead of stoping the sync and waiting for input. Maybe there could ne a switch in the Settings?
### Actual behaviour

stop synching and waiting for me to choose
### Steps to reproduce
1. Waiting for the "Backup Detected"... don't know how to reproduce... but I see it every day.
2. now the sync won't stop until I choose between "keep local files as conflict" or "normal sync"
### Server configuration

Operating system: ‪Ubuntu 14.04.5 LTS‬
Web server: apache
Database: mysql
PHP version: 5.5.9
ownCloud version: ownCloud 9.1.0 (stable)
### Client configuration

Client version: 2.2.4 (build 6408)
Operating system: Windows Server 2008 R2 (same problem on Windows 10 x64)
OS language: German
Installation path of client: C:\Program Files (x86)\ownCloud
### Logs

Server logfile: ownCloud log (data/owncloud.log):
Latest error (many times teh same text in one sec):
`Exception: {"Exception":"BadMethodCallException","Message":"Not in batch","Code":0,"Trace":"#0 \/var\/www\/owncloud\/lib\/private\/Files\/Utils\/Scanner.php(143): OC\\Files\\Cache\\Propagator->commitBatch()\n#1 \/var\/www\/owncloud\/apps\/files\/lib\/BackgroundJob\/ScanFiles.php(87): OC\\Files\\Utils\\Scanner->backgroundScan('')\n#2 \/var\/www\/owncloud\/apps\/files\/lib\/BackgroundJob\/ScanFiles.php(111): OCA\\Files\\BackgroundJob\\ScanFiles->runScanner(Object(OC\\User\\User))\n#3 \/var\/www\/owncloud\/lib\/private\/BackgroundJob\/Job.php(52): OCA\\Files\\BackgroundJob\\ScanFiles->run(NULL)\n#4 \/var\/www\/owncloud\/lib\/private\/BackgroundJob\/TimedJob.php(53): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#5 \/var\/www\/owncloud\/cron.php(122): OC\\BackgroundJob\\TimedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#6 {main}","File":"\/var\/www\/owncloud\/lib\/private\/Files\/Cache\/Propagator.php","Line":145}`

**Comment by ogoffart** [comment]
The backup detection works with heuristics.
There is most likely files that where uploaded with a timestamp which was before the files that was last synchronized.

Future version of the server will have a data-fingerprint which is supported by owncloud 2.3

Should we disable heuristics checking in 2.3 ?

**Comment by LukasRo** [comment]
The important point in my bugreport is that the client stops working until I choose one of the options.

**Comment by andrewperry** [comment]
This is happening to us on various machines on OS X with 2.2.2 - hadn't been happening until recently.  You might want to fix the typo in the pop-up box of "erlier" to "earlier" while you are looking at this.

**Comment by ogoffart** [comment]
(The typo was fixed in mastersome time ago already : 7f0cc5b699dfbe41e218c64c0dade0b8fb08c6fc )

**Comment by ogoffart** [comment]
In 2.3,  the heuristics were modified so it is less likely the message appears. Is we detect that the ownCloud server is >= 9.1, we will not display this message as the server has the fingerprint feature.

Since the message is gone with newer server, i consider this issue closed.
