### ISSUE TITLE
Windows 7 Sync client does not sync

### ISSUE THREAD

**Issue by allcoolusernamesaregone** [owncloud/client#5264]
### Expected behaviour
After uploading a file, renaming a file or deleting a file by web ui or another sync client on another computer, the changes should be synced to the client. 

I use the client 2.2.4 build 2 on another windows computer where the client was not installed but is used by copy & paste the nextcloud directory, as no admin privileges for installing.
This clients _does_ recognize the changes on the server side.

So if I change a file name by webui, client 1 - regulary installed - does not gets notified or does not detect the change, but client 2 - copied instead of installed - does get notified and detects the change.

After a file in the client 1 which does not sync was modified or created or deleted, this change is synced to the server and after that the changes made by other clients/webgui are deteced. But as long as the client has no local changes to send, no remote changes are received/detected.

### Actual behaviour
Nothing. The client does not detect the changes on the server.

### Steps to reproduce
1.  install client 2.2.4 (build 2) and login
2. enable selective sync (but should not matter, problem occurs in the root directory)
3. after first sync no further server side changes are synced

### Server configuration
Operating system:  Bananian
Web server: nginx
Database: mysql
PHP version: 5.5
ownCloud version: nextcloud 10.0.1 (stable)
Storage backend (external storage): -

### Client configuration
Client version: nextcloud client 2.2.4 (build 2)
Operating system: win7
OS language: german
Installation path of client: C:\Program Files (x86)\Nextcloud

### Logs

Client 1 log which does not sync:
10-21 12:12:55:528 0x47480b0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "ip" + "/" "OCC::QuotaInfo"
10-21 12:13:13:378 0x47480b0 OCC::AbstractNetworkJob::start: !!! OCC::JsonApiJob created for "ip" + "ocs/v2.php/apps/notifications/api/v1/notifications" "OCC::ServerNotificationHandler"
10-21 12:13:23:778 0x47480b0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
10-21 12:13:23:780 0x47480b0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "ip" + "/" "OCC::ConnectionValidator"
10-21 12:13:26:055 0x47480b0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "ip" + "/" "OCC::QuotaInfo"
10-21 12:13:55:790 0x47480b0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
10-21 12:13:55:792 0x47480b0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "ip" + "/" "OCC::ConnectionValidator"
10-21 12:13:56:583 0x47480b0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "ip" + "/" "OCC::QuotaInfo"
10-21 12:14:26:955 0x47480b0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "ip" + "/" "OCC::QuotaInfo"
10-21 12:14:27:798 0x47480b0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
10-21 12:14:27:800 0x47480b0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "ip" + "/" "OCC::ConnectionValidator"
10-21 12:14:57:467 0x47480b0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "ip" + "/" "OCC::QuotaInfo"
10-21 12:14:59:807 0x47480b0 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
10-21 12:14:59:809 0x47480b0 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "ip" + "/" "OCC::ConnectionValidator"

Client 2 log which does sync on a change by another client/webui:
10-21 12:21:27:582 0x89e208 OCC::Folder::slotRunEtagJob: * Trying to check "https://ip:port/remote.php/webdav/" for changes via ETag check. (time since last sync: 742 s)
10-21 12:21:27:583 0x89e208 OCC::FolderMan::slotRunOneEtagJob: Scheduling "https://ip:port/remote.php/webdav/" to check remote ETag
10-21 12:21:27:584 0x89e208 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://ip" + "/" "OCC::Folder"
10-21 12:21:28:079 0x89e208 unknown: QString::arg: Argument missing: "https://docs.nextcloud.com/desktop/2.2/" , 2
10-21 12:21:28:080 0x89e208 unknown: QString::arg: Argument missing: "https://docs.nextcloud.com/desktop/2.2/" , 2
10-21 12:21:57:597 0x89e208 OCC::Folder::slotRunEtagJob: * Trying to check "https://ip:port/remote.php/webdav/" for changes via ETag check. (time since last sync: 772 s)
10-21 12:21:57:599 0x89e208 OCC::FolderMan::slotRunOneEtagJob: Scheduling "https://ip:port/remote.php/webdav/" to check remote ETag
10-21 12:21:57:602 0x89e208 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://ip" + "/" "OCC::Folder"
10-21 12:21:58:130 0x89e208 unknown: QString::arg: Argument missing: "https://docs.nextcloud.com/desktop/2.2/" , 2
10-21 12:21:58:131 0x89e208 unknown: QString::arg: Argument missing: "https://docs.nextcloud.com/desktop/2.2/" , 2
10-21 12:22:27:649 0x89e208 OCC::Folder::slotRunEtagJob: * Trying to check "https://ip:port/remote.php/webdav/" for changes via ETag check. (time since last sync: 802 s)
10-21 12:22:27:649 0x89e208 OCC::FolderMan::slotRunOneEtagJob: Scheduling "https://ip:port/remote.php/webdav/" to check remote ETag
10-21 12:22:27:649 0x89e208 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://ip" + "/" "OCC::Folder"
10-21 12:22:28:212 0x89e208 unknown: QString::arg: Argument missing: "https://docs.nextcloud.com/desktop/2.2/" , 2
10-21 12:22:28:212 0x89e208 unknown: QString::arg: Argument missing: "https://docs.nextcloud.com/desktop/2.2/" , 2

Both logs are repeating always the same, until a change is detected or send... but if idle, it keeps like shown

**Comment by allcoolusernamesaregone** [comment]
Oh forgot, after a client exit and restart it's ok for a while. Have to observe for how long, and if server or network issues force this issue to occur.

**Comment by guruz** [comment]
You might have mixed things up, this is the bugtracker of the ownCloud client.
