### ISSUE TITLE
Nextcloud client appears to break on relaunch

### ISSUE THREAD

**Issue by sfunk1x** [owncloud/client#5265]
Pardon me putting this bug here. The nextcloud client page suggested these bugs go here as opposed to under the nextcloud project (??). This appeared to break, for me, between Nextcloud 9 and 10.

### Expected behaviour

When I closed and re-launch the Nextcloud client, I expect it to reconnect to the Nextcloud server the way my Android phone does.

### Actual behaviour

The client can't reconnect to the server unless the account is removed from the client and then re-added. If that action is performed, then the account will sync. Closing the client and re-starting it (as in an update, or a reboot) will cause the client to fail to connect with a "credentials issue".

### Steps to reproduce
1. Build the nextcloud client and launch.
2. Add account to nextcloud server.
3. Sync files (save a file to the sync folder, note that the icon changes and the log shows that files are synced)
4. Close client and relaunch.

Note that the client won't reconnect to the server

### Server configuration
Operating system:

CentOS 7

Web server: 

Nginx

Database:

PHP version:

7

ownCloud version:

10

### Client configuration
Client version:

Current master

Operating system:

Ubuntu 16.04.01

### Logs

10-21 19:49:56:701 1062 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://cloud.domain.com" + "status.php" "OCC::ConnectionValidator"
10-21 19:49:56:850 1062 OCC::CheckServerJob::finished: status.php returns:  QMap(("edition", QVariant(QString, ""))("installed", QVariant(bool, true))("maintenance", QVariant(bool, false))("version", QVariant(QString, "9.1.0.16"))("versionstring", QVariant(QString, "10.0")))   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x1e069c0)
10-21 19:49:56:851 1062 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found:  QUrl("https://cloud.domain.com/status.php")  with version  "10.0" ( "9.1.0.16" )
10-21 19:49:56:851 1062 OCC::AccountState::slotConnectionValidatorResult: AccountState connection status change:  "Undefined" -> "Credentials Wrong"

2. Web server error log:

No errors recorded in nginx log.

3. Server logfile: ownCloud log (data/owncloud.log):

Exception: {"Message":"HTTP\/1.1 401 Username or password was incorrect, Username or password was incorrect","Exception":"Sabre\\DAV\\Exception\\NotAuthenticated","Code":0,"Trace":"#0 [internal function]: Sabre\\DAV\\Auth\\Plugin->beforeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#1 \/usr\/share\/nginx\/html\/nextcloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#2 \/usr\/share\/nginx\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(446): Sabre\\Event\\EventEmitter->emit('beforeMethod', Array)\n#3 \/usr\/share\/nginx\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/usr\/share\/nginx\/html\/nextcloud\/apps\/dav\/lib\/Server.php(184): Sabre\\DAV\\Server->exec()\n#5 \/usr\/share\/nginx\/html\/nextcloud\/apps\/dav\/appinfo\/v2\/remote.php(30): OCA\\DAV\\Server->exec()\n#6 \/usr\/share\/nginx\/html\/nextcloud\/remote.php(165): require_once('\/usr\/share\/ngin...')\n#7 {main}","File":"\/usr\/share\/nginx\/html\/nextcloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Auth\/Plugin.php","Line":188,"User":false}

**Comment by dragotin** [comment]
I am very sorry but we can not support with software that we neither control nor provide. Nextcloud copies the client code over, builds somehow and ships the software, so I am sure they are happy to help you with that.
Be our guest of course when running ownCloud :-)

Hint: make sure your config.php is accessible unauthenticated.

**Comment by sfunk1x** [comment]
That's kind of what I thought. Sorry for the bother.

**Comment by RealRancor** [comment]
@dragotin Seems the nextcloud client issue tracker is pointing users to this tracker here:

https://raw.githubusercontent.com/nextcloud/client_theming/master/issue_template.md

**Comment by ogoffart** [comment]
@dragotin, As long as there is no difference between the owncloud client and the nextcloud client, bugs that affect the nexcloud client are most likely to affect the owncloud client as well. Therefore we should accept bug reports from the nexcloud community as they can also affect owncloud users.

However, in this case, it is more likely that this is related to the server as it appeared with an upgrade of the server.  So i believe the nextcloud server bug tracker would be a better place.

**Comment by RealRancor** [comment]
@ogoffart https://github.com/owncloud/client/issues/5283 is another example where the issue is caused by the nextcloud client only.

**Comment by RealRancor** [comment]
@ogoffart And another difference:

> The Qt shipped with the ownCloud Client has some custom patches in it but it is quite a complicated and prone-to-break process to ship with a patched Qt so we don't.
> https://github.com/nextcloud/client_theming/issues/39#issuecomment-256642644

I have no idea what implications that have so you need to judge here.
