### ISSUE TITLE
Add user avatars to settings

### ISSUE THREAD

**Issue by tushevorg** [owncloud/client#5268]
It would be also great if Settings window could show user avatar instead of standard account icon ("gray shadow of a man"). When you have multiple accounts, it's easier to distinguish them by icons rather then by reading the text.

![image](https://cloud.githubusercontent.com/assets/5861233/19624939/d8f3089a-9923-11e6-9562-f412b0ddc8d0.png)

**Comment by guruz** [comment]
thanks. :)
however dup of https://github.com/owncloud/client/issues/3741
