### ISSUE TITLE
Add option to disable the delete all files prompt

### ISSUE THREAD

**Issue by JarbyDev** [owncloud/client#5276]
everytime a file got deleted in web UI, i got this warning in the windows 10 computer, how i can disable this notification, Thanks ( i using the latest version of the client)

![ow](https://cloud.githubusercontent.com/assets/11229573/19695198/40c1fad4-9ab0-11e6-8264-6f47529a51df.PNG)

also i tried to go to the configuration file but i dont see the option promptDeleteAllFiles.

This is my current owncloud,cfg

[General]
optionalDesktopNotifications=true

[Accounts]
0\Folders\1\localPath=C:/Users/jarbydev/JMH Drive/
version=2
0\Folders\1\targetPath=/
0\url=https://owncloud.example.com
0\Folders\1\paused=false
0\serverVersion=
0\Folders\1\ignoreHiddenFiles=true
0\http_certificatePasswd=
0\http_certificatePath=
0\http_user=jarbydev
0\authType=http
0\user=jarbydev

**Comment by RealRancor** [comment]
@JarbyDev This is already possible by adding the mentioned option here to your config file:

https://doc.owncloud.org/desktop/2.2/advancedusage.html#configuration-file

As explained in https://github.com/owncloud/client/pull/4389#issuecomment-256092763 this issue tracker shouldn't be misused for asking questions. Please only report actual bugs (e.g. if that config option is not working) in here.

**Comment by ckamm** [comment]
@JarbyDev You're saying you're seeing this message every time you delete a single file, even though there are other files in the folder that are not deleted? I'll try to reproduce that.

**Comment by ckamm** [comment]
@guruz pointed out to me that this might be linked to #5263 - potentially related to server/client time differences?

**Comment by hodyroff** [comment]
No info provided, please reopen with steps to reproduce if issue prevails.
