### ISSUE TITLE
Syncing one folder to two different instances

### ISSUE THREAD

**Issue by aleksandar-todorovic** [owncloud/client#5279]
### Expected behaviour

I should be able to sync a particular directory on my local machine to two different ownCloud instances at the same time. 
### Actual behaviour

Syncing on one without any problems, get an error saying: `Warning: The local folder /home/XX/YY is already used in a folder sync connection. Please pick another one!` when trying to sync it to another instance of ownCloud. 
### Steps to reproduce
1. Drop some files in some folder.
2. Choose a folder to sync on the first instance
3. Switch to a second tab where you are logged into a second ownCloud instance and try syncing the same folder.
### Server configuration

Operating system: Ubuntu 16.04

Web server: Apache2

Database: NoSQL

PHP version: 7.0.8-0ubuntu0.16.04.3

ownCloud version: NextCloud 10.0.1
### Client configuration

Client version: 2.2.2+dfsg-1

Operating system: Ubuntu GNOME 16.10

OS language: English

Installation path of client: /usr/bin/owncloud
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

`Template for output < 10 lines`
1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
   (On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
   (See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

```
10-27 14:10:22:810 7458 OCC::ownCloudGui::slotShowSettings: void OCC::ownCloudGui::slotShowSettings()
10-27 14:10:22:841 7458 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "{{FIRST INSTANCE}}" + "/" "OCC::QuotaInfo"
10-27 14:10:24:501 7458 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "{{SECOND INSTANCE}}" + "/" "OCC::QuotaInfo"
10-27 14:10:31:668 7458 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
10-27 14:10:31:668 7458 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "{{SECOND INSTANCE}}" + "/" "OCC::ConnectionValidator"
10-27 14:10:32:013 7458 OCC::AccountSettings::slotFolderWizardRejected: * Folder wizard cancelled
10-27 14:10:32:014 7458 unknown: QXcbConnection: XCB error: 3 (BadWindow), sequence: 802, resource id: 4195919, major code: 40 (TranslateCoords), minor code: 0
```
1. Web server error log:

I don't have access to the logs on the second instance.
1. Server logfile: ownCloud log (data/owncloud.log):

I don't have access to the logs on the second instance.

**Comment by dragotin** [comment]
This is exactly what is implemented in https://github.com/owncloud/client/pull/5045 

Testing of the pull request would be highly appreciated.

**Comment by aleksandar-todorovic** [comment]
Alright, will test it after work and comment there.

**Comment by ckamm** [comment]
@aleksandar-todorovic Nice, thanks! :)
