### ISSUE TITLE
Put deleted files into recycle bin locally

### ISSUE THREAD

**Issue by ganomi** [owncloud/client#528]
Hi,

i have a wish for future versions. (Maybe as an option that can be set in the preferences for each shared folder.)

When a file is deleted on the server then it should be put into the recycle bin on the local machine.
When a file is only renamed or moved and Mirall tells me it was "deleted", then it does not need to be put in the recycle bin.

(This would also be great for situations when the client crashes or does weird stuff and deletes random files. At least they would not be totally lost then.)

**Comment by catborise** [comment]
I think it is essential feature for some unusual delete operation. A few days ago, One client's files deleted unexpectedly in weird way. 
Owncloud recycle bin does not work proper way: Some files remain at recycle bin the others are vanished. 
Also desktop recycle bin is empty. Very important some files are disappeared, because of that feature lacking. If delete operation sent deleted file to recycle bin, may be we can return back them.
We are in pain for that situation. May be you should consider that request. Our clients are start to refused to use owncloud.
(may be you can say why you did not backup your files. the cause happened in 10 minutes.)

**Comment by jancborchardt** [comment]
> Owncloud recycle bin does not work proper way: Some files remain at recycle bin the others are vanished.

That sounds unusual. Can you elaborate @catborise?

Also @dragotin @danimo please comment on this from a desktop client dev standpoint.

**Comment by catborise** [comment]
hi,
unusual behaviour is some other issue's result and i am investigating(as far as i know it is related with user quota which is related with %50 limit of user quota for trash can)

i specified the situation for requrement of to send removed files to desktop recycle bin.

thanks

**Comment by ulakjira** [comment]
Hello,

indeed; as @catborise discribed we lost user data after the user unintentionally deleted all data on the web interface. The user was having 5 GB of data before deleting and only 2 GB of his data could be recovered from the trash bin.

Today we faced another bug with the delete operation. There is a zombie file which cannot be deleted all. 

cheers, Danyal

**Comment by dragotin** [comment]
Well, this seems to point to an bug in the server trashbin.

From my perspective, if the data is deleted on the web interface, it should go to the trashbin of ownCloud and be recoverable from there. If data is removed on the client, the desktop will have the native trash. So I do not see the need for an additional trash implementation on the client.

**Comment by ulakjira** [comment]
to be on the safe site with user data what would you recommend @dragotin @catborise ?

**Comment by dragotin** [comment]
@ulakjira backup and a working trashbin on the server.

**Comment by jancborchardt** [comment]
cc @schiesbn @DeepDiver1975 regarding deleted files app on the server.

**Comment by schiesbn** [comment]
It's depends on the quota of the user. The trashbin is only allowed to use up to 50% of the remaining free space. So it can happen that not all files end up in the trash bin.

**Comment by madorian** [comment]
why 50% of the remaining trash? This seems like a ridiculos setting. Who comes up with this stuff? So, if you accidently delete something, half of your shit might be gone forever? Jesus, I'm surrounded by morons.
