### ISSUE TITLE
macOS client doesn't use keychain

### ISSUE THREAD

**Issue by 1951FDG** [owncloud/client#5280]
### Expected behavior

macOS client doesn't use keychain, credentials are not saved in OS X keychain, this would be nice to have for our organization, because we have a strict security policy which enforces users to change their passwords, but in order for them to do so they need to know their current password, if owncloud would store the credentials in keychain, users could easily lookup their current password to change their password before it expires according to our security policy. We use LDAP binding. This would also be great, because keychain is like the macOS built-in standard for password keeping.
### Actual behavior

Currently unknown where the current password is stored, or how it can be retrieved.
### Steps to reproduce
1. N/A
2. N/A
3. N/A
### Client configuration

Client version: Version 2.2.4 (build 3709)

Operating system: macOS El Capitan

OS language: English

Installation path of client: /Applications

**Comment by ckamm** [comment]
Hm, we use the qtkeychain library (https://github.com/frankosterfeld/qtkeychain/) which should store the passwords in the OS X Keychain.

@guruz, do you know more?

**Comment by guruz** [comment]
Indeed, the OS X client is using the OS X keychain. Not sure why @1951FDG would have other behaviour?

**Comment by 1951FDG** [comment]
I will provide more info, maybe it only affect certain clients.

**Comment by 1951FDG** [comment]
@guruz It is rather unfortunate that this has been closed, on some clients the password is saved in keychain and on others it is not, what could be the cause of this?

**Comment by guruz** [comment]
@1951FDG Because you did not give information in the last 18 days. So from our side it was fixed. This happens all the time in our bugtracker, people don't report back because the issue solved itself. 

Is the password stored at all? Do you get the password dialog?
Did you check owncloud.cfg for the password?

**Comment by 1951FDG** [comment]
I believe the password is stored, but I don't where. The password dialog does show. But for the sample owncloud.cfg, no password is stored in keychain. Apparently the latest version does store the password in the keychain, since when does owncloud use qtkeychain? Maybe this issue is only prevalent in older versions of the mac client.

A sample owncloud.cfg:

```
[General]
optionalDesktopNotifications=true

[Accounts]
0\Folders\1\ignoreHiddenFiles=true
0\Folders\1\localPath=/Users/xxx/ownCloud/
0\Folders\1\paused=false
0\Folders\1\targetPath=/
0\authType=http
0\http_certificatePasswd=
0\http_certificatePath=
0\http_user=xxx@xxx.com
0\serverVersion=9.1.1.3
0\url=https://xxx.xxx.com
0\user=xxx@xxx.com
version=2

[SettingsMac]
geometry=@ByteArray(\x1\xd9\xd0\xcb\0\x2\0\0\0\0\0\0\0\0\0\x1\0\0\x2\x7f\0\0\x1\xf6\0\0\0\0\0\0\0\x17\0\0\x2\x7f\0\0\x1\xf6\0\0\0\0\0\0\0\0\x5\0)
```

**Comment by guruz** [comment]
@1951FDG The password is not stored in the .cfg, it's always in keychain (since some years?)
Maybe you had a really ancient version?

**Comment by 1951FDG** [comment]
No we never really used ancient versions here, it is rather strange, I recall systems were the keychain didn't include the owncloud password. Now, I would have to find a system where that is still the case, if I stumble upon a system like that, I will let you know.

**Comment by dometto** [comment]
On owncloud `2.5.4`, I am not even seeing the option to save to the Keychain, where I believe there used to be a 'Save this password' (or some such) checkbox. Anything I can do to debug?

**Comment by michaelstingl** [comment]
@dometto storing credentials in the macOS keychain is nothing users can control. It's done automatically. You can open _Keychain Access_ to verify.

**Comment by guruz** [comment]
@dometto @1951FDG Any news?

**Comment by 1951FDG** [comment]
I have no new news on this, I stopped using owncloud a while ago, @dometto to debug, just check your keychain access app and search for the saved password, it should be in your keychain.
