### ISSUE TITLE
Domain name change, LDAP database, how to transition users

### ISSUE THREAD

**Issue by 1951FDG** [owncloud/client#5281]
### Expected behavior
We currently changed our domain name, and we use LDAP binding, currently our AD is still setup with our old domain, we need need to transition to our new domain, but we don't know what the consequences would be for users data in owncloud. Is there anyone who has experience with this or could provide us wth advice.

### Actual behavior
We still use our old domain, fearing that changing domains will mess up users data in owncloud.

### Steps to reproduce
1. N/A
2. N/A
3. N/A

### Client configuration
Client version: Version 2.2.4 (build 3709)

Operating system: macOS El Capitan

OS language: English

Installation path of client: /Applications

**Comment by ckamm** [comment]
@1951FDG I'm sorry, but this does not sound like an issue with the ownCloud client. It may be a good idea for you to get in touch with ownCloud support.

From the client point of view: if you change domains and can set up forwarding from the old to the new domain, the client configurations should continue to work. (I think their settings would continue to point to the old domain though!) Make sure to test this with your specific forwarding setup and let us know if something goes wrong!

If you can't forward the old domain to the new one, your users will have to re-setup their clients. (there's the advanced option of changing the url in the configuration file)
