### ISSUE TITLE
owncloud folder is shared across different user accounts (permissions issue)

### ISSUE THREAD

**Issue by 1951FDG** [owncloud/client#5282]
### Expected behavior

For example, if you create a standard account or admin account, you can see the contents of the owncloud folder for other users, this is of security concern. Proper permissions should be setup for the owncloud folder. Antoher example, if we take a computer to a an Apple store for repair and create a standard account for Apple for testing purposes, Apple techs using that account could still see files and folders within the owncloud folder of the account belonging to the owner.
### Actual behavior

The contents of the owncloud folder is visible to different users, unlike what apple does for the Pictures, Movie, Music, etc folders that are all located in the user folder.
### Steps to reproduce
1. N/A
2. N/A
3. N/A
### Client configuration

Client version: Version 2.2.4 (build 3709)

Operating system: macOS El Capitan

OS language: English

Installation path of client: /Applications

**Comment by guruz** [comment]
@ckamm @ogoffart What is the behaviour on Linux? Is this with regards to umask somehow too?
On my OS X umask returns 0022

**Comment by ogoffart** [comment]
On linux we just use the default which is drwxr-xr-x.  But since it is usually within the user home directory, they are not readable by other users normaly.

**Comment by ckamm** [comment]
@guruz @ogoffart I don't think we explicitly change the permissions at all, do we? So the umask should be respected. There's some code in FileSystem to detect the default-write permissions that the umask implies, but this ticket is about either r permissions on files or x permissions on directories.

**Comment by ckamm** [comment]
I've double checked this on linux with a 002 and 027 umask. It sets the expected file and directory permissions. @1951FDG please clarify!

**Comment by 1951FDG** [comment]
I will clarify tomorrow, and do the tests in a MacOS system

**Comment by 1951FDG** [comment]
On my OS X umask also returns 0022

~/ownCloud returns 755 which is the standard permission
~/Downloads returns 700 which is the permission that should be set also for ownCloud

`This umask will be applied to all new files and folders created in the system. While the built-in Documents, Desktop, Music, Movies, and other folders in your home directory have custom permissions that keep them private, because of the umask, if you create a new folder next to these in your home folder then its contents can be readable by everyone. Therefore, for privacy, be sure to either change the permissions of files and folders you create in your home folder, or only place them within the existing folders Apple has created there.`

**Comment by 1951FDG** [comment]
@guruz  Thanks for fixing this, and by the way do you happen to know which upcoming release will include this fix?

**Comment by guruz** [comment]
@1951FDG it will be 2.3..
If you're brave enough you can grab a nightly build :) http://download.owncloud.com/desktop/daily/testpilotcloud-2.3.0.3839-nightly20161125.pkg
