### ISSUE TITLE
Share from Windows Desktop app not working

### ISSUE THREAD

**Issue by pfloor** [owncloud/client#5283]
### Expected behaviour
Right click any file or folder should bring up "Share with Nextcloud"

### Actual behaviour
There are no icons on any files or folders and there is no option to "Share with Nextcloud" from within file explorer when I right click a file or folder.

### Steps to reproduce
1. Shut down Owncloud and Install latest Nextcloud client Version 2.2.4 (build 2)
2. Shut down Nextcloud client, copy config file from Owncloud client. and uninstall Owncloud client.
3. Reboot.

### Server configuration
Operating system: SME Server 9 (Centos 6.7 derivative)

Web server: Apache 2.2.15

Database: MySQL 5.1.73

PHP version: 5.6.24-1

ownCloud version: 10.0.1

Storage backend (external storage): N/A

### Client configuration
Client version: 2.2.4 (build 2)

Operating system: Windows 10

OS language: English

Installation path of client: C:\Program Files (x86)\Nextcloud

### Logs

1. Client logfile: 
https://gist.github.com/pfloor/fa0d45cc581283e580305a2b235540ac

2. Web server error log:
```[Thu Oct 27 00:22:12 2016] [error] [client 10.0.0.50] client denied by server configuration: /home/e-smith/files/ibays/owncloud/html/data/htaccesstest.txt
[Thu Oct 27 00:22:17 2016] [error] [client 10.0.0.50] client denied by server configuration: /home/e-smith/files/ibays/owncloud/html/data/htaccesstest.txt
[Thu Oct 27 01:05:59 2016] [error] [client 10.0.0.50] client denied by server configuration: /home/e-smith/files/ibays/owncloud/html/data/htaccesstest.txt
[Thu Oct 27 01:06:03 2016] [error] [client 10.0.0.50] client denied by server configuration: /home/e-smith/files/ibays/owncloud/html/data/htaccesstest.txt
[Fri Oct 28 10:44:00 2016] [error] [client 10.0.0.50] client denied by server configuration: /home/e-smith/files/ibays/owncloud/html/data/htaccesstest.txt
[Fri Oct 28 10:55:53 2016] [error] [client 10.0.0.50] client denied by server configuration: /home/e-smith/files/ibays/owncloud/html/data/htaccesstest.txt```


3. Server logfile: ownCloud log (data/owncloud.log):
https://gist.github.com/pfloor/a6334b7a0764698f1b734447bf9cf7d7

**Comment by guruz** [comment]
This is the ownCloud client bugtracker, we cannot help you here.
