### ISSUE TITLE
Unable to update to 2.2.4 because the rpm package is broken.

### ISSUE THREAD

**Issue by tuxmaster** [owncloud/client#5286]
The package for Fedora is broken.
LANG=C sudo dnf update --best will fail with:
Last metadata expiration check: 0:36:53 ago on Sun Oct 30 07:28:41 2016.
Error: nothing provides opt-qt5-qtwebkit needed by owncloud-client-2.2.4-1.1.x86_64.
nothing provides opt-qt5-qtwebkit needed by owncloud-client-2.2.4-1.1.x86_64.
nothing provides opt-qt5-qtwebkit needed by owncloud-client-2.2.4-1.1.x86_64.
nothing provides opt-qt5-qtwebkit needed by owncloud-client-2.2.4-1.1.x86_64
Because the package is called qt5-qtwebkit and not opt-qt5-qtwebkit under Fedora

**Comment by PVince81** [comment]
@owncloud/packaging please have a look

**Comment by tuxmaster** [comment]
The link is dead (404)

**Comment by jnweiger** [comment]
For me this works fine:
<pre>
dnf config-manager --add-repo http://download.opensuse.org/repositories/isv:ownCloud:desktop/Fedora_24/isv:ownCloud:desktop.repo
Adding repo from: http://download.opensuse.org/repositories/isv:ownCloud:desktop/Fedora_24/isv:ownCloud:desktop.repo
[root@62c905df206b /]# dnf install owncloud-client
The ownCloud Desktop Client (Fedora_24)                                                                                       219 kB/s |  87 kB     00:00    
Dependencies resolved.
==============================================================================================================================================================
 Package                                   Arch                     Version                                      Repository                              Size
==============================================================================================================================================================
Installing:
 aajohan-comfortaa-fonts                   noarch                   2.004-6.fc24                                 fedora                                 151 k
 alsa-lib                                  x86_64                   1.1.1-1.fc24                                 fedora                                 407 k
 avahi-libs                                x86_64                   0.6.32-4.fc24                                updates                                 61 k
 cairo                                     x86_64                   1.14.6-2.fc24                                updates                                720 k
 cdparanoia-libs                           x86_64                   10.2-21.fc24                                 fedora                                  57 k
 cups-libs                                 x86_64                   1:2.1.4-2.fc24                               updates                                398 k
 double-conversion                         x86_64                   2.0.1-7.fc24                                 fedora                                  43 k
 fontconfig                                x86_64                   2.11.94-7.fc24                               updates                                241 k
 fontpackages-filesystem                   noarch                   1.44-17.fc24                                 fedora                                  15 k
 freetype                                  x86_64                   2.6.3-2.fc24                                 fedora                                 360 k
 glx-utils                                 x86_64                   8.3.0-3.fc24                                 fedora                                  38 k
 graphite2                                 x86_64                   1.3.6-1.fc24                                 fedora                                 115 k
 gstreamer1                                x86_64                   1.8.3-1.fc24                                 updates                                1.1 M
 gstreamer1-plugins-base                   x86_64                   1.8.3-1.fc24                                 updates                                1.4 M
 harfbuzz                                  x86_64                   1.2.7-1.fc24                                 fedora                                 219 k
 hwdata                                    noarch                   0.294-1.fc24                                 updates                                1.4 M
 iso-codes                                 noarch                   3.68-1.fc24                                  fedora                                 3.0 M
 libICE                                    x86_64                   1.0.9-5.fc24                                 fedora                                  70 k
 libSM                                     x86_64                   1.2.2-4.fc24                                 fedora                                  43 k
 libX11                                    x86_64                   1.6.3-3.fc24                                 fedora                                 607 k
 libX11-common                             noarch                   1.6.3-3.fc24                                 fedora                                 164 k
 libXau                                    x86_64                   1.0.8-6.fc24                                 fedora                                  33 k
 libXcomposite                             x86_64                   0.4.4-8.fc24                                 fedora                                  27 k
 libXdamage                                x86_64                   1.1.4-8.fc24                                 fedora                                  25 k
 libXext                                   x86_64                   1.3.3-4.fc24                                 fedora                                  41 k
 libXfixes                                 x86_64                   5.0.3-1.fc24                                 updates                                 22 k
 libXft                                    x86_64                   2.3.2-4.fc24                                 fedora                                  62 k
 libXi                                     x86_64                   1.7.8-2.fc24                                 updates                                 43 k
 libXrender                                x86_64                   0.9.10-1.fc24                                updates                                 29 k
 libXv                                     x86_64                   1.0.11-1.fc24                                updates                                 21 k
 libXxf86vm                                x86_64                   1.1.4-3.fc24                                 fedora                                  22 k
 libdatrie                                 x86_64                   0.2.9-3.fc24                                 fedora                                  31 k
 libdrm                                    x86_64                   2.4.73-1.fc24                                updates                                149 k
 libevdev                                  x86_64                   1.5.4-1.fc24                                 updates                                 39 k
 libgudev                                  x86_64                   230-3.fc24                                   fedora                                  31 k
 libicu                                    x86_64                   56.1-5.fc24                                  updates                                8.3 M
 libinput                                  x86_64                   1.5.1-1.fc24                                 updates                                116 k
 libjpeg-turbo                             x86_64                   1.5.0-4.fc24                                 updates                                153 k
 libmodman                                 x86_64                   2.0.1-12.fc24                                fedora                                  33 k
 libogg                                    x86_64                   2:1.3.2-5.fc24                               fedora                                  28 k
 libowncloudsync0                          x86_64                   2.2.4-1.3                                    isv_ownCloud_desktop                   397 k
 libpciaccess                              x86_64                   0.13.4-3.fc24                                fedora                                  30 k
 libpng                                    x86_64                   2:1.6.26-1.fc24                              updates                                119 k
 libproxy                                  x86_64                   0.4.12-3.fc24                                fedora                                  68 k
 libqt5keychain1                           x86_64                   0.7.0-9.3                                    isv_ownCloud_desktop                    57 k
 libthai                                   x86_64                   0.1.24-1.fc24                                fedora                                 196 k
 libtheora                                 x86_64                   1:1.1.1-14.fc24                              fedora                                 192 k
 libvisual                                 x86_64                   1:0.4.0-20.fc24                              fedora                                 141 k
 libvorbis                                 x86_64                   1:1.3.4-6.fc24                               fedora                                 189 k
 libwacom                                  x86_64                   0.21-1.fc24                                  updates                                 35 k
 libwacom-data                             noarch                   0.21-1.fc24                                  updates                                 59 k
 libwayland-client                         x86_64                   1.10.0-1.fc24                                fedora                                  33 k
 libwayland-server                         x86_64                   1.10.0-1.fc24                                fedora                                  38 k
 libwebp                                   x86_64                   0.5.1-2.fc24                                 updates                                243 k
 libxcb                                    x86_64                   1.11.1-2.fc24                                fedora                                 191 k
 libxkbcommon-x11                          x86_64                   0.6.1-1.fc24                                 updates                                 23 k
 libxshmfence                              x86_64                   1.2-3.fc24                                   fedora                                  11 k
 libxslt                                   x86_64                   1.1.28-12.fc24                               fedora                                 247 k
 mesa-libEGL                               x86_64                   12.0.3-2.fc24                                updates                                 96 k
 mesa-libGL                                x86_64                   12.0.3-2.fc24                                updates                                158 k
 mesa-libgbm                               x86_64                   12.0.3-2.fc24                                updates                                 42 k
 mesa-libglapi                             x86_64                   12.0.3-2.fc24                                updates                                 48 k
 mtdev                                     x86_64                   1.1.5-6.fc24                                 fedora                                  21 k
 opus                                      x86_64                   1.1.2-2.fc24                                 fedora                                 180 k
 orc                                       x86_64                   0.4.26-1.fc24                                updates                                169 k
 owncloud-client                           x86_64                   2.2.4-1.3                                    isv_ownCloud_desktop                   1.0 M
 owncloud-client-l10n                      x86_64                   2.2.4-1.3                                    isv_ownCloud_desktop                    13 k
 pango                                     x86_64                   1.40.3-1.fc24                                updates                                280 k
 pixman                                    x86_64                   0.34.0-2.fc24                                fedora                                 259 k
 qt-settings                               noarch                   24-7.fc24                                    updates                                 26 k
 qt5-qtbase                                x86_64                   5.6.1-3.fc24                                 updates                                3.0 M
 qt5-qtbase-common                         noarch                   5.6.1-3.fc24                                 updates                                 30 k
 qt5-qtbase-gui                            x86_64                   5.6.1-3.fc24                                 updates                                5.2 M
 qt5-qtdeclarative                         x86_64                   5.6.1-5.fc24                                 updates                                4.2 M
 qt5-qtlocation                            x86_64                   5.6.1-2.fc24                                 updates                                726 k
 qt5-qtsensors                             x86_64                   5.6.1-2.fc24                                 updates                                196 k
 qt5-qtwebchannel                          x86_64                   5.6.1-2.fc24                                 updates                                 84 k
 qt5-qtwebkit                              x86_64                   5.6.1-3.b889f46git.fc24                      updates                                 10 M
 qt5-qtxmlpatterns                         x86_64                   5.6.1-1.fc24                                 updates                                1.1 M
 xcb-util                                  x86_64                   0.4.0-5.fc24                                 fedora                                  20 k
 xcb-util-image                            x86_64                   0.4.0-5.fc24                                 fedora                                  19 k
 xcb-util-keysyms                          x86_64                   0.4.0-3.fc24                                 fedora                                  14 k
 xcb-util-renderutil                       x86_64                   0.3.9-6.fc24                                 fedora                                  17 k
 xcb-util-wm                               x86_64                   0.4.1-8.fc24                                 fedora                                  29 k
 xml-common                                noarch                   0.6.3-44.fc24                                fedora                                  31 k

Transaction Summary
==============================================================================================================================================================
Install  85 Packages

Total download size: 49 M
Installed size: 168 M
Is this ok [y/N]: 
...
Installed:
  aajohan-comfortaa-fonts.noarch 2.004-6.fc24         alsa-lib.x86_64 1.1.1-1.fc24                        avahi-libs.x86_64 0.6.32-4.fc24                    
  cairo.x86_64 1.14.6-2.fc24                          cdparanoia-libs.x86_64 10.2-21.fc24                 cups-libs.x86_64 1:2.1.4-2.fc24                    
  double-conversion.x86_64 2.0.1-7.fc24               fontconfig.x86_64 2.11.94-7.fc24                    fontpackages-filesystem.noarch 1.44-17.fc24        
  freetype.x86_64 2.6.3-2.fc24                        glx-utils.x86_64 8.3.0-3.fc24                       graphite2.x86_64 1.3.6-1.fc24                      
  gstreamer1.x86_64 1.8.3-1.fc24                      gstreamer1-plugins-base.x86_64 1.8.3-1.fc24         harfbuzz.x86_64 1.2.7-1.fc24                       
  hwdata.noarch 0.294-1.fc24                          iso-codes.noarch 3.68-1.fc24                        libICE.x86_64 1.0.9-5.fc24                         
  libSM.x86_64 1.2.2-4.fc24                           libX11.x86_64 1.6.3-3.fc24                          libX11-common.noarch 1.6.3-3.fc24                  
  libXau.x86_64 1.0.8-6.fc24                          libXcomposite.x86_64 0.4.4-8.fc24                   libXdamage.x86_64 1.1.4-8.fc24                     
  libXext.x86_64 1.3.3-4.fc24                         libXfixes.x86_64 5.0.3-1.fc24                       libXft.x86_64 2.3.2-4.fc24                         
  libXi.x86_64 1.7.8-2.fc24                           libXrender.x86_64 0.9.10-1.fc24                     libXv.x86_64 1.0.11-1.fc24                         
  libXxf86vm.x86_64 1.1.4-3.fc24                      libdatrie.x86_64 0.2.9-3.fc24                       libdrm.x86_64 2.4.73-1.fc24                        
  libevdev.x86_64 1.5.4-1.fc24                        libgudev.x86_64 230-3.fc24                          libicu.x86_64 56.1-5.fc24                          
  libinput.x86_64 1.5.1-1.fc24                        libjpeg-turbo.x86_64 1.5.0-4.fc24                   libmodman.x86_64 2.0.1-12.fc24                     
  libogg.x86_64 2:1.3.2-5.fc24                        libowncloudsync0.x86_64 2.2.4-1.3                   libpciaccess.x86_64 0.13.4-3.fc24                  
  libpng.x86_64 2:1.6.26-1.fc24                       libproxy.x86_64 0.4.12-3.fc24                       libqt5keychain1.x86_64 0.7.0-9.3                   
  libthai.x86_64 0.1.24-1.fc24                        libtheora.x86_64 1:1.1.1-14.fc24                    libvisual.x86_64 1:0.4.0-20.fc24                   
  libvorbis.x86_64 1:1.3.4-6.fc24                     libwacom.x86_64 0.21-1.fc24                         libwacom-data.noarch 0.21-1.fc24                   
  libwayland-client.x86_64 1.10.0-1.fc24              libwayland-server.x86_64 1.10.0-1.fc24              libwebp.x86_64 0.5.1-2.fc24                        
  libxcb.x86_64 1.11.1-2.fc24                         libxkbcommon-x11.x86_64 0.6.1-1.fc24                libxshmfence.x86_64 1.2-3.fc24                     
  libxslt.x86_64 1.1.28-12.fc24                       mesa-libEGL.x86_64 12.0.3-2.fc24                    mesa-libGL.x86_64 12.0.3-2.fc24                    
  mesa-libgbm.x86_64 12.0.3-2.fc24                    mesa-libglapi.x86_64 12.0.3-2.fc24                  mtdev.x86_64 1.1.5-6.fc24                          
  opus.x86_64 1.1.2-2.fc24                            orc.x86_64 0.4.26-1.fc24                            owncloud-client.x86_64 2.2.4-1.3                   
  owncloud-client-l10n.x86_64 2.2.4-1.3               pango.x86_64 1.40.3-1.fc24                          pixman.x86_64 0.34.0-2.fc24                        
  qt-settings.noarch 24-7.fc24                        qt5-qtbase.x86_64 5.6.1-3.fc24                      qt5-qtbase-common.noarch 5.6.1-3.fc24              
  qt5-qtbase-gui.x86_64 5.6.1-3.fc24                  qt5-qtdeclarative.x86_64 5.6.1-5.fc24               qt5-qtlocation.x86_64 5.6.1-2.fc24                 
  qt5-qtsensors.x86_64 5.6.1-2.fc24                   qt5-qtwebchannel.x86_64 5.6.1-2.fc24                qt5-qtwebkit.x86_64 5.6.1-3.b889f46git.fc24        
  qt5-qtxmlpatterns.x86_64 5.6.1-1.fc24               xcb-util.x86_64 0.4.0-5.fc24                        xcb-util-image.x86_64 0.4.0-5.fc24                 
  xcb-util-keysyms.x86_64 0.4.0-3.fc24                xcb-util-renderutil.x86_64 0.3.9-6.fc24             xcb-util-wm.x86_64 0.4.1-8.fc24                    
  xml-common.noarch 0.6.3-44.fc24                    

Complete!

</pre>

**Comment by jnweiger** [comment]
@tuxmaster please reopen if you still see this issue.

**Comment by tuxmaster** [comment]
It will still fails:
LANG=C dnf update
Last metadata expiration check: 0:24:22 ago on Fri Nov 25 13:33:04 2016.
Dependencies resolved.
=======================================================================================================================================================================
 Package                                        Arch                         Version                                  Repository                                  Size
=======================================================================================================================================================================
Installing:
 kernel                                         x86_64                       4.8.8-100.fc23                           updates                                     64 k
 kernel-core                                    x86_64                       4.8.8-100.fc23                           updates                                     20 M
 kernel-devel                                   x86_64                       4.8.8-100.fc23                           updates                                     11 M
 kernel-modules                                 x86_64                       4.8.8-100.fc23                           updates                                     22 M
 kernel-modules-extra                           x86_64                       4.8.8-100.fc23                           updates                                    2.1 M
Upgrading:
 bind99-libs                                    x86_64                       9.9.9-4.P4.fc23                          updates                                    664 k
 bind99-license                                 noarch                       9.9.9-4.P4.fc23                          updates                                     12 k
 ghostscript                                    x86_64                       9.20-5.fc23                              updates                                     45 k
 ghostscript-core                               x86_64                       9.20-5.fc23                              updates                                    4.5 M
 ghostscript-devel                              x86_64                       9.20-5.fc23                              updates                                     57 k
 ghostscript-x11                                x86_64                       9.20-5.fc23                              updates                                     73 k
 hwdata                                         noarch                       0.294-1.fc23                             updates                                    1.4 M
 kernel-headers                                 x86_64                       4.8.8-100.fc23                           updates                                    1.0 M
 kernel-tools                                   x86_64                       4.8.8-100.fc23                           updates                                    153 k
 kernel-tools-libs                              x86_64                       4.8.8-100.fc23                           updates                                     73 k
 libsndfile                                     x86_64                       1.0.27-1.fc23                            updates                                    186 k
 libsndfile-devel                               x86_64                       1.0.27-1.fc23                            updates                                    151 k
 mediawriter                                    x86_64                       4.0.7-0.fc23                             updates                                    2.7 M
 ntfs-3g                                        x86_64                       2:2016.2.22-3.fc23                       updates                                    307 k
 ntfsprogs                                      x86_64                       2:2016.2.22-3.fc23                       updates                                    339 k
 perl                                           x86_64                       4:5.22.2-355.fc23                        updates                                    6.9 M
 perl-Math-BigInt                               noarch                       1.9997-355.fc23                          updates                                    188 k
 perl-Time-Piece                                x86_64                       1.29-355.fc23                            updates                                     82 k
 perl-devel                                     x86_64                       4:5.22.2-355.fc23                        updates                                    551 k
 perl-libs                                      x86_64                       4:5.22.2-355.fc23                        updates                                    823 k
 perl-macros                                    x86_64                       4:5.22.2-355.fc23                        updates                                     57 k
 perl-open                                      noarch                       1.10-355.fc23                            updates                                     62 k
 python-perf                                    x86_64                       4.8.8-100.fc23                           updates                                    164 k
 sudo                                           x86_64                       1.8.18p1-1.fc23                          updates                                    725 k
Removing:
 kernel                                         x86_64                       4.7.8-100.fc23                           @updates                                     0  
 kernel-core                                    x86_64                       4.7.8-100.fc23                           @updates                                    52 M
 kernel-devel                                   x86_64                       4.7.8-100.fc23                           @updates                                    40 M
 kernel-modules                                 x86_64                       4.7.8-100.fc23                           @updates                                    21 M
 kernel-modules-extra                           x86_64                       4.7.8-100.fc23                           @updates                                   2.0 M
Skipping packages with broken dependencies:
 libowncloudsync0                               x86_64                       2.2.4-1.1                                isv_ownCloud_desktop                       403 k
 owncloud-client                                x86_64                       2.2.4-1.1                                isv_ownCloud_desktop                       1.0 M
 owncloud-client-l10n                           x86_64                       2.2.4-1.1                                isv_ownCloud_desktop                        13 k
 owncloud-client-nautilus                       x86_64                       2.2.4-1.1                                isv_ownCloud_desktop                        21 k

Transaction Summary
=======================================================================================================================================================================
Install   5 Packages
Upgrade  24 Packages
Remove    5 Packages
Skip      4 Packages

**Comment by jnweiger** [comment]
You have Fedora 23, my test was with Fedora 24.

**Comment by guruz** [comment]
https://owncloud.org/changelog/desktop/ 2.3 is out which might fix this
