### ISSUE TITLE
[2.2.4] Pause synchronization: Wrong UI in menus

### ISSUE THREAD

**Issue by armaccloud** [owncloud/client#5290]
When the tray icon menu of the owncloud client is used to pause a synchronization, the icon changes to indicate that the client has paused the sync, however in fact the sync is still running.
Using the option to pause the sync from within the application itself does work as it should (pause the sync)

### Expected behaviour
When the menu option (from the tray icon) pause synchronization is chosen, the synchronization is paused.

### Actual behaviour
When the menu option (from the tray icon) pause synchronization is chosen, the synchronization continues to run.

### Steps to reproduce
1. Place a large file in a synchronized folder on the Ubuntu desktop
2. Open `nethogs` and verify owncloud client is sending data
3. Choose the option `pause synchronization` from the tray icon menu
4. Verify in `nethogs` the data being sent doesn't drop

### Server configuration
Operating system:
Unknown (ocloud.de provider)

Web server:
Unknown (ocloud.de provider)

Database:
Unknown (ocloud.de provider)

PHP version:
Unknown (ocloud.de provider)

ownCloud version:
9

Storage backend (external storage):
Unknown (ocloud.de provider)

### Client configuration
Client version:
2.2.4

Operating system:
Ubuntu Desktop 16.04

OS language:
English

Installation path of client:
/usr/bin/owncloud

**Comment by ckamm** [comment]
I can reproduce the problem.

**Comment by SamuAlfageme** [comment]
@ckamm not happening anymore (tested w/ Ubuntu 16.10 + OC 2.3.0~nightly20161110) but the menubar dropdown is still displaying the words: `Syncing X MB (n minute(s) t second(s) left)` it'd be NtH something pointing that synchronization is paused. 

![dropdown_ubuntu](https://cloud.githubusercontent.com/assets/2644445/20171911/2053ef5c-a733-11e6-909c-b561abdc5972.png)

**Comment by SamuAlfageme** [comment]
And this was not only for Linux client: 

![sync_paused](https://cloud.githubusercontent.com/assets/2644445/20172568/ed36691c-a735-11e6-84fa-19b53ab89c3a.gif)

With the fix, OS X displays `Unknown status` on the menubar options (see comment above regarding Linux)

![cropped](https://cloud.githubusercontent.com/assets/2644445/20172653/3e38e7a4-a736-11e6-94b5-bd6be615d32e.png)

**Comment by ckamm** [comment]
@SamuAlfageme I'm a bit confused about how this ticket's focus changed. In the future, feel free to close and make a new ticket for a follow-up issue. 

So, the remaining problem in the "syncing" or "Unknown status" message in the context menu?

**Comment by SamuAlfageme** [comment]
@ckamm I removed the `bug` tag because I feel like the critical part of the issue was solved (pausing the sync now does pause the sync) and the `[LINUX]` part from the title as it doesn't involve only Linux OS. 

And yes, the only remaining issue is to clarify in the context menu which is **the state in which the client is left** after pausing the sync cause it's kind of confusing. I just commented in here as I guessed it's somehow closely related to this issue.

**Comment by ckamm** [comment]
@SamuAlfageme I've done a small change with which I can't reproduce the problem anymore. It now says "Up to date" which is also wrong, but that state display is wrong a lot. I'll make a separate ticket about it.

**Comment by SamuAlfageme** [comment]
@ckamm I was testing this again with multiple accounts and the `Pause all synchronization` option and it seems to be reproducing when more than one account is being synced at the same time (as one account is "waiting" for the other to be done downloading) it just pauses the active and causes the other to start downloading.

**Comment by ckamm** [comment]
@SamuAlfageme You're saying that you clicked "Pause all synchronization" and the current sync gets aborted and one that was in the queue gets started? That shouldn't happen, but I'll try to reproduce.

**Comment by ckamm** [comment]
@SamuAlfageme This is an actual bug in the folder scheduling logic, great catch! :)

**Comment by SamuAlfageme** [comment]
@ckamm working as expected now 👌. One small detail to consider if relevant is that the account that was being synced (not the one "waiting") is left in `SyncResult::Success` estate when pausing the download; while the other one appears "Paused".

![screen shot 2016-11-29 at 09 32 04](https://cloud.githubusercontent.com/assets/2644445/20702242/4e9ce48e-b617-11e6-91d8-50a8b7990eb8.png)

**Comment by ckamm** [comment]
@SamuAlfageme I addressed that issue.

**Comment by SamuAlfageme** [comment]
@ckamm 👍 working like a charm! Found #5341 while testing this and could be related.
