### ISSUE TITLE
Feature request: "Chunked" Downloads

### ISSUE THREAD

**Issue by marcos-guerrero** [owncloud/client#5292]
Chunked and parallel uploads are an amazing feature , the client avoids timeout the server with a unique and long request, and in case of failure of one o more chunks uploads the client only needs to repeat the upload of the failed chunks...
Why don't implement chunked (and parallel) downloads? Owncloud server functionality includes GET with Range headers ... so that feature could be used by the client, doing as many range requests as it needs to download the all the chunks of the file and put them together (as the server does) to obtain the file.
Again, the client would avoid a long and unique download (right now I can upload huge files but I cannot download them because of timeouts) and would be more resilient to slow/bad connections.

**Comment by guruz** [comment]
The client does resuming already, so in case of a bad connection (timeout, network change etc) it will just resume the file. :) It is better to just let it get as fast as possible with 1 connection.

The chunked download in this case makes only sense for things like https://github.com/owncloud/client/issues/230

**Comment by marcos-guerrero** [comment]
Oh! I didn't realize the client resumes the download... I tested with a 2Gb file on a slow server and maybe didn't wait enough to see the download complete instead the timeout error ... So is the client already using the Range header?

**Comment by marcos-guerrero** [comment]
Sorry, I tested again, yes, the client uses Range header to resume the download. But still ...  my server has a php timeout of 300 seconds. I can upload big files because the client chops the files in chunks and thus is able to upload them without errors... but on downloads the client shows timeout errors and  finally gets the entire file ... 
It would be great to configure (like the OWNCLOUD_CHUNK_SIZE enviroment variable) a OWNCLOUD_DOWNLOAD_CHUNK_SIZE to make the client to request (in sequence, no need to parallelize) the file in chunks. It would decrement the chances of timeout and disconnection errors.

**Comment by guruz** [comment]
@marcos-guerrero sorry, this is not normal and sounds like a configuration issue with your webserver.
You can get help here: https://central.owncloud.org
