### ISSUE TITLE
Documentation missing for client config file

### ISSUE THREAD

**Issue by marl-scot** [owncloud/client#5293]
The only documentation for the client config file is : 
https://doc.owncloud.org/desktop/2.2/advancedusage.html#configuration-file
This page shows 5 config options, and doesn't detail any of the [Accounts] section including the 'Folders', 'localPath', 'targetPath' and 'url' variables.
This makes it impossible to manually create/edit the config file.

Thaks

Marlscot

**Comment by guruz** [comment]
You are not supposed to :-)

What's your goal? Maybe there's a better way..

**Comment by ckamm** [comment]
@marl-scot How come you want to write a configuration file manually?

**Comment by SamuAlfageme** [comment]
There was [a discussion in central](https://central.owncloud.org/t/script-owncloud-client-for-mac/3473) open about this.

**Comment by marl-scot** [comment]
Hi ckamm / guruz,
Sorry for the late reply, basically I want to be able to pre-configure client configs so I don't have to remote into a clients machine and run through the same menus every time, it would be easier (in some cases) to be able to create a script on the server that just auto generates the config file, ready to be downloaded by the client, or (even better) could be included in a custom windows installer for that client.  That way, I can get a client to log into a secure area, enter there username/password etc, and they are then presented with a download customised just for them.
MarlScot

**Comment by guruz** [comment]
@marl-scot Hm.. I think some (or all?) of this might be possible via https://doc.owncloud.com/branded_clients/branded_desktop_client/branded_desktop_client.html or (if you're on Windows) the some Microsoft tools..

**Comment by settermjd** [comment]
@guruz & @ckamm - should the documentation be updated then?

**Comment by guruz** [comment]
@settermjd I don't think we should unless it's an officially supported way of (ab)using the client.

**Comment by settermjd** [comment]
@PVince81 @DeepDiver1975 @felixboehm what say you?

**Comment by PVince81** [comment]
@guruz @ogoffart @jvillafanez ^

**Comment by settermjd** [comment]
Any further update on this?

**Comment by guruz** [comment]
We don't support this

**Comment by settermjd** [comment]
Thanks for the clarification and closing the issue @guruz
