### ISSUE TITLE
doesn't remember window size of settings dialog

### ISSUE THREAD

**Issue by es20490446e** [owncloud/client#5296]
As reported [in Launchpad](https://bugs.launchpad.net/ubuntu/+source/unity/+bug/1638987):

HOW TO REPRODUCE:
1. Open the OwnCloud Client settings.
2. Resize the Window to the screen border.
3. Close the window and reopen it.

RESULT:
- The window size isn't the one from the previous opening.

RELEVANT DETAILS:
- Doesn't happen if you don't resize the Window to the point that the screen border becomes sticky. In that case the size is saved.
- Also affects Owncloud Client 2.2.4.

ProblemType: Bug
DistroRelease: Ubuntu 16.04
Package: owncloud-client 2.1.1+dfsg-1ubuntu1.1
ProcVersionSignature: Ubuntu 4.4.0-45.66-generic 4.4.21
Uname: Linux 4.4.0-45-generic x86_64
ApportVersion: 2.20.1-0ubuntu2.1
Architecture: amd64
CurrentDesktop: Unity
Date: Thu Nov  3 18:03:05 2016
InstallationDate: Installed on 2016-05-02 (185 days ago)
InstallationMedia: Ubuntu 16.04 LTS "Xenial Xerus" - Release amd64 (20160420.1)
SourcePackage: owncloud-client
UpgradeStatus: No upgrade log present (probably fresh install)

**Comment by ckamm** [comment]
This is probably Unity-specific, it didn't happen with Ubuntu 16.04 and KDE in my tests.

**Comment by es20490446e** [comment]
@ ckamm

Exactly, I just close the window.

**Comment by ckamm** [comment]
@es20490446e Unfortunately this is very likely to not be a bug in the application but rather something the window manager does. I just checked the settings window code, and didn't see anything related.

**Comment by es20490446e** [comment]
@ckamm 

So I have marked it downstream as affecting the Unity desktop environment. Thanks

**Comment by TheOneRing** [comment]
I assume the issue does not longer exists.
If it does please reopen.
