### ISSUE TITLE
Kaspersky Anti-virus deletes windows client based on suspicious behaviour

### ISSUE THREAD

**Issue by poVoq** [owncloud/client#5297]
### Expected behaviour
Own/Nextcloud client should not be detected as an application with virus like behaviour.

### Actual behaviour
Kaspersky Internet security is sometimes (but not consistently) detecting behavior (I think based on server side deletion of files) that makes it classify nextcloud.exe as a harmful application and delete it.

### Steps to reproduce
1. Install client and connect it to server with file activities on shared folders
2. Have Kaspersky Internet Security installed with automatic response
3. Nextcloud.exe gets deleted and deleted files restored by Kaspersky

### Server configuration
Operating system: Ubuntu 16.04

Web server: 
Apache2
Database:
MariaDB
PHP version:
7.0
ownCloud version:
Nextcloud 10
Storage backend (external storage):
none
### Client configuration
Client version:
2.2.4 (build2) with nextcloud theming
Operating system:
Winows 8.1
OS language:
English
Installation path of client:
programfiles (x86)
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
This is the ownCloud bugtracker, not the nextCloud bugtracker.

**Comment by poVoq** [comment]
Erm, technically its the same client (with different theming) and it should the owncloud client should be also effected by it.

**Comment by poVoq** [comment]
Erm, technically its the same client (with different theming) and it should the owncloud client should be also effected by it.

**Comment by poVoq** [comment]
Erm, technically its the same client (with different theming) and it should the owncloud client should be also effected by it.

**Comment by poVoq** [comment]
Erm, technically its the same client (with different theming) and it should the owncloud client should be also effected by it.

**Comment by RealRancor** [comment]
@poVoq Anyway, thats most likely something which needs to be fixed by the Kaspersky guys. They have a support page available here: https://support.kaspersky.com/ where you can report this issue in their product.
