### ISSUE TITLE
Folder Sync Connections - Please order alphabetically

### ISSUE THREAD

**Issue by julesmoretti** [owncloud/client#5299]
This is on the Mac OSX client app.

### Expected behaviour
After adding several "Folder Sync Connections" I should have those be organized alphabetically in the settings tab and on the top menu for the "Open folder ...".

### Actual behaviour
When adding several "Folder Sync Connections". Those are displayed in the order they were added but not alphabetically which is a bit of a burden. I have currently 8 folders and would love to have those ordered in an ascending manner.

### Steps to reproduce
1. Install the mac client app
2. Add a new server without specifying which folder
3. Then in the settings click on "Folder Sync Connection" and create several
4. You will see that those are not listed alphabetically

### Server configuration
Operating system:
OSX

**Comment by rperezb** [comment]
@SamuAlfageme let's start the show!
thx

**Comment by SamuAlfageme** [comment]
👍

**Comment by rperezb** [comment]
thanks!
