### ISSUE TITLE
Sync hard links

### ISSUE THREAD

**Issue by doits** [owncloud/client#530]
Being redirected from https://forum.owncloud.org/viewtopic.php?f=14&t=8697 to here.

Using owncloud client 1.2.3 on osx. I want to hard link some files into my owncloud folder, so I have them at two places (one inside owncloud sync folder, one outside). It looks like hard links are ignored by the sync client by default. An options to sync files hard linked would be nice.

**Comment by ogoffart** [comment]
owncloud client 2.0 will sync hard links

**Comment by aschiller2** [comment]
So hard links are now supported with owncloud client 2.0, but..

my scenario:
- "sourcefile" hello-world.txt somewhere on my system
- hard linked version of hello-world.txt in sync dir
- hello-world.txt is synced perfectly to oc server
- after editing hello-world.txt on oc server on another client who received it, hello-world.txt will be created as a new copy instead of replacing the hard linked hello-world.txt on my system.

I believe this is the wrong behaviour with hard links

**Comment by ogoffart** [comment]
Yes, we "break"  the links when the files are updated.

**Comment by aschiller2** [comment]
Why? I believe this is a not expected behaviour, because when I edit the (hard linked) file in my sync-dir the "source" changes too. (This is what hard links are for, I think)

**Comment by pierrejochem** [comment]
A hardlink isn't a pointer to a file, it's a directory entry (a file) pointing to the same inode. Even if you change the name of the other file, a hardlink still points to the file. If you replace the other file with a new version (by copying it), a hardlink will not point to the new file!

**Comment by aschiller2** [comment]
Correct. But why would i expect the file gets replaced when it gets synced with a new version while it gets changed when I'm editing it locally?

**Comment by phil-davis** [comment]
I wonder how the code can even know which is the "real file entry in folder1" and the "hard link file entry in folder2". The two should not be distinguishable - they are both just pointers in a folder to an inode.
So I guess if you create the "real" file inside your ownCloud client sync folder tree, and then make a hard link to it from somewhere else outside of the sync folder tree, the ownCloud client will not treat the "real" file like a "real" file either, and you will lose the hard-linking effect when an update comes from the server.
This seems rather odd - I would have thought that any file change/update that comes down from the server would rewrite the data blocks for the existing inode on the client side, and then the modification date... would update.

**Comment by ogoffart** [comment]
> when I edit the (hard linked) file in my sync-dir the "source" changes too. 

This depends on the editor. Many editor break the links as well.

**Comment by aschiller2** [comment]
> This depends on the editor. Many editor break the links as well.

ok.. so there is no chance that ownclouud client will behave like a "good" editor, ie. respecting links and not creating new files?

**Comment by phil-davis** [comment]
If an application does a file save by the process:
1) Save the file content to a new temp-named-file, e.g. abc.tmp
2) Delete the original file abc.txt
3) Rename (move) abc.tmp to abc.txt
then the hard link effect is lost.
If the application does a file truncate/rewrite in place then the hard link effect is preserved.
So I guess it is application-specific behaviour.

**Comment by aschiller2** [comment]
I see..

But which is a "good" or expected behaviour?

> This seems rather odd - I would have thought that any file change/update that comes down from the server would rewrite the data blocks for the existing inode on the client side, and then the modification date... would update.

so would I think.

But you're right it is application-specific:
- nano behaves "good"
- vi behaves "good"
- gedit does not
- geany does
- Libreoffice (Writer) does
- Owncloud Client does not (ok, this was a little provocing ;-))

(while "good" means it replaces the contents)

**Comment by phil-davis** [comment]
For an app like ownCloud that will be downloading big files and the connection is regularly interrupted and... I can see that it is useful to get the chunks of the file, put it all together in a temporary file on the client all ready to go, then do the file name switch at the very end, which is a quick and somewhat atomic operation. I guess that is one reason for the current behaviour.

**Comment by juangamnik** [comment]
What about files that have all their hardlinks in the sync-folder? Do they break after a change, too?

My use case is as follows: ownCloud AFAIK does not support macOS tags, so I would like to have tag-folders in my ownCloud folder and hardlink the files from their "normal" place to all tag-folders they belong to. But after changing the file in its normal place  on any synced machine and update it on any other machine, the links should still be in place. Braking the link in this situation would make it unusable for tagging.

Or is there support for macOS tags now?
