### ISSUE TITLE
"Recent Changes" menu shows duplicate entries

### ISSUE THREAD

**Issue by jmdeboer-surfsara** [owncloud/client#5301]
The 'Recent Changes' menu in the desktop client shows duplicate entries.

This happens on OSX, Windows and Ubuntu Linux. Client version is 2.2.4, but it also happens in 2.2.2.
After clicking on 'Details', the client opens on the 'Sync protocol' or 'Activity' tab (depending on whether or not the activity app is enabled). Here the items are _not_ duplicated.

From doing some testing, it appears to be related to how deep a file is nested; it does not seem to happen with files in the root, and the deeper a file is nested, the more often the line is duplicated. However that is not 100% consistent. I have not seen duplicates at the root level, but I cannot guarantee it never happens...

### Expected behaviour
Each action should be listed once

### Actual behaviour
Actions are listed once, twice or even four times.

### Steps to reproduce
1. Fire up the client
2. Perform some actions
3. Look at 'Recent changes'

### Server configuration

I tried this using our 8.2.8 enterprise install, but also against the 9.1.1 enterprise trail version downloaded as a VirtualBox image; so I am assuming this is purely a client-side issue.
 
![recent changes](https://cloud.githubusercontent.com/assets/23337494/20102516/a8a13f0e-a5c6-11e6-8b86-c9da7513ce5a.png)

**Comment by michaelstingl** [comment]
@jmdeboer-surfsara Might be related / a duplicate: https://github.com/owncloud/client/issues/5256

The strange thing: With the latest changes in the master branch, it isn't reproducible.

**Comment by CorneelDragon** [comment]
@michaelstingl  have they tried with nesting? As Jean-Marie points out: when you change files in root, there is only one entry.

**Comment by jmdeboer-surfsara** [comment]
@michaelstingl Yes, looks to be the same issue; since the other ticket was in status 'closed', I overlooked it.

**Comment by michaelstingl** [comment]
@CorneelDragon @jmdeboer-surfsara You could test with the latest builds from https://download.owncloud.com/desktop/daily/ . (perhaps wait for tomorrow)

**Comment by ckamm** [comment]
@CorneelDragon @michaelstingl This was a bug in 2.2.4 (and possibly earlier) that was fixed for master (will be 2.3.0) in #5256. I have attempted to reproduce this again using nested files, like suggested here, but everything looks good to me in master. 

If you can trigger this problem in the current daily builds, please describe how.

**Comment by jmdeboer-surfsara** [comment]
I confirm the issue does not appear in the current daily build.

**Comment by michaelstingl** [comment]
@jmdeboer-surfsara Awesome. Thanks for your help!
