### ISSUE TITLE
[2.2.4] [Linux] [Nautilus] [Nemo] File Manager refresh only working after restarting oC once

### ISSUE THREAD

**Issue by joaoherberto** [owncloud/client#5302]
**Steps to reproduce**
1.Install owncloud Client in any Linux Distro and log into your account and set your sync folders.
2.open file manager and download/copy a file to an open File Manager window, contents should refresh.
3.Quit Owncloud Client, repeat test, contents refresh as expected.

**Expected behaviour**
Contents of File Manager window should refresh without manual intervention.

**Actual behaviour**
Must move from current directory and back for files/folders to appear.

### Server configuration
Operating system: Centos
Web server:cPanel/Apache2.4
Database:MariaDB 10
PHP version:7.0
ownCloud version (see ownCloud admin page):9.1.1
Updated from an older ownCloud or fresh install:Updated from Previous

### Client configuration
**Client version:** 2.2.4

**Operating system:** Manjaro Linux, (Cinnamon) - Also tried in Fedora 23 -Gnome Same results.

**OS language:** English

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
Do you mean the icons do not refresh in the file manager?

**Comment by joaoherberto** [comment]
Yes, if you have the file manager open to the directory "Downloads", and you download a file from the web, as an example, to the Downloads directory, it does not show up. You must move to a different directory and then back for it to show up. If you quit Owncloud Client, and repeat all is well.  This happens in Nautilus and Memo file managers.

**Comment by ckamm** [comment]
@joaoherberto So far I can't reproduce, here's what I tried:
* Open nautilus on an ownCloud folder, ensure there are overlay icons.
* In a shell, create a new file in that folder.
* The file appears in nautilus without manual intervention.

But I worry that even if I could reproduce the problem there would be little we could do. The plugin API doesn't allow us to do things significantly differently from the way they are already being done.

**Comment by joaoherberto** [comment]
@ckamm, I just read your post, went to my computer, started OC Client, and tested... everything worked fine! That is interesting, I never thought of restarting owncloud to see if the issue was still there. I restarted my computer and waited for everything to load. Sure enough, the file manager did not refresh. I quit OC client and everything works. But if you restart OC client, everything works fine. So it is only on initial boot (it is set to autostart). I decided to add a 15 second delay to the autostart entry with no effect.
I created a screencast of the issue, watch/dowload here: [https://dl.dropboxusercontent.com/u/100301597/filemanagerissue.webm](https://dl.dropboxusercontent.com/u/100301597/filemanagerissue.webm)
I hope this helps, at least now I have a temporary workaround... Let me know if there is anything I can help with.

Joao

**Comment by ckamm** [comment]
@joaoherberto You're saying that the automatic refresh works when you disable the client's autostart. And then it breaks when you start the client the first time?

I'm wondering whether the problem is unrelated to the client - but if you can break the refresh by starting the client, that's evidence against it.

**Comment by joaoherberto** [comment]
@ckamm No, I verified Autostart has no affect on the issue. The issue is only there on the first initial start of ownCloud client. Closing the client and restarting seems to fix the issue.

**Comment by ckamm** [comment]
@joaoherberto Thanks for the clarification. I'll try to reproduce, but it's really unlikely we'll be able to do something about this issue.

**Comment by joaoherberto** [comment]
@ckamm It appears to be isolated to Cinnamon and Gnome desktops only, I just tried it in Manjaro XFCE and issue does not manifest itself. I even tried installing Nautilus-filemanager and it worked just fine. 

Very odd...

Joao
