### ISSUE TITLE
Latest Release Version on Github

### ISSUE THREAD

**Issue by julesmoretti** [owncloud/client#5303]
Could we have the last release version number displayed on github's readme. Since you seem to be working on 2.3.0 but I currently have 2.2.4.

Ideally some sort of notification to alert when there is a new version on the client side.

This is for Mac OSX.

Thank you.

**Comment by guruz** [comment]
We're working on 2.3.0 which is not released :)

So 2.2.4 is the current release. If you want something more bleeding edge try the nightly builds.
https://owncloud.org/install/#testing-development
