### ISSUE TITLE
Desktop client allows to add the same account multiple times

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5305]
### Expected behaviour
An account (user@server combination) should be only added once in the same desktop client.

### Actual behaviour
The client allows to input the same url address **and user** (different users should be fine) multiple times. Resulting in duplicate entries on the "Activity" tab, account tabs ... 

![duplicated accounts](http://i.imgur.com/XIbYZpA.png)

And menu bar dropdown:

![menu dropdown](http://i.imgur.com/pbEpZn8.png)

### Steps to reproduce
1. Open the desktop client and add an account
2. Skip the rest of the config 
3. On the client, select: Settings > Account > Add new
4. Add the same server and credentials from step 1

### Server configuration
Operating system:
CentOS 6.6

Web server: 
Apache

Database:
MySQL

PHP version: 
5.6

ownCloud version: 
9.1.2 Enterprise

Storage backend (external storage):
No

### Client configuration
Client version:
2.3.0.3806-nightly20161109 (build 3806)

Operating system:
OS X 10.11.6

OS language:
English

Installation path of client: 
`/Applications/owncloud.app`

**Comment by guruz** [comment]
I think this is by design. It used to be forbidden but now is allowed.

**Comment by TDannhauer** [comment]
It should be allowed. 
It is not allowed to sync the root node and additionally only a subfolder in a second sync folder setup. The recommendation for this setup is to setup the same account twice - so it must be allowed.

**Comment by hodyroff** [comment]
Lets keep it for now the way it is. Obviously if a user does this, there is an easy workaround. ownBrander (part of Enterprise) allows to create branded clients which only allow one account.

**Comment by SamuAlfageme** [comment]
> It is not allowed to sync the root node and additionally only a subfolder in a second sync folder setup.

After https://github.com/owncloud/client/pull/6032 we can now sync the root `owncloud/` folder multiple times per account. Might be worth looking at this again.
