### ISSUE TITLE
Open folder from activity tab

### ISSUE THREAD

**Issue by mafigo** [owncloud/client#5306]
If you have an error, or a conflicting file, it would be nice to be able to open the respective folder from the activity tab. Has is you have to memorize the path to the file and then navigate to it outside the client.

A simple double click, or any other shortcut +click would be a nice addition.

**Comment by guruz** [comment]
I thought @ckamm or @dragotin had implemented this. But maybe that was only for uploads/downloads where the file name is existing. Or so.

**Comment by mafigo** [comment]
Yes it is working, on Sync Protocol, and on Server Activity, but is not working on Not Synced.

**Comment by ckamm** [comment]
Sounds like a good idea, I'll look into it.

**Comment by SamuAlfageme** [comment]
👍 awesome!

**Comment by SamuAlfageme** [comment]
@ckamm I think there's some debugging message being printed out on STDOUT/ERR when clicking the entry on the activity tab:

![msj](https://user-images.githubusercontent.com/2644445/29167759-fdf34afa-7dcb-11e7-9042-0ede175931a9.gif)

Can you take a look?
