### ISSUE TITLE
[Budige Remix PPA] Tray icon not showing up

### ISSUE THREAD

**Issue by freakyy85** [owncloud/client#5311]
### Expected behaviour
Tray icon of owncloud should show up in tray

### Actual behaviour
Icon doesnt show up.

### Steps to reproduce
1. install budgie remix from ppa
2. have owncloud installed (or reinstall after)

### Server configuration
Operating system:
Ubuntu-Gnome with Budige Remix PPA

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:
uwe@schleppi:~$ owncloud --version
ownCloud version 2.2.4
Using Qt 4.8.7
uwe@schleppi:~$ 

Operating system:

OS language:

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
Wont paste this as it contains sensitive data.

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by freakyy85** [comment]
Ok, with the app indicator applet it works - owncloud shows up - but not in the normal system tray and other programs show up there, like discord. can you please make it so owncloud shows up there too, without having to add a not good looking additional applet which even seperates the owncloud icon from other icons?

**Comment by guruz** [comment]
Which exact ownCloud package did you use?

I think you should submit these kind of bugs at your distro/WM/whatever, they can help you better.

**Comment by freakyy85** [comment]
we@schleppi:~$ apt-cache policy owncloud-client
owncloud-client:
  Installiert:           2.2.4-1.1
  Installationskandidat: 2.2.4-1.1
  Versionstabelle:
 *** 2.2.4-1.1 500
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.10  Packages
        100 /var/lib/dpkg/status
     2.2.2+dfsg-1 500
        500 http://de.archive.ubuntu.com/ubuntu yakkety/universe amd64 Packages
uwe@schleppi:~$

**Comment by fmoc** [comment]
Issue has not seen activity in many years. I think we can assume it has been resolved in the meantime. If not, please don't hesitate to reopen.
