### ISSUE TITLE
[Windows] [2.2.4 build 6408] does not re-include unavailable local sync folders when they are available again.

### ISSUE THREAD

**Issue by TDannhauer** [owncloud/client#5317]
### Expected behaviour
After adding a folder sync to a removable drive (e.g. stick or Veracrypt container), the client complains after system boot:  It marks the unaccessible folder with a read cross and says "Unable to find local sync folder."

After making the missing folder accessible, ( e.g. mounting the encrypted device), the missing folder should be re-evaluated (time or event based) by the OC client and included into sync activities as soon as it is available again. 

This would make it convenient to setup local sync folders on encrypted devices. 

### Actual behaviour
However, after making the missing folder accessible, ( e.g. mounting the encrypted device) does not re-enable syncronisation for that folder. Only manually pausing and resuming sync triggers the OC client to re-evaluate the folder, to find it and to re-enable its synchronisation.

### Steps to reproduce
1. 
Setup a folder syncronisation on a accessible removable drive (like a Truecrypt/veracrypt container)
2. 
Make drive unaccessible at bootup.
3. 
Setup Owncloud Client to auto start at user login
4.
Reboot system
5. 
Look at Owncloud client: It marks the unaccessible folder with a read cross and says "Unable to find local sync folder."
6.
Make folder accessible again, e.g. by mounting it in Veracrypt
7. 
Look at Owncloud client: It still marks the unaccessible folder with a read cross and says "Unable to find local sync folder.".
8.
Pause sync for that folder manually.
9.
Resume sync for that folder manually.
10.
Look at Owncloud client: It now finds the accessible folder and re-enables sync for that folder.

### Server configuration
Operating system:
Debian Jessie

Web server: 
Apache 2.4.10

Database:
Postgres 9.3

PHP version:
PHP-FPM 5.6.27

ownCloud version:
9.1.2

Storage backend (external storage):
none

### Client configuration
Client version:
2.2.4 build 6408

Operating system:
Win10 64 bit

OS language:
DE

Installation path of client:
C:\Program Files (x86)\ownCloud

**Comment by SamuAlfageme** [comment]
It's not reproducing in Windows 7/10. The folder is automatically found, no need to Pause/Resume the sync. It just takes a bit (<20s) to be found and synced again.

**Comment by TDannhauer** [comment]
Have you used veracrypt with a encrypted container to reproduce? Are you usi g Win10 1607 64 bit?

I waited 120 min and it highly reproducable. Should i make a screen video?

Torben

Von unterwegs gesendet
Sent from mobile

**Comment by SamuAlfageme** [comment]
@TDannhauer yup, followed every step. The thing is, I was trying to reproduce it unsuccessfully right after windows restarting and the client launch: [look at this video](https://webmshare.com/play/7QDLe)).

But you are right, some time after the OS startup, the client is not checking if the folder is available anymore. **I'm reopening to keep that availability check open**. Appending this [logfile](https://gist.githubusercontent.com/SamuAlfageme/d63a256201f9d9509caf138b33ddf838/raw/f854c2ca58975ec6c9b1e323b917989262d5e1a9/gistfile1.txt) here describing what's happening after adding that folder some time after the startup.

**Comment by TDannhauer** [comment]
Great, thanks for your investigation!

**Comment by ckamm** [comment]
Looking at it briefly, I see two issues:
* When the sync fails with the "Unable to find local sync folder" message, the sync isn't retried with a short interval. It probably is retried when the long-sync period expires, but that takes several hours.
* Even when a sync is triggered (though pause/unpause or force-sync/F6), the folder watchers aren't set up. And thus the folder isn't watched for local changes from then on.

**Comment by ckamm** [comment]
Work in progress branch for these issues: https://github.com/ckamm/owncloud-client/tree/late_local_folder_5317

**Comment by ckamm** [comment]
Pull request: #5381

I think there are several issues with "temporarily unavailable" sync folders (folder watchers, potentially sync journal db access) that are not yet solved. This is just the first step towards making that work.

**Comment by guruz** [comment]
@TDannhauer Would you want to try a 2.3 nightly build? http://download.owncloud.com/desktop/daily/ownCloud-2.3.0.6613-nightly20170105-setup.exe

**Comment by TDannhauer** [comment]
Great! Will do that! Is it sufficient this evening CET?

 

Many Thanks,

Torben

 

Von: Markus Goetz [mailto:notifications@github.com] 
Gesendet: Donnerstag, 5. Januar 2017 13:13
An: owncloud/client <client@noreply.github.com>
Cc: Torben Dannhauer <torben@dannhauer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [owncloud/client] [Windows] [2.2.4 build 6408] does not re-include unavailable local sync folders when they are available again. (#5317)

 

@TDannhauer <https://github.com/TDannhauer>  Would you want to try a 2.3 nightly build? http://download.owncloud.com/desktop/daily/ownCloud-2.3.0.6613-nightly20170105-setup.exe

**Comment by guruz** [comment]
Sure :)

**Comment by TDannhauer** [comment]
The installer asks me to uninstall the older version. Does this erase my stored sync settings? Or can I simple install it over the old version without previous uninstall of the old client?

 

My goal is to save my preferences to avoid a full re-setup of all syncing settings.

 

Thanks,

Torben

 

Von: Markus Goetz [mailto:notifications@github.com] 
Gesendet: Donnerstag, 5. Januar 2017 13:13
An: owncloud/client <client@noreply.github.com>
Cc: Torben Dannhauer <torben@dannhauer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [owncloud/client] [Windows] [2.2.4 build 6408] does not re-include unavailable local sync folders when they are available again. (#5317)

 

@TDannhauer <https://github.com/TDannhauer>  Would you want to try a 2.3 nightly build? http://download.owncloud.com/desktop/daily/ownCloud-2.3.0.6613-nightly20170105-setup.exe

**Comment by guruz** [comment]
@TDannhauer You can install over the old version, the uninstaller won't remove settings

**Comment by TDannhauer** [comment]
Hi, works as expected, adds encrypted local folders as soon as they are made available – great!

 

Thanks,

Torben

 

Von: Markus Goetz [mailto:notifications@github.com] 
Gesendet: Donnerstag, 5. Januar 2017 14:56
An: owncloud/client <client@noreply.github.com>
Cc: Torben Dannhauer <torben@dannhauer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [owncloud/client] [Windows] [2.2.4 build 6408] does not re-include unavailable local sync folders when they are available again. (#5317)

 

@TDannhauer <https://github.com/TDannhauer>  You can install over the old version, the uninstaller won't remove settings

**Comment by SamuAlfageme** [comment]
👍

**Comment by Challado** [comment]
Hello Friends. 
These bug has appeared again. On earlier versions of owncloud all works fine, but now I need to remount unit in veracrypt and close/open owncloud to start sync volume again.
