### ISSUE TITLE
404 on Ubuntu 16.04 packages

### ISSUE THREAD

**Issue by detly** [owncloud/client#5320]
Trying to install the OwnCloud client packages for Ubuntu 16.04 via Synaptic or `apt-get` fails with a 404 error. This can be confirmed by trying to visit the link to one of the packages in a browser, eg. http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/./all/owncloud-client-l10n_2.2.4-1.3_all.deb

Note that the directory listing at http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/./all/ shows the package as present, but clicking on the link to it or using the full URL above redirects to https://ftp.gwdg.de/pub/opensuse/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/all/owncloud-client-l10n_2.2.4-1.3_all.deb which is missing.

The problem seems to be that there are no Ubuntu directories under https://ftp.gwdg.de/pub/opensuse/repositories/isv%3A/ownCloud%3A/desktop/

**Comment by Kawohl** [comment]
@detly did you try from the official repo: 

https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client
?

This works fine for me and i cannot reproduce.

**Comment by detly** [comment]
@Kawohl Yes, I am using that repo and still getting 404s. Do the links I posted for you work?

**Comment by detly** [comment]
Immediately after `sudo apt-get update` I do:

```text
$ sudo apt-get install owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages were automatically installed and are no longer required:
  libcuda1-361 linux-headers-4.4.0-42 linux-headers-4.4.0-42-generic linux-headers-4.4.0-43
  linux-headers-4.4.0-43-generic linux-image-4.4.0-42-generic linux-image-4.4.0-43-generic
  linux-image-extra-4.4.0-42-generic linux-image-extra-4.4.0-43-generic linux-signed-image-4.4.0-42-generic
  linux-signed-image-4.4.0-43-generic nvidia-opencl-icd-361
Use 'sudo apt autoremove' to remove them.
The following additional packages will be installed:
  libowncloudsync0 libqt5keychain1 owncloud-client-l10n
The following NEW packages will be installed:
  libowncloudsync0 libqt5keychain1 owncloud-client owncloud-client-l10n
0 to upgrade, 4 to newly install, 0 to remove and 0 not to upgrade.
Need to get 1,713 kB of archives.
After this operation, 6,627 kB of additional disk space will be used.
Do you want to continue? [Y/n] Y
Err:1 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  libqt5keychain1 0.7.0-9.4
  404  Not Found
Err:2 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  libowncloudsync0 2.2.4-1.3
  404  Not Found
Err:3 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  owncloud-client-l10n 2.2.4-1.3
  404  Not Found
Err:4 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  owncloud-client 2.2.4-1.3
  404  Not Found
N: Ignoring file '20auto-upgrades.ucf-old' in directory '/etc/apt/apt.conf.d/' as it has an invalid filename extension
E: Failed to fetch http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/./amd64/libqt5keychain1_0.7.0-9.4_amd64.deb 404  Not Found

E: Failed to fetch http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/./amd64/libowncloudsync0_2.2.4-1.3_amd64.deb 404  Not Found

E: Failed to fetch http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/./all/owncloud-client-l10n_2.2.4-1.3_all.deb 404  Not Found

E: Failed to fetch http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/./amd64/owncloud-client_2.2.4-1.3_amd64.deb 404  Not Found

E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
```

**Comment by Kawohl** [comment]
sorry i just checked the .deb seems to throw 404.s 
@crrodriguez @jnweiger could help probably.

using the script on the page before works  it is just the deb that is missing somehow.

**Comment by Kawohl** [comment]
hmm that is akward would you mind showing the content of etc/apt/sources.list.d/owncloud-client.list?

**Comment by Kawohl** [comment]
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/
works (again)

**Comment by detly** [comment]
@Kawohl sure thing:

```text
~ • cat /etc/apt/sources.list.d/owncloud-client.list 
deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/ /
```

**Comment by detly** [comment]
@Kawohl That link works, but the problem is the files themselves redirect to the `ftp.gwdg.de` site, where they don't exist.

**Comment by Kawohl** [comment]
that is weird behaviour. i mentionend @crrodriguez before i hope he can fix that soon. Did you import the keys?

**Comment by detly** [comment]
@Kawohl yep.

**Comment by Kawohl** [comment]
sorry that i can't be of any help right now....

**Comment by detly** [comment]
@Kawohl Heh, that's fine, I'm not in any rush. It could be a temporary problem (eg. currently syncing repos) but I figured I'd flag it just in case it wasn't.

**Comment by Kawohl** [comment]
Yeah thanks for reporting!

**Comment by detly** [comment]
Are there any mirrors I could use? I'd like to try out OC at some point, but I can't without the desktop clients.

**Comment by Kawohl** [comment]
@crrodriguez 

please fix !

**Comment by jnweiger** [comment]
I've escalated this to gwdg support. Quick response and fix there.  @detly please try again.
<pre>
Dear Jürgen Weigert,

> https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adesktop&package=owncloud-client
>
> redirects me to your site. Packages for older distos are three, but not 
> the newer ones. E.g. this one is missing:
>
> http://ftp.gwdg.de/pub/opensuse/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/amd64/owncloud-client_2.2.4-1.3_amd64.deb

we had some problems with the sync of opensuse/repositories and we are in dialog with the SUSE team to solve this. The problems arose, when we switched to a completely new FTP-Server.

For now we have resynchronized the data from the old server to the new one. This may lead to older files, but we will have soon solved the sync problems with SUSE, too.

Best regards

Tim Ehlers
</pre>

**Comment by detly** [comment]
:+1:
