### ISSUE TITLE
Ubuntu 16.04 installation package has missing dependencies

### ISSUE THREAD

**Issue by linufix** [owncloud/client#5323]
After installing the LAMP - Stack I installed ownCloud from this repository
http://download.owncloud.org/download/repositories/stable/Ubuntu_16.04/

### Expected behaviour
After installation and entering: localhost/owncloud
in my browser, the configuration for owncloud should show up

### Actual behaviour
PHP code was not executed, but printed in the browsers window instead

### Steps to reproduce
After issuing the command:
sudo apt-get install php libapache2-mod-php
the missing packages have been installed and the behaviour was as expected.

### Server configuration
Operating system: Kubuntu 16.04 LTS

Web server: Apache2

Database: MySQL

PHP version: 7.0

ownCloud version: 9.1

Storage backend (external storage):

### Client configuration
same computer localhost

**Comment by guruz** [comment]
Please try support via https://central.owncloud.org/ or https://owncloud.org/support/
