### ISSUE TITLE
[2.3.1] Check crash reporter for important crashes

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5329]

**Comment by ogoffart** [comment]
Some fixes:  https://github.com/owncloud/client/pull/5343

**Comment by guruz** [comment]
Thanks!
Close here?

**Comment by ogoffart** [comment]
we need to check again with the beta.

**Comment by ogoffart** [comment]
In 2.3 beta1, there is a frequent crash in PropagateDirectory::slotSubJobFinished.  I hope that 1cec2ca13dc35aba6aaf79f42bde9a6dd00143a7 fixes it because of the s/reset/take/

**Comment by guruz** [comment]
AFAIK @jturcotte and @ogoffart are discussing this on IRC and plan to put the fix in 2.3 too?

**Comment by guruz** [comment]
@ogoffart Check again and close issue?
