### ISSUE TITLE
[Placeholder] Make sure we can parse test cookies

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5330]
https://github.com/owncloud/core/issues/26651

**Comment by guruz** [comment]
@PVince81 @ogoffart @PhilippSchaffrath If this really creates too much sessions on the server I think we should do a workaround in the client too for old server versions?

**Comment by PVince81** [comment]
When I talked with @ogoffart he said the cookie is ignored because the specific cookie path doesn't match. So it's likely that the server side needs to be fixed to specify the correct path.

**Comment by guruz** [comment]
@PVince81 Yes but that does not mean that we can't work around this by doing some manual magic when cookie parsing.
If you tell us it makes sense performance wise?

**Comment by PVince81** [comment]
I don't think the client needs workarounds but the server needs fixing.

But first let's see if the fix works once it's there.

**Comment by ogoffart** [comment]
The client is behaving properly.   The problem is the path in the test cookie.
