### ISSUE TITLE
Fedora 23 repo

### ISSUE THREAD

**Issue by apeyser** [owncloud/client#5334]
# Fedora 23 Repository update

dnf update -b

Error: nothing provides opt-qt5-qtwebkit needed by owncloud-client-2.2.4-1.1.x86_64.
nothing provides opt-qt5-qtwebkit needed by owncloud-client-2.2.4-1.1.x86_64.
nothing provides opt-qt5-qtwebkit needed by owncloud-client-2.2.4-1.1.x86_64
(try to add '--allowerasing' to command line to replace conflicting packages)

cat /etc/yum.repos.d/isv\:ownCloud\:desktop.repo
[isv_ownCloud_desktop]
name=The ownCloud Desktop Client (Fedora_23)
type=rpm-md
baseurl=http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Fedora_23/
gpgcheck=1
gpgkey=http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Fedora_23//repodata/repomd.xml.key
enabled=1

See #4400

**Comment by jnweiger** [comment]
Is this perhaps an update-only issue? I've made several flawless fresh installs with fedora23.

**Comment by apeyser** [comment]
@jnweiger: recently?

I downloaded the srpm and find:
Requires:       %{qtprefix}qt5-qtwebkit

which appears to be turned on for fedora23, with qtprefix set top opt, which implies using the owncloud version rather than the fedora23 repository version.

Thus I don't see how the package can be installed without the owncloud repository making opt-qt5-qtwebkit available. And I don't see the package available in isv_ownCloud_desktop.

Maybe you've cached it locally somewhere? Is the repository under version control to see whether the package was in the repo historically and has disappeared?

**Comment by jnweiger** [comment]
Ah, I got owncloud-client-2.2.2-1.fc23 from Fedora Updates....

**Comment by crrodriguez** [comment]
Since other  opt-qt5-* packages are published for Fedora 23, I will assume qt5webkit not been published is an error that I just corrected. if there is a reason for the package not to be present there on purpose please reopen this ticket. thanks.

**Comment by jnweiger** [comment]
@crrodriguez thanks!
