### ISSUE TITLE
Tray icon blink on lxde

### ISSUE THREAD

**Issue by matbonucci** [owncloud/client#5338]
The icon blinks every now and then and it drives me crazy

### Expected behaviour
The icon should remain static

### Actual behaviour
The tray icon blink like every 5 minutes

### Steps to reproduce
1. Install owncloud client on lxde
2. Sync your account
3. Run it

### Server configuration
Operating system: 
Web server: 
Database:

PHP version:

ownCloud version: 8.0.10

Storage backend (external storage):

### Client configuration
Client version: 2.2.4

Operating system: Lubuntu 16.04

OS language: Spanish

Installation path of client: /usr/bin/owncloud /usr/share/owncloud

**Comment by guruz** [comment]
You could try a 2.3 nightly build. We had some changes there.
https://owncloud.org/install/#testing-development

**Comment by SamuAlfageme** [comment]
Tested in Lubuntu 16.04 with sync client version 2.3.0nightly20161115 (build 2024) and It's not reproducing (had the screen recorded for 10 minutes, played at 5x speed and didn't see the icon blinking)

**Comment by matbonucci** [comment]
@guruz thank you that solved my problem
