### ISSUE TITLE
Option `--confdir` not added to Autostart config

### ISSUE THREAD

**Issue by klada** [owncloud/client#5339]
When launching the OwnCloud client with `--confdir` it creates the wrong Autostart config. The command line switch should also be appended to the OwnCloud binary when generating the Autostart config.

### Expected behaviour

1. Start OwnCloud with `/path/to/owncloud.exe --confdir %APPDATA%\custom.ownCloud\`

2. Configure client and enable Autostart

3. The full path to the client binary, including the `--confdir %APPDATA%/ownCloud/` should be stored in `HKCU\Software\Microsoft\Windows\CurrentVersion\Run\ownCloud` (or whereever the autostart config is stored on other platforms).

### Actual behaviour

When starting the client with `--confdir %APPDATA%/ownCloud/`  this config is omitted when creating Autostart entries.

**Comment by ckamm** [comment]
Note that we want to generate the command line from the arguments that were parsed. Simply forwarding the command line arguments is not going to work if they contain relative paths.

**Comment by hodyroff** [comment]
@ckamm sounds like you do suggest this is not a bug, but a different command should be used?

**Comment by ckamm** [comment]
@hodyroff No, I'm saying that forwarding the arguments that were passed to the owncloud binary to the autostart entry verbatim is not going to work, getting this right is not complicated but needs a bunch of work.

This is a low-severity issue: Users who need the client started with specific command line arguments are probably savy enough to set up autostart for themselves. The client could be nice and not set up autostart if it was started with command line arguments, or at least tell the user that what's happening is probably not what they want.

**Comment by TheOneRing** [comment]
--confdir was removed https://github.com/owncloud/client/issues/11142
