### ISSUE TITLE
Backup Detected message contains a typo

### ISSUE THREAD

**Issue by linucksrox** [owncloud/client#5347]
The Backup Detected message says "This sync would reset the files to an erlier time..."
it should be "earlier". This affects the newest client on Windows, and I believe it also affects the Linux version but I haven't tested that.

**Comment by SamuAlfageme** [comment]
This has already been fixed https://github.com/owncloud/client/commit/7f0cc5b699dfbe41e218c64c0dade0b8fb08c6fc (you can test it in the current 2.3 development version: https://owncloud.org/install/#testing-development)
