### ISSUE TITLE
No synchronization on folder's with colons in the name

### ISSUE THREAD

**Issue by Ascendor** [owncloud/client#5351]
If you create a folder on the owncloud website containing a colon (":"), it will not be synchronized to the client's PC.

### Expected behaviour
Multiple possible solutions:

- The folder from the server should be downloaded to the client's PC (with exchanged characters)
- An error message should be displayed on the client
- it  should be impossible to create such folders at all

### Actual behaviour
The folder is ignored.

### Steps to reproduce

1. Create a folder via owncloud web, include a colon into the name
2. Start owncloud client connected to the instance, see that the folder is not being synchronized
3. Rename the folder, removing all colons
4. Restart the owncloud client, observe that the folder is being downloaded

### Server configuration
Operating system: Debian Linux 7.11

Web server: Apache/2.2.22 (Debian)

Database: mysqld  Ver 5.5.53-0+deb7u1 for debian-linux-gnu on x86_64 ((Debian))

PHP version: PHP 5.4.45-0+deb7u5 (cli) (built: Aug 30 2016 20:15:34)

ownCloud version: ownCloud 9.1.2 (stable)

Storage backend (external storage): x

### Client configuration
Client version: Version 2.2.4 (build 6408)

Operating system: Windows 10 Pro Version 1607 (Build 14393.447)

OS language: German

Installation path of client: D:\Program Files (x86)\ownCloud

### Logs

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
12-02 14:30:01:951 0x1f7f10 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "test:test" INSTRUCTION_IGNORE 6 "Dateiname enthält Zeichen die nicht auf allen Betriebssystemen dargestellt werden können."
12-02 14:30:01:952 0x1f7f10 OCC::SocketApi::sendMessage: SocketApi:  Sending message:  "STATUS:IGNORE:E:\Users\User\ownCloud\test:test"
12-02 14:30:01:958 0x1f7f10 OCC::SyncEngine::slotItemCompleted: void OCC::SyncEngine::slotItemCompleted(const OCC::SyncFileItem&, const OCC::PropagatorJob&) "" INSTRUCTION_NONE 4 ""

**Comment by SamuAlfageme** [comment]
This issue has been reported for a while now, both in the server and the client repositories (e.g. #1940 #1733) and is still an ongoing discussion looking for a good, uniform solution.

The reasons for this problem are deeply explained in the [client manual](https://doc.owncloud.org/desktop/2.2/architecture.html#ignored-files) and in many other [useful references](https://www.dropbox.com/en/help/145).

First of all, there's no problem with the Linux clients, as they support the same filenames the web interface allows. Then, for the rest of the clients, this is the behavior as for today (tested with `nightly20161202`): 

* For single files, colons are replaced with slashes in OS X (`reports:2016.txt` is downloaded as `reports/2016.txt`). While in the other hand, in NTFS-based filesystems (as Windows is), errors are displayed in the activity tab.

![screen shot 2016-12-02 at 15 21 29](https://cloud.githubusercontent.com/assets/2644445/20837153/0b1749d2-b8a3-11e6-97f0-55b204f677cf.png)

* Also when the colons are present on folder names, both OS X and Windows client display an error in the activity tab. And additionally OS X shows the sync as unsuccessful (❌ on the system tray icon) and in the account tab:

![error](https://cloud.githubusercontent.com/assets/2644445/20837228/6b2909a0-b8a3-11e6-9d3b-de93ad41ddfe.png)

This error messages were improved after #5076 but **I think there should be an uniform behavior between these OS** that are unable to download such filenames. (e.g. by replacing the char for something different than a slash for the folder pov and the same sync behavior: error messages and such)

**Comment by Ascendor** [comment]
Thanks @SamuAlfageme for the explanation so far. I had seen that there were reports on single files, but wanted to make sure that folders are known as well. I find it a lot more severe to not synchronize whole directories instead of single files.
I wasn't aware of the error messages. I agree that they should be a lot more visible.

**Comment by dragotin** [comment]
You should refer to http://kizu514.com/blog/forbidden-file-names-on-windows-10/ for example to understand why file- and folder names with colons in it will not work on Windows 10 clients.

Sorry, this is hard to change.

**Comment by Ascendor** [comment]
@dragotin I'm perfectly aware of the different limitations of operating systems with regards to file and directory naming. I'm not asking to fix that.
But _silently_ ignoring complete directories is a high risk, that's what I'm criticizing.

If it would be as visible as in the MacOS version, it'd be fine for me.
