### ISSUE TITLE
[Linux] translations missing for qt5

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#5354]
I am using owncloud client with german localization. 
In rare occasions I see english strings in standard dialog widgets.

Here is an example, as seen with our latest with 2.2.4 compiled with qt5 (upper half) compared with a fresh build from a git checkout with qt4 (lower half):
![translation-qt5](https://cloud.githubusercontent.com/assets/1108546/20885951/d49f29d0-baf3-11e6-89f1-c2f03b87956f.png)

The build from todays git checkout shows the QtMessageBox with correct translations. 
I am not sure, if this is because it compiled with qt4 for me, or if the issue was actually fixed.
thanks,

**Comment by guruz** [comment]
I guess the Qt translations are for the distro and we don't ship them ourselves?

**Comment by ogoffart** [comment]
Duplicate of https://github.com/owncloud/client/issues/6774
