### ISSUE TITLE
Fedora 25 fails to build

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#5355]
As seen in the obs log file:
/bin/sh: /usr/bin/sphinx-build: /usr/bin/python2: bad interpreter: No such file or directory

**Comment by jnweiger** [comment]
Manual build with osc fails much earlier:
<pre>
cd .../obs/isv:ownCloud:desktop/owncloud-client
osc up
osc build *.spec Fedora_25 --no-verify
</pre>

[    3s] [54/56] preinstalling rpm...
[    3s] cpio: Can't write over symlinks: ./bin/rpm
[    3s] 
[    3s] [55/56] preinstalling rpm-libs...
[    3s] [56/56] preinstalling rpm-sign...
[    3s] 
[    3s] running libcrypt postinstall script
[    3s] chroot: failed to run command 'sh': No such file or directory
[    3s] initializing rpm db...
[    3s] chroot: failed to run command 'rpm': No such file or directory

**Comment by crrodriguez** [comment]
So, the build root is broken.. :-|

**Comment by jnweiger** [comment]
The build root is broken in that way, whenever I try it on Ubuntu. On my old openSUSE-13 box the build root works..

**Comment by jnweiger** [comment]
@michaelstingl @pmaier1 we can now start to officiall support Fedora 25, yeay!

**Comment by jnweiger** [comment]
This is fixed by installing bsdtar in the host. The build script uses cpio when bsdtar is unavailable and all modern versions of cpio do not work for creating the build root.

**Comment by persistance** [comment]
I meet the same problem, could you help me to solve the problem?
thanks

**Comment by guruz** [comment]
@persistance Without more info there is no way to help you.
Do you have a log?
What commands are you running?
