### ISSUE TITLE
Yield to event loop during main loop blocking operations in reconciler

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5356]
I had this idea when reviewing @mrow4a 's latest PR and because I played with nodejs yesterday..

Instead of moving things (back) to a non-UI thread, we could also "yield" at strategic points by invoking a "next" function via a QueuedConnection invocation (with timer delay or not). This would give Qt the chance to catch up with repaints and mouse events..

Relates: https://github.com/owncloud/client/issues/3064 

Opinions? @ckamm @ogoffart

**Comment by ogoffart** [comment]
The problem with this approach is that it would make the reconcile slower. (going through the event loop on each iteration adds significant overhead).
It can make also the code more spagethis-ish because of the additional states that need to be kept.

Doing the work in a worker thread does not have these problem.

**Comment by guruz** [comment]
See some numbers in https://github.com/owncloud/client/issues/5497#issuecomment-307330497 about the main thread being blocked

**Comment by guruz** [comment]
I've also noticed that the _getErrorBlacklistQuery from SyncJournalDb::errorBlacklistEntry from SyncEngine::checkErrorBlacklisting which gets called for every file from SyncEngine::treewalkFile (post-reconcile) might be something to check?

**Comment by guruz** [comment]
We might be fast already in 2.4

CC @jturcotte

**Comment by jturcotte** [comment]
Why can't we reconcile walk_local/remote_tree in the discovery thread before returning BTW?

**Comment by ogoffart** [comment]
yes, we could do the reconcile in the discovery thread.

**Comment by guruz** [comment]
That's actually issue https://github.com/owncloud/client/issues/3064 though

**Comment by guruz** [comment]
Partial solution: https://github.com/owncloud/client/pull/7457

**Comment by ogoffart** [comment]
The reconciler no longer exist
