### ISSUE TITLE
[Windows] The Uninstaller executable is not signed

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5363]
### Expected behaviour
The uninstaller [should be signed](http://nsis.sourceforge.net/Signing_an_Uninstaller) as the installer is to prevent some warning messages:

![screen shot 2016-12-07 at 11 21 46](https://cloud.githubusercontent.com/assets/2644445/20964659/b5d3b6b2-bc72-11e6-8a0e-7ee480171d7b.png)

### Actual behaviour

![screen shot 2016-12-07 at 11 22 46](https://cloud.githubusercontent.com/assets/2644445/20964625/8e9bff78-bc72-11e6-88f5-d417ff9bf32a.png)

### Steps to reproduce
1. Run `Uninstall.exe` 
2. See the yellow warning about the unsigned publisher

**Comment by SamuAlfageme** [comment]
Right now, we use an approach based on `osslsigncode`, which signs the installer on Linux. 

It [doesn't seem like there's a portable solution for this](http://stackoverflow.com/q/31776889/2172072)...

**Comment by guruz** [comment]
Might be better with NSIS

**Comment by guruz** [comment]
... MSI :-)

**Comment by dschmidt** [comment]
It is. msi has no uninstaller.exe and the .msi itself is already signed.
