### ISSUE TITLE
[Windows 10] Overlay icons broken

### ISSUE THREAD

**Issue by CasseThor** [owncloud/client#5365]
I do the update today (2.2.4 build 6408) 
when i launch owncloud client on windows 10, i cant see "the overlay icons" on folder
Bye

**Comment by guruz** [comment]
Did you try a reboot? Otherwise the support forum is https://central.owncloud.org/ or https://owncloud.org/support/
This here is for bugs.

**Comment by CasseThor** [comment]
Oh ok i try reboot ty

**Comment by CasseThor** [comment]
It's work :)

**Comment by guruz** [comment]
Great :))
