### ISSUE TITLE
[Debian/Ubuntu] Nightly packages have not been updated since November the 15th

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5367]
The official repositories for [Debian](http://download.opensuse.org/repositories/isv:/ownCloud:/community:/nightly/Debian_8.0/) and [Ubuntu](http://download.opensuse.org/repositories/isv:/ownCloud:/community:/nightly/xUbuntu_16.04/) have not been updated for a while now.

**Comment by jnweiger** [comment]
https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/testpilotcloud-client
has build targets, but is not filled in by jenkins.

https://build.opensuse.org/package/show/isv:ownCloud:testpilot:nightly/testpilotcloud-client gets nightly updates from jenkins, but does not build anything.

**Comment by guruz** [comment]
The reason is the leading space introduced by @dragotin in https://github.com/owncloud/administration/commit/9995820c70e3f74d962bee902fec6b77d4739230#diff-c2518db5a3e7a1560da30ee2e436050dR80

Will change

**Comment by guruz** [comment]
There is still some distros "Unresolvable"
https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/owncloud-client

What does that mean @dragotin @jnweiger ?

**Comment by jnweiger** [comment]
The 'unresolvable' issue  are all one: qtkeychain is broken. I assume @dragotin is not listening here. I'll investigate.

**Comment by jnweiger** [comment]
https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/owncloud-client
now build all targets. Also added Leap_42.2 and SLE_12_SP2
