### ISSUE TITLE
macOS client deletes keychain entry when entry is no longer valid

### ISSUE THREAD

**Issue by 1951FDG** [owncloud/client#5369]
### Expected behavior

macOS client does use the keychain, but deletes the keychain entry when the entry is no longer valid. We have a strict security policy which enforces users to change their passwords, but in order for them to do so they need to know their current password, if owncloud would not delete the credentials in keychain when no longer valid, users could easily lookup their current password to change their password before it expires according to our security policy.

### Actual behavior
Actual password disappears when password is no longer valid.

### Steps to reproduce
1. set password to expired
2. restart owncloud

### Client configuration

Client version: Version 2.2.4 (build 3709)

Operating system: macOS El Capitan

OS language: English

Installation path of client: /Applications

**Comment by guruz** [comment]
This is really an exotic request.
Your users should remember their password in another way. :-\

**Comment by 1951FDG** [comment]
@guruz Why does owncloud remove the credentials from keychain in the first place? Other apps don't, even if the password is not valid anymore.

**Comment by 1951FDG** [comment]
@guruz It goes further, if you log out of owncloud, it also removes the credentials from the keychain. Is this the desired behavior?

**Comment by guruz** [comment]
I guess that's how logout is implemented: If there is somnething in the keychain use that, if not show a dialog? I don't know.

**Comment by 1951FDG** [comment]
who's is responsible for the keychain implementation in owncloud?

**Comment by TheOneRing** [comment]
Out of scope
