### ISSUE TITLE
Fedora 25 client always English 

### ISSUE THREAD

**Issue by tuxmaster** [owncloud/client#5376]
The client always shown in English, even Fedora is running with the German language.
Client:  owncloud-client-2.2.4-4.1.x86_64

The owncloud-client-l10n-2.2.4-4.1.x86_64 package is installed.

Gnome is running in X11 mode.

**Comment by ckamm** [comment]
@tuxmaster Could you try this?
* Open a shell
* Run `echo "1=$LANGUAGE 2=$LANG"` so we can check whether the environment variables are set.
* Close your owncloud client and start it from the shell by running `LANGUAGE=de_DE.utf8 owncloud`. This starts it in German for me.

**Comment by tuxmaster** [comment]
Here the output:
echo "1=$LANGUAGE 2=$LANG"
1= 2=de_DE.utf8

call LANGUAGE=de_DE.utf8 owncloud
will also result in English one.

**Comment by ckamm** [comment]
@tuxmaster Thanks. I don't know what's happening. Try this?

* Quit ownCloud
* Run `LANGUAGE=de_DE.utf8 owncloud --logfile - | head` in a shell and paste the output

For me there's a line saying
```
12-14 10:49:14:422 6479 OCC::Application::setupTranslations: void OCC::Application::setupTranslations() Using "de_DE" translation
```

This is probably a problem with the distribution packaging.

**Comment by tuxmaster** [comment]
No line about loading translation:
LANGUAGE=de_DE.utf8 owncloud --logfile -

(owncloud:21150): Gtk-WARNING **: Theme parsing error: gtk.css:5:17: The 'gtk-key-bindings' property has been renamed to '-gtk-key-bindings'
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: *~
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: ~$*
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: .~lock.*
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: ~*.tmp
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: ]*.~*
*2-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: ]Icon
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: ].DS_Store
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: ].ds_store
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: ._*
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: ]Thumbs.db
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: desktop.ini
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: .*.sw?
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: .*.*sw?
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: ].TemporaryItems
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: ].Trashes
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: ].DocumentRevisions-V100
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: ].Trash-*
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: .fseventd
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: .apdisk
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: .htaccess
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: .directory
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: *.part
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: *.filepart
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: *.crdownload
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: *.kate-swp
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: *.gnucash.tmp-*
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: .synkron.*
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: .sync.ffs_db
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: .symform
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: .symform-store
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: .fuse_hidden*
12-14 11:04:24:455 0xe9b740 csync_exclude_load: Adding entry: *.unison
12-14 11:04:24:456 0xe9b740 csync_exclude_load: Adding entry: .nfs*
12-14 11:04:24:456 0xe9b740 csync_exclude_load: Adding entry: My Saved Places.
12-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: *~
12-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: ~$*
12-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: .~lock.*
12-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: ~*.tmp
12-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: ]*.~*
*2-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: ]Icon
12-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: ].DS_Store
12-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: ].ds_store
12-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: ._*
12-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: ]Thumbs.db
12-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: desktop.ini
12-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: .*.sw?
12-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: .*.*sw?
12-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: ].TemporaryItems
12-14 11:04:24:528 0xe9b740 csync_exclude_load: Adding entry: ].Trashes
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: ].DocumentRevisions-V100
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: ].Trash-*
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: .fseventd
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: .apdisk
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: .htaccess
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: .directory
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: *.part
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: *.filepart
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: *.crdownload
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: *.kate-swp
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: *.gnucash.tmp-*
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: .synkron.*
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: .sync.ffs_db
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: .symform
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: .symform-store
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: .fuse_hidden*
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: *.unison
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: .nfs*
12-14 11:04:24:529 0xe9b740 csync_exclude_load: Adding entry: My Saved Places.
12-14 11:04:30:531 0xe9b740 csync_exclude_load: Adding entry: *~
12-14 11:04:30:531 0xe9b740 csync_exclude_load: Adding entry: ~$*
12-14 11:04:30:531 0xe9b740 csync_exclude_load: Adding entry: .~lock.*
12-14 11:04:30:531 0xe9b740 csync_exclude_load: Adding entry: ~*.tmp
12-14 11:04:30:531 0xe9b740 csync_exclude_load: Adding entry: ]*.~*
*2-14 11:04:30:531 0xe9b740 csync_exclude_load: Adding entry: ]Icon
12-14 11:04:30:531 0xe9b740 csync_exclude_load: Adding entry: ].DS_Store
12-14 11:04:30:531 0xe9b740 csync_exclude_load: Adding entry: ].ds_store
12-14 11:04:30:531 0xe9b740 csync_exclude_load: Adding entry: ._*
12-14 11:04:30:531 0xe9b740 csync_exclude_load: Adding entry: ]Thumbs.db
12-14 11:04:30:531 0xe9b740 csync_exclude_load: Adding entry: desktop.ini
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: .*.sw?
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: .*.*sw?
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: ].TemporaryItems
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: ].Trashes
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: ].DocumentRevisions-V100
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: ].Trash-*
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: .fseventd
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: .apdisk
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: .htaccess
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: .directory
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: *.part
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: *.filepart
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: *.crdownload
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: *.kate-swp
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: *.gnucash.tmp-*
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: .synkron.*
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: .sync.ffs_db
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: .symform
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: .symform-store
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: .fuse_hidden*
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: *.unison
12-14 11:04:30:532 0xe9b740 csync_exclude_load: Adding entry: .nfs*
12-14 11:04:30:533 0xe9b740 csync_exclude_load: Adding entry: My Saved Places.
12-14 11:04:30:533 0x144fd80 csync_update: Journal: /home/foo/ownCloud/.csync_journal.db
12-14 11:04:30:535 0x144fd80 csync_statedb_load: sqlite3 version "3.14.2"
12-14 11:04:30:535 0x144fd80 csync_statedb_load: Success
12-14 11:04:30:535 0x144fd80 csync_memstat_check: Memory: 1360100K total size, 84892K resident, 64176K shared

**Comment by michaelstingl** [comment]
@jnweiger Do you remember any language hacks in the Fedora 25 builds?

**Comment by tuxmaster** [comment]
I have found the problem:
LANG=C rpm -ql owncloud-client-l10n-2.2.4-4.2.x86_64
(contains no files)
strace -f -n -o /var/tmp/oc.txt owncloud
less /var/tmp/oc.txt|grep ENOENT|grep ..qm
31292 access("/usr/share/owncloud/i18n/client_de_DE.qm", R_OK) = -1 ENOENT (No such file or directory)
31292 access("/usr/share/owncloud/i18n/client_de.qm", R_OK) = -1 ENOENT (No such file or directory)
31292 access("/usr/share/owncloud/i18n/client.qm", R_OK) = -1 ENOENT (No such file or directory)

**Comment by jnweiger** [comment]
Localization is disabled here due to https://github.com/owncloud/client/issues/4987

**Comment by jnweiger** [comment]
An attempt to build for Fedora_25 with localization loads the following additional packages
<pre>
(Fedora:25) qt5-qttools-devel-5.7.0-3.fc25.x86_64.rpm         100% |==============================| 267 kB    00:00     
(Fedora:25) qt5-qttools-libs-help-5.7.0-3.fc25.x86_64.rpm     100% |==============================| 219 kB    00:00     
(Fedora:25) qt5-qttools-libs-clucene-5.7.0-3.fc25.x86_64.rpm  100% |==============================|  51 kB    00:00     
(Fedora:25) qt5-designer-5.7.0-3.fc25.x86_64.rpm              100% |==============================| 201 kB    00:00     
(Fedora:25) qt5-linguist-5.7.0-3.fc25.x86_64.rpm              100% |==============================| 870 kB    00:00     
(Fedora:25) qt5-qdoc-5.7.0-3.fc25.x86_64.rpm                  100% |==============================| 476 kB    00:00     
(Fedora:25) qt5-qhelpgenerator-5.7.0-3.fc25.x86_64.rpm        100% |==============================|  24 kB    00:00     
(Fedora:25) qt5-qttools-5.7.0-3.fc25.x86_64.rpm               100% |==============================|  45 kB    00:00     
(Fedora:25) clucene09-core-0.9.21b-16.fc24.x86_64.rpm         100% |==============================| 299 kB    00:00     
</pre>

and fails with
<pre>
[  179s] Processing files: owncloud-client-dolphin-2.2.4-0.x86_64
[  179s] error: File not found: /home/abuild/rpmbuild/BUILDROOT/owncloud-client-2.2.4-0.x86_64/usr/lib64/*dolphinpluginhelper.so
[  179s] error: File not found: /home/abuild/rpmbuild/BUILDROOT/owncloud-client-2.2.4-0.x86_64/usr/lib64/qt5/plugins/kf5/overlayicon/*dolphinoverlayplugin.so
[  179s] error: File not found: /home/abuild/rpmbuild/BUILDROOT/owncloud-client-2.2.4-0.x86_64/usr/lib64/qt5/plugins/*dolphinactionplugin.so
[  179s] error: File not found: /home/abuild/rpmbuild/BUILDROOT/owncloud-client-2.2.4-0.x86_64/usr/share/kservices5/*dolphinactionplugin.desktop
[  179s] error: Directory not found: /home/abuild/rpmbuild/BUILDROOT/owncloud-client-2.2.4-0.x86_64/usr/lib64/qt5/plugins/kf5/overlayicon
[  179s] 
</pre>

**Comment by michaelstingl** [comment]
@SamuAlfageme Do you have any idea here?
