### ISSUE TITLE
[Windows] When two instances of the sync client are running, just one gets overlays and context menu options

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5377]
As @phil-davis  reported in https://github.com/owncloud/client/issues/3764#issuecomment-266336482

### Expected behavior
All the accounts in different ownCloud (branded/not) clients running under the same Windows OS get all the file explorer features: overlay icons, `Share with ownCloud` contextual menu option...  

### Actual behavior
Just the first sync client to run has these, and this behavior maintain until that first process is terminated: 

![conflict](https://cloud.githubusercontent.com/assets/2644445/21093079/33b3e3aa-c050-11e6-9054-b566d7ade20f.gif)

### Steps to reproduce
1. Install both, ownCloud and testpilot desktop sync clients and configure them with any account.
2. Check the file explorer for the local sync folders.

### Client configuration
Client version: 2.2.4
Operating system: Windows 
OS language: English 
Installation path of client: `C:\Program Files\ownCloud`

**Comment by phil-davis** [comment]
I have not been able to get the icons back at all. I have uninstalled testpilot, restarted ownCloud, rebooted the whole laptop. Then tried uninstall ownCloud client completely, then install again using the latest nightly ownCloud-2.3.0.6562-nightly20161212-setup.exe
The icons have not come back.
So I uninstalled ownCloud 2.3.0.6562 and installed 2.2.4 (build 6408). Still no icons.
Does anyone have an idea how I could get the icons back?

**Comment by SamuAlfageme** [comment]
@phil-davis You can try this out: https://github.com/owncloud/client/wiki/Debugging-Overlay-Icons#i-dont-see-icons-what-do-i-do to see if you have something corrupted in the way (and reinstalling is not fixing it)

**Comment by phil-davis** [comment]
The regsvr32 worked:
regsvr32 "C:\Program Files (x86)\ownCloud\shellext\OCOverlays_x64.dll"
So I have my overlay icons and context menu entry back now, still running 2.2.4 release version.
I can move on to testing the nightly snapshot now. I will directly use the "real" build rather than TestPilot, so as to avoid this issue about overlay and context menu items.

**Comment by SamuAlfageme** [comment]
Duplicated of https://github.com/owncloud/client/issues/2388
