### ISSUE TITLE
[Windows] Syncing a folder with 200+ items eventually displays an error 

### ISSUE THREAD

**Issue by webbytechltd** [owncloud/client#5378]
### Actual behaviour
Owncloud works when syncing a folder with a small amount of items in, when i try and sync a folder with 200+ in it shows up a red box after some time in the own cloud app

### Server configuration
Web server: Ubuntu

ownCloud version:  9.1.0 (stable)

Storage backend (external storage): Amazon S3

### Client configuration
Client version: 2.2.4 build 6408

Operating system: Windows 10

### Logs

2. Web server error log:
https://gist.github.com/webbytechltd/8464a4c72b1174cc2b79b0af25b4e6af

3. Server logfile: ownCloud log (data/owncloud.log):
https://gist.github.com/webbytechltd/dad815934785f88cd37f4f6df65aa7cb

**Comment by RealRancor** [comment]
> ownCloud version: 9.1.0 (stable)

Please always use the latest available version of your used major release (which is currently 9.1.2, https://owncloud.org/changelog/#latest9.1) before reporting any issues.

**Comment by webbytechltd** [comment]
Hi,

I have now updated the server to the latest version and tried syncing. New folders with a small amount of data works fine.

Trying to sync larger folders have the same errors and the app ending up showing a red x through the cloud

**Comment by guruz** [comment]
And what error does the client show?

**Comment by SamuAlfageme** [comment]
@guruz by what I see in the logs, I'm guessing `An error occurred while opening a folder Operation canceled`; @webbytechltd confirm? 

I am also leaving this here for follow up since I'm not being able to reproduce an S3 uploaded folder tree: https://github.com/owncloud/core/issues/26819

**Comment by guruz** [comment]
Looks like a timeout to me
```
12-12 14:17:31:051 0x51b7538 OCC::AbstractNetworkJob::slotTimeout: virtual void OCC::AbstractNetworkJob::slotTimeout() OCC::LsColJob(0xa322348) Timeout  QUrl( "https://images.{website}.me.uk/remote.php/webdav/Amazon S3/Noah James {website}/Up to 3 Months" ) 
```

This can very much depend on the s3 storage backend on the server.
I'd update to a newer server version and try again.

**Comment by ogoffart** [comment]
Closing this old issue that does not appear to be a client bug but rather a server misconfiguration or bug.
You go to https://owncloud.org/support/ if you need more help
