### ISSUE TITLE
Ability to run scripts before and after sync

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#5380]
### Feature request

Make it possible to run shell scripts or external programs before and after a sync.
This could appear as additional text fields in the configuration panel (advanced mode) where one can enter the path to one script to run before sync and one to run after.
Optionally the sync client could provide some info about the last sync run as command line arguments, for example what folder was synced (in case of selective sync).

### Use case

Here's a use case, for me at least.
It's important to note that my server has limited space which makes this process more useful

1. Setup computer for family member M who is not very good with computers
1. Setup a guest account for M on ownCloud server
1. Share a folder "Pictures" read-only with M
1. Install the desktop client on M's computer and let it sync the "Pictures" folder
1. Write a shell script that automatically copies (rsync?) pictures from "ownCloud/Pictures" to "Archive/Pictures"
1. In the desktop client, select that script to run every time after sync
1. Remove all pictures from "Pictures" as owner
1. Put another batch of pictures inside "Pictures" and wait a few days
1. Desktop client of M will download the Pictures and run the shell script
1. The shell script copies the pictures to the archive folder
1. Remove pictures again and copy newer pictures
1. Repeat
1. ...

This makes it possible for M to have ALL pictures available on her local computer and use ownCloud as a way to transfer batches of pictures. Usually in this use case I'd expect the batch of pictures to be weekly or so. (it's baby pictures, so there's often something new to show 😄)

**Comment by PVince81** [comment]
Of course one could argue that if I had setup an OC with big enough space there would be no need for the copying. But even in that case I wouldn't want the pictures to disappear from M's computer when I move them around or delete them.

**Comment by PVince81** [comment]
@pmaier1 @felixboehm

**Comment by mrow4a** [comment]
Interesting, however not sure how many users could leverage that. Reminder is that you can actually achieve sth like that using owncloudcmd, forcing sync to run every 15 minutes (as propfind currently)

**Comment by felixboehm** [comment]
FR:  use ownCloud as a way to transfer batches of files to local computers

You actually describe a technical solution, right. IMHO this solution is not very nice, it kind of injects scripts on DAU computers ...

I heard a similar FR before: Sync only in one direction.

I'd like to challenge you and our PM to find a nicer solution, adding value to the product and rounding it up. But for the Baby - no one will say "No" ^^

**Comment by dragotin** [comment]
Doesn't that sound rather like a task for https://winscp.net/eng/docs/scripting ? In case M's computer is a windows computer ;-)

**Comment by PVince81** [comment]
My proposed solution doesn't actually inject scripts. The scripts already exist on the client's computer and are outside the sync folder. Of course now that you mention it one could also have it run scripts located within the sync folder and this would technically be an injection.

I've been thinking about a simpler solution with only a python script that will download the whole folder and maybe just check the etag of the folder. Less fancy than scripting but would do.

Or the solution proposed by @mrow4a where a cron job would run owncloudcmd once a day then rsync (unidirectionally) to the target folder.

The advantage of using the sync client here is mostly only about avoiding to redownload stuff that we already have in case there were no changes on the ownCloud folder.

**Comment by PVince81** [comment]
By extension, in theory the script could then also remove the contents of the folder after archiving the files, and then put a text file into the folder to say "ok, I got it" 😉 
Really feels like "client-side workflow" here.

**Comment by PVince81** [comment]
@dragotin thanks for the link.
Now I have another family member on which computer I had the privilege of being able to install openSUSE, so in that one it will be a bit easier with cron and stuff 😄

**Comment by felixboehm** [comment]
So we search for use cases about Client Workflows.
This could become very powerful and we never thought into this direction, right? @pmaier1

**Comment by PVince81** [comment]
Server-side workflow was already thought of, but requires whatever workflow script to run on the server and might have security implications depending how the script is run. Some workflows might need to run external shell scripts.

The advantage of client-side workflows is that you could have a dedicated machine that simply syncs down files, processes them then reuploads to a target folder or the same folder (ex: converting office files to PDF). The client in question could have a dedicated ownCloud user + password and run fully automatically on a dedicated isoalted machine instead of running directly on the server.
Drawback is that the file needs to be fully downloaded first before processing. A server-side workflow can in most cases access the file directly, except for ext storages where it needs to be downloaded anyway.

**Comment by pmaier1** [comment]
Interesting ideas here. Needs to be discussed and use cases have to be collected in order to determine our interest in it. Another idea for a client workflow that just came up to my mind could be end-to-end-encryption. You could for example have an option to encrypt a file before upload and trigger additional workflows for e.g. key exchange after that.

**Comment by TheOneRing** [comment]
Not planned
