### ISSUE TITLE
[OS X > 10.10]  ownCloud Extensions is running even when owncloud is not 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5382]
### Expected behaviour
When you close the sync client, the Extensions process helper should be closed too to avoid having resources consumed and files open. (owncloud should be the parent process)

### Actual behaviour
The `ownCloud Extensions`  process is created by `launchd(1)` and keeps running indefinitely:

![img](http://i.imgur.com/ephS9IG.png)

### Steps to reproduce
1. Quit/Kill the ownCloud process 
2. Check the Activity Monitor and filter by `ownCloud Extensions`

### Client configuration
Client version: 2.2.4 
Operating system: Mac OS X > 10.10 (Finder Sync Extension)

**Comment by jturcotte** [comment]
We don't control this, that process is only the sandbox shell for the plugin, and the plugin must be loaded by Finder in order for us to detect if the ownCloud client is reachable through the SocketAPI or not. This should normally match the behavior of Dropbox, Google Drive and other sync clients.

Enabling or disabling the extension in "System Preferences / Extensions" is the normal way to let the user control the presence of this process, and activating/deactivating that setting on startup would mean that we overwrite what the user has chosen.

It should however take no CPU, and very little memory.

**Comment by jturcotte** [comment]
Dropbox seems to unload their extension, maybe it destroys itself? However they are allowed to do this since they install/uninstall the extension at runtime depending on a setting they have in the Dropbox settings. Not sure if we should go all that way to achieve this. I haven't checked what Google Drive does.

**Comment by SamuAlfageme** [comment]
@jturcotte thanks for explaining! I wanted to discuss a bit about this because I've found myself having an extension process from a client I had not opened for a while. And if somehow could we improve this so the process life span limits to the client's. 

> activating/deactivating that setting on startup would mean that we overwrite what the user has chosen. 

This is a really good point. We could consider how other projects deal with the sandboxed process for the finder sync extension and close if we don't find a better solution.

**Comment by SamuAlfageme** [comment]
@jturcotte Just tried: 

> I haven't checked what Google Drive does. 

And the sandboxed process is killed a bit after main process termination. It's also a child of `launchd(1)` but probably pools if the Drive process is running.

**Comment by SamuAlfageme** [comment]
@jturcotte maybe one additional reason to kill the finder extension process together with the client would be to allow users to uninstall from the apps folder; i.e right now you're prompted with: 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/31932477-b12d3c4c-b8a6-11e7-8c0f-4ebdfd544f39.png"/>
</p>

For the update process, I guess the `.pkg` installer **kills the running extension and replaces it with the new one**. Haven't had the chance to check just yet though.

**Comment by guruz** [comment]
@jturcotte Can't ownCloud client on exit send something to all connected sockets to make them unload themselves?

**Comment by jturcotte** [comment]
The socket will be closed, so you can already know that in the plugin, the question is if you can exit the sandbox from the inside, or if you need to do this from the outside (like with some `pluginkit` hack).

**Comment by guruz** [comment]
@jturcotte i think the ```pluginkit```way is the only one.. feel free to review https://github.com/owncloud/client/pull/6444
