### ISSUE TITLE
[macos]Chinese can't be displayed correctly

### ISSUE THREAD

**Issue by SHawnHardy** [owncloud/client#5385]
![2016-12-15 9 23 25](https://cloud.githubusercontent.com/assets/11208599/21225626/c2fde470-c30c-11e6-85fe-b5fbc7115358.png)
My macOS 's version is Sierra. If I delete all the files under Contents/Resources/Translations ,it can display English.
![2016-12-15 9 27 42](https://cloud.githubusercontent.com/assets/11208599/21225758/5541e4c6-c30d-11e6-9895-953693ad7085.png)

**Comment by guruz** [comment]
Is that for traditional or simplified?

**Comment by phil-davis** [comment]
Note: The OP's first screen shot is in Greek, does Chinese display in Greek or???

**Comment by guruz** [comment]
@SHawnHardy Any info? Also which exact version/package you downloaded?

**Comment by guruz** [comment]
Can't reproduce this with Traditional or Simplified on OS X 10.11.6 and current master branch build.

@jturcotte @SamuAlfageme Can you try with Sierra? It's quick to change the language in OS X system preferences

**Comment by SHawnHardy** [comment]
After I got rid of the Greek in Language setting.(I added Greek typewriting to make math formula ,but I choose Simplified Chinese as the language.)It shows English.
How can I do to make it show simplified Chinese?
The version of macos is Sierra 10.12.2 ,and the owncloud client’s version is 2.2.4(build 3709).
Sorry for my poor English. @guruz @phil-davis

**Comment by guruz** [comment]
@SHawnHardy Did you try to drag-and-move the Greek language down in the OS X system preferences? It is an ordered list

**Comment by SHawnHardy** [comment]
English language is not in the list.After I remove Greek, Simplified Chinese is the only language in the system preferences.

**Comment by guruz** [comment]
@SHawnHardy We have Qt 5.6.2 based builds of 2.3 (pre-release) now here that could change this. Do you want to try?
http://download.owncloud.com/desktop/daily/ownCloud-2.3.0.3974-nightly20170118.pkg

**Comment by SHawnHardy** [comment]
@guruz It doesn't work.Still English.

**Comment by ogoffart** [comment]
This looks like a configuration problem.
Is the rest of the system in chinese?

**Comment by ogoffart** [comment]
Closing old issue.
