### ISSUE TITLE
owncloud client influences text input

### ISSUE THREAD

**Issue by fotastisch** [owncloud/client#5389]
Hi there!

I'm running into a strange issue with the owncloud client. At first, I blamed elementary OS, but Xubuntu shows the same/similar behaviour.

### Expected behaviour
"Nothing much", sync in background with tray indicator.

### Actual behaviour
Sync in background, tray indicator works. But every 30 seconds, the text input in the current window is interrupted, which causes:
- missing characters, input is interrupted for a (very) short period
- cursor to blink
- selected text to blink
- e.g. on github: blinking focus of input area
- ...
Running Xubuntu, the tray items "shake" in the same interval.

All these symptoms disappear immediately when quitting the owncloud client.

### Steps to reproduce
1. install owncloud client
2. run and connect to server
3. try text input

### Server configuration
Operating system: raspbian

Web server: nginx

Database: mysql

PHP version: not sure

ownCloud version: 9.1.2

Storage backend (external storage):

### Client configuration
Client version: 2.2.4

Operating system: elementary OS (Loki), Xubuntu (Xenial)

OS language: English

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: empty

**Comment by fotastisch** [comment]
Something else I just noticed:
The RAM allocated by wingpanel increases every 30 seconds by a few MBs simultaneously to the issue described above. This also stops immediately when quitting the client.

**Comment by fotastisch** [comment]
And another update: I've tested different hosts which were not set up by me. They also cause the same behaviour, so it seems it's not just some misconfiguration on my server.

Could it maybe be caused by the quotainformation? It was the only thing I found so far that is coded to happen in a 30 second interval...

**Comment by fotastisch** [comment]
Based on the increasing RAM usage: Could this be linked?
[https://github.com/owncloud/client/issues/4929](url)
Both the wingpanel RAM as well as the owncloud RAM keep on increasing everytime the system freezes...
Another thing that I just noticed: Being connected to two servers makes things much worse...

**Comment by ckamm** [comment]
@fotastisch Probably the tray issue #4990 . Try whether starting with the environment variable OWNCLOUD_MINIMAL_TRAY_MENU set to 1 makes the problem go away.

There was also a fix in master (upcoming 2.3.0 that should trigger this upstream problem less often). You could try a nightly build: https://owncloud.org/install/#testing-development

**Comment by ckamm** [comment]
There are likely to be fixes for this in 2.3 already. Feel free to reopen if you have more data.

**Comment by guruz** [comment]
2.3.0 beta1 is out
https://owncloud.org/changelog/desktop/
