### ISSUE TITLE
Under XWayland (Fedora 25) owncloud-client crashes with (owncloud:10554): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window

### ISSUE THREAD

**Issue by qwazix** [owncloud/client#5393]
### Expected behaviour
File picker window opens

### Actual behaviour

owncloud-client crashes with 

```
(owncloud:10554): Gdk-WARNING **: gdkwindow-x11.c:5573 drawable is not a native X11 window
Segmentation fault (core dumped)
```

### Steps to reproduce
1. Open owncloud-client settings
2. Click Add Folder Sync Connection 
3. Click Choose

### Server configuration
Operating system: Ubuntu 14.04

Web server: Apache 2.4.7

Database: MySQL

PHP version: 5.5.9

ownCloud version: 9.1

Storage backend (external storage): No

### Client configuration
Client version: 2.2.4

Operating system: Fedora 25

OS language: English

**Comment by guruz** [comment]
Which package did you use?
Can you also tell us the Qt version, it should be displayed inside the client settings window

**Comment by qwazix** [comment]
The package is from the opensuse.org repos (latest) and Qt is 5.7 (system)
