### ISSUE TITLE
ear

### ISSUE THREAD

**Issue by aappddeevv** [owncloud/client#5397]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:

Operating system:

OS language:

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by mrow4a** [comment]
Please edit the issue, otherwise we would need to close it.

**Comment by aappddeevv** [comment]
I did not open this issue...which is a bit concerning how it was opened under my account...
