### ISSUE TITLE
Email syntax as username in the server url causes an host not found error

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5398]
### Expected behaviour
When using email address syntax for the username combined with the [qualified form of the server URL](https://doc.owncloud.org/desktop/1.8/advancedusage.html#credential-handling), the user credentials are copied into the authentication page of the new account wizard. 

![qualified_creds](https://cloud.githubusercontent.com/assets/2644445/21355452/4dce0f7a-c6ce-11e6-84a0-9d09a01ade68.gif)

### Actual behaviour
The URL is not recognized as valid. And the credentials are not automatically used as input for the auth phase.

![screen shot 2016-12-20 at 16 00 38](https://cloud.githubusercontent.com/assets/2644445/21355235/820b574e-c6cd-11e6-939e-5a4d21ae0e79.png)

**Note:** the same goes for `owncloudcmd`:
```
!!! OCC::LsColJob created for "http://https://username@mail.server.com:password@owncloud.server.com" + "" "OCC::DiscoverySingleDirectoryJob"
void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(HostNotFoundError) "Host https not found" QVariant(Invalid)
void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply *) "Host https not found" 0 QNetworkReply::NetworkError(HostNotFoundError)
void OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot(int, const QString &) 5 "Host https not found"
OCC::DiscoveryJob(0x7f9788f32630)  ...Returned from main thread
5 when opening  msg= "Host https not found"
[4] csync_ftw  opendir failed for  - errno 5
[6] csync_statedb_close  sqlite3_close=0
 #### ERROR during  csync_update :  "An error occurred while opening a folder Host https not found"
```

### Steps to reproduce
1. Input the qualified address for the server `https://username@mail.server.com:password@owncloud.server.com`
2. Click Next

**Comment by ckamm** [comment]
This happens because QUrl considers these urls invalid. I'm not sure whether this is correct.

**Comment by SamuAlfageme** [comment]
@ckamm Yup I agree with `QUrl` considering the url as invalid as it's sticking to the EBNF in Section 3.2.1 of the URI syntax RFC: https://www.ietf.org/rfc/rfc3986.txt but reality is that server allows `userinfo`s to be email addresses. 

Also there it says this: 

> Use of the format "user:password" in the userinfo field is deprecated.

So I think we should drop this way of passing username/pass in `owncloudcmd` and favor some flagged alternative (e.g. `-u usename -x pass` or similar).

**Comment by guruz** [comment]
I'm not sure I understand the situation and the animated GIF above.
Why is there suddenly an e-mail address?
Remember that you need to encode characters in URLs using percent encoding.

http://stackoverflow.com/a/6718568/2941

**Comment by SamuAlfageme** [comment]
@guruz The situation on the gif is described in the reproduction steps;

> Why is there suddenly an e-mail address?

I've been seeing for a time now OC servers using email addresses as usernames (e.g. https://github.com/owncloud/administration/tree/master/redirectServer#example) 

You are right, I missed that using `%40` as percent encoding for the `@` does the trick. Thanks for pointing it out. From the user of the GUI pov this is not that obvious to use `https://username%40mail.server.com:password@owncloud.server.com` . But we can close here as this is no longer relevant.

**Comment by guruz** [comment]
@SamuAlfageme Ah sorry I was blind for the headlines Expected vs Actual, I had wondered where 'mail.server.com' was from because I didn't see it.
