### ISSUE TITLE
NSIS MUI: opens two instances in a row by itself

### ISSUE THREAD

**Issue by gabr131** [owncloud/client#5402]
Hello,

I am compiling a owncloud client for windows, I am using OpenSUSE 13.3, mingw32 and qt 5.7 for compilation. I have the following inconvenience: the installation occurs perfectly, however when it is finished or I cancel the installation the wizard closes however opens another immediately.

The following is the installation script:

From this link you can view the installation script I'm using: https://github.com/owncloud/client/blob/master/cmake/modules/NSIS.template.in

If anyone has any idea how to fix this or where to start looking, thank you. I have been looking for forums or documentation for several days to help me but I have not found anything about it.

**Comment by SamuAlfageme** [comment]
@gabr131, that behavior seems odd. You can check the script used in our CI environment here: https://github.com/owncloud/administration/blob/master/jenkins/win32_build/compile_client.sh from where we cross-compile the client and pack it using NSIS. Give it a try to see if that fits your cross compiling env.

**Comment by guruz** [comment]
... or use ownBrander
https://doc.owncloud.org/server/9.0/admin_manual/enterprise_clients/creating_branded_apps.html
