### ISSUE TITLE
The username in SAML logins doesn't appear next to the URL in the account tab

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5407]
### Expected behavior
The username should be shown after the server URL as it does in the regular auth scenario/the account tab tittle itself. 
 
### Current behavior
Just the regular trailing dot used after the username is shown. 

![saml_username](https://cloud.githubusercontent.com/assets/2644445/21389191/a136863a-c780-11e6-996a-5d480fe005d7.png)

### Client configuration
* **Client version:** 2.3.0git self compiled from 0797d5c5254b52dcbf7add5274dee1b10426f2e6 
* **Operating system:** OS X 10.11.6
* **OS language:** English

**Comment by ckamm** [comment]
Same in 2.2.4.

**Comment by ckamm** [comment]
Probably has the same root cause as https://github.com/owncloud/client/issues/5408

**Comment by ckamm** [comment]
Should be fixed by https://github.com/owncloud/client/pull/5409

**Comment by SamuAlfageme** [comment]
👍
