### ISSUE TITLE
Download small files first?

### ISSUE THREAD

**Issue by Nowaker** [owncloud/client#5410]
### Expected behaviour

When new files are on the server, small files should be downloaded first, larger next.

### Actual behaviour

It's frustrating to see a sync blocked by a download of a huge file like 500 MB when I'm waiting for that one small PDF to be downloaded.

### Steps to reproduce

0. Shut down owncloud client.
1. Upload large file to owncloud (externally).
2. Upload small file to owncloud (externally).
3. Start client.

### Server configuration

Not relevant.

### Client configuration

2.2.4

### Logs

Not relevant.

**Comment by mrow4a** [comment]
Co bys powiedzial na sortowanie po czasie modyfikacji a nie po wielkosci pliku (What will you say about sorting folders by modification time instead of its size) ? 

Please have a look here, this is ongoing work: https://github.com/owncloud/client/pull/5349

We tried with filesizes, but we though better idea will be modification time of the deepest child to decide which folder to sync first. So if you have HUGE sync pending, but you work on some document/PDF, this will be synced first of all :>

**Comment by Nowaker** [comment]
...unless in the meantime a different client uploads a 500 MB file and it's the newest file.

So - it's a worse idea. Small files first sounds like the best scenario. Small files can be quickly downloaded.

**Comment by mrow4a** [comment]
It is not a upload time what matters, it is an update/creation time of the file itself. Probability that you created big file before your document is very very low :> Document means something on which you work on.

BTW, if you place a big file and small file next to each other, your small file will be synced probably after the first chunk of the big one. You would need to have a folder full of big files in order to block your small file upload. OwnCloud operates on 3 parallel flows.

**Comment by Nowaker** [comment]
Which, when a file is new, is the same as upload date. 

We work on shared folders. Many people make changes. Create date is unpredictable. File size is. 

That being said, I'd rather see 200 small files downloaded first that are 20MB in total rather than one file that is 500MB, no matter if new or not.

**Comment by mrow4a** [comment]
As said above, only 1 big file will never block it. It needs to be bigger collection of big files. 

![image](https://cloud.githubusercontent.com/assets/13368647/21409173/00a20b8c-c7d9-11e6-9101-c74abcd4e80a.png)

But yes, I will suggest it to have a client side option of selection in GUI, by which priority your folders should be sorted - modification time or asc/des filesize.

**Comment by Nowaker** [comment]
I know it did block. I had this problem today. There was a big file, and there was a small PDF. PDF wasn downloaded to my desktop by the client after the big file downloaded.

**Comment by jturcotte** [comment]
Some people might be waiting for their small PDF to be synced while 500MB of 10k files are being synced. Somebody could be waiting for that 500MB file while all smaller files are being synced. The file size is predictable, but not necessarily correlated to the value of the file for one of the users (and different users might care about different files).

All ideas are worse ideas in some situations, since they're all only approximations unless we start using the stars in the web interface as a priority or something like that.

**Comment by mrow4a** [comment]
Ok, What could happen is, your system does PROPFIND, and finds big file. So it starts syncing it. If you added in the mean time of that process a PDF, long wait my friend. Next time just pause and start sync to init the process from beginning :>

**Comment by mrow4a** [comment]
@Nowaker Do you think the above has solved your issue ? Please also have an eye on #5349 in the future, maybe you could have a valuable comment there :>

**Comment by Nowaker** [comment]
> Ok, What could happen is, your system does PROPFIND, and finds big file. So it starts syncing it. If you added in the meantime of that sync a PDF

No, it wasn't a case. I did pause/resume owncloud client multiple times, yet the big file wanted to sync first no matter what.

> Some people might be waiting for their small PDF to be synced while 500MB of 10k files are being synced. Somebody could be waiting for that 500MB file while all smaller files are being synced. The file size is predictable, but not necessarily correlated to the value of the file for one of the users (and different users might care about different files).

If you have a lot of files, it's gonna take long to sync anyway - no matter what. Order isn't that important if you have thousands of files. If you have **a few** files to sync, it's ALWAYS, **ALWAYS** better to download small first, big next. There's virtually no reason to do it differently.

**Comment by phil-davis** [comment]
1) In the case where the user considers each file of equal value, then the optimal is to sync the smallest files first - gaining value for the user most quickly. If the user happens to consider some small file(s) more valuable than some big file, then "sync small files first" is even more optimal.
It is only in the case where a user considers some big file to be of much greater value than a whole "swarm" of small files (e.g. that might be the result of some app that creates/changes a load of underlying files as it works), where "sync small files first" is not optimal. But I can't think of a good way to predict the user's value - e.g. some rule like "if there are more than 1,000 small files to sync in a folder tree then they must be a load of little rubbish so put them at the end and sync some bigger files first" - which would be quite arbitrary!

2) The other thing that happens is when a small file is changed (by another client) when client1 is currently syncing big files that will take "a long time" (as defined by the user). Even if we do sync small files first, sometimes a small file will still get "stuck" waiting for an existing sync to finish and a check for changes to be made again. If some algorithm is put in place to order files for sync in some way (e.g. from small to large), then there is also an argument that we should check again for recent changes at some interval and merge recently change files into the pending sync list so they can also "jump the queue".

**Comment by Nowaker** [comment]
Exactly right about point number 1. Now add the "how often" question to the equation. How often do you have just a couple files to sync? Answer: very often, every day, all the time. And this is the reason why owncloud needs to optimize downloads for file size, not date.

But if it's not convincing, let's do some maths. As mentioned in point number 1, we cannot predict which file is more important. In that case each file is assigned the same value of importance. Downloading small files first maximizes the probability of getting the file you're interested in.

**Comment by guruz** [comment]
@mrow4a Maybe we should have a poll on central.owncloud.org to get more input..

**Comment by mrow4a** [comment]
@Nowaker I see one more option. It is possible that your apache server configuration allows only 1 operation at the time. Can you verify that your server is not putting all the files in the single queue, executing files 1 after another instead of 3-6 flows?

**Comment by Nowaker** [comment]
Thanks for your suggestion @mrow4a. Is there a synthetic way to test it? A simple script to execute to have a yes/no answer about the number of flows? Or a set of specific requests I need to call - so I can write a tester script myself?

**Comment by felixboehm** [comment]
My expectation is that the sync goes folder by folder.
And having multiple downloads in parallel is avoiding this kind of blocking anyways.

@Nowaker You can use mitmproxy to observe the clients requests, or Wireshark.

**Comment by guruz** [comment]
> And having multiple downloads in parallel is avoiding this kind of blocking anyways.

But we take as much as possible files from one folder. I think @mrow4a is also considering to take one file from each folder and only continue with a folder if that is not possible. But that might be more messy to implement.

**Comment by mrow4a** [comment]
@guruz It is not and it is done like this in bundling. Bundling takes all files which satisfy its requirements (under chunking size) and places it in its internal class queue (per directory currently). If you disable parallel requests in the bundle, it will first search for files >10MB in the parent folder, and if it will not find it then call scheduleNext on different folders, and repeat the process.

**Comment by mrow4a** [comment]
@Nowaker Did you enable Network Limits in your sync client? 
![selection_002](https://cloud.githubusercontent.com/assets/13368647/21746362/6290b64c-d542-11e6-8ebc-44979210709c.png)

I found in the code, that his could also finalize in no parallelisation - https://github.com/owncloud/client/blob/master/src/libsync/owncloudpropagator.cpp#L82

@jturcotte @ogoffart

**Comment by ogoffart** [comment]
I beleive having a predicable (alphabetical) order is more usefull that using some kind of heuristics like this to try to be smart about the order.
