### ISSUE TITLE
On LDAP accounts, the user name is being replaced by an internal identifier in some places

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5413]
### Expected behavior
The username used to log in into the application is shown as the Internal Username Attribute in LDAP everywhere on the application.

### Actual behavior
A long internal identifier is shown instead of the regular `user`/`http_user`:

![delete](https://cloud.githubusercontent.com/assets/2644445/21425797/76c0a4b4-c84b-11e6-8e79-dab525c53c0c.png)

Note: in some installations, I've also noticed it being replaced in the tray menu: 
 
![tray_menu](https://cloud.githubusercontent.com/assets/2644445/21425774/5ab2029a-c84b-11e6-93a3-935fba194c9c.png)

### Steps to reproduce
1. Log in with an LDAP account.
2. Try to delete that account.

**Comment by ckamm** [comment]
@SamuAlfageme Neat catch, it's indeed a regression. Fixed now.

**Comment by SamuAlfageme** [comment]
👍
