### ISSUE TITLE
[Overlays] Don't show green check mark icon while discovering changes

### ISSUE THREAD

**Issue by mvglasow** [owncloud/client#5415]
When the client is discovering changes, IMHO it should not show the green check mark icon—I take that icon to indicate “all is in sync, nothing to do”. It would be more appropriate to switch to the the “sync in progress” icon as soon as:

* The user initiates synchronization
* Changes are found during synchronization (regardless of whether sync was triggered by the user or the application)

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/40331887-overlays-don-t-show-green-check-mark-icon-while-discovering-changes?utm_campaign=plugin&utm_content=tracker%2F216457&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F216457&utm_medium=issues&utm_source=github).

**Comment by jturcotte** [comment]
We have the filesystemwatcher that will set a file as syncing if we detected a change on disk.
For other cases, how do you know if a file is in need of sync if we're currently discovering changes?

I don't think that setting all files as "sync in progress" is a good compromise, if this is what you have in mind.

**Comment by guruz** [comment]
Closing in favor of https://github.com/owncloud/client/issues/5860 even though your issue is older.
