### ISSUE TITLE
[UX] Tap finished upload in upload list must open folder

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#5418]
### Steps

1. Upload many pictures using the "share" feature and select "ownCloud" as target
1. Navigate to different folders in the ownCloud app during the upload (because why not?)
1. Wait for upload to finish and all notifications to disappear
1. Go to upload list (need to go to the root to find the menu item, see https://github.com/owncloud/client/issues/5417)
1. Tap on one of the successful uploads

### Expected
App navigates to the folder where the file was uploaded, maybe select it by default.

### Actual
Tapping an entry does nothing

**Comment by michaelstingl** [comment]
Android? Better open it in https://github.com/owncloud/android ?
