### ISSUE TITLE
Trash icon too close to "three dots" menu

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#5419]
Note: I usually use vimtouch to open text files

1. Install vimtouch (or any other text editor)
1. Upload some text file "test.txt" from another machine
1. In the ownCloud app, navigate into the folder of the file "test.txt"
1. Hold on the "test.txt" item (we want to edit but don't want to view the file with the built-in viewer)
1. Use the "three dots" menu to select "open with" but be clumsy and tap a bit on the left of it

### Expected
No trash icon so close to "three dots"

### Actual
Risk of tapping the delete icon when aiming for the three dots menu.

Note: in general I'm not too happy to have to use this menu when editing a file. But due to the new built-in viewer I need to do more manual action to be able to open the file in an external editor. (maybe I'll make another separate report)

**Comment by guruz** [comment]
Wrong bugtracker?
