### ISSUE TITLE
Fix bug in the "Credential Handling" section of the documentation

### ISSUE THREAD

**Issue by settermjd** [owncloud/client#5422]
There's an error in [the Credential Handling section of the ownCloud Client Manual](https://doc.owncloud.org/desktop/1.8/advancedusage.html#credential-handling)

```console
$ owncloudcmd / https://carla:secret@server/owncloud/remote.php/webdav/
```

In the command above, a user is trying to sync their root filesystem to their ownCloud server. However, because of permission issues (notice $ instead of #) he can't do this. The verbose error of `owncloudcmd` shadows this also:

```console
Error: "unable to open database file" for "/._sync_9dede02bb8da.db"
Error opening the db:  "unable to open database file"
No way to create a sync journal!
void OCC::SyncJournalDb::close() "/._sync_9dede02bb8da.db"
No database Transaction to commit
CSync run took  0
void OCC::SyncEngine::abort() QObject(0x0)
void OCC::SyncJournalDb::close() "/._sync_9dede02bb8da.db"
No database Transaction to commit
2:21 PM
```

Given that, the following example would be better:

```console
$ owncloudcmd ./ https://carla:secret@server/owncloud/remote.php/webdav/  
```

**NOTE:** This is an issue which was requested by someone else other than myself.

**Comment by guruz** [comment]
@settermjd Hm, this is a bad example then. Maybe we should explicitely put ```/home/user/my_sync_folder``` instead of / or ./?

**Comment by ckamm** [comment]
@guruz Your suggestion made sense to me, applied!
