### ISSUE TITLE
Folder Size Bug

### ISSUE THREAD

**Issue by Spire9** [owncloud/client#5423]
Brought from central.owncloud.org by request of tflidd.

It seems that when you open the owncloud client app the parent folder sizes in the root directory are stuck until the client is rebooted.  The child folders seem to get their updates as they should, but not their parent directories.  It shows a successful last sync too.  I rebooted the PC and got the right sizes to show then.  It happened both times I tested.

https://www.dropbox.com/s/p4qp29cjrq864ly/ownCloud%20size%20error.png?dl=1

[b]Steps to reproduce[/b]
1.Make a noticeable chance to the content size of a subfolder (child folder) that owncloud is syncing.
2.Observe the child folder shows an updated size, the parent folder does not.
3. Restart required.

[b]Expected behaviour[/b]
Show current size

[b]Actual behaviour[/b]
Shows old size

[b]Client configuration[/b]
Client version: 2.2.4
Client operating system: Windows10

[b]Server configuration[/b]
Operating system: Ubuntu16
Web server: Apache
Database:SQL
PHP version:Latest
ownCloud version (see ownCloud admin page):9.1.3
Updated from an older ownCloud or fresh install: fresh
Special configurations (external storage, external authentication, reverse proxy, server-side-encryption):
external hdd
[b]ownCloud log (data/owncloud.log)[/b]

Please paste possible errors in the following code block, see https://central.owncloud.org/t/how-to-find-webserver-or-oc-logfile-enable-php-logfile/808 for more info
[code]

[/code]

**Comment by ckamm** [comment]
I could not reproduce this specific behavior with master.

However, I do see in the code and in practice, that only directory actions reset the selective sync ui folder sizes. Uploading a new large file does not trigger any size update in that view.

**Comment by joshk03** [comment]
That would be the same issue then, I wasn't modifying any files, just drag-and-drop adding files.

**Comment by PVince81** [comment]
In my case I was doing some cleanup and deleted many sub-subfolders then checked the quota page and noticed that the folder sizes were not updated either (client v2.2.4)
