### ISSUE TITLE
Change several Q_ASSERT to if() with qFatal

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5429]
We have several places where it is much better to crash than to assert only in debug mode.

* [ ] Change https://github.com/owncloud/client/commit/143320341e1b01a53e69755cbd2badc61cf4440c to be only be for rcs and betas
* [ ] Check all asserts and see if it is better to change them to qFatal (e.g. https://github.com/owncloud/client/commit/adbe5ecf5507f5f751d869b02a2033fb895aaa14 )

FYI @ckamm

**Comment by dschmidt** [comment]
Additional consideration to take into account:

Asserts might also hide improper error handling, developers might never see how the application behaves after an assertion didn't "fire" - i.e. there might be crashes in completely unexpected parts of the code - and that only in release builds, not even in beta or rc builds.
I'd recommend to at least make the behavior of beta, rc and release builds identical - so basically reverting https://github.com/owncloud/client/commit/143320341e1b01a53e69755cbd2badc61cf4440c.

And yes, I agree, if we can't recover from situations where assertions failed, we should use `qFatal()`

**Comment by jturcotte** [comment]
We need to at least revert 1433203 in 2.3.

**Comment by ckamm** [comment]
Pull request: https://github.com/owncloud/client/pull/5518

**Comment by guruz** [comment]
(Closing in favour of PR)
