### ISSUE TITLE
[OS X][Keychain] When there's a configuration/network error on startup, the accounts affected stay stuck disconnected

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5430]
**Note: this is a problem related with some buggy keychain setting in custom builds. Not reproducible on stable/nightly builds**

### Actual behavior
When there's a problem on startup, the user is unable to re-login and the client is left in a cyclic dirty state: 

![blank diagram - page 1 2](https://cloud.githubusercontent.com/assets/2644445/21677670/6b6714a4-d33b-11e6-80b6-468a8940cc3b.png)

*Note that only the transition `"Disconnected" -> "X error"` is made on startup*

Some similar behavior was reported also in https://github.com/owncloud/client/issues/5408#issuecomment-268575274 

This reproduces when there's problems with the config:
```
OCC::AccountState::setState: AccountState state change:  "Disconnected" -> "Configuration error"
OCC::FolderMan::slotAccountStateChanged: Account "admin@localhost:32768" disconnected or paused, terminating or descheduling sync folders
```
... or with the network, e.g. when the server is not available: 
```
OCC::AccountState::setState: AccountState state change:  "Network error" -> "Signed out"
OCC::FolderMan::slotAccountStateChanged: Account "admin@localhost:32768" disconnected or paused, terminating or descheduling sync folders
OCC::AccountState::setState: AccountState state change:  "Signed out" -> "Disconnected"
OCC::FolderMan::slotAccountStateChanged: Account "admin@localhost:32768" disconnected or paused, terminating or descheduling sync folders
```

Both have the same result in the UI:
![logout-login](https://cloud.githubusercontent.com/assets/2644445/21680037/7396c9ec-d347-11e6-9aa6-cd6f79acdc95.gif)

### Expected behavior
If there was a config/network error, there should be a simple way to recover from it without having to delete the account and restore everything, e.g. asking for pasword input, new server url...

### Steps to reproduce
1. Add an account 
2. **Cause a Network/Configuration error** (from a dirty config file or server that is down)
3. Restart the client

Again (#5321 and https://github.com/owncloud/client/issues/5290#issuecomment-260587066), I think it's really important to define a set of distinctive states and a solid state machine that supports the whole client operative.

**Comment by guruz** [comment]
If you really get this behaviour, it is a severity 1 not 3 :)

**Comment by SamuAlfageme** [comment]
@guruz hm, just tried with an old nightly and did not reproduce. I was testing against the current master and some of the work done in #5408 could be the one causing the weird behavior. Will look into it.

**Comment by guruz** [comment]
I can't seem to reproduce this with a non-shib account.
But i'm also not 100% sure I understand the issue.

**Comment by SamuAlfageme** [comment]
Closing this as I just confirmed it was the qtkeychain issue as suspected.
