### ISSUE TITLE
owncloud client crashes frequently linux mint gui when clicking system tray

### ISSUE THREAD

**Issue by jdcrecur** [owncloud/client#5433]
### Expected behaviour
The app should not crash the Linux Mint desktop GUI when you click on the icon in the system tray

### Actual behaviour
The client app frequently crashes the linux mint GUI which then requires a the GUI to restart when clicking on the icon in the system tray.

This happens on more than one std installation of linux mint.

### Steps to reproduce
1. run the latest owncloud client onthe latest  linux mint OS
2. the server mapped via a host entry & using a std snakeoil cert
3. 40-50% of the time the client crashes the linux mint GUI clicking on the icon in the system tray.

### Server configuration
Operating system:
Linux Mint 18

Web server: 
ubuntu 16 running owncloud & apache. Owncloud installed and updated via apt. Owncloud sever in private network and mapped to via host entries form the clients.

Database:
mysql 5.7

PHP version:
7.0

ownCloud version:
latest

Storage backend (external storage):
local hdd

### Client configuration
Client version:
Version 2.1.1+dfsg-1ubuntu1.1.

Operating system:
linux mint 18

OS language:

Installation path of client:
installed via software manager

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by DPTJKKVH** [comment]
I can confirm this error. In fact it is an old error that returned with the latest update. The issue is with the indicator menu not being able to be drawn, throwing countless errors in syslog and eventually crashing the whole system. Why the display manager of all crashes first I don't know. Here are the logs relevant:

Stage one, righ after boot and when idleing:

> Jan  7 14:11:28 xxx unity-panel-ser[2292]: Getting layout failed: Operation was cancelled
> Jan  7 14:11:29 xxx unity-panel-ser[2292]: Group Properties error: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/MenuBar'
> Jan  7 14:11:29 xxx unity-panel-ser[2292]: message repeated 8 times: [ Group Properties error: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/MenuBar']

This is repeated over and over and over in syslog. When you start the system the indicator menu somewhat still works even though you notice a little stutter when opening it. After a while the menu can't be drawn at all. You get an empty box with no menu items. This is usually the moment when your system is beyond saving and the display manager becomes unresponsive and all you can do ist press the reset button on your computer.


Stage two after a couple of minutes:

> Jan  7 14:16:17 xxx unity-panel-ser[2292]: Getting layout failed: Operation was cancelled
> Jan  7 14:16:17 xxx unity-panel-ser[2292]: panel_service_show_entry_common: assertion 'INDICATOR_IS_OBJECT (object)' failed
> Jan  7 14:16:17 xxx unity-panel-ser[2292]: Getting layout failed: Operation was cancelled

This happens when you click on the indicator icon. In 2 of 3 times it turns into a black box crossed out by a red line. At the third click the menu opens.

Unfortunately I don't have the time to catch the actual crash logs right now because you have to wait for about 30 minutes to an hour to get the system to this state. I will do later when I have time. But maybe the logs provided are already helpful.


Additional log entries:

> n  7 14:13:48 xxx compiz[2260]: WARN  2017-01-07 14:13:48 unity.iconloader IconLoader.cpp:756 Unable to load icon file:///home/xxx at size -1x22: Error opening file /home/xxx: Is a directory

I'm not sure if this is related but it fits the icon error.


>  7 14:21:16 xxx unity-panel-ser[2292]: Getting layout failed: Operation was cancelled
> Jan  7 14:21:16 xxx unity-panel-ser[2292]: Group Properties error: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/MenuBar'
> Jan  7 14:21:16 xxx unity-panel-ser[2292]: message repeated 17 times: [ Group Properties error: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/MenuBar']


>  7 14:14:45 xxx compiz[2260]: ERROR 2017-01-07 14:14:45 unityfree <unknown>:0 g_sequence_get: assertion '!is_end (iter)' failed
> Jan  7 14:14:45 xxx compiz[2260]: ERROR 2017-01-07 14:14:45 unity null <unknown>:0 Unable to get value. NULL row data in DeeSequenceModel@0x562429bee860 at position 2. The row has probably been removed
> Jan  7 14:14:45 xxx compiz[2260]: ERROR 2017-01-07 14:14:45 unity null <unknown>:0 Unable to get string. Column 5 in DeeSequenceModel@0x562429bee860 holds a NULL value in row 2
> Jan  7 14:14:47 xxx unity-panel-ser[2292]: Getting layout failed: Operation was cancelled
> Jan  7 14:14:47 xxx unity-panel-ser[2292]: Getting layout failed: Operation was cancelled

**Comment by DPTJKKVH** [comment]
I noticed something! 

Right after boot I get tons of those errors:

> 7 14:08:16 xxx unity-panel-ser[2292]: Unable to replace properties on 0: Error getting properties for ID
> Jan  7 14:08:16 xxx unity-panel-ser[2292]: Unable to replace properties on 609: Error getting properties for ID
> Jan  7 14:08:16 xxx unity-panel-ser[2292]: Unable to replace properties on 610: Error getting properties for ID
> Jan  7 14:08:16 xxx unity-panel-ser[2292]: Unable to replace properties on 611: Error getting properties for ID


A couple moments later those pop up as well:

> 7 14:08:24 xxx unity-panel-ser[2292]: Group Properties error: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/MenuBar'
> Jan  7 14:08:24 xxx unity-panel-ser[2292]: Unable to replace properties on 0: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/MenuBar'
> Jan  7 14:08:24 xxx unity-panel-ser[2292]: Unable to replace properties on 908: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/MenuBar'
> Jan  7 14:08:24 xxx unity-panel-ser[2292]: Unable to replace properties on 909: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/MenuBar'


When owncloud client did its first sync with the server this error occours:

> 7 14:09:31 xxx unity-panel-ser[2292]: Unable to replace properties on 0: Error getting properties for ID
> Jan  7 14:09:31 xxx unity-panel-ser[2292]: message repeated 41 times: [ Unable to replace properties on 0: Error getting properties for ID]
> Jan  7 14:10:25 xxx unity-panel-ser[2292]: Getting layout failed: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: No such object path '/MenuBar'
> Jan  7 14:10:26 xxx unity-panel-ser[2292]: Getting layout failed: Operation was cancelled
> Jan  7 14:10:29 xxx unity-panel-ser[2292]: message repeated 61 times: [ Getting layout failed: Operation was cancelled]


This also happens:

> Jan  7 14:13:04 xxx compiz[2260]: WARN  2017-01-07 14:13:04 unity <unknown>:0 Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx compiz[2260]: WARN  2017-01-07 14:13:04 unity <unknown>:0 Failed to fetch type: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx compiz[2260]: WARN  2017-01-07 14:13:04 unity <unknown>:0 Failed to fetch monitor: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx compiz[2260]: WARN  2017-01-07 14:13:04 unity <unknown>:0 Failed to fetch maximized state: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx compiz[2260]: WARN  2017-01-07 14:13:04 unity <unknown>:0 Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx compiz[2260]: WARN  2017-01-07 14:13:04 unity <unknown>:0 Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx compiz[2260]: WARN  2017-01-07 14:13:04 unity <unknown>:0 Unable to fetch children: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.view' on object at path /org/ayatana/bamf/application/290671880
> Jan  7 14:13:04 xxx compiz[2260]: WARN  2017-01-07 14:13:04 unity <unknown>:0 Failed to fetch path: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.application' on object at path /org/ayatana/bamf/application/290671880
> Jan  7 14:13:04 xxx compiz[2260]: message repeated 7 times: [ WARN  2017-01-07 14:13:04 unity <unknown>:0 Failed to fetch path: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.application' on object at path /org/ayatana/bamf/application/290671880]
> Jan  7 14:13:04 xxx compiz[2260]: WARN  2017-01-07 14:13:04 unity <unknown>:0 Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx compiz[2260]: WARN  2017-01-07 14:13:04 unity <unknown>:0 Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx compiz[2260]: WARN  2017-01-07 14:13:04 unity <unknown>:0 Failed to fetch maximized state: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx compiz[2260]: WARN  2017-01-07 14:13:04 unity <unknown>:0 Failed to fetch type: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx compiz[2260]: WARN  2017-01-07 14:13:04 unity <unknown>:0 Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx compiz[2260]: WARN  2017-01-07 14:13:04 unity <unknown>:0 Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx unity-panel-ser[2292]: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx unity-panel-ser[2292]: Failed to fetch type: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx unity-panel-ser[2292]: Failed to fetch monitor: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx unity-panel-ser[2292]: Failed to fetch maximized state: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx unity-panel-ser[2292]: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx unity-panel-ser[2292]: message repeated 2 times: [ Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804]
> Jan  7 14:13:04 xxx unity-panel-ser[2292]: Failed to fetch property `_GTK_UNIQUE_BUS_NAME': GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx unity-panel-ser[2292]: Failed to fetch path: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx unity-panel-ser[2292]: Failed to fetch path: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.application' on object at path /org/ayatana/bamf/application/290671880
> Jan  7 14:13:04 xxx unity-panel-ser[2292]: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx unity-panel-ser[2292]: Failed to fetch xid: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx unity-panel-ser[2292]: Failed to fetch property `_GTK_UNIQUE_BUS_NAME': GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx unity-panel-ser[2292]: Failed to fetch path: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface 'org.ayatana.bamf.window' on object at path /org/ayatana/bamf/window/52428804
> Jan  7 14:13:04 xxx unity-panel-ser[2292]: menus_destroyed: assertion 'IS_WINDOW_MENU(wm)' failed


And this says something about GTK which might be the culprit after all:

> 7 14:36:18 xxx unity-panel-ser[2292]: Getting layout failed: Operation was cancelled
> Jan  7 14:36:18 xxx unity-panel-ser[2292]: message repeated 621 times: [ Getting layout failed: Operation was cancelled]
> Jan  7 14:36:19 xxx compiz[2260]: javaldx: Could not find a Java Runtime Environment!
> Jan  7 14:36:19 xxx compiz[2260]: Warning: failed to read path from javaldx
> Jan  7 14:36:20 xxx soffice.bin[4219]: gtk_grid_attach: assertion 'GTK_IS_GRID (grid)' failed

**Comment by glannes31** [comment]
Hello, could you uninstall owncloud and try to install with : 

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/ /' > /etc/apt/sources.list.d/owncloud-client.list"
sudo apt-get update
sudo apt-get install owncloud-client

I have the same OS  and i have no proble with this install

**Comment by DPTJKKVH** [comment]
@glannes31 This could be a workaround but isn't a fix. I will try it out later today or at the weekend. If it really works with the 14.04 repo version this is most likely a Qt4/5 issue. Or should I say **THE Qt4/5 issue** we had last year? ;)

**Comment by guruz** [comment]
You could also try a 2.3 nightly which might help there. 

> Version 2.1.1+dfsg-1ubuntu1.1.

This is too old, sorry.

Plus we don't know what Ubuntu had been doing to this package.

What @glannes31  suggested is good:)

**Comment by DPTJKKVH** [comment]
Could you please open this up again? I have the exact same problem with an unmodified and recent package from the opensuse repo on Ubuntu 16.10.

Ubuntu 16.10 / Unity 7
Owncloud Client: 2.2.4
Built from Git revision eaeed0 on Jan 4 2017, 21:04:22 using Qt 5.6.1, OpenSSL 1.0.2g 1 Mar 2016

For more information please see my log files.

Using the 14.04 repo is neither a fix nor a solution if there is a 16.10 repo with this bug. It's a workaround at best and I'd like to help finding out what is causing this bug.

**Comment by guruz** [comment]
@DPTJKKVH OK! Please also have a look at https://github.com/owncloud/client/issues?utf8=%E2%9C%93&q=is%3Aissue%20%20Ubuntu%20tray%20

**Comment by DPTJKKVH** [comment]
I'm not 100% sure what you meant with directing me to the search but I read through seemingly related issues and all I could gather is that it's probably a Qt5 issue and that you might have a fix `OWNCLOUD_MINIMAL_TRAY_MENU` present in 2.3.0. 

Though I'm not sure if this is actually the same bug. The symptoms are very similar to mine but nobody else had the same syslog events like me or didn't post any logs to begin with.
Is there anything I can do to help you pinpoint the exact problem or matching it to an existing issue?

**Comment by johnc1984** [comment]
@DPTJKKVH

How can i help here, how/where do i get the logs?

**Comment by ckamm** [comment]
@DPTJKKVH Have you tried with `OWNCLOUD_MINIMAL_TRAY_MENU` to check whether that cluster of issues is related to your issue?

**Comment by DPTJKKVH** [comment]
No but I'd love to try. How do I enable this option? (I don't know about environment variables and compiling from source though...)

**Comment by ckamm** [comment]
@DPTJKKVH Quit owncloud. Open a shell. Type
```
OWNCLOUD_MINIMAL_TRAY_MENU=1 owncloud
```
to start with that environment variable set.

**Comment by DPTJKKVH** [comment]
I thoroughly tested running the client with this and had neither any
suspicious syslog events nor crashes or slowdowns. Since this option
also removed all but the "exit owncloud" option from the indicator menu
I think my "/MenuBar" syslog entries are the most relevant to this bug.

Thanks for the workaround and I hope my logs can help you find the exact
cause for this bug. If you need anything else please let me know.

**Comment by ckamm** [comment]
@DPTJKKVH I'm glad the workaround helps. Would you be able to test with a 2.3 build? I want to know whether all the tray fixes that went into that version will make it work without the workaround. 

You can usually get nightly builds from https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/owncloud-client .

**Comment by DPTJKKVH** [comment]
Unfortunately I can't for two reasons. :(

1.
I don't have a testing setup and I store very important data on the
server. If this data is lost due to an error in the nightly build I have
to restore from backup which will anger many other people on the server.

2.
After a MySQL update I have severe performance issues that I wasn't able
to fix yet.

Is there something like a test environment for owncloud?

**Comment by hodyroff** [comment]
"Is there something like a test environment for owncloud?"
Yes, you can test against demo.owncloud.org

**Comment by ckamm** [comment]
Feel free to reopen if tests with 2.3 suggest this issue still exists.
