### ISSUE TITLE
cmake gives error while configuring the client build on OS X

### ISSUE THREAD

**Issue by agrawal-mohit** [owncloud/client#5434]
I am building the client app on OS X, the error happens when i execute this command on the terminal from the `owncloud-client/client-build` directory

`cmake -DCMAKE_BUILD_TYPE="Debug" ../install`

### Expected behaviour
Build happens successfully without errors

### Actual behaviour
The terminal shows this 
 
`CMake Error: The source "<project location>/owncloud-client/install/CMakeLists.txt" does not match the source "<project location>/owncloud-client/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.`

### Steps to reproduce

1. Clone the latest versions of the client from Git as follows:
```
git clone git://github.com/owncloud/client.git owncloud-client
cd owncloud-client
git submodule init
git submodule update
```

Create the build directory:
```
mkdir client-build
cd client-build
```

Configure the client build:
`cmake -DCMAKE_BUILD_TYPE="Debug" ../install`

### Client configuration
Client version: Latest master branch
Operating system: OS X 10.10.5 Yosemite
OpenSSL 1.0.2h  3 May 2016

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by SamuAlfageme** [comment]
@agrawal-mohit This usually happens because you changed/included some new argument to CMake after a previous run and your config now is colliding with the cached. Try removing the `CMakeCache.txt` in your build dir. or even remove and create a new `client-build` dir. and launch CMake again. 

To ask for help in the future, try https://central.owncloud.org/ instead of the issue tracker.
