### ISSUE TITLE
References to "owncloud" still require renaming

### ISSUE THREAD

**Issue by gandalf3** [owncloud/client#5436]
As may be apparent from the title, **This only applies to nextcloud!**
Unfortunately I can't find where to report this; https://github.com/nextcloud/client_theming says to report anything not theme-related issues here, but this seems like entirely the wrong place for nextcloud-only issues..

----

### Expected behaviour
Nextcloud would
* Add a right click menu entry to dolphin for sharing files
* Overlay various icons on the synced dir and files within (also in dolphin)
* *Not* attempt to execute `/usr/bin/owncloud` when running `systemctl start nextcloud`.

### Actual behaviour
* No right click entry is added. Changing `owncloud` to `nextcloud` in `/usr/share/kservices5/nextclouddolphinactionplugin.desktop` fixes it.
* No icons are overlayed. I somewhat suspect naming is to blame here as well, as `strings /usr/lib/qt/plugins/kf5/overlayicon/nextclouddolphinoverlayplugin.so` reveals many references to owncloud stuff.
* `nextcloud-client.service` executes `/usr/bin/owncloud`.

### Steps to reproduce
1. Install owncloud-client (either the stable or -git version) from the [AUR](https://aur.archlinux.org/packages/?O=0&K=owncloud-client)

**Comment by dragotin** [comment]
These sound like integration/branding issues with nextcloud which I am sure the nc client devs and integrators will be happy to fix. Sorry that I am asking you to re-open it in the nc bugtracker. They will come back to us with a patch.
