### ISSUE TITLE
[UX] Tap finished upload in upload list must open folder

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#5442]
### Steps

1. Upload many pictures using the "share" feature and select "ownCloud" as target
1. Navigate to different folders in the ownCloud app during the upload (because why not?)
1. Wait for upload to finish and all notifications to disappear
1. Go to upload list (need to go to the root to find the menu item)
1. Tap on one of the successful uploads

### Expected
App navigates to the folder where the file was uploaded, maybe select it by default.

### Actual
Tapping an entry does nothing

**Comment by PVince81** [comment]
DAMMIT, I did it again... Wrong repo

**Comment by phil-davis** [comment]
Yeh, it would have been nice if the desktop (laptop, server running as client... it does not have to be really a machine on (or under) a desktop) client had been named with an extra word. Perhaps desktop-client would be understood fine as also applying to laptops, or maybe there is some other word in use these days to cover all variations of "a traditional computer".
