### ISSUE TITLE
Wrong Desktop version is shown in the documentation

### ISSUE THREAD

**Issue by davitol** [owncloud/client#5444]
https://doc.owncloud.org/desktop/2.2/ownCloudClientManual.pdf 

The version shown in the link above is 2.2.5 😟 

![screenshot 2017-01-11 10 22 00](https://cloud.githubusercontent.com/assets/10596560/21842696/3a1a9dc4-d7e8-11e6-9707-58238fc7b1ee.png)

@settermjd

**Comment by settermjd** [comment]
@davitol thanks for raising this. I'll get the docs corrected.

**Comment by settermjd** [comment]
@davitol that's the correct version, based on the linked binaries.

**Comment by SamuAlfageme** [comment]
@settermjd nope it's not.

> The version shown **in the link above** is 2.2.5

![screenshot 2017-01-18 10 59 20](https://cloud.githubusercontent.com/assets/2644445/22059482/3a45cd70-dd6d-11e6-9aa3-3924afe8fbdf.png)

Latest stable version: https://owncloud.org/install/#install-clients. `2.2.5` doesn't exist.

**Comment by settermjd** [comment]
According to the binaries, it's correct. But, according to the manual, I agree, it's not.

**Comment by SamuAlfageme** [comment]
@settermjd this issue is about the manual, that should say:

> Release 2.2.4

According to the binaries: e.g. https://download.owncloud.com/desktop/stable/ownCloud-2.2.4.3709.pkg

```
$ owncloud --version
ownCloud version 2.2.4 (build 3709)
Using Qt 5.4.0
```

**Comment by settermjd** [comment]
ah ok. my bad. thanks for clarifying.
