### ISSUE TITLE
[OS X][Mac OS 10.11] Authentication failed for any account

### ISSUE THREAD

**Issue by glannes31** [owncloud/client#5448]
### Expected behaviour
Authentication  successful

### Actual behaviour
Authentication failed with any account

### Steps to reproduce
1. Enter the server name
2. Enter credentials
3. Click Next

### Server configuration
Operating system: Redhat 

Web server: Apache

Database: Mysql/MariaDB

PHP version:5

ownCloud version:7.0.5

### Client configuration
Client version:2.2.4

Operating system: Mac OS

OS language: English

### Logs

https://gist.github.com/glannes31/8ae3b88137034d5cba68e746324d9414

**Comment by guruz** [comment]
Are you getting to the user/password input fields at all in the wizard?

Server 7.0.5 is also getting old..

**Comment by glannes31** [comment]
Hello,
I know that the server is old .. I getting the user password fields . It's here that i have the authentication failed.

**Comment by glannes31** [comment]
Hello, any idea? 
All those actions failed: 

Removal of all the hidden files of the program: hide, plist, VAr, comapplesharelist,… 
- Removal of the software with a program which searches all the occurrences (appcleaner); reinstalment of the software 
- test on another session 
- cleaning of OS (hides system, masks to use, services of launching, masks shared DYLD, XPC aitches, authorizations repair, checking of the file system OK

**Comment by glannes31** [comment]
Hello, 

2.2.4 (build 3709) . An upgrade on Sierra does nothing

**Comment by guruz** [comment]
Does it work with any other desktop?
Does it work from the iOS or Android app?
Does it work from the webinterface?

If I look at your server from the command line I'm very confused to get multiple cookies for the same cookie name ( @PVince81 did you ever see something like this?)

```
guruz@mgmacbookpro ~ $ curl -v 'https://mycore.core-cloud.net/remote.php/webdav' -H 'Authorization: Basic dXNlcjpwYXNz'
*   Trying 194.57.138.240...
* Connected to mycore.core-cloud.net (194.57.138.240) port 443 (#0)
* TLS 1.2 connection using TLS_DHE_RSA_WITH_AES_256_CBC_SHA
* Server certificate: mycore.core-cloud.net
* Server certificate: TERENA SSL CA 3
* Server certificate: DigiCert Assured ID Root CA
> GET /remote.php/webdav HTTP/1.1
> Host: mycore.core-cloud.net
> User-Agent: curl/7.43.0
> Accept: */*
> Authorization: Basic dXNlcjpwYXNz
> 
< HTTP/1.1 401 Unauthorized
< Date: Wed, 18 Jan 2017 10:50:58 GMT
< Server: Apache/2.2.15 (Red Hat)
< X-Powered-By: PHP/5.4.16
< Set-Cookie: ocfcb4e58640=8r4niqq6q7dsjj0ovivqshtb30; path=/; HttpOnly
< Expires: Thu, 19 Nov 1981 08:52:00 GMT
< Cache-Control: no-store, no-cache, must-revalidate, post-check=0, pre-check=0
< Pragma: no-cache
< Strict-Transport-Security: max-age=0
< X-XSS-Protection: 1; mode=block
< X-Content-Type-Options: nosniff
< X-Frame-Options: Sameorigin
< Content-Security-Policy: default-src 'self'; script-src 'self' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; frame-src *; img-src *; font-src 'self' data:; media-src *
< X-Robots-Tag: none
< Set-Cookie: ocfcb4e58640=94uici1ml88be597iblq62nju3; path=/; HttpOnly
< Set-Cookie: ocfcb4e58640=8nqsgognq9hjh3cf35sjaouft5; path=/; HttpOnly
< Set-Cookie: ocfcb4e58640=m0hupclimt7s474p2n7okaqfp1; path=/; HttpOnly
< Set-Cookie: ocfcb4e58640=u0ng51njoun523mm90ml5bk7f4; path=/; HttpOnly
< Set-Cookie: ocfcb4e58640=c022mhb34eni2vv2ajugr0k9m6; path=/; HttpOnly
< Set-Cookie: ocfcb4e58640=pnv3mcuqev2d394j4murs3t1t2; path=/; HttpOnly
< WWW-Authenticate: Basic realm="Service My CoRe"
< Content-Length: 285
< Content-Type: application/xml; charset=utf-8
< 
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotAuthenticated</s:exception>
  <s:message>Username or password does not match</s:message>
  <s:sabredav-version>1.8.12</s:sabredav-version>
</d:error>
* Connection #0 to host mycore.core-cloud.net left intact
```

**Comment by glannes31** [comment]
It's Okay from another interface

**Comment by guruz** [comment]
Another interface? You mean another IP for the same server?

**Comment by glannes31** [comment]
Web, Ios, Android , Windows OK .

**Comment by glannes31** [comment]
The problem is just from this Mac.

**Comment by guruz** [comment]
Then please enter that curl command from both the working Mac and the non-working Mac and paste output here

```
 curl -v 'https://mycore.core-cloud.net/remote.php/webdav' -H 'Authorization: Basic dXNlcjpwYXNz'
```

**Comment by glannes31** [comment]
could you give me the command with Login and password? witch options with curl?

**Comment by guruz** [comment]
@glannes31 I wrote the command above with a bogus user/password just to see if you receive different things from different machines.
You should be able to just run that, it won't damage anything

**Comment by glannes31** [comment]
I try to get the result with a simple Finder  Webdav Connection . I will answer you later
