### ISSUE TITLE
Propagator: Create direct sub job of PropagateDirectory only when running it

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5451]
```
<guruz> ogoffart: could a syncjob be replaced with a placeholdersyncob with less info that creates the real one when started?
<jturcotte> guruz: We could just create the PropagateDirectory, and store a list of their sub-SyncFileItemPtr.
<jturcotte> And create the real job right before scheduling it.
```

**Comment by guruz** [comment]
@ogoffart Is this feasible for 2.3?

@mrow4a @jturcotte FYI

**Comment by guruz** [comment]
... or maybe not.
@mrow4a 's bundling is solving the same problem?

**Comment by mrow4a** [comment]
@guruz Bundling as a bundle itself works only for upload, and small files.

**Comment by guruz** [comment]
@mrow4a Indeed. So would you say this is orthogonal?
(Although it could also work for small file downloads and for deletes)

**Comment by mrow4a** [comment]
I think it would be great to store in "Containers" just item pointers, and Bundle is yet another container. :>

**Comment by jturcotte** [comment]
Done in 16ad3d5c88c16e528635437743ab480837df72fe.
