### ISSUE TITLE
PropagateDownload: Make _stopwatch a QScopedPointer?

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5455]
And only allocate when using?
Would save 1 pointer in memory.

**Comment by ogoffart** [comment]
This would make the memory usage worse wouldn't it? Because it would always be used at peek memory.

The question is if we need the _stopwatch at all.  It's only used for the log, but i would not say it is usefull.

**Comment by jturcotte** [comment]
I could rename the `UNIT_TESTING` define to `TESTING` and put the stopwatch behind that define. What do you think?

**Comment by guruz** [comment]
> What do you think?

ok, let's have this as debug only

**Comment by jturcotte** [comment]
Let's track in #5456
