### ISSUE TITLE
PropagateUpload: Optimize memory usage of time measuring 

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5456]
Some ideas:
* Unify _stopWatch and _duration?
* clear() _stopWatch after job is done
* Have _stopWatch and _duration as QScopedPointer analogous to  https://github.com/owncloud/client/issues/5455

**Comment by jturcotte** [comment]
Will disable in production builds as discussed in https://github.com/owncloud/client/issues/5455#issuecomment-275362731.
