### ISSUE TITLE
[Linux] Unrelated SSL certificates error

### ISSUE THREAD

**Issue by Webbeh** [owncloud/client#5460]
http://imgur.com/a/LiWJ1

Since I installed owncloud client a year ago, I've had this issue from time to time, on **every computer** that has owncloud installed.

Those popups are definitely coming from OwnCloud : 
- It's seen in the log window
- It has the owncloud client logo
- When there's a popup, owncloud freezes all activity
- Killing owncloud shuts down the popup

The popup shows that the certificate from the last website I visited is being used instead of my server's one...

Today, I've got this error every few minutes, sometimes the error doesn't appear at all.

It seems to be caused by the notifications plugin, although there is no current notification in the activity.

### Server configuration
Operating system:
Linux paris.edelblack.ch 4.4.39-1-lts #1 SMP Thu Dec 15 21:10:18 CET 2016 x86_64 GNU/Linux

Web server: 
Server version: Apache/2.4.25 (Unix)
Server built:   Dec 20 2016 13:02:22

Database:
mysql  Ver 15.1 Distrib 10.1.20-MariaDB, for Linux (x86_64) using readline 5.1

PHP version:
7.0.14

ownCloud version:
9.1.3

Storage backend (external storage):
File, using Redis server (v=3.2.6 sha=00000000:0 malloc=jemalloc-4.0.3 bits=64 build=9b67e28e3565a12f)

### Client configuration
Client version: 2.4.4

Operating system:
ArchLinux 
Linux elite.edelblack.ch 4.8.15-rt10-1-rt #1 SMP PREEMPT RT Sat Dec 31 17:59:23 CET 2016 x86_64 GNU/Linux

OS language:
English

Installation path of client:
/usr/share/owncloud

### Logs

Log of what happens at the moment of a popup appearing, the last two lines being when I cancel the popup : 
```
01-15 14:29:09:940 30495 OCC::AbstractNetworkJob::start: !!! OCC::JsonApiJob created for "https://levert.ch" + "ocs/v2.php/apps/notifications/api/v1/notifications" "OCC::ServerNotificationHandler"
01-15 14:29:17:940 30495 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
01-15 14:29:17:942 30495 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://levert.ch" + "/" "OCC::ConnectionValidator"
01-15 14:29:21:473 30495 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(OperationCanceledError) "Operation canceled" QVariant(Invalid)
01-15 14:29:21:475 30495 OCC::Account::resetNetworkAccessManager: Resetting QNAM
```

Log of two errors happening later, less than one minute apart : 
https://gist.github.com/Webbeh/828a649d77a787d932ffc0e3bcb9e7f3

Their screenshots : 
http://imgur.com/a/jWzzk

**Comment by Webbeh** [comment]
I want to add that the issue happens a lot more when I'm on an unreliable or slow internet connection (phone tethering, for example).

**Comment by guruz** [comment]
I'm not sure I understand. Why would it show a certificate for Imgur?
Are you working there and it's related to your VPN gateway / captive portal ?

**Comment by Webbeh** [comment]
That's exactly the issue, the error is based on a totall‎y unrelated certificate, which is, oddly enough, always the one of the last website I visited ‎ -> it changes every time.No proxy or VPN.Maybe owncloud is reading the wrong SSL cache?                                                                                                                                                                                                                                                                                                                                                                                                                    From: Markus GoetzSent: Tuesday, 17 January 2017 15:26To: owncloud/clientReply To: owncloud/clientCc: Nicolas Glassey; AuthorSubject: Re: [owncloud/client] [Linux] Unrelated SSL certificates error (#5460)I'm not sure I understand. Why would it show a certificate for Imgur?
Are you working there and it's related to your VPN gateway / captive portal ?

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/owncloud/client","title":"owncloud/client","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/owncloud/client"}},"updates":{"snippets":[{"icon":"PERSON","message":"@guruz in #5460: I'm not sure I understand. Why would it show a certificate for Imgur?\r\nAre you working there and it's related to your VPN gateway / captive portal ?"}],"action":{"name":"View Issue","url":"https://github.com/owncloud/client/issues/5460#issuecomment-273179314"}}}

**Comment by guruz** [comment]
We're shipping our own OpenSSL and Qt which should mean we're independant from whatever macOS might be doing.

It's odd, I never heard of this issue.

Are you using a desktop firewall application on your mac? Or any proxies? etc

**Comment by Webbeh** [comment]
I don't want to sound rude, but you should read everything on a bug report, because i'm not on a Mac and the answer for proxies is in my last comment.But no, no proxies or VPN.                                                                                                                                                                                                                From: Markus GoetzSent: Tuesday, 17 January 2017 16:21To: owncloud/clientReply To: owncloud/clientCc: Nicolas Glassey; AuthorSubject: Re: [owncloud/client] [Linux] Unrelated SSL certificates error (#5460)We're shipping our own OpenSSL and Qt which should mean we're independant from whatever macOS might be doing.
It's odd, I never heard of this issue.
Are you using a desktop firewall application on your mac? Or any proxies? etc

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/owncloud/client","title":"owncloud/client","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/owncloud/client"}},"updates":{"snippets":[{"icon":"PERSON","message":"@guruz in #5460: We're shipping our own OpenSSL and Qt which should mean we're independant from whatever macOS might be doing.\r\n\r\nIt's odd, I never heard of this issue.\r\n\r\nAre you using a desktop firewall application on your mac? Or any proxies? etc"}],"action":{"name":"View Issue","url":"https://github.com/owncloud/client/issues/5460#issuecomment-273199062"}}}

**Comment by guruz** [comment]
Mixed you up, sorry :-) Too many tabs.

**Comment by Webbeh** [comment]
Okay then.So I was saying, maybe owncloud is reading a cache that is being updated somewhere?                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         From: Markus GoetzSent: Tuesday, 17 January 2017 16:33To: owncloud/clientReply To: owncloud/clientCc: Nicolas Glassey; AuthorSubject: Re: [owncloud/client] [Linux] Unrelated SSL certificates error (#5460)Mixed you up, sorry :-) Too many tabs.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/owncloud/client","title":"owncloud/client","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/owncloud/client"}},"updates":{"snippets":[{"icon":"PERSON","message":"@guruz in #5460: Mixed you up, sorry :-) Too many tabs."}],"action":{"name":"View Issue","url":"https://github.com/owncloud/client/issues/5460#issuecomment-273202025"}}}

**Comment by guruz** [comment]
It would be an idea to install our Qt 5.6.2 based packages (they ship their own Qt)

https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client

**Comment by guruz** [comment]
the 2.5.0 release will even ship with Qt 5.10.1
