### ISSUE TITLE
Error (Sabre\DAV\Exception\Forbidden) on Sync/Upload

### ISSUE THREAD

**Issue by nickian** [owncloud/client#5461]
I recently moved my Owncloud installations to a new server. After the move, I can still sync/download from the server, but I can't seem to upload anything from the local Nextcloud clients on Windows or Mac. I get this error:

`Test.txt: Error downloading https://mysite.com/files/remote.php/webdav/Test.txt - server replied: Forbidden (Sabre\DAV\Exception\Forbidden)`

Any idea why this might be happening? Doesn't seem to be a permissions issue. I made sure all of the files were owned by www-data:www-data and tried temporarily setting everything to chmod 777. Didn't make a difference.

Thanks.

### Server configuration
**Operating system:** Ubuntu 16.04
**Web server:** Apache
**PHP version:** 7.0.4
**ownCloud version:** 10.0.2
**Are you using encryption:** No

#### ownCloud log

`Exception: {"Message":"HTTP\/1.1 403 Forbidden","Exception":"Sabre\\DAV\\Exception\\Forbidden","Code":0,"Trace":"#0 \/home\/mysite\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1036): OCA\\DAV\\Connector\\Sabre\\Directory->createFile('Test.txt', Resource id #93)\n#1 \/home\/mysite\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(523): Sabre\\DAV\\Server->createFile('Test.txt', Resource id #93, NULL)\n#2 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#3 \/home\/mysite\/www\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#4 \/home\/mysite\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#5 \/home\/mysite\/www\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#6 \/home\/mysite\/www\/apps\/dav\/appinfo\/v1\/webdav.php(60): Sabre\\DAV\\Server->exec()\n#7 \/home\/mysite\/www\/remote.php(165): require_once('\/home\/mysite\/f...')\n#8 {main}","File":"\/home\/mysite\/www\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php","Line":126,"User":"nick"}`

**Comment by guruz** [comment]
> ownCloud version: 10.0.2

> from the local Nextcloud clients

There must have been a mixup in your browser, this is the bugtracker for the ownCloud client. :)

**Comment by nickian** [comment]
There isn't a client for Nextcloud, is there? I thought it used the owncloud client?
