### ISSUE TITLE
Share with owncloud in multiaccount folders only works for the first account created

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5462]
As pointed in https://github.com/owncloud/client/issues/3764#issuecomment-270632561 the `Share with ownCloud` is troublesome for shared (meaning multiaccount  #3764) folders. Couple of issues that should be addressed:

- [ ] Right now, only the first user that created the folder sync connection get to share files from the contextual menu. And you get `SocketApi:  Sending message:  "SHARE:NOTSYNCED:/file.txt"` until the new user's files that you are trying to share are uploaded to the first user account. (Related: https://github.com/owncloud/client/issues/4608)
- [ ] An account picker should be implemented to choose which account should originate the share 

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/21977710/9923be34-dbd7-11e6-992f-b8e616b08127.png"/>
</p>

Also, consider @phil-davis concerns in https://github.com/owncloud/client/issues/3764#issuecomment-272838242) :

> And so the client needs to know which upstream servers have the file - e.g. if it has been just downloaded from account1 and is yet to finish uploading to account2 - so it can **present only the valid accounts to share from in the account picker.**

**Comment by ckamm** [comment]
@SamuAlfageme @jturcotte The "one folder, multiple accounts" feature leads to edge cases that we sometimes intentionally don't address (like selective sync, now this one) -- it may be a good idea to pop up a warning when users configure this kind of setup, letting them know that it's a possible, but weakly supported configuration?

As far as I remember there was no pressing need for having the feature.

**Comment by TheOneRing** [comment]
Multiple accounts for one folder is no longer supported
