### ISSUE TITLE
TLS v1.1 and v1.2 Not Supported (macOS)

### ISSUE THREAD

**Issue by thomaskonrad** [owncloud/client#5465]
When allowing only TLS v1.1 and TLS v1.2 on the server, the macOS ownCloud client is unable to connect. Only TLS v1.0 and below seem to be supported.

TLS v1.2 is now 9 years old, TLS v1.1 was standardised 11 years ago - it would be nice to have support for more recent TLS versions that the one from 1999.

I'm using the macOS ownCloud client version 2.2.4. The error message is:

```
No connection to ownCloud at https://myserver.com. Connection closed
```

**Comment by glannes31** [comment]
Hello ,
Our Oc Server is 7.0.5 with the TLS V1.1 and TLS V1.2 activated . We have no problem .

**Comment by thomaskonrad** [comment]
Do you have TLS v1.0 enabled as well? The error occurs when I _disable_ TLS v1.0. When I enable TLS v1.0, v1.1, and v1.2, it works, but the ownCloud client chooses TLS v1.0.

I have the latest stable version, but this does not depend on ownCloud, but on the webserver. I use nginx.

**Comment by guruz** [comment]
My 2.2.4 client on macOS uses 1.2, I can see that by clicking the lock icon in the UI.
What does it show for you?
Can you tell us the exact version/package you used? You can see that in the settings dialog, including build number.

**Comment by tflidd** [comment]
a list of supported ciphers would be good as well. You probably have disabled some ciphers that others do use with TLSv1.1 or TLSv1.2.

**Comment by thomaskonrad** [comment]
It says here that it uses SSLv3, RSA, DH, AES(256), which is bullshit, because SSLv3 is disabled for sure.

![screen shot 2017-01-21 at 18 20 30](https://cloud.githubusercontent.com/assets/2149539/22176253/5dd7705e-e006-11e6-8c9d-a6c498b3ef82.png)

This is my config on nginx:

```
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
ssl_ciphers 'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
ssl_prefer_server_ciphers on;
ssl_dhparam /etc/ssl/dhparams.pem;
ssl_session_cache shared:SSL:10m;
ssl_stapling on;
ssl_stapling_verify on;
```

The Qualys SSL test confirms this:

```
Protocols
TLS 1.2	Yes
TLS 1.1	Yes
TLS 1.0	Yes
SSL 3	No
SSL 2	No
```

I use a pretty modern set of ciphers, but it is very weird that ownCloud which sees itself as very security-aware does not support them.

**Comment by thomaskonrad** [comment]
This is the complete list of supported ciphers of my server:

```
# TLS 1.2 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 (0xc030)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	256
TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 (0xc02f)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	128
TLS_DHE_RSA_WITH_AES_256_GCM_SHA384 (0x9f)   DH 2048 bits   FS	256
TLS_DHE_RSA_WITH_AES_128_GCM_SHA256 (0x9e)   DH 2048 bits   FS	128
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA384 (0xc028)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	256
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA256 (0x6b)   DH 2048 bits   FS	256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x39)   DH 2048 bits   FS	256

# TLS 1.1 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x39)   DH 2048 bits   FS	256

# TLS 1.0 (suites in server-preferred order)
TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA (0xc014)   ECDH secp256r1 (eq. 3072 bits RSA)   FS	256
TLS_DHE_RSA_WITH_AES_256_CBC_SHA (0x39)   DH 2048 bits   FS	256
```

Is there a chance to see the list of ciphers that are supported by the ownCloud / Nextcloud client?

**Comment by thomaskonrad** [comment]
It seems to be an issue of the Nextcloud client. I posted this issue here because I thought the [Nextcloud client](https://github.com/nextcloud/client_theming) uses this repo as a submodule, which is true, but still there seems to be a difference in the handling of SSL/TLS connections. Closing this.
