### ISSUE TITLE
OSX Client compilation problem

### ISSUE THREAD

**Issue by waheni** [owncloud/client#5475]
I am trying to compile the owncloud client on OSX but i get this error 

 cmake -DCMAKE_BUILD_TYPE="Debug"  -DCMAKE_INSTALL_PREFIX=../install  ../owncloud/
-- The C compiler identification is AppleClang 7.0.0.7000072
-- The CXX compiler identification is AppleClang 7.0.0.7000072
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build of crashreporter disabled.
-- GIT_SHA1 3836339fe7792a8de201e2a52a4c72e435562378
CMake Error at /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR: Found unsuitable version "0.9.8}", but
  required is at least "1.0.0" (found
  /usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:386 (_FPHSA_FAILURE_MESSAGE)
  /usr/local/Cellar/cmake/3.6.2/share/cmake/Modules/FindOpenSSL.cmake:370 (find_package_handle_standard_args)
  CMakeLists.txt:157 (find_package)

Can any one help me 
thanks

**Comment by glannes31** [comment]
Hello,
Open SSL is installed ?  

Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
system variable OPENSSL_ROOT_DIR: Found unsuitable version "0.9.8}", but
required is at least "1.0.0" (found
/usr/lib/libssl.dylib;/usr/lib/libcrypto.dylib)

**Comment by SamuAlfageme** [comment]
Hi @waheni for this kind of questions instead of issue reports it's better if you ask in https://central.owncloud.org, there's more chances you get an answer there. 

If you, like me for example, are using homebrew's openssl, you can find the info you need after the install (`brew install openssl`) or running:

```
$ brew info openssl
openssl: stable 1.0.2j (bottled) [keg-only]
SSL/TLS cryptography library
https://openssl.org/

[...]

    LDFLAGS:  -L/usr/local/opt/openssl/lib
    CPPFLAGS: -I/usr/local/opt/openssl/include
```
Then, you need to specify these values to `cmake` in the form of:

```
-DOPENSSL_ROOT_DIR=/usr/local/opt/openssl
-DOPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include
-DOPENSSL_LIBRARIES=/usr/local/opt/openssl/lib
```

If you have more remaining issues you can ask them in: https://central.owncloud.org
