### ISSUE TITLE
Logged out accounts stay "Waiting" if unpaused

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5477]
Thought I had already reported this:

### Expected behavior
It's not possible to click (i.e. button disabled) on resume either in the tray menu or the account view for any folder sync connection when the account is logged out.

### Actual behavior
It's indeed possible and the account is "`Waiting...`".
![waiting...](http://i.imgur.com/ekfq31m.gif)

### Steps to reproduce
1. Pause a folder sync connection
2. Log out of the FSC's account
3. Resume the sync of the FSC

**Comment by ckamm** [comment]
What happens here is that whether a folder is paused and whether an account is logged in are orthogonal. When the account is logged out and you resume a folder, the folder gets queued. But it can't sync, so it just shows "Waiting...". 

We could adjust the text to say "Waiting for connectivity" or something. Would that make sense to you, @SamuAlfageme ?

**Comment by SamuAlfageme** [comment]
@ckamm hm, I was looking at this as a single state for the account (logged out) rather than 2 (logged out paused/unpaused) for the folder sync connection. But it makes sense to differentiate up to some point. The user might want to log in and start the sync/with it paused. 

We can settle with a label change to clarify; something like you suggest.

**Comment by ckamm** [comment]
Trivial fix in https://github.com/ckamm/owncloud-client/tree/folder-ui-msg (I didn't change the message, but just treat these folders similar to paused folders, which removes the inconsistency)

**Comment by ckamm** [comment]
@SamuAlfageme Merged into 2.3 branch.

**Comment by SamuAlfageme** [comment]
Nice! 👍
