### ISSUE TITLE
idea: zip files before upload

### ISSUE THREAD

**Issue by davidak** [owncloud/client#548]
some files can be good compressed like textfiles, bitmap images, wav audio... some not like jpg, mp4, mp3

the client can decide if its better to sync compressed on the extension.

if there are 100 textfiles, the client can compress them in one zip-file and decompress them on the server... 

in my test-szenario https://github.com/owncloud/mirall/issues/547 are about 500.000 small textfiles, on disk ~2GB ... compressed only 108MB!

what do you think?

but please work first on a rock-solid sync befor implementing new features like this!

**Comment by hodyroff** [comment]
@mrow4a this can be closed, or? Not an approach we will take?

**Comment by mrow4a** [comment]
I think the topic is still ongoing, we evaluated advantages and disadvantages of Bundling compared to HTTP2, both technical (https://www.youtube.com/watch?v=9RecQUqddfs) and thinking about code complexity and maintenance, and for now Bundling is too heavy API and protocol change to maintain (and is basicaly HTTP workaround - considered both as obsolete practice https://medium.com/@asyncmax/the-right-way-to-bundle-your-assets-for-faster-sites-over-http-2-437c37efe3ff, http://stackoverflow.com/questions/30861591/why-bundle-optimizations-are-no-longer-a-concern-in-http-2 but might be viable option in the future also bundling small group of files to fight latency and maybe batch multiple files in single transaction in DB). ZIP is no-go here for sure, if so I think protocol change needs to be done as in my prototype.

**Comment by DeepDiver1975** [comment]
will  not happen ....
