### ISSUE TITLE
Unify _contentChecksumType of all SyncFileItem and _transmissionChecksumType of PropagateUpload in memory

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5481]
Not sure which Qt data structure is good there if we don't go for changing this to a global enum.

**Comment by ogoffart** [comment]
Note that QByteArray is already implicitly shared. If the content checksum is the same as the transmission checksum (most likely the case), they are already shared in memory.

**Comment by guruz** [comment]
@ogoffart Sorry should clarify, this is meant to be about ....type.
To store all those strings only once.

**Comment by guruz** [comment]
Just noticed that we already do this kind of map-to-integer in the Journal DB.

```
CREATE TABLE checksumtype(id INTEGER PRIMARY KEY,name TEXT UNIQUE);
INSERT INTO "checksumtype" VALUES(1,'SHA1');
```

**Comment by jturcotte** [comment]
I think that 9d16ad844ca0d48bfdcc2fb69d535dea2906c394 should be enough to close this, no?

**Comment by guruz** [comment]
Hm maybe not because it's not for _transmissionChecksumType
I didn't dig deeper, not urgent currently after the recent improvements

**Comment by jturcotte** [comment]
`_transmissionChecksumType` also ultimately comes from `contentChecksumType()` without being modified, so it will use the same byte array data.
