### ISSUE TITLE
[Windows] Garbled text in the installation of windows client

### ISSUE THREAD

**Issue by acyang** [owncloud/client#5483]
### Expected behaviour
Correct text in the installation windows.

### Actual behaviour
Garbled text in the installation windows.
[https://dl.dropboxusercontent.com/u/5934422/owncloud.png](https://dl.dropboxusercontent.com/u/5934422/owncloud.png)

### Client configuration
Client version: 2.2.4.6408

Operating system: windows 7 professional

OS language: traditional chinese

Does anybody know to fix this problem?

**Comment by SamuAlfageme** [comment]
Hi! @acyang, we are aware of this situation as reported by other users in https://github.com/owncloud/client/issues/4960 and working to fix soon it as it's a problem with the software used to generate the installer. You can follow the discussion there as it's a duplicate.

Thanks for reporting!
