### ISSUE TITLE
Keep files option after aboutToRemoveAllFiles() signal ignores previously unchecked folders

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5484]
### Expected behavior
When trying to remove all files under a folder sync connection and cancelling the operation (i.e. the removal was a mistake) the local folder is restored to the original state, previous to the deletion operation. 

### Actual behavior
The previously unchecked folders are ignored and therefore, downloaded. See [this video](https://webmshare.com/play/WJmND) to see it reproduced. 

### Steps to reproduce
1. Uncheck some folders in a folder sync connection 
2. Remove all the files in the local folder sync connection
3. Select `Keep files` as resolution strategy

**Comment by ogoffart** [comment]
Ah, of course, the "keep file" option deletes the database which removes the blacklist.  We need to do something else.

**Comment by SamuAlfageme** [comment]
👍
