### ISSUE TITLE
[2.2.4][OS X] Client unusable due to excessive CPU usage

### ISSUE THREAD

**Issue by mlangiu** [owncloud/client#5487]
### Expected behaviour
Client syncing normally

### Actual behaviour
Client does not appear to sync and is unresponsive even after extended period of time, CPU usage at 100% and System starts becoming unresponsive if client is not killed

### Steps to reproduce
1. download [https://download.owncloud.com/desktop/stable/ownCloud-2.2.4.3709.pkg](latest client for MAC)
2. install
3. start

### Client configuration
Client version:
2.2.4.3709

Operating system:
OS X 10.12

OS language:
German

Installation path of client:
Macintosh HD/Applications

**Comment by guruz** [comment]
Would be cool to try 2.3pre1 and report back :-)

http://download.owncloud.com/desktop/daily/ownCloud-2.3.0.3979pre1.pkg

**Comment by mlangiu** [comment]
Hey guruz, thanks for the speedy reply. Here is my 

#Test:

- On Startup: CPU Load between 3 and 5 % (as opposed to 100% straight away in 2.2.4).
- When first scan for updated files is apparently  finished: CPU Load jumps to 100% and settings window/top bar icon become unresponsive again. 
- After ~5 min CPU usage drops to 0% and settings window reports done syncronization.
- After another minute or two a second scan starts, this time the CPU load maxes out during the search already.
- The previous two steps repeat with a period of approx. 5-10 min
- Adding an empty folder to the owncloud dir causes the client to draw full CPU again for a minute but seems to return to stable state.
- Adding a copy of a 10MB directory triggers a similar response, but for a slightly longer period of time.

# Summary

Since the temporary unresponsiveness of the client is a minor inconvenience to me, and the rest of the OS seems to be largely unaffected I am content with this temporary fix.
However during the search and sync phases the client (both settings 
 window and top bar icon) remains entirely unresponsive, so I suppose there's still some work to be done.

Let me know if you have other suggestions.

**Comment by guruz** [comment]
Thanks for testing. :)

What you request is basically https://github.com/owncloud/client/issues/3935

Regarding performance improvement for the detection of updates we have some upcoming ideas but there is no timeplan yet https://github.com/owncloud/client/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20label%3APerformance%20
