### ISSUE TITLE
Client should not allow modifying a write protected file

### ISSUE THREAD

**Issue by virtnix** [owncloud/client#5491]
### Steps to reproduce
1. Share a file to a user B with the option "Can Edit" unticked
2. User B : Once downloaded by the NC client, locally modify this file
3. Save the modified file

### Expected behaviour
User B should not be able to save the file, as it is write protected.

### Actual behaviour
File is locally saved, and the following error appears on the NC client :
25/01/2017 15:18:31, TODO_LIST, Nextcloud_test,Continue blacklisting: Error downloading https://share.infranix.eu/remote.php/webdav/TODO_LIST - server replied: Forbidden (Sabre\DAV\Exception\Forbidden)

File is then set as blacklisted on NC client

Problem is that once the file has been saved, there is no way for User B to "recover" the original file, the file being permanently blacklisted by the NC client.

I would suggest perhaps to :
1 - Find a way to "physically" avoid the User B to edit the file

If point 1 is not possible :
2 - Set locally a specific flag (there is already the green and blue one, perhaps a new red one? ) on the write protected files/folders, so that the user will be aware of the permissions set on them.
3 - If the file has been edited anyway, create an explicit warning on the NC client (This file is write protected !!), and propose to the User B to download again the original file

Thanks !!

**Comment by guruz** [comment]
Sorry, this is the bugtracker for the ownCloud client.

**Comment by virtnix** [comment]
This behaviour is exactly the same for Nextcloud as for Owncloud client, so users are affected in both cases. So would it be please possible to re-open this ticket ?

Thanks !!

**Comment by guruz** [comment]
Can you reproduce this with **ownCloud** client and **ownCloud** server? Version 2.3pre1? http://download.owncloud.com/desktop/daily/
Please create a log and attach here, then we can have a look.

**Comment by virtnix** [comment]
I have done a quick install of an owncloud server instance , and reproduced the problem with last owncloud client.

Here the server info : 

root@VirtualBox:/var/www/owncloud# sudo -u www-data php occ config:list system
{
    "system": {
        "instanceid": "ocf33x2kb80r",
        "passwordsalt": "***REMOVED SENSITIVE VALUE***",
        "secret": "***REMOVED SENSITIVE VALUE***",
        "trusted_domains": [
            "192.168.56.101"
        ],
        "datadirectory": "\/var\/www\/owncloud\/data",
        "overwrite.cli.url": "http:\/\/192.168.56.101",
        "dbtype": "mysql",
        "version": "9.1.3.1",
        "dbname": "owncloud",
        "dbhost": "127.0.0.1",
        "dbtableprefix": "oc_",
        "dbuser": "***REMOVED SENSITIVE VALUE***",
        "dbpassword": "***REMOVED SENSITIVE VALUE***",
        "logtimezone": "Europe\/Paris",
        "installed": true,
        "logfile": "\/var\/log\/owncloud\/owncloud.log",
        "debug": true
    }
}

Installed client version : ownCloud-2.3.0.6659pre1-setup

Same behaviour has already explained in my first post :
I am able to locally modify a read only shared file, which will afterward be blacklisted by the Owncloud client:
 27/01/2017 00:38:29,                                                   proc_owncloud,                 owncloud_toto,Error transferring http://192.168.56.101/remote.php/webdav/proc_owncloud - server replied: Forbidden (Sabre\DAV\Exception\Forbidden)

**Comment by ogoffart** [comment]
I tried to reproduce the problem on both linux and windows, but this works as expected.
When sharing as read-only the server sets the permission correctly in the permission field sent to the client. And the client mark the files as read only on the file system.
