### ISSUE TITLE
[OS X] Fix some UI problems after #5340

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5492]
Some changes were made to the new account wizard, and account/general settings tabs. Some of them are not visually nice.

- [x] **[Wizard, Settings]** The checkboxes are not aligned H/V:

![](https://cloud.githubusercontent.com/assets/2644445/22258989/e928fa92-e263-11e6-9c70-575316035231.png)

- [x] **[Account]** Some folder names are cropped after the line break.
- [ ] **[Account, Wizard]** The style of the buttons is not the native when that problem occurs (Same than https://github.com/owncloud/client/issues/4581#issuecomment-269325083)

![](https://cloud.githubusercontent.com/assets/2644445/22258727/087c299c-e263-11e6-86b1-0e02309c3ad6.png)

- [ ] **[Account]** Also, the links on the list of potential folder exclusions don't link anywhere (maybe they could highlight the entry on the list). This happens in all platforms though.

**Comment by ckamm** [comment]
Seems to really be OS X only, the first issue is not visible on linux. The magins and spacing on those widgets looks sane to me too.

**Comment by guruz** [comment]
Related https://github.com/owncloud/client/issues/5083

**Comment by guruz** [comment]
Might be something for @jturcotte our pixel perfectionist :-)

**Comment by jturcotte** [comment]
Layout issues are caused by https://bugreports.qt.io/browse/QTBUG-42457
I also can't seem to get `WA_LayoutUsesWidgetRect` to have any effect.

**Comment by jturcotte** [comment]
@SamuAlfageme I tried to reproduce it and the links work for me, they highlight the element in the selective sync list. Would you have a bit more detailed repro steps?

I also didn't see the native vs. non-native buttons issue.

**Comment by SamuAlfageme** [comment]
@jturcotte you're right, just tested in https://github.com/owncloud/client/commit/7a96e8a292c9d543ce772a5aadb76d36157b7dd2 and it's both highlighting the rows and listing all ext. sto. nicely without changing the style of the 3 buttons. 🎉 

I guess since the `newFolderLimitSpinBox` forces the Horizontal Layout to be a bit wider on OS X (dunno why doesn't happen the same in the rest of the platforms) there's no way to get the line spacing in the text to be the same 😕

![screenshot 2017-07-28 09 11 16](https://user-images.githubusercontent.com/2644445/28706471-beada63a-7374-11e7-92fb-ae4b69030983.png)

Closing here! 👍

**Comment by jturcotte** [comment]
@SamuAlfageme Unfortunately that's the best I could do because of https://bugreports.qt.io/browse/QTBUG-42457. I really don't know how people manage to ship nice UIs on macOS with this bug around (or this could explain why Qt applications always look a bit off).

**Comment by SamuAlfageme** [comment]
@jturcotte np, I understand. Great job here! 🙌
