### ISSUE TITLE
Improve message when deleting all files in the local sync folder conection (aboutToRemoveAllFiles)

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5494]
- [x] Give more details about why this message occurs, something like: 

> You are trying to remove all the files on your local sync folder `<folder>`. <br> These changes will be synchronized with your server, making your files unavailable unless restored. <br> Are you sure you want to remove all the files? 

- [x] [Windows] Make the dialog have focus over other windows, so it doesn't go minimized without picking a resolution strategy, etc.

**Comment by SamuAlfageme** [comment]
@CaptionF PR in https://github.com/owncloud/client/pull/5503 check this GIF: 

![on_top_dialog](https://cloud.githubusercontent.com/assets/2644445/22422752/61d46ba0-e6ee-11e6-8509-cadfc03b6089.gif)

**Comment by michaelstingl** [comment]
Sticky! 👍

**Comment by guruz** [comment]
Can we close this issue and keep the PR https://github.com/owncloud/client/pull/5503 in 2.3?
And someone (@ogoffart ?) adjusts the msg in the PR to what holger mentioned in 5503?

**Comment by SamuAlfageme** [comment]
@guruz sure!
