### ISSUE TITLE
Build SyncFileItemVector directly from QMap without going through QList

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5497]
Current code:
```
 SyncFileItemVector syncItems = _syncItemMap.values().toVector();
```

**Comment by guruz** [comment]
For 110k files, this takes 130msec on my macOS.
Not worth to optimize, @ogoffart @ckamm ?

It happens on main thread though.. whole ```slotDiscoveryJobFinished``` blocks main thread then for 16sec (if i'm understanding this correctly).. but that's more issue https://github.com/owncloud/client/issues/5356

**Comment by guruz** [comment]
Ah, without --logfile - and --debug it's only around 5.5 sec not 16 sec.

(FYI @jturcotte )

**Comment by ckamm** [comment]
@guruz If this line's only 130ms in your 110k test, I think we can close this ticket. It's O(N), so even for larger sync folders this will be far from the bottleneck. The the whole blocking slotDiscoveryJobFinished sounds like it could use optimization though.
