### ISSUE TITLE
owncloud icon aligned left in unity panel

### ISSUE THREAD

**Issue by schiran** [owncloud/client#5498]
I installed owncloud-client 2.2.4 on ubuntuy 14.04.

### Expected behaviour
I expect the owncloud-icon to appear in the unity-panel aligned to the right, next to all other symbols.

### Actual behaviour
The icon appears on the left, actually overlapping with the "close"-button of all windows

### Steps to reproduce
1. Install owncloud-client 2.2.4 on ubuntu 14.04

**Comment by juliad25** [comment]
I also have the same issue on Ubuntu 14.04 with kernel 3.13.0-107-generic x86_64. I didn't have any problems with updating before version 2.2.4. The icon was always in the correct position.

**Comment by Chessmasterrr** [comment]
I had the same problem, but it is already fixed with version 2.2.4-10.1.
See also https://github.com/owncloud/client/issues/4828.

**Comment by guruz** [comment]
Great, please re-open if it still occurs with latest updates.
