### ISSUE TITLE
Brandings: Don't migrate from ownCloud.cfg if branded config is not readable

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5499]
Unproven but plausible.

Issue found by @jturcotte 

In ```AccountManager::restore()``` we need to not ```restoreFromLegacySettings``` if the branded config is there and can't be read for locking or whatever reasons.

EDIT: We also should have more debug output when doing such a migration

**Comment by guruz** [comment]
Waiting for info from @michaelstingl

**Comment by michaelstingl** [comment]
@guruz plz check https://github.com/owncloud/enterprise/issues/1729#issuecomment-277098702

**Comment by ckamm** [comment]
@jturcotte @guruz If the settings were restored from the old `ownCloud/owncloud.cfg` path, we should see a `Migrate: checking old config` log message. That's the legacy-legacy code path. I'll add a debug message to the legacy path and check `QSettings::status`.

**Comment by ckamm** [comment]
Pull request: https://github.com/owncloud/client/pull/5523
