### ISSUE TITLE
Server replied: Locked and client didn't notified the user

### ISSUE THREAD

**Issue by tuxayo** [owncloud/client#5500]
### Expected behaviour
The client should notify of "server replied: Locked"

### Actual behaviour
It's logged but in the desktop notifications I see updated files but not this error.
`Error transferring https://example.org/remote.php/webdav/linux - server replied: Locked`
`Error transferring https://example.org/remote.php/webdav/prog - server replied: Locked`
So it's been 2 weeks without sync on two folders at the root that contain more that 70% of all the files synced.

### Client configuration
Client version: 2.2.4

Operating system: Arch Linux

OS language: en_US

Qt version used by client package (Linux only, see also Settings dialog):
`Built from Git revision eaeed0 on Sep 28 2016, 20:08:09 using Qt 5.7.0, OpenSSL 1.0.2j 26 Sep 2016`

Client package (From ownCloud or distro) (Linux only): owncloud-client 2.2.4-1

### Logs

1. Client logfile:
After running the client with `owncloud --logwindow`, waiting for sync and then pausing:
https://gitlab.com/snippets/934882

**Comment by dragotin** [comment]
This is most probably a server problem. You should check the server logs.

**Comment by tuxayo** [comment]
I agree that there is also a server issue that must be investigated. But here the issue is that the client didn't notify the user.

**Comment by hodyroff** [comment]
Don't understand how this can be reproduced. Please add info. Running against 9.1.4?

**Comment by ckamm** [comment]
@tuxayo Do you still have a client log that you could share? My expectation is that the error should be shown, then blacklisted for a bit (5 min initially). I can try to reproduce.

**Comment by ckamm** [comment]
@tuxayo The reason you're not seeing an error message is that the client currently assumes 423 is transient. So when it encounters it, it considers it a soft error (not shown to the user, but visible in Activity tab) and schedules another sync.

It seems like the client should track the error and eventually realize it's permanent and notify the user.

The special casing for 423 errors is done in our `classifyError()` function.

**Comment by ckamm** [comment]
@guruz You added this to 2.3.1, what were your thoughts here? 

What could be in scope for that in my opinion:
* Make 423 go to the blacklist. (it should stay a soft error initially, since in most cases retrying should make it not pop up again)
* Possibly: Escalate a repeated 423 to a NormalError?
* Show blacklisted entries in the "Not Synced" tab. I'm not sure whether this is already being done.

**Comment by ckamm** [comment]
Pull request: https://github.com/owncloud/client/pull/5548

**Comment by tuxayo** [comment]
> Don't understand how this can be reproduced. Please add info. Running against 9.1.4?

I renamed in my file manager two top level directories in my synced folder. And the folders that were locked were the old ones and due this error, the rename didn't get synced (as well as all latter changes).

I don't know if it's reproducible.

**Comment by SamuAlfageme** [comment]
I could not reproduce the locking state in server either. Let's close since these errors would not abort the sync (see https://github.com/owncloud/client/issues/5859#issuecomment-311607651) and that was the original root for this issue.
