### ISSUE TITLE
"Close" button is not translated

### ISSUE THREAD

**Issue by ldmpub** [owncloud/client#5501]
Hi,

Here is a screen capture for Nextcloud client under Windows: 2.2.4 (build 2), button is not available in french (or translation is not used in the code?):
![close not translated](https://cloud.githubusercontent.com/assets/1452146/22408120/a69bfab2-e673-11e6-9c02-d2066fa2c0e5.png)

**Comment by SamuAlfageme** [comment]
Hi @ldmpub since that is an issue related with the Nexcloud theming support for the ownCloud desktop client, you should go check their repo: https://github.com/nextcloud/client_theming/issues for this kind of issues.

Best!

**Comment by ldmpub** [comment]
Hi,

I'm sorry but this problem also occurs in Owncloud Version 2.2.4 (build 6408).
Can you re-open it for investigation?

**Comment by SamuAlfageme** [comment]
@ldmpub tried installing [the latest nightly](https://owncloud.org/install/#testing-development) release on the client on a french installation of Lubuntu and I see the button translated correctly:

![screenshot 2017-01-30 12 52 47](https://cloud.githubusercontent.com/assets/2644445/22422131/15fca272-e6eb-11e6-99a1-660b0f910e4c.png)

**If you find further typos or want to help translate owncloud to your language, you can head over ﻿﻿https://www.transifex.com/owncloud-org/owncloud to get involved!**

**Comment by ldmpub** [comment]
Hi,

I'm already member of the french translation team ;-).

Checked in Xubuntu: you're right => translation of the button is OK.

It's not so easy for translators to understand all the process: reviewed strings, languages updates, periodical builds and how to install and test them ;-(.

I consider my request as closed. Thanks for your answers, Regards,

**Comment by SamuAlfageme** [comment]
@ldmpub 

> It's not so easy for translators to understand all the process: reviewed strings, languages updates, periodical builds and how to install and test them ;-(.

Yeah, you're right. I'll pass your feedback and try to come up with a good explanation for the translation process to be more understandable. 

Thanks for your feedback! ☺️

**Comment by ldmpub** [comment]
Hi,

Follow up: ok in recent nightly build and I'm already part of the french translation team in Transifex.

Thanks for your answers.
