### ISSUE TITLE
Single shared file creates conflict when changes are applied

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#5502]
### Expected behaviour
Shared files are synced correctly without conflicts.

### Actual behaviour
The client always creates a conflict file when I try to save a textfile

### Steps to reproduce
1. Connect two setups via federated cloud sharing
2. Share one text document from OC 9.0.7 to a user on NC 11.0.1
3. Accept shared file (on NC, to be verified with other OC setup)
4. install testpilot client: Version 2.3.0-nightly20170130 (build 6694).
5. Sync files
6. Edit the shared file and save it
7. You get an error and a conflict file is created

I shared a folder and did the same test with a text file within this folder, that works without problem. It's only if you share a single file. I can also login on NC 11.0.1 and can use the web-interface to edit the file, that works perfectly. The current stable client (2.2.4) has the same problem.

I know you guys don't like issues with Nextcloud in it, but currently my other owncloud test-setup is broken and I can't test it there. Because it works via web interface and for files within shared folders, it could be a general problem of the sync client.

### Server configuration
Operating system: Debian 8

Web server: Apache 2.4

Database: MariaDB

PHP version: 7.0 (dot deb packages)

ownCloud version: 9.0.7 (and NC 11.0.1)

Storage backend (external storage): Federated Cloud sharing

### Client configuration
Client version: Version 2.3.0-nightly20170130 (build 6694).

Operating system: Windows 10 Pro

OS language: English

### Logs

https://gist.github.com/tflidd/27c1ba2a1837001a66eeeb3876219547

**Comment by hodyroff** [comment]
Please reproduce with two oC 9.1.4 servers.
@SamuAlfageme if you have a chance as part of 2.3 QA ...

**Comment by tflidd** [comment]
I got a OC 9.1-setup running. Textfile is now shared from OC 9.0.8 to OC 9.1.4. I have the same problem with the conflict file, direct editing in the 9.1.4 interface is no problem.

Client side: Version 2.3.0beta1 (build 6725)
OS: Win 7 Pro
OS language: German

If you have problems reproducing it, I can share the file from my 9.0.8 to your setup via federated cloud sharing.

**Comment by guruz** [comment]
Are you using encryption?

Reminds me a bit of https://github.com/owncloud/client/issues/5133#issuecomment-242039425

> Server files are encrypted but stored locally, 

@PVince81 @sagamusix @phil-davis

**Comment by tflidd** [comment]
No enrcryption is used in any of the setups. The 9.0 setup used encryption up to OC 7.0 but was then disabled. The file in question was just created for this purpose, so no old file that might be forgotten being decrypted.

**Comment by tflidd** [comment]
Do you still need more info?

**Comment by SamuAlfageme** [comment]
@tflidd Tried to reproduce this couple of weeks ago (on `OC 9.0.4 -> OC 9.1.4`) without success: no conflict file is being created in the OC 9.1.4 side. However...

>  The 9.0 setup used encryption up to OC 7.0 but was then disabled.

This can be an interesting addition to the reproduction steps (as @guruz pointed, related to https://github.com/owncloud/client/issues/5133#issuecomment-242039425) I'll try to reproduce that configuration first and then repeat with the issue _da capo_ and report

**Comment by ogoffart** [comment]
Closing old issue, most likely fixed as per #5106
