### ISSUE TITLE
Handle File Firewall Forbiden Message

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5504]
While glancing at https://github.com/owncloud/android/issues/1759#issuecomment-276028150 I realized https://github.com/owncloud/client/issues/4007 can have interfered with the way the client deals with this condition.

### Expected behavior
The same it happens with old servers, a warning message is displayed before setting the connection:

![](https://cloud.githubusercontent.com/assets/9048796/10459377/87efff92-71cf-11e5-9e9b-a4506db8ed7e.png)

Result of the PROPFIND 403:

```
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>OCP\SabrePluginException</s:exception>
  <s:message>Access to this resource has been forbidden by a file firewall rule.</s:message>
</d:error>

``` 

### Actual behavior
The connection is not stopped in any step of the wizard and the folders (empty) created locally. The files cannot be downloaded though, and the sync client is flooded with Forbidden error messages since individual 403 are issued for each file. 

![screenshot 2017-01-30 13 55 22](https://cloud.githubusercontent.com/assets/2644445/22423819/c38cdec2-e6f3-11e6-8213-62deca11a0ef.png)

### Steps to reproduce
1. Set a `User Device` rule equal to `Desktop Client` in the file firewall (`<server>/index.php/settings/admin#goto-file-firewall`) **on a server > 9.0**
2. Enter the server url at the new account wizard
3. Connect to an account 

![screenshot 2017-01-30 12 45 28](https://cloud.githubusercontent.com/assets/2644445/22421928/04d37990-e6ea-11e6-80d3-83ae2474ba43.png)

**Comment by guruz** [comment]
Thoughts:
* Isn't this a server bug? Why would the new dav endpoint not return this?
* is it a academical scenario to have the whole sync folder firewalled? (instead of single files)

**Comment by SamuAlfageme** [comment]
@guruz 

> Isn't this a server bug? 

It definitely is, follow up in https://github.com/owncloud/firewall/issues/266 for closure, also this behavior bugs me: https://github.com/owncloud/firewall/issues/266#issuecomment-278626612:

> if several rules are set [in the firewall app], even the downloads are done.

> is it a academical scenario to have the whole sync folder firewalled?

If the `User Device` `is` `Desktop Client` rule is set, I believe this is expected behavior.

**Comment by guruz** [comment]
@davitol @PVince81 @SamuAlfageme Shall we keep this issue open until it is fixed by server?

**Comment by ogoffart** [comment]
This is a server issue that is already tracked in the server bugtracker.
