### ISSUE TITLE
[Feature Request] Alternate server address when connected through home local network

### ISSUE THREAD

**Issue by denniskhong** [owncloud/client#5506]
Most consumer grade routers do not allow NAT Loopback, unless the firmware has been changed to DD-WRT or Open-WRT. Accessing an ownCloud server connect to a home network is problematic when we want to access the same server both from outside the home network and from within the home network at other times, e.g. using a laptop. We can easily configure to have a dynamic domain name using services such as DyDNS and port-forwarding. But once we enter that dynamic domain name into our ownCloud client, we will not be able to access the same server from within the home network.

My request is to add a feature in the client software to allow a secondary server address (for home local network) which will be triggered when (1) the primary server address is not working or (2) when the system detects through its IP address that it has connected to a designated local network.

Thank you.

**Comment by phil-davis** [comment]
Just a comment about what can work on some home routers. You can add a host override in the DNS forwarder that is built-in to the home router, thus for example pointing mycloud.example.com to 192.168.1.42 (the local private IP of your cloud server). Then when at home your client receives 192.168.1.42 as the IP of the cloud server and when on the public internet you get the public IP.

Of course that facility is not always available on every home router, just mentioning this here for the benefit of readers looking for ways to achieve this home-and-away functionality.

**Comment by SamuAlfageme** [comment]
These are some more detailed implementation ideas for https://github.com/owncloud/client/issues/203

**Comment by we-sell-bags** [comment]
Personally....  I would enable the Router with a VPN.
then  pop open a VPN connection via  DDNS, Not a direct  file syncing connnection.

when you are inside your WAN you get access, when you are outside and require access you fire up the VPN.

Simply opening up a consumer grade 'firewall' on multiple ports is asking for it, because you backend listeners have to be ROCK SOLID.

**Comment by michaelstingl** [comment]
Please run `dnsmasq` somewhere in your home network and point to this host in your routers DNS settings.

Here you can find more information:
https://wiki.debian.org/HowTo/dnsmasq
