### ISSUE TITLE
mac client is not be able to sync files with slash in there name

### ISSUE THREAD

**Issue by CordlessWool** [owncloud/client#5507]
error happens on an client of my system. It is not my own mac so I do not have all details, sorry

### Expected behaviour
Should upload files or give a understandable error message back.

### Actual behaviour
the syncing process was aborted 

### Steps to reproduce
1. folder is called like "WS 12/13"
2. 
3. 

### Client configuration
Client version: macOS

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

**Comment by SamuAlfageme** [comment]
Hey @CordlessWool, I believe this is by design. You can check the reference to see which specific characters in filenames cause the sync client to ignore them: https://doc.owncloud.org/desktop/2.2/architecture.html#ignored-files
