### ISSUE TITLE
Wrong description in the client settings tab

### ISSUE THREAD

**Issue by racic** [owncloud/client#5508]
With client 2.2.4 on Linux (both Arch and Ubuntu 16.04, x86_64) there is a labeling problem in the General settings section. In my language version (polish) the setting item label says 'start with Windows' while the clients are both Linux x86_64.

### Expected behaviour
I suppose label could say 'launch on system startup' or something similar

### Actual behaviour
Displays name 'Windows' on a Linux system

### Steps to reproduce
1. Start the sync client on Linux x86_64
2. Observe the settings tab

### Server configuration
_not relevant_

Storage backend (external storage):
_not relevant_

### Client configuration
Client version: 2.2.4
Operating system: Linux x86_64 (Arch + Ubuntu 16.04)
OS language: polish
Qt version used by client package (Linux only, see also Settings dialog): 5.5.1
Client package (From ownCloud or distro) (Linux only): ownCloud repo
Installation path of client: standard

**Comment by SamuAlfageme** [comment]
Hey @racic thanks for reporting! I just checked and that mistake has been already corrected: https://github.com/owncloud/client/commit/f3a345a23be884bfc447a7a2fb5f4c85fed95732#diff-2f012d163fe03d843e4f660b331dc90bL1159 and will be released with v.2.3 very soon.

If you want to test it out by yourself, you can try a nightly build from: https://owncloud.org/install/#testing-development

And also, of course, if you would like improving owncloud's translations, you can head to https://www.transifex.com/owncloud-org/owncloud/ and join the translators team!
