### ISSUE TITLE
Windows 10 - searching indefinitely and not syncing

### ISSUE THREAD

**Issue by esprit-libre** [owncloud/client#5509]
### Actual behaviour
A user have its windows client that loops indefinitely looking for modifications.
The problem appears with ownCloud-client 2.1.1 after an error `server replied: Insufficient Storage` when trying to upload two large files.
To solve the problem, I move out from sync dirs these large files and update owncloud-client to 2.2.4.
Same result : searching is looping forever. So no uploading and no downloading.
Please note that owncloud-client is connected to server and "server activity" corresponds to real other users activities.
Other infos : large files were in a personal and not shared folder.

### Steps to reproduce
Don't know.

### Server configuration
Operating system: Debian 8
Web server: Apache 2.4.10
Database: MySQL 5.5.54
PHP version: 7.0.15
ownCloud version: 9.1.3

### Client configuration
Client version: 2.2.4 (build 6408)
Operating system: Windows 10
OS language: French
Installation path of client: C:\Program Files (x86)\ownCloud

### Logs
1. Client logfile: 
> #=#=#=# Syncrun started 2017-01-12T09:01:32 until 2017-01-12T09:16:31 (898928 msec)
[...]
> |0|espace_indiv_marie/schrems/100_1259.MOV|INST_NEW|Up|1455026308||2074480175||6|Conserver sur liste noire : Error downloading https://***/remote.php/webdav/espace_indiv_marie/schrems/100_1259.MOV-chunking-1489417574-396-279 - server replied: Insufficient Storage (Sabre\DAV\Exception\InsufficientStorage)|507|0|0|||INST_NONE|
> |0|espace_indiv_marie/schrems/100_1261.MOV|INST_NEW|Up|1455092390||2074476124||6|Conserver sur liste noire : Error downloading https://***/remote.php/webdav/espace_indiv_marie/schrems/100_1261.MOV-chunking-2830538604-396-335 - server replied: Insufficient Storage (Sabre\DAV\Exception\InsufficientStorage)|507|0|0|||INST_NONE|

Collecting new one...

2. Web server error log:
No errors for this looping search.

**Comment by esprit-libre** [comment]
More infos, in case...
- server has been update in december from 9.0.2
- I ran `sudo -u www-data ./occ files:scan --all` yesterday, no errors but not better

**Comment by esprit-libre** [comment]
Some news !
User is linked via Federated Sharing to a shared folder from another ownCloud (same version of the server: 9.1.3).
I tried disabling sync to Fed Shared folder, and now sync restart on "local" folders.
So the problem comes from interaction between the two servers...
On remote server, recurring error is "OCA\DAV\Connector\Sabre\Exception\FileLocked: HTTP/1.1 423 "FD CIVAM 35/Installation" is locked".

**Comment by hodyroff** [comment]
How large are the files? Is it possible to upload such file size into the server the federated share resides on? Smaller files work perfectly? In this case I'd assume its not a challenge in the client but in the server side configuration.

**Comment by esprit-libre** [comment]
about 100M, and it is allowed on the server.
can't tell if upload of small files works because sync does not work at all if Fed Share enabled.

I continue to investigate, here is the state now : 
- ownCloud instance A, and ownCloud instance B
- user from B share a folder to user from A
- B folder can be seen and navigate by A user in A's web gui
- but user A oc-client cannot sync B folder
Also, B instance faces to [26837](https://github.com/owncloud/core/issues/26837) problem. Could be linked but does not explain why I can navigate B folder through web gui, but oc-client cannot sync...

**Comment by dbolton** [comment]
I had a similar issue about a year ago when I ran out of disk space on my server. To free up space I had to complete two steps: 
1. Delete the large files.
2. Log in to ownCloud as the user via the web, click on "Deleted files" (bottom left of screen), and remove the large files from there as well.

It took me a while to work out that I needed to complete the second step in addition to the first. 

To avoid the problem in the future I logged in to owncloud using the administrator account, went to the "Users" page, and added quotas to the users. That way users would hit the quota within owncloud before I ran out of disc space on the server.

**Comment by dbolton** [comment]
Also it may take a day or so for a folder to start syncing again after an insufficient storage error. See https://github.com/owncloud/client/issues/5346

**Comment by guruz** [comment]
I'm not sure I understand the issue.
If the server sends ```InsufficientStorage``` there is nothing we can do.
Are you saying both your server and the federated server actually have enough storage?

FYI @PVince81

**Comment by esprit-libre** [comment]
Hello,
I finally find a workaround and maybe an explanation...

The situation was this one:
1. User A (owner) from owncloud instance I1 share a large forlder (>22GB) to local users group G. User B belongs to G.
2. B share the same folder with Federated Share to User C from ownCloud instance I2
3. C try to sync on his computer (Windows 10) the totality (its own files/folders and the large folder from FedShare)
4. owncloud-client on C's computer scan indefinitely without logging errors. No errors on server logs for I2 neither for I1.

To solve the problem I simplify the chain:
* It was: User A from I1 => User B from I1 => User C from I2
* It is now: User A from I1 => User C from I2

Now sync is working. But first sync takes about 1,5 or 2 days before completing. Regularly, owncloud-client stops and restarts scanning.

**Comment by hodyroff** [comment]
Great feedback! For large amounts of data a user in I1 might make more sense, is this not an option? In 10.0 we have "guest users" to make this easier, maybe an option to test. And looks like there is performance to be optimized ...

**Comment by esprit-libre** [comment]
Yes I will create a user in first instance instead of using FedShare. This use case (large folder shared via FedShare) is not usual I guess, but I didn't notice that users configure sharing like that.

Do you keep this issue opened for performance optimization? From my point of view I don't have problem anymore, but I can reproduce the same use case if you need it for testing.

**Comment by hodyroff** [comment]
Yes, when 10.0 is out of the door I would like to see if we can optimize this. We are looking right now into similar issues from the client to the first server and think infinite propfinds can help and we should try the same between 2 federated servers ...

**Comment by guruz** [comment]
https://central.owncloud.org/t/desktop-client-2-4-0-alpha1-released/9837

2.4.0 alpha1 has a change that might improve the situation but not fix it completely.

Do you guys want to try?

**Comment by guruz** [comment]
@esprit-libre Any news?
2.4.1 final is out

**Comment by esprit-libre** [comment]
It seams ok. Quick test passed.
I don't have any users complaining :)

**Comment by guruz** [comment]
Great to hear!
