### ISSUE TITLE
Dialog spelling: "erlier time" instead of "earlier time"

### ISSUE THREAD

**Issue by dbolton** [owncloud/client#5513]
### Expected behaviour
After I restore from a backup (after a hard disk failure, for example), I should get the following dialog during the first sync:
> This sync would reset the files to an **earlier** time in the sync folder 'ownCloud'.
> This might be because a backup was restored on the server.
> Continuing the sync as normal will cause all your files to be overwritten by an older file in an earlier state. Do you want to keep your local most recent files as conflict files?

### Actual behaviour
After I restored from a backup I actually got the following dialog during the first sync:

> This sync would reset the files to an **erlier** time in the sync folder 'ownCloud'.
> This might be because a backup was restored on the server.
> Continuing the sync as normal will cause all your files to be overwritten by an older file in an earlier state. Do you want to keep your local most recent files as conflict files?

I've not looked at owncloud code before, but I did search the owncloud client repository on github (via the website). Unfortunately I didn't find an instance of "erlier" in the repository so I can't offer a code fix for this. 

If it is helpful, the dialog text is quoted in this thread: https://central.owncloud.org/t/problem-with-file-version-restore/894

### Server configuration
Operating system: 

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version: Version 2.2.4 (build 6408).

Operating system: Windows 7

OS language: US English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by phil-davis** [comment]
It looks like it was fixed in master 8 months ago by:
https://github.com/owncloud/client/commit/7f0cc5b699dfbe41e218c64c0dade0b8fb08c6fc
But in 2.2.4 branch it still has the typo (I wonder why that little typo fix never got into 2.2.4):
https://github.com/owncloud/client/blob/2.2.4/src/gui/folder.cpp
It is fixed in 2.3 branch:
https://github.com/owncloud/client/blob/2.3/src/gui/folder.cpp
