### ISSUE TITLE
sharing client - ubuntu - dialogue in background

### ISSUE THREAD

**Issue by herrdeh** [owncloud/client#5515]
When opening the sync client GUI, it will not appear in the foreground, but send a message: "Sync client is ready". Clicking this will bring the GUI into the foreground.
The same happens with the "share with owncloud..." dialogue from a file manager.

Normally, a programme will launch in the foreground.

ubuntu 16.10, gnome, the same with debian 8.6
OC client 2.2.4

**Comment by SamuAlfageme** [comment]
@herrdeh

> When opening the sync client GUI, it will not appear in the foreground, but send a message: "Sync client is ready". Clicking this will bring the GUI into the foreground.

This is expected behavior if you don't have anything to configure (i.e. if the connection with your server was set and successful). Since it's running smooth already you don't need co configure anything on the client GUI.

>  The same happens with the "share with owncloud..." dialogue from a file manager.

This however should not happen, is the dialogue popping behind the file manager?

**Comment by herrdeh** [comment]
> This is expected behavior if you don't have anything to configure (i.e. if the connection with your server was set and successful). Since it's running smooth already you don't need co configure anything on the client GUI.

Yes. But I'd not open the GUI when everything is running smoothly. Only in the case adjustments are required, errors occur etc - then I'd open the GUI, but then I'd like to have it in the foreground immediately. 

> is the dialogue popping behind the file manager?

Yes, it does so; but I found very rare exeptions.

**Comment by guruz** [comment]
Let's try to send the sharing dialogue more to foreground, I know @ogoffart @SamuAlfageme had been trying something last week.

**Comment by ogoffart** [comment]
The way to open the "GUI" is by clicking on the systemtray icon.

With plasma, the sharing dialog always appear on the top.

**Comment by ckamm** [comment]
I've tested this on linux with the account wizard and several share dialogs open. It worked fine for me.
