### ISSUE TITLE
[Windows] Desktop client crashes on wakeup if syncing an encrypted local drive

### ISSUE THREAD

**Issue by TDannhauer** [owncloud/client#5522]
### Expected behaviour
If the computer wakes up from engery-saving/standby, the desktop client should revalidate whether all drives are still available. if not, it should react on removed drives appropriately.

### Actual behaviour
If the computer uses encrypted drives with auto-dismount-on-standby, the client crashes after wake up since the expected drives are not longer available.

### Steps to reproduce
1. use an encrypted drive with veracrypt or truecryt.
2. configure VC/TC to auto dismount encryted drives on standby or user log-off
3. go into standby/energy-saving
4. wake up again
5. see OC desktop client crashing

### Server configuration
Operating system:
Debian stretch

Web server: 
Apache 2.4.25

Database:
PostgreSQL 9.6

PHP version:
7.0.15

ownCloud version:
9.1.4

Storage backend (external storage):
none, internal only

### Client configuration
Client version:
2.3.0-nightly20170105 (build 6613)

Operating system:
Win 10 Pro 64bit

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):
-

Client package (From ownCloud or distro) (Linux only):
-
Installation path of client:
default path

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

[...]
02-08 11:14:07:534 0xe8610 OCC::ownCloudGui::slotSyncStateChange: Sync state changed for folder  "https://owncloud.DOMAIN.TLD/remote.php/webdav/CHM" :  "SyncPrepare"
02-08 11:14:07:534 0xe8610 OCC::Folder::startSync: *** Start syncing  "https://owncloud.DOMAIN.TLD/remote.php/webdav/CHM"  - client version 2.3.0-nightly20170105 (build 6613)
02-08 11:14:07:534 0xe8610 OCC::Folder::setIgnoredFiles: ==== adding system ignore list to csync: "C:/Program Files (x86)/ownCloud/sync-exclude.lst"
02-08 11:14:07:534 0xe8610 OCC::Folder::setIgnoredFiles: ==== adding user defined ignore list to csync: "C:/Users/Torben/AppData/Local/ownCloud/sync-exclude.lst"
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: *~
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: ~$*
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: .~lock.*
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: ~*.tmp
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: ]*.~*
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: ]Icon
*
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: ].DS_Store
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: ].ds_store
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: ._*
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: ]Thumbs.db
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: desktop.ini
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: .*.sw?
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: .*.*sw?
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: ].TemporaryItems
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: ].Trashes
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: ].DocumentRevisions-V100
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: ].Trash-*
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: .fseventd
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: .apdisk
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: .htaccess
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: .directory
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: *.part
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: *.filepart
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: *.crdownload
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: *.kate-swp
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: *.gnucash.tmp-*
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: .synkron.*
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: .sync.ffs_db
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: .symform
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: .symform-store
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: .fuse_hidden*
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: *.unison
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: .nfs*
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: My Saved Places.
02-08 11:14:07:534 0xe8610 csync_exclude_load: Adding entry: photosync
02-08 11:14:07:534 0xe8610 unknown: QIODevice::write: device not open
02-08 11:14:07:534 0xe8610 OCC::FolderMan::slotFolderSyncStarted: >===================================== sync started for  "https://owncloud.DOMAIN.TLD/remote.php/webdav/CHM"
02-08 11:14:07:534 0xe8610 OCC::SyncJournalDb::close: void OCC::SyncJournalDb::close() "E:/CHM-Owncloud/._sync_075be9e41e60.db"
02-08 11:14:07:534 0xe8610 OCC::SyncJournalDb::commitTransaction: No database Transaction to commit

2. Web server error log:
-

3. Server logfile: ownCloud log (data/owncloud.log):
-

**Comment by guruz** [comment]
Did you send a crash report? Or have one saved?

**Comment by TDannhauer** [comment]
Yes, I sent it multiple times.

Von unterwegs gesendet
Sent from mobile

**Comment by ckamm** [comment]
@TDannhauer Can you reproduce without the standby by dismounting your encrypted drive and triggering a sync manually (select a folder and press F6)? I'll try reproducing.

**Comment by TDannhauer** [comment]
Yes, I did that already to rule out an issue of the standby.

It is simply caused by removing a drive (of course it has to be forced since truecrypt warns about umlimting still used folders.

LG,
Torben

Von unterwegs gesendet
Sent from mobile

**Comment by ckamm** [comment]
@TDannhauer Hm, I tried reproducing like this with the current 2.3.0beta1:
* Create a drive with `subst g: c:\my\path`
* Create a sync folder using a subfolder of g:
* Make g: go away with `subst g: /D`
* Retrigger a sync

But all I get is the "Unable to find local sync folder" error. Would you be up for trying with the 2.3.0 beta1? I'll also install truecrypt and try again.

**Comment by TDannhauer** [comment]
Where can I get 2.0.3 Beta1?

 

Then I’ll try your below instructions.

 

Regards,

Torben

 

Von: ckamm [mailto:notifications@github.com] 
Gesendet: Freitag, 10. Februar 2017 11:38
An: owncloud/client <client@noreply.github.com>
Cc: Torben Dannhauer <torben@dannhauer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [owncloud/client] [Windows] Desktop client crashes on wakeup if syncing an encrypted local drive (#5522)

 

@TDannhauer <https://github.com/TDannhauer>  Hm, I tried reproducing like this with the current 2.3.0beta1:

*	Create a drive with subst g: c:\my\path
*	Create a sync folder using a subfolder of g:
*	Make g: go away with subst g: /D
*	Retrigger a sync

But all I get is the "Unable to find local sync folder" error. Would you be up for trying with the 2.3.0 beta1? I'll also install truecrypt and try again.

**Comment by ckamm** [comment]
@TDannhauer 

The beta download links are in the changelog at https://owncloud.org/changelog/desktop/. I've also tried with Veracrypt and could not reproduce the problem you describe: When I unmount a volume and trigger a sync, I just get an error message about the sync folder not being found.

**Comment by TDannhauer** [comment]
Hi, I still have he error with 2.3.0beta1.

 

Did your veracrypt complain on dismount that some folders are still used? I think this is crucial since answering the dialogbox with yes ( force unmount) introduces the error.

 

Torben

 

Von: ckamm [mailto:notifications@github.com] 
Gesendet: Freitag, 10. Februar 2017 11:48
An: owncloud/client <client@noreply.github.com>
Cc: Torben Dannhauer <torben@dannhauer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [owncloud/client] [Windows] Desktop client crashes on wakeup if syncing an encrypted local drive (#5522)

 

@TDannhauer <https://github.com/TDannhauer> 

The beta download links are in the changelog at https://owncloud.org/changelog/desktop/. I've also tried with Veracrypt and could not reproduce the problem you describe: When I unmount a volume and trigger a sync, I just get an error message about the sync folder not being found.

**Comment by TDannhauer** [comment]
Using exactly your below instructions, I cannot reproduce the error.

However, when using Veracrypt and forcing dismount (since some folders are used e.g. by owncloud), then OC desktop client still crashes.

 

 

 

Von: ckamm [mailto:notifications@github.com] 
Gesendet: Freitag, 10. Februar 2017 11:38
An: owncloud/client <client@noreply.github.com>
Cc: Torben Dannhauer <torben@dannhauer.de>; Mention <mention@noreply.github.com>
Betreff: Re: [owncloud/client] [Windows] Desktop client crashes on wakeup if syncing an encrypted local drive (#5522)

 

@TDannhauer <https://github.com/TDannhauer>  Hm, I tried reproducing like this with the current 2.3.0beta1:

*	Create a drive with subst g: c:\my\path
*	Create a sync folder using a subfolder of g:
*	Make g: go away with subst g: /D
*	Retrigger a sync

But all I get is the "Unable to find local sync folder" error. Would you be up for trying with the 2.3.0 beta1? I'll also install truecrypt and try again.

**Comment by ckamm** [comment]
@TDannhauer Yes, Veracrypt said that the volume was still in use and asked whether to force the dismount. I chose yes, but the client did not crash.

Can you give me a very detailed step-by-step guide on how to reproduce? Alternatively, a log file might also help us track down where the crash comes from. (logs have private information, feel free to send it to me by email: ckamm at woboq com)

**Comment by TDannhauer** [comment]
I will do that later today, thanks for your help

Von unterwegs gesendet
Sent from mobile

**Comment by ckamm** [comment]
Feel free to reopen if still reproducible.
