### ISSUE TITLE
Syncing "confuses" two similar folder names

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#5527]
### Expected behaviour
Directory names should not be confused

### Actual behaviour
In a directory containing version-controlled sourcecode, I had a sub-directory called "portmidi". After updating this working copy, the "portmidi" directory was removed and a new directory "rtmidi" was added. The two directories have nothing in common, apart from their similar-looking folder names, probably.
When ownCloud was running over this directory, for some reason, it downloaded the old contents of the "portmidi" folder into the new "rtmidi" folder.

### Server configuration
Operating system: Bananian (~Debian Jessie)

Web server: Apache 2.4.10

Database: MariaDB

PHP version: 5.6.30

ownCloud version: 9.1.4

Storage backend (external storage): Local, encrypted

### Client configuration
Client version: 2.2.4

Operating system: Windows 7

OS language: German

Installation path of client: Default

**Comment by guruz** [comment]
Invoking @PVince81 

@sagamusix Do you have any log? Any conclusion from the access log on server? Or ```.owncloudsync.log``` on client?

**Comment by PVince81** [comment]
> the "portmidi" directory was removed and a new directory "rtmidi" was added.

was this a manual operation ? or do you mean something (server or client) decided to do that ?

**Comment by sagamusix** [comment]
> @sagamusix Do you have any log? Any conclusion from the access log on server? Or .owncloudsync.log on client?

The client logs seem to start after this happened; I'll see if I can find something on the server.

> was this a manual operation ? or do you mean something (server or client) decided to do that ?

This change was executed by TortoiseSVN, I guess that qualifies as "manual".

**Comment by sagamusix** [comment]
Is there a way to download just a part of the server log? I know which day the change must have happened on, so I do not want to download a multi-gigabyte server log and search through it...

**Comment by PVince81** [comment]
There is no such way. If possible I'd recommend to ssh into the server and then grep the log for the specific date and pipe the output into a separate file, then download that file.

**Comment by sagamusix** [comment]
It seems like not only simiarly-named folders trigger this issue. Here's roughly what I did this time to trigger the issue:
* Move two folders (let's call them A and B) inside my sync folder to a different sub-folder.
* Rename a couple of files in folders A and B.
* ownCloud decides to re-download the files with their old filenames from A, but puts them into folder B.

I do have client and server logs secured, let me know who I should send them to if required.

**Comment by ogoffart** [comment]
Yes, client logs could be usefull if you still have them.
What version of the client were you using?
Was the owncloud client giving you any error? Were there big folder? (could some calls to the server have timed out or failed because of network connection?)

**Comment by sagamusix** [comment]
I used a 2.5 daily build from around February. I don't remember if there were any errors, and the folders were around 100-200MB.
Is there a way to send the logs to you privately?

**Comment by sagamusix** [comment]
Just had another really random occasion of this that I cannot explain. It seems like some folder hierarchy was severely mixed up.
I deleted one folder locally, and somehow it later ended being downloaded from the server into a completely different parent folder. I am how it got there, afterwards it showed up on the server in that wrong parent folder as well, so somehow the server must have thought that the files belong there...?

**Comment by PVince81** [comment]
please upgrade and run `occ files:scan --all --repair` just in case.

if there are inconsitencies in the file cache table (like partial data from failed moves) it could explain such weird behavior

**Comment by ckamm** [comment]
We forbid retrieving files matching a 0 inode, so that's not it. dcf0baa9de7b0a2bad65742ea380102d87bdca65 fixed a problem that could have led to truncated inodes in the db (via `setFileRecordMetadata` - but that is in since >=2.4.0)
