### ISSUE TITLE
Use software collections on Redhat/Centos for desktop sync client and Qt packaging

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5533]
As discussed with @michaelstingl, @jnweiger, @SamuAlfageme.

Please review the work from CERN Linux team. Its about Software Collections on Redhat and packaging the client according to practices used on Redhat systems.

Ref: https://github.com/owncloud/client/issues/2558#issuecomment-75262413

**Comment by michaelstingl** [comment]
Currently we use OBS and as far as I know OBS is not capable of building repos in SCL (RHEL) or PPA (Ubuntu) format.

**Comment by guruz** [comment]
FYI @crrodriguez @dragotin

**Comment by fmoc** [comment]
We're using craft now to handle dependencies for the AppImage builds. Long term goal is to replace classic packaging (which for CentOS always has used some software collections) with those (or maybe provide packages that contain the AppImages' contents).
