### ISSUE TITLE
[OS X] Recent Changes is not working properly 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5535]
The `Recent Changes` section on the tray menu is displaying duplicate information:

### Actual behavior
- **Duplicated messages**: only for single files, not folders (uploads, moves, deletions...)
![screenshot 2017-02-15 10 53 50](https://cloud.githubusercontent.com/assets/2644445/22968998/0eefccaa-f36d-11e6-8d69-ac03a0e61b7e.png)
- If you open the tray menu while pushing changes, these doesn't appear until you push some more changes with the menu closed (maybe this is an OS limitation of being reactive to async changes)

**Client version: `2.3.0 beta1`** -- I still have to check if this only reproduces on OS X

**Comment by phil-davis** [comment]
This behavior has happened in the past, and I have seen it myself on Windows. So I am sure there are old issues that discussed it. But I have not noticed it on my Windows laptop recently.
Not much help, but at least gives you a clue to search old issues a bit.

**Comment by SamuAlfageme** [comment]
You are right, closing as duplicate of https://github.com/owncloud/client/issues/5535 (and https://github.com/owncloud/client/issues/5301) and reopening there
