### ISSUE TITLE
[arm] SSL handshake timeout

### ISSUE THREAD

**Issue by monochromec** [owncloud/client#5539]
Client version: 2.2.4 on an armv7h reverse-proxied with nginx 1.10.3-2 against a 9.0.2-1 server.
Client (both owncloudcmd and owncloud) times out when initiating the initial SSL handshake.
Relevant nginx configuation snippet at: http://pastebin.com/nDgd2jD0
Other clients including a 2.2.2 Ubuntu-based instance works flawlessly against the same
configuration.

Please let me know if you need more details.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system:
ALARM armv5
Web server: 
nginx
Database:
sqlite3
PHP version:
7
ownCloud version:
9.0.2.1
Storage backend (external storage):

### Client configuration
Client version:
2.2.4-1
Operating system:
ALARM armv7h
OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):
qt5
Client package (From ownCloud or distro) (Linux only):
2.2.4-1
Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

See  http://pastebin.com/CWwPvs3h.
2. Web server error log:

2017/02/16 17:48:08 [info] 28539#28539: *1 client timed out (110: Connection timed out) while SSL handshaking, client: XXX.XXX.XXX.XXX, server: 0.0.0.0:443
2017/02/16 17:49:08 [info] 28539#28539: *5 client timed out (110: Connection timed out) while SSL handshaking, client: XXX.XXX.XXX.XXX, server: 0.0.0.0:443
2017/02/16 17:50:08 [info] 28539#28539: *8 client timed out (110: Connection timed out) while SSL handshaking, client: XXX.XXX.XXX.XXX, server: 0.0.0.0:443
2017/02/16 17:51:08 [info] 28539#28539: *11 client timed out (110: Connection timed out) while SSL handshaking, client: XXX.XXX.XXX.XXX, server: 0.0.0.0:443
2017/02/16 17:54:25 [info] 28539#28539: *20 peer closed connection in SSL handshake while SSL handshaking, client: XXX.XXX.XXX.XXX, server: 0.0.0.0:443
201

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by hodyroff** [comment]
Please test with 2.3 Beta. Where did you get a client for ALARM armv7h from?

**Comment by monochromec** [comment]
Same results as with the original package (which I got from the official ALARM repos as configured). 

More than happy to provide a libssl dump if you tell me how to to do this. I tried to put some sense into openssl environment variables documentation but didn't get very far due to the poor quality of the docs. I assume that the _topendir function (defaulting to standard opendir on Linux) uses an libssl wrapper to access https URLs; so just let me know to go about this.

Thanks in advance for your help!

**Comment by monochromec** [comment]
I also noticed that the runtime paths of both owncloud and owncloudcmd are confined to <prefix>/lib/owncloud during installation, thus missing out on shared objects installed in <prefix>/lib.

Also, "make install" doesn't install the man pages.

**Comment by ogoffart** [comment]
So you are saying that in the wizard, you get a timeout on the first connection?

What happen if you set another server? (For example, if you enter https://github.com in the wizard, do you get a timeout, or an error telling that status.php was not found?)

Is the certificate valid otherwise, according to chrome?

**Comment by monochromec** [comment]
Both the command line client and the GUI client exhibit this behavior. As other clients (as outlined above, for example version 2.2 on Ubuntu) do not show this bug, I suspect a problem of the client code interfacing with the SSL wrapper when trying to open the server URL.

The certificate is a Let's Encrypt certificate so foul play can be ruled out here (as all other software including the other owncloud clients work OK with this certificate).

**Comment by ogoffart** [comment]
Does it work with other servers?

**Comment by monochromec** [comment]
This is getting weirder by the minute. 

2.2.4 works fine (as pulled from the Arch repo) on an Intel atom. The same version (both command line and GUI client) fails with symptoms described above on both armv7 and armv5. All other clients running on Intel CPUs work as expected.

Running an openssl s_client against the nginx instance running on an armv5 reveals the following issue in the SSL state during handshake: http://pastebin.com/jHneH1E6

I'm seeing similar issues when testing owncloudcmd against an openssl s_server running on the same armv7. Removing Elliptic Curve ciphers from the nginx SSL config doesn't make a difference.

Thoughts? 

More than happy to debug the SSL handshake further if I knew how.

**Comment by ckamm** [comment]
My guess is that this is unrelated to the owncloud client, and instead a problem with the arm build you are using. Maybe there's an issue with how its ssl dependencies are set up.

If I understand your last message right, then 2.2.4 on Intel works fine against this server, and the arm client doesn't work against a different ssl server either; correct?

**Comment by monochromec** [comment]
Let's recap: as outlined above, the only issue is on arm architectures (v5 and v7). The exact same software versions (both clients and supporting libraries such as libssl) are used on all platforms, the only difference is the CPU architecture. OS is Arch in all cases, the software is obtained from the repos with the exception of a custom build of the client for debugging purposes. 

If I knew how to debug the SSL handshake beyond a simulation with openssl s_client and s_server, we would be one step closer to the resolution of this issue. More than happy to provide more information as already provided - just let me know.

**Comment by monochromec** [comment]
At the end of the day, this turned out to be a symptom of a root cause somewhat unrelated. A misconfigured resolv.conf on the client side caused an incorrect name resolution and a subsequent certification mismatch which in turn resulted in the SSL / TLS timeout initially observed.
