### ISSUE TITLE
Client stuck in upload loop on similarly named files

### ISSUE THREAD

**Issue by pylorak** [owncloud/client#5544]
If you have a folder that contains two files whose names differ only in casing, the Windows client gets stuck in a loop and keeps reuploading one of the files every minute forever. This situation can happen for people dual-booting Windows with Linux and storing an owncloud-synchronized folder on a shared drive. Windows has otherwise no problems accessing or processing the files created this way.

Using Windows client version 2.2.4 on an NTFS partition under Win10.

I renamed one of the files and the upload-loop stopped, so the fix is easy IF you happen to figure it out. This has been happening silently in the background though for the past few days, and I am afraid it will have cost me a lot in mobile data transfer by the end of the month.

The desktop client should handle this situation and *not* keep reuploading the same file over and over again if a differently-cased file exists in the same folder.

**Comment by hodyroff** [comment]
@SamuAlfageme Looks like a classic corner case to look into after 2.3 is out of the door.

**Comment by SamuAlfageme** [comment]
@pylorak I've tried using [`win-sshfs`](https://code.google.com/archive/p/win-sshfs) to mount a remote Linux NTFS partition with a filename case collision (should be the same for dual-boot-like shared drives) and I've not been able to reproduce for the moment since windows is ignoring one of the files (the second queued for download). 

I'll try to reproduce with the same shared folder setup you propose to see if I'm able to see what's going on in the logs (if you have your own, please paste them here too). Thanks for reporting! 😉

**Comment by ckamm** [comment]
I also attempted to reproduce, but it worked fine in Win7 with a case collision on a non-ntfs filesystem. I think we've previously seen problems when an NTFS filesystem is adjusted to states that are usually unreachable in Windows (by mounting in linux, for example).

**Comment by pylorak** [comment]
I'm not sure if it can give any more info than what I already explained, but here is a screenshot of the sync log of the phenomenon. As you can see the affected file was named TcomTcp.cpp, the other was TCOMTCP.cpp. I renamed the latter to something else and the client immediately stopped resyncing the other one. They were both originally created under Linux in the same location, but I only have the sync client running under Windows.

The client is of nextcloud, but its repository tells everybody they should report problems here at owncloud, as the nextcloud repository for the client is only for theming. So both should be exhibiting the same problem.

![nc-issue](https://cloud.githubusercontent.com/assets/4016335/23127765/77fcf3cc-f77c-11e6-9c72-f2daf344a80b.png)

**Comment by ckamm** [comment]
@ogoffart Didn't we have a similar issue when ntfs was mounted from linux before? Do you remember the details or issue id?

**Comment by ckamm** [comment]
@pylorak I've done a bunch of tests on this issue. Specifically:
* Add a new drive to my Windows test VM, set up a sync folder there
* Mount this new drive under linux, creating case1.txt and Case1.txt in the root and in a subfolder.
* Trigger a sync in the VM.

That didn't reproduce the reported sync-loop issue, unfortunately.

But there is an issue: The client attempts to upload the contents of both files. But it uploads the contents of Case1.txt twice. This inability to distinguish the two files also applies to other programs such as notepad (Case1 content no matter which file is clicked) or the "type" command though. "dir" is able to see that the two files have different sizes though.

I'm not sure it's worthwhile to attempt to make this work. Using NTFS in a case-sensitive way is bound to cause issues.

**Comment by ckamm** [comment]
I could reproduce it in a Win10 VM though! The case1.txt file gets uploaded on each sync run. I have logs and will investigate.

**Comment by pylorak** [comment]
@ckamm Is it possible that this "other" issue you describe was exactly my problem? In my case the two files differed not only in name, but also in content. So I can imagine a case where, as you describe the client uploaded both files but always picking the content from one, therefor for one of the files the size/content was always wrong. Then the client saw a minute later that the content/size of the wrong file was different on server and client, and tried uploading it again, but again took the wrong content from the other file. As this repeated I got the upload loop.

Is this plausible?

**Comment by ckamm** [comment]
Probably because we can get the correct stat values while enumerating the entries of a directory, but not when statting "case1.txt" directly. Maybe we can work around this by adding `FILE_FLAG_POSIX_SEMANTICS` to CreateFile calls. (see http://stackoverflow.com/questions/33998669/windows-ntfs-and-case-sensitivity)

**Comment by pylorak** [comment]
mtime... so I guess whether this happens also depends on which file you created first. Depending on which one has an earlier mtime and which is the one that always gets (wrongly) picked you can get the loop or not.

Also, I might add, if the client can pick the wrong file content to upload in such situations, it means we have a case where the client can lead to data loss. If someone uses the client for backups, and then at some point needs to restore, one of the files will have been lost.

**Comment by ckamm** [comment]
@pylorak Data loss: Yes. My current suggestion is to make this case "not supported" and add a abort-sync error when the client detects conflicting file names on NTFS. Then we could go in and make it work later on - if that's possible and there's demand for it.

@guruz @jturcotte @ogoffart Opinions?

**Comment by ckamm** [comment]
Pull request: https://github.com/owncloud/client/pull/5583

**Comment by ckamm** [comment]
@pylorak The client will now refuse to upload files if there is a second file with a path that differs only in casing. It isn't a perfect solution, but will prevent data loss or this kind of looping behavior for people in this situation.
