### ISSUE TITLE
[Regression][2.3] HTTP redirections are not being followed properly

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5553]
### Expected behavior
On multi-tenancy installations (like the one in https://github.com/owncloud/administration/tree/master/redirectServer) after getting the username, the final destination host should be reached following the redirections:

```
OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 301 ""
OCC::OwncloudSetupWizard::slotAuthError: authed request was redirected to "https://owncloud.achernar.uberspace.de/instance1/remote.php/webdav/"
OCC::OwncloudSetupWizard::slotAuthError: setting account url to "https://owncloud.achernar.uberspace.de/instance1"
OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://owncloud.achernar.uberspace.de/instance1" + "/" "OCC::OwncloudSetupWizard"
OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://owncloud.achernar.uberspace.de/instance1" + "/" "OCC::OwncloudAdvancedSetupPage"
OCC::OwncloudWizard::slotCurrentPageChanged: Current Wizard page changed to  3

```

### Actual behavior
Instead of the `301` code, the `PROPFIND` is getting:
```
OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 200 ""
```

### Steps to reproduce
1.  Server URL: `https://owncloud.achernar.uberspace.de`
2. User: `test@instance1.com` & Pass: `secret`
3. Try to connect.

**Comment by ckamm** [comment]
The problem is that `followRedirects` is true for the auth-test PROPFIND request. That circumvents the wizard's custom redirect handling. Also, the automatically followed redirect request uses GET, which is a second issue.

Initial tests suggest setting followRedirects to false makes this work.

**Comment by ckamm** [comment]
Pull request: https://github.com/owncloud/client/pull/5554

**Comment by SamuAlfageme** [comment]
LGTM 👍
