### ISSUE TITLE
Transparent redirect handling forces verb to GET

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#5555]
If `_followRedirects` is enabled - as is the case for nearly all requests - we attempt to follow redirects by automatically issuing follow-up requests. However, these follow ups will always use GET.

This probably makes the redirect handling not work for many requests (we've seen that it can break PROPFINDs) and might have detrimental effects on some of them (what if a PUT is redirected to a GET?)

@ogoffart Do you know if this is in any way intentional?

**Comment by ogoffart** [comment]
This is NOT intentional. It's a pretty bad bug, i'd say.

**Comment by vladimiroff** [comment]
The fact the `_followRedirects` is applicable only for `GET` requests is pretty well documented:

```c++
    // Automatically follows redirects. Note that this only works for
    // GET requests that don't set up any HTTP body or other flags.
    bool          _followRedirects;
```

So, the fix should probably be to simply ignore the value of `_followRedirects` when method is not `GET`?

**Comment by ckamm** [comment]
@vladimiroff That sounds like a good first step. It would be nice to address these shortcomings as a second step.

**Comment by ckamm** [comment]
Making redirects work generally: https://github.com/owncloud/client/pull/5577
