### ISSUE TITLE
Windows client "host not found" after enabling server-side encryption

### ISSUE THREAD

**Issue by JakeCowton** [owncloud/client#5560]
After upgrading to ownCloud 8.2.9 and enabling server-side encryption, the windows client cannot find the host, but the Ubuntu one can

### Expected behaviour
I enabled server-side encryption, the client requests that I log out and back in after enabling server side encryption then continues to function as normal

### Actual behaviour
Client requests that I log out and back in after enabling server side encryption but after doing so cannot find the host, however, works fine on Ubuntu 16.04

```
Failed to connect to ownCloud at https://cloud.xxx.yyy/status.php:
Host cloud.xxx.yyy not found
```

### Steps to reproduce
1.  Upgrade to 8.2.9
2.  Enable server-side encryption
3. Log in and out 

### Server configuration
Operating system:
Debian 8

Web server: 
Nginx 1.6.2
Database:
mysql  Ver 14.14 Distrib 5.5.50, for debian-linux-gnu (armv7l) using readline 6.3
PHP version:
PHP 5.6.29-0+deb8u1 (cli) (built: Dec 14 2016 13:57:05)
ownCloud version:
8.2.9
Storage backend (external storage):

### Client configuration
Client version:
2.2.4 (build 6408)
Operating system:
Windows 10 64bit
OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
C:\Program File (x86)\ownCloud

**Comment by hodyroff** [comment]
Weird, did you retry with 2.3?

**Comment by JakeCowton** [comment]
This was an error on my part. No need to look further in this.
