### ISSUE TITLE
[Windows 10] account 1 of 2 lost during upgrade 2.2.4 -> 2.3.0.rc2

### ISSUE THREAD

**Issue by martin-rueegg** [owncloud/client#5562]
I have started the setup while v2.2.4 was running. Setup correctly asked to stop the process and stopped it. Then the setup also asked to remove the previous installation which I confirmed as during previous upgrades. After successful installation, the client was automatically started.

The admin account during setup was not the same user as the one I was logged in and the client was running before and after.

### Expected behaviour
After installation, all accounts that where set up previously, should still be available.

### Actual behaviour
After installation, the client was started but had only one of two accounts left in the configuration. It is the one that was most left in the GUI, but has originally be added as second account.

### Steps to reproduce
Did not reproduce as config is lost.

#### Account 1 (lost)
- Operating system:
Ubuntu 16.04.2 LTS (GNU/Linux 4.4.0-57-generic x86_64)
- Web server:
Apache/2.4.18 (Ubuntu)
- Database:
mysqld  Ver 5.7.17-0ubuntu0.16.04.2 for Linux on x86_64 ((Ubuntu))
- PHP version:
PHP 7.0.15-0ubuntu0.16.04.1
- ownCloud version:
- Storage backend (external storage):
multiple WebDav / SMB

#### Account 2 (preserved)

- Operating system:
ReadyNASOS 6.6.0
- Web server:
Apache/2.2.31 (Debian)
- Database:
mysqld  Ver 5.5.43-0+deb7u1 for debian-linux-gnu on x86_64 ((Debian))
- PHP version:
PHP 5.6.24-0+deb8u1.netgear1
- ownCloud version:
ownCloud 9.1.0 (stable)
- Storage backend (external storage):
none

### Client configuration

- Client version:
  - old: 2.2.4.6408
  - new: 2.3.0.6760rc2
- Operating system
Microsoft Windows [Version 10.0.14393]
- OS language:
English
- Qt version used by client package (Linux only, see also Settings dialog):
  - new: Built from Git revision 53bc15 on Feb 24 2017, 14:08:52 using Qt 5.6.2, OpenSSL 1.0.2h 3 May 2016
- Installation path of client:
C:\Program Files (x86)\ownCloud\

### Logs
n/a

**Comment by SamuAlfageme** [comment]
@martin-rueegg thanks for detailed report Martin! we definitely have to investigate this behavior.

Can you check how the [`[Accounts]`section](https://central.owncloud.org/t/script-owncloud-client-for-mac/3473/6?u=alfageme) in the config file (`%LOCALAPPDATA%\ownCloud\owncloud.cfg`) looks like? (i.e. if it has records of both accounts).

I'm guessing none of the accounts was using Shibboleth authentication, right?

**Comment by martin-rueegg** [comment]
Hi @SamuAlfageme,

thanks for the reply.

Yes, I've checked the `[Accounts] ` section and no, unfortunately there's nothing left from the second account. (Should've made a backup!).

Also yes, there was no Shibboleth account involved. Both two regular oC setups with local users only.

Maybe a good thing to consider to create a .bak file upon upgrade, or when config changed?

**Comment by SamuAlfageme** [comment]
@martin-rueegg sure, that backup could also be considered upon major updates (such 2.3) if this sort of thing could happen. 

I'll keep trying to reproduce this with more scenarios I can come up with. cc/ @guruz @ckamm to see if you guys have any ideas.

**Comment by martin-rueegg** [comment]
I never had any 2.3 installed on this system before.

What is also interesting, I have no folder set up in the account that is left. However, I can't remember if I ever had. As I don't use the files in that account very often.

In the account I have lost, I had removed the main folder, and added a number of other folders which where partly under the OwnCloud user home, and partly at other places in the system.

It is such a shame I have no backup. Comparing the two config files might have helped to track the issue. Furthermore I could not find any log files regarding the client as a whole, only regarding sync. And they obviously don't contain any information regarding config/accounts.

If the error cannot be reproduced (I can try myself) maybe the backup copy of the config file would at least help if for whatever reason it does happen to someone else in production.

As much as I'd love to, I'm sorry not to be able to provide more information.

**Comment by guruz** [comment]
@martin-rueegg (might be related or not..) Do you have a ```folder``` or ```folders``` (forgot which one) subdirectory in your config directory?

**Comment by martin-rueegg** [comment]
Yes, @guruz, I do, with one file in it:

`\AppData\Local\ownCloud\folders\ownCloud` conaining:
```
[ownCloud]
localPath=C:/Users/mdr/ownCloud/
targetPath=/
backend=owncloud
connection=ownCloud
```

The relevant `[accounts]` section in `owncloud.cfg` reads:
```
[Accounts]
1\url=https://some.host.net:43443/owncloud
1\serverVersion=9.1.0.15
1\http_certificatePasswd=
1\http_certificatePath=
1\http_user=Admin
1\user=Admin
1\authType=http
1\General\CaCertificates="@ByteArray(-----BEGIN CERTIFICATE-----|snip|-----END CERTIFICATE-----\n\n)"
version=2
```

Accoount 0 has been removed

**Comment by guruz** [comment]
This is tricky. I'm thinking of what can cause this but don't have a clue.


The only related code I could imagine would be 4198d9f420f630f2f346a123422f937bfbec88d2 or 9d3e78ed542cda175a9121b805cb93689f2dab65

Did the account have a strange URL?

Maybe stopping the client from the installer borked the config file. But that should not happen either.

**Comment by martin-rueegg** [comment]
Url for the 0 account (removed) was most normal, a regular https://this.host/owncloud
three letter username, 16 char long password alphanum.

The other account (preserved) hat a special port (see above).

**Comment by guruz** [comment]
@martin-rueegg I presume C:/Users/mdr/ownCloud/ is for account 0 ?

Not that i think it matters

**Comment by martin-rueegg** [comment]
Yes, but I had removed that folder from the folder list in the GUI and added other folders, some of them beneath C:/Users/mdr/ownCloud/, some outside of this tree altogether. I can provied more details on this later but gotta go for now ...

**Comment by guruz** [comment]
Neither @SamuAlfageme nor me were able to reproduce this so far. :/

**Comment by jturcotte** [comment]
Maybe we have a bug where we sometimes write incomplete configurations, but we don't usually see it since we always write the full configuration on exit. The installer killed the existing instance in this case, so this would have exposed an existing bug (which might or might not be new).

Could also be related to this dummy credential issue we've been seeing in 2.2, did we find the cause after all?

**Comment by ckamm** [comment]
I've also looked at it and don't see a likely cause.

@jturcotte Hm, in order to create an incomplete account configuration we'd need to actively remove an account from the config file, and I think the only place we do that is `deleteAccount`. And as far as I'm aware `QSettings::sync` uses atomic updating of the config file and shouldn't leave us with a half-filled accounts table.

Not reading the account for some reason seems more likely to me, possibly due to the new url validation that was mentioned above.

**Comment by jturcotte** [comment]
@ckamm I mean for example `AccountManager::saveAccount` which assumes that `Utility::settingsWithGroup` was able to load the config successfully before writing to it, and since we sometimes save one account at a time, maybe this could mean losing the rest of the configuration.

In any case this is only an hypothesis to illustrate that it's also possible that this is a 2.2.4 bug happening when the process gets killed, rather than a 2.3.0 bug corrupting the config on read.

**Comment by ckamm** [comment]
@jturcotte Makes sense. I thought QSettings would re-read the file and only commit changes if it could successfully read the file, but it looks like it soldiers on with empty base settings in `syncConfigFile` if reading fails. (does set an error flag, which we don't check)

With that in mind, wouldn't it make sense to adjust our config-writing code to not touch the config file if there's an error on initial reading of it? I.e. allow things like `settingsWithGroup` to return null on error and require checking that before writing changes?

**Comment by jturcotte** [comment]
@ckamm I'd guess that we should try to handle that case, but we should be careful since even if we can't read it sometimes, it's possible that we'll still manage to regenerate it from the state in memory. 

So "don't write if we can't read" could lead to state loss of the user just change its folder configuration. I'm wondering if an abort/retry dialog could make sense.

**Comment by ckamm** [comment]
@jturcotte I had similar worries and added a paragraph to my previous comment a couple minutes back: What if we kept a QSettings instance alive that we require to have read the config file on startup? I don't think we could run into this issue that way.

**Comment by martin-rueegg** [comment]
I will try to 
- uninstall v2.3 for now,
- re-insatall 2.2.4,
- re-setup the accounts as close as I can remember to my previous state
- make a backup of owncloud.cfg
- re-update to v2.3.0.rc2 (or would you suggest to go directly to rc3 - never change two things at a time, right?) while 2.2.4 is running.
- let you know if I can reproduce it.

**Comment by SamuAlfageme** [comment]
@martin-rueegg awesome! thank you! 😃

**Comment by martin-rueegg** [comment]
You're welcome.

Btw, you're talking about "killing" the current instance during setup. Could an application.close event be issued, rather than term and give the client 5 seconds to shut down or so, and then - if still there - send a term?

Maybe by this the update process would get smoother?

**Comment by martin-rueegg** [comment]
Ok, I've done as laid out in my previous comment, but unfortunately could not reproduce the error.

Obviously, if it has something to do with writng out the config only partially due to the process being killed in that very instance, I would require to hit "OK" at the very moment the old client is in the very same state as during my first upgrade.

Maybe it was really just bad luck. However, instead of killing the process, ending it graciously might help, as the process would have time to save the config. Unfortunately I do not have a copy of the config file _before_ the setup, nor in the state after uninstalling the old version _during_ the setup. So I can't say whether or not the config file has been incomplete at any given state. When I first inspected it, the new client had alredy started up and might have fixed missing information.

Furthermore, saving the config with the version name during uninstall or the previous config during install as pre-newVersion, would help users to recover if - in rare cases - it happens again.

I am very sorry not being able to reproduce the error or provide further information. If you have any idea of what I could try, please let me know.

I can also send you the config files, if that would help.

However, thank you so much for looking into this and taking my report seriously.

**Comment by guruz** [comment]
> The admin account during setup was not the same user as the one I was logged in and the client was running before and after.

I wonder if this somehow plays into it.

@martin-rueegg Thanks for trying to re-reproduce. 

@ckamm @ogoffart I'd hope Qt 5.6.2 has a more robust QSettings than the 5.4.x we ship?
