### ISSUE TITLE
[Windows 10] [2.2.4] New account wizard gets positioned under all other Windows

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5566]
This report is when adding a second account and having other windows programs windows open.
For me the new wizard was then hidden.

FYI @SamuAlfageme @ogoffart

**Comment by guruz** [comment]
... now I'm thinking this might have been fixed in 2.3 already

**Comment by ckamm** [comment]
@guruz I cannot reproduce it on Windows 10. When I click the "Add account" menu entry, the account settings window hides and the new account wizard pops up in its place and is properly covering the other windows.

**Comment by guruz** [comment]
This is fixed with my patch above..
