### ISSUE TITLE
[Windows] Running client directly after install blocks other installations

### ISSUE THREAD

**Issue by martin-rueegg** [owncloud/client#5569]
When installing v2.3.0.rc3 I opted for the default behaviour to launch the client directly from the setup program.

### Expected behaviour
Client should start and installation completely finish, in order for other installations to be able to run.

### Actual behaviour
Client starts as expected, but when an other non-ownCloud setup is launched (e.g. Java JDK) then an error is shown (in the new setup routine) that a setup is currently still in process. Closing OwnCloud client solves the issue.

### Steps to reproduce
1. Install OwnCloud client and launch the client from within the setup
2. start another setup (e.g. Java JDK) before closing the client

### Client configuration
- Client version:
2.3.0.rc3
- Operating system:
Microsoft Windows [Version 10.0.14393]
- OS language:
English

Happy to provide further informations.

**Comment by SamuAlfageme** [comment]
@martin-rueegg thanks for reporting! Just tried out with a Windows10 VM and JRE's installer and I'm not seeing it reproduced (check [this video I made](https://webmshare.com/play/M0qDd))

There's any change you are trying to run the second installer without admin rights? Only happens with JDK's installer?

**Comment by martin-rueegg** [comment]
Hi @SamuAlfageme, I also tried by uninstalling oC 2.3.0.rc3, reinstalling it and then test with both JRE and JDK. Both worked fine this time.

No, I run both installers with admin rights, which is a different user than the owncloud process runs in. Can try to go back to 2.2.4 and the upgrade again. That's what I did before.

**Comment by martin-rueegg** [comment]
I tried as outlined above, but still worked. :-) So maybe it was something else then.

**Comment by ogoffart** [comment]
Closing old issue
