### ISSUE TITLE
Synchronization problem for manually added files

### ISSUE THREAD

**Issue by marcocastignoli** [owncloud/client#5570]
I transferred my music directly on my server using ftp then i ran the owncloud's scan command. Then I   added the remote music folder using owncloud client for linux (Linux Mint 18) selected my local music folder that contains excactly  the same files. 

Owncloud created lots of conflicts file ruining my music library. And the owncloud client is not asking me to fix those conflicts.

Hope informations are enough

### Client configuration
Operating system: Debian

Web server: apache2

Database: mariadb  10.1.21-5

PHP version: 7.0.15-1

ownCloud version: 9

### Client configuration
Client version: 2.2.4

Operating system: Linux Mint 18

OS language: IT

Qt version used by client package (Linux only, see also Settings dialog): 5.5.1

Client package (From ownCloud or distro) (Linux only): 2.2.4-1.1

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
empty

2. No log

3. Server logfile: ownCloud log (data/owncloud.log):
https://gist.github.com/marcocastignoli/e91a46d3a3b570cc4866c3c17a84e3eb

**Comment by hodyroff** [comment]
Your server and the client have different mtimes in this case, thats why you are getting conflicts. This type of initiating a scny is currently not supported.

**Comment by marcocastignoli** [comment]
How can I clean my library from conflict files? I have two kind of files for each one, this is an example:

```
-rwxrwxrwx 1 marcocastignoli marcocastignoli        0 Feb  8 10:44 01. Sphynx.mp3*
-rwxrwxrwx 1 marcocastignoli marcocastignoli 11095549 Feb  8 10:44 01. Sphynx_conflict-20170208-104421.mp3*

```

**Comment by guruz** [comment]
@marcocastignoli @hodyroff This should not happen if the files are IDENTICAL, the client does a byte-by-byte check of the file before creating a conflict.

> -rwxrwxrwx 1 marcocastignoli marcocastignoli        0 Feb  8 10:44 01. Sphynx.mp3*

Why 0 file size? Why is there a ```*``` in the file name? This is a not allowed character.

**Comment by marcocastignoli** [comment]
> Why 0 file size? Why is there a * in the file name? This is a not allowed character.

that is exactly what I'm asking, the files were not like this. It happened after owncloud sync the music folder.

**Comment by guruz** [comment]
> ownCloud version: 9

Which exact version?

@ogoffart I was under the assumption * is not a valid character on Linux either?

**Comment by ogoffart** [comment]
@guruz afaik, the only invalid character on typical linux FS is the /,  so * is a valid one, and is synced properly if the owncloud backend also supports it.

**Comment by ogoffart** [comment]
The log don't have information about anything like Sphynx.mp3.  There are a few errors in the logs but i don't know if they are related or if they are normal.

It would be interresting to have the client logs when such conflict happens.

**Comment by marcocastignoli** [comment]
Sorry I have been busy. I corrected all the files name. Then I fixed the time of my machine and the server, then changed all the files mtime on my machine to the actual date. Finally ran again the sync. Now everything is working. Thank for your support.

**Comment by hodyroff** [comment]
ok, closing for now. When we have more info towards reproduction/bug we can reopen.
