### ISSUE TITLE
Additionnal ')' characters on each line in certifcate popup

### ISSUE THREAD

**Issue by ldmpub** [owncloud/client#5573]
See screen shot:
![bug additionnal character](https://cloud.githubusercontent.com/assets/1452146/23480573/ae5301de-fec8-11e6-96d6-0ceef25d0e63.jpg)

Version 2.3.0rc3 (build 2254)

**Comment by ogoffart** [comment]
Thanks for reporting the issue.
Fixing in https://github.com/owncloud/client/pull/5574
