### ISSUE TITLE
[Qt] [OS X] Dragging the application icon in any client window displays a popup error

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5575]
![drag_error](https://cloud.githubusercontent.com/assets/2644445/23509548/7af6ff0a-ff56-11e6-88e0-9db1cb8a279c.gif)

Looks like a Qt regression: https://bugreports.qt.io/browse/QTBUG-30064

**Comment by TheOneRing** [comment]
Can't reproduce anymore
