### ISSUE TITLE
GLib-CRITICAL: Source ID was not found when attempting to remove it (Ubuntu 14.04, client 2.3.0) 

### ISSUE THREAD

**Issue by s-ntech** [owncloud/client#5578]
### Expected behaviour
After fresh install (Ubuntu 14.04, client 2.3.0 using Qt 4.8.6), client should be able to sync folders and the client should not crash.

### Actual behaviour
After downloading (syncing) a folder from remote for a short time (~10s) the client crashes. In the command line:

> (owncloud:9634): GLib-CRITICAL **: Source ID 251 was not found when attempting to remove it
Aborted (core dumped)

### Steps to reproduce
1. `sudo apt-get install owncloud-client`
2. Connect to remote folder and try to sync remote folder

### Server configuration
Operating system: Ubuntu 14.04 (3.13.0-110-generic)

Web server: Apache2 

Database: MySql

PHP version:

ownCloud version: 9.1.4

Storage backend (external storage):

### Client configuration
Client version: 2.3.0

Operating system: Ubuntu 14.04

OS language: En

Qt version used by client package (Linux only, see also Settings dialog): 4.6.8

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt` (I'm showing the last 10 or so lines here, but can upload full log if required as well)
`03-06 10:43:54:952 0x1d07070 void OCC::AbstractNetworkJob::slotFinished() 2 "Connection closed" QVariant(int, 200) 
03-06 10:43:54:952 0x1d07070 void OCC::PropagateDownloadFile::slotGetFinished()  QUrl( "https://******.de/remote.php/webdav/instr/2011-Linear_Algebra_I/Aufgabeblätter/R Vektorräume.pdf" )  FINISHED WITH STATUS 2 "Connection closed" 0 179340 189666 0 "" "189666" 
03-06 10:43:54:952 0x1d07070 void OCC::SyncEngine::slotItemCompleted(const SyncFileItemPtr&) "2011-Linear_Algebra_I/Aufgabeblätter/R Vektorräume.pdf" INSTRUCTION_NEW 1 "Connection closed" 
03-06 10:43:54:971 0x1d07070 void OCC::AbstractNetworkJob::slotFinished() 5 "Operation canceled" QVariant(, ) 
03-06 10:43:54:971 0x1d07070 void OCC::PropagateDownloadFile::slotGetFinished()  QUrl( "https://******.de/remote.php/webdav/instr/2011-Linear_Algebra_I/Aufgabeblätter/la1-1.pdf" )  FINISHED WITH STATUS 5 "Operation canceled" 0 0 124166 0 "" "" 
03-06 10:43:54:971 0x1d07070 "DELETE FROM downloadinfo WHERE path=?1" "2011-Linear_Algebra_I/Aufgabeblätter/la1-1.pdf" 
03-06 10:43:54:971 0x1d07070 void OCC::SyncEngine::slotItemCompleted(const SyncFileItemPtr&) "2011-Linear_Algebra_I/Aufgabeblätter/la1-1.pdf" INSTRUCTION_NEW 1 "Operation canceled" 
03-06 10:43:54:972 0x1d07070 void OCC::AbstractNetworkJob::slotFinished() 5 "Operation canceled" QVariant(, ) 
03-06 10:43:54:972 0x1d07070 void OCC::PropagateDownloadFile::slotGetFinished()  QUrl( "https://******.de/remote.php/webdav/instr/2011-Linear_Algebra_I/Aufgabeblätter/la1-10.pdf" )  FINISHED WITH STATUS 5 "Operation canceled" 0 0 203363 0 "" "" 
03-06 10:43:54:972 0x1d07070 "DELETE FROM downloadinfo WHERE path=?1" "2011-Linear_Algebra_I/Aufgabeblätter/la1-10.pdf" 
03-06 10:43:54:972 0x1d07070 void OCC::SyncEngine::slotItemCompleted(const SyncFileItemPtr&) "2011-Linear_Algebra_I/Aufgabeblätter/la1-10.pdf" INSTRUCTION_NEW 1 "Operation canceled" 
03-06 10:43:54:977 0x1d07070 * Ignoring file "/home/fh/instr/2011-Linear_Algebra_I/Aufgabeblätter/.la1-1.pdf.~1b3fdec" 
03-06 10:43:54:978 0x1d07070 * Ignoring file "/home/fh/instr/2011-Linear_Algebra_I/Aufgabeblätter/.la1-10.pdf.~513e23d7" 
03-06 10:43:54:978 0x1d07070 * Ignoring file "/home/fh/instr/2011-Linear_Algebra_I/Aufgabeblätter/.R VektorrÃ¤ume.pdf.~373f3585" 
03-06 10:43:54:978 0x1d07070 ASSERT: "i >= 0" in file /usr/src/packages/BUILD/src/libsync/owncloudpropagator.cpp, line 665`

2. Web server error log: No webserver errors

3. Server logfile: ownCloud log (data/owncloud.log): No errors

### Comment
My first bug report. I would really like to help getting to the bottom of this issue. Please let me know if and how I can supply further information.

**Comment by ogoffart** [comment]
The actual crash is 

```
ASSERT: "i >= 0" in file /usr/src/packages/BUILD/src/libsync/owncloudpropagator.cpp, line 665
```

This seems to happen for "Connection closed" errors.  

This looks like the crash we tries to fix during the rc phase but were not able to reproduce.

**Comment by ogoffart** [comment]
Pull request: https://github.com/owncloud/client/pull/5579

**Comment by ogoffart** [comment]
Normally fixed for 2.3.1

**Comment by s-ntech** [comment]
Thanks. I'm assuming that this will only fix the crash and not the "Connection Closed" error that I have been having on Ubuntu 14.04 since at least client  2.1.0? Is there any chance this could be looked into more? I do not see the Connection Closed error on any other machines - just on this Ubuntu 14.04. No fresh client install was able to solve the issue. The only thing that ever helped is going back to clients < 2.1.0 and limit the download bandwidth.

**Comment by ogoffart** [comment]
Try upgrading to Qt 5.6.

**Comment by s-ntech** [comment]
Thanks for the reply. I'm not able to compile the client with Qt 5.6. I think I've come pretty far but now another lot of unmet dependencies have cropped up: 

> /usr/lib/x86_64-linux-gnu/libQt5WebKit.so.5.1.1: undefined reference to `QWindowSystemInterface::registerTouchDevice(QTouchDevice*)'
> /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5.2.1: undefined reference to `QOpenGLTextureGlyphCache::QOpenGLTextureGlyphCache(QFontEngineGlyphCache::Type, QTransform const&)'
> /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5.2.1: undefined reference to `QPdfEnginePrivate::pageRect() const'
> /usr/lib/x86_64-linux-gnu/libQt5OpenGL.so.5.2.1: undefined reference to `QFontEngine::glyphCache(void const*, QFontEngineGlyphCache::Type, QTransform const&) const'
> /usr/lib/x86_64-linux-gnu/libQt5Quick.so.5.2.1: undefined reference to `QShortcutMap::tryShortcutEvent(QObject*, QKeyEvent*)'
> /usr/lib/x86_64-linux-gnu/libQt5PrintSupport.so.5.2.1: undefined reference to `QPdfEnginePrivate::paperRect() const'
> collect2: error: ld returned 1 exit status


I don't think I'll be able to compile it in the end. Through extensive reading, I'm now aware of #2558. Sticking it out until 2.3.1 hits might be a good idea then? Will I get Qt5 on Ubuntu 14.04 as well with 2.3.1?
