### ISSUE TITLE
client uses lots of System Resources

### ISSUE THREAD

**Issue by holzfelix** [owncloud/client#5581]
The updater app for windows uses too much resourses. Is there a way to reduce the amount of system resources?

I'm using windows 10 64bit professional, i7 6200 and 16GB ram. When app is in sync mode the whole system is unusable.

Already tried to reinstall the app.

**Comment by ogoffart** [comment]
What's the version of the client? Have you tried the version 2.3.0?
How many files/folder do you have? (order of magnitude)
What is exactly the resource that is used so much? (memory/cpu/IO?) Can you see that in the task manager?

**Comment by holzfelix** [comment]
Hi actually installed is version 2.2.4 (Build 2) Where do I get the 2.3.0 Client? is this a beta version?

All files of the user profile (pictures/download/desktop/ .... ) is in sync. About 60-100GB of files but not all of the are under access all the time. only a few will change often.

Problem is a high cpu usage. About 30 to 60 percent.

**Comment by ogoffart** [comment]
The client 2.3.0 was released last week:  https://owncloud.org/install/#install-clients

**Comment by holzfelix** [comment]
but im using the nextcloud client or is it the same?

**Comment by ogoffart** [comment]
it's the same, only the branding is different.  And the version 2.3 got several performence improvement so i guess it should help.

**Comment by hodyroff** [comment]
No info provided.
