### ISSUE TITLE
[Windows] 302 redirection problem

### ISSUE THREAD

**Issue by fusioncowork** [owncloud/client#5584]
Hi,

Trying to connect on a windows 7 machine, with the latest desktop client. The error is what follows on the bellow image when entering the host to connect.

[https://fusioncowork.com/Screen_Shot_2017-03-07.png](url)

### Server configuration
Operating system: Linux

Web server: 

Database:

PHP version:

ownCloud version: Latest

Storage backend (external storage):

### Client configuration
Client version: Latest

Operating system: Windows 7

OS language: Portuguese

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):
{"reqId":"WL3uiF4usL4ACtCoKG8AAAAD","remoteAddr":"89.155.198.219","app":"core","message":"Login failed: 'hugo' (Remote IP: '89.155.198.219')","level":2,"time":"2017-03-06T23:19:36+00:00","method":"POST","url":"\/index.php\/login","user":"--"}
{"reqId":"WL4B8l4usL4AC2RyHnMAAAAS","remoteAddr":"94.46.163.221","app":"core","message":"Trusted domain error. \"94.46.163.221\" tried to access using \"www.cloud2.heatermec.com\" as host.","level":2,"time":"2017-03-07T00:42:26+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"WL4B8l4usL4AC2RlGoMAAAAN","remoteAddr":"31.185.104.20","app":"core","message":"Trusted domain error. \"31.185.104.20\" tried to access using \"www.cloud2.heatermec.com\" as host.","level":2,"time":"2017-03-07T00:42:26+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"WL4B8l4usL4AC3ccUJ0AAAAB","remoteAddr":"141.170.2.53","app":"core","message":"Trusted domain error. \"141.170.2.53\" tried to access using \"www.cloud2.heatermec.com\" as host.","level":2,"time":"2017-03-07T00:42:26+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"WL4B8l4usL4AC2RxHWkAAAAR","remoteAddr":"94.46.163.221","app":"core","message":"Trusted domain error. \"94.46.163.221\" tried to access using \"www.cloud2.heatermec.com\" as host.","level":2,"time":"2017-03-07T00:42:26+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"WL4B8l4usL4AC2RkGdkAAAAK","remoteAddr":"5.28.62.85","app":"core","message":"Trusted domain error. \"5.28.62.85\" tried to access using \"www.cloud2.heatermec.com\" as host.","level":2,"time":"2017-03-07T00:42:27+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"WL4B814usL4AC2SQJfcAAAAa","remoteAddr":"31.185.104.20","app":"core","message":"Trusted domain error. \"31.185.104.20\" tried to access using \"www.cloud2.heatermec.com\" as host.","level":2,"time":"2017-03-07T00:42:27+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"WL4B814usL4ACwC1b@YAAAAI","remoteAddr":"52.199.95.88","app":"core","message":"Trusted domain error. \"52.199.95.88\" tried to access using \"www.cloud2.heatermec.com\" as host.","level":2,"time":"2017-03-07T00:42:27+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"WL4B9F4usL4AC2R7IZUAAAAX","remoteAddr":"52.199.95.88","app":"core","message":"Trusted domain error. \"52.199.95.88\" tried to access using \"www.cloud2.heatermec.com\" as host.","level":2,"time":"2017-03-07T00:42:28+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"WL4B9l4usL4AC2cWS0UAAAAG","remoteAddr":"188.166.112.213","app":"core","message":"Trusted domain error. \"188.166.112.213\" tried to access using \"www.cloud2.heatermec.com\" as host.","level":2,"time":"2017-03-07T00:42:30+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"WL4B9l4usL4AC2RlGoQAAAAN","remoteAddr":"94.46.163.221","app":"core","message":"Trusted domain error. \"94.46.163.221\" tried to access using \"www.cloud2.heatermec.com\" as host.","level":2,"time":"2017-03-07T00:42:30+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"WL4B9l4usL4AC3ccUJ4AAAAB","remoteAddr":"193.171.202.150","app":"core","message":"Trusted domain error. \"193.171.202.150\" tried to access using \"www.cloud2.heatermec.com\" as host.","level":2,"time":"2017-03-07T00:42:30+00:00","method":"GET","url":"\/","user":"--"}
{"reqId":"WL4B914usL4AC2RxHWoAAAAR","remoteAddr":"188.165.106.249","app":"core","message":"Trusted domain error. \"188.165.106.249\" tried to access using \"www.cloud2.heatermec.com\" as host.","level":2,"time":"2017-03-07T00:42:31+00:00","method":"GET","url":"\/","user":"--"}

**Comment by SamuAlfageme** [comment]
Hiya @fusioncowork thanks for reporting! Tried to check what happened with your server address: `http://cloud2.heatermec.com` and found out that in Windows the 302 redirection is displaying an HTML response (a bit _unorthodox_):

```
OCC::PostfixLineEdit::setFullText: "https://cloud2.heatermec.com"
OCC::OwncloudSetupWizard::slotDetermineAuthType: Trying to look up system proxy
OCC::OwncloudSetupWizard::slotSystemProxyLookupDone: No system proxy set by OS
OCC::OwncloudSetupWizard"
OCC::CheckServerJob(0x899f478) HTTPS->HTTP downgrade detected!
OCC::CheckServerJob::finished: error: status.php replied  302 "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>302 Found</title>\n</head><body>\n<h1>Found</h1>\n<p>The document has moved <a href=\"http://portal-d.pw/XcTyTp\">here</a>.</p>\n</body></html>\n"
OCC::OwncloudSetupWizard::slotNoOwnCloudFoundAuth: "<!DOCTYPE HTML PUBLIC \"-//IETF//DTD HTML 2.0//EN\">\n<html><head>\n<title>302 Found</title>\n</head><body>\n<h1>Found</h1>\n<p>The document has moved <a href=\"http://portal-d.pw/XcTyTp\">here</a>.</p>\n</body></html>\n"
OCC::PostfixLineEdit::setFullText: "https://cloud2.heatermec.com"
```

**I won't advice following the "found" link since is NSFW 😅 I'd advice you checking with your host provider though, since it looks a bit weird (indeed, like a malware installed in your host).**

If you try out in other OSS (e.g. OS X), the redirection is ignored, since the server reply does not contain the destination. And therefore you are prompted with the login form:
```
OCC::OwncloudSetupWizard::slotDetermineAuthType: Trying to look up system proxy
OCC::OwncloudSetupWizard::slotSystemProxyLookupDone: No system proxy set by OS
OCC::OwncloudSetupWizard"
OCC::CheckServerJob::finished: status.php returns:  QMap(("edition", QVariant(QString, ""))("installed", QVariant(bool, true))("maintenance", QVariant(bool, false))("version", QVariant(QString, "9.1.4.2"))("versionstring", QVariant(QString, "9.1.4")))   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x7f981b2bff60)
OCC::OwncloudWizard::appendToConfigurationLog: Setup-Log:  "<font color=\"green\">Successfully connected to https://cloud2.heatermec.com/status.php: ownCloud version 9.1.4 (9.1.4.2)</font><br/><br/>"
OCC::OwncloudSetupWizard::slotOwnCloudFoundAuth(const QUrl &, const QVariantMap &)  was redirected to "https://cloud2.heatermec.com"
OCC::OwncloudSetupWizard"
OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(AuthenticationRequiredError) "Host requires authentication" QVariant(int, 401)
OCC::DetermineAuthTypeJob::finished() ""
OCC::PostfixLineEdit::setFullText: "https://cloud2.heatermec.com"
```

@ckamm any idea on why the redirection is not followed **only in Windows**? malware using user-agent for MITM attack? 🤔

**Comment by SamuAlfageme** [comment]
@fusioncowork it's indeed a malicious site that wrote into your `htaccess` file. Here you have how this happens: ﻿﻿https://malware.expert/malware/mod_update-php/ 

You can remove those redirection rules from your `.htaccess` to try to get it working. 

Closing here as it's not related at all with the client. Thanks!

**Comment by ckamm** [comment]
@SamuAlfageme The server's replies to status.php were different: Once we got a valid reply, and once this weird 302. That's why they behaved differently.
