### ISSUE TITLE
On Windows, files beginning with '.' are not synced, even if they are not hidden.

### ISSUE THREAD

**Issue by KJ4IPS** [owncloud/client#5588]
This is being opened under owncloud as it is present here also, even though it was observed in nextcloud's branded client.

This does present a possible unusual situation where well-know filenames may start with a dot. Under linux/unix, hidden files are designated by a dot at the beginning of the filename, but on other OSs (Windows,OS X) they are designated by attributes. Because filename and hidden status on linux are entangled, the user may not be able to rename a directory they wish to be synced. (for example .config, via a custom map).

My initial suggestion is to still show files that are hidden in the tree view for folder selection (possibly with a show/hide check box) and simply have them disabled by default (like large files recieved from the server. However, on cursory inspection, it appears that the tree view works wholly off data on the remote side, so this may be difficult to implement.

### Expected behaviour
On windows, files beginning with '.' should be synced as normal.

### Actual behaviour
Files beginning with . are not synced, a message in the form "Not Synced: File/Folder ignored becaues it's hidden." appears in the client under Activity -> Not Synced

### Steps to reproduce
1. Inside a synced directory (on windows) create a folder beginning with . (you man need to use cmd/powershell to do this)
2. Observe that the file does not appear on the server, and the above mentioned message appears.
3. 

### Server configuration
Operating system: CentOS 7, + Docker

Web server: Nginx 1.10.3

Database: PostgreSQL

PHP version: 5.6.30

ownCloud version: Nextcloud 11.0.1 (stable)

Storage backend (external storage): xfs Filesystem, (Docker volume)

### Client configuration
Client version: 2.2.4 (Nextcloud Branding)

Operating system; Windows 10 x64

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): Not applicable

Client package (From ownCloud or distro) (Linux only):

Installation path of client: C:\Program Files (x86)\Nextcloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
Not applicable, no unusual content.

2. Web server error log: Not applicable, no error generated

3. Server logfile: ownCloud log (data/owncloud.log): Not applicable, no traffic generated.

**Comment by hodyroff** [comment]
This can be configured in .sync-exclude and is desired default behaviour. There is also the option to sync hidden files generally.
