### ISSUE TITLE
OpenSSL version: Output the actually loaded one, not the build version

### ISSUE THREAD

**Issue by t-b** [owncloud/client#5592]
### Expected behaviour
owncloud client should use the latest version of openssl available on the distribution.
On debian jessie this is currently `1.0.1t-1+deb8u6`.

Maybe it is only an issue of compile time openssl version vs. runtime openssl version. But even compiling against an old version is not the right thing to do.
### Actual behaviour
Owncloud client tells me

```
Gebaut von der GIT-Revision 832599 auf Mar 3 2017, 09:28:09 verwendet Qt 4.8.6, OpenSSL 1.0.1k 8 Jan 2015
```
### Client configuration
Client version: 2.3

Operating system:
debian jessie
OS language:
de

Installation path of client:
Packages from https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

```
2.3.0-1.1 (/var/lib/apt/lists/download.opensuse.org_repositories_isv:_ownCloud:_desktop_Debian%5f8.0_Packages) (/var/lib/dpkg/status)
 Description Language: 
                 File: /var/lib/apt/lists/download.opensuse.org_repositories_isv:_ownCloud:_desktop_Debian%5f8.0_Packages
                  MD5: 3ce97b207e6d1f58416ab77929104f12
```

**Comment by ogoffart** [comment]
Yes, that string is using the build-time version.

**Comment by ogoffart** [comment]
We can use QSslSocket::sslLibraryVersionString,  but that's only working with Qt 5, so it would not help in this case

**Comment by ckamm** [comment]
Note that the string says "built from ..." and then lists the compile-time QT and SSL versions. How useful are the build-versions vs runtime-versions? Currently `--version` shows the run-time Qt version.

**Comment by ckamm** [comment]
Adding more info to --version: https://github.com/owncloud/client/pull/5598

**Comment by t-b** [comment]
Why does the build daemon uses an outdated openssl version full of bugs?

**Comment by ckamm** [comment]
@ogoffart I'd expect that the runtime Qt and SSL versions are more useful, if you agree I'd adjust it.

Also, do you know whom to ask regarding the build daemon's openssl version?

**Comment by ckamm** [comment]
Pull request changing what is being shown: https://github.com/owncloud/client/pull/5619

**Comment by ckamm** [comment]
@ogoffart @guruz The remaining questing is: is building against an outdated version of openssl a problem? How do we update the build machine's version?

**Comment by ogoffart** [comment]
The build is done on OBS machines.  I guess the OBS machines where not up-to-date.
I believe this may even be intentional so we don't build against a version that the end user might not have.

**Comment by t-b** [comment]
> I believe this may even be intentional so we don't build against a version that the end user might not have.
Not applying security updates to be more compatible? Well I'm not sure...

**Comment by guruz** [comment]
@t-b If you think this poses a security problem to **YOU**, I recommend compiling the client yourself.

**Comment by ogoffart** [comment]
Since the openssl library is loaded dynamically, there should not be security issue by compiling against an outdated openssl. (unless there is an issue in inlined code, but i don't think it's the case). What count is the installed openssl.

I think the idea is that the client is build with the library in the default installation of the distribution.

That said, we could raise the minimum version of openssl in the package.

**Comment by SamuAlfageme** [comment]
@ogoffart 

> That said, we could raise the minimum version of openssl in the package. 

No longer needed after: https://github.com/owncloud/client/pull/5833 right? Actually, could this whole issue be closed?

**Comment by ogoffart** [comment]
Yes.
