### ISSUE TITLE
regression bug on 2.3 macos client with "/" or ":" in file or folder name  

### ISSUE THREAD

**Issue by joanlouis** [owncloud/client#5593]
in the past (2.2.X client) when a file or a folder name contain a / it was replaced by : on the server
but 2.3 client can't do it and the sync is aborted with a 500 error

### Expected behavior
the client must be capable to sync files with : (server side) and / (client side) in their name as 2.2 client does
### Actual behavior
if a file contain ":" (server side) -> 500 error

### Steps to reproduce
1. put on a server a file containing a ":" in the name
2. sync with 2.3 macos client

### Server configuration
Operating system: debian

Web server: apache

Database: mysql

PHP version: 5.4.45

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:2.3

Operating system: macos (tested on many versions 10.11.6 , 10.8.5 , 10.12.1)

OS language: french

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by ogoffart** [comment]
500 error means that the bug is likely to be on the server.

Please provide server logs.  What's the version of the server? Did you upgrade the server and the client at the same time?

**Comment by joanlouis** [comment]
just some clients have been upgraded the same folder sync well with 2.2 client but fail with 2.3 client
but effectively if i sync a file with / in the name with 2.3 client it's ok to reproduce the bug the file must be sync with 2.2 and upgrade the client to 2.3 .
server : 9.1
the server log : 

Exception: {"Message":"An exception occurred while executing 'INSERT INTO `oc_file_locks` (`key`,`lock`,`ttl`) SELECT ?,?,? FROM `oc_file_locks` WHERE `key` = ? HAVING COUNT(*) = 0' with params [\"files\\\/e4c33d9a5738ebb9361ae14975e2a38c\", 1, 1489155356, \"files\\\/e4c33d9a5738ebb9361ae14975e2a38c\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry 'files\/e4c33d9a5738ebb9361ae14975e2a38c' for key 'lock_key_index'","Exception":"Doctrine\\DBAL\\Exception\\UniqueConstraintViolationException","Code":0,"Trace":"#0 \/home\/web\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/DBALException.php(116): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 \/home\/web\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Connection.php(996): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'INSERT INTO `oc...', Array)\n#2 \/home\/web\/owncloud\/lib\/private\/DB\/Connection.php(209): Doctrine\\DBAL\\Connection->executeUpdate('INSERT INTO `oc...', Array, Array)\n#3 \/home\/web\/owncloud\/lib\/private\/DB\/Adapter.php(113): OC\\DB\\Connection->executeUpdate('INSERT INTO `*P...', Array)\n#4 \/home\/web\/owncloud\/lib\/private\/DB\/Connection.php(247): OC\\DB\\Adapter->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\n#5 \/home\/web\/owncloud\/lib\/private\/Lock\/DBLockingProvider.php(117): OC\\DB\\Connection->insertIfNotExist('*PREFIX*file_lo...', Array, Array)\n#6 \/home\/web\/owncloud\/lib\/private\/Lock\/DBLockingProvider.php(162): OC\\Lock\\DBLockingProvider->initLockField('files\/e4c33d9a5...', 1)\n#7 \/home\/web\/owncloud\/lib\/private\/Files\/Storage\/Common.php(668): OC\\Lock\\DBLockingProvider->acquireLock('files\/e4c33d9a5...', 1)\n#8 \/home\/web\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(584): OC\\Files\\Storage\\Common->acquireLock('files\/Serveur M...', 1, Object(OC\\Lock\\DBLockingProvider))\n#9 \/home\/web\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(584): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/Serveur M...', 1, Object(OC\\Lock\\DBLockingProvider))\n#10 \/home\/web\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(584): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/Serveur M...', 1, Object(OC\\Lock\\DBLockingProvider))\n#11 \/home\/web\/owncloud\/apps\/files_sharing\/lib\/sharedstorage.php(372): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('files\/Serveur M...', 1, Object(OC\\Lock\\DBLockingProvider))\n#12 \/home\/web\/owncloud\/lib\/private\/Files\/Storage\/Wrapper\/Wrapper.php(584): OC\\Files\\Storage\\Shared->acquireLock('2011\/Soci\\xC3\\xA9t\\xC3\\xA9s...', 1, Object(OC\\Lock\\DBLockingProvider))\n#13 \/home\/web\/owncloud\/lib\/private\/Files\/View.php(1916): OC\\Files\\Storage\\Wrapper\\Wrapper->acquireLock('2011\/Soci\\xC3\\xA9t\\xC3\\xA9s...', 1, Object(OC\\Lock\\DBLockingProvider))\n#14 \/home\/web\/owncloud\/lib\/private\/Files\/View.php(2022): OC\\Files\\View->lockPath('\/C CONSEIL\/2011...', 1)\n#15 \/home\/web\/owncloud\/lib\/private\/Files\/View.php(1105): OC\\Files\\View->lockFile('\/C CONSEIL\/2011...', 1)\n#16 \/home\/web\/owncloud\/lib\/private\/Files\/View.php(962): OC\\Files\\View->basicOperation('fopen', 'C CONSEIL\/2011\/...', Array, 'rb')\n#17 \/home\/web\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/File.php(304): OC\\Files\\View->fopen('C CONSEIL\/2011\/...', 'rb')\n#18 \/home\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(83): OCA\\DAV\\Connector\\Sabre\\File->get()\n#19 [internal function]: Sabre\\DAV\\CorePlugin->httpGet(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#20 \/home\/web\/owncloud\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#21 \/home\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:GET', Array)\n#22 \/home\/web\/owncloud\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#23 \/home\/web\/owncloud\/apps\/dav\/appinfo\/v1\/webdav.php(56): Sabre\\DAV\\Server->exec()\n#24 \/home\/web\/owncloud\/remote.php(164): require_once('\/home\/web\/owncl...')\n#25 {main}","File":"\/home\/web\/owncloud\/3rdparty\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/AbstractMySQLDriver.php","Line":66,"User":"chris"}

**Comment by ogoffart** [comment]
@DeepDiver1975 or @PVince81 : i need advice from a server dev.

What can cause this error? Then maybe i can figure out why was it not a problem with the 2.2 client.

**Comment by PVince81** [comment]
is there a number behind the colon ":" of said filenames ? if yes, please update to 9.1.4.

**Comment by PVince81** [comment]
ref https://github.com/owncloud/core/issues/25479

**Comment by ogoffart** [comment]
Also, file cannot contains '/'

**Comment by joanlouis** [comment]
PVince yes this is the problem you point. upgrade to 9.1.4 resolve the problem
