### ISSUE TITLE
OpenBSD issue - "Too many open files"

### ISSUE THREAD

**Issue by bceverly** [owncloud/client#5595]
### Expected behaviour
Client application should successfully launch and begin syncing.

### Actual behaviour
Application segfaults with the following output:
libGL error: unable to load driver: swrast_dri.so
libGL error: failed to load driver: swrast
(process:58877): GLib-ERROR **: Creating pipes for GWakeup: Too many open files
Trace/BPT trap (core dumped)

### Steps to reproduce
1. Run owncloudclient from the shell

### Server configuration
Operating system: OpenBSD 6.0

Web server: nginx

Database:mysql

PHP version:7.0.13

ownCloud version:9.1.2

Storage backend (external storage):zfs (freebsd)

### Client configuration
Client version:2.2.4p0

Operating system:OpenBSD 6.0

OS language:

Qt version used by client package (Linux only, see also Settings dialog):5.6.2

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by bceverly** [comment]
This is 100% a client side issue.  Everything works fine against this same server from Linux.  Trying to figure out how I can troubleshoot it so any tips would be very much appreciated.

**Comment by guruz** [comment]
Did you try to use lsof (or so?) to check what are the open files?

Can you compile Qt without the glib event dispatcher?

**Comment by ogoffart** [comment]
You can use the environment variable `QT_NO_GLIB=1` to try Qt without the glib event dispatcher.

I would suspect this might be a problem with the file system watcher.
maybe related to the filesystemwatcher? (we use inotify)
How many directories and files do you have in your sync directory?

**Comment by yason** [comment]
Hi.
You need to tweak your login.conf and increase openfiles-cur and openfiles-max for your login class.

**Comment by guruz** [comment]
@bceverly Does this help?

**Comment by gawin** [comment]
@guruz a little bit late to the party, but this fixed it for me:

/etc/sysctl.conf
```
kern.maxfiles=102400
```

/etc/login.conf
```
openfiles-max=102400
openfiles-cur=102400
```

Restart and verify:
```
$ sysctl kern.maxfiles
kern.maxfiles=102400
$ ulimit -n
102400
```

Note that `102400` is rather large, so please adjust as needed.
Added this for others that might run into the same issue.

**Comment by josefig** [comment]
> @bceverly @guruz a little bit late to the party, but this fixed it for me:
> 
> /etc/sysctl.conf
> 
> ```
> kern.maxfiles=102400
> ```
> 
> /etc/login.conf
> 
> ```
> openfiles-max=102400
> openfiles-cur=102400
> ```
> 
> Restart and verify:
> 
> ```
> $ sysctl kern.maxfiles
> kern.maxfiles=102400
> $ ulimit -n
> 102400
> ```
> 
> Note that `102400` is rather large, so please adjust as needed.
> Added this for others that might run into the same issue.

Remember the make cache. [1] [2]

1. https://man.openbsd.org/login.conf.5
2. https://man.openbsd.org/cap_mkdb.1

This helped me. Thanks.
