### ISSUE TITLE
Allow context menu to open the local Folder/subfolder in selective sync list in main window

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5596]

**Comment by ckamm** [comment]
@guruz Do you mean for the sync folder or for the individual selective-sync folders?

It seems we'll have to manually disambiguate single and double clicks for that.

**Comment by guruz** [comment]
I meant individual folders.

**Comment by guruz** [comment]
Apparantly double click detection is tricky for Qt/legacy reasons, let's have it in a right-mouse button menu.

**Comment by guruz** [comment]
Needs a quick test on Windows

**Comment by SamuAlfageme** [comment]
Lookin' neat: 

![opensubfolder](https://cloud.githubusercontent.com/assets/2644445/25800377/5c497e62-33e9-11e7-9dc0-1d51af303087.gif)
