### ISSUE TITLE
Undefined reference to 'adler32' win7

### ISSUE THREAD

**Issue by xormultiplexus** [owncloud/client#5599]
Hello,

i am unable to build the client. I've tried with the latest version, openssl (both 32 and 64 bit), qt 5.8.0; win7 64bit sp1;
The error is:

[ 29%] Linking CXX shared library ..\..\bin\libowncloudsync.dll
CMakeFiles\owncloudsync.dir/objects.a(filesystem.cpp.obj):filesystem.cpp:(.text+
0x1cd7): undefined reference to `adler32'
CMakeFiles\owncloudsync.dir/objects.a(filesystem.cpp.obj):filesystem.cpp:(.text+
0x1d7c): undefined reference to `adler32'
collect2.exe: error: ld returned 1 exit status
src\libsync\CMakeFiles\owncloudsync.dir\build.make:1188: recipe for target 'bin/
libowncloudsync.dll' failed
mingw32-make[2]: *** [bin/libowncloudsync.dll] Error 1
CMakeFiles\Makefile2:241: recipe for target 'src/libsync/CMakeFiles/owncloudsync
.dir/all' failed
mingw32-make[1]: *** [src/libsync/CMakeFiles/owncloudsync.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by SamuAlfageme** [comment]
Hey, @xormultiplexus! Thanks for your interest on the client development. 

We have a way to build the client installer using Docker (which also [works on Windows](https://docs.docker.com/docker-for-windows/)). Check [**this link**](https://central.owncloud.org/t/error-using-docker-to-build-the-windows-client/5107/5?u=alfageme) for more instructions on how to build from there. 

If you still want and need help building the client on windows, you can always post the issues you face in https://central.owncloud.org. Closing here as this is not strictly speaking an issue. 

Thank you for reporting! 😊
