### ISSUE TITLE
Pop-up Window for excluded file list / Second column is too narrow

### ISSUE THREAD

**Issue by ldmpub** [owncloud/client#5600]
Hi,

I have updated french translation and it misses 2 caracters (1 at the start and 1 at the end) in the 2d column title which should be "Autoriser suppression" (and more better "Autoriser la suppression automatique" (with means in englih "Authorize automatic deletion").

Can we:
- extend this column width
- add automatic line breaks in this column?

See current screen shot in the Desktop client:
![exclude file list - column width](https://cloud.githubusercontent.com/assets/1452146/23824122/2eb0f96c-0671-11e7-8577-bc959e2c21ce.png)

**Comment by hodyroff** [comment]
Hopefully easy ;) Thanks a lot for your help!

**Comment by ldmpub** [comment]
Tested on Nightly Version 2.3.1-nightly20170315 (build 6806) / Git d95b43 15 2017, 01:34:51 => it's OK.

Many thanks; this issue can be closed from my point of view ... even if the first column is now a little too big ;-).

**Comment by ldmpub** [comment]
Everything is ok from my point of view: my initial request + other columns width in the same Windows popup => I have tested it ok on Version 2.3.2-nightly20170429 (build 6906).
Can we close this issue?
