### ISSUE TITLE
Duplicated uploads from android client - even in same directory

### ISSUE THREAD

**Issue by nneul** [owncloud/client#5601]
### Expected behaviour
Sharing a file multiple times with OwnCloud client on android should not result in multiple duplicate copies of the file in the instant upload directory.

### Actual behaviour
Multiple files created with (2) in the name for example, even though they are checksum identical.

### Steps to reproduce
1. Allow a file to automatically instant upload
2. Share file explicitly with oc - typically as a "I want to make sure everything is uploaded" share in a big batch.

### Client configuration
Client version: 2.3.0
Operating system: Android

I understand your view that in general OC should not concern itself with duplicate uploads/files/etc. but this is a bit of a more relevant/important edge case with mobile. I think there should either be a means to check and avoid duplicating files during upload process when the files are being uploaded to the SAME directory.

**Comment by hodyroff** [comment]
This issue happens on Android, right? Please give us some more information about the Android version you are using and how exactly it can be reproduced. "Share file explicitly with oc" ... I don't understand. Which menu entry in Android are you using to do that?

**Comment by hodyroff** [comment]
Issue moved to [owncloud/android #1922](https://github.com/owncloud/android/issues/1922) via [**ZenHub**](https://www.zenhub.com/)

**Comment by nneul** [comment]
Seen it on multiple versions, reproduced with current 7.0 on an sgs7. 

To reproduce - go to any file explorer application or the photo gallery - select a bunch of photos or files, click "Share" icon, choose owncloud from the application list. Owncloud will pop up and ask you for a folder to share them to. Pick the folder - in my case, I'm choosing the folder I'm using for instant uploads since I'm wanting to upload a bunch of files that were missed due to having instant upload turned off - but there is some overlap with when it was. 

If files were already uploaded, it will create duplicate+renamed files - even though an exactly matching file already exists in the same folder.
