### ISSUE TITLE
owncloud client can't download files larger than 2Gb

### ISSUE THREAD

**Issue by krot-mstu** [owncloud/client#5602]
### Actual behaviour
Owncloud client can't download files larger than 2Gb with error "<name of the file>: The downloaded file is empty despite the server announced it should have been <size>Gb "

### Steps to reproduce
1. Put file larger than 2Gb into the owncloud folder on the client_1
2. Wait while it is synced to the server. In this moment file is available on the server in the /owncloud/data/<user> folder
3. Client_2 on the another PC shows error like "<name of the file>: The downloaded file is empty despite the server announced it should have been <size>Gb "

### Server configuration
Operating system:
Linux raspberry 4.1.19-v7+ #858 SMP Tue Mar 15 15:56:00 GMT 2016 armv7l armv7l armv7l GNU/Linux

Web server: 
Apache\/2.4.18 (Ubuntu)

Database:
        "dbtype": "sqlite3",
        "version": "9.1.4.2",

PHP version:
php 7

ownCloud version:
ownCloud version": "9.1.4.2

Storage backend (external storage):
local disk

### Client configuration
Client version:
ownCloud version 2.3.0

Operating system:
Linux PC 4.8.0-41-generic #44-Ubuntu SMP Fri Mar 3 15:27:17 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
(Ubuntu 16.10)

OS language:
En

Qt version used by client package (Linux only, see also Settings dialog):
Using Qt 4.8.7

Client package (From ownCloud or distro) (Linux only):
2.3.0 rev 832599

Installation path of client:
/usr/bin/owncloud

### Logs

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
03-12 02:05:07:499 0x55e6b48dfce0 * Ignoring file "xxx/.xxx.ISO.~1e386f47" 
03-12 02:05:07:505 0x55e6b48dfce0 * Ignoring file "xxxx/.xxx.vmdk.~5918e0c8" 
....

2. Web server error log:
Error 	PHP 	stream_copy_to_stream() expects parameter 3 to be integer, string given at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#78 	2017-03-11T22:00:09+00:00
Error 	PHP 	stream_copy_to_stream() expects parameter 3 to be integer, string given at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#78 	2017-03-11T22:00:08+00:00
Error	PHP	stream_copy_to_stream() expects parameter 3 to be integer, string given at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#78	2017-03-11T23:06:31+00:00
Error	PHP	stream_copy_to_stream() expects parameter 3 to be integer, string given at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#78	2017-03-11T23:06:31+00:00
Error	PHP	stream_copy_to_stream() expects parameter 3 to be integer, string given at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#78	2017-03-11T23:06:31+00:00
Error	PHP	stream_copy_to_stream() expects parameter 3 to be integer, string given at /var/www/owncloud/3rdparty/sabre/http/lib/Sapi.php#78	2017-03-11T23:05:07+00:00

3. Server logfile: ownCloud log (data/owncloud.log):
{"reqId":"48dOA2XljQfDJM5+9dlU","remoteAddr":"xxx","app":"PHP","message":"stream_copy_to_stream() expects parameter 3 to be integer, string given at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#78","level":3,"time":"2017-03-11T23:06:31+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/xxxx","user":"xxx"}
{"reqId":"5mntxR8vxaRghWxPXOdw","remoteAddr":"xxx","app":"PHP","message":"stream_copy_to_stream() expects parameter 3 to be integer, string given at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#78","level":3,"time":"2017-03-11T23:06:32+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/xxxx","user":"xxx"}
{"reqId":"yY9yE0YAhNmdHw0I7232","remoteAddr":"192.168.1.226","app":"PHP","message":"stream_copy_to_stream() expects parameter 3 to be integer, string given at \/var\/www\/owncloud\/3rdparty\/sabre\/http\/lib\/Sapi.php#78","level":3,"time":"2017-03-11T23:06:32+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/vmware\/xxx","user":"xxx"}

**Comment by hodyroff** [comment]
Did this work before for you? 1 GB and 1.8GB work?

**Comment by ogoffart** [comment]
I could not reproduce the bug, the sync worked fine with me.
@SamuAlfageme  Did you also try synchronizing big files?

This could be a server problem,  can you download the file with your browser, and does it work then?

**Comment by krot-mstu** [comment]
Hello  hodyroff  and ogoffart, I also can't download big files via GUI. As I can see, I have issue only with 2Gb and bigger files. I haven't had such issue earlier.
My installation is available via internet, I can give you access  (account) in the case if it can help.

**Comment by hodyroff** [comment]
It is not a client issue in this case.
There are many things around big files which can be configured wrongly, here is some documentation:
https://doc.owncloud.org/server/9.1/admin_manual/configuration_files/big_file_upload_configuration.html
Generally you can ask on central.owncloud.org for such configuration issues and likely will get some additional help but first follow the different steps to configure your setup correctly for large files.

**Comment by krot-mstu** [comment]
I've done, no changes. In my case I can't download big files. Not upload

**Comment by ogoffart** [comment]
If you also can't download them with the web interface, this is not a client issue. The bug is probably in the server. Which has some complication with big files.

**Comment by filerem** [comment]
i confirm this bug. my configuration is a ubuntu 16.04 server with owncloud 9.1.6 , and only big file >2gb had problem. 
i can't download this file via web interface, the file downloaded = 0bytes.
but all over works.

**Comment by ogoffart** [comment]
@filerem  This is a server configuration issue, please check the documentation about big files or ask question on the forum: https://owncloud.org/support/
