### ISSUE TITLE
certificate information display error

### ISSUE THREAD

**Issue by tessus** [owncloud/client#5603]
Version 2.3.0 (build 4097)

The certificate information seems to have a display error: The text always starts with a `)` character.
See screenshot below.

<img width="770" alt="certinfo" src="https://cloud.githubusercontent.com/assets/223439/23828948/1c8b62f6-06b0-11e7-928d-2c865a05aaf8.png">

**Comment by phil-davis** [comment]
Version 2.3.0 (build 6780) on also has this. I know there was a right-bracket accidentally intriduced a few weeks ago and that was fixed. It somehow did not get into the release build :(

**Comment by tessus** [comment]
Thanks for the info.
