### ISSUE TITLE
Owncloud Centos Latest Client 2.3.0 Sync Error

### ISSUE THREAD

**Issue by infosrig** [owncloud/client#5604]
Just updated the centos client 2.3.0, but getting always unknown error and connection lost

### Expected behaviour
Expected to sync around 1.5 GB of Data

### Actual behaviour
Getting Error like "unknown Error" and getting lost connection to the server.
When tried to "force sync" it works for few files but again got interrupted. The issue continues inconsistently.

But in windows client, same data from same server synced without any issues.
### Steps to reproduce
1. Upgrade centos desktop centos client to 2.3.0
2. Sync with server

### Server configuration
Operating system:  Centos 6.5

Web server: Apache/2.2.15 (Unix)

Database: MariaDB SQL

PHP version: PHP 5.6.30

ownCloud version: 9.1.4 

Storage backend (external storage): Yes

### Client configuration
Client version: 2.3.0 

Operating system: Centos 6.8

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only): Distro

Installation path of client: /usr/bin/owncloud

### Logs

03-12 14:50:50:183 0xf56340 virtual OCC::BandwidthManager::~BandwidthManager() 
03-12 14:50:50:184 0xf56340  - client version 2.3.0  Qt 4.8.6 
03-12 14:50:50:185 0xf56340 -> SyncEngine finished with ERROR 
03-12 14:50:50:201 0xf56340 OO folder slotSyncFinished: result:  3 
03-12 14:50:50:202 0xf56340     * owncloud csync thread finished with error 
03-12 14:50:50:202 0xf56340 the last 12 syncs failed 
03-12 14:50:50:202 0xf56340 Sync state changed for folder  "https://g4m-phx.dyndns.org:1011/owncloud/remote.php/webdav/" :  "Error" 
03-12 14:50:50:403 0xf56340 <===================================== sync finished for  "https://g4m-phx.dyndns.org:1011/owncloud/remote.php/webdav/" 
03-12 14:51:11:987 0xf56340 # Check whether authenticated propfind works. 
03-12 14:51:11:988 0xf56340 !!! OCC::PropfindJob created for "https://g4m-phx.dyndns.org/owncloud" + "/" "OCC::ConnectionValidator" 
03-12 14:51:14:798 0xf56340 !!! OCC::PropfindJob created for "https://g4m-phx.dyndns.org/owncloud" + "/" "OCC::QuotaInfo" 
03-12 14:51:15:790 0xf56340 Saving account "https://g4m-phx.dyndns.org:1011/owncloud" 
03-12 14:51:15:791 0xf56340 Saving  1  unknown certs. 
03-12 14:51:15:792 0xf56340 Saving cookies. "/home/sridhar/.local/share/data//ownCloud//cookies0.db" 
03-12 14:51:15:793 0xf56340 "/home/sridhar/.local/share/data//ownCloud//cookies0.db" 
03-12 14:51:15:794 0xf56340 Saved account settings, status: 0 
03-12 14:51:28:298 0xf56340 * Trying to check "https://g4m-phx.dyndns.org:1011/owncloud/remote.php/webdav/" for changes via ETag check. (time since last sync: 38 s) 
03-12 14:51:28:299 0xf56340 Scheduling "https://g4m-phx.dyndns.org:1011/owncloud/remote.php/webdav/" to check remote ETag 
03-12 14:51:28:299 0xf56340 !!! OCC::RequestEtagJob created for "https://g4m-phx.dyndns.org/owncloud" + "/" "OCC::Folder" 

1. Client logfile: 
[owncloud-clent-2.3.0-log.txt](https://github.com/owncloud/client/files/836404/owncloud-clent-2.3.0-log.txt)

**Comment by ogoffart** [comment]
Few interresting things from the log file:

```
03-12 14:50:49:946 0xf56340 Saving account "https://g4m-phx.dyndns.org:1011/owncloud" 
03-12 14:50:49:947 0xf56340 Saving  1  unknown certs. 
03-12 14:50:49:948 0xf56340 Saving cookies. "/home/sridhar/.local/share/data//ownCloud//cookies0.db" 
03-12 14:50:49:949 0xf56340 "/home/sridhar/.local/share/data//ownCloud//cookies0.db" 
03-12 14:50:49:949 0xf56340 Saved account settings, status: 0 
```
Repeated 3 times.
Why are we saving the account?  Could be because of Account::slotHandleSslErrors. 
So maybe that's normal

```
03-12 14:50:50:084 0xf56340 void OCC::AbstractNetworkJob::slotFinished() 99 "Unknown error" QVariant(, ) 
03-12 14:50:50:085 0xf56340 void OCC::PropagateDownloadFile::slotGetFinished()  QUrl( "https://g4m-phx.dyndns.org:1011/owncloud/remote.php/webdav/[redacted].pdf" )  FINISHED WITH STATUS 99 "Unknown error" 0 0 51164 0 "" "" 
```

We need to figure out what this "Unkown error" could be.

```
03-12 14:50:50:122 0xf56340 ASSERT: "i >= 0" in file /home/abuild/rpmbuild/BUILD/owncloudclient-2.3.0/src/libsync/owncloudpropagator.cpp, line 665
```

That's another bug that should be fixed in 2.3.1  



Anyway, the problem here is that we have an "Unkown Error", would be interresting to know what causes the problem.  

@guruz: any idea?

I guess a network trace could help to know what really happened at the network level? (Was the transfer successful or not)

**Comment by infosrig** [comment]
Thanks for your concern.

FYI : In windows this version is working good with the same server.

**Comment by guruz** [comment]
I'd be curious if @infosrig gets different behaviour with the Qt 5.6.2 based packages.

https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client

**Comment by infosrig** [comment]
Yes, Encountered the same issue even with this "http://download.opensuse.org/repositories/isv:ownCloud:devel:Qt562/CentOS_6/isv:ownCloud:devel:Qt562.repo" 

Even I have removed the ~/.local/share/data/ownCloud before installing the above version.

Attaching the screenshot.
![screenshot-owncloud](https://cloud.githubusercontent.com/assets/26358081/23981798/59211c24-0a2f-11e7-947f-68eed54ced72.png)

**Comment by guruz** [comment]
And you're saying 2.2.4 worked fine?

**Comment by infosrig** [comment]
Yes, Of course. It was working well until this update.

**Comment by guruz** [comment]
So from your screenshot we can see that even the selective sync returns that "Unknown Error".
Can you check your server side access.log and error.log for details on what is happening?

I'm unsure on why this should be different between those client versions.

Do you use proxies?

**Comment by infosrig** [comment]
I shall check and revert back to u.

Meanwhile could you please tell how to pull old version(Linux 2.2.4) of the client? When I try to pull the 2.2.4 from the URL "https://owncloud.org/changelog/desktop/" it lands in 2.3.0. 

Not only 2.2.4 all the old version links to Linux is landing at 2.3.0. I think this is not intentional

**Comment by infosrig** [comment]
Do you mean apache access and error logs?

**Comment by jnweiger** [comment]
Downloads for older releases are very hard to find. Sorry for this. The last two we have are

https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adesktop%3Aclient-2.2.4&package=owncloud-client
and
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adesktop%3Aclient-2.2.1&package=owncloud-client

Note that these are not exact archives, but are actually rebuilds.

**Comment by infosrig** [comment]
I am sorry to say, after installation this too having the same issue.

BTW, this is showing 2.3.0 in the display. is it normal for the rebuild?

![screenshot-owncloud-3](https://cloud.githubusercontent.com/assets/26358081/24034905/233404c4-0b19-11e7-9a50-7961e086c6dc.png)
![screenshot-owncloud-2](https://cloud.githubusercontent.com/assets/26358081/24034906/2336295c-0b19-11e7-8160-3fd2f79fc0d6.png)

**Comment by guruz** [comment]
@infosrig If it shows 2.3.0 in that dialogue then you didn't downgrade to 2.2.4

Can you (WHEN USING 2.3.0) still check the Apache access log and error log?
We need to know which error the server thinks that it sends (if the client only sees "Unknnown error")

**Comment by infosrig** [comment]
@guruz I have installed the package from below URL and followed the steps.

```
cd /etc/yum.repos.d/

wget http://download.opensuse.org/repositories/isv:ownCloud:desktop:client-2.2.4/CentOS_6/isv:ownCloud:desktop:client-2.2.4.repo

yum install owncloud-client
```

**ACCESS LOG**

202.83.36.28 - admin [14/Mar/2017:00:10:32 -0700] "GET /owncloud/status.php HTTP/1.1" 200 95
137247 202.83.36.28 - admin [14/Mar/2017:00:10:33 -0700] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 383
137248 202.83.36.28 - admin [14/Mar/2017:00:10:35 -0700] "GET /owncloud/ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 652
137249 202.83.36.28 - admin [14/Mar/2017:00:10:37 -0700] "GET /owncloud/ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 138
137250 202.83.36.28 - admin [14/Mar/2017:00:10:38 -0700] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74
137251 202.83.36.28 - admin [14/Mar/2017:00:10:38 -0700] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 423
137252 202.83.36.28 - admin [14/Mar/2017:00:10:38 -0700] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 4823

202.83.36.28 - admin [14/Mar/2017:00:13:38 -0700] "PROPFIND /owncloud/remote.php/webdav/Admin-Data/Official/Legal-Contracts HTTP/1.1" 207 4799
137362 202.83.36.28 - admin [14/Mar/2017:00:13:40 -0700] "PROPFIND /owncloud/remote.php/webdav/Admin-Data/Official/Legal-Contracts/ abc HTTP/1.1" 207 1477
137363 202.83.36.28 - admin [14/Mar/2017:00:13:42 -0700] "PROPFIND /owncloud/remote.php/webdav/Admin-Data/Official/Legal-Contracts/abc HTTP/1.1" 207 7800
137364 202.83.36.28 - admin [14/Mar/2017:00:13:44 -0700] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 383

202.83.36.28 - - [14/Mar/2017:00:14:23 -0700] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74
137390 202.83.36.28 - admin [14/Mar/2017:00:14:48 -0700] "GET /owncloud/status.php HTTP/1.1" 200 95
137391 202.83.36.28 - admin [14/Mar/2017:00:14:49 -0700] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 383
137392 202.83.36.28 - admin [14/Mar/2017:00:14:51 -0700] "GET /owncloud/ocs/v1.php/cloud/capabilities?format=json HTTP/1.1" 200 652
137393 202.83.36.28 - - [14/Mar/2017:00:14:52 -0700] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74
137394 202.83.36.28 - admin [14/Mar/2017:00:14:53 -0700] "GET /owncloud/ocs/v1.php/cloud/user?format=json HTTP/1.1" 200 138
137395 202.83.36.28 - admin [14/Mar/2017:00:14:54 -0700] "GET /owncloud/ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 74
137396 202.83.36.28 - admin [14/Mar/2017:00:14:54 -0700] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 423
137397 202.83.36.28 - admin [14/Mar/2017:00:14:54 -0700] "PROPFIND /owncloud/remote.php/webdav/ HTTP/1.1" 207 4823
137398 202.83.36.28 - admin [14/Mar/2017:00:14:55 -0700] "PROPFIND /owncloud/remote.php/webdav/Admin-Data HTTP/1.1" 207 10960

**Error Log**

[Sat Mar 11 02:05:09 2017] [error] [client 202.83.36.173] PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in dri    ver: SQLSTATE[HY000] [2002] No such file or directory' in /var/www/html/owncloud/lib/private/DB/Connection.php:58\nStack trace:\n#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connect    ion.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/    html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connec    tion.php(621): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/html/owncloud/lib/private/DB/Connection.php(141): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/html/ow    ncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Ar in /var/www/html/owncloud/lib/private/DB/Connection.php on line 58
 31 [Sat Mar 11 02:05:09 2017] [error] [client 202.83.36.173] PHP Fatal error:  Uncaught exception 'Doctrine\\DBAL\\DBALException' with message 'Failed to connect to the database: An exception occured in dri    ver: SQLSTATE[HY000] [2002] No such file or directory' in /var/www/html/owncloud/lib/private/DB/Connection.php:58\nStack trace:\n#0 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connect    ion.php(429): OC\\DB\\Connection->connect()\n#1 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\\DBAL\\Connection->getDatabasePlatformVersion()\n#2 /var/www/    html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\\DBAL\\Connection->detectDatabasePlatform()\n#3 /var/www/html/owncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Connec    tion.php(621): Doctrine\\DBAL\\Connection->getDatabasePlatform()\n#4 /var/www/html/owncloud/lib/private/DB/Connection.php(141): Doctrine\\DBAL\\Connection->setTransactionIsolation(2)\n#5 /var/www/html/ow    ncloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DriverManager.php(172): OC\\DB\\Connection->__construct(Ar in /var/www/html/owncloud/lib/private/DB/Connection.php on line 58
 32 [Sat Mar 11 02:25:17 2017] [error] [client 202.83.36.173] File does not exist: /var/www/html/favicon.ico, referer: https://g4m-phx.dyndns.org:1011/
 33 [Sat Mar 11 04:40:51 2017] [error] [client 202.83.36.173] File does not exist: /var/www/html/ownlcoud
 34 [Sat Mar 11 04:40:52 2017] [error] [client 202.83.36.173] File does not exist: /var/www/html/ownlcoud
 35 [Sat Mar 11 21:26:19 2017] [error] [client 202.83.36.173] File does not exist: /var/www/html/owncloud/status
 36 [Sat Mar 11 21:26:21 2017] [error] [client 202.83.36.173] File does not exist: /var/www/html/favicon.ico, referer: https://g4m-phx.dyndns.org:1011/owncloud/status
 37 [Sun Mar 12 00:34:51 2017] [error] [client 202.83.36.173] File does not exist: /var/www/html/favicon.ico, referer: https://98.167.166.109:1011/
 38 [Sun Mar 12 03:29:02 2017] [warn] RSA server certificate is a CA certificate (BasicConstraints: CA == TRUE !?)
 39 [Sun Mar 12 03:29:02 2017] [warn] RSA server certificate CommonName (CN) `g4m-ph100' does NOT match server name!?
 40 [Sun Mar 12 04:57:22 2017] [error] [client 84.169.229.230] File does not exist: /var/www/html/favicon.ico
 41 [Sun Mar 12 04:57:22 2017] [error] [client 84.169.229.230] File does not exist: /var/www/html/favicon.ico
 42 [Mon Mar 13 13:10:18 2017] [error] [client 66.249.75.4] File does not exist: /var/www/html/robots.txt

**Comment by jnweiger** [comment]
@infosrig I can guess two possible error sources here:

* Please make sure you really exit the owncloud client before or after upgrade. Upgrading the files on the disk does not update a running process.

* Your yum probably just does nothing, when it sees, you already have a later version. Please make sure that you de-install 2.3.0 first. E.g. try 
```
rpm -e owncloud-client
rpm -e owncloud-client-l10n
rpm -e libowncloudsync0
yum install 'owncloud-client = 2.2.4'
```

**Comment by guruz** [comment]
@infosrig Any news from you?

**Comment by infosrig** [comment]
Thanks @guruz and @jnweiger 

Could able to re-install 2.2.4 by uninstalling 2.3.0 completely by removing 'owncloud-client-l10n' and now showing 2.2.4 in the window, But even now getting same issues as previously shown screenshot as (2.3.0). 

Is there any information for you ppl to interpret from access and error logs in my previous post?

FYI : In windows-8, client 2.3.0 is working great.!

**Comment by infosrig** [comment]
Hello Geeks,

Any suggestion regarding this issue?

I am stuck here.

**This is latest log report**

```
03-24 11:51:55:881 0x12ea340  - client version 2.3.1  Qt 4.8.6 
03-24 11:51:55:881 0x12ea340 -> SyncEngine finished with ERROR 
03-24 11:51:55:883 0x12ea340 OO folder slotSyncFinished: result:  3 
03-24 11:51:55:883 0x12ea340     * owncloud csync thread finished with error 
03-24 11:51:55:883 0x12ea340 the last 4 syncs failed 
03-24 11:51:55:884 0x12ea340 Sync state changed for folder  "https://g4m-phx.dyndns.org:1011/owncloud/remote.php/webdav/" :  "Error" 
```

**Comment by guruz** [comment]
@infosrig You're still using the Qt 4.8.6 based packages. Please instead try the ones based on Qt 5.6.2
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client
