### ISSUE TITLE
client-2.30 with Qt-5.6.2 crashes on Ubuntu-14.04

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#5610]
while testing first build results for https://github.com/owncloud/client/issues/5470:

The client starts fine, diggs through the discovery phase for several minutes, but as soon, as it descides to sync the first file, this happenes:

<pre>
 [New Thread 0x7fc716ffd700 (LWP 22255)]

Program received signal SIGSEGV, Segmentation fault.
0x00007fc74100db22 in OCC::PropagateDirectory::scheduleNextJob() ()
from /opt/ownCloud/Qt-5.6.2/lib/x86_64-linux-gnu/libowncloudsync.so.0
(gdb)
Ubuntu 14.04

```
(gdb) where
#0  0x00007fc74100db22 in OCC::PropagateDirectory::scheduleNextJob() ()
   from /opt/ownCloud/Qt-5.6.2/lib/x86_64-linux-gnu/libowncloudsync.so.0
#1  0x00007fc74100da73 in OCC::PropagateDirectory::scheduleNextJob() ()
   from /opt/ownCloud/Qt-5.6.2/lib/x86_64-linux-gnu/libowncloudsync.so.0
#2  0x00007fc74100da73 in OCC::PropagateDirectory::scheduleNextJob() ()
   from /opt/ownCloud/Qt-5.6.2/lib/x86_64-linux-gnu/libowncloudsync.so.0
#3  0x00007fc74100c7b5 in OCC::OwncloudPropagator::scheduleNextJob() ()
   from /opt/ownCloud/Qt-5.6.2/lib/x86_64-linux-gnu/libowncloudsync.so.0
#4  0x00007fc73e4e55f6 in QObject::event(QEvent*) ()
   from /opt/ownCloud/Qt-5.6.2/lib/x86_64-linux-gnu/libQt5Core.so.5
#5  0x00007fc741468c1c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
   from /opt/ownCloud/Qt-5.6.2/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#6  0x00007fc74146d29a in QApplication::notify(QObject*, QEvent*) ()
   from /opt/ownCloud/Qt-5.6.2/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007fc73e4b9925 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
   from /opt/ownCloud/Qt-5.6.2/lib/x86_64-linux-gnu/libQt5Core.so.5
#8  0x00007fc73e4bb76a in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
   from /opt/ownCloud/Qt-5.6.2/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007fc73e50bbc3 in ?? () from /opt/ownCloud/Qt-5.6.2/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007fc73ccd0e04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#11 0x00007fc73ccd1048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007fc73ccd10ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007fc73e50b20c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
---Type <return> to continue, or q <return> to quit---
   from /opt/ownCloud/Qt-5.6.2/lib/x86_64-linux-gnu/libQt5Core.so.5
#14 0x00007fc73e4b787b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /opt/ownCloud/Qt-5.6.2/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007fc73e4bf986 in QCoreApplication::exec() ()
   from /opt/ownCloud/Qt-5.6.2/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x000000000046d897 in main ()
(gdb) 
</pre>

Next possible steps:

* build debug packages. pkg-create-dbgsym helps, but does not get picked up by OBS.

* grab `*-dbgsym_*.ddeb` package from local osc build attempts and produce better stack traces.

* try reproduce with a simpler setup. Mine is with multiple servers and large filesystem trees.

* Add patches. Almost all DEB/Ubuntu patches are currently disabled.

* More eyeballs.

**Comment by jnweiger** [comment]
FYI: @michaelstingl

Can you reporduces something like this, @SamuAlfageme

**Comment by SamuAlfageme** [comment]
@jnweiger so far, tests with the command line client did successful syncs without crashing: e.g.:https://gitlab.com/alfageme/client-linux-tests/builds/11896354/artifacts/file/test_Ubuntu_14.04.txt

Let's see what happens with the ol' GUI. Thanks for pointing this out!

**Comment by ogoffart** [comment]
What version is that? 2.3.0?
This should have normaly be fixed with commit 9c83c57f1cc0a69a85b54080315593843334df92

**Comment by ogoffart** [comment]
Also the log would be usefull.

**Comment by ogoffart** [comment]
But if it is 2.3.0, I assume that's the crash that we fixed in the 2.3 branch, and it is not related to Qt 5.6 at all.

**Comment by dschmidt** [comment]
@ogoffart it's some snapshot from the 2.3 branch, older than the commit you referenced. We will update to 2.3.0 release.

**Comment by ogoffart** [comment]
2.3.0 old don't have the fix either.
Just take a snapshot from the 2.3 branch.

**Comment by ogoffart** [comment]
Anyway, that crash was fixed in commit 9c83c57

**Comment by dschmidt** [comment]
Hehe.. apparently did not send my edit "to 2.3 branch". Yes, already uploaded :)

**Comment by jnweiger** [comment]
thanks @ogoffart I was so much afraid this is 5.6.2 related. Good to know it is not.

**Comment by jnweiger** [comment]
For completeness: That is what it looks with debug symbols:
<pre>
#0  0x00007ffff745cb22 in OCC::PropagateDirectory::scheduleNextJob (this=0x2d8c570)
    at /usr/src/packages/BUILD/src/libsync/owncloudpropagator.cpp:630
#1  0x00007ffff745ca73 in possiblyRunNextJob (next=0x2d8c570, this=0x306e3d0) at /usr/src/packages/BUILD/src/libsync/owncloudpropagator.h:235
#2  OCC::PropagateDirectory::scheduleNextJob (this=0x306e3d0) at /usr/src/packages/BUILD/src/libsync/owncloudpropagator.cpp:638
#3  0x00007ffff745ca73 in possiblyRunNextJob (next=0x306e3d0, this=0x3176950) at /usr/src/packages/BUILD/src/libsync/owncloudpropagator.h:235
#4  OCC::PropagateDirectory::scheduleNextJob (this=0x3176950) at /usr/src/packages/BUILD/src/libsync/owncloudpropagator.cpp:638
#5  0x00007ffff745b7b5 in OCC::OwncloudPropagator::scheduleNextJob (this=0x326d5a0)
    at /usr/src/packages/BUILD/src/libsync/owncloudpropagator.cpp:529
#6  0x00007ffff49345f6 in QObject::event (this=0x326d5a0, e=<optimized out>) at kernel/qobject.cpp:1256
#7  0x00007ffff78b7c1c in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x326d5a0, e=0x32a6260)
    at kernel/qapplication.cpp:3804
#8  0x00007ffff78bc29a in QApplication::notify (this=0x7fffffffdcc0, receiver=0x326d5a0, e=0x32a6260) at kernel/qapplication.cpp:3561
#9  0x00007ffff4908925 in QCoreApplication::notifyInternal2 (receiver=0x326d5a0, event=event@entry=0x32a6260)
    at kernel/qcoreapplication.cpp:1015
#10 0x00007ffff490a76a in sendEvent (event=0x32a6260, receiver=<optimized out>)
    at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:225
#11 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x821d80)
    at kernel/qcoreapplication.cpp:1650
#12 0x00007ffff490ad18 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0)
    at kernel/qcoreapplication.cpp:1508
#13 0x00007ffff495abc3 in postEventSourceDispatch (s=0x852db0) at kernel/qeventdispatcher_glib.cpp:270
#14 0x00007ffff311ee04 in g_main_context_dispatch () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#15 0x00007ffff311f048 in ?? () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
#16 0x00007ffff311f0ec in g_main_context_iteration () from /lib/x86_64-linux-gnu/libglib-2.0.so.0
</pre>

**Comment by guruz** [comment]
@jnweiger Can you confirm this is fixed when using a 2.3. branch from git?

**Comment by e-alfred** [comment]
Any idea when this fix will make it into a bugfix release?

**Comment by guruz** [comment]
@e-alfred next 48h hopefully
