### ISSUE TITLE
Cannot exclude individual files from top level (All Files)

### ISSUE THREAD

**Issue by felibb** [owncloud/client#5611]
### Expected behaviour
The desktop client allows to exclude subfolders residing in All Files from sync. I expected there be a way to exclude individual files residing in the top level of All Files in the same way.

### Actual behaviour
There is no obvious way to exclude individual files from sync.

### Client configuration
Client version: 2.3.0

Operating system: OS X

I don't really understand the ignore list. Can there be a way to simply uncheck the checkbox, similar to excluding folders? The issue stems from users who do not organise their All Files top folder into subfolders. Some individual files are also shared with users. This leads to a messy All Files folder. When a user needs to sync a single folder/file, it becomes impossible without syncing files that do not reside in subfolders.

**Comment by SamuAlfageme** [comment]
@felibb Yup, this has been reported quite a few times already and IMO needs to be fixed. You can +1 on https://github.com/owncloud/client/issues/3664 and refer to https://github.com/owncloud/client/issues/3664#issuecomment-133367256 for the workaround to avoid this behavior. 

Closing here as duplicate. Thanks for reporting!

**Comment by felibb** [comment]
@SamuAlfageme thx, I didn't find that one myself.
