### ISSUE TITLE
wrong owncloud icon with openSUSE-leap 42.2

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#5612]
The owncloud client as installed from https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

openSUSE Leap 42.2 shows this icon 
![leap42-2-wrong-owncloud-icon](https://cloud.githubusercontent.com/assets/1108546/23909224/7aebc0ac-08d6-11e7-8dce-3106d83b2e73.png)

I've reviewed the sources and binaries on obs, and could not find any svg or png file that looks similar to this icon. Instead, I expected something like this:

![owncloud-icon2](https://cloud.githubusercontent.com/assets/1108546/23909738/dd848a40-08d7-11e7-8122-ce3cbf5b67ae.png)

@guruz @dragotin any idea where this comes from?

**Comment by jnweiger** [comment]
The design looks similar to this: https://www.iconfinder.com/icons/1630212/rain_rainy_weather_icon

**Comment by dragotin** [comment]
The client reads the icon from the systems Icon theme, and Leap ships an icon named 
`/usr/share/icons/breeze/status/16/state-sync.svg` which is taken there I guess.

**Comment by jnweiger** [comment]
@dragotin what can we do to control which icons are used? Is there a re-mapping with leap?

**Comment by mrlinux1** [comment]
The paths for these icons seem to be:

/usr/share/icons/breeze/status/16/state-sync.svg
/usr/share/icons/breeze/status/22/state-sync.svg
/usr/share/icons/breeze-dark/status/16/state-sync.svg
/usr/share/icons/breeze-dark/status/22/state-sync.svg

state-sync is one of the used icons ;-) 
There are more like dropboxstatus-idle ...

**Comment by jnweiger** [comment]
workaround: 
<pre>
sudo mv /usr/share/icons/breeze{,.off}
owncloud
 Icon theme "breeze" not found.
</pre>
and then it looks normal again.... :-)

**Comment by dragotin** [comment]
The 'problem' is that in https://github.com/owncloud/client/blob/master/src/libsync/theme.cpp#L130 it is first checked if there is a system-theme-icon available before it uses the one that you ship. I tend to think that is cool and not a problem.

**Comment by jnweiger** [comment]
This might be cool from a clean suse design perspective.
It is confusing for the user all his cloud services use exactly the same icons.
It is frustrating from a branding perspective. The CI should not be touched.

**Comment by dragotin** [comment]
Yes, I understand. So a solution would be to execute the line 130 above only if the client is not branded. That way, the "normal" ownCloud client would pick up the distro specific icons and branded ones never. 

Alternatively, you can remove the line completely and always use your icon, as I actually doubt that openSUSE has included this icon purposely to brand the ownCloud client.

**Comment by ogoffart** [comment]
I think that's the expected behavior.  The icons are the one from the theme.  The KDE graphics team thought that this icon is nicer and fits better in the KDE environment. It's nice and it makes ownCloud looks better integrated with other applications on the platform.

**Comment by dragotin** [comment]
Just for the record - this is not fixed in 2.3.2rc1:
![ocicon](https://cloud.githubusercontent.com/assets/1070214/25531999/f22e0774-2c2b-11e7-8f53-80cddef5b50d.png)

**Comment by guruz** [comment]
> I think that's the expected behavior. 

vs

> this is not fixed in 2.3.2rc1:

Which one do we pick?

**Comment by dragotin** [comment]
That is actually consistent. The openSUSE icon is still used because that is the expected behaviour.
