### ISSUE TITLE
after upgrade to 2.2.4 no more connection

### ISSUE THREAD

**Issue by ferdiga** [owncloud/client#5615]
configuration changed - see
https://help.nextcloud.com/t/client-not-connecting-to-server/6732
after removing and recreating the account login was possible again

### Expected behaviour
connection established

### Actual behaviour
connection not established

### Steps to reproduce
1. upgrade to nextcloud 2.3
2. 
3. 

### Server configuration
Operating system:
debian 8
Web server: 
apache2
Database:
mariadb
PHP version:
php7
ownCloud version:
11.0.2
Storage backend (external storage):

### Client configuration
Client version:
2.2.4

Operating system:
ubuntu 16.04
OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by hodyroff** [comment]
Can't follow what the ownCloud Client bug/issue shall be in this context. Please debug your server side and if you have a true client easy please reproduce with ownCloud Client and ownCloud Server.

**Comment by ferdiga** [comment]
after following the advice in this link
https://help.nextcloud.com/t/client-not-connecting-to-server/6732
the connection worked again
