### ISSUE TITLE
Qt patches to apply

### ISSUE THREAD

**Issue by ogoffart** [owncloud/client#5618]
Candidate of patches we should consider applying in our builds (sorted by order of importance according to me)

[ ] https://codereview.qt-project.org/188629/  fix the most frequent unsolved crash in the crash reporter
[ ] https://codereview.qt-project.org/187378/ fix issue #5572 and #5530
[ ] https://codereview.qt-project.org/186861/ for issue #5557

**Comment by guruz** [comment]
Hm I'm not sure if we should do this if we want an early 2.3.1.

FYI @dschmidt for OBS-stuff for both mingw32 cross and Linux 5.6.1
FYI @jturcotte for OS X Qt
FYI @michaelstingl heads-up for ownBrander too

**Comment by guruz** [comment]
(possibly also the Windows 10 DPI fix https://github.com/owncloud/client/issues/5620#issuecomment-287026378 )

**Comment by michaelstingl** [comment]
Uff, I thought we no longer need patches with Qt 5.6.2+ :grimacing:

**Comment by guruz** [comment]
@michaelstingl Well, we don't need the old patches because they're merged. :-P

**Comment by ogoffart** [comment]
@guruz  the DPI fix is not ready to be integrated yet.

@michaelstingl theses are new patches which are not even in any released upstream Qt yet. They will only be in Qt 5.6.3 or Qt 5.9

**Comment by ogoffart** [comment]
The bugs they are fixing are also not super critical, and they can wait a couple of release if it's too complicated.

**Comment by guruz** [comment]
HTTP2: This would be if we were using Qt 5.9 which we are not: https://github.com/owncloud/client/pull/5659

**Comment by ogoffart** [comment]
All the patches are in Qt 5.9
Ideally we should use Qt 5.9(.1) for 2.4

**Comment by guruz** [comment]
Nope, too dangerous.
2.5 please.

**Comment by guruz** [comment]
@mrow4a Can you make sure we have smashbox testing with HTTP2? :)

**Comment by ogoffart** [comment]
I still think it's worth to apply these patch, especially the one about the crash.

**Comment by guruz** [comment]
FYI @dschmidt for OBS-stuff for both mingw32 cross and Linux 5.6.1
FYI @jturcotte for OS X Qt
FYI @michaelstingl heads-up for ownBrander too

**Comment by hefee** [comment]
Can you please release such informations for packages, too, if you send the release notes? Than packagers can make sure, that they have the necessary Qt patches available, if they package occ for their distribution.

**Comment by guruz** [comment]
@hefee FYI packagers are using the system Qt usually.

**Comment by hefee** [comment]
@guruz yes, but a distribution may have a version of Qt that should may be fixed to give the user the best experience. Thats why it is a very usfull information for packages, what they should check.

**Comment by guruz** [comment]
@hefee The patches above are what @ogoffart thinks we should apply, the patches in https://github.com/owncloud/client/tree/v2.3.3/admin/qt/patches are what we actually apply. But this might or might not be current info.

**Comment by hefee** [comment]
@guruz: oh interessting, i stripped out the complete admin directory, so i never see that there is now important suff for linux packagers.

> But this might or might not be current info.

but why it is not updated?

**Comment by guruz** [comment]
> Ideally we should use Qt 5.9(.1) for 2.4

We will use Qt 5.10.1
