### ISSUE TITLE
Creating desktop client - OCUtil_x64.dll file not found

### ISSUE THREAD

**Issue by clouddav** [owncloud/client#5624]
I am trying to build desktop clients on Windows 10 machine through docker. When I run
docker build -t nextcloud-client-win32:2.3 client/admin/win/docker/
I don't get any error message.

but when when I run following command
docker run -v "$PWD:/home/user/" nextcloud-client-win32:2.3 /home/user/win/build.sh $(id -u)

I get (File: "/home/user/client\binary\shell_integration\windows\Release\x64\OCUtil_x64.dll" -> no files found) error in the log file and following on screen.

CPack: Create package
CPack Error: Problem running NSIS command: "/usr/bin/makensis" "/home/user/build-win32/_CPack_Packages/unused/NSIS/project.nsi"
Please check /home/user/build-win32/_CPack_Packages/unused/NSIS/NSISOutput.log for errors
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: Nextcloud
Makefile:138: recipe for target 'package' failed
make: *** [package] Error 1
Test project /home/user/build-win32
No tests were found!!!

Kindly guide me how to solve this problem.

Thanks

**Comment by SamuAlfageme** [comment]
Hey @clouddav! that's most likely a problem with the docker image (I don't really know where the def. of `nextcloud-client-win32` is) . Refer to https://central.owncloud.org/t/error-using-docker-to-build-the-windows-client/5107/5 for some detailed instructions on how to use [the updated version of the windows toolchain](https://hub.docker.com/r/guruz/docker-owncloud-client-win32/).

Closing here; if something comes up, let's continue the discussion in central! Best! 😉

**Comment by NguyenVanVuong** [comment]
how can fix this ?
