### ISSUE TITLE
Share dialog displays only partial link share url

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#5626]
Sharelink is cutted because the dialog is too small

### Expected behaviour
the dialog should be bigger in with

### Actual behaviour
dialog is too small

### Steps to reproduce
1. clik share with desktop-client

client version: Version 2.3.0rc1 (build 4)
Gebaut von der GIT-Revision 832599 auf Mar 6 2017, 09:59:04 verwendet Qt 5.6.2, OpenSSL 1.0.2h 3 May 2016

Operating system: Win7

OS language: German

screenshot:
![](https://i.imgur.com/GA4E1pC.png)

**Comment by hodyroff** [comment]
To do what? We show the link so you can click on it and open the view in the web for checking. For Mail we have a direct button and for clipboard as well ... so for what purpose do you want to see the full thing?

**Comment by MegaV0lt** [comment]
So why display it anyway?

Better display the buttuns under the link

Bonus: make the dialog larger

**Comment by hodyroff** [comment]
Reason for displaying today: You can click on it and it opens in the web browser for you = testing or if you want to share with yourself via federated ... Agree its not looking perfect. Proposals welcome.

**Comment by MegaV0lt** [comment]
First: The hole dialog looks "not nice" and not modern at all. Much wasted space. Input field is shorter than the box below.
Space  between elements too much.

Sugestion: 
Redesign it completely. 
Put buttons below Link on te right side
Make dialog wider
Add a dropdownfield for users and groups

**Comment by guruz** [comment]
I think it was designed by @jancborchardt

**Comment by guruz** [comment]
I know it will be better in 2.4.0 :)
