### ISSUE TITLE
Gui glitch. Somteímes dot and somtime not

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#5629]
on the settingstab of the client some lines have a dot and others not. please change it to be consistent

![](https://i.imgur.com/KQvfRlr.png)

**Comment by phil-davis** [comment]
Version 2.3.1rc1 (build 6812) in English does not have this problem. First run that version and check if the translation has been made more consistent. If not, then it seems it is an inconsistency in the way the translation team have translated it.

**Comment by guruz** [comment]
@MegaV0lt Can you contribute fix this on Transifex directly?

https://www.transifex.com/owncloud-org/owncloud/dashboard/
