### ISSUE TITLE
Feature request: Local network setting

### ISSUE THREAD

**Issue by Matttter** [owncloud/client#5630]
### Expected behaviour

It'd be nice (and convenient) to be able to choose a local network, just like you can do with Transdroid for example (Settings > Servers > [Your server] > Advanced settings > Local Network and Local IP or host). My server runs inside my home network and it is very annoying to have to either change the settings when I get home or to have to access my Nextcloud instance using mobile data. I hope this makes sense.

### Actual behaviour
Can't connect to Nextcloud instance if it's on local network.

### Steps to reproduce
1. go to local network
2. open app
3. doesn't work

### Client configuration
Client version: 2.2.4

Operating system: Ubuntu

Client package (From ownCloud or distro) (Linux only): Nextcloud

**Comment by guruz** [comment]
-> https://github.com/owncloud/client/issues/203
