### ISSUE TITLE
[Windows] [NSIS] Microsoft runtime overwritten when PostgreSQL for Windows is installed too

### ISSUE THREAD

**Issue by gsimpson64** [owncloud/client#5632]
Steps to reproduce
1. Install PostgreSQL 9.5 x86 version. Make sure that everything comes up like it is supposed to.
2. Install ownCloud client 2.3.0 (This installs the x64 version of a file called MSVCR120.DLL)
3. Stop and restart the PostgreSQL service. It will not start.

Expected behaviour
PostgreSQL should start and the MSVCR120.DLL file should not be overwritten.

Actual behaviour
File MSVCR120.DLL gets overwritten.

During the installation of ownCloud, the file vcredist_x64 (version 12.0.30501) gets run.

If I re-run the vcredist_x86 file (version 12.0.21005 that comes with the installation of PostgreSQL), everything including ownCloud runs fine.

Client configuration
Client version: 2.3.0.6780
Client operating system: Windows 7

This is what I do not understand and please correct me if I am wrong.
ownCloud is a 32bit application. Why is it installing a 64bit version of the vcredist file in the first place?

Thanks,
Greg

**Comment by dschmidt** [comment]
Are you using Windows 7 32bit or 64bit?

**Comment by gsimpson64** [comment]
I am using Windows 7 64bit. OwnCloud is a 32bit app, right?

**Comment by dschmidt** [comment]
Yes and no. AFAIK the Explorer integration is shipped in 32bit and 64bit and installs the runtime accordingly. I haven't looked deeply into this, but my gut feeling is that installing the 64bit runtime on 64bit windows should be pretty much correct. To me it sounds more like an issue in postgres. Where does postgres install the MSVCR120.DLL?

**Comment by dschmidt** [comment]
I still think we don't do something wrong here, but this should be fixed anyway by the upcoming MSI anyway.

**Comment by dschmidt** [comment]
We use MSI now and don't install the runtime files to system directories.
