### ISSUE TITLE
Server Activity log lines are not formatted nicely

### ISSUE THREAD

**Issue by phil-davis** [owncloud/client#5634]
### Expected behaviour
The Server Activity log should have messages "You created somefile.txt" and so on regularly down the "page".

### Actual behaviour
There are empty lines starting with just "You created"

### Steps to reproduce
1. Add some files to the client end
2. Let them sync up to the server
3. View the Server Activity log in the client

### Server configuration
Hosted server
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:
nextCloud 11.0.2
Storage backend (external storage):

### Client configuration
Client version:
ownCloud 2.3.1rc1 (build 6812)
Operating system:
Windows10
OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Copying the log to text gives stuff like this:
```
me@xyz.owncube.com,      Mon Mar 20 12:06:49 2017 GMT,/Books-Technical/Oreilly/Windows_PowerShell__2dot0_Best_Practices.mobi,                   You created Books-Technical/Oreilly/Windows_PowerShell__2dot0_Best_Practices.mobi,                                                       
me@xyz.owncube.com,      Mon Mar 20 12:05:53 2017 GMT,                              ,                                                                                        You created ,                                                       
me@xyz.owncube.com,      Mon Mar 20 12:04:50 2017 GMT,/Books-Technical/Oreilly/Training_Guide_Programming_in_HTML5_with_JavaScript_and_CSS3.mobi,You created Books-Technical/Oreilly/Training_Guide_Programming_in_HTML5_with_JavaScript_and_CSS3.mobi,                                                       
me@xyz.owncube.com,      Mon Mar 20 12:04:33 2017 GMT,                              ,                                                                                        You created ,                                                       
me@xyz.owncube.com,      Mon Mar 20 12:00:31 2017 GMT,/Books-Technical/Oreilly/Programming_JavaScript_Applications.mobi,                        You created Books-Technical/Oreilly/Programming_JavaScript_Applications.mobi,                                                       
me@xyz.owncube.com,      Mon Mar 20 11:59:39 2017 GMT,                              ,                                                                                        You created ,                                                       
me@xyz.owncube.com,      Mon Mar 20 11:59:03 2017 GMT,/Books-Technical/Oreilly/Learning_PHP_MySQL_JavaScript_CSS_and_HTML5_Third_Edition.mobi,You created Books-Technical/Oreilly/Learning_PHP_MySQL_JavaScript_CSS_and_HTML5_Third_Edition.mobi and Books-Technical/Oreilly/PHP_Web_Services.mobi,                                                       
me@xyz.owncube.com,      Mon Mar 20 11:58:52 2017 GMT,                              ,                                                                                        You created ,                                                       
me@xyz.owncube.com,      Mon Mar 20 11:57:39 2017 GMT,/Books-Technical/Oreilly/PHP_Cookbook_Third_Edition.mobi,                                 You created Books-Technical/Oreilly/PHP_Cookbook_Third_Edition.mobi,                                                       
me@xyz.owncube.com,      Mon Mar 20 11:54:05 2017 GMT,                              ,                                                                                        You created ,                                                       
me@xyz.owncube.com,      Mon Mar 20 11:53:50 2017 GMT,/Books-Technical/Oreilly/JavaScript_The_Definitive_Guide_Sixth_Edition.mobi,              You created Books-Technical/Oreilly/JavaScript_The_Definitive_Guide_Sixth_Edition.mobi,                                                       
me@xyz.owncube.com,      Mon Mar 20 11:52:55 2017 GMT,                              ,                                                                                        You created ,                                                       
me@xyz.owncube.com,      Mon Mar 20 11:51:05 2017 GMT,/Books-Technical/Oreilly/JavaScript_for_PHP_Developers.mobi,                              You created Books-Technical/Oreilly/JavaScript_for_PHP_Developers.mobi,                                                       
```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

![owncloudserveractivity](https://cloud.githubusercontent.com/assets/1535615/24099635/7a6089ee-0d98-11e7-97ab-13c8bd02ce83.png)

**Comment by guruz** [comment]
Can you reproduce this  with ownCloud server? Looks like a server issue.

**Comment by phil-davis** [comment]
I added an account to an ownCloud 9.1.3 server. Now I can't make the problem happen when making client-side add/change/delete of files to either server (ownCloud or nextCloud).
I saw so many of the odd-looking lines in the server activity log that I thought it must have been an easy thing that happened a lot, but not so.
I will let a bit of general activity happen and see if it reproduces in the next day.

**Comment by phil-davis** [comment]
ownCloud client Version 2.3.1 (build 6824) to NextCloud server 11.0.2 - I just got a few empty "You created" entries - see attached. Logging this here to document what is happening.
![youcreatedtonextcloud11](https://cloud.githubusercontent.com/assets/1535615/24283484/2014e784-108e-11e7-8c52-250f5e899a12.png)
Now to try and replicate against the ownCloud server.
