### ISSUE TITLE
[Feature Request] Enhance Desktop Notifications

### ISSUE THREAD

**Issue by stkjj** [owncloud/client#5635]
presently Desktop notifications on Mac/Win/Linux show activities of synced files/folders, with no further actions which can be taken. 

Enhancement could be to have an action button (configurable in Mac OS X) which takes one to the just updated file/folder in the Finder/Explorer to take a closer look what is new or changed.

**Comment by guruz** [comment]
@michaelstingl Is this a dup?

**Comment by michaelstingl** [comment]
more or less a duplicate of https://github.com/owncloud/client/issues/4410 - needs to be extended for other platforms…
