### ISSUE TITLE
Tray menu: Clarify "Up to date" item with time of last E-Tag check

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5644]
When I wake up my laptop while being on flaky WiFi I don't know to what exact time the "Up to date" confirms to.

**Comment by ckamm** [comment]
@guruz Sounds good. You suggest a message like "Up to date as of 2017-3-24 11:59"?

**Comment by guruz** [comment]
@ckamm No date as it should always be from today or currently syncing?

**Comment by guruz** [comment]
haha you edited while I typed :-P

**Comment by TheOneRing** [comment]
Probably https://github.com/owncloud/client/blob/master/src/gui/folder.h#L452 is a good source.
