### ISSUE TITLE
2.3 client corrupted account when maint mode turned on

### ISSUE THREAD

**Issue by brianbgness** [owncloud/client#5645]
### Expected behaviour
When turning on maintenance mode, the client should behave as version 2.2.

### Actual behavior
Preface:  all my users authenticate via LDAP.  Something has changed and this client immediately prompts for a user password when maintenance is turned on.  The client account then becomes corrupted and can no longer sign in after maintenance mode is turned off.  In the Admin portal the Logging app repeatedly lists 'login failed' warnings.

### Steps to reproduce
1. Turn on maintenance mode
2. Client 2.3 then creates a dialog box asking for password
3. Close this dialog by pressing the upper-right "X"
4. Maintenance mode then turned off
5. Account won't sign in on client.  Get a red message:
   No connection to Nextcloud at https://server.domain.com. Operation canceled
6. Remedy is to remove the account and re-add

### Server configuration
Operating system:  Centos 7

Web server:  Apache

Database:  MariaDB

PHP version:  7.0

ownCloud version:  NC 11.0.2

Storage backend (external storage):  local storage and external SMB/CIFS

### Client configuration
Client version:  2.3 RC

Operating system:  Windows 10

OS language:  English

Installation path of client:  C:\Program Files (x86)\Nextcloud

### Logs

1. Client logfile: 
03-22 09:58:58:901 10376 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
03-22 09:58:58:902 10376 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
03-22 09:58:58:905 10376 OCC::ConnectionValidator::systemProxyLookupDone: No system proxy set by OS
03-22 09:58:58:907 10376 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://server.domain.com" + "status.php" "OCC::ConnectionValidator"
03-22 09:58:59:265 10376 OCC::CheckServerJob::finished: status.php returns:  QMap(("edition", QVariant(QString, ""))("installed", QVariant(bool, true))("maintenance", QVariant(bool, false))("needsDbUpgrade", QVariant(bool, false))("productname", QVariant(QString, "Evergreen"))("version", QVariant(QString, "11.0.2.7"))("versionstring", QVariant(QString, "11.0.2")))   QNetworkReply::NetworkError(NoError)  Reply:  QNetworkReplyHttpImpl(0x6f60e18)
03-22 09:58:59:266 10376 OCC::ConnectionValidator::slotStatusFound: ** Application: ownCloud found:  QUrl("https://server.domain.com/status.php")  with version  "11.0.2" ( "11.0.2.7" )
03-22 09:58:59:266 10376 OCC::ConnectionValidator::checkAuthentication: # Check whether authenticated propfind works.
03-22 09:58:59:266 10376 OCC::AbstractNetworkJob::start: !!! OCC::PropfindJob created for "https://server.domain.com" + "/" "OCC::ConnectionValidator"
03-22 09:59:26:261 10376 OCC::AbstractNetworkJob::slotTimeout: virtual void OCC::AbstractNetworkJob::slotTimeout() OCC::PropfindJob(0x6f394d0) Timeout QUrl("https://server.domain.com/remote.php/webdav/")
03-22 09:59:26:262 10376 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(OperationCanceledError) "Operation canceled" QVariant(Invalid)
03-22 09:59:26:262 10376 OCC::PropfindJob::finished: PROPFIND request *not* successful, http result code is 0 ""
03-22 09:59:26:262 10376 unknown: QIODevice::read (QNetworkReplyHttpImpl): device not open
03-22 09:59:26:262 10376 OCC::AccountSettings::showConnectionLabel: "No connection to Nextcloud at <a href=\"https://server.domain.com\">https://server.domain.com</a>.\nOperation canceled"
03-22 09:59:26:264 10376 OCC::FolderMan::slotAccountStateChanged: Account "username@server.domain.com" disconnected or paused, terminating or descheduling sync folders
03-22 09:59:30:897 10376 OCC::Account::resetNetworkAccessManager: Resetting QNAM

2. Web server error log:  none

3. Server logfile: ownCloud log (data/owncloud.log):
[ip removed] - - [22/Mar/2017:09:59:11 -0700] "-" 408 -
[ip removed] - username [22/Mar/2017:09:59:16 -0700] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 408
[ip removed] - - [22/Mar/2017:09:59:20 -0700] "GET /ocs/v2.php/apps/notifications/api/v2/notifications HTTP/1.1" 200 74
[ip removed] - username [22/Mar/2017:09:58:59 -0700] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 409
[ip removed] - username [22/Mar/2017:09:59:31 -0700] "GET /status.php HTTP/1.1" 200 146
[ip removed] - - [22/Mar/2017:09:59:41 -0700] "-" 408 -
[ip removed] - username [22/Mar/2017:09:59:47 -0700] "PROPFIND /remote.php/webdav/ HTTP/1.1" 207 408

**Comment by hodyroff** [comment]
Please reproduce with 2.3.1 ownCloud Client and ownCloud Server. Sounds like an error code issue, likely server side.

**Comment by brianbgness** [comment]
Update:  I have not tried ownCloud server yet, but the new 2.3.1 Owncloud client has different behavior.  I can create an account, but after quitting the client it refuses to sign in again.  The same corruption but it occurs without maintenance mode.  Something very odd is happening.

**Comment by hodyroff** [comment]
You can also just try demo.owncloud.com as the server side ...

**Comment by ckamm** [comment]
This is very likely a server problem.

Maintenance mode: The client requires the server to reply 503 to a bunch of requests in maintenance mode. If you get logged out when you turn on maintenance mode then probably the server replies with an auth failure instead of a "service unavailable" in that state.

If the account becomes unusable even without that: Like @hodyroff suggested, test against a different server like demo.owncloud.com. If it doesn't reproduce, something is probably up with your server or setup.

**Comment by hodyroff** [comment]
CLosing for now, if there is a bug in the client please comment with additional information and we will reopen.
