### ISSUE TITLE
Sync icons missing on all Windows 10 computers

### ISSUE THREAD

**Issue by AsherJac** [owncloud/client#5648]
### Expected behaviour
On each file and folder inside the owncloud folder there should be a small icon overlay to show whether it is synced, syncing or in error.

### Actual behaviour
These icons are not there. It just shows the standard folder or file icon.

### Steps to reproduce
Owncloud sync client 2.3.0 installed on at least 3 different Win10 computers. None are showing the icons.
One Win7 computer is.
I have unistalled and reinstalled owncloud sync client with no improvement.
On one laptop I have reinstalled Windows10 and then reinstalled owncloud sync client. Icons overlays are still missing.

### Server configuration
Operating system: Through owncube.com (not sure)

Web server: 

Database:

PHP version:

ownCloud version: 9.0.8 

Storage backend (external storage): None.

### Client configuration
Client version: 2.3.0

Operating system: Windows 10

OS language: English (UK)

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

**Comment by hodyroff** [comment]
Did you reboot Windows after the install? Sometimes thats needed.

**Comment by guruz** [comment]
@AsherJac What's the result with 2.3.1? It was release last week.

**Comment by AsherJac** [comment]
@hodyroff Yes. I've rebooted many times. This has been an issue for a long time and I've tried several reinstalls.
@guruz I'll uninstall everything again now, install the new client and reboot.

**Comment by hodyroff** [comment]
Which other file sync and share software do you have installed? Sometimes icons conflict and there is a maximum which is allowed by MS Windows.

**Comment by AsherJac** [comment]
@hodyroff Ah. That's interesting. I have Dropbox and Google Drive installed as well, so it may be that I've hit the limit. I'll try uninstalling them and see what happens.

**Comment by x9t9** [comment]
I have the same problem, with an added symptom of not showing the "Share with next cloud" context menu entry ..  the problem appeared after upgrading the client ( and moving the local folder location ) .
Win 7 / Client Version 2.3.1 (build 8) /

**Comment by michaelstingl** [comment]
Here you can find the steps to debug this issue:
https://github.com/owncloud/client/wiki/Debugging-Overlay-Icons

**Comment by AsherJac** [comment]
Tried the debug steps and all was good, but icons still not showing. The issue for me does seem to be the one @hodyroff identified. Found a fix to that here: https://www.garethjmsaunders.co.uk/2015/03/22/managing-overlay-icons-for-dropbox-and-tortoisesvn-and-tortoisegit/

**Comment by hodyroff** [comment]
Thanks for providing the solution, we will add this to the documentation. Nice!
