### ISSUE TITLE
[Windows]: owncloud client is not started when updated is canceled

### ISSUE THREAD

**Issue by RubenGarcia2081** [owncloud/client#5651]
### Expected behaviour
when owncloud detects an update, the user will get a prompt, where he can initiate or cancel the update. If the user klicks "OK" and the user has no local administration permission assigned, the windows UAC dialog is displayed. If the user now decides to quit the UAC, for example because he don't has credentials of another user with local administration permission, UAC should close and owncloud client should start or continue running.

### Actual behaviour
when the user logs into a new windows session and owncloud starts and first detects an update (installed was 2.2.4, detected update was 2.3.0). the owncloud client is not started, but the user is promoted with a dialog. This dialog only gives him the option to press the OK-button. Now the user klicks OK, then he sees the UAC dialog and quits this dialog without entering valid credentials. The update is canceled and the ownCloud client is not started.

So I see two not user friendly behaviours here:
1. The update dialoge should give the user an aditional option than only OK. For example: "Not now", "No thanks"
2. When the update is canceled (eg. because UAC is closed by the user), ownCloud client should be started. This is important, because a normal end-user will not notice, that the ownCloud client isn't running. Some hours the end-user will find out, that his files are not synched anymore, but without any idea of the reason. He will treat owncloud as unreliable.

### Steps to reproduce
1. install owncloud client
2. login as a non privileged user
3. in the owncloud wizard enter server, login and pw
4. in the owncloud settings, configure it, to start owncloud automatically
5. wait till ownCloud notices an update (update dialog will only be displayed when ownCloud client is started)
6. quit the UAC dialog without entering credentials
7. result: no owncloud client is started

### Client configuration
Client version: 2.2.4/2.3.0
Operating system: Windows 10 1604
OS language: German
Installation path of client: default

Would be great, if the behvior could the adjusted.

Thanks

**Comment by TheOneRing** [comment]
Unsupported scenario, the user will need to start the client manually.
