### ISSUE TITLE
[OC 10.0][OS X] libsync is able to download files with 4 byte-unicode names but upload etc

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5661]
4 byte-unicode (a.k.a. emoji) filenames are supported in ownCloud 10.0 (https://github.com/owncloud/core/issues/4513)

### Expected behavior
The client should be able to handle this filenames as long as the underlying filesystem supports them as well. 

### Actual behavior
- [x] Sync a file/folder with an emoji filename **from the server into the desktop client** (`v2.3.1`)
- [x] Upload a file/folder to the server with a 4byte-unicode name prompts [this error](https://github.com/owncloud/client/blob/master/src/libsync/syncengine.cpp#L678-L681)
- [x] Delete/rename the file/folder on the server, the client doesn't keep up with these changes

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/24409389/5a760080-13d0-11e7-8bc7-e724df86305a.gif"/>
</p>

Solving this will be enough to close some old issues: 
- https://github.com/owncloud/client/issues/4811
- https://github.com/owncloud/client/issues/5231

**Comment by guruz** [comment]
Note that this might be macOS specific because we have to do file name mangling on macOS https://github.com/owncloud/client/search?utf8=%E2%9C%93&q=normalization&type=  . 

How does it look on other OS?

@mstingl this would mandate an earlier 2.3.2

**Comment by SamuAlfageme** [comment]
@guruz you're right, I assumed the name-conversion error was platform-independent but just tried with Win10 and no flags were raised there. My bad 😅

**Comment by michaelstingl** [comment]
> @michaelstingl this would mandate an earlier 2.3.2

Works for me

**Comment by ogoffart** [comment]
I bet that's because iconv can't convert the string (cf. https://github.com/owncloud/client/issues/2777 )

**Comment by guruz** [comment]
@ogoffart Any proposal for your Qt code?
Alternatively 2: Instead of using POSIX/csync _treaddir we could use something from Qt for reading directories.

**Comment by guruz** [comment]
maybe https://doc.qt.io/qt-5/qfile.html#decodeName-1 ..

**Comment by guruz** [comment]
This is messy. I'm trying a few things but I think this is too invasive for a patch release.

**Comment by guruz** [comment]
@michaelstingl @pmaier1 Moving to 2.4, the needed patch is too invasive

**Comment by SamuAlfageme** [comment]
👍
