### ISSUE TITLE
wrong trusted domains setting causes unhelpful error message

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#5667]
Enhancement suggestion (GSoc?)

When the server has its trusted_domains settings in config.php wrong, the web page gives helpful instructions that the correct trusted domains setting should be added.

But the desktop client ends up with 'Bad Request' error like this:
![client-error-when-trusted-domains](https://cloud.githubusercontent.com/assets/1108546/24504988/9abd6be0-1558-11e7-956f-62a33bf552f3.png)

I'd suggest to add a hint 'Please check with a web browser, if the server sends a human readable error message'

In this case, the web page perfectly explains the situation:
![web-err-trusted-domains](https://cloud.githubusercontent.com/assets/1108546/24505239/763c452e-1559-11e7-9576-9878fef9bb99.png)

**Comment by SamuAlfageme** [comment]
@jnweiger Hm, maybe it has something to do with your config... I see you have a warning on the SSL section of the browser, did the cert pop-up appear in the client?

When I try to log in using one of the alias set in my `/etc/hosts` without setting it as trusted domain, I get this: 

![screenshot 2017-04-03 11 28 20](https://cloud.githubusercontent.com/assets/2644445/24603350/b272782e-1860-11e7-9254-a269002610b4.png)

**Comment by guruz** [comment]
I did this in 2.3.0, please re-test @jnweiger

**Comment by jnweiger** [comment]
@SamuAlfageme your screenshot show, that all is well. That is the helpful info I was looking for.
I am worried that I did not see that one when testing.
