### ISSUE TITLE
Windows: Silent Deployment options

### ISSUE THREAD

**Issue by eroueen** [owncloud/client#567]
The following options for silent installation on Windows exist:

for installing:
owncloud-1.2.5-setup.exe /S

uninstall string:
"C:\Program Files (x86)\ownCloud\Uninstall.exe" /S

I would appreciate a few more options:
(1) define the location of the client sync folder; e.g.
    owncloud-1.2.5-setup.exe /S /LocalSyncFolder=F:\owncloud

(2) define the URL of the owncloud server; e.g.
    owncloud-1.2.5-setup.exe /S /DestinationURL=https://x.y.z/path

(3) define a username; e.g.
    owncloud-1.2.5-setup.exe /S /User=John

Thank you 
-eroueen

**Comment by ktWaran** [comment]
Hi @danimo, 
I would like to add another installer package within the owncloudsetup file in NSIS,template.in. I have managed to copy the file in the installation directory. I tried exec the my.exe file, It was not successful. 

Any suggestions please. 

Thanks
Kt
