### ISSUE TITLE
Logging: Make it easier to know which account in involved in parts of the log

### ISSUE THREAD

**Issue by jturcotte** [owncloud/client#5672]
Related to #5671.

**Comment by guruz** [comment]
👍 Finally

**Comment by jturcotte** [comment]
Only added it on the sync start and stop line.

@cdamken @michaelstingl Do you think this will help and be enough, or are there other parts of the log beside syncs that multiple accounts make the log confusing.

**Comment by michaelstingl** [comment]
Will help a lot! I will test-drive with the nightly…

**Comment by ckamm** [comment]
The logs appear as expected. @michaelstingl let us know if any additional logging would be helpful.
