### ISSUE TITLE
Logging: Add a checkbox in the log window to also capture *.debug categorized logs

### ISSUE THREAD

**Issue by jturcotte** [owncloud/client#5673]
After #5671, some of the less user-friendly logs we had previously will be hidden by default to keep the log concise, but in some cases those logs could be useful to investigate tough issues.

There could also be a free editbox that calls `QLoggingCategory::setFilterRules`, and the checkbox could just mean filling it with `*=true`.

**Comment by guruz** [comment]
I wonder if we should get rid of that window completely as using something like Notepad+ which re-loads files as they grow is much more user friendly for big syncs.

@michaelstingl @cdamken  opinions?

**Comment by michaelstingl** [comment]
I'm a big fan of the startup parameters and never need the log window. @cdamken ?

**Comment by jturcotte** [comment]
Fixed by cf058bc537ff926f2c0c03be40fcff978d570c70
