### ISSUE TITLE
too many connections on reconnect after a short networkoutage 

### ISSUE THREAD

**Issue by MakeTeaNotLove** [owncloud/client#5674]
Hi!

I'm running nextcloud-client (2.2.4-4) on Arch Linux (4.10.2-1-zen) and i have noticed the following problem: 

Everytime my laptop switches network or the client cant connect to my nextcloud server for other reasons (local timeout on network), the client quickly retries the connection resulting in hundreds of open sockets in the TIME_WAIT state, so if the network comes back online quickly after it went down, my server is bombarded with connections.  

My firewall on the serverside then blocks my ip for overuse of resources.  

Ignoring the fact that it is my firewall and not the client that is causing my server to become unavailable, maybe it is not such a bad idea to make libsync less aggressive qua retrying connections? 

If this is completely stupid, please ignore this thread. 

Bye!

**Comment by hodyroff** [comment]
Please reproduce with ownCloud Client and ownCloud Server.

**Comment by MakeTeaNotLove** [comment]
I'm terribly sorry. This problem was not due to the Nextcloud/Owncloud desktopclient but due to a mobile application (either Davdroid or Notes). I thought I had weeded out the mobile app as the culprit but I appear to be mistaken.
