### ISSUE TITLE
[Feature] Filename encoding with gbk standard should be supported

### ISSUE THREAD

**Issue by ericlin1001** [owncloud/client#5676]
### Steps to reproduce
1. In linux, use owncloud client(owncloud version 2.3.0 Using Qt 4.8.6)
2. In the owncloud syncing directory.
  1. `touch 乱码.txt`
  2. `convmv -f utf-8 -t gbk 乱码.txt`
  3. owncloud complained: *???.txt  could not be synced due to errors. *
3. In log, I found: *File ignored because of invalid utf-8 sequence: ???.txt*

### Expected behaviour
Tell us what should happen
The file with name encoding in gbk, should be synced. Because I'm converting file name encoding of a large amount of files in linux, and these files are to be used in windows(win7).

### Actual behaviour
Tell us what happens instead
1. owncloud complained: *???.txt  could not be synced due to errors. *
2. In log, I found: *File ignored because of invalid utf-8 sequence: ???.txt*

### Server configuration
**Operating system**:
LSB Version:	core-2.0-amd64:core-2.0-noarch:core-3.0-amd64:core-3.0-noarch:core-3.1-amd64:core-3.1-noarch:core-3.2-amd64:core-3.2-noarch:core-4.0-amd64:core-4.0-noarch:core-4.1-amd64:core-4.1-noarch:security-4.0-amd64:security-4.0-noarch:security-4.1-amd64:security-4.1-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

**Web server:**

**Database:**

**PHP version:**

**ownCloud version:** (see ownCloud admin page)

**Updated from an older ownCloud or fresh install:**

**Where did you install ownCloud from:**

**Signing status (ownCloud 9.0 and above):**

```
Login as admin user into your ownCloud and access 
http://example.com/index.php/settings/integrity/failed 
paste the results here.
```

**List of activated apps:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ app:list
from within your ownCloud installation folder
```

**The content of config/config.php:**

```
If you have access to your command line run e.g.:
sudo -u www-data php occ config:list system
from within your ownCloud installation folder

or 

Insert your config.php content here
(Without the database password, passwordsalt and secret)
```

**Are you using external storage, if yes which one:** local/smb/sftp/...

**Are you using encryption:** yes/no

**Are you using an external user-backend, if yes which one:** LDAP/ActiveDirectory/Webdav/...

#### LDAP configuration (delete this part if not used)

```
With access to your command line run e.g.:
sudo -u www-data php occ ldap:show-config
from within your ownCloud installation folder

Without access to your command line download the data/owncloud.db to your local
computer or access your SQL server remotely and run the select query:
SELECT * FROM `oc_appconfig` WHERE `appid` = 'user_ldap';


Eventually replace sensitive data as the name/IP-address of your LDAP server or groups.
```

### Client configuration
**Browser:**

**Operating system:**

#### Web server error log
```
Insert your webserver log here
```

#### ownCloud log (data/owncloud.log)
```
Insert your ownCloud log here
```

#### Browser log
```
Insert your browser log here, this could for example include:

a) The javascript console log
b) The network log 
c) ...
```

**Comment by hodyroff** [comment]
We are currently preparing 2.3.1 packages with QT5.6 as new Linux packages, those will be worth a try first and then we might be able to look into this.

**Comment by guruz** [comment]
https://dict.leo.org/chinesisch-deutsch/%E4%B9%B1%E7%A0%81 :-))))))

**Comment by hodyroff** [comment]
Packages with QT 5.6: https://software.opensuse.org//download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client

**Comment by guruz** [comment]
I heard from the other engineers that we only support UTF-8 on the client side, sorry.

**Comment by ericlin1001** [comment]
Ok, that's fine. Though I'm still hoping it'll support all file name encoding. Because with it, life will be more easy.

**Comment by hodyroff** [comment]
Lets keep it as a feature request, but if not heavily requested from Chinese users this will not be implemented. If you could add some reasoning in regards of the use case and benefits rather then using UTF-8 only this would also be appreicated.

**Comment by guruz** [comment]
My wife (who is Chinese) says:
```
it is the most used codec in mainland china
big5 is the one for taiwan.
```

**Comment by ericlin1001** [comment]
Yes, in China, most of Chinese computer users use GBK encoding in Windows, even Linux.

**Comment by guruz** [comment]
@ericlin1001 Do you want to try this using a 2.4 nightly build?
We have a testpilot package available https://download.owncloud.com/desktop/daily/testpilotcloud-client-2.4.0.8373nightly20170911.linux-repo.html

**Comment by guruz** [comment]
https://central.owncloud.org/t/desktop-client-2-4-0-alpha1-released/9837

@ericlin1001 Alpha1 released. Could you check?

**Comment by guruz** [comment]
@ericlin1001  ping

**Comment by ckamm** [comment]
@guruz @ogoffart I've tested with the example from the first post and it still doesn't work. The client attempts to convert the gbk characters to utf8 and fails, showing a "Filename encoding is not valid" error. That's done in `SyncEngine::treewalkFile`. I don't think the client is prepared to deal with non-utf8 filenames?

**Comment by guruz** [comment]
Moved to 2.5

**Comment by ogoffart** [comment]
@ckamm,  but what's your file system encoding, and the environment variable that specify the encoding (LC_ALL/LC_CTYPE/LANG)?
QString::fromLocal8Bit should do the right thing.
If the filename is invalid on the file system, then there is nothing that can be done.

**Comment by ckamm** [comment]
@ogoffart I agree, it's just that none of the env variables I tried had an effect on the system locale. So what I report is a failure of testing and not indicative of a bug on its own.

**Comment by ogoffart** [comment]
I tested:
```
unset LC_ALL
unset LC_CTYPE
export LANG=en_US
```
(en_US is specified in my /etc/locale.gen  as en_US ISO-8859-1)
I verified that the codecForLocale is indeed latin1.
Filename that can be encoded as latin1 works as expected.

However the bug i noticed is that if the server contains filename that cannot be encoded in the user's locale, Qt uses replacement character instead ('?').  And next sync rename the file with the replacement character.

**Comment by guruz** [comment]
2.5.0 beta1 is out :-)
https://central.owncloud.org/t/desktop-sync-client-2-5-0-beta1-released/14667
Everyone, please comment here if we can close this issue. Thank you.

**Comment by jnweiger** [comment]
### Mint Tara (aka Ubuntu 18.04)

testpilotcloud version 2.5.0daily20180801 (build 9974)

touch 乱码.txt
... syncs fine.
convmv -f utf-8 -t gbk 乱码.txt --notest
... but then we still get a sync error as reported by the OP:
![grafik](https://user-images.githubusercontent.com/1108546/43685304-b45f67d8-98b0-11e8-8ca4-b6e70729d304.png)

This feature does not seem to be ready for 2.5.0 release.

@ckamm I understand the expected outcome should be: file ignored.
Maybe https://github.com/owncloud/client/commit/7d70f1becb646040e2428c12bca9ec28596a50f8 only sets the ignore flag when down-syncing? This was asked for upwards (too).

My personal opinion (aka server enhancement idea): filenames should be opaque byte streams for us. Whatever bytes a user  puts into owncloud, should store that and bring it back unchanged. Interpreting encoding of a filename is a problem of the representation layer, not of the transport layer.

**Comment by ogoffart** [comment]
@jnweiger that's because your locale is still UTF-8. So it is expected that when a filename is not in UTF-8, we show one error for this file. (but we still continue to sync the other files)

> My personal opinion (aka server enhancement idea): filenames should be opaque byte streams for us. Whatever bytes a user puts into owncloud, should store that and bring it back unchanged. Interpreting encoding of a filename is a problem of the representation layer, not of the transport layer.

That's not really possible as you need to display the filename in the web interface from HTML whose encoding is UTF-8.  And since you need to sync, you need to compare the filename for equality.  So we need to understand what it is. And we can't sync invalid filename.

**Comment by jnweiger** [comment]
Client observing the local locale is actually cool! So correct behaviour there!
Some more tests:
### Mint Tara (aka Ubuntu 18.04)
locale LC_ALL=de_DE.UTF-8

LC_CTYPE= LANG=C LC_ALL=C LANGUAGE=C testpilotcloud &

touch xxx.txt; sleep 10 # sufficient sleep so that it syncs
mv xxx.txt x乱码.txt
OK
 - syncs up fine.

Client Error log:
 - 6 Aug 2018 16:51:25, Documents/issue5676/x������.txt, testpilotcloud3,   The filename cannot be encoded on your file system.

BUT: the file gets renamed on the server.
 - local changes are no longer synced up.
 - changes on the server are no longer synced down.

OK:
  Files that 'cannot be encoded on your file system' according to the locale of the owncloud-client (LC_ALL=C) in this case are rejected with the correct error message.

BUT:
  - touch 乱码.txt
    Different error message: 'File Removed'. But the file was not removed.

**Comment by jnweiger** [comment]
@ogoffart Regarding byte-streams.
I believe both your points are invalid/can be worked around. Let's move that discussion to the server space: https://github.com/owncloud/core/issues/32251

**Comment by jnweiger** [comment]
The behaviour seen in https://github.com/owncloud/client/issues/5676#issuecomment-410742959 is as expected. Closing.
