### ISSUE TITLE
No U2F support for desktop client

### ISSUE THREAD

**Issue by AquaL1te** [owncloud/client#5680]
### Actual behaviour
I enabled U2F (Yubikey Neo) on my Nextcloud for my user account. Now I can't use the desktop client anymore, only with the Chrome browser.

### Expected behaviour
An option to scan my Yubikey Neo to gain access.
 
### Steps to reproduce
1. Enable U2F addon in Nextcloud
2. In the Personal account menu, enable the U2F option
3. Touch the Yubikey
4. Try to log in with the Nextcloud desktop client

### Environment data
Desktop OS: Fedora 25

Nextcloud client version: nextcloud-client.x86_64 2.2.4-8.fc25

Nextcloud server version: 11.0.2

**Comment by guruz** [comment]
Sorry, this is not supported with ownCloud at the moment.
