### ISSUE TITLE
[Linux] [NFS?] client not starting: setNativeLocks failed: Resource temporarily unavailable

### ISSUE THREAD

**Issue by dnacombo** [owncloud/client#5683]
### Expected behaviour
Owncloud should start at login.

### Actual behaviour
A window filled with black opens and the program freezes at startup. Killing it then starting it again either from menu or terminal brings a black square in the panel (Mint cinnamon). Totally unresponsive. Only way to interact is by killing owncloud process.

### Steps to reproduce
1. login to cinnamon with start at login option enabled.
2. black window comes up
3. kill
4. start either from menu or terminal
5. black square icon in panel area.

### Server configuration
ownCloud version: 9.1

### Client configuration
Client version: 2.3.1~rc1-2.1

Operating system: Mint Sarah running Cinnamon

OS language: Eng

Qt version used by client package (Linux only, see also Settings dialog): info unavailable.

### Logs

04-04 17:32:11:739 44177 OCC::Application::setupLogging: "################## ownCloud en_US () 2.3.1rc1 (build 2295) on Linux Mint 18"
04-04 17:32:11:739 44177 OCC::Application::setupTranslations: void OCC::Application::setupTranslations() Using "en_US" translation
04-04 17:32:11:739 44177 OCC::Application::Application: Loading global exclude list
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: *~
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: ~$*
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: .~lock.*
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: ~*.tmp
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: ]*.~*
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: ]Icon
*
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: ].DS_Store
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: ].ds_store
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: ._*
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: ]Thumbs.db
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: desktop.ini
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: System Volume Information
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: .*.sw?
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: .*.*sw?
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: ].TemporaryItems
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: ].Trashes
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: ].DocumentRevisions-V100
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: ].Trash-*
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: .fseventd
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: .apdisk
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: .htaccess
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: .directory
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: *.part
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: *.filepart
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: *.crdownload
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: *.kate-swp
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: *.gnucash.tmp-*
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: .synkron.*
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: .sync.ffs_db
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: .symform
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: .symform-store
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: .fuse_hidden*
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: *.unison
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: .nfs*
04-04 17:32:11:741 0xae0cb0 csync_exclude_load: Adding entry: My Saved Places.
04-04 17:32:11:741 44177 OCC::SocketApi::SocketApi: SocketApi:  server started, listening at  "/run/user/2068/ownCloud/socket"
04-04 17:32:11:741 44177 OCC::FolderMan::FolderMan: setting remote poll timer interval to 30000 msec
04-04 17:32:11:773 44177 OCC::AccountManager::loadAccountHelper: Account for QUrl("https://owncloud.icm-institute.org") using auth type "http"
04-04 17:32:11:773 44177 OCC::AccountManager::loadAccountHelper: Account for QUrl("https://mycore.core-cloud.net") using auth type "http"
04-04 17:32:11:773 44177 OCC::AccountManager::loadAccountHelper: Account for QUrl("https://somaxluan.hd.free.fr/owncloud") using auth type "http"
04-04 17:32:11:774 44177 OCC::FolderMan::setupFolders: * Setup folders from settings file
04-04 17:32:11:774 44177 OCC::Folder::checkLocalPath: Checked local path ok
04-04 17:32:11:774 44177 OCC::Folder::setIgnoredFiles: ==== adding system ignore list to csync: "/etc/ownCloud/sync-exclude.lst"
04-04 17:32:11:774 44177 OCC::Folder::setIgnoredFiles: ==== adding user defined ignore list to csync: "/lena13/home_users/users/chaumon/.local/share/data/ownCloud/sync-exclude.lst"
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: *~
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: ~$*
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: .~lock.*
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: ~*.tmp
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: ]*.~*
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: ]Icon
*
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: ].DS_Store
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: ].ds_store
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: ._*
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: ]Thumbs.db
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: desktop.ini
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: System Volume Information
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: .*.sw?
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: .*.*sw?
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: ].TemporaryItems
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: ].Trashes
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: ].DocumentRevisions-V100
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: ].Trash-*
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: .fseventd
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: .apdisk
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: .htaccess
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: .directory
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: *.part
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: *.filepart
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: *.crdownload
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: *.kate-swp
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: *.gnucash.tmp-*
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: .synkron.*
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: .sync.ffs_db
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: .symform
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: .symform-store
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: .fuse_hidden*
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: *.unison
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: .nfs*
04-04 17:32:11:775 0xae0cb0 csync_exclude_load: Adding entry: My Saved Places.
04-04 17:32:11:775 44177 OCC::FolderMan::addFolderInternal: Adding folder to Folder Map  OCC::Folder(0xe032d0) "1"
04-04 17:32:11:775 44177 OCC::FolderWatcherPrivate::slotAddFolderRecursive: (+) Watcher: "/home/owncloud/"
04-04 17:32:12:500 44177 OCC::FolderWatcherPrivate::slotAddFolderRecursive:     `-> and 6979 subdirectories
04-04 17:32:12:500 44177 OCC::FolderMan::scheduleFolder: Schedule folder  "1"  to sync!
04-04 17:32:12:500 44177 OCC::FolderMan::scheduleFolder: Folder is not ready to sync, not scheduled!
04-04 17:32:12:500 44177 OCC::Folder::checkLocalPath: Checked local path ok
04-04 17:32:12:500 44177 OCC::Folder::setIgnoredFiles: ==== adding system ignore list to csync: "/etc/ownCloud/sync-exclude.lst"
04-04 17:32:12:500 44177 OCC::Folder::setIgnoredFiles: ==== adding user defined ignore list to csync: "/lena13/home_users/users/chaumon/.local/share/data/ownCloud/sync-exclude.lst"
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: *~
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: ~$*
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: .~lock.*
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: ~*.tmp
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: ]*.~*
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: ]Icon
*
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: ].DS_Store
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: ].ds_store
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: ._*
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: ]Thumbs.db
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: desktop.ini
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: System Volume Information
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: .*.sw?
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: .*.*sw?
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: ].TemporaryItems
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: ].Trashes
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: ].DocumentRevisions-V100
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: ].Trash-*
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: .fseventd
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: .apdisk
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: .htaccess
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: .directory
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: *.part
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: *.filepart
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: *.crdownload
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: *.kate-swp
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: *.gnucash.tmp-*
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: .synkron.*
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: .sync.ffs_db
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: .symform
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: .symform-store
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: .fuse_hidden*
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: *.unison
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: .nfs*
04-04 17:32:12:501 0xae0cb0 csync_exclude_load: Adding entry: My Saved Places.
04-04 17:32:12:501 44177 OCC::FolderMan::addFolderInternal: Adding folder to Folder Map  OCC::Folder(0xebe690) "2"
04-04 17:32:12:501 44177 OCC::FolderWatcherPrivate::slotAddFolderRecursive: (+) Watcher: "/home/ownCNRS/"
04-04 17:32:12:501 44177 OCC::FolderWatcherPrivate::slotAddFolderRecursive:     `-> and 1 subdirectories
04-04 17:32:12:501 44177 OCC::FolderMan::scheduleFolder: Schedule folder  "2"  to sync!
04-04 17:32:12:501 44177 OCC::FolderMan::scheduleFolder: Folder is not ready to sync, not scheduled!
04-04 17:32:12:501 44177 OCC::Folder::checkLocalPath: Checked local path ok
04-04 17:32:12:501 44177 OCC::Folder::setIgnoredFiles: ==== adding system ignore list to csync: "/etc/ownCloud/sync-exclude.lst"
04-04 17:32:12:501 44177 OCC::Folder::setIgnoredFiles: ==== adding user defined ignore list to csync: "/lena13/home_users/users/chaumon/.local/share/data/ownCloud/sync-exclude.lst"
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: *~
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: ~$*
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: .~lock.*
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: ~*.tmp
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: ]*.~*
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: ]Icon
*
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: ].DS_Store
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: ].ds_store
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: ._*
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: ]Thumbs.db
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: desktop.ini
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: System Volume Information
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: .*.sw?
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: .*.*sw?
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: ].TemporaryItems
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: ].Trashes
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: ].DocumentRevisions-V100
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: ].Trash-*
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: .fseventd
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: .apdisk
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: .htaccess
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: .directory
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: *.part
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: *.filepart
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: *.crdownload
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: *.kate-swp
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: *.gnucash.tmp-*
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: .synkron.*
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: .sync.ffs_db
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: .symform
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: .symform-store
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: .fuse_hidden*
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: *.unison
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: .nfs*
04-04 17:32:12:502 0xae0cb0 csync_exclude_load: Adding entry: My Saved Places.
04-04 17:32:12:502 44177 OCC::FolderMan::addFolderInternal: Adding folder to Folder Map  OCC::Folder(0xec1b20) "3"
04-04 17:32:12:502 44177 OCC::FolderWatcherPrivate::slotAddFolderRecursive: (+) Watcher: "/home/ownSoMax/"
04-04 17:32:12:751 44177 OCC::FolderWatcherPrivate::slotAddFolderRecursive:     `-> and 3528 subdirectories
04-04 17:32:12:751 44177 OCC::FolderMan::scheduleFolder: Schedule folder  "3"  to sync!
04-04 17:32:12:751 44177 OCC::FolderMan::scheduleFolder: Folder is not ready to sync, not scheduled!
04-04 17:32:12:751 44177 OCC::ClientProxy::setupQtProxyFromConfig: Set proxy configuration to use system configuration
04-04 17:32:12:762 44177 OCC::ActivitySettings::setNotificationRefreshInterval: Starting Notification refresh timer with  300  sec interval
04-04 17:32:12:848 44177 OCC::Updater::getSystemInfo: Sys Info size:  87
04-04 17:32:13:046 44177 OCC::SyncJournalDb::checkConnect: sqlite3 version "3.11.0"
04-04 17:32:13:046 44177 OCC::SyncJournalDb::checkConnect: sqlite3 journal_mode= "wal"
04-04 17:32:13:046 44177 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect" and starting new transaction
04-04 17:32:13:046 44177 OCC::SyncJournalDb::tableColumns: Columns in the current journal:  ("phash", "pathlen", "path", "inode", "uid", "gid", "mode", "modtime", "type", "md5", "fileid", "remotePerm", "filesize", "ignoredChildrenRemote", "contentChecksum", "contentChecksumTypeId")
04-04 17:32:13:046 44177 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add inode index" and starting new transaction
04-04 17:32:13:046 44177 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add path index" and starting new transaction
04-04 17:32:13:046 44177 OCC::SyncJournalDb::tableColumns: Columns in the current journal:  ("path", "lastTryEtag", "lastTryModtime", "retrycount", "errorstring", "lastTryTime", "ignoreDuration", "renameTarget")
04-04 17:32:13:047 44177 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect End" 
04-04 17:32:13:054 44177 OCC::SyncJournalDb::checkConnect: sqlite3 version "3.11.0"
04-04 17:32:13:054 44177 OCC::SyncJournalDb::checkConnect: sqlite3 journal_mode= "wal"
04-04 17:32:13:054 44177 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect" and starting new transaction
04-04 17:32:13:055 44177 OCC::SyncJournalDb::tableColumns: Columns in the current journal:  ("phash", "pathlen", "path", "inode", "uid", "gid", "mode", "modtime", "type", "md5", "fileid", "remotePerm", "filesize", "ignoredChildrenRemote", "contentChecksum", "contentChecksumTypeId")
04-04 17:32:13:055 44177 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add inode index" and starting new transaction
04-04 17:32:13:055 44177 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add path index" and starting new transaction
04-04 17:32:13:055 44177 OCC::SyncJournalDb::tableColumns: Columns in the current journal:  ("path", "lastTryEtag", "lastTryModtime", "retrycount", "errorstring", "lastTryTime", "ignoreDuration", "renameTarget")
04-04 17:32:13:055 44177 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect End" 
04-04 17:32:13:070 44177 OCC::SyncJournalDb::checkConnect: sqlite3 version "3.11.0"
04-04 17:32:13:070 44177 OCC::SyncJournalDb::checkConnect: sqlite3 journal_mode= "wal"
04-04 17:32:13:070 44177 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect" and starting new transaction
04-04 17:32:13:070 44177 OCC::SyncJournalDb::tableColumns: Columns in the current journal:  ("phash", "pathlen", "path", "inode", "uid", "gid", "mode", "modtime", "type", "md5", "fileid", "remotePerm", "filesize", "ignoredChildrenRemote", "contentChecksum", "contentChecksumTypeId")
04-04 17:32:13:070 44177 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add inode index" and starting new transaction
04-04 17:32:13:070 44177 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "update database structure: add path index" and starting new transaction
04-04 17:32:13:070 44177 OCC::SyncJournalDb::tableColumns: Columns in the current journal:  ("path", "lastTryEtag", "lastTryModtime", "retrycount", "errorstring", "lastTryTime", "ignoreDuration", "renameTarget")
04-04 17:32:13:070 44177 OCC::SyncJournalDb::commitInternal: void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "checkConnect End" 
04-04 17:32:13:104 44177 OCC::Account::resetNetworkAccessManager: Resetting QNAM
04-04 17:32:13:104 44177 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
04-04 17:32:13:104 44177 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
04-04 17:32:13:104 44177 OCC::Account::resetNetworkAccessManager: Resetting QNAM
04-04 17:32:13:104 44177 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
04-04 17:32:13:104 44177 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
04-04 17:32:13:104 44177 OCC::Account::resetNetworkAccessManager: Resetting QNAM
04-04 17:32:13:104 44177 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
04-04 17:32:13:104 44177 OCC::ConnectionValidator::checkServerAndAuth: Trying to look up system proxy
04-04 17:32:13:109 44177 OCC::ConnectionValidator::systemProxyLookupDone: No system proxy set by OS
04-04 17:32:13:109 44177 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://somaxluan.hd.free.fr/owncloud" + "status.php" "OCC::ConnectionValidator"
04-04 17:32:13:109 44177 OCC::ConnectionValidator::systemProxyLookupDone: No system proxy set by OS
04-04 17:32:13:109 44177 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://mycore.core-cloud.net" + "status.php" "OCC::ConnectionValidator"
04-04 17:32:13:109 44177 OCC::ConnectionValidator::systemProxyLookupDone: No system proxy set by OS
04-04 17:32:13:110 44177 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://owncloud.icm-institute.org" + "status.php" "OCC::ConnectionValidator"
04-04 17:32:13:153 44177 OCC::AccountManager::saveAccount: Saving account "https://somaxluan.hd.free.fr/owncloud"
04-04 17:32:13:153 44177 OCC::AccountManager::saveAccountHelper: Saving  1  unknown certs.
04-04 17:32:13:424 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:32:14:056 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:32:14:649 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:32:15:598 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:32:16:780 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:32:18:807 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:32:22:426 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:32:29:167 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:32:36:280 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:32:43:086 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:32:50:016 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:32:56:771 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:33:03:651 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:33:10:508 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:33:17:371 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:33:24:250 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:33:31:251 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:33:38:227 44177 unknown: setNativeLocks failed: Resource temporarily unavailable
04-04 17:33:45:167 44177 unknown: setNativeLocks failed: Resource temporarily unavailable

**Comment by guruz** [comment]
Your config directory is on NFS?
https://bugreports.qt.io/browse/QTBUG-43454

Can you uninstall the client and try our 5.6.2 based packages?
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client

**Comment by dnacombo** [comment]
Am away from that computer. will do this next week. thanks.

Le mar. 4 avr. 2017 à 20:12, Markus Goetz <notifications@github.com> a
écrit :

**Comment by dnacombo** [comment]
Most of my home folder is on nfs, (not the data folders), so I suppose it
is. If you tell me which folder I should look for I can tell you.

I just downloaded your 5.6.2 based packages and it works like a charm

Thanks!

**Comment by guruz** [comment]
Nice that it works, thanks for testing!

(Ref https://github.com/owncloud/client/issues/5470 )
