### ISSUE TITLE
GSoC Junior Job - Remove magic numbers

### ISSUE THREAD

**Issue by mrow4a** [owncloud/client#5685]
In the code, in the Propagation phase, we decide on the number of parallel connections based on some condition called `isLikelyFinishedQuickly()`. This method is virtual method https://github.com/owncloud/client/blob/53c5f03c323d5bb11595c816a9cc1e1fef01fa0e/src/libsync/owncloudpropagator.h#L87 being overridden by other classes like here https://github.com/owncloud/client/search?utf8=%E2%9C%93&q=isLikelyFinishedQuickly&type= 

In case of Upload and Download, we decide it based on filesize, however, currently it is MAGIC NUMBER. Please remove magic number and implement sth like here -> https://github.com/owncloud/client/pull/5440/files#diff-2034b4c8369e7ef2d650e78a5e5e0ad9R134

Please also discuss it here, issues how to install server and client also, will be happy to guide you through the ownCloud :> Please also use QtCreator for that.

If you decide to solve this issue, please assign yourself to it:
![selection_166](https://cloud.githubusercontent.com/assets/13368647/24799365/186bc3b4-1b9b-11e7-913b-0665726ef126.jpg)

**Comment by mrow4a** [comment]
@jturcotte

**Comment by jturcotte** [comment]
cc @guruz @ogoffart 

I would call this more a "static estimation" rather than magic numbers. There were some thought behind those numbers. The questions I'm sending back is how much would we gain from making this estimation dynamic and what would it be based on?

**Comment by mrow4a** [comment]
I think the only issue here is to have some function instead of raw numbers. The topic you touches is yet another one, not sure if scope of the "Lets setup QtCreator, build client, install server, play with server, apply small not breaking patch, build, test, PR" :>

**Comment by kaustubh-welankar** [comment]
For building the client for Windows, is there a recommended version of Qt?

**Comment by jturcotte** [comment]
5.6.2 should work, but you'd need to build Qt and QtWebKit yourself. An unofficial way to bypass the fact that QtWebKit is deprecated and not shipped with Qt 5.6 would be to pass the `-DNO_SHIBBOLETH=NO` cmake parameter.

Feel free to ask on IRC for help.

**Comment by mrow4a** [comment]
You can also use QtCreator and CMakeList.txt which will save you a time of doing that all in console 
![selection_169](https://cloud.githubusercontent.com/assets/13368647/24815103/50fdf5b0-1bd4-11e7-8cb3-793c85215e22.jpg)

![selection_171](https://cloud.githubusercontent.com/assets/13368647/24815124/662e67a8-1bd4-11e7-99de-04e6fc1df91e.jpg)

This might also later help you with branded clients.

**Comment by mrow4a** [comment]
Yep, const in proper place would be enough.

**Comment by kaustubh-welankar** [comment]
I've built the client and installed the server on a Raspberry Pi. I'll work on this patch. @mrow4a, I can't assign the bug to myself. 
![capture1](https://cloud.githubusercontent.com/assets/20023689/24839658/6ada4d72-1d7c-11e7-88f5-eede340ba237.JPG)
Please assign it to me.

**Comment by mrow4a** [comment]
Hmm, ok, did realise you cannot, dont bother about that.

**Comment by mrow4a** [comment]
Closed with https://github.com/owncloud/client/pull/5705
