### ISSUE TITLE
[Linux] Corrupted menu under Elementary OS

### ISSUE THREAD

**Issue by gareththered** [owncloud/client#5688]
### Expected behaviour
On clicking the lower section of the client icon in the notification area, the menu should be displayed in the same way as it is displayed when cursor is further up the icon.  This doesn't seem to be a wingpanel bug as all other icons (remmina, language, sound, network etc) work as expected when the cursor is over the lower end of the respective icon.

### Actual behaviour
The menu displays for a fraction of a second then the text disappears from the menu leaving a slightly shorter (but empty) menu.

![owncloud_menu](https://cloud.githubusercontent.com/assets/3902182/24832482/5d6d9e88-1ca9-11e7-9d97-3ebd78e15da6.png)

### Steps to reproduce
1.  Install client version 2.3.1
2.  Exit old version and start new version of OwnCloud client.
2. Click on OwnCloud icon toward the lower end of the tick (or check mark).

### Client configuration
Client version:
2.3.1
Operating system:
Elementary OS 0.4
OS language:
English (UK)
Qt version used by client package (Linux only, see also Settings dialog):
5,5,1
Client package (From ownCloud or distro) (Linux only):
ownCloud
Installation path of client:
/usr/bin/owncloud
### Logs

1. Client logfile: Nothing shown in log file when clicking on the icon

**Comment by guruz** [comment]
> Qt version used by client package (Linux only, see also Settings dialog):
> 5,5,1

We have packages with Qt 5.6.2, can you try those?
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client

**Comment by gareththered** [comment]
I've just tried the package with Qt 5.6.2 and the results are the same unfortunately.

**Comment by SamuAlfageme** [comment]
@gareththered which version of the client for Ubuntu did you install? I've just tried with 16.10 on 0.4 (Loki) and multiple resolutions and it's looking like this: 

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/24899003/177022a0-1e9f-11e7-8437-5a4c61567a75.png"/>
</p>

Maybe it has something to do with the HiDPI settings? Have you experienced issues with more Qt applications?

**Comment by gareththered** [comment]
I initially installed the version for 16.04 (as that's what Elementary OS is based on).  I've just tried the 16.10 packages and also set my display to 1366x768 and this didn't fix the issue.  I do feel that I had to have the cursor lower down over the icon before the issue appeared, but it is still there.

I noticed that you had the client running without any configured accounts. I've just temporarily renamed my ownCloud config directory (to remove my settings/accounts) and the issue doesn't happen.  I have noticed though, that if I don't click on the icon itself, and instead place the mouse pointer over (for example) the area below the cloud and left of the circle, but still within the square that you'd consider the area of the icon, then the Applications menu or the calendar pop up!  This isn't the case for the built-in notification icons, such as the volume or network, where there is a space around the icon that is still considered part of the clickable area.

I haven't seen any other Qt issues, other than icons being too small on Qt applications - that's my next hurdle to fix.

**Comment by guruz** [comment]
Please @-MENTION someone from Elementary OS here because debugging all those Distro-specific bugs really takes too much of our time.

**Comment by guruz** [comment]
@davidak reported this issue too https://github.com/owncloud/client/issues/5534#issuecomment-281379735

Seems to work for @lchigami @peteruithoven https://github.com/owncloud/client/issues/5171

**Comment by gareththered** [comment]
@guruz - thank you for spotting that.  My symptoms are identical.  I'll close this as a duplicate of https://github.com/owncloud/client/issues/5534#issuecomment-281379735

**Comment by guruz** [comment]
Let's keep yours open, the other one is closed :)

**Comment by guruz** [comment]
@davidak  @lchigami @peteruithoven Which version and package are you on? And does it work for you?

**Comment by davidak** [comment]
@guruz see my last comment in https://github.com/owncloud/client/issues/5534#issuecomment-281379735.

Now i use Nextcloud. (which still has the issue)

**Comment by guruz** [comment]
I can only recommend to ping someone from Elementary OS as it is most probably their bug.

**Comment by SamuAlfageme** [comment]
I've noticed this behavior just now when hovering on different tray items:

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/26671423/b73f3076-46b5-11e7-91e0-80949e85aa89.gif"/>
</p>

As @guruz said in the previous comment best option there is to reach out to elementary guys to ask for issues with Qt applications regarding the tray menus.

**Comment by ogoffart** [comment]
I wopnder if this can still be reproduced with newer Qt version, and if the OWNCLOUD_FORCE_QDBUS_TRAY_WORKAROUND=1 or =0 helps

Not much we can do in our code tough, not really our bug.
