### ISSUE TITLE
owncloudcmd:  Don't start the sync when the capability call fails.

### ISSUE THREAD

**Issue by ogoffart** [owncloud/client#5692]
Reported here:  https://github.com/owncloud/client/issues/3936#issuecomment-292921020

 owncloudcmd still starts the sync even tough the capabilities call fails. (For example because there is no connection or that the login/password are wrong)

**Comment by kaustubh-welankar** [comment]
I'll fix this bug this week. You could assign it to me

**Comment by ckamm** [comment]
I've tested this by trying to use owncloudcmd with an invalid password and checking the log output.
