### ISSUE TITLE
[Bug] Unselected root, root syncs anyways

### ISSUE THREAD

**Issue by BloodyIron** [owncloud/client#5693]
I'm using the desktop client 2.3.1 in Ubuntu, connecting to OC 9.1.4.

I intentionally deselected the root folder to sync, yet the contents of the root (some documents) synced anyways. Of course any modifications are synced too, even though it's deselected.

I want it to honour the setting I have, namely not sync things I did not select.

I've seen this also happen when I select folders within a folder, just some, instead of all, and it will sync the contents of the parent folder, even though it's not selected.

Not sure why this wasn't noticed before.

**Comment by SamuAlfageme** [comment]
@BloodyIron Yup, this has been reported quite a few times already and IMO needs to be fixed. You can +1 in https://github.com/owncloud/client/issues/3664 to show your interest on this being solved and refer to https://github.com/owncloud/client/issues/3664#issuecomment-133367256 for the workaround to avoid this behavior. 

Closing here as duplicate. Thanks for reporting!

**Comment by BloodyIron** [comment]
Ahh sorry about that, I tried to search for it, clearly I missed it.
