### ISSUE TITLE
Check if we still need PROPFIND call before checking capabilities

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5697]
```ConnectionValidator::checkAuthentication()```

this is a PROPFIND not a GET (like in the comment). Could we directly request capabilities instead?
I remember there was a legacy server bug/reason behind all this which might be fixed by now. (-> git blame?)

**Comment by ogoffart** [comment]
See also the comment and PROPFIND in ShibbolethCredentials::slotFetchUser

This was added in commit d6525a979d36ba4d6f2d9017e3927129b19c6f95. at the time, the server was not accepting login on some other call than the webdav endpoint.

**Comment by guruz** [comment]
>  at the time, the server was not accepting login on some other call than the webdav endpoint.

FYI @PVince81

**Comment by ckamm** [comment]
FWIW, I can get a working session cookie from the capabilities request with my test server (10.0.0.8):
```
$ curl -k -u admin 'http://localhost/ocs/v1.php/cloud/capabilities?format=json' --cookie-jar sessioncookie
$ curl -k  'http://localhost/remote.php/webdav/' --cookie sessioncookie -X PROPFIND
-> good response
```

**Comment by PVince81** [comment]
Are you getting **one** cookie or **several** cookies ?

In the old code some endpoints would serve you a plate with several cookie flavors, but only one was valid and it wasn't guaranteed to be the last one...

**Comment by ckamm** [comment]
@PVince81 On demo.owncloud.org I get three different session cookies on my request, two of which are marked 'secure'. My follow-up request uses the last one sent.

While you're here, any ideas on https://github.com/owncloud/client/issues/5714 ?

**Comment by guruz** [comment]
ping @PVince81 (not urgent)

**Comment by TheOneRing** [comment]
@guruz  2.8 does a get against status.php first so I guess the core idea of this issue has be fixed?
We still perform a propfind to validate the credentials...

**Comment by TheOneRing** [comment]
Not planned
