### ISSUE TITLE
Owncloud client on Ubuntu 16.4 showing a red stop sign in status ribbon 

### ISSUE THREAD

**Issue by Foadsf** [owncloud/client#5700]
Dear Developers,

Today I noticed that my Ownlcoud client is showing a weird red stop sign in a black box on top left of unity status bar:

![screenshot from 2017-04-13 10-48-37](https://cloud.githubusercontent.com/assets/12762442/24997568/5cb29d0e-2037-11e7-9d6d-542ecf460df2.png)

I'm not sure why is it happening and what are the consequences. I am dealing with my project data and need to be sure that they are safely synced.
I'm using Owncloud client version 2.3.1, Built from Git revision 433ba0 on Mar 21 2017, 12:51:04 using Qt 5.5.1, OpenSSL 1.0.2g 1 Mar 2016
the server is a company which offers the service to the Dutch scientific organisations, Surfdrive. But I don't think there is any problem with the server because it works fine on windows and mac.

 Client logfile

04-13 10:56:47:713 2853 OCC::Application::setupLogging: "################## ownCloud en_US (en_US) 2.3.1 on Ubuntu 16.04.2 LTS"
04-13 10:56:47:714 2853 OCC::Application::slotParseMessage: Running for 745.035 sec
04-13 10:56:47:714 2853 OCC::ownCloudGui::slotShowSettings: void OCC::ownCloudGui::slotShowSettings()
04-13 10:56:52:764 2853 OCC::Folder::slotRunEtagJob: * Trying to check "https://surfdrive.surf.nl/files/remote.php/webdav/" for changes via ETag check. (time since last sync: 574 s)
04-13 10:56:52:764 2853 OCC::FolderMan::slotRunOneEtagJob: Scheduling "https://surfdrive.surf.nl/files/remote.php/webdav/" to check remote ETag
04-13 10:56:52:764 2853 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://surfdrive.surf.nl/files" + "/" "OCC::Folder"

**Comment by guruz** [comment]
Please uninstall the client and try the package from https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client
Does this work?
Thank you

**Comment by Foadsf** [comment]
I actually installed the client yesterday from the page you just gave me. I'm worried if I uninstall and install the client again all of my files have to be downloaded again. is it the only way?

**Comment by ogoffart** [comment]
Normally all file would not be downloaded again if you re-install the client.  (as uninstalling the client should normally not remove the configuration files or the data)

> using Qt 5.5.1

The package should be using Qt 5.6.2, hence i believe you are not using this package.
The problem might because of the Qt version.

**Comment by Foadsf** [comment]
how can I upgrade my Qt without uninstalling the Owncloud?

**Comment by Foadsf** [comment]
I reinstalled the ownlcoud client from the link again. and I also did update/upgrade using apt. the problem seems to be solved for now. I will report again if I see it again. thanks guys.

**Comment by michaelstingl** [comment]
Will be fixed with https://github.com/owncloud/client/issues/5470
