### ISSUE TITLE
[Fedora 24], [Fedora 25] No keychain service available - add "libgnome-keyring"?

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#5703]
I installed ownCloud client 2.3.1 on pretty minimal Fedora Desktops:

![fedora-workstation-netinst-x86_64-25-1_3](https://cloud.githubusercontent.com/assets/214010/25013729/11c2f706-2075-11e7-8940-9acd59d8eb0b.png)

### Expected behaviour
ownCloud client should install all necessary/recommended packages

### Actual behaviour
Reading from keychain failed with error: 'No keychain service available'

### Steps to reproduce
1. `Fedora-Workstation-netinst-x86_64-25-1.3.iso`
2. Software Selection: Minimal Install
3. `dnf -y group install base-x`
4. `dnf -y install gnome-classic-session control-center gnome-terminal gnome-terminal-nautilus liberation-mono-fonts wget`
5. `dnf config-manager --add-repo http://download.opensuse.org/repositories/isv:ownCloud:desktop/Fedora_25/isv:ownCloud:desktop.repo`
6. `dnf install owncloud-client`
7. Configure account
8. Quit ownCloud client and start again

### Client configuration
Client version:
2.3.1

Operating system:
Fedora 24, Fedora 25

OS language:
EN

Qt version used by client package (Linux only, see also Settings dialog):
Fedora 24: qt5-qtbase.x86_64 5.6.2-3.fc24
Fedora 25: qt5-qtbase.x86_64 5.7.1-14.fc25

Client package (From ownCloud or distro) (Linux only):
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

I had to install `libgnome-keyring` manually to fix this issue:

```
dnf -y install libgnome-keyring
```

@crrodriguez Should this be added to the ownCloud client dependencies?

**Comment by SamuAlfageme** [comment]
@michaelstingl which kind of minimal distro did you try? I have also experienced with other distro-scenarios where this could also happen e.g. in the [GUI-tests Dockerimage](https://gitlab.com/alfageme/client-GUI-tests/blob/master/Dockerfile#L22), based on an ubuntu pretty lightweight; I also needed to install [D-Bus](https://www.freedesktop.org/wiki/Software/dbus/).

This could probably be extended to the rest of the distros if we want to provide a self-contained as possible client.

**Comment by guruz** [comment]
@michaelstingl @jnweiger @crrodriguez Is this still to be done for 2.3.3? Or was it fixed with the recent changes by @jnweiger @dschmidt ?

**Comment by jnweiger** [comment]
I am hesitant to add hard requires for random packages. This increase the chance that owncloud-client cannot be installed due to one missing dependency.

For Fedora, I am adding now a 
Suggests:       libgnome-keyring

Hope that is sufficient.
