### ISSUE TITLE
owncloudcmd has to run many times before it's able to get the whole directory

### ISSUE THREAD

**Issue by madorian** [owncloud/client#5704]
Please help us by providing the following info. Before posting please make sure that you're running the latest available version for your oC release: https://owncloud.org/changelog/ + https://owncloud.org/changelog/desktop/

Steps to reproduce
1. owncloudcmd -h . https://foo:bar@hukarz/remote.php/webdav/
2. run it again, cause it didn't grab everything the first time
3. run it again, cause it didn't grab everything the second time
4. run it again and again and again and each time, it grabs more data

Expected behaviour
Tell us what should happen
It should only be run once.

Actual behaviour
Tell us what happens instead
I have to run it many times to grab all the data and I'm not even sure I have everything

Client configuration
Client version: 2.3.1
Client operating system: Ubuntu GNU/Linux 16.04

Server configuration
Operating system: Hosted
Web server:
Database:
PHP version:
ownCloud version (see ownCloud admin page):
Updated from an older ownCloud or fresh install:
Special configurations (external storage, external authentication, reverse proxy, server-side-encryption):

ownCloud log (data/owncloud.log)

Please paste possible errors in the following code block, see https://central.owncloud.org/t/how-to-find-webserver-or-oc-logfile-enable-php-logfile/808 for more info

**Comment by guruz** [comment]
It's hard to help you if you don't disclose any error messages or useful information log messages that you received. :-)

**Comment by madorian** [comment]
I can provide that, yes, but I just wanted to check first if this was intended behavior.

**Comment by ogoffart** [comment]
it should sync everything.   altought i think the files need to be at least 2 seconds old, otherwise they are not synced because it is tought that the files are still being modified.

**Comment by guruz** [comment]
@madorian Can you confirm this 2-second-age behaviour? Does this fix the issue?

**Comment by guruz** [comment]
Linking https://central.owncloud.org/t/owncloudcmd-has-to-run-x-amount-of-times-to-sync-the-directory/7004/2

**Comment by ogoffart** [comment]
Closing old issues.
Can't do more without more info.
