### ISSUE TITLE
Trying to synchronize Dropbox files which were flagged by DMCA breaks syncing

### ISSUE THREAD

**Issue by C0rn3j** [owncloud/client#5708]
I'm using the nextcloud client, git version from 2 days ago.

### Expected behaviour
Files should get synced.

### Actual behaviour
Client crawls through all the dropbox folders(which is unbearably slow too). When it tries to sync a DMCAed file("Restricted content" as dropbox calls it), it throws an error.
http://i.imgur.com/MduzNUS.png

After a while it starts this process again.

### Steps to reproduce
1. Get yourself a flagged file - I attached a FOSS penetration tool which seems to be flagged too, don't forget to unzip it.
[cSploit-release.zip](https://github.com/owncloud/client/files/927777/cSploit-release.zip)
2. Configure external storage app for dropbox and give it full access
3. Try to sync

### Server configuration
Operating system: Arch Linux

Web server: Nginx

Database: MariaDB

PHP version: 7.x

ownCloud version: Nextcloud 11.0.2.7

Storage backend (external storage): Dropbox  - full access

### Client configuration
Client version: 2.2.4

Operating system: Arch Linux

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):
Built from Git revision eaeed0 on Apr 16 2017, 20:59:23 using Qt 5.8.0, OpenSSL 1.0.2k 26 Jan 2017

Client package (From ownCloud or distro) (Linux only): built from nextcloud git

Installation path of client: not sure, if needed ask and I'll look

Are any more logs needed other than the screenshot I posted?

**Comment by ogoffart** [comment]
I am closing this issue because I think this is a server issue. The client only reports the errors from the server.

Please report this issue to the server component.

**Comment by SamuAlfageme** [comment]
@C0rn3j more on Dropbox & DMCA automated flagging: https://www.neowin.net/news/dropbox-is-scanning-your-files-for-signs-of-piracy. Report back in the Dropbox-integration issue tracker  https://github.com/owncloud/files_external_dropbox/issues for @Hemant-Mann
