### ISSUE TITLE
flatpak version of NextCloud client

### ISSUE THREAD

**Issue by rugk** [owncloud/client#5716]
Please create a flatpak version of the NextCloud client, so one can use this on Linux instead of having to built the sources.

As it is not related to theming I posted this here.

**Comment by hodyroff** [comment]
Please use ownCloud Client and ownCloud Server. Great stuff coming with 10.0!

**Comment by rugk** [comment]
Maybe you could offer a flatpak version? 😊

**Comment by hodyroff** [comment]
We have fully tested packages for Ubuntu, *SUSE, RHEL, CentOS, Fedora, Debian and Ubuntu ...
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

**Comment by michaelstingl** [comment]
Some more thoughts…
http://flatkill.org/

**Comment by halsafar** [comment]
A flatpak seems to be the only hope for getting Owncloud-Client on SteamDeck via the Discover store.  You can disable the OS protection and install it manually via pacman but it'll be wiped anytime the OS updates.

**Comment by rugk** [comment]
Even the update is two years old, … anyway, that's off-topic.
