### ISSUE TITLE
Failing OSX build

### ISSUE THREAD

**Issue by colinosullivan** [owncloud/client#5717]
### Expected behaviour

Expecting a successful build in the final step of the osx/build.sh step

### Actual behaviour

Produces an error and aborts the build. 

**Output as follows:**

```
[ 25%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/creds/credentialscommon.cpp.o
[ 25%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/__/3rdparty/qjson/json.cpp.o
[ 26%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/creds/httpcredentials.cpp.o
[ 26%] Building CXX object src/libsync/CMakeFiles/owncloudsync.dir/owncloudsync_automoc.cpp.o
make[2]: *** No rule to make target `/Users/builder/Library/Frameworks/Sparkle.framework', needed by `src/libsync/libowncloudsync.2.3.1.dylib'.  Stop.
make[1]: *** [src/libsync/CMakeFiles/owncloudsync.dir/all] Error 2
make: *** [all] Error 2
[  3%] Built target cstdlib
[  9%] Built target ocsync
[ 10%] Automatic moc for target owncloudsync
[ 10%] Built target owncloudsync_automoc
make[2]: *** No rule to make target `/Users/builder/Library/Frameworks/Sparkle.framework', needed by `src/libsync/libowncloudsync.2.3.1.dylib'.  Stop.
make[1]: *** [src/libsync/CMakeFiles/owncloudsync.dir/all] Error 2
make: *** [all] Error 2
sudo: /Users/colm/client_theming/client/admin/osx/sign_app.sh: command not found
Reference folder '../install/' does not exist.
Failed to create ownCloud-2.3.1.1.pkg
osx/build.sh: line 36: /Users/colm/install/*.tbz: No such file or directory
mv: rename /Users/colm/sig.txt to /Users/colm/install/signature.txt: No such file or directory

MacBook-Air:client_theming colm$ 
```

### Steps to reproduce
1. Get clean source and build for OSX. I follow all the steps outlined in the guide. 

### Server configuration
Operating system: OSX 10.11.1 El Capitain

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
> I follow all the steps outlined in the guide.

Which guide? URL?

And which command creates the above log output?

**Comment by guruz** [comment]
https://github.com/owncloud/client/blob/master/doc/building.rst ?

**Comment by colinosullivan** [comment]
@guruz I started the build process from scratch for OSX and this time it worked. Apologies. I'm closing the issue here. Thanks.

**Comment by Ohjay44** [comment]
@colinosullivan When you say you started the build process from scratch, how far back did you go? I am stuck with the same error you had posted above but I wasn't sure where you started over from.
