### ISSUE TITLE
file locking between users

### ISSUE THREAD

**Issue by EmilObermayr** [owncloud/client#5718]
### Expected behaviour
Shared files should be locked when opened in an application, just like this is the case when the file is shared through a file server.

### Actual behaviour
The same file can get opened and saved by multiple users. The last one "wins".

### Steps to reproduce
1. share XLS with another user A
2. open yourself in Excel
3. let user A open the file in Excel

### Server configuration
Operating system: 

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by ckamm** [comment]
Yes, ownCloud doesn't support locking files while a user is editing them. Instead, simultaneous edits are allowed and conflicts will need to be resolved manually. Both conflicting files are saved, so data isn't lost. 

This was a tradeoff made in the initial design, and I don't believe an automatic edit-lock feature is on the table for near or mid term.
