### ISSUE TITLE
Linux client will not connect reliably - No Connection - Webdav works though

### ISSUE THREAD

**Issue by wgregori** [owncloud/client#5721]
I've had problems over some time with my desktop client not being able to connect to the server despite that I can access Nextcloud via webdav from the same computer.  To reconnect the client I can remove the account and recreate it.  Furthermore, I can have another account connect with the client but not my main account.

Installation Details:
Nextcloud 11.0.2, Ubuntu 16.04, Nginx

Client: Version 2.2.4.

F12 Capture from Client
<script src="https://gist.github.com/wgregori/e0ac93a2024a09c0dcd2ded2ce98c0ae.js"></script>

Nginx error log
<script src="https://gist.github.com/wgregori/935a11b6ab84bdf2c2b8bf404b484112.js"></script>

**Comment by kdslkdsaldsal** [comment]
@wgregori This is the issue tracker of the ownCloud client. Please report issues with the nextcloud client at https://github.com/nextcloud/client_theming/issues
