### ISSUE TITLE
[OS X][Overlays] Finder extension does not work until the last page of the wizard is closed

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5726]
### Expected behavior
Once the account is set up, finder extension should start working on the local sync folder. 

### Actual behavior
Neither overlay icons **inside the folder**, nor the "Share with ownCloud" context menu entry are available until the last page of the wizard is closed. 

![apr-26-2017 11-46-02](https://cloud.githubusercontent.com/assets/2644445/25428406/0eee6c4e-2a76-11e7-93f3-c8afadd7135e.gif)

### Steps to reproduce
1. Complete account setup but leave the "Everything set up!" page opened. 
2. Open the local sync folder on the finder.

**Comment by guruz** [comment]
@SamuAlfageme didn't we say we'll just remove the last wizard page and pop up the config dialog?

**Comment by guruz** [comment]
Please re-test with the last wizard page removed :-)

**Comment by SamuAlfageme** [comment]
After closing https://github.com/owncloud/client/issues/5764 I think we've run every possible scenario affected by the last page removal. 

Continue the discussion about the page's dead code in the PR?

**Comment by guruz** [comment]
@settermjd FYI https://doc.owncloud.org/desktop/2.2/installing.html the https://doc.owncloud.org/desktop/2.2/_images/client-4.png wizard page has been removed.
