### ISSUE TITLE
Client asks for account password after certificate is rejected

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#5728]
When a SSL server certificate is presented to the user and rejected the client will not be able to communicate with that server. However, the client will still pop up a dialog asking for the user's password *after* the certificate was rejected. That is pointless and confusing.

Steps:
1. Have a server with a self-signed certificate (or mitmproxy one)
2. Set up an account, log out of it, quit the client.
3. Remove the certificate authorization from the config file. (or restart mitmproxy)
4. Start the client.
5. Reject the server's certificate.
6. Notice that the "Please enter your password" dialog pops up for the account.

@guruz

**Comment by ckamm** [comment]
This happens because the SSL Error that happens during the GET status.php causes a CredentialsMissingOrWrong. That's the case because we might need to retrieve the SSL *client* certificates from the keychain. So the httpcreds are fetched, but not ready (no password), and we go to askFromUser().

**Comment by guruz** [comment]
As discussed on IRC, should listen to ```authenticationRequired``` instead.
We discussed some more, need to summarize this still

**Comment by ckamm** [comment]
@guruz The code for sending the Auth header all the time refers to issue #4326 - doesn't that mean we can't re-revert https://github.com/owncloud/client/commit/ef9483c82d111464e67291cd134beef99d0afcfc as long as we support servers 8.X?

**Comment by ckamm** [comment]
PR https://github.com/owncloud/client/pull/5782

**Comment by guruz** [comment]
-> https://github.com/owncloud/client/issues/5789

**Comment by SamuAlfageme** [comment]
@ckamm @guruz somehow related: wouldn't it be useful that if the user mistakenly rejects the certificate and clicks on `Account > log-in`, the certificate will be displayed for acceptance again. Client restart is needed now for that

**Comment by ckamm** [comment]
@SamuAlfageme That'd be possible and make some sense. We'd need to track which rejected cert belongs to which account, so we can clear the "previously rejected" list of the right certificates when a relogin is triggered. It's a different ticket though, I'll make one.

**Comment by SamuAlfageme** [comment]
@ckamm closing here then 🎉
