### ISSUE TITLE
[OS X/WIN] After upgrading to Owncloud 10 file size/chunk limit on desktop client uploads

### ISSUE THREAD

**Issue by travisbotello** [owncloud/client#5733]
After upgrading Owncloud to version 10 uploads from macOS desktop client > 17/18MB fail with error msg `Server: forbidden`. From Android client uploads are working without any problems after Update to Owncloud 10.

### Expected behaviour
Uploading files to Owncloud folders via macOS desktop client should work without file size limitations.

### Actual behaviour
Uploading files larger than 17/18 MB causing a `Server: forbidden` error msg after the upload should be completed.

### Steps to reproduce
1. Upload files with different sizes from macOS desktop client
2. Uploading files > 17 MB will fail with error msg `Server: forbidden`

### Server configuration
Operating system: CentOS Linux release 7.3.1611 (Core) 

Web server: Apache/2.4.6

Database: 10.1.22-MariaDB

PHP version: PHP 7.1.3

ownCloud version: 10.0.0.12

### Client configuration
Client version: 2.3.1

Operating system: macOS Sierra (10.12.4)

OS language: German

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
```
28.04.17 11:41:10, Photos/test.zip, ownCloud,Blacklisting fortsetzen: Error transferring https://domain.com/remote.php/dav/uploads/admin/1763746003/.file - server replied: Forbidden
```

2. Web server error log:
No related entry in error log

3. Server logfile: ownCloud log (data/owncloud.log):
No related entry in data/owncloud.log

**Comment by SamuAlfageme** [comment]
Hm... haven't seen this particular behavior while testing updates to 10.0; maybe it was coincidence that my files were not big enough 🤔

However it sounds like it could be an issue with the new chunking algorithm since we switched to it if the server announces it's available; can you give a try switching the  [`OWNCLOUD_CHUNKING_NG`](https://github.com/owncloud/client/blob/92027e869230d82de1bbbd0d486ebf14bfc471f7/src/libsync/owncloudpropagator.cpp#L274-L280) env.var and restart the client?

Could you also paste the client/server logs while the issue reproduces to better find out what's the problem?

**Comment by travisbotello** [comment]
Also same problem/issue can be reproduced on Windows Desktop Client. Only my android sync app is working with large files.

Here are the log outputs:

**.owncloudsync.log**
```
#=#=#=# Syncrun started 2017-04-28T12:13:47
#=#=#=#=# Propagation starts 2017-04-28T12:13:50 (last step: 3436 msec, total: 3436 msec)
||Documents/large.zip|INST_NEW|Up|1493367635||38400802||2|Error transferring https://domain.com/remote.php/dav/uploads/myuser/2620097489/.file - server replied: Forbidden|403|0|0|||INST_NONE|
#=#=#=# Syncrun finished 2017-04-28T12:15:14 (last step: 83404 msec, total: 86840 msec)
#=#=#=# Syncrun started 2017-04-28T12:15:28
#=#=#=#=# Propagation starts 2017-04-28T12:15:32 (last step: 3508 msec, total: 3508 msec)
||Documents/large.zip|INST_ERROR|Up|1493367635||38400802||6|Das Element ist aufgrund vorheriger Fehler nicht synchronisiert: Error transferring https://domain.com/remote.php/dav/uploads/myuser/2620097489/.file - server replied: Forbidden|0|0|0|||INST_NONE|
#=#=#=# Syncrun finished 2017-04-28T12:15:32 (last step: 308 msec, total: 3816 msec)
```

**Access Log**
```
0.0.0.0 - myuser [28/Apr/2017:12:13:13 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 518
0.0.0.0 - myuser [28/Apr/2017:12:13:25 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 481
0.0.0.0 - myuser [28/Apr/2017:12:13:36 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 81
0.0.0.0 - myuser [28/Apr/2017:12:13:41 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 3726
0.0.0.0 - myuser [28/Apr/2017:12:13:42 +0200] "DELETE /remote.php/dav/uploads/myuser/2467049877 HTTP/1.1" 204 -
0.0.0.0 - myuser [28/Apr/2017:12:13:43 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 518
0.0.0.0 - myuser [28/Apr/2017:12:13:49 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 3726
0.0.0.0 - myuser [28/Apr/2017:12:13:50 +0200] "MKCOL /remote.php/dav/uploads/myuser/2620097489 HTTP/1.1" 201 -
0.0.0.0 - myuser [28/Apr/2017:12:14:09 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 482
0.0.0.0 - myuser [28/Apr/2017:12:13:51 +0200] "PUT /remote.php/dav/uploads/myuser/2620097489/00000000 HTTP/1.1" 201 -
0.0.0.0 - myuser [28/Apr/2017:12:14:14 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 518
0.0.0.0 - myuser [28/Apr/2017:12:14:11 +0200] "PUT /remote.php/dav/uploads/myuser/2620097489/00000001 HTTP/1.1" 201 -
0.0.0.0 - myuser [28/Apr/2017:12:14:38 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 482
0.0.0.0 - myuser [28/Apr/2017:12:14:46 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 518
0.0.0.0 - myuser [28/Apr/2017:12:14:33 +0200] "PUT /remote.php/dav/uploads/myuser/2620097489/00000002 HTTP/1.1" 201 -
0.0.0.0 - myuser [28/Apr/2017:12:15:12 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 482
0.0.0.0 - myuser [28/Apr/2017:12:14:54 +0200] "PUT /remote.php/dav/uploads/myuser/2620097489/00000003 HTTP/1.1" 201 -
0.0.0.0 - myuser [28/Apr/2017:12:15:13 +0200] "MOVE /remote.php/dav/uploads/myuser/2620097489/.file HTTP/1.1" 403 6193
0.0.0.0 - myuser [28/Apr/2017:12:15:16 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 518
0.0.0.0 - myuser [28/Apr/2017:12:15:29 +0200] "GET /ocs/v2.php/apps/notifications/api/v1/notifications?format=json HTTP/1.1" 200 81
0.0.0.0 - myuser [28/Apr/2017:12:15:31 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 3726
0.0.0.0 - myuser [28/Apr/2017:12:15:40 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 482
0.0.0.0 - myuser [28/Apr/2017:12:16:12 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 482
0.0.0.0 - myuser [28/Apr/2017:12:16:25 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 481
0.0.0.0 - myuser [28/Apr/2017:12:16:55 +0200] "PROPFIND /remote.php/dav/files/myuser/ HTTP/1.1" 207 481
```

**Error Log**
empty

**owncloud.log**
empty

**Comment by travisbotello** [comment]
> However it sounds like it could be an issue with the new chunking algorithm since we switched to it if the server announces it's available; can you give a try switching the OWNCLOUD_CHUNKING_NG env.var and restart the client?

I added this to owncloud.cfg

```
[ownCloud]
ChunkingNg=0
```

and restarted the client. Upload is still not working.

**Comment by ogoffart** [comment]
In the http log, we see

```
0.0.0.0 - myuser [28/Apr/2017:12:15:13 +0200] "MOVE /remote.php/dav/uploads/myuser/2620097489/.file HTTP/1.1" 403 6193
```
Why do you get a error 403 there?
Is there more info in the owncloud server log.

cc @DeepDiver1975

**Comment by travisbotello** [comment]
That is the big question...I've already pasted everything that is in the server logs...I don't see any errors or 403 requests.

Just restored a backup from yesterday, running owncloud 9 and here everything is working. Don't really know what's going on here..

**Comment by guruz** [comment]
@travisbotello It's not a config variable, it's a shell variable.

Can you please run the client with:

```OWNCLOUD_CHUNKING_NG=0 owncloud --logfile -```

thanks a lot :)

**Comment by guruz** [comment]
@travisbotello Any news?
Did you also check your ```owncloud.log``` in the server ```data``` directory?

**Comment by travisbotello** [comment]
@guruz Unfortunately I can't help with debugging anymore. 

I was having a lot of trouble with OC 10 regarding this issue...we are uploading files larger than 18mb all the time and some of our crucial company workflows were stuck because of this. So I downgraded to Version OC 9 which was working and now switched to NC 11 which is also working without any issues.

**Comment by travisbotello** [comment]
The `owncloud.log` in the `data` directory never showed any related entries to my failed uploads. I always changed the file name to check for corresponding log entries...but no results.

**Comment by guruz** [comment]
Strange. It should definitely occur for us too in testing but it doesn't.

**Comment by travisbotello** [comment]
That is indeed very strange that you can't reproduce. Maybe it was related to my server configuration, company network...IDK. However there are three main reasons why our theory might be wrong:

- OC 9 server working
- NC 11 server working 
- OC 10 server working from mobile applications

Why would it only stop working with OC 10 from desktop clients...?

**Comment by amberaries** [comment]
Oh my god! I have searched in google same issue many days! And gotcha!

@travisbotello did you solve that problem? Will downgrade of version or upgrade to new NC solve the issue?
