### ISSUE TITLE
Backup Detected

### ISSUE THREAD

**Issue by IT247NW** [owncloud/client#5736]
How do we prevent this message from popping up please? Only happens with 2 or 3 users.

### Expected behaviour
Files should sync up

### Actual behaviour
Message pops up to say a backup has been detected - keep local files as conflict or normal synchronisation.
### Steps to reproduce
1.  Wait
2. 
3. 

### Server configuration
Operating system: Linux

Web server: Apache\/2.2.15 (CentOS)
ownCloud version: 9.1.4

Storage backend (external storage):

### Client configuration
Client version: 2.3.1

Operating system: Windows 10

OS language: English

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

This type of error shows up quite often:

1. Exception: {"Message":"HTTP\/1.1 423 \"UA Certifcates\/Learner Certificates Apps\/apprentices 21.11.16 1.pdf\" is locked","Exception":"OCA\\DAV\\Connector\\Sabre\\Exception\\FileLocked","Code":0,"Trace":"#0 \/var\/www\/html\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php(136): OCA\\DAV\\Connector\\Sabre\\File->put(Resource id #387)\n#1 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(1036): OCA\\DAV\\Connector\\Sabre\\Directory->createFile('apprentices 21....', Resource id #387)\n#2 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/CorePlugin.php(523): Sabre\\DAV\\Server->createFile('UA Certifcates\/...', Resource id #387, NULL)\n#3 [internal function]: Sabre\\DAV\\CorePlugin->httpPut(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#4 \/var\/www\/html\/3rdparty\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#5 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(459): Sabre\\Event\\EventEmitter->emit('method:PUT', Array)\n#6 \/var\/www\/html\/3rdparty\/sabre\/dav\/lib\/DAV\/Server.php(248): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#7 \/var\/www\/html\/apps\/dav\/appinfo\/v1\/webdav.php(57): Sabre\\DAV\\Server->exec()\n#8 \/var\/www\/html\/remote.php(164): require_once('\/var\/www\/html\/a...')\n#9 {main}","File":"\/var\/www\/html\/apps\/dav\/lib\/Connector\/Sabre\/File.php","Line":174,"User":"D.Taylor"}

2. https://it247ltd-my.sharepoint.com/personal/support_it247nw_com/_layouts/15/guestaccess.aspx?docid=155d81d1252a64541834cb99472fcaac0&authkey=Abxi1hQduheuGdEg-gNrrsM

**Comment by ogoffart** [comment]
Did you, in fact, restore a backup?

**Comment by IT247NW** [comment]
No, I did not.

**Comment by guruz** [comment]
How many files/folders are in that sync folder?

Is ```apprentices 21.11.16 1.pdf``` in there?

**Comment by IT247NW** [comment]
There appears to be no files or folder in "UA Certifcates/Learner Certificates Apps"

When I search for "apprentices 21.11.16 1.pdf" it shows up in the list but when I click on it to take me to the file path, it's no there?

**Comment by guruz** [comment]
In your log file, I see some things which are not good

```{\"Message\":\"HTTP\\\/1.1 507 Insufficient Storage\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\InsufficientStorage```
 out of disk space?

Also a lot of ```is locked``` exceptions (FYI @PVince81)

**Comment by IT247NW** [comment]
Ok, thanks.  I have increased the quotas for all users and will keep an eye on it.
What does the 'is locked' exception mean please?

**Comment by ogoffart** [comment]
This message should no longer happen with the client >= 2.3.0 and the server >= 9.1

Could that be that the users were on earlier version of the client?
Are you sure this still happen with recent version of the client?

**Comment by fmoc** [comment]
No response within years but likely fixed, so I think we can close the issue. If not, please don't hesitate to reopen it.
