### ISSUE TITLE
Xfce4 systray icon for owncloud client looks ugly

### ISSUE THREAD

**Issue by thegreatyellow67** [owncloud/client#5737]
Hi, I'm working on a Linux Mint 18.1, today there was and update for owncloud client and I've installed it, but now the systray icon in the xfce4 panel notification area looks very ugly (bigger than others and outsized).
Actually I have the 2.3.1 client version installed.

http://i.imgur.com/pSouGKy.png](http://i.imgur.com/pSouGKy.png

The client was previously installed following instructions at this page:

https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

What's wrong? A known bug? A wrong recompiling for the lastest version?

Before the upgrade icons was ok.
Anyone can help me? Thanks

**Comment by ckamm** [comment]
@thegreatyellow67 This is not a known issue yet and I'm afraid we're unlikely to be able to help. The ownCloud client calls `QSystemTrayIcon::setIcon()` which is documented with "The icon will be scaled to the appropriate size as necessary".

If it's not scaled correctly that should be either a problem with Qt (Which version are you running? We recommend >= 5.6.1, try `owncloud --version`) or xfce4's tray panel.

You're welcome to suggest workarounds by looking at owncloudgui.cpp:71 (the `setIcon` call).

**Comment by guruz** [comment]
We have special Qt 5.6.2 based builds available from https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client
Can you try those?

**Comment by thegreatyellow67** [comment]
Not yet, yesterday I was trying to install qt in my Linux Mint 18 but with no luck. The owncloud --version said that was using qt version 4.8.7, but older version of owncloud-client 2.2.1 said that was using version 5.5.1...I was a little bit confusing!! Anyway I will try in a clean vm and report if was successfull or not. Many thanks.

Il 03 maggio 2017 17:39:46 CEST, Markus Goetz <notifications@github.com> ha scritto:
>We have special Qt 5.6.2 based builds available from
>https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client
>Can you try those?
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/owncloud/client/issues/5737#issuecomment-298949660

-- 
Inviato dal mio dispositivo Android con K-9 Mail. Perdonate la brevità.

**Comment by guruz** [comment]
@thegreatyellow67 the link above ships its own private Qt. No need to install it in the system :-)

**Comment by thegreatyellow67** [comment]
Yes, thanks, understood after installation :-)
Anyway, it seems to work like a charm! ;-) I've tried in a clean VM machine with Linux Mint 18.1 Serena, I will test moreover in other Linux Mint machines so I will finally confirm this.
Many thanks.

**Comment by guruz** [comment]
@thegreatyellow67 great:)

FYI @dschmidt @jnweiger @SamuAlfageme

**Comment by thegreatyellow67** [comment]
I confirm that Qt 5.6.2 based build of owncloud client fixes the ugly icon look in old Linux Mint 18 Sarah and also in newer Linux Mint 18.1 Serena.
Previous I was using the installation steps mentioned in this link:
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client
that gives me the error.

Anyway, many thanks!
Cheers.
