### ISSUE TITLE
[Windows] Manual for building owncloud-client is confusing

### ISSUE THREAD

**Issue by davidix** [owncloud/client#5739]
I've read the manual of building the client for windows and skipped the steps one by one to step 4.
but unfortunately i'm not familiar with qt and cmake and the manual doesn't explain it as well
can anyone tell me how i should skip the rest of steps?

i don't know how to skip this step :
set PATH=C:\<OpenSSL Install Dir>\bin;%PATH%
set PATH=C:\<qtkeychain Clone Dir>;%PATH%

**Comment by kaustubh-welankar** [comment]
1. Try the steps mentioned in the comments https://github.com/owncloud/client/issues/5685 for building the client using the Qt tools. Follow these steps after you have completed step 4 in the building instructions.
2.  I'm not sure if you can build the client without OpenSSL and Qtkeychain, so don't skip it. For adding anything to your PC's PATH, refer to https://www.computerhope.com/issues/ch000549.htm. 
3. Also, for OpenSSL, install the 32-bit "non-Light" version.

**Comment by settermjd** [comment]
@davidix this sounds like a support request. Have you tried getting help in https://central.owncloud.org/? I'm not trying to infer that the issue isn't genuine and will review the wording in the documentation.

**Comment by settermjd** [comment]
@davidix did the feedback from @kaustubh-welankar help out?
