### ISSUE TITLE
High memory usage for Large Amount Of Files 

### ISSUE THREAD

**Issue by kingmxiii** [owncloud/client#5742]
### Expected behaviour
Syncing proccess should be normal !!

### Actual behaviour
Owncloud Client is acting up and I noticed memory usage is going over 2GB

### Steps to reproduce
1. Install Windows 2008 Server
2. Install Owncloud Client
3. Sync A folder with More than 1 millions Files

### Server configuration
Operating system:
Ubuntu 16.04
Web server: 
Apache 2
Database:
MariaDB
PHP version:
7.0.15
ownCloud version:
9.1.4
Storage backend (external storage):
Local Storage
### Client configuration
Client version:
2.3.2
Operating system:
Windows Server 2012
OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

4. Comment:
The client was constantly freezing and crashing when memory usage was reaching 2GB, Doing some research I found the 32 bits applications are limited to 2GB usage. With lead me to think that whats the reason why the client was crashing. 

Using this tutorial http://gisgeek.blogspot.com/2012/01/set-32bit-executable-largeaddressaware.html i was able I was able to modify the the client .exe file. After That changes the client doesnt crash but it is still freezing a lot. with high memory usage.

**Comment by hodyroff** [comment]
Yes, this is expected behavior on Windows as we are currently using a 32bit client.
https://github.com/owncloud/client/issues/2717 you are welcome to add your case there. I suppose you are syncing a file server?

**Comment by guruz** [comment]
> 2.3.2

That version has greatly reduced memory usage. How many files were you trying to sync?

Maybe there is a bug.

FYI @jturcotte isn't memory usage even lower with on-demand jobs in 2.4?

**Comment by jturcotte** [comment]
There were improvements to reduce the peak, but memory in 2.3 was still growing indefinitely during sync.

I was able to do a sync of 500k files and 50k directories download with the current 2.4 master branch, completed with a peak usage of 425 MB private bytes (actual memory used) and 850 MB virtual memory (address space usage including reserved empty heap pages).

This should allow us to sync 1 million files with 2.4.
I don't know how virtual memory usage will behave past this amount with heap fragmentation, so I wouldn't claim higher unless we test it.

**Comment by stevenmcastano** [comment]
I seem to be having this issue on a Mac with version 2.4.1.

It looks like the client is reading all the files, scans all the directories... and memory hits about 1.5G, but then it pauses before starting to upload the changed files, and memory starts increasing QUICKLY until it hits about 6GB, then the client crashes.

Any possible idea on how to get around this?
