### ISSUE TITLE
[2.1.1] [Linux] Cannot recover from network interface removed and reconnected

### ISSUE THREAD

**Issue by ctrlbru** [owncloud/client#5743]
### Expected behaviour
I expect the client to be able to recover if the network interface (e.g. eth0) is hot pluggable and it's removed and reconnected.

### Actual behaviour
Client shows a red warning "No connection to ownCloud on... Network access is disabled" and cannot reconnect. I have to close and open it again.

### Steps to reproduce
1. Open client and check it's connected to the server
2. Unplug network interface
3. Plug network interface
4. Client cannot reconnect anymore

### Client configuration
Client version: 2.1.1+dfsg-1ubuntu1.1
Operating system: Mint 18.1
Installation path of client: standard from pm

### Logs
https://gist.github.com/ctrlbru/6123b098fd8fe162ebb1e874d175fa7e#file-gistfile1-txt

**Comment by SamuAlfageme** [comment]
Hey @ctrlbru It looks like you are using quite an old client version:

> 2.1.1+dfsg-1ubuntu1.1

Can you try again with an updated version of the client? I've just tried this with 2.3.1 in Ubuntu 16.10 and it recovered gracefully after plugging the cable again.

**Comment by ctrlbru** [comment]
I can try, but please note that I'm not just disconnecting the cable, but the entire network interface (it's an usb-c hub for xps 13). That's why, I think, you see

`Interfaccia "org.freedesktop.DBus.Properties" inesistente sull'oggetto nel percorso /org/freedesktop/NetworkManager/ActiveConnection/13`

Which give or take translates to:

`Interface "org.freedesktop.DBus.Properties" not existing on object at path  /org/freedesktop/NetworkManager/ActiveConnection/13`

I think that 13 is my ethernet adapter being unplugged. Maybe

`unknown: QIODevice::read (QDisabledNetworkReply): device not open`

occours because the client is somehow still referring to the old ethernet interface and cannot see the "new" one? After plugging the interface back, networkmanager knows it as 14, not 13 anymore.

**Comment by SamuAlfageme** [comment]
@ctrlbru oh, that's an interesting case, just curious: does the same happens in mint if you switch from a wired connection to a wireless one? (in practice it will be the same)

**Comment by guruz** [comment]
This client version is way too old. Please try our builds from https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client

**Comment by ctrlbru** [comment]
Hi, I tried with 2.3.1 and it seems to work flawlessly. Sorry for not trying the latest version before, but I was sure I already had it, because on another machine I added the repository... on this one I had not.

Thanks!
