### ISSUE TITLE
When there's not enough space on local disk the error is displayed briefly and then gone

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5746]
This might be either a regression or expected behavior, but looks rather odd: 

### Actual behavior
When the disk space available is [under the `OWNCLOUD_FREE_SPACE_BYTES` threshold](https://doc.owncloud.org/desktop/2.2/advancedusage.html#low-disk-space): 

* All the remote files not synced are created hidden with a `.~XXXX` suffix and 0B. 
* The `Not synced` tab displays the errors, but they're tagged as non-fatal (i.e. with [the `i` icon](https://doc.owncloud.org/desktop/2.2/_images/icon-information.png)) and therefore, the account page displays no visible error. 

![space_error](https://cloud.githubusercontent.com/assets/2644445/25670180/28ef5eda-302c-11e7-98ae-56870934e18c.gif)

### Expected behavior
This kind of errors could be considered "hard" and therefore displayed on the account page visibly for the user to notice them and fix the space problems. 

### Steps to reproduce
1. Create a 200MB virtual drive
2. Add an account and use that drive as local sync folder
3. Start the sync

**Client 2.3.1 on Windows7**

**Comment by guruz** [comment]
FYI @ckamm

**Comment by ckamm** [comment]
@SamuAlfageme Nice find, will look at it.

**Comment by ckamm** [comment]
I fixed the spurious temporaries by the way.

**Comment by ckamm** [comment]
@SamuAlfageme Partially this is fixed for 2.3.2 and I'd be glad if you confirmed by testing, but the part about error messaging isn't started yet.

**Comment by guruz** [comment]
The error too briefly is also here: https://github.com/owncloud/client/issues/5516

**Comment by ckamm** [comment]
Addressed by https://github.com/owncloud/client/pull/5890

**Comment by SamuAlfageme** [comment]
@ckamm nice! working as expected now. Only detail worth to mention is that the empty folders from the selective sync step of the wizard are recreated even though nothing is synced inside them, could be a good idea not to recreate anything locally until we know we have the space in disk.

Closing here 👍
