### ISSUE TITLE
Unable to delete Redis Dat files

### ISSUE THREAD

**Issue by OccieCat** [owncloud/client#5749]
Windows 10, 1607, 64 Bit
Redis is not installed and not running as a Service (used Task Manager and Autoruns)
There are over 60 RedisQFork_####.dat files in a Windows/System32/Config/ folder for a total of 17.7GB
SpaceSniffer shows the files, WINDIRSTAT does not and I can't see the files using Windows Explorer or from the Command Prompt (run as Administrator).
Apparently some application I previously installed then uninstalled creates these files but did not delete the older versions.
How can I delete these files that I can't see and recover the space?

**Comment by kdslkdsaldsal** [comment]
@OccieCat Are you sure that this (an issue tracker of the sync client of ownCloud) is the correct place to report this?
