### ISSUE TITLE
No follow on Symlinks :(

### ISSUE THREAD

**Issue by vincegre** [owncloud/client#5751]
### Expected behaviour
Tell us what should happen

The app on Linux should follow symlinks ! It doesn't right now ! Tested on Ubuntu 16.04.2 LTS 64 Bits

### Actual behaviour
Tell us what happens instead

Nothing, it ignores the directory  !

### Steps to reproduce
1. Put in the sync folder of the client a link to an other directory and you'll see that nothing happens !

### Server configuration
Operating system:

Ubuntu 16.04.2 on server and client

Web server: 

Apache 2

Database:

MySQL

PHP version:

7

ownCloud version:

Nextcloud 11.0.3

Storage backend (external storage):

N/A

### Client configuration
Client version:

2.3.1

Operating system:

Ubuntu 16.04.2

OS language:

French

Client package (From ownCloud or distro) (Linux only):

Package from repository

Thanks

Vincèn

**Comment by hodyroff** [comment]
Correct, this is a documented architectural decision and there are many other ways for the same effect from a user perspective. https://doc.owncloud.org/server/latest/admin_manual/release_notes.html#owncloud-does-not-follow-symlinks

**Comment by vincegre** [comment]
I think there is a serious misunderstanding here ! I'm speaking about the NextCloud client on computer not the NextCloud app you run on the server !

**Comment by hodyroff** [comment]
Same thing. Client and Server side. At least for ownCloud. As Nextcloud pretty much copies everything we do it is likely the same there.

**Comment by krwlng** [comment]
i used since 5 years, but i update oc and symlinks is disabled, i'm so angry!
