### ISSUE TITLE
The share dialog for indirectly shared items shouldn't say "This item is not shared"

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#5753]
When one shares `foo/` and then opens the sharing dialog for a subfolder of contained file, like `foo/bar`, it will state "The item is not shared with any users or groups". That could very well be confusing users.

It would be nice to be able to see whether an item is already indirectly shared through a user/group share or a public link.

@guruz

**Comment by guruz** [comment]
I agree... @pmaier1 @michaelstingl

**Comment by TheOneRing** [comment]
The sharing dialog is considered deprecated
