### ISSUE TITLE
[Windows] Unable to sync empty directories when using ext2fsd drivers on an ext4 filesystem

### ISSUE THREAD

**Issue by iakko** [owncloud/client#5757]
### Expected behaviour
Creating a new empty directory on a synchronized folder. See the new directory through web interface.

### Actual behaviour
Creating a new empty directory on a synchronized folder. OwnCloud Windows Client returns a **CSync failed to access** error.

### Additional Notes
This error occurs only if the directory remains empty. If I put some file inside the directory, it will be correctly uploaded and synchronized. The CSync error disappears from Windows' Client.
If I create the same directory through the Web Interface, the directory appears correctly on the local folder after the Windows' Client synchronization process.

### Steps to reproduce
1. Create a new directory on a synchronized folder. 
2. Wait the client to recognize the new directory.
3. See the error on the client windows (and system tray icon).

### Server configuration
Operating system: Ubuntu 16.04 LTS

Web server: Apache 2.4.18

Database: MySQL 5.7.18

PHP version: 7.0.15-0ubuntu0.16.04.4

ownCloud version: 9.1.5 (stable)

Storage backend (external storage):

### Client configuration
Client version: 2.3.1

Operating system: Windows 10

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: "C:\Program Files\ownCloud\"

**Filesystem of local directory**: ext4 mounted with **ext2fsd** drivers.

### Logs

1. Client logfile: https://gist.github.com/iakko/9325d62002a1c3277c201d73d0a5432e

2. Web server error log: nothing

3. Server logfile: nothing

**Comment by guruz** [comment]
```
05-08 14:26:46:986 0x67d9ce4 csync_walker: directory: S:/mydrive/Documents/Test [inode=851989]
05-08 14:26:46:986 0x67d9ce4 _csync_detect_update: Checking for rename based on inode # 851989
05-08 14:26:46:986 0x67d9ce4 _csync_detect_update: file: Documents/Test, instruction: INSTRUCTION_NEW <<=
05-08 14:26:46:987 0x67d9ce4 csync_statedb_close: sqlite3_close=0
05-08 14:26:46:997 4420 OCC::SyncEngine::handleSyncError:  #### ERROR during  csync_update :  "CSync failed to access S:/mydrive/Documents/Test"
05-08 14:26:46:998 4420 OCC::SyncJournalDb::close: void OCC::SyncJournalDb::close() "S:/mydrive/._sync_c01cfb7decc6.db"
```

Weird! I guess it works if you put it on a normal windows NTFS drive?

I can only assume that the drive for ext2fsd returns something that we don't like in https://github.com/owncloud/client/blob/95c479aa07e29cce0b3a948964e5056de355edd4/csync/src/vio/csync_vio_local_win.c#L51 or https://github.com/owncloud/client/blob/95c479aa07e29cce0b3a948964e5056de355edd4/csync/src/vio/csync_vio_local_win.c#L137
(or in the callees..)

**Comment by iakko** [comment]
Hello Guruz,
yes, seems like if I place the local folder in a NTFS filesystem, everything works.

Also, I noticed that syncing the same folder when I'm on Linux (with Linux client), I don't have that issue.

So, I can assume that's a ext2fsd driver problem.

Thanks.

**Comment by guruz** [comment]
@iakko Have you tried asking the developers of ext2fsd?
I'll try it: @matt-wu @ngkaho1234

**Comment by iakko** [comment]
@guruz: nope, I didn't.

**Comment by TheOneRing** [comment]
For full feature support we require NTFS on Windows.
With fat we have support a limited feature set, other file systems are not supported.
