### ISSUE TITLE
Owncloud Client Ubuntu 16.04. does not install

### ISSUE THREAD

**Issue by ohnemich** [owncloud/client#5758]
Hi, 
I am facing an error when trying to install Owncloud client in ubuntu 16.04LTS 32bit. Would appreciate any help!

### Expected behaviour
Owncloud should be installed when using the software-centre (or the downloaded client from opensuse.org)

### Actual behaviour
Owncloud does not install

### Steps to reproduce
1. Open Software-Centre
2. Install owncloud
3. Installation stops, producing an error

### Server configuration
Operating system: unknown

Web server: unknown

Database:unknown

PHP version:unknown

ownCloud version:9.1.4

Storage backend (external storage):unknown

### Client configuration
Client version: n/a

Operating system Ubuntu 16.04 LTS 32bit

OS language: German/English

Qt version used by client package (Linux only, see also Settings dialog): unknown

Client package (From ownCloud or distro) (Linux only): unknown

Installation path of client: n/a

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: 

Output of Installation routine, using the installation package of the software-centre

"Package dependencies cannot be resolved

The following packages have unmet dependencies:

owncloud-client: Depends: libowncloudsync0 (= 2.1.1+dfsg-1ubuntu1.1) but 2.1.1+dfsg-1ubuntu1.1 is to be installed
                 Depends: libc6 (>= 2.4) but 2.23-0ubuntu7 is to be installed
                 Depends: libgcc1 (>= 1:4.2) but 1:6.0.1-0ubuntu1 is to be installed
                 Depends: libqt5core5a (>= 5.5.0) but 5.5.1+dfsg-16ubuntu7.2 is to be installed
                 Depends: libqt5dbus5 (>= 5.0.2) but 5.5.1+dfsg-16ubuntu7.2 is to be installed
                 Depends: libqt5gui5-gles (>= 5.0.2) but 5.5.1+dfsg-16ubuntu6 is to be installed
                 Depends: libqt5network5 (>= 5.0.2) but 5.5.1+dfsg-16ubuntu7.2 is to be installed
                 Depends: libqt5webkit5 (>= 5.0.2) but 5.5.1+dfsg-2ubuntu1 is to be installed
                 Depends: libqt5widgets5 (>= 5.2.0) but 5.5.1+dfsg-16ubuntu7.2 is to be installed
                 Depends: libqt5xml5 (>= 5.0.2) but 5.5.1+dfsg-16ubuntu7.2 is to be installed
                 Depends: libstdc++6 (>= 5.2) but 5.4.0-6ubuntu1~16.04.4 is to be installed
"

I do run a 32-bit system and upgraded from 14.04 to 16.04, but I also checked my sources.list, which refers correct to the 16.04. sources. Even installing the older i386 package for Ubuntu 14.04 does not work, trying to install this version results in the icon shown in the side bar but nothing more happening.

Thanks!!

**Comment by michaelstingl** [comment]
Please install the client following the instructions here: https://owncloud.org/install/#install-clients

**Comment by ohnemich** [comment]
Hi Michael,

I tried it and it did not finish with another error.

_sudo apt-get install _owncloud-client_
resulted in
_The_ following packages have unmet dependencies:
 owncloud-client : Depends: owncloud-client-l10n but it is not going to be installed
E: Unable to correct problems, you have held broken packages._

and trying to (re)install owncloud-client-l10n via
_sudo apt-get install owncloud-client-l10n_
resulted in
The following packages have unmet dependencies:
 owncloud-client-l10n : Depends: owncloud-client (>= 2.3.1-1.2) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Comment by guruz** [comment]
Please try the packages that ship with their own Qt in a newer version.
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Adevel%3AQt562&package=owncloud-client

**Comment by ohnemich** [comment]
Hi @guruz , that did the trick! Thank you very much.

**Comment by guruz** [comment]
Great!

FYI @jnweiger @dschmidt
