### ISSUE TITLE
[Linux] Display build number and runtime dependencies on "About" section

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5760]
Testing 2.3.1 with @guruz we noticed that some useful info is missing/**not-visible** in the "About" section of the Settings:
* Build no. from the CI (maybe there's no such thing to track different builds on the OBS, but would be useful to identify unequivocally dif. builds)
* Runtime dependencies (and versions: https://github.com/owncloud/client/pull/5619), useful for automated tests, and checking that client's are with the shiny Qt5.6.2.

### Expected behavior
e.g. from OS X: 
<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/25839886/ddae8370-3499-11e7-8204-d7b44f2405f2.png"/>
</p>

### Actual behavior:
e.g. from CentOS 7
<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/25839890/e1e1f12a-3499-11e7-8630-4ee4fa651c11.png"/>
</p>

**Comment by guruz** [comment]
@ckamm @ogoffart You see this when you build from your local machine, right?
It's only not visible when built from build machine?

**Comment by SamuAlfageme** [comment]
😅 I just spotted the problem:  

![info](https://cloud.githubusercontent.com/assets/2644445/25840283/8184b130-349b-11e7-8588-02ecd6e2862c.gif)

Dropping sev.

**Comment by guruz** [comment]
I noticed those kind of problems with the sharing dialogue on macOS too.
Maybe @ogoffart can make a quick comment about the Qt layout magic that is needed.

**Comment by ckamm** [comment]
Setting the vertical size policy to `Minimum` fixes it.

**Comment by SamuAlfageme** [comment]
Updated in master, switching milestone for coherence

**Comment by guruz** [comment]
After testing this also close https://github.com/owncloud/client/issues/3088

**Comment by SamuAlfageme** [comment]
👍
