### ISSUE TITLE
Client on Ubuntu does not save password

### ISSUE THREAD

**Issue by kaumpail** [owncloud/client#5761]
Hello,
not sure if this is related to: 'Owncloud Client Mac does not save password #5750'. I'm using Nextcloud and the Nextcloud themed client but they state bugs not concerning the theming should be reported here.
After reboot the client asks me every time for the user credentials. Quitting the client and restarting it does not.
I have a dual boot system with Windows and Ubuntu 17.04. The synchronized folder is not shared (each operating system syncs on its own).

### Expected behaviour
No new password prompt after rebooting.

### Actual behaviour
After rebooting Linux I am prompted for the user credentials. First I thought it's only when after switching the OS bus it happens at every reboot. In the 'Password and Keys' Manager from Ubuntu the Login credentials are still saved. After entering the credentials again two new entries are created with type base64, user: 'username_clientKeyPEM:URL' and empty password string.

### Steps to reproduce
1. Boot to Ubuntu. Enter Account credentials.
2. Shut down, reboot.
4. Client asks for account credentials.

### Server configuration
Operating system: Arch Linux ARM
Web server: nginx
Database: MariaDB
PHP version: 7.0
ownCloud version: Nextcloud 11.0.3.2

### Client configuration
Client version: Nextcloud client-theming Version 2.3.1. ([https://github.com/nextcloud/client_theming](https://github.com/nextcloud/client_theming))

Operating system: Ubuntu 17.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): cannot find any information in the settings dialogue.

Client package (From ownCloud or distro) (Linux only): distro, not self build 

Installation path of client:

### Logs

Client log file: 
The first one is the log file after reboot and the second one is after quitting the client and restarting it.
[gist_logs](https://gist.github.com/kaumpail/85a1e81fbf82801185463a2d03bb3274)

Can it be that line line 44 of file 'after_rebooting.log' is the problem as it looks for a place that does not exist and after all it is a problem with the Nextcloud themed client?

UPDATE:
The loss of the user credentials does not happen all of the time, sometimes it works fine but I didn't find a pattern.

**Comment by guruz** [comment]
> they state bugs not concerning the theming should be reported here.

But here we can't help either because the keychain strongly depends on the OS/distro integration and how the client is built. I'd suggest you still try at nextCloud first, sorry.

If you find a solution, please also let us know :)
