### ISSUE TITLE
improvement: local unix permissions for local sync folder

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5765]
Currently the local sync directory, ~/ownCloud, has local UNIX permissions quite widely open: "drwxr-xr-x".

It would be better if that was limited by default to "dwrx-------". That's in case of computers shared between several users. That would apply to new client installations.

**Comment by ckamm** [comment]
@moscicki What we currently do is follow unix-standard and create new files and directories with the active umask. Wouldn't you expect admins or users to change the user homedir permissions in the first place if access isn't desired?

**Comment by moscicki** [comment]
Makes sense. Thanx.
