### ISSUE TITLE
Add New Sync Folder Pair: pasting a complete path to remote folder should issue only one PROPFIND

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5766]
Please see screenshot below.

I just pasted the full path into the text box. The error message is bogus - I can proceed with adding the folder. But the error message confuses the users.

The widget creates a sequence of PROPFIND requests for all the parent directories. In our generalized storage approach I do not have access to parent directories (only to the final one). I know that this is not POSIX-like but that's the way it works.

One PROPFIND to the final destination would fix it nicely (and would make less calls to the server anyway).

![screenshot](https://cloud.githubusercontent.com/assets/621965/25955617/0df5c706-366a-11e7-9f47-9f0be9b522a5.png)

**Comment by hodyroff** [comment]
The message is of course correct: The parent folders can't be listed. But confusing, yes.
ownCloud Server puts all the shares in the root or /Shared to avoid this ...
That the folder can't be found through the browser is fine? So the full path paste is the only way to get there.
Better error message or should it just silently be added to the browser?

**Comment by moscicki** [comment]
In this case if the full path is copy/pasted then I don't think it should check the parent folders -- just the target one.

The error message still applies in case the path which is typed into the textbox is not accessible. In this case the error message should be improved e.g. "Cannot access folder: <folder> (Bad Request)" or alike.

This improvement makes sense for the more general owncloud logic with unsyncable/unreachable folders which is discussed in several places:  e.g. https://github.com/owncloud/core/issues/26311

**Comment by guruz** [comment]
>  I know that this is not POSIX-like but that's the way it works.

Ughh..

> This improvement makes sense for the more general owncloud logic with unsyncable/unreachable folders which is discussed in several places: e.g. owncloud/core#26311

Hmmmmmmm

This is departing from the logic we had since years. But might be fine if it is only for the wizard.

**Comment by moscicki** [comment]
This actually request is for the wizard when the full path specified (and IMO makes sense in general not to query the parent folders by the client in this wizard because it is up to the server to define the access policy on the target folder/URI anyway).

For sync discovery phase you obviously goes top down so by definition go cross all the parents. There is no contradiction with owncloud/core#26311: if some subtree would not be accessible, it would not be discovered and synced.

**Comment by ckamm** [comment]
@moscicki The reason it PROPFINDs the parents is that it wants to highlight the target folder in the file tree view, therefore expands all parents and then needs to discover these folder's contents.

We could add a special case for your situation, but it's not something that usually comes up for other people, so it'd be brittle and prone to break. :/

**Comment by michaelstingl** [comment]
Duplicate for https://github.com/owncloud/client/issues/7724. Fixed in https://github.com/owncloud/client/pull/8101 (2.7+)
