### ISSUE TITLE
.desktop file contains ~800 unnecessary lines

### ISSUE THREAD

**Issue by inputsh** [owncloud/client#5767]
### Expected behaviour

`.desktop` file needs to have like 10 lines of code + translations.

### Actual behaviour

`.desktop file contains ~800 of necessary files, in this order:

    # Translations
    
    
    # Translations
    ...

So, one line with the translations caption, two blank lines, repeated all the way down to line 805, under which there are actual translations. 

Thought it might be the Nextcloud theming, but nope. See https://github.com/owncloud/client/blob/master/mirall.desktop.in

### Steps to reproduce
1. Install ownCloud / Nextcloud client on Ubuntu-based distro
2. `cd /usr/share/applications`
3. `less owncloud-client.desktop`

### Server configuration
Operating system: N/A

Web server: N/A

Database: N/A

PHP version: N/A

ownCloud version: N/A

Storage backend (external storage):

### Client configuration
Client version: Nextcloud 2.3.1

Operating system: Ubuntu GNOME 17.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): can't figure out where it says

Client package (From ownCloud or distro) (Linux only): Nextcloud PPA

Installation path of client: 

    $ whereis nextcloud
    nextcloud: /usr/bin/nextcloud /usr/share/nextcloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

N/A

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

N/A

2. Web server error log:

N/A

3. Server logfile: ownCloud log (data/owncloud.log):

N/A

**Comment by michaelstingl** [comment]
Looks like @owncloud-bot adds a new line every night.

<img width="696" alt="client_mirall_desktop_in_at_master_ _owncloud_client" src="https://cloud.githubusercontent.com/assets/214010/25961281/0b16301a-367a-11e7-8d6f-270c0383b9f7.png">

**Comment by SamuAlfageme** [comment]
Yup, I checked with @DeepDiver1975 some time ago if it was @owncloud-bot's fault:

```
samuel      10:36 AM  I noticed in the client repo is duplicating a comment over and over: https://github.com/owncloud/client/blob/master/mirall.desktop.in#diff-5432296e16dadebb5595f3ec652209ee
samuel      10:42 AM  only when the client's name change
deepdiver 10:55 AM  this is transifex by itself - the bot is only executing the tx command
```

... but it's more an issue with the Transifex CLI client for the API, I'll make sure to check there.

**Comment by SamuAlfageme** [comment]
Also, we should remove the `Icon` entry on that file from the potentially translatable strings in Transifex to remove some more duplicated lines when we fix this.

**Comment by SamuAlfageme** [comment]
Awaiting feedback from the Transifex support team.

**Comment by ckamm** [comment]
I've removed the extra lines. The rest will need to be done for 2.4

**Comment by ogoffart** [comment]
They are comming back with each transifex commit.

**Comment by guruz** [comment]
I guess @SamuAlfageme was not notified yet :-/
https://github.com/transifex/transifex-client/issues/173

**Comment by SamuAlfageme** [comment]
@guruz @ogoffart nopes 😕 

@nelefth ping?

**Comment by ckamm** [comment]
They're still coming back, I removed some more during the placeholder merge. I'd close this as it is from upstream and doesn't have noticable negative effects (unless you open the .desktop file).

**Comment by aleksandar-todorovic** [comment]
@ckamm I agree that it doesn't have any easily spottable negative effects an average Joe (since average users don't look at `.desktop` files), but I do believe that this issue should remain open until the bot is fixed, since its behavior directly affects a file in this repository and every Linux install of the client for at least a year now.

I guess you could keep deleting the extra lines and consider this as a minor annoyance task for the team, but unless there's a repository in which one can report a faulty code running @owncloud-bot, I can't think of a better place for this issue. A quick skim through the bot's commit history seems to indicate that this is the only affected file across all of the Owncloud repositories.

**Comment by SamuAlfageme** [comment]
@aleksandar-todorovic it was actually reported on https://github.com/transifex/transifex-client/issues/173 (as read above) - since that's what @owncloud-bot runs behind the scenes.

**Comment by guruz** [comment]
Commented on https://github.com/transifex/transifex-client/issues/173#issuecomment-460235329

**Comment by TheOneRing** [comment]
Fixed
