### ISSUE TITLE
[Linux] bandwidth limiting is disabled in latest packages

### ISSUE THREAD

**Issue by xkill** [owncloud/client#5769]
The download limits are disabled.

This could be duplicated of https://github.com/owncloud/client/issues/4334 but it is closed and I cannot reopen it.

See https://github.com/owncloud/client/issues/4334#issuecomment-301019559 for more information.

![Screenshot Network Tab with Bandwidth options disabled](http://storage8.static.itmages.com/i/17/0512/h_1494578974_8672438_773c2f226f.png)

**Comment by SamuAlfageme** [comment]
@xkill I can reproduce, will look into it. Thanks for reporting!

**Comment by SamuAlfageme** [comment]
I was running a Qt4 based-build on the previous test 'cause I get messed up with the testpilot ed. I've just tried with https://software.opensuse.org/download.html?project=isv:ownCloud:devel:Qt562&package=owncloud-client and running `apt-get autoremove` && `apt-get autoclean` and the network limits are enabled again. 

@xkill what does appear in the "About" section of your client?

![info](https://cloud.githubusercontent.com/assets/2644445/25840283/8184b130-349b-11e7-8588-02ecd6e2862c.gif)

Which version of Qt is it using?, even though we're seeing that it installed the new `oc-` Qt5 packages. 

Thanks!

**Comment by xkill** [comment]
```
# dpkg -l | grep -P "owncloud|oc-\w*qt5"
ii  libowncloudsync0:amd64                      2.3.2-1.1                                                                        amd64        the ownCloud sync library
ii  oc-libqt5concurrent5:amd64                  5.6.2-88.1                                                                       amd64        Qt 5 concurrent module
ii  oc-libqt5core5a:amd64                       5.6.2-88.1                                                                       amd64        Qt 5 core module
ii  oc-libqt5dbus5:amd64                        5.6.2-88.1                                                                       amd64        Qt 5 D-Bus module
ii  oc-libqt5designer5:amd64                    5.6.2-1                                                                          amd64        Qt 5 designer module
ii  oc-libqt5designercomponents5:amd64          5.6.2-1                                                                          amd64        Qt 5 Designer components module
ii  oc-libqt5gui5:amd64                         5.6.2-88.1                                                                       amd64        Qt 5 GUI module
ii  oc-libqt5network5:amd64                     5.6.2-88.1                                                                       amd64        Qt 5 network module
ii  oc-libqt5opengl5:amd64                      5.6.2-88.1                                                                       amd64        Qt 5 OpenGL module
ii  oc-libqt5opengl5-dev:amd64                  5.6.2-88.1                                                                       amd64        Qt 5 OpenGL library development files
ii  oc-libqt5printsupport5:amd64                5.6.2-88.1                                                                       amd64        Qt 5 print support module
ii  oc-libqt5sql5:amd64                         5.6.2-88.1                                                                       amd64        Qt 5 SQL module
ii  oc-libqt5sql5-sqlite:amd64                  5.6.2-88.1                                                                       amd64        Qt 5 SQLite 3 database driver
ii  oc-libqt5test5:amd64                        5.6.2-88.1                                                                       amd64        Qt 5 test module
ii  oc-libqt5widgets5:amd64                     5.6.2-88.1                                                                       amd64        Qt 5 widgets module
ii  oc-libqt5xml5:amd64                         5.6.2-88.1                                                                       amd64        Qt 5 XML module
ii  oc-qt5-default:amd64                        5.6.2-88.1                                                                       amd64        Qt 5 development defaults package
ii  oc-qt5-qmake:amd64                          5.6.2-88.1                                                                       amd64        Qt 5 qmake Makefile generator tool
ii  owncloud-client:amd64                       2.3.2-1.1                                                                        amd64        The ownCloud sync client - github.com/owncloud/client
ii  owncloud-client-l10n                        2.3.2-1.1                                                                        all          Internationalization files for ownCloud

# lsb_release -a
LSB Version:	core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

!()[http://storage2.static.itmages.com/i/17/0516/h_1494951131_7616473_6312920bbb.png]

It is obtained following the instructions on https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

The package installed is:
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/amd64/owncloud-client_2.3.2-1.1_amd64.deb

What I have to do to fix it?

**Comment by jnweiger** [comment]
the packages at isv:ownCloud:desktop do not know anything about the new ocqt562-* packages.
You may try a wrapper like this:
<pre>
cat /usr/bin/testpilotcloud
#!/bin/sh

# Wrapper to start the correct owncloud binary with proper preinitializations.
export LD_LIBRARY_PATH=/opt/ownCloud/testpilotcloud/lib64:/opt/ownCloud/testpilotcloud/lib:/opt/ownCloud/testpilotcloud/lib/x86_64-linux-gnu:/opt/ownCloud/testpilotcloud/lib/x86-linux-gnu:/opt/ownCloud/qt-5.6.2/lib64:/opt/ownCloud/qt-5.6.2/lib:/opt/ownCloud/qt-5.6.2/lib/x86_64-linux-gnu:/opt/ownCloud/qt-5.6.2/lib/x86-linux-gnu:$LD_LIBRARY_PATH

exec /opt/ownCloud/testpilotcloud/bin/testpilotcloud "$@"
</pre>
