### ISSUE TITLE
Linux: allow to add files to a shared folder

### ISSUE THREAD

**Issue by parrenin** [owncloud/client#5773]
### Expected behaviour
The linux owncloud client should allow the option to add files to a shared folder.

### Actual behaviour
This is actually not possible with the linux client, but it is possible with the http client.

### Steps to reproduce
1.  Create a folder in your owncloud folder 
2.  Right-click and select "share with owncloud"
3.  => the "allow modification" option is not permitted

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:
2.3.2
Operating system:
Linux
OS language:
French
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by hodyroff** [comment]
Hm, this works for me perfectly. But I am running the new QT5.6 packages already. Can you test: https://build.opensuse.org/repositories/isv:ownCloud:testpilot:nightly

**Comment by SamuAlfageme** [comment]
Yup, just checked on Ubuntu 16.04 and there it is the "Change" (aka "allow modification" option):

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/26151006/4634ea66-3b01-11e7-9c2c-b7a6460aa49f.png"/>
</p>
