### ISSUE TITLE
[Sharing Dialog] [OSX, Windows] Adjust the layout when a file cannot be shared

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5774]
The layout of the new sharing dialog is not wrapping the error message when the target file/folder cannot be shared: 
![screenshot 2017-05-16 16 23 16](https://cloud.githubusercontent.com/assets/2644445/26111255/ea507ca8-3a54-11e7-85e3-d2574b68f2bb.png)

### Steps to reproduce
1. Disable sharing on an external storage mountpoint
2. Try to share a file from that storage in the client

**Comment by ckamm** [comment]
Looks good on Linux, possibly OSX only?

**Comment by SamuAlfageme** [comment]
Windows also: 

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/26150538/106dd8f4-3aff-11e7-9797-f4bdf91726bf.png"/>
</p>

**Comment by SamuAlfageme** [comment]
Clarification, text is wrapping after: 8da7919a4375990c69569c56de5a17ff1464ded4 but the layout looks overlapping: 

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/26204046/d6857838-3bdd-11e7-8fd4-25dfeb4ed4e7.png"/>
</p>

**Comment by ckamm** [comment]
PR #5781

**Comment by SamuAlfageme** [comment]
Following the comments in https://github.com/owncloud/client/pull/5781, there's still a layout problem with the container widget box on macOS when there's no tabs to display: 

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/26244158/f1e34806-3c8e-11e7-9f0f-eccc08801fc8.png"/>
</p>

Also,

> I think https://github.com/owncloud/client/pull/5781/commits/21fa9be560eac12542469fffed870ef2982a4999 is hiding the OS's default icon displayed on the sharing dialog unless the thumbnail from the server is fetched. 

| pre- | post- |
|:---:|:--------------------:|
| ![screenshot 2017-05-22 12 29 09](https://cloud.githubusercontent.com/assets/2644445/26307370/6fe8785e-3ef4-11e7-9dcc-1d36d7d9eb58.png) | ![post](https://cloud.githubusercontent.com/assets/2644445/26307361/64c4e930-3ef4-11e7-9d01-3e8f9986c0fb.png) |

**Comment by ckamm** [comment]
@guruz This is about the small dark-grey box in the upper left corner. I don't get it on Linux. It needs debugging on OSX, so I'd give the issue to you.

**Comment by ckamm** [comment]
@SamuAlfageme The "default icon isn't used" bug was fixed by 91f6cae168d5aa17d36f9403c2388cc25fa7fdaf

**Comment by SamuAlfageme** [comment]
@ckamm completely forgot about this one. Thx a bunch.

**Comment by SamuAlfageme** [comment]
🤙 fantastic: 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/40191247-2b946d06-5a01-11e8-84e9-4fef2b9b8ed5.png"/>
</p>

Also, client now (https://github.com/owncloud/client/pull/6330) avoids displaying the (useless) informative dialog when this happens even earlier, _at context-menu time_: 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/40191310-5cd5e782-5a01-11e8-810e-0327ad92a958.png"/>
</p>
