### ISSUE TITLE
[Feature request]Put back symlink support as power option

### ISSUE THREAD

**Issue by g1franc** [owncloud/client#5776]
Title: Put back desktop client symlink support as a power option

Category: Client/Desktop (Windows)

Link to Central topic (and/or GitHub issue if applicable):

Quick summary of the use case: Put back support for symbolic link in windows desktop client as with an option, hidden option or command line option

Problem it solves / why you think this is important: In the past the desktop client was supporting symbolic link and it was a a very nice feature. But due to the lack of knowledge of some users, it was removed from the client to avoid loop during file tree hierarchy building. 
Could you please add it back ?
It is really useful to add folders outside of the synchronized folder. 
Best would be to add it as option, (hidden or not) or like a feature needed an specific argument from the command line. This would prevent end-users creating loop with symlink to use it but still allow power users to have the wonderful nice feature. If power user, activate symlink support but create loop -> too bad for them, fight itself.

Any special treatment/checks for symlink could be drop as responsibility would be transferred to user and no more developers.

**Comment by SamuAlfageme** [comment]
Hey @g1franc you can share your good points (including it as expert option) in https://github.com/owncloud/client/issues/5019, some users are in favor of including junctions back and support there in the issue could bring attention back on focus.

Closing here as duplicate.
