### ISSUE TITLE
[Sharing Dialog][oC 8.2.X] Public links cannot be deleted/edited

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5777]
### Actual behavior
The new sharing dialog (https://github.com/owncloud/client/pull/5695) is not including the `<share_id>` at the end of the URL on`DELETE`/`PUT` requests. 

#### Client Request:
```
curl \
    -H 'Ocs-APIREQUEST:true' \
    -H 'Content-Type:application/x-www-form-urlencoded' \
    -H 'User-Agent:Mozilla/5.0 (Macintosh) mirall/2.4.0-nightly20170509 (build 4255)' \
    [...]
    -H 'Host:<server>' \
    -X DELETE 'http://<server>/ocs/v1.php/apps/files_sharing/api/v1/shares/?format=json'
```

#### Server Reply:
```
{
    "ocs": {
        "data": [],
        "meta": {
            "message": "Invalid query, please check the syntax. API specifications are here: http://www.freedesktop.org/wiki/Specifications/open-collaboration-services. DEBUG OUTPUT:\n",
            "status": "failure",
            "statuscode": 999
        }
    }
}
```
![screenshot 2017-05-17 09 53 10](https://cloud.githubusercontent.com/assets/2644445/26145266/257cb4d0-3aec-11e7-87da-f92df08878f3.png)

### Expected behavior
The right (legacy) endpoint would be: 
```
-X DELETE 'http://<server>/ocs/v1.php/apps/files_sharing/api/v1/shares/<share_id>?format=json'
```

**oC Server > 9.0 is not affected by this.**

### Steps to reproduce
1. Create a new public link on a server older than 9.0 
2. Remove it

**Comment by ckamm** [comment]
Nice catch, I'll take care of it.

**Comment by ckamm** [comment]
PR: https://github.com/owncloud/client/pull/5780

**Comment by SamuAlfageme** [comment]
👍
