### ISSUE TITLE
[Sharing Dialog] Disable sharing options if capabilities report "api_enabled": false

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5778]
### Expected behavior

When the capabilities call report: 

```
"files_sharing": {
    "api_enabled": false,
    "public": {
        "enabled": false
    }
```

the client could disable the sharing tabs from the dialog the same way it's done with the ["Users and Groups" tab for servers <8.2.0](https://github.com/owncloud/client/blob/master/src/gui/sharedialog.cpp#L181-L190).

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/26153185/93fc1aea-3b0a-11e7-94cc-16b0f392dd56.png"/>
</p>

#### ~~Exception: Users/Groups in Federated Shares enabled~~
~~Don't really know why but Federated Shares fall outside of "Sharing API" but yet it does. So, if the server reports:~~

```
"federation": {
    "outgoing": true,
...
```

~~...the Users/Group tab should be enabled.~~

### Actual behavior
Both tabs are displayed, giving the user the feeling that sharing is enabled. This way we can avoid errors from happening:

| Lookup errors | Public Link creation |
|:-------------:|:--------------------:|
| ![no_result](https://cloud.githubusercontent.com/assets/2644445/26153322/15d42ce2-3b0b-11e7-8f59-e74d752639f3.png) | ![sharing failed](https://cloud.githubusercontent.com/assets/2644445/26153527/06b97f22-3b0c-11e7-9eb0-832c57fcc1e8.png) |

### Steps to reproduce
1.  Disable "Allow apps to use the Share API" on Settings > Admin > Sharing
2. "Share with ownCloud" from the desktop client

**Comment by ckamm** [comment]
This should already happen for link sharing (the tab is visible, but disabled), but it doesn't seem to work in practice. Will investigate.

**Comment by ckamm** [comment]
@SamuAlfageme Currently, when the share api is disabled, but federated outgoing is enabled, the client shows a "the server doesn't allow sharing" message and displays no tabs. This is consistent with what the server does: when share API is disabled, no sharing buttons are displayed in the file app.

You're suggesting `share_api: false, federated: {outgoing: true}` should show the user share dialog? That doesn't seem right to me.

**Comment by ckamm** [comment]
PR https://github.com/owncloud/client/pull/5779

**Comment by SamuAlfageme** [comment]
@ckamm 

> Currently, when the share api is disabled, but federated outgoing is enabled, the client shows a "the server doesn't allow sharing" message and displays no tabs.

I've just checked and you're right; my problem was the time it takes for the client to get the new capabilities. Once they're updated, the message is correct. 

> You're suggesting `share_api: false, federated: {outgoing: true}` should show the user share dialog? That doesn't seem right to me.

Nope, I'm actually really confused on why the federated shares fall out of the "Sharing API" switch, precisely because of what you explained: 

> when share API is disabled, no sharing buttons are displayed in the file app.

Maybe we should raise a core ticket. I wrote it as a exception since I believe I saw the client being able to share using federation while the API was disabled (in the same time window as explained before). I just checked via cURL and nope, even when:

```
"federation": {
    "outgoing": true,
    "incoming": true
    }
```

... the server replies with a 404: `"message": "Share API is disabled"`. Pretty weird.
