### ISSUE TITLE
Selective sync may not locally remove unneeded files

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#5783]
When a folder is removed from the sync by deselecting it in the selective sync ui, typically it is deleted locally. However, when there are new, conflicting or untracked files inside the folder, nothing at all is done with it. Discussions with @ogoffart suggest that removing all subitems that are safe to remove may be more desirable.

Steps to reproduce:
* Inside a synced folder, create a folder `foo/` containing `foo/uptodate`, `foo/subfolder/uptodate`.
* Fully sync it, then pause the sync
* Create a new file `foo/newfile`
* Open selective sync and deselect `foo/`
* Unpause the sync

Expected: `foo/uptodate`, `foo/subfolder/uptodate` and `foo/subfolder` should be removed
Actual: Nothing is removed

This behavior is the result of `checkForPermission()`: All subitems inside a selective-sync ignored folder get set to `IGNORED`. But even if they weren't: as long as the parent is `IGNORED` subjobs are not executed in `PropagateDirectory`.

**Comment by ogoffart** [comment]
Test case in TestSyncEngine::testSelectiveSyncBug  :  parentFolder/subFolder/fileA.txt  should be deleted but it is not.

**Comment by guruz** [comment]
What would be the milestonde for this @ogoffart @ckamm ?

**Comment by ckamm** [comment]
I've tested it using the test case from the initial comment
