### ISSUE TITLE
addtitional info: link to owncloud.com

### ISSUE THREAD

**Issue by stkjj** [owncloud/client#5784]
### Expected behaviour
Additional info about the Desktop Client

### Actual behaviour
a link to the main page of owncloud.com
### Steps to reproduce
take a look at the attached screenshot ;-)

### Server configuration
doesn't matter

### Client configuration
Client version: 2.3.2 

![bildschirmfoto 2017-05-19 um 14 01 52](https://cloud.githubusercontent.com/assets/832642/26246986/247e7f76-3c9c-11e7-8091-60a40eb5f7c3.jpg)

a link to doc.owncloud.org or a dedicated page for the client would be more helpful

**Comment by SamuAlfageme** [comment]
@stkjj you just need to open the tray menu to find: 

![help](https://cloud.githubusercontent.com/assets/2644445/26247390/f50cdbbe-3c9d-11e7-8b34-7b336cd392ba.png)

**Comment by stkjj** [comment]
yes  I know. But that does not make the shown link better ;-)
