### ISSUE TITLE
[Sharing Dialog] Password set is lost when using return key on the expiration date field

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5788]
### Expected behavior
Editing the "Expiration Date" via keyboard on a public link share should not have any collateral effects on the password. 

### Actual behavior
Hitting return on that field causes a `PUT` request with `'password='` as payload, disabling the password on the share. 

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/26305632/655c18cc-3ef0-11e7-8370-4abe77ed7af8.gif"/>
</p>

### Steps to reproduce
1. Set a pass on a public link share
2. Click on the "expiration date" input field 
3. Hit return (editing the date or not)

**Comment by ckamm** [comment]
This does not happen on Linux. I assume the problem is that "Set password" still has keyboard focus on OSX and that hitting enter triggers it. I'll work around the issue by disabling the button when no new password was entered.

**Comment by SamuAlfageme** [comment]
👍
