### ISSUE TITLE
[Sharing Dialog] Simplify the user/group sharing permissions/attributes handling 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5797]
If in the future, more fine-grained options can be introduced in the sharing permissions/attributes via core-functionality or apps (ideally, announcing it via a corresponding capability). The permission handling on the desktop's native sharing dialog could be simplified to fit all these options while keeping it clean.

- [ ] Remove the "can" from "can share"/"edit" for a cleaner UI (like it happens with "change", "create" and "delete")
- [ ] Move all the extended permissions to a different "share settings" dialog, that can easily fit new check-boxes and additional options. 

An initial proposal I came up with: 

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/26541771/647a28e2-4457-11e7-95d0-28adcbdad2e5.png"/>
</p>

| No extended permissions | No extra actions (ext.perm. nor "additional") |
|:-----------------------:|:----------------------------------------:|
| ![no_ext_permissions](https://cloud.githubusercontent.com/assets/2644445/26542474/46b1fe40-445a-11e7-826a-4991d15f7f51.png) | ![no_extra_actions](https://cloud.githubusercontent.com/assets/2644445/26542449/2aa83a16-445a-11e7-8f54-4d618caf443b.png) |

cc/ @ckamm @michaelstingl @pmaier1

**Comment by SergioBertolinSG** [comment]
The way the sharing api is done currently would require different dialogs for regular shares and public shares. In public shares you can add expiration date, a password and the option of public upload.

**Comment by SamuAlfageme** [comment]
@SergioBertolinSG we already have the different dialogs covered with the multitab "Share with ownCloud" (see above for "Users and Groups" and "Public Links" tabs).

This one is just about the Private share, in order to move the extended permissions or future new attributes for the share (e.g. expiration date) to a different dialog to both simplify and allow bulk edition of these. This is how it is right now:

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/26628116/1a84fe54-45fd-11e7-8b58-d6d7d78a35ba.gif"/>
</p>

**Comment by SergioBertolinSG** [comment]
Ah yes, didn't see it before. 

Ok, adding that will require changes in the sharing api and some automated tests in core  before adding it to the client.

**Comment by SamuAlfageme** [comment]
@SergioBertolinSG yeah, https://github.com/owncloud/core/issues/11642 has to happen before the expiration date gets there, into the client.

**Comment by michaelstingl** [comment]
@SamuAlfageme @ckamm Expiration date for user/group shares planned for oC server 10.0.5: https://github.com/owncloud/enterprise/issues/2001#issuecomment-332617932

**Comment by TheOneRing** [comment]
The sharing dialog is considered deprecated
