### ISSUE TITLE
Qt5Core.dll Error Runtime on start owncloud client win10

### ISSUE THREAD

**Issue by woofix** [owncloud/client#5802]
Nom de l’application défaillante owncloud.exe, version : 2.3.2.6928, horodatage : 0x00000000
Nom du module défaillant : Qt5Core.dll, version : 5.6.2.0, horodatage : 0x3e343e27
Code d’exception : 0x40000015
Décalage d’erreur : 0x00010cae
ID du processus défaillant : 0x1048
Heure de début de l’application défaillante : 0x01d2d9150df62a4c
Chemin d’accès de l’application défaillante : C:\Program Files (x86)\ownCloud\owncloud.exe
Chemin d’accès du module défaillant: C:\Program Files (x86)\ownCloud\Qt5Core.dll
ID de rapport : 8ef17498-0878-4d4d-a324-7f6a869bc3ce

**Comment by SamuAlfageme** [comment]
Hey @woofix! Please stick to the [issue template](https://github.com/owncloud/client/blob/master/.github/issue_template.md) in order for us to track down your issue. 

If you have more info on the problem, feel free to reopen.
