### ISSUE TITLE
libtestpilotcloudsync.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by C138** [owncloud/client#5803]
### Expected behaviour
Tell us what should happen

Tespilotcloud-client running ... ;-)

### Actual behaviour
Tell us what happens instead
root@phoenix:~# testpilotcloud
/opt/ownCloud/testpilotcloud/bin/testpilotcloud: error while loading shared libraries: libtestpilotcloudsync.so.0: cannot open shared object file: No such file or directory
### Steps to reproduce
1. install testpilotcloud-client from http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/nightly/xUbuntu_16.04 

try to run.

### Server configuration
Operating system:  Ubuntu 16.04
testpilotcloud-client:
  Installé : 2.3.3~git20170529-1
  Candidat : 2.3.3~git20170529-1
  Table de version :
 *** 2.3.3~git20170529-1 500
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/nightly/xUbuntu_16.04  Packages

Of course :
~# ldd /opt/ownCloud/testpilotcloud/bin/testpilotcloud | grep not
	libtestpilotcloudsync.so.0 => not found

dpkg -S libtestpilotcloudsync.so.0
libtestpilotcloudsync0:i386: /opt/ownCloud/testpilotcloud/lib/i386-linux-gnu/libtestpilotcloudsync.so.0

May be a pointrelated to LDD_LIBRARY_PATH definition... [of course] could be patched with a symbolic and ugly link  ;-)

Anyway, this shoud work out of the box isn't it ?

Thanks

**Comment by SamuAlfageme** [comment]
Hey @C138 I've just installed that nightly testpilotcloud version and didn't run into any lib problems, works out of the box:

![screenshot 2017-05-30 13 08 33](https://cloud.githubusercontent.com/assets/2644445/26580626/384bc130-4539-11e7-8d40-556b5d141d2f.png)

Do you come from a previous installation, or is it a clean one? Do you have the installation output? 

These new packages come with some differences in matter of dependencies and libraries nomenclature. If the problem persists, maybe you can try to remove previous stale installations and try to install from scratch:
```
# apt-get purge testpilotcloud-client
# apt-get autoremove
# apt-get autoclean
# apt-get install testpilotcloud-client
```

**Comment by C138** [comment]
Hi
* Was a fresh install  (first time I heard about testpilotowncloud...)
* Doing a reinstall, same problem.
note : is 'apt-get autoclean' really needed ? it removes thunderbird and vlc for me ;-)
  
* I have "patched" ldconfig by adding /opt/ownCloud/testpilotcloud/lib/i386-linux-gnu in the ld conf files, and now it works (as expected ;-)

ldd /opt/ownCloud/testpilotcloud/bin/testpilotcloud | grep /opt | grep -v qt-5.6.2
	libtestpilotcloudsync.so.0 => /opt/ownCloud/testpilotcloud/lib/i386-linux-gnu/libtestpilotcloudsync.so.0 (0xb5065000)
	libocsync.so.0 => /opt/ownCloud/testpilotcloud/lib/i386-linux-gnu/testpilotcloud/libocsync.so.0 (0xb2de8000)

(without configuring ld) I wonder : 
* why /opt/ownCloud/qt-5.6.2/lib/i386-linux-gnu libraries are correctly found
* why those in /opt/ownCloud/testpilotcloud/lib are not found

Thanks

**Comment by jnweiger** [comment]
purge is important, so that config files get removed. autoclean should help getting dependencies removed. If it kills your thunderbird, you better look for *oc562* packages manually.

@SamuAlfageme did you notice that @C138 is on a 32bit system?

**Comment by jnweiger** [comment]
with the 64bit environment in Ubuntu 16.04:
We have /usr/bin/testpilotcloud as a shell script that sets up the correct LD_LIBRARY_PATH
We have /opt/ownCloud/testpilotcloud/bin/testpilotcloud which almost gets everything without the help of LD_LIBRARY_PATH, except one thing:
<pre>ldd /opt/ownCloud/testpilotcloud/bin/testpilotcloud | grep 'not found'
	libtestpilotcloudsync.so.0 => not found
</pre>

When I try to call that binary directly without the shell script wrapper I can reproduce the same error message: /opt/ownCloud/testpilotcloud/bin/testpilotcloud: error while loading shared libraries: libtestpilotcloudsync.so.0: cannot open shared object file: No such file or directory

**Comment by jnweiger** [comment]
@C138 I can reproduce the issue on a 32bit system, exactly as you describe it.

**Comment by C138** [comment]
Hi everyone,
* "Wrong" architecture was an hypothesis I didn't even mention in my previous report  (sorry)
* and I also didn't think of looking at bin/testpilotcloud ... where the real cause of my trouble is clearly written ;-)
Thanks for helping.
Suppose that the script can be improved for next releases.
The issue can be closed (and BTW, there are not so much 32bits machine around me ;-)
