### ISSUE TITLE
csync failed to access and duplicate folders

### ISSUE THREAD

**Issue by Maikie86** [owncloud/client#5804]
Seems the bug below has not been reported yet and more and more people are having the same problem 

https://central.owncloud.org/t/csync-failed-to-access-and-duplicate-folders/6071

**Comment by SamuAlfageme** [comment]
Hey @Maikie86, it was opened some days ago in https://github.com/owncloud/core/issues/28018  and a fix is already in the making (https://github.com/owncloud/core/pull/28022), keep an eye in the core issue for updates.

As it's not strictly an issue on the desktop client (see https://github.com/owncloud/core/issues/28018#issuecomment-304270786) let's close it here. 

Thanks for reporting! 😉
