### ISSUE TITLE
Disable the external storages/big folders notice on account log-out

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5809]
### Steps to reproduce
1. Add a new external storage/folder exceeding the size limit set on the client
2. Get notified in the account tab
3. Don't select any option and log-out

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/26641105/cef20a86-4629-11e7-8eb5-a131ef73d4bc.png"/>
</p>

### Expected behavior
The options should be gone after log-out, the same way the selective sync list is. 

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/26641230/394c86f4-462a-11e7-8059-72c24bd00795.gif"/>
</p>

**Comment by ckamm** [comment]
PR https://github.com/owncloud/client/pull/5826

**Comment by SamuAlfageme** [comment]
Still reproduces in `Version 2.5.0alpha1 (build 9885)` - my concerns from the comments on https://github.com/owncloud/client/pull/5826 are still valid - e.g.

1. Wait till the buttons appear
2. Log out / disable the network on the OS 
3. Click on `Synchronize all`
4. Log in / re-enable the connection on the host
5. **Client lost the selection** 

I'm still voting for the "_if we don't display the selective sync list at all, do not display these buttons until connection is established back either_"

**Comment by ckamm** [comment]
@SamuAlfageme Checking it out. Possibly my change only covered the case of edits to the selective sync list, not the "big folder" edit state.

**Comment by SamuAlfageme** [comment]
Now, this is great stuff:

![hide_external](https://user-images.githubusercontent.com/2644445/41593688-302089d4-73c1-11e8-8a17-6c8b7d00cf20.gif)

Closing here! 🤘

**Comment by ckamm** [comment]
Finally! :)
