### ISSUE TITLE
Cant Sync From Windows Shared Folder Mounted on Ubuntu

### ISSUE THREAD

**Issue by kingmxiii** [owncloud/client#5812]
### Expected behaviour
I should be able to sync all files located in a Window Shared folder mounted trough CIFS on Ubuntu 16.10
### Actual behaviour
When I try to sync the Client Crash. I tried syncing from a local folder and the client works

### Steps to reproduce
1. Mount a Windows share folder on Ubuntu with CIFS
2. Setup Owncloud client to point to the Windows Shared Folder

### Server configuration
Operating system: Ubuntu 16.04

Web server: Apache

Database: MariaDB

PHP version: 

ownCloud version: 10.0.1.5

Storage backend (external storage): No

### Client configuration
Client version: 2.3.2-1.1

Operating system: Ubuntu 16.10

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

06-01 18:20:53:421 0x564bd4033330 csync_statedb_query: sqlite3_prepare: BUSY counter: 118
06-01 18:20:53:521 0x564bd4033330 csync_statedb_query: sqlite3_prepare: BUSY counter: 119
06-01 18:20:53:621 0x564bd4033330 csync_statedb_query: sqlite3_prepare: BUSY counter: 120
06-01 18:20:53:622 0x564bd4033330 csync_statedb_query: Gave up waiting for lock to clear
06-01 18:20:53:622 0x564bd4033330 csync_statedb_query: sqlite3_compile error: database is locked - on query PRAGMA quick_check;
06-01 18:20:53:622 0x564bd4033330 csync_statedb_load: ERR: sqlite3 integrity check failed - bail out: database is locked.
06-01 18:20:53:625 0x564bd3102fd0  #### ERROR during  csync_update :  "CSync failed to load the journal file. The journal file is corrupted." 
06-01 18:20:53:626 0x564bd3102fd0 void OCC::SyncJournalDb::close() "/media/ocshare/01-SITE CODES_ SITE INFO/._sync_d6d0e436b7dc.db" 
06-01 18:20:58:634 0x564bd3102fd0 ERROR committing to the database:  "database is locked" 
06-01 18:20:59:084 0x564bd3102fd0 CSync run took  17505 
06-01 18:20:59:085 0x564bd3102fd0  - client version 2.3.2  Qt 4.8.7 
06-01 18:20:59:085 0x564bd3102fd0 -> SyncEngine finished with ERROR 
06-01 18:20:59:091 0x564bd3102fd0 OO folder slotSyncFinished: result:  2 
06-01 18:20:59:091 0x564bd3102fd0     * owncloud csync thread finished with error 
06-01 18:20:59:092 0x564bd3102fd0 the last 1 syncs failed 
06-01 18:20:59:191 0x564bd3102fd0 Sync state changed for folder  "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" :  "Error" 
06-01 18:20:59:391 0x564bd3102fd0

**Comment by SamuAlfageme** [comment]
Hey @kingmxiii looks like some process might be hanging and locking your DB, try using `fuser` to determine which:

```
$ fuser ._sync_d6d0e436b7dc.db
._sync_d6d0e436b7dc.db: 1680
```

... and kill it to see if that solves your problem. If not, you can always delete your sync journal (this will make you loose your selective sync preferences, in case you want to make a backup first) and the client will restore it next time it runs. 

Hope this helps!

**Comment by kingmxiii** [comment]
@SamuAlfageme It is only being used by the Owncloud Process Which I suppose it is ok. Thanks for the reply.!

**Comment by kingmxiii** [comment]
I think the problem it might be that the file is getting locked. When I check the File Opened on Windows Share Sessions I can see that there are 3 locks on the file. Perhaps there is a flag or option that I have to use for the cifs mount to avoid locking the files.

**Comment by kingmxiii** [comment]
It is working now. I have to set a "nolock" option on the cifs command.
