### ISSUE TITLE
[OAuth2] When opening the browser for authentication, the account wizard displays no content and allows forward navigation 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5813]
Relates to: https://github.com/owncloud/client/issues/5811

### Steps to reproduce
1. Use the URL of a server with [OAuth app](https://github.com/owncloud/oauth2) active in the account wizard. 
2. Clicking on the tray icon brings back the wizard with no content but the navigation buttons

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/26722198/3887a350-478f-11e7-9f5d-169d5eb20cee.png"/>
</p>

* If `next >` is selected, wizard will take you to next page where it fails to connect **but create the local sync folder**.
* If `Skip folders configuration` is selected next without authenticating in the browser, a _userless_ account will be created (i.e. `@<server.tld>` on the account tab, etc.)

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/26723316/43a44888-4794-11e7-9564-d21ed3692a77.png"/>
</p>

### Expected behavior
- [x] Display a spinner or some other component to inform the user that an action is required (maybe also a button to relaunch the browser in case it was closed by mistake)
- [ ] Still offer the "Application Password" option as a fallback from OAuth.

<p align="center">
  <img src="https://cloud.githubusercontent.com/assets/2644445/26723048/ed2c6eaa-4792-11e7-84f6-a15dbb458d32.png"/>
</p>

- [x] Change the behavior of the buttons:
    * `Cancel`: will close the wizard and discard the account creation (e.g. if the user forgot the password and wants to stop the action for good) 
    * `Back` will allow to go back to wizard's first page to change the URL in case of mistake.

cc/ @ogoffart

**Comment by guruz** [comment]
I'm thinking this should be higher priority, maybe even mandatory for 2.4.0
What do you think @pmaier1 @ogoffart @tomneedham @lukebier @joneug  ?

**Comment by joneug** [comment]
I agree!

**Comment by Emil-G** [comment]
"Still offer the "Application Password" option as a fallback from OAuth." - Do you know if this will be server configurable to force OAuth and block Application Password?

**Comment by SamuAlfageme** [comment]
Status with @ogoffart's tweaks: https://github.com/owncloud/client/pull/5825:

| Wizard waiting for browser | OAuth flow error |
|:-----------------------:|:----------------------------------------:|
| ![screenshot 2017-06-12 09 36 35](https://user-images.githubusercontent.com/2644445/27023404-aeed74c8-4f52-11e7-9f7e-fc9e5ca89bb9.png) | ![screenshot 2017-06-12 09 30 15](https://user-images.githubusercontent.com/2644445/27023405-aeeff5c2-4f52-11e7-8876-b1fac7b728b3.png) |

As for the 

> Still offer the "Application Password" option as a fallback from OAuth.

> I can't imagine a use case, where Application Password is required instead of OAuth2. Fallback for what?

You're right. I agree we could drop the application password support for the client and restrict it's use to authenticate with WebDAV clients (see this (2FA use-case example)[https://support.google.com/accounts/answer/185833?hl=en]) or other software that does not implement all auth methods **we currently support**. 

However, **If and only if** the server announces and supports basic auth. as well, we could **temporarily** offer support for it as fallback for the OAuth application malfunctioning to avoid the user being locked out of his account. As said, as a temporary solution until the OAuth workflow is reliable enough to wrap all authentication flows, when it'd not only be prioritized, but the only method if the server supports it.

**Comment by guruz** [comment]
Some more error handling requested by @SamuAlfageme : https://github.com/owncloud/client/pull/5668#issuecomment-307722242

**Comment by butonic** [comment]
might confuse users and this is important since we need it for SAML scenarios: p1

**Comment by SamuAlfageme** [comment]
Closing here as this is ready, merged and tested 👍 

Follow-up issues for some more OAuth aspects in https://github.com/owncloud/client/issues/5847 & https://github.com/owncloud/client/issues/5848
