### ISSUE TITLE
Disable update notification

### ISSUE THREAD

**Issue by rugk** [owncloud/client#5814]
When using the system update tool (linux package manager) to update the client, one gets a notification "Version x.y of the NextCloud client is available. Use your system update tool to update."

However, there is no option to disable this check/this notification, because the notification is largely useless. If your distro/package manager has not yet released an update, there is no need to annoy the user with a notification.
And when an update is really available, you can a notification from your system update tool, anyway…

So there should at least be a way to disable it.

**Comment by ogoffart** [comment]
There is a hidden configuration option already that does that:  "skipUpdateCheck"

**Comment by rugk** [comment]
Okay and where can this hidden option be set/specified/changed?

BTW the topic of this issue is, IMHO, to disable it by default (so to set this option to true) when a "system tool" is needed for updating.

**Comment by guruz** [comment]
-> https://doc.owncloud.org/desktop/2.3/autoupdate.html#preventing-automatic-updates-in-linux-environments

**Comment by guruz** [comment]
> BTW the topic of this issue is, IMHO, to disable it by default (so to set this option to true) when a "system tool" is needed for updating.

This is an interesting argument, but users might still be interested in knowing that they run an out-dated version.. :)
