### ISSUE TITLE
Access unsnyced folders / files when online

### ISSUE THREAD

**Issue by eglipeter** [owncloud/client#5815]
As a feature request it would be nice if folders which are excluded from syncronization are visible and accessible in the file explorer (especially in the Windows explorer) if the computer is online. When a user with an active connection to the Owncloud servers accesses his owncloud folder, the client would then start downloading the file from the server. After a change, the updated version is uploaded and the local file gets removed. 

What I think of is a functionality like in the mobile client for iOS. In my understanding this would be a "superposition" of WebDAV and Local synchronization.

**Comment by hodyroff** [comment]
Yes. https://github.com/owncloud/client/issues/4341
Closing as duplicate. It is getting more popular generally.
