### ISSUE TITLE
give log an universal name so it not confuses with nextcloud users

### ISSUE THREAD

**Issue by MegaV0lt** [owncloud/client#5816]
I am using the nextcloud server (Debian) and the nextcloud windowsclient. In the local datafolder there are log files named owncloud*

![](http://pix.toile-libre.org/upload/original/1496679708.png)

To keep it simple and universal just rename it to .sync.log or something similar

See also: https://github.com/nextcloud/client_theming/issues/112#issuecomment-306218546

**Comment by SamuAlfageme** [comment]
Duplicated of https://github.com/owncloud/client/issues/5675. This will be in for 2.4 (see milestone)
