### ISSUE TITLE
Waiting too long during credential dialog leads to disconnect

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#5818]
As reported by @leobase in https://github.com/owncloud/client/issues/5714#issuecomment-303708463:

Typical situation:
* Start the computer
* The account credential dialog pops up
* Let it sit there for >5min
* Enter the password
* No synchronization is happening

We should usually be able to disable client-side timeouts during these dialogs, but might still hit server-side timeouts.

This should also affect the SSL certificate dialog.

**Comment by ogoffart** [comment]
I could not reproduce the problem.
