### ISSUE TITLE
Triggering log in should re-ask about previously rejected certificates

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#5819]
Suggested by @SamuAlfageme  in https://github.com/owncloud/client/issues/5728#issuecomment-305225953:

Currently rejecting a certificate is permanent for the duration the client is running. So the client will never ask about a certificate again if it was rejected once unless the client is restarted.

What if the client asked again when the user explicitly triggers the "log in" action?

**Comment by ogoffart** [comment]
Patch: https://github.com/owncloud/client/pull/5835

**Comment by ckamm** [comment]
I've tested it.
