### ISSUE TITLE
Updating windows app overwrites sync-exclude.lst

### ISSUE THREAD

**Issue by suamikim** [owncloud/client#5820]
Custom changes in the file `sync-exclude.lst` are overwritten during automatic updates of the sync client.

Please don't overwrite the `sync-exclude.lst` file when performing an automatic uninstall of the current version in the course of an client update.

I just had to manually delete a lot of files since the file has been overwritten and stuff has been uploaded/downloaded to and from clients erroneously since i wasn't aware of this until now. Also I'm pretty sure that I'm going to "trap" into this again during future updates...

**Comment by ogoffart** [comment]
You mean the global sync-exclude.lst?   This one is not supposed to be edited by hand.  There is a local file that contains the actual config (editable from the dialog) that should not be overwritten by an update.

**Comment by suamikim** [comment]
Yes, I'm talking about the global `sync-exclude.lst` which is located in the clients install dir. Where is the local file located? Using the editor in the app is no real solution for me since I have to add ~ 70 entries on multiple machines and the editor only allows me to add 1 entry at a time...

**Comment by ogoffart** [comment]
That would be in %LOCALAPPDATA%\ownCloud\sync-exclude.lst
