### ISSUE TITLE
Client Package - Checksums & GPG Signing

### ISSUE THREAD

**Issue by jaredledvina** [owncloud/client#5824]
Reopening https://github.com/nextcloud/client_theming/issues/26#issuecomment-306215169 here copy the original post below:

> This seemed like the appropriate place, but let me know if I should file this else where.
> 
> Could Nextcloud publish the md5/sha256/sha512 of the published Nextcloud client here:
> https://download.nextcloud.com/desktop/releases/Mac/Installer/
> 
> If this matched the type's available for the server releases that'd be great!
> 
> If possible, it'd be great to have the checksum files signed with Nextcloud's GPG key.

Let me know if I'm missing any info, happy to fill in the blanks!

**Comment by guruz** [comment]
> This seemed like the appropriate place

You are completely right, you were in the right repo to submit this issue :-)

This here is the wrong one
