### ISSUE TITLE
Windows desktop client stops to sync on random big folders

### ISSUE THREAD

**Issue by marcos-guerrero** [owncloud/client#5829]
Server 9.1.6 , Windows desktop client  2.3.2 (build 6928)

When create a new account on the client we choose YES on "Ask sync folders bigger than " 500Mb and NO on "Ask sync folders on external storage" , that are the options I have in the general settings

![image](https://user-images.githubusercontent.com/13331362/26964231-d79be30a-4cf0-11e7-8a40-52ccff77a5b1.png)

Once the account is set up, the client gives a warning about one folder bigger than 500Mb (the user has indeed lot of Gb that are placed in one and only one big big big folder called ROOT)

Then I choose only to sync the folder /ROOT/Refs/15/10/151085 (and all of its subfolders) that are 26Gb.

The sync starts, and 

### Expected behaviour
the expect behaviour : the client downloads all the files contained in the path I chose without any other warning about big folders

### Actual behaviour
after a while downloading files, the sync pauses and the same warning about a big folder is showed:

![image](https://user-images.githubusercontent.com/13331362/26964533-411a2b92-4cf2-11e7-8729-75635482a32d.png)

Why does the sync stop on the "07_Gestion de compras (PO)" folder to ask me again? 
(I know that nobody else is adding files or folders on the /ROOT/Refs/15/10/151085 that initially selected for sync and the  "07_Gestion de compras (PO)" folder already was there and had 5,2Gb ... 
Why does the sync stop on this folder to ask and not on the others that are bigger than 500Mb?

this behaviour is happening in other big folders, and I can't get the pattern on why happens neither on what folders are choosen by the client to ask again for sync

### Steps to reproduce
As I told
### Server configuration
Operating system: Ubuntu 16.04

Web server: 
Apache 2.4

Database:
MariaDB 10.1
PHP version:
7.0.15
ownCloud version:
9.1.6
Storage backend (external storage):
Yes, external storage : local 
### Client configuration
Client version:
2.3.2
Operating system:
Windows 10
OS language:
Spanish
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

[owncloudsync.log.txt](https://github.com/owncloud/client/files/1063238/owncloudsync.log.txt)

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
This is indeed funny.
Both that dialogue and the syncing are using ```http://owncloud.org/ns:size``` to determine the size.

Is this from a new client sync directory? Because maybe you previously selected some things which makes the client just sync this?

Could you give us the contents of your client's sync directory ._sync_*.db file ```selectivesync``` table?

**Comment by marcos-guerrero** [comment]
Yes, it's a new client sync, as I told. New account, first sync (as I told in the first post) and I select EVERYTHING under the folder:

"Then I choose only to sync the folder /ROOT/Refs/15/10/151085 (and all of its subfolders) that are 26Gb."

And after a while the sync pauses to ask about to sync the "07_Gestion de compras (PO)" that was previously selected and had already 5,2Gb

About the content of the selectivesync table... here it goes! But let me repeat the issue, because now I already checked the "07_Gestion de compras (PO)" to continue the sync 
[selectivesync.csv.txt](https://github.com/owncloud/client/files/1063488/selectivesync.csv.txt)


I'll do a fresh start and capture the database at the beginning when " I choose only to sync the folder /ROOT/Refs/15/10/151085 (and all of its subfolders) that are 26Gb", and capture again when the sync stops to ask for a folder that was already selected for sync

**Comment by ogoffart** [comment]
This issue is really strange to me.  Especially because i see no special pattern in this folder compared to the other.

Can you please try to reproduce and dump the content of the `selectivesync` table
 - Right before you accepted the parent big folder.
 - Right after you accepted the parent big folder.
 - When the clients asks you again for a child folder (before you check it). (normally it should be the same as in the previous step, but who knows)

**Comment by marcos-guerrero** [comment]
Of course is strange, and funny, that's why I'm opening the issue. This is happening to several users on random folders , the only pattern is that always happens on big folders, tenths of Gb .
I'm trying to repeat the issue, but not alway happens, and not always in the same place. Meanwhile, I can tell you in advance that the client is right now in the middle of the sync of the entire  /ROOT/Refs/15/10/151085 folder  (there are already lot of files downloaded) ...
 
![image](https://user-images.githubusercontent.com/13331362/26971945-bf6167d2-4d0f-11e7-893d-2be375c23914.png)


![image](https://user-images.githubusercontent.com/13331362/26971914-9d733da8-4d0f-11e7-8321-4a6883817728.png)

but in selectivesync table still no rows refering to those subfolders already downloaded. 

[selectivesync.txt](https://github.com/owncloud/client/files/1063743/selectivesync.txt)

**Comment by marcos-guerrero** [comment]
Sorry, I don't have enough time yet to do a complete report. Please, stay tuned, I'll be back soon with more info

**Comment by ogoffart** [comment]
Any news?

**Comment by marcos-guerrero** [comment]
Hi!
I apologize for not to be able to get all the info I promised.

I gave instructions to the user who was suffering the issue about what files, screenshots and explanations had to get ... and I still waiting, so maybe is not happening any more...
Maybe it's better to close the issue, and I promise to reopen the issue in case I have all the info you requested to me.

**Comment by guruz** [comment]
thanks @marcos-guerrero  let's do that.
