### ISSUE TITLE
docker file url linked from client/admin/win/docker/ not found 

### ISSUE THREAD

**Issue by goshdark138** [owncloud/client#5832]
http://download.opensuse.org/repositories/windows:/mingw/openSUSE_42.1/windows:mingw.repo

**Comment by guruz** [comment]
Could you please file a complete bug report ;)

Which docker file? Where did you see this link? etc

**Comment by goshdark138** [comment]
client/admin/win/docker/

**Comment by dschmidt** [comment]
Maybe the repo was renamed, the correct link seems to be: http://download.opensuse.org/repositories/windows:/mingw/openSUSE_Leap_42.1/windows:mingw.repo

We should consider updating to a newer openSUSE though, current stable release would be 42.3 with:
http://download.opensuse.org/repositories/windows:/mingw/openSUSE_Leap_42.3/windows:mingw.repo

**Comment by goshdark138** [comment]
I build the client but it does not work
Install but generate errors in libraries
Run the test with the nextcloud client and generate the same error

HELP PLEASE

![388261f7af076528a37e778c24cb150af00153a9](https://user-images.githubusercontent.com/10076619/27166046-a402bc46-515d-11e7-9b92-c4e006127bd7.png)

**Comment by goshdark138** [comment]
share the build
https://www.dropbox.com/s/3z8y5pc65qmoxpr/Nextcloud-2.3.2.1beta-setup.exe?dl=0

**Comment by guruz** [comment]
For building help, please ask on https://help.nextcloud.com

This is a tracker for bugs/features, not support.

**Comment by jnweiger** [comment]
You are building with gcc7. This does not work. The libraries from our mingw toolchain require gcc-6.x - please try again with a downgraded compiler.

**Comment by goshdark138** [comment]
@jnweiger where change gcc7 to gcc-6.x -

**Comment by SamuAlfageme** [comment]
Solved in https://github.com/owncloud/client/pull/5900 

See https://central.owncloud.org/t/building-the-windows-installer/8403 for an temporary workaround to the https://github.com/owncloud/client/issues/5832#issuecomment-314589158 above.
