### ISSUE TITLE
I build the client but it does not work

### ISSUE THREAD

**Issue by goshdark138** [owncloud/client#5841]
I build the client but it does not work

Both in owncloud and in nextcloud the same error occurs

https://www.dropbox.com/s/3z8y5pc65qmoxpr/Nextcloud-2.3.2.1beta-setup.exe?dl=0

**Comment by guruz** [comment]
Please don't attach .exe files to this issue tracker. How can we know you don't send a virus?

For building help, try https://central.owncloud.org

This is a tracker for bugs/features, not support.
