### ISSUE TITLE
[Shell Extensions] [Windows, macOS] Provide context menu options for private link handling

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5842]
Follow-up of https://github.com/owncloud/client/pull/5763 to extend it up to the rest of platforms. 

Assigning @jturcotte here as shell-extensions all-star 😁

**Comment by ckamm** [comment]
@jturcotte The details are best seen in the nautilus or dolphin integration changes done in https://github.com/owncloud/client/pull/5763, direct link: https://github.com/owncloud/client/pull/5763/files#diff-9db1a5f75704bbe2b3ca76fc057d2633

Roughly:
* Use `GET_STRINGS` to get the translated names of the new actions
* Build a context menu containing the new actions
* Send `COPY_PRIVATE_LINK` or `EMAIL_PRIVATE_LINK` when the actions are selected

**Comment by ckamm** [comment]
I think this is done!
