### ISSUE TITLE
[Linux] - File does not get discovered when local sync dir on CIFS mount

### ISSUE THREAD

**Issue by kingmxiii** [owncloud/client#5846]
### Expected behaviour
it should detect files changes in a reasonable amount of time.

### Actual behaviour
At some point The client stop Checking for changes and It goes into some sort of infinite loop. 

### Steps to reproduce
1. Map a Windows Shared Drive with CIFS
2. Install a Run OC Desktop Client for Ubuntu 17.04
3. Let it run for some time. 

### Server configuration
Operating system:
Ubuntu 16.04
Web server: 
Apache
Database:
MariaDB
PHP version:
7.0
ownCloud version:
10.0.2
Storage backend (external storage):

### Client configuration
Client version:
2.3.2
Operating system:
Ubuntu 17.10
OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
```
06-16 11:55:25:671 0x55eacede4fd0 void OCC::SyncJournalDb::walCheckpoint() took 0 msec 
06-16 11:55:25:671 0x55eacede4fd0 void OCC::SyncJournalDb::commitInternal(const QString&, bool) Transaction commit  "All Finished."  
06-16 11:55:25:755 0x55eacede4fd0 void OCC::SyncJournalDb::close() "/media/ocshare/Dropbox/._sync_d6d0e436b7dc.db" 
06-16 11:55:25:755 0x55eacede4fd0 No database Transaction to commit 
06-16 11:55:26:900 0x55eacede4fd0 CSync run took  426243 
06-16 11:55:26:901 0x55eacede4fd0 virtual OCC::BandwidthManager::~BandwidthManager() 
06-16 11:55:28:130 0x55eacede4fd0  - client version 2.3.2  Qt 4.8.7 
06-16 11:55:28:138 0x55eacede4fd0 -> SyncEngine finished without problem. 
06-16 11:55:28:153 0x55eacede4fd0 OO folder slotSyncFinished: result:  3 
06-16 11:55:28:154 0x55eacede4fd0 Sync state changed for folder  "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" :  "Success, some files were ignored." 
06-16 11:55:28:155 0x55eacede4fd0 another sync was requested by the finished sync, this has happened 11 times 
06-16 11:55:28:355 0x55eacede4fd0 <===================================== sync finished for  "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" 
06-16 11:55:43:168 0x55eacede4fd0 # Check whether authenticated propfind works. 
06-16 11:55:43:170 0x55eacede4fd0 !!! OCC::PropfindJob created for "https://ibccloud.ironbo.com" + "/" "OCC::ConnectionValidator" 
06-16 11:55:55:965 0x55eacede4fd0 void OCC::ActivityListModel::startFetchJob(OCC::AccountState*) Start fetching activities for  "ibcadmin@ibccloud.ironbo.com" 
06-16 11:55:55:967 0x55eacede4fd0 !!! OCC::JsonApiJob created for "https://ibccloud.ironbo.com" + "ocs/v1.php/cloud/activity" "OCC::ActivityListModel" 
06-16 11:55:55:969 0x55eacede4fd0 !!! OCC::JsonApiJob created for "https://ibccloud.ironbo.com" + "ocs/v2.php/apps/notifications/api/v1/notifications" "OCC::ServerNotificationHandler" 
06-16 11:56:11:168 0x55eacede4fd0 * Trying to check "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" for changes via ETag check. (time since last sync: 43 s) 
06-16 11:56:11:172 0x55eacede4fd0 Scheduling "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" to check remote ETag 
06-16 11:56:11:179 0x55eacede4fd0 !!! OCC::RequestEtagJob created for "https://ibccloud.ironbo.com" + "/" "OCC::Folder" 
06-16 11:56:41:168 0x55eacede4fd0 * Trying to check "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" for changes via ETag check. (time since last sync: 73 s) 
06-16 11:56:41:171 0x55eacede4fd0 Scheduling "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" to check remote ETag 
06-16 11:56:41:171 0x55eacede4fd0 !!! OCC::RequestEtagJob created for "https://ibccloud.ironbo.com" + "/" "OCC::Folder" 
06-16 11:57:11:168 0x55eacede4fd0 * Trying to check "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" for changes via ETag check. (time since last sync: 103 s) 
06-16 11:57:11:169 0x55eacede4fd0 Scheduling "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" to check remote ETag 
06-16 11:57:11:169 0x55eacede4fd0 !!! OCC::RequestEtagJob created for "https://ibccloud.ironbo.com" + "/" "OCC::Folder" 
06-16 11:57:41:168 0x55eacede4fd0 * Trying to check "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" for changes via ETag check. (time since last sync: 133 s) 
06-16 11:57:41:168 0x55eacede4fd0 Scheduling "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" to check remote ETag 
06-16 11:57:41:168 0x55eacede4fd0 !!! OCC::RequestEtagJob created for "https://ibccloud.ironbo.com" + "/" "OCC::Folder" 
06-16 11:58:11:168 0x55eacede4fd0 * Trying to check "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" for changes via ETag check. (time since last sync: 163 s) 
06-16 11:58:11:168 0x55eacede4fd0 Scheduling "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" to check remote ETag 
06-16 11:58:11:169 0x55eacede4fd0 !!! OCC::RequestEtagJob created for "https://ibccloud.ironbo.com" + "/" "OCC::Folder" 
06-16 11:58:41:168 0x55eacede4fd0 * Trying to check "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" for changes via ETag check. (time since last sync: 193 s) 
06-16 11:58:41:168 0x55eacede4fd0 Scheduling "https://ibccloud.ironbo.com/remote.php/dav/files/ibcadmin/" to check remote ETag 
06-16 11:58:41:168 0x55eacede4fd0 !!! OCC::RequestEtagJob created for "https://ibccloud.ironbo.com" + "/" "OCC::Folder" 
```

2. Web server error log:
No Error
3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
Your log does not really show a loop? :)

You need to show what triggers the new sync. The ```RequestEtagJob``` is normal maintenance jobs before the sync, not an actual sync

Or do you want to say it does not check anymore for new files? (so not a loop in a sense of a syncing loop)

Which files does it not detect, the ones on the server?

Have you tried to scan on the server? https://doc.owncloud.org/server/9.1/admin_manual/configuration_server/occ_command.html#file-operations-label

**Comment by kingmxiii** [comment]
I'm sorry I probably misinterpreted the process. But the Begining of the log is the last time my client synced files to the server. Then it will go to "Trying to Check ..." forever. Thats not the whole log. And i did not see any error on it. I will put some files from the client on the syncing folder and the client wont detect the changes. What seems to work is to pause and Restart syncing from the client menu.

**Comment by guruz** [comment]
I was thinking you had the CIFS mount in the ownCloud server.

But I think you have it in your linux client and have your local linux sync folder configured to be on the CIFS mount?

**Comment by kingmxiii** [comment]
Yes thats correct the CIFS mount is on the Client.

**Comment by guruz** [comment]
Ah you also had reported https://github.com/owncloud/client/issues/5812 before..

**Comment by kingmxiii** [comment]
#5812 Was a different issue. In that Issue the client was not able to access the db file because it was being locked by cifs mount. I was able to solve that problem with some research. And in that case I was able to detect an Error message.

**Comment by hodyroff** [comment]
Is there a reason you are not using a Windows Client on the Windows Server to sync with the ownCloud Server? How large is the mount?

**Comment by kingmxiii** [comment]
@hodyroff I tried running the desktop client on Windows Server 2012 But the client was crashing all the time. According to some topics in the forum, it is because the windows client is 32 bits. That's why I am trying the Ubuntu Client. The Data size is 2.7 TB For one user.

**Comment by hodyroff** [comment]
If you can reproduce this for Windows Server we might rather investigate into this one. Actually you need to run the client with NSSM over there, as otherwise when the user is logged out of the server it will not crash but correctly stop working. https://help.dattodrive.com/hc/en-us/articles/218238018-Configure-DattoDrive-application-to-run-as-a-Service

**Comment by hodyroff** [comment]
also discussed here https://github.com/owncloud/client/issues/1581

**Comment by guruz** [comment]
@kingmxiii Did you get this to work by now? 
Seem to be a known issue with CIFS.. https://github.com/docker/for-win/issues/56

@jvillafanez would you agree that this is not possible with CIFS mounts on the client?

**Comment by jvillafanez** [comment]
I'm not sure how the client detects the changes, so I don't think I'll be helpful here.

My recommendation is to remove ownCloud from the list of variables and check how Inotify or whatever mechanism you want to use behaves as isolated as possible. If Inotify doesn't detect changes properly in the same environment, don't expect the ownCloud (if it's using Inotify behind the scenes) will behave better.

**Comment by ogoffart** [comment]
Closing old issue
