### ISSUE TITLE
[OAuth2] - Error handling on authentication errors

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5847]
As pointed out in https://github.com/owncloud/client/issues/5813 there's some more error handling logic to be included on the auth. workflow **once it's ready on the app/core**; e.g. depends on:

- [ ] https://github.com/owncloud/oauth2/issues/46
- [ ] ~~https://github.com/owncloud/oauth2/issues/47~~ https://github.com/owncloud/core/issues/28129
- [ ] https://github.com/owncloud/oauth2/issues/49 (this was the original cause of https://github.com/owncloud/client/pull/5668#issuecomment-307722242)

(Migrating the tags from https://github.com/owncloud/client/issues/5813)

**Comment by ogoffart** [comment]
I believe most of the issues should not be fixed.
Please re-open tasks for specific issues.
