### ISSUE TITLE
Qt build missing libxkbcommon-x11 support for remote owncloud execution from XQuartz

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5849]
Problem: 

On MacOSX with XQuartz installed. From Terminal ssh -Y to a Centos7 box and run owncloud from there. The keyboard input is broken and pressing keys has no effect. Graphics are rendered OK.

This was checked with owncloud 2.3.2.

This case is similar to reported here: https://bugreports.qt.io/browse/QTBUG-39910

**Comment by guruz** [comment]
Which package are you using for the linux client?
Which Qt version does it claim to use?

**Comment by moscicki** [comment]
Our 2.2.4 version comes with Qt 5.4:
```
	libQt5Widgets.so.5 => /opt/qt-5.4/lib64/libQt5Widgets.so.5 (0x00007f55b7558000)
	libQt5Network.so.5 => /opt/qt-5.4/lib64/libQt5Network.so.5 (0x00007f55b73fe000)
	libQt5Xml.so.5 => /opt/qt-5.4/lib64/libQt5Xml.so.5 (0x00007f55b73c1000)
	libQt5WebKitWidgets.so.5 => /opt/qt-5.4/lib64/libQt5WebKitWidgets.so.5 (0x00007f55b737a000)
	libQt5Sql.so.5 => /opt/qt-5.4/lib64/libQt5Sql.so.5 (0x00007f55b7338000)
	libQt5DBus.so.5 => /opt/qt-5.4/lib64/libQt5DBus.so.5 (0x00007f55b72b2000)
	libcernboxsync.so.0 => /lib64/libcernboxsync.so.0 (0x00007f55b6f7e000)
	libQt5WebKit.so.5 => /opt/qt-5.4/lib64/libQt5WebKit.so.5 (0x00007f55b4b5f000)
	libQt5Gui.so.5 => /opt/qt-5.4/lib64/libQt5Gui.so.5 (0x00007f55b45e7000)
	libQt5Concurrent.so.5 => /opt/qt-5.4/lib64/libQt5Concurrent.so.5 (0x00007f55b45e0000)
	libQt5Core.so.5 => /opt/qt-5.4/lib64/libQt5Core.so.5 (0x00007f55b409f000)
```

**Comment by SamuAlfageme** [comment]
@moscicki you can try to upgrade to current 2.3.3 nightly (_soon to be released_: https://software.opensuse.org/download.html?project=isv:ownCloud:community:nightly&package=owncloud-client) which includes the self-built Qt5.6.2 dependencies and might solve the issue. 

I remember running that version inside an Ubuntu container & X11 forwarding over OS X without much issue (with a few tweaks on the X11 config though: http://bit.ly/2tJ5oe0)

**Comment by moscicki** [comment]
@SamuAlfageme : yes, indeed, this keyboard problem is fixed with the nightly. that's very promising indeed!

Side note: the owncloud executable from this nightly requires the environment to point to /opt/qt-5.4. 
It does not set it up so by default it does not start complaining about missing .so (Centos 7). I had to set the environment by hand to make it work. Is this expected?

In the past there used to be a bash script that was sourced automatically by owncloud executable which was a wrapper: /op/qt-4.8/bin/qt-4.8-env.sh

**Comment by guruz** [comment]
@moscicki Are you sure you checked correctly using ldd? The nightly should ship Qt 5.6.2

**Comment by moscicki** [comment]
@guruz, @SamuAlfageme: my bad (it got installed from EPEL, hence the environment note above which I crossed out).

I tried the nigtly and it looks good. The keyboard problem is gone as well with the nightly.
```
#owncloud --version
ownCloud version 2.4.0git (build 74)
Using Qt 5.6.2, built against Qt 5.6.2
Using 'OpenSSL 1.0.1e-fips 11 Feb 2013'
```

**Comment by michaelstingl** [comment]
@moscicki Thanks for your feedback!
