### ISSUE TITLE
chunked uploads: Don't mix upload V1 and NG

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5850]
probably because of dynamic job creation

Placeholder issue, @mrow4a and me are aware

**Comment by mrow4a** [comment]
Pr which should solve the issue - https://github.com/owncloud/client/pull/5852 - it is not dynamic jobs creaton, it was dynamic chunking. 

Just also merged smashbox PR which will test new and old endpoints https://github.com/owncloud/smashbox/pull/162, in chunked/non-chunked/conflict/share/reshared/etc scenarios

**Comment by guruz** [comment]
Grrrreat!
