### ISSUE TITLE
Get sync state programmatically

### ISSUE THREAD

**Issue by floli** [owncloud/client#5851]
Hello,

is is possible to get the state of a running owncloud client programmatically? e.g. using a command line tool or a socket?

OS of interest is Linux.

Best Thanks!

**Comment by guruz** [comment]
Yes, there is the socket used by the file manager plugins. Please check the source for that.
https://github.com/owncloud/client/tree/master/shell_integration

There is also the GUI testing that @dschmidt attempted at https://github.com/owncloud/client/pull/5682/files

**Comment by floli** [comment]
Is there some documentation for the socket API or just the source code of the clients?

Thx.

**Comment by guruz** [comment]
I just found/remembered this: https://github.com/owncloud/client/wiki/Overlay-Icons

But I guess "the source is the documentation" might be more true nowadays

**Comment by floli** [comment]
Just saw that the nauitlus subdir has a python implementation, that should work as source doc.

**Comment by guruz** [comment]
What's your goal by the way? :)

**Comment by floli** [comment]
Showing the sync status in i3pystatus, alongside with dropbox / git-annex or any other long running processes that may or may not be busy, see https://github.com/enkore/i3pystatus/issues/324
