### ISSUE TITLE
Send a unique X-Request-ID header to allow tracing requests in apache and owncloud logs.

### ISSUE THREAD

**Issue by butonic** [owncloud/client#5853]
https://github.com/owncloud/core/pull/28144 has been merged. It will use the value of a `X-Request-ID` header as the request id in log files to allow linking events on the client to events in the apache and owncloud logs.

- [x] generate a string to use as unique id.
  - 20-200 chars
  - only `[a-zA-Z0-9-+/_=.:]` allowed
- [x] use it in the client log
- [x] send it as `X-Request-ID` header on every request

**Comment by ckamm** [comment]
@butonic @ogoffart Should this id be saved in the config file? Identifying clients across restarts would be handy for debugging sometimes, but the down side would be that you could identify clients across restarts. (and some people copy config files around, leading to clients with the same request ids)

**Comment by ckamm** [comment]
PR https://github.com/owncloud/client/pull/5897

**Comment by ckamm** [comment]
Closed because I tested with mitmproxy and I don't think it needs an extra verification step.

**Comment by guruz** [comment]
Re-opened as there was a misunderstanding between us..
