### ISSUE TITLE
Error while syncing chunked files: server replied: Precondition failed (An If-Match header was specified and the resource did not exist)

### ISSUE THREAD

**Issue by umgfoin** [owncloud/client#5854]
I'm adding a reference to [this nextcloud issue](https://github.com/nextcloud/server/issues/5238) as it might be client-related.

### Expected behaviour
All files are synced.

### Actual behaviour
File upload starts and stops after some progress with error:
Certain files are not synced if upload is chunked.

### Steps to reproduce
1. Create a jpg with size 10.1 MB in a synced folder
2. Watch sync progress and log

### Server configuration
Operating system:
CentOS 6.9

Web server: 
nginx version: nginx/1.11.10

Database:
Postgres 9.6.3

PHP version:
PHP 7.1.6 (fpm-fcgi) 

ownCloud version:
Nextcloud 12.0.0

Storage backend (external storage):

### Client configuration
Client version:
Version 2.3.2beta (build 1).

Operating system:
Win7 x64

OS language:
DE

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile:
```
22.06.2017 15:03:29, InstantUpload/2017/06/2017-06-17 17-38-12 3036_stitch.jpg, Nextcloud,Error transferring https://<fqdn>/remote.php/dav/files/hias/InstantUpload/2017/06/2017-06-17 17-38-12 3036_stich.jpg-chunking-3292803479-2-0 - server replied: Precondition failed (An If-Match header was specified and the resource did not exist).
```

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):
```
Sabre\DAV\Exception\PreconditionFailed: HTTP/1.1 412 An If-Match header was specified and the resource did not exist
/var/www/<nondisclosed>/3rdparty/sabre/dav/lib/DAV/Server.php - line 474: Sabre\DAV\Server->checkPreconditions(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/<nondisclosed>/3rdparty/sabre/dav/lib/DAV/Server.php - line 254: Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))
/var/www/<nondisclosed>/apps/dav/lib/Server.php - line 253: Sabre\DAV\Server->exec()
/var/www/<nondisclosed>/apps/dav/appinfo/v2/remote.php - line 33: OCA\DAV\Server->exec()
/var/www/<nondisclosed>/remote.php - line 162: require_once('/var/www/<nondisclosed>...')
{main}
```

**Comment by guruz** [comment]
Sorry, this is for sure (99.9% chance) a nC server issue and has nothing to do with oC/nC client. 
Especially if it happens after a server upgrade as the linked issue said

> Cant sync - Precondition failed after upgrade from 11.0.2 to 12.0

**Comment by PVince81** [comment]
It could be what I observed here: https://github.com/owncloud/core/issues/28197

@umgfoin are the files that don't sync received shared files ? (direct file shares, not folder shares).
If yes, then it's the problem from https://github.com/owncloud/core/issues/28197

**Comment by PVince81** [comment]
Desktop client version owncloud-client-2.3.2-1.5.x86_64 on openSUSE Tumbleweed. for me

**Comment by umgfoin** [comment]
> are the files that don't sync received shared files ? (direct file shares, not folder shares).

No, unshared (instantUpload folder).
Although the error was shown (periodically with every sync attempt), the files were correctly uploaded.
Deleting and re-creating the file (in local filesystem), fixed the problem so far.

++umgfoin.

**Comment by PVince81** [comment]
Are these small files (< 10 MB) being overwritten by big files (> 10 MB) ?

**Comment by umgfoin** [comment]
Basically, they were created in the local file-system by photoshop (filesize > 10MB).  It is possible, that the initial sync succeeded and the errors appeared after successively saving modifications. The activity log shows an initial creation-event, but no update-events. Additionally, I'm unsure if photoshop creates a file in an atomic operation or several open/close/append steps.

**Comment by guruz** [comment]
@umgfoin You found a client bug after all :-)

Let's close in favor of https://github.com/owncloud/client/issues/5855

**Comment by guruz** [comment]
The nightly build for tomorrow should have this
