### ISSUE TITLE
Owncloud client not working con Centos 7.

### ISSUE THREAD

**Issue by dcialdella** [owncloud/client#5857]
### Expected behaviour
I updated Centos 7 and Owncloud-client did not work anymore.
I try to remove and install again, but never work again.

### Actual behaviour
Never show the GUI interface, no process running as owncloud

### Steps to reproduce
1. Centos 7 
2. update to last version (yum update)
3. install owncloud-client last version for Centos 7 
   (add isv repo, yum update   yum install owncloud.client)

### Server configuration
Operating system: Linux (not related to server).
with Xubuntu, Manjaro and Windows the server (installed in other server) works perfectly.

Web server: 

Database:

PHP version:

ownCloud version: 2.3.2

Storage backend (external storage):

### Client configuration
Client version:    Package owncloud-client-2.3.2-3.el7.x86_64 already installed and latest version 
Linux vmdac.localdomain 3.10.0-514.21.2.el7.x86_64 #1 SMP Tue Jun 20 12:24:47 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

Operating system: Centos 7 

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 

Client package (From ownCloud or distro) (Linux only): from both....

Installation path of client:
/usr/bin/owncloud 

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
owncloud --logwindow
owncloud: error while loading shared libraries: libqt5keychain.so.1: cannot open shared object file: No such file or directory

owncloud --version
owncloud: error while loading shared libraries: libqt5keychain.so.1: cannot open shared object file: No such file or directory

May be related to other library
Package qtkeychain-qt5-0.7.0-1.el7.x86_64 is obsoleted by opt-libqt5keychain1-0.7.0-9.4.x86_64 which is already installed

2. Web server error log:
no error in owncloud server

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by SamuAlfageme** [comment]
Hey @dcialdella! we had some build system turbulence in the past weeks that might have affected the integrity of the linux packages there. 

We're about to release into the stable channel some new packages that include all the work carried out for https://github.com/owncloud/client/issues/5470 (with self-cooked, dependencies), you can help us testing by installing them from the `nightly` repositories: 

https://software.opensuse.org//download.html?project=isv:ownCloud:community:nightly&package=owncloud-client

Try them out and tell us if they worked out for you!

**Comment by dcialdella** [comment]
I remove all RPMs related to Owncloud and installed it with these lines

cd /etc/yum.repos.d/
wget http://download.opensuse.org/repositories/isv:ownCloud:community:nightly/CentOS_7/isv:ownCloud:community:nightly.repo
yum install owncloud-client



Now is working again. Thanks !!!

**Comment by SamuAlfageme** [comment]
@dcialdella Great! Care to edit: https://github.com/owncloud/client/issues/5470#issuecomment-310981061 to point this out? 

Thanks for reporting!
