### ISSUE TITLE
Remove references to openSSL on the client build docs

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5858]
After https://github.com/owncloud/client/pull/5833, linking against openSSL (i.e.) on cmake is no longer needed. 

Build docs should be adapted consequently. (See https://central.owncloud.org/t/locally-built-client-error-creating-ssl-context/8264)

**Comment by ogoffart** [comment]
maybe i should not have removed the openssl instruction for windows.  The client itself does not need openssl,  but Qt still needs it
