### ISSUE TITLE
Tray icon "incorrect" on discovery phase

### ISSUE THREAD

**Issue by burner1024** [owncloud/client#5860]
### Expected behaviour
Tray icon should display a green tick **then and only then** when all files are synced and there are no errors or warnings. Thus, a situation like shown on screenshot must be impossible:
<img width="772" alt="1" src="https://user-images.githubusercontent.com/1279852/27569445-e4bd2a64-5b21-11e7-84e3-d9ebd268c51a.png">

### Actual behaviour
Tray icon is in "green/ok" state, but setting show "Checking for change/sync ongoing" icon

### Steps to reproduce
1. Launch Owncloud client
2. Click on tray icon > settings

### Server configuration
Operating system: Centos 7

Web server:  Nginx

Database: Mysql

PHP version: 5.5.38

ownCloud version: 9.1.5

Storage backend (external storage):

### Client configuration
Client version: 2.3.2

Operating system: Mac OS

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by SamuAlfageme** [comment]
Hm. Can you provide additional steps to reproduce/[client logs](https://doc.owncloud.org/desktop/2.3/troubleshooting.html#log-files) to better be able to determine what's going on? I cannot reproduce otherwise with the details provided.

Thanks for reporting!

**Comment by michaelstingl** [comment]
Currently this is _"works as designed"_ (see https://github.com/owncloud/client/issues/2432)

**Comment by burner1024** [comment]
No need for logs, then?

**Comment by SamuAlfageme** [comment]
@burner1024 nope! As @michaelstingl pointed out, it has to do with the discovery phase. We can discuss here (continuing from #2432) if this is something we want to change. I actually find it reasonable.

**Comment by guruz** [comment]
I agree with @burner1024

If the sync-trigger is a local file change, then the tray icon should switch immediately so that the user is aware that the client is working on syncing this.

**Comment by guruz** [comment]
Also mentioned by @mvglasow \ in https://github.com/owncloud/client/issues/5415
