### ISSUE TITLE
Link to central.owncloud.org leads to 404 in client

### ISSUE THREAD

**Issue by mghansen256** [owncloud/client#5862]
In the OwnCloud client under "General" (Allgemein in German) is a link to central.owncloud.org, leading to https://central.owncloud.org/c/help/desktop-file-sync, which gives an error 404 upon following the link.

### Client configuration
Client version: 2.3.2 build 6928
Operating system: Windows 7
OS language: German

**Comment by SamuAlfageme** [comment]
@mghansen256 indeed! central.owncloud.com categories were recently redone. I'm updating the link everywhere it appears in the repo. Thanks for the heads up! 

PR in https://github.com/owncloud/client/pull/5869
