### ISSUE TITLE
What protocol does Owncloud use for desktop sync and mobile sync?

### ISSUE THREAD

**Issue by jelimoore** [owncloud/client#5866]
I've heard chatter about csync being a major part of the desktop client but what is really going on under the hood? It can't use SFTP or the like since Owncloud is simply a PHP application.

**Comment by michaelstingl** [comment]
@jelimoore ownCloud uses WebDAV. Here you can find more information:
https://doc.owncloud.org/desktop/latest/architecture.html
https://github.com/cernbox/smashbox/blob/master/protocol/protocol.md

This is a tracker for bugs/features. The place for general discussion is https://central.owncloud.org .
