### ISSUE TITLE
Ubuntu repository: GPG error - key expired

### ISSUE THREAD

**Issue by sserdyuk** [owncloud/client#5877]
I followed the current and up-to-date instructions to install desktop client from a repo hosted at http://download.opensuse.org. I downloaded and installed the PGP key to white-list this repo. Unfortunately the current key is expired, so apt-get ignores the repo altogether.

```
$ wget -nv http://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_16.04/Release.key -O Release.key
2017-07-05 20:00:25 URL:http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/Release.key [1098/1098] -> "Release.key" [1]
$ sudo apt-key add - < Release.key
OK
$ sudo apt-get update
..... 
Hit:20 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  Release
Err:21 http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04  Release.gpg
  The following signatures were invalid: KEYEXPIRED 1496576244
Reading package lists... Done 
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04  Release: The following signatures were invalid: KEYEXPIRED 1496576244
W: Failed to fetch http://download.opensuse.org/repositories/home:/Horst3180/xUbuntu_16.04/Release.gpg  The following signatures were invalid: KEYEXPIRED 1496576244
W: Some index files failed to download. They have been ignored, or old ones used instead.

```

**Comment by jnweiger** [comment]
<pre>osc signkey --extend home:Horst3180</pre>
should do the trick, if I read the messages correctly.

**Comment by guruz** [comment]
@sserdyuk Any news?

@dragotin @jnweiger What is "Horst3180"? :)

**Comment by dragotin** [comment]
@guruz horst3180? Something nuclear powered. Secret!

**Comment by crrodriguez** [comment]
@dragotin @jw is correct.. this bug is invalid.. we extended our keys a while ago.. the relevant expired key is from Horst3180 home repository, not from isv:Owncloud.

Let's close this now.

**Comment by sserdyuk** [comment]
@crrodriguez You're correct. Sorry for the false alarm.

**Comment by repsorp** [comment]
Hi,

Today, Ubuntu 16.04 > sudo apt update returns the following error message:

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  Release: The following signatures were invalid: KEYEXPIRED 1543957762
W: Failed to fetch http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/Release.gpg  The following signatures were invalid: KEYEXPIRED 1543957762
