### ISSUE TITLE
Windows cross compile using docker failed with error File '/repositories/windows:/mingw/openSUSE_42.1/windows:mingw.repo' not found on medium 'http://download.opensuse.org/'

### ISSUE THREAD

**Issue by anzharip** [owncloud/client#5878]
I'm pulling the latest version of this branch. Commit ce8341ca1fd21d946e8c056430025f08d586e380. 

I'm following the guide from here: 
https://doc.owncloud.org/desktop/2.3/building.html#windows-installer-build-cross-compile

On step #1 I'm running this command: 
docker build . -t owncloud-client-win32:2.3

I got error: 
Step 7/15 : RUN zypper --non-interactive --gpg-auto-import-keys ar http://download.opensuse.org/repositories/windows:/mingw/openSUSE_42.1/windows:mingw.repo
 ---> Running in 98c7e1cef3d8
File '/repositories/windows:/mingw/openSUSE_42.1/windows:mingw.repo' not found on medium 'http://download.opensuse.org/'

I found that actually '/repositories/windows:/mingw/openSUSE_42.1/' doesn't exist. The one available is '/repositories/windows:/mingw/openSUSE_Leap_42.1/'. 

I changed line 11 on file 'client/admin/win/docker/Dockerfile' from this: 
RUN zypper --non-interactive --gpg-auto-import-keys ar http://download.opensuse.org/repositories/windows:/mingw/openSUSE_42.1/windows:mingw.repo

To this: 
RUN zypper --non-interactive --gpg-auto-import-keys ar http://download.opensuse.org/repositories/windows:/mingw/openSUSE_Leap_42.1/windows:mingw.repo

And the docker build process is working normally. 

### Expected behaviour
Tell us what should happen: 
The docker build process should be working normally. 

### Actual behaviour
Tell us what happens instead: 
It doesn't work with File '/repositories/windows:/mingw/openSUSE_42.1/windows:mingw.repo' not found on medium 'http://download.opensuse.org/' error message. 

### Steps to reproduce
1. Follow guide to cross compile windows client here: https://doc.owncloud.org/desktop/2.3/building.html#windows-installer-build-cross-compile
2. Follow step #1

### System configuration
Operating system:
macOS Sierra 10.12.5
Docker version 17.06.0-ce, build 02c1d87

Web server: 
n/a

Database:
n/a

PHP version:
n/a

ownCloud version:
Trying to build version 2.3

Storage backend (external storage):
n/a

**Comment by SamuAlfageme** [comment]
Hey @anzharip we're working to fix and update our cross-compilation toolchain ATM since it contains a problem with one of the libraries of the compiler.

In the meantime, you can read this thread https://central.owncloud.org/t/building-the-windows-installer/8403 to find a snapshot for the old image used and fix your issues. 

Thanks for reporting! I'll ping you here once the mainstream image it's fixed.

**Comment by anzharip** [comment]
Hi @SamuAlfageme, thanks for the prompt reply. Let me try your suggestion.
