### ISSUE TITLE
 Client should not use the same directory for different accounts

### ISSUE THREAD

**Issue by dartcafe** [owncloud/client#5883]
When setting up mutiple accounts, the client suggests the same local sync directory for all accounts, which could lead in mixing up the files of the synchronized accounts. The client should inform the user about the conflict, that if the selected directory is already in use by another account, when the user adds another account.

**Comment by hodyroff** [comment]
Originally we disallowed this. The we did allow it. Sounds like a good idea to give a small warning but most important we should use different default suggestions if we don't do this yet. I think people reported some other things with multi-account / same directory usage might be worth looking at the combination.

**Comment by phil-davis** [comment]
Have a read of #5597 - is it enough of a solution?

**Comment by SamuAlfageme** [comment]
@dartcafe the issue @phil-davis points at is precisely what you're looking for. It's already merged and will be included in version 2.4 (https://github.com/owncloud/client/blob/master/ChangeLog#L10) 

You can start testing it out with one of our nightlies: http://download.owncloud.com/desktop/daily/ 😉

**Comment by dartcafe** [comment]
I am satisfied. Maybe I will give it a try this evening, if I have time, cause I am preparing for vacation...
