### ISSUE TITLE
[Proxy Settings] Validate for empty hostname when manual proxy is selected

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5885]
### Expected behavior
Settings should not be able to set themselves to a non-valid config (i.e. no hostname when manual proxy selected). Error focus could be applied to the field to bring attention to it.

### Actual behavior
No error is displayed in Network tab, and "Host not found" error propagating to the account(s) tab(s):

![screenshot 2017-07-10 14 07 08](https://user-images.githubusercontent.com/2644445/28017388-4f77ca2e-6579-11e7-91c6-2dfbb2d4b663.png)

### Steps to reproduce
1. Select "Specify proxy manually as" 
2. Do not input a hostname

**Comment by SamuAlfageme** [comment]
@ckamm even when not the empty field has error-like focus:

![screen shot 2018-04-12 at 10 50 13](https://user-images.githubusercontent.com/2644445/38666507-600c9be0-3e3f-11e8-9f44-dba29ef6c123.png)

It's still possible to leave it empty - causing the "host not found" error as above.

**Comment by ckamm** [comment]
@SamuAlfageme I don't think so. If we want modal behavior for the settings they shouldn't be a non-modal page in the account settings in the first place. (but we won't make that change for 2.5)

Maybe I can improve the sync error message for the proxy with an empty hostname.

**Comment by SamuAlfageme** [comment]
@ckamm agreed - let's review the settings UI/arrangement on a future version, nothing to do for now. 

> Maybe I can improve the sync error message for the proxy with an empty hostname.

WFM - also make the error linked to the "Network" tab like we do with conflict warnings and "Activity > Not Synced" maybe?

**Comment by ckamm** [comment]
@SamuAlfageme This is a minor issue and I don't want to add complex ui for it. Currently what happens is that an empty proxy host gets treated as "no proxy" which seems ok to me: I guess that users would only ever leave this field empty if they wanted to unset the proxy, deleted the hostname but forgot to switch the combo box. 

I'd just leave this as-is. The most I'd do is set the ui to "no proxy" if the user leaves the network settings page without having filled in the hostname.

**Comment by SamuAlfageme** [comment]
@ckamm You're right - Sorry if I went down the over-engineering rabbit hole 😅 

> set the ui to "no proxy" if the user leaves the network settings page without having filled in the hostname.

Perfect!

**Comment by ckamm** [comment]
Let's track this minor change in the PR
