### ISSUE TITLE
Ubuntu packages are still built with Qt4

### ISSUE THREAD

**Issue by btittelbach** [owncloud/client#5886]
[Description updated to match the actual problem]

### Expected behaviour
The linux packages should use Qt 5.6 at least

### Actual behaviour
Some packages are still using Qt4,  and Qt4 bugs (such as the config file being erased) are still reproduced.

### Client configuration
Client version: 2.3.2

Operating system: GNU/Linux, Ubuntu 17.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): Qt 4.8.7

Client package (From ownCloud or distro) (Linux only):

Distro Client (Built from Git revision 820899 on May 8 2017, 14:16:42 using Qt 4.8.7, built with OpenSSL 1.0.2g 1 Mar 2016)

Installation path of client: /usr/bin/owncloud

### Future

As of now I've switched from the Ubuntu distributed package to the ownCloud distributed package. Expect same behaviour but if the bug disappears I'll report on it.

ownCloud ppa version newly installed: (Built from Git revision 820899 on May 8 2017, 14:15:40 using Qt 4.8.7, built with OpenSSL 1.0.2g 1 Mar 2016)

**Comment by michaelstingl** [comment]
Qt 4.8.7 sounds very weird. @jnweiger You made sure that we get a Qt5 with Ubuntu 16.10. Please apply the same fixes to the 2.3.2 Ubuntu 17.04 builds .

@btittelbach Please wait for @jnweiger 's fix, the please test again from https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

**Comment by michaelstingl** [comment]
@btittelbach From 2.3.3, ownCloud client for Linux no longer relies on the distribution Qt packages. All platforms will come with own Qt 5.6.2 included.

**Comment by jnweiger** [comment]
https://github.com/owncloud/administration/commit/d18649511ed48626767c83ab55313a4e7c5b0189 enforces qt5 builds on all deb/ubuntu targets. 17.04 is rebuilding fine, right now.

**Comment by jnweiger** [comment]
Rebuild results: All relevant Ubuntu/Debian succeed with some version of Qt5.
<pre>
Ubuntu_17.04/x86_64:            qt-5.7.1
Ubuntu_16.10/x86_64:            qt-5.6.1
Ubuntu_16.04/x86_64:            qt-5.5.1
Ubuntu_14.04/i586:              qt-5.2.1
Ubuntu_14.04/x86_64:            qt-5.2.1

Debian_9.0_update/i586:         qt-5.7.1
Debian_9.0_update/x86_64:       qt-5.7.1
Debian_9.0/i586:                qt-5.7.1
Debian_9.0/x86_64:              qt-5.7.1
Debian_8.0/i586:                qt-5.3.2
Debian_8.0/x86_64:              qt-5.3.2

openSUSE_Tumbleweed/x86_64:     qt-5.9.1
openSUSE_Leap_42.3/x86_64:      qt-5.6.2
openSUSE_Leap_42.2/x86_64:      qt-5.6.1
openSUSE_Leap_42.1_Update/x86_64: qt-5.5.1
openSUSE_Leap_42.1/x86_64:      qt-5.5.0
openSUSE_Factory/i586:          qt-5.9.1
openSUSE_Factory/x86_64:        qt-5.9.1
openSUSE_13.2/i586:             qt-5.3.2
openSUSE_13.2/x86_64:           qt-5.3.2
openSUSE_13.1/i586:             qt-4.8.5
openSUSE_13.1/x86_64:           qt-4.8.5
SLE_12_SP2/x86_64:              qt-5.6.1
SLE_12_SP1/x86_64:              qt-4.8.6
SLE_12/x86_64:                  qt-4.8.6
RHEL_7/x86_64:                  qt-5.4.2
Fedora_25/x86_64:               qt-5.7.0
Fedora_24/x86_64:               qt-5.6.0
Fedora_23/x86_64:               qt-5.4.2
Fedora_22/x86_64:               qt-5.4.1
CentOS_7/x86_64:                qt-5.4.2
CentOS_6/i586:                  qt-4.8.6
CentOS_6/x86_64:                qt-4.8.6
</pre>

**Comment by jnweiger** [comment]
@btittelbach Please try again with Ubuntu-17.04 when you see owncloud-client_2.3.2-5.1 on the mirrors. Note the minimum 5.1 rebuild suffix (or later).

**Comment by guruz** [comment]
@btittelbach Any news? :)

**Comment by ogoffart** [comment]
I took the liberty to edit the title and description to reflect what the problem actually is

**Comment by btittelbach** [comment]
@guruz I repeated the things that previously triggered the bug. Does not really count as exhaustive testing, but for everything that i've tried so far the issue seems to be solved! ;-) Thanks!!
