### ISSUE TITLE
Cannot add SMB mount to client, client crashes

### ISSUE THREAD

**Issue by eggithub** [owncloud/client#5887]
I want to sync nextcloud files to a device I cannot install the client on using samba shares. I use "mount -t cifs <share> <mountpoint>" to mount a network share from another device running bare-metal (libreelec). For me this seems the only way to sync files to the libreelec device. When I add the mountpoint to the client and select a webdav folder and try to finish the adding process, owncloud client crashes. Also i'm unable to start the client with actual nextcloud.cfg and have to restore a backup

Before I add a lot of info, is this even possible? or is the client bound to crash on this?

cheers!

**Comment by guruz** [comment]
You could generate a backtrace with gdb ("thread apply all bt") and paste it here.

**Comment by eggithub** [comment]
im not familiar with gdb but I guess it is a tool to get some raw data on the client binary while running or crashing. can you give me to command line entry that I need to give you the logs that you need?

**Comment by guruz** [comment]
```gdb owncloud```
This should run in gdb.
Then
```r```
to run the application.
Then on the actual crash/abort
```thread apply all bt```

**Comment by guruz** [comment]
Closing as there was no info :(
