### ISSUE TITLE
Start supporting Fedora 26 in the OBS

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5891]
FYI: https://fedoramagazine.org/fedora-26-is-here/

cc/ @jnweiger @crrodriguez

**Comment by crrodriguez** [comment]
already added the isv:owncloud:desktop , now building on internal obs desktop project, ce:10 and ee:10. closing.

**Comment by SamuAlfageme** [comment]
@crrodriguez nice! However... 

> First, of course, we have thousands of improvements from the various upstream software we integrate, including new development tools like **GCC 7** 

I'll be careful when testing/releasing the new Fedora26 builds because of the compiler used - at least for the client - (e.g. the problems we had on mingw: https://github.com/owncloud/client/issues/5832#issuecomment-314589158)

**Comment by crrodriguez** [comment]
@SamuAlfageme While it is impossible to know in advance what problems a new toolchain might bring to non-trivial C++ codebases, problems like the one you experience with mingw..should never happen  at the scale of a distribution like Fedora..as every single of the 1000's of packages  is bootstraped and rebuilt against the very same toolchain.. now if you add third party toolchains to the mix ..sure..it might ocurr.

**Comment by goshdark138** [comment]
@crrodriguez tengo problemas para crear el cliente de win
la url "http://download.opensuse.org/repositories/windows:/mingw/openSUSE_42.1/windows:mingw.repo"
la cambie por openSUSE_LEAP_42.1 y realiza el compilado pero se genera el siguiente error

![27166046-a402bc46-515d-11e7-9b92-c4e006127bd7](https://user-images.githubusercontent.com/10076619/28194998-547f677a-680d-11e7-9414-38f1ea9e8d3f.png)

uso el metodo de docker que otro metodo puedo usar o que cambios debo realizar

**Comment by SamuAlfageme** [comment]
@goshdark138 That's unrelated to this one. See https://central.owncloud.org/t/building-the-windows-installer/8403 for an explanation and temporary solution.

**Comment by jnweiger** [comment]
https://build.opensuse.org/repositories/isv:ownCloud:desktop/owncloud-client has publishing of.
Thus the new Fedora 26 builds of 2.3.2 are not visible to end users.
