### ISSUE TITLE
macOS Journal DB filename with dot underscore

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5904]
@dragotin did you notice that a filename like ```._sync_7d56ce96981f.db``` is COMPLETELY INVISIBLE in Finder while ```.csync_journal.db``` is visible in light grey if you have 
```defaults write com.apple.finder AppleShowAllFiles YES``` set.

Did we think about the implications this could have for end users when moving files/folders/directories etc? @michaelstingl 

But maybe normal users anyway don't have ```AppleShowAllFiles``` set?

FYI @ckamm @ogoffart @SamuAlfageme 

Feel free to close this issue, I just wanted to mention it.

**Comment by michaelstingl** [comment]
> Did we think about the implications this could have for end users when moving files/folders/directories etc

If someone moves the full sync folder, it's included. I don't see a "real" problem,

**Comment by ogoffart** [comment]
There was another issue because of ._  in the name:  #5633    (but that was fixed by removing the _  for samba shares)

**Comment by labkode** [comment]
@guruz @michaelstingl  @ogoffart as @matthiasschroder described, we usually have to ask the user for this file while doing support as the owncloud sync longs are not enough for debugging the problem.
Having this file completely invisible (and we do not want to ask end-users to type commands in a Termninal) makes our support life more difficult. If there is not any strong technical reason for having that prefix I propose to change it back to .csync_journal.db or somethink alike.

**Comment by guruz** [comment]
@ckamm maybe the code here could just be swapped around a bit to prefer the non-underscore-path?
https://github.com/owncloud/client/commit/4291ea47f77752848e31341019e9be98f59526df#diff-0b6f105ffd4493a278873f32b7c170c1R84

**Comment by ckamm** [comment]
@guruz Yes.  We needed  `._sync` for client versions <= 2.3.2 apparently. Now that we don't support these versions anymore we could go for plain `.sync` by default. Since the journal file name is stored in the config it'd be easy and safe to do this for new folders without needing lots of migration code.

**Comment by ckamm** [comment]
New databases will be created with the `.sync_` prefix.

**Comment by labkode** [comment]
@ckamm @guruz Thank you!

**Comment by HanaGemela** [comment]
New databases are created with the .sync_ prefix
Tested in 2.6.0alpha2 (build 12128), macOS 10.14.5
