### ISSUE TITLE
[macOS] When switching from oauth2/master back to a 2.3 client I get a password dialog filled with a lot of characters

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5906]
Maybe we read unitialized memory from keychain?

I think I see only 2 entries for the (null) SSL client cert/key in the keychain.

**Comment by ogoffart** [comment]
It's not unitialized memory,  it's the refresh_token that is used as a password.
The user will just have to enter the right password. There is no dataloss or anything. It's a bit wierd, but also not something so bad, and downgrading is not a normal workflow anyway, so i'm closing this issue.

**Comment by guruz** [comment]
Hmmm but then why

> I think I see only 2 entries for the (null) SSL client cert/key in the keychain.
