### ISSUE TITLE
do not auto retry on invalid login credentials

### ISSUE THREAD

**Issue by staabm** [owncloud/client#5909]
it seems the client is doing auto-retry even when invalid login credentials are stored in it.

we hit this problem, as our server side fail2ban dropped clients which did to many invalid login tries.
our guess is that one of the clients (either ipad, iphone or the windows native app) is doing auto retry on invalid login credentials.

sorry for the vague error report, as I cannot pinpoint which of those 3 apps could be the actual reason.

the error happend as soon as I changed the password via the webinterface and all the apps tried to login and finally made fail2ban block my connection.

**Comment by guruz** [comment]
I think the desktop client should switch to offline (right @ogoffart @ckamm ?)

CC @nasli

**Comment by ogoffart** [comment]
What's the version of the client?

**Comment by ogoffart** [comment]
According to my test, we only do one attempt if the password is wrong.

**Comment by guruz** [comment]
Yes, I think it might have been from the iPhone/iPad client then @jesmrec ?

**Comment by nasli** [comment]
@staabm Could you check the requests headers? In the request should go the user agent and should appears iOS, Android.. there.

**Comment by staabm** [comment]
hmm I tried to reproduce the issue. it seems that I cannot reproduce it.

sorry for the noise.
