### ISSUE TITLE
[self-compiled] Mac OS X sync client is draining energy

### ISSUE THREAD

**Issue by ericbodden** [owncloud/client#5910]
Hi. I am using the sync client on OS X and the Activity Manager shows that it's really draining my battery, having an average energy impact of about 24% even _although_ nothing was synced within the last few hours. Hence even when running in idle mode, the energy drain is higher than Chrome's for instance, which seems odd.

### Expected behaviour
Low energy consumption if not syncing

### Actual behaviour
High energy consumption on OS X

### Steps to reproduce
Just let sync client run for a while
Look at energy consumption using OS X Activity Monitor

### Client configuration
Client version:  Git revision 820899 

Operating system: OSX Sierra (10.12.5 (16F73))

**Comment by ericbodden** [comment]
Some additional information: interestingly, the energy utilization remains high even when I pause all syncing!

**Comment by guruz** [comment]
Could you check the 'Activity' tab of the client to verify that you really didn't sync anything? :)

Can you tell us a bit more about how you're using the client? I'm wondering if you use Selective Sync to exclude subfolders? And were there changes in the excluded subfolders?

Also how many subfolders/files do you have?

**Comment by ericbodden** [comment]
Hello. Thanks for the quick response!

I did check the activity tab before I posted the issue. Back then, the last activities had been hours ago.

I am not using excluded sub-folders. I am using two accounts, one of which is set up to sync one folder and the other one of which is set up to sync six different folders.

Is there any kind of log I can provide you that might be helpful?

Cheers
Eric

**Comment by SamuAlfageme** [comment]
@ericbodden try sampling the owncloud process from the activity monitor and pasting the output on a gist.github.com 

![sample](https://user-images.githubusercontent.com/2644445/28307337-dce116f2-6ba2-11e7-98ac-aa46245468df.gif)

... and also, some [client logs](https://doc.owncloud.org/desktop/2.3/troubleshooting.html#log-files) could be handy to determine what's going on there. 

Thanks!

**Comment by ericbodden** [comment]
Thanks a lot! I have posted a sample here:
https://gist.github.com/ericbodden/ed8a87e101802050e25e35c26022396e
Let me know if that helps.

I am somewhat reluctant to share a log since it contains somewhat confidential information (in terms of file names). I’d be OK to share it by private mail, though.

Cheers
Eric

**Comment by guruz** [comment]
I think it's because of

```
    2681 Thread_3878265: QScanThread
      2681 thread_start  (in libsystem_pthread.dylib) + 13  [0x7fffa5e1a08d]
        2681 _pthread_start  (in libsystem_pthread.dylib) + 286  [0x7fffa5e1a887]
          2681 _pthread_body  (in libsystem_pthread.dylib) + 180  [0x7fffa5e1a93b]
            2681 QThreadPrivate::start(void*)  (in QtCore) + 363  [0x10dc0a5ab]
              2681 QScanThread::run()  (in libqcorewlanbearer.dylib) + 357  [0x113decf65]
                2681 -[CWInterface scanForNetworksWithName:error:]  (in CoreWLAN) + 106  [0x7fff91b930bf]
                  2681 -[CWInterface(Private) scanForNetworksWithChannels:ssidList:legacyScanSSID:includeHiddenNetworks:mergedScanResults:maxAge:maxMissCount:maxWakeCount:maxAutoJoinCount:waitForWiFi:waitForBluetooth:priority:error:]  (in CoreWLAN) + 623  [0x7fff91b9a0e8]
                    2681 _dispatch_semaphore_wait_slow  (in libdispatch.dylib) + 103  [0x7fffa5bd4891]
                      2681 _os_semaphore_wait  (in libdispatch.dylib) + 16  [0x7fffa5be3a77]
                        2681 semaphore_wait_trap  (in libsystem_kernel.dylib) + 10  [0x7fffa5d28386]
```

In our build, we don't ship the Qt bearer plugins so we avoid this totally uneeded WiFi-scanning behaviour.

Which Qt are you compiling with?

Does it get fixed by removing the bearer plugins? qgenericbearer* qnativewifibearer* from somewhere in the .app

**Comment by ericbodden** [comment]
Hmm, this is odd, I thought I had downloaded the official OwnCloud client. Let me download that one again and double-check...

**Comment by ericbodden** [comment]
FYI, I just reinstalled OwnCloud from this page:
https://owncloud.org/install/#install-clients

I received a build that shows the following info:
Built from Git revision 820899 on May 8 2017, 15:57:50 using Qt 5.6.2, OpenSSL 1.0.2j 26 Sep 2016

For now the energy profile looks somewhat better. Let me run it for a few hours and then report back to you.

**Comment by ericbodden** [comment]
It looks like this in fact solved the problem. I have no idea why I had a different build earlier. Anyway, I am glad this was cleared up. Closing the issue for now... Thanks!

**Comment by guruz** [comment]
@ericbodden Out of curiousity, which version of Qt did you have?

**Comment by guruz** [comment]
in your self compiled..

**Comment by ericbodden** [comment]
@guruz I never did self-compile OwnCloud. I can just imagine that I must have downloaded an OwnCloud binary from somewhere else, but actually I was pretty sure that also the previous build I received from owncloud.org.

Anyway, I have now uninstalled that build and hence I don't know any more which version of QT I had there. Sorry. Anyway, the average energy impact is not way below 1%, so I am happy :-)
