### ISSUE TITLE
Auto Upload and camera folder doesn´t work on Zenfone 3

### ISSUE THREAD

**Issue by FernandoRD** [owncloud/client#5911]
Auto upload feature doesn´t work, and when I tried to change the camera folder, the interface does not show all folders available, for example if I select the folder "/" I get stuck because it does not show any folder to select from.

And even selecting the correct folder auto upload does not work

### Expected behaviour
Any photo I take must be uploaded

### Actual behaviour
It does not working

### Steps to reproduce
Described above 

### Server configuration
Operating system: Raspbian (pi 3)

Web server: apache2

Database: sqlite
![screenshot_20170717-103346](https://user-images.githubusercontent.com/10245960/28270469-f965099a-6adb-11e7-9dfb-8a2b7b54167a.jpg)

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version: 2.4.0

Operating system: Android 7

OS language: Portuguese

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by michaelstingl** [comment]
@FernandoRD Android upload issues have been improved. You could test the Android beta and provide feedback: https://owncloud.org/blog/the-owncloud-beta-client-is-coming-to-the-fdroid-repository-for-easier-testing/

I will close this issue in the repo for the ownCloud desktop sync client.

**Comment by FernandoRD** [comment]
Downloaded 2.4.0 version from F-Droid, and it is having the same problems....
Thanks

**Comment by michaelstingl** [comment]
@FernandoRD Please test **beta** version (2.5.0-beta.1) and don't use this repo (desktop sync client) for Android issues. Please follow the instructions in the linked blog post and send feedback to apps@owncloud.com .
