### ISSUE TITLE
Feature Request: Clickable link to folder in Syncprotocol

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#5917]
**Feature Request:**
When a file get´s synced, you see in the sync protocol what has been done.
This FR is about that when a file got added, you can click on the file name and a file explorer opens with the location of the file. The file will not get opened, only the folder.

**Comment by hodyroff** [comment]
Good stuff, but difficult to achieve. Will need to be integrated with each file browser ...

**Comment by mmattel** [comment]
Easy for Windows and Mac. Both standard file browsers are known, Explorer and Finder. Agree to Linux, different possibilities.

What about a user editable config list (table) with defaults where you have OS (Windows, Mac, Other), File Browser Application Command (Explorer, Finder, ...), Parameter (whatever to be entered here) ?

We can identify the OS the client runs or is built for, it is not one of the first two it is the last...

We can also give suggestions based on best practice.

**Comment by SamuAlfageme** [comment]
@mmattel this was already included in version 2.3 for all the tabs under the "Activity" section (see https://github.com/owncloud/client/issues/5306)

![click_and_load](https://user-images.githubusercontent.com/2644445/28519279-3b1da0c4-706b-11e7-800c-b7c29e35fd8a.gif)

Which client version do you have installed?

**Comment by mmattel** [comment]
2.3.2
Interresting.
I was looking at Sync Protocol and not Sync Activity
The latter means server activity while the other means as the term states sync protocol = client related.
Maybe as an idea to have the same function also at the Sync Protocol tab - would be natural to me...

**Comment by SamuAlfageme** [comment]
@mmattel 

> I was looking at Sync Protocol and not Sync Activity 

See the gif above, that one is the "Sync Protocol" tab (client-related, as you say) - Sync Activity is directly related to the https://github.com/owncloud/activity app API. 

(btw, in the previous gif there's no "Server Activity" tab since it's hidden when the accounts synced do not have Activity app support, i.e. not installed in the server)
