### ISSUE TITLE
ownCloud Client direct sync to Network or IP

### ISSUE THREAD

**Issue by vaibhavbhatu** [owncloud/client#5923]
**Please tell me how can I set on my OWNCloud to sync all data directly on my network or IP**

The cloud is setup as follows:
 
VMWARE INSTALL on Server,
Data store is a Network NAS drive located on the network with my IP. In this data store, there are all the user account directories of folders with all their files. What I have been asking is for the network drive to be mapped to the cloud server as the data store, instead all files are now being stored on the local server drive – the login of any account still shows the allocated files per account but the files themselves are not in the local data store they are on the network store as above.
 
I need this network store mapped correctly so that we can access the files and upload new ones to the network drive and not the local drive, 

@owncloud-bot  please help me out in this situation

**Comment by hodyroff** [comment]
Seems that your primary storage is not the NAS yet, you normally would mount that on your server and use it as the primary storage.
Question is not related to the Client, please followup at central.owncloud.org if you have more configuration questions.
