### ISSUE TITLE
Add New Folder Connection: whitespace characters in the input path 

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5924]
It can happen that ^M (newline) or other whitespace characters are incidently copy/pasted into the remote path field. This obviously results in an error -- see below.

It could be a better idea to make them visible so that a user understands that there is a problem.

![image](https://user-images.githubusercontent.com/621965/28629367-83755962-7227-11e7-9dff-3a6c2563bfd5.png)

**Comment by guruz** [comment]
I agree but what if you really have whitespace at the end?
(Can't happen on Windows afaik, but macOS and linux can)

**Comment by moscicki** [comment]
Making them visible would probably be sufficient. Also could filter out some leading/trailing whitespace such as \n,\r -- these should not be part of the filename in any case.

**Comment by ogoffart** [comment]
Trying to reproduce this issue in 2.4, I noticed it crashed.  (Fixing with https://github.com/owncloud/client/pull/5927 )

However, the error message has changed in the 2.4 branch and is showing this:

![spectacle b11371](https://user-images.githubusercontent.com/959326/28709167-69068886-737f-11e7-952a-18b09251402e.png)

Note that we hide the 404 error as they often contains error as we type. But maybe we shouldn't?

**Comment by ogoffart** [comment]
Is there still something to do here?
I think the current error is good enough.
