### ISSUE TITLE
conflict shown in activity stream, but with no chance to resolve

### ISSUE THREAD

**Issue by stkjj** [owncloud/client#5930]
### Expected behaviour
conflict solving -> choice of »Client«/»Server«/»Ignore (leave unresolved)«

### Actual behaviour
conflicts are only shown in activity stream without having an option to solve them at all

### Steps to reproduce
1. install Desktop 2.4.0-8111 nightly
2. rename local copy before starting client

### Server configuration
Operating system: centOS6.9 
Web server: Apache 2.2.15
Database: MySQL 5.0.11-dev
PHP version: 7.0.21
ownCloud version: 10.0.2.1

Storage backend (external storage):

### Client configuration
Client version: 2.4.0. 8111

Operating system: macOS 10.12.6

OS language: german

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by SamuAlfageme** [comment]
This one is planned for 2.5 -> https://github.com/owncloud/client/issues/5896
