### ISSUE TITLE
Migrate sync journal table structure to support BIGINT switch on server's DB

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#5933]
Once support for big fileids (https://github.com/owncloud/core/issues/26901 & https://github.com/owncloud/core/pull/28364) is merged in core, we'll need to review the way the client stores the fileids on the sync journal.

Also, review the impact this switch might have in the private link feature: https://github.com/owncloud/client/pull/5763 - I remember there was some intermediate step for filling the id with zeroes in https://github.com/owncloud/client/pull/5763#issuecomment-300757841, maybe we now need more padding (?) cc/ @ckamm 

In https://github.com/owncloud/core/issues/26901#issuecomment-314613339 there's a list of all affected columns on the server's DB.

**Comment by guruz** [comment]
At least three things to it:
* Our C layer (ex-csync)
* Our C++/Qt layer (propagation)
* The sqlite3 DB (["INTEGER. The value is a signed integer, stored in 1, 2, 3, 4, 6, or 8 bytes depending on the magnitude of the value."](https://sqlite.org/datatype3.html))

**Comment by ckamm** [comment]
`BIGINT` is roughly an 8 byte integer on MySQL, MariaDB and PostgreSQL. So our sqlite layer is already safe. We do need to go through the code and ensure we use a fitting datatype though. And yes, the conversion from fileid to id needs a double check to be in line with what the server does.

**Comment by ckamm** [comment]
On further investigation, the client is already fully prepared for this change. We store the full id as text in the database and extract the numeric id (as text) from it.

I've commented about potential effects on the full id at https://github.com/owncloud/core/issues/26901#issuecomment-327147423 . Once that receives an answer, I'd add a unittest and close this issue.

**Comment by ckamm** [comment]
I've also tested with master owncloud server by manually assigning a fileid beyond the 4-byte range in the servers database. The client database looks fine and the link generation works.
