### ISSUE TITLE
Sync multiple accounts simultaneously

### ISSUE THREAD

**Issue by thinking-aloud** [owncloud/client#5934]
Hi,
I have my private Nextcloud and our University ownCloud setup in my sync client. The University OC is kinda slow and reindexes quite often or syncs some stuff. This blocks my private Nextcloud sync.
It would be great to have them sync at the same time or at least be able to prioritise which Account gets synced first.

**Comment by SamuAlfageme** [comment]
Hey @thinking-aloud thanks for the FR; it was also suggested in the past in https://github.com/owncloud/client/issues/4951 (drop your 👍 there to express your support for the feature) - where you can see the explanation for the current implementation and tell us about your use-case.

Closing here as duplicate.
