### ISSUE TITLE
How to check where is located my sync path on own cloud 

### ISSUE THREAD

**Issue by vaibhavbhatu** [owncloud/client#5935]
First time i use this own cloud and i got some issue for data storage path on VM network,
I don't know how to check path storage location or how to change location on VM network storage,

And ya, On more thing when i log in my account and sync data i got data for only one user but i want to data sync for all user on one-time sync on VM network storage so how to do this ?

@ownclouders

**Comment by guruz** [comment]
Sorry, This is a bug tracker, please get support via https://central.owncloud.org/ or https://owncloud.org/support
