### ISSUE TITLE
Windows 10 WebDAV Client(Windows Builtin) bug or not? It can only create 0kb file.

### ISSUE THREAD

**Issue by iMocW** [owncloud/client#5938]
### Expected behavior
Normally created.

### Actual behavior
Created a 0 kb file, then it asked you if you want to override it. If you click yes, it will say can not read source file(???????).

### Steps to reproduce
1. Add WebDAV(https://DOMAIN/remote.php/webdav/) to windows file manager.
2. Copy file to it.
3. Then it created a 0kb file on the server.

### Server configuration
Operating system: Ubuntu Server 16.04.03

Web server: Apache 2.4.27

Database: MariaDB

PHP version: 7.1.7

ownCloud version: 10.0.2

Storage backend (external storage): Server Internal Disk.

### Client configuration
Client version: Windows 10 Enterprise file manager

Operating system: Windows 10 Enterprise

OS language: Chinese

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: C:\

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log: None.

3. Server logfile: ownCloud log (data/owncloud.log):
[owncloud.log.zip](https://github.com/owncloud/client/files/1199269/owncloud.log.zip)

PS. It works fine on my Android 7.0 phone with ES file manager Pro.
So I guess Windows WebDAV client have compatibility issues with owncloud WebDAV server.

**Comment by guruz** [comment]
This is the issue tracker for the desktop sync client https://owncloud.org/changelog/desktop/ 

If you need help for webdav mounting you could ask on https://central.owncloud.org/ :)
Also make sure to include a screenshot of the error (even if it is Chinese).

You can also first check on the SERVER issue tracker if someone reported this: https://github.com/owncloud/core/issues
