### ISSUE TITLE
[Sharing Dialog] Not possible to set public link expiration date beforehand when defining max. expiration days in password policy app 

### ISSUE THREAD

**Issue by individual-it** [owncloud/client#5939]
### Steps to reproduce
1. install password policy app
2. in password policy app settings enable "days until link expires if password is not set" and set any number of days
3. try to share a public link with the client

### Expected behaviour
It should be possible to set the expiration date

### Actual behaviour
It is not possible to set the expiration date
![image](https://user-images.githubusercontent.com/2425577/28967158-94d3287e-7939-11e7-9667-0986eb665cd2.png)

### Server configuration
Operating system: Debian

Web server: Apache2

Database: MySQL

PHP version: 7.1

ownCloud version: 10.0.2 (git master branch)

Storage backend (external storage): local only

### Client configuration
Client version: 2.3.2 Built from Git revision 820899 on Jun 12 2017

Operating system: Linux Debian

OS language: EN/DE

Qt version used by client package (Linux only, see also Settings dialog): Qt 4.8.7

Client package (From ownCloud or distro) (Linux only): [ownCloud](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client)

Installation path of client: /usr/bin/owncloud

### Logs

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
```
08-04 17:28:54:919 0x560e5a191eb0 void OCC::SocketApi::command_SHARE(const QString&, OCC::SocketListener*) "/home/....../localhost-owncloud-core/lorem.txt" 
08-04 17:28:54:920 0x560e5a191eb0 SocketApi:  Sending message:  "SHARE:OK:/home/...../localhost-owncloud-core/lorem.txt" 
08-04 17:28:54:921 0x560e5a191eb0 void OCC::ownCloudGui::slotShowShareDialog(const QString&, const QString&, bool) Opening share dialog "/lorem.txt" "/home/...../localhost-owncloud-core/lorem.txt" QFlags(0x1|0x2|0x4|0x8|0x10) 
08-04 17:28:54:962 0x560e5a191eb0 !!! OCC::ThumbnailJob created for "http://localhost/owncloud-core" + "index.php/apps/files/api/v1/thumbnail/150/150//lorem.txt" "OCC::ShareDialog" 
08-04 17:28:54:971 0x560e5a191eb0 !!! OCC::PropfindJob created for "http://localhost/owncloud-core" + "/lorem.txt" "" 
08-04 17:28:55:157 0x560e5a191eb0 Received sharing permissions for "/lorem.txt" QFlags(0x1|0x2|0x10) 
08-04 17:28:55:159 0x560e5a191eb0 !!! OCC::OcsShareJob created for "http://localhost/owncloud-core" + "ocs/v1.php/apps/files_sharing/api/v1/shares" "" 
08-04 17:28:55:167 0x560e5a191eb0 !!! OCC::OcsShareJob created for "http://localhost/owncloud-core" + "ocs/v1.php/apps/files_sharing/api/v1/shares" "" 
08-04 17:28:55:315 0x560e5a191eb0 void OCC::ShareManager::slotSharesFetched(const QVariantMap&) "10.0.2.3" Fetched 0 shares 
08-04 17:28:55:316 0x560e5a191eb0 void OCC::ShareManager::slotSharesFetched(const QVariantMap&) Sending  0 shares 
08-04 17:28:55:405 0x560e5a191eb0 void OCC::ShareManager::slotSharesFetched(const QVariantMap&) "10.0.2.3" Fetched 0 shares 
08-04 17:28:55:406 0x560e5a191eb0 void OCC::ShareManager::slotSharesFetched(const QVariantMap&) Sending  0 shares 
08-04 17:28:55:406 0x560e5a191eb0 void OCC::ShareLinkWidget::slotSharesFetched(const QList<QSharedPointer<OCC::Share> >&) "10.0.2.3" Fetched 0 shares 
08-04 17:28:57:455 0x560e5a191eb0 void OCC::ShareLinkWidget::slotCheckBoxShareLinkClicked() true 
08-04 17:28:57:457 0x560e5a191eb0 !!! OCC::OcsShareJob created for "http://localhost/owncloud-core" + "ocs/v1.php/apps/files_sharing/api/v1/shares" "" 
08-04 17:29:20:759 0x560e5a191eb0 * Trying to check "http://localhost/owncloud-core/remote.php/dav/files/admin/" for changes via ETag check. (time since last sync: 58 s) 
08-04 17:29:22:602 0x560e5a191eb0 Scheduling "http://localhost/owncloud-core/remote.php/dav/files/admin/" to check remote ETag 
08-04 17:29:22:602 0x560e5a191eb0 !!! OCC::RequestEtagJob created for "http://localhost/owncloud-core" + "/" "OCC::Folder" 
```

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
Can you point us to the exact version and URL of that password policy app?
(As I've never heard about it before:)

**Comment by michaelstingl** [comment]
https://github.com/owncloud/password_policy , previously shipped with oC EE

**Comment by SamuAlfageme** [comment]
This has never been supported on the Sharing Dialog design since the flow has been always create link -> update properties

We contemplated the option in 2.4's new sharing dialog (https://github.com/owncloud/client/pull/5695) where we do set a property upon creation (name). We might need to review the link creation workflow for this consideration. 

Note that in the server while setting the properties beforehand is possible, the UX is not very nice when using the password policy app:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/29017990-91b28f8c-7b59-11e7-80ef-78686e5a11e3.gif"/>
</p>

**Comment by ckamm** [comment]
I think I already covered this now, will verify.

**Comment by ckamm** [comment]
Yes, this was covered in #7152 for owncloud/enterprise#3271. Link share creation now allows setting properties before creation is triggered.

QA: Set up password policy app as described above. Creation of  link share should succeed if expire date is set. Should error if no expire date is set.

**Comment by HanaGemela** [comment]
Works as expected in 2.6.0alpha2 (build 12128), macOS 10.14.5
