### ISSUE TITLE
Implement setup switches for e.g. silent install or others

### ISSUE THREAD

**Issue by rakekniven** [owncloud/client#594]
Just tried to find out if owncloud setup.exe (windows) supports any switches.
Couldn't get any information from setup itself. 

Does setup support switches like "quiet" e.g. /q to perform quiet installations?
I would be interested in having a switch do disable autostart.

I am creating setup using inno setup and installshield. There you can use switches easily.

**Comment by michaelstingl** [comment]
2.5.1 MSI installer will have an option to enforce autostart, I'd need to check "disable autostart"…
