### ISSUE TITLE
Qt-5.6.2 everywhere: aggregated rpms don't propagate to all repos correctly

### ISSUE THREAD

**Issue by dschmidt** [owncloud/client#5941]
### Expected behaviour
When I update `ocqt562-qt5keychain` in `isv:ownCloud:devel:Qt562:templatized`, I expect the updated build rpm to appear on all repos/mirrors that aggregate that package. 

### Actual behaviour
There are lots of old rpm builds on the mirrors that use aggregate. We need to use `osc wipebinaries` to update it.
C.f. http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/nightly/openSUSE_Leap_42.2/x86_64/

**Comment by dschmidt** [comment]
Fixed by doing wipebinaries on aggregated packages when updating a repository. cc @jnweiger

**Comment by jnweiger** [comment]
OBS misbehaviour. We can make useless escalate attempts towards opensuse team, if you like :-)

osc wipebinaries is the correct approach.

sigh.

**Comment by dschmidt** [comment]
Interesting enough: it works for `.deb` files, just not for rpms ....
