### ISSUE TITLE
syncing files issues with external storage sources

### ISSUE THREAD

**Issue by catalyst1987** [owncloud/client#5942]
### Expected behaviour
Syncing from the client should happen without error.

### Actual behaviour
Get a series of errors on items and then syncing starts over again.  This goes in a continuous cycle.  

### Server configuration
Operating system: Ubuntu Mate 16.04 ARM version on RPi3

Web server: Apache

Database: MariaDB

PHP version: 7.0

ownCloud version:  NextCloud 12

Storage backend (external storage):  Google Drive and External hard drives

### Client configuration
Client version:  2.3.2 beta build 14.

Operating system: Ubuntu 16.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.8.0
Client package (From ownCloud or distro) (Linux only):

Installation path of client: /home/<user>/Downloads/Nextcloud-2.3.2-beta-x86_64.glibc2.14.AppImage
![screenshot from 2017-08-06 18-01-20](https://user-images.githubusercontent.com/26027600/29007134-d6ee5852-7af4-11e7-9271-d43a4c0b14f9.png)

[nextcloudloglatest.txt](https://github.com/owncloud/client/files/1203442/nextcloudloglatest.txt)

**Comment by guruz** [comment]
> with external storage sources

> ownCloud version: NextCloud 12

External Storage is handled by the server, not by the client.
Please report at nC server github repository
