### ISSUE TITLE
[macOS] installer does not properly overwrite .app when trying to install older version

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5944]
Sometimes our macOS installer doesn't seem to overwrite the old owncloud.app
If I have the Finder window open I can see that the owncloud.app file mtime doesn't change.
If I launch the owncloud.app I can see that it's the old version still (in settings dialogue)

Maybe this is related to the Finder extensions still being in use?
Maybe it's related to not killing the Finder anymore. (although I've seen this when going to 2.3.3 where maybe we still do this)

**Comment by SamuAlfageme** [comment]
@guruz maybe you're trying to overwrite a **newer** (meaning higher ver. e.g. 2.4. master) version of the client with an older one (2.3.3)? I think I've seen this one before and I've always blamed that.

**Comment by guruz** [comment]
Could be :) But I'd say it should still allow that

**Comment by TheOneRing** [comment]
Needs retesting

**Comment by TheOneRing** [comment]
I don't think this still happens
