### ISSUE TITLE
ocqt562-qt5-qtbase fails to compile on Fedora 26

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#5945]
API breakage: old qt562 does not support new openssl-110, support for the openssl-110 api is needed.

https://kanboard.owncloud.com/project/1/task/922

**Comment by jnweiger** [comment]
@guruz @michaelstingl is this a blocker for 2.3.3 ?

**Comment by SamuAlfageme** [comment]
@jnweiger @dschmidt already dealt with this for Debian 9 and fixed it last week:

```
dschmidt 10:33 AM  https://build.opensuse.org/package/rdiff/isv:ownCloud:devel:Qt562:templatized/ocqt562-qt5-qtbase?linkrev=base&rev=10
 
dschmidt 10:35 AM  basically qt tried to load openssl at runtime (via dlopen) and failed to do so ... because debian comes with libssl1.1 nowadays, which Qt (5.6 at least) does not support

dschmidt 10:35 AM  so i needed to install libssl1.0 and it worked

dschmidt 10:36 AM  now i changed the qt package recipe to link against ssl which should pull in the dep on installation automatically ... this is the slower approach than hacking a libssl requirement into the owncloud spec file... but also the more robust one
```

A pretty dummy sanity-check was also included on the after-install scripts that run on all package installation tests: https://gitlab.com/alfageme/client-linux-tests/blob/release_2.3.3/after_install/no_qssl_unresolved.sh

**Comment by michaelstingl** [comment]
Is adding support for Fedora 26 a matter of a few days, or do you think is is a bigger issue. I think it's no big deal to add F26 builds a few days later…

**Comment by jnweiger** [comment]
seen on debian 9:

```
ldd /usr/bin/owncloud
...
        libssl.so.1.1 => /lib/x86_64-linux-gnu/libssl.so.1.1 (0x00007f4c06898000)
        libcrypto.so.1.1 => /lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f4c06403000)
...
        libssl.so.1.0.2 => /lib/x86_64-linux-gnu/libssl.so.1.0.2 (0x00007f4c02beb000)
        libcrypto.so.1.0.2 => /lib/x86_64-linux-gnu/libcrypto.so.1.0.2 (0x00007f4c02785000)
```

**Comment by guruz** [comment]
We can still announce the rc1 today and have the fedora builds only published after you guys fixed it?

**Comment by jnweiger** [comment]
Yes. Go ahead. Just don't mention that it is missing - I see no more blockers, except kindergarden obs errors that I need to workaround the usual way. Matter of minutes of my time scattered over matter of hours and hours of rebuild attempts for obs.

**Comment by jnweiger** [comment]
ocqt562-qt5-qtbase builds. OBS now fails on qtwebkit, where it complains that a 600MB log file is too big.

**Comment by guruz** [comment]
@jnweiger URL? :)

FYI @jturcotte

**Comment by jnweiger** [comment]
URL: e.g. https://build.opensuse.org/package/show/isv:ownCloud:testpilot:nightly/testpilotcloud-client
(for the reference only)

FIXED: All OBS nightly and testing obs projects now build 2.3.3-rc1 also for Fedora_26

btw: https://build.opensuse.org/package/show/isv:ownCloud:testpilot:edge/testpilotcloud-client (aka master nightly) no longer compiles on any platform.

**Comment by guruz** [comment]
Created https://github.com/owncloud/client/issues/5957 for the edge/master build issue

**Comment by ogoffart** [comment]
If the distribution already has Qt >= 5.6,  we should then not need to ship our own Qt.
