### ISSUE TITLE
Bug list for each release

### ISSUE THREAD

**Issue by jfmatth** [owncloud/client#5946]
Hi, this isn't a bug but a request.

A new release just came out, but I have no idea what fixes it contains?

Where can i get this information.

thanks,

J

**Comment by SamuAlfageme** [comment]
Hi @jfmatth, that's precisely what changelogs are made for: https://owncloud.org/changelog/desktop/ and https://github.com/owncloud/client/blob/master/ChangeLog you can find the right GitHub issues linked in them to expand the info about a feature/bugfix. 

If you have ideas on how to improve the client changelogs do not hesitate to post 'em here. Thanks!
