### ISSUE TITLE
NSIS update on build machine

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5950]

**Comment by jnweiger** [comment]
Update to NSIS 3.01 done on our nbg jenkins workers.
@guruz @michaelstingl do we also need that update on the lex-worker?

**Comment by michaelstingl** [comment]
> do we also need that update on the lex-worker?

@jnweiger yes: https://github.com/owncloud/enterprise/issues/2210

**Comment by jnweiger** [comment]
IMHO pushing nsis-3.01 into lex-brander is not helpful. It does not bring the fix we wanted, and touching lex-brander is a risk.

**Comment by guruz** [comment]
But inconsistent versions is also meh.. but your decision:) not a big problem

**Comment by jnweiger** [comment]
Done: https://lex-brander.int.owncloud.com/view/desktop-client/job/official-client-win32/6/console 
nsis3 ported to lex-brander.
