### ISSUE TITLE
Osx Client building failure 

### ISSUE THREAD

**Issue by waheni** [owncloud/client#5956]
good day

I am building owncloud client for mac os ,
i use 2.4 version (last version)
i use xcode 8.2 and qt 5.9  in osx el captain version 10.11.6

all step are ok , i compiled the source code successfully but in the final step when we call this command (building dmg ) 

admin/osx/create_mac.sh <build_dir> <install_dir>

i got this error 

Building Project (19:23:05) at path: /Users/mohsen/client-build/admin/osx/macosx.pkgproj 
------------------------------------------------------------------------------

Build Folder

==============================================================================
ERROR:

Description:

Unable to find folder at path '/Users/mohsen/client-build/admin/osx/build'
==============================================================================
Build Failed

can any one help ??

thanks for all

**Comment by guruz** [comment]
For compile help please use https://central.owncloud.org/ :-)

Have you clearly followed the https://doc.owncloud.org/desktop/2.3/building.html#mac-os-x ?
