### ISSUE TITLE
"Service Unavailable" from oC 9.1.6.2

### ISSUE THREAD

**Issue by gaspar02** [owncloud/client#5961]
# Owncloud Sync Error:

**PROBLEM:** Some files encountered _Operation Cancelled_ during sync of Owncloud Client to Owncloud Server. But when the server access via browser it's working properly and no error. Only sync of client to server have an error. 
By the way, we already use owncloud server and no error for client and Server for our Old PC Server. But we need to replace the server with the new Computer(SERVER PC) with high specs that's why we need to transfer all the data to the new owncloud server, but after copying the data to the new server and trying to sync the server to the client we encountered that error: "OPERATION CANCELLED."

**_Server:_**
-Ubuntu Server 16.04
-Owncloud Version: 9.1.6.2

**_Client:_**
-Windows 10 Pro
-Owncloud Client Version 2.3.2 (build 6928)

"Already changed the post_max_size and Upload_size but the problem still occur."

No error logs on apache logs and even the owncloud logs.

**Comment by PVince81** [comment]
Is it happening randomly or is it always the same file that cannot get through ?

DId you check the server logs ? (apache error log, owncloud.log)

**Comment by gaspar02** [comment]
Hi PVince81, Thanks for your reply. Yes it's randomly. 

I already checked the server logs (apache error log and owncloud.log) and here's the logs when I force sync the client to server.

**apache error.log:**
[Tue Aug 15 14:30:05.829097 2017] [mpm_prefork:notice] [pid 2489] AH00169: caught SIGTERM, shutting down
[Tue Aug 15 14:30:06.912061 2017] [mpm_prefork:notice] [pid 5878] AH00163: Apache/2.4.18 (Ubuntu) configured -- resuming normal operations
[Tue Aug 15 14:30:06.913041 2017] [core:notice] [pid 5878] AH00094: Command line: '/usr/sbin/apache2'
[Tue Aug 15 14:35:20.244491 2017] [autoindex:error] [pid 5883] [client 10.0.2.2:13879] AH01276: Cannot serve directory /var/www/owncloud/core/doc/user/_static/: No matching DirectoryIndex (index.php,index.html) found, and server-generated directory index forbidden by Options directive, referer: http://192.168.1.38:83/owncloud/core/doc/user/index.html
[Tue Aug 15 14:35:37.417975 2017] [authz_core:error] [pid 5885] [client 10.0.2.2:13919] AH01630: client denied by server configuration: /var/www/owncloud/data/htaccesstest.txt


**Owncloud.log:**
{"reqId":"kEqp3IwwTxPVWjQZyBaV","remoteAddr":"10.0.2.2","app":"PHP","message":"fopen(\/var\/www\/owncloud\/data\/jomar\/files\/fIlesngmgacuTe\/SIMPLEX  IGATE LEASED LINE (2)_3.pdf): failed to open stream: No such file or directory at \/var\/www\/owncloud\/lib\/private\/Files\/Storage\/Local.php#278","level":3,"time":"2017-08-15T07:59:30+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/fIlesngmgacuTe\/SIMPLEX%20%20IGATE%20LEASED%20LINE%20(2)_3.pdf","user":"chester"}
{"reqId":"kEqp3IwwTxPVWjQZyBaV","remoteAddr":"10.0.2.2","app":"webdav","message":"Exception: {\"Message\":\"HTTP\\\/1.1 503 Could not open file\",\"Exception\":\"Sabre\\\\DAV\\\\Exception\\\\ServiceUnavailable\",\"Code\":0,\"Trace\":\"#0 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/CorePlugin.php(83): OCA\\\\DAV\\\\Connector\\\\Sabre\\\\File->get()\\n#1 [internal function]: Sabre\\\\DAV\\\\CorePlugin->httpGet(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#2 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/event\\\/lib\\\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\\n#3 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(459): Sabre\\\\Event\\\\EventEmitter->emit('method:GET', Array)\\n#4 \\\/var\\\/www\\\/owncloud\\\/3rdparty\\\/sabre\\\/dav\\\/lib\\\/DAV\\\/Server.php(248): Sabre\\\\DAV\\\\Server->invokeMethod(Object(Sabre\\\\HTTP\\\\Request), Object(Sabre\\\\HTTP\\\\Response))\\n#5 \\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/appinfo\\\/v1\\\/webdav.php(61): Sabre\\\\DAV\\\\Server->exec()\\n#6 \\\/var\\\/www\\\/owncloud\\\/remote.php(164): require_once('\\\/var\\\/www\\\/ownclo...')\\n#7 {main}\",\"File\":\"\\\/var\\\/www\\\/owncloud\\\/apps\\\/dav\\\/lib\\\/Connector\\\/Sabre\\\/File.php\",\"Line\":306,\"User\":\"chester\"}","level":4,"time":"2017-08-15T07:59:30+00:00","method":"GET","url":"\/owncloud\/remote.php\/webdav\/fIlesngmgacuTe\/SIMPLEX%20%20IGATE%20LEASED%20LINE%20(2)_3.pdf","user":"chester"}

**Comment by PVince81** [comment]
Try running `occ files:scan --all` on the server once, then resume uploading.

**Comment by gaspar02** [comment]
OCC command not found 

When I'm trying to run that command @PVince81

**Comment by gaspar02** [comment]
@PVince81 I run occ files:scan --all.

After running that command and trying to sync again the client to server the problem still occur.

**Comment by gaspar02** [comment]
Error transferring http://OWNCLOUD-IP/owncloud/remote.php/webdav/sampleFiles-1.pdf - server replied: Service Unavailable
SampleFolder/sampleFiles-2.pdf: Operation Cancelled
Operation Cancelled
Operation Cancelled
Operation Cancelled


That's the error when I'm trying sync client to owncloud server

**Comment by PVince81** [comment]
Does the folder "/var/www/owncloud/data/jomar/files/fIlesngmgacuTe/" exist on disk ? Apparently it tries to upload a file there but says "does not exist" from your last owncloud.log entries

**Comment by gaspar02** [comment]
@PVince81 /var/www/owncloud/data/jomar/files/fIlesngmgacuTe/ are still exist on the server. When I'm trying to open the owncloud via browser there's no error/missing contains on that folder.

**Comment by PVince81** [comment]
@gaspar02 can you double check that all files/folders inside the "data" folder have the correct permissions/ownership ? I don't see why it wouldn't be able to open a file for writing inside that folder.

**Comment by gaspar02** [comment]
Hi @PVince81 I'm not the owner of this folder: /var/www/owncloud/data/jomar/files/fIlesngmgacuTe/ and its only shared on my owncloud account. I check the owner of this folder, the files are still there.

Were still using/running owncloud on our old server(PC) and when I copy the DATA folder to the new server(PC) which is high specs than the old one we encountered that problem. But on our old server our owncloud sync work properly,

**Comment by gaspar02** [comment]
Hi @PVince81 permission/ownership of new owncloud set up are same from my old owncloud setup.

**Comment by gaspar02** [comment]
Hi @PVince81 and @guruz How can I resolve this error on my new set up owncloud? Thanks

**Comment by gaspar02** [comment]
@PVince81 and @guruz any help regarding this concern? Thanks.

**Comment by PVince81** [comment]
I'm out of ideas right now, sorry. I don't see why it wouldn't be able to open the target file if the permissions are correct.

**Comment by gaspar02** [comment]
@PVince81 Thanks for your reply, Actually this is the 2nd Time I transfer owncloud server to different Server. Before, we test the owncloud to our vacant server (Testing Server) and test it with some user for about 2months. After testing and found that owncloud is working fine, we decided to transfer it to other server included all the data of all user in our owncloud, But we didn't encounter any problem like what I encountered today in our 2nd trial transferring owncloud to another server. I don't know what is the problem of this. :(

**Comment by PVince81** [comment]
Moving to another server shouldn't be a problem. Make sure that the data folder has the exact same path as it had before.

**Comment by gaspar02** [comment]
@PVince81. Yes, we copy the data folder from the old server exactly to the same path of new server.

**Comment by gaspar02** [comment]
@PVince81 for your reference; That folder/files is shared to my owncloud account, and I encountered problem when I sync the files/folder that are only shared to my account and Im not the owner

![screenshot_1](https://user-images.githubusercontent.com/31028657/29697175-194c16f0-8980-11e7-858f-a8198a1c7356.jpg)

![errorrefe](https://user-images.githubusercontent.com/31028657/29697177-1c4a15dc-8980-11e7-8cb2-f33948d19e02.jpg)

**Comment by ogoffart** [comment]
Is this still a problem?
I'm closing this issue here in the client repository for this is most likely not a problem in the client. Please re-open an issue on the core repository if the bug still exists.
