### ISSUE TITLE
Connection closed error when synchronizing

### ISSUE THREAD

**Issue by waheni** [owncloud/client#5962]
Good day

I compiled last version of owncloud client (2.4.0) in mac (sierra 10.12) with qt 5.9

but when synchronizing it stop and 
<img width="827" alt="screen shot 2017-08-15 at 8 12 47 pm" src="https://user-images.githubusercontent.com/5937941/29313811-69ae9a52-81b3-11e7-9d6e-110092186d7b.png">
 give error "Connection Closed  " 

Can any one help 

Thanks for all

**Comment by guruz** [comment]
hi!

That is a server setup issue, the server is the one closing the connection.
You need to check your owncloud.log and error.log on server side to find out more.

Might also be an ownCloud server issue, then the right tracker is https://github.com/owncloud/core :-)

Closing unfortunately

**Comment by waheni** [comment]
Thanks for your response
the problem is that i used the pre-build application from  the officiel site (same version 2.3.2) and i  does get this issues

**Comment by guruz** [comment]
@waheni It's a SERVER or SERVER CONFIGURATION issue, nothing to do with client prebuilt vs your build :)
