### ISSUE TITLE
handling of colons and other non-cross-platform characters in filenames

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#5964]
Please improve handling of these. Why between two Unix machines I cannot synchronize a file with a colon in the name? How do I explain it to the user who never uses Windows and is not concerned by Windows limitations whatsoever?

The solution is easy: on Unix and Mac upload and download these files, whereas on Windows do not download them but put them on "Not Synced" items tab. There should be very few characters which are genuinely not allowed, such as a forward slash in the filename or a non-printable characters (^M or \n) for example.

**Comment by michaelstingl** [comment]
Please also check https://github.com/owncloud/documentation/issues/2832 (platform-wide known limitations, excluded files)

**Comment by ccoenen** [comment]
I believe what you're describing is already happening. And this behaviour does now work well, either.

My "not synced" tab looks like this, and I hate it. It makes working in a larger group very error prone.

![grafik](https://user-images.githubusercontent.com/124909/29809268-cd1a9940-8c9b-11e7-8685-48188ed4c9b0.png)

Most of these have been created on mac os, where more characters seem to be allowed. In a group of ~40 people working on the same files, things like these are bound to happen. There's no way every one remembers to "never pot a question mark in there" or something like that.

While I don't think, we should limit the set to the lowest common denominator, there needs to be a better solution than this.

**Comment by ccoenen** [comment]
Rough translation for those who can't read the screenshot. In order (but without duplications) the errors are:

- file name ends with a dot `.`
- file name contains a question mark `?`
- file name contains a colon `:`
- file name ends with a space ` `

**Comment by ckamm** [comment]
@moscicki I just tried uploading a file with a colon, and it worked. What specific error message are you seeing?

Looking at the code, it looks like the client is only preemptively excluding certain characters in paths on Windows now. So if you get an error about invalid characters on a linux client, it's probably passed down from the server?

**Comment by moscicki** [comment]
@ckamm: which version of the client have you tried please?

**Comment by ckamm** [comment]
@moscicki Sorry, I was using master, but am not aware of changes in this area from 2.3.

**Comment by guruz** [comment]
@ccoenen I believe your screenshot https://github.com/owncloud/client/issues/5964#issuecomment-325578545 is from a Windows machine, at least the font looks like it.
Windows does not support file names like this (see text in screenshot).

**Comment by ccoenen** [comment]
@guruz Yes, it is from windows. My point is: I am working with many people across systems, and this makes working with nextcloud more of a hassle than it should be.

This is a major pain point for me. Files are not being synced, and I have to go looking for them. The group that is using this nextcloud instance is ~100 people roughly 60/35/5 for MacOS/Windows/Linux. This is a group of students, which changes every 3-4 years, so there will always be "new ones" getting this "wrong" (and of course the "old ones" fail occasionally, too).

**Comment by guruz** [comment]
What @moscicki described above is different from what you see. What would be the solution for your Windows machine? Auto-renaming files is an option, but that's confusing too. You might be able to use the file firewall to allow the students from using those characters in filenames.. https://doc.owncloud.org/server/latest/admin_manual/enterprise/firewall/file_firewall.html
Suggestion: You make a new issue with a proposal on what should be done :-)

Otherwise for @moscicki I agree with @ckamm : It should already be happening what @moscicki request in the original issue.

**Comment by ccoenen** [comment]
I beg to differ, what I am describing is _exactly_ what the original poster describes? How ist that any different? I am just giving a real world example where such a thing occurs. What _is_ different is our point of view. @moscicki does **not** want to exclude certain characters for monocultures. I **do** want to exclude characters for a heterogenous infrastructure.

@guruz thank you for suggesting file_firewall, from the manual entry I can't yet see how it is related (I see no references to file names specifically) but I will dig deeper over the next few days.

**Comment by webjoko** [comment]
I have the same issues with various installs. It also blocks filenames with a comma or uppercase characters. Indeed, it is a major pain and potentially blocking issue for me and my clients to work with this solution.

**Comment by guruz** [comment]
@webjoko Can you please go into detail? Which kind of filename are you uploading from where (which OS) and downloading to where (which OS)? And is the upload or download blocked? Also state your expectation what should happen instead (renaming the file? Error at an earlier stage? Error at a later stage?)

**Comment by guruz** [comment]
Please create a new issue with a proposal on which behaviour you'd want.

**Comment by ccoenen** [comment]
Done. Although I don't really see a benefit of closing this issue in favor of a new one?
