### ISSUE TITLE
Newer file gets renamed to _conflict, should be the other way around

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#5965]
The current state is this:
![screenshot from 2017-06-30 15-03-06](https://user-images.githubusercontent.com/925062/27736621-3f2488fa-5da5-11e7-94ca-c8b1186ad7ab.png)

The newer (top) file which also is the correct one gets the _conflict status. However, in most of these cases the more recent file is the correct one, and the older one should get the _conflict status. Making the recent one to look like it’s _only_ a conflict is confusing.

Currently to fix the conflict, I need to:
1. Check and really make sure that _conflict is indeed the correct one
2. Delete the other file
3. Rename the »conflict« file to remove the »_conflict« part from the name

If it would be the other way around, I could just simply quickly look at it, see that the conflict file is older anyway, and delete that one.

cc @ckamm @ogoffart @guruz what do you think? I am continuously confused by this.

**Comment by hodyroff** [comment]
https://owncloud.org/faq/#conflict is the FAQ entry for that. Conflict files occur locally - there is a feature request to upload them all into versions, which we are strongly considering to avoid data loss. Your description is correct if you are alone, but in a multi-user system and in a conflict case we want to avoid data loss and want to inform the user who created the conflict that it is his task to do something about it. Most of the time the solution will have to be to rebase (= recreate your change in the file on the server) and delete your conflict file afterwards.
Only useful way to avoid conflicts is online editing in a collaborative way using the strong integration in ownCloud with Collabora Online or also OnlyOffice or in the future MS Office 365.
I guess for .xcf that option doesn't exist yet, however.
In any case changing such a default would need very strong arguments as they effect 12 Million+ Users worldwide who suddenly would have a new behavior. For me this is a close, Will reopen if needed.

**Comment by jturcotte** [comment]
Essentially a duplicate of #5106, have a look for more explanation.
