### ISSUE TITLE
Account settings are sometimes losting after boot on Linux Mint 18.2

### ISSUE THREAD

**Issue by Wohlstand** [owncloud/client#5970]
### Expected behaviour
Account settings must be saved persistently and always used on each boot

### Actual behaviour
After reboot account settings are lose, and client asks me to setup them again from scratch. This is very annoying! This happens randomly and I can't guess when it will nuke settings again.

### Steps to reproduce
1. Set client to auto-start on boot
2. Reboot computer multiple times

### Server configuration
<No matter, error of client itself, I have tested on two different servers and I have same>

### Client configuration
Client version: 2.3.2

Operating system: Linux Mint 18.2

OS language: Russian

Qt version used by client package (Linux only, see also Settings dialog):
Git version 820899 in May 8 2017, 14:16:42 using Qt 4.8.7, built with OpenSSL 1.0.2g 1 Mar 2016

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
Installed through `deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.10/ /` as `owncloud-client`

**Comment by guruz** [comment]
Can you go to 'General' settings in the client options, make the window size big enough and copy/paste the Qt version?

**Comment by Wohlstand** [comment]
```
Собрано исходников Git версии 820899 на May 8 2017, 14:16:42 используя Qt 4.8.7, built with OpenSSL 1.0.2g 1 Mar 2016
```
I.e. Buily from git sources of version 820899 in 8 of May 2017 in 14:16:42 using of Qt 4.8.7

**Comment by guruz** [comment]
Our [Qt4 support is dead](https://owncloud.org/changelog/desktop/) :-) It's a known settings bug in Qt4.

**Comment by Wohlstand** [comment]
Okay, Qt 4 is pretty old, and myself I using Qt 5 for my apps. I think, I would to build client from scratch by Qt 5.
