### ISSUE TITLE
I can not open encrypted office files on my owncloud ios

### ISSUE THREAD

**Issue by riccardopirani** [owncloud/client#5971]
I can not open encrypted office files on mycloud ios, if I try to load and open ios files, I get this error: (QuickLookErrorDomain error 44820)

### Steps to reproduce
1. I put password to excel or word file
2. Load the files on owncloud
3. When I open ios files i have this error: errror_message_main: can not complete the operation (QuickLookErrorDomain error 44820)

### Server configuration
Operating system: Ubuntu Server

Web server: Apache 

Database: MariaDB

PHP version: PHP 7.0.22

ownCloud version: 10.0.1

### Client configuration
Client version: 3.6.2

Operating system: IOS

OS language: italian

**Comment by michaelstingl** [comment]
@riccardopirani Could you post a screenshot? Can mobile Safari display the file if you access from your ownCloud mobile web UI?

Background: ownCloud iOS app uses system viewer for office files. If mobile Safari can't display it. ownCloud also can't display it.

**Comment by guruz** [comment]
Can you re-post this in https://github.com/owncloud/ios/issues @riccardopirani ?
