### ISSUE TITLE
Save the new URL when hitting a permanent redirection 301

### ISSUE THREAD

**Issue by tflidd** [owncloud/client#5972]
### Expected behaviour
When you server URL is updated and your are redirected permanently (301) to a new URL, update the URL in the config.

Here: https://mycloud.example.org/owncloud -> https://mycloud.example.org/

Thunderbird lightning detects the redirect and asks if it should update the URL.

### Actual behaviour
Follows the redirect but it means you have to keep the redirection forever

OC Client  version 2.3.2

**Comment by guruz** [comment]
(I thought we did this, but maybe only in wizard.. FYI @ogoffart )

**Comment by ckamm** [comment]
Since I'm set up for redirect testing anyway from #6003 I'll take care of this. I'll add redirection checking in the request for `status.php`. If we see a 301/308 there, it'll update the account with the new url.

**Comment by guruz** [comment]
thanks a ton @ckamm

**Comment by SamuAlfageme** [comment]
👍 yay!
