### ISSUE TITLE
[macOS] show macOS Dock icon while settings dialog or wizard is open

### ISSUE THREAD

**Issue by guruz** [owncloud/client#5973]
I've seen this with the Docker app which is normally only in the menu bar, might be interesting for us to have?

**Comment by michaelstingl** [comment]
I'd love this too. And Docker app is also accessible in the Application Switcher (Command-Tab) while the window is open. 👍👍

**Comment by SamuAlfageme** [comment]
Some reference: https://wiki.qt.io/MacOS_application_without_menu_bar

https://github.com/owncloud/client/blob/881f8463e8c7cd3e531e447c677994c2bdbe714c/cmake/modules/MacOSXBundleInfo.plist.in#L7-L8

Compiling wo/ the [`LSUIElement`](https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/LaunchServicesKeys.html#//apple_ref/doc/uid/20001431-108256) indeed **always** displays the icon on the dock and the app.switcher. But we rather need something in the middle like docker settings window; just when the client is not minimized. 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/30866033-701b44f8-a2d8-11e7-94f9-3dc3ae5cc629.png"/>
</p>

**Comment by TheOneRing** [comment]
Fixed since 2.7 or 2.8
