### ISSUE TITLE
Linux Mint 18.2 - owncloud 

### ISSUE THREAD

**Issue by glannes31** [owncloud/client#5975]
### Expected behaviour
Valid credentials

### Actual behaviour
Erro : Invalid settings credentials

### Steps to reproduce
1. Install owncloud client from Linux Mint 18.2 (17.04 repository)   - 1.7.0 beta 
2. Try to set up an account
3. 

### Server configuration
Operating system: Redhat

Web server: 

Database: Maria DB

PHP version: 

ownCloud version:10.0.2

Storage backend (external storage):

### Client configuration
Client version: 1.7.0.beta.1

Operating system: Linux Mint 

OS language:FR

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

**Comment by glannes31** [comment]
Solved with : 
$ sudo sh -c "echo 'deb http://ftp.debian.org/debian jessie-backports main' >> /etc/apt/sources.list.d/additional-repositories.list"
$ sudo apt-get -t jessie-backports install owncloud-client

**Comment by michaelstingl** [comment]
@glannes31 1.7.0 ist 3 years old. 2.2.4 is 1 year old. Better use the latest builds: https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client
(2.3.3 is planned for the next days)

**Comment by glannes31** [comment]
@guruz hello. Tks for your anwser. It s okay now. I said that is solved when i update in version 2.2.

**Comment by guruz** [comment]
@glannes31 2.2 is old too :D
