### ISSUE TITLE
Network access is disabled

### ISSUE THREAD

**Issue by johnbester** [owncloud/client#5977]
### Expected behaviour
If the network connection is down at the time owncloud client starts up, the client never connects again - even though from the logs it is clearly retrying. From owncloud --logwindow it seems almost as if owncloud selects a network device when internet is down and then attempts to re-use it when internet connection is up.

### Actual behaviour
Ubuntu network manager (16.04LTS with lightdm and Gnome desktop) only brings a network connection up after login. This means that an autostarted owncloud client remains in the state "No connection to owncloud at ... Network access is disabled". 

### Steps to reproduce
1. Install Owncloud client on Ubuntu 16.04 LTS (with latest updates). apt install owncloud-client
   (client must autostart on login)
2. Kill any running instance of owncloud.
3. Close the network connection that provides connectivity to owncloud server.
4. Start owncloud client (owncloud --logwindow)
5. Wait about 70 seconds (each 30 seconds a connection attempt is made and logged)
6. Now connect the network connection.
7. Wait another 70 seconds (log window shows connection attempts every 30 seconds, but no different to the log entries from when network connection was down.

### Server configuration 
(Not applicable to this problem)
Operating system: Ubuntu 16.04 LTS
Web server: Apache
Database: pgsql
PHP version: 7.0.18
ownCloud version: 9.1.4-2.1
Storage backend (external storage):

### Client configuration
Client version: 2.1.1+dfsg-1ubuntu1.1
Operating system: Ubuntu 16.04 LTS (regularly updated)
OS language: English
Qt version used by client package (Linux only, see also Settings dialog): 5.5.1+dfsg-16u
Client package (From ownCloud or distro) (Linux only):  owncloud-client (2.1.1+dfsg-1ubuntu1.1)
Installation path of client: /usr/share/owncloud-client

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
08-22 10:22:28:693 7754 OCC::ConnectionValidator::checkServerAndAuth: Checking server and authentication
08-22 10:22:28:695 7754 OCC::AbstractNetworkJob::start: !!! OCC::CheckServerJob created for "https://yyy.zzz/owncloud" + "status.php" "OCC::ConnectionValidator"
08-22 10:22:28:699 7754 OCC::AbstractNetworkJob::slotFinished: void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(UnknownNetworkError) "Network access is disabled." QVariant(Invalid)
08-22 10:22:28:701 7754 OCC::ConnectionValidator::slotNoStatusFound: void OCC::ConnectionValidator::slotNoStatusFound(QNetworkReply*) QNetworkReply::NetworkError(UnknownNetworkError) "Network access is disabled."
08-22 10:22:28:703 7754 OCC::AccountSettings::showConnectionLabel: "No connection to ownCloud at <a href=\"https://yyy.zzz/owncloud\">https://yyy.zzz/owncloud</a>.\nNetwork access is disabled."
08-22 10:22:28:704 7754 OCC::FolderMan::slotAccountStateChanged: Account "xxx@yyy.zzz" disconnected, terminating or descheduling sync folders
08-22 10:22:28:706 7754 unknown: QIODevice::read (QDisabledNetworkReply): device not open
08-22 10:22:28:707 7754 OCC::CheckServerJob::finished: error: status.php replied  0 ""

2. Web server error log:
No output (tail -f /var/log/access.log  or  tail -f /var/log/ssl_access.log or tail -f /var/log/error.log)

3. Server logfile: ownCloud log (data/owncloud.log):
No output under these circumstances (tail -f data/owncloud.log)

**Comment by johnbester** [comment]
I managed to get a little more information. I wrote a script to be called on autostart. The script would ping the server every second and once the server replied, the script would exit the loop and start owncloud client. The loop worked, but owncloud still started without a connection. However, when I added a sleep 10 after exiting the loop, the problem was fixed. From this experiment, it seems that even though networking seemed to be ready, but not completely. However, this test did not respond the exact same way every time.

**Comment by michaelstingl** [comment]
Please test with the latest version:
https://owncloud.org/install/#install-clients

2.1.1 has been released in February 2016.

**Comment by guruz** [comment]
@johnbester please go to 2.3.3rc2 directly.. https://owncloud.org/changelog/desktop/

We can re-open if needed

**Comment by ibr123** [comment]
Hi,

i have the same issue, the NextCould version that am using is 2.5.0, i tracked the code to know where is the error happens exactly, the line of code is here [discoveryphase.cpp](https://github.com/owncloud/client/blob/06936bc603c91b1c5f10442901bcfeb765b17243/src/libsync/discoveryphase.cpp#L656), after that line the following error is printed on the CMD

```
07-04 15:27:30:007 [ info sync.engine ]:        Server ""
07-04 15:27:30:009 [ info sync.csync.csync ]:   ## Starting local discovery ##
07-04 15:27:30:011 [ info sync.csync.csync ]:   Update detection for local replica took 0.001 seconds walking 0 files
07-04 15:27:30:012 [ info sync.csync.csync ]:   ## Starting remote discovery ##
07-04 15:27:30:014 [ info sync.accessmanager ]: 6 "PROPFIND" "http://**********" has X-Request-ID "************"
07-04 15:27:30:017 [ info sync.networkjob ]:    OCC::LsColJob created for "http:**********" + "" "OCC::DiscoverySingleDirectoryJob"
07-04 15:27:30:020 [ warning sync.networkjob ]: QNetworkReply::NetworkError(UnknownNetworkError) "Network access is disabled." QVariant(Invalid)
07-04 15:27:30:022 [ info sync.networkjob.lscol ]:      LSCOL of QUrl("http://sync.zoolz.com/nextcloud/remote.php/dav/files/userN/") FINISHED WITH STATUS QNetworkReply::NetworkError(UnknownNetworkError) "Network access is disabled."
07-04 15:27:30:024 [ warning sync.discovery ]:  LSCOL job error "Network access is disabled." 0 QNetworkReply::NetworkError(UnknownNetworkError)
07-04 15:27:30:026 [ warning sync.csync.updater ]:      opendir failed for  - errno 5
07-04 15:27:30:027 [ warning sync.engine ]:     ERROR during  csync_update :  "An error occurred while opening a folder Network access is disabled."
07-04 15:27:30:031 [ info sync.database ]:      Closing DB "*********/._sync_369bd5743963.db"
07-04 15:27:30:037 [ info sync.engine ]:        CSync run took  32 ms
```
how i can solve this issue?
Thanks

**Comment by michaelstingl** [comment]
@ibr123 this is the ownCloud issue tracker. Please test with the [ownCloud builds](https://download.owncloud.com/desktop/daily/?C=M;O=D) and [ownCloud server](https://owncloud.org/download/).

**Comment by guruz** [comment]
@ibr123 Use the ownCloud client. It's perfectly compatible with Nextcloud.

**Comment by ibr123** [comment]
Cloud you please tell me what part of the code of ownCloud that handles this issue?
Thnaks

**Comment by OsamaRadwan** [comment]
am also having the same problem, with NextCloud desktop client
what is the code in the own cloud that fixes this network  error
Keep in mind that im using the Qt 5.10, and this error is supposed to be fixed from the Qt DLLs side, im guessing it a threading issue, since it appears in the Release build more often than the Debug build
how is that solved in the OwnCloud desktop client?

**Comment by nigelhorne** [comment]
Why has this issue been closed?  I see no fix, and the problem persists.

**Comment by nigelhorne** [comment]
Problem is still there on Linux.  That other ticket is for Windows.

**Comment by michaelstingl** [comment]
> Problem is still there on Linux. That other ticket is for Windows.

You mean you see the same problem with the 2.6.1 installed from https://owncloud.org/download/#owncloud-desktop-client-linux ?

Please open a new issue and provide all the relevant information, especially new log files. Many things changed since the 2.1.1 in the original report. Thanks!

**Comment by nigelhorne** [comment]
I tried that but it downloaded 2.2.4, not 2.6.1.  Still that's at least better than the 2.1.x in the Debian repo.  It still doesn't work.

Output of uname:

Linux njh 4.15.11-mainline-rev1 #1 SMP Mon Mar 19 08:29:15 UTC 2018 aarch64 GNU/Linux

**Comment by michaelstingl** [comment]
@nigelhorne please install the 2.6.1 from ownCloud official repo:
https://owncloud.org/download/#owncloud-desktop-client-linux
(Choose option "Add repository and install manually" and follow the instructions)

**Comment by nigelhorne** [comment]
Actually come to think of it, that may not be the right link as it takes me to the desktop client, not the CLI.

**Comment by michaelstingl** [comment]
@nigelhorne CLI client is always installed with the ownCloud desktop app.

> The ownCloud Client packages contain a command line client, owncloudcmd, that can be used to synchronize ownCloud files to client machines.

(Source: https://doc.owncloud.org/desktop/2.6/advanced_usage/command_line_client.html)

**Comment by nigelhorne** [comment]
Yeah, it's a pain bundling all that gui stuff with the CLI, really invalidates a headless machine where you don't want to install too much.

**Comment by michaelstingl** [comment]
@nigelhorne this is another discussion and out of scope of this issue.

This issue is resolved (see https://github.com/owncloud/client/issues/7788#issuecomment-595286084)
