### ISSUE TITLE
password file on encrypted partition

### ISSUE THREAD

**Issue by DarkknightAK** [owncloud/client#5984]
### Expected behaviour
we have in our office an automouted encrypted veracrypt partition. there the owncloud files are stored. On windows there is nothing like kwallet so I'm not sure where the owncloud client passwords are stored. Is it needed or possible to store the connection passwords at the encrypted partition?

### Server configuration
Operating system:
SLES 12

Web server: 
appache

Database:
mariadb

PHP version:

ownCloud version:
ownCloud server 9

### Client configuration
Client version:
2.3.2 (build 6928)

Operating system:
Windows 7

OS language:
English

**Comment by michaelstingl** [comment]
@DarkknightAK ownCloud client uses Windows Vault to store credentials. (see https://github.com/owncloud/client/issues/4429)

**Comment by DarkknightAK** [comment]
thanks for the answer.
