### ISSUE TITLE
Renaming files under shares (case-relative changes) might propagate as a new directory in server 

### ISSUE THREAD

**Issue by count0-krsk** [owncloud/client#5985]
I have problem, described in 
https://github.com/owncloud/client/issues/1348
It still have no decision, 3 years ago... 

### Actual behaviour
User Anna have shared folder from Boris. User Ken also have this shared folder. 
1. Anna create dir Files and put some documments.xls and dir Subfiles.  
2. User Ken rename dir Subfiles to SUBFILES and put some files to it. 
3. Anna see "Subfiles" with no new files from Ken. And error in Client about "Case conflict". Ken also have Case conflict. Server (Lubuntu 14.04.5) see Subfiles and SUBFILES dirs.

### Expected behaviour
User Anna see Folder with SUBFILES dir (as Ken rename it) and new files.
                                              **or**
I want to manually FORCE server and client to use only small case. Then I rename all files on server (600 GB+...) and sync clients with hands. And forget this forever...

### Server configuration
Operating system: Lubuntu 14.04.5
server version 9.1.4
Web server: 
Apache 2.4.7

### Client configuration
Client version: 2.3.2 (build 6928)
Operating system: Windows 7/8/10, no matter
OS language: Russian

Server logfile: ownCloud log (data/owncloud.log):

[owncloud-case.zip](https://github.com/owncloud/client/files/1261777/owncloud-case.zip)

My suggestion:
If (Windows client send "rename" command to server) and (uppercase (new_filename) == uppercase(old_filename)) then `mv old_filename new_filename"
That happens next - depends on Server-side filesystem. We have file_versions and deleted_files folders, and backup server for all cloud with "greedy" rsync, so we are secured against deletion. If you are not sure about this - give us option, on server-side, disabled by default. 
It's very annoying, to sync manually remote clients every day with hands. So, it's I - syncer, not owncloud ((

**Comment by michaelstingl** [comment]
Related: https://github.com/owncloud/documentation/issues/2832

**Comment by SamuAlfageme** [comment]
@count0-krsk tried to reproduce with these instructions and the ones on https://github.com/owncloud/client/issues/1348#issuecomment-323346005:

> Clients have many folders with sharing from one user to many other partially (some dirs to one group, some to other users). **Some users rename Folder locally to FOLDER, add some files to it.** Other see Folder with no new files and add their own. Then I must go to their PC's and sync manually...

So far I'm getting the rename of the folder correctly propagated to the server, this issue would only be possible, if I understood correctly, when both `SUBFILES` and `subfiles` are created in server (since the client ignores one of them). Will take a look at the logs to see if I can grasp something from there.

**Comment by count0-krsk** [comment]
@SamuAlfageme
Users don't use web interface, just their own directories on PC's

**Comment by SamuAlfageme** [comment]
@count0-krsk are the directories being renamed living on an external storage backends (i.e. WND, SMB...)

**Comment by count0-krsk** [comment]
@SamuAlfageme 
No, it's on ext4 hard drive. 
I try install OC on Windows, but no success. Now thinking about use ntfs or something like FS on linux, but truecrypt is only supported EXT* and FAT filesystems. We need truecrypt because data contains commercial classified information and personal information.

**Comment by ogoffart** [comment]
> My suggestion:
> If (Windows client send "rename" command to server) and (uppercase (new_filename) == uppercase(old_filename)) then `mv old_filename new_filename"

This is exactly what should happen.

I don't really know what to look for in the log provided. What were the files that cause problem in that log

I could not reproduce the problem.

Can you maybe come up with more accurate step on how to reproduce the problem?
The log file of the client would also help to detect what the client is doing exactly.

**Comment by count0-krsk** [comment]
OK, you are the best, mans. You cannot reproduce bug, that happens on 30+ PC's with different OS'es and ever after migrating to Nextcloud. 
I try with another side: that you do, trying reproduce bug? May be I must create virtual PC's and send it to you?
After Nextcloud we migrate to Netdrive and apache + dav plugin. It work excellent. Sync immediately  without many garbage traffic to server and large cache on client side. It was 6 months ago. And now you write that all OK ))) It was mirage ))

**Comment by ckamm** [comment]
@count0-krsk I understand you're frustrated, and I would be happy if we could fix the problem you're seeing. Unfortunately we currently don't understand the problem well enough to do anything about it.

What would help:
- To have a step-by-step description of how to reproduce the problem. It doesn't reproduce with the current steps for us, see https://github.com/owncloud/client/issues/5985#issuecomment-325933424
- Alternatively, if reproducing doesn't work, send client log files. See https://doc.owncloud.org/desktop/2.4/troubleshooting.html#saving-files-directly (use `--logdebug`, be aware that client logs have private information like filenames and metadata)

**Comment by count0-krsk** [comment]
OK, I found some logs despite removing owncloud folder from most of computers in winter.

[ownCloud-evgeniy.zip](https://github.com/owncloud/client/files/2027430/ownCloud-evgeniy.zip)
[ownCloud-user.zip](https://github.com/owncloud/client/files/2027527/ownCloud-user.zip)

**Comment by ckamm** [comment]
These are propagation logs and it's hard to make sense of them: What was the name of the case-changing folder? If these logs really capture an instance of the problem the curious thing would be no INST_RENAME being seen anywhere.

**Comment by count0-krsk** [comment]
OK, found log with INST_RENAME.
[owncloud-lena.zip](https://github.com/owncloud/client/files/2052007/owncloud-lena.zip)

**Comment by count0-krsk** [comment]
And even more ))
[user04-ownCloud.zip](https://github.com/owncloud/client/files/2111828/user04-ownCloud.zip)
[user15-ownCloud.zip](https://github.com/owncloud/client/files/2111829/user15-ownCloud.zip)
[user16-ownCloud.zip](https://github.com/owncloud/client/files/2111830/user16-ownCloud.zip)
[natalya.zip](https://github.com/owncloud/client/files/2111831/natalya.zip)
[sv2-ownCloud.zip](https://github.com/owncloud/client/files/2111832/sv2-ownCloud.zip)
[sv-ownCloud.zip](https://github.com/owncloud/client/files/2111833/sv-ownCloud.zip)
[user01-owncloud.zip](https://github.com/owncloud/client/files/2111834/user01-owncloud.zip)
[user02-ownCloud.zip](https://github.com/owncloud/client/files/2111835/user02-ownCloud.zip)
[user03-owncloud.zip](https://github.com/owncloud/client/files/2111836/user03-owncloud.zip)

**Comment by ogoffart** [comment]
I had a look at the log, but i wouldn't know what to look for.
(Note that there is a bug in SyncRunFileLog. When there is a INST_RENAME|Down in the log, we see the target twice)
Maybe this has to do with the russian locale. Maybe the case sensitive/insensitive matcher does not work.

**Comment by ogoffart** [comment]
I tried to reproduce, even with names in the cirilic alphabet, but everything works as expected.

Anyway, my guess it that when the user renamed Subfiles to SUBFILES, this was not detected as a rename for some reason and the folder ended up duplicated on the server.
If the folder is duplicated this behavior is expected. Or maybe the folder is not duplicated, the the fileid of the directory has changed and then it is no longer a rename.

@count0-krsk could you please tell us more precisely how we can reproduce this problem?
Also, more interresting would be the debug log ,which can be accessed by pressing F12, or by using the `--logfile` option.  (not the .owncloudsync.log file), and some information about what files exactly are failling.

**Comment by guruz** [comment]
(There is also the ```--logdebug``` option for making the log more verbose)

**Comment by ogoffart** [comment]
None of us were able to reproduce the issue. 

Without a way to reproduce, there is nothing we can do about this issue.

**Comment by count0-krsk** [comment]
> None of us were able to reproduce the issue.
> 
> Without a way to reproduce, there is nothing we can do about this issue.
May be sometime I create virtual machine with owncloud, reproduce it, and put link here.
