### ISSUE TITLE
Keynote files (.key) not syncing using desktop client on MacOS 10.12

### ISSUE THREAD

**Issue by LidhemRV** [owncloud/client#5987]
### Expected behaviour
The file should be uploaded to the server. When i change the extension of the file from .key to something else (exempel .ppt) then the file syncs without a problem. The extension .key seems to trigger the issue.

### Actual behaviour
A red X appears and the file is not loaded to the server.

### Steps to reproduce
Steps to reproduce

1. Create a new keynote file and save in Nextcloud folder
2. Desktop sync (both old and latest version) will not upload the file to server (red x)
3. In the log an errormessage is displayed

### Server configuration
Operating system:  Linux

Hosting Package | Professional
-- | --
Server Name | cpsrv19
cPanel Version | 66.0 (build 14)
Apache Version | 2.4.27
PHP Version | 5.6.31
MySQL Version | 10.0.32-MariaDB
Architecture | x86_64
Operating System | linux
Shared IP Address | 185.76.64.169
Path to Sendmail | /usr/sbin/sendmail
Path to Perl | /usr/bin/perl
Perl Version | 5.16.3
Kernel Version | 3.10.0-614.10.2.lve1.4.50.el7.x86_64

Web server: 
https://nextcloud.lidhem.se

Database:

MySQL

PHP version:
7.1

ownCloud version:

10.0.2

Storage backend (external storage):

### Client configuration
Client version: 2.3.2

Operating system: Macos 10.12.6

OS language: Swedish

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: 

# timestamp | duration | file | instruction | dir | modtime | etag | size | fileId | status | errorString | http result code | other size | other modtime | other etag | other fileId | other instruction
#=#=#=# Syncrun started  until  (0 msec)
#=#=#=# Syncrun started  until  (0 msec)
|0|01. LHV AB/f. daily business (Q)/seizoen info (werkdocumenten)/2017/gasteninfo 2017 .key|INST_NEW|Down|1495619084|7e1075564fc19e11c9ea4b8f303ce01a|15454550|00043327ocv0fa8f0bpk|2|Error downloading https://nextcloud.lidhem.se/remote.php/webdav/01. LHV AB/f. daily business (Q)/seizoen info (werkdocumenten)/2017/gasteninfo 2017 .key - server replied: Forbidden|403|0|0|||INST_NONE|
|0|01. LHV AB/faciliteiten en extras kopia.key|INST_NEW|Up|1504168205||769497||2|Error downloading https://nextcloud.lidhem.se/remote.php/webdav/01. LHV AB/faciliteiten en extras kopia.key - server replied: Forbidden|403|0|0|||INST_NONE|
|0|01. LHV AB/faciliteiten en extras test.key|INST_NEW|Up|1504169733||769491||2|Error downloading https://nextcloud.lidhem.se/remote.php/webdav/01. LHV AB/faciliteiten en extras test.key - server replied: Forbidden|403|0|0|||INST_NONE|
|0|01. LHV AB/faciliteiten en extras.key|INST_NEW|Up|1504168189||768468||2|Error downloading https://nextcloud.lidhem.se/remote.php/webdav/01. LHV AB/faciliteiten en extras.key - server replied: Forbidden|403|0|0|||INST_NONE|
|0|01. LHV AB/testrene2.key|INST_NEW|Down|1493409941|96f96c6a284f6e09278fdd9a545a91ca|321064|00042753ocv0fa8f0bpk|2|Error downloading https://nextcloud.lidhem.se/remote.php/webdav/01. LHV AB/testrene2.key - server replied: Forbidden|403|0|0|||INST_NONE|

2. Web server error log:

No errors on the serverside...

3. Server logfile: ownCloud log (data/owncloud.log):

No log entries wrt these files in the server

**Comment by hodyroff** [comment]
Sounds weird, can you reproduce against a standard ownCloud Server (demo.owncloud.com admin/admin) with 2.3.3. or even your client version, please? Does not sound ownCloud Desktop Client related.

**Comment by LidhemRV** [comment]
Thank you for your response, I tested with the demo server and it worked fine. My server configuration is also standard, so I checked all possible settings with my webhotel. And then I found something called ModSecurity which was switched on for this site. I switched it off and suddenly the sync worked fine again. Thank you for the small push in the right direction.

**Comment by hodyroff** [comment]
Perfect, thank you!
