### ISSUE TITLE
Feature Request: Auto Check Cert in Background 

### ISSUE THREAD

**Issue by benyanke** [owncloud/client#5990]
When connecting to a captive portal, NC's client will typically complain about a bad cert, as would be expected in a traffic intercept situation.

However, as soon as I connect to the captive portal and get connected to the internet, NC won't sync until you manually click "cancel" on the cert override window. Since the window usually gets pushed behind my browser while I'm authenticating to the portal, it's out of sight. Quite often, it is several minutes before I remember to find that window and click cancel, to allow NC to move on and sync with the server which it has had access to for several minutes.

**Feature Request:** I would like to propose that the client checks in the background repeatedly, and if it finds the cert issue fixed, it will silently remove the error dialog and starts the sync.

**Comment by guruz** [comment]
-> Dup https://github.com/owncloud/client/issues/3120
