### ISSUE TITLE
Repository on openSuse build service for Ubuntu not available

### ISSUE THREAD

**Issue by pjbroad** [owncloud/client#5991]
Owncloud's [website](https://owncloud.org/install/#install-clients) directs users to the [Suse Build service](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client) to get packages for the Linux desktop client.  While Centos, Fedora, Debian, openSUSE and Redhat packages are still available, Ubuntu packages for all versions have been silently removed.

1. Visit the  [Suse Build service](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client) site, no Ubuntu packages are listed.
2. If previously configure in you package manager, updates fail.  This also breaks automatic updates thus effecting system security until the repository is manually removed.

Operating system: Ubuntu Linux 16.04 (and all previous supported versions)
ownCloud version: All

**Comment by workingmachine** [comment]
Same problem here with Ubuntu 14.04 LTS (server).
I use owncloudcmd to synchronize server files to owncloud.

Operating system: Ubuntu Linux 14.04 Server
ownCloud version: All

**Comment by SamuAlfageme** [comment]
I think @jnweiger changed something in the naming schema for the xUbuntu* distros by what I read in https://github.com/owncloud/client/issues/5889#issuecomment-326542094

However, build results are all green for those distros in OBS: https://build.opensuse.org/package/show/isv:ownCloud:desktop/owncloud-client (also, [support for 14.04LTS](https://github.com/owncloud/client/wiki/OS-Support-Policy#ubuntu-lts) is missing on the OBS? cc/ @jnweiger)

**Comment by jnweiger** [comment]
The upcoming 2.3.3 release is not yet published. and the old 2.3.2 binaries were already removed. That is bad. Sorry for that.

For the time being, you can get a copy of 2.3.2 at https://build.opensuse.org/project/show/isv:ownCloud:desktop:client-2.3.2

**Comment by jnweiger** [comment]
the repo is back.

**Comment by glannes31** [comment]
And for 14.04 ? it's not back

**Comment by michaelstingl** [comment]
@glannes31 Please check the [policy for the supported Linux distributions](https://doc.owncloud.org/server/latest/admin_manual/installation/system_requirements.html#desktop) we added to our docs in April. (added with https://github.com/owncloud/documentation/pull/3001)

Please also check the post on ownCloud Central for discussions:
https://central.owncloud.org/t/desktop-sync-client-2-3-3-released/

**Comment by pjbroad** [comment]
Thanks for restoring the repo.
