### ISSUE TITLE
owncloud client crashed with "Inconsistency detected by ld.so" (SOLVED)

### ISSUE THREAD

**Issue by rasos** [owncloud/client#5992]
When launching owncloud client on a vanilla Xubuntu 16.04 , it crashed with 
`Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 517: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!`

 This is just for the records, how I fixed it.

`strace owncloud` was a bit more verbose and  showed a number of dependencies of the owncloud-client package.
```
writev(2, [{"Inconsistency detected by ld.so:"..., 33}, {"../sysdeps/x86_64/dl-machine.h", 30}, {": ", 2}, {"517", 3}, {": ", 2}, {"elf_machine_rela_relative", 25}, {": ", 2}, {"Assertion `", 11}, {"ELFW(R_TYPE) (reloc->r_info) == "..., 49}, {"' failed!\n", 10}], 10Inconsistency detected by ld.so: ../sysdeps/x86_64/dl-machine.h: 517: elf_machine_rela_relative: Assertion `ELFW(R_TYPE) (reloc->r_info) == R_X86_64_RELATIVE' failed!
) = 167
exit_group(127)                         = ?
+++ exited with 127 +++
```

Depends: libnextcloudsync0 (= 2.3.2-20170823.130651~xenial1), libc6 (>= 2.14), libgcc1 (>= 1:3.0), libqt5core5a (>= 5.5.0), libqt5dbus5 (>= 5.0.2), libqt5gui5 (>= 5.0.2) | libqt5gui5-gles (>= 5.0.2), libqt5keychain0 (>= 0.3.0), libqt5network5 (>= 5.4.0), libqt5webkit5 (>= 5.0.2), libqt5widgets5 (>= 5.2.0), libqt5xml5 (>= 5.0.2), libstdc++6 (>= 5.2), nextcloud-client-l10n

After re-installing some packages, the problem was fixed.    
sudo apt-get install --reinstall libqt5keychain0 libqt5network5 libqt5webkit5 libqt5widgets5 libqt5xml5 libstdc++6

ownCloud client version:
Version: 2.3.2-20170823.130651~xenial1

**Comment by ogoffart** [comment]
looks like it was a configuration problem.   Please try the latest version 2.3.3.
Also, it seems that this comes from the nextcloud packages and not the official owncloud packages.

Closing for now. Please re-open if you see a problem with the latest 2.3.3 pakages.
