### ISSUE TITLE
dependency problems on Debian 9

### ISSUE THREAD

**Issue by skriesch** [owncloud/client#5999]
A Debian user installed the ownCloud Client 2.3.3 and has got dependency problems:

> root@debian:/home/xyz/Téléchargements# dpkg -i owncloud-client_2.3.3-8294_i386.deb
Sélection du paquet owncloud-client:i386 précédemment désélectionné.
(Lecture de la base de données... 147651 fichiers et répertoires déjà installés.)
Préparation du dépaquetage de owncloud-client_2.3.3-8294_i386.deb ...
Dépaquetage de owncloud-client:i386 (2.3.3-8294) ...
dpkg: des problèmes de dépendances empêchent la configuration de owncloud-client:i386 :
owncloud-client:i386 dépend de libowncloudsync0 (= 2.3.3-8294) ; cependant :
Le paquet libowncloudsync0 n'est pas installé.
owncloud-client:i386 dépend de ocqt562-libqt5concurrent5 ; cependant :
Le paquet ocqt562-libqt5concurrent5 n'est pas installé.
owncloud-client:i386 dépend de ocqt562-libqt5core5a ; cependant :
Le paquet ocqt562-libqt5core5a n'est pas installé.
owncloud-client:i386 dépend de ocqt562-libqt5dbus5 ; cependant :
Le paquet ocqt562-libqt5dbus5 n'est pas installé.
owncloud-client:i386 dépend de ocqt562-libqt5gui5 ; cependant :
Le paquet ocqt562-libqt5gui5 n'est pas installé.
owncloud-client:i386 dépend de ocqt562-libqt5keychain1 ; cependant :
Le paquet ocqt562-libqt5keychain1 n'est pas installé.
owncloud-client:i386 dépend de ocqt562-libqt5network5 ; cependant :
Le paquet ocqt562-libqt5network5 n'est pas installé.
owncloud-client:i386 dépend de ocqt562-libqt5sql5 ; cependant :
Le paquet ocqt562-libqt5sql5 n'est pas installé.
owncloud-client:i386 dépend de ocqt562-libqt5webkit5 ; cependant :
Le paquet ocqt562-libqt5webkit5 n'est pas installé.
owncloud-client:i386 dépend de ocqt562-libqt5widgets5 ; cependant :
Le paquet ocqt562-libqt5widgets5 n'est pas installé.
owncloud-client:i386 dépend de ocqt562-libqt5xml5 ; cependant :
Le paquet ocqt562-libqt5xml5 n'est pas installé.
owncloud-client:i386 dépend de owncloud-client-l10n ; cependant :
Le paquet owncloud-client-l10n n'est pas installé.
owncloud-client:i386 dépend de ocqt562-libqt5sql5-sqlite ; cependant :
Le paquet ocqt562-libqt5sql5-sqlite n'est pas installé.

dpkg: erreur de traitement du paquet owncloud-client:i386 (--install) :
problèmes de dépendances - laissé non configuré
Traitement des actions différées (« triggers ») pour desktop-file-utils (0.23-1) ...
Traitement des actions différées (« triggers ») pour mime-support (3.60) ...
Traitement des actions différées (« triggers ») pour hicolor-icon-theme (0.15-1) ...
Des erreurs ont été rencontrées pendant l'exécution :
owncloud-client:i386

**Comment by michaelstingl** [comment]
Why i386?

Could you try again with official instructions?:
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

I tested following those instructions and wasn't able to reproduce in a debian:9 Docker (64-bit) and I wasn't able to reproduce in full-blown desktop Debian 9 (installed from debian-9.1.0-amd64-netinst.iso).

**Comment by jnweiger** [comment]
Question: "Le paquet libowncloudsync0 n'est pas installé" does that mean, you downloaded libowncloudsync0 and the system did not want to install it, or does that mean, that the system wanted to install the package and it was not there?

Sorry my french is lacking.

**Comment by skriesch** [comment]
The guy used the instructions on software.opensuse.org.
I explained it there: https://central.owncloud.org/t/own-cloud-desk-top-client-does-not-work-on-debian-9-i386/9283/12

It seems the system wanted to install the package and it wasn't there.

**Comment by guruz** [comment]
@skriesch I'm confused, your french log in the original report where is it from? 

I'm thinking of closing this, users should install via apt-get, not via dpkg..

**Comment by Flo354** [comment]
Same problem here with "apt" on debian 9

> apt-get install owncloud-client                                                                                                                                    
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

> The following packages have unmet dependencies:
 owncloud-client : Depends: libowncloudsync0 (= 2.3.4-8626) but it is not going to be installed
                   Depends: ocqt562-libqt5concurrent5 but it is not installable
                   Depends: ocqt562-libqt5core5a but it is not installable
                   Depends: ocqt562-libqt5dbus5 but it is not installable
                   Depends: ocqt562-libqt5gui5 but it is not installable
                   Depends: ocqt562-libqt5keychain1 but it is not installable
                   Depends: ocqt562-libqt5network5 but it is not installable
                   Depends: ocqt562-libqt5sql5 but it is not installable
                   Depends: ocqt562-libqt5webkit5 but it is not installable
                   Depends: ocqt562-libqt5widgets5 but it is not installable
                   Depends: ocqt562-libqt5xml5 but it is not installable
                   Depends: owncloud-client-l10n but it is not going to be installed
                   Depends: ocqt562-libqt5sql5-sqlite but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by jnweiger** [comment]
@Flo354 The Qt version 5.6.2 is our well tested version. We do not use system provided qt, even if it has a newer versions. There was too much unexplainable behaviour in the past with different qt versions.
We ship the needed 5.6.2 Qt packages also from https://software.opensuse.org//download.html?project=isv%3AownCloud%3Adesktop&package=owncloud-client

I've tried the install and it works fine for me.
For unknown reasons I am getting authentication warnings like this:
```
WARNING: The following packages cannot be authenticated!
  ocqt562-libqt5core5a ocqt562-libqt5dbus5 ocqt562-libqt5network5 ocqt562-libqt5gui5 ocqt562-libqt5widgets5
  ocqt562-libqt5opengl5 ocqt562-libqt5printsupport5 ocqt562-libqt5sql5 ocqt562-libqt5webkit5
  ocqt562-libqt5concurrent5 ocqt562-libqt5keychain1 libowncloudsync0 ocqt562-libqt5sql5-sqlite
  ocqt562-libqt5xml5 owncloud-client-l10n owncloud-client
Install these packages without verification? [y/N] 
```
But when accepting this, the install succeeds.

**Comment by Flo354** [comment]
@jnweiger thanks for your answer.

I understand, but I cannot install these packages on debian 9.3
The packages ocqt562-* don't exist, so I can't install them.

My owncloud-client.list : 

> deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0/ /

The result of the search for the packages

> [14:59:12] florian@florian-debian ~/Desktop % apt-cache search ocqt                                                                                                                                           
[14:59:13] florian@florian-debian ~/Desktop %  

The result of a manual install

> [14:59:13] florian@florian-debian ~/Desktop % sudo apt-get install ocqt562-libqt5concurrent5                                                                                                                  
[sudo] password for florian: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package ocqt562-libqt5concurrent5 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or is only available from another source
E: Package 'ocqt562-libqt5concurrent5' has no installation candidate

But what I don't understand is that the packages are present here:
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0/amd64/

**Comment by jnweiger** [comment]
is `apt-get update` showing any errors? 
`apt-cache policy ocqt562-libqt5webkit5` should print something like this:
```
ocqt562-libqt5webkit5:
  Installed: 5.6.2-1
  Candidate: 5.6.2-1
  Version table:
 *** 5.6.2-1 500
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  Packages
        100 /var/lib/dpkg/status
```

**Comment by jnweiger** [comment]
I am not exactly sure what is broken. If it is an issue with the mirrors, then you might be lucky using a different repo that has the same contents:

https://software.opensuse.org//download.html?project=isv:ownCloud:desktop:client-2.3.4&package=owncloud-client

Difference there is, this will remain at version 2.3.4 even after we publish the next release.
Whereas isv:owncloud:desktop will be updated with every release.

**Comment by Flo354** [comment]
It seems that the repo was the problem...

> [15:02:04] florian@florian-debian ~/Desktop % apt-cache policy ocqt562-libqt5webkit5                                                                                                                          
ocqt562-libqt5webkit5:
  Installed: (none)
  Candidate: (none)
  Version table:

I changed the repo, and then apt-get update : 

> [15:28:15] florian@florian-debian ~/Desktop % apt-cache policy ocqt562-libqt5webkit5                                                                                                                          
ocqt562-libqt5webkit5:
  Installed: (none)
  Candidate: 5.6.2-1
  Version table:
     5.6.2-1 500
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/client-2.3.4/Debian_9.0  Packages

And now owncloud is installed ;)

**Comment by Flo354** [comment]
An interesting thing... Right after installind owncloud I switched back to the initial owncloud repo, then apt-get update and tried an "upgrade".

> [15:31:03] florian@florian-debian ~/Desktop % sudo upgrade                                                                                                                                                    
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  ocqt562-libqt5concurrent5 ocqt562-libqt5core5a ocqt562-libqt5dbus5 ocqt562-libqt5gui5 ocqt562-libqt5keychain1 ocqt562-libqt5network5 ocqt562-libqt5opengl5 ocqt562-libqt5printsupport5 ocqt562-libqt5sql5
  ocqt562-libqt5sql5-sqlite ocqt562-libqt5widgets5 ocqt562-libqt5xml5
12 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 8,172 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  ocqt562-libqt5core5a 5.6.2-1+22.4 [1,813 kB]
Get:2 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  ocqt562-libqt5concurrent5 5.6.2-1+22.4 [60.8 kB]
Get:3 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  ocqt562-libqt5dbus5 5.6.2-1+22.4 [221 kB]
Get:4 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  ocqt562-libqt5network5 5.6.2-1+22.4 [588 kB]
Get:5 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  ocqt562-libqt5gui5 5.6.2-1+22.4 [2,511 kB]
Get:6 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  ocqt562-libqt5keychain1 0.7.0-1+4.13 [43.4 kB]
Get:7 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  ocqt562-libqt5widgets5 5.6.2-1+22.4 [2,233 kB]
Get:8 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  ocqt562-libqt5opengl5 5.6.2-1+22.4 [159 kB]
Get:9 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  ocqt562-libqt5printsupport5 5.6.2-1+22.4 [205 kB]
Get:10 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  ocqt562-libqt5sql5 5.6.2-1+22.4 [141 kB]
Get:11 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  ocqt562-libqt5sql5-sqlite 5.6.2-1+22.4 [69.0 kB]
Get:12 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  ocqt562-libqt5xml5 5.6.2-1+22.4 [125 kB]
Fetched 8,172 kB in 2s (3,329 kB/s)          
Reading changelogs... Done
(Reading database ... 275600 files and directories currently installed.)
Preparing to unpack .../00-ocqt562-libqt5core5a_5.6.2-1+22.4_amd64.deb ...
Unpacking ocqt562-libqt5core5a:amd64 (5.6.2-1+22.4) over (5.6.2-1+1.3) ...
Preparing to unpack .../01-ocqt562-libqt5concurrent5_5.6.2-1+22.4_amd64.deb ...
Unpacking ocqt562-libqt5concurrent5:amd64 (5.6.2-1+22.4) over (5.6.2-1+1.3) ...
Preparing to unpack .../02-ocqt562-libqt5dbus5_5.6.2-1+22.4_amd64.deb ...
Unpacking ocqt562-libqt5dbus5:amd64 (5.6.2-1+22.4) over (5.6.2-1+1.3) ...
Preparing to unpack .../03-ocqt562-libqt5network5_5.6.2-1+22.4_amd64.deb ...
Unpacking ocqt562-libqt5network5:amd64 (5.6.2-1+22.4) over (5.6.2-1+1.3) ...
Preparing to unpack .../04-ocqt562-libqt5gui5_5.6.2-1+22.4_amd64.deb ...
Unpacking ocqt562-libqt5gui5:amd64 (5.6.2-1+22.4) over (5.6.2-1+1.3) ...
Preparing to unpack .../05-ocqt562-libqt5keychain1_0.7.0-1+4.13_amd64.deb ...
Unpacking ocqt562-libqt5keychain1 (0.7.0-1+4.13) over (0.7.0-1+1.10) ...
Preparing to unpack .../06-ocqt562-libqt5widgets5_5.6.2-1+22.4_amd64.deb ...
Unpacking ocqt562-libqt5widgets5:amd64 (5.6.2-1+22.4) over (5.6.2-1+1.3) ...
Preparing to unpack .../07-ocqt562-libqt5opengl5_5.6.2-1+22.4_amd64.deb ...
Unpacking ocqt562-libqt5opengl5:amd64 (5.6.2-1+22.4) over (5.6.2-1+1.3) ...
Preparing to unpack .../08-ocqt562-libqt5printsupport5_5.6.2-1+22.4_amd64.deb ...
Unpacking ocqt562-libqt5printsupport5:amd64 (5.6.2-1+22.4) over (5.6.2-1+1.3) ...
Preparing to unpack .../09-ocqt562-libqt5sql5_5.6.2-1+22.4_amd64.deb ...
Unpacking ocqt562-libqt5sql5:amd64 (5.6.2-1+22.4) over (5.6.2-1+1.3) ...
Preparing to unpack .../10-ocqt562-libqt5sql5-sqlite_5.6.2-1+22.4_amd64.deb ...
Unpacking ocqt562-libqt5sql5-sqlite:amd64 (5.6.2-1+22.4) over (5.6.2-1+1.3) ...
Preparing to unpack .../11-ocqt562-libqt5xml5_5.6.2-1+22.4_amd64.deb ...
Unpacking ocqt562-libqt5xml5:amd64 (5.6.2-1+22.4) over (5.6.2-1+1.3) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...
Setting up ocqt562-libqt5core5a:amd64 (5.6.2-1+22.4) ...
Setting up ocqt562-libqt5concurrent5:amd64 (5.6.2-1+22.4) ...
Setting up ocqt562-libqt5sql5:amd64 (5.6.2-1+22.4) ...
Setting up ocqt562-libqt5xml5:amd64 (5.6.2-1+22.4) ...
Setting up ocqt562-libqt5dbus5:amd64 (5.6.2-1+22.4) ...
Setting up ocqt562-libqt5keychain1 (0.7.0-1+4.13) ...
Setting up ocqt562-libqt5network5:amd64 (5.6.2-1+22.4) ...
Setting up ocqt562-libqt5sql5-sqlite:amd64 (5.6.2-1+22.4) ...
Setting up ocqt562-libqt5gui5:amd64 (5.6.2-1+22.4) ...
Setting up ocqt562-libqt5widgets5:amd64 (5.6.2-1+22.4) ...
Setting up ocqt562-libqt5printsupport5:amd64 (5.6.2-1+22.4) ...
Setting up ocqt562-libqt5opengl5:amd64 (5.6.2-1+22.4) ...
Processing triggers for libc-bin (2.24-11+deb9u1) ...

The versions shipped is not the same...

**Comment by jnweiger** [comment]
great it works now!
There part after the + is the rebuild counter. It is insignificant.
So in the end after switching back and forth the main repo worked for you -- I am happy to know our infrastructure works -- but it leaves me puzzled what was wrong in your case. It is more likely that your apt was confused by something, which is now resolved.

**Comment by Flo354** [comment]
Thanks for your help. When it will be "officially" available, I will try to update with the main repo :)

**Comment by michaelstingl** [comment]
Works now (tested with `docker run -ti --rm debian:9`):

```
root@7123b2355edf:/# owncloudcmd --version
ownCloud version 2.4.0 (build 8911)
Git revision 9a1f736e306f135628e77bca5c1edeed8b1f3736
Using Qt 5.6.2, built against Qt 5.6.2
Using 'OpenSSL 1.0.2l  25 May 2017'
root@7123b2355edf:/# history
    1  apt update && apt install wget -y && apt-get install gnupg2 --no-install-recommends -y
    2  wget -nv https://download.opensuse.org/repositories/isv:ownCloud:desktop/Debian_9.0/Release.key -O Release.key
    3  apt-key add - < Release.key
    4  apt-get update
    5  echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0/ /' > /etc/apt/sources.list.d/owncloud-client.list 
    6  apt-get update
    7  apt-get install owncloud-client
    8  owncloudcmd --version
    9  history
```

**Comment by Flo354** [comment]
Ok, I successfully updated to the newest version. But it's weird, **apt-get upgrade** found nothing, I had to manually do **apt-get upgrade owncloud-client** to be able to install the version.

**Comment by herrdeh** [comment]
> manually do apt-get upgrade owncloud-client 
Thank you, you saved my life......, (-;
