### ISSUE TITLE
Loop in sync windows client when encounters files with path longer than MAX_PATH

### ISSUE THREAD

**Issue by blanch** [owncloud/client#60]
When PC files being synchronized, have path longer than MAX_PATH., sync ( version 1.1.1) 
loops 

Find attached a log where the loop can be seen

After several unsuccessful attemps to recover, loop begins after MAX_PATH error

====

10-31 15:37:10:608 csync.propagator - Remote repository atomar push enabled for ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos/survey.js (0).
10-31 15:37:10:608 csync.owncloud - => open called for ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos/survey.js
10-31 15:37:10:608 csync.owncloud - Stating directory ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos
10-31 15:37:10:608 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos called
10-31 15:37:10:608 csync.owncloud - stat results fetched.
10-31 15:37:10:654 csync.owncloud - Request failed, don't take session header.
10-31 15:37:10:654 csync.owncloud - WRN: propfind named failed with 1, request error: 404 Not Found
10-31 15:37:10:654 csync.owncloud - Session error string 404 Not Found
10-31 15:37:10:654 csync.owncloud - stat fails with errno 2
10-31 15:37:10:654 csync.owncloud - Directory ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos of file to open does NOT exist.
10-31 15:37:10:654 csync.propagator - file: ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos/survey.js, command: open(O_CREAT), error: 2
10-31 15:37:10:654 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos called
10-31 15:37:10:654 csync.owncloud - stat results fetched.
10-31 15:37:10:717 csync.owncloud - Request failed, don't take session header.
10-31 15:37:10:717 csync.owncloud - WRN: propfind named failed with 1, request error: 404 Not Found
10-31 15:37:10:717 csync.owncloud - Session error string 404 Not Found
10-31 15:37:10:717 csync.owncloud - stat fails with errno 2
10-31 15:37:10:717 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge) called
10-31 15:37:10:717 csync.owncloud - stat results fetched.
10-31 15:37:10:826 csync.owncloud - Simple propfind OK.
10-31 15:37:10:826 csync.owncloud - Server Date from HTTP header value: Wed, 31 Oct 2012 14:37:10 GMT
10-31 15:37:10:826 csync.owncloud - Ok: Time delta remained (almost) the same: 0.
10-31 15:37:10:826 csync.owncloud - Working on file z99 -- evolution (sourceforge)
10-31 15:37:10:826 csync.owncloud - STAT result from propfind: z99 -- evolution (sourceforge), md5: 5091379671e869.78918162
10-31 15:37:10:826 csync.owncloud - ERR: Path is too long for OS max path length!
10-31 15:37:10:826 csync.owncloud - => open called for ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos/survey.js
10-31 15:37:10:826 csync.owncloud - Stating directory ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos
10-31 15:37:10:826 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos called
10-31 15:37:10:826 csync.owncloud - stat results fetched.
10-31 15:37:10:873 csync.owncloud - Request failed, don't take session header.
10-31 15:37:10:873 csync.owncloud - WRN: propfind named failed with 1, request error: 404 Not Found
10-31 15:37:10:873 csync.owncloud - Session error string 404 Not Found
10-31 15:37:10:873 csync.owncloud - stat fails with errno 2
10-31 15:37:10:873 csync.owncloud - Directory ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos of file to open does NOT exist.
10-31 15:37:10:873 csync.propagator - file: ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos/survey.js, command: open(O_CREAT), error: 2
10-31 15:37:10:873 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos called
10-31 15:37:10:873 csync.owncloud - stat results fetched.
10-31 15:37:10:935 csync.owncloud - Request failed, don't take session header.
10-31 15:37:10:935 csync.owncloud - WRN: propfind named failed with 1, request error: 404 Not Found
10-31 15:37:10:935 csync.owncloud - Session error string 404 Not Found
10-31 15:37:10:935 csync.owncloud - stat fails with errno 2
10-31 15:37:10:935 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge) called
10-31 15:37:10:935 csync.owncloud - stat results from fs cache - md5: 5091379671e869.78918162
10-31 15:37:10:935 csync.owncloud - ERR: Path is too long for OS max path length!
10-31 15:37:10:935 csync.owncloud - => open called for ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos/survey.js
10-31 15:37:10:935 csync.owncloud - Stating directory ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos
10-31 15:37:10:935 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos called
10-31 15:37:10:935 csync.owncloud - stat results fetched.
10-31 15:37:10:982 csync.owncloud - Request failed, don't take session header.
10-31 15:37:10:982 csync.owncloud - WRN: propfind named failed with 1, request error: 404 Not Found
10-31 15:37:10:982 csync.owncloud - Session error string 404 Not Found
10-31 15:37:10:982 csync.owncloud - stat fails with errno 2
10-31 15:37:10:982 csync.owncloud - Directory ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos of file to open does NOT exist.
10-31 15:37:10:982 csync.propagator - file: ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos/survey.js, command: open(O_CREAT), error: 2
10-31 15:37:10:982 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos called
10-31 15:37:10:982 csync.owncloud - stat results fetched.
10-31 15:37:11:044 csync.owncloud - Request failed, don't take session header.
10-31 15:37:11:044 csync.owncloud - WRN: propfind named failed with 1, request error: 404 Not Found
10-31 15:37:11:044 csync.owncloud - Session error string 404 Not Found
10-31 15:37:11:044 csync.owncloud - stat fails with errno 2
10-31 15:37:11:044 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge) called
10-31 15:37:11:044 csync.owncloud - stat results from fs cache - md5: 5091379671e869.78918162
10-31 15:37:11:044 csync.owncloud - ERR: Path is too long for OS max path length!
10-31 15:37:11:044 csync.owncloud - => open called for ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos/survey.js
10-31 15:37:11:044 csync.owncloud - Stating directory ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos
10-31 15:37:11:044 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos called
10-31 15:37:11:044 csync.owncloud - stat results fetched.
10-31 15:37:11:091 csync.owncloud - Request failed, don't take session header.
10-31 15:37:11:091 csync.owncloud - WRN: propfind named failed with 1, request error: 404 Not Found
10-31 15:37:11:091 csync.owncloud - Session error string 404 Not Found
10-31 15:37:11:091 csync.owncloud - stat fails with errno 2
10-31 15:37:11:091 csync.owncloud - Directory ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos of file to open does NOT exist.
10-31 15:37:11:091 csync.propagator - file: ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos/survey.js, command: open(O_CREAT), error: 2
10-31 15:37:11:091 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos called
10-31 15:37:11:091 csync.owncloud - stat results fetched.
10-31 15:37:11:154 csync.owncloud - Request failed, don't take session header.
10-31 15:37:11:154 csync.owncloud - WRN: propfind named failed with 1, request error: 404 Not Found
10-31 15:37:11:154 csync.owncloud - Session error string 404 Not Found
10-31 15:37:11:154 csync.owncloud - stat fails with errno 2
10-31 15:37:11:154 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge) called
10-31 15:37:11:154 csync.owncloud - stat results from fs cache - md5: 5091379671e869.78918162
10-31 15:37:11:154 csync.owncloud - ERR: Path is too long for OS max path length!
10-31 15:37:11:154 csync.owncloud - => open called for ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos/survey.js
10-31 15:37:11:154 csync.owncloud - Stating directory ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos
10-31 15:37:11:154 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos called
10-31 15:37:11:154 csync.owncloud - stat results fetched.
10-31 15:37:11:216 csync.owncloud - Request failed, don't take session header.
10-31 15:37:11:216 csync.owncloud - WRN: propfind named failed with 1, request error: 404 Not Found
10-31 15:37:11:216 csync.owncloud - Session error string 404 Not Found
10-31 15:37:11:216 csync.owncloud - stat fails with errno 2
10-31 15:37:11:216 csync.owncloud - Directory ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos of file to open does NOT exist.
10-31 15:37:11:216 csync.propagator - file: ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos/survey.js, command: open(O_CREAT), error: 2
10-31 15:37:11:216 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos called
10-31 15:37:11:216 csync.owncloud - stat results fetched.
10-31 15:37:11:263 csync.owncloud - Request failed, don't take session header.
10-31 15:37:11:263 csync.owncloud - WRN: propfind named failed with 1, request error: 404 Not Found
10-31 15:37:11:263 csync.owncloud - Session error string 404 Not Found
10-31 15:37:11:263 csync.owncloud - stat fails with errno 2
10-31 15:37:11:263 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge) called
10-31 15:37:11:263 csync.owncloud - stat results from fs cache - md5: 5091379671e869.78918162
10-31 15:37:11:263 csync.owncloud - ERR: Path is too long for OS max path length!
10-31 15:37:11:263 csync.owncloud - => open called for ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos/survey.js
10-31 15:37:11:263 csync.owncloud - Stating directory ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos
10-31 15:37:11:263 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos called
10-31 15:37:11:263 csync.owncloud - stat results fetched.
10-31 15:37:11:310 csync.owncloud - Request failed, don't take session header.
10-31 15:37:11:310 csync.owncloud - WRN: propfind named failed with 1, request error: 404 Not Found
10-31 15:37:11:310 csync.owncloud - Session error string 404 Not Found
10-31 15:37:11:310 csync.owncloud - stat fails with errno 2
10-31 15:37:11:310 csync.owncloud - Directory ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos of file to open does NOT exist.
10-31 15:37:11:310 csync.propagator - file: ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos/survey.js, command: open(O_CREAT), error: 2
10-31 15:37:11:310 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos called
10-31 15:37:11:310 csync.owncloud - stat results fetched.
10-31 15:37:11:372 csync.owncloud - Request failed, don't take session header.
10-31 15:37:11:372 csync.owncloud - WRN: propfind named failed with 1, request error: 404 Not Found
10-31 15:37:11:372 csync.owncloud - Session error string 404 Not Found
10-31 15:37:11:372 csync.owncloud - stat fails with errno 2
10-31 15:37:11:372 csync.owncloud - owncloud_stat ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge) called
10-31 15:37:11:372 csync.owncloud - stat results from fs cache - md5: 5091379671e869.78918162
10-31 15:37:11:372 csync.owncloud - ERR: Path is too long for OS max path length!
10-31 15:37:11:372 csync.owncloud - => open called for ownclouds://owncloud.clinic.cat/owncloud/remote.php/webdav/dsk_prova_sync/z99 -- evolution (sourceforge)/REVISIÓN Las aplicaciones basadas en Windows que usan la variable de entorno TZ no pueden funcionar como se esperaba por los cambios en DST (KB932590)_archivos/survey.js

===

Best regards

Josep Blanch

**Comment by guruz** [comment]
@danimo Yes, you're missing the whole csync update phase

**Comment by edd--** [comment]
just tried the latest nightly of 1.8, problem still exists. Should this already be solved ?

**Comment by guruz** [comment]
@edd-- Unfortunately not.

Note to self: Possibly use the same hook mechanism as https://github.com/owncloud/client/issues/2507 (but single-threaded) to use Qt's ```QDirIterator``` (if performant enough). This should kill of csync's VIO for good and fix this issue.
(+ possible fix for ```csync_win32_set_file_hidden``` to use ```\\``` notation for long filenames)

**Comment by abika** [comment]
also a lot of "The system cannot find the path specified" errors here with the Windows client (only after updating to 1.7?).
Many user are affected, please fix this soon.

**Comment by cdamken** [comment]
I have also the problem, before 1.7.1 did work.

Log:
S3-ownCloud\Shared\owncloud\support\github-issues\client\60\Log File.txt

@MorrisJobke 

00002621

**Comment by bastiaenssenst** [comment]
I experience a similar problems with long dir/dir/dir/dir/file paths

**Comment by cdamken** [comment]
For some reason we have users now experiencing this issue after the upgrade to 1.7.1

**Comment by christianrj** [comment]
We now have many files not synchronizing in the Windows client, because they have a path with 260 characters or more . I hope this gets fixed soon.

**Comment by guruz** [comment]
TODO: One first measure is to change the temporary download file name creation to cut the ``` .myfile.doc``` prefix to 100 characters (or whatever number) (but not damage the path)

**Comment by michaelstingl** [comment]
@danimo @guruz Will this be fixed in 1.9.0 ? /cc @MorrisJobke 

00002801

**Comment by michaelstingl** [comment]
@danimo @guruz any news? /cc @MorrisJobke @dragotin

**Comment by danimo** [comment]
No

**Comment by cdamken** [comment]
I have another user with the same problem

@MorrisJobke 

00002982

**Comment by craigpg** [comment]
@dragotin, might need to bump the priority of this one out of the backlog as it's been reported more than once.

**Comment by dragotin** [comment]
@MTRichards

**Comment by ArtIntell** [comment]
As for me, I just change one function in /lib/private/files/view.php to let it work with utf8:
	private function assertPathLength($path) {
		$maxLen = min(PHP_MAXPATHLEN, 4000);
		$pathLen = mb_strlen($path, 'utf8');
		if ($pathLen>=$maxLen) {
			throw new \OCP\Files\InvalidPathException("Path length($pathLen) exceeds max path length($maxLen): $path");
		}
	}
Maybe, it's a bad idea, but in my test-server environment (Win7x64) and for cyrillic filenames works fine. Files synchronizing well.

**Comment by nunomazer** [comment]
Having serious problems here
ownCloud server 8.0.1 on Linux Debian
windows cliente 1.7.1 and 1.8.1

Similar problems as reported by "christianrj commented on 13 Mar":

> Lots of folders and files that are not synchronizing in the Windows client, because they have a path with 260 characters or more. The client keeps creating some sort of a temporary file, but not the file itself. Example: file name is myfile.doc. Instead of creating or updating the file, the client creates files similar to this: .myfile.doc.~487e and shows an error message in the log: The system cannot find the specified file.

When this happens some other folders are not synchronized even  do not presenting the error message

**Comment by dragotin** [comment]
@MTRichards sorry, but this is not in scope of 1.8.2. That will be a really intrusive thing. Please move to 2.0.

**Comment by guruz** [comment]
@nunomazer @christianrj The temporary download file name issue is fixed. If you're curious to try it we have nightly builds at http://download.owncloud.com/desktop/daily/ (Note that those builds are not QAed..)

**Comment by MTRichards** [comment]
@guruz, this is only part of the problem right? (just checking).

**Comment by cdamken** [comment]
@MTRichards @dragotin This has high priority for me, the problem is since Nov 6, 2012!

**Comment by moscicki** [comment]
Hello, our users also reported this problem. I agree with @cdamken. We cannot have critical data handing bugfixes to be bundled with major feature releases which always introduce a whole new set of problems (and need weeks if not months until they reach production quality level). That effectively pushes back the resolution of the problem by several long months.

**Comment by MTRichards** [comment]
@moscicki if we make this fix into a 1.8.4, would you upgrade to that and stay with it for now? Asking at this time, not committing, but I seek to understand.

**Comment by dragotin** [comment]
starting in branch https://github.com/owncloud/client/commits/winlongfilenames

**Comment by moscicki** [comment]
@MTRichards: I think this is what we are asking for - stable version with bugfix releases for a defined time (compatible with "enterprise" timelines).

**Comment by dragotin** [comment]
Pull request https://github.com/owncloud/client/pull/3390 was closed, but the branch was merged into master. This needs testing now.

**Comment by Dianafg76** [comment]
I tried this, and I have a way with 260 characters or more and sync well
Desktop v ownCloud-2.0.0.5255-nightly20150709-setup.exe

**Comment by Dianafg76** [comment]
If you sync the second time, appears this error.
![screen shot 2015-07-13 at 10 56 53](https://cloud.githubusercontent.com/assets/12032058/8646194/0312f10e-294e-11e5-92aa-89e7885f07e9.png)

Desktop v ownCloud-2.0.0.5264-nightly20150713-setup.exe   13
Server v {"installed":true,"maintenance":false,"version":"8.1.0.8","versionstring":"8.1 RC2","edition":"Enterprise"}

**Comment by dragotin** [comment]
@Dianafg76 what do you consider an error?

**Comment by cdamken** [comment]
@dragotin 
I tested 1.8.4 and ownCloud-2.0.0.5271-nightly20150714-setup.exe

1.8.4 in windows 8.1 
2.0.X in windows 7
server 7.0.7
[Client 1]
Steps to reproduce:
1.- [Client 1] in 1.8.4 created 2 folder with the length of 260 characters.
2.- [Client 1] try to create a file..... Not Possible
3.- [Client 1] Sync those folders.... Works!
4.- [Server] Log in server.
5.- [Server] create a file in the folder.... Works!
6.- [Client 2] Sync in 2.0....... Works!
7.- [Client 2] create a file in the folder .... Works!
8.- [Client 2] Sync those files ..... Works!
9.- [Client 1] Sync new files..... Works!
10.- [Client 1]  create a file in the folder (where previously was not possible).... Works!
11.- [Client 1]  create folder..... Not possible
12.- [Client 2] create folder..... Not possible
13.- [Server] create folder... Works!
14.- [Server] create files in the new folder... Works!
15.- [Client 1] Sync files and folders..... does not sync them!
16.- [Client 2] Sync files and folders..... does not sync them!

Restarted the 2 Sync-clients and folders are still not synced in both clients.

Results:
Folder created over 260 Characters (Path and File) are synced and works in both directions after created.
Files are synched too.
Folders under that folder aren't synced also the files.

**Comment by dragotin** [comment]
Testing with 1.8.4 does not make sense at all. It does not support long file names.

**Comment by cdamken** [comment]
@dragotin If you take the time to read it carefully what I wrote:

It tested both clients to see the differences, and 1.8.4 is working and syncing the large folders and the files.

BUT!,  The only difference is that the files are synced with a wrong names:

In 1.8.4:
14-Jul-15  12:58                 0 .Hola.txt.txt.~1bc
14-Jul-15  12:58                11 .Holas.txt.txt.~692
14-Jul-15  12:58                75 .TEst.txt.~7281
14-Jul-15  16:16    <DIR>          test

in 2.0:
07/14/2015  07:15 AM    <DIR>          ..
07/14/2015  03:04 AM                 0 Hola.txt.txt
07/14/2015  03:57 AM                11 Holas.txt.txt
07/14/2015  07:16 AM    <DIR>          test
07/14/2015  03:03 AM                75 TEst.txt

Another test that I saw: 
Creating in server a folder without spaces worked (see Test folder)
Creating in server  folder with spaces didn't work (you can't see: Test test test)

Tesing if it was possibly the length:
Creating in server the folder 1234567890 can be downloaded
Creating in server the folder 1234 56789 can't be downloaded

**Comment by dragotin** [comment]
@cdamken the "wrong names" you're seeing are the temporar files that were created by the download, while the rename to the final file name has failed. The log file would have told you. As said before, 1.8.4 is broken. **Please** stop nailing on that.

About the space issue: Can you reproduce that with 2,0.0 ?

**Comment by cdamken** [comment]
@dragotin Yes I can reproduce it... I wanted to show you today :smile:

**Comment by cdamken** [comment]
@dragotin btw:

> more ".Holas.txt.txt.~692"
hadgasdfasd

The content of the files in 1.8.4 is correct, only the name is wrong. 

I know that in theory 1.8.4 should not download it, but if someone use it now in a production system will download a lot of wrong filenames that will be synced when they upgrade to 2.0. Have you think about that too?

**Comment by dragotin** [comment]
@cdamken have you seen them being uploaded? They wont, because the pattern 
```
*.~*
```
is in the system ignore file list.

**Comment by cdamken** [comment]
@dragotin  I found the error why some folders were not synced... a space was at the end of the file too.

(I saw that in the log file)

**Comment by Dianafg76** [comment]
I tried this, and I have a way with 260 characters or more and sync well
 Desktop v ownCloud-2.0.0.2548-nightly20150720.pkg. 
I have a way with 260 characters or more and sync well
Desktop v ownCloud-2.0.0.5289-nightly20150720-setup.exe 

But I found this. If you have in Mac one folder with space in the end, and you going to the same folder in Windows, you don't have the folder. And if you goin to the Sync Activity you look this "Filename contains invalid characters that can not be sync cross platform"

**Comment by a-schild** [comment]
@Dianafg76 Windows does not support folders/files with blanks an the start and/or end of the names. So this is correct.

**Comment by Dianafg76** [comment]
@a-schild Ok, Thanks

**Comment by cdamken** [comment]
@guruz Tested with testpilotcloud :+1:  Works great!
