### ISSUE TITLE
Fedora Sync Client 2.3.3 version string contains "%{prerelease}"

### ISSUE THREAD

**Issue by timm2k** [owncloud/client#6000]
### Expected behaviour
Version 2.3.3 (build 8294).

### Actual behaviour
Version 2.3.3%{prerelease} (build 8294).

### Steps to reproduce
1. install Fedora 26
2. install ownCloud Sync Client repo
3. dnf install -y owncloud-client

### Client configuration
Client version:
2.3.3
Operating system:
Fedora 26
OS language:
German
Qt version used by client package (Linux only, see also Settings dialog):
5.6.2
Client package (From ownCloud or distro) (Linux only):
from ownCloud
Installation path of client:
default

**Comment by michaelstingl** [comment]
@SamuAlfageme Please check how to catch such naming glitches in automated testing.

**Comment by jnweiger** [comment]
that is strange. Investigating...

**Comment by jnweiger** [comment]
oh yeah. The empty variable in RPM is not the empty string. It is %nil. 
Pushing the fix in the nightly builds.

**Comment by jnweiger** [comment]
looks good. Rebuild of the released RPMs triggered.

**Comment by jnweiger** [comment]
fixed packages are public.thanks!
