### ISSUE TITLE
Check redirect handing with HttpCredentials

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6003]
2.4 has seen the introduction of OAuth2 in HttpCredentials and I have the inkling that this might have changed something with respect to how redirects are handled.

1. Check what happens when a configured server url suddenly becomes a redirect on startup in 2.3.3
2. Test the same scenario in 2.4, with basic auth and with oauth2.

**Comment by ckamm** [comment]
Test setup:
1. Have an ownCloud instance that's reachable as localhost/sub/status.php and localhost/other/status.php
2. Create an account pointing to localhost/sub, quit the client
3. Change localhost/sub/* to 301 redirect to localhost/other/$1
4. Start the client again. It should be able to connect to the configured account.

Results for 2.3 branch: works
Results for master branch: does not work

(note that the client doesn't respect the permanent redirect and always funnels all requests through the initially configured address)

**Comment by ckamm** [comment]
PR #6016 fixes redirects and oauth

**Comment by SamuAlfageme** [comment]
Both a single 301 redirection and also some more chained work out now in 2.4 as well. 👍 Closing here.

**Comment by ckamm** [comment]
Thanks for all the recent tests!
