### ISSUE TITLE
 QtKeychain in 3rdparty

### ISSUE THREAD

**Issue by hefee** [owncloud/client#6004]
Why you include an old version of qtkeychain 0.5.0 inside 3rdparty with 2.3.3? 

0.5.0 was released at 2015! But the newest 0.8.0 has for example an issue, that at least stops Debian of shipping it:
https://github.com/frankosterfeld/qtkeychain/issues/99

Please do not include every library,that you depend on in 3rdparty. It makes it much harder for distributions to package owncloud-client, because distributions needs to unbundle the complete mess afterwards. 
And at least document we you add a specific lib to 3rdparty and document this, why you do this!

**Comment by jnweiger** [comment]
Linux builds use qtkeychain-0.7.0 -- maybe we can just update that client/src/3rdparty/qtkeychain to use the same source and configure settings than we use in https://build.opensuse.org/package/show/isv:ownCloud:devel:Qt562:templatized/ocqt562-qt5keychain

**Comment by guruz** [comment]
Funny, this seems to be added mistakeninly in c8b3df6668469de07626141d3bf32cc894e6676d probably when i tried to do https://github.com/owncloud/client/issues/1416

**Comment by guruz** [comment]
Should be removed for 2.4 :)
