### ISSUE TITLE
Don't pack unnecessary stuff in the public tarball. Maybe there should be a separate public tarball

### ISSUE THREAD

**Issue by hefee** [owncloud/client#6005]
Hey,

I checked the new tarball 2.3.3 and because now libcrashreporter-qt is included the endproduct is GPL3+:
'''
src/3rdparty/libcrashreporter-qt/src/libcrashreporter-gui/CrashReporter.cpp
src/3rdparty/libcrashreporter-qt/src/libcrashreporter-gui/CrashReporter.h
src/3rdparty/libcrashreporter-qt/src/libcrashreporter-handler/Handler.cpp
src/3rdparty/libcrashreporter-qt/src/libcrashreporter-handler/Handler.h
'''

But even more problematic is that there are files, that are under Unicode license, that are marked as a not free license:
'''
src/3rdparty/libcrashreporter-qt/3rdparty/breakpad/common/convert_UTF.c
src/3rdparty/libcrashreporter-qt/3rdparty/breakpad/common/convert_UTF.h
'''

see https://lintian.debian.org/tags/license-problem-convert-utf-code.html

**Comment by dschmidt** [comment]
What license do we need for libcrashreporter? GPL2?

We can relicense that probably, I just need to check with a few people. 

The files in breakpad are more problematic, need to dig into this.

**Comment by dschmidt** [comment]
The explanation page lists a bunch of other packages using the same file(s)? 

Is this just a debian policy violation or also a gpl violation?

**Comment by jnweiger** [comment]
I suggest to generate two flavours of the source tar ball. The full one, and the downstream tar that would not contain crashreporter and other stuff that is not used anyway in linux packages.

Also remove the /binary/ folder with horrible stuff like binary/shell_integration/windows/Release/Win32/OCOverlays_x86.dll in this downstream tar!

**Comment by guruz** [comment]
... what @jnweiger said.

**Comment by hefee** [comment]
> What license do we need for libcrashreporter? GPL2?

well you say, that occ is GPL2+ so, it must be also GPL2+, otherwise the endproduct is GPL3+. That is not a vialation but than the occ is inderectly GPL3+. And I haven't looked deeply into the code how the things are linked together etc. so it may be okay to link to a GPL3+ lib, but for sure at the least libcrashreporter is GPL3+.

> the Unicode files

well Unicode company gives you the right to distribute and to make copy of the files. So they are okay to use, I don't know if you are allowed to use them in combination with GPL code, because the GPL says, that you have the right to modify the code, that the Unicode files don't give you. IMO they violating the GPL, but I'm not a laywer. 

> The explanation page lists a bunch of other packages using the same file(s)?

yes, but it is marked as error, what means, they really needs to fix it before the next upload...

> I suggest to generate two flavours of the source tar ball. The full one, and the downstream tar that would not contain crashreporter and other stuff that is not used anyway in linux packages.
 
oh interessting, that the crashreporter is not used under linux, this i don't see in the code... in the CMakeLists.txt i only see, that it is disabled for arm.

>Also remove the /binary/ folder with horrible stuff like binary/shell_integration/windows/Release/Win32/OCOverlays_x86.dll in this downstream tar!

When doing a free tar than completly. Currently I remove following from the tarball:

```
    admin
    binary
    shell_integration/windows
    shell_integration/MacOSX
    src/3rdparty/sqlite3
    src/3rdparty/libcrashreporter-qt/3rdparty/breakpad/common/convert_UTF.*
```

btw. that you are adding 3rdparty/libcrashreporter-qt and 3rdparty/qtkeychain in a minor release is not a really cool release management...

**Comment by guruz** [comment]
@hefee Would it be an option for you to use the git tag (v2.3.3) instead of the .tar.xz?

**Comment by dragotin** [comment]
Ok, thanks @hefee for digging this. I stopped the submit request to openSUSE Leap for now.

**Comment by hefee** [comment]
@dragotin 
I won't solve this issue, because for me as downstream it is not that important if it is GPL2+ or GPL3+ and the unicode files are excluded from the tarball I use.

**Comment by jnweiger** [comment]
@hefee  thanks for the list!
I've applied an rm -rf loop with these. Result is pushed into https://build.opensuse.org/package/show/isv:ownCloud:community:edge/owncloud-client
Would that tarball be DFSG free?

**Comment by hefee** [comment]
>If I were a lawyer, I'd argue that 'the right to freely use' includes modification and that the inclusion of the files itself already supports the Unicode standard. But alas, I am none.

Well nope, if you look at https://lintian.debian.org/tags/license-problem-convert-utf-code.html and than what DFSG#3 is https://www.debian.org/social_contract#guidelines, than you see a lawyer see this differently.

**Comment by jnweiger** [comment]
Saw that. Arguments can win and lose dependening how convincing a speaker is. Sadly that also applies to arguments amongst lawyers. I'd be much more interested to hear a comment from the Unicode authorities, if they intended their license the way it is currently being interpreted. 

In any case: Removing the files should settle the issue for us.

**Comment by ogoffart** [comment]
The crash reporter is in a git submodule and is not part of the client's git repository directly.
Furthemore, the crash reporter is only used on Windows and Mac and is not used on Linux. So I don't think debian should be impacted by the license of these files.

**Comment by hefee** [comment]
@ogoffart well at the moment you have added libcrashreporter to the tarball, so Debian needs to care about this! Also the current CMakeLists.txt is compiling with libcrashreporter, because it only disables it if it does not find "${CMAKE_CURRENT_SOURCE_DIR}/src/3rdparty/libcrashreporter-qt/CMakeLists.txt", what is true for everyone.

Please either update the CMakeLists.txt or do not ship libcrashreporter in the normal tarball.

**Comment by guruz** [comment]
@hefee @dragotin Please ```rm``` the crash reporter for now until we have found a solution for this. Since 2.3.3 we create all builds from that tar ball, but this was "zu viel des guten" it seems.

**Comment by dragotin** [comment]
Ok. I reworked the tar ball and it is on the way to Tumbleweed, and once it is there, I will push it also to Leap 42.3. 

For the record, my cleanup script looks like
```
rm -rf binary/ 
rm -rf src/3rdparty/libcrashreporter-qt 
rm -rf shell_integration/windows 
rm -rf shell_integration/MacOSX 
rm -rf src/3rdparty/libcrashreporter-qt/3rdparty/breakpad/common/convert_UTF.*
```

**Comment by guruz** [comment]
Added de8ab35cb3587a1c216d82f4ece0c35aa860f450 ...

Let's see if the script itself shows up the tarball.

**Comment by jnweiger** [comment]
If we run the script during tarball build, it will of course not show up... :-)

**Comment by jnweiger** [comment]
@hefee I wonder why we remove /admin .. this is not needed for a dfsg-free tarball, is it?
Not removing that could simplify the build toolchain ....

**Comment by hefee** [comment]
@jnweiger I removed it in Debian, because it is not needed there and I don't had to check the license for this directory.

There are several python, shell and svg without copyright informations. Also it is unclear if all files have been created by owncloud itself. So delete the complete admin folder was a shortcut. If you solve these license issues, than we don't have to remove it anymore.

Btw. also the clean_tarball.sh has no copyright header :)

> Is https://github.com/owncloud/client/blob/master/admin/osx/DS_Store.in considered non-free?

well that file it is not needed to build occ, so normally we can ignore it. IMO removing it, because this file has nothing to do in a tarball.

**Comment by jnweiger** [comment]
Yeah, let's push two more lines of code, and we have that folder optional. 
I am already removing the folder when generating my Linux tarballs (along with the other items discussed here). So if you pick one from the sources in obs, it should be already DFSG-free!

**Comment by guruz** [comment]
@hefee can this be closed with regards to 2.4.0? See the beta tarball -> https://owncloud.org/changelog/desktop/

**Comment by hefee** [comment]
Well the files are still inside the 2.4.0 beta tarball:
```
$find owncloudclient-2.4.0-beta1  -name 'convert_UTF*'
owncloudclient-2.4.0-beta1/src/3rdparty/libcrashreporter-qt/3rdparty/breakpad/common/convert_UTF.h
owncloudclient-2.4.0-beta1/src/3rdparty/libcrashreporter-qt/3rdparty/breakpad/common/convert_UTF.c
```

I thought you wanted to get rid of the libcrashreporter-qt completly in tarball. So for me the issue is not solved :D

**Comment by guruz** [comment]
Updated title and milestone.

**Comment by TheOneRing** [comment]
I'm right now digging through old issues AFAIK we still ship breakpad. 
@dschmidt is that really required? I mean we provide breakpad as an system package?

**Comment by dschmidt** [comment]
IIRC we just provide breakpad-tools via craft. 

Well, we would need proper releases for libcrashreporter-qt ...

**Comment by TheOneRing** [comment]
As only we are interested in the crash reporter we should use a system package on our ci.

TODO:
- remove the submodule
- add crashreproter to craft
- investigate new solution for the crash reporter
