### ISSUE TITLE
[Regression][Debian8] owncloud client symbol disappeared

### ISSUE THREAD

**Issue by Wikinaut** [owncloud/client#6008]
* Debian 8
* Owncloud  2.3.3: Gebaut von der GIT-Revision 57bc79 auf Sep 5 2017, 18:45:40 verwendet Qt 5.6.2, OpenSSL 1.0.1t 3 May 2016

#### Regression
After updating the version and debian, the owncloud symbol is no longer shown.

**Comment by michaelstingl** [comment]
"owncloud symbol" where? Could you post a screenshot?

**Comment by Wikinaut** [comment]
in the upper notification bar, close to the date/time information.

**Comment by Wikinaut** [comment]
reopenend https://github.com/owncloud/client/issues/5435 because of regression

closed this #6008 as duplicate to #5435

**Comment by guruz** [comment]
Do the latest 2.3.3 packages from https://owncloud.org/changelog/desktop/ work for @matlink @montanaviking @gwalarn ?

@Wikinaut What happens if you do
```QT_QPA_PLATFORMTHEME=generic owncloud```

**Comment by guruz** [comment]
@Wikinaut also try to give what @ckamm had said before in https://github.com/owncloud/client/issues/5435#issuecomment-271816524

**Comment by montanaviking** [comment]
Hi Markus,
In response to your question:
I'm running Ubuntu 14.04 64-bit and the latest package appears to work.
There was a glitch in setting it up as I got an error about an icon.
Redoing the Synaptic install (didn't have to uninstall) apparently cleared
up the error and the client appears to run.
Best,
Phil

**Comment by ckamm** [comment]
Also https://github.com/owncloud/client/issues/5435#issuecomment-271823342 and https://github.com/owncloud/client/issues/5435#issuecomment-273159521

**Comment by Wikinaut** [comment]
I upgraded my system now to debian 9 stretch, and moved build the nextcloud themed client. The behaviour is the same:  icon is sometimes present after user login, and sometimes not.

The process - ```\usr\bin\nextcloud``` in my case now - is running:

```
\_ lightdm --session-child 12 21
user  1332  0.0  0.1 420052 22472 ?        Ssl  08:38   0:00      \_ mate-session
user  1502  0.0  0.3 854256 56504 ?        SLl  08:38   0:00          \_ /usr/bin/nextcloud
```


@ckamm "It's also odd how it appears and goes away, given that the Qt dependency is nailed down now."

I still suppose an unsolved dependency or hiccup-sickness from qt5, because there were changes when updating the system (debian 8) in the last weeks.

**Comment by ckamm** [comment]
@Wikinaut Does the tray icon reproducibly appear when you quit and restart the client? Possibly owncloud starts before the systray is ready, or something?

**Comment by Wikinaut** [comment]
@ckamm No. Even restarting manually does not force the appearance of the tray icon.

**Comment by Wikinaut** [comment]
@ckamm but "kill (running nextcloud instance)" and "nextcloud" works

**Comment by ckamm** [comment]
@Wikinaut That sounds contradictory. :) So does restarting (with kill to guarantee it's actually restarting) reliably create the icon or not?

**Comment by Wikinaut** [comment]
@ckamm Yes, 100% reproducible:

```killall nextcloud; nextcloud &```

**Comment by guruz** [comment]
We're not responsible for the nextcloud builds.
Please try here: https://github.com/nextcloud/client_theming/issues

Or get an oC build: https://owncloud.org/changelog/desktop/ :-)

**Comment by Wikinaut** [comment]
@guruz Yes, I build it from  https://github.com/nextcloud/client_theming/issues . Same problem.

**Comment by Wikinaut** [comment]
Owncloud has the same problem, see my original posting!

**Comment by Wikinaut** [comment]
Problem - I use NextCloud - disappeared after yesterday's upgrading to debian 10.
