### ISSUE TITLE
tray icon flickrs from time to time

### ISSUE THREAD

**Issue by allo-** [owncloud/client#601]
the tray icon flickrs from time to time, even when no files are synced. 
I guess it flickrs each time the client checks for changes.

This is annoying, because it draws attention to the icon and distracts from working, even when there is nothing to see there.

Steps to reproduce:
- use mirall and sync at least one folder
- have no changes there
- observe the tray-icon (in kde (4.10) environment, not sure if this matters)

ownCloud Client Version 1.2.5
Built from Git revision b4e2e5 on Apr 23 2013, 14:48:16
using OCsync 0.70.6 and Qt 4.8.3.

**Comment by fetzerms** [comment]
I am experiencing the same problem with:

`client version 2.2.2  Qt 5.5.1  SSL  OpenSSL 1.0.2g-fips  1 Mar 2016`

I am running Xubuntu 16.04 (Xfce 4.12) and i am syncing **three folders**. Is this a regression bug? The flickering is quite fast, i am not sure if its actually disappearing or if its changing the icon.

**Comment by xHasKx** [comment]
Problem still presented - tray icon flickrs every 30 seconds. Screencast with 3 blinks: https://www.dropbox.com/s/o8mfowq3hkzym1y/scr2.mkv?dl=0 (download file to see in best quality)

```
$ lsb_release -d
Description:    Linux Mint 18 Sarah

$ uname -a
Linux acer 4.4.0-47-generic #68-Ubuntu SMP Wed Oct 26 19:39:52 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux`

$ dpkg -l | grep owncloud-client
ii  owncloud-client:amd64                                       2.2.4-1.3                                  amd64        The ownCloud sync client - github.com/owncloud/client
ii  owncloud-client-l10n                                        2.2.4-1.3                                  all          Internationalization files for ownCloud
```
