### ISSUE TITLE
Copies of unused? jquery and bootstrap in docs

### ISSUE THREAD

**Issue by hefee** [owncloud/client#6011]
Currently my Debian sid builds fails, because there are unknown versions of jquery/bootstrap versions:
```
dh_sphinxdoc: error: unknown JavaScript code: debian/owncloud-client-doc/usr/share/doc/owncloud-client/html/com/_static/jquery.js
dh_sphinxdoc: error: unknown JavaScript code: debian/owncloud-client-doc/usr/share/doc/owncloud-client/html/com/_static/bootstrap.js

```
So I started to search why there is jquery/bootstrap copy inside occ and it looks like at least jquery is only used for the owncloud_org theme:
```
% grep -r 'jquery[-.0-9]*\(min\|fix\)\?\.js'
doc/ocdoc/_shared_assets/themes/owncloud_org/layout.html             
```

and bootstrap:
```
% grep -r 'bootstrap[-.0-9]*\(min\|fix\)\?\.js'
doc/ocdoc/_shared_assets/themes/owncloud_release/layout.html
doc/ocdoc/_shared_assets/themes/bootstrap/layout.html
doc/ocdoc/_shared_assets/themes/owncloud_com/layout.html
doc/ocdoc/_shared_assets/themes/owncloud_org/layout.html
```

maybe somebody can explain me, why we need a copy of bootstrap/jquery and if I can safly replace them with system ons.

**Comment by michaelstingl** [comment]
@settermjd Can you help here?

**Comment by SamuAlfageme** [comment]
To avoid building the docs with the client we should use the`-WITH_DOC=FALSE` flag for cmake as stated in: https://doc.owncloud.org/desktop/2.3/building.html#generic-build-instructions (only used for manpages there, I think) - or even use it by default, since most of the time we might not want to build the docs locally.

**Comment by hefee** [comment]
Well the client is built with -WITH_DOC=FALSE by default. But for Debian we want the documentation built to ship it to the users! I think that the whole doc/ocdoc/_shared_assets was added to the released 2.3.3 tarball by accident. Because without this folder, occ just created the "unthemed" documentation like before. Here the relevant part of CMakeLists.txt, why I needed to handle several copies of the documentation:

```
    if (EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/ocdoc/_shared_assets")
       add_dependencies(doc doc-html-org)
       add_dependencies(doc doc-html-com)
    endif()
```

**Comment by michaelstingl** [comment]
`doc/ocdoc/` has been removed from master branch some time ago: https://github.com/owncloud/client/pull/5929

@settermjd @guruz Backport to 2.3?

**Comment by guruz** [comment]
CC @jnweiger for accidental tarball stuff..

I'd be ok with #5929 but then how can the docs be built by packagers? (CC @dragotin )

**Comment by hefee** [comment]
Well doc/ocdoc is not needed for the documention of the client in "unthemed" mode.
But according to #5929, why the hell are you deleting the manpages? doc/owncloud.1.rst and doc/owncloudcmd.1.rst

**Comment by guruz** [comment]
> Well doc/ocdoc is not needed for the documention of the client in "unthemed" mode.

Ah good!

> But according to #5929, why the hell are you deleting the manpages? doc/owncloud.1.rst and doc/owncloudcmd.1.rst

Because we don't want to maintain duplicate information. there is already ```--help```

**Comment by jnweiger** [comment]
Where do we have accidential tarball stuff? The doc/ocdoc is in the release branch. That is why it is included. 

Man page source are missing in master now, that is bad.

**Comment by michaelstingl** [comment]
`doc/owncloud.1.rst` and `doc/owncloudcmd.1.rst` and looked like super outdated duplicates of client docs, and it showed up in the search results from our docs, which was confusing. That's why I proposed to delete it. Sorry.

**Comment by jnweiger** [comment]
To avoid duplicate texts falling apart, we could try to format the client docs in a way that we can extract both the `--help` text and man page source from them. Looking in the direction of @settermjd  here... :-)

**Comment by hefee** [comment]
sorry but the manpages are not that outdated. for 2.3.3 owncloud manpage is okay and for owncloudcmd there are two/three things missing, but IMO not wrong.

**Comment by hefee** [comment]
> Where do we have accidential tarball stuff? The doc/ocdoc is in the release branch. That is why it is included.

Well before 2.3.3 all tarballs had NO ocdoc NO libqtkeychain and NO libcrashreporter-qt included. So for me it looks like an accident, that you guys have include these three subrepos in the release tarball with a minor release. Who wants to see this in real, can checkout the [debian repository](https://anonscm.debian.org/git/pkg-owncloud/owncloud-client.git) and look at the upstream branch. Especially at commit e2003b2f7091ce7feaff317ec4483107c611fa76, that has ~1700 new files that appead with 2.3.3 tarball.
