### ISSUE TITLE
Can't add pattern #*# to ignore list

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#6012]
One of our users can't add the pattern `#*#` to the client's ignore list. Trying to add this pattern manually into the `sync-exclude.lst` results in the client is deleting this entry. 

Our user wants to exclude temporary emacs files with this entry. 

Tested with v2.3.2 on Linux Mint 17.x.

@SamuAlfageme Any idea why this isn't working as expected?

00008148

**Comment by michaelstingl** [comment]
Some more thoughts:

> Maybe it has to do with the first `#`. I can add `*#*#`, but not `#*#`.
> The `#` is a comment in bash and some other files.
> Maybe it's the reason?
> 
> With the pattern `*#*#` I will ignore the file `#Test.txt#`, but it will ignore `a#test.txt#`, too. So, that's not a clean workaround.

**Comment by SamuAlfageme** [comment]
Indeed lines starting with `#` in the `sync-exclude.lst` are being ignored as comments: 

https://github.com/owncloud/client/blob/8be2aaa751f03088efc5600be1d20adc732526b3/src/csync/csync_exclude.cpp#L158-L168

We should provide a way to exclude these; i.e. escaping the pattern somehow.

**Comment by ckamm** [comment]
Simple suggestion: Allow \# to become #, and add a example comment to the default `sync-exclude.lst`

**Comment by SamuAlfageme** [comment]
👍 neat!
