### ISSUE TITLE
allow editing the account / domain in client

### ISSUE THREAD

**Issue by x9t9** [owncloud/client#6013]
This is more an enhancement than a bug , but : 

There should be some possibility to edit the host domain , under the account menu.

Last week , I had to change the domain of my OC server ( only domain - not the server itself ).
I had about 12 different devices with 20 accounts counting many many gigas of files , and I was very surprised to see that there is no option for editing the domain under the account menu .
( you can find "_add new_" , "_log out_" and "_Remove_" - but no "**edit**" or " **change**" or the likes .

Same is true for changing username or changing password [ which is somewhat available - not directly - only when pass is incorrect ] 

In my above scenario, none of the configurations changed - not the usernames, not the passwords, not the accounts or share settings for folders - only the domain - and it seems a bit absurd to delete all accounts on all machines and set up new ones from scratch ( that also opens the door to mistakes and data-loss )

I am not sure if I am missing something , and if there is already an exposed option to do that - but if not - it is a welcome enhancement ..

somewhat related : https://github.com/owncloud/client/issues/5075

**Comment by SamuAlfageme** [comment]
@x9t9 this is actually in the scope of https://github.com/owncloud/client/pull/6009 :

> During connectivity ping (ConnectionValidator) 
> status.php gets permanently redirected -> adjust url (new!)

It'll of course require you to set-up a redirection in your old server's endpoint but all clients will update transparently in exchange. 

Of course, you can always edit the [configuration file](https://doc.owncloud.org/desktop/2.3/advancedusage.html#configuration-file) (at your own risk), where you can find the `0\url=https://<your-old-server>` and point it to the new location.

Hope this helps!
