### ISSUE TITLE
Forbiden Error

### ISSUE THREAD

**Issue by marshallpp** [owncloud/client#6014]
### Expected behaviour
Norman Syncing

### Actual behaviour
Red cross and following errors on transfering

Error transferring https://www.jasperglobal.com/jaspercloud/remote.php/webdav/Cara Samways (Wuala Transfer)/CarasSpace/Company.NDA.MOU.Costings/UK/UKTI/UKTI.proposals.May16.xlsx - server replied: Forbidden (Sabre\DAV\Exception\Forbidden)|403|15618|1463054093|1daf0257daffb47d88ed438be1109958|00054985ocafd6abe1de|INST_NONE|

### Steps to reproduce
1.Just drop and wait to sync
2. 
3. 

### Server configuration
Operating system: Linux

Web server: Apache

Database: mysql

PHP version: 5.3

ownCloud version: 10.0

Storage backend (external storage): None

### Client configuration
Client version:

Operating system: Windows 10

OS language: Microsoft

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: https://www.jasperglobal.com/jaspercloud
[.owncloudsync.log.1.txt](https://github.com/owncloud/client/files/1290484/default.owncloudsync.log.1.txt)

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by phil-davis** [comment]
PHP 5.3 is well out-of-date - I am expecting to see PHP 5.6 7.0 or 7.1 on any ownCloud server.
Perhaps the server has the Firewall app, and something is actually being purposely blocked?
Or some other issue with the user account on the server?

This is a the bug-tracker for ownCloud. It is not at all clear if there is a bug here. I suggest that you report/discuss in https://central.owncloud.org/ where you will get more suitable and timely response to an issue like this. Also discuss with whoever administers the server.

**Comment by michaelstingl** [comment]
PHP 5.3 isn't supported with oC 10.0.x.

status.php says 9.1.4 (min. requirement PHP 5.4):
```
$ curl https://www.jasperglobal.com/jaspercloud/status.php | json_pp
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    95    0    95    0     0    154      0 --:--:-- --:--:-- --:--:--   154
{
   "version" : "9.1.4.2",
   "versionstring" : "9.1.4",
   "edition" : "",
   "maintenance" : false,
   "installed" : true
}
```

Client version not provided.
