### ISSUE TITLE
ChunkingNG test flaky on CI?

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6015]
Works fine for me locally.

Not working on 
https://jenkins.owncloud.org/job/owncloud-client/job/client/job/PR-5995/2/consoleFull
https://jenkins.owncloud.org/job/owncloud-client/job/client/job/master/378/console
Sometimes works on master
https://jenkins.owncloud.org/job/owncloud-client/job/client/job/master/379/console

**Comment by mrow4a** [comment]
You mean, investigate why it does not work on CI?

**Comment by guruz** [comment]
Why it SOMETIMES does not work on CI :)

Maybe you can also get it flaky on your local system?

Maybe some sleep() needed like in the other issue we had?

(btw, there was also this basicSync smashbox test flaky, not sure what is the state of this)

**Comment by mrow4a** [comment]
@tboerger is that related to our blasting fast CI now ?

**Comment by tboerger** [comment]
> @tboerger is that related to our blasting fast CI now ?

These tests are still running on the old Jenkins machine, so I don't think so.

**Comment by ckamm** [comment]
The key message from one of the failing logs: 

```
16: 09-05 14:45:42:669 [ warning sync.propagator ]:	Could not complete propagation of "A/a0" by OCC::PropagateDownloadFile(0x240aad0) with status 8 and error: "The download would reduce free local disk space below the limit"
```

The test creates a 150MB file, and I assume jenkins didn't have enough free space for that.

**Comment by guruz** [comment]
This is related to https://github.com/owncloud/enterprise/issues/2202 😡

**Comment by tboerger** [comment]
> This is related to owncloud/enterprise#2202 😡

It's not... The jenkins partition got more than enough free space 😡

**Comment by guruz** [comment]
Because it failed when there was not enough disk space, it doesn't fail now.
Closing for now then..
