### ISSUE TITLE
2.4 Alpha

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6019]
(Real release issue to be created)

For Alpha for sure:
* [x] Check PRs
* [x] Check auto tests
* [x] Check smashbox
* [x] https://github.com/owncloud/enterprise/issues/2253 Crash reporter symbol files
* [x] https://github.com/owncloud/client/pull/6048 allow us to server beta and rcs to users of alpha via auto updater

For beta:
*  [ ] https://kanboard.owncloud.com/project/1/task/1173 ming32 builds with up to date toolchain.
*  [x] https://kanboard.owncloud.com/project/31/task/1254 and https://github.com/owncloud/client/issues/5957  "upstream" packaging.diff
*  [x] https://github.com/owncloud/enterprise/issues/2134#issuecomment-314866103
*  [x] https://github.com/owncloud/enterprise/issues/2031

**Comment by SamuAlfageme** [comment]
@guruz should we create the 2.4 branch already? I've seen some PRs starting to make it to 2.5 milestone and being merged.

**Comment by SamuAlfageme** [comment]
We should try to fix https://github.com/owncloud/client/issues/6049 before the alpha release IMO, still need to find & comment the crash reports in the issue though.

**Comment by guruz** [comment]
(No branch yet as it would also imply changing transifex etc branches)

**Comment by guruz** [comment]
Alpha is released.
Moved rest of open checkboxes to https://github.com/owncloud/client/issues/6082
