### ISSUE TITLE
[mac OS] - Clicking on the padlock icon in settings is very slow

### ISSUE THREAD

**Issue by tomneedham** [owncloud/client#6031]
### Expected behaviour
Open the settings page. Click the padlock icon. Menu should appear

<img width="267" alt="screen shot 2017-09-13 at 23 48 11" src="https://user-images.githubusercontent.com/660805/30404472-bef7c4a6-98de-11e7-89f9-a9131da99601.png">

### Actual behaviour
Everytime I do this it takes about 4 seconds to load the menu, by which time I've clicked it a few more times

### Server configuration
Operating system: Ubuntu

Web server: Apache

Database: MySQL

PHP version: PHP 5.5

ownCloud version: 9.0.2

Storage backend (external storage): Local

### Client configuration
Client version: 2.3.3

Operating system:OSX 10.12.6

OS language: English

Installation path of client: /Applications

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

**Comment by SamuAlfageme** [comment]
@guruz @jturcotte we talked about this one some time ago and IIRC it was related to some Qt binding on macOS right?

**Comment by guruz** [comment]
Ha, @danimo 's legendary SSLButton :-)

**Comment by jturcotte** [comment]
Here is sample's output, it seems to spend most of its time in some parseXMLElement:
[Sample of owncloud.txt](https://github.com/owncloud/client/files/1302995/Sample.of.owncloud.txt)

**Comment by jturcotte** [comment]
Ah it's extracting the list of system CA certificates from the OS every time you click the button for some reason.

**Comment by guruz** [comment]
@ogoffart had improved the situation with 71dcf7fc37  .. I'll improve more
