### ISSUE TITLE
"re-login" adds / to serverpath, making request token link wrong

### ISSUE THREAD

**Issue by Emil-G** [owncloud/client#6044]
### Expected behaviour
When a user is for some reason logged out of ownCloud the login to existing account popup should use the correct server link. 

### Actual behaviour
For first time setup, adding the server url and then pressing "request token" takes the user to the correct link. But when the account is already added the request token link is wrong because the application adds an extra "/" to the path.

### Steps to reproduce
1. Login using token to server url : https://mysite.com/app/
2. Log out of client from "account -> log out" . 
3. Try to log back in on the already configured account using token. ("account -> log in" )
4. Pressing "request token" takes the user to : https://mysite.com/app//index.php/settings/personal?sectionid=security#apppasswords
5. User gets HTTP 500 error as the link now contains two // after app instead of one. 

### Server configuration
Operating system:
Red Hat
Web server: 
Apache
ownCloud version:
10.0.X

### Client configuration
Client version:
2.3.3 
Operating system:
Windows 7
OS language:
English

**Comment by ogoffart** [comment]
Fix: https://github.com/owncloud/client/pull/6047

**Comment by ogoffart** [comment]
btw, what is the exact version of the server?

**Comment by Emil-G** [comment]
10.0.2

**Comment by michaelstingl** [comment]
@Emil-G You could check with the [latest 2.4.0 nightlies](https://download.owncloud.com/desktop/daily/?C=M;O=D).

00008230

**Comment by Emil-G** [comment]
@michaelstingl hi, downloaded _testpilotcloud-2.4.0.8408-nightly20170925-setup.exe_ to test. 

It resolves the issue, but it adds one you should be aware of. Our normal branded client is www.mysite.com/app/ <- see the "/" at the end in ownBrander. When using the testpilot version, it seems to add a / on its own during initial login, making the "correct url" fail, so that I had to input www.mysite.com/app <- no "/" at the end to connect to server. 

Cheers,
Emil

**Comment by michaelstingl** [comment]
@ogoffart this is how @Emil-G 's `mysite-theme.h` looks like

```
    QString defaultServerFolder() const { return  QString::fromUtf8("/"); }
    QString quotaBaseFolder() const { return QString::fromUtf8("/"); }
    QString forceConfigAuthType() const { return QLatin1String("http"); }
      QString overrideServerUrl() const { return QLatin1String("https://mysite.com/app/"); }
     QString helpUrl() const { return QLatin1String("https://myothersite.com/link/e5a27e672d2445cda5beca1160f84404/"); }
    QString wizardUrlPostfix() const { return QLatin1String(""); }

        QColor wizardHeaderBackgroundColor() const { return QColor("#0000ffff"); }
    QColor wizardHeaderTitleColor() const { return QColor("#000000"); }
    QString wizardUrlHint() const { return QLatin1String(""); }
```

**Comment by ogoffart** [comment]
I fail to understand what is the problem now.
We should not add a second slash anymore in the nightly20170925
Or where is the second slash added now?

**Comment by michaelstingl** [comment]
I checked more ownBrander generated `oem-theme.h`'s and some have a fixed server URL with trailing "`/`", some have fixed server URL without trailing "`/`". @ogoffart Please make sure it works in all cases.

Example 1:
`QString overrideServerUrl() const { return QLatin1String("https://mysite.com/app/");`

Example 2:
`QString overrideServerUrl() const { return QLatin1String("https://mysite.com/app");`

**Comment by ogoffart** [comment]
@michaelstingl   make sure that what exactly work in all cases?   I don't think there should be a problem with or without the slash.  (Other than the problems that were just fixed)
It is possible that there are still locations were we add a double slash, but i don't know where that could be.

**Comment by michaelstingl** [comment]
> I don't think there should be a problem with or without the slash.

👍

**Comment by guruz** [comment]
https://central.owncloud.org/t/desktop-client-2-4-0-alpha1-released/9837

Want to test, @Emil-G ? :)

**Comment by Emil-G** [comment]
@guruz Hi, I have tested it, and it introduces the bug I described in my last comment:

The url I would normally input:
https://mysite.com/app/

Does not work with this release. Now I am forced to input this:
https://mysite.com/app//

Adding an extra "/" to the path to reach the correct server and be able to log on.

**Comment by ckamm** [comment]
@Emil-G I've tested with 2.4 but don't experience the same behavior.

I've tried the following variants:
* manual url: "http://localhost/sub"
* manual url: "http://localhost/sub/"
* overideServerUrl "http://localhost/sub"
* overideServerUrl "http://localhost/sub/"

And for all of these there is no double slash in the url when I click the link to request an app password from the web interface in the initial setup wizard.

How exactly can we reproduce the issue?

**Comment by Emil-G** [comment]
@ckamm Hi, there is no extra added by the client. However I have to either do "/app" or "/app//" for the client to connect to the correct server. "/app/" does no longer work in 2.4.

**Comment by ckamm** [comment]
@Emil-G Huh, for me the url with the trailing / works fine. I'll try again. Just to confirm:
* Start 2.4.0 alpha
* Trigger new account wizard
* Put in url ending with /app/, click next
* Click the link
* Be directed to an url that contains the string "/app//" ?

**Comment by Emil-G** [comment]
@ckamm It may be related to our enterprise setup where the servers located under / are not available from the outside, only the /app/ ones are.  I cannot post the URL here. But let me clarify that the client does not add the extra "/" I have to do that in order to be directed to the correct servers.

With 2.4 this works:
/app
/app//
With 2.4 this does not work:
/app/ directs to wrong servers, so that the client gets an 401 unauthorized.

This is fixable by putting /app in ownbrander I would assume, as in 2.4 the "request token" is working if I connect with /app and then do the logout/login test.

I think this can be closed.

Cheers!

**Comment by michaelstingl** [comment]
@SamuAlfageme please verify with a quick test with fixed serverURL and check the generation of URL's like app passwords, tokens, OAuth2 etc…

**Comment by SamuAlfageme** [comment]
All links generated from the client look sane, both for fixed (branded `overrideServerUrl()`'s) and for manual values. No malformed double slashes with the trailing '`/`'. 

👍
