### ISSUE TITLE
client crashes when storage unaccessable or read only mode

### ISSUE THREAD

**Issue by sentabi** [owncloud/client#6050]
### Expected behaviour
The  apps tell the folder is unaccessable, so it paused the sync.

### Actual behaviour
Aborted (core dumped), without explanation

### Steps to reproduce
I test this on dual boot system Windows 10 / Fedora 26. 
1. run owncloud client on read only system
2. owncloud client show nothing about what happen
3. using `strace` to debug 

### Client configuration
Client version:
ownCloud version 2.3.3 (build 8338)

Operating system:
Fedora 26 64 Bit

OS language:
English

### Logs
strace output
```
....
fcntl(18, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
fcntl(18, F_SETLK, {l_type=F_RDLCK, l_whence=SEEK_SET, l_start=1073741826, l_len=510}) = 0
fcntl(18, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=1073741824, l_len=1}) = 0
stat("/media/DATA/ownCloud/._sync_960e5fa11295.db-journal", 0x7ffdbb623360) = -1 ENOENT (No such file or directory)
stat("/media/DATA/ownCloud/._sync_960e5fa11295.db-wal", 0x7ffdbb623360) = -1 ENOENT (No such file or directory)
fstat(18, {st_mode=S_IFREG|0755, st_size=10104832, ...}) = 0
pread64(18, "SQLite format 3\0\20\0\2\2\0@  \0\0\0\31\0\0\t\243"..., 4096, 0) = 4096
getpid()                                = 2755
stat("/media/DATA/ownCloud/._sync_960e5fa11295.db", {st_mode=S_IFREG|0755, st_size=10104832, ...}) = 0
open("/media/DATA/ownCloud/._sync_960e5fa11295.db-wal", O_RDWR|O_CREAT|O_CLOEXEC, 0755) = -1 EROFS (Read-only file system)
open("/media/DATA/ownCloud/._sync_960e5fa11295.db-wal", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
fcntl(18, F_SETLK, {l_type=F_UNLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
rt_sigprocmask(SIG_UNBLOCK, [ABRT], NULL, 8) = 0
rt_sigprocmask(SIG_BLOCK, ~[RTMIN RT_1], [], 8) = 0
getpid()                                = 2755
gettid()                                = 2755
tgkill(2755, 2755, SIGABRT)             = 0
rt_sigprocmask(SIG_SETMASK, [], NULL, 8) = 0
--- SIGABRT {si_signo=SIGABRT, si_code=SI_TKILL, si_pid=2755, si_uid=1000} ---
+++ killed by SIGABRT (core dumped) +++
Aborted (core dumped)
...
```

**Comment by michaelstingl** [comment]
Related: https://github.com/owncloud/client/issues/6049

@SamuAlfageme Is this a regression introduced with 2.3.3 ?

**Comment by SamuAlfageme** [comment]
@michaelstingl most likely introduced by either https://github.com/owncloud/client/pull/5844 or the extended logging for SQlite. 

@sentabi will close here in favor of #6049. Follow up there. Thanks a bunch for reporting

**Comment by SamuAlfageme** [comment]
See https://github.com/owncloud/client/issues/6049#issuecomment-333533165

**Comment by guruz** [comment]
@sentabi Do you remember if this happened with earlier client versions too?

**Comment by sentabi** [comment]
@guruz sorry I can't remmember. 

another update : 

If I reboot my system but didn't mount disk where I store my owncloud files, owncloud client didn't crash. and show the right error (check screenshot below) 
![screenshot from 2017-10-08 20-46-44_blur](https://user-images.githubusercontent.com/203196/31317372-000f38fe-ac6a-11e7-966e-7033d7206801.png)

Problem appear if I boot to Windows (didn't disable *Fast startup*) 
- login to linux (Fedora)
- owncloud client will crash similiar with my first post. I can't mount drive where I store owncloud files.



if i disable *Fast startup* on Windows, Linux owncloud client didn't crash.

**Comment by ckamm** [comment]
@sentabi I'll try to reproduce by opening the client when the database file is on a read-only file system. It'd be awesome if you could give us the end of the log file as it crashed (`--logfile foo.txt`).

**Comment by ckamm** [comment]
I can reproduce it. Surprisingly sqlite3_open_v2 returns OK on readonly files when SQLITE_OPEN_READWRITE is requested. Then we think it's open and intentionally crash when preparing sql statements fails. Log excerpt:
```
10-27 11:08:47:886 [ debug default ]	[ OCC::SqlDatabase::openOrCreateReadWrite ]:	Opening "/home/kamm/tmp/ro-target/._sync_dba920715f43.db"
10-27 11:08:47:886 [ warning sync.database.sql ]:	Sqlite prepare statement error: "unable to open database file" in "PRAGMA quick_check;"
10-27 11:08:47:886 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "PRAGMA quick_check;"
10-27 11:08:47:886 [ warning sync.database.sql ]:	Can't exec query, statement unprepared.
10-27 11:08:47:886 [ warning sync.database.sql ]:	Error running quick_check on database
10-27 11:08:47:886 [ critical sync.database.sql ]:	Consistency check failed, removing broken db "/home/kamm/tmp/ro-target/._sync_dba920715f43.db"
10-27 11:08:47:887 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT sqlite_version();"
10-27 11:08:47:887 [ info sync.database ]:	sqlite3 version "3.16.2"
10-27 11:08:47:887 [ warning sync.database.sql ]:	Sqlite prepare statement error: "unable to open database file" in "PRAGMA journal_mode=WAL;"
10-27 11:08:47:887 [ fatal default ]:	ENFORCE: "allow_failure" in file /home/kamm/dev/woboq/mirall/mirall/src/common/ownsql.cpp, line 244 with message: SQLITE Prepare error
```

**Comment by ckamm** [comment]
@SamuAlfageme @sentabi I'd appreciate if you could test the 2.4 nightlies tomorrow.

**Comment by guruz** [comment]
@sentabi Any news? Nightlies from https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3Anightly&package=owncloud-client

**Comment by SamuAlfageme** [comment]
Cannot reproduce anymore neither on mounted storage that suddenly disappears nor local sync folders that were created and then made read-only. Let's close here 🎉 

Great work!
