### ISSUE TITLE
Can't Install client on Ubuntu 16.04.3 x64 and QT5.6.2

### ISSUE THREAD

**Issue by kemoc** [owncloud/client#6058]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?
    
### Expected behaviour
success for:
`
sudo apt install owncloud-client
`

### Actual behaviour
`
Do you want to continue? [Y/n] y
Err:1 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5core5a 5.6.2-1+22.1
  Protocol "http" not supported or disabled in libcurl
Err:2 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5dbus5 5.6.2-1+22.1
  Protocol "http" not supported or disabled in libcurl
Err:3 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5network5 5.6.2-1+22.1
  Protocol "http" not supported or disabled in libcurl
Err:4 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5gui5 5.6.2-1+22.1
  Protocol "http" not supported or disabled in libcurl
Err:5 https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  ocqt562-libqt5widgets5 5.6.2-1+22.1
  Protocol "http" not supported or disabled in libcurl
...
`

### Steps to reproduce
1. Installed Qt5.6.2 (instruction https://wiki.qt.io/Install_Qt_5_on_Ubuntu)
`
qmake -v
QMake version 3.0
Using Qt version 5.6.2 in /usr/lib/x86_64-linux-gnu/qt5.6/lib
`
2. i added owncloud repo for Ubuntu 16.04 instruction from link:
https://download.owncloud.com/repositories/desktop/download/

### Server configuration
Operating system: Ubuntu 16.04.3

Web server: apach2 2.4

Database: mariadb 10.0

PHP version: 5.6

ownCloud version: owncloud server 10.3, client probablu 2.3.3 but i'm not sure

Storage backend (external storage):

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:
no installed client, no log
3. Server logfile: ownCloud log (data/owncloud.log):
no client no log file

**Comment by michaelstingl** [comment]
@kemoc There is an issue in the OBS system. It already has been reported: https://bugzilla.opensuse.org/show_bug.cgi?id=1060231

You could use the backup repo created on ownCloud infrastructure instead:
https://download.owncloud.com/repositories/desktop/download
