### ISSUE TITLE
Activity alert for update available is missing the server context

### ISSUE THREAD

**Issue by jochenwezel** [owncloud/client#6059]
I've got this screen at my client:
![image](https://user-images.githubusercontent.com/3033827/30855757-5bbfe92c-a2b6-11e7-9ce6-a0f5ebe4186b.png)

The question for me is now: where do I have to update?
Is it
- the owncloud sync client? --> No, in tab "Allgemein" ("General") it shows that it's up-to-date
- one of the connected servers --> uuuhm, but which one? There are 5 servers connected...

Can you please provide some more details in the shown alert message so that I can identify the place to run the required update?

Thank you very much!

**Comment by SamuAlfageme** [comment]
@jochenwezel yup, the notification is indeed coming from one of your connected servers to update one of your apps, you can handle those on your ownCloud instance. 

And indeed, including the server URL originating the notification is pretty necessary here and was already suggested in https://github.com/owncloud/client/issues/5587. It will allow you to quickly identify where to go. However, starting on 2.3.3 the "dismiss" button should match the server's logic: https://github.com/owncloud/client/issues/5922

Closing here as duplicate, leave your 👍 on https://github.com/owncloud/client/issues/5587 to show your support. Thanks for reporting!
