### ISSUE TITLE
Windows client does not start at system start

### ISSUE THREAD

**Issue by timmersr** [owncloud/client#6062]
### Expected behaviour
Client should start if Start at system start is selected.

### Actual behaviour
The client does not start at system start. This behaviour has been observed on 5 PC's.

### Steps to reproduce
1. Select Start at system start in the settings, select Close.
2. Reboot de computer
3. 

### Server configuration
Operating system: Linux Ubuntu 16.04

Web server: Apache

Database: MySQL

PHP version: 7.0

NextCloud version: 12.0.3

Storage backend (external storage):

### Client configuration
Client version: 2.3.2 (build 1)

Operating system: Windows 10 Home version 1703 build 15063.608

OS language: Dutch

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: C:\Program Files (x86)\Nextcloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: (with F12, nothing related to startup issues)

2. Web server error log: N/A

3. Server logfile: ownCloud log (data/owncloud.log): N/A

**Comment by timmersr** [comment]
FYI: my workaround is Windows+R  **shell:startup**  and then add a shortcut to C:\Program Files (x86)\Nextcloud\nextcloud.exe

**Comment by hodyroff** [comment]
Please try with the ownCloud Client. I am pretty certain it will work. Otherwise comment and we'll reopen. Most recent version is 2.3.3
