### ISSUE TITLE
./OwnCloudCPack.cmake: line 1: syntax error near unexpected token `InstallRequiredSystemLibraries'

### ISSUE THREAD

**Issue by marwahalabi** [owncloud/client#6071]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
You just posted the default template without any further information.
How can we help you without further information?

**Comment by SamuAlfageme** [comment]
@marwahalabi for detailed instructions on how to build the client, please refer to https://doc.owncloud.org/desktop/latest/building.html. 

If you need further help w/the build process; you can ask with your particular details (platform, environment...) in https://central.owncloud.org/c/desktop-client/help
