### ISSUE TITLE
Waiting for sync - but it already syncs

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#6073]
### Expected behaviour
Syncing big files (8GB), the client should tell that he is in progress of syncing file xyz

### Actual behaviour
The screenshot shows that I have full bandwidth (server upload max is 5mb/s)
but the client says wayiting for sync. I know that there is the big file in progress because there is nothing else with that size. Activity just shows in the sync protocol the last successful transfer.
It would be great if there is:
a.) in the taskbar showing in the text that there is a file progress
b.) in the sync protocol the file beeing processed and the status "downloading"

![image](https://user-images.githubusercontent.com/3321281/31128630-a9e20698-a852-11e7-99ff-0c8285f9509d.png)

Edit: additionally it would be great, especially with long lasting syncing files, to see where we are like a % value in the size field at the sync protocol tab.

### Server configuration
Operating system: Ubuntu 16.04

Web server: nginx

Database: mysql

PHP version: 7

ownCloud version: 10.0.3

Storage backend (external storage):

### Client configuration
Client version: 2.3.3

Operating system: W10x64

OS language: German

**Comment by guruz** [comment]
@mmattel OK this sounds weird. It should for sure not show the "Wartet auf Beginn..." if it is actually syncing.

So stupid question maybe but: Are you sure the bandwidth graph you show is for the ownCloud client and not for something else going on? (Windows update, browser, Bittorrent ;-)

Or do you have multiple accounts set up in your client?

How can we reproduce this?

**Comment by mmattel** [comment]
I use the bandwidth monitor since years together with other tools like process monitors and others to identify possible "bandwidth eaters". In this case, no other processes consumed remarkable bandwidth.

At home where my server runs, the Internet upload bandwidth is 5Mbit . Because I tested from outside home, the upload bandwidth was the limiting factor. The download bandwidth where I tested was +100Mbit - so no limiting factor. The bandwidth monitor showed increased donwload when I concurrently added a short file download via a browser from another server = no problems.

Yes it is reproductable. You can easily try this with your environment.
Pause syncing (just to be sure...)
Save a big file eg 1-2GB via the browser on the server
Your client must download from outside the network where the server resides
Server upload bandwidth must be (much) lower as the download bandwidth of the location you are
Continue syncing
Watch...

**Comment by ckamm** [comment]
@mmattel Just to confirm again because it's so surprising. You reproduce like this:
* Go to owncloud client, pause everything.
* Upload a large file to the server
* Observe a large amount of downstream bandwidth

That shouldn't happen. Could you start the client with `--logfile log.txt` (https://doc.owncloud.org/desktop/2.3/troubleshooting.html#saving-files-directly) and try reproducing? Pick an easy to distinguish filename for the file that you're uploading. It shouldn't even appear in the log file.

**Comment by mmattel** [comment]
Will do.
Note to your item list: It is important that downloading MUST be outside the network of the server. It must go over the WAN not the LAN to get the bandwith limitation. Else a download might be too quick you may oversee the issue - what happens especially with small and medium files...

**Comment by mmattel** [comment]
Such things drive me nuts...
Started the client as described.
Now it tells me in the taskbar it is syncing.
The download will continue for the next 3h, currently no log is written.
Regarding the log, need to stop syncing and redo it because I need the bandwidth for business. 
The entries blacked out are because of security
It would be great if the item currently beeing synced is shown in the sync protocol with a (estimated) % status.

![image](https://user-images.githubusercontent.com/3321281/31275134-3e981972-aa96-11e7-9039-e0e1f341a105.png)
![image](https://user-images.githubusercontent.com/3321281/31275146-48a16eaa-aa96-11e7-9989-056c89009333.png)
![image](https://user-images.githubusercontent.com/3321281/31275275-ebc602f8-aa96-11e7-9714-061751fbdc9e.png)
![image](https://user-images.githubusercontent.com/3321281/31275326-1e084c3a-aa97-11e7-8b48-1548211b6d2c.png)

**Comment by ckamm** [comment]
@mmattel Thanks for testing! Too bad it didn't reproduce this time. Maybe abort the download, delete the file on the server and try again. 

A log should be written: make sure you get log outpuf working before trying to reproduce since we can't debug it otherwise. You can just start and quit the client and check that the log file contains data.

Your efforts to reproduce are much appreciated.

**Comment by ckamm** [comment]
Feel free to reopen if still relevant.
