### ISSUE TITLE
Setting window is too tall and rannot be made smaller (because of the general settings tab)

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#6075]
### Expected behaviour
Open the client, resize horizontally and vertically should be possibe as it was in W7

### Actual behaviour
Open the client, resize horizontally = works, resize vertically = will not do
It "feels" like this is (b)locked, moving the window works

### Client configuration
Client version: 2.3.3

Operating system: W10x64

OS language: German

**Comment by SamuAlfageme** [comment]
@mmattel hm, I can resize vertically, but only to make the window taller. Might have something to do with the `sizepolicy` set for https://github.com/owncloud/client/issues/5760 -> https://github.com/owncloud/client/commit/87a7642381858c298a3c3dbc4d3480701bf501e5 

Will take a look. Thanks for the tip!

**Comment by ogoffart** [comment]
The problem is that the general settings tab is too big.
We should re-design it, or split it, or make the about text shorter. (There is also some space that is wasted because a bug in which way Qt computes the minimum size when word wrap is activated for the about label.)

**Comment by ogoffart** [comment]
Note that we are talking about the minimum width of the settings dialog.  This is the case on every plaftorm and is not specific to Windows 10  (and Windows 7 had the same behavior)

@mmattel  can you confirm that you can indeed make the dialog veritcally bigger ?

**Comment by mmattel** [comment]
I guess you mean horizontally...
To be precise:
Horizontally: Left - Right: slimmer: yes
Vertically: Bottom - Top: shorter: no

**Comment by ogoffart** [comment]
@mmattel  But:  Vertically: Bottom - Top: bigger:  yes or no?

Anyway, I adjusted the title assuming yes.

**Comment by mmattel** [comment]
Vertically (y-axis) no resize possible

**Comment by SamuAlfageme** [comment]
@mmattel I'm testing with 2.4alpha (you also can give it a spin without conflicting with your current installation downloading the testpilotcloud version: https://download.owncloud.com/desktop/testing/testpilotcloud-2.4.0.8458alpha1-setup.exe) and I'm unable to reproduce: 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/31715639-f9d4aeae-b404-11e7-9a8a-e65bce991562.gif"/>
</p>

**Comment by mmattel** [comment]
Just tested.

I can make the window narrow or wider (x-axis is ok)
But not shorter or higher (y-axis not)

My NB has W10x64 Enterprise edition, 8GB Ram

**Comment by ckamm** [comment]
@mmattel Would it be correct to rephrase as: You can't reduce the vertical/y-axis size of the window because there is a minimum height? And with 200% scaling, the window is almost as big as your screen is, vertically?

I've tried reproducing on Windows 10 with various scalings and that's what I observe. It's not Win10 specific or a regression. The min vertical size of the General tab is just too big.

We could move the "About" text into a separate box that opens when you click a button? @ogoffart ?

**Comment by mmattel** [comment]
@ckamm yes this is correct.
Because beginning with the use of W10 recently with my NB which has a high resolution AND W10 suggest respectively sets as suggestion the scaling with the resultution of my NB, this issue first appeared even scaling was possible with W7.

Q: is it possible to read out if scaling is present and consider it mathematically in the min height setting? Somthing like ``min_height = min_constant / scaling_factor``

**Comment by ckamm** [comment]
@mmattel In my tests the minimum height was correct when the scaling factor was set. The minimum height derives from the height of the contents of the "General" tab. That means it's expected and correct that the minimum height for a scale setting of 200% would be about twice as big as on 100%.

I think we want to disable or reduce that height but need to make sure users don't miss important information because of it.

**Comment by ogoffart** [comment]
We should maybe redisign the general tab to make it smaller.

The version string is very long (and due to a bug in the way qt layout word-wrapped text, it extends a bit the minimum height)
The update part is usually saying "no update"  We could maybe hide that.

**Comment by guruz** [comment]
Dup in https://github.com/owncloud/client/issues/6215

**Comment by guruz** [comment]
Dup in https://github.com/owncloud/client/issues/6215 but for Fedora.

**Comment by chrpinedo** [comment]
The same happens with ArchLinux/GNOME. The app can't fit in the 12,5'' screen of my laptop.

**Comment by guruz** [comment]
@ogoffart What about moving the whole "About" section into a new QMessageBox/Dialog triggered from the tray menu?

**Comment by guruz** [comment]
Will be better with 2.5.0
https://github.com/owncloud/client/pull/6596
