### ISSUE TITLE
[Debian 8 Jessie] owncloud client not supported by owncloud server 10.0.3 

### ISSUE THREAD

**Issue by wioxjk** [owncloud/client#6076]
### Expected behaviour
Latest version should be available in the Debian 8 repository

### Actual behaviour
Latest version is not available in the Debian 8 repository

### Steps to reproduce
1. Try do install latest version of the Owncloud Sync client on a debian 8 based distro
2. Run Owncloud 10.0.3

### Server configuration
Operating system:
Debian 8

Web server: 
Apache/2.4.10 (Debian)

Database:
mysql  Ver 14.14 Distrib 5.5.57, for debian-linux-gnu (x86_64) using readline 6.3

PHP version:
PHP 7.0.23-1~dotdeb+8.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.23-1~dotdeb+8.1, Copyright (c) 1999-2017, by Zend Technologies

ownCloud version:
10.0.3

### Client configuration
Client version:
2.2.3

Operating system:
Bunsenlabs Linux (Debian 8 Jessie with Openbox preconfigured)

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
Installed from repository

1. Client logfile: 
"New ownCloud version 2.3.3 available. Please use the system's update tool to install it.

=====================

The 2.3.3 client is not available on the official debian 8 repository.
And yes, I have written on Owncloud Central about this.

```
root@jonte:/home/jonathan# apt-cache policy owncloud-client
owncloud-client:
  Installed: 2.2.3-1.1
  Candidate: 2.2.3-1.1
  Version table:
 *** 2.2.3-1.1 0
        500 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_8.0/  Packages
        100 /var/lib/dpkg/status
     1.7.0~beta1+really1.6.4+dfsg-1+deb8u1 0
        500 http://httpredir.debian.org/debian/ jessie/main amd64 Packages
        500 http://security.debian.org/ jessie/updates/main amd64 Packages

```

**Comment by hefee** [comment]
Well inside a relaesed version owncloud-client is never updated ( except for security issues). An overview about version available for Debian see [tracker](https://tracker.debian.org/pkg/owncloud-client). You see, that you can get a newer version via [backports](https://backports.debian.org/) (2.2.4). Keep in mind, that jessie is oldstable and do not get anymore much manpower updating it.

There is a team on Debian side taking care about ownclient-client, but currently we have no enough manpower to package and test a current owncloud-client for old Debian releases. Especially there should be people caring about the old Debian releases and testing the packages on these releases.If you want to help you are welcome to join the team: pkg-owncloud-maintainers@lists.alioth.debian.org

**Comment by wioxjk** [comment]
Thanks,
Installing if from backports does "solve" that.

**Comment by guruz** [comment]
(otherwise there is always the packages from https://owncloud.org/changelog/desktop/ ...)

**Comment by wioxjk** [comment]
@guruz 
That does not help as I mentioned above ;)

**Comment by kdslkdsaldsal** [comment]
@wioxjk 
> That does not help as I mentioned above ;)

Seems there is something broken in your apt setup causing this issue. Just to show that the repository linked is not providing the outdated 2.2.3 you get but the current 2.3.3 as expected:


![screenshot_2017-10-05_20-42-07](https://user-images.githubusercontent.com/25050304/31246467-c934a048-aa0d-11e7-8031-8ac34d01ec20.png)
