### ISSUE TITLE
[2.4.0.alpha1] Context menu for sharing not in Language OS

### ISSUE THREAD

**Issue by glannes31** [owncloud/client#6085]
I'm a french user and when i share a file or folder with the client, the context menu is in english.

### Expected behaviour
Context menu for sharing in french

### Actual behaviour
Context menu for sharing in english

### Steps to reproduce
1. Right click on a file or folder that you want to share
2. See the incorrect language

### Server configuration
Operating system:  Redhat

Web server:  Apache

Database: MariaDB 

PHP version:7.1

ownCloud version:10.0.2

Storage backend (external storage):

### Client configuration
Client version: 2.4.0.alpha1

Operating system: WIndows 7

OS language:French 

![bug_owncloud](https://user-images.githubusercontent.com/20032648/31327287-9d8c1a98-acce-11e7-9b57-a5d618a8c7a1.jpg)

**Comment by ckamm** [comment]
@glannes31 Thanks for the report! This happens because these strings are new in 2.4 and haven't been translated yet. The translation is done on https://www.transifex.com/owncloud-org/owncloud/ if you're interested in helping out.
