### ISSUE TITLE
Make use of Content-md5 header for checksum purposes

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6088]
@DeepDiver1975: @guruz pinged me about letting the client handle that header similarly to the `oc-checksums` header for object storage integration. You've not started working on that aspect right? 

Concretely I'd grab the header on GET replies and use it for transmission validation.

**Comment by guruz** [comment]
(Should be a three-liner I think, moving 2.4)

**Comment by ckamm** [comment]
@guruz agreed

**Comment by SamuAlfageme** [comment]
👍
