### ISSUE TITLE
Still download/upload file is 0KB

### ISSUE THREAD

**Issue by ryankkim** [owncloud/client#6089]
We deployed owncloud 10.0.3

and made Network drive Z: location is http://demo-ni.cloudrim.co.kr/remote.php/webdav/

and then..  we start web brower IE11 to download an attachment via email system.

When we download some file directly into Network drive Z. After complete downloading.
We can see that file detail attribute size is 0 KB with right clicking. So we can not open that file with any application.

Please give me solution that problem

[zerosize.pdf](https://github.com/owncloud/client/files/1371132/zerosize.pdf)

**Comment by ryankkim** [comment]
We can open the correct file though Web interface.  but We cannot open that file though Network drive.

**Comment by ryankkim** [comment]
After rebooting laptop computer. I can open that file though Network drive.
Without rebooting, Can I fix this problem? please help me

**Comment by ryankkim** [comment]
After rebooting my labtop, I can open that file correctly.
Whitout rebooting, can I fix this problem. please help me out.

**Comment by guruz** [comment]
It's hard to help if you don't mention any version information and don't fill out template or logs :-)

**Comment by ckamm** [comment]
The client isn't involved here, right? I think they download some file from the browser to the webdav-network-drive and it's not working correctly?

**Comment by ryankkim** [comment]
Yes. You are correct.  Have you experienced the same case?

**Comment by ryankkim** [comment]
@ckamm If so,  Please share your insight with us.

**Comment by ckamm** [comment]
@ryankkim I haven't reproduced it, I was just trying to understand. This is not an issue relating to the synchronization client. Most probably it's a problem with the interaction of the oC server's webdav with the windows network drive webdav implementation.

If you don't have a strong reason to prefer using webdav directly I recommend you use the ownCloud client to keep your files in sync with the folder instead. That should make this problem go away.
