### ISSUE TITLE
[cernbox] handling of colons and other characters (#5964 continued)

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#6092]
#5964 was closed but I still believe it is not fixed.

Just tried with 2.3.3 client on Linux. Are we missing a server capability or some client setting to enable these characters? Screenshot attached.

![image](https://user-images.githubusercontent.com/621965/31447643-c8617242-aea2-11e7-95b5-cd748baccd76.png)

**Comment by ckamm** [comment]
@moscicki Ah, that explains it! What you're seeing is behavior that's only switched on for server versions < 8.1.0. Probably from then on the client started to trust the server about which characters are allowed and which aren't.

Proposal: Add a capability for this to allow your server to also have authority about invalid path names.

**Comment by guruz** [comment]
@moscicki Please test tomorrow morning's 2.4 nightlies.

**Comment by moscicki** [comment]
Thank you for this patch. We tested it in our environment and it works as expected.

**Comment by guruz** [comment]
hooray
