### ISSUE TITLE
Use an "account-aware" local sync folder name in the multiaccount/server scenario

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6100]
Following the discussion in https://github.com/owncloud/client/issues/5597#issuecomment-304641252

> @pmaier1 we discussed this one a really long time ago. It was about using more clear names for the sync folders on the multiaccount scenario to distinguish. Only problem is the length of the names when not syncing the root (see example below)
> 
> If I understood correctly https://github.com/owncloud/client/issues/5295 that would be helpful to organize all the accounts in the client(s). Imagine the scenario with both a branded and unbranded client that displays 2 top-level dropdowns on the explorer's sidebar (1 per client): 
> 
> - `ownCloud` (unbranded)
>     - `demo@demo.owncloud.com`
>     - `Photos - admin@demo.owncloud.com` - [when the root is not the folder to sync]
> - `testpilotCloud` (branded client)
>     - `user1@private.server.tld`

**Comment by guruz** [comment]
BTW what is displayed in Explorer in the side bar can be different from what we actually create on the file system. (https://github.com/owncloud/client/issues/5295)
Just wanted to mention tht.

FYI @jturcotte

**Comment by SamuAlfageme** [comment]
I really like how this was handled for the cloud provider integration in Win10 (see https://github.com/owncloud/client/pull/6113#issuecomment-338626327) 

Extend the naming schema to the rest of the platforms?

**Comment by ogoffart** [comment]
Closing old issue.
Please re-open if there is still something we should do.
