### ISSUE TITLE
Building ownCloud client on macOS fails

### ISSUE THREAD

**Issue by settermjd** [owncloud/client#6103]
### Expected Behaviour

I was expecting the client to build successfully

### Actual Behaviour

I received the following build error

```console
** BUILD FAILED **


The following build commands failed:
	PhaseScriptExecution Run\ Script /Users/settermjd/Documents/Business/Clients/Current\ Clients/ownCloud/software/client/shell_integration/MacOSX/OwnCloudFinderSync.build/Release/FinderSyncExt.build/Script-5B3335471CA058E200E11A45.sh
(1 failure)
make[2]: *** [shell_integration/MacOSX/CMakeFiles/mac_overlayplugin] Error 65
make[1]: *** [shell_integration/MacOSX/CMakeFiles/mac_overlayplugin.dir/all] Error 2
make: *** [all] Error 2
```

### Steps to reproduce

1.  Complete up to step 4 in [the generic build instructions](https://doc.owncloud.org/desktop/2.3/building.html#generic-build-instructions).

### Server configuration

Operating system: macOS 10.13 High Sierra

**Comment by guruz** [comment]
Let's follow up via chat
