### ISSUE TITLE
[SAML] When prompting the QtWebview and clicking the tray icon the wizard is still visible and empty

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6105]
@ogoffart same as it happened in https://github.com/owncloud/client/issues/5813 for OAuth2 auth. flow, this time in SAML

**Comment by SamuAlfageme** [comment]
Just tested & working like a charm now 👍 

Can we disable the "Add new account" option from the tray menu since it does nothing while the webview is open?

**Comment by ogoffart** [comment]
> Can we disable the "Add new account" option from the tray menu since it does nothing while the webview is open?

We could, but we can easily raise the wizard in that case: https://github.com/owncloud/client/pull/6111

**Comment by SamuAlfageme** [comment]
WFM 👍
