### ISSUE TITLE
nighly-2.4.0 fails on Debian7

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6112]
[  439s] In file included from /usr/src/packages/BUILD/src/gui/synclogdialog.h:19:0,
[  439s]                  from /usr/src/packages/BUILD/src/gui/generalsettings.cpp:24:
[  439s] /usr/src/packages/BUILD/src/gui/protocolwidget.h:46:28: error: 'QTreeWidgetItem::QTreeWidgetItem' names constructor

Is there some language feature not supported by that prehistoric ancient compiler version?
g++ --version
g++ (Debian 4.7.2-5) 4.7.2

**Comment by ogoffart** [comment]
Apparently that's inheriting constructor. (the `using QTreeWidgetItem::QTreeWidgetItem;`)
Any chance to upgrade the compiler? 
Otherwise we need to manually write the constructor for this class.

**Comment by jnweiger** [comment]
@michaelstingl how about officially deprecating Debian7 support? We still have the two latest Debian9, and Debian8.

**Comment by michaelstingl** [comment]
@jnweiger Debian 7 won't be supported with the release after the 2.3.3:
https://owncloud.org/changelog/desktop/#233

**Comment by SamuAlfageme** [comment]
https://github.com/owncloud/client/pull/6093 was only targeted at 2.4.0 so no problem disabling the Deb7 builds on nightly (and all those not supported anymoar). Close here?

**Comment by jnweiger** [comment]
the templates for 2.3 and 2.4 branch are already split. Debian7 removed from the 2.4 templates. 
Close here with fire! WONTFIX
