### ISSUE TITLE
Wizard errors show mystery /owncloud/ path

### ISSUE THREAD

**Issue by peakovsky** [owncloud/client#6116]
### Expected behaviour
Want to connect windows client to server

### Actual behaviour
Cannot see status.php
Client automatically adds /owncloud/ to the path which does not exist in real path
So instead of trying to connect to my server at _mirzabad.com/cloud/status.php_ it tries to connect to _mirzabad.com/cloud/owncloud/status.php_

### Server configuration
Operating system:
Windows 10

**Comment by peakovsky** [comment]
![image](https://user-images.githubusercontent.com/33043692/31917976-53d9b922-b828-11e7-886f-4747ddf91678.png)

**Comment by ckamm** [comment]
This is an issue with the error message. The client secretly also tries appending /owncloud/ for backwards-compatibility. But only after reaching the user's path failed. 

@peakovsky Probably the server isn't reachable or replies incorrectly. Check if you can access /cloud/status.php on your server.

**Comment by ckamm** [comment]
PR to improve error message: https://github.com/owncloud/client/pull/6122

**Comment by peakovsky** [comment]
Unfortunately I cannot reproduce the issue. I went back and this time installed the server on a folder called "owncloud" and setup went through.
