### ISSUE TITLE
Systray status icon missing when client starts before systray

### ISSUE THREAD

**Issue by RalfJung** [owncloud/client#6117]
### Expected behaviour
The systray status icon sometimes disappears even though ownCloud clients keeps running.

### Actual behaviour
The status icon should not disappear.

### Steps to reproduce
1. Start owncloud
2. Suspend and resume the system a couple of times and plug an external screen in and out

### Client configuration
Client version: 2.3.3

Operating system: Linux, Debian, Gnome, with Topicon plus extension

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):
The settings dialog dosn't say anything, but I have Qt 5.9.1 installed.

Client package (From ownCloud or distro) (Linux only): distro (Debian)

Installation path of client: /usr (?)

### Logs

The problem is not reproducible, so I have not managed to collect logs yet.

**Comment by ckamm** [comment]
The client never explicitly hides itself so this is likely a bug in Qt or the tray icon implementation. At best we could attempt to work around it by doing `hide(); show();` on the tray icon. (but not too often, that's caused performance problems with some tray implementations in the past)

**Comment by RalfJung** [comment]
Closer observation showed that actually this only seems to happen when ownCloud autostarts on log-in. Probably owncloud starts so early that Gnome shell has not yet set up the systray, and hence it does not work.

I will edit the .desktop file to include a delay; maybe including that upstream would make sense? It's a crude work-around though. Ideally, once the notification icon dbus service appears, ownCloud would register there.

**Comment by ckamm** [comment]
@RalfJung Thanks for the clarification! I think something like this has been reported before. I'd be okay with adding a workaround. We don't want the tray to pop up late when users start the client explicitly though.

Due to old upstream bugs we currently don't query `isSystemTrayAvailable` if `QT_QPA_PLATFORMTHEME` is `appmenu-qt5`. I'll check whether that's still relevant today. 

Can you tell me the value of your `QT_QPA_PLATFORMTHEME` environment variable?

**Comment by RalfJung** [comment]
> Can you tell me the value of your QT_QPA_PLATFORMTHEME environment variable?

It is not set.

> I'd be okay with adding a workaround. We don't want the tray to pop up late when users start the client explicitly though.

What I did for now is, in the desktop file, add `X-GNOME-Autostart-Delay=10`. That file is generated by ownCloud when I set the "autostart" option in the settings (I assume), so I guess that work-around could be applied automatically? However, KDE may have similar problems, and I don't know if it has similar autostart delay.

**Comment by ckamm** [comment]
@ogoffart As far as I can tell the workarounds reading
```
    // We can't call isSystemTrayAvailable with appmenu-qt5 because it breaks the systemtray
    // (issue #4693, #4944)
```
were for an old version of appmenu-qt5 in conjunction with Qt <5.6. I propose to remove them for 2.5 and add a timer that'll attempt establishing the tray menu again after 1 minute or so.

**Comment by ckamm** [comment]
@RalfJung I've added a PR with your workaround that is targeting 2.4. Thanks for your suggestions!

**Comment by RalfJung** [comment]
Unfortunately, it seems that either this delay doesn't do anything or it doesn't suffice. I still don't have an ownCloud icon after logging in.

**Comment by RalfJung** [comment]
I now, instead, created a little shell script that does "sleep 10" before executing ownCloud. That works.

**Comment by guruz** [comment]
(We could always wait/retry a bit on Linux for the tray IMHO)

**Comment by ckamm** [comment]
@guruz I thought about just doing a hide/show after 30 secs or so to re-establish the icon in the tray if the initial attempt was too early. But with all the various buggy tray implementations out there I'm not confident that it wouldn't break something. 

On balance it might still be worthwhile. We'd also want to do it only if the tray isn't currently visible to avoid hiding the tray icon the user is currently interacting with.

**Comment by ogoffart** [comment]
Is this still a problem?

(Note there is some code to wait up to 30 seconds if the system tray is not there on XFCE, so we could also do the same on gnome)

**Comment by RalfJung** [comment]
Yes, it is (gnome-shell 3.30, owncloud-client 2.4.1).

**Comment by guruz** [comment]
> owncloud-client 2.4.1

We're at 2.5.1 :-)

**Comment by RalfJung** [comment]
Debian testing isn't, unfortunately :/

**Comment by guruz** [comment]
@RalfJung Then take the oC packages instead of Debian :-)
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client


CC @hefee

**Comment by j-4** [comment]
I have the same setup and the same problem. Just upgraded to owncloud-client 2.5.1 from debian unstable and still no notification icon showing up. It worked well with debian stretch (current stable) and owncloud-client 2.4.1.
Thanks for your effort!

**Comment by ckamm** [comment]
@j-4 Thanks for testing. Sounds like I'll add the "hide/show 30s after startup" quirk for gnome desktops.

**Comment by ckamm** [comment]
Ended up being done in #6518. The internal delay didn't work but future versions shall have an autostart delay that should help.
