### ISSUE TITLE
Show a warning when folder watcher becomes unreliable

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6119]
See #2297 and 66f0ce6616edcb6e44d235ae779170eb28c9c7c0. Suggested by @moscicki.

When a folder watcher becomes unreliable the client will revert to doing full local discovery. Possibly there should be a warning when that happens to let the user know what's happening and what steps they could take to make the problem go away.

Currently the only case is inotify file descriptor exhaustion.

**Comment by moscicki** [comment]
Many thanks for opening this!

**Comment by guruz** [comment]
Is the 100-sync-inotify.conf not working?
https://github.com/owncloud/client/issues/4107

**Comment by guruz** [comment]
2.5.0 beta1 is out :-)
https://central.owncloud.org/t/desktop-sync-client-2-5-0-beta1-released/14667
Everyone, please comment here if we can close this issue. Thank you.

**Comment by jnweiger** [comment]
### Mint Tara (aka Ubunut 18.04)

testpilotcloud version 2.5.0daily20180801 (build 9974)

sudo cat /proc/sys/fs/inotify/max_user_watches
524288

OK: setting from our sync-inotify.conf file is applied.

sudo sysctl fs.inotify.max_user_watches=280
sudo sysctl -p

populate ca 2000 files in ca 20 directories
find . | wc -l
2179
find . -type d | wc -l
24
![grafik](https://user-images.githubusercontent.com/1108546/43686661-e0e3a5da-98c9-11e8-815e-afe25ccd2b56.png)


OK: When the limit is too low, the warning appears. When the limit is set higher, now warning appears.
In this test, 270 was found too low, and 280 was found sufficient

BAD: The exact numbers are hard to explain. It should be either in the 2000 range (if files are watched) or well below 100 (if directories are watched).
