### ISSUE TITLE
Audio cuts out when owncloud-client is started

### ISSUE THREAD

**Issue by SamyCoenen** [owncloud/client#6124]
When auto-start is enabled the client should start while the rest of system also stays working including audio.

The client auto-starts and immediately all sound cuts out, it comes back a couple of seconds every minute. When auto-start is disabled and owncloud-client isn't running, the audio works fine. 

### Steps to reproduce
1. Enable auto-start 
2. Reboot

### Server configuration
Operating system:
Ubuntu 16.04
Web server: 
Apache
Database:
MariaDB 10.3.2
PHP version:
7
ownCloud version:
11.0.5
https://hub.docker.com/_/nextcloud/ 

### Client configuration
Client version:
Version: 2.3.2-1 (latest)
Operating system:
NAME="Antergos Linux"
VERSION="17.6-ISO-Rolling"

No pulseaudio logs could be found that report the error.

**Comment by ckamm** [comment]
@SamyCoenen That sounds very surprising. The client shouldn't be doing anything to your audio. Could you double check?
* Disable ownCloud autostart. Does audio work after a reboot?
* If it does, start the ownCloud client manually. Does audio still work now?

**Comment by SamyCoenen** [comment]
@ckamm The issues has dissapeared, I'm guessing a update ended up fixing it, I can't identify which one because arch had 70 updates after a couple of days. I also set my inotify limit  higher because I saw other people having issues due to it being too low.
