### ISSUE TITLE
publish in Ubuntu Software Center

### ISSUE THREAD

**Issue by jancborchardt** [owncloud/client#613]
The ownCloud desktop client is already available there, but only in the old 1.0.5 version: https://apps.ubuntu.com/cat/applications/owncloud-client/

Since Ubuntu is (one of) the most popular free software distributions, we should probably investigate to publish the client natively on the Ubuntu Software Center: http://developer.ubuntu.com/publish/

**Comment by guruz** [comment]
They're now at 1.3, still way too old.
@jnweiger @dragotin @hefee  Can we somehow get it out of there or always current?

**Comment by jancborchardt** [comment]
Please always current, if possible. Ubuntu is one of the most widely-used distros out there so we should be on it.

**Comment by jnweiger** [comment]
We'll find out how to do ubuntu -- I mean the normal way. without OBS, if needed.

**Comment by hefee** [comment]
Well ubuntu uses normal debian packages and has a time base release cycle. So the version is kept and only in some few cases an updated is allowed:

trusty: 1.5.0
utopic: 1.6.3
vivid: 1.6.4
wily: 1.8.1
http://packages.ubuntu.com/wily/owncloud-client

But what apps.u.c uses and what the way to update there things i don't know - i never got in touch with it. Please leave me a note if you get the knowlege about the process there.

**Comment by spipau** [comment]
I'll tried to install the desktop version via: 
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client
but Ubuntu does not trust the connection. So I went to the Ubuntu Software Center and I'm now using v1.5. Please simply update the version in the Store. Can't be that hard and would be the easiest way.

Thanks for your effort and great work!

**Comment by danimo** [comment]
@spipau The version in the store is not under our control

**Comment by LukasReschke** [comment]
> but Ubuntu does not trust the connection. So I went to the Ubuntu Software Center and I'm now using v1.5. Please simply update the version in the Store. Can't be that hard and would be the easiest way.

/me giggles and just lets http://www.pcworld.com/article/2845072/ubuntu-owncloud-and-a-hidden-dark-side-of-linux-software-repositories.html fall here…

**Comment by spipau** [comment]
@danimo So who controls it? Seems like it would be important to take it over or to remove it... as @LukasReschke's article points out - thanks btw! And Ubuntu should accept the Open Suse version, who's fault is that?

**Comment by LukasReschke** [comment]
@spipau Nah. We actually would rather if Ubuntu just stops packaging insecure garbage as they do right now with a ton of software.

Ubuntu is basically trying to force software developers to spend time on packaging it for them. It's basically a modern form of blackmail: "Either you do it or we will just give the users old and totally insecure stuff."

Which basically leads to the fact that nearly everything you can download in Ubuntu is insecure :rocket: :see_no_evil: 

>  So who controls it?

Ubuntu. Complain to them :wink:
