### ISSUE TITLE
[Overlays] Overlapping overlays

### ISSUE THREAD

**Issue by tobiasKaminsky** [owncloud/client#6130]
As you can see in the screenshot somehow the icon is duplicated
- one is "synced"
- one is "red" (conflict/not transferred maybe?)

![screenshot_20171027_162054](https://user-images.githubusercontent.com/5836855/32108746-ef90a86e-bb32-11e7-973b-d26d0113fd12.png)

**Comment by SamuAlfageme** [comment]
@tobiasKaminsky is that file living on a path also associated to another program with overlays (i.e. Dropbox, tortoiseSVN...)?

What do you see if you close the client? Which Linux distro are you using? might be related to OpenSUSE using both its native icons and the ones that come with the client (like in https://github.com/owncloud/client/issues/5612) cc/ @dragotin

**Comment by tobiasKaminsky** [comment]
Thank you for the hint.
Indeed it was git as I had a ".git" in my home folder and then all subfolders had the git overlay.
