### ISSUE TITLE
Identify federated/external shares in the account/selective sync view

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#6132]
This feature request is about the following:

- If a "root" folder shown in the main window is not originally from the domain the client is connected to (like foreign shares or federated shares), the folder icon should have a different color for better identification
- It would be helpful to show for federated shares, if possible for foreign shares, the used capacity

**Comment by SamuAlfageme** [comment]
Might be easy to do something similar to https://github.com/owncloud/client/commit/517623e457bdbea67cc88130842e9a55cb813232 (icon for mountpoints) - and also extend them to the wizard's selective sync dialog (see https://github.com/owncloud/client/pull/5340#issuecomment-275357875)

**Comment by TheOneRing** [comment]
Not planned
