### ISSUE TITLE
webdav client

### ISSUE THREAD

**Issue by alahwany** [owncloud/client#6134]
hello,

can anyone build for me a client for windows, mac and iphone with no logo and after installing make the map with any general word like "files" ?

because i dont' know to know hot make this and i saw many steps and i didn't understood anything so is there anyone can helping me?

**Comment by SamuAlfageme** [comment]
Hey @alahwany, thanks for your interest on the desktop client development! 

Custom Branding is part of the features [ownCloud Enterprise Edition](https://owncloud.com/enterprise-edition/) offers to its users. You can get more info on: https://doc.owncloud.org/branded_clients/branded_android_app/building_branded_android_client.html

We do not provide branding support in this repo, sorry. If you have any questions regarding the compilation process of the clients I'd suggest you to post them in https://central.owncloud.org/.
