### ISSUE TITLE
How to delete files, not existed in server database?

### ISSUE THREAD

**Issue by count0-krsk** [owncloud/client#6137]
It's not issue, just question. 
Some day ago while connecting 3rd disk to server, sdb and sdc drives are switched. And "greedy"
rsync backup hdd with deleted files become "main" cloud storage.
At night "occ file:scan" runned by Cron, and old deleted files synced to users. 
At morning I give many cry from users and restore cloud database from yesterday. But files still exists physically on both drives (backup and main). Now I can't use "occ file:scan" and users have many RED errors about case, non-existed files, etc... 
How to fix it, not searching every "old" deleted file by hands? Database size is 4GB...

**Comment by SamuAlfageme** [comment]
@count0-krsk this is the repository for the desktop sync client; it seems like the behavior you're experiencing is rather on the server side. 

Head to https://central.owncloud.org/c/server/help for help and tips on how to solve your problems with the DB from the community.
