### ISSUE TITLE
Overlay icons not working

### ISSUE THREAD

**Issue by GTT8** [owncloud/client#6139]
### Expected behaviour
The overlay Icons should show

### Actual behaviour
The overlay Icons are not showing

### Steps to reproduce
1. Install the owncloud client
2.  Not overlay icons

### Server configuration
Operating system: Debian 9.0

Web server: apache 2.4.20

Database: MySQL

PHP version: 7.1.7

ownCloud version: 10.0.3

## Client configuration
Client version: 2.3.4

Operating system: W10

OS language: Spanish

Installation path of client: `C:\Program Files (x86)\ownCloud`

### Logs

```
1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
11-05 13:34:54:396 11368 OCC::Folder::slotRunEtagJob: * Trying to check "https://cloud/remote.php/dav/files/443efad7-0bf8-4def-bd12-773130048638/" for changes via ETag check. (time since last sync: 307 s)
11-05 13:34:54:396 11368 OCC::FolderMan::slotRunOneEtagJob: Scheduling "https://cloud/remote.php/dav/files/443efad7-0bf8-4def-bd12-773130048638/" to check remote ETag
11-05 13:34:54:406 11368 OCC::AbstractNetworkJob::start: !!! OCC::RequestEtagJob created for "https://cloud." + "/" "OCC::Folder"
```
2. Web server error log: not relevant

3. Server logfile: ownCloud log (data/owncloud.log): not relevant

### ShExtView:

![image](https://user-images.githubusercontent.com/23523010/32414792-c84641e4-c22e-11e7-9a42-a93916433c6e.png)

As you can see no entries such as `OCError `or `OCOK`.

**Comment by SamuAlfageme** [comment]
Hey @GTT8 thanks for reporting! Does this still happen after restarting the explorer (known limitation of the installation process); and just out of curiosity, do you have any other ownCloud sync client installed: https://github.com/owncloud/client/issues/2388? And/Or other programs that take slots on your registry? from https://github.com/owncloud/client/wiki/Debugging-Overlay-Icons#i-dont-see-icons-what-do-i-do 

> **If you have several software products installed which use overlay icons, you might be running into the issue that Windows is using only the first 15**, here is a description how to change the order and fix this: https://www.garethjmsaunders.co.uk/2015/03/22/managing-overlay-icons-for-dropbox-and-tortoisesvn-and-tortoisegit/

(also, see related https://github.com/owncloud/client/issues/1818 and https://github.com/owncloud/client/issues/5648)

**Comment by GTT8** [comment]
HI @SamuAlfageme. Yes have restarted the explorer and modified the register, but nothing new happens.

![image](https://user-images.githubusercontent.com/23523010/32439615-cab4dde8-c2ef-11e7-915b-4bb3a4dcabc2.png)

**Comment by SamuAlfageme** [comment]
@GTT8 from what I can see in your screenshot: 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/32439680-07b64a10-c2f0-11e7-82cf-b6a4864e66c4.png"/>
</p>

It seems that the issue might be that Windows is using only the first 15 overlays; **on your setup, these spots are taken by Dropbox and oneDrive** - you could try and see the effects of placing ` 0X_OC` overlays even higher in the list. 

See also https://superuser.com/a/1166585/657628 for reference.

**Comment by GTT8** [comment]
Ok. That fixed it, I had to add 3 spaces before the `0X_OC` to be able to change the order. 

Thanks

**Comment by ckamm** [comment]
Unfortunately there's no effective way around this. Starting a "how many spaces can we add in front of the name" fight would be silly, and we're unlikely to add a tray icon prioritization ui at this stage. We might have a warning and a button to put the ownCloud overlays on top?

**Comment by GTT8** [comment]
@ckamm it wold be actually great to display a warning mesage with the error and a link with the solution in the ui.

**Comment by mbs1337** [comment]
![image](https://user-images.githubusercontent.com/3889166/42342543-b1afbfce-8096-11e8-9d9f-fc3eecf0a06b.png)

This is a working thing, if anybody struggle with: Owncloud, Synology Cloud Station, and Dropbox. Thanks to Github and: https://www.garethjmsaunders.co.uk/2015/03/22/managing-overlay-icons-for-dropbox-and-tortoisesvn-and-tortoisegit/

**Comment by ebadola** [comment]
if you want you overly icons work fine you should uninstall other apps they have overly icon too
I had Dropbox and Overlay icons didn't work,  after Uninstall Dropbox it worked fine.
