### ISSUE TITLE
[Windows] Show warning if owncloud is not in the first 15 overlays in the register

### ISSUE THREAD

**Issue by GTT8** [owncloud/client#6142]
### Expected behaviour
The overlay icons should appear always.

### Actual behaviour
Due to a windows limitation, in some cases the overlaz icons don't show

### Steps to reproduce
1. Install owncloud
2. Install other programmes whit overlay icons
3. No overlay icons on owncloud folder.

### Client configuration

Operating system: Windows

### Related issue
#6139 

### Improvement
Show warning if owncloud is not in the first 15 overlays in the register and add a link to the solution or add a button to auto solve it. Plus the client instalation should check if the owncloud is inside the 15 first overlays in the register.

**Comment by ckamm** [comment]
Thanks for making this ticket!

**Comment by hodyroff** [comment]
Great idea if we find a way to make this smooth and seamless. In many cases the user himself will not be able to resolve the issue, could we automatically resolve the issue for him?
Where would we show the warning?

**Comment by GTT8** [comment]
What about something like this:

![overlay](https://user-images.githubusercontent.com/23523010/32540948-8e22966a-c46e-11e7-835c-d546642bd8a9.png)

**Comment by michaelstingl** [comment]
We previously discussed not using our own overlay icons if there are some present from another product and the user hits the limit. We could offer the user to use the existing icon set in this case.

**Comment by ckamm** [comment]
@michaelstingl No, it's not just about icons. It's about the logic behind the icons too. Another product's logic can't be used to control the status of the owncloud icons.

**Comment by GTT8** [comment]
It’s not a full solution, but TortoiseSVN project has made a .cmd file to fix this same issue.

In a first stage, we could show an alert on the client, adapt this file and uploaded to a website with the instructions on how to use it. And in further versions we could include the solution inside the client.

https://gist.github.com/HelderMagalhaes/37ca7bbdba2b693006c46df1d8481705

**Comment by guruz** [comment]
We can use a "sticky" desktop notification (one that has to be clicked away, doesn't auto hide) that is shown once per client run as soon as the Explorer plugin requests something from the socket API.
If the Explorer plugin does not do that because it's not in the first 15, we could do it at startup.

**Comment by hodyroff** [comment]
@guruz yes, that would work. And we need to offer the solution to fix the problem = bring us in front I guess.
Browser wars transfered to explorer extensions ... Like it, because it can solve quite some user support issues.

**Comment by michaelstingl** [comment]
> "sticky" desktop notification

👍 for all platforms!

Related: https://github.com/owncloud/client/issues/5635 , https://github.com/owncloud/client/issues/4410 , https://github.com/owncloud/client/issues/4697

**Comment by michaelstingl** [comment]
deprecated with https://github.com/owncloud/client/issues/7747
