### ISSUE TITLE
Hidden folders/files are synced with 2.4.0

### ISSUE THREAD

**Issue by hodyroff** [owncloud/client#6145]
Tested 2.4.0 Alpha1 with openSUSE Leap 42.2 against internal ownCloud Server with 10.0.3

### Expected behaviour
Hidden files/folders shall not be synced, neither from the server to the client nor from the client to the server
Like with 2.3.x

### Actual behaviour
Hidden files/folders started syncing from the server to the client.
Example: privat/.mozilla/plugins

### Steps to reproduce
1. Install 2.4.0 have hidden files/folders on the server side
2. start sync
3. files/folders appear

**Comment by ckamm** [comment]
Possibly related to the speedups in exclude detection @guruz

**Comment by SamuAlfageme** [comment]
Nice catch! 

@ckamm thanks for including the csync test case 👍
