### ISSUE TITLE
server replied: Origin Time-out 

### ISSUE THREAD

**Issue by edlaika** [owncloud/client#6147]
I am having issues with my ownCloud syncing mp4's and .rar files sometimes I get an error saying can't sync mp4 and .rar files and ISO files. Sometimes the client application ignores them as well as sometimes it displays that the files are locked.
Error transferring http://xxx.xxx.xxx.xxx/remote.php/Edgar/xxxxxx/.file - server replied: Origin Time-Out.
Continue blacklisting: Error transferring http://xxx.xxx.xxx.xxx/remote.php/Edgar/xxxxxx/.file - server replied: Origin Time-out 
Some files can't be synched with ownCloud some are less than 2 GB and some are over 2GB.

This problem occurred in the client application I just choose the folder I want to sync and this error messages popped up:
https://share.teamhusky.net/more%20issues.JPG
https://share.teamhusky.net/Capture2.JPG

Server info:

Database
Server: Localhost via UNIX socket
Server type: MariaDB
Server version: 10.1.24-MariaDB-cll-lve - MariaDB Server
Protocol version: 10
User: teamhusk@localhost
Server charset: UTF-8 Unicode (utf8)

PHP:
cpsrvd 11.68.0.9
Database client version: libmysql - 5.1.73
PHP extension: mysqliDocumentation curlDocumentation mbstringDocumentation
PHP version: 5.6.30

ownCloud:
Server:
version: 10.0.3.

Log file: https://share.teamhusky.net/owncloud.log

I contacted the hosting company for support to see if its something wrong with their server but they said everything is running fine.

**Comment by guruz** [comment]
Is this a shared webspace? They are known to make problems. Please close this issue here if yes (sorry!)

To get ownCloud properly running, we recommend a vserver (or real server)

You can also try to get support in https://central.owncloud.org

**Comment by edlaika** [comment]
Thank you for the fast reply!
