### ISSUE TITLE
[Enhancement] Check file hash before starting network transfer

### ISSUE THREAD

**Issue by stefanochiappini** [owncloud/client#6153]
Following [this discussion](https://central.owncloud.org/t/first-sync-of-big-folders-when-most-of-the-files-are-the-same/10302) with @dragotin, it would be very useful to implement file hash check in the client, in order to avoid unnecessary data transfer, saving time and bandwitdh when syncing big folder with most of the files  #equal.

### Expected behaviour
1. Whenever the client is started or there's a change in the synchronized folder, for every local file, the client should check if a file with the same name and size exists on the server;
2. if it already exists, calculate the hash of the file locally and compare that to the one on the server;
3. if both are equal, the client knows that both files are the same, and it can fill the entry in the local sync journal from the values from the server, while not downloading the file.

### Actual behaviour
Equal files are unnecessarly downloaded, wasting a lot of time and bandwidth.

### Steps to reproduce
1. Install client on PC-1 a fill the synchronized "owncloud" folder with files.
2. Data on PC-1 are copied in the server.
3. Install client on PC-2 a fill the synchronized "owncloud" folder with the same files in PC-1.
4. PC-2 downloads data from the server even if the files are exactly the same

### Server configuration
Operating system: CentOS 7.2
Web server: Apache 2.4.6
Database: MariaDB 5.5.56
PHP version:  7.1
ownCloud version:  10.0.3

### Client configuration
Client version:  2.3.3 (build 8250)
Operating system: Windows 7
OS language:  Italian

### Logs
no error log

**Comment by ckamm** [comment]
This feature exists in 2.4, see #5838. If the size, mtime and content hash match, no data will be downloaded.

**Comment by guruz** [comment]
I'm re-opening this. When having a good checksum (md5 or sha1) then there is no need for mtime check. The tuple (size,checksum/hash) is good enough. Please remove this mtime check if possible :-)

@ckamm Not sure if this is too late for 2.4.0. Maybe move to 2.4.1 or 2.5.0

**Comment by ckamm** [comment]
If we don't discover significant issues during review I think this PR will be fine for 2.4

**Comment by stefanochiappini** [comment]
I agree with **guruz**, the mtime check might be the reason why it didn't work for me during the first sync (a big folder was unnecessarily downloaded), maybe moving file across different OS (Win, Linux, OSx) mtime can be touched somewhere...

**Comment by SamuAlfageme** [comment]
Finally got to check this. It's actually quite dope. Might also partially fix https://github.com/owncloud/client/issues/5388 

Closing!
