### ISSUE TITLE
Wizard font size issues

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#6156]
![screenshot_20171113_110519](https://user-images.githubusercontent.com/277525/32720006-8a02c1c0-c862-11e7-90df-83b5a1596129.png)

### Setup
owncloud-client-2.4.0~alpha1-8649.1.x86_64
plasma5-workspace-5.11.2-1.2.x86_64
openSUSE Tumbleweed

I'm on a HighDPI screen and I might have tweaked some fonts in Plasma 5:

![screenshot_20171113_110625](https://user-images.githubusercontent.com/277525/32720058-b18f1e64-c862-11e7-9830-10c566c545f4.png)

**Comment by jnweiger** [comment]
This is not only the header: https://github.com/owncloud/client/issues/6158

**Comment by ckamm** [comment]
Adding @jnweiger's image from #6158 here:
![](https://user-images.githubusercontent.com/1108546/32732961-5d6c2378-c88e-11e7-9745-cf26d1db0211.png)

**Comment by ogoffart** [comment]
Can be reproduced on linux on a normal screen by setting an env variable, for example:
`QT_FONT_DPI=180`

**Comment by ogoffart** [comment]
I think the problem is that QWizard has some sizes hardcoded, and it cannot be resized dynamically

**Comment by ogoffart** [comment]
It turns out that we make the wizard a fixed size by setting a banner to it.
The size of the banner is hardcoded in Theme::wizardHeaderBanner.  Maybe we should scale it by the DPI

**Comment by ogoffart** [comment]
Suggested fix: https://github.com/owncloud/client/pull/6164

**Comment by jnweiger** [comment]
I believe the fix from @ogoffart should help in Vincent's case, -- but probably not in my case.

**Comment by ogoffart** [comment]
@jnweiger  yes, it fixes both,  the width of the wizard is fixed and the same as the width of the header banner

**Comment by SamuAlfageme** [comment]
@PVince81 care to give latest nightly: https://software.opensuse.org//download.html?project=isv:ownCloud:community:nightly&package=owncloud-client a try?

**Comment by SamuAlfageme** [comment]
@ogoffart I think the "Add Folder Sync Connection" button also has a prefixed width; the label is not being wrapped as for 2.4.0nightly-20171121:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/33167597-4f66512e-d03e-11e7-9adf-5dafe3362a61.png"/>
</p>

**Comment by ogoffart** [comment]
@SamuAlfageme That's really strange.  I cannot reproduce the problem with the nightly, how do you reproduce it?
Also noprmaly the size of this button is computed with the size of the text, i don't see how they can get out of sync.

**Comment by SamuAlfageme** [comment]
@ogoffart might be a Qt upstream bug: 

- Win10 
- resolution 1920x1015 
- scale 100% 
- **Text size for icons: 7pt** (it seems to determine button labels as well)

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/33176483-7df4f560-d05f-11e7-9e3b-da183c8ef001.png"/>
</p>

I remember an issue where extremely small text sizes also caused normally-hidden labels to be displayed: e.g. this is with a 6pt text size

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/33176659-1b7e8eb8-d060-11e7-8633-6599b21815c1.png"/>
</p>

**Comment by ogoffart** [comment]
@SamuAlfageme    ah, I can reproduce, thank you.
However this is a different issue entierly.

**Comment by guruz** [comment]
@PVince81 @jnweiger please test with 2.4.0 rc1
https://software.opensuse.org/download.html?project=isv%3AownCloud%3Acommunity%3Atesting&amp;package=owncloud-client
