### ISSUE TITLE
Forbidden web page when using invalid URL in setup dialog

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#6157]
### Steps
1. Setup Apache2 with ownCloud under http://localhost/owncloud
1. Setup desktop client and enter "http://localhost" (note that it's the wrong path)
1. Click "next"

### Expected
User-friendly error message

### Actual
Popup appears with 403 error page inside. I can close it to go back.
![screenshot_20171113_110915](https://user-images.githubusercontent.com/277525/32720199-167e6726-c863-11e7-83ff-1cd37d4ffa48.png)

### Versions
openSUSE Tumbleweed
plasma5-workspace-5.11.2-1.2.x86_64
owncloud-client-2.4.0~alpha1-8649.1.x86_64

**Comment by ckamm** [comment]
This behavior should exist since 2.3.0 with 679ac0d26a6607a1d98024d829c0f71cc715d480: If the server replies with text the client displays that to the user. 

It would be nice
1) If it were clearer to the user that this is what's happening
2) The "Ok" button that's supposed to be there were visible

**Comment by PVince81** [comment]
Maybe the client should first ping status.php of the given URL to decide whether it's even worth opening a web view ?

**Comment by ckamm** [comment]
It looks like the intention was to show the 400 replies for missing client certs or the ip needing to be added as a "trusted domain" for the instance. We could filter out 404 which would cover most arbitrary urls. @guruz ?

**Comment by guruz** [comment]
@PVince81 It's a Qt message box, not a web view. it is just a dialog that renders some HTML using Qt's Label HTML implementation. :-)

> The "Ok" button that's supposed to be there were visible

Will that be visible now?

> We could filter out 404 which would cover most arbitrary urls

What do you want to do for 404? @PVince81 got a 403

**Comment by ckamm** [comment]
@guruz I have no idea why the "ok" button isn't visible for @PVince81, it was always there in my tests. Maybe specific html can hide it somehow?

404/403: Right. Do you think my patch 
aa9a386  (not yet merged) is sufficient here?

**Comment by guruz** [comment]
.oO(Is @PVince81 getting some shibboleth web view?)

Yes, sufficient. let's re-evaluate this for 2.5 if there is any issues

**Comment by ckamm** [comment]
@guruz ok, merged simple "info" patch to 2.4

**Comment by PVince81** [comment]
Maybe I don't see the OK button of highdpi issues ? See my other ticket https://github.com/owncloud/client/issues/6156

**Comment by TheOneRing** [comment]
Fixed in https://github.com/owncloud/client/commit/41c10b8f5b600446aaa601e7a9345a7f6c2d389a
