### ISSUE TITLE
window layout of new-connection dialog chops off texts

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6158]
owncloud-client-2.4.0~alpha1 on Ubunutu 16.04 cinamon, with larger fonts, texts are truncated or overlapping.
Font sizes up to 14pt looks fine for me, font size 15pt starts to show issues. More issues show at larger font sizes
![client-20pt-font](https://user-images.githubusercontent.com/1108546/32732961-5d6c2378-c88e-11e7-9745-cf26d1db0211.png)

Window resizing currently allows to change the height only. Please also allow to change width, that might be an easy "fix" for the truncated lines.

**Comment by ckamm** [comment]
Closing in favor of #6156
