### ISSUE TITLE
owncloudcmd hangs when http is a 302 redirect to https

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6159]
owncloud-client-2.4.0~alpha1 on ubuntu-16.04 running against a 10.0.3 server at demo.owncloud.com .

`mkdir /tmp/xx && owncloudcmd /tmp/xx http://demo.owncloud.com`
 connects fine and starts to download, prints many messages, but then hangs. The Photos folder e.g. still looks like this after waiting several minutes:
```
$ ls -la /tmp/xx/Photos/
insgesamt 0
drwxr-xr-x 2 testy testy 100 Nov 13 18:35 .
drwxr-xr-x 4 testy testy 135 Nov 13 18:35 ..
-rw-r--r-- 1 testy testy   0 Nov 13 18:35 .Paris.jpg.~19b9880b
-rw-r--r-- 1 testy testy   0 Nov 13 18:35 .San Francisco.jpg.~d994da7
-rw-r--r-- 1 testy testy   0 Nov 13 18:35 .Squirrel.jpg.~57f5f2f1
```

When using `https://` instead of `http://` the download succeeds within seconds.
With the owncloud GUI client it does not matter which protocol is specified with the server. It succeeds within seconds.

owncloudcmd should behave just the same as owncloud and succeed to download.

Note:
```
$ curl -i http://demo.owncloud.com/status.php
HTTP/1.1 302 Found
Location: https://demo.owncloud.com:443/status.php
```

**Comment by jnweiger** [comment]
console log:
https://gist.github.com/jnweiger/3c83c91fdf226a8b79da441d5faaa523

**Comment by SamuAlfageme** [comment]
Hm, I remember this one but never got back to it (ref. https://chat.owncloud.com/channel/desktop?msg=W9uECBDo9o8erBtij):

```
jturcotte 3:08 PM  Looks like the redirection causes the file propagation not to be properly caught.
samuel 3:15 PM  `owncloudcmd . demo.owncloud.com` vs. `owncloudcmd . https://demo.owncloud.com`
samuel 3:16 PM  maybe somethin' is bothering QUrl with when composing `"https://demo.owncloud.com:443/remote.php/webdav/Photos/Squirrel.jpg"`
samuel 3:16 PM  notice the port
samuel 3:17 PM  (that's the output when calling the client without `https`)
jturcotte 3:18 PM  Humm looks OK, if you try that exact URL in the browser with your credentials it should also work.
jturcotte 3:18 PM  And QUrl should be able to handle a port number without issue.
```

**Comment by ckamm** [comment]
The `GETFileJob` isn't redirection-safe because all the QNetworkReply connections aren't transfered to the redirected request.

**Comment by ckamm** [comment]
PR https://github.com/owncloud/client/pull/6162

**Comment by SamuAlfageme** [comment]
👍
