### ISSUE TITLE
Can not add account if wizard is closed before completion on first run.

### ISSUE THREAD

**Issue by k9t9** [owncloud/client#6170]
### Expected behaviour
Upon launching the client, if no account was configured, the setup wizard should appear.
Alternatively - some other location to add an account should be presented in the UI.

### Actual behaviour
On first run of the client, the wizard was closed without completing the account configuration.
Upon relaunch of the client , there is no apparent way to add a new account in the UI .
Only the "Activity" , "General" and "Network" tabs are present .
Unless I missed some obvious action or button ,
The wizard reappears only after reboot or re-install .

### Steps to reproduce
1. Install the Client , 
2. Launch Client { wizard } and close without ending the configuration process.
3. Relaunch Client.

### Steps to fix
1. Reboot.
2. Relaunch Client.

### Server configuration

N/A

### Client configuration
Client version: 2.3.2 (Build 1 )

Operating system:  win7sp3

OS language: EN

Installation path of client: C:\Program Files\Nextcloud

### Screenshots
![2017-11-19_192430](https://user-images.githubusercontent.com/23067654/32990729-92a61afa-cd69-11e7-9ebe-d4d3c328fdda.png)
![2017-11-19_192443](https://user-images.githubusercontent.com/23067654/32990730-930aaa60-cd69-11e7-83b9-d60a256ba8d0.png)
![2017-11-19_192416](https://user-images.githubusercontent.com/23067654/32990731-93635610-cd69-11e7-9a69-18a7b6a0270b.png)

**Comment by michaelstingl** [comment]
Checked the tray icon?

**Comment by SamuAlfageme** [comment]
Hey @k9t9 thanks for your report! 

I just tried out with version 2.3.2 Win7**SP1** and I'm getting the wizard back every time I relaunch the client without accounts configured. Odd that you're not getting it. 

Additionally, on Windows, you can trigger a new wizard with a left click on the activity menu icon or right click to display all the options and select "Add new account". 

The new tab button on the settings window has been already requested in https://github.com/owncloud/client/issues/5307, don't forget to 👍 there to show your support for that change. 

I'm closing this one down in favor of the mentioned techniques and issue. If you're able to find any more steps for reproduction; feel free to include 'em in this issue.
