### ISSUE TITLE
2.3.4 yields 'Not Acceptable' errors with new files, but problem does not occur with version 2.2.4

### ISSUE THREAD

**Issue by isaacgerg** [owncloud/client#6171]
### Expected behaviour
New files should upload successfully 

### Actual behaviour
I get 2 errors now starting with version 2.3.4.8624, one file continually gives me Not Acceptable errors in the GUI and the other files will not upload and the log returns the error. 

```
Stack trace:
#0 /public_html/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): OC\DB\Connection->connect()
#1 /public_html/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion()
#2 /public_html/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform()
#3 /public_html/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(623): Doctrine\DBAL\Connection->getDatabasePlatform()
#4 /public_html/owncloud/lib/private/DB/Connection.php(146): Doctrine\DBAL\Connection->setTransactionIsolation(2)
#5 /public_html/owncloud/lib/compos in /public_html/owncloud/lib/private/DB/Connection.php on line 63
[19-Nov-2017 16:12:23 UTC] PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away' in /public_html/owncloud/lib/composer/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOStatement.php:91
```

and

`Desktop\MyDrive,Error downloading http://owncloud.gggggg.com/remote.php/webdav/2005/dump/bookmarks.bak - server replied: Not Acceptable`

### Steps to reproduce
1.  Have successful sync with version 2.2.4.6408
2. Reinstall OS and install version 2.3.4.8624
3. Attempt to sync with server. Also, attempt to add new files (some files work, others do not.  Larger files >10MB do not seem to work reliably. 

### Server configuration
Operating system: linux

Web server: hostmonster.com

Database: mysql

PHP version: 5.6

ownCloud version: 

installed | true
-- | --
maintenance | false
needsDbUpgrade | false
version | 10.0.3.3
versionstring | 10.0.3
edition | Community
productname | ownCloud

Storage backend (external storage): none

### Client configuration
Client version: 2.3.4.8624

Operating system: Windows 7 home

OS language: unknown

**Comment by SamuAlfageme** [comment]
Hey @isaacgerg, it's highly unlikely that the issue is related to your client version; by what I can read in your server logs: 

```
PHP Fatal error:  Uncaught exception 'PDOException' with message 'SQLSTATE[HY000]: General error: 2006 MySQL server has gone away'
```

... and considering you're using a shared hoster (i.e. hostmonster.com) there's more chances that the problem has to do with the DB infrastructure your hoster provides.  

Something that changed sensibly from version 2.2.4 to 2.3.* is the use of the new chunking algorithm (https://github.com/owncloud/client/issues/4019) if the server reports it - can you give a try switching the  [`OWNCLOUD_CHUNKING_NG`](https://github.com/owncloud/client/blob/92027e869230d82de1bbbd0d486ebf14bfc471f7/src/libsync/owncloudpropagator.cpp#L274-L280) env.var and restart the client? (i.e. launch the client with this var. set to 0)

**Comment by isaacgerg** [comment]
@SamuAlfageme I uninstalled  2.2.4 and then installed 2.3.4.  I verified that the file did not upload.  Then, I quit the client, set OWNCLOUD_CHUNKING_NG to 0, and then restarted the client.  The file uploaded successfully.  Thank you for the help.

Do you have an idea what I should adjust on my server so that I don't have to put in this hack? 

I'll let you close this issue unless you have any more tests for me to run.

**Comment by SamuAlfageme** [comment]
@isaacgerg cool, I'm glad it works out ☺️ 

@DeepDiver1975 I know shared hosters are not supported; but, for any server with flaky DB-connection, is there any way chunking-ng could be linked to these issues and potentially disabled in core (once the server switches the capability, client will use the old chunking in next restart) upon these kind of failures?

**Comment by guruz** [comment]
@SamuAlfageme I don't think we can really do so much for shared hoster setups that make the core behave in bizantine ways.
