### ISSUE TITLE
Too big folder list wraps round and is not scrollable

### ISSUE THREAD

**Issue by tomneedham** [owncloud/client#6174]
![screen shot 2017-11-20 at 15 46 10](https://user-images.githubusercontent.com/660805/33027163-49c8d128-ce0a-11e7-95bd-87379312f908.png)

### Expected behaviour
Should be able to see all of the folders whcih are not synced

### Actual behaviour
The list is wrapped around and not scrollable

### Steps to reproduce
1. Made lots of changes (moves) on the server
2. Sync client ran

### Server configuration
Operating system:

Web server: 
Apache

Database:
MySQL

PHP version:
5.6

ownCloud version:
9.0.2.2

### Client configuration
Client version:
2.3.2

Operating system:
OSX

OS language:
English

**Comment by SamuAlfageme** [comment]
@tomneedham was reported in https://github.com/owncloud/client/issues/5492 and fixed for 2.4 (https://github.com/owncloud/client/issues/5492)

**Comment by guruz** [comment]
@tomneedham Please also double check by using 2.4.0 beta1, thx
