### ISSUE TITLE
Display the private shares as a list

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6176]
Follow up of https://github.com/owncloud/client/pull/4310#issuecomment-345999910 

Maybe we could consider delimiting each entry (share) using a list with alternate colors (like the one in "Sync Protocol/Not Synced") to get rid of the rectangle that encloses the checkboxes now. I remember a mockup from some time ago:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/33070389-222fa6ec-ceb8-11e7-9bb4-52cb343fc21d.png"/>
</p>

Additionally we could think of a way (icons, multi-line...) to avoid widening the dialog on such long names e.g. remote shares (currently displays the full federated share id + the string "`(remote)`") 

## Screenshot for reference: 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/33069989-af6f5c34-ceb6-11e7-93b5-29359822499e.png"/>
</p>

**Comment by ckamm** [comment]
The alternating background colors are covered by #4310. 

The long user labels making the dialog very wide are harder to deal with: Just enabling word wrap on the label doesn't look particularly nice.

**Comment by guruz** [comment]
moved to 2.6

**Comment by ogoffart** [comment]
So what shall be done here?

**Comment by ckamm** [comment]
The bug is that the dialog becomes very wide when the share recipient name is long. That happens particularly for federated shares.

**Comment by TheOneRing** [comment]
The sharing dialog is considered deprecated
