### ISSUE TITLE
Asterisk after folder name in sync-exclude.lst does not match subfolders

### ISSUE THREAD

**Issue by c-ney** [owncloud/client#6178]
### Expected behaviour
I have a directory hierarchy in my sync root directory and want to exclude all files with a certain file extension `.ext` in one directory `folder` and all its subdirectories from syncing. According to the documentation at

[1] https://doc.owncloud.org/desktop/latest/navigating.html#using-the-ignored-files-editor
[2] https://doc.owncloud.org/desktop/latest/architecture.html#ignored-files-label
[3] http://pubs.opengroup.org/onlinepubs/009695399/utilities/xcu_chap02.html#tag_02_13_01

this should be achievable by putting `folder/*.ext` in the user's sync-exclude.lst.

From [2]:

> To match filenames against the exclude patterns, the unix standard C library function fnmatch is used. This process checks the filename against the specified pattern using standard shell wildcard pattern matching. For more information, please refer to The opengroup website.
>
> The path that is checked is the relative path under the sync root directory.

From [3]:

> \* An asterisk is a pattern that shall match multiple characters, as described in Patterns Matching Multiple Characters.

> 1. The asterisk ( '*' ) is a pattern that shall match any string, including the null string.
> 2. ...
> 3. The concatenation of one or more patterns matching a single character with one or more asterisks is a valid pattern. In such patterns, each asterisk shall match a string of zero or more characters, matching the greatest possible number of characters that still allows the remainder of the pattern to match the string.

### Actual behaviour
Only files located at the top level of `folder`, e.g. `folder/file.ext`, are correctly excluded from syncing. Files in deeper levels, e.g. `folder/subfolder/file.ext`, are still synced.

### Steps to reproduce
1. Create `folder/subfolder` in sync root directory
2. Add `folder/*.ext` to `~/.local/share/data/ownCloud/sync-exclude.lst`
3. Create file `folder/subfolder/test.ext`

### Server configuration

Operating system: don't know

Web server: don't know

Database: don't know

PHP version: don't know

ownCloud version: sciebo 9.1.6 (stable)

Storage backend (external storage): don't know

### Client configuration
Client version: 2.3.3 Built from Git revision 57bc79 on Oct 21 2017, 12:00:00 using Qt 5.9.2, OpenSSL 1.0.2m-fips 2 Nov 2017

Operating system: openSUSE Tumbleweed

OS language: en

Qt version used by client package (Linux only, see also Settings dialog): Qt 5.9.2

Client package (From ownCloud or distro) (Linux only): owncloud-client 2.3.3-3.1

Installation path of client: /usr/bin

### Logs

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

```
11-21 17:28:36:246 0xb05970 csync_exclude_load: Adding entry: documents/*.aux
...
11-21 17:29:02:320 19291 OCC::FolderWatcher::changeDetected: detected changes in paths: QSet("/data/sciebo/documents/blah/blah/test6.aux")
...
11-21 17:29:06:665 0xef33a8 csync_walker: file: /data/sciebo/documents/blah/blah/test6.aux [inode=39192132 size=0]
11-21 17:29:06:665 0xef33a8 _csync_detect_update: Checking for rename based on inode # 39192132
11-21 17:29:06:665 0xef33a8 _csync_detect_update: file: documents/blah/blah/test6.aux, instruction: INSTRUCTION_NEW <<=
...
11-21 17:29:08:894 0xb05970 _csync_merge_algorithm_visitor: INSTRUCTION_NEW                client file: documents/blah/blah/test6.aux
```

2. Web server error log: no access

3. Server logfile: ownCloud log (data/owncloud.log): no access

**Comment by ckamm** [comment]
@c-ney Unfortunately there currently is no way of specifying the ignore pattern you would like to have.

From a matching rules point of view [3] says further down:
> The slash character in a pathname shall be explicitly matched by using one or more slashes in the pattern; it shall neither be matched by the asterisk or question-mark special characters nor by a bracket expression.

So the `*` doesn't expland to a `/` -- and we pass `FNM_PATHNAME` to `fnmatch`, so that applies to the owncloud client.

This is another case where being able to escape to a full-regex ignore pattern syntax would be helpful. (We actually convert some patterns to regex for performance reasons anyway.) I'll make a ticket about that.

**Comment by c-ney** [comment]
My mistake! I somehow stopped reading after section 2.13.2.

Thanks for working on it!
