### ISSUE TITLE
testpilotcloud-client-2.4.0~beta1 kills owncloud-client-2.3.4

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6180]
Having both isv:/ownCloud:/desktop and isv:/ownCloud:/testpilot:/testing repos registered, causes mismatch of libraries:
seen during apt-get install testpilotcloud-client:
```
Get:26 http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/testing/Ubuntu_17.04  ocqt562-libqt5dbus5 5.6.2-14+13.1 [221 kB]
Get:27 http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/testing/Ubuntu_17.04  ocqt562-libqt5network5 5.6.2-14+13.1 [473 kB]
Get:28 http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/testing/Ubuntu_17.04  ocqt562-libqt5gui5 5.6.2-14+13.1 [2128 kB]
Get:55 http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/testing/Ubuntu_17.04  ocqt562-libqt5widgets5 5.6.2-14+13.1 [2222 kB]
Get:88 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_17.04  ocqt562-libqt5opengl5 5.6.2-1+22.1 [159 kB]                          
Get:89 http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/testing/Ubuntu_17.04  ocqt562-libqt5printsupport5 5.6.2-14+13.1 [206 kB]        
Get:90 http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/testing/Ubuntu_17.04  ocqt562-libqt5sql5 5.6.2-14+13.1 [141 kB]                 
Get:91 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_17.04  ocqt562-libqt5webkit5 5.6.2-1 [8839 kB]                              
Get:92 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_17.04  ocqt562-libqt5keychain1 0.7.0-1+4.4 [42.6 kB]                        
Get:93 http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/testing/Ubuntu_17.04  libtestpilotcloudsync0 2.4.0~beta1-8710 [438 kB]          
Get:94 http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/testing/Ubuntu_17.04  ocqt562-libqt5sql5-sqlite 5.6.2-14+13.1 [69.1 kB]         
Get:95 http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/testing/Ubuntu_17.04  ocqt562-libqt5xml5 5.6.2-14+13.1 [126 kB]                 
Get:96 http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/testing/Ubuntu_17.04  testpilotcloud-client-l10n 2.4.0~beta1-8710 [344 kB]      
Get:97 http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/testing/Ubuntu_17.04  testpilotcloud-client 2.4.0~beta1-8710 [846 kB]          
```

A Dockerfile to reproduce the issue looks like this:
```
FROM ubuntu:17.04
RUN apt-get update
RUN apt-get install -y wget
RUN wget -nv https://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_17.04/Release.key -O - | apt-key add -
RUN echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_17.04/ /' > /etc/apt/sources.list.d/owncloud-client.list
RUN echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot:/testing/Ubuntu_17.04/ /' > /etc/apt/sources.list.d/testpilotcloud-client.list
RUN apt-get update

RUN apt-get install -y testpilotcloud-client
RUN testpilotcloudcmd --version
#### EXPECT: testpilotcloud version 2.4.0beta1 (build 8710)
#### SEEN:   testpilotcloud version 2.4.0beta1 (build 8710)

RUN testpilotcloud || true
#### EXPECT: QXcbConnection: Could not connect to display    
#### SEEN:   testpilotcloud: relocation error: /opt/ownCloud/qt-5.6.2/lib/x86_64-linux-gnu/libQt5OpenGL.so.5: symbol _ZTV26QOpenGLSharedResourceGuard, version Qt_5_PRIVATE_API not defined in file libQt5Gui.so.5 with link time reference

RUN apt-get install -y owncloud-client
RUN owncloudcmd --version
#### EXPECT: ownCloud version 2.3.4
#### SEEN:   ownCloud version 2.3.4

RUN owncloud
#### EXPECT: QXcbConnection: Could not connect to display  
#### SEEN:   owncloud: relocation error: /opt/ownCloud/qt-5.6.2/lib/x86_64-linux-gnu/libQt5OpenGL.so.5: symbol _ZTV26QOpenGLSharedResourceGuard, version Qt_5_PRIVATE_API not defined in file libQt5Gui.so.5 with link time reference
```

**Comment by jnweiger** [comment]
@dschmidt seperating the installation paths and package names for 2.3x libs and 2.4x libs should help, right?
@SamuAlfageme regression test for this please.
@guruz @michaelstingl  2.4.0 release blocker?

**Comment by jnweiger** [comment]
Both, OC_QT_VERSION and PACKAGE_NAME_PREFIX are rolled into the client package meta data trhough the templating engine.
gitea.int.owncloud.com/ownbrander/scripting/client/linux/genbranding/setup_client_obs.sh now allows
control of the template variables from jenkins:

test -z "${PACKAGE_NAME_PREFIX}" && PACKAGE_NAME_PREFIX=ocqt562+240
test -z "${OC_QT_VERSION}" && OC_QT_VERSION=5.6.2+2.4.0

-PACKAGE_NAME_PREFIX="ocqt562"
-OC_QT_VERSION="5.6.2"
+PACKAGE_NAME_PREFIX="${PACKAGE_NAME_PREFIX}"
+OC_QT_VERSION="${OC_QT_VERSION}"

**Comment by jnweiger** [comment]
Deployed into https://build.opensuse.org/project/monitor/isv:ownCloud:Qt562:2.4.0
and into internal build service. Nightlies to be checked, then let's roll a beta2.

**Comment by jnweiger** [comment]
Nightlies look good now.
Pushed also into testing. The current beta1 is rebuilt from v2.4.0-beta1 tag and reflects these changes.
https://software.opensuse.org//download.html?project=isv%3AownCloud:community:testing&package=owncloud-client

TODO: testpilotcloud-client beta1

**Comment by jnweiger** [comment]
@pmaier1 @SamuAlfageme can you please re-test the beta1 from the above Linux repos?
If you approve, we can close this as fixed!

**Comment by SamuAlfageme** [comment]
@jnweiger all the test steps I've conducted on xUbuntu distros are looking good now (after purging old clients), I think I have a pre-2.3.3 (templates) version somewhere, will try from there without purging. 

> regression test for this please

Yas that's it, will include in https://github.com/owncloud/platform/issues/81's "update" scenarios.

**Comment by jnweiger** [comment]
There is no good way to switch back and forth between nightlies and betas. only one of :testing or :daily repo must be registered.

**Comment by guruz** [comment]
.oO(maybe nightly could be a theme like testpilotcloud.. but then it won't use the same config directory..)

**Comment by guruz** [comment]
can this be closed?

**Comment by SamuAlfageme** [comment]
@guruz will check with RC1 and 2.3.4 ASAP and report back once again. Last time I did (https://github.com/owncloud/client/issues/6180#issuecomment-347170391) OBS was still a bit unstable to do so.

**Comment by SamuAlfageme** [comment]
Finally got to see everything living together in peace:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/34107849-0ca2b868-e3fe-11e7-8fdc-16eacfc86431.png"/>
</p>

`+<version>` infix makes libraries no longer conflict with each other. Closing here as fixed! 🎉
