### ISSUE TITLE
Allow regex exclude patterns

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6181]
We have recently started using regular expressions over `fnmatch` calls for exclude pattern matching after observing significant performance benefits. See #6063 

It would sometimes be useful to users to express exclude patterns in regular expressions directly: it allows a wider range of behaviors, and sometimes they can use one pattern where they'd need multiple before.

This is a follow up to #6178 and #5017.

**Comment by SamuAlfageme** [comment]
@ckamm there's a bunch of issues about the "Exclude files" feature with common traits, should I create a meta-issue to track 'em down and discuss there?

**Comment by ckamm** [comment]
@SamuAlfageme Wouldn't hurt, thanks. I have a good idea of what needs doing and have already started though.

**Comment by ckamm** [comment]
After the significant exclude pattern rework it's now clear that allowing general regex patterns to match against paths would have significant performance issues. (currently we get by with only matching the bname in the first pass, which is way faster than matching against the full path) Let's not do this then.
