### ISSUE TITLE
Beta1: Manpage missing

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#6183]
The doc files for the manpages for owncloud and owncloudcmd were removed from the source tree, thus building man pages is broken.

Hint: Try `make doc-man` in the source build tree. Breaks because owncloud.1.rst and owncloudcmd.1.rst were removed, see https://github.com/owncloud/documentation/issues/3240 for details and the commit that removed it.

**Comment by SamuAlfageme** [comment]
manpages were removed as per https://github.com/owncloud/client/issues/2153#issuecomment-286037172 in 2.3.2 - but maybe we should keep actively maintaining those if distros since it seems @dragotin is not the only one missing them (ref. https://github.com/owncloud/client/issues/6011#issuecomment-328476462) 

cc/ @jnweiger @hodyroff

**Comment by jnweiger** [comment]
All releases have separate packaging templates. We never want changes to be retroactove.

Currently there is no config for 2.4.1 -- we support 2.4.0 from branch 2.4 and 2.5.0 from branch master.

**Comment by guruz** [comment]
PR was merged.
@jnweiger need to make sure that branded packages don't ship with owncloud* man pages.

**Comment by guruz** [comment]
Source file seems to have it again
```
drwxr-xr-x  0 jenkins jenkins       0 Dec  4 16:48 owncloudclient-2.4.0-rc1/man/
-rw-r--r--  0 jenkins jenkins     871 Dec  4 16:48 owncloudclient-2.4.0-rc1/man/owncloud.1.rst
-rw-r--r--  0 jenkins jenkins     520 Dec  4 16:48 owncloudclient-2.4.0-rc1/man/CMakeLists.txt
-rw-r--r--  0 jenkins jenkins    2664 Dec  4 16:48 owncloudclient-2.4.0-rc1/man/owncloudcmd.1.rst
-rw-r--r--  0 jenkins jenkins       1 Dec  4 16:48 owncloudclient-2.4.0-rc1/man/index.rst
```

**Comment by guruz** [comment]
https://owncloud.org/changelog/desktop/

**Comment by SamuAlfageme** [comment]
They continue non-linked (i.e. not present in the `manpath`, `/usr/share/man/man1`); so `man owncloud` will output "No manual entry for owncloud" 

@jnweiger where the post-install scripts adapted to do https://github.com/owncloud/client/issues/2153#issuecomment-269344867?

**Comment by jnweiger** [comment]
So it looks like we no longer want to 'prevent packaging of man pages' https://github.com/owncloud/client/issues/2153#issuecomment-288996228 but want to have them back. 

What contents do we want to put in the man pages? We currently have there only a subset of what owncloud --help produces.

**Comment by jnweiger** [comment]
sphinx-build fails processing the doc/conffile.rst when trying to generate man pages:
```
writing... owncloud.1 { } ../doc/conffile.rst:: WARNING: "table cell spanning" not supported
../doc/conffile.rst:: WARNING: "table cell spanning" not supported
../doc/conffile.rst:: WARNING: "table cell spanning" not supported
../doc/conffile.rst:: WARNING: "table row spanning" not supported
../doc/conffile.rst:: WARNING: "table row spanning" not supported
owncloudcmd.1 { } 
```
Does that work better when generating html or pdf?

**Comment by guruz** [comment]
I see a checked-in man page, why Spinhx?
https://github.com/owncloud/client/blob/master/man/owncloud.1.rst

**Comment by jnweiger** [comment]
nroff cannot read rst. The process to convert from rst to nroff is
```
cat <<EOF>conf.py
master_doc = 'index'    # dummy

# General information about the project.
project = u'ownCloud Client'
copyright = u'2017, ownCloud GmbH'
author = u'ownCloud GmbH'

# The short X.Y version.
version = u'2.4.0'
# The full version, including alpha/beta/rc tags.
release = u'2.4.0-rc1'

man_pages = [
    ('owncloud.1', 'owncloud', u'ownCloud Client Documentation', [author], 1),
    ('owncloudcmd.1', 'owncloudcmd', u'ownCloud Command Line Client Documentation', [author], 1)
]
EOF

mkdir -p build
sphinx-build -b man . build

**Comment by michaelstingl** [comment]
- [x] man pages work for community packages (see https://github.com/owncloud/client/pull/6193#pullrequestreview-80718780)
- [x] unbranded man packed don't show up in branded builds (Sphinx ignores `/man` dir)

Related PR: https://github.com/owncloud/client/pull/6193

**Comment by jnweiger** [comment]
@michaelstingl thanks. 
No man pages in our packages. --> Nothing to do :+1:

**Comment by dragotin** [comment]
Thanks for supporting this even though you are not benefiting directly from this. Very appreciated from downstream :-)
