### ISSUE TITLE
adding command line options to the setup.exe

### ISSUE THREAD

**Issue by finius** [owncloud/client#6187]
I would suggest to add a support of command line installation options to the Windows Nextcloud client to make administrators able to predefine some basic things from config file (like server URL, authentication/username, sync options, etc) to enhance user experience as no GPO package is available to autoconfig nextcloud on an enterprise level.

**Comment by michaelstingl** [comment]
@finius ownCloud offers self-service portal that generates customized clients with corporate design, fixed URL, etc for Win, Mac and all flavours of Linux.

MSI installer is planned too. Here you can find an early draft of the docs:
https://github.com/owncloud/client/blob/msi-doc/doc/installing.rst

Related: https://github.com/owncloud/client/issues/567, https://github.com/owncloud/client/issues/1419, https://github.com/owncloud/client/issues/860
