### ISSUE TITLE
Beta / testing repo installs stable version on Fedora 26

### ISSUE THREAD

**Issue by DominicMe** [owncloud/client#6190]
Following instruction for latest beta below:

```
dnf config-manager --add-repo https://download.opensuse.org/repositories/isv:ownCloud:community:testing/Fedora_26/isv:ownCloud:community:testing.repo
dnf install owncloud-client
```

Last command still installs version 2.3.3 instead of 2.4

**Comment by michaelstingl** [comment]
@jnweiger still confusion with the repos. Could you check?

**Comment by jnweiger** [comment]
you also have the normal isv:ownCloud:desktop repo installed and got the client from there.

**Comment by DominicMe** [comment]
@jnweiger I don't know what you are trying to say exactly..?

**Comment by jnweiger** [comment]
Im trying not to say that I accidently wiped the packages from the testing repo last night. Sorry for this.
I had hoped it would recover fast, but it did not. I am pushing a rebuild from the same github tag  v2.4.0-beta1 now.

**Comment by jnweiger** [comment]
Fixed: 
```
dnf config-manager --add-repo https://download.opensuse.org/repositories/isv:ownCloud:community:testing/Fedora_26/isv:ownCloud:community:testing.repo
dnf install owncloud-client
```

... just installed the correct package for me:

owncloud-client                  x86_64       2.4.0-0.8742.1.beta1        isv_ownCloud_community_testing

you should also get a new set of ocqt562 packages:

ocqt562+240-libQt5Concurrent5.x86_64 5.6.2-3.1             
  ocqt562+240-libQt5Core5.x86_64 5.6.2-3.1                      ocqt562+240-libQt5DBus5.x86_64 5.6.2-3.1                   
  ocqt562+240-libQt5Gui5.x86_64 5.6.2-3.1                       ocqt562+240-libQt5Network5.x86_64 5.6.2-3.1                
  ocqt562+240-libQt5PrintSupport5.x86_64 5.6.2-3.1              ocqt562+240-libQt5Sql5.x86_64 5.6.2-3.1                    
  ocqt562+240-libQt5Widgets5.x86_64 5.6.2-3.1                   ocqt562+240-libQt5Xml5.x86_64 5.6.2-3.1                    
  ocqt562+240-libqt5-qtwebkit.x86_64 5.6.2-2.2                  ocqt562+240-qt5keychain1.x86_64 0.7.0-1.3

**Comment by DominicMe** [comment]
@jnweiger I had to remove and install from  scratch but it does work now.

**Comment by jnweiger** [comment]
closing here. The beta is fine again.
