### ISSUE TITLE
Adapt "public link" permissions to oC server 10.0.4 UI

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#6192]
UI for "public link" permissions has been improved with oC server 10.0.4:
https://github.com/owncloud/core/pull/29376

![bildschirmfoto vom 2017-10-27 16-30-06](https://user-images.githubusercontent.com/12717530/32109172-3460e192-bb34-11e7-9f91-6f02710c95dc.png)

@ckamm What is the effort to bring this to the desktop client? /cc @guruz @ogoffart @SamuAlfageme

**Comment by ogoffart** [comment]
I don't think it is too difficult.  But this would still be something we would only do in 2.5, right?  (because otherwise it would delay the 2.4 release)


(I'm wondering if it would not be better to open the browser to share instead of having a native dialog, that way we always have the same ui.  (but that would need a decent single sign on mechanism))

**Comment by SamuAlfageme** [comment]
@ogoffart 👍  for 2.5, no need to rush this over 2.4

> (I'm wondering if it would not be better to open the browser to share instead of having a native dialog, that way we always have the same ui. 

I wonder the same; see comments in https://github.com/owncloud/client/issues/5796 and https://github.com/owncloud/client/issues/5797. However, I like the minimalist approach of client's native sharing dialog **and all @ckamm's nice redesigns for 2.4/2.5** (meaning I'd still keep it for straightforward tasks)

> (but that would need a decent single sign on mechanism))

yup: https://github.com/owncloud/client/issues/633 was one of my main ideas for the upcoming ownCloud hackweek

**Comment by michaelstingl** [comment]
> we would only do in 2.5, right?

yes

> decent single sign on mechanism

==> next week 😉

**Comment by ckamm** [comment]
It's a minor change.

Fwiw, I'd be perfectly fine with replacing the native UI if we can make it work reliably and smoothly for the user.

**Comment by pmaier1** [comment]
Sorry to open this again but we refined the wording for the web interface and I would like to adapt this for the next client release as well:

- [ ] Download / View
Recipients can view or download contents.
- [ ] Download / View / Upload
Recipients can view, download, edit, delete and upload contents.
- [ ] Upload only (File Drop)
Receive files from multiple recipients without revealing the contents of the folder.

![link_share_permissions](https://user-images.githubusercontent.com/21193500/38415374-993de688-3991-11e8-803c-055d83ce2d17.png)

**Comment by michaelstingl** [comment]
For comparison: This was planned for 2.5:

| oC server 10.0.4 | (was) planned for 2.5 |
| - | - |
| ![oC server 10.0.4](https://user-images.githubusercontent.com/12717530/32109172-3460e192-bb34-11e7-9f91-6f02710c95dc.png) | ![planned for 2.5](https://user-images.githubusercontent.com/833306/33939474-a603d68c-e00b-11e7-8228-8a0e87a06748.png) |

**Comment by pmaier1** [comment]
@michaelstingl looks good, so only wording change :+1: 
@PVince81 Possible to reduce the opacity / make the inline text grey similar to this screenshot: 
![link_expiration](https://user-images.githubusercontent.com/21193500/38416630-97ce0c16-3995-11e8-85bf-c561554152f2.jpg)

**Comment by michaelstingl** [comment]
@pmaier1 Changing again is pain, but I also prefer the new wording for non-tech users.

@ckamm I'm very sorry, but could you do your magic once again for us? Thanks!

**Comment by ckamm** [comment]
It's a straightforward change, sure :)

**Comment by pmaier1** [comment]
> Please don't call the headline "Link properties". Can we agree on just having Permissions?

(Or just remove the headline as there is none in the WebUI as well)

> It's a straightforward change, sure :)

:+1:
