### ISSUE TITLE
owcloudcmd dependencies for debian/ubuntu

### ISSUE THREAD

**Issue by RandomReaper** [owncloud/client#6197]
The command line client (`owncloudcmd`), is packaged with the graphical client, and thus depends on gui libraries. 

Since installing all the Xorg libraries on a headless machine is a non-sense, I would like to suggest the creation of a separate .deb for the client.

Package from : deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/
Version (as of today) : 2.3.4-8626

**Comment by SamuAlfageme** [comment]
This has been a long running discussion in the client (see https://github.com/owncloud/client/issues/2002) - And I think a lightweight client makes sense. Would be straightforward to create a separate package for `owncloudcmd` and keep it bundle in the current `owncloud-client` package? Are there any strong dependencies with the normal client? 

cc/ @dschmidt

**Comment by RandomReaper** [comment]
Ouch, I completely missed that the `owncloudcmd` is not a daemon... so please forget about this issue. Is there any way to "vote up" the #2002 issue?

**Comment by michaelstingl** [comment]
> Is there any way to "vote up" the #2002 issue?

==> https://www.bountysource.com/issues/3316729-add-a-sync-client-daemon
