### ISSUE TITLE
not correctly signed tarball owncloudclient-2.4.0-beta1.tar.xz

### ISSUE THREAD

**Issue by hefee** [owncloud/client#6199]
i downloaded the newest tarballs with download page and the signatur is not valid:
```
$gpg --verify owncloudclient-2.4.0-beta1.tar.xz.asc owncloudclient-2.4.0-beta1.tar.xz
gpg: Signature made Do 16 Nov 2017 15:34:37 CET
gpg:                using RSA key 0x498C45EBE94E7B37
gpg: BAD signature from "ownCloud Client Team (Signing Key) <info@owncloud.com>" [unknown]
```

**Comment by ogoffart** [comment]
@jnweiger: please have a look.

**Comment by guruz** [comment]
I can confirm this. Heh.

**Comment by guruz** [comment]
@hefee All good. The tar.xz file is still with same contents as the one from release day. But @jnweiger accidently recreated the tar.xz when he re-created the linux packages.

We'll update the signatur.

**Comment by guruz** [comment]
```
-----BEGIN PGP SIGNATURE-----

iQIcBAABAgAGBQJaHpz1AAoJEEmMRevpTns3kxAQALWAsQM+mr1xn7hjwH/XaCtc
8lpiMdQHoQo4pZmuP1mv5KvcVrUeBws9MIvWgwfiBrLzbocRkEffXeVijYc2BVpg
eJFM2WuYbgtEaO3WnktE5l1ZZqb1ROtTio9ZvCBgLf8kxBXLgCHOr7gou4PydrId
mw0d4oPEkf8VkE0bJ7vN2r9thPh2wwAzeNcVjnA9eY4GsfNLjTNg6Bd+gsYLpuq/
VTbz9U+3PRSawgFhxjjHrFdX8CR/lJQTrIoWwcqz6LMPgHLVmkn/DthJ0Rnj2dGv
2pdyDvp0tw0sfMjN0Zp+xMhXdnWpsvpLM+E9qNXZISsAxhyMUmk3eMgHm+DoSgnu
Xc8k5tXyZh2YLmxPztujVg6OQO8aIovcz/sGAVFcy4s7dbsW6VzC1crLAe6hTnR4
sQROenSopV8pJhJIvr0nzTbbyG6AbbsM95riJmhnhL9aT0g1pU+J1CsHl6WmmnuT
69ptigDUOPJiPxn8u9esQ8Rwgcj8ZDkPtbZ4SgqN6eZm3K3q+pT45ugP5ZTvV+Ud
W8PNbT/XQ+cOxcrxMSUiBSOW21pecqNmium5mq41T/LXnq0lY/K1Ddb9VwwERd5P
8SrXvNTTbEnBs5j+wnYnyAE85fXKtkvY//25Q1oLl24mRDlxZ9HBO5asrPoINNEZ
AeXTZFis3Pn4y9oBWCqD
=2N01
-----END PGP SIGNATURE-----
```

Sorry for the confusion!

**Comment by jnweiger** [comment]
Yes, please update the signature. I was not aware that the source tar ball gets  auto-uploaded whenever jenkins rebuilds something. Sorry for this!

**Comment by jnweiger** [comment]
@hefee new owncloudclient-2.4.0-beta1.tar.xz.asc published. Please check again in half an hour, when the mirrors are synced.

**Comment by guruz** [comment]
@jnweiger Why not give the source tarball a build number too? (and therefore also the .asc)

**Comment by jnweiger** [comment]
The source tar ball has exactly the content from the github tag v2.4.0-beta1 -- a build number would only add confusion. It would be much better, if rerolling the same tar with the same machinery from the same github tag would create an indentical tar.

I hope it is only timestamps or random permutations that make up the difference ...

**Comment by JcChimjj** [comment]
本人：大叔Chim  請問為何我！從來都收不到你們(此線程)的任何通知？？
jcchimjj

**Comment by hefee** [comment]
jepp fixed
