### ISSUE TITLE
Permissions  of $HOME/.local/share/data

### ISSUE THREAD

**Issue by timesuptim** [owncloud/client#6201]
### Expected behaviour
The desktop client should remember what I told it. It seems to be because the directory $HOME/.local/share/data had permissions 660 which stopped the client reading the directory.

### Actual behaviour
It didn't work. Fixing permissions with 
chmod 770 .local/share/data
makes it work.

### Steps to reproduce
1. Normal install
2. Re enter server details on each reboot and be frustrated
3. Change permissions as above
4. Works again, so be happy!

### Server configuration
Operating system:
Linux 
Web server: 
cloud.servus.at
Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:
Built from Git revision 80aac8 on Nov 3 2017, 19:31:33 using Qt 5.6.2, OpenSSL 1.0.1f 6 Jan 2014
Operating system:
Linux Ubuntu 14.04
OS language:
German and English
Qt version used by client package (Linux only, see also Settings dialog):
5.6.2
Client package (From ownCloud or distro) (Linux only):

**Comment by ogoffart** [comment]
Why would you set the permission of `$HOME/.local/share/data` to 660 ?

**Comment by timesuptim** [comment]
It was set to 660 automatically. I had to change it to 770 manually.
Possible fix: if the directory already exists, then change its permissions explicitly to 770, or at least that these bits are set. I "presume" that some other installation had created the folder and given it the wonky permissions (for unknown reasons).
Question: can I look in some log file and see when that directory was created by some installation?

**Comment by ogoffart** [comment]
I don't know how to find out why the directory had these wrong permissions. Nobody else ever reported the problem and i think it is just a problem with your configuration.

I don't think we need to handle this case, so i'm closing this bug.

If you ever find out why it was set to 660 and that there are reasons to believe that it may happen to several user, we could consider do something.
