### ISSUE TITLE
Rework the folder selection state depending on sync settings on subfolders (2 bugs) / Initialy: Checkbox missing in Folder Tree

### ISSUE THREAD

**Issue by ldmpub** [owncloud/client#6208]
### Expected behaviour
Checkbox  at top level should be "selected" to inform user that a sublevel is selected for sync.
Actual behaviour is particularly confusing when tree is collapsed.

### Actual behaviour
Missing "greyed tick": it's an indication of a partial selection (UI standard for ages ... see application setup when choosing options and suboptions for installation).

### Steps to reproduce
See screen shot.

### Client configuration
Client version: 2.3.4
Operating system: XUbuntu
![owncloud client - misses a tick](https://user-images.githubusercontent.com/1452146/33523385-b40433b6-d805-11e7-95e8-e2cb478563c5.png)

**Comment by ogoffart** [comment]
How do you reproduce the problem.  How did you get in this state?

**Comment by ldmpub** [comment]
Step to reproduce (bug 1 / above)
1. Top folder no selected for sync
2. Expand
3. Select a subfolder ... you've got it.


But the is an other bug on the behaviour of the "father folder tick" (bug 2):
1. Select the father for sync
2. Then unselect all sub folders ... the parent folder is not automatically deselected ... see new screen shot.

Note: folder "Translations" has no file content (it contains only subfolders).

![unselect al subfolders does not remove father folder selection](https://user-images.githubusercontent.com/1452146/33524831-2e954a34-d824-11e7-8837-da607138b5c0.png)

I will change issue title to a more general "Rework the folder selection state depending on sync settings on subfolders (2 bugs)". Please have a look at #6209 which is also a bug on the way folders are displayed in Sync settings.

**Comment by ogoffart** [comment]
I cannot reproduce your first bug. When selecting an item, the parent is always put in the intermediate state.

The second bug however is the expected behavior, because new files or folder for this folder will be sync'ed.

**Comment by ogoffart** [comment]
I really don't understand how you can get into a state where child folder are selected when the parent folder is not.  "Select a subfolder" automatically partially check the parent folder.

**Comment by michaelstingl** [comment]
@ogoffart I think @cdamken knows a way to reproduce too

**Comment by guruz** [comment]
...isn't what @ldmpub shows in the original post something else than what @cdamken shows in his screenshots?

@ldmpub Try 2.4.1 instead indeed.. and report back :)

**Comment by ogoffart** [comment]
@cdamken right, that is not what was originaly reported, in which a selected subfolder was under a completely selected folder. (while here, you have 

I created a patch that "fix" the behavior you are seeing : https://github.com/owncloud/client/pull/6482 
However I don't think it is such a good idea to land this patch, as it disalow unchecking directories while still checking for the files or new directories in the parent directory.

**Comment by ogoffart** [comment]
Closing old issue that cannot be reproduced
