### ISSUE TITLE
[Feature Request] Windows uninstalling - keep credentials, settings, data (yes/no)

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#6217]
Running version 2.3.4 (build 8624) on Win10x64

**Currently:**
When uninstalling the client, all data, credentials and settings are kept.
This means, that even after rebooting and reinstalling the client, I do not need to reenter my data to connect respectively need to do the resetup. Beside of having a clean uninstall, this is also a serious security issue !

**Feature Request:**
When uninstalling, it should ask if following items, a checkmark for each, should be kept or deleted: client credentials plus settings and sync data.

I do not know how this is in *unix derivates, maybe the same or similar issue !

**Comment by SamuAlfageme** [comment]
Agreed, duplicated of https://github.com/owncloud/client/issues/5342
