### ISSUE TITLE
Produce a notification when a new folder matching the selective sync list contents appears in the FS

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6222]
This is by request of the mighty @cdamken 

### Steps to reproduce:

1. Uncheck a folder on your selective sync list
2. Create a folder matching that folder name
3. An entry about the ignored item because of the "choose what to sync" blacklist appears in the activity tab. 

### Expected Result 

A notification should be issued since the client is ignoring the user actions in that folder and might call for resolution in the selective sync list.

**Comment by ckamm** [comment]
So the suggestion is that when the user creates "foo/" when that path was excluded through the selective sync functionality: emit a notification about it.

**Comment by SamuAlfageme** [comment]
@ckamm exactly that, yeah. So the user is aware of any changes made locally that are currently not being synced because our internal logic.

Scenario: the user in the past didn't select the "Photos" to sync and he forgot. Turns out that he created now a new local "Photos" folder and it's not being synced, the user doesn't know why until he takes a look into the Activity > "Not Synced" tab.
