### ISSUE TITLE
Wrong status for app icon in task bar

### ISSUE THREAD

**Issue by ldmpub** [owncloud/client#6225]
See screen shot during a file synchro:
- M$ Windows explorer says "synchronizing"
- The same in the App Window
- but the app icon in task bar says "synchronized" which is wrong.

![inconsistance in status on app icon](https://user-images.githubusercontent.com/1452146/33796301-bd014d5a-dcf1-11e7-8289-c9878de15a0d.png)

**Comment by michaelstingl** [comment]
Duplicate for https://github.com/owncloud/client/issues/5860

**Comment by ldmpub** [comment]
Sorry for the duplicate, I will follow ##5860.
