### ISSUE TITLE
"Not synchronized" tab gets cleared when skipping local discovery

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#6226]
### Expected behaviour
The "Not synchronized" tab contains critical information such as file conflicts. This information should be persistent until the application is closed or until it is superseded by other, similar information.

### Actual behaviour
It appears that the list of errors and warnings belonging to a specific folder is cleared the next time that folder is synchronized. While it may make sense for ignored files and such, I can no longer see previous messages regarding conflicts and other errors - despite the main page telling me that there was a conflict. If I click on that information, I just see an empty log.

### Steps to reproduce
1. Synchronize a folder.
2. Synchronize another folder.
3. Synchronize the folder from step 1 again.

### Client configuration
Client version: 2.4.0rc1

Operating system: Windows 7

OS language: German

Installation path of client: Default

**Comment by ckamm** [comment]
The conflict information should be rediscovered by each the sync run. The idea was to use the data the sync run gathers to keep the conflict entries up to date. I'll attempt to reproduce this later.

**Comment by ckamm** [comment]
I can reproduce the problem like this:
* produce a conflict
* notice the conflict entry on the first sync that created it
* restart the folder sync with F6
* the conflict entry is gone

**Comment by ckamm** [comment]
The bug becomes visible when local discovery is skipped. There was a bug that made skipping of local discovery inconsistent. With that addressed I can also reproduce this reliably.

**Comment by guruz** [comment]
@sagamusix  Do you want to try 2.5.0 alpha1? https://github.com/owncloud/client/releases

**Comment by SamuAlfageme** [comment]
I see this solved now; tried both reproducers - @sagamusix care to confirm?

**Comment by sagamusix** [comment]
I couldn't test it yet but will try to do so during the weekend!

**Comment by guruz** [comment]
@sagamusix ping.. just if you had a chance.

**Comment by sagamusix** [comment]
Sadly I haven't been running ownCloud a whole lot in the last weeks so I wasn't able to actively test this, but I remember that there was one conflict that was still being displayed after a while, so I'll assume for now that it works. Feel free to resolve.
