### ISSUE TITLE
Dolphin overlay icon size is not constant

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#6230]
### Steps

1. Upload a bunch of pictures with different sizes, portrait, landscape, and also some videos
1. Wait for sync
1. Open the folder with dolphin

### Expected result
Indicator always has the same size as it's supposed to be an addition on top of the thumbnails.

### Actual result
Indicator seems to be embedded into the image and its size seems to be influenced by the scaling of individual images.

See that the icon size is not the same for every entry here:
![image](https://user-images.githubusercontent.com/277525/33837952-4aa6e8e8-de8e-11e7-9709-0c0a85d3c7a9.png)

### Version
owncloud-client-2.4.0~rc1-8802.5.x86_64
owncloud-client-dolphin-2.3.4-8626.1.x86_64

Weird mismatch of package versions: https://github.com/owncloud/client/issues/5976#issuecomment-350753816

**Comment by ckamm** [comment]
I assume this is an issue in dolphin since the dolphin plugin only returns a list of overlay icon names.

**Comment by PVince81** [comment]
dolphin-17.08.3-1.1.x86_64

**Comment by ckamm** [comment]
I can reproduce this in with the "Compact" view mode in dolphin. It's definitely an upstream issue - the composited image is scaled instead of applying the icon after the scaling.

**Comment by ogoffart** [comment]
Upstream issue.
