### ISSUE TITLE
Dolphin overlay stuck on sync mode after folder creation

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#6234]
### Steps

1.Setup OC client 2.4.0~rc1
1. Wait for sync
1. Open dolphin
1. Navigate into ownCloud sync folder
1. Create a folder "test"
1. Wait for sync

### Expected result
After sync, the overlay icon for "test" becomes a blue tick mark.

### Actual result
Overlay icon is stuck on the red "syncing" icon. Need to refresh the page to update it.

### Version
openSUSE Tumbleweed
owncloud-client-2.4.0\~rc1-8842.1.x86_64
owncloud-client-dolphin-2.4.0~rc1-8842.1.x86_64
dolphin-17.08.3-1.1.x86_64

**Comment by ckamm** [comment]
I cannot reproduce it with master unfortunately. For me, the newly created folder gets a blue tick mark immediately. Possibly it's already fixed?
