### ISSUE TITLE
[Notifications] Open "link" in browser 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6236]
This is quite similar to the FR in https://github.com/owncloud/client/issues/5922, this time about the "`link`" property of the notifications we get from the server. This got my eye on Marketplace notifications. 

Tagging as discussion to see if this is something that would bring value to users. e.g. an admin clicking on a desktop notification to open an app's page in marketplace to update the version: 

```json
{
   "ocs":{
      "meta":{
         "status":"ok",
         "statuscode":200,
         "message":null,
         "totalitems":"",
         "itemsperpage":""
      },
      "data":[
         {
            "notification_id":1,
            "app":"market",
            "user":"admin",
            "datetime":"2017-12-12T07:54:04+00:00",
            "object_type":"market",
            "object_id":"0.2.3",
            "subject":"Update for Market to version 0.2.3 is available.",
            "message":"",
            "link":"<server>/apps/market/#/app/market",
            "actions":[],
            "icon":""
         }
      ]
   }
}
```

This one gets rendered as: 

![screenshot 2017-12-12 16 21 00](https://user-images.githubusercontent.com/2644445/33892190-78567c70-df58-11e7-8054-2956e9dd2dd4.png)

We could simply add a new button to open it in browser or make the whole thing clickable.

**Comment by guruz** [comment]
Indeed there is no link option from command line at least. I'll hack the source or so.

```
notifications:generate [-u|--user USER] [-g|--group GROUP] [--] <subject> [<message>]
..
sudo -u http ./occ notifications:generate -u guruz hello_subject "hello this is guruz speaking"
```

FYI @tomneedham

**Comment by guruz** [comment]
> Indeed there is no link option from command line at least. 

https://github.com/owncloud/notifications/pull/172

**Comment by guruz** [comment]
-> https://github.com/owncloud/client/pull/6453

**Comment by ckamm** [comment]
Tested manually on a oc-master instance by using the `occ notifications:generate` command.
