### ISSUE TITLE
Regex excludes cause existing patterns to behave differently

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6245]
From @sagamusix #5017 
> for example my pattern */.svn/pristine/ no longer seems to work

Summary from investigation:

The client used `fnmatch` with `FNM_PATHNAME` on unix and `PathMatchSpec` on Windows. These had different behavior when expanding `*` patterns: `fnmatch` never expands it to `/`, while that is allowed on windows. That means `*/foo/bar` would match `a/b/foo/bar` on windows, but not on other oses.

The new regex exclude matching code implements the `fnmatch` behavior on all platforms thereby changing the meaning of existing patterns on windows.

**Comment by ckamm** [comment]
@sagamusix So it's now syncing some folder foo/.svn/pristine and its contents?

**Comment by sagamusix** [comment]
Exactly, and previously these files were ignored as intended.

**Comment by ckamm** [comment]
@sagamusix It works for me. The pattern gets translated to `[^/]*/\.svn/pristine)(?:$|/)`. Can you let me know what path exactly was excluded before and isn't anymore?

**Comment by sagamusix** [comment]
Two paths were matched before I realized and aborted the sync; one was `Uni\powerwall-trunk\.svn\pristine` and the other one was similar in structure. It seems like if I move the folder one level up, it works as intended, which coincides with your idea, I think.

**Comment by sagamusix** [comment]
I have changed the pattern to just `.svn/pristine` (including all other patterns in my list that were structured similarly) and it seems like the initial discovery is much, much slower now - it's now running for almost an hour for a folder that previously took a few minutes. In fact, it's still discovering folders so I cannot see yet if it helps fixing the problem.

**Comment by ckamm** [comment]
@sagamusix changing too `.svn/pristine/` still wouldn't trigger the right behavior. See https://github.com/owncloud/client/issues/5275 for discussion of the unclear behavior.

**Comment by ckamm** [comment]
Yes, unfortunately. But I don't think it's acceptable to break patterns windows users had added. I think we'll need to put in extra work to make sure that migrates nicely.

And that performance issue you're seeing also definitely needs to be investigated.

**Comment by ckamm** [comment]
I'm looking at allowing `*` to match `.*` in the regex: it complicates the bname-as-activation optimization though since `foo/bar*daa` could very well be activated by a bname `xyzdaa`. It may be ok to be just mostly correct here.

**Comment by ckamm** [comment]
@sagamusix I've adjusted the regex matching on windows to be backwards compatible. Could you check out the new 2.5 nightly when it becomes available?

**Comment by sagamusix** [comment]
Judging from the timestamps, I guess the current nightly build doesn't have the fix yet, right?

**Comment by ckamm** [comment]
@sagamusix Available now: http://download.owncloud.com/desktop/daily/ownCloud-2.5.0.8967-nightly20180110-setup.exe

**Comment by sagamusix** [comment]
The patterns seem to work as intended again, although initial discovery still seems to have slowed down considerably. Waiting more than two hours now and the actual sync still hasn't happened.

**Comment by ckamm** [comment]
@sagamusix Ouch, that's horrible. Let's move back to the optimization task #5017. Thanks for testing.
