### ISSUE TITLE
what problem when i try run owncloud.exe

### ISSUE THREAD

**Issue by NguyenVanVuong** [owncloud/client#6246]
When i run owncloud.exe win show The procedure entry point usearch_getCollator_52 could not be loacted in the dynamic link library
c:qt\..\qt5webkit.dll

**Comment by michaelstingl** [comment]
@NguyenVanVuong Thank you very much for reporting this issue. Please check [the issue template](https://raw.githubusercontent.com/owncloud/client/master/.github/issue_template.md). (some essential information is missing in your report)
