### ISSUE TITLE
Folders named "logs" do not get synced

### ISSUE THREAD

**Issue by Wrumm** [owncloud/client#6247]
### Expected behaviour
Folders names "logs" are synced as all other folders.

### Actual behaviour
Content in a folder named "logs" is not synced with the error message on the client "server replied: Method not allowed"

### Steps to reproduce
1. Create a folder named "logs" in any currently synced folder 
2. Put any file(s) into that new folder e.g. a create a new text file names "test.txt"
3. The error in the sync client occures

### Server configuration
Operating system:
OpenSuse Leap 42.3
Docker 17.04.0-ce

Web server: 
Apache

Database:
MySQL

PHP version:
7.1.2

ownCloud version:
Nextcloud 12.0.4

Storage backend (external storage):
none

### Client configuration
Client version:
Nextcloud 2.3.2

Operating system:
Windows 10 1703

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
In the Window it is shown: "server replied: Method not allowed"

2. Web server error log:
None

3. Server logfile: ownCloud log (data/owncloud.log):
None at this point in time
Several entries of this but that is a known php issue:
{PHP} Narrowing occurred during type inference. Please file a bug report on bugs.php.net at /var/www/html/lib/composer/composer/ClassLoader.php#444

**Comment by guruz** [comment]
```Method not allowed``` is ALWAYS a server-side issue. :-) 

> Nextcloud 12.0.4

Please try in https://github.com/nextcloud/server/issues

**Comment by hodyroff** [comment]
How many weird bugs does it need for you to switch back to ownCloud?

**Comment by brunt82** [comment]
"Server" must not mean the implementation of the server. I could also mean the configuration. Compare this one: https://github.com/owncloud/core/issues/8536
