### ISSUE TITLE
Can't build client on Windows 10

### ISSUE THREAD

**Issue by newfuture33** [owncloud/client#6249]
### Expected behaviour
Tell us what should happen
build client on Windows 10
### Actual behaviour
Tell us what happens instead
get error in step 7 in Windows Development Build
### Steps to reproduce
followed by https://doc.owncloud.org/desktop/2.3/building.html
1. step 1
CMake 3.10.1 x64 Git 2.15.1
qt-5.5.0-x64-mingw510r0-seh-rev0
Win64OpenSSL-1_1_0g
2. step 2 ~ 6
same as manual
3. step 7
cmake -G "MinGW Makefiles" ../client

then show error 
Could Not find INOTIFY (missing: INOTIFY_INCLUDE_DIR INOTIFY_LIBRARY_DIR)
Could Not find Sphinx (missing: SPHINX_EXECUTABLE)
Could Not find PdfLatex (missing: PDFLATEX_EXECUTABLE)
...
Cound NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR)

### Client configuration
Client version:
2.4
Operating system:
Windows 10

**Comment by NguyenVanVuong** [comment]
u download zlib and install it will ok

**Comment by SamuAlfageme** [comment]
@newfuture33 hm, those libraries are needed to generate the documentation. You can try to run `cmake` with the `-DWITH_DOC=FALSE` flag so they're not required on compilation (as cmake won't try to build'em out)

You can also check both, the dependencies installed on the Dockerfile used to create the windows installer in https://github.com/owncloud-docker/docker-ownCloud-client-win32/blob/master/2.4/Dockerfile and the build steps in https://github.com/owncloud/administration/blob/master/jenkins/win32_build/compile_client.sh

**Comment by guruz** [comment]
@SamuAlfageme ZLIB is a mandatory dependency now for the client itself, we should update our build instructions.

**Comment by mono1981** [comment]
Thank you SamuAlfageme and guruz.
I installed all environment including ZLIB so that compiled with no error.
But compile after Client, there's no exe, Do you have any idea?

**Comment by dschmidt** [comment]
> But compile after Client, there's no exe, Do you have any idea?

What does that mean? Any build output you can share?

**Comment by guruz** [comment]
Closing for now..
