### ISSUE TITLE
Windows: Re-enable stack protection

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6250]
See https://github.com/owncloud/client/commit/298f1ab57000afd7acb8c0ddbddca8a1fc6cd92a
https://github.com/owncloud/client/pull/6229#issuecomment-352021918

**Comment by ckamm** [comment]
Reenabling would be trivial. Packages also need to include at least `libssp-0.dll` though.

**Comment by guruz** [comment]
> Packages also need to include at least libssp-0.dll though.

Did @dschmidt do this issue?
7839c4d4e1192a14165fef546b074e78acbc61d1 1f9763eda9db9e9aead8060f7f222e0d3f2bf1ce

**Comment by ckamm** [comment]
@dschmidt Closing since this looks done!

**Comment by guruz** [comment]
...also for the MSVC-based 2.5 builds?

**Comment by ckamm** [comment]
Ok, thought this was only about undoing 298f1ab

**Comment by guruz** [comment]
MSVC by default has
https://msdn.microsoft.com/en-us/library/8dbf701c.aspx
https://msdn.microsoft.com/en-us/library/bb384887.aspx
CC @rockihack

**Comment by rockihack** [comment]
:+1:
Just to make sure it works as intended you can use `dumpbin /headers owncloud.exe`.
Also DEP (https://msdn.microsoft.com/en-us/library/ms235442.aspx) and High Entropy ASLR for 64bit executables (https://msdn.microsoft.com/en-us/library/dn195771.aspx) should be enabled by default.
