### ISSUE TITLE
CPack Error: Problem running NSIS command: "/usr/bin/makensis"

### ISSUE THREAD

**Issue by NguyenVanVuong** [owncloud/client#6257]
i use open suse 42.3
ownCloud version:2.4

Run CPack packaging tool...
CPack: Create package using NSIS
CPack: Install projects
CPack: - Run preinstall target for: client
CPack: - Install project: client
CPack: Create package
CPack Error: Problem running NSIS command: "/usr/bin/makensis" "/home/user/client/build-win32/_CPack_Packages/unused/NSIS/project.nsi"
Please check /home/user/client/build-win32/_CPack_Packages/unused/NSIS/NSISOutput.log for errors
CPack Error: Problem compressing the directory
CPack Error: Error when generating package: ownCloud
Makefile:140: recipe for target 'package' failed
make: *** [package] Error 1
Test project /home/user/client/build-win32
No tests were found!!!

**Comment by SamuAlfageme** [comment]
Hey @NguyenVanVuong you can check both, the dependencies installed on the Dockerfile used to create the windows installer in https://github.com/owncloud-docker/docker-ownCloud-client-win32/blob/master/2.4/Dockerfile and the build steps in https://github.com/owncloud/administration/blob/master/jenkins/win32_build/compile_client.sh

Also, refer to https://central.owncloud.org/t/building-the-windows-installer/8403/8 for more info on your particular error. If you happen to have more doubts/issues with the building process, report those in https://central.owncloud.org. Thanks!
