### ISSUE TITLE
Allow enabling/disabling the beta update channel

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6259]
Recently I saw how some colleagues were offered to update to 2.4-RC2 (https://github.com/owncloud/enterprise/pull/2362) after we introduced support for beta channels in #6048

Would be cool to give the users the chance to only display update notices on stable releases on the Settings window. 

Related https://github.com/owncloud/enterprise/issues/2367

**Comment by guruz** [comment]
@SamuAlfageme the logic is: If you use a alpha/beta/rc currently, then you get more alpha/beta/rc.
;-)

**Comment by ckamm** [comment]
Edited to make this into a gui setting. For nightlies etc. it'd default to the beta channel, as right now, for stable releases it'd default to stable.

**Comment by ckamm** [comment]
@guruz So for instance the testcloud client shouldn't show the channels, and neither should any other branding that has an `APPLICATION_UPDATER_URL`?

**Comment by guruz** [comment]
You are right, testpilotcloud should show it too.
Other brandings - Hm, we can't know yet so better hide it?

**Comment by guruz** [comment]
Although for simplicity maybe just show it as soon as there is a ```APPLICATION_UPDATER_URL```

**Comment by michaelstingl** [comment]
Not many branding users have own `APPLICATION_UPDATER_URL` configured.

**Comment by SamuAlfageme** [comment]
@michaelstingl but there's also not that many branding users building their own (branded) beta versions. In the future, we could ease beta generation/distribution for them provided they have a URL to server them.

**Comment by SamuAlfageme** [comment]
Maybe @ChrisEdS is interested on this topic, since IIRC he's going to run beta distribution for the iOS client, right?

**Comment by ChrisEdS** [comment]
Oh, yes. I am an automation fan! I am currently working on my thesis with complete automation of all iOS tasks related to releases. Beta releases are already automated.

**Comment by guruz** [comment]
Closing.
The next releases will have a drop down to switch the channel.
If you downloaded a alpha/beta/rc yourself, it's your own fault :)
