### ISSUE TITLE
vcredist_x86.exe -> no files found.

### ISSUE THREAD

**Issue by NguyenVanVuong** [owncloud/client#6261]
when i try cross build in suse 42.1 
i recive warning: File: "/home/user/client/build-win32/bin/owncloud_crash_reporter.exe" -> no files found.
"/home/user/client/build-win32\vcredist_x86.exe" -> no files found.

**Comment by SamuAlfageme** [comment]
Refer to https://central.owncloud.org/t/building-the-windows-installer/8403/8 for info on the cross-compilation build. If you happen to have more doubts/issues with the building process, report those in https://central.owncloud.org. Thanks!
