### ISSUE TITLE
2.4.0 crashes, 2.4.0rc2 did not (OSX 10.7.5)

### ISSUE THREAD

**Issue by thetrial** [owncloud/client#6264]
### Expected behaviour
The client should at least act and work like its final rc2. But it immediately crashes when starting.

### Actual behaviour
It crashes.

### Steps to reproduce
Just replace 2.4.0rc2 with 2.4.0 on a OSX 10.7.5 machine.

### Server configuration
Operating system:
Raspbian
Web server: 
Apache
Database:
…
PHP version:
…
ownCloud version:
10.0.4
Storage backend (external storage):
-
### Client configuration
Client version:
2.4.0 and 2.4.0rc2
Operating system:
OSX 10.7.5
OS language:
German
Qt version used by client package (Linux only, see also Settings dialog):
-
Client package (From ownCloud or distro) (Linux only):
-
Installation path of client:
-
### Logs
No logs, I forgot to save them before switching back to the rc2, sorry.

**Comment by guruz** [comment]
Works for me on 10.12.6.
Could you right-click on the ```/Applications/owncloud.app``` and check the exact version? Mine is 2.4.0 (build 8801)

**Comment by guruz** [comment]
I guess the system requirements here were not adjusted.
https://doc.owncloud.org/server/latest/admin_manual/installation/system_requirements.html#desktop

**Comment by guruz** [comment]
Are you sure it was rc2 and not rc1?
The difference could be the OpenSSL update? @michaelstingl @jnweiger But I can't find anywhere what is the minimum version for that.
(The stack protector change was already in rc2)

**Comment by guruz** [comment]
@thetrial Can you try to get a backtrace to confirm? (I don't see anything in our crash reporter..so it crashes/quits quite early. Were you asked to submit a crash report?)

In Terminal run:
```
lldb /Applications/owncloud.app
```
Then on crash try:
```
bt all
```
and paste the full output here. thank you

(You might need to disable our crash reporter, if this is the case check https://github.com/owncloud/documentation/issues/3583)

**Comment by michaelstingl** [comment]
oC desktop sync client 2.4.0 requires macOS 10.10+ (has been announced with the release of 2.3.3)

**Comment by guruz** [comment]
@michaelstingl But he wrote that 2.4.0rc2 still worked, that's why I'm still curious about what backtrace he gets. :)

**Comment by JayBrown** [comment]
Crashes on OS X 10.11.6. Here are four log files:

[owncloud_crashes.zip](https://github.com/owncloud/client/files/1591679/owncloud_crashes.zip)

**Comment by jnweiger** [comment]
These 4 crashes are an identical Illegal instruction fault when 
/Applications/owncloud.app/Contents/MacOS/libssl.1.0.0.dylib initializes itself and calls EVP_add_cipher from  /Applications/owncloud.app/Contents/MacOS/libcrypto.1.0.0.dylib

Did we update both of them to 1.0.2n or only libssl?

**Comment by guruz** [comment]
Related https://github.com/owncloud/client/issues/6268

**Comment by guruz** [comment]
@thetrial @JayBrown Could you try if https://download.owncloud.com/desktop/testing/ownCloud-2.4.0.8827.pkg is better (build number 8827 just created)

**Comment by JayBrown** [comment]
Nope. Crashes too.

[owncloud_crash_reporter_2017-12-29-122307.log](https://github.com/owncloud/client/files/1593018/owncloud_crash_reporter_2017-12-29-122307.log)

PS – one more thing: the pkg installer has this in the postinstall shell script:

```
osascript << EOF
tell application "Finder"
   activate
   select the last Finder window
	reveal POSIX file "/Applications/owncloud.app"
end tell
EOF
```

There are people (like me) who (rightfully) think that the Finder is total crapware, which is why Finder is disabled on our systems. And it tends to be annoying that some installers (like owncloud) activate (in our case: reactivate) the Finder, just to reveal the .app bundle. It would probably be better to reveal the ownload.app bundle using a more general method that does not involve Finder. But to my knowledge that's not possible, so maybe a different approach would be a little check if the system is running the Finder process, and if not, then do nothing, and if yes, then run the reveal-part of the script as usual.

**Comment by JayBrown** [comment]
In `bash` a Finder check would be like this:

```
if [[ $(ps aux | grep "/System/Library/CoreServices/Finder.app/Contents/MacOS/Finder" | grep -v "grep") != "" ]] ; then
	# Finder is running
	osascript << EOF
tell application "Finder"
	activate
	select the last Finder window
		reveal POSIX file "/Applications/owncloud.app"
end tell
EOF
fi
```

Don't know how to do it in `sh`.

**Comment by guruz** [comment]
Let's track this in https://github.com/owncloud/client/issues/6268
Thanks so far @JayBrown @thetrial

**Comment by thetrial** [comment]
> Are you sure it was rc2 and not rc1?

What’s still working here: 2.4.0rc2 (build 8770). Like a charm.

> The difference could be the OpenSSL update? @michaelstingl @jnweiger But I can't find anywhere what is the minimum version for that.
> (The stack protector change was already in rc2)

2.4.0 not for OSX 10.7.5 … I heard a rumour? WTF? Why should …? It works. Normally. And what does not work, crashes because of other things.

Sorry I’d been travelling. Next days I’ll try to look. My las try to download showed me an offline OC server?!

**Comment by thetrial** [comment]
> oC desktop sync client 2.4.0 requires macOS 10.10+ (has been announced with the release of 2.3.3)

And why is rc2 working?! These are those stupid obsolescence decisions one cannot accept.

**Comment by guruz** [comment]
> These are those stupid obsolescence decisions one cannot accept.

It's not a decision, it's a bug :-( see https://github.com/owncloud/client/issues/6268

**Comment by thetrial** [comment]
> These are those stupid obsolescence decisions one cannot accept.
> 
> It's not a decision, it's a bug :-( see #6268

The bug’s not my problem, but hadn’t someone stated that 2.4 shall prerequisite a newer 10.something+? As rc2 works that made me wonder. I think, such ported clients can run wherever we want them to.

**Comment by thetrial** [comment]
I tried 8828, it crashed.

> @thetrial @JayBrown Could you try if https://download.owncloud.com/desktop/testing/ownCloud-2.4.0.8827.pkg is better (build number 8827 just created)

**Comment by thetrial** [comment]
> @thetrial Can you try to get a backtrace to confirm? (I don't see anything in our crash reporter..so it crashes/quits quite early. Were you asked to submit a crash report?)

I always sent the reports via this new internal dialogue. And at the moment I have one or two crash reports on my Mac Pro’s system. And yes, it points to ssl, what I see.

> In Terminal run:
> 
> lldb /Applications/owncloud.app
> 
> Then on crash try:
> 
> bt all
> 
> and paste the full output here. thank you
> 
> (You might need to disable our crash reporter, if this is the case check owncloud/documentation#3583)

Is this still necessary?

**Comment by thetrial** [comment]
I have to come back to this: » oC desktop sync client 2.4.0 requires macOS 10.10+ (has been announced with the release of 2.3.3)«

Why was rc2 working, why is even 2.4.0 working on 10.7.5, but there is no legacy finder overlay? So I revert back to 2.3.4? I’m really confused and don’t get it why you have to drop working stuff!
