### ISSUE TITLE
Completely uninstall macOS client

### ISSUE THREAD

**Issue by ey3432** [owncloud/client#6269]
How to completely uninstall the desktop client on macOS?

Expected behavior
I go to "Applications" and try to move nextcloud to the trash. It is completely removed.

Actual behavior
I cannot move nextcloud to the trash because it displays the attached error message.
![screen shot 2017-12-27 at 9 31 18 pm](https://user-images.githubusercontent.com/34285053/34401125-50703dd0-eb4d-11e7-930e-5ca5bd10de7f.png)

Steps to reproduce
1. Find the nextcloud client application
2. Attempt to move it to the trash
3. Receive an error message

Client configuration
Client version: nextcloud version 2.3.3
Operating system: macOS High Sierra version 10.13.2

**Comment by ey3432** [comment]
After searching the internet extensively, posting the issue on GitHub, and submitting a message via the "Contact Us" form of NextCloud, I finally came across this YouTube video: https://www.youtube.com/watch?v=cEHkK4r7_ks. I followed the steps outlined in the video and successfully uninstalled the NextCloud client from my Mac.

**Comment by SamuAlfageme** [comment]
@ey3432 Indeed this is a collateral of https://github.com/owncloud/client/issues/5382 and will be solved once we implement a way to close the extension after the client (see https://github.com/owncloud/client/issues/5382#issuecomment-267314626). I've seen myself many times forced to kill the extension manually to remove the `.app`.

Let's close in favor of that one and track there. Thanks for your report!

**Comment by guruz** [comment]
-> https://github.com/owncloud/client/pull/6444
