### ISSUE TITLE
Every update on windows creates a shortcut on my desktop

### ISSUE THREAD

**Issue by mueller-ma** [owncloud/client#6270]
### Expected behaviour
When updating the client on windows, the updater shouldnt create a shortcut on my desktop without asking.

### Actual behaviour
It does.

### Steps to reproduce
1. Update client

### Server configuration
Not required.

### Client configuration
Client version: 2.3.1

Operating system: Windows 7 64 bit DE

OS language: ?

Installation path of client: Not required.

### Logs

Not required.

**Comment by dschmidt** [comment]
The new MSI installer should remember whether the desktop icon was installed or not.
