### ISSUE TITLE
Mac OS X 10.11.6 - Owncloud desktop client fails installation

### ISSUE THREAD

**Issue by dubun290** [owncloud/client#6273]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
You did not specify anything in your bug report.
What "fails"?
Which errors?
When does it fail?

**Comment by guruz** [comment]
Please comment with more info if this is still an issue.
Latest macOS version is https://download.owncloud.com/desktop/testing/ownCloud-2.4.0.8836.pkg
