### ISSUE TITLE
csync failed to access on a new Macbook Pro

### ISSUE THREAD

**Issue by naziris** [owncloud/client#6274]
I have just bought a new MacBook Pro 2017. I installed the OwnCloud Client. Since 1st sync I receive the error csync failed to access. On my PC though Sync is working perfect, no errors at all. I can access and share my data through web page as well. I dont know what is going on with the mac client. On my previous mac it was working fine, as far as I remember.

How I connect to my Server: OS X Client -> IIS Server (Proxy & SSL) -> OwnCloud Server (HTTP)

### Expected behaviour
Sync my data

### Actual behaviour
Returns the csync failed to access error, after it checks my data.

### Steps to reproduce
1. Start sync my files
2. 
3. 

### Server configuration
Operating system: Debian 8

Web server: Apache 2

Database: mysql  Ver 15.1 Distrib 10.0.32-MariaDB

PHP version: PHP 7.0.26-1~dotdeb+8.2 (cli) ( NTS )

ownCloud version: 10.0.4.4

Storage backend (external storage):

### Client configuration
Client version: Latest

Operating system: High Sierra

OS language: US Eng

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: /Applications/

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

Log Files: https://gist.github.com/naziris/52b020f7ec3f377037ad03f1c2d593f4

**Comment by guruz** [comment]
What do you mean by "latest"? This is not an exact version. :)

Have you tried https://download.owncloud.com/desktop/testing/ownCloud-2.4.0.8836.pkg ?

**Comment by naziris** [comment]
2.4.0

**Comment by guruz** [comment]
@naziris there is a 4th number missing.

Have you tried the URL above? 2.4.0.**8836**

**Comment by naziris** [comment]
The version of the provided link on the website is a bit lower than that..I've tried the one you gave me but still the same error.

**Comment by ogoffart** [comment]
The error is caused because of a 404 durring the discovery.

Relevant log:

```
01-01 11:29:05:796 [ info sync.accessmanager ]:	6 "PROPFIND" "https://mycloud.naziris.com/remote.php/dav/files/naziris/Coding/menu/platforms/android/cordova/node_modules/nopt/bin" has X-Request-ID "41b762fc-b59d-43b2-9d28-391c2291baf4"
[...]
01-01 11:29:05:827 [ warning sync.networkjob ]:	QNetworkReply::NetworkError(ContentNotFoundError) "Server replied \"404 Not Found\" to \"PROPFIND https://mycloud.naziris.com/remote.php/dav/files/naziris/Coding/menu/platforms/android/cordova/node_modules/nopt/bin\"" QVariant(int, 404)
01-01 11:29:05:828 [ info sync.networkjob.lscol ]:	LSCOL of QUrl("https://mycloud.naziris.com/remote.php/dav/files/naziris/Coding/menu/platforms/android/cordova/node_modules/nopt/bin") FINISHED WITH STATUS QNetworkReply::NetworkError(ContentNotFoundError) "Server replied \"404 Not Found\" to \"PROPFIND https://mycloud.naziris.com/remote.php/dav/files/naziris/Coding/menu/platforms/android/cordova/node_modules/nopt/bin\""
01-01 11:29:05:829 [ warning sync.discovery ]:	LSCOL job error "Error transferring https://mycloud.naziris.com/remote.php/dav/files/naziris/Coding/menu/platforms/android/cordova/node_modules/nopt/bin - server replied: Not Found" 404 QNetworkReply::NetworkError(ContentNotFoundError)
01-01 11:29:05:830 [ debug sync.discovery ]	[ OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot ]:	2 "Error transferring https://mycloud.naziris.com/remote.php/dav/files/naziris/Coding/menu/platforms/android/cordova/node_modules/nopt/bin - server replied: Not Found"
[...]
01-01 11:29:05:842 [ warning sync.engine ]:	ERROR during  csync_update :  "CSync failed to access Coding/menu/platforms/android/cordova/node_modules/nopt/bin"
```

So the server seems to claim that there exist a directory called `Coding/menu/platforms/android/cordova/node_modules/nopt/bin`  but trying to list its content failed with a 404.
This looks like some cache problem on the server maybe.

**Comment by PVince81** [comment]
Please try running `occ files:scan --all`. If that doesn't fix the cache inconsistency, have a look at https://doc.owncloud.org/server/10.0/admin_manual/configuration/server/occ_command.html#the-repair-option

**Comment by skriesch** [comment]
The scan is working. We had the same problem in a case on central.owncloud.org:
https://central.owncloud.org/t/c-sync-failed-to-access-local-external-storage/12011/4

**Comment by guruz** [comment]
@naziris Can you report back if the scan worked for you too so we can close this issue? :)

**Comment by ogoffart** [comment]
This is a bug in the server.
The error message in the client were reworded in 2.5 to be a bit more explicit.
