### ISSUE TITLE
2.4.0 - test fails on alpha

### ISSUE THREAD

**Issue by hefee** [owncloud/client#6276]
After fixing the issue - building occ on alpha/hppa. We now run into a test failure on alpha:

```
[ RUN      ] check_c_tspecdiff_five
[  ERROR   ] --- 0x6 != 0x5
[   LINE   ] --- /<<BUILDDIR>>/owncloud-client-2.4.0+dfsg/test/csync/std_tests/check_std_c_time.c:55: error: Failure!
[  FAILED  ] check_c_tspecdiff_five
```
[2.4.0/alpha](https://buildd.debian.org/status/fetch.php?pkg=owncloud-client&arch=alpha&ver=2.4.0%2Bdfsg-1&stamp=1514728302&raw=0)

For me the code/test looks like it have some things missing:
* no test of 
```
c_tspecdiff(finish, start) == -c_tspecdiff(start, finish) 
```
(it looks wired that inside c_tspecdiff there are some tests like time0 < time1 but for me it looks not symetric and i would expect that code fails if you switch time0 and time1.)

* the (1E9 + 1) looks also wired. Why you divide to something different, when time0 > time1?

**Comment by ogoffart** [comment]
Note: this test is going to be removed in 2.5 by  https://github.com/owncloud/client/pull/6244/commits/0d86d4452592e4614accb7aa9599de7196d7641d

c_tspecdiff is only being used for logging purposed anyway, and not for the actual sync engine

**Comment by hefee** [comment]
@ogoffart sounds like a good idea to remove this code :D

**Comment by ogoffart** [comment]
Closing this because it is removed in 2.5, even if it is still failling in 2.4
