### ISSUE TITLE
Missing SQLITE3_INCLUDE_DIRS, but need to set SQLITE3_INCLUDE_DIR

### ISSUE THREAD

**Issue by MichaelEhrlichman** [owncloud/client#6278]
### Expected behaviour
Setting SQLITE3_INCLUDE_DIRS allows cmake to find sqlite3 header files.

### Actual behaviour
-- checking for module 'sqlite3'
--   package 'sqlite3' not found
CMake Error at /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:108 (message):
  Could NOT find SQLite3 (missing: SQLITE3_INCLUDE_DIRS) (Required is at
  least version "3.8.0")
Call Stack (most recent call first):
  /usr/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:315 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindSQLite3.cmake:61 (find_package_handle_standard_args)
  CMakeLists.txt:193 (find_package)

cmake complains that SQLITE3_INCLUDE_DIRS is missing, but actually SQLITE3_INCLUDE_DIR is what needs to be set.

### Steps to reproduce
Fails:
cmake -D_SQLITE3_LIBDIR=/home/myhome/local/lib -DSQLITE3_INCLUDE_DIRS=/home/myhome/local/include -DCMAKE_ILL_PREFIX=/home/myhome/owncloud -DCMAKE_LIBRARY_PATH=/home/myhome/local/lib -DQTKEYCHAIN_INCLUDE_DIR=/home/myhome/local/include -DNO_SHIBBOLETH=1 ..

Works:
cmake -D_SQLITE3_LIBDIR=/home/myhome/local/lib -DSQLITE3_INCLUDE_DIR=/home/myhome/local/include -DCMAKE_ILL_PREFIX=/home/myhome/owncloud -DCMAKE_LIBRARY_PATH=/home/myhome/local/lib -DQTKEYCHAIN_INCLUDE_DIR=/home/myhome/local/include -DNO_SHIBBOLETH=1 ..

### Client configuration
Client version:  Latest release

Operating system:  Linux Scientific Linux (Redhat)

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):  cloned git://github.com/owncloud/client.git

**Comment by ckamm** [comment]
@ogoffart From what I can tell this seems to be a confusion in `FindSQLite3.cmake` which seems to use DIR as input, and output both, and both are being used later on too. I'm assigning to you since you were reworking cmake files anyway.
