### ISSUE TITLE
Avatar requests use the new WebDAV endpoint regardless of the server version

### ISSUE THREAD

**Issue by BloodyIron** [owncloud/client#6279]
As per the notes ( https://owncloud.org/changelog/desktop-client/ ) for the Desktop Sync client 2.4, the relevant part is "Gui: Display the user server avatar (#5482)".

I changed my user avatar on the OC server, but my client does nnot appear to have picked that up anywhere. It was previously the default B letter icon.

I'm using the 2.4.0 desktop sync client in Ubuntu 17.10 from the OC client PPA/repo for 17.10.

**Comment by BloodyIron** [comment]
@ckamm I tried nicely closing it and relaunching it before making this bug report. I did not see the logo pop up anywhere. Also, I am not sure exactly where the logo should be showing up. While I did try to look in every part of the app, would you mind telling me where I should expect it to show up? :)

**Comment by guruz** [comment]
Should be like in https://owncloud.org/news/new-2-4-0-owncloud-client-oauth2-support/ at the quite bottom :)

**Comment by BloodyIron** [comment]
Yeah my client still has the basic avatar, the dark gray/black shroud of a person. It does not seem to be picking up on my avatar at all. :(

I'd rather not have to re-attach my account for this.

**Comment by SamuAlfageme** [comment]
@BloodyIron 

> I'd rather not have to re-attach my account for this. 

Indeed you shouldn't. It should behave like @ckamm mentioned in https://github.com/owncloud/client/issues/6279#issuecomment-355506021; every time you launch the client; a request should return your avatar's PNG and place it on the account tab. 

Can you run `curl --user <username>:<password> http://<server>/remote.php/dav/avatars/<user>/128.png` on your instance and tell us what it returns?

Also; which distro/desktop manager are you using? and version of the ownCloud server? Thanks a bunch!

**Comment by BloodyIron** [comment]
<?xml version="1.0" encoding="utf-8"?>
<d:error xmlns:d="DAV:" xmlns:s="http://sabredav.org/ns">
  <s:exception>Sabre\DAV\Exception\NotFound</s:exception>
  <s:message>File not found: avatars in 'root'</s:message>
</d:error>

That's the output it spits out. I ran that at the CLI on the server itself. And put it so "<user>" is typed exactly the same as "<username>" as there are capitals in a few characters.

BTW I'm on OC 9.1.4

**Comment by SamuAlfageme** [comment]
@BloodyIron this is actually a bug! Problem is the client uses the old WebDAV endpoint (https://github.com/owncloud/client/issues/4007) for **everything but the avatars**. Since the avatar API was introduced in 10.0 (https://github.com/owncloud/core/pull/26872) the client is unable to retrieve an image on that endpoint and continues displaying the default one. 

However, there is a legacy endpoint for avatars not going through this WebDAV API still in use for the WebUI. If you try:

```
$ curl --user <username>:<password> https://<server>/avatar/<user>/128
```

... it should display the binary contents of yours. We can use this one if we're connected to versions before 10.0.

Good catch! Thanks!

**Comment by ckamm** [comment]
@SamuAlfageme You mean
```
$ curl --user <username>:<password> https://<server>/index.php/avatar/<user>/128
```

**Comment by SamuAlfageme** [comment]
@ckamm I think my setup had a redirection rule that allows omitting the `index.php` part. But yes, I guess the canonical path would be fully qualified. 

Patch on `AvatarJob` also solves this for https://github.com/owncloud/client/pull/4310. Sweet!

**Comment by BloodyIron** [comment]
@ckamm @SamuAlfageme Yup, that sure looks to spit out binary to my console! Hah!

Glad to know there's value in me holding off on upgrading for a while, hehehe ;D

**Comment by BloodyIron** [comment]
Aww yeah, just got 2.4.1 and my avatar is showing! :DDD
