### ISSUE TITLE
Nextcloud client terminated on Windows 10

### ISSUE THREAD

**Issue by vasyugan** [owncloud/client#6283]
### Expected behaviour
Client should start run normally

### Actual behaviour
Crashes immediately;
![grafik](https://user-images.githubusercontent.com/3313208/34580662-0ab7a3fe-f18e-11e7-885d-2d145f8276fd.png)

### Steps to reproduce
1. Start windows 10
2. Wait until nextcloud client crashes
3. try to launch it again

### Server configuration
(not relevant here)

### Client configuration
Client version: 2.3.3

Operating system: Windows 10 pro

OS language: German

Installation path of client:

C:\Programs Files (x86)\Nextcloud

```Template for output < 10 lines```

The client generates no log before it crashes (tried with nextcloud.exe --logfile nextcloud.log)

Windows system log:

Name der fehlerhaften Anwendung: nextcloud.exe, Version: 2.3.3.1, Zeitstempel: 0x5a12a16c
Name des fehlerhaften Moduls: Qt5Core.dll, Version: 5.6.2.0, Zeitstempel: 0x3e343e27
Ausnahmecode: 0x40000015
Fehleroffset: 0x00010cae
ID des fehlerhaften Prozesses: 0x51f4
Startzeit der fehlerhaften Anwendung: 0x01d385906384f046
Pfad der fehlerhaften Anwendung: C:\Program Files (x86)\Nextcloud\nextcloud.exe
Pfad des fehlerhaften Moduls: C:\Program Files (x86)\Nextcloud\Qt5Core.dll
Berichtskennung: 8ec3c82f-44ca-48fc-98b0-4a80ef637a8a
Vollständiger Name des fehlerhaften Pakets: 
Anwendungs-ID, die relativ zum fehlerhaften Paket ist:

**Comment by vasyugan** [comment]
seems that this is a duplicate of bug #6021 
I should mention one thing: I use Nextcloud to sync the documents pictures videos and music folder across devices. So maybe there is some special protection that applies to these folders

**Comment by ckamm** [comment]
@vasyugan Please also try generating a logfile with `--logfile mylog.txt`. If that's empty or never written it's indeed likely to be similar to #6021 and a problem with how the nextcloud client packages are built.

**Comment by guruz** [comment]
@vasyugan Please try to reproduce with https://owncloud.org/download/#owncloud-desktop-client-windows

**Comment by guruz** [comment]
@vasyugan Please re-open if you can reproduce it with our client.

**Comment by vasyugan** [comment]
Will try. Thanks.

**Comment by vasyugan** [comment]
@ckamm I noted in my report that I did try to generate a logfile and that it was empty.

**Comment by vasyugan** [comment]
@ogoffart where do I find the 2.4 client?

**Comment by ckamm** [comment]
@vasyugan Try the ownloud desktop client 2.4.0 from https://owncloud.org/download/#owncloud-desktop-client-windows

**Comment by vasyugan** [comment]
@ckamm installed owncloud client 2.4 now, left the computer running overnight. This morning I am again greeted by the familiar crash alert. 

![grafik](https://user-images.githubusercontent.com/3313208/34815183-ba8707bc-f6b0-11e7-9449-9604373ba749.png)

**Comment by ckamm** [comment]
@vasyugan Thanks for the test! I thought it was crashing immediately on startup.

Can you give us a logfile (https://doc.owncloud.org/desktop/2.3/troubleshooting.html#saving-files-directly) or a stack trace of the crash?

**Comment by guruz** [comment]
@vasyugan Hi, any input?
You can also try a daily build
https://download.owncloud.com/desktop/daily/ownCloud-2.4.1.9324-daily20180212.pkg.tbz.sig
