### ISSUE TITLE
Linux: Encoding problems with non-uft8 locale

### ISSUE THREAD

**Issue by fmkaiser** [owncloud/client#6287]
### Expected behaviour
Files with special characters in the name are synchronized correctly.

### Actual behaviour
With the 2.4.0 Linux ownCloud client and locale set to LANG=C, 
objects on the server with special characters such as umlauts in the name
get downloaded with the special character replaced by a question mark (?) 
and then renamed on the server on the next sync as well.

That's especially bad if the files are in a folder shared with you by someone else...

### Steps to reproduce
1. Start ownCloud client v2.4 under Linux with
> LANG=C owncloud --logwindow
2. Create a folder with some special characters on the server
3. Watch the sync log

### Server configuration
Doesn't seem to matter much, tested with ownCloud 9.0.8 and 10.0.3.

### Client configuration
Client version: 2.4.0 - Problem did not occur with 2.3.3

Operating system: openSUSE Leap 42.3

OS language: LANG=C

Qt version used by client package (Linux only, see also Settings dialog): Qt 5.6.2

Client package: owncloud-client-2.4.0-8911.1.x86_64 (ownCloud)

### Logs
Client log - the interesting parts:
> \# filename is "täßt.txt" - apologies to all German speakers for the spelling
> 01-09 10:50:43:896 [ info sync.accessmanager ]:	6 "PROPFIND" "https://staging.sis.rzg.mpg.de/remote.php/dav/files/test-fek/umlauttest" has X-Request-ID "2576f085-78e2-49b1-a59e-bb6aa77a3063"
01-09 10:50:44:031 [ info sync.csync.updater ]:	file: umlauttest/t??t.txt, instruction: INSTRUCTION_NEW <<=
01-09 10:50:44:202 [ info sync.database ]:	Updating file record for path: "umlauttest/t\xC3\xA4\xC3\x9Ft.txt" inode: 107843249
01-09 10:50:46:381 [ info sync.propagator ]:	Starting INSTRUCTION_RENAME propagation of "umlauttest/t??t.txt" by OCC::PropagateRemoteMove(0x56329b1622f0)
01-09 10:50:46:382 [ info sync.accessmanager ]:	6 "MOVE" "https://staging.sis.rzg.mpg.de/remote.php/dav/files/test-fek/umlauttest/t??t.txt" has X-Request-ID "e6c9de7a-b8ce-4e73-8bb5-a7c0ceeb55c7"

Full log: https://gist.github.com/fmkaiser/4f18c2b75b042c1f9d728be87c2f2e07

**Comment by ckamm** [comment]
Thank you for the report. I'm attempting to reproduce it now. Possibly related to this change: 72809ef5b1aeb578976e4360ed267ac1c4d71ea6

**Comment by ckamm** [comment]
Yep, can reproduce!

**Comment by ckamm** [comment]
It's neither of the two commits mentioned.

It looks like the remote file "tö" gets inserted into the database as "t\xC3\xB6" (which is utf8 for tö, and correct), but stored to the filesystem as "t?". Then the next sync notices the local and db name are different and propagates a rename to the server.

**Comment by ckamm** [comment]
I don't yet see why this would be a new issue in 2.4: we pass the correct path to `QFile::rename`. It gets a "t\xC3\xB6" but what arrives on the filesystem is a "t?".

**Comment by ckamm** [comment]
Yes, same behavior with the 2.3 branch.

**Comment by ckamm** [comment]
I think we should ignore files that can't be encoded for the filesystem without producing invalid characters.

**Comment by ckamm** [comment]
We have tracked this down to a bug in `QTextCodec::canEncode` and will add a workaround for 2.4.1

**Comment by fmkaiser** [comment]
@ckamm Thanks for the quick response!

Maybe the local state database is rebuilt from the server in 2.4?
The question marks in the file names definitely appeared after the upgrade to 2.4 (from 2.3.3).
However the files with the umlauts have been in my workspace for a while and were likely downloaded with sync client < 2.3. The 2.3 client probably didn't touch them as long as they weren't changed on the server...

**Comment by felixboehm** [comment]
please test and reopen if there is still an issue. Thanks
