### ISSUE TITLE
Windows10 desktop client installer garbled.

### ISSUE THREAD

**Issue by devi69** [owncloud/client#6291]
### Expected behaviour
Garbled characters are generated by the installer.

### Actual behaviour
When installing desktop client, garbled characters are occurring.

### Steps to reproduce
1. Download ownCloud-2.4.0.8894-setup.exe from https://owncloud.org/download/
2. Run ownCloud-2.4.0.8894-setup.exe
3. Garbled characters occur in Windows 10 Japanese environment while executing installer.

### Client configuration
Client version: ownCloud-2.4.0.8894

Operating system: Windows10

OS language: Japanese

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

Since there is no log, I attach the capture of the installer screen.

![desktopclient1](https://user-images.githubusercontent.com/23556623/34753273-63705642-f5fa-11e7-9db2-279b99b733cd.png)
![desktopclient2](https://user-images.githubusercontent.com/23556623/34753274-66e79ee8-f5fa-11e7-956b-0879d4185ed8.png)

**Comment by SamuAlfageme** [comment]
Hey @devi69 thanks for your report! Is this the first time you see these issues on the installer? (I mean, have you tried pre-2.4 installers and those were correct?)

btw, If you wanna help us improve the translation of the client or the installer in your language you can join in https://www.transifex.com/owncloud-org/owncloud

**Comment by pomu0326** [comment]
HI @SamuAlfageme. This is my verification result.

- ownCloud-2.4.0.8894-setup.exe => NG
![image](https://user-images.githubusercontent.com/8056227/35672293-66fcc4a6-0781-11e8-917f-5b9047337a0b.png)

- ownCloud-2.3.4.8624-setup.exe => NG
![image](https://user-images.githubusercontent.com/8056227/35672312-77025d70-0781-11e8-894d-35a26f9ed823.png)

- ownCloud-2.2.4.6408-setup.exe => OK
![image](https://user-images.githubusercontent.com/8056227/35672326-82a9a174-0781-11e8-8323-3ea1782c402b.png)

**Comment by SamuAlfageme** [comment]
@pomu0326 thanks for coming back at this, I'm diffing the installer translation for Japanese between:

- https://github.com/owncloud/client/blob/2.2/admin/win/nsi/l10n/Japanese.nsh - Reported working
- https://github.com/owncloud/client/blob/2.3/admin/win/nsi/l10n/Japanese.nsh - Garbled 

```diff
diff --git a/admin/win/nsi/l10n/Japanese.nsh b/admin/win/nsi/l10n/Japanese.nsh
index 15b1030a4..52ae4c717 100644
--- a/admin/win/nsi/l10n/Japanese.nsh
+++ b/admin/win/nsi/l10n/Japanese.nsh
@@ -9,7 +9,7 @@ StrCpy $PageReinstall_NEW_Field_3 "
 StrCpy $PageReinstall_NEW_MUI_HEADER_TEXT_TITLE "ÉCÉìÉXÉgÅ[Éãçœ"
 StrCpy $PageReinstall_NEW_MUI_HEADER_TEXT_SUBTITLE "${APPLICATION_NAME} ÇÃÉCÉìÉXÉgÅ[Éãï˚ñ@ÇëIëÇ∑ÇÈ"
 StrCpy $PageReinstall_OLD_Field_1 "${APPLICATION_NAME} ÇÃç≈êVÉoÅ[ÉWÉáÉìÇ™Ç∑Ç≈Ç…ÉCÉìÉXÉgÅ[ÉãÇ≥ÇÍÇƒÇ¢Ç‹Ç∑ÅB$\nãåÉoÅ[ÉWÉáÉìÇÃÉCÉìÉXÉgÅ[ÉãÇÕÇ®ä©ÇﬂÇµÇ‹ÇπÇÒÅBãåÉoÅ[ÉWÉáÉìÇÃÉCÉìÉXÉgÅ[ÉãÇ™ñ{ìñÇ…ïKóvÇ»èÍçáÇÕÅAÇ‹Ç∏ç≈êVÉoÅ[ÉWÉáÉìÇÉAÉìÉCÉìÉXÉgÅ[ÉãÇµÇƒÇ©ÇÁÅAãåÉoÅ[ÉWÉáÉìÇÉCÉìÉXÉgÅ[ÉãÇµÇƒÇ≠ÇæÇ≥Ç¢ÅB$\nÉIÉyÉåÅ[ÉVÉáÉìÇëIëÇµÅAéüÇ÷ÇÉNÉäÉbÉNÇ∑ÇÈÅB"
-StrCpy $PageReinstall_SAME_Field_1 "${APPLICATION_NAME} ÇÕÅA${VERSION} Ç™ä˘Ç…ÉCÉìÉXÉgÅ[ÉãÇ≥ÇÍÇƒÇ¢Ç‹Ç∑ÅB$\n$\né¿çsÇµÇΩÇ¢ëÄçÏÇëIëÇµÅAéüÇ÷ÇÉNÉäÉbÉNÇ∑ÇÈÅB"
+StrCpy $PageReinstall_SAME_Field_1 "${APPLICATION_NAME} ÇÕÅA${VERSION} Ç™Ç∑Ç≈Ç…ÉCÉìÉXÉgÅ[ÉãÇ≥ÇÍÇƒÇ¢Ç‹Ç∑ÅB$\n$\né¿çsÇµÇΩÇ¢ëÄçÏÇëIëÇµÇƒÅAéüÇ÷ÇÉNÉäÉbÉNÇµÇƒÇ≠ÇæÇ≥Ç¢ÅB"
 StrCpy $PageReinstall_SAME_Field_2 "í«â¡/çƒÉCÉìÉXÉgÅ[ÉãÉRÉìÉ|Å[ÉlÉìÉg"
 StrCpy $PageReinstall_SAME_Field_3 "${APPLICATION_NAME} ÇÉAÉìÉCÉìÉXÉgÅ[Éã"
 StrCpy $UNINSTALLER_APPDATA_TITLE "${APPLICATION_NAME} ÇÉAÉìÉCÉìÉXÉgÅ[Éã"
```

This suggests it's rather a file encoding issue - however, `file -I admin/win/nsi/l10n/Japanese.nsh` outputs the same encoding in both tags (`text/plain; charset=unknown-8bit`).

I'm inclined to say it's rather an issue with the NSIS version we used to generate the installers. I'll dig up a bit, but the issue overall will be solved once we release 2.5 which replaces NSIS installers for MSI. Would you be up to join our translations team in https://www.transifex.com/owncloud-org for it? 

cc/ @dschmidt  let's talk about migrating existing translations for the MSI installers (consolidate the MSI-experiment orga) sometime soon.

**Comment by guruz** [comment]
Related (or duplicate?): https://github.com/owncloud/client/issues/4960

**Comment by TheOneRing** [comment]
We are using an msi installer since version 2.5
