### ISSUE TITLE
Small text issue

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#6303]
### Expected behaviour
Text proper shown

### Actual behaviour
Missing blank, see screenshot
![image](https://user-images.githubusercontent.com/3321281/34870465-6f435c58-f78a-11e7-988d-e750e9f3a477.png)

### Steps to reproduce
1. Rightclick on file, owncloud/share
2. Window openes, look at the bottom

ownCloud version: 10.0.4

### Client configuration
Client version: 2.4.0 (build 8894)
Operating system: W10x64
OS language: German

**Comment by ogoffart** [comment]
That was a translation issue.  

I fixed it by commiting directly the .ts file, i hope transifex will pick it up.

**Comment by mmattel** [comment]
@ogoffart 
Q: looking on Transifex: what does the ``&`` mean when you translate eg:
```&Choose... Aus&wählen…```
Why is it in the middle of the German translation and not at the beginning as on Choose?
I understand ``1%`` as a placeholder for a variable coming from the code but ``&`` ?

**Comment by ogoffart** [comment]
@mmattel it adds at little underline on the label, and let you use the interface with the keyboard by using ALT+C  (or Alt+W)  https://stackoverflow.com/questions/16666060/qt-why-add-to-the-string

**Comment by mmattel** [comment]
@ogoffart 
Transifex did not pick that up because this will always be overwritten from Transifex down to the code.
Only the Englisch source text will be taken and this one needs to be translated via Transifex...
I am a registered translator on Transifex 😄 
Did a quick review on the existing text elements in Locale: de_DE and some corrections.
I also corrected the above text. Changes will be propagated down to the code tomorrow automatically.
The next client build will contain it.

Let´s check tomorrow. If present we can close it.

**Comment by mmattel** [comment]
@ogoffart 
Q: Looking into the translation files today, the last update from transifex was 11 days ago...?
Doesńt it do the transfer automatically/daily?

**Comment by ogoffart** [comment]
@mmattel  transifex updates happens in the 2.4 branch.

**Comment by ogoffart** [comment]
Anyway, closing this issue here, please see in transifex.
