### ISSUE TITLE
Owncloud Client keeps asking for password on reboot

### ISSUE THREAD

**Issue by msedek** [owncloud/client#6304]
im running my owncloud server ubuntu on the latest version and if I install the owncloud client from the ubuntu repo it says that it is not compatible with my server..

so i have to install the owncloud client from the official site.. Im running ubuntu GNOME 17.10 on my workstation and seahorse it running perfectly with everything but no matter what the owncloud client keeps asking for password on reboot.. I was following a thread with the issue happening from 2014 and was closed with no solution so .. I have to re open ..

**Comment by michaelstingl** [comment]
Maybe related? https://github.com/owncloud/client/issues/5703

Do you have keyring/keychain/key… stuff installed?

Could you post the exact steps to reproduce? Could post the exact error message you've got?

**Comment by msedek** [comment]
my keyring is the default for gnome, it is installed

![ownclouderror](https://user-images.githubusercontent.com/2139697/34907091-369a07fe-f847-11e7-901d-a87f17760f66.png)

the error is the same from the closed and unresolved thread.. telling me about some kde dependencies, I dont have kde, I dont like kde and will never install kde.. dont know why the app has  kde dependencies, at least on gnome DE, I have another machine with XFCE and the same version of owncloud and this does not happen, does not happen on UNITY UBUNTU 16.04, but happens on ubuntu GNOME 17


the exact steps are, install owncloud from www.owncloud.org/download
linux steps ubuntu

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_17.10/ /' > /etc/apt/sources.list.d/owncloud-client.list"
wget -nv https://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_17.10/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
sudo apt-get install owncloud-client

run the client, connect to my server and all good up to here.. but when you restart the error in the screenshot starts..

**Comment by michaelstingl** [comment]
Hm, strange. I couldn't reproduce. I installed with default options from `ubuntu-17.10.1-desktop-amd64.iso` in a VM. GNOME should be default in ubuntu-17.10?

```
michaelstingl@michaelstingl-virtual-machine:~$ owncloudcmd --version
ownCloud version 2.4.0 (build 8911)
Git revision 9a1f736e306f135628e77bca5c1edeed8b1f3736
Using Qt 5.6.2, built against Qt 5.6.2
Using 'OpenSSL 1.0.2g  1 Mar 2016'
michaelstingl@michaelstingl-virtual-machine:~$ history
…
    7  wget -nv https://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_17.10/Release.key -O Release.key
    8  sudo apt-key add - < Release.key
    9  sudo apt-get update
   10  sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_17.10/ /' > /etc/apt/sources.list.d/owncloud-client.list"
   11  sudo apt-get update
   12  sudo apt-get install owncloud-client
   13  owncloudcmd --version
   14  history
```

Then I configured the ownCloud account, synced, and performed a restart. ownCloud client connected without problems after reboot.

**Comment by michaelstingl** [comment]
@jnweiger @ogoffart any idea why `kwalletd` is requested (in some cases) by `qtkeychain` if `gnome-keyring` is present? Bug in `qtkeychain`?

**Comment by msedek** [comment]
yes gnome is default on ununtu 17, canocical got rid of unity.. did you set password to login?

**Comment by michaelstingl** [comment]
Yes, I have to enter password when I login to the graphical system.
		
		

		--Michael Stingl mstingl@owncloud.comhttps://owncloud.com/
Your Data, Your Cloud, Your Way!
ownCloud GmbH - GF: Tobias Gerlinger, Holger Dyroff, Harald WeimerLeipziger Platz 21, 90491 Nürnberg, HRB 28050 (AG Nürnberg)
	




On Sat, Jan 13, 2018 at 6:34 PM +0100, "Miguel Sedek" <notifications@github.com> wrote:












yes gnome is default on ununtu 17, canocical got rid of unity.. did you set password to login?

**Comment by msedek** [comment]
I hope someone could help with the issue , I appreciate the time you took to do the test and provide the feedback. this issue is really annoying.. I have been searching and investigating about it but there is not a whole bunch of information on the matter out there

**Comment by msedek** [comment]
sorry missclicked on close issue, didnt ment to

**Comment by msedek** [comment]
ok I have solved the issue for myself... you guys have to correct the installation instructions 

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_17.10/ /' > /etc/apt/sources.list.d/owncloud-client.list"
wget -nv https://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_17.10/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update
sudo apt-get install owncloud-client

in the last line "sudo apt-get install owncloud-client" if you press TAB it will give you several options of the clients to install AND in the list there is owncloud-client-nautilus  .. which is the one you HAVE you install on UBUNTU since IT IS GNOME and not KDE or anything else...  so update your installation instruction for every distro acordingly

**Comment by michaelstingl** [comment]
The bad thing, maintainers of a project on http://download.opensuse.org/ have no control about the instructions on this page (know issue for a long time) /cc @jnweiger 

The thing that can be improved, is the ownCloud documentation. (https://doc.owncloud.org)

**Comment by ernesst** [comment]
I figured out that on ubuntu 16.04 + gnome-shell, on the start up there is /usr/bin/gnome-keyring-daemon --start --components=ssh.

I figure out that removing --start --components=ssh was allowing to save the password, visible in the seahorse app.

**Comment by jnweiger** [comment]
We can update the installation instructions when we switch to self hosted repositories. But it is still unclear to me how a user should correctly decide which of the plugins is needed. 

It is surprising that adding the owncloud-client-nautilus plugin fixes a wallet issue. I am on MINT, a Ubuntu derivative, and have no such issues.
