### ISSUE TITLE
[Windows 7] UI Glitch: Sync controls on wizard collapse upon completion 

### ISSUE THREAD

**Issue by wqqbanana** [owncloud/client#6306]
Hello, I use the owncloud client to connect to the server is found, enter the user name and password, use the default local synchronization path, click the connect button there will be prompted the statement overlap, if you manually change the synchronization path, the display is normal

### Expected behaviour
Tell us what should happen
The second sentence will not move up, the interface statement shows normal.
Like the interface before clicking the Connect button:
![normal](https://user-images.githubusercontent.com/35329370/34976927-ab7b33f2-fad3-11e7-8434-cff2ad5c4e19.png)

### Actual behaviour
Tell us what happens instead
Click the link button, the two sentences overlap:
![issue](https://user-images.githubusercontent.com/35329370/34977063-1e22c26c-fad4-11e7-89a9-9763488f4069.png)

### client configuration
Operating system:
windows7

ownCloud version:
2.4.0

**Comment by SamuAlfageme** [comment]
Hey @wqqbanana thanks for reporting! I've seen this one when finishing up with the account wizard.  

>  Click the link button 

You mean the "Connect..." button right? The one that closes down the wizard.  It's a UI glitch but just displayed for a couple of seconds at most, no?

**Comment by wqqbanana** [comment]
Hi @SamuAlfageme   Yes, there are only a few seconds, but if you choose an empty folder as the local sync file path, the interface is displayed as normal.

**Comment by TheOneRing** [comment]
Supposed to be fixed.
