### ISSUE TITLE
Conflict between file and folder is not handled

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6312]
Basic case:
* Add a file "foo" locally
* Add a folder "foo" remotely, with some files inside
* Start the sync

The sync will not complete successfully. The same happens if the folder is local and the file is remote. Or if what used to be a file becomes a directory on one end while the file changes on the other end.

What should happen is the usual conflict behavior: The local item gets renamed and the remote item gets downloaded.

I have already started to work on this issue.

**Comment by SamuAlfageme** [comment]
Hmm... while I'm testing this /me wonders if this would be a nice way to solve cash-clashes on the client (things like https://github.com/owncloud/client/issues/5870#issuecomment-347564603 should get better with this). 

Using conflicts could be a way (not sure if good or not) to solve part of the neverending story: https://github.com/owncloud/client/issues/1348. What'cha think @ckamm?

**Comment by ckamm** [comment]
@SamuAlfageme Making case clashes conflicts creates the following problem:

* Linux user: uploads foo.txt and Foo.txt. Syncs and updates them, all is good.
* Windows user starts syncing, gets foo.txt and Foo_case_clash_with_foo.txt. That doesn't make sense, foo and Foo are entirely unrelated.

**Comment by SamuAlfageme** [comment]
Fixed 🎉  - great catch @ckamm!
