### ISSUE TITLE
misleading "conflict file downloaded" activity message 

### ISSUE THREAD

**Issue by moscicki** [owncloud/client#6316]
Sync client (2.3.3 OSX) reported conflict files but it did not create them:

![image](https://user-images.githubusercontent.com/621965/35109029-7d0f02c0-fc75-11e7-9f9d-2dabe0d20a29.png)

Why is that? AFAIK there is a content check of the temporarily downloaded conflict file and if it is the same no action is taken -- is this correct? In this case the message should not be there because it is confusing.

Or is this some other abnormal condition?

**Comment by moscicki** [comment]
Actually looking into server logs do not see any GET for these files. So this looks like another wierd error condition.

**Comment by ogoffart** [comment]
Version 2.3 should always have downloaded.
Version 2.4 does more check and avoid downloading if the file hashes are the same. But still, we should not see this message in that case.

Do you have any ways to reproduce the problem?

**Comment by ckamm** [comment]
I can reproduce this. All items with a `CONFLICT` instruction get that message, even if they end up not downloading the remote file, or downloading it and realizing both files are identical.

**Comment by guruz** [comment]
Maybe @moscicki can test with a daily build?

**Comment by SamuAlfageme** [comment]
All my tests came up green after 2.4.1. All conflicts solved on hash comparison are no longer displayed on the issues tab. Very nice & clean code:

https://github.com/owncloud/client/blob/5f54a601083d2941ba01d81d26bb541f602bbbf2/src/libsync/syncfileitem.h#L190-L206

Great work @ckamm! 🙌
