### ISSUE TITLE
Conflict file names should include user name if uploaded

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6325]
In master the client can optionally upload conflict files. In this case it's easy for there to be several conflict files uploaded to the server by different users. In this situation it is very useful if it's immediately obvious which user created which conflict file. This should become part of the conflict file name:
```
foo-conflict_20180115-1412.txt
foo-conflict_20180112-1100.txt
vs
foo-conflict_frank_20180115-1412.txt
foo-conflict_greta_20180112-1100.txt
```

**Comment by ckamm** [comment]
@PVince81 @DeepDiver1975 I'm planning to use the dav username, that is the string used in `/remote.php/dav/files/<user>/` inside generated conflict files. Would there be a better choice?

**Comment by SamuAlfageme** [comment]
@ckamm I think that'd result in a UUID on LDAP setups (for the same reason we still have troubles with things like https://github.com/owncloud/oauth2/issues/109#issuecomment-357663934) 😕

**Comment by ckamm** [comment]
@SamuAlfageme Great catch, so we need to be able to determine the "display user" first!

**Comment by SamuAlfageme** [comment]
@ckamm since it's gonna be used for a filename (whitespace-safe) you can get the current logged in display name from the [User Provisioning API](https://doc.owncloud.org/server/10.0/admin_manual/configuration/user/user_provisioning_api.html) i.e.`/ocs/v1.php/cloud/user`

**Comment by ckamm** [comment]
@SamuAlfageme I had edited my comment a bit. The display name can be long and have spaces though...

**Comment by hodyroff** [comment]
Hm, really? This lands in the versions, right? The versions view should have the ability to list the user ... not sure changing the filename is a great idea ... think about long file names which will go out of bound quickly ...

**Comment by ckamm** [comment]
@hodyroff No, as yet this does not interact with the server's versions functionality. See https://github.com/owncloud/platform/issues/159 for a detailed description of the conflict-uploading feature.

**Comment by PVince81** [comment]
> The versions view should have the ability to list the user 

The server doesn't store the user id of who modified a file. Would require a new column in oc_filecache or better: move the versions out of oc_filecache into a separate table where we can store more information. See https://github.com/owncloud/core/issues/2263

**Comment by guruz** [comment]
> Great catch, so we need to determine the "display user" first! 

FYI we do this already for the toolbar. https://github.com/owncloud/client/blob/ed5385faa36cd21ac9645f896d13fde8bd53bd2e/src/libsync/connectionvalidator.cpp#L294

>  It could have characters that aren't valid in filenames.

mhm.

**Comment by ckamm** [comment]
So, what do we actually do? The user `id` can be a uuid, and the display name can be verbose and unsuitable for filenames. Names can have all shapes and forms, so extracting something from the display name is prone to break in odd ways. The local host name wouldn't look good.

I'd start out with a sanitized display name.

**Comment by SamuAlfageme** [comment]
Done and documented on https://doc.owncloud.org/desktop/2.5/conflicts.html - great job 👍

**Comment by jnweiger** [comment]
### linux mint tara
testpilotcloud version 2.5.0daily20180808 (build 10016)

OK 
 works nicely when enabled.


BAD
 The username should always be there. See example in #4557

BAD
 The feature should be enabled per default :-)

**Comment by guruz** [comment]
> The username should always be there, not only when enabled. 

agreed.
