### ISSUE TITLE
Size-aware sorting on Sync Protocol tab

### ISSUE THREAD

**Issue by cresse2200** [owncloud/client#6326]
When I upload multiple files and want to sort them in the synchronization protocol, it seems to sort as a string. For example it the size unit (KB, MB, GB) into account last. So a 2MB file is sorted in between a 1 KB and 3 KB file. 

I would expect the sort function to sort after the actual file size, and not the number.

Using version build from GIT-Revision 9a1f73 at Dec 21 2017, 17:00:11      Version 2.4.0 (build 8894)
OS: Win7 64bit
Chosen Language: German

**Comment by SamuAlfageme** [comment]
Hey @cresse2200, great catch! You're absolutely right; we'll fix this.

**Comment by SamuAlfageme** [comment]
Tried w/ today's daily (ownCloud-2.5.0.9402) and can say it's fixed  🎉 

@cresse2200 care to give it a try? -> http://download.owncloud.com/desktop/daily You can install the testpilot edition of the client to preserve your stable version while testing 2.5 out. Closing up here!

**Comment by cresse2200** [comment]
I do not have access to my cloud in the next days, but will test as soon as possible.

**Comment by cresse2200** [comment]
Is working correctly, thanks

**Comment by jnweiger** [comment]
OK looks great after clicking on sort by size

![grafik](https://user-images.githubusercontent.com/1108546/43951245-f295c322-9c92-11e8-8301-c5750d831db7.png)
