### ISSUE TITLE
Server replied "423 Locked" to "DELETE http....

### ISSUE THREAD

**Issue by julesmoretti** [owncloud/client#6331]
### Expected behaviour
File that I deleted locally to also delete on my server on my Drobo 5D

### Actual behaviour
I get several lines with:
`director/to/file.ext: Server replied "423 Locked" to "DELETE https://username.mydrobo.com/remote.php...`

### Steps to reproduce
1. Installed Owncloud on mac version 2.4.0
2. Sync to Drobo 5N that has MyDrobo and DroboAccess installed
3. Delete some file from folder

### Server configuration
Operating system:
Not sure Drobo 5N version 2 Probably DroboAccess

Web server: Apache

Database: MySQL

PHP version: not sure

ownCloud version: 2.4.0

Storage backend (external storage): Drobo 5N

### Client configuration
Client version: 2.4.0

Operating system: Mac osX 10.13.2

OS language: Mac

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Could not find those within the mac client nor drobo sorry. :/

**Comment by michaelstingl** [comment]
@julesmoretti Could you check the output of `https://username.mydrobo.com/status.php` ? Does it show version information?

**Comment by julesmoretti** [comment]
@michaelstingl here you go:
`{"installed":true,"maintenance":false,"version":"9.1.4.2","versionstring":"9.1.4","edition":""}`

**Comment by SamuAlfageme** [comment]
@julesmoretti for the locking issue, refer to https://central.owncloud.org/t/file-is-locked-how-to-unlock/985 - I guess you should have access to admin's interface on your setup (to manually run cronjobs).

**Comment by julesmoretti** [comment]
@SamuAlfageme that did the trick! For my drobo, went into MySql and cleared that database table :)
