### ISSUE TITLE
[2.4.0] Client required to be authorized to sync at every start

### ISSUE THREAD

**Issue by abeljouve** [owncloud/client#6335]
Hello,
My problem is that ownCloud ask me to authorize it to sync at every start. I haven't this problem with my other computer. I dont know if it's a mistake from me or a bug.
Thanks to helping me.

### Expected behaviour

Normally, when i start my computer the ownCloud client start the sync with my server whithout doing anything.

### Actual behaviour

When my computer start the ownCloud client start and open a web page on the ownCloud server that saying me this: 
The application "Desktop Client" is requesting access to your account. To authorize it, please log in first.
And with the login form, i type my credentials and i click on the authorize button and my client start the sync.

### Server configuration
Operating system: Debian 9.1
Web server: Apache 2.4.29
Database: MariaDB 10.1.26
PHP version: 7.1.13-1
ownCloud version: 10.0.3 (stable)

### Client configuration
Client version: Version 2.4.0 (build 8894)
Operating system: Windows 10 Pro x64
OS language: French
Installation path of client: C:\Program Files (x86)\ownCloud

**Comment by ogoffart** [comment]
This uses the new oauth2 authentication.  But the client should remember the oauth2 refresh_token and use that to re-authenticate at restart.
Can you check the client or server log, and see if the client does a request to `index.php/apps/oauth2/api/v1/token?grant_type=refresh_token&...`?  And what does the server answer?

**Comment by ogoffart** [comment]
So there is no call to `index.php/apps/oauth2/api/v1/token`, that's wierd.

Normaly the token should be stored in the window credentials store.

Maybe running owncloud with  --logwindow --logdebug  will show some warning as to why this did not work.

**Comment by abeljouve** [comment]
I noticed that if I restart ownCloud it does not ask me anything, my problem is that when starting the computer, it's pretty strange. And for the client's logs, they are heavy, QT Gesture records the events of the mouse.

**Comment by SamuAlfageme** [comment]
@abeljouve can you check if, after you restart your computer there's an ownCloud entry on [Windows Credential Store](https://support.microsoft.com/en-us/help/4026814/windows-accessing-credential-manager) - to rule out Windows erasing it due to OS settings or something.

**Comment by abeljouve** [comment]
Yes there's an entry on the Credential Store. But there ownCloud has successfully sync with the server, so i think, sometime or after a while that the entry is remove from the Credential Store probably by windows.

**Comment by guruz** [comment]
@abeljouve Which exact version of the server and the oauth2 app are you using?

**Comment by abeljouve** [comment]
@guruz The owncloud server version is 10.0.3 (stable), and for the Oauth2 I don't know how get it. But my problem is resolved I think, I have delete the ownCloud entry on the Credential Store and restart my ownCloud client and after a week of use, i have encounter no problem.

**Comment by guruz** [comment]
@abeljouve Happy to hear it works now, but we should still try to track this down so we can fix it for others.
Are you sure you or another administrator of your server did not install https://marketplace.owncloud.com/apps/oauth2 ? Because otherwise you should not get the browser message:
> The application "Desktop Client" is requesting access to your account. To authorize it, please log in first.

@ckamm @ogoffart Is there some case where it would sometimes use OAuth2 and sometimes fall back to normal basic auth?
@ckamm something fishy in your migration code for the credential store key-names?

**Comment by guruz** [comment]
@abeljouve ping :)

**Comment by abeljouve** [comment]
Sorry for the wait, I am the owner of this server and i have verify Oauth2 is not installed.

**Comment by ckamm** [comment]
@guruz I've looked at the credential store migration again but don't see any problem. To me the mysterious thing is that @abeljouve gets oauth-like behavior without having the OAuth2 plugin installed on the server. This should **only** happen if the `WWW-Authenticate` reply contains `Bearer`.

@abeljouve Could you try this?
```
$ curl -v -k https://your-server-url/remote.php/webdav/ 2>&1 | grep WWW-Auth
```

**Comment by abeljouve** [comment]
The command return:
`< WWW-Authenticate: Basic realm="ownCloud"`

**Comment by ckamm** [comment]
@abeljouve Thanks for testing! And when you press "Sign out" and then "Sign in" the browser window comes up, asking you to log into your ownCloud instance?

**Comment by abeljouve** [comment]
@ckamm When i sign out and sign in, owncloud ask me to type my account password or create a new app password from the web interface.

**Comment by ckamm** [comment]
@abeljouve Okay, then the behavior is correct now. (In your initial report you said that a browser window was openend by the client when your computer started, asking you to authorize the client application. )

**Comment by abeljouve** [comment]
Oui, mais mon problème c'est résolu de lui même, je ne sais pas comment.

**Comment by ckamm** [comment]
@abeljouve Yes, thank you again for your tests and feedback! 

I'll see whether I can find a way in which the client could hit the oauth codepath without the plugin being installed and will otherwise close this issue.

**Comment by abeljouve** [comment]
Ok thanks for your help and i hope that this problem will not come again.

**Comment by ckamm** [comment]
I double checked the code of master and v2.4.0 again and don't see a way in which this could happen. The url that shows up in your log is from `OAuth::authorizationLink()` which is only actively used in `OAuth::openBrowser()` which is only called from the wizard and from the http auth type detection. And the auth type detection will only call it if the Authenticate header contains `bearer`.

It's a mystery to me.
