### ISSUE TITLE
Feature Request: Retrieve password automatically without gnome-keyring

### ISSUE THREAD

**Issue by doronbehar** [owncloud/client#6340]
Very much related to #6304 , since I don't use gnome and I would like to configure a different automatic retrieval of my app-password, perhaps using a `passwordeval` variable of some sort that will invoke `[pass](https://www.passwordstore.org/) nextcloud-app-desktop-client`. It is a common practice in many command line programs:
- `msmtp`: https://wiki.archlinux.org/index.php/msmtp#GnuPG
- `mutt`: https://unix.stackexchange.com/a/20572
- `vdirsyncer`: http://vdirsyncer.pimutils.org/en/stable/keyring.html#command
- `toxic` (tox client): https://github.com/JFreegman/toxic/issues/434

**Comment by hodyroff** [comment]
Is this not possible with the ownCloud command line client?
For desktop client does oAuth2 not work for you - why? That will allow you to not worry about password at all ...

**Comment by doronbehar** [comment]
Hmm, oAuth2 isn't related to app passwords in any way right? I created an app password for this client but it keeps ask it every startup as well.

**Comment by guruz** [comment]
@doronbehar This needs to be implemented in https://github.com/frankosterfeld/qtkeychain which we are using.

@hodyroff OAuth2 secrets need to be stored somewhere too, so we store it via keychain :)

**Comment by hodyroff** [comment]
Makes sense, so something needs to be stored locally and I understand now that this request is about storing this something in more options then we provide today. Perfect. Lets hope for upstream = KDE ;)

**Comment by doronbehar** [comment]
Isn't it possible to implement this feature here and not only in upstream? It could be great to have a string configuration option in the GUI that will define a shell command that should return the password.

This is an option the programs I listed in [my first comment](https://github.com/owncloud/client/issues/6340#issue-293258828) offer. Usually, these configuration options are used when the user encrypts his passwords in PGP encrypted files with GnuPG and he decrypts them with something like: `gpg --decrypt mypassword.gpg`

**Comment by ogoffart** [comment]
QtKeychain can have local unencrypted fallback, but we disabled it.

Arguably, the oauth2 referesh_token is much less sensitive. Maybe we can re-enable the insecure fallback when using oauth2.

**Comment by michaelstingl** [comment]
@settermjd thoughts?

**Comment by guruz** [comment]
@ogoffart What's the unencrypted fallback? Is that in some .ini files? Then how would @doronbehar get the OAuth2 token?
I still think it's better to improve on QtKeychain somehow..

**Comment by guruz** [comment]
With ```owncloudcmd``` we support ```netrc```
https://doc.owncloud.org/desktop/2.4/advancedusage.html

**Comment by ogoffart** [comment]
@guruz   i'm talking about `QKeychain::Job::setInsecureFallback` which we currently set to false.  https://code.woboq.org/owncloud/client/src/libsync/creds/httpcredentials.cpp.html#199   We could set it to true for the oauth2 refresh_token.  It means that the token would be written in the owncloud config file.

**Comment by guruz** [comment]
@ogoffart OK now I understand, the login method would stay the same. Hm. But is OAuth2 token really more OK to lose? :-/ It's not a password true, but if I have the OAuth2 token I can still impersonate when I steal it?

**Comment by michaelstingl** [comment]
@guruz @ogoffart We don't have scopes for OAuth2 yet. Maybe OAuth2 tokens are too powerful at the moment.

**Comment by ogoffart** [comment]
So in conclusion, we won't write the password, or oauth2 token in the settings in plain text. We will only allow what QtKeychain provide, but not its insecure fallback.

Should we then close this issue?

**Comment by olberger** [comment]
I'm not exactly sure, but it seems that libgnome-keyring0 is deprecated, reading https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892359 and a suggestion is to replace it by libsecret.

Maybe this is relevant to owncloud-client, at least for its presence in future Debian releases...

**Comment by guruz** [comment]
Whatever needed for other credential storage needs to be done in  https://github.com/frankosterfeld/qtkeychain .. therefore closing here.

> I'm not exactly sure, but it seems that libgnome-keyring0 is deprecated, reading https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=892359 and a suggestion is to replace it by libsecret.

Recent QtKeyChain versions support libsecret :-)
