### ISSUE TITLE
[Windows 7] sync after choosing keep files for new user freezes the program

### ISSUE THREAD

**Issue by cresse2200** [owncloud/client#6341]
Running latest version, at least the update function doesn't tell me off an existing newer version, on Windows 7 64bit.

I changed my owncloud server from http to https, because I think about opening it to the internet. As of now I'm still running locally. Because I couldn't find an option to change the settings I deleted my user and recreated it using https instead of http. (Only noticed later that it migth have been possible to just change the configuration file) Because the files on my computer and in the cloud are the same and I wanted to prevent uploading/downloading everything again I choose the same folder again, and told the client to keep all the files. Afterwards it started to check the files for changes. Then it checks about 2GB/500-700files and notices they are the same version. Then it tells me that there is no connection to the server, because of a timeout. And then the program freezes and I can't do anything anymore.
Have done this 3 times now (restarting client program), each time the initial scan is done, but the total of files to sync goes done each time.

### Expected behaviour
As I'm not sure if the connection termination is due to my owncloud settings, the thing i would expect the client to do: 
retry to establish a connection again 

If the lost connection is caused by the client program, then to not lose connection. (Will post a part of the apache server logs, maybe someone can see on which side the connection termination is issued)

### Actual behaviour
the program freezes

### Steps to reproduce
Only done it once
1. Delete user account in client settings
2. Recreate this user
3. tell it to keep the files already in the folder

Now I can reproduce it with restarting owncloud client

### Logs
access.log:

>192.168.0.10 - chris [31/Jan/2018:19:44:59 +0000] "PROPFIND /owncloud/remote.php/dav/files/chris/ HTTP/1.1" 207 1637 "-" "Mozilla/5.0 (Windows) mirall/2.4.0 (build 8894)"
>192.168.0.10 - chris [31/Jan/2018:19:45:06 +0000] "PROPFIND /owncloud/remote.php/dav/files/chris/ >HTTP/1.1" 207 1533 "-" "Mozilla/5.0 (Windows) mirall/2.4.0 (build 8894)"
192.168.0.10 - chris [31/Jan/2018:19:45:28 +0000] "PROPFIND /owncloud/remote.php/dav/files/chris/ >HTTP/1.1" 207 1495 "-" "Mozilla/5.0 (Windows) mirall/2.4.0 (build 8894)"
192.168.0.10 - chris [31/Jan/2018:19:45:47 +0000] "PROPFIND /owncloud/remote.php/dav/files/chris/ >HTTP/1.1" 207 1533 "-" "Mozilla/5.0 (Windows) mirall/2.4.0 (build 8894)"
192.168.0.10 - chris [31/Jan/2018:19:46:02 +0000] "PROPFIND /owncloud/remote.php/dav/files/chris/ >HTTP/1.1" 207 1495 "-" "Mozilla/5.0 (Windows) mirall/2.4.0 (build 8894)"
>192.168.0.10 - - [31/Jan/2018:19:46:55 +0000] "-" 408 142 "-" "-"
>192.168.0.10 - - [31/Jan/2018:19:46:55 +0000] "-" 408 142 "-" "-"
>192.168.0.10 - - [31/Jan/2018:19:47:29 +0000] "-" 408 1610 "-" "-"
>192.168.0.10 - chris [31/Jan/2018:19:47:21 +0000] "PROPFIND /owncloud/remote.php/dav/files/chris/ >HTTP/1.1" 207 3268 "-" "Mozilla/5.0 (Windows) mirall/2.4.0 (build 8894)"

In this time I haven't accessed the owncloud via my browser, and I set the client to access owncloud using https

owncloudsync.log:

>#=#=#=# Syncrun started 2018-01-31T03:19:32Z
>#=#=#=#=# Propagation starts 2018-01-31T04:50:41Z (last step: 5468399 msec, total: 5468399 msec)
>#=#=#=# Syncrun started 2018-01-31T05:00:19Z
>#=#=#=#=# Propagation starts 2018-01-31T06:31:46Z (last step: 5487249 msec, total: 5487249 msec)
>#=#=#=# Syncrun started 2018-01-31T12:35:32Z
>#=#=#=#=# Propagation starts 2018-01-31T14:07:59Z (last step: 5545865 msec, total: 5545865 msec)
>#=#=#=# Syncrun started 2018-01-31T14:27:14Z
>#=#=#=#=# Propagation starts 2018-01-31T15:57:05Z (last step: 5391112 msec, total: 5391112 msec)
>#=#=#=# Syncrun started 2018-01-31T16:29:23Z
>#=#=#=#=# Propagation starts 2018-01-31T17:59:15Z (last step: 5391902 msec, total: 5391902 msec)
>#=#=#=# Syncrun started 2018-01-31T18:14:01Z
>#=#=#=#=# Propagation starts 2018-01-31T19:43:29Z (last step: 5367592 msec, total: 5367592 msec)
>#=#=#=# Syncrun started 2018-01-31T20:35:27Z

just to compare the logs better, there is 1 hour time difference between both computers due to different timezones

**Comment by ckamm** [comment]
@cresse2200 Thanks for your report! The server log shows 408 (request timeout) errors. Could you start your client with `--logfile mylog.txt --logdebug` to generate a detailed logfile that would help show what happens from the client's point of view? If you're not comfortable uploading the file (it has the server name, file names, etc) you could send it to me: mail at ckamm de.

**Comment by cresse2200** [comment]
Hi,

if it interrupts again, I will try that. I started it again (I think for the 5th time) and now it is running without a problem and nearly 85% done, so I would rather not terminate it. 

The only difference between this try and the last was, that I deleted a bunch (1500) of empty files, that were created by accident some time ago. I deleted those files via the browser in the cloud and my local copy of those files.

**Comment by cresse2200** [comment]
If my current synchronization is finished, I will try if I can recreate this with a different user and smaller testcase. Then it will be no Problem to upload the logs as well.

**Comment by cresse2200** [comment]
that might have been optimistic, started it with the given command. If it terminates again I will mail you the logfile/end of it depending on size.

**Comment by cresse2200** [comment]
it is done without another freeze, so I will try to reproduce the error in the next days, and then post the logs.

**Comment by ogoffart** [comment]
Could also be the same as issue #6272
Would be worth to try the 2.4.1 nightly build and see if this is not already fixed.

**Comment by guruz** [comment]
@cresse2200 Could you please try https://download.owncloud.com/desktop/daily/ownCloud-2.5.0.66-daily20180205-setup.exe and report back?

**Comment by cresse2200** [comment]
Hi,

I can try, but as I'm unable so far to reproduce the problem, that doesn't tell us that much. But if a similar problem is already fixed and my problem doesn't happen anymore, I'm going to close this and if the problem appears again and 2.4.1 doesn't help then either, Im going to open a new Issue.

Thanks for the help.
