### ISSUE TITLE
Client Freezes when syncing

### ISSUE THREAD

**Issue by TheAppService** [owncloud/client#6344]
Hello alltogether,

unfortunateley after the upgrade to version 2.4.0 my Client freezes every time during the syncing progress. No matter whether it's just checking for changes and does not find new files( See video attached) But also at synchronization, including timeouts et cetera, The whole Thread seems to pause.
My Server Version is ownCloud 9.1.6 (stable)
My Client Version ( 2.4.0. Build 8894)
The only strange lines I could find in the Log were: 
https://gist.github.com/TheAppService/aa71df61eeb3dff5763a686b69f43ad5
https://youtu.be/b6EfYk-e9uo

**Comment by SamuAlfageme** [comment]
Hey @TheAppService! Thanks for your report - this might be a duplicate of https://github.com/owncloud/client/issues/6341; try to see if the description there matches your setup so we can narrow down the issue at hand. 

Also, could you try to get some [client logs](https://doc.owncloud.org/desktop/latest/troubleshooting.html#log-files) during the incident and also [sample the process](https://support.plex.tv/articles/201373203-gather-a-process-dump-or-sample-process) to obtain more info on what's going on?

**Comment by ogoffart** [comment]
Could also be the same as issue #6272
Would be worth to try the 2.4.1 nightly build and see if this is not already fixed.

**Comment by guruz** [comment]
@ogoffart It's called daily build now ;-)

@TheAppService Can you try https://download.owncloud.com/desktop/daily/ownCloud-2.5.0.66-daily20180205-setup.exe and report back?

**Comment by TheAppService** [comment]
Jep, the daily build fixed the issue so this seemed to be a duplicate. So it doesn't need to be investigated further I guess.... 

Best thanks and regards!!

Daniel

**Comment by guruz** [comment]
Hooray :)
