### ISSUE TITLE
Create a consistent testpilotcloud theme that follows ownCloud CI

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#6359]
- [x] Win ~~NSIS~~ *.MSI installer
- [x] Mac Installer
- [x] Setup wizard
- [ ] Application and activity icons
- [x] Update OS X icons to retina (@guruz knows the details)

@ChrisEdS please take care for the 2.5.0 release.

**This is what @hurradieweltgehtunter proposed:**

> We do not use gradients anywhere and we shouldn't start here. 
> Proposals:
> ![image](https://user-images.githubusercontent.com/16665512/36223812-971710a8-1193-11e8-81df-05de58bd5fda.png)
> 
> ![image](https://user-images.githubusercontent.com/16665512/36223832-a7b555c8-1193-11e8-9942-7595c8ecf33f.png)
> 
> ![image](https://user-images.githubusercontent.com/16665512/36223841-b040d4ba-1193-11e8-84a1-11620898d6b4.png)
> 
> Colors are generated by using a color palette using oc dark blue as base. I'm fine with all of them.

**Comment by ChrisEdS** [comment]
Then we should take the SATIN SHEEN GOLD in my opinion.

**Comment by guruz** [comment]
Related https://github.com/owncloud/client/issues/5014

**Comment by michaelstingl** [comment]
@guruz thanks, added it to the list: `- [ ] Update OS X icons to retina (@guruz knows the details)`

**Comment by michaelstingl** [comment]
@ChrisEdS any update?

**Comment by michaelstingl** [comment]
Retina related: https://github.com/owncloud/client/issues/6439

**Comment by guruz** [comment]
Moving to 2.6

**Comment by ChrisEdS** [comment]
I've created an "TestpilotUSER" account with the new testpilotcloud theme - I will test the clients in the next days.

**Comment by michaelstingl** [comment]
@ChrisEdS related: https://github.com/owncloud/ownbrander/issues/800

**Comment by ogoffart** [comment]
Note that the testpilot cloud theme is not in this repository. So this is not something the development team can do.

**Comment by guruz** [comment]
Removing this from milestone..

**Comment by ChrisEdS** [comment]
I'll take care together with @jw this week.

**Comment by guruz** [comment]
Removed from milestone

**Comment by jnweiger** [comment]
testpilotcloud ladybug theme uses these colors:
* 000000
* FFFFFF
* DB5461
* CCA43B
* DB969D

**Comment by jnweiger** [comment]
ios, android, and desktop sections in ownbrander all have all needed graphics.
Done from my perspective.
There is one unchecked item in the initial post, [ ] Application and activity icons
No idea what should be done there. Obsolete? @michaelstingl please review and close this issue.

**Comment by michaelstingl** [comment]
@jnweiger are the macOS testpilot icons retina now? (https://github.com/owncloud/client/issues/5014 links to this issue)

**Comment by TheOneRing** [comment]
Closing as I assume this to be ready.
