### ISSUE TITLE
delta-sync crashes the client occasionally when synchronizing many files at once

### ISSUE THREAD

**Issue by orzeech** [owncloud/client#6361]
### Expected behaviour
When synchronizing several files at once (in my case, 12 files, 10x 200mb, 2 small ones), the operation should finish correctly and the larger files should be synchronized with delta-sync

### Actual behaviour
The client crashes and silently exits

### Steps to reproduce
1. Build a new client from delta-sync branch, synchronize it with delta-sync enabled server
2. Create some files in your folder, preferably over 100mb (I haven't had problems with smaller files than 50mb)
3. Make sure delta-sync is enabled
4. synchronize your files, make modifications repeat several times, possible to use the following simple script to modify files:
`#!/bin/bash
for file in $1/*
do
	echo "Appending to $file"
	echo "b">>"$file"
done
`
5. (optional) break the connection with the server mid-sync. Happened to me twice with broken connection, once with normal connection
6. The client will sometimes exit without any warning

### Server configuration
Operating system: Ubuntu linux 17.04 on vbox

Web server: apache2

Database: mariadb

PHP version: 7

ownCloud version: from https://github.com/ahmedammar/core

Storage backend (external storage): no external storage

### Client configuration
Client version: client from delta-sync branch cd7ba1

Operating system: ubuntu 17.04

OS language: english us

Qt version used by client package (Linux only, see also Settings dialog): 5.9.1

Client package (From ownCloud or distro) (Linux only): from delta-sync branch, built locally

Installation path of client: 

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: 
https://gist.github.com/orzeech/52966b371830492e0e868d487dd74147

2. Server logfile: ownCloud log (data/owncloud.log):
https://gist.github.com/orzeech/32ee5693f0e21b5378488192b6eed36d

**Comment by guruz** [comment]
Related to https://github.com/owncloud/client/pull/6342 ?

FYI @ckamm @ahmedammar

**Comment by ckamm** [comment]
@orzeech Thank you for the report!
@guruz I don't think #6342 should lead to crashes.

The client log aborts just after starting a new remote discovery. I think I'll need to try to reproduce to see if I can get a stacktrace. @orzeech If you build yourself - can you run the client with a debugger attached when reproducing to capture a stacktrace?

```
gdb --args path/to/my/owncloud --logdebug --logfile /tmp/client-logfile.txt
> run
once the crash happens
> thread apply all bt
lots of relevant output here
```

**Comment by ckamm** [comment]
Furthermore, but probably unrelated: The 404 DELETEs that are seen in the server log originate from `SyncEngine::deleteStaleUploadInfos`. Why are there stale upload infos though? It looks like `finalize()` is called correctly on the upload job which should wipe the finished uploadInfo.

**Comment by guruz** [comment]
@orzeech ping?

**Comment by orzeech** [comment]
Sorry, I didn't notice your comments. I will get back to you this weekend

**Comment by guruz** [comment]
Great. make sure to have the latest commits https://github.com/owncloud/client/commits/delta-sync

**Comment by ckamm** [comment]
Feel free to reopen if there's more information. We also fixed a bunch of unrelated crashes in the meantime!
