### ISSUE TITLE
Use more user friendly conflict tags in filenames

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6365]
Currently conflict files are tagged with `-conflict-20180220-141213`. As suggested by @ogoffart in #6364 (and also implied by dropbox) we could be using `(Conflict 2018-02-20 14.12.13)` instead.

This kind of change would need to be backwards compatible and take into account the "user name in conflict tag" change #6364.

**Comment by guruz** [comment]
Moving to 2.6.0

**Comment by ogoffart** [comment]
I think we should try to take the oportunity to do it in 2.5 if possible so we don't change the format of conflict file too often.

**Comment by ckamm** [comment]
@ogoffart @guruz What's the exact pattern we want to use? I'm going with " (Conflict Username yyyy-mm-dd hh:mm:ss)" for now. Dropbox seems to use " (Username's conflicted copy yyyy-mm-dd)".

**Comment by ogoffart** [comment]
I'd say  " (Conflict Username yyyy-mm-dd hh-mm-ss)"
Upper case for "Conflict"  and you unfortunately cannot use ':' on windows, so better not use it. (maybe using ';' instead would be better?  or just nothing: hhmmss?)

**Comment by SamuAlfageme** [comment]
We might also wanna think about a future where the server might be able to handle conflict files as such (not as plain, regular files but files with some metadata associated). I'm thinking on ways to feed e.g. https://github.com/owncloud/client/issues/5896

Will it make sense to send/store information on who created a conflict, when it was created, etc. without relying on the filename? e.g. to be sent on hypothetical `OC-Conflict-Creator`, `OC-Conflict-Mtime`... headers

**Comment by ckamm** [comment]
@SamuAlfageme The client already sends this kind of data to the server: https://github.com/owncloud/platform/issues/159

**Comment by SamuAlfageme** [comment]
@ckamm aw, you're a man ahead of your time! 😂

**Comment by SamuAlfageme** [comment]
Same as in https://github.com/owncloud/client/issues/6325#issuecomment-389922348 - closing!

**Comment by jnweiger** [comment]
With 2.5.0 beta1, the naming looks like this: 
`filename (conflicted copy jwtest 2018-08-08 201107).txt`

The username "jwtest" is only present, if the uploadConflictFiles feature is enabled. It should always be present for forward compatibility when the feature gets enabled later.

BAD
When the uploadConflictFiles feature is disabled, the client will silently ignore a file that I create via
`echo "not a conflict" > "filename (conflicted copy jwtest 2018-08-08 201107).txt"`
Maybe https://github.com/owncloud/client/issues/6702 could help.

**Comment by guruz** [comment]
@ckamm indeed, why is the user name only added when conflicts are being uploaded?

**Comment by ogoffart** [comment]
When the conflict file is not uploaded, there is no  reason to have the username in the filename since it is obviously from the local user. 

When the feature gets enabled later, should we even upload the old conflict file?

**Comment by jnweiger** [comment]
### tested with 2.5.1 rc2

`.*conflicted copy.*` seems to work well as a pattern.
OK: The artificially created file `filename (conflicted copy jwtest 2018-08-08 201107).txt` is recognized as a conflict file. (even with wrong user name).

OK: With OWNCLOUD_UPLOAD_CONFLICT_FILES=1 the username is part of the conflict file name, without, it is not. both kind of conflict files are correctly recognized even after the client is restarted with a changed OWNCLOUD_UPLOAD_CONFLICT_FILES setting.

The inconsistency of having the username in one case and not having it in another may be confusing to some users, but okayish given that it no longer causes odd behaviour.

PASS
