### ISSUE TITLE
2.4.1.RC1 - Empty Setup Windows after installation

### ISSUE THREAD

**Issue by glannes31** [owncloud/client#6375]
### Expected behaviour
Setup Windows says that the installation is finish

### Actual behaviour
Empty Setup Windows appear with no pssibility to close this

![image](https://user-images.githubusercontent.com/20032648/36489086-6bb26f10-1725-11e8-88d3-47beb2b00f9b.png)

### Steps to reproduce
1. Do the installation
2. Wait
3. See the blank setup windows

### Server configuration
Operating system:  RHEL 

Web server:  APACHE

Database:Maria DB 

PHP version:7

ownCloud version:10.0.6

Storage backend (external storage):

### Client configuration
Client version:2.4.1.RC1

Operating system: Windows 7 Pro

OS language: French

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

No Logs

**Comment by guruz** [comment]
@glannes31 Strange!
How does the installer of 2.4.0 look? https://download.owncloud.com/desktop/stable/ownCloud-2.4.0.8894-setup.exe

**Comment by SamuAlfageme** [comment]
I cannot reproduce so far (neither `ownCloud-2.4.1.9260rc1-setup` nor `testpilotcloud-2.4.1.9261rc1-setup`); may need to check with a different OS base language.

**Comment by glannes31** [comment]
@guruz Thanks for your answer, i upgrade from 2.4.0 with a desinstallation.

**Comment by guruz** [comment]
@glannes31 But how does the 2.4.0 installer look? :-) Does it have the same bug? You can try to run it..
Just to see if the 2.4.1 installer behaves strange or also 2.4.0 installer (when you start it now without acctually installing)

**Comment by glannes31** [comment]
With a fresh install , it's okay .

**Comment by konisolde** [comment]
I installed & it worked fine. Win 10 Pro, English.

**Comment by guruz** [comment]
same for my windows 10 home, English (which can't be set to French grrr)
can't reproduce it a windows 7 enterprise, English  (which can't be set to French grrr)

Let's ignore this for now and try to have @glannes31 provide more information if this can be reproduced with 2.4.1 final.

**Comment by guruz** [comment]
@glannes31 Do you get the same problem with https://download.owncloud.com/desktop/testing/ownCloud-2.4.1.9270-setup.exe ?

**Comment by guruz** [comment]
@glannes31 ^^ :)

**Comment by glannes31** [comment]
@guruz nope! it's okay with 2.4.1 , so issue closed . Thks for all guys!
