### ISSUE TITLE
No option to "Edit" Account instead of Remove/Add New

### ISSUE THREAD

**Issue by konisolde** [owncloud/client#6376]
### Expected behaviour
Tell us what should happen
1. Open the Desktop client
2. Click on Account
3. See Edit within the choices 
4. Edit the Account details (URL, user name, password)
5. Save & close = Account updated

### Actual behaviour
Tell us what happens instead
1. Open the Desktop client
2. Click on Account
3. Do not see Edit within the choices - currently: Add New, Logout, Remove
4. Remove old account
5. Go through all the initial steps required to create/add a new account: enter url, user name, password, sync entire folder(s) 

### Steps to reproduce
1. Open the Desktop client
2. Click on Account
3. Look for a way to edit the current Account (no Edit function available)

### Server configuration
Operating system: Windows

Web server: Apache

Database: MariaDB (or MySQL)

PHP version: current

ownCloud version: 10.0.4

Storage backend (external storage):

### Client configuration
Client version: 2.3.3 (build 8250)

Operating system: Windows 10 Pro

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

![image](https://user-images.githubusercontent.com/20224734/36485780-3b9c5b86-171d-11e8-8193-f818ff0c55c2.png)

**Comment by michaelstingl** [comment]
@konisolde Thank for very much for your feedback!

What is your use case? ownCloud server admin changes the URL of an ownCloud instance?

1. I remember a branding option for migration of a fixed/hidden server URL to another fixed/hidden server URL
2. @SamuAlfageme Isn't there something with redirects? Can the oC instance "learn" about a new server URL from the redirect?

**Comment by konisolde** [comment]
@michaelstingl :) Hope I formulated clearly and included all the pertinent information needed. 

UC: Yes, Server Admin changes the URL of an ownCloud instance and then the users have to update the account information to continue syncing to desktop (and mobile) clients. As updating/editing is not possible within the Account options, it is then necessary to setup a new account and go through all initial steps required. It's not a huge issue - except that I have quite a lot of data to sync, so my desktop client is going to take over 12 hrs. to sync everything. I can easily go through the web client in the meantime, but it would simplify things if there were additional options to edit the account. 

I use ownCloud every day - and especially the desktop client! :)

**Comment by konisolde** [comment]
BTW, it might be nice to add "What's your use case?" to the text when opening a new Issue. Totally forget to add this on my own.

**Comment by jnweiger** [comment]
For yo Linux guys and gals:
`sed -i -e 's@//s3\.owncloud\.com@//cloud.owncloud.com@' ~/.config/ownCloud/owncloud.cfg`

**Comment by glannes31** [comment]
Hello, and with the 2.4.0 version ?

**Comment by guruz** [comment]
@settermjd Maybe we need a small paragraph here that it is possible to change the username or URL?
https://doc.owncloud.org/desktop/2.2/advancedusage.html#configuration-file
or maybe better here: https://doc.owncloud.org/desktop/2.2/faq.html

**Comment by SamuAlfageme** [comment]
Our recommended (and supported) way to change the server URL is to set up a 301/302 redirection on the old location. The client will then adjust to the new one. 

Linking here these 2 posts from central - if the above falls out of the user's hands (since setting up a redirection is the task of the server admin); editing the `.cfg` like @jnweiger pointed on https://github.com/owncloud/client/issues/6376#issuecomment-367465577

- https://central.owncloud.org/t/changing-domain-of-owncloud-installation/11445/2
- https://central.owncloud.org/t/change-server-without-re-downloading-everything

**Comment by SamuAlfageme** [comment]
@michaelstingl @konisolde forgot to mention this one is only available after 2.4.0 (that's probably why the URL was not auto-adjusted even though the redirection was in place).

**Comment by jnweiger** [comment]
@SamuAlfageme The redirect is now in place in @konisolde 's case to ease the transition. But we should eventually find a process to deprecate old names.

**Comment by konisolde** [comment]
@glannes31 - see comment from SamuAlfageme. Have not tested myself.

**Comment by ckamm** [comment]
@jnweiger The feature to update the url for an account in the config file when seeing a permanent redirect was added for 2.4 for #5972 :)

**Comment by ogoffart** [comment]
note that changing the url or the username would break all the existing folder if pointing to a different server or username. Because all the file etags will be different, everything will be re-downloaded again. (or removed if the files are not on the server)

The use case in which the user have to change the URL and that there is no server redirection is too seldom that we add an option in the UI for that.

**Comment by jnweiger** [comment]
@ogoffart will the one-liner from https://github.com/owncloud/client/issues/6376#issuecomment-367465577 also break thing like you describe? I don't think that etags got changed at all.

**Comment by ogoffart** [comment]
@jnweiger : Yes.  It will break if you make it point to a different server.  

In this case it is fine because s3.owncloud.com is the same server as cloud.owncloud.com. But it is also unnecessary since there is a redirection between the two (although being a `302 Moved Temporarily`, we don't save the new url in the config. We only do it for 301 and 308)

**Comment by guruz** [comment]
FYI @ogoffart i think this is about the SAME server getting a different URL or a new server restored from the same backup(=same etags, fileids etc)
For all other cases you are right of course.

**Comment by ogoffart** [comment]
@guruz   I know that.  But then, the server admin should set a redirect up, and no need to have an option to edit the account.

If we have an option that allow to change the account URL, it will be abused to change to another server.

I understand there might be cases where you want to change the URL and a redirection is not possible. (eg: the domain for the server was stolen or lost).  Do we really need to care about that?

**Comment by guruz** [comment]
> Do we really need to care about that?

No, we don't. @settermjd can add this to the FAQ in the doc. (e.g. either setup redirect or edit cfg)
https://github.com/owncloud/client/issues/6376#issuecomment-367653473
