### ISSUE TITLE
Excessively large buttons and icon on Linux

### ISSUE THREAD

**Issue by Carlgo11** [owncloud/client#6385]
Hello,
I'm not sure whether or not this is a ownCloud issue, dependency issue or something related to Gnome-desktop but for some reason the ownCloud client on my PC has excessively buttons along with an icon in the system tray that's bigger than the tray width.

Here's a screenshot:
![owncloud_screenshot_0](https://user-images.githubusercontent.com/3535780/37123611-2c64e266-2265-11e8-8cad-6f6e9bc18ed6.png)

and here's a screenshot that shows ownCloud in reference to other programs along with the system tray to the top right:
![owncloud_screenshot_1](https://user-images.githubusercontent.com/3535780/37123625-32273744-2265-11e8-9ce7-55f717dcb512.png)

### Client configuration
Client version: 2.4.0 (8911) _9a1f73_.

Operating system: Ubuntu, Linux  (\w Gnome-Desktop)

OS language: EN_us

Qt version used by client package (Linux only, see also Settings dialog): 5.6.2

Client package (From ownCloud or distro) (Linux only): ownCloud PPA.

Installation path of client: N/A

**Comment by ogoffart** [comment]
What's the version of Ubuntu and Gnome?
Do you have any other Qt-based application running, to they show a similar problem? What's the Qt version on your system?

Could you tell me if you have these environment variable defined, and it yes, to what:
`QT_SCALE_FACTOR`  ,  `QT_AUTO_SCREEN_SCALE_FACTOR` ,  `QT_SCREEN_SCALE_FACTORS` , `QT_DEVICE_PIXEL_RATIO` 

You can try setting the `QT_SCALE_FACTOR=1`  before starting owncloud


also, what is the result of the following commands could be useful:

```
xdpyinfo | grep -B2 resolution
xrdb -query | grep dpi
xrandr  | grep -w connected
```

Thanks.

**Comment by Carlgo11** [comment]
Thanks for pointing me in the right direction. The problem was `QT_AUTO_SCREEN_SCALE_FACTOR`. If I set it to something lower than 1 then the application shows as intended.
Sorry for waisting your time on something that apparently wasn't related to ownCloud.

Have a great Friday evening! :tada:
