### ISSUE TITLE
Correct building requirements

### ISSUE THREAD

**Issue by angerangel** [owncloud/client#6386]
Hi,
to build this client you ask at least **Qt 5.9.0**, but the package **Qt5::WebKitWidgets** was removed from Qt with **Qt 5.7**.
The new package is called **WebEngine**

**Comment by ogoffart** [comment]
We still need WebKitWidgets. We won't port to QtWebEngine
There are still community supported version of webkit working with Qt 5.9 that can be used.
Otherwise Shibboleth can be disdabled with -DNO_SHIBBOLETH=1

**Comment by angerangel** [comment]
So, please write some instruction to build this client, because cmake continue to give me errors:

- or Qt is too old
- or Qt is good, but it doesn't have WebKitWidgets

Best regards

**Comment by angerangel** [comment]
Or just create the **appimage** (see https://appimage.org/) many software for Linux now use this universal binary independent format.

**Comment by ogoffart** [comment]
The build instruction are here:  https://github.com/owncloud/client/blob/master/doc/building.rst

Qt 5.6 is the mibimum version supported, and you can still build it with Qt 5.6

It is specified that you need webkit. But if you don't have it , you wan still build with `-DNO_SHIBBOLETH=1`

**Comment by ogoffart** [comment]
As for app image, it is indeed planed: https://github.com/owncloud/client/issues/5951
