### ISSUE TITLE
owncloud-client 2.4.1-1 breaks nemo integration

### ISSUE THREAD

**Issue by khartahk** [owncloud/client#6393]
I've already reported the issue to the Arch linux bug tracker but they say it's a bug in the upstream code with localisation beeing broken due to adding python3 build support or something like that. Here's the link: https://bugs.archlinux.org/task/57885#comment167697

### Expected behaviour
right click on dir/file in nemo should show owncloud option to share public link etc...

### Actual behaviour
right click on dir/file in nemo doesn't show owncloud option

### Steps to reproduce
1. install nemo 3.6.4 and nemo-python 3.6.0-2
2. install owncloud-client 2.4.1-1
3. set up owncloud connection
4. start owncloud-client 
5. run `nemo -q` to completely kill nemo
6. open new nemo instance and right click on a file inside synced owncloud folder should give you an owncloud option - it doesn't
6.1. there should also be an icon for sync status on the folder / file itself - it's missing

Temporary Workaround:
install `downgrade` package and use `downgrade owncloud-client` to downgrade to 2.4.0-1 and it works

### Client configuration
Client version: 2.4.1-1
Operating system: Arch / Antergos
OS language: Slovenian
Client package (From ownCloud or distro) (Linux only): 2.4.1-1
Installation path of client: `/usr/bin/owncloud`

### Other package versions:
community/nemo 3.6.5-1
community/nemo-python 3.6.0-2

### Logs
```mar 19 15:13:58 computer nemo.desktop[17379]: Initializing ownCloud-client-nemo extension
mar 19 15:13:58 computer nemo.desktop[17379]: Socket File: /run/user/1000/ownCloud/socket
mar 19 15:13:58 computer nemo.desktop[17379]: Setting connected to True.
mar 19 15:13:58 computer nemo.desktop[17379]: Socket watch id: 15
mar 19 15:13:58 computer nemo.desktop[17379]: Server response: REGISTER_PATH:/home/primoz/ownCloud
mar 19 15:13:58 computer nemo.desktop[17379]: Server response: GET_STRINGS:BEGIN
mar 19 15:13:58 computer nemo.desktop[17379]: Traceback (most recent call last):
mar 19 15:13:58 computer nemo.desktop[17379]: File "/usr/lib/python2.7/site-packages/gi/overrides/GLib.py", line 754, in <lambda>
mar 19 15:13:58 computer nemo.desktop[17379]: func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
mar 19 15:13:58 computer nemo.desktop[17379]: File "/usr/share/nemo-python/extensions/syncstate-ownCloud.py", line 131, in _handle_notify
mar 19 15:13:58 computer nemo.desktop[17379]: self._handle_server_response(l.decode())
mar 19 15:13:58 computer nemo.desktop[17379]: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc4 in position 29: ordinal not in range(128)```

**Comment by michaelstingl** [comment]
@khartahk Thank you very much for reporting this issue. Do you have any hint how to reproduce with one of the supported Linux distros? Fedora? Debian? (I've no Arch experience)

**Comment by khartahk** [comment]
Hm official ubuntu repo only has nemo-python 3.4.0-2 and owncloud-client 2.4.0-1 which work on Arch. So you would probably have to install from owncloud [repo](https://software.opensuse.org/download/package?project=isv:ownCloud:testpilot&package=testpilotcloud-client) but I'm not sure if this is the same version as the one I have in Arch. Also since nemo-python is older I don't know how that affects this issue. I'll try to install this on ubuntu later this week and I'll post my results here.

**Comment by antonio-rojas** [comment]
To reproduce this, run owncloud-client with a locale whose owncloud context menu contains non-ascii characters, eg.
```
LANG=zh_CN owncloud
```
and then launch nemo

**Comment by michaelstingl** [comment]
@jnweiger Could you have a look?

@SamuAlfageme Any chance to cover the extensions with your testing machine? (install + execute)

**Comment by ckamm** [comment]
This is probably an issue with the python2/3 compatibility we added. See f254ee3211d18af79ed5c2fd1fa87c23658c7b6b - I'll investigate

**Comment by ckamm** [comment]
@khartahk Thanks for the report. There's a PR now and this will go into 2.4.2 - if there is one - or 2.5.

**Comment by sagitariozod** [comment]
Hello, after reading on github, I have solved the problem by replacing the file of the version 2.4.1
/usr/share/nautilus-python/extensions/**syncstate-ownCloud.py**

with that of version 2.4.0, included in the package nautilus-owncloud_2.4.0+dfsg-1_all.deb.

I have also deleted the file.
/usr/share/nautilus-python/extensions/**syncstate-ownCloud.pyc**

After restarting, in this way everything works normally again.

Thank you very much.

**Comment by khartahk** [comment]
In Arch owncloud-client 2.4.1-2 already has this fix. I've tested it and it works.
Thank you for a fast response.

**Comment by mbiebl** [comment]
I run into the same issue on Debian sid.
I've applied the patch from the associated PR, unfortunately this does not fix the issue fully.

If I run nautilus from the terminal, it works fine.
If I run nautilus via the app launcher, it does not. The difference afaics is, that starting nautilus via the app launcher does trigger the start via D-Bus:
```
Mai 11 05:33:52 pluto systemd[6013]: Created slice dbus\x2d:1.2\x2dorg.gnome.Nautilus.slice.
Mai 11 05:33:52 pluto systemd[6013]: Started dbus-:1.2-org.gnome.Nautilus@0.service.
Mai 11 05:33:52 pluto gnome-software[6320]: Failed to find one package for vmware-netcfg.desktop, /usr/share/applications/vmware-netcfg.desktop, [0]
Mai 11 05:33:52 pluto nautilus[6762]: sys:1: PyGIWarning: Nautilus was imported without specifying a version first. Use gi.require_version('Nautilus', '3.0') before
Mai 11 05:33:53 pluto nautilus[6762]: Initializing ownCloud-client-nautilus extension
Mai 11 05:33:53 pluto nautilus[6762]: Socket File: /run/user/1000/ownCloud/socket
Mai 11 05:33:53 pluto nautilus[6762]: Setting connected to True.
Mai 11 05:33:53 pluto nautilus[6762]: Socket watch id: 14
Mai 11 05:33:53 pluto nautilus[6762]: Server response: REGISTER_PATH:/mnt/data/ownCloud
Mai 11 05:33:53 pluto nautilus[6762]: Server response: GET_STRINGS:BEGIN
Mai 11 05:33:53 pluto nautilus[6762]: Traceback (most recent call last):
Mai 11 05:33:53 pluto nautilus[6762]:   File "/usr/lib/python2.7/dist-packages/gi/overrides/GLib.py", line 668, in <lambda>
Mai 11 05:33:53 pluto nautilus[6762]:     func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
Mai 11 05:33:53 pluto nautilus[6762]:   File "/usr/share/nautilus-python/extensions/syncstate-ownCloud.py", line 133, in _handle_notify
Mai 11 05:33:53 pluto nautilus[6762]:     self._handle_server_response(l.decode('utf-8'))
Mai 11 05:33:53 pluto nautilus[6762]:   File "/usr/share/nautilus-python/extensions/syncstate-ownCloud.py", line 140, in _handle_server_response
Mai 11 05:33:53 pluto nautilus[6762]:     print("Server response: " + line)
Mai 11 05:33:53 pluto nautilus[6762]: UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 47: ordinal not in range(128)
Mai 11 05:33:56 pluto nautilus[6762]: Traceback (most recent call last):
Mai 11 05:33:56 pluto nautilus[6762]:   File "/usr/share/nautilus-python/extensions/syncstate-ownCloud.py", line 219, in get_file_items
Mai 11 05:33:56 pluto nautilus[6762]:     state_ok = state.startswith('OK')
Mai 11 05:33:56 pluto nautilus[6762]: AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by mbiebl** [comment]
```
$ systemctl --user status "dbus-:1.2-org.gnome.Nautilus@1.service"
● dbus-:1.2-org.gnome.Nautilus@1.service
   Loaded: loaded (/run/user/1000/systemd/transient/dbus-:1.2-org.gnome.Nautilus@1.service; transient)
Transient: yes
   Active: active (running) since Fri 2018-05-11 05:40:25 CEST; 1min 24s ago
 Main PID: 7663 (nautilus)
   CGroup: /user.slice/user-1000.slice/user@1000.service/dbus\x2d:1.2\x2dorg.gnome.Nautilus.slice/dbus-:1.2-org.gnome.Nautilus@1.service
           └─7663 /usr/bin/nautilus --gapplication-service

Mai 11 05:40:25 pluto nautilus[7663]:     func_fdtransform = lambda _, cond, *data: callback(channel, cond, *data)
Mai 11 05:40:25 pluto nautilus[7663]:   File "/usr/share/nautilus-python/extensions/syncstate-ownCloud.py", line 133, in _handle_notify
Mai 11 05:40:25 pluto nautilus[7663]:     self._handle_server_response(l.decode('utf-8'))
Mai 11 05:40:25 pluto nautilus[7663]:   File "/usr/share/nautilus-python/extensions/syncstate-ownCloud.py", line 140, in _handle_server_response
Mai 11 05:40:25 pluto nautilus[7663]:     print("Server response: " + line)
Mai 11 05:40:25 pluto nautilus[7663]: UnicodeEncodeError: 'ascii' codec can't encode character u'\u2026' in position 47: ordinal not in range(128)
Mai 11 05:40:29 pluto nautilus[7663]: Traceback (most recent call last):
Mai 11 05:40:29 pluto nautilus[7663]:   File "/usr/share/nautilus-python/extensions/syncstate-ownCloud.py", line 219, in get_file_items
Mai 11 05:40:29 pluto nautilus[7663]:     state_ok = state.startswith('OK')
Mai 11 05:40:29 pluto nautilus[7663]: AttributeError: 'NoneType' object has no attribute 'startswith'
```

**Comment by ckamm** [comment]
@mbiebl Your stack traces show an error originating from `print("Server response: " + line)` - that line doesn't appear in 2.4.2's nautilus/nemo shell integration anymore, see f8a4994307030d26a62ae2f6039807802e214802

To check whether the patch that will go into 2.4.2 fixes your problem, please use the plugin file from https://github.com/owncloud/client/blob/2.4/shell_integration/nautilus/syncstate.py.

**Comment by ckamm** [comment]
Great! Yes, 2.4.2 is not released yet.

**Comment by jnweiger** [comment]
Tested with 2.4.2~rc1 on ubuntu 18.04 cinnamon:

having german locale LANG=de_DE and these two files in the sync folder
<pre>
    echo huhu > '♥_♥.txt'
    echo huhu > 'Jü.txt'
</pre>
Sharing via owncloud works fine from within nemo.
There are several python errors logged to nemo's stdout, but none seem to cause any issues.
<pre>
     Traceback (most recent call last):
  File "/usr/share/nemo-python/extensions/syncstate-testpilotcloud.py", line 217, in get_file_items
    state_ok = state.startswith('OK')
AttributeError: 'NoneType' object has no attribute 'startswith'
</pre>
