### ISSUE TITLE
[Windows] [MS Office] Accessing ownCloud data from Word 2016 on Win 10, is nearly impossible

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#6394]
Accessing ownCloud data from Word 2016 on Win 10, is nearly impossible:

![word2016-win10](https://user-images.githubusercontent.com/214010/30226726-617c3e8e-94d7-11e7-90c4-82bd6b27c061.gif)

Related: [[Windows] File Explorer integration (#5295)](https://github.com/owncloud/client/issues/5295), PR: https://github.com/owncloud/client/pull/6113

### Expected behaviour
ownCloud accounts and sync folder pairs should show up similar as OneDrive accounts

### Actual behaviour
Accessing ownCloud data from Word 2016 on Win 10, is nearly impossible. (see GIF)

### Steps to reproduce
1. Install MS Office 2016 on Win 10
2. Install oC client 2.4.1
3. Open file menu in Word 2016

### Client configuration
Client version:
2.4.1

Operating system:
Win 10

OS language:
EN

@dschmidt @SamuAlfageme as discussed some time ago, we need specs what needs to be implemented here.

00009003

**Comment by ad1rie1** [comment]
Hello, you can port the fix on owncloud if you want :) 
Or Use this regex adapted to owncloud 
`Windows Registry Editor Version 5.00

; NOTE, this file uses a GUID generated here
; https://www.guidgenerator.com/online-guid-generator.aspx
; IF you are going to have multiple Nextcloud folders in your tree you
; will need to make a new GUID for each folder and find/replace the
; value "38d6662b-09f4-4e73-bf61-b0e512ec41e1" with your unique GUID

[HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\\{38d6662b-09f4-4e73-bf61-b0e512ec41e1}]
; Name of the folder, also see last line below
@="Nextcloud"
; Sort order, lower number for higher in list
"SortOrderIndex"=dword:00000040
; 1 for shown, 0 for not shown
"System.IsPinnedToNamespaceTree"=dword:00000001

[HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\\{38d6662b-09f4-4e73-bf61-b0e512ec41e1}\DefaultIcon]
; folder icon, pulled the Nextcloud favicon.ico from nextcloud.com
@="C:\\Users\\Thibault NASPLEDA\\Nextcloud\\favicon.ico"

[HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\\{38d6662b-09f4-4e73-bf61-b0e512ec41e1}\InProcServer32]
@=hex(2):25,00,53,00,59,00,53,00,54,00,45,00,4d,00,52,00,4f,00,4f,00,54,00,25,\
  00,5c,00,73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,73,00,68,00,\
  65,00,6c,00,6c,00,33,00,32,00,2e,00,64,00,6c,00,6c,00,00,00

[HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\\{38d6662b-09f4-4e73-bf61-b0e512ec41e1}\Instance]
"CLSID"="{0E5AAE11-A475-4c5b-AB00-C66DE400274E}"

[HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\\{38d6662b-09f4-4e73-bf61-b0e512ec41e1}\Instance\InitPropertyBag]
"Attributes"=dword:00000011
; this is the folder we're pointing at
"TargetFolderPath"="C:\\Users\\Thibault NASPLEDA\\Nextcloud"

[HKEY_CURRENT_USER\SOFTWARE\Classes\CLSID\\{38d6662b-09f4-4e73-bf61-b0e512ec41e1}\ShellFolder]
"Attributes"=dword:f080004d
"FolderValueFlags"=dword:00000028

[HKEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel]
"{38d6662b-09f4-4e73-bf61-b0e512ec41e1}"=dword:00000001

[HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Explorer\Desktop\NameSpace\{38d6662b-09f4-4e73-bf61-b0e512ec41e1}]
; Name of the folder again
@="Nextcloud"


[HKEY_CURRENT_USER\SOFTWARE\Classes\Wow6432Node\CLSID\\{38d6662b-09f4-4e73-bf61-b0e512ec41e1}]
; Name of the folder, also see last line below
@="Nextcloud"
; Sort order, lower number for higher in list
"SortOrderIndex"=dword:00000040
; 1 for shown, 0 for not shown
"System.IsPinnedToNamespaceTree"=dword:00000001

[HKEY_CURRENT_USER\SOFTWARE\Classes\Wow6432Node\CLSID\\{38d6662b-09f4-4e73-bf61-b0e512ec41e1}\DefaultIcon]
; folder icon, pulled the Nextcloud favicon.ico from nextcloud.com
@="C:\\Users\\Thibault NASPLEDA\\Nextcloud\\favicon.ico"

[HKEY_CURRENT_USER\SOFTWARE\Classes\Wow6432Node\CLSID\\{38d6662b-09f4-4e73-bf61-b0e512ec41e1}\InProcServer32]
@=hex(2):25,00,53,00,59,00,53,00,54,00,45,00,4d,00,52,00,4f,00,4f,00,54,00,25,\
  00,5c,00,73,00,79,00,73,00,74,00,65,00,6d,00,33,00,32,00,5c,00,73,00,68,00,\
  65,00,6c,00,6c,00,33,00,32,00,2e,00,64,00,6c,00,6c,00,00,00

[HKEY_CURRENT_USER\SOFTWARE\Classes\Wow6432Node\CLSID\\{38d6662b-09f4-4e73-bf61-b0e512ec41e1}\Instance]
"CLSID"="{0E5AAE11-A475-4c5b-AB00-C66DE400274E}"

[HKEY_CURRENT_USER\SOFTWARE\Classes\Wow6432Node\CLSID\\{38d6662b-09f4-4e73-bf61-b0e512ec41e1}\Instance\InitPropertyBag]
"Attributes"=dword:00000011
; this is the folder we're pointing at
"TargetFolderPath"="C:\\Users\\Thibault NASPLEDA\\Nextcloud"

[HKEY_CURRENT_USER\SOFTWARE\Classes\Wow6432Node\CLSID\\{38d6662b-09f4-4e73-bf61-b0e512ec41e1}\ShellFolder]
"Attributes"=dword:f080004d
"FolderValueFlags"=dword:00000028`
