### ISSUE TITLE
Link to, and improve documentation on conflict resolution

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6396]
Currently, when there are conflicts, the user gets tray notifications and sees a yellow box in the account status. These should redirect them to the "not synced" list where all pending conflicts are visible. However, currently there's no explanation on what the steps to resolve a conflict might be.

This page should have a link to our documentation and the documentation should be updated with an explanation and a step by step guide on resolving conflicts and common issues.

@guruz

**Comment by SamuAlfageme** [comment]
👍

**Comment by ckamm** [comment]
Not done, we want a link to the new documentation show up in the ui when conflicts are present

**Comment by ckamm** [comment]
![image](https://user-images.githubusercontent.com/833306/38794380-305e460a-4155-11e8-98c6-52d13284ef97.png)

**Comment by ckamm** [comment]
Note that we only want to merge the PR https://github.com/owncloud/client/pull/6456 once the documentation link becomes available.

**Comment by ckamm** [comment]
Track in PR instead

**Comment by jnweiger** [comment]
OK: 
clicking on the yellow badge, opens the 'not synced' tab, clicking on a conflicting file opens the file browser, 
clicking on the documentation link opens https://doc.owncloud.org/desktop/2.5/conflicts.html
which has a good description what to do.

Idea:
Add to the documentation, currently the strategy is 'server always wins", but give a warning that this strategy may change in  future.
