### ISSUE TITLE
Verify 2.4 and master merge for crashreporter

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6398]
While merging 2.4 and master there was a tricky conflict between slightly different versions of mostly the same commit: d69e9ebf464023826dd74caaf901e9921faffc53 (master) and 567f7eb205fb2a7071b64b9880a0624a182aa4da (2.4). Please verify master is fine now!

In particular:
* There was no 
```
qt_wrap_ui( crashreporter_UI_HEADERS ${crashreporter_UI} )
qt_add_resources( crashreporter_RC_RCC ${crashreporter_RC} )

include_directories(${CMAKE_CURRENT_BINARY_DIR}
    "../3rdparty/libcrashreporter-qt/src/"
)
```
in master anymore.
* Which of these two lines is right in this insert/insert conflict?
```
set(CRASHREPORTER_ICON_PATH "${CRASHREPORTER_ICON_DIR}/${CRASHREPORTER_ICON_SIZE}-${CRASHREPORTER_ICON_FILENAME}")
set(CRASHREPORTER_ICON_PATH "${CRASHREPORTER_ICON_DIR}/${APPLICATION_ICON_NAME}-icon-${CRASHREPORTER_ICON_SIZE}.png")
```
during the merge I picked the master (top) one

**Comment by guruz** [comment]
@dschmidt tested the crash reporter afaik for other reasons. Can he close it?

**Comment by dschmidt** [comment]
Also https://github.com/owncloud/client/blob/v2.5.0-alpha/src/crashreporter/CMakeLists.txt#L21 looks good.
