### ISSUE TITLE
Linux Ubuntu 14.04 repository of onwcloud client is missing

### ISSUE THREAD

**Issue by workingmachine** [owncloud/client#6401]
### Actual behaviour
Package manager apt could not load packages from repository.

### Steps to reproduce
1.  apt-get update

### Client configuration
Client version: 2.4.0

Operating system: Ubuntu 14.04 LTS

OS language: English

### Logs
W: Failed to fetch http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_14.04/Packages  404  Not Found [IP: 2001:67c:2178:8::13 80]

E: Some index files failed to download. They have been ignored, or old ones used instead.
--------------------------------------------------------------------------------------------------
At http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/xUbuntu_14.04/

Resource is no longer available!

**Comment by jnweiger** [comment]
Same discussion also started in central: https://central.owncloud.org/t/repo-for-ubuntu-14-04-has-disappeared/12397/16

It is a pity that modern systems like mint linux 17 are still based on old ubuntu 14.04

I'd be happy with a decision to keep 14.04 active for a while.

**Comment by guruz** [comment]
If it's not hard to keep the repo up and building then let's do it..?

**Comment by ogoffart** [comment]
Since we no longer support Ubuntu 14.04, is that something we should care about?
Is it about not deleting old packages?  Is that OBS deleting the  old packages ?

**Comment by michaelstingl** [comment]
If 14.04 causes no extra work, we could keep the repo… (unsupported)

**Comment by thomasfla** [comment]
I could really use a .deb for 14.04 at the moment. 

Is there a mirror somewhere ? Or do I have to build from source to use owncloud-client on 14.04?

**Comment by jnweiger** [comment]
I've enabled the 14.04 repo in https://software.opensuse.org//download.html?project=isv%3AownCloud%3Adesktop&package=owncloud-client

Let's see if things just rebuild on their own. If not I'll spend some free time to make it work again.

**Comment by thomasfla** [comment]
Worked for me,
Thank's a lot!

**Comment by workingmachine** [comment]
A simple smoke test worked for me.
Thank a lot.

I use the owncloudcmd client at an ubuntu server 14.04 to synchronize some changed scripts and configuration files to the owncloud server which runs also at the same operating system.
I will upgrade the operating system when ubuntu 18.04 is out, my hosting provider does support this operating system and some time is gone where people have collect experience with this new operating system.
Until this time I need to have a synchronization client at my server.

If there are no security issues than I can live with an older owncloudcmd client.
In the case where no more updates would come it would be great if you could retain the old packages at one of your servers.

Thank you for your great work.

**Comment by michaelstingl** [comment]
@workingmachine I recommend to use the 2.3.4. That was the last version that officially supported Ubuntu 14.04, 32-bit Linux and pre-10.10 Mac OS X versions. There is nothing wrong with the 2.3.4. 2.3.4 is a great ownCloud desktop sync client. I'll try to get the link to to the repo with older versions added here: https://owncloud.org/download/older-versions/ /cc @jnweiger

**Comment by workingmachine** [comment]
@michaelstingl The link of older versions for example 14.04 https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client
 shows the current owncloud client 2.4.1.

After some searches I have found the correct repository path of 2.3.4:
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/client-2.3.4/Ubuntu_14.04/
