### ISSUE TITLE
[2.5.x] Client recovery strategy for broken chunked uploads when server hd was full?

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6405]
Server replied "400 Bad Request" to "MOVE https://..../owncloud/remote.php/dav/uploads/guruz/45471869/.file"
["Chunks on server do not sum up to 39730872 but to 39688248"](https://github.com/owncloud/core/blob/6bc3941603a5fab30d85f89a75ae8ec53c158264/apps/dav/lib/Upload/ChunkingPlugin.php#L105)
(While uploading, I had also received "Connected Closed" but I guess that can be ignored as the server was bin byzzantine state.)

FYI @DeepDiver1975 @ogoffart

**Comment by ogoffart** [comment]
Thanks for the but report.
Can you please fill the bug template? 
In particular, what are the step to reproduce and what would be the expected behavior?

If the server only reports Bad Request, that's what the client will show.

**Comment by ckamm** [comment]
Fwiw, there already is a recovery strategy for server chunk brokenness - but only for http code 412 by default. See `PropagateUploadFileCommon::checkResettingErrors()`. The idea is that if you receive this error code three times you throw away the `UploadInfo` and start from scratch instead.

**Comment by guruz** [comment]
@ogoffart I don't want to fill the server hard drive again to know how exactly to reproduce the bug, obviously.

@ckamm I unfortauntely don't know if it did a follow-up sync. Maybe it had the grace perioud and was waiting to do a follow up? I worked around the whole issue by renaming the file (after cleaning up the hd a bit)
So HTTP 412 is precondition failed? hmmmm.
I don't know if the server should return that. What does @DeepDiver1975 think?

**Comment by ckamm** [comment]
@guruz I didn't mean that the server should reply 412, I was just saying that there was a mechanism that could be used for recovering from broken uploads if we can make it apply to this case (in case it doesn't work already, which it should!).

**Comment by ckamm** [comment]
@guruz Why ReadyToTest, was there a change here?

**Comment by ckamm** [comment]
This is closed by the PR #6460
