### ISSUE TITLE
[Win] Publish MSVC/MSI client daily builds

### ISSUE THREAD

**Issue by voroyam** [owncloud/client#6409]
A msi client should be build for download for windows in the daily repo

**Comment by dschmidt** [comment]
we have several tickets for this already. We are working on it and will publish dailys very soon hopefully.

**Comment by voroyam** [comment]
Good to know, Michael noticed me that this would be "issue-worthy" :)

And I did not check the other issues before making this one. My bad

**Comment by michaelstingl** [comment]
@dschmidt first daily builds would be okay-ish without crash reporter. Anything else missing? I think it already builds daily? Just upload it? /cc @jnweiger

**Comment by dschmidt** [comment]
@mstingl yup. I wanted a review by Samuel but otherwise - yep, just upload it. @jw should know how to do it from the msvc-msi job.

**Comment by jnweiger** [comment]
upload is easy, once the jobs work  :-)

**Comment by michaelstingl** [comment]
okay, re-assigned @dschmidt …

**Comment by SamuAlfageme** [comment]
@dschmidt I'm on it! will give it a past and post here the results

**Comment by jnweiger** [comment]
Almost success: https://jenkins.int.owncloud.com/job/client-win32-msvc-msi/104/console 

That fails to upload after building a nice and shiny msi. I'll investigate.

**Comment by dschmidt** [comment]
Jobs work, even with crash reporter by now... closing.
