### ISSUE TITLE
Client doc Screen shots

### ISSUE THREAD

**Issue by voroyam** [owncloud/client#6410]
The screen shots for the client installation are wrong. These are for connecting the client to the server, but not for the installation wizard. 

https://doc.owncloud.com/desktop/latest/installing.html#installation-wizard

New screen shots should be taken of the msi client

**Comment by michaelstingl** [comment]
Existing screenshots are valid too, but we might also need screenshots for the real installation. (*.MSI for example, or/and macOS installation…)

**Comment by voroyam** [comment]
@michaelstingl I would like to close this.

opened in 2018, now is 2021, no progress.

**Comment by michaelstingl** [comment]
works for me
