### ISSUE TITLE
Blacklisted items don't prevent parent directory etags from updating

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6411]
Currently if an item is blacklisted it will not be reattempted. Instead it's set to `Ignored` and `BlacklistedError`. The intention is that we want to show the sync as successful and silently reattempt the file after some time. (the value of the whole feature is debatable)

The problem with this approach becomes clear in a specific scenario: Say the file `A/foo.txt` can't be downloaded and gets blacklisted after the first sync. On the second sync it doesn't get attempted and the sync as well as `PropagateDirectory` for `A` is successful, updating the etag of `A`. When the blacklist entry expires the client will know longer be aware that it needs to rediscover `A` and do something inside it.

**Comment by ckamm** [comment]
PR #6412

**Comment by ckamm** [comment]
Keeping this open because I still want to add blacklisting tests - we've had none of them for too long.

**Comment by guruz** [comment]
This bug must exist since ages?
