### ISSUE TITLE
Persist X-Request-ID with the events that originated them 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6420]
`X-Request-ID` was introduced in client v. 2.4: https://github.com/owncloud/client/issues/5853 for tracing back and cross-referencing requests with the server logs. This can be seen as an extension of that to help users locate the cause of their issues together with admins. 

Would it be possible to store this ID together with its originator event on the sync journal to allow some sort of "Copy X-Request-ID` when right-clicking an event from the "Activity > Not Synced" tab? (only in those cases that are strictly related to the server operation/network activity). This way is not strictly necessary to have the log window open or to be inspecting the network to get this ID. 

e.g. 

```
sqlite> select * from blacklist;
path        lastTryEtag  lastTryModtime  retrycount  errorstring                                                                                                                     X-Request-ID                                    lastTryTime  ignoreDuration  renameTarget  errorCategory
----------  -----------  --------------  ----------  --------------------------------------------------------------------------------------------------------------------            ----------------------------------------------  -----------  --------------  ------------  -------------
.htaccess                1522758480      2           Server replied "403 Forbidden" to "PUT https://localhost/remote.php/dav/files/admin/.htaccess" (Sabre\DAV\Exception\Forbidden)  4c5adb86-2a66-4450-9af9-f6f77b5bdf581522758593   125                           0
```

cc/ @michaelstingl

**Comment by guruz** [comment]
@ogoffart What about adding a column for the in ```.owncloudsync.log ```?
And also modifying the server log templates (for apache, nginx) to show them in the server log file?

**Comment by SamuAlfageme** [comment]
@guruz 

> And also modifying the server log templates (for apache, nginx) to show them in the server log file?

Makes complete sense, will open issues/poke people around to do so.

**Comment by SamuAlfageme** [comment]
Link https://github.com/owncloud-docker/base/issues/22

**Comment by SamuAlfageme** [comment]
WFM 👍 

--- 

For reference, since @michaelstingl asked me: log rotation period is 2MB - all blacklist errors are meant to re-appear in there, but old errors that went away are not granted to be preserved; an error-only log might be an interesting idea to explore, but a different topic. 

https://github.com/owncloud/client/blob/fabc706e43c54f8a9c7ee89807d16e63948fdb8b/src/gui/syncrunfilelog.cpp#L96-L110

I fear most of the log contain _not-so-useful_ info, but that's also a different topic: 

```
#=#=#=# Syncrun started 2018-05-17T15:52:45Z
#=#=#=#=# Propagation starts 2018-05-17T15:52:46Z (last step: 857 msec, total: 857 msec)
#=#=#=# Syncrun finished 2018-05-17T15:52:46Z (last step: 12 msec, total: 870 msec)
#=#=#=# Syncrun started 2018-05-17T15:52:48Z
#=#=#=#=# Propagation starts 2018-05-17T15:52:48Z (last step: 322 msec, total: 322 msec)
#=#=#=# Syncrun finished 2018-05-17T15:52:48Z (last step: 36 msec, total: 359 msec)
#=#=#=# Syncrun started 2018-05-17T15:52:59Z
#=#=#=#=# Propagation starts 2018-05-17T15:52:59Z (last step: 267 msec, total: 267 msec)
15:53:03||cv_en.pdf|INST_NEW|Up|1506664574||23909||8|Upload of 23 KB exceeds the quota for the folder|507|0|0|aaa544b5-af30-4d0b-a6d0-18ab07c519a1|
#=#=#=# Syncrun finished 2018-05-17T15:53:00Z (last step: 410 msec, total: 678 msec)
```

**Comment by guruz** [comment]
FYI 74e412c7897aab31f368757946ae59dce13eac77 2.5
