### ISSUE TITLE
Delta-sync windows tests

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6424]
During the discussions around the delta sync patch we had concerns around how well the posix-api using zsync library will work on windows. The baseline usually is that it kind of works, but suboptimally. 

The client has made significant progress over the years in dealing with locked files on Windows, very long file names and filename encoding issues. The zsync upload/download code paths might cause regressions in these areas.

To make sure we catch as many issues as we can early we need to look at what file ops zsync does in particular, and explicitly - probably manually - test for these problems on windows.

(raised after a conversation with @dragotin - thanks for the reminder!)

**Comment by ckamm** [comment]
Potential problem areas:
* `ZsyncGenerateRunnable` uses `fopen()` to open a user file for generating a zsync metadata file during uploads
* `ZsyncSeedRunnable` uses `QFile::open` to open a user file for seeding during up/downloads

Both probably want to use `FileSystem::openAndSeekFileSharedRead` instead

The other reads and writes are either to temporary files or not new.

**Comment by ckamm** [comment]
The PR https://github.com/owncloud/client/pull/6425 already implements the changes that seemed necessary when going through the code. Lots of testing is still necessary.

**Comment by ckamm** [comment]
p3 since delta sync still isn't enabled by default. I still believe delta sync has received hardly any testing on windows.

**Comment by ckamm** [comment]
QA: 
1. Set up server that supports zsync (I don't know what the current state of doing it is, used to be a server branch/pr). Verify by checking dav/zsync capability is present.
2. Enable delta sync by putting this into your owncloud.cfg
```
[DeltaSync]
enabled=true
```
3. Sync files >10MB up and down. Verify logs don't contain "zsync disabled" string.
4. Verify there are no odd errors, no data corruption etc.

**Comment by HanaGemela** [comment]
@ckamm server does not support zsync
@michaelstingl @pmaier1 please advice what to do with this issue and with delta sync in the client in general

**Comment by HanaGemela** [comment]
@michaelstingl @pmaier1 @ckamm move to ReadyToTest once it is ready to test. For now I'm removing the label

**Comment by TheOneRing** [comment]
Deltasync was killed

**Comment by CrispStrobe** [comment]
@ckamm @TheOneRing @michaelstingl @HanaGemela 
icyi, here is a fork that attempts delta sync: https://github.com/CrispStrobe/owncloud-client 
together with https://github.com/CrispStrobe/crispcloud-delta-sync
otherwise, sorry for necroposting ;)
