### ISSUE TITLE
How do I de-select a folder and keep on local filesystem

### ISSUE THREAD

**Issue by tomneedham** [owncloud/client#6429]
1. I sync my desktop folder with my ownCloud
2. I accidentally aded a vm disk image to my desktop which was uploaded to owncloud
3. Now I want to remove this from my ownCloud, but keep it on my desktop
4. I tried deselecting the folder from the sync client but this says it will remove it from my local system

How can I deselect, but leave this on my local system?

I imagined the deselect box to ask, delete from remote or delete from local and I choose where I want to keep the file from now onwards.

**Comment by guruz** [comment]
Move it out of the sync folder :-) 

Semi-related: https://github.com/owncloud/client/issues/6381

**Comment by hodyroff** [comment]
Yep. Currently move it out of the sync folder into any other folder and it will do what you want. Closing.
We keep thinking about the other options mentioned in 6381 and prior, but most likely in the context of virtual file system, etc.
