### ISSUE TITLE
Translation for Nautilus integration

### ISSUE THREAD

**Issue by jose1711** [owncloud/client#6430]
Python script for Nautilus is not l10n ready - text in menu items is hardcoded in English:
```
labelStr = "Share with " + appname + "..."
..
tip='Share file {} through {}'.format(file.get_name(), appname) )
```

**Comment by ogoffart** [comment]
Thanks for your bug report.
This was fixed in commit 0238a29c7cd8bffce79ac684d3aae15bed481412 which is already in 2.4.0
