### ISSUE TITLE
Fix menubar status icon resolution on retina displays

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6439]
@tomneedham just reported the client's status icon is a bit blurry on retina resolution (HiDPI) after 2.4.1 update: 

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/38496725-ceb6c518-3bfe-11e8-94a7-8ae08cd2d830.png"/>
</p>

I think this has to do with the new `ECMAddAppIcon` macro introduced on: https://github.com/owncloud/client/commit/81c20352e1dfd7800f7c43ce8dc9bb08b68b33ce#diff-a6d1bb854f78adb4d11e13a57d0d52f1 - maybe requiring >64px. icons for the `.icns` bundle. 

cc/ @dschmidt can you take a peek to see if this makes sense?

**Comment by guruz** [comment]
Can't reproduce this with 2.4 branch or 2.5 branch with normal oC.
is this about testpilotcloud @tomneedham ?

**Comment by guruz** [comment]
2.5:
<img width="176" alt="screen shot 2018-04-27 at 09 39 26" src="https://user-images.githubusercontent.com/959327/39351012-42a9a210-4a00-11e8-8b45-184476c7a737.png">
2.4:
<img width="176" alt="screen shot 2018-04-27 at 09 49 04" src="https://user-images.githubusercontent.com/959327/39351020-4c218f74-4a00-11e8-9cc2-1172eb5fca2e.png">

(Yes, the Quassel logo IS blurry)

**Comment by tomneedham** [comment]
I restarted the client and its fine now... strange.

**Comment by guruz** [comment]
@tomneedham great
