### ISSUE TITLE
Simple permanent logging

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6442]
Debugging sync problems is often extremely challenging without a detailed log. But many sync problems are intermittent and people won't have logging switched on when it is most needed.

We already have a solution: `--logdir` and `--logexpire` but so far I haven't seen it used.

What if there was a simple button people could use to permanently switch on logging into a temporary directory? The logs should be compressed and expire after a few hours. The button could be hidden in the logwindow or something.

Benefits:
* Makes it easier when asking people to capture logs. They no longer need to pass `--logfile --logdebug` etc on the command line
* Makes it easier for our high-quality reporters to provide logs for sporadic and tricky problems

**Comment by SamuAlfageme** [comment]
@ckamm could a small note for the details of this be included into https://doc.owncloud.org/desktop/latest/troubleshooting.html#log-files for reference?

**Comment by ckamm** [comment]
@SamuAlfageme Definitely!

**Comment by SamuAlfageme** [comment]
@ckamm great job! 🎉
