### ISSUE TITLE
Windows 10 Client Limit LTE SIM Card use Mobile Data

### ISSUE THREAD

**Issue by jonathanmmm** [owncloud/client#6445]
### Expected behaviour
I am using Windows 10 with a SIM Card with LTE
I have enabled in windows that background and so on is limited, so that e.g. OneDrive won't sync automatically over my SIM Card.
Problem, I don't see such an option like in the Android App etc. that you can only sync via LAN or WLAN or that the service recognizes the setting under: (I am trying to translate german to english, don't know if the name is excactly the same)
settings->Network and Internet -> Datausage (above Proxy, the circle with the piece). -> Datausage limit in background and I have chosen "Always"

### Actual behaviour

It uploaded e.g. a ~800MB file and I didn't want that.
The option with the limit setting this to 0MB folder size would not recognize the difference with LTE or WLAN or LAN.

### Server configuration
Operating system:
Debian Stretch
Web server: 
13.0.1 (Nextcloud)
Database:
MariaDB
PHP version:
7.x
### Client configuration
Client version:
2.3.3 (Nextcloud Client
Operating system:
Windows 10 1709
OS language:
German

I have seen that I should enter the topic here and not in nextcloud because it is the same windows client with some template, I believe, right?

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/client/issues/4808
