### ISSUE TITLE
Failure when trying to ignore server notification

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#6449]
The ownCloud server notifies me that there is an update to an App. Okay, I got it, but I don't want this hint to take up valuable space in the UI while I cannot update the App, so I press the dismiss button. 

### Expected behaviour

The message should vanish.

### Actual behaviour

The client refuses to remove the message with an error message:

![failure](https://user-images.githubusercontent.com/875883/38615640-abb82662-3d91-11e8-816d-3604ee45d0e0.png)

(The German error message seems to be a bit nonsensical but that's probably a different issue :))

### Steps to reproduce
1. Dismiss a server notification about an App update.

### Server configuration
Operating system: Debian Jessie (Bananian)

Web server: Apache 2.4

Database: MySQL

PHP version: 5.6

ownCloud version: 10.0.7

Storage backend (external storage): Local

### Client configuration
Client version: 2.5.0-daily20180216 (build 9245)

Operating system: Windows 7

OS language: German

Installation path of client: Default

**Comment by SamuAlfageme** [comment]
@sagamusix weird - this was fixed by @guruz on https://github.com/owncloud/client/pull/5936 and I've just tried to dismiss a notification for `templateeditor`'s update on `Version 2.5.0daily20180411 (build 9586)` (bit older than yours, but fix should be there as well) 😕

**Comment by guruz** [comment]
btw the additional needed fix is 7eb2dc21af043a4b91cde5e92d5965bdaf251af3 which was done in february 6th in 2.4 branch. I don't know when it got into 2.5/master but I think @sagamusix 's build might not have it yet.

> Client version: 2.5.0-daily20180216 (build 9245)

Try with a newer one @sagamusix ?

**Comment by sagamusix** [comment]
Since I updated the App in question I can no longer verify at this point, but if you think that the required patch was merged into 2.5 at a later point, feel free to close. I'll obtain a new daily build.

**Comment by guruz** [comment]
ok, i'll close.
BTW, you can create notifications with https://marketplace.owncloud.com/apps/announcementcenter (or directly from the market app in your oC)
