### ISSUE TITLE
Drop QtWebKit from build dependencies

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6451]
After having https://github.com/owncloud/client/pull/5668 implemented and https://marketplace.owncloud.com/apps/oauth2 gaining more and more adoption, we're in the right track (platform-wise) to drop the requirement of shipping a full-blown browser together with the client. 

Today I was looking at the differences and benefits we'll get in the e.g. `.app` bundles on install time and QtWebKit bloats the size in disk more than 50% (45.7 MB build with `-DNO_SHIBBOLETH=1` vs. 92.2 MB wo/ the build flag).

**Comment by jnweiger** [comment]
Will master build without QtWebKit now?

**Comment by ogoffart** [comment]
The packages just need to update the package to remove this dependences.

**Comment by guruz** [comment]
I'll check macOS and NSIS now

**Comment by guruz** [comment]
NSIS and macOS merged https://github.com/owncloud/client/pull/7158
MSI and Linux/Drone pending.
Linux OBS won't do.

**Comment by guruz** [comment]
MSI is done

**Comment by guruz** [comment]
@dschmidt @jnweiger How is this with the Linux/Drone builds? Done already so we can close here?

**Comment by jnweiger** [comment]
2.6.0 will still be done with the openSUSE Build service. I'll remove the dependency and see what happens.

**Comment by jnweiger** [comment]
https://build.opensuse.org/package/show/isv:ownCloud:desktop:daily:2.6/owncloud-client
is doing a rebuild without qtwebkit.

**Comment by jnweiger** [comment]
https://gitea.owncloud.services/client/build-linux/commit/32e709e29dd9d136067575c524bbb86ed9791516

https://gitea.owncloud.services/ownbrander/scripting/commit/a55cf01cce3f9c1de098cfded23177d081790050

done. 

## Tested ownCloud version 2.6.0daily20190604 (build 914) on Linux Mint 19
login with web token and password works. syncs fine. No more ocqt*qebkit packages on my system!
