### ISSUE TITLE
Placeholder-aware sharing from the context menu

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6461]
When sharing a file from its placeholder counterpart, use the real name for across the sharing dialog  instead of the `.owncloud` file living on the real FS:

- as `path`for private sharing / public links 
- to query the `fileid` / `privatelink` via PROPFIND
- to fetch the thumbnail (in case there's one)

```
curl  \
    -H 'Ocs-APIREQUEST:true' \
    -H 'Content-Type:application/x-www-form-urlencoded' \
    -H 'User-Agent:Mozilla/5.0 (Windows) mirall/2.5.0placeholderprototype (build 9468)' \
    [...]
    -X POST 'https://demo.owncloud.com/ocs/v1.php/apps/files_sharing/api/v1/shares?format=json' \
    --data-binary 'path=%2FownCloud%20Manual.pdf.owncloud&shareType=3&name=Public%20link'
```

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/38867493-830cb432-4244-11e8-941d-8fd5cde9e825.png"/>
</p>

A user might want to create a share link or copy its private link wo/ having to download the file.

**Comment by SamuAlfageme** [comment]
Working like a charm! 🎉 

@ogoffart was also backported to 2.5 right?

**Comment by ogoffart** [comment]
(yes, this is in 2.5)
