### ISSUE TITLE
Do not unfold "Sync Protocol" placeholder entries in deletion + real file download

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6462]
![screen shot 2018-04-17 at 13 52 48](https://user-images.githubusercontent.com/2644445/38868251-b66f7790-4246-11e8-9f11-31baa85fa06c.png)

This will also avoid extra noise in terms of notifications (1 per "Sync Protocol" entry).

**Comment by ckamm** [comment]
Sounds good!

**Comment by SamuAlfageme** [comment]
The virtual files flow (i.e. delete `.owncloud` -> download original) is no longer reflected like this. Can be closed as no longer confuses the user with "Deleted" actions. 

However, there's still room for improvement as when virtual and real file are fetched on the same client run, they'll appear as "duplicated" downloads in there:

![placeholder_activity](https://user-images.githubusercontent.com/2644445/41219164-cde137be-6d5d-11e8-93e2-8cd8be40656f.png)

The desired entries in the Activity for a "_seamless VFS experience_" need to be properly defined by PM. cc/ @pmaier1 @hodyroff
