### ISSUE TITLE
Bundled download of placeholders inside folder(s)

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6466]
I see a common use-case where a user might want to "materialize" (i.e. download and sync) all the files inside a folder. 

It's too demanding in terms of user-interaction to go file-by-file fetching every placeholder from a directory. Also consider that in this case, we don't want the usual "download and forward the real file to the program responsible for its opening" - we'll easily end up with one "photo viewer" window per picture inside the `"Holidays 2017"` folder.  

Getting some sort of context menu entry/switch for folders (and groups of folders as well, maybe?) will ease up such workflow. 

cc/ opinions @ckamm @ogoffart

**Comment by ckamm** [comment]
I agree that clicking on a folder and saying "download this and all contents, recursively" would be nice. I also thought about it, but it didn't make the "first version" cut. :)

**Comment by SamuAlfageme** [comment]
This is so awesome 😍 

I can use my file explorer to do a funky selection of folders at different depths in the three and get their contents sync'ed on my disk. yay!
