### ISSUE TITLE
Investigate if calling mapChecksumType once per downloaded file is a problem

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6473]
It always attempts an INSERT.

Maybe it's ok.

**Comment by ckamm** [comment]
It's not yet come up as a bottleneck. :)

I'm pretty sure the operation will be fast since the table is extremely small (<5 entries), The `name` column is marked as `unique` too so presumably sqlite will have an index on it.

**Comment by ckamm** [comment]
Quick test: Running the two sql queries comes out to around 1300 ns per `mapChecksumType()` call. Nevertheless a cache was added in 73dfe32be41d123c02be63a9958c92af0f504d11 which brings it down to 75ns per call.
