### ISSUE TITLE
Kill live log feature in log window

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6475]
https://github.com/owncloud/client/issues/6435#issuecomment-382774286

> And yeah, the log window isn't very functional. Personally, I'd drop the live view and just keep the "capture logs" checkbox along with a button that can open the folder that contains the files.

**Comment by ckamm** [comment]
Thanks!

**Comment by ogoffart** [comment]
I think the log window is fine, this is supposed to be a debug only feature. Normal users should not open it.

**Comment by ckamm** [comment]
I agree it's a debug feature. I think the live view and search is very had to use for debugging and we'd be better off dropping it and encouraging users to use log files. (via the permanent logging feature)

**Comment by michaelstingl** [comment]
Bring the settings for permanent logging to the general settings? (Then kill the window)

**Comment by guruz** [comment]
> Bring the settings for permanent logging to the general settings? 

but please only behind the extended settings checkbox..

**Comment by michaelstingl** [comment]
@ChrisEdS suggested:

> I desire an additional button that takes me directly to the appropriate folder. Let's say it's called "View" or "Saved Logs".
> 
> ![image](https://user-images.githubusercontent.com/33026403/54416351-65cc3f80-46ff-11e9-801d-3c77900543a0.png)

👍
