### ISSUE TITLE
Client can't find the server

### ISSUE THREAD

**Issue by cosnetltd** [owncloud/client#6480]
### Expected behaviour
Add a server.

### Actual behaviour
When at the first start no server is given, later is not possible
to add a server, it comes always an error message: It is not possible to connect to the server,
although the browser can connect to the server, to the API too (.../remote.php/webdav).
Remove and reinstall not helps.
A question: How is possible totally remove the client? I think it would be solve the problem.
### Steps to reproduce
1.  Install client and type next without to give a server-name.

3. 

### Server configuration
Operating system: 

Web server:  It is not working with the **demo.owncloud.org** too,

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:

Operating system:  Windows 7

OS language: Hungarian

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by ogoffart** [comment]
Hi,

I'm having some trouble to understand what the problem exactly is.

What version of the client are you using.

You can't press next on the wizard without entering a server.
If you enter a wrong server, you get an error and you can correct the server.

The only problem i could see is that if the server does not answer, it takes about a minute before it times out and you cannot cancel the request during this time.  Is that the problem?

**Comment by ogoffart** [comment]
Closing old issue.
