### ISSUE TITLE
2.5.0 release

### ISSUE THREAD

**Issue by ogoffart** [owncloud/client#6483]
Some weeks before the release:
* [x] Check if we should update the bundled sqlite3 (https://github.com/owncloud/client/tree/master/src/3rdparty/sqlite3)
* [x] Check if we should update Sparkle on build machine (https://github.com/sparkle-project/Sparkle/releases)
* [ ] Ensure NSIS is up to date on the build machine
* [x] Ensure up-to-date dependencies (e.g. [latest Qt version](http://qt-project.org/downloads#qt-lib) is installed on the machine and picked up (cmake output)
* [x] Ensure the crash reporter server is up
* [x] Check crash reporter for bad crashes
* [x] Ensure Windows Overlay DLLs are rebuilt
* [x] Check nightly builds are up and running, that is Jenkins jobs ownCloud-client-linux, ownCloud-client-osx and ownCloud-client-win32 all green.
* [x] Ensure Linux nightlies are built too for all distros https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/owncloud-client
  * Check if patches still apply in the linux packages
* [ ] Build branded clients through the scripting machine and smoke test one or two branded clients (especially with predefined url)
* [x] Upload a nightly build of the windows version to virustotal.com
  * Contact AV vendors whom's engine reports a virus
* [x] Documentation should be online before the release http://doc.owncloud.org/desktop/1.X/
* [ ] QA goes over https://github.com/owncloud/mirall/wiki/Testing-Scenarios
* [x] Make sure to have `client/ChangeLog` updated
 * use `git log --format=oneline v<lastrelease>...master` if your memory fails you
* [ ] check if enterprise issues are fixed

For first Alpha/Beta of a Major or Minor release:
* [x] branch off master to new version branch (e.g. master -> 2.1, when releasing 2.1)
* [ ] Adjust `VERSION.cmake` in master and count up (e.g. 2.2)
* [ ] Adjust translation jobs for [client](https://ci.owncloud.org/view/translation-sync/job/translation-sync-client/) and [NSIS](https://ci.owncloud.org/view/translation-sync/job/translation-sync-client-nsis/) to point to the release branch (e.g. 2.1).
* [ ] Make sure there is a job for the docs of the new master branch and the current release branch on rotor e.g. http://doc.owncloud.org/desktop/1.X/ exists

**alpha WITH WINDOWS OVERLAY BUG, IGNORE IT**
* [x] Add last updates to Changelog in the client source repository.
* [x] Branch off a release branch called VERSION-rcX or VERSION-betaX  (without v, v is for tags)
* [x] Edit ```VERSION.cmake``` to set the suffix to beta1, beta2 etc. Commit the result to the release branch only
* [x] Make sure to increase the version number of the branched of release, e.g. if you release 2.3.2 then you should change VERSION.cmake in 2.3 to 2.3.3 since that branch now will be 2.3.3
* [x] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'ownCloud'
* [x] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'testpilotcloud'
* [x] Only now download the last created source .tar.xz and sign it with gpg. Copy the signature into a new .asc file. (timing issue because currently 'testpilotcloud' re-creates the source .tar.xz)
* (no need to copy builds as they are already in testing directory or repository) (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [x] Mac: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Win: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Smoke test of one distro package (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Run @SamuAlfageme 's magic Linux-test-all-packages-script
https://gitlab.com/alfageme/client-linux-tests/pipelines/22832976
* [x] Create a signed tag using ```git tag -u E94E7B37 tagname``` (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [ ] Create a pull request to the owncloud.org repository to update the install page (strings.php, page-desktop.php) and the changelog on owncloud.org. From now on download packages from the staging webserver.
* [ ] Inform packagers @dragotin (openSUSE), @hefee (Debian), ??? (Fedora)
* [ ] Announce on https://central.owncloud.org
* [ ] Inform community mailinglists devel@owncloud.org and testpilots@owncloud.org (make sure to mention it is an rc). Link to the central post so discussion happens there.
* [ ] Check crash reporter

_alpha1_
* [x] Add last updates to Changelog in the client source repository.
* [x] Branch off a release branch called VERSION-rcX or VERSION-betaX  (without v, v is for tags)
* [ ] Edit ```VERSION.cmake``` to set the suffix to beta1, beta2 etc. Commit the result to the release branch only
* [ ] Make sure to increase the version number of the branched of release, e.g. if you release 2.3.2 then you should change VERSION.cmake in 2.3 to 2.3.3 since that branch now will be 2.3.3
* [x] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'ownCloud'
* [x] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'testpilotcloud'
* [ ] Only now download the last created source .tar.xz and sign it with gpg. Copy the signature into a new .asc file. (timing issue because currently 'testpilotcloud' re-creates the source .tar.xz)
* (no need to copy builds as they are already in testing directory or repository) (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [x] Mac: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Win: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Smoke test of one distro package (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Run @SamuAlfageme 's magic Linux-test-all-packages-script
* [x] Create a signed tag using ```git tag -u E94E7B37 tagname``` (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [x] Create a pull request to the owncloud.org repository to update the install page (strings.php, page-desktop.php) and the changelog on owncloud.org. From now on download packages from the staging webserver.
* [x] Inform packagers @dragotin (openSUSE), @hefee (Debian), ??? (Fedora)
* [x] Announce on https://central.owncloud.org
* [x] Inform community mailinglists devel@owncloud.org and testpilots@owncloud.org (make sure to mention it is an rc). Link to the central post so discussion happens there.
* [ ] Check crash reporter

beta1:
* [x] Add last updates to Changelog in the client source repository.
* [x] Branch off a release branch called VERSION-rcX or VERSION-betaX  (without v, v is for tags)
* [x] Edit ```VERSION.cmake``` to set the suffix to beta1, beta2 etc. Commit the result to the release branch only
* [ ] Make sure to increase the version number of the branched of release, e.g. if you release 2.3.2 then you should change VERSION.cmake in 2.3 to 2.3.3 since that branch now will be 2.3.3
* [x] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'ownCloud'
* [ ] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'testpilotcloud'
* [x] Only now download the last created source .tar.xz and sign it with gpg. Copy the signature into a new .asc file. (timing issue because currently 'testpilotcloud' re-creates the source .tar.xz)
* (no need to copy builds as they are already in testing directory or repository) (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [x] Mac: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Win: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [ ] Linux: Smoke test of one distro package (Install, make sure it does not explode, and check if all version indicators are correct)
* [ ] Linux: Run @SamuAlfageme 's magic Linux-test-all-packages-script
* [x] Create a signed tag using ```git tag -u E94E7B37 tagname``` (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [x] Create a pull request to the owncloud.org repository to update the install page (strings.php, page-desktop.php) and the changelog on owncloud.org. From now on download packages from the staging webserver.
* [ ] Inform packagers @dragotin (openSUSE), @hefee (Debian), ??? (Fedora)
* [x] Announce on https://central.owncloud.org
* [x] Inform community mailinglists devel@owncloud.org and testpilots@owncloud.org (make sure to mention it is an rc). Link to the central post so discussion happens there.
* [ ] Check crash reporter

beta2:
* [x] Add last updates to Changelog in the client source repository.
* [x] Branch off a release branch called VERSION-rcX or VERSION-betaX  (without v, v is for tags)
* [x] Edit ```VERSION.cmake``` to set the suffix to beta1, beta2 etc. Commit the result to the release branch only
* [ ] Make sure to increase the version number of the branched of release, e.g. if you release 2.3.2 then you should change VERSION.cmake in 2.3 to 2.3.3 since that branch now will be 2.3.3
* [x] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'ownCloud'
* [ ] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'testpilotcloud'
* [x] Only now download the last created source .tar.xz and sign it with gpg. Copy the signature into a new .asc file. (timing issue because currently 'testpilotcloud' re-creates the source .tar.xz)
* (no need to copy builds as they are already in testing directory or repository) (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [x] Mac: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Win: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [ ] Linux: Smoke test of one distro package (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Run @SamuAlfageme 's magic Linux-test-all-packages-script
* [x] Create a signed tag using ```git tag -u E94E7B37 tagname``` (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [x] Create a pull request to the owncloud.org repository to update the install page (strings.php, page-desktop.php) and the changelog on owncloud.org. From now on download packages from the staging webserver.
* [ ] Inform packagers @dragotin (openSUSE), @hefee (Debian), ??? (Fedora)
* [x] Announce on https://central.owncloud.org
* [x] Inform community mailinglists devel@owncloud.org and testpilots@owncloud.org (make sure to mention it is an rc). Link to the central post so discussion happens there.
* [x] Check crash reporter

rc1:
* [x] Add last updates to Changelog in the client source repository.
* [x] Branch off a release branch called VERSION-rcX or VERSION-betaX  (without v, v is for tags)
* [x] Edit ```VERSION.cmake``` to set the suffix to beta1, beta2 etc. Commit the result to the release branch only
* [ ] Make sure to increase the version number of the branched of release, e.g. if you release 2.3.2 then you should change VERSION.cmake in 2.3 to 2.3.3 since that branch now will be 2.3.3
* [x] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'ownCloud'
* [x] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'testpilotcloud'
* [x] Only now download the last created source .tar.xz and sign it with gpg. Copy the signature into a new .asc file. (timing issue because currently 'testpilotcloud' re-creates the source .tar.xz)
* (no need to copy builds as they are already in testing directory or repository) (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [x] Mac: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Win: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [ ] Linux: Smoke test of one distro package (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Run @SamuAlfageme 's magic Linux-test-all-packages-script
* [x] Create a signed tag using ```git tag -u E94E7B37 tagname``` (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [x] Create a pull request to the owncloud.org repository to update the install page (strings.php, page-desktop.php) and the changelog on owncloud.org. From now on download packages from the staging webserver.
* [ ] Inform packagers @dragotin (openSUSE), @hefee (Debian), ??? (Fedora)
* [ ] Announce on https://central.owncloud.org
* [ ] Inform community mailinglists devel@owncloud.org and testpilots@owncloud.org (make sure to mention it is an rc). Link to the central post so discussion happens there.
* [x] Check crash reporter

_For all alphas, betas and RCs (Copy this section for each alpha/beta/rc):_
* [ ] Add last updates to Changelog in the client source repository.
* [ ] Branch off a release branch called VERSION-rcX or VERSION-betaX  (without v, v is for tags)
* [ ] Edit ```VERSION.cmake``` to set the suffix to beta1, beta2 etc. Commit the result to the release branch only
* [ ] Make sure to increase the version number of the branched of release, e.g. if you release 2.3.2 then you should change VERSION.cmake in 2.3 to 2.3.3 since that branch now will be 2.3.3
* [ ] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'ownCloud'
* [ ] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'testpilotcloud'
* [ ] Only now download the last created source .tar.xz and sign it with gpg. Copy the signature into a new .asc file. (timing issue because currently 'testpilotcloud' re-creates the source .tar.xz)
* (no need to copy builds as they are already in testing directory or repository) (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [ ] Mac: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [ ] Win: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [ ] Linux: Smoke test of one distro package (Install, make sure it does not explode, and check if all version indicators are correct)
* [ ] Linux: Run @SamuAlfageme 's magic Linux-test-all-packages-script
* [ ] Create a signed tag using ```git tag -u E94E7B37 tagname``` (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [ ] Create a pull request to the owncloud.org repository to update the install page (strings.php, page-desktop.php) and the changelog on owncloud.org. From now on download packages from the staging webserver.
* [ ] Inform packagers @dragotin (openSUSE), @hefee (Debian), ??? (Fedora)
* [ ] Announce on https://central.owncloud.org
* [ ] Inform community mailinglists devel@owncloud.org and testpilots@owncloud.org (make sure to mention it is an rc). Link to the central post so discussion happens there.
* [ ] Check crash reporter

One week before the final release:
* [ ] Communicate the release schedule on mailinglist release-coordination@owncloud.com. Give a high level overview of the upcoming new features, changes etc.
* [x] Ensure marketing is aware (marketing@owncloud.com) and prepared for the release (social, .com website, cust. communications)
* [ ] Inform GCX knows the next version is about 1 week out (gcx@owncloud.com)

Day before final Release:
* [x] Check the translations coming from transifex: All synchronized?
* [x] Run the tx.pl scripts on the final code tag
* [x] Run ```make test```
* [x] Run smashbox
* [x] Inform product management and marketing that we are 1 day out

On Release Day (for final release):
* [x] Add last updates to Changelog in the client source repository.
* [x] Branch off a release branch called VERSION  (without v, v is for tags)
* [x] Edit ```VERSION.cmake``` to set the suffix to "" etc. Commit the result to the release branch only
* [x] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'ownCloud'
* [x] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'testpilotcloud'
* [x] Only now download the last created source .tar.xz and sign it with gpg. Copy the signature into a new .asc file. (timing issue because currently 'testpilotcloud' re-creates the source .tar.xz) (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [x] Branch isv:ownCloud:desktop to isv:ownCloud:desktop:client-X.Y.Z before overwriting https://github.com/owncloud/administration/blob/master/jenkins/obs_integration/obs-backup-prj.sh (the linux packages will land in the :testing repository still)
  ```obs-backup-prj.sh isv:ownCloud:desktop isv:ownCloud:desktop:client-2.4.1 owncloud-client 2.4.1 # (if not already done)```

* [x] Re-download Mac builds and check signature. Interactive in installer window
* [x] Re-download Win build check signature. From Mac or Linux: ```osslsigncode verify ownCloud-version-setup.exe```
* [x] Mac: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Win: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Smoke test of one distro package (Install, make sure it does not explode, and check if all version indicators are correct)
* [ ] Linux: Run @SamuAlfageme 's client-linux-tests Jenkins job (this tests only package installations!) Adjust REPO_URL in https://jenkins.int.owncloud.com/job/client-linux-tests/build (Better: gitlab?)
* [x] Win/Mac Copy builds from ```testing``` to ```stable``` on download.owncloud.com, double check the download links. (make sure the .asc is there too)
* [x] Linux: disable publishing on project isv:ownCloud:desktop
* [x] Linux: Use https://github.com/owncloud/administration/blob/master/jenkins/obs_integration/obs-deepcopy-prj.sh to copy from isv:ownCloud:community:testing to isv:ownCloud:desktop
  ```obs-deepcopy-prj.sh isv:ownCloud:desktop:testing isv:ownCloud:desktop```
  ```obs-deepcopy-prj.sh isv:ownCloud:testpilot:testing isv:ownCloud:testpilot```
* [x] check osc meta prj for needed updates between :desktop:testing and :desktop
* [x] Linux: Re-enable OBS publishing on the project after official release date and if all distros build (check for accidentially disabled packages too) 
* [ ] Linux: Wait until everything is built and published, then disable publishing on project isv:ownCloud:desktop
* [x] Create git signed tag in client repository using ```git tag -u E94E7B37 tagname``` (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [ ] Create a (draft) release on https://github.com/owncloud/client/releases
* [x] Update https://owncloud.org/changelog/desktop-client/
* [x] Update https://owncloud.org/download/#owncloud-desktop-client -> Download ownCloud -> click open 'Desktop Client', edit win/mac/lin, each all three tabs "Production", "Technical Preview" [disabled], "Test pilot" 
* [x] Announce on https://central.owncloud.org
* [ ] Announce on announcements@owncloud.org Link to the central post so discussion happens there.
* [ ] Inform packagers @dragotin (openSUSE) @hefee (Debian) @Germano0 (Fedora)
* [x] Send out Social (tweet, blog, other)
* [ ] Send out customer communication (if any)
* [ ] Inform GCX that the new version is released (gcx@owncloud.com)
* [ ] Inform release-coordination@owncloud.com
* [x] Ensure marketing is aware (marketing@owncloud.com)
* [x] Take pride and celebrate!
* [ ] Tell GCX to increment the minimum supported version for enterprise customers
* [ ] Check if minimum.supported.desktop.version (https://github.com/owncloud/core/blob/master/config/config.sample.php#L1152) needs to be updated in server

15 minutes after after release:
* [x] Test all advertised download links to have the expected version
* [x] Check for build errors in OBS, do
```obs-deepcopy-prj.sh isv:ownCloud:desktop isv:ownCloud:desktop:client-2.X.X```
* [ ] disable publishing in OBS to prevent that accidential rebuilds hit the end users.

A few days after the release (for final release)
* [ ] Review changes in the release branch, merge back into master
* [ ] check the crash reporter if auto update is a good idea or we need a new release
* [x] Update the updater script ```clientupdater.php``` https://github.com/owncloud/enterprise/wiki/How-to-use-the-Client-Updater#updating-the-owncloud-hosted-updater
* [ ] Execute announced deprecations. Disable builds for deprecated platforms. Update accordingly: https://doc.owncloud.org/server/latest/admin_manual/installation/system_requirements.html#desktop
* [ ] Increment version number in nightly builds. Special case: after the last release in a branch, jump forward to the 'next release branch'... That may mean, this is nightly is the same as edge then.

**Comment by guruz** [comment]
@dschmidt How is the compatibility of the MSI-based installer with regards to
1) Our auto updater
2) Installing on top of an existing NSIS install
?

**Comment by SamuAlfageme** [comment]
@guruz I've been collecting (on a pretty chaotic way) testing scenarios and results from my preliminary tests with msi on https://github.com/owncloud/client/wiki/Windows-.msi-testing-scenarios 

Feel free to include e.g. the auto updater scenario (good catch).

**Comment by dschmidt** [comment]
Definitely a good catch, I don't know. Need to check.

**Comment by guruz** [comment]
@dragotin @hefee FYI the alpha will be out real soon now (TM).

However the source tar xz did not get uploaded yet: https://jenkins.int.owncloud.com/job/client-trigger/656/console

**Comment by guruz** [comment]
Draft release for github: https://github.com/owncloud/client/releases/edit/untagged-9b60dce0c5b97953cbbb (missing sources link)

**Comment by dragotin** [comment]
@guruz pls provide a source tar as beta similar to what you plan to release. Enterprise bugs are hidden for community ;-)

**Comment by guruz** [comment]
@dragotin Tarball is up. owncloudclient-2.5.0-alpha.tar.xz in the usual directory.
(Note the alpha is still not released officially)

**Comment by guruz** [comment]
How did Fedora detect this?
> owncloud-client-2.5.0-alpha is available
https://bugzilla.redhat.com/show_bug.cgi?id=1551559#c1

**Comment by guruz** [comment]
CC @comzeradd

**Comment by SamuAlfageme** [comment]
@guruz it says on the link: 

> Based on the information from anitya:  https://release-monitoring.org/project/1987/

**Comment by guruz** [comment]
> Backend:
> GitHub
Interesting..

**Comment by dragotin** [comment]
Please consider fixing #6555

**Comment by guruz** [comment]
Scratch the -alpha, We're doing a -alpha1 with a showstopper fix.

**Comment by guruz** [comment]
@dragotin https://download.owncloud.com/desktop/testing/owncloudclient-2.5.0-alpha1.tar.xz

**Comment by guruz** [comment]
Central: https://central.owncloud.org/t/owncloud-virtual-file-system-discussion/13823

Clickable ChangeLog on: https://github.com/owncloud/client/releases/tag/v2.5.0-alpha1

**Comment by guruz** [comment]
beta1 is out
https://github.com/owncloud/client/releases/tag/v2.5.0-beta1

**Comment by guruz** [comment]
https://central.owncloud.org/t/desktop-sync-client-2-5-0-beta1-released/14667

**Comment by jnweiger** [comment]
@guruz Releasenotes in github mention Settings: Hide selective sync buttons while disconnected (#5809)
Please remove this line and move the milestone post 2.5.0, the PR is not merged.

**Comment by jnweiger** [comment]
@guruz Releasenotes in github mentions:
    Conflicts: Better comparison when connection broke (#6626)

the issue number belongs to something different. Please fix.

**Comment by guruz** [comment]
> Please remove this line and move the milestone post 2.5.0, the PR is not merged.
Hmm but 9c66dbb2b77a581d56a4ef1000c8e55410e56cfb is in 2.5.0
Are you mixing up something?

> the issue number belongs to something different. Please fix.

I have no idea what this was about. The line is copied from the ChangeLog though, so I also need to improve it there if we can find out what it was about :/

**Comment by guruz** [comment]
For Linux [on QtKeyChain 0.9.1 now](https://build.opensuse.org/package/show/isv:ownCloud:Qt5101/ocqt5101-qt5keychain). Thanks @jnweiger 
For [Windows it's WiP](https://github.com/owncloud/client/issues/6729#issuecomment-413863325) for @dschmidt

**Comment by guruz** [comment]
https://github.com/owncloud/client/releases/tag/v2.5.0-beta2

https://mailman.owncloud.org/pipermail/testpilots/2018-August/000396.html

https://central.owncloud.org/t/desktop-sync-client-2-5-0-beta2-released/14667

**Comment by guruz** [comment]
rc1 planned for tomorrow.

**Comment by guruz** [comment]
rc1 out https://github.com/owncloud/client/releases/tag/v2.5.0-rc1
@lefherz can you adjust the links on https://owncloud.org/download/#owncloud-desktop-client from beta2 to rc1?

@michaelstingl @ogoffart @ckamm @dschmidt (probably) last chance to test stuff before final! Please test and identify any showstoppers.

**Comment by guruz** [comment]
Edited https://central.owncloud.org/t/desktop-sync-client-2-5-0-rc1-released/14667

Deployed auto updater https://github.com/owncloud/enterprise/pull/2834 (beta channel)

**Comment by jnweiger** [comment]
Disabled repo signature checking via https://github.com/owncloud/enterprise/issues/2836 as desktop:testing currently has mismatched keys.
Testsuite now can test tings.

**Comment by guruz** [comment]
I had considered https://github.com/owncloud/client/issues/6699#issuecomment-420513324 a release blocker but I think I'm alone with that opinion :/

**Comment by dragotin** [comment]
Hmm, I think I would support you @guruz, for what it is worth...

**Comment by guruz** [comment]
@michaelstingl Can you arrange for builds being moved from https://download.owncloud.com/desktop/testing/ to https://download.owncloud.com/desktop/stable/ ?

ownCloud-2.5.0.10359-setup.exe
ownCloud-2.5.0.10650.10598.msi
ownCloud-qt5.10.1-2.5.0.10516.pkg*
owncloudclient-2.5.0.10650.tar.xz*
testpilotcloud-2.5.0.10655.10600.msi
testpilotcloud-2.5.0.10364-setup.exe
testpilotcloud-qt5.10.1-2.5.0.10521.pkg*
testpilotcloudclient-2.5.0.10655.tar.xz*

After this is done, set the download links in https://owncloud.org/download/#owncloud-desktop-client
Can we link to both 2.4.3 and 2.5.0 without calling it "technical preview"?
For Windows, link to the .msi not to the .exe 

Please report here when done :)

@dragotin @hefee You can make linux packages based https://download.owncloud.com/desktop/testing/owncloudclient-2.5.0.10650.tar.xz  on if you want :)

**Comment by dragotin** [comment]
Package test builds are available in https://build.opensuse.org/package/show/home:kfreitag/owncloud-client

Is that the official, released version?

**Comment by jnweiger** [comment]
@dragotin owncloudclient-2.5.0.10650.tar.bz2 is good. It is the source for our official 2.5.0 release tomorrow.

**Comment by jnweiger** [comment]
The download links are: 
* https://download.owncloud.com/desktop/stable/ownCloud-qt5.10.1-2.5.0.10516.pkg
* https://download.owncloud.com/desktop/stable/testpilotcloud-qt5.10.1-2.5.0.10521.pkg

* https://download.owncloud.com/desktop/stable/ownCloud-2.5.0.10650.10598.msi
* https://download.owncloud.com/desktop/stable/testpilotcloud-2.5.0.10655.10600.msi

* https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client
* https://software.opensuse.org/download.html?project=isv:ownCloud:testpilot:testing&package=testpilotcloud-client

**Comment by guruz** [comment]
Draft release created https://github.com/owncloud/client/releases/edit/untagged-a3e97b6486dca61f24e8
I can hit Publish when @jnweiger or @jnweiger tell me tonight (NBG timezone ;-)

**Comment by jnweiger** [comment]
Published the above links to owncloud.org. We have now 2.5.0 show up everywhere.

**Comment by guruz** [comment]
@jnweiger You missed the *'s in my [filename links](https://github.com/owncloud/client/issues/6483#issuecomment-421439597) so the .pkg.tbz and .pkg.tbz.sig are lost. See chat on how to re-create. :-)\

**Comment by guruz** [comment]
Auto updater PR: https://github.com/owncloud/enterprise/pull/2863

**Comment by guruz** [comment]
Auto updater is at the moment disabled (thanks @jnweiger ) because we want a more stable 2.5.1 for it.
