### ISSUE TITLE
macOS: Dark Wake / Power Nap error message from keychain

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6487]
I have 3 accounts, all showed up in the morning with one of those:

<img width="423" alt="screen shot 2018-04-25 at 09 17 48" src="https://user-images.githubusercontent.com/959327/39234711-54a9a420-4874-11e8-9444-ac53c912dd3c.png">
<img width="409" alt="screen shot 2018-04-25 at 09 17 19" src="https://user-images.githubusercontent.com/959327/39234718-56c7d434-4874-11e8-9365-c6b3a36835af.png">

I think I only got this because the Mac woke up somewhere where I didn't have the WiFi password (yet).
After restarting the client all is fine.

Maybe we can get macOS to keep our app frozen.
Or we ignore that specific keychain error -25320..wondering if the other one is just a follow up

FYI @SamuAlfageme 
FYI @frankosterfeld in case you're interested for QtKeyChain

(note that power nap != app nap)

**Comment by TheOneRing** [comment]
Please reopen the issue if it still exist.
