### ISSUE TITLE
macOS: Overlay icons only appeared after a client restart in a folder that didn't sync before (Sync folder canonicalization)

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6489]
The folder didn't sync **because the sync folder didn't exist** (I had it somewhere in /tmp which is wiped on reboot).
Then I created the folder and it synced, but icons didnt come.
Then I restarted the client and icons came.

When the sync folder is created with mkdir in first launch:
Sending SocketAPI message --> "REGISTER_PATH:/tmp/127sync" to SocketApiSocket(0x7f9e6ae73190)

No Icons:
Received SocketAPI message <-- "RETRIEVE_FILE_STATUS:/private/tmp/127sync/sf2/welcome copy 5.txt" from SocketApiSocket(0x7f9e6ae73190)
Sending SocketAPI message --> "STATUS:NOP:/private/tmp/127sync/sf2/welcome copy 5.txt" to SocketApiSocket(0x7f9e6ae73190)
NOP = no icon

In second client launch when things work:
Sending SocketAPI message --> "REGISTER_PATH:/private/tmp/127sync" to SocketApiSocket(0x7f8a7f765ca0)

**Comment by guruz** [comment]
(2.6 milestone is fine with me too)

**Comment by ogoffart** [comment]
It works for me, on linux, it sends the REGISTER_PATH when the account becomes connected. This is a result of the Folder::canSyncChanged and i don't see any platform specific code in there.

**Comment by guruz** [comment]
@ogoffart See the lines in my issue, the problem is that /tmp is a symlink and therefore the canon canonicalization happens too early (before the folder exists) and therefore doesn't happen.
So it the canonicalizstion needs to happen as soon as the folder exists too.

**Comment by ogoffart** [comment]
Ah, I see,   Folder::_canonicalLocalPath should be calculated again in a slot connected to AccountState::isConnectedChanged maybe

**Comment by TheOneRing** [comment]
Can the issue still be reproduced?

**Comment by HanaGemela** [comment]
Couldn't reproduce with ownCloud 4.0.0.10490-daily20230324, mac
