### ISSUE TITLE
Reading from keychain failed with error 'Could not open wallet: other; Failed to execute program org.kde.kwalletd: No such file or directory'

### ISSUE THREAD

**Issue by ahmadsocrat** [owncloud/client#6495]
### Expected behaviour
ownCloud desktop client should have the password saved and opens immediately

### Actual behaviour
ownCloud desktop client always asks for the password at startup with the following error: 

`Reading from keychain failed with error 'Could not open wallet: other; Failed to execute program org.kde.kwalletd: No such file or directory'
`
### Steps to reproduce
1. Open ownCloud Desktop client
2. The error appears and asks to reenter your password

### Client configuration
Client version:
2.4.1+dfsg-1
Operating system:
Ubuntu 18.04
OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):
distro
Installation path of client:
default

**Comment by cheshire-mouse** [comment]
check this one
https://github.com/owncloud/client/issues/3726

you should install libgnome-keyring0

**Comment by ahmadsocrat** [comment]
I already have it installed.

**Comment by SamuAlfageme** [comment]
@ahmadsocrat this was a known limitation on Ubuntu 18.04 (see https://github.com/owncloud/client/issues/6455) and try our latest build (you have the "`dfsg-1`" version from Ubuntu repositories): 

```bash
sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_18.04/ /' > /etc/apt/sources.list.d/isv:ownCloud:desktop.list"
sudo apt-get update
sudo apt-get install owncloud-client
```

¿Does it work out for you?

**Comment by fabianbur** [comment]
the bug was reported in the Ubuntu distribution package:

https://bugs.launchpad.net/ubuntu/+source/owncloud-client/+bug/1761936

So far there is no one assigned to make a patch. Here it was fixed:

**Comment by ahmadsocrat** [comment]
All good now, thanks a lot guys.
