### ISSUE TITLE
File changes in VeraCrypt files (.hc) are not detected -> no sync

### ISSUE THREAD

**Issue by jochenwezel** [owncloud/client#6496]
### Expected behaviour
File changes in .hc files (VeraCrypt container) should be synced, too - as soon as the disk is unmounted in VeryCrypt.

### Actual behaviour
OwnCloud Client doesn't detect that there is a need to sync the file.

Please note: file size and file time stamp are NOT updated by veracrypt - maybe the reason why it's not immediately recognised. After updating last write time with following powershell script, it immediately starts re-sync: 

```powershell
$a = Get-Date
$b = Get-ChildItem ".\FileSafe.hc"

foreach ($i in $b)
{
    $i.LastWriteTime = $a
}

$b
```

### Steps to reproduce
1. Create a veracrypt-container.hc in OwnCloud, let it sync 
2. Open the veracrypt-container in VeraCrypt (mount as volume)
3. Update/add files
4. Unmount the VeraCrypt volume
5. Wait 1 minute for the OwnCloud client to check for changes in filesystem

### Client configuration
Operating system:
Windows 10 (German) with latest updates

ownCloud Client version: v2.4.1

**Comment by dragotin** [comment]
That is a known problem with Veracrypt, but there is a setting to change that:
https://sourceforge.net/p/veracrypt/discussion/features/thread/aba037cb/?limit=25#73a1

I guess this can be closed as works-as-designed.

**Comment by ogoffart** [comment]
On linux, we could also use the generation from the file system "st_gen" and if it changes we should then do a hash comparison

**Comment by guruz** [comment]
@ogoffart Is that still triggered by file watching though?
(Note the original issue is for Windows)

I'd also close as @jochenwezel needs to enable the option that @dragotin mentioned

**Comment by jochenwezel** [comment]
In principle, @dragotin is right: the veracrypt file date should be refreshed.

But the idea of @ogoffart is also great, to use the hashes of the file system - if the file system provides these hashes. It might also be an improvement for some other use cases for file changes detection, potentiallly. At least for Linux clients, it could work; for Windows systems it would usually not work unless file system support (e.g. by ReFS?) is given.

Workaround for Windows (and maybe other unsupported file systems/platforms) would be to scan for file content changes for known/pre-configured extensions (such as TrueCrypt/VeraCrypt) from time to time on low process priority.

I'm not sure if the VeraCrypt will apply feature requests for "better" support of the use case of this issue. But this use case would be great for sharing/syncing encrypted file system containers via OwnCloud which should stay encrypted on every device.

**Comment by TheOneRing** [comment]
> That is a known problem with Veracrypt, but there is a setting to change that: https://sourceforge.net/p/veracrypt/discussion/features/thread/aba037cb/?limit=25#73a1
> 
> I guess this can be closed as works-as-designed.

I agree with @dragotin .
