### ISSUE TITLE
No keychain service available on Ubuntu 18.04

### ISSUE THREAD

**Issue by jgrocha** [owncloud/client#6500]
Hi,

This recurring error is back on Ubuntu 18.04, after installing the OS and then ownCloud client from the repositories: owncloud-client 2.4.1+dfsg-1

### Expected behaviour
Passwords should be stored.

### Actual behaviour
When starting ownCloud, after reboot, there is a dialog to enter the password with the message: `No keychain service available`

### Steps to reproduce
1. Install Ubuntu 18.04
2. Install ownClient
3. Add one or more accounts to ownCloud
4. reboot

### Client configuration
Client version: 2.4.1

Operating system: Ubuntu 18.04

Client package (From ownCloud or distro) (Linux only):
gnome-keyring                                               3.28.0.2-1ubuntu1
libgnome-keyring-common                                     3.12.0-1build1
libqt5keychain1:amd64                                       0.7.0-3
ubuntu-keyring                                              2018.02.28

I've tries several workarounds from previous related errors, but none worked. I'll still trying to find a solution. I'll report back.

**Comment by jgrocha** [comment]
Thanks @fabianbur for the links provided.
`sudo apt install libgnome-keyring0` solves the problem for now.

**Comment by gitgudgithub** [comment]
Simply installing `sudo apt install libgnome-keyring0` fixed it for me too! :)

**Comment by guruz** [comment]
FYI @hefee

**Comment by luoc0815** [comment]
On Fedora (28 in my case) you do `sudo dnf install libgnome-keyring`.

**Comment by rudiservo** [comment]
if you are running the snap on ubuntu 18.04 you can solve this by running
# snap connect nextcloud-client:password-manager-service

I do not know if this is the best solution but I found it in
https://askubuntu.com/questions/1032137/nextcloud-client-complains-about-missing-keychain-at-startup

**Comment by SirJoe60** [comment]
Ubuntu 18.10 and ownCloud from repository.
Installing sudo apt install libgnome-keyring0 fixed it!
Thanks a bunch!

**Comment by skonsoft** [comment]
@rudiservo Thanks. It works for ubuntu 18.10.

**Comment by ncws** [comment]
Today I solved it as follows:
sudo apt install gnome-keyring
sudo apt install python-keyring

**Comment by i2dcarrasco** [comment]
The problem still there (at least on Fedora 31 and Ubuntu 18.04), and instaling the library fixed it.
libgnome-keyring0
libgnome-keyring

I don't understand why they don't add that library as requirement...

Best regards.

**Comment by michaelstingl** [comment]
@i2dcarrasco 2.6.1?! Distro package or ownCloud download page? Could you open new issue with the details?

**Comment by i2dcarrasco** [comment]
Hello,

Was done using the webpage steps for repository installation.

I'll try to open the issue later.

Best regards

**Comment by drginfo** [comment]
> Hi,
> 
> This recurring error is back on Ubuntu 18.04, after installing the OS and then ownCloud client from the repositories: owncloud-client 2.4.1+dfsg-1
> ### Expected behaviour
> 
> Passwords should be stored.
> ### Actual behaviour
> 
> When starting ownCloud, after reboot, there is a dialog to enter the password with the message: `No keychain service available`
> ### Steps to reproduce
> 
>     1. Install Ubuntu 18.04
> 
>     2. Install ownClient
> 
>     3. Add one or more accounts to ownCloud
> 
>     4. reboot
> 
> 
> ### Client configuration
> 
> Client version: 2.4.1
> 
> Operating system: Ubuntu 18.04
> 
> Client package (From ownCloud or distro) (Linux only):
> gnome-keyring 3.28.0.2-1ubuntu1
> libgnome-keyring-common 3.12.0-1build1
> libqt5keychain1:amd64 0.7.0-3
> ubuntu-keyring 2018.02.28
> 
> I've tries several workarounds from previous related errors, but none worked. I'll still trying to find a solution. I'll report back.

On ubuntu 18.04:
sudo apt install python-keyring python3-keyring
and restart system.
