### ISSUE TITLE
Rely on OCS' user-provisioning:apps endpoint to determine if "Activity" is enabled  

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6507]
... _à la capabilities_. Rather than letting a wild `ActivityListModel::startFetchJob()` do a `<server>/ocs/v1.php/cloud/activity` directly and: 

https://github.com/owncloud/client/blob/eae00f9969e92eca156419b21c02db31a6257889/src/gui/activitywidget.cpp#L138-L141

This is coming from https://github.com/owncloud/core/pull/31336

See for reference: https://doc.owncloud.org/server/latest/admin_manual/configuration/user/user_provisioning_api.html#instruction-set-for-apps

```
curl -X GET \
  https://localhost/ocs/v1.php/cloud/apps?filter=enabled&format=json \
  -H 'Authorization: Basic YWRtaW46YWRtaW4=' 
  -H 'OCS-APIREQUEST: true' :

{
    "ocs": {
        "meta": {
            "status": "ok",
            "statuscode": 100,
            "message": null
        },
        "data": {
            "apps": [
                "files",
                "activity",
                "comments",
                "configreport",
                "dav",
                "federatedfilesharing",
                "federation",
                "files_external",
                "files_sharing",
                "files_trashbin",
                "files_versions",
                "files_videoplayer",
                "firstrunwizard",
                "market",
                "notifications",
                "provisioning_api",
                "systemtags",
                "templateeditor",
                "updatenotification"
            ]
        }
    }
}
```

**Comment by ckamm** [comment]
@SamuAlfageme I think it makes some sense to query whether the api we want to use is available, instead of checking for a specific app. Where does depending on `/ocs/v1.php/cloud/activity` returning an error go wrong?

**Comment by SamuAlfageme** [comment]
@ckamm yeah, it makes sense. And you're absolutely right. It's just [OCS](https://www.freedesktop.org/wiki/Specifications/open-collaboration-services/) being kinda _poorly designed_ : querying anything under the `ocs/` namespace will return non-standard and broad status codes:

> Statuscode 100 means "request sucessful", **999 means "unknown request"**

For me, semantically "unknown request" **doesn't strictly mean that the app is not enabled**, but has a way broader meaning (i.e. malformed request...) and feels _weird_. Also, If such API ever returns something inside `data` field (even when the app is not enabled) - client will read it as activity IIRC. 

Let's close and tag as discussion just in case this ever changes.
