### ISSUE TITLE
Context menu for system tray icon sometimes flows off screen (Windows)

### ISSUE THREAD

**Issue by dbolton** [owncloud/client#6508]
### Expected behaviour
The context menu for system tray icon should always be visible on screen

### Actual behaviour
Sometimes the context menu appears below where where you right click (in other words: mostly off screen). This only happens to the context menu for ownCloud (the context menu for other system tray icons behave correctly)

### Steps to reproduce
1. Right click on the ownCloud system tray icon

Unfortunately this isn't 100 percent reproducible. It may be triggered by switching between a multi-screen setup to a single screen (but not every time). I've experienced this issue from time to time for more than a year. 

### Server configuration
N/A

### Client configuration
Client version: 2.4.1(build 9270)

Operating system: Windows 10 Pro, Version 1709, OS Build 16299.371

OS language: US English

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs
The client log file is empty (I'm not currently connected to the server, since my server is temporarily down).

**Comment by SamuAlfageme** [comment]
Hey @dbolton, thanks for your report! Do you happen to have a screenshot of the issue? I think we've seen this one in the past and might have been fixed on a newer version of Qt. 

Care to give a try to one of [our latest (native) MSVC builds](https://download.owncloud.com/desktop/daily/ownCloud-2.5.0-daily20180502.MSVC.159.msi)?

**Comment by dbolton** [comment]
Sorry. Since your comment I haven't been able to reproduce using the stable release of the owncloud client. I will post a screenshot the next time it happens (and continue to investigate).

**Comment by ogoffart** [comment]
I noticed that as well, also with other Qt applications.

**Comment by dbolton** [comment]
Here's a screenshot using the current stable version of the Windows desktop client (2.4.1)

![owncloud offscreen menu](https://user-images.githubusercontent.com/712270/40788619-1c343368-64b6-11e8-906e-2c06cd421bfa.PNG)

**Comment by guruz** [comment]
BTW there is a 2.5.0 alpha1 build out, maybe @dbolton wants to retry. This build has a newer Qt version (5.10.1 instead of 5.6.2)
https://github.com/owncloud/client/releases

**Comment by TheOneRing** [comment]
Seems to be fixed in recent Qt versions
