### ISSUE TITLE
Public Link - setting a password - checkmark issue

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#6512]
### Expected behaviour
Adding a public link
Setting the checkbox for password and enter one BUT do not apply it
Change the expiration date
The password checkbox should stay checked (maybe to highlight that the pwd has not been appied, it should be emptied as you start when setting the checkbox the first time )
(It does not happen when you click "Bearbeitung erlauben" instead the date)

### Actual behaviour
The password checkbox changes to unchecked

<img src="https://user-images.githubusercontent.com/3321281/39809142-440483fc-5381-11e8-979e-ff536efb2300.gif" height="365" width="300">

### Client configuration
Client version: Version 2.4.1 (build 9270)

Operating system: W10x64

OS language: DE

**Comment by SamuAlfageme** [comment]
Hmm.. is it https://github.com/owncloud/client/issues/5788 regressing? @ckamm could you take a peek on how focus is handled once again?  

I remember the creating/updating workflow discussion on https://github.com/owncloud/client/pull/5695#pullrequestreview-32304429 - For the "_empty password field with the checkbox enabled_" we could match the logic of recent https://github.com/owncloud/client/pull/6458 - i.e. uncheck the box when focusing on a different field.

**Comment by ckamm** [comment]
I suspect this is just a bug. When the result from setting the expiry date arrives, the temporary ui state around the password is overwritten.

**Comment by SamuAlfageme** [comment]
Working like a charm now 👍
