### ISSUE TITLE
2.4 branch does not compile with Qt 5.11.0, only with Qt 5.11.1: Replace deprecated qt5_use_modules in src/libsync/CMakeLists.txt:142  in the 2.4 branch

### ISSUE THREAD

**Issue by jaykijay** [owncloud/client#6517]
### Expected behaviour
Building with qt 5.11 is possible
### Actual behaviour
Build fails with:
CMake Error at src/libsync/CMakeLists.txt:142 (qt5_use_modules):
  Unknown CMake command "qt5_use_modules".
### Steps to reproduce
1. Try to build with qt 5.11

### Client configuration
Client version: latest from client_theming

Operating system: Linux 

Qt version used by client package (Linux only, see also Settings dialog): 5.11

On QT 5.11 the  qt5_use_modules call is removed. It was deprecated long time before, so it should be refactored and removed to get it working with qt >5.10

It is used here:
/src/libsync/CMakeLists.txt:142

Seems to be fixed in latest master.

**Comment by ogoffart** [comment]
This is fixed in master and 2.5. But was part of a huge refactoring of the build system in master which cannot be backported.

If the change is as imple as using target_link_libraries, we might consider changing that in the 2.4 branch.

**Comment by guruz** [comment]
@jaykijay pull requests to 2.4 branch are welcome!

**Comment by kenny-w1** [comment]
I can't make stuff that requires QT5 build with cmake now, what am I supposed to do??? Can somebody please tell me what command I am supposed to use to make things build with cmake??

-- Configuring file barrier.spec
CMake Error at src/gui/CMakeLists.txt:25 (qt5_use_modules):
  Unknown CMake command "qt5_use_modules".


what is this qt5_use_modules??? :( please someone tell me how this is supposed to work, I'm stuck and I can't find any answers on google that work..

**Comment by guruz** [comment]
@kenny-w1 compile with Qt 5.9.4

**Comment by ogoffart** [comment]
Note that Qt 5.11.1 will put it back.

**Comment by dschmidt** [comment]
@guruz This is irrelevant for 2.6.0, if at all for 2.4.x
