### ISSUE TITLE
ownCloud-nemo not working anymore after installing testpilotcloud-nemo

### ISSUE THREAD

**Issue by lefherz** [owncloud/client#6524]
### Expected behaviour
testpilotcloud-client + testpilotcloud-client-nemo can be installed next to owncloud-client + owncloud-client-nemo, and the file explorer overlays are usable for both separate sync folders.

### Actual behaviour
After I installed testpilotcloud, owncloud-client-nemo stopped working. you don't see the file explorer overlays anymore for the owncloud sync folder. they don't reappear after stopping the testpilotcloud process, or even rebooting.

### Steps to reproduce
1. sudo apt install owncloud-client owncloud-client-nemo
2. log in with owncloud-client and create a sync folder
3. sudo apt install testpilotcloud-client testpilotcloud-client-nemo
4. (log in with testpilotcloud-client and create a sync folder) <- maybe optional

### Server configuration

demo.owncloud.org

### Client configuration
Client version: 2.4.1

Testpilotcloud version: 2.5.0daily20180514

Operating system: Xubuntu 18.04

OS language: english

Qt version used by client package (Linux only, see also Settings dialog): 5.6.2

Qt version used by testpilotcloud package: 5.10.1

Client package (From ownCloud or distro) (Linux only): all packages from ownCloud repos

Installation path of client: both /usr/bin

**Comment by michaelstingl** [comment]
related: https://github.com/owncloud/client/issues/5976

@jnweiger could you have a look?

**Comment by lefherz** [comment]
I fixed it locally:

1. uninstalling testpilotcloud-client-nemo
2. restarting owncloud process
3. restarting nemo process

Now it works for my ownCloud directory again - but not for my testpilotcloud directory, of course.

**Comment by guruz** [comment]
@ogoffart @ckamm Please triage

**Comment by guruz** [comment]
@lefherz Can you retest with out 2.5 nightlies?

**Comment by jnweiger** [comment]
without?

**Comment by ogoffart** [comment]
> @lefherz Can you retest with out 2.5 nightlies?

> without?

I guess he meant "our"

**Comment by guruz** [comment]
I did mean 'our'

**Comment by guruz** [comment]
2.5.0 beta1 is out :-)
https://central.owncloud.org/t/desktop-sync-client-2-5-0-beta1-released/14667
@lefherz  please comment here if we can close this issue. Thank you.

**Comment by lefherz** [comment]
it worked after I killed and restarted the nemo process :) thanks a lot!

**Comment by lefherz** [comment]
ah, I should add:

```
emil@xubuntu-18:~$ testpilotcloud --version
testpilotcloud version 2.5.0beta1 (build 9904)
Git revision d1a468eda916484aa78d04443956728e4f1d19ae
Using Qt 5.10.1, built against Qt 5.10.1
Using 'OpenSSL 1.0.2n  7 Dec 2017'
emil@xubuntu-18:~$ owncloud --version
ownCloud version 2.4.2 (build 9883)
Git revision d6e9755121c22b8033d18d496b0e59b7bb752b62
Using Qt 5.6.2, built against Qt 5.6.2
Using 'OpenSSL 1.0.2n  7 Dec 2017'
```
