### ISSUE TITLE
Sever replied: "423 Locked"

### ISSUE THREAD

**Issue by apach3guy** [owncloud/client#6528]
Owncloud 9.1.8 on Raspbian. My issue is exactly as described here:

https://central.owncloud.org/t/file-is-locked-how-to-unlock/985

I followed the steps to manually disable the lock including turning on maintenance mode and TRUNCATING the oc_file_locks table. I have also rebooted the OS. The issue persists.

**Comment by michaelstingl** [comment]
@apach3guy 9.1.x is EOL (https://github.com/owncloud/core/wiki/Maintenance-and-Release-Schedule)

**Comment by apach3guy** [comment]
I see. Well, issue appears to have cleared for now at least.

**Comment by ckamm** [comment]
Would belong into https://github.com/owncloud/core/ if not EOL
