### ISSUE TITLE
[Windows 7] Crashes leave qtsingleapplication-*-lockfile in the temp directory

### ISSUE THREAD

**Issue by AnrDaemon** [owncloud/client#6535]
It seems, OwnCloud does not cleanup after itself.
I only reboot my system once or twice a month, so I only have a handful of these files around, but on my coworkers' machines that rebooted multiple times a day, these files are multiply like rabbits.

**Comment by ckamm** [comment]
On normal shutdown the file will be removed. Crashes do indeed lead to left-over files in the temp directory.

**Comment by ogoffart** [comment]
We probably should upgrade qtsingle application to the last solution based on Qt 5, which use QLockFile instead of this custome lock file mechanism.
I don't know if it will fix this problem tough.

**Comment by AnrDaemon** [comment]
Crashes? Who said anything about crashes?
Please don't edit the report if you don't understand the issue.

**Comment by ogoffart** [comment]
@AnrDaemon  owncloud does clean after itself. It only is a problem if the owncloud client is not terminated properly. For example, because of a crash, or if the computer was shut down without closing the client.

**Comment by AnrDaemon** [comment]
The logoff/shutdown process is well documented, all window messages posted through it are known, if you ignore them (or your library ignore them) it is your problem to fix, and you can fix it.

**Comment by guruz** [comment]
@AnrDaemon which Windows version?

**Comment by TheOneRing** [comment]
We now use kdsingleapplication which should work better.
