### ISSUE TITLE
Large remote shares get synced by default when its size is "Pending" 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6536]
Yet another issue explained by the _mighty_ @cdamken. I believe it's **quite related to fed. shares performance** (ref. https://github.com/owncloud/enterprise/issues/2512) - but a client workaround might be also in place. 

### Steps to reproduce
Having the "_Ask for confirmation before synchronizing folders larger than 500MB_" setting enabled:

1. Create a folder that contains large subfolders (> 500MB) on ownCloud instance "`A`"
2. Sync a user on a remote instance "`B`" 
3. Share the folder in "`A`" with `user@B (remote)`
4. Accept the share in the client -> size on the folder's `PROPFIND` might be "pending" 

### Expected behavior
Since individual sizes on sub-folders are available but total root size is not; the client could wait for the full remote discovery to be carried out and **calculate its own "full virtual tree size" to determine whether these kind of conditions might met** 

### Actual behavior
- The accepted fed. share is included on the "selective sync list" by default (as designed*) and therefore: 
- The large subfolders appear on the "Confirmation area" (account's bottom part) one by one, stacking instead of getting just **one confirmation** for the container folder.

*: would it be interesting to introduce a new "_do not sync (remote) shares by default_" as we do for mounted storages? (https://github.com/owncloud/client/pull/5340) -> rel. to #6378 cc/ @hodyroff @pmaier1

**Comment by TheOneRing** [comment]
Removed in https://github.com/owncloud/client/pull/11517
