### ISSUE TITLE
build owncloud mac desktop client can't find WebKitWidgets

### ISSUE THREAD

**Issue by edsgershao** [owncloud/client#6540]
**Expected behaviour**
Building with qt 5.10.1 on mac  is possible

**Actual behaviour**
Build fail with qt 5.10.1
shaorongjiedeMacBook-Pro:client shaorongjie$ cmake -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_INSTALL_PREFIX="/Users/shaorongjie/Documents/OwnCloud_Client/client/client-build"
-- Build of crashreporter disabled.
-- GIT_SHA1 394ef439e0c05a74b6e79889b2ea15ff6f9d5eee
-- Could NOT find Sparkle (missing: SPARKLE_INCLUDE_DIR SPARKLE_LIBRARY) 
-- Could NOT find INOTIFY (missing: INOTIFY_INCLUDE_DIR INOTIFY_LIBRARY_DIR) 
-- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE) 
-- Could NOT find PdfLatex (missing: PDFLATEX_EXECUTABLE) 
-- Using own sqlite3 from /Users/shaorongjie/Documents/OwnCloud_Client/client/src/3rdparty/sqlite3
-- Using own sqlite3 from /Users/shaorongjie/Documents/OwnCloud_Client/client/src/3rdparty/sqlite3
-- OWNCLOUD_SIDEBAR_ICONS: owncloud: /Users/shaorongjie/Documents/OwnCloud_Client/client/theme/colored/16-owncloud-sidebar.png;/Users/shaorongjie/Documents/OwnCloud_Client/client/theme/colored/18-owncloud-sidebar.png;/Users/shaorongjie/Documents/OwnCloud_Client/client/theme/colored/32-owncloud-sidebar.png;/Users/shaorongjie/Documents/OwnCloud_Client/client/theme/colored/36-owncloud-sidebar.png;/Users/shaorongjie/Documents/OwnCloud_Client/client/theme/colored/64-owncloud-sidebar.png
-- Could NOT find Qt5WebKitWidgets (missing: Qt5WebKitWidgets_DIR)
CMake Warning at src/gui/CMakeLists.txt:307 (find_package):
  Found package configuration file:

    /usr/local/opt/qt/lib/cmake/Qt5/Qt5Config.cmake

  but it set Qt5_FOUND to FALSE so package "Qt5" is considered to be NOT
  FOUND.  Reason given by package:

  Failed to find Qt5 component "WebKitWidgets" config file at
  "/usr/local/opt/qt/lib/cmake/Qt5WebKitWidgets/Qt5WebKitWidgetsConfig.cmake"

  

-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE) 
-- Configuring done
CMake Error at src/gui/CMakeLists.txt:253 (add_executable):
  Target "owncloud" links to target "Qt5::WebKitWidgets" but the target was
  not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?

-- Generating done
-- Build files have been written to: /Users/shaorongjie/Documents/OwnCloud_Client/client

**Steps to reproduce**
Try to build with qt 5.10.1
Client configuration
Client version: latest from client_theming

Operating system: mac OS

when i build owncloud mac desktop client following https://doc.owncloud.org/desktop/2.3/building.html#generic-build-instructions,

It seems qt5.10.1 has not support qtwebkit, but build owncloud desktop client still needs qtwebkit . 
and I tap brew info qt. how to build owncloud mac desktop client? can some boys help me ?

**Comment by edsgershao** [comment]
shaorongjiedeMacBook-Pro:client shaorongjie$ brew info qt5
qt: stable 5.10.1 (bottled), HEAD [keg-only]
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt/5.10.1 (9,375 files, 295.1MB)
  Poured from bottle on 2018-05-22 at 10:36:36
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/qt.rb
==> Dependencies
Build: pkg-config ✔
Optional: mysql ✘, postgresql ✘
==> Requirements
Build: xcode ✔
Required: macOS >= 10.8 ✔
==> Options
--with-docs
	Build documentation
--with-examples
	Build examples
--with-mysql
	Build with mysql support
--with-postgresql
	Build with postgresql support
--without-proprietary-codecs
	Don't build with proprietary codecs (e.g. mp3)
--HEAD
	Install HEAD version
==> Caveats
We agreed to the Qt opensource license for you.
If this is unacceptable you should uninstall.

This formula is keg-only, which means it was not symlinked into /usr/local,
because Qt 5 has CMake issues when linked.

If you need to have this software first in your PATH run:
  echo 'export PATH="/usr/local/opt/qt/bin:$PATH"' >> ~/.bash_profile

For compilers to find this software you may need to set:
    LDFLAGS:  -L/usr/local/opt/qt/lib
    CPPFLAGS: -I/usr/local/opt/qt/include
For pkg-config to find this software you may need to set:
    PKG_CONFIG_PATH: /usr/local/opt/qt/lib/pkgconfig

I use command brew info qt5, has no option forv --with-qtwebkit

**Comment by ogoffart** [comment]
Well, either you need to get webkit, or you can run cmake with `-DNO_SHIBBOLETH=1`
