### ISSUE TITLE
text on the gui becomes unreadable when connect failed

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6546]
First screenshot below shows the next screen of the gui after entering login credentials.
If the credentiasl were invalid, and user presses the [Connect...] button, the screen changes to the second screenshot below. 

![40486212-ef587c14-5f60-11e8-8737-82adebd2e20f](https://user-images.githubusercontent.com/1108546/41785493-112ec9a8-7643-11e8-8af1-b6bd8db8a117.png)

Note the lines get squeezed to make room for the pink error message.  Here everything is still readable, but sometimes one can no longer decipher the texts.

Seen on Kubuntu18.04 with Plasma desktop.

**Comment by ckamm** [comment]
@jnweiger I'll check it out and will be able to reproduce the label appearing -- but how did you get to this screen with invalid credentials? That shouldn't happen as far as I know!

**Comment by michaelstingl** [comment]
Server issue/hack is needed to get stuck with this error.

**Comment by guruz** [comment]
@jnweiger fix is in alpha, feel free to test and close

**Comment by SamuAlfageme** [comment]
Still reproducible in 2.5: 

![screenshot 2018-06-04 12 25 53](https://user-images.githubusercontent.com/2644445/40912647-7d142c12-67f2-11e8-86c7-c3e04eb87842.png)

Hints to reproduce: 

- Set up mitmproxy on the client and set it to intercept all (`.*`) requests
- Get to the "Connect to ownCloud" page on the wizard and click connect
- Hit `a` to accept the request, then enter to inspect it
- Hit tab to switch to `Response` and `e` to edit, then `o` to tamper the HTTP code to e.g. 500
- Forward the response to the client (`a` to accept it)

**Comment by ckamm** [comment]
@SamuAlfageme Yes, this still happens for a multi-line error message, I had only tested with single-line errors.

The underlying problem is that this layout has no vertical wriggle room. So when an error message becomes visible and needs more space than expected there's not enough space left over all and the layout becomes squished. I'm checking whether I can give the middle spacer some shrinking flexibility.

**Comment by ckamm** [comment]
@SamuAlfageme There's a new PR to check out.

**Comment by jnweiger** [comment]
@michaelstingl @ckamm no server hackery needed. This was simply a client with preconfigured server url

**Comment by jnweiger** [comment]
reproduce attempt with https://github.com/owncloud/client/pull/6589 results in a nice little scrollbar next to the error mssage, no more squeezed widgets.
Thanks!
![grafik](https://user-images.githubusercontent.com/1108546/41794783-d350c6c2-7660-11e8-9344-856debc36358.png)
