### ISSUE TITLE
Bad translation on tray context menu (pt_BR)

### ISSUE THREAD

**Issue by lhartmann** [owncloud/client#6547]
### Expected behaviour
Log Out => Desconectar
Quit ownCloud => Fechar ownCloud

### Actual behaviour
Log Out => Sair
Quit ownCloud => Sair ownCloud

"Sair" would be a good translation for either option, but having it on both makes it impossible to distinguish.

### Steps to reproduce
1. Right click system tray icon

### Client configuration
Client version: 2.4.1 (build 9083)
Operating system: Fedora Linux 26
OS language: pt_BR.UTF-8
Qt version used by client package: 5.6.2
Client package: ownCloud-supplied repository for fedora 27.

**Comment by SamuAlfageme** [comment]
Thanks for the report @lhartmann! The translation is pulled automatically from our transifex project, so it has be fixed over there. 

Of course, if you would like improving ownCloud's translations on your language, you can head to https://www.transifex.com/owncloud-org/owncloud/ and join the translators team!

**Comment by lhartmann** [comment]
Just posted the suggestion there. Thanks for the directions.
