### ISSUE TITLE
"Checking" takes too long: make it parallel with upload/download?

### ISSUE THREAD

**Issue by lhartmann** [owncloud/client#6548]
### Expected behaviour
"Checking for changes" should be on a thread separate from upload/download, so changes can be propagated before the checking ends.

Total sync time = max(check, copy).

Even if the sync is restarted every few minutes it should eventually complete.

### Actual behaviour
"Checking for changes" runs to completion before any file is uploaded/downloaded. 

Total sync time >= check + copy.

If the sync is interrupted during checking then no files will have been copied, so checking restarts from scratch. A notebook that is power cycled faster than the checking period will never sync, same on an unreliable network.

### Steps to reproduce
1. Have a huge sync folder (mine is 52GB, 172000 files).
2. Add this sync to a new local folder, manually populated or empty makers no difference.
3. Let it sync.
4. Checking will take several hours, and restart from scratch if interrupted.

### Server configuration
Operating system: Debian GNU/Linux 8.10 (jessie)
Web server: Apache/2.4.10 (Debian)
Database: MySQL
PHP version: 5.6.33
ownCloud version: 10.0.8
Storage backend: local drive.

### Client configuration
Client version: 2.4.1 (build 9083)
Operating system: Fedora 26
OS language: pt_BR.UTF-8
Qt version used by client package: Qt 5.6.2
Client package: owncloud's repository for Fedora 27

**Comment by ogoffart** [comment]
This is a known limitation of the current sync alogitmh.

2.5 Should already improve the situation as it uses the filesystem watcher to know what has change so it does not need to re-discover everything.  But that does not help in the case of a new sync.

The long term goal is to get rid of the latest piece of csync and rewrite the discovery/reconcile algorithm so they can be done in parallel. 
https://github.com/owncloud/client/wiki/New-Discovery-Reconcile-Algorithm

**Comment by guruz** [comment]
@lhartmann https://github.com/owncloud/client/releases/tag/v2.5.0-alpha1
Can you tell your experience with that? It should improve the situation already since the long indexing run will only be done once every few hours.

For the unrealiable network that's issue https://github.com/owncloud/client/issues/2976

**Comment by lhartmann** [comment]
The long indexing run is an issue on first sync, I have never noticed it aftwerwards.

One thing that helps a lot using selective sync to download only a few folders at a time. The partial scans finish quickly, and download starts right away. Maybe this could be integrated into the default behavior?

**Comment by guruz** [comment]
@lhartmann Yep, it's on the roadmap :-)
