### ISSUE TITLE
Windows: Our DLLs don't have the company name or version

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6554]
From Process explorer:

![screen shot 2018-05-29 at 12 03 34](https://user-images.githubusercontent.com/959327/40652482-a05abd3a-6338-11e8-98b3-b61c0ce6eb42.png)
![screen shot 2018-05-29 at 12 02 09](https://user-images.githubusercontent.com/959327/40652483-a0757580-6338-11e8-8379-8811cf62e396.png)

**Comment by guruz** [comment]
Found in https://github.com/owncloud/client/issues/6553

**Comment by dschmidt** [comment]
> I think @ogoffart or @ckamm should be assigned, this is about the DLL, not about MSI/NSIS.

In this case it's not related indeed. It could be though: The dlls for the NSIS are shipped in the `client-binaries` repo and built from MSVC solution files, the dlls for MSI are built as part of the client through cmake. The `.rc` would need to be added to solution files and `CMakeLists.txt` as long as we still support NSIS and MSI.

**Comment by guruz** [comment]
Just noticed our normal DLLs don't have this either, the .exe has it. Something we want to fix? Hm.

![screen shot 2018-06-27 at 13 51 20](https://user-images.githubusercontent.com/959327/41972194-632fd338-7a11-11e8-99f1-a26b14cc730b.png)

**Comment by guruz** [comment]
It works for the Explorer DLLs:
![screen shot 2018-06-27 at 14 00 30](https://user-images.githubusercontent.com/959327/41972554-7eb9024a-7a12-11e8-8038-343fe90fb7b0.png)

**Comment by ogoffart** [comment]
I guess this would be the way to do it:
https://stackoverflow.com/questions/6693100/how-to-generate-windows-dll-versioning-information-with-cmake

Don't know if it is worth it.

**Comment by dschmidt** [comment]
@TheOneRing something we want or rather not?

**Comment by TheOneRing** [comment]
I don't really care.
@michaelstingl ?

**Comment by michaelstingl** [comment]
Yeah, I think this would look better 👍

**Comment by TheOneRing** [comment]
OK: let's do a cmake macro we can upstream to ecm
