### ISSUE TITLE
Register virtual file extension on msi 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6564]
Since now VFS is one of 2.5 killer (but experimental) features. We need to port the extension registration (see https://github.com/owncloud/client/pull/6290/commits/892615bec2cb8cd20f80b2640174428ec1d123fa for NSIS) to the msi installers to avoid: 

![virtualbox_msedge - win10_31_05_2018_13_54_38](https://user-images.githubusercontent.com/2644445/40780868-32a6df3c-64da-11e8-8f18-ab352694a285.png)

**Comment by guruz** [comment]
Shit, this is bad. https://owncloud.org/download/ mentions the .msi but it should mention the .exe then.
@lefherz @michaelstingl @jw @hurradieweltgehtunter @JKawohl Can you urgently switch the alpha1 links for Windows from MSI to EXE?
https://download.owncloud.com/desktop/testing/ownCloud-2.5.0.9736alpha1-setup.exe
https://download.owncloud.com/desktop/testing/testpilotcloud-2.5.0.9738alpha1-setup.exe

**Comment by guruz** [comment]
@SamuAlfageme If one picks "owncloud" in this Windows dialog for the file to open this with, it will work?

**Comment by SamuAlfageme** [comment]
@guruz yup; it does. It manually registers the extension as we'd like to automate on installation time.

**Comment by WhiteBahamut** [comment]
But shouldn't be there the original files extension? at least in OneDrive I see for my place holder files the original extension. So it is automatically registered with the correct program

**Comment by guruz** [comment]
@WhiteBahamut Still work in progress :)
Also with ownCloud it is opened with the correct program, first .owncloud is opened by owncloud.exe, then the real file is downloaded, then the correct program opens the real file. If this is not the case for you it's a bug -> create a new issue please

**Comment by SamuAlfageme** [comment]
Great job @dschmidt!! 🎉 

Just tested w/ today's master daily (`2.6.0daily20180611`) and works like a charm. This might call for a 2.5beta/rc1 - cc/ @guruz
