### ISSUE TITLE
german minor Translation issue

### ISSUE THREAD

**Issue by NGonka** [owncloud/client#6566]
https://github.com/owncloud/client/blob/a0a6e9fabc4ced57fa6077ebdda1eb677c812720/translations/client_de.ts#L1063

It should say: "Empfange Ordnerliste vom Server..."

**Comment by SamuAlfageme** [comment]
Thanks for the report! The translation is pulled automatically from our transifex project, so it has be fixed over there. 

Of course, if you would like improving ownCloud's translations on your language, you can head to https://www.transifex.com/owncloud-org/owncloud/ and join the translators team!

**Comment by NGonka** [comment]
Thanks for the hint. I see if i can help over there.
