### ISSUE TITLE
Nextcloud client Version 2.3.3  - Add option to add or chnge server url and account info...

### ISSUE THREAD

**Issue by Dutchglory** [owncloud/client#6571]
Nextcloud client Version 2.3.3  
installed from: https://m4lvin.github.io/nextcloud-client-debian-packaging/

Please add option to add or change server url and account info (username and pass)
there' s no way to re-configure nextcloud server url and account info...

**Comment by karakayasemi** [comment]
You are in ownClud/client repository. You should open this issue in Nextcloud repository.

**Comment by guruz** [comment]
> Nextcloud client Version 2.3.3

That is super old. ownCloud is already at 2.5.0 alpha1. https://github.com/owncloud/client/releases/tag/v2.5.0-alpha1
It also has a nice new feature: https://central.owncloud.org/t/owncloud-virtual-file-system-discussion/13823/10

> Please add option to add or change server url and account info (username and pass)

You can edit the config file: https://doc.owncloud.org/desktop/2.5/advancedusage.html

@ckamm @SamuAlfageme  Should there be a menu entry that opens the documentation to show how to change the URL? Maybe a FAQ entry? hmmm
(Note for branded clients we must not show this entry)

**Comment by SamuAlfageme** [comment]
Good ol' https://github.com/owncloud/client/issues/6376 

@guruz @ckamm I'm not sure about a menu entry - FAQ entry however can be of use, yup.

**Comment by ckamm** [comment]
Yes, let's add it to the faq
