### ISSUE TITLE
2.5.0alpha: Doc installed three times.

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#6572]
### Expected behaviour
Documentation is installed once.

### Actual behaviour
All documentation is installed three times into the directories, here for example the file advancedusage.html (but all other files also):

```
/usr/share/doc/client/owncloud-client/html/unthemed/advancedusage.html
/usr/share/doc/client/owncloud-client/html/org/advancedusage.html
/usr/share/doc/client/owncloud-client/html/com/advancedusage.html
```

Ihe the .com doc supposed to be in here? What is the difference between unthemed and org?

### Steps to reproduce
Build the package for openSUSE in  a spec file, using this sequence:

```
%build

# http://www.cmake.org/Wiki/CMake_RPATH_handling#Default_RPATH_settings
%cmake .. -DWITH_DOC=TRUE \
  -DKDE_INSTALL_USE_QT_SYS_PATHS=1 \
  -DCMAKE_C_FLAGS:STRING="%{optflags}" \
  -DCMAKE_CXX_FLAGS:STRING="%{optflags}" \
  -DCMAKE_SKIP_RPATH=OFF \
  -DCMAKE_BUILD_TYPE=RelWithDebInfo \
  -DCMAKE_INSTALL_PREFIX=%{_prefix} \
%if %{_lib} == lib64
  -DLIB_SUFFIX=64 \
%endif
  %cmake_args

env LD_RUN_PATH=%{_libdir}/owncloud:%{_libdir}/owncloud make %{?_smp_mflags} VERBOSE=1

make doc
make doc-man

%install
%cmake_install

```

This is probably not specific to package building.

**Comment by guruz** [comment]
AFAIK @settermjd and @SamuAlfageme had a WiP for this..

**Comment by SamuAlfageme** [comment]
Commented in https://github.com/owncloud/client/pull/6510#issuecomment-396309626

**Comment by ogoffart** [comment]
Is this still a problem?

**Comment by HanaGemela** [comment]
@pmaier1 what is the expected result? What documentation should I see in what location?

**Comment by jnweiger** [comment]
## tested with owncloud-client-2.6.0~alpha2-lp150 on opensuse leap 15.0
```
zypper addrepo https://download.opensuse.org/repositories/isv:ownCloud:desktop:testing/openSUSE_Leap_15.0/isv:ownCloud:desktop:testing.repo
zypper ref
zypper install owncloud-client owncloud-client-doc

rpm -ql owncloud-client | grep html
rpm -ql owncloud-client-doc | grep html
```

We don't ship html documentation at all with client version 2.6.0 -- that is okayish.

**Comment by jnweiger** [comment]
@guruz I think @dragotin did a manual build, and found that this also prepares the documentation trees for owncloud.org, owncloud.com and an unthemed tree. This is redundant, but is not meant for an end user anyway.

**Comment by guruz** [comment]
I'm moving this issue

**Comment by ogoffart** [comment]
Is this still a problem now?

**Comment by dragotin** [comment]
Not longer relevant.
