### ISSUE TITLE
Could not create file & directory

### ISSUE THREAD

**Issue by qtechsandesh** [owncloud/client#6580]
### Expected behaviour
It should create file or folder 

### Actual behaviour
showing error"Could not create file "

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system: Ubuntu Server 16.04 LTS 

Web server: apache2

Database:MySql server

PHP version:php 7.0

ownCloud version: 10.0.4

Storage backend (external storage):

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
You gave nearly no information. Please fill out the issue template, then we can re-open.
