### ISSUE TITLE
Investigate white UI text

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6581]
Also seen by @SamuAlfageme 

![image](https://user-images.githubusercontent.com/833306/41340205-1cef13a4-6ef7-11e8-89e7-119c940d711b.png)

Some normal ui text is white in this screenshot. Also something is up with the sync scheduling - for me it's stuck in "Preparing to sync" permanently.

**Comment by ckamm** [comment]
This problem is odd. Using entirely new build directories each time I could initially reproduce it and gradually bisected through the recent commits. Then it was gone and is now also gone on the head of the 2.5 branch, I can not make it appear again.

I would guess at something timing / memory corruption related (why would the text go white?) but don't understand why it's now consistently gone for me.

@ogoffart The patches I thought might be related were 76bb76a59e6633b9a38c7a0e36d8e51efc7a4047 and 888f2aae2f31cb16ca8aa370ff44222d618bc146 - since not much else changed between 2.5.0-alpha1 and 2.5 - but I don't see anything wrong with them.

**Comment by ckamm** [comment]
Another recompile without even changing code (just dependencies) and I reproducably get this on startup:
![image](https://user-images.githubusercontent.com/833306/41347127-fefb3db6-6f08-11e8-9653-ed53bedd5cb8.png)

**Comment by ckamm** [comment]
The bug is in 13cb9ab1c5e645d1103254a8ef00273e87f67044 (download doesn't complete) and it was occasionally invisible when the file was blacklisted for a while.

**Comment by ckamm** [comment]
@SamuAlfageme fixed in 2.5

**Comment by guruz** [comment]
Did @SamuAlfageme manage to test this? I remember seeing something about this in an enterprise ticket

> Some normal ui text is white in this screenshot. 

Where was this fixed?

**Comment by ckamm** [comment]
The odd white text wasn't fixed. It's possible that could still happen. What was fixed was the sync getting stuck - and with that no white text is visible anymore.

**Comment by ogoffart** [comment]
White text was fixed in  36ca910d339fbb40eb9aeb225292af8b06258806
