### ISSUE TITLE
Group administration views not working with space char in group name

### ISSUE THREAD

**Issue by jochenwezel** [owncloud/client#6587]
I've created some groups. Group views work if they don't contain a space character in the group name.
![image](https://user-images.githubusercontent.com/3033827/41419377-2628ea66-6ff2-11e8-8f51-a8aa3ffd04d5.png)

### Expected behaviour
The group "CM Staff" in screenshot above should contain 6 users and show them in the list.

### Actual behaviour
As soon as I've got a space char in the group name, the group view doesn't list any users any more.
The group "CM Staff" in screenshot above should contain 6 users, but the list is empty.
Other groups without space chars in group name work as expected.

### Server configuration
Operating system: Ubuntu 

Web server: Apache

Database:

PHP version:

ownCloud version: 10.0.8

Storage backend (external storage):

### Client configuration
Client version: Google Chrome Browser

Operating system: Windows

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

**Comment by ogoffart** [comment]
Hi, This is the bug tracker for the desktop client.
However, this bug does not seem related.
I suppose this should go in the server component, so please copy your bug report in https://github.com/owncloud/core/issues
