### ISSUE TITLE
Add "Settings > General: Experimental" section 

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#6590]
### Things to include:

- [ ] Conflict upload / resolution interface #5896 
- [ ] ownCloud Virtual Files mode https://github.com/owncloud/client/pull/6290
- [ ] Delta Sync https://github.com/owncloud/client/pull/6297
- [ ] ...

**Comment by ogoffart** [comment]
The general settings tab is to tall. we need to take "about" out of the general settings tab before adding more settings. (https://github.com/owncloud/client/issues/6075)

Note that virtual files is not a "general settings" since it is activated per folder in the wizard.

**Comment by SamuAlfageme** [comment]
@ogoffart I meant the general feature switch - equivalent to `showExperimentalOptions` in https://doc.owncloud.org/desktop/2.5/advancedusage.html#configuration-file

**Comment by guruz** [comment]
One idea was to have visible only for branding "ownCloud" and if the update channel is on 'beta'. But for testpilotcloud always visible.

**Comment by ogoffart** [comment]
The `showExperimentalOptions` is meant to be a hidden option.
If it is not hidden, we would simply show the experimental checkbox in the UI. (they are marked with "experimental" after all.

**Comment by ogoffart** [comment]
done  (for delta sync)
