### ISSUE TITLE
Ubuntu Client Loses connection when resuming from sleep/suspend

### ISSUE THREAD

**Issue by xabispacebiker** [owncloud/client#6595]
The desktop client from ubuntu software center (2.1.1) on ubuntu 16.04 64 bit (and 32 bit) does not reconnect to the server when resuming from sleep.

### Expected behaviour
Tell us what should happen

Client should reconnect automatically

### Actual behaviour
Tell us what happens instead

I get the message No connection to ownCloud at https://urlhere. Network access is denied

I have to close the app and reopen it to restore functionality.

I might add that I have accidentally lost files because I did not notice this at first. We use this at work fro a large number of users so it is quite a big bug!

On openSUSE 42.1 it works fine. Just ubuntu it does not (with same client version).

### Steps to reproduce
1. Put PC to sleep
2. Wake up PC
3. It's broken (No connection to ownCloud at https://urlhere. Network access is denied).

### Server configuration
Operating system:

Web server: Debian stretch (Apache2)

Database: MariaDB (MySQL)

PHP version: 7.0

ownCloud version: 9.1

Storage backend (external storage):

### Client configuration
Client version: 2.1

Operating system: Elementary OS (Ubuntu)

OS language: Spanish

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by SamuAlfageme** [comment]
> Client version: 2.1

@xabispacebiker thanks for reporting! Could you please try out a newer version of the client from https://owncloud.org/install/#install-clients? Lots of cool things have improved since then and it's interesting to know if you're still able to reproduce such issues with 'em. 

Feel free to reopen if you observe the same behavior there!
