### ISSUE TITLE
Release 2.4.2 (bugfixes and updater-in-between-step for EXE->MSI)

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6599]
Some weeks before the release:
* [x] Check if we should update the bundled sqlite3 (https://github.com/owncloud/client/tree/master/src/3rdparty/sqlite3)
* [x] Check if we should update Sparkle on build machine (https://github.com/sparkle-project/Sparkle/releases)
* [x] Ensure NSIS is up to date on the build machine
* [x] Ensure up-to-date dependencies (e.g. [latest Qt version](http://qt-project.org/downloads#qt-lib) is installed on the machine and picked up (cmake output)
* [x] Ensure the crash reporter server is up
* [x] Check crash reporter for bad crashes
* [x] Ensure Windows Overlay DLLs are rebuilt
* [x] Check nightly builds are up and running, that is Jenkins jobs ownCloud-client-linux, ownCloud-client-osx and ownCloud-client-win32 all green.
* [x] Ensure Linux nightlies are built too for all distros https://build.opensuse.org/package/show/isv:ownCloud:community:nightly/owncloud-client
  * Check if patches still apply in the linux packages
* [ ] Build branded clients through the scripting machine and smoke test one or two branded clients (especially with predefined url)
* [ ] Upload a nightly build of the windows version to virustotal.com
  * Contact AV vendors whom's engine reports a virus
* [x] Documentation should be online before the release http://doc.owncloud.org/desktop/1.X/
* [ ] QA goes over https://github.com/owncloud/mirall/wiki/Testing-Scenarios
* [x] Make sure to have `client/ChangeLog` updated
 * use `git log --format=oneline v<lastrelease>...master` if your memory fails you
* [x] check if enterprise issues are fixed

For first Alpha/Beta of a Major or Minor release:
* [ ] branch off master to new version branch (e.g. master -> 2.1, when releasing 2.1)
* [ ] Adjust `VERSION.cmake` in master and count up (e.g. 2.2)
* [ ] Adjust translation jobs for [client](https://ci.owncloud.org/view/translation-sync/job/translation-sync-client/) and [NSIS](https://ci.owncloud.org/view/translation-sync/job/translation-sync-client-nsis/) to point to the release branch (e.g. 2.1).
* [ ] Make sure there is a job for the docs of the new master branch and the current release branch on rotor e.g. http://doc.owncloud.org/desktop/1.X/ exists

For all alphas, betas and RCs (Copy this section for each alpha/beta/rc):
* [x] Add last updates to Changelog in the client source repository.
* [x] Branch off a release branch called VERSION-rcX or VERSION-betaX  (without v, v is for tags)
* [x] Edit ```VERSION.cmake``` to set the suffix to beta1, beta2 etc. Commit the result to the release branch only
* [x] Make sure to increase the version number of the branched of release, e.g. if you release 2.3.2 then you should change VERSION.cmake in 2.3 to 2.3.3 since that branch now will be 2.3.3
* [x] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'ownCloud'
* [x] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'testpilotcloud'
* [ ] Only now download the last created source .tar.xz and sign it with gpg. Copy the signature into a new .asc file. (timing issue because currently 'testpilotcloud' re-creates the source .tar.xz)
* (no need to copy builds as they are already in testing directory or repository) (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [x] Mac: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Win: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Smoke test of one distro package (Install, make sure it does not explode, and check if all version indicators are correct)
* [X] Linux: Run @SamuAlfageme 's magic Linux-test-all-packages-script
https://jenkins.int.owncloud.com/view/client/job/client-linux-tests/75/console 
* [x] Create a signed tag using ```git tag -u E94E7B37 tagname``` (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [ ] Create a pull request to the owncloud.org repository to update the install page (strings.php, page-desktop.php) and the changelog on owncloud.org. From now on download packages from the staging webserver.
* [ ] Inform packagers @dragotin (openSUSE), @hefee (Debian), ??? (Fedora)
* [ ] Announce on https://central.owncloud.org
* [ ] Inform community mailinglists devel@owncloud.org and testpilots@owncloud.org (make sure to mention it is an rc). Link to the central post so discussion happens there.
* [ ] Check crash reporter

One week before the final release:
* [ ] Communicate the release schedule on mailinglist release-coordination@owncloud.com. Give a high level overview of the upcoming new features, changes etc.
* [ ] Ensure marketing is aware (marketing@owncloud.com) and prepared for the release (social, .com website, cust. communications)
* [ ] Inform GCX knows the next version is about 1 week out (gcx@owncloud.com)

Day before final Release:
* [ ] Check the translations coming from transifex: All synchronized?
* [ ] Run the tx.pl scripts on the final code tag
* [ ] Run ```make test```
* [ ] Run smashbox
* [ ] Inform product management and marketing that we are 1 day out

On Release Day (for final release):
* [x] Add last updates to Changelog in the client source repository.
* [x] Branch off a release branch called VERSION  (without v, v is for tags)
* [x] Edit ```VERSION.cmake``` to set the suffix to "" etc. Commit the result to the release branch only
* [x] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'ownCloud'
* [x] Create build for using owncloud-client-trigger (uncheck the "nightly build" checkbox, use the proper dropdown for version suffix) for theme 'testpilotcloud'
* [x] Only now download the last created source .tar.xz and sign it with gpg. Copy the signature into a new .asc file. (timing issue because currently 'testpilotcloud' re-creates the source .tar.xz) (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [ ] Branch isv:ownCloud:desktop to isv:ownCloud:desktop:client-X.Y.Z before overwriting https://github.com/owncloud/administration/blob/master/jenkins/obs_integration/obs-backup-prj.sh (the linux packages will land in the :testing repository still)
  ```obs-backup-prj.sh isv:ownCloud:desktop isv:ownCloud:desktop:client-2.4.1 owncloud-client 2.4.1 # (if not already done)```

* [x] Re-download Mac builds and check signature. Interactive in installer window
* [x] Re-download Win build check signature. From Mac or Linux: ```osslsigncode verify ownCloud-version-setup.exe```
* [x] Mac: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Win: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Smoke test of one distro package (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Run @SamuAlfageme 's client-linux-tests Jenkins job (this tests only package installations!) Adjust REPO_URL to say `...:/desktop:/testing` in https://jenkins.int.owncloud.com/job/client-linux-tests/build (Better: gitlab? no alternative yet: that uses github)
https://jenkins.int.owncloud.com/view/client/job/client-linux-tests/75/console 
* [x] Win/Mac Copy builds from ```testing``` to ```stable``` on download.owncloud.com, double check the download links. (make sure the .asc is there too)
* [x] Linux: disable publishing on project isv:ownCloud:desktop
* [x] Linux: Use https://github.com/owncloud/administration/blob/master/jenkins/obs_integration/obs-deepcopy-prj.sh to copy from isv:ownCloud:community:testing to isv:ownCloud:desktop
  ```obs-deepcopy-prj.sh isv:ownCloud:desktop:testing isv:ownCloud:desktop```
  ```obs-deepcopy-prj.sh isv:ownCloud:testpilot:testing isv:ownCloud:testpilot```
* [x] Linux: Re-enable OBS publishing on the project after official release date and if all distros build (check for accidentially disabled packages too) 
* [ ] Linux: Wait until everything is built and published, then disable publishing on project isv:ownCloud:desktop
* [x] Create git signed tag in client repository using ```git tag -u E94E7B37 tagname``` (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [x] Create a (draft) release on https://github.com/owncloud/client/releases
* [ ] Update https://owncloud.org/changelog/desktop-client/
* [x] Update https://owncloud.org/download/#owncloud-desktop-client -> Download ownCloud -> click open 'Desktop Client', edit win/mac/lin, each all three tabs "Production", "Technical Preview" [disabled], "Test pilot" 
* [x] Announce on https://central.owncloud.org
* [ ] Announce on announcements@owncloud.org Link to the central post so discussion happens there.
* [x] Inform packagers @dragotin (openSUSE) @hefee (Debian) @Germano0 (Fedora)
* [ ] Send out Social (tweet, blog, other)
* [ ] Send out customer communication (if any)
* [x] Inform GCX that the new version is released (gcx@owncloud.com)
* [x] Inform release-coordination@owncloud.com
* [x] Ensure marketing is aware (marketing@owncloud.com)
* [ ] Take pride and celebrate!
* [ ] Tell GCX to increment the minimum supported version for enterprise customers
* [ ] Check if minimum.supported.desktop.version (https://github.com/owncloud/core/blob/master/config/config.sample.php#L1152) needs to be updated in server

15 minutes after after release:
* [ ] Test all advertised download links to have the expected version
* [x] Check for build errors in OBS, do
```obs-deepcopy-prj.sh isv:ownCloud:desktop isv:ownCloud:desktop:client-2.X.X```
* [ ] disable publishing in OBS to prevent that accidential rebuilds hit the end users.

A few days after the release (for final release)
* [ ] Review changes in the release branch, merge back into master
* [ ] check the crash reporter if auto update is a good idea or we need a new release
* [x] Update the updater script ```clientupdater.php``` https://github.com/owncloud/enterprise/wiki/How-to-use-the-Client-Updater#updating-the-owncloud-hosted-updater
* [ ] Execute announced deprecations. Disable builds for deprecated platforms. Update accordingly: https://doc.owncloud.org/server/latest/admin_manual/installation/system_requirements.html#desktop
* [ ] Increment version number in nightly builds. Special case: after the last release in a branch, jump forward to the 'next release branch'... That may mean, this is nightly is the same as edge then.

CC @ogoffart @dschmidt @ckamm

**Comment by guruz** [comment]
Blocking: https://github.com/owncloud/client/issues/6603

**Comment by guruz** [comment]
Blocking: https://github.com/owncloud/client/issues/6609

**Comment by guruz** [comment]
I can properly update a 2.4.2 unstable to 2.5.0 unstable.
So we can have a go at releasing 2.4.2
@michaelstingl @ogoffart @ckamm @jnweiger

**Comment by jnweiger** [comment]
currently https://build.opensuse.org/package/live_build_log/isv:ownCloud:Qt562:2.4.0/ocqt562+240-qt5-qtbase/openSUSE_Leap_15.0/x86_64
fails in obs. investigating, but should not be a blocker for 2.4.2

**Comment by dragotin** [comment]
Ahh, I see, you guys having fun with your own Qt version.... Probably the distros SSL is too old?

**Comment by guruz** [comment]
@dragotin too old or too new?
I see for Leap 15.0:
```
[    5s] cycle: libopenssl-1_1-devel -> libopenssl-devel
[    5s]   breaking dependency libopenssl-devel -> libopenssl-1_1-devel
```

@jnweiger Now OBS shows an error in a message box when I click on the "unresolvable" openSUSE_Leap_15.0:
https://build.opensuse.org/package/show/isv:ownCloud:desktop:daily:2.4/owncloud-client
> nothing provides libicui18n.so.59.1()(64bit) needed by ocqt562+240-libQt5Core5, nothing provides libicuuc.so.59.1()(64bit) needed by ocqt562+240-libQt5Core5, nothing provides libicui18n.so.59.1()(64bit) needed by ocqt562+240-libqt5-qtwebkit, nothing provides libicuuc.so.59.1()(64bit) needed by ocqt562+240-libqt5-qtwebkit

**Comment by dragotin** [comment]
The unresolveable issues probably means that the libicu library, that the ocqt562 is built against, is not longer available on Leap15 and Tumbleweed. Probably these two went to a later version. That should be visible in the build process of the ocqt562 somehow. I am sure domme knows.

**Comment by guruz** [comment]
FYI @dschmidt @crrodriguez

**Comment by jnweiger** [comment]
the easy answer is: Leap 15 is supported with 2.5, but not with 2.4.x ....

**Comment by michaelstingl** [comment]
> Leap 15 is supported with 2.5.0 and up, but not with 2.4.x ....

fine for me

**Comment by jnweiger** [comment]
victory: 
leap15 and tumblweed builds now succeed. using ssl 1.0.2n (and other silly hacks...).
The libicu issues were indeed misleading nonsense only. pffft.
https://build.opensuse.org/package/show/isv:ownCloud:desktop:daily:2.4/owncloud-client

Pushing the fixes into our internal build service now.

**Comment by guruz** [comment]
Wow, thanks @jnweiger :)

**Comment by guruz** [comment]
https://github.com/owncloud/client/releases/tag/v2.4.2-rc1
FYI @dragotin @hefee

**Comment by guruz** [comment]
https://central.owncloud.org/t/desktop-sync-client-2-4-2-rc1-released-release-candidate/14408

**Comment by guruz** [comment]
https://download.owncloud.com/desktop/testing/owncloudclient-2.4.2-rc1.tar.xz

**Comment by guruz** [comment]
btw, old versions will just go to 250exe. Then 250ex can go to 251msi.

**Comment by michaelstingl** [comment]
> old versions will just go to 250exe

Now I'm confused again. Could you elaborate? What are the implications for people running own update server?

**Comment by jnweiger** [comment]
As far as I can tell all combinations should work. Please correct me if I am wrong.,

**Comment by guruz** [comment]
> Now I'm confused again. Could you elaborate? What are the implications for people running own update server?

I just meant we could do this if we wanted. But maybe it's better to supply only 250 msi so everyone has to go via 242 exe first. :-)

**Comment by guruz** [comment]
> @jnweiger wrote 241exe -> 250msi works fine too. No need to install a magic.exe version first.

Yes it works if you as a humanoid double click the 250msi in the explorer.exe
it does NOT WORK in 241 exe when using our auto updater. Because 241 exe has no idea what to do with a msi file (and also won't even get a link to the msi file as we prevent that in the auto updater PHP). It will however work with the magic 2.4.2 release exe that we're going to release today ;-)

**Comment by jnweiger** [comment]
my test yesterday was wrong. 
In the case '241exe -> 250msi' this is what actually happens:
 * when the client starts, the update is advertised with a 'ignore, not now, get update' -- when I click 'get update', my browser is sent to the download page. That is a semi manual install, it works, if the user locates the correct download link on the webpage.
 * when I open the general tab in the settings, the update is advertised with a 'Restart & Update button' When I click this, the client shuts down, a window flashes briefly, and nothing more happens. No error messages.

I missed that issue yesterday. Sorry. 

So the 241exe -> 250msi update does not work, and we must take care that no customers try that path.

**Comment by guruz** [comment]
> when I open the general tab in the settings, the update is advertised with a 'Restart & Update button' When I click this, the client shuts down, a window flashes briefly, and nothing more happens. No error messages.

This is not a possible if you use the real updater PHP as
.exe belongs into: client_update_checker/config-win32.php
.msi belongs into: client_update_checker/config-win32msi.php
2.4.1 will NEVER request the msi=true file.

So everything is fine I think.

**Comment by guruz** [comment]
@hefee @dragotin https://download.owncloud.com/desktop/stable/owncloudclient-2.4.2.tar.xz

**Comment by guruz** [comment]
https://github.com/owncloud/client/releases/tag/v2.4.2

**Comment by guruz** [comment]
Auto updater PR: https://github.com/owncloud/enterprise/pull/2744

**Comment by guruz** [comment]
https://owncloud.org/download/#owncloud-desktop-client-macos is updated too.

**Comment by guruz** [comment]
Sent a mail to announcements@ too.
https://mailman.owncloud.org/pipermail/announcements/2018-July/000103.html
