### ISSUE TITLE
Corrupted config file after upgrade to version 2.3.3 in Centos7

### ISSUE THREAD

**Issue by labkode** [owncloud/client#6600]
After doing an upgrade to version 2.3.3 of the cernbox client, we have seen that the configuration file is corrupted, the user field is set to *@Invalid()*, you can see the diff here:

```
> 0\http_user=hugo
8c17
< 0\user=@Invalid()
```

**Comment by guruz** [comment]
I remember having seen this bug before, but already > 1y ago.

> doing an upgrade to version 2.3.3 

@labkode @moscicki 2.3.3 is nearly a year old.
(We're about to release 2.4.2)

**Comment by ogoffart** [comment]
The upgrade is done from which version to which version?

**Comment by ogoffart** [comment]
Closing old issue. The glitch was probably caused by a very old client version, and there would be not much that can be done about it.
