### ISSUE TITLE
[Windows] I can't see the build number from the owncloud.exe

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6601]
E.g. this is from the alpha1:
<img width="374" alt="screen shot 2018-06-20 at 17 08 22" src="https://user-images.githubusercontent.com/959327/41667297-e25ba7e6-74ac-11e8-967a-2064d2e48037.png">
(I would want to see both the number and the alpha1 string)

(I didn't check yet for nightlies)

The about dialog will just display alpha1, so I can't see it there either.

**Comment by guruz** [comment]
I don't remember if the screenshot/test above was from the MSI or the EXE.

But it breaks the auto updater :) 
(Together with https://github.com/owncloud/client/issues/6618 )

**Comment by dschmidt** [comment]
The build number is now passed to the build. That you don't see it in this dialog, is a separate issue.
What would you like to see there? The full version info e.g. 2.5.0.9780-daily20180620 e.g.?

**Comment by guruz** [comment]
Moving to 2.6.0 then :)
The about dialog is fixed now and the updater does not endless-loop anymore.

**Comment by guruz** [comment]
https://github.com/owncloud/client/issues/6762#issuecomment-418633961

**Comment by dschmidt** [comment]
Passing the build number was still broken but is fixed now and this issue with it.

**Comment by guruz** [comment]
![bildschirmfoto 2018-09-05 um 14 38 47](https://user-images.githubusercontent.com/959327/45093683-72048e00-b119-11e8-9e76-5d6ce6f5fb33.png)
