### ISSUE TITLE
[Windows] EXE->MSI update doesn't launch

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6603]
I compiled 2.4 branch with my custom APPLICATION_UPDATE_URL.

I get the custom client as far as downloading the update and then restarting itself. The msi does not seem(?) to be run:

```
06-20 17:25:32:414 [ info gui.updater ]:	Downloaded "https://download.owncloud.com/desktop/testing/ownCloud-2.5.0-alpha1.MSVC.238.msi" to "C:/Users/marku/AppData/Local/ownCloud/ownCloud-2.5.0-alpha1.MSVC.238.msi"
06-20 17:28:20:028 [ info gui.updater ]:	Running updater "C:/Users/marku/AppData/Local/ownCloud/ownCloud-2.5.0-alpha1.MSVC.238.msi"
06-20 17:28:20:048 [ info gui.account.manager ]:	Saved all account settings, status: QSettings::Status(NoError)
06-20 17:28:20:097 [ debug gui.socketapi ]	[ OCC::SocketApi::~SocketApi ]:	dtor
06-20 17:28:20:097 [ info gui.socketapi ]:	Lost connection  QLocalSocket(0x604fe38)
(end of log)
```

**Comment by guruz** [comment]
Now for some reason it works. Heh. :-(

**Comment by guruz** [comment]
Added some debug, it's running the self .exe again instead of the installed MSI.
This is the same behaviour as on other platforms, I wonder if it is good like that. Hm. 

```
06-21 12:44:56:622 [ info gui.updater ]:	Running updater "C:/Users/marku/AppData/Local/ownCloud/ownCloud-2.5.0-alpha1.MSVC.238.msi"
06-21 12:44:56:622 [ debug default ]	[ OCC::OCUpdater::slotStartInstaller ]:	"&{msiexec /norestart /passive /i 'C:\\Users\\marku\\AppData\\Local\\ownCloud\\ownCloud-2.5.0-alpha1.MSVC.238.msi'| Out-Null ; &'C:\\github\\build-client\\bin\\owncloud.exe'}"
```

**Comment by guruz** [comment]
Got another issue when overwriting from 2.4.2 instead of my self compiled: https://github.com/owncloud/client/issues/6609

**Comment by dschmidt** [comment]
FTR: We could instead read the installation location from the registry and launch owncloud.exe from there. Or we could at least show a warning if the path and the installed path stored in registry don't match ... or something like that.
