### ISSUE TITLE
[Linux] build date is wrong in about page because of OBS reproducable build setting

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6608]
A freshly built 2.5.0 daily on openSUSE LEAP 15.0
shows the correct git sha sum a93f2d... but a wrong date, Mar 30 2017.
The correct date should be Jun 21 2018.
![grafik](https://user-images.githubusercontent.com/1108546/41736430-bdf8b7f0-758c-11e8-902f-e4944e31b4ec.png)

**Comment by SamuAlfageme** [comment]
@jnweiger nice catch! Those 2 macros come from the C++ compiler: 

https://github.com/owncloud/client/blob/dfb1a504485308671e4e424b3233470034d2a6b1/src/libsync/theme.cpp#L325-L326

Can you check  what's the output of`time` on the internal build machine? On macOS builds those hold the right value.

**Comment by guruz** [comment]
https://build.opensuse.org/public/build/isv:ownCloud:desktop:daily:2.5/openSUSE_Leap_15.0/x86_64/owncloud-client/_log

> [    1s] lamb51 started "build owncloud-client.spec" at Fri Jun 22 05:09:43 UTC 2018.

then in VM:

> [   59s] setting SOURCE_DATE_EPOCH=1490875200

1490875200 = 03/30/2017 @ 12:00pm (UTC)

This is related to reproducable builds. https://reproducible-builds.org/specs/source-date-epoch/

Maybe @dragotin @crrodriguez know more.

**Comment by crrodriguez** [comment]
The OBS behaviour is correct, in order to produce reproducible builds the toolchain works together with the build system and sets SOURCE_DATE_EPOCH to the last time the .changes files was modified, the preproccesor, compiler and linker honour this variable. you may also set it yourself to something that does not change on every rebuild but only on real source changes.

**Comment by guruz** [comment]
> you may also set it yourself to something that does not change on every rebuild but only on real source changes.

@crrodriguez Where would we set that? In the client? in OBS?

@jnweiger Can you try to set like in https://gist.github.com/dmerejkowsky/2e00b0d84bacdf173d6f ?

**Comment by jnweiger** [comment]
export SOURCE_DATE_EPOCH=$(git log -1 --format=%ct)

looks perfect, we already do `git rev-parse HEAD` to know where we came from.

**Comment by jnweiger** [comment]
Ah yeah, since March 2017 we neglect the changes files. I should have known that....

**Comment by crrodriguez** [comment]
@guruz It is to be set in the current enviroment..  in the case of spec files.. in the %build section. ;)

**Comment by jnweiger** [comment]
It seems the reproducable build settings are not fully reproducable in OBS. SOURCE_DATE_EPOCH only affects RPM based systems, but not DEB. Sigh.

Fixed for RPMs, ignoed for DEBs.

**Comment by crrodriguez** [comment]
@jnweiger It should work on debian packages too.

**Comment by guruz** [comment]
@crrodriguez Please help @jnweiger to fix it for DEB then :-)

**Comment by jnweiger** [comment]
https://github.com/openSUSE/open-build-service/issues/1555#issuecomment-400211886
obs blaims lack of support on deb tools. 
we should find out, if a simple dpkd-buildpackage command honors SOURCE_DATE_EPOCH, if so all will be fine when we stop using obs,
Currently all DEB builds have the current Build date, while all RPM builds show the last commit timestamp where one expects the build date. Good enough for me. I'd rather go for current build date in both cases if the debian toolchain would need fixing.
