### ISSUE TITLE
[Windows] 2.4.2 nightly EXE-> 2.5.0 alpha1 MSI update doesn't work

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6609]
Installed 2.4.2 daily.

Run with 
```
C:\Program Files (x86)\ownCloud>set OCC_UPDATE_URL=http://[...]/updater.xml
C:\Program Files (x86)\ownCloud>owncloud.exe --logfile=c:\github\oclog_msi.txt --logdebug
```
Click the 'install and relaunch'. in settings.

```
06-22 14:26:40:962 [ info gui.updater ]:	Running updater "C:/Users/marku/AppData/Local/ownCloud/ownCloud-2.5.0-alpha1.MSVC.238.msi"
```

MSI seems to be getting installed (I see a progress dialog quickly)

But then I get a broken ownCloud directory:

<img width="471" alt="screen shot 2018-06-22 at 14 34 42" src="https://user-images.githubusercontent.com/959327/41776818-77155224-7629-11e8-8643-8f5c50fba1e4.png">

-> Installation busted.

is it because I have the directory open in cmd.exe?

**Comment by guruz** [comment]
(A reboot doesn't change anything, the leftover files are there still and there is no new one)

**Comment by guruz** [comment]
Not sure if relevant, when cleaning build dir in explorer
![screen shot 2018-06-22 at 14 46 00](https://user-images.githubusercontent.com/959327/41777276-0d0ba796-762b-11e8-8b38-c4ce1b118518.png)
:

**Comment by guruz** [comment]
> is it because I have the directory open in cmd.exe?

Not related to that (but I still had it open in explorer)

**Comment by guruz** [comment]
> Not related to that (but I still had it open in explorer)

Not related to that either.
@dschmidt I can't update at all! :-/

**Comment by guruz** [comment]
When I use the "Restart & Update" button I get more files but still a broken installation.
The client seems to exit properly before installation (maybe).

![screen shot 2018-06-25 at 12 38 18](https://user-images.githubusercontent.com/959327/41845730-c85b9056-7874-11e8-915e-c70c3de7314a.png)

**Comment by guruz** [comment]
(The owncloud.exe there is the 2.5.0 one so it has succeeded partly)

**Comment by guruz** [comment]
qt5keychain, Qt5Sensors, Qt5PrintSupport.dll are also missing.

This sounds similar-but-not-same as the leftover files. heh

**Comment by guruz** [comment]
Funny, this might be a timing issue. Now I used the "Restart & Update" button again but get the same leftover files as in initial issue https://github.com/owncloud/client/issues/6609#issue-334862440

**Comment by guruz** [comment]
@dschmidt there should not even be an existing version!?
```
MSI (s) (88:60) [14:27:29:261]: Executing op: FileCopy(SourceName=g1u_43jc.dll|Qt5Sensors.dll,SourceCabKey=fil1BB4A9C30BAC3E369C173390D38A2055,DestName=Qt5Sensors.dll,Attributes=512,FileSize=167936,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=5.10.1.0,Language=1033,InstallMode=58982400,,,,,,,)
MSI (s) (88:60) [14:27:29:261]: File: C:\Program Files (x86)\ownCloud\Qt5Sensors.dll;	Overwrite;	Won't patch;	Existing file is a lower version
```

**Comment by guruz** [comment]
```
MSI (s) (88:60) [14:27:27:511]: Executing op: CustomActionSchedule(Action=UninstallLegacyInstallation64,ActionType=3073,Source=BinaryData,Target=WixQuietExec,CustomActionData="C:\Program Files (x86)\ownCloud\Uninstall.exe" /S)
MSI (s) (88:D8) [14:27:27:511]: Invoking remote custom action. DLL: C:\WINDOWS\Installer\MSIA48A.tmp, Entrypoint: WixQuietExec
MSI (s) (88:8C) [14:27:27:511]: Generating random cookie.
MSI (s) (88:8C) [14:27:27:511]: Created Custom Action Server with PID 6604 (0x19CC).
MSI (s) (88:B0) [14:27:27:573]: Running as a service.
MSI (s) (88:B0) [14:27:27:573]: Hello, I'm your 32bit Elevated Non-remapped custom action server.
MSI (s) (88:60) [14:27:29:026]: Executing op: ActionStart(Name=ProcessComponents,Description=Updating component registration,)
MSI (s) (88:60) [14:27:29:026]: Executing op: ProgressTotal(Total=86,Type=1,ByteEquivalent=24000)
```
Something seems to be getting run (2sec diff in timestamp) though.

**Comment by dschmidt** [comment]
```MSI (s) (8C:DC) [17:48:16:323]: Source for file 'fil106BDBC29CDF5C2354C0D7B7CF62D4F3' is compressed
MSI (s) (8C:DC) [17:48:16:323]: Executing op: FileCopy(SourceName=g1u_43jc.dll|Qt5Sensors.dll,SourceCabKey=fil1BB4A9C30BAC3E369C173390D38A2055,DestName=Qt5Sensors.dll,Attributes=512,FileSize=167936,PerTick=65536,,VerifyMedia=1,,,,,CheckCRC=0,Version=5.10.1.0,Language=1033,InstallMode=58982400,,,,,,,)
MSI (s) (8C:DC) [17:48:16:323]: File: C:\Program Files (x86)\ownCloud\Qt5Sensors.dll;	To be installed;	Won't patch;	No existing file```

FTR that's what it should look like...

**Comment by guruz** [comment]
It works with @dschmidt 's latest MSI fixes. (running NSIS uninstall.exe sequentially)
