### ISSUE TITLE
onlyoffice with owncloud sync problem

### ISSUE THREAD

**Issue by mihai89** [owncloud/client#6631]
I have a problem when I edit documents online with other users, I mention that I have the latest version of owncloud and onlyoffice document server on 2 different VPS

### Expected behaviour
I expect that what others edit in onlyoffice to sync with my folder in my computer

### Actual behaviour
I cannot see what others edited in document, i see a blank document in my folder, and if I download the file from browser it is empty

### Steps to reproduce
1. create a file using onlyoffice
2. edit the file online in browser
3. open the document from your folder

### Server configuration
Operating system: Ubuntu 16.04 x64

ownCloud version:10.0.8.5

**Comment by ogoffart** [comment]
If the file that you are downloading from the browser is also empty, this seems to be a problem on the server, or in onlyoffice.

Please open a bug report in the server componenent, or in onlyoffice. Or ask help on the forum: https://owncloud.org/help/
