### ISSUE TITLE
Syncing Large Folders (many files) => Logic improvement. (Creating file batches)

### ISSUE THREAD

**Issue by whiteonion** [owncloud/client#6640]
### Expected behaviour
Syncing taking a short time to finish
(without reindexing (rechecking all the files a few times during the process))

### Actual behaviour
When first time adding large folders (60 GB and 50,000 files) to owncloud share, the client takes forever to first index all the files, prior it starts syncing. This especially creates problems with syncing on bad internet connections, since the connection might break during the indexing process - and the client will NEVER actually start syncing (uploading files). Things get worse, when the connection breaks a few times, since now it has to check for hatches for some files, which makes the whole process EVEN slower.

Note that this does not happen if you add 6 times 10GB, or even better 12 times 5GB. Sync flies thru the files, and the whole process happens much much faster. 

My suggestion is to make the client NOT index all the files that have changed, but have a limit of the realistic maximum number of files it can process (maybe, time-wise - what it can do in 30 min or one hour). Than, when it finishes the first batch, it will take on the second one, and do that until it finishes everything, when it actually indexes all the files, and checks if everything is ok with all of them.

### Steps to reproduce
1.  Drop a new large folder (60GB + 50,000 files) in the ownCloud sync folder
2.  optional : make it loose connection a few times
3.  watch what happens

### Server configuration
Operating system:
CentOS7 minimal

Web server: 
iMac i7 4GB ram

Database:
MariaDB 10

PHP version:
7.2

ownCloud version:
10.0.8

Storage backend (external storage):
Drobo over Firewire

### Client configuration
Client version:
Version 2.4.1 (build 9367)

Operating system:
MacOSX High Sierra

**Comment by guruz** [comment]
@whiteonion Thanks for your report :) Something like that is currently being worked on :) https://github.com/owncloud/client/wiki/New-Discovery-Reconcile-Algorithm

CC @ogoffart
