### ISSUE TITLE
[macOS] Missing scrollbar for explanation text in settings for ignored files

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/client#6641]
### Expected behaviour
The complete text should be readable

### Actual behaviour
The text is truncated. A scroll bar is missing.

<img width="802" alt="issue_client" src="https://user-images.githubusercontent.com/33026403/42561875-93030f6e-84fa-11e8-8d12-7f8e0d5ef2b5.png">

### Client configuration
Client version:
2.4.2 for macOS

@ogoffart @ckamm @guruz

**Comment by jnweiger** [comment]
move to 2.5.1 ?

**Comment by ChrisEdS** [comment]
Sorry guys still not working with `2.5.2rc2 (build 11135)`

![image](https://user-images.githubusercontent.com/33026403/51347702-1a9c0480-1aa1-11e9-9c5d-d23e414085a9.png)

**Comment by jnweiger** [comment]
@guruz Please remove this from the Changelog and Release-notes of 2.5.2 unless we expect a post rc2 fix.
