### ISSUE TITLE
Linux: locale env handling is non-standard

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6650]
tested with 242~rc1 on ubuntu18.04:

Expected behaviour: `LC_ALL=C testpilotcloud` starts the testpilotcloud in untranslated C locale.

Seen behaviour: `LC_ALL=C LANGUAGE=de_DE.UTF-8 testpilotcloud` starts in german locale, (given the locale is installed in the system).

According to the locale specs, LC_ALL=C should take precedence. 
See also: https://www.gnu.org/software/gettext/manual/html_node/The-LANGUAGE-variable.html#The-LANGUAGE-variable

Typical standard conforming behaviour:

```
$ LC_ALL=C dd if=fooo
dd: failed to open 'fooo': No such file or directory

$ LC_ALL=C LANGUAGE=de_DE.UTF-8 dd if=fooo
dd: failed to open 'fooo': No such file or directory

$ LC_ALL= LANGUAGE=de_DE.UTF-8 dd if=fooo
dd: konnte 'fooo' nicht öffnen: Datei oder Verzeichnis nicht gefunden

**Comment by jnweiger** [comment]
Probably not a regression. we should fix this for 2.5.0.

**Comment by guruz** [comment]
> Probably not a regression. we should fix this for 2.5.0.

Does this happen in any standard linux distro or is this a bug you manually constructed?

Sounds like an upstream Qt bug if it is a bug.

**Comment by ogoffart** [comment]
Yes, this is a Qt issue.

The logic is in QSystemLocale::query in qlocale_unix.cpp. (the case for QSystemLocale::UILanguages)
It first read the `LANGUAGE` env variable, and only if this is empty, it reads `d->lc_messages_var` which itself is the value of `LC_MESSAGES` env variable, and if unset, `LC_ALL`

We will not work around this bug, we will stay consistent to other Qt applications.

**Comment by jnweiger** [comment]
Thanks for checking with upstream Qt. Agreed.

There are not so many combinations of environment variables. As long as there is at least one working combination, of variables that allows locale switching, I am fine with nonstandard Qt-Behaviour.
