### ISSUE TITLE
It is not possible to denote rc1 or beta versions in the beta channel

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6651]
enhancement suggestion:

It is not possible to denote rc1 or beta versions in the beta channel. We can only use the numeric version number
without any suffix. Entries like 
'2.4.2rc1' 
'2.4.2~rc2' 
'2.4.2-rc2' 
'3.4.2~beta1'
are ignred by the 2.4.2~rc1 client.

**Comment by guruz** [comment]
@jnweiger I don't understand your bug report. It's always only x.y.z.BUILDNUMBER for the internal version that is used for comparisons.
The versionString displayed to the user can contain anything.
See also https://github.com/owncloud/client/issues/6602

**Comment by jnweiger** [comment]
understand. the BUILDNUMBER works fine. thanks.
but it also only display the build number, when offering an update, no hint if it is a beta or rc, actually.

**Comment by guruz** [comment]
>  but it also only display the build number, when offering an update, no hint if it is a beta or rc, actually. 

On which platform?
For macOS i had fixed this recently. For Windows it's lacking as per https://github.com/owncloud/client/issues/6602 ...
For Linux you tell me :-)

**Comment by ogoffart** [comment]
Is this still an issue?

**Comment by guruz** [comment]
@jnweiger Was the string that you saw one of
```
    QString updateVersion = _updateInfo.versionString();
...
    case DownloadComplete:
        return tr("%1 available. Restart application to start the update.").arg(Theme::instance()->appNameGUI(), updateVersion);
....
    case UpdateOnlyAvailableThroughSystem:
        return tr("New %1 available. Please use the system's update tool to install it.").arg(updateVersion);
```
?

Then I would think @ogoffart already fixed it by https://github.com/owncloud/client/commit/21ac396bd1b2fb88763901bbafb36474e244c4f5

Please re-open if not
