### ISSUE TITLE
Window Client Area Fixed - Can't see all of ownCloud window

### ISSUE THREAD

**Issue by adavie1** [owncloud/client#6652]
### Expected behaviour
The window should be visible, at least on screen sizes of 800x600 and above. I've got a screen res of 1920 x 1080 and can't see all the screen.

### Actual behaviour
The lower part of the screen is not visible.
![image](https://user-images.githubusercontent.com/3030402/42700875-9f76d4de-86f7-11e8-8bf9-1a5741347730.png)

### Steps to reproduce
1. Open ownCloud client.

### Server configuration
Operating system: N/A

Web server:  N/A

Database: N/A

PHP version: N/A

ownCloud version: Client version  2.4.1 - on Windows 10.

Storage backend (external storage):

### Client configuration
Client version: 2.4.1

Operating system: Windows 10

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs: N/A

**Comment by ogoffart** [comment]
Thanks for the bug report.
This is the same issue as#6075 which is fixed in 2.5
