### ISSUE TITLE
easy setup to sync within a sync folder

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6654]
Tested with 242~rc1 on ubuntu 18.04 and testpilotcloud version 2.6.0daily20180713 (build 9853)

**DO NOT DO THAT ON A PRODUCTION SYSTEM**

Expected behavior: it should not be possible to have two syncs in the same folder running at the same time.

Observed: It is quite easy to do so, one client is sufficient. Havoc results, replicating the same folders inside the toplevel folder again and again, probably until MAXPATHLEN or diskquota are exhausted.

Reproduce:

* Start `testpilotcloud &`
* Connect to demo.owncloud.org user demo.
* Choose what to sync: [x] Documents 35kb, everything else unchecked.
* Wait until sync completes. Quit the client from the tray menu.
* `rm -rf ~/testpilotcloud`
* start `testpilotcloud &` and notice the expected error message:
![grafik](https://user-images.githubusercontent.com/1108546/42705127-a776bd86-86d2-11e8-9f4b-6ef316115d3f.png)
* click 'Add Folder sync connection', confirm the suggested local folder `/home/USERNAME/testpilotcloud`
* Click on `Documents`  -> Next -> Add Sync Connection

Now we have two active sync connections. The client window alternates between

![grafik](https://user-images.githubusercontent.com/1108546/42705319-36a93178-86d3-11e8-8908-50584c2ec62b.png)
and
![grafik](https://user-images.githubusercontent.com/1108546/42705557-fc9c910e-86d3-11e8-9400-43e975b1b0ad.png)

The top level folder gets synced into the Documents folder with every rediscovery loop, generating a deep hierarchy of 
```
ll testpilotcloud/Documents/Documents/Documents/Documents/Documents/
insgesamt 4968
drwxr-xr-x 4 testy testy    4096 Jul 13 19:32  ./
drwxr-xr-x 4 testy testy    4096 Jul 13 19:31  ../
drwxr-xr-x 2 testy testy    4096 Jul 13 19:32  Documents/
-rw-r--r-- 1 testy testy   36227 Jul 13 19:02  Example.odt
-rw-r--r-- 1 testy testy 5017133 Jul 13 19:02 'ownCloud Manual.pdf'
drwxr-xr-x 2 testy testy    4096 Jul 13 19:32  Photos/
```

There are two ._sync_*.db datastructures in the same folder. Both active
```
ls -la ~/testpilotcloud
total 5360
drwxr-xr-x  4 testy testy    4096 Jul 13 19:37  ./
drwx------ 33 testy testy   12288 Jul 13 19:29  ../
-rw-r--r--  1 testy testy  118784 Jul 13 19:37  ._sync_943bac99edd8.db
-rw-r--r--  1 testy testy   32768 Jul 13 19:37  ._sync_943bac99edd8.db-shm
-rw-r--r--  1 testy testy       0 Jul 13 19:37  ._sync_943bac99edd8.db-wal
-rw-r--r--  1 testy testy  114688 Jul 13 19:36  ._sync_f3502dd50375.db
-rw-r--r--  1 testy testy   32768 Jul 13 19:36  ._sync_f3502dd50375.db-shm
-rw-r--r--  1 testy testy       0 Jul 13 19:36  ._sync_f3502dd50375.db-wal
-rw-r--r--  1 testy testy   32080 Jul 13 19:37  .owncloudsync.log
drwxr-xr-x  4 testy testy    4096 Jul 13 19:29  Documents/
-rw-r--r--  1 testy testy   36227 Jul 13 19:02  Example.odt
drwxr-xr-x  2 testy testy    4096 Jul 13 19:29  Photos/
-rw-r--r--  1 testy testy 5017133 Jul 13 19:02 'ownCloud Manual.pdf'
```

**DO NOT DO THAT ON A PRODUCTION SYSTEM**

**Comment by jnweiger** [comment]
A deadlock error can be seen when quitting and restarting the client. It goes away after a few seconds, and folder replication continues....
![grafik](https://user-images.githubusercontent.com/1108546/42705828-eb60bb1c-86d4-11e8-93cf-cde440b94671.png)

**Comment by ogoffart** [comment]
Well, we can't prevent the user to do every stupid things.

We could guard against syncing a folder or one of its subfolder which is already shared with a local folder or one of its parent folder of the same account. 

This would catch some of these wierd issues. There would still be ways to introduce loops with other accounts, but we IMHO don't need to go to great length to prevent that.

**Comment by jnweiger** [comment]
I found it "too easy", because the user interface seems to guide me into that situation. I know that a 'Add Folder Sync Connection' is something different. But I fear that most users don't realize that, when they see
the red error message 'Unable to find the local sync folder' and directly below a friedly button offering 'Add Folder Sync Connection' -- seems to be the perfect fit, but then explodes ...

**Comment by ogoffart** [comment]
@jnweiger  Unrelated, but your screenshot do not have the '...' icon. Seems like the svg plugin is missing.

**Comment by ogoffart** [comment]
The logic to avoid this kind of problem was already there. But it did not work correctly when there was existing folder with deleted directory.  Fixed in #6656

**Comment by jnweiger** [comment]
@ogoffart looks like I can run two owncloud clients in parallel in the same sync folder now. 
But my setup is strange, I'll have to reproduce that on a fresh instlal.

**Comment by jnweiger** [comment]
### test under Ubuntu 18.10
running owncloud 2.5.1rc2

sync folder /home/testy/ownCloud, -> removed.
the restarted client suggests /home/testy/ownCloud2 -> OK
editing the path to say e.g. /home/testy/ownCloud2/Documents causes a friendly warning -> OK
![image](https://user-images.githubusercontent.com/1108546/48095373-dd033b80-e214-11e8-8a89-f245421fa7a5.png)

The [Next] button is grayed out -> OK

All this while the sync folder /home/testy/ownCloud does not exist

PASS
