### ISSUE TITLE
online updates are offered in both beta and stable channel, if beta channel is empty or older

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6658]
![grafik](https://user-images.githubusercontent.com/1108546/42824605-73274d1e-89e0-11e8-9df5-171186255034.png)

This was with a faked update server that offered 242rc1 in the standard channel.
242 introduces the beta channel here, but shows what was offered in the standard channel next to the beta keyword.
the beta channel is empty on this updater.

**Comment by jnweiger** [comment]
oops, that 9968 was a typo. should have been 9967 that explains, why it shows at all.
But still: it should not show up in the beta channel imho. Is there a fallback logic from beta to standard?

**Comment by jnweiger** [comment]
if there is an entry for 'ownCloud' in the beta channel then it is correctly reported as 'nothing new' or 'update available.

**Comment by ogoffart** [comment]
I don't understand the problem.   There is a new version (build 9968) so it is reported as available. What's wrong with that?

**Comment by guruz** [comment]
>  Is there a fallback logic from beta to standard?

The beta channel just enables additional (unstable) versions that are eligible for download.
everything is done based on x.z.y.buildnumber. (see my comment on https://github.com/owncloud/client/issues/6651#issuecomment-405258718 )

**Comment by guruz** [comment]
Works as expected :-)
