### ISSUE TITLE
Missing files in owncloud (only directory tree)

### ISSUE THREAD

**Issue by dnacombo** [owncloud/client#6660]
### Expected behaviour
Folder should be in my owncloud. Appears in the web interface and in the desktop client interface. Only directory tree in the file system.

### Server configuration
ownCloud 10.0.1 (production) 

### Client configuration
Client version: Version 2.4.1+dfsg-1

Operating system: Linux Mint 19 Tara

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): no info on QT in the interface.

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

**Comment by ogoffart** [comment]
Hi, Please explain the step to reproduce. And what is happening wrong.

**Comment by dnacombo** [comment]
I can't, sorry. It happened all over sudden.
Fixed by unlinking and relinking the local owncloud folder.
Thanks
