### ISSUE TITLE
Up-/Download multiple small files at once to increase overall transfer speed

### ISSUE THREAD

**Issue by cnmicha** [owncloud/client#6663]
### Expected behaviour
Many small files upload simultaneously, so uploading many of them is fast

### Actual behaviour
Many small files upload one after each other, which takes ~4s for every file and minutes to upload the whole list of changed (small) files.
This should also be improved for download.

### Steps to reproduce
1. Create/change many small files
2. Upload or download them

### Server configuration
Operating system: CentOS Linux release 7.5.1804

Web server: nginx/1.12.2

Database: mysql  Ver 15.1 Distrib 5.5.56-MariaDB, for Linux (x86_64) using readline 5.1

PHP version: 7.1.19

ownCloud version: 13.0.4

Storage backend (external storage): none
### Client configuration
Client version: 2.3.2 (build 1)

Operating system: Win 10 64 bit, Ubuntu 64 bit

OS language: German, English

Client package (From ownCloud or distro) (Linux only): distro (APT)

**Comment by ogoffart** [comment]
Hi, thanks for your bug report.

This is a known issue, and it has been worked on.
https://github.com/owncloud/core/pull/25760
https://github.com/owncloud/client/pull/5319

However, the current state is that this is on hold and no more progress is being done.

**Comment by michaelstingl** [comment]
@cnmicha Next 2.5 version supports HTTP 2.0 which can bundle requests too.

**Comment by guruz** [comment]
> which takes ~4s for every file 

Are you sure you have opcode caching, APCu etc enabled in your PHP?
Are you on a newer PHP7?
