### ISSUE TITLE
Re-shares not shown in client UI

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#6666]
### Expected behaviour
Owner of a share should also see recipients of re-shares, same as in web UI.

### Actual behaviour
Re-shares not shown in client UI.

### Steps to reproduce
1. User A shares folder with User B
2. User B shares received folder with User C

### Server UI

| User A | User B | User C |
|---|---|---|
| ![files_-_owncloud](https://user-images.githubusercontent.com/214010/43005844-5480580a-8c34-11e8-966f-b4919a4ce127.png) | ![files_-_owncloud](https://user-images.githubusercontent.com/214010/43006035-f13fce96-8c34-11e8-904c-4dc63e00516a.png) | ![files_-_owncloud](https://user-images.githubusercontent.com/214010/43006098-1d726a50-8c35-11e8-9ea0-d2ff65cd7f71.png) |

### Client UI

| User A | User B | User C |
|---|---|---|
| <img width="443" alt="owncloud_sharing_and_ownclouds_and_mstingl_oc_and_rocket_chat__and_inbox__8_677_messages_" src="https://user-images.githubusercontent.com/214010/43006671-96b71cca-8c36-11e8-842d-bc8869de41da.png"> | <img width="446" alt="owncloud_sharing_and_ownclouds_and_mstingl_oc_and_rocket_chat__and_inbox__8_677_messages_" src="https://user-images.githubusercontent.com/214010/43006726-be7d73a8-8c36-11e8-80b6-9f6990b714bc.png"> | <img width="406" alt="owncloud_sharing_and_ownclouds_and_mstingl_oc_and_rocket_chat__and_inbox__8_677_messages_" src="https://user-images.githubusercontent.com/214010/43006765-db95c382-8c36-11e8-81ca-b1e67b37d3cb.png"> |

### Server configuration
ownCloud version:
10.0.9

### Client configuration
Client version:
2.4.2

Operating system:
macOS 10.13

OS language:
EN

Qt version used by client package (Linux only, see also Settings dialog):
Qt 5.6.2

## Solution

PR from @jnweiger https://github.com/owncloud/client/pull/6665

**Comment by michaelstingl** [comment]
related: https://github.com/owncloud/enterprise/issues/2505

**Comment by michaelstingl** [comment]
@jnweiger in 
https://github.com/owncloud/android/issues/2264#issuecomment-407453191 @PVince81 recommended to use the `v2` endpoint. Could you fix it once more?

**Comment by jnweiger** [comment]
switch to the v2 api endpoint a different scope https://github.com/owncloud/client/pull/6700
