### ISSUE TITLE
MSI: Odd no-taskbar-or-explorer-or-desktop state 

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6667]
Windows 10.

I've "updated" from 2.5.0beta1 EXE to 2.5.0beta1 MSI.
In the message dialog which asks to close and restart Explorer.exe I picked "yes" (or whatever it was called) to close+restart it.
I picked "No" to the option to restart Windows.
But for some reason Explorer is not restarted.

(The windows appear minimized because they used to be in the taskbar which is dead)

<img width="1312" alt="screen shot 2018-07-20 at 18 16 42" src="https://user-images.githubusercontent.com/959327/43013797-5792c22e-8c4a-11e8-919b-d9eeb5d68d89.png">

If I do some combination of ctrl+alt+del and then launching explorer.exe from there and then clicking "restart" of explorer.exe I can get the task bar and esktop back

**Comment by guruz** [comment]
this time with ownCloud-2.5.0.10516.-beta2.10506.msi launched from IE it works. After the progress baras run through, the taskbar comes back.
I don't know how I launched in my initial report.
Maybe someone should try to reproduce @michaelstingl @ckamm

**Comment by guruz** [comment]
Did no one ever get this?

**Comment by dschmidt** [comment]
I have never seen this personally. I have seen that the MSI *sometimes* kills the taskbar, but I don't know how to reproduce that either. It was never as bad as this for me.

**Comment by michaelstingl** [comment]
> Did no one ever get this?

nope

**Comment by ogoffart** [comment]
Has anyone been able to reproduce?

**Comment by ckamm** [comment]
I've installed via msi a bunch of times but my explorer.exe always restarted automatically.

**Comment by ogoffart** [comment]
Closing as no one can reproduce it.
