### ISSUE TITLE
bogus message for removed sync connection

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6679]
Using 2.5~daily from July 27 with multiple accounts:

Account -> Add new -> demo.owncloud.org .... -> Connect.
Wait until it starts syncing some files.
Account -> Remove 

When visiting the Activity tab afterwards, it complains that the Acocunt demo@demo.owncloud.org does not have activities enabled.
![grafik](https://user-images.githubusercontent.com/1108546/43514969-ae008048-9581-11e8-9aa1-f54f4e9b3172.png)

**Comment by ogoffart** [comment]
Fix in https://github.com/owncloud/client/pull/6687

**Comment by jnweiger** [comment]
### tested on Ubuntu 18.04
owncloud-client 2.5.1 rc2

The message "Account demo@demo.owncloud.org does not have activities enabled." is shown while the account is active. -> OK
As soon as the account is removed, the message disappears. -> OK

PASS
