### ISSUE TITLE
How to get the MSI installer following the instructions "Building the Client"

### ISSUE THREAD

**Issue by marcos-guerrero** [owncloud/client#6681]
Hi! I'm following the instructions in https://doc.owncloud.org/desktop/2.3/building.html to get the installer for windows (Cross-Compile) , I could manage to get everything working using v2.5.0-beta1 tag but the final piece I get is an .exe.
As I see in https://github.com/owncloud/client/releases/tag/v2.5.0-beta1 there are two installers available, an .exe and .msi
I found a bunch of issues related to msi installer but I couldn't find how to get the msi 
Would anyone be so kind to point me how to build the client and get the msi?
Thanks in advance for your help

**Comment by michaelstingl** [comment]
@marcos-guerrero we didn't publish the instructions how to build the *.MSI yet.

Could you open new issues for your *.MSI findings?

**Comment by marcos-guerrero** [comment]
Thank you for your answer,
Ok, so my polite request is: please, publish the instructions or at least one file (README o so) to know how to build it ...
For your second phrase ... sorry, I don't understand "Could you open new issues for your *.MSI findings?"
My goal is to change a buch of things in the client (only one upload thread, no autoupdate, leave almost everything in the settings section predefined and unchangeable) and then get an msi to install thru GPO ...
So which new issues do you want me to open? 
Best regards

**Comment by guruz** [comment]
@marcos-guerrero This can be achieved through [ownBrander](https://doc.owncloud.org/branded_clients/branded_desktop_client/branded_desktop_client.html).

> only one upload thread 

Why would you want this?
I think there is an environment variable for this too.

**Comment by marcos-guerrero** [comment]
One upload thread is only one of the tweaks I want to apply, and maybe that one could be achieved by using an environment variable (more registry tweaking) but there're others that can be reached changing the code... and I've already done it before.

So, as final products there're an exe and a msi installer, that's why asking for how to get the msi

**Comment by karakayasemi** [comment]
Hey @marcos-guerrero, you can find build instructions with docker in here: https://central.owncloud.org/t/error-using-docker-to-build-the-windows-client/5107/5 . Also, in this repository https://github.com/ITUBIDB/kovan-desktop-client, you can find branding commits, also in the README file you can find build instructions with docker for owncloud desktop client v2.4.1. I hope, it helps.

**Comment by marcos-guerrero** [comment]
@karakayasemi  I'll give a try , but looks like I won't get a msi installer following the instructions on your link and README file.
Anyway all sources of documentation are very welcome!

**Comment by michaelstingl** [comment]
@marcos-guerrero please send me your contact information to `michael <at> owncloud.com`

**Comment by darksworm** [comment]
+1 I would love to see msi build instructions as well.

**Comment by michaelstingl** [comment]
@darksworm ==> `michael <at> owncloud.com`

**Comment by dschmidt** [comment]
> My goal is to change a buch of things in the client (only one upload thread, **no autoupdate**, leave almost everything in the settings section predefined and unchangeable)

The no autoupdate part can be achieved with the standard msi already: https://doc.owncloud.org/desktop/latest/installing.html#disabling-automatic-updates
As other things this is simply a registry setting, so if you already plan on provisioning other settings, you might as well simply set the corresponding registry key, compare https://github.com/owncloud/client/blob/master/cmake/modules/NSIS.template.in#L819 for the old NSIS based setup.
