### ISSUE TITLE
dolphin integration on Fedora28 misses overlay icons

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6684]
Fedora 28, default GNOME desktop. owncloud-client-2.4.2 and testpilotcoud-client-2.5.0~beta1
With `dnf install owncloud-client-dophin dolphin` we can force in the dolphin file browser and install the shell integration for owncloud.

When the client is connected to an owncloud server, overlay icons should indicate the sync state.
They are missing. I can confirm that the client is indeed connected, by checking the right click file actions.
ownCloud is there, and offers its services.
![grafik](https://user-images.githubusercontent.com/1108546/43608580-b70243b8-96a1-11e8-907d-18a330cbd8e0.png)

**Comment by ogoffart** [comment]
@jnweiger does any other system have the problem? Is it a packaging issue?
