### ISSUE TITLE
Align testpilotcloud themeing with original ownCloud (except for name and artwork)

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6685]
openSUSE Leap 42.2 and Fedora 28, testpilotcloud-client-2.5.0~beta1

When entering demo.owncloud.org, demo, demo in the firstrun wizard, The connect page opens.
and the user can choose several sync options.

![grafik](https://user-images.githubusercontent.com/1108546/43610688-26ff5ed0-96a7-11e8-8473-a68e12a56c24.png)
Ontop of the connection page, the 'choose what to sync' popup immediately appears, with everything deselected. This popup should only appear, If I click 'Choose what to sync' and it should start with everything selected.

When dragging the popup a bit downwards, one can see that the radio button is at 'Synchronize everything' -- as seen in the screenshot above.

**Comment by ogoffart** [comment]
Note: testpilot has different theme options. One of them is that Theme::wizardSelectiveSyncDefaultNothing is set to true:

```
   /**
     * When true, the setup wizard will show the selective sync dialog by default and default
     * to nothing selected
     */
    virtual bool wizardSelectiveSyncDefaultNothing() const;
```

So it is expected to show this dialog.  Maybe the problem is that the "synchronize everything from the server" is selected.  This is because we choose the right checkbox when we close that dialog. So maybe i can fix it so the right radio button is selected.

**Comment by ogoffart** [comment]
https://github.com/owncloud/client/pull/6686 will make sure that the "Choose what to sync" radio button is selected in that case.

**Comment by jnweiger** [comment]
Hmm, thanks for the explanation and the fix for the button logic. 
But then, the fault is in the testpilot theme: It is meant for testing, so that users can explore a new client version before they upgrade their produciton client. 
Its behaviour must not intentionally differ.

**Comment by ogoffart** [comment]
@jnweiger , I consider that the "wrong checkbox" state is fixed.
If you want to make the theming of the testpilot client the same, you need to do it yourself for i don't have access to it.

**Comment by jnweiger** [comment]
### tested on a fresh Ubuntu 18.04
rm -rf ~/.config/ownCloud\ Testpilot\ Edition
rm -rf ~/testpilotcloud
testpilotcloudcmd -v
 testpilotcloud version 2.5.1daily20181031 (build 10426)

The connection wizardnow starts normally. (*) Synchronize everything is preselected. -> OK
When clicking on ( ) [Choose what to sync] the dialog opens with all elements selected. -> OK
This is consistent with the normal owncloud client -> OK

PASS
