### ISSUE TITLE
new mount point handling

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#6697]
### Expected behaviour
When the server mount point gets deleted, it should also remove the "what to do" choice on the client

### Actual behaviour
When a new mount point is created, it is transmitted to the client.
The client asks on the window what to do regarding syncing, see screenshot.
Before you do anything on the client, if you remove the mount point on the server, this screen stays as long you click a choice even the mount point is not longer present.
![image](https://user-images.githubusercontent.com/3321281/43777583-8572204c-9a53-11e8-873c-42419d16cd68.png)

### Steps to reproduce
1.  create a mount point on the server
2.  watch on the client that choices for this mount point show up
3. delete the mount point on the server
4. watch if the mount point choices get removed automatically

### Server configuration
Operating system: Ubuntu 16.04

Web server: nginx

Database: mysql

PHP version: 7.1

ownCloud version: 10.0.9

Storage backend (external storage): smb, ftp, dropbox

### Client configuration
Client version: 2.4.2 (build 10040)

Operating system: W10x64

OS language: DE

**Comment by michaelstingl** [comment]
@mmattel thank you for reporting this issue. 2.5.0 will refresh more often, maybe this helps here too. Could you verify with a 2.5.0 daily build? (https://download.owncloud.com/desktop/daily/?C=M;O=D)

**Comment by mmattel** [comment]
> 2.5.0 will refresh more often

This does not seem to be the issue as it appears quite quickly after the mount points gets created. But it does not disappear, I can wait forever. My pov is, that this sync questionair is blocking incoming changes addressing the questionair itself - that is the cause for the endless wait. The removal of a mount point should also remove the questionaire, if the questionaire was correlateded to the mount point. (sounds complicated, I know, but is easy to see if you give it a try)

I am fearing running 2.4.2 (productive) and 2.5.0 (dev) in parallel. The last time I tried some time ago, I needed to remove both clients and restup the sync. Will it work flawless in parallel?

**Comment by ogoffart** [comment]
(I remember there was a similar issue reported recently but i can't find it.)

However, since we do not synchronize these folder, we also don't know when they are deleted.
We would need to do additional query to the server to know that these questions are out of date.
The user can just decide to apply the "choose what to sync" screen, and these questions will be gone.

**Comment by mmattel** [comment]
He would agree on something that is not longer present.

When you create or delete a mount point on the server, this change is recognized by the client by regularly querying the server. If you hava already decided what to do with a mount point on the client and you delete the mount point on the server, it disappears on the client side - ok.

What I am highlighting is, that when you have NOT decided what to do with respect of syncing the mount point (the questionnaire is visible) AND you delete the mount point on the server side AND the client has queried the server, the questionaire what to do becomes sensless and should go away automatically (for that particular server deleted mount point).

I can really encourage to give it a try to understand the issue.

**Comment by ogoffart** [comment]
@mmattel  I understand the issue, and know that this is a problem. 

The thing is that "answering an outdated question" is not the end of the world for an user.
And the bug is not trivial to fix.

In other words, I agree this is a bug, but given the ratio <importance of the bug>/<difficulty to fix>, we might not fix it soon.

**Comment by mmattel** [comment]
I never said it is trivial to fix 😄 

pls see things from a user pov. the question is not outdated as the user is not the admin and the user is commonly low experienced.
If the admin did a mistake he fixes immediately (by deleting the mp or removing the user/group), all affected users will get this action to process. This is a good driver for a fix.
The question is, if the questionnaire box can be automatically removed for that particular mount point without any button pressed.

We have two cases:
Case 1: the questionnaire is in a „view“ queue as there is already another one waiting for a user input. 
Case 2: the questionnaire is is already visible by the user.

For me, just my pov, user experience has a very high rating as this are those people who recommend  or blame, justified or not...

(before you suggest writing code by myself, no C# knowledge available 😄 )

**Comment by TheOneRing** [comment]
The above dialog was removed in 6.0
