### ISSUE TITLE
[macOS] garbled settings dialog when clicking fast

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6704]
macos 10.13
client 250beta1 build 10216

clicking back and forth in the settings dialog on a sluggish machine, it is possible to reach a state where both activity and general tab are active simultaneously. That looks like this:
![grafik](https://user-images.githubusercontent.com/1108546/43921779-16338128-9c1d-11e8-934c-7cd2ce74be17.png)

this should not be possible.

**Comment by ogoffart** [comment]
Is it still a problem in 2.6 now that we use the same settings dialog as on linux/win ?
