### ISSUE TITLE
Uninstaller nukes everything in the installation directory when it should only be removing owncloud files

### ISSUE THREAD

**Issue by darksworm** [owncloud/client#6708]
### Expected behaviour
Tell us what should happen
1. User wants to remove owncloud
2. User runs the uninstaller and uninstalls owncloud
3. Owncloud program files are deleted
### Actual behaviour
Tell us what happens instead
The whole installation directories contents are deleted
### Steps to reproduce
1. Install owncloud anywhere
2. Copy files to owncloud installation directory
3. Uninstall owncloud
### Why is this an issue?
I recommended owncloud to someone and they installed owncloud in the root of their Program Files folder. When they uninstalled owncloud, the uninstaller proceeded to delete everything in their Program Files folder. 
Although I admit that setting the installation directory to the root of program files or any other existing directory which contains data is a bad idea, this should not have been an option in the first place!
In my opinion the uninstaller should not be touching files which the installer did not produce or at the very least the installer shouldn't allow you to install the program to a non-empty directory.
### Server configuration
Does not apply
### Client configuration
Client version:
2.4.3.10188
Operating system:
Windows 10
OS language:
english
Installation path of client:
default
### Logs
Does not apply

**Comment by guruz** [comment]
@darksworm It would be interesting to see how this behaves with the new MSI based installer.
https://github.com/owncloud/client/releases/tag/v2.5.0-beta1

**Comment by darksworm** [comment]
@guruz I just tried, and looks like it works as it should - it removed only the files which the installer created.

**Comment by guruz** [comment]
Great!
Thanks.

@dschmidt FYI. (after your holiday)
