### ISSUE TITLE
Client anounces folder removal, but does not remove.

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6715]
I decide to sync one of my local folders with an owncloud server. 
One subfolder called trebuchet is so huge, that I don't want to upload it now, but perhaps later.
![grafik](https://user-images.githubusercontent.com/1108546/44162552-fe92d200-a0c0-11e8-846d-484537620ebd.png)
Using selective sync, I can disable that folder, but then a message appears, that says, the folder would be deleted. A cautious user would now copy the huge folder away, wondering why owncloud would want to delete data that is not yet on the server. Scary.

The good news is: The desktop client only deletes local folders, if there is a copy on the server. 
The printed warning is overly pessimistic. Please adjust the text, to say e.g:

Unchecked folders that exist on the server will be **removed** from your local filesystem and will not be synchronized to this computer anymore.

**Comment by ogoffart** [comment]
I think the current wording is fine.
The fact that some files cannot be removed because they were modified or added will result in errors later anyway.

**Comment by TheOneRing** [comment]
Removed in https://github.com/owncloud/client/pull/11517
