### ISSUE TITLE
Renaming virtual files does not work correctly

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6718]
### tested on Linux Mint Tara, testpilotcloud-client-2.5.0~daily20181014

    [General]
    showExperimentalOptions=true

* Renaming a file foo.txt.testpilotcloud_virtual to bettername.txt.testpilotcloud_virtual 
in a local sync folder has no effect. The original name is restored 2 or 3 seconds later.
* Renaming a subfolder in the local sync folder works as expected, though.
* Renaming a local file Photos/Paris.jpg.testpilotcloud_virtual to Photos/Paris.jpg almost does the right thing:
  - Message: Server version downloaded, copied changed local file into conflict file
  - Message: Conflict: Server version downloaded, local copy renamed and not uploaded.
 
OK:
The virtual file gets replaced by the original file. Nice!

BAD
A self-conflict is generated `Paris (conflicted copy 2018-08-15 220222).jpg`

* Renaming a fully downloaded file to its virtual placeholder should do the obvious.
  `mv Photos/Paris.jpg Photos/Paris.jpg.testpilotcloud_virtual`

BAD
Data loss! The file gets removed on the server and on the client
  - Message: Photos/Paris.jpg Deleted

### tested win10 owncloud-client 2.5.0beta1

C:\Users\IEUser\AppData\Roaming\ownCloud\owncloud.cfg

    [General]
    showExperimentalOptions=true

* The suffix in win10 is  .owncloud (instead of .owncloud_virtual)

BAD
Same issues including data loss through renaming.

**Comment by ckamm** [comment]
Virtual file suffix is sometimes .owncloud and sometimes .owncloud_virtual -> #6719

Let's make this issue purely about 
1. renaming virtual files (a.owncloud -> b.owncloud)
2. renaming virtual files to actual files (a.owncloud -> a; a.owncloud -> b)
3. renaming files to virtual files (a -> a.owncloud; a -> b.owncloud)

**Comment by jnweiger** [comment]
Edited back to the truth: Tests were done with testpilotcloud actually. That makes a difference, unfortunately. Sorry.

**Comment by jnweiger** [comment]
### Linux Mint tara, ownCloud version 2.5.0filerenametovirtual6718 (build 10079)
Git revision 5d3d6d362b795e3954875d2608ad7523f31c2ea3

OK
this fixes the data loss. 

```
mv .../somewhere/stars.svg Photos
sleep 10
mv Photos/stars.svg{,.owncloud}
sleep 10
ls -la Photos/stars*
 -rw-r--r-- 1 testy testy 1 Aug 16 19:10 Photos/stars.svg.owncloud
```

BAD
(enhancement idea:) The file must first be placed in the folder without the .owncloud suffix.We must wait untils the client syncs. only then we add the .owncloud suffix. It does not work, if we rename before the sync starts, or if te copy is created with the .owncloud extension.

BAD
the conflict is still there when removing the .owncloud extension.

PLEASE MERGE ;-)

**Comment by ckamm** [comment]
@jnweiger Thanks for the very quick testing, this PR is merged. I think the other renaming issues will not be in time for 2.5.0

**Comment by jnweiger** [comment]
### test under ubuntu 18.10
running owncloud-client 2.5.1rc2

renaming a virtual file stays -> OK
the new name propagates to the server -> OK
immediate double click on a renamed file downloads the file from the server correctly -> OK

PASS
