### ISSUE TITLE
[VFS] Migrating existing sync folder(s) to VFS

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#6725]
### Expected behaviour
It would be awesome to migrate pre-2.5 accounts to the new VFS behaviour

### Actual behaviour
Currently it's not possible
(tested with todays daily 2.5.0 build)

**Comment by ogoffart** [comment]
Sync-engine wise, this is trivial to do. We just need to find a way to do it ui-wise.
Add an entry in the context menu with  "[] New files are created as Virtual Files" ?
Can one disable the option and then all the files are downloaded?  Does it need a message box to confirm?

**Comment by michaelstingl** [comment]
Cool, good to know! 👍

**Comment by tessus** [comment]
@ogoffart @michaelstingl is this supposed to be done automatically? It's just that I do not plan to use VFS and I don't want the client to automatically convert my setup to VFS.

According to the commit log, it's not a behind-the-curtain conversion, but I just wanted to make sure.

**Comment by tessus** [comment]
@michaelstingl thanks for the reply. I only wanted to say that I do not want the client to convert non-VFS setups to VFS automatically - ever. If people choose not to use VFS, it should be respected.
