### ISSUE TITLE
[VFS] No option to replace downloaded files with placeholder files

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#6726]
Currently there is no option for the user to replace downloaded files with placeholder files to free-up disk space. (tested with todays daily 2.5.0 build)

![owncloud-3](https://user-images.githubusercontent.com/214010/44232136-7257dc00-a1a0-11e8-83b2-97bb4afe72a6.png)

### Expected behaviour
There should be an option (in the context menu) to replace downloaded files with placeholder files

### Actual behaviour
Currently there is no option replace individual downloaded files, but there is a workaround to replace all content of the parent folder with placeholder files.

### Workaround
1. Open settings and deselect the parent folder in the selective sync UI
2. Apply this change
3. Wait for the files to be deleted
4. Then select the parent folder in the selective sync UI
5. Apply this change
6. ==> Placeholder file gets downloaded from ownCloud server

### Here is the example from another tool

![db-ss](https://user-images.githubusercontent.com/214010/44232684-14c48f00-a1a2-11e8-8798-338160066853.png)

If multiple elements have the same state, a checkmark is shown:

![db-ss-checkmark](https://user-images.githubusercontent.com/214010/44232854-9ddbc600-a1a2-11e8-8dd4-643c1ffbefff.png)

**Comment by ogoffart** [comment]
@ckamm:  here is how i'd do it:

I'd add a new option in the context menu (socket api) `tr("Replace by virtual files")`, then i see several options: 

1) Simply delete the files we want to replace, and at the same time, delete their entry in the DB.  Next sync will then restore the placeholder.

2) For each file we want to replace, just rename it by adding the ".owncloud" extension, and let the logic from #6721 make the virtual file in the next sync.

3) For each file we want to replace, delete it, replace it by a placeholder, and update the database as wall.

What approach should we take?
Thinking about it, I think I'd do 2. It is the easier. But it relies on the hack done for #6721, I guess it is fine.
3 Would be the most correct but also is a bit more work.

**Comment by ckamm** [comment]
@ogoffart I'm ok with using 2. if there's a warning note about the interaction on the code that performs the action. More advanced vfs will need to do more complex actions like 3.

**Comment by michaelstingl** [comment]
LGTM

![cursor_and_msedge_-_win10](https://user-images.githubusercontent.com/214010/44998118-6008db00-afb3-11e8-934d-5b6a02ede99c.png)

- real file(s) selected ==> `Replace file(s) by virtual file`
- virtual file(s) selected ==> `Download file(s)`
- mixed files selected ==> `Download file(s)` + `Replace file(s) by virtual file`

@ogoffart close?
