### ISSUE TITLE
ownCloud server hostname in the Server Activity tab does not account for email addresses as username

### ISSUE THREAD

**Issue by mdusher** [owncloud/client#6728]
### Expected behaviour
Show the hostname of the ownCloud server

### Actual behaviour
Shows the domain of the user's username and the server's hostname

**Example:**
If user is called user@domain.com and the hostname of the server is owncloud.domain.com, it will show domain.com@owncloud.domain.com

![image](https://user-images.githubusercontent.com/3529874/44249792-e5ab2d80-a234-11e8-88eb-091423cc8d73.png)

### Steps to reproduce
1. Create a user with an email address as the username (eg. user@domain.com)
2. Configure the sync client with this user
3. Create a file
4. Force the client to sync
5. Go to Activity -> Server Activity and check the right column and it will say "1 minute(s) ago on domain.com@hostname"

### Client configuration
Client version: 2.4.3

Operating system: Ubuntu and Windows

Qt version used by client package (Linux only, see also Settings dialog): 5.6.2

Client package (From ownCloud or distro) (Linux only): ownCloud

**Comment by michaelstingl** [comment]
Problem is, client hides a part of the username.

User: `aa@bb.com`
Host: `example.de`

Client displays: `bb.com@example.de`
Correct would be: `aa@bb.com@example.de`

I don't really have a problem with `aa@bb.com@example.de`. I think this is what we call _Federation ID_. @pmaier1 Is there any convention how we display user+host?

We could also discuss using `cloud.domain.com (username)`, but it seems the right column has fixed width and will probably hide most parts.

![macos_10_13](https://user-images.githubusercontent.com/214010/44269418-c2807e00-a234-11e8-91e9-02776f82e699.png)

We also use `username@host` on other places, so we would have to change it there as well:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/31886272-f2ae6532-b7f3-11e7-88c2-16f672c02744.png"/>
</p>

(from https://github.com/owncloud/client/pull/6113#issuecomment-338626327 )

**Comment by guruz** [comment]
> I don't really have a problem with aa@bb.com@example.de

+1
There's a bug somewhere, we're cutting away too much if there is an '@'

**Comment by ogoffart** [comment]
Ah ok, i misunderstood the problem.
Fix in https://github.com/owncloud/client/pull/6731

**Comment by michaelstingl** [comment]
@ogoffart strange, just tested with `ownCloud-qt5.10.1-2.5.0.10453-daily20180827.pkg`, and no username is visible at all in the activity tab. Only the hostname is shown:

![macos_10_13](https://user-images.githubusercontent.com/214010/44987663-3edec500-af88-11e8-9bcf-9de4199b8d25.png)

**Comment by ogoffart** [comment]
@michaelstingl I don't see what's wrong in the screenshot.

I think the was never supposed to be there.  (The code explicitly removes the username since it shows the account, in commit 3bccfb89934d13c9391275e99aa5dcb246439f0b )

If one should show the user name, then that can be changed.

**Comment by ogoffart** [comment]
Ah Ok. The original issue was about the fact that the removal of the username was not working properly if the username contained a '@'.

But if we do not want to remove the username, that can also be done.

**Comment by ogoffart** [comment]
So to summarize:  Since the time the activity tab was created, it normally did not have the user name. But there was a bug (reported by this bug report), which made that some part of the user name would show there if the username had a '@'.

That bug was fixed with PR #6731 , but it was asked later to actually put the user in there, so it was quickly amended with PR #6763,  which is now the state in 2.5.0
(I believe that this number is indeed is indeed part of the *Federation ID* that, was asked for)

It would be possible to change the dav user with the dav display name (which would typically be the full name)

Note that there are many location that we show the account name, and they currently most use this  `dav_user@hostname` format  (via the `Account::displayName` function)  
I believe we should keep everything the same.

@michaelstingl : what should be placed there?

**Comment by ogoffart** [comment]
Personally, i'd put   `cloud.domain.com (User Name)`    (where User Name is the dav display name  (most likely the full name of the user)

**Comment by amc2002** [comment]
Thanks for the summary. In my case, I can't see what the full ID is because there is no column scroll or resize. We use LDAP and those ID's are what appear in the "Username" field. I didn't realize there had never been an ID in that client column before. Thanks again for explaining.

**Comment by michaelstingl** [comment]
> I can't see what the full ID is because there is no column scroll or resize.

Yeah, I get your point.

I think we'd need proper columns and headers, with the option to resize column width etc. Probably option to filter by account too…  All tabs in the Activity view should work similar. As a temporary solution, we could go back to the previous implementation, and build it better for one of the next releases…

**Comment by ogoffart** [comment]
This cannot be "quickly enabled". The activity view has its own delegate that draws everything.

**Comment by HanaGemela** [comment]
Column resizing, filtering etc moved in https://github.com/owncloud/client/issues/7619
2.6.1-daily20191127 (build 12791), macOS 10.15.1 shows `cloud.domain.com (User Name)`
