### ISSUE TITLE
Crash during client update

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#6740]
When trying to update ownCloud 2.5 to the latest version through the built-in updater, it just crashes.
Crash dumps: bp-c3a7c8a5-0730-41ce-ad64-0b5ed2180824 and bp-5cecaf2e-52c2-4f92-a1ba-9e82d2180824

### Expected behaviour
Updater should not crash.

### Actual behaviour
Updater crashes reliably every time I try to update to the latest version. Verified on both Windows 7 and Windows 10.

### Steps to reproduce
1. Launch ownCloud 2.5 build 10372
2. Accept offer to update to build 10516
3. Watch it crash instantly.

**Comment by ogoffart** [comment]
I think this was the crash that was fixed in 2.4.3 / 2.5 beta 2, with commit 45bf2e9023761f261e32764f351cf936e8eb0226
