### ISSUE TITLE
Max file size is ignored 

### ISSUE THREAD

**Issue by tomneedham** [owncloud/client#6747]
Steps to reproduce:
1. Make sure your desktop client is connected and synced.
2. Upload a file which exceeds the maximum file size.
3. Upload will start even when file exceeds maximum allowed size. Once finished, user will receive only "Connection timeout" error without clear message about the exceeded file size.

**Comment by michaelstingl** [comment]
@tomneedham where/how did you configure maximum file size ?

**Comment by ogoffart** [comment]
There is no concept of max size in the desktop client.

Is there an API on the server to get the max allowed size?
