### ISSUE TITLE
User/group share: Show <shareWithAdditionalInfo> in autocompletion of shares

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#6749]
oC users can have same displayname, only username or email is different:

![users_-_owncloud_enterprise_edition](https://user-images.githubusercontent.com/214010/44736144-bcb95100-aaee-11e8-83a4-35e4d9d97a6b.png)

This make sharing UI difficult, but oC server got a solution for this:

![settings_-_owncloud_enterprise_edition](https://user-images.githubusercontent.com/214010/44736170-d65a9880-aaee-11e8-8af8-3764900a3624.png)

![com_bjango_istatmenus_network_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0_and_item-0](https://user-images.githubusercontent.com/214010/44736184-dd81a680-aaee-11e8-8303-205bdfb9f499.png)

### Expected behaviour
Users with same displayname should be easier to distinguish. oC server can add `User ID` or `Email address` in brackets after the displayname

### Actual behaviour
Users with same displayname can't be distinguished

### Server configuration
ownCloud version:
10.0.9

### Client configuration
Client version:
ownCloud-qt5.10.1-2.5.0.10453-daily20180827.pkg

Operating system:
macOS

### API

Response with `shareWithAdditionalInfo` = `None`:

```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <exact>
   <users/>
   <groups/>
   <remotes/>
  </exact>
  <users>
   <element>
    <label>Michael</label>
    <value>
     <shareType>0</shareType>
     <shareWith>michael1</shareWith>
    </value>
   </element>
   <element>
    <label>Michael</label>
    <value>
     <shareType>0</shareType>
     <shareWith>michael2</shareWith>
    </value>
   </element>
  </users>
  <groups/>
  <remotes/>
 </data>
</ocs>
```

Response with `shareWithAdditionalInfo` = `User ID`:

```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <exact>
   <users/>
   <groups/>
   <remotes/>
  </exact>
  <users>
   <element>
    <label>Michael</label>
    <value>
     <shareType>0</shareType>
     <shareWith>michael1</shareWith>
     <shareWithAdditionalInfo>michael1</shareWithAdditionalInfo>
    </value>
   </element>
   <element>
    <label>Michael</label>
    <value>
     <shareType>0</shareType>
     <shareWith>michael2</shareWith>
     <shareWithAdditionalInfo>michael2</shareWithAdditionalInfo>
    </value>
   </element>
  </users>
  <groups/>
  <remotes/>
 </data>
</ocs>
```

Response with `shareWithAdditionalInfo` = Email address`:

```
<?xml version="1.0"?>
<ocs>
 <meta>
  <status>ok</status>
  <statuscode>100</statuscode>
  <message>OK</message>
  <totalitems></totalitems>
  <itemsperpage></itemsperpage>
 </meta>
 <data>
  <exact>
   <users/>
   <groups/>
   <remotes/>
  </exact>
  <users>
   <element>
    <label>Michael</label>
    <value>
     <shareType>0</shareType>
     <shareWith>michael1</shareWith>
     <shareWithAdditionalInfo>michael1@example.com</shareWithAdditionalInfo>
    </value>
   </element>
   <element>
    <label>Michael</label>
    <value>
     <shareType>0</shareType>
     <shareWith>michael2</shareWith>
     <shareWithAdditionalInfo>michael2@example.com</shareWithAdditionalInfo>
    </value>
   </element>
  </users>
  <groups/>
  <remotes/>
 </data>
</ocs>
```

**Comment by ogoffart** [comment]
@michaelstingl   Is this already implemented on the server? What is the exact query to do?
I tried `ocs/v1.php/apps/files_sharing/api/v1/sharees?shareWithAdditionalInfo=Email%20address`   But that's not valid.

Is that not something we would fix by showing the server page?

**Comment by guruz** [comment]
I also don't understand it. The [screenshot](https://user-images.githubusercontent.com/214010/44736170-d65a9880-aaee-11e8-8af8-3764900a3624.png) above looks like a server configuration setting, so this should be automatic by the server?
The client would just use the same query as before and it would just work?
(CC @PVince81 )

**Comment by michaelstingl** [comment]
> I tried `ocs/v1.php/apps/files_sharing/api/v1/sharees?shareWithAdditionalInfo=Email%20address` But that's not valid.

No, the clients can't control what is shown. Just show the content of `<shareWithAdditionalInfo>michael2</shareWithAdditionalInfo>` in round brackets after displayname.

**Comment by PVince81** [comment]
as far as I remember we added it in a separate response field to avoid breaking existing behavior.
also it has the benefit to make it possible to format this information differently (ex: different color like grey) from the actual label/display name

**Comment by ogoffart** [comment]
What version of the server implements this ?
I just pulled master, and i don't see the `shareWithAdditionalInfo`

**Comment by michaelstingl** [comment]
The server admin needs to configure the sharing settings first:

![settings_-_owncloud_enterprise_edition](https://user-images.githubusercontent.com/214010/44736170-d65a9880-aaee-11e8-8af8-3764900a3624.png)

**Comment by ogoffart** [comment]
@michaelstingl   I don't seem to find these config option.  where is it? Do i need a special app?

**Comment by guruz** [comment]
@michaelstingl Please test with Monday's nightly.

**Comment by guruz** [comment]
Somehow i thought it was friday. Damn.

**Comment by michaelstingl** [comment]
Will do…
