### ISSUE TITLE
Ownclound removes all files from client desktop and the resyncs data back to clients when extarnal nas or smb share goes offline

### ISSUE THREAD

**Issue by johanbt** [owncloud/client#6751]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by johanbt** [comment]
### Server configuration
Operating system: Ubuntu 16.04 lts

Web server: 

apache2 -v
Server version: Apache/2.4.18 (Ubuntu)
Server built:   2018-06-07T19:43:03

Database:

dpkg -l | grep mariadb
ii  mariadb-client-10.0                  10.0.36-0ubuntu0.16.04.1                   amd64        MariaDB database client binaries
ii  mariadb-client-core-10.0             10.0.36-0ubuntu0.16.04.1                   amd64        MariaDB database core client binaries
ii  mariadb-common                       10.0.36-0ubuntu0.16.04.1                   all          MariaDB common metapackage
ii  mariadb-server                       10.0.36-0ubuntu0.16.04.1                   all          MariaDB database server (metapackage depending on the latest version)
ii  mariadb-server-10.0                  10.0.36-0ubuntu0.16.04.1                   amd64        MariaDB database server binaries
ii  mariadb-server-core-10.0             10.0.36-0ubuntu0.16.04.1                   amd64        MariaDB database core server files

PHP version:

php -v
PHP 7.0.30-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

php -i | grep -i '^libxml'
libxml Version => 2.9.3
libxml
libXML support => active
libXML Compiled Version => 2.9.3
libXML Loaded Version => 20903
libXML streams => enabled
libxml2 Version => 2.9.3

ownCloud version:

System Status
installed	1
maintenance	
needsDbUpgrade	
version	10.0.8.5
versionstring	10.0.8
edition	Community
productname	ownCloud

Storage backend (external storage):

Freenas ixsystem storage solution

accessing Data over smb/cifs share

Also

Add additional drive to owncloud server owncloud accessing drive over smb/cifs share

**Comment by johanbt** [comment]
redis-server
29831:C 30 Aug 10:08:38.185 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
29831:C 30 Aug 10:08:38.185 # Redis version=4.0.10, bits=64, commit=00000000, modified=0, pid=29831, just started
29831:C 30 Aug 10:08:38.185 # Warning: no config file specified, using the default config. In order to specify a config file use redis-server /path/to/redis.conf
29831:M 30 Aug 10:08:38.185 * Increased maximum number of open files to 10032 (it was originally set to 1024).
29831:M 30 Aug 10:08:38.185 # Creating Server TCP listening socket *:6379: bind: Address already in use

**Comment by johanbt** [comment]
What I have seen is that if the storage unit or any smb share is down or the owncloud server cannot connect to it,it removes the files from the clients desktops, when the storage unit is online or the smb share the it resyncs

Can we config the server that it does not remove the files when the remote share or online storage is off line

**Comment by johanbt** [comment]
Line 145878: {“reqId”:“bde1f4ba-9f47-4e5c-bdf4-6d8b90f6460f”,“level”:4,“time”:“2018-08-29T20:20:03+00:00”,“remoteAddr”:“105.212.61.43”,“user”:“Lorealj”,“app”:“webdav”,“method”:“MOVE”,“url”:"/remote.php/dav/uploads/Lorealj/1088895322/.file",“message”:“Exception: {“Message”:“HTTP\/1.1 503 Failed to check file size: smb:\/\/192.168.88.81\/wip\/wip\/0013476_MBFS_AUS_Creative_Strategic%20Pitch\/0013476_MBFS_AUS_Creative_Strategic%20Pitch\/0013476_MBFS_AUS_Creative_Strategic%20Pitch_STUDIO\/WIP\/Pitch%20Doc\/Ujala%20DFM%20Pitch%20-%20Document%20FINALISED%20SLIDES%20v3%2020180829.pptx.ocTransferId1646376607.part”,“Exception”:“Sabre\\DAV\\Exception\\ServiceUnavailable”,“Code”:0,“Trace”:”#0 \/var\/www\/html\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php(172): OCA\\DAV\\Connector\\Sabre\\File->put(Resource id #87)\n#1 \/var\/www\/html\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Tree.php(314): OCA\\…
Line 145879: {“reqId”:“cf998518-d4dc-468e-8bdc-2ae1e9d1b370”,“level”:4,“time”:“2018-08-29T20:20:06+00:00”,“remoteAddr”:“105.212.61.43”,“user”:“samanthar”,“app”:“webdav”,“method”:“MOVE”,“url”:"/remote.php/dav/uploads/samanthar/1771724777/.file",“message”:“Exception: {“Message”:“HTTP\/1.1 503 Failed to check file size: smb:\/\/192.168.88.81\/wip\/wip\/0013476_MBFS_AUS_Creative_Strategic%20Pitch\/0013476_MBFS_AUS_Creative_Strategic%20Pitch\/0013476_MBFS_AUS_Creative_Strategic%20Pitch_STUDIO\/WIP\/Pitch%20Doc\/Ujala%20DFM%20Pitch%20-%20Document%20v1%2020180828%20Sam.pptx.ocTransferId1734515121.part”,“Exception”:“Sabre\\DAV\\Exception\\ServiceUnavailable”,“Code”:0,“Trace”:”#0 \/var\/www\/html\/owncloud\/apps\/dav\/lib\/Connector\/Sabre\/Directory.php(172): OCA\\DAV\\Connector\\Sabre\\File->put(Resource id #87)\n#1 \/var\/www\/html\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Tree.php(314): OCA\\DAV\\Conn…

**Comment by johanbt** [comment]
Owncloud

Runs in virtual environment vmware 6.5 on hp server

**Comment by johanbt** [comment]
when the share is down and shows 0 kb

the data is removed from the clients

**Comment by johanbt** [comment]
![image](https://user-images.githubusercontent.com/42835983/44848106-d9bc6400-ac55-11e8-8240-e885cc3ab1cc.png)

**Comment by johanbt** [comment]
![image](https://user-images.githubusercontent.com/42835983/44848152-053f4e80-ac56-11e8-97a2-809fa6b7a5e6.png)

**Comment by ogoffart** [comment]
I have not read in details the log yet, but in most case, this is because the server just report the files as removed instead of marking them as unavailable with the proper status.

**Comment by johanbt** [comment]
Good Day ogoffart

How can we not remove the files form the clients till the smb links are online again.

Thanks in Advance

Regards

Johan

**Comment by ogoffart** [comment]
Normally, the owncloud server should report the error 503 on the PROPFIND or other access telling that the files are temporarily unavailable.
If the owncloud server reports that the files are gone, this usually means they have been deleted and the client will proceed.

**Comment by michaelstingl** [comment]
@ogoffart thanks for clarification. @johanbt please address this issue in a server issue. /cc @PVince81
