### ISSUE TITLE
Win updater wants to replace new daily with old beta

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#6762]
![msedge_-_win10](https://user-images.githubusercontent.com/214010/44989608-b152a380-af8e-11e8-85e2-15b67250894d.png)

(Version 2.5.0daily20180903)

![cursor_and_msedge_-_win10](https://user-images.githubusercontent.com/214010/44989656-d3e4bc80-af8e-11e8-89e4-a3f6f6be876e.png)

![cursor_and_msedge_-_win10](https://user-images.githubusercontent.com/214010/44989780-3f2e8e80-af8f-11e8-9870-4aab32862f21.png)

### Expected behaviour
New daily build shouldn't be replaced with older beta version

### Actual behaviour
After installing the new daily build, win updater would like to replace it with older beta version.

### Steps to reproduce
1. Install `ownCloud-2.5.0.10589.-daily20180903.10537.msi`
2. Open ownCloud
3. Wait for update Notification

### Client configuration
Client version:
ownCloud-2.5.0.10589.-daily20180903.10537.msi

Operating system:
Win 10, 64-bit

OS language:
EN

Qt version used by client package (Linux only, see also Settings dialog):
Qt 5.11.1

@dschmidt @guruz Could you take care? This makes testing the daily builds a little confusing…

**Comment by guruz** [comment]
The build number of your daily is ownCloud-2.5.0.**10589.**-daily20180903.10537.msi
The build number of the beta2 is ownCloud-2.5.0.**10516.**-beta2.10506.msi
So in theory it should not update because 10589>10516. (The msi build numbers are also 10537>10506 but that should not play a role).
I could only think that somehow the additional dot is a problem? This is issue https://github.com/owncloud/enterprise/issues/2803 assigned to @dschmidt

**Comment by guruz** [comment]
When running beta2:
```
09-05 09:43:43:791 [ info gui.updater ]:	Checking for available update
09-05 09:43:43:791 [ info sync.accessmanager ]:	2 "" "https://updates.owncloud.com/client/?version=2.5.0.0&platform=win32&oem=ownCloud&versionsuffix=beta2&channel=beta&msi=true" has X-Request-ID "bb173d14-1d07-4535-bdd3-e5f033cf5de3"
```
Why is there no build number in there?

**Comment by guruz** [comment]
When running 2.5.0daily20180903:
```
09-05 09:47:19:360 [ info gui.updater ]:	Checking for available update
09-05 09:47:19:360 [ info sync.accessmanager ]:	2 "" "https://updates.owncloud.com/client/?version=2.5.0.0&platform=win32&oem=ownCloud&versionsuffix=daily20180903&channel=beta&msi=true" has X-Request-ID "6617cf73-d54f-4e97-881d-78730caf6ff1"
```
Also 2.5.0.0 instead of 2.5.0.10589

**Comment by guruz** [comment]
So this is what I had reported as https://github.com/owncloud/client/issues/6601 which was supposed to be fixed... errrrr.

**Comment by guruz** [comment]
@dschmidt ``` QString::fromLatin1(MIRALL_STRINGIFY(MIRALL_VERSION_FULL));``` is the one sent as ```version=```
From our repo:
```
VERSION.cmake:set( MIRALL_VERSION_FULL ${MIRALL_VERSION} )
VERSION.cmake:set( MIRALL_VERSION_FULL "${MIRALL_VERSION_FULL}.${MIRALL_VERSION_BUILD}" )
version.h.in:#define MIRALL_VERSION_FULL  @MIRALL_VERSION_FULL@
```
Are you setting ```MIRALL_VERSION_BUILD``` for MSI?

**Comment by dschmidt** [comment]
I implemented it in a branch, tested it and claimed it was fixed - apparently I forgot to branch that build script branch. It's merged now. New daily build in progress.

**Comment by dschmidt** [comment]
I fixed some more hiccups in the version handling in the msi build scripts, this is what we have now: https://download.owncloud.com/desktop/daily/ownCloud-2.5.0.10522.10556-daily20180905.msi

Can you please test everything works as expected now? https://github.com/owncloud/client/issues/6601 should be fixed too, I might have been wrong it was a separate issue.

**Comment by guruz** [comment]
Thanks @dschmidt this looks fixed.
I'm also not getting the update dialog anymore.

```
09-05 14:43:39:138 [ info gui.updater ]:	Checking for available update
09-05 14:43:39:138 [ info sync.accessmanager ]:	2 "" "https://updates.owncloud.com/client/?version=2.5.0.10522&platform=win32&oem=ownCloud&versionsuffix=daily20180905&channel=beta&msi=true" has X-Request-ID "c400ec6a-5b0d-476e-aba3-a12b1908df40"
```

![bildschirmfoto 2018-09-05 um 14 50 00](https://user-images.githubusercontent.com/959327/45094230-fefc1700-b11a-11e8-91d1-ae02e2e9cf0a.png)
![bildschirmfoto 2018-09-05 um 14 49 52](https://user-images.githubusercontent.com/959327/45094231-00c5da80-b11b-11e8-9d43-2f9948b0ff9b.png)
