### ISSUE TITLE
[VFS] [Win] Double-click on virtual file opens oC settings before file opens in application

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#6764]
![screenflow](https://user-images.githubusercontent.com/214010/44996569-de13b480-afa8-11e8-939a-e2aeacc7271a.gif)

### Expected behaviour
Double-click on virtual file should only trigger download and opens real in application

### Actual behaviour
Double-click on virtual file opens the settings view, then triggers download

### Steps to reproduce
1. Install `ownCloud-2.5.0.10589.-daily20180903.10537.msi`
2. Configure account with virtual files
3. Double-click on virtual file `test.txt`

### Client configuration
Client version:
`ownCloud-2.5.0.10589.-daily20180903.10537.msi`

Operating system:
MSEdge on Win10 (x64) Stable (17.17134) ([VM](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/)) with all updates applied

OS language:
EN

**Comment by guruz** [comment]
> Expected behaviour

Do we want to fix this at all? Showing the settings dialog could be a good way for now to show a "progress bar that shows download progress" before we have a proper way to display that (the project @ckamm is working on).

**Comment by michaelstingl** [comment]
On macOS, settings screen doesn't open, download starts directly. I personally prefer this behaviour.

We already have the "`$FILE has been downloaded`" notification. Maybe having also a "`download of $FILE has been started`" notification is sufficient.

**Comment by ckamm** [comment]
I think this happens because starting the second owncloud.exe will send the "please open this file" request as well as the "show the settings window" request to the main process. We could adjust this to send only the former.

**Comment by ckamm** [comment]
@guruz Yeah, looks like it. If it's that simple, feel free to do for 2.5.1.

**Comment by guruz** [comment]
@michaelstingl Please test on Windows with a nightly

**Comment by lazawan** [comment]
@guruz  i have just tested the new client 2.5.2 on windows 10 ,and it works fine :-)
