### ISSUE TITLE
[MSI] [Windows 10] odd tray icon / exe state

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6765]
i can see the oC settings window (oc10) but no tray icon.
i think it's related to msi installer half-assedly restarting tor quitting the previous version's owncloud.exe 
icon is back if i kill owncloud.exe from trask manager and restart it.

Can we somehow set MSI to always kill (and not restart or ask or anything) the owncloud.exe?

@dschmidt @michaelstingl have you seen this before?

**Comment by michaelstingl** [comment]
> @michaelstingl have you seen this before?

not that I'm aware of

**Comment by dschmidt** [comment]
It's discouraged to do that - we should find out what's actually causing this behavior. 
Will  look into it.

**Comment by TheOneRing** [comment]
Have't ever seen that in recent clients
