### ISSUE TITLE
Files with extensions marked as "ignored" (shouldn't synchronize) are synchronizing

### ISSUE THREAD

**Issue by voroyam** [owncloud/client#6768]
A user in central reported the following problem:

https://central.owncloud.org/t/files-with-extensions-marked-as-ignored-shouldnt-synchronize-are-synchronizing/15454

"vcortazar":

We have a win 10 laptop that synchronized files with extensions marked to be ignored, evidence attached. 

I already compared configurations with another computer, but it seems to be the same.

Am I missing something? 

I don't want those files being synchronizing with the client. 

Thanks in advanced for your kind help.

Regards

![image](https://user-images.githubusercontent.com/24212810/45209310-f3306200-b28c-11e8-8967-44157c1dd40d.png)

![image](https://user-images.githubusercontent.com/24212810/45209300-e9a6fa00-b28c-11e8-8e98-ca33a63fc046.png)

### Expected behaviour
files marked as "ignored" shouldn't be synchronized

### Actual behaviour
files marked as "ignored" are synchronizing

### Steps to reproduce
1. Sync from desktop client
2. 
3. 

### Server configuration
Operating system: ubuntu 14.04

Web server:  Apache 2.4.7

Database: MariaDB 5.5.59

PHP version: PHP 5.6.36

ownCloud version: 9.1.8

Storage backend (external storage):

### Client configuration

Client version: 2.4.3

Operating system:  Win 10

**Comment by guruz** [comment]
I replied on central.

**Comment by ogoffart** [comment]
Looks like an invalid issues.
The files shown in the screenshot are just the metadata database and log needed for the inner working of the client. It is not synchronized on the server.

**Comment by voroyam** [comment]
question from central:
is there anyway to “hide” those files? just for aesthetic purposes.

**Comment by voroyam** [comment]
question answered, is a windows 10 issue :D
