### ISSUE TITLE
[Linux] No translations for Qt builtin strings

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6774]
The three words 'Updates', 'Channel' and 'Close' should be translated to german:

![grafik](https://user-images.githubusercontent.com/1108546/45646993-121cc880-bac5-11e8-932c-5c1fe69f136a.png)

And the string in green: 

![grafik](https://user-images.githubusercontent.com/1108546/45647355-f960e280-bac5-11e8-85ea-e7fd0b57aa6a.png)

**Comment by ogoffart** [comment]
Need to be changed in transifex.

**Comment by ogoffart** [comment]
Close is correctly translated for me.  Maybe a packaging issue? Do you include the Qt translations in the packages?

As for the other ones, please update them in transifex.

**Comment by guruz** [comment]
I can't login to transifex anymore, the 'forgot password' link doesnt send me a mail :-(
Someone else speaking German needs to check..

**Comment by michaelstingl** [comment]
@guruz what is the action item for me? How can I help?

**Comment by guruz** [comment]
@michaelstingl Check transifex german translation and possibly add the words mentioned by @jnweiger

**Comment by michaelstingl** [comment]
Okay, understood 👍

**Comment by jnweiger** [comment]
Found it myself in https://www.transifex.com/owncloud-org/owncloud/translate/#de/client/

All strings from that screenhot now translated, except the Close button. That one does not seem to come from transifex.

@guruz If you have an idea how to make that translated, please reopen.

**Comment by jnweiger** [comment]
'Stabil' sounds awkwards to me, but we have that already in other places.

**Comment by guruz** [comment]
There is no "Close" button on macOS. 
But in the ignore list editor, there is "Abbrechen" and "OK"for me. They seem to come from Qt -> QDialogButtonBox::Cancel|QDialogButtonBox::Ok

So on macOS it works.

@jnweiger Which linux package and version exactly are you using? DEB or RPM?

**Comment by guruz** [comment]
@jnweiger What do you have in /opt/ownCloud/qt-5.10.1/share/qt5/translations ?

[This is also a bit odd](https://build.opensuse.org/public/build/isv:ownCloud:Qt5101/Ubuntu_18.10/x86_64/ocqt5101-qt5-qtbase/_log)?:
```
[  577s] Note: -headerdir is not a subdirectory of -prefix.
[  577s] Note: -libdir is not a subdirectory of -prefix.
[  577s] Note: -bindir is not a subdirectory of -prefix.
[  577s] Note: -datadir is not a subdirectory of -prefix.
[  577s] Note: -translationdir is not a subdirectory of -prefix.
[  577s] Note: -examplesdir is not a subdirectory of -prefix.
[  577s] Note: -archdatadir is not a subdirectory of -prefix.
[  577s] Note: -plugindir is not a subdirectory of -prefix.
[  577s] Note: -importdir is not a subdirectory of -prefix.
[  577s] Note: -hostdatadir is not a subdirectory of -hostprefix.
[  577s] Maybe you forgot to specify -prefix/-hostprefix?
```
I don't see any other copying in this build log than
```
[ 2970s] /usr/src/packages/BUILD/bin/qmake -install qinstall /usr/src/packages/BUILD/examples/widgets/tools/i18n/translations /usr/src/packages/BUILD/debian/tmp//opt/ownCloud/qt-5.10.1/lib/x86_64-linux-gnu/qt5/examples/widgets/tools/i18n/translations
```

**Comment by guruz** [comment]
On my German windows the ignore list editor is broken too.
I see "OK" and "Cancel" while everything else is German. We don't have any qt*.qm in the .exe dir only client*.qm

On my working Mac the files are
```
/Applications/testpilotcloud.app/Contents/Resources/Translations/qt_de.qm
/Applications/testpilotcloud.app/Contents/Resources/Translations/qtbase_de.qm
```

**Comment by jnweiger** [comment]
@guruz If that is the case, then it is probably broken since ever. Nothing we need for 2.5.1.

**Comment by guruz** [comment]
For MSI it's a regression.
For Linux I don't know, you're the packaging guy.
2.5.2 -> fine

**Comment by dschmidt** [comment]
@michaelstingl ???

**Comment by michaelstingl** [comment]
I thought only Qt related stuff is remaining in this issue. I didn't understand what the MSI has to do with Qt? In the other issue I understand, we're re-using the Qt translation for MSI?

**Comment by guruz** [comment]
@michaelstingl No ;-) Don't worry, @dschmidt will fix it for MSI. For NSIS it always worked.

**Comment by dschmidt** [comment]
https://download.owncloud.com/desktop/daily/testpilotcloud-2.5.1.10935.10824-daily20181030.msi

Should be fixed...

**Comment by ogoffart** [comment]
@dschmidt  on windows, but how about linux packages?

**Comment by dschmidt** [comment]
I can check..

**Comment by TheOneRing** [comment]
Fixed in current deployments
