### ISSUE TITLE
OWNCLOUD_CHUNKING_NG not working?

### ISSUE THREAD

**Issue by boydhako** [owncloud/client#6779]
https://github.com/owncloud/client/blob/92027e869230d82de1bbbd0d486ebf14bfc471f7/src/libsync/owncloudpropagator.cpp#L274-L280

So I'm using the Version 2.4.3 (build 10347) Mac OS X client. And it doesn't seem to be syncing large files. I already did the .htaccess and .user.ini changes and still nothing. I did `export OWNCLOUD_CHUNKING_NG=0` and still nothing. The file is 33MB.

Client reporting:
    9/18/18 09:18:23,       documents/Note_From_DR_Onopa.pdf,                      ownCloud,Server replied "406 Not Acceptable" to "PUT http://<redacted>/remote.php/dav/uploads/bako/1491225990/00000000" (skipped due to earlier error, trying again in 17 hour(s))

**Comment by ogoffart** [comment]
Maybe you can try the 2.5 version, this code has been changed.

Also the file was blacklisted for many hours. You need to reset the blacklist.
You can do that in 2.5 by clicking "force sync now"  from the context menu in the folder.

**Comment by boydhako** [comment]
> Maybe you can try the 2.5 version, this code has been changed.
> 
> Also the file was blacklisted for many hours. You need to reset the blacklist.
> You can do that in 2.5 by clicking "force sync now" from the context menu in the folder.

Almost... The error changed for the file. I updated to 2.5 and did the force sync now and now I get this....
`    9/20/18 00:51:37,                                   Note_From_DR_Onopa-Kaiser.pdf,                      ownCloud,Error transferring https://<redacted FQDN>/remote.php/dav/uploads/bako/1209018672/00000000 - server replied: `

**Comment by ogoffart** [comment]
Where you still setting the OWNCLOUD_CHUNKING_NG to "0"?

>  server replied:

What did the server replied? There should be an error with it.

**Comment by ogoffart** [comment]
I tested on my linux and the environment variable has the right effect.
Maybe another instance of owncloud client was still running?

**Comment by boydhako** [comment]
what running processes should I be looking for?

I tried doing a reboot. But, that doesn't exactly help since I can't set the env before it starts. Or at lease I don't know how to set it up on a Mac.

Of course it worked in GNU Linux. EVERYTHING DOES!!! #FREESOFTWAREFOUNDATION XD

**Comment by guruz** [comment]
For the record on macOS you can use Terminal.app and then run (all in one line):
```
OWNCLOUD_CHUNKING_NG=0  /Applications/owncloud.app/Contents/MacOS/owncloud --logfile - --logdebug
```

@boydhako There is normally no reason to bother with the ```OWNCLOUD_CHUNKING_NG``` variable so we should find out why you'd actually need this. You should be able to see the server's error message in the Terminal maybe:
```
OWNCLOUD_CHUNKING_NG=1  /Applications/owncloud.app/Contents/MacOS/owncloud --logfile - --logdebug
```
Can you paste the log snippet or error message here?

**Comment by boydhako** [comment]
Sorry for side tabling. Still having the issue...

=Client activity log=
    1/10/19 00:25:33,           LENOVO/Drivers/Wlan_LiteonNFA335/Install_CD/data2.cab,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/2975199310/00000000 - server replied: 
    1/10/19 00:25:25,           LENOVO/Drivers/Wlan_LiteonNFA335/Install_CD/data1.cab,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/3152145862/00000000 - server replied: 
    1/10/19 00:25:17,                  LENOVO/Drivers/TouchPad_Synaptics/SynTPRes.dll,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/3409131900/00000000 - server replied: 
    1/10/19 00:25:11,                                   Note_From_DR_Onopa-Kaiser.pdf,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/811623326/00000000 - server replied: 
    1/10/19 00:25:03,   LENOVO/Drivers/IntelVGA/Graphics/ocl_cpu_clang_compiler64.dll,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/363622384/00000000 - server replied: 
    1/10/19 00:24:44,                 LENOVO/Drivers/IntelVGA/Graphics/igdumdim64.dll,                      ownCloud,HTTP/2 protocol error
    1/10/19 00:24:40,                          LENOVO/Drivers/ME/DAL/vcredist_x64.exe,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/1921139113/00000000 - server replied:  (skipped due to earlier error, trying again in 22 hour(s))
    1/10/19 00:24:39,                          LENOVO/Drivers/EnergyManager/setup.exe,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/2459467484/00000000 - server replied: 
    1/10/19 00:24:37,   LENOVO/Drivers/IntelVGA/Graphics/ocl_cpu_clang_compiler32.dll,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/3978429411/00000000 - server replied:  (skipped due to earlier error, trying again in 22 hour(s))
    1/10/19 00:24:37,                 LENOVO/Drivers/IntelVGA/Graphics/libmfxhw64.dll,                      ownCloud,HTTP/2 protocol error
    1/10/19 00:24:29,                 LENOVO/Drivers/IntelVGA/Graphics/libmfxhw32.dll,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/1598356896/00000000 - server replied:  (skipped due to earlier error, trying again in 24 hour(s))
    1/10/19 00:24:29,                 LENOVO/Drivers/IntelVGA/Graphics/igdumdim32.dll,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/2684953069/00000000 - server replied:  (skipped due to earlier error, trying again in 1 minute(s))
    1/10/19 00:24:29,                   LENOVO/Drivers/IntelVGA/Graphics/igdfcl64.dll,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/251798008/00000000 - server replied:  (skipped due to earlier error, trying again in 42 minute(s))
    1/10/19 00:24:29,                   LENOVO/Drivers/IntelVGA/Graphics/igdfcl32.dll,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/2843774564/00000000 - server replied:  (skipped due to earlier error, trying again in 24 hour(s))
    1/10/19 00:24:29,                LENOVO/Drivers/IntelVGA/Graphics/igd10iumd64.dll,                      ownCloud,  Unknown error
    1/10/19 00:24:29,                        LENOVO/Drivers/BT_LiteonNFA335/setup.EXE,                      ownCloud,  Unknown error
    1/10/19 00:24:25,                LENOVO/Drivers/IntelVGA/Graphics/igd10iumd32.dll,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/4269516457/00000000 - server replied:  (skipped due to earlier error, trying again in 23 second(s))
    1/10/19 00:24:25,               LENOVO/Drivers/Audio/Vista64/MaxxVoiceAPO3064.dll,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/1863215328/00000000 - server replied: 
    1/10/19 00:24:22,                       LENOVO/Drivers/Audio/Vista64/RAVCpl64.exe,                      ownCloud,HTTP/2 protocol error
    1/10/19 00:24:17,                       LENOVO/Drivers/Audio/Vista64/RCORES64.dat,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/2323565279/.file - server replied:  (Chunks on server do not sum up to 56684544 but to 0) (skipped due to earlier error, trying again in 24 hour(s))
    1/10/19 00:24:17,                 LENOVO/Drivers/Audio/Vista64/MaxxAudioVnA64.dll,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/3797660921/00000000 - server replied: 
    1/10/19 00:24:09,                         LENOVO/Drivers/Audio/Vista/RtHDVCpl.exe,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/2476734628/00000000 - server replied: 
    1/10/19 00:24:02,                           LENOVO/Drivers/Audio/Vista/RCORES.dat,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/3025642519/00000000 - server replied: 
    1/10/19 00:23:57,             LENOVO/Drivers/Audio/Vista64/MaxxAudioRealtek64.dll,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/1469665484/00000000 - server replied:  (skipped due to earlier error, trying again in 40 minute(s))
    1/10/19 00:23:57,                   LENOVO/Drivers/Audio/Vista/MaxxVoiceAPO30.dll,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/4174811989/00000000 - server replied: 
    1/10/19 00:23:47,                     LENOVO/Drivers/Audio/Vista/MaxxAudioVnA.dll,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/3720665798/00000000 - server replied: 
    1/10/19 00:23:35,                 LENOVO/Drivers/Audio/PCEE4/DolbyHomeTheater.msi,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/2864049570/00000000 - server replied: 
    1/10/19 00:23:29,                 LENOVO/Drivers/Audio/Vista/MaxxAudioRealtek.dll,                      ownCloud,HTTP/2 protocol error
    1/10/19 00:23:24,               LENOVO/Drivers/Audio/PCEE4/DolbyAdvancedAudio.msi,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/1074821679/00000000 - server replied: 
    1/10/19 00:23:10,             LENOVO/Drivers/Audio/DS1/x86/DolbyDigitalPlusAA.msi,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/2175445055/00000000 - server replied: 
    1/10/19 00:23:08,             LENOVO/Drivers/Audio/DS1/x86/DolbyDigitalPlusHT.msi,                      ownCloud,HTTP/2 protocol error
    1/10/19 00:23:02,     LENOVO/Applications/McAfee/Factory/Apps/VSO/install_all.cab,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/1624994992/00000000 - server replied: 
    1/10/19 00:22:58,             LENOVO/Applications/McAfee/Apps/VSO/install_all.cab,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/3311234296/00000000 - server replied: 
    1/10/19 00:22:47,             LENOVO/Drivers/Audio/DS1/x64/DolbyDigitalPlusHT.msi,                      ownCloud,Error transferring https://cloud.boydhanaleiako.me/remote.php/dav/uploads/bako/4134688905/00000000 - server replied: 


=Requested log info=
See Attached
[owncloudclient.log](https://github.com/owncloud/client/files/2744811/owncloudclient.log)

**Comment by guruz** [comment]
@boydhako 

> HTTP/2 protocol error

Probably you can fix this by updating your Apache or nginx?

**Comment by boydhako** [comment]
> > HTTP/2 protocol error
> 
> Probably you can fix this by updating your Apache or nginx?

Hmm.... I'll see what I can do. It's on a shared host. I just noticed the requirement jumped to HTTPD 2.4 and I'm at 2.2.

```
Server version: Apache/2.2.34 (Unix)
Server built:   Sep 19 2017 15:19:52
Server's Module Magic Number: 20051115:43
Server loaded:  APR 1.5.2, APR-Util 1.5.4
Compiled using: APR 1.5.2, APR-Util 1.5.4
Architecture:   64-bit
Server MPM:     Worker
  threaded:     yes (fixed thread count)
    forked:     yes (variable process count)
Server compiled with....
 -D SECURITY_HOLE_PASS_AUTHORIZATION
 -D APACHE_MPM_DIR="server/mpm/worker"
 -D APR_HAS_SENDFILE
 -D APR_HAS_MMAP
 -D APR_HAVE_IPV6 (IPv4-mapped addresses enabled)
 -D APR_USE_SYSVSEM_SERIALIZE
 -D APR_USE_PTHREAD_SERIALIZE
 -D SINGLE_LISTEN_UNSERIALIZED_ACCEPT
 -D APR_HAS_OTHER_CHILD
 -D AP_HAVE_RELIABLE_PIPED_LOGS
 -D DYNAMIC_MODULE_LIMIT=128
 -D HTTPD_ROOT="/etc/httpd"
 -D SUEXEC_BIN="/usr/sbin/suexec"
 -D DEFAULT_SCOREBOARD="logs/apache_runtime_status"
 -D DEFAULT_ERRORLOG="logs/error_log"
 -D AP_TYPES_CONFIG_FILE="conf/mime.types"
 -D SERVER_CONFIG_FILE="conf/httpd.conf"

```

**Comment by guruz** [comment]
Disable HTTP2 then so it uses only HTTP1? Might not be handled by the Apache though but by something from your provider?

**Comment by TheOneRing** [comment]
HTTP2 setups are currently not supported, so HTTP2 support is disabled in recent clients.
https://github.com/owncloud/client/issues/7626
