### ISSUE TITLE
Win7, client 2.5.0, replacing more than 47 files at a time by virtual files impossible

### ISSUE THREAD

**Issue by sorenweber** [owncloud/client#6780]
### Expected behaviour
I select 48 files (jpeg-photos) or more, right-click and select ownCloud->Replace file(s) by virtual file, and the files will be replaced by virtual files.

### Actual behaviour
If I select 48 files or more, nothing happens. If I select 47 files or less, it works.

### Steps to reproduce
1. Select 48 files or more in Windows Explorer
2. Right-click and select ownCloud->Replace file(s) by virtual file
3. Observe that nothing happens

### Server configuration
Operating system: Windows 7 Enterprise 64-bit

Web server: Apache 2.4

Database: MySQL

PHP version: 7.0

ownCloud version: 10.0.9

Storage backend (external storage):

### Client configuration
Client version: 2.5.0

Operating system: Windows 7 Enterprise

OS language: US

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by ogoffart** [comment]
I just realize there is a 4K buffer that need to contains the concatenation of all the filename.
So if all the file names is bigger than about 4000 character, this won't work.

**Comment by ogoffart** [comment]
Should be fixed with https://github.com/owncloud/client/pull/6782 , thanks for the bug report!

**Comment by sorenweber** [comment]
> Should be fixed with #6782 , thanks for the bug report!

Awesome, thanks for fixing it!

**Comment by sorenweber** [comment]
I have verified the fix, and it works (both ways, i.e. replacing files with virtual files, and vice versa). I had to perform the recommended reboot after installation. Thank you!
