### ISSUE TITLE
[macOS] installation package causes Privacy problems in Mojave

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#6781]
Feedback on Twitter:

![93c37d84-99b9-41f6-b5d8-7b462c3e97f8](https://user-images.githubusercontent.com/214010/45772327-a3b44380-bc47-11e8-8275-f214a74c21a0.jpeg)

[Source](url
https://twitter.com/grahamrpugh/status/1042379402481475584)

**Comment by michaelstingl** [comment]
Is there a new version of the installer available that could help here?

**Comment by guruz** [comment]
As @dschmidt correctly found out the problem is in admin/osx/post_install.sh.cmake
The code there can be removed, we don't need to show the ownCloud.app in the Finder window. Maybe we can get the installer instead to show a checkbox [x] launch ownCloud

**Comment by guruz** [comment]
@tomneedham @michaelstingl Please test with a nightly newer than Saturday 13th of october

**Comment by jnweiger** [comment]
=== Testing current 2.5 branch on osx 10.13 with a branded client

GOOD: The above allow dialog does not appear. 
BAD: there is no checkbox [x] launch ownCloud.

**Comment by jnweiger** [comment]
@dschmidt should I have seen that checkbox?

**Comment by michaelstingl** [comment]
I think we never had the checkbox in the Mac installers.
