### ISSUE TITLE
When upgrading previous version 2.4.x to version 2.5.0, an error occurred "missing api-ms-win-crt-runtime-l1-1-0.dll"

### ISSUE THREAD

**Issue by xmana** [owncloud/client#6788]
### Expected behavior
Successfully upgrade to the latest version

### Actual behavior
The previous version is uninstalled.
The latest version is not installed due to an error.

When upgrading previous version 2.4.x to version 2.5.0, an error occurred "missing api-ms-win-crt-runtime-l1-1-0.dll"

It turned out that the new version of the client uses the functions of the package
Microsoft Visual C ++ Redistributable for Visual Studio 2015.

Previous versions of the function of this package were not used.

As a result, on one wonderful day, more than 200 remote locations were without file sharing, scheduling and other capabilities.

The restoration work continues on the 4th day.

Really good manners do not imply the integration of an additional package into an installer whose functions use software?

### Playback Actions
1. Automatic client update.

### Server configuration
Operating system: Ubuntu 16.04.3 LTS

Web server:  nginx 1.13.8-1~xenial

Database: MySQL database server  5.7.20-0ubuntu0.16.04.1

PHP version: PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )

ownCloud version: 10.0.4.4

### Client configuration
Client version: 2.5.0.10598

Operating system: Windows 7 x86

OS language: Russian, English

**Comment by ogoffart** [comment]
Hi, Thanks for your bug report.
Do you remember the exact version you were upgrading from?
I assume you used the .msi installer.

@dschmidt  don't we ship the MSVC runtime ?

**Comment by xmana** [comment]
Good day!
Our network has about 220 remote points. 
Over the past few days, by hand, in different ways, we had to restore a network of approximately 160 remote locations.
When building a file sharing network, client version 2.4.0.8894 was used.
Later it was automatically updated.
I find it difficult to say exactly, but in most cases there was a client version 2.4.3.
The problem arose, and still continues to occur, with automatic updating of the client to version 2.5 (probably the client uses msi to update itself).

**Comment by xmana** [comment]
P.S.:
I apologize, I clarify, the version with which the construction of the network began, 2.3.2.6928.
All clients have been configured to auto-update.

**Comment by dschmidt** [comment]
Yes, we ship the MSVC runtime dlls but what's missing here is the Universal CRT, which you get when you keep your systems up to date or you need to follow this documentation for the stable release for now:
https://docs.microsoft.com/en-us/cpp/ide/universal-crt-deployment?view=vs-2017

It used to be impossible to ship the Universal CRT with an application, but apparently that changed and we might be able to resolve this issue with outdated systems for 2.5.1.
Please give this daily build a try:
https://download.owncloud.com/desktop/daily/ownCloud-2.5.1.10741.10684-daily20181003.msi

**Comment by xmana** [comment]
Thanks for the prompt response to our problem.

True, the situation has not changed today, the remaining remote locations continue to be updated to version 2.5.0, via the stable channel.

Well, in principle, the problem can be considered closed.

We will monitor the timely update of the system.
 
Thanks again for the help.
