### ISSUE TITLE
Repository broken?

### ISSUE THREAD

**Issue by marcorighi** [owncloud/client#6789]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by DeepDiver1975** [comment]
no content -> close

**Comment by repsorp** [comment]
ubuntu 16.04

'sudo apt update' give the following error message:

E: The repository 'http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

![capture du 2018-10-03 13-20-41](https://user-images.githubusercontent.com/6297032/46407772-45d82f00-c710-11e8-8295-789791010fca.png)

**Comment by karakayasemi** [comment]
![image](https://user-images.githubusercontent.com/14157973/46407992-58a33180-c719-11e8-88ea-e902b25a9c97.png)

Looks like the problem fixed.

**Comment by repsorp** [comment]
Still the same error message here:
E: The repository 'http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04 Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.

**Comment by repsorp** [comment]
There's some kind of IP address issue...
Ign:97 http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_16.04  InRelease
Ign:98 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  InRelease
Err:99 http://download.opensuse.org/repositories/home:/manuelschneid3r/xUbuntu_16.04  Release
  Connection failed [IP: 130.57.72.10 80]
Err:100 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  Release
  Could not connect to download.opensuse.org:80 (130.57.72.10), connection timed out [IP: 130.57.72.10 80]

While pinging is ok though...
PING 130.57.72.10 (130.57.72.10) 56(84) bytes of data.
64 bytes from 130.57.72.10: icmp_seq=5 ttl=46 time=270 ms
64 bytes from 130.57.72.10: icmp_seq=6 ttl=46 time=293 ms
64 bytes from 130.57.72.10: icmp_seq=7 ttl=46 time=213 ms
64 bytes from 130.57.72.10: icmp_seq=8 ttl=46 time=236 ms
64 bytes from 130.57.72.10: icmp_seq=9 ttl=46 time=168 ms
64 bytes from 130.57.72.10: icmp_seq=10 ttl=46 time=281 ms
64 bytes from 130.57.72.10: icmp_seq=11 ttl=46 time=201 ms
64 bytes from 130.57.72.10: icmp_seq=12 ttl=46 time=223 ms
64 bytes from 130.57.72.10: icmp_seq=13 ttl=46 time=183 ms
64 bytes from 130.57.72.10: icmp_seq=14 ttl=46 time=206 ms
64 bytes from 130.57.72.10: icmp_seq=15 ttl=46 time=292 ms
64 bytes from 130.57.72.10: icmp_seq=16 ttl=46 time=168 ms
64 bytes from 130.57.72.10: icmp_seq=17 ttl=46 time=235 ms
64 bytes from 130.57.72.10: icmp_seq=18 ttl=46 time=258 ms
64 bytes from 130.57.72.10: icmp_seq=19 ttl=46 time=280 ms
64 bytes from 130.57.72.10: icmp_seq=20 ttl=46 time=200 ms
64 bytes from 130.57.72.10: icmp_seq=21 ttl=46 time=222 ms
64 bytes from 130.57.72.10: icmp_seq=22 ttl=46 time=245 ms
64 bytes from 130.57.72.10: icmp_seq=23 ttl=46 time=268 ms
64 bytes from 130.57.72.10: icmp_seq=24 ttl=46 time=290 ms
64 bytes from 130.57.72.10: icmp_seq=25 ttl=46 time=211 ms
64 bytes from 130.57.72.10: icmp_seq=26 ttl=46 time=234 ms

**Comment by repsorp** [comment]
seems to be working now

**Comment by guruz** [comment]
We will probably switch from opensuse.org to owncloud.org repositories so this doesn't affect us anymore later :) 

CC @jnweiger
