### ISSUE TITLE
Activity message on file upload (dropbox target): Server does not support X-OC-MTime

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#6797]
### Expected behaviour
Upload file

### Actual behaviour
File not synced with error message: ``Server does notsupport X-OC-MTime``
Shown in activity, not synced
Files shows red crossed sync button
After some minutes, the file gets green and the client error message is gone
The file is also visible via the browser

### Steps to reproduce
1. Create a dropbox mount on the server and let the mount sync to the client
2. Add a file via local filesystem eg ``test.txt`` (no upper / lower case issue as it is already lower case)
3. Watch the client activity

### Server configuration
Operating system: Ubuntu 16.04

Web server: nginx

Database: mysql

PHP version: 7.0

ownCloud version: 10.0.10 (Stable)

Storage backend (external storage): local, smb, ftp, dropbox

### Client configuration
Client version: 2.5.0

Operating system: W10x64

OS language: DE

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: 

2. Web server error log:
no issues

3. Server logfile: ownCloud log (data/owncloud.log):
no issues

**Comment by ogoffart** [comment]
The server must return the `X-OC-MTime: accepted` header.  
@PVince81  Any reason this header would not be present?

**Comment by PVince81** [comment]
As far as I remember, the upload code tries to do a `touch()` on the target storage to adjust the mtime. If the target server doesn't support touch() and returns false, it assumes the mtime was not accepted and doesn't return that header.

Looking at https://github.com/owncloud/core/blob/v10.0.10/lib/private/Files/Storage/Flysystem.php#L224 which is the base class from the Dropbox implementation, it looks like setting mtime isn't supported by the Flysystem API at all.

**Comment by PVince81** [comment]
@ogoffart wasn't the older client behavior different, where if the header isn't returned it would try to do a PROPPATCH with the mtime afterwards ? Now even if it did, the mtime would not be settable due to the same reasons stated above.

**Comment by PVince81** [comment]
also see https://github.com/owncloud/core/blob/v10.0.10/apps/dav/lib/Connector/Sabre/File.php#L99

now this feels like a design inconsistency: in oc_filecache we have two columns, "storage_mtime" and "mtime" and the purpose of "mtime" is to be able to hold whatever mtime the client sent while the "storage_mtime" is whatever value the storage has now. In an ideal case they are identical but for cases where the storage does not support "touch", "storage_mtime" would be whatever value the storage assigns the file after writing is completed.

A possible fix would be to change the current behavior to always accept the mtime and simply store it there. Need to think of potential side effects though.

**Comment by ogoffart** [comment]
> @ogoffart wasn't the older client behavior different, where if the header isn't returned it would try to do a PROPPATCH with the mtime afterwards ? 

We do no longer call propatch since we got rid of the neon dependency in mirall 2.1. (At the time already, we were no longer supporting server which did not support the X-OC-MTime. (And I thought that it would be always accepted if the server supports it)

In other words, this is an error since 2.1, and nobody who had ownCloud > 6.0  complained about it  (that i know of)

But maybe we can just remove this error as it does not really need to be an error in the first place.

**Comment by mmattel** [comment]
closing as #6800 has been merged
