### ISSUE TITLE
Desktop client 2.5.0 shows generic icons

### ISSUE THREAD

**Issue by kiuru** [owncloud/client#6803]
I updated the desktop client today and then every folders' and files' icon changed to generic.

Client configuration
Client version: 2.5.0
Operating system: Windows 10
OS language: English

![image](https://user-images.githubusercontent.com/3456027/46716649-9221f280-cc6d-11e8-9e7b-174b9a2a24a4.png)

**Comment by kiuru** [comment]
This problem seems to be solved after I upgrade my owncloud server to 10.0.10. At this moment every icons is showing correctly.

**Comment by michaelstingl** [comment]
Other users reported, a reboot of the machine also helped.

**Comment by guruz** [comment]
@kiuru Do you remember if you got https://github.com/owncloud/client/issues/6799 during installation?

**Comment by kiuru** [comment]
@guruz I didn't get any error messages during installation.
