### ISSUE TITLE
Single user unable to logon via windows sync client - web + other users all fine

### ISSUE THREAD

**Issue by gwes** [owncloud/client#6817]
**### Expected behaviour**
User can logon to the destkop syc client using their LDAP credentials.

**### Actual behaviour**
User can not logon to the destkop syc client using their LDAP credentials.

**### Steps to reproduce**
I'm not totally sure when this happened but it was brought to my attention after taking the owncloud server down for an update from 9.something to 10.0.10. The update did not go to plan so the server was down for some time whilst I had a fight with Ubuntu, PHP and owncloud.

We have 30 ish users that are synced with owncloud using the LDAP plugin. The users are members of a group called (not surprisingly) owncloud. To the best of my knowledge all of the other users are able to connect via either the web interface or via the windows / mac / iOS sync apps except One.One user is able to logon to the web interface but attempts to logon via the Windows sync app result in an “Access Forbidden by server” error.

Generating an App Specific password via the web interface and using that instead of the LDAP credentials does allow the user to logon but I am concerned that I might end up in a situation where all of my users, on all devices (maybe 100 bits of kit) will all need an app specific password entering and I don't much like the idea of that.

I have been chatting to a couple of the guys over at central.owncloud.org but they have run out of ideas.
(https://central.owncloud.org/t/single-user-receives-access-forbidden-when-using-desktop-sync-client/16267)

Any help that anyone can provide would be appreciated.

Gareth

**I have tried the following so far to resolve the issue;**
I have updated the sync client on the machine in question to 2.5, the problem persists (not sure what version it was before the update but probably 2.3.?).
I have tried on 3 different machines (another win7 pro on 2.5 and two windows 10 machines one at 2.5 the other at 2.4.1) with the same result.
I have reset the users AD password and that change has propagated to the web interface.

**Server:**
Ubuntu 14.04.5, Apache2, PHP 5.6.38, Mysql 14.14

**Logs**
The relevant bit of client log (I think) is this. I’ve pulled the  url’s out but it’s all https

```
10-15 12:09:58:161 [ info gui.wizard ]:	Connect to url: “owncloud”
10-15 12:09:58:162 [ info sync.accessmanager ]:	6 “PROPFIND” “owncloud/remote.php/webdav/” has X-Request-ID “9b4703c1-91fe-40b5-a8f1-9a0229c8bdb1”
10-15 12:09:58:163 [ info sync.networkjob ]:	OCC::PropfindJob created for “owncloud” + “/” “OCC::OwncloudSetupWizard”
10-15 12:09:58:565 [ warning sync.credentials.http ]:	Stop request: Authentication failed for “owncloud/remote.php/webdav/”
10-15 12:09:58:566 [ warning sync.networkjob ]:	QNetworkReply::NetworkError(OperationCanceledError) “Operation canceled” QVariant(Invalid)
10-15 12:09:58:566 [ info sync.networkjob.propfind ]:	PROPFIND of QUrl(“owncloud/remote.php/webdav/”) FINISHED WITH STATUS “OperationCanceledError Operation canceled”
10-15 12:09:58:566 [ warning sync.networkjob.propfind ]:	not successful, http result code is 0 “”
```

Web server error.log, again, the relevant line I think is;
```
[Mon Oct 15 11:29:32.754265 2018] [negotiation:error] [pid 19661] [client MYIPADDRESS:63192] AH00687: Negotiation: discovered file(s) matching request: /var/www/owncloud/settings/users (None could be negotiated).
```

server Owncloud.log has the following line;
```
{“reqId”:“9b4703c1-91fe-40b5-a8f1-9a0229c8bdb1”,“level”:2,“time”:“2018-10-15T11:09:59+00:00”,“remoteAddr”:“MYIPADDRESS”,“user”:"–",“app”:“core”,“method”:“PROPFIND”,“url”:"/remote.php/webdav/",“message”:“Login failed: ‘USERNAME’ (Remote IP: ‘MYIPADDRESS’)”}
```

**Comment by ogoffart** [comment]
Looks like the server don't accept the password.
CC @DeepDiver1975

**Comment by gwes** [comment]
No, but the server does accept it when accessing via a web browser.

**Comment by gwes** [comment]
Any ideas anyone?

**Comment by michaelstingl** [comment]
You could check with `mitmproxy` what's the difference between the requests from the desktop client and the web UI.

**Comment by gwes** [comment]
Thanks @michaelstingl . I'll add that to the "things to learn how to use list" and see what it gives me.

**Comment by guruz** [comment]
A quick google leads me to this, can this be related? https://serverfault.com/a/548522/90786

**Comment by guruz** [comment]
Does it work with a normal WebDAV client? e.g. https://winscp.net/eng/index.php

https://YOURSERVER/owncloud/remote.php/webdav/

**Comment by hohwille** [comment]
FYI: I do have the same problem. Login with browser directly works fine, also WebDAV Clients like carddav-sync or Thunderbird (Inverse Sogo Connector) are able to connect and sync.

Why I can say in my case is that I am running owncloud 10.x on QNap device and wanted to have HTTPS access. The only way I could get this working was to create a proxy server on the QNap device. I am using ngingx for that via [docker-ssl-proxy](https://hub.docker.com/r/fsouza/docker-ssl-proxy/). I adjusted the config template like this:
```
worker_processes 1;
pid /run/nginx.pid;
daemon off;

events { worker_connections 1024; }

http {
    sendfile on;

    server {
        listen ${SSL_PORT};

        client_max_body_size ${CLIENT_MAX_BODY_SIZE};
        ssl_certificate     /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        ssl on;
        ssl_session_cache  builtin:1000  shared:SSL:10m;
        ssl_protocols  TLSv1 TLSv1.1 TLSv1.2;
        ssl_ciphers HIGH:!aNULL:!eNULL:!EXPORT:!CAMELLIA:!DES:!MD5:!PSK:!RC4;
        ssl_prefer_server_ciphers on;

        location / {
            proxy_pass  ${TARGET_SCHEME}://${TARGET_HOST}:${TARGET_PORT};
            proxy_redirect https://${TARGET_HOST} https://${TARGET_HOST}:${SSL_PORT};

            proxy_set_header Host              ${TARGET_HOST_HEADER};
            proxy_set_header X-Real-IP         $remote_addr;
            proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host  $host;
            proxy_set_header X-Forwarded-Port  ${SSL_PORT};
            proxy_set_header                   X-Real-IP $remote_addr;

            proxy_set_header Authorization $http_authorization;
            proxy_pass_header Authorization;

            proxy_buffer_size        128k;
            proxy_buffers            4 256k;
            proxy_busy_buffers_size  256k;
        }
    }
}
```

BTW: owncloud is unable to honor `X-Forwarded-Port` header. The redirects work only via `proxy_redirect` directive and not for all cases (e.g. logout does not work - I have to fix the port in the browser manually after failed redirect. It seems some things in owncloud implementation do not perfectly follow webstandards to work behind proxies).
As I was reading about `mitmproxy` in this thread I think this issue has something to do with owncloud sitting behind such proxy.
Do you have any further hint how to get this fixed?
I do not see any config option in owncloud to run it natively with TLS. Any ideas how to adjust the above proxy config to make it work? Why can all clients (even from various other vendors connect but owncloud desktop client not - sounds kind of wired)?

**Comment by hohwille** [comment]
FYI: I have bought official owncloud sync client for Android and it is also working fine.

**Comment by hohwille** [comment]
I also used "Click here to request an app password from the web interface" and generated such app password. However, with that generated password it does not work either.

**Comment by michaelstingl** [comment]
@hohwille Please open separate issues. Sounds different from the initial post in some aspects. Since you mention issues with the ownCloud server, maybe consider open issues in the core repo.

**Comment by michaelstingl** [comment]
> As I was reading about `mitmproxy` in this thread I think this issue has something to do with owncloud sitting behind such proxy.

I asked to debug with `mitmproxy`. I hope nobody runs `mitmproxy` for production 🙀

**Comment by TheOneRing** [comment]
Closing for long inactivity.
