### ISSUE TITLE
Raspbian ownCloud client: issues with large files

### ISSUE THREAD

**Issue by lonewolf1870** [owncloud/client#6821]
### Expected behaviour
I have an ownCloud server 10.0.10 running on Ubuntu 16.04, a Mac client (2.5.0) and I recently compiled an ownCloud client (v. 2.5.0) on a Raspberry PI3 with Raspbian Strecth (2018-06-27-raspbian-stretch.img).

Sync between client and server should work in both directions, regardless of file size

### Actual behaviour

Instead, sync between my Mac client and Ubuntu server works seamlessly in all cases (both GUI and headless)

But it is not working as expected on the client I build on Raspbian. Specifically, all goes well if the files are 1-2GB or smaller, but it's not working properly for larger files

### Steps to reproduce

**Compilation commands used**

sudo apt-get install cmake extra-cmake-modules doxygen
sudo apt-get install qtdeclarative5-dev qt5keychain-dev qttools5-dev
sudo apt-get install libsqlite3-dev libqt5webkit5-dev libkf5kio-dev
wget https://download.owncloud.com/desktop/stable/owncloudclient-XYZ
tar xf owncloudclient-XYZ
mkdir build; cd build
cmake -DWITH_DOC=TRUE -DCMAKE_BUILD_TYPE="Release" ../owncloudclient-XYZ
make

**Sync steps** (mostly tested in headless mode, but also the GUI had same issue the one time I tried):
1. I first sync a folder with small documents inside: everything gets synchronised
2. On the server, I place a large (2.6GB) file, e.g _IMAGE.iso_. Sync of the file begins. File is downloaded and sync reported as successful - but with an error. See _Logs_ section
3. I re-run the sync: the client **deletes the large file _IMAGE.iso_ from the server only**!
5. I re-start the sync a third time: even if the file _IMAGE.iso_ is present on the local folder, this is not uploaded on the server (I imagine because it's not present in the local DB file)
6. If I restore the large file on the server, this is re-downloaded at the next sync (4th). However, at the end the client does not rename it: two identical files will be present in the local folder, one named _IMAGE.iso_ and another _.IMAGE.iso.[STRING HERE]_
7. I restart the sync a 5th time, the client restart download entirely the _IMAGE.iso_ reproducing point 6.
8. And so on...

### Server configuration
Operating system: Ubuntu 16.04LTS
Web server: Apache/2.4.18 (Ubuntu) 
Database: mysql  Ver 14.14 Distrib 5.7.23, for Linux (x86_64) using  EditLine wrapper
PHP version: 7.2.11-2+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Oct 15 2018 11:40:04) ( NTS )
ownCloud version: 10.0.10
Storage backend (external storage):

### Client configuration
Client version: 2.5.0 manually built
Operating system: Raspbian Stretch
OS language: English
Qt version used by client package (Linux only, see also Settings dialog): Qt5
Client package (From ownCloud or distro) (Linux only):
Installation path of client: /usr/local/bin

### Client logs
I think the important bit (and only warning) in the log is the following:

>    10-13 00:24:33:955 [ warning sync.filesystem ]: Could not get modification time for "/home/pi/test/.IMAGE.iso.~697ae223" with csync, using QFileInfo
>    10-13 00:24:33:968 [ warning sync.fileitem ]: Failed to query the 'inode' for file  "/home/pi/test/IMAGE.iso"

**Comment by ogoffart** [comment]
I don't have a repbian setup to try it on.

Maybe the problem is caused because it is a 32bit architecture. But I believe this should not be a problem.

Do you see any error in the UI?
Any other information message or warning in the log about this file?  Can you paste maybe a more complete logs at the moment the file is downloaded.

**Comment by lonewolf1870** [comment]
By the way, everything was working fine up to few months ago, when for other reasons I stopped syncing daily the Raspberry and the server...

At the time, I was on server 9.1 (I suppose, I can't remember honestly) and client client version 2.3.2 that I got from here: https://wiki.sgripon.net/doku.php/building_owncloud_client_for_raspberry_pi

When I decided to resume syncing the machines, I decided to upgrade the client too and I noticed this issue

**Comment by guruz** [comment]
> 10-13 00:24:33:955 [ warning sync.filesystem ]: Could not get modification time for "/home/pi/test/.IMAGE.iso.~697ae223" with csync, using QFileInfo
>  10-13 00:24:33:968 [ warning sync.fileitem ]: Failed to query the 'inode' for file "/home/pi/test/IMAGE.iso"

Can you give us the output of `mount`? 
If it is size dependent, then there is really something odd about your system. 

(Also, Have you thought about fake SD cards with less capacity?)

**Comment by ogoffart** [comment]
```
10-13 02:25:03:705 [ debug sync.networkjob.get ]	[ OCC::GETFileJob::slotReadyRead ]:	Actually finished!
10-13 02:26:24:910 [ warning sync.filesystem ]:	Could not get modification time for "/home/pi/test/.2g.~2d321a0f" with csync, using QFileInfo
10-13 02:26:24:941 [ warning sync.fileitem ]:	Failed to query the 'inode' for file  "/home/pi/test/2g"
10-13 02:26:24:945 [ info sync.database ]:	Updating file record for path: "2g" inode: 0 modtime: 1539851892 type: 0 etag: "dd5f46e6903456c58c4da71fb0c61c7d" fileId: "00439712ocq2bqutkbec" remotePerm: "WDNVR" fileSize: 2147483648 checksum: "SHA1:91d50642dd930e9542c39d36f0516d45f4e1af0d"
```

Then next sync:

```
10-13 02:28:19:405 [ info sync.csync.updater ]:	item: 2g - item type 3 not iterated
```

The type 3 is `ItemTypeSkip` which can happen for the following reason:

- The call to _csync_vio_local_stat_mb fails, which can happen if `lstat` fails, which is likely since logs show that other call to stat also failed. I'd even bet it returns `EOVERFLOW` 
- the `st_mode` is not the one of a normal file

Skipping if stat fails is a very poor choice which leads to data loss.

We must address this issue.

**Comment by guruz** [comment]
@ogoffart then this should be in 2.5.x milestone?

**Comment by ogoffart** [comment]
The thing is that this is in the discovery which is changed completely in 2.6.
Supporting it in 2.5 means the work need to be done twice.

**Comment by guruz** [comment]
@ogoffart We have to keep 2.5 alive for a while because we removed WebKit in 2.6 ...

**Comment by ckamm** [comment]
@lonewolf1870 Sounds like you can potentially avoid the problem by compiling with `-D_FILE_OFFSET_BITS=64` on your 32bit system.

**Comment by lonewolf1870** [comment]
@ckamm thanks for the suggestion, but it didn't solve the problem
I upgraded the client to the lasted released version (2.5.4) and compiled with the flag you mentioned: still, files above 2GB are not sync 
And from my little knowledge it makes sense: the 32bit limit would apply to a 4GB file, not 2GB, wouldn't it?

**Comment by ckamm** [comment]
It might be, if something were using signed 32 bit integers for sizes. I think to solve this we'd need a developer to look at it directly on Raspbian.

**Comment by lonewolf1870** [comment]
As a side note, you don't need a Raspberry: I'm testing it on a VM using QEMU.
If needed, I can provide the steps for the VM creation

**Comment by ckamm** [comment]
Thanks! Unfortunately Raspbian is not an officially supported platform so it's unlikely we'll get around to looking at it soon. :/

**Comment by michaelstingl** [comment]
Win builds are 32-bit too and we don't have issues?

**Comment by TheOneRing** [comment]
Closing this issue as it has been inactive for a long period of time.
If the problem still occurs please reopen the issue.
