### ISSUE TITLE
Forbidden when Move or Rename Files or Folders

### ISSUE THREAD

**Issue by georgeoftown** [owncloud/client#6824]
### Expected behaviour
Move or rename file or folder

### Actual behaviour
403 Forbidden MOVE

### Steps to reproduce
1. Configure Client with Server Address ended with slash (Example https://owncloud.org/)
2. Sync something
3. Move or rename folder or file synced
4. Sync Error

### Server configuration
Operating system:
Debian 9.5
Web server: 
Apache/2.4.25
Database:
mysql Ver 15.1 Distrib 10.1.26-MariaDB
PHP version:
PHP 7.0.30-0+deb9u1
ownCloud version:
10.0.10

### Client configuration
Client version:
2.5.0 (build 10560)
Operating system:
Windows 10
OS language:
ES

### Logs

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
```
#=#=#=# Syncrun started 2018-10-18T11:56:20Z
#=#=#=#=# Propagation starts 2018-10-18T11:56:20Z (last step: 196 msec, total: 196 msec)
11:56:21||Pruebas/Prueba2 -> Pruebas/1|INST_RENAME|Up|1539862451|5bc86fa3018b9|0|00057074511b5315c9cf7|2|El servidor respondió "403 Forbidden" a "MOVE https://owncloud.org/remote.php/dav/files/aaaaaa.mmmmm/Pruebas/Prueba3"|403|0|0|fb133929-61e9-4e83-b085-4cb86af6c2a1|
11:56:21||Pruebas/2 -> Pruebas/23|INST_RENAME|Up|1539862435|5bc86fa7e0977|0|00057075511b5315c9cf7|2|El servidor respondió "403 Forbidden" a "MOVE https://owncloud.org/remote.php/dav/files/aaaaaa.mmmmm/Pruebas/2"|403|0|0|6790c65c-179f-44b8-b92c-347c81aff3c8|
#=#=#=# Syncrun finished 2018-10-18T11:56:20Z (last step: 171 msec, total: 368 msec)
```
2. Web server error log:
look the 3 slash together ///
```
111.111.111.111 - - [18/Oct/2018:10:26:05 +0000] "MOVE /remote.php/dav/files/aaaaaa.mmmmm/Prueba/Prueba3 HTTP/1.1" 403 297 ///remote.php/dav/files/aaaaaa.mmmmm/Prueba/Prueba2
```
3. Expected
```
111.111.111.111 - - [18/Oct/2018:10:27:23 +0000] "MOVE /remote.php/dav/files/aaaaaa.mmmmm/Prueba/Prueba3 HTTP/1.1" 201 - //remote.php/dav/files/aaaaaa.mmmmm/Prueba/Prueba4
```
4. Server logfile: ownCloud log (data/owncloud.log):
https://gist.github.com/georgeoftown/614821c3bef3ddc074893c5f65d0fd63#file-owncloud-log

## Possible solutions
1. Remove multiple slash at the beginning of _destination leaving only one 
https://github.com/owncloud/client/blob/319472e1797892afe84e844a20544d7085b34ca2/src/libsync/propagateremotemove.cpp#L50
2. Remove slash at the end of the url line on client file config owncloud.cfg
```
2\url=https://owncloud.org <-- works
2\url=https://owncloud.org/ <-- forbidden
```

**Comment by guruz** [comment]
@georgeoftown  As no one else is reporting this, I think this could be a problem of how you configured ownCloud/PHP in your Apache config? Can you paste this here?

**Comment by georgeoftown** [comment]
Here is the configuration we have

Apache conf
https://gist.github.com/georgeoftown/58a4c800a6c004401bb97180db8a22e9

Apache mpm
https://gist.github.com/georgeoftown/e3bde410a6112bfc3ef2aa1bcb4b7336

Apache php-fpm
https://gist.github.com/georgeoftown/dccd2ff469ff26134af9f93f8945fd2a

fpm pool conf
https://gist.github.com/georgeoftown/e50fd4dbd162bf66bc4a1f03596216e1

Thanks

**Comment by pumasloth** [comment]
@georgeoftown 
I have been having the same issues lately (seem to have started after 2.5 desktop client release, mostly with renaming/moves that have already been uploaded to the server.

I tried removing the slash in the owncloud.cfg (%AppData%\ownCloud), restarted the desktop client and uploaded some folders/files then renamed/moved them and haven't gotten an error yet.
2\url=https://owncloud.org <-- works
2\url=https://owncloud.org/ <-- forbidden

**Comment by ogoffart** [comment]
The problem is most likely the extra slash here:

https://github.com/owncloud/client/blob/319472e1797892afe84e844a20544d7085b34ca2/src/libsync/propagateremotemove.cpp#L92-L93

since the dav path already starts with a /.
Actually, Account::davPath only starts with a / when chunking-ng is enabled, so we can't just remove the /.
I'd hope QDir::cleanPath remove the useless slashes, but it seems it does not.

**Comment by guruz** [comment]
@ogoffart @pumasloth @georgeoftown ˜Thanks. we should fix this for 2.5.1

**Comment by ogoffart** [comment]
It turns out that QDir::cleanPath on windows leaves the starting slashes on windows, as it can mean something.

**Comment by georgeoftown** [comment]
Thanks
