### ISSUE TITLE
Client autonomously deletes files without reason

### ISSUE THREAD

**Issue by davedodo** [owncloud/client#6825]
### Expected behaviour
The client should not delete files that are not supposed to be deleted

### Actual behaviour
The client deletes files without reason

### Steps to reproduce
Unknown

### Server configuration
Operating system:
Ubuntu 16.04

Web server: 
Apache 2.4

Database:
MySQL 5.7

PHP version:
7.1.23

ownCloud version:
10.0.10

Storage backend (external storage):
No external storage

### Client configuration
Client version:
2.5.0

Operating system:
Windows 10 x64

OS language:
German

Installation path of client:
Default

During the past days, we experienced two mysterious cases of file deletions. Without any user interaction, the client deleted files on local machines as well as the server. From the web server logs, it looks (to me) like the files were deleted by a user on purpose, but they were not. I can see DELETE requests in the web server logs, e.g.:
`IP_ADDRESS - - [18/Oct/2018:01:33:24 +0200] "DELETE /remote.php/dav/files/_user_/_path-to-deleted-file_ HTTP/1.1" 204 589 "-" "Mozilla/5.0 (Windows) mirall/2.5.0 (build 10560)"`

We first encountered this phenomenon a few days ago. The client deleted a couple of video files that were not open on any local machine and there was definitely no user interaction. We were able to restore them from the owncloud trash bin.

Last night, a document was deleted and progress was lost. However, since the document was edited on two separate machines alternatingly, I cannot exactly reconstruct the chain of events that led to the loss of progress. I can only say that in the end the file was deleted on one of the two machines, while on the other machine the file was synced normally. There was a DELETE request for that file in the web server log also. (Is this expected?)

There is no mention of these files (deletions or otherwise) in the owncloud server log.

**Comment by michaelstingl** [comment]
Please let your client write some logs permanently the next few days if you expect this could happen again. Here you can find more information:
https://doc.owncloud.org/desktop/latest/troubleshooting.html#log-files

**Comment by guruz** [comment]
@davedodo What do you see in the client's ```.owncloudsync.log``` in the sync folder ?

**Comment by ogoffart** [comment]
We can't do anything about this issue without more information such as ways to reproduce or detailed client logs.
wrongly deleting file is a serious issue, and we try hard to to have such bugs, but i am not aware of any case when this could happen.

**Comment by guruz** [comment]
I'm moving this to 2.5.2 and hoping for an answer to https://github.com/owncloud/client/issues/6825#issuecomment-431287813

**Comment by rodmardo1** [comment]
Dear, we have presented the same problem, files are deleted alone from the user's PC and appear in the web client's trash, from where we can restore them. This will generate serious problems with the users. Please, if you could help us.

**Comment by guruz** [comment]
@rodmardo1 What do you see in the client's .owncloudsync.log in the sync folder for this specific file?
What do you see in the web server's access.log for this file?

**Comment by ogoffart** [comment]
We really need logs, or step to reproduce this issue.
We need to know why the client is deciding to remove these files.

Maybe this is related to the new local discovery caching. But I do not see how.

**Comment by ckamm** [comment]
Unfortunately not actionable, removing from milestone.

**Comment by ogoffart** [comment]
Closing issue, please re-open if you have more information

**Comment by davedodo** [comment]
It happened again last night. Sorry I couldn't get the log from my customer the last time. I am waiting for them to get home and send me the current log. I pray it contains the necessary information to fix this.

On the Apache server log I only see one single DELETE request for the file in question:

`_ip_address_ - - [18/Jul/2019:02:11:48 +0200] "DELETE /remote.php/dav/files/_user_/_path_to_file_ HTTP/1.1" 204 589 "-" "Mozilla/5.0 (Windows) mirall/2.5.4 (build 11415)"`

There is no mention of the file in the server's owncloud log. I'll post the client's log soon.

**Comment by pirunet** [comment]
Do you still have the problem? Can you post more logs? Did you use a Lenovo-Notebook?
