### ISSUE TITLE
Owncloudcmd dont sync after update to Owncloud 

### ISSUE THREAD

**Issue by joaquimferraz** [owncloud/client#6830]
### Expected behaviour
Tell us what should happen

### Actual behaviour
10-19 12:03:17:244 [ info sync.clientproxy ]:	Set proxy configuration to use system configuration
10-19 12:03:17:255 [ info sync.accessmanager ]:	2 "" "https://myserver.com.br/owncloud/ocs/v1.php/cloud/capabilities?format=json" has X-Request-ID "176df856-7130-4773-87b0-749a4fe40155"
10-19 12:03:17:255 [ info sync.networkjob ]:	OCC::JsonApiJob created for "https://myserver.com.br/owncloud" + "ocs/v1.php/cloud/capabilities" ""
10-19 12:03:17:480 [ info sync.networkjob.jsonapi ]:	JsonApiJob of QUrl("https://myserver.com.br/owncloud/ocs/v1.php/cloud/capabilities?format=json") FINISHED WITH STATUS QNetworkReply::NetworkError(NoError) ""
10-19 12:03:17:480 [ debug default ]	[ main(int, char**)::<lambda ]:	Server capabilities QJsonObject({"checksums":{"preferredUploadType":"SHA1","supportedTypes":["SHA1"]},"core":{"pollinterval":60,"status":{"edition":"Community","hostname":"LNXCLOUDWEB","installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"ownCloud","version":"10.0.10.4","versionstring":"10.0.10"},"webdav-root":"remote.php/webdav"},"dav":{"chunking":"1.0","reports":["search-files"]},"files":{"bigfilechunking":true,"blacklisted_files":[".htaccess"],"privateLinks":true,"undelete":true,"versioning":true},"files_sharing":{"api_enabled":true,"auto_accept_share":true,"can_share":true,"default_permissions":31,"federation":{"incoming":true,"outgoing":true},"group_sharing":true,"public":{"enabled":true,"expire_date":{"enabled":false},"multiple":true,"password":{"enforced":false,"enforced_for":{"read_only":false,"read_write":false,"upload_only":false}},"send_mail":true,"social_share":true,"supports_upload_only":true,"upload":true},"resharing":true,"search_min_length":2,"share_with_group_members_only":true,"share_with_membership_groups_only":true,"user":{"send_mail":true},"user_enumeration":{"enabled":true,"group_members_only":false}},"notifications":{"ocs-endpoints":["list","get","delete"]}})
10-19 12:03:17:482 [ info sync.database ]:	sqlite3 version "3.22.0"
10-19 12:03:17:482 [ info sync.database ]:	sqlite3 journal_mode= "wal"
10-19 12:03:17:484 [ info sync.engine ]:	There are 636917002240 bytes available at "/root/teste/"
10-19 12:03:17:484 [ info sync.engine ]:	Sync with existing sync journal
10-19 12:03:17:484 [ info sync.engine ]:	"Using Qt 5.9.5 SSL library OpenSSL 1.1.0g  2 Nov 2017 on Ubuntu 18.04.1 LTS"
10-19 12:03:17:484 [ info sync.engine ]:	NOT Using Selective Sync
10-19 12:03:17:484 [ info sync.engine ]:	#### Discovery start ####################################################
10-19 12:03:17:485 [ info sync.engine ]:	Server "" 
10-19 12:03:17:487 [ info sync.accessmanager ]:	6 "PROPFIND" "https://myserver.com.br/owncloud/remote.php/dav/files/testesip/" has X-Request-ID "d5fa6b7f-5c91-4d0a-9ea7-42034e95101a"
10-19 12:03:17:488 [ info sync.networkjob ]:	OCC::LsColJob created for "https://myserver.com.br/owncloud" + "" "OCC::DiscoverySingleDirectoryJob"
10-19 12:03:17:605 [ warning sync.networkjob ]:	QNetworkReply::NetworkError(ContentNotFoundError) "Server replied \"404 Not Found\" to \"PROPFIND https://myserver.com.br/owncloud/remote.php/dav/files/testesip/\"" QVariant(int, 404)
10-19 12:03:17:605 [ info sync.networkjob.lscol ]:	LSCOL of QUrl("https://myserver.com.br/owncloud/remote.php/dav/files/testesip/") FINISHED WITH STATUS QNetworkReply::NetworkError(ContentNotFoundError) "Server replied \"404 Not Found\" to \"PROPFIND https://myserver.com.br/owncloud/remote.php/dav/files/testesip/\""
10-19 12:03:17:606 [ warning sync.discovery ]:	LSCOL job error "Error transferring https://myserver.com.br/owncloud/remote.php/dav/files/testesip/ - server replied: Not Found" 404 QNetworkReply::NetworkError(ContentNotFoundError)
10-19 12:03:17:606 [ warning sync.engine ]:	ERROR during  csync_update :  "CSync failed to access "
10-19 12:03:17:606 [ info sync.database ]:	Closing DB "/root/teste/._sync_305eaacab98b.db"
10-19 12:03:17:607 [ info sync.engine ]:	CSync run took  122 ms
10-19 12:03:17:607 [ info sync.database ]:	Closing DB "/root/teste/._sync_305eaacab98b.db"

### Steps to reproduce
1. owncloudcmd -u user -p pass --trust teste https://myserver.com.br/owncloud/remote.php/webdav

### Server configuration
Operating system: Ubuntu 16.04

Web server: Apache 2

**Comment by joaquimferraz** [comment]
Owncloud Version: 10.0.10.4

**Comment by joaquimferraz** [comment]
root@MS-7A15:~# owncloudcmd -v
ownCloud version 2.4.1
Git revision cd60c2b88ac858339637575f124c58d88b42e78c
Using Qt 5.9.5, built against Qt 5.9.4
Using 'OpenSSL 1.1.0g  2 Nov 2017'

**Comment by michaelstingl** [comment]
Please test with the 2.5.0 linked from the ownCloud download page: https://owncloud.org/download/#owncloud-desktop-client-linux

**Comment by joaquimferraz** [comment]
I updated and it did not solve. I get https://owncloud.org/download/#owncloud-desktop-client-linux

root@MS-7A15:~# owncloudcmd -v
ownCloud version 2.5.0 (build 10213)
Git revision c739318335fab93ae049d93cb13787488af8f285
Using Qt 5.10.1, built against Qt 5.10.1
Using 'OpenSSL 1.0.2n  7 Dec 2017'

# owncloudcmd -u myuser -p password --trust /root/teste https://myserver.com.br/remote.php/webdav

output:

10-19 14:41:06:682 [ info sync.accessmanager ]:	2 "" "https://myserver.com.br/ocs/v1.php/cloud/capabilities?format=json" has X-Request-ID "6599d6c0-01cb-46c9-b77b-4a87cd2c7c14"
10-19 14:41:06:682 [ info sync.networkjob ]:	OCC::JsonApiJob created for "https://myserver.com.br" + "ocs/v1.php/cloud/capabilities" ""
10-19 14:41:06:851 [ info sync.networkjob.jsonapi ]:	JsonApiJob of QUrl("https://myserver.com.br/ocs/v1.php/cloud/capabilities?format=json") FINISHED WITH STATUS "OK"
10-19 14:41:06:852 [ debug default ]	[ main(int, char**)::<lambda ]:	Server capabilities QJsonObject({"checksums":{"preferredUploadType":"SHA1","supportedTypes":["SHA1"]},"core":{"pollinterval":60,"status":{"edition":"Community","hostname":"LNXCLOUDWEB","installed":true,"maintenance":false,"needsDbUpgrade":false,"productname":"ownCloud","version":"10.0.10.4","versionstring":"10.0.10"},"webdav-root":"remote.php/webdav"},"dav":{"chunking":"1.0","reports":["search-files"]},"files":{"bigfilechunking":true,"blacklisted_files":[".htaccess"],"privateLinks":true,"undelete":true,"versioning":true},"files_sharing":{"api_enabled":true,"auto_accept_share":true,"can_share":true,"default_permissions":31,"federation":{"incoming":true,"outgoing":true},"group_sharing":true,"public":{"enabled":true,"expire_date":{"enabled":false},"multiple":true,"password":{"enforced":false,"enforced_for":{"read_only":false,"read_write":false,"upload_only":false}},"send_mail":true,"social_share":true,"supports_upload_only":true,"upload":true},"resharing":true,"search_min_length":2,"share_with_group_members_only":true,"share_with_membership_groups_only":true,"user":{"send_mail":true},"user_enumeration":{"enabled":true,"group_members_only":false}},"notifications":{"ocs-endpoints":["list","get","delete"]}})
10-19 14:41:06:861 [ info sync.database ]:	sqlite3 version "3.22.0"
10-19 14:41:06:861 [ info sync.database ]:	sqlite3 journal_mode= "wal"
10-19 14:41:06:862 [ info sync.engine ]:	There are 636818698240 bytes available at "/root/teste/"
10-19 14:41:06:862 [ info sync.engine ]:	Sync with existing sync journal
10-19 14:41:06:862 [ info sync.engine ]:	"Using Qt 5.10.1 SSL library OpenSSL 1.0.2n  7 Dec 2017 on Ubuntu 18.04.1 LTS"
10-19 14:41:06:862 [ info sync.engine ]:	NOT Using Selective Sync
10-19 14:41:06:862 [ info sync.engine ]:	#### Discovery start ####################################################
10-19 14:41:06:862 [ info sync.engine ]:	Server "" 
10-19 14:41:06:862 [ info sync.csync.utils ]:	Memory: 441328K total size, 20636K resident, 18496K shared
10-19 14:41:06:863 [ info sync.csync.csync ]:	## Starting local discovery ##
10-19 14:41:06:863 [ info sync.csync.updater ]:	._sync_5b7caeed4c45.db-shm excluded  (1)
10-19 14:41:06:863 [ info sync.csync.updater ]:	._sync_de36892518a6.db excluded  (1)
10-19 14:41:06:863 [ info sync.csync.updater ]:	._sync_305eaacab98b.db excluded  (1)
10-19 14:41:06:863 [ info sync.csync.updater ]:	._sync_1818b6c188f8.db excluded  (1)
10-19 14:41:06:863 [ info sync.csync.updater ]:	._sync_85db17f1bc0f.db excluded  (1)
10-19 14:41:06:863 [ info sync.csync.updater ]:	._sync_5b7caeed4c45.db-wal excluded  (1)
10-19 14:41:06:863 [ info sync.csync.updater ]:	._sync_5b7caeed4c45.db excluded  (1)
10-19 14:41:06:863 [ info sync.csync.updater ]:	 <= Closing walk for /root/teste with read_from_db 0
10-19 14:41:06:863 [ info sync.csync.csync ]:	Update detection for local replica took 0 seconds walking 0 files
10-19 14:41:06:863 [ info sync.csync.utils ]:	Memory: 441356K total size, 20636K resident, 18496K shared
10-19 14:41:06:864 [ info sync.csync.csync ]:	## Starting remote discovery ##
10-19 14:41:06:864 [ info sync.accessmanager ]:	6 "PROPFIND" "https://myserver.com.br/remote.php/dav/files/myuser/" has X-Request-ID "885f9644-cd6d-4596-831c-2ffb8cb2c72a"
10-19 14:41:06:864 [ info sync.networkjob ]:	OCC::LsColJob created for "https://myserver.com.br" + "" "OCC::DiscoverySingleDirectoryJob"
10-19 14:41:06:959 [ warning sync.networkjob ]:	QNetworkReply::NetworkError(ContentNotFoundError) "Server replied \"404 Not Found\" to \"PROPFIND https://myserver.com.br/remote.php/dav/files/myuser/\"" QVariant(int, 404)
10-19 14:41:06:959 [ info sync.networkjob.lscol ]:	LSCOL of QUrl("https://myserver.com.br/remote.php/dav/files/myuser/") FINISHED WITH STATUS "ContentNotFoundError Server replied \"404 Not Found\" to \"PROPFIND https://myserver.com.br/remote.php/dav/files/myuser/\""
10-19 14:41:06:959 [ warning sync.discovery ]:	LSCOL job error "Error transferring https://myserver.com.br/remote.php/dav/files/myuser/ - server replied: Not Found" 404 QNetworkReply::NetworkError(ContentNotFoundError)
10-19 14:41:06:959 [ warning sync.engine ]:	ERROR during  csync_update :  "File or directory not found: "
10-19 14:41:06:959 [ info sync.database ]:	Closing DB "/root/teste/._sync_5b7caeed4c45.db"
10-19 14:41:06:960 [ info sync.engine ]:	CSync run took  97 ms
10-19 14:41:06:960 [ info sync.database ]:	Closing DB "/root/teste/._sync_5b7caeed4c45.db"

**Comment by dragotin** [comment]
You have a server setup problem, the server pretends that it can not find any files there. Check the server logfiles for more hints on the problem.

**Comment by joaquimferraz** [comment]
I get this log bellow, any help?

Oct 22 09:56:03 LNXCLOUDWEB ownCloud[3234]: [4b00deab-e07e-4ff4-9090-407eb8b29059][X.x.x.x][957bc822-a997-1036-9fc6-33cdf6ff7ecd][webdav][PROPFIND][/remote.php/dav/files/testesip/] Exception: HTTP/1.1 404 Principal with name testesip not found: {"Exception":"Sabre\\DAV\\Exception\\NotFound","Message":"Principal with name testesip not found","Code":0,"Trace":"#0 \/var\/www\/owncloud\/apps\/dav\/lib\/Tree.php(64): Sabre\\DAVACL\\AbstractPrincipalCollection->getChild('testesip')\n#1 \/var\/www\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(966): OCA\\DAV\\Tree->getNodeForPath('files\/testesip')\n#2 \/var\/www\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(1665): Sabre\\DAV\\Server->getPropertiesIteratorForPath('files\/testesip', Array, 1)\n#3 \/var\/www\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/CorePlugin.php(355): Sabre\\DAV\\Server->generateMultiStatus(Object(Generator), false)\n#4 [internal function]: Sabre\\DAV\\CorePlugin->httpPropFind(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#5 \/var\/www\/owncloud\/lib\/composer\/sabre\/event\/lib\/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 \/var\/www\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(479): Sabre\\Event\\EventEmitter->emit('method:PROPFIND', Array)\n#7 \/var\/www\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAV\/Server.php(254): Sabre\\DAV\\Server->invokeMethod(Object(Sabre\\HTTP\\Request), Object(Sabre\\HTTP\\Response))\n#8 \/var\/www\/owncloud\/apps\/dav\/lib\/Server.php(298): Sabre\\DAV\\Server->exec()\n#9 \/var\/www\/owncloud\/apps\/dav\/appinfo\/v2\/remote.php(31): OCA\\DAV\\Server->exec()\n#10 \/var\/www\/owncloud\/remote.php(165): require_once('\/var\/www\/ownclo...')\n#11 {main}","File":"\/var\/www\/owncloud\/lib\/composer\/sabre\/dav\/lib\/DAVACL\/AbstractPrincipalCollection.php","Line":118}

**Comment by joaquimferraz** [comment]
Using graphical client way it works, via owncloudcmd not.

I get this log bellow, any help?


Oct 22 09:56:03 LNXCLOUDWEB ownCloud[3234]: [4b00deab-e07e-4ff4-9090-407eb8b29059][X.x.x.x][957bc822-a997-1036-9fc6-33cdf6ff7ecd][webdav][PROPFIND][/remote.php/dav/files/testesip/] Exception: HTTP/1.1 404 Principal with name testesip not found: {"Exception":"Sabre\DAV\Exception\NotFound","Message":"Principal with name testesip not found","Code":0,"Trace":"#0 /var/www/owncloud/apps/dav/lib/Tree.php(64): Sabre\DAVACL\AbstractPrincipalCollection->getChild('testesip')\n#1 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(966): OCA\DAV\Tree->getNodeForPath('files/testesip')\n#2 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(1665): Sabre\DAV\Server->getPropertiesIteratorForPath('files/testesip', Array, 1)\n#3 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/CorePlugin.php(355): Sabre\DAV\Server->generateMultiStatus(Object(Generator), false)\n#4 [internal function]: Sabre\DAV\CorePlugin->httpPropFind(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#5 /var/www/owncloud/lib/composer/sabre/event/lib/EventEmitterTrait.php(105): call_user_func_array(Array, Array)\n#6 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(479): Sabre\Event\EventEmitter->emit('method:PROPFIND', Array)\n#7 /var/www/owncloud/lib/composer/sabre/dav/lib/DAV/Server.php(254): Sabre\DAV\Server->invokeMethod(Object(Sabre\HTTP\Request), Object(Sabre\HTTP\Response))\n#8 /var/www/owncloud/apps/dav/lib/Server.php(298): Sabre\DAV\Server->exec()\n#9 /var/www/owncloud/apps/dav/appinfo/v2/remote.php(31): OCA\DAV\Server->exec()\n#10 /var/www/owncloud/remote.php(165): require_once('/var/www/ownclo...')\n#11 {main}","File":"/var/www/owncloud/lib/composer/sabre/dav/lib/DAVACL/AbstractPrincipalCollection.php","Line":118}

**Comment by ogoffart** [comment]
The problem seems to be that the `https://myserver.com.br/remote.php/dav/files/myuser/` returns a 404.  This is a server issue, as this is supposed to exist!

Maybe try on the old endpoint by setting the env variable `OWNCLOUD_CHUNKING_NG=0`

**Comment by ogoffart** [comment]
I wouldn't explain why the gui works properly. One difference could be the authentication method. (are you using oauth2?)

What is the sync log with the GUI?

**Comment by joaquimferraz** [comment]
Running like this does not work:

export OWNCLOUD_CHUNKING_N=0
owncloudcmd -u myuser -p password --trust /root/teste https://myserver.com.br/remote.php/webdav

or 

export OWNCLOUD_CHUNKING_N="0"
owncloudcmd -u myuser -p password --trust /root/teste https://myserver.com.br/remote.php/webdav

**Comment by ogoffart** [comment]
You are missing a G in the last comment (_NG)

**Comment by joaquimferraz** [comment]
> You are missing a G in the last comment (_NG)

Truth. Sorry for my lack of attention. Thank you!!!

**Comment by ogoffart** [comment]
I think the problem here, is the username used.

`owncloudcmd` does not do a query to the server to know the dav user name. Maybe that's something that need to be fixed.

**Comment by jnweiger** [comment]
@joaquimferraz can you please test if OWNCLOUD_CHUNKING_NG=0 is still needed with 2.5.1rc2
available from https://software.opensuse.org//download.html?project=isv%3AownCloud%3Adesktop%3Atesting&package=owncloud-client

**Comment by joaquimferraz** [comment]
@jnweiger, I tested it and it worked. Thank you.

**Comment by guruz** [comment]
Great!
