### ISSUE TITLE
[macOS] [Mojave] No boxes surrounding the settings sections anymore

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/client#6831]
The former client (<= 2.5.0) had gray boxes around the different sections. This increased the user experience. It seems as if there is a regression here.
___
### Expected behaviour
<img width="868" alt="screenshot 2018-10-22 at 16 25 36" src="https://user-images.githubusercontent.com/33026403/47298313-be4b5500-d617-11e8-8ad9-2c50f2a81cea.png">

### Actual behaviour
<img width="912" alt="screenshot 2018-10-22 at 16 19 33" src="https://user-images.githubusercontent.com/33026403/47298419-08ccd180-d618-11e8-8003-bf12eff0602b.png">

<img width="912" alt="screenshot 2018-10-22 at 16 18 57" src="https://user-images.githubusercontent.com/33026403/47298428-0f5b4900-d618-11e8-9ed0-7b2ccc5ac7e3.png">

### Steps to reproduce
1. Install 2.5.1 daily build
2. Go to General or Network tab

### Client configuration
Client version:
2.5.x
Operating system:
macOS Mojave
OS language:
English
Qt version used by client package (Linux only, see also Settings dialog):
Qt 5.10.1 - ownCloud-2.5.1.10736-daily20181022

@guruz @ogoffart

**Comment by ogoffart** [comment]
The box are still there, for me.
I think that's the style on macOS Mojave

**Comment by ogoffart** [comment]
But maybe the boxes are gone because that's how mojave's style is.
I mean, maybe the box disappeared from every application.

**Comment by ChrisEdS** [comment]
Same system different style: 
![image](https://user-images.githubusercontent.com/33026403/49222926-98b32780-f3dd-11e8-978b-a127c8b2db71.png)

**Comment by michaelstingl** [comment]
Boxes come back with Qt 5.12.1:

![cursor_and_macos_10_14_and_macos_10_13](https://user-images.githubusercontent.com/214010/51405486-bb003080-1b56-11e9-95ba-d9b111f756b0.png)

Thanks @dschmidt for building it!

**Comment by guruz** [comment]
Boxes are back according to comment above and according to https://github.com/owncloud/enterprise/issues/3138#issuecomment-465055091

See discussion regarding dark mode in https://github.com/owncloud/client/issues/7043#issuecomment-465448121
