### ISSUE TITLE
[Wizard] sslcert mixture

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6832]
=== client 2.5.1 daliy 20181023 running on Ubuntu 18.10

The client seems to remember the certificate from a failed connect, and uses it at the next connect, even if that is a different server.

Reproduce: 
start, connect to demo.owncloud.com with username invalid and password invalid.
The login fails as expected.
Use the back button, change the server name to demo.owncloud.org and press connect.
The Warning dialog seen on the right side appears. The connection cannot be properly authenticated.

![image](https://user-images.githubusercontent.com/1108546/47388802-6e51b880-d713-11e8-8fde-84908038d1aa.png)

**Comment by ogoffart** [comment]
I can reproduce the problem

**Comment by ogoffart** [comment]
the important part is that both demo.owncloud.org and demo.owncloud.com have the same IP, and the client is somehow configured to re-use the TLS session.

This simple test case reproduces the problem:

```C++

#include <QtNetwork/QtNetwork>

int main(int argc, char **argv)
{
    QCoreApplication app(argc, argv);

    QNetworkAccessManager manager;
    QEventLoop loop;

    // Code from Account::getOrCreateSslConfig
    QSslConfiguration sslConfig = QSslConfiguration::defaultConfiguration();
    // Try hard to re-use session for different requests
    //sslConfig.setSslOption(QSsl::SslOptionDisableSessionTickets, false);
    //sslConfig.setSslOption(QSsl::SslOptionDisableSessionSharing, false);
    sslConfig.setSslOption(QSsl::SslOptionDisableSessionPersistence, false);

    {
        QNetworkRequest request = QNetworkRequest(QUrl("https://demo.owncloud.com"));
        request.setSslConfiguration(sslConfig);
        QNetworkReply* reply = manager.get(request);
        QObject::connect(reply, &QNetworkReply::finished, [&] {
            qDebug() << ".com: " << reply->error();
            // What CheckServerJob::metaDataChangedSlot  does
            sslConfig = reply->sslConfiguration();
            loop.quit();
        });
        loop.exec();
    }

    {
        QNetworkRequest request = QNetworkRequest(QUrl("https://demo.owncloud.org"));
        request.setSslConfiguration(sslConfig);
        QNetworkReply* reply = manager.get(request);
        QObject::connect(reply, &QNetworkReply::finished, [&] {
            qDebug() << ".org: " << reply->error();
            loop.quit();
        });
        loop.exec();
    }
}

```

The thing is that the wizard re-uses the same account in the wizard, so it keeps the configuration from the previous call, 

Maybe we should always create a new account in OwncloudSetupWizard::slotCheckServer

**Comment by ogoffart** [comment]
I wonder if the same problem would not happen if https://demo.owncloud.com was redirecting to https://demo.owncloud.org , in which case, the fix would not help.

**Comment by guruz** [comment]
> I wonder if the same problem would not happen if https://demo.owncloud.com was redirecting to https://demo.owncloud.org , in which case, the fix would not help.

Maybe not because the redirect handling in the wizard is earlier (just guessing)? Before we stuff any SSL server cert info into the Account?

**Comment by ogoffart** [comment]
> Maybe not because the redirect handling in the wizard is earlier (just guessing)? Before we stuff any SSL server cert info into the Account?

Yes, but we support redirecting from any requests now. So any GET could redirect.

**Comment by jnweiger** [comment]
### tested  - client 2.5.1 daily 20181023 running on mint tara 19 aka ubuntu 18.04

 rm ~/.config/*/testpilotcloud.cfg

first demo.owncloud.com then demo.owncloud.org -> OK
first demo.owncloud.orm then demo.owncloud.com -> OK
PASS

(cannot test the redirect scenario here. But that is not part of this issue.)
