### ISSUE TITLE
[Linux] Extreme load in linux client when temporarily offline

### ISSUE THREAD

**Issue by thommierother** [owncloud/client#6838]
Both standard owncloud client and testpilot show extreme loads until a network connection is established (e.g. on startup until WLAN client connection is up):

### Expected behaviour
No significant load differences

### Steps to reproduce
1. install owncloud client 2.5.0 on opensuse leap 15 (same for testpilot)
2. start computer and login, owncloud is started first, wlan connection is established later
3. owncloud client shows 100 % load until network is up

### Server configuration
not applicable

ownCloud version:
ownCloud version 2.5.0 (build 10213)
Git revision c739318335fab93ae049d93cb13787488af8f285
Using Qt 5.10.1, built against Qt 5.10.1
Using 'OpenSSL 1.1.0i-fips  14 Aug 2018'

Client package (From ownCloud or distro) (Linux only):
distro

See screenshot

**Comment by thommierother** [comment]
![screenshot_20181024_202124](https://user-images.githubusercontent.com/6594120/47453760-da90f280-d7cd-11e8-9d17-b5539e70b088.png)

**Comment by ogoffart** [comment]
could you maybe run `perf top`  to give an idea of what might cause this high load.

**Comment by thommierother** [comment]
[ocperf.txt](https://github.com/owncloud/client/files/2514068/ocperf.txt)
perf top >> ocperf.txt

**Comment by ogoffart** [comment]
Looks like some qtnetwork call. Since it is the distro package, it must have the Qt's bearer management plugin install, which must be causing this.

Can you try to remove the bearer plugins which are in `/usr/lib/qt/plugins/bearer`  (location may vary from distro to distro)  and see if the cpu is still high when these plugins are removed. (or move them to a temporary location, for the test)

Bearer plugins are known to cause performence issues ( https://bugreports.qt.io/browse/QTBUG-40332 ) and we disable them in our own build.

**Comment by thommierother** [comment]
hm, I believe it is libqconnmanbearer.so, but its hard to remove it without breaking the whole KDE installation ... So we'll have to wait for a QT fix I assume ...

**Comment by guruz** [comment]
@thommierother You can move the file temporarily to libqconnmanbearer.so.moved and restart the client and see. Just to prove or falsify @ogoffart 's theory.

Which distro are you on?[ We also have specific packages with our own Qt](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client).

**Comment by guruz** [comment]
> without breaking the whole KDE installation

The Qt plugins are usually optional so you won't break anything badly.

**Comment by thommierother** [comment]
@guruz  OK, I tried sequentially with all three libqconnmanbearer.so,  libqgenericbearer.so and libqnmbearer.so plugins. I renamed one, restarted oc client, then renamed it again to *.so and tried with the second and then the third. I always have high load in top (up to 200 % CPU) until the connection reappears. distro is opensuse leap 15

**Comment by guruz** [comment]
@thommierother But have you tried disabling all 3 at the same time so that there are none?

Which exact package are you using?

**Comment by ogoffart** [comment]
Is there anything in the log? while the CPU is so high?

**Comment by guruz** [comment]
thanks.
Also interesting would be to start the client with
```
owncloud --logfile - --logdebug
```
Is there anything interesting popping up there? Does it flood the terminal with log messages or not? Can you paste? If the 100% CPU whatever-loop is inside Qt itself then maybe we don't see a log flood.


> Since it is the distro package, it must have the Qt's bearer management plugin install, which must be causing this.

So it's not the distro package if it has all the ocqt5101-* stuff and is from isv:ownCloud:desktop (openSUSE_Leap_15.0)


@dragotin Can you point @thommierother to the upstream suse packages? This might get @thommierother 's setup working again, but we should still first debug this issue here.

**Comment by thommierother** [comment]
[oclog.txt](https://github.com/owncloud/client/files/2518655/oclog.txt)

**Comment by thommierother** [comment]
does not look like something from "inside" the client .. ?

**Comment by guruz** [comment]
```
10-26 11:40:28:728 [ info sync.clientproxy ]:	Set proxy configuration to use system configuration
...
10-26 11:40:28:751 [ info sync.connectionvalidator ]:	Setting QNAM proxy to be system proxy "3://192.168.72.1:3128"
```

Is 192.168.72.1:3128 really your network proxy? 3:// means http://? What if you set the proxy setting to "None" in the client settings?

@ogoffart Maybe Qt (bearer integration) has a problem with proxy but not without.

**Comment by thommierother** [comment]
192.168.72.1:3128 is the local network proxy but its not mandatory. I tested with both active and inactive "global" proxy settings in yast. In both cases the client connects to the remote owncloud server. The only trigger that forces the "high load" is the missing (WLAN) network connection. I don't believe it has something to do with the proxy settings...

**Comment by guruz** [comment]
To me it is weird that even removing the bearer plugins trigger the situation.
Do you see any bearer plugin loading when trying
```
QT_DEBUG_PLUGINS=1 owncloud --logfile - --logdebug
```

**Comment by thommierother** [comment]
... hm, no:

...
10-26 18:14:36:641 [ debug gui.activity ]	[ OCC::ActivitySettings::setNotificationRefreshInterval ]:	Starting Notification refresh timer with  300  sec interval
10-26 18:14:36:660 [ debug gui.updater ]	[ OCC::Updater::getSystemInfo ]:	Sys Info size:  348
10-26 18:14:36:701 [ debug default ]	[ unknown ]:	QFactoryLoader::QFactoryLoader() checking directory path "/opt/ownCloud/qt-5.10.1/lib64/qt5/plugins/accessible" ...
10-26 18:14:36:701 [ debug default ]	[ unknown ]:	QFactoryLoader::QFactoryLoader() checking directory path "/opt/ownCloud/ownCloud/bin/accessible" ...
10-26 18:14:36:702 [ debug default ]	[ unknown ]:	loaded library "/opt/ownCloud/qt-5.10.1/lib64/qt5/plugins/iconengines/libqsvgicon.so"
10-26 18:14:36:717 [ info gui.application ]:	Tray menu workarounds: noabouttoshow: true fakedoubleclick: false showhide: false manualvisibility: true
10-26 18:14:36:718 [ info gui.folder.manager ]:	Setup folders from settings file
10-26 18:14:36:718 [ debug gui.folder ]	[ OCC::Folder::checkLocalPath ]:	Checked local path ok
10-26 18:14:36:718 [ info sync.configfile ]:	Adding system ignore list to csync: "/etc/ownCloud/sync-exclude.lst"
10-26 18:14:36:718 [ info sync.configfile ]:	Adding user defined ignore list to csync: "/home/thommie/.config/ownCloud/sync-exclude.lst"
10-26 18:14:36:720 [ info gui.folder.manager ]:	Adding folder to Folder Map  OCC::Folder(0x55eb0e1c18c0) "1"
10-26 18:14:36:720 [ debug gui.folderwatcher ]	[ OCC::FolderWatcherPrivate::slotAddFolderRecursive ]:	(+) Watcher: "/home/thommie/ownCloud/"
10-26 18:14:36:741 [ debug gui.folderwatcher ]	[ OCC::FolderWatcherPrivate::slotAddFolderRecursive ]:	    `-> and 999 subdirectories
10-26 18:14:36:742 [ info gui.folder.manager ]:	Schedule folder  "1"  to sync!
10-26 18:14:36:742 [ info gui.folder.manager ]:	Folder is not ready to sync, not scheduled!
10-26 18:14:36:742 [ info gui.application ]:	Sync state changed for folder  "https://www.netzwissen.de/owncloud/remote.php/webdav/" :  "Not yet Started"

**Comment by guruz** [comment]
@thommierother Nothing with "loaded library" related to bearer even BEFORE that log you pasted?

CC @ogoffart @ckamm for help.

**Comment by ckamm** [comment]
I've looked at it too but don't have further ideas. The `perf top` output does indeed make it look like something's going on inside Qt. Nothing happening in the log confirms that.

@thommierother Do you think you could attach a debugger, interrupt when cpu usage is high like this and get backtraces for all threads? (I'm not sure whether what we see would be helpful or not)

**Comment by thommierother** [comment]
@ckamm: shure, if you show me how or provide some links with infos ;-). I'm an not a KDE/C++ developer, so I would need some infos. And the laptop is productive, I don't want to deform it somehow...

**Comment by ckamm** [comment]
@thommierother Ok, great!
- Switch off wifi, quit owncloud client
- Start owncloud client with `gdb owncloud`, then `run`
- In that shell, when you get the cpu spike, hit ctrl-c to interrupt the program
- `thread apply all bt` and copy the output
- if the condition lasts for a bunch of seconds you can also `continue` and then interrupt the program again a few seconds later to capture another trace

Maybe the stacktraces will be confusing due to a lack of debug symbols, we'll see.

**Comment by thommierother** [comment]
@ckamm: unfortunately (or better: luckily) there was an update for some libraries on 28.10:

2018-10-28 10:58:32|install|ocqt5101-libQt5Core5|5.10.1-lp150.27.1|x86_64||openSUSE_Leap_15.0_3|b1c5043ac14a459c5f0814772e6234cc6b3a14176aed927bec34b9f1d3713a9f|
2018-10-28 10:58:32|install|ocqt5101-libQt5Xml5|5.10.1-lp150.27.1|x86_64||openSUSE_Leap_15.0_3|2087af08786d15eed5ac571c7b15727e38bcb280efa4c5bb6bd910b319cb881e|
2018-10-28 10:58:32|install|ocqt5101-libQt5Sql5|5.10.1-lp150.27.1|x86_64||openSUSE_Leap_15.0_3|6a99e3d834af9544d300b16022294a144661eb97b92ecdbaf19adaf6fe2f8eea|
2018-10-28 10:58:33|install|ocqt5101-libQt5DBus5|5.10.1-lp150.27.1|x86_64||openSUSE_Leap_15.0_3|cd1886e803fcf35c37e565733ac4ffa42e82a073636c73fa014d47f351d7be47|
2018-10-28 10:58:33|install|ocqt5101-libQt5Sql5-sqlite|5.10.1-lp150.27.1|x86_64||openSUSE_Leap_15.0_3|035f971881b98553ac98735b651bcd8beee23a29c10a1850b357bdd4fc645158|
2018-10-28 10:58:33|install|ocqt5101-libQt5Network5|5.10.1-lp150.27.1|x86_64||openSUSE_Leap_15.0_3|3d9665782cff0c0c29c406487d8c6f17f943e63e9371815b399763f793b7e22b|
2018-10-28 10:58:33|install|ocqt5101-libQt5Gui5|5.10.1-lp150.27.1|x86_64||openSUSE_Leap_15.0_3|775caf0e06b51290c1dd9c23e7295ba13756521eeff9ea9fcb886a49ec287141|
2018-10-28 10:58:34|install|ocqt5101-libQt5Widgets5|5.10.1-lp150.27.1|x86_64||openSUSE_Leap_15.0_3|dbeeca4c8fabc8883eb51f1b0e3c378ac8ae3d33d4e6a487479b0e611cba1830|
2018-10-28 10:58:34|install|ocqt5101-libQt5PrintSupport5|5.10.1-lp150.27.1|x86_64||openSUSE_Leap_15.0_3|7cb800e82e01f3d7be3632cf2509b2c748feccc270bd68a14793afd6310596de|
2018-10-28 10:58:35|install|ocqt5101-libqt5-qtwebkit|5.10.1-lp150.11.33|x86_64||openSUSE_Leap_15.0_3|cbb86c5524c58c85e1e64ff4280e81a4261458930f004a67dd9cacae9da996f5|

Since then, I can not reproduce the effect of high load when the client starts with no network in the background... Some, somehow, the issue disappeared, I will close it now.

**Comment by guruz** [comment]
(The Qt update was unrelated to network issues, but possibly it somehow made the client to use the correct Qt plugins again?)

@ogoffart @ckamm @jnweiger This could be prevented by having the namespace infix in Qt? (but not for plugins?)
