### ISSUE TITLE
[macOS] [2.5.x] Progress bar glitchy

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#6839]
### `ownCloud-qt5.6.2-2.4.3.10347.pkg`
(Qt 5.6.2 on macOS High Sierra 10.13.6)

![243-1013](https://user-images.githubusercontent.com/214010/47458737-9fe18700-d7da-11e8-9e3e-18db2b82d626.gif)

==> looks good 👍 

### `ownCloud-2.5.1.10748-daily20181024.pkg`
(Qt 5.10.1 on macOS High Sierra 10.13.6)

![251-1013](https://user-images.githubusercontent.com/214010/47458763-b12a9380-d7da-11e8-8f1d-6f9c7f9af0ba.gif)

==> progress bar disappearing 👎 

### `ownCloud-2.5.1.10748-daily20181024.pkg`
(Qt 5.10.1 on macOS Mojave 10.14)

![251-1014](https://user-images.githubusercontent.com/214010/47458799-c56e9080-d7da-11e8-9a8f-ada630cb35f2.gif)

==> progress bar misplaced 👎

**Comment by guruz** [comment]
@michaelstingl Sure you don't consider this a showstopper for 2.5.1?

**Comment by ogoffart** [comment]
This looks like a Qt bug in the QMacStyle.

**Comment by ogoffart** [comment]
(The QMacStyle was changed a lot in Qt 5.10, so that might explain it)

**Comment by michaelstingl** [comment]
No change in first Qt 5.12.1 build

**Comment by guruz** [comment]
> No change in first Qt 5.12.1 build

Wasn't that a 5.12.0 build?

**Comment by michaelstingl** [comment]
> Wasn't that a 5.12.0 build?

No, check https://github.com/owncloud/client/issues/6831#issuecomment-455641801

**Comment by guruz** [comment]
@michaelstingl @dschmidt so that was a rc or git build?
5.12.1 was only released yesterday
https://blog.qt.io/blog/2019/02/01/qt-5-12-1-released/
Would need to check if the final fixes it?

**Comment by michaelstingl** [comment]
> Would need to check if the final fixes it?

yes, sure. @dschmidt please ping as soon we build with the final.

**Comment by guruz** [comment]
Still the case with the latest dailies? (Qt 5.12.1 based)

**Comment by michaelstingl** [comment]
@lazawan could you perform a quick check?

**Comment by lazawan** [comment]
@michaelstingl sure !

**Comment by lazawan** [comment]
@michaelstingl @guruz 
firstly I used the client 2.5.4 with Qt 5.12.1 and that is the build ,that I tested
https://download.owncloud.com/desktop/daily/ownCloud-2.5.4.11337-daily20190219.pkg

I tested 2 cases : 
first case : owncloud-client at the first run-time " I didn't configure any account yet " 

![screenrecording20190212at1](https://user-images.githubusercontent.com/44814084/53080853-e087ad80-34f9-11e9-8ca0-0928a56192cd.gif)

second case : I have already an account and I remove it and add a new one " at this point there is a problem " 

![screenrecording20190212at1 copy](https://user-images.githubusercontent.com/44814084/53080911-07de7a80-34fa-11e9-99e7-076f25c85e23.gif)

**Comment by TheOneRing** [comment]
Might be related to https://bugreports.qt.io/browse/QTBUG-67830

**Comment by wazoox** [comment]
> Might be related to https://bugreports.qt.io/browse/QTBUG-67830

Definitely related...

**Comment by TheOneRing** [comment]
Fixed in 2.7
