### ISSUE TITLE
HTTP/2 protocol error since ownCloud client update

### ISSUE THREAD

**Issue by rmk-ch** [owncloud/client#6843]
Hi,

This is a follow-up to: https://central.owncloud.org/t/http-2-protocol-error-since-owncloud-client-update/15986
A similar bug was fixed with https://github.com/owncloud/client/pull/6353 but it seemed to re-appear in 2.5.0
Problem happens with multiple Windows 10 64 bit clients on the same owncloud server.

Thanks for fixing!

### Expected behaviour
After installing ownCloud I should be able to add my server and connect to it.

### Actual behaviour
The connection fails saying “HTTP/2 protocol error”. Client is not usable!

### Steps to reproduce
Install ownCloud client 2.5.0 (build 10560) on Windows (Win10 64-bit) or perform automatic upgrade from previous version.
Add a new server configuration
When finishing by pushing the “Connect…” button it fails saying “Error: HTTP/2 protocol error”
Downgrading to an older client version (e.g. 2.4.3.10188) is a workaround for the problem.

### Server configuration
owncloud version: 10.0.10.4 (updated since bug report opened)
Operating system: FreeBSD
Web server: Apache (I believe)
Database: 10.1-MariaDB
PHP version: 7.2.11
Storage backend (external storage): only local folder

### Client configuration
Client version: 2.5.0.10560
Operating system: Windows 10, 64-bit
OS language: English
Installation path of client: C:\Program Files (x86)\ownCloud

### Logs
1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
https://gist.githubusercontent.com/fabbra/e5e5b1a8a2b5ea1892f07ce016657a5b/raw/96cb5d37da467e48677b98ac8031a5cdf07bafcd/gistfile1.txt 4

2. Web server error log:
[code]XY - - [24/Oct/2018:11:27:56 +0200] "PROPFIND /remote.php/webdav/ HTTP/2.0" 207 342 "-" "Mozilla/5.0 (Windows) mirall/2.5.0 (build 10560)" XY - - [24/Oct/2018:11:27:59 +0200] "PROPFIND /remote.php/webdav/ HTTP/2.0" 207 304 "-" "Mozilla/5.0 (Windows) mirall/2.5.0 (build 10560)"[/code]

3. Server logfile: ownCloud log (data/owncloud.log):
https://gist.github.com/rmk-ch/e62e8e2639f552d6fbb1de8cce7239be

**Comment by guruz** [comment]
@rmk-ch What is interesting about your log is that several requests work fine and only then it claims a protocol error.
```
10-02 10:15:00:952 [ info sync.accessmanager ]:	1 "" "https://owncloud.mydomain.com/remote.php/webdav//" has X-Request-ID "0cb1b649-4a52-41ab-b39d-15f698900e3c"
10-02 10:15:00:953 [ info sync.networkjob ]:	OCC::EntityExistsJob created for "https://owncloud.mydomain.com" + "remote.php/webdav//" "OCC::OwncloudSetupWizard"
10-02 10:15:01:124 [ warning sync.networkjob ]:	QNetworkReply::NetworkError(ProtocolFailure) "HTTP/2 protocol error" QVariant(Invalid)
10-02 10:15:01:123 [ warning qt.network.http2 ]:	stream 1 finished with error: "HTTP/2 protocol error"
```

What would be important is to get information from the web server **error** log. What you pasted is from the **access** log. Those are different files.

> Web server: Apache (I believe)

Is this a current enough version? Just wondering..

**Comment by rmk-ch** [comment]
Hi @guruz and @ogoffart 

Thanks for responding.
Hmm... I was looking for the error log in my hosters control panel, but unfortunately I could only find the access log. If it would help, I can ask the hoster for error log. 

I found the server version with PHP variable $_SERVER['SERVER_SOFTWARE'] that returns Apache/2.4. If you need more detail, I need to further investigate. However, since this owncloud installation is hosted on a public professional webspace I would assume the version to be quite up-to-date.

@ogoffart I have sent you an email with URL and credentials for debugging to the email adress listed in your github profile.

**Comment by ogoffart** [comment]
@rmk-ch thanks, i got the credentials, and I could reproduce the problem, so i'll try to debug it

**Comment by ogoffart** [comment]
It looks like your server is misconfigured and has trouble with the "HEAD" http call via HTTP/2

It can be shown with curl

```
$ curl --head --http2  https://<your_server>/
curl: (92) HTTP/2 stream 0 was not closed cleanly: PROTOCOL_ERROR (err 1)
```

Using `--http1.1` works.

The client uses the HEAD command to know if a file exist before configuring the account, and this is failling on your server.

**Comment by guruz** [comment]
Great, thanks for debugging @ogoffart 

I'll close to issue here..

@rmk-ch Please comment if you find out what was the issue, maybe others can help.
I guess you need to ask your FreeBSD admin

**Comment by rmk-ch** [comment]
Hi @ogoffart 
Thank you very much for debugging. I contacted the server administrator and let you know if he provides more information.

**Comment by th3boz** [comment]
Hi everyone,
I have the same problem:

“Install ownCloud client 2.5.0 (build 10560) on Windows (Win10 64-bit) or perform automatic upgrade from previous version.
Add a new server configuration
When finishing by pushing the “Connect…” button it fails saying “Error: HTTP/2 protocol error”
Downgrading to an older client version (e.g. 2.4.3.10188) is a workaround for the problem.”

I tried to do 

$ curl --head --http2  https://<my_server/

and the result is:

HTTP/2 200 
date: Wed, 16 Jan 2019 23:13:38 GMT 
server: Apache 
last-modified: Thu, 03 Mar 2016 22:26:29 GMT 
etag: "84-52d2c7d62ef40" 
accept-ranges: bytes 
content-length: 132 
content-type: text/html

So.. my server seems to be configured correctly and works with the version 2.4.x of the client, but not with the version 2.5.x

Could you please help me?
Thanks very much!!
Andrea

**Comment by th3boz** [comment]
Addendum

If the http/2 request is done with ALPN enabled, the curl result is the one reported in the previous post, while if it’is done with APLN disabled it does not work.

Application-Layer Protocol Negotiation requires a valid SSL certificate and TLSv1.2 or newer.. and the result reported in the previous post says that I have a correct SSL certificate.

Could this information be useful? Does the 2.5.x client version of ownCloud support HTTP/2 using APLN only? (all major browsers support HTTP/2 using ALPN only).

Thank you very much!
Andrea

**Comment by guruz** [comment]
Has anyone seen issues with HTTP2 in 2.6.0 similar as in https://github.com/owncloud/client/issues/7610 ? Please comment there...
