### ISSUE TITLE
Settings > Activity > Not Synced: View hangs dramatically and renders ownCloud Client useless

### ISSUE THREAD

**Issue by eskimodev** [owncloud/client#6847]
### Expected behaviour
You should be able to open the view/tab of "Not Synced" items and edit conflicts one by one.

### Actual behaviour
Instead, black rectangles flash on the screen and the ownCloud client slows down and hangs.

### Steps to reproduce
Open Settings > Activity > Not Synced

### Server configuration
unknown (managed hosting)

### Client configuration
Client version: 2.5.0 (Build 10560)

Operating system: Windows 10 Pro 64-bit (current version)

OS language: English

**Comment by ckamm** [comment]
@eskimodev Do you have more information, ideally a log file? (https://doc.owncloud.org/desktop/2.5/troubleshooting.html#logging-to-a-temporary-directory)

How many files and conflicts were there approximately? Does this happen immediately after you restart the client too? How can I attempt to reproduce the problem?

**Comment by ckamm** [comment]
The "not synced" tab should already have a 50k items limit to prevent problems. The main thing that happens when the widget is shown is `_ui->_treeWidget->sortByColumn(0, Qt::DescendingOrder);` (even though this should also be the default sort column). How many entries did the header show would be in this tab?

**Comment by guruz** [comment]
@eskimodev How long is this hang, e.g. does it eventually catch up and display something?
Also keep task manager open to check the owncloud client CPU load.

**Comment by eskimodev** [comment]
It is hard for me to reproduce this problem, because I fixed the conflicts already and reinstalled ownCloud multiple times. I had approximately 40 conflicts. I checked the CPU load, while the freeze occurred - nothing out of the ordinary. Thanks for the fast replies though.

**Comment by eskimodev** [comment]
The hang (flashing black rectangles) occurred just after I switched to the "Settings > Activity > Not Synced" tab and did not affect the performance of my PC that much, I could only notice how the client turned unusable. After I closed and reopened the client, it worked normally again.

**Comment by ckamm** [comment]
I'll try what happens with a couple hundred conflicts.

**Comment by ckamm** [comment]
Feel free to reopen if there's more data or a way to reproduce.
