### ISSUE TITLE
"ownCloud2" picked for new folder connection in FOLDER wizard when SKIPPING folder configuration in ACCOUNT wizard (so I didn't even configure "ownCloud")

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6853]
@ogoffart @ckamm i don't have time to investigate right now, do you?

I guess it is related to:

```
        emit createLocalAndRemoteFolders(localFolder(), _remoteFolder);
...
src/gui/accountsettings.cpp:            if (!dir.mkpath(".")) {
src/gui/owncloudsetupwizard.cpp:        if (fi.mkpath(localFolder)) {
```

**Comment by guruz** [comment]
(This is in a totally fresh VM where there was never any ~/ownCloud)

**Comment by ogoffart** [comment]
Looks like the wizard creates the empty ~/ownCloud folder even when we skip the folder configuration.  I guess that's a regression

**Comment by jnweiger** [comment]
### tested on a vanilla Fedora 28 VM
dnf config-manager --add-repo http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/testing/Fedora_28/isv:ownCloud:desktop:testing.repo
 dnf install owncloud-client
 rm -rf ~/.config/ownCloud
 rm -rf ~/ownCloud*
 owncloud
 -> (*) Manually create folder sync connections
 [Add Folder Sync Connection]
 no ~/ownCloud exists up to now. -> OK
 ~/ownCloud gets suggested -> OK
  -> PASS
