### ISSUE TITLE
Owncloud-Client on Raspbian X/Qt issues, maybe induced by X2go

### ISSUE THREAD

**Issue by damarx180** [owncloud/client#6857]
### Expected behaviour
OwnCloud Desktop Client (from Raspbian-Repo) should open.

### Actual behaviour
When starting by command  "owncloud" , I receive an error message: 

** (owncloud:1812): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Gdk-Message: owncloud: Fatal IO error 2 (No such file or directory) on X server :51.0.

### Steps to reproduce
1. Just issue command "owncloud"

### Server configuration
<not necessary, working fine on other OSes / has nothing to do with my issue>

### Client configuration
Client version:  7.0.13~dfsg-1

Operating system: Raspbian Stretch with desktop  (4.14.71-v7+ Kernel)

OS language: en

Qt version used by client package (Linux only, see also Settings dialog): 
Qt5: 5.7.1+dfsg-3+rpi1
Qt4: 4:4.8.7+dfsg-11+rpi1

_Qt4 might be the issue since i'm trying to run the application from inside a X2GO session, which uses Qt4. But i was able to install and setup Owncloud via X2GO aswell?!
 The X server error might be issued due to this._

Client package (From ownCloud or distro) (Linux only): Raspbian default Repo
pool/main/o/owncloud/owncloud_7.0.13~dfsg-1_all.deb

Installation path of client:
Executable is in /usr/bin

### Logs

** (owncloud:1812): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Gdk-Message: owncloud: Fatal IO error 2 (No such file or directory) on X server :51.0.

**Comment by ogoffart** [comment]
What's the version of the client? (7 is not a valid version, the last one is 2.5)
I guess the problem is that it cannot show a system tray icon.  You can try to run the client twice, that should open the settings if it is already running.

Run with `--logfile -`  to have more logs

**Comment by damarx180** [comment]
ah, sry, looked at the wrong package information.

owncloud-client:
  Installed: 2.2.4+dfsg-2+b4
  Candidate: 2.2.4+dfsg-2+b4
  Version table:
 *** 2.2.4+dfsg-2+b4 500
        500 http://raspbian.raspberrypi.org/raspbian stretch/main armhf Packages
        100 /var/lib/dpkg/status

[oclog.log](https://github.com/owncloud/client/files/2543186/oclog.log)

**Comment by ogoffart** [comment]
Is the program crashing?  If yes, can you open it with gdb to get a backtrace?

**Comment by damarx180** [comment]
`Starting program: /usr/bin/owncloud 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/arm-linux-gnueabihf/libthread_db.so.1".
[New Thread 0x70202340 (LWP 13796)]
[New Thread 0x6c62e340 (LWP 13801)]
[New Thread 0x6be2e340 (LWP 13802)]
[New Thread 0x6b62e340 (LWP 13803)]
[New Thread 0x6ae2e340 (LWP 13804)]

** (owncloud:13781): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
[New Thread 0x69702340 (LWP 13808)]
[New Thread 0x68dff340 (LWP 13809)]
[New Thread 0x683ff340 (LWP 13814)]
[New Thread 0x67aff340 (LWP 13815)]
Gdk-Message: owncloud: Fatal IO error 2 (No such file or directory) on X server :51.0.

[Thread 0x67aff340 (LWP 13815) exited]
[Thread 0x683ff340 (LWP 13814) exited]
[Thread 0x68dff340 (LWP 13809) exited]
[Thread 0x6ae2e340 (LWP 13804) exited]
[Thread 0x6b62e340 (LWP 13803) exited]
[Thread 0x6be2e340 (LWP 13802) exited]
[Thread 0x6c62e340 (LWP 13801) exited]
[Thread 0x70202340 (LWP 13796) exited]
[Thread 0x706ac150 (LWP 13781) exited]
[Inferior 1 (process 13781) exited with code 01]
`

**Comment by damarx180** [comment]
[New LWP 6679]
Core was generated by `x2goagent -nolisten tcp -extension BIG-REQUESTS -nolisten tcp -dpi 96 -D -auth'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x7676398c in ?? ()
(gdb) bt
#0  0x7676398c in ?? ()
#1  0x76dc4834 in ?? ()
Backtrace stopped: previous frame identical to this frame (corrupt stack?)

I hope this is the required data.
So it seems x2go causes the trouble?

**Comment by guruz** [comment]
@damarx180 So x2goagent is the application crashing, the owncloud client is just reporting an error?
Try updating x2ago or contact the developers there?
