### ISSUE TITLE
files or folders named in Japanese with English locale are not synced

### ISSUE THREAD

**Issue by kobayashi** [owncloud/client#6858]
### Expected behaviour
Sync files or folders named in Japanese with English locale

### Actual behaviour
Any files or folders named in Japanese with English locale are not synced with ownCloud server.
This is similar to issue #6287 
To sync them, need to change the locale to Japanese

### Steps to reproduce
1. Start ownCloud client version 2.5 on windows7 and 10 (locale=English)
2. Create a folder or a file with Japanese
3. Cannot see them in ownCloud server.

### Server configuration
Operating system:
CentOS release 6.10 (Final)

Web server: 
Server version: Apache/2.2.15 (Unix)

Database:
Server version: 5.5.45-log MySQL Community Server (GPL) by Remi

PHP version:
7.0.32

ownCloud version:
10.0.7

Storage backend (external storage):

### Client configuration
Client version:
version 2.5

Operating system:
Windows7 and Windows10

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
NA

Client package (From ownCloud or distro) (Linux only):
NA

**Comment by dschmidt** [comment]
Can you try the 2.5.1 nightlies? There was a fix for filenames on Windows since the 2.5.0 release

**Comment by guruz** [comment]
@kobayashi e.g. https://download.owncloud.com/desktop/daily/ownCloud-2.5.1.10964.10842-daily20181104.msi
Please report back if it works..

**Comment by kobayashi** [comment]
That works for me!
Thanks @dschmidt @guruz

**Comment by kobayashi** [comment]
That works for me.

Thanks @dschmidt @guruz
