### ISSUE TITLE
nautilus integration: 'open with owncloud' produces error messages

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6865]
### tested with Linux mint tara
Connect client 2.5.1rc2 to demo.owncloud.org, wait until sync finishes.

`echo huhu > Documents/abc`
`echo huhu > Documents/foo.txt`

open nautilus with shell extensions enabled.

double click on the file `abc` the following error message is printed on stderr of nautilus:
```
Unrecognized option '/home/testy/ownCloud/Documents/abc'
Try 'owncloud --help' for more information
```
right click on file `foo.txt` -> suggests `open with owncloud` as default action.
same as double click, same error message.

With other mime types, jpg, pdf, odt, the respective applications are to open the file are offered as default actions. 

The owncloud client is the wrong default application for *.txt files or files without suffix.

**Comment by ogoffart** [comment]
These files should not be associated to the owncloud client.
Did you perhaps configure that yourself?  Or how did this association came?
Perhaps the config was set wrongly during a trial of an early alpha of the virtual file system?

**Comment by jnweiger** [comment]
You are right that was on a test machine without a proper reset.
On a fresh Ubuntu 18.10 *.txt files remain associated with 'text editor' even with our nautilus shell extension registered.
Sorry for the noise. Invalid.
