### ISSUE TITLE
unsupported client verison

### ISSUE THREAD

**Issue by AqwelF** [owncloud/client#6869]
Hello,

I have a problem connecting owncloud-client to my owncloud server.
This is the message i have on the app

` error transferring https://myservername/owncloud/remote.php/webdav/ - server repplied : Forbidden (unsupported client verison).`

This appeared when i make an update of my owncloud server to the last version.

Owncloud client version : 2.2.4+dfsg-2
OS : Debian stretch
Desktop : Gnome

I took owncloud-client from the debian repository

Owncloud server version : 10.0.10

Thanks for helping

**Comment by michaelstingl** [comment]
Please always check the release notes before you update your ownCloud server: 
https://doc.owncloud.org/server/latest/admin_manual/release_notes.html#new-default-minimum-supported-desktop-client-version

Current stable version of the ownCloud desktop sync client is 2.5.0.

**Comment by AqwelF** [comment]
Ok but i'm forced to do the update or i can't acces mycloud....
So what can i do ?

**Comment by guruz** [comment]
Great to hear :)
