### ISSUE TITLE
macOS: (Mojave 10.14.1) Owncloud does not appear in rightclick Finder menu  

### ISSUE THREAD

**Issue by evgu** [owncloud/client#6871]
In Finder the owncloud right-click menu (e.g. to share files) no longer appears when you rightclick in on files in FInder (within the Owncloud folder). Susuepcting this is due to increase file level locking security in latest Mac OS. 
  
Tried the usual resolves: reinstalling Owncloud client, restating it, restarting OS. 

Suspecting this might be related:
https://tidbits.com/2018/09/10/mojaves-new-security-and-privacy-protections-face-usability-challenges/

https://github.com/owncloud/client/issues/6781

### Expected behaviour
Owncloud menu shows in right-click Finder menus. 

### Actual behaviour
Owncloud menu doe NOT show in right-click Finder menus.
 
### Steps to reproduce
1. Ensure Owncloud 2.5.0 (build 10516) client is running on Mac OS Mojave 10.14.1
2. In Finder go to Owncloud shared folder. 
3. Rightclick on a file you want to share or edit sharing permissions. Owncloud menu does not appear. 

### Server configuration
N/A

### Client configuration
Installation path of client: Standard

**Comment by evgu** [comment]
#6781 might be related.

**Comment by michaelstingl** [comment]
#6781 should be fixed with todays 2.5.1 release:
https://owncloud.org/download/#owncloud-desktop-client-macos

**Comment by evgu** [comment]
2.5.1 release fixes this issue. Thank you.
