### ISSUE TITLE
warning: unknown option after ‘#pragma GCC diagnostic’ kind [-Wpragmas]

### ISSUE THREAD

**Issue by gergap** [owncloud/client#6872]
I get the warning mention in the subject with gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516
and arm-poky-linux-gnueabi-gcc (GCC) 5.3.0

Instead of relying on GCC version specific pragmas I recommend using better portable comments:
/* fall-thru */

This gets recognized by GCC7 as well, and gets ignored by other compilers.
See https://developers.redhat.com/blog/2017/03/10/wimplicit-fallthrough-in-gcc-7/ for a good explanation.

**Comment by ogoffart** [comment]
Fixed with https://github.com/owncloud/client/commit/17a4055e8d658f24b1fc47c44fd2daf66c7d5dbf
