### ISSUE TITLE
Removing a suffix-virtual file does not trigger a remote deletion

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6875]
### tested with testpilotcloud 2.5.1 on Ubuntu 18.04

Enabled virtual files experimental feature on the connection wizard
Connected to demo.owncloud.org
Amongst others, a file 'ownCloud Manual.pdf.owncloud'
is downloaded.
when I remove the file on the client, it is recreated within a few seconds.

Expected behaviour: The remove propagates to the server, the file gets removed and remains removed.

Maybe related: owncloud/client#6718 -- renaming a virtal file works as expected in 2.5.1 but in 2.5.0 it showed a similar behaviour: automatic reset to the previous state.

**Comment by jnweiger** [comment]
@lazawan fyi

**Comment by ogoffart** [comment]
This is currently working as designed. Removing a placeholder does not remove the file of the server, for we are afraid of data loss.

This could be changed if another behaviour is preffered.  @ckamm, @michaelstingl: what do you think?

**Comment by ckamm** [comment]
Yes, intentional for now. Users might not expect that removing "a.owncloud" removes "a" on the server.

**Comment by jnweiger** [comment]
Users might not expect that they have to download a move in order to make delete work.

**Comment by michaelstingl** [comment]
Dropbox and iCloud for example have similar "virtual" concepts, and both have warning when a file gets moved out or gets deletes.

| Dropbox: delete | Dropbox: move | iCloud: move | 
|---|---|---|
| ![dropbox-delete](https://user-images.githubusercontent.com/214010/48509256-deee7f80-e850-11e8-9ce1-40fdfdf777d5.png) | ![dropbox-move](https://user-images.githubusercontent.com/214010/48509257-deee7f80-e850-11e8-8a48-04707d154b89.png) | ![icloud-move](https://user-images.githubusercontent.com/214010/48509261-df871600-e850-11e8-8e61-d5c65663ce26.png) |
| Warning on top of all windows | Warning on top of all windows | Warning sliding in from top in current Finder window |

I'm not sure if I'm a fan of this warning, but after confirmation of such a warning, we could delete the the remote file.

**Comment by guruz** [comment]
@ckamm How is this with wincfapi?

**Comment by ckamm** [comment]
There deletions of local dehydrated files synchronize as remote deletions. In my opinion that makes sense since it's clear it's the same file.

**Comment by ckamm** [comment]
This is blocked on a decision: Should a local placeholder deletion trigger a remote deletion or not?

**Comment by guruz** [comment]
@hodyroff @michaelstingl for discussion ^^
Safest would be to have the warning message like @michaelstingl screenshotted above, but this might be not so easy to implement with current architecture.

Is there a way now to have the file be moved to the server side trashbin? That could be an idea.. maybe this can be done with a MOVE operation?

**Comment by guruz** [comment]
@DeepDiver1975 just said that moving files to server side trashbin is currently not possible via WebDAV.

**Comment by ckamm** [comment]
I suggest we leave it as-is and instead focus efforts on nicer vfs solutions, like wincfapi and equivalents for other platforms.

**Comment by guruz** [comment]
Moving out of milestone and keeping as discussion topic

**Comment by michaelstingl** [comment]
> @hodyroff @michaelstingl for discussion ^^
> Safest would be to have the warning message like @michaelstingl screenshotted above, but this might be not so easy to implement with current architecture.

Client detects deletion, but shouldn't send `DELETE` to the oC server. Instead it should open the warning dialogue. In case, users confirm the deletion, we can send the `DELETE` to the oC server. In the other case where the user cancels the deletion, it should re-download the file to the local sync folder. (similar handling like deletions in read-only folders)

> I suggest we leave it as-is and instead focus efforts on nicer vfs solutions, like wincfapi and equivalents for other platforms.

I think we'll need this popup also for the newer fancy implementations where we don't have the real data in the local trashbin.

**Comment by ckamm** [comment]
A warning dialog has complications:

1) Ideally it pops up immediately when the deletion happens: but that only works if file watchers are reliable and the client is running. To be entirely safe it'd need to pop up during the sync run but that has huge disadvantages: It'd happen much too late and I very much want to avoid user interaction during sync runs (how would that work with owncloudcmd?).

2) Users will ask for a "always delete" checkbox.

So: I imagine a file-watcher triggered dialog with this checkbox. If the user deletes placeholders while the client isn't looking the current no-delete behavior persists.

About other vfs implementations: Do you really think so? If the file is not distinguishable from the real file, why would deleting it not trigger a remote deletion?

**Comment by michaelstingl** [comment]
> About other vfs implementations: Do you really think so? If the file is not distinguishable from the real file, why would deleting it not trigger a remote deletion?

Yeah, it triggers the remote deletion. But also triggers a popup.

**Comment by HanaGemela** [comment]
There is inconsistency between deleting a file and deleting a folder. File is not deleted but folder is. 
There should be some warning that it will delete the folder on the server as well or it should just be recreated as is a file after deletion

**Comment by michaelstingl** [comment]
> There should be some warning that it will delete the folder on the server as well or it should just be recreated as is a file after deletion

👍

**Comment by jnweiger** [comment]
Contrary to the original post, I have also seen the opposite behaviour coming as a surprise: Some users seem to expect, they can remove local placeholders, without any effect on the server. That is a misconception. Requesters like thise in Michael's screenshot should help to educate users about the semantics of virtual files.

**Comment by ckamm** [comment]
I think we have consensus on the warning, I've created https://github.com/owncloud/client/issues/7360 to track the implementation.
