### ISSUE TITLE
Switching between selective sync and virtual files works only one direction

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6876]
### tested with testpilotcloud 2.5.1 on Ubuntu 18.04
connect to demo.owncloud.org
start with [Choose what to sync], 
deselect the Photos folder.

wait until the sync finishes.
The click on the 3 dots of the sync folder to enable virtual files.
The Photos folder gets created, all files in it are virtual files. -> GOOD.

Click on the 3 dots in the sync folder to disable the virtual files feature again.
The Photos folder remains as is. All files have suffix *.testpilotcloud_virtual
The sync folder setting shows the Photos folder as fully synced. 

Expected behaviour: 
The folder gets either removed and is shown deselected
or: is fully populated with pyhsical files and shown selected. 

If the folder contains a mixture of virtual and pyhsical files, it is unclear, which of these behaviour is better. But in any case it should be consistent with the folder selection setting.

I'd suggest: when at least one file is pyhsical, make the entire folder selected (and physical). Maybe with a warning popup, that now more space may be used.

**Comment by michaelstingl** [comment]
Do we really need the migration back? As I understood, switching VFS off only changes future behavior.

**Comment by ogoffart** [comment]
> The click on the 3 dots of the sync folder to enable virtual files.

This did not exist in 2.5.0,  do you mean 2.5.1?

But as @michaelstingl explained, this is working as designed, this only affect new files.
And we do indeed erase the selective sync list when virtual files is enabled.

**Comment by jnweiger** [comment]
I mean 2.5.1 -- edited. 
If this is expected behaviour, then this is a design bug. 
a) it affects all existing files, not only new files.
b) having Photos/Squirrel.jpeg.owncloud in a folder where selective sync is on, (and vfs is off !) is an error.
c) renaming Photos/Squirrel.jpeg.owncloud to Photos/Squirrel.jpeg triggers a download of the pyhsical file. Renaming backwards makes it virtual again. Apparently both, selective sync and vfs are on in this folder.

**Comment by tessus** [comment]
People should be able to switch between virtual files and selective sync.
If this is not possible what is the supported way to not use virtual files anymore? 

You may find virtual files the best feature ever, but I can think of a few reasons why one don't want to use virtual files.
So at one point somebody decides to test virtual files and enables them. Now what? They are stuck with them forever? At least you should make it crystal clear that there's no way back.

I really believe some actions should be better guarded. (e.g. I still think that deleting a user on the server should be guarded by asking the admin to enter the userid (same as repo delete on github), but that's another story and does not belong here.)

**Comment by ogoffart** [comment]
> People should be able to switch between virtual files and selective sync

Currently, you can disable virtual files, this will only apply for new files (all virtual files will not be downloaded)
Then you can use selective sync to un-select folder again. 
And then you can go in the file explorer and take the option to download all the files.
You're back in the same situation as before. (Just that the selective sync list was removed and you need to uncheck folders again)

> If this is not possible what is the supported way to not use virtual files anymore?

Just don't enable them. There is a warning that it is an experimental feature already. 
If you find the message is not clear enough, please suggest an alternative.

**Comment by michaelstingl** [comment]
> I really believe some actions should be better guarded. (e.g. I still think that deleting a user on the server should be guarded by asking the admin to enter the userid (same as repo delete on github), but that's another story and does not belong here.)

@pmaier1 ^ FYI

**Comment by michaelstingl** [comment]
> You may find virtual files the best feature ever, but I can think of a few reasons why one doesn't want to use virtual files.

@tessus Could you elaborate? What are your use cases where VFS don't work?

**Comment by tessus** [comment]
@ogoffart 

> Just don't enable them. There is a warning that it is an experimental feature already.
If you find the message is not clear enough, please suggest an alternative.

I did not know that there was a message, however it should state something like:

If you choose to activate it, please note that the following steps are necessary to go back to your previous configuration: ....

I'm also not a big fan of help items opening a web page. IMO applications should have help text and files locally.

@michaelstingl 

> Could you elaborate? What are your use cases where VFS don't work?

1. Privacy - I might not want to have a stub for every single file on my server.
2. The VFS is still not really stable (according to issues and even comments from developers e.g. look at https://github.com/owncloud/client/issues/6876#issuecomment-438384391)
3. I haven't tested the VFS myself, but will it also work on the command line? Or is this just a Finder extension? - I do not use Finder, but have been using several alteratives over the years (PathFinder, ForkLift, ...).
4. the stub should not be called .owncloud, but .virtual - afaik the client can be used with any WebDAV server

I think the biggest no-go for me is that I do not use Finder - ever. A close second is item number 1.

**Comment by guruz** [comment]
> I haven't tested the VFS myself, but will it also work on the command line? Or is this just a Finder extension? - I do not use Finder, but have been using several alteratives over the years (PathFinder, ForkLift, ...).

It works on the command line. Just type ```open theFile.docx.owncloud```
it's not related to Finder or mounts, it's just files with a special extension.

**Comment by michaelstingl** [comment]
As I understood @jnweiger , renaming it with the extension triggers replacement with the virtual file.

**Comment by tessus** [comment]
> It works on the command line. Just type open theFile.docx.owncloud
it's not related to Finder or mounts, it's just files with a special extension.

What will `open` do? Will this download the file and open the .docx? Will it open the client UI?
Let's say I have a text file: `text.txt.owncloud`. Will `cat text.txt.owncloud` show me the contents of `text.txt`?

I usually work on the command line on Linux and macOS and unfortunately a true headless client is still missing. (sad face)
I know that there's a way to run `owncloudcmd` periodically on Linux, but that's not a real sync client. Especially on Linux using inotify should be an easy way to trigger syncs. Anyway, this is also off-topic here.

**Comment by guruz** [comment]
@tessus No, using any IO etc won't work. It's not the real file, it's only something that tells the client to download it..

**Comment by tessus** [comment]
@guruz well, but this basically means that the Finder is required to use virtual files. (`open` is the commandline access to Finder.) 

To summarize: `open text.txt.owncloud` will open the file in a text editor. However, using the file on the command line does not work, unless it has already been downloaded.

**Comment by michaelstingl** [comment]
@tessus renaming the file worked well. Add the `.owncloud` extension and your local file will be replaced with a 0-size placeholder file. Remove the `.owncloud` extension and download starts and replaces the 0-size placeholder file with actual file. This works independent from Finder.

@owncloud/desktop-core-developers Should we make this a real feature? (Add to QA etc)

**Comment by ckamm** [comment]
@michaelstingl I'd say it's an inelegant fallback for cases where there's no context menu available. For non-suffix vfs this wouldn't work.

From the client point of view it's a feature and tested. It could be added to QA and docs, I'd not advertise it as a default way of interacting with with suffix-virtual files.

**Comment by michaelstingl** [comment]
> It could be added to QA and docs

👍 

> I'd not advertise it as a default way of interacting with with suffix-virtual files.

👍

**Comment by ckamm** [comment]
@jnweiger Switching between "online only" and "available locally" got significant upgrades in master. Would you recheck?

**Comment by michaelstingl** [comment]
> @michaelstingl @dschmidt @ogoffart Agree?

yeah, sounds good 👍

**Comment by ckamm** [comment]
Switching between vfs and selective sync is done in #6954

**Comment by HanaGemela** [comment]
> Expected behaviour:
> The folder gets either removed and is shown deselected
> or: is fully populated with pyhsical files and shown selected.

@ckamm @michaelstingl which expected result is correct?

**Comment by ckamm** [comment]
@HanaGemela The expected behavior is that selective sync settings are reset when vfs is enabled. So after deactivating vfs the folder should show as selected and all contained files should be downloaded.

**Comment by HanaGemela** [comment]
Switching between VFS and selective sync works as expected in Windows 10 and client 2.6.0alpha2 (build 12097), macOS 10.14.5 and client 2.6.0alpha2 (build 12128)

For renaming I've raised a separate issue https://github.com/owncloud/client/issues/7338
