### ISSUE TITLE
[Linux] after Upgrade from 2.4.3 to 2.5.1 both Clients run 

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#6878]
Operating System : Ubuntu 18.10 , Centos 7
install owcloud-client version 2.4.3 for Ubuntu 18.04 or Centos 7
start owncloud-client 
connect to demo.owncloud.com
sync-folder is /home/admin1/owncloud
upgrade to 2.5.1 
start owncloud-client 
connect to demo.owncloud.com
sync-folder is again /home/admin1/owncloud (conflict happens)
both owncloud-clients run 

![screenshot_20181113_152240](https://user-images.githubusercontent.com/44814084/48423349-ba1adf00-e760-11e8-93af-c2358d883389.png)

expected that two Clients never run in the same Folder .

**Comment by jnweiger** [comment]
The new 2.5.1 was manually started. I would expect that starting 2.5.1 while 2.4.3 is running would  cause 2.4.3 to show its settings dialog and 2.5.1 would exit immediately.

**Comment by michaelstingl** [comment]
what are the steps to reproduce?

**Comment by ogoffart** [comment]
Two instances are not supposed to run at the same time.
How was the second application started?
Normaly, it uses a lockfile in the $TMPDIR. Have you been messing with these?

**Comment by jnweiger** [comment]
@michaelstingl the steps above dont work for you?

**Comment by jnweiger** [comment]
The client process has a filedescriptor open to /tmp/qtsingleapplication-787e-3e8-lockfile
That is probably the name of the lock file on my machine. @lazawan can you check if you have two such lockfiles?

**Comment by lazawan** [comment]
@ogoffart do you mean the lockfiles ,that are under /tmp ? if yes ,then these are the files ,that i found:
qtsingleapplication-5aa9-3e8
qtsingleapplication-5aa9-3e8-lockfile
qtsingleapplication-a876-3e8
qtsingleapplication-a876-3e8-lockfile

**Comment by ogoffart** [comment]
They actually should have a name like this: `/tmp/qipc_sharedmemory_qtsingleapplication*`.
The `/tmp/qtsingleapplication-*` is the pipe which allow communication between two apps
The fact that there are two pipe shows that two applications are running.

Normally there should be only one qipc_sharedmemory_qtsingleapplication<hash>.


What's the Qt version used in the different versions?

**Comment by jnweiger** [comment]
2.4.3 uses qt-5.6.2 and 2.5.1 uses qt-5.10.1

I can trivially reproduce on a fresh ubuntu 16.04 box. 
there is:
```
ll /tmp/q*
-rw-r----- 1 testy testy    0 Nov 14 11:49 /tmp/qipc_sharedmemory_qtsingleapplicationbfde75a5bf91e5179df8ee7ad4556d71fef8ca2ca6aa
srwxrwxr-x 1 testy testy    0 Nov 14 11:51 /tmp/qtsingleapplication-2d22-3e8=
-rw-rw-r-- 1 testy testy    0 Nov 14 11:51 /tmp/qtsingleapplication-2d22-3e8-lockfile
srwxrwxr-x 1 testy testy    0 Nov 14 11:49 /tmp/qtsingleapplication-7df3-3e8=
-rw-rw-r-- 1 testy testy    0 Nov 14 11:49 /tmp/qtsingleapplication-7df3-3e8-lockfile
-rw------- 1 testy testy 1373 Nov 14 12:00 /tmp/qt-trayicon-Wv7343.png

**Comment by jnweiger** [comment]
I have captured a logfile with --logdebug, but no messages about the startup in there. :-(
There was a console output saying

```
gui.application: Migrating old config from "/home/testy/.local/share/data//ownCloud" to "/home/testy/.config/ownCloud"
```
all fine so far... hmm. 
But I also have both 2.4.3 and 2.5.1 running simultaneously in the same sync folder.

**Comment by jnweiger** [comment]
strace log of 251 startup, when 243 is already running mentions the exact qipc* file that was created by 243:

```10189 access("/opt/ownCloud/qt-5.10.1/lib/x86_64-linux-gnu/qt5/plugins/styles/.", F_OK) = -1 ENOENT (No such file or directory)
10189 access("/opt/ownCloud/ownCloud/bin/styles/.", F_OK) = -1 ENOENT (No such file or directory)
10189 getuid()                          = 1000
10189 open("/tmp/qipc_systemsem_qtsingleapplicationbfde75a5bf91e5179df8ee7ad4556d71fef8ca2ca6aa", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0640) = 10
10189 close(10)                         = 0
10189 stat("/tmp/qipc_systemsem_qtsingleapplicationbfde75a5bf91e5179df8ee7ad4556d71fef8ca2ca6aa", {st_mode=S_IFREG|0640, st_size=0, ...}) = 0
10189 semget(0x51014650, 1, IPC_CREAT|IPC_EXCL|0600) = 2031616
10189 semctl(2031616, 0, SETVAL, 0x1)   = 0
10189 open("/tmp/qipc_systemsem_qtsingleapplicationbfde75a5bf91e5179df8ee7ad4556d71fef8ca2ca6aa", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0640) = -1 EEXIST (File exists)
10189 stat("/tmp/qipc_systemsem_qtsingleapplicationbfde75a5bf91e5179df8ee7ad4556d71fef8ca2ca6aa", {st_mode=S_IFREG|0640, st_size=0, ...}) = 0
10189 semget(0x51014650, 1, IPC_CREAT|IPC_EXCL|0600) = -1 EEXIST (File exists)
10189 semget(0x51014650, 1, IPC_CREAT|0600) = 2031616
10189 semctl(2031616, 0, SETVAL, 0x1)   = 0
10189 semop(2031616, [{0, -1, SEM_UNDO}], 1) = 0
10189 open("/tmp/qipc_sharedmemory_qtsingleapplicationbfde75a5bf91e5179df8ee7ad4556d71fef8ca2ca6aa", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0640) = -1 EEXIST (File exists)
10189 access("/tmp/qipc_sharedmemory_qtsingleapplicationbfde75a5bf91e5179df8ee7ad4556d71fef8ca2ca6aa", F_OK) = 0
10189 stat("/tmp/qipc_sharedmemory_qtsingleapplicationbfde75a5bf91e5179df8ee7ad4556d71fef8ca2ca6aa", {st_mode=S_IFREG|0640, st_size=0, ...}) = 0
10189 shmget(0x5101272b, 1024, IPC_CREAT|IPC_EXCL|0600) = -1 EEXIST (File exists)
10189 semop(2031616, [{0, 1, SEM_UNDO}], 1) = 0
10189 unlink("/tmp/qipc_systemsem_qtsingleapplicationbfde75a5bf91e5179df8ee7ad4556d71fef8ca2ca6aa") = 0
10189 semctl(2031616, 0, IPC_RMID, 0)   = 0
10189 open("/tmp/qipc_systemsem_qtsingleapplicationbfde75a5bf91e5179df8ee7ad4556d71fef8ca2ca6aa", O_RDWR|O_CREAT|O_EXCL|O_CLOEXEC, 0640) = 10
10189 close(10)                         = 0
10189 stat("/tmp/qipc_systemsem_qtsingleapplicationbfde75a5bf91e5179df8ee7ad4556d71fef8ca2ca6aa", {st_mode=S_IFREG|0640, st_size=0, ...}) = 0
10189 semget(0x51014650, 1, IPC_CREAT|IPC_EXCL|0600) = 2064384
10189 semctl(2064384, 0, SETVAL, 0x1)   = 0
10189 semop(2064384, [{0, -1, SEM_UNDO}], 1) = 0
10189 access("/tmp/qipc_sharedmemory_qtsingleapplicationbfde75a5bf91e5179df8ee7ad4556d71fef8ca2ca6aa", F_OK) = 0
10189 stat("/tmp/qipc_sharedmemory_qtsingleapplicationbfde75a5bf91e5179df8ee7ad4556d71fef8ca2ca6aa", {st_mode=S_IFREG|0640, st_size=0, ...}) = 0
10189 shmget(0x5101272b, 0, 0600)       = 5275662
10189 shmat(5275662, NULL, 0)           = 0x7f6788a8a000
10189 shmctl(5275662, IPC_STAT, {shm_perm={uid=1000, gid=1000, mode=0600, key=1359030059, cuid=1000, cgid=1000}, shm_segsz=1024, shm_cpid=9138, shm_lpid=10189, shm_nattch=1, shm_atime=1542198589, shm_dtime=1542198289, shm_ctime=1542198262}) = 0
10189 semop(2064384, [{0, 1, SEM_UNDO}], 1) = 0
10189 open("/tmp/qtsingleapplication-bf6d-3e8-instances", O_RDWR|O_CREAT|O_CLOEXEC, 0666) = 10
10189 fcntl(10, F_SETLKW, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
10189 getuid()                          = 1000
10189 open("/tmp/qtsingleapplication-95d2-3e8-lockfile", O_RDWR|O_CREAT|O_CLOEXEC, 0666) = 11
10189 fcntl(11, F_SETLK, {l_type=F_WRLCK, l_whence=SEEK_SET, l_start=0, l_len=0}) = 0
10189 access("/tmp/qtsingleapplication-95d2-3e8", F_OK) = 0
10189 unlink("/tmp/qtsingleapplication-95d2-3e8") = 0
10189 socket(PF_LOCAL, SOCK_STREAM|SOCK_CLOEXEC, 0) = 12
10189 bind(12, {sa_family=AF_LOCAL, sun_path="/tmp/qtsingleapplication-95d2-3e8"}, 110) = 0
10189 listen(12, 50)  
```
Its open O_CREAT|O_EXCL  runs twice into EEXIST, then decides to unlink and then the open succeeds. 
That unlink must not happen.

**Comment by ogoffart** [comment]
Ah, I see, the problem is because of the two different version of Qt. 

From the Qt 5.9.0 changelog:

```
****************************************************************************
*                        Important Behavior Changes                        *
****************************************************************************
[...]
- [QTBUG-60771] Reverted a change that caused Qt 5.6 through 5.8 not to
  connect to QSystemSemaphore and QSharedMemory created by running
  applications using Qt earlier than 5.6. Unfortunately, this means that Qt
  5.9 will not connect to 5.6-5.8.
```

In other words, Qt 5.6 had a "bug" that caused version Qt 5.6 to Qt 5.8 QSharedMemory to be incompatible with other Qt versions.

There is nothing we can do to fix this bug.
And I do not consider this critical as this is quite a corner case.

**Comment by jnweiger** [comment]
So the incompatibility of the two qt versions breaks our locking :-( 
Is there no other way to detect a running instance? 

Thinking of 
`pid=$(lsof $SYNCFOLDER/._sync_*.db 2>/dev/null | cut -d ' ' -f2)`
but that is probably not 100% reliable...

We risk data loss by wasting the lock.

**Comment by ogoffart** [comment]
As I said, it would require us to copy the Qt 5.6 implementation of QSharedMemory, and modify QtSingleApplication to check both. That's not a trivial task.
And considering that most people will have upgraded to 2.5.1 already,  and the remaining will probably not try to open two instences at the same time.

> We risk data loss by wasting the lock.

Do we?  This hasn't been carefully tested, but this normaly should not lead to terrible dataloss.

**Comment by dschmidt** [comment]
If at all - wouldn't it make more sense to backport the 5.9 fix to our 5.6 Qt - not the other way round?

**Comment by jnweiger** [comment]
I did not want to dig further into shared memory implementation details. Forward porting a compatibility layer is definitily overkill.
A connect() system call on the socket should be simple enough.

Do we know what impact sqlite corruption on a running client has? Maybe dataloss is not possible? I cannot tell.

**Comment by ogoffart** [comment]
> A connect() system call on the socket should be simple enough.

That's a not a bad idea...  That could work.  
But I still do not think it is worth it.

**Comment by dschmidt** [comment]
> No that would not make sense, we won't release anything with Qt 5.6 anymore.

Well we can still fix our linux packages... I'd not want to keep the workaround forever. We could not ever remove it without the same situation as now. If you say it's not going to eat data, let's not do anything.
