### ISSUE TITLE
after Deleting Owncloud-client 2.5.1 ,it's still running with Error

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#6879]
Client is still running  ,though it was deleted  . see please the following Photo below :

![screenshot_20181113_161801](https://user-images.githubusercontent.com/44814084/48427333-d15dca80-e768-11e8-9f5c-ce654006ae5b.png)

Steps to reproduce the Issue :
install client 2.5.1 on Centos 7
run the Client
try to connect with demo account (demo.owncloud.com)
let client  synchronize the files 
delete the client using " sudo yum remove owncloud-client "

regards,
lazawan

**Comment by jnweiger** [comment]
What is the behaviour on win or macos in this case? 
Should we add a kill to the postrm script?

**Comment by ogoffart** [comment]
This is how any application on linux work, you can remove the binary, but the application will continue working.

**Comment by jnweiger** [comment]
owncloud-client continues working with an error message "Could not read system exclude file" so it is already half broken. I dont think it makes sense to continue in our case.
