### ISSUE TITLE
[2.5.1] Unhandled C++ Exception in PropagateUploadFileNG::startNextChunk()

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6880]
https://sentry.io/owncloud/desktop-win-and-mac/issues/655442309/events/36380829151/
```
﻿﻿Crash: Unhandled C++ Exception at 0x773017d2
  File "propagateuploadng.cpp", line 319, in OCC::PropagateUploadFileNG::startNextChunk()
  File "propagateuploadng.cpp", line 442, in OCC::PropagateUploadFileNG::slotPutFinished()
```

We were discussing a similar backtrace here: https://github.com/owncloud/client/issues/6699#issuecomment-420513324

**Comment by guruz** [comment]
Related https://github.com/owncloud/enterprise/issues/2985

**Comment by ogoffart** [comment]
Since it is the location of one of the bigger allocation, it is likely to be triggered in a out of memory situation.
We were hoping that the leaks were fixed in 2.5.1. Maybe there's still leaks. Or maybe it's just the peak memory which is too big.

**Comment by ckamm** [comment]
The sentry issue shows that this is still regularly reported with 2.5.1 on Windows. However, I don't think we can do much without further information. I think both @ogoffart and me have already done a bunch of analysis around this and I would imagine further undirected work to not be worth the cost. I'd be different if there was a hint, through user reports of heap tracking tools.

One thing we might try would be including memory tracking code in the released client, so users can more easily provide us with useful data on memory issues.

**Comment by ckamm** [comment]
Ideas:
- We could catch all exceptions and log them
- We could add extra logging like #6855 

Do you know of a way to make the stackframe for `prepareAndOpen()` show up? Stacktraces always point to propagateuploadng:319 and then into QtCore.

**Comment by ckamm** [comment]
Interestingly there seems to be no case of this issue reported for >=2.5.2

**Comment by ckamm** [comment]
On further investigation this is likely to be the 2.5.2, 2.5.3 version of this crash: https://sentry.io/organizations/owncloud/issues/866377501 . It points towards not enough memory being available for allocating the uploaddevice.

**Comment by ckamm** [comment]
How about we try-catch around that particular allocation - which is way more likely than others to fail - and report it as a sync error?

**Comment by HanaGemela** [comment]
@ckamm @guruz is this something I can test? If so, please provide steps to recreate. Otherwise please close
