### ISSUE TITLE
plugin owncloud-client-nautilus.x86_64 on Centos 7 does not work.

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#6884]
the plugin doesn't work because of lack of package "python-nautilus"

**Comment by jnweiger** [comment]
The exact error is:
```
yum install -t owncloud-client-nautilus 
---> Package owncloud-client-nautilus.x86_64 0:2.5.1.10973-10450.1 will be installed
--> Processing Dependency: nautilus-python for package: owncloud-client-nautilus-2.5.1.10973-10450.1.x86_64
--> Finished Dependency Resolution
Error: Package: owncloud-client-nautilus-2.5.1.10973-10450.1.x86_64 (isv_ownCloud_desktop)
           Requires: nautilus-python
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```

The suggested 'You could try' hints do not work. `yum Install --tolerant` also does not work.

Package nautilus-python is not available from standard centos repos.
One workaround is:
```
wget http://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -Uhv epel-release-latest-7.noarch.rpm
yum install nautilus-python owncloud-client-nautilus
```

I have no idea how we can give that hint to an end-user when the error happens. (Instead or additional to the useless hints that are given)

**Comment by michaelstingl** [comment]
Deprecate file manager extensions for CentOS 6 & 7 ? (This would also mean that VFS can't be used) /cc @moscicki thoughts?

**Comment by HanaGemela** [comment]
The same for Centos 8

**Comment by jnweiger** [comment]
Tested on CentOS8: out testpilotcloud-client-nautilus package places its  extension in /usr/share/nautilus-python/extensions/synstate-testpilotcloud.py -- Nautilus does not pick it up there without the glue-code from the nautilus-python package. No such package is found in the system repositories.

**Comment by jnweiger** [comment]
For CentOS-7 we now provide our own nautilus-python apdapter.
The suse OBS does not want to build any python cpde for CentOS8, we neither have python2 nor python3 in OBS, although python36 is a default install with centos 8 otherwise. 
![image](https://user-images.githubusercontent.com/1108546/67313284-03dc7f80-f503-11e9-97a0-2502bf6fa310.png)

Workaround for CentOS_8:

The CentOS_7 build of nautilus-python also works fine on CentOS_8:
![image](https://user-images.githubusercontent.com/1108546/67313125-b95b0300-f502-11e9-8a16-528dbc4485d3.png)

This fixes the original issue, but leaves space for improvement with CentOS_8. We need help from openSUSE ...

**Comment by jnweiger** [comment]
Made the CentOS_7 nautilus-python available in the CentOS_8 repo of isv:ownCloud:testpilot:testing
```
[root@centos8 testy]# yum install testpilotcloud-client-nautilus
Letzte Prüfung auf abgelaufene Metadaten: vor 0:00:08 am Mi 23 Okt 2019 15:42:38 CEST.
Abhängigkeiten sind aufgelöst.
================================================================================
 Paket             Arch   Version          Paketquelle                    Größe
================================================================================
Installing:
 testpilotcloud-client-nautilus
                   x86_64 2.6.0~rc2-1603.1 isv_ownCloud_testpilot_testing  13 k
Installiere Abhängigkeiten:
 nautilus-python   x86_64 1.2.2-3.1        isv_ownCloud_testpilot_testing  29 k
 testpilotcloud-client
                   x86_64 2.6.0~rc2-1603.1 isv_ownCloud_testpilot_testing 1.8 M
 testpilotcloud-client-l10n
                   x86_64 2.6.0~rc2-1603.1 isv_ownCloud_testpilot_testing 444 k
 testpilotcloud-client-overlays-icons
                   x86_64 2.6.0~rc2-1603.1 isv_ownCloud_testpilot_testing 144 k

Transaktionsübersicht
================================================================================
Installieren  5 Pakete

Gesamte Downloadgröße: 2.4 M
Installationsgröße: 8.4 M
Ist dies in Ordnung? [j/N]:  
```
