### ISSUE TITLE
upgrading from 2.4.3 oc-client to 2.5.1 on fedora 29 failed

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#6887]
upgrading failed 
steps to reproduce the bug :  
install owncloud-client 2.4.3 on fedora 29 box (2.4.3 for fedora 29 is not available ,please use package for fedora 28)
run owncloud-client 2.4.3
upgrade client 2.4.3 to 2.5.1 
run owncloud-client   >>>  version 2.4.3.was not upgraded to 2.5.1 (it is still 2.4.3) and owncloud-client gives the following error message 

![screenshot_20181115_160417](https://user-images.githubusercontent.com/44814084/48566028-1cf3ae00-e8fa-11e8-87cd-3605818135a8.png)
and in terminal gives the output : "  gui.application already running,existing "

reboot system after a failed upgrade in the hope that 2.4.3 works again 
>>>  version 2.4.3 ,that wasn't upgraded to 2.5.1 ,now doesn't react 

![screenshot_20181115_161246](https://user-images.githubusercontent.com/44814084/48566348-e0748200-e8fa-11e8-8b12-4597ee91e788.png)

i almost forgot to mention that owncloud-logo doesn't appear at taskbar too .
as a hint : 
 when one installs 2.5.1 directly (without upgrading ) ,it works without problems

**Comment by jnweiger** [comment]
dnf install does not attempt upgrades. To upgrade an loder version to a newer version of an already installed package, we need to use

```
dnf upgrade owncloud-client
```

**Comment by jnweiger** [comment]
owncloud-client 2.5.1 on Fedora 28 with gnome 3.28.2 has
* tray icon is also missing
* but the settings dialog opens correctly when a second owncloud-client instance is started.

**Comment by jnweiger** [comment]
The tray icon behaviour depneds on the exact gmome version, before 3.16 and after 3.25 makes a difference https://www.omgubuntu.co.uk/2017/09/will-you-miss-gnome-legacy-tray

**Comment by jnweiger** [comment]
On Fedora 28 there is `gnome-shell-extension-topicon-plus` that promisies to "move all legacy tray icons to the top panel".
But installing this package and rebooting does not make the icon appear.

**Comment by TheOneRing** [comment]
@jnweiger can we close this one?
