### ISSUE TITLE
owncloud-client-icon "version 2.5.1 " at taskbar on leap_15 is not identical to owncloud-Logo/icon

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#6889]
please see the photo below : 

![screenshot_20181120_144833](https://user-images.githubusercontent.com/44814084/48780921-40906d00-ecdb-11e8-8b65-ff9cf2e6bf7e.png)

until version 2.4.3 icon was correct

**Comment by dragotin** [comment]
Is that the package coming with openSUSE or the one provided by ownCloud?

**Comment by michaelstingl** [comment]
sounds like https://github.com/owncloud/client/issues/5612

**Comment by michaelstingl** [comment]
@dragotin commented in an [internal thread in May 2017:](https://github.com/owncloud/ownbrander/issues/715#issuecomment-298881098)

> I think that should be fixed in the code. If branding is active, the icon should not be read from the distro theme, and if not (unbranded client) the icon should be read from theme.
> 
> That results in the correct icon for branded clients, and a potentially desktop aligned one for the unbranded.

Also see discussion in https://github.com/owncloud/client/issues/6036 regarding accessibility etc

**Comment by ogoffart** [comment]
It is not the distro which are theming the app.  It's the KDE Icon style (breeze) which provide an icon for owncloud.

Also, the patch disable theming for all icons.
I would recommend against patching that, and leave the breeze icon.

**Comment by ogoffart** [comment]
(note that the advantage of the breeze icon is that it fits properly in the kde system tray, while the default icon looks a bit alien, being the only icon not in a "flat" design))

**Comment by dragotin** [comment]
@ogoffart correct, and I agree. I just posted the patch as it proofs that our guess was right. I haven't committed the patch to the package.
