### ISSUE TITLE
Linux: In our packages, have a oc-sqlite3

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6891]
This is without real urgency, but would help against performance and compile problems on distros with old sqlite3.

As discussed with @jnweiger the idea would be to create a oc-sqlite3 package that is used by owncloud-client and oc-qtwebkit packages.

**Comment by guruz** [comment]
@crrodriguez Everything .RPM is fine, .DEB would be cool but not urgent.
We're already shipping a current sqlite3 with the client (for macOS and Windows) so we'd want the same for Linux but as package (for technical reasons, can't link to it directly on Linux)

**Comment by jnweiger** [comment]
package version 3.26.0 for https://blade.tencent.com/magellan/index_en.html

**Comment by jnweiger** [comment]
For Linux I have packaged 3.26.0 https://build.opensuse.org/package/show/isv:ownCloud:Qt5122/ocqt5122-sqlite3
