### ISSUE TITLE
Dual screen icon glitch on OSX Mojave

### ISSUE THREAD

**Issue by asterisktec** [owncloud/client#6895]
This is more of an annoyance than a problem but it would be nice to have fixed (if possible).

### Expected behaviour
Owncloud client starts up and icon appears in menu bar with focus on either primary or secondary monitor. When using colored or monochrome icons the client appears in menu bar with no graphical errors

### Actual behaviour
Owncloud client starts up and icon appears in menu bar with focus on either primary or secondary monitor. When using monochrome icons the client appears in menu bar with no a strange black box around the Ownloud icon, I'm guessing this is a transparency mask. If color icons are used, there is no issue.

<img width="282" alt="screen shot 2018-11-22 at 9 29 47 am" src="https://user-images.githubusercontent.com/6060635/48915287-5a48c600-ee3b-11e8-9ae4-1a58e89311c5.png">

### Steps to reproduce
1. Connect external monitor to Mac via HDMI ensure that "Displays have separate space" is enabled.
2. Set Owncloud client to use monochrome icons and restart client
3. Square box appears around icon when running, will disappear once icon is clicked.

### Server configuration
Operating system:
Ubuntu 14.04.01
Web server: 
Apache
Database:
MySQL
PHP version:

ownCloud version:
10.0.2.1
Storage backend (external storage):

### Client configuration
Client version:
2.5.1

Operating system:
OSX Mojave

OS language:
Canadian English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
Default
### Logs

11-22 10:02:42:321 [ info sync.accessmanager ]:	6 "PROPFIND" "https://cloud.nine-one-one.ca:8800/remote.php/dav/files/ahanley/" has X-Request-ID "9c710cbb-4195-40b2-b3f0-d4c4d317d8ad"
11-22 10:02:42:322 [ info sync.networkjob ]:	OCC::PropfindJob created for "https://cloud.nine-one-one.ca" + "/" "OCC::ConnectionValidator"
11-22 10:02:42:347 [ info gui.account.manager ]:	Saving account "https://cloud.nine-one-one.ca:8800"
11-22 10:02:42:348 [ info gui.account.manager ]:	Saving  1  unknown certs.
11-22 10:02:42:348 [ info gui.account.manager ]:	Saving cookies. "/Users/alanhanley/Library/Preferences/ownCloud/cookies0.db"
11-22 10:02:42:352 [ info gui.account.manager ]:	Saved account settings, status: QSettings::Status(NoError)
11-22 10:02:42:352 [ info sync.account ]:	"SSL-Errors happened for url  \"https://cloud.nine-one-one.ca:8800/remote.php/dav/files/ahanley/\" \tError in  QSslCertificate(\"3\", \"dc:86:86:d5:fb:70:ce:48\", \"i90DmmPJ0PUlR5YSkEK9vA==\", (\"Nine-One-One Communication Supply\"), (\"Nine-One-One Communication Supply\"), QMap(), QDateTime(2016-06-23 14:25:19.000 UTC Qt::TimeSpec(UTC)), QDateTime(2017-06-23 14:25:19.000 UTC Qt::TimeSpec(UTC))) : \"The certificate is self-signed, and untrusted\" ( \"The certificate is self-signed, and untrusted\" ) \n \tError in  QSslCertificate(\"3\", \"dc:86:86:d5:fb:70:ce:48\", \"i90DmmPJ0PUlR5YSkEK9vA==\", (\"Nine-One-One Communication Supply\"), (\"Nine-One-One Communication Supply\"), QMap(), QDateTime(2016-06-23 14:25:19.000 UTC Qt::TimeSpec(UTC)), QDateTime(2017-06-23 14:25:19.000 UTC Qt::TimeSpec(UTC))) : \"The certificate has expired\" ( \"The certificate has expired\" ) \n " Certs are known and trusted! This is not an actual error.
11-22 10:02:42:452 [ info sync.networkjob.propfind ]:	PROPFIND of QUrl("https://cloud.nine-one-one.ca:8800/remote.php/dav/files/ahanley/") FINISHED WITH STATUS "OK"
11-22 10:02:45:321 [ info gui.folder ]:	Trying to check "https://cloud.nine-one-one.ca:8800/remote.php/dav/files/ahanley/" for changes via ETag check. (time since last sync: 1377 s)
11-22 10:02:45:322 [ info sync.accessmanager ]:	6 "PROPFIND" "https://cloud.nine-one-one.ca:8800/remote.php/dav/files/ahanley/" has X-Request-ID "711276eb-3a6d-4fe0-9635-a5907cc42d49"
11-22 10:02:45:322 [ info sync.networkjob ]:	OCC::RequestEtagJob created for "https://cloud.nine-one-one.ca" + "/" "OCC::Folder"
11-22 10:02:45:418 [ info sync.networkjob.etag ]:	Request Etag of QUrl("https://cloud.nine-one-one.ca:8800/remote.php/dav/files/ahanley/") FINISHED WITH STATUS "OK"

**Comment by michaelstingl** [comment]
@lazawan Could you have a look next week?

**Comment by guruz** [comment]
I suspect this can only be fixed by changing Qt to use macOS' native menu bar icon drawing.
(Discovered in https://github.com/owncloud/client/issues/4174#issuecomment-192255048 )

**Comment by TheOneRing** [comment]
Fixed by one of the Qt updates in the last 4 years.
