### ISSUE TITLE
[Crash] [macOS 10.14.1] ownCloud crashes when trying to synchronise

### ISSUE THREAD

**Issue by rei-vilo** [owncloud/client#6896]
### Expected behaviour
ownCloud synchronises without crashing.

### Actual behaviour
ownCloud crashes when trying to synchronise.

### Steps to reproduce
1. Launch ownCloud.
2. Wait for the automatic synchronisation.

### Server configuration
Operating system: Linux 4.14.71-v7+ #1145 SMP Fri Sep 21 15:38:35 BST 2018 armv7l GNU/Linux

Web server: 10.0.8.5

Database: mysql  Ver 15.1 Distrib 10.1.23-MariaDB, for debian-linux-gnueabihf (armv7l) using readline 5.2

PHP version: PHP 7.0.30-0+deb9u1 (cli) (built: Jun 14 2018 13:50:25) ( NTS )

ownCloud version:

Storage backend (external storage): yes

### Client configuration
Client version: Version 2.5.1 (build 10818)

Operating system: macOS 10.14.1

OS language: French

Qt version used by client package (Linux only, see also Settings dialog): NA

Client package (From ownCloud or distro) (Linux only): NA

Installation path of client: /Applications

### Logs

crash bp-6835b2d3-a6f3-454e-82ba-9a1c72181122

**Comment by rei-vilo** [comment]
Again with Version 2.6.0-daily20181122 (build 10867) reported as crash bp-7c134c8d-d1f6-4b56-ae6f-7f9dc2181123

**Comment by michaelstingl** [comment]
@rei-vilo I think we've seem this before, but were never able to reproduce this. The information in the crash report isn't sufficient. Please enable permanent debug logging, so you will capture the actions performed right before the next crash…: https://doc.owncloud.com/desktop/latest/troubleshooting.html#logging-to-a-temporary-directory

**Comment by rei-vilo** [comment]
I've tried the permanent debug logging, but saw nothing labelled as error after the crash.

So I've reverted back to Version 2.4.3 (build 10347), which was stable.

**Comment by michaelstingl** [comment]
Could you send the lines before the crash to `apps<at>owncloud.com` ?

**Comment by rei-vilo** [comment]
I've been running ownCloud with logging on but I've faced no crash for the last 24 hours.

Random errors are the most difficult to spot and fix.

**Comment by guruz** [comment]
This is the same (so far unresolved) crash as in https://github.com/owncloud/client/issues/6787

> So I've reverted back to Version 2.4.3 (build 10347), which was stable.

That's interesting because we also have users reporting this crash with 2.4.3
e.g. https://sentry.io/owncloud/desktop-win-and-mac/issues/231973066/events/37195904808/

**Comment by ogoffart** [comment]
QCocoaEventDispatcher::processEvents  is the root of the event loop, so maybe it's a catch all for all the crashes.

Perhaps running the application in a debugger could give a more interesting backtrace.

**Comment by manngo** [comment]
I am using MacOS 10.14.2, and have had a number of crashes in the last few days. I don’t know whether this is the same issue.

**Comment by japerki** [comment]
Please remove my email address

**Comment by rei-vilo** [comment]
@japerki You can mute the thread to no longer receive updates from it.

**Comment by guruz** [comment]
> I am using MacOS 10.14.2, and have had a number of crashes in the last few days. 

What's the crash ID (the long number separated by dashes) that is reported when submitting the crash report?

**Comment by guruz** [comment]
> QCocoaEventDispatcher::processEvents is the root of the event loop, so maybe it's a catch all for all the crashes.

if you click the ```full_report_url``` you can see the crash is actually much longer and happens somewhere inside macOS related to HIToolbox and AppKit.
So somehow GUI-triggered?
or only GUI involved?

**Comment by japostoles** [comment]
Crash here as well:  bp-64b4ebe9-5a37-46d2-b2f7-19ff02181221

I can't figure out how to turn on permanent debugging in my client

**Comment by manngo** [comment]
It took 5 days to happen again, but I got `bp-0b3c52a4-77c6-46ad-93a0-39c002181223`

**Comment by hidakat** [comment]
how about this solution?
I can't understand why it works, but my problem(oc desktop client for mac crashes) has solved. 
ref-> https://central.owncloud.org/t/owncloud-desktop-client-2-5-1-doesnt-start-on-macos-10-11-6/17338

at your environment, when you open the application in Terminall.app(type /Applications/owncloud.app/Contents/MacOS/owncloud ), you've got the message "dyld: lazy symbol binding failed: Symbol not found…", it's worth to try.
•delete oc client completely(just type sudo rm -rf sudo rm /Applications/owncloud.app)
•install oc desktop for mac (i tryied oc2.6 on mac os 10.13.6, it works!)

**Comment by ckamm** [comment]
Thank you for the reports. Unfortunately the crash reports don't contain useful backtraces so this is still a mystery issue. If you can, try running the client in a debugger and get a backtrace when the crash happens. That would be enormously helpful for addressing the problem. Currently we have little idea about what's causing it.

#6930 may be related and we're working on a fix there, but there's a chance this issue is a separate problem and still needs more information before it can be addressed.

**Comment by guruz** [comment]
Please also watch the memory usage "before" the crash (which is hard of course. so you'd check it each hour and note it down and then when it crashes you take the last value you wrote down).

**Comment by Rene33** [comment]
I have this problem of crashes on Mac OS desktop client 2.5.1 (build 10818) running on High Sierra (10.13.5). I have the app "memory clean", so the state of the memory is displayed. I did not observe any problem of low memory when the crash happens (once or twice a day). It did happen few minutes ago, and I have 1.36GB of free memory. 
I don't know whether it might be useful, but I found that in the system log

> Path:                  /Applications/owncloud.app/Contents/PlugIns/FinderSyncExt.appex/Contents/MacOS/FinderSyncExt
> Identifier:            com.owncloud.desktopclient.FinderSyncExt
>        0x10d512000 -        0x10d516ff7 +com.owncloud.desktopclient.FinderSyncExt (1.0 - 1) <7756C8C6-7C1E-341A-BF8C-D21DDB15B844> /Applications/owncloud.app/Contents/PlugIns/FinderSyncExt.appex/Contents/MacOS/FinderSyncExt

**Comment by guruz** [comment]
We (mostly @ckamm ..) made some patches that could fix this. They made it into the rc2.
Could you give this a try?
https://download.owncloud.com/desktop/testing/ownCloud-2.5.2.11135rc2.pkg

**Comment by Rene33** [comment]
Thanks!
It is installed! We have now to wait and see.

**Comment by jnweiger** [comment]
## tested 252rc2 on macos 10.13.6 and 10.14
Some manual torture test with 3700 files up and down looks good. No crashes. -> OK

**Comment by Rene33** [comment]
So far so good. It has been running for 6 days, without any crash...

**Comment by ChrisEdS** [comment]
Same here. I haven't seen a crash the whole week. Good work guys!

**Comment by guruz** [comment]
Great to hear!

**Comment by CTassisF** [comment]
I just experienced this issue on 2.5.2 too: `bp-087d5ebf-6cd9-4811-8317-aaa242190205`

**Comment by ckamm** [comment]
This looks like a different issue, the backtraces are different. Unfortunately they are both pretty non-informative:
```
Thread 6 (crashed) SIGABRT
 0  libsystem_kernel.dylib + 0x723e
    rax = 0x0000000000000000   rdx = 0x0000000000000000
    rcx = 0x000070000b131858   rbx = 0x000070000b132000
    rsi = 0x0000000000000006   rdi = 0x000000000000c703
    rbp = 0x000070000b131890   rsp = 0x000070000b131858
     r8 = 0x000070000b131718    r9 = 0x000070000b1318f0
    r10 = 0x0000000000000000   r11 = 0x0000000000000206
    r12 = 0x000000000000c703   r13 = 0x0000003000000008
    r14 = 0x0000000000000006   r15 = 0x000000000000002d
    rip = 0x00007fff68e7423e
    Found by: given as instruction pointer in context
 1  libsystem_c.dylib + 0x5c1c9
    rbp = 0x000070000b1318c0   rsp = 0x000070000b1318a0
    rip = 0x00007fff68ddd1c9
    Found by: previous frame's frame pointer
 2  libc++abi.dylib + 0x3231
    rbp = 0x000070000b1319f0   rsp = 0x000070000b1318d0
    rip = 0x00007fff6645d231
    Found by: previous frame's frame pointer
 3  libc++abi.dylib + 0x33b5
    rbp = 0x000070000b131e30   rsp = 0x000070000b131a00
    rip = 0x00007fff6645d3b5
    Found by: previous frame's frame pointer
 4  libobjc.A.dylib + 0x18c8f
    rbp = 0x000070000b131e50   rsp = 0x000070000b131e40
    rip = 0x00007fff67c68c8f
    Found by: previous frame's frame pointer
 5  libc++abi.dylib + 0xedfe
    rbp = 0x000070000b131e70   rsp = 0x000070000b131e60
    rip = 0x00007fff66468dfe
    Found by: previous frame's frame pointer
 6  libc++abi.dylib + 0xee73
    rbp = 0x000070000b131e90   rsp = 0x000070000b131e80
    rip = 0x00007fff66468e73
    Found by: previous frame's frame pointer
 7  QtCore!QThreadPrivate::start(void*) [qthread_unix.cpp : 388 + 0x5]
    rbp = 0x000070000b131f10   rsp = 0x000070000b131ea0
    rip = 0x000000010d94ca46
    Found by: previous frame's frame pointer
```

**Comment by ckamm** [comment]
Moved new issue to #7016
