### ISSUE TITLE
[Windows] [2.5.1] crash during sync (propagation)

### ISSUE THREAD

**Issue by panta82** [owncloud/client#6897]
After updating client to 2.5.1 and server to 10.0.10, I am getting persistent crashes after a few hours of background sync. It seems like the same issue as #6801.

Crash id: `bp-a7838cf3-24a0-4f60-8236-0872e2181125`

I've tailed the last 10000 lines of the client log and pasted that here: https://gist.github.com/panta82/069a3585f152716bb561a47d149868de

LMK if you need more, there is like 1 gigabyte of logs. But there doesn't seem to be anything notable there.

**Comment by guruz** [comment]
@panta82 Could you try to check the memory usage of the client every hour or so?
We've looked at the crash and suspect it could be an out of memory situation

**Comment by guruz** [comment]
@panta82 How many files/folders are in this sync folder?

**Comment by panta82** [comment]
@guruz I have 4 folders with a LOT of files. Here's the breakdown.

![image](https://user-images.githubusercontent.com/4291324/49033633-00842b00-f1b0-11e8-929d-fafe9542cc6e.png)

![image](https://user-images.githubusercontent.com/4291324/49033689-1eea2680-f1b0-11e8-8d62-592d59adf6fd.png)

I don't know which folder causes the crash.

**Comment by panta82** [comment]
@guruz I started the client and will be monitoring RAM usage.

**Comment by panta82** [comment]
Crash after 3 hours. I checked several times, and there was no apparent memory leak, ownCloud was taking ~ 100MB RAM. Also, sync seems to have worked, until the client crashed.

New crash id: `bp-1d954386-0327-412c-8fc2-75c3e2181126`

**Comment by michaelstingl** [comment]
@panta82 We plan to release a 2.6.0 RC2 tomorrow that should behave better:
https://github.com/owncloud/client/releases

Could you give it a try and provide feedback?

**Comment by TheOneRing** [comment]
Might have been the 4GB 32bit limit closing after needs info for 2 years
