### ISSUE TITLE
OperationCanceledError Connection timed out - opendir failed

### ISSUE THREAD

**Issue by JedatKinports** [owncloud/client#6900]
### Expected behaviour
All directories should get synced.

### Actual behaviour
One directory (which has 10000+ files in the same directory) doesn't get synced.

### Steps to reproduce
1. I execute this command: owncloudcmd -u username -p password --trust --non-interactive /var/www/something/ https://myowncloudserver.domain.com
2. Then I get this error: 

### Server configuration
Operating system: 

Debian 9

Web server: 

Apache/2.4.25 (Debian)

Database:

mysql

PHP version:

ownCloud version:

Storage backend (external storage):

/

### Client configuration
Client version:

`owncloudcmd -v`
ownCloud version 2.5.1 (build 10450)

Operating system:

Debian 9

OS language:

us

Qt version used by client package (Linux only, see also Settings dialog):

Using Qt 5.10.1, built against Qt 5.10.1

Client package (From ownCloud or distro) (Linux only):

owncloud-client

Installation path of client:

/usr/bin/owncloudcmd

### Logs

```
11-29 09:25:17:163 [ info sync.csync.csync ]:   ## Starting remote discovery ##
11-29 09:25:17:163 [ info sync.accessmanager ]: 6 "PROPFIND" "https://cloud.mydomain.com/remote.php/dav/files/filesync/" has X-Request-ID "eecbc783-e450-4204-8510-117ced4e574a"
11-29 09:25:17:164 [ info sync.networkjob ]:    OCC::LsColJob created for "https://cloud.mydomain.com" + "" "OCC::DiscoverySingleDirectoryJob"
11-29 09:25:17:239 [ info sync.networkjob.lscol ]:      LSCOL of QUrl("https://cloud.mydomain.com/remote.php/dav/files/filesync/") FINISHED WITH STATUS "OK"
11-29 09:25:17:240 [ info sync.csync.updater ]: Checking for rename based on fileid 00227869ocpw2kdzfkgx
11-29 09:25:17:241 [ info sync.csync.updater ]: file: images, instruction: INSTRUCTION_NEW <<=
11-29 09:25:17:241 [ info sync.accessmanager ]: 6 "PROPFIND" "https://cloud.mydomain.com/remote.php/dav/files/filesync/images" has X-Request-ID "23660c82-4d0a-4e05-a319-5325dcab11a9"
11-29 09:25:17:241 [ info sync.networkjob ]:    OCC::LsColJob created for "https://cloud.mydomain.com" + "/images" "OCC::DiscoverySingleDirectoryJob"
11-29 09:30:17:321 [ warning sync.networkjob ]: Network job timeout QUrl("https://cloud.mydomain.com/remote.php/dav/files/filesync/images")
11-29 09:30:17:321 [ warning sync.networkjob ]: QNetworkReply::NetworkError(OperationCanceledError) "Connection timed out" QVariant(Invalid)
11-29 09:30:17:321 [ info sync.networkjob.lscol ]:      LSCOL of QUrl("https://cloud.mydomain.com/remote.php/dav/files/filesync/images") FINISHED WITH STATUS "OperationCanceledError Connection timed out"
11-29 09:30:17:321 [ warning sync.discovery ]:  LSCOL job error "Operation canceled" 0 QNetworkReply::NetworkError(OperationCanceledError)
11-29 09:30:17:321 [ warning sync.csync.updater ]:      opendir failed for images - errno 5
11-29 09:30:17:321 [ warning sync.engine ]:     ERROR during  csync_update :  "An error occurred while opening a folder images: Operation canceled"
11-29 09:30:17:326 [ info sync.database ]:      Closing DB "/var/www/path/uploads/._sync_e3c4d804bfac.db"
11-29 09:30:17:327 [ info sync.engine ]:        CSync run took  302200 ms
11-29 09:30:17:329 [ info sync.database ]:      Closing DB "/var/www/path/uploads/._sync_e3c4d804bfac.db"

```

ANOTHER NOTE:

If I install the Windows client on another machine and set the "timeout" to 3600 under [General] in the %LOCALAPPDATA%\ownCloud\owncloud.cfg config file then the whole sync completes successfully. That's why I believe that the problem lies in the timeout.

**Comment by michaelstingl** [comment]
@JedatKinports You could check your owncloud.log for errors using the `X-Request-ID`'s.

**Comment by JedatKinports** [comment]
@michaelstingl do you mean the client or server log file? And how can I check this?

**Comment by ogoffart** [comment]
The default timeout is 5 minutes, which should be enough. (and we can confirm that by the time difference in the log: 09:25:17 -> 09:30:17)
The problem here is that your server is not replying in time. (or perhaps the connection was closed?)

**Comment by michaelstingl** [comment]
@JedatKinports The owncloud.log is generated on the ownCloud server. Server versions 10.0.4+ show the `X-Request-ID` from the clients requests. This way you can debug server issues that cause strange behaviour in the clients.

**Comment by JedatKinports** [comment]
@ogoffart so I would have to increase the timeout on the server probably? Do I do this in php.ini, apache config or in some owncloud config file? The connection was not closed I think. I tried it a couple of times.

@michaelstingl thank you. I will check the server logs and get back to you.

**Comment by ogoffart** [comment]
> so I would have to increase the timeout on the server probably?

No, the timeout is on the client (5 minutes). 
The problem is that the client takes way to long to answer.

**Comment by JedatKinports** [comment]
@michaelstingl so I have checked the server log and this is the error which I get there:

{"reqId":"f1881c1c-c343-4d2d-bf36-7252a72a2167","level":3,"time":"2018-11-29T02:13:31+00:00","remoteAddr":"client_ip","user":"my_username","app":"PHP","method":"PROPFIND","url":"\/remote.php\/dav\/files\/filesync\/images","message":"Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes) at \/var\/www\/owncloud\/lib\/composer\/doctrine\/dbal\/lib\/Doctrine\/DBAL\/Driver\/PDOStatement.php#142"}

Do I need more memory/RAM?

**Comment by michaelstingl** [comment]
@JedatKinports This is the client repo – I'm not an expert for server operations.

You can find helpful information in the docs:
https://doc.owncloud.com/server/10.0/admin_manual/installation/deployment_recommendations.html

…or ask for help in https://central.owncloud.org/
