### ISSUE TITLE
setting of shared folder was lost.

### ISSUE THREAD

**Issue by YTS85205107** [owncloud/client#6908]
**Expected behaviour**

I enabled external storage plugin on owncloud, and I shared a folder to user.
After restarting the server, it should not affect the settings of the folder. (ex: shared folder to who)

**Actual behaviour**

After server maintenance and restart, owncloud is normal, but setting of folder all lost.

**Steps to reproduce**

1. Mapping external storage that use sftp type.
![2018-11-30_16h18_03](https://user-images.githubusercontent.com/32276008/49277130-90c9b500-f4bb-11e8-886f-bccab0e19509.png)

2. After found folder from external storage , I shared it to user.
![2018-11-30_16h20_11](https://user-images.githubusercontent.com/32276008/49278633-51519780-f4c0-11e8-8379-c5d4dba56694.png)

3. Server restart.

4. Although user can find this folder, but folder setting was lost, so when user upload document to this folder, he still can't see document from external storage.
![2018-11-30_16h23_17](https://user-images.githubusercontent.com/32276008/49278643-59a9d280-f4c0-11e8-993f-75c73e3e76f9.png)

**Server configuration**

Ubuntu 16.04
Owncloud 10.0.10

**Client configuration**

Owncloud client 2.5.1

**Other comments:**
It has happened three times, include server maintenance restart and abnormal restart, although owncloud can restart and work fine, but setting of shared folder was lost.

Is there a setting that I have not set?

Thanks in advance.

**Comment by ogoffart** [comment]
Hi, this is the bug repository for the owncloud desktop client.
But it seems that this bug is a bug in the server. So please re-open this bug on the server repository https://github.com/owncloud/core
If you have a question which is not a bug report, you can also ask it in the forum: https://owncloud.org/help/

**Comment by YTS85205107** [comment]
Hi , @ogoffart 
Thanks your reply , I will re-open this bug on the server repository.
Thanks so much.

**Comment by guruz** [comment]
Server issue on https://github.com/owncloud/core/issues/33710

@ogoffart You can also try to 'Transfer this issue' in right sidebar here next time
