### ISSUE TITLE
[Windows] --logdir not making any logs

### ISSUE THREAD

**Issue by voroyam** [owncloud/client#6909]
Description in the title.

Tried to have the log dir at C, then as a folder on my desktop - no log files are written.

Latest Client, latest windows with latest updates.

Examples I tried

`owncloud.exe --logdir C:\Users\user1\Desktop\oclog`

`C:\Program Files (x86)\ownCloud>owncloud.exe --logdir C:\oclog`

`C:\Program Files (x86)\ownCloud>owncloud.exe --logdir c:\oclog`

I wonder why you would are making an option, document an option but apparently not test this option on windows though many people use windows for their sync client.

PS Why is the version of the client is now written in a picture that you can't copy paste out of?

![image](https://user-images.githubusercontent.com/24212810/49287953-95807000-f49f-11e8-85ef-7e10cdb3add7.png)

**Comment by voroyam** [comment]
![2](https://user-images.githubusercontent.com/24212810/49359496-b54da900-f6d6-11e8-8caa-f8316459241d.PNG)

![3](https://user-images.githubusercontent.com/24212810/49359501-b8489980-f6d6-11e8-9133-a618b6793612.PNG)

**Comment by ogoffart** [comment]
Ah, I see...
The problem is that the option  "Log-Dateien dauerhaft sichern" is checked.
This option override the log directory and saves the log in a different directory.  You can hover over this option to see in which directories the log are saved.  

Disable this option, then restart the client,  and the --logdir option should work again.

**Comment by guruz** [comment]
Can we make both work at same time?

**Comment by ogoffart** [comment]
With https://github.com/owncloud/client/pull/6912 we make sure that --logdir overwrite takes precedence over that checkbox.

> Can we make both work at same time?

That would mean making two stream, while the logger currently has one.
I don't think it is worth it for a purely debugging option

**Comment by voroyam** [comment]
> Ah, I see...
> The problem is that the option "Log-Dateien dauerhaft sichern" is checked.
> This option override the log directory and saves the log in a different directory. You can hover over this option to see in which directories the log are saved.
> 
> Disable this option, then restart the client, and the --logdir option should work again.

this is the solution. thanks
