### ISSUE TITLE
GPG Error: Key Expired [Ubuntu 16.04]  

### ISSUE THREAD

**Issue by repsorp** [owncloud/client#6920]
Hi,

Ubuntu 16.04 > sudo apt update returns following error message:

W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04  Release: The following signatures were invalid: KEYEXPIRED 1543957762
W: Failed to fetch http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/Release.gpg  The following signatures were invalid: KEYEXPIRED 1543957762
W: Some index files failed to download. They have been ignored, or old ones used instead.

**Comment by michaelstingl** [comment]
Couldn't reproduce using the install instructions linked from https://owncloud.org/download/#owncloud-desktop-client-linux

```
docker run --rm -ti ubuntu:16.04
```

```
root@b24699850c97:/# owncloudcmd -v
ownCloud version 2.5.1 (build 10450)
Git revision d1e6fd700210c3f6502507065d59248e47bf8362
Using Qt 5.10.1, built against Qt 5.10.1
Using 'OpenSSL 1.0.2g  1 Mar 2016'
root@b24699850c97:/# history 
    1  apt update && apt install wget -y && apt install apt-transport-https sudo -y
    2  wget -nv https://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_16.04/Release.key -O Release.key
    3  sudo apt-key add - < Release.key
    4  sudo apt-get update
    5  sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/ /' > /etc/apt/sources.list.d/isv:ownCloud:desktop.list"
    6  sudo apt-get update
    7  sudo apt-get install owncloud-client
    8  owncloudcmd -v
    9  history
```

**Comment by repsorp** [comment]
It's working now
Thanks
