### ISSUE TITLE
Remember previous installation directory when upgrading to a new version

### ISSUE THREAD

**Issue by abudden** [owncloud/client#6924]
### Expected behaviour
When upgrading, installer should default to the folder in which ownCloud's client was previously installed

### Actual behaviour
Installer always defaults to C:\Program Files (x86)\ownCloud.  I have to manually tell it where it was installed last time every time a new version is released.

### Steps to reproduce
1.  Install ownCloud client in a non-standard folder (e.g. c:\applications\sync\ownCloud)
2. Wait for a new version to be released and the prompt pops up notifying about the new version
3. Download the installer for the new version and run it - it defaults to the wrong folder.

### Client configuration
Client version: in the process of upgrading to 2.5.1

Operating system: Windows 10

OS language: English (UK)

Installation path of client: c:\applications\sync\owncloud

**Comment by michaelstingl** [comment]
@dschmidt Is something that can be done with the *.MSI? I think especially in the case of auto-update it would be handy to not need to pick the install location again…

**Comment by dschmidt** [comment]
Msi should handle this correctly already. The auto update to 2.5.x does handle this in particular

**Comment by michaelstingl** [comment]
@abudden What was the version you used before the upgrade?

**Comment by abudden** [comment]
@michaelstingl I'm afraid I don't know for certain, although it might have been 2.4.1.

**Comment by TheOneRing** [comment]
@dschmidt I think we fixed that one for 2.6.x?

**Comment by dschmidt** [comment]
It was indeed broken and should have been fixed for 2.6.x yes.
