### ISSUE TITLE
Owncloud resyncs moved folders

### ISSUE THREAD

**Issue by Che66** [owncloud/client#6931]
### Expected behaviour
When I move a folder locally in owncloud (e.g. from "Projects" to "Closed Projects", owncloud client deletes the server copy and re-uploads the folder to the new location. 

Can we investigate if we can prevent this from happening?

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system: Debian 9

Web server:  Apache2

Database: MariaDB

PHP version: Last one

ownCloud version: 10.0.10 (stable)

Storage backend (external storage): No

### Client configuration
Client version: Last one

Operating system: Windows 10

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
> owncloud client deletes the server copy and re-uploads the folder to the new location.

Are you sure this is inside the SAME sync folder configured of the SAME account in client?

> Client version: Last one

Please state the exact version.

**Comment by ckamm** [comment]
Possibly fixed with the db-error detection fix for 2.5.4. Please reopen if this happens with that or a newer version or you have more information.
