### ISSUE TITLE
New folders should have vfs support available by default

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6932]
Currently new folders have no vfs support enabled unless it's explicitly switched on during folder creation. That means one needs to edit the config file to enable it later.

- New folders should default to the best availabe vfs mode, but with the root folder starting out "available locally". Or Vfs::Off should migrate to the best available vfs mode once the first item is unpinned by the user?
- There should be a way to move between vfs modes?
- What does this mean for selective sync?

@michaelstingl fyi

**Comment by ckamm** [comment]
Suggestions: @michaelstingl 
1. New folders start out with the best available vfs mode and the root as AvailableLocally by default.
2. The wizard vfs setting just changes the root folder pin state to OnlineOnly instead.
3. If any vfs mode is enabled (independent of pin state), selective sync is disabled.
4. Old accounts without vfs enabled continue like that by default.
5. Old accounts with suffix-vfs enabled are attempted to be migrated to better-vfs and stay suffix-vfs if it doesn't work.
6. There's an option to switch on vfs for existing accounts where it's disabled.
7. There probably should be an option to switch between vfs modes, in particular to off, so users can use selective sync again. Even though we might want to gradually deprecate selective sync.

**Comment by ckamm** [comment]
Speaking about selective sync: It'd make sense if features such as "don't automatically sync external storages" or "don't automatically sync folders with >100MB of contents" were available in the vfs world too.

**Comment by ckamm** [comment]
PR #6954 already implements 3, 4, 5, 6, 7 (off only).
I don't think the remaining 1,2,8 should be done while vfs is considered experimental. @michaelstingl

**Comment by TheOneRing** [comment]
Fixed in https://github.com/owncloud/client/pull/8019
