### ISSUE TITLE
Progress reporting shows incorrect amounts with vfs

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6933]
The progress reporting isn't aware that files will not actually be downloaded and shows progress as if downloads are happening.

@hodyroff Thanks for testing!

**Comment by HanaGemela** [comment]
@ckamm could you please specify what are the steps to test this issue? Also what is the expected result

**Comment by ckamm** [comment]
@HanaGemela Enable VFS. Have a online-only folder. Add a file there on the server, say one with 100 MB. When the file is propagated by a sync (via creation of a local placeholder) the progress indicator shouldn't pretend it downloads 100 MB.

This is also noticable during initial sync.

**Comment by HanaGemela** [comment]
# Tested 
Tested with 2.6.0-daily20190426 (build 11674)
Progress bar doesn’t show that it's downloading the actual 100 MB file

**Comment by HanaGemela** [comment]
Also tested on Windows with 2.6.0daily20190425 (build 11620). The above was macOS
