### ISSUE TITLE
Data loss in vfs/selective sync interaction

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6936]
See https://github.com/owncloud/enterprise/issues/3065 written up by @jnweiger:

> Windows desktop client 2.5.1. User wants to explore the experimental VFS featue. His client is connected to cloud.owncloud.com, and he uses selective sync to hide parts of the tree. Several GB of data are synced to his local disk.
>
> Now
> - he disables more folders to reduce his local disk usage.
> - Without waiting, he immediately switches the account to virtual files.
> 
> DATA LOSS: The client now removes the newly disabled folders from his local storage and also on the server.

**Comment by ckamm** [comment]
I'd target this for 2.6.0 since there are large differences in vfs support between 2.5.1 and that and 2.5 vfs support was experimental to start with. If it ends up being easy to backport we can do that, but let's do the cost-benefit analysis of that after the primary fix is done.

**Comment by ckamm** [comment]
This relates to the general choice of how to switch between vfs modes and what to do about selective sync in #6932. A simple "bugfix" for 2.5.x could be to remove the ability to enable vfs mode for existing folders.

**Comment by ckamm** [comment]
This is still a problem with PR #6954: The user can trigger a vfs on/off switch while the folder is syncing. That should be prohibited.

**Comment by ckamm** [comment]
I can't prevent bad things from happening if the user deletes files instead of waiting - but the sync client is more careful about the vfs on/off switch now.

**Comment by HanaGemela** [comment]
1. Turn on VFS (wait until it's done) 
2. Turn off VFS
3. Immediately (when the sync is in progress) deselect all folders in the selective sync and confirm

This triggers 'All files were deleted on the server' message. User can select 'Keep all' so no data loss on the server but the message should not be shown.
After selecting 'Keep all':

1. Checkboxes in the selective sync list are not checked
2. Large (1G) files are missing in the file system (but present on the server) as they didn't manage to be downloading after switching off VFS
3. There are no icons against the files even thought the account is connected to the server (I can't recreate this one)

macOS 10.14.5, client 2.6.0alpha2 (build 12128)

**Comment by HanaGemela** [comment]
Apart from point 2 (Large files missing) I think it is not related to this issue. They seem to be issues with selective sync. Do you want me to raise it separately or will you fix everything here?

**Comment by ckamm** [comment]
I think this new issue is different from the original one. This one relates to terminating the sync run that happens when vfs is switched off. When vfs is switched off:
- ItemTypeVirtualFile entries are deleted from the database
- virtual files are deleted from the filesystem
- a full remote discovery is requested

What's notably absent is a full local discovery request. Adding that should ensure that the client doesn't mistakenly believe files are present when they aren't.

**Comment by HanaGemela** [comment]
@ckamm big file still missing on the client 2.6.0beta1 (build 12261), macOS 10.14.6

**Comment by ckamm** [comment]
@HanaGemela I'm having trouble finishing with the selective ui while the sync after "disable vfs" is still in progress. How do you make sure it doesn't finish quickly? Since it doesn't need to download or upload any files it finishes near instantly for me.

**Comment by ckamm** [comment]
What I've tried:
- turn on vfs, wait
- dehydrate some large files
- turn off vfs and...
- while it's running uncheck (some) selective sync settings, hit apply

But in this scenario the large files are downloaded and present in a follow-up sync.

**Comment by HanaGemela** [comment]
@ckamm try:
1. Make sure you have one single folder with one large file (1G) 
2. Turn on VFS 
3. Free up local space against that single folder
4. Turn off VFS
5. Immediately unselect the folder from the selective sync list and hit apply
6. Click 'Keep files'

**Comment by HanaGemela** [comment]
@ckamm I'm a bit confused right now. Running the scenario above it seems that this behaviour is as expected. Maybe it would be better to try once https://github.com/owncloud/client/issues/7337 is fixed...
Anyway if you try with a folder with two files - large and small one. The large one will disappear and the small one will stay. Either both should be deleted or both should stay

**Comment by ckamm** [comment]
@HanaGemela What's happening is this:
- After turning off vfs, the small and large file are being downloaded. The small one has finished, the large one is in progress.
- Deselecting the folder in selective sync terminates the sync run and marks the small file for deletion in the next run.
- The next run notices everything will be deleted and asks the user if this is right.
- Choosing "keep" cancels the deletion. That means the small file in the selective sync excluded folder will stay around, but be ignored.

I think this is pretty much correct. It's just a combination of complicated actions that makes the result somewhat confusing.

I do agree about #7337 - it would be nicer if the "all files deleted" warning dialog didn't come up when it's a selective-sync based deletion. Changing that would make this situation less confusing too: The folder and the contained small file would be deleted.

**Comment by HanaGemela** [comment]
@ckamm Thank you for your explanation. I'm closing the issue
