### ISSUE TITLE
[Bug] Owncloud Client Timeout

### ISSUE THREAD

**Issue by WeissmanGmbH** [owncloud/client#6937]
### Fun Fact
using WinSCP doenst give any of the issues. All folders or Files are shown. It consumes 2 minutes of course but it works like a charm.

### Expected behaviour
No Timeout

### Actual behaviour
Timeout hits

### Steps to reproduce
1. Connect Owncloud to cifs share and use LDAP authentication
2. change the generel section in testpilotcloud.cfg, adding "timeout=6000"
3. open Owncloud Testpilot Client and try to access folders/files or even expand the folder structures

Client Behavior
![image](https://user-images.githubusercontent.com/46027719/50332628-034e1380-0503-11e9-9818-53b14ba49909.png)

Client Version
![image](https://user-images.githubusercontent.com/46027719/50331771-2a571600-0500-11e9-9921-174ad7854b77.png)

### Server configuration
Operating system:

Web server: 
root@wcie-oc:~# dpkg -l | grep apache
ii  apache2                               2.4.29-1ubuntu4.5                     amd64        Apache HTTP Server
ii  apache2-bin                           2.4.29-1ubuntu4.5                     amd64        Apache HTTP Server (modules and other binary files)
ii  apache2-data                          2.4.29-1ubuntu4.5                     all          Apache HTTP Server (common files)
ii  apache2-utils                         2.4.29-1ubuntu4.5                     amd64        Apache HTTP Server (utility programs for web servers)
ii  libapache2-mod-php7.2                 7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        server-side, HTML-embedded scripting language (Apache 2 module)

Database:
root@wcie-oc:~# dpkg -l | grep sql
ii  libaprutil1-dbd-sqlite3:amd64         1.6.1-2                               amd64        Apache Portable Runtime Utility Library - SQLite3 Driver
ii  libsqlite3-0:amd64                    3.22.0-1                              amd64        SQLite 3 shared library
ii  mysql-client-5.7                      5.7.24-0ubuntu0.18.04.1               amd64        MySQL database client binaries
ii  mysql-client-core-5.7                 5.7.24-0ubuntu0.18.04.1               amd64        MySQL database core client binaries
ii  mysql-common                          5.8+1.0.4                             all          MySQL database common files, e.g. /etc/mysql/my.cnf
ii  mysql-server                          5.7.24-0ubuntu0.18.04.1               all          MySQL database server (metapackage depending on the latest version)
ii  mysql-server-5.7                      5.7.24-0ubuntu0.18.04.1               amd64        MySQL database server binaries and system database setup
ii  mysql-server-core-5.7                 5.7.24-0ubuntu0.18.04.1               amd64        MySQL database server binaries
ii  php7.2-mysql                          7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        MySQL module for PHP

PHP version:
root@wcie-oc:~# dpkg -l | grep php
ii  libapache2-mod-php7.2                 7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        server-side, HTML-embedded scripting language (Apache 2 module)
ii  php-common                            2:68+ubuntu18.04.1+deb.sury.org+1     all          Common files for PHP packages
ii  php-igbinary                          2.0.7-1+ubuntu18.04.1+deb.sury.org+10 amd64        igbinary PHP serializer
ii  php-imagick                           3.4.3-4+ubuntu18.04.1+deb.sury.org+1  amd64        Provides a wrapper to the ImageMagick library
ii  php-redis                             4.1.1-1+ubuntu18.04.1+deb.sury.org+10 amd64        PHP extension for interfacing with Redis
ii  php-smbclient                         0.9.0-3+ubuntu18.04.1+deb.sury.org+10 amd64        PHP wrapper for libsmbclient
ii  php7.2-bz2                            7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        bzip2 module for PHP
ii  php7.2-cli                            7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        command-line interpreter for the PHP scripting language
ii  php7.2-common                         7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        documentation, examples and common module for PHP
ii  php7.2-curl                           7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        CURL module for PHP
ii  php7.2-gd                             7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        GD module for PHP
ii  php7.2-intl                           7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        Internationalisation module for PHP
ii  php7.2-json                           7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        JSON module for PHP
ii  php7.2-ldap                           7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        LDAP module for PHP
ii  php7.2-mbstring                       7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        MBSTRING module for PHP
ii  php7.2-mysql                          7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        MySQL module for PHP
ii  php7.2-opcache                        7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        Zend OpCache module for PHP
ii  php7.2-readline                       7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        readline module for PHP
ii  php7.2-xml                            7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        DOM, SimpleXML, WDDX, XML, and XSL module for PHP
ii  php7.2-zip                            7.2.12-1+ubuntu18.04.1+deb.sury.org+1 amd64        Zip module for PHP

ownCloud version:
![image](https://user-images.githubusercontent.com/46027719/50332687-37c1cf80-0503-11e9-8968-a2facd40eb3b.png)

Storage backend (external storage):
cifs with ldap

### Client configuration
Client version: different kinds of versions. 2.6.0daily201812051 build 10917 for example
We used a bunch of stable and test versions on Windows and Mac systems.

Operating system: Ubuntu Sever 18 LTS

OS language: english

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
![image](https://user-images.githubusercontent.com/46027719/50331628-99803a80-04ff-11e9-816c-0a4b4ac78e27.png)

2. Web server error log:
==> /var/log/apache2/error.log <==
[Fri Dec 21 06:25:01.727569 2018] [mpm_prefork:notice] [pid 16953] AH00163: Apache/2.4.29 (Ubuntu) configured -- resuming normal operations
[Fri Dec 21 06:25:01.727601 2018] [core:notice] [pid 16953] AH00094: Command line: '/usr/sbin/apache2'

3. Server logfile: ownCloud log (data/owncloud.log):
==> /var/www/owncloud/data/owncloud.log <==
{"reqId":"J8azfdOSVNkQPoNFzk9w","level":3,"time":"2018-12-21T08:15:05+01:00","remoteAddr":"","user":"--","app":"user_ldap","method":"--","url":"--","message":"No or empty name for cn=schreibgesch\u00fctzte dom\u00e4nencontroller,cn=users,dc=wcie,dc=local."}
{"reqId":"J8azfdOSVNkQPoNFzk9w","level":3,"time":"2018-12-21T08:15:05+01:00","remoteAddr":"","user":"--","app":"user_ldap","method":"--","url":"--","message":"No or empty name for cn=schema-admins,cn=users,dc=wcie,dc=local."}

4. Redis
==> /var/log/redis/redis-server.log <==
4659:M 21 Dec 08:07:12.099 * 10 changes in 300 seconds. Saving...
4659:M 21 Dec 08:07:12.099 * Background saving started by pid 11184
11184:C 21 Dec 08:07:12.108 * DB saved on disk
11184:C 21 Dec 08:07:12.108 * RDB: 0 MB of memory used by copy-on-write
4659:M 21 Dec 08:07:12.200 * Background saving terminated with success

**Comment by michaelstingl** [comment]
@WeissmanGmbH Please check the failed request in the client log. You'll find a `X-REQUEST-ID` next to it. The same `X-REQUEST-ID` should help you find related entries in the `owncloud.log` from the server.

The lines in the `owncloud.log` you posted don't look like client requests.

**Comment by WeissmanGmbH** [comment]
[client.log](https://github.com/owncloud/client/files/2702294/client.log)
[owncloud.log](https://github.com/owncloud/client/files/2702295/owncloud.log)

@michaelstingl The Loglevel was set to "everything" but i cannot find the ID strings.

**Comment by ogoffart** [comment]
Relevant part of the log:

client:

```
12-21 10:31:53:492 [ info sync.networkjob ]:	OCC::LsColJob created for "http://owncloud.weissman.de" + "/01 Weissman & Cie. Deutschland/02 Projekte/Projekte/01 Alte Projekte/" "OCC::FolderStatusModel"
...
12-21 10:32:53:563 [ warning sync.networkjob ]:	Network job timeout QUrl("http://owncloud.weissman.de/remote.php/dav/files/mm/01 Weissman & Cie. Deutschland/02 Projekte/Projekte/01 Alte Projekte/")
```

Server corresponding for this file:

```
{"reqId":"0a2a26e9-9627-4eee-b41e-c4951821b4d5","level":0,"time":"2018-12-21T10:31:53+01:00","remoteAddr":"10.0.11.203","user":"mm","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/mm\/01%20Weissman%20&%20Cie.%20Deutschland\/02%20Projekte\/Projekte\/01%20Alte%20Projekte\/","message":"updating token 71, last check is now 1545384673"}
{"reqId":"0a2a26e9-9627-4eee-b41e-c4951821b4d5","level":0,"time":"2018-12-21T10:31:53+01:00","remoteAddr":"10.0.11.203","user":"mm","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/mm\/01%20Weissman%20&%20Cie.%20Deutschland\/02%20Projekte\/Projekte\/01%20Alte%20Projekte\/","message":"token 630796776e5b14a5430311a4f23d2b59debf159c4d774df3fdbfbebb0ab580510cb0ae228c8309c2c28f061f62da19bd8f18ff5e1599119e3fafa1d10d88513b does not exist"}
```

I can't really see the problem. But it seems to me that the client is behaving correctly and that there is indeed a timeout on the server.
So this issue should be moved to the server ( @PVince81  )

**Comment by WeissmanGmbH** [comment]
bump

are there any news? We are really lost and need to get this issue fixed. I was even thinking to change the apache to nginx just to make sure it isn't apache issue at all.

So what's your suggestion?

**Comment by michaelstingl** [comment]
@WeissmanGmbH There's nothing that can be fixed in the ownCloud desktop sync client.

Check here for more help:
https://owncloud.org/help/

**Comment by WeissmanGmbH** [comment]
we have checked again and the new version of the client doesnt show up this error anymore. so looks like it has been fixed soemhow.
Issue solved. Tanks for all the support :+1:
