### ISSUE TITLE
Simple folder rename is deleting/resyncing 160GB

### ISSUE THREAD

**Issue by igormcoelho** [owncloud/client#6944]
### Expected behaviour
I renamed a folder with 160GB and it should happen quickly.

### Actual behaviour
After the rename, it's resyncing everything! It will take more than 10 days :'(

### Steps to reproduce
1. Rename a folder with a lot of stuff
2. 
3. 

### Server configuration
Operating system: Deepin Linux (debian-based) - Desktop OwnCloud 2.5.0

Web server: 10.0.9

Database: mysql

PHP version: php5

ownCloud version: 10.0.9

Storage backend (external storage): mysql

### Client configuration
Client version: 2.5.0

Operating system: Deepin Linux

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 

Client package (From ownCloud or distro) (Linux only): owncloud 2.5.0 build 10213

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by ogoffart** [comment]
Renaming a folder should indeed happen quickly.
If the folder is indeed detected as just a rename, it is just one rename operation. This is tested and works well.
If it does not for you that might be a bug. But we need more information to know what triggered the bug because it works fine on our test setup.

Could you elaborate a bit more on the step to reproduce. Are you renaming a directory on the server, or on the client? Is there anything special about this directory.
Could you provide maybe the logfile when this happens.

Please also upgrade to 2.5.1

**Comment by igormcoelho** [comment]
Ok, it's probably my fault. I'm trying to rename again, to see if it will resync again the 160GB, then I inform here xD
I uploaded these files directly on the server, to be faster, then I ran the `occ` command to index them on server. I already had them in local folder on desktop ownCloud, so I expected no sync at all. So, after a few time I renamed the folder, and it started to sync, so perhaps it's a side effect of uploading files directly to server.
Do you know if it's supposed to download the files after uploading to server, even if I put them in the same folder locally before sync?

**Comment by igormcoelho** [comment]
Strange, tried again, and it's re-downloading 127GB after rename :'(
It's very strange because many files appeared as "Moved", and suddently, it started sending others. In the same folder, half files was "moved" and the other half was "sent".

Now, my desktop client is version 2.4.1... I had downgraded for other tests, don't know if it affects the situation.

**Comment by igormcoelho** [comment]
I think that's complicated to give logs, because these are actually my wife's private data. On Deepin I'm having difficulty to keep-up with top 2.5.1 version (it's currently 2.5.0, but nearly impossible to upgrade due to dependencies). Worse part is that nautilus-owncloud plugin is on 2.4.1... which makes it hard for you guys to debug, because it's such an old version.
So, perhaps I'll close this PR, and reopen as soon as I manage to get top version. It could be something already fixed. Thanks a lot for the advices!

**Comment by michaelstingl** [comment]
@igormcoelho Please open a new issue about the nautilus-owncloud plugin and dependency/upgrade  problems. Maybe @lazawan could have a look next week…
