### ISSUE TITLE
nautilus-owncloud plugin is currently old (on Deepin)

### ISSUE THREAD

**Issue by igormcoelho** [owncloud/client#6946]
I'm experiencing dependency problems on Deepin (Debian/Ubuntu based), which are the following:
- owncloud desktop 2.5.0 installs fine (using opensuse repo)
- nautilus-owncloud, however, depends on <= 2.4.1, so I cannot have it together with my desktop sync (my solution was to downgrade owncloud desktop sync too)
- I could not install 2.5.1 on deepin due to many dependency issues (on Qt for example). Perhaps this is a problem with deepin, but owncloud desktop dependencies looks very "bleeding-edge", because even latest released ubuntu does not have them I think (only 19.04 perhaps), so it's hard for regular users to use them.

Perhaps neither of it is a owncloud problem, but I heard @lazawan could perhaps help :)

Thanks!

**Comment by michaelstingl** [comment]
@igormcoelho Thanks for opening the issue. What is the Debian version you tested?

**Comment by igormcoelho** [comment]
I've tried on Deepin 15.8: https://www.deepin.org/en/
Deepin is debian-based, but it's not debian or ubuntu itself... many people don't know it yet, but it's really beautiful (I changed from debian -> ubuntu -> deepin).
I usually install rare packages using latest ubuntu repo, and it's always compatible, so my problem was to install 2.5.1. For 2.4.0 I used Ubuntu 18.04 repo, I'll try again with Debian 9.0 and report back.

**Comment by igormcoelho** [comment]
Ok, now I managed to install 2.5.1, using Debian 9 repository \o/
However, natilus-owncloud is still broken:
```
apt install nautilus-owncloud 
[sudo] senha para imcoelho: 
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
Alguns pacotes não puderam ser instalados. Isto pode significar que
você solicitou uma situação impossível ou, se você está usando a
distribuição instável, que alguns pacotes requeridos não foram
criados ainda ou foram retirados da "Incoming".
A informação a seguir pode ajudar a resolver a situação:

Os pacotes a seguir têm dependências desencontradas:
 nautilus-owncloud : Depende: owncloud-client (< 2.4.1+dfsg-1.1.1~) mas 2.5.1.10973+oc-10450 está para ser instalado
E: Impossível corrigir problemas, você manteve (hold) pacotes quebrados.
```

**Comment by michaelstingl** [comment]
Thanks for the details. We'll try to check the file manager extensions…

**Comment by ho4ho** [comment]
@igormcoelho @michaelstingl 

``nautilus-owncloud`` wrong name, correct ``owncloud-client-nautilus``:

http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0/all/

**Comment by igormcoelho** [comment]
Ohh, this is very, very strange... when I removed `owncloud-client-data` (`#apt-get remove owncloud-client-data`) the option to install `owncloud-client-nautilus` finally appeared!
Now it's working, thanks a lot @ho4ho @michaelstingl  :)
