### ISSUE TITLE
windows client gives file could not be located

### ISSUE THREAD

**Issue by sachinbanugariya** [owncloud/client#6948]
hello,

getting error "fillename" could not be located issue and sync stopped in owncloud windows desktop client.

file which gives erros is in shared folder from another people,
but that file is also seems in owncloud web, still that gives error.

please let me know how can i fix this.
thanks

**Comment by michaelstingl** [comment]
@sachinbanugariya Please answer the questions from the template as good as possible:
https://raw.githubusercontent.com/owncloud/client/master/.github/issue_template.md

With that little information, it's impossible to help you.

**Comment by sachinbanugariya** [comment]
### Expected behaviour
Tell us what should happen
windows client getting "file could not be located" and showing red x icon and stopped syncing.
file which not found is already there in owncloud website just gives issue at client side anyhow.
and the file which gives error is in shared folder by other people.

### Actual behaviour
Tell us what happens instead
ofcourse if error in one file then just not sync that file only instead of whole syncing broken.

### Steps to reproduce
1. dont know why this error happens.

### Server configuration
Operating system: centos

Web server: nginx

Database: mysql

PHP version: php-7.2

ownCloud version: 10

Storage backend (external storage):

### Client configuration
Client version: 2.5.1

Operating system: windows

OS language: english

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: 

### Logs

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:
seems not any error related this.

3. Server logfile: ownCloud log (data/owncloud.log):
not getting any error.

**Comment by TheOneRing** [comment]
Can't reproduce.
