### ISSUE TITLE
[Linux] Moving/copying new folder only syncs one level deep 

### ISSUE THREAD

**Issue by packi** [owncloud/client#6949]
### Expected behaviour
When copying a folder into a synced folder the whole folder structure should get synced.  

### Actual behaviour
Only the first two levels of the folder get synced. Anything else won't end up on the server. When touching a file deeper in the structure, some of the structure gets synced, although not recursively.

### Steps to reproduce
1. Given the following folder structure:
```
the_user@the_user-to-go:~$ tree test/
test/
├── 1
│   ├── 1
│   │   └── foo.txt
│   ├── 2
│   │   └── foo.txt
│   └── foo.txt
├── 2
│   ├── 1
│   │   └── foo.txt
│   ├── 2
│   │   └── foo.txt
│   └── foo.txt
└── foo.txt

6 directories, 7 files
the_user@the_user-to-go:~$
```
2. Move or copy to a synced folder using `mv test ~/Owncloud/`
3. Wait for sync to happen. It actually terminates after only syncing `test`, `test/1`, `test/2` and `test/foo.txt`

Script to create folder structure: https://gist.github.com/packi/1361912055bd03490bbb6a8906d9800e

### Server configuration

Self-signed certificate on a non-default port.

Operating system: Debian Stretch

Web server: Apache/2.4.25 (Debian)

Database: Ver 15.1 Distrib 10.1.37-MariaDB, for debian-linux-gnu (x86_64)

PHP version: PHP 7.0.33-0+deb9u1 (cli)

ownCloud version: Nextcloud 15.0.0

Storage backend (external storage): -

### Client configuration
Client version: b37cbe

Operating system: Ubuntu (Kubuntu) 18.10

OS language: en

Qt version used by client package (Linux only, see also Settings dialog): Qt 5.11.0

Client package (From ownCloud or distro) (Linux only): -

Installation path of client: /home/the_user/Downloads/...

### Logs
1. Client logfile: https://gist.github.com/packi/6700c8adb4f3f60f3f4fc214f197edd1

2. Web server error log: https://gist.github.com/packi/50e1b7f2bb7f1b8542948c22f360184c

3. Server logfile: no errors showing up, haven't enabled debug logging there

**Comment by guruz** [comment]
@packi Since you are using Nextcloud client, you should report to https://github.com/nextcloud/desktop/issues
Please try with the ownCloud client which is known to be more robust https://github.com/owncloud/client/releases/tag/v2.5.1 .. if you get the same problem, we can re-open.
