### ISSUE TITLE
owncloud-client version 2.5.1 installation on Ubuntu 16.04 LTS aborts with Error ,which is caused by missing owncloud-client-l10n

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#6950]
Hi ,
installtion of owncloud-client version 2.5.1 aborted on fresh installed Ubuntu 16.04 LTS with Error message .
Error is caused by missing library named owncloud-client-l10n 
Error is as following : 
![screenshot from 2019-01-07 14-27-20](https://user-images.githubusercontent.com/44814084/50770684-6f14d800-1288-11e9-89ae-c052a1f91018.png)

steps to reproduce are as following :  
install ubuntu 16.04 LTS
install owncloud-client 2.5.1 by following instructions on owncloud.org web page

**Comment by michaelstingl** [comment]
I performed a quick test using a Docker container:

```
docker run --rm -ti ubuntu:16.04
```

I followed the instructions linked here:
https://owncloud.org/download/#owncloud-desktop-client-linux

```
root@786f1ac2b5ff:/# owncloudcmd --version
ownCloud version 2.5.1 (build 10450)
Git revision d1e6fd700210c3f6502507065d59248e47bf8362
Using Qt 5.10.1, built against Qt 5.10.1
Using 'OpenSSL 1.0.2g  1 Mar 2016'
root@786f1ac2b5ff:/# history
    1  apt update && apt install wget -y && apt install apt-transport-https sudo -y
    2  wget -nv https://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_16.04/Release.key -O Release.key
    3  sudo apt-key add - < Release.key
    4  sudo apt-get update
    5  sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/ /' > /etc/apt/sources.list.d/isv:ownCloud:desktop.list"
    6  sudo apt-get update
    7  sudo apt-get install owncloud-client
    8  owncloudcmd --version
    9  history
```

Could you post your steps before executing `sudo apt-get install owncloud-client` ?

**Comment by lazawan** [comment]
@michaelstingl  sure ! 
i used these instructions from owncloud.org  : 
wget -nv https://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_16.04/Release.key -O Release.key
sudo apt-key add - < Release.key
sudo apt-get update

sudo sh -c "echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_16.04/ /' > /etc/apt/sources.list.d/isv:ownCloud:desktop.list"
sudo apt-get update
sudo apt-get install owncloud-client

**Comment by ho4ho** [comment]
Different priorities?

``apt-cache policy owncloud-client owncloud-client-l10n``

**Comment by lazawan** [comment]
it turned out after testing ,it works fine and that problem isn't reproducible
and here we close this Issue 
thanks for efforts
