### ISSUE TITLE
Client as proxy server (new feature)

### ISSUE THREAD

**Issue by EstebanSalpeter** [owncloud/client#6952]
### Expected behaviour
As most dispositive are often in the same LAN, it would really be more efficient that a client with a synced version of the files would act as a server for another client with an older version of the same files. 
The syncing operation would be much more efficient, by replacing WAN traffic with LAN traffic. 
Thanks!

**Comment by michaelstingl** [comment]
@EstebanSalpeter duplicate for https://github.com/owncloud/client/issues/230 ?

**Comment by EstebanSalpeter** [comment]
oh, you're right, sorry, I should have read it before opening this issue. thanks for the indication, I'll read it and see if I can contribute in some way. this one can be closed then.
