### ISSUE TITLE
Selective sync lists aren't guaranteed to be sorted

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6958]
I somehow ended up with a selective sync blacklist that runs into `Q_ASSERT(std::is_sorted(list.begin(), list.end()));` in discoveryphase.cpp. The lists should be actively sorted at the start of the discovery phase.

**Comment by HanaGemela** [comment]
@ckamm is this something I can test? If so, please provide the steps and the expected result

**Comment by ckamm** [comment]
No, this was a crash resulting from an internal error that's hard to reproduce without all the detail knowledge.
