### ISSUE TITLE
Documentation for owncloudcmd  seems to be wrong 

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#6964]
Hi there , 
i have just tried to use owncloudcmd on 2.5.1 client on Linux machine but there is no Documentation for this version yet
and i have followed the instructions for the 2.3 version from https://doc.owncloud.org/desktop/2.3/owncloudcmd.1.html and it seems to be wrong

according to instructions ,i have to type 
owncloudcmd  $HOME/media/music  https://server/owncloud/remote.php/webdav/Music
 it doesn't work

but actually i have to do only
 
owncloudcmd  $HOME/sync-folder  https://server
it works

**Comment by ChrisEdS** [comment]
It depends on the used server. You can go to you Web-UI und check your WebDAV link here: 

![image](https://user-images.githubusercontent.com/33026403/50982801-49910400-14fe-11e9-9efe-42bb2de9adc7.png)

But maybe i did not get the problem.

**Comment by lazawan** [comment]
@Csherm i have just tried what you suggested but it didn't work 

![screenshot from 2019-01-10 17-44-00](https://user-images.githubusercontent.com/44814084/50983272-709c0580-14ff-11e9-9913-98ce16864697.png)

![screenshot from 2019-01-10 17-44-40](https://user-images.githubusercontent.com/44814084/50983285-7691e680-14ff-11e9-90b7-bea6ada5ebee.png)
