### ISSUE TITLE
win build fails

### ISSUE THREAD

**Issue by gfvh** [owncloud/client#6967]
fetched from master

I followed https://doc.owncloud.org/desktop/2.5/building.html instructions 
fails with result:

> 
> PS C:\Users\Administrator\client-build> cmake -G "MinGW Makefiles" -DNO_SHIBBOLETH=1 C:\Users\Administrator\client
> -- Build of crashreporter disabled.
> -- GIT_SHA1 e87660ba28c95fe2462d58f901b8d2492521c57d
> -- Could NOT find INOTIFY (missing: INOTIFY_INCLUDE_DIR INOTIFY_LIBRARY_DIR)
> -- Could NOT find Sphinx (missing: SPHINX_EXECUTABLE)
> -- Could NOT find PdfLatex (missing: PDFLATEX_EXECUTABLE)
> -- Using Qt 5.12.0 (C:/Qt/Qt5.12.0/5.12.0/mingw73_64/bin/qmake.exe)
> -- Using own sqlite3 from C:/Users/Administrator/client/src/3rdparty/sqlite3
> -- Using own sqlite3 from C:/Users/Administrator/client/src/3rdparty/sqlite3
> -- Added vfsPlugin without tests: suffix
> -- Could NOT find Png2Ico (missing: Png2Ico_EXECUTABLE)
> -- Could NOT find IcoTool (missing: IcoTool_EXECUTABLE)
> CMake Warning at cmake/modules/ECMAddAppIcon.cmake:272 (message):
> Unable to find the png2ico or icotool utilities or icons in matching sizes
> - application will not have an application icon!
> Call Stack (most recent call first):
> src/gui/CMakeLists.txt:221 (ecm_add_app_icon)
> 
> 
> -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
> -- Configuring done
> CMake Error at src/libsync/CMakeLists.txt:124 (add_library):
> Cannot find source file:
> 
> ../3rdparty/zsync/c/librcksum/hash.c
> 
> Tried extensions .c .C .c++ .cc .cpp .cxx .cu .m .M .mm .h .hh .h++ .hm
> .hpp .hxx .in .txx
> 
> 
> CMake Error at src/libsync/CMakeLists.txt:124 (add_library):
> No SOURCES given to target: owncloudsync
>

**Comment by michaelstingl** [comment]
Please check this conversation about Win builds:
https://central.owncloud.org/t/building-owncloud-client-on-windows-10/17730

**Comment by gfvh** [comment]
@dschmidt thank you for helping. that solved this issue. now i can move on
