### ISSUE TITLE
HTTP2: Check if we need to update Qt

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6968]
...to at least v5.11.0

Found via https://central.owncloud.org/t/headers-on-invalid-stream-owncloud-10/16765/4

**Comment by dschmidt** [comment]
I'm about to update Qt to 5.12 for master/2.6 builds on macOS and would do the same for Windows afterwards. 

Linux needs to be discussed with @jnweiger

**Comment by ckamm** [comment]
@guruz I'd want to avoid touching our dependencies for 2.5.2 unless there's a critical bug. Would prefer making HTTP2 opt-in over a Qt update. Even if the update is necessary, releasing 2.5.2 *now* and then a 2.5.3 as soon as the Qt update is done may be better. I'm worried it might cost a month.

**Comment by dschmidt** [comment]
I didn't notice the 2.5.x milestone. As I wrote I was talking of 2.6.
For patch releases I would only bump Qt to a newer patch release as well, if there's no really strong reason to do otherwise.

**Comment by guruz** [comment]
> , releasing 2.5.2 now and then a 2.5.3 as soon as the Qt update is done may be better.

+1

**Comment by jnweiger** [comment]
Timelinewise: I should start pushing qt-5.12 into obs, right after client 2.5.2 is done. Correct?

**Comment by guruz** [comment]
Moved to 2.5.3 as per https://github.com/owncloud/client/issues/7009#issuecomment-458943550

**Comment by jnweiger** [comment]
Linux done for 2.6.daily, https://gitlab.com/ownclouders/client-linux-tests/pipelines/45977768
Bringing qt-5.12.1 to 2.5.4 should be trivial now.

**Comment by ckamm** [comment]
I'm not sure I'm reading this right, but I think the linux 2.5.4 builds use Qt 5.10.1 (looking at client-linux-obs/421) and the windows 2.5.4 builds use Qt 5.11.2 (looking at client-win32-msvc/11329). #7050

**Comment by jnweiger** [comment]
2.5.4 still builds with qt5.10.1 today. I am changing the config now for 2.5.4 to link with qt-5.12.1 instead.

**Comment by guruz** [comment]
That said, HTTP2 was disabled due to bugs in Qt :-/

https://github.com/owncloud/client/pull/7053#issuecomment-468153843

**Comment by guruz** [comment]
Moving to 2.5-next (which is 2.5.5)

**Comment by guruz** [comment]
When https://codereview.qt-project.org/#/c/254111/ is merged, Qt can send ProtocolFailure (and Http2WasUsed) so we could have some some retry logic at least..

**Comment by ckamm** [comment]
Using Qt 5.12.4 for 2.5 would have the advantage of users being able to test HTTP2 support with the release. I suggest not enabling HTTP2 support by default though since I'm not at all confident we wouldn't just discover another issue. I've enabled HTTP2-with-Qt5.12.4 for 2.6 though.

Let's close this and track the Qt dependency version for 2.5.5 in #7092.
