### ISSUE TITLE
Instructions to build binaries

### ISSUE THREAD

**Issue by thalst** [owncloud/client#6970]
Hello.

I`m trying to build the windows installer of owncloud desktop client. When cross-compiling from OpenSUSE with the command:

`docker run -v "$PWD:/home/user/client" owncloud-client-win32:2.5 \
   /home/user/client/admin/win/docker/build.sh client/  $(id -u)`

And I get:

Docker: Error response from daemon: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"/home/user/client/admin/win/docker/build.sh\": stat /home/user/client/admin/win/docker/build.sh: no such file or directory": unknown.

I can`t figure out what am I doing wrong. Can anyone help me?

**Comment by guruz** [comment]
This is an issue tracker. For build support, pleasey try https://central.owncloud.org/c/desktop

PS: Make sure /home/user/client/ is the ownCloud client source code.
