### ISSUE TITLE
Aborts during discovery don't lead to finished() signal

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#6972]
When a sync is aborted while it's still in the discovery phase, SyncEngine just cleans up with `        _discoveryPhase.take()->deleteLater();` and I don't think it ever causes the sync to finish.

(Tested by invoking `DiscoveryPhase::finished()` with a 10s delay in `DiscoveryPhase::startJob()` - likely an artifact of this setup. But I also don't see how it'd work otherwise since no one emits the SyncEngine's finished() signal?)

@ogoffart

**Comment by ckamm** [comment]
Hopefully addressed by #6973

**Comment by HanaGemela** [comment]
@ckamm how do you abort the sync? Could you provide the steps to test and the expected result?

**Comment by ckamm** [comment]
@HanaGemela When I tested I added custom code to do the abort. Things that abort syncs:
- enabling/disabling vfs support
- pausing a folder
- force sync on another folder
- implicitly hydrating a vfs file

**Comment by lazawan** [comment]
@ckamm how can we check if we are sill in the discovery phase or how could we slow down the discovery phase ?

**Comment by ckamm** [comment]
@lazawan To delay discovery:
- Most conveniently, apply this patch to add a 5s delay between each directory listing server request:
```
--- a/src/libsync/discoveryphase.cpp
+++ b/src/libsync/discoveryphase.cpp
@@ -253,7 +253,7 @@ void DiscoverySingleDirectoryJob::start()
         this, &DiscoverySingleDirectoryJob::directoryListingIteratedSlot);
     QObject::connect(lsColJob, &LsColJob::finishedWithError, this, &DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot);
     QObject::connect(lsColJob, &LsColJob::finishedWithoutError, this, &DiscoverySingleDirectoryJob::lsJobFinishedWithoutErrorSlot);
-    lsColJob->start();
+    QTimer::singleShot(5000, lsColJob, [=]() { lsColJob->start(); });
 
     _lsColJob = lsColJob;
 }
```

- Use ctrl-f6 while having a folder selected to request a full remote rediscovery
- Have very many subfolders on the server

To know whether discovery is still running, look for "Checking for changes in ..." messages in the sync progress ui.

**Comment by HanaGemela** [comment]
Steps to recreate:
1) Pause the sync when "Checking for changes in ..."  message is shown
2) Resume the sync
Actual result: The message says Aborted and Synchronizing at the same time
![image](https://user-images.githubusercontent.com/49001702/62209667-7faeac00-b39a-11e9-94b8-6e5cb1342746.png)

@ckamm could you described what should I see? When I abort when "Checking for changes in ..."  message is shown, the sync is aborted. Then I resume the sync, is says waiting, then  "Checking for changes in ..."  and then it's done

**Comment by ckamm** [comment]
@HanaGemela This problem is resolved if the "Checking for changes in..." message doesn't stay visible permanently after a sync is aborted.

I'll see about reproducing the Synchronizing+Aborted issue you point to.

**Comment by ckamm** [comment]
@HanaGemela I've moved the aborted+syncing to a separate issue.

**Comment by HanaGemela** [comment]
Works as expected on macOS 10.14.6, client 2.6.0.12234260alpha2+6972
