### ISSUE TITLE
Confusing behaviour when right click "About"

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/client#6974]
A right-click on "About" shows me "Copy link location" 

![image](https://user-images.githubusercontent.com/33026403/51121417-b0246380-1817-11e9-986c-efc9cb9f7d33.png)

### Expected behaviour
In my opinion, the `version` of the client should be copied to the clipboard. This is useful. Especially because the text cannot be selected.

### Actual behaviour
The word "about" is copied to the clipboard. This makes no sense.

### Client configuration
Client version:
2.5.2

**Comment by ckamm** [comment]
Trivial to fix, will put in 2.5 branch.

**Comment by ChrisEdS** [comment]
Copies now the `version`. (2.5.2rc2 (build 11135)
