### ISSUE TITLE
2.5.2 release

### ISSUE THREAD

**Issue by guruz** [owncloud/client#6975]
Some weeks before the release:
* [x] Check if we should update the bundled sqlite3 (https://github.com/owncloud/client/tree/master/src/3rdparty/sqlite3)
* [x] Check if we should update Sparkle on build machine (https://github.com/sparkle-project/Sparkle/releases)
* [x] Ensure NSIS is up to date on the build machine
* [ ] Ensure up-to-date dependencies (e.g. [latest Qt version](http://qt-project.org/downloads#qt-lib) is installed on the machine and picked up (cmake output)
* [x] Ensure the crash reporter server is up
* [x] Check crash reporter for bad crashes
* [x] Ensure Windows Overlay DLLs are rebuilt. Why? How?
* [x] Check daily builds are up and running, that is Jenkins.int jobs client-linux, client-osx and client-win32-msvc, client-win32--msvc-msi all green.
* [x] Ensure Linux daily builds are built too for all distros https://build.opensuse.org/package/show/isv:ownCloud:desktop:daily:2.X/owncloud-client
* [x] Build branded clients through the scripting machine and smoke test one or two branded clients (especially with predefined url)
* [x] Upload a daily build of the windows version to virustotal.com
  * Contact AV vendors whom's engine reports a virus
* [ ] Documentation should be online before the release http://doc.owncloud.org/desktop/2.X/
* [x] QA goes over https://github.com/owncloud/client/wiki/Testing-Scenarios
* [x] Make sure to have `client/ChangeLog` updated
 * use `git log --format=oneline v<lastrelease>...master` if your memory fails you
* [x] check if enterprise issues are fixed

**rc1**:
* [x] Add last updates to Changelog in the client source repository.
* [x] Branch off a release branch called VERSION-rcX or VERSION-betaX  (without v, v is for tags)
* [x] Edit ```VERSION.cmake``` to set the suffix to beta1, beta2 etc. Commit the result to the release branch only
* [x] Make sure to increase the version number of the branched of release, e.g. if you release 2.3.2 then you should change VERSION.cmake in 2.3 to 2.3.3 since that branch now will be 2.3.3
* [x] Create build for theme 'ownCloud' using client-trigger (uncheck the "daily build" checkbox, use rcX or betaX dropdown for version suffix)
* [x] Create build for theme 'testpilotcloud' using client-trigger (uncheck the "daily build" checkbox, use the rcX or betaX dropdown for version suffix)
* Build results are in https://download.owncloud.com/desktop/testing -- win and mac binaries are there, linux packages are listed in a *repo.html file.
* [x] Check if *tar.xz.asc files are there. If not resort to https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge
* [x] Mac: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Win: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Smoke test of one distro package (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Run https://jenkins.int.owncloud.com/job/client-linux-tests/ with REPO_URL=https://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/testing
* [x] Linux: add/remove build targets in isv:ownCloud:Qt5101 and isv:ownCloud:desktop:testing to match the list of supported platforms and announced(!) deprecations. Keep in sync with https://doc.owncloud.org/server/latest/admin_manual/installation/system_requirements.html#desktop
* [ ] Create a signed tag using ```git tag -u E94E7B37 tagname``` (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [ ] update the wordpress content at owncloud.org/download (Attention: No staging!)
* [ ] Inform packagers @dragotin (openSUSE), @hefee (Debian), ??? (Fedora)
* [ ] Announce on https://central.owncloud.org
* [ ] Inform community mailinglists devel@owncloud.org and testpilots@owncloud.org (make sure to mention it is an rc). Link to the central post so discussion happens there.
* [ ] Check crash reporter

**rc2:**
* [x] Add last updates to Changelog in the client source repository.
* [x] Branch off a release branch called VERSION-rcX or VERSION-betaX  (without v, v is for tags)
* [x] Edit ```VERSION.cmake``` to set the suffix to beta1, beta2 etc. Commit the result to the release branch only
* [x] Make sure to increase the version number of the branched of release, e.g. if you release 2.3.2 then you should change VERSION.cmake in 2.3 to 2.3.3 since that branch now will be 2.3.3
* [x] Create build for theme 'ownCloud' using client-trigger (uncheck the "daily build" checkbox, use rcX or betaX dropdown for version suffix)
* [x] Create build for theme 'testpilotcloud' using client-trigger (uncheck the "daily build" checkbox, use the rcX or betaX dropdown for version suffix)
* Build results are in https://download.owncloud.com/desktop/testing -- win and mac binaries are there, linux packages are listed in a *repo.html file.
* [x] Check if *tar.xz.asc files are there. If not resort to https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge
* [x] Mac: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Win: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Smoke test of one distro package (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Run https://jenkins.int.owncloud.com/job/client-linux-tests/ with REPO_URL=https://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/testing
* [x] Linux: add/remove build targets in isv:ownCloud:Qt5101 and isv:ownCloud:desktop:testing to match the list of supported platforms and announced(!) deprecations. Keep in sync with https://doc.owncloud.org/server/latest/admin_manual/installation/system_requirements.html#desktop
* [x] Create a signed tag using ```git tag -u E94E7B37 tagname``` (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [ ] update the wordpress content at owncloud.org/download (Attention: No staging!)
* [x] Inform packagers @dragotin (openSUSE), @hefee (Debian), ??? (Fedora)
* [ ] Announce on https://central.owncloud.org
* [x] Inform community mailinglists devel@owncloud.org and testpilots@owncloud.org (make sure to mention it is an rc). Link to the central post so discussion happens there.
* [x] Check crash reporter

One week before the final release:
* [x] Communicate the release schedule on mailinglist release-coordination@owncloud.com. Give a high level overview of the upcoming new features, changes etc.
* [ ] Ensure marketing is aware (marketing@owncloud.com) and prepared for the release (social, .com website, cust.communications)
* [ ] Inform GCX knows the next version is about 1 week out (gcx@owncloud.com)

Day before final Release:
* [ ] Check the translations coming from transifex: All synchronized? (20181109jw: where? how?)
* [ ] Run the tx.pl scripts on the final code tag (20181109jw: really? What does that test?)
* [ ] Run ```make test```
* [ ] Run smashbox (20180719 jw: FIXME: add details, how?)
* [ ] Inform product management and marketing that we are 1 day out

On Release Day (for final release):
* [x] Add last updates to Changelog in the client source repository.
* [x] Branch off a release branch called VERSION  (without v, v is for tags)
* [x] Edit ```VERSION.cmake``` to set the suffix to "" etc. Commit the result to the release branch only
* [x] Create build for theme 'ownCloud' using client-trigger (uncheck the "daily build" checkbox, use the proper dropdown for version suffix)
* [x] Create build for theme 'testpilotcloud' using client-trigger (uncheck the "daily build" checkbox, use the proper dropdown for version suffix)
* Build results are in https://download.owncloud.com/desktop/testing -- win and mac binaries are there, linux packages are listed in a *repo.html file. 
* [x] Check if *tar.xz.asc files are there. If not resort to https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge
* [x] Branch isv:ownCloud:desktop to isv:ownCloud:desktop:client-X.Y.Z using https://github.com/owncloud/administration/blob/master/jenkins/obs_integration/ (the Linux packages will always land in the :testing repository)
  ```obs-deepcopy-prj.sh isv:ownCloud:desktop isv:ownCloud:desktop:client-2.5.1```
* [x] Re-download Mac builds and check signature. Interactive in installer window
* [x] Re-download Win build check signature. From Mac or Linux: ```osslsigncode verify ownCloud-version-setup.exe```
* [x] Mac: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Win: Perform smoke test (Install, make sure it does not explode, and check if all version indicators are correct)
* [ ] Linux: Smoke test of one distro package (Install, make sure it does not explode, and check if all version indicators are correct)
* [x] Linux: Run https://jenkins.int.owncloud.com/job/client-linux-tests/ with REPO_URL=https://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/testing
* [x] Win/Mac Copy builds from ```testing``` to ```stable``` on download.owncloud.com, double check the download links. (make sure the .asc is there too)
* [x] Linux: disable publishing on project isv:ownCloud:desktop
* [x] Linux: copy from testing to released in OBS:
  ```obs-deepcopy-prj.sh isv:ownCloud:desktop:testing isv:ownCloud:desktop```
  ```obs-deepcopy-prj.sh isv:ownCloud:testpilot:testing isv:ownCloud:testpilot```
* [ ] Linux: Re-enable OBS publishing on the project after official release date and if all distros build (check for accidentially disabled packages too) 
* [ ] Linux: Wait until everything is built and published, then disable publishing on project isv:ownCloud:desktop
* [x] Create git signed tag in client repository using ```git tag -u E94E7B37 tagname``` (https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)
* [x] Create a (draft) release on https://github.com/owncloud/client/releases
* [x] Update https://owncloud.org/changelog/desktop-client/
* [x] Update https://owncloud.org/download/#owncloud-desktop-client -> Download ownCloud -> click open 'Desktop Client', edit win/mac/lin, each all three tabs "Production", "Technical Preview" [disabled], "Test pilot" enabled, edit the links.
* [x] Announce on https://central.owncloud.org
* [ ] Announce on announcements@owncloud.org Link to the central post so discussion happens there.
* [x] Inform packagers @dragotin (openSUSE) @hefee (Debian)
* [x] Send out Social (tweet, blog, other)
* [ ] Send out customer communication (if any)
* [ ] Inform GCX that the new version is released (gcx@owncloud.com)
* [ ] Inform release-coordination@owncloud.com
* [ ] Ensure marketing is aware (marketing@owncloud.com)
* [ ] Take pride and celebrate!
* [ ] Tell GCX to increment the minimum supported version for enterprise customers
* [ ] Check if minimum.supported.desktop.version (https://github.com/owncloud/core/blob/master/config/config.sample.php#L1152) needs to be updated in server

15 minutes after after release:
* [ ] Test all advertised download links to have the expected version
* [ ] Check for build errors in OBS, do
```obs-deepcopy-prj.sh isv:ownCloud:desktop isv:ownCloud:desktop:client-2.X.X```
* [ ] disable publishing in OBS to prevent that accidential rebuilds hit the end users.
* [ ] add the previous release to https://owncloud.org/download/older-versions/

A few days after the release (for final release)
* [ ] Review changes in the release branch, merge back into master
* [ ] check the crash reporter if auto update is a good idea or we need a new release
* [ ] Update the owncloud hosted updater according to https://github.com/owncloud/enterprise/blob/master/client_update_checker/README.md#deploy  
* [ ] Increment version number in daily builds. Special case: after the last release in a branch, jump forward to the 'next release branch'... That may mean, this is nightly is the same as edge then.

**Comment by jnweiger** [comment]
Known issue: https://doc.owncloud.org/desktop/2.5 renders without stylesheets.

**Comment by jnweiger** [comment]
daily linux build of 2.5 are building on all platforms. https://build.opensuse.org/package/show/isv:ownCloud:desktop:daily:2.5/owncloud-client -- any special features we should watch out for manual testing?

**Comment by jnweiger** [comment]
virustotal is happy with ownCloud-2.5.2.11314.11170-daily20190115.msi

**Comment by guruz** [comment]
rc2 is building.

**Comment by guruz** [comment]
> @DeepDiver1975 the last transifex commit in 2.5 was from mid december.

@DeepDiver1975 did you fix something there? Commits are coming again from transifex

**Comment by guruz** [comment]
> Known issue: https://doc.owncloud.org/desktop/2.5 renders without stylesheets.

This is still the case.
@settermjd @tboerger any idea?

**Comment by jnweiger** [comment]
SUSE obs still has several http vs https inconsistencies, making our test suite fail. added a docker/debian9.sh entry point to manually run one of the affected platforms. 
Heureka: https://gitlab.com/ownclouders/client-linux-tests/pipelines/43861863 succeeded with 252rc2

**Comment by guruz** [comment]
GitHub release published -> https://github.com/owncloud/client/releases/tag/v2.5.2-rc2

FYI @hefee @dragotin

**Comment by guruz** [comment]
Auto updater PR: https://github.com/owncloud/enterprise/pull/3099

**Comment by guruz** [comment]
@tboerger @jnweiger Is the testpilots@ mailing list broken? i didnt get a post confirmation yet
https://mailman.owncloud.org/pipermail/testpilots/

**Comment by jnweiger** [comment]
auto updater PR done. (no idea about broken mailing lists)

**Comment by tboerger** [comment]
> @tboerger @jnweiger Is the testpilots@ mailing list broken? i didnt get a post confirmation yet
> https://mailman.owncloud.org/pipermail/testpilots/

The MX record have been fixed in friday evening.

**Comment by jnweiger** [comment]
@guruz @michaelstingl  Good news
@lazawan and myself are done with testing of 252rc2. Results-overview: https://cloud.owncloud.com/index.php/s/Aws6TGySyRs12ks minor issues seen, okay to proceed.

**Comment by michaelstingl** [comment]
> @lazawan and myself are done with testing

Awesome – great job! Thanks a lot for your hard work!

**Comment by guruz** [comment]
Why does cloud.owncloud.com not have the text editor app installed? :p

**Comment by jnweiger** [comment]
https://gitlab.com/ownclouders/client-linux-tests/pipelines/44782144 succeeded with owncloud-client-2.5.2 final.

**Comment by guruz** [comment]
@jnweiger Can you move the following files (incl the *sig and *asc) from testing/ to stable/ ?

https://download.owncloud.com/desktop/testing/ownCloud-2.5.2.11383.11232.msi
https://download.owncloud.com/desktop/testing/ownCloud-2.5.2.11383.11232.en-US.msi
https://download.owncloud.com/desktop/testing/ownCloud-2.5.2.11198.pkg
https://download.owncloud.com/desktop/testing/owncloudclient-2.5.2.11325-rc1.tar.xz



https://download.owncloud.com/desktop/testing/testpilotcloud-2.5.2.11199.pkg
https://download.owncloud.com/desktop/testing/testpilotcloud-2.5.2.11384.11233.msi
https://download.owncloud.com/desktop/testing/testpilotcloud-2.5.2.11384.11233.en-US.msi

**Comment by jnweiger** [comment]
ownCloud-2.5.2.11325.11181-rc1.en-US.msi            owncloudclient-2.5.2.11325-rc1.tar.xz.asc  testpilotcloud-2.5.2.11384.11233.en-US.msi
ownCloud-2.5.2.11383.11232.en-US.msi                testpilotcloud-2.5.2.11199.pkg             testpilotcloud-2.5.2.11384.11233.msi
ownCloud-2.5.2.11383.11232.msi                      testpilotcloud-2.5.2.11199.pkg.sig         testpilotcloud-client-2.5.2.11384.269.linux-repo.html
owncloud-client-2.5.2.11325.217rc1.linux-repo.html  testpilotcloud-2.5.2.11199.pkg.tbz         testpilotcloudclient-2.5.2.11384.tar.xz
owncloudclient-2.5.2.11325-rc1.tar.xz               testpilotcloud-2.5.2.11199.pkg.tbz.sig     testpilotcloudclient-2.5.2.11384.tar.xz.asc

copied to stable.

**Comment by jnweiger** [comment]
The wordpress page at https://owncloud.org/download now has 2.5.2 for all platforms.

**Comment by michaelstingl** [comment]
@jnweiger could you also link the single-language *.MSI for GPO-deployments? (see https://owncloud.com/download/#desktop-clients )

**Comment by jnweiger** [comment]
Added https://owncloud.com/download/#desktop-clients  to the release checklist. TODO: find credentials.

**Comment by jnweiger** [comment]
Update the updater: https://github.com/owncloud/enterprise/pull/3112
Please someone find the typo, then merge :-)

**Comment by guruz** [comment]
https://owncloud.org/news/desktop-client-2-5-2-release-thanks-feedback/
https://central.owncloud.org/t/desktop-client-2-5-2-release/18166

**Comment by guruz** [comment]
2.5.3 -> https://github.com/owncloud/client/issues/7009

**Comment by jnweiger** [comment]
Done last year.
