### ISSUE TITLE
Selective sync folder size limit and external storage download setting don't apply to vfs

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#6980]
Hi there ,

i think there is a problem on all platforms with Virtualisation .
let's suppose , i limit the folder-sync-size to 4 megabyte and i have in the  folder a file, ,which is 5 megabyte
while account-creating on client ,i enable the virtualisation-file Feature 
now after sync , i have virtual files and folders 
in this moment i want to download the folder ,which contains at least a  file with 5 megabyte
in order to download it , right click on folder " in sync folder " owncloud-menu then download 
and all files will be downloaded without any check for the whole folderssize .

i know , it is so described " download all files " and in this case the folder-limit isn't took into account 

regards ,

**Comment by ckamm** [comment]
The download size limit and external storage download limit currently apply only to selective sync. It's plausible they could be generalized for vfs.

**Comment by TheOneRing** [comment]
We  clarified the wording for those settings, they don't make any sense with vfs.
