### ISSUE TITLE
Error : file can not be downloaded because of a local file name clash!

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#6981]
Hi there ,

sync-process aborted with Error-message file can not be downloaded because of a local file name clash!
Error occurred on macos 10.4 and owncloud-client has version 2.5.2 

steps to reproduce : 
- create on owncloud-server two files : -   ownCloud Manual.pdf
                                                         -    ownCloud ManuaL.pdf
-set up your owncloud client and while syncing ,we get this Error-message 

![screen shot 2019-01-17 at 11 58 58](https://user-images.githubusercontent.com/44814084/51314475-0c71c800-1a50-11e9-91b7-7706f3c77d44.png)

server doesn't have problem with the names but client .

**Comment by guruz** [comment]
https://www.google.com/search?client=firefox-b-ab&q=macos+file+system+case+insensitive =)

**Comment by lazawan** [comment]
@guruz ok , Macos system uses case-insensitive, that means ,it is ok 😉

**Comment by hannesa2** [comment]
> Macos filesystem uses case-insensitive, that means ,it is ok 😉.
> I can consider it as solved

My macOS Big Sur run into this error

I use` ownCloud 2.7.2 (build 2626) e52f9e Dec 2 2020 10:21:25`
