### ISSUE TITLE
[Windows] HTTP/2 protocol error since ownCloud client update to 2.5.x version

### ISSUE THREAD

**Issue by th3boz** [owncloud/client#6985]
Hello to everyone,
I open a new issue that is very similar to the issue #6843 “HTTP/2 protocol error since ownCloud client update”, but I see that is closed (I don’t know if this is the correct procedure).

I have the same problem reported in the issue #6843:

“Install ownCloud client 2.5.x on Windows (Win10 64-bit) or perform automatic upgrade from previous version.
Add a new server configuration
When finishing by pushing the “Connect…” button it fails saying “Error: HTTP/2 protocol error”
Downgrading to an older client version is a workaround for the problem.”

I tried to do

$ curl --head --http2 https://<my_server/

and the result is:

HTTP/2 200
date: Wed, 16 Jan 2019 23:13:38 GMT
server: Apache
last-modified: Thu, 03 Mar 2016 22:26:29 GMT
etag: "84-52d2c7d62ef40"
accept-ranges: bytes
content-length: 132
content-type: text/html

So.. my server seems to be configured correctly and works with the version 2.4.x of the client, but not with the version 2.5.x (also the lastest version available).

If the http/2 request is done with ALPN enabled, the curl result is the one reported above, while if it’is done with APLN disabled it does not work.

Application-Layer Protocol Negotiation requires a valid SSL certificate and TLSv1.2 or newer.. and the result reported above says that I have a correct SSL certificate.

Could this information be useful? Does the 2.5.x client version of ownCloud support HTTP/2 using APLN only? (all major browsers support HTTP/2 using ALPN only).

Could you please help me?

Thanks.
Andrea

PS: the server is hosted by a shared hosting provider, so I don’t have the server logs.

---

Expected behaviour

After installing ownCloud I should be able to add my server and connect to it.

Actual behaviour

The connection fails saying “HTTP/2 protocol error”. Client is not usable!

Steps to reproduce

Install ownCloud client 2.5.0 (build 10560) on Windows (Win10 64-bit) or perform automatic upgrade from previous version.
Add a new server configuration
When finishing by pushing the “Connect…” button it fails saying “Error: HTTP/2 protocol error”
Downgrading to an older client version (e.g. 2.4.3.10188) is a workaround for the problem.

Server configuration

owncloud version: 10.0.9
Operating system: Linux
Web server: Apache
Database: MySQL
PHP version: 7.2.11
Storage backend (external storage): local

Client configuration

Client version: 2.5.0.10560
Operating system: Windows 10, 64-bit
OS language: Italian
Installation path of client: Default

**Comment by michaelstingl** [comment]
@th3boz there was a question about the Qt version. Could you post this information from your 2.4.3 and 2.5.0 client? Same result with the 2.5.1?

**Comment by th3boz** [comment]
Hello @michaelatingl
Thanks for your replay.

Yes.. the problem occours with all 5.x versions (5.0, 5.1).

Do I have to provide more informations?

Thanks!!!

**Comment by ogoffart** [comment]
If you are willing to give me an account on your server, i can have a look at it.

**Comment by guruz** [comment]
If I understand @th3boz correctly, she/he could fix it by enabling ALPN in Apache?

(Note that in theory we could use QNetworkRequest::Http2DirectAttribute to avoid this, but I think this should be just done in server with ALPN)

**Comment by th3boz** [comment]
@guruz .. well.. I think that in the previous post I wrote something wrong, sorry. I can’t enable the APLN on the server because the hosting provider does not permit it. But I was thinking: if the problem is the APLN, why it does not occour with the previous version of ownCloud client? Right? Thanks!!

**Comment by th3boz** [comment]
@ogoffart I just sent to you via mail (I took it in your profile). Thank you vero much!!!

**Comment by ogoffart** [comment]
@th3boz The credentials did not work.

**Comment by guruz** [comment]
@th3boz @ogoffart Is there a conclusion on this issue?

**Comment by th3boz** [comment]
Sorry.. I did a restore of the DB and moved to another server, so I “solved” the problem.

Thanks very much to all!!

**Comment by guruz** [comment]
@th3boz great!

**Comment by guruz** [comment]
Has anyone seen issues with HTTP2 in 2.6.0 similar as in https://github.com/owncloud/client/issues/7610 ? Please comment there...
