### ISSUE TITLE
[Linux] trailing newline or carriage in filename are neither rejected nor handled correctly

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6987]
owncloud-client 2.5.2rc1 on Linux mint happily uploads files with trailing newline 0x0a or carriage return 0x0d to the owncloud server. The server web ui handles them, and replaces them with an _ when requesting a download via web.
owncloud-client 2.5.2rc1 on windows fails with error messages.
A trailing carriage return causes "Access denied" (very misleading)
A trailing newline causes "The filename, directory name, or volume label syntax is incorrect"

![image](https://user-images.githubusercontent.com/1108546/51325620-a136ee80-1a6d-11e9-91ad-5d17de09c35a.png)

**Comment by ogoffart** [comment]
You seem to describe a problem on the server rather than a problem on the client.

Btw, When I tried with the demo server, i get the error `File name contains at least one invalid character` which seems correct.

**Comment by ckamm** [comment]
I can reproduce the problem, "foo\n" uploads successfully (created with `touch $'foo\n'` in zsh). We could add `\x00-\x1F` to our invalid filename regex? Or just `\R`? Opinions? @jnweiger @ogoffart @guruz 

The current pattern is `[\\:?*"<>|]`

**Comment by guruz** [comment]
I'd say "Anything in the unicode control characters category" but I'm not an expert.

**Comment by ckamm** [comment]
We have two options here:
1) consider this invalid early, not even uploading these files
2) consider this invalid filenames for downloading to Windows systems

We currently do a mix of both. The pattern I mentioned above is for 1) but there are also some 2)-style filters (like windows reserved words).

For control characters I'd suggest 1) since they also not great to have on the server.

**Comment by guruz** [comment]
@jnweiger Please test with rc1

**Comment by jnweiger** [comment]
## tested 254rc1 on win10
 A trailing newline causes an entry as not synced with the message "The filename is a reserved name in this filesystem" -> green checkmark indicates a successful sync nevertheless ->
OK

A trailing carriage return causes the file to be ignored without entry in the not synced.
Renaming a "foo.txt" to "foo\r" on the server (via a different client) causes the windows client to simply delete the file locally.
 -> green checkmark indicates a successful sync nevertheless ->
BAD -> There should the same entry in the not synced tab as with a trailing.

**Comment by ckamm** [comment]
@jnweiger Nice catch, there files should definitely appear in the not-synced tab! It's very odd, because there's no distinction between \n and \r in the code. I'll try to reproduce.

**Comment by ckamm** [comment]
I'd say deleting the file locally when it is renamed to a non-representable name is expected behavior.
If I create "foo\n" and "bar\r" on the server both will show up in the not-synced tab for me.
If I rename "foo.txt" to "gone\r" I also see the file deletion and "gone" is listed in the not-synced tab.

@jnweiger Could you check again, maybe there's a particular situation that makes it not show up?

**Comment by jnweiger** [comment]
Retest with 260daily20190923

* upload with an Ubuntu 18.04 client:
  `mkdir xx\^M 'yy
'` sends both unchanged to the server.
* A windows 10 client does not download them. Proper message in the 'Not Synced' tab:
![image](https://user-images.githubusercontent.com/1108546/65447742-848e5a00-de37-11e9-883a-3b3d92e49af1.png)
* rename test with an Ubuntu 18.04 client:
 'mkdir aa bb; sleep 120; mv aa aa\^M; mv bb 'bb
'`
* A windows client first download empty folders aa and bb, then deletes them, adding proper messsages in the 'Not Synced' tab:
![image](https://user-images.githubusercontent.com/1108546/65448199-902e5080-de38-11e9-8ef6-e58d19a7954d.png)
![image](https://user-images.githubusercontent.com/1108546/65448238-a50ae400-de38-11e9-9141-e04402fcc5f1.png)

**Comment by jnweiger** [comment]
Looks fine to me. Thanks! Closing.

**Comment by jnweiger** [comment]
> I'd say "Anything in the unicode control characters category" but I'm not an expert.

Right! 
https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file says: 

> > Characters whose integer representations are in the range from 1 through 31, except for alternate data streams where these characters are allowed. For more information about file streams, see File Streams.
