### ISSUE TITLE
owncloud-client 2.5.2 on opensuse leap 15 still has problem with owncloud-icon

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#6988]
root has no problem with icon but the normal users have already 
left is root
Right is normal user

![screenshot from 2019-01-17 16-18-21](https://user-images.githubusercontent.com/44814084/51328550-ec540000-1a73-11e9-902d-f859c2a6baee.png)

**Comment by ogoffart** [comment]
That's expected:  left is using the "oxygen" style,  right is using the "breeze" style
You can see that both the folder icon, the sync icon, and the close icon adapt to the style.
