### ISSUE TITLE
owncloud-client 2.5.2 on Fedora 29 still has problem like 2.5.1 

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#6989]
Hi there , 

issue #6887 is still existing 

![screenshot from 2019-01-17 17-38-24](https://user-images.githubusercontent.com/44814084/51334182-9422fb00-1a7f-11e9-91c3-5f2e54e1e4a0.png)

**Comment by ogoffart** [comment]
Issue #6887 is still open, we did not find the cause of the problem. Please comment on that issue.
