### ISSUE TITLE
Wizzard: wrong german translation for "Ask for confirmation before synchronizing e&xternal storages"

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6990]
## tested 252rc2 on linux mint
The wizard when connecting a new connection has two possible issues
a) it inherits the default for maximum folder size(47MB in this case) from somewhere.
b) the line describing the external storage setup appears truncated at the end (Grenze: ...?)

![image](https://user-images.githubusercontent.com/1108546/51396698-e0357480-1b3f-11e9-91ad-fafa36ac448b.png)

Behaviour a) might be as expected. I don't know. Is this one global limit affecting all sync connections?
Behaviour b) might be a localization issue for german?

**Comment by ogoffart** [comment]
> a) it inherits the default for maximum folder size(47MB in this case) from somewhere.

There is only one global option for all accounts for that.  So changing this value changes the global options, and so it inherits this from the global option.
The other checkbox about the external folder is also a global option.

If you tell me that it does not make sens to have a global option there, i'd agree with you. But that's how we were told to do it.


> b) the line describing the external storage setup appears truncated at the end (Grenze: ...?)

That's a mistake in the german translation, the english text is `Ask for confirmation before synchronizing external storages` and does not have the concept of limit.

Please report or fix this porblem in transifex.

Note: the above string is composed of two strings: `Ask for confirmation before synchronizing folders larger than`  and then `MB`. For technical reasoin there must be two strings there.
The translator maybe did not realize these two string are related, and could use that to change the position of the box in the sentence. I'd suggest translations such as 
`Bestätigung erfragen, bevor Ordner größer als` and `MB synchronisiert werden`

**Comment by TheOneRing** [comment]
Is this still a thing?

**Comment by HanaGemela** [comment]
@TheOneRing Yes, tested with 2.6.3

**Comment by TheOneRing** [comment]
Just realised that the layout of the page is suboptimal.
I'll try to improve it first.

**Comment by TheOneRing** [comment]
![image](https://user-images.githubusercontent.com/200626/85712690-db87cf00-b6e8-11ea-9ade-df06d3eceaba.png)

**Comment by jnweiger** [comment]
Shortended the german translation to 61 chars. If that is still to much, allow resizing the window, enable line breaks, reduce font size. 
Hiding widgets is never correct.

**Comment by TheOneRing** [comment]
It was not about a long translation but a wrong one. The "Grenze:" is not part of the original string and makes no sense in that line.
