### ISSUE TITLE
three points on branded-client-GUI 2.5.2  on ubuntu and debian   are missing 

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#6996]
Hi ,

three points are missing in the user-interface on 2.5.2 branded-client 
i have tested for ubuntu 18.10 and 16.04  and debian 9

![screenshot from 2019-01-21 16-32-40](https://user-images.githubusercontent.com/44814084/51530427-343fa200-1e3b-11e9-8bec-815c92d9bef2.png)

**Comment by lazawan** [comment]
@dschmidt  i just updated my post , look up ;)

**Comment by michaelstingl** [comment]
Needs the SVG package. Maybe packaging issue… Compare installed packages with the ones from the unbranded client?

**Comment by dschmidt** [comment]
Huh? what about the last one in the list?

**Comment by lazawan** [comment]
@dschmidt he asked about if it is not there ,but it is there :P 
he thought , the package is missing

**Comment by guruz** [comment]
@lazawan There is also a SVG image plugin, can you check if that one is there?
On macOS is called like this, on Linux no idea about path or name, something with qsvg:
```
$ find /Applications/owncloud.app |grep -i svg
/Applications/owncloud.app/Contents/PlugIns/imageformats/libqsvg.dylib
```

**Comment by lazawan** [comment]
the package ocqt5101-qtsvg5 is already installed , we already checked  if it exists .

**Comment by guruz** [comment]
@lazawan What does that mean? do you have libqsvg (or whatever it is called) or not? :)

**Comment by lazawan** [comment]
@guruz yep ,we have it :--)

**Comment by guruz** [comment]
@lazawan Can you paste the directory listing of the directory with those image plugins?

**Comment by lazawan** [comment]
@guruz      find /opt/owncloud | grep -i svg  ,will deliver the same result ,what i did before ,however here it is the output 

![screenshot from 2019-02-04 13-47-15](https://user-images.githubusercontent.com/44814084/52209211-8349f600-2883-11e9-925d-05274bd0d0ba.png)

**Comment by lazawan** [comment]
sorry i removed the label accidentally :'(

**Comment by guruz** [comment]
@lazawan So the image plugin for SVG is missing.
We got those on macOS:
```
$ ls -l /Applications/owncloud.app/Contents/PlugIns/imageformats/
total 1088
-rwxr-xr-x  1 root  admin    59K Jan 30 01:31 libqgif.dylib
-rwxr-xr-x  1 root  admin    57K Jan 30 01:32 libqico.dylib
-rwxr-xr-x  1 root  admin   371K Jan 30 01:32 libqjpeg.dylib
-rwxr-xr-x  1 root  admin    52K Jan 30 01:32 libqsvg.dylib
```

**Comment by lazawan** [comment]
@guruz ok ,this problem is only on branded-client , i will install the normal owncloud-client and compare it with branded ,whether these images/plugin are missing or not and then let you know

**Comment by jnweiger** [comment]
daily master does not install /opt/ownCloud/qt-5.10.1/lib/x86_64-linux-gnu/qt5/plugins/imageformats/libqsvg.so on Ubuntu 18.04 -- neither with testpilotcloud-client, nor with owncloud.client. Strange.

**Comment by lazawan** [comment]
@jnweiger  @guruz  you are right , it looks so in normal owncloud-client 2.5.2 

![screenshot from 2019-02-04 14-36-18](https://user-images.githubusercontent.com/44814084/52211514-61a03d00-288a-11e9-9384-60438414ca80.png)

**Comment by jnweiger** [comment]
Sometimes the qtsvg package is not installed at all. I'll have to investigate...

**Comment by jnweiger** [comment]
the situation is a bit fuzzy, as when the svg package was installed before for another client, it will remain installed....

**Comment by jnweiger** [comment]
ocqt5101-qt5-qtsvg is miscompiled in internal obs. libqsvg.so was in the -dev package instead of in the main package. Arrgh.
-> Fixed.
internal buildservice is now recompiling the svg packages...

**Comment by lazawan** [comment]
i just tested it and  works fine , problem is solved :--)

**Comment by jnweiger** [comment]
Thanks testing!
