### ISSUE TITLE
macos 10.14, client 252rc2: double click on desktop icon does not open settings

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#6998]
macOS normally does not install a desktop icon. 
I am using finder to navigate to Applications, then drag the icon of the ownclod client to the desktop.

This desktop icon works well to start the client. A trayicon appears after one double click.
A second double click is expected to open the settings dialog. It does not.

**Comment by TheOneRing** [comment]
Possible duplicate of #7018

**Comment by michaelstingl** [comment]
> macOS normally does not install a desktop icon.

Desktop icon isn't a common thing on macOS.

> A second double click is expected to open the settings dialog. It does not.

Won't fix for now, see https://github.com/owncloud/client/issues/7018#issuecomment-626666764
