### ISSUE TITLE
2.5.2 rc2: Tarball does not contain docs-theme

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#7002]
When trying to update the openSUSE client package to 2.5.2 rc2 I found that building the docs fails with the following error:

```
[   81s] Theme error:
[   81s] no theme named u'owncloud_org' found (missing theme.conf?)
[   81s] 
[   81s] Theme error:
[   81s] no theme named u'owncloud_com' found (missing theme.conf?)
[   81s] make[2]: *** [doc/CMakeFiles/doc-html-org.dir/build.make:60: doc/CMakeFiles/doc-html-org] Error 2
```
In the 2.5.2 tarball, the directory `doc/docs-themes` is empty. The 2.5.1 tarball contains themes. Should these be restored for 2.5.2?

**Comment by dragotin** [comment]
I copied the docs-themes directory back to the 2.5.2 tarball and the packages build again. 

Do you want to resurrect the data in there?

**Comment by dragotin** [comment]
If you have python-Sphinx on your system (or the buildroot) the 2.5.2 tarball does not build. It fails with the error above.

**Comment by guruz** [comment]
```
guruz@mgmbp2018 owncloudclient-2.6.0.11419-daily20190201 $ ls doc/docs-themes/
README.md static    templates themes
..
guruz@mgmbp2018 owncloudclient-2.5.3.11417-daily20190201 $ ls doc/docs-themes/
README.md static    templates themes
```

-> Is that what you need @dragotin ?

**Comment by lazawan** [comment]
@dragotin could you provide please the steps to recreate ? thanks .
