### ISSUE TITLE
Truncated Text under Tab Icons

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#7003]
An image says it all:

![truncated_tabs](https://user-images.githubusercontent.com/1070214/51739033-cb516780-2090-11e9-95f5-02cfc4135b16.png)

That makes the information rather useless... 

It started with 2.5.0 or 2.5.1 (dunno...) and is also there in 2.5.2 on Linux Desktop (KDE).

**Comment by guruz** [comment]
That's with the distro's Qt right?
Which Qt version does the about dialog claim?

**Comment by ckamm** [comment]
For the account, we explicitly use Qt::ElideMiddle to shorten the display name to something that fits the tool button. But for the other three items we don't. There's no other use of ElideMiddle in our code that would do that. And grepping through Qt code I think there's no eliding going on by default for tool button labels either.

My guess would be that there's a custom style at work that decides to elide these labels? I don't think there's any setting we could use to avoid that.

**Comment by ogoffart** [comment]
I noticed that since i upgraded to Qt 5.12

**Comment by ckamm** [comment]
Ah, that was a good hint. It's b2a282d7c7b8f49819bbc86ed705980438ecb04b from QTBUG-64132. Note that there's a fix c879fc2ab7c5278f1a1f7727b011479a5baafc0c about avoiding unnecessary elision that's not yet in any release.

**Comment by ckamm** [comment]
Looks like it will be fixed in 5.12.1: https://bugreports.qt.io/browse/QTBUG-72226

**Comment by jnweiger** [comment]
Minor issue from my point of view, as the mouseover balloons still have the complete names.

Seen with 2.5.2 using qt-5.10.0 here:
![grafik](https://user-images.githubusercontent.com/1108546/51904141-2f8c6800-23be-11e9-8281-8f93c1e90b17.png)
Not as bad as it looks for Klaas, but also some unhelpful ellipsis there.

* 'cloud.owncloud.com' is shown in full, although lengthy.
* 'oc-fablab-nuernberg.de' gets an ellipsis to replace '-nu' with three dots. (not much saving, actually)
* 'cloud.damken.com' gets an ellipsis to save 4 letters, although 'damken' is shorter than 'owncloud'  

Strange logic anyway. We should try to avoid that.

**Comment by dragotin** [comment]
@ckamm s answer is great for me, if it is fixed in 5.12.1 I am fine. Closing this issue.

**Comment by guruz** [comment]
Let's QA this in case we switch to 5.12.1

**Comment by ogoffart** [comment]
With Qt 5.12.1 the  main tabs are fixed,  but there seem to be another problem with the account tabs

![screenshot_20190228_144143](https://user-images.githubusercontent.com/959326/53570567-1d414d80-3b67-11e9-94e0-15c746b9be0d.png)

**Comment by ckamm** [comment]
@ogoffart I'm pretty sure the elision in the account tabs is something the client does itself intentionally.

**Comment by ogoffart** [comment]
@ckamm  the client explicitly say it must be ellided, but the ellision is made by Qt.  The bug in 5.12 that is not fixed, is that the \n is ellided

**Comment by ckamm** [comment]
Ah, there are two layers of elision. We elide the host and the user ourselves in `shortDisplayNameForSettings()` but then Qt elides the whole thing too. Could we disable that?

**Comment by ogoffart** [comment]
This is probably fixed by 7024090e1dc7043e7a2a692ede105bcb7952781d in Qt 5.12.2

**Comment by guruz** [comment]
So this is actually not ReadyToTest?

**Comment by ckamm** [comment]
@guruz The awkward elision for the non-account buttons was fixed in Qt 5.12.1, but there's still incorrect elision for the account buttons which'll likely be fixed with Qt 5.12.2 as @ogoffart found out. So overall I'd say it's not ready to test.

**Comment by ogoffart** [comment]
Just tested with Qt 5.12.2, and it looks good now.
