### ISSUE TITLE
[Windows] Cannot open pinned OwnCloud folder or Recent Folder ownCloud folder from Windows taskbar Explorer right click menu while OwnCloud client is running

### ISSUE THREAD

**Issue by NoNaym** [owncloud/client#7004]
I like to right click on the pinned Windows Explorer icon that is on the Windows taskbar in order to open one of my pinned (or “Quick access”) folders. Recently I noticed that while the OwnCloud Windows client is running (on Windows 10), my primary owncloud folder (and any other folder inside) which I have pinned to Windows Explorer refuse to open when right clicking on the Window Explorer taskbar icon and then clicking on the applicable folder (i.e. owncloud folder or any folder within). Nothing happens at all. All other (non-owncloud) folders open without issue. If I kill the OwnCloud client, then right clicking the Windows Explorer taskbar icon and selecting one of my owncloud folders work (the folder opens in Windows Explorer normally)!

This leads me to believe that the problem is being caused by the Windows OwnCloud client, and not Windows itself. Has anybody else experienced this issue? Anybody know of a fix? And/or does the OwnCloud team have any plans on fixing this issue?

Client OS: Windows 10 Pro (x64)

Windows ownCloud client version: 2.5.1 (build 10807)

OS language: US English

Installation path of client: C:\Program Files (x86)\ownCloud

**Comment by guruz** [comment]
@NoNaym Would you say this is related to #6982 ?

**Comment by guruz** [comment]
@NoNaym Could you also run the client with logging, especially checking for the ```SocketAPI``` related messages?

**Comment by NoNaym** [comment]
Yes, I would say these issues are related. They sounds very similar.

**Comment by NoNaym** [comment]
I'll try to do this as soon as I can and will post the log shortly...

**Comment by MikeKnife** [comment]
I have an issue, that might be related to the one above.
It started when I switched from 
ownCloud-2.4.3.10188-setup.exe 
to 
ownCloud-2.5.0.10359-setup.exe.

I use to have only shortcuts of simple text files (program code) on the desktop. Right click and choose to open it with Scite (auto-it-editor) or with Ultra Edit Studio opens the file. (The entries for this come with the editors.)
Since the last owncloud version this function is gone, nothing happens. Clicking on the file itself instead of its shortcut still works though.
In my case deselect the option "Integration in den Windows Explorer" during install fixed the problem.

Mike Knife

**Comment by guruz** [comment]
Pinned folder:
```
02-04 13:08:05:051 [ info gui.socketapi ]:	New connection QLocalSocket(0x7110428)
02-04 13:08:05:051 [ info gui.socketapi ]:	Sending SocketAPI message --> "REGISTER_PATH:C:\\Users\\marku\\ownCloud_test" to QLocalSocket(0x7110428)
02-04 13:08:05:058 [ info gui.socketapi ]:	Received SocketAPI message <-- "GET_STRINGS:CONTEXT_MENU_TITLE" from QLocalSocket(0x7110428)
02-04 13:08:05:058 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_STRINGS:BEGIN" to QLocalSocket(0x7110428)
02-04 13:08:05:059 [ info gui.socketapi ]:	Sending SocketAPI message --> "STRING:CONTEXT_MENU_TITLE:ownCloud" to QLocalSocket(0x7110428)
02-04 13:08:05:059 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_STRINGS:END" to QLocalSocket(0x7110428)
02-04 13:08:05:059 [ info gui.socketapi ]:	Received SocketAPI message <-- "GET_MENU_ITEMS:C:\\Users\\marku\\ownCloud_test" from QLocalSocket(0x7110428)
02-04 13:08:05:059 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_MENU_ITEMS:BEGIN" to QLocalSocket(0x7110428)
02-04 13:08:05:060 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:SHARE:d:Teilen…" to QLocalSocket(0x7110428)
02-04 13:08:05:060 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:COPY_PUBLIC_LINK:d:Öffentlichen Link in die Zwischenablage kopieren" to QLocalSocket(0x7110428)
02-04 13:08:05:061 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:COPY_PRIVATE_LINK:d:Privater Link in die Zwischenablage kopiert" to QLocalSocket(0x7110428)
02-04 13:08:05:061 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:OPEN_PRIVATE_LINK:d:Im Browser öffnen" to QLocalSocket(0x7110428)
02-04 13:08:05:061 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_MENU_ITEMS:END" to QLocalSocket(0x7110428)
02-04 13:08:05:109 [ info gui.socketapi ]:	Lost connection  QLocalSocket(0x7110428)
02-04 13:08:05:173 [ info gui.socketapi ]:	New connection QLocalSocket(0x7110428)
02-04 13:08:05:173 [ info gui.socketapi ]:	Sending SocketAPI message --> "REGISTER_PATH:C:\\Users\\marku\\ownCloud_test" to QLocalSocket(0x7110428)
02-04 13:08:05:176 [ info gui.socketapi ]:	Lost connection  QLocalSocket(0x7110428)
02-04 13:08:05:177 [ info gui.socketapi ]:	Received SocketAPI message <-- "opennewwindow:C:\\Users\\marku\\ownCloud_test" from QLocalSocket(0x7110428)
02-04 13:08:05:177 [ warning gui.socketapi ]:	The command is not supported by this version of the client: "opennewwindow" with argument: "C:\\Users\\marku\\ownCloud_test"
```

**Comment by guruz** [comment]
Wow. I rebooted my Win10 machine (it asked for updates) and now it works. 
I don't get anything in the client log anymore and the Explorer folder just opens (for a pinned folder).

**Comment by guruz** [comment]
I don't find the word ```opennewwindow``` anywhere in our repository.
Seems to be a Windows thing though.

Why would this get sent as command over our SocketAPI? @ogoffart

**Comment by NoNaym** [comment]
Sorry for the lack of responses here, but I just had a quick chance to check logs, and Windows version. I am on Windows 10 Pro 1803 (build 17134.523), and just checked for updates (none available at the moment). Here is an owncloud client log after clicking on a pinned folder:

`02-04 07:46:48:042 [ info gui.socketapi ]:	New connection QLocalSocket(0xeb85ef0)
02-04 07:46:48:048 [ info gui.socketapi ]:	Sending SocketAPI message --> "REGISTER_PATH:D:\\Users\\Ryan\\ownCloud" to QLocalSocket(0xeb85ef0)
02-04 07:46:48:067 [ info gui.socketapi ]:	Received SocketAPI message <-- "GET_STRINGS:CONTEXT_MENU_TITLE" from QLocalSocket(0xeb85ef0)
02-04 07:46:48:068 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_STRINGS:BEGIN" to QLocalSocket(0xeb85ef0)
02-04 07:46:48:068 [ info gui.socketapi ]:	Sending SocketAPI message --> "STRING:CONTEXT_MENU_TITLE:ownCloud" to QLocalSocket(0xeb85ef0)
02-04 07:46:48:068 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_STRINGS:END" to QLocalSocket(0xeb85ef0)
02-04 07:46:48:068 [ info gui.socketapi ]:	Received SocketAPI message <-- "GET_MENU_ITEMS:D:\\Users\\Ryan\\ownCloud" from QLocalSocket(0xeb85ef0)
02-04 07:46:48:069 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_MENU_ITEMS:BEGIN" to QLocalSocket(0xeb85ef0)
02-04 07:46:48:183 [ info sync.database ]:	sqlite3 version "3.24.0"
02-04 07:46:48:183 [ info sync.database ]:	sqlite3 journal_mode= "wal"
02-04 07:46:48:189 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:SHARE:d:Share..." to QLocalSocket(0xeb85ef0)
02-04 07:46:48:189 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:COPY_PUBLIC_LINK:d:Copy public link to clipboard" to QLocalSocket(0xeb85ef0)
02-04 07:46:48:190 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:COPY_PRIVATE_LINK:d:Copy private link to clipboard" to QLocalSocket(0xeb85ef0)
02-04 07:46:48:190 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:OPEN_PRIVATE_LINK:d:Open in browser" to QLocalSocket(0xeb85ef0)
02-04 07:46:48:190 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_MENU_ITEMS:END" to QLocalSocket(0xeb85ef0)
02-04 07:46:48:220 [ info gui.socketapi ]:	Lost connection  QLocalSocket(0xeb85ef0)
02-04 07:46:48:344 [ info gui.socketapi ]:	New connection QLocalSocket(0x8afcf98)
02-04 07:46:48:344 [ info gui.socketapi ]:	Sending SocketAPI message --> "REGISTER_PATH:D:\\Users\\Ryan\\ownCloud" to QLocalSocket(0x8afcf98)
02-04 07:46:48:346 [ info gui.socketapi ]:	Lost connection  QLocalSocket(0x8afcf98)
02-04 07:46:48:346 [ info gui.socketapi ]:	Received SocketAPI message <-- "opennewwindow:D:\\Users\\Ryan\\ownCloud" from QLocalSocket(0x8afcf98)
02-04 07:46:48:347 [ warning gui.socketapi ]:	The command is not supported by this version of the client: "opennewwindow" with argument: "D:\\Users\\Ryan\\ownCloud"`

**Comment by guruz** [comment]
The ```opennewwindow``` is most probably coming from a second launched instance which then sends to first instance
```
            if (!app.sendMessage(QLatin1String("MSG_PARSEOPTIONS:") + msg))
                return -1;
```
We can fix/workaround this issue by implementing a new ```opennewwindow``` in the SocketAPI that uses QDesktopServices to open the Explorer.
Thanks for the logs.

**Comment by faramir** [comment]
_Comment from #6982 with the similar bug (but closed to consolidate bugs):_

winver says:
```
Windows 10, version 1809 (build 17763.292)
```

⚙ > System > About:
```
Version: Windows 10 Pro
Version: 1809
Build: 17763.292
```

No updates are available for my system. Checked it right now.

It seems that I have more recent version of Windows 10 installed.

The frequent items still not working.

Log:
```
02-05 08:40:58:746 [ info gui.socketapi ]:	New connection QLocalSocket(0x7cd4580)
02-05 08:40:58:746 [ info gui.socketapi ]:	Sending SocketAPI message --> "REGISTER_PATH:<owncloud-dir-path0>" to QLocalSocket(0x7cd4580)
02-05 08:40:58:746 [ info gui.socketapi ]:	Sending SocketAPI message --> "REGISTER_PATH:<owncloud-dir-path1>" to QLocalSocket(0x7cd4580)
02-05 08:40:58:746 [ info gui.socketapi ]:	Sending SocketAPI message --> "REGISTER_PATH:<owncloud-dir-path2>" to QLocalSocket(0x7cd4580)
02-05 08:40:58:762 [ info gui.socketapi ]:	Received SocketAPI message <-- "GET_STRINGS:CONTEXT_MENU_TITLE" from QLocalSocket(0x7cd4580)
02-05 08:40:58:762 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_STRINGS:BEGIN" to QLocalSocket(0x7cd4580)
02-05 08:40:58:762 [ info gui.socketapi ]:	Sending SocketAPI message --> "STRING:CONTEXT_MENU_TITLE:ownCloud" to QLocalSocket(0x7cd4580)
02-05 08:40:58:762 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_STRINGS:END" to QLocalSocket(0x7cd4580)
02-05 08:40:58:762 [ info gui.socketapi ]:	Received SocketAPI message <-- "GET_MENU_ITEMS:<owncloud-dir-path2>\\<frequent-dir-path>" from QLocalSocket(0x7cd4580)
02-05 08:40:58:762 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_MENU_ITEMS:BEGIN" to QLocalSocket(0x7cd4580)
02-05 08:40:58:762 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:SHARE::Udostępnij..." to QLocalSocket(0x7cd4580)
02-05 08:40:58:762 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:COPY_PUBLIC_LINK::Kopiuj link publiczny do schowka" to QLocalSocket(0x7cd4580)
02-05 08:40:58:762 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:COPY_PRIVATE_LINK::Kopiuj link prywatny do schowka" to QLocalSocket(0x7cd4580)
02-05 08:40:58:762 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:OPEN_PRIVATE_LINK::Otwórz w przeglądarce" to QLocalSocket(0x7cd4580)
02-05 08:40:58:762 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_MENU_ITEMS:END" to QLocalSocket(0x7cd4580)
02-05 08:40:58:817 [ info gui.socketapi ]:	Lost connection  QLocalSocket(0x7cd4580)
02-05 08:40:58:868 [ info gui.socketapi ]:	New connection QLocalSocket(0x7cd4690)
02-05 08:40:58:868 [ info gui.socketapi ]:	Sending SocketAPI message --> "REGISTER_PATH:<owncloud-dir-path0>" to QLocalSocket(0x7cd4690)
02-05 08:40:58:868 [ info gui.socketapi ]:	Sending SocketAPI message --> "REGISTER_PATH:<owncloud-dir-path1>" to QLocalSocket(0x7cd4690)
02-05 08:40:58:868 [ info gui.socketapi ]:	Sending SocketAPI message --> "REGISTER_PATH:<owncloud-dir-path2>" to QLocalSocket(0x7cd4690)
02-05 08:40:58:874 [ info gui.socketapi ]:	Lost connection  QLocalSocket(0x7cd4690)
02-05 08:40:58:874 [ info gui.socketapi ]:	Received SocketAPI message <-- "opennewwindow:<owncloud-dir-path2>\\<frequent-dir-path>" from QLocalSocket(0x7cd4690)
02-05 08:40:58:875 [ warning gui.socketapi ]:	The command is not supported by this version of the client: "opennewwindow" with argument: "<owncloud-dir-path2>\\<frequent-dir-path>"
```

**Comment by guruz** [comment]
@faramir thanks, cause already found. See my comment above for what ownCloud client needs to implement to workaround

**Comment by guruz** [comment]
Wow, see also https://github.com/owncloud/client/issues/7023
What else will come up?

**Comment by ckamm** [comment]
@guruz I don't see how that `app.sendMessage()` in a second instance would trigger a message being received on the socketapi socket? This sounds like a bug or behavior change in the explorer integration to me. I'm keeping it in 2.5.4 since it sounds serious.

**Comment by guruz** [comment]
Merged, you can test this with Friday's 2.5.4 daily build.
https://download.owncloud.com/desktop/daily/

**Comment by faramir** [comment]
Working for me using version ownCloud-2.5.4.11583.11403-daily20190305.
Work both for pinned and recently used items, and for copying file paths.

**Comment by ckamm** [comment]
@faramir Thanks for testing!

**Comment by jnweiger** [comment]
## tested with 2.5.4rc1 on win10
pinned a folder to quick access while the folder still shows the blue downloading icon.
pin the same folder to the explorer.
navigate elsewhere
click quick access entry. -> visit folder.  -> GOOD
close file browser.
right clock explorer icon, -> click pinned folder -> file broser opnes at the correct folder -> GOOD.
OK
