### ISSUE TITLE
Suggest improved filtering options for Activity tab

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7005]
I believe it is in general a good idea to view Activity details on a per account basis.
We already allow filtering for accounts in the 'Not Synced' tab. But we do not have such a filter for the other Activity tabs 'Server Activity' or 'Sync Protocol'. 
![grafik](https://user-images.githubusercontent.com/1108546/51905048-8135f200-23c0-11e9-93bd-5892a1b310bb.png)

I suggest to allow the existing filter for all Activities.

**Comment by NiceFeather** [comment]
This maybe is a need improved issue.

Currently, in the case of multiple accounts, I notice that "Not Synced" tab of "Activity" module, the "List of issues" could be filtered and displayed for different accounts, which is very good. In fact, the "Local sync protocol" list of "Sync Protocol" tab should be the same with that, in the case the synced contents can also be filtered and viewed by switching account.

**Comment by NiceFeather** [comment]
By the way, when will this improvement be put on the development schdule?

**Comment by michaelstingl** [comment]
> By the way, when will this improvement be put on the development schedule?

No ETA yet

**Comment by TheOneRing** [comment]
Done in 2.10
