### ISSUE TITLE
[Gnome 3] tray menu is constantly changing size

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7006]
## Client 2.5.2 on Ubuntu 18.10 wiht default gnome 3 desktop
The menue as it drops down from the icon bar constanly moves its entries left and right. 
https://www.youtube.com/watch?v=mGxefUQvPKs

This is a mere nuisance, but still distracting.

Maybe there is a simple fix for that to truncate long lines?

**Comment by TheOneRing** [comment]
I assume the issue to be resolved by time
