### ISSUE TITLE
[macOS] Icon changed in Finder but only with small icon display

### ISSUE THREAD

**Issue by guruz** [owncloud/client#7010]
Maybe this was fixed meanwhile though

![screen shot 2019-01-30 at 13 56 59](https://user-images.githubusercontent.com/959327/51982680-fbd14100-2496-11e9-8ef9-cf9a7608a7ea.png)

vs

![screen shot 2019-01-30 at 13 55 51](https://user-images.githubusercontent.com/959327/51982681-fc69d780-2496-11e9-9d92-d6d6368550bb.png)

^^ check the lowest icon

**Comment by michaelstingl** [comment]
Fixed in 2.6
