### ISSUE TITLE
MINGW32-MAKE Error

### ISSUE THREAD

**Issue by timetofaceit** [owncloud/client#7011]
Hello,

I'm trying to build owncloud client following these instruction - 
https://doc.owncloud.org/desktop/2.5/building.html. Everything goes well until 7 step. When I hit mingw32-make command I receive this error (picture):

![image](https://user-images.githubusercontent.com/47183414/52050431-30a5cc80-2559-11e9-950a-3ed8c628c4eb.png)

What am doing wrong?

**Comment by dschmidt** [comment]
@ckamm you've been using mingw until very recently - have you seen this?

@timetofaceit I recommend to use KDE Craft to build the owncloud-client. Also the official binaries are built with MSVC by now, maybe worth using that if you don't insist on a free software compiler. (MSVC at least does not cost anything for personal use)

**Comment by timetofaceit** [comment]
@dschmidt @ckamm thanks for the quick answer. I have applied your fix and it works great, but when I want to start the owncloud.exe file in bin directory it asks for Qt5Core.dll Q5Network.dll and so on. How can this be fixed?

Also I would like to know how to build it using visual studio on windows as you said before?

**Comment by timetofaceit** [comment]
@michaelstingl trying to follow kde craft instructions but getting this error:

![image](https://user-images.githubusercontent.com/47183414/52069471-737e9900-2587-11e9-858e-35b0ba11887f.png)

I installed python 2.7 manually to C disk, but still no go. Any thoughts?

**Comment by timetofaceit** [comment]
Have sorted this out by not using the "craft --set version master owncloud-client" command.

**Comment by timetofaceit** [comment]
Well I builded with kde craft, but can someone tell me what to do next? How to make installation file or launch the owncloud client?

I don't know if am in the right spot after build but that's what kind of error I get now:

![image](https://user-images.githubusercontent.com/47183414/52075074-06253500-2594-11e9-97da-e310f7b2482e.png)

Any ideas?

**Comment by michaelstingl** [comment]
This is an issue tracker. For build support, please join the discussion in https://central.owncloud.org/t/building-owncloud-client-on-windows-10/17730
