### ISSUE TITLE
owncloud: error while loading shared libraries: libowncloudsync.so.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by withit** [owncloud/client#7012]
### Expected behaviour
Client should launch.
### Actual behaviour
When launched on the command line, the error `owncloud: error while loading shared libraries: libowncloudsync.so.0: cannot open shared object file: No such file or directory` is returned. With the GUI, the wait cursor appears for a while (<20 seconds) before disappearing. The GUI client does not launch.

It appears that the build results in the libowncloud sync libraries being installed into `/usr/local/lib/arm-linux-gnueabihf/`, but the client won't launch unless `libowncloud_csync.so.0` and `libowncloudsync.so.0` are copied up one directory to `/usr/local/lib/` and `ldconfig` executed.

Contents of `/usr/local/lib/arm-linux-gnueabihf/`
```
pi@raspberrypi:/usr/local/lib/arm-linux-gnueabihf $ ls -lah
total 1.8M
drwxr-sr-x 2 root staff 4.0K Feb  2 15:36 .
drwxrwsr-x 6 root staff 4.0K Feb  2 16:14 ..
lrwxrwxrwx 1 root staff   22 Feb  2 15:36 libowncloud_csync.so -> libowncloud_csync.so.0
lrwxrwxrwx 1 root staff   26 Feb  2 15:36 libowncloud_csync.so.0 -> libowncloud_csync.so.2.5.2
-rw-r--r-- 1 root staff 445K Feb  2 14:46 libowncloud_csync.so.2.5.2
lrwxrwxrwx 1 root staff   20 Feb  2 15:36 libowncloudsync.so -> libowncloudsync.so.0
lrwxrwxrwx 1 root staff   24 Feb  2 15:36 libowncloudsync.so.0 -> libowncloudsync.so.2.5.2
-rw-r--r-- 1 root staff 1.3M Feb  2 14:59 libowncloudsync.so.2.5.2
```

### Steps to reproduce
1. Build client per instructions at [Building owncloud client for Raspberry pi's raspbian](https://wiki.sgripon.net/doku.php/building_owncloud_client_for_raspberry_pi) by SGRipon
2. Launch client 

### Server configuration
Operating system: Ubuntu 18.04.1 LTS
Web server: Apache\/2.4.29 (Ubuntu)
Database: mysql 5.0.12
PHP version: 7.1.26-1+ubuntu18.04.1+deb.sury.org+1
ownCloud version: 10.0.10
Storage backend (external storage): None

### Client configuration
Client version: 2.5.2
Operating system: Linux raspberrypi 4.14.79-v7+ #1159 SMP Sun Nov 4 17:50:20 GMT 2018 armv7l
OS language: English
Qt version used by client package (Linux only, see also Settings dialog): 5.7.1
Client package (From ownCloud or distro) (Linux only): 
Installation path of client:

### Logs
1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
Log file not generated.
2. Web server error log:
No web server error detected.
3. Server logfile: ownCloud log (data/owncloud.log):
No server error detected.

**Comment by jnweiger** [comment]
As SGRipon says in https://wiki.sgripon.net/doku.php/building_owncloud_client_for_raspberry_pi#build_a_debian_package
copying the two files one level up is a manual step in his instructions. 
@withit I suggest you try to clarify with him directly why that is needed.
Without further research, I cannot tell if the involved oc-build-deb.sh is his or from owncloud.

Does that help?
