### ISSUE TITLE
[macOS] 2.5.2 Status icons missing in Finder

### ISSUE THREAD

**Issue by vco1** [owncloud/client#7013]
### Expected behaviour
Show status icon next to a file or folder in the Finder.

### Actual behaviour
Status icons in Finder next to files and folders are missing (again).

### Steps to reproduce
1. Open Finder window
2. Look for status icons.

### Client configuration
Client version: 2.5.2

Operating system: macOS 10.14.3

OS language: English

This error also occured with version 2.5.0 and was fixed in 2.5.1. Now it's back in 2.5.2.

**Comment by guruz** [comment]
@vco1 Could you try to reproduce this with 2.5.3 rc1 which we are about to release?
https://download.owncloud.com/desktop/testing/ownCloud-2.5.3.11279rc1.pkg

**Comment by vco1** [comment]
@guruz After installing 2.5.3 rc1 I can confirm that the status icons in the Finder are working again.
Test (for this issue) passed.

**Comment by guruz** [comment]
Thanks a lot
