### ISSUE TITLE
owncloud client 2.5 os x mojave 10.14.3 file extension not work

### ISSUE THREAD

**Issue by EugenioLST** [owncloud/client#7024]
### Expected behaviour
Hi have update mi OS X to  mojave 10.14.3
I have owncloud client 2.5 for OS X
the file extension not work

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/client/issues/7013 (try [2.5.3](https://github.com/owncloud/client/releases/tag/v2.5.3))
