### ISSUE TITLE
[Linux] Client not usable when running as 'root' user

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#7026]
"client freezes" means as following :  
one can't call owncloud-menu over tray-icon during sync
if owncloud-settings-window is open ,it doesn't react  by clicking at all till sync is over 
etc .. 
after testing , this problem isn't existing on Ubuntu 18.10 
regards ,

**Comment by ogoffart** [comment]
Can you run with gdb and get a backtrace showing what's happening when it freeze?

Open owncloud with  `gdb owncloud`
Then when it is frozen, press Ctrl+C,  then  `thread apply all bt`  to get the backtrace.

**Comment by lazawan** [comment]
@ogoffart  sure,  i will try to do it and let you know what i get

**Comment by lazawan** [comment]
i have just noticed ,it occurs only if one uses root account ,other users don't have this problem
