### ISSUE TITLE
virtual-files feature on Owncloud client v2.6.0 with Qt 5.12.1 is missing completely

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#7027]
simply VFS is not there :-`(  " i mean on all linux Platforms )

regards,

**Comment by ogoffart** [comment]
It is!

Maybe you are using a branding that disable it?

**Comment by lazawan** [comment]
@ogoffart  no i used the daily build for 2.6.0 client , i'm aware that branded-client doesn't have VFS

**Comment by ckamm** [comment]
Maybe the client can't open any of the vfs plugins. @lazawan Could you give me the first 20 lines of the client log file? It should say "VFS windows plugin is available" and "VFS suffix plugin is available".

**Comment by jnweiger** [comment]
Same here: 2.6.0 daily 20190211 on Linux Mint, Ubuntu 18.04

* The firstrun wizard no longer mentions any expermimental features.
* The three dots menu no longer allows switching to/from virtual mode.
* renaming a file to end in .owncloud just renames the file. It is uploaded to the server with this suffix.

Is there now a VFS plugin that is needed for Linux? Maybe packagaging needs to adapt for structural changes?

**Comment by ckamm** [comment]
@jnweiger Does the package contain the libowncloudsync_vfs_* shared libraries? @dschmidt

**Comment by jnweiger** [comment]
No. Packaging cannot pick up new additions. I need to locate everything manually. Thanks for the hint, I have to ho searching now..

**Comment by ckamm** [comment]
@jnweiger The plugin is called "owncloudsync_vfs_suffix.so" built from "src/libsync/vfs/suffix" and should be installed next to the binary.

**Comment by jnweiger** [comment]
DEB packages have it in the build-log
[  368s] [ 21%] Linking CXX shared library ../../../../bin/owncloudsync_vfs_suffix.so
[ 1182s] -- Installing: /usr/src/packages/BUILD/debian/tmp/opt/ownCloud/ownCloud/lib/x86_64-linux-gnu/plugins/owncloudsync_vfs_suffix.so

but it neither breaks packages with "unpackaged file error", nor is it auto-included anywhere. That is odd.

**Comment by jnweiger** [comment]
Is there a simple test to see where the plugin is searched at runtime?
should e.g. `strace owncloudcmd -v` show something?

**Comment by jnweiger** [comment]
It gets loaded, if placed in 
```
ll /opt/ownCloud/ownCloud/bin/
insgesamt 2604
drwxr-xr-x 2 root root    4096 Feb 27 10:34 ./
drwxr-xr-x 4 root root    4096 Feb 11 16:48 ../
-rwxr-xr-x 1 root root 2541848 Feb 27 09:59 owncloud*
-rwxr-xr-x 1 root root   84216 Feb 27 09:59 owncloudcmd*
-rw-r--r-- 1 root root   26776 Feb 27 10:34 owncloudsync_vfs_suffix.so
```
@ckamm that is a mess. We should try to make it work from the libs or better libs/plugins folder.

**Comment by jnweiger** [comment]
Workaround committed to OBS. Symlink into bin.
https://build.opensuse.org/package/rdiff/isv:ownCloud:desktop:daily:master/owncloud-client?linkrev=base&rev=482

**Comment by ckamm** [comment]
Huh, dlopen() should be using the normal search path for shared libraries, so it should be found among the other libraries that the executable's RPATH points to. I'll install it and check it out.

**Comment by ckamm** [comment]
Qt manually resolves plugin paths and uses dlopen only with absolute filenames. I agree that our plugin doesn't belong into the Qt/plugins directory and assume distribution packagers would also be unhappy putting them there.

I propose we add a build setting for a path that we add to Qt's plugin search path on startup and then place our plugins there.

**Comment by ckamm** [comment]
@jnweiger Now that this is in the workaround should not be necessary any more. Either set the new PLUGINDIR path, or install to the place it points to by default.

**Comment by jnweiger** [comment]
Linux builds seem to install the vfs_suffix plugin now into
@CLIENT_ROOT@/lib/$(DEB_HOST_MULTIARCH)/@APPLICATION_SHORTNAME@/plugins/

Examples:
* /opt/ownCloud/ownCloud/lib64/ownCloud/plugins/owncloudsync_vfs_suffix.so
* /opt/ownCloud/testpilotcloud/lib64/testpilotcloud/plugins/testpilotcloudsync_vfs_suffix.so

I am changing the *.install, *.rules *.spec files to pick it up from there.

**Comment by jnweiger** [comment]
## tested 2.6.0daily20190322  on ubuntu-18.04 using Qt-5.12.2
The plugin is there
-rw-r--r-- 1 root root 26776 Mär 22 17:53 /opt/ownCloud/ownCloud/lib/x86_64-linux-gnu/ownCloud/plugins/owncloudsync_vfs_suffix.so

and works.
