### ISSUE TITLE
No Qt platform plugin could be initialized. Windows Client

### ISSUE THREAD

**Issue by timetofaceit** [owncloud/client#7034]
Hello,

I have compiled the client for windows from open source. On my PC client is starting and working normal as it should. If am trying to launch the bin directory from the other PC I get this error:

![image](https://user-images.githubusercontent.com/47183414/52720470-58ad1b00-2fb0-11e9-979a-70e33c58807d.png)

I used windeployqt from this link -> https://doc.qt.io/Qt-5/windows-deployment.html#the-windows-deployment-tool but still getting the same error.

My bin folder looks like this:

![image](https://user-images.githubusercontent.com/47183414/52720654-b0e41d00-2fb0-11e9-8236-b26ec10192b0.png)

Any ideas?

**Comment by dschmidt** [comment]
What's the content of `platforms/` folder?

**Comment by timetofaceit** [comment]
@dschmidt thank's for the quick answer.

Platforms folder:

![image](https://user-images.githubusercontent.com/47183414/52722064-952e4600-2fb3-11e9-9281-10017cce05f5.png)

**Comment by dschmidt** [comment]
Maybe try to create a `qt.conf` file with:

``
[Paths]
Plugins = .
``
Compare https://doc.qt.io/qt-5/qt-conf.html

**Comment by dschmidt** [comment]
Neat! :tada: 

FTR I'm currently updating the windows build instructions: https://github.com/owncloud/client/pull/7035
But glad you could make it work too :-)

**Comment by qasimali-byte** [comment]
https://www.youtube.com/watch?v=9eyNNkxYvEA

**Comment by esackbauer** [comment]
I am suddenly experiencing this exact error when I logon to Windows and OwnCloud Client is automatically started.
If I start Owncloud client manually, there is no problem.

It is happening since version 2.7.2
2.7.1 was ok.
Running on Windows 10 20H2.

**Comment by michaelstingl** [comment]
@esackbauer this issue is about self-compiled ownCloud Win builds. Do you use self-compiled ownCloud desktop client, or one downloaded from ownCloud website?

**Comment by esackbauer** [comment]
Its the one downloaded from the website.

**Comment by esackbauer** [comment]
Ok, its all sorted now. I uninstalled ownCloud client, removed any traces in the file system, rebooted, and then did a clean install.
Now it properly installed into c:\program files\owncloud as its supposed to.
Also the qt error during startup is now gone.

**Comment by Tomino-RI** [comment]
Hi esackbauer!
Thank you for sharing how you solved your problem.
I have the same problem as you had.  Mine ownCloud client is also installed on C:\ root folder and is version 2.7.3
Do I have to synchronize again all data after I uninstall and perform new installation of ownCloud.
I mean, do I have to copy again all data from cloud to my computer or new installation of ownCloud will recognize structure of folders which were synchronized before?

**Comment by esackbauer** [comment]
Actually this happened again to me, when updating to 2.7.3! It seems something is wrong with the update procedures.
I uninstalled 2.7.2, and downloaded 2.7.3, all settings were taken over, no need to sync again.

**Comment by Tomino-RI** [comment]
Thank you for your fast reply.
I am on Windows 10 Pro version 1909.
If I have understood well, the problem is still there, but you did not need to sync again.

**Comment by dschmidt** [comment]
I'm sorry for the inconvenience with the installation to C:/.

This happened when your initial install of the client was from the 64bit MSI and then the autoupdater installed the 32bit version for you.

This was reported in https://github.com/owncloud/client/issues/8297 and fixed since then.

The autoupdater now correctly updates 64bit installs to 64bit binaries, so this won't happen automatically anymore.

Moreover 2.7.4 will contain a fix so that manual downgrades to 32bit will fallback to `[ROOTDRIVE]Program Files (x86)/ownCloud`.

**Comment by Tomino-RI** [comment]
Dear dschmidt,

Thank for your reply and this information!
This inconvenience with the installation to C:/ is not so serious. It is more important that ownCloud function properly 👍 
I am again nicely surprised and thankful for help I get from internet community.
Thank you guys! 👍
