### ISSUE TITLE
Mac client deleting .docx files

### ISSUE THREAD

**Issue by lukewoj** [owncloud/client#7036]
### Expected behaviour
A user with the Windows client saves a .docx file. The user with the Mac client then edits the .docx file, saves the changes and then the file is still in the original location, not deleted.

### Actual behaviour
A user with the Windows client saves a .docx file. The user with the Mac client then edits the .docx file, saves the changes and then the file is placed in the trash.

Please not, this same issue doesn't occur with .doc files, only .docx files.

### Steps to reproduce
1.  Save a Word Document as .docx on Windows and save it. Make sure it syncs up to OwnCloud.
2.  Open the Word Document on the Mac client, modify it and save it.
3.  The file will now be in the trash in OwnCloud.

### Server configuration
Operating system: CentOS release 6.9

Web server: Apache/2.4.34

Database: MariaDB 10.0.35

PHP version: 5.6

ownCloud version: 10.0.10.4

Storage backend (external storage): Server storage

### Client configuration
Client version: Unknown

Operating system: Mac

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): Unknown

Client package (From ownCloud or distro) (Linux only): Unknown

Installation path of client: Unknown

### Logs

{"reqId":"379e98a8-c2f0-421b-b8f4-5ad6dc7da4b1","level":0,"time":"2019-02-12T04:38:47+00:00","remoteAddr":"removed","user":"removed","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/removed","message":"updating token 13137, last check is now 1549938946"}
{"reqId":"379e98a8-c2f0-421b-b8f4-5ad6dc7da4b1","level":0,"time":"2019-02-12T04:38:48+00:00","remoteAddr":"removed","user":"removed","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"PROPFIND","url":"\/remote.php\/dav\/files\/removed","message":"token af3bc2ab76a070da73565272ee8ded1f5803e05d66dc1281155230b08044966c5be66d48f6bb133752c0e6dcde15d74e8b7c0b62e372f4372ef37f8a23d72b16 does not exist"}
{"reqId":"b9c0293c-cedb-4124-ad7d-b7465c02bcd0","level":0,"time":"2019-02-12T04:38:49+00:00","remoteAddr":"removed","user":"removed","app":"OC\\Authentication\\Token\\DefaultTokenProvider::updateToken","method":"DELETE","url":"\/remote.php\/dav\/files\/removed.docx","message":"updating token 13137, last check is now 1549938946"}
{"reqId":"b9c0293c-cedb-4124-ad7d-b7465c02bcd0","level":0,"time":"2019-02-12T04:38:49+00:00","remoteAddr":"removed","user":"removed","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"DELETE","url":"\/remote.php\/dav\/files\/removed.docx","message":"token af3bc2ab76a070da73565272ee8ded1f5803e05d66dc1281155230b08044966c5be66d48f6bb133752c0e6dcde15d74e8b7c0b62e372f4372ef37f8a23d72b16 does not exist"}

**Comment by ckamm** [comment]
@lukewoj Thanks for the report, this looks like a serious issue and is probably related to the program editing the docx on the Mac. What are you using?

The server has seen a DELETE command, which means the Mac client thought the file was deleted locally and that it thus needed to be removed on the server. Can you reproduce the problem? It'd be extremely helpful to have a client log file from the Mac client. See https://doc.owncloud.org/desktop/2.5/troubleshooting.html#saving-files-directly for how to enable logging.

**Comment by lukewoj** [comment]
Hi @ckamm,

The user is using Word 2016 on Mac to modify the file.

Strangely, the user had this same issue with .xlsx files but they upgraded from Office 2011 to Office 2016 which resolved the issue.

I've seen the problem first hand remotely logged into the Mac.

I'll get the client log file and will reply back.

Cheers!

**Comment by lukewoj** [comment]
Hi @ckamm,

I've been able to get the logs from the Mac when the issue is occurring.

Is there a way for me to privately send them to you as there is some confidential information in them?

Cheers!

**Comment by ckamm** [comment]
@lukewoj Great! Send them to mail at ckamm de.

**Comment by ckamm** [comment]
What it looks like to me from the log:
* changes to file A are uploaded to the server
* a server rename A -> B is propagated
* the file B is not found locally and thus removed from the server

Probably the file is open in the application the whole time. My guess is either something went wrong with the rename (I'm seeing a "[ warning sync.propagator ]:	No valid fileinfo") or the application got confused and deleted the file.

**Comment by ckamm** [comment]
This may be related: https://answers.microsoft.com/en-us/msoffice/forum/msoffice_word-mso_mac-mso_mac2011/file-name-changes-to-word-work-file-d-and-deletes/aea3ef5a-2f7a-444f-8ec6-99a5a045aca7?page=1 - no resolution though.

**Comment by ckamm** [comment]
Summary: Likely a misbehavior of Word 2016 for Mac. :(
