### ISSUE TITLE
branded client 2.5.3 on opensuse leap 15 freezes during synchronization 

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#7037]
used Qt is 5.10.1 and problem occurs if one runs branded-client as root 
normal user didn't get this problem
when one puts cursor on 3-point-icon on client ,then gets a strange hand or cursor 
related with #7026

**Comment by michaelstingl** [comment]
@lazawan please provide the information from [`.github/issue_template.md`](https://github.com/owncloud/client/blob/master/.github/issue_template.md)

**Comment by lazawan** [comment]
### Expected behaviour
        as root one should be able to run owncloud-client without freezing during sync on linux "rpm based                                  
        distros"
### Actual behaviour
       owncloud-client freezes during sync if one runs owncloud as root 
       freezing means : one can't switch  between owncloud-client-taps " in settings window " and can't call         
        menu from tray-icon

### Steps to reproduce
     1. log in as root "in terminal" on for instance opensuse leap 15 
     2. run owncloud-client and configure it
     3. let owncloud-client sync and during sync one will notice a freezing at the end of sync 

### Server configuration

       ownCloud version: 10.0.10

### Client configuration
      Client version: 2.5.3 and 2.5.2 

      Operating system: opensuse leap 15 

      OS language: english

      Qt version used by client package (Linux only, see also Settings dialog): 5.10.1

**Comment by guruz** [comment]
While we maybe could fix this, running GUI apps as root user is not something one should do.

Closing as dup of https://github.com/owncloud/client/issues/7026
