### ISSUE TITLE
client 2.6.0 on windows 10 downloads several fotos in VFS mode,though one  has downloaded/requested only one

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#7039]
Hi there , 
client was from daily build "ownCloud-2.6.0.11504.11331-daily20190214.en-US.msi"
steps to reproduce : 
- configure client with VFS
- after sync one gets Photos folder " i normally use demo.owncloud.org"
- go to Photos
- double click on a photo to download it 
- now another Photos are downloaded though i didn't request/download them. 

regards ,

**Comment by michaelstingl** [comment]
@lazawan logfile?

**Comment by lazawan** [comment]
@michaelstingl  

> 02-14 07:46:50:811 [ info sync.vfs ]:	FETCH
02-14 07:46:50:811 [ info sync.vfs ]:	fetch data request "C:/Users/admin/ownCloud5/" "\\Users\\admin\\ownCloud5\\Photos\\Squirrel.jpg" "00000016ocmm8a5fnafq" 0 233724 0 0
02-14 07:46:50:825 [ info gui.folder.manager ]:	>========== Sync started for folder [ownCloud5] of account [demo@demo.owncloud.org] with remote [https://demo.owncloud.org/remote.php/dav/files/demo/]
02-14 07:46:50:842 [ info gui.application ]:	Sync state changed for folder  "https://demo.owncloud.org/remote.php/dav/files/demo/" :  "Sync Running"
02-14 07:46:50:858 [ info sync.accessmanager ]:	2 "" "https://demo.owncloud.org/remote.php/dav/files/demo/Photos/Squirrel.jpg" has X-Request-ID "987ae0d2-a979-4ba0-accf-9fd7f82ab7cd"
02-14 07:46:50:858 [ info sync.networkjob ]:	OCC::GETFileJob created for "https://demo.owncloud.org" + "/Photos/Squirrel.jpg" "OCC::HydrationContext"
02-14 07:46:50:903 [ info sync.accessmanager ]:	6 "PROPFIND" "https://demo.owncloud.org/remote.php/dav/files/demo/" has X-Request-ID "a9f5eb94-904d-4d37-8356-a790e8d17378"
02-14 07:46:50:903 [ info sync.networkjob ]:	OCC::PropfindJob created for "https://demo.owncloud.org" + "/" "OCC::ConnectionValidator"
02-14 07:46:51:045 [ info sync.networkjob.propfind ]:	PROPFIND of QUrl("https://demo.owncloud.org/remote.php/dav/files/demo/") FINISHED WITH STATUS "OK"
02-14 07:46:51:125 [ info sync.vfs ]:	request to validate data "\\Users\\admin\\ownCloud5\\Photos\\Squirrel.jpg" 0 233724
02-14 07:46:51:125 [ info sync.checksums ]:	Computing "SHA1" checksum of iodevice in a thread
02-14 07:46:51:139 [ info sync.vfs ]:	validation success: "Photos/Squirrel.jpg"
02-14 07:46:51:139 [ info sync.database ]:	Updating file record for path: "Photos/Squirrel.jpg" inode: 625 modtime: 1550156530 type: 0 etag: "5fecf96ad989bf65c939f242f5897ff8" fileId: "00000016ocmm8a5fnafq" remotePerm: "WDNVR" fileSize: 233724 checksum: "SHA1:ed266b89065e74483248da7ff71cb80e3cca40a5"
02-14 07:46:51:154 [ info gui.folder.manager ]:	<========== Sync finished for folder [ownCloud5] of account [demo@demo.owncloud.org] with remote [https://demo.owncloud.org/remote.php/dav/files/demo/]
02-14 07:46:51:154 [ info gui.socketapi ]:	Sending SocketAPI message --> "UPDATE_VIEW:C:\\Users\\admin\\ownCloud5" to QLocalSocket(0x75e9728)
02-14 07:46:51:154 [ info gui.application ]:	Sync state changed for folder  "https://demo.owncloud.org/remote.php/dav/files/demo/" :  "Success"
02-14 07:46:51:154 [ info gui.folderwatcher ]:	Detected changes in paths: QSet("C:/Users/admin/ownCloud5/Photos/Squirrel.jpg")
02-14 07:46:51:154 [ info gui.folder ]:	Ignoring spurious notification for file "Photos/Squirrel.jpg"
02-14 07:46:53:824 [ info sync.accessmanager ]:	6 "PROPFIND" "https://demo.owncloud.org/remote.php/dav/files/demo/" has X-Request-ID "2a70193c-4fda-4dfb-b8b1-efbe39b4e61b"
02-14 07:46:53:824 [ info sync.networkjob ]:	OCC::PropfindJob created for "https://demo.owncloud.org" + "/" "OCC::QuotaInfo"
02-14 07:46:54:011 [ info sync.networkjob.propfind ]:	PROPFIND of QUrl("https://demo.owncloud.org/remote.php/dav/files/demo/") FINISHED WITH STATUS "OK"
02-14 07:46:55:361 [ info sync.vfs ]:	FETCH
02-14 07:46:55:361 [ info sync.vfs ]:	fetch data request "C:/Users/admin/ownCloud5/" "\\Users\\admin\\ownCloud5\\Photos\\San Francisco.jpg" "00000017ocmm8a5fnafq" 0 216071 0 0
02-14 07:46:55:361 [ info gui.folder.manager ]:	>========== Sync started for folder [ownCloud5] of account [demo@demo.owncloud.org] with remote [https://demo.owncloud.org/remote.php/dav/files/demo/]
02-14 07:46:55:361 [ info gui.application ]:	Sync state changed for folder  "https://demo.owncloud.org/remote.php/dav/files/demo/" :  "Sync Running"
02-14 07:46:55:361 [ info sync.accessmanager ]:	2 "" "https://demo.owncloud.org/remote.php/dav/files/demo/Photos/San Francisco.jpg" has X-Request-ID "1f4bd1bb-e64c-403b-b7ef-4d5978c71848"
02-14 07:46:55:361 [ info sync.networkjob ]:	OCC::GETFileJob created for "https://demo.owncloud.org" + "/Photos/San Francisco.jpg" "OCC::HydrationContext"
02-14 07:46:55:385 [ info sync.vfs ]:	FETCH
02-14 07:46:55:385 [ info sync.vfs ]:	fetch data request "C:/Users/admin/ownCloud5/" "\\Users\\admin\\ownCloud5\\Photos\\Paris.jpg" "00000018ocmm8a5fnafq" 0 228761 0 0
02-14 07:46:55:385 [ info sync.accessmanager ]:	2 "" "https://demo.owncloud.org/remote.php/dav/files/demo/Photos/Paris.jpg" has X-Request-ID "aea1be2b-9845-45b2-9d6b-1e1e58e77d44"
02-14 07:46:55:401 [ info sync.networkjob ]:	OCC::GETFileJob created for "https://demo.owncloud.org" + "/Photos/Paris.jpg" "OCC::HydrationContext"
02-14 07:46:55:697 [ info sync.vfs ]:	request to validate data "\\Users\\admin\\ownCloud5\\Photos\\San Francisco.jpg" 0 216071
02-14 07:46:55:697 [ info sync.checksums ]:	Computing "SHA1" checksum of iodevice in a thread
02-14 07:46:55:712 [ info sync.vfs ]:	validation success: "Photos/San Francisco.jpg"
02-14 07:46:55:712 [ info sync.database ]:	Updating file record for path: "Photos/San Francisco.jpg" inode: 554 modtime: 1550156531 type: 0 etag: "ae620440c4c69519943aa98d673412c7" fileId: "00000017ocmm8a5fnafq" remotePerm: "WDNVR" fileSize: 216071 checksum: "SHA1:f00431c8f8ac1530febe519ca413806be16e8e4c"
02-14 07:46:55:712 [ info gui.folderwatcher ]:	Detected changes in paths: QSet("C:/Users/admin/ownCloud5/Photos/San Francisco.jpg")
02-14 07:46:55:712 [ info gui.folder ]:	Ignoring spurious notification for file "Photos/San Francisco.jpg"
02-14 07:46:55:853 [ info sync.vfs ]:	request to validate data "\\Users\\admin\\ownCloud5\\Photos\\Paris.jpg" 0 228761
02-14 07:46:55:853 [ info sync.checksums ]:	Computing "SHA1" checksum of iodevice in a thread
02-14 07:46:55:853 [ info sync.vfs ]:	validation success: "Photos/Paris.jpg"
02-14 07:46:55:853 [ info sync.database ]:	Updating file record for path: "Photos/Paris.jpg" inode: 546 modtime: 1550156532 type: 0 etag: "7f7583fde64e155bae338c913314c5bb" fileId: "00000018ocmm8a5fnafq" remotePerm: "WDNVR" fileSize: 228761 checksum: "SHA1:73e6f4c116ef8fa4568028c7a1e45917ffeea8d8"
02-14 07:46:55:936 [ info gui.folder.manager ]:	<========== Sync finished for folder [ownCloud5] of account [demo@demo.owncloud.org] with remote [https://demo.owncloud.org/remote.php/dav/files/demo/]
02-14 07:46:55:936 [ info gui.socketapi ]:	Sending SocketAPI message --> "UPDATE_VIEW:C:\\Users\\admin\\ownCloud5" to QLocalSocket(0x75e9728)
02-14 07:46:55:936 [ info gui.application ]:	Sync state changed for folder  "https://demo.owncloud.org/remote.php/dav/files/demo/" :  "Success"
02-14 07:46:55:936 [ info gui.folderwatcher ]:	Detected changes in paths: QSet("C:/Users/admin/ownCloud5/Photos/Paris.jpg")
02-14 07:46:55:948 [ info gui.folder ]:	Ignoring spurious notification for file "Photos/Paris.jpg"
02-14 07:47:13:514 [ info gui.folder ]:	Trying to check "https://demo.owncloud.org/remote.php/dav/files/demo/" for changes via ETag check. (time since last sync: 46 s)
02-14 07:47:13:515 [ info sync.accessmanager ]:	6 "PROPFIND" "https://demo.owncloud.org/remote.php/dav/files/demo/" has X-Request-ID "189d1bc4-196a-42a8-ab76-cea54e372cb7"
02-14 07:47:13:516 [ info sync.networkjob ]:	OCC::RequestEtagJob created for "https://demo.owncloud.org" + "/" "OCC::Folder"
02-14 07:47:13:798 [ info sync.networkjob.etag ]:	Request Etag of QUrl("https://demo.owncloud.org/remote.php/dav/files/demo/") FINISHED WITH STATUS "OK"

**Comment by ckamm** [comment]
There's nothing we can do here unfortunately. What happens is that the photo viewer that is opened wants to preview the other photos in the directory and opens them to read their data. This causes them to be hydrated as well.

**Comment by michaelstingl** [comment]
@lazawan What photo viewer are you using in this local folder? Maybe we should add such stuff to the VFS FAQ or similar…

**Comment by lazawan** [comment]
@michaelstingl i was using the standard windows viewer
