### ISSUE TITLE
[Windows] Client crashed when adding new sync folder

### ISSUE THREAD

**Issue by BWibo** [owncloud/client#7041]
### Expected behaviour
Add a new sync folder using the clients GUI

### Actual behaviour
When hitting the *Add Sync Folder* button the client crashes.

### Steps to reproduce
1. Hit the *Add Sync Folder* button and see it crash.
Bug Report ID: bp-09ebfc78-40e8-445c-bc8a-57ea82190215

### Server configuration
Operating system: Ubuntu 16.04 x64

Web server: Apache

Database: PostgreSQL 10

PHP version: PHP 7.0.32-0ubuntu0.16.04.1 (cli) ( NTS )

ownCloud version: 10.0.10.4

Storage backend (external storage): local HDD

### Client configuration
Client version: 2.5.3 (build 11250)

Operating system: Win10 x64 1803 build 17134.590

OS language: german

Qt version used by client package (Linux only, see also Settings dialog): Qt 5.11.2

Client package (From ownCloud or distro) (Linux only):

Installation path of client: C:\Program Files (x86)\ownCloud\

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: let me know if you need it, it contains sensitive info like file names.
2. Web server error log:
3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by ckamm** [comment]
Sentry link to crash report: https://sentry.io/owncloud/desktop-win-and-mac/issues/862031540/events/46378587012/

Backtrace:
```
EXCEPTION_STACK_OVERFLOW at 0x77905f68

    Qt5Core.dll in QArrayData::allocate(unsigned
    qstring.cpp in QString::QString(int,Qt::Initialization)
    Qt5Core.dll in QUtf16::convertToUnicode(char
    Qt5Core.dll in QString::fromUtf16(unsigned
    Qt5Core.dll in QString::fromWCharArray(wchar_t
    Qt5Core.dll in QFileSystemEngine::nativeAbsoluteFilePath(QString
    Qt5Core.dll in QFSFileEnginePrivate::longFileName(QString
    qfilesystementry.cpp in QFileSystemEntry::resolveNativeFilePath()
    qfilesystementry.cpp in QFileSystemEntry::nativeFilePath()
    Qt5Core.dll in QFileSystemEngine::fillMetaData(QFileSystemEntry
```

Has happened for 2.5.2 and 2.5.3.

**Comment by ckamm** [comment]
Update: Getting access to the full stack trace shows it's an infinite loop in `OCC:canonicalPath()`

**Comment by guruz** [comment]
@BWibo Can you test this with https://download.owncloud.com/desktop/testing/ownCloud-2.5.4.11614.11431-rc1.msi ?

**Comment by BWibo** [comment]
@guruz I will do that tomorrow morning when I have access to the machine where the problem occured.

**Comment by BWibo** [comment]
@guruz Just tested the build and everything seems to work fine! Thank's for the fix.

**Comment by ckamm** [comment]
@BWibo Thanks for testing!

**Comment by jnweiger** [comment]
## tested 2.5.4.11614.11431-rc1 on win10
Hit Add folder Sync button
  -> Does not crash. A text entry opens.
OK

Enter 'f' into the entry field. OK. Enter ':' -> immediate crash.
bp-222216fc-69cf-46c9-91c1-0600a2190313

100% reproducable. Trying to enter a non-existant drive name causes a crash.
In some cases, it causes a frozen nonresponsive client that just hangs.
![grafik](https://user-images.githubusercontent.com/1108546/54303704-e5ed8a80-45c3-11e9-8f56-5cb51cbcb071.png)

BAD

**Comment by ckamm** [comment]
@jnweiger I think I know what's up, there's yet another recursive validation function that doesn't abort correctly in this case. I'll reproduce and fix.
