### ISSUE TITLE
"503 Service Unavailable" Error Issue on Almost All Files in Client Sync

### ISSUE THREAD

**Issue by JeronimoElias** [owncloud/client#7042]
Hello, I have a problem with my server, it has already updated 60% of the files (4.7gb), but it gives 503 error, if I change the filename, put a "-" for example, it usually comes up, but keeps giving this error straight.

### Expected behaviour

Send files without errors, like Mega Sync, or Google Sync

### Actual behaviour

Every 2 files checked, give the error "503 Service Unavailable" and stop synchronizing

### Server configuration

Operating system: Linux, I do not know, because I'm using the Hostinger.com.br c-panel to host my cloud

Database: MySQL 6

PHP version: 7.0

ownCloud version: 10.1.0

### Client Configuration
Client version: 2.5.2 (build 11181)

Operating system: Windows 10 pro

OS language: PT-BR

**Comment by ckamm** [comment]
The 503 is a message that's delivered to the client from the server, probably as a response to an attempted upload. There may not be much that the client can do about it aside from trying again, which should be the current behavior.

**Comment by JeronimoElias** [comment]
Thanks a lot for the answer @ckamm  , I checked in a discussion here in Git something about error 503 being considered a fatal error, which would have how to change this on the server, do you know something about, or in which file can be edited such a 503 rating?
Thanks again !!!

**Comment by ckamm** [comment]
@JeronimoElias That was a client code change discussed in #5088 and implemented in #6906 for versions 2.6+ - there a 503 that doesn't look like it comes from server maintenance will only lead to skipping the affected file.

You can already try this out by using the experimental 2.6 builds from http://download.owncloud.com/desktop/daily/ (probably start with the latest owncloud-2.6 msi)

**Comment by guruz** [comment]
@JeronimoElias This sounds more like a server issue. Please check the owncloud.log on server and also web server error_log.
