### ISSUE TITLE
build 11250 crashing repeatingly on win7

### ISSUE THREAD

**Issue by yasuoiwakura** [owncloud/client#7044]
### Expected behaviour
Owncloud client used to run days, weeks and months BEFORE client update

### Actual behaviour
Client 2.5.3 (build 11250) crashes several times a day. The taskbar icon will stay until i move the mouse cursor over the icon

### Steps to reproduce

- Crashes now and then without any noticable trigger
- Rescently, it crashes REPLICABLE when checking one directory share using the explorer context menu

last message in logfile (i would prefer not to share the WHOLE logfile to the world):
`02-17 13:14:10:657 [ info gui.socketapi ]:	Lost connection  QLocalSocket(0xe765248)
02-17 13:14:10:657 [ info gui.socketapi ]:	Received SocketAPI message <-- "SHARE:D:\\Daten\\cloud.blox.media\\Dir1\\Dir2\\Dir3" from QLocalSocket(0xe765248)`

### Server configuration
Operating system:
Ubuntu 16.04.5 LTS (GNU/Linux 4.4.0-042stab134.8 x86_64)
Web server: 
`ii  apache2                          2.4.18-2ubuntu3.9                     amd64        Apache HTTP Server
ii  apache2-bin                      2.4.18-2ubuntu3.9                     amd64        Apache HTTP Server (modules and other binary files)
ii  apache2-data                     2.4.18-2ubuntu3.9                     all          Apache HTTP Server (common files)
ii  apache2-utils                    2.4.18-2ubuntu3.9                     amd64        Apache HTTP Server (utility programs for web servers)
ii  libapache2-mod-php7.0            7.0.33-0ubuntu0.16.04.1               amd64        server-side, HTML-embedded scripting language (Apache 2 module)`

Database:
`ii  mysql-server                     5.7.25-0ubuntu0.16.04.2               all          MySQL database server (metapackage depending on the latest version)`

PHP version:
`ii  php7.0                           7.0.33-0ubuntu0.16.04.1               all          server-side, HTML-embedded scripting language (metapackage)`

ownCloud version:
`ii  owncloud-files                   10.0.9-1+1.1 `

Storage backend (external storage):

### Client configuration
Client version:
 2.5.3 (build 11250)
Operating system:
Win7 pro sp1

OS language:
german

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
"C:\Program Files (x86)\ownCloud\"
### Logs

1. Client logfile: 
`02-17 13:14:10:657 [ info gui.socketapi ]:	Lost connection  QLocalSocket(0xe765248)
02-17 13:14:10:657 [ info gui.socketapi ]:	Received SocketAPI message <-- "SHARE:D:\\Daten\\cloud.blox.media\\Dir1\\Dir2\\Dir3" from QLocalSocket(0xe765248)`
2. Web server error log:
nothing regarding OC

3. Server logfile: ownCloud log (data/owncloud.log):
todays entries:
``{"reqId":"ICHANGEDTHIS","level":2,"time":"2019-02-17T05:07:52+00:00","remoteAddr":"104.131.137.66","user":"--","app":"core","method":"GET","url":"\/","message":"Trusted domain error. \"104.131.137.66\" tried to access using \"85.214.112.18\" as host."}``

**Comment by yasuoiwakura** [comment]
p-de44f011-1e15-4bf8-96c4-292042190217 i

**Comment by ckamm** [comment]
Sentry link: https://sentry.io/owncloud/desktop-win-and-mac/issues/862016382/events/46576784640/

Backtrace:
```
Crash: EXCEPTION_ACCESS_VIOLATION_READ at 0x13a40fe6
  Module "Qt5Core.dll", in operator<<(QDebug,QObject
  Module "owncloud.exe", in OCC::SocketListener::sendMessage(QString
  Module "owncloud.exe", in OCC::SocketApi::processShareRequest(QString
  Module "owncloud.exe", in OCC::SocketApi::command_SHARE(QString
  Module "owncloud.exe", in OCC::SocketApi::qt_static_metacall(QObject
  Module "Qt5Core.dll", in QMetaMethod::invoke(QObject
  File "socketapi.cpp", in OCC::SocketApi::slotReadSocket()
  Module "Qt5Core.dll", in QMetaObject::activate(QObject
  Module "Qt5Core.dll", in QMetaObject::activate(QObject
  Module "Qt5Core.dll", in QMetaObject::activate(QObject
```

The QObject being passed to qDebug here is the SocketListener's `socket`. There hasn't been a change to the relevant code recently so this is probably due to a Qt upgrade.

**Comment by ckamm** [comment]
On further reading: This is a consequence of 0bfe7ac250c54f5415c0a794c7b271428e83c3cf. It's possible to get a `disconnected()` and then a `readyRead()` from the socket. The disconnect will remove the listener and then the data will be read and the handler will be invoked with an empty listener.

**Comment by ckamm** [comment]
PR: https://github.com/owncloud/client/pull/7045

**Comment by guruz** [comment]
@yasuoiwakura We have a daily build with this fix here: https://download.owncloud.com/desktop/daily/ownCloud-2.5.4.11526.11353-daily20190220.msi
Would you try this one and report back if it fixes the issue? Thank you

**Comment by ingogoeppert** [comment]
I have the same problems since version 2.5.2. ownCloud-2.5.4.11526.11353-daily20190220.msi fixed the issue for me.

**Comment by yasuoiwakura** [comment]
> 
> 
> @yasuoiwakura We have a daily build with this fix here: https://download.owncloud.com/desktop/daily/ownCloud-2.5.4.11526.11353-daily20190220.msi
> Would you try this one and report back if it fixes the issue? Thank you

sorry the the late reply.

no more crashes so far - thanks for the quick fix!
