### ISSUE TITLE
Error receiving folder list should be an error

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7051]
Client 2.6.0 daily 20190211 Ubuntu 18.04 fails to get a folder list from cloud.owncloud.com
![grafik](https://user-images.githubusercontent.com/1108546/53079809-8a196f80-34f7-11e9-99b5-8aac20ddd2ac.png)

The green checkmark indicates all is well, but instead of a folder list, there is an error message. Ending in 'Operation canceled'. The logwindow seems to have nothing suspicious.

**Comment by guruz** [comment]
@jnweiger That checkmark is the sync state, not related to the folder list state.

That said, why Operation Cancelled? Is there a timeout?
I dont see any in the log

**Comment by TheOneRing** [comment]
@jnweiger please answer

**Comment by TheOneRing** [comment]
Can't reproduce
