### ISSUE TITLE
[macOS only] 2.5.2 Client crashes when many files are to be synced

### ISSUE THREAD

**Issue by dportabella** [owncloud/client#7052]
I have 350'000 files to be synced, and the client crashes after one minute of starting.
Moreover, when I activate the log file as described here, no log files are generated:
https://doc.owncloud.com/desktop/2.5/troubleshooting.html#log-files

Using the GUI, and empty file is created.
Using the command-line, no files are created:
```
$ mkdir /tmp/owncloud_log
$ /Applications/owncloud.app/Contents/MacOS/owncloud --logdir /tmp/owncloud_log/
```

### Client configuration
Client version: 2.5.2
Operating system: Mac OSX 10.14.3 (18D109)
Installation path of client: default

**Comment by guruz** [comment]
@dportabella Could you please try a current 2.5.4 daily build?
https://download.owncloud.com/desktop/daily/ownCloud-2.5.4.11390-daily20190304.pkg

**Comment by dportabella** [comment]
I am sorry but, because it's a production environment and I already found a workaround by adding the appropriate ignore folders.

**Comment by michaelstingl** [comment]
many improvements in the 2.6, so I'd assume it is fixed
