### ISSUE TITLE
Reliably persist cookies

### ISSUE THREAD

**Issue by corneliusweiss** [owncloud/client#7054]
The client looses cookies after close and reopen. They can be found in the cookies.db but the client doesn't send them.

### Expected behaviour
When a Load Balancer or Proxy adds a cookie it should be preserved/send by the client.

### Actual behaviour
The cookie is not send to the server after the client got closed and opened again.

### Steps to reproduce
1. introduce cookie via proxy or lb
2. watch traffic
3. cookie is lost after quitting and opening client

Please see related discussion in #2808

**Comment by guruz** [comment]
@corneliusweiss Thanks for creating the bug, but you really need to provide version numbers etc, else how can we know you are using a current client version?

As @michaelstingl wrote in the comment already:
> What client version? What operating system?

**Comment by guruz** [comment]
@corneliusweiss Are you sure your proxy/loadbalancer is sending a persistant cookie?
http://www.allaboutcookies.org/cookies/cookies-the-same.html
(Although I don't remember how strict is cookies.db about this)

**Comment by corneliusweiss** [comment]
sorry for missing this. I testet with Version 2.5.1 (build 10818) on macOS (is think it's the latest version from autoupdates)

And yes, the cookie is persistent. Here is the sniffed cookie from the lb:
    Set-Cookie: be=app03; expires=Wed, 01-Jan-2020 00:00:00 GMT; Max-Age=26491080; path=/

I already played with the path option - but w.o. success

**Comment by ogoffart** [comment]
I can reproduce.

**Comment by guruz** [comment]
@corneliusweiss Want to test a current daily build? https://download.owncloud.com/desktop/daily/

**Comment by corneliusweiss** [comment]
sure, but which is the right one? testpilotclient? which version to test? I need a macOS package.

**Comment by guruz** [comment]
@corneliusweiss https://download.owncloud.com/desktop/testing/ownCloud-2.5.4.11420rc1.pkg

**Comment by corneliusweiss** [comment]
@guruz works like a charm 
Thanks a lot!

**Comment by guruz** [comment]
Great!
