### ISSUE TITLE
Checking folders in selective sync collapses folder

### ISSUE THREAD

**Issue by elmeto** [owncloud/client#7055]
### Expected behaviour
It used to be that you could look at a whole list of folders, then tick/untick one, then another, etc.

### Actual behaviour
As soon as you tick/untick a folder, all the folders collapse.  So if you've just navigated through to several subfolders, you now have to repeat all of that again, in order to tick/untick the next folder. 

### Steps to reproduce
1. Open Settings...
2. Expand the home folder to reveal subfolders, then expand another subfolder
3. tick/untick a folder inside

### Server configuration
Operating system:
macOS 10.13

Web server: 
Apache

Database:
MySQL

PHP version:
7
ownCloud version:
10
Storage backend (external storage):
RAID

### Client configuration
Client version:
2.5.3
Operating system:
macOS 10.14.3
OS language:
English UK
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
https://owncloud.org/download/

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by guruz** [comment]
I can reproduce this.
It only happens for the first time you click a subfolder. Clicking (after re-opening) further subfolders at the same level does not close again.

**Comment by guruz** [comment]
@elmeto Please test with https://download.owncloud.com/desktop/testing/ownCloud-2.5.4.11420rc1.pkg

**Comment by elmeto** [comment]
Brilliant, that works, thank you!

**Comment by guruz** [comment]
Great!
