### ISSUE TITLE
Owncloud client crashes under Windows 7 when trying to share file via explorer context menu

### ISSUE THREAD

**Issue by erik-saarts** [owncloud/client#7065]
### Expected behaviour
Window for sharing options should appear.

### Actual behaviour
Owncloud client crashes.

### Steps to reproduce
1. Right click on shared file in explorer.
2. Pick owncloud -> Share
3. Crash (reported it - bp-40e7e1af-21fc-42df-8a3f-557882190301)

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version: 2.5.3 (build 11250), 2.5.2 (build 11181); 2.5.1 (build 10807) works!

Operating system: Windows 7 Pro 64bit

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
"C:\Program Files (x86)\ownCloud\owncloud.exe"

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also http://doc.owncloud.org/desktop/2.2/troubleshooting.html#client-logfile )
```
03-01 15:22:25:132 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:SHARE::Share..." to QLocalSocket(0x675cfa8)
03-01 15:22:25:132 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:COPY_PUBLIC_LINK::Copy public link to clipboard" to QLocalSocket(0x675cfa8)
03-01 15:22:25:132 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:COPY_PRIVATE_LINK::Copy private link to clipboard" to QLocalSocket(0x675cfa8)
03-01 15:22:25:132 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:OPEN_PRIVATE_LINK::Open in browser" to QLocalSocket(0x675cfa8)
03-01 15:22:25:132 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_MENU_ITEMS:END" to QLocalSocket(0x675cfa8)
03-01 15:22:25:168 [ info gui.socketapi ]:	Lost connection  QLocalSocket(0x675cfa8)
03-01 15:22:27:636 [ info gui.socketapi ]:	New connection QLocalSocket(0x675cfa8)
03-01 15:22:27:636 [ info gui.socketapi ]:	Sending SocketAPI message --> "REGISTER_PATH:C:\\Users\\Erik\\ownCloud" to QLocalSocket(0x675cfa8)
03-01 15:22:27:637 [ info gui.socketapi ]:	Sending SocketAPI message --> "REGISTER_PATH:C:\\bsqlie" to QLocalSocket(0x675cfa8)
03-01 15:22:27:637 [ info gui.socketapi ]:	Sending SocketAPI message --> "REGISTER_PATH:C:\\test1" to QLocalSocket(0x675cfa8)
03-01 15:22:27:637 [ info gui.socketapi ]:	Lost connection  QLocalSocket(0x675cfa8)
03-01 15:22:27:637 [ info gui.socketapi ]:	Received SocketAPI message <-- "SHARE:C:\\Users\\Erik\\ownCloud\\test.xlsx" from QLocalSocket(0x675cfa8)
```

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by ingogoeppert** [comment]
I think this is a duplicate of #7044.

**Comment by guruz** [comment]
Indeed, please check a current daily build:
https://download.owncloud.com/desktop/daily/ownCloud-2.5.4.11579.11401-daily20190304.msi

**Comment by erik-saarts** [comment]
Indeed it fixes the problem.
