### ISSUE TITLE
Resolved conflicts aren't noticed immediately

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7073]
When I resolve a conflict by deleting the conflict file the client only picks up on it the next time a sync run happens. It should notice it immediately.

The issue here is that the file watcher discards changes to ignored files, and conflict files are ignored files. That means no update is done if only the conflict file changes.

**Comment by HanaGemela** [comment]
@ckamm I don't really understand what should happen here

1. User makes changes to file test.txt on the desktop
2. User makes changes to file test.txt in webUI
3. Sync creates a conflict file
4. User deletes the conflict file in the file system 

What is the expected result? I see that the yellow warning message disappears almost immediately. Is that it? No other checks needed? Tested with 2.6.0alpha2 (build 12128), macOS 10.14.5

![image](https://user-images.githubusercontent.com/49001702/61303172-5e20c280-a7e7-11e9-84a4-26abeec6a078.png)

**Comment by ckamm** [comment]
@HanaGemela Your guess is exactly right. The yellow "unresolved conflicts" bar should disappear quickly when all conflicts are resolved. That's all this ticket was about.

**Comment by HanaGemela** [comment]
Works as expected then
Tested with 2.6.0alpha2 (build 12128), macOS 10.14.5
