### ISSUE TITLE
owncloud client 2.5.3 doesn't take  OWNCLOUD_MAX_CHUNK_SIZE into account 

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#7078]
### Expected behaviour
i have to be able to limit `OWNCLOUD_MAX_CHUNK_SIZE` to 1MB  by exporting `OWNCLOUD_MAX_CHUNK_SIZE=1000000` `OWNCLOUD_MIN_CHUNK_SIZE=1000000` `OWNCLOUD_CHUNK_SIZE=1000000` in  shell

### Actual behaviour
exported max-value isn't token into account (client begins uploading with 10 000 000 bytes )  

### Steps to reproduce

- install owncloud-client 2.5.3
- make account on an owncloud-server 
- let account be empty ( i wanted to test uploading without downloading) 
- create a folder "sync-folder" and put some  files (in my case 223 MB) .
- now trigger : `owncloudcmd $HOME/sync-folder https://server`
- please type in your credentials of your empty account on server 
- obeserve please the logs in the shell and you should see something like that : 

"Chunked upload of 10000000 bytes took 62899 ms, desired is 60000 ms, expected good chunk size is 9539102 bytes and nudged next chunk size to 9598859 bytes"

### Server configuration
Operating system: Ubuntu 18.04 

Web server: Apache2

ownCloud version: 10.1.0

### Client configuration

ownCloud version 2.5.3 (build 342)
Using Qt 5.10.1, built against Qt 5.10.1
Using 'OpenSSL 1.0.2n  7 Dec 2017
Operating system: linux Mint or (ubuntu 18.04)
OS language: English

regards 
@jnweiger please take a look at it

**Comment by ckamm** [comment]
The chunk size environment variables currently don't apply to `owncloudcmd`. I'll change the milestone to 2.6 since it's not a regression.

**Comment by lazawan** [comment]
@ckamm i have just tested the chunk_size with 

https://software.opensuse.org//download.html?project=isv:ownCloud:desktop:daily:2.6&package=owncloud-client

and i think , it seems to be working :) 

that's what i got : 

Chunked upload of 1000000 bytes took 6288 ms, desired is 60000 ms, expected good chunk size is 9541984 bytes and nudged next chunk size to  1000000 bytes

**Comment by ckamm** [comment]
@lazawan That looks good!
