### ISSUE TITLE
Remove "ownCloud" submenu from shell integrations and instead show actions directly

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7079]
Suggested by @lexo-mfleuti in https://github.com/owncloud/client/issues/7061#issuecomment-468621463 along with a suggestion to make the context menu entries configurable.

**Comment by michaelstingl** [comment]
Related: https://github.com/owncloud/client/issues/7746

**Comment by TheOneRing** [comment]
While configurable entries make sense, I think it would really clutter the menu
