### ISSUE TITLE
Virtual file context menu options should be in submenu

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7083]
Follow up from #6815.

Currently the vfs actions appear next to sharing options etc. That's fine while there are few options but will become cluttered as the number of actions increases. A separator or maybe a submenu would be best.

Depends on #6921  and similar work for other shell extensions.

**Comment by jnweiger** [comment]
Daily master on win10 currently looks like this:
![grafik](https://user-images.githubusercontent.com/1108546/54297648-8f7a4f00-45b7-11e9-9875-5077284a5169.png)

No vfs actions anymore?

**Comment by michaelstingl** [comment]
For Native WinVFS, maybe no longer necessary. (see https://github.com/owncloud/client/issues/7746)

**Comment by fmoc** [comment]
@michaelstingl as far as I can see, #7746 suggests to revert on Windows what this issue suggests to introduce on Linux. Which strategy should be followed: submenu or not? We should decide on a single approach and then implement this everywhere to provide a consistent UX on all platforms.

**Comment by michaelstingl** [comment]
> submenu or not?

I think we can't control this in Windows. so others platforms would need to follow…

**Comment by TheOneRing** [comment]
I assume this ticket was about changing
![image](https://user-images.githubusercontent.com/200626/114706409-35fe2480-9d29-11eb-8528-a67ba5d5d40e.png)

**Comment by fmoc** [comment]
Oh, I see... Well, adding a submenu there likely makes things worse, so I'd rather try to add a separator.

**Comment by fmoc** [comment]
It doesn't seem like GNOME's Nautilus extension API provides any functionality to add separators, and an empty entry is even worse. I guess we'll have to add a submenu. However, that's would be quite ugly with the current socket API...

**Comment by TheOneRing** [comment]
@tbsbdr afaik sub menus in submenus are considered bad year 2k ux, am I right?

**Comment by fmoc** [comment]
Well, either a submenu, or we'll leave it as is for the Nautilus version. I'm looking into the Dolphin implementation next.

**Comment by fmoc** [comment]
Adding a separator in Dolphin worked fine. For GNOME, we would have to use a submenu, or leave things as they are.

**Comment by tbsbdr** [comment]
> @tbsbdr afaik sub menus in submenus are considered bad year 2k ux, am I right?

jep, don't! (unless you have very very good reason..)

**Comment by fmoc** [comment]
I think we can close this issue then? Given we don't want to add a submenu but Nautilus doesn't provide separators, we won't be making changes there. For Dolphin, the PR was merged.
