### ISSUE TITLE
Automatic dehydration of outdated unpinned files

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7084]
Follow up from #6815 

Imagine a file is hydrated but not explicitly pinned and then it changes on the server. Currently the sync client would update the local file by downloading the new contents. An alternate and maybe more intuitive course of action would be to dehydrate the local file.

This could potentially annoy users though.

**Comment by michaelstingl** [comment]
> An alternate and maybe more intuitive course of action would be to dehydrate the local file.

Yeah, I think so as well. 👍

**Comment by TheOneRing** [comment]
see https://github.com/owncloud/client/issues/7470
