### ISSUE TITLE
Virtual file actions are missing from the context menu

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7085]
daily master 20190313 on win10 looks like this
![grafik](https://user-images.githubusercontent.com/1108546/54297919-13343b80-45b8-11e9-9ec6-77609550dadd.png)

I cannot see any vfs actions. It is no longer possible to explicitly download an object or explicitly make it virtual.
The options 'Download file(s)' and 'Replace file(s) by virtual file' should be there, as e.g. seen in 2.5.4 
![grafik](https://user-images.githubusercontent.com/1108546/54298996-3233cd00-45ba-11e9-9ee2-0d82dfc61f23.png)

**Comment by michaelstingl** [comment]
@jnweiger What is the exact version of Win 10 you tested?

**Comment by jnweiger** [comment]
![grafik](https://user-images.githubusercontent.com/1108546/54299518-580da180-45bb-11e9-9e46-1807694702d2.png)

**Comment by michaelstingl** [comment]
Hm, Win 10 version 16299.15 or later is [needed](
https://support.office.com/en-us/article/use-onedrive-files-on-demand-in-windows-0e6860d3-d9f3-4971-b321-7092438fb38e) for the advanced Win integration.

@ckamm Could you have a look?

**Comment by ckamm** [comment]
@jnweiger @michaelstingl This looks correct. The options are "Immer auf diesem Gerät..." und "Speicherplatz freigeben" and are provided by Windows. 

But if you're confused by this, users might be as well. We could duplicate the actions in the ownCloud submenu?

**Comment by michaelstingl** [comment]
> The options are "Immer auf diesem Gerät..." und "Speicherplatz freigeben" and are provided by Windows.

Ah, didn't read properly. Let me check this on my device.

**Comment by jnweiger** [comment]
Ah, that explains it!
I am too Linux-narrow-minded. I never actually read any of the windows-specific right click items.

Duplicating the entries into our sub-menue is probably helpful for those of 
There are different users out there:
* "I know ownCloud. This is a cool, new and prominently advertised feature"
* "I know one-drive. Whatever-cloud backend there is, it should just work as expected."

To satisfy both, I agree, we could duplicate the actions in the ownCloud submenu.
If so, we must adopt the naming from one-drive to make it clear that it is the same thing.

Another argument is consistency across platforms. System-integration with Linux, Mac, Windows will each have different concepts and different user interfaces. The ownCloud-client is the only possible instance that can present a consistent user-interface. The right-click menu on all platforms has an ownCloud sub-menu. The current Inconsistency is: On Linux and Mac this sub menu has six entries, on windows only four.

**Comment by ckamm** [comment]
It'll be tricky to duplicate them exactly due to localization, and the Windows-provided actions may also change with Windows updates. While they are supposed to behave identically, that's not guaranteed - we only control the behavior of our own codepath.

Showing the vfs actions in our context menu again would be a trivial change (hiding them is a flag in the vfs plugin) - I assume we'll want to do that? @michaelstingl, any thoughts or suggestions?

**Comment by ckamm** [comment]
I've simply reenabled the hydrate/dehydrate actions for winvfs now.

**Comment by HanaGemela** [comment]
# Tested
Vfs actions are now available in ownCloud submenu in 2.6.0daily20190424 (build 11614)

**Comment by ckamm** [comment]
@HanaGemela Feel free to close ReadyToTest issues if testing passes.
