### ISSUE TITLE
Clicking items in "not synced" tab doesn't reliably open explorer window

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7088]
From https://github.com/owncloud/enterprise/issues/3212: It usually works on Macs, but not for ignored files. It never works on Windows.

**Comment by ckamm** [comment]
@ChrisEdS I've not been able to reproduce on Win10 with 2.5.4: I can double-click ignored files and conflict files and it'll take me to an explorer window that has the file selected. Can you retest, or maybe describe in which situations exactly the navigation didn't work?

**Comment by ChrisEdS** [comment]
Thank you @ckamm for looking into this. I'll test that again and maybe get some more information.

**Comment by ChrisEdS** [comment]
Tested with client 2.5.1 on Windows 10: Click on conflict file -> Explorer opens
Tested with client 2.5.4 on macOS: Click on conflict file -> Finder opens

I will ask the user for further information.

**Comment by ChrisEdS** [comment]
The user reported the following:

```
Strange that you have different results. I tested with branded 2.5.1
and oC 2.5.3 (the release from owncloud.com, when I switch to
beta-channel I don't get an update).
I tested on Mac Mojave and a VM with Windows 10.

On Mac with branded 2.5.1 conflict files are clickable but other files
(for instance, ignored ain't).
On Mac with oC 2.5.3 nothing is clickable.
On the Windows VM SD 2.5.1 nothing is clickable.
On the Windows VM oC 2.5.3 nothing is clickable.

My request is: all files clickable on both OS's.
```

I can't explain the different results. I think it makes sense to wait for the branded client 2.5.4 and request another test.

**Comment by kleinehector** [comment]
Thanks for looking into this. The behavior is very strange.

On VM with Windows 10  and 2.5.1 it didn't work for me, but it did work for a colleague with the same client on a native Windows 10.

After this another colleague who is just as me on Mac Mojave and the same client was unable to get to Finder from any files in the Not Synced, while the conflict files did work for me.

I have spoken with several colleagues and re-tested myself and the behavior on a particular desktop / client is stable (whatever (doesn't) work remains that way after a reboot. Between desktop / clients it is thus really variable.

**Comment by ckamm** [comment]
@kleinehector Hmm. Let's check whether the actions the client takes to show the files in the native browsers work.

On Mac, the client essentially does
```
/usr/bin/osascript -e 'tell application "Finder" to reveal POSIX file "%1"'
/usr/bin/osascript -e 'tell application "Finder" to activate'
```
Could you try this in a console manually, substituting %1 for the full path to the file that was clicked on?  I don't see why it would work for a conflict file and not work for other files though.

On Windows, the client calls
```
explorer.exe /select,"%1"
```
Does that work on the command line?

**Comment by ckamm** [comment]
In other issues I've seen people mention that they need to double-right(!)-click to open in the file browser. Could you double check that?

**Comment by CorneelDragon** [comment]
My colleague hector replied in my stead. I think I found it: The files that are not 'clickable' are simply not clickable because they are on the server and not local. Server files can be hidden as well and the client doesn't show a distinction where it blocks an upload or download 

I will check with colleagues to see if this explains there issues as well.

**Comment by ckamm** [comment]
@CorneelDragon Any updates or suggestions for ui improvement?

**Comment by ckamm** [comment]
Feel free to reopen.
