### ISSUE TITLE
Fix plugin packaging on OSX

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7090]
Now that #7076 is merged it should be possible to properly include the vfs plugin into the generated bundle for OSX.

@guruz already suggested that Contents/PlugIns looks like the right place according to https://developer.apple.com/library/archive/documentation/CoreFoundation/Conceptual/CFBundles/BundleTypes/BundleTypes.html#//apple_ref/doc/uid/10000123i-CH101-SW1 .

1) I would imagine that we want a relative PLUGINDIR "../PlugIns" for that.
2) Need to make sure the plugin binaries are placed in the right location.
3) Also, is the plugin found properly when doing developer builds without bundle creation?

Since I can't test the results I don't want to be the one implementing the changes.

Relates to #7027 which is about plugin packaging for linux.

**Comment by HanaGemela** [comment]
@ckamm @guruz is this something QA team can test? If so, please provide steps to reproduce

**Comment by guruz** [comment]
If the virtual file system mode works in your build on macOS, then this implicitly works too :-)
