### ISSUE TITLE
Check switchting to Qt 5.12.4

### ISSUE THREAD

**Issue by guruz** [owncloud/client#7092]
https://blog.qt.io/blog/2019/03/15/qt-5-12-2-released/

**Comment by tessus** [comment]
any update on this? I would really like to use H2 again.

**Comment by guruz** [comment]
Needs even Qt 5.12.4 apparantly :-(
https://github.com/owncloud/client/issues/7174#issuecomment-498602407

**Comment by ckamm** [comment]
It seems Qt 5.12.4 is on track for release on June 11th though, that'd be in time for 2.5.5.

**Comment by tessus** [comment]
> that'd be in time for 2.5.5

That would be great, because I really want to minimize (or even disable) HTTP1 traffic.

**Comment by ckamm** [comment]
@tessus 2.5.5 will not get the HTTP2 changes as the chance for http2 to still have bugs is too large. But the PRs were merged into 2.6. It's not certain that 2.6.0 will be shipped with Qt 5.12.4 though.

**Comment by tessus** [comment]
@ckamm this is too bad, because this means I have to wait for at least 6 or 8 more months. can't you just add a switch, in which case people can already choose what to use and you get additional info in the meantime....

**Comment by ckamm** [comment]
@tessus It's just enable-by-default that doesn't suit 2.5. There already is a `OWNCLOUD_HTTP2_ENABLED=1` environment variable switch, but you'd also need the resending logic - that looks safe for 2.5 though.

**Comment by tessus** [comment]
@ckamm That's fine. as long as I can use HTTP2 without havung to fear for my data I'm ok. I don't have a a problem with certain things not working or running into issues. I can then report back and you guys can fix that later. The more people test and run HTTP2 the better. And I mean for you too, because you'll get more reports of what's working and what's not.

**Comment by ckamm** [comment]
@tessus  The HTTP2 resend workaround is now backported to 2.5 to allow for early testing. Still requires  the new Qt though.

**Comment by tessus** [comment]
@ckamm I remember you made previous builds available with 2 different qt vesions. e.g. 2.4.3 with Qt 5.10.1 and with Qt 5.8.x.

I'd compile it myself but the space requirements for Qt and the ownCloud client are ridiculously high.

**Comment by guruz** [comment]
> I'd compile it myself but the space requirements for Qt and the ownCloud client are ridiculously high.

Note that you only need to compile owncloud client. Qt you can take a precompiled package.

**Comment by jnweiger** [comment]
We are pushing Qt-5.12.4 into all Platforms Windows, Mac, Linux for building beta1 of client 2.6.0 release.

**Comment by tessus** [comment]
@jnweiger does this mean that H2 will be working on 2.6.0?

**Comment by michaelstingl** [comment]
> @jnweiger does this mean that H2 will be working on 2.6.0?

You should test with the 2.6.0-beta1 to find out…

**Comment by jnweiger** [comment]
Yes, http2 is a planned feature of 2.6.0 - I havent seen testresults myself, .... please let us know if you find issues with beta1.

**Comment by guruz** [comment]
@tessus Which OS are you on?
https://github.com/owncloud/client/issues/7063#issuecomment-517402779

**Comment by tessus** [comment]
@guruz macOS 10.14.6 18G84

**Comment by guruz** [comment]
@tessus https://download.owncloud.com/desktop/testing/ownCloud-2.6.0.12261beta1.pkg

**Comment by guruz** [comment]
I can confirm macOS uses 5.12.4.

@HanaGemela can you confirm this for Windows and one of the Linux builds?

**Comment by tessus** [comment]
@guruz is this the testpilotcloud branded client? if not, I won't be able to test, because I can't replace my production client.

**Comment by HanaGemela** [comment]
Linux 2.6.0beta1 (build 1269)
macOS 2.6.0beta1 (build 12261)
and Windows 2.6.0beta1 (build 12201) use Qt 5.12.4

**Comment by guruz** [comment]
@tessus Build in progress, will let you know..

**Comment by tessus** [comment]
@guruz no rush. I have to go to bed and get some sleep anyway.

**Comment by guruz** [comment]
@tessus https://download.owncloud.com/desktop/testing/testpilotcloud-2.6.0.12267beta1.pkg
You can see in the button menu if HTTP2 is used.

**Comment by guruz** [comment]
🔒 button menu
