### ISSUE TITLE
Can't install owncloud 2.5.3 on debian 9 stretch due to unmet dependencies

### ISSUE THREAD

**Issue by frazy81** [owncloud/client#7096]
I currently can't install owncloud-client on debian 9 stretch due to unmet dependencies. My output of "apt install owncloud-client" goes like:

The following packages have unmet dependencies:
 owncloud-client : Depends: libowncloudsync0 (= 2.5.3.11470+oc-342) but it is not going to be installed
                   Depends: ocqt5101-libqt5concurrent5 but it is not installable
                   Depends: ocqt5101-libqt5core5a but it is not installable
                   Depends: ocqt5101-libqt5dbus5 but it is not installable
                   Depends: ocqt5101-libqt5gui5 but it is not installable
                   Depends: ocqt5101-libqt5keychain1 but it is not installable
                   Depends: ocqt5101-libqt5network5 but it is not installable
                   Depends: ocqt5101-libqt5webkit5 but it is not installable
                   Depends: ocqt5101-libqt5widgets5 but it is not installable
                   Depends: ocqt5101-libqt5xml5 but it is not installable
                   Depends: owncloud-client-l10n but it is not going to be installed
                   Depends: ocqt5101-libqt5sql5-sqlite but it is not installable
                   Depends: ocqt5101-qtsvg5 but it is not installable
E: Unable to correct problems, you have held broken packages.

### Expected behaviour
owncloud 2.5.3 client installes without unmet dependencies

### Actual behaviour
"apt install owncloud-client", fails with dependency errors:

root@debian:/root# apt install owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud-client : Depends: libowncloudsync0 (= 2.5.3.11470+oc-342) but it is not going to be installed
                   Depends: ocqt5101-libqt5concurrent5 but it is not installable
                   Depends: ocqt5101-libqt5core5a but it is not installable
                   Depends: ocqt5101-libqt5dbus5 but it is not installable
                   Depends: ocqt5101-libqt5gui5 but it is not installable
                   Depends: ocqt5101-libqt5keychain1 but it is not installable
                   Depends: ocqt5101-libqt5network5 but it is not installable
                   Depends: ocqt5101-libqt5webkit5 but it is not installable
                   Depends: ocqt5101-libqt5widgets5 but it is not installable
                   Depends: ocqt5101-libqt5xml5 but it is not installable
                   Depends: owncloud-client-l10n but it is not going to be installed
                   Depends: ocqt5101-libqt5sql5-sqlite but it is not installable
                   Depends: ocqt5101-qtsvg5 but it is not installable
E: Unable to correct problems, you have held broken packages.

### Steps to reproduce
1. fresh installation of Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux
2. echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0/ /' > /etc/apt/sources.list.d/isv:ownCloud:desktop.list
3. wget -nv https://download.opensuse.org/repositories/isv:ownCloud:desktop/Debian_9.0/Release.key -O Release.key
4. apt-key add - < Release.key
5. apt-get update
6. apt-get install owncloud-client

(as described in https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client)

### Server configuration
omitted, it's a client installation problem.

### Client configuration
Client version:
2.5.3.11470+oc-342

Operating system:
Linux debian 4.9.0-8-amd64 #1 SMP Debian 4.9.144-3.1 (2019-02-19) x86_64 GNU/Linux

OS language:
EN

Qt version used by client package (Linux only, see also Settings dialog):
Qt 5.7.1

### Logs
none.

**Comment by michaelstingl** [comment]
I was able to reproduce using the install instructions linked from:
https://owncloud.org/download/#owncloud-desktop-client-linux

```
docker run -ti --rm debian:9
```

```
root@6841c8883e28:/# apt-get update
Ign:1 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  InRelease
Get:3 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  Release [1020 B]
Get:4 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  Release.gpg [481 B]
Hit:2 http://security-cdn.debian.org/debian-security stretch/updates InRelease              
Get:5 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0  Packages [3228 B]
Ign:6 http://cdn-fastly.deb.debian.org/debian stretch InRelease           
Hit:7 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease
Hit:8 http://cdn-fastly.deb.debian.org/debian stretch Release
Fetched 4729 B in 0s (6774 B/s)
Reading package lists... Done
root@6841c8883e28:/# apt-get install owncloud-client
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud-client : Depends: libowncloudsync0 (= 2.5.3.11470+oc-342) but it is not going to be installed
                   Depends: ocqt5101-libqt5concurrent5 but it is not installable
                   Depends: ocqt5101-libqt5core5a but it is not installable
                   Depends: ocqt5101-libqt5dbus5 but it is not installable
                   Depends: ocqt5101-libqt5gui5 but it is not installable
                   Depends: ocqt5101-libqt5keychain1 but it is not installable
                   Depends: ocqt5101-libqt5network5 but it is not installable
                   Depends: ocqt5101-libqt5webkit5 but it is not installable
                   Depends: ocqt5101-libqt5widgets5 but it is not installable
                   Depends: ocqt5101-libqt5xml5 but it is not installable
                   Depends: owncloud-client-l10n but it is not going to be installed
                   Depends: ocqt5101-libqt5sql5-sqlite but it is not installable
                   Depends: ocqt5101-qtsvg5 but it is not installable
E: Unable to correct problems, you have held broken packages.
root@6841c8883e28:/# history
    1  apt update && apt install wget -y && apt-get install gnupg2 --no-install-recommends -y
    2  wget -nv https://download.opensuse.org/repositories/isv:ownCloud:desktop/Debian_9.0/Release.key -O Release.key
    3  apt-key add - < Release.key
    4  apt-get update
    5  echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Debian_9.0/ /' > /etc/apt/sources.list.d/isv:ownCloud:desktop.list
    6  apt-get update
    7  apt-get install owncloud-client
    8  history
```

@jnweiger for help…

**Comment by jnweiger** [comment]
Ouch. We are preparing a 2.5.4 release. Publishing is disabled, but SUSE OBS has decided to push some updates through, already. Now http://download.opensuse.org/repositories/isv:/ownCloud:/desktop is in a broken state. Half 2.5.3 and half 2.5.4 sorry for this. I have fallen into that trap before. 

Please try https://build.opensuse.org/package/show/isv:ownCloud:desktop:client-2.5.3/owncloud-client
instead. That repository stays at 2.5.3

**Comment by jnweiger** [comment]
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop  should have 2.5.4 within the next one or two hours.

**Comment by frazy81** [comment]
@michaelstingl @jnweiger 

Thank you for the fast reply and workaround suggestion/solution! It works perfectly now.

Cheers, Philipp
