### ISSUE TITLE
Version 2.5: A HTTP transmission error happened. : The server file discovery reply is missing data.

### ISSUE THREAD

**Issue by JoKalliauer** [owncloud/client#7104]
### Expected behaviour
It should sync with server (Webservice works as expected)

### Actual behaviour
![Screenshot from 2019-03-18 13-40-39](https://user-images.githubusercontent.com/15687581/54743227-d8d42b00-4bc3-11e9-862e-e49c8c585bf6.png)

### Steps to reproduce
1. start owncloud version 2.5.3 or 2.5.4

### Server configuration

Web server: https://owncloud.tuwien.ac.at/index.php/login

Details: https://www.it.tuwien.ac.at/owncloud (Version 9.1.1)

### Client configuration
Client version: 2.5.3.(Win) and  2.5.4 (Linux)

Operating system: Windows 10 and Ubuntu 18.04

OS language: German (Win) and English (Linux)

### Workaround
Downgrade to 2.4.3, see
https://help.nextcloud.com/t/http-transmission-error/41620/14

Linux: https://software.opensuse.org/download/package?project=isv:ownCloud:desktop:client-2.4.3&package=owncloud-client

Windows: https://download.owncloud.com/desktop/stable/ownCloud-2.4.3.10188-setup.exe

**Comment by guruz** [comment]
@JoKalliauer Does it work with 2.5.4? (Which has HTTP2 disabled, maybe that's related)
https://github.com/owncloud/client/releases/tag/v2.5.4

**Comment by JoKalliauer** [comment]
@guruz :  I wrote `Client version: 2.5.3.(Win) and 2.5.4 (Linux)`
Therefore it did not work with 2.5.4 on Ubuntu. (I did not try on Windows.)

**Comment by cyryllo** [comment]
In my case, I use external authorization via imap (external_users). With every major update nextloud I have this problem until I log in. Then accounts with external authorization disappear. And shared catalogs disappear with them. Logging in with clients via imap restores the user again and the shared directories.

There is a chance to get around it somehow? because it starts to be tiring with more users.

**Comment by michaelstingl** [comment]
> With every major update nextloud I have this problem until I log in.

@cyryllo This is the ownCloud repo 😉

**Comment by ckamm** [comment]
@JoKalliauer @cyryllo The error happens when the server does not send all data that is required for the sync client to work correctly. The size, permissions, etag or fileid are missing.

Note that the ownCloud Desktop client is not tested against nextcloud servers. Use a matching client-server pair!

**Comment by JoKalliauer** [comment]
@ckamm 
I use a matching client-server pair.

But the server seems to use owncloud?
https://www.it.tuwien.ac.at/owncloud

> Die Open Source Software [ownCloud](https://owncloud.org/) (derzeit Version 9.1.1) läuft auf TU.it-Servern

Text is german and means: The Open Source Software [ownCloud](https://owncloud.org/) (currently version 9.1.1) runs at TU.it-Servers

Therfore I do not understand your last sentence.

https://owncloud.tuwien.ac.at/index.php/login

**Comment by michaelstingl** [comment]
@JoKalliauer Looks like a server problem that can't be solved in the client. Please check with your admin.

**Comment by ckamm** [comment]
@JoKalliauer Ah, I mixed up the two reports then, sorry. You can figure out what data is missing exactly by looking at the "Missing properties" line in your client log file (https://doc.owncloud.org/desktop/2.5/troubleshooting.html#obtaining-the-client-log-file).

**Comment by JoKalliauer** [comment]
@ckamm :
I updated on Microsoft Windows [Version 10.0.17763.379]  to owncloud-client 2.5.4:

And got this log-files:

[20190325_2137_owncloud.log.0.gz](https://github.com/owncloud/client/files/3005416/20190325_2137_owncloud.log.0.gz)

[20190325_2138_owncloud.log.0.gz](https://github.com/owncloud/client/files/3005403/20190325_2138_owncloud.log.0.gz)

[20190325_2139_owncloud.log.0.log.zip](https://github.com/owncloud/client/files/3005412/20190325_2139_owncloud.log.0.log.zip)

**Comment by ckamm** [comment]
@JoKalliauer "Dropbox" and "DropboxTU" have no etag. Maybe reuploading, deleting or editing will fix the server data - otherwise you'll need to contact your server admin.

**Comment by JoKalliauer** [comment]
@ckamm 

How can I remove external storage?

![Screenshot from 2019-03-26 09-26-59](https://user-images.githubusercontent.com/15687581/54981820-9175e200-4fa9-11e9-9ef8-5fb742ffc404.png)

![Screenshot from 2019-03-26 09-27-11](https://user-images.githubusercontent.com/15687581/54981828-95096900-4fa9-11e9-8d85-1b47fc292a8e.png)

![Screenshot from 2019-03-26 09-27-20](https://user-images.githubusercontent.com/15687581/54981830-96d32c80-4fa9-11e9-9fc3-a8454775f8e7.png)

I looked at
- https://doc.owncloud.com/server/admin_manual/configuration/files/external_storage_configuration_gui.html
- https://www.howtoforge.com/tutorial/how-to-add-external-storage-to-owncloud-9/

but my preferences/settings do look different.

**Comment by ckamm** [comment]
@JoKalliauer I don't know. Potentially a server configuration issue? Server admin can probably help.

**Comment by guruz** [comment]
> @JoKalliauer "Dropbox" and "DropboxTU" have no etag.

Maybe this is fixed with a newer version of https://github.com/owncloud/files_external_dropbox/ ?
ownCloud 9 is also not very current anymore..

**Comment by JoKalliauer** [comment]
I think the homepage is outdated, and we have a newer owncloud-version.

https://owncloud.tuwien.ac.at/status.php 

  |  
-- | --
installed | true
maintenance | false
needsDbUpgrade | false
version | "10.1.0.4"
versionstring | "10.1.0"
edition | "Enterprise"
productname | "ownCloud TU Wien"

I did not get any E-Mail reply till now from the help-desk of my university (=server-administrator). I might call/visit them.

**Comment by JoKalliauer** [comment]
The University updated (also the website-info https://www.it.tuwien.ac.at/owncloud ) to `Version 10.1`.

I got an E-Mail from the help-desk that due to the [PGDR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) external mounts are supposedly not allowed any more. But the E-Mail did not contain anything relevant for bugsolving.

I think the University restricted/banned the usage of external mounts, since due to the [PGDR](https://en.wikipedia.org/wiki/General_Data_Protection_Regulation) **most** external storages (such as Dropbox, Google Drive, Onedrive) are not allowed for data than can be related to **personal data**.

Bud sadly the University disabled external storages in such a way that even unmounting is not possible. Is there an alternative way to remove/unmount external storages, that I could try?

Anyway it is still unclear if the external mounts are the problem for not syncing.

**Comment by JoKalliauer** [comment]
The Service Center of the University removed the external mounts and everything works fine now. Thanks!

**Comment by michaelstingl** [comment]
@JoKalliauer glad to hear – have a great weekend!

**Comment by ashleydrees** [comment]
Searching for a resolution to my issue I ended up here, I am setting up Nextcloud 16.0.5 to use external SMB resources, I was trying out different settings and mounts and now I am completely unable to add any SMB external resources that can sync with Nextcloud Client  Version 2.6.0stable, the moment i add an external SMB resource - it shows up in a web browser fine but the Nextcloud Client always fails with the above error... removing the external SMB resource removes the error and the NC Client can sync again... adding new different named SMB External resources all have the same effect.

**Comment by ashleydrees** [comment]
After reading a lot more about it and trying to get it working for some hours.  I tried the OC Client 2.5.4 build 11456, which does not have an issue with the external SMB mounted drive but does complain about the "Server version 16.0.5.1-nextcloud is unsupported! proceed at your own risk" well i did and it now works... i will drop back to the NextCLOUD client and see if that is still broken.
