### ISSUE TITLE
[CentOS] Package ocqt5121-sqlite3-devel replaces sqlite3-devel

### ISSUE THREAD

**Issue by nlurkin** [owncloud/client#7105]
### Expected behaviour
Install package ocqt5121-sqlite3-devel-3.26.0-2.1.x86_64 besides the standard sqlite3-devel package

### Actual behaviour
The package ocqt5121-sqlite3-devel-3.26.0-2.1.x86_64 was installed and replaced the standard sqlite3-devel package.

### Steps to reproduce
1. sudo yum update

### Client configuration
Client version: 2.5.4
Operating system: Centos 7
OS language: English
Qt version used by client package (Linux only, see also Settings dialog): 5.12.1
Client package (From ownCloud or distro) (Linux only): isv_ownCloud_desktop
Installation path of client: default

### 
I need sqlite3-devel for code development. Howerver the ocqt5121-sqlite3-devel replaces the standard package, but the location of the headers and libraries are non-standard (/opt/ownCloud/qt-5.12.1/include/ and /opt/ownCloud/qt-5.12.1/lib64/). Therefore my code fails to compile unless I hardcode these paths in my cmake file (which is not possible since this code is usually compiled by the rest of the team on systems that have things in standard paths)

**Comment by jnweiger** [comment]
System sqlite3 and ocqt5121-sqlite3 should happily co-exist. Ours is not meant as a replacement.

**Comment by guruz** [comment]
https://build.opensuse.org/package/view_file/isv:ownCloud:desktop/ocqt5121-sqlite3/debian.control?expand=1
> Provides: libsqlite3-dev

**Comment by jnweiger** [comment]
Ouch. Patched these conflicting provides away. Rebuilds triggered.
-Provides:       %{oname}-devel = %{version}
-Obsoletes:      %{oname}-devel < %{version}
-Provides:       %{oname}3-devel = %{version}
-Obsoletes:      %{oname}3-devel < %{version}

**Comment by jnweiger** [comment]
The 2.5.4 download repo now has ocqt5121-sqlite3-devel-3.26.0-3.1.x86_64.rpm
This one no longer conflicts with your system sqlite-devel libraries.

I can do:
```
yum update
 ...
rpm -qa | grep sqlite
 ocqt5121-sqlite3-3.26.0-3.1.x86_64
 sqlite-3.7.17-8.el7.x86_64
 sqlite-devel-3.7.17-8.el7.x86_64
 ocqt5121-libsqlite3-0-3.26.0-3.1.x86_64
 ocqt5121-sqlite3-devel-3.26.0-3.1.x86_64
```

closed fixed.

**Comment by guruz** [comment]
@nlurkin  Please test

**Comment by nlurkin** [comment]
I confirm it is fixed. Thank you
