### ISSUE TITLE
2.5.4 not working on macOS 10.11

### ISSUE THREAD

**Issue by s1a3ti** [owncloud/client#7106]
The desktop client version 2.5.4 does not work anymore on macOS 10.11.

I get the following error:

Sorry, "owncloud" can not be run on this version of macOS. Qt requires macOS 10.12.0 or later, you have macOS 10.11.6.

Thank you!

**Comment by guruz** [comment]
@s1a3ti Thanks for reporting. We'll discuss internally how we can bring builds with the old Qt (and possibly old build machine) back as additional download options.

**Comment by sbgraphic** [comment]
Hi, same issue here but no message, except in the log:

`29.03.19 12:26:40.333 pkd[493]: enabling pid=481 for plug-in com.owncloud.desktopclient.FinderSyncExt(1.0) 8AAF8C6D-CFDE-4BCC-A662-C912268552BF /Applications/owncloud.app/Contents/PlugIns/FinderSyncExt.appex
`
Best,
Eric

**Comment by warmsocks** [comment]
I'm seeing the same issue with the same version (3.5.4) on the same OS after accepting an update dialog box from the previous version.  I'm on a Mac Pro Early 2008, which is still a plenty awesome fast productive machine, but Apple doesn't support anything newer then El Capitan/10.11 on it, so I'm stuck with the Web UI for now.  I would love to see support for the desktop client on 10.11 fixed.

In the meantime, a few suggestions:

1. The desktop app should not offer to install an update that will not run on the current OS.

2. If run from the terminal as `/Applications/owncloud.app/Contents/MacOS$ owncloud` the desktop app does print the message "Sorry, "owncloud" can not be run on this version of macOS. Qt requires macOS 10.12.0 or later, you have macOS 10.11.6." However the message should be logged to the Mac console too (as @sbgraphic noted, this is not the case; the console message is not helpful), and very preferably shown in a popup dialog when the user starts the app.

3. Even though the desktop app doesn't run, Activity Monitor shows ownCloud Extensions is running, but it doesn't appear to be doing anything useful; it certainly isn't synchronizing my local folder with the server.  If the desktop app isn't going to run, it doesn't seem like the Extensions should be running either.  Maybe disable them on boot/have the desktop client stop them after showing the "Cannot run on 10.11..." message?

Best,
Shaun

**Comment by jnweiger** [comment]
http://download.owncloud.com/desktop/daily/testpilotcloud-qt5.10.1-2.5.5.11542-daily20190404.pkg
was built with an older qt version. This might work. on macOS 10.11.6 -- cannot test myself.

**Comment by warmsocks** [comment]
@jnweiger,

> http://download.owncloud.com/desktop/daily/testpilotcloud-qt5.10.1-2.5.5.11542-daily20190404.pkg
> was built with an older qt version. This might work. on macOS 10.11.6 -- cannot test myself.

I tried it on Mac 10.11.6 and it worked perfectly--connected to our server and synced my files immediately.  Very nice!

**Comment by jnweiger** [comment]
I am wondering what the influence of the environment variable DEPLOYMENT_TARGET=10.10
is. With client version 2.6.x this will be DEPLOYMENT_TARGET=10.12

Would that again exclude El Capitan users?

**Comment by s1a3ti** [comment]
@jnweiger I tested the following version:
testpilotcloud-2.6.0.11546-daily20190404.pkg

It installs fine, but I get the following error in the terminal:

VM-El-Capitan:~ ch$ /Applications/testpilotcloud.app/Contents/MacOS/testpilotcloud
Sorry, "testpilotcloud" can not be run on this version of macOS. Qt requires macOS 10.12.0 or later, you have macOS 10.11.6.

**Comment by jnweiger** [comment]
Upcoming daily builds could have two distinct deliverables. the normal one, and the ElCapitan compatibility build (using qt-5.10.1) How about this:

SSH: put [testpilotcloud-2.6.0.11548-daily20190404.pkg]
SSH: put [testpilotcloud-2.6.0.11548-daily20190404.pkg.tbz]
SSH: put [testpilotcloud-2.6.0.11548-daily20190404.pkg.tbz.sig]
SSH: put [testpilotcloud-osx10.11-2.6.0.11548-daily20190404.pkg]
SSH: put [testpilotcloud-osx10.11-2.6.0.11548-daily20190404.pkg.tbz]
SSH: put [testpilotcloud-osx10.11-2.6.0.11548-daily20190404.pkg.tbz.sig]

**Comment by jnweiger** [comment]
@s1a3ti that is the one for you: testpilotcloud-osx10.11-2.6.0.11548-daily20190404.pkg

**Comment by s1a3ti** [comment]
@jnweiger Here is the result: 
![1 181 14-03-22 04 04 2019](https://user-images.githubusercontent.com/36929829/55554239-95f57580-56e2-11e9-8699-584ba42c1f29.png)

I guess, DEPLOYMENT_TARGET does matter.

**Comment by jnweiger** [comment]
Thanks for testing! 'starting from command line' means starting the normal gui client from a shell? Or is that about the testpilotcloudcmd client?

@guruz , what do you think, can we set DEVELOPMENT_TARGET=10.10 for a 2.6.x legacy build?
Do we have other dependencies in the new code that would break on 10.11?

**Comment by s1a3ti** [comment]
@jnweiger I'm starting the gui client from the terminal app:

VM-El-Capitan:Contents ch$ /Applications/testpilotcloud.app/Contents/MacOS/testpilotcloud
m_crashReporterChar:  /Applications/testpilotcloud.app/Contents/MacOS/testpilotcloud_crash_reporter

**Comment by guruz** [comment]
@dschmidt Can you jump in here?
Do you need to adapt the build scripts to set the DEVELOPMENT_TARGET variable too (not only the Qt configuration)?

**Comment by dschmidt** [comment]
Yes, I can take care. 

Probably yes. Setting the target based on the qt version.

**Comment by michaelstingl** [comment]
Here's the 2.5.4 build for OS X 10.10 and 10.11:
https://download.owncloud.com/desktop/stable/ownCloud-osx10.11-2.5.4.11669.pkg

**Comment by s1a3ti** [comment]
@michaelstingl Works fine on my 10.11. machines. Thank you!

**Comment by RobFog** [comment]
The version offered for download at the website doesn't seem to differentiate between a version for 10.10 and 10.11, and a version for 10.12+: https://owncloud.org/download/#owncloud-desktop-client-macos Does that version work on 10.11 and 10.10? If not, shouldn't the version requirement ("Mac OS X 10.10+ (64-bit only)") be changed accordingly?

**Comment by jnweiger** [comment]
@RobFog Thanks for the hint!
System requirements updated.

We need to restructure the download page somewhat, so that it reflects the two builds that we have properly. @hurradieweltgehtunter can you please have a look?

Meanwhile, I misused the 'technical preview' entry to publish the link for the osx1.11 build.
![grafik](https://user-images.githubusercontent.com/1108546/56816627-2e939700-6844-11e9-87df-849fb3b731b2.png)

**Comment by RobFog** [comment]
You're welcome. :-)

**Comment by tessus** [comment]
@jnweiger The DEPLOYMENT_TARGET specifies the minimum OS version the binary will run on.

So, if it is set to 10.12, it won't run on 10.11.

**Comment by michaelstingl** [comment]
ownCloud desktop sync client or macOS 10.10 and 10.11 is available on the website:
https://owncloud.org/download/#owncloud-desktop-client
(only text is wrong)
