### ISSUE TITLE
Smoke test 2.5.4  with Qt 5.10 on macOS

### ISSUE THREAD

**Issue by dschmidt** [owncloud/client#7114]
Related https://github.com/owncloud/client/issues/7106

See /job/client-osx/11503/

**Comment by jnweiger** [comment]
#tested owncloud-client-2.5.4.11503 on osx mojave
works fine. syncs files, start stop, folder erase, virtual files, ..

**Comment by jnweiger** [comment]
@dschmidt @michaelstingl what is the oldest test machine we have?

**Comment by guruz** [comment]
I think it's perfectly fine to let @s1a3ti test that build.
@jnweiger Can you put it into our download server (maybe with file name indicating that it's not a regular build)

**Comment by s1a3ti** [comment]
@guruz I can test the build on macOS 10.11. We are still using some machines with 10.11.

**Comment by jnweiger** [comment]
2.5.4, 2.5.5  got browser integration back. https://github.com/owncloud/enterprise/issues/3253
there was a broken patch in our internal toolchain. 

As far as qt-5.10.1 is concerned: several clients on 10.13 and 10.14 tested. all behaved well here.

**Comment by s1a3ti** [comment]
@jnweiger Can I download a test version somewhere? So I can test it on 10.11?

**Comment by jnweiger** [comment]
http://download.owncloud.com/desktop/daily/testpilotcloud-qt5.10.1-2.5.5.11542-daily20190404.pkg
This is a fresh build. I can no longer access the original build 11503.

**Comment by s1a3ti** [comment]
@jnweiger Thank you! Works like a charm. Tested creating and deleting files and folders.

**Comment by jnweiger** [comment]
thanks for testing.
