### ISSUE TITLE
OwnCloud Client 2.5.4: Wrong last change date of directories when using VFS

### ISSUE THREAD

**Issue by herrep** [owncloud/client#7116]
Expected behaviour:
When synchronizing directories using VFS, each newly created directory on an OwnCloud client shall have a last change date that is identical to the last change date of the directory on the server.

Actual behaviour:
When synchronizing directories using VFS, each newly created directory, at least at a Mac client, has a last change date which corresponds to the point of time when they directory is created at the client. In contrast, the synchonized files do not show this behavior: All files are synchronized according to their original last change date, but not the directories.

**Comment by michaelstingl** [comment]
This is the case for a long time, long before VFS. Not only with ownCloud, also with other solutions.

Related: https://github.com/owncloud/core/issues/7009

**Comment by herrep** [comment]
I fully understand the decision to not synchronize modification dates of directories. As a side effect, bandwidth is preserved. Fine. Nevertheless, I suggest an improvement that appears to have little impact on performance and adds great value when synchronizing storages with a lot of directories that are not toiched at all for a long time: See issue #7119

**Comment by ckamm** [comment]
Thanks for rephrasing as enhancement!
