### ISSUE TITLE
CentOS 7.5 support

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7118]
We build and test owncloud-client 2.5.4 on CentOS 7.6

This leads to issues when users try to run it on CentOS_7.5 as detailled here:
https://central.owncloud.org/t/unable-to-start-desktop-client-symbol-lookup-error-libqt5xcbqpa-so-5-undefined-symbol-ft-get-font-format/19250

Technically CentOS 7.5 support would need bundling more libraries with our product. At least the system libfreetyp is too old.

Maybe we can rename our CentOS_7 platform into CentOS_7.6 to better set expectations. But dropping a well known name could have bad side effects too...

Same logic probably applies to all the one digit platforms we support. We have to expect that the openSUSE Build service regularly deploys platform updates without reflecting this in the names.

**Comment by michaelstingl** [comment]
> Maybe we can rename our CentOS_7 platform into CentOS_7.6 to better set expectations.

Yes, sounds like a plan 👍

**Comment by jnweiger** [comment]
Renamed the obs repo CentOS_7 to CentOS_7.6
Adapted the lient/linux-docker-install testsuite to install from the CentOS_7.6 repo when the base OS is CentOS_7 . Let's see if that works with tomorrow's dailes.

**Comment by jnweiger** [comment]
@michaelstingl We need to revert this. 
It is utterly more confusing then expected. Sorry for this. Users wait for CentOS_7.8 to appear and things.
