### ISSUE TITLE
SSL handshake error with OSX client

### ISSUE THREAD

**Issue by clayton256** [owncloud/client#712]
The OSX client used to connect but I don't know when it stopped working. It now fails to connect to an owncloud install on my web hosting site (bluehost.com). I get error "SSL handshake failed".
The client log shows:
06-19 11:08:54:414 ownCloudInfo Network Error:  6 
06-19 11:08:54:414 status.php returns:  ""   6  Reply:  QNetworkReplyImpl(0x1015b3be0) 
06-19 11:08:54:414 No proper answer on  "https://box282.bluehost.com/~m/owncloud/status.php/status.php" 

If I run curl on that url, it get, what looks like a valid OC response:
$curl -3 https://box282.bluehost.com/~m/owncloud/status.php
{"installed":"true","version":"5.0.12","versionstring":"5.0.7","edition":""}$

The linux (Ubuntu 13.04) client works fine. 

I don't see anything interesting in the server logs.

owncloud 5.0.7
OSX clients 1.3.0beta3 and 1.2.5
PHP 5.4.15
Apache 2.2.24
openssh 5.3p1

**Comment by timtelcik** [comment]
Hello All, 

just in case it's helpful to another reader of this thread, I bumped into a similar issue, an SSL SNI handshake error.

My SSL handshake error manifested as follows:

{code}
$ git clone https://GIT-HOST/GIT-PROJECT.git
Cloning into 'GIT-PROJECT'...
fatal: unable to access 'https://GIT-HOST/GIT-PROJECT.git/': SSL peer handshake failed, the server most likely requires a client certificate to connect
{code}


My local Mac development environment:

* Mac OS : Mac OS Sierra (10.12.2)
* Git client : 2.10.1 (downloaded from Git sourforge, not the default Apple Mac OS release)
* Open SSL : OpenSSL 1.0.2j  26 Sep 2016
* Package manager : Mac Port (not Brew)


I resolved the SSL SNI handshake error as follows:

1/ Upgraded openssl resources for Mac Port

{code}
sudo pip install ndg-httpsclient pyasn1
sudo pip install ndg-httpsclient pyasn1 --upgrade
{code}


2/ Upgraded Apple XCode developers tools

e.g.

{code}
xcode-select --install
{code}


3/ Update Git client configuration

Edit file $HOME/.gitconfig and change "sslvertify" from "false" to "true"

From ...

{code}
...

[http]
	postBuffer = 209715200
	sslverify = false
	
....
{code}	

To ...

{code}
...

[http]
	postBuffer = 209715200
	sslverify = true
	
....
{code}	


Some helpful references:

* How to upgrade OpenSSL in OS X?
** http://apple.stackexchange.com/questions/126830/how-to-upgrade-openssl-in-os-x

* Command Line Tools bash (git) not working - macOS Sierra final release candidate
** http://stackoverflow.com/questions/39484218/command-line-tools-bash-git-not-working-macos-sierra-final-release-candidate

* kennethreitz requests - https GET request fails with "handshake failure" #2022
** https://github.com/kennethreitz/requests/issues/2022#issuecomment-133204955



Regards,

Tim

email: telcik@gmail.com

**Comment by chscorpio** [comment]
Instead of wireshark, here is a simpler way to reveal this issue if you have openssl...

```
$ openssl s_client -servername domain.com -connect domain.com:443 -state
CONNECTED(00000003)
SSL_connect:before/connect initialization
SSL_connect:SSLv2/v3 write client hello A
SSL3 alert read:warning:unrecognized name
SSL_connect:SSLv3 read server hello A
```
