### ISSUE TITLE
xdg-open is deprecated

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7121]
While testing 2.5.4 on CentOS-7.6

Messages on the console appear, when I right click open folder on the sync folder:

```
This tool has been deprecated, use 'gio open' instead.
See 'gio help open' for more info.
```

That apparently comes from xdg-open.

**Comment by ckamm** [comment]
Apparently the deprecation message comes from gvfs-open which xdg-open calls (over gio open, which is supposedly a bug in xdg-open). xdg-open itself is not deprecated. See https://github.com/github/hub/issues/1473#issuecomment-303656214
