### ISSUE TITLE
Requesting download of virtual file in subfolder doesn't trigger local discovery

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7124]
When double-clicking a virtual file or using the context menu to trigger a download that doesn't mark the path for local discovery. That means that a follow-up sync might not pick up on it and the requested hydration does not happen.

**Comment by ckamm** [comment]
QA:
- use suffix vfs
- in subfolder, double click one file, right-click and trigger download on another
- verify that the next sync actually performs the hydration

**Comment by michaelstingl** [comment]
@ckamm no relevance for 2.6? just close?
