### ISSUE TITLE
Owncloud Client 2.5.4: Enhancement for Download Directory (VFS)

### ISSUE THREAD

**Issue by herrep** [owncloud/client#7129]
When working with VFS, I encountered some difficulties to synchronize more important and less important directories. For the more important directories, I would expect an automatic download of all files, also for newly created files in these directories, whereas in less important directories, everything may remain in placeholder files which can be accessed on demand.

I expected to handle this functionality by applying the context menu function "Download" to the more important directories. Indeed, I got the files of these directories locally stored. But then I recognized certain drawbacks, as newly added files in the more important directories did not automatically got downloaded.

## Expected behaviour:
When selecting a directory in the Owncloud Client and applying the context menu function "Download", then all available files in this directory are downloaded. Once new files will be stored on the server, also new upcoming files shall be downloaded. Preferably, two different functions are available, i.e. one download function that downloads all present and future files once they are created, and the currently existing download function that works only on-demand, i.e. only the presently available files are downloaded without any automatic downloading of new files, thereby arriving at mixed folders having downloaded files plus placeholer files (the newly added ones).

## Actual behaviour:
When selecting a directory in the Owncloud Client and applying the context menu function "Download", then all available files in this directory are downloaded. Once new files will be stored on the server, only the placeholder files are locally stored.

**Comment by ckamm** [comment]
In 2.6 we added "pin states" to items. They can now be always-local, online-only or unspecified and this state affects the hydration state of new remote files (new files in always-local folders will start out downloaded etc). That's controlled through the right-click menu actions.

You may be interested in checking out the 2.6 builds and providing early feedback (http://download.owncloud.com/desktop/daily/). There should also be an alpha release soon.
