### ISSUE TITLE
Add an indicator to show which vfs plugin is available

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7137]
When different plugins are available the client picks one. For debugging it'll be very useful to allow users to discover which plugin is in use without going through the log files. Adding an indicatior to the about dialog would be sufficient.

**Comment by michaelstingl** [comment]
> Adding an indicatior to the about dialog would be sufficient.

Works for me 👍

**Comment by ckamm** [comment]
@guruz @michaelstingl Does this seem good?
![image](https://user-images.githubusercontent.com/833306/55875278-06920b80-5b95-11e9-8fef-f1540b5ba8ee.png)
I'd just add it to the bottom as a small paragraph without translation.

**Comment by michaelstingl** [comment]
> Does this seem good?

yes
