### ISSUE TITLE
It is possible to delete a shared folder without privileges

### ISSUE THREAD

**Issue by lmaestro** [owncloud/client#714]
### Expected behaviour
If you have a share folder without any privileges,  you shouldn't be able to remove it

### Actual behaviour
If you have a share folder without any privileges, neither you cant edit nor remove

### Steps to reproduce
1. Open the desktop client
2. Access to your shared folder, where there are folders shared with you from other users without any privileges
3. Wait for the folder to synch to the web client and the desktop
4. Remove the one of the share folders
5. Check that this folder is not shown any longer on your sync folder

### Server configuration
{"installed":"true","version":"5.0.12","versionstring":"5.0.7 RC2","edition":"Enterprise"}
open suse 12.2 
sql lite

### Client configuration
ownCloud Client Version 1.3.0-nightly20130619beta3

Operating system:Mac 10.8.3

### Logs
```
Fatal 	PHP 	SQLSTATE[HY000]: General error: 5 database is locked at /srv/www/htdocs/owncloud/lib/db.php#961 	24 de junio de 2013 13:20 

```

This could be related to: https://github.com/owncloud/core/issues/3823

**Comment by Dianafg76** [comment]
I tested this issue and happen the same.
DESKTOP v1.8.2 (build 2417)
SERVER {"installed":true,"maintenance":false,"version":"8.0.2.0","versionstring":"8.0.2","edition":"Enterprise"}

**Comment by mcastroSG** [comment]
Hi hi:

## Test 1

**Steps executed:**

1. As user (user1) create a new folder at ownCloud shared folder (TEST1).
2. As user (user1) create inside a new txt file (test.txt). 
3. As user (user1) share without privileges first level folder (TEST1) with another user (user2).
4. Server syncs both clients.
5. As user (user2) delete txt file (test.txt) at client.

**Result**

It works fine. After delete the file ownCloud client is sync and file is restored. 

## Test2

**Steps executed:**

1. As user (user1) create a new folder at ownCloud shared folder (TEST1).
2. As user (user1) create inside a new folder (TEST2). 
3. As user (user1) share without privileges first level folder (TEST1) with another user (user2).
4. Server syncs both clients.
5. As user (user2) delete subfolder  (TEST2) at client.

**Result**

It works fine. After delete the subfolder ownCloud client is sync and subfolder is restored. 

## Test3

**Steps executed:**

1. As user (user1) create a new folder at ownCloud shared folder (TEST1).
2. As user (user1) create inside a new folder (TEST2). 
3. As user (user1) share without privileges first level folder (TEST1) with another user (user2).
4. Server syncs both clients.
5. As user (user2) delete folder  (TEST1) at client.

**Result**

It works fine. Once you delete the folder shared it is not synced again and is deleted from user2 server files and appears as not shared at user1 server files. 

Tested at: 

**Windows**
Client Version: Version 2.2.0-nightly20160419 (build 6002)
Client OS: Windows 10
Server Version: 9.0.1
Server OS: Ubuntu

**IOS**
Client Version: Version 2.2.0-nightly20160419 (build 3282)
Client OS: IOS El Capitan 10.11.4
Server Version: 9.0.1
Server OS: Ubuntu

Regards

**Comment by guruz** [comment]
Great, thanks!
