### ISSUE TITLE
wincfapi: database dotfiles have 'syncing' arrows

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7141]
## tested ownCloud-2.6.0.11775.11588-daily20190411.GPO.msi with vfs enabled on win10

![grafik](https://user-images.githubusercontent.com/1108546/56041257-9623ef80-5d38-11e9-812c-5b1bca25b5e8.png)

The client should not try to sync the database files.

**Comment by ckamm** [comment]
Ah, the problem is that to remove the "needs syncing" icon the client needs to explicitly set an "excluded" state on the files. It does that, but it looks like the files are recreated on sync, wiping that flag again.

**Comment by HanaGemela** [comment]
"Needs syncing" icon is visible in 2.6.0alpha1 (build 11573) after restart

Steps to recreate:
1) Stop the server
2) Restart the computer the client is running on
3) Check the "needs syncing" icons

Actual result: The icons are shown until the client is connected to the server. Then the icons disappear. 
Expected result: The client should not try to sync the database files.

**Comment by ckamm** [comment]
@HanaGemela Thanks for the test, I see the problem - my fix only addresses things after the first sync has completed.

**Comment by ckamm** [comment]
With the new patch the icon does not appear or appears very briefly even if the sync folder is paused on startup.

**Comment by HanaGemela** [comment]
# Tested
Tested on windows with 2.6.0daily20190429 (build 11644)
Syncing arrows don't appear against the files mentioned above
