### ISSUE TITLE
wincfapi: right click menu not deterministic

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7142]
## tested ownCloud-2.6.0.11775.11588-daily20190411.GPO.msi with vfs enabled on win10

This screenshot is a collage showing two types of right click menues.
To the left, the "good" menu with the owncloud sub-menu is seen, to the right, another one is seen, that is unexpexted and less helpful in our context "bad"

![grafik](https://user-images.githubusercontent.com/1108546/56041788-d899fc00-5d39-11e9-9fe0-23a45b3431fe.png)

When clicking on some text, the good one appears.
When clicking on whitespace between the texts, the bad one appears.
When clicking on the cloud icon, either one can appear. This apparently depends on the highlight status. If the entry was previously left-clicked, the blue highlight remains, and the good one appears. If the entry was not previously left-clicked, the blue highlight disappears and the bad one appears.

Can we make the region around the cloud icon react more like normal text?

**Comment by ckamm** [comment]
The right-click behavior is driven entirely by the file explorer and the os part of the cloud filter api, so there's nothing we can do.

**Comment by jnweiger** [comment]
ok. I already anticipated something like that. Thanks for checking.
