### ISSUE TITLE
wincfapi: right click text german translations are not in sync

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7143]
## tested ownCloud-2.6.0.11775.11588-daily20190411.GPO.msi with vfs enabled on win10

Good in the main menue: Immer auf diesem Gerät beibehalten, Speicherplatz freigeben.
English version of the same in the owncloud-sub-menu: Make always available locally, Free up local space.

It should be translated to german in both places. (And identical wording to reduce confusion)

![grafik](https://user-images.githubusercontent.com/1108546/56043171-046ab100-5d3d-11e9-9fe1-17c41f923562.png)

Also, in this example the item is virtual. Thus "Speicherplatz freigeben" in the main menue is grayed out. The corresponding entry in the owncloud-sub-menu should also be grayed out.

**Comment by jnweiger** [comment]
BTW: What is the purpose of 'Available online only'? It seems to be grayed out in both states.

**Comment by guruz** [comment]
See also discussions in https://github.com/owncloud/client/issues/7085#issuecomment-472739021 (?)

**Comment by ckamm** [comment]
Needs to be adjusted in transifex but that still points to the 2.5 branch.

The "Available online only" is a hack to show the current availability state. How could we make that clearer? "Currently: Available online only" maybe? (the shell integrations won't be updated to have checkmarked items, icons or submenus for 2.6)

**Comment by jnweiger** [comment]
Aha, so that grayed out text should be an indicator of current state. Hmm, that is counter intuitive, as 'grayed out' items usually are are temporarily impossible.

Another logic issue is: "Available online only" implies, that nothing can be freed locally. 
But the "Free up local Space" entry is there and it is **not** grayed out.

**Comment by ckamm** [comment]
I agree about disabling items not usually being used to convey the current state. We just don't have another good option in suffix-vfs right now. The indicator isn't necessary for winvfs since is has the icons.

And I see the problem with "Free up space". The code needs to distinguish `SomeDehydrated` from `AllDehydrated` to do this right.

**Comment by HanaGemela** [comment]
I see two issues in 2.6.0alpha1 (build 11573):
1) Translations are still missing - 'Make always available locally' and 'Free up local space' are still in English. Also the state is in English 
2)  'Free up local space' is always available (not greyed out) even if all files are virtual and 'Speicherplatz freigeben' is greyed out. See the screenshot below.

And one question - what states can I see in the ownCloud submenu? So far I've seen 'Some available online only' and 'Always available locally'. Should I get another state when e.g. all files are available online only?

![Unbenannt](https://user-images.githubusercontent.com/49001702/56589818-41a92b80-65e6-11e9-9c60-8f8b499064d3.png)

**Comment by HanaGemela** [comment]
I've retested with 2.6.0daily20190424 (build 11614):

1. Translations are still missing - 'Make always available locally' and 'Free up local space' are still in English. Also the current state is in English
2. 'Free up local space' is available in ownCloud submenu against ignored files (so are the other options)

**Comment by michaelstingl** [comment]
@HanaGemela We use Transifex for translation. You can check language completion here:
https://www.transifex.com/owncloud-org/owncloud/client-desktop/

Register with your account on GitHub.com, and @DeepDiver1975 can approve you as a translator for German and Czech…

**Comment by ckamm** [comment]
@HanaGemela The following are possible:
- "Currently always available locally" (pinned, always synced)
- "Currently available locally" (available, but not pinned)
- "Currently some available online only" (some available, some not)
- "Currently available online only" (all unavailable, independent of pin)

To get the "Currently available locally" state, have a folder with one file. Free up space to unpin. Then double click the file to implicitly hydrate it. Now the file is available, but is wasn't pinned by the user which means the platform may chose to dehydrate it in the future.

**Comment by ckamm** [comment]
I'm not taking care of adding the translations. Usually it doesn't make sense to have tickets about translations - one could have an infinite number of them. For this particular case we may want to reduce confusion by specifying some translations ourselves.

So the "PR available" and "ReadyToTest" labels I assign are only about the logic issue with the "Free up local space" menu action.

**Comment by HanaGemela** [comment]
@ckamm when I free up local space and then double click the file to implicitly hydrate it, when will the platform chose to dehydrate it in the future?

**Comment by ckamm** [comment]
@HanaGemela I don't know, unfortunately. It may be related to low-disk-space logic, but I've never seen a platform-triggered dehydration so far.

**Comment by HanaGemela** [comment]
VFS related context menu is translated to German in 2.6.0alpha2 (build 12097), Windows 10. Works as expected

@michaelstingl  @pmaier1 Do you want to change the translations to use the same text as Windows? If so, raise an enhancement issue or let me know and I'll do it

![image](https://user-images.githubusercontent.com/49001702/61639094-198ba000-ac9b-11e9-9765-bcd6e84aaf47.png)
