### ISSUE TITLE
wincfapi: Provide "More Info" in hydration error dialog

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7144]
## tested ownCloud-2.6.0.11775.11588-daily20190411.GPO.msi with vfs enabled on win10

![grafik](https://user-images.githubusercontent.com/1108546/56044680-07b36c00-5d40-11e9-9cf4-ca37706f1b2f.png)

The network connection to the server was lost. Is this an expected message?
Would we get one popup per file, when there are 10000 files?

**Comment by jnweiger** [comment]
Clicking on 'Mehr Details' does not do anything.

**Comment by jnweiger** [comment]
Or: 
Fehler 0x8007016A: Der Clouddateianbieter wird nicht ausgeführt.

**Comment by ckamm** [comment]
It's a windows-driven dialog that we have no control over. We may be able to fill "Mehr Details" though, let's make this ticket about that.
