### ISSUE TITLE
Client doesn't indicate that it is offline

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7160]
![Capture](https://user-images.githubusercontent.com/49001702/56578314-a86e1b00-65cd-11e9-8614-37ed3a04e801.PNG)

Found in 2.6.0alpha1 (build 11573)

Steps to recreate:
1) Connect a client with a server
2) Stop the server
3) Check if the client is connected to the server

Actual result: Client still seems to be connected to the server
Expected result: Client indicates that it is offline

**Comment by ckamm** [comment]
I can reproduce. Interestingly it only happenend the second time I stopped my server.  The key log message probably is:

```
[ OCC::AccountState::checkConnectivity ]:       "admin@192.168.0.195" The last ETag check succeeded within the last  30  secs. No connection check needed!
```

**Comment by HanaGemela** [comment]
When the server is turned off, the client goes offline in the reasonable amount of time
Tested in 2.6.0alpha2 (build 12128), macOS 10.14.5
