### ISSUE TITLE
Ignored files editor should include more instructions

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7162]
After adding a new pattern to Ignored files, a client has to be restarted. This should be mentioned in the description so that the users know when the changes will take effect

Steps to recreate:
1) Go to General tab in the client
2) Click on 'Edit Ignored Files' button
3) Click on Add button 
4) Add a new pattern
5) Click OK

Actual result: There is still the 'Needs syncing' icon in the file explorer against the ignored files
Expected result: User knows that the client has to be restarted to apply the changes

![Capture](https://user-images.githubusercontent.com/49001702/56716923-c6f22480-673b-11e9-97b3-0c33cd280a39.PNG)

**Comment by ckamm** [comment]
@HanaGemela No client restart should be necessary. The changes definitely affect the next sync (which is triggered automatically). So this is probably a bug in the icons. Did you test with or without vfs? On windows, I assume?

**Comment by HanaGemela** [comment]
On windows with vfs on 
So the expected result should be: There is no icon in file explorer as the files are ignored

**Comment by ckamm** [comment]
I tested like this but couldn't reproduce:
1. Add ignore pattern "ignoreme", click ok.
2. Add a file "ignoreme". Verify it has no icon after sync.
3. Rename to different file name, verify it syncs.
4. Rename back, verify icon is gone again.
5. Edit ignore pattern to "ignoreme2", click ok.
6. Verify file is synced.
7. Edit ignore pattern back, click ok.
8. Verify icon is gone after sync again.

**Comment by ogoffart** [comment]
maybe there was lots of file that needed to be synced.  Or the discovery phase was very slow.
So the sync takes time and that's why it seems that it did not work immediatly.
(we do not refresh the icons until we get a state change from the syncengine IIRC)

**Comment by guruz** [comment]
>  (we do not refresh the icons until we get a state change from the syncengine IIRC)

Kind of related:
https://github.com/owncloud/client/issues/5860
https://github.com/owncloud/client/issues/4731

**Comment by ckamm** [comment]
Could add a note along the lines of "changes take effect after the next time the folders are synchronized".

**Comment by ckamm** [comment]
Updated description label to:
> Files or folders matching a pattern will not be synchronized. Changes take effect the next time folders are synchronized.
> Items where deletion is allowed will be deleted if they prevent a directory from being removed. This is useful for meta data.

**Comment by ogoffart** [comment]
Is this now fixed?

**Comment by HanaGemela** [comment]
Works as expected in 2.6.1daily20191127 (build 12732), Windows 10
