### ISSUE TITLE
error buil opensuse leap 42.3

### ISSUE THREAD

**Issue by vectorez** [owncloud/client#7165]
Looked in the following places:
/home/user/build-win32/bin/FolderWatcherTest.exe
/home/user/build-win32/bin/FolderWatcherTest.exe
/home/user/build-win32/bin/Release/FolderWatcherTest.exe
/home/user/build-win32/bin/Release/FolderWatcherTest.exe
/home/user/build-win32/bin/Debug/FolderWatcherTest.exe
/home/user/build-win32/bin/Debug/FolderWatcherTest.exe
/home/user/build-win32/bin/MinSizeRel/FolderWatcherTest.exe
/home/user/build-win32/bin/MinSizeRel/FolderWatcherTest.exe
/home/user/build-win32/bin/RelWithDebInfo/FolderWatcherTest.exe
/home/user/build-win32/bin/RelWithDebInfo/FolderWatcherTest.exe
/home/user/build-win32/bin/Deployment/FolderWatcherTest.exe
/home/user/build-win32/bin/Deployment/FolderWatcherTest.exe
/home/user/build-win32/bin/Development/FolderWatcherTest.exe
/home/user/build-win32/bin/Development/FolderWatcherTest.exe
home/user/build-win32/bin/FolderWatcherTest.exe
home/user/build-win32/bin/FolderWatcherTest.exe
home/user/build-win32/bin/Release/FolderWatcherTest.exe
home/user/build-win32/bin/Release/FolderWatcherTest.exe
home/user/build-win32/bin/Debug/FolderWatcherTest.exe
home/user/build-win32/bin/Debug/FolderWatcherTest.exe
home/user/build-win32/bin/MinSizeRel/FolderWatcherTest.exe
home/user/build-win32/bin/MinSizeRel/FolderWatcherTest.exe
home/user/build-win32/bin/RelWithDebInfo/FolderWatcherTest.exe
home/user/build-win32/bin/RelWithDebInfo/FolderWatcherTest.exe
home/user/build-win32/bin/Deployment/FolderWatcherTest.exe
home/user/build-win32/bin/Deployment/FolderWatcherTest.exe
home/user/build-win32/bin/Development/FolderWatcherTest.exe
home/user/build-win32/bin/Development/FolderWatcherTest.exe
31/33 Test #31: FolderWatcherTest ................***Not Run   0.00 sec
      Start 32: FolderManTest
Could not find executable /home/user/build-win32/bin/FolderManTest.exe
Looked in the following places:
/home/user/build-win32/bin/FolderManTest.exe
/home/user/build-win32/bin/FolderManTest.exe
/home/user/build-win32/bin/Release/FolderManTest.exe
/home/user/build-win32/bin/Release/FolderManTest.exe
/home/user/build-win32/bin/Debug/FolderManTest.exe
/home/user/build-win32/bin/Debug/FolderManTest.exe
/home/user/build-win32/bin/MinSizeRel/FolderManTest.exe
/home/user/build-win32/bin/MinSizeRel/FolderManTest.exe
/home/user/build-win32/bin/RelWithDebInfo/FolderManTest.exe
/home/user/build-win32/bin/RelWithDebInfo/FolderManTest.exe
/home/user/build-win32/bin/Deployment/FolderManTest.exe
/home/user/build-win32/bin/Deployment/FolderManTest.exe
/home/user/build-win32/bin/Development/FolderManTest.exe
/home/user/build-win32/bin/Development/FolderManTest.exe
home/user/build-win32/bin/FolderManTest.exe
home/user/build-win32/bin/FolderManTest.exe
home/user/build-win32/bin/Release/FolderManTest.exe
home/user/build-win32/bin/Release/FolderManTest.exe
home/user/build-win32/bin/Debug/FolderManTest.exe
home/user/build-win32/bin/Debug/FolderManTest.exe
home/user/build-win32/bin/MinSizeRel/FolderManTest.exe
home/user/build-win32/bin/MinSizeRel/FolderManTest.exe
home/user/build-win32/bin/RelWithDebInfo/FolderManTest.exe
home/user/build-win32/bin/RelWithDebInfo/FolderManTest.exe
home/user/build-win32/bin/Deployment/FolderManTest.exe
home/user/build-win32/bin/Deployment/FolderManTest.exe
home/user/build-win32/bin/Development/FolderManTest.exe
home/user/build-win32/bin/Development/FolderManTest.exe
32/33 Test #32: FolderManTest ....................***Not Run   0.00 sec
      Start 33: OAuthTest
Could not find executable /home/user/build-win32/bin/OAuthTest.exe
Looked in the following places:
/home/user/build-win32/bin/OAuthTest.exe
/home/user/build-win32/bin/OAuthTest.exe
/home/user/build-win32/bin/Release/OAuthTest.exe
/home/user/build-win32/bin/Release/OAuthTest.exe
/home/user/build-win32/bin/Debug/OAuthTest.exe
/home/user/build-win32/bin/Debug/OAuthTest.exe
/home/user/build-win32/bin/MinSizeRel/OAuthTest.exe
/home/user/build-win32/bin/MinSizeRel/OAuthTest.exe
/home/user/build-win32/bin/RelWithDebInfo/OAuthTest.exe
/home/user/build-win32/bin/RelWithDebInfo/OAuthTest.exe
/home/user/build-win32/bin/Deployment/OAuthTest.exe
/home/user/build-win32/bin/Deployment/OAuthTest.exe
/home/user/build-win32/bin/Development/OAuthTest.exe
/home/user/build-win32/bin/Development/OAuthTest.exe
home/user/build-win32/bin/OAuthTest.exe
home/user/build-win32/bin/OAuthTest.exe
home/user/build-win32/bin/Release/OAuthTest.exe
home/user/build-win32/bin/Release/OAuthTest.exe
home/user/build-win32/bin/Debug/OAuthTest.exe
home/user/build-win32/bin/Debug/OAuthTest.exe
home/user/build-win32/bin/MinSizeRel/OAuthTest.exe
home/user/build-win32/bin/MinSizeRel/OAuthTest.exe
home/user/build-win32/bin/RelWithDebInfo/OAuthTest.exe
home/user/build-win32/bin/RelWithDebInfo/OAuthTest.exe
home/user/build-win32/bin/Deployment/OAuthTest.exe
home/user/build-win32/bin/Deployment/OAuthTest.exe
home/user/build-win32/bin/Development/OAuthTest.exe
home/user/build-win32/bin/Development/OAuthTest.exe
Unable to find executable: /home/user/build-win32/bin/LockedFilesTest.exe
Unable to find executable: /home/user/build-win32/bin/FolderWatcherTest.exe
Unable to find executable: /home/user/build-win32/bin/FolderManTest.exe
Unable to find executable: /home/user/build-win32/bin/OAuthTest.exe
Errors while running CTest
33/33 Test #33: OAuthTest ........................***Not Run   0.00 sec

0% tests passed, 33 tests failed out of 33

Total Test time (real) =   0.02 sec

The following tests FAILED:
          1 - OwncloudPropagatorTest (Not Run)
          2 - UpdaterTest (Not Run)
          3 - NetrcParserTest (Not Run)
          4 - OwnSqlTest (Not Run)
          5 - SyncJournalDBTest (Not Run)
          6 - SyncFileItemTest (Not Run)
          7 - ConcatUrlTest (Not Run)
          8 - XmlParseTest (Not Run)
          9 - ChecksumValidatorTest (Not Run)
         10 - ExcludedFilesTest (Not Run)
         11 - UtilityTest (Not Run)
         12 - SyncEngineTest (Not Run)
         13 - SyncVirtualFilesTest (Not Run)
         14 - SyncMoveTest (Not Run)
         15 - SyncDeleteTest (Not Run)
         16 - SyncConflictTest (Not Run)
         17 - SyncFileStatusTrackerTest (Not Run)
         18 - DownloadTest (Not Run)
         19 - ChunkingNgTest (Not Run)
         20 - ZsyncTest (Not Run)
         21 - AsyncOpTest (Not Run)
         22 - UploadResetTest (Not Run)
         23 - AllFilesDeletedTest (Not Run)
         24 - BlacklistTest (Not Run)
         25 - LocalDiscoveryTest (Not Run)
         26 - RemoteDiscoveryTest (Not Run)
         27 - PermissionsTest (Not Run)
         28 - SelectiveSyncTest (Not Run)
         29 - DatabaseErrorTest (Not Run)
         30 - LockedFilesTest (Not Run)
         31 - FolderWatcherTest (Not Run)
         32 - FolderManTest (Not Run)
         33 - OAuthTest (Not Run)

**Comment by ckamm** [comment]
What's the build error? You just show `make test` failing because your test binaries aren't present.

**Comment by TheOneRing** [comment]
Cross compiling is now longer supported, please give our current instructions a try https://doc.owncloud.org/desktop/building.html#windows-development-build-with-kde-craft
