### ISSUE TITLE
Can't open a folder with logs on macOS

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7166]
Found on Mac in 2.6.0-daily20190426 (build 11674)

Steps to recreate:
1) Open a client
2) Pres F12 or Command+L to open 'Log Output' window
3) Click on 'Open folder' button 

Actual result: Nothing 
Expected result: Folder with logs has been opened 

<img width="611" alt="Screenshot 2019-04-26 at 15 00 55" src="https://user-images.githubusercontent.com/49001702/56809725-dbfeae80-6834-11e9-82c6-fd6e1c97ce79.png">

**Comment by michaelstingl** [comment]
@HanaGemela What exact macOS version?

**Comment by HanaGemela** [comment]
@michaelstingl 10.14.3

**Comment by ckamm** [comment]
@HanaGemela Could you try reproducing with a recent build? It's possible that it was addressed by the other log window fixes. (I don't have osx unfortunately)

**Comment by guruz** [comment]
I can confirm.

**Comment by HanaGemela** [comment]
Works as expected in 2.6.0alpha2 (build 12128), macOS 10.14.5
