### ISSUE TITLE
Typo in german message

### ISSUE THREAD

**Issue by mtx500** [owncloud/client#7167]
`<message>`
`        <location filename="../src/gui/folderman.cpp" line="1278"/>`
`        <source>Waiting to start syncing.</source>`
`        <translation>Wartet auf Beginn der Synchronistation</translation>`
`</message>`

Synchronis**t**ation should be Synchronisation

**Comment by ogoffart** [comment]
Hi, Thanks for reporting problem.
The translations are worked on and should be fixed on transifex.
https://www.transifex.com/owncloud-org/owncloud/
(The best would be if you could fix it there)

**Comment by mtx500** [comment]
Fixed it right now in transifex (plus some other typos), but I have no idea how and when this fix will make it into the client app. Some of my fixes I could only save as "suggestion" - what will happen with them?

**Comment by dschmidt** [comment]
I'm taking care

**Comment by dschmidt** [comment]
Should be fixed after the next run of translation-sync job. The latest in 24h.

**Comment by jnweiger** [comment]
Should be in by now. Please reopen if not.
