### ISSUE TITLE
Proxy settings are ignored without warning when connected to localhost 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7169]
Client: 2.6.0-daily20190429 (build 11690)
macOS 10.14.4

Steps to recreate:
1) Run ownCloud server and client on your machine
2) Connect the client to the server using localhost:8080
3) Set up the proxy in the Network tab in the client

Actual result: User can set proxy but this settings is ignored
Expected result: Logs mention that proxy settings has been ignored. Also user interface warns that proxy is not used - e.g. if connected to localhost and proxy has been set up, the Account tab displays 'Connected to http://localhost:8080 as admin (no proxy)'

**Comment by ckamm** [comment]
Indeed, proxys are not used for local host by Qt (see https://doc.qt.io/qt-5/qnetworkproxy.html#details). The client could notify about that.

**Comment by ogoffart** [comment]
How should we notify about it?  A label in the networksetting with a warning that is shown if at least one account has a localhost url?

**Comment by guruz** [comment]
Either that or in the label that mentions the account state for that specific localhost account?

**Comment by butonic** [comment]
um what is the rationale behind this? if I want to debug connections I locally run mitmproxy as well as my apache .... but how do I make the client use mitmproxy?

hm ok I had expected to make it use the proxy by giving it the public ip of my machine...  that did not work ... but using the public ip for the oc server did ...

:confused: ... anyway ... workaround is good enough ... maybe list this as a warning when running `owncloudcmd`...

**Comment by ogoffart** [comment]
> um what is the rationale behind this? 

I don't know. That's what the network library we are using (Qt) is doing.

I guess the rationale is maybe that network settings are used globally for things that need access to the internet, and localhost does not need that.

**Comment by ogoffart** [comment]
A warning was added when localhost is used as an host.
But we can't apply the proxy for localhost because Qt does not allow it.
