### ISSUE TITLE
2.6.0-alpha for macos does not mention it is an alpha

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7170]
Client 2.5.4rc1 running on macos 10.14 with update channel set to beta.
The client shows this popup when it detects a new release.

![grafik](https://user-images.githubusercontent.com/1108546/56968112-dc63b600-6b62-11e9-8193-0f8cfbd13320.png)

It looks like a finals 2.6.0 release is there. This is misleading. It should explicitly say 'alpha' to avoid confusion!

Side note:
it seems we have not enough space in the drop down menu to spell out 'stable'. The 'e' is missing here:
![grafik](https://user-images.githubusercontent.com/1108546/56968465-7b88ad80-6b63-11e9-8b48-c78864292819.png)

**Comment by jnweiger** [comment]
config/ownCloud.yml has

```
  macos-unstable:
    currentVersion: 2.6.0.11615
    currentVersionString: ownCloud Client 2.6.0 alpha1 (build 11615)
```
Should 'alpha1' be part of the the 'currentVersion' too?

**Comment by TheOneRing** [comment]
@jnweiger I think we can close this one?

**Comment by TheOneRing** [comment]
Closing this one, we don't need an alpha channel, we could talk about renaming beta to unstable....
