### ISSUE TITLE
macos 2.6.0-alpha cannot be installed via online update

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7171]
running 2.5.4-rc1 on macos 10.14 with update channel beta enabled.
The client detects there is an update and suggests:
![grafik](https://user-images.githubusercontent.com/1108546/56968987-7ed06900-6b64-11e9-8165-f02af18cdf46.png)

User clicks Install Update
ca 19MB are downloaded, then this error appears:
![grafik](https://user-images.githubusercontent.com/1108546/56969033-9ad40a80-6b64-11e9-84a6-689ae4e049a0.png)

@guruz we changed the from compressed pkg to plain pkg, didn't we? 
Um, 19MB is especially short. Other pkg files are 32MB.

**Comment by guruz** [comment]
>  Um, 19MB is especially short. Other pkg files are 32MB.

Then re-upload the correct .pkg?

**Comment by jnweiger** [comment]
![grafik](https://user-images.githubusercontent.com/1108546/57387051-ed8d7200-71b5-11e9-9dc5-56fffc5e39fc.png)

Success. Reconfigured the online updater to use *.pkg.tbz and *.pkg.tbz.sig instead.

**Comment by jnweiger** [comment]
Sparkle does not seem to work with plain *.pkg -- that is bad. We need to keep the *.pkg.tbz packages for this reason. @guruz Do we have the unpack tar bz step hard-coded somewhere in the online updater workflow?
