### ISSUE TITLE
Resend network requests on ContentReSendError

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7174]
Now that https://codereview.qt-project.org/#/c/254111/ is merged and will apear in Qt 5.12.4 we can prepare the client by catching the error and doing a manual resend. This will allow us to re-enable HTTP2 support once that Qt is available.

**Comment by ogoffart** [comment]
(moved to 2.6.1 since Qt 5.12.4 is not yet released)

**Comment by ckamm** [comment]
This is extremely hard to test, to the point where I would skip it. One needs to run with 5.12.4 and have a server that's enabled for http2 and sends GOAWAY frames in the way that triggers the Qt bug that used to exist.

**Comment by HanaGemela** [comment]
@ckamm How come all the platforms are using different version of Qt? 
macOS uses 5.12.1
Window uses Qt 5.12.4
Ubuntu uses Qt 5.12.2

Does this need testing on lower version than 5.12.4?

**Comment by ckamm** [comment]
@HanaGemela I don't know the exact reason. (@dschmidt ?)

This enhancement can only be tested with Qt >=5.12.4, can't test it with an earlier version.

**Comment by HanaGemela** [comment]
@ckamm does that mean that the client with Qt 5.12.4 has HTTP2 enabled by default? 
What if I'll connect it to the server that does not support it?
Do you know how to send GOAWAY frames in the way that triggers the Qt bug?

**Comment by ckamm** [comment]
@HanaGemela Yes, a 2.6.0 client with Qt >= 5.12.4 will check whether a server supports http2 and use it if possible. If the server doesn't support it will work as before.

GOAWAY: I think this nginx config triggered the issue, but only sometimes:
```
http2_max_concurrent_streams 2;
http2_max_requests 2;
http2_idle_timeout 3m;
```

**Comment by HanaGemela** [comment]
Closing as exact steps to recreate are not known.

**Comment by guruz** [comment]
> @ckamm How come all the platforms are using different version of Qt?

The Qt version is defined by the build systems not by the client source code :-)
We try to get this all to 5.12.4 though

**Comment by guruz** [comment]
@ckamm Please evaluate https://codereview.qt-project.org/c/qt/qtbase/+/272754 when you have the time..
