### ISSUE TITLE
2.6.0 Alpha1 virtual files mode - no preview/thumbnails in explorer for locally available files

### ISSUE THREAD

**Issue by lulle2007200** [owncloud/client#7175]
No previews for images etc. in windows explorer for downloaded files in owncloud virtual files mode.

### Expected behaviour
Explorer should display previews for downloaded files.

### Actual behaviour
Explorer only displays preview for files i just uploaded (just dropped into the sync folder). 
![right after dropping files in sync folder](https://user-images.githubusercontent.com/13625968/57185758-8a5bc100-6ed1-11e9-9878-52fa628d7782.png)

After refreshing explorer (F5, close and reopen etc.), previews for all files are gone. 
![after refresh](https://user-images.githubusercontent.com/13625968/57185762-a3647200-6ed1-11e9-9869-1dad84f1ee04.png)

No previews for any downloaded files.

### Steps to reproduce
0. Enable virtual files mode
1. Drag'n'drop image in sync folder.
2. Preview will be displayed.
3. Refresh explorer.
4. Preview disappears.
5. No preview for any file downloaded file.

### Server configuration
Operating system: Ubuntu 18.10

Web server:  Apache 2

Database: MySql

PHP version: 7.2

ownCloud version: 10.1.1

### Client configuration
Client version: 2.6.0 Alpha 1

Operating system: Windows 10 Pro
Using Windows 10 1809 (Buildnumber 17763).
I have a second machine running Windows 10 LTSC Build 17763, exact same behaviour.

OS language: DE

Qt version used by client package (Linux only, see also Settings dialog): - 

Client package (From ownCloud or distro) (Linux only): - 

Installation path of client: C:\program files (X86)

**Comment by michaelstingl** [comment]
What is the exact version / build of your Win 10 Pro?

**Comment by lulle2007200** [comment]
Using Windows 10 1809 (Buildnumber 17763).
I have a second machine running Windows 10 LTSC Build 17763, exact same behaviour.

**Comment by ckamm** [comment]
Interesting. Maybe some metadata forwarding needs to be done on the placeholder files.

**Comment by guruz** [comment]
https://docs.microsoft.com/en-us/windows/desktop/shell/thumbnail-providers

**Comment by TheOneRing** [comment]
https://docs.microsoft.com/en-us/windows/win32/cfapi/build-a-cloud-file-sync-engine a cloud file thumbnail provider is missing.
AFAIK it requires a msix or alternative Windows 10 installer.

**Comment by michaelstingl** [comment]
@lulle2007200 could you check again with the 2.7-beta2?
https://download.owncloud.com/desktop/ownCloud/testing/2.7.0.1947-v270beta2/

**Comment by Warlock667** [comment]
Although I am not lulle2007200 I tried 2.7-beta2, because I have the same problem.
In my case 2.7-beta2 did not help. Neither pictures that were uploaded before I upgraded to 2.7-beta2, nor pictures I uploaded after the upgrade have a thumbnail in Win10.
The thumbmail can only be seen for a short time after copying into the folder before it is synced. Right after the sync there is no thumbnail anymore.

**Comment by lulle2007200** [comment]
i currently dont have an owncloud server set up, will test in the next couple of days.

**Comment by TheOneRing** [comment]
> 
> 
> i currently dont have an owncloud server set up, will test in the next couple of days.

You can use https://demo.owncloud.com/login for testing.

**Comment by ParisGreen** [comment]
![Screenshot 2020-09-08 17 11 10](https://user-images.githubusercontent.com/8505474/92528266-7c6d2d00-f1f6-11ea-9b24-e07307333746.png)
I tried fiddling with this one a little myself, and it seems like windows only shows thumbnails for files that you've manually opened, even if they're set to locally available.

**Comment by TheOneRing** [comment]
Hmmm for some reason its working here.
@ParisGreen which version of windows is that and which client version?
(Windows version can be found out by running winver)

**Comment by Warlock667** [comment]
Just installed Windowsupdates and suddenly it works in my case.

Windowsversion: 1909 (Build 18363.1082)
OC Client Version: 2.7.0v27beta3 (build 1997)

Windowsupdates that were just installed are:

KB4576484
KB4574727

That's just awesome! :-)

**Comment by TheOneRing** [comment]
I was hoping that its not a ownCloud bug :D

**Comment by lulle2007200** [comment]
Just tried, seems to be working
