### ISSUE TITLE
Incorrect file path encoding in "If" header

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7176]
From https://github.com/owncloud/core/issues/34760

```
MOVE /owncloud-core/remote.php/dav/uploads/admin/3564657344/.file HTTP/1.1
Destination: /owncloud-core/remote.php/dav/files/admin/aa-%252F-aa.txt
If: </owncloud-core/remote.php/dav/files/admin/aa-%2F-aa.txt> (["b48e2c9c9b3fedce55c1ddcb600862a9"])
```

`Destination` and `If` have different paths.

**Comment by ckamm** [comment]
To test, upload changes to a large file that has a "%" in its name.

**Comment by jnweiger** [comment]
@ckamm, what does large mean? Is that chunked uploads?
Cant reproduce. My naive tests with such a file just seem to work fine with 2.6.0 RC3

**Comment by ckamm** [comment]
@jnweiger Yes, without the patch the error should appear in any file that is uploaded with chunked uploading. Note that the file must already be successfully synced before a change is made and the updates are uploaded - otherwise the `If` header isn't sent.

**Comment by guruz** [comment]
> 2.6.0 RC3

We're not even at the beta :)

**Comment by HanaGemela** [comment]
Paths in `Destination` and `If` are the same when chunk uploading 1G file with % in the name
Works as expected in 2.6.0alpha2 (build 12128), macOS 10.14.5
