### ISSUE TITLE
owncloudcmd: Please add an option to set log level output in console

### ISSUE THREAD

**Issue by ghost** [owncloud/client#7178]
There is too much output. I log everything to file and this quickly gets over 10mb. Please add an option to set the log level like:

--log-level debug (displays debug messages)
--log-level warn (displays warnings and errors)
--log-level error (displays only errors)

**Comment by ogoffart** [comment]
You can set the `QT_LOGGING_RULES` environment varialbe.

For example 
`QT_LOGGING_RULES="*.info=false" owncloudcmd ...`

See https://doc.qt.io/qt-5/qloggingcategory.html#logging-rules
