### ISSUE TITLE
docker run error response from daemon: OCI runtime create failed..

### ISSUE THREAD

**Issue by habelaid** [owncloud/client#7182]
hi everybody,
when i am trying to build the client for windows i receive this message:
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"/home/user/client/admin/win/docker/build.sh\": stat /home/user/client/admin/win/docker/build.sh: no such file or directory": unknown.
ERRO[0000] error waiting for container: context canceled 

i am in the second step of building client for windows. i can see the image on docker but when i try to run the comande 
docker run -v "$PWD:/home/user/client" owncloud-client-win32:2.5.4 /home/user/client/admin/win/docker/build.sh client/  $(id -u)
it doesn't work instead the error appears.
i am on opensuse 42.3.
thank you in advance

**Comment by michaelstingl** [comment]
@habelaid This is an issue tracker. For build support, please try https://central.owncloud.org/c/desktop

We recommend to build Win clients on Windows with the magic of KDE Craft:
https://github.com/owncloud/client/blob/master/docs/modules/ROOT/pages/building.adoc#windows-development-build-with-kde-craft

Check also this blog post:
https://owncloud.org/news/interview-kde-craft-improves-owncloud-client-build-process/

There was also some discussion in the forum:
https://central.owncloud.org/t/building-owncloud-client-on-windows-10/17730/2

**Comment by habelaid** [comment]
thanks michael have a good day!
