### ISSUE TITLE
Missing builds for Fedora 30

### ISSUE THREAD

**Issue by xoxys** [owncloud/client#7183]
Currently, there are no builds or repositories available for Fedora 30.

**Comment by jnweiger** [comment]
Fedora 30 build succeeded during the weekend.

*2.6.0 alpha1 is here: https://software.opensuse.org//download.html?project=isv%3AownCloud%3Adesktop%3Atesting&package=owncloud-client
* 2.5.x daily is here: https://software.opensuse.org//download.html?project=isv%3AownCloud%3Adesktop%3Adaily%3A2.5&package=owncloud-client
* the main download location as advertised via owncloud.org/download remains unchanged for now. the 2.5.4 release was before Fedora 30.

**Comment by jnweiger** [comment]
* https://software.opensuse.org//download.html?project=isv%3AownCloud%3Adesktop%3Aclient-2.5.4&package=owncloud-client finished too.
@xoxys please test! :-)

**Comment by xoxys** [comment]
@jnweiger daily 2.5.x repo and client installation works :)
