### ISSUE TITLE
Certificate & key (pkcs12) field too small

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7184]
Found on macOS 10.14.4.
Client 2.6.0-daily20190513 (build 11776)

Steps to recreate:
1) Open ownCloud Connection Wizard (=click on Add new account in the Account drop down menu in the Account tab) 
2) Enter server address: https://localhost:8080
3) Click Next
4) Click 'Configure client-side TLS certificate' button
5) Check Certificate & key (pkcs12) field

Actual result: Path to a selected file is not visible as the field is too small and also the bottom part of the Browse button is missing
Expected result: User can see the selected path and the entire Browse button is visible

![image](https://user-images.githubusercontent.com/49001702/57611778-de227600-7573-11e9-9191-9957f2f24520.png)

**Comment by ogoffart** [comment]
I think this is caused by a bug in the QFormLayout which does not set the minimum size and the sizehint properly.

**Comment by guruz** [comment]
@HanaGemela This is the kind of issue where we mentioned it's not worth to write it in any test plan or have the build in a defined state to test it. It's a one off fix that can be checked and closed :)

Before (for me):
<img width="477" alt="Screen Shot 2019-06-04 at 12 38 38" src="https://user-images.githubusercontent.com/959327/58873856-8c2ec500-86c7-11e9-9b53-147518fbeccc.png">

After:
<img width="587" alt="Screen Shot 2019-06-04 at 12 47 36" src="https://user-images.githubusercontent.com/959327/58873854-86d17a80-86c7-11e9-946a-7d868ea4d411.png">

**Comment by guruz** [comment]
(yeah, the window height could be smaller. Probably another UI glitch or there is a widget above the buttons still?)
