### ISSUE TITLE
Public links show password even though there isn't any

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7189]
Found on macOS 10.14.4
Client 2.6.0-daily20190513 (build 11776)
Bug also present in web ui and on Linux

Steps to recreate:
1) Right click on the file in your file system
2) Select ownCloud submenu
3) Select Share 
4) Select Public Links
5) Create a new link without password
6) Click on the link in the list of links 
7) Check its password

Expected result: Check box is not checked and no password is set
Actual result: Password check box is checked and stars are shown to indicate presence of the password. But there is no password required when accessing the link

![image](https://user-images.githubusercontent.com/49001702/57697660-0f727300-7654-11e9-8cff-79a34be78e2f.png)

**Comment by ckamm** [comment]
I'll check this out, but if it's also in the web ui there's a good chance it's not easy to work around.

**Comment by ogoffart** [comment]
I could not reproduce the problem lçocally on Linux with 2.6 branch and a somehow old server (version 10.1.0.1)

What's the version of the server used?  I guess this is a bug in the server.

**Comment by guruz** [comment]
Server issue: https://github.com/owncloud/core/issues/35419

CC @pmaier1

**Comment by ckamm** [comment]
I can reproduce it with demo.owncloud.com. The client used to use the `share_with` field to determine whether a linkshare had a password. Now the reply is `"share_with":"***redacted***"`

**Comment by HanaGemela** [comment]
This is a server issue. Will be tested when https://github.com/owncloud/core/issues/35419 has been resolved
TL: desktop-22
