### ISSUE TITLE
User email addresses can be duplicate

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7191]
Steps to recreate:
1) Create a user with an email address
2) Create another user with the same email address

Actual result: Users can have duplicate addresses. This stops users from being able to use email address to login. 
Expected result: Users cannot have duplicate addresses.

**Comment by michaelstingl** [comment]
Where can I add an user in the desktop sync client? Screenshot? Client version? Server version?

**Comment by HanaGemela** [comment]
Moved to owncloud/core as this is not a client issue
