### ISSUE TITLE
Reminder to forward port doc PR 7173 (merged to 2.6) to master

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#7194]
This is a reminder to forwardport PR https://github.com/owncloud/client/pull/7173 (Add TOC, some text fixes and rendering improvements)
to master. This PR is currently merged to 2.6 branch only.

@settermjd @ckamm

**Comment by dschmidt** [comment]
2.6 is merged to master regularly, so it will be merged at some point, don't worry :-)

**Comment by ckamm** [comment]
I did it immediately after merging your PR.
