### ISSUE TITLE
Direct access versions in the web UI

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#7196]
This might help while https://github.com/owncloud/client/issues/4556 isn’t designed and implemented yet.

It needs only a new entry in the context menu, that opens a private link in the default system web browser, with a special parameter at the end.

There’s also a new capability available in the 10.2.

**Technical docs**

- Issue: https://github.com/owncloud/docs/issues/265#issue-382224245
- PR: https://github.com/owncloud/docs/pull/1228

**Comment by ckamm** [comment]
QA:
- Verify that the new "Show file versions in browser" right-click menu item shows up when the server supports it (privateLinksDetailsParam capability)
- That it doesn't show up for older servers.
- That using the item opens the browser and shows the "versions" pane for the correct file/dir

**Comment by michaelstingl** [comment]
Just found folders have no versions. That would be cool to change. Sorry, my fault.

**Comment by michaelstingl** [comment]
`occ app:disable files_versions` on the ownCloud server should also disable this.

`occ app:enable files_versions` ==> 

```
$ curl --silent -u admin:password 'https://example.cloud/ocs/v1.php/cloud/capabilities?format=json' | json_pp
{
…
            "files" : {
               "versioning" : true,
               "privateLinksDetailsParam" : true,
               "undelete" : true,
               "privateLinks" : true,
               "blacklisted_files" : [
                  ".htaccess"
               ],
               "bigfilechunking" : true
            },
```

`occ app:disable files_versions`

```
$ curl --silent -u admin:password 'https://example.cloud/ocs/v1.php/cloud/capabilities?format=json' | json_pp
{
…
            "files" : {
               "undelete" : true,
               "privateLinksDetailsParam" : true,
               "privateLinks" : true,
               "blacklisted_files" : [
                  ".htaccess"
               ],
               "bigfilechunking" : true
            },
```

@ckamm do we check both capabilities?

**Comment by ckamm** [comment]
Good finds! No, I wasn't aware of the `versioning` capability and will add the check. And remove it for folders.

**Comment by guruz** [comment]
@michaelstingl Please test

**Comment by HanaGemela** [comment]
Tested with macOS 10.14.5, client 2.6.0alpha2 (build 12128)
Option not shown for server 10.1.1 (stable)
For server 10.2.1 (Stable):
Shown for files when files_versions enabled
Not shown for folders and when files_versions disabled

Waiting for @michaelstingl if he wants to test himself. Otherwise this issue can be closed

**Comment by HanaGemela** [comment]
QA done for this issue so I'm removing the ReadyToTest label
