### ISSUE TITLE
Client 2.6.0 has some English text though used language is German 

### ISSUE THREAD

**Issue by lazawan** [owncloud/client#7198]
Hi there , 

i just noticed that ownCloud-Client 2.6.0daily20190514 (build 11739) has some words in English though  used language is German 

please see the screenshots below : 

![2](https://user-images.githubusercontent.com/44814084/58092853-fd2b9400-7b81-11e9-8919-c181dc7daf90.png)

![1](https://user-images.githubusercontent.com/44814084/58092886-0f0d3700-7b82-11e9-9251-b71cdfd2faea.png)

regards

**Comment by mtx500** [comment]
At least for the text in the first picture (in src/gui/folderstatusmodel.cpp), there is no entry in Transifex. So there are no translations available at all.

**Comment by guruz** [comment]
```
src/gui/folderstatusmodel.cpp:            ? QStringList(tr("Virtual file support is enabled."))
```

If you don't see it in transifex, maybe @dschmidt needs to change the branch used in transifex.

**Comment by guruz** [comment]
I think @dschmidt fixed transifex by now, can you re-check?

**Comment by guruz** [comment]
@michaelstingl @tboerger @DeepDiver1975 @dschmidt Please please fix translations for 2.6 branch. Last updated 3 months ago :-(
https://github.com/owncloud/client/tree/2.6/translations

**Comment by dschmidt** [comment]
How is translations any relevant?

**Comment by guruz** [comment]
@dschmidt That's the subdirectory not the branch ;-)

**Comment by dschmidt** [comment]
Noticed, that's why I removed my comment - I'm checking what's wrong.

**Comment by dschmidt** [comment]
Urghs: https://drone.owncloud.com/owncloud/translation-sync/687/335

**Comment by guruz** [comment]
Same for me locally.
```
guruz@mgmbp2018 translations $ make l10n-read
cd .. && lupdate src -no-obsolete -ts translations/client_en.ts
Scanning directory 'src'...
/Users/guruz/woboq/owncloud/client/mirall/src/3rdparty/libcrashreporter-qt/3rdparty/breakpad/common/mac/macho_reader.cc:418: Ignoring definition of undeclared qualified class
/Users/guruz/woboq/owncloud/client/mirall/src/3rdparty/libcrashreporter-qt/3rdparty/breakpad/common/mac/macho_reader.cc:513: Ignoring definition of undeclared qualified class
/Users/guruz/woboq/owncloud/client/mirall/src/gui/shareusergroupwidget.cpp:449: Unterminated C++ string
/Users/guruz/woboq/owncloud/client/mirall/src/gui/shareusergroupwidget.cpp:456: Unterminated C++ string
/Users/guruz/woboq/owncloud/client/mirall/src/gui/shareusergroupwidget.cpp:627: Excess closing brace in C++ code (or abuse of the C++ preprocessor)
/Users/guruz/woboq/owncloud/client/mirall/src/libsync/propagatedownload.cpp:185: Qualifying with unknown namespace/class ::GETFileJob
/Users/guruz/woboq/owncloud/client/mirall/src/libsync/syncengine.cpp:350: Qualifying with unknown namespace/class ::OCC
Updating 'translations/client_en.ts'...
    Found 840 source text(s) (125 new and 715 already existing)
    Removed 89 obsolete entries
```

**Comment by guruz** [comment]
But still it changed the file, those messages are just warnings(?): 	modified:   client_en.ts

**Comment by guruz** [comment]
Ah but you are getting:
```
lupdate warning: For some reason, 'translations/client_en.ts' is not writable.
```

I think it's odd that `make l10n-read` is run in the source directory, not shadow build directory.

**Comment by dschmidt** [comment]
Yes, that's the point. Running in source tree is fine, we actually want to change the files in the source tree. Also there's a handwritten Makefile there, it's not related to CMake in any way. The issue is probably that the files belong to root and lupdate is run as a user, because the docker image I'm using is setting a default user other than root. I tried to add a workaround, let's see...

**Comment by guruz** [comment]
> we actually want to change the files in the source tree.

We could get cmake to copy the translations to build directory though and use them from there.. just an idea.

But your docker hotfix sounds easier

**Comment by guruz** [comment]
Ah you're right because we need to commit back to source directory. OK ignore my comment please.

**Comment by tboerger** [comment]
Unassigned myself as @dschmidt is already working on it.

**Comment by HanaGemela** [comment]
Retested with daily MacOS build 2.6.0-daily20190613 (build 11917) and it still uses English when speaking about virtual files 
![image](https://user-images.githubusercontent.com/49001702/59417984-807a8700-8dc8-11e9-8163-a3fa463676b6.png)
![image](https://user-images.githubusercontent.com/49001702/59418047-9f791900-8dc8-11e9-95dd-bf7e0aeef1cf.png)

**Comment by ckamm** [comment]
It looks like the updated translations have not yet arrived in our repo.

**Comment by jnweiger** [comment]
In branch 2.6 we still have 
```grep -C2 'support is enabled' client_en.ts 
    <message>
        <location filename="../src/gui/folderstatusmodel.cpp" line="215"/>
        <source>Virtual file support is enabled.</source>
        <translation type="unfinished"></translation>
    </message>

**Comment by ckamm** [comment]
@jnweiger The translations should be there now, I see them in client_**de**.ts.

**Comment by jnweiger** [comment]
@ckamm yeah, I can see them in 2.6 branch! How about also keeping master up to date? https://github.com/owncloud/translation-sync/pull/19

**Comment by ckamm** [comment]
@jnweiger We sometimes merge 2.6 to master, keeping it up to date.
