### ISSUE TITLE
One broken folder stops the entire sync

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7199]
Server: 10.2.0
Client: 2.6.0-daily20190513 (build 11776)
macOS: 10.14.4

Steps to recreate:
1) Add a new account that has one broken folder on the server

Expected result: All items apart from the broken folder have been synced

Actual result: Nothing has been synced - see log below

Note: Currently working on how to recreate that broken folder on server. Once known, the issues will be linked together

![image](https://user-images.githubusercontent.com/49001702/58174968-62c17280-7c9f-11e9-863a-8b3e5fd596e0.png)

![image](https://user-images.githubusercontent.com/49001702/58174989-6c4ada80-7c9f-11e9-8e8a-1eabe7a6f1ac.png)

**Comment by michaelstingl** [comment]
Looks like a candidate for my collection in https://github.com/owncloud/client/issues/5859

**Comment by HanaGemela** [comment]
Follow steps 1-5 in https://github.com/owncloud/core/issues/35305 to create that problematic folder

**Comment by jnweiger** [comment]
It should also be possible to poison one folder using mitmproxy with a python script that fakes a 500 response, whenever a specific folder is accessed.

**Comment by ogoffart** [comment]
What was the server error code.  Looking at the error message it seems to be a 404. But 404 should not cause the sync to stop, neither should 500.
The only errors causing the sync to abort is a 503 if the server is in maintainnence, or a connection drop (connection timeout or similar)


Could you paste the log from the client?

**Comment by HanaGemela** [comment]
@ogoffart I've just emailed you the logs

**Comment by ogoffart** [comment]
Thanks for the log. I realized the problem was during the discovery and not during the propagation.

Fix PR: https://github.com/owncloud/client/pull/7219

**Comment by HanaGemela** [comment]
The folder is not synced but it is still shown in the selective sync list as synced 

![image](https://user-images.githubusercontent.com/49001702/61793425-68fad900-ae1f-11e9-9657-5d2948795939.png)

**Comment by HanaGemela** [comment]
@michaelstingl please decide if it is worth the effort to fix the selective sync list

**Comment by michaelstingl** [comment]
The remaining issue is only cosmetic, so I'd close it for now.
