### ISSUE TITLE
After renaming the original file is synchronised as well

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7204]
Server: 10.2.0
Client: 2.6.0-daily20190522 (build 11801)
macOS: 10.14.4.

Steps to recreate:
1) Make sure you have only one single file in your ownCloud
2) Rename the file

Expected result: File has been renamed

Actual result: Pop-up message "All files in the sync folder 'ownCloud' folder were deleted on the server....". When user clicks 'Keep files', the original file gets synchronised as well. That means now user has two files - original one and renamed one

**Comment by ogoffart** [comment]
PR #7215

**Comment by HanaGemela** [comment]
Works as expected in 2.6.0alpha2 (build 12128), macOS 10.14.5
