### ISSUE TITLE
Folder is called file in 'Resharing not allowed message'

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7206]
Server: 10.2.0
macOS: 10.14.4
Client: 2.6.0-daily20190522 (build 11801)

Steps to recreate:
1) Share a folder with a user but don't give them share permission
2) Log in as a recipient
3) Right click on a shared folder
4) Select ownCloud submenu

Actual result: 'Resharing this file is not allowed' message
Expected result: 'Resharing this folder is not allowed' message

**Comment by ogoffart** [comment]
PR #7216

**Comment by HanaGemela** [comment]
Works as expected in 2.6.0alpha2 (build 12128), macOS 10.14.5
