### ISSUE TITLE
postinst for debian package `owncloud-client-cmd` does not touch `/etc/owncloud-client/sync-exclude.lst`

### ISSUE THREAD

**Issue by siriobalmelli** [owncloud/client#7207]
My apologies if this is not the right place to post this issue, I did a GitHub search for `org:owncloud owncloud-client-cmd` and while I can't find seem to find a matching source file, issues mentioning it are against this repo.

Also, I would post a pull request directly, but I can't seem to find the .deb package tree that builds this. See my proposed changes below.

### Expected behaviour

Installing owncloud-client-cmd on a vanilla Ubuntu Server image:

```bash
$ uname -r
4.15.0-38-generic
$ cat /etc/issue
Ubuntu 18.04.2 LTS \n \l
$ sudo apt-get install owncloud-client-cmd
# ... output elided for brevity
$ owncloudcmd --version
ownCloud version 2.4.1
Git revision cd60c2b88ac858339637575f124c58d88b42e78c
Using Qt 5.9.5, built against Qt 5.9.4
Using 'OpenSSL 1.1.0g  2 Nov 2017'
$ mkdir ./ownCloud
$ owncloudcmd -u USER -p PASSWORD ./ownCloud URL
# sync succeeds
$
```

### Actual behaviour (failure) and manual fix

```bash
$ sudo apt-get install owncloud-client-cmd
$ mkdir ./ownCloud
$ owncloudcmd -u USER -p PASSWORD ./ownCloud URL
# ... output elided for brevity
[ fatal default ]:	Cannot load system exclude list or list supplied via --exclude
$ sudo mkdir -p /etc/owncloud-client
$ sudo touch /etc/owncloud-client/sync-exclude.lst
$ owncloudcmd -u USER -p PASSWORD ./ownCloud URL
# success
```

### Proposed changes

I propose to add the following lines to `DEBIAN/postinst` in the .deb package.

Apologies I searched for a DEBIAN directory being maintained, but perhaps this is being autogenerated somewhere? Maybe by CMake?
I did some searching around the project sources but didn't seem to find a clue.

```bash
# add to owncloud-client-cmd/DEBIAN/postinst
TGT=/etc/owncloud-client/sync-exclude.lst
[[ -e $TGT ]] || mkdir -p $(dirname $TGT) && touch $TGT
```

**Comment by ho4ho** [comment]
owncloud-client-cmd package not by ownCloud:

https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

maybe by Ubuntu provided?

**Comment by siriobalmelli** [comment]
Thank you, much appreciated :)
Filed on [Ubuntu Launchpad](https://bugs.launchpad.net/ubuntu/+source/owncloud-client/+bug/1830509), in case anyone encounters this bug in the future.
