### ISSUE TITLE
Improve gtk/gnome integration by exporting data with libcloudproviders

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7209]
This issue is about using `libcloudproviders` to export the ownCloud client's sync folders, thereby allowing users of gnome to see their sync folders in the file browser and to access client settings from there. 

Background: For some time applications have been heavily discouraged from using tray icons in gnome. Users having to work around the deprecation has been a constant source of issues. The supported way of providing the functionality is supposed to be using the cloudproviders api (https://csoriano.gitlab.io/libcloudprovidersweb/).

Note that this enhancement does not immediately solve the problem yet as some common distributions (like ubuntu 18.04) do not enable libcloudproviders support in their gtk builds.

**Comment by ckamm** [comment]
@jnweiger I propose that we aim to enable it for linux distos where the right dependencies are available from 2.6.1 onwards. It needs libcloudproviders>=0.3.0 and gio-2.0.

Warning: https://github.com/owncloud/client/pull/7210#issuecomment-496409934

**Comment by ckamm** [comment]
This issue now is about building packages with libcloudproviders and adding the dependency. Was confused there for a bit because I thought it was done.

**Comment by jnweiger** [comment]
Looking into this now.
Should be possible starting with Ubuntu 19.04 
Will add ReadyToTest as soon as there is a daily build that compile with libcloudprivoders.

**Comment by ckamm** [comment]
Note that as far as I'm aware we targeted this for 2.6.1 - having it in 2.6.0 is optional.

**Comment by jnweiger** [comment]
Packaging is updated. 
deb based distros will pick up libcloudproviders automatically at build time if available,
rpm based distros cannot do that, but the *.spec file now has 
```
%if 0%{?fedora_version} > 30 || 0%{?sle_version} > 150200
# fedora 30 has only 0.2.5
# opensuse leap 15.2 still has only 0.2.5
BuildRequires:  libcloudproviders-devel >= 0.3.0
%endif
```
as a hint...

**Comment by jnweiger** [comment]
That is all we can do here, it seems. Ubuntu 19.04 already suffers from missing tray icons, but their nautilus is not built with --enable-cloudproviders. The user experience is rather broken there, and we cannot do much about it, afaik.
