### ISSUE TITLE
Crash reporter window is empty

### ISSUE THREAD

**Issue by guruz** [owncloud/client#7211]
This is confusing to the user, as we're sending something actually.

Since symbolication is happening on server side, we can't populate fully but at least should show something.

![Screen Shot 2019-05-27 at 13 44 31](https://user-images.githubusercontent.com/959327/58417637-b3f9a980-8085-11e9-8efb-1cbf0349136c.png)

FYI @dschmidt

**Comment by ckamm** [comment]
I agree!

It seems to be called `commentTextEdit` and I don't see anything in the crash reporter to support pre-populating it. Maybe we can find it by name in crashreporter/main.cpp and add some template text encouraging users to give us more information.

Where will we be able to see this information?

**Comment by TheOneRing** [comment]
@dschmidt maybe something we can fix in your fork?

**Comment by dschmidt** [comment]
Yes, of course.. maybe just add a placeholder text as @ckamm suggested.

**Comment by TheOneRing** [comment]
Yes a placeholder would be nice.

**Comment by TheOneRing** [comment]
We nowadays use it to send a part of the logs.
