### ISSUE TITLE
[Win10] automated update leaves owncloud in broken state

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7221]
After logging in to my Win10 VM, owncloud-client announces there is an update, 
I confirm, the update gets installed.

I am not starting the client.
On next log-in, this error appears
![grafik](https://user-images.githubusercontent.com/1108546/58943852-eb9cdb80-8780-11e9-8990-a1e872e25652.png)

and the client cannot be started any more.

**Comment by guruz** [comment]
@jnweiger That's an update to what version?

**Comment by jnweiger** [comment]
It does not start. Hard to tell.

**Comment by jnweiger** [comment]
![grafik](https://user-images.githubusercontent.com/1108546/59039233-bd002d00-8874-11e9-8f2a-ec3f6a78ab92.png)

**Comment by dschmidt** [comment]
Please provide reproducing steps. 

Especially the formerly installed version.

**Comment by jnweiger** [comment]
I'll try to reproduce

**Comment by jnweiger** [comment]
Run uninstall owncloud via windows, allows me to install a fresh ownCloud-2.6.0.12251.12038-daily20190701.msi

But the current broken state only mentions the version 2.6.011573 from the last install attempt.
Not sure, how to retrieve earlier install logs from the system.

**Comment by jnweiger** [comment]
Rolling back snapshots of that windows VM brings me back to the previously running owncloud client
![image](https://user-images.githubusercontent.com/1108546/60464311-75d84280-9c4e-11e9-8a31-7d6cf28a401b.png)

From there, the system wants to install version 2.6.0.11573

![image](https://user-images.githubusercontent.com/1108546/60464457-eaab7c80-9c4e-11e9-9fe2-8600d773e935.png)

During the install, the desktop turns black. I have a mouse pointer, but cannot click or type anything. ALT-F2 does nothing.
CTRL-ALT-DEL brings up a screen where I can selet Task-Manager. Nothing running except a Windows Defender eating ca 20% CPU time constantly. Cannot be killed. Permission denied.

CTRL-ALT-DEL (again) allows logout. A normal login screen appears, login works, and all looks good, except that owncloud shows 

![image](https://user-images.githubusercontent.com/1108546/60464936-2a269880-9c50-11e9-9003-0f3bf01dfc3f.png)

That reproduces the issue starting with a possibly broken alpha version.

**Comment by jnweiger** [comment]
## Retesting the issue on win10
* starting with an uninstall of onwncloud, to make sure the system is in a clean state.
* install client manually from https://download.owncloud.com/desktop/stable/ownCloud-2.5.4.11654.11466.msi
* setup an update server which advertises https://download.owncloud.com/desktop/daily/ownCloud-3.6.0.12254.12041-daily20190702.msi in the stable channel
* redirect update requests to the test update server using the environment variable OCC_UPDATE_URL=http://$IP_ADDR/client/
* start client 2.5.4, open the general tab
![image](https://user-images.githubusercontent.com/1108546/60514389-ae712e00-9cd9-11e9-9018-ae0d907ad36f.png)
* click Restart&Update

A small window with a progress bar appears, the desktop turns otherwise all black.
After a few minutes, this intimidating requester appears.
![image](https://user-images.githubusercontent.com/1108546/60514551-027c1280-9cda-11e9-818f-2fda3e94cdaf.png)

**Comment by jnweiger** [comment]
The original error is not easily reproducable. Sorry. There are other errors now. Even more sorry.

**Comment by jnweiger** [comment]
After fixing the updater config to be exact on the build number, update from 2.5.4 to 2.6.0 works fine.

**Comment by jnweiger** [comment]
Closing. This is no longer reproducable.
