### ISSUE TITLE
Read file chunk data on demand to reduce peak memory use

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7226]
This is a continuation of #6880.

Some users, usually on windows, experienced crashes during parallel uploads of large files. This was because a chunk of each file was loaded into memory and chunk size goes up to 100 MB. A workaround was added to avoid the crash and instead error on the upload.

The better solution is to keep only a much smaller buffer of file data in memory and read from disk as needed. This would significantly reduce the peak amount of memory used by the client during upload.

**Comment by ckamm** [comment]
QA: Add many large new local files and trigger an upload. Observe memory use. Increase during sync should be < 100MB.

**Comment by HanaGemela** [comment]
Works as expected in 2.6.0alpha2 (build 12128) on macOS and Windows
