### ISSUE TITLE
Clarify "Apply manual changes" when asking user about large folders

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7230]
Client: 2.6.0-daily20190522 (build 11801)
Server: 10.2.0
OS: Mojave 10.14.5

Steps to recreate:
1. After completing an initial sync, log out the client
2. Upload an additional folder to the server that exceeds the limit beyond which the client asks for confirmation if folders larger than that should be synced (Advanced Setting in General tab) 
3. Log in the client to the server
4. Select "Apply manual changes" in the warning message

Expected result: Not really sure. Maybe the client should offer a selection which files inside that folder should be synced?
Actual result: The folder is not synced. Basically identical behaviour as 'Synchronize none' button. If the behaviour is really the same, then there is no need for 'Apply manual changes' button

**Comment by ckamm** [comment]
Indeed, if you make no changes to the selective sync list "Apply manual changes" will be the same as "Synchronize none". Possibly we could disable "Apply manual changes" until the user has actually made a change.

**Comment by HanaGemela** [comment]
@ckamm What should I do to see the difference between these two buttons?

**Comment by ckamm** [comment]
@HanaGemela When the "new large folder" ui state is activated you should be seeing some sync folders subfolders pop up. Each has a checkbox for its current selective sync state. The new large folders have are unchecked by default. You could have two new large folders, check only one and use "Apply manual changes" to confirm your manual choice (instead of syncing both or neither).

**Comment by HanaGemela** [comment]
The same when syncing External storages

**Comment by guruz** [comment]
@HanaGemela Please test

**Comment by ckamm** [comment]
Behavior change is that now the "Apply manual changes" button only becomes enabled when a change was made.

**Comment by HanaGemela** [comment]
@ckamm Does it mean I'll see the button when there are two large folder to be synced? 
Are the below steps to recreate correct?

1. After completing an initial sync, select only some folders to be synced, log out the client
2. Upload an additional folder to the server that exceeds the limit 
3. Log in the client to the server
Expected result: the button is shown

**Comment by ckamm** [comment]
@HanaGemela When you do these steps the button will be shown (as before), but it will be disabled (new). It will become enabled when you change the checked status of at least one subfolder checkbox.

**Comment by HanaGemela** [comment]
@ckamm I've checked with macOS 2.6.0-daily20190616 (build 11930), I run exactly the steps described above and the button is enabled. 
And what subfolder do you mean?

**Comment by ckamm** [comment]
@HanaGemela This is what I see when there's a new "big" folder:
![image](https://user-images.githubusercontent.com/833306/60003423-f3a6b780-966a-11e9-8e86-6e9451ec1596.png)
And "Apply manual changes" becomes enabled when I change the state of any of the checkboxes in front of the folders.

**Comment by HanaGemela** [comment]
@ckamm my button is not disabled 
![image](https://user-images.githubusercontent.com/49001702/60013132-fc54b900-967d-11e9-8c9a-c2ee65b8e925.png)

**Comment by HanaGemela** [comment]
@ckamm this still does not work

**Comment by ckamm** [comment]
Weird. Since it's an unimportant change I'm moving further investigation to 2.6.1.

**Comment by ckamm** [comment]
@HanaGemela I've tried to reproduce this again but am still unsuccessful.

Scenario 1:
- Set big folder threshold to 1 MB
- Have a folder on the server with contents > 1MB
- Create a new account with that folder
- The selective sync ui comes up an the "apply manual changes" button starts out disabled

Scenario 2:
- Set big folder threshold to 1 MB
- Have an existing sync folder fully synced
- Pause sync
- Add a new folder on the server with contents >1MB
- Resume sync
- The selective sync ui comes up an the "apply manual changes" button starts out disabled

**Comment by HanaGemela** [comment]
Works as expected in 2.6.0rc1 (build 12411), mac 10.14.6
