### ISSUE TITLE
List of synced folders is not updated when one failed

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7234]
Server: 10.2.0
Client: 2.6.0-daily20190522 (build 11801)

Steps to recreate:
1) Add new external share
2) Turn off the machine where the share is from
3) Add a new folder via WebUI
4) Sync the folder to the client

Actual result: The folder is synced but the list of all synced folders in Account tab is not updated. The list gets updated after restart.
Expected result: List of synced folders reflects what is in file system all the time

![image](https://user-images.githubusercontent.com/49001702/59106392-91457b80-8936-11e9-9641-3393cbabd5ae.png)

**Comment by ckamm** [comment]
Indeed, currently syncs with an `Error` state don't lead to an update of the selective sync folder list, see `FolderStatusModel::slotFolderSyncStateChange()`.

**Comment by TheOneRing** [comment]
@HanaGemela could you test with the latest version?
