### ISSUE TITLE
Feature: Peer-to-Peer P2P syncing possible = v fast client sync

### ISSUE THREAD

**Issue by maddhin** [owncloud/client#724]
Before (trying to) use Owncloud I used syncing.net (http://www.syncing.net). Their main business is provide syncing for non-exchange-Outlook-users. IMHO this is a rare breed but they also offer a pretty genius file sycning tool.

The tool works this way: generally, there is only P2P sync between the clients = very fast sync if in the same network at the same time. If in different networks / locations syncing is depending on internet speed but under normal conditions acceptable fast. Now the genius part: there is a relay / buffer server, which remembers how many clients are out there and what data has been synced and which is saving / buffering the data clients might need. This way, a client can get synced as soon as it is online again and it is not necessary to always keep all computers online.

IMHO owncloud should have such a feature as sycning of clients is speed up significantly. The option to have your data in the cloud / accessible through the webbrowser is good but, practically, one wants to have and work with the data locally (on different machines). The webbrowser access is just a plus (at least for me) but the biggest advantage (again, for me) is to have the data synced between different locations and computers (also for sharing!) and most importantly: I can properly backup the data and have a central point where I can administer the data.

IMHO P2P syncing would bring Owncloud to a whole new level and would make it much more useful / attractive to companies.

PS: P2P syncing would have nothing to do with "torrent P2P". Naturally these connections must be VPN and encrypted, etc pp.

**Comment by ttemiel** [comment]
Is there any news on this? It would be great to have owncloud use P2P to sync with other clients whenever possible.

**Comment by q2dg** [comment]
Well...we are in 2016...hello?

**Comment by L00maca** [comment]
Any news?

**Comment by ivakyb** [comment]
6 years later... 2019.

**Comment by lopugit** [comment]
7 years later

**Comment by MichaelWei7** [comment]
9 years later

**Comment by Wehzie** [comment]
Seeing as Syncthing Android is no longer officially supported, I am interested in hearing whether ocis has capacities to address p2p.
