### ISSUE TITLE
Detect crippled folder watchers to avoid bad sync behavior

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7241]
From https://github.com/owncloud/enterprise/issues/3303

Some filesystems may have limitations in file and folder watchers, like some Windows network drives. This leads to two main problems:
- Changes to files in the sync folder don't trigger a sync run. Users must trigger it manually or wait for a time-based one.
- To avoid slow local discovery the client normally trusts the folder watcher about changes. When notifications are missing the client may perform a sync run and not notice local changes.

Workarounds: Use the `forceSyncInterval` and `fullLocalDiscoveryInterval` settings to reduce the duration between time-based sync runs and to require full local discovery every time.

This issue is about automatically detecting bad folder watchers. The client should then notify the user and switch into the existing "unreliable folder watcher" mode.

**Comment by ckamm** [comment]
QA: I tested by verifying no warning comes up after startup on Windows and linux. Then I commented out these lines in folderwatcher.cpp
```
    if (QFile::exists(path)) {
        auto mtime = FileSystem::getModTime(path);
        FileSystem::setModTime(path, mtime + 1);
    } else {
        QFile f(path);
        f.open(QIODevice::WriteOnly | QIODevice::Append);
    }
```
and checked that the warning notification was triggered.

To test for real one would need to set up a network drive like in the enterprise ticket.

**Comment by HanaGemela** [comment]
@ckamm Does it mean that any Windows network drive will not sync the changes until the client does the full local discovery which is once an hour?

**Comment by ckamm** [comment]
@HanaGemela No. It should only come up for network drives where folder watchers are unsupported. I don't know which those are. Unfortunately I didn't hear back in owncloud/enterprise#3303 about what kind of network drive was affected specifically and couldn't reproduce their problem. That's why I could only test that the check works in principle by changing code.

**Comment by HanaGemela** [comment]
OK, this issue will be closed as soon as https://github.com/owncloud/client/issues/7305 has passed QA

**Comment by HanaGemela** [comment]
#7305 has passed QA
