### ISSUE TITLE
Public sharing does not work anymore with 10.2.0 when password is enforced

### ISSUE THREAD

**Issue by lexo-mfleuti** [owncloud/client#7245]
### Expected behaviour
When the option "Enforce expiration date" is enabled the Windows client should automatically set the latest expiration date and create a valid public share link. This worked up until 10.2.0.

### Actual behaviour

- Creating a public share link directly via context menu: does not work at all
- Creating a public share link via "share" dialog: does not work at all. The "expiration date" field is greyed out and cannot be activated - not even manually. Instead a red "expiration date is enforced" error message is shown from the beginning.

### Steps to reproduce

1. Enable this setting in OC Settings: Sharing > Enforce expiration date
2. Right click on a file -> Select "ownCloud" within context menu
3. Select "Share..." (Teilen...)
4. Enjoy the show

### Server configuration
Operating system: 
Ubuntu 19.04 (GNU/Linux 5.0.0-16-generic x86_64)

Web server: 
Apache/2.4.38 (Ubuntu)

Database: mysql  Ver 15.1 Distrib 10.3.13-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

PHP version: 
PHP 7.2.19-0ubuntu0.19.04.1 (cli) (built: Jun  4 2019 14:44:42) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.19-0ubuntu0.19.04.1, Copyright (c) 1999-2018, by Zend Technologies

ownCloud version:
10.2.0

Storage backend (external storage):
Local

### Client configuration
Client version:
I tried 2.5.4 and 2.6.0alpha1 from here: https://owncloud.org/download/

OS language:
English

Installation path of client:
C:\Program Files (x86)\ownCloud
![oc_error](https://user-images.githubusercontent.com/8611779/59550368-34ffde80-8f6a-11e9-8bf0-16ae2ae3088d.png)

**Comment by ckamm** [comment]
@lexo-mfleuti So you're saying with server version 10.2.0 it starts failing?

**Comment by lexo-mfleuti** [comment]
@ckamm Yes, we updated to 10.2.0 about 2-3 weeks ago and it's no longer working ever since. 
There was an issue with this in client version 2.5.3 already which I reported and was solved shortly after in 2.5.4. But with 10.2.0 it's now failing completely. I cannot even set a date manually anymore.

**Comment by ckamm** [comment]
Yes, it looks like the server no longer auto-fills the expiration date if it's required.

**Comment by lexo-mfleuti** [comment]
Glad you found the error that quickly. Thank you very much for looking into it!

Though there must remain a very quick and simple way to share files with like 1 click. OwnClouds' primary purpose is sharing files.  This needs to be extremely fast and easy. That's why I suggested this:
https://github.com/owncloud/client/issues/7061#issuecomment-468621463

**Comment by ckamm** [comment]
@lexo-mfleuti Yes, the current quick link-share creation also assumes the server will fill in the expire date if it requires it, instead of erroring - that's why it's also broken by 10.2.0. I currently guess that there'll be a workaround for it in >=2.6.0 while, and the behavior may be reverted in future server releases to make older clients work again.

**Comment by ckamm** [comment]
QA: Check that the "Copy public link to clipboard" action works (creates share if necessary, sets it to clipboard) with and without the "Set default expiration date" and "Enforce expiration date" server sharing settings.

Need to restart client after changing server settings.

The option can't work yet if shares require a password.

**Comment by patrickjahns** [comment]
@ckamm 
Did you test with ownCloud versions < 10.2 ? Is this only broken on 10.2.1 or earlier?

**Comment by lexo-mfleuti** [comment]
It worked up until 10.2.0. Though - to be honest - I'm not quite certain what the version was before. I think 10.1.0

**Comment by ckamm** [comment]
@patrickjahns I think I started on version 10.1.0 where it worked, and it started failing with 10.2.0. That makes some sense since https://github.com/owncloud/core/pull/34971 was merged for 10.2.0.

**Comment by HanaGemela** [comment]
6 scenarios were tested:

1. "Copy public link to clipboard" action works without the "Set default expiration date" server sharing settings - works as expected 
2. "Copy public link to clipboard" action works with the "Set default expiration date" server sharing settings - works as expected 
3. "Copy public link to clipboard" action works with the "Set default expiration date" and the "Enforce expiration date" server sharing settings - still broken https://github.com/owncloud/client/issues/7286 :x:

4. "Create a new public link via ownCloud Sharing dialog" works without the "Set default expiration date" server sharing settings - works as expected 
5. "Create a new public link via ownCloud Sharing dialog" works with the "Set default expiration date" server sharing settings - works as expected 
6. "Create a new public link via ownCloud Sharing dialog" works with the "Set default expiration date" and the "Enforce expiration date" server sharing settings - works as expected

As this issue contains multiple bugs and some of them has been fixed, I'll close it and the remaining one will be tracked in the separate issue as mentioned above

**Comment by HanaGemela** [comment]
Tested with 2.6.0alpha2 (build 12097), Windows 10
