### ISSUE TITLE
Setting share expire date and password on creation impossible if fields are required by server

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7246]
If the server security settings say a password or expire date is required it becomes impossible to create public link shares: In the share creation dialog the checkboxes for enabling expire dates or passwords are disabled and unchecked.

They should be disabled *and checked* to allow users to set an expire date or a password before creating the link share.

Found while investigating #7245

**Comment by ckamm** [comment]
QA: Verify that creating and editing of public link shares is possible with permutations of these server sharing options:
- "Set default expiration date"
- "Enforce expiration date"
- "Enforce password"

Need to restart client after changing server settings.

Note that the "Enforce password" setting was split into three options for 10.2.0 and that's not yet reflected in the client dialog. See #7247

**Comment by micbar** [comment]
@ckamm please evaluate https://github.com/owncloud/core/pull/35564

**Comment by HanaGemela** [comment]
Creating and editing of public link shares is possible when password and/or expiry date is enforced 2.6.0alpha2 (build 12128), macOS 10.14.5

NOTE: There are still some issues opened around this area
