### ISSUE TITLE
New "password required" capabilities lead to incorrect behavior

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7247]
The server 10.2.0 (edit: actually since 10.0.8, see below) has new fine-grained capabilities for requiring passwords for link shares. This setting can now be controlled independently for "read-only", "read/write" and "upload only" link shares.

The client should support these new capabilities.

However, there's an additional complication: it seems that if any one of these settings is enabled, the server will set the previous files_sharing/public/password/enforced capability to 1. This is unfortunate because it'll make the client require passwords for *all* public link shares when the server may only require it for one of the three types.

Found while testing with 10.2.0 for #7245.

**Comment by ckamm** [comment]
Moving to 2.6.1 since it doesn't need to block 2.6.0 release. Users can still create shares, they just may be required to set passwords when that's not actually required for the particular link share type.

**Comment by pmaier1** [comment]
This has been added with 10.0.8 more than one year ago. https://doc.owncloud.com/server/10.2/admin_manual/release_notes.html#new-option-to-granularly-configure-public-link-password-enforcement

**Comment by ckamm** [comment]
@pmaier1 Thanks, I hadn't looked it up yet. Unfortunate we didn't see it earlier, but at least not urgent then.

**Comment by michaelstingl** [comment]
Can this be solved with https://github.com/owncloud/client/issues/7487

**Comment by michaelstingl** [comment]
fixed
