### ISSUE TITLE
delta sync crashes

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7253]
New experimental feature. In the General tab I have:
   [X] Enable Delta-Synchronization for files larger than 1 MB

In my sync area, I have a folder
<pre>
$ ln -lh pdf
-rw-r--r-- 1 testy testy 8,3M Jun 17 17:48 x1.pdf
-rw-r--r-- 1 testy testy 8,3M Jun 17 17:48 x2.pdf
-rw-r--r-- 1 testy testy 8,3M Jun 17 17:48 x3.pdf
-rw-r--r-- 1 testy testy 8,3M Jun 17 17:48 x4.pdf
-rw-r--r-- 1 testy testy 8,3M Jun 17 17:48 x5.pdf
</pre>
All 5 files have identical contents.

* Conntect with server, wait until initial sync is done.
* on the client side, duplicate the content `cp -a pdf pdf2`
* a sync starts and takes ca 30 seconds to upload.
This timing is very consistent, with or without delta sync. Restarted the client to make sure the changed delta sync setting is applied.

* Use selective sync to disable and then re-enable syncing of the pdf2 folder.
* Upon re-enable, a sync starts and takes ca 15 seconds to download.
Again this timing is very consistent, with or without delta sync. Restarted the client to make sure the changed delta sync setting is applied.

Expected result:

* With selective sync both upload and download should be much faster, as both client and server can find identical files in folder pdf.
* With many identical files in one folder, both upload and download should be much faster, even without the extra folder.

**Comment by jnweiger** [comment]
Same for inplace file changes:
* I have a 40MB logfile.txt, and wait for the sync to finish.
* on one client, I add one short line with e.g. `echo huhu >> logfile.txt`
* this client re-uploads the entire 40MB logfile.txt
* another client ona differnt machine then re-downloads the entire logfile.txt 

Identical timing with or without delta-sync enabled.

**Comment by michaelstingl** [comment]
Delta Sync is not about identical files. It’s about partial changes of a file. Idea is, to only transfer the changed parts.

**Comment by michaelstingl** [comment]
@ckamm do we have a list of delta-sync enabled mime types?

**Comment by ckamm** [comment]
Indeed, delta sync will not detect duplicate files. It's only about reducing the number of bytes that need to be transfered when uploading/downloading a file.

Your second test, appending to a file, should be covered by delta sync though.

Double check whether zsync is enabled by looking for "[zsync disabled]" log messages. You need:
- server zsync capability "dav/zsync"
- file not in external storage
- delta sync enabled on the client (settings, DeltaSync/enabled in config file)
- file larger than minimum size for delta sync (settings, DeltaSync/minFileSize in config file)

Since you set the latter two, maybe the server support is missing/disabled. 

There's other requirements too
- Delta uploads are more limited than delta downloads. Appends and changing a random byte should work though.
- But only if the server has zsync metadata from a previous upload.
- And only if the chunked UploadFileNG codepath is used, By default that's for files larger than 10 MB only.

**Comment by ckamm** [comment]
@michaelstingl Mime-types are not relevant for delta sync.

**Comment by jnweiger** [comment]
Ah, probably my server did not offer any dav/zsync capability then :-/
Is there a minimum server version needed for that?

**Comment by ckamm** [comment]
@jnweiger I may be wrong, but I don't think it's in a released version yet (`git tag --contains 0e0ab090fa14f846abec305e3e842c9f60579183`)

**Comment by guruz** [comment]
It's not in a released version which is kind of a problem. Ask your co-worker @michaelstingl about it. There is a backport which is not progressing.. 

https://github.com/owncloud/core/pull/35011

CC @PVince81 @DeepDiver1975

**Comment by jnweiger** [comment]
Installed owncloud-master from tonight. It has
```
curl -s https://admin:admin@$SERVER/ocs/v2.php/cloud/capabilities?format=json -k | jq .ocs.data.capabilities.dav.zsync
"1.0"
```

Now the client crashes.

```
$ gdb /usr/bin/owncloud
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/owncloud...Reading symbols from /usr/lib/debug/.build-id/b8/fa18f7130bee8a0dbf98b3acc76714a0c2fd44.debug...done.
done.
(gdb) run 
Starting program: /usr/bin/owncloud 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffee33f700 (LWP 7909)]
[New Thread 0x7fffedb3e700 (LWP 7910)]
[New Thread 0x7fffec990700 (LWP 7912)]
[New Thread 0x7fffdf014700 (LWP 7918)]
[New Thread 0x7fffde813700 (LWP 7919)]
[New Thread 0x7fffdddd0700 (LWP 7920)]
[New Thread 0x7fffdd3c8700 (LWP 7921)]
[New Thread 0x7fffdc9ac700 (LWP 7922)]
[Thread 0x7fffdc9ac700 (LWP 7922) exited]
[New Thread 0x7fffdc9ac700 (LWP 7923)]
[New Thread 0x7fffc7fff700 (LWP 7924)]

Thread 1 "owncloud" received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0xffffffffc00025c0) at malloc.c:3103
3103	malloc.c: Datei oder Verzeichnis nicht gefunden.
(gdb) where
#0  0x00007ffff568598d in __GI___libc_free (mem=0xffffffffc00025c0) at malloc.c:3103
#1  0x00007ffff7b89473 in zsync_end (zs=0x7fffc0004890) at /usr/src/packages/BUILD/src/3rdparty/zsync/c/libzsync/zsync.c:809
#2  0x00007ffff7b5cfe4 in std::function<void (zsync_state*)>::operator()(zsync_state*) const (__args#0=<optimized out>, this=<optimized out>) at /usr/include/c++/7/bits/std_function.h:706
#3  0x00007ffff7b5cfe4 in std::unique_ptr<zsync_state, std::function<void (zsync_state*)> >::~unique_ptr() (this=0x7fffffffd690, __in_chrg=<optimized out>) at /usr/include/c++/7/bits/unique_ptr.h:268
#4  0x00007ffff7b5995f in OCC::PropagateUploadFileNG::slotZsyncSeedFinished(void*) (this=0x55555652e820, _zs=<optimized out>)
    at ./src/libsync/propagateuploadng.cpp:60
#5  0x00007ffff65df712 in QObject::event(QEvent*) () at /opt/ownCloud/qt-5.12.2/lib/x86_64-linux-gnu/libQt5Core.so.5
#6  0x00007ffff758719c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /opt/ownCloud/qt-5.12.2/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#7  0x00007ffff758e6d0 in QApplication::notify(QObject*, QEvent*) ()
    at /opt/ownCloud/qt-5.12.2/lib/x86_64-linux-gnu/libQt5Widgets.so.5
#8  0x00007ffff65aefc8 in QCoreApplication::notifyInternal2(QObject*, QEvent*) ()
    at /opt/ownCloud/qt-5.12.2/lib/x86_64-linux-gnu/libQt5Core.so.5
#9  0x00007ffff65b1b87 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /opt/ownCloud/qt-5.12.2/lib/x86_64-linux-gnu/libQt5Core.so.5
#10 0x00007ffff660cab3 in  () at /opt/ownCloud/qt-5.12.2/lib/x86_64-linux-gnu/libQt5Core.so.5
#11 0x00007ffff3de0387 in g_main_context_dispatch () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#12 0x00007ffff3de05c0 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#13 0x00007ffff3de064c in g_main_context_iteration () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#14 0x00007ffff660c0cf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /opt/ownCloud/qt-5.12.2/lib/x86_64-linux-gnu/libQt5Core.so.5
#15 0x00007ffff65ad2fa in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /opt/ownCloud/qt-5.12.2/lib/x86_64-linux-gnu/libQt5Core.so.5
#16 0x00007ffff65b6500 in QCoreApplication::exec() () at /opt/ownCloud/qt-5.12.2/lib/x86_64-linux-gnu/libQt5Core.so.5
#17 0x00005555555dfafb in main(int, char**) (argc=<optimized out>, argv=<optimized out>) at ./src/gui/main.cpp:171
(gdb)
```

**Comment by jnweiger** [comment]
server log ends with 
```
{"reqId":"09fa2191-f6ef-42e3-a450-ada0654e12fb","level":0,"time":"2019-06-18T12:49:51+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"GET","url":"\/owncloud\/ocs\/v1.php\/cloud\/activity?page=0&pagesize=100&format=json","message":"token a752d1c8ea6e8f275c0f4c07660fa6a83e8790078fe8196e6bf2419becca394bbb8ccb2d2964e83c33d5a270a07a7b11d3efa00a02589dd6bff846c36b16e34b does not exist"}
{"reqId":"bb4a6c5f-34e3-45c7-8be9-0116d7b0e04a","level":0,"time":"2019-06-18T12:49:52+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"PROPFIND","url":"\/owncloud\/remote.php\/dav\/files\/admin\/","message":"token a752d1c8ea6e8f275c0f4c07660fa6a83e8790078fe8196e6bf2419becca394bbb8ccb2d2964e83c33d5a270a07a7b11d3efa00a02589dd6bff846c36b16e34b does not exist"}
{"reqId":"df204e6a-7e0d-49c4-80c6-ae54345cf54f","level":0,"time":"2019-06-18T12:49:52+00:00","remoteAddr":"127.0.0.1","user":"admin","app":"OC\\Authentication\\Token\\DefaultTokenProvider::getToken","method":"GET","url":"\/owncloud\/remote.php\/dav\/files\/admin\/x.pdf?zsync","message":"token a752d1c8ea6e8f275c0f4c07660fa6a83e8790078fe8196e6bf2419becca394bbb8ccb2d2964e83c33d5a270a07a7b11d3efa00a02589dd6bff846c36b16e34b does not exist"}
```

**Comment by ckamm** [comment]
@jnweiger :( I've not yet been able to reproduce it though with a oc-master snapshot and the current 2.6 build. What were the last few lines in your client log?

**Comment by ogoffart** [comment]
I tried delta sync and couldn't reprodce the crash either.
@jnweiger  In case of crash, a valgrind log can often be very usefull

**Comment by TheOneRing** [comment]
@jnweiger can you still reproduce it?
