### ISSUE TITLE
option --logwindow does not show log output

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7254]
The option --logwindow is described as showing log output. It no longer does. 
![image](https://user-images.githubusercontent.com/1108546/59672624-1bf06b00-91c0-11e9-9fa1-22ba5f60f132.png)

(I'd argue this is a regression, but i already understood it is meant as a feature)

**Comment by jnweiger** [comment]
As https://github.com/owncloud/client/issues/7255 look like a wontfix, the parameter --logwindow should be renamed to --logdialog and the description should be something like 'open a window to configure temporary log files'

**Comment by ckamm** [comment]
Agree.
