### ISSUE TITLE
Clarify how to log to stdout directly

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7255]
The logs are now always split into many files, and as soon as a sync run finsihes, the log gets compressed.

It is now very hard to use standard tools like less or grep on these logs.

Can we please have an option to disable automatic compression?

![image](https://user-images.githubusercontent.com/1108546/59672997-d1232300-91c0-11e9-95c6-1a0812f1a597.png)

**Comment by michaelstingl** [comment]
This window is meant for unexperienced users, to collect logs to send to their admin. For debugging on the machine, please run the sync client with the `--logfile` parameter

**Comment by ckamm** [comment]
@jnweiger If this is genuinely making testing hard and you can't use --logfile we *could* bring back the logwindow (albeit not exposed to normal users).

**Comment by michaelstingl** [comment]
@jnweiger what's the benefit of having the scrolling log in this tiny window instead of working with it in your terminal?

**Comment by dschmidt** [comment]
FTR ``--logfile -` outputs the logs to stdout.

**Comment by guruz** [comment]
> FTR --logfile - outputs the logs to stdout.

Maybe this could be shown as an explicit option (for user guidance) in the --help

**Comment by ckamm** [comment]
QA: No testing needed imo.

**Comment by jnweiger** [comment]
Workaround:

```
apt install ruby-file-tail
cd /tmp/ownCloud-logdir
rtail -m '*.log.0'
```

This produces a nice stream of logging that does not end every few seconds.
