### ISSUE TITLE
Public link share default expiration date not used

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7256]
Set "Set default expiration date" sharing setting in the server and then try to create a public link share in the client:

1) If "Enforce expiration date" is off and the user wants to create a new share, the "expiration date" checkbox currently starts out unchecked. It should be checked.
2) When checking the checkbox the expiration date is by default set to tomorrow. It should be set to the configured number of days.

**Comment by ckamm** [comment]
QA: Top comment explains what to look out for.

**Comment by HanaGemela** [comment]
Works as expected in 2.6.0alpha2 (build 12128), macOS 10.14.5
New issue raised: https://github.com/owncloud/client/issues/7313
