### ISSUE TITLE
Server error message when connecting to untrusted domain confuses by mentioning that JavaScript is disabled

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7258]
Client: 2.6.0-daily20190613 (build 11917)
macOS 10.14.5
Server: 11.0.0 prealpha (daily) Build:2019-06-17T20:04:09+00:00 038c73133e98991dc707be32c2baffdcc623486a

Steps to recreate:
1) Install the server without editing trusted domains
2) Connect a client to the server

Actual result: Error message saying user has to enable JavaScript
Expected result: Only message about editing trusted domains

![image](https://user-images.githubusercontent.com/49001702/59692861-2160ac00-91e6-11e9-8f43-d358b6c76567.png)

**Comment by michaelstingl** [comment]
@HanaGemela Where does this server come from?

**Comment by HanaGemela** [comment]
@michaelstingl This is a daily build. But I believe the message is the same with server 10.2.0

**Comment by michaelstingl** [comment]
@HanaGemela Maybe related:
https://github.com/owncloud/client/issues/6157

For this, a PR is in the works:
https://github.com/owncloud/client/pull/6914

**Comment by ckamm** [comment]
What you're seeing is the error message the server sends. That includes the error about missing javascript. We could special case the "untrusted domain" error (maybe; if we can detect it without relying on the text) but there'll likely be other errors that we haven't covered.

**Comment by michaelstingl** [comment]
@ckamm @HanaGemela better try to get a proper response from the ownCloud server

**Comment by ogoffart** [comment]
Now we just show the error code from the server, without the HTML
