### ISSUE TITLE
[macOS] enable clicking paths in desktop notifications

### ISSUE THREAD

**Issue by anselmpaul** [owncloud/client#7259]
I get a notification about sync behaviour, e.g. 'Sync Activity: path/path/path/file.extension'
### Expected behaviour
Clicking the notification opens my finder at the file location
### Client configuration
Client version: 2.5.4 (build 11456)

Operating system: macOS Mojave

OS language: english

**Comment by michaelstingl** [comment]
Duplicate for https://github.com/owncloud/client/issues/4841
