### ISSUE TITLE
wincfapi usage source code location

### ISSUE THREAD

**Issue by LokiMidgard** [owncloud/client#7260]
I currently try to understand how the wincfapi works. The official microsoft sample is prety limited and the documentation also does not answer all my questions. So I am trying to look at open source projects that use the api. 

This reposetory is the only one that seems to use it on github. However I only find references in the source code to load a plugin, but I wasn't able to find the actuall source code for that plugin.

If someone could point me to the right direction, I would be thankful.

**Comment by michaelstingl** [comment]
@LokiMidgard Plugin wasn't published yet. Please send a mail to `michael-<at>-owncloud.com` for more information.
