### ISSUE TITLE
Notifications that a new file has been added even though it was not

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7261]
Server: 10.2.0
Client:2.6.0-daily20190613 (build 11917)
macOS: 10.14.5

Steps to recreate:
1) Start the client -> 'ownCloud Manual.pdf.owncloud has been added.' notification has been shown
2) Go to General tab
3) Open 'Edit Ignored Files'
4) Cancel -> 'Big/Example.odt has been added' notification has been shown

Expected result: None of these notifications has been received as everything has been already added
Actual result: Notifications as described above

Logs emailed

**Comment by ckamm** [comment]
It's very likely that this won't reproduce. Do you have log files?

**Comment by HanaGemela** [comment]
@ckamm I've emailed you the logs on 19/06/2019 3:20 PM

**Comment by ckamm** [comment]
Relates to https://github.com/owncloud/client/issues/7350

**Comment by HanaGemela** [comment]
Similar issue from https://github.com/owncloud/client/issues/6953

Also the notification is wrong. The notification says that all 3 files have been added and in the logs I can see things like
08-07 01:49:38:278 [ info sync.discovery ]:	Processing "Once more/test.owncloud.owncloud" | valid: false/false/true | mtime: 0/0/1563960721 | size: 0/0/16 | etag: ""//"40def6a0b835c3927848a4519818a5fa" | checksum: ""//"SHA1:5bc110031ebf379964dac0801b8f9cd757e9e15c" | perm: //WDNVR | fileid: ""//"00002670oc9hhs3phb8b" | inode: 0/0/ | type: 3/3/0

**Comment by ogoffart** [comment]
Is this now fixed?

**Comment by HanaGemela** [comment]
@ckamm @ogoffart What exactly has been fixed? Not really sure what to test here

**Comment by ogoffart** [comment]
There have been fixes for the case in which there are .owncloud files on the server.
I believe this most likely had fixed the bug.
