### ISSUE TITLE
Uploads and vfs test on windows are broken

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7264]
When running vfs tests on windows I noticed that:
- file uploads would not work, the resulting file on the server was 0 bytes in size
- winvfs `convertToPlaceholder` would emit warnings about not being able to get the exclusive lock on a file after the upload was done

Both are due to 42e4d1061ffd7f73d086438824991bf2def1512b and #7226, PR will follow.

**Comment by HanaGemela** [comment]
Could you help me put together the steps to test?

1) Turn on VFS
2) Upload a new file via client ( -> gets uploaded on the server, status in the client is Available on this device)
3) Free up local space by right clicking on the new file

Actual result: The icon and the text don't match when I check the status
![image](https://user-images.githubusercontent.com/49001702/61524041-d53b9e00-aa15-11e9-9565-8345c11ef719.png)

**Comment by ckamm** [comment]
Testing for this issue is simply:
- When adding a new file locally the correct data is uploaded to the server, with vfs and without vfs
- When adding a new file locally with vfs enabled there's no warning including "CfOpenWithOplock error". In fact there should be no warnings on the sync.vfs logger.

The icon and the tooltip disagreeing is a bug, but unfortunately outside of our control. Hopefully it's just a caching issue in the Windows cfapi layer and doesn't last long.

**Comment by HanaGemela** [comment]
What is sync.vfs logger?

**Comment by ckamm** [comment]
@HanaGemela Look for the "sync.vfs" string in the logs. I meant that there should (probably) be no lines containing the string "[ warning sync.vfs ]".

**Comment by HanaGemela** [comment]
Windows 10, client 2.6.0alpha2 (build 12097)
Files can be uploaded to the server with and without VFS. 
No warning sync.vfs or CfOpenWithOplock in logs.
Works as expected
