### ISSUE TITLE
Long path - Error while reading directory

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7266]
Server: 10.2.0
macOS: 10.14.5
Client: 2.6.0-daily20190613 (build 11917)

Steps to recreate:
1) Paste a file within subfolders into a local sync folder - see an example of a file below

2qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcvb/qwertyuiopasdfghjklzxcvbnmqwertyuiopasdfghjklzxcv/h.txt

Actual result: Error while reading directory
Expected result: Nice error explaining what went wrong or file has been synced

**Comment by ogoffart** [comment]
Works for me on linux (the file is currently uploaded / downloaded, not matter how long the path is.)
I assume this is OSX specific.

**Comment by TheOneRing** [comment]
@HanaGemela can you still reproduce?
