### ISSUE TITLE
Rename to start with dot removes the file from server

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7269]
I have a file foobar.txt synced with the server.
On the linux desktop I do `mv foobar.txt .foobar.txt`
The client activity window logs a delete action for file foobar.txt
The file still exists in the local filesystem with the new name .foobar.txt but gets removed from the server.

My /etc/ownCloud/sync-exclude.lst does not contain a rule for `.*` or anything that would match .foobar.txt 

I'd expect the file .foobar.txt to be present on the server.

**Comment by michaelstingl** [comment]
It should be uploaded to the server, but maybe it's hidden, depending on your preferences to list files in the web UI.

**Comment by ckamm** [comment]
There's a "sync hidden files" setting that's independent from the ignore list. If it's enabled hidden files (windows) and .* files (everywhere I think?) will be ignored.

**Comment by jnweiger** [comment]
I agree. But when the client logs 
![image](https://user-images.githubusercontent.com/1108546/59922427-0afa6080-9431-11e9-9f2b-97792762d018.png)

then I do not expect to see the hidden file in the web gui any more. and indeed, it is gone from the web gui too.  (with settings [x] show hidden files)

Same procedure on the server has a different result though:

I have a file emco/x.pdf -- sync is finished.
I rename the file from x.pdf to .x.pdf

The file still visible, when I have setting [x] show hidden files.
But the client removes the file.

**Comment by jnweiger** [comment]
@ckamm Thanks for the hint!
Indeeed: 
```
grep Hidden ~/.config/ownCloud/owncloud.cfg 
0\FoldersWithPlaceholders\1\ignoreHiddenFiles=true
1\Folders\2\ignoreHiddenFiles=true
2\Folders\3\ignoreHiddenFiles=true
3\Folders\4\ignoreHiddenFiles=true
```

Is there a way to change the default? I cannot see anything in the client gui?
Using 2.6.0daily20190618 (build 988) btw.

**Comment by jnweiger** [comment]
Can we change the message from 'Deleted' to 'Moved to excluded or hidden name, deleted.' ?

**Comment by jnweiger** [comment]
Workaround: change the config file manually and restarting the client. Now everything syncs fine.

**Comment by ckamm** [comment]
@jnweiger The "Sync hidden files" option is currently inside the "Edit ignored files" dialog.

**Comment by ckamm** [comment]
The client completely skips over "ignored" or "hidden" (if enabled) files. That's why when you rename "foo" -> ".foo" on the server the client will delete "foo" locally: it filters out ".foo" very early and then believes that "foo" was deleted on the server. That also makes it hard to change the message for such an action.

**Comment by TheOneRing** [comment]
@michaelstingl won't fix?

**Comment by michaelstingl** [comment]
@TheOneRing yes
