### ISSUE TITLE
Renames get propagated as delete+put occasionally

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7271]
Renaming `z.txt` to `a.txt` (the filenames matter) will be propagated as DELETE+PUT. It should be propagated as a MOVE. This likely happens because something's up with the remote etag check.

**Comment by HanaGemela** [comment]
@ckamm When I rename z.txt to a.txt I'm getting PROPFIND + MOVE 
When I rename a.txt to z.txt I'm getting only MOVE 
Please confirm what I should see. I tested with 2.6.0alpha2 (build 12128), macOS 10.14.5

**Comment by ckamm** [comment]
Both the MOVE and PROPFIND+MOVE are fine. (it depends on the order items are processed: if the discovery has already seen that the source file is not around locally anymore it can skip the PROPFIND. That's why a -> z is different from z -> a)

The key test is that it's not a DELETE + PUT because reuploading the file data can be costly.

**Comment by HanaGemela** [comment]
Then it works as expected in 2.6.0alpha2 (build 12128), macOS 10.14.5
