### ISSUE TITLE
Pin state of suffix virtual files persists on file deletion

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7273]
Test case:
- create file "a" in always-local folder, mark it online only, sync
- delete "a" on the server, sync
- create file "a" on the server, sync

The new remote file will be online-only because that pin state is still in the database. It should be hydrated and inherit the always-local pin state.

Follow up to #7250

**Comment by HanaGemela** [comment]
@ckamm What does a remote file mean?

Testing is currently blocked by https://github.com/owncloud/client/issues/7329 and https://github.com/owncloud/client/issues/7264 as now I can't really say what files are virtual and what files are available locally

**Comment by ckamm** [comment]
With "create new remote file" I meant "create a new file on the server".

**Comment by HanaGemela** [comment]
@ckamm I don't really understand the steps. If the pin state might persist, I have to delete virtual file to  have 'online-only' state in the database? But it is not possible to delete virtual files, they get recreated

**Comment by ckamm** [comment]
@HanaGemela Updated the original description. The file needs to be deleted on the server.

**Comment by HanaGemela** [comment]
Works as expected on macOS 10.14.5, client 2.6.0alpha2 (build 12128)
