### ISSUE TITLE
Cannot reshare a folder with restricted permissions via User and Groups share

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7275]
Server: 10.2.1 RC1
Client: macOS testpilot 2.6.0-daily20190626 (build 11996)
macOS: 10.14.5

Steps to recreate:
1) Share a folder with one subfolder (e.g. Test/Subfolder) with User1 and remove Edit permissions
2) Login as User1
3) Reshare Subfolder with User2 via User and Groups share

Actual result: Entry in Users and Groups sharing list cannot be created
Expected result: Entry in Users and Groups sharing list with the same permissions as the recipient has 

![image](https://user-images.githubusercontent.com/49001702/60577704-27c35c00-9d80-11e9-91ff-44da00d5e98f.png)

**Comment by michaelstingl** [comment]
@micbar looks like the thing we found. Maybe open a server issue too…

**Comment by micbar** [comment]
## Background
- Desktop client tries to reshare a subfolder. 
- The Share permissions on the incoming parent folder are for example `17`
- The desktop client (2.5.x) tries to create the share with default permissions from the Capabilities API, which are for example `31`
- The creation of the share fails

## Solution
- Do a PROPFIND on the Subfolder you want to share first and request the sharing-permissions
- Respect the current permissions when creating a share

```
<?xml version="1.0" ?>
<d:propfind xmlns:d="DAV:" xmlns:oc="http://owncloud.org/ns" xmlns:x1="http://open-collaboration-services.org/ns">
  <d:prop>
    <d:getetag/>
    <oc:fileid/>
    <oc:permissions/>
    <oc:share-types/>
    <oc:owner-id/>
    <d:getlastmodified/>
    <oc:size/>
    <oc:checksums/>
    <x1:share-permissions/>
  </d:prop>
</d:propfind>```

**Comment by jnweiger** [comment]
Reproduced with client 2.6.0daily on Linux:

User Admin shares AdminPhotos with user jwtest, allowing reshare, but not edit.
User jwtest tries to reshare AdminPhotos/subfolder with user testy, he gets this error message:

![image](https://user-images.githubusercontent.com/1108546/60578372-5db51000-9d81-11e9-8c81-badc8e95eed8.png)

**Comment by ckamm** [comment]
@jnweiger I've tried to reproduce with 240d97686808800ec51fa170d7816b5860e74fd6 (current 2.6) and 10.2.1RC1.
- user1 shared a folder to user2 using a local by-user share and disabled the "can edit" permission (using client gui)
- user2 could successfully share the folder with user3, the share gets created without "can edit"  permission and the check box for it is disabled. (using client gui)

There's code in `ShareManager::createShare` that retrieves the share's permissions with the `shared_with_me` API and creates the new share with appropriately limited permissions. That code has existed for a while. 

Any ideas about what made your case different?

**Comment by ckamm** [comment]
See previous discussion https://github.com/owncloud/client/issues/4358#issuecomment-173545984

**Comment by ckamm** [comment]
Nevermind, I didn't read carefully enough: The issue only happens when resharing a subfolder of the initial share. Will look.

**Comment by HanaGemela** [comment]
Works as expected in 2.6.0 alpha2 on macOS
