### ISSUE TITLE
Random crashes

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7281]
Sometimes the client crashes when it is not used. This issue will gather all the crash reports - new will be added once it happens again

Without doing anything, the client crashed - bp-6c602b25-9e17-43e7-aa54-67f052190628
Client: 2.5.4 (build 11456), Server 10.1.1 and 10.2.1RC1, macOS: 10.14.5

When I tried to open the client mentioned above again - another crash bp-4fb78a59-52fd-4cfc-a289-e721f2190628

**Comment by HanaGemela** [comment]
This one wasn't random (let me know if you want me to raise a separate issue): 
bp-6253bc5e-f0f1-49bd-b56e-4d43c2190701
Client: 2.5.4 (build 11456), 10.2.1RC2, macOS: 10.14.5
Crash happened after I clicked Share from the context menu

**Comment by HanaGemela** [comment]
I switched on my computer this morning and both of my clients crashed 
Testpilot bp-d67bd52c-8e2a-4b93-afde-95d262190702
Client: 2.6.0-daily20190626 (build 11996)
Server:  10.2.1RC2
macOS: 10.14.5

ownCloud bp-21e86c21-9fcc-41cc-9f1c-939432190702
Client: 2.5.4 (build 11456)
Server:  10.2.1RC2, 10.1.1
macOS: 10.14.5

**Comment by guruz** [comment]
> Without doing anything, the client crashed - bp-6c602b25-9e17-43e7-aa54-67f052190628

EXC_BAD_INSTRUCTION / 0x00000001 at 0x7fff7a5a83eb

    QtNetwork in QHttpNetworkConnectionPrivate::prepareRequest
    qscopedpointer.h in QHttpNetworkConnectionPrivate::dequeueRequest
    QtNetwork in QHttpNetworkConnectionChannel::qt_static_metacall
    QtCore in QMetaObject::activate
    moc_qabstractsocket.cpp in QAbstractSocketPrivate::fetchConnectionParameters
    qabstractsocket.cpp in QAbstractSocketPrivate::_q_testConnection

> When I tried to open the client mentioned above again - another crash bp-4fb78a59-52fd-4cfc-a289-e721f2190628

EXC_BAD_ACCESS / KERN_INVALID_ADDRESS at 0xffffffffb118ed70

    QtCore in QLocale::name
    QtNetwork in QHttpNetworkConnectionPrivate::prepareRequest
    qscopedpointer.h in QHttpNetworkConnectionPrivate::dequeueRequest
    QtNetwork in QHttpNetworkConnectionChannel::qt_static_metacall
    QtCore in QMetaObject::activate
    moc_qabstractsocket.cpp in QAbstractSocketPrivate::fetchConnectionParameters
    qabstractsocket.cpp in QAbstractSocketPrivate::_q_testConnection

> bp-6253bc5e-f0f1-49bd-b56e-4d43c2190701
>  Crash happened after I clicked Share from the context menu

EXC_BAD_ACCESS / 0x0000000d at 0x0

    qcocoaeventdispatcher.mm in QCocoaEventDispatcher::processEvents
    qeventloop.cpp in QEventLoop::exec
    qcoreapplication.cpp in QCoreApplication::exec
    main.cpp in main

>  Testpilot bp-d67bd52c-8e2a-4b93-afde-95d262190702

EXC_BAD_ACCESS / KERN_INVALID_ADDRESS at 0x8

    QtGui in QScreen::handle
    qcocoascreen.mm in QCocoaWindow::handleGeometryChange
    libqcocoa.dylib in QCocoaWindow::qt_static_metacall
    QtCore in QMetaMethod::invoke
    qmetaobject.h in ___ZL30qRegisterNotificationCallbacksv_block_invoke
    libqcocoa.dylib in -[QNSWindow
    libqcocoa.dylib in -[QNSApplication
    qcocoaeventdispatcher.mm in QCocoaEventDispatcher::processEvents]

> ownCloud bp-21e86c21-9fcc-41cc-9f1c-939432190702

EXC_BAD_ACCESS / KERN_INVALID_ADDRESS at 0x88

    libqcocoa.dylib in QCocoaWindow::qt_static_metacall
    QtCore in QMetaMethod::invoke
    qmetaobject.h in ___ZL30qRegisterNotificationCallbacksv_block_invoke
    qcocoaeventdispatcher.mm in QCocoaEventDispatcher::processEvents
    qeventloop.cpp in QEventLoop::exec
    qcoreapplication.cpp in QCoreApplication::exec

**Comment by guruz** [comment]
Those are all crashes in Qt :-/

**Comment by HanaGemela** [comment]
Another one after restarting the desktop client: bp-cf55455a-4f51-4c65-9c43-59e0c2190716
client 2.6.0alpha2 (build 12128), macOS 10.14.5, server 10.2.1. stable

**Comment by HanaGemela** [comment]
Another one after restarting the desktop client:  bp-16f1fad0-56f0-412a-a399-d37a02190716
client 2.6.0alpha2 (build 12128), macOS 10.14.5, server 10.2.1. stable

**Comment by HanaGemela** [comment]
Another one after Restarting the sync from the three dots menu 80885046-515d-477c-bd9c-16fb58e0997f

**Comment by HanaGemela** [comment]
Another one after Restarting the sync from the three dots menu cd15539b-1323-4847-b8e0-a2e137bf1298

**Comment by HanaGemela** [comment]
Switching between VFS and Selective sync quickly bf781858-2481-49d7-85b9-f7f058bc5ea9

**Comment by HanaGemela** [comment]
640a9068-e964-4cd6-bd5c-3627b382ab6c when turning on the client after previous crash caused by the scenario described above

**Comment by HanaGemela** [comment]
Crashes cased by switching between VFS and selective sync moved to a separate issue as it is easy to reproduce

**Comment by HanaGemela** [comment]
As I cannot recreate I'm moving this crash to Random crashes from https://github.com/owncloud/client/issues/5088

I've tried with server in maintenance mode. While in maintenance mode, I've unchecked one folder in selective sync list and disabled VFS for another account. After turning off the maintenance mode, the client crashed 48a065f1-c5e8-4541-b427-9355b200dd62
Not sure if it is related to this issue or not. I've found the scenario with maintenance mode in the top level issue. In case it is not related, I'll raise a new issue

**Comment by michaelstingl** [comment]
My crash:
a76aaee9-dbe2-4ec8-bb74-0adeafd5f493
(client in background – no user interaction)

**Comment by HanaGemela** [comment]
New one with RC2: 723aae1f-cad1-4669-99d0-a95a7ff03fe3 @ogoffart @ckamm @TheOneRing

**Comment by HanaGemela** [comment]
Another one: e4de98ed-ad74-40b3-9eae-dc2cd2fd7e7e

**Comment by HanaGemela** [comment]
Another one without any obvious reason: 5225ed3e-eb0c-44ed-97a3-46d6f3536159 

QWidgetBackingStore::markDirtyOnScreen
Fatal Error: EXC_BAD_ACCESS / KERN_INVALID_ADDRESS
