### ISSUE TITLE
Users cannot remove permissions that they don't have themselves

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7283]
in the client language permissions 23 mean Share and Edit, permissions 17 mean Share

Steps to recreate:
1. Admin shares TMP folder with User1 with permissions 23
2. User1 shares TMP folder with User2 with permissions 23
3. User2 shares TMP folder with User3 with permissions 23
4. User1 changes the permissions for User2 to 17

Actual result:
User2 cannot remove Edit permissions from User3
When User2 removes Share permissions from User3, the entry is greyed out and cannot even be deleted 

The window has to closed and open again.

Expected result: 
User2 can remove Edit permissions from User3
User2 can remove Share permissions from User3
User2 can delete User share with User3 (after some changes have been done)

or

everybody down the chain immediately getting less permissions @pmaier1 please specify

Client: 2.5.4 (build 11456)
Server: 10.2.1.RC2, 10.1.1.
macOS: 10.14.5

**Comment by TheOneRing** [comment]
The sharing dialog is considered deprecated
