### ISSUE TITLE
Password not saved when expiration date is wrong

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7284]
Client: 2.5.4 (build 11456)
macOS: 10.14.5

Preconditions : Maximum expiry date 3 days, expiry date if password set 1 day, enforce YES
Steps to recreate:
1. Create a new public link (expiry date in 3 days)
2. Set a password (expiry date cannot exceed 1 day warning)
3. Set the the expiry date to 1 day in the future (now everything looks OK)
4. Close
5. Open Public links again 
Actual result: Password is missing

or 

1. Untick Set default expiration date
2. Create a new public link with expiry date in 7 days
3. Tick Set default expiration date, expire after 3 days, tick Enforce
4. Set Password for that link
5. Close 
Actual result: Password not saved

Expected result: Warning that password has not been saved or password has been saved @pmaier1 please specify

**Comment by jnweiger** [comment]
Client 2.6.0daily on linux has a separate close and create button:
![image](https://user-images.githubusercontent.com/1108546/60580371-4546f480-9d85-11e9-8172-5b913902a877.png)

This should solve the issue. No link is created when you just close.

**Comment by TheOneRing** [comment]
The sharing dialog is considered deprecated
