### ISSUE TITLE
Public link not copied to clipboard when password enforced

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7285]
Client: 2.5.4 (build 11456)
Server: 10.1.1., 10.2.1. RC2 (testing)
macOS: 10.14.5

Steps to recreate:
1) On the server go to Settings -> Admin -> Sharing
2) Enforce all three types of password protection
3) Right click on a folder/file 
4) From the context menu select ownCloud -> Copy public link to clipboard
5) Access the link

Actual result: No link has been created
Expected result: User is prompted to add a password

**Comment by ckamm** [comment]
I've tested this on 2.6.0 and the right thing happens for me: When passwords are enforced it's impossible to silently create a public sharing link. The client detects it and opens the link sharing page instead, so the user can choose their password.

**Comment by HanaGemela** [comment]
Right clicking on 'Copy public link to clipboard' does nothing in 2.6.0alpha2 (build 12128), macOS 10.14.5

**Comment by HanaGemela** [comment]
It seems to work sometimes... I'll need to have a look what is the settings when it doesn't work. It could be some combination with expiration date

**Comment by ckamm** [comment]
There's a good chance that #7343 fixed this.

**Comment by HanaGemela** [comment]
The sharing dialog gets opened when password is enforced and with different combinations of expiration date. Works as expected on Windows 10, client 2.6.0beta1 (build 12201)
