### ISSUE TITLE
Public link not copied to clipboard when expiration date required 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7286]
Client: 2.5.4 (build 11456)
Server: 10.2.1. RC2 (testing)
macOS: 10.14.5

Steps to recreate:
1. Enforce expiration date in Sharing settings and also in Security settings on the server
2. Right click on a folder/file
3. From the context menu select ownCloud -> Copy public link to clipboard
4. Access the link

Actual result: No link has been created
Expected result: User is prompted to add an expiration date

**Comment by HanaGemela** [comment]
Works on server 10.1.1.

**Comment by ckamm** [comment]
Works for me with 2.6.0 and 10.2.1RC1

**Comment by HanaGemela** [comment]
2.6.0alpha2 (build 12128), macOS 10.14.5.

It is better now. At least I get a 'nice' error message. But I thought the expected result is to open the Public link creation window so users can edit the expiration date themselves

![image](https://user-images.githubusercontent.com/49001702/61532368-e9899600-aa29-11e9-9226-3ad59929f719.png)

**Comment by ckamm** [comment]
@HanaGemela I imagine you get that error message when you
- enable default/max expire date in sharing settings
- enable maximum share expire date in security settings with a date that's smaller than the default expire date

There's no way for the client to detect the "security" settings, so it will attempt to create a share with the default expire date. That's where the dialog comes from.

**Comment by ckamm** [comment]
An alternative might be to open the link share dialog instead of showing the error message.

**Comment by HanaGemela** [comment]
@ckamm I think opening the share dialog would be better as the user wants a new link so in the next step they will open the share dialog anyway. If it is done automatically it would save them a few clicks and avoid confusion why they see an error. 
But maybe this will be fixed once https://github.com/owncloud/client/issues/7328 is resolved?

**Comment by ckamm** [comment]
Ok, I'll look at opening the dialog instead. Unfortunately #7328 can't be resolved client side.

**Comment by HanaGemela** [comment]
I've closed #7328 and tried again and it is still broken, still the same - clicking the button doesn't do anything

Client: 2.6.0alpha2 (build 12128)
macOS: 10.14.5
Server:10.2.1. (stable)

**Comment by ckamm** [comment]
@HanaGemela Fyi, there were two different kinds of error condition and only one lead to the warning dialog. With the new PR both kinds of failures will just lead to the "public share" dialog opening.

**Comment by HanaGemela** [comment]
Works as expected on macOS 10.14.6, client 2.6.0beta1 (build 12241)
