### ISSUE TITLE
Deletion of shared folder should be called Unsharing

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7287]
Client: 2.5.4
Server: 10.2.1.RC2

Steps to recreate:
1) Share a folder with delete permissions 
2) As a recipient, delete the folder

Actual result: Only recipient’s copy has been deleted. There is no difference if user has delete permissions against a folder or not. Always a shared copy can be deleted and the original remains 

Expected result: @pmaier1 please specify the difference between having and not having delete permissions against a folder

**Comment by HanaGemela** [comment]
Delete means delete the content

**Comment by jnweiger** [comment]
Tested with client 2.6.0daily on linux

User deletes a folder that was shared with him. The Activity tab does not log the action as Server Activity (nothing really happened on the server side, ok). But there is an entry in the Sync Protocol tab, that says Deleted: 
![image](https://user-images.githubusercontent.com/1108546/60581622-804a2780-9d87-11e9-8a26-06fa822573f7.png)

Suggested improvement: Make this say 'Unshared'

**Comment by jnweiger** [comment]
Without delete permission, a user can not delete files and subfolders within the share. But he can still "delete" the shared folder itself, which is not really a delete. This is an unshare action.

**Comment by HanaGemela** [comment]
Original issue is OK, delete permission allows to user to delete the content of a folder

Please rename the Action when user deletes a shared folder from Deleted to Unshared as reported by @jnweiger

**Comment by ogoffart** [comment]
For the client point of view, this is still just a delete.
The client has no way (i think) to know if the folder was, in fact, unshared.
Also for the user, the end result is the same: The folder is no longer in his/her owncloud.
So i'm tempted to close this as wontfix.

**Comment by ogoffart** [comment]
I'm closing this since we have no way to fix it and it is not so important.
