### ISSUE TITLE
German translation uses 'Klients' as translation for client

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7290]
I am not ecxactly sure if we have a good word in german for the english word "client".

"Klients" is not part of the german language so far. Klient and Klienten exists, but only in a very different context. 

![image](https://user-images.githubusercontent.com/1108546/60521876-4aa23180-9ce8-11e9-8f4b-df1d0e950759.png)

Suggestion: I'd vote for not translating client. E.g. 
"Eine neue Version des ownCloud-client ist verfügbar."

(or "... des ownCloud-clients ..." if we  want to apply german declinations to a foreign word.)

**Comment by guruz** [comment]
> Suggestion: I'd vote for not translating client. E.g.

I agree.

**Comment by guruz** [comment]
Assiged to 2.6.1 but fixable in 2.6.0 if someone fixes the strings in transifex

**Comment by ogoffart** [comment]
@jnweiger  Translations needs to be changed in transifex.

**Comment by dschmidt** [comment]
> (or "... des ownCloud-clients ..." if we want to apply german declinations to a foreign word.)
Yes, I'd go for  "des ownCloud-Clients".

**Comment by michaelstingl** [comment]
> Yes, I'd go for "des ownCloud-Clients".

👍

**Comment by TheOneRing** [comment]
Apparently fixed

**Comment by jnweiger** [comment]
Other option: "Eine neue Version der ownCloud desktop App ist verfügbar."
Our websites talk about a desktop app, instead of a desktop client now.
