### ISSUE TITLE
MacOS overlay icons

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7291]
Client: 2.5.4.
MacOS: 10.14.5
Server: 10.2.1. RC3

Steps to recreate:
1) Pause the sync
2) Check the overlay icons

Actual result: Icons are missing
Expected result: Paused icons shown - EDIT: see the comment below, no paused icons required

**Comment by ckamm** [comment]
I don't think there've ever been "paused" overlay icons. There's only Ok/Error/Sync/Warning. Should there be? Currently paused folders have no sync icons because we can't determine good states while the folder is paused and there's no "paused" icon.

**Comment by HanaGemela** [comment]
Used terms explained:

Overlay icon: icon displayed over file/folder name, showing if the resource has been synced - failed/synced/ignored. Also indicates if the resource has been shared.

Status icon: icon displayed in separate column called Status (only applies to Windows, on macOS the icon is next to the file name), showing availability of the file -currently locally/ always locally/ online only. Sharing not included.

To match Windows behaviour
1) When VFS on, the overlay icons reflect the status of the file (currently locally, always locally, online only) - that means status icon is the same as overlay icon
2) When VFS on and sync paused, the overlay icons reflect the status of the file (currently locally, always locally, online only) or it could display only 'online only' icon, local files are without the icon (then also Windows needs a change)
3) When VFS on and file cannot be synced (e.g. 503 error), syncing icon is shown
4) When VFS off and sync paused, no icons are shown

**Comment by TheOneRing** [comment]
There is no status column on mac
