### ISSUE TITLE
User can change a file without change permissions

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7292]
Client: 2.5.4 (build 11456)
Server: 10.2.1 RC3
macOS: 10.14.5

Steps to recreate:
1) User1 creates a folder A with one file inside
2) User1 shares folder A with User2 without change permissions (only Share, Create and Delete permissions granted)
3) User2 changes the file -> a conflict file has been created
4) User2 deletes the original file
5) User2 renames the conflict file to name the original name

Actual result: Original copy has been changed, User1 received the changes
Expected result: Original copy has not been changed @pmaier1 please specify

**Comment by ckamm** [comment]
Forbidding the change permission without prohibiting delete+replace doesn't restrict User2. It's not a combination of permissions that makes much sense.

I'd say this works as expected: changing the file is forbidden by the client. But User2 deleting and recreating the file is allowed as per sharing permissions.

**Comment by HanaGemela** [comment]
User can add another files in that folder
And user can also rename the files

**Comment by HanaGemela** [comment]
This used to work in 2.5.4 - in that version file is read-only. No change allowed

**Comment by ogoffart** [comment]
> This used to work in 2.5.4 - in that version file is read-only. No change allowed (Windows 10)

Works as expected here. The files do indeed not have the write permission when the change flag is not there.

**Comment by ogoffart** [comment]
I don't think there is something we can fix
