### ISSUE TITLE
Move duplicates file when shared with only create permissions

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7294]
Tested with client-2.6.0daily20190618 on Linux mint with server 10.2.1RC3

User A shares folder Test with user B, granting **only** edit-create permission.

User A creates folder Test/Sub and file Test/file.txt - optionally extra contents in folder Test/Sub to test for duplication of files.

User B is connected with a desktop client, folder Test is synced. 

User B moves testfile.txt into folder Sub
The move succeeds, but the file reappears. Both, server and client now have two copies.

Expected result: The move either succeeds or fails. We should not duplicate files. Never ever.

**Comment by jnweiger** [comment]
Client log messages:
```
||Test/testfile.txt|INST_ERROR|Up|1562083312||36227||2|Not allowed because you don't have permission to add files in that folder|0|0|0||
15:24:03||Test/file.txt|INST_NEW|Down|1562083312|4ca1a78742ce574460137a8978e8e5a3|36227|00000338ockqgn48lpag|7|Not allowed to remove, restoring|200|36227
```
Technically the issue is:
When the client realizes, that a readonly file disappers, it restores the file to undo the damage.
This restore assumes a delete instead of a rename.

**Comment by ogoffart** [comment]
Not allowed move fallback to delete + create (which, in case of forbidden delete, is the same as copy)
That's the expected behavior.
