### ISSUE TITLE
Too many overlay icons

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7295]
client 2.6.0-daily20190618 on Linux Mint

While reproducing #7294, a file ends in a state where it has a total of 7 overlay icons:

![image](https://user-images.githubusercontent.com/1108546/60674717-098e5680-9e7b-11e9-9089-d9f8ca1b8fc6.png)

This is too much information.

**Comment by ckamm** [comment]
I've looked into this before and didn't see what was going wrong. I guess it's an upstream issue - but maybe we're using the (sparsely documented) API wrong. Do you have a path for reliably reproducing the issue?

**Comment by ogoffart** [comment]
do we know how to reproduce?
