### ISSUE TITLE
Sync does not recover when a rename fails with 403

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7296]
Tested with client 2.6.0daily20190618 on Linux Mint with server 10.2.1RC3

User A shares folder Test with user B, granting **only** edit-create + edit-delete permission.
User A creates folder Test/Sub and file Test/file.txt - optionally extra contents in folder Test/Sub to test for duplication of files.

User B is connected with a desktop client, folder Test is synced
User B renames folder Sub to subfolder in the file browser.

Client logs an error: 403 Forbidden.
Server still has Sub, client has subfolder.
They are two separate object now. Changes in Sub are no longer synced down. Changes in the local subfolder are not synced to the server.

**Comment by ogoffart** [comment]
I believe the 403 error was probably fix, as we know check more carefully the permission.
However, when it is not allowed, it will fallback to delete and create, which is the expected behavior.

**Comment by HanaGemela** [comment]
Tested with 2.6.1-daily20191127 (build 12791), macOS 10.15.1
Client doesn't create two object anymore, also 403 doesn't happen anymore. 
However the rename successes which shouldn't. Only local copy should be renamed, not the original folder. Tracked in https://github.com/owncloud/client/issues/7293
