### ISSUE TITLE
client duplicates file on rename with change permission

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7299]
Client 2.6.0-daily20190708 on Linux Mint. Server 10.2.1RC3
User has a share with only edit-change permission, but no create or delete).
User connects a client, waits until sync is done. In the local filesystem he does
`mv testfile.txt foo.txt`

The rename propagates as expected to the server, but a file with the original name gets recreated:
```
#=#=#=# Syncrun started 2019-07-08T15:41:59Z
#=#=#=#=# Propagation starts 2019-07-08T15:41:59Z (last step: 102 msec, total: 102 msec)
15:41:59||Test-m/testfile.txt|INST_NEW|Down|1562083312|dc30efb94213f0447120f1ab52277853|36227|00000364ockqgn48lpag|7|Not allowed to remove, restoring|200|36227|1562083312|4b917b52-5d0e-454c-af20-c8bde94ef37c|
15:41:59||Test-m/testfile.txt -> Test-m/foo.txt|INST_RENAME|Up|1562083312|dc30efb94213f0447120f1ab52277853|36227|00000364ockqgn48lpag|4||201|0|0|9c685e53-3143-4754-aeb7-3f7f2cb8ba05|
#=#=#=# Syncrun finished 2019-07-08T15:41:59Z (last step: 250 msec, total: 352 msec)
```
Client has now two copies.
Expected behaviour: The `INST_NEW|Down` action never trigger together with `INST_RENAME|Up`.

**Comment by jnweiger** [comment]
May or may not be reproducable. Sometimes this happens instead:
```
#=#=#=#=# Propagation starts 2019-07-08T19:15:01Z (last step: 88 msec, total: 88 msec)
19:15:01||Test-m/foo.txt|INST_NEW|Down|1562083312|dc30efb94213f0447120f1ab52277853|36227|00000364ockqgn48lpag|1|Not allowed to remove, restoring; Restoration Failed: Server replied "503 Service Unavailable" to "GET http://localhost/owncloud/remote.php/dav/files/jwtest/Test-m/foo.txt" (Could not open file)|503|36227|1562083312|a6a5e372-62fb-4184-89d0-019989e9bada|
||Test-m/foo.txt -> Test-m/file.txt|INST_RENAME|Up|1562083312|dc30efb94213f0447120f1ab52277853|36227|00000364ockqgn48lpag|3|Operation canceled|0|0|0|4d9cd179-db6c-41f3-9405-5ceda3790537|
```

From a user perspective, everything is fine then. The file is renamed, and no duplicate is created (as creation fails with 503).

**Comment by jnweiger** [comment]
I suspect race conditions everywhere.

**Comment by ogoffart** [comment]
Recent change might have fixed this issue.

Note again that move is just a special case of delete and re-create.  If one of these operation is not allowed, the move can't happen and the deleted part might be recovered

**Comment by HanaGemela** [comment]
Progress tracked in https://github.com/owncloud/client/issues/7293
