### ISSUE TITLE
All existing file data is removed when enabling vfs

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7302]
Currently when vfs mode is enabled all files are marked as `OnlineOnly` and the contents are deleted locally. That can cause problems for users with large sync folders who have to redownload all their data.

There's no good reason to do this. Instead, set the root to `Unspecified`. That means the existing hydrated data is retained but new files will start out as dehydrated.

I consider this p2 and 2.6.0 worthy because the warning dialog doesn't mention that all local data will be deleted.

QA: Sync a folder without vfs. Selective sync exclude some folders. Switch on VFS. Existing files should stay hydrated. The files in the previously excluded folders should appear but be dehydrated. Try with suffix vfs and winvfs.

**Comment by guruz** [comment]
FYI @HanaGemela @jnweiger

**Comment by HanaGemela** [comment]
Works as expected on macOS 10.14.5, 2.6.0alpha2 (build 12128)
Testing on Windows blocked by https://github.com/owncloud/client/issues/7329

**Comment by HanaGemela** [comment]
Works as expected on Windows 10, client 2.6.0beta1 (build 12201)
