### ISSUE TITLE
Remove all files message is too complicated

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7304]
client 260daily20190711 on win10, with demo.owncloud.org

The client was off for a while. The server reset itself, then the client is connected again.
This message pops up.

![image](https://user-images.githubusercontent.com/1108546/61042464-8ae26d80-a3d4-11e9-8d83-45ac91588d9d.png)

The second sentence gives me a hard time. Syncing a "delete" probably means delete the files. If so, please say so. What "right to restore" do I need. Does "making ... unavailable" mean, it is moved to some hidden trashcan, where I need admin rights? If it is simply deleted, then we should say so.

Why is there a warning about "rights to do so" when choosing "keep the files"? Is that different from a normal sync?

The last sentence somehow contradicts the second. It seems to say, that nothing is deleted unless I am the owner. Client runs undermy account, so I am the owner of almost all files here. I don't believe that.

Suggestion:

    Remove All Files?
     
    All files in the sync folder 'ownCloud' were deleted on the server.
    Choose keep  to re-upload to the server.
    Chose remove to delete them locally too.
     
    [Keep]   [Remove]

**Comment by ckamm** [comment]
Simplifying like this looks good to me. Any concerns @michaelstingl ?

**Comment by dragotin** [comment]
How about this:

```
All files in the sync folder 'ownCloud' were deleted on the server.

Do you want to restore them from your local files or also remove locally?

[Restore]    [Remove]
```

**Comment by michaelstingl** [comment]
@hodyroff @pmaier1 could you have a look?

**Comment by hodyroff** [comment]
I remember that this was carefully worded ;) Need to think about it ... at least folder seems twice in the first sentence. The challenge is that if you don't have write access there will be nothing restored, thats why its worded also for read-only users. Was there not a similar message which got cleaned up already?

**Comment by dragotin** [comment]
Does this message also show if a share from another user was removed, and as a result the sync client does not longer see it? That might also influence the wording, because fi the user decides to restore the files, she will create the removed share locally in her space (not longer as a share obviously) what is a bit against the idea ...

**Comment by ckamm** [comment]
The message shows exactly if it's determined that a sync action is performed on every single known file and at least one of them is a deletion.

So in the "share removed" scenario the message would only show if the user has no other files.

**Comment by TheOneRing** [comment]
Another nice piece of information would be the account name/url...

**Comment by jnweiger** [comment]
Dragotin suggested:
> ```
> All files in the sync folder 'ownCloud' were deleted on the server.
> 
> Do you want to restore them from your local files or also remove locally?
> 
> [Restore]    [Remove]
> ```

"Restore" is much better than "keep". Yes! Why did I suggest Keep in the first place? :-)

I just spot now, that we use both delete and remove. I'd suggest to say delete everywhere. That has the nice side effekt to make the two choices more distinct.
Now, how about this:

```
All files in the sync folder 'ownCloud' of demo@demo.owncloud.org were deleted on the server.

Do you want to restore them from your local files or also delete locally?

[Restore]    [Delete]
```

**Comment by TheOneRing** [comment]
Doesn’t sound too bad.
In my test setup I have lots of sync folders so the original message doesn’t tell me anything

**Comment by dragotin** [comment]
Another choice might be to disconnect the sync connection, ie. just leave the local files but do not sync the folder anymore at all.

**Comment by TheOneRing** [comment]
Site note, when fixing this issue, we should also remove the QDialog::exec() call

**Comment by michaelstingl** [comment]
What are the exact conditions when this message is shown? What should change with the VFS? Need more messages?

**Comment by TheOneRing** [comment]
As mentioned in https://github.com/owncloud/client/issues/5931 no button should be pre selected.
Alternatively we could show  "Are you sure you want to delete all data" dialogue after the first one
