### ISSUE TITLE
Client ignores hosts file

### ISSUE THREAD

**Issue by noah95** [owncloud/client#7311]
### Expected behaviour
My oc server is running on a NAS inside my network. Accessible from outside (oc.example.com) but not local with the oc client. I therefore statically assign the local ip to that domain in my `/etc/hosts` file. Google chrome can resolve the URL and oc works.
```
192.168.0.99 oc.example.com
```
### Actual behaviour
No connection to https://example.com/ inside my network. Outside, all works fine.

### Steps to reproduce
1. Setup OC server in nginx virtual host
2. Assign hostname and forward ports
3. Use oc client to connect using the hostname given

### Server configuration
Operating system: Synology NAS DS1511+ DSM 6.1.7-15284 Update 3
Web server: Apache 2.4
Database: Maria DB 10
PHP version: 7.0
ownCloud version: 10.0.4.4
Storage backend (external storage): Synology NAS RAID

### Client configuration
Client version: 2.6.0alpha1
Operating system: Mac OSx 10.14.5 Mojave
OS language: English
Installation path of client: /Applications/

**Comment by ckamm** [comment]
I can't reproduce.
- Added `127.0.0.1    testhost` to `/etc/hosts`
- Added `testhost` to `trusted_domains` for oc instance
- Created an account using http://testhost

What error do you get exactly?

**Comment by noah95** [comment]
The log
```
[ info gui.socketapi ]:	Sending SocketAPI message --> "GET_STRINGS:BEGIN" to SocketApiSocket(0x7fea7ca2e9b0)
[ info gui.socketapi ]:	Sending SocketAPI message --> "STRING:SHARE_MENU_TITLE:Share..." to SocketApiSocket(0x7fea7ca2e9b0)
[ info gui.socketapi ]:	Sending SocketAPI message --> "STRING:CONTEXT_MENU_TITLE:ownCloud" to SocketApiSocket(0x7fea7ca2e9b0)
[ info gui.socketapi ]:	Sending SocketAPI message --> "STRING:COPY_PRIVATE_LINK_MENU_TITLE:Copy private link to clipboard" to SocketApiSocket(0x7fea7ca2e9b0)
[ info gui.socketapi ]:	Sending SocketAPI message --> "STRING:EMAIL_PRIVATE_LINK_MENU_TITLE:Send private link by email..." to SocketApiSocket(0x7fea7ca2e9b0)
[ info gui.socketapi ]:	Sending SocketAPI message --> "STRING::" to SocketApiSocket(0x7fea7ca2e9b0)
[ info gui.socketapi ]:	Sending SocketAPI message --> "GET_STRINGS:END" to SocketApiSocket(0x7fea7ca2e9b0)
[ info gui.account.state ]:	Fetched credentials for "https://oc.example.com" attempting to connect
[ info sync.connectionvalidator ]:	No system proxy set by OS
[ info sync.accessmanager ]:	2 "" "https://oc.example.com/status.php" has X-Request-ID "1a69f7be-e9eb-44ba-8b48-dd6f8c64d77c"
[ info sync.networkjob ]:	OCC::CheckServerJob created for "https://oc.example.com" + "status.php" "OCC::ConnectionValidator"
[ warning sync.networkjob ]:	Network job timeout QUrl("https://oc.example.com/status.php")
[ warning sync.networkjob.checkserver ]:	TIMEOUT
[ info gui.account.state ]:	AccountState connection status change:  OCC::ConnectionValidator::Undefined -> OCC::ConnectionValidator::Timeout
[ info gui.account.state ]:	AccountState state change:  "Disconnected" -> "Network error"
[ info gui.folder.manager ]:	Account "noah@oc.example.com" disconnected or paused, terminating or descheduling sync folders
[ info sync.connectionvalidator ]:	No system proxy set by OS
[ info sync.accessmanager ]:	2 "" "https://oc.example.com/status.php" has X-Request-ID "8f293a34-5df2-4fc0-bbfc-07c40936e509"
[ info sync.networkjob ]:	OCC::CheckServerJob created for "https://oc.example.com" + "status.php" "OCC::ConnectionValidator"
```

I can't ping oc.domain.com but the oc in the web browser works

**Comment by ckamm** [comment]
Thanks. So it can't connect at all and eventually times out.

If you can't ping it, that's suspicious. Can you
```
curl https://oc.example.com/status.php
```
If that doesn't work the problem isn't with the client, but with your `hosts` entry somehow not working.

**Comment by TheOneRing** [comment]
@noah95 if the issue still exists please reopen it

**Comment by noah95** [comment]
@TheOneRing moved the physical server location to another network, thus the issue is resolved for me. Thanks for closing
