### ISSUE TITLE
Cannot edit public link expiration date when it is enforced

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7313]
Client: 2.6.0alpha2 (build 12128)
macOS: 10.14.5
Server: 10.2.1. (stable)

Steps to recreate:
1) In the client create a public link without an expiration date
2) On the server go to Settings -> Admin -> Sharing
3) Tick 'Enforce expiration date' checkbox
4) Go back to the client and set expiration against the link created in the step 1 (Client restart might be needed to get the new settings from the server)

Actual result: 'Set expiration date' is greyed out so it cannot be changed
Expected result: Expiration date can be set

**Comment by TheOneRing** [comment]
@HanaGemela can you have a look and close this issue if its fixed :)
