### ISSUE TITLE
Changing update channel from beta to stable should downgrade

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7314]
When changing the update channel of the client, we get this message:

> 
> The update channel determines which client updates will be offered for installation. The "stable" channel contains only upgrades that are considered reliable, while the versions in the "beta" channel may contain newer features and bugfixes, but have not yet been tested thoroughly.
> 
> Note that this selects only what pool upgrades are taken from, and that there are no downgrades: So going back from the beta channel to the stable channel usually cannot be done immediately and means waiting for a stable version that is newer than the currently installed beta version.

Enhancement idea: Make downgrades possible.

**Comment by guruz** [comment]
I don't think we don't really support downgrades no matter how...

**Comment by michaelstingl** [comment]
> So going back from the beta channel to the stable channel usually cannot be done immediately and means waiting for a stable version that is newer than the currently installed beta version.

Works for me
