### ISSUE TITLE
Selective Sync and VFS should not be exclusive

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7320]
When I switch to virtual files, the number of files and folders in my sync folder connection explodes as compared with selective sync. 

I would like to use selective sync as way to hide unneeded folders from view, when browsing files on my local machine.

I know at least two other colleagues who personally think the same, they say.

**Comment by ckamm** [comment]
Why is the number of files something you're concerned about?

I think having both is confusing from a user point of view. Files could then be invisible, visible but online-only, or visible and available. I imagine most users don't care about the invisible / visible+unavailable distinction.

If it were enabled we'd need to make sure the current "selective sync" ui is integrated with vfs availability states so there's one place to see and edit everything.

**Comment by michaelstingl** [comment]
> If it were enabled we'd need to make sure the current "selective sync" ui is integrated with vfs availability states so there's one place to see and edit everything.

Yeah, this describes the problem. We would have 4 places where users get in touch with syncing or not syncing of files…

1. "File Explorer" (VFS in right-click menu)
2. "Selective Sync" for every sync folder pair
3. "Not synced" tab where users can check what files doesn't sync
4. "Ignored Files", another place where users can configure something

Ideally, we only need "1." and can combine "2."+"3."+"4." in one view… (needs a concept)

**Comment by Draghmar** [comment]
I'd like to remove some files/folders from being ever sync even if they are available locally. This for the situations when the folder is synced but some files there are per machine. I do understand that it is not the usual case but a handy one. 
At the moment I can achieve something similar by first doing offline sync and then using filtering to remove files from being synced. So the concept already exists but the UI is far from being ergonomic.

**Comment by jnweiger** [comment]
I received a huge share (ca 80.000 files) from one of my colleagues. 
Whenever I connect a new windows client to this account, it takes several hours scanning that share. During this time the CPU and network loads are high. Windows is still usable, but sluggish.

On Linux, I have selective sync, so that I can skip such a folder. On Mobile, folders trees are only crawled on directory at a time, when the user enters a directory. On windows with default winVFS, there is no option, to get back to speed. I have to patiently wait.

**Comment by TheOneRing** [comment]
Not planned
