### ISSUE TITLE
Misaligned icons when clicking on the local sync folder

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7321]
Client: 2.6.0alpha2 (build 12128)
macOS: 10.14.5
Server: 10.2.1. (stable)

Steps to recreate: 
1) Click on the local sync folder in the account tab (e.g. on the cloud icon with green check mark)

Actual result: The icons below have moved down for a second. Then they've returned back
Expected result: Icons stay where they are supposed to

![image](https://user-images.githubusercontent.com/49001702/61445149-1b78fa80-a94d-11e9-8484-7dd4afd6b82b.png)

**Comment by ckamm** [comment]
I couldn't reproduce it on linux, maybe OSX specific? Does it happen every time @HanaGemela?

**Comment by HanaGemela** [comment]
@ckamm for VFS folders it happens for every other click. For normal folders it happens every time
Works OK on Windows 2.6.0alpha2 (build 12097)

**Comment by TheOneRing** [comment]
Can't reproduce
