### ISSUE TITLE
File doesn't stay hydrated after viewing 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7322]
Client: 2.6.0alpha2 (build 12128)
macOS: 10.14.5

Steps to recreate

1. Folder has VFS on
2. User opens one file to view it 

Actual result: The file has been downloaded, opened and immediately dehydrated again
Expected result: File stays hydrated

**Comment by guruz** [comment]
Fix only in after alpha2

**Comment by HanaGemela** [comment]
Works as expected on macOS 10.14.6, client 2.6.0beta1 (build 12241)
