### ISSUE TITLE
File gets dehydrated when it is supposed to be always available locally 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7323]
Client: 2.6.0alpha2 (build 12128)
macOS: 10.14.5
Server:10.2.1. (stable)

Steps to recreate:

1. Folder has VFS on
2. User makes one file in VFS folder always available locally
3. User opens another VFS file from that folder

Actual result: The hydrated file that is supposed to be always available locally gets dehydrated
Expected result: Both files are hydrated

**Comment by HanaGemela** [comment]
Might be the same cause as in https://github.com/owncloud/client/issues/7322

**Comment by guruz** [comment]
Fix only in after alpha2

**Comment by HanaGemela** [comment]
Works as expected macOS 10.14.6, client 2.6.0beta1 (build 12241)
