### ISSUE TITLE
'Add Folder Sync Connection' button is bigger than it looks like

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7326]
This applies to all clients I just managed to get a nice screenshot on Windows 2.6.0alpha2 (build 12097)

'Add Folder Sync Connection'  button is small but clicking anywhere around it or on the entire row also opens 'Add Folder Sync Connection' window

![image](https://user-images.githubusercontent.com/49001702/61461717-86d4c380-a971-11e9-9e6b-df0f443cb25e.png)

**Comment by ogoffart** [comment]
PR: https://github.com/owncloud/client/pull/7529

**Comment by HanaGemela** [comment]
Works as expected in 2.6.1daily20191127 (build 12732), Windows 10
