### ISSUE TITLE
Excluding all folders from sync triggers 'All files were deleted on the server message' message

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7337]
Client: 2.6.0alpha2 (build 12128)
macOS: 10.14.5
Server: 10.2.1. (stable)

Steps to recreate:
1) Make sure there are no files directly in the root directory 
2) Deselect all folders in the selective sync list
3) Confirm your selection

Actual result: Message that 'all files were deleted on the server'
Expected result: No message, the files are removed only locally 

4) When user selects 'Keep all'

Actual result:
Checkboxes in the selective sync list are not checked
There are no icons against the files even though the account is connected to the server

![image](https://user-images.githubusercontent.com/49001702/61722793-35f70d80-ad6b-11e9-8a91-e79fe80e4e6f.png)

**Comment by ogoffart** [comment]
PR: https://github.com/owncloud/client/pull/7530

**Comment by HanaGemela** [comment]
Works as expected in 2.6.1-daily20191127 (build 12791), macOS 10.15.1
