### ISSUE TITLE
Windows vfs incorrectly thinks an implicitly hydrated 0 byte file stays dehydrated

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7339]
Found while testing #7111 

- Create a folder
- Put a 0 byte file into it
- Use "Free up space"
- Double click it to hydrate it without pinning it

Right click the folder and check the availability status in the ownCloud submenu. It'll say the contents are online only.

The problem here is that since no download needs to happen the cfapi "fetch" callback doesn't trigger and the client therefore doesn't realize that the file was hydrated and can't update the database.

**Comment by gabi18** [comment]
I'm not sure about this:
> Right click the folder and check the availability status in the ownCloud submenu. It'll say the contents are online only.
>

The availibity status isn't in the ownCloud submenu but in file menu... ?

![issue-7339](https://user-images.githubusercontent.com/75983861/145204306-2cd216eb-78c1-454c-b5a2-11fd6dc567e2.png)

**Comment by gabi18** [comment]
Next step done:
- 'Free up space' on folder
Result: icon remains spinning
![issue-7339_free_up_space](https://user-images.githubusercontent.com/75983861/145204879-2712b22a-bcb3-45bb-9ac1-ca7bdd0a7acc.png)

**Comment by TheOneRing** [comment]
Thx for testing
