### ISSUE TITLE
When a new folder is created it always syncs twice, even on success

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7345]
Create a new sync folder. Wait for the initial sync to finish. A second sync will be triggered.

The log shows:
```
Compare etag with previous etag: last: "\"foo\"", received: "foo" -> CHANGED
```

That means there's still a place where etag parsing isn't done consistently. This appears now because I fixed a different (more rare) case where etag parsing wasn't done.

**Comment by HanaGemela** [comment]
Works as expected on Windows 10, 2.6.0beta1 (build 12201)
