### ISSUE TITLE
.owncloudsync.log does not contain duration

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#7348]
### Expected behaviour
The .owncloudsync.log should contain the duration column.

### Actual behaviour
The column (it's the second one after the timestamp) is always empty. It used to be there, but was eliminated.

### Client configuration
Client version: 2.5.4, but also master

The .owncloudsync.log is a useful file to make examinations about the sync operation of the client for advanced users. I often use it to check the what happened. I think it is an important feature for people who appreciate transparency of their tools, especially in complex things like file sync. That is a benefit of free software IMHO, and it should be maintained carefully ;-)

The duration was removed in patches like 4aeaa67caeea952a567c9d5c036fbe7c8aeba880. I think that is the wrong way. The less information the log contains the less useful it is. Please consider to bring the full data back. Maybe there is a good way of disabling it for "normal" use?

Also, the reason for saving it because of memory usage is not longer valid because you do not build the full reconcile list any more, right @ogoffart ?

Thanks for considering!

**Comment by HanaGemela** [comment]
Test passed
ownCloud 3.0.0.8922-alpha9 [8e733b]
macOS 13.0
