### ISSUE TITLE
client commandline parameters do not create log files

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7351]
Seen with 2.5.4
```owncloud --logdir /tmp/clientlogs --logdebug --logexpire 48```
should fill /tmp/clientlogs with logfiles. 

It does not, unless the user opens the GUI and removes the checkmarks at [x] permanently save.

@patrickjahns possibly fixed in 2.6.0

**Comment by ckamm** [comment]
Can't reproduce with 2.6.0, probably fixed there.
