### ISSUE TITLE
Tray icon still white with Windows light theme

### ISSUE THREAD

**Issue by krnkktz** [owncloud/client#7356]
Client version: Version 2.4.3 (build 10188) on Windows 10 1903

With the Windows 10 1903 update, a new light theme is available. When using monochrome icons with the light theme on, the dark systray icons should be used. Instead, the systray icon remains white on a light background and is unreadable.

![image](https://user-images.githubusercontent.com/15186493/62171786-7852b880-b330-11e9-8e2e-f35be9a1fe30.png)

If my understanding of the code is correct, implementing [hasDarkSystray_private](https://github.com/owncloud/client/blob/4d0e4c0a18ace992c641f7805b61f611301285c6/src/common/utility_win.cpp#L97) to detect the theme should solve the issue.

To reproduce:
Under Owncloud > General, set "Use Monochrome Icons".
Under Windows 10 Settings > Personalization > Colors, set "Choose your color" to "Light".

**Comment by michaelstingl** [comment]
> Client version: Version 2.4.3 (build 10188) on Windows 10 1903

Please check with latest stable 2.5.4:
https://owncloud.org/download/#owncloud-desktop-client-windows

**Comment by krnkktz** [comment]
Reproduced with 2.5.4 (build 11415) (understandably, see [theme.cpp](https://github.com/owncloud/client/blob/5cbf60c6f4c3e57cfeb679bee6e9fb28c829a562/src/libsync/theme.cpp#L264) and [utility_win.cpp](https://github.com/owncloud/client/blob/4d0e4c0a18ace992c641f7805b61f611301285c6/src/common/utility_win.cpp#L97)).
