### ISSUE TITLE
after execute command “docker-compose down -v”, the data uploaded have all lost, how to recovery

### ISSUE THREAD

**Issue by zjuskm** [owncloud/client#7358]
my owncloud work fine almost one year which is installed using docker-compose command following [this site](https://doc.owncloud.org/server/10.0/admin_manual/installation/docker/).
 Until these days users say it can not login in, then I login to the server to the directory with file docker-compose.yml exists. And I found ownclouddockerserver_owncloud_1 restarting look like this 
![image](https://user-images.githubusercontent.com/5374191/62272057-c076f580-b46c-11e9-9b3e-864ad58ff248.png)
To fix the restarting problem, I execute command "docker-compose down -v", then the users' data all lost. 
So ask for how can I rescovery the user data, or does the docker-compose installation method has default backup strategy.

### Expected behaviour
Tell us what should happen
How to restore lost data after execute command "docker-compose down -v"
### Actual behaviour
Tell us what happens instead
After execute command "docker-compose down -v", no action I operate.
The owncloud can work normally, but data lost.

### Steps to reproduce
1.  Install owncloud using docker-compose following [this](https://doc.owncloud.org/server/10.0/admin_manual/installation/docker/)
2.  Create some user account, and upload some data like text file, image and so on.
3.  The owncloud not work healthy, always restarting(not know how to reproduce)
4.  Execute command "docker-compose down -v"
5.  How to restore lost data, does owncloud have default backup strategy to find the user data.

### Server configuration
Operating system:
Ubuntu 18.04.1 LTS
Web server: 

Database:

PHP version:
PHP 7.2.19
ownCloud version:
10.0.9 (stable)
Storage backend (external storage):
2T disc

**Comment by michaelstingl** [comment]
@zjuskm this is the issue tracker for the ownCloud desktop sync client, not a help forum. Better check https://central.owncloud.com/ for help.

With the -v parameter, you deleted the volumes that persist your files and database. This is how Docker-compose works, not a bug.

**Comment by zjuskm** [comment]
@michaelstingl Sorry for this, I am so anxious to ask for somone know owncloud well to help. There will not be another time.
