### ISSUE TITLE
Pop up warning when deleting a virtual file

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7360]
Follow up for #6875

Current behavior:
- Delete a local dehydrated virtual file
- suffix vfs: it is recreated on the next sync run
- win vfs: it is deleted from the server

Both behaviors surprise some users. Some expect that virtual file deletion has no effect, some expect that the remote file gets deleted.

Suggested enhancement: 
- On deletion a warning dialog pops up notifying the user about the behavior. 
- The warning pops up immediately on deletion, not during sync. 
- Users can choose to stop having the warning pop up (check box in dialog?)
- If the user didn't disable the warning and it failed to come up for some reason (like, client was not running), the safer "recreate local virtual file" behavior is chosen.

**Comment by HanaGemela** [comment]
We also need a warning before deleting a folder as the behaviour is different. 
On suffix VFS:
Folders will be deleted on the server
Files cannot be deleted and will be recreated on the next sync

**Comment by TheOneRing** [comment]
Windows behavior is the intended one, the suffix vfs is broken.
