### ISSUE TITLE
Crash after switching between VFS and Selective sync 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7368]
I've moved the comments from https://github.com/owncloud/client/issues/7281 to a separate issue

Switching between VFS and Selective sync quickly causes a crash:
bf781858-2481-49d7-85b9-f7f058bc5ea9

When turning on the client after previous crash caused by the scenario described above:
640a9068-e964-4cd6-bd5c-3627b382ab6c 

Another scenario:
Server: 10.2.2 (stable)
Client: macOS 2.6.0.12241beta1
User has an unavailable folder, an unavailable file (503 errors), a big file... then switches between VFS and selective sync and then the client crashes. 
This time I cannot start the client again. On each start the client crashes immediately (e.g. 341ceedf-abad-47d1-b035-462f7e8c7f92 or cb0728c9-8c84-467d-9b0c-4d79d52f7db3). Logs shares

**Comment by HanaGemela** [comment]
I've tried with newer build with Ot 5.12.4 (2.6.0-daily20190806 (build 12251))
crash: 8a0c1b20-e22d-4071-ad4d-ce8034e7c130

**Comment by guruz** [comment]
Havent looked at the bt, but maybe 2.6.0?! @ckamm

**Comment by ckamm** [comment]
Seems to be a crash in `calcCryptoHash()`
- https://sentry.io/organizations/owncloud/issues/1142050016/events/8a0c1b20e22d4071ad4dce8034e7c130/?project=79001&statsPeriod=14d
- with deeper stacktrace: https://sentry.io/organizations/owncloud/issues/1142008010/events/cb0728c98c84467d9b0c4d79d52f7db3/?project=79001&statsPeriod=14d

**Comment by ckamm** [comment]
It crashes in `QObject::objectName()`. I assume the QIODevice is somehow deleted while the checksum computation is running.

**Comment by HanaGemela** [comment]
Cannot recreate in 2.6.0rc1 (build 12411), believed to be fixed. mac 10.14.6
