### ISSUE TITLE
[Windows] [Linux] 2.6.0beta1 (build 12201) the client only show a white (or black) window at second opening of tray icon

### ISSUE THREAD

**Issue by DangerSchwob** [owncloud/client#7371]
Hi,

Client Version: 2.6.0beta1 (build 12201)
Server Version: 10.2.1.4
OS Version: Microsoft Windows 10 Pro - 10.0.18362 Build 18362

Issue: When you open the ownCloud client window via tray icon, the first time all working fine, but the second time and later you get only a white window

![grafik](https://user-images.githubusercontent.com/22342104/62759153-d4c87d00-ba80-11e9-9618-ebafa62018b9.png)

Resizing the window or click somewhere in the navbar, where a navigation button is, bring everything back, but if you close and open the window, you see the same issue again.

If you find in the white window the "account" button, you see also all again, but when the menu closing, the whole client crashing. CrashID: bf541872-6a27-4ea9-a8cb-910da4f9ff2f

![grafik](https://user-images.githubusercontent.com/22342104/62759561-efe7bc80-ba81-11e9-97d9-ea2f19cdaf0c.png)

**Comment by jnweiger** [comment]
Similar, but black instead of white:
2.6.0daily 20190916 on debian 8

 - connect, then close the settings dialog.
 - run the client again to trigger reopening the settings dialog. 
 - It appears all black,
 - Workaround: click the mouse near the top left corner of the black area. This causes a refresh.

**Comment by guruz** [comment]
@HanaGemela @jnweiger Let's try to achieve this for 2.6.0, it sounds rather annoying?

**Comment by TheOneRing** [comment]
I'll do

**Comment by guruz** [comment]
> If you find in the white window the "account" button, you see also all again, but when the menu closing, the whole client crashing. CrashID: bf541872-6a27-4ea9-a8cb-910da4f9ff2f

Sounds also very Qt-ish..:

```
EXCEPTION_ACCESS_VIOLATION_READ

Fatal Error: EXCEPTION_ACCESS_VIOLATION_READ



    Qt5Widgets0x6a3e5c50QWidget::windowHandle qwidget.cpp:2660

Qt5Widgets0x6a3f6fe6QWidgetWindow::handleMouseEvent qwidgetwindow.cpp:591
Qt5Widgets0x6a3f5446QWidgetWindow::event qwidgetwindow.cpp:281
Qt5Widgets0x6a3b4889QApplicationPrivate::notify_helper qapplication.cpp:3737
Qt5Widgets0x6a3b38fdQApplication::notify qapplication.cpp:3692
Qt5Core0x6995feec<unknown> 
```

https://sentry.io/organizations/owncloud/issues/1147233037/events/bf5418726a274ea9a8cb910da4f9ff2f/?project=79001

**Comment by guruz** [comment]
@HanaGemela Looks like you accidently moved this to 2.6.1 :-)

**Comment by guruz** [comment]
I see this in a Jenkins log:
>  > git checkout -f 70ee58303f22c9ec3457144aee8d4b02ca478a47
Commit message: "prepare for qt 5.12.5 : testpilotlient 2.6 has it already, owncloud 2.6 remains at 5.12.4"

@jnweiger

**Comment by guruz** [comment]
On macOS the window does not become black/white but still somehow gets re-created and is then in the wrong non-unified style.

After launch:
<img width="447" alt="Bildschirmfoto 2019-09-24 um 10 31 06" src="https://user-images.githubusercontent.com/959327/65495189-995e0280-deb6-11e9-923c-79ff4bdb0f1e.png">

After closing and opening window:
<img width="453" alt="Bildschirmfoto 2019-09-24 um 10 30 24" src="https://user-images.githubusercontent.com/959327/65495170-8fd49a80-deb6-11e9-8f4d-d3240ca52829.png">

**Comment by guruz** [comment]
If i glimpse through https://code.qt.io/cgit/qt/qtbase.git/log/?h=5.12.5 (clicking next a few times until 5.12.4) i see quite some commits related to window(s) or painting.
So it's worth a try to update Qt.

**Comment by guruz** [comment]
@dschmidt I hate to say that, but with 5.12.5 it behaves  even worse **on macOS** :-(
The window gets transparent.
Maybe we need as quick hotfix disable any fancyness we do with @shadone 's special macOS toolbar. https://github.com/owncloud/client/blob/master/src/gui/settingsdialogmac.cpp


![Bildschirmfoto 2019-09-25 um 09 13 05](https://user-images.githubusercontent.com/959327/65577935-1a7bcf00-df75-11e9-9c26-d8f8eb5b81e3.png)

Version 2.6.026 (build 12498)
Gebaut aus der GIT-Revision 88de51 am Sep 24 2019, 20:28:11; verwendet Qt 5.12.5, OpenSSL 1.1.1d 10 Sep 2019

Or we keep 5.12.4 for now on macOS and live with the not so grave issue https://github.com/owncloud/client/issues/7371#issuecomment-534453553 until we fix it with 5.12.5

**Comment by shadone** [comment]
I am sorry about that. I don't think I'll have time in the near future to look into this myself, so feel free to remove this ~prettyness~hack :)

**Comment by guruz** [comment]
Unfortunately
```
plutil -remove NSRequiresAquaSystemAppearance /Applications/owncloud.app/Contents/Info.plist
```
Does not help to fix it :/

**Comment by guruz** [comment]
Temporarily removing the MacSettingsDialog in https://github.com/owncloud/client/pull/7492
(Then dialog behaves like on other OS, e.g. it does not auto-resize the window and it has an ugly 'Close'-Button)

**Comment by jnweiger** [comment]
I haven't seen the any blank windows own Linux since we updated to 5.12.5 -- I'd assume its fixed with 5.12.5

How about mac? @DangerSchwob did you have a chance to try a daily with 5.12.5 ?

**Comment by DangerSchwob** [comment]
@guruz : Sorry for the delay. I were off for some days.

I'm unable to reproduce the issue with this version (2.6.0rc2 (build 12524))

Looks like the issue is fixed. I wil test it the next days also on other machines.

**Comment by guruz** [comment]
Great!
