### ISSUE TITLE
Creating the Docker image for building the Win32 client fails: manifest for opensuse:42.1 not found

### ISSUE THREAD

**Issue by jkraemer** [owncloud/client#7387]
### Expected behaviour

Following the instructions in https://doc.owncloud.org/desktop/2.5/building.html#windows-installer-build-cross-compile should allow me to build the Win32 client on Linux. However it isn't possible to create the docker image.

### Actual behaviour

~~~~
> sudo docker build -t owncloud-client-win32:2.5 client/admin/win/docker/
Sending build context to Docker daemon  4.608kB
Step 1/14 : FROM opensuse:42.1
manifest for opensuse:42.1 not found: manifest unknown: manifest unknown
~~~~

I believe this has to do with https://github.com/docker-library/official-images/issues/5371

**Comment by fmoc** [comment]
This docs page has been removed since. I couldn't find it any more. I presume we don't support this cross-compilation workflow any more?

See https://doc.owncloud.com/desktop/next/appendices/building.html for the current workflows.
