### ISSUE TITLE
Installer downloaded even though it doesn't exist

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7390]
Windows 10
Client beta1
Online updater: client-qa-server-0.4

Steps to recreate:

1. Set a wrong download url (https://download.owncloud.com/desktop/daily/ownCloud-11.6.0.12480.12264-daily20190807.msi) on the online updater
2. Click 'Restart&Update' button in General tab in the client (new version has to be available to see this button)
3. Check the 'Update failed' dialog message

Actual result: The message says that the installer has been downloaded and it really is present in AppData\Roaming\ownCloud
Expected result: File has not been downloaded as it doesn't exist
---
TODO:
- Allow https redirects
- Download to a temporary file and only rename to the actual name if the download was successful

**Comment by ckamm** [comment]
I don't understand this one. There already is error handling for catching bad downloads. Will need to try to reproduce.

**Comment by TheOneRing** [comment]
Ensure the download was successful and follow https redirects, right now we don't even follow redirects to our attic server.
On a redirect we write the http response to the target file....
