### ISSUE TITLE
KDECraft

### ISSUE THREAD

**Issue by reberthkss** [owncloud/client#7391]
Can help me??
![erro](https://user-images.githubusercontent.com/54030471/63074201-77aa4c80-bf02-11e9-865b-3814987f5b5c.png)

**Comment by TheOneRing** [comment]
Please install python2 and adjust your settings.
https://www.python.org/downloads/

**Comment by michaelstingl** [comment]
@reberthkss  this is the issue tracker of the ownCloud desktop sync client, not a help forum. Please use https://central.owncloud.org/ instead.
