### ISSUE TITLE
German translation confuses "stop" and "pause"

### ISSUE THREAD

**Issue by FlominatorTM** [owncloud/client#7395]
am running 2.5.4 build 11415 on Windows 10 1809. When I right click a synced folder and select "pause synchronisation" I receive this error message:

![Unbenannt](https://user-images.githubusercontent.com/12448283/63094371-76ac0600-bf68-11e9-9ba1-451157ddcfbe.png)

This can be read as "a synchronisation is running currently. do you want to stop it".

"Wollen Sie sie beenden?" I would replace by "Wollen Sie sie unterbrechen?" which does not have this connotation of "stopping for good" or "canceling"

I tried creating an account at Transifex but I neither managed to find the text, nor to join the team.

Maybe somebody else could change it?

Thanks

Flo

**Comment by jnweiger** [comment]
The original string is 

    The syncing operation is running. Do you want to terminate it?

I agree that stop is the wrong connotation. But using 'terminate' in the english phrase is also pretty harsh.

With end users in mind, I agree that "unterbrechen" is a better choice here. Fixed in transifex.
