### ISSUE TITLE
Warning every 2 seconds when file not found

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7397]
Windows 10
Client: 2.6.0daily20190807 (build 12211)
Server: 10.2.1

Steps to recreate:
1) Make sure there is a file on the server that is 'Not found'

<img width="807" alt="Screenshot 2019-08-15 at 14 31 10" src="https://user-images.githubusercontent.com/49001702/63094782-968ff980-bf69-11e9-8808-d8f6f03fe9e8.png">

2) Turn on the desktop client

Actual result: Desktop sync client notifies a user every two seconds. Logs shared
Expected result: Only one notification that this file has not been synced 

<img width="971" alt="Screenshot 2019-08-15 at 14 28 09" src="https://user-images.githubusercontent.com/49001702/63094787-9b54ad80-bf69-11e9-8bb7-f1f3f0ebb918.png">

<img width="1440" alt="Screenshot 2019-08-15 at 14 28 36" src="https://user-images.githubusercontent.com/49001702/63094802-a6a7d900-bf69-11e9-97d3-8ca00ced11c6.png">

**Comment by michaelstingl** [comment]
> Desktop sync client notifies a user every two seconds

🙀 

Our usual blacklisting should work here.

**Comment by michaelstingl** [comment]
> 1. Make sure there is a file on the server that is 'Not found'

@HanaGemela Could you share the detailed steps to reproduce?

**Comment by HanaGemela** [comment]
I don't know at the moment. But the same behaviour is already described here https://github.com/owncloud/client/issues/6953#issuecomment-519005689 
In that case the problematic file was virtual file on the server.

**Comment by ogoffart** [comment]
Yes, steps to reproduce would be nice.

**Comment by TheOneRing** [comment]
Closing after being in needs info for more than a year
