### ISSUE TITLE
Change the color of VFS box so the account doesn't appear online and synced 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7403]
'Virtual file support is enabled.' text is displayed in a green box. That makes the account look connected and synced. So even though the user is signed out, their account is green which evokes online state. 

<img width="790" alt="Screenshot 2019-08-16 at 14 59 04" src="https://user-images.githubusercontent.com/49001702/63170093-cfe36a80-c038-11e9-837d-c2d7be46556d.png">

**Comment by ogoffart** [comment]
What color do you suggest?

**Comment by HanaGemela** [comment]
Blue or grey to match the rest of the dialog

**Comment by ogoffart** [comment]
How about  this:  (this is what one get if we invert the green and blue component in the color)

![image](https://user-images.githubusercontent.com/959326/66814874-98f5dc00-ef37-11e9-98f2-ee8370c9b74d.png)

**Comment by HanaGemela** [comment]
Nice
