### ISSUE TITLE
Windows Virtual file support is now technical preview 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7406]
Remove all references to 'Experimental' on Windows
Virtual files are now technical preview

Replace 'Experimental' with 'Tech preview'

**Comment by HanaGemela** [comment]
PR https://github.com/owncloud/client/pull/7394

**Comment by HanaGemela** [comment]
Failed on Windows 10, 2.6.0daily20190820 (build 12286):
The change of the button in the three dots menu in Account tab is missing. The button is 'Enable virtual file support (experimental)'

Connection wizard also not changed
<img width="566" alt="Screenshot 2019-08-20 at 10 22 21" src="https://user-images.githubusercontent.com/49001702/63330805-bdb54500-c334-11e9-9401-8d2ea9ed3284.png">

Still to be tested: Old windows version

**Comment by ckamm** [comment]
I assume with https://github.com/owncloud/client/pull/7424 merged this is ready to test again.

**Comment by HanaGemela** [comment]
Virtual files are now called tech preview on Windows 10 with client 2.6.0rc1 (build 12357)

**Comment by HanaGemela** [comment]
I've successfully updated from 2.6 beta1 to 2.6 rc1
