### ISSUE TITLE
Suffix VFS - ask before deleting a resource

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7407]
Suffix VFS:

There should be a warning message before deleting a file or a folder informing users what will happen:
Folders will be deleted on the server
Files cannot be deleted and will be recreated on the next sync

**Comment by michaelstingl** [comment]
Duplicate for https://github.com/owncloud/client/issues/7360 ?

**Comment by HanaGemela** [comment]
@michaelstingl OK, I'll add a comment to #7360, move it to 2.6.1 and close this one
