### ISSUE TITLE
External storage is copied into a new folder after renaming or moving

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7408]
Client: 2.6.0beta1 (build 12241)
macOS: 10.14.6
Server: 10.2.1

Steps to recreate: 
1) Rename an external storage (Windows Network Drive)

Actual result: External storage has been copied into a new folder with a new name
Expected result: Rename not allowed

**Comment by HanaGemela** [comment]
The same behaviour happens for moving the external storage

**Comment by ogoffart** [comment]
If you do not have the permission to delete, this is the expected behavior: the original name gets restored.

**Comment by HanaGemela** [comment]
@michaelstingl please confirm this is the expected behaviour. After renaming or moving user has two copies of that folder

**Comment by HanaGemela** [comment]
Could there be at least a notification that a user doesn't have permissions to delete therefore a new copy with a new name has been created. User might not know that they don't have the permission and this is surprising behaviour

**Comment by TheOneRing** [comment]
Expected behaviour
