### ISSUE TITLE
Windows: libssl is not installed reliably

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7409]
Earilier I tried to install beta1 from the msi package on Windows. The installation succeeded. I did not reboot. When I tried to start owncloud there was an error that `libssl-1_1.dll` was missing.

Installs often succeed. We don't yet know how to reproduce.

**Comment by ckamm** [comment]
I've tried three times, twice installing from scratch and once upgrading from 2.5.4 and couldn't reproduce the problem.

**Comment by jnweiger** [comment]
May be relevant if user chooses 'yes' or 'no' on the requesters he gets while installing / upgrading.
I had tried several combinations last week, including client hangs and system complains that it cannot be stopped. Maybe there are multiple ways how things can block during unstall/uninstall, maybe there are races.

Not yet reproducable on my side too. 

Do we know, if the client always uses the libssl from its own tree, or could it also pick up a lib elsewhere? I have typically 3 or 4 copies of libssl-1_1.dll in the system.

**Comment by ckamm** [comment]
It'd use any libssl in path. In my tests I checked the install directory to verify it got installed correctly.

**Comment by TheOneRing** [comment]
@ckamm you are using vanilla qt? Craft builds qt with openssl linked.
