### ISSUE TITLE
Renaming deletes the original file when user has delete but not change/create permissions

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7410]
Windows 10
Client: 2.6.0daily20190820 (build 12286)
Server: 10.3.0 alpha, 10.2.1.4

Steps to recreate:
1) User1 shares a folder with a group without change and create permissions. The folder includes one file 
2) User2 (member of that group) renames the file

Actual result: File has been deleted from User1
Expected result: Account of User1 unchanged, User2 got a warning message that renaming (changing) not allowed

**Comment by guruz** [comment]
If this only happens with 10.3 alpha,are you in the right repo?

**Comment by sharidas** [comment]
At least in the webUI where user2 requests for MOVE is made with url `remote.php/dav/files/$username/$foldername` dav Forbidden exception is thrown.

**Comment by michaelstingl** [comment]
Compare requests from client 2.6.0 and 10.x web UI ? @jnweiger Could you have a look?

**Comment by patrickjahns** [comment]
@HanaGemela 
Is this only an issue on 10.3.0alpha - or also with 10.2.x ?

**Comment by HanaGemela** [comment]
@patrickjahns also 10.2 as mentioned in the description

**Comment by jnweiger** [comment]
Server involved should be irrelevant here. It is a dataloss, that the client can easily prevent all by itself, 

10.3 web interface: Rename of a file or folder is not available in this case -> No problem.
10.2 web interface: Rename of a file or folder is not available in this case -> No problem.

Client probably goes down the pipe when MOVE throws a forbidden exception and it tries to workaround with copy and delete locally.

The new local file won't sync to the server, but the delete action will. 
By breaking an atomic move action up into two unrelated actions, we create a data loss. -> reassign @guruz

**Comment by jnweiger** [comment]
The code responsible for this behaviour is
https://github.com/owncloud/client/blob/2.6/src/libsync/discovery.cpp#L1231

I read this as: 
* we see, that server does not allow the new file to be created. Missing hasPermission(RemotePermissions::CanAddFile) for the new name.
* we decide that a rename would not work, and to avoid more rename attempts we remove the etag.
* another effect of removing the etag is: The "move transaction" breaks apart into whatever independant(!) actions the next sync run will decide to do.
* The next sync run discovers changes on both oldname and newname and schedules actions for each of them. One delete, one create.
* Bummer.

**Comment by jnweiger** [comment]
@ogoffart do you remember if this is intended behaviour? I see your name near that code...

**Comment by ogoffart** [comment]
Was there really a change in the server?  (Is it a regression ?)

As for the logic, the code there is just a port of the logic from 2.5
https://github.com/owncloud/client/blob/2.5/src/libsync/syncengine.cpp#L1523
Which as added in commit 2f284209d89fd2d1ba64215775ede71c190d0dd1 whose message explain the rational.

This should work because the server should forbid the deletion, so the file should be restored.  
If the server claims that the file cannot be rename, it is strange that it allow it to be deleted.

The logic is the way it is because the old discovery algorithm did not allow to easily do better in this case.  But as the comment in the new code say, some other resolution could be done now.  Option include: showing an error without trying to restore; renaming/moving the file back to its original location (meh... not user friendly); imediatly converting to recover the old file and upload the new one (this is almost the same as the current behavior, but was not possible with the old discovery).

**Comment by michaelstingl** [comment]
> Was there really a change in the server?

No, 10.3.0 alpha not different than 10.2.1.4

**Comment by PVince81** [comment]
> If the server claims that the file cannot be rename, it is strange that it allow it to be deleted.

It's only strange when people would set strange permissions. Sadly over the years we always supported this complex model of weird permission combinations. See first post in https://github.com/owncloud/docs/issues/361 for an overview... (the matching docs page is misformatted https://doc.owncloud.com/server/10.2/admin_manual/configuration/files/file_sharing_configuration.html#personal-share-2)

**Comment by jnweiger** [comment]
@ogoffart it is not caused by a server change. I just reproduced the same issue with client 2.6beta1 and server 9.0.9
Absolute indentical behaviour there.

**Comment by HanaGemela** [comment]
2.6.0rc1 (build 12411), mac 10.14.6:

The error message is 'no permission to add files'

<img width="777" alt="Screenshot 2019-09-09 at 14 58 15" src="https://user-images.githubusercontent.com/49001702/64532692-4b6fc900-d312-11e9-884c-7675a7073410.png">

The error message should state that rename is not allowed and the file should be either renamed back to the original name so it is still synced or the message should mention the original name and if the user renames the file back, it gets synced again. Currently renaming to the original file name causes the same 'not allowed to add new files' error

But the original issue has been fixed - no dataloss. The file is not deleted from the owner. Therefore moving to the next milestone

**Comment by michaelstingl** [comment]
> But the original issue has been fixed - no dataloss.

@HanaGemela Please open a new issue for the remaining tasks, then close this one.

**Comment by HanaGemela** [comment]
Continues in https://github.com/owncloud/client/issues/7490
