### ISSUE TITLE
Default sharing permissions are ignored

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7412]
Windows 10
Client: 2.6.0daily20190820 (build 12286)
Server: 10.3.0 alpha, 10.2.1.4

Steps to recreate:
1) On the server go to Settings -> Admin -> Sharing
2) Untick all default sharing permissions
3) Restart the client
4) Share a resource 
5) Check the default sharing permissions

Actual result: Full permissions
Expected result: No permissions as all were unticked in the settings

**Comment by HanaGemela** [comment]
Increasing the priority as this used to work in 2.5.4 (Windows)
Needs fixing in 2.6.1

**Comment by HanaGemela** [comment]
Still broken in 2.6.1sprint1 (build 12882), macOS 10.15.1

**Comment by TheOneRing** [comment]
Server issue, https://github.com/owncloud/core/issues/36619 @HanaGemela could you fill in missing bit for the newly created issue?
