### ISSUE TITLE
Move without permissions creates a copy

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7413]
Windows 10
Client: 2.6.0daily20190820 (build 12286)
Server: 10.3.0 alpha, 10.2.1

Steps to recreate:

1. User A shares folder Test with user B, granting no edit permissions.
2. User A creates folders Test/Sub, Test/testfolder and file Test/file.txt - optionally extra contents in folder Test/Sub to test for duplication of files.
3. User B is connected with a desktop client, folder Test is synced.
4. User B moves testfolder into folder Sub

Actual result: Copy of testfolder has been created in Sub folder. This copy cannot be synced due to insufficient permissions 
Expected result: No copy has been created

Similar issue: https://github.com/owncloud/client/issues/7294

**Comment by HanaGemela** [comment]
Same for file:
User B moves file.txt into folder Sub

**Comment by HanaGemela** [comment]
This scenario sounds similar:

Moving a file into read-only external storage duplicates the file

Server 10.4.0 RC3 
Client 2.6.1 (build 13096)
macOS 10.15.2

Steps to recreate:
1) Add a read-only WND storage
2) In the client move a file into WND storage

Actual result: File has been moved, sync failed, file has been recreated at its original location -> user has two copies on that file (one in WND and one at the original location)
Expected result: File has not been moved

**Comment by TheOneRing** [comment]
Nothing we can change here without risking data loss
