### ISSUE TITLE
Rename possible but new folder not synced due to insufficient permissions

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7414]
Windows 10
Client: 2.6.0daily20190820 (build 12286)
Server: 10.3.0 alpha, 10.2.1

Steps to recreate:

1. User A shares folder Test with user B, granting no edit permissions.
2. User A creates folders Test/Sub, Test/testfolder and file Test/file.txt - optionally extra contents in folder Test/Sub to test for duplication of files.
3. User B is connected with a desktop client, folder Test is synced.
4. User B renames Sub to subfolder

Actual result: Sub folder has been recreated and subfolder cannot be synced due to insufficient permissions
Expected result: subfolder has not been created

Similar issue: https://github.com/owncloud/client/issues/7413

**Comment by HanaGemela** [comment]
The same for files:

User B renames file file.txt to testfile.txt

**Comment by ogoffart** [comment]
Is that not the same as #7413

Rename being just a special case of delete and recreate with a new name, i think this "duplicate" is the expected behavior in read-only folders.

**Comment by TheOneRing** [comment]
Nothing we can change for now
