### ISSUE TITLE
Move duplicates local folder when shared with only change permissions

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7416]
Related to: https://github.com/owncloud/client/issues/7294 and https://github.com/owncloud/client/issues/7293

Windows 10
Client: 2.6.0daily20190820 (build 12286)
Server: 10.3.0 alpha, 10.2.1

Steps to recreate:

1. User A shares folder Test with user B, granting **change** permissions.
2. User A creates folders Test/Sub, Test/testfolder and file Test/file.txt 
3. User B is connected with a desktop client, folder Test is synced.
4. User B moves testfolder into folder Sub

Actual result: Copy of testfolder has been created in Sub folder. This copy cannot be synced due to insufficient permissions
Expected result: Folder has been successfully moved

The same for moving files

**Comment by ogoffart** [comment]
> Expected result: Folder has been successfully moved

But that's not possible, you need the create and delete permission on the server to do that. 
You also can't do the move from the web interface.
