### ISSUE TITLE
User can move a folder without Change permissions

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7420]
Windows 10
Client: 2.6.0daily20190820 (build 12286)
Server: 10.3.0 alpha, 10.2.1

Steps to recreate:

1. User A shares folder Test with user B, granting delete permissions.
2. User A creates folders Test/Sub, Test/testfolder and file Test/file.txt
3. User B is connected with a desktop client, folder Test is synced.
4. User B moves folder testfolder into folder subfolder

Actual result: The move succeeds
Expected result: Move not allowed without Change permissions

**Comment by ogoffart** [comment]
If the server don't deny it, it is allowed.
So I would say that this is working as expected and is simply a bug in the server. 
(Giving delete AND create permission means you also can change since you can delete the original and re-create a new one)

So i'm going to close this.
