### ISSUE TITLE
Cannot sync resource with special characters

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7421]
Client 2.6.0-daily20190820 (build 12341), macOS 10.14.6, server 10.2.1.4
Client 2.6.0daily20190820 (build 12286), Windows 10, server 10.3.0.1

**Scenario 1**

1. Create a folder called  ? < >  * | on Mac
2. Share it to Windows

Actual result: Nothing on Windows, no error, nothing
Expected result: User friendly error

**Scenario 2**

1. Add a new folder on Mac called ±!@#$%^&*()_+{}|"?><`§-=[]\'/
2. Sync to the server

Actual result:  400 Bad request
Expected result: User friendly error

**Comment by kort3x** [comment]
Same goes for folders and files created via the webinterface.

Let's say someone creates a folder called "XYZ 1:500"online. 
Windows clients will simply not sync the folder and its content because of the colon.
Users might have no clue something is missing on their windows box.

**Comment by kort3x** [comment]
I mean the prefered way would be to sync the folder by normalizing the name.

**Comment by ogoffart** [comment]
On windows, the file should appear in the "not synchronized" list. Is that not a user friendly error?

As for the 400 bad request, that's what the server returns. This can have several reason. Normally, the server should include the reason in some additional message that we also display.

**Comment by ogoffart** [comment]
Personally, I think the current behavior is good enough: You see the error in the "not synchronized" tab.

Normalizing the name is out of question as it would cause many problems.

**Comment by TheOneRing** [comment]
Out of scope.
Needs to be handled on the server.

**Comment by jnweiger** [comment]
I believe it is more difficult for the server to handle this than for the clients.
Each client can easily probe its own filesystems for limitations -- the server cannot.
