### ISSUE TITLE
Rename causes 'Move not allowed' error 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7422]
Related to:
https://github.com/owncloud/client/issues/7417
https://github.com/owncloud/client/issues/7293
https://github.com/owncloud/client/issues/7294
https://github.com/owncloud/client/issues/7413
https://github.com/owncloud/client/issues/7416

Windows 10
Client: 2.5.4
Server: 10.3.0 alpha

Steps to recreate:

1. User A shares folder Test with user B, granting delete and create permissions.
2. User A creates folders Test/Sub, Test/testfolder and file Test/file.txt
3. User B is connected with a desktop client, folder Test is synced.
4. User B renames Sub into folder subfolder

Actual result: Rename successful but 'Move not allowed' error shown for a while
Expected result: No error

The same for renaming files

**Comment by ogoffart** [comment]
I could not reproduce this (Tried with the 2.6 branch from today)

Maybe this was fixed by https://github.com/owncloud/client/pull/7436

Can this still be reproduced?

**Comment by HanaGemela** [comment]
The original issue has been fixed.
Another two issues here:
1) Move is followed by a desktop notification that the original resource has been removed 
2) The original resource in User1's account has been renamed as well. Expected result: Rename only applies to the users' personal space, not for other collaborators

**Comment by ogoffart** [comment]
> Move is followed by a desktop notification that the original resource has been removed

I can't reproduce this.

> The original resource in User1's account has been renamed as well. Expected result: Rename only applies to the users' personal space, not for other collaborators

That's the expected behavior

**Comment by HanaGemela** [comment]
Renaming the original file is the expected behaviour?

**Comment by ogoffart** [comment]
Well, yes. Unless I misunderstand what's happening.
But if you rename a file locally, it is supposed to propagate to the server if you have the permission (which you have with the right to delete and create files)

**Comment by HanaGemela** [comment]
https://github.com/owncloud/product/blob/e76e813be9de6051c05a47e4d6ca345c5a8faa44/src/resources/features/renaming_a_resource.feature#L19

**Comment by ogoffart** [comment]
So what's the remaining issue?

**Comment by HanaGemela** [comment]
Notification. Move is followed by a desktop notification that the original resource has been removed

**Comment by ogoffart** [comment]
I'm a bit lost. What are the step to reproduce and the actual vs. expected behavior?

I don't get the notification

**Comment by HanaGemela** [comment]
I'll close this issue as the original issue has been fixed.
Renaming without change permission is being dealt with in https://github.com/owncloud/client/issues/7417
