### ISSUE TITLE
Cannot unshare without permissions to share

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7423]
Windows 10
Client: 2.5.4 (build 11415)
Server: 10.3.0 alpha

Steps to recreate:
1) User1 shares a resource with User2 with full permissions
2) User2 shares the resource with User3
3) User1 removes Share permissions from User2
4) User2 removes the share from User3

Actual result: User2 cannot unshare the resource with User3
Expected result: User2 can unshare the resource

**Comment by michaelstingl** [comment]
Behaviour should be same as server. Can we compare with server tests?

**Comment by dpakach** [comment]
Test added in https://github.com/owncloud/client/pull/8508

**Comment by individual-it** [comment]
on API level its possible for User2 to remove its own share that goes to User3, but its not possible in the old webUI

**Comment by individual-it** [comment]
API tests added in https://github.com/owncloud/core/pull/38652

**Comment by TheOneRing** [comment]
The sharing dialog is considered deprecated
