### ISSUE TITLE
Deleting a file without permissions - file becomes ignored and user is not notified

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7434]
Client: 2.5.4, 2.6. beta
Server: 10.2, 10.3

Steps to recreate:
1) User1 shares a file with User2 without Edit permissions (without Create, Change, Delete permission)
2) User2 deletes the file 

Actual result: 
File has been restored and marked as Ignored (until next sync, then it is synced again)

Expected result:
File has been recreated and is synced
File is still synced
Error message has been shown that user doesn't have permission to do this 
Notification has been shown informing that the file has been restored

**Comment by HanaGemela** [comment]
The same applies to folders

**Comment by ogoffart** [comment]
There is a change in https://github.com/owncloud/client/pull/7514 that would add the entry in the sync protocol tab.

But we indeed would need to add the notification.

**Comment by ogoffart** [comment]
Btw, the file is not ignored.  The warning icon means that there was an error, not that it was ignored.

**Comment by ogoffart** [comment]
Personally I think the current behavior is good enough. It is actually close to the one in the "Expected result".  The diescription in "Actual result" might be a misunderstanding, as the error is indeed present in the "not synced" tab
