### ISSUE TITLE
Server directories can be deleted before renames happen

### ISSUE THREAD

**Issue by ckamm** [owncloud/client#7441]
Have the following tree:
```
A/
A/f
```
pause the sync and perform these actions
```
local mkdir B/
local move A/f -> B/f
local remove A/
```
restart the sync.

It's possible that A/ will be removed on the remote before the remote rename from A/f to B/f happens. 

That's because the `PropagateDirectory` job for B/ (containing the remote mkdir, and the move) has `FullParallelism` and thus the delete of A/ can happen while the mkdir B/ is still running and before the move has started.

**Comment by guruz** [comment]
Didn't @jnweiger report this some time ago?

**Comment by ckamm** [comment]
If he did I wasn't aware of it. :(

**Comment by HanaGemela** [comment]
@ckamm Do you know if I can reliably test it?

**Comment by ckamm** [comment]
@HanaGemela It was reliable in an autotest. I haven't tried manual testing. Just check whether the setup above causes an error with current 2.6 builds.

**Comment by HanaGemela** [comment]
@ckamm But if it works, can I be sure it is thanks to the fix or just this time rename happened before delete?

**Comment by ckamm** [comment]
I meant that you could test with the current builds that don't have the patch yet to figure out whether testing is reliable.

**Comment by jnweiger** [comment]
Is this related? https://github.com/owncloud/client/issues/7438

**Comment by ckamm** [comment]
I don't think so. In this issue the client decides to do the right thing but shoots itself in the foot by executing in the wrong order.

**Comment by HanaGemela** [comment]
Cannot recreate in 2.6.0rc1 (build 12411), macOS 10.14.6. Believed to be fixed
