### ISSUE TITLE
can't  download binary files

### ISSUE THREAD

**Issue by optticall** [owncloud/client#7444]
Sorry guys, I know this is not the best place for this, but it seems that all download links for windows client are broken. Can you guys take a look at this, please?

**Comment by michaelstingl** [comment]
Thank you very much for reporting this issue! There are some hiccups with the download mirrors – sorry for the inconvenience! Could you check again? The team will work on a sustainable solution starting Monday morning…

**Comment by optticall** [comment]
It's woking now. Thank you!
