### ISSUE TITLE
Progress wheel shown when unselecting password protection

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7459]
Client: 2.6.0rc1 (build 12411)
mac 10.14.6
server: 10.2.0 stable

Steps to recreate:
1) Right click on a file 
2) Select Share from ownCloud menu
3) Select Public link tab
4) Tick the Password protect checkbox 
5) Untick the Password protect checkbox 

Actual result: Loading wheel next to the checkbox
Expect result: Checkbox has been just unchecked. No loading wheel

<img width="409" alt="Screenshot 2019-09-06 at 20 27 32" src="https://user-images.githubusercontent.com/49001702/64451985-a7a1d580-d0e5-11e9-9cd5-c87c8fd4e098.png">

**Comment by michaelstingl** [comment]
I'd only touch this when covered by tests…

**Comment by HariBhandari07** [comment]
Test for checking "progress wheel while unselecting password protection checkbox" has been added in PR https://github.com/owncloud/client/pull/8496.

All the remaining public link share test will be covered by https://github.com/owncloud/client/issues/8501

**Comment by TheOneRing** [comment]
The sharing dialog is considered deprecated
