### ISSUE TITLE
inconsistent icons

### ISSUE THREAD

**Issue by voroyam** [owncloud/client#7465]
When you have 2 Folders for sync

1. Local folder
2. Network share

The client displays "undefined status" although it should be syncing while it syncing. 

![image](https://user-images.githubusercontent.com/24212810/64607073-08702d00-d3c8-11e9-8fcc-2d925d0729ed.png)

**Comment by michaelstingl** [comment]
@voroyam Any errors in the activity tab?

**Comment by voroyam** [comment]
No, no errors in activity tab or the not synced files. I think it's just because oC got 2 folders, one is in sync and the other one is syncing. But then I would expect an syncing icon.

**Comment by ogoffart** [comment]
I could not reproduce this problem.
For me once there is at least one account syncing, the state is in sync mode. (and this is consistent with what the code intends)

What version of the client is that?

**Comment by voroyam** [comment]
The latest one. The important point here = windows + one sync folder is added to the sync client and is on a network share.

**Comment by voroyam** [comment]
can you show me your sync folders in your client ?
