### ISSUE TITLE
craft windows builds fail in test suite

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7468]
There are long log file dump in the logs, but no apparent error. Still the testsuite fails in two cases:

The following tests FAILED:
	 27 - PermissionsTest (Failed)
	 29 - DatabaseErrorTest (Exit code 0xc0000374
)
Errors while running CTest
Action: test for owncloud/owncloud-client:master FAILED
*** Craft test failed: owncloud/owncloud-client after 2 minutes 7 seconds ***

Should we disable these, or is this fixable?

**Comment by jnweiger** [comment]
Edited https://jenkins.int.owncloud.com/job/client-daily/
to say BUILD_TESTING=false
with testpilotcloud 2.6

**Comment by jnweiger** [comment]
The testsuite seems to have random failures, sometimes more, somtimes less.
@TheOneRing just ran into https://ci.appveyor.com/project/ownclouders/client/builds/27495161/job/5rk2wxk214h2ygl3

with more failures:

 The following tests FAILED:
	 13 - SyncVirtualFilesTest (Failed)
	 20 - ZsyncTest (Failed)
	 27 - PermissionsTest (Failed)
	 29 - DatabaseErrorTest (Failed)
Errors while running CTest

**Comment by guruz** [comment]
Indeed:
@ckamm wrote:
> The three tests pass for me with current 2.6 on windows 10

I saw 'The process cannot access the file because it is being used by another process.' in one of the tests, is it always the same one?
Maybe we need some artificial sleeps() again somewhere?

**Comment by jnweiger** [comment]
All daily builds fail on this issue for quite a while. It is never exaclty the same test that fail, so fighting some race conditions is probably a good approach. Make this very long sleeps for a start, we can optimize them later :stuck_out_tongue:

**Comment by TheOneRing** [comment]
The issue is not in the unittests, Appveyor provides a slow vm with a single core.
The tests fail as the checksum process has the tmp file still open while it should be renamed

**Comment by michaelstingl** [comment]
@TheOneRing @jnweiger remove from 2.6.0 milestone? Drop AppVeyor?

**Comment by guruz** [comment]
@TheOneRing not sure I understand your reasoning.

If the issue is VM slowness, then a sleep/wait-longer as suggested above will help :-)

If the issue is with the test that the test fails if there is a slow VM, then our code has a bug and we should check our use of threading in case of certain OS/CPU timings.

Unrelated to that, how could we upgrade to a faster CPU? https://www.appveyor.com/pricing/

**Comment by guruz** [comment]
> remove from 2.6.0 milestone?

Only if it is proven that the issue is not in our actual client code, only in our test tests (or indirectly due to slow VM)

**Comment by HanaGemela** [comment]
Works as expected
Tested by @TheOneRing
