### ISSUE TITLE
Automatic dehydration when computer running low on disk space 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7470]
Client should automatically dehydrate files that are not pinned when running low on disk space

Other automatic dehydration issues: 
https://github.com/owncloud/client/issues/7084 
https://github.com/owncloud/client/issues/7402

**Comment by TheOneRing** [comment]
@michaelstingl we need to document storage sense

**Comment by TheOneRing** [comment]
Duplicate of https://github.com/owncloud/client/issues/8586
