### ISSUE TITLE
Check 2.6 memory usage for deeply nested trees

### ISSUE THREAD

**Issue by guruz** [owncloud/client#7472]
Ref https://github.com/owncloud/enterprise/issues/3491

**Comment by guruz** [comment]
Might be fixed, @jnweiger ?
https://github.com/owncloud/enterprise/issues/3491#issuecomment-532176574

**Comment by jnweiger** [comment]
That is not a regression. Should not be a blocker for 2.6.0 IMHO.

**Comment by jnweiger** [comment]
1.5Mio files in a deep tree, moving in after the initial sync:
 * Desktop daily 20190919 msi: 
   * local discovery takes ca. 8 minutes, consumes  970MB RAM, GUI remains responsive.
   * Upload starts  fine, RAM size remains constant then.
 * Aborting sync after 4k files.
 * Upgrade to daily 20190923 msi: 
   * local discovery takes ca. 8 minutes, consumes  970MB RAM, GUI remains responsive.
   * Upload starts  fine, RAM size remains constant then.

This is consistent with what we saw with 2.5.4 in 
https://github.com/owncloud/enterprise/issues/3491#issuecomment-528948792
Given a normal amount of  RAM in the system (4GB or more), this behavious is fine from my POV.
