### ISSUE TITLE
Owner doesn't have control over subshares

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7473]
Client: 2.6.0rc1 (build 12357)
Windows10
Server: ownCloud 10.3.0 alpha2 (testing)

Steps to recreate:
1) User1 shares a folder with User2 with full permissions
2) User2 adds a new file into the shared folder
3) User2 shares the file with User3 with full permissions
4) User3 shares the file back to User2 with full permissions (at this point User2 has two copies of the same file - is that OK?)
5) User1 removes share permissions of the shared folder from User2 

Actual result: Now User2 cannot reshare the first copy in the shared folder but still can share the second copy in his root directory. To remove the share permission from the second copy, User1 has to remove the permissions from the file. But User1 doesn't necessarily know that there is any subshare in his share. User1 would need to open every single file in his folder and check if it wasn't reshared.
User1 as an owner doesn't see all these reshares in web ui in Shared with others. 
And also the web ui shows that the file comes from User1 and from User3 as well 

![Screenshot 2019-09-12 at 14 18 02](https://user-images.githubusercontent.com/49001702/64783533-4e63f700-d568-11e9-9ba9-8a76b7c4560e.png)

Expected result: Either the loops are not allowed or the owner has the overview over all the subshares

**Comment by jnweiger** [comment]
Permission handling is done into the server. To me it also comes as a surprise, that a user can have multiple sets of permissions on the same resource (file or folder) if he somehow has the same resource under multiple path names. This should not be possible.

We should either prevent one resource to appear at multiple paths. or we should keep the permissions in sync. In any case, its a server issue.

**Comment by jnweiger** [comment]
The WebUI prevents loops, thus implementing suggested solution a). In step 4, no user can be chosen. User2 is not available; User1 is available in the form, but triggers an error later.

**Comment by TheOneRing** [comment]
The sharing dialog is considered deprecated
