### ISSUE TITLE
Improve UI freeze (main thread?) on sync abort/pause

### ISSUE THREAD

**Issue by guruz** [owncloud/client#7479]
Found by @jnweiger in https://github.com/owncloud/client/issues/7456#issuecomment-532241063

> 
    initial sync with ca 10 files, 25 MB: 2 seconds.
    move in a folder with 500k files after initial sync: 122 seconds discovery (340MB RAM), then upload starts.
    pause sync after uploading ca 1k files out of 500k: 177 seconds UI freeze (100%CPU, 340MB RAM). Then tabs can be switched (0% CPU, 40MB RAM).

**Comment by jnweiger** [comment]
Seen on both, win10 and ubuntu18.04 today.

With such a big tree, some slowdown is acceptable. E.g. during discovery the gui takes ca 2 sec to switch tabs in the settings windows.

When clicking pause sync, we have a hard freeze of the gui for 2 minutes. That is bad.

But this is kind of a corner case. pausing sync, while such a large upload is ongoing. I asusme that is a rare thing. I am fine with low prio. Also, this is not a regression. 2.5.4 has the same issue.

**Comment by ogoffart** [comment]
> When clicking pause sync, we have a hard freeze of the gui for 2 minutes.

Pausing  does not cause any slowdown for me (linux). It is instant.
Can you get a backtrace showing where the client is while it is frozen?

**Comment by guruz** [comment]
(I also noticed this UI freeze on macOS when i tested pausing)

**Comment by TheOneRing** [comment]
Could have been related to the wal issue and should no longer happen in 2.8
