### ISSUE TITLE
OpenID Connect support

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#7482]
iOS implementation:
- https://github.com/owncloud/ios-app/pull/401

Testing environment:
- https://github.com/owncloud/openidconnect/issues/17

Related:
- https://github.com/owncloud/enterprise/issues/2929
- https://github.com/owncloud/enterprise/issues/2577

**Comment by michaelstingl** [comment]
We'd need to extend the current OAuth 2.0 implementation with Proof Key for Code Exchange (PKCE) and OpenID Connect (OIDC).

@TheOneRing you mentioned, there are existing libraries in the Qt world that could help here? /cc @owncloud/desktop-core-developers

**Comment by ogoffart** [comment]
Initial PR: https://github.com/owncloud/client/pull/7509
