### ISSUE TITLE
Download links for windows production client doesn't work

### ISSUE THREAD

**Issue by underdpt** [owncloud/client#7486]
### Expected behaviour
Click on any production client download link and the client should be dowloaded.

### Actual behaviour
Trying to download a windows client result in the navigator waiting forever and it doesn't download the client

### Steps to reproduce
1. Go to https://owncloud.org/download/#owncloud-desktop-client-windows
2. Try to download production windows client installer
3. Wait forever....

MacOS, Linux and server download links seem to work correctly.

**Comment by michaelstingl** [comment]
@underdpt Thank you very much for reporting this. The temporary issue gut resolved, please try again. The team is working on a more sustainable solution, which should be finished the next few days…
