### ISSUE TITLE
Permissions when sharing a folder via public link don't match the server 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7488]
![Screen Shot 2019-09-24 at 13 48 25](https://user-images.githubusercontent.com/49001702/65510769-02a13e00-ded6-11e9-8750-fdc6ef543678.png)

Steps to recreate:

1. Connected to server 10.2
2. Right click on a folder
3. Select Share from ownCloud submenu
4. Select Public links

Expected result: Available permissions match the permissions on the server 
Actual result: Currently Upload and Edit permissions are mixed into one

For 10.3+ server see https://github.com/owncloud/client/issues/7487

**Comment by TheOneRing** [comment]
The sharing dialog is considered deprecated
