### ISSUE TITLE
oAuth2 not working with Safari

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7497]
Server: 10.3.0.3 **with oAuth2**
Client: 2.6.0 RC1

Steps to recreate:
1) Add a new account to the desktop sync client or click log in in the client
2) Open the login page in Safari
3) Log in
4) Authorise

Actual result: 'Safari Can't Open the Page' error message
Expected result: "The application was authorised successfully. You can now close this window." message

**Comment by michaelstingl** [comment]
@HanaGemela how did you setup this ownCloud instance? This link should never have a `https://localhost…`. It's always `http://localhost…`

**Comment by DeepDiver1975** [comment]
This url is Not the Owncloud instance but the clients callback url. As metioned above.

**Comment by HanaGemela** [comment]
Works as expected after deleting website data and clearing the cache

**Comment by guruz** [comment]
@HanaGemela maybe you have some browser plugin that redirects http->https for something something

**Comment by hostirosti** [comment]
I ran into the same issue. Could this be related to a reverse proxy rewrite which should exclude localhost rewrites?

**Comment by michaelstingl** [comment]
Yeah, I’ve seen networking middleware like reverse Proxies that also rewrote the localist route. What setup do you use?
