### ISSUE TITLE
Entry in collaborators list is greyed out after not allowed operation

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7498]
Client: 2.6.0 RC1
Server: 10.3.0 RC1
macOS: 10.14.6

Steps to recreate:

1. User2 is a member of group called friends
2. User1 shares a file to User2 with only Share permission (no Edit permissions)
3. User1 shares the same file to the group called friends with Edit permissions
4. User2 removes Edit permissions from friends group
5. User2 grants Edit permissions to friends group

Actual result: The entire entry is greyed out. That means that user cannot grant Share permissions even though they are allowed to do so and it seems that friends can edit now as the checkbox is ticked. User also cannot delete. 
<img width="459" alt="Screenshot 2019-10-02 at 11 39 00" src="https://user-images.githubusercontent.com/49001702/66034285-41a04680-e509-11e9-9a6b-b0ba2cb72c7c.png">

Expected result: Only `can edit` is greyed out and not ticked. The bin icon and `can share` remain available. There should also be some error message explaining why the operation was not successful

**Comment by HanaGemela** [comment]
<img width="449" alt="Screenshot 2019-10-02 at 16 15 23" src="https://user-images.githubusercontent.com/49001702/66051878-ed5c8d00-e52f-11e9-8ccf-6bcfb51ce0ed.png">

The error message is already there but shown only when user tries to share by typing the name into the collaborator search field. This should be also shown when sharing by clicking on `can share` checkbox

**Comment by michaelstingl** [comment]
Behaviour should be same as server. Can we compare with server tests?

**Comment by SwikritiT** [comment]
I couldn't reproduce this error. 

```
Client: 2.7.6
Server: current master
```

 `user1` shares file with  `user2` and group `Friends` that  `user2` is also a part of


![currentmasteruser1](https://user-images.githubusercontent.com/41103328/111984692-cdf65d00-8b33-11eb-90a1-45203d25e0f4.png)



When I go to `user2` account and to  the sharing tab of file `textfile0.txt`  , which was shared by `user1`, I get a blank screen as such



![current-user2](https://user-images.githubusercontent.com/41103328/111985488-c2effc80-8b34-11eb-8831-43d5c06c99e0.png)


However if I try to share the same file to `Friend` group through `user2` account , it gives me error saying that the `path  already shared with this group`

![path_already](https://user-images.githubusercontent.com/41103328/111985894-5295ab00-8b35-11eb-923a-39dbb1854a26.png)


Shows same behaviour in `core` UI


![current-core](https://user-images.githubusercontent.com/41103328/111986501-229ad780-8b36-11eb-9c2f-817027266e6c.png)

##

```
Client: 2.7.6
Server: 10.3.0 RC1
```

I found same behavior with `10.3.0 RC1` as well

 `user1` shares file with  `user2` and group `Friends` that  `user2` is also a part of

![client_core10 3](https://user-images.githubusercontent.com/41103328/111986732-6f7eae00-8b36-11eb-80fd-df7e0dbd3f29.png)


When I go to `user2` account and to  the sharing tab of file `textfile.txt`  , which was shared by `user1`, I get a blank screen as such


![client](https://user-images.githubusercontent.com/41103328/111986855-91783080-8b36-11eb-96ab-cc05dc806560.png)


![core](https://user-images.githubusercontent.com/41103328/111986886-9ccb5c00-8b36-11eb-9cb8-9f49e4cc2cd6.png)

**Comment by swoichha** [comment]
### To-Do:
- [ ] add tests for desktop-client

**Comment by TheOneRing** [comment]
Can't be reproduced, thanks for testing.
