### ISSUE TITLE
Too low contrast when tab is selected

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7512]
Client: 2.6.0-daily20191009 (build 12541)
macOS: 10.15

When a tab is selected, contrast is too low. 

<img width="860" alt="Screenshot 2019-10-10 at 10 59 26" src="https://user-images.githubusercontent.com/49001702/66554330-17740780-eb4d-11e9-810b-35569a50fa77.png">

**Comment by ogoffart** [comment]
PR: https://github.com/owncloud/client/pull/7513

**Comment by HanaGemela** [comment]
Works as expected in 2.6.1-daily20191127 (build 12791), macOS 10.15
