### ISSUE TITLE
[Windows] Official 64-bit owncloud.exe and .msi installer

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#7525]
- [x] Create a 64bit msi installer
- [ ] Validate installer and client

**Comment by guruz** [comment]
2.6.1 even maybe? :-)

**Comment by TheOneRing** [comment]
> 
> 
> 2.6.1 even maybe? :-)

Depends on how fast @dschmidt is 😄

**Comment by michaelstingl** [comment]
> 64bit core client program

What do you mean? (I'm not a Win expert myself)

**Comment by dschmidt** [comment]
> > 2.6.1 even maybe? :-)
> 
> Depends on how fast @dschmidt is

Rather on how it's prioritized ;-)

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/releases/tag/v2.7.0-beta5
