### ISSUE TITLE
Win10 explorer is destroyed by v2.6.0 RC2 installer

### ISSUE THREAD

**Issue by NiceFeather** [owncloud/client#7532]
Win 10 explorer is destroyed while running the v2.6.0 RC2 installer, it would be encountered errors when the shell extension installed was appling to the explorer. By force closing system explorer will causes a series of problems and gives users a bad experience, is there a better way to handle this issue gently?

**Comment by guruz** [comment]
@NiceFeather Is it by any chance https://github.com/owncloud/client/issues/6667 ?

@dschmidt I think we should not have the option to close the explorer, better restart the system.

**Comment by TheOneRing** [comment]
@dschmidt I think you made the behaviour a bit nicer?  Is this still valid?
