### ISSUE TITLE
ownCloud 2.6rc2 fails to read keychain on Debian 10

### ISSUE THREAD

**Issue by AlfTetzlaff** [owncloud/client#7536]
### Expected behaviour
ownCloud saves my credentials and uses them for logging in on startup.

### Actual behaviour
I have two accounts linked to different servers. One of the connections now fails telling me "reading from keychain failed with error: unknown error" and asks to enter my password. The other one always pops up the browser asking me to authorize this app. After entering my pw and authorizing it works.

### Client configuration
Client version:
2.6.0~rc2+oc-1598

Operating system:
Debian 10 (buster) 
4.19.0-6-amd64
Gnome 3.30.2

OS language:
English (UK)

Client package (From ownCloud or distro) (Linux only):
latest ownCloud package from 
https://software.opensuse.org//download.html?project=isv:ownCloud:desktop:testing&package=owncloud-client

Sorry, but as of now I can't provide any logfiles etc. please ask if you need more info.

**Comment by ogoffart** [comment]
Thanks for testing the RC2

Did it work with the previous version of the client?
What keychain are you using?

**Comment by AlfTetzlaff** [comment]
1) Version 2.5.1 which comes with the distro works as expected.

2) I am using a „normal“ Debian + gnome, so i assume its the regular gnome keyring, but i can check when I‘m back home on sunday.

**Comment by ogoffart** [comment]
I don't have a setup ready to test Debian 10. Does the log not show some more information about the reason why this fails?

**Comment by GregJohnStewart** [comment]
Bump to this issue, the client won't remember the password on Ubuntu 19.10 or CentOS Stream for me.. Ubuntu using keyring version `3.34.0`, and CentOS using `3.28.2`

**Comment by michaelstingl** [comment]
see https://github.com/owncloud/client/issues/7578

**Comment by SpacyNG** [comment]
2.6.0 still produces this bug even without libgnome-keyring, but it seems to be fixed in the testing repo.
`http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/testing/Ubuntu_19.10`
Current version at the time of this writing is 2.6.1~sprint2+oc-1994 and this works nicely. 
I guess there's testing versions for Debian, too.

**Comment by ogoffart** [comment]
Was most likely caused by https://github.com/owncloud/client/issues/7578
(reported fixed in https://github.com/owncloud/client/issues/7651#issuecomment-575305195 )
