### ISSUE TITLE
ownCloud desktop client notifications redirect to localhost

### ISSUE THREAD

**Issue by aalf1987** [owncloud/client#7537]
### Expected behaviour
When you get a notification about an update (market application, core...) and you click it, the browser should go to http://whatever.ddns.net/index.php...

### Actual behaviour
http://localhost/index.php... is opened.

### Steps to reproduce
1. 
![image](https://user-images.githubusercontent.com/5657720/67139625-90144b80-f252-11e9-9bd2-01e61ee3a35d.png)

2. 
![image](https://user-images.githubusercontent.com/5657720/67139635-af12dd80-f252-11e9-813b-3c8cc557d358.png)

### However...
1.
![image](https://user-images.githubusercontent.com/5657720/67139667-03b65880-f253-11e9-8a6a-c5c352a4c0ca.png)

2.
![image](https://user-images.githubusercontent.com/5657720/67139692-49732100-f253-11e9-99a1-464c5408ba4a.png)

### Server configuration
Operating system: Raspbian 9 (stretch)

Web server: Apache 2 2.4.25-3+deb9u9

Database: MariaDB 10.1.38-0+deb9u1

PHP version: 7.0.33-0+deb9u5

ownCloud version: 10.2.1.4

Storage backend (external storage): none

### Client configuration
Client version: ownCloud 2.5.4

Operating system: Windows 10 Pro 1903

OS language: Spanish

Installation path of client: "C:\Program Files (x86)\ownCloud"

**Comment by ogoffart** [comment]
I believe the links comes from the server,  so there is most likely something wrong in the server configuration.  (Somewhere in the server configuration there is a configuration for the preferred host name)

**Comment by aalf1987** [comment]
```
  'trusted_domains' =>
  array (
    0 => '192.168.X.X',
    1 => 'whatever.ddns.net'
  ),
  'overwrite.cli.url' => 'http://whatever.ddns.net',
```

**Comment by michaelstingl** [comment]
@aalf1987 Please also check the other parameters:
https://doc.owncloud.com/server/10.2/admin_manual/configuration/server/config_sample_php_parameters.html#proxy-configurations
