### ISSUE TITLE
Server activity - icon too big 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7543]
Server: 10.3.0 stable
Client: 2.6.0 rc2
Windows 10

Steps to recreate:

1. Create folders Documents/Empty and Photos/Empty2
2. Run: move Documents/Empty ./ && move Photos/Empty2 ./ && move Documents Empty2/ && move Photos Empty/
3. Check the Server Activity tab

Expected result: All entries have the person icon visible
Actual result: The person icon is too big to fit into the line on Windows. Only every second line shows the full icon 

<img width="631" alt="Screenshot 2019-10-22 at 15 10 50" src="https://user-images.githubusercontent.com/49001702/67289725-599f3080-f4df-11e9-9207-c82c10b5af2d.png">

**Comment by TheOneRing** [comment]
was fixed
