### ISSUE TITLE
[macOS] Testpilot doesn't provide VFS 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7544]
Client: 2.6.0rc2 (build 12578)
Server: 10.3.0 stable
macOS 10.15

Steps to recreate: 
1) Go to Account tab
2) Open three dots menu
3) Enable virtual file support 

Actual result: VFS is missing
Expected result: VFS available

![Screenshot 2019-10-23 at 09 41 30](https://user-images.githubusercontent.com/49001702/67369773-e4cd0480-f579-11e9-98ba-19ae29fec29c.png)

**Comment by guruz** [comment]
@TheOneRing is that what you mentioned on Rocket chat?

**Comment by HanaGemela** [comment]
> @TheOneRing is that what you mentioned on Rocket chat?

Yes, that's the one mentioned by @TheOneRing

**Comment by HanaGemela** [comment]
2.6.0-daily20191025 (build 12616) Testpilot provides VFS on macOS 10.15

**Comment by jnweiger** [comment]
@HanaGemela This needs retesting with 2.6 daily unbranded too, please.
