### ISSUE TITLE
[QA] Files with .owncloud suffix on the server cause a syncing loop

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7556]
* Connect Linux client 2.6.0rc2 to owncloud server 10.3
* Wait until initial sync is done.
* Pause syncing.
* upload the same file three times to the server with the web GUI like this:
   * upload adler05.jpg and rename on the server to adler05.jpg.owncloud.owncloud
   * upload adler05.jpg and rename on the server to adler05.jpg.owncloud
   * upload adler05.jpg
* resume syncing.

The client downloads all three of them:
![image](https://user-images.githubusercontent.com/1108546/67575889-c9aaf200-f73d-11e9-85c2-049dbdd7a2e4.png)
```
3& [testy:~/ownCloud5] $ ll adl*
-rw-r--r-- 1 testy testy 99226 Mai 12 01:10 adler05.jpg
-rw-r--r-- 1 testy testy 99226 Mai 12 01:10 adler05.jpg.owncloud
-rw-r--r-- 1 testy testy 99226 Mai 12 01:10 adler05.jpg.owncloud.owncloud
```
OK so far.

* enable virtual files ; wait for a sync -> Nothing changes.
* switch 'Availability' -> 'Free up local space'

The client starts looping. 
![image](https://user-images.githubusercontent.com/1108546/67576217-6cfc0700-f73e-11e9-8f49-e7b79d1d460d.png)

and contents of at least one file is lost:
```
3& [testy:~/ownCloud5] $ ll adl*
-rw-r--r-- 1 testy testy     1 Mai 12 01:10 adler05.jpg.owncloud
-rw-r--r-- 1 testy testy 99226 Mai 12 01:10 adler05.jpg.owncloud.owncloud
3& [testy:~/ownCloud5] $ 
```

**Comment by jnweiger** [comment]
related issue: #6953

**Comment by jnweiger** [comment]
when we switch back to 'Availability' -> 'Make always available locally' the looping stops, but we lost one file:
```3& [testy:~/ownCloud5] $ ll adl*
-rw-r--r-- 1 testy testy 99226 Mai 12 01:10 adler05.jpg
-rw-r--r-- 1 testy testy 99226 Mai 12 01:10 adler05.jpg.owncloud.owncloud
3& [testy:~/ownCloud5] $

**Comment by jnweiger** [comment]
@ogoffart Force sync is not needed here to reproduce. The client immediately starts looping after switching the availability.

**Comment by jnweiger** [comment]
when instead of switching directly from VFS with "freed local space" to non-VFS, then all three files are restored correctly.

**Comment by ogoffart** [comment]
I couldn't reproduce the problem unless i do force sync. Maybe there is something that make the client not "trust" the filesystem watcher

**Comment by jnweiger** [comment]
The loop no longer happens. We see an apropriate error message, that was introduced in  https://github.com/owncloud/client/commit/48d3c8432e33eb6a241d15bf98663939e11c8282 
![image](https://user-images.githubusercontent.com/1108546/72440284-d5400f00-37a8-11ea-9b35-76d28f6ccff2.png)
