### ISSUE TITLE
Connection Wizard - checkboxes too small when selected Local folder is not empty

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7560]
Client: 2.6.0rc2 (build 12577)
macOS 10.15, Ubuntu 19.04
Server: 10.3.0 stable

Steps to recreate:
1) Select 'Add new' account in the account tab
2) Enter server url
3) Enter login details
4) In 'Setup local folder options' select a Local folder that is not empty
5) Check the 'Ask for confirmation' checkboxes

Actual result: 'Ask for confirmation before synchronizing' checkboxes are too small. (But they get displayed when the dialog is bigger)
Expected result: Checkboxes are always properly displayed. 

Ubuntu
<img width="734" alt="Screenshot 2019-10-29 at 09 52 20" src="https://user-images.githubusercontent.com/49001702/67752463-4e925600-fa33-11e9-8ed1-c7c6fbe72fb5.png">

mac
<img width="748" alt="Screenshot 2019-10-29 at 09 48 31" src="https://user-images.githubusercontent.com/49001702/67752465-4fc38300-fa33-11e9-872e-44e239b7b6ba.png">

**Comment by TheOneRing** [comment]
@HanaGemela could you test with the latest builds?
