### ISSUE TITLE
Nothing provides nautilus-python needed by owncloud-client-nautilus

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7570]
Centos 8
Client: 2.6.0rc4 (build 1679)

Steps to recreate:
1) Run `sudo yum install owncloud-client-nautilus`

Expected result: owncloud-client-nautilus has been installed
Actual result: Error:
 Problem: conflicting requests
  - nothing provides nautilus-python needed by owncloud-client-nautilus-2.6.0~rc4-1679.2.x86_64

**Comment by jnweiger** [comment]
We have 
https://build.opensuse.org/package/show/isv:ownCloud:Qt5125/nautilus-python

It builds well for CentOS_8. (Fails strangely on centos7)
The package does not show up in the build repos.

**Comment by jnweiger** [comment]
I've done a manual 
`osc copypac isv:ownCloud:Qt5125 nautilus-python isv:ownCloud:desktop` to bring it into place.

Now, it works for me
![image](https://user-images.githubusercontent.com/1108546/73462791-9dc28c80-437c-11ea-981f-5024baabc872.png)

TODO: our linux build toolchains needs to learn about nautilus-python

**Comment by jnweiger** [comment]
Added nautilus-python to prepare_obs_prj.sh in ownbrander/scripting 
-- should be visible in next daily build.
