### ISSUE TITLE
SMB share: "Directory temporarily not available on server"

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [owncloud/client#7572]
I use ownCloud 2.5.1 from the Debian 10 package repository.
I am not able to use a newer upstream version of ownCloud because of complex package dependencies.

I have a SMB share connected to my ownCloud server account. Loggin into my ownCloud account via web-frontend the folder representing the share is accessiable without problems. Also the share settings indicated that the share is connected without any problems.

But my ownCloud client on Debian tells me that the share representing ""Directory temporarily not available on server".

**EDIT**: I can confirm that I have no problem with an ownCloud Client 2.5.4 on a Windows 10 machine.

**EDIT2**: I setup a second Debian 10 machine. It is a VM running on a Windows 10 host. On this second Debian 10 machine I have no problem to access the share. So it looks like this is not dependend on server or client version. Must depend on a specific machine.

Do you have any idea or hints about it?

Via Google I can not find any report about that error string.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
Tonight I will test the release candidate for the 2.6.0 client.

https://github.com/owncloud/client/issues/7515#issuecomment-549513532

**Comment by michaelstingl** [comment]
> I use ownCloud 2.5.1 from the Debian 10 package repository.

We recommend to use the repositories maintained by ownCloud.

**Stable:**
https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client

**Beta & RC:**
https://software.opensuse.org//download.html?project=isv:ownCloud:desktop:testing&package=owncloud-client

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I am aware of this "maintained" repositories.
Support for Debian 10 (what is stable!) is still missing.

**Comment by guruz** [comment]
Please re-open if it happens again.
