### ISSUE TITLE
Overlay icons not shown sometimes

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7573]
Ubuntu 18.04
Client Testpilot 2.6.0rc4 (build 1684)
Server: 10.3.0 stable

One file doesn't have an overlay icon, the other files do. The file with missing icon is shown in 'Sync protocol' as Downloaded.

<img width="875" alt="Screenshot 2019-11-05 at 10 29 05" src="https://user-images.githubusercontent.com/49001702/68195966-2a48f300-ffb8-11e9-9491-bcddf04d9caa.png">

macOS 10.15
Client non-branded 2.6.0rc4 (build 12665)
Server: 10.3.0 stable

One account has overlay icons, the other doesn't

<img width="975" alt="Screenshot 2019-11-04 at 17 32 37" src="https://user-images.githubusercontent.com/49001702/68195710-9aa34480-ffb7-11e9-81f8-9c289499df92.png">

Steps to recreate not known at the moment

**Comment by guruz** [comment]
@HanaGemela So this is two different bugs? You are showing Ubuntu in one screenshot and macOS in another.
The overlay icons are highly platform specific, so the platforms can't be compared and should not be in the same bug report.

**Comment by guruz** [comment]
Regarding the macOS bug: It might already help to restart the client, is the problematic account a newly created one?

**Comment by HanaGemela** [comment]
OK, then this is two separate bugs. I don't have steps to recreate for neither of them . In both cases it happened after installation. For mac it was an old account, for Ubuntu it was a newly added account. I'll split the issues once I have steps to recreate, is that ok?

**Comment by ogoffart** [comment]
I tried reproducing the problem on Nautilus, but it worked fine.
I added a file on the server in a folder that was open in nautilus, and the file appeared with the sync'ed icon.

**Comment by HanaGemela** [comment]
Another example from Windows 10, 2.6.0 stable client

1) I've installed the client
2) Let the computer restart
3) Windows got updated
4) Overlay icons were missing

<img width="935" alt="Screenshot 2019-11-27 at 15 32 52" src="https://user-images.githubusercontent.com/49001702/69732440-e9ae4680-112b-11ea-94fb-f0e0867fa5d5.png">

**Comment by HanaGemela** [comment]
Overlay icons missing again in 2.6.1daily20191127 (build 12732), Windows 10 after editing Ignored files

**Comment by michaelstingl** [comment]
@HanaGemela Please open individual issues for every platform. Win Explorer, Mac Finder and Ubuntu Nautilus are all totally different.

**Comment by HanaGemela** [comment]
https://github.com/owncloud/client/issues/7612 [Windows] Overlay icons not shown sometimes
https://github.com/owncloud/client/issues/7613 [Mac] Overlay icons not shown sometimes
https://github.com/owncloud/client/issues/7614 [Ubuntu] Overlay icons not shown sometimes

**Comment by michaelstingl** [comment]
@HanaGemela thanks a lot!
