### ISSUE TITLE
gnome-keyring dependence on 2.6.0rc4 on Debian 10

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [owncloud/client#7578]
I use 2.6.0rc4 on Debian 10.

There is still a dependency to `gnome-keyring`. There is no technical reason for this.

Please remove this dependency.

The problem is that if `gnome-keyring` is installed it asked me everytime for the master password when ownCloud starts. But I do not use this keyring for any application.

**Comment by michaelstingl** [comment]
@ogoffart @jnweiger @TheOneRing change this?

**Comment by TheOneRing** [comment]
https://github.com/frankosterfeld/qtkeychain/issues/151

**Comment by jnweiger** [comment]
We have libgnome-keyring as a direct dependency of our  owncloud-client package. It is not a dependency of qtkeychain.  qtkeychain pulls libsecret. I'll remove the libgnome-keyring dependency, it seems it is not needed, and deprecated anyway.

Thanks for testing! Thanks for the report!

**Comment by jnweiger** [comment]
Pushed template update to ownbrander/scripting --  Next dailies will show the fix.
Also rebuilding rc4 (tar unchanged) in https://build.opensuse.org/package/show/isv:ownCloud:desktop:testing/owncloud-client

**Comment by jnweiger** [comment]
Upgrading from 260rc2 to 260 final has this in the logs:
```
Removing libgnome-keyring0:amd64 (3.12.0-1build1) ...
Removing libgnome-keyring-common (3.12.0-1build1) ...
```
This confirms the dependency is gone.
