### ISSUE TITLE
windows 10: claims client 2.6.0rc4 msi contains a virus

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7579]
Tested on windows 10 Enterprise Evaluation
Build 17763.rs5_release.180914-1434 

Installing the 2.6.0 rc4 msi packages of testpilotcloud-client or ownCloud-client results in

![image](https://user-images.githubusercontent.com/1108546/68403637-8c068a00-017d-11ea-9c10-55912cf48bfe.png)

![image](https://user-images.githubusercontent.com/1108546/68403694-a3de0e00-017d-11ea-81c1-45ab6de436ec.png)

The downloads get deleted before I can install them:
![image](https://user-images.githubusercontent.com/1108546/68404094-4c8c6d80-017e-11ea-8eb5-0b6c74f549f6.png)

![image](https://user-images.githubusercontent.com/1108546/68404014-2ebf0880-017e-11ea-894b-5d1d48eef393.png)

**Comment by michaelstingl** [comment]
@jnweiger please also upload to https://www.virustotal.com/ and post the results

**Comment by jnweiger** [comment]
owncloud client 2.6.0 RC2 downloads and installs without complaints on the same system.

**Comment by jnweiger** [comment]
virustotal is happy with https://download.owncloud.com/desktop/testing/ownCloud-2.6.0.12984.12659-rc4.msi

**Comment by michaelstingl** [comment]
@TheOneRing any idea?

**Comment by jnweiger** [comment]
Downloading the same again -- seems to be good.
![image](https://user-images.githubusercontent.com/1108546/68405197-f3253e00-017f-11ea-94ab-f24c9a0e0d85.png)

**Comment by jnweiger** [comment]
It is a fresh VM with only two reboots. They seem to want a third reboot... Let's see if that helps.
![image](https://user-images.githubusercontent.com/1108546/68405762-f3720900-0180-11ea-858f-90dff8bd67a9.png)

**Comment by jnweiger** [comment]
Not reproducable with the same VM snapshot. No more virus alerts seen.
Checked our three mirror URls with virustotal. All fine.

Let's say it was a microsoft goof.
Closing.

**Comment by jnweiger** [comment]
Analyst comments:

                We have removed the detection.  Please follow the steps below to clear cached detection and obtain the latest malware definitions.

     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
     3. Run "MpCmdRun.exe -SignatureUpdate"

Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions

Thank you for contacting Microsoft.

**Comment by jnweiger** [comment]
![image](https://user-images.githubusercontent.com/1108546/68489122-c25c0c00-0246-11ea-8337-7d847d48245e.png)

Reproduced with the final build, before following microsoft's instructions.

![image](https://user-images.githubusercontent.com/1108546/68489408-51692400-0247-11ea-95cd-000db60fbca5.png)

Still getting the error.

**Comment by guruz** [comment]
Virustotal seems fine
.GPO.msi: https://www.virustotal.com/gui/file/0d3d72e76b2fc6eb3a3693f0e31f4f539e25f4e55ded40013577e7ebdcf647be/detection
.msi: https://www.virustotal.com/gui/file/f14244365e55da230c233b3641e771fec4a4a3be72687091639568f3d2aeed97/detection

**Comment by guruz** [comment]
I can not reproduce this with my windows 10 VM. I installed all the updates..
Maybe it's @jnweiger 's VM which actually has the virus.

But still would be good to have a 3rd tester?
@TheOneRing @HanaGemela

**Comment by HanaGemela** [comment]
My Windows 10 pro 18362.418 installs ownCloud client 2.6.0 (build 12644) without any complains but my Defender is different:
![image](https://user-images.githubusercontent.com/49001702/68551157-3266bf80-040a-11ea-96fa-44e3b153b7e6.png)

**Comment by cdamken** [comment]
I tested yesterday with the windows antivirus updated with Chrome and IE in Windows 10

I downloaded from https://download.owncloud.com/desktop/testing/ownCloud-2.6.0.13018.12690.msi

And could install from both browsers.

**Comment by TheOneRing** [comment]
If virus total says its ok its ok.
If a vm with an ancient antivir definition complains it is a false positive that has already be fixed...

**Comment by guruz** [comment]
We'll assume then it is fixed and a MS glitch, thanks everyone for testing
