### ISSUE TITLE
Auto-update should follow the installation path selected by the previous version

### ISSUE THREAD

**Issue by NiceFeather** [owncloud/client#7580]
The program was automatically upgraded a few days ago, but I noticed the installation of the new version didn't follow the installation path selected by the previous version which is located at "E:\ownCloud", it automatically installed into the "C:\ Program Files (x86)" directory of the system, in fact that is actually a brand new installation. I think it should be improved in next installation pack.

**Comment by NiceFeather** [comment]
and I noticed the auto-starting feature was not working anymore after auto-updating, because the installed program directory is different with the key value of Registry.

**Comment by HanaGemela** [comment]
Auto-starting feature still broken in 2.6.1sprint2 (build 12916), Windows 10
Also broken for the first installation, not just for the update

**Comment by HanaGemela** [comment]
@TheOneRing 
When I remove the entry from Registry (Computer\HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\Run), new one is created and the auto start works. 
When I change the location when installing new version, the Registry is not updated and auto start doesn't work

**Comment by HanaGemela** [comment]
Auto start moved into a new issue https://github.com/owncloud/client/issues/7672
Original bug is fixed in 2.6.1sprint2 (build 12916)
