### ISSUE TITLE
"Force sync now" not discovering new file (only restarting helps)

### ISSUE THREAD

**Issue by philbit** [owncloud/client#7590]
### Expected behaviour
"Force sync now" causes the client to discover any locally added/changed files it might have missed, so they are synchronized to the server. 

### Actual behaviour
Files added on the client computer "behind the owncloud client's back" are not discovered/sync'ed when I hit "Force sync now". But they are when I completely restart the client.

((I had expected "Force sync now" and restarting to be essentially equivalent. If at all, I would have assumed "Force sync now" to do even MORE than restarting, since a restarted client could theoretically still use some cached information from a previous instance)).

### Background
All the directories I have write access to on the client computer are NFS mounted from a central location (imagine a HPC cluster with several frontends etc.). Thus, my local ownCloud sync directory on the client computer is on one of those NFS shares. Sometimes, it happens that a file in the local sync directory is added by a different computer on the network, i.e. "behind the owncloud client's back".

In older versions of the client, the sync would eventually still happen, although it would sometimes take long to discover the change. With the current client, this doesn't seem to happen anymore (but I am not sure this was ever expected behavior; was it?). In order to remove the inconsistency if such a change has happened, I manually try "Force sync now" on the machine running the client, but it still fails to discover the created file. Only restarting the client entirely helps. I use web authentication (via the browser), so restarting the client is rather tedious.

### Steps to reproduce
1. Install client with local folder on a mounted NFS share
2. When clean sync has been achieved, add a local file to the owncloud directory on a different machine mounting the same NFS share (also tested for deletion)
3. Wait for client to discover the change (--> does not happen in 2.6.0, but happened in some earlier version).
4. Hit "Force sync now" in the client settings (--> still does not discover the file).
5. Restart client (--> file is discovered and sync'ed to server).

### Server configuration
(I do not have access to the server, so the only thing I know is the server version)

ownCloud version:
ownCloud Enterprise Edition 10.1.0 (stable)

### Client configuration
Client version:
2.6.0 (build 1714)

Operating system:
Ubuntu 18.04 LTS

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):
wasn't able to find

Client package (From ownCloud or distro) (Linux only):
from ownCloud (via opensuse repo)

Installation path of client:
/usr/bin/owncloud

### Logs
not attached

Edit: Trying to reproduce this, I noticed that _sometimes_, the new/deleted file actually _is_ discovered. In these cases, after hitting "Force sync now", the synchronization (overlayed blue icon) also takes much longer (as if the client is doing more work). When it doesn't discover the file, the time the blue "sync in progress" icon is displayed is only one or two seconds. I have do not change anything about the setup between the different sync attempts, so presently it looks entirely random to me whether the change is discovered by "Force sync now" or not.

**Comment by philbit** [comment]
Might be a hint on what's going wrong: On a different system (also Ubuntu 18.04 LTS), I have client version "2.4.1+dfsg-1", installed via the standard system repositories. In this version, when I hit "Force sync now", the client says "Looking for changes in {x}", where {x} cycles through all the folders. It doesn't do this on the system above. Instead, it very quickly changes back to the "sync'ed" status (green checkmark overlay icon).

**Comment by ogoffart** [comment]
"Force sync now" is  not much more than just doing a normal sync.
The part that wipe the cache can be done by pressing ctrl+f6 in the account settings when the folder is selected.

The reason for files to be missed is if the file system watcher is not doing its job at notifying the client that files have changed while it was running.

**Comment by michaelstingl** [comment]
@philbit Older clients did discovery more often. Latest client rely more on file system events. Maybe they're not reliable with your network drives. You could try to set a smaller `OWNCLOUD_FULL_LOCAL_DISCOVERY_INTERVAL`. Here you can find more information:
https://doc.owncloud.org/desktop/advanced_usage/environment_variables.html

**Comment by philbit** [comment]
@michaelstingl Thank you. That explains the difference to previous versions without manual interference.

@ogoffart Thank you! I didn't know about ctrl+F6. This indeed causes the client to cycle through all local folders as I described above. However, this kind of clean local discovery takes much much longer than the full local discovery without discarding the cache (see below), so I think it's not really an alternative to how "Force sync now" behaves in my 2.4.1 installation, where it also showed "Checking for changes in ..." and reliably detected changes (but much faster than a full Ctrl+F6, so I assume it is also using "full local discovery" without clearing the cache).

I did some testing to compare the different discovery modes and their triggers:

- If I set OWNCLOUD_FULL_LOCAL_DISCOVERY_INTERVAL to 0 (i.e. always use full local discovery), syncing takes about 12s every time I hit "Force sync now" and changes are reliably detected.

- In contrast, a sync after discarding the cache via Ctrl+F6 takes more than 2 minutes.

- OWNCLOUD_FULL_LOCAL_DISCOVERY_INTERVAL=0 alone does not help discover files missed by the system watcher automatically, unless something else is triggering a discovery (either a local change picked up by the system watcher or a remote change). I.e. it would in principle do a full local discovery every time (instead of a normal one), but it is never triggered. Instead, using the information at https://doc.owncloud.org/desktop/advanced_usage/configuration_file.html, I had to set both fullLocalDiscoveryInterval=0 and forceSyncInterval to something low like 30000, in order to force a discovery (which will then always be full local) every 30 seconds.

(Times above are those displayed by in the client status messages.)

The thing is that I seem to be able to trigger a full local discovery (witout discarding the cache) via "Force sync now" in 2.4.1 (without any changes to OWNCLOUD_FULL_LOCAL_DISCOVERY_INTERVAL). So in 2.6.0 there seems to be no way to manually trigger the full local discovery without discarding the cache other than restarting the client (or setting OWNCLOUD_FULL_LOCAL_DISCOVERY_INTERVAL to 0 and using "Force sync now", but then all the automatic discoveries will be full local as well).

Would it be unreasonable to expect there to be some way to trigger a full local discovery manually without discarding the cache? Maybe now that full local discovery is used less often in general (apparently every hour according to https://doc.owncloud.org/desktop/advanced_usage/configuration_file.html), "Force sync now" sounds "forceful" ;-) enough to be a candidate? Or a separate option?

**Comment by dragotin** [comment]
Apart from considering a change to the "Force sync now" option, I think we should try to find out if the sync directory is on NFS (or any other "difficult" filesystem) and either notify the user about the problems with it, or try to fix that.

If we knew that the local dir is on NFS we could consider to always do full discoveries and somehow tell the user that this will be slow.

**Comment by TheOneRing** [comment]
Fixed in 2.10 https://github.com/owncloud/client/commit/a94a8abe6ffe2453d8cb6c16812f6d3a7fe59d69
