### ISSUE TITLE
MacOS 10.14.6 (18G1012) application icon broken

### ISSUE THREAD

**Issue by sbonaime** [owncloud/client#7594]
MacOS application icon is broken for 2.6.0 (build 12703)
Macos 10.14.6 (18G1012)

![Capture d’écran 2019-11-14 à 14-11-19 14 07 49](https://user-images.githubusercontent.com/750709/68859757-4a7b5f00-06e8-11ea-8604-a5480ce6ed84.png)

**Comment by ChrisEdS** [comment]
@sbonaime Have you completely reinstalled the client or have you updated it?

**Comment by sbonaime** [comment]
I updated from 2.6.0.rc4 to 2.6.0. I remember that 2.6.0.rc4 has also this broken icon.

**Comment by ChrisEdS** [comment]
Doesn't seem like a general problem.

![image](https://user-images.githubusercontent.com/33026403/68860417-c4601800-06e9-11ea-8e43-8580d78f5eea.png)

**Comment by sbonaime** [comment]
Anything I can do to update the icon ?

**Comment by ChrisEdS** [comment]
You can try to clear the icon cache. Run a terminal and execute this command:
```
sudo rm -rfv /Library/Caches/com.apple.iconservices.store; sudo find /private/var/folders/ \( -name com.apple.dock.iconcache -or -name com.apple.iconservices \) -exec rm -rfv {} \; ; sleep 3;sudo touch /Applications/* ; killall Dock; killall Finder
```

https://gist.github.com/ismyrnow/e92c6010cda9325b2d8811387a05f224#file-mac-clear-icon-cache-sh

**Comment by sbonaime** [comment]
I tried this gist which rebuild all my icons but unfortunately not my Owncloud !

**Comment by ChrisEdS** [comment]
Can you check if the file `owncloud.icns` is available and the access rights fit?

![image](https://user-images.githubusercontent.com/33026403/68862360-9977c300-06ed-11ea-80a5-78b7ff3da39d.png)

**Comment by sbonaime** [comment]
![Capture d’écran 2019-11-14 à 14-11-19 14 58 00](https://user-images.githubusercontent.com/750709/68863213-35ee9500-06ef-11ea-9e9e-b564bf0aea6f.png)

Same permissions

**Comment by ChrisEdS** [comment]
I'm running out of ideas. Have you already tried to uninstall the client with a tool like `AppCleaner` and reinstall?

**Comment by ChrisEdS** [comment]
What you might want to try: Drag `owncloud.icns` to the icon in the `Info` dialog.

![image](https://user-images.githubusercontent.com/33026403/68869599-bca86f80-06f9-11ea-8967-c9aae61cc955.png)

**Comment by sbonaime** [comment]
>What you might want to try: Drag owncloud.icns to the icon in the Info dialog.

Thanks !
