### ISSUE TITLE
Support opentelemetry.io

### ISSUE THREAD

**Issue by butonic** [owncloud/client#7595]
https://opentelemetry.io/ allow tracing requests from client to server.

**Comment by michaelstingl** [comment]
@TheOneRing effort estimation? Should this be part of the client or should this be better a Qt thingy?

**Comment by michaelstingl** [comment]
Ah, they have a C++ library: https://github.com/open-telemetry/opentelemetry-cpp

**Comment by TheOneRing** [comment]
There would also be https://api.kde.org/frameworks/kuserfeedback/html/index.html

**Comment by TheOneRing** [comment]
> 
> 
> Ah, they have a C++ library: https://github.com/open-telemetry/opentelemetry-cpp

Its just a bunch of empty folders at the moment.

**Comment by butonic** [comment]
opencensus has merged with opentracing into opentelemetry. maybe they will continue to use the opencensus stuff in https://github.com/census-instrumentation/opencensus-cpp

**Comment by butonic** [comment]
related: https://github.com/owncloud/client/issues/4606

**Comment by tboerger** [comment]
IMHO this doesn't really make sense for clients, this only makes sense for complex micro service architectures where it's hard to debug the flow of requests.

**Comment by ogoffart** [comment]
What exactly is the client supposed to log?
I believe logging request would be better done on the server side.

**Comment by michaelstingl** [comment]
W3C specification that defines standard HTTP headers and a value format to propagate context information that enables distributed tracing scenarios:
https://www.w3.org/TR/trace-context/#examples-of-http-traceparent-headers
