### ISSUE TITLE
Approved but unmerged PR´s

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#7597]
As of today, 
there are a bunch of approved but unmerged changes. (not the `DO NOT MERGE YET` labeled)
What is causing that these changes do not get merged?
Maybe just no one is clicking the button...?
Sorry for pushing

@michaelstingl @ogoffart @TheOneRing

**Comment by TheOneRing** [comment]
Some of them are not finished yet or require other changes before they can be merged.
Some are just proposals and need discussion/evaluation first

**Comment by mmattel** [comment]
Sorry, had not been able to identify them as unfinished/proposal/evaluation.
