### ISSUE TITLE
[DOCS] master and 2.6 are not in sync

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#7598]
If you take a look on docs (example: https://doc.owncloud.org/desktop/navigating.html at the bottom)
and switch between **master** and **2.6**, you see differnces which should not be in 2.6 as they have already been fixed in master.

**Master:**
![image](https://user-images.githubusercontent.com/3321281/68940811-6fcda300-07a4-11ea-8156-4d370627a9df.png)

**2.6:**
![image](https://user-images.githubusercontent.com/3321281/68940835-8116af80-07a4-11ea-89a4-282026863c0f.png)

Seems that no backporting has been made.
Maybe a full resync from **master** to **2.6** is necessary to bring back sync status.

@settermjd @michaelstingl

**Comment by settermjd** [comment]
Will get this sorted out.
