### ISSUE TITLE
ownCloud-osx10.11-2.6.0.12703.pkg not working on macOS 10.11

### ISSUE THREAD

**Issue by s1a3ti** [owncloud/client#7603]
I get the following error message when I try to run the client:

"Sie können diese Version des Programms 'owncloud' nicht mit dieser Version von OS X verwenden. Auf Ihrem Computer ist OS X 10.11.6 installiert. Das Programm erfordert OS X 10.12 oder neuer."

However, it is running, when started from the command line:
/Applications/owncloud.app/Contents/MacOS/owncloud

Best regards,
Christoph

**Comment by guruz** [comment]
@dschmidt Places to investigate:
https://github.com/owncloud/client/blob/2.6/cmake/modules/MacOSXBundleInfo.plist.in
https://github.com/owncloud/client/blob/2.6/admin/osx/macdeployqt.py#L410
https://github.com/owncloud/client/blob/2.6/shell_integration/MacOSX/OwnCloudFinderSync/desktopclient/Info.plist#L25 What is MACOSX_DEPLOYMENT_TARGET set to?
https://github.com/owncloud/client/blob/2.6/shell_integration/MacOSX/OwnCloudFinderSync/FinderSyncExt/Info.plist#L28

**Comment by sbgraphic** [comment]
Hello, same issue for me on osx 10.11 with same package:

--
Cannot open this version of the "owncloud" application with this version of osx
You have OS X 10.11.6. The application requires OS X 10.12 or later.
--
Impossible d'ouvrir cette version de l'application "owncloud" avec cette version d'osx. Vous avez OS X 10.11.6. L’application requiert OS X 10.12 ou ultérieur
--

I'll revert to 2.5.4 for now.
Best

**Comment by dschmidt** [comment]
> Hello, same issue for me on osx 10.11 with same package:
> 
> ## --
> Cannot open this version of the "owncloud" application with this version of osx
> You have OS X 10.11.6. The application requires OS X 10.12 or later.
> ## Impossible d'ouvrir cette version de l'application "owncloud" avec cette version d'osx. Vous avez OS X 10.11.6. L’application requiert OS X 10.12 ou ultérieur
> I'll revert to 2.5.4 for now.
> Best

Please provide the URL to the .pkg you have used.

**Comment by sbgraphic** [comment]
Hello, if I remember well it was this one:
https://download.owncloud.com/desktop/stable/ownCloud-osx10.11-2.6.0.12703.pkg
Bye

**Comment by dschmidt** [comment]
Mixed up this ticket, answered in another one. 2.6.0 is b0rked.

Try a new build and refer to https://github.com/owncloud/client/issues/7628.
