### ISSUE TITLE
[Windows] Overlay icons not shown sometimes

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7612]
Windows 10
Client: 2.6.0 stable

1. I've installed the client
2. Let the computer restart
3. Windows got updated
4. Overlay icons were missing

<img width="935" alt="Screenshot 2019-11-27 at 15 32 52" src="https://user-images.githubusercontent.com/49001702/69796344-2763ab80-11ce-11ea-8db8-fec4b4d1fbc5.png">

**Comment by HanaGemela** [comment]
Overlay icons missing again in 2.6.1daily20191127 (build 12732), Windows 10 after editing Ignored files and restarting the client

**Comment by michaelstingl** [comment]
@HanaGemela could you check with the steps from the wiki?
https://github.com/owncloud/client/wiki/Debugging-Overlay-Icons#windows

**Comment by TheOneRing** [comment]
Was the context menu available? If not the shell extension was not loaded.
How much time passed between the system start and your screenshot?

**Comment by HanaGemela** [comment]
As it was so long time ago, I don't have more info that I could add
