### ISSUE TITLE
[Ubuntu] Overlay icons not shown sometimes

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7614]
Ubuntu 18.04
Client Testpilot 2.6.0rc4 (build 1684)
Server: 10.3.0 stable

One file doesn't have an overlay icon, the other files do. The file with the missing icon is shown in 'Sync protocol' as Downloaded. Steps to recreate unknown

<img width="875" alt="68195966-2a48f300-ffb8-11e9-9491-bcddf04d9caa" src="https://user-images.githubusercontent.com/49001702/69797076-63e3d700-11cf-11ea-9774-b1163de814a1.png">

**Comment by fmoc** [comment]
Possibly related to #8334. The timeout is increased in #8571. I hope that the PR fixes this issue as well.

**Comment by TheOneRing** [comment]
Sounds reasonable, closing.
