### ISSUE TITLE
[Windows] 'Add folder sync connection' dialog doesn't look nice

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7615]
Client: 2.6.1daily20191127 (build 12732)
Windows 10
Server: 10.3.2 RC1

Steps to recreate:
1) Go to Account tab
2) Click on 'Add folder sync connection' button

Actual result: 'Add folder sync connection' dialog has been opened and it doesn't look nice. Cross icon, logo and the title are not aligned. Apart from the look the left arrow doesn't do anything

<img width="498" alt="Screenshot 2019-11-28 at 15 20 11" src="https://user-images.githubusercontent.com/49001702/69813908-77089e00-11f3-11ea-9490-014e577f1641.png">

Expected result: All nicely aligned and the left arrow removed

**Comment by TheOneRing** [comment]
Should look better nowadays
