### ISSUE TITLE
PROPFIND requests for unchanged folders too.

### ISSUE THREAD

**Issue by user-64** [owncloud/client#7617]
Hi,
I know I am not on the current version of ownCloud. But due to a limitation with my other projects I'm unable to update qt version.

When I upgraded from 1.8.1 to 2.4.2 sync PropFind requests goes for unchanged folders too till the nth level inside the folder, even if there is a change in single folder or there is no change at all. 

I checked the latest code & change logs too, but couldn't find the solution. Can you tell me in which version of ownCloud client this got fixed,if there was a such issue.

Sorry for bothering you guys. Thanks in advance.

Client configuration
Client version: 2.4.2
Operating system: Windows/Mac
Qt version : 5.6

**Comment by michaelstingl** [comment]
Official ownCloud clients come with own Qt. No need to update system Qt:
https://owncloud.org/download/#owncloud-desktop-client

**Comment by user-64** [comment]
I have also customized the source code for my work. Hence, won't be able to upgrade immediately. Wanted to know if there was a regression, so that I can patch it in my code. Thanks.

**Comment by michaelstingl** [comment]
> Wanted to know if there was a regression, so that I can patch it in my code.

This is an issue tracker. For support, please use https://central.owncloud.org/c/desktop
