### ISSUE TITLE
File is displayed in grey colour in Finder 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7618]
macOS 10.15.1
Client 2.6.1-daily20191127 (build 12791)

Steps to recreate:
1) Make sure hidden files are visible in Finder
2) Download a large file
3) Stop sync in the middle
4) Resume the sync

Actual result:
When the hidden files are visible, the new file is grey. When hidden files are hidden, the new file is black.
The incomplete downloading file is grey and once the download finishes, the file is replaced by that completely downloaded file including the colour of the file name

Expected result: File is shown in black 

Found during testing https://github.com/owncloud/client/issues/7419
<img width="578" alt="64534295-7f98b900-d315-11e9-846a-6790205d6ac1" src="https://user-images.githubusercontent.com/49001702/69963353-5a7ca680-1510-11ea-955e-c517f6355fdc.png">

**Comment by TheOneRing** [comment]
Still valid?

**Comment by HanaGemela** [comment]
Still valid in 2.6.3 (build 13252), macOS 10.15.3

**Comment by michaelstingl** [comment]
> Still valid in 2.6.3 (build 13252), macOS 10.15.3

Could you check attributes/properties of this file? (Terminal & Finder) What's different from regular files?

**Comment by HanaGemela** [comment]
When I open a different folder in Finder and then go back to ownCloud folder, the file has black colour.
So nothing changed with the file, just the Finder window refreshed -> Finder issue?

**Comment by TheOneRing** [comment]
sounds like a finder issue 🤷‍♀ 🦐
