### ISSUE TITLE
Server Activity should match the other tabs

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7619]
https://github.com/owncloud/client/issues/6728#issuecomment-432401762

Enhancements in Server Activity tab:

1. Proper columns and headers
2. Option to resize column width
3. Option to filter by account

**Comment by TheOneRing** [comment]
@HanaGemela is this still an issue?

**Comment by HanaGemela** [comment]
Yes

**Comment by TheOneRing** [comment]
Duplicate of https://github.com/owncloud/client/issues/4350
