### ISSUE TITLE
Evaluate why HTTP2 is broken with Qt 5.12.5

### ISSUE THREAD

**Issue by guruz** [owncloud/client#7626]
Created from https://github.com/owncloud/client/issues/7610

**Comment by jnweiger** [comment]
Do we have a demo server that runs HTTP2?

I'd be happy to see a test setup, that demonstrates that e.g 2.4.3 as used by @tessus works fine, and client 2.6.1 with `env OWNCLOUD_HTTP2_ENABLED=1` fails.

**Comment by tessus** [comment]
Thanks for picking this up again. 

This is the exact version of my current client:
Version 2.4.3 (build 10347)
Built from Git revision 560555 on Aug 10 2018, 21:27:04 using Qt 5.10.1

**Comment by ho4ho** [comment]
@tessus https://github.com/owncloud/client/issues/7610#issuecomment-581053314:
> the QT implemrntation of H2 has been broken since forever. There's always: "ah, there's this bug, which will be fixed in QT x.x.x", then it takes forever to switch the client to use that QT version and then it starts all over. If QT is unable to do H2 properly, a different approach must be taken. e.g. using the nghttp2 lib directly and use a wrapper to use from the oc client.
>
> With all due respect, but after a few years of trying to get H2 working without success, somebody must accept that the current approach is not working.
In 2020 one should be able to expect H2 to be working flawlessly.
