### ISSUE TITLE
Owncloud legacy macos client not working on OS X 10.10 (again).

### ISSUE THREAD

**Issue by mcvogt** [owncloud/client#7628]
Hi,

neither the 2.6.0 stable ...-osx-10.11 macos legacy version, nor the macos legacy daily builds are working on macos 10.10.5. I keep getting the "The application requires OS X 10.12 or later" error message on startup.

When trying to start the client from the command line, I get
```
dyld: Library not loaded: @executable_path/../MacOS/libowncloudsync.0.dylib
  Referenced from: /Applications/owncloud.app/Contents/MacOS/./owncloud
  Reason: no suitable image found.  Did find:
	/Applications/owncloud.app/Contents/MacOS/./../MacOS/libowncloudsync.0.dylib: code signature invalid for '/Applications/owncloud.app/Contents/MacOS/./../MacOS/libowncloudsync.0.dylib'
```

Thanks for your help.

Best regards,
Marcus

**Comment by michaelstingl** [comment]
@mcvogt thanks for the feedback! We'll have a look

**Comment by michaelstingl** [comment]
@TheOneRing @dschmidt Could you clarify min. requirements for 2.6.x and for a 2.6.x-legacy client? Which Qt, which Xcode & macOS for the build machine etc

**Comment by dschmidt** [comment]
Can you try this build? 
https://download.owncloud.com/desktop/daily/ownCloud-osx10.11-2.6.1.12880-daily20191217.pkg

**Comment by dschmidt** [comment]
FTR this is built with macOS 10.14, with the deployment target set to 10.10.
The Qt version is 5.10.x. 

Xcode is probably not too relevant and I don't know from the top of my head.

master depends on Qt 5.12 and won't support 10.10 anymore because Qt 5.12 needs macOS 10.12.

**Comment by sbgraphic** [comment]
Thanks, this build 2.6.1 above seems to works fine with 10.11 now, Best !

**Comment by dschmidt** [comment]
The new stable 2.6.1 release should work as well!
