### ISSUE TITLE
Update settings page icons

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#7629]
Current suggestion is
![Clipboard - 4  Dezember 2019 11_41](https://user-images.githubusercontent.com/200626/70138488-a6565980-1690-11ea-9e51-c4b6342125e2.png)

https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt

**Comment by TheOneRing** [comment]
https://github.com/KDE/breeze-icons/blob/master/icons/actions/32/system-lock-screen.svg could also be ineresting

**Comment by hurradieweltgehtunter** [comment]
I used Font Awesome as icon lib to have aligned Icons. Also the lib is very big and has a lot of icons. We should stay in this lib to have a aligned look.

**Comment by jnweiger** [comment]
If we choose to stay with the existing theme, I could draft a matching quit.svg

**Comment by hurradieweltgehtunter** [comment]
Have a look here: https://fontawesome.com/icons?d=gallery&m=free
No need for custom icons

**Comment by guruz** [comment]
@hurradieweltgehtunter @TheOneRing Is this the same icon set that our iOS and Android apps use?
Is it the same icon set that Phoenix uses?

**Comment by michaelstingl** [comment]
Icon sets not aligned yet, but I have this on my list. So anything icon related is temporary anyway…

**Comment by hurradieweltgehtunter** [comment]
> @hurradieweltgehtunter @TheOneRing Is this the same icon set that our iOS and Android apps use?
> Is it the same icon set that Phoenix uses?

Good point and agreed. I'm using a single Icon lib in all of my projects (marketplace, oc.online, oc.org).

**Comment by TheOneRing** [comment]
Fixed in 2.7
