### ISSUE TITLE
https://doc.owncloud.org/desktop/latest/ still points to 2.5

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7632]
The entrypoint 'latest' is used e.g. in our websites. It should now be updated point to https://doc.owncloud.org/desktop/2.6

**Comment by jnweiger** [comment]
Handbook release_processes/client/documentation.adoc -- please add details there.

**Comment by settermjd** [comment]
Just created a gitea PR to resolve the issue.

**Comment by settermjd** [comment]
https://github.com/owncloud/client/issues/7632 has been merged, so this should be fixed shortly.

**Comment by settermjd** [comment]
The latest version of the docs now redirects to version 2.6 of the docs.

**Comment by HanaGemela** [comment]
@settermjd 
https://doc.owncloud.org/desktop/latest/ points 2.5
https://doc.owncloud.org/desktop/latest points to 2.6

**Comment by tboerger** [comment]
For me the links redirect to 2.6

**Comment by HanaGemela** [comment]
Works with clear cache

**Comment by jnweiger** [comment]
Changes can **only** work after manually clearing caches.
The contents is sent by Caddy without an cache control headers.
The only max-age that is in the response headers is a 
`strict-transport-security: max-age=315360000; preload` -- that number is 10 years written in seconds.

**Comment by tboerger** [comment]
And how should be a HSTS security header related to cache of websites???
