### ISSUE TITLE
2.6.1 community release - Update new and deprecated platforms

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7633]
- [x] Announce depreciation of platforms for the next release on central 
- [ ] Add change to Release notes
- [x] Update Desktop client for current release [download page](https://owncloud.org/download/#owncloud-desktop-client)
- [x] Update [client docs](https://doc.owncloud.com/desktop/installing.html#system-requirements) for current release (master and backport to 2.6)
- [x] Update [server docs](https://doc.owncloud.com/server/admin_manual/installation/system_requirements.html#client-operating-system) for current release  (master and backport to 10.3 and 10.4)
- [x] Update OBS for next release 
  * [x] deepcopy 2.6.1 including its Qt5125 dependencies
  * [ ] apply deprecations/new platfroms to isv:ownCloud:Qt5125
  * [x] apply deprecations/new platforms to isv:owncloud:Qt5127
  * [x] check if all new platfroms build.
  * [ ] do the same in internal obs.
- [ ] Update Drone toolchain for next release
(needs a full re-sync with OBS. That is more involved.)

**Comment by michaelstingl** [comment]
@jnweiger what about https://doc.owncloud.com/server/admin_manual/installation/system_requirements.html#client-operating-system ?

**Comment by michaelstingl** [comment]
Also:
- Announce deprecation of macOS 10.10, macOS 10.11 with the 2.7 release (Those users can still use the 2.6.x legacy builds for macOS 10.10, macOS 10.11)

**Comment by HanaGemela** [comment]
Already announced depreciations:
Fedora 27 (EOL 2018-11-31)
Ubuntu 17.10 (EOL 2018-07-19)

**Comment by HanaGemela** [comment]
Central: https://central.owncloud.org/t/desktop-client-supported-platforms-updated/24165

**Comment by HanaGemela** [comment]
Update client docs 2.6. PR: https://github.com/owncloud/client/pull/7733

**Comment by HanaGemela** [comment]
Support for the next release
* Windows 7+
* Mac OS X 10.10+ (*64-bit only*)
* CentOS 7 (64-bit only) & 8
* Debian 9.0 & 10
* Fedora 30 & 31
* Ubuntu 18.04 & 19.04 & 19.10
* openSUSE Leap 15.0 & 15.1

**Comment by michaelstingl** [comment]
> * [ ]  Update OBS for next release
> * [ ]  Update Drone toolchain for next release

@dschmidt @jnweiger @TheOneRing both unchecked. What needs to be done?

**Comment by jnweiger** [comment]
The 'update obs for next release' breaks down into:
* [ ] deepcopy 2.6.1 including its Qt5125 dependencies
* [ ] apply deprecations/new platfroms to isv:ownCloud:Qt5125
* [ ] apply deprecations/new platforms to isv:owncloud:Qt5127
* [ ] check if all new platfroms build.
* [ ] do the same in internal obs.

Drone toolchain needs a full re-sync with OBS. That is more involved.

**Comment by michaelstingl** [comment]
> The 'update obs for next release' breaks down into:

@jnweiger I updated the top post

**Comment by jnweiger** [comment]
internal obs has no Qt5127 thus platforms cannot be updated there. Pushing Qt5127 to internal obs is out of scope here.

Drone toolchain updates is a different topic. It will be updated at a later point. Out of scope here.

**Comment by jnweiger** [comment]
@HanaGemela please merge to handbook and close here.

**Comment by HanaGemela** [comment]
Merged
