### ISSUE TITLE
Upgrade to client 2.6.0 resyncs all data and pushes local files to server

### ISSUE THREAD

**Issue by mirekys** [owncloud/client#7637]
### Expected behaviour
Nothing should happen after upgrading the client to latest version as the files weren't changed locally and many of them are very old, the client should stay in sync with the server.

### Actual behaviour
Upgrade to the latest 2.6.0 client triggered a resync of all data in a local directory and pushed them to the server (hopefully just) overwriting the server files ctime on storage backend as the local files were in sync prior to upgrade.

### Steps to reproduce
1.  Upgrade client to 2.6.0
2. 
3. 

### Server configuration
Operating system: RHEL 7

Web server: Apache 2.4

Database: PostgreSQL 9.6

PHP version: 7.1

ownCloud version: 10.0.10

Storage backend (external storage): GPFS

### Client configuration
Client version: 2.6.0

User Agent: Mozilla/5.0 (Windows) mirall/2.6.0 (build 12644)

Operating system: Win 10

Installation path of client: default

### Logs

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

```Since this happened only once after upgrade, we don't have full log file of the event at hand```

2. Client sync logfile `owncloudsync.log` contains just a lot of these INST_SYNC entries for the files that weren't changed locally and were in sync with the server prior to client upgrade:
```
16:20:18||! filename.doc|INST_SYNC|Up|1205311448|553037d6179f8|3802|26382198oc0ba1a88ad3|4||204|0|1205311448|bf007fb9-5964-4b04-a6ae-052631255206|
16:20:18||! filename.pdf|INST_SYNC|Up|1152740874|553037db66622|381753|26382202oc0ba1a88ad3|4||204|0|1152740874|27fc0dc6-db11-4631-9899-5371fe23b1f9|
16:20:27||! filename.pdf|INST_SYNC|Up|1321829906|553037db91206|65329|26382203oc0ba1a88ad3|4||204|0|1321829906|c7bc7430-a671-4155-8389-0ba299c101fb|
16:20:27||! filename.xls|INST_SYNC|Up|1442327276|2b08e61067976bd92668b122f8191298|162816|26382204oc0ba1a88ad3|4||204|0|1442327276|2f4d6408-295c-4624-9004-61584acb23c2|
16:20:33||! filename.doc|INST_SYNC|Up|1086349136|553037eb5b89f|151552|26382206oc0ba1a88ad3|4||204|0|1086349136|90c0070a-c55a-4dcb-80d8-826588b90e9b|
16:20:36||! filename.pdf|INST_SYNC|Up|1433548126|557235bb530cc|2778359|31691578oc0ba1a88ad3|4||204|0|1433548126|d6a32579-7b8f-4c26-9736-203bb2b4245d|
16:20:56||filename.pdf|INST_SYNC|Up|1455575197|56c25a8ebe34c|180874|64425785oc0ba1a88ad3|4||204|0|1455575197|dd473675-fa51-4d72-aaaf-43264a53824d|
...
```
File mtimes and create times from sync log match the timestamps of files stored on server storage backend (and the files in snapshot created just before the client upgrade) and in DB, but they are obviously overwritten, as their change time has been updated to a time of a sync run.

3. Web server error log:
```
No errors were found in web server error log
```

4. Server logfile: ownCloud log (data/owncloud.log) contains just a bunch of NotFoundExceptions when the cron task was trying to expire old versions just around the time when the problematic sync run finished.
```
Nov 23 23:17:01 app ownCloud[10008]: [F6QBVrTejQPDSKN8ZMjY][][--][no app in context][--][--] Exception: {"Exception":"OCP\\Files\\NotFoundException","Message":"filename.xls.v1110632452 not found while trying to get owner","Code":0,"Trace":"#0 \/web\/lib\/private\/Files\/Filesystem.php(961): OC\\Files\\View->getOwner('filename...')\n#1 \/web\/lib\/private\/Preview.php(1241): OC\\Files\\Filesystem::getOwner('filename...')\n#2 \/web\/lib\/private\/legacy\/hook.php(105): OC\\Preview::prepare_delete(Array)\n#3 \/files_versions\/lib\/Storage.php(765): OC_Hook::emit('\\\\OCP\\\\Versions', 'preDelete', Array)\n#4 \/web\/apps\/files_versions\/lib\/Command\/Expire.php(60): OCA\\Files_Versions\\Storage::expire('filename...', 'user@example.com')\n#5 \/web\/lib\/private\/Command\/CommandJob.php(34): OCA\\Files_Versions\\Command\\Expire->handle()\n#6 \/web\/lib\/private\/BackgroundJob\/Job.php(57): OC\\Command\\CommandJob->run('O:33:\"OCA\\\\Files...')\n#7 \/web\/lib\/private\/BackgroundJob\/QueuedJob.php(42): OC\\BackgroundJob\\Job->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#8 \/web\/cron.php(120): OC\\BackgroundJob\\QueuedJob->execute(Object(OC\\BackgroundJob\\JobList), Object(OC\\Log))\n#9 {main}","File":"\/web\/lib\/private\/Files\/View.php","Line":1717}
...
```
5. I was checking with the user if this issue can't be related to an already existing one: https://github.com/owncloud/client/issues/7602, but there is only one syncdb file named `._sync_xxxx(.db-shm|db-wal)?` in the sync directory. Virtual Files feature wasn't enabled on the client.

**Comment by TheOneRing** [comment]
Fixed in 2.9 multiple migration paths where broken...
