### ISSUE TITLE
File fails to upload from client (but OK from web interface)

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#7642]
### Expected behaviour
File should sync correctly after being modified

### Actual behaviour
I have previously added a comment on a [core issue](https://github.com/owncloud/core/issues/31832#issuecomment-558292184) that two specific files fail to synchronize:

1. one file was being rewritten by another application while it was uploading
2. another file was a VeraCrypt container that was open and locked while it was tried to be uploaded

Now I realized that if I update the file through the ownCloud web interface, it is being updated correctly. Only the client keeps trying and trying to upload the file, and each time it fails with the following error message:

`Server hat "500 Internal Server Error" auf "MOVE https://.../remote.php/dav/uploads/johannes/3843534773/.file" geantwortet (Call to a member function getId() on null) (Übersprungen aufgrund des früheren Fehlers, erneuter Versuch in 2 Minuten)`

Even if I modify the file, or if it delete it and then later re-add the same file, the upload keeps failing.

Edit: I also ran a file scan with the repair option, but it didn't fix the problem.

I keep getting desktop notifications about the failed file upload, until I finally upload the current version of the file via the web interface.

### Steps to reproduce
See above.

### Server configuration
Operating system: Debian 10

Web server: nginx 1.14.2

Database: MariaDB 10.3

PHP version: 7.3

ownCloud version: 10.3.1.1

Storage backend (external storage):

### Client configuration
Client version: 2.6.0

Operating system: Windows 10

OS language: German

Installation path of client: default

### Logs

`Server hat "500 Internal Server Error" auf "MOVE https://.../remote.php/dav/uploads/johannes/3843534773/.file" geantwortet (Call to a member function getId() on null) (Übersprungen aufgrund des früheren Fehlers, erneuter Versuch in 2 Minuten)`

2. Web server error log: Empty

3. Server logfile: ownCloud log (data/owncloud.log): Nothing related to this specific file, as far as I can tell.

**Comment by michaelstingl** [comment]
@sagamusix I'd say nothing the desktop sync client can do about "500 Internal Server Error"?

Could you provide detailed "steps to reproduce" and an example file?

**Comment by sagamusix** [comment]
If I replace exactly the same file through the web UI, it works as intended, so I assume the client must be doing something differently during upload. Obviously the actual fault may lie in the server but I cannot judge that. All I can do is observe that this problem only happens with the client.

It all seems to be tied to that specific file location. The file contents don't matter - if I create a duplicate of the file with a different name, that duplicate can be uploaded correctly. However, as soon as I modify the original file again, the client fails to upload the modifications. If I delete the file in its original location, then re-create it the upload succeeds at first but any subsequent updates of the same file name fail again if initiated by the client. Could it be that the client assumes that it should continue a previously cancelled upload, but there is nothing to continue?

**Comment by sagamusix** [comment]
This was a server configuration issue as commented in https://github.com/owncloud/core/issues/31832#issuecomment-565589426
