### ISSUE TITLE
Update qtkeychain to 0.10.0 on Linux

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#7652]
Issue: https://central.owncloud.org/t/xubuntu-keychain-error/22825
https://github.com/frankosterfeld/qtkeychain/releases/tag/v0.10.0

**Comment by jnweiger** [comment]
I'll not create a separate build environment for that. Will update inside  isv\:ownCloud\:Qt5125

This means, rebuilds of 2.6.0 will be built with the new qtkeychain. I assume this is harmless. @TheOneRing correct?

**Comment by jnweiger** [comment]
Updated to v0.10.0  -- rebuilding

* https://build.opensuse.org/package/show/isv:ownCloud:Qt5125/ocqt5125-qt5keychain
* https://obs.int.owncloud.com/package/show/desktop:Qt5125/ocqt5125-qt5keychain

**Comment by jnweiger** [comment]
Dependencies updated. Check out tomorrows nightlies.

**Comment by TheOneRing** [comment]
Was fixed long ago
