### ISSUE TITLE
Owncloud 2.6.0 crash on Win10

### ISSUE THREAD

**Issue by paolodaniele** [owncloud/client#7657]
### Expected behaviour
Syncing all files (using Virtual Drive) about 500k files total

### Actual behaviour
After few minutes and few files owncloud client sto working with no error and close gui

### Server configuration
Operating system: Debian 10 (under KVM VM)

Web server: Apache

Database: MariaDB

PHP version: 7.2.22

ownCloud version: latest stable (10.2.1)

Storage backend (external storage): local storage

### Client configuration
Client version: Latest stable (2.6.0)

Operating system: Windows 10

OS language: ITA

### Logs

1. No error founds in client log files

2. Web server error log: No relevant error founds

3. Server logfile: ownCloud log (data/owncloud.log): No entry

I cas see the ucrtbase.dll error in Windows Event Registry

Strange things happened because other owncloud running same os and same version (but updated from a daily version) works fine. (maybe because when they did the first sync there was few files on server?)

**Comment by michaelstingl** [comment]
Was the crash reporter shown? Could you send the crash ID ?

**Comment by paolodaniele** [comment]
Codice eccezione: 0xc0000409
Offset errore 0x0009e6eb
ID processo che ha generato l'errore: 0x14a4
Ora di avvio dell'applicazione che ha generato l'errore: 0x01d5c18352ea3cc8
Percorso dell'applicazione che ha generato l'errore: C:\Program Files (x86)\ownCloud\owncloud.exe
Percorso del modulo che ha generato l'errore: C:\Windows\System32\ucrtbase.dll
ID segnalazione: 92ea0846-3f89-4d67-8c44-59c6370325ea
Nome completo pacchetto che ha generato l'errore: 
ID applicazione relativo al pacchetto che ha generato l'errore:

Ita language but easy to see the error code. Thanks

**Comment by paolodaniele** [comment]
Sorry for double posting but is there someone who had the same problem and solved in some way? I can confirm that if i'm going to sync single folder, everything works fine and gives no error.
Thanks

**Comment by michaelstingl** [comment]
@TheOneRing Could you have a quick look in the next sprint?

**Comment by michaelstingl** [comment]
@paolodaniele Is this Windows crash reporter window or ownCloud crash reporter window. We didn't find `92ea0846-3f89-4d67-8c44-59c6370325ea` in our systems. Could you post a screenshot of the window?

**Comment by paolodaniele** [comment]
Hi Michael, this is the Windows crash reporter. Owncloud crashes without any message or any window.
If it could be helpful i think is something related to the gui because when we start owncloud again it continues to sync and when the files that it needs to sync are less than 200k (this is an empiric number) sync proceed as usual so in the ends the clients finally sync and not crash anymore.
Regards

**Comment by TheOneRing** [comment]
Hi can you open the about dialogue (context menu of the system tray icon) and copy paste the build info here?
The two last lines from 
![image](https://user-images.githubusercontent.com/200626/72423416-84b6ba80-3784-11ea-98b8-b79e2cc7dd2b.png)

**Comment by paolodaniele** [comment]
Hi,
version is 2.6.0 build 12644.
We've tried with other releases (previously and not) with the same issue. When the number of file to be synced has been decreased everything worked fine. (sorry to not post the screen but i've not in my hand the notebook where i've installed the client)

**Comment by TheOneRing** [comment]
That sound like the 32bit memory limitation, during initial sync the client might consume quite some memory. We are planning to release a x64 installer with 2.7 but might provide a x64 binary zip preview with 2.6.1.

**Comment by paolodaniele** [comment]
thank you. I usually find a way to make things work but i've opened the ticket to help you in your great job and help someone that maybe have the same problem. So if you want you can close the issue.
Thank you :)

**Comment by michaelstingl** [comment]
Will be solved with https://github.com/owncloud/client/issues/7525 (planned for 2.7)
