### ISSUE TITLE
Permit to set the chunk size

### ISSUE THREAD

**Issue by xdmx** [owncloud/client#766]
I've read at #751 that the chunk size is currently about 10 MB and I haven't found any way to change it.

Unfortunately I have a very slow connection on upload and I'm using ownCloud on a shared hosting where I can't change the php timeout nor the maxfilesize settings, because of this I can't upload files bigger than a couple of MB, then the connection goes in timeout.

I'd love the ability to manually lower the default 10MB chunk size to 256-512KB

**Comment by ET-Bent** [comment]
Is there a way of setting the chunk size permanently in the OC Client config file?

Or even better wouldn't it be way more confortable to a add a option in the GUI for this? (I'll open a separate ticket for this in the next days)

**Comment by stevenbuehner** [comment]
@ET-Bent Please refer in your ticket to this post. I'd really would love to see this in GUI. 
Mostly, because I
- don't want to chance the settings every time I do an update
- it is really annouing to explain someone else, what to do
:-)

**Comment by guruz** [comment]
What are your intentions for Setting the chunk size and to which value?
We are thinking of doing Auto scaling of the chunk size based on Network conditions
https://github.com/owncloud/client/issues/4354

**Comment by ET-Bent** [comment]
@guruz okay that would be a good solution, currently using OwnCloud on gigabit ethernet connections internally is hilariously slow. We are talking at about 3.5% of the possible sync speed on large file. In my home setup I was setting the chunk size to about 2 GB to fix this issue and get upload rates of about 60 MB/s (which is reasonable). 

Having a option to easily set the chunk size easily would be beneficial in my opinion as I think that the auto detection will not be working flawlessly / sometimes you want to tinker around and try out different settings.
