### ISSUE TITLE
Account tab: some areas become blue when clicked

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7662]
Windows 10
Client: 2.6.1sprint2 (build 12916)

<img width="724" alt="Screenshot 2020-01-08 at 16 25 29" src="https://user-images.githubusercontent.com/49001702/71990730-3198b100-3234-11ea-97c7-8c54a1473692.png">

<img width="726" alt="Screenshot 2020-01-08 at 16 26 05" src="https://user-images.githubusercontent.com/49001702/71990756-4117fa00-3234-11ea-9d56-5750e10164cd.png">

Actual result: When user clicks next to the `Add folder sync connection` button or next to `ownCloud`, the entire area gets blue

Expected result: No change in color

**Comment by michaelstingl** [comment]
Hehe, related: https://www.youtube.com/watch?v=BinWA0EenDY

**Comment by jnweiger** [comment]
@michaelstingl eiffel65 works as designed :-) thanks for the link. Made my day!

In both cases above it is a container widget that takes focus when clicked. 
In the first case, only the [Add Folder Sync Connection] button within the container should take focus.
In the second case, only the "local folder ownCloud51" and the [...] button within the container should take focus.

**Comment by TheOneRing** [comment]
Is this still happening?

**Comment by HanaGemela** [comment]
Fixed in 2.6.3 (build 13252), macOS 10.15.3
