### ISSUE TITLE
Entries from the Sync Protocol view cannot be opened locally

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7667]
![image](https://user-images.githubusercontent.com/1108546/72147087-1b0e6900-339e-11ea-9a23-461a1828061a.png)
Objects in the "Sync Protocol" tab have a right click menu entry "Open in browser" that navigates to the object in the servers web interface.

![image](https://user-images.githubusercontent.com/1108546/72147492-ed75ef80-339e-11ea-90b6-7dad5b417e16.png)

I suggest to add a second menu entry "Open in local folder" that navigates the desktop file browser to the object, like e.g.:

![image](https://user-images.githubusercontent.com/1108546/72147543-0aaabe00-339f-11ea-9212-414b8affe482.png)

**Comment by jnweiger** [comment]
Use case:

* clicking on an *.html file in the servers web ui most likely display raw html source, or open an office suite.
* clicking on an *.html file in the local desktop most likely shows the contents nicely in a browser.

**Comment by AditiThirdEye** [comment]
Please assign me this issue if PR is not done yet.

**Comment by TheOneRing** [comment]
Fixed in https://github.com/owncloud/client/issues/8528
