### ISSUE TITLE
Renaming folder causes it to be uploaded again

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#7671]
### Expected behaviour
Renaming the folder should essentially be an operation that causes little traffic between client and server: Files should not be re-transmitted

### Actual behaviour
I added a folder (about 120 MB), waited for it to be fully synced, then instantly renamed the folder and it got uploaded again.

### Steps to reproduce
1. Sync a folder
2. Rename it
3. Watch it being uploaded again and old folder being deleted on server afterwards

### Server configuration
Operating system: Debian 10

Web server: nginx 1.14.2

Database: MariaDB 10.3

PHP version: 7.3

ownCloud version: 10.3.2.2

Storage backend (external storage):

### Client configuration
Client version: 2.6.0

Operating system: Windows 10 Professional x64

OS language: German

Installation path of client: Default

**Comment by TheOneRing** [comment]
Fixed in the upcoming 2.7.7
