### ISSUE TITLE
[VFS] Branding name should not influence the placeholder file .owncloud

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#7677]
Placeholder based VFS (user-facing `.owncloud` files) will always be an experimental option. I'd never recommend branding users to enable it for their end users. So, there is no necessity to change the placeholder files with the branding.

**Comment by TheOneRing** [comment]
Removing branded extension at the current point would break testpilot installations.
But we can easily detect wrong placeholder files.
A placeholder file is empty, if a user renames a file to a placeholder file it is not empty.
Files detected as invalid placeholders should cause a sync error.

@ogoffart whats your opinion on this matter

**Comment by michaelstingl** [comment]
> Removing branded extension at the current point would break testpilot installations.

Okay from my pov.

**Comment by TheOneRing** [comment]
> > Removing branded extension at the current point would break testpilot installations.
> 
> Okay from my pov.

Also as the file extension encoded which client has to handle it, it would mean that only the vanilla client would be able to use placeholders...

**Comment by michaelstingl** [comment]
> Also as the file extension encoded which client has to handle it, it would mean that only the vanilla client would be able to use placeholders...

Hm, then better don't do it?

**Comment by TheOneRing** [comment]
Yes maybe rename this issue or create a new one with
"Mark actual files with vfs extension as error" or something like that.

**Comment by ogoffart** [comment]
This vould be just a configuration option from ownbrander.  (It is the APPLICATION_VIRTUALFILE_SUFFIX cmake parameter right now)
It defaults to "owncloud" for owncloud, and to `"${APPLICATION_SHORTNAME}_virtual"` for anything else.  Maybe we should just change the default to "owncloud" ?

But i'd think that those not happy with "xxx_virtual" can still rename it to "xxx" or "owncloud" in ownbrander.

**Comment by TheOneRing** [comment]
But if we always set it to owncloud, what will happen if you have multiple branded versions installed?
I think the idea of disallowing different placeholder file names came up to simplify invalid placeholder file detection, but I don't really think we need that.

**Comment by ogoffart** [comment]
yes that's true. you can't have several branded client installed at the same time in that case.

**Comment by TheOneRing** [comment]
Branded extensions are required for file type asignment
