### ISSUE TITLE
Run the tx.pl scripts

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7679]
@guruz 
@ogoffart 

Please provide all necessary information on how to run the script and what the expected result is

**Comment by ogoffart** [comment]
The instructions are there: https://github.com/owncloud/client/tree/master/test/scripts/txpl

Besically you need perl and some you will need to make sure you have HTTP and Dav.
You need to have an actual server for the test
This was to my knowledge only working on linux.


You would run something like

```
./t1.pl && ./p2.pl && ./t3.pl && [...] && ./t9.pl && echo "OK"
```

And you should see the "OK"
The tests are quite slow to run.

However I must say that these tests are not that great. They haven't been ran for a long time, i don't know if they still pass.
For new tests, we have been using the testing framework which are testing the client with a fake/mock server.

I believe that smashbox tests are also supperior to test things with the real server.

I think most of the actual use case covered by the tx.pl scripts should be covered either by the new tests or by smashbox tests.

**Comment by jnweiger** [comment]
## Testing this against server 10.3.2
```
cd owncloud/client/test/scripts/txpl
git checkout master
git pull

sudo apt-get install libhttp-dav-perl
cat <<EOF>t1.cfg
  user   => "demo",
  passwd => "demo",
  url    => "https://demo.owncloud.org/remote.php/webdav/",
  ld_libpath => "",
  csync => "/usr/bin/owncloudcmd",
  ocs_url => "https://demo.owncloud.org/ocs/v1.php/",
  share_user => "demo1",
  share_passwd => "demo1"
EOF
export PERL_LWP_SSL_VERIFY_HOSTNAME=0
./t1.pl
```

connects to the server, but fails creating a folder there:

```
Hello, this is t1, a tester for csync with ownCloud.
Read config from ./t1.cfg: https://demo.owncloud.org/remote.php/dav/
Connecting to ownCloud at https://demo.owncloud.org/remote.php/dav/
Failed to create test dir https://demo.owncloud.org/remote.php/dav/t1-20200123180716-28/
```

**Comment by ogoffart** [comment]
What's strange is that the config file says `remote.php/webdav/`  but it tries to connect to `remote.php/dav/`

The `dav` endpoins needs some user id i think.

**Comment by HanaGemela** [comment]
@michaelstingl we've just agreed that these tx.pl scripts should be replaced by smashbox/acceptance tests from Domme. Is that OK with you? If so, I'll remove it from the release template and they won't be fixed and run anymore

**Comment by michaelstingl** [comment]
> Is that OK with you?

Yeah, please do so 👍

**Comment by ogoffart** [comment]
These scripts have now been removed.
