### ISSUE TITLE
Investigate the load on the download server after release

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7685]
Reason: Find out if throttling on the online updater can be disabled or what's the value it can be safely set to

Once resolved paste the line below into the release template at the very end
* [ ] QA: Update throttling in the owncloud hosted auto updater

**Comment by guruz** [comment]
it's not primarily about the load, more our cheap way of doing https://developer.apple.com/app-store-connect/whats-new/?id=phased-release-macos

**Comment by ogoffart** [comment]
One problem users complain about is that we don't gradually increase the percentage after a few days, by we "forget" and leave it to 10% only.  Leaving only a very slim changes for users that only seldom open their client to actually have the update.

So the thing with the throttle is that if no critical bugs have been found after, say, one week,  then the throttle should be disabled completely.

**Comment by HanaGemela** [comment]
@tboerger @xoxys can you help here somehow?

**Comment by tboerger** [comment]
We try to put the update server into a git based build process based on docker soon, than you are able to manipulate it within minutes on your own while creating and merging pull requests.

**Comment by TheOneRing** [comment]
We decided against removal of the throttling.
