### ISSUE TITLE
Qt: 5.12.7 update

### ISSUE THREAD

**Issue by guruz** [owncloud/client#7708]
Contains security stuff, maybe for next patch release?

**Comment by TheOneRing** [comment]
Sounds reasonable thx for mentioning.

**Comment by jnweiger** [comment]
Started here https://build.opensuse.org/project/show/isv:ownCloud:Qt5127
Let's see if openSUSE is nice and builds it without much manual patchy-patchy...

**Comment by TheOneRing** [comment]
Done on Windows and Mac.
@jnweiger once the 2.6 builds on linux switched you can close this one.
