### ISSUE TITLE
Crash when closing VFS dialog

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7709]
Windows 10
macOS 10.15.2
client: 2.6.1
server: 10.3.2

Windows crash reports: 40872c65-1a69-4c45-ab06-bc9dfdf2bb16 and 0f4afa5e-513d-425e-9884-d10dbefbba87
macOS: f40ed3d8-51fa-47a2-9207-782d3d988e7f

Steps to recreate:
1) Open Setting dialog -> go to Account tab
2) Click 'Add new' from the Account dropdown
3) Enter Server address
4) Click Next 
5) Enter credentials 
6) Click Next
7) Select virtual files and ignore the dialog to confirm
8) Click Connect without closing the VFS dialog
9) Close the VFS dialog by clicking on the Cross icon

Actual result: Crash
Expected result: Clicking Connect in the step 8 not allowed until VFS dialog is gone

**Comment by jnweiger** [comment]
"Don't press buttons in an unexpected order!" :-)

**Comment by michaelstingl** [comment]
fixed
