### ISSUE TITLE
Closing VFS dialog behaves like confirmation 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7710]
macOS 10.15.2
Windows 10
client 2.6.1

Steps to recreate:
1) Click on Enable (or disable) VFS -> Confirmation dialog will pop up
2) Click the cross icon to close the dialog

Actual result: VFS has been enabled (respectively disabled). 
Expected result: No changes to the files when the dialog has been closed

**Comment by michaelstingl** [comment]
fixed

**Comment by HanaGemela** [comment]
Broken in 2.6.3263_rc1 (build 13516) macOS 10.15.3

Steps to recreate:

1. Click on Disable VFS -> Confirmation dialog will pop up
2. Click the cross icon to close the dialog

**Comment by HanaGemela** [comment]
Still broken in 2.6.3263rc2 (build 13648)

**Comment by TheOneRing** [comment]
![vfs](https://user-images.githubusercontent.com/200626/82817003-78620d00-9e9c-11ea-9335-9579f0f1d4d2.gif)

**Comment by HanaGemela** [comment]
Oh, we have more VFS dialogs :) I'm opening the dialog from the Account tab

**Comment by TheOneRing** [comment]
That should behave the same 😭 I'll see

**Comment by TheOneRing** [comment]
You where talking about the disable vfs dialog?

**Comment by HanaGemela** [comment]
Yes. Enable is correct
