### ISSUE TITLE
VFS dialog can be opened multiple times

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7711]
Windows 10
macOS 10.15.2
client: 2.6.1

Steps to recreate:
1) Click Enable VFS twice

Actual result: Two dialogs have been opened to confirm if VFS should be turned on. It is very confusing what should happen if user selects 'Stay safe' in one and enables VFS in the second one
Expected result: Only one dialog can be opened

**Comment by michaelstingl** [comment]
fixed
