### ISSUE TITLE
[VFS] Moving of files in 'online only' folders on external SMB storage leads to file ignoring

### ISSUE THREAD

**Issue by lex2k0** [owncloud/client#7713]
### Expected behaviour
The moval of a file is recognized correctly and the file is moved to the new folder

### Actual behaviour
The moval is not recognized correctly. The file in the source folder is deleted and inside the new folder the file is ignored.

### Steps to reproduce
1. Add an external SMB storage on a NAS or somewhere else
2. Add the synchronization of that folder in the owncloud client using VFS, keeping the files online only
3. Navigate in a subfolder and select a file which is only available online
4. Move that file to another folder
5. Look into the synchronization protocol of the client. You should see that the file got deleted and in the new folder it is ignored.

### Server configuration
Operating system:
Docker
Web server: 
Apache
Database:
mariaDB
PHP version:
something with 7
ownCloud version:
10.3.2
Storage backend (external storage):
qnap NAS
### Client configuration
Client version:
2.6.0
Operating system:
Windows 10
OS language:
German
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
C:\Program Files (x86)\ownCloud

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/client/issues/7714
