### ISSUE TITLE
[VFS] Moving of virtual files that are on external storage is broken

### ISSUE THREAD

**Issue by lex2k0** [owncloud/client#7714]
### Expected behaviour
The moval of a file is recognized correctly and the file is moved to the new folder

### Actual behaviour
The moval is not recognized correctly. The file is recognized correctly and gets moved to the new folder. But after that the file gets created again as virtual file in the initial source folder. Thus the file gets duplicated.

### Steps to reproduce
1. Add an external Dropbox storage
2. Add the synchronization of that folder in the owncloud client using VFS, keeping the files online only
3. Navigate in a subfolder and select a file which is only available online
4. Move that file to another folder
5. Look into the synchronization protocol of the client. You should see that the file got moved and after that directly recreated in the source folder.

### Server configuration
Operating system:
Docker
Web server: 
Apache
Database:
mariaDB
PHP version:
something with 7
ownCloud version:
10.3.2
Storage backend (external storage):
qnap NAS
### Client configuration
Client version:
2.6.0
Operating system:
Windows 10
OS language:
German
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
C:\Program Files (x86)\ownCloud

**Comment by HanaGemela** [comment]
I can easily reproduce on macOS 10.15.3, client 2.6.1 (build 13096) and Windows 10, client 2.6.1 (build 12992). Get in touch if test system needed, I can provide mine

**Comment by TheOneRing** [comment]
@HanaGemela is it a Windows vfs issue or does it happen with suffx/normal files too?

**Comment by michaelstingl** [comment]
@TheOneRing reported with Win10, but @HanaGemela reproduced it with macOS too

**Comment by michaelstingl** [comment]
Same behaviour with external SMB storage (https://github.com/owncloud/client/issues/7713)

**Comment by lex2k0** [comment]
@michaelstingl: Its fine for me to close #7713 as both problems are relating to an external storage behavior.
But I would be thankful if both reported issues are fixed and tested in the end, because in this issue the file gets moved corretly but also duplicated on the inital folder and for #7713 nothing is correct. the source file gets deleted but in the new folder it doesn't get synchronized as the file is ignored (visible in the log) somehow.

**Comment by michaelstingl** [comment]
Needs testing again after https://github.com/owncloud/client/issues/7799 is fixed.

**Comment by TheOneRing** [comment]
Does it still happen?
