### ISSUE TITLE
Tray icon shows exclamation mark while happily syncing

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7715]
Seen with 2.6.1 on Ubuntu 18.04:

![image](https://user-images.githubusercontent.com/1108546/73617742-41809680-4622-11ea-8e0a-7379a800422c.png)

There are two servers connected, one is syncing, the other one is waiting.
The tray-icon shows an exclamation mark. It should show the sync circle.

The mouse over help text says both are waiting. That is incorrect.

**Comment by TheOneRing** [comment]
Can you still reproduce the issue?
