### ISSUE TITLE
owncloud-client upgrade fails when using openSUSE Build Service repos

### ISSUE THREAD

**Issue by enbrnz** [owncloud/client#7723]
I have the daily build repository on my Ubuntu 19.10 workstation:
```
cat /etc/apt/sources.list.d/isv\:ownCloud\:desktop\:testing.list
deb http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot/Ubuntu_19.10/ /
```

### Problem
I tried to update to the latest version today (05.02.2020), and I received the following error message
```
The following package was automatically installed and is no longer required:
  ocqt5125-libsqlite0
Use 'apt autoremove' to remove it.
The following NEW packages will be installed:
  ocqt5125-libsqlite0-dev
[...]
Selecting previously unselected package ocqt5125-libsqlite0-dev:amd64.
Preparing to unpack .../2-ocqt5125-libsqlite0-dev_3.29.0-1+1.1_amd64.deb ...
Unpacking ocqt5125-libsqlite0-dev:amd64 (3.29.0-1+1.1) ...
dpkg: error processing archive /tmp/apt-dpkg-install-puK2hM/2-ocqt5125-libsqlite0-dev_3.29.0-1+1.1_amd64.deb (--unpack):
 trying to overwrite '/opt/ownCloud/qt-5.12.5/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6', which is also in package ocqt5125-libsqlite0:amd64 3.29.0-1+11.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
[...]
Errors were encountered while processing:
 /tmp/apt-dpkg-install-puK2hM/2-ocqt5125-libsqlite0-dev_3.29.0-1+1.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
### Expected behaviour
1. `owncloud-client` shouldn't depend on `*-dev`-packages:
```
apt-cache show owncloud-client
Package: owncloud-client
Version: 2.6.2~daily20200205+oc-2101
Architecture: amd64
[...]
ocqt5125-libsqlite0-dev
```
2. Also `*-dev`-packages shouldn't generate conflicts with the `*non-dev`-package
```
apt --fix-broken install
[...]
Unpacking ocqt5125-libsqlite0-dev:amd64 (3.29.0-1+1.1) ...
dpkg: error processing archive /var/cache/apt/archives/ocqt5125-libsqlite0-dev_3.29.0-1+1.1_amd64.deb (--unpack):
 trying to overwrite '/opt/ownCloud/qt-5.12.5/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6', which is also in package ocqt5125-libsqlite0:amd64 3.29.0-1+11.1
dpkg-deb: error: paste subprocess was killed by signal (Broken pipe)
Errors were encountered while processing:
 /var/cache/apt/archives/ocqt5125-libsqlite0-dev_3.29.0-1+1.1_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
### Steps to reproduce
1. Install owncloud-client from isv:ownCloud:desktop project
2. Change repo to testpilotcloud-client from isv:ownCloud:testpilot project
3. Install `testpilotcloud-client-l10n`

### Client configuration
Client version: 2.6.2 daily build

Operating system: Ubuntu 19.10

OS language: English

**Comment by jnweiger** [comment]
This is not about daily master, this is released versions.

**Comment by jnweiger** [comment]
I can confirm that testpilotcloud-client from http://download.opensuse.org/repositories/isv:/ownCloud:/testpilot depends on ocqt5125-libsqlite0-dev instead of ocqt5125-libsqlite0.

But installing both `sudo apt-get install ocqt5125-sqlite3 ocqt5125-libsqlite0-dev` works without conflict for me.

**Comment by jnweiger** [comment]
The 2.6.2 (build 2101) must have been from 

`deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop:/daily:/2.6/Ubuntu_19.10/ /`
Installing owncloud-client from there also pulls in `ocqt5125-libsqlite0-dev` -- that is bug. But pretty harmless on its own.

@enbrnz Where do you see a dependency on ocqt5125-libsqlite0 ? All I can see is ocqt5125-sqlite3

**Comment by jnweiger** [comment]
dpkg -L ocqt5125-libsqlite0-dev
/.
/opt
/opt/ownCloud
/opt/ownCloud/qt-5.12.5
/opt/ownCloud/qt-5.12.5/include
/opt/ownCloud/qt-5.12.5/include/sqlite3.h
/opt/ownCloud/qt-5.12.5/include/sqlite3ext.h
/opt/ownCloud/qt-5.12.5/lib
/opt/ownCloud/qt-5.12.5/lib/x86_64-linux-gnu
/opt/ownCloud/qt-5.12.5/lib/x86_64-linux-gnu/libsqlite3.la
/opt/ownCloud/qt-5.12.5/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
/opt/ownCloud/qt-5.12.5/lib/x86_64-linux-gnu/pkgconfig
/opt/ownCloud/qt-5.12.5/lib/x86_64-linux-gnu/pkgconfig/sqlite3.pc
/usr
/usr/share
/usr/share/doc
/usr/share/doc/ocqt5125-libsqlite0-dev
/usr/share/doc/ocqt5125-libsqlite0-dev/changelog.Debian.gz
/opt/ownCloud/qt-5.12.5/lib/x86_64-linux-gnu/libsqlite3.so
/opt/ownCloud/qt-5.12.5/lib/x86_64-linux-gnu/libsqlite3.so.0


dpkg -L ocqt5125-sqlite3       
/.
/usr
/usr/share
/usr/share/doc
/usr/share/doc/ocqt5125-sqlite3
/usr/share/doc/ocqt5125-sqlite3/changelog.Debian.gz

dpkg -L ocqt5125-libsqlite0    
/.
/opt
/opt/ownCloud
/opt/ownCloud/qt-5.12.5
/opt/ownCloud/qt-5.12.5/lib
/opt/ownCloud/qt-5.12.5/lib/x86_64-linux-gnu
/opt/ownCloud/qt-5.12.5/lib/x86_64-linux-gnu/libsqlite3.so.0.8.6
/usr
/usr/share
/usr/share/doc
/usr/share/doc/ocqt5125-libsqlite0
/usr/share/doc/ocqt5125-libsqlite0/changelog.Debian.gz
/opt/ownCloud/qt-5.12.5/lib/x86_64-linux-gnu/libsqlite3.so
/opt/ownCloud/qt-5.12.5/lib/x86_64-linux-gnu/libsqlite3.so.0

**Comment by enbrnz** [comment]
> But installing both `sudo apt-get install ocqt5125-sqlite3 ocqt5125-libsqlite0-dev` works without conflict for me.

I had trouble installing `ocqt5125-libsqlite0` and `ocqt5125-libsqlite0-dev` at the same time.

> Where do you see a dependency on ocqt5125-libsqlite0 ?
I think `owncloud-client` from `deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_19.10/ /` has one, because...

> ### Steps to reproduce
> 
>     1. Install owncloud-client from isv:ownCloud:desktop project
> 
>     2. Change repo to testpilotcloud-client from isv:ownCloud:testpilot project
> 
>     3. Install `testpilotcloud-client-l10n`

..., because I was able to do this in a Ubuntu 19.10 docker container.

**Comment by enbrnz** [comment]
Workaround:
`dpkg -i --force-overwrite /var/cache/apt/archives/ocqt5125-libsqlite0-dev_3.29.0-1+1.1_amd64.deb`

**Comment by jnweiger** [comment]
Next daily should bring you version 3.29.0-**2**... of our sqlite3 packages with a fix.
I have a hard time finding out, how OBS decides if the dev package (wrong) or the non-dev package (correct) should become the runtime dependency. With the fix, it should not matter anymore.

https://build.opensuse.org/package/rdiff/isv:ownCloud:Qt5125/ocqt5125-sqlite3?linkrev=base&rev=2&expand=1

**Comment by Trebacz** [comment]
> dpkg -i --force-overwrite /var/cache/apt/archives/ocqt5125-libsqlite0-dev_3.29.0-1+1.1_amd64.deb

This forcing worked for me - Thanks.
