### ISSUE TITLE
Wrong PROPFIND when adding a new sync folder pair

### ISSUE THREAD

**Issue by labkode** [owncloud/client#7724]
When adding a new sync folder pair I copy and paste the path I want to sync however the sync client will issue a PROPFIND to a parent node which I don't have access and it fails.

I only have access to the given path and not to the whole parent nodes.

<img width="912" alt="Screenshot 2020-02-06 at 06 06 14" src="https://user-images.githubusercontent.com/5175912/73907635-60dc2580-48a7-11ea-9bb7-27c6be97a3c2.png">

Can we avoid the sync client to trigger such PROPFIND and only do it on the node that is given (/eos/user/e/xxx/Picture/BMW) ?

The client is the CERNBox branded client, the problem happens since at least version 2.4.3.

**Comment by ogoffart** [comment]
The problem here is that the client does request as one type in order to open the tree.
The warning is valid: it could not open the tree because of one 403 error.

Should we just not show the warning?  Or should there be another wording?

@michaelstingl what's your opinion ?

**Comment by labkode** [comment]
@ogoffart after pasting the path the propfind to parent should not happen. I understand the if you browser the three yes and you need to discover the paths (which you don't have access).

So, this message should not be there in the first place.

**Comment by ogoffart** [comment]
When you paste a path, it will still try to open the tree to select the pasted path in the UI.

**Comment by labkode** [comment]
yes, however the tree is opened in the UI even though you don't have the permissions.

In the example:

```
/eos/user/e/xxx/Picture/BMW
```

the sync client only triggers one PROPFIND that fails with 403 to /eos/user/e/xxx/Picture, and not the other parent directories (/eos, /eos/user, /eos/user/e/, /eos/user/e/xxx/).

**Comment by ogoffart** [comment]
I think it probably does, but only show one warning.

**Comment by labkode** [comment]
@ogoffart you're right, it does. Can we make the sync client trigger the propfind only for the last element of the path ?

**Comment by TheOneRing** [comment]
@labkode I guess on a normal setup we would want to display the whole tree.
I guess a better solution would be to have a less prominent error, mark the folder in the tree red and provide the error in the tooltip.
Only display the error that prominent on the final folder.

**Comment by jnweiger** [comment]
@iHerrmann77 tried to reproduce, got a crash, Screenshot from 2020-10-21 11-42-18

![image](https://user-images.githubusercontent.com/1108546/96702927-8c019900-1392-11eb-9e3c-94fac458a173.png)

Hmm.
