### ISSUE TITLE
Can't log back in after logging out while waiting 

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7728]
Client: 2.6.1
macOS 10.15.3
Server: 10.3.2

Steps to recreate:
1) Turn on VFS
2) Move a file into a folder
3) Repeat the previous step with other files and different folders as quick as possible at least 10 times
4) When the client shows blue spinning wheel icon (=waiting) but actually there is no progress shown, log out
5) Log back in

Can't recreate

Actual result: Nothing
`02-06 14:37:20:514 [ warning gui.account.state ]:	ConnectionValidator already running, ignoring "localhost:8080 (admin)"`
Logs shared 

Expected result: User has been logged in

**Comment by TheOneRing** [comment]
I'd need a full log including debug information

**Comment by michaelstingl** [comment]
Close for now. @HanaGemela Next time this happens, please capture some logs.
