### ISSUE TITLE
2.6.1 on Ubuntu 18.04 fails to load vfs extension

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7729]
![image](https://user-images.githubusercontent.com/1108546/73947587-fbfceb80-48f7-11ea-9766-8a9395631460.png)

It should say vfs plugin: suffix

The plugin is installed as `/opt/ownCloud/ownCloud/lib/x86_64-linux-gnu/ownCloud/plugins/owncloudsync_vfs_suffix.so` but does not seem to get loaded.

**Comment by jnweiger** [comment]
Instead a file that happens to be in my homedirectory gets loaded:
`-rw-r--r-- 1 testy testy 26776 Oct 31 15:44 owncloudsync_vfs_suffix.so`

and it does not work. Didn't we fix that long ago?

**Comment by ogoffart** [comment]
It was fixed in Qt 5.14.0
(The fix will also be in  Qt 5.12.7)

**Comment by jnweiger** [comment]
Yeay! looking forward to 5.12.7 ! 

Refernence: https://github.com/owncloud/client/issues/7567

**Comment by michaelstingl** [comment]
Qt 5.12.7 update: https://github.com/owncloud/client/issues/7708
/cc @TheOneRing

**Comment by michaelstingl** [comment]
Will be fixed with #7708 in 2.6.2
