### ISSUE TITLE
client startup aborts with coredump when it cannot connect to display

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7731]
The desktop client cannot work without a display connection. That is fine. 

But without a display connection, it should exit with a proper error message. 
Currently it creashes:
```
root@24053c37673b:/# testpilotcloud             
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: linuxfb, minimal, offscreen, vnc, xcb.

Aborted (core dumped)
root@24053c37673b:/#     
```

**Comment by ogoffart** [comment]
That's what Qt do, we have no way to control that in owncloud itself.
If anything, we would need to change Qt itself.

**Comment by TheOneRing** [comment]
Yes we require a ui session, you can use xvfb to run the client in a headless mode.
