### ISSUE TITLE
Add Folder Sync Connection sometimes does not warn

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7741]
The GUI has a prominent button `Add Folder Sync Connection` (that should never be used IMHO).

If the user adds a second Folder Sync Connection, he normally gets a warning, 
![image](https://user-images.githubusercontent.com/1108546/74364789-21449a80-4dcd-11ea-90d2-22bb6c325b4a.png)
This warning is good, as there is no option to **replace** the '/' connection with another one. So every second connection is an overlap.
After accepting the warning, the connection is created, and the selected subfolder is synced outside of the main tree again.

The user can now delete the original Folder Sync Connection
![image](https://user-images.githubusercontent.com/1108546/74365157-c9f2fa00-4dcd-11ea-8353-655be60156c7.png)

... and recreate a sync connection for the parent folder:

![image](https://user-images.githubusercontent.com/1108546/74365238-eee76d00-4dcd-11ea-9cc4-86a0155e1e38.png)

This time, it is again an overlap, but no narning is shown.
The warning should be shown in both cases.

**Comment by TheOneRing** [comment]
The issue is part of the changelog and will be tested in the qa process, reopen if the issue was not fixed.

**Comment by jnweiger** [comment]
### confirmed fixed in 2.7.0 rc3

The expected `Warning: You are already syncing /Photos/, which is a subfolder of /.` is shown.
