### ISSUE TITLE
Branding does not include version info in about dialog

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#7749]
Improve version info, (related to https://github.com/owncloud/client/issues/7704) and ensure it is displayed in about, independent of branding.

**Comment by jnweiger** [comment]
I belive, this works as designed. @cdamken has ticked this option in his branded version:
![image](https://user-images.githubusercontent.com/1108546/74766360-7bd66e80-5285-11ea-9fd1-5ba1299f07cd.png)
