### ISSUE TITLE
Branded clients should not show experimental options

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7756]
Only "ownCloud" and "testpilotcloud" should show experimental features.

We already have a config setting showExperimentalOptions=false, which is used in two places

    in the wizard to advertise vfs or not.
    in theme.cpp as a default in showVirtualFilesOption()

Both cases don't cover what we need here. showExperimentalOptions seems to be a misnomer. It is rather a showVirtualFilesOption only.

**Comment by jnweiger** [comment]
quick'n'dirty fix: https://github.com/owncloud/client/pull/7754

**Comment by TheOneRing** [comment]
Duplicate of #7756

**Comment by jnweiger** [comment]
Actually a duplicate of #7755 -- sorry for the confusion.
