### ISSUE TITLE
Possible crash in Windows VFS when a file is marked as "Always keep on this device"

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#7761]
As discussed in https://talk.owncloud.com/group/desktop-wincfapi?msg=HBPXt7HaetBjhzcDx use the correct handle type to mark a file as pinned (CfSetPinState)

The issue only occurs on some Windows installations but there 100% of the time.

2504ee06d8989be4b5a8ff51ab886f036535fabe

**Comment by HanaGemela** [comment]
@TheOneRing please provide steps to test
