### ISSUE TITLE
Xubuntu 19.10 - Dark Tray Icon Missing

### ISSUE THREAD

**Issue by vexillia** [owncloud/client#7780]
## Expected behaviour
When switching on monochrome icons, with a light theme, client icon should show a dark icon against the light panel background.

### Actual behaviour
Icon shows a light icon on a light background.  Icon works OK.  Switching to a dark panel background shows same icon but of course it's much more visible.

### Steps to reproduce
1. Install 2.6.1 via PPA
2. Start client.
3. Switch to monochrome icon

### Client configuration
Client version: 2.6.1
Operating system: Xubuntu 19.10
OS language: English (UK)
Client package (From ownCloud or distro) (Linux only): ownCloud PPA

**Comment by michaelstingl** [comment]
> * Install 2.6.1 via PPA

Could you please verify with the official ownCloud Linux clients?
https://owncloud.org/download/#owncloud-desktop-client-linux

**Comment by vexillia** [comment]
It was the official Linux client for Ubuntu 19.10 from the link you provided.

**Comment by TheOneRing** [comment]
@vexillia are you able to reproduce the issue with 2.7.6?

**Comment by vexillia** [comment]
I gave up using owncloud after repeated broken upgrades.  Can help any further.
