### ISSUE TITLE
detailed steps for build

### ISSUE THREAD

**Issue by sachinbanugariya** [owncloud/client#7781]
hello,

i tried to build/compile the owncloud client from here:
https://doc.owncloud.org/desktop/2.5/building.html.

but somehow something goes wrong and getting error for linux build and for windows build not getting what we have to do from steps.

can you please give us the detailed doc for build the client on linux and windows with proeper version.

thanks

**Comment by michaelstingl** [comment]
@sachinbanugariya this is the issue tracker of the ownCloud desktop sync client, not a help forum. Please use https://central.owncloud.org/ instead. Please provide the detailed commands and all terminal output there…
