### ISSUE TITLE
sockets in /tmp/ are not removed when stopped with SIGKILL or SIGINT (CTRL-C)

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7787]
Seen on Ubuntu 18.04:

```
$ owncloud --version
ownCloud version 2.6.1 (build 2071)
$ owncloud &
[1] 971
$ lsof -p 971 | grep /tmp/
owncloud 971 testy    8uW     REG              259,5        0    664586 /tmp/qtsingleapplication-ebfc-3e8-lockfile
owncloud 971 testy    9u     unix 0x0000000000000000      0t0  10167881 /tmp/qtsingleapplication-ebfc-3e8 type=STREAM
$ ls /tmp/qtsingleapplication-* | wc -l
30
$ kill -SIGINT 971
[1]+  Killed                  owncloud
ls /tmp/qtsingleapplication-* | wc -l
30
$ ls -la /tmp/*ebfc*
srwxr-xr-x 1 testy testy 0 Mar  5 13:23 /tmp/qtsingleapplication-ebfc-3e8
-rw-r--r-- 1 testy testy 0 Mar  5 13:23 /tmp/qtsingleapplication-ebfc-3e8-lockfile
```

Expected result: The socket should be removed during atexit() handler or similar.
the file count in the ls command above should go down from 30 to 28.

**Comment by jnweiger** [comment]
Same happens at logout / login, when the owncloud-client is in autostart mode.

My socket count increases. I'd assume the system sends SIGKILL then.

**Comment by ogoffart** [comment]
These files are internal details of the QtSingleApplication.
Note that despite being in 3rdparty, this is a for done many years ago as there is no real maintained upstream.
We could try to install a signal handler to clear them. but i think this this is quite low priority.
These files get removed if the client is started again.

**Comment by TheOneRing** [comment]
Out of scope
