### ISSUE TITLE
Network Disabled

### ISSUE THREAD

**Issue by nigelhorne** [owncloud/client#7788]
This seems to have been reported a number of times and closed, but with no real solution.  It is still occurring:

owncloudcmd version 2.2.4

owncloudcmd --exclude /dev/null  -u xxx -p xxxx --non-interactive ~/ownCloud http://xxx.com

ith read_from_db 0
[03/05 09:17:33.054695, 8] csync_update:  Update detection for local replica took 0.00 seconds walking 0 files.
[03/05 09:17:33.054813, 7] csync_memstat_check:  Memory: 295104K total size, 25512K resident, 19636K shared
[03/05 09:17:33.054885, 4] csync_ftw:  URI without fuzz for ownclouds://nigelhorne.force9.co.uk/owncloud/remote.php/webdav is ""
OCC::DiscoveryJob(0xaaab02d7ce00)  Calling into main thread...
!!! OCC::LsColJob created for "xxxxx/" + "" "OCC::DiscoverySingleDirectoryJob"
void OCC::AbstractNetworkJob::slotFinished() QNetworkReply::NetworkError(UnknownNetworkError) "Network access is disabled." QVariant(Invalid)
void OCC::DiscoverySingleDirectoryJob::lsJobFinishedWithErrorSlot(QNetworkReply*) "Network access is disabled." 0 QNetworkReply::NetworkError(UnknownNetworkError)
void OCC::DiscoveryMainThread::singleDirectoryJobFinishedWithErrorSlot(int, const QString&) 5 "Network access is disabled."
OCC::DiscoveryJob(0xaaab02d7ce00)  ...Returned from main thread
5 when opening  msg= "Network access is disabled."
[03/05 09:17:33.056621, 4] csync_ftw:  opendir failed for ownclouds://xxxxx/remote.php/webdav - errno 5
[03/05 09:17:33.057090, 6] csync_statedb_close:  sqlite3_close=0
 #### ERROR during  csync_update :  "An error occurred while opening a folder Network access is disabled."
void OCC::SyncJournalDb::close() "/home/njh/ownCloud/.csync_journal.db"
No database Transaction to commit
CSync run took  7
void OCC::SyncEngine::abort() QObject(0x0)
void OCC::SyncJournalDb::close() "/home/njh/ownCloud/.csync_journal.db"
No database Transaction to commit

**Comment by michaelstingl** [comment]
> owncloudcmd version 2.2.4

Please test with the current 2.6.1 and provide the detailed steps to reproduce.

**Comment by nigelhorne** [comment]
'apt update' says I have the latest version.  When will 2.6.1 be pushed out to the repos?

**Comment by ogoffart** [comment]
> Network access is disabled.

That's because of bug the Qt bearer plugin.
The plugin should be deleted. 
I'm pretty sure this is fixed if Qt and the client get upgraded.

We have no control in when the client gets updated in your distribution, but you should download the client following the instruction there https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client
