### ISSUE TITLE
Missing file change right on server causes client to crash

### ISSUE THREAD

**Issue by faltin** [owncloud/client#7791]
### Expected behaviour
The client should warn the user that he does not have all needed access right on the server to synchronise 

### Actual behaviour
Client crashes and asks to send a crash report to the developers

### Steps to reproduce
1. Create a repository on the Owncloud server
2. Assign a user, let us call him U to the repository but only give U the right to upload and download, not the right to delete or rename files
3. U sets up the desktop client and synchronises with the repository
4. U moves a file on his local filesystem to another directory
5. When client tries to synchronise it can not move the file and crashes (as described above)

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version: Windows client, 2.6.1 (build 12992)

Operating system: Windows 10

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by michaelstingl** [comment]
@faltin please post the crash ID that was shown in the crash report window.

**Comment by faltin** [comment]
The Client asked me whether I wanted to send the crash report, an i pressed YES button. I did not note the crash ID. I now received the needed change rights on the server, and it now works fine for me, so I can not reproduce it either.

**Comment by TheOneRing** [comment]
@faltin thanks for the report, the issue should now be fixed with 2.7 https://github.com/owncloud/client/issues/8066 if the issue still exists please reopen this issue.
