### ISSUE TITLE
2.6.3/2.7.0: CentOS: client shown GUI on first start

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7802]
The ownCloud client is **not** running.
When starting `owncloud` from a shell, ~~or clicking the app-icon on the desktop,~~ the ownCloud client starts and opens the GUI.

Expected behaviour:
When starting `owncloud` from a shell, ~~or clicking the app-icon on the desktop,~~ the ownCloud client starts **without** showing the GUI.
This expected behaviour is seen with 2.6.3 and 2.7.0 on Ubuntu_18.04 and was discussed in https://github.com/owncloud/client/issues/7775 and https://github.com/owncloud/client/issues/7018

**Comment by jnweiger** [comment]
This is a gnome-3.28 desktop without tray icons. A desktop app-icon is not automatically installed. 
I found the icon by searching for owncloud, then right click on the icon and add to favourites, so that I can use it for starting.

**Comment by TheOneRing** [comment]
@jnweiger that is exactly what we changed last week. You even approved the review...

**Comment by jnweiger** [comment]
No, I don't think so. What we discussed and approved last week was
* `owncloud` without parameters -> the client starts without GUI
* `owncloud --showsettings` -> the client starts with GUI

I see exactly this on Ubuntu.
But in CentOS the client behaves as if it were always run with `--showsettings`

I did a stupid copy paste above. When clicking the icon is not relevant. I have not checked, if the Exec line in the desktop icon has the `--showsettings` parameter or not.
Please ignore that part. This issue is about starting from the shell (or autostart).

**Comment by TheOneRing** [comment]
I'd say its expected to happen see https://github.com/owncloud/client/blob/master/src/gui/main.cpp#L154

Also on ubuntu, I just got `ubuntu:gnome` in my setup.
