### ISSUE TITLE
Bug: OwncloudSetupPage::slotUrlChanged always uses old endpoint

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#7840]
https://github.com/owncloud/client/blob/59152a890aa01aadb3165abac19f7e6c66358753/src/gui/wizard/owncloudsetuppage.cpp#L115

account()->davPath() requires capabilities but we don't query any capabilities.....

**Comment by michaelstingl** [comment]
@TheOneRing this is a branding option we have.

**Comment by TheOneRing** [comment]
davPath() either returns the old dav path or the new one.
As at that point no capabilities are set, at least not with a normal setup, this always returns the old entry point.

**Comment by TheOneRing** [comment]
Won't fix as long as we need to support all old upload protocols
