### ISSUE TITLE
OwnCloud not downloading files that Google Drive says is a virus

### ISSUE THREAD

**Issue by voarsh2** [owncloud/client#7841]
ownCloud version: 10.4.0.4
Client version: 2.6.1
Operating system: Windows 10
OS language: English

It would appear that OwnCloud Desktop client doesn't download files that Google Drive says is a virus.
This is either intended behaviour of OwnCloud, or there isn't a condition in the client to accept Google's different response.

E.G. On the browser if I download the file that failed on the client, I get this from Google: https://central.owncloud.org/uploads/db1708/original/2X/d/d4120a938f459a7b174527c378d18f176b29dc6f.png
Perhaps the client can't handle this properly?

I know for a fact that this is a false positive, and I have my own antivirus, so I need OwnCloud to handle this properly and still download the file.

**Comment by michaelstingl** [comment]
Not a client issue. (Check my comment https://central.owncloud.org/t/owncloud-not-downloading-files-that-google-drive-says-is-a-virus/25500/6)
