### ISSUE TITLE
Owncloud client crash after rewrite file attempt

### ISSUE THREAD

**Issue by paolodaniele** [owncloud/client#7842]
Expected behaviour

Actual behaviour

User with no delete permission try to copy a file from desktop to owncloud folder but owncloud client crash instead of sending error message
History:
few days ago an owncloud client started to delete files (not folder) from the first subdirectory in order.
To avoid problem, after backup restore, we deny delete from all users.
This cause random crash of owncloud client when users try to replace a file inside a directory or rename a file.
After 3-4 cases we've found that is related to our deny policy.
My 2 question:
- Is it possible to simply show an error message instead of crash all client? Because in this way i've to resync all customer's folders.
- In what condition a client start to delete all file from folders? example

-Folder
---SubFolder
-----FileD.xx
-----FileE.xx
-----SubSubFolder
-------FileA.xx
-------FileB.xx 

All file were deleted but subfolders remains.
I know that are 2 different issue but are strictly related. (also no log on server only the webdav delete command from the user)

Server configuration

Operating system: Debian 10 (under KVM VM)

Web server: Apache

Database: MariaDB

PHP version: 7.2.22

ownCloud version: latest stable (10.2.1)

Storage backend (external storage): local storage
Client configuration

Client version: Latest Stable (2.5.4) (but other version too like the last daily)

Operating system: Windows 10

OS language: ITA
Logs

    No error founds in client log files

    Web server error log: No relevant error founds

    Server logfile: ownCloud log (data/owncloud.log): No entry

**Comment by michaelstingl** [comment]
@paolodaniele please post the crash ID that is shown in the crash reporter window.

**Comment by paolodaniele** [comment]
@michaelstingl i'd like to do but in the crash report windows it says only this:
![Immagine](https://user-images.githubusercontent.com/20563026/79373554-0a4e3000-7f57-11ea-94ad-2294c1c29be2.gif)

**Comment by michaelstingl** [comment]
You need to send the report, You'll get the ID on the next screen.

**Comment by paolodaniele** [comment]
sorry but customers take the screenshot and then close the screen before ticket ID appear. So if you don't have more information please close the issue and apologize me.

**Comment by paolodaniele** [comment]
Sent! Many thanks. Please refer to crash f04f304f-651d-4b56-a306-228551fdc233 in bug reports.

**Comment by michaelstingl** [comment]
@paolodaniele we think it should be fixed in the 2.6.3 pre-release builds. Could you give it a try?
https://download.owncloud.com/desktop/daily/ownCloud-2.6.3.13748.13350-daily20200409.msi

**Comment by michaelstingl** [comment]
@paolodaniele can you confirm it's fixed in the 2.6.3 pre-release builds?

**Comment by paolodaniele** [comment]
@michaelstingl nope. I've tried few things before writing. But no, that version do not fix the problem. The only thing i've done to fix it was restore the original permissions (also delete) to all users.

**Comment by michaelstingl** [comment]
> But no, that version do not fix the problem.

Thanks for the feedback. We'll have another look…

**Comment by michaelstingl** [comment]
We’re very, very confident it’s fixed with the final 2.6.3. In case it crashes again, please reopen and also send the new crash ID.
