### ISSUE TITLE
Owncloud crases at startup macOS Catalina

### ISSUE THREAD

**Issue by dnscosta** [owncloud/client#7845]
### Expected behaviour
The app shouldn't crash ;)

### Actual behaviour
Owncloud crashes at startup

### Steps to reproduce
1. Start the app.
2. App crashes within seconds. I can hardly open the settings window. 

### Server configuration
Operating system: 

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version: Owncloud 2.6.1

Operating system: macOS Catalina 10.15.3

OS language: English

Installation path of client:

### Logs

owncloud crash report 71eebd9b-c7c5-4bb5-812e-c2f450112a4b

```Template for output < 10 lines```

1. Client logfile:  

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by romix123** [comment]
Crashes on my system too (and so does Owncloud derivate Surfdrive)
OS Version:            Mac OS X 10.15.4 (19E287)
bug report 89351f6d-8d08-4064-ac29-d7408ba78701.

**Comment by michaelstingl** [comment]
@romix123 2.6.2 from [SURF download page](https://www.surf.nl/en/store-and-share-your-files-securely-in-the-cloud-with-surfdrive/downloads-for-surfdrive) ?

**Comment by TheOneRing** [comment]
@romix123 You where experiencing a different issue, which should be fixed in the upcoming release.
See https://github.com/owncloud/client/issues/7878

**Comment by TheOneRing** [comment]
The original crash id here is fixed in 2.6.3 see https://github.com/owncloud/client/commit/a359baec4376cb508075b48307a48b8d82d5dcd3
