### ISSUE TITLE
Desktop client should disable chunking if bigfilechunking capability is false

### ISSUE THREAD

**Issue by PVince81** [owncloud/client#7849]
See related https://github.com/owncloud/ocis/issues/195

Whenever the capability "bigfilechunking" is set to false, the desktop client must not attempt to use the chunking v1 algorithm (this one https://github.com/owncloud/client/blob/f076682a8c7b1a425131fcb5eae2dfbc4febfac5/src/libsync/propagateuploadv1.cpp#L104)

the capability attribute is in:
```
"ocs": {
    "data": {
      ...
      "capabilities": {
        ...
        "files": {
          ...
          "bigfilechunking": false,
        },
```

I guess the check was never implemented in the desktop client as chunking v1 was always supported by OC from start. So now dealing with OCIS with no or broken support makes this check necessary.

@michaelstingl @TheOneRing

**Comment by TheOneRing** [comment]
See https://github.com/owncloud/client/issues/7849
