### ISSUE TITLE
ownCloud submenu keeps disappearing

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7851]
Windows 10 
2.6.3263_rc1 (build 13313)

Steps to recreate:
1) Open setting dialog
2) Select 'Open folder' from the three dots menu in Account tab
3) Right click on Documents folder 
4) Select ownCloud -> Share
5) Close the Sharing dialog
6) Select ownCloud -> Share again

Actual result: ownCloud submenu is missing. (You might need to repeat the 4th and 5th step twice). Restart brings the menu back
Expected result: ownCloud submenu is always available

**Comment by TheOneRing** [comment]
Can't reproduce on Windows and Mac.

**Comment by jnweiger** [comment]
That is normal behaviour, if there is also a testpilotcloud or other branded client running. 
Did that happen on a machine, where no other client ran?

**Comment by HanaGemela** [comment]
Yeah, more than one client was running with oC10
