### ISSUE TITLE
Client fails to load sync-exlude.lst from /etc/ownCloud/

### ISSUE THREAD

**Issue by MonkeyKhan** [owncloud/client#7852]
### Expected behaviour
ownCloud client reads `/etc/owncloud/sync-exlude.lst` and sychronizes.

### Actual behaviour
Error `Could not read system exclude file` and no synchronization. The log indicates that the system exclude file is searched for relative to current working directory. If owncloud is launched from `/`, there is no error (I had to manually move the sync-exclude.lst to its destination though)

Error log when being started from directory of binary executable
```
04-30 15:47:39:724 [ info gui.application ]:	"################## ownCloud locale:[en_US] ui_lang:[] version:[2.7.0git] os:[Ubuntu 20.04 LTS]"
04-30 15:47:39:725 [ info gui.application ]:	Using "en_US" translation
04-30 15:47:39:725 [ info gui.application ]:	Adding extra plugin search path: "/usr/local/bin/../lib/x86_64-linux-gnu/plugins"
04-30 15:47:39:725 [ info gui.application ]:	VFS suffix plugin is available
04-30 15:47:39:725 [ info gui.socketapi ]:	server started, listening at  "/run/user/1000/ownCloud/socket"
04-30 15:47:39:725 [ info gui.folder.manager ]:	setting remote poll timer interval to 30000 msec
04-30 15:47:39:752 [ info gui.account.manager ]:	Restored:  0  unknown certs.
04-30 15:47:39:890 [ info gui.application ]:	Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
04-30 15:47:39:892 [ info gui.folder.manager ]:	Setup folders from settings file
04-30 15:47:39:892 [ info sync.configfile ]:	Adding system ignore list to csync: "/home/user_name/git/owncloud_client/client-build/etc/ownCloud/sync-exclude.lst"
04-30 15:47:39:892 [ info sync.configfile ]:	Adding user defined ignore list to csync: "/home/user_name/.config/ownCloud/sync-exclude.lst"
04-30 15:47:39:893 [ warning gui.folder ]:	Could not read system exclude file
```

### Steps to reproduct
1. Clone repo, build, start owncloud from any directory other than `/`

### Client configuration
Client version: 2.7.0git

Operating system: Ubuntu 20.04

OS language: enUs

Qt version used by client package (Linux only, see also Settings dialog): 5.12.8

Client package (From ownCloud or distro) (Linux only): from source

Installation path of client: /home/user_name/git/owncloud_client/

**Comment by TheOneRing** [comment]
Hi did you use the install step?
