### ISSUE TITLE
Client forgetting Auth Token

### ISSUE THREAD

**Issue by Wurzelkoch** [owncloud/client#7857]
More or less the same behaviour as in this issue for android:
https://github.com/owncloud/android/issues/2685

Re-authentification prompt did in all but one occurrence happen after shotdown/reboot of the system.

Currently I'm using Owncloud client 2.6.1 (build 2071), problem happened before and after upgrade from Debian 9 to 10.

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version: 2.6.1 (build 2071)
Operating system: Debian  4.19.98-1+deb10u1
OS language: german
Qt version used by client package (Linux only, see also Settings dialog):
Client package (From ownCloud or distro) (Linux only): from distro owncloud-client_2.5.1.10973+dfsg-1_amd64.deb

### Logs

1. Client logfile: Will give later, switched on logging just now. So I'll have to wait until it happens the next time.

**Comment by Wurzelkoch** [comment]
I did not read the latest discussion in the mentioned issue, so I guess we'll wait if the fix discussed there will help.

**Comment by michaelstingl** [comment]
> More or less the same behaviour as in this issue for android:
> [owncloud/android#2685](https://github.com/owncloud/android/issues/2685)

@Wurzelkoch Android issue has probably nothing to do with Debian issue. I'd recommend to re-open the issue and investigate independent.

What is the oC server version you're connected to?

**Comment by Wurzelkoch** [comment]
You may be right.
> What is the oC server version you're connected to?
ownCloud 10.3.2 (stable) 
The issue did not (yet) happen with my second account, where the Server version is sciebo 10.4.0 (stable)

**Comment by TheOneRing** [comment]
Could you try to reproduce it with 2.6.3 :)

**Comment by TheOneRing** [comment]
Now new information provided
