### ISSUE TITLE
Problems in VFS using .owncloud extension

### ISSUE THREAD

**Issue by icestraw** [owncloud/client#7859]
I'm using VFS and when using "Free up space", the file is replaced with a placeholder file with .owncloud extension. However that name is not identical to the original file name, which may cause many app unable to find the original file.

Instead of using .owncloud file, the placeholder should use the original file's name. And for example, in macOS, we should use xattr, add com.apple.fileutil.PlaceholderData for file metadata and use com.apple.LaunchServices.OpenWith for downloading placeholder.

### Expected behaviour

The placeholder's name should be the same as original file.

### Actual behaviour

The placeholder's name is different

### Steps to reproduce
1. Open owncloud and add a folder for VFS
2. Free up its space
3. The folder is filled with .owncloud files.

### Server configuration
Operating system: ubuntu 18

Web server: apache2

Database: mariadb

PHP version: 7.2

ownCloud version: 10

Storage backend (external storage): local

### Client configuration
Client version: 2.6.1

Operating system: macOS

OS language: English

Installation path of client: /Applications

**Comment by michaelstingl** [comment]
> However that name is not identical to the original file name, which may cause many app unable to find the original file.

Please provide an example. Name before and after? `.owncloud` gets added, but name before the extension stays the same? Can you confirm?

> Instead of using .owncloud file, the placeholder should use the original file's name. And for example, in macOS, we should use xattr, add com.apple.fileutil.PlaceholderData for file metadata and use com.apple.LaunchServices.OpenWith for downloading placeholder.

Plan is to get rid of placeholder files and implement based on the native API's around Apple's [`FileProvider`](https://developer.apple.com/documentation/fileprovider). See discussion in https://github.com/owncloud/client/issues/4341#issuecomment-521588697

I hope we get enough information at [WWDC starting June 22nd](https://www.apple.com/newsroom/2020/03/apples-wwdc-2020-kicks-off-in-june-with-an-all-new-online-format/).

**Comment by icestraw** [comment]
I see...it's actually better to use that File Provider API, since it's the same logic as iOS.
One advice, if using File Provider, there should be a server implemented dir listing pagination, which needs additional work.

**Comment by michaelstingl** [comment]
Seems macOS 11.0 Big Sur will come with the required API’s:
http://codeworkshop.net/objc-diff/sdkdiffs/macos/11.0/FileProvider.html
