### ISSUE TITLE
Client shouldn't chunk in case no chunking capabilities were announced.

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#7862]
https://github.com/owncloud/client/issues/7849
> See related https://github.com/owncloud/ocis/issues/195
> 
> Whenever the capability "bigfilechunking" is set to false, the desktop client must not attempt to use the chunking v1 algorithm (this one https://github.com/owncloud/client/blob/f076682a8c7b1a425131fcb5eae2dfbc4febfac5/src/libsync/propagateuploadv1.cpp#L104)
> 
> the capability attribute is in:
> ```
> "ocs": {
>     "data": {
>       ...
>       "capabilities": {
>         ...
>         "files": {
>           ...
>           "bigfilechunking": false,
>         },
> ```
> 
> I guess the check was never implemented in the desktop client as chunking v1 was always supported by OC from start. So now dealing with OCIS with no or broken support makes this check necessary.
> 

---------------------------------

Similar when `OWNCLOUD_CHUNK_SIZE=0` was set

Also in case:
`"bigfilechunking": false,`

Related:
https://github.com/owncloud/ocis/issues/203
https://github.com/owncloud/ocis/issues/272

**Comment by jnweiger** [comment]
Chunking settings are in multiple places in the capabulities report:

```
.ocs.data.capabilities.dav: { "chunking": "1.0", ...
.ocs.data.capabilities.files: { "bigfilechunking": true, ...
```

Capabilities are normally hardcoded per server. There is no GUI or config file to tune them.
For testing purposes, capabilities can be edited /var/www/owncloud/apps/*/lib/Capabilities.php -- Edit at own risk :-)

**Comment by jnweiger** [comment]
Tested with
testpilotcloud 2.7.0daily20201019 (build 2311)
and 
```
curl -s -u admin:admin 'http://pigpen.jw-qa.owncloud.works/status.php'
{"installed":true,"maintenance":false,"needsDbUpgrade":false,"version":"10.5.0.10","versionstring":"10.5.0","edition":"Community","productname":"ownCloud"}
```

We disable all chunking support on the server side by editing apps/dav/lib/Capabilities.php and apps/files/lib/Capabilities.php

```
curl -s -u admin:admin 'http://pigpen.jw-qa.owncloud.works/ocs/v1.php/cloud/capabilities?format=json'  | jq . | grep chunk
          "bigfilechunking": false,
          "chunking": "",
```

Steps to reproduce
* connect client to server, with logging enabled
* wait for initial sync
* move a 42MB file into the desktop sync folder
* wait until upload finishes
* check the logfiles
```
zgrep -i nextchunk 20201028_1132_owncloud.log.0.gz 
10-28 11:32:18:534 [ debug sync.propagator.upload.v1 ]	[ OCC::PropagateUploadFileV1::startNextChunk ]:	5 false 0 10000000
10-28 11:32:18:535 [ debug sync.propagator.upload.v1 ]	[ OCC::PropagateUploadFileV1::startNextChunk ]:	5 false 10000000 10000000
10-28 11:32:18:535 [ debug sync.propagator.upload.v1 ]	[ OCC::PropagateUploadFileV1::startNextChunk ]:	5 false 20000000 10000000
10-28 11:33:34:715 [ debug sync.propagator.upload.v1 ]	[ OCC::PropagateUploadFileV1::startNextChunk ]:	5 false 30000000 10000000
10-28 11:34:20:953 [ debug sync.propagator.upload.v1 ]	[ OCC::PropagateUploadFileV1::startNextChunk ]:	5 true 40000000 3994768

```
The client did chunking.

Expected behaviour: no chunking.

**Comment by jnweiger** [comment]
[20201028_1148_owncloud.log.0.gz](https://github.com/owncloud/client/files/5451334/20201028_1148_owncloud.log.0.gz)
[20201028_1147_owncloud.log.0.gz](https://github.com/owncloud/client/files/5451335/20201028_1147_owncloud.log.0.gz)
[20201028_1146_owncloud.log.2.gz](https://github.com/owncloud/client/files/5451336/20201028_1146_owncloud.log.2.gz)
[20201028_1146_owncloud.log.1.gz](https://github.com/owncloud/client/files/5451337/20201028_1146_owncloud.log.1.gz)
[20201028_1146_owncloud.log.0.gz](https://github.com/owncloud/client/files/5451339/20201028_1146_owncloud.log.0.gz)
[20201028_1144_owncloud.log.0.gz](https://github.com/owncloud/client/files/5451340/20201028_1144_owncloud.log.0.gz)
[20201028_1135_owncloud.log.0.gz](https://github.com/owncloud/client/files/5451342/20201028_1135_owncloud.log.0.gz)
[20201028_1134_owncloud.log.0.gz](https://github.com/owncloud/client/files/5451343/20201028_1134_owncloud.log.0.gz)
[20201028_1132_owncloud.log.0.gz](https://github.com/owncloud/client/files/5451344/20201028_1132_owncloud.log.0.gz)

**Comment by jnweiger** [comment]
We need to restart the client, when changing the settings.
Changing server capabilities while the client is connected is unrealstic, given that these values are normally hardcoded per server.

Retesting with restarting the client before changing the server capabilities:

|`bigfilechunking`|`chunking`|result
|----|----|----
|true| | chunking
|false || no chunking :heart:

**Comment by jnweiger** [comment]
Takeaway:
* We ignore the reported `OC-Chunk-Size` in the logs -- the actual upload is in one big chunk and is considered "no chunking".
* The capability `chunking="1.0" does *not* enable "Chunking V1" -- it switches to "NG" instead.
