### ISSUE TITLE
Client does not remove local files after unchecking single folder

### ISSUE THREAD

**Issue by NicolasGoeddel** [owncloud/client#7882]
### Expected behaviour
After unchecking a single folder to disable its synchronisation and confirming that its content will be removed locally, the client should remove it locally.

### Actual behaviour
The folder and its content still exists locally, but remains unchecked in the folder tree and does not get synchronized anymore. Also on every sync run it shows a message like this:
```
0 seconds remaining, 833 KB of 833 KB, File 9 of 216694
```
The number 216694 is nearly the amount of files inside the folder I excluded from synchronisation.

It appears that the synchronization is as fast as it was before but it has some problems with calculating the amount of files it has to sync and also forgot to delete the folder locally.

### Steps to reproduce
1. Synchronise a folder consisting of over 1 million nested subfolders (311 GB).
2. Wait until all files were synchronized (in reality this happened distributed over several years)
3. Go through the directory tree shown in the frontend and uncheck a single and quite big folder (210000+ files, 36 GB)
4. Confirm that you want to have that folder deleted locally.
5. Quit the client normally using the context menu because it seems not hang and because the SQLite's `wal` file grew over 4 GB.
6. Verify that the `wal` file got processed.
7. Start the client again. 
8. Wait 2.5 hours until the frontend finally pops up. In the meantime run `strace -p $(pidof owncloud)` in a terminal to see what it does. It runs `stat` on every file in the previously unchecked folder and writes to its SQlite database.
9. While the frontend is now available expect it to do the same thing twice, so wait another 2.5 hours until it has settled.
10. Now the previously unchecked folder is still locally available but the sync run ignores it which seems right.

### Server configuration
Operating system:
Ubuntu 18.04.4 LTS

Web server:
Apache 2.4.29

Database:
Mysql 14.14

PHP version:
PHP 7.2 FPM

ownCloud version:
10.4.0

Storage backend (external storage):
None

### Client configuration
Client version:
2.6.1 (build 2071)

Operating system:
ubuntu 18.04.4 LTS

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):
Nothing to see there

Client package (From ownCloud or distro) (Linux only):
http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_18.04  Packages

Installation path of client:
/usr/bin/owncloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
https://cloud.goeddel.net/index.php/s/wmBMSqPMCLTnjzY
(The password comes with an email to @TheOneRing because I don't want to have the log publicly available)

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by NicolasGoeddel** [comment]
I guess I found the solution.

The client just stops its sync run before deleting all files in the folder if an error like "Destination file exists" happens. In my case there were 4 of these errors present since a while and I didn't care about them. These errors also were at a different location than the folder I want to get rid of locally, so I thought it's okay to ignore them.

Now after just a few minutes all the files are gone like I expected it to happen.

I still think this is an issue and the error messages should be a bit more meaningful. I didn't find any explanation about what "Destination file exists" really means. The mentioned files exist on both sides (server and client). I expect them to be in sync, not in sync or conflicting. But not that message. Can you please explain to me what it really means?

**Comment by TheOneRing** [comment]
Fixed in https://github.com/owncloud/client/issues/9311
