### ISSUE TITLE
Ubuntu 20.04 - SSL handshake failed

### ISSUE THREAD

**Issue by JJussi** [owncloud/client#7884]
Ubuntu 20.04
Original problem (this same) with 2.5.1.10973+dfsg-1ubuntu4, so I tried
Version 2.6.3daily20200530 (build 2600) but still when add new account, I get error:
Failed to connect to ownCloud at https://owncloud.jjussi.com: SSL handshake failed

Program owncloud-client works at Ubuntu 18.04 (version 2.4.1+dfsg-1) without errors. Installing that same version to Ubuntu 20.04 doesn’t work…

Whole ticket can be found:

https://central.owncloud.org/t/ubuntu-20-04-ssl-handshake-failed/26366

**Comment by davidboutelier** [comment]
Identical problem after upgrading from 18.04 to 20.04

**Comment by jnweiger** [comment]
Is this specific to the server at https://owncloud.jjussi.com or do you have the same issue, when e.g. connecting to demo.owncloud.org ?

**Comment by JJussi** [comment]
If I go to https://owncloud.jjussi.com, it's certificate points to that address

![image](https://user-images.githubusercontent.com/5318740/85525625-ec194600-b611-11ea-89b9-9b40cdc22740.png)

If I go to https://iot.jjussi.com, it's have own certificate....

![image](https://user-images.githubusercontent.com/5318740/85525921-369ac280-b612-11ea-861d-2b3772f6d0ca.png)

And.. If I try to use **IP-address** (or host name **jjussi.com**), then I get information that it's not secure, because certificate points to iot.jjussi.com

![image](https://user-images.githubusercontent.com/5318740/85526425-ab6dfc80-b612-11ea-84a4-0bcca89a1715.png)

So, do **owncloud** -client try to connect to jjussi.com or owncloud.jjussi.com?

**Comment by jnweiger** [comment]
On the client side we have
|Platform|Test|Result|
|-|-|-|
|ubuntu:20.04|01_cmd_vers.sh|	owncloud version 2.6.3 (build 2795)
|ubuntu:18.04|01_cmd_vers.sh|	owncloud version 2.6.3 (build 2795)
|ubuntu:20.04|12_openssl_vers.sh|	Using 'OpenSSL 1.1.1f  31 Mar 2020'
|ubuntu:18.04|12_openssl_vers.sh|	Using 'OpenSSL 1.1.1  11 Sep 2018'


Okay, maybe I mistyped the url on that one attempt that gave me the iot.jjussi.com cert. I cannot reproduce that anymore.

**Comment by JJussi** [comment]
And at the Manjaro (5.6.15) where owncloud-client works fine it's 
ownCloud version 2.6.1
Git revision 6793f774adcd4beff46923ff7186ff1a9b6ec47c
Using Qt 5.14.2, built against Qt 5.14.1
Using 'OpenSSL 1.1.1g  21 Apr 2020'

So, maybe it's that 1.1.1f?!?

**Comment by jnweiger** [comment]
https://www.openssl.org/blog/blog/2017/05/04/tlsv1.3/ has something scary:

> There are new ciphersuites that only work in TLSv1.3. The old ciphersuites cannot be used for TLSv1.3 connections.

So **if** the new 1.1.1f insists on using TLSv1.3, and your server cannot do this, then the connection must fail. :-(
To test that hypothesis: We'd need to find the supported tls versions on both ends and see if or if not we have some protocol version in common.

**Comment by michaelstingl** [comment]
You‘ll get detailed lists of ciphers with https://www.ssllabs.com/ssltest/

**Comment by jnweiger** [comment]
https://www.ssllabs.com/ssltest/analyze.html?d=owncloud.jjussi.com
Lists the supported protocols like this:
![image](https://user-images.githubusercontent.com/1108546/85576600-d408ed00-b638-11ea-94df-c67994696e57.png)

So it is TLS-1.2 only on the server side. Now we need to find out, if our clients are locked to TLS-1.3 when running on Ubuntu-20.04

**Comment by jnweiger** [comment]
@JJussi Please also note: https://www.ssllabs.com/ssltest/analyze.html?d=owncloud.jjussi.com lists the iot.jjussi.com cert as a second certificate under owncloud.jjussi.com --  Is that the expected reading?

**Comment by JJussi** [comment]
@jnweiger That host have multiple sub-sites and as you saw, if you ask certificate with IP-address (or just jjussi.com), it will return with iot.jjussi.com -certificate.
Anyway, iot.jjussi.com and owncloud.jjussi.com are at same host and with share same IP-address. 

#> nslookup 185.81.166.228
228.166.81.185.in-addr.arpa     name = owncloud.jjussi.com.

OK.. There is "error"... I need to change that certificate to there... Earlier machine IP-address was tight to iot.jjussi.com, but I just change it... That didn't change this problem earlier.

**Comment by jnweiger** [comment]
@TheOneRing The open question now is, if the desktop client should be able to connect via TLS-1.2 when running on Ubuntu-20.04 with their openssl-1.1.1f -- or if we can make that happen.

**Comment by guruz** [comment]
(Maybe related to https://blog.cloudflare.com/encrypted-sni/ ? Just a super wild guess...)

**Comment by TheOneRing** [comment]
Could you try https://github.com/owncloud/client/actions/runs/257441975 the builds provides an app image for testing and it comes with our own openssl build.

**Comment by JJussi** [comment]
I tested that version and it worked very well against my owncloud-server.

**Comment by TheOneRing** [comment]
So we can assume its due to an old openssl, thx.

**Comment by dpsi** [comment]
Hi, I am also facing TLS related issues with [Simon Fraser University's](https://vault.sfu.ca) ownCloud instance. The above app image worked without issue.

When you say "due to an old openssl", do you mean old openssl on the server? On the Ubuntu client openssl 1.1.1f is still newish, only 1 release behind.

```
$ curl -V
curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
Release-Date: 2020-01-08
$ curl -v https://vault.sfu.ca
*   Trying 142.58.104.89:443...
* TCP_NODELAY set
* Connected to vault.sfu.ca (142.58.104.89) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (IN), TLS handshake, Server key exchange (12):
* TLSv1.2 (OUT), TLS alert, handshake failure (552):
* error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
* Closing connection 0
curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
```

**Comment by jayonhisphone** [comment]
> Hi, I am also facing TLS related issues with [Simon Fraser University's](https://vault.sfu.ca) ownCloud instance. The above app image worked without issue.
> 
> When you say "due to an old openssl", do you mean old openssl on the server? On the Ubuntu client openssl 1.1.1f is still newish, only 1 release behind.
> 
> ```
> $ curl -V
> curl 7.68.0 (x86_64-pc-linux-gnu) libcurl/7.68.0 OpenSSL/1.1.1f zlib/1.2.11 brotli/1.0.7 libidn2/2.2.0 libpsl/0.21.0 (+libidn2/2.2.0) libssh/0.9.3/openssl/zlib nghttp2/1.40.0 librtmp/2.3
> Release-Date: 2020-01-08
> $ curl -v https://vault.sfu.ca
> *   Trying 142.58.104.89:443...
> * TCP_NODELAY set
> * Connected to vault.sfu.ca (142.58.104.89) port 443 (#0)
> * ALPN, offering h2
> * ALPN, offering http/1.1
> * successfully set certificate verify locations:
> *   CAfile: /etc/ssl/certs/ca-certificates.crt
>   CApath: /etc/ssl/certs
> * TLSv1.3 (OUT), TLS handshake, Client hello (1):
> * TLSv1.3 (IN), TLS handshake, Server hello (2):
> * TLSv1.2 (IN), TLS handshake, Certificate (11):
> * TLSv1.2 (IN), TLS handshake, Server key exchange (12):
> * TLSv1.2 (OUT), TLS alert, handshake failure (552):
> * error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
> * Closing connection 0
> curl: (35) error:141A318A:SSL routines:tls_process_ske_dhe:dh key too small
> ```

@dpsi 
did you find a resolution? Are you staff or student? I am also having this problem, just having upgraded to ubuntu 20.4 from 18.4.
I put in a ticket with the FS IT staff, but I'm not holding my breath. ( I work at Facilities Services) jhaynes

**Comment by dpsi** [comment]
> @dpsi
> did you find a resolution? Are you staff or student? I am also having this problem, just having upgraded to ubuntu 20.4 from 18.4.

Hey there, the packaged version of ownCloud (2.6.3 (build 2668)) still does not work with SFU Vault.
For now I have been manually running the AppImage mentioned above.

I will shoot you an email so we can discuss further.

**Comment by TheOneRing** [comment]
Could you try a recent non working 2.7 build and paste the output of --version here?
It should look similar to
```
testpilotcloud 2.7.0daily20201019 (build 2310) Oct 19 2020 02:11:56
https://github.com/owncloud/client/commit/b32bdc69a5c546c2170ac7a71e54e16150045d0e
Libraries Qt 5.12.9, OpenSSL 1.1.1g  21 Apr 2020
Using virtual files plugin: suffix
```
If the openssl version would be missing we could be certain that something is seriously broken

**Comment by TheOneRing** [comment]
Does the issue still exists?

**Comment by JJussi** [comment]
No problem anymore.

**Comment by kuateric** [comment]
i have the same problem since the upgrade to ubuntu 22.04 
the output of --version is : 
```bat
gui.platform: adding plugin directory "/opt/ownCloud/ownCloud/bin/../lib/x86_64-linux-gnu/plugins"
ownCloud ownCloud 3.0.0.9215-
https://github.com/owncloud/client/commit/457b08ed362e4c9ae430797508791ff25171c36c
Libraries Qt 5.15.2, OpenSSL 3.0.2 15 Mar 2022
Using virtual files plugin: suffix
ubuntu-5.15.0-56-generic 
```

**Comment by kuateric** [comment]
okay
