### ISSUE TITLE
tray icon is unresponsive while first run dialog is open

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7889]
Seen with 2.6.3 testpilotcloud-client and owncloud-client 2.7.daily on Ubuntu 18.04

![image](https://user-images.githubusercontent.com/1108546/84003819-e1e91d80-a96a-11ea-8950-4f58125f292f.png)

While the user has the 'Choose What to Sync' open, the tray icon cannot be clicked. 
Expected behaviour: A left click on the icon should bring the settings window to the front (in case it is hidden behind other windows). And: A right click should bring up the tray menu, e.g. in order to close the client, without finding the open windows on the desktop.

One step earlier (entering the URL in the first run wizard) or later, the tray icon is responsive:
![image](https://user-images.githubusercontent.com/1108546/84004555-01cd1100-a96c-11ea-93eb-a6e9f745fd4d.png)

**Comment by TheOneRing** [comment]
This is intended behaviour as we want the user to finish and respond to that dialog before getting side tracked...

**Comment by michaelstingl** [comment]
> we want the user to finish and respond to that dialog before getting side tracked

Fine for me 👍

**Comment by jnweiger** [comment]
A nonresponsive icon is bad UX in any case. Doing that on purpose is still bad UX. Not giving a clue makes it hard to find the reason.

**Comment by TheOneRing** [comment]
Its not unresponsive on mac.
Also could we remove the option that pops up this dialog automatically?
Thats bad ux...

**Comment by jnweiger** [comment]
Reproduced with Version 2.7.0 (build 1868) dated Jul 23 2020, 01:48:16 on Ubuntu 18.04

* go to the settings page,
* click the version number
* the version dialog opens
* click firefox or some other window to the front to hide the owncloud client.
* click on the tray icon. No response. The client remains hidden.
