### ISSUE TITLE
No Tray-Icon in Fedora 32 and CentOS

### ISSUE THREAD

**Issue by iHerrmann77** [owncloud/client#7890]
Tested on Desktop Sync Client 2.6.3 RC4
- Fedora 32 (Workstation Edition) 64-Bit, GNOME Version 3.36.2
- CentOS 8.1, GNOME Version 3.32.2

![noTrayIcon](https://user-images.githubusercontent.com/63246306/84029694-1670cf80-a993-11ea-943d-1763e98fc2b4.png)

Ubuntu and Windows 10 Icon are there.
Expected result: Consistently have icons everywhere.

**Comment by jnweiger** [comment]
I am afraid this is "intended misbehaviour" on behalf of gnome. 
@TheOneRing Do users know, or should we speak about that in the release notes?

**Comment by TheOneRing** [comment]
The behaviour is completely unrelated to ownCloud so no we won't mention it in the release notes.
Closing this as modern gnome distributions just don't have a system tray.
