### ISSUE TITLE
263 changelog should mention qt 5.12.7

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7892]
2.6.1 was released with Qt-5.12.5
2.6.3 will have Qt-5.12.7 bundled.

CHANGELOG.md should mention this and maybe refer https://bugreports.qt.io/browse/QTBUG-81024?filter=21854 for details.

**Comment by jnweiger** [comment]
Um, the CHANGELOG.md file only exists in master, but not in the release branches. Is that correct?

**Comment by TheOneRing** [comment]
We won't mention 3rd party libs in our change log.
