### ISSUE TITLE
Mac: Setup wizard skips "destination" step

### ISSUE THREAD

**Issue by voroyam** [owncloud/client#7894]
When installing the sync client, the installation wizard skips the destination step.
It's not a big issue, but when it's not supposed to ask you where to install the client, it should not show you that there is a step that is skipped.

![](https://im4.ezgif.com/tmp/ezgif-4-851c51e1f149.gif)

Client Version: 2.6.1
Mac OS Version: 10.15.5

**Comment by TheOneRing** [comment]
Works as designed, we only support a installation to the rot drive, so there is no point in displaying the destination selection.

**Comment by TheOneRing** [comment]
And as far as I can tell we can't hide that step in the installer.

**Comment by voroyam** [comment]
We can't modify our own installer? O_o

**Comment by HanaGemela** [comment]
mac client 2.6.3 (build 13765) sometimes doesn't skip this step

**Comment by TheOneRing** [comment]
And its not our installer, is is a theme pkg installer and the theming has some limitations.

**Comment by voroyam** [comment]
Where is the original installer if the one for the Mac OS is a themed one?

**Comment by TheOneRing** [comment]
That is a default mac pkg, we can theme it but we can't change its basic structure.

**Comment by michaelstingl** [comment]
Won’t fix for the *.pkg. Better spend effort in getting rid of the *.pkg.
