### ISSUE TITLE
anongit.kde.org is Discarded but still exists

### ISSUE THREAD

**Issue by ozata** [owncloud/client#7895]
With the last commit anongit.kde.org is discarded but when I try to build with "craft owncloud-client" command it still goes for the anongit.kde.org, is there any way to update this, I have the latest commit but it changed only in the CI Cycle not on the craft I presume?

**Comment by michaelstingl** [comment]
Related:
https://central.owncloud.org/t/owncloud-desktop-client-build-error-with-kdecraft/26562

**Comment by TheOneRing** [comment]
Hi KDE recently discontinued anongit, there was about one month in which an automatic update was possible.
Right now I'd suggest reinstalling craft.
