### ISSUE TITLE
craft-blueprint-kde master fetch error because of anongit.

### ISSUE THREAD

**Issue by ozata** [owncloud/client#7897]
Hello, I'm getting error because git cannot connect to anongit using https.
<img width="1351" alt="error" src="https://user-images.githubusercontent.com/33320778/84637914-f7c48880-aefe-11ea-8b53-0aa3794a6063.png">

**Comment by michaelstingl** [comment]
Issue in `client` repo or in upstream `craft-blueprint-kde` repo?

**Comment by TheOneRing** [comment]
Hi KDE recently discontinued anongit, there was about one month in which an automatic update was possible.
Right now I'd suggest reinstalling craft.
