### ISSUE TITLE
Monochrome tray icon missing

### ISSUE THREAD

**Issue by vexillia** [owncloud/client#7903]
### Expected behaviour
Switching to monochrome icon produces new icon in tray as it does in 2.5.1

### Actual behaviour
Tray area blank but responds to mouse as expected.

### Steps to reproduce
1. Load new release via PPA
2. Change icon to monochrome.

### Client configuration
Client version: 2.6.3
Operating system: xubuntu 20.04 (xfce)
OS language: English

**Comment by jnweiger** [comment]
What is the exact build release number or deb package name that you installed?
Do you have the same issue, if you install the latest 2.6.3 from https://software.opensuse.org//download.html?project=isv%3AownCloud%3Adesktop&package=owncloud-client

**Comment by vexillia** [comment]
Sorry I can't help any further.  I ran into an insoluble upload issue which persisted even though I re-installed everything.  I deleted everything including the deb files I used that gave this issue.
