### ISSUE TITLE
[VFS] Documentation needed

### ISSUE THREAD

**Issue by voroyam** [owncloud/client#7913]
We need an official documentation about the state, how to use and the risk involved when using VFS on windows Mac or linux.

Right now we have 2 blog articles, which is not sufficient from my POV.

https://owncloud.org/news/desktop-client-2-6-release-native-virtual-file-system-on-windows-10/ https://owncloud.org/news/owncloud-client-goes-virtual-sync-files-demand/

**Comment by voroyam** [comment]
Need to document that we need windows version 1709 at least to support VFS.

**Comment by voroyam** [comment]
no progress, closing

**Comment by michaelstingl** [comment]
Next attempt: https://github.com/owncloud/docs/issues/3508
