### ISSUE TITLE
Update Supported Platforms

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#7914]
- [x] Announce depreciation for the next release on central

- [x]  Add changed platforms to Release Notes - no release notes for 2.6.3

- [x]  Update Desktop client [download page](https://owncloud.org/download/#owncloud-desktop-client)

- [x]  Update [client docs](https://doc.owncloud.com/desktop/installing.html#system-requirements) (update master and backport to 2.6) to display supported platforms for the latest stable release. 
Master: https://github.com/owncloud/client/pull/7929 https://github.com/owncloud/client/pull/7915
2.6: https://github.com/owncloud/client/pull/7974

- [x]  Update [server docs](https://doc.owncloud.com/server/admin_manual/installation/system_requirements.html#client-operating-system) (update master and backport to 10.4) to display supported platforms for the latest stable release
Master: https://github.com/owncloud/docs/pull/2712
10.5: https://github.com/owncloud/docs/pull/2713
10.4: https://github.com/owncloud/docs/pull/2714

Update OBS:
+ [x] deepcopy current client including its Qt512x dependencies, so that platforms dont get lost for the current one. 
+ [x] apply platform change to isv:ownCloud:Qt512x 
+ [x] do the same in obs.int / drone toolchain

**Comment by HanaGemela** [comment]
@michaelstingl Do we have release notes?

**Comment by jnweiger** [comment]
Checked 'apply platform change to isv:ownCloud:Qt512x' without doing anything. 
Qt5127 had received all current platforms before the builds. I cannot think of anything to be done after a release.

**Comment by HanaGemela** [comment]
All tasks done
