### ISSUE TITLE
Long pathnames gives 404 Not found on Windows

### ISSUE THREAD

**Issue by JanOonk** [owncloud/client#7927]
### Expected behaviour
Syncing files with long pathnames on Windows should work.

### Actual behaviour
Every day the sames files with long pathnames give "ownCloud,Server replied "404 Not Found"

27/06/2020 09:39:29,Shared/Lesmateriaal MIW 2.0 FINAL/1_Basisfase/1.3 - OOP/_MIW Tentamens/Herkansing cohort 16/HerkansingMilieuzone20190606Uitwerking/pom.xml,                      **ownCloud,Server replied "404 Not Found"** to "GET https://surfdrive.surf.nl/files/remote.php/dav/files/j.oonk@fontys.nl/Shared/Lesmateriaal MIW 2.0 FINAL/1_Basisfase/1.3 - OOP/_MIW Tentamens/Herkansing cohort 16/HerkansingMilieuzone20190606Uitwerking/pom.xml" **(Sabre\DAV\Exception\NotFound)**

If I do "force sync now" the problems seems to disappear, but a few hours later the exact same files give 404 errors.

### Steps to reproduce
1. Use longpathnames for files to sync

### Server configuration
Surfdrive

### Client configuration
Client version:
Owncloud latest 2.6.3 build 13551 from Stable channel

Operating system:
Windows 10

OS language:
English

### Logs

1. Client logfile: 
[logfile.txt](https://github.com/owncloud/client/files/4840908/logfile.txt)

**Comment by T0mWz** [comment]
Hi @JanOonk,

Can you have a look of this issue still occurs?

Thanks! :-)

**Comment by JanOonk** [comment]
Did something change on your end? Nevertheless today I didn't get the errors anymore.
