### ISSUE TITLE
Desktop client synchronizing 404 error

### ISSUE THREAD

**Issue by Disenosos** [owncloud/client#7933]
### Expected behaviour
Synchronize files from the cloud to my pc

### Actual behaviour
synchronization gives 404 error

### Steps to reproduce
1. Run owncloud client on windows 10
2. Wait for it to start syncing
3. starts loading and gives 404 error

### Server configuration
Operating system:

Web server: Ubuntu 18

Database: mysql 5.7

PHP version: 7.4

ownCloud version: 10.5.0 RC2

Storage backend (external storage): none

### Client configuration
Client version: 2.6.3

Operating system: windows 10

OS language: english

Installation path of client: widnows default, drive C

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: https://gist.github.com/Disenosos/eac5b4a106c16975e1e1cb27ec1c0c38

2. Web server error log:  https://gist.github.com/Disenosos/ea430a2011d8e6b958c8415d8d23e2a5

3. Server logfile: ownCloud log (data/owncloud.log): https://gist.github.com/Disenosos/ce0137ec86ddeaae9c6f8e100af2eef5

**Comment by michaelstingl** [comment]
@Disenosos In the client logfile, I can't find an error. No single occurrence of `404`. Please capture the log from the time of the incident.

I'd recommend check the client log for the error, then use the "X-Request-ID" from the client log to search for the root cause the owncloud.log or in the webserver log.

**Comment by TheOneRing** [comment]
Nothing can be done with the provided information.
