### ISSUE TITLE
Cannot verify certificate on Centos7

### ISSUE THREAD

**Issue by diocas** [owncloud/client#7951]
We have a few users reporting that their clients, running on CERN Centos 7 (CC7), complain about the certificate of cernbox.cern.ch. I am able to reproduce the problem in a system clean-installed and with all the latest root CAs.

```
The root certificate of the certificate chain is self-signed, and untrusted
with Certificate USERTrust RSA Certification Authority
Organization: The USERTRUST Network
Unit: <not specified>
Country: US
Fingerprint (MD5): 1b:fe:69:d1:91:b7:19:33:a3:72:a8:0f:e1:55:e5:b5
Fingerprint (SHA1): 2b:8f:1b:57:33:0d:bb:a2:d0:7a:6c:51:f7:0e:e9:0d:da:b9:ad:8e

Effective Date: Mon Feb 1 00:00:00 2010 GMT
Expiration Date: Mon Jan 18 23:59:59 2038 GMT
Issuer: USERTrust RSA Certification Authority"
Organization: The USERTRUST Network
Unit: 
Country: US
```

Due to the recent expiration of the Sectigo AddTrust External CA we had to remove this from the chain. But all recent systems should already be trusting UserTrust. When testing our certificate no problem is detected.

We only see this problem with the CERNBox/unbranded OC clients and nothing else (and only on this OS). Are the clients coming with their own set or CAs or is there any problem with the SSL protocol version or some other problem? Can you please check? I've seen that the SSL version could be a problem and, according to your about dialog, you seem to be using a pretty old version of OpenSSL.

Thank you,
Diogo

### Expected behaviour
Client connects without complaining about the certificate

### Actual behaviour
Client complains certificate is self signed.

### Steps to reproduce
1. Install CC7 in a VM
2. Install the latest public release of the sync client
3. Try to connect to cernbox.cern.ch/cernbox/desktop

### Client configuration
Client version: 2.6.3 (build 2668, from https://download.opensuse.org/repositories/isv:ownCloud:desktop/CentOS_7.6/isv:ownCloud:desktop.repo)

Operating system: Centos 7

OS language:

Qt version used by client package (Linux only, see also Settings dialog): 5.12.7

**Comment by TheOneRing** [comment]
Hi,
is the output of `owncloud --version` the same as:
```
ownCloud version 2.6.3 (build 2668)
Git revision f28dd972e941986edc3e1803a25cf067f520b7e3
Using Qt 5.12.7, built against Qt 5.12.7
Using 'OpenSSL 1.0.2k-fips  26 Jan 2017'

**Comment by crrodriguez** [comment]
Hi, the Client on linux is built against whatever the operating system's openSSL is.. centos 7 ships an ancient version.
We will check what certificate store is the client using on this OS

**Comment by TheOneRing** [comment]
I couldn't reproduce the issue with the above setup, in a fresh centos7 docker image.

**Comment by diocas** [comment]
Strange, I would expect CC7 not to have anything special compared to Centos 7. @TheOneRing would you be able to test with CC7 instead?

https://linux.web.cern.ch/centos7/docs/install/ (just download the boot iso, start your vm with it and then install from that url)

**Comment by TheOneRing** [comment]
I tested it with CC7.
![image](https://user-images.githubusercontent.com/200626/87405419-b4257300-c5bf-11ea-98e0-b613efa27d9f.png)

Works like expected

**Comment by diocas** [comment]
Strange, I still see the problem. @TheOneRing when you installed CC7, did you select the CERN options?

**Comment by michaelstingl** [comment]
@diocas could you provide detailed steps to reproduce? (starting from zero)

**Comment by TheOneRing** [comment]
Removing `sudo yum remove CERN-CA-certs-20200530-1.el7.cern.noarch` fixed the issue.

**Comment by diocas** [comment]
Strange, we had to update that package precisely for other software to work.. I will try to contact the linux team to see what they say. Thank you @TheOneRing 
I will update/close this ticket whenever I have news.

**Comment by diocas** [comment]
The CERN team is workin on a fix for the certificate. Thank you so much for helping here.

**Comment by diocas** [comment]
@TheOneRing can you help me reproduce the problem with `openssl`?

Doing `openssl s_client -connect cernbox.cern.ch:443 -CApath /etc/ssl/certs/` is returning ok.

**Comment by TheOneRing** [comment]
I just deleted my cc7 vm 🙈

**Comment by cdamken** [comment]
@diocas I can see in your description that you are testing in a VM from CentOS 7.

In the steps that I had from you were:

```
Steps to replicate the problem:

# Run all of these steps inside a centos7 docker container
docker run -it centos:7 bash

# Install the sync client
````

@TheOneRing @crrodriguez  could be a difference between an installation in a VM and the Docker Container? 

I already had some issues where the Docker does not behave as it should, especially when the clients are running over CLI in the Cern servers

**Comment by diocas** [comment]
I gave the docker image as an easier-to-test version, but we see the problem in both: a (C)C7 VM or docker image.

**Comment by hodyroff** [comment]
root cause is described here: https://access.redhat.com/articles/5117881 we recommend other workarounds then the once chosen.
