### ISSUE TITLE
2.7-daily upload progress indicator does not move

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7958]
Testing on ubuntu-18.04: ownCloud version 2.7.0daily20200708 (build 2764) from https://software.opensuse.org//download.html?project=isv%3AownCloud%3Adesktop%3Adaily%3Amaster&package=owncloud-client 
with ocis-1.0.0-beta8 started via `docker run -ti -p 9200:9200 owncloud/ocis:1.0.0-beta8`

I am adding a 1.99GB size file in the local sync folder of the client.
The client starts uploading.
![image](https://user-images.githubusercontent.com/1108546/87455849-5cf6c100-c606-11ea-98f8-5882969cea99.png)
The progress indicators does not show any progress. It remains at 0 B. After a while the upload indicator disappears and the green checkmark is shown again.
I can confirm by loking at the server, that the file was uploaded successfully.

Expected behaviour: The progress indicator should move while uploading.

**Comment by jnweiger** [comment]
When connecting the same client to demo.owncloud.org (an owncloud-10.4 server), the progress indicator moves as expected while uploading a single big file.

**Comment by TheOneRing** [comment]
It's the tus protocol implementation in the client.
A fix is almost ready.

**Comment by jnweiger** [comment]
confirmed fixed in Version 2.7.0 (build 1868) dated Jul 23 2020, 01:48:16
