### ISSUE TITLE
2.7 Mac issues with the window

### ISSUE THREAD

**Issue by diocas** [owncloud/client#7963]
Hi,

I'm testing the new sync client on my Mac and found some issues with the "new connection" window:

![image](https://user-images.githubusercontent.com/2589871/87548049-4145f600-c6ac-11ea-929a-b479ee47f8ad.png)

If I try to connect to https://ocis-latest.owncloud.com/, I am redirected to the browser correctly. When the browser opens, the application window minimizes, as expected, but it looks like it's minimizing the main window AND the "new connection" window separately. So, after I finish the authentication process, I had the following situations happening to me:
1. Both windows are maximized but the "new connection" is maximized first, which then prevents me from clicking it (because it's behind). This is a problem because the main window is blocked and I cannot click anywhere while the focus is on the other one, so I need to force close the app
1. The main window is maximized first, but the "new connection"  one is not maximized at all, so it took me some time to realize that this window was hidden. As in the first case, the main window is blocked.

I also tried to connect to our OCIS deployment but I forgot to enable implicit auth in our CERN SSO. This caused the application to crash when trying to get the user tokens. Again the problem with the window happened.. The "new connection" disappeared but the main one was blocked and I could not use it.

Versions:
Mac OS: 10.15.4
Client: ownCloud-2.7.0.1667-daily20200702

Diogo

**Comment by TheOneRing** [comment]
Fixes by now
