### ISSUE TITLE
How to build the client on Mac OS X

### ISSUE THREAD

**Issue by ozata** [owncloud/client#7965]
# Expected behaviour
owncloud.app/Contents/Frameworks should exists

### Actual behaviour
It does not

### Steps to reproduce
0. Do the mac build steps
1. Set cmake parameters `cmake -DCMAKE_PREFIX_PATH=/usr/local/Cellar/qt/5.15.0 -DCMAKE_INSTALL_PREFIX=~/owncloud/build ../`
2. run `make` 
3. Check bin/owncloud.app/Contents you will see "Info.plist MacOS      PlugIns    Resources" folders and files but no Frameworks folder.
4. Download owncloud desktop mac client from official site. Install it, you will see owncloud.app/Contents/Frameworks

Without Frameworks app won't run on Macs with no QT Packages.

**Comment by TheOneRing** [comment]
Hi for 2.7 we switched to Craft on mac.
So in a dev environment the client can be directly started in the build dir but for a deployment we use Craft.

We have a new neat script which should help to set up a dev env, https://github.com/owncloud/ownbuild .
It not only sets up Craft but also creates a setup identical to the one we use on out ci (versions etc).

Could you give it a try :)

**Comment by ozata** [comment]
Hello, I'm giving it a try now, thanks

**Comment by ozata** [comment]
@TheOneRing I tried the craft but it gave me permission errors (Maybe couldnt connect to the repo.) And as far as I know we can't build 2.6.3 with craft right? And there is no 2.7 release right now?

**Comment by TheOneRing** [comment]
Hi I fixed the url, just do a pull in the ownbuild folder.

I'm sorry I used authenticated git url... thx for testing 🙈

**Comment by ozata** [comment]
ownbuild built but I got an error at the last step, still there's a possibility that I have a successful build, Im trying to open it right now, not sure if error is because of my system.
<img width="1421" alt="ownbuild build error" src="https://user-images.githubusercontent.com/33320778/88028936-fb70ae00-cb41-11ea-9380-129a68e46f50.png">



The second error is when I'm trying to build 2.
```
ownbuild git:(master) ✗ python3 build.py --branch 2.7 owncloud-client 
Download: https://raw.githubusercontent.com/owncloud/client/2.7/.craft.ini to /Users/ataoz/owncloud/ownbuild/2.7/.craft.ini
HTTP Error 404: Not Found
```

**Comment by TheOneRing** [comment]
thx for pointing out I will fix it.
For now passing  `--no-cache`  should fix it (be sure dependencies are installed first. if not it will build everything from scratch)

**Comment by TheOneRing** [comment]
Should by fixed by https://github.com/owncloud/ownbuild/commit/a6eb57538181b470d0d6801fc2b31f0b9f423d9f

**Comment by ozata** [comment]
<img width="1435" alt="error" src="https://user-images.githubusercontent.com/33320778/88157904-07c53b80-cc14-11ea-9e75-8fdcf8ed8a45.png">


It stops because of a python error but it was getting past this steps 2 days ago, couldn't understand the error, im trying to debug

**Comment by TheOneRing** [comment]
Fixed in https://invent.kde.org/packaging/craft/commit/f613280429fb44de75b889c13e7f0ac30287e060 but the only way that could happen is if craft failed to create a log file.
This can happen with a full disk, see the notification on the screenshot or on Windows when multiple instance are running.

**Comment by ozata** [comment]
Thanks. Process finished successfully but app couldnt be opened because Frameworks folder and some Plugins is not in owncloud.app. (This was my first problem, they dont come when building with generic build instructions too.) Is there a parameter where installs the frameworks and plugins into the owncloud.app

I tried on clean mac machine with only xcode. There is no errors but no QT frameworks or plugins either.

<img width="1216" alt="Screen Shot 2020-07-22 at 15 06 48" src="https://user-images.githubusercontent.com/33320778/88174469-05231000-cc2d-11ea-85e8-403817a31b1f.png">
<img width="1279" alt="Screen Shot 2020-07-22 at 15 06 41" src="https://user-images.githubusercontent.com/33320778/88174481-094f2d80-cc2d-11ea-8918-4acbb6fc7f28.png">
<img width="1306" alt="Screen Shot 2020-07-22 at 15 06 33" src="https://user-images.githubusercontent.com/33320778/88174487-0bb18780-cc2d-11ea-8492-1add0730fd2e.png">

**Comment by ozata** [comment]
I belive it doesnt install QT 
<img width="1378" alt="noqterror" src="https://user-images.githubusercontent.com/33320778/88177746-0acf2480-cc32-11ea-8c73-4dd5bae4753a.png">

**Comment by TheOneRing** [comment]
Ah yes you'd need to execute it through the build script by passing  --run ./macos-x64.....
or by entering a craft env by sourcing the craftenv.sh in the sub folder.

Another solution is to call the build.py with --package owncloud-client which should produce a .pkg file :)

**Comment by ozata** [comment]
I'm trying the first solution but I got error in second solution:
<img width="890" alt="error3" src="https://user-images.githubusercontent.com/33320778/88189903-470a8100-cc42-11ea-8fc0-457e44e4cb19.png">
<img width="1003" alt="error2" src="https://user-images.githubusercontent.com/33320778/88189908-483bae00-cc42-11ea-949b-a7b095e94a6b.png">
<img width="904" alt="error1" src="https://user-images.githubusercontent.com/33320778/88189910-48d44480-cc42-11ea-9441-d243ebf9e300.png">

**Comment by TheOneRing** [comment]
`python3 build.py -- --package owncloud-client`
`python3 build.py -- --run owncloud-client`

**Comment by TheOneRing** [comment]
I updated the readme https://github.com/owncloud/ownbuild/blob/master/README.md

**Comment by ozata** [comment]
I had this error on one machine with `python3 build.py -- --package owncloud-client`
<img width="1018" alt="error1" src="https://user-images.githubusercontent.com/33320778/88260760-b8434600-cccd-11ea-8c23-8b431f023535.png">


And this one on the second machine
<img width="1440" alt="error2" src="https://user-images.githubusercontent.com/33320778/88261539-2d634b00-cccf-11ea-9d08-c1fc15a55a33.png">


Two different errors looked odd. Second instance kept going longer but

**Comment by TheOneRing** [comment]
Hi, did you delete the build folder in between?
If yes, before you can package owncloud, you need to build it first :)
so its `build.py  -- owncloud-client` `build.py  -- --package owncloud-client`

**Comment by ozata** [comment]
I have successfully build with: 🚀 
```
python3 build.py --branch 2.7 owncloud-client
python3 build.py --branch 2.7 -- --package owncloud-client
```
But it shows 2.8.0 git as the version

<img width="687" alt="Screen Shot 2020-07-23 at 14 20 06" src="https://user-images.githubusercontent.com/33320778/88281052-ab374e80-ccef-11ea-865d-5f98bb921f9f.png">

And I have a question. We already have a branded 2.6.3 branch. Could I build that branch with Craft?
Or can I edit build.py end build our branch? 
Do you have any suggestions?

**Comment by TheOneRing** [comment]
2.6 is not supported with craft on mac, and 2.6 is not supported with the build.py at all.
The branch command is for builds.py and ensures that you end up with the dependencies for that branch.

To get a 2.7 build run `python3 build.py --branch 2.7 -- --target 2.7 owncloud-client` same for the package step.

**Comment by ozata** [comment]
Hello Hannah, owncloud builds successfully and easily with craft but we couldn't build our branded version, but we managed it with generic build instructions on Mac OS X. Our problem is solved, so, I'm closing this ticket, thanks for your help.
