### ISSUE TITLE
VFS init sync, use bulk update for log and progress updates 

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#7973]
When creating the placeholders we spend quite some cpu on updating the sync log and tooltips etc.
Only display status for every n'th item

**Comment by TheOneRing** [comment]
For the tooltip updates we could use https://github.com/KDAB/KDToolBox/tree/master/qt/KDSignalThrottler

**Comment by michaelstingl** [comment]
Status updates improved with other approach ✅
