### ISSUE TITLE
2.7 daily builds all have same version number 2.7.0-1

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#7981]
I am installing from the new download repo at https://download.owncloud.com/desktop/ownCloud/daily/2.7/linux/download/
...
Unpacking owncloud-client:amd64 (2.7.0-1) over (2.7.0~daily20200708+oc-2764)
...
the upgrade is smooth, since ubuntu deems `2.7.0` larger than `2.7.0~something`
Later daily or a final will not count as 'newer' as it is. Please re-introduce the `~` notation to indicate "just before"

Reference: https://www.debian.org/doc/debian-policy/ch-controlfields.html#version
```
The lexical comparison is a comparison of ASCII values modified so that all the letters sort earlier than all the non-letters and so that a tilde sorts before anything, even the end of a part.
```

**Comment by jnweiger** [comment]
Today's daily identifies itself as 
![image](https://user-images.githubusercontent.com/1108546/88283570-ecc5fa80-cceb-11ea-970d-f4f521fe684e.png)

**Comment by jnweiger** [comment]
I cannot tell how old my currently installed daily client is. 
owncloudcmd -v says `ownCloud version 2.7.0 (build 1992)`

Updating today from the 2.7 daily repo now gives me `ownCloud version 2.7.0 (build 2058)`

**Comment by TheOneRing** [comment]
@dschmidt was that the error where builds "inherited" config values?

**Comment by dschmidt** [comment]
> @dschmidt was that the error where builds "inherited" config values?

unlikely...

**Comment by dschmidt** [comment]
Fixed https://gitea.owncloud.services/client/build/commit/7ae413a9379c978b736843391dd25ac558f90147 🙈
