### ISSUE TITLE
2.7 Beta1 Connect Window not accessable and Gnome-shell crash

### ISSUE THREAD

**Issue by iHerrmann77** [owncloud/client#7986]
installing from https://download.owncloud.com/desktop/ownCloud/testing/2.7.0.1871-v270beta1/linux/download/

### Steps to reproduce
1. connect the client to https://95.217.214.10:9200
2. trust Certificate
3. Kopano Connect
4. Login successful
5. back to the Client -> NO Connect Window

Gnome-shell crashes!
testet on Ubuntu 20.04/19.10

**Comment by jnweiger** [comment]
beta1 on Linux Mint (Ubuntu 18.04) desktop does not cause a crash.
But same issue withthe connect window, it is hidden behind the settings window.
My workaround: click the tray icon. then the connect window comes to the front.

**Comment by TheOneRing** [comment]
> But same issue withthe connect window, it is hidden behind the settings window.
> My workaround: click the tray icon. then the connect window comes to the front.

I think I know what you are talking about but I haven't seen the issue yet, can you share a screenshot?

**Comment by iHerrmann77** [comment]
[gnome_error_userlog.txt](https://github.com/owncloud/client/files/4981044/gnome_error_userlog.txt)

**Comment by TheOneRing** [comment]
Well https://gitlab.freedesktop.org/wayland/weston/-/issues/231
🤢

**Comment by TheOneRing** [comment]
Was fixed
