### ISSUE TITLE
2.7 Beta1 - Toolbar can be disabled

### ISSUE THREAD

**Issue by iHerrmann77** [owncloud/client#7993]
tested on Windows 10 and Linux

![fedora32dsc270B1_toolbar](https://user-images.githubusercontent.com/63246306/88784578-7bc18f80-d190-11ea-8b58-2622cc444f44.png)

**Comment by michaelstingl** [comment]
@iHerrmann77 steps to reproduce?

**Comment by iHerrmann77** [comment]
Right-Click -> Click on Toolbar

![IMG_1785](https://user-images.githubusercontent.com/63246306/88787172-c09af580-d193-11ea-8b18-c8026ae0701f.jpg)

**Comment by TheOneRing** [comment]
🙈

**Comment by TheOneRing** [comment]
Good that you found it but what did you try to find that 🤣

**Comment by TheOneRing** [comment]
Fixed in https://github.com/owncloud/client/pull/7997
