### ISSUE TITLE
double-colons in key-filename break use of signed-by in sources.list.d - NO_PUBKEY 4ABE1AC7557BEFF9

### ISSUE THREAD

**Issue by btittelbach** [owncloud/client#7998]
### Expected behaviour
If the install instructions for Ubuntu 20.04 from [https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client](https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client) are followed, I expect the packages for the owncloud-client to install without a problem

### Actual behaviour
This error appears during `apt update`
```
Err:5 http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_20.04  InRelease                                                                                                     
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 4ABE1AC7557BEFF9 

```
### Steps to reproduce
1. Install Ubuntu 20.04
2. execute instructions to install owncloud-client 
```
echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/isv:ownCloud:desktop.list
curl -fsSL https://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/isv:ownCloud:desktop.gpg > /dev/null
sudo apt update
sudo apt install owncloud-client

``` 

### Server configuration
Operating system: GNU/Linux Ubuntu 20.04

### Solution

The problem goes away if `isv:ownCloud:desktop.gpg` is renamed to e.g. `owncloud-client.gpg`
``` 
sudo mv /etc/apt/trusted.gpg.d/isv:ownCloud:desktop.gpg /etc/apt/trusted.gpg.d/owncloud_desktop.gpg
``` 

Therefore it appears to me that doublecolons `:` have become invalid in `trusted.gpg.d/*` filenames.

**Comment by btittelbach** [comment]
P.S.: I've of course verified that it is not a permission issue

**Comment by michaelstingl** [comment]
> If the install instructions for Ubuntu 20.10 from https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client are followed, I expect the packages for the owncloud-client to install without a problem

Page shows only instructions for 20.10.

**Comment by michaelstingl** [comment]
I fired up a fresh 20.10 Docker:

```
docker run --rm -ti ubuntu:20.10
```

Wasn't able to reproduce the problem:

```
root@6bdebdf8aa08:/# owncloudcmd --version
ownCloud version 2.6.3 (build 2668)
Git revision f28dd972e941986edc3e1803a25cf067f520b7e3
Using Qt 5.12.7, built against Qt 5.12.7
Using 'OpenSSL 1.1.1f  31 Mar 2020'
root@6bdebdf8aa08:/# history
    1  apt update && apt install wget curl sudo gnupg -y
    2  echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/isv:ownCloud:desktop.list
    3  curl -fsSL https://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/isv:ownCloud:desktop.gpg > /dev/null
    4  sudo apt update
    5  sudo apt install owncloud-client
    6  owncloudcmd --version
    7  history
```

(Just copy-pasting from https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client)

**Comment by btittelbach** [comment]
Ok, Iverified that the instructions work on a ubuntu20.04 docker image. (sorry for the typo above. I meant 20.04, not 20.10)
Then tried the same on my system to find out why the problem initially occurred there...

Once thing I changed on my system in order to mitigate the original "NO_PUBKEY 4ABE1AC7557BEFF9" remained and apparently triggers the issue I reported.

In order to make sure Ubuntu would find the public key, I modified `/etc/apt/sources.list.d/isv:ownCloud:desktop.list` to look like this:
```
deb [signed-by=/etc/apt/trusted.gpg.d/isv:ownCloud:desktop.gpg] http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_20.04/ /

```
This also did not work.

Then I renamed `isv:ownCloud:desktop.gpg` to `owncloud_desktop_key.gpg` _and_ changed `/etc/apt/sources.list.d/isv:ownCloud:desktop.list` accordingly:

```
deb [signed-by=/etc/apt/trusted.gpg.d/owncloud_desktop_key.gpg] http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_20.04/ /

```
This worked. Thus I assumed the `:` in the filename are the problem.

However, `apt update` _also_ does not report a problem, when `[signed-by...]` is removed and the key filename contains `:`

It seems that while double-colons are allowed in key-filenames, they are _not_ allowed in arguments to `deb [signed-by=`
(this is actually clearly specified here: https://manpages.debian.org/unstable/apt/sources.list.5.en.html )

I believe this could be the reason why the person who wrote the owncloud install instructions left out the `[signed-by...]` in the deb-line, which is be the recommended way to add and verify third-party sources.

So the bug is actually _not_ that the `:` contained in the key-filename break the install instructions,
but rather that the doublecolons contained in the key-filename break the ability to use the `signed-by` option.

**Comment by michaelstingl** [comment]
Sadly, we have very little control about the suse download pages. @jnweiger do you know if we can improve here?

BTW Next 2.7 release, primary repos will on our own download page, so we can control the user experience.

**Comment by jnweiger** [comment]
@btittelbach The instructions at SUSE recently got changed. But neither the new nor the old instructions include [signed-by ..] in the deb line for the list file.
Personally I like the idea of having the signed-by tag in the deb line of the list file. But afaik, this is not supported by openSUSE. 
We should open the issue at https://bugzilla.novell.com/enter_bug.cgi?product=openSUSE%20Build%20Service

It is yet another good argument, why colons should not be use in filenames!

As @michaelstingl already noted, we are moving away from the downloads at openSUSE. The repositories at our own infrastructure won't have colons, which "fixes" this issue as far as ownCloud is concerned. But it remains for all of openSUSE, unfortunateley.
