### ISSUE TITLE
'The Cloud sync engine failed to validate the download - Error 0x8007017F' due to checksum's validationFailed

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#7999]
### Expected behavior
The basic user journey should work out of the box without any server-side changes. Right click + '_Always keep on this device_' for instance, does work. 

### Actual behavior
We're encountering this issue when trying to open any '_Available when online_' files by double-clicking on them via the Windows Explorer:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/89413458-24d82f00-d729-11ea-882c-cc13f3bea01a.png"/>
</p>

This introduces a lot of undefined behavior when running the client on VFS mode.

### Logs:

```
08-05 14:45:28:739 [ debug sync.networkjob.get ]	[ OCC::GETFileJob::start ]:	QObject(0x0) false false
08-05 14:45:28:739 [ info sync.networkjob ]:	OCC::GETFileJob created for "https://cernbox.cern.ch/cernbox/desktop" + "/home/Security ebooks/practicalforensicimaging.epub" "OCC::HydrationContext"
08-05 14:45:35:994 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::GETFileJob finished for "/home/Security ebooks/practicalforensicimaging.epub"
08-05 14:45:35:994 [ info sync.vfs ]:	request to validate data "\\Users\\Alfageme\\ownCloud7\\Security ebooks\\practicalforensicimaging.epub" 0 18923667
08-05 14:45:35:994 [ debug sync.networkjob.get ]	[ OCC::GETFileJob::slotReadyRead ]:	Actually finished!
08-05 14:45:35:994 [ info sync.checksums ]:	Computing "SHA1" checksum of device OCC::PlaceholderValidationDevice(0x57ae9c0) in a thread
08-05 14:45:36:231 [ info sync.checksums ]:	Computing "Adler32" checksum of device OCC::PlaceholderValidationDevice(0x57aecd0) in a thread
08-05 14:45:36:231 [ info sync.vfs ]:	validation failed: "Security ebooks/practicalforensicimaging.epub" "The downloaded file does not match the checksum, it will be resumed."
```

The `Oc-Checksum` header for the `GETFileJob` was `Adler32:8e4b7ee2`.

### Client configuration
Client version: CERNBox `2.7.0v270beta1 (build 1913)`

**Comment by TheOneRing** [comment]
Well that just sounds like a broken download or corrupted file, does it occur for all files?

**Comment by SamuAlfageme** [comment]
@TheOneRing yep, reproduces with all the files, but the really weird part is that the alternative path (right click + _Always keep in this device_) downloads the file without checksum validation issues. How does the `OCC::PlaceholderValidationDevice()` calculates the adler32 and how it might differ from the server?

**Comment by TheOneRing** [comment]
@SamuAlfageme can we close this issue or does the problem still exist?

**Comment by TheOneRing** [comment]
Hi @SamuAlfageme this issue should be fixed, I'll mark the issue as stale so it will get closed in 7 days.
If the issue still exist please comment or reopen.

**Comment by SamuAlfageme** [comment]
@TheOneRing finally managed to test these issues and I can confirm it works 🎉 - great work! 🙂
