### ISSUE TITLE
Failed 'desktop.ini' file requests inside dehydrated folders are requested continously by the Windows explorer

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#8000]
### Expected behavior
After setting up the client on VFS mode, the windows explorer requests all the `desktop.ini` files for all the dehydrated folders inside the folder sync connection. (Expected behavior as long as syncing hidden files is enabled - https://github.com/owncloud/client/pull/6404 just blacklists the root sync fonder connection `desktop.ini`.). 

Just opening the explorer is a way of consuming the ini files, as it needs to read it in order to display e.g. the folder icon. It leaves all of them 'Available on this device' (but unpinned).

### Actual behavior
The explorer keeps requesting`desktop.ini` **if it does not succeed to fetch the file (a collateral from #7999)**.

### Client configuration
Client version: CERNBox `2.7.0v270beta1 (build 1913)`

**Comment by michaelstingl** [comment]
Hm, interesting find. I'd need to check behaviour of `desktop.ini` hydration in OneDrive and iCloud for Windows for comparison.

**Comment by SamuAlfageme** [comment]
@michaelstingl I suspect this happens due to the **hidden file** Windows property for `desktop.ini` is not propagated server-side (https://github.com/owncloud/client/issues/3199) **mixed with the issue on #7999 - virtual files fail when hydrating from the explorer/third party software consuming them.**

For reference, the`desktop.ini` (and all hidden) files are totally ignored/blacklisted on OneDrive, with no option otherwise:

<p align="center">
  <img src="https://user-images.githubusercontent.com/2644445/90037726-d09ef300-dcc4-11ea-9689-d062d97e9277.png"/>
</p>

This is also the default behavior for the sync client. However, when **using a client running on Linux syncing in a mount shared with a Windows OS**, the client cannot determine whether the file is hidden as the criteria in both OSS is different.

**Comment by TheOneRing** [comment]
@SamuAlfageme can we close this issue or does the problem still exist?

**Comment by TheOneRing** [comment]
Hi @SamuAlfageme this issue should be fixed, I'll mark the issue as stale so it will get closed in 7 days.
If the issue still exist please comment or reopen.
