### ISSUE TITLE
Blacklist's exponential backoff is ignored when 'Always keep on this device' selected on a folder with erroneous files

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#8001]
### Expected behavior
The usual blacklisting policy to be applied in virtual files with server-side errors (e.g. permission denied, connection closed, server error...).

### Actual behavior
The client keeps retrying to download the file(s), instead of blacklisting after a number of failed (and spaced in time) download attempts.

### Steps to reproduce
1. Set up an intercepting proxy pointing to a file path `/dav/files/.../folder/file`.
2. Mark the parent folder as '_Always available offline_'.
3. **Edit the intercepted flow and impersonate a `500` response code for the GET request.**

### Client configuration
Client version: CERNBox `2.7.0v270beta1 (build 1913)`

**Comment by TheOneRing** [comment]
@SamuAlfageme can we close this issue or does the problem still exist?

**Comment by TheOneRing** [comment]
Hi @SamuAlfageme this issue should be fixed, I'll mark the issue as stale so it will get closed in 7 days.
If the issue still exist please comment or reopen.
