### ISSUE TITLE
Question: what is the meaning of [ info sync.database ]:      possibleUpgradeFromMirall_1_5 detected!

### ISSUE THREAD

**Issue by labkode** [owncloud/client#8004]
What is the meaning of this log line?

It appears on 2.5.4 and 2.6.1 clients at least.

```
[ info sync.database ]:      possibleUpgradeFromMirall_1_5 detected!
```

**Comment by TheOneRing** [comment]
Does it appear with fresh installs or with existing sync roots?
(Mirall is a legacy name of the ownCloud client from before the existence of time)

**Comment by labkode** [comment]
@TheOneRing it appears when running the `owncloudcmd tool`.

**Comment by TheOneRing** [comment]
It was just a pointless warning on a first run https://github.com/owncloud/client/pull/8011
