### ISSUE TITLE
Owncloud gui window doesn't show. 

### ISSUE THREAD

**Issue by rewolff** [owncloud/client#8005]
### Expected behaviour
When I type "owncloud" I expect a window to appear. It worked a few times and now... nothing. It looks as if it is displaying somewhere where I can't see it. I checked my taskbars and no "owncloud" window is listed. 

### Actual behaviour
It worked a few times and now... nothing. It looks as if it is displaying somewhere where I can't see it. I checked my taskbars and no "owncloud" window is listed. 

I'm getting notifications that there is an issue, so I would like to check it out. 

### Steps to reproduce
1. ???
2. now the window shows somewhere where I don't see it. 
3. 

### Server configuration
Operating system: Linux. Ubuntu?
Web server: Apache
Database:mariadb
PHP version: 7.x
ownCloud version: latest. Pulled from the repo. 
Storage backend (external storage): a sata disk. 

### Client configuration
Client version:
ownCloud version 2.6.3 (build 2668)
Git revision f28dd972e941986edc3e1803a25cf067f520b7e3

Operating system: ubuntu 20.04

OS language: mostly written in C. 

Qt version used by client package (Linux only, see also Settings dialog): I can't see the window. 
Using Qt 5.12.7, built against Qt 5.12.7

Client package (From ownCloud or distro) (Linux only):
dpkg -l owncloud
dpkg-query: no packages found matching owncloud

Installation path of client:
/usr/bin/owncloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

Logwindow shows up, main window does not. 

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by TheOneRing** [comment]
what do you get when you invoke it directly?
`/usr/bin/owncloud --logfile - --logdebug`

and does something happen with 
`/usr/bin/owncloud --logfile - --logdebug -s`

**Comment by rewolff** [comment]
Tried the first, and... got the window. (ran the program on my home computer, displays on my work computer 3km away. ) 
I managed to configure a synchronizing a directory.

**Comment by rewolff** [comment]
It's happening again now that I'm home. 

The "with logfile" commandline shows that it is DOING lots of stuff. 

08-15 08:07:31:744 [ info sync.networkjob ]:    OCC::GETFileJob created for "http://prolix/owncloud" + "/pdf/air602/Luat_WiFi_WM_W600/Src/Network/lwip2.0.3/include/lwip/prot/icmp6.h" "OCC::PropagateDownloadFile"

For a gui application I'd expect the window to show and THEN for activity to start. It's now been doing things for two or three minutes without showing the window.

**Comment by herrdeh** [comment]
Similar here with ubuntu 20.04, OC client 2.6.3:
System boots, no OC client GUI, no sync activities. When I launch the OC GUI window manually, it says "not connected to server", within a few seconds the connection is established and the sync performs. 

I cant tell whether this is connected to [that problem.](https://github.com/owncloud/client/issues/8097)

**Comment by rewolff** [comment]
You're reporting something totally different. 

When I start the GUI client, I expect the gui to appear. It doesn't do that unless I specify the (so far) undocumented "-s" switch.

**Comment by TheOneRing** [comment]
> 
> 
> Similar here with ubuntu 20.04, OC client 2.6.3:
> System boots, no OC client GUI, no sync activities. When I launch the OC GUI window manually, it says "not connected to server", within a few seconds the connection is established and the sync performs.
> 
> I cant tell whether this is connected to [that problem.](https://github.com/owncloud/client/issues/8097)

That sounds like your client has auto start not enabled, so it only launches when you explicitly do that.

**Comment by TheOneRing** [comment]
> 
> 
> You're reporting something totally different.
> 
> When I start the GUI client, I expect the gui to appear. It doesn't do that unless I specify the (so far) undocumented "-s" switch.

Since version 2.6.3 the client should open the settings view when the application is directly invoked by the user https://github.com/owncloud/client/blob/v2.6.3/mirall.desktop.in#L4 .
So it should pass the `-s´ flag.
If the application is invoked by the auto start the application is supposed not to open a window.

Before 2.6.3 the application only opened when invoked a second time or when the user interacted the system tray icon.

**Comment by rewolff** [comment]
> Since version 2.6.3 the client

I looked for "help -> about" which is the standard location for gui apps to hide their version info. 

If ound the version info under "general". I have 2.6.3 build 2668.

**Comment by TheOneRing** [comment]
Hmmm
`more /usr/share/applications/owncloud.desktop` does look like the file above?

**Comment by rewolff** [comment]
I'm a bit oldfashioned. 
I started using Unix when you started applications by typing their name into a shell command prompt. 
Nowadays, you have those "desktop managers" that annoy the heck out of me. I don't like mousing over to "activities", clicking, typing "termi" clicking on the terminal application that shows up, then mouse over to the terminal and then type "ssh zebigibos" to open a shell on the machine called "zebigbos". I prefer to mouse over to the blue background of my desktop and type "z" to get that effect. Why people prefer the first: I have no clue. 

The desktop file exists, as actions like "settings" and "quit" near the bottom.

**Comment by TheOneRing** [comment]
Ahh ok, the old behavior was to only show the client the second time it was started, that worked more or less ok when the client was started with the system.
We changed that as it did not provide any feedback to the user, especially on gnome where there might not  be a system tray.
As there are existing scripts and different ways how autostart is implemented on the os we where not able to change what happens when the client gets started with out any arguments, therefor we modified the .desktop files and shortcuts etc.

So I guess there is nothing we can fix right now...

**Comment by rewolff** [comment]
So what you're saying is that I should see the window show up the second time I start the application? Or is that the "old way" and is the new way what I observed: never a window ?

Would it be an idea to make a small user-callable program (script): 
```
#!/bin/sh
# owncloud user-callable application
owncloud-internal -s $* 
```
and then call the owncloud-internal from the .desktop and "autostart when logging in" situations?

**Comment by TheOneRing** [comment]
I'd recommend you to use the -s parameter as not showing the ui when started from the command line is the default behavior.
The old behavior was to never show the ui when ownCloud was started for the fist time,
the new behavior is to show the ui when executed from a graphical environment.

**Comment by TheOneRing** [comment]
With graphical environment I mean people clicking on shiny icons, the behavior in the command line is expected and yes you could write a script to pass -s.
You could also create a bash alias https://opensource.com/article/19/7/bash-aliases

**Comment by rewolff** [comment]
I don't use bash as my shell... 

Didn't you guess. :-)

**Comment by TheOneRing** [comment]
Is this still an issue?

**Comment by rewolff** [comment]
i.e. can you close this? I think so. 

Apparently the behaviour I am seeing is "as intended".  Due to me using a 20 year old window-manager and everybody else moving on, I don't (always???)  have a small owncloud icon on my statusbar. 

So when I don't get that icon, I don't get anything. Anyway, the -s option is a workaround. I can tolerate that for being stubborn with my windowmanager.
