### ISSUE TITLE
VFS is disabled and not included on custom Windows Build.

### ISSUE THREAD

**Issue by ozata** [owncloud/client#8006]
Hello, the last time we built windows successfully with VFS but now when we tried again it comes disabled and not included.

We tried to `self.options.dynamic.registerOption("buildVfsWin", False) ` change this to `True` on "owncloud/owncloud-client/owncloud-client.py" but it tries to get it from the private repo like https://github.com/owncloud/craft-blueprints-owncloud/issues/14 this issue.

Do you have any recommendations how could we include VFS and enable it as the default option in the Windows Build?

**Comment by michaelstingl** [comment]
You can build Windows yourself only with the suffix / placeholder approach. Same as macOS and Linux. There must be an option in the scripts.

**Comment by ozata** [comment]
Is this parameter works for building with KDECraft or MinGW?

**Comment by michaelstingl** [comment]
KDECraft. No idea about the MinGW. It is no longer used.

**Comment by TheOneRing** [comment]
The suffix placeholders should be active by default, but can be disabled in the theme.
https://github.com/owncloud/client/blob/d1eb9afe756b608abaebb00f65bc37455a2f5f91/src/libsync/owncloudtheme.h#L40

**Comment by ozata** [comment]
Thanks.

**Comment by TheOneRing** [comment]
Did it build owncloudsync_vfs_suffix.dll ? Check the logs for 
```08-10 11:11:45:358 [ info gui.application ]:	VFS suffix plugin is available```
And as @michaelstingl said, it will only be the suffix implementation not the windows virtual files.

**Comment by ozata** [comment]
We solved it by altering owncloudtheme.h and theme.cpp, thanks guys, issue closed once again!
