### ISSUE TITLE
Mixed german/english GUI

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8012]
Seen on Centos-7.8 Gnome -- german desktop settings

![image](https://user-images.githubusercontent.com/1108546/90235364-76677480-de21-11ea-9c37-6e9f7e218aff.png)

Some button labels are untranslated. Hide, No, Yes. 
Expected: German translations.

**Comment by TheOneRing** [comment]
The missing translations for yes now indicate a missing or not loaded translations file for Qt, do you ship `qtbase_de.qm` and `qt_de.qm` .

Hide is a custom string and needs to be translated in transifex.

**Comment by jnweiger** [comment]
Ah, this is a gnome desktop. There are no Qt components in the system unless we bring them as part of the ownCloud clent install.
Neither qtbase_de.qm nor qt_de.qm are installed.

**Comment by TheOneRing** [comment]
It shouldn't have to do anything to  do with the system, we always install our own Qt so we also should install our own Qt's translations.

**Comment by jnweiger** [comment]
Ok. No, on Linux, we don't seem to bring our own Qt translations. 

My Ubuntu testsystem has /usr/share/qt5/translations/qtbase_de.qm, but my CentOS has nothing.
We need to have our copies under /opt/ownCloud then...

**Comment by jnweiger** [comment]
A new package ocqt5129-qt5-qttranslations is on the horizon. That should provide us with stock Qt translations.

**Comment by jnweiger** [comment]
Manually installing the translations package gets me the yes / no translations nicely:

![image](https://user-images.githubusercontent.com/1108546/90414071-9b711700-e0af-11ea-9ab5-84f5b07f0942.png)

There are now

/opt/ownCloud/qt-5.12.9/share/qt5/translations/qt_de.qm
/opt/ownCloud/qt-5.12.9/share/qt5/translations/qtbase_de.qm
...

**Comment by TheOneRing** [comment]
so I guess we can close the issue then?

**Comment by jnweiger** [comment]
* [x] That was the first step. 
* [ ] Step two: test drive the new dependency in OBS: https://build.opensuse.org/package/rdiff/isv:ownCloud:desktop:daily:master/owncloud-client?linkrev=base&rev=295
* [ ] Step three: do the same in our internal drone builds.

Then close the issue :-)

**Comment by jnweiger** [comment]
@dschmidt 

Ich kann nun nichtmehr installieren von: https://download.owncloud.com/desktop/ownCloud/daily/2.7/linux/download/

```The following packages have unmet dependencies:
 owncloud-client : Depends: ocqt5129-qttranslations5 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
Was müssen wir tun, damit die neue dependency auch im repo landet?

**Comment by dschmidt** [comment]
@jnweiger rebuild the build images?

**Comment by jnweiger** [comment]
After a long day of studying and hacking, drone finally rebuilds the build images. https://drone.owncloud.services/client/build-linux/1658/

**Comment by jnweiger** [comment]
![image](https://user-images.githubusercontent.com/1108546/90777038-33af0c00-e2fb-11ea-9999-81f0069754cb.png)
Fixed!
