### ISSUE TITLE
Concurrent upload of file does not generate conflict file

### ISSUE THREAD

**Issue by labkode** [owncloud/client#8013]
When creating a file concurrently from two sync clients we expect a conflict to be created, but this not the case.

This scenario is tested in the Smashbox ping pong test, that does the following:
The test has two workers creating and uploading a file in parallel.
After the first sync, one of the workers is going to detect a conflict and should generate a conflict file 
The issue that we see with the test is when the sync is started practically at the same time between both workers and the underlying oc commands are executed in parallel the conflict file is not created and this causes the test to fail, because both workers think they have the correct version of the file but on the server side we only see one version.
So in truth, only one of them has the actual correct version that is present on the server.

The expected behaviour is that one worker will have a local conflict.
 
Attached are the logs on an execution with 2.6.1 against demo.owncloud.com.

[pingpong.zip](https://github.com/owncloud/client/files/5073982/pingpong.zip)

**Comment by hodyroff** [comment]
IMO the expectation is wrong. There is a clear definition WHEN a conflict file will be created. If that definition is not met, it will not be created.
The conflict creation doesn't cover corner cases like this, we do recommend actual file locking for that purpose. 10.5. just got manual file locking in the UI ... and we recommend collaborative editing in the browser to avoid it also. There is also an API for file locking.

**Comment by moscicki** [comment]
Even if only a corner case this leads to data loss. So it is a bit hard to accept as is. Client-side locking can hardly be a solution. Looks like a race condition on the server side.

**Comment by hodyroff** [comment]
The proposed locking is across the ownCloud experience. Predominantly server-side.
I can't follow the data-loss situation. Both versions are successfully uploaded to the server which means that both versions from both clients will be in the versions of the owncloud server. If not, this would indeed be a case, but the case was about a conflict file to be generated - which has a clear definition.
