### ISSUE TITLE
Client sent Delete command to all files mounted as Virtual Files

### ISSUE THREAD

**Issue by GameBurrow** [owncloud/client#8016]
**Warning: Yes I use OwnCloud client with Nextcloud server because it has more features and Virtual File System, but technically as they both use similar standardized webdav protocol. I've been using it like this for a year without any issues.**
I'm hoping you won't just dismiss this issue because of that and will at least look into if there is something that can cause something like this.

### Expected behaviour
This shouldn't have happened

### Actual behaviour
Yesterday morning I suddently started getting reports that most of my files on my Nextcloud server for my account have disappeared. Upon contacting my hosting provider they saw that my Owncloud client sent Delete commands for all of my files.

We found thankly all the files from Trash Bin. What I also found that all files that were deleted were the files that I had in Online mode while I have Virtual Files enabled. All files in offline mode weren't affected.

I myself did not delete any files on my computer (at least not that I'm aware of) and I would have accidentelly deleted all of my own folders, then everything should have been deleted so it makes my think it's some kind of bug in the client.

### Steps to reproduce
N/A

### Server configuration
**Nextcloud** server 19.0.1 hosted by Hetzner.

### Client configuration
Client version:
`OwnCloud 2.6.3 build 13551`

Operating system:
`Windows 10 Pro x64 2004 (build 19041)`

OS language:
`English (UK)`

Installation path of client:
`C:\Program Files (x86)\ownCloud\owncloud.exe`

### Logs

I don't have any logs to provide as my client logging wasn't enabled and I don't have access to server logs (and you problably won't care also as the server is Nextcloud one)

**Comment by michaelstingl** [comment]
Provided information is really not helpful. Please try to reproduce with ownCloud server, collect the logfiles, then we can have a closer look.

**Comment by GameBurrow** [comment]
Yes, I realise I don't have a lot of info because out of the box logging for client is disabled as I learned after it had happened. 
As I don't know what caused it, there's no way for me to reproduce it.

I enabled logging for now and should this happen again, I should have some logs to provide do you.

**Comment by pirunet** [comment]
@GameBurrow What hardware do you use? Do you use Bitlocker? Where ist the synced path located?

**Comment by GameBurrow** [comment]
> @GameBurrow What hardware do you use? Do you use Bitlocker? Where ist the synced path located?

No Bitlocker. Samsung EVO SSD as secondary SATA drive. Path is: `D:\Sepaurg-cloud`.

**Comment by pirunet** [comment]
Thank you. The question seems strange, but are you using a Lenovo notebook? In my case, it happened only on Lenovo-Clients, which can of course also be a coincidence.

**Comment by GameBurrow** [comment]
> Thank you. The question seems strange, but are you using a Lenovo notebook? In my case, it happened only on Lenovo-Clients, which can of course also be a coincidence.

That's an interesting one. I actually do. I use Lenovo Legion Y740-17ICH. 
Just incase though, the secondary drive didn't come with the computer, I added that myself and windows has been reinstalled from scratch also, so it's not how it shipped with.

**Comment by pirunet** [comment]
Ok, possibly a small approach. We've had the problem so far on Lenovo ThinkPad T480, Thinkpad E14 and Thinkpad 14.

@michaelstingl Can a specific driver or device causing the problem?

**Comment by jnweiger** [comment]
@pirunet @GameBurrow seems you have similar issues. As I don't believe in coincidence, here, can you run your clients with logging enabled and report ynthing strange that might be related with attached logfiles please?

Regarding the Lenovo suspicion, I cannot think of anything, how a windows filesystem on this hardware would be different than on other hardware. 
I assume this is on NTFS, right?

If you can, I'd like to invite you to switch to a 2.7.0 owncloud client asap, this one will allow more detailled logging, to better diagnose such cases. We currently have an RC3 in the public beta program.

(I know my advise to enable logging is a bit moot -- after the fact.)

**Comment by pirunet** [comment]
Yes, it's on NTFS.

Maybe I've some more helpful logs now, see here...

https://github.com/owncloud/client/issues/7899#issuecomment-735734059

**Comment by GameBurrow** [comment]
Happened to me again yesterday.  Thankly I managed to catch it before it deleted everything again so the recovery process was bit less painful.

Sadly I don't have any logs again as the owncloud client had unticked the logging setting. But I saw again, that owncloud client sent delete command to all "online only" files in VFS mode.

**Comment by TheOneRing** [comment]
I assume this was the issue fixed in 2.7.3.
Sorry that this issue did not get the attention it deserved...

**Comment by jnweiger** [comment]
@pirunet @GameBurrow can you confirm it is fixed for you with 2.7.x clients?
