### ISSUE TITLE
Owncloud client always shows default english captions

### ISSUE THREAD

**Issue by infosteo** [owncloud/client#8023]
### Expected behaviour
Italian translations not loaded running owncloud client

### Actual behaviour
Owncloud Client always shows default english captions.

### Steps to reproduce
1. Built lastest 2.7 version using KDE Craft (windows)
2. Built nsis setup package
3. Installed setup an PC and run owncloud.exe

### Client configuration
Client version: 2.7 git build (on 2.6 too)
Operating system: Windows 10
OS language: Italian

Installation path of client: c:\program files\Owncloud

**Comment by TheOneRing** [comment]
Should be fixed with https://github.com/owncloud/craft-blueprints-owncloud/commit/8abf8fd310257d5b5a78753fd5d9b28686bfbbdf

**Comment by TheOneRing** [comment]
Fixed in the blueprint
