### ISSUE TITLE
Use .plist settings format on OS X

### ISSUE THREAD

**Issue by karlmikaelskar** [owncloud/client#803]
Dear developers!

As an OS X sysadmin I really do like applications that use plist-files I can manage by MCX or Profile Manager.

Unfortunately the sync client does not store its preferences in ~/Library/Preferences/com.owncloud.desktopclient.plist

Please please look in to this as this will make deploying much easier.

Cheers!

Mikael Johansson

**Comment by TheOneRing** [comment]
No intentions to change the internal format of a non user facing config file.
