### ISSUE TITLE
linux daily builds should have dailyYYYYMMDD in their version

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8034]
While re-testing https://github.com/owncloud/client/issues/8012

Seen on Ubuntu 18.04:
![image](https://user-images.githubusercontent.com/1108546/90775343-06f9f500-e2f9-11ea-97a2-c80a53fa06b7.png)

Seen on CentOS-7.8:
![image](https://user-images.githubusercontent.com/1108546/90777363-97d1d000-e2fb-11ea-83e5-4c42778befe4.png)

**Comment by dschmidt** [comment]
afaict duplicate of #7981

**Comment by jnweiger** [comment]
yep duplicate. I am starting to repeat myself after a month. sorry.
