### ISSUE TITLE
Always full recheck on Google Drive mounts

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#8035]
### Expected behaviour
Check for changed files only

### Actual behaviour
Full recheck when syncing with GD mounts.
Having local, SMB and GD mounts. Only on GD, the client does a full check which takes a while.
I may be wrong, but this has to do with 10.5, because this was not the case up to 10.4.x
It was quick on GD before, but now it looks like it always does a full check on every file.
Maybe this is optical recognizable, as GD is much slower than local and SMB, but is is apparrent

### Steps to reproduce
1. create a GD mount and put many files in
2. let the client sync that mount
3. watch the client regulary

### Server configuration
Operating system: Ubuntu 18.04

Web server: nginx

Database: mariadb

PHP version: 7.3

ownCloud version: 10.5

Storage backend (external storage): local. smb, gd

### Client configuration
Client version: 2.6.3

Operating system: W10x64

OS language: DE

@michaelstingl

**Comment by TheOneRing** [comment]
Was moved to server
