### ISSUE TITLE
Crash dialog cannot be resized

### ISSUE THREAD

**Issue by HanaGemela** [owncloud/client#8042]
Client: 2.7.0v270beta3 (build 1997)
Windows 10

Steps to recreate:
1) Trigger a crash
2) Resize the dialog

Actual result: Not possible
Expected result: Works OK

<img width="365" alt="Screenshot 2020-08-24 at 14 14 44" src="https://user-images.githubusercontent.com/49001702/91043710-5e0f0b00-e614-11ea-943c-08fbe5ca4847.png">

**Comment by michaelstingl** [comment]
> Windows 10

HiDPI settings in the Win display preferences?

**Comment by jnweiger** [comment]
## re-tested with ownCloud 2.7.0v270rc1 (build 2254)
"C:\Program Files\ownCloud\owncloud.exe" --debug
-> tray icon -> right click -> Crash now - Div by zero

![image](https://user-images.githubusercontent.com/1108546/96514749-64141780-1264-11eb-8c62-fbaa7cc053d9.png)

Cannot find a way to resize this windows. it is still fixed size. 
Although large enough to see the crash number.

**Comment by TheOneRing** [comment]
there are not many reasons to resize the dialog, but as thx to the changes the window is displayed correctly the issue is fixed
