### ISSUE TITLE
VFS showing downloaded files as 0KB

### ISSUE THREAD

**Issue by sandstormkeshav** [owncloud/client#8043]
### Expected behaviour
With double-clicking on an unsynced file it should be downloaded automatically and open afterwards.

### Actual behaviour
Double-clicking on an unsynced file results in an incomplete (?) download. The files is downloaded and marked as synced (green hook on white background). The file size is shown with 0kb. Opening the file results in an error-message.
Same issue is ocurring while copying unsynced files.

### Steps to reproduce
Open ownCloud folder
Double-Click on unsynced file
File opens with error-message

### Server configuration
Operating system:
Synology Disk Station DS216+II
DSM 6.2.2-24922 Update 4

Web server:
Apache HTTP Server 2.2

Database:
MariaDB 10

PHP version:
5.6

ownCloud version:
10.0.7.2

### Client configuration
Client version: 2.6.3

Operating system: Windows 10 x64 

OS language: English

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

2. Web server error log:
05-02 11:18:07:882 [ debug sync.networkjob ] [ OCC::AbstractNetworkJob::slotFinished ]: Network job OCC::GETFileJob finished for “/Testfile.txt”
05-02 11:18:07:882 [ debug sync.networkjob.get ] [ OCC::GETFileJob::slotReadyRead ]: Actually finished!
05-02 11:18:08:862 [ info gui.folderwatcher ]: Detected changes in paths: QSet(“C:/Users/Frank/ownCloud/Testfile.txt”)
05-02 11:18:08:862 [ debug sync.localdiscoverytracker ] [ OCC::LocalDiscoveryTracker::addTouchedPath ]: inserted touched “Testfile.txt”
05-02 11:18:08:862 [ debug sync.database.sql ] [ OCC::SqlQuery::bindValue ]: SQL bind 1 QVariant(qlonglong, -6894368967105351058)
05-02 11:18:08:865 [ debug sync.database.sql ] [ OCC::SqlQuery::exec ]: SQL exec “SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize, ignoredChildrenRemote, contentchecksumtype.name || ‘:’ || contentChecksum FROM metadata LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE phash=?1”
05-02 11:18:08:865 [ info gui.folder ]: Ignoring spurious notification for file “Testfile.txt”
05-02 11:18:38:241 [ info sync.accessmanager ]: 6 “PROPFIND” “https://[DomainDeletedForPrivacyReasons]/owncloud/remote.php/dav/files/Frank/” has X-Request-ID “42f72f49-bf4e-4be5-9d9c-7347cf3d0a9e”
05-02 11:18:38:241 [ debug sync.cookiejar ] [ OCC::CookieJar::cookiesForUrl ]: QUrl(“https://[DomainDeletedForPrivacyReasons]/owncloud/remote.php/dav/files/Frank/”) requests: (QNetworkCookie(“oc_sessionPassphrase=iZe00tYVj8AeMeoRLfLYZ3NdyZWrYADhgw7kKH91eudfq6ubW9jJ8s6jzQhZBBnNDYw%2FJKTxbyhbC%2FOWtm2Ui2J9RUsUw%2Fen%2BTF5d4sIRPP2BTkXFFIofpT8oXcwPUrH; secure; HttpOnly; domain=[DomainDeletedForPrivacyReasons]; path=/owncloud”), QNetworkCookie(“oc0l7t9dbwu1=vh28b6q4ai085va6cilic53215; secure; HttpOnly; domain=[DomainDeletedForPrivacyReasons]; path=/owncloud”))
05-02 11:18:38:241 [ info sync.networkjob ]: OCC::PropfindJob created for “https://[DomainDeletedForPrivacyReasons]/owncloud/” + “/” “OCC::QuotaInfo”
05-02 11:18:38:822 [ info sync.networkjob.propfind ]: PROPFIND of QUrl(“https://[DomainDeletedForPrivacyReasons]/owncloud/remote.php/dav/files/Frank/”) FINISHED WITH STATUS “OK”
05-02 11:18:38:822 [ debug sync.networkjob ] [ OCC::AbstractNetworkJob::slotFinished ]: Network job OCC::PropfindJob finished for “/”
05-02 11:18:40:302 [ info gui.activity ]: Start fetching activities for “[DomainDeletedForPrivacyReasons] (Frank Drieslein)”
05-02 11:18:40:302 [ info sync.accessmanager ]: 2 “” “https://[DomainDeletedForPrivacyReasons]/owncloud/ocs/v1.php/cloud/activity?page=0&pagesize=100&format=json” has X-Request-ID “05da8581-f9a1-455b-984b-4d06f04b76cf”
05-02 11:18:40:302 [ debug sync.cookiejar ] [ OCC::CookieJar::cookiesForUrl ]: QUrl(“https://[DomainDeletedForPrivacyReasons]/owncloud/ocs/v1.php/cloud/activity?page=0&pagesize=100&format=json”) requests: (QNetworkCookie(“oc_sessionPassphrase=iZe00tYVj8AeMeoRLfLYZ3NdyZWrYADhgw7kKH91eudfq6ubW9jJ8s6jzQhZBBnNDYw%2FJKTxbyhbC%2FOWtm2Ui2J9RUsUw%2Fen%2BTF5d4sIRPP2BTkXFFIofpT8oXcwPUrH; secure; HttpOnly; domain=[DomainDeletedForPrivacyReasons]; path=/owncloud”), QNetworkCookie(“oc0l7t9dbwu1=vh28b6q4ai085va6cilic53215; secure; HttpOnly; domain=[DomainDeletedForPrivacyReasons]; path=/owncloud”))

**Comment by michaelstingl** [comment]
This was reported before:
https://central.owncloud.org/t/empty-txt-files-when-using-virtual-file-system/27181

But we weren't able to reproduce yet. We'd need a client log from the time of the incident to investigate what's going on.

Here you can find more information:
https://doc.owncloud.com/desktop/troubleshooting.html#obtaining-the-client-log-file

Please send log to `apps-<at>-owncloud.com`
