### ISSUE TITLE
NSIS Setup creates Start menu shortcut that points to <program files>\owncloud\bin\owncloud.exe

### ISSUE THREAD

**Issue by infosteo** [owncloud/client#8045]
### Expected behaviour
After installation setup, I can't run owncloud from windws start menu because
the shortcout points to 
<program files>\owncloud\**bin**\owncloud.exe
On start menu, owncloud icon is obviously "blank"

### Actual behaviour
owncloud.exe is correctly presenti in 
<program files>\owncloud\

### Steps to reproduce
1. Run Setup
2. open windows start menu
3. click to run owncloud.exe
4. nothing happens and windows opens "browse for app" dialog.

### Client configuration
Client version: 2.7

Operating system: Windows 10

**Comment by TheOneRing** [comment]
Was fixed in https://github.com/owncloud/craft-blueprints-owncloud/commit/9601a53c58a3538e6a7700815032a965d768e34a
