### ISSUE TITLE
MacOS: When using recent daily builds of 2.70 Finder Integration for Share does not show a Share Dialog

### ISSUE THREAD

**Issue by dirkpape** [owncloud/client#8046]
### Expected behaviour
When using the context menu "ownCloud --> Share" (German: Teilen) on a file in a synched folder a dialog should open to let share the file or folder

### Actual behaviour
Instead the owncloud client window opens showing the main window with the formerly selected account.
There is no dialog to name user or group or create a share

### Steps to reproduce
1. Have Finder integration active and select a file in Finder which is synched by owncloud client
2. use contextual menu and select "Teilen" (Share)

### Server configuration
Operating system:
Debian 18

Web server: 
apache

Database:
mysql 10.1.44

PHP version:
7.4.9

ownCloud version:
nextcloud 19.0.2

Storage backend (external storage):
none

### Client configuration
Client version:
Version 2.7.0 (build 2046)

Operating system:
MacOS Catalina Version 10.15.6

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
/Applications

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by michaelstingl** [comment]
Thanks for the feedback! Known issue in the beta3. Beta4 planned for next week.
