### ISSUE TITLE
[QA][OCIS] Spurious authentication error in selective sync list

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8060]
tested with
 * ocis-1.0.0-rc1 via https://gitea.owncloud.services/jw/hetzner/src/branch/master/make_ocis_eos_test.sh
 * docker run --rm -ti -p 9200:9200 -e REVA_FRONTEND_UPLOAD_MAX_CHUNK_SIZE=100000000 owncloud/ocis:1.0.0-rc1
 * and desktop daily (20200908) client ownCloud version 2.7.0 (build 2058)

Login as user einstein to an ocis server, wait 10 minutes, collapse and expand the selective sync folder list
An error message appears. Either within the list or instead of the list:

![image](https://user-images.githubusercontent.com/1108546/92522868-adae2300-f21f-11ea-9654-0348303d39d3.png)

A force sync syncs without problem. The error remains.

**Comment by michaelstingl** [comment]
@jnweiger log with HTTP logging available?

**Comment by TheOneRing** [comment]
Duplicate https://github.com/owncloud/ocis/issues/576#issuecomment-692643570
