### ISSUE TITLE
[QA][OCIS] Double negation deselect requester is confusing

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8061]
tested with
 * ocis-1.0.0-rc1 via https://gitea.owncloud.services/jw/hetzner/src/branch/master/make_ocis_eos_test.sh
 * and desktop daily (20200908) testpilotcloud version 2.7.0 (build 2059)

![image](https://user-images.githubusercontent.com/1108546/92524172-ec44dd00-f221-11ea-9919-e111655d00cf.png)

The instruction is a double negation: "Deselect remote folders you do not wish to synchronize"
Suggest to change to "Select remote folders that you wish to synchronize"

The double negation is especially confusing, when initially all folders are already deselected.
Without selecting any, just pressing Okay, the next screen has 
![image](https://user-images.githubusercontent.com/1108546/92524581-a2a8c200-f222-11ea-89bf-f5dacc79f553.png)

That indicates that all are selected "(*) Synchronize everything ..." but that is not the case. Only the root folder gets synchronized.

**Comment by TheOneRing** [comment]
~~@michaelstingl can we remove the branding switch that opens this dialog directly?~~
Apparently we can't. https://chat.owncloud.com/channel/desktop-internal?msg=QjtwsZtCZjx5zSHxw

anyhow the current workflow is an ugly hack and a horrible ux...

**Comment by jnweiger** [comment]
Reference: https://github.com/owncloud/ownbrander/issues/942
