### ISSUE TITLE
Desktop client crashes on Windows 7 with virtual file support enabled

### ISSUE THREAD

**Issue by netzimon** [owncloud/client#8070]
### Expected behaviour
Synchronizing shared folders using virtual file support on a Windows 7 machine

### Actual behaviour
OwnCloud app crashes when starting to download/create virtual files on local machine

### Steps to reproduce
1. Install latest version of OwnCloud client
2. Connect account, selecting virtual file support
3. OC client crashes after going through all the files that need to be synchronized and when its is about to create the first file/folder on local machine

### Notes
1. When installing the account without virtual file support the files are synchronized just fine.
2. When installing a previous version of the OC client (2.5.4) the virtual files are created without error, however, when attempting to open a file (i.e. to download the actual file from the server) the client asks to be updated to the latest version. After the update, it crashes when trying to access a file.
3. Attempted to run the OC client as administrator as well as in compatibility mode, but still crashes.

### Server configuration
Operating system: CentOS 7.8
Web server: Apache/2.4.6 (CentOS)
Database: mysql  Ver 15.1 Distrib 5.5.65-MariaDB
PHP version: PHP 7.2.33
ownCloud version: ownCloud 10.5.0
Storage backend (external storage): No external storage

### Client configuration
Client version: 2.6.3
Operating system: Windows 7 SP1
OS language: Spanish
Installation path of client: C:\Program Files (x86)\ownCloud\

### Logs
Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile (server name, folder and file names have been removed - including last lines before OC client crashed): 
09-10 16:06:10:594 [ info sync.networkjob ]:	OCC::LsColJob created for "https://***.*****.com" + "/UIO Analisis Quito/2007/UIAN-UIO/CASO CAT/REQUERIMIENTOS" "OCC::DiscoverySingleDirectoryJob"
09-10 16:06:10:637 [ info sync.networkjob.lscol ]:	LSCOL of QUrl("https://***.*****.com/remote.php/dav/files/WPPA7/****FOLDER****") FINISHED WITH STATUS "OK"
09-10 16:06:10:638 [ info sync.csync.updater ]:	Checking for rename based on fileid 00073453ocmtos9cpfvk
09-10 16:06:10:638 [ info sync.csync.updater ]:	file: ****FILE****.wbk.owncloud, instruction: INSTRUCTION_NEW <<=
09-10 16:06:10:638 [ info sync.csync.updater ]:	Checking for rename based on fileid 00073454ocmtos9cpfvk
09-10 16:06:10:638 [ info sync.csync.updater ]:	file: ****FILE****.wbk.owncloud, instruction: INSTRUCTION_NEW <<=
09-10 16:06:10:639 [ info sync.csync.updater ]:	Checking for rename based on fileid 00073455ocmtos9cpfvk
09-10 16:06:10:639 [ info sync.csync.updater ]:	file: ****FILE****.doc.owncloud, instruction: INSTRUCTION_NEW <<=
09-10 16:06:10:639 [ info sync.csync.updater ]:	Checking for rename based on fileid 00073456ocmtos9cpfvk
09-10 16:06:10:639 [ info sync.csync.updater ]:	file: ****FILE****.doc.owncloud, instruction: INSTRUCTION_NEW <<=
09-10 16:06:10:639 [ info sync.csync.updater ]:	Checking for rename based on fileid 00073457ocmtos9cpfvk
09-10 16:06:10:639 [ info sync.csync.updater ]:	file: ****FILE****.doc.owncloud, instruction: INSTRUCTION_NEW <<=
09-10 16:06:10:639 [ info sync.csync.updater ]:	 <= Closing walk for UIO Analisis Quito/2007/UIAN-UIO/CASO CAT/REQUERIMIENTOS with read_from_db 0
09-10 16:06:10:639 [ info sync.csync.updater ]:	Checking for rename based on fileid 00073379ocmtos9cpfvk
09-10 16:06:10:639 [ info sync.csync.updater ]:	file: ****FOLDER****, instruction: INSTRUCTION_NEW <<=
09-10 16:06:10:639 [ info sync.accessmanager ]:	6 "PROPFIND" "https://***.*****.com/remote.php/dav/files/****FOLDER****" has X-Request-ID "7e388ce5-085d-4064-b408-3b18950aecf7"
09-10 16:06:10:640 [ info sync.networkjob ]:	OCC::LsColJob created for "https://***.*****.com" + "/****FOLDER****" "OCC::DiscoverySingleDirectoryJob"

**Comment by TheOneRing** [comment]
Hi @netzimon could you send the full log to `apps-<at>-owncloud.com`
Also when the client crashes you usually get a dialog to report the crash, could you report the crash again and send me the crash id that gets displayed, that way I'll be able to see exactly where in the code your client crashed.

**Comment by netzimon** [comment]
We decided to upgrade the OS to Windows 10 on the computers where the desktop was installed, which solved the problem. Unfortunately I wasn't able to get the log file output before we did the upgrade
