### ISSUE TITLE
Cannot log in OCIS 1.0.0. RC1 server using Desktop Client v.2.7.0

### ISSUE THREAD

**Issue by davitol** [owncloud/client#8079]
### Expected behaviour

User should be able to log in the server via Desktop Client

### Actual behaviour

User cannot log in

<img width="1031" alt="Screenshot 2020-09-14 at 11 17 39" src="https://user-images.githubusercontent.com/10596560/93076506-ba9b9e00-f687-11ea-9e18-32d800c6cb1f.png">

### Steps to reproduce
1. Install ocis-1.0.0-rc1 via https://github.com/owncloud-docker/compose-playground/blob/master/examples/hetzner-deploy/make_ocis_eos_compose_test.sh
2. Add server to Desktop Client and try to authenticate

### Client configuration
Client version: 2.7.0
Operating system: Mac OSX Catalina 10.15.0
OS language: English
Installation path of client: /Applications/owncloud.app/Contents/MacOS/owncloud

### Logs

`09-14 11:16:29:156 [ info gui.application ]:    Using "en_ES" translation
09-14 11:16:29:163 [ info gui.application ]:    VFS suffix plugin is available
09-14 11:16:29:254 [ info gui.socketapi ]:      Loaded shell extension: "pluginkit" "-a /Applications/owncloud.app/Contents/PlugIns/FinderSyncExt.appex/" ""
09-14 11:16:30:634 [ info gui.socketapi ]:      Loaded shell extension: "pluginkit" "-e use -i com.owncloud.desktopclient.FinderSyncExt" ""
09-14 11:16:30:634 [ info gui.socketapi ]:      server started, listening at  "com.owncloud.desktopclient.socketApi"
09-14 11:16:30:635 [ info gui.folder.manager ]: setting remote poll timer interval to 30000 msec
09-14 11:16:30:787 [ debug gui.activity ]       [ OCC::ActivitySettings::setNotificationRefreshInterval ]:      Starting Notification refresh timer with  300  sec interval
09-14 11:16:30:836 [ debug gui.updater ]        [ OCC::Updater::create ]:       QUrl("https://updates.owncloud.com/client/?version=2.7.0.0&platform=macos&oem=ownCloud&versionsuffix=")
09-14 11:16:30:843 [ warning default ]: QObject::connect: signal not found in QPushButton
09-14 11:16:30:870 [ info gui.application ]:    Tray menu workarounds: noabouttoshow: true fakedoubleclick: false showhide: false manualvisibility: true
09-14 11:16:31:055 [ info gui.folder.manager ]: Setup folders from  "/Users/davidtoledocelada/Library/Preferences/ownCloud/folders" (migration)
09-14 11:16:31:055 [ info sync.clientproxy ]:   Set proxy configuration to use system configuration
09-14 11:16:31:192 [ info gui.application ]:    No configured folders yet, starting setup wizard
09-14 11:16:32:535 [ debug gui.wizard ] [ OCC::OwncloudWizard::slotCurrentPageChanged ]:        Current Wizard page changed to  0
09-14 11:16:33:099 [ info gui.socketapi ]:      New connection SocketApiSocket(0x7fc312baa540)
09-14 11:16:33:101 [ info gui.socketapi ]:      Received SocketAPI message <-- "GET_STRINGS:" from SocketApiSocket(0x7fc312baa540)
09-14 11:16:33:101 [ info gui.socketapi ]:      Sending SocketAPI message --> "GET_STRINGS:BEGIN" to SocketApiSocket(0x7fc312baa540)
09-14 11:16:33:102 [ info gui.socketapi ]:      Sending SocketAPI message --> "STRING:SHARE_MENU_TITLE:Share..." to SocketApiSocket(0x7fc312baa540)
09-14 11:16:33:102 [ info gui.socketapi ]:      Sending SocketAPI message --> "STRING:CONTEXT_MENU_TITLE:ownCloud" to SocketApiSocket(0x7fc312baa540)
09-14 11:16:33:103 [ info gui.socketapi ]:      Sending SocketAPI message --> "STRING:COPY_PRIVATE_LINK_MENU_TITLE:Copy private link to clipboard" to SocketApiSocket(0x7fc312baa540)
09-14 11:16:33:104 [ info gui.socketapi ]:      Sending SocketAPI message --> "STRING:EMAIL_PRIVATE_LINK_MENU_TITLE:Send private link by email..." to SocketApiSocket(0x7fc312baa540)
09-14 11:16:33:104 [ info gui.socketapi ]:      Sending SocketAPI message --> "STRING::" to SocketApiSocket(0x7fc312baa540)
09-14 11:16:33:106 [ info gui.socketapi ]:      Sending SocketAPI message --> "GET_STRINGS:END" to SocketApiSocket(0x7fc312baa540)
09-14 11:16:33:993 [ info gui.updater ]:        Checking for available update
09-14 11:16:33:994 [ info sync.accessmanager ]: 2 "" "https://updates.owncloud.com/client/?version=2.7.0.0&platform=macos&oem=ownCloud&versionsuffix=" has X-Request-ID "247b86bf-9c33-4536-9527-d10bdcfb21e5"
09-14 11:16:33:994 [ info sync.httplogger ]:    "247b86bf-9c33-4536-9527-d10bdcfb21e5: Request: GET https://updates.owncloud.com/client/?version=2.7.0.0&platform=macos&oem=ownCloud&versionsuffix= Header: { User-Agent: Mozilla/5.0 (Macintosh) mirall/2.7.0 (ownCloud, osx-19.5.0 ClientArchitecture: x86_64 OsArchitecture: x86_64), Accept: */*, X-Request-ID: 247b86bf-9c33-4536-9527-d10bdcfb21e5, } Data: []"
09-14 11:16:33:994 [ debug sync.cookiejar ]     [ OCC::CookieJar::cookiesForUrl ]:      QUrl("https://updates.owncloud.com/client/?version=2.7.0.0&platform=macos&oem=ownCloud&versionsuffix=") requests: ()
@                                                                                                                                                                                    @                                                                                                                                                                                    @                                                                                                                                                                                    @
/1970
09-14 11:17:00:689 [ debug gui.wizard ] [ OCC::OwncloudWizard::appendToConfigurationLog ]:      Setup-Log:  "<font color=\"green\">Successfully connected to https://168.119.56.223:9200: ownCloud version 10.0.9 (10.0.9.5-ownCloud)</font><br/><br/>"
09-14 11:17:00:689 [ info sync.networkjob.determineauthtype ]:  Determining auth type for QUrl("https://168.119.56.223:9200/remote.php/webdav/")
09-14 11:17:00:689 [ info sync.accessmanager ]: 6 "PROPFIND" "https://168.119.56.223:9200/remote.php/webdav/" has X-Request-ID "c12ecfff-8e92-44cc-b998-0434686c67f6"
09-14 11:17:00:689 [ info sync.httplogger ]:    "c12ecfff-8e92-44cc-b998-0434686c67f6: Request: PROPFIND https://168.119.56.223:9200/remote.php/webdav/ Header: { User-Agent: Mozilla/5.0 (Macintosh) mirall/2.7.0 (ownCloud, osx-19.5.0 ClientArchitecture: x86_64 OsArchitecture: x86_64), Accept: */*, Content-Type: text/xml; charset=utf-8, X-Request-ID: c12ecfff-8e92-44cc-b998-0434686c67f6, } Data: []"
09-14 11:17:00:689 [ debug sync.cookiejar ]     [ OCC::CookieJar::cookiesForUrl ]:      QUrl("https://168.119.56.223:9200/remote.php/webdav/") requests: ()
09-14 11:17:00:690 [ info sync.networkjob ]:    OCC::SimpleNetworkJob created for "https://168.119.56.223" + "" ""
09-14 11:17:00:690 [ debug sync.networkjob ]    [ OCC::AbstractNetworkJob::slotFinished ]:      Network job OCC::CheckServerJob finished for "status.php"
09-14 11:17:00:737 [ info sync.httplogger ]:    "c12ecfff-8e92-44cc-b998-0434686c67f6: Response: PROPFIND https://168.119.56.223:9200/remote.php/webdav/ Header: { Content-Length: 0, Date: Mon, 14 Sep 2020 09:17:00 GMT, Www-Authenticate: Basic realm=\"168.119.56.223:9200\", Bearer realm=\"168.119.56.223:9200\", } Data: []"
09-14 11:17:00:738 [ info sync.networkjob.determineauthtype ]:  Auth type for QUrl("https://168.119.56.223:9200/remote.php/webdav/") is OCC::DetermineAuthTypeJob::AuthType::OAuth
09-14 11:17:00:739 [ info sync.accessmanager ]: 2 "" "https://168.119.56.223:9200/.well-known/openid-configuration" has X-Request-ID "615ba707-64ac-49b3-bcbb-04d82dc3c8ce"
09-14 11:17:00:739 [ info sync.httplogger ]:    "615ba707-64ac-49b3-bcbb-04d82dc3c8ce: Request: GET https://168.119.56.223:9200/.well-known/openid-configuration Header: { User-Agent: Mozilla/5.0 (Macintosh) mirall/2.7.0 (ownCloud, osx-19.5.0 ClientArchitecture: x86_64 OsArchitecture: x86_64), Accept: */*, X-Request-ID: 615ba707-64ac-49b3-bcbb-04d82dc3c8ce, } Data: []"
09-14 11:17:00:739 [ debug sync.cookiejar ]     [ OCC::CookieJar::cookiesForUrl ]:      QUrl("https://168.119.56.223:9200/.well-known/openid-configuration") requests: ()
09-14 11:17:00:740 [ info sync.networkjob ]:    OCC::SimpleNetworkJob created for "https://168.119.56.223" + "" ""
09-14 11:17:01:697 [ debug gui.wizard ] [ OCC::OwncloudWizard::slotCurrentPageChanged ]:        Current Wizard page changed to  2
09-14 11:17:01:697 [ debug sync.networkjob ]    [ OCC::AbstractNetworkJob::slotFinished ]:      Network job OCC::SimpleNetworkJob finished for ""
09-14 11:17:01:808 [ info sync.httplogger ]:    "615ba707-64ac-49b3-bcbb-04d82dc3c8ce: Response: GET https://168.119.56.223:9200/.well-known/openid-configuration Header: { Access-Control-Allow-Origin: *, Cache-Control: no-cache, no-store, max-age=0, must-revalidate, value, Content-Length: 1803, Content-Type: application/json; encoding=utf-8, Date: Mon, 14 Sep 2020 09:17:01 GMT, Expires: Thu, 01 Jan 1970 00:00:00 GMT, Last-Modified: Mon, 14 Sep 2020 09:17:01 GMT, Vary: Origin, X-Content-Type-Options: nosniff, X-Frame-Options: DENY, X-Konnectd-Version: 0.0.0, X-Xss-Protection: 1; mode=block, } Data: [{\n  \"issuer\": \"https://168.119.56.223:9200\",\n  \"authorization_endpoint\": \"https://168.119.56.223:9200/signin/v1/identifier/_/authorize\",\n  \"token_endpoint\": \"https://168.119.56.223:9200/konnect/v1/token\",\n  \"userinfo_endpoint\": \"https://168.119.56.223:9200/konnect/v1/userinfo\",\n  \"end_session_endpoint\": \"https://168.119.56.223:9200/signin/v1/identifier/_/endsession\",\n  \"check_session_iframe\": \"https://168.119.56.223:9200/konnect/v1/session/check-session.html\",\n  \"jwks_uri\": \"https://168.119.56.223:9200/konnect/v1/jwks.json\",\n  \"scopes_supported\": [\n    \"openid\",\n    \"offline_access\",\n    \"profile\",\n    \"email\",\n    \"konnect/uuid\",\n    \"konnect/raw_sub\"\n  ],\n  \"response_types_supported\": [\n    \"id_token token\",\n    \"id_token\",\n    \"code id_token\",\n    \"code id_token token\"\n  ],\n  \"subject_types_supported\": [\n    \"public\"\n  ],\n  \"id_token_signing_alg_values_supported\": [\n    \"RS512\",\n    \"PS256\",\n    \"PS384\",\n    \"PS512\",\n    \"RS256\",\n    \"RS384\"\n  ],\n  \"userinfo_signing_alg_values_supported\": [\n    \"RS512\",\n    \"PS256\",\n    \"PS384\",\n    \"PS512\",\n    \"RS256\",\n    \"RS384\"\n  ],\n  \"request_object_signing_alg_values_supported\": [\n    \"ES256\",\n    \"ES384\",\n    \"ES512\",\n    \"RS256\",\n    \"RS384\",\n    \"RS512\",\n    \"PS256\",\n    \"PS384\",\n    \"PS512\",\n    \"none\",\n    \"EdDSA\"\n  ],\n  \"token_endpoint_auth_methods_supported\": [\n    \"client_secret_basic\",\n    \"none\"\n  ],\n  \"token_endpoint_auth_signing_alg_values_supported\": [\n    \"RS512\",\n    \"PS256\",\n    \"PS384\",\n    \"PS512\",\n    \"RS256\",\n    \"RS384\"\n  ],\n  \"claims_parameter_supported\": true,\n  \"claims_supported\": [\n    \"iss\",\n    \"sub\",\n    \"aud\",\n    \"exp\",\n    \"iat\",\n    \"name\",\n    \"family_name\",\n    \"given_name\",\n    \"email\",\n    \"email_verified\"\n  ],\n  \"request_parameter_supported\": true,\n  \"request_uri_parameter_supported\": false\n}\n]"
09-14 11:17:01:872 [ debug sync.networkjob ]    [ OCC::AbstractNetworkJob::slotFinished ]:      Network job OCC::SimpleNetworkJob finished for ""`

**Comment by TheOneRing** [comment]
Could you describe what happened? Can't log in is a bit general.
Also could you try to include line breaks in the next log :D

**Comment by davitol** [comment]
Screenshots in order:

<img width="978" alt="Screenshot 2020-09-14 at 13 21 53" src="https://user-images.githubusercontent.com/10596560/93080241-a9ee2680-f68d-11ea-92b1-c115088e39ce.png">
<img width="975" alt="Screenshot 2020-09-14 at 13 22 06" src="https://user-images.githubusercontent.com/10596560/93080252-ace91700-f68d-11ea-8cf4-1bc3888b9ff8.png">
<img width="1280" alt="Screenshot 2020-09-14 at 13 23 00" src="https://user-images.githubusercontent.com/10596560/93080254-ae1a4400-f68d-11ea-92cb-6861eadafbb5.png">
<img width="1280" alt="Screenshot 2020-09-14 at 13 23 09" src="https://user-images.githubusercontent.com/10596560/93080259-af4b7100-f68d-11ea-8490-e1dd4fb9e297.png">
<img width="1275" alt="Screenshot 2020-09-14 at 13 23 37" src="https://user-images.githubusercontent.com/10596560/93080261-af4b7100-f68d-11ea-844f-d221717c6c3c.png">


> Could you describe what happened? Can't log in is a bit general.

The new account is not added and the Desktop Client gets frozen. I am not able to click in any section in the last screenshot

**Comment by davitol** [comment]
Highlight that log above says:


`{ Access-Control-Allow-Origin: *, Cache-Control: no-cache, no-store, max-age=0, must-revalidate, value, Content-Length: 1803, Content-Type: application/json; encoding=utf-8, Date: Mon, 14 Sep 2020 09:17:01 GMT, Expires: Thu, 01 Jan 1970 00:00:00 GMT, Last-Modified: Mon, 14 Sep 2020 09:17:01 GMT, Vary: Origin, X-Content-Type-Options: nosniff, X-Frame-Options: DENY, X-Konnectd-Version: 0.0.0, X-Xss-Protection: 1; mode=block, } `

Date from the past, not sure if it affects

**Comment by TheOneRing** [comment]
Which client build is that? It doesn't look like beta3 or 4.

**Comment by TheOneRing** [comment]
Also the ip is public reachable, I just logged in successful

**Comment by davitol** [comment]
Version 2.7.0. Built from Git revision 6f0608 on Jul 2 2020, 19:23:32 using Qt 5.12.7, OpenSSL 1.1.1g 21 Apr 2020

**Comment by michaelstingl** [comment]
The part of the log you posted shows no problem. I extracted the HTTP parts:

```
09-14 11:16:33:994 [ info sync.httplogger ]: "247b86bf-9c33-4536-9527-d10bdcfb21e5: 
Request: GET https://updates.owncloud.com/client/?version=2.7.0.0&platform=macos&oem=ownCloud&versionsuffix= 
Header: { User-Agent: Mozilla/5.0 (Macintosh) mirall/2.7.0 (ownCloud, 
osx-19.5.0 ClientArchitecture: x86_64 OsArchitecture: x86_64), 
Accept: */*, 
X-Request-ID: 247b86bf-9c33-4536-9527-d10bdcfb21e5, 
} 
Data: []" 

09-14 11:17:00:689 [ info sync.httplogger ]: "c12ecfff-8e92-44cc-b998-0434686c67f6: 
Request: PROPFIND https://168.119.56.223:9200/remote.php/webdav/ 
Header: { User-Agent: Mozilla/5.0 (Macintosh) mirall/2.7.0 (ownCloud, 
osx-19.5.0 ClientArchitecture: x86_64 OsArchitecture: x86_64), 
Accept: */*, 
Content-Type: text/xml; charset=utf-8, 
X-Request-ID: c12ecfff-8e92-44cc-b998-0434686c67f6, 
} 
Data: []" 

09-14 11:17:00:737 [ info sync.httplogger ]: "c12ecfff-8e92-44cc-b998-0434686c67f6: 
Response: PROPFIND https://168.119.56.223:9200/remote.php/webdav/ 
Header: { Content-Length: 0, 
Date: Mon, 
14 Sep 2020 09:17:00 GMT, 
Www-Authenticate: Basic realm=\"168.119.56.223:9200\", 
Bearer realm=\"168.119.56.223:9200\", 
} 
Data: []" 

09-14 11:17:00:739 [ info sync.httplogger ]: "615ba707-64ac-49b3-bcbb-04d82dc3c8ce: 
Request: GET https://168.119.56.223:9200/.well-known/openid-configuration 
Header: { User-Agent: Mozilla/5.0 (Macintosh) mirall/2.7.0 (ownCloud, 
osx-19.5.0 ClientArchitecture: x86_64 OsArchitecture: x86_64), 
Accept: */*, 
X-Request-ID: 615ba707-64ac-49b3-bcbb-04d82dc3c8ce, 
} 
Data: []" 

09-14 11:17:01:808 [ info sync.httplogger ]: "615ba707-64ac-49b3-bcbb-04d82dc3c8ce: 
Response: GET https://168.119.56.223:9200/.well-known/openid-configuration 
Header: { Access-Control-Allow-Origin: *, 
Cache-Control: no-cache, 
no-store, 
max-age=0, 
must-revalidate, 
value, 
Content-Length: 1803, 
Content-Type: application/json; encoding=utf-8, 
Date: Mon, 
14 Sep 2020 09:17:01 GMT, 
Expires: Thu, 
01 Jan 1970 00:00:00 GMT, 
Last-Modified: Mon, 
14 Sep 2020 09:17:01 GMT, 
Vary: Origin, 
X-Content-Type-Options: nosniff, 
X-Frame-Options: DENY, 
X-Konnectd-Version: 0.0.0, 
X-Xss-Protection: 1; mode=block, 
} 
Data: [{
 \"issuer\": \"https://168.119.56.223:9200\",
 \"authorization_endpoint\": \"https://168.119.56.223:9200/signin/v1/identifier/_/authorize\",
 \"token_endpoint\": \"https://168.119.56.223:9200/konnect/v1/token\",
 \"userinfo_endpoint\": \"https://168.119.56.223:9200/konnect/v1/userinfo\",
 \"end_session_endpoint\": \"https://168.119.56.223:9200/signin/v1/identifier/_/endsession\",
 \"check_session_iframe\": \"https://168.119.56.223:9200/konnect/v1/session/check-session.html\",
 \"jwks_uri\": \"https://168.119.56.223:9200/konnect/v1/jwks.json\",
 \"scopes_supported\": [
 \"openid\",
 \"offline_access\",
 \"profile\",
 \"email\",
 \"konnect/uuid\",
 \"konnect/raw_sub\"
 ],
 \"response_types_supported\": [
 \"id_token token\",
 \"id_token\",
 \"code id_token\",
 \"code id_token token\"
 ],
 \"subject_types_supported\": [
 \"public\"
 ],
 \"id_token_signing_alg_values_supported\": [
 \"RS512\",
 \"PS256\",
 \"PS384\",
 \"PS512\",
 \"RS256\",
 \"RS384\"
 ],
 \"userinfo_signing_alg_values_supported\": [
 \"RS512\",
 \"PS256\",
 \"PS384\",
 \"PS512\",
 \"RS256\",
 \"RS384\"
 ],
 \"request_object_signing_alg_values_supported\": [
 \"ES256\",
 \"ES384\",
 \"ES512\",
 \"RS256\",
 \"RS384\",
 \"RS512\",
 \"PS256\",
 \"PS384\",
 \"PS512\",
 \"none\",
 \"EdDSA\"
 ],
 \"token_endpoint_auth_methods_supported\": [
 \"client_secret_basic\",
 \"none\"
 ],
 \"token_endpoint_auth_signing_alg_values_supported\": [
 \"RS512\",
 \"PS256\",
 \"PS384\",
 \"PS512\",
 \"RS256\",
 \"RS384\"
 ],
 \"claims_parameter_supported\": true,
 \"claims_supported\": [
 \"iss\",
 \"sub\",
 \"aud\",
 \"exp\",
 \"iat\",
 \"name\",
 \"family_name\",
 \"given_name\",
 \"email\",
 \"email_verified\"
 ],
 \"request_parameter_supported\": true,
 \"request_uri_parameter_supported\": false
 }
]" 

```

I'd assume the problem is in a later part of the log. Please link the full log.

**Comment by davitol** [comment]
https://cloud.owncloud.com/index.php/s/oDngsk39uSp9Ij6

Public link with the full log

**Comment by TheOneRing** [comment]
Could you please use a recent client?

**Comment by michaelstingl** [comment]
> Could you please use a recent client?

tomorrows daily-2.7.0 will be awesome!!
https://download.owncloud.com/desktop/ownCloud/daily/2.7/mac/?sort=time&order=desc

**Comment by davitol** [comment]
> Could you please use a recent client?

Could you please provide me the download link? I got the latest build i found in https://download.owncloud.com/desktop/testing/

**Comment by davitol** [comment]
Retested with Built from Git revision 4cb5cf on Sep 14 2020, 02:12:32 using Qt 5.12.9, OpenSSL 1.1.1g 21 Apr 2020


I still not able to login but Desktop Client does not get frozen any more

**Comment by davitol** [comment]
> Retested with Built from Git revision 4cb5cf on Sep 14 2020, 02:12:32 using Qt 5.12.9, OpenSSL 1.1.1g 21 Apr 2020
> 
> I still not able to login but Desktop Client does not get frozen any more

Logs with this attempt: https://cloud.owncloud.com/index.php/s/F3Og4Iz0AqjZPdN

**Comment by davitol** [comment]
Retried changing the Default Browser from Firefox to Chrome:

Desktop Client crashed:

Logs here: https://cloud.owncloud.com/index.php/s/F3Og4Iz0AqjZPdN


Sent info to the bugtracker too
`Sent! Many thanks. Please refer to crash 05939f04-1c7b-4765-a0f0-e4f13a57f0cd in bug reports.`

**Comment by jnweiger** [comment]
> > Could you please use a recent client?
> 
> Could you please provide me the download link? I got the latest build i found in https://download.owncloud.com/desktop/testing/



    Could you please use a recent client?

https://download.owncloud.com/desktop/ownCloud/daily/2.7/mac/

or 

https://download.owncloud.com/desktop/testpilotcloud/daily/2.7/mac/

**Comment by TheOneRing** [comment]
The crash was somewhere in Qt and not very informative.
The issue with firefox vs chrome looks like a local issue, it works with firefox here.
Could you try to investigate why it is not working with firefox, could be a noteworthy effort for future support cases.
Else I'd suggest to close the issue.

**Comment by davitol** [comment]
Yes, let's close the ticket and if i can find more info related my firefox problem I will comment here. Thanks for the help.
