### ISSUE TITLE
Activity button text is cropped using Mac Client

### ISSUE THREAD

**Issue by davitol** [owncloud/client#8080]
Built from Git revision 4cb5cf on Sep 14 2020, 02:12:32 using Qt 5.12.9, OpenSSL 1.1.1g 21 Apr 2020 using Mac Client

<img width="208" alt="Screenshot 2020-09-14 at 13 58 30" src="https://user-images.githubusercontent.com/10596560/93083360-c50f6500-f692-11ea-9480-8647d0844c47.png">

**Comment by TheOneRing** [comment]
Qt layout bug that only happens when no account is configured.
Closing for now
