### ISSUE TITLE
Windows Desktop App used token gets lost

### ISSUE THREAD

**Issue by elbae** [owncloud/client#8092]
Hi, I am reporting here an Issue (probably wrongly) opened in /core (https://github.com/owncloud/core/issues/37748) since I see no answer there.

The scenario is the following:
- 2FA authentication, first with LDAP second Google Auth
- App token created in /index.php/settings/personal?sectionid=security
- App token randomly lost

This issue might be related to: https://github.com/owncloud/client/issues/7857

Client configuration

Client version: 2.6.3 (build 13551)
Operating system: Microsoft Windows 10 Pro

**Comment by michaelstingl** [comment]
Did the app token disappear from the web UI?

**Comment by TheOneRing** [comment]
For 2FA I recommend to use oauth.
The web interface will still ask you every second time for a key, but the desktop client will run just fine after the initial auth.

**Comment by elbae** [comment]
@michaelstingl  exactly, they disappear.

**Comment by michaelstingl** [comment]
> @michaelstingl exactly, they disappear.

Hm, then it needs to be solved in https://github.com/owncloud/core/issues/37748 . Nothing the ownCloud desktop team can fix.

Did you consider migrate to OAuth 2.0? Then web browser opens for login, you can enter 2FA in web view, and you no longer need to rely on app token… 

You could give it a try with demo.owncloud.com (`demo:demo` or `admin:admin`)

**Comment by elbae** [comment]
Thank you @michaelstingl  and @TheOneRing for your support.
We are going to verify whether it is feasible or not.

**Comment by elbae** [comment]
Hello, we tried to implement Oauth for ownCloud desktop app.
Unfortunately no one is able to sync documents anymore since we receive the following error:
> 403 Forbidden .... (Encryption not ready: Private key missing: please try to log-out and log-in again)

This might be related (as stated in https://github.com/owncloud/oauth2/issues/213) 

> As stated here https://doc.owncloud.com/server/admin_manual/configuration/files/encryption/encryption_configuration.html
> Oauth2 doesn't work with User-Key Based Encryption, hence my issue.

and I think we are in the  `User-Key` situation.

**Comment by TheOneRing** [comment]
Where you able to find a solution

**Comment by elbae** [comment]
Hi, unfortunately we could not follow your suggestions (for reasons).
Closing the issue since I can't provide update anymore (maybe our misconfiguration).
