### ISSUE TITLE
gpg: invalid key resource URL

### ISSUE THREAD

**Issue by herrdeh** [owncloud/client#8097]
After upgrade to ubuntu20 (gnome 3.36.3), whenever I try to add another key, I get this error:

```
gpg: invalid key resource URL '/etc/apt/trusted.gpg.d/isv:ownCloud:desktop.gpg'
gpg: Schlüsselblockhilfsmittel`(null)': Allgemeiner Fehler
gpg: key 4ABE1AC7557BEFF9: 1 Beglaubigung wegen fehlendem Schlüssel nicht geprüft
gpg: key 3B4FE6ACC0B21F32: 3 Beglaubigungen wegen fehlender Schlüssel nicht geprüft
gpg: key D94AA3F0EFE21092: 3 Beglaubigungen wegen fehlender Schlüssel nicht geprüft
gpg: key 871920D1991BC93C: 1 Beglaubigung wegen fehlendem Schlüssel nicht geprüft
gpg: key 8881B2A8210976F2: 1 Beglaubigung wegen fehlendem Schlüssel nicht geprüft
gpg: Anzahl insgesamt bearbeiteter Schlüssel: 10
gpg:       ignorierte neue Schlüssel: 10
```

OC desktop client works fine, but I’m not sure whether it blocks me from installing other software (trying pgAdmin4).

To install, I followed the instructions at SuSE:

```
echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/isv:ownCloud:desktop.list
curl -fsSL https://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/isv:ownCloud:desktop.gpg > /dev/null
sudo apt update
sudo apt install owncloud-client


```
Fellows at [owncloud central](https://central.owncloud.org/t/gpg-invalid-key-resource-url-etc-apt-trusted-gpg-d-isvdesktop-gpg/28013/5) tend to regard this as a bug.

**Comment by abhiquiet** [comment]
Hi,
I am using Ubuntu 20.04
Today I was updating my system and realized the same error is popping up in my machine too. 
Kindly share the updated and verifiable keys. 

Regards
Abhinav Aggarwal

**Comment by michaelstingl** [comment]
With the next 2.7 version, we’re moving away from download.opensuse.org/repositories… . 2.7.0-beta5 repos are already available on our own download mirrors.

Here you can give it a try:
https://download.owncloud.com/desktop/ownCloud/testing/2.7.0.2141-v270beta5/linux/download/

**Comment by herrdeh** [comment]
Did so. Same error happens:

```
gpg: invalid key resource URL '/etc/apt/trusted.gpg.d/isv:ownCloud:desktop.gpg'
gpg: Schlüsselblockhilfsmittel`(null)': Allgemeiner Fehler
gpg: key 4ABE1AC7557BEFF9: 1 Beglaubigung wegen fehlendem Schlüssel nicht geprüft
gpg: key 3B4FE6ACC0B21F32: 3 Beglaubigungen wegen fehlender Schlüssel nicht geprüft
gpg: key D94AA3F0EFE21092: 3 Beglaubigungen wegen fehlender Schlüssel nicht geprüft
gpg: key 871920D1991BC93C: 1 Beglaubigung wegen fehlendem Schlüssel nicht geprüft
gpg: Anzahl insgesamt bearbeiteter Schlüssel: 10
gpg:       ignorierte neue Schlüssel: 10

```

**Comment by michaelstingl** [comment]
Could you post the full steps you tried?

**Comment by herrdeh** [comment]
Sorry. This happens after the very first command - with sudo as well:

`wget -nv https://download.owncloud.com/desktop/ownCloud/testing/2.7.0.2141-v270beta5/linux/Ubuntu_20.04/Release.key -O - | sudo apt-key add -`

**Comment by jferradans** [comment]
Hi,

My workaround was rename "/etc/apt/**trusted.gpg.d/isv:ownCloud:desktop.gpg**" to "/etc/apt/trusted.gpg.d/**isv-ownCloud-desktop.gpg**"

It worked for me.

Regards,

**Comment by herrdeh** [comment]
Sorry for the late reply. I tried it on two machines - works on both. I think it's more than a workaround, isn't it?
Thank you very much - you made my day! - Couldn't install pgAdmin4 all the time for that reason - now I could.

**Comment by Basster** [comment]
To be fair, the official install instruction pipes the key into `/etc/apt/trusted.gpg.d/isv:ownCloud:desktop.gpg`, so this issue isn't solved, as long as Ubuntu 20.04 seems to have a problem with a key filename with colons?!

I'd reopen it.

**Comment by herrdeh** [comment]
> I'd reopen it.
Agreed.

**Comment by jnweiger** [comment]
SUSE fixed the instructions. They now use isv_ownCloud_desktop.gpg instead of isv:ownCloud:desktop.gpg

**Comment by Basster** [comment]
Sorry, to bother you but then the owncloud website still points to the wrong package:

![image](https://user-images.githubusercontent.com/1265783/99768720-920ba680-2b05-11eb-8ade-8c7931afc384.png)

Who's resonsible for changing that?

**Comment by michaelstingl** [comment]
Website will be updated with the 2.7 links the next few days anyway.

**Comment by AWSBarker** [comment]
This is still a bug on Ubuntu 20.04. Tried to update again today and still same issue from last year.

Renaming as suggested doesn't help:

`sudo mv /etc/apt/trusted.gpg.d/isv\:ownCloud\:desktop.gpg /etc/apt/trusted.gpg.d/isv-ownCloud-desktop.gpg`

I still get this error

```
Err:8 https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_20.04  InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 0700205DFD41A71A

```
Any suggestions to hacks or we must wait?

**Comment by michaelstingl** [comment]
I performed a quick test using Docker, but I wasn't able to reproduce.

```
docker run --rm -ti ubuntu:20.04
```

**Fresh install from ownCloud repo**

Instructions:

1. https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/

```
# owncloudcmd --version
ownCloud 2.7.4 (build 2934) Dec 21 2020 15:42:27
https://github.com/owncloud/client/commit/44d1541bdc7765d11ab0327910496a09afeb1b0b
Libraries Qt 5.12.9, OpenSSL 1.1.1f  31 Mar 2020
Using virtual files plugin: off
root@f91dbe9ca6b5:/# history
    1  apt update && apt install curl wget sudo gnupg -y
    2  wget -nv https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_20.04/Release.key -O - | sudo apt-key add -
    3  echo 'deb https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_20.04/ /' | sudo tee -a /etc/apt/sources.list.d/owncloud.list
    4  sudo apt update
    5  sudo apt install owncloud-client
    6  owncloudcmd --version
    7  history
```

**Fresh install from SUSE repo, then update from ownCloud repo**

Instructions:

1. https://software.opensuse.org/download/package?project=isv:ownCloud:desktop&package=owncloud-client
  (Add repository and install manually)
2. https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/

```
# owncloudcmd --version
ownCloud 2.7.4 (build 2934) Dec 21 2020 15:42:27
https://github.com/owncloud/client/commit/44d1541bdc7765d11ab0327910496a09afeb1b0b
Libraries Qt 5.12.9, OpenSSL 1.1.1f  31 Mar 2020
Using virtual files plugin: off
root@acca479d673a:/# history
    1  apt update && apt install curl wget sudo gnupg -y
    2  echo 'deb http://download.opensuse.org/repositories/isv:/ownCloud:/desktop/Ubuntu_20.04/ /' | sudo tee /etc/apt/sources.list.d/isv:ownCloud:desktop.list
    3  curl -fsSL https://download.opensuse.org/repositories/isv:ownCloud:desktop/Ubuntu_20.04/Release.key | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/isv_ownCloud_desktop.gpg > /dev/null
    4  sudo apt update
    5  sudo apt install owncloud-client
    6  owncloudcmd --version
    7  wget -nv https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_20.04/Release.key -O - | sudo apt-key add -
    8  echo 'deb https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_20.04/ /' | sudo tee -a /etc/apt/sources.list.d/owncloud.list
    9  sudo apt update
   10  sudo apt install owncloud-client
   11  owncloudcmd --version
   12  history
```

**Comment by michaelstingl** [comment]
There's a recommendation in another issue:

> You have an error message there: `gpg: invalid key resource URL '/etc/apt/trusted.gpg.d/isv:ownCloud:desktop.gpg'` -> that is from a a previous attempt. Remove that file.

(Source: https://github.com/owncloud/client/issues/8195#issuecomment-728558300)
