### ISSUE TITLE
Subfolder is reported larger than parent folder

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8102]
Tested with
 * ocis master from 7h ago
 * appliance from https://github.com/owncloud/client/actions/runs/255830173

<details>
<summary> ocis master version details</summary>

<pre>
OCIS_VERSION:         master
ocis --version:       ocis version 7b8e9bc
git log:              commit 7b8e9bc2981c0fd9917bc576a291ab5231c02685 (HEAD -> refs/heads/master, refs/remotes/origin/master, refs/remotes/origin/HEAD)
eos --version:        EOS 4.6.5 (2019)
xrootd -v:            v4.11.0
bin/ocis contains:
	owncloud/ocis-accounts@v0.4.2-0.20200911161616-e55b8ae2f440
	owncloud/ocis-glauth@v0.5.1-0.20200909064150-0735ec933777
	owncloud/ocis-graph-explorer@v0.0.0-20200210111049-017eeb40dc0c
	owncloud/ocis-graph@v0.0.0-20200318175820-9a5a6e029db7
	owncloud/ocis-hello@v0.1.0-alpha1.0.20200828085053-37fcf3c8f853
	owncloud/ocis-konnectd@v0.3.2
	owncloud/ocis-migration@v0.2.0
	owncloud/ocis-ocs@v0.3.2-0.20200916110615-7ca52baa61c4
	owncloud/ocis-phoenix@v0.13.1-0.20200910090722-8e3ed0e966a5
	owncloud/ocis-pkg/v2@v2.4.1-0.20200902134813-1e87c6173ada
	owncloud/ocis-proxy@v0.7.1-0.20200907105449-201b9a652685
	owncloud/ocis-reva@v0.14.0
	owncloud/ocis-settings@v0.3.2-0.20200903035407-ad5de8264f91
	owncloud/ocis-store@v0.1.1
	owncloud/ocis-thumbnails@v0.3.0
	owncloud/ocis-webdav@v0.1.1
</pre></details>

![image](https://user-images.githubusercontent.com/1108546/93621268-97e8ec80-f9db-11ea-86dd-c7257a596d2b.png)

Wait 10min, see if it gets in sync...  Nope. It stays.
Force sync now? Nope.
Logout/login? Nope.

Expected behaviour: Parent folder is at least as large (949MB) as its subfolder.

Workaround: disable selective sync parent folder, reenable parent folder.
Now the sizes get in sync:
![image](https://user-images.githubusercontent.com/1108546/93621699-3c6b2e80-f9dc-11ea-88bc-93f20d9a59e9.png)

**Comment by saw-jan** [comment]
Tested on `ownCloud 6.0.0.13589-daily20240328 [32670a]`

![Screenshot from 2024-03-28 15-00-09](https://github.com/owncloud/client/assets/52366632/0420eac1-2365-4bbf-8314-9f0bbad7f072)
