### ISSUE TITLE
OpenID Connect scopes need to be brandable

### ISSUE THREAD

**Issue by DeepDiver1975** [owncloud/client#8110]
### Expected behaviour
The list of scopes which are required for an OpenID Connect setup are subject to change on every installation.
The list of scopes need to be brandable.

examples:
```
- 'openid', 'api://212e9d79-509d-4f4a-ad35-58922eb76e4d/owncloud', 'user.read', 'profile', 'email', 'offline_access'
- 'openid'
- 'openid', 'offline_access'

**Comment by TheOneRing** [comment]
Related https://github.com/owncloud/ownbrander/issues/945
