### ISSUE TITLE
[2.7][Beta5] Icons not perfectly aligned

### ISSUE THREAD

**Issue by ChrisEdS** [owncloud/client#8114]
### Actual behaviour
The icons and the text in the header looks a bit off-center.

![image](https://user-images.githubusercontent.com/33026403/94293019-02f76d80-ff5e-11ea-9d4c-69ef448952a2.png)

### Client configuration
Client version: 2.7.0 Beta5 

Operating system:
macOS`

**Comment by TheOneRing** [comment]
Fixed in newer versions of Qt 
![image](https://user-images.githubusercontent.com/200626/94559411-7f8d9300-0261-11eb-8187-69130c3820bf.png)

**Comment by TheOneRing** [comment]
Qt on Mac flakiness, hard to reproduce.
