### ISSUE TITLE
Linux Desktop Client Open Virtual Files Fails for Symlinked Paths

### ISSUE THREAD

**Issue by t3nk3y** [owncloud/client#8117]
### Expected behaviour
Attempting to open a virtual file (*.owncloud) should sync the file and open in the associated application.

### Actual behaviour
If the path that is provided to owncloud is has a symlink in the path, owncloud will fail to find the file, and an error will be placed in the log, and no other feedback will be given to the user.

### Steps to reproduce
1. Create a symlink to a path that is inside an owncloud virtually synced path.
**owncloud path:** /owncloud/path
`ln -s /owncloud/path /home/path`
2. Attempt to open an owncloud virtual file from the symlinked path:
`owncloud /home/path/example.txt.owncloud`
**Log will show:**
_[ warning gui.application ]:	Can't find sync folder for "/home/path/example.txt.owncloud"_
3. Attempt to open owncloud virtual file from actual path:
`owncloud /owncloud/path/example.txt.owncloud`
**File will sync and open in viewer associated with example.txt**
### Server configuration
CLIENT ONLY ISSUE

### Client configuration
Client version:
**2.7.0v270beta5 (build 2141)**
Operating system:
**Ubuntu 20.04**
OS language:
**English**
Qt version used by client package (Linux only, see also Settings dialog):
**5.12.9**
Client package (From ownCloud or distro) (Linux only):
From download.owncloud/com testing
Installation path of client:
/opt/ownCloud and /usr/bin
### Logs
Relevant log line included in steps to reproduce

**Comment by TheOneRing** [comment]
Using symlinks with ownCloud is currently not supported and at the moment there are no pans to change that.

**Comment by TheOneRing** [comment]
See https://github.com/owncloud/client/issues/1887 and https://github.com/owncloud/client/issues/1440 for context

**Comment by t3nk3y** [comment]
This is not about pointing the OwnCloud client to a symlinked path.  In this case, OC is set to sync a real path.
However, if attempting to open a VIRTUAL file from the OC client, OC does not de-reference the path back to the real path that OC uses.

This is specific to the newer virtual file support.  The issue comes up, as if a user navigates to any OC path FROM a symlink within a GUI file manager, when the user clicks the file to open it, it won't open.

I could almost certainly solve this by putting a simple wrapper bash script around the owncloud binary, and associating that bash script with the owncloud mime type.  This is really an issue of how the file identifier is communicated to the virtual file support, and it's not reasonable to expect a user to solve the problem, but is relatively simple to solve the problem in the command line parser before the symlink gets any further down the road.

**Comment by t3nk3y** [comment]
In fact, here is a summarized workaround.  Just make this a bash script, and associate owncloud files with it, instead of the owncloud binary and this problem is solved(in Linux environments that have the readlink command available)

`echo owncloud \'$(readlink -f "$@")\' | bash -`

**Comment by TheOneRing** [comment]
If you want to sync a folder outside of your home directory I'd recommend to use a Folder Sync connection.
![image](https://user-images.githubusercontent.com/200626/94658426-12323e80-0303-11eb-91bd-29510a6b927c.png)
