### ISSUE TITLE
[QA] Selective sync warns about big folders even if unselected

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8142]
## seen with Version 2.7.0daily20201006 (build 2214) running on Ubuntu 18.04

I have a 2GB folder in the server, that I had exceluded from selective sync.
Quit the client. restart the client. An error appears:

![image](https://user-images.githubusercontent.com/1108546/95208288-2d141f80-07e9-11eb-93ef-908750271661.png)

Note, how the folder Intern+/projekte is already deselected. I want to sync the other folders, thus I cannot select 'Synchronize none' and I don't want to include any deslected folders, so I cannot select 'Synchronize all'. I miss an option "The settings are fine, just continue".

Workaround:
* Click the checkbox at 'Projekte' -> A checkmark appears, and the option 'Apply manual changes' becomes available.
* Click the checkbox again -> the checkmark disappears, but the option remains.
* Now click the 'apply manual changes' -- which effectively applies no changes.

**Comment by TheOneRing** [comment]
Feature was removed in https://github.com/owncloud/client/pull/11517
