### ISSUE TITLE
[QA] Build date disagrees with daily version number

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8143]
## Seen with version 2.7.0daily20201006 (build 2214) on Ubuntu 18.04

![image](https://user-images.githubusercontent.com/1108546/95209481-af511380-07ea-11eb-84aa-385605962377.png)

The daily build is dated 20201006, which is Oct 10. But the text further down says:
"Built from Git revision 76c52e on Sep 23 2020, 09:54:34"
the commit history on the 2.7 branch has 15 commits since Sept 23, (master has 10).

Are we building dailies from old sources?  The commit id displayed matches Sept 23.

**Comment by dschmidt** [comment]
what kind of sorcery is this?! 🧙🏻‍♂️

**Comment by jnweiger** [comment]
Github tries to confuse me:

* Clicking the link in the UI expands to https://github.com/owncloud/client/commit/76c52e65d1f53036c05fa2470dc646facc3c9d18 (13 days old)
* Manually searching for 76c52e in git brings up https://github.com/owncloud/client/tree/76c52e (yesterday)

**Comment by jnweiger** [comment]
Windows does it a bit differently: same commit ID, but yesterdays date.
![image](https://user-images.githubusercontent.com/1108546/95230050-9ef86300-0801-11eb-84f8-64a1fc2eb21b.png)

that'd be perfectly fine, if there weren't the  confusion about the same  git ID referning to two different points in time :dizzy:

**Comment by TheOneRing** [comment]
CCache? using __DATE__ is problematic with ccache

**Comment by TheOneRing** [comment]
Does it still happen? I'll mark the report as stale so it will be closed in a week from now if nothing happens.

**Comment by dschmidt** [comment]
I think this was caused by drone incorrectly caching the converted job config and still using your fork. I'd expect this to be fixed now after the drone downgrade.
