### ISSUE TITLE
[QA] Error while loading the list of folders from the server -- with openidconnect

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8145]
Tested with server 10.5 + openidconnect 1.0.0RC4 for https://github.com/owncloud/openidconnect/issues/66 + desktop client testpilotcloud version 2.7.0daily20201004 (build 2209)

* connect the client with openidconnect
* wait for the initial sync
* suspend the client computer over night
* resume the next day, reconnect to the server
* "Error while loading the list of folders from the server."
* add a folder locally, to confirm if we are really connected. Yes, the client starts syncing.
* The error is still visible:
![image](https://user-images.githubusercontent.com/1108546/95428110-d9204c80-0948-11eb-991e-bafd5f558cea.png)

Expected behaviour:
Any transient errors due to intterupted connections go away when reconnected.

**Comment by TheOneRing** [comment]
Probably same as https://github.com/owncloud/openidconnect/issues/106 please reopen if it still happens after the fix
