### ISSUE TITLE
[QA] Three-dots menue is disabled after sync paused

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8147]
Tested with owncloudclient-2.7.0-daily20201007.2219-vfs.x64.msi  on a Win10 VM

* Connected to a server via openidconnect
* connect a second account to demo.owncloud.com
* start a long download of thousands o files. (e.g. pigpen)
* pause the sync
* suspend the VM, time passes.
* restart the VM

On the demo account, the three dots menu works as expected

![image](https://user-images.githubusercontent.com/1108546/95462134-67abc280-0977-11eb-8851-4139dc3dbbd1.png)

But on the pigpen account the three dots menu is (almost always) non-responsive:
![image](https://user-images.githubusercontent.com/1108546/95462475-d7ba4880-0977-11eb-9394-2248d44cf1c7.png)

Workaround: Try clicking very often, try waiting 10 seconds after clicking without moving the mouse. Somtimes the menu appears.

**Comment by jnweiger** [comment]
After getting the menue and selecting to continue the sync, a deadlock seems to appear. The demo account is stil lin state "waiting" the pigpen account is now in state waiting for two(??) other folders:

![image](https://user-images.githubusercontent.com/1108546/95462475-d7ba4880-0977-11eb-9394-2248d44cf1c7.png)

**Comment by jnweiger** [comment]
Stop the client, restart. That solves the dead locks and the long waits.

**Comment by TheOneRing** [comment]
Might be related to https://github.com/owncloud/client/issues/7973 closing for now
