### ISSUE TITLE
[QA] /usr/share/cloud-providers/*.ini is missing 

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8155]
## Seen with ownCloud 2.7.0v270rc1 (build 2254) Oct  9 2020 12:56:43
The file
/usr/share/cloud-providers/*.ini
is missing on all Linux platforms.
This is a regression. With e.g. 2.6.3 this file was present in Linux packages for some modern linux distros.

@dschmidt Packaging thing?

**Comment by jnweiger** [comment]
e.g. 2.6.4daily20200816 (build 2841) had

|Platform|Test|Result|
|-|-|-|
|centos:7|30_cloud_prov_ini.sh| ls: cannot access /usr/share/cloud-providers/*.ini: No such file or directory
|centos:8|30_cloud_prov_ini.sh| ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|debian:9|30_cloud_prov_ini.sh| ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|debian:10|30_cloud_prov_ini.sh|        -rw-r--r-- 1 root root 102 Sep 26 11:50 /usr/share/cloud-providers/com.owncloud.desktopclient.ini
|fedora:30|30_cloud_prov_ini.sh|        ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|fedora:31|30_cloud_prov_ini.sh|        -rw-r--r-- 1 root root 102 Aug 16 01:08 /usr/share/cloud-providers/com.owncloud.desktopclient.ini
|fedora:32|30_cloud_prov_ini.sh|        -rw-r--r-- 1 root root 102 Aug 16 01:08 /usr/share/cloud-providers/com.owncloud.desktopclient.ini
|Linux_Mint_19|30_cloud_prov_ini.sh|    ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|ubuntu:18.04|30_cloud_prov_ini.sh|     ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|ubuntu:19.10|30_cloud_prov_ini.sh|     -rw-r--r-- 1 root root 102 Aug 16 01:07 /usr/share/cloud-providers/com.owncloud.desktopclient.ini
|ubuntu:20.04|30_cloud_prov_ini.sh|     -rw-r--r-- 1 root root 102 Aug 16 01:08 /usr/share/cloud-providers/com.owncloud.desktopclient.ini
|opensuse/leap:15.0|30_cloud_prov_ini.sh|       ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|opensuse/leap:15.1|30_cloud_prov_ini.sh|       ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory
|opensuse/leap:15.2|30_cloud_prov_ini.sh|       ls: cannot access '/usr/share/cloud-providers/*.ini': No such file or directory

**Comment by dschmidt** [comment]
Well ... probably? Forgot to sync some changes from obs to build-linux repo?

**Comment by TheOneRing** [comment]
Yes packaging issue 
```

Can't determine libcloudproviders version, not enabling it
--

**Comment by jnweiger** [comment]
I am removing the test from gitea/client/linux-docker-install/test -- 
@michaelstingl please reopen, if or when work there should continue.
