### ISSUE TITLE
Add haeder to activity view

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8158]
## Seen with 2.7.0 RC1 on Ubuntu 18.04

Due to #8104 we use Displayname@host which can be quite long. The second column is not resizable, and shows the cloud.dam... or cloud.ownclou... only abbreviated

![image](https://user-images.githubusercontent.com/1108546/95930909-08f7a600-0dc8-11eb-8dea-e905319664d2.png)

Expected behaviour: The column should be resizeable.
Workaround: Wait for the mouse over text.

**Comment by TheOneRing** [comment]
The activity tab is also not rtl aware https://github.com/owncloud/client/issues/4336

**Comment by dragotin** [comment]
Shouldn't the information who did that rather be represented by the Avatar (which is not really one so far) on the left? And even in the text displays the name (such as "Du hast.." or "Barnie Geröllheimer hat..."), so maybe it can be dropped in the right column?

**Comment by TheOneRing** [comment]
I agree it should display the avatar, but by default all accounts have the same avatar... and as you can have quite a number of accounts on different servers, at least in theory...

And then there is You@Job1, You@Job2, You@Home so I guess the column has some right to exist.
