### ISSUE TITLE
[QA] Log Settings window is to small for the amount of text presented

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8168]
## Seen with testpilotcloud 2.7.0daily20201014 (build 2280) 4b53c8 Oct 14 2020 09:13:20

![image](https://user-images.githubusercontent.com/1108546/96033694-b74f2a00-0e60-11eb-8511-262fa7bc5639.png)

Easy workaround: pull the window a few pixels larger.

**Comment by TheOneRing** [comment]
@jnweiger could you try the app image from https://github.com/owncloud/client/pull/8190
