### ISSUE TITLE
Renaming a local folder will lead to the deletion of all files after the next sync cycle

### ISSUE THREAD

**Issue by pitr4cloud** [owncloud/client#817]
Hi guys,

I'm heavily testing owncloud and it seems that the Desktop Client is not able to manage local renaming of folders / subfolders.

Here is the use case to reproduce the defect:
- let's assume that you would have created a valid synchronization.
  local folder would be "C:\LOCAL" and remote folder would be "/"
- in your LOCAL repository, create a folder called "NAME_1" and paste any file within it (I have stored 10 MSI files for a total amount of 200MB)
- wait for the SYNC to happen (it may take some time depending on the number of files to be uploaded)
- if you go to the Web interface, you see your NAME_1 folder containing the right files; so far so good;
- back to your LOCAL folder, rename NAME_1 to NAME_2
- wait for the SYNC to happen
- within your LOCAL folder, the new NAME_2 folder is properly displayed; however, all files have been deleted... and the Desktop application will let you know that all files have been sucessfully deleted (arg!)
- if you want to be 100% sure, go to the could so that you can indeed confirm that your files are gone, on both sides!

Hope you can fix this dangerous behaviours as it is a road blocker for rolling out this solution towards users that are not proficient in IT

Best,

Pitr

Server Side - MS Server 2008 running on VMWARE + Wamp Server 5 + owncloud 5.0.9
Client Side - Windows 7 Pro + owncloud Windows client 1.3.0

**Comment by cbxk1xg** [comment]
I habe the same issue here. I m running Owncloud on Debian 7.8 and nginx. It make Ownloud unusuable!

**Comment by ogoffart** [comment]
please open an issue in the owncloud/core component,  (https://github.com/owncloud/core/issues)

 (following the template https://raw.githubusercontent.com/owncloud/core/master/issue_template.md )

**Comment by cbxk1xg** [comment]
It's not just a server problem. I just expericenced it again on another setup. - Guys, seriously, DO SOMETHING! - I am not gonna write another stupid bug report again. Last time I did it for the music app, I also provided the solution. And guess what, till that day, no response at all.

**Comment by LukasReschke** [comment]
> Last time I did it for the music app, I also provided the solution. And guess what, till that day, no response at all.

The music app is a community contributed application by @MorrisJobke in his spare time. If you encounter problems and he has no time nor will to fix this, this is absolutely ok as you did not pay anything at all to use the software.

It's an open-source project. If you encounter issues you are welcome to provide patches for them as well in form of a pull request or open an issue and hope that somebody will fix these issues. Alternatively you can obviously pay somebody to do it for you ;-)

**Comment by LukasReschke** [comment]
If you refer to https://github.com/owncloud/music/pull/348 then you REALLY impatient. You can't expect somebody else to take a look at all changes and approve them within 2 days.

**Comment by cbxk1xg** [comment]
Have you lost it? There are several people reporting, that there is a severe bug that can cause loss of data. And you young feller have the nerve to tell an old IT-veteran that I shouldn't complain about it?

**Comment by LukasReschke** [comment]
No. I have young feller have the nerve to tell an old IT-veteran to do what the hell you have been nicely asked to do by the client guys: https://github.com/owncloud/client/issues/817#issuecomment-73401611

If you expect ANY kind of support here I'd highly encourage you to change your tone and follow our code of conduct. You're talking to "the young feller who has the 7th most commits in the ownCloud server code base".

**Comment by LukasReschke** [comment]
https://owncloud.org/community/code-of-conduct/

**Comment by Raydiation** [comment]
@cbxk1xg np, just install systemd and everything will work. We will start to require it in 8.0.1

**Comment by cbxk1xg** [comment]
Alright, we are getting a bit of topic here. So you tell me basically that you don't care about your own code? Because that's standing between the lines if people report a severe bug and none of the developers responds. And that's just because no one want's to fill out your reporting form?

A cloud-software should have a clear priority. And that is under any circumstances: Keep the user data save!

I really don't get your point.

**Comment by DeepDiver1975** [comment]
> I really don't get your point.

@cbxk1xg 
1. This issue is rather old an out dated
2. You issue is for sure caused by a different reason
3. Please open a new issue and give us all the information we need and we will happily help you out
4. https://owncloud.org/community/code-of-conduct/
5. Thanks you!
