### ISSUE TITLE
Support for macOS 11/10.16 (Big Sur)

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#8173]
Placeholder ticket to track the progress to support macOS 11/10.16 - as the client right now is unable to start on the latest beta version (10) of Big Sur.

Ref. ticket on Qt tracker: https://bugreports.qt.io/browse/QTBUG-85546

**Comment by michaelstingl** [comment]
> Placeholder ticket to track the progress to support macOS 11/10.16 - as the client right now is unable to start on the latest beta version (10) of Big Sur.

@SamuAlfageme What hardware did you test?

**Comment by guruz** [comment]
What's the error message?

**Comment by TheOneRing** [comment]
Looks like it worked here https://github.com/owncloud/client/issues/8149

**Comment by michaelstingl** [comment]
`owncloudclient-2.7.0-daily20201111.2431.pkg` is running fine on x64 macOS Big Sur 11.0.1 RC (Parallels VM)

![CleanShot 2020-11-12 at 08 39 49](https://user-images.githubusercontent.com/214010/98924515-34f46d00-24d5-11eb-9322-c7af5d1a8008.png) | ![CleanShot 2020-11-12 at 08 37 59](https://user-images.githubusercontent.com/214010/98924535-39208a80-24d5-11eb-8fad-3ed12546d126.png)
-- | --

**Comment by SamuAlfageme** [comment]
Indeed, it looks like it was a misunderstanding from the report we got. Thanks a lot for looking into it! ❤️

Closing here!

**Comment by michaelstingl** [comment]
Runs also fine on Apple Silicon:

![Screenshot 2020-11-20 at 23 04 03](https://user-images.githubusercontent.com/214010/99854287-d427fd00-2b84-11eb-9930-b48f84c872df.png)

**Comment by diocas** [comment]
Great news @michaelstingl !

Just a remark: I will only update to Big Sur in a month from now (so I haven't tested with the real thing!), but by looking at the apps that have already adapted, I started noticing this:

![image](https://user-images.githubusercontent.com/2589871/99984010-7b36af80-2da4-11eb-9f4a-e7ea072a0ac9.png)

The app logos are much bigger than the others... Maybe you could scale them down? (the branded version as well)

**Comment by michaelstingl** [comment]
> The app logos are much bigger than the others... Maybe you could scale them down? (the branded version as well)

Please open separate issue.
