### ISSUE TITLE
Undefined behaviour when user was deleted on the server

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8185]
Seen with testpilotcloud 2.7.0daily20201019 (build 2311) Oct 15 2020 00:08:32 and oc10.5 with openidconnect:

* Connect a user via kopano IDP
* logout from the client gui
* as owncloud admin, delete the user in the gui.
* client tries to log in again, 
* The IDP  accepts the user and redirects, resulting in "Login Error - Failed to retrieve user info" OK.

The client offers to reopen the browser.
![image](https://user-images.githubusercontent.com/1108546/96736004-73a67400-13bc-11eb-9f20-aa3c72a51d0e.png)
But nothing happens, when the user clicks that button.

This only happens like that, when the account was previously connected.

-----------------------------------------------------------------------------------------
With a fresh connection attempt, we get

![image](https://user-images.githubusercontent.com/1108546/96737141-9e44fc80-13bd-11eb-9baf-bbb1edbfacdf.png)

Here the reopen browser button works.

**Comment by TheOneRing** [comment]
logs pls....

**Comment by TheOneRing** [comment]
@jnweiger what does happen with a current client and the fixed logout on auth errors?

**Comment by michaelstingl** [comment]
can't be solved with the information provided
