### ISSUE TITLE
Permission changes, x removed

### ISSUE THREAD

**Issue by 31SFX4** [owncloud/client#820]
### Expected behaviour

When syncing folders with executable files, they should remain executable
### Actual behaviour

I have a folder with executable scripts (perms "-rwxr--r--"). It's synced between two computers, permissions are the same on both machines.

Again and again all permissions get changed to "-rw-r--r--" so that script suddenly are no longer running. 

The permissions are actually changed on _all_ files in the folder, even the ones that haven't changed for years. It happened today even though the last change in this folder was 11 days ago.
### Steps to reproduce

No idea. It just happens spontanously and repeatedly, but not all the time (perhaps 4 or 5 times in the last month), and I haven't found out under which circumstances the permissions get changed. It's not related to actual changes in the folder. 
### Server configuration

Operating system: Debian
Web server: Apache
Database: MySQL 5.1.66
PHP version: 5.3.3-7+squeeze15
ownCloud version: 5.0.9
### Client configuration

Client version: 1.3.0beta4
Operating system: Ubuntu 13.4
Installation path of client: /usr/bin/owncloud

Log: Can't produce one at the moment because I don't know exactly when it happens.

**Comment by Nowaker** [comment]
> Next version of mirall should preserve file permission on the same machine.

owncloud 2.0 here. Doesn't look like implemented in this version.

**Comment by ogoffart** [comment]
It should!

If you make a file executable and that the file is modified on the server, the client will redownload it, but will not reset the permission as it used to do.

However the permissions are not synchronized on the server because the server still do not have support for arbitrary metadata

**Comment by Nowaker** [comment]
Okay, I misunderstood that. For me "preserve" is when I chmod +x, other copies will get +x too. Thanks for your explanation.

**Comment by githof** [comment]
Note that it's not just about x permission.
My client sets a-w (removes write permission for all, *including owner*) for all files.
So i chmod -R u+w, which removes write protection also for files i had intentionally set to r--r--r-- to prevent accidental editions for important files.
Well, along with so many other reasons why Unix file permissions have been invented ~40 years ago ;)

**Comment by DesideriusE** [comment]
Two years later: this issue *still* hasn't been fixed. Is it on any developer's to-do list?

**Comment by ogoffart** [comment]
@githof Right, the read-only flag is synchronized from the permission given from the server (as in: it will be set for read-only share, and unset otherwise)

@DesideriusE This issue was fixed a long time ago, the permissions should not be changed by the sync. If you can still reproduce the problem with recent version, please open a new bug report with detailed informations including client version and step to reproduce.

If you are talking about synchronizing the permissions with other clients, this is https://github.com/owncloud/core/issues/6983 which is indeed not implemented and need support on the server.
