### ISSUE TITLE
[QA] German translation issues

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8212]
Using testpilotcloud 2.7.0rc3 (build 2412) Nov  6 2020 09:36:47

![image](https://user-images.githubusercontent.com/1108546/98417437-30692800-2081-11eb-9521-a08fd92be60c.png)
![image](https://user-images.githubusercontent.com/1108546/98419108-a622c300-2084-11eb-80a7-b07344957037.png)
![image](https://user-images.githubusercontent.com/1108546/98419337-234e3800-2085-11eb-99bc-01c8dfe455b8.png)
![image](https://user-images.githubusercontent.com/1108546/98419542-922b9100-2085-11eb-9e69-8c6be23ca90c.png)
![image](https://user-images.githubusercontent.com/1108546/98419775-0e25d900-2086-11eb-8e20-6e354260a98e.png)

Untranslated:
* Add account
* Synchronizing with local folder
* Sync hidden files
* Log Settings
* Advanced - Approval of folder sync (Non virtual file mode only)
* About
* *The entire "About Window ..."*
* *A Username label is missing in the  "Connection Wizard"*

**Comment by jnweiger** [comment]
Transifex https://www.transifex.com/owncloud-org/owncloud/client/ has
* German (de): 100%
* German (Germany) (de_DE): 96.1%

**Comment by jnweiger** [comment]
I've pushed German (Germany) (de_DE) to 100% in transifex. I did not see
* Sync hidden files
* About
* and the Username label

**Comment by jnweiger** [comment]
Under Windows 10, the testpilot cloud client does not localize at all:
![image](https://user-images.githubusercontent.com/1108546/98424172-36ff9b80-2091-11eb-86d4-c963085bae73.png)

**Comment by jnweiger** [comment]
Retested with testpilotcloud 2.7.0daily20201110 (build 2426) Nov  9 2020 18:00:49 
My transifex updates 4 days ago have no effect so far. @TheOneRing Some backporting needed?

**Comment by TheOneRing** [comment]
@dschmidt there was no transifex sync, something broken?

**Comment by dschmidt** [comment]
Last transifex sync was 12h ago ...

https://github.com/owncloud/client/commit/bccd398a566b3ae35a1f6922a165e0f6885c0b9f

**Comment by TheOneRing** [comment]
Translation sync was broken, fixed in https://github.com/owncloud/client/commit/585182a98fb4eac16055a85b17a653fce2d1a345

**Comment by jnweiger** [comment]
Is this '<no filter>' translatable?

![image](https://user-images.githubusercontent.com/1108546/99456965-857f2680-292a-11eb-8c17-1c793eb07ebb.png)

**Comment by TheOneRing** [comment]
It is but I guess transifex has issues with the <>
![image](https://user-images.githubusercontent.com/200626/99503159-4975b100-297e-11eb-810d-36cd15ceeffa.png)

**Comment by jnweiger** [comment]
* The versions page has a stray '%' character:
![image](https://user-images.githubusercontent.com/1108546/99555757-f53ff080-29c0-11eb-8e04-2b2dced295f7.png)

**Comment by jnweiger** [comment]
Verified with 2.8.2: All marked items <except '<no filter>' are proper German in 'de_DE'
