### ISSUE TITLE
[QA] Windows VFS tries to hydrate excluded filenames and fails

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8216]
Seen with ownCloud client 2.7.0 RC3 on windows 10 using VFS.

* With the web UI on the server create a folder 'Music', with a few files in them. (PNG files in my case)
* wait until sync finishes.
* Make sure the status column of the folder shows a cloud. If needed click and and choose 'Free up space'
* on the client rename the folder to one of the excluded filenames. e.g. `Music~`
* the folder gets removed from the server. BAD. The contents is lost now. See #8217 
* enter the folder, click open a file. 

Windows tries to connect the owncloud client for the contents of the file and fails after a timeout:

![image](https://user-images.githubusercontent.com/1108546/98594603-35beb080-22d5-11eb-91ed-b9ab508ebd76.png)
![image](https://user-images.githubusercontent.com/1108546/98594633-3e16eb80-22d5-11eb-95c1-4fd8f5dd7ff6.png)

Expected behaviour: an excluded file should always be exclude in fully hydrated state only. (Or alternatively, the exculded files list is not applied for renames. )
The file is always available locally.

**Comment by jnweiger** [comment]
[logs.zip](https://github.com/owncloud/client/files/5513428/logs.zip)

**Comment by TheOneRing** [comment]
After the rename to the excluded pattern the the files are removed from the sync set, meaning they are deleted on the server and the placholders are invalid.
TODO:
- Improve the error message.
- Add documentation
