### ISSUE TITLE
[QA] Win10 VFS: Client hangs in state Waiting

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8218]
Seen with 2.7.0 on Win10 with VFS enabled

Sometimes, when a new folder appears on the server, the client is unable to sync. Hard to reproduce.
Happened while retriggerning #8217 
The client enters a waiting state, no network activity for over 10 minutes before I filed the report.

![image](https://user-images.githubusercontent.com/1108546/98597579-86d0a380-22d9-11eb-9882-c121904701d4.png)

Failed attempts to make it sync again:
* Pause sync, resume sync
* logout / login does not fix the state.
* switch from virtual to physical. 

Quit client, restart client succeeds in making it sync again. The missing folder appears.

**Comment by jnweiger** [comment]
[logs.zip](https://github.com/owncloud/client/files/5513373/logs.zip)

**Comment by michaelstingl** [comment]
@TheOneRing any clue what happens during "Waiting"? Anything in the logs?

**Comment by TheOneRing** [comment]
What is printed in the logs while the client is waiting?
(The logs don't contain lines like, now we display "Waiting..." ) :D

**Comment by TheOneRing** [comment]
Can't reproduce
