### ISSUE TITLE
[QA] Linux build release numbers missing in package name

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8228]
![image](https://user-images.githubusercontent.com/1108546/99240122-52d71000-27fc-11eb-8841-a8a3d9c5d342.png)

Expected behaviour: the version number should say 2.7.0-2443 instead of 2.7.0-1

**Comment by jnweiger** [comment]
And I need help finding, where I configured that minio- repo. It is not in /etc/apt/sources* anywhere :-)

**Comment by TheOneRing** [comment]
@dschmidt drone build number not defined in the ci step

**Comment by dschmidt** [comment]
This looks like @jnweiger added some corrupted repo at some point ... 

Using that internal minio url is at least fishy ... no warranties it ever worked. The repos are later exported and then paths are fixed up...

**Comment by jnweiger** [comment]
I don't think the two things are releated.

**Comment by jnweiger** [comment]
There was some improvement between "2.7.0-rc3" and "2.7.0.2443"
* /https://download.owncloud.com/desktop/ownCloud/testing/2.7.0-rc3.2413/linux/
   - Fedora_32/owncloud-client-2.7.0-0.0.0.rc3.x86_64.rpm 
   - Ubuntu_20.04/owncloud-client_2.7.0~rc3-1_amd64.deb 
* https://download.owncloud.com/desktop/ownCloud/testing/2.7.0.2443/linux/
    - Fedora_32/owncloud-client-2.7.0-2443.x86_64.rpm
    - Ubuntu_20.04/owncloud-client_2.7.0-1_amd64.deb 

RPM is fixed, but DEB still misses the build number.

**Comment by dschmidt** [comment]
Interesting...

**Comment by dschmidt** [comment]
Fixed, just not synced to mirrors yet...
