### ISSUE TITLE
[QA] Client responds with confusing message after user mismatch in IDP

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8230]
After reproducing https://github.com/owncloud/ocis/issues/865

![image](https://user-images.githubusercontent.com/1108546/99273361-33a2a780-2829-11eb-8545-42a2fd7174bf.png)

The message "Please log out of ownCloud Testpilot Edition in another tab, then click here and log in as user einstein"
The running testpilotcloud client cannot be found in "another tab" -- if that means browser tab. If i means client tab, then I am not sure where to click, as I believe I am already locked out there.

Expected behaviour: 
a) The message should say" Hit the 'Re-open Browser' button of ownCloud Testpilot Edition, select 'Choose another account' and log in as user einstein"
b) if possible avoid https://github.com/owncloud/ocis/issues/865

**Comment by TheOneRing** [comment]
Loging out and signing in with the correct account is the solution that works 100% of the time, not all servers might offer a user selection.
