### ISSUE TITLE
[QA] Virus checker alerts

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8233]
https://download.owncloud.com/desktop/ownCloud/testing/2.7.0.2443/win/owncloudclient-2.7.0.2443-vfs.x64.msi
https://www.virustotal.com/gui/url/e563a702745e66815fa35dafb97debb8af68e1f675fa245323710faedb107286/detection
![image](https://user-images.githubusercontent.com/1108546/99420401-73d35a00-28fd-11eb-89f7-f68909e58c6a.png)

Anything we can do about that?

**Comment by jnweiger** [comment]
All four x86.msi, x64.msi,  x86.GPO.msi, x64.GPO.msi show the same result.

**Comment by jnweiger** [comment]
When uploading owncloudclient-2.7.0.2443-vfs.x64.msi as a file, (not passed by URL), the scanners are all happy. 

 https://www.virustotal.com/gui/file/123d6c8358ddf9734d1550e0b9a44815bb8106b8f8a787866767fbbc00fd302d/detection

They run more scanners, when they get a URL than when they get a file.

**Comment by TheOneRing** [comment]
When pasting a url it evaluates the url and not the file as you can see on the details page https://www.virustotal.com/gui/file/123d6c8358ddf9734d1550e0b9a44815bb8106b8f8a787866767fbbc00fd302d/details https://www.virustotal.com/gui/url/e563a702745e66815fa35dafb97debb8af68e1f675fa245323710faedb107286/details
