### ISSUE TITLE
Rename context menu entry "Settings" to "Show"

### ISSUE THREAD

**Issue by hosy** [owncloud/client#8234]
### Expected behaviour
As an user I would like to open the activity view right from the status bar menu, without opening the Settings.

<img width="235" alt="Bildschirmfoto 2020-11-18 um 10 24 47" src="https://user-images.githubusercontent.com/736109/99511602-c3129c80-2988-11eb-8dec-1fdd5b226a3b.png">

Furthermore it would be nice, to show the activity items in a separate window.

### Actual behaviour
Activity items only accessible via settings window

### Client configuration
Client version:
2.7.0

Operating system:
macOS 11

**Comment by michaelstingl** [comment]
> Furthermore it would be nice, to show the activity items in a separate window.

Why would this make a difference?

**Comment by hosy** [comment]
The settings window suggest to have only `settings` inside. In the web view we also separate the activity items from the settings. For me it is not intuitive to show into the settings window when I want to have a look at the activity items. It would be a better clean-up of the UI.

**Comment by TheOneRing** [comment]
Ok we reworked the whole "Settings window" its now just the UI, so we might want to rename the entry "Settings" to "Show"?

**Comment by fmoc** [comment]
Perhaps "Show" is a bit too short (likely to lead to misleading translations). How about renaming it to "Maximize"?

**Comment by TheOneRing** [comment]
it doesn't maximize :D
"Open"
"Open ownCloud"

**Comment by HanaGemela** [comment]
ownCloud 3.0.0.8922-alpha9
macOS 13.0

Expected behaviour: The original request was to add Show option to display Activities. 
Actual behaviour: Settings option was removed completely and Show ownCloud option displays the tab that was opened as last. Not activities

**Comment by HanaGemela** [comment]
@hosy I've just noticed the title says to remove Settings. But you attached a screenshot to add a new entry Show. So what is the expected behaviour?

**Comment by TheOneRing** [comment]
Its expected see the pr
