### ISSUE TITLE
[QA] Client loops in uploading without progress

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8235]
Tested with 2.7.1 on windows 10
* create a folder 'Music~' in the sync folder.
* the folder is ignored due to its ~ suffix.
* populate the folder with a few *.mp3 files.
* restart the client (actually I had created the folder with 2.7.0-rc3 client, then upgraded to 2.7.1)
* rename the folder from 'Music~' to 'Music' so that upload would start.
  -> Windows immediately shows the folder as busy uploading 

![image](https://user-images.githubusercontent.com/1108546/99557194-b14deb00-29c2-11eb-985e-0524ce0572f0.png)

The client activity view scrolls quickly with 'ignored messages'
![image](https://user-images.githubusercontent.com/1108546/99556737-32f14900-29c2-11eb-98b2-4581faa512ae.png)

[logs.zip](https://github.com/owncloud/client/files/5561326/logs.zip)

Expected behaviour: the upload succeesds, as the folder is no longer ignored.

**Comment by TheOneRing** [comment]
The file is still on the ignore list, there is a timeout for the ignore...
