### ISSUE TITLE
[QA] 32bit win10 client fails on a 64bit system with unhelpful message

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8239]
Just for the records: if win10 users report
"This application failed to start because no QT platform plugin could be initialized."
![image](https://user-images.githubusercontent.com/1108546/99687970-8a0c2200-2a85-11eb-81e2-66c8422a5d59.png)

it most likely means they have a 32 vs 64 bit architecture mismatch.
Could the installer catch that?

**Comment by TheOneRing** [comment]
I guess you manged to install a 32bit install into a 64bit one....
Can you reproduce and did the same error occur after a reboot?
