### ISSUE TITLE
[QA] client loops fast trying to log in a blocked user

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8241]
Tested with testpilotcloud 2.7.1 (build 2529) Nov 18 2020 08:46:25
connected to a server setup via docker-compose-eos-test.yml from branch `fix-yml-for-rc5` on localhost

* connect the client as user einstein and wait for inital sync to complete

From the WEB UI:
* log in as moss, 
* visit the accounts page, select einstein and chose 'Block'.

The activated column for einstein shows a red cross. OK.
After ca 1min the desktop client shows
![image](https://user-images.githubusercontent.com/1108546/99708434-1aeef780-2a9e-11eb-8113-9514932b8fd0.png)

* the 'Browser erneut öffnen' button does not open a browser session. BAD. 
* debug log output starts scrolling fast. [tp-1119_1804.log.zip](https://github.com/owncloud/client/files/5568955/tp-1119_1804.log.zip)

Expected behaviour: re-open browser should reopen the browser. The client handles the blocked user the same as below:

After a restart of the client an error message appears:
![image](https://user-images.githubusercontent.com/1108546/99708218-d7948900-2a9d-11eb-832a-69bb0aca023a.png)

**Comment by TheOneRing** [comment]
Might have been fixed by https://github.com/owncloud/client/commit/170678b9eb26f2c06fc260cccd16dbb2b236b355#diff-3e5d8f11959bb9efacd329a29f1b224916ec6a57d00da7b6f5e4aefb82f6fe69

**Comment by TheOneRing** [comment]
I assume the issue has been fixed.
