### ISSUE TITLE
Client green but files missing locally

### ISSUE THREAD

**Issue by bornakke** [owncloud/client#8243]
### Expected behaviour
That all files and folders should be avaiable in local folder

### Actual behaviour
Some folders and files are never downloaded by the client dispite the client showing the green 'all-good' logo in tray and on folder.

### Steps to reproduce
1. Connect client to server
2. Let it sync
3. Navigate to the specific subfolder and only one of the files will be there.

I have earlier had a similar issue which related to a folder name being 

### Server configuration
Operating system: Ubuntu 18.04

Web server: Apache 2.4.29

Database: MySQL 5.7

PHP version: 7.2

ownCloud version: 10.5.0.10

### Client configuration
Client version: 2.7.1

Operating system: Windows 10

OS language: English

Installation path of client:

### Logs

No related errors or warnings appear neither in the client log file, webserver or owncloud server. That is the big trouble :(

1. Client logfile: No errors. Everything returns 200 OK or nothing to check. 
2. Web server error log: Nothing related to owncloud
3. Server logfile: 104 MB, but I have searcherd for the specific files and they do not appear.

**Comment by michaelstingl** [comment]
Mounted/external storages?

**Comment by bornakke** [comment]
> 
> 
> Mounted/external storages?

Nope

**Comment by quwip10** [comment]
I am running into a similar issue with two Windows 10 clients. It was showing good, but when moving or adding files within the client folders, it was not updating on the server despite saying good to go. I tried everything I could think of and eventually completely removed the account from the PC and uninstalled the client. Now I can add the account, but it won't sync. It just says waiting for sync. This is happening on two Win10 PCs, but all the Macs and iPhones connected work fine and the Web works fine...

**Comment by bornakke** [comment]
Apparently there were a trailing space in the foldername which made it not sync. Earlier i have experienced something similar with uncommon charecters in foldername. Owncloud shoudl have some kind of warning when this happens in order to debug the problem
