### ISSUE TITLE
owncloud-client-nautilus and friends are missing in Fedora and CentOS

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8252]
With 2.7.1 https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/
has owncloud-client-nautilus, -nemo, -caja, -dolphin packages only for openSUSE, Debian, and Ubuntu. 
They are missing all CentOS and all Fedora versions. 

This is a regression. We had them in 2.6.3 as seen in e.g. https://download.opensuse.org/repositories/isv:/ownCloud:/desktop/CentOS_8/x86_64/

@dschmidt are there any explosions in drone that we did not notice?

**Comment by dschmidt** [comment]
doubt it.

I rather assume that some rpm macros are undefined ...

**Comment by dschmidt** [comment]
Fixed in dailies.
