### ISSUE TITLE
[QA] Linux Mint is missing

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8260]
2.7.1 final builds do not offer Linux Mint for download.
https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/

![image](https://user-images.githubusercontent.com/1108546/100353175-6baaa700-2fee-11eb-98e6-01b6ac1b1ed8.png)

Expected behaviour:
* Ubuntu 18.04 is also available as "Linux Mint 19"
* Ubuntu 20.04 is also available as "Linux Mint 20"

**Comment by cClaude** [comment]
Is this planned? It will be nice.

**Comment by TheOneRing** [comment]
Appimage is planned for 2.8
