### ISSUE TITLE
[QA] Repetitive requestors

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8263]
Client 2.7.1 on Ubuntu 20.04 connected to demo.owncloud.com 
* Keep it connected over night.
* Demo.owncloud.com resets itself every hour. Requestors accumulate. A total of 14 requestors, nicely arranged in three stacks.
![image](https://user-images.githubusercontent.com/1108546/100538245-dcd89d00-322e-11eb-8c13-9ff74530d8e3.png)
![image](https://user-images.githubusercontent.com/1108546/100538347-786a0d80-322f-11eb-917b-40839f8ed64d.png)

Expected behaviour: One requestor is sufficient.

**Comment by jnweiger** [comment]
Retested with the appimage found in https://github.com/owncloud/client/pull/8265/checks?check_run_id=1473544279

As soon as the first requester comes up, the connection shows the yellow pause icon. OK
Waiting for furhter requesters....

**Comment by TheOneRing** [comment]
Thx for testing, I fixed the remaining issue

**Comment by jnweiger** [comment]
Confirmed fixed. Only one requestor, even after multiple server resets over night.

Followup nitpick: #8275
