### ISSUE TITLE
Linux Qt-Creator build runtime issue

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#8264]
### Actual behaviour

Building the current client in QtCreator on openSUSE 15.2 or Tumbleweed results in an disturbing issue: The build is fine, but when I start the client app in the creator using the start or debug button, the following runtime error is displayed:

```
13:11:05: Starte /mnt/crypthome/kf/projects/build-client-Desktop-Debug/bin/owncloud ...
/mnt/crypthome/kf/projects/build-client-Desktop-Debug/bin/owncloud: symbol lookup error: /mnt/crypthome/kf/projects/build-client-Desktop-Debug/bin/owncloud: undefined symbol: _ZN3OCC10SyncEngine21aboutToRemoveAllFilesENS_12SyncFileItem9DirectionESt8functionIFvbEE
13:11:05: /mnt/crypthome/kf/projects/build-client-Desktop-Debug/bin/owncloud wurde mit dem Rückgabewert 127 beendet
```

The created app however is running when started from the command line.

I tried different compiler (gcc, clang) and different versions, even of QtCreator. Other projects build in Creator and also run.
The error is always the same. 

### Steps to reproduce
1. Clone client and build it in QtCreator on openSUSE Linux
2. Try to start it in QtCreator

I am out of ideas. @ogoffart any hint?

**Comment by ogoffart** [comment]
Maybe Qt Creator does not set the LD_LIBRARY_PATH correctly?

**Comment by TheOneRing** [comment]
Was fixed in chat
