### ISSUE TITLE
[QA] AppImage forgets config after restart

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8267]
Download a linux AppImage from e.g. https://github.com/owncloud/client/pull/8265/checks?check_run_id=1473544279

* run the AppImage client from a shell and create connections.
* end the clinet with e.g. CTRL-C 
* re-run

![image](https://user-images.githubusercontent.com/1108546/100761121-d135d380-33f2-11eb-84bd-87d1e3e4550a.png)
All sync connections fail to reconnect. BAD.
State seems to be "logged in", as a 'logout' action is offered.

Expected behaviour: The folder sync connections either reconnect automatiallly (when basic auth) or the user gets prompted for oauth/oidc

**Comment by TheOneRing** [comment]
We need to compile qtkeychain with libsecret

**Comment by TheOneRing** [comment]
2.8 nighties are build with libsecret and should be able to save credentials on gnome

**Comment by fmoc** [comment]
@jnweiger please retry with the lastest RC AppImage build. The issue should be fixed there.

**Comment by gabi18** [comment]
> @jnweiger please retry with the lastest RC AppImage build. The issue should be fixed there.

Confirmed fixed with 2.10.0 AppImage builds.
