### ISSUE TITLE
[QA] "Remove all" requestor blocks the UI

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8275]
![image](https://user-images.githubusercontent.com/1108546/100937242-00cc0500-34f3-11eb-81f8-fa546882a05c.png)

I have two connections in the screenshot. While one is waiting for user interaction, it should be possible to interact with the other connections, or check activity or pause syncing, etc.

**Comment by TheOneRing** [comment]
It blocks the ui to force the user to a decision
