### ISSUE TITLE
[QA] progress bar jumps forward when file download restarts

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8279]
Client 2.7.2 on Linux connected to ocis-1.0.0-rc6 deployed via hetzner-deploy/make_ocis_eos_compose_test.sh

* connect client to server as user moss, wait for initial sync
* throttle the client bandwidth to 100kb download speed.
* add an 11 MB file to the server (in a different way, not through this client)
* the client starts downloading.
* when half of the file is downloaded, (after ca 1min) quit the client and restart the client.
* The half downloaded file gets truncated. Most likely a server issue here. -> #8280 Okayish.
* the progress bar restarts at the already downloaded position, ca 50%, and starts showning wrong values. BAD
![image](https://user-images.githubusercontent.com/1108546/101064870-c024c800-3594-11eb-81b2-0e4a78362ce0.png)
* when the size of the temporary file is ca 6MB, the progress bar reaches 100% and hangs there while the file continues to download.

Expected behaviour: When a file download restarts, the progress bar also restarts.

**Comment by TheOneRing** [comment]
See https://github.com/owncloud/client/issues/8280
