### ISSUE TITLE
[QA] client should fallback to NG or V1, when TUS fails

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8286]
Setup as per https://github.com/owncloud/ocis/issues/997
This server configuration is broken. It advertises TUS in the capabilities, but TUS uploads cannot work. 
Although the fix is a serverside fix, the desktop client should handle the situation better. 
Currently it simply fails to upload anyting. 

For improved robustness, the client should switch from TUS to CHUNKING_NG and probe if this protocol works.

Forcing the switch via `env OWNCLOUD_NO_TUS=1 owncloud` demonstrates that it uploads fine now.

**Comment by michaelstingl** [comment]
As far as I know, oCIS never learned chunking V1 or NG, and clients should not fallback to stuff that’s not in the capabilities. 

If capabilities announce TUS, but TUS isn’t working, we could discuss if clients should fallback to big plain PUT. I’d tend to not go that route.

**Comment by jnweiger** [comment]
Starting the client with OWNCLOUD_NO_TUS=1 does big PUT requests with this ocis server.

IMO, syncing that way, is way better than not syncing at all. Succeding in syncing must always be a top prio -- syncing beautifully is a bonus of course.

Attached log was produced with the following commands in the client sync folder:
```
mkdir testpics
cp ~/Pictures/testpics_3/* testpics
cp ~/xxl/50MB.zip testpics/
```

The three small files from testpics_3 upload fine with one PUT each, the 50MB file causes an internal error 500 during upload, gets redownloaded from the server correcctly, so we know the upload is in fact fine.
[tp-1206_0000.log.zip](https://github.com/owncloud/client/files/5648023/tp-1206_0000.log.zip)

**Comment by TheOneRing** [comment]
I don't think we should implement any complicated logic in the client to handle a broken server 🤷
