### ISSUE TITLE
Virtual sync placeholders not working - Windows 10 problem?

### ISSUE THREAD

**Issue by Tenivar** [owncloud/client#8294]
Relate to https://central.owncloud.org/t/virtual-file-sync-no-longer-working-properly/29388 ; similar system, except that my storage is not external.
The virtual sync is not working for files (works for folders!) in folders and subfolders, contained in the owncloud synced folder.
When freeing up space/beginning new synchronisation, the client says it creates the virtual file, and then send a deletition request to the server. The "virtual file" is not even displayed and removed immediately in the explorer.
Creating a new file in the windows explorer, in a folder where there are files displayed in the web UI, but not in the explorer - because client just says "Virtual file successfully created" (or similar), without actually displaying a cloud file - results in deleting all files in the (sub) folder server side, replacing the contents with the newly created file.
The issue is not only for the last client version (2.7.2). I have tested the two previous version (2.7.1 and 2.6.3) that show the exact same behavior. The problem may be a windows update, since it used to work when I used those versions...
![image](https://user-images.githubusercontent.com/29178195/101833498-60e92980-3b39-11eb-8754-23800b04fc2c.png)

**Comment by michaelstingl** [comment]
@Tenivar please provide the information from [the template](https://raw.githubusercontent.com/owncloud/client/master/.github/issue_template.md)

**Comment by michaelstingl** [comment]
Work goes on in https://github.com/owncloud/client/issues/8295
