### ISSUE TITLE
Crash on sync .ini files (virtual file system)

### ISSUE THREAD

**Issue by efrenbg1** [owncloud/client#8298]
Constant crash on new client 2.7.3 with virtual file system (.ini files causing crash?).

### Expected behaviour
Client should sync all files.

### Actual behaviour
When syncing client stops working and crashes. Last file synced is .ini and removing it makes it possible to advance the sync process until another .ini files is synced. Both x86 and x86_64 clients crash.

### Steps to reproduce
1. Place .ini file in owncloud server
2. Sync client with virtual file system
3. Wait until client crash

### Server configuration
Operating system: debian 10 (Linux 4.19.0 - amd64)

Web server: nginx/1.14.2

Database: 10.3.25-MariaDB

PHP version: 7.2.34

ownCloud version: 10.5.0

Storage backend (external storage): none

### Client configuration
Client version: 2.7.3

Operating system: Windows 10 Pro 20H2

OS language: Spanish

Qt version used by client package (Linux only, see also Settings dialog): none

Client package (From ownCloud or distro) (Linux only): none

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs
1. Client logfile: 
12-12 11:08:36:078 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job OCC::GETFileJob finished for "/10_TRABAJOS/00_ARCHIVAR/1000. TCSD - {sensible data ommited}/Documentación técnica/190906_DOC PARA 5.1, 5.2/5.2.3_Documentación técnica/desktop.ini"
12-12 11:08:36:079 [ debug sync.networkjob.get ]	[ OCC::GETFileJob::slotReadyRead ]:	Actually finished!

2. Web server error log: none

3. Server logfile: ownCloud log (data/owncloud.log): none

**Comment by jnweiger** [comment]
Since client 2.4.0 the name `desktop.ini` is hardcoded as an excluded file. Strange.

**Comment by jnweiger** [comment]
When /Photos/desktop.ini was already synced, and I add Photos/Desktop.ini on the server, we get an error (maybe unrelated to your crash):
```
12.12.2020 04:06:09, Photos/Desktop.ini, ownCloud2,CfCreatePlaceholders error WindowsError: ffffffff80070780: Das System kann auf die Datei nicht zugreifen. : WindowsError: ffffffff80070780: Das System kann auf die Datei nicht zugreifen. for Photos/Desktop.ini

**Comment by dragotin** [comment]
@efrenbg1 could you add the term `desktop.ini` to your sync ignore list please? That will be a workaround for you.

I am up to propose a PR to fix this. I think we never should sync the desktop.ini.

**Comment by efrenbg1** [comment]
> The name `desktop.ini` is hardcoded as an excluded file: https://github.com/owncloud/client/blob/master/src/csync/csync_exclude.cpp#L203
> when it sits in the top folder. In subfolders it syncs just fine for me. Is the exact contents of you desktop.ini file critical to reproduce the crash?

The owncloud instance, while updated not so long ago, is somewhat old (maybe the exclude was hardcoded afterwards?). I will write back as soon as I've tested everything proposed (will take a while to sync everything). 

Many thanks for your quick responses!

**Comment by efrenbg1** [comment]
Indeed both suggestions fix the problem. I've tried to:
1. Remove al desktop.ini and add the filename to 'blacklisted_files'
2. Add the desktop.ini to the sync ignore list

> am up to propose a PR to fix this. I think we never should sync the desktop.ini.
That would be the right thing to do. Even though the client app should not crash, this filename should be avoided both at the client and backend sides.
