### ISSUE TITLE
2.8

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#8308]
- [ ] Qt 5.15
  - https://doc.qt.io/qt-5/qregularexpression.html#wildcardToRegularExpression
  - https://doc.qt.io/qt-5/qfile.html#moveToTrash
- [ ] c++17, at least for Windows
  - [ ] [[nodiscard]] where applicable Q_REQUIRED_RESULT older platforms

**Comment by saschaeggi** [comment]
Please include a native Mac M1 (ARM) build
