### ISSUE TITLE
Properly display parent Window when displaying a dialog

### ISSUE THREAD

**Issue by dimstudio** [owncloud/client#8313]
### Expected behaviour
OwnCloud to behave normally

### Actual behaviour
After migration to a new Macbook, my OwnCloud client gave unverifiable account authentication. I deleted the certificates from the Keychain Access and I got logged out completely. Now my UI is not responding. In the dialogue in the screenshot below, I cannot edit nor click. I tried to download and install the client again from the website. The problem persists. 

![image](https://user-images.githubusercontent.com/8708230/102596674-caf56600-4119-11eb-8e98-130b7c33a508.png)

### Steps to reproduce
1. Delete ownCloud certificates from KeyChain 
2. UI is not responsive

### Client configuration
Client version: latest downloaded from website
Operating system: MacOS big Sur 11.1
OS language: English
Installation path of client: standard

**Comment by TheOneRing** [comment]
Does killing the client and starting it again help?
Deleting credentials from the keychain while the client is running is not a supported use case.

**Comment by dimstudio** [comment]
No, it doesn't help. Any idea how to delete my settings and reconfigure my client again? I thought reinstalling the client would help but it didn't.

**Comment by TheOneRing** [comment]
Just to be sure does a reboot help?
And you are using 2.7.3?

**Comment by dimstudio** [comment]
> Just to be sure does a reboot help?
No rebooting doesn't help
> And you are using 2.7.3?
Yes correct

**Comment by TheOneRing** [comment]
I can reproduce your issue.
The client is meant to block actions until you entered the new credentials.
At least on my system the input field works, cancel works too.
That the rest of the ui looks like in your secreenshot, well that's a bug.
Clicking on the system tray icon and clicking on "Settings..." will bring the proper ui back.

**Comment by dimstudio** [comment]
> At least on my system the input field works, cancel works too.

The dialog is unresponsive, I am not able to edit the field.

> Clicking on the system tray icon and clicking on "Settings..." will bring the proper ui back.

That's correct. The tray icon is working but the dialog is still shown and there is no option to cancel it or edit it

**Comment by dimstudio** [comment]
The problem is present on all 2.7.x versions. I resolved reverting back to v2.6.3
