### ISSUE TITLE
Owncloud client crashing with nextcloud

### ISSUE THREAD

**Issue by Marcus6699** [owncloud/client#8315]
### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. to open owncloud agent
2. in mount folder owncloud, i tried open to edit a file with status sync.
3. Owncloud stop and crashed with log:
2580e5cf-1112-4273-acce-046697c93712
and the other time:
4a3675bc-bc25-4718-85a2-5f2262f48898 

### Server configuration
Operating system:"Ubuntu 18.04.5 LTS"

Web server: nginx/1.14.0

Database:  5.7.32-0ubuntu0.18.04.1

PHP version: 7.3.24-3

ownCloud version: Nextcloud 19.0.4

Storage backend (external storage):

### Client configuration

Client version: 2.7.3

Operating system: Windows 10

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by TheOneRing** [comment]
Hi while we can't officially support your setup, could you send us the last few lines of the log, right when your client crashes.
