### ISSUE TITLE
[QA] VFS on Win10 is not "recommended" setting in connection wizard 

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8317]
Test on Win10 Pro 20H2
https://download.owncloud.com/desktop/ownCloud/testing/2.7.4-rc1.2909/win/ownCloud-2.7.4-rc1.2909.x64.msi

* start client
* connect to demo.owncloud.org 
* the connection wizards shows several options:

![image](https://user-images.githubusercontent.com/1108546/102765558-0e9bda00-437d-11eb-904b-c8754dcc2637.png)

* The first option (VFS) is default selected. OK
* But the second option "syncthonize everything" says "(recommended)". BAD

Expected behaviour: the default selection is "(recommended)".

**Comment by TheOneRing** [comment]
Good point, I stopped reading those strings a loooong time ago.

**Comment by jnweiger** [comment]
Suggest to also rephrase the second option to say
"Synchronize immediately" instead of "Synchronize everything"

"Everything" was always so wrong, because only this option allows selective sync, "Choose what to sync"
(The VFS always exposes the the entire tree, no selective sync is available, that is what I'd call "Everything" ...)

**Comment by michaelstingl** [comment]
> "Synchronize immediately"

Also wrong because of initial discovery will need some time with bigger accounts.

**Comment by jnweiger** [comment]
> > "Synchronize immediately"
> 
> Also wrong because of initial discovery will need some time with bigger accounts.

"There is no such thing as immediate" -- I know :-)

The discovery time is the same overhead, with or without VFS. That also can take long with VFS. 
(Possibly even longer, as selective sync cannot be used to skip the unimportant. )

**Comment by TheOneRing** [comment]
Fixed in https://github.com/owncloud/client/pull/8348/files
The fix will only go to master as we don't want to break the translations.

**Comment by jnweiger** [comment]
> > "Synchronize immediately"
> 
> Also wrong because of initial discovery will need some time with bigger accounts.

This argument is moot. We advertise VFS as the opposite of `immediate` so we can identify the opposite of vfs as immediate. (Just in case we want to make things self explanatory through logic)

![image](https://user-images.githubusercontent.com/1108546/130379950-c9aacbaa-4f9d-4910-bca6-00d65eea1035.png)
