### ISSUE TITLE
Crash on missing sync root

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8321]
Test on Win10 Pro 20H2
https://download.owncloud.com/desktop/ownCloud/testing/2.7.4-rc1.2909/win/ownCloud-2.7.4-rc1.2909.x64.msi

* make multipl connections to multiple servers, some with VFS some without.
* remove all connections from the client gui
* quit the client
* remove all the left over ownCloud* sync folders from the filesystem. Okayish 
* empty trashcan
* start the client. It crashes. BAD

![image](https://user-images.githubusercontent.com/1108546/102775940-2760bb80-438e-11eb-88ee-eac98c5073c8.png)
Sent! Many thanks. Please refer to crash 27953ce4-d0f7-4396-9bbf-4b14368b214c in bug reports.

Removing AppData/Local/ownCloud does not help. Another crash:

Sent! Many thanks. Please refer to crash 5f4329bc-8784-4f32-9f39-249f5b01186f in bug reports.

Workaround: Manually remove AppData/Roaming/ownCloud
now the client can be started again.

**Comment by jnweiger** [comment]
Also reproduced with a branded client.

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/pull/7994

**Comment by jnweiger** [comment]
Reproduced by @iHerrmann77 with 2.7.5-RC1

**Comment by TheOneRing** [comment]
Fixed in 2.9
