### ISSUE TITLE
[QA] online updater fails to detect corrupt download

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8325]
Test on Win10 Pro 20H2
https://download.owncloud.com/desktop/ownCloud/stable/2.7.4.2934/win/ownCloud-2.7.4.2934.x64.msi

* Start with desktop client 2.6.3 up and running.
* switchto the Settings page, the online updater eventually reports an available update to 2.7.4
* Click Install & Restart
* A small requester appears, confirm
* The requester disaperars, and reappears 2 seconds later. No error messages given. BAD
* inspect %AppData%/ownCloud, the downloaded msi installer package is there. It is only 8MB. Too short. 

Expected behaviour: the truncated download is detected and redownloaded.

Workaround: manually remove the corrupt msi installer packakge.

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/issues/2435

**Comment by TheOneRing** [comment]
Duplicate of https://github.com/owncloud/client/issues/7390
