### ISSUE TITLE
[Feature Request] Disable Overlay Icons Setting

### ISSUE THREAD

**Issue by NiklasVoigt** [owncloud/client#8330]
Please add a feature to disable overlay icons of the owncloud client.

**Comment by michaelstingl** [comment]
I don’t get it. What is the real world problem you’re trying to solve? Maybe you can elaborate on your use case.

**Comment by NiklasVoigt** [comment]
This is a feature request.
Every synced file gets an overlay icon. Some People dont want that.
A way to disable the Overlay Icons is delete the keys using regedit (Windows) from
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\ShellIconOverlayIdentifiers`
but after you update the client you have to do this. Very annoying.

An option to turn on/off in the Settings of the Client to disable the Icons in the Explorer would be a nice feature!

**Comment by michaelstingl** [comment]
@NiklasVoigt 2.7 desktop client on Win10 no longer use overlay icons. It uses the Explorer native Status column. (check screenshot in https://github.com/owncloud/client/issues/7747)

Does this already solve your problem?

**Comment by NiklasVoigt** [comment]
Oh yes this is a great Feature! This solves the Problem.
