### ISSUE TITLE
Inaccessible trash / deleted file recovery (2.7.2 client)

### ISSUE THREAD

**Issue by audouts** [owncloud/client#8331]
The 2.7.2 client deleted hundreds of thousands of files from our server.

We get an error, when trying to access the "Trash" via the web interface.
(_This directory is unavailable, please check the logs or contact the administrator_)

The recovery script is unusable because it will take hundreds of days for it to recover the files.
(https://github.com/JanAckermann/owncloud-restore-trash)

Is there any way to address the error in the web interface?

**Comment by TheOneRing** [comment]
Please follow the discussion in https://github.com/owncloud/client/issues/8295 

Duplicate: https://github.com/owncloud/client/issues/8295

**Comment by audouts** [comment]
The 2.7.2 client deleted hundreds of thousands of files from our server.

We could not access the "Trash" via the web interface:
`This directory is unavailable, please check the logs or contact the administrator`

The recovery script was unusable because it will take hundreds of days for it to recover the files.
(https://github.com/JanAckermann/owncloud-restore-trash)

I could not find a way to use `propfind` to get the file ID, which the ownCloud docs describe in the webDAV, TrashBin API. I made a minor change that allowed me to get the file IDs and then dumped a list with `propfind`. I then used the TrashBin API "restore" call and tried to restore the files.

Approximately 92% of the files succeeded. We now face other problems:

First, when I try the TrashBin API restore call, it says that the file already exists. It does not. I cannot find it anywhere in the database (except the trash and the history, showing it was deleted). It's not in the filesystem.

Second, the web interface works now (presumably due to the lower number of files) but has no way of selecting files before/after a certain date. I don't want to restore files that were intentionally deleted before the client bug started deleting everything.

I decided to try using the TrashBin API to delete files from the trash, before a certain date. That brings me to the third problem. Apparently, I can only delete one file at a time via the API. I get an error about it being "locked" if I try to run concurrent calls. It's taking 70-80 seconds per delete, which means it will take days to complete this relatively small operation.

What can we do to solve this?

**Comment by audouts** [comment]
#8295 is apparently closed. What should I do?
