### ISSUE TITLE
Client update automation

### ISSUE THREAD

**Issue by xmana** [owncloud/client#8332]
### Expected behaviour
the client should update automatically

### Actual behaviour
If an update is available, the client prompts you to install the update.

### Steps to reproduce
nothing

### Server configuration
Operating system:
Ubuntu
VERSION="16.04.3 LTS (Xenial Xerus)"

Web server: 
nginx version: nginx/1.13.8
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.5)
built with OpenSSL 1.0.2g 1 Mar 2016
TLS SNI support enabled

Database:
mysql Ver 15.1 Distrib 10.0.31-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

PHP version:
PHP 7.0.22-0ubuntu0.16.04.1 (cli) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
with Zend OPcache v7.0.22-0ubuntu0.16.04.1, Copyright (c) 1999-2017, by Zend Technologies

ownCloud version:
ownCloud 10.0.4

Storage backend (external storage):
file storage on the local server partition

### Client configuration
Client version:
2.7.4

Operating system:
Win 7 Pro x64

OS language:
Ukrainian

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
"C:\Program Files (x86)\ownCloud\owncloud.exe"

### Remark

We currently have over 300 remote offices. Each of the offices exchanges files with the central office using Owncloud. In most offices, computers with the client installed are used by people who do not have a specific computer education. Very often, a situation occurs when employees answer "no" to a client update request.
Is it possible to add an option to the client settings to disable update notification and update the client automatically?

**Comment by michaelstingl** [comment]
You should disable auto update, then use the MSI to deploy new versions on all the remote machines. 

In the server config.php, you can also set min. client version, so only newer versions can access the ownCloud server. 

No background-auto-update is planned.

**Comment by xmana** [comment]
OK. Understandably. Thanks for the information.
