### ISSUE TITLE
[VFS] Linux (Nautilus) Context menu missing items

### ISSUE THREAD

**Issue by cfalas** [owncloud/client#8334]
### Expected behaviour
Whenever I right click on any synced file, I would expect Nautilus to have the options to share, keep locally, free up space, etc as in the screenshot below.
![image](https://user-images.githubusercontent.com/34488895/103307163-55d23c80-4a07-11eb-9b63-e04f46105be0.png)

### Actual behaviour
Sometimes, only some of the options are shown, as in the screenshot below.
![image](https://user-images.githubusercontent.com/34488895/103306264-11de3800-4a05-11eb-8ee4-f21b05b1c7af.png)
This also seems to be the case in Nemo. In Dolphin, it either shows all options, or there's no ownCloud context menu at all.

### Steps to reproduce
1. Add a new account on ownCloud client
2. Sync a few files
3. Right click on a file in Thunar
Sometimes this works as expected (rarely for me, but sometimes restarting both the ownCloud client and the file manager seems to work). Still haven't found when it works and when it doesn't

### Server configuration
Operating system: Ubuntu 18.04
Web server: Apache2
Database: MariaDB
PHP version: 7.2.24
ownCloud version: 10.5.0

Storage backend (external storage): None

### Client configuration
Client version: 2.7.4 (44d154)
Operating system: Arch Linux with kernel 5.9.14
OS language: English
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only): 
Installation path of client: 5.15.2

### Logs

I am only including a client logfile since I don't think that the others are relevant. This is the logfile for the second during which I right click on a single folder.
```
12-29 21:01:39:299 [ info gui.socketapi ]:	Received SocketAPI message <-- "GET_MENU_ITEMS:/<file_path>" from QLocalSocket(0x55ae74950700)
12-29 21:01:39:299 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_MENU_ITEMS:BEGIN" to QLocalSocket(0x55ae74950700)
12-29 21:01:39:299 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 -6092617122107506663
12-29 21:01:39:299 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE phash=?1"
12-29 21:01:39:299 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 -6092617122107506663
12-29 21:01:39:299 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE phash=?1"
12-29 21:01:39:300 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:SHARE::Share..." to QLocalSocket(0x55ae74950700)
12-29 21:01:39:300 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:COPY_PUBLIC_LINK::Copy public link to clipboard" to QLocalSocket(0x55ae74950700)
12-29 21:01:39:300 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:COPY_PRIVATE_LINK::Copy private link to clipboard" to QLocalSocket(0x55ae74950700)
12-29 21:01:39:300 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:OPEN_PRIVATE_LINK::Open in browser" to QLocalSocket(0x55ae74950700)
12-29 21:01:39:300 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 "<file_path>"
12-29 21:01:39:300 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT pinState FROM flags WHERE ((?1 == path OR (?1 > (path||'/') AND ?1 < (path||'0'))) OR path == '') AND pinState is not null AND pinState != 0 ORDER BY length(path) DESC LIMIT 1;"
12-29 21:01:39:339 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 "<file_path>"
12-29 21:01:39:339 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT DISTINCT pinState FROM flags WHERE ((path > (?1||'/') AND path < (?1||'0')) OR ?1 == '') AND pinState is not null and pinState != 0;"
12-29 21:01:39:346 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 "<file_path>"
12-29 21:01:39:346 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT DISTINCT type FROM metadata WHERE ((path == ?1 OR (path > (?1||'/') AND path < (?1||'0'))) OR ?1 == '');"
12-29 21:01:39:414 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:CURRENT_PIN:d:Available online only" to QLocalSocket(0x55ae74950700)
12-29 21:01:39:414 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:MAKE_AVAILABLE_LOCALLY::Make always available locally" to QLocalSocket(0x55ae74950700)
12-29 21:01:39:414 [ info gui.socketapi ]:	Sending SocketAPI message --> "MENU_ITEM:MAKE_ONLINE_ONLY:d:Free up local space" to QLocalSocket(0x55ae74950700)
12-29 21:01:39:414 [ info gui.socketapi ]:	Sending SocketAPI message --> "GET_MENU_ITEMS:END" to QLocalSocket(0x55ae74950700)
```
Notice that all of the correct options are sent through the socket to the Nautilus extension. In this case, just like in the screenshot above, there's no "public" link option, but instead there is a "send link by email". Even though I am not very familiar with the client codebase, this looks like the legacy menu items [here](https://github.com/owncloud/client/blob/master/shell_integration/nautilus/syncstate.py#L282-L339)

**Comment by cfalas** [comment]
Increasing the timeout in the [extension code](https://github.com/owncloud/client/blob/0b67e0cc7a5411da0db57311c8aeda7e76c5d442/shell_integration/nautilus/syncstate.py#L240) (I increased it to 0.5) seems to resolve the case in my issue.

**Comment by jnweiger** [comment]
Wow, great spotting, I was not aware, we have such a tight timeout there! 0.1sec is definitly too low.
