### ISSUE TITLE
Feature request - just use as file browser without syncing

### ISSUE THREAD

**Issue by stylefieber** [owncloud/client#8342]
Sometimes the virtual file system has its downsides, for example when there are a lot of files (x TB of mixed sized files) the initial sync lasts hours. Or sometimes it isn't very stable and tries to resync folders again and again.
Or for some (not tech) users, the functionality might be to complicated.

On the other hand, a complete sync of all files (without virtual files) is often not an option, when there are too many files for example.

A compromise would be just to have it implemented as a file browser like you would have it when you use ownCloud as webDAV drive (in windows), but without the limitations and bugs from the windows version. So unlimited file-size for up - and download and a working progress-bar.

Would it be hard to implement?

**Comment by michaelstingl** [comment]
> Would it be hard to implement?

try https://mountainduck.io/

**Comment by michaelstingl** [comment]
If you run macOS on the new Apple M1 chip, you can also use the new iOS app to browse files on the desktop:
https://apps.apple.com/app/id1359583808

**Comment by michaelstingl** [comment]
The mobile app for Windows should also work on desktop:
https://www.microsoft.com/en-us/p/owncloud/9pj6d2hkq1zt

**Comment by stylefieber** [comment]
> The mobile app for Windows should also work on desktop:
> https://www.microsoft.com/en-us/p/owncloud/9pj6d2hkq1zt

Thank you, but here I miss the file browser integration.

**Comment by michaelstingl** [comment]
> Thank you, but here I miss the file browser integration.

Ah, seems I misunderstood. You don't want a standalone file browser. Got it now.

**Comment by stylefieber** [comment]
> > Thank you, but here I miss the file browser integration.
> 
> Ah, seems I misunderstood. You don't want a standalone file browser. Got it now.

But Mountainduck does it very well. You can open and copy files without have it synced automatically. But you can optionally do that. Thats perfect.
I would happy to see that in the ownCloud client as well. Because Mountainduck does not have all the other features like permission / share management etc.

**Comment by TheOneRing** [comment]
We currently have no plans to implement a file browser right now.
Instead we intend to improve the current Windows Virtual Files implementation and find similar solutions for the other platforms.

> tries to resync folders again and again.

that might already be fixed in the nighties.
