### ISSUE TITLE
Files Get autodeleted when  desktop owncloud app is run

### ISSUE THREAD

**Issue by tejaspandhare007** [owncloud/client#8345]
### Expected behaviour
Files should not get autodeleted when owncloud app is sync

### Actual behaviour
FIles get autodeleted from shared directories

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system: Centos8.2

Web server: 
apache 2.4
Database:
Mariadb 10.3
PHP version:
7.3.21
ownCloud version:
10.6
Storage backend (external storage):
Internal filesystem
### Client configuration
Client version:2.7.3 and 2.7.3

Operating system:
windows 10
OS language:
English US
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by TheOneRing** [comment]
If a user deletes files in a shared folder, they have write access too, those files get deleted for everyone.
Is that what you are describing here?

**Comment by tejaspandhare007** [comment]
Hi,

 

We have one shared directory which is accessed by multiple people. 

e.g. HR department. One of the user when starts desktop apps, some of the files get deleted for everyone after automatic sync and we see those files under deleted items on shared directory.

 

Any help on this is greatly appreciated. 

Note: We recently updated owncloud server version to 10.6 

 

 

Tejas Pandhare

www.mLogica.com

**Comment by TheOneRing** [comment]
Please make sure no one is still using a Windows client < 2.7.3 
See https://owncloud.com/news/important-windows-client-issue-fix-available/
Steps to restore the data are discussed in https://github.com/owncloud/client/issues/8295

**Comment by tejaspandhare007** [comment]
Ok, we have 2.7.3 users with the same issues. I did update to 2.7.4.

 

Tejas Pandhare

www.mLogica.com

**Comment by TheOneRing** [comment]
Under certain conditions, when the sync with 2.7.2 was aborted while the error occurred, 2.7.3+ continues to sync the deletes.
The only solution here is to stop the deleting client and delete  the sync_*.db in the sync root to reset the sync.

**Comment by tejaspandhare007** [comment]
Another  case is that, user is using web url to download and after download files are deleted from shared storage. Screen shot attached

**Comment by TheOneRing** [comment]
It doesn't look like attachments are handled by github email replies

**Comment by tejaspandhare007** [comment]
Never mind, I think we will have to update clients to 2.7.4 I think. Any way if we can prevent this on older versions.

**Comment by TheOneRing** [comment]
Don't update Windows before updating to the ownCloud client

**Comment by tejaspandhare007** [comment]
Ok.
