### ISSUE TITLE
[QA] CHANGELOG.md in 2.7.5-RC1 is not up to date

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8351]
The changelog found in https://download.owncloud.com/desktop/ownCloud/testing/2.7.5-rc1.3035/source/ownCloud-2.7.5-rc1.3035.tar.xz
start with
<hr>

Changelog for ownCloud Desktop Client [unreleased] (UNRELEASED)
=======================================

The following sections list the changes in ownCloud Desktop Client unreleased relevant to
ownCloud admins and users.

[unreleased]: https://github.com/owncloud/client/compare/v2.6.3...master

Summary
-------

* Bugfix - Some check boxes in the sharing dialog are disabled: [#7877](https://github.com/owncloud/client/issues/7877)
* Change - Don't hardcode a plugin location: [#3839](https://github.com/owncloud/enterprise/issues/3839)
* Change - Enabling native VFS on Windows create two shortcuts in the Explorer: [#7748](https://github.com/owncloud/client/issues/7748)
* Change - The password dialog is hidden behind a window: [#7833](https://github.com/owncloud/client/issues/7833)
* Change - The client uploads chunks even though the server repports lack of support: [#7862](https://github.com/owncloud/client/issues/7862)
* Change - Mac does not display a dock entry: [#7868](https://github.com/owncloud/client/issues/7868)
* Change - Option to log HTTP requests and responses: [#7873](https://github.com/owncloud/client/issues/7873)
* Change - The layout of serveral ui elements is broken: [#7920](https://github.com/owncloud/client/issues/7920)
* Change - The client hides the window during the authentication process: [#7922](https://github.com/owncloud/client/pull/7922)
* Change - The settings ui shows a prompt for a few seconds: [#7925](https://github.com/owncloud/client/pull/7925)
* Change - Reorgenize Settings: [#7962](https://github.com/owncloud/client/pull/7962)
* Change - Support for OpenID Connect: [#7509](https://github.com/owncloud/client/pull/7509)
* Change - Allow OpenID Connect authentication without a .well-known configuration: [#7681](https://github.com/owncloud/client/pull/7681)
* Change - Add support for the TUS resumeable upload protocol: [#19](https://github.com/owncloud/product/issues/19)

Details
-------

<hr>

The next section below this [UNRELEASED] section is 2.6.3

Expected behaviour:
* The [UNRELEASED] section shoulld be named 2.7.5
* There should be a section 2.7.4 between 2.7.5 and 2.6.3

**Comment by TheOneRing** [comment]
Will only be up to date in the release.

**Comment by jnweiger** [comment]
Unchanged with RC2
