### ISSUE TITLE
Owncloud client icon not appearing Ubuntu 18.04 Gnome 3

### ISSUE THREAD

**Issue by montanaviking** [owncloud/client#8352]
### Expected behaviour
Owncloud client icon should appear in upper right-hand side of top bar in the Gnome 3 desktop upon logging in.

### Actual behaviour
Owncloud client icon does not appear on the Gnome 3 desktop anywhere post reboot and log-in.
# steps to reproduce
In this case, I find that ps aux command shows the Owncloud client running but with no icon on the desktop.
To work around:
1. Reboot machine and log in
2. Kill Owncloud client job.
3. Restart Owncloud client
4. The above results in apparently correct operation of the Owncloud Client and its icon now appears on the upper righthand of the Gnome 3 screen.

### Server configuration
Operating system: Ubuntu 18.04 64-bit
5.4.0-60-generic #67~18.04.1-Ubuntu SMP Tue Jan 5 22:01:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

Web server: 
Apache2
Server version: Apache/2.4.29 (Ubuntu)
Server built:   2020-08-12T21:33:25

Database:
mysql  Ver 14.14 Distrib 5.7.32, for Linux (x86_64) using  EditLine wrapper
PHP version:
PHP 7.2.24-0ubuntu0.18.04.7 (cli) (built: Oct  7 2020 15:24:25) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.24-0ubuntu0.18.04.7, Copyright (c) 1999-2018, by Zend Technologies

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:
Client: version 2.7.4 build 2934
Operating system:
Ubuntu 18.04 64-bit
5.4.0-60-generic #67~18.04.1-Ubuntu SMP Tue Jan 5 22:01:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
OS language:

Qt version used by client package (Linux only, see also Settings dialog): 
Qt5.12.9

Client package (From ownCloud or distro) (Linux only): owncloud

Installation path of client:
Ubuntu 18.04 64-bit
5.4.0-60-generic #67~18.04.1-Ubuntu SMP Tue Jan 5 22:01:05 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by TheOneRing** [comment]
@jnweiger @dschmidt how is the gnome extension called again which enables the systray?

**Comment by montanaviking** [comment]
More Information:
owncloud client logfile post log in with no icon appearing:

this file is in:
/tmp/ownCloud-logdir
#########################
cat 20210112_1325_owncloud.log.0
01-12 13:25:10:331 [ info gui.application ]:	"################## ownCloud locale:[en_US] ui_lang:[] version:[2.7.4 (build 2934)] os:[Ubuntu 18.04.5 LTS]"
01-12 13:25:10:334 [ info gui.application ]:	Using "en_US" translation
01-12 13:25:10:336 [ info gui.application ]:	Adding extra plugin search path: "/opt/ownCloud/ownCloud/bin/../lib/x86_64-linux-gnu/plugins"
01-12 13:25:10:337 [ info gui.application ]:	VFS suffix plugin is available
01-12 13:25:10:337 [ warning default ]:	QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-viking'
01-12 13:25:10:338 [ debug gui.socketapi ]	[ OCC::SocketApi::SocketApi ]:	creating "/tmp/runtime-viking/ownCloud" true
01-12 13:25:10:338 [ info gui.socketapi ]:	server started, listening at  "/tmp/runtime-viking/ownCloud/socket"
01-12 13:25:10:338 [ info gui.folder.manager ]:	setting remote poll timer interval to 30000 msec
01-12 13:25:10:401 [ info gui.account.manager ]:	Restored:  1  unknown certs.
01-12 13:25:10:421 [ debug gui.activity ]	[ OCC::ActivitySettings::setNotificationRefreshInterval ]:	Starting Notification refresh timer with  300  sec interval
01-12 13:25:10:541 [ debug gui.updater ]	[ OCC::Updater::getSystemInfo ]:Sys Info size:  87
01-12 13:25:10:541 [ debug gui.updater ]	[ OCC::Updater::create ]:	QUrl("https://updates.owncloud.com/client/?client=RGlzdHJpYnV0b3IgSUQ6CVVidW50dQpEZXNjcmlwdGlvbjoJVWJ1bnR1IDE4LjA0LjUgTFRTClJlbGVhc2U6CTE4LjA0CkNvZGVuYW1lOgliaW9uaWMK&version=2.7.4.2934&platform=linux&oem=ownCloud&buildArch=x86_64&currentArch=x86_64&versionsuffix=")
01-12 13:25:10:606 [ info gui.application ]:	Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
01-12 13:25:10:616 [ info gui.folder.manager ]:	Setup folders from settings file
01-12 13:25:10:647 [ debug gui.folder ]	[ OCC::Folder::checkLocalPath ]:	Checked local path ok
01-12 13:25:10:647 [ info sync.configfile ]:	Adding system ignore list to csync: "/etc/ownCloud/sync-exclude.lst"
01-12 13:25:10:670 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "PRAGMA quick_check;"
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT sqlite_version();"
01-12 13:25:10:796 [ info sync.database ]:	sqlite3 version "3.22.0"
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "PRAGMA locking_mode=EXCLUSIVE;"
01-12 13:25:10:796 [ info sync.database ]:	sqlite3 locking_mode= "exclusive"
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "PRAGMA journal_mode=WAL;"
01-12 13:25:10:796 [ info sync.database ]:	sqlite3 journal_mode= "wal"
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "PRAGMA synchronous = NORMAL;"
01-12 13:25:10:796 [ info sync.database ]:	sqlite3 synchronous= "NORMAL"
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "PRAGMA case_sensitive_like = ON;"
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "DROP INDEX IF EXISTS metadata_parent;"
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE TABLE IF NOT EXISTS metadata(phash INTEGER(8),pathlen INTEGER,path VARCHAR(4096),inode INTEGER,uid INTEGER,gid INTEGER,mode INTEGER,modtime INTEGER(8),type INTEGER,md5 VARCHAR(32),PRIMARY KEY(phash));"
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE TABLE IF NOT EXISTS downloadinfo(path VARCHAR(4096),tmpfile VARCHAR(4096),etag VARCHAR(32),errorcount INTEGER,PRIMARY KEY(path));"
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE TABLE IF NOT EXISTS uploadinfo(path VARCHAR(4096),chunk INTEGER,transferid INTEGER,errorcount INTEGER,size INTEGER(8),modtime INTEGER(8),contentChecksum TEXT,PRIMARY KEY(path));"
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE TABLE IF NOT EXISTS blacklist (path VARCHAR(4096),lastTryEtag VARCHAR[32],lastTryModtime INTEGER[8],retrycount INTEGER,errorstring VARCHAR[4096],PRIMARY KEY(path));"
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE TABLE IF NOT EXISTS async_poll(path VARCHAR(4096),modtime INTEGER(8),filesize BIGINT,pollpath VARCHAR(4096));"
01-12 13:25:10:796 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE TABLE IF NOT EXISTS selectivesync (path VARCHAR(4096),type INTEGER);"
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE TABLE IF NOT EXISTS checksumtype(id INTEGER PRIMARY KEY,name TEXT UNIQUE);"
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE TABLE IF NOT EXISTS datafingerprint(fingerprint TEXT UNIQUE);"
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE TABLE IF NOT EXISTS flags (path TEXT PRIMARY KEY,pinState INTEGER);"
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE TABLE IF NOT EXISTS conflicts(path TEXT PRIMARY KEY,baseFileId TEXT,baseEtag TEXT,baseModtime INTEGER);"
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE TABLE IF NOT EXISTS version(major INTEGER(8),minor INTEGER(8),patch INTEGER(8),custom VARCHAR(256));"
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:797 [ debug sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "checkConnect" and starting new transaction
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "PRAGMA table_info('metadata');"
01-12 13:25:10:797 [ debug sync.database ]	[ OCC::SyncJournalDb::tableColumns ]:	Columns in the current journal: QVector("phash", "pathlen", "path", "inode", "uid", "gid", "mode", "modtime", "type", "md5", "fileid", "remotePerm", "filesize", "ignoredChildrenRemote", "contentChecksum", "contentChecksumTypeId")
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE INDEX IF NOT EXISTS metadata_inode ON metadata(inode);"
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:797 [ debug sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "update database structure: add inode index" and starting new transaction
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE INDEX IF NOT EXISTS metadata_path ON metadata(path);"
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:797 [ debug sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "update database structure: add path index" and starting new transaction
01-12 13:25:10:797 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE INDEX IF NOT EXISTS metadata_parent ON metadata(parent_hash(path));"
01-12 13:25:10:800 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:800 [ debug sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "update database structure: add parent index" and starting new transaction
01-12 13:25:10:801 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "PRAGMA table_info('uploadinfo');"
01-12 13:25:10:801 [ debug sync.database ]	[ OCC::SyncJournalDb::tableColumns ]:	Columns in the current journal: QVector("path", "chunk", "transferid", "errorcount", "size", "modtime", "contentChecksum")
01-12 13:25:10:801 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "PRAGMA table_info('conflicts');"
01-12 13:25:10:801 [ debug sync.database ]	[ OCC::SyncJournalDb::tableColumns ]:	Columns in the current journal: QVector("path", "baseFileId", "baseEtag", "baseModtime", "basePath")
01-12 13:25:10:801 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "PRAGMA table_info('blacklist');"
01-12 13:25:10:801 [ debug sync.database ]	[ OCC::SyncJournalDb::tableColumns ]:	Columns in the current journal: QVector("path", "lastTryEtag", "lastTryModtime", "retrycount", "errorstring", "lastTryTime", "ignoreDuration", "renameTarget", "errorCategory", "requestId")
01-12 13:25:10:801 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "CREATE INDEX IF NOT EXISTS blacklist_index ON blacklist(path collate nocase);"
01-12 13:25:10:801 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	Last exec affected 0 rows.
01-12 13:25:10:801 [ debug sync.database ]	[ OCC::SyncJournalDb::commitInternal ]:	Transaction commit "checkConnect End" 
01-12 13:25:10:801 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT COUNT(*) FROM metadata"
01-12 13:25:10:801 [ info gui.folder.manager ]:	Adding folder to Folder Map  OCC::Folder(0x562e8065dd80) "1"
01-12 13:25:10:801 [ debug gui.folderwatcher ]	[ OCC::FolderWatcherPrivate::slotAddFolderRecursive ]:	(+) Watcher: "/data/owncloud/"
01-12 13:25:16:328 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/data/owncloud/python/fixturecalc/.idea"
01-12 13:25:16:328 [ debug gui.folderwatcher ]	[ OCC::FolderWatcherPrivate::slotAddFolderRecursive ]:	* Not adding "/data/owncloud/python/fixturecalc/.idea"
01-12 13:25:16:328 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/data/owncloud/python/fixturecalc/.idea/inspectionProfiles"
01-12 13:25:16:328 [ debug gui.folderwatcher ]	[ OCC::FolderWatcherPrivate::slotAddFolderRecursive ]:	* Not adding "/data/owncloud/python/fixturecalc/.idea/inspectionProfiles"
01-12 13:25:16:328 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/data/owncloud/python/fixturecalc_dialog/.idea"
01-12 13:25:16:328 [ debug gui.folderwatcher ]	[ OCC::FolderWatcherPrivate::slotAddFolderRecursive ]:	* Not adding "/data/owncloud/python/fixturecalc_dialog/.idea"
01-12 13:25:16:328 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/data/owncloud/python/fixturecalc_dialog/.idea/inspectionProfiles"
01-12 13:25:16:328 [ debug gui.folderwatcher ]	[ OCC::FolderWatcherPrivate::slotAddFolderRecursive ]:	* Not adding "/data/owncloud/python/fixturecalc_dialog/.idea/inspectionProfiles"
01-12 13:25:16:348 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/data/owncloud/python/probe_database/.idea"
01-12 13:25:16:348 [ debug gui.folderwatcher ]	[ OCC::FolderWatcherPrivate::slotAddFolderRecursive ]:	* Not adding "/data/owncloud/python/probe_database/.idea"
01-12 13:25:16:348 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/data/owncloud/python/probe_database/.idea/inspectionProfiles"
01-12 13:25:16:348 [ debug gui.folderwatcher ]	[ OCC::FolderWatcherPrivate::slotAddFolderRecursive ]:	* Not adding "/data/owncloud/python/probe_database/.idea/inspectionProfiles"
01-12 13:25:16:355 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/data/owncloud/python/smithchartgamma/.idea"
01-12 13:25:16:355 [ debug gui.folderwatcher ]	[ OCC::FolderWatcherPrivate::slotAddFolderRecursive ]:	* Not adding "/data/owncloud/python/smithchartgamma/.idea"
01-12 13:25:16:355 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/data/owncloud/python/smithchartgamma/.idea/inspectionProfiles"
01-12 13:25:16:355 [ debug gui.folderwatcher ]	[ OCC::FolderWatcherPrivate::slotAddFolderRecursive ]:	* Not adding "/data/owncloud/python/smithchartgamma/.idea/inspectionProfiles"
01-12 13:25:16:356 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/data/owncloud/python/waferprobe/.idea"
01-12 13:25:16:356 [ debug gui.folderwatcher ]	[ OCC::FolderWatcherPrivate::slotAddFolderRecursive ]:	* Not adding "/data/owncloud/python/waferprobe/.idea"
01-12 13:25:16:356 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/data/owncloud/python/waferprobe/.idea/inspectionProfiles"
01-12 13:25:16:356 [ debug gui.folderwatcher ]	[ OCC::FolderWatcherPrivate::slotAddFolderRecursive ]:	* Not adding "/data/owncloud/python/waferprobe/.idea/inspectionProfiles"
01-12 13:25:16:371 [ debug gui.folderwatcher ]	[ OCC::FolderWatcherPrivate::slotAddFolderRecursive ]:	    `-> and 1284 subdirectories
01-12 13:25:16:372 [ info gui.folder.manager ]:	Schedule folder  "1"  to sync!
01-12 13:25:16:372 [ info gui.folder.manager ]:	Folder is not ready to sync, not scheduled!
01-12 13:25:16:372 [ info gui.application ]:	Sync state changed for folder  "https://localhost/owncloud/remote.php/webdav/" :  "Not yet Started"
01-12 13:25:16:372 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 3
01-12 13:25:16:372 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path FROM selectivesync WHERE type=?1"
01-12 13:25:16:372 [ info sync.clientproxy ]:	Set proxy configuration to use system configuration
01-12 13:25:16:387 [ debug gui.folderwatcher ]	[ OCC::FolderWatcher::pathIsIgnored ]:	* Ignoring file "/data/owncloud/.owncloudsync.log"
01-12 13:25:16:390 [ debug default ]	[ unknown ]:	static bool LibSecretKeyring::findPassword(const QString&, const QString&, QKeychain::JobPrivate*)
01-12 13:25:16:412 [ debug default ]	[ unknown ]:	static bool LibSecretKeyring::findPassword(const QString&, const QString&, QKeychain::JobPrivate*)
01-12 13:25:16:413 [ debug default ]	[ unknown ]:	static bool LibSecretKeyring::findPassword(const QString&, const QString&, QKeychain::JobPrivate*)
01-12 13:25:19:280 [ info gui.updater ]:	Checking for available update
01-12 13:25:19:280 [ info sync.accessmanager ]:	2 "" "https://updates.owncloud.com/client/?client=****deleted for security************&version=2.7.4.2934&platform=linux&oem=ownCloud&buildArch=x86_64&currentArch=x86_64&versionsuffix=" has X-Request-ID "3dee16d3-78df-426b-b66f-6df382dcf4e8"
01-12 13:25:19:280 [ debug sync.cookiejar ]	[ OCC::CookieJar::cookiesForUrl ]:	QUrl("https://updates.owncloud.com/client/?client=********deleted for securty********&version=2.7.4.2934&platform=linux&oem=ownCloud&buildArch=x86_64&currentArch=x86_64&versionsuffix=") requests: ()
01-12 13:25:19:980 [ info gui.updater ]:	Client is on latest version!
01-12 13:25:45:797 [ info gui.application ]:	Running for 35.527 sec
01-12 13:25:45:800 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 3
01-12 13:25:45:801 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path FROM selectivesync WHERE type=?1"

**Comment by jnweiger** [comment]
Afaik, Gnome removed the tray icon functionality.
"As a workaround", we made all menu elements we had on the tray icon available from the settings page.
The way to open the settings page is to click on the owncloud icon for a second time.

**Comment by TheOneRing** [comment]
You can also right click the desktop file to access some actions.

**Comment by jhenion209** [comment]
I am also seeing this on the Windows 10 Pro client. Seems to only be happening with large files >50GB. Seems to ignore the files after a few connection closed errors.

**Comment by TheOneRing** [comment]
> 
> 
> I am also seeing this on the Windows 10 Pro client. Seems to only be happening with large files >50GB. Seems to ignore the files after a few connection closed errors.

Hi @jhenion209 did you accidentally respond to the wrong issue?
What issue are you experiencing.
