### ISSUE TITLE
[QA] broken GUI on gnome3 after logout/login 

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8355]
Client 2.7.5rc1 on Debian 10.7.0

Installed via `apt-get install owncloud-client-nautilus`
When first started the client operates normally. 
After logout/login, the gui looks like this:

![image](https://user-images.githubusercontent.com/1108546/104474114-facf4680-55bd-11eb-8a23-eb0eed7648e0.png)
The gui elements take focus when clicked, but do not do anything.

Expected behaviour: owncloud-client still works normally after logout/login

Workaround: Kill the owncloud client from the shell and restart. That brings back the correct GUI.

**Comment by TheOneRing** [comment]
Duplicate https://github.com/owncloud/client/issues/8354
