### ISSUE TITLE
[QA] branded client does not show wizard icon

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8358]
## tested with testpilotcloud-client 2.7.5-rc1 on Ubuntu-20.04

* click '+' for new account, the connection wizard page shows.
* the client shows empty whitespace in the top righthand corner:

![image](https://user-images.githubusercontent.com/1108546/104583914-070cdf80-5662-11eb-9b58-f77ffb7339f8.png)

Expected behaviour: according to ownbrander there should be a wizard logo on the top righthand corner.

**Comment by jnweiger** [comment]
## Reproduced also with 2.7.5-rc1 on macos mojave:
![image](https://user-images.githubusercontent.com/1108546/104635348-0d22b080-56a2-11eb-93cc-9a514e2199fa.png)

**Comment by TheOneRing** [comment]
Testpilot cloud needs a regeneration.

**Comment by jnweiger** [comment]
Please don't close be for the fix.
I'll retrigger a build from ownbrander. Is that what you mean with 'regeneration'

**Comment by jnweiger** [comment]
Confirmed fixed in testpilotcloud 2.7.5daily20210115 (build 3064)
![image](https://user-images.githubusercontent.com/1108546/104757625-921ed000-575d-11eb-8153-7c645e530882.png)
