### ISSUE TITLE
"Remove all dialog": Keep files will make the dialog pop up again and again

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#8360]
After clicking on keep files, a  new dialog pops up which asks to keep all files or remove all.

Might have been a special scenario, local db was deleted and all files on the remote where deleted.

**Comment by gabi18** [comment]
Couldn't reproduce the issue that the 'Remove all' dialog popups again and again.
- deleted all folder and files on server,  clicked on 'Keep files' -> the popup didn't reappear
- deleted all folder and files locally, same as above

**Comment by gabi18** [comment]
When testing to delete all both on server and locally the popup also appears once. 
Clicking on 'Keep files' cannot restore the files but they are still visible in the client.

[20210216_1611_owncloud.log.1.gz](https://github.com/owncloud/client/files/5989764/20210216_1611_owncloud.log.1.gz)

![all_deleted](https://user-images.githubusercontent.com/75983861/108085659-dca1ae00-7075-11eb-8c8a-0571762626d9.png)

**Comment by gabi18** [comment]
I could reproduce the issue on Windows 10 with VFS enabled.

Steps done:
1. Enable VFS support in client
2. Delete all folder/files on server
3. The 'Keep files / Remove files' popup appears
4. Click 'Keep files' 
   Result: virtual folder/files are kept locally - no attempt to resync (see #8442)
5. Quit owncloud-client and restart
6. 'Keep files / Remove files' popup appears
   Result: client tries to resync after clicking 'Keep files' but doesn't succeed and the popup appears again and again

**Comment by gabi18** [comment]
> I could reproduce the issue on Windows 10 with VFS enabled.
> 
> Steps done:
> 
>     1. Enable VFS support in client
> 
>     2. Delete all folder/files on server
> 
>     3. The 'Keep files / Remove files' popup appears
> 
>     4. Click 'Keep files'
>        Result: virtual folder/files are kept locally - no attempt to resync (see [[QA] No re-sync from client to server after 'Keep files'  #8442](https://github.com/owncloud/client/issues/8442))

NOT relevant here (for Windows VFS On), the issue above was reported for Linux

> 
>     5. Quit owncloud-client and restart

No need to restart on Windows, the popup appears again and again after clicking 'Keep files'. The files which should be kept are virtual - no chance to keep them.

> 
>     6. 'Keep files / Remove files' popup appears
>        Result: client tries to resync after clicking 'Keep files' but cannot succeed (because of VFS) and the popup appears again and again

**Comment by gabi18** [comment]
[keep-files.log.gz](https://github.com/owncloud/client/files/9037732/keep-files.log.gz)

**Comment by fmoc** [comment]
TODO:

- abort current sync and pause sync root before displaying dialog
- if keep files: keep current behavior (removing all hacks from the code), start new sync to upload the files again
- if remove all files: remove all files and start a new sync cycle

**Comment by nabim777** [comment]
Seen with ownCloud-5.0.0.11398--daily20230707 b0734d ([download link](https://download.owncloud.com/desktop/ownCloud/daily/5.0/win/ownCloud-5.0.0.11398-daily20230707.x64.msi)) on Windows 10 Enterprise Evaluation :

- the popup appears again and again when clicking "Keep files"

![Screenshot from 2023-07-10 12-10-04](https://github.com/owncloud/client/assets/61624650/f460501d-c2ad-4706-a1f5-fe23cd1cd7fe)

- "Remove all files" stops the endless loop but only removes the dehydrated files and keeps the hydrated
![Screenshot from 2023-07-10 12-14-45](https://github.com/owncloud/client/assets/61624650/6f3406fb-fad1-418a-9cbd-743e37e0eb56)
[ownCloud-0709_23.16.33.080.log](https://github.com/owncloud/client/files/11998934/ownCloud-0709_23.16.33.080.log)

**Comment by Salipa-Gurung** [comment]
<b>Tested on:</b> Windows10
<b>ownCloud version:</b> ownCloud 5.0.0.11398-daily20230707

### Deleting all the files on the server 
- In case of hydrated and saturated files, both `Keep files` and `Remove all files` option works and `Remove All Files` dialog appears only once. :heavy_check_mark: 
- In case of dehydrated files, `Keep files` option does not work with the dehydrated files(VFS on) ❌ and `Remove All Files` dialog appears again and again. `Remove all files` option removes all the files. 
[ownCloud-0710_01.56.28.604.log.gz](https://github.com/owncloud/client/files/11999897/ownCloud-0710_01.56.28.604.log.gz) 

 ![keep-file-error](https://github.com/owncloud/client/assets/53458341/642e4bf9-4310-4233-bdc4-b568cf5fea2e)  


### Deleting all the folders on the server
- In case of dehydrated, hydrated and saturated folders both `Keep files` and `Remove all files` option works accordingly:heavy_check_mark:
- `Remove All Files` dialog appears only once :heavy_check_mark:

**Comment by TheOneRing** [comment]
It makes sense @michaelstingl

**Comment by Salipa-Gurung** [comment]
### Client version
ownCloud 5.0.0.11438-daily20230712 0f63d2
Libraries Qt 6.4.3, OpenSSL 3.1.1 30 May 2023
Using virtual files plugin: wincfapi
windows-10.0.19045

### Deleting all the `files only` on the server  
- In case of hydrated and `Always keep on this device` files, both `Keep files` and `Remove all files` option works and `Remove All Files` dialog appears only once. :heavy_check_mark: 

- In case of dehydrated file, 
  - `Remove All Files` dialog does not appear again and again.
  - `Remove all files` button removes the files :heavy_check_mark: 
  - `Keep files` button does not keep the file ❌ [ instead it removes the dehydrated file ]

     [ownCloud.log](https://github.com/owncloud/client/files/12026333/ownCloud.log)

> Dehydrated files inside folder also gets deleted when `keep files` button clicked. ❌ 

### Deleting all the folders (empty folders) on the server
- In case of dehydrated, hydrated and `Always keep on this device` folders both `Keep files` and `Remove all files` option works accordingly :heavy_check_mark:
- `Remove All Files` dialog appears only once :heavy_check_mark:

**Comment by TheOneRing** [comment]
@Salipa-Gurung @michaelstingl this is expected behavior.
At least if I understand the scenario correctly.
You have dehydrated placeholders locally and all files are removed on the server, this means the virtual files do no longer exist.
We have to remove the local placeholders as they are already gone.

**Comment by Salipa-Gurung** [comment]
so, can it be closed then?

**Comment by michaelstingl** [comment]
> so, can it be closed then?

yes, close
