### ISSUE TITLE
Unable to see NSLog messages when debugging FinderSync Extention

### ISSUE THREAD

**Issue by MikeHibbert** [owncloud/client#8365]
I'm trying to learn about FinderSync and have managed to build the owncloud FinderSync with XCode 12.3 on Big Sur

However, when I run it I can see my debug log appear but none of the NSLog statements are being shown there as they do with other projects.

Is there something I need to configure to enable them?

**Comment by TheOneRing** [comment]
@hosy do you have an idea 😊

**Comment by TheOneRing** [comment]
@MikeHibbert I assume you added some log messages to your build, as our code only has 3 log call on errors.

**Comment by felix-schwarz** [comment]
@MikeHibbert Depending on your log settings, you might not see much in the Console.app's main log. IIRC `NSLog` does log to `system.log` however, so you might see `NSLog` messages pop up there.
