### ISSUE TITLE
[FR] Share window: Expire Date DD.MM.YYY:  Format is hardcoded --> Format OS System Settings

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#8367]
This Feature Request is a matter of the expire date representation when setting up a share via the context menu.
At the moment, the date is shown hardcoded as DD.MM.YYYY
This should be changed according the System Settings of the OS
If the setting can not be aquired, a default of YYYY.MM.DD should be used.

### Expected behaviour
Date representation according the OS System Setting

### Actual behaviour
Hardcoded date representation DD.MM.YYYY

### Steps to reproduce
1. Open share dialogue via context menu
2. Set an exiration date

### Client configuration
Client version: 2.7.4

Operating system: W10x64Pro

OS language: DE

@TheOneRing

**Comment by fmoc** [comment]
@mmattel I am pretty sure I fixed the issue in #8541, but we couldn't really reproduce the issue without the ability to set a custom language in #8493. The only plausible scenario is that the date picker used the system locale whereas the UI used a theme-enforced locale. Please check whether that was the case, so we can estimate whether #8541 really fixes this issue, alternatively we'll have to dig deeper.

**Comment by jnweiger** [comment]
confirmed fixed. These three incovations produce three differnt date formats in the public link dialog
* `LANG=C LANGUAGE=C LC_ALL=C testpilotcloud-2.9.0-beta3.5019.AppImage` -> 26 Aug 2021
* `LANG=de_DE LANGUAGE=de_DE LC_ALL=de_DE testpilotcloud-2.9.0-beta3.5019.AppImage` -> 26.08.21
* `LANG=en_US LANGUAGE=en_US LC_ALL=en_US testpilotcloud-2.9.0-beta3.5019.AppImage` -> 8/26/21
