### ISSUE TITLE
[QA] macOS: settings window does not open when starting again

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8377]
Seen with 2.7.5RC2

Start the client. If the settings window is open, hide it.
Find a desktop icon of the owncloud client.
Click the icon. the settings window should open.

On Windows and Linux it is possible to open the settings window, when clicking on the desktop icon.
On macOS the icons are unresponsive. Nothing happens with: Click, double click, or right click -> open. 

I find two "desktop icons": one in the dock at the bottom of the screen, anotherone in the Applications folder.
![image](https://user-images.githubusercontent.com/1108546/105040980-c26ab500-5a62-11eb-9228-1f7f97e325cb.png)

Epected behaviour: The first click starts the client. (Tray icon appears at the top). The second click opens the settings window.

**Comment by TheOneRing** [comment]
@felix-schwarz can we register a second invocation?
We use qsingle application and use ipc to communicate with the original instance.
As mac prevents multiple instances this of course does not work...

**Comment by TheOneRing** [comment]
@jnweiger unrelated to this release

**Comment by felix-schwarz** [comment]
@TheOneRing If you try to relaunch a running app or click it in the dock, the app should receive a `kAEReopenApplication` AppleEvent. You should be able to get notified by implementing this AppDelegate method:

https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428638-applicationshouldhandlereopen?language=objc#

**Comment by TheOneRing** [comment]
Thx

**Comment by gabi18** [comment]
Confirmed with client version 2.8 rc1.
When closing the client with the 'Hide' button on any window (not only 'Settings') it cannot be opened by clicking the dock icon.
This works, if the dialog is closed using minimize ![Bildschirmfoto 2021-05-04 um 10 03 37](https://user-images.githubusercontent.com/75983861/116975934-b8428e80-acc0-11eb-925e-cb1d5c78b7ca.png), the dock icon shows a dot ![Bildschirmfoto 2021-05-04 um 10 08 07](https://user-images.githubusercontent.com/75983861/116976190-1bccbc00-acc1-11eb-9155-1a703a83116b.png) then.

If the dock icon doesn't have the dot, the client window can only be opened by clicking on sys tray icon (and choosing 'Details) at the top ![Bildschirmfoto 2021-05-04 um 10 12 42](https://user-images.githubusercontent.com/75983861/116976642-baf1b380-acc1-11eb-9a26-2fffbcdc0dd4.png)

**Comment by gabi18** [comment]
The behavior on client start is similar. Clicking on the dock icon (single/double click) starts the client but the window isn' t opened. Also here one have to use the systray icon on top.
Exception here is: if the client opens the Connection window to configure an account, the window and the client appear.

**Comment by TheOneRing** [comment]
@erikjv Could you have a look :)

**Comment by erikjv** [comment]
This should be handled by Qt by sending a `QEvent::ApplicationActivate`. (Well, if nobody messed with the delegate, etc.)

**Comment by TheOneRing** [comment]
I think I tried to use that event before, but it did not behave as expected....
