### ISSUE TITLE
[QA] Bad error message with architecture mismatch on Windows

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8380]
Seen with 2.7.5rc2 on a 32bit installation of Windows 8.1

The 32bit client installs fine, (left)
The 64bit client produces an error messge (right)

![image](https://user-images.githubusercontent.com/1108546/105066197-f81d9700-5a7e-11eb-82d2-ae066c4a14ad.png)

----

The error message is misleading:
 a) the processor type fine. The system is 32bit - that is the problem.
 b) the product vendor should not be contacted. - we deliverer binaries for both already.

Expected behaviour: "You are trying to install a 64bit client on a 32bit system. This is not supported."

**Comment by TheOneRing** [comment]
Nothing we can change. That's Windows.
