### ISSUE TITLE
[QA] Folderlist Service Unavailable

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8388]
## tested with testpilotcloud-client 2.7.5rc2 against oc-10.6.0 with openiconnect-2.0.0

* login the client with the IDP. 
* wait until initial sync completes, the log-out in the client gui.
* try click open the selectev folder list. It does not open. OK.

* re-login the client using the IDP.
* click open the selective folder list
![image](https://user-images.githubusercontent.com/1108546/105527801-7333b700-5ce4-11eb-9cfc-63b2ca4b7765.png)
* a force sync does not change this.

expected behaviour: the list would refresh as soon as the client is connected again.

**Comment by TheOneRing** [comment]
Sounds a bit like https://github.com/owncloud/client/issues/7363
