### ISSUE TITLE
Enhancement: notify all clients of existing sync issues

### ISSUE THREAD

**Issue by ltomuta** [owncloud/client#8392]
We are a team using a shared folder synced through ownCloud. However, many a times a Mac user copies something there and forgets to check if folder name is legit for Windows users. As per specifications, a folder having ilegal characters in the name is not synced but only the owner of those files is notified of the problem.

### Expected behaviour
My suggestion is that the error status should propagate to all the clients so that:
- everybody knows that there is new content but it is not synced (and who the originator is)
- everybody gets a chance to correct the problem by triggering a rename (this I was able to do from the Web GUI, but not form the client, where the broken folder is not shown at all)

### Actual behaviour
All other parties aside from the originator (and not even him/her if not careful) are unaware that new content should be available to them.

**Comment by TheOneRing** [comment]
@michaelstingl I think something like that should be better handled on the server.
With a switch to disable it for sub trees.

**Comment by TheOneRing** [comment]
@michaelstingl @pmaier1 @dragotin
