### ISSUE TITLE
[QA] macOS Big Sur 11.1 dark mode broken with certain display settings

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#8400]
Installed: testpilotcloud 2.7.5rc4

Dark mode selected.

Some buttons or tabs are completely white.
Color of buttons in popups changes if focus isn't on client main window.

See screenshots:
<img width="808" alt="Bildschirmfoto 2021-01-28 um 16 08 22" src="https://user-images.githubusercontent.com/75983861/106158738-5ab01a80-6184-11eb-97ca-a02ce1a5123e.png">
<img width="866" alt="Bildschirmfoto 2021-01-28 um 16 01 39" src="https://user-images.githubusercontent.com/75983861/106158806-6e5b8100-6184-11eb-9c77-b7eecce0f4a8.png">
<img width="807" alt="Bildschirmfoto 2021-01-28 um 16 00 57" src="https://user-images.githubusercontent.com/75983861/106158847-79161600-6184-11eb-8eff-f42c615ef5a8.png">

**Comment by TheOneRing** [comment]
Did you switch between the themes without restarting the client?

**Comment by gabi18** [comment]
Just retested. Quit client and start again - but same result.

**Comment by gabi18** [comment]
Tested client v2.7.5rc4 - same result
<img width="802" alt="Bildschirmfoto 2021-01-28 um 16 35 51" src="https://user-images.githubusercontent.com/75983861/106161131-e460e780-6186-11eb-9f8c-f05d58a871ea.png">

**Comment by TheOneRing** [comment]
@michaelstingl hmm the design does look flatter than the normal mac design do you know more?

**Comment by gabi18** [comment]
I have additionally scaling on.

**Comment by michaelstingl** [comment]
Yes, just display settings in @gabi18 ’s machine. Maybe compare result with macOS VM without those display settings? Maybe we found some Qt glitches about such display settings in macOS.

**Comment by gabi18** [comment]
Indeed it looks Okay in my VM MacOS 10.14.

<img width="1017" alt="Bildschirmfoto 2021-01-28 um 18 22 53" src="https://user-images.githubusercontent.com/75983861/106174963-d8c8ed00-6195-11eb-806d-d716058ffde9.png">
<img width="803" alt="Bildschirmfoto 2021-01-28 um 18 23 22" src="https://user-images.githubusercontent.com/75983861/106175027-e8e0cc80-6195-11eb-8308-6b1d92bc2602.png">

**Comment by michaelstingl** [comment]
> Indeed it looks Okay in my VM MacOS 10.14.

Maybe you can find out what exact setting breaks this. (not urgent)

**Comment by gabi18** [comment]
Ok, I will try to find out.

**Comment by TheOneRing** [comment]
Might be related to https://bugreports.qt.io/browse/QTBUG-86513
If that's the case only a update to Qt 5.15 would help.

**Comment by gabi18** [comment]
I found out which display settings cause the issue:
For the white buttons it's 'Increase contrast' from 'System Preferences' 'Accessibility' 'Display'.
The white tabs can be avoided by choosing another 'Highlight Color' e.g. blue (instead of graphite) in 'System Preferences' 'General'.
