### ISSUE TITLE
Latest version of Windows client app crashes

### ISSUE THREAD

**Issue by netzimon** [owncloud/client#8401]
### Expected behaviour
OC Windows client app should work stable in the background.

### Actual behaviour
OC Windows client app crashes unexpectedly.

### Steps to reproduce
1. Start computer and/or client app manually.
2. Wait for app to crash.
3. App crashes and asks to send crash log.

### Server configuration
Operating system: CentOS 7.8
Web server: Apache/2.4.6 (CentOS)
Database: mysql Ver 15.1 Distrib 5.5.65-MariaDB
PHP version: PHP 7.2.33
ownCloud version: ownCloud 10.5.0
Storage backend (external storage): No external storage

### Client configuration
Client version: 2.7.4
Operating system: Windows 10 Professional
OS language: Spanish
Installation path of client: C:\Program Files (x86)\ownCloud\

### Logs
Crash log with ID **61755a21-97de-45ff-9c75-28d86c5342ba** sent by client app upon crashing.

**Comment by TheOneRing** [comment]
It is a crash in Qt, could you have a look into the log file, we should see something from QWindowsNativeImage
![image](https://user-images.githubusercontent.com/200626/106168882-0fe7d000-618f-11eb-8b94-1f93495bed80.png)

**Comment by TheOneRing** [comment]
https://github.com/qt/qtbase/blob/5.12.9/src/platformsupport/fontdatabases/windows/qwindowsnativeimage.cpp#L105

**Comment by netzimon** [comment]
Found nothing from **QWindowsNativeImage** in .owncloudsync.log files. Let me know if you want me to email those logs.

**Comment by michaelstingl** [comment]
Wrong log file. Please follow these instructions:
https://doc.owncloud.com/desktop/troubleshooting.html#log-files
