### ISSUE TITLE
[QA] dynamic registration times out after 1h

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8402]
## Tested with 2.8 daily against oc10.6.0 with oidc-2.0.0rc1 and kopano konnect

Discussion started in https://github.com/owncloud/openidconnect/issues/132#issuecomment-768982643
When the client_secret expires after 1h, we don't seem to get an automatic refresh.
The client asks the user to reautheticate: 
![image](https://user-images.githubusercontent.com/1108546/106301298-d62ecc00-6257-11eb-816b-0de3872cbb55.png)
[ownCloud-logdir.zip](https://github.com/owncloud/client/files/5895005/ownCloud-logdir.zip)

**Comment by jnweiger** [comment]
Problem discussion: https://github.com/owncloud/openidconnect/issues/142

**Comment by TheOneRing** [comment]
IDP issue
