### ISSUE TITLE
[Win] Display remaining files after removal of the client

### ISSUE THREAD

**Issue by voroyam** [owncloud/client#8407]
We need at least to display the files with the paths to be displayed after the client is removed, maybe not he last page, so the user knows what files he needs to delete where to complete remove the client and or start fresh if he has issues.

Example: User configures sync folder to be a mapped drive L.

Mapped drive changes from L to P.

User starts client - client crashes.

User removes and installs client - starts client - client sees existing config file - starts - crashes.

User confused.

If we would display the config file with path at the end of the client removal wizard the user would know that he has to remove that file to fully start fresh.

**Comment by voroyam** [comment]
@michaelstingl

**Comment by michaelstingl** [comment]
> If we would display the config file with path at the end of the client removal wizard the user would know that he has to remove that file to fully start fresh.

I'd better link to the docs. This is maybe netter usability. (better copypasta from your webbrowser, you can access it later again…

**Comment by michaelstingl** [comment]
@dschmidt could we link to the uninstall docs on the last page of the Win-uninstaller?

**Comment by TheOneRing** [comment]
I think this was solved by improvements made to the documentation?

**Comment by voroyam** [comment]
nothing got solved :] 

we can improve the documentation but we can't assume all customers and users read it.

I would expect at least a link to the docs on how to remove the client and all the remnants on the last page of the uninstall wizard of the client, but from what I can see in this issue there has not been made anything in this direction.

**Comment by TheOneRing** [comment]
Some installers have the "remove all config files" checkbox but as people usually don't grasp what that means I can imagine we would get even more complains.

**Comment by TheOneRing** [comment]
I guess the best would be to include a link to the documentation

**Comment by voroyam** [comment]
@michaelstingl please advise how to proceed.

**Comment by michaelstingl** [comment]
Please check if link to docs can be added on the last screen of the uninstalled. (I already wrote this 1 Month ago in https://github.com/owncloud/client/issues/8407#issuecomment-770966968 🤔)

**Comment by voroyam** [comment]
Who, who should check? 

You pinged @dschmidt  but got no response. 

As the PO of the client you should know who can do this kind of things.

**Comment by voroyam** [comment]
another week without progress. Closing the issue. Re-Open if someone important asks for it so we can give it more prio.
