### ISSUE TITLE
OBS packages should conflict with distro packages

### ISSUE THREAD

**Issue by RealRancor** [owncloud/client#841]
Hi,

there are some reports of users which have problems using the sync client packages of the OBS after they have installed the sync client from the repositories of their distros (Debian/Ubuntu, Fedora for example):

https://github.com/owncloud/mirall/issues/597, https://github.com/owncloud/mirall/issues/247, https://github.com/owncloud/mirall/issues/832

As mentioned by @dragotin in https://github.com/owncloud/mirall/issues/832#issuecomment-22240602 its probably the best to conflict with the packages of the distros:

Fedora:
owncloud-csync-libs-0.80.0-1.fc19.x86_64
owncloud-csync-plugin-owncloud-0.80.0-1.fc19.x86_64
mirall-1.3.0-1.fc19.x86_64

Debian/Ubuntu:
http://packages.debian.org/search?keywords=mirall
http://packages.ubuntu.com/search?keywords=mirall
mirall
mirall-doc
mirall-i18n (Ubuntu)
mirall-i10n (Debian)

**Comment by ogoffart** [comment]
Closing old issue.
