### ISSUE TITLE
Desktop Sync Client Incorrectly Detects Local Changes

### ISSUE THREAD

**Issue by tuaris** [owncloud/client#8416]
The Owncloud desktop client is constantly uploading local files to the remote server, even though they have not been changed.  It seems to repeat every few hours.  See example logs from GUI: 

- https://bin.morante.net/?8e9fa73121f72daa#DcnxJF4zMLdtM1miaASSzEvpWT2F1Q7k9u5MJkfNwaD1
- https://bin.morante.net/?344e3e37e230a920#BNUPrN73BdCgyitQhyjj8CUQZcizpMYGjDvMo7xjaSGR

It says "You changed", but I did not change anything.

I am only seeing this behavior on FreeBSD and Linux.  Windows and Android do not have this problem.

### Expected behavior
Desktop client should not upload unchanged local files to remote server

### Actual behavior
Desktop client is detecting changes on local unchanged items and uploading to remote server

### Steps to reproduce
1. Start desktop client
2. Wait a few minutes

### Server configuration
Operating system: FreeBSD 11.4-RELEASE

Web server: Apache 2.4.46

Database: MySQL 5.7.32

PHP version: Originally using 7.2, recently upgraded to 7.3.  Issue persists.

ownCloud version: had 10.5, recently upgraded to 10.6 

Storage backend (external storage): Originally on Local UFS partition, later moved to remote NFS share.  Issue persists regardless of storage backend

### Client configuration
Client version: Originally using 2.6.0, upgraded to 2.7.4.  Issue persists.

Operating system: FreeBSD 12.2-RELEASE

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.15.2

Client package (From ownCloud or distro) (Linux only): 2.7.4

Installation path of client: /usr/local/bin/owncloud

### Logs

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
https://bin.morante.net/?d647381c12fbe668#3SqpNvsY6fDYtpYSZpg6a62V9kepMe8DF8Bp8e8A8iEw

2. Web server error log:
No relevent entries

3. Server logfile: ownCloud log (data/owncloud.log):
https://bin.morante.net/?3a0dcc7f3fc72574#H7oyaLxXL5SLU4DzShrAA7LM4Tm3bsGiR4vaTaNfvi5T

**Comment by TheOneRing** [comment]
Sounds like:
> -  Bugfix - Remove stray placeholders: #8326
>
>We fixed a bug where Windows Virtual Files where not handled as such and thus not removed.

Which was fixed in 2.7.5

**Comment by TheOneRing** [comment]
Sorry I should not answer tickets on the phone, didn't see the freebsd part

**Comment by TheOneRing** [comment]
Hmmm `01-18 20:58:19:933 [ warning sync.filesystem ]:	Could not get modification time for "/usr/home/redacted_username/Sync/InstantUpload/IMG_20170623_134322.jpg" with csync, using QFileInfo` is there anything special with that file or the file system?

**Comment by tuaris** [comment]
The filesystem is ZFS, but there isn't anything different about this specific installation:

```
zfs get "all" FreeBSD/usr/home
NAME              PROPERTY              VALUE                  SOURCE
FreeBSD/usr/home  type                  filesystem             -
FreeBSD/usr/home  creation              Sat Dec 12 12:39 2020  -
FreeBSD/usr/home  used                  69.7G                  -
FreeBSD/usr/home  available             136G                   -
FreeBSD/usr/home  referenced            69.7G                  -
FreeBSD/usr/home  compressratio         1.48x                  -
FreeBSD/usr/home  mounted               yes                    -
FreeBSD/usr/home  quota                 none                   default
FreeBSD/usr/home  reservation           none                   default
FreeBSD/usr/home  recordsize            128K                   default
FreeBSD/usr/home  mountpoint            /usr/home              inherited from FreeBSD/usr
FreeBSD/usr/home  sharenfs              off                    default
FreeBSD/usr/home  checksum              on                     default
FreeBSD/usr/home  compression           lz4                    inherited from FreeBSD
FreeBSD/usr/home  atime                 off                    inherited from FreeBSD
FreeBSD/usr/home  devices               on                     default
FreeBSD/usr/home  exec                  on                     default
FreeBSD/usr/home  setuid                on                     default
FreeBSD/usr/home  readonly              off                    default
FreeBSD/usr/home  jailed                off                    default
FreeBSD/usr/home  snapdir               hidden                 default
FreeBSD/usr/home  aclmode               discard                default
FreeBSD/usr/home  aclinherit            restricted             default
FreeBSD/usr/home  createtxg             14                     -
FreeBSD/usr/home  canmount              on                     default
FreeBSD/usr/home  xattr                 off                    temporary
FreeBSD/usr/home  copies                1                      default
FreeBSD/usr/home  version               5                      -
FreeBSD/usr/home  utf8only              off                    -
FreeBSD/usr/home  normalization         none                   -
FreeBSD/usr/home  casesensitivity       sensitive              -
FreeBSD/usr/home  vscan                 off                    default
FreeBSD/usr/home  nbmand                off                    default
FreeBSD/usr/home  sharesmb              off                    default
FreeBSD/usr/home  refquota              none                   default
FreeBSD/usr/home  refreservation        none                   default
FreeBSD/usr/home  guid                  11572690808527923366   -
FreeBSD/usr/home  primarycache          all                    default
FreeBSD/usr/home  secondarycache        all                    default
FreeBSD/usr/home  usedbysnapshots       0                      -
FreeBSD/usr/home  usedbydataset         69.7G                  -
FreeBSD/usr/home  usedbychildren        0                      -
FreeBSD/usr/home  usedbyrefreservation  0                      -
FreeBSD/usr/home  logbias               latency                default
FreeBSD/usr/home  objsetid              134                    -
FreeBSD/usr/home  dedup                 off                    default
FreeBSD/usr/home  mlslabel                                     -
FreeBSD/usr/home  sync                  standard               default
FreeBSD/usr/home  dnodesize             legacy                 default
FreeBSD/usr/home  refcompressratio      1.48x                  -
FreeBSD/usr/home  written               69.7G                  -
FreeBSD/usr/home  logicalused           103G                   -
FreeBSD/usr/home  logicalreferenced     103G                   -
FreeBSD/usr/home  volmode               default                default
FreeBSD/usr/home  filesystem_limit      none                   default
FreeBSD/usr/home  snapshot_limit        none                   default
FreeBSD/usr/home  filesystem_count      none                   default
FreeBSD/usr/home  snapshot_count        none                   default
FreeBSD/usr/home  redundant_metadata    all                    default
FreeBSD/usr/home  special_small_blocks  0                      default
```

Well... as I do a stat on the file I now see something with the access time and modification dates.  

Not all files are affected.  I checked my other systems and the server, they also have incorrect modify and access timestamps.  Unclear if this is a result of the bug or if it is causing the bug.

```
stat Sync/InstantUpload/IMG_20170623_134322.jpg
10202492494433145596 72534 -rw-r--r-- 1 redacted_username redacted_username 18446744073709551615 3702744 "Dec 31 19:00:00 1969" "Dec 31 19:00:00 1969" "Dec 13 05:52:23 2020" "Dec 31 19:00:00 1969" 131072 7065 0x800 Sync/InstantUpload/IMG_20170623_134322.jpg
```

Here's the same in a more familiar format 😀

```
stat -x Sync/InstantUpload/IMG_20170623_134322.jpg
  File: "Sync/InstantUpload/IMG_20170623_134322.jpg"
  Size: 3702744      FileType: Regular File
  Mode: (0644/-rw-r--r--)         Uid: ( 1001/   redacted_username)  Gid: ( 1001/   redacted_username)
Device: 18446744071790037202,1514537212   Inode: 72534    Links: 1
Access: Wed Dec 31 19:00:00 1969
Modify: Wed Dec 31 19:00:00 1969
Change: Sun Dec 13 05:52:23 2020
```

**Comment by TheOneRing** [comment]
It's probably the same issue hopefully not caused by the client 😅
@dragotin any idea?
