### ISSUE TITLE
Server reported no permissions, file ID

### ISSUE THREAD

**Issue by spacehitchhiker42** [owncloud/client#8417]
### Expected behaviour

Owncloud client should upload files in local directory to owncloud server

### Actual behaviour
Files do not upload and the client shows the error message "server reported no permissions, file id"

### Steps to reproduce
Installed owncloud client from repository.
created synced folder with virtual files enabled
copied files from external drive to synced folder

### Server configuration
Operating system: Ubuntu 18.04

Web server: Apache2

Database: Mysql

PHP version:7.2.24

ownCloud version:

Storage backend (external storage): none

### Client configuration
Client version:2.7.4

Operating system: Ubuntu 18.04

OS language:English

Qt version used by client package (Linux only, see also Settings dialog):5.12.9

Client package (From ownCloud or distro) (Linux only): From Owncloud

Installation path of client: unknown

**Comment by TheOneRing** [comment]
Please share a complete log with, http logger enabled to apps@owncloud.com .
![image](https://user-images.githubusercontent.com/200626/106864632-72c6f300-66ca-11eb-9f9c-7fa3d54811b1.png)

When you do so please update this issue.

**Comment by spacehitchhiker42** [comment]
Just sent in the log with the subject "owncloud log. server reported no permissions, file id"

**Comment by TheOneRing** [comment]
Could you provide the name of an affected file.
