### ISSUE TITLE
[QA] Missing label 'User' on Connection dialog (testpilotcloud 2.7.5 build 3222)

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#8418]
Installed:
 testpilotcloud 2.7.5 (build 3222)

Issue seen on Win10 and openSUSE 15.2

Steps done:
 'Add account'
 Connect to...  demo.owncloud.org
 'Next'

Result:
 Missing label 'User' on Connection dialog

![TestpilotWithoutUser](https://user-images.githubusercontent.com/75983861/106862270-30e87d80-66c7-11eb-9e2e-a3ff060453e1.png)
![TestpilotVersion](https://user-images.githubusercontent.com/75983861/106862277-33e36e00-66c7-11eb-9c13-46f14245bcd6.png)

[20210204_0833_owncloud.log.0.gz](https://github.com/owncloud/client/files/5924081/20210204_0833_owncloud.log.0.gz)

**Comment by jnweiger** [comment]
Also had the missing label on a 2.7.4 testpilotcloud clinet. but only on testpilotcloud clients, never had that issue on unbranded, or any other branding.

**Comment by TheOneRing** [comment]
Internal insanity

**Comment by jnweiger** [comment]
Sorry for testing things with the testpilot client. This has a long history. Please review all settings and bring them to sane defaults. I won't touch them again.
