### ISSUE TITLE
There is no documentation about the exclude file list format used by owncloudcmd

### ISSUE THREAD

**Issue by molok** [owncloud/client#8424]
The only info in the documentation (https://doc.owncloud.com/desktop/advanced_usage/command_line_client.html#exclude-list) is

_owncloudcmd requires access to an exclude list file. It must either be installed along with owncloudcmd and thus be available in a system location, be placed next to the binary as sync-exclude.lst or be explicitly specified with the --exclude switch._

there is no info on its format

**Comment by michaelstingl** [comment]
Not specific to owncloudcmd client, same file as for the GUI application. More information in the docs, default one in the repo:
- https://doc.owncloud.com/desktop/navigating.html#usingIgnoredFilesEditor-label
- https://doc.owncloud.com/desktop/architecture.html#ignored-files
- https://github.com/owncloud/client/blob/master/sync-exclude.lst
