### ISSUE TITLE
Desktop client fails to connect to server

### ISSUE THREAD

**Issue by sundowndev** [owncloud/client#8439]
My server is properly configured, it only works with HTTPS, not HTTP. But when connecting Linux client with the server, the browser redirects to `http://example.com/login/v2/grant`. Which is not accepted by the Content Security Policy. So I change manually the URL to `httpS://example.com/login/v2/grant` then click on "Authorize". The client receive the response but fails to connect.

### Expected behaviour

Client to connect with the server

### Actual behaviour

Client rejects the response, as the server is misconfigured. Because the redirection was supposed to happen with HTTP scheme, not HTTPS.

![image](https://user-images.githubusercontent.com/16480203/108043802-d396e980-7041-11eb-896c-659e9248585a.png)

### Steps to reproduce

1. Type the server URL, click on next
2. Authorize the request in the browser

### Server configuration

Operating system: Ubuntu LTS
Web server: NC v20.0.7

### Client configuration

Nextcloud version 3.1.2-20210128.185328.9398260fb-1.0~focal1
Using Qt 5.12.8, built against Qt 5.12.8
Using Qt platform plugin 'xcb'
Using 'OpenSSL 1.1.1f  31 Mar 2020'
Running on Ubuntu 20.04.2 LTS, x86_64

**Comment by michaelstingl** [comment]
> Nextcloud version 3.1.2-20210128.185328.9398260fb-1.0~focal1

This is the issue tracker for the ownCloud desktop sync app.
