### ISSUE TITLE
Mobile UI

### ISSUE THREAD

**Issue by stealthgun** [owncloud/client#8447]
**Expected behaviour:**
Open the client and log in owncloud

**Actual behaviour:**
Can't log in since "log in"-button is outside of the screen

**Steps to reproduce:**
Install client on PlasmaMobile (or Phosh)
open it
scratch your head

**Client version:**
All

**Operating system:**
Any mobile OS for the librem of pinephone

The Android version is Mobile Optimzed, but now that PinePhone and Librem 5 are getting more and more users Owncloud would be better used on one of these phones using the desktop client with a Mobile UI optimization.

With a toggle option or maybe even a build option to enable it.

This option would be great to use on my PinePhone.

**Comment by TheOneRing** [comment]
The client is not designed for a mobile platform, I don't mean the ui, I mea the sync flow.
It would just drain your battery way to fast.
Currently a mobile port is way out of scope.
