### ISSUE TITLE
Align with 10.7 sharing behavior

### ISSUE THREAD

**Issue by pmaier1** [owncloud/client#8451]
## User story
As a user I want to share with other users by entering their email address. Currently I usually get two results when I search for a user
1. the real user on the system and
2. a federated user (because federation IDs have the same syntax like email addresses). As I'm not familiar with ownCloud specifics, I don't know what a "federated" user is.
As the lookup for the "real user" takes some time in my installation, it happens that I only see the "federated user" first. When I'm too quick, I click on it and see the share failing (because there actually is no federated user; I'm looking for the real user) which I don't understand. At this point I open a support request.

## Solution approach
Change the sharing autocomplete to only display the federated user 
1. once the regular user search has finished and
2. did not find results for the input provided

As a consequence in case that the entered email address matches a known user, only show that user.

**Comment by TheOneRing** [comment]
Maybe https://github.com/owncloud/client/pull/7564

**Comment by michaelstingl** [comment]
@TheOneRing could you check if we just render the API response, or if we construct the result with some local magic?

![CleanShot 2021-03-12 at 10 41 30@2x](https://user-images.githubusercontent.com/214010/110922215-b8a55580-831f-11eb-9d93-4b6036e35085.png)

![CleanShot 2021-03-12 at 10 44 56](https://user-images.githubusercontent.com/214010/110922619-31a4ad00-8320-11eb-84ff-a323e770b910.png)

**Comment by TheOneRing** [comment]
@michaelstingl https://github.com/owncloud/client/blob/3ef9835f8bed0ca36e67dd79abed10acba63f77d/src/gui/sharee.cpp#L146

**Comment by michaelstingl** [comment]
@pmaier1 I checked in detail with @TheOneRing , desktop app just renders the API response and isn't affected by the delay-problem.

**Comment by pmaier1** [comment]
Yeah, thanks. But it still shows the invalid federated share suggestion. If you read the solution approach closely, it says that the autocomplete should only show the federated share suggestion if the internal lookup **did not find results for the input provided**. That's what was done for the WebUI. 

The Desktop client even shows that as the first result. Root problem is the API response, I guess. Let me know if you see ways for a "quick fix". 

Apart from that we're investigating how to improve the whole share creation flow for the future. FYI @tbsbdr
