### ISSUE TITLE
[Mac OS] Unable to type password

### ISSUE THREAD

**Issue by ThomasCh666** [owncloud/client#8457]
### Expected behaviour
After starting the desktop client, I want to enter my password to log in into my owncloud account.

### Actual behaviour
I cannot type anything (but ' and `), nor paste in the password box. The issue looks similar to https://github.com/owncloud/client/issues/6811. I tried the fixes described there, and updated qt (5.15.2) using homebrew, but no success so far.    

### Steps to reproduce
1. start owncloud
2. try to type password when dialog box opens up

### Client configuration
Client version: 2.7.6 (also tried 2.7.3 and 2.7.5)
Operating system: mac OS Catalina, 10.15.7
OS language: English

Installation path of client: /Applications/owncloud.app

### Logs

1. Client logfile: 
owncloud --logfile log.txt returns an error: 'File 'log.txt' cannot be opened for writing. The log output cannot be saved.' 
owncloud --logwindow does not work.

Thanks in advance for your help.

**Comment by ThomasCh666** [comment]
Actually deleting config files (following https://github.com/owncloud/client/issues/8421) worked. 
Quite unconvenient though as I have many synced accounts, any possible fix?

**Comment by TheOneRing** [comment]
It appears to be an Qt upstream bug, I reported it the 10th of February https://bugreports.qt.io/browse/QTBUG-91059

**Comment by ThomasCh666** [comment]
Thanks for your reply!

**Comment by TheOneRing** [comment]
Duplicate: #8421
