### ISSUE TITLE
Refine German translation.

### ISSUE THREAD

**Issue by sfadschm** [owncloud/client#8465]
https://github.com/owncloud/client/blob/f6e49785b5a7cd05e714d9293468e34c3d21792c/translations/client_de.ts#L3943-L3945

Should be
`Von %1 getrennt`

**Comment by michaelstingl** [comment]
Thanks. I changed it in Transifex:
https://www.transifex.com/owncloud-org/owncloud/translate/#de_DE/client/55136102

**Comment by sfadschm** [comment]
Thanks! I think I have some more corrections (mostly cosmetic, so far). 
Can we just add the transifex team or is it restricted?

**Comment by michaelstingl** [comment]
> Can we just add the transifex team or is it restricted?

Sure, you can join the Transifex team 😍 (@ChrisEdS will approve)

**Comment by sfadschm** [comment]
So it seems to me that the `German` and `German (Germany)` translations are quite different from each other. So to say most of the things I wanted to change are already changed in `German` but not in de_de.

How does the client decide which one it uses?

**Comment by ChrisEdS** [comment]
@sfadschm We have a language switch in the users settings. `de` is `German` and it is the casual variant (`Du`). 
`de_DE` is more for the professional use-cases where we have to use `Sie` and so on.

**Comment by ChrisEdS** [comment]
Arg, you talking about the client. @michaelstingl Do you know more about that part?

**Comment by sfadschm** [comment]
> 
> 
> Arg, you talking about the client. @michaelstingl Do you know more about that part?

I was just looking to find that switch in my client 😆

**Comment by michaelstingl** [comment]
I think most desktop platforms don't have this selection. In the web UI, or in the iOS settings for example, users can choose.

**Comment by TheOneRing** [comment]
We lack a command line switch, on linux you can set an env var `LC_ALL` and `LANG`.
Such a command line switch is somewhere on my imaginary todo list...

**Comment by sfadschm** [comment]
I see. So with the distinction that @ChrisEdS explained it seems to me that the github client translation is build from the 'formal' german version, which in my opinion lacks far behind the non-formal one.
Can we somehow link translations in transifex between languages? (E.g., no need to translate "Folder removed" twice in both language flavours).
