### ISSUE TITLE
Feature Request: .owncloudignore files

### ISSUE THREAD

**Issue by maxfrei750** [owncloud/client#8474]
I'm not sure, if this is the right place for feature requests, so any guidance is welcome.

# Pitch
Add a feature, which allows the use of `.owncloudignore` files, which work exactly like `.gitignore` files, to precisely control which files and folders should be ignored.

# Motivation
1. Allow a more granular control of what is to be ignored, right alongside the affected files and folders.
2. Sync ignore files from one client to another.

**Comment by TheOneRing** [comment]
Duplicate of #1558
