### ISSUE TITLE
src\common\utility.h:23: error: ocsynclib.h: No such file or directory  I  not  find   ocsynclib.h

### ISSUE THREAD

**Issue by 837856359** [owncloud/client#8476]
### Expected behaviour
i use  ownCloud-2.7.6.3261  , use  qt  creator  ，  not find   ocsynclib.h； and i don`t  find ocsynclib.h  in   source code  help ,tel  me  where  is  it 
sorry , english  is  very pool, haha

### Actual behaviour
Tell us what happens instead

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by 837856359** [comment]
src\csync\std\c_private.h:26: error: owncloudlib.h: No such file or directory   owncloudlib.h i not find   too  why?

**Comment by TheOneRing** [comment]
Owncloudlib.h is autogenerated, can you rerun cmake?

Which version of cmake are you using, which os and compiler?

**Comment by fmoc** [comment]
Closing, as essential information is missing, and the author does not react at all.
