### ISSUE TITLE
Sharing link in windows client do nothing

### ISSUE THREAD

**Issue by lucker999** [owncloud/client#8483]
### Expected behaviour
Get a sharing link to a file from Windows Desktop Client 

### Actual behaviour
Nothing. A click in context menu "Nextcloud -> Copy public link"

![screenshot1](https://nc.shershidsky.eu/s/A9wtRtxX473yoqM/preview)

opens a dialog 

![screenshot2](https://nc.shershidsky.eu/s/i3QZtW9kZMzZcbY/preview)

which is identical to dialog "Share options", but it does nothing in order to provide a public link:
- If no user\group entered the arrow is not active (I want a public link, not for a user)
- the button "share link" is not active

So, I have to open web access, log in to installation, find the file, click menu, open sidebar, click to create a link, then do not forget to open context menu to uncheck password protection, and only then use the link. This is ridiculous. I do not mention that the help pages do not reflect actual behaviour of windows client.

### Steps to reproduce
1. Right click on a file in Windows Explored
2. Chose Nextcloud -> Copy bublic link 
3. Stumble upon "Nothing happens"

### Server configuration
Operating system: FreeBSD 12.2
NC Installation in a jail

Web server: 
Nginx reverse proxy and local nginx in the jail

Database: MariaDB 10.4.18

PHP version: 7.3.27

ownCloud version: 21.0

Storage backend (external storage): none

### Client configuration
Client version: 3.1.3

Operating system: Win 8.1

OS language: En

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
default

**Comment by michaelstingl** [comment]
This is the ownCloud repository. For issues with other software, you need to open ticket somewhere else.
