### ISSUE TITLE
Owncloud file delete problem since v. 2.7.x

### ISSUE THREAD

**Issue by ceaseDD** [owncloud/client#8484]
**Steps to reproduce**
open the owncloud.cfg file
insert Flag promptDeleteAllFiles=false
when trying to delete all files in ownCloud and then clicking merge changes it crashes.
**Expected behaviour**
Tell us what should happen

ownCloud should delete all files without the warning message of “Remove All Files”? with the choices of Remove all files or to keep files when the files are deleted from the server, it used to work on v 2.6.x
but now it doesnt

**Actual behaviour**
Tell us what happens instead

now it just crashes with promptDeleteAllFiles=false

**Server configuration**
**Operating system:**
Ubuntu 16.04.7

**Web server:**
Apache2

**Database:**
mysql
**PHP version:**
7.2
**ownCloud version: (see ownCloud admin page)**
10.5
**Updated from an older ownCloud or fresh install:**
fresh
**Where did you install ownCloud from:**
from the official website
Signing status (ownCloud 9.0 and above):
```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by TheOneRing** [comment]
Thx for reporting will be fixed in 2.7.8 or 2.8
