### ISSUE TITLE
[QA] linux sharing dialog (nemo) uses a strange trashcan icon

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8491]
Seen with client 2.7.0 RC2 (3509)
![Screenshot from 2021-03-16 04-25-24](https://user-images.githubusercontent.com/1108546/111251636-ea643800-860f-11eb-801b-3ed72b2adb83.png)

The green thingy at the right hand side acts as a trashcan.

Do we have control over this icon?

**Comment by TheOneRing** [comment]
We use the system default icon for folders and trash can.
If that's the default icon for trash, its not a bug on our side.
