### ISSUE TITLE
[QA] Implement "expected-to-fail" system for client as well

### ISSUE THREAD

**Issue by SwikritiT** [owncloud/client#8494]
We have `expected-to-fail` system for `web` and `ocis` like 

https://github.com/owncloud/ocis/blob/master/tests/acceptance/expected-failures-API-on-OWNCLOUD-storage.md

https://github.com/owncloud/web/blob/master/tests/acceptance/expected-failures-with-ocis-server-owncloud-storage.md

But this type of system is not implemented in  `client` yet . 

TODO

- [ ] implement  expected-to-fail system for client

**Comment by individual-it** [comment]
I don't think we need this right now, or maybe not at all. In Squish we have already a build-in expected to fail system, see https://github.com/owncloud/client/pull/8621
If the build-in system works for us, we don't need to implement something new
So leaving this closed for now

CC @swoichha  @Talank
