### ISSUE TITLE
What is the difference between the GPO client and non-GPO client?

### ISSUE THREAD

**Issue by codaamok** [owncloud/client#8495]
Customers have requested the ownCloud client be added to Patch My PC's catalogue. When going to download the client, I see there are two options for both architecture types. One with "GPO" in the name, the other without. They're different in size, in fact the GPO client is smaller.

What is the difference between the GPO client and non-GPO client? If I install the GPO client, and then try to install the non-GPO client, the installer tells me the product is already installed so this tells me that they're not completely different products at least.

I'm just trying to consider which installer to suggest for Patch My PC.

**Comment by michaelstingl** [comment]
GPO client has only EN-language included. Single-language is a requirement for large-scale automated software deployments in the Windows world. Users on managed Windows devices will never see the Windows Installer GUI. For regular users that perform the installation themselves, the regular MSI is recommended.

**Comment by codaamok** [comment]
Perfect, thank you very much for prompt reply. 

If anyone else comes across this: only the installer is localised to English (forced) for the GPO installer, however the ownClient client UI is still localised to the system's locale when it installs. The UI of the app itself is not forced to English, again, only the installer is.
