### ISSUE TITLE
Add tests to cover public link functionality

### ISSUE THREAD

**Issue by HariBhandari07** [owncloud/client#8501]
### Description
Add tests to cover all the public link functionality

#### Files
- [x] permissions #8519 
- [x] expiration date  #8527
- [x] password protection #8519 

#### Folders
- [x] permissions (https://github.com/owncloud/client/pull/8561 )
- [x] expiration date https://github.com/owncloud/client/pull/8560 
- [x] password protection https://github.com/owncloud/client/pull/8545 
For reference check the public link tests of web

**Comment by swoichha** [comment]
For now tests has been added for public link functionality. So, closing this issue for now.
