### ISSUE TITLE
[QA] active sync folder can be re-used with a different sync connection

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8512]
Seen with client 2.7.7-rc2 on Linux Mint

* connect ownCloud client to demo.owncloud.com 
* note the sync folder
* connect testpilotcloud client to demo.owncloud.org, but specfy the sync folder of the other client.

![image](https://user-images.githubusercontent.com/1108546/112162306-399c0100-8bec-11eb-8447-0936d0d24bc5.png)

* Click "Connect". Two servers are now connected to the same folder. 

Expected behaviour: The folder should be exclusive to the first client that connects. The connecting a second client should fail.

Multiple connections to the same folder is untested. Especially scary with VFS options.

**Comment by jnweiger** [comment]
Same client can also connect the same user on the same server to the same folder a second time :see_no_evil:

**Comment by TheOneRing** [comment]
We don't handle branding names in the current code https://github.com/owncloud/client/blob/c0a3ef9d590ccb6dc4c6f1851f20ffeb9a5146d7/src/gui/folderman.cpp#L1431
I guess we need to come up with a different detection mechanism.
