### ISSUE TITLE
Could NOT find ECM (missing: ECM_DIR)

### ISSUE THREAD

**Issue by saiful7** [owncloud/client#8515]
An issue on Build with Windows 10.

OS Version: Microsoft Windows [Version 10.0.19042.870]

Source Code Version/Commit ID: commit 8f6e8c5358be3ceaed405cc4e10d0ae3f7bddc2f
Source Code Branch: master
cmake version 3.20.0

I am trying to build owncloud desktop client on a Windows environment using flowing instruction. https://doc.owncloud.org/desktop/building.html#windows-development-build-mingw [Windows Development Build MinGW without KDE Craft].

When I run ` cmake -G "MinGW Makefiles" ../client ` it's showing a flowing error. I flow the doc every step as they said. 

```cmd

C:\Users\saifu\client-build>cmake -G "MinGW Makefiles" ../client
-- Could NOT find ECM (missing: ECM_DIR)
--
 * ECM (required version >= 5.50.0), Extra CMake Modules., <https://projects.kde.org/projects/kdesupport/extra-cmake-modules>

CMake Error at C:/Program Files/CMake/share/cmake-3.20/Modules/FeatureSummary.cmake:464 (message):
  feature_summary() Error: REQUIRED package(s) are missing, aborting CMake
  run.
Call Stack (most recent call first):
  CMakeLists.txt:9 (feature_summary)


-- Configuring incomplete, errors occurred!
See also "C:/Users/saifu/client-build/CMakeFiles/CMakeOutput.log".

```

**I am not understanding what I am missing here! Can anyone please let me know how to fix this error?**

**Comment by TheOneRing** [comment]
Hi I'm sorry but building with mingw is no longer officially supported, it can still be done but we recommend to follow https://doc.owncloud.org/desktop/building.html#windows-development-build-with-kde-craft .

Besides that the error message does point you to the solution.
