### ISSUE TITLE
[Windows Server 20219] no icon in system tray while starting sync client using task scheduler

### ISSUE THREAD

**Issue by IngoBelka** [owncloud/client#8520]
### Expected behaviour
If the sync client was started over the task schedeuler, there should appaer a status icon in the system tray.

### Actual behaviour
Sync client is started with operating system start as a job created in the task scheduler. I found a process in the taskmanager. Sync is running, too. But no status icon is visible in the system tray.

### Steps to reproduce
1. create a job in the task scheduler to start sync client while starting the operating system
2. start the operating system
3. check the system tray, no icon to be find

### Client configuration
Client version: 2.7.6 (build 3261)
Operating system: Windows Server 2019 (1809)
OS language: German
Installation path of client: C:\Program Files (x86)\ownCloud\

Sorry if this problem is solved yet, but din't found a solution.

**Comment by michaelstingl** [comment]
Launching with task scheduler is not a supported use case. Please use the builtin autostart feature.

What is the real world problem you're trying to solve?

**Comment by IngoBelka** [comment]
> Launching with task scheduler is not a supported use case. Please use the builtin autostart feature.

Thank you for pointing me to that, I did overseen this option.
 
> What is the real world problem you're trying to solve?

Nevertheless, there is no icon in the system tray while starting over task scheduler, that's the problem. Maybe it has no great meaning now, if one uses the mentioned option.
