### ISSUE TITLE
ownCloud-2.8.0-daily20210409.3734 crashes on launch on MacOS BigSur

### ISSUE THREAD

**Issue by dirkpape** [owncloud/client#8544]
### Expected behaviour
testing owncloud desktop client version 2.8.0 with latest daily should be possible on MacOS Big Sur

### Actual behaviour
owncloud desktop client
version ownCloud-2.8.0-daily20210409.3734.pkg
crashes immediately when launching on MacOS Big Sur

### Steps to reproduce
1. download and install ownCloud-2.8.0-daily20210409.3734.pkg
2. start owncloud desktop client

### Server configuration
Operating system:
n/a

Web server: 
n/a

Database:
n/a

PHP version:
n/a

ownCloud version:
n/a

Storage backend (external storage):
n/a

### Client configuration
Client version:
2.8.0-daily20210409.3734

Operating system:
MacOS Big Sur 11.2.3 (20D91)

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```
Dyld Error Message:
  dyld: Using shared cache: 52762DF1-0E55-3F8B-9588-8169E6D0EB95
Library not loaded: @executable_path/../Frameworks/libsqlite3.3.dylib
  Referenced from: /Applications/owncloud.app/Contents/MacOS/owncloud
  Reason: no suitable image found.  Did find:
	file system relative paths not allowed in hardened programs
```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by michaelstingl** [comment]
Thanks for your feedback! Please submit the crash report and post the crash ID.

**Comment by dirkpape** [comment]
link to gist: <https://gist.github.com/dirkpape/babd1dfe2047f9808e9963176dfdedaa>

**Comment by michaelstingl** [comment]
Didn't you get the crash reporter window afterwards?

(see screenshot in https://github.com/owncloud/client/issues/8130 for example)

**Comment by TheOneRing** [comment]
I broke it fixing 😅

**Comment by dirkpape** [comment]
> Didn't you get the crash reporter window afterwards?
> 
> (see screenshot in #8130 for example)

no definetely not. I think the crash occurs much to early, earlier than any feature of the owncloud client has been loaded, even crash reporter

**Comment by TheOneRing** [comment]
Yes I tweaked the deployment and the build is lacking some symlinks, weird thing my test deployments contain them...

**Comment by TheOneRing** [comment]
Fixed in https://invent.kde.org/packaging/craft/commit/584239b579e56b78c4a78c0411262bb2f2895960 the issue existed for a long time but just now surfaced.

I just trigger some new nightlies, should be ready to test in about 1h

**Comment by michaelstingl** [comment]
[`ownCloud-2.8.0-daily20210410.3751.pkg`](https://download.owncloud.com/desktop/ownCloud/daily/2.8/mac/ownCloud-2.8.0-daily20210410.3751.pkg
) runs fine again… 👍 

<img width="555" alt="CleanShot 2021-04-11 at 13 11 18@2x" src="https://user-images.githubusercontent.com/214010/114302005-6ba3d300-9ac7-11eb-8611-91a30ce0448d.png">

**Comment by dirkpape** [comment]
thanks for quick reaction
