### ISSUE TITLE
OpenID Connect fails with Azure AD

### ISSUE THREAD

**Issue by ib-mlatin** [owncloud/client#8562]
### Expected behaviour
Authentication passes through to Azure AD, which authenticates the client.

### Actual behaviour
Azure throws an error code:
```
AADSTS90023: Unsupported 'prompt' value.
```
This could be related to the fact that you cannot statically define an application with the same client ID. You also cannot set it up as an authorized client application as it needs to be a GUID.

### Steps to reproduce
1. Follow the OpenID Connect guide to configure OwnCloud server for OpenID on Azure ( https://doc.owncloud.com/server/admin_manual/configuration/user/oidc/ms-azure-setup.html )
2. Once web login is working on OwnCloud, try to connect the desktop client.
3. Enter the URL to your owncloud server in the add account wizard
4. Web browser opens and Azure throws the above error code.

### Server configuration
Operating system: Ubuntu 20.04.2

Web server: Apache/2.4.46

Database: MySQL Community 5.7.33-log

PHP version: PHP 8.0.3

ownCloud version: 10.7.0.4

Storage backend (external storage): SMB

### Client configuration
Client version: 2.7.6

Operating system: Windows 10 20H2

OS language: English

Installation path of client: C:\Program Files\ownCloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

https://gist.github.com/ib-mlatin/3d5fac88d202c5485dc59dd7e980763a

**Comment by michaelstingl** [comment]
> Azure throws an error code:

There’s a branding parameter to send the correct parameter. You’d need to build your own clients for every platform, or get in touch with ownCloud Team to get a branding subscription for such customization. (https://owncloud.com/contact-us/)

**Comment by ib-mlatin** [comment]
> > Azure throws an error code:
> 
> There’s a branding parameter to send the correct parameter. You’d need to build your own clients for every platform, or get in touch with ownCloud Team to get a branding subscription for such customization. (https://owncloud.com/contact-us/)

If this is the case, I have created a pull request to add a note to the integration documents: https://github.com/owncloud/docs/pull/3492 
This would make it significantly easier for people to figure out why Azure AD isn't working at all.

And it seems like all of the necessary client parameters are hard coded in themes.cpp unless themes are loaded from a file somewhere that overrides these string constants. There is no documentation on desktop themes at this time. https://github.com/owncloud/client/blob/8013ce2872ab8c771c45b5f48d7c53e822099a36/src/libsync/theme.cpp#L638-L661

**Comment by mmattel** [comment]
@fschade @DeepDiver1975 @pmaier1 fyi
