### ISSUE TITLE
[QA] add option to log socket api traffic

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8563]
Seen in build 3677 on win10

The "log settings" window allows to e.g. log all HTTP traffic:
![image](https://user-images.githubusercontent.com/1108546/115392365-c5e81680-a1e0-11eb-98e3-de55a8bc621b.png)

Enhancement suggestion: Also allow logging all socket API traffic.

Use case: debugging complex api client issues, when long running socket connections get in an inconsistent state.

**Comment by TheOneRing** [comment]
Covered by enable logging to temporary folder.
