### ISSUE TITLE
[QA] harfbuzz dll error while upgrading

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8564]
Seen on windows 10 20H2_v2 connected to local docker server 10.7
while upgrading from (running) ownCloud-2.8.0-daily20210413.3766.x64.msi to
*  https://download.owncloud.com/desktop/ownCloud/daily/2.8/win/ownCloud-2.8.0-daily20210420.3827.x64.GPO.msi

![image](https://user-images.githubusercontent.com/1108546/115431173-4caeea80-a205-11eb-8af8-4597bbee16c6.png)

Clicking 'OK', then 'Yes' a second time makes the reboot succeeds, But then the client still won't start.

![image](https://user-images.githubusercontent.com/1108546/115431947-289fd900-a206-11eb-9f73-1bb1d303cb9e.png)

Same with https://download.owncloud.com/desktop/ownCloud/daily/2.8/win/ownCloud-2.8.0-daily20210419.3816.x64.msi

Wokaround: reinstall ownCloud-2.8.0-daily20210413.3766.x64.msi

**Comment by TheOneRing** [comment]
Should be fixed tomorrow

**Comment by gabi18** [comment]
Error ...harfbuzz.dll was not found persists with
 
https://download.owncloud.com/desktop/ownCloud/daily/2.8/win/ownCloud-2.8.0-daily20210421.3839.x64.msi 

on Windows 10 20H2_v2

**Comment by TheOneRing** [comment]
Yes your right forgot one step..

**Comment by jnweiger** [comment]
Thanks! Build 3845 works again!
