### ISSUE TITLE
[QA] [Mac] Cannot install ownCloud-2.8.0-daily20210422.3859.pkg

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#8570]
Seen on macOS Big Sur Version 11.2.3

Installation of latest daily build https://download.owncloud.com/desktop/ownCloud/daily/2.8/mac/ownCloud-2.8.0-daily20210422.3859.pkg isn't possible because of:

![Bildschirmfoto 2021-04-22 um 14 48 38](https://user-images.githubusercontent.com/75983861/115717600-9e2cb600-a37a-11eb-91d9-cd7482363d50.png)

Last working build is ownCloud-2.8.0-daily20210410.3751.pkg

**Comment by michaelstingl** [comment]
I also received notification from Apple about failing notarizations.

**Comment by TheOneRing** [comment]
yes I broke notarisation.... of 2.8 and 2.9..

**Comment by TheOneRing** [comment]
Fixed

**Comment by gabi18** [comment]
Thank you! Confirmed is installable again 👍
