### ISSUE TITLE
Add `--list--languages`, print available languages also in the hint of `--language`

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#8574]
Also document the format of the language argument.

**Comment by fmoc** [comment]
I'd like to get rid of `_helpOnly`/`_versionOnly` in `Application`, as they are not only redundant, but I would have to add a third of them. We could either exit in `parseOptions` directly or change it into a `boolean` that determines whether to exit early. That also removes some state from `Application` that is not needed later on anyway.

**Comment by fmoc** [comment]
Decided to implement this feature following the already-existing infrastructure. The (overdue) big refactoring will be tracked in #8603, and will be done in a future PR.

**Comment by fmoc** [comment]
Can you please give an example how you want the format to be documented? I think it's relatively easy to just call `--list-languages`.
