### ISSUE TITLE
[QA] file browser integration: 'open in Browser' is grayed out on the syc root folder

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8595]
Seen in 2.8.0RC1 on Ubuntu 2.04 with Nemo file browser.

* connect to cloud.damken.com with sync root folder ~/damkenCloud
* open Nemo, right click on the folder ~/damkenCloud, enter the 'ownCloud' sub-menu

![image](https://user-images.githubusercontent.com/1108546/117076866-6e48bf80-ad37-11eb-9553-2513b289e00f.png)

Expected behaviour: only gray out, what is technically impossible. At lease 'Im Broser öffnen' should also be possible on the sync root folder.

(On a sub-folder all four entries are available)

---
TODO: Don't send https://github.com/owncloud/client/blob/master/src/gui/socketapi/socketapi.cpp#L1051for the root folder.

**Comment by TheOneRing** [comment]
Same on windows, we either should not add a context menu to the root item or at least enable the open in browser action.
The other actions don't make much sense and are probably also technically impossible.

**Comment by HanaGemela** [comment]
How was this solved?
Currently on Windows with 3.0.0 alpha 9 client the ownCloud menu is not available at the root folder

**Comment by TheOneRing** [comment]
Share and link options where removed as they are not available on the sync root.

**Comment by individual-it** [comment]
tested on nautilus with oc10 server => no owncloud menu is shown on sync root folder
