### ISSUE TITLE
[UI] Scribble Spaces MVP

### ISSUE THREAD

**Issue by tbsbdr** [owncloud/client#8605]
### userstory
> As a user who is already using the Desktop Client, I want to explore the Spaces that I could sync with my local PC, so that i can access them quickly in my Windows File Explorer.

- **figma clickdummy** (same as gif below): https://www.figma.com/file/4DF8SMW9geE6KRZqQvYzvg/Desktop-Spaces-MVP?node-id=0%3A1
- **Whimsical scribbles**: https://whimsical.com/v1-spaces-desktop-mvp-HVBWwywQXabcRETr1ZJoEo@2Ux7TurymNNrD3axCz2E
- **Photos Whiteboard** (hi-res) https://cloud.owncloud.com/index.php/s/L31UkPQByKdBYWi
### first ideas
(evolved from the clickdummy above)

- [general] get rid of dialogues, that lay upon the main window. no "stacked dialogues" in the future
- [general] visualize profiles very minimalistic, so that there is more space for the main sections
- [general] 3 Tabs in the main section: "General", "Spaces", "Advanced"
- for the MVP the primary way to manage spaces is via rightclick on the syncfolder
- cool cornercases like "mout a space via foldersync" can be configured in the advanced mode in the context of other foldersync connections (there will be no special section to add foldersync for Spaces) 

 
![2021-05-06_11-31-35 (1)](https://user-images.githubusercontent.com/26610733/117275901-cf1ee780-ae5e-11eb-95b3-999e507441ed.gif)

![PXL_20210504_114045652](https://user-images.githubusercontent.com/26610733/117273681-a564c100-ae5c-11eb-931d-22d3938d4cfb.jpg)
![PXL_20210504_114041951](https://user-images.githubusercontent.com/26610733/117273669-a39afd80-ae5c-11eb-9a8a-f3851d4df9d6.jpg)
![PXL_20210421_145910874](https://user-images.githubusercontent.com/26610733/117273608-95e57800-ae5c-11eb-9924-a3b28095c3cf.jpg)
![PXL_20210421_145917637](https://user-images.githubusercontent.com/26610733/117273621-9a119580-ae5c-11eb-8dbc-115f5105b255.jpg)
![PXL_20210421_145922323](https://user-images.githubusercontent.com/26610733/117273630-9bdb5900-ae5c-11eb-963d-5b8a60f9d5a2.jpg)
![PXL_20210504_111237976](https://user-images.githubusercontent.com/26610733/117273642-9d0c8600-ae5c-11eb-9c0c-b51c0bf75c6a.jpg)
![PXL_20210504_111243652](https://user-images.githubusercontent.com/26610733/117273652-9f6ee000-ae5c-11eb-9efe-fd5b46f647cd.jpg)
![PXL_20210504_111247211](https://user-images.githubusercontent.com/26610733/117273661-a138a380-ae5c-11eb-8735-b6dbe38bcb42.jpg)

### integrate "Manage Spaces" into the Desktop Client
basic idea: get rid of stacked dialoges

![image](https://user-images.githubusercontent.com/26610733/122935145-63da9780-d370-11eb-87a7-f1d76ff15812.png)

**Comment by tbsbdr** [comment]
updated initial issue:
- links: figma, whimsical, hi res-photos whiteboard
- scribble: "integrate "Manage Spaces" into the Desktop Client"

**Comment by TheOneRing** [comment]
Pragmatic approach for now:
![image](https://user-images.githubusercontent.com/200626/138259252-0ce8a8ea-3514-486a-9e5d-0a64af9a58b7.png)
