### ISSUE TITLE
sync client has lost its connection (gray icon with three white dots)

### ISSUE THREAD

**Issue by IngoBelka** [owncloud/client#8626]
### Expected behaviour
When sync client loses the connection to the server it should start syncing if the connection is available again.

### Actual behaviour
When sync client loses the connection to the server it stucks in that state and doesn't syncing anymore. One has to close the client and restart again. Then syncing is starting immediately.

### Steps to reproduce
I don't really have some steps to reproduce:

1. start snyc client
2. let it run 
2. wait for randomly lost connection
3. close and restart sync client

### Server configuration
Operating system: Ubuntu Linux
Web server: Apache 2.4 shared host

Database: MySQL 5

PHP version: 7.3

ownCloud version: 10.4.1.3

Storage backend (external storage):

### Client configuration
Client version: 2.7.6

Operating system: Windows Server 2019

OS language: German

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

Please, tell me what log files or parts of the log files you need. Which keywords I should looking for?.

**Comment by gabi18** [comment]
Thank  you very much for reporting the issue.

The client should (and usually does) reconnect automatically when the connection which was lost before is available again. I have retested with client version 2.7.6 on Windows 10 20H2 and the reconnect worked like expected.

I can confirm that under certain circumstances (which we don't know so far) the client remains in unconnected state. It should be possible then to 'Logout' and 'Login' again using the 'Account' button.

**Comment by gabi18** [comment]
I see the problem for you to find out when the connection is lost. 

The relevant log messages are:
```
[ info sync.httplogger ]:	"99b12242-fd73-42ad-980e-154924ee6add: Response: PROPFIND 404 https://demo.owncloud.org/remote.php/dav/files/admin/ Header: { Content-Length: 1757,  .... <title>No worries! Setup in progress.</title>\n\ ...    <h1>\n          404\n        </h1>\n\n        <h4>\n          No worries! Setup in progress.\n        </h4>\n\n        <p>\n          A fresh demo server is being prepared and will be available soon.\n        </p>\n      </div>\n    </div>\n  </body>\n</html>\n]"
05-12 09:00:49:224 [ info sync.networkjob.propfind ]:	PROPFIND of QUrl("https://demo.owncloud.org/remote.php/dav/files/admin/") FINISHED WITH STATUS "ContentNotFoundError Server replied \"404 Not Found\" to \"PROPFIND https://demo.owncloud.org/remote.php/dav/files/admin/\""
[ warning sync.networkjob.propfind ]:	*not* successful, http result code is 404 ""
[ info gui.account.state ]:	AccountState connection status change:  OCC::ConnectionValidator::Connected -> OCC::ConnectionValidator::Timeout
[ info gui.account.state ]:	AccountState state change:  "Connected" -> "Network error"
[ debug gui.account.settings ]	[ OCC::AccountSettings::showConnectionLabel ]:	"No connection to ownCloud at <a href=\"https://demo.owncloud.org\">https://demo.owncloud.org</a>.\nServer replied \"404 Not Found\" to \"PROPFIND https://demo.owncloud.org/remote.php/dav/files/admin/\""
[ warning sync.networkjob ]: QNetworkReply::ContentNotFoundError "Server replied \"404 Not Found\" to \"PROPFIND https://demo.owncloud.com/remote.php/dav/files/demo/\"" QVariant(in     t, 404)
```

In case of above logging the client automatically reconnects and there isn't any error logging. 
If you search for 'error' in your log files you might find useful information why the client couldn't reconnect.

Thank you for the feedback.

**Comment by IngoBelka** [comment]
Sorry for the long time of not reporting something. We still have randomly connection losts. But in the log files there is nothing to find, what could point me to the reason, why it happens. It's easier to me to close and restart the owncloud client from time to time, than to spend a lot of time to find the problem. So I close this issue. I'll get back, if I find anything on this.
