### ISSUE TITLE
[QA] client 2.9.0 always prints useless url change warnings

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8645]
Seen with ownCloud-2.9.0-daily20210520.4179.AppImage on Ubuntu 20.04

![image](https://user-images.githubusercontent.com/1108546/118963859-32347200-b967-11eb-9098-a77711340671.png)

the URLs are identical except for a trialing /

Expected behavior: trailing slashes do not cause such pop-ups.

**Comment by jnweiger** [comment]
When the user does not immediately act, the requestors multiply... :-(

**Comment by TheOneRing** [comment]
The joy of non blocking popups
