### ISSUE TITLE
[QA] deselecting one folder via selective sync causes full re-download

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8647]
Seen with ownCloud-2.9.0-daily20210520.4179.AppImage on Ubuntu 20.04

* connect client to a server with a large tree (e.g. damken cloud)
* wait for the sync to complete.
* create a new sync folder connection for one subfolder (in my case `gallifreyan`)
* wait for the new sync folder connection completes its sync
* deselect that folder (gallifreyan) in the selective sync list of the original sync.

The client starts a full re-download.

![image](https://user-images.githubusercontent.com/1108546/118966417-023a9e00-b96a-11eb-9fdd-6b4f8d8b8e43.png)

Expected behaviour: Only the deselected folder gets removed locally without any other re-downloads.

The client log contains `05-20 12:42:55:456 [ info gui.folder ]: Forbidding local discovery to read from the database`

[20210520_1242_owncloud.log.0.zip](https://github.com/owncloud/client/files/6515342/20210520_1242_owncloud.log.0.zip)

**Comment by TheOneRing** [comment]
Not a bug, thats how sync folder pairs work
