### ISSUE TITLE
[QA] "Manually create sync folder connection" and "use VFS..." are mutually exclusive in the connection wizard

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8658]
Seen in 2.8.1.4457 on Linux Mint

When connecting to a server, the user has three choices. The preselected standard is "Sync everything ..." the two others are "Manually create sync folder connection" and "use VFS..."
This is confusing to the user, as it is not obvious, why choice "physical" vs "virtual" should have an impact on the sync connection folder (user's home at the server, or a subfolder).
In fact, VFS and choice of subfolder ist never an exclusive choice. Whichever route the user takes both can be combined in the end (but through a very different UI).

When you choose VFS in the wizard, you can later also choose to "Add Folder Sync Connection"
![image](https://user-images.githubusercontent.com/1108546/119519519-c9d7fd00-bd79-11eb-9e36-2407d83131cb.png)

----

When you choose to Manually Create Sync folder connection in the wizard, 
![image](https://user-images.githubusercontent.com/1108546/119519733-f724ab00-bd79-11eb-8458-89429f8ff029.png)
you also get a checkbox for enabling VFS
![image](https://user-images.githubusercontent.com/1108546/119519808-086db780-bd7a-11eb-9acf-9756f4347463.png)

Expected behaviour:
a) the choice VFS or physical should be disentangled from all other choices. It is orthogonal to everything else.
b) the UI should present the base folder choice (on the server) and the local folder choice (reuse an existing folder...) etc. in one consistend dialog.

**Comment by TheOneRing** [comment]
Not a bug
