### ISSUE TITLE
Branding options to skip 2nd wizard step

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#8665]
2nd wizard step looks like this:

![image](https://user-images.githubusercontent.com/200626/96601759-a2581800-12f2-11eb-8373-09c0b929944a.png)

(`forceVirtualFilesOption`)

We’d need another option to prevent users choosing their local sync folder.

In case both parameters are set, 2nd wizard step should be skipped, similar as 1st wizard step is skipped with fixed URL. (Only in case of errors, this screen is shown)

**Comment by jnweiger** [comment]
Confirmed fixed in 2.9.0-rc1

When ...-theme.h contains

```
    bool wizardSkipAdvancedPage() const { return true; }

```
then the client automatically chooses a sync folder name all by itself and starts syncing immediately after the user authenticated with a server.
