### ISSUE TITLE
Repeatly/Always crash in a minute after start while checking for remote changes

### ISSUE THREAD

**Issue by alessandromannini** [owncloud/client#8668]
After installing v. 2.8.1 the client (on Windows 10) crash in a minute from the start while it is connect to the server and is checking for remote changes. The problem persists with version 2.8.2.

### Expected behaviour
The client worked without problem for months before installing version 2.8.1 (and 2.8.2)

### Actual behaviour
In a minute from the start the client crash with code 21fc225c-9900-4121-b038-72db4701b043 .
If a restart the client or the PC the client always crash in a minute.
Tried to update the server too, without resolving.

### Steps to reproduce
Start or restart the ownclient Windows client and wait a minute.

### Server configuration
Operating system: debian 9

Web server: 
apache2

Database:
mysql

PHP version:
7.3
ownCloud version:
10.7.0.4

Storage backend (external storage):

### Client configuration
Client version:
2.8.2
Operating system:
Windows 10 Pro
OS language:
Italian
Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

**Comment by TheOneRing** [comment]
Thx for reporting the issue.
The client crashes during the initialisation of the virtual file plugin.
Does the local folder you sync to still exists?
Is the folder on a ntfs drive?
Is the folder on a network share?

If you start the client in a powershell window `& 'C:\Program Files\ownCloud\owncloud.exe' --logfile - ` (ensure the path is correct and you copied the `&`) you should see an error before the client dies.

**Comment by alessandromannini** [comment]
Hi,
      
      the folder is on a LOCAL SSD disk in a NTFS partition (nothing has
      been changed). It exists (it's my main document folder :)).
      
      Below the final part of the log. It reports a "Access denied" on a
      jpg image. I tried to access the email form Explorer and I can
      read it without problems.
      
      Thx
      Alessandro
      
    05-31
      10:39:23:180 [ info sync.discovery ]:     Processing
      "C3/Ricette/doc/benchmark/all/10281.jpg" | valid: true/true/db |
      mtime: 1232013578/1232013578/0 | size: 94944/94944/0 | etag:
      "27742ceab6336180c51ab8a9009fc955"//"" | checksum:
      "SHA1:5c1237ad9cc05f8ba2df52cb0a4cefbde00a2da2"//"" | perm:
      0x234a72e3db8//0x7ffbcb3d8340 | fileid: "00006047ocxlih0wvqr9"//""
      | inode: 21778/21778/ | type:
CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile
      05-31 10:39:23:180 [ info sync.discovery ]:     Discovered
      "C3/Ricette/doc/benchmark/all/10281.jpg"
      CSyncEnums::CSYNC_INSTRUCTION_UPDATE_METADATA
      OCC::SyncFileItem::Down CSyncEnums::ItemTypeFile
      05-31 10:39:23:193 [ info sync.database ]:      Updating file
      record for path: "C3/Ricette/doc/benchmark/all/10281.jpg" inode:
      21778 modtime: 1232013578 type: CSyncEnums::ItemTypeFile etag:
      "27742ceab6336180c51ab8a9009fc955" fileId: "00006047ocxlih0wvqr9"
      remotePerm: "WDNVR" fileSize: 94944 checksum:
      "SHA1:5c1237ad9cc05f8ba2df52cb0a4cefbde00a2da2"
      05-31 10:39:23:193 [ fatal default ]:   Error registering
      StorageProvider for D:\lale\documents Accesso negato.
      05-31 10:39:23:193 [ fatal default ]:   Error registering
      StorageProvider for D:\lale\documents Accesso negato.05-31
      10:39:23:193 [ warning sync.vfs.win ]:     void __cdecl
      OCC::VfsWin::fileStatusChanged(const class QString &,class
      OCC::SyncFileStatus) : could not make handle for
      "D:/lale/documents/C3/Ricette/doc/benchmark/all/10281.jpg"
      "WindowsError: 5: Accesso negato."
      
      05-31 10:39:23:194 [ info sync.discovery ]:     Processing
      "C3/Ricette/doc/benchmark/all/10282.jpg" | valid: true/true/db |
      mtime: 1232013580/1232013580/0 | size: 93650/93650/0 | etag:
      "3f4ca26a3aec08c76a8eb1977fb95a03"//"" | checksum:
      "SHA1:f98d51eee496760851f2c9d217e4a1466c64b653"//"" | perm:
      0x234a72e3d88//0x7ffbcb3d8340 | fileid: "00006048ocxlih0wvqr9"//""
      | inode: 21779/21779/ | type:
CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile
    
    
    
    Il 31/05/2021 10:25, Hannah von Reth ha scritto:
    
      
      Thx for reporting the issue.
        The client crashes during the initialisation of the virtual file
        plugin.
        Does the local folder you sync to still exists?
        Is the folder on a ntfs drive?
        Is the folder on a network share?
      If you start the client in a powershell window &
          'C:\Program Files\ownCloud\owncloud.exe' --logfile - 
        (ensure the path is correct and you copied the &)
        you should see an error before the client dies.
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/owncloud/client/issues/8668#issuecomment-851311371",
"url": "https://github.com/owncloud/client/issues/8668#issuecomment-851311371",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by TheOneRing** [comment]
```
   05-31 10:39:23:193 [ fatal default ]:   Error registering StorageProvider for D:\lale\documents Accesso negato.
```
Can you tell me something about `D:\lale\documents`
Does the folder exist?
Did anything related to the folder change?

**Comment by alessandromannini** [comment]
I said (see below). 
      The folder exists and never has changed in the last months.
      
      
      Here a screenshot while accessing it from Explorer:
      
      
    
    
        
        Thx
        A
        
        
      
    Il 31/05/2021 10:46, A. Mannini ha
      scritto:
    
    the folder is on a LOCAL SSD disk in a NTFS partition
        (nothing has been changed). It exists (it's my main document
        folder :)).

**Comment by TheOneRing** [comment]
The screenshot is missing in the web ui.

Can you check the folders permissions?

**Comment by alessandromannini** [comment]
The screenshot was to demostrate that locally, with
      File Explorer I can access the folder. I repeat this is the folder
      were I have all my documents, where every days I read, update,
      delete files... Nothing is changed for months/years... After
      installing ownCloud client v.2.8.1 stopped working.
      Anyway:
      
      
      My account is Admnistrator.
      
      Waht do you mean for Web UI? Is that ok?
      
      
      Thx
      A
      
      
      
    
    Il 01/06/2021 10:24, Hannah von Reth ha
      scritto:
    
    
      
      The screenshot is missing in the web ui.
      Can you check the folders permissions?
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view it on GitHub, or unsubscribe.
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/owncloud/client/issues/8668#issuecomment-851932600",
"url": "https://github.com/owncloud/client/issues/8668#issuecomment-851932600",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by alessandromannini** [comment]
Hi, my client keep not working...
The folder is accessible with full rights form windows...
No changes on it frommonths/years...

Any suggestion?

![fpkjlgmpidhiekal](https://user-images.githubusercontent.com/85100584/122749862-21d92500-d28e-11eb-8b9b-8fe4c060c008.png)

**Comment by michaelstingl** [comment]
@alessandromannini please reproduce with the 2.9 daily build, then post the new crash ID.

**Comment by alessandromannini** [comment]
Hi,

daily installed. Crash ID e4ad53e5-1193-42e8-8edf-0fc68520e6cb

Thx
Alessandro

**Comment by TheOneRing** [comment]
`06-21 13:22:22:477 [ fatal default ]:	Error registering StorageProvider for D:\lale\documents Accesso negato

**Comment by alessandromannini** [comment]
> 
> 
> ```
> 06-21 13:22:22:477 [ fatal default ]:	Error registering StorageProvider for D:\lale\documents Accesso negato
> ```

I know, but why i can access by windows with all applications without problems?
What others checks can i do?

Thx
A

**Comment by alessandromannini** [comment]
HI,

tried to run as admin, re-check folder permissions (never changed) and daily version but nothing...it doesn't work.
What else can I check? How to reproduce the same access technique used by OC client or get more indepth debug details?

Thx
A

**Comment by michaelstingl** [comment]
@alessandromannini you could try this:
https://central.owncloud.org/t/crash-on-startup/31909/6

**Comment by alessandromannini** [comment]
@michaelstingl  thx!
Tried and also tried to uninstall and reinstall the latest build.
Now it crash just after started.

This is the log:
`
>>
>> & 'C:\Program Files\ownCloud\owncloud.exe' --logfile - --logflush | Write-Host
>>
>>
07-27 17:32:19:017 [ debug default ]    [ OCC::Logger::setLogRules ]:   ""
07-27 17:32:19:017 [ info gui.application ]:    ################## "ownCloud" locale: "it_IT" version: "ownCloud 2.9.0daily20210727 (build 4735) d6817e Jul 26 2021 17:11:39 Libraries Qt 5.12.11, OpenSSL 1.1.1k  25 Mar 2021 Using virtual files plugin: wincfapi windows-10.0.19043"
07-27 17:32:19:017 [ info gui.application ]:    Arguments: ("C:\\Program Files\\ownCloud\\owncloud.exe", "--logfile", "-", "--logflush")
07-27 17:32:19:017 [ info gui.application ]:    Using "it_IT" translation
07-27 17:32:19:017 [ info gui.application ]:    VFS windows plugin is available
07-27 17:32:19:017 [ info gui.application ]:    VFS suffix plugin is available
07-27 17:32:19:017 [ info gui.socketapi ]:      server started, listening at  "\\\\.\\pipe\\ownCloud-lale"
07-27 17:32:19:017 [ info gui.folder.manager ]: setting remote poll timer interval to 30000 msec
07-27 17:32:19:049 [ info gui.account.manager ]:        Restored:  2  unknown certs.
07-27 17:32:19:372 [ info gui.application ]:    Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
07-27 17:32:19:379 [ info gui.folder.manager ]: Setup folders from settings file
07-27 17:32:19:380 [ info plugins ]:    Created VFS instance from plugin "owncloudsync_vfs_win"
07-27 17:32:19:380 [ info sync.database ]:      Detected filesystem "NTFS" for "D:/lale/documents/.sync_ded2500a5289.db"
07-27 17:32:19:380 [ info sync.configfile ]:    Adding system ignore list to csync: "C:/Program Files/ownCloud/sync-exclude.lst"
07-27 17:32:19:380 [ info sync.configfile ]:    Adding user defined ignore list to csync: "C:/Users/lale/AppData/Roaming/ownCloud/sync-exclude.lst"
07-27 17:32:19:425 [ warning sync.vfs.win ]:    Could not check for or unregister previous StorageFolder for "D:\\lale\\documents" "Impossibile trovare elemento."
`

**Comment by TheOneRing** [comment]
Did you delete the folder D:\lale\documents ?

**Comment by alessandromannini** [comment]
No! It contains ALL my data. I use it every day with all applications but ownCloud (the new versions) say me "Access denied".
Now it start "as administrato" but it keeps crashing with:
`07-28 09:22:01:500 [ fatal default ]:   Error registering StorageProvider for D:\lale\documents Accesso negato.`

**Comment by TheOneRing** [comment]
Your last message said
```
07-27 17:32:19:425 [ warning sync.vfs.win ]: Could not check for or unregister previous StorageFolder for "D:\lale\documents" "Impossibile trovare elemento."```
Which google translate, translates to something like file not found?

**Comment by alessandromannini** [comment]
@TheOneRing your are right but, as written then, running from PowerShell **"as administrator"** OCC start but keeps crashing with "Access denied". Sorry I repeat....**I can access that folder (and subfolder) with ALL my applications except OCC**.

**Comment by alessandromannini** [comment]
A new try. Owncloud crash with 'access denied' but i can access and write to d:\lale\documents; how is it possible? See below:

`08-04 10:04:19:637 [ fatal default ]:   Error registering StorageProvider for D:\lale\documents Accesso negato.
PS C:\WINDOWS\system32> cd d:\lale\documents
PS D:\lale\documents> New-Item -Name empty-file.txt -ItemType file


    Directory: D:\lale\documents


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        04/08/2021     10:05              0 empty-file.txt


PS D:\lale\documents>`
