### ISSUE TITLE
[QA] Sync protocol sort by time does not sort correctly across month ends

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8674]
Seen with client 2.8.2 (build 4246) running on Win10_20H2_v2

* Sync some files on th elast day of the month.
* Sync some more on the first day of the next month.
* Visit 'Activity'->Sync Protocol, click on sort by Time.

The latest sync activity 5:11:47 AM on June 1st 2021 is neither on top, nor on bottom, it is in the middle. BAD.

![image](https://user-images.githubusercontent.com/1108546/120321570-c4336780-c2e3-11eb-994c-b01766d8e602.png)

Expected behaviour: Timestamps are compared as internal timestamps, not as strings in the users locale.

Workaround: German locale seems to be not affected :scream:

**Comment by gabi18** [comment]
![date_german](https://user-images.githubusercontent.com/75983861/120323299-a6670200-c2e5-11eb-97c3-6712bacbc100.png)

**Comment by TheOneRing** [comment]
Fixed in the rewrite in 2.9
