### ISSUE TITLE
[QA] Local folder delete not synced to server

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#8688]
Seen on openSUSE 15.2 with ownCloud-2.9.0-daily20210607.4309.AppImage
(also seen on MacOS with daily 2.9.0 build)

Server version: 10.7.0

Steps done:
- start client 
- open file browser 
- delete a folder (here 'MyVeryNewFolder')

Result:
The deletion of the folder isn't synced to the server (20210607_0914_owncloud.log.0_no_delete.gz)

Only after 'Force Sync' the folder delete on server is done (20210607_0922_owncloud.log.0.gz)

[20210607_0914_owncloud.log.0_no_delete.gz](https://github.com/owncloud/client/files/6606772/20210607_0914_owncloud.log.0_no_delete.gz)

[20210607_0922_owncloud.log.0.gz](https://github.com/owncloud/client/files/6606774/20210607_0922_owncloud.log.0.gz)

![Screenshot_20210607_093028](https://user-images.githubusercontent.com/75983861/120977319-7dc28a80-c773-11eb-8c76-1b074073e336.png)

**Comment by gabi18** [comment]
[owncloudsync.log.gz](https://github.com/owncloud/client/files/6606908/owncloudsync.log.gz)
![time_differs](https://user-images.githubusercontent.com/75983861/120979783-3984b980-c776-11eb-87e1-ed43a9ec54e1.png)

**Comment by gabi18** [comment]
Also the delete of a file isn't synced to the server
Seen with 2.9.0daily20210616 (build 4404) 
on MacOS BigSur 11.4
Server: 10.7.0

Steps done:
- copy a new file (ownCloud Manual.pdf) to Documents/New folder
- > file is synced to the server

- 'Open folder' and move ownCloud Manual.pdf to trash

Result:
The file is deleted locally but is still available on the server

![Bildschirmfoto 2021-06-17 um 14 04 16](https://user-images.githubusercontent.com/75983861/122395220-0d87e600-cf77-11eb-9c21-de30ace9184a.png)

**Comment by TheOneRing** [comment]
> 
> 
> Also seen: different time stamp for sync in .owncloudsync.log is not corrected in 'Sync Protocol' tab (see screenhot above - time for 'Deleted' should be 9:22)
> 
> ```
> [07:22:27||MyNewFolder/MyVeryNewFolder|2|1|1623050065|60bdc75112fd2|0|00000597oc4pjymlb7e1|4||204|0|1623050065|5633c25b-ed42-48c3-bab1-6792058e0e2b|
> #=#=#=# Syncrun finished 2021-06-07T07:22:27Z (last step: 250 msec, total: 414 msec)
> ```
> 
> [owncloudsync.log.gz](https://github.com/owncloud/client/files/6606962/owncloudsync.log.gz)

The sync log uses utc time

**Comment by michaelstingl** [comment]
@TheOneRing closer look before the 2.9? Set Milestone?

**Comment by gabi18** [comment]
What I found in the logs so far is a line that the file is ignored:
```
06-17 13:50:35:374 [ debug gui.folderwatcher ]  [ OCC::FolderWatcher::pathIsIgnored ]:  * Ignoring file "/Users/gabrielemohr/ownCloud6/Documents/New folder/ownCloud Manual.pdf"
```

When the file was created the log was ignore non-content changes

```
20210617_1338_owncloud.log.0:06-17 13:42:00:995 [ debug gui.folderwatcher ]	[ OCC::callback ]:	Ignoring non-content changes for "/Users/gabrielemohr/ownCloud6/Documents/New folder/ownCloud Manual.pdf"
```

**Comment by TheOneRing** [comment]
We found the reason for the issue fix should be ready soon.
