### ISSUE TITLE
[QA] Client crash after account removal

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#8690]
Seen with ownCloud-2.9.0-daily20210607.4309.AppImage on openSUSE 15.2

Steps done:

- start client
- remove an account 
- switch to 'Activity' view

Result:
Client seg fault

![crash_remove_account](https://user-images.githubusercontent.com/75983861/120982508-127bb700-c779-11eb-907f-b9f9873fa877.png)

**Comment by jnweiger** [comment]
``gdb ./ownCloud-2.9.0-daily20210607.4309.AppImage
(gdb) run
Starting program: /home/testy/Downloads/ownCloud-2.9.0-daily20210607.4309.AppImage 
``` 

```
Thread 1 "AppRun.wrapped" received signal SIGSEGV, Segmentation fault.
0x00005555555abcad in ?? ()
(gdb) where
#0  0x00005555555abcad in ?? ()
#1  0x00005555556a9e00 in ?? ()
#2  0x00007ffff670cdc9 in QSortFilterProxyModel::data(QModelIndex const&, int) const () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Core.so.5
#3  0x00007ffff7d27fd6 in QStyledItemDelegate::initStyleOption(QStyleOptionViewItem*, QModelIndex const&) const ()
   from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#4  0x00007ffff7d37f1c in QStyledItemDelegate::paint(QPainter*, QStyleOptionViewItem const&, QModelIndex const&) const ()
   from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#5  0x00007ffff7d06c78 in QTableViewPrivate::drawCell(QPainter*, QStyleOptionViewItem const&, QModelIndex const&) ()
   from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#6  0x00007ffff7d075cb in QTableView::paintEvent(QPaintEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#7  0x00007ffff7ba8ddf in QWidget::event(QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#8  0x00007ffff7c55a0e in QFrame::event(QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#9  0x00007ffff7dcc34b in QAbstractItemView::viewportEvent(QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#10 0x00007ffff676d1cd in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Core.so.5
#11 0x00007ffff7e1cbb5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#12 0x00007ffff7e20820 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#13 0x00007ffff6771788 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Core.so.5
#14 0x00007ffff7af5f15 in QWidgetPrivate::sendPaintEvent(QRegion const&) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#15 0x00007ffff7b06733 in QWidgetPrivate::drawWidget(QPaintDevice*, QRegion const&, QPoint const&, int, QPainter*, QWidgetBackingStore*) ()
   from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#16 0x00007ffff7e17424 in QWidgetBackingStore::doSync() () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#17 0x00007ffff7e176f5 in QWidgetBackingStore::sync() () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#18 0x00007ffff7af927f in QWidgetPrivate::syncBackingStore() () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#19 0x00007ffff7ba8c48 in QWidget::event(QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#20 0x00007ffff7caeedd in QMainWindow::event(QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#21 0x00007ffff7e1cbdc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#22 0x00007ffff7e20820 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#23 0x00007ffff6771788 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Core.so.5
#24 0x00007ffff7e15bcb in QWidgetBackingStore::sendUpdateRequest(QWidget*, QWidgetBackingStore::UpdateTime) [clone .part.93] ()
   from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#25 0x00007ffff7e1892e in QWidgetBackingStore::markDirty(QRect const&, QWidget*, QWidgetBackingStore::UpdateTime, QWidgetBackingStore::BufferState) ()
   from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#26 0x00007ffff7b95f2b in QWidget::repaint(QRect const&) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#27 0x00007ffff7b9601c in QWidget::repaint() () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#28 0x00007ffff7c54248 in QAbstractButtonPrivate::click() () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#29 0x00007ffff7c54625 in QAbstractButton::mouseReleaseEvent(QMouseEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#30 0x00007ffff7b6d77a in QToolButton::mouseReleaseEvent(QMouseEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#31 0x00007ffff7ba945f in QWidget::event(QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#32 0x00007ffff7b849e2 in QToolButton::event(QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#33 0x00007ffff7e1cbdc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#34 0x00007ffff7e20da8 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#35 0x00007ffff6771788 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Core.so.5
#36 0x00007ffff7e2338e in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool, bool) ()
   from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
--Type <RET> for more, q to quit, c to continue without paging--
#37 0x00007ffff7ce61b8 in QWidgetWindow::event(QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#38 0x00007ffff7e1cbdc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#39 0x00007ffff7e20820 in QApplication::notify(QObject*, QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Widgets.so.5
#40 0x00007ffff6771788 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Core.so.5
#41 0x00007ffff75584ad in QGuiApplicationPrivate::processMouseEvent(QWindowSystemInterfacePrivate::MouseEvent*) ()
   from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Gui.so.5
#42 0x00007ffff755d6c5 in QGuiApplicationPrivate::processWindowSystemEvent(QWindowSystemInterfacePrivate::WindowSystemEvent*) ()
   from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Gui.so.5
#43 0x00007ffff755c96b in QWindowSystemInterface::sendWindowSystemEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Gui.so.5
#44 0x00007ffff3a903ba in xcbSourceDispatch(_GSource*, int (*)(void*), void*) [clone .lto_priv.401] ()
   from /tmp/.mount_ownCloBWYzv4/usr/plugins/platforms/../../lib/libQt5XcbQpa.so.5
#45 0x00007ffff4ad7cca in g_main_context_dispatch () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libglib-2.0.so.0
#46 0x00007ffff4ad7f00 in ?? () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libglib-2.0.so.0
#47 0x00007ffff4ad7f8c in g_main_context_iteration () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libglib-2.0.so.0
#48 0x00007ffff677ea0f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Core.so.5
#49 0x00007ffff6861d5b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Core.so.5
#50 0x00007ffff677d390 in QCoreApplication::exec() () from /tmp/.mount_ownCloBWYzv4/usr/bin/../lib/libQt5Core.so.5
#51 0x000055555559df39 in ?? ()
#52 0x00007ffff60590b3 in __libc_start_main (main=0x55555559dc70, argc=1, argv=0x7fffffffd478, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, 
    stack_end=0x7fffffffd468) at ../csu/libc-start.c:308
#53 0x000055555559e51a in _start ()
(gdb)

**Comment by TheOneRing** [comment]
Not yet. But the bt already tells me something
