### ISSUE TITLE
[QA] Folder size not updated on account view

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#8710]
Seen with owncloud-client 2.8.2, also seen with client version 2.7.6

Steps done:
- in account view open the sync root by clicking > to see the folder listed
- 'Open folder' and add a (big) file to a subfolder

Result:
The used space (size) of the subfolder isn't updated, only update of '... in use' is done

Expected behavior:
Folder size should be updated as well

![no_size_update](https://user-images.githubusercontent.com/75983861/121481087-118e9380-c9cc-11eb-9618-8cb7a1964160.png)

The correct size is shown after restart of the client.

**Comment by gabi18** [comment]
Short time after the sync is finished the client checks for changes but only size in line '... MB in use' is updated.
```
06-10 08:57:47:625 [ info gui.folder.manager ]: <========== Sync finished for folder [ownCloud8] of account [demo@demo.owncloud.org] with remote [https://demo.owncloud.org/remote.php/dav/files/demo/]

06-10 08:58:05:375 [ info gui.folder ]: Trying to check "http://localhost/owncloud/remote.php/dav/files/gabi/" for changes via ETag check. (time since last sync: 56 s)
06-10 08:58:05:376 [ info gui.folder ]: Trying to check "http://localhost/owncloud/remote.php/dav/files/gabriele/" for change
```
[20210610_0857_owncloud.log.0.gz](https://github.com/owncloud/client/files/6629122/20210610_0857_owncloud.log.0.gz)

**Comment by TheOneRing** [comment]
Can you search in the existing issues? I think we already have an issue like that.

**Comment by gabi18** [comment]
I will check...

**Comment by gabi18** [comment]
I have found #5423 - but here is reported that the subfolder shows updated size.

**Comment by gabi18** [comment]
With current version neither the subfolder nor the parent is updated.
![no_size](https://user-images.githubusercontent.com/75983861/121861893-8c241f80-ccfa-11eb-8a38-7ee1c60f0a1e.png)

**Comment by gabi18** [comment]
Further there is #7193 - but this about quota on server.
