### ISSUE TITLE
Creating public link share with expiration date doesn't work

### ISSUE THREAD

**Issue by swoichha** [owncloud/client#8733]
### Steps to reproduce
1. Create a public link for a file with expiration date e.g. 6/25/21
2. Close the sharing dialog
3. Open the public links sharing dialog for that file again
4. Select the recently created public link 

### Expected behavior
In the sharing dialog for public link shared file with expiration date the `Set expiration date` checkbox should be checked and the expiration date field should have the date same as the date set during creation of public link(6/16/21).
![image](https://user-images.githubusercontent.com/17021686/122049333-07bcc400-ce02-11eb-82db-66352d20d333.png)

### Actual behavior
When a user creates a public link with expiration date and opens the sharing dialog in desktop-client for that file then the `Set expiration date` checkbox is unchecked and the expiration date field have public link creation date(6/16/21).
![image](https://user-images.githubusercontent.com/17021686/122049350-0c817800-ce02-11eb-8ef7-d2c9dc79e53d.png)

**Comment by individual-it** [comment]
This seems only to happen with the latest master of core
CC @micbar

**Comment by phil-davis** [comment]
Is this a problem introduced by the expiration time in share responses changing from 00:00:00 to 23:59:59 ?

We really need to know if that is going to break desktop clients that are "in the wild" - before branching core for 10.8 release!

@micbar @TheOneRing

**Comment by individual-it** [comment]
Tomorrow we will check the traffic and see what causes it

**Comment by swoichha** [comment]
## Pre-Condition
- For user admin a folder name `test-user` containing file `login.feature` should exist.

###  Latest master of core  
Creating public link  with expiration date `2021-06-25` and `Download / View` permission using following command:
- `curl -k -X POST -u admin:admin 'http://localhost/core/ocs/v2.php/apps/files_sharing/api/v1/shares' -d 'shareType=3&path=%2Ftest-user%2Flogin.feature&permissions=1&expireDate=18-06-2021'| xmllint --format -`

### Response
We get `<expiration>2021-06-18 23:59:59</expiration>` .

### Tarball 10.7.0

Creating public link  with expiration date `2021-06-25` and `Download / View` permission using following command:
- `curl -k -X POST -u admin:admin 'http://localhost/owncloud-10.7.0/owncloud/ocs/v2.php/apps/files_sharing/api/v1/shares' -d 'shareType=3&path=%2Ftest-user%2Flogin.feature&permissions=1&expireDate=18-06-2021'| xmllint --format -`

### Response
We get `<expiration>2021-06-18 00:00:00</expiration>` in.

**Comment by phil-davis** [comment]
This behavior was changed in core PR  https://github.com/owncloud/core/pull/38813

Now we need to know all the effects for the desktop client. The `expiration` for all types of shares (user,group,federated,public link) was changed so that the time is reported as `23:59:59` (rather than `00:00:00`) because actually all shares work until the end of the expiration day.

But there are clients (like the desktop client) that have "unfortunate" behavior as a result, then we need to find a different solution on the server (and maybe completely revert the change on the server).
