### ISSUE TITLE
Add latest target for bundled dailies

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#8734]
For single binary bundles upload ownCloud-2.11.0-daily-latest-vfs.x64.GPO.msi in addition to ownCloud-2.11.0-daily20220408.7220-vfs.x64.GPO.msi

**Comment by dschmidt** [comment]
What is this about?

**Comment by TheOneRing** [comment]
We talked about providing a dailies/latest url.

**Comment by dschmidt** [comment]
Ah, yes, ok

**Comment by fmoc** [comment]
WIP: https://gitea.owncloud.services/client/build/pulls/39

**Comment by fmoc** [comment]
Done. https://download.owncloud.com/desktop/ownCloud/daily/latest/

**Comment by fmoc** [comment]
Can we move from https://download.owncloud.com/desktop/ownCloud/daily/latest to something like https://download.owncloud.com/desktop/ownCloud/daily/3.2/latest/ (yes, we need a separate directory especially for the Linux repos)? In the current setup, we'd have to decide on which release we consider "latest" and configure (and maintain!) this in the CI scripts. When creating a latest binaries for every minor release, it's up to the user to make that decision.

For automation purposes, to always get the latest release, users can use the updater API which we already update once a stable release is made (also supports A/B testing/thresholds).

**Comment by fmoc** [comment]
Improved version: https://download.owncloud.com/desktop/ownCloud/daily/3.2/latest/ (not entirely happy with this as of yet (maybe we should prepend a `_`, i.e., `_latest`), but it's good enough for now).

**Comment by saw-jan** [comment]
Available: https://download.owncloud.com/desktop/ownCloud/daily/4.0/latest/

![Screenshot from 2023-03-22 14-29-56](https://user-images.githubusercontent.com/52366632/226848191-a3af81bc-4813-42f9-9197-a970fc1bb118.png)
