### ISSUE TITLE
Users find "Synchronizing to local folder" to be confusing

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#8749]
Maybe we can find a better wording.
![image](https://user-images.githubusercontent.com/200626/122367336-a52c0b00-cf5c-11eb-8d74-edfbb7c4efc2.png)

**Comment by dragotin** [comment]
Created PR proposing the following changes for sync with VFS:
![ksnip_20210620-123131](https://user-images.githubusercontent.com/1070214/122670842-49fc5180-d1c4-11eb-95dd-a7d7fbf402dd.png)
and this for full data sync:
![ksnip_20210620-123239](https://user-images.githubusercontent.com/1070214/122670851-508ac900-d1c4-11eb-852a-93cee1cf4209.png)

**Comment by TheOneRing** [comment]
Fixed in 2.9
