### ISSUE TITLE
Add sync folder pair does not use the exclude filter.

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#8756]
![DGMItU](https://user-images.githubusercontent.com/200626/122551069-c9f3b180-d034-11eb-9c83-484181727624.png)

A proper implementation is used in the selectivesyncdilaog.cpp

**Comment by TheOneRing** [comment]
Check whether selective sync is correctly filtered.

**Comment by fmoc** [comment]
Possibly obsolete issue, see https://github.com/owncloud/client/pull/10937.
