### ISSUE TITLE
[QA] Concurrent update and rename duplicates file

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8765]
Seen while testing https://github.com/owncloud/client/pull/8763 with 2.8.3.4442

* Connect a windows machine with client 2.8.3.4442 (without using winVFS) to demo@demo.owncloud.org
* Connect a linux machine with 2.8.2 (also not using VFS) to the same account.
* On the windows machine, open Documents/Example.odt with LibreOffice Writer, change a few lines and hit the save button.
* Very quickly afterwards(!) rename the file Documents/Example.odt on the Linux machine to Documents/Away.odt
* Wait until all syncs complete.
* On the Linux machine, Example.odt gets recreated (with the updated contents from LibreOffice), Away.odt remains there with the previous contents.

Expected behaviour: No duplication. The file with the new name should receive updates on the Linux. The updated file on the windows side should be renamed.

**Comment by TheOneRing** [comment]
@dragotin so rather than retrying to rename I assume I'd need to check where the file is lcoked BEFORE I try...

**Comment by TheOneRing** [comment]
I assume the same would happen with a 2.8.2.
I don't expect vfs to have an influence on this.

**Comment by jnweiger** [comment]
Re-Tested with 2.8.2.4461: Behaviour unchanged.

**Comment by TheOneRing** [comment]
After another debugging session with @jnweiger we can document the following behaviour.
# Scenario A
- A locks
- B moves
  - on B: the file on system B is moved immediately
  - on A: nothing happens, as the file is locked
- A unlocks
  - on B: nothing happens
  - on A: the file is moved  

# Scenario B
- A locks
- B moves
  - on B: the file on system B is moved immediately
  - on A: nothing happens, as the file is locked
- B modifies the moved file
  - on B: the file is updated
  - on A: a file is created in the new location   
- A unlocks
  - on B: nothing happens
  - on A: the unmodified file is deleted

# Scenario C
- A locks
- B moves
  - on B: the file on system B is moved immediately
  - on A: nothing happens, as the file is locked
- B modifies the moved file
  - on B: the file is updated
  - on A: a file is created in the new location
 - A modifies the original file
  - on B: nothing happens
  - on A: no update is populated as the file is locked
- A unlocks
  - on B: downloads the new file in the original location
  - on A: uploads the file

**Comment by michaelstingl** [comment]
> After another debugging session with @jnweiger we can document the following behaviour.

Okay, fine 👍

**Comment by TheOneRing** [comment]
Closing.
Original issue has been fixed.
Scenario C is works as expect.

**Comment by jnweiger** [comment]
* While the libreoffice file Example.odt is still locked on the windows machine, I rename the file through the Linux client to Away.odt
* wait one minute
* the file Away.odt appears on the windows machine, 

![image](https://user-images.githubusercontent.com/1108546/128569998-346500c6-649b-47d0-aeca-055f9b09d873.png)

* Exit LibreOffice to releases the lock on Example.odt
* The updated Example.odt file is synced now to the linux machines. Both clients now have both files.


![image](https://user-images.githubusercontent.com/1108546/128569848-58bd9426-27ff-46e3-8750-562754aaeaa0.png)

**Comment by TheOneRing** [comment]
Please compare to https://github.com/owncloud/client/issues/8765#issuecomment-866773943

**Comment by jnweiger** [comment]
Compared. What I did is different:

## Scenario D

* A locks
* B moves
    * on B: the file on system B is moved immediately
    * on A: nothing happens to the original file, but the move syncs as a copy to A.

**Comment by TheOneRing** [comment]
Your D sounds like my C
Well there is nothing we can do as long as we don't implement client side locking ourself
