### ISSUE TITLE
virtual files are not working when client is compiled using craft

### ISSUE THREAD

**Issue by vagner-dias** [owncloud/client#8775]
### Expected behaviour
The owncloud client is compiled as per the instructions in https://doc.owncloud.com/desktop/building.html and virtual files work as in the official version

### Actual behaviour
Virtual files show up as "experimental" and the virtual files plugin ("about" window) is set to "suffix" whereas the installer version shows virtual files as "wincfapi"

### Steps to reproduce
1. Fresh windows 10 install
2. Intall Visual Studio 2019 community edition + Windows Communication Foundation libraries
3. Install Python 2.7, Python 3.6+, and PowerShell 7.0
4. Set-ExecutionPolicy -Scope CurrentUser RemoteSigned
iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/KDE/craft/master/setup/install_craft.ps1'))
5. run C:\CraftRoot\craft\craftenv.ps1
6. craft --add-blueprint-repository https://github.com/owncloud/craft-blueprints-owncloud.git
7. craft --set version=2.8 owncloud-client
8. craft --install-deps owncloud-client
9. craft --fetch owncloud-client
10. craft --configure --make --install
11. craft owncloud-client
12. craft nsis
13. craft --package owncloud-client

### Client configuration
Client version: 2.8

Operating system: Windows 10 Pro

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.15.2

Installation path of client: C:\Program Files\ownCloud

**Comment by TheOneRing** [comment]
Hi the source code for the vfs is not yet pubically available.
