### ISSUE TITLE
Owncloud client crashes

### ISSUE THREAD

**Issue by perpetuaIwar** [owncloud/client#8776]
### Expected behaviour
I am using virtual files setting on Owncloud client. Client should just sync files fine.

### Actual behaviour
The actual issue is that the Owncloud client continuously crashes. This has been an issue with only one person within our company - no one else has this issue. Her laptop was reimaged at one point - Owncloud client worked but the issue has returned. 

### Steps to reproduce
1. After looking at the logs, I noticed a specific file crashing her client. For testing purposes, I deleted the file.
2. Re-launched the Owncloud client, client crashes again. Logs indicate the next file in line crashes the client. 

### Server configuration
Operating system: Ubuntu Server 18.04 LTS

Web server: 

Database:

PHP version:

ownCloud version: 10.4.1

Storage backend (external storage): N/A

### Client configuration
Client version: 2.8.2

Operating system: Win10 Pro

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile:
06-09 13:21:44:718 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE inode=?1"
06-09 13:21:44:724 [ info sync.discovery ]:	checking checksum of potential rename  "CMT/zzDrake/RCLS Polaris 852 for Suppliers with Processing tabs 052221.xlsx" "SHA1:a3c24d0f69480903425dba419bb1250e827e87ff" "SHA1:a3c24d0f69480903425dba419bb1250e827e87ff"
06-09 13:21:44:724 [ warning sync.discovery ]:	OC_ENFORCE(FAILING) "CMT/RCLS Polaris 852 for Suppliers with Processing tabs 052221.xlsx"
06-09 13:21:44:724 [ warning sync.discovery ]:	instruction == CSYNC_INSTRUCTION_REMOVE false
06-09 13:21:44:724 [ warning sync.discovery ]:	((*it)->_type == ItemTypeVirtualFile && instruction == CSYNC_INSTRUCTION_NEW) false
06-09 13:21:44:724 [ warning sync.discovery ]:	((*it)->_isRestoration && instruction == CSYNC_INSTRUCTION_NEW)) false
06-09 13:21:44:724 [ warning sync.discovery ]:	instruction CSyncEnums::CSYNC_INSTRUCTION_IGNORE
06-09 13:21:44:724 [ warning sync.discovery ]:	(*it)->_type CSyncEnums::ItemTypeFile
06-09 13:21:44:724 [ warning sync.discovery ]:	(*it)->_isRestoration  true
06-09 13:21:44:724 [ fatal default ]:	ENFORCE: "false" in file C:\_\66b504ca\ownCloud-2.8.2.4246-vfs\src\libsync\discoveryphase.cpp, line 185

**Comment by michaelstingl** [comment]
Could you test with the latest 2.9-daily build?
https://download.owncloud.com/desktop/ownCloud/daily/2.9/win/?sort=time&order=desc

In case it still crashes, please submit the crash report, and post the crash ID that is displayed on the 2nd page.

**Comment by perpetuaIwar** [comment]
@michaelstingl Thank you, Michael. I will test this as soon as she's available.

**Comment by TheOneRing** [comment]
I know that crash, all I can say its supposed to be fixed in 2.9

**Comment by TheOneRing** [comment]
Duplicate: #8069

**Comment by perpetuaIwar** [comment]
This issue was not resolved with the client you pointed me to:

06-29 11:12:37:404 [ info sync.discovery ]:	Discovered "CMT/zzzLEA/Profile etc 2019/Library Collection Profile Form 040318 Leander.pdf" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeFile
06-29 11:12:37:523 [ info sync.networkjob.lscol ]:	LSCOL of QUrl("https://cloud.lsslibraries.com/remote.php/dav/files/Diane.Drake/CMT/zzDrake") FINISHED WITH STATUS "OK"
06-29 11:12:37:523 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 -4234079331077405591
06-29 11:12:37:523 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE parent_hash(path) = ?1 ORDER BY path||'/' ASC"
06-29 11:12:37:524 [ info sync.discovery ]:	Processing "CMT/zzDrake/Camarillo 852 spreadsheet for suppliers Rev  040220.xls" | valid: true/true/true | mtime: 1591641324/1591641324/1591641324 | size: 71680/71680/71680 | etag: "ed404c3f11d51b0e702d0d3ca0596406"//"ed404c3f11d51b0e702d0d3ca0596406" | checksum: "SHA1:054e251a4180bce14edd35617b22971807fb3cb2"//"SHA1:054e251a4180bce14edd35617b22971807fb3cb2" | perm: 0x192b300cfa8//0x192b300d098 | fileid: "00053601ocsyyu2afwdz"//"00053601ocsyyu2afwdz" | inode: 329282/329282/ | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile
06-29 11:12:37:524 [ info sync.discovery ]:	Discovered "CMT/zzDrake/Camarillo 852 spreadsheet for suppliers Rev  040220.xls" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeFile
06-29 11:12:37:524 [ info sync.discovery ]:	Processing "CMT/zzDrake/EPL 852 spreadsheet for vendors Rev 031821.xlsx" | valid: true/true/true | mtime: 1616114990/1616114990/1616114990 | size: 23913/23913/23913 | etag: "66b399547f81323aaae4cdff22853be5"//"66b399547f81323aaae4cdff22853be5" | checksum: "SHA1:4c709bd74f68f7e67d3df4bc19e5d5ff5be25f2f"//"SHA1:4c709bd74f68f7e67d3df4bc19e5d5ff5be25f2f" | perm: 0x192b300c6a8//0x192b300cd68 | fileid: "00623621ocsyyu2afwdz"//"00623621ocsyyu2afwdz" | inode: 339064/339064/ | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile
06-29 11:12:37:524 [ info sync.discovery ]:	Discovered "CMT/zzDrake/EPL 852 spreadsheet for vendors Rev 031821.xlsx" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeFile
06-29 11:12:37:524 [ info sync.discovery ]:	Processing "CMT/zzDrake/RCLS Polaris 852 for Suppliers with Processing tabs 052221.xlsx" | valid: false/true/false | mtime: 0/1621696871/0 | size: 0/1664751/0 | etag: ""//"" | checksum: ""//"" | perm: 0x7ffe55869350//0x7ffe55869350 | fileid: ""//"" | inode: 0/13611/ | type: CSyncEnums::ItemTypeSkip/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile
06-29 11:12:37:524 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 13611
06-29 11:12:37:524 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path, inode, modtime, type, md5, fileid, remotePerm, filesize,  ignoredChildrenRemote, contentchecksumtype.name || ':' || contentChecksum FROM metadata  LEFT JOIN checksumtype as contentchecksumtype ON metadata.contentChecksumTypeId == contentchecksumtype.id WHERE inode=?1"
06-29 11:12:37:535 [ info sync.discovery ]:	checking checksum of potential rename  "CMT/zzDrake/RCLS Polaris 852 for Suppliers with Processing tabs 052221.xlsx" "SHA1:a3c24d0f69480903425dba419bb1250e827e87ff" "SHA1:a3c24d0f69480903425dba419bb1250e827e87ff"
06-29 11:12:37:535 [ warning sync.discovery ]:	OC_ENFORCE(FAILING) "CMT/RCLS Polaris 852 for Suppliers with Processing tabs 052221.xlsx"
06-29 11:12:37:535 [ warning sync.discovery ]:	instruction == CSYNC_INSTRUCTION_REMOVE false
06-29 11:12:37:535 [ warning sync.discovery ]:	((*it)->_type == ItemTypeVirtualFile && instruction == CSYNC_INSTRUCTION_NEW) false
06-29 11:12:37:535 [ warning sync.discovery ]:	((*it)->_isRestoration && instruction == CSYNC_INSTRUCTION_NEW)) false
06-29 11:12:37:535 [ warning sync.discovery ]:	instruction CSyncEnums::CSYNC_INSTRUCTION_IGNORE
06-29 11:12:37:535 [ warning sync.discovery ]:	(*it)->_type CSyncEnums::ItemTypeFile
06-29 11:12:37:535 [ warning sync.discovery ]:	(*it)->_isRestoration  true
06-29 11:12:37:535 [ fatal default ]:	ENFORCE: "false" in file C:\_\66b504ca\ownCloud-2.9.0-daily20210616.4404-vfs\src\libsync\discoveryphase.cpp, line 186 struct QPair<bool,class QByteArray> __cdecl OCC::DiscoveryPhase::findAndCancelDeletedJob(const class QString &)

**Comment by TheOneRing** [comment]
@jw I closed it as it is a duplicate.

**Comment by jnweiger** [comment]
This is with a pretty old 10.4.1 server -- we do not test against this server -- not sure, if that is a hint...

**Comment by TheOneRing** [comment]
It happens with moves on read only shares see the original issue
