### ISSUE TITLE
[QA] "Error while loading the list of folders..." 

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#8778]
Seen with 2.9 (compiled from github master on 23.06.2021)

Steps done:
- configured an account on demo.owncloud.com
- 'Choose what to sync' -> only sync 'Documents'
- wait

Result:
After a while the error message is shown:

![Error_while_loading](https://user-images.githubusercontent.com/75983861/123224260-f34b8c00-d4d1-11eb-89d7-dfcad4ad0db0.png)

Logfile shows:
```
06-24 09:33:03:410 [ info sync.httplogger ]:	"7fcff31e-f6f8-4fb6-81e3-8dcee35bf370: Response: PROPFIND 0 https://demo.owncloud.com/remote.php/dav/files/demo/ Header: { } Data: []"
06-24 09:33:03:410 [ warning sync.networkjob ]:	OCC::LsColJob("https://demo.owncloud.com/remote.php/dav/files/demo/", "7fcff31e-f6f8-4fb6-81e3-8dcee35bf370", "7fcff31e-f6f8-4fb6-81e3-8dcee35bf370", "Socket operation timed out") QNetworkReply::TimeoutError "Socket operation timed out" 0
06-24 09:33:03:411 [ info sync.networkjob.lscol ]:	LSCOL of QUrl("https://demo.owncloud.com/remote.php/dav/files/demo/") FINISHED WITH STATUS "TimeoutError Socket operation timed out"
06-24 09:33:03:411 [ debug gui.folder.model ]	[ OCC::FolderStatusModel::slotLscolFinishedWithError ]:	"Socket operation timed out"
06-24 09:33:03:411 [ debug sync.database.sql ]	[ OCC::SqlQuery::bindValue ]:	SQL bind 1 3
06-24 09:33:03:411 [ debug sync.database.sql ]	[ OCC::SqlQuery::exec ]:	SQL exec "SELECT path FROM selectivesync WHERE type=?1"
06-24 09:33:03:411 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job finished OCC::LsColJob("https://demo.owncloud.com/remote.php/dav/files/demo/", "7fcff31e-f6f8-4fb6-81e3-8dcee35bf370", "7fcff31e-f6f8-4fb6-81e3-8dcee35bf370", "Socket operation timed out")
06-24 09:33:05:409 [ warning gui.account.state ]:	checkConnectivity blocking: false
06-24 09:33:05:409 [ debug sync.connectionvalidator ]	[ OCC::ConnectionValidator::checkServerAndUpdate ]:	Checking server and authentication
06-24 09:33:05:409 [ debug sync.connectionvalidator ]	[ OCC::ConnectionValidator::checkServerAndUpdate ]:	Trying to look up system proxy
06-24 09:33:05:409 [ warning gui.account.state ]:	checkConnectivity blocking: false
```
[20210624_0930_owncloud.log.0.gz](https://github.com/owncloud/client/files/6707382/20210624_0930_owncloud.log.0.gz)

**Comment by gabi18** [comment]
'Force Sync' doesn't help, after client restart the connection is shown correctly.

![Connection_OK](https://user-images.githubusercontent.com/75983861/123225326-e5e2d180-d4d2-11eb-849d-1d07648a08df.png)

**Comment by gabi18** [comment]
Also seen with client 2.8.2 connected to demo.owncloud.com

![Error_2_8_2](https://user-images.githubusercontent.com/75983861/123226581-15460e00-d4d4-11eb-8961-a017359ae0ba.png)

**Comment by TheOneRing** [comment]
They all sound related to the regular shutdown of the demo server

**Comment by gabi18** [comment]
Yes, that's what I think.

**Comment by gabi18** [comment]
Also with 2.8.2 the folder sync connection is shown correctly after client restart:

![2_8_2_OK](https://user-images.githubusercontent.com/75983861/123227771-322f1100-d4d5-11eb-98b4-a2c7e8223918.png)

**Comment by gabi18** [comment]
But what is a further issue/question:

While 2.9 only shows the chosen folder 'Documents' the 2.8.2 client also shows the additional available folder(s) on server. 
Is this indented?

**Comment by gabi18** [comment]
The list of folder should be complete.

Related pull request: https://github.com/owncloud/client/pull/8755

**Comment by TheOneRing** [comment]
Couldn't reproduce

**Comment by gabi18** [comment]
Confirmed with with 2.9.0daily20210810 - complete folder list is shown.

![sync_folder_complete](https://user-images.githubusercontent.com/75983861/128833682-138f066a-32bd-4a1e-a4ff-91b37fdbcdb1.png)
