### ISSUE TITLE
Context menu items and folder sync icon status are not available when client is compiled using craft

### ISSUE THREAD

**Issue by vagner-dias** [owncloud/client#8781]
### Expected behaviour
when the installer is created/installed using the procedure described in https://doc.owncloud.com/desktop/building.html, context menu items and folder sync status would behave the same way as in the official installer version.

### Actual behaviour
Neither context menu items nor folder sync status are showing up when the client is compiled using craft.

Expected:
![image](https://user-images.githubusercontent.com/86367839/123323183-8ce35f80-d50b-11eb-8d1a-16f2fc965e4e.png)

Result:
![image](https://user-images.githubusercontent.com/86367839/123324021-b8b31500-d50c-11eb-8836-6919271eafbb.png)

### Steps to reproduce
Fresh windows 10 install
Intall Visual Studio 2019 community edition + Windows Communication Foundation libraries
Install Python 2.7, Python 3.6+, and PowerShell 7.0
Set-ExecutionPolicy -Scope CurrentUser RemoteSigned
iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/KDE/craft/master/setup/install_craft.ps1'))
run C:\CraftRoot\craft\craftenv.ps1
craft --add-blueprint-repository https://github.com/owncloud/craft-blueprints-owncloud.git
craft --set version=2.8 owncloud-client
craft --install-deps owncloud-client
craft --fetch owncloud-client
craft --configure --make --install
craft owncloud-client
craft nsis
craft --package owncloud-client

### Client configuration
Client version: 2.8

Operating system: Windows 10 Pro

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.15.2

Installation path of client: C:\Program Files\ownCloud

**Comment by michaelstingl** [comment]
Did you restart Windows?

**Comment by vagner-dias** [comment]
> Did you restart Windows?

Yes. I installed the owncloud client as administrator and restarted windows right after.

**Comment by TheOneRing** [comment]
The nsis does not register the plugins
