### ISSUE TITLE
Version 2.8.2.4246 Windows Client problem (Virtual filesystem does not support drive as sync)

### ISSUE THREAD

**Issue by citation79** [owncloud/client#8785]
Hi, just tried to install version 2.8.2.4246 on my Windows server 2019 and I can no longer sync to a folder I had setup on another disk (D:\owncloud).
When I try to resync it returns error that the virtual filesystem does not support drive as sync and it doesn’t let me sync unless I chose a different folder. It was working perfectly before and now with the new version it stopped responding, I tried to reinstall only to find out that error.
I had to revert to version 2.7.6 to get it working again.
Any suggestion on why am I getting this error if it was working perfectly before?

I am using Windows 2019 standard 64 bit client and I am saving the owncloud on my D drive inside a folder called owncloud.

OS: Windows 2019 Standard with latest updates (June 2021)
Owncloud install location: D:\owncloud

Steps to replicate: Install owncloud version 2.8.2.4246 and point to an owncloud folder inside the D drive. You will get the mentioned error.

**Comment by TheOneRing** [comment]
Fixed in https://github.com/owncloud/client/pull/8750
