### ISSUE TITLE
"Untrusted certificate" for valid chain on 2.8.2 with OpenSSL 1.1.1k

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#8794]
We've received a couple of reports from users testing 2.8.2 (on CentOS 8 and Fedora 34) getting prompted with the "untrusted certificate" dialog when trying to connect to [CERNBox](https://cernbox.cern.ch):

```
06-25 14:43:07:811 [ info sync.account ]: "SSL-Errors happened for url  \"https://<server>/status.php\" 
\tError in  QSslCertificate(\"3\", 
\"39:72:44:3a:f9:22:b7:51:d7:d3:6c:10:dd:31:35:95\", 
\"KF7JCcSrDS1X9QhrIleZqg==\", \"AAA Certificate Services\",
\"USERTrust RSA Certification Authority\", 
QMap(), QDateTime(2019-03-12 00:00:00.000 UTC Qt::UTC), QDateTime(2028-12-31 23:59:59.000 UTC Qt::UTC)) : 
\"The issuer certificate of a locally looked up certificate could not be found\" ( 
\"The issuer certificate of a locally looked up certificate could not be found\" ) \n 
" Certs are known and trusted! This is not an actual error.
```

Client version:

```
cernbox 2.8.2 (build 4410) May 28 2021 12:06:08
ea9d50
Libraries Qt 5.12.10, OpenSSL 1.1.1k  FIPS 25 Mar 2021
```
While on CentOS 7, the client is installed/linked to `OpenSSL 1.0.2k-fips  26 Jan 2017`

**Comment by fmoc** [comment]
Please ask these users whether they can connect to the service with a normal browser. We need to make sure that the issue is limited to the ownCloud client. The error message suggests that this is a system-wide/general usage problem rather than a desktop client one. In two up-to-date, standard CentOS 8 and Fedora 34 installations respectively live systems, connecting to CERNBox works fine.

**Comment by michaelstingl** [comment]
@SamuAlfageme In the previous Centos7 issue, you installed some packages with additional. Is this also the case for the CentOS 8 and Fedora 34? Could you post again the full steps to reproduce in clean CentOS 8 and Fedora 34 Docker containers or VMs?

**Comment by erikjv** [comment]
I have a centos7 VM, I have the owncloud client on it, and I can install the CERN certificates. Are there steps to reproduce this with and without those certificates? I tried the steps in issue #4124, but I'm not sure what to look for in the output.

**Comment by SamuAlfageme** [comment]
@michaelstingl do you mean https://github.com/owncloud/client/issues/7951#issuecomment-658208444?

**Comment by michaelstingl** [comment]
Yes. I was wondering if the new reported issue can be reproduced with vanilla C8 or F34, or does it only happen after CERN-cert-packages were installed. (Similar to #7851)

**Comment by SamuAlfageme** [comment]
@TheOneRing is something keeping https://github.com/owncloud/client/pull/8689 as WIP? Maybe we can test a custom build to see if it also fixes this collaterally.

**Comment by erikjv** [comment]
Qt will return this error text when the OpenSSL error `X509_V_ERR_UNABLE_TO_GET_ISSUER_CERT_LOCALLY` occurs. I didn't look when this happens, but I found [this](https://stackoverflow.com/questions/24315526/openssl-connection-to-a-public-server-gives-x509-v-err-unable-to-get-issuer-cert#24317266) and [this](https://github.com/openssl/openssl/commit/7d3d1788a5efe89da992e804e3624f6943d35d31) link.

Does that ring a bell with someone?

**Comment by fmoc** [comment]
I asked this question in my first comment:

> Please ask these users whether they can connect to the service with a normal browser.

This is, as far as I can see, a general certificate issue not limited to the ownCloud client. Qt just uses the system certificates, so the issue should show in other applications as well. We need to know whether this is a user error or a bug in the application (and its components).

**Comment by erikjv** [comment]
There is no error when using e.g. curl (see below). @fmoc can you tell me if I read this right?

```
[erik@localhost ~]$ curl -v -S -ssl --ssl-reqd https://cernbox.cern.ch/cernbox/desktop/remote.php/webdav/home/test
* About to connect() to cernbox.cern.ch port 443 (#0)
*   Trying 128.142.170.17...
* Connected to cernbox.cern.ch (128.142.170.17) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=*.cernbox.cern.ch
* 	start date: Mar 05 00:00:00 2021 GMT
* 	expire date: Mar 05 23:59:59 2022 GMT
* 	common name: *.cernbox.cern.ch
* 	issuer: CN=Sectigo RSA Domain Validation Secure Server CA,O=Sectigo Limited,L=Salford,ST=Greater Manchester,C=GB
> GET /cernbox/desktop/remote.php/webdav/home/test HTTP/1.1
> User-Agent: curl/7.29.0
> Host: cernbox.cern.ch
> Accept: */*
> 
< HTTP/1.1 401 Unauthorized
< Content-Length: 194
< Content-Type: text/html
< Date: Thu, 22 Jul 2021 16:56:02 GMT
< Server: nginx/1.6.2
< Www-Authenticate: Basic Realm='cboxauthd credentials'
< 
<html>
<head><title>401 Authorization Required</title></head>
<body bgcolor="white">
<center><h1>401 Authorization Required</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>
* Connection #0 to host cernbox.cern.ch left intact
```

**Comment by erikjv** [comment]
Status:

- for some reason, openssl cannot verify the issuer of the certificate that's used
- if you put that missing cert in the trust store (@crrodriguez which one), the issue goes away
- this is a warning, but the way we log it is very confusing. We could special-case this, because the enum value is `QSslError::UnableToGetLocalIssuerCertificate`

**Comment by crrodriguez** [comment]
This is a debug message, that shouldn't actually be logged unless handshake fails when certificater validation is enabled, it happens because either the server is not sending the complete certificate chain or has its trust store incomplete. it is not an error.

(to debug, use ssllabs server test, and find chain issues or  see what "extra certificate download" occurs)

**Comment by michaelstingl** [comment]
@SamuAlfageme could you verify with the 2.9-beta3?
https://download.owncloud.com/desktop/ownCloud/testing/2.9.0-beta3.5018/
