### ISSUE TITLE
server installed on /owncloud and VirtualFiles combination 

### ISSUE THREAD

**Issue by deftoner** [owncloud/client#8797]
### Expected behaviour
When adding a server that has OC installed on /owncloud, and you select VirtualFiles, should work like when you select sync all or select to sync any folder.

### Actual behaviour
When adding a server that has OC installed on /owncloud, and you sellect VirtualFiles, client will print error "no connection to owncloud at https://oc.server.com. Server replied "404 Not Found" to "PROFIND https://oc.server.com/remote.php/webdav/

During the new server add OC cliente auto detect that the server is running on /owncloud. But looks like the feature virtualfiles does not check that. If you sellect sync all or you add each folders, or even listing the online folder during the process of adding a server, everything works at it should

### Steps to reproduce
1. On client, Add account
2. Enter url of a server that is running on /owncloud but without the path (https://oc.server.com instead of https://oc.server.com/owncloud
3. Next screen select Use virtual files instead.... and click connect
4. Next windows will print the error of not found.

### Server configuration
Operating system:
Ubuntu 19.10

Web server: 
Apache

Database:
MySQL

PHP version:
7 something (is not related to this)

ownCloud version:
ownCloud 10.5.0 (stable)

Storage backend (external storage):

### Client configuration
Client version:
2.8.2 - 4246
Operating system:
Windows 10

OS language:
English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:
Default
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

https://pastebin.com/RBAua1qg

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by TheOneRing** [comment]
Hm this does look unrelated to virtual files.
To be sure this used to work with an older client so any server issues can be ruled out?

**Comment by deftoner** [comment]
> Hm this does look unrelated to virtual files.
> To be sure this used to work with an older client so any server issues can be ruled out?

Yes, latest client. It is related to virtual files, installer takes a different path after you choose virtual files. If you follow the steps is super easy to reproduce. I can make a video.

**Comment by michaelstingl** [comment]
@deftoner could you try to reproduce with the latest 2.9 pre-release build?
https://download.owncloud.com/desktop/ownCloud/daily/2.9/win/?sort=time&order=desc

**Comment by TheOneRing** [comment]
![image](https://user-images.githubusercontent.com/200626/128676912-37f50b4a-79a2-4140-8da1-57735a684603.png)

**Comment by TheOneRing** [comment]
You shouldn't be able to enter the url without /owncloud , you should get a red box with a 404 error.
Do you have some redirect rules active?
