### ISSUE TITLE
Investigate if csync processing local diretories can be optimized

### ISSUE THREAD

**Issue by guruz** [owncloud/client#880]
We're doing a ```opendir/readdir``` call but then also ```stat``` each of the contained files.

I'm guessing this is expensive.

We could optimize this. However the problem is that ```readdir``` does not return all needed information (e.g. mtime)

There is probably system calls that allow this though, for example ```FindFile``` on Windows (
http://msdn.microsoft.com/en-us/library/aa364418%28VS.85%29.aspx) or ```fts``` on Linux (http://linux.die.net/man/3/fts).

Should investigate if this is faster.

The relevant code is in ```csync_ftw``` in ```csync_update.c```

**Comment by guruz** [comment]
@ckamm Are you interested in taking this over from me? For Windows using ```FindFirstFileW``` in ```csync_vio_local_opendir``` instead of the Windows POSIX stuff?

**Comment by guruz** [comment]
Another idea instead of using ```FindFirstFileW``` directly In the same go this should fix https://github.com/owncloud/client/issues/60 via https://github.com/owncloud/client/issues/60#issuecomment-70245354

**Comment by guruz** [comment]
Update: @dragotin has switched the Windows code to use ```FindFirstFileW``` for 2.0. I'll try to do some optimizations based on this.

**Comment by dragotin** [comment]
This is done.
