### ISSUE TITLE
Using the language selector to select an RTL language on mac does not cause the ui to be reversed

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#8806]
![image](https://user-images.githubusercontent.com/200626/124591641-d2cdeb00-de5c-11eb-82a4-34cf5364fbe2.png)

**Comment by TheOneRing** [comment]
Maybe because we call the translations code AFTER we initialized QApplication?

**Comment by fmoc** [comment]
I think we just need to call `setLayoutDirection` in `setupTranslations`, once we can tell whether we have an RTL language or not. https://doc.qt.io/qt-5/qguiapplication.html#layoutDirection-prop

**Comment by fmoc** [comment]
I cannot reproduce this issue. You didn't reveal which locale you were testing against. I selected a random right-to-left-looking language, and without a code change the layout was changed:

![grafik](https://user-images.githubusercontent.com/80399010/125012905-7801e280-e05a-11eb-9ee4-54080f74d206.png)

I can also control the layout direction using `setLayoutDirection`. We could add the following snippet to `setupTranslations` nevertheless, if you want to:

```cpp
            // use a right-to-left layout for such languages
            QApplication::setLayoutDirection(QLocale(lang).textDirection());
```

**Comment by TheOneRing** [comment]
I don't think we should call it directly this should be handled by the translations system.
The issue seems to only occur on mac.
I could imagin it being caused by us setting up the translations in the QApplication constructor....
@erikjv

**Comment by erikjv** [comment]
Hmm, Qt has this in `QGuiApplicationPrivate::init()`:
```C++
    if (layout_direction == Qt::LayoutDirectionAuto || force_reverse)
        QGuiApplication::setLayoutDirection(qt_detectRTLLanguage() ? Qt::RightToLeft : Qt::LeftToRight);
```
That in turn is called from the `QApplication` constructor.

That said, I assume you're not running with the `-reverse` cmdline option, right? And your translations have the following translated:
```C++
        (QGuiApplication::tr("QT_LAYOUT_DIRECTION",
                         "Translate this string to the string 'LTR' in left-to-right"
                         " languages or to 'RTL' in right-to-left languages (such as Hebrew"
                         " and Arabic) to get proper widget layout.") == QLatin1String("RTL"));
```
Correct?

**Comment by gabi18** [comment]
Remaining problem with systray menu?

![CleanShot 2021-09-30 at 14 14 01@2x](https://user-images.githubusercontent.com/75983861/135457836-6ef4b337-ed69-4453-aa7a-e7a8555d1d40.png)
