### ISSUE TITLE
Virtual Filesystem reports: "Does not support a drive as sync root" even though path is not at root of drive

### ISSUE THREAD

**Issue by Xalaxis** [owncloud/client#8807]
### Expected behaviour

When giving a path such as S:\ShadowPlay, the VFS feature should work, as the path is not at the root of the drive.

### Actual behaviour

The error below is produced.

![image](https://user-images.githubusercontent.com/12937964/125145907-51f04700-e11b-11eb-8aaf-d668f2b712aa.png)

### Steps to reproduce
1. Attempt to add a path that is not at the drive's root as a VFS sync (maybe only top level +1?)
2. Sync creation will error

This may be a regression, as this folder has previously been in a sync pairing and a user at https://central.owncloud.org/t/version-2-8-2-4246-windows-client-problem-virtual-filesystem-does-not-support-drive-as-sync/32777/2 reports the same issue.

### Server configuration
Operating system: Docker/Unraid 6.9.2

Web server: Unknown, latest docker

Database: Unknown, latest docker

PHP version: Unknown, latest docker

ownCloud version: 10.7.0 Stable

Storage backend (external storage): Local

### Client configuration
Client version: Version 2.8.2 (build 4246)

Operating system: Windows 11 Version 21H2 (OS Build 22000.51)

OS language: English (United Kingdom)

Installation path of client: C:\Program Files\ownCloud

### Logs

Omitting logs as this appears to be a strictly client-side issue, and the only notable log line was 

`07-10 01:18:42:357 [ info gui.account.settings ]:	Folder wizard cancelled` showing the folder sync creation was cancelled. No mention was made of the error displayed or why. Happy to provide logs if needed.

**Comment by michaelstingl** [comment]
Duplicate for https://github.com/owncloud/client/issues/8785

Already fixed. 

You can test-drive with the 2.9-prerelease builds:
https://download.owncloud.com/desktop/ownCloud/daily/2.9/win/?sort=time&order=desc
