### ISSUE TITLE
command line client "hangs" when working in a script file.

### ISSUE THREAD

**Issue by xmana** [owncloud/client#8813]
### Expected behaviour
The command line client should execute and return an exit code.

### Actual behaviour
The command line client, under certain circumstances, stops in a waiting state.

### Steps to reproduce

1.  First, let's place some arbitrary files in a folder on the local computer. Next, let's synchronize. The operation is successful. See log file log001.log.
[log001.log](https://github.com/owncloud/client/files/6809054/log001.log)

2. Next, we delete all the files from the specified folder on the local computer and sync again. As a result, the command line client "hangs" pending the user's response.  See log file log002.log. In the log we see the following message: "All the files are going to be changed, asking the user"
[log002.log](https://github.com/owncloud/client/files/6809300/log002.log)

The same situation occurs if in the second step, you delete all the files from the specified folder on the server side.

As you can see from the log, the command line client is called with the parameter --non-interactive, which in this case does not work ...

In my opinion, this is one of several reasons that cause the problem №8327.
https://github.com/owncloud/client/issues/8327.

As a workaround, I can suggest leaving at least one file to avoid "hanging".

### Server configuration
Operating system:
PRETTY_NAME="Ubuntu 20.04.1 LTS"

Web server: 
nginx version: nginx/1.19.6
built by gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.12)
built with OpenSSL 1.0.2g  1 Mar 2016 (running with OpenSSL 1.0.2n  7 Dec 2017)
TLS SNI support enabled

Database:
mysql  Ver 15.1 Distrib 10.3.25-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2

PHP version:
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

ownCloud version:
ownCloud 10.5.0

Storage backend (external storage):
none

### Client configuration
Client version:
ownCloud 2.8.2 (build 4246) May 28 2021 07:23:56
https://github.com/owncloud/client/commit/ea9d50062fe1bda7bd1b96b406519f1b6564662f
Libraries Qt 5.12.10, OpenSSL 1.1.1k  25 Mar 2021
Using virtual files plugin: suffix

Operating system:
Win 7 Pro x64

OS language:
Ukrainian

Qt version used by client package (Linux only, see also Settings dialog):
Libraries Qt 5.12.10

Client package (From ownCloud or distro) (Linux only):
---

Installation path of client:
"C:\Program Files (x86)\ownCloud\owncloudcmd.exe"

### Logs
provided above

### Remark

Is there a possibility to solve this issue, except for the transition to paid maintenance?

**Comment by TheOneRing** [comment]
You might have experienced an issue that was fixed in https://github.com/owncloud/client/pull/8805

Could you test with a 2.9 dayli https://download.owncloud.com/desktop/ownCloud/daily/2.9/

**Comment by xmana** [comment]
on version 2.9.0beta3 (build 5018) the problem ceased to be observed
