### ISSUE TITLE
create tests for enabling/disabling VFS

### ISSUE THREAD

**Issue by individual-it** [owncloud/client#8821]
Even it would be hard to test the underlying functionality of VFS, enabling and disabling VFS in the client should have visual effects, we can test those.

CC @jnweiger

**Comment by swoichha** [comment]
It has been already added to the list here https://github.com/owncloud/client/issues/8651#issuecomment-857373491

**Comment by swoichha** [comment]
https://github.com/owncloud/client/pull/8835 has been merged so closing it now
