### ISSUE TITLE
Bundle resources using qrc to ease deployment

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#8822]
Deployment of additional resources is not easy, and can cause a lot of issues, e.g., because of differences between the target platforms. Some of these issues are eased by Qt. However, it might be beneficial to ship as many resources as possible using Qt's built-in resource system called [qrc](https://doc.qt.io/qt-5/resources.html).

Recently, we noticed that translations are not loaded correctly in the AppImages we build. This is due to a limitation of `QStandardPaths` which is documented in the [AppImage best practices](https://docs.appimage.org/reference/best-practices.html). This issue makes the binary non-relocatable, which is important to AppImages. We would have to implement a workaround specific to Linux to resolve this issue.

We already use qrc files to bundle resources in the binaries for theme files (cf. https://github.com/owncloud/client/blob/master/cmake/modules/OCGenerateTheme.cmake#L35, https://github.com/owncloud/client/blob/master/src/gui/main.cpp#L48).

We should bundle at least the translations using qrc as well, and then simplify the loading code accordingly.

**Comment by fmoc** [comment]
@TheOneRing are you aware of other resources which we could bundle with qrc that we haven't thought of yet?

**Comment by TheOneRing** [comment]
The exclude list but and the ownbrander2 theme, but not yet :)

**Comment by TheOneRing** [comment]
At the moment I'd say we bundle everything that needs bundling.
