### ISSUE TITLE
Regression use of legacy settings location

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#8824]
Testpilot cloud now falls back to the legacy location C:\Users\hanna\AppData\Roaming\testpilotcloud....

Introduced in https://github.com/owncloud/client/pull/8670

The migration in https://github.com/owncloud/client/blob/master/src/gui/application.cpp#L171 was broken since the first day as 
https://github.com/owncloud/client/blob/master/src/libsync/configfile.cpp#L112 was setting the legacy name each time the constructor is called.

TODO:
- Remove all calls to setApplicationName besides the main one in Application.
- Implement an additional migration path to the short name location.

**Comment by fmoc** [comment]
Fixed in #8860.
