### ISSUE TITLE
Terminology "dehydrate" winVFS

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8825]
We use the term "to dehydrate" and "DEHYDRATION" in the source code and in developer documentation.
A file is dehydrated (also called in virtual state) - when only metadata are present on a user's device, but the content is remote.
A file is in hydrated (or physical) state otherwise. This is the "normal" state, known from all files not in a VFS.

I suggest to avoid this term in In user-facing dialogs and documentation. Microsoft does the same. They typically use "Free up space" for the dehydrate (make virtual) action and "Keep on this device" for the hydrate (make physical) action.

References:
* https://support.microsoft.com/de-de/office/sparen-von-speicherplatz-mit-onedrive-dateien-bei-bedarf-f%C3%BCr-windows-10-0e6860d3-d9f3-4971-b321-7092438fb38e?ui=de-DE&rs=de-DE&ad=DE
* https://support.microsoft.com/en-us/office/save-disk-space-with-onedrive-files-on-demand-for-windows-10-0e6860d3-d9f3-4971-b321-7092438fb38e

Example error message that sparked this discussion: "Failed to dehydrate %1, the file is currently in use"
* Suggested English version: "Failed to free up space, the file %1 is currently in use"
* Suggested German version: "Kann Speicherplatz nicht freigeben, die Datei %1 wird gerade benutzt"

**Comment by TheOneRing** [comment]
Please eopen if you find another string.
