### ISSUE TITLE
Allow users to choose unsync behaviour

### ISSUE THREAD

**Issue by theycallmelaurenz** [owncloud/client#8828]
Unchecking folders in a folder sync connection warns the user that those folders will be deleted locally. This is counter-intuitive. Right now, it is not possible to unsync a folder without deleting the local copy. Even worse, despite the warning message at the bottom of the window, this leads to users accidentally deleting local folders, which they may not realise until it is too late.

I suggest that users are given the choice to simply unsync the unchecked folders, or to delete them.

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/client/issues/2502
