### ISSUE TITLE
STATUS:OK is reported before internal delay is finished

### ISSUE THREAD

**Issue by individual-it** [owncloud/client#8832]
When the client touches a file, the change notifications are blocked for some time but the status of the file is already reported as `STATUS:OK`. This happens e.g. when a new account is connected and all files are synced down.

The responsible code is https://github.com/owncloud/client/blob/9117275c67ca311152b4f16749c6fd32c3d40fe9/src/libsync/syncengine.cpp#L61-L74

For the GUI tests this is an issue, because as soon as `STATUS:OK` is reported back by the socket API the tests assume that the next step can be carried out. If the tests change the file during this delay, the client ignores the change and does not upload the changed file.

In #8814 a static wait had to be implemented to make sure that the file is ready to be changed.

Ideally `STATUS:OK` would only be reported AFTER the delay is over, both for the folder as well as the files. But it also would be sufficient if the status of the root folder would be something different than `OK` during the delay.

This would help the tests to act correctly and not to waste time even if the delay would change in the future.

**Comment by TheOneRing** [comment]
`STATUS:OK` Is meant for applications waiting for the availability of the file and for the status icon of the file and not designed for testing.

If a sync is enforced we would still detect the change to the file.

**Comment by individual-it** [comment]
With the end-to-end tests we trying to rely only on things that a user could do. A user would wait till the status icon is indicating that the file is synced and then change the content of it. The only thing the tests do different is checking the status through the socket API and not watching the visual icon. And the tests are obviously faster than a user. It's unlikely (but possible) that a user would overwrite a file within the first 3sec.

> STATUS:OK Is meant for applications waiting for the availability of the file
That is exactly what we are trying to do. The End-to-End test-suite is the application waiting for the availability of the file. As soon as the socket API says the file is available, it get changed, but then the sync does not work. So strictly speaking `STATUS:OK` indicates that the file was available for read but not for write. If that is what it is supposed to indicate, then the feature works as intended, but the tests would need an other solution to find out if a file is ready to be written.

We could keep the static waits, but that would lead to the issues I described above.

Or we do a force-sync. That would cost a lot of time (because AFAIK it cannot be done by soket-API, but need to be done through UI clicks) and even more important it would not test what we are intending to test. We want to test if the client picks up and uploads a file change correctly. Using the force-sync would not test that behavior.

**Comment by TheOneRing** [comment]
Again it is ok to directly write to that file, it will just not be directly synced.

I agree that the timeout behaviour is not optimal but at least for now there is nothing we can change easily. 
For testing we could emit a signal once the file is watched again but 🤷‍♀️

**Comment by TheOneRing** [comment]
@dragotin I think we should clear the touched list once we finished the propagation, what do you think?

**Comment by TheOneRing** [comment]
@dragotin we actually clear the list of touched files https://github.com/owncloud/client/blob/master/src/libsync/syncengine.cpp#L109 but only 30s after the sync... any idea why?

**Comment by TheOneRing** [comment]
Hmm https://github.com/owncloud/client/commit/28c12a3ca0769877e7b900c5bc4b1e9148dd5abf

Could the file watcher be so slow that it takes 30s to detect all changes we induced?

**Comment by dragotin** [comment]
The reasoning for the whole touchFilesList are summarized here: https://github.com/owncloud/client/blob/master/src/libsync/syncengine.cpp#L61

Actually I think the 30 seconds after the propagation is finished is really long... 

OTOH, I don't think it really play a role because in `slotAddTouchedFile(const QString &fn)` there is a check that removes entries that are older than the 3 seconds from the list. So the 30 seconds thing is really a general cleanup, when nothing else happens.
