### ISSUE TITLE
[QA] Add hint to GUI testing documentation

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#8841]
There should be a hint in the docu that it might be necessary to change the ownership of the file ~/squish-for-qt-X.x.x/etc/paths.ini.

I have followed the steps described in https://doc.owncloud.com/desktop/appendices/guitest.html until
https://doc.owncloud.com/desktop/appendices/guitest.html#configure-squish.

Then when I tried to start the Squish IDE  I got an error message:

![squish_error](https://user-images.githubusercontent.com/75983861/126958706-0935e01a-c5b8-4e0c-9036-926e723e2c18.png)

The reason is written to the log file ~/.squish/squishlibrary0.log.0:

 <message>PTR: [com.froglogic.squish.util.ProcessToolRunner@72d0196d] content from stderr: Could not read paths for robust application from /home/gabi/squish-for-qt-6.7.1/etc/paths.ini
</message>

It's because paths.ini only is readable for root.
-rw-------  1 root root   1176 Jul 26 08:43 paths.ini

Solution:
Change the ownership of paths.ini to make it readable for the user.

```
gabi@gabi-VirtualBox:~/squish-for-qt-6.7.1/etc$ ll
total 444
drwxrwxr-x  2 gabi gabi   4096 Jul 26 08:43 ./
drwxrwxr-x 16 gabi gabi   4096 Jul 26 08:43 ../
-rw-r--r--  1 gabi gabi    388 Jun 11 01:41 android_snapshot_filter.xml
-rw-r--r--  1 gabi gabi    945 Jun 11 01:41 android_visualvp_filter.xml
-rw-r--r--  1 gabi gabi   5673 Jun 11 01:41 androidwrapper_descriptors.xml
-rw-rw-r--  1 gabi gabi 236061 Jun 11 01:41 cacert.pem
-rw-r--r--  1 gabi gabi   4092 Jun 11 01:41 flexwrapper_descriptors.xml
-rw-r--r--  1 gabi gabi   1500 Jun 11 01:41 flexwrapper.ini
-rw-r--r--  1 gabi gabi    384 Jun 11 01:41 ios_snapshot_filter.xml
-rw-r--r--  1 gabi gabi   1319 Jun 11 01:41 ios_visualvp_filter.xml
-rw-r--r--  1 gabi gabi    385 Jun 11 01:41 java_snapshot_filter.xml
-rw-r--r--  1 gabi gabi   6487 Jun 11 01:41 java_visualvp_filter.xml
-rw-r--r--  1 gabi gabi  10461 Jun 11 01:41 javawrapper_descriptors.xml
-rw-r--r--  1 gabi gabi   2469 Jun 11 01:41 javawrapper.ini
-rw-r--r--  1 gabi gabi    384 Jun 11 01:41 mac_snapshot_filter.xml
-rw-r--r--  1 gabi gabi    593 Jun 11 01:41 mac_visualvp_filter.xml
-rw-r--r--  1 gabi gabi  10511 Jun 11 01:41 macwrapper_descriptors.xml
-rw-------  1 gabi gabi   1176 Jul 26 08:43 paths.ini
-rw-rw-r--  1 root root   1245 Jul 26 08:43 paths.ini.original
-rw-r--r--  1 root root    590 Jul 26 08:43 pythonchangerlog.txt
-rw-r--r--  1 gabi gabi    383 Jun 11 01:41 qt_snapshot_filter.xml
....
```

**Comment by gabi18** [comment]
@swoichha Could you please take care.

**Comment by jnweiger** [comment]
It works differently for me :-)

`sudo ./squish-6.7.0-qt512x-linux64.run` suggests to install squish under `cd  -- I haven't changed that, and got everything inside the home of user root, owned by user root.
PythonChanger.py must then be run not in my home, but 
```
cd /root/squish-for-qt-6.7.0
wget https://kb.froglogic.com/squish/howto/using-external-python-interpreter-squish-6-6/PythonChanger.py
python3 PythonChanger.py --force
```

**Comment by gabi18** [comment]
Please also add a short description about the prerequisites before the step:
` * Start the owncloud-test-middleware`

- a hint that before running middleware one have to clone https://github.com/owncloud/owncloud-test-middleware/
- an instruction how to install correct `yarn` (e.g. https://classic.yarnpkg.com/en/docs/install/#debian-stable)

On my system I had the problem that a wrong version of `yarn` was installed, in fact I had installed `cmdtest` instead of the `yarn` package (yarn version was 0.32+git)
I did `apt remove cmdtest` and then followed above instructions for Debian/Ubuntu to get yarn version 1.22.5.

**Comment by gabi18** [comment]
... and a hint that before the step 
`* Click the play button for a test-case or scenario.`

one has to quit the desktop client (which is started when doing the check if everything works properly via Run  Lauch AUT)

Thank you!

**Comment by gabi18** [comment]
Maybe also worth a hint that the password for user 'admin' has to be 'admin' on BACKEND_HOST.

**Comment by swoichha** [comment]
https://github.com/owncloud/docs-client-desktop/pull/77 has been merged. So, closing this issue for now.
