### ISSUE TITLE
Prevent multiple accounts from sharing a sync folder

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#8849]
Since https://github.com/owncloud/client/commit/838c072ccc2dd56b56ef256b70179361d8f226d2 we allow that multiple accounts share the same sync folder.
- In combination with virtual files it leads to data loss
- Security risk by allowing mirroring to an external server
- We don't warn that we mirror to an external server

**Comment by pmaier1** [comment]
- Write down reasoning why to drop the feature => deprecation note
- Alternatives?
- Drop with 2.9

**Comment by jnweiger** [comment]
Retested in an update scenario on Linux Mint: 
* testpilotcloud 2.9.0-beta3 and owncloud 2.9.0-beta3 configured a remote connection to different servers using the shared ~/ownCloud4 sync folder.
* the servers start sharing data in a confusing way. To be expected. This is before @erikjv 's fix came in.
* stop both clients. Upgrade both to 2.9.0-rc1 to bring in that fix.
* start testpilotcloud client. Wait for sync to complete
* start owncloud client -- it hangs frozen.
* killall owncloud, to be really sure there is nothing old.
* Try inf foreground from the shell as follows, window frame is drawn without contents, Place for tray icon is created without content, we get only these few lines of output then it hangs:
```
$ owncloud --debug -s --logflush --logfile -
08-30 17:20:41:171 [ debug default ]    [ OCC::Logger::setLogRules ]:   "gui.*.debug=true\nsync.*.debug=true\nsync.httplogger=true"
08-30 17:20:41:171 [ debug default ]    [ OCC::Logger::setLogRules ]:   "gui.*.debug=true\nsync.httplogger=true\nsync.*.debug=true\nsync.httplogger=true"
08-30 17:20:41:197 [ info gui.application ]:    ################## "ownCloud" locale: "en_US" version: "ownCloud 2.9.0rc1 (build 5070) 49cfb1 Aug 27 2021 17:26:42 Libraries Qt 5.12.10, OpenSSL 1.1.1f  31 Mar 2020 Using virtual files plugin: off linuxmint-5.4.0-81-generic"
08-30 17:20:41:197 [ info gui.application ]:    Arguments: ("owncloud", "--debug", "-s", "--logflush", "--logfile", "-")
08-30 17:20:41:198 [ info gui.application ]:    Using "en_US" translation
08-30 17:20:41:198 [ info gui.application ]:    Adding extra plugin search path: "/opt/ownCloud/ownCloud/bin/../lib/x86_64-linux-gnu/plugins"
08-30 17:20:41:200 [ info gui.application ]:    VFS suffix plugin is available
08-30 17:20:41:200 [ info gui.socketapi ]:      server started, listening at  "/run/user/1000/ownCloud/socket"
08-30 17:20:41:258 [ info gui.account.manager ]:        Restored:  0  unknown certs.
08-30 17:20:41:258 [ info gui.account.manager ]:        Restored:  0  unknown certs.
08-30 17:20:41:258 [ info gui.account.manager ]:        Restored:  0  unknown certs.
08-30 17:20:41:259 [ info gui.account.manager ]:        Restored:  1  unknown certs.
08-30 17:20:41:283 [ debug gui.activity ]       [ OCC::ActivitySettings::setNotificationRefreshInterval ]:      Starting Notification refresh timer with  300  sec interval
08-30 17:20:41:298 [ debug gui.application ]    [ OCC::GeneralSettings::loadLanguageNamesIntoDropdown ]:        Warning: could not find native language name for locale "TW"
08-30 17:20:41:394 [ debug gui.updater ]        [ OCC::Updater::getSystemInfo ]:        Sys Info size:  83
08-30 17:20:41:394 [ debug gui.updater ]        [ OCC::Updater::create ]:       QUrl("https://updates.owncloud.com/client/?client=RGlzdHJpYnV0b3IgSUQ6CUxpbnV4bWludApEZXNjcmlwdGlvbjoJTGludXggTWludCAyMC4yClJlbGVhc2U6CTIwLjIKQ29kZW5hbWU6CXVtYQo%3D&version=2.9.0.5070&platform=linux&oem=ownCloud&buildArch=x86_64&currentArch=x86_64&versionsuffix=rc1")
08-30 17:20:41:470 [ info gui.application ]:    Tray menu workarounds: noabouttoshow: false fakedoubleclick: false showhide: false manualvisibility: false
08-30 17:20:41:479 [ info gui.folder.manager ]: Setup folders from settings file
08-30 17:20:41:479 [ info plugins ]:    Created VFS instance from plugin "owncloudsync_vfs_suffix"
08-30 17:20:41:479 [ debug gui.folder ] [ OCC::Folder::checkLocalPath ]:        Checked local path ok
08-30 17:20:41:479 [ info sync.configfile ]:    Adding system ignore list to csync: "/etc/ownCloud/sync-exclude.lst"
```

**Comment by jnweiger** [comment]
TODO:
* [ ] retest upgrade with shared sync root on a fresh system
* [ ] retest on windows

I'd venture a guess: the client tries an exclusive flock() on its sqlite db, while the same file is already flock()ed exclusively by the alread running client?

**Comment by jnweiger** [comment]
Retested the upgrade scenario in Fedora 33

* install both testpilot cand owncloud client in verison 2.8.2, 
* connect both with different accounts to servers, using the same e.g. `~/testpilotcloud3` sync folder
* wait for (chaotic) cross sync to finish. quit both, upgrade both to 2.9.0 rc1
* both continue happily to sync. BAD

![image](https://user-images.githubusercontent.com/1108546/131469754-d7a70dd9-4210-4f93-bff7-19f70fe6c6be.png)
[testpilotcloud-logdir.zip](https://github.com/owncloud/client/files/7082384/testpilotcloud-logdir.zip)
[ownCloud-logdir.zip](https://github.com/owncloud/client/files/7082385/ownCloud-logdir.zip)

**Comment by jnweiger** [comment]
Regarding charotic syncing:
* Using VFS on Linux (Placeholder mode) in one client, and physical mode in the other client, bad things happen.
   - placeholder files are uploaded to the server (seen in 2.9.0-rc1)
![image](https://user-images.githubusercontent.com/1108546/131491231-e78bb485-3c06-4a44-9f07-206734f57192.png)

**Comment by jnweiger** [comment]
Retested the upgrade scenario in Windows 10

 *  install both testpilot cand owncloud client in verison 2.8.2,
 *  connect both with different accounts to servers, using the same sync folder
 *  wait for (chaotic) cross sync to finish. quit both, upgrade both to 2.9.0 rc1
 *  same as on Fedora33 above, both clients happily sync.
![image](https://user-images.githubusercontent.com/1108546/131524964-bd7f3854-d057-4e41-b234-0fb76029467d.png)

A third sync folder connetcion (fresh, not from an upgrade) cannot be added to the same sync folder:
![image](https://user-images.githubusercontent.com/1108546/131525615-f5d4e086-f869-4150-8bc0-85404ca3ad59.png)

**Comment by jnweiger** [comment]
I am not sure what the expected behaviour should be:

a) Detect the folder sharing and prevent using that with 2.9.0 and later.
b) Allow it as a legacy configuration so to not disrupt the user too much. But disallow the creation of the same.

Currently we do b) -- this has two disadvantages
1) the user might experience some misbehaviour
2) the user is not aware that the same sharing cannot b recreated with 2.9.0

To make b) nice and safe, I suggest to pop up a warning dialog, e.g. like this:

"Warning: Legacy shared sync folder detected: Folder testpilotcloud3 is connected to bothadmin@xyz.com and demo@abc.com -- this can lead to bad side effects including data loss, especially when using VFS. Please resolve this as soon as possible.   [Remove Account] [Continue for now]"

**Comment by TheOneRing** [comment]
At the moment the behavior is ok, we didn't plan to break existing setups we just want that never to happen again.
