### ISSUE TITLE
make a separate object for VFS enabled banner

### ISSUE THREAD

**Issue by swoichha** [owncloud/client#8867]
### Description
While adding tests for VFS(https://github.com/owncloud/client/issues/8651#issuecomment-857373491) we needed to verify if it was enabled or not using a purple banner with text `Virtual file support is enabled.`. However, while adding this test we could not find an object for that. It was inside another object as it can be seen in the image below.
![Screenshot from 2021-07-26 15-59-58](https://user-images.githubusercontent.com/17021686/128309883-fab5b53a-d9d8-4cec-b35d-25856414373c.png)

The element that we want for this test to work does not have a UI file. It is a custom paint job based on model. This make testing a little bit hard. 

### Possible Solution
For now we have added the test here https://github.com/owncloud/client/pull/8835 and verified the enabling/disabling of VFS using the enable/disable VFS button which is an object `names.stack_folderList_QTreeView, "_1"` at `718,27`. But it would be better if we could get an object for the VFS enabled element.

**Comment by TheOneRing** [comment]
As I said before the delegate just directly paints the text.
The above screenshot shows me that you get a QModelIndex, you need to access the data() function of that object and query for  `FolderStatusDelegate::FolderInfoMsg` value `362`.

Now on how you can get the value from a QModelIndex, no idea but I'm pretty sure squish supports it.
