### ISSUE TITLE
Release Desktop 2.9

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#8869]
## Reason

* Needed for branded client 2.9 release (add link to branded release ticket)
* ...

### Template
[Release Template](https://github.com/owncloud/client/blob/master/.github/patch_release_template.md) 

__TODO__: [patch_release_template.md](https://github.com/owncloud/client/blob/master/.github/patch_release_template.md) is used here because it's the newest, updated version for a release ticket template. What might be missing from [release_template.md](https://github.com/owncloud/client/blob/master/.github/release_template.md) should be merged so we can use one template for patch, minor or major release in future (rename template accordingly).

### Create Changelog

* ~[x] DEV: Update [ChangeLog](https://confluence.owncloud.com/display/OG/ChangeLog)~ XXX delete here

### Prerequisites

* [x] QA: Update [Test Plans](https://confluence.owncloud.com/display/OG/Test+Plan+Update)  new URL: https://confluence.owncloud.com/display/OG/Desktop+Client+Test+Plan+Maintenance XXX
* [ ] QA: Update [documentation](https://confluence.owncloud.com/display/OG/Documentation)
* [x] QA: Check the translations coming from https://github.com/owncloud/client/actions/workflows/translate.yml   XXX
* [x] DEV: check for new OpenSSL version XXX
* [x] DEV: Check [dependencies](https://confluence.owncloud.com/display/OG/Dependencies) for updates
* [x] DEV: Prepare the release in a `X.x` version branch (patch release is maintained in minor release branch) XXX
* [x] DEV: bump VERSION.cmake in master to say 2.(x+1).x unless already done.

### Build

* [x] DEV: Tag and build [builds](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-Sprintbuild) for theme 'ownCloud' and 'testpilotcloud' XXX
* ~[x] QA: Check the new subfolder of [testing download](https://download.owncloud.com/desktop/ownCloud/testing/) if `*tar.xz.asc` files are there. If not follow the [instructions](https://github.com/owncloud/enterprise/wiki/Desktop-Signing-Knowledge)~ XXX not needed
* [x] Beta/RC Communication (https://confluence.owncloud.com/display/OG/Marketing+and+Communication)
   * [x] Website links for beta (needed for the following posts)
   * [ ] Central post https://central.owncloud.org/tags/c/news/desktop
   * [x] All other stakeholders
* [x] QA: Check crash reporter (WIN/Mac/Linux Appimage: start 'owncloud --debug' on cmd line, system tray right click menu choose 'Crash now - qt fatal') XXX

### QA

~#### DEV QA~ XXX
* [x] DEV: [Smash box test](https://drone.owncloud.com/owncloud/smashbox-testing) Make sure tests run on latest version XXX
* [x] QA: [Smoke test](https://confluence.owncloud.com/display/OG/Manual+Tests#ManualTests-DEVSmokeTest) XXX
* [ ] ~DEV: Run [automated tests](https://confluence.owncloud.com/display/OG/Automated+Tests)~ moved to BTR QA
~#### BTR QA~ XXX
* [x] QA: Run [automated tests](https://confluence.owncloud.com/display/OG/Automated+Tests)
   * [ ]  XXX TODO:  add "xvfb-run owncloud-client" to RUN.sh [Xvfb](https://en.wikipedia.org/wiki/Xvfb)
* [x] QA: Make sure squish tests are running successfully on 2.9 branch: go to https://github.com/owncloud/client,  click on 'commits', check 'continious integration' on drone /GUI-tests-@smokeTest/GUITests   XXX move to prerequisites
* [x] QA: [Antivirus scan](https://confluence.owncloud.com/display/OG/Virus+Scanning)
* [x] QA:  Regression Testplan https://github.com/owncloud/client/issues/8870
Create regression testplan according to release type (patch or minor, see ~https://confluence.owncloud.com/display/OG/Manual+Tests#ManualTests-RegressionTest~ https://confluence.owncloud.com/display/OG/Desktop+Client+Release+Process) and link here XXX 
* [x] QA: Changelog Testing https://github.com/owncloud/client/issues/8870#issuecomment-899592913
Add link to Changelog Test XXX

~### After QA Approval~ XXX remove headline

~* [ ] DEV: Tag and build [builds](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-Sprintbuild) for theme 'ownCloud' and 'testpilotcloud' for final build~ XXX moved to Final rebuild

### Final Rebuild

* [x] DEV: Tag and build [builds](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-Sprintbuild) for theme 'ownCloud' and 'testpilotcloud' for final build XXX
~* [ ] DEV: Change the date in `ChangeLog` to the date of creating the tag~ TODO: create confluence page with info about final DEV release steps  XXX
~* [ ] DEV: Bump `MIRALL_VERSION_PATCH` in [`VERSION.cmake`](https://confluence.owncloud.com/display/OG/Branching+Off#BranchingOff-PatchRelease)~ XXX
* [ ] DEV: Adjust [Linux Templates](https://confluence.owncloud.com/display/OG/Branching+Off#BranchingOff-Linuxtemplates) to support the next patch release version (e.g. 2.6.2)->  domme fabian
~* [ ] DEV: Trigger the [build job](https://confluence.owncloud.com/display/OG/Build+and+Tags#BuildandTags-Finalbuild)~ included in tag and build (see above)
* [x] DEV: Ping marketing to do their [actions](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-Marketingtasks)
* [x] DEV: Create [a (draft) release](https://github.com/owncloud/client/releases) with Download links - save as a draft until smoke tested
* [ ] QA: Create a new release issue for a branded release if needed
* [x] QA: Give [heads-up](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-Heads-upbeforethefinalrelease) before the final release 

### Final QA

* [x] QA: [Smoke test](https://confluence.owncloud.com/display/OG/Manual+Tests#ManualTests-SmokeTest)
~* [ ] DEV: Check if [GitHub download links](https://github.com/owncloud/client/releases) point to correct location~ XXX
* [x] DEV: Publish the release in GitHub XXX
~* [ ] QA: Check [minimum.supported.desktop.version](https://github.com/owncloud/core/blob/master/config/config.sample.php#L1367) on the server~ XXX related to server release

### Communicate the Availability

* [ ] Final Communication https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-Central
   * [ ] Website links for final release (needed for the following posts)
   * [ ] QA: Central post https://central.owncloud.org/tags/c/news/desktop
   * [ ] QA: Inform other [stakeholders](https://confluence.owncloud.com/display /OG/Marketing+and+Communication#MarketingandCommunication-InformStakeholdersaboutFinal) XXX
   * [x] QA: Inform [packagers](https://confluence.owncloud.com/display/OG/Marketing+and+Communication#MarketingandCommunication-Packagers) - ping @dragotin (openSUSE)

### Final Infrastructure Check

* [x] QA/DEV: Update [stable channel](https://confluence.owncloud.com/display/OG/Online+Updater%2C+Crash+reporter%2C+Transifex#OnlineUpdater,Crashreporter,Transifex-UpdatetheUpdater) in the owncloud hosted auto updater
* [x] QA: Ensure that the [client patch release template](https://github.com/owncloud/client/blob/master/.github/patch_release_template.md) is up to date and in sync with other client templates XXX
* [x] QA: Ensure that the [client test plan template](https://github.com/owncloud/QA/blob/master/Desktop/Regression_Test_Plan_Patch_Release.md) is up to date. XXX
~* [ ] QA: Update [supported platforms](https://confluence.owncloud.com/display/OG/Supported+Platforms)~ -> branded release XXX

### A Few Days After the Release

* [x] DEV: Check the [crash reporter](https://confluence.owncloud.com/display/OG/Online+Updater%2C+Crash+reporter%2C+Transifex#OnlineUpdater,Crashreporter,Transifex-CrashReporter) for bad/frequent crashes

**Comment by gabi18** [comment]
### Issues found while testing:

**Comment by jnweiger** [comment]
On windows 10_20H2v2 stored credentials are correctly re-used after the upgrade.

**Comment by jnweiger** [comment]
|| Linux Package Installation Report |
|-|-|
|date| Wed Sep  8 17:57:34 CEST 2021
|repourl| https://download.owncloud.com/desktop/ownCloud/testing/2.9.0.5147/linux/
|package| owncloud-client

<details><summary>Test details (click to view)</summary>

|Platform|Test|Result|
|-|-|-|
|centos:7|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 14:19:17
|centos:8|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 13:21:10
|debian:9|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 13:21:10
|debian:10|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 13:21:10
|fedora:31|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 13:21:10
|fedora:32|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 13:21:10
|fedora:33|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 13:21:10
|fedora:34|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 13:21:10
|ubuntu:18.04|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 13:21:10
|ubuntu:20.04|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 13:21:10
|ubuntu:20.10|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 13:21:10
|ubuntu:21.04|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 13:21:10
|opensuse/leap:15.1|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 13:21:10
|opensuse/leap:15.2|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 13:21:10
|opensuse/leap:15.3|01_cmd_vers.sh|	2.9.0 (build 5147) Sep  8 2021 13:21:10
|centos:7|10_key_expiry.sh|	gpgkeys: HTTP fetch error 6: Could not resolve host: keys.gnupg.net; Unknown error
|centos:7|10_key_expiry.sh|	gpgkeys: HTTP fetch error 6: Could not resolve host: keys.gnupg.net; Unknown error
|centos:7|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|centos:8|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|debian:9|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-09-08
|debian:10|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-09-08
|fedora:31|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|fedora:32|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|fedora:33|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|fedora:34|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|ubuntu:18.04|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-09-08
|ubuntu:20.04|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-09-08
|ubuntu:20.10|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-09-08
|ubuntu:21.04|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-09-08
|opensuse/leap:15.1|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|opensuse/leap:15.2|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|opensuse/leap:15.3|10_key_expiry.sh|	<devel@s2.owncloud.com> expires: 2022-04-29
|centos:7|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|centos:8|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|debian:9|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|debian:10|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:31|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:32|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:33|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|fedora:34|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:18.04|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:20.04|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:20.10|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|ubuntu:21.04|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|opensuse/leap:15.1|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|opensuse/leap:15.2|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|opensuse/leap:15.3|15_wayland.sh|	Available: linuxfb, minimal, offscreen, vnc, wayland, xcb.
|centos:7|20_qttrans_de.sh|	OK
|centos:8|20_qttrans_de.sh|	OK
|debian:9|20_qttrans_de.sh|	OK
|debian:10|20_qttrans_de.sh|	OK
|fedora:31|20_qttrans_de.sh|	OK
|fedora:32|20_qttrans_de.sh|	OK
|fedora:33|20_qttrans_de.sh|	OK
|fedora:34|20_qttrans_de.sh|	OK
|ubuntu:18.04|20_qttrans_de.sh|	OK
|ubuntu:20.04|20_qttrans_de.sh|	OK
|ubuntu:20.10|20_qttrans_de.sh|	OK
|ubuntu:21.04|20_qttrans_de.sh|	OK
|opensuse/leap:15.1|20_qttrans_de.sh|	OK
|opensuse/leap:15.2|20_qttrans_de.sh|	OK
|opensuse/leap:15.3|20_qttrans_de.sh|	OK
|centos:7|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.0.2k-fips  26 Jan 2017
|centos:8|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1g FIPS  21 Apr 2020
|debian:9|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.0l  10 Sep 2019
|debian:10|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1d  10 Sep 2019
|fedora:31|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1g FIPS  21 Apr 2020
|fedora:32|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1k  FIPS 25 Mar 2021
|fedora:33|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1k  FIPS 25 Mar 2021
|fedora:34|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1k  FIPS 25 Mar 2021
|ubuntu:18.04|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1  11 Sep 2018
|ubuntu:20.04|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1f  31 Mar 2020
|ubuntu:20.10|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1f  31 Mar 2020
|ubuntu:21.04|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1j  16 Feb 2021
|opensuse/leap:15.1|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.0i-fips  14 Aug 2018
|opensuse/leap:15.2|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1d  10 Sep 2019
|opensuse/leap:15.3|30_openssl_vers.sh|	Libraries Qt 5.12.10, OpenSSL 1.1.1d  10 Sep 2019
|centos:7|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|centos:8|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|debian:9|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|debian:10|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|fedora:31|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|fedora:32|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|fedora:33|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|fedora:34|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|ubuntu:18.04|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|ubuntu:20.04|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|ubuntu:20.10|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|ubuntu:21.04|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|opensuse/leap:15.1|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|opensuse/leap:15.2|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst
|opensuse/leap:15.3|50_sync_excl.lst.sh|	392 /etc/ownCloud/sync-exclude.lst

</details>

Generated via client/linux-docker-install/run_tests.sh

----
