### ISSUE TITLE
Don't display "Synchronizing VirtualFiles with local folder" if vfs is enforced

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#8871]
I find the text we display in 
![image](https://user-images.githubusercontent.com/200626/128870106-a9848688-dfa3-4095-8165-8f3c922386ba.png)
![image](https://user-images.githubusercontent.com/200626/128870234-d602113d-d9e0-42b0-a3f8-9dd3875f55d4.png)

rather pointless.

Yes our desktop sync client does sync...
Displaying the local folder name is also not that use full as we usually refer to the folder as "user@server" at least on Windows
![image](https://user-images.githubusercontent.com/200626/128870424-214d5334-95ac-4f5b-b5be-5d7f658e70c1.png)

As we had complains about the text I'd like to remove the text all together.
However the delegate looks broken without that text.

https://github.com/owncloud/client/pull/8760

**Comment by michaelstingl** [comment]
I'd only remove it with branding option "VFS enforced" AND "single-folder". Multi-folder would need an alternative text.

**Comment by TheOneRing** [comment]
I think it has nothing to do with vfs.
The information of the following image is just useless.
![image](https://user-images.githubusercontent.com/200626/128871591-e7c05312-601a-4de0-a016-48ddacc782b4.png)

**Comment by dragotin** [comment]
I disagree. This display needs to provide the following information for me:

- The remote folder name
- the local folder name
- VFS or data sync.

In an ideal world I can open the explorer by clicking on the local folder.

**Comment by TheOneRing** [comment]
But the local folder name does not provide any useful information, the path would, but displaying the path here would overcrowd the ui.

Any how, what about "Local folder:  testpilotcloud" (optionally as a button or link) instead of "Synchronizing with local folder"

**Comment by dragotin** [comment]
yes, _Local folder: testpilotcloud_ sounds reasonable.  Or even... 

![ksnip_20210810-184522](https://user-images.githubusercontent.com/1070214/128900092-edbd4f3c-0fdd-415b-855a-9256cf25dd68.png)
(scribble...)

**Comment by tbsbdr** [comment]
> "Local folder: testpilotcloud" (optionally as a button or link) instead of "Synchronizing with local folder"

would also exactly do it like that.
