### ISSUE TITLE
Error while reading directory

### ISSUE THREAD

**Issue by elmeto** [owncloud/client#8876]
### Expected behaviour
Mac OS Client syncs files & folders

### Actual behaviour
On client only, I'm getting an error message 'Error while reading directory /Volumes/[...path]

### Steps to reproduce
1. 
2. 
3. 

### Server configuration
Operating system:
macOS 10.13

Web server:
Apache

Database:
MySQL

PHP version:
7
ownCloud version:
10
Storage backend (external storage):
RAID

### Client configuration
Client version:2.8.2

Operating system: macOS 10.15.7

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: 
08-09 16:20:43:418 [ info sync.discovery ]:	Processing "[Folder Level 2] / [Folder Level 3] / [Folder Level 4] / [Folder Level 5] / [Folder Level 6] / [Folder Level 7] / [Folder Level 8] /18 Track 18.wma" | valid: true/true/db | mtime: 1208462433/1208462433/0 | size: 3495668/3495668/0 | etag: "079dbfd3aa03afc2f8c01b81be0265cb"//"" | checksum: "SHA1:105638743dbb0bd6c4aeac962e60dcb2286f71d2"//"" | perm: 0x60000128cdc8//0x10c06a028 | fileid: "01393040ocd0jxx7gpk9"//"" | inode: 10376557/10376557/ | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile

08-09 16:20:43:418 [ info sync.discovery ]:	Discovered "[Folder Level 2] / [Folder Level 3] / [Folder Level 4] / [Folder Level 5] / [Folder Level 6] / [Folder Level 7] / [Folder Level 8] /18 Track 18.wma" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeFile

08-09 16:20:43:418 [ info sync.discovery ]:	Processing "[Folder Level 2] / [Folder Level 3] / [Folder Level 4] / [Folder Level 5] / [Folder Level 6] / [Folder Level 7] / [Folder Level 8] /19 Track 19.wma" | valid: true/true/db | mtime: 1208462433/1208462433/0 | size: 3764588/3764588/0 | etag: "bfb6d7ac0913498dbe378b8bbb5e4422"//"" | checksum: "SHA1:f83147b28363469d5ceb6f0b940596c54a0a91f7"//"" | perm: 0x60000128cfa8//0x10c06a028 | fileid: "01393041ocd0jxx7gpk9"//"" | inode: 10376560/10376560/ | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile

08-09 16:20:43:418 [ info sync.discovery ]:	Discovered "[Folder Level 2] / [Folder Level 3] / [Folder Level 4] / [Folder Level 5] / [Folder Level 6] / [Folder Level 7] / [Folder Level 8] /19 Track 19.wma" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeFile

08-09 16:20:43:418 [ info sync.discovery ]:	Processing "[Folder Level 2] / [Folder Level 3] / [Folder Level 4] / [Folder Level 5] / [Folder Level 6] / [Folder Level 7] / [Folder Level 8] /20 Track 20.wma" | valid: true/true/db | mtime: 1208462433/1208462433/0 | size: 3483716/3483716/0 | etag: "e4dc22d42a2703761ca5d122cba7a7fc"//"" | checksum: "SHA1:fddc9ef7758aa394e13ca38c5218b88ebbc85e96"//"" | perm: 0x60000128cdc8//0x10c06a028 | fileid: "01393042ocd0jxx7gpk9"//"" | inode: 10376563/10376563/ | type: CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile/CSyncEnums::ItemTypeFile

08-09 16:20:43:418 [ info sync.discovery ]:	Discovered "[Folder Level 2] / [Folder Level 3] / [Folder Level 4] / [Folder Level 5] / [Folder Level 6] / [Folder Level 7] / [Folder Level 8] / 20 Track 20.wma" CSyncEnums::CSYNC_INSTRUCTION_NONE OCC::SyncFileItem::None CSyncEnums::ItemTypeFile

08-09 16:20:43:421 [ info sync.discovery ]:	STARTING "[Folder Level 2] / [Folder Level 3] / [Folder Level 4] / [Folder Level 5] / [Folder Level 6] /Unknown Artist" OCC::ProcessDirectoryJob::ParentNotChanged "[Folder Level 2] / [Folder Level 3] / [Folder Level 4] / [Folder Level 5] / [Folder Level 6] /Unknown Artist" OCC::ProcessDirectoryJob::NormalQuery

08-09 16:20:43:421 [ info sync.discovery ]:	STARTING "[Folder Level 2] / [Folder Level 3] / [Folder Level 4] / [Folder Level 5] / [Folder Level 6] /Various Artists" OCC::ProcessDirectoryJob::ParentNotChanged "[Folder Level 2] / [Folder Level 3] / [Folder Level 4] / [Folder Level 5] / [Folder Level 6] /Various Artists" OCC::ProcessDirectoryJob::NormalQuery

08-09 16:20:43:484 [ warning sync.discovery ]:	readdir failed for file in  "/Volumes/ [RAID volume name] / [Folder Level 1] / [Folder Level 2] / [Folder Level 3] / [Folder Level 4] / [Folder Level 5] / [Folder Level 6] / Playlists"  - errno:  5

08-09 16:20:43:567 [ warning sync.discovery ]:	readdir failed for file in  "/Volumes/ [RAID volume name] / [Folder Level 1] / [Folder Level 2] / [Folder Level 3] / [Folder Level 4] / [Folder Level 5] / [Folder Level 6] /Royal Liverpool Philharmonic Choir & Orchestra"  - errno:  5

2. Web server error log:
3[Mon Aug 09 00:06:15.655836 2021] [ssl:warn] [pid 1205] AH01909: [IP (Local)]:10:0 server certificate does NOT include an ID which matches the server name
[Mon Aug 09 00:06:15.657627 2021] [mpm_prefork:notice] [pid 1205] AH00163: Apache/2.4.29 (Ubuntu) OpenSSL/1.1.1 configured -- resuming normal operations
[Mon Aug 09 00:06:15.657675 2021] [core:notice] [pid 1205] AH00094: Command line: '/usr/sbin/apache2'
[Mon Aug 09 00:06:15.669148 2021] [:error] [pid 83861] avahi_entry_group_add_service_strlst("[LINUX USER]") failed: Local name collision

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by TheOneRing** [comment]
That sounds like there is something going on with your file system, maybe you check check the disks integrity.
https://askubuntu.com/a/65835

**Comment by elmeto** [comment]
Thank very much, I think you're right, the Mac's disk utility First Aid failed
