### ISSUE TITLE
Adding a sync connection with a network location displays a write permission error message

### ISSUE THREAD

**Issue by theycallmelaurenz** [owncloud/client#8896]
### Expected behaviour
Adding a sync connection and choosing a mapped network location as the "local" folder should be possible and not show an error message.

### Actual behaviour
Instead, an error message `Warning: You have no permission to write to the selected folder!` is displayed, and the **Next** button is greyed out.

### Steps to reproduce
1. Map a network location Windows Explorer
2. Open the settings window of the desktop app
3. Add a new sync connection
4. As the local folder, choose the network drive you mapped earlier
5. Notice that the sync client refuses the location

### Server configuration
Operating system: n/a

Web server: n/a

Database: n/a

PHP version: n/a

ownCloud version: n/a

Storage backend (external storage): n/a

### Client configuration
Client version: 2.8.2

Operating system: Windows 10 Version 21H1 (OS Build 19043. 1110)

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): n/a

Client package (From ownCloud or distro) (Linux only): n/a

Installation path of client: C:\Program Files\ownCloud\

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

1. Client logfile: [log.txt](https://github.com/owncloud/client/files/6977687/log.txt)

2. Web server error log: n/a

3. Server logfile: ownCloud log (data/owncloud.log): n/a

**Comment by michaelstingl** [comment]
Upcoming 2.9 release should behave better. You could test-drive the pre-release builds:
https://download.owncloud.com/desktop/ownCloud/daily/2.9/win/?sort=time&order=desc

We'd love to hear your feedback!

Note: Virtual files doesn't work on a network drive due to a limitation of the system API we're using, you need to sync the full data. Local changes can't be detected in real time because of lacking file system events. You need to wait for the next full local discovery. (default 1/h, but you can tweak it)

**Comment by TheOneRing** [comment]
Hm with vfs you should get a error that virtual files are not supported on network drives.
If you are not using virtual files, I assume you need to fiddle with the permissions of the share, its not always easy to get them right.

On a side note, the client mirrors a server directory, so what is the point in now storing the files on an other server (network share).

**Comment by theycallmelaurenz** [comment]
@michaelstingl when connect to the ownCloud demo server using the pre-release version of 2.9, and try to add a new sync connection with a WebDAV mounted network drive as the local folder, it gives me the same error message.

**Comment by theycallmelaurenz** [comment]
@TheOneRing as far as I am aware, I do not use virtual files. I don't think the share permissions are the problem, I noticed this error message after switching from Nextcloud Client 2.6.5 to ownCloud Desktop App 2.8.2.

As for your side note, I do feel that setting network shares as a local folder isn't the Desktop App's intended purpose, and I am aware that this may cause problems when the mapped network location doesn’t automatically reconnect after the computer going to sleep or a reboot. But this looks broken and some of our customers do work like this.

**Comment by michaelstingl** [comment]
WebDAV mounts on Windows are really flaky. Please use regular Windows network share.

**Comment by jnweiger** [comment]
Network shares should actually work as a home of your sync folder. But I have to say, I cannot really say what made it work when I tested that.
I had quite some struggle with Windows showing me the readonly attribute in the properties, while at the same time windows could write, rename and delete.
This situation (in my case at least) probably confused the client for a while.

**Comment by gabi18** [comment]
> When we fixed the write access check you and gabi also had issues setting up the permissions correctly.
What I did to get write permissions: setting all permissions for all users on right click menu 'Properties' 'Security' tab 
> It is very easy to have one flag wrong.
> Also it might not be possible to directly use the shared folder itself but we require a sub folder as we need to be able to do changes to the folder itself.

**Comment by carwe** [comment]
encoutered this too, while trying to connect a 2.7, 2.11, 3.2.1 and 4.2 client to a network share which was provided by samba on debian 12

had to manually grant full access for "everybody" to the directory, despite my regular user could fully access the directory already

seems the OC client does some guesswork by interpreting the ACL instead just trying it
