### ISSUE TITLE
[QA] Adjust existing GUI tests for 2.9

### ISSUE THREAD

**Issue by swoichha** [owncloud/client#8897]
### Description
As `2.9` is in-progress some of the existing tests are failing due to change in UI elements.

For example:
test for adding new account fails because it can not find the account connect button as it has been changed.

### To-Do:
Fix the connect button object to make it work as per the new design and code changes.

**Comment by TheOneRing** [comment]
Before fixing it, could you specify the breaking change, it can always be a bug :)

**Comment by swoichha** [comment]
After https://github.com/owncloud/client/pull/8879 has been merged. Now we have Finish button instead of Connect. Also, the object name for the button has been changed from `"name": "__qt__passive_wizardbutton1"` to `"name": "qt_wizard_finish"`. So, we need to fix that.

**Comment by swoichha** [comment]
@TheOneRing  Another thing that I found while fixing this issue was that we cannot use same `client_sync_path`. Previously when we added two users to client then they both had same sync path i.e. `/tmp/client-bdd` but now we need to have separate sync folder else the test fails with error like this

![error](https://user-images.githubusercontent.com/17021686/129344960-e9cb5724-e948-4f04-874a-80828f415ded.jpeg)

Is this suppose to happen or is it an error?

**Comment by TheOneRing** [comment]
> 
> 
> @TheOneRing Another thing that I found while fixing this issue was that we cannot use same `client_sync_path`. Previously when we added two users to client then they both had same sync path i.e. `/tmp/client-bdd` but now we need to have separate sync folder else the test fails with error like this
> 
> ![error](https://user-images.githubusercontent.com/17021686/129344960-e9cb5724-e948-4f04-874a-80828f415ded.jpeg)
> 
> Is this suppose to happen or is it an error?

Sync root sharing was removed as it could cause data loss when virtual files where involved.

**Comment by TheOneRing** [comment]
> 
> 
> After #8879 has been merged. Now we have Finish button instead of Connect. Also, the object name for the button has been changed from `"name": "__qt__passive_wizardbutton1"` to `"name": "qt_wizard_finish"`. So, we need to fix that.

Yes it is now using the finish button as I removed a dead page that was available after the advanced setup page.
The finish button how ever should still have "Connect" as text.

**Comment by swoichha** [comment]
> Sync root sharing was removed as it could cause data loss when virtual files where involved.
Okay. I'll make some changes so that it will use two different directory for syncing two different users.

**Comment by swoichha** [comment]
https://github.com/owncloud/client/pull/8898 has been merged so closing this issue now.
