### ISSUE TITLE
[CI] Run all GUI test in a single pipeline

### ISSUE THREAD

**Issue by swoichha** [owncloud/client#8899]
### Description
Currently, we run GUI smoke test in one pipeline and remaining tests in another pipeline. GUI tests is about 25-30 mins. Once the smoke test pipeline is completed then only the other tests will start to run. While doing so each pipeline builds client separately.

We need to find a way to save a significant amount of build time so that the client is build only once. 

### Possible-Fix:
- Maybe we can combine smoke and non-smoke tests in a single pipeline

**Comment by TheOneRing** [comment]
I assume combining them in a single pipeline and just fail hard if the smoke tests fail would be perfect.

**Comment by swoichha** [comment]
Fixed in https://github.com/owncloud/client/pull/8987 so closing this issue.
