### ISSUE TITLE
[QA] 2.9.0 "some files were ignored"

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8909]
Seen with client 2.9.0-beta1 (build 4915) on Mint Linux

* Connect to a server with a large tree. 
* Wait until sync is done.
* After the sync is done, the status icon shows a blue circle with an 'i'
* The mouse over text has contradicting texts:
  * "Sync Success" and
  * "some files were ignored"

![image](https://user-images.githubusercontent.com/1108546/129796417-b342e3d9-13fd-49f0-8cf3-27a38fa6b682.png)

Expected behaviour: 
- Either the sync succeeds, then a green checkmark is shown, or
- or the sync status is not successful.

**Comment by jnweiger** [comment]
In this state, the tray icon also shows the 'i' on blue background.
Subsequent sync activity is no longer shown with the blue circling arrows in the tray icon. The 'i' on blue simply remains as if there were no sync activiy.

**Comment by gabi18** [comment]
Confirmed with client 2.9.0-beta1 (build 4915) on openSUSE 15.2.

The "i" icon is shown 
![Screenshot_20210818_073303](https://user-images.githubusercontent.com/75983861/129843485-655e36c2-0ee9-4737-8758-33ce197fe8e8.png)

the 'Not Synced' tab shows the reason
![info_not_synced](https://user-images.githubusercontent.com/75983861/129843570-916d4a87-524c-4c57-b666-587b3d682290.png)

``` 
20210818_0731_owncloud.log.4:08-18 07:31:08:676 [ info gui.application ]:       Sync state changed for folder  "https://cloud.owncloud.com/remote.php/dav/files/gmohr/INFOS_all" :  "Success, some files were ignored."
```
[20210818_0731_owncloud.log.4.gz](https://github.com/owncloud/client/files/7004789/20210818_0731_owncloud.log.4.gz)

After a new file "TextFileNew.txt" is created the icon turns to green checkmark
![info_green_checkmark](https://user-images.githubusercontent.com/75983861/129844680-973831fb-288c-4bb9-b045-cd3d5632767d.png)

[20210818_0738_owncloud.log.0.gz](https://github.com/owncloud/client/files/7004822/20210818_0738_owncloud.log.0.gz)

**Comment by TheOneRing** [comment]
Not a bug, its feature.

Hidden files won't cause the state, invalid file names will.
The other case are blacklisted files, so if a file fails multiple times we will no longer display a green icon and pretend everything is fine.

**Comment by jnweiger** [comment]
This is a regression. 2.8.2 succeeds to a green checkmark icon wit the same files.

**Comment by TheOneRing** [comment]
> 
> 
> Not a bug, its feature.
> 
> Hidden files won't cause the state, invalid file names will.
> The other case are blacklisted files, so if a file fails multiple times we will no longer display a green icon and pretend everything is fine.

**Comment by michaelstingl** [comment]
> Not a bug, its feature.

Intentional product change. But expectation would be to see the new errors in the "not listed" tab. Please open new issue if this isn't the case.

**Comment by jnweiger** [comment]
I also confirm https://github.com/owncloud/client/issues/8909#issuecomment-900831484
Linux Mint 20.1 and testpilotcloud-2.9.0-beta1.4914.AppImage :
The 'i' that was initially caused by symlinks, disappears when doing a force sync.

**Comment by TheOneRing** [comment]
So the initial sync displays a problem state when sym links are found and the second not?
And it is not related to that file without write permissions you had?

**Comment by jnweiger** [comment]
No write permission problems involved.

Reproducer:
* connect Linux client to server.
* Wait for initial sync
* Add a symlink. The blue circle i appears (with contradicting mouse over "sync success") and the activity log reports the symlink as not synced.
* do force sync
* sometimes, the green checkmark icon appears (with mouse over "sync success") and remains, but the activity log again reports the symlink as not synced.
* if you get the blue circle i again, try force sync again. eventually the green checkmark appears.
