### ISSUE TITLE
[QA] Resizing of the columns in 'Activity' views doesn't work properly

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#8910]
Seen with 2.9.0beta1 (build 4915) on openSUSE 15.2

The resize behaviour of the in 'Server Activity', 'Sync Protocol' and 'Not Synced' tab is strange.
Changing the width of the last column 'Time' isn't possible directly but only when changing the size of the first column.

Size of 'Time' column doesn't change:
![time_column](https://user-images.githubusercontent.com/75983861/129852348-583af3f0-6d5a-4597-856b-ad46058eb9f7.png)

Width of 'Time' changes when changing 'Action'
![action_column](https://user-images.githubusercontent.com/75983861/129852666-0c882758-4217-4dbc-ac78-8e8036ddf915.png)

There was already an issue about column size before:
https://github.com/owncloud/client/issues/8660

**Comment by michaelstingl** [comment]
You can resize the time-column, but it's not intuitive:
![CleanShot 2021-08-18 at 09 08 05](https://user-images.githubusercontent.com/214010/129853673-30586712-4231-461d-8f31-5d13f9084afe.gif)

**Comment by gabi18** [comment]
I haven't tried that. Indeed, I'm also able to resize 'Time'.

**Comment by TheOneRing** [comment]
The code responsible for the behaviour can be fund in https://github.com/owncloud/client/blob/master/src/gui/models/expandingheaderview.cpp#L33

**Comment by erikjv** [comment]
What should the behavior be? That if you resize one column, it doesn't change the sizes of the other columns?

**Comment by michaelstingl** [comment]
Maybe move the separator line between Account and Time, both should change, but all other keep their width.

**Comment by michaelstingl** [comment]
macOS Finder cheats with an empty column on the right:

![CleanShot 2021-08-18 at 13 01 23](https://user-images.githubusercontent.com/214010/129887183-3fde2ed4-cd21-4b69-8e19-0484099b2918.gif)

**Comment by jnweiger** [comment]
> What should the behavior be? That if you resize one column, it doesn't change the sizes of the other columns?

* The behaviour as show in @michaelstingl's post looks good.
* In general: dragging a column separator should change the width of the column directly left to it. Columns on the right side move in position, but do not change size. Nothing else changes.
* The last column is hard to change, if you cannot grab the column separator to its right. That may need special handling.

On Linux
* I see multiple columns changing size, when I drag one separator, that is cunter-intuitive.
* I don't seem to have a way to change the order of the columns. Wasn't that possible in the past?

**Comment by TheOneRing** [comment]
Qt only offers the possibility to make the last column fill up the remaining space, not very useful besides if we want to put a lot of focus on the Time column.

And alternative would be fixed sized columns, but they provide an even worse ux.
Of course we can also use a random width and just display a scroll area also not nice...

**Comment by jnweiger** [comment]
As seen in the screenshots of https://github.com/owncloud/client/issues/8660 there is already a scrollbar. Thus the table can expand beyond the window size. The concept of "remaining space" does not apply, when the table can expand as needed.

**Comment by TheOneRing** [comment]
The scroll bar only pops up when you fiddle for a long time with the widget, normally it should not be visible.

**Comment by erikjv** [comment]
@jnweiger that's the default OS behavior, right? If so, why do we have a custom code to have the current behavior? @michaelstingl Do you happen to know?

**Comment by TheOneRing** [comment]
It resizes the "interesting" column which might not be the first one

**Comment by jnweiger** [comment]
Not fixed in beta2

**Comment by TheOneRing** [comment]
> 
> 
> Not fixed in beta2

Specify

**Comment by TheOneRing** [comment]
I forgot to merge https://github.com/owncloud/client/pull/8914 🤦‍♀️
