### ISSUE TITLE
Moving files causes delete and re-upload with second Folder Sync Conncetion

### ISSUE THREAD

**Issue by Darkexy** [owncloud/client#8913]
### Expected behaviour
In Windows explorer moving a file or folder within a synced directory should be done by an move operation.

### Actual behaviour
In one account I have two Folder Sync Conncetions going two different HDDs on my Desktop. The first is older, syncing the root, but not every folder within it. The second is a few days old, syncing one folder within the root to an other hdd, since I ran out of space.

Moving files and folders in the first Folder Sync works totally fine, according to the log.

Moving files and folders in the second Folder Sync causes delete and re-upload unfortunately. 

### Steps to reproduce
As described and seen in the log, the folder sync on D:/OwnCloud behaves normally, while the folder sync on X: causes a Delete and Re-Upload instead of Move.

![Issue](https://user-images.githubusercontent.com/46348738/129888190-1893d616-3fcb-47a8-aec7-7429b4dd581f.JPG)

### Server configuration
Operating system: Raspberry Pi OS on Raspi 4

Web server: Apache  2.4.38-3+deb10u5 armhf 

Database: mariadb-server-10.3

PHP version: php7.3/stable,now 7.3.29-1~deb10u1

ownCloud version: latest stable (10.8.0.4)

Storage backend (external storage): External 4TB HDDs

### Client configuration
Client version: 2.8.2 (build 4246)

Operating system: Windows 10

OS language: German

Installation path of client: C:\Program Files\ownCloud

NOTE: I found a simular Issue here, but it seems this is fixed: https://github.com/owncloud/client/issues/7838

**Comment by TheOneRing** [comment]
Sync folder connections are completely independent they just share an account but don't know about the files of other connections.

Detecting changes across sync connections and disks is not possible.

**Comment by Darkexy** [comment]
That is not what I asked for. I just wanted to illustrate that on the First Connection Moving Files and Folders worked like it should, while on the second Connection it doensn't.

To set it straight:

I created a File and a Folder to test on both, the first and on the second conncetion. And I moved the testfile and folder from the first connection only within the first connection and the second testfile and folder only within the second conncetion.

On the first connection it makes the move operation, and the second it doesn't. So there have to be a problem.

**Comment by TheOneRing** [comment]
Sorry I got your report wrong.
Can you tell me more about X: I assume you are not using virtual files (those are not supported on a drive root)

Is X: normal HDD, are both drives using NTFS?

Besides that I already have an idea what could cause the issue. The sync is using X: without any slash so our code comparing the file locations could have issues with this...

**Comment by Darkexy** [comment]
No problem, havn't thought about that it could get read wrong.^^

I dont have virtal files, I sync all the the drive. X is an external USB 3.0 HDD. X: uses exFAT, D: uses NTFS.

**Comment by TheOneRing** [comment]
So I did some research:
We are using the file id to detect file moves.
On FAT however the id might change:

>In the FAT file system, the file ID is generated from the first cluster of the containing directory and the byte offset within the directory of the entry for the file. Some defragmentation products change this byte offset. (Windows in-box defragmentation does not.) Thus, a FAT file ID can change over time. Renaming a file in the FAT file system can also change the file ID, but only if the new file name is longer than the old one.

https://docs.microsoft.com/en-us/windows/win32/api/fileapi/ns-fileapi-by_handle_file_information

**Comment by Darkexy** [comment]
Okay, that means I need to format it to NTFS and it should work propably?

**Comment by TheOneRing** [comment]
Yes

**Comment by Darkexy** [comment]
Okay. Than it seems like I have no choice. :)

Since I need to redownload all the files, I've an other question/problem. I recognized, that the download speed dropped most of the time to under 2MB/s, while downloading the files to X:. My local netwerk uses Gigabit-Ethernet, which makes me suspicious. Is it possible, that this exFAT thing could effect the downloadspeed too?

**Comment by TheOneRing** [comment]
I'd rather blame the speed on the raspberry pi :)

**Comment by Darkexy** [comment]
The Raspi4 ha an Gigabit-Ethernet-Port, too. This si the first time that the speed is that slow. Normaly it does load with about 30-40 MB/s. And it does upload with about 20-40 MB/s. Only with this Connection it started to vary a lot with the download. It starts super fast, than go down to super slow. And from time to time it went up to 20 MB/s for a few minutes and then it drops again.

**Comment by Darkexy** [comment]
Can verify, that format in NTFS works!

**Comment by TheOneRing** [comment]
Thx,  we will update our documentation and maybe also warn when using fat
