### ISSUE TITLE
[QA] Link in modified "About" window does not work

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8920]
Seen in testpilotcloud-2.9.0-beta1.4914.AppImage on Linux Mint 20.1
* Open Settings, -> click About
* A window with version number and some text opens.
* In case the theme has the modified about option, there is a badly formatted URL
![image](https://user-images.githubusercontent.com/1108546/130056291-9544ae31-d404-4db5-aff9-939a3a0b4bd5.png)

----

The testpilot theme has

![image](https://user-images.githubusercontent.com/1108546/130056123-be35ed8b-8152-49f1-88c7-938c9b9b4b71.png)

![image](https://user-images.githubusercontent.com/1108546/130056094-98417595-7bea-49bc-8177-786501852c5c.png)

The theme.json file corresponding to these settings has:
![image](https://user-images.githubusercontent.com/1108546/130056066-73e1442b-c47b-4c0d-9962-72363226ee32.png)

**Comment by gabi18** [comment]
Confirmed fixed on Windows 10 with client 2.9.1rc1
