### ISSUE TITLE
[QA] activity -> not synced list fills up with complaints about symlinks

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8922]
Seen with 2.9.0 (and before -- not a regression) on Linux

* connect client to server, wait for initial sync.
* inside the client's sync folder, create a subfolder `symlinks` with 5 symbolic links, e.g. like this
```
$ ls -la symlinks
total 28
drwxrwxr-x 2 testy testy 4096 Aug 19 12:59 ./
drwxrwxr-x 8 testy testy 4096 Aug 19 11:51 ../
lrwxrwxrwx 1 testy testy    2 Aug 18 14:33 ba1 -> fo
lrwxrwxrwx 1 testy testy    2 Aug 18 14:33 ba2 -> fo
lrwxrwxrwx 1 testy testy    2 Aug 18 14:33 ba3 -> fo
lrwxrwxrwx 1 testy testy    2 Aug 18 14:33 ba4 -> fo
lrwxrwxrwx 1 testy testy    2 Aug 18 14:33 ba5 -> fo
```

* on the next sync, the client lists them in the activity -> not synced list:
![image](https://user-images.githubusercontent.com/1108546/130058333-f0da8a3a-c9e1-49e2-8140-f7bf0a91b74a.png)

**Comment by TheOneRing** [comment]
Yes we don't syc symlinks so what?
