### ISSUE TITLE
[QA] Win VFS status icon only set correctly after sync is forced

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#8926]
Seen with 2.9.0beta1 (build 4915) on Win10 20H2

Steps to reproduce:
- start client and open folder in Explorer
- create a new folder in syncroot
- press "Enter" twice, remain inside the newly created folder for more than 30s

Result: 
- the new folder is created on the server, no entry in 'Sync Protocol' tab
- a message "Setting file status due to lock failed" appears in 'Not Synced' tab
- the status icon remains 'spinning' for the new folder
- the status icon doesn't change when leaving the folder after longer than 30s
- the message in 'Not Synced' tab disappears
- after a 'Force Sync' the icon is set correctly to cloud icon
- 'Sync Protocol' tab shows message "Downloaded" "New folder" 
![download](https://user-images.githubusercontent.com/75983861/130091395-d0b6b20c-76ef-43f2-ae51-02024c255dad.PNG)

Expected result:
- Synced tab should show uploaded, spinning icon should change to cloud icon when folder is uploaded

[20210819_0737_owncloud.log.1.gz](https://github.com/owncloud/client/files/7015313/20210819_0737_owncloud.log.1.gz)
[20210819_0737_owncloud.log.0.gz](https://github.com/owncloud/client/files/7015314/20210819_0737_owncloud.log.0.gz)
[20210819_0730_owncloud.log.0.gz](https://github.com/owncloud/client/files/7015315/20210819_0730_owncloud.log.0.gz)

**Comment by jnweiger** [comment]
Restested with 2.9.0 RC1 on both, win10_20h2 and win10_21h1

*  after a few seconds the circling arrow disappear, as expected. OK.
*  cannot reproduce

**Comment by gabi18** [comment]
Problem:
'Not Synced' tab shows the folder and notification says not synced - but the folder was synced to the server already

![notification](https://user-images.githubusercontent.com/75983861/136526760-d432fa35-b889-44a2-bfea-036a6f580bed.png)

**Comment by TheOneRing** [comment]
Thx for testing thats the now expected behaviour, however it should also work with out a force sync.

**Comment by gabi18** [comment]
Confirmed fixed with ownCloud-2.10.0-rc3.6417.x64.msi (VFS ON).
- 'Sync Protocol' shows Uploaded NewFolder
- icon for NewFolder changes correctly to cloud icon (despite remaining more than 30 seconds inside the folder and without a Force sync)
