### ISSUE TITLE
[QA] folder clash after resolving folder clash

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8929]
Seen with client 2.9.0-beta2 on windows10

* connect client to server
* at the server create a folder `gallery` containing file `foo`
* wait for sync. client has gallery with foo.
* at the server create a folder `Gallery` containing file `bar`
* wait for sync.  A "Not synced" issue is logged: `Can not create local folder C:\Users\Administrator\testpilotcloud\Gallery because of a local file name clash with C:\Users\Administrator\testpilotcloud\gallery` OK
* at the server delete folder `gallery`
* wait for sync. The client again reports the same "Not synced" issue. It persists, although the lower case version is deleted at the server.

Expected behaviour: The delete propagates, then the uppercase version of `Gallery` gets synced to the client.

**Comment by TheOneRing** [comment]
In the described scenario we still have a case clash locally.
We have a folder called `gallery` and the server has a file called `Gallery` merging the folders would not be expected behaviour as it would be quite the same as merging the two folders while the clash existed on the server.
