### ISSUE TITLE
[QA] Folder without subfolder show the arrow icon

### ISSUE THREAD

**Issue by swoichha** [owncloud/client#8935]
Seen with client 2.9.0-beta2 on Windows 10 (Enterprise Evaluation) version 21H1 (OS build 19043.1165) 
-  Start to setup the oC Desktop app
-  Fill in server, user and password
-  In the new window select "Synchronize everything from server"  and select/unselect different kinds of folder with and without sub-folder. Wait until everything is sync.

## Actual
- Click on a folder with and without sub-folder the arrows is displayed.
- When minimizing the directory tree and opening the it again, the arrow for folder without sub-folder disappears.

## Expected
- Folder without sub-folder should not have arrows.

**Comment by saw-jan** [comment]
Tested on `ownCloud 6.0.0.13589-daily20240328 [32670a]`

Expectation: arrow should disappear from empty folder :question:

![Screenshot from 2024-03-28 15-08-01](https://github.com/owncloud/client/assets/52366632/e4495a6f-ea69-4a23-b3c4-32d4a88cd97c)

@TheOneRing the expectation in this issue does not met. Will there be a fix to meet the expectation or arrow in the empty folders are expected (arrow will not disappear)?

**Comment by erikjv** [comment]
We should emit a row/data changed signal and indicate that there are no children, which should make the arrow disappear.

**Comment by ishabaral** [comment]
Tested with : ` ownCloud-6.0.0.14906-daily20241029 [b056cf]`

![Screenshot from 2024-10-29 16-01-48](https://github.com/user-attachments/assets/471ec499-71cb-43d9-a04c-32dcff27d5cc)
