### ISSUE TITLE
[QA] Sharing dialog has no expiry option for user shares

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8937]
Seen with owncloud-client 2.9.0-beta3 on Linux Mint 20.2 and Windows 10 (connected to server 10.8.0):

* At the webserver the options are (file / folder)
![image](https://user-images.githubusercontent.com/1108546/130590936-d0dc678f-5dd0-4038-abe2-ee8478434fc2.png)
![image](https://user-images.githubusercontent.com/1108546/130592136-9c75ff9a-618a-4820-8121-f926211dbf4c.png)

* At the client, the options are (file / folder)
![image](https://user-images.githubusercontent.com/1108546/130591216-ae1fd7f5-3f8c-40f2-99da-10de64fddd6f.png)
![image](https://user-images.githubusercontent.com/1108546/130591963-b2543dd3-3658-496c-b4d2-87be7972d21c.png)

Expected behaviour: Client offers the same option as server: Expiration date option is currently missing in both file and folder share dialogs.

**Comment by jnweiger** [comment]
When sharing with public link, the client offers setting an expiration date (and a pasword) -- which is in sync with the server.

**Comment by michaelstingl** [comment]
Known limitation. No fix in 2.9.

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/pull/7564
Ceterum censeo dialogem dividere esse delendam (or something like this)

**Comment by TheOneRing** [comment]
The sharing dialog is considered deprecated
