### ISSUE TITLE
[QA] internal LDAP user id shows up when resharing fails

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8941]
Seen with testpilotcloud client 2.9.0-beta3 running on Win10

* LDAP user shares a file with admin with default permissions (including allow share)
* admin connects with desktop client and right clicks the file in explorer to access the testpilotcloud sharing dialog
* while that dialog is open, the ldap user removes the "allow share" permission.
* admin enters a third user in the sharing dialog. An error occurs. OK.
* The error message has the internal ldap user id. BAD
![image](https://user-images.githubusercontent.com/1108546/130625803-d1f9a3f7-7fd7-4ee5-88b6-840383627f29.png)

Expected behaviour, the error message uses the username of the ldap user.
This is server related. Same effect when attempting to reshare on the Web UI.

**Comment by michaelstingl** [comment]
This is the path of the storage location on the server. We should only data starting in account root. (`/Portugal (1).jpg` in this case). Technical parent path segments have no value for the end user.

**Comment by jnweiger** [comment]
Reproduced in testpilotcloudclient 2.10.0 RC3
![image](https://user-images.githubusercontent.com/1108546/149090940-e44a4a4a-80ae-49a2-9596-05d182b78667.png)

**Comment by TheOneRing** [comment]
Won't fix
