### ISSUE TITLE
[QA] OIDC Kopano expects localhost instead 127.0.0.1

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8968]
Seen with testpilotcloud-client 2.9.0-beta3 on Linux Mint, with server 10.8.0 and openidconnect 2.0.0 using kopano idp.

The client does a roundtrip via firefox, the redirect URL uses 127.0.0.1 instead of localhost. But the client_id matches the static 'ownClod desktop app' from our identifier-registration.yml

https://konnect-oidc-2-0-0-20210830.jw-qa.owncloud.works/signin/v1/chooseaccount?client_id=xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69&code_challenge=WTv6x-IN-mzsKOkkgmLve8Z-nLufTnOi4XTSkDNV-7M&code_challenge_method=S256&flow=oidc&login_hint=aaliyah_abernathy&prompt=select_account+consent&redirect_uri=http%3A%2F%2F127.0.0.1%3A35287&response_type=code&scope=openid+offline_access+email+profile&state=mCjspJiDGFxTm8PpQjfpbMGyxVyzqiUpbG_KVUrsQsk%3D&user=aaliyah_abernathy

The client logfile says:
```
08-30 14:36:09:364 [ info sync.httplogger ]:    "ad72d963-fd1e-48df-8ee2-8d74d247c768: Request: POST https://konnect-oidc-2-0-0-20210830.jw-qa.owncloud.works/konnect/v1/register Header: { Content-Type: application/json, User-Agent: Mozilla/5.0 (Linux) mirall/2.9.0beta3 (build 5019) (testpilotcloud, linuxmint-5.4.0-81-generic ClientArchitecture: x86_64 OsArchitecture: x86_64), Accept: */*, X-Request-ID: ad72d963-fd1e-48df-8ee2-8d74d247c768, Original-Request-ID: ad72d963-fd1e-48df-8ee2-8d74d247c768, Content-Length: 224, } Data: [{\n    \"application_type\": \"native\",\n    \"client_name\": \"ownCloud Testpilot Edition 2.9.0beta3 (build 5019)\",\n    \"redirect_uris\": [\n        \"http://127.0.0.1\"\n    ],\n    \"token_endpoint_auth_method\": \"client_secret_basic\"\n}\n]"
08-30 14:36:09:364 [ info sync.networkjob ]:    OCC::SimpleNetworkJob("https://konnect-oidc-2-0-0-20210830.jw-qa.owncloud.works/konnect/v1/register", "ad72d963-fd1e-48df-8ee2-8d74d247c768", "ad72d963-fd1e-48df-8ee2-8d74d247c768") created for "https://oc-10-8-0-oidc-2-0-0-20210830.jw-qa.owncloud.works/" + "" "RegisterClientJob"
08-30 14:36:09:538 [ info sync.httplogger ]:    "ad72d963-fd1e-48df-8ee2-8d74d247c768: Response: POST 400 https://konnect-oidc-2-0-0-20210830.jw-qa.owncloud.works/konnect/v1/register Header: { Cache-Control: no-cache, no-store, must-revalidate, Content-Length: 127, Content-Type: application/json; encoding=utf-8, Date: Mon, 30 Aug 2021 12:36:09 GMT, Pragma: no-cache, Referrer-Policy: origin, Server: Caddy, X-Content-Type-Options: nosniff, } Data: [{\n  \"error\": \"invalid_redirect_uri\",\n  \"error_description\": \"native clients must only use localhost redirect_uris with http\"\n}\n]"
08-30 14:36:09:538 [ debug sync.networkjob ]    [ OCC::AbstractNetworkJob::needsRetry ]:        Not Retry auth job OCC::SimpleNetworkJob("https://konnect-oidc-2-0-0-20210830.jw-qa.owncloud.works/konnect/v1/register", "ad72d963-fd1e-48df-8ee2-8d74d247c768", "ad72d963-fd1e-48df-8ee2-8d74d247c768", "Error transferring https://konnect-oidc-2-0-0-20210830.jw-qa.owncloud.works/konnect/v1/register - server replied: Bad Request") QUrl("https://konnect-oidc-2-0-0-20210830.jw-qa.owncloud.works/konnect/v1/register")
08-30 14:36:09:538 [ warning sync.networkjob ]: OCC::SimpleNetworkJob("https://konnect-oidc-2-0-0-20210830.jw-qa.owncloud.works/konnect/v1/register", "ad72d963-fd1e-48df-8ee2-8d74d247c768", "ad72d963-fd1e-48df-8ee2-8d74d247c768", "Error transferring https://konnect-oidc-2-0-0-20210830.jw-qa.owncloud.works/konnect/v1/register - server replied: Bad Request") QNetworkReply::ProtocolInvalidOperationError "Server replied \"400 Bad Request\" to \"POST https://konnect-oidc-2-0-0-20210830.jw-qa.owncloud.works/konnect/v1/register\"" 400
08-30 14:36:09:538 [ warning sync.credentials.oauth ]:  Failed to dynamically register the client, try the default client id "\tError: Missing field client_secret_expires_at\n"
08-30 14:36:09:538 [ debug sync.credentials.oauth ]     [ isUrlValid ]: Checking URL for validity: QUrl("https://konnect-oidc-2-0-0-20210830.jw-qa.owncloud.works/signin/v1/identifier/_/authorize?response_type=code&client_id=xdXOt13JKxym1B1QcEncf2XDkLAexMBFwiT9j6EfhhHFJhs2KM9jbjTmf8JBXE69&redirect_uri=http://127.0.0.1:35287&code_challenge=WTv6x-IN-mzsKOkkgmLve8Z-nLufTnOi4XTSkDNV-7M&code_challenge_method=S256&scope=openid offline_access email profile&prompt=select_account consent&state=mCjspJiDGFxTm8PpQjfpbMGyxVyzqiUpbG_KVUrsQsk%3D&login_hint=aaliyah_abernathy&user=aaliyah_abernathy")
08-30 14:36:09:549 [ debug sync.networkjob ]    [ OCC::AbstractNetworkJob::slotFinished ]:      Network job finished OCC::SimpleNetworkJob("https://konnect-oidc-2-0-0-20210830.jw-qa.owncloud.works/konnect/v1/register", "ad72d963-fd1e-48df-8ee2-8d74d247c768", "ad72d963-fd1e-48df-8ee2-8d74d247c768", "Error transferring https://konnect-oidc-2-0-0-20210830.jw-qa.owncloud.works/konnect/v1/register - server replied: Bad Request")
08-30 14:36:17:045 [ warning gui.account.state ]:       checkConnectivity blocking: false
08-30 14:36:17:046 [ debug gui.account.state ]  [ OCC::AccountState::checkConnectivity ]:       "jwtest@oc1080-ldap-20210820.jw-qa.owncloud.works" The last ETag check succeeded within the last  122 s ( 63 s). No connection check needed!
```

**Comment by jnweiger** [comment]
Another blocking issue with DCR at kopano would be https://github.com/owncloud/openidconnect/issues/142 -- But I believe that in my case I am failing earler.

**Comment by michaelstingl** [comment]
I've only seen DCR working with Keycloak.

**Comment by wkloucek** [comment]
From https://github.com/owncloud/openidconnect/issues/142#issuecomment-772458761:

>> Thanks for sharing that! In the specs, nothing pointed to `0` as a possible/plausible value and the implementation in the iOS client would have seen that as expiration on the first minute of the year 1970.

> the `0` value is part of the spec (see https://openid.net/specs/openid-connect-registration-1_0.html#RegistrationResponse). So treating it as 1970 is certainly an implementation bug.

Could be also the case for this implementation, even if the error message `Error: Missing field client_secret_expires_at` suggests an different error.

**Comment by TheOneRing** [comment]
We handle the case that it is 0, but as the doc mentions it's a required field and thus should be present?
I could also default to 0 but ....

**Comment by wkloucek** [comment]
> We handle the case that it is 0, but as the doc mentions it's a required field and thus should be present?
> I could also default to 0 but ....

If you read it exactly you will notice `REQUIRED if client_secret is issued` (took me also 5 times reading). But I don't know what to do if it is omitted :man_shrugging:

**Comment by TheOneRing** [comment]
Narf had another look at the output....
```08-30 14:36:09:538 [ info sync.httplogger ]:    "ad72d963-fd1e-48df-8ee2-8d74d247c768: Response: POST 400 https://konnect-oidc-2-0-0-20210830.jw-qa.owncloud.works/konnect/v1/register Header: { Cache-Control: no-cache, no-store, must-revalidate, Content-Length: 127, Content-Type: application/json; encoding=utf-8, Date: Mon, 30 Aug 2021 12:36:09 GMT, Pragma: no-cache, Referrer-Policy: origin, Server: Caddy, X-Content-Type-Options: nosniff, } Data: [{\n  \"error\": \"invalid_redirect_uri\",\n  \"error_description\": \"native clients must only use localhost redirect_uris with http\"\n}\n]"```

so completely unrelated.

**Comment by jnweiger** [comment]
@TheOneRing unrelated to DCR: is the original issue localhost vs 127.0.0.1 fixed? I remember we discussed that already???

**Comment by TheOneRing** [comment]
> @TheOneRing (unrelated to the DCR topic, sorry for mixing that here): What can we do about the Kopano-case that was caused by #8593 ?

That was for oauth, this issue here needs fixing in kopano

**Comment by wkloucek** [comment]
> > @TheOneRing (unrelated to the DCR topic, sorry for mixing that here): What can we do about the Kopano-case that was caused by #8593 ?
> 
> That was for oauth, this issue here needs fixing in kopano

This shouldn't be an issue with version 0.34 (https://github.com/libregraph/lico/blob/22d608b4c8308a94afd53f43d00ec4afe699861e/identity/clients/clients.go#L49-L63).
Prior versions would only accept `localhost`. @jnweiger which version of the Kopano IDP did you use?

**Comment by michaelstingl** [comment]
> This shouldn't be an issue with version 0.34

@GeraldLeikam can you update this system and test again? (or send me credentials)

**Comment by wkloucek** [comment]
@michaelstingl you should also be able to use oCIS installations since we have that version of the Kopano IDP already running and configured ;-)

**Comment by michaelstingl** [comment]
> @michaelstingl you should also be able to use oCIS installations since we have that version of the Kopano IDP already running and configured ;-)

Good point 👍 (I always use Keycloak with oCIS)

**Comment by michaelstingl** [comment]
`redirect_uri=http://127.0.0.1:62285` works fine with https://ocis.ocis-traefik.latest.owncloud.works/.well-known/openid-configuration

**Comment by TheOneRing** [comment]
Thx for checking!
