### ISSUE TITLE
[QA] Linux download page for Fedora does not mention RC or Beta

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8969]
Seen with owncloud-client 2.0.0 - Beta3 and RC1

* https://download.owncloud.com/desktop/ownCloud/testing/2.9.0-rc1.5070/linux/download/
* https://download.owncloud.com/desktop/ownCloud/testing/2.9.0-beta3.5018/linux/download/
----
* Click any Linux platform except Fedora, the suffix `beta3` or `rc1`is shown in the version number of the headings, and in the download links.
* Click Fedora, the headings have `2.9.0-0` as version number, only the download links show the correct prerelease. 

![image](https://user-images.githubusercontent.com/1108546/131464672-a3379841-6844-4f3f-ada7-ab292980b850.png)

**Comment by TheOneRing** [comment]
Seems fixed
