### ISSUE TITLE
[Fedora, KDE Plasma] Owncloud (client) icon missing in some themes from the sytem tray 

### ISSUE THREAD

**Issue by aNDy-Squirrel** [owncloud/client#8976]
### Expected behaviour
Icon is visible in system tray.

### Actual behaviour
The owncloud icon is invisible in some icon themes (I guess in the ones that don't have their own owncloud icon set). Example: Oxygen theme: not visible, Breeze: visible. 
There is an empty spot in the systemtray, which opens the Owncloud-client window if clicked. 

### Steps to reproduce
1.  Log in to a plasma session and wait until Owncloud-client starts. 

### Server configuration
Server is run by employer. I don't know the configuration, but it is probably irrelevant.

### Client configuration
Client version: 2.7.4 (most recent in Fedora 34)
Operating system: Fedora 34 (linux)
OS language: US English
Qt version used by client package (Linux only, see also Settings dialog): 5.15.2
Client package (From ownCloud or distro) (Linux only): owncloud-client-2.7.4-2.fc34.src.rpm
KDE Plasma version: 5.22.4
KDE Frameworks: 5.85.0

Installation path of client: /usr/bin/owncloud

### Logs
Please let me know if logs are needed (syncing seems to work fine).

**Comment by TheOneRing** [comment]
Is there no icon or is it just a dark icon on a dark background?

**Comment by aNDy-Squirrel** [comment]
There is no icon. If I change the Plasma Style to some light style (e.g., Breeze), the Panel (including the system tray) turns light, but I still see no icon. I also tried to restart the owncloud client, but that doesn't help.

**Comment by michaelstingl** [comment]
> Client version: 2.7.4 (most recent in Fedora 34)

Could you try with the 2.9.0-rc1?
https://download.owncloud.com/desktop/ownCloud/testing/2.9.0-rc1.5107/linux/download/

**Comment by aNDy-Squirrel** [comment]
That works. After removing the old client, installing the new version and restarting it, the icon appeared. 

The icon is indeed dark and hard to see.

**Comment by TheOneRing** [comment]
Thx for reporting and testing.
