### ISSUE TITLE
[QA] download in WinVFS mode sometimes has no time estimate

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8984]
Seen in 2.9.0 RC2

* let the client sync down several thousand files in WinVFS mode
* during initial download, there is a time estimate.
* after the sync finishes, move a folder. The next sync does not have a time indicator:
![image](https://user-images.githubusercontent.com/1108546/132420312-3dcb0627-039b-44ee-a051-f9f1414646a4.png)

Upper client: winVFS, lower testpilot: Linux physical download

**Comment by TheOneRing** [comment]
We can only estimate time if we download files, not when we create placeholder.
