### ISSUE TITLE
[QA] WinVFS: copy out a large folder causes nervous tray icon and is slow

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#8985]
Seen with 2.9.0-RC2 in Win10 21H1

* sync a server that has folders with thousands of small files using VFS
* when the sync is done, use the windows explorer to copy one folder from the sync root to the desktop
* the client becomes active, as it has to now physically download the files.
* the icon in the settings window slowly alternates between circling arrows and green checkmark. OK
* the tray icon starts flickering very fast

https://user-images.githubusercontent.com/1108546/132485158-103c71a3-5bcb-43ec-8dce-d767cfba04c0.mp4

**Comment by jnweiger** [comment]
The copying was very slow, and the windows progress indicator remained at 0% until the end. 
9381 files with a total of 5MB took ca. 30 minutes. 

Besides the flickering icon, an excessive amount of of logfiles is created. Probably one logfile per file in the folder? 
Find attached a smal exerpt from the logdir.

[ownCloud-logdir.zip](https://github.com/owncloud/client/files/7128253/ownCloud-logdir.zip)

**Comment by jnweiger** [comment]
The "not synced" issues list, repeatedly says aborted, without further explanation. But the folder and its files are copied correclty, as far as I can tell.

![image](https://user-images.githubusercontent.com/1108546/132496868-f31902d7-a4fd-40b4-9975-c4485843ed7d.png)

**Comment by amrita-shrestha** [comment]
Test result: the tray icon doesn't flicker while copying one folder with more than 9 thousand file from the sync root to the desktop.
 Tested with owncloud 4.0.0.10476-daily20230322 bb5d97
