### ISSUE TITLE
build instructions missing

### ISSUE THREAD

**Issue by casey-ac** [owncloud/client#8990]
### Expected behaviour
If you don't package build instructions in with your downloads, the link you provide should work. 

### Actual behaviour
Error 404

### Steps to reproduce
1. Go to the site you direct people to in your Readme:  https://doc.owncloud.org/desktop/building.html

**Comment by michaelstingl** [comment]
> If you don't package build instructions in with your downloads

Where do you expect the build instructions? Please elaborate.

> the link you provide should work.

Where did you find the link? I'd like to fix it.

The link I know is this:
https://doc.owncloud.com/desktop/appendices/building.html

I think this is helpful too:
https://github.com/owncloud/ownbuild

**Comment by TheOneRing** [comment]
Its also linked in our README.MD https://github.com/owncloud/client#building-the-source-code which is part of the released tarball.

**Comment by michaelstingl** [comment]
> 1. https://doc.owncloud.org/desktop/building.html

@casey-ac works again.
