### ISSUE TITLE
Automated update restarts Windows Explorer

### ISSUE THREAD

**Issue by matthiastummers** [owncloud/client#8995]
This issue is almost a copy of https://github.com/nextcloud/desktop/issues/3726 as I experienced similar behavior.
Also, this issue https://github.com/nextcloud/desktop/issues/3399 seems to describe the same problem.

### How to use GitHub

- Please use the 👍 reaction to show that you are affected by the same issue.
- Please don't comment if you have no relevant information to add. It's just extra noise for everyone subscribed to this issue.
- Subscribe to receive notifications on status change and new comments.

### Expected behavior

No crash of Windows Explorer

### Actual behavior

Windows Explorer crashes (more or less if you read about other user reports) once the update is complete or at the very end of it.
Some have to wait a few seconds or minutes until Windows Explorer recovers by itself, some recover from the crash using the task manager some others still need to hard reboot.

Steps to reproduce

1. I had version 2.8.2 installed (not sure)
2. Wait for the update notice (I waited until the message window appeared that an update was available and clicked "Ok" to install it

### Client configuration

Client version: 2.8.2 (not sure) (now: 2.9.0 (build 5150) 240687 Sep 8 2021 07:50:41)

Operating system: Windows 10 (Libraries Qt 5.12.11, OpenSSL 1.1.1k 25 Mar 2021 ; Using virtual files plugin: wincfapi ; windows-10.0.19043)

OS language: English

Installation path of client: C:\Program Files (x86)\ownCloud

**Comment by matthiastummers** [comment]
I just tried to reproduce on a second pc with exactly the same windows and qt config (i.e. : (Libraries Qt 5.12.11, OpenSSL 1.1.1k 25 Mar 2021 ; Using virtual files plugin: wincfapi ; windows-10.0.19043)

And it didn't crash (although I had a blue screen for 3 to 5 seconds ...)

**Comment by nssatlantis** [comment]
This whole virtual files thing seems to have been a badly functional idea on both sides, for a lot of people.

NC hasn't acknowledged nor even responded to the problem, perhaps Owncloud can set a decent standard here.

**Comment by TheOneRing** [comment]
Hi @matthiastummers can you specify when the crash happens?
During the update?
During a sync?
When interacting with virtual files?

**Comment by nssatlantis** [comment]
> Hi @matthiastummers can you specify when the crash happens?
> During the update?
> During a sync?
> When interacting with virtual files?

I can vouch for when it happens on NextCloud, basically after installation, and/or a reboot windows explorer will eventually freeze up, non responsive or very, very slow as if it's being overloaded. Closing the NC client for me completely resolves the freeze and everything loads up again without issues.

In this case I have tried reboots, reinstalls and deleting the configs but something with the virtual file system seems to hate my computer, I have quit using the client since then. 

It's hard to pin it to anything, but it happens somewhere in the initializing or start of the sync... Or just before that.

**Comment by matthiastummers** [comment]
Hi @TheOneRing ,
During the update !
Not during the use of the client afterwards (I do not even know what virtual files are ^^)
Once Windows has recovered from the bug, there are no other apparent bugs.

**Comment by TheOneRing** [comment]
During the unattended update we restart the explorer in order to be able to update the browser extension.

If the msi is executed manually we ask for the permission. The alternative would be to ask you to reboot after the update.

**Comment by matthiastummers** [comment]
I am not an expert on updates, so I am not sure whether I fall under the category 'unattended' or not, but, in any case, what happened was the following:
1. OwnCloud notifies an update is available via a popup
2. I click on the popup to launch the update
3. OwnCloud automatically retrieves the update installer from the server and launches the installer.
4. I get prompted again to authorize OwnCloud to install the update.
5. I grant authorization
6. The installer starts the installation of the update and nearing the end of the installation ...
7. BOOM ! :-)

Never did I manually launched a msi nor was I asked to reboot the client or my PC
Also, I have no clue about what the browser extension is ...
GL !
