### ISSUE TITLE
Allow to filter issue table by issue type

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9000]
Add the ability to filter by issue type to the context menu of the issue type column header.

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/pull/9010 ads the status to the table.
Filtering is still missing.

**Comment by erikjv** [comment]
As far as I can see, `OCC::Models::displayFilterDialog` is used in two places. Do both need filtering by status?

The context menu is the same no matter which column you click, so I assume we need to show both the account filter, and the status filter. Also both filters should be usable independent of each other (e.g. "show all excluded for admin@")?

Or should there be only 1 active filter, depending on which column you click, that resets the filter for the other column?

The filtering can be done by a subclass of `QSortFilterProxyModel`, which asks for the `UnderlyingDataRole` of the item, and filters based on that.

**Comment by TheOneRing** [comment]
I think the filter only makes sense on the issue widget, the column is hidden on the protocol view.
It might come handy to allow to filter by account and status?
Whether we want to allow multiple accounts/states as filter, depends on the complexity of the solution.
