### ISSUE TITLE
[REQUEST] Move files to trash instead of deleting them

### ISSUE THREAD

**Issue by tbarbette** [owncloud/client#9001]
Due to a problem in the RAID array backing my ownCloud server, some files were thought to be received but were actually not written on the disk. As a consequence after fixing the problem and running `occ files:scan` the files were thought to be removed on the server.

Then, the sync made ownCloud clients delete all the concerned files. This happened before any backup could be made as it was all the recent files sent by clients, and therefore resulted in a dramatic loss.

To prevent this kind of scenario, it would be interesting to have an option to move the local files to the trash instead of permanently deleting the files.

---

TODO:
Remove https://github.com/owncloud/client/blob/6f8e49d51add2f9cf75fb9cb020315199cd93c4d/src/common/filesystembase.cpp#L383 and replace its usage with https://doc.qt.io/qt-5/qfile.html#moveToTrash

**Comment by TheOneRing** [comment]
Sorry to hear that you encountered data loss.

At the moment we only support the trash on linux systems.
Qt 5.15 brought support for cross platform support.
Switching to Qt 5.15 is planned for 2.10.

The trash will only work for downloaded files not for placeholders.

**Comment by tbarbette** [comment]
Ah, so it is in the roadmap? This happened on a Mac client.

**Comment by TheOneRing** [comment]
Add advanced setting: Default off

**Comment by HanaGemela** [comment]
Scenario:
1. Exclude a folder in the selecting sync
Expected result: Folder has also been moved to the trash bin

**Comment by HanaGemela** [comment]
Passed in ownCloud 6.0.0.12640-daily20231117
