### ISSUE TITLE
Multiple accounts are sharing the folder error

### ISSUE THREAD

**Issue by mattvaccoda** [owncloud/client#9002]
### Expected behaviour
HDD to sync with the server.

### Actual behaviour
There's an error message that says...

**Multiple account are sharing the folder H:/.
This configuration is know to lead to dataloss and is no longer supported.
Please consider removing this folder from the account and adding it again.**

This happens not only for myself but my colleagues as well. We believe it's this commit that has caused the issue...

https://github.com/owncloud/client/commit/1b5925c327c01bbff65de4059d1153c9d6574ba9

We are unable to sync anything.

### Steps to reproduce
1. Open OwnCloud
2. Error message appears

### Server configuration
Operating system: CentOS

Web server: Apache 2.4

Database: MySQL 5.7

PHP version: PHP 7.3

ownCloud version: Latest version

Storage backend (external storage): Local Disk

### Client configuration
Client version: Version 2.9.0 (build 5150)

Operating system: Windows 10

OS language: English (UK)

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )

I've tried to get the client log file but the above link doesn't work so not sure how I can get it.

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by TheOneRing** [comment]
You either have multiple accounts using the same folder or some old and orphaned `._sync_*.db` or `.sync_*.db ` files from previous setups in that folder.

**Comment by mattvaccoda** [comment]
Hi Hannah,

Thanks for the quick response. We deleted the highlighted files and everything works now.

[https://ibb.co/yghZcX1](url)

Thanks

Matt

**Comment by Vogtinator** [comment]
I see the same issue here and I believe this is a genuine bug.

On the first start of 2.9.0, it created a new `.sync_journal.db` file, but kept the previous `.sync_286ccd77d0ee.db` file around. This triggers the check for multiple `.sync_*.db` files.

**Comment by TheOneRing** [comment]
Any reason you created a new sync connection without properly removing the old one?

2.9.1 Will add a link to a faq to those messages and how to solve the problems,

**Comment by Vogtinator** [comment]
> Any reason you created a new sync connection without properly removing the old one?

I did not change any configuration at all, I simply updated ownCloud client from 2.8.1 to 2.9.0.

**Comment by TheRealDude2** [comment]
Both files were present in my folder (._sync_*.db and .sync_*.db).
After deleting the file that has not been changed for the longest time, everything works without error message in 2.9.0, but a .sync_journal.db file is not created.

**Comment by Step72** [comment]
> You either have multiple accounts using the same folder or some old and orphaned `._sync_*.db` or `.sync_*.db ` files from previous setups in that folder.

Hello
Where is the files ?

**Comment by TheOneRing** [comment]
> > You either have multiple accounts using the same folder or some old and orphaned `._sync_*.db` or `.sync_*.db ` files from previous setups in that folder.
> 
> Hello
> Where is the files ?

In you sync root, it is a hidden file so you need to make those visible first.

**Comment by Step72** [comment]
Can you tell me how to make it visible?

**Comment by TheRealDude2** [comment]
Caution. After our discussion at Central. Deleting is only the solution if you do not do this double sync, but that is just the remains of an old sync.

**Comment by Vogtinator** [comment]
@TheOneRing Can you please confirm the bug I reported and reopen this?

Or should I file a new issue?

**Comment by TheOneRing** [comment]
What you describe looks like indeed the migration failed, but in that case you should have seen the setup wizard directly after the upgrade. It was supposed to just continue using the old sync journal.

Can you open an issue regarding the config migration, I'll need to know which platform you are using and from which client you upgraded from.

**Comment by Vogtinator** [comment]
> Can you open an issue regarding the config migration, I'll need to know which platform you are using and from which client you upgraded from.

Ok: https://github.com/owncloud/client/issues/9019
