### ISSUE TITLE
Synchronization protcol shows timestamps in UTC since 2.9.0

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#9006]
### Expected behaviour
All timestamps should be in local time

### Actual behaviour
After upgrading to the 2.9.0 desktop client for Windows, I see UTC timestamps in the synchronization protocol, but in the "Not synchronized" tab they are in local time as expected.

These two screenshots are from the same syncronization run:

![sync-protocol](https://user-images.githubusercontent.com/875883/132986938-e409d356-2326-4bcc-9a0c-9e0e81c64c84.png)

![not-synced](https://user-images.githubusercontent.com/875883/132986939-6060fbbb-af26-4cc7-9425-18e522e4f5eb.png)

### Client configuration
Client version: 2.9.0

Operating system: Windows 10 x64

OS language: German

Installation path of client: Default

**Comment by TheOneRing** [comment]
Thank you for reporting the issue.
