### ISSUE TITLE
Migration from 2.8.1 to 2.9.0 fails silently

### ISSUE THREAD

**Issue by Vogtinator** [owncloud/client#9019]
After upgrading from 2.8.1 to 2.9.0, it shows a message that "multiple accounts are sharing the same folder" and started to sync paths which were explicitly excluded before. The sync folder contains both `.sync_journal.db` and `.sync_286ccd77d0ee.db`.

Neither issue happens if I rename `.sync_286ccd77d0ee.db` to the new `.sync_journal.db` name before starting 2.9.0.

### Server configuration
Not relevant (I think)

### Client configuration
Client version: From 2.8.1 to 2.9.0

Operating system: openSUSE Tumbleweed

OS language: German

Qt version used by client package (Linux only, see also Settings dialog): 5.15.2 (before and after update)

Client package (From ownCloud or distro) (Linux only): Using the package from the distro (2.8.1-2.1 to 2.9.0-1.1), which has no patches.

### Logs

Nothing really relevant unfortunately. The log shows that it fills a new database:

```
09-14 11:11:01:133 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 1 2
09-14 11:11:01:133 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 2 9
09-14 11:11:01:133 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 3 0
09-14 11:11:01:133 [ debug sync.database.sql ]  [ OCC::SqlQuery::bindValue ]:   SQL bind 4 0
09-14 11:11:01:133 [ debug sync.database.sql ]  [ OCC::SqlQuery::exec ]:        SQL exec "INSERT INTO version VALUES (?1, ?2, ?3, ?4);"
09-14 11:11:01:133 [ debug sync.database.sql ]  [ OCC::SqlQuery::exec ]:        Last exec affected 1 rows.
```

I should mention that for reproducing this to get logs, I just "undid" the migration by doing `mv .sync_journal.db .sync_286ccd77d0ee.db`.

**Comment by TheOneRing** [comment]
I assume you also got to see the setup wizard and you where asked to setup your account again.
In 2.9 we migrate old client configurations to a new config folder, the unbranded ownCloud version however should not have been affected.

**Comment by Vogtinator** [comment]
> I assume you also got to see the setup wizard and you where asked to setup your account again.

I did not see any setup wizard. I only noticed the issue because of unusual high network activity, which made me open the client window.

**Comment by TheOneRing** [comment]
Well then I'm a bit lost on what might have happened :(

**Comment by Vogtinator** [comment]
Can you link to the code which is responsible for either migrating the database to the new location or selecting the old database name? Maybe I can spot something.

**Comment by TheOneRing** [comment]
The migration does not do anything to your database it only migrates the location of the config file containing the name of your db.
https://github.com/owncloud/client/commit/4314447664de7efa48f9c8443776b4af38418ff2#diff-157772a2ade24319c7637b70253590dddfb55f6d4902b814582aca1a2ce23bc8

**Comment by Vogtinator** [comment]
> The migration does not do anything to your database it only migrates the location of the config file containing the name of your db.
> [4314447#diff-157772a2ade24319c7637b70253590dddfb55f6d4902b814582aca1a2ce23bc8](https://github.com/owncloud/client/commit/4314447664de7efa48f9c8443776b4af38418ff2#diff-157772a2ade24319c7637b70253590dddfb55f6d4902b814582aca1a2ce23bc8)

Ok. That approach probably failed here because the configuration here does not include `journalPath` keys:

```
[Accounts]
0\Folders\ownCloud\ignoreHiddenFiles=true
0\Folders\ownCloud\localPath=/home/fvogt/ownCloud/
0\Folders\ownCloud\paused=false
0\Folders\ownCloud\targetPath=/
0\authType=http
...
```

I guess the previous version(s) never wrote that into the file?

**Comment by TheOneRing** [comment]
But how https://github.com/owncloud/client/blob/master/src/gui/folder.cpp#L1256

**Comment by TheOneRing** [comment]
The settings folder should contain backups of your config

**Comment by Vogtinator** [comment]
It looks like this:

```
-rw-r--r--  1 fvogt    50   125 15. Sep 09:02 cookies0.db
-rw-r--r--  1 fvogt    50   377 14. Mär 2017  cookies.db
drwxr-xr-x  2 fvogt    50  4096  8. Dez 2015  folders
-rw-r--r--  1 fvogt users  3174 15. Sep 09:03 owncloud.cfg
-rw-r--r--  1 fvogt users  1565 15. Okt 2018  owncloud.cfg.backup_20181015_153124
-rw-r--r--  1 fvogt users  1597 21. Nov 2018  owncloud.cfg.backup_20181121_135453_2.5.0
-rw-r--r--  1 fvogt users  1615 28. Feb 2019  owncloud.cfg.backup_20190228_132204_2.5.1
-rw-r--r--  1 fvogt users  1664  2. Mai 2019  owncloud.cfg.backup_20190502_100026_2.5.3
-rw-r--r--  1 fvogt users  1667 24. Feb 2020  owncloud.cfg.backup_20200224_095230_2.5.4
-rw-r--r--  1 fvogt users  1672 15. Jul 13:28 owncloud.cfg.backup_20210715_132817_2.6.1
-rw-r--r--  1 fvogt users  1672 13. Sep 16:11 owncloud.cfg.backup_20210913_161144_2.8.1
```

None of them contain `journalPath`.

**Comment by Vogtinator** [comment]
I guess `Folder::saveToSettings` is only called when settings actually changed, so that might not have happened for a long time.

I set this up sometime 2015 and haven't changed any folder settings since then.

**Comment by TheOneRing** [comment]
Awesome the old migration code sets a journalPath but never saves it 😢  https://github.com/owncloud/client/blob/master/src/gui/folderman.cpp#L293

**Comment by Vogtinator** [comment]
I built the 2.9 branch locally and gave it a try.

2.4 -> 2.8 -> 2.9.1
-

That did unfortunately not work. Before 2.9.1, only `.sync_286ccd77d0ee.db` is present, but 2.9.1 then ignores that and created a new `._sync_286ccd77d0ee.db` instead (???)

2.4 -> 2.9.0 -> 2.9.1
---

That worked, it continued to use the `.sync_journal.db` created by 2.9.0. However, the old database is still there, so the warning about multiple accounts will stay.

**Comment by TheOneRing** [comment]
> I built the 2.9 branch locally and gave it a try.
> 
> ## 2.4 -> 2.8 -> 2.9.1
> That did unfortunately not work. Before 2.9.1, only `.sync_286ccd77d0ee.db` is present, but 2.9.1 then ignores that and created a new `._sync_286ccd77d0ee.db` instead (???)

`._sync_286ccd77d0ee.db`  Looks like a 2.4 db where is sync_286ccd77d0ee.db coming from?
> 
> ## 2.4 -> 2.9.0 -> 2.9.1
> That worked, it continued to use the `.sync_journal.db` created by 2.9.0. However, the old database is still there, so the warning about multiple accounts will stay.

That is expected deleting stuff is always dangerous and will still require manual intervention.

**Comment by Vogtinator** [comment]
> `._sync_286ccd77d0ee.db` Looks like a 2.4 db where is sync_286ccd77d0ee.db coming from?

Sorry, that was supposed to be `.sync_92839cef8e49.db`. For some reason after the 2.9.1 migration the hash changed.

Using GDB, I see the difference:

`user@https://host:/` (2.8.1 config) vs. `user@https://host/:/` (2.9.1 migrated config)

So the config migration added a trailing `/` to the URL, which results in it no longer finding the database...

**Comment by TheOneRing** [comment]
Regarding 2.4 -> 2.8 -> 2.9.1

Yes thats broken since https://github.com/owncloud/client/commit/5211d9a8b1cade64d6f9123ada0dd08b38f30735

So we probably need a 2.4 -> 2.5 -> 2.6 .......


I need another round to fix the migration from ._sync to .sync.....

**Comment by silvain** [comment]
I have 6 owncloud accounts, and 2 of them got the error message «Multiple accounts are sharing the folder /home/silvain/ownCloud/...».
Reading the explanation above, I tried one thing which worked:
**Deleting the old synchronization db files (hidden files) from the data folders of the 2 accounts affected.**
._sync_5ff816b09f82.db
._sync_5ff816b09f82.db-shm
._sync_5ff816b09f82.db-wal
(only one was present in one case, and I actually moved them somewhere else to be safe).
This was enough for the error message to disappear.
### Why did this happen?
I suspect this happened only on two of my accounts... because these are the older ones I have, and the previous upgrad(s) kept these old versions of the db files, which did not have any effect until this recent upgrade.
These deleted db files are all dated May 21, 2019.

**Comment by Vogtinator** [comment]
I think this got closed by accident, it's not fixed yet

**Comment by TheOneRing** [comment]
Yes thx for mentioning, I merged a commit with a `Fixes:` to master

**Comment by TheOneRing** [comment]
@gabi18 we are ready for another round of tests:

    2.4 -> 2.5 -> 2.6 -> 2.7-> 2.8 -> 2.9.1
    2.4 -> 2.8 -> 2.9.1
    2.4 -> 2.9.0 -> 2.9.1
    2.9.0 -> 2.9.1

The idea is to keep the old database but if a previous migration already created a duplicated db we only take the newest.

**Comment by Vogtinator** [comment]
With #9046 the issue with the hash generation remains. Instead of using the existing sync journal, it creates a new empty one again. This time it's properly called `.sync_journal.db` though, instead of using the wrong hash.

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/issues/9019#issuecomment-920105001 I didn't get that the hash changed...
Ill have another look...

**Comment by Vogtinator** [comment]
I tried 2.9 with #9054 merged and it appears to be working, thanks!

While testing 2.8.1 -> 2.9 again I only had to reenter the password, which is apparently not migrated from the old entry format to the new one.

**Comment by TheOneRing** [comment]
Thank you very much ❤️ 
Credentials should be migrated but I can imagine that also your tests could have messed up stuff.
Anyhow the pain of reentering a pw is much less than what we experienced here.

Many thanks for your reporting and the ongoing testing.

**Comment by Vogtinator** [comment]
> Credentials should be migrated but I can imagine that also your tests could have messed up stuff.

I actually started from a clean keychain (kwallet) to avoid that. Where can I find the migration code?

**Comment by TheOneRing** [comment]
Here we read the old credentials https://github.com/owncloud/client/blob/master/src/libsync/creds/httpcredentials_p.h#L81 they are then saved in https://github.com/owncloud/client/blob/master/src/libsync/creds/httpcredentials.cpp#L354 .

**Comment by Vogtinator** [comment]
I had a quick look:

2.8.1 creates a password entry in the format of `username:https://host/:0` with the password, nothing else.

The 2.9 branch reads this, and then tries to delete a nonexistant `username:https://host/` entry. For some reason (`removeEntry` seems to be dead code), QtKeychain instead calls `writePassword` with empty data, so it creates an empty entry instead of doing nothing...

On top of that QtKeychain bug there is another weirdness which I can't explain so far: The account is "offline" immediately after migration, and I need to restart the client to trigger a connection. Could be some missing signal emission or something like that.

**Comment by TheOneRing** [comment]
Lets continue in https://github.com/owncloud/client/issues/9064

**Comment by gabi18** [comment]
Testing on Windows 10: 

- 2.4 -> 2.5 -> 2.6 -> 2.7-> 2.8 -> 2.9.1

2.4.3 -> 2.5.4
![update-2-4_2-5](https://user-images.githubusercontent.com/75983861/134896997-f9e76bba-8521-44a8-a4f1-0949dfc19cbc.png)

**Comment by gabi18** [comment]
Testing on Windows 10 VFS OFF
- 2.4.3 -> 2.8.2 -> 2.9.1daily20210927.5255

2.4.3 -> 2.8.2
The account isn't configured any longer
![update-2-4_2_8](https://user-images.githubusercontent.com/75983861/135036030-32d2161d-e53b-4f90-8f7f-5d4bf5152dd4.png)

**Comment by gabi18** [comment]
- 2.4.3 -> 2.7.6 ->  2.8.2 -> 2.9.1daily20210927.5255
- 2.4 -> 2.9.0 -> 2.9.1
- 2.9.0 -> 2.9.1

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/issues/9019#issuecomment-928901702 is unrelated and covered by https://github.com/owncloud/enterprise/issues/4597 closed in 2.9.0

**Comment by gabi18** [comment]
To complete update scenarios (Windows 10 VFS ON)

-  2.8.2 -> 2.9.1daily20210927.5255 

Result: works correctly, database file: .sync_xxxx.db

![update-2 8_2-9-1](https://user-images.githubusercontent.com/75983861/135084408-a1397aa7-d0ed-4622-80eb-995eaaecc18a.png)

**Comment by gabi18** [comment]
Retesting with owncloud-client 2.9.1rc2

- 2.4.3 to 2.9.1rc2 VFS OFF -> database file 

![2_4-2_9_1](https://user-images.githubusercontent.com/75983861/136791227-eae52e56-3338-430b-aaa0-426ea362c28b.png)

**Comment by gabi18** [comment]
Problem was because of outdated certificates. After a system update of the Win 10 20H2 VM the update check is successful:
![update_ok](https://user-images.githubusercontent.com/75983861/136972383-2bd82553-80a6-4636-b072-6a2bb7b69d78.png)
