### ISSUE TITLE
German buttons translation missing (and some others).

### ISSUE THREAD

**Issue by sfadschm** [owncloud/client#9022]
### Expected behaviour
Everything should be translated.

### Actual behaviour
The `Local folder` string and e.g., buttons in the add sync dialog are not translated (see screenshots).
I checked transiflex but everything seems to be translated there (and was working before 2.9).
Tested with both the `use default` language setting and specifically selecting `Deutsch`.

### Client configuration
Client version: 2.9.0

Operating system: Windows 10 (up-to-date)

OS language: German

### Screenshots
![Local Folder](https://user-images.githubusercontent.com/40514119/133256235-502e1553-2630-43b7-9bde-e6598c4c7d52.png)
![Local Folder2](https://user-images.githubusercontent.com/40514119/133256244-dd6e0ea7-dfce-4fc1-bd1d-bfd2d86c7f34.png)

**Comment by fmoc** [comment]
Such buttons are standard within Qt. You won't be able to find them on Transifex, because the translations should be provided by Qt as well.

What's really strange is that the "Auswählen..." button _is_ translated, because it's also a standard button. ll check the dialog's definition.

**Comment by fmoc** [comment]
I've checked how that dialog is set up. We use [QWizard](https://doc.qt.io/qt-5/qwizard.html) as a "frame" widget, the pages are four widgets we define in `src/gui/wizard`.

I don't see why there should be an inconsistency between the buttons on the bottom and the buttons on the wizard page.

**Comment by TheOneRing** [comment]
@fmoc do we successfully load the qtbase translations?

**Comment by fmoc** [comment]
I can't tell, really. We try a couple of different locations, but there is no logging in place that could tell us if the last call in the chain fails:
https://github.com/owncloud/client/blob/c7cf6611f3cf60652af4183d9a7d2b6c080f07a3/src/gui/application.cpp#L731-L738

**Comment by fmoc** [comment]
Can be reproduced in a Windows 10 VM.

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/pull/9062

**Comment by gabi18** [comment]
Confirmed on Windows 10 20H2, client 2.9.1rc1 (build 5270) that the buttons are translated:

![local_folder](https://user-images.githubusercontent.com/75983861/135397165-d66725ae-e17c-4f1d-8a85-dbf775c46dbc.png)

But 'Local folder' isn't translated.
