### ISSUE TITLE
Tray icon always shows "information" icon since 2.9.0

### ISSUE THREAD

**Issue by sagamusix** [owncloud/client#9027]
### Expected behaviour

Previously, when all synchronization runs finished, the client would show the green check mark in the tray icon. Now it always shows the blue information icon instead, telling me that the run was successful but files were ignored - which is completely expected, otherwise I would not have added those files to my ignore list after all! Of course this change could be intentional but to me, showing this icon gives the constant impression that some action is necessary, but that's not true.

### Actual behaviour

Since ownCloud 2.9.0, I always see the blue information icon in the tray because some files were ignored.

### Steps to reproduce
1. Have a list of ignored files
2. Do a synchronization run
3. The tray icon now shows the information icon instead of the green checkmark.

### Client configuration
Client version: 2.9.0

Operating system: Windows 10 x64

OS language: German

Installation path of client: Default

**Comment by TheOneRing** [comment]
See https://github.com/owncloud/client/issues/8970
