### ISSUE TITLE
Error message about multiple accounts

### ISSUE THREAD

**Issue by silvain** [owncloud/client#9039]
### Expected behaviour
All my 6 accounts should work together seamlessly

### Actual behaviour
Since I upgraded my client to 2.9.0 (on Ubuntu 20.04), two of my six accounts display an error message : 
_Multiple accounts are sharing the folder /home/silvain/ownCloud/<spedific folder of the account>
This configuration is know to lead to dataloss and is no longer supported.
Please consider removing this folder from the account and adding it again._
I do not understand where this supposed error come from, as I have separate folders for my different accounts.
Nvertheless, synchronizations seems to work normally.

### Steps to reproduce
Ugrade client to 2.9.0
Read information in settings

### Server configuration
Operating system: 

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:
ownCloud 2.9.0
Operating system:
Ubuntu 20.04 (ubuntu-5.4.0-84-generic)
OS language:
French
Qt version used by client package (Linux only, see also Settings dialog):
Qt 5.12.10
Client package (From ownCloud or distro) (Linux only):
probably disto, not sure, I have been using it for a very long time...
Installation path of client:
/etc/owncloud-client
### Logs
.owncloudsync.log file is 5.1 MB in one data folder, idem in another...
Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client logfile: Output of `owncloud --logwindow` or `owncloud --logfile log.txt`
(On Windows using `cmd.exe`, you might need to first `cd` into the ownCloud directory)
(See also https://doc.owncloud.org/desktop/troubleshooting.html#log-files )
These commands do not produce any result, either from a data directory, or from the config directory.
2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by michaelstingl** [comment]
duplicate for https://github.com/owncloud/client/issues/9019
