### ISSUE TITLE
owncloud-client-nautilus can not be installed on Debian 11

### ISSUE THREAD

**Issue by olifre** [owncloud/client#9040]
### Expected behaviour
`apt install owncloud-client-nautilus` should work. 

### Actual behaviour
Error message:
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 owncloud-client-nautilus : Depends: python-nautilus but it is not installable
E: Unable to correct problems, you have held broken packages.
```

### Steps to reproduce
1. `apt install owncloud-client-nautilus`

### Client configuration
Client version: 2.9.0 from ownCloud repositories

Operating system: Debian 11

### Further information
`python-nautilus` is not available anymore on Debian 11, it is superseded by `python3-nautilus`:
https://packages.debian.org/bullseye/python3-nautilus

**Comment by fmoc** [comment]
Will be fixed in the next daily build and subsequent releases.

**Comment by TheOneRing** [comment]
Thx

**Comment by gabi18** [comment]
Also for openSUSE 15.2/15.3 new package is python3-nautilus.
