### ISSUE TITLE
Unify enum translations by using enumDisplayName

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9043]
Some enums are translated to display strings in multiple locations and differently each time.
Port them to enumDisplayName and unify them.

See https://github.com/owncloud/client/blob/f29c794c5b4bca37190911cb2acd60b737498805/src/libsync/syncfileitem.h#L285 
https://github.com/owncloud/client/blob/f29c794c5b4bca37190911cb2acd60b737498805/src/libsync/syncfileitem.cpp#L78-L84

for an example.

**Comment by kitsiosvas** [comment]
Hello, I am interested in working on this. Can you explain the issue with a little more detail?
Mainly, where in the code, the problem is located?
Thank you

**Comment by fmoc** [comment]
@kitsiosvas there should be one utility function per enum only that converts the enum into user-readable strings. It makes no sense to do that more than once in various locations.

**Comment by TheOneRing** [comment]
One example of such an duplication is:
https://github.com/owncloud/client/blob/b26ffe42ccc8c43f2f225831bee477bacf035a5e/src/libsync/syncresult.cpp#L37
and 
https://github.com/owncloud/client/blob/724f7c8f97a3d9cb18d821942132762dade12c04/src/libsync/theme.cpp#L95
But I'm sure there are more.

**Comment by sourav25998** [comment]
Hello. Is this issue still open? If yes, then I would like to try my hands on it. Can you please brief me about the issue a bit more?

**Comment by fmoc** [comment]
The issue is still open. What do you want to know?
