### ISSUE TITLE
macOS: Copy Private Link Address copies wrong informations

### ISSUE THREAD

**Issue by hosy** [owncloud/client#9048]
When trying to copy a private link from the share menu, the wrong information will be copied into the clipboard

### Expected behaviour
ownCloud private link will be copied into the clipboard 

### Actual behaviour
Content `private link menu` will be copied into the clipboard

### Steps to reproduce
- On macOS open the ownCloud share menu for a shared item in the Finder
- Right Click on "Private Link" 
- "Copy Link Location"

<img width="798" alt="Bildschirmfoto 2021-09-17 um 13 50 09" src="https://user-images.githubusercontent.com/736109/133777977-4f5a7ad3-98d5-45de-90c0-7887aacccd27.png">

### Client configuration
Client version:
ownCloud 2.9.0 (build 5150) 240687 Sep 8 2021 16:49:13
Libraries Qt 5.12.11, OpenSSL 1.1.1k 25 Mar 2021
Using virtual files plugin: suffix
osx-20.6.0

Operating system:
macOS 11.5.1

OS language:
German

**Comment by HanaGemela** [comment]
client ownCloud 3.0.0.8922-alpha9
macOS 13.0 

Hasn't the steps to recreate changed? The flow of creating a link seems different now.
Anyway, a private link is not created.
oc10 10.11.0 - the link doesn't work
ocis - the option to share is greyed out

**Comment by TheOneRing** [comment]
Private links are not created but always existed in oc10.
In descirption you can see that wen you right clicked the link and selected copy link your got `private link menu`.
This is no longer the case.
