### ISSUE TITLE
no files listed in "Not Synced", but in "Sync Protocol" many files are listed as ignored

### ISSUE THREAD

**Issue by JoKalliauer** [owncloud/client#9052]
### Expected behaviour
Files should get synced, and if not there should be an explanation why they are ignored.

### Actual behaviour
Some files are listed as ignored, and I don't know why.
![Screenshot from 2021-09-17 14-56-04](https://user-images.githubusercontent.com/15687581/133786530-b2ed33f5-b0bc-4944-a92f-4a21f986b1f7.png)

![Screenshot from 2021-09-17 14-56-07](https://user-images.githubusercontent.com/15687581/133786542-164dcc5c-d05e-49fb-92e4-b264dde2c1bd.png)

### Steps to reproduce
![Screenshot from 2021-09-17 15-00-49](https://user-images.githubusercontent.com/15687581/133786626-caab3812-5f75-462c-a09a-c2d5e89d33fc.png)

### Server configuration
Web server: https://owncloud.tuwien.ac.at

ownCloud version: https://owncloud.tuwien.ac.at/status.php

| name | value |
|  -- | -- |
|installed | true|
|maintenance | false|
|needsDbUpgrade | false|
|version | "10.7.0.4"|
|versionstring | "10.7.0"|
|edition | "Enterprise"|<
|productname | "ownCloud TU Wien"|

### Client configuration
Client version: `owncloud --version`
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
ownCloud ownCloud 2.9.0 (build 5150) Sep  8 2021 13:21:10
https://github.com/owncloud/client/commit/240687d608c470ecad15d449184257b250531a36
Libraries Qt 5.12.10, OpenSSL 1.1.1l  FIPS 24 Aug 2021
Using virtual files plugin: off
fedora-5.13.15-200.fc34.x86_64
```

Operating system: `$ hostnamectl`
```
 Static hostname: lws84.imws.tuwien.ac.at
       Icon name: computer-laptop
         Chassis: laptop
      Machine ID: 96434f58f7644401a3f9d69da903899d
         Boot ID: ce0b799699ae4148ae05550cf1937bb7
Operating System: Fedora 34 (Workstation Edition) 
     CPE OS Name: cpe:/o:fedoraproject:fedora:34
          Kernel: Linux 5.13.15-200.fc34.x86_64
    Architecture: x86-64
 Hardware Vendor: Lenovo
```

OS language:  `$ locale`
```
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=de_AT.UTF-8
LC_TIME=de_AT.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=de_AT.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=de_AT.UTF-8
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT=de_AT.UTF-8
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

Qt version used by client package (Linux only, see also Settings dialog):
```
ownCloud 2.9.0 (build 5150) 240687 Sep 8 2021 13:21:10
Libraries Qt 5.12.10, OpenSSL 1.1.1l FIPS 24 Aug 2021
Using virtual files plugin: suffix
fedora-5.13.15-200.fc34.x86_64
```

Client package (From ownCloud or distro) (Linux only): `$ dnf list owncloud*`
```
Last metadata expiration check: 3:11:51 ago on Fr 17 Sep 2021 11:53:03.
Installed Packages
owncloud-client.x86_64                             2.9.0-5150          @owncloud
owncloud-client-nautilus.x86_64                    2.9.0-5150          @owncloud
owncloud-client-nemo.x86_64                        2.9.0-5150          @owncloud
owncloud-client-overlays-icons.x86_64              2.9.0-5150          @owncloud
```

Installation path of client:
`/opt/ownCloud/ownCloud/bin/owncloud`

**Comment by JoKalliauer** [comment]
> Would it be possible that you could provide the logs for the files?
> Could you also select the affected files in the share protocol and use right click -> copy to clipboard and share that with us?

I wanted to post them here however they are too large (~40MB) for github aswell they exceed the processing time of https://gist.github.com/ .

Therefore I uploaded them to https://owncloud.tuwien.ac.at/index.php/s/ZuQEE71GaKVMnX2

The smaller log-files are also below:

[20210918_1116_owncloud.log.0.LOG](https://github.com/owncloud/client/files/7189638/20210918_1116_owncloud.log.0.LOG)

[20210918_1117_owncloud.log.0.LOG](https://github.com/owncloud/client/files/7189641/20210918_1117_owncloud.log.0.LOG)

-----

Some files which are "ignored" exist in owncloud, but not locally (only virtual as *.owncloud), also the folder is set as always local:

[cyg_Matlab_Forces_.git_logs_refs_remotes_origin_HEAD.TXT](https://github.com/owncloud/client/files/7189667/cyg_Matlab_Forces_.git_logs_refs_remotes_origin_HEAD.TXT)
[cyg_Matlab_Forces_.git_refs_remotes_origin_HEAD.TXT](https://github.com/owncloud/client/files/7189668/cyg_Matlab_Forces_.git_refs_remotes_origin_HEAD.TXT)

All files in https://owncloud.tuwien.ac.at/index.php/s/7oz4v08EZIFVjAE are also affected. (Switching to "free disk-Space" and back to "always local" did not help.)

**Comment by TheOneRing** [comment]
Sorry for the delay, but its kind of busy here at the moment.
I had a look on your logs and found
`09-17 22:39:59:883 [ info sync.discovery ]:	Virtual file with non-virtual db entry, ignoring: "Shared/FKL_und_IM_skripten_source_files/Skripten/UE_Skriptum_202665/PvL_Sparrendach_iA/00_rs_Vorlage_final.pdf"`

This usually means that the local state and the db are out of sync, due to a db issue or a client bug.
With the suffix placeholder this can also happen with moves of virtual files.
In a later step the client would then remove that stale placeholder locally, and it would be recreated if found on the server.

Did the issue resolve it self in a later sync?

**Comment by JoKalliauer** [comment]
> Sorry for the delay, but its kind of busy here at the moment. I had a look on your logs and found `09-17 22:39:59:883 [ info sync.discovery ]: Virtual file with non-virtual db entry, ignoring: "Shared/FKL_und_IM_skripten_source_files/Skripten/UE_Skriptum_202665/PvL_Sparrendach_iA/00_rs_Vorlage_final.pdf"`
> 
> This usually means that the local state and the db are out of sync, due to a db issue or a client bug. With the suffix placeholder this can also happen with moves of virtual files. In a later step the client would then remove that stale placeholder locally, and it would be recreated if found on the server.
> 
> Did the issue resolve it self in a later sync?

Thanks for looking into the logs.

The issue still occurs:
![Screenshot from 2021-11-15 10-38-20](https://user-images.githubusercontent.com/15687581/141758248-de3fb967-5e30-4eac-aad8-042a7721a6df.png)

`00_rs_Vorlage_final.pdf` has 1.7MB on the server, and is a virtual file locally

The option in the contextmenü to `Immer local verfügbar` (german for `always locally avalable`)  is missing. Opening it with owncloud does not change anything.

Can I reset the local db?

**Comment by JoKalliauer** [comment]
I deleted the file `~/home/owncloud/.sync_531d4f25c6cb.db` that solved the problem for me, however the cause might still exist.
