### ISSUE TITLE
info-icon, without listing anything in "not sycronized"

### ISSUE THREAD

**Issue by JoKalliauer** [owncloud/client#9053]
### Expected behaviour
If the info-icon is active there should be a info at "not sycroniced", which files are affected.

It is related to #8970 and #9052 , but differently to #9052 this issue seems not to be always be reproducible.

### Actual behaviour
![Screenshot from 2021-09-17 15-35-44](https://user-images.githubusercontent.com/15687581/133791976-dd676ccf-f5c6-4045-a06e-7037876184f6.png)

### Steps to reproduce
unknown

### Server configuration
Web server: https://owncloud.tuwien.ac.at

ownCloud version: https://owncloud.tuwien.ac.at/status.php

| name | value |
|  -- | -- |
|installed | true|
|maintenance | false|
|needsDbUpgrade | false|
|version | "10.7.0.4"|
|versionstring | "10.7.0"|
|edition | "Enterprise"|<
|productname | "ownCloud TU Wien"|

### Client configuration
Client version: `owncloud --version`
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
ownCloud ownCloud 2.9.0 (build 5150) Sep  8 2021 13:21:10
https://github.com/owncloud/client/commit/240687d608c470ecad15d449184257b250531a36
Libraries Qt 5.12.10, OpenSSL 1.1.1l  FIPS 24 Aug 2021
Using virtual files plugin: off
fedora-5.13.15-200.fc34.x86_64
```

Operating system: `$ hostnamectl`
```
 Static hostname: lws84.imws.tuwien.ac.at
       Icon name: computer-laptop
         Chassis: laptop
      Machine ID: 96434f58f7644401a3f9d69da903899d
         Boot ID: ce0b799699ae4148ae05550cf1937bb7
Operating System: Fedora 34 (Workstation Edition) 
     CPE OS Name: cpe:/o:fedoraproject:fedora:34
          Kernel: Linux 5.13.15-200.fc34.x86_64
    Architecture: x86-64
 Hardware Vendor: Lenovo
```

OS language:  `$ locale`
```
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=de_AT.UTF-8
LC_TIME=de_AT.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=de_AT.UTF-8
LC_MESSAGES="en_GB.UTF-8"
LC_PAPER=de_AT.UTF-8
LC_NAME="en_GB.UTF-8"
LC_ADDRESS="en_GB.UTF-8"
LC_TELEPHONE="en_GB.UTF-8"
LC_MEASUREMENT=de_AT.UTF-8
LC_IDENTIFICATION="en_GB.UTF-8"
LC_ALL=
```

Qt version used by client package (Linux only, see also Settings dialog):
```
ownCloud 2.9.0 (build 5150) 240687 Sep 8 2021 13:21:10
Libraries Qt 5.12.10, OpenSSL 1.1.1l FIPS 24 Aug 2021
Using virtual files plugin: suffix
fedora-5.13.15-200.fc34.x86_64
```

Client package (From ownCloud or distro) (Linux only): `$ dnf list owncloud*`
```
Last metadata expiration check: 3:11:51 ago on Fr 17 Sep 2021 11:53:03.
Installed Packages
owncloud-client.x86_64                             2.9.0-5150          @owncloud
owncloud-client-nautilus.x86_64                    2.9.0-5150          @owncloud
owncloud-client-nemo.x86_64                        2.9.0-5150          @owncloud
owncloud-client-overlays-icons.x86_64              2.9.0-5150          @owncloud
```

Installation path of client:
`/opt/ownCloud/ownCloud/bin/owncloud`

**Comment by TheOneRing** [comment]
Same as #9052
