### ISSUE TITLE
Expose the use of VFS through the user-agent on PROPFINDs

### ISSUE THREAD

**Issue by SamuAlfageme** [owncloud/client#9061]
In order to measure the adoption and rollout status of VFS as a feature, it'd be interesting to log those requests made by the client in a way they're easily identified. 

The user-agent is a non-intrusive way of exposing this information on the server logs, without the need for the client to push it to a central service itself. 

Since the sync client can support multiple accounts and each of them, several sync folders with one of the two modes enabled (either "classical" selective sync or VFS). I suggest a `(vfs)` suffix that could be included in the user-agent string to label these requests somehow. e.g. 

```
192.168.1.56 - salfagem [20/Sep/2021:11:40:31 +0200] 
"PROPFIND /cernbox/desktop/remote.php/webdav/home/Pictures HTTP/1.1" 207 2045 "" "Mozilla/5.0 (Macintosh) mirall/2.9.0 (build 5137) (cernbox)"
[...]
192.168.1.56 - salfagem [20/Sep/2021:11:48:45 +0200] 
"PROPFIND /cernbox/desktop/remote.php/webdav/home/myLargeFiles HTTP/1.1" 207 4065 "" "Mozilla/5.0 (Macintosh) mirall/2.9.0 (build 5137) (cernbox) (vfs)"
```

Here, one can easily tell that the user is syncing the `myLargeFiles` folder à la VFS and `Pictures` in the old mode.

**Comment by TheOneRing** [comment]
Not that easy.
We should rather look into support of https://api.kde.org/frameworks/kuserfeedback/html/index.html

**Comment by SamuAlfageme** [comment]
Reopening as still relevant to evaluate the user-adoption of VFS as feature
