### ISSUE TITLE
QtKeyhcain: DeletePasswordJob with KWallet does not delete, but creates an empty entry instead

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9064]
https://github.com/owncloud/client/issues/9019#issuecomment-923820728
> 
> 
> I had a quick look:
> 
> 2.8.1 creates a password entry in the format of `username:https://host/:0` with the password, nothing else.
> 
> The 2.9 branch reads this, and then tries to delete a nonexistant `username:https://host/` entry. For some reason (`removeEntry` seems to be dead code), QtKeychain instead calls `writePassword` with empty data, so it creates an empty entry instead of doing nothing...
> 
> On top of that QtKeychain bug there is another weirdness which I can't explain so far: The account is "offline" immediately after migration, and I need to restart the client to trigger a connection. Could be some missing signal emission or something like that.

Are you using the appimage? Where there warnings from qtkeychain?

**Comment by Vogtinator** [comment]
> Are you using the appimage?

No, I built from the 2.9 branch manually, against `libqt5keychain1-0.12.0-2.5.x86_64`.

> Where there warnings from qtkeychain?

Only `Could not load qtkeychain translations`

**Comment by TheOneRing** [comment]
So I had issues before but it turned out that my qtkeychain was build without support for lib secret.
```08-20 13:35:43:674 [ debug default ] [ LibSecretKeyring::deletePassword ]: static bool LibSecretKeyring::deletePassword(const QString&, const QString&, QKeychain::JobPrivate*)```

So the client switched between libsecret and gnome keything, and lost the pw on the way.

**Comment by Vogtinator** [comment]
I'm using kwallet and it's using the kwallet methods in qtkeychain properly.

My theory is that https://github.com/frankosterfeld/qtkeychain/blob/c729d0bc3a7d0932cbcacc773a98ea8660064fc0/keychain_unix.cpp#L520 is never reached because `mode` is always either `Text` or `Binary`. That's a bug which owncloud-client could only work around by just not attempting to delete keys unfortunately

**Comment by Vogtinator** [comment]
Done: https://github.com/frankosterfeld/qtkeychain/issues/199

Working around that in the client should be possible by not reading the old password twice

**Comment by TheOneRing** [comment]
Fixed in 0.13.1.
Will be part of 2.10 for app images.
@fmoc anything needed for obs?

**Comment by TheOneRing** [comment]
https://github.com/frankosterfeld/qtkeychain/issues/199
