### ISSUE TITLE
Multiple number of conflicts instead of one

### ISSUE THREAD

**Issue by swoichha** [owncloud/client#9066]
### Description
After https://github.com/owncloud/client/pull/9011 has been merged we now get numbers as well in `Not Synced`. Due this test "Syncing a file from the server and creating a conflict" was failing. While fixing this test according to the new UI design I came across this issue. When we run this test using squish instead of (1) conflict we get multiple repetative conflicts.

### Steps to reproduce
1. For user "Alice" upload a file "conflict.txt" on the server with content "server content" 
2. Add user "Alice" to client with default setting
3. Wait for file "conflict.txt" to be synced
4. Paused the file sync
5. Chang the content of local file "conflict.txt" to "client content"
6. Change the content  of "conflict.txt"  on the server to "changed server content" 
7. Resume the file sync on the client
8. Click on the activity tab and select the not synced  tab

OR,

1. Run this test using squish https://github.com/owncloud/client/blob/master/test/gui/tst_syncing/test.feature#L29-L51 

### Expected behaviour
Only one conflict should be displayed  like this `Not Synced (1)

### Actual behaviour
More than one conflicts is shown. It is not persistent sometimes it shows (3) sometimes (5) or (7). Following is the screenshot of this issue. 
![Screenshot from 2021-09-16 14-40-22](https://user-images.githubusercontent.com/17021686/134165575-92ca8409-348d-421a-8a2c-9b7e5b9c0fd4.png)

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version: 2.9.0

Operating system: Ubuntu 20.04

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

**Comment by TheOneRing** [comment]
So in 2.9 we are expecting 1-2 issues.
On the first encounter when the issue file is created we expect two issues.
1. for the occurrence of the conflict
2. for the creation of the conflict file

On the screenshot I also see one hidden file that is excluded.
The third issue here could be an older conflict? I cant see the path.

If you select all entries and use the context menu to copy to clipboard, I could see some more information.

**Comment by swoichha** [comment]
@TheOneRing The  hidden file that is excluded is from creating user with default attributes and without skeleton files using middleware which can be fixed. 

In this screenshot there are 4 conflicts but sometimes I also got 5 or 7 conflicts.

I'll copy it to the clipboard and send you the information.
