### ISSUE TITLE
Sync Fail: "error updating metadata: could not create file handle"

### ISSUE THREAD

**Issue by Megagoth1702** [owncloud/client#9070]
### Expected behaviour
Sync should work as expected, keeping folders which are selected as "always keep on this device" updated.

### Actual behaviour
Sync process fails, I get the
`error updating metadata: could not create file handle` on files, which exist or don't exist
message. Only way to reliably sync, is to disable virtual file support and manually select folders to be synced.

### Steps to reproduce
Unfortunately I have no idea how to reproduce this. It suddenly started happening weeks ago and I can not recall what changed. I just started seriously looking into it. :(

### Client configuration
Client version: 2.9.0

Operating system: Win 10

OS language: English

Installation path of client: C:\Program Files\ownCloud

### Logs
Deleted after issue was solved.

**Comment by TheOneRing** [comment]
I had a look on your logs:
``` could not make handle for "xxx/SOUND LIBRARY - RECORDINGS" "WindowsError: ffffffff80070005: Access is denied."````

And many more like that, can you have a look on the Windows permissions of that folder.

Not the permissions in:
![image](https://user-images.githubusercontent.com/200626/134311403-222cbaac-dca0-4c18-966b-6f5c42b5c137.png)

but in:
![image](https://user-images.githubusercontent.com/200626/134311934-35798f6d-a637-41b0-80ef-1e1e501f4221.png)

**Comment by Megagoth1702** [comment]
Hey,
thank you a lot for your response! My permissions look like the ones you showed in the screenshot. I have added "Full Control" to users & authenticated users, will see how it goes. Before this, every box besides "full control" was checked. 

Also, weirdly enough, I tried removing the "read only" from your first screenshot for the synced folder, it did something, but if I opened properties again, the checkmark was back. :D Maybe this other method of setting permissions will work. :) 

Will get back to you after 1TB of data is done being marked & I can restart the sync process.

**Comment by TheOneRing** [comment]
Is D: a normal ntfs drive or a network drive or is anything else special with it.

**Comment by Megagoth1702** [comment]
It's a USB connected external drive.

**Comment by Megagoth1702** [comment]
Solved! Changing the permissions to "full control" for "users" & "authenticated users" worked. Thank you very much!
