### ISSUE TITLE
[GUI-tests] get rid of multiple sync-path settings

### ISSUE THREAD

**Issue by individual-it** [owncloud/client#9072]
Currently we are using two settings for the client to sync files to `CLIENT_SYNC_PATH_USER1` and `CLIENT_SYNC_PATH_USER2` in the feature files we have to use `%client_sync_path_user1%` and `%client_sync_path_user2%`
This is an issue because long-term two path will not be enough, the amount will grow, and every-time someone writes a Scenario that needs a not-conflicting path, changes need to be made in a lot of places.
I suggest to have only one setting `CLIENT_SYNC_PATH_ROOT` and everywhere its used for real add the corresponding username to the path. e.g. set `CLIENT_SYNC_PATH_ROOT=/tmp/client-bdd/` and where `%client_sync_path%` is used in the scenario it will translate to `/tmp/client-bdd/Alice`

**Comment by saw-jan** [comment]
Done in PR https://github.com/owncloud/client/pull/9123
Merging PR didn't automatically close.
