### ISSUE TITLE
[QA] 2.9.1daily20210923 regression: folder detected as managed by another client

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9075]
- stop client 2.9.1daily20210920 with an existing account 
- update to 2.9.1daily20210923 (build 5245)
- start client 

Result:
Error popup is shown: 
![error_managed_by_other_client](https://user-images.githubusercontent.com/75983861/134462210-a9d7ca9f-5d22-493e-95ee-49692aaf4920.png)

[20210923_0813_owncloud.log.0.gz](https://github.com/owncloud/client/files/7215352/20210923_0813_owncloud.log.0.gz)

**Comment by TheOneRing** [comment]
Supposed to be fixed in tomorrows builds

**Comment by gabi18** [comment]
Test scenarios on Windows 10 20H2 VFS ON
 
- Update client 2.9.0 to 2.9.1daily20210927.5255
-> no error, no "Remove all files" popup
- stop client, start testpilot 2.9.1daily20210927.5256
-> no error, no attempt to remove files

- Update client 2.8.2 to 2.9.0 to 2.9.1daily20210927.5255
-> no error
- stop client, start testpilot 2.9.1daily20210927.5256
-> no error
