### ISSUE TITLE
Use proper id for WinVfs registration

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9092]
Starting with 2.10 we should use an id as documented in 
https://docs.microsoft.com/en-us/uwp/api/windows.storage.provider.storageprovidersyncrootinfo.id?view=winrt-20348#Windows_Storage_Provider_StorageProviderSyncRootInfo_Id
`[Storage Provider ID]![Windows SID]![Account ID]`

As far as we know it is not easily possible to update an existing folder but newly registered should use the correct format.

**Comment by erikjv** [comment]
Posted a question on msdn, asking for the purpose of the id, and how to use/format the last part. See https://learn.microsoft.com/en-us/answers/questions/1183563/(cfapi)-what-is-storageprovidersyncrootinfo-id-use .

**Comment by saw-jan** [comment]
Looks like only code refactoring. Nothing is to be tested manually. Moving to Done
CC @TheOneRing
