### ISSUE TITLE
Enable cloudproviders in linux builds

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9097]
Provide the required dependencies on the linux builders and pass
`-DWITH_LIBCLOUDPROVIDERS=ON` this will make cloud providers a required dependency and we can't forget about it.

**Comment by TheOneRing** [comment]
Dependency added in the ci (once the docker build succeeds again)
Missing in the linux repos and craft.

**Comment by fmoc** [comment]
The linux builds install libcloudproviders as a distro dependency now.

**Comment by TheOneRing** [comment]
Are the package templates also updated?

**Comment by fmoc** [comment]
Except for CentOS 7, all distros provide at least some version of libcloudproviders. Do we still target 2.10 (which still includes CentOS 7) or should we move to the next milestone?

**Comment by TheOneRing** [comment]
@fmoc  can we close it?

**Comment by fmoc** [comment]
I'll close it when the builds really work. We had some build issues, I have to update the images, then build the binaries to be able to confirm everything works.

**Comment by fmoc** [comment]
Confirmed fixed. 2.11+ builds have libcloudproviders enabled.
