### ISSUE TITLE
when app crashes during UI tests a backtrace would be helpfull to show

### ISSUE THREAD

**Issue by individual-it** [owncloud/client#9103]
In the case of an app-crash e.g. https://drone.owncloud.com/owncloud/client/9208/6/13 line 12114 we don't have any information about why the app crashed. 
![grafik](https://user-images.githubusercontent.com/2425577/135434917-97d338b4-8a7b-464e-9109-1ff0984c2720.png)

Showing the backtrace for this kind of cases would be very helpful for the developer.
Maybe we can implement this in CI: https://kb.froglogic.com/misc/getting-backtraces-on-linux/

**Comment by Talank** [comment]
The `test.stackTrace()` method in squish api could be helpful https://doc.froglogic.com/squish/latest/rgs-squish.html#test.stackTrace-function

**Comment by individual-it** [comment]
@Talank any progress here?

**Comment by Talank** [comment]
No, I haven't had time to look into it lately. May be we will look into it when we finish adding new tests as per the test plan discussed during 2.9 release.

**Comment by Talank** [comment]
@swoichha @saw-jan if you guys want to look into it, please go ahead.

**Comment by individual-it** [comment]
squish 6.7.2 is out https://www.froglogic.com/news/squish-672-release-available-now/?utm_campaign=squish_6_7_2_rel&utm_medium=email&utm_source=rel_email

the change-log says `    Enabled stacktraces for warnings in Squish test results.` maybe that would help

**Comment by individual-it** [comment]
The nighly runs all fail currently with `RuntimeError: startApplication() failed` we need this immediately, so that we can find out what is happening!

**Comment by swoichha** [comment]
@Talank can you look into this?

**Comment by individual-it** [comment]
@Talank the squish server docker container is configured here https://github.com/owncloud-ci/squish
if you need a newer it has to be updated as described in https://github.com/owncloud-ci/squish#update-squish
