### ISSUE TITLE
run smoke and non-smoke tests in one pipeline

### ISSUE THREAD

**Issue by individual-it** [owncloud/client#9104]
currently the app is build and then the smoke tests run, then the app is build again and the non-smoke tests run.

@swoichha @Talank any reason not to run the non-smoke tests in the same pipeline, just after the smoke tests? That would same around 4:30min

**Comment by Talank** [comment]
I think we had a discussion about it few weeks ago. And actually, this PR by @swoichha addresses this issue as well https://github.com/owncloud/client/pull/8987

**Comment by swoichha** [comment]
@individual-it There is already an issue for this https://github.com/owncloud/client/issues/8899 and it has been fixed in https://github.com/owncloud/client/pull/8987

**Comment by individual-it** [comment]
closing because duplicate of #8899
