### ISSUE TITLE
Deployment of outdated translations

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9105]
![image](https://user-images.githubusercontent.com/200626/135453742-5ade511c-53a0-4a3c-b0e9-89970e694b15.png)

**Comment by fmoc** [comment]
The translations are provided by Qt. AFAICS, there is no such locale `TW`, but it should probablybe `zh_TW`. Should we just rename the file?

**Comment by TheOneRing** [comment]
I've also seen a related warning when starting up.

We have some special handling for one or two translations we we substitute the translation name.
Maybe we need to do the same with TW

**Comment by fmoc** [comment]
Could you post a link to that code, please?

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/blob/master/src/gui/application.cpp#L672

**Comment by erikjv** [comment]
There is a `client_TW.ts` and a `client_zh_TW.ts`. The first one causes the "unknown", while the second one shows up as 繁體中文. So I think we should just remove the first one (it's also a quarter of the size of the latter).
