### ISSUE TITLE
[QA] testpilotcloud failed to send crash report

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9106]
Seen with testpilotcloud 2.9.1rc1

<img width="703" alt="CleanShot 2021-09-30 at 14 22 52@2x" src="https://user-images.githubusercontent.com/75983861/135456846-0c1e919b-efb8-40b0-9178-e27c2802511a.png">

```
MacBook-Pro-15 ~ % /Applications/testpilotcloud.app/Contents/MacOS/testpilotcloud --debug  
Dump file was written to: /private/var/folders/mt/pxxsr98x4bl15__ftqtbc4dr0000gn/T/380A7780-9DB3-48FD-B6A7-60181E6E0902.dmp
michaelstingl@Michaels-MacBook-Pro-15 ~ % RESPONSE: ""
Error: 301 "Protocol \"\" is unknown"
```

**Comment by TheOneRing** [comment]
At the moment the asumtion is that we do not set the crash reporter url....

**Comment by TheOneRing** [comment]
Fixed in the theme
