### ISSUE TITLE
Client certificate support

### ISSUE THREAD

**Issue by node13h** [owncloud/client#9111]
Support for client certificates has been removed in 2.9 as the feature never been officially supported. That's fair, but please consider bringing it back as a supported feature.  
Client certificates provide a valuable additional layer of protection. With the certificate check implemented on the reverse proxy level, the ownCloud server would stay protected even in cases of 0-day ownCloud vulnerabilities.

**Comment by tvdmitrii** [comment]
No way! Was it removed? Why? Man, I do not understand why this feature is so hard to come by. It is THE way to secure your home deployment. I really do not want to go back to nextcloud, but they do support it.
