### ISSUE TITLE
Investigate removal of unused `Multifolders` settings

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9117]
`Multifolder` was introduced in https://github.com/owncloud/client/commit/61b4da944c6d45332de3ebadbd6a80985719109a#diff-4b086fafd9fc04284b2316ff9b3a2cdc787fbb8ae8d0b296570ef02d067ec311R612

The whole structure of the settings should be redesigned.
Possible overlap: https://github.com/owncloud/client/issues/9128

TODO:
- Investigate why we still create new folders with the `_saveBackwardsCompatible` mode
- Find out if there are scenarios where we have  `Multifolder` settings
- If possible remove `Multifolder` from the already complex settings code

**Comment by fmoc** [comment]
Investigation time boxed to 3 hours. Should you exceed this limit, we need to re-evaluate the problem in the next sprint.

**Comment by erikjv** [comment]
The best "explanation" is in a comment that I removed in #10982 :
```
        // The folder is saved to backwards-compatible "Folders"
        // section only if it has the migrate flag set (i.e. was in
        // there before) or if the folder is the only one for the
        // given target path.
        // This ensures that older clients will not read a configuration
        // where two folders for different accounts point at the same
        // local folders.
```
So I think we can remove the saving, but keep on loading it for the time being.

**Comment by erikjv** [comment]
After chatting with @TheOneRing , this comment refers to a feature that we do not support anymore: having 2 accounts syncing to the same folder, which thereby keeps 2 servers in sync. We don't support that, so any references to `Multifolders` can be removed.
