### ISSUE TITLE
Broken linux dependencies on centos 8 and openSUSE

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9126]
> Errors seen while installing on Centos:8:
> 
> ```
> Error:
>  Problem: conflicting requests
>   - nothing provides nemo-python needed by owncloud-client-nemo-2.9.1~rc1-5270.x86_64
> (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> Last metadata expiration check: 0:00:43 ago on Wed Oct  6 09:43:58 2021.
> Error:
>  Problem: conflicting requests
>   - nothing provides caja-python needed by owncloud-client-caja-2.9.1~rc1-5270.x86_64
> (try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
> |CentOS_8| owncloud-client-2.9.1~rc1-5270.x86_64
> |CentOS_8| package owncloud-client-dolphin is not installed
> |CentOS_8| owncloud-client-nautilus-2.9.1~rc1-5270.x86_64
> |CentOS_8| package owncloud-client-nemo is not installed
> |CentOS_8| package owncloud-client-caja is not installed
> ```
> 
> @gabi18 do we need to fix dependencies, or is this just not available on centos?

It seems that ``nemo-python`` is not available for CentOS 8 (only for CentOS 7) and I cannot find ``caja-python`` at all.

_Originally posted by @gabi18 in https://github.com/owncloud/client/issues/9079#issuecomment-936186844_

**Comment by fmoc** [comment]
Builds are done, now we'll have to wait for the deployment to the download server. Meanwhile, I'll open an issue over at the docs repo.
