### ISSUE TITLE
Regular Quota PROPFIND request should not be separate

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#9143]
### Expected behaviour
Reduce `PROPFIND` requests to the server to the minimal level.

The quota request should be part of the ETag query that also happens frequently. It should not be a separate request.
At least it should make use of the configurable poll frequency that we have since 2.9.0.

### Actual behaviour
A `PROPFIND` asks for the current quota on the server every 30 seconds.

### Steps to reproduce
1. Start mitmproxy and have your client run through that.
2. Filter for PROPFINDs and see that it polls for quota.

### Client configuration
Client version: 2.9.1

Operating system: Linux

### Logs

`PROPFIND` requests go out every 30 seconds on the sync root:
```
<?xml version="1.0" encoding="utf-8"?>
<d:propfind xmlns:d="DAV:">
  <d:prop>
    <d:quota-available-bytes/>
    <d:quota-used-bytes/>
  </d:prop>
  M
</d:propfind>
```

**Comment by TheOneRing** [comment]
Does no longer happen with ocis, no quota support with ocis at the moment.
