### ISSUE TITLE
Batch WebDAV calls for DELETE

### ISSUE THREAD

**Issue by guruz** [owncloud/client#917]
(This is more of a RFC right now..)

Whenever we need to do a DELETE (or MOVE or...) on multiple files in a directory, we need to send a request to the server for each file. The roundtrip for that kills performance, especially with slow file backends server side.

Microsoft specifies a BDELETE (batch delete) command http://msdn.microsoft.com/en-us/library/exchange/aa142716(v=exchg.65).aspx that allows to delete multiple files (in a single folder?) with one command.

We could implement this and use it to improve performance.

Things making this hard are probably the handling of error cases when some files were deleted, but some files were not.
We can find out if the server supports it using the OPTIONS verb.

Any comments @ogoffart @evert @dragotin

**Comment by DeepDiver1975** [comment]
will not happen ....
