### ISSUE TITLE
Include architecture in AppImage and MacPkg artifacts

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#9185]
The craft-provided AppImages our CI/CD environment builds emit the architecture. Typically, AppImages follow the scheme `<name>[-<version>]-<arch>.AppImage`, e.g., `someapp-x86_64.AppImage`. This is the only way to make transparent to users which architectures the AppImage works on. Other packages, e.g., Linux packages or MSI bundles, also embed an architecture.

I suppose we need to change this in craft, @TheOneRing?

**Comment by TheOneRing** [comment]
At the moment we only use the provided by the src job.
https://gitea.owncloud.services/client/build/src/branch/2.10/craft.ps1#L18

**Comment by fmoc** [comment]
Done.
