### ISSUE TITLE
[QA] symbol lookup error testpilotcloud-2.9.2-rc2.5886.AppImage on CentOS 8

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9192]
The testpilotcloud 2.9.2-rc2 AppImage doesn't work on Centos 8.

Steps to reproduce:
- run testpilotcloud-2.9.2-rc2.5886.AppImage
-> testpilot starts, connection dialog opens
- try to connect to demo.owncloud.org
-> testpilot terminates 

![centos8-appimage](https://user-images.githubusercontent.com/75983861/139853370-f41b4e36-0804-4143-a67d-800fcf237caf.png)

[testpilot.log](https://github.com/owncloud/client/files/7465707/testpilot.log)

**Comment by fmoc** [comment]
Cannot reproduce on CentOS 8.5.2111 with kernel 4.18.0-348.el8.x86_64. Please provide the distribution's version as exactly as you can. You can use `cat /etc/centos-release` respectively `uname -r`.

**Comment by TheOneRing** [comment]
2.9 is still build on an ubuntu 18.04 the failure on centos is expected. It occurs as ubuntu 18.04 is to new compared with centos...

**Comment by gabi18** [comment]
> Cannot reproduce on CentOS 8.5.2111 with kernel 4.18.0-348.el8.x86_64. Please provide the distribution's version as exactly as you can. You can use `cat /etc/centos-release` respectively `uname -r`.
tested on: CentOS 8.4.2105 kernel: 4.18.0-305.3.1.el8.x86_64
