### ISSUE TITLE
File not synced 

### ISSUE THREAD

**Issue by ypcyc** [owncloud/client#9194]
Version 2.9.1 build 5500

### Expected behaviour
File should be synced 

### Actual behaviour
File appears in Activity -> Not synced tab

### Steps to reproduce
NA

### Server configuration
Operating system:
Windows 10

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

1. Client 
https://gist.github.com/ypcyc/00ca16dfedd32a8f201a4efb4a944377

**Comment by TheOneRing** [comment]
If you are talking about `.pending-1621883245-20210517_220725391.mp4` the leading . means its `unix hidden` file.
We don't sync hidden files by default because hidden usually means its a system file or a temporary file.

**Comment by ypcyc** [comment]
No, sorry it is vidos2\20211031_130513.mp4   Error says it it's in use.
I have already restarted laptop few times and changed the folder name, but get same error

**Comment by TheOneRing** [comment]
Is any media app running which periodically indexes the media library? 
The log reads like the file gets locked while its being uploaded.... the code there could be optimised but that's still unexpected.

**Comment by ypcyc** [comment]
No, nothing is running

**Comment by TheOneRing** [comment]
Hard to guess what really happens, but the file is locked during the upload.
We can improve the behaviour, which makes sense for large files, however this will still not guarantee to fix the issue.
Something seems to lock the file...

**Comment by TheOneRing** [comment]
The next nightly build is supposed to fix your issue.

**Comment by ypcyc** [comment]
@TheOneRing Thank you for fixing, but that didn't help.
I couldn't find the "nightly" build, instead I found "daily"
https://download.owncloud.com/desktop/ownCloud/daily/2.10/win/

I have also Resource Monitor trying to find process that is locking, but couldn't find any. I think ownCloud returns misleading message. It was only shown used by Video player when I really opened it:
![image](https://user-images.githubusercontent.com/1402005/145673259-36cc4647-5770-4e77-9be4-5d6e6f9bffe6.png)

![image](https://user-images.githubusercontent.com/1402005/145673089-a18752c2-1fca-4461-bcdb-07e298e5e3e8.png)

**Comment by TheOneRing** [comment]
Could you please provide logs with that file and the new version?

**Comment by ypcyc** [comment]
Can I send it to some email? There are some folder names I wouldn't like to disclose here publicly.

**Comment by TheOneRing** [comment]
Could you upload them to https://cloud.owncloud.com/index.php/s/FYcyvrj0Te68WDO

**Comment by ypcyc** [comment]
Done.

**Comment by TheOneRing** [comment]
Thx, in the last commit I only fixed the issue in the one of the chunked uploaders, not in the old one.
https://github.com/owncloud/client/pull/9296
