### ISSUE TITLE
Can't install owncloud-client on Ubuntu 20.04

### ISSUE THREAD

**Issue by TheDoctorT** [owncloud/client#9199]
### Expected behaviour
The client should install normally when following the steps on the [website](https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/download/)

### Actual behaviour
The installation fails

### Steps to reproduce
Install by following the instructions on the website

### Client configuration
Client version: 2.9.1 (the version it's trying to install)

Operating system: Ubuntu 20.04.3 LTS

OS language: Italian

Qt version used by client package: 5.12.10 (once installed)

Client package: Ubuntu_20.04 owncloud-client-2.9.1+oc-5500

### Logs
[Terminal output](https://gist.github.com/TheDoctorT/4f8462d9a0a164a0de37e55c25f823d9)

### Comments
The problem seems to lie with the libicu67 package, which at the moment isn't available for Ubuntu 20.04 LTS. Once I manually downloaded and installed the version for Ubuntu 20.10 from [here](https://packages.ubuntu.com/groovy/libicu67), the installation of owncloud-client happened successfully. At the moment it seems to work without a problem, but I have just done this so the situation might change.

**Comment by michaelstingl** [comment]
I wasn't able to reproduce using Docker:

```
docker run --rm -ti ubuntu:20.04
```

Here are my steps:

```
root@ff9256349f4d:/# owncloudcmd --version
ownCloud 2.9.1 (build 5500) Oct 13 2021 08:34:12
https://github.com/owncloud/client/commit/42fb299cadd56dc5b7f99bb6946f5bed8a53a2eb
Libraries Qt 5.12.10, OpenSSL 1.1.1f  31 Mar 2020
Using virtual files plugin: off
ubuntu-5.10.47-linuxkitroot@ff9256349f4d:/# history
    1  apt update && apt install curl wget sudo gnupg -y
    2  wget -nv https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_20.04/Release.key -O - | sudo apt-key add -
    3  echo 'deb https://download.owncloud.com/desktop/ownCloud/stable/latest/linux/Ubuntu_20.04/ /' | sudo tee -a /etc/apt/sources.list.d/owncloud.list
    4  sudo apt update
    5  sudo apt install owncloud-client
    6  owncloudcmd --version
    7  history
```

**Comment by TheOneRing** [comment]
@TheDoctorT is the rest of the system up to date?
I assume you ran `apt update`?

**Comment by TheDoctorT** [comment]
After browsing for similar issues, I noticed I copied the wrong source from the installation page...
Sorry for wasting your time
