### ISSUE TITLE
Client user is locked in oidc workflow after oidc was disabled at the server

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9205]
Seen with client 2.9.1, server 10.8.0 and openidconnect 2.1.0-rc2

* Enable openidocnnect
* Connect client with a user via odic
* owncloud admin disables the oidc app
* client user tries force sync now. An error appears (as expected)

![image](https://user-images.githubusercontent.com/1108546/141160278-819acf86-941e-49c2-b0b2-30e4e2060e85.png)

The client hangs in an inconsistent state.

* The Account menu thinks we are still logged in, but the server has kicked us.
* The client user cannot log in. After clicking log out, then log in, the client keeps trying oidc. "Re-open Browser" just opens a web UI session.
 
Exepected behaviour: 
* The client enters 'logged out' state.
* other login methods become available to the client user (if nothing else, he should be able to choose basic auth)

**Comment by jnweiger** [comment]
Oauth2 has a similar issue: https://github.com/owncloud/client/issues/8359

**Comment by TheOneRing** [comment]
Downgrading to basic auth is not supported
