### ISSUE TITLE
Possible endless loop when conflict file is locked

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9208]
If the client tries to rename a file to its conflict file name and that file is currently locked, the client fails, still creates an error message and immediately tries again.

The result is a flickering ui and a log full of hundreds of errors.

**Comment by dragotin** [comment]
Same if the a file is locked (ie. in Office) and the user clicks on "Dehydrate files" using Windows VFS. That results in endless loops trying to dehydrate the file which fails until it is unlocked.

**Comment by gabi18** [comment]
Tested ownCloud-2.10.0-daily20211214.6294.x64.msi on Windows10 

Steps done:
- open 'New text file.odt' in LibreOffice
- edit and save

Result:
Client shows 'i' and info that file is locked in 'Not synced' tab
![client-2-10-libreoffice-save](https://user-images.githubusercontent.com/75983861/146154683-5f0c5972-9732-49ed-a798-db833fe76d97.png)

- 'Free up space' on right click on file 'New text file.odt'
Result: Client shows 'i' - no flickering, no endless loop of retry -> OK

- 'Free up space' on folder 'Neuer Ordner (2)'
Result: nothing changed

- Exit LibreOffice
Result: 'New text file.odt'  is synced to server, client shows green check mark -> OK

![client-2-10-libreoffice-close](https://user-images.githubusercontent.com/75983861/146155615-3bd46d9f-7272-40a8-b8b4-4d8f9505c5c2.png)

cloud icon in Explorer for fille 'New text file.odt' -> OK
Spinning icon remains for folder 'Neuer Ordner (2)', also after  'Force sync' -> NOT ok

**Comment by gabi18** [comment]
Tested ownCloud-2.10.0-daily20211216.6305.x64.msi on Windows10 20H2 (Build 19042.1348)

- file opened in LibreOffice
- free up space -> OK, no endless retry (spinning icon for file and folder)
- exit LibreOffice -> folder: cloud icon, file: full file

![2 10-folder+file-ok](https://user-images.githubusercontent.com/75983861/146374053-fb2751e3-1b52-4954-89c9-ac135af69292.png)
