### ISSUE TITLE
Cannot edit expiration date from left to right while creating new public share

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#9218]
When trying to create a new public link share for a file with an expiration date, the month number cannot be edited or deleted at first (up-down arrow keys work).
But the date can be edited from backward i.e. first we have to edit year in order to edit day and month

Is this behavior due to the date validation?

![Screenshot from 2021-11-16 17-56-05](https://user-images.githubusercontent.com/52366632/141983148-2f22f32e-1d6f-402a-b1e0-87efa2377062.png)

Note: while editing already created public share, the above things work (screenshot below)
![Screenshot from 2021-11-16 17-59-51](https://user-images.githubusercontent.com/52366632/141983628-dfe6b963-28a4-4a8f-a6ff-cfd4dc18ed8a.png)

### Expected behaviour
expect the month number to get deleted with the `delete` key

### Actual behaviour
`delete` key doesn't do anything

### Steps to reproduce
1. open public share dialog for a file/folder
2. enable `Set expiration date`
3. try to delete month number with `delete` key or `back-space` key

### Server configuration
Operating system: ubuntu20.04

Web server: `apache2`

Database: `mysql`

PHP version: `7.4`

ownCloud version: `10.8.0 (stable)`

Storage backend (external storage):

### Client configuration
Client version: built from `2.9` branch

Operating system:

OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client [logfile](https://doc.owncloud.com/desktop/latest/appendices/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by TheOneRing** [comment]
Its a QDateEdit, with the German localization here I can delete the month and enter a new value.
However I can't remove the separator which is expected behavior.  You must enter a fully specified date.
