### ISSUE TITLE
Branded migration might migrate the wrong profile

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9224]
Migration from 2.4 might have failed in 2.8.
This resulted in a new configuration used in 2.8.

In 2.9 we fixed the migration, but we migrate the abandoned 2.4 config to 2.9 instead of the 2.8.

This only happened with branded clients, due to the change in the config location in the update from 2.8 to 2.9.

**Comment by gabi18** [comment]
2.4.3 config from AppData\Local
[testpilotcloud.zip](https://github.com/owncloud/client/files/7563426/testpilotcloud.zip)
2.8.2 config from AppData\Roamin
[testpilotcloud.zip](https://github.com/owncloud/client/files/7563431/testpilotcloud.zip)
g

**Comment by gabi18** [comment]
Prerequisite: update testpilot 2.4.3 to 2.8.2
->  in 2 db-files
![2_db-files](https://user-images.githubusercontent.com/75983861/142992268-46ad6182-53ff-4d1c-b57e-80f4c4d9f9ee.png)
-> 2.4.2 config file in AppData\Local, 2.8.2 config file in AppData\Roaming (see https://github.com/owncloud/client/issues/9224#issuecomment-972902038)
-> VFS ON for 2.8.2

Tested update testpilot 2.8.2 VFS ON to testpilotcloud-2.9.2-rc5:
-> confirmed that the correct profile (config file) is taken for migration, VFS remains ON
![vfs-on-2 9 2](https://user-images.githubusercontent.com/75983861/142994171-15d6f751-9e41-443b-bd2f-46ab8a08334e.png)

The config file written to AppData\Roaming/testpilotcloud

**Comment by gabi18** [comment]
Confirmed fixed with testpilotcloud-2.9.2-rc5.6114.x64.msi.
