### ISSUE TITLE
After a db backup was restored on the server the client tries to upload the empty placeholders to the no longer exisitng share

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9230]
After a db failure I restored a backup.
A certain share was no longer existing, the client tried to upload the placeholders to the share location on the server...

**Comment by michaelstingl** [comment]
Did you execute `sudo -u www-data ./occ maintenance:data-fingerprint` after restore?

(see https://doc.owncloud.com/server/next/admin_manual/maintenance/backup_and_restore/restore.html#update-the-systems-data-fingerprint-after-a-backup-is-restored)

**Comment by michaelstingl** [comment]
This needs to work reliable, especially in context of migration from oC10 to oCIS. Maybe involve @jnweiger too…

**Comment by TheOneRing** [comment]
Can't reproduce
