### ISSUE TITLE
Client on linux forcing to use the keyring

### ISSUE THREAD

**Issue by pascal06** [owncloud/client#9231]
Hello,

as said many time here, I think this behaviour is very annoying. These days, I decided to use hardware key (Yubikey) to login into my computer. So yesterday I changed my original password (that was 3 years old !) to a shorter one plus the Yubikey. This morning, after having rebooted my computer, the "keyring" says my password has changed and asked me the old one. So I guess that each time I will change my system password keyring will ask my first password that I used 3, 4, maybe 10 years ago... It's a non-sense for me, sorry.
It could be great I don't know how as I'm not a specialist to remove this behaviour. Thanks a lot in advance.

Pascal

```
$ apt-cache policy owncloud-client
owncloud-client:
  Installé : 2.4.1+dfsg-1
  Candidat : 2.4.1+dfsg-1
 Table de version :
 *** 2.4.1+dfsg-1 500
        500 http://fr.archive.ubuntu.com/ubuntu bionic/universe amd64 Packages
        100 /var/lib/dpkg/status
```
Xubuntu
```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.6 LTS
Release:	18.04
Codename:	bionic
```

**Comment by TheOneRing** [comment]
This appears to be an issue with keyring not the ownCloud client.
Afaik ubutu 20.04 will use libsecret.
