### ISSUE TITLE
Purge sync errors for removed files

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9236]
Seen in 2.9.2-rc5 (and probably earlier versions)

After successful syncing, the client shows the blue (i) instead of the green checkmark icon.
The 'Not Synced' tab reports many files that end in '.owncloud' -- They are historic. They existed on the server due to another bug. But have been removed from the server. Client is running without VFS.

The entries still exist in the local database and cannot be removed there:

[testy:~/damkenCloud] $ sqlite3 .sync_aed5c7dcc5be.db 
SQLite version 3.31.1 2020-01-27 19:55:54
Enter ".help" for usage hints.
sqlite> select * from metadata where path="Scanner_im_Koffer/Kontakte.txt.owncloud";
349034419178290878|39|Scanner_im_Koffer/Kontakte.txt.owncloud|15097359|0|0|0|1444944788|0|86bed4d84e74ee4c7195aacb4490d587|04883803ocuhsyihz2sp|WDNVR|1|0|b858cb282617fb0956d960215c8e84d1ccf909c6|1
sqlite> delete from metadata where path="Scanner_im_Koffer/Kontakte.txt.owncloud";
Error: unknown function: parent_hash()
sqlite> 

Expected behaviour:
 * files that do not exist neither locally nor on the server should never cause an error.
 * it should be possible to manually repair the local database.
 * the blue '(i)' icon should inform the user only about issues, he can fix.

**Comment by TheOneRing** [comment]
Have you restarted the client?

**Comment by jnweiger** [comment]
Seen after multiple restarts of the client. Also reproduced with client 2.9.2.6188

Seen while the client is stopped.
When the client is running, I get the error message: "Error: database is locked"

**Comment by jnweiger** [comment]
Related commit: d43463e6037b3918de90d37cb9f063edd86f0a1b
```
Author: Olivier Goffart <ogoffart@woboq.com>
Date:   Sat Oct 20 13:24:31 2018 +0200

    Database: Add an index on the parent path

    So we can quickly query the items in a parent directory

    This uses a custom slite3 function, which means that when downgrading the client,
    or using another tool to add entries in the database, any insertion in the metadata
    table will produce an error: "unknown function: parent_hash()"
    (This will crash the client 2.5)
```

**Comment by jnweiger** [comment]
Workaround:

* stop the client
* `sqlite3 .sync_*.db `
* `drop index metadata_parent;
* restart client, ...

**Comment by TheOneRing** [comment]
Please don't drop tables, just delete the db or use a selective query.

The client ignores all .owncloud files, that are not placeholders, however .owncloud on the server are not supposed to be present in your db.

The db is from before 2.8 I assume?

**Comment by TheOneRing** [comment]
Steps to reproduce:
* Install 2.7
* Add a file called foo.owncloud (an error will be displayed)
* Install 2.10.0  (foo.owncloud error)
* remove foo.owncloud (the error will still be displayed)
* Update to 2.10.1 (foo.owncloud  will no longer be displayed as an error)
