### ISSUE TITLE
improve documentation on how to run squish tests

### ISSUE THREAD

**Issue by individual-it** [owncloud/client#9247]
- [x] after https://github.com/owncloud/client/issues/9240 gets fixed there might be extra steps for Ubuntu 21.x & master branch
- [ ] different versions of the client needs different versions of Qt & with that also different versions of squish

**Comment by phil-davis** [comment]
QA:team issues should not be marked stale. I made PR #9401

**Comment by phil-davis** [comment]
@Talank I noticed that you have been writing some docs. Are you working on this issue?

**Comment by Talank** [comment]
No it is not the same doc that I was writing, we already have good docs for how to run squish tests, that doc might change after we fix tests in master. Let us keep it open until then.
