### ISSUE TITLE
Move fails with Linux vfs and server encryption

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9251]
Seen with
* client 2.9.2.6188 running on Linux Mint (Ubuntu 20.04) with experimental VFS enabled, connecting to a
* server 10.9.0 beta1 with encyption app 1.5.1, master key option enabled on all storages.

Reproduce
* Connect the client using VFS, wait for the initialy sync to finish.
* Also install owncloud-client-nemo to make the overlay icons work with nemo.
* open the local file browser nemo and navigate to the Photos folder.
  - drag Teotihuacan.jpg.owncloud into the parent folder. The move succeeds.
  - wait 1 minute to make sure all syncing is done.
  - drag Teotihuacan.jpg.owncloud back into the Photos folder. The file appears in Photos, but without any overlay icons.
  - wait 1 minute. Nothing more happens. BAD.
    The file is still in the parent folder with overlay icons, and we now see a copy in the Photos folder wthout overlay icons.
 
![image](https://user-images.githubusercontent.com/1108546/144456444-139a0f04-ee68-4f0f-b71a-1b4dbaea7273.png)

**Comment by TheOneRing** [comment]
Unrelated to encryption. Placeholder vfs doesn't support moves.

**Comment by jnweiger** [comment]
The same with testpilotcloud client 2.9.2 (build 6207) -- this time with log files.
* First, move the file out of the Photos folder (work as expected)
![image](https://user-images.githubusercontent.com/1108546/144466302-c4966786-bad7-4efe-ae87-662b00a2840b.png)
----
* Second move back in, a duplicate appears. BAD
![image](https://user-images.githubusercontent.com/1108546/144466267-f576cb9c-8ffb-4aa2-b29d-acf98744e309.png)


[issue-9251-owncloud.log.zip](https://github.com/owncloud/client/files/7643681/issue-9251-owncloud.log.zip)
[testpilotcloud-logdir.zip](https://github.com/owncloud/client/files/7643682/testpilotcloud-logdir.zip)

**Comment by jnweiger** [comment]
This is a serious defect in the implementation of placeholder vfs.
It is currently an accepted problem, this placeholder VFS is marked experimental.

Feel free to close here.
