### ISSUE TITLE
Settings window has a large minimum size

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9255]
Seen with 2.9.2, 2.9.1 and 2.9.0 on Linux 

The settings window takes up at least 700 pixels vertical size: 

![image](https://user-images.githubusercontent.com/1108546/144582995-c941ad51-fa88-4881-a939-fb7a5e4af359.png)

----
In 2.8.2 the minimum size was a much nicer 368 pixels:

![image](https://user-images.githubusercontent.com/1108546/144583080-400464a9-eeae-4bc6-85eb-8cb5c54fd030.png)

**Comment by TheOneRing** [comment]
```
    const QSize min { 800, 700 }; // When changing this, please check macOS: widgets there have larger insets, so they take up more space.
