### ISSUE TITLE
Can't sync folders previously synced by nextcloud

### ISSUE THREAD

**Issue by juliocoliveira** [owncloud/client#9267]
### Expected behaviour
Be able to sync my documents and pictures and etc

### Actual behaviour
It gives error "This folder is used by different client FolderX"

### Steps to reproduce
1. Install Nextcloud
2. Sync all your folders
3. Remove NextCloud, Install OwnCloud and try to sync the previously synced folders.

### Server configuration
Operating system: Oracle Cloud Linux 8

Web server:  Apache 2.4.37

Database: MySQL 8.0.26

PHP version: 7.2.24

ownCloud version: 10.3.2

Storage backend (external storage): None

### Client configuration
Client version: 2.9.2

Operating system: Windows 10

OS language: english

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs
Too much personal information so i'll not send those.

----------------------------
Already deleted the  .sync_*.db files but does not seems to matter.
I'm unable to remove the errors, the ... button is disabled.
![Capture](https://user-images.githubusercontent.com/6606725/145284903-f40c4665-ce1a-48f5-bf23-4028311d3aae.PNG)

**Comment by juliocoliveira** [comment]
I managed to remove the red warnings by logging out, but if I try to add those folders again the error persists.

**Comment by juliocoliveira** [comment]
I'm also using Icedrive to sync the same folders.
Maybe they are incompatible? Tried to close icedrive but re-add the folders but didn't fixed it.

**Comment by TheOneRing** [comment]
It looks like the folder uses virtual files registered with a different client, in order to use them they need to be unregistered in the original client.
(The error message was supposed to look a bit different.)
If all files in that folder where in sync you could also create a backup of the folder and download them again with our client.

**Comment by TheOneRing** [comment]
At the moment we don't offer such a tool but I like the idea.


So the server does no longer exists, I assume in that case all files are locally available and no files are placeholders?

**Comment by juliocoliveira** [comment]
Yes locally, but still there are stuck with "Sync Pending", this is a windows explorer thing, used by multiple sync clients, and there is no command to remove the sync?
I really don't want to format my windows to remove it.

**Comment by TheOneRing** [comment]
You can try to install nexcloud again, the client will fail to connect but might load the old account locally.
Then select remove account.

If that fails you could try to create a new folder D:\ownCloud\Documents (so just use another folder name) and move all available data there.
