### ISSUE TITLE
Text and icon in tray menu stays wrong

### ISSUE THREAD

**Issue by sfadschm** [owncloud/client#9270]
The windows client tray icon sometimes shows the "idle" state, while the client is still syncing:

![145189629-5d1ccbf9-ce60-4a0a-a466-625d96bb2630](https://user-images.githubusercontent.com/40514119/145452774-e431c949-aa52-4323-9ff8-5f53c3e014c2.png)

This was observed with 2.9.1, I will try to observe and replicate with 2.9.2 from today.

Note: The screenshot was taken during a large upload action with a slow internet connection.
I only use sync folders, not the full sync feature (as this was important info in a previous issue).

Ref.: #7365.

### Expected behaviour
The tray icon should show the "syncing" state while syncing.

### Actual behaviour
It occasionally show the "idle/synced" state.

### Steps to reproduce
1. Install owncloud and add sync folders.
2. Upload a bunch of files.
3. Watch the tray icon.

### Client configuration
Client version: 2.9.1

Operating system: Windows 10 (up-to-date)

OS language: German

Installation path of client: default

**Comment by sfadschm** [comment]
Bump.

**Comment by Salipa-Gurung** [comment]
Tested with `ownCloud version 4.0.0.10468-daily20230321`
oCIS Server: [ocis.ocis-traefik.latest.owncloud.works](https://ocis.ocis-traefik.latest.owncloud.works/)
OS: Windows 10 Pro
| ![Screenshot from 2023-03-21 14-36-27](https://user-images.githubusercontent.com/53458341/226558484-e86dc0a3-ae63-4a18-9ff6-dd581adb2c98.png) | ![Screenshot from 2023-03-21 14-36-48](https://user-images.githubusercontent.com/53458341/226558542-87dfb23d-8d0b-4874-9002-e1d712939e23.png) |
|--|--|
|multiple file sync| single file sync |
| Tray icon mouse over shows "Waiting to start syncing."  | Tray icon mouse over shows "Sync is running." :heavy_check_mark: |

**Comment by TheOneRing** [comment]
Well the icon however is correct, the text not so much

**Comment by Salipa-Gurung** [comment]
Tested with `ownCloud version 4.0.0.10542-daily20230331`
oCIS Server: [ocis.ocis-traefik.latest.owncloud.works](https://ocis.ocis-traefik.latest.owncloud.works/)
OS: Windows 10 Pro
| Uploading all files at once | Uploading files consecutively |
|--|--|
|  ![Screenshot from 2023-03-31 15-02-20](https://user-images.githubusercontent.com/53458341/229079892-04257aae-02ae-4191-839c-c921a9d2e7b6.png) | ![Screenshot from 2023-03-31 15-03-06](https://user-images.githubusercontent.com/53458341/229079992-8da33f7d-6d70-4ce5-99d9-3cffbc3215e3.png) |
| Tray icon shows corresponding state :heavy_check_mark: | Tray icon shows corresponding state :heavy_check_mark: |
| Tray icon mouse over message shows "Sync is running." :heavy_check_mark: | Tray icon mouse over message shows "Waiting to start syncing" :x: |

**Comment by saw-jan** [comment]
Tested with `ownCloud 4.0.0.10627-daily20230413 7757ba`
oCIS Server: [ocis.ocis-traefik.latest.owncloud.works](https://ocis.ocis-traefik.latest.owncloud.works/)
OS: Win10
 ![Screenshot from 2023-04-13 12-39-24](https://user-images.githubusercontent.com/52366632/231678245-ac3f5913-b66a-410d-9af2-084654d1c77d.png) | ![Screenshot from 2023-04-13 12-38-10](https://user-images.githubusercontent.com/52366632/231678238-273b8bd5-6dcf-45f1-aff7-00c1e8d4d28c.png) | ![Screenshot from 2023-04-13 12-44-06](https://user-images.githubusercontent.com/52366632/231679012-50a04cce-594d-43de-82e1-3853aecfc32f.png)
--|--|--
sync singe file :heavy_check_mark: | sync multiple files at once :heavy_check_mark: | sync multiple files consecutively :heavy_check_mark:
