### ISSUE TITLE
List of 'not synced' errors keeps growing

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9294]
Seen with client 2.9.2

Connected to cloud.owncloud.com with my personal account.
In several folders there are errors regarding uploaded .owncloud placeholder files.
I tried to suppress these errors by deselecting the affected folders in my selective sync settings.

It does not help:

![image](https://user-images.githubusercontent.com/1108546/146290654-cf03bed9-7755-402b-9d55-6a36c012aab6.png)

The list of items seems repetitive.

Expected behaviour:
 * each error is only listed once.
 * errors from deselected folders are not shown
 * a clear errors button would be helpful to see, which are new, which are old.
 * (and of course placeholder files should not be uploaded, but that is off topic here)

**Comment by TheOneRing** [comment]
I believe this to be a duplicate but I can't find the original issue.
Also the .placheholder files are the only files affected by this issue.
