### ISSUE TITLE
Fix GUI tests related to virtual file support  

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9303]
After https://github.com/owncloud/client/pull/9291, the tests related to VFS are failing. Normally, the all tests in `tst_vfs` are failing. Also, the following 2 step implementations need to be changed.

```
@When("the user enables virtual file support")
def step(context):
    enableVFSSupport("Enable virtual file support (experimental)...")
```

AND 

```
@Given("the user has enabled virtual file support")
def step(context):
    enableVFSSupport("Enable virtual file support (experimental)...")
```

**Comment by Talank** [comment]
Enable/Disable VFS must be there. It was removed by accident and has been reverted by https://github.com/owncloud/client/pull/9317. So, we should revert test for enable/disable feature. However, we do not need to remove the VRT for enable VFS.

TODO
- [ ] Include test for enable/disable VFS using the dot menu

**Comment by individual-it** [comment]
@Talank #9320 got merged, close this?

**Comment by Talank** [comment]
Fixed by https://github.com/owncloud/client/pull/9320.
