### ISSUE TITLE
Ranaming of virtual files to ignored pattern has undefined result

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9309]
~When a new ignored file is added we need to handle it in the vfs backend in order to display the correct/no icon.~

~However the FolderWatcher does not provide a change event for ignored files.~

When a dehydrated placeholder is renamed to an ignored name, it might no longer be connected to an actual file on the server.

We need to define the behavior.

**Comment by saw-jan** [comment]
Tested with `ownCloud 5.0.0.11734-daily20230816 9e8820`

Linux:
- With VFS off: rename is allowed :heavy_check_mark: 
- With VFS on: renamed is reverted :heavy_check_mark: 

Win:
- With VFS off: rename is allowed :heavy_check_mark: 
- With VFS on: renamed is not allowed :heavy_check_mark: 
![Screenshot from 2023-08-16 18-32-04](https://github.com/owncloud/client/assets/52366632/cb734ca7-486e-4f9a-84a5-7b60a62aaeed)
