### ISSUE TITLE
[QA] Entries in client 2.10.0 RC1 dot menu are missing

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9314]
Seen with client ownCloud-2.10.0-rc1.6315.x64.msi on Windows 10 20H2

The entries "Availability" and "Enable/Disable virtual file support..." are missing on the client dot menu.

![2-10_dot-menu](https://user-images.githubusercontent.com/75983861/147061843-fb3dde2e-8342-4cd4-91f0-16d53294fbd7.png)

Not sure whether it is intended that "Availability" is removed here. I think it should be there to be able to "Free up local space" or "Make always available locally" for the whole sync folder.

**Comment by michaelstingl** [comment]
side-effect from https://github.com/owncloud/client/pull/9291 ?

**Comment by TheOneRing** [comment]
Not a side effect the sole effect.

**Comment by TheOneRing** [comment]
Indeed valid, sry

**Comment by saw-jan** [comment]
@TheOneRing I still cannot find `Availability` menu in `client 2.10.0rc2`

**Comment by michaelstingl** [comment]
> @TheOneRing I still cannot find `Availability` menu in `client 2.10.0rc2`

Removed intentionally. Only Enable/Disable VFS must be there.
