### ISSUE TITLE
GUI test for changing expiration date fails

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9321]
Two of the tests that changes expiration date is failing in drone as well as locally. These scenarios are in `tst_sharing` feature
1. user changes the expiration date of an already existing public link using webUI
2. user changes the expiration date of an already existing public link for folder using client-UI

Also, both scenarios were tagged issue https://github.com/owncloud/client/issues/8733.

### Error message in CI
```
[
    {
        "Error Details": "Exception: Step execution through test middleware failed. Error: AssertionError [ERR_ASSERTION]: Expiry Date Mismatch: [object Object]\n    at Object.assertUserLastPublicShareDetails (/drone/src/middleware/src/helpers/sharingHelper.js:431:16)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /drone/src/middleware/src/app.js:66:7",
        "Feature": "Sharing",
        "Feature File": "tst_sharing",
        "Scenario": "user changes the expiration date of an already existing public link using webUI",
        "Test Step": "Then the fields of the last public link share response of user \"Alice\" should include on the server"
    },
    {
        "Error Details": "Exception: Step execution through test middleware failed. Error: AssertionError [ERR_ASSERTION]: Expiry Date Mismatch: [object Object]\n    at Object.assertUserLastPublicShareDetails (/drone/src/middleware/src/helpers/sharingHelper.js:431:16)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /drone/src/middleware/src/app.js:66:7",
        "Feature": "Sharing",
        "Feature File": "tst_sharing",
        "Scenario": "user changes the expiration date of an already existing public link for folder using client-UI",
        "Test Step": "Then the fields of the last public link share response of user \"Alice\" on the server should include"
    }
]
````
REF: 
- https://drone.owncloud.com/owncloud/client/10150/5/14
- https://drone.owncloud.com/owncloud/client/10151/5/14

### Error while running locally
For some reason Squish can change the value of day but not month and year in the expiration date change field.

![Screenshot from 2021-12-28 14-57-28](https://user-images.githubusercontent.com/27364813/147549928-2c5565c1-b1b1-4a71-a6f8-88af49cc1f34.png)

**Comment by individual-it** [comment]
we have now multiple tests skipped because of this issue, lets increase the prio for it and fix it

**Comment by Talank** [comment]
We can not modify the expiration date properly. The workaround that was already implemented was to modify year first. But even of we do so, the modification of expiration date is not being done properly. The only good way to do it is to open the datepicker and automate the date modification with the help of datepicker.

**Comment by Talank** [comment]
fix PR has been merged
