### ISSUE TITLE
File creation GUI tests fails saying file changed during sync

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9325]
As of the error in Scenario `Syncing a file to the server`, the file is not synced where the not synced tab says that the file changed while uploading.
![Screenshot from 2021-12-28 17-01-52](https://user-images.githubusercontent.com/27364813/147561194-9ce9eddf-7cf2-411b-81b5-7efc8da6d285.png)

_Originally posted by @Talank in https://github.com/owncloud/client/issues/9281#issuecomment-1002033359_

**Comment by Talank** [comment]
Note that 2 of the failing tests tagged with #9281 are because of this issue. Those tests are as follows: 
```
6 | {
7 | "Error Details": "Exception: Step execution through test middleware failed. Error: AssertionError [ERR_ASSERTION]: File should have content \"test content\", but found \"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<d:error xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\">\n  <s:exception>Sabre\\DAV\\Exception\\NotFound</s:exception>\n  <s:message>File with name lorem-for-upload.txt could not be located</s:message>\n</d:error>\n\"\n    at fileShouldHaveContent (/drone/src/middleware/src/stepDefinitions/webdavContext.js:36:17)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /drone/src/middleware/src/app.js:66:7",
8 | "Feature": "Syncing files",
9 | "Feature File": "tst_syncing",
10 | "Scenario": "Syncing a file to the server",
11 | "Test Step": "Then as \"Alice\" the file \"lorem-for-upload.txt\" on the server should have the content \"test content\""
12 | },
13 | {
14 | "Error Details": "Exception: Step execution through test middleware failed. Error: AssertionError [ERR_ASSERTION]: File should have content \"test content\", but found \"<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<d:error xmlns:d=\"DAV:\" xmlns:s=\"http://sabredav.org/ns\">\n  <s:exception>Sabre\\DAV\\Exception\\NotFound</s:exception>\n  <s:message>File with name Folder1/really long folder name with some spaces and special char such as $%\u00f1&amp;/test.txt could not be located</s:message>\n</d:error>\n\"\n    at fileShouldHaveContent (/drone/src/middleware/src/stepDefinitions/webdavContext.js:36:17)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:95:5)\n    at async /drone/src/middleware/src/app.js:66:7",
15 | "Feature": "Syncing files",
16 | "Feature File": "tst_syncing",
17 | "Scenario": "Verify that you can create a subfolder with long name",
18 | "Test Step": "And as \"Alice\" the file \"Folder1/really long folder name with some spaces and special char such as $%\u00f1&/test.txt\" on the server should have the content \"test content\""
19 | }
```

**Comment by Talank** [comment]
One of the failing scenario is as follows:
```feature
Scenario: Verify that you can create a subfolder with long name
        Given user "Alice" has set up a client with default settings
        And user "Alice" has created a folder "Folder1" inside the sync folder
        When user "Alice" creates a folder "Folder1/really long folder name with some spaces and special char such as $%ñ&" inside the sync folder
        And user "Alice" creates a file "Folder1/really long folder name with some spaces and special char such as $%ñ&/test.txt" with the following content inside the sync folder
            """
            test content
            """
        And the user waits for file "Folder1/really long folder name with some spaces and special char such as $%ñ&/test.txt" to be synced
        Then as "Alice" folder "Folder1" should exist on the server
        And as "Alice" folder "Folder1/really long folder name with some spaces and special char such as $%ñ&" should exist on the server
        And the file "Folder1/really long folder name with some spaces and special char such as $%ñ&/test.txt" should exist on the file system with the following content
            """
            test content
            """
        And as "Alice" the file "Folder1/really long folder name with some spaces and special char such as $%ñ&/test.txt" on the server should have the content "test content"
```

And in the step to create file with `test content`, if I wait exactly 5 sec before creating the file with python (as done [here](https://github.com/owncloud/client/blob/bfa988779de6fc08edf905f0d3780dd3db893af2/test/gui/shared/steps/steps.py#L379)), then the file is synced properly. Otherwise the not sync tab says that the file changed while syncing and then never gets synced (at least not until the default timeout of the GUI tests).

If I create a python script to create a file just like it is done in the squish tests, then the file gets synced. May be the problem exists when I run the script to recently created user (I haven't checked it yet).

**Comment by Talank** [comment]
I performed git bisect to know since when the test actually failed. And it turned out that the first bad commit is `4ba37025f4b5ac4a2a6cde6aac7d4a5896cfbac1` Here is the detailed bisect log.

```log
# bad: [56057b563d117395452945742703c5946c20bd7e] [Tests-Only] Reverted removed steps of VFS tests (#9320)
git bisect bad 56057b563d117395452945742703c5946c20bd7e
# good: [dca00fcc15e7c972472648e9403a993b75e32c08] [tx] updated client translations from transifex [skip ci]
git bisect good dca00fcc15e7c972472648e9403a993b75e32c08
# bad: [16c0139c9fde0561abec6fc4fe7a3ab48930952d] Handle file locks with deletes
git bisect bad 16c0139c9fde0561abec6fc4fe7a3ab48930952d
# good: [c8dd64d8fdd8913341b498d4c18da64dadbf8523] [Tests-Only] add test for folder sync (#9280)
git bisect good c8dd64d8fdd8913341b498d4c18da64dadbf8523
# bad: [6300c004300655c2de18da42766a547137217f8a] [tests-only]add tests for sharee editing files/folder (#9282)
git bisect bad 6300c004300655c2de18da42766a547137217f8a
# bad: [f77ab8804378f925cebae2ad50f3068d82b9a6e3] Run tests with full debug log
git bisect bad f77ab8804378f925cebae2ad50f3068d82b9a6e3
# bad: [4ba37025f4b5ac4a2a6cde6aac7d4a5896cfbac1] Restart oauth on error
git bisect bad 4ba37025f4b5ac4a2a6cde6aac7d4a5896cfbac1
# first bad commit: [4ba37025f4b5ac4a2a6cde6aac7d4a5896cfbac1] Restart oauth on error
```

**Comment by TheOneRing** [comment]
Regarding this issue, this can happen if:
We schedule a file to be synced but are busy with other tasks once we are getting ready to upload the file we check whether the file is still the one we scheduled.
If it changed we abort the upload and wait for the next sync.

What might have changed recently is that if this happens 3 times in a row, the file is ignored for an increasing amount of time.

**Comment by Talank** [comment]
For how many seconds/minutes do we have to wait for the next sync? What I didn't understand is why we should wait exactly 5 seconds before creating a file so that it syncs in the first attempt 🤔

**Comment by TheOneRing** [comment]
If a file fails, we mark it as ignored for 5s. If it fails again within the 25s, 5*25, if again 5*5*25...
If you want to test the "changed during upload" scenario, you should wait for the error to be resolved, or force sync.
If you don't want to test it, don't modify the src file to often and not after the sync was started.

Besides the mentioned ignore list there are other random timeouts in the client which are hard to predict.

**Comment by TheOneRing** [comment]
Might break again once https://github.com/owncloud/client/pull/9386 merged.
This is what I was thinking of in https://github.com/owncloud/client/issues/9382#issuecomment-1019827709

**Comment by Talank** [comment]
But the CI passed for the changes https://drone.owncloud.com/owncloud/client/10461 

And if the file sync is immediately retried if it is changed during the discovery, then waiting for extra 5 sec will not break it. However, that extra wait will now be useless, right?

**Comment by TheOneRing** [comment]
The 5s could theoretically go, but I don't think that 5s optimization are worth the work of a pr :)
