### ISSUE TITLE
Fix GUI tests for blacklisted files

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9326]
For the test for blacklisted file `"Then the file \"Folder1/a\\\\a.txt\" should be blacklisted`, the status in not synced tab used to show that the file name is blacklisted. An now , it shows `info`. 
![Screenshot from 2021-12-14 14-46-08](https://user-images.githubusercontent.com/27364813/145967663-5046b0da-839f-43ce-83f9-b9c9ccf2b4bc.png)

_Originally posted by @Talank in https://github.com/owncloud/client/issues/9281#issuecomment-993326243_

Local Soft Errors are no longer promoted to "Blacklist Error" as the icon would change to a red one and it would display a misleading "timeout" period. The change was done with Soft Errors like locked files and blacklisted files.

**Comment by phil-davis** [comment]
@Talank is this still an issue?

**Comment by Talank** [comment]
Yes, it still is an issue, and I think https://github.com/owncloud/client/pull/9398 will fix it.

**Comment by saw-jan** [comment]
Fix PR in progress https://github.com/owncloud/client/pull/9599

**Comment by saw-jan** [comment]
Fix PR merged
Closing here
