### ISSUE TITLE
make CI nightly run tests on 2.10 branch

### ISSUE THREAD

**Issue by individual-it** [owncloud/client#9327]
- [x] nightly builds should run on the 2.10 branch
- [x] template of tests need to have a note saying to update the branch

**Comment by Talank** [comment]
I have added a new cron job in drone with the name `nightly-2-10`

**Comment by Talank** [comment]
The nightly build is running https://drone.owncloud.com/owncloud/client/10186

**Comment by individual-it** [comment]
the reporting of the result to Rocket.Chat does not work yet

**Comment by Talank** [comment]
The rocket chat always shows the result for build https://drone.owncloud.services/client/build/6443 instead of showing the result of the recent nightly builds. The issue is with all the cron jobs.
