### ISSUE TITLE
[QA] COM directory gets synced from server to client

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9332]
While testing https://github.com/owncloud/client/issues/9290#issuecomment-995727781 (under the Folders i.e. 2->14), the folder named "COM" gets synced from server to the desktop client.

### Expected behaviour
A windows client syncs down folder 'COM'

### Actual behaviour
'COM` gets synced

### Steps to reproduce
1. create a folder named COM in server
2. Check if it gets synced to desktop client

### Server configuration
as mentioned in the issue for testplan release desktop 1.10.0

### Client configuration
Client version: Version 2.10.0rc3 (build 6417)

Operating system: Windows 10, Version 1809 (OS Build 17763.379)

**Comment by TheOneRing** [comment]
The restricted file names are:
```
const QLatin1String win_device_names[] = {
    QLatin1String("CON"), QLatin1String("PRN"), QLatin1String("AUX"), QLatin1String("NUL"),
    QLatin1String("COM1"), QLatin1String("COM2"), QLatin1String("COM3"),
    QLatin1String("COM4"), QLatin1String("COM5"), QLatin1String("COM6"),
    QLatin1String("COM7"), QLatin1String("COM8"), QLatin1String("COM9"),
    QLatin1String("LPT1"), QLatin1String("LPT2"), QLatin1String("LPT3"),
    QLatin1String("LPT4"), QLatin1String("LPT5"), QLatin1String("LPT6"),
    QLatin1String("LPT7"), QLatin1String("LPT8"), QLatin1String("LPT9"),
    QLatin1String("CLOCK$")
};
```

**Comment by Talank** [comment]
@gabi18 we should update the testplan for this as well.

**Comment by Talank** [comment]
I also need to refactor the tests added in this PR https://github.com/owncloud/client/pull/9258
