### ISSUE TITLE
refactor test for invalid folder name and long folder name

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9334]
Need to refactor the tests added in this PR https://github.com/owncloud/client/pull/9258

_Originally posted by @Talank in https://github.com/owncloud/client/issues/9332#issuecomment-1006360739_

**Comment by phil-davis** [comment]
@Talank is this still an issue to do?

**Comment by Talank** [comment]
Yes, and it should be a good task for those who are new for desktop client.

**Comment by phil-davis** [comment]
> Yes, and it should be a good task for those who are new for desktop client.

I added it to the backlog project. Please move it to the current sprint when appropriate.

**Comment by sushmita56** [comment]
I'm working on this issue.
