### ISSUE TITLE
server URL with a trailing slash sends the client in an (endless) loop

### ISSUE THREAD

**Issue by individual-it** [owncloud/client#9335]
### Expected behaviour
client should connect if a server URL does not have a trailing `/`

### Actual behaviour
spinning wheel, no connection

### Steps to reproduce
1. build client from master branch
2. add a new account
3. give `http://localhost/owncloud-core` as server URL

### Server configuration
Operating system:
Ubuntu 21.10
Web server: 
apache2
Database:
MySQL
PHP version:
7.4
ownCloud version:
current master

### Client configuration
Client version:
master
Operating system:
Ubuntu 21.10
OS language:
DE
Qt version used by client package (Linux only, see also Settings dialog):
5.15
Installation path of client:
/home/artur/www/client/client-build/bin
### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client [logfile](https://doc.owncloud.com/desktop/latest/appendices/troubleshooting.html#log-files)
  no output
2. wireshark
   a `PROPFIND` request is send to `/owncloud-core/remote.php/webdav/` and gets a 401 reply and that's all
   I believe older clients send two PROPFIND requests 

CC @Talank you said the same issue existed in 2.9? I cannot find an issue in GitHub

**Comment by individual-it** [comment]
P.S. 2.10 seems not to have that problem

**Comment by Talank** [comment]
I think it was discussed while doing changelog testing for 2.9

**Comment by TheOneRing** [comment]
I would need logs with http logs enabled.

**Comment by individual-it** [comment]
cannot reproduce anymore, closing
