### ISSUE TITLE
Rename parent folder while updating file cause alternating "i" icon and check mark

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9342]
If we rename a parent folder and at the same time update content in the file, then it cause alternating "i" icon and check mark icon to appear. The issue is found during the test of 2.10 release as per the [testplan](https://github.com/owncloud/client/issues/9290#issuecomment-996486638)  [REF: Edit Files -> Edit a file while the folder is renaming]

The log files can be found here:
[log_alternating_sync_icon.zip](https://github.com/owncloud/client/files/7838647/log_alternating_sync_icon.zip)

**Comment by TheOneRing** [comment]
```
01-10 03:10:20:704 [ warning sync.propagator ]:	Could not complete propagation of "New folder renamed" by OCC::PropagateLocalRename(0x237a394f180) with status OCC::SyncFileItem::SoftError and error: "Could not rename C:/Users/IEUser/ownCloud3/New folder to C:/Users/IEUser/ownCloud3/New folder renamed, the file is currently in use"
```

However it should be handled by the ignore list.
```
01-10 03:10:23:426 [ info sync.propagator ]:	blacklisting  "New folder"  for  625 , retry count  3
```

Probably again an effect of treating folders totally different than files.

**Comment by TheOneRing** [comment]
Fixed in https://github.com/owncloud/client/commit/b5e4b562fb0cbcde1f62f81fbcbd4c052dda0f85
