### ISSUE TITLE
[QA] testpilotcloud 2.10.0-rc3 not available for update - error for update to 2.10.0-rc2

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9343]
Steps to reproduce:

- install and start testpilotcloud 2.9.2
- change update channel to 'Beta'

Result: 2.10.0-rc2 is available update version instead of 2.10.0-rc3

![update-2-10-0-rc2-available](https://user-images.githubusercontent.com/75983861/148769125-f71f9106-ce8c-4a96-8eea-99c237797246.png)

**Comment by gabi18** [comment]
Further scenario:

- have a testpilotcloud 2.9.1 installed
- start Windows and login

Result: testpilotcloud 2.9.1 is auto started and shows a popup that update to 2.10.0-rc2 failed

![2-9-1-update-fails](https://user-images.githubusercontent.com/75983861/148774123-a91a30bf-bd65-46f6-b4dd-20de6667d0c0.png)

**Comment by gabi18** [comment]
Updating manually to 2.10.0-rc3 works.

**Comment by TheOneRing** [comment]
I'd need logs or any info at all

**Comment by gabi18** [comment]
2.10.0-rc3 is not available -> okay

But update to 2.10.0-rc2 shouldn't show an error.

testpilotcloud log-file when popup "Update failed" is shown:
[20220111_1035_owncloud.log.2.gz](https://github.com/owncloud/client/files/7845435/20220111_1035_owncloud.log.2.gz)

I couldn't get an MSI Installer log. Configured reg-key but didn't get a log-file in %temp%.
![regedit](https://user-images.githubusercontent.com/75983861/148920798-06684627-7881-45e0-8dda-fbc66b79182e.PNG)

**Comment by gabi18** [comment]
After selection "Neustarten  und aktualisieren" the update is done without problems.

**Comment by TheOneRing** [comment]
> 2.10.0-rc3 is not available -> okay
> 
> But update to 2.10.0-rc2 shouldn't show an error.
> 
> testpilotcloud log-file when popup "Update failed" is shown: [20220111_1035_owncloud.log.2.gz](https://github.com/owncloud/client/files/7845435/20220111_1035_owncloud.log.2.gz)
> 
> I couldn't get an MSI Installer log. Configured reg-key according https://docs.microsoft.com/en-us/troubleshoot/windows-client/application-management/enable-windows-installer-logging - but didn't get a log-file in %temp%. ![regedit](https://user-images.githubusercontent.com/75983861/148920798-06684627-7881-45e0-8dda-fbc66b79182e.PNG)

The doc says the key is called `Logging` ?

**Comment by gabi18** [comment]
I also don't get a log-file with key `Logging`.

**Comment by TheOneRing** [comment]
Works here the log file is called `C:\Users\hanna\AppData\Local\Temp\MSI931d3.LOG` but its of course a unique name.

**Comment by gabi18** [comment]
Works here as well today - didn't work yesterday even after reboot.

**Comment by gabi18** [comment]
In general I get MSI logs now - but not in case the "Update failed" popup is shown.

Found while further testing:
The error popup is only shown if a previous update was stopped by answering NO to the question about allowing system access.

Otherwise no error - the update popup is shown: 
![correct-update](https://user-images.githubusercontent.com/75983861/149108274-cfe54b4e-218a-4825-8de5-2197df693046.png)

**Comment by gabi18** [comment]
Confirmed fixed with testpilotcloud-2.10.0rc4 (build 6487) on Win 10 10H2 with testpilotcloud 2.9.2 VFS ON installed (update channel 'Beta')
- 2.10.0-rc4 is provided for update
- update popup is shown after starting testpilotcloud (no error popup)
- update to 2.10.0rc4 works without problems
