### ISSUE TITLE
[QA] No popup keep or delete date after all data are deleted on server

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9360]
Seen with testpilotcloud 2.10.0-rc4 connected to demo.owncloud.org (10.9.0) on Win10 20H2 VFS ON

Steps to reproduce:

- start client, 'Open folder' and create a new document 'NeuesRC4Doc.odt'
-> new doc is uploaded
- wait for full hour when demo.owncloud.org is restarted
- watch client: there isn't any popup that all data on server are deleted and the choice keep or delete

Result: data are downloaded from server and the newly created file is deleted locally without user confirmation

Sync protocol
![2-10-0rc4_sync_activity](https://user-images.githubusercontent.com/75983861/149305024-a77222ad-081a-41cd-9480-2e562f3d5ed2.png)

**Comment by gabi18** [comment]
[20220113_0834_owncloud.log.2.gz](https://github.com/owncloud/client/files/7861728/20220113_0834_owncloud.log.2.gz)
[20220113_0835_owncloud.log.0.gz](https://github.com/owncloud/client/files/7861730/20220113_0835_owncloud.log.0.gz)

**Comment by TheOneRing** [comment]
the popup only happens under certain conditions, in a normal scenario after the full hour the dir is reset to the template which could be identical to the local state.

Only if you have a certain amount of files that all vanish at the same time the pop up is show.

**Comment by gabi18** [comment]
The popup doesn't appear if only one file is affected and will disappear locally?

**Comment by gabi18** [comment]
I get the file on Linux with owncloud-client-2.10.0~rc3-6436.x86_64
![2 10 0-rc3-linux](https://user-images.githubusercontent.com/75983861/149309189-1a58e085-6f26-4123-b44b-5be36d6008ba.png)

**Comment by gabi18** [comment]
I have retested: also on Linux with 2.10.0-rc4 the popup doesn't appear sometimes.

@jw also has observed this behavior and we found an explanation: it's related to demo.owncloud.org:  the skeleton files are immediately recreated and if the client doesn't poll exactly at time all files are deleted it's just a 'normal' server delete and no popup is needed.

**Comment by gabi18** [comment]
Confirmed that the popup appears reliable when deleting all user data on server (remain deleted if not restored automatically).
