### ISSUE TITLE
QtCreators file watcher detects changes on file, caused by ownCloud

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9383]
Create a project using QtCreator.
Modify a file.
Save.
QtCreator claims the file was changed
![image](https://user-images.githubusercontent.com/200626/150746682-7ecb38f6-7813-442a-8871-e7a9e58c6904.png)

**Comment by grgprarup** [comment]
> QtCreator claims the file was changed
> ![image](https://user-images.githubusercontent.com/200626/150746682-7ecb38f6-7813-442a-8871-e7a9e58c6904.png)

I do not see this anymore. It is the expected behavior.

**Comment by michaelstingl** [comment]
> I do not see this anymore. It is the expected behavior?

👍
