### ISSUE TITLE
Ask for confirmation for big folder does not ask when uploading

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9395]
Seen with 2.10.0 (but probably not a regression)

Connect client with server using a size limit of 111MB:
![image](https://user-images.githubusercontent.com/1108546/151355353-ff35905b-3aad-4059-80b0-ba99e66d4fbc.png)

1) Test **download** of a **folder** with 170MB -> OK, it asks, as it should.

![image](https://user-images.githubusercontent.com/1108546/151355409-e2fdc975-81b5-4b18-8866-cc5c574ced25.png)

2) Test **upload** of a **folder** with 170MB -> upload is done without asking.
3) Test **download** of a **file** with 170MB -> upload is done without asking.
4) Test **upload** of a **file** with 170MB -> upload is done without asking.

Is that as designed?

Expected behaviour:
* Both download and upload should ask.
* both files and folders would be logical, but okayish (that the setting only works on folders, as that is how the setting is labeled.)

**Comment by michaelstingl** [comment]
Rename ~synchronize~ ==> download in new wizard @fmoc

**Comment by TheOneRing** [comment]
Works as expected
