### ISSUE TITLE
Implement support for Systray Icon Themes

### ISSUE THREAD

**Issue by ainola** [owncloud/client#940]
While the monochromatic icons look great for Ubuntu's default theme, users of 'Radiance' will find results less than satisfying.
![mono](https://f.cloud.github.com/assets/5383525/1081769/2be19744-157c-11e3-8362-681c8fa21850.png)

**Comment by scic** [comment]
I would really like this feature as well. A black monochrome icon for plasma 5 would be great. (See #2994)

What's the status of this feature? Maybe it should be unassigned again since it has been dormant for 1 year now? Then somebody else could pick it up.

**Comment by DarkknightAK** [comment]
I know you look for an standardized name are the emblems icons vcs-added vcs-added, vcs-conflicting vcs-locally-modified vcs-normal vcs-removed vcs-update-required usefull for this. you can add them at your application icon
