### ISSUE TITLE
"Open local folder" and "Open folder in browser" are not shown in the context menu

### ISSUE THREAD

**Issue by naokton** [owncloud/client#9405]
### Expected behaviour
"Open local folder" and "Open folder in browser" are shown in the context menu when I right click synced sub folders in ownCloud app. This was the behavior of version 2.9.2.

### Actual behaviour
"Open local folder" and "Open folder in browser" are not shown. Instead, "Remove folder sync connection" is shown.

### Steps to reproduce
1. Open ownCloud desktop application
2. Right click synced sub folder

### Server configuration
Operating system:

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage):

### Client configuration
Client version:
2.10.0

Operating system:
Windows Server 2019

OS language:
English

Installation path of client:
C:\Program Files\ownCloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client [logfile](https://doc.owncloud.com/desktop/latest/appendices/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by TheOneRing** [comment]
Could you share a screenshot of what you are talking about?
Names etc can be redacted.

**Comment by naokton** [comment]
Sure. This is version 2.10.0
![image](https://user-images.githubusercontent.com/996594/151829082-95c18d1c-e763-47a4-a65f-d6b147ae29f4.png)

And this is version 2.9.2
![image](https://user-images.githubusercontent.com/996594/151829346-1dd82f79-4cd0-486d-ac6a-2b1e17c8564e.png)

**Comment by TheOneRing** [comment]
@naokton thx for reporting.

@erikjv can you have a look, you recently changed the model index handling.

**Comment by erikjv** [comment]
Can you add a screenshot of what you get when you right-click on the cloud-with-checkmark?

**Comment by naokton** [comment]
@erikjv This is the screenshot. Both version (2.10.0 and 2.9.2) show the same items.

![image](https://user-images.githubusercontent.com/996594/152233971-d80d3fde-6b32-4a48-911e-cac7155a8f44.png)
