### ISSUE TITLE
[QA] desktop client 2.10.0 does not offer update channels

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9419]
Seen in 2.10.0 (build 6519) on win10 V21H1

The setting dialogue has an online updater section. 
In previous versions (screenshot shows 2.8.2 on the right side) it was possible to select between channels Beta and Stable.

In 2.10.0 this selection is no possible.

**Comment by TheOneRing** [comment]
We removed it two years ago from non testpilotcloud clients?
