### ISSUE TITLE
[QA] Account Filter for Server Activity does not do anything

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9425]
Seen on 2.10.0rc3 (build 6436) in Linux Mint

* connect multiple servers.
* wait for server activity messages to come
* view Activity -> Server Activity
* click Filter, three accounts are shown there. Choose one.
* Still Activity messages from all accounts are shown. BAD
 
![image](https://user-images.githubusercontent.com/1108546/152970817-396c8fab-222b-409a-aff8-4f9c09b21eba.png)

The screenhot shows the situation after re-opening the Filter dropdown. The Account column shows accounts not filtered for.

The available filters in the the other tabs (Activity -> Sync Protocol tab and in Activity -> Not Synced) work fine.

**Comment by jnweiger** [comment]
@enbrnz @gabi18 fyi

**Comment by gabi18** [comment]
Also seen with ownCloud 2.10.0 (build 6519) on Windows 10 20H2

**Comment by jnweiger** [comment]
UX improvement ideas:

* Replace "no filter" with "All" (avoid a brain-erors due to double negatives)
* When a filter is active, replace the Label "Filter" on the drop down button with something that indicates that a filter is active.
