### ISSUE TITLE
Waiting for another folder

### ISSUE THREAD

**Issue by mmattel** [owncloud/client#9427]
Using the Desktop Client 2.10 on Windows 10x64

Having two different _accounts_ to sync
When one account syncs, the other account tells that it waits for another _folder_ to be synced, sometimes it tells there are more than one folders to be synced first, see
![image](https://user-images.githubusercontent.com/3321281/153011446-1dcc48d8-aab9-4839-9b5d-afe4d29f89ff.png)
I am asking myself which folder it is waiting for. It would be more expressive if eg the name of the folder it waits for is printed in that line, aka, who is the one in the queue to be finished first before it can start.
Or is it more that it waits for an account to be finished syncing?

@gabi18 @TheOneRing fyi

**Comment by michaelstingl** [comment]
1 account can have multiple sync folder pairs. Worst case, it waits for multiple sync folder pairs in multiple accounts. This is the current architecture.

**Comment by mmattel** [comment]
> waits for multiple sync folder pairs in multiple accounts

Totally ok. imho it is known what is the last folder in the queue before the job can start. The question is, why not printing it on the screen to make it clear to the user?
