### ISSUE TITLE
Owncloud Client don't sync file written in MS Ofice until document is closed

### ISSUE THREAD

**Issue by bojanpog** [owncloud/client#9428]
Now it sync's only when file is closed in MS Office app.

### Expected behaviour
Owncloud client syncs MS Office files whenever file is saved during editing.

### Actual behaviour
Now it syncs and sends to Owncloud server only when file is closed or MS Office is closed.

### Steps to reproduce
1. Open existing MS Word file.
2. Write some new content
3. Save file
4. <File is not synced with owncloud server, no error displayed in client>
5. Close file.
6. Client syncs the file to Owncloud server.

**Comment by HanaGemela** [comment]
Will also be tested in https://github.com/owncloud/client/issues/9829
