### ISSUE TITLE
Single File/Folder delete tests failed after middleware bumping

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9439]
The file/folder delete tests are failing after the numping of middleware. The reasons are is as follows:
- Given there is only one file/folder in the sync directory of current user, after syncing from server. When we delete the file/folder then delete activity is not synced.
- This test, however, used to pass in the previously pinned version of middleware. Because, in the previous version of middleware, the file existance in the server was not compared properly, causing the false pass of the files/folders tests.

_Originally posted by @Talank in https://github.com/owncloud/client/issues/9412#issuecomment-1036206951_

### Possible fix
When a file/folder is deleted, the delete task is not synced unless we trigger a force sync. And while triggering the force sync, it asks for conformation that if we want to delete all files (because we only upload one file which is now deleted). So, I modified the step for force sync as well. The conformation message is as shown in the picture below.

![Screenshot from 2022-02-10 15-07-55](https://user-images.githubusercontent.com/27364813/153377477-019be7ed-ee7d-4cef-8074-837ef415d570.png)

**Comment by saw-jan** [comment]
Fix PR has been merged
