### ISSUE TITLE
1.4.0 forgets server on reboot

### ISSUE THREAD

**Issue by kleinerChemiker** [owncloud/client#945]
OS: Win 7

I just upgraded to 1.4.0 and when the client started after the update it seemed to have a connection to my server, at least it doesn't show an error. But after I restarted my system the client showed an error, that it cannot connect to the server. I "changed" my credentials then and the client could again connect, but now its syncing all the files again. (I hope I dont get tons of duplicates) After another system reboot the client didn't forget the credentials. I could reproduce this problem on another PC too.

If you need any further information, just ask.

**Comment by zb2oby** [comment]
Hello
Same issue with debian jessie and client 2.2.4 on boot and reboot. I can restore config with backup too but it don't really fix the problem. I could execute a script to automatically restore it at boot with my backup version of owncloud.cfg but it is not a very clean solution. If someone have a better way. thanks

**Comment by zb2oby** [comment]
after a systeme update this probleme is resolved on debian jessie with KDE. I don't remember where i've read it could be a probleme with qt. 
During the system update i've effecetively seen a lot of package related to qtkeychain etc..

**Comment by s-light** [comment]
i also can reproduce the 'configuration is gone' if i 'restart'
 - Kubuntu 16.10 - client Version 2.3.1. 
with normal shutdown it is all fine.

**Comment by x7i7l** [comment]
Can confirm also 
system : Ubuntu Budgie 17.04 - client Version 2.3.1

**Comment by btittelbach** [comment]
confirm as well.
system: Ubuntu 17.04
client: Version 2.3.2 (Built from Git revision 820899 on May 8 2017, 14:16:42 using Qt 4.8.7, built with OpenSSL 1.0.2g 1 Mar 2016)

### Bug Description:
When I login to Ubuntu and have no internet connection, the owncloud client creates a new 0byte owncloud.cfg on startup and asks for server address, login, etc. If I restart owncloud with an internet connection afterwards, the configuration is still gone.

However, when I login to Ubuntu with a working internet connection, everything is fine, the owncloud client starts as expected. (without asking for server url/login)

**Comment by michaelstingl** [comment]
@btittelbach 2.3.2 and Qt 4.8.7 on Ubuntu 17.04 sounds like a weird config in OBS. Please open a new issue. Thanks!

**Comment by btittelbach** [comment]
thnx. Just openend #5886
