### ISSUE TITLE
Provide informal german translations

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9460]
The community is providing informal German translations for years.

We however don't even build them.

ISO allows the `-informal` suffix and the Qt supports it as well.

# TODO: 
## in the client:
1. Display the lang code in the language selector to allow multiple "German translations"

![image](https://user-images.githubusercontent.com/200626/157459148-b1c910e2-5126-420f-94a9-3b8eb6ea6420.png)

**Comment by ChrisEdS** [comment]
I'm sorry but I can't find an option to rename. Only adding and deleting is possible. 

https://docs.transifex.com/projects/adding-and-removing-project-languages

**Comment by michaelstingl** [comment]
> ## on Transifex:
> 1. Rename `de`-> `de-informal`
> 2. Rename `de-DE` -> `de`

yeah, would love to have this changed in Transifex, also in the other client repos…

> Only adding and deleting is possible.

Is this doable?

**Comment by ChrisEdS** [comment]
Renaming is not possible as far as I can tell.

**Comment by TheOneRing** [comment]
For now we use the mapping https://github.com/owncloud/client/blob/325b155b3ce8eae231c54cdd45e2999be73ff234/translations/.tx/config#L11

**Comment by michaelstingl** [comment]
> Renaming is not possible as far as I can tell.

That's why I asked for adding and deleting. What's the effort? Will we break stuff?

**Comment by ChrisEdS** [comment]
Yes, adding and deleting should work. Effort low, I can't tell if we break thing, we never did that before.

**Comment by jnweiger** [comment]
We probably break the history? Will contributors be still able to recognize who authored what?

**Comment by TheOneRing** [comment]
No action needed on transifex, I updated the issue.
