### ISSUE TITLE
[ci] use public s3 cache information

### ISSUE THREAD

**Issue by kiranparajuli589** [owncloud/client#9469]
the bucket has changed to a public s3 but the endpoint, AWS access key id, and secret are still using old values

https://github.com/owncloud/client/blob/97798a98cc843be8754c8a45f10847402a8d9bb1/.drone.star#L568-L601

**Comment by kiranparajuli589** [comment]
cc @individual-it @Talank @saw-jan

**Comment by individual-it** [comment]
THX @kiranparajuli589 
this line needs to be changed: 
```
             "endpoint": { 
                 "from_secret": "cache_s3_endpoint", 
             }, 
```
to 
```
 "endpoint": {
        "from_secret": "cache_public_s3_server",
    },
```

I'm not sure if we need the env. variables or they can be deleted

**Comment by kiranparajuli589** [comment]
> I'm not sure if we need the env. variables or they can be deleted

These environment variables are required. see https://github.com/owncloud/client/pull/9470#issuecomment-1049566673

**Comment by kiranparajuli589** [comment]
closing as #9470 is merged
