### ISSUE TITLE
[QA] install.sh mixes download.owncloud.com and minio.owncloud.services 

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9474]
Seen in 2.10.0
![image](https://user-images.githubusercontent.com/1108546/155998497-911f61c8-6754-455f-84f2-4edb9c274d05.png)

Expected behaviour:
* Both lines say download.owncloud.com

**Comment by TheOneRing** [comment]
Please add an assert from now on that the resulting repo now longer contains references for the original url....
Preventing such broken repos from being released should be relatively easy...

**Comment by fmoc** [comment]
See also https://central.owncloud.org/t/minio-owncloud-services-offline/36553/3. The code causing the invalid URL wascommitted in November 2021 while fixing a variety of shellcheck complaints. I've fixed that, now `repo-admin.py` is working correctly.
