### ISSUE TITLE
Show failed test in nightly builds

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9479]
After https://github.com/owncloud/client/pull/9459 we have proper provision to comment the link of test report, when the test fails and report exists. However, after we disabled the use of `gui test result parser`, debugging fails in nightly builds has been difficult. Hence there is a need for appropriate method to show failed tests result (or link to log) in nightly builds.

Possible solutions could be (but not limited to):
- In the notification of nightly builds, use a template which contains the link of test result (like that we show via GitHub comment in PRs)

**Comment by saw-jan** [comment]
Implementation PR merged
