### ISSUE TITLE
Hardcoded oauth config

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9484]
Seen in client 2.10.0 with the openidconnect app 2.1.1 rc1 running on server 10.9.1 -- connected to Azure

This is a followup on https://github.com/owncloud/enterprise/issues/4386

```
String Theme::openIdConnectPrompt() const
{
    return QStringLiteral("select_account consent");
}
```
as e.g. seen in https://github.com/owncloud/client/blob/master/src/libsync/theme.cpp#L646
is invalid with (at least my playground in) Azure: "AADSTS90023: Unsupported 'prompt' value."

Azure works, when it is only `consent`, as shown in my original https://github.com/owncloud/enterprise/issues/4386#issuecomment-799865744 research.

I am aware that differnt brandings can overwrite this in their theme. But I believe the value seen here, and used by the unbranded ownCloud client, and testpilotcloud and btr branding should a valid default.

For best flexibility, I'd suggest to allow changing this string without recompiling, e.g. via env (or maybe *.cfg ) 
```
QString openIdConnectPrompt() const
{
    return qEnvironmentVariable("OWNCLOUD_OPENIDCONNECT_PROMPT", QStringLiteral("consent"));
}

```

**Comment by michaelstingl** [comment]
@IljaN @ChrisEdS @wkloucek what would be your recommendation for the unbranded client? I don't want to break other IdP's.

/cc @TheOneRing

**Comment by TheOneRing** [comment]
Related: https://github.com/owncloud/client/pull/9339

**Comment by TheOneRing** [comment]
Different idps require different parameter.
As far as we know there is no default we can use for all idps.

I'm against adding any more environment variables, https://github.com/owncloud/client/pull/9339 suggest adding it to the config.

The upcoming new theming support could also make it easier to provide the idp settings in a branding.

Configurable oauth settings require research regarding security.
