### ISSUE TITLE
Client just deleted local files, but they still exist on the server

### ISSUE THREAD

**Issue by jsochocki** [owncloud/client#9485]
Expected behaviour
When the client delete files/directories on local repository then files should be deleted on server repository

Actual behaviour
The client deleted files/directories on local repository, but files still available on server repository.
On Polish version of OS (Win 11 PRO) it works, but only on France version of oS (Win 10 PRO) it doesn't works

Steps to reproduce
1. Create directory
2. Sync
3. Delete director
4. Sync (I can see an error on sync - i attached log file)

Client configuration
Client version: Version 2.10.0 (build 6519).

Operating system: Windows 10 Pro x64

OS language: France

Installation path of client: Defaul
[20220307_1027_owncloud.log.0.gz](https://github.com/owncloud/client/files/8197031/20220307_1027_owncloud.log.0.gz)
t

**Comment by TheOneRing** [comment]
If files remained on the server can you check your not synced table in the Activity tab?
You can select an copy(right click) them and append them to the report.

Your log show
```
03-07 10:27:03:811 [ warning sync.propagator ]:	Could not complete propagation of "Photos/Portugal.jpg" by OCC::PropagateIgnoreJob(0x21fb54fe7d0) with status OCC::SyncFileItem::BlacklistedError and error: "The downloaded file does not match the checksum, it will be resumed. '3d8badad7cdf5e30644573009f9540841fcb2c1c' != 'da39a3ee5e6b4b0d3255bfef95601890afd80709' (skipped due to earlier error, trying again in 2 minute(s))"
```
Which could be the reason the files where not deleted, this usually indicates a server issue.

The deletion of the files is however not recorded in the log files.
