### ISSUE TITLE
[QA] 2.10.1 testpilotcloud doesn't offer VFS (experimental) on Linux

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9493]
Seen with testpilotcloud 2.10.1daily20220307 on openSUSE 15.3

- start the client and check the dot menu
Result: the entry "Enable virtual file support (experimental)" is missing

![2-10-1-no-vfs](https://user-images.githubusercontent.com/75983861/157204915-39c3d57f-3b20-4b0f-965f-e08e560ccf04.png)

Expected: should be there for testpilotcloud

![testpilot-versions](https://user-images.githubusercontent.com/75983861/157205010-fdbf6aad-d0c7-44ea-9a24-3f24aae00beb.png)

[20220308_0957_owncloud.log.0.gz](https://github.com/owncloud/client/files/8204476/20220308_0957_owncloud.log.0.gz)

**Comment by gabi18** [comment]
Logs from starting testpilotcloud 2.10.1daily20220310 (build 6984)
[20220310_0911_owncloud.log.0.gz](https://github.com/owncloud/client/files/8221475/20220310_0911_owncloud.log.0.gz)

**Comment by TheOneRing** [comment]
Someone regenerated the testpilotcloud theme and thus experimental features are disabled, again.

**Comment by TheOneRing** [comment]
Didn't see the testpilot in the first screenshot.

**Comment by TheOneRing** [comment]
Fixed in a new build thats supposed to pop out of the ci soon

**Comment by gabi18** [comment]
Confirmed fixed with latest build.

![testpilot-vfs-ok](https://user-images.githubusercontent.com/75983861/157654421-d68701be-1a40-41f6-81e9-e242aeb64015.png)
![testpilot-vfs-menu-ok](https://user-images.githubusercontent.com/75983861/157654429-227b81cd-041d-44aa-bdd3-263ba5e063f6.png)
