### ISSUE TITLE
Owncloudcmd on MacOS bound to OD, username prompt takes forever

### ISSUE THREAD

**Issue by TheWrongGuy** [owncloud/client#9496]
### Description of the environment

- macOS Client with Big Sur 11.6.4 is bound to an Open Directory Server running macOS 11.6.4, too
- I want to execute /Applications/owncloud.app/Contents/MacOS/owncloudcmd as a network LDAP user which is mapped from the Open Directory Server

### Expected behaviour

Login to the client machine via e.g. ssh as a user. Then executing /Applications/owncloud.app/Contents/MacOS/owncloudcmd owncloud/ https://urlofserver

Owncloud cmd should now prompt for a user name. Example picture with a local user on the client machine

![Screenshot 2022-03-09 at 08 52 53](https://user-images.githubusercontent.com/72255550/157397546-0295ee07-858a-4603-befa-f21b742704ed.png)

### Actual behaviour

I login via ssh as a network user which is mapped from a open directory server running macOS 11.6.4 to the client I try to use owncloudcmd on. If I then execute "/Applications/owncloud.app/Contents/MacOS/owncloudcmd owncloud/ https://urlofserver" It sometimes takes hours for the user name prompt to show up:

Example picture where I executed the command as a network user:

![Screenshot 2022-03-09 at 08 52 42](https://user-images.githubusercontent.com/72255550/157398909-1b06f265-7cd3-4841-9983-851817c3d50c.png)

### Steps to reproduce
1. Bind macOS client to Open Directory and use ldap user to login
2. Execute the example command "/Applications/owncloud.app/Contents/MacOS/owncloudcmd owncloud/ https://urlofserver"
3. Prompt for username takes forever

### Server configuration

I have no information about the server configuration.

Storage backend (external storage):

### Client configuration
Client version: 2.10.0.6519

Operating system: MacOS Big Sur 11.6.4

OS language: Englisch

Installation path of client: /Applications/owncloud.app

### Logs

owncloudcmd --logdebug doesn't give any output (you can see it on the picture. No verbose information at all. Am I using --logdebug wrong?). Would the information of "--logdebug" normally be printed on the screen or stored in a file?

**Comment by fmoc** [comment]
I'm sorry, but I have no idea what you're trying to accomplish and where you think you found a bug. We need more information to be able to investigate this issue. Please start by describing what you're trying to do in greater detail and at which step you hit the bug.

Things that do not help:
- reporting more than one bug in an issue
- speculation from your end ("probably also Linux LDAP" for instance)
- providing no screenshots or no log output

Regarding `owncloudcmd --logdebug`, please open a new issue in case you consider this a bug. I'm not sure what you mean. Even if you think there is no additional information, please leave the judgement to the developers and post every log you have.

**Comment by TheWrongGuy** [comment]
@fmoc 

You are right. I should have put in more details. The issue for me is now with this issue I can't find any logging or verbose information, maybe you can help me with this, too. I updated the initial post, I hope this makes the issue more clear. Please let me know!

**Comment by fmoc** [comment]
Do you observe the same behavior with trivial commands, e.g., `--help` or `--version`?
Is the desktop client binary somehow mounted from a remote storage which might have performance issues and lead to a longer loading time?

**Comment by TheWrongGuy** [comment]
Trivial commands like this work fine! The application is installed locally on the machine, not mounted from remote storage.

I didn't experience this issue with another applications as of now. I don't know if you now it but sciebo, basically a fork or the owncloud client customized for university needs and based on the latest owncloud version also has this issue for me. I also experience this with different network accounts on different clients with. So it feels like being related to a network user executing this instead of a local account.

**Comment by fmoc** [comment]
That's a fascinating problem.

I've just tested that `--logdebug` works. There is no log output because no log messages are emitted before the prompt (unless there are fatal issues). There is not much activity going on in the client before the prompt. The CLI params are parsed, some structs are set up, but nothing that could possibly block is happening. The only thing I could imagine that could block is when some configuration values are read, i.e., files are loaded from the home directory. Is your home directory somehow managed by the directory server? Does it reside on a remote file system and is mounted on demand?

In any case, this issue is very hard to analyze remotely. I guess one needs to step through the code with a debugger or hook up macOS's `strace` equivalent to see what's going on.

**Comment by erikjv** [comment]
We're wondering if the client tries to open a window, or interact with the WindowServer. So, could you test the following: login to the mac on the mac itself (so by keyboard & screen) as the OpenDirectory user, and then:

1. run the command from Terminal on the machine itself
2. ssh in from another machine (while still being logged in like above), and run the command in that ssh session.

**Comment by TheWrongGuy** [comment]
Okay, so there is now GUI prompt, so I don't see the issue here, but what @fmoc mentioned pushed me in the right direction and this is another detail I should have added to the initial post, but forgot to mention it. 

> There is not much activity going on in the client before the prompt. The CLI params are parsed, some structs are set up, but nothing that could possibly block is happening. The only thing I could imagine that could block is when some configuration values are read, i.e., files are loaded from the home directory. Is your home directory somehow managed by the directory server? Does it reside on a remote file system and is mounted on demand?
> 

This seems to be part of the problem! Our users have remote home folders mounted to /home/username. Since logging in directly to a network home folder via GUI is not possible we set up in the OD for the users to user /Users/username. Therefore on a normal device a user will login and local folder gets created in /Users/username and he/she can access network files on /home/username or via SMB. For a headless machine like this one where we try to use owncloudcmd no GUI login happens, so we create symlinks in /Users/ which show to /home. E.g. /Users/username -> /home/username, so upon ssh login the user immediately lands in his/her network home folder. This seems to be part of the problem, so it would be interesting what owncloudcmd is doing before the user name prompt. I also don't understand if it's important what it is doing, since without a home folder at all the command is working and asks for the username. I tested the following:

Actual local home folder in /Users/username -> After a reboot owncloudcmd is working via SSH
No homefolder at all (Upon login via SSH "couldn't chdir to home directory")in /Users at all -> Owncloudcmd is working via SSH
Symlink /Users/username -> /Home/username -> Owncloudcmd is not working via SSH

Since the macOS PPPC get more aggressive with every version I also created a profile allowing owncloudcmd and sshd to have full disk access and network volume access and distributed the profile to the machine. This didn't help....

**Comment by fmoc** [comment]
I think there is nothing we can do other than recommend people not to put this application into a network drive that is mounted on demand. This is not a bug within `owncloudcmd`.

**Comment by TheWrongGuy** [comment]
You misunderstand my comment. Owncloudcmd is NOT installed inside a network drive! It is installed locally in /Applications/owncloud.app

Owncloudcmd seems to be bothered if the user has a network home folder even though If I'm trying to sync to a local folder in /tmp or /Users/Shared. I'm not using the network home for owncloudcmd at all. It is just mounted and the default home. Without the network home being mounted, so with no home folder whatsoever owncloudcmd is suddendly prompting for the user.

**Comment by TheWrongGuy** [comment]
Okay. I used dtruss now. FYI one has to remove the codesignature of the owncloudcmd binary, since otherwise dtruss can't trace this! Also running dtruss with sudo before owncloudcmd also doesn't help to track the problem since using sudo owncloudcmd is working even with network home folder mounted. I used sudo dtruss -f -W owncloudcmd in one ssh sessiond and executed the owncloudcmd command in another one. This works!

I will attach the results to this comment. I attached one where the command doesn't prompt for username and one where I removed the symlink form /Users to /home, so the command works and we might see a difference. I didn't use dtruss to often, so I can't identify the problematic section directly. I only put in the section where owncloudcmd seems to try to open something in /home/testuser aka /Users/testuser..... Even if it has something to do with network home access I don't get why it is not working I create a config profile with a PPPC payload giving full disk access, network volume access and so on for owncloudcmd...


[NoHomeFolderLinkExistent_owncloudcmd_working.txt](https://github.com/owncloud/client/files/8252513/NoHomeFolderLinkExistent_owncloudcmd_working.txt)


[HomefolderMountedAndLinkes_owncloudcmd_not_working.txt](https://github.com/owncloud/client/files/8252515/HomefolderMountedAndLinkes_owncloudcmd_not_working.txt)


[FromTestUserExecutedwithSudo.txt](https://github.com/owncloud/client/files/8252516/FromTestUserExecutedwithSudo.txt)

**Comment by TheWrongGuy** [comment]
Release 2.10.1 the issue still occurs. Just FYI. Can I provide more information regarding this? Or can you give me an update on the status of this issue?

**Comment by fmoc** [comment]
Unfortunately, the logs you provided don't reveal any obvious problems. I can't tell why the CLI behaves like that on your computer.

We can leave the issue open for other people to add their information. This appears to be some weird edge case related to your setup.

**Comment by TheWrongGuy** [comment]
Even if network homesfolders on macOS aren't that common anymore in the linux universe they still are. I suspect something from the tcc system of macOS is blocking network volume access, but: I would understand this behaviour if I would try to sync to the the network home folder, but I'm not. I'm running owncloudcmd from local source and trying to sync to a local folder and just happen to have a network home folder. Why is owncloudcmd trying to access something in the own home folder if I'm not trying to sync there? This access seems to be unnecassary, since syncing while not having a home folder at all works. So even if our setup is fairly custom it exposes some weird behaviour of owncloudcmd imo. Is it necassary that owncloudcmd is trying to access some files in the home folder before asking for credentials?

**Comment by TheWrongGuy** [comment]
Un-Stale

**Comment by TheWrongGuy** [comment]
Un-Stale

Issue persists. Changed affected users to local home folder. Owncloud is working this way.
