### ISSUE TITLE
TUS: revert upload on error

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9505]
https://github.com/owncloud/client/pull/9500 implemented a mechanism to prevent finishing uploads if they can't be finalized locally.

We need to find a solution for tus uploads, there is no final operation we can prevent, ideally there would be some kind of transaction mechanism.

**Comment by TheOneRing** [comment]
Discussed with @felix-schwarz .
He suggested we could upload all but one byte and perform the patch request after we are done locally.

**Comment by michaelstingl** [comment]
Additional request for every tiny file will decrease performance?
