### ISSUE TITLE
owncloud --version does not reports `Using virtual files plugin: suffix` in windows 10

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9521]
try the command `owncloud --version` in windows 10. This does not displays the result as indicated in https://github.com/owncloud/client/issues/9155

## Screenshot
![Screenshot from 2022-03-17 13-22-37](https://user-images.githubusercontent.com/27364813/158802536-3243a221-aeaa-49be-82af-afe9d7d93f52.png)

**Comment by fmoc** [comment]
The output is correct for Windows, as there the `wincfapi` plugin is used, whereas `suffix` is the plugin used on Linux (see the issue).

(`suffix` means that basically empty files are created as stubs with a `.owncloud` suffix, on Windows a native API is used that doesn't need such a workaround.)

**Comment by TheOneRing** [comment]
Windows should list both

**Comment by TheOneRing** [comment]
Ok my bad seems like I imagined that.
```
owncloudonline 2.8.2 (build 4401) [ea9d50](https://github.com/owncloud/client/commit/ea9d50062fe1bda7bd1b96b406519f1b6564662f) Jun 15 2021 11:34:18
Libraries Qt 5.12.10, OpenSSL 1.1.1k 25 Mar 2021
Using virtual files plugin: wincfapi
```
