### ISSUE TITLE
Branding option for folder sync wizard

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#9523]
tbd

**Comment by gabi18** [comment]
Tested with 2.10.1-rc2 testpilotcloud:

- confirmed that selecting the sync root as destination is prevented:
![testpilot-syncroot](https://user-images.githubusercontent.com/75983861/161709717-be63191b-f3d4-43d4-8f2e-88c8555f465c.png)

- but it's still possible to select a subfolder:
![testpilot-subfolder](https://user-images.githubusercontent.com/75983861/161709867-61e13323-e4d1-4716-a0fe-f1a97ab1eb68.png)

Is this intended?

**Comment by gabi18** [comment]
Not sure if it's a problem of my self-compiled client: 
I get a crash when I try to create a new folder ("Create Folder", enter name on 'Create Remote Folder' popup and click "OK")  

```
04-05 10:54:21:594 [ fatal default ]:	ENSURE: "relativePath.startsWith(QLatin1Char('/'))" in file /home/gabriele/development/owncloud/client/src/libsync/abstractnetworkjob.cpp, line 201 QUrl OCC::AbstractNetworkJob::makeDavUrl(const QString&) const
```

**Comment by TheOneRing** [comment]
> Not sure if it's a problem of my self-compiled client: I get a crash when I try to create a new folder ("Create Folder", enter name on 'Create Remote Folder' popup and click "OK")
> 
> ```
> 04-05 10:54:21:594 [ fatal default ]:	ENSURE: "relativePath.startsWith(QLatin1Char('/'))" in file /home/gabriele/development/owncloud/client/src/libsync/abstractnetworkjob.cpp, line 201 QUrl OCC::AbstractNetworkJob::makeDavUrl(const QString&) const
> ```

Only a warning for devs

**Comment by TheOneRing** [comment]
> > Not sure if it's a problem of my self-compiled client: I get a crash when I try to create a new folder ("Create Folder", enter name on 'Create Remote Folder' popup and click "OK")
> > ```
> > 04-05 10:54:21:594 [ fatal default ]:	ENSURE: "relativePath.startsWith(QLatin1Char('/'))" in file /home/gabriele/development/owncloud/client/src/libsync/abstractnetworkjob.cpp, line 201 QUrl OCC::AbstractNetworkJob::makeDavUrl(const QString&) const
> > ```
> 
> Only a warning for devs

Crash only happens in debug builds.

**Comment by michaelstingl** [comment]
> * but it's still possible to select an existing subfolder
> 
> ![testpilot-subfolder](https://user-images.githubusercontent.com/75983861/161711027-d62954d7-6da2-4fa5-8325-be1eda6c1274.png)
> 
> Is this intended?

Yes, all subfolders allowed 👍

**Comment by gabi18** [comment]
Also confirmed with btr-client 2.10.1 (build 7211) built in ownbrander with unchecked option "Allow duplicated folder sync pair":

![btr-noduplcated-syncroot](https://user-images.githubusercontent.com/75983861/162145300-a73d2ce2-f555-4c0a-85ec-899a23a92df2.png)
