### ISSUE TITLE
[QA] Cannot open public link in browser on web-app server

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9530]
Seen with client 2.10.1-rc and account 'demo' on server client-test.owncloud.works (web-app enabled)

Steps to reproduce:

- start client
- "Open in file manager"
- right click on file 'Photos/Teotihuacon.jpg' and create a public link
- try to open link in browser (dot menu)

Result:
Failed to open link, spinning icon remains

![public-link](https://user-images.githubusercontent.com/75983861/159227306-ae34633b-5f93-4484-a208-38eaba3f7f93.png)

[log-public-link.txt.gz](https://github.com/owncloud/client/files/8314021/log-public-link.txt.gz)

**Comment by gabi18** [comment]
The issue is reproducible with client 2.10.0.

**Comment by gabi18** [comment]
Open a public link on other server, e.g. client-test2.owncloud.works (account 'admin' works)

**Comment by michaelstingl** [comment]
Sounds like a setup issue with ownCloud web. Not a client issue.

**Comment by gabi18** [comment]
Yes, it seems to be an issue with an older web-app version (or other config problems) - it works on client-test2.owncloud.works wep-app version 5.3.0-rc1.
