### ISSUE TITLE
[QA] language cannot be switched with the usual environment variables

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9534]
Seen with testpilotcloud-client 2.10.1 rc1

* start the client, go to settings, switch laguage to 'Deutsch (de)'
* quit the client.
* start with `LANGUAGE=C LANG=C LC_ALL=C testpilotcloud-client`
* the client comes up again with german UI. BAD
* other attempts with en, en.UTF-8, en_US also don't work
![image](https://user-images.githubusercontent.com/1108546/159478207-b1468052-2f69-48fc-b5f5-dd34aa12a452.png)

**Comment by TheOneRing** [comment]
Is there a language explicitly set in the client, on linux the default should be influenced by the env var.
In order to switch the language I'd recommend to use the language switch.

The language switcher was introduced in 2.9 so not a regression.

**Comment by jnweiger** [comment]
Yes, language is set to Deutsch in the settings UI

![image](https://user-images.githubusercontent.com/1108546/159483973-d7fb92a1-545e-4534-b4f8-1454fbd26671.png)

Not a regression.

**Comment by TheOneRing** [comment]
In that case its expected behavior as the users input takes priority over the system language.

**Comment by jnweiger** [comment]
Something in a config file takes priority over user's comand line. That is a step backwards. LC_ALL should be the mighty override for all and any.

**Comment by TheOneRing** [comment]
When you modify LC_ALL you pretend that the system lang changed. Before you did so, you however changed the language of the client from the system default, which depends on that env var, to German.
If we would now still react to the env, that would be a bug.
However you are not lost and can still set the language from the terminal, see --help.

**Comment by jnweiger** [comment]
The current behaviour as seen in testpilotcloud 2.10.1-rc1:

![image](https://user-images.githubusercontent.com/1108546/159686861-382cc96d-061c-4671-96c9-3d3ed8e78037.png)
----
When the setting is 'use default', the environment variable LANGUAGE takes control (LANG and(! :cry: ) LC_ALL have no effect)

When the setting is any other language, then also LANGUAGE has no effect.

In any case, the command line option `--language` takes priority -- even when the UI says (use default). OK.

**Comment by TheOneRing** [comment]
For the default on linux have a look at https://wiki.qt.io/Locales
