### ISSUE TITLE
Server Not found error is a bit too technical

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9540]
If you append anything after a valid server address then the `404 Nof Found` error is a bit technical IMO.

### Steps to reproduce
- Enter valid server + some other text at the end for example `demo.owncloud.com/abc`

### Expected Behavior
Error message such as "Server not found" or "invalid server address" should be displayed

### Actual Behavior
Error message that indicates the error during GET request is displayed as in the screenshot below
![technical error message](https://user-images.githubusercontent.com/27364813/159657771-e8eb7a7b-b7f5-4e2a-ac11-50e197d834b6.png)

**Comment by TheOneRing** [comment]
![image](https://user-images.githubusercontent.com/200626/159661762-67e9f41f-a9a5-46a2-89be-2bb7deac3797.png)

**Comment by michaelstingl** [comment]
Looks like to first line is the message for the end user, and the second line is more a message for the admin.

@TheOneRing @fmoc separate the 2nd line visually with some space? Or make it expandable and include more technical information like the `X-REQUEST-ID` for example?

![CleanShot 2022-03-23 at 10 16 44](https://user-images.githubusercontent.com/214010/159665834-c22516f5-41be-4180-91f0-8f1f1a864468.png)

/cc @tbsbdr

**Comment by TheOneRing** [comment]
Legacy wizard.

We can discuss error handling in our new wizard meeting.

**Comment by michaelstingl** [comment]
> We can discuss error handling in our new wizard meeting.

Yes, new wizard scope.

**Comment by TheOneRing** [comment]
@fmoc please check with the new wizard

**Comment by TheOneRing** [comment]
![image](https://user-images.githubusercontent.com/200626/175063196-22ddbace-dac5-47f6-9c9b-40d5466369b8.png)
Still too technical
