### ISSUE TITLE
Installing previous stable verison after a beta update says downgrade not supported 

### ISSUE THREAD

**Issue by SagarGi** [owncloud/client#9556]
### Description
After an update to a client to beta version and a uninstall, then installing back to a stable version shows a downgrade not supported message.

### Steps to Reproduce
- Install `testpilot client `(2.10.0)
- Update it to a beta version by switching to beta update channel in settings which then downloads a newer version.
- Uninstall the `testpilot client` in the same state (beta -updated)
- Install the stable version again (2.10.0)

### Test Environment
- Client version: testpilotcloud-2.10.0.6518.x64
- OS: Windows 10
-  Server: https://client-test3.owncloud.works

### Actual Behaviour

![Screenshot (1)](https://user-images.githubusercontent.com/46086950/160386680-a3cd6d82-db5b-467b-9280-0321bc51eb93.png)

Also after the install to a stable version the about section version has a stable version description

![Screenshot (2)](https://user-images.githubusercontent.com/46086950/160386876-5419e148-cd24-4e42-b417-fa80693d523e.png)

### Expected Behaviour

The client should have been in a stable state after an uninstall

**Comment by michaelstingl** [comment]
> The client should have been in a stable state after an uninstall

Can't work with existing data.

**Comment by SagarGi** [comment]
Closing this issue as it cant work with the existing data.
