### ISSUE TITLE
Add "Copy to clipboard" action to "Re-open Browser" button on account screen

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#9559]
![CleanShot 2022-04-04 at 09 27 03](https://user-images.githubusercontent.com/214010/161495482-5ddef6bb-d787-4baf-80ae-dcb47b66ee19.png) | ![CleanShot 2022-04-04 at 09 28 30](https://user-images.githubusercontent.com/214010/161495503-5f6e35b1-f703-4414-8b25-999d44a783de.png)
-- | --

Could it be added there as well?

**Comment by TheOneRing** [comment]
TODO: Now that the browser does not open by itself anymore, we need to display a dialog, raise it to the top and ask the user to proceed with oauth in the browser or log out.
