### ISSUE TITLE
[Wizard] Auto-SSL for Server URL

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#9561]
![CleanShot 2022-04-05 at 11 46 05](https://user-images.githubusercontent.com/214010/161727220-f07d647c-0043-498e-807e-a8c26ce4fc9d.png) | ![CleanShot 2022-04-05 at 11 46 21](https://user-images.githubusercontent.com/214010/161727231-b2cb8cb2-ecbd-4c92-8513-5ab5e0e28ad4.png)
-- | --

SSL should be default nowadays. (check previous version)

iOS app even asks users for approval before connecting to non-SSL servers:

![IMG_112F56ED846F-1](https://user-images.githubusercontent.com/214010/161733534-88aba7e6-b7f4-4232-b633-376ecb1c486a.jpeg)

**Comment by fmoc** [comment]
On `master`, `https://` is automatically prepended if no protocol has been specified. I wonder why it doesn't work on your end. Please post the client's version information.

Regarding invalid SSL certificates, the according dialog has not been ported yet. See https://github.com/owncloud/client/issues/9249#issuecomment-1077479540 for this and other TODOs.

**Comment by michaelstingl** [comment]
> On `master`, `https://` is automatically prepended if no protocol has been specified. I wonder why it doesn't work on your end. Please post the client's version information.

```
ownCloud 2.11.0.7178-daily20220405 Apr 4 2022 18:00:38
Libraries Qt 5.15.2, OpenSSL 1.1.1l 24 Aug 2021
Using virtual files plugin: wincfapi
windows-10.0.22000
```

was built from master a few hrs ago 🤔

**Comment by michaelstingl** [comment]
> Regarding invalid SSL certificates, the according dialog has not been ported yet. See [#9249 (comment)](https://github.com/owncloud/client/issues/9249#issuecomment-1077479540) for this and other TODOs.

Not about invalid SSL certificates. iOS warns warns about connections without SSL.

**Comment by fmoc** [comment]
Reproducible. Seems to be caused by `QUrl::fromUserInput`, which inserts `http` by default.
