### ISSUE TITLE
Run GUI tests parallelly 

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9567]
As we add more GUI test cases, the execution time for test run is increasing and it is now near to 30 minutes. Hence, to finish the execution faster and to utilize the license properly, we should run GUI tests parallelly

**Comment by saw-jan** [comment]
I don't think we can increase Squish test pipelines as of now. Because currently, we have two Squish test pipelines for oc10 and ocis servers. More pipelines mean more Squish licenses are required. So I will close this here.
