### ISSUE TITLE
Move Upload option results in data loss

### ISSUE THREAD

**Issue by tcspestana** [owncloud/client#9574]
### Expected behaviour
File should be preserved and not deleted after "Move Upload" combined with replace file.

### Actual behaviour
File is deleted before being uploaded to the cloud resulting in data loss.

### Steps to reproduce
1. On your local machine move a file to a sub-folder inside owncloud's local folder.
2. Quickly and before it has been uploaded, right-click on  the file and choose Owncloud > Move and Upload
3. When prompted to "Select new location" just click on save.
4. Dialog window should appear saying that the file already exists and asks if you want to replace. Choose Replace
5. You should get a Dialog window saying that "Moving file failed: Destination file is the same file"
6. Now the file is either deleted or moved to an unknown location

### Server configuration
Operating system:
macOS Sierra version 10.12.6 

### Client version
Version 2.10.1 (build 7187)

# TODO
The action `Move and Upload` is supposed to only be available for files in read only remote folders.
Due to a bug the action is also available for files not synced yet.
https://github.com/owncloud/client/blob/2b81fb2df2c766c675e8c683d4fb1bffe3d6b55f/src/gui/socketapi/socketapi.cpp#L1075

Check for conflicts when moving.

**Comment by TheOneRing** [comment]
Which version of the client are you using?

**Comment by tcspestana** [comment]
> Which version of the client are you using?

I am on version 2.10.1 (build 7187).

**Comment by bishwasojha** [comment]
- i cannot find `Move and Upload` button in ownCloud on right click of file!!

- But i found that ownCloud > other options arenot accessible during file syncing

- After file is synced then only ownCloud > options is accessible

### Screenshot
![Screenshot from 2022-11-10 10-16-44](https://user-images.githubusercontent.com/33860671/201005383-8d4b6716-21df-4bc4-9b19-b774daf3c6f0.png)

ownCloud Versions
```
ownCloud 3.0.0.9005-beta1 [6b12ec](https://github.com/owncloud/client/commit/6b12ecdb4236d3d485ed57ec0bc2feac72b8f340)
Libraries Qt 5.15.2, OpenSSL 3.0.2 15 Mar 2022
Using virtual files plugin: suffix
ubuntu-5.15.0-52-generic
```

**Comment by TheOneRing** [comment]
Please read the changelog, it was a bug that the menu was displayed and it is supposed to not show up.
