### ISSUE TITLE
Remove version dependen checks and only rely on capabilities

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#9578]
@TheOneRing could you check if this is used?

```
% curl 'https://demo.owncloud.org/ocs/v1.php/cloud/capabilities?format=json' \
  -u demo:demo | jq '.ocs.data.version'
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  2117  100  2117    0     0   9974      0 --:--:-- --:--:-- --:--:-- 10377
{
  "major": 10,
  "minor": 9,
  "micro": 1,
  "string": "10.9.1",
  "edition": "Community"
}
```

(not the `status.php`)

What is expected? What would happen if it changes to this this? https://github.com/owncloud/ocis/pull/2918#issuecomment-1004744700

**Comment by TheOneRing** [comment]
As far as I can tell we only use the version from status.php .
A version > 10 is expected for some legacy version checks that should be removed anyhow.

**Comment by michaelstingl** [comment]
> A version > 10 is expected for some legacy version checks that should be removed anyhow.

Everything > 10 is okay? We could [turn it up to 11](https://en.wikipedia.org/wiki/Up_to_eleven) and more…?

https://github.com/owncloud/client/blob/2b73fb95e01d0a4ce47602df24116cf81b4463a9/src/libsync/account.cpp#L503-L504

**Comment by TheOneRing** [comment]
Supposedly
