### ISSUE TITLE
Green checkmark icon is shown in the parent folder even when files inside it are not fully synced 

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9586]
### Description
The parent folder is shown as synced even when files inside it are not synced or in the sync process. Creating two folders[inside the sync folder] each containing 500 files each of size 1 MB results in syncing of the first folder along with all files inside it but it is not the same for the second folder. The second folder gets synced but not the files inside it.

The test is automated in this PR. #9588

### Steps to reproduce
1. Create folder `folder1` 
2. Create `500` files inside the folder `folder1`
3. Create folder `folder2`
4. Create `500` files inside folder `folder2`
5. Wait for `folder1` and `folder2` to be synced

### Script to create files inside folder
```
import os
def createFile(folder, numberOfFile):
    cmd = "mkdir {}".format(folder)
    os.system(cmd)
    for i in range(0,numberOfFile):
        filename = "/{}/file{}.txt".format(folder, i)
        cmd = "truncate -s 1048576 {}".format(filename)
        os.system(cmd)
createFile('folder1', 500)
createFile('folder2', 500)
```

### Client configuration
Client version: 2.10.0
Operating system: Ubuntu

### Screenshot

![SYNCISSUE1](https://user-images.githubusercontent.com/66173400/163145123-2247864c-069f-4a79-9eec-59881378190c.gif)

**Comment by hodyroff** [comment]
Still existing with 2.10.1?
