### ISSUE TITLE
Computer 1 gets all files, computer 2 gets some files, same user account

### ISSUE THREAD

**Issue by Flea77** [owncloud/client#9592]
I am not sure this goes here, honestly I am not sure where it goes. If this is incorrect and you can point me in the right direction I would very much appreciate it and I apologize in advance for bothering you. 

I have several computers on several different owncloud installs and have never seen this behavior before. I installed a QNAP NAS with owncloud specifically for these two people to use as a personal cloud as it has worked extremely well for me in the past for myself and others.

I have uninstalled and reinstalled but I am no expert here so I will take any advice, suggestions, pointers to other places I need to look, insults, whatever, as long as it moves me forward to finding and solving the errors.

### Expected behaviour
When installing Owncloud on two computers using the same login credentials and telling it to sync all files, the same files/folders should appear on both computers.

### Actual behaviour
Two laptops both logged into the same owncloud server using the same credentials, one computer gets all the files, one computer gets some of the files/folders.

### Steps to reproduce
1. Install owncloud on computer 1 and 2
2. Wait for sync to complete
3. Compare synced files/folders

### Server configuration
Operating system: Linux of some flavor on QNAP NAS

Web server: 

Database:

PHP version:

ownCloud version:

Storage backend (external storage): 

### Client configuration
Client version: 2.10.1

Operating system: Windows 10

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client [logfile](https://doc.owncloud.com/desktop/latest/appendices/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by michaelstingl** [comment]
How is the storage mounted in your ownCloud? External storage? Does a file scan in the related folder trigger the sync?

Related:
https://doc.owncloud.com/server/10.9/admin_manual/configuration/files/external_storage/configuration.html#detecting-files-added-to-external-storages

**Comment by Flea77** [comment]
Brand new Windows install, then Owncloud and sync. All folders synced except the INVOICES-ETC folder. The sync log shows an error with that folder, but oddly enough if I open Owncloud in a web browser on that same computer, I can download that folder in a zip file and all the files are in it. So why can it grab the files, zip them up, then send them to be when logged into the web browser but not simply sync the folder? Ideas?

![oc-02](https://user-images.githubusercontent.com/103694508/164113590-fe3b5b78-dd26-4e37-b7be-643479dc2b34.jpg)
![oc-03](https://user-images.githubusercontent.com/103694508/164113593-fc087b71-5097-46e3-ba63-dc9e1cfb8bb0.jpg)
![oc-01](https://user-images.githubusercontent.com/103694508/164113594-59da49b2-d243-4e3d-9792-fe5d342c3ff3.jpg)
.

**Comment by TheOneRing** [comment]
> Brand new Windows install, then Owncloud and sync. All folders synced except the INVOICES-ETC folder. The sync log shows an error with that folder, but oddly enough if I open Owncloud in a web browser on that same computer, I can download that folder in a zip file and all the files are in it. So why can it grab the files, zip them up, then send them to be when logged into the web browser but not simply sync the folder? Ideas?
> 
> ![oc-02](https://user-images.githubusercontent.com/103694508/164113590-fe3b5b78-dd26-4e37-b7be-643479dc2b34.jpg) ![oc-03](https://user-images.githubusercontent.com/103694508/164113593-fc087b71-5097-46e3-ba63-dc9e1cfb8bb0.jpg) ![oc-01](https://user-images.githubusercontent.com/103694508/164113594-59da49b2-d243-4e3d-9792-fe5d342c3ff3.jpg) .

Could you check the server log for the affected folder, what exact error does appear in the client log.

When @michaelstingl asked whether you are using external storage, he meant on the server, stuff like an external sftp or s3 storage.

**Comment by Flea77** [comment]
Sorry, crazy week. 

I will check the server log as soon as I get access to it again.

There is no external storage of any kind on the server; physical, cloud, or otherwise.

**Comment by Flea77** [comment]
So I can't tell you why it happened, but creating a new folder on one PC, copying all the files to the new folder, and deleting the old folder seems to have fixed the issue. It now syncs on all PCs just fine.
