### ISSUE TITLE
Owncloud overwrites my newer local files.

### ISSUE THREAD

**Issue by steve-tmq** [owncloud/client#9593]
### Expected behaviour
Tell us what should happen

When I start the client.  I expect any edited files to be uploaded to the cloud(a server I have at home)
The local file should never overwritten.

I do not stand for the cloud owning my local files.  There should be a setting to stop this.
This is the 3rd time this has happened and so I am taking steps to stop using this software.
 
### Actual behaviour
Tell us what happens instead
However what happens is an older version on the cloud gets downloaded and the new version gets renamed.
Issues         ,File                                                            ,Folder                        ,Size  ,Account             ,Time                ,Status              ,
Conflict: Server version downloaded, local copy renamed and not uploaded.,Places.aplibrary/Thumbnails/2018/11/03/20181103-121541/ixBKNM40RCWrmaQahz0jgA/thumb_DSC_2769_face0            ,

### Server configuration
Operating system:
Ubuntu 20

Web server: 
Apache 2
ownCloud version:
ownCloud 10.8.0 (stable)  
### Client configuration
Client version:
V2.10.1
Operating system:
OSX 10.13
OS language:

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client:

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client [logfile](https://doc.owncloud.com/desktop/latest/appendices/troubleshooting.html#log-files)

2. Web server error log:

3. Server logfile: ownCloud log (data/owncloud.log):

**Comment by TheOneRing** [comment]
That is the clients conflict resolution strategy, see https://doc.owncloud.com/desktop/2.10/conflicts.html for how to resolve the issue.
