### ISSUE TITLE
Cannot unpause syncing 

### ISSUE THREAD

**Issue by JohnnyDoorn** [owncloud/client#9595]
### Expected behaviour
Allow me to resume syncing

### Actual behaviour
Syncing is paused, and there is no option anymore to unpause. Before, I had the option to unpause, but it seemed to have disappeared from the client (both tray icon and gui).

### Steps to reproduce
1. Not sure, it just happened one day

### Client configuration
Client version: 2.10.1 (build 7187)

Operating system: Pop OS 20.04 (Ubuntu-based)

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): 5.12.10

Client package (From ownCloud or distro) (Linux only): ownCloud

**Comment by TheOneRing** [comment]
Hi @JohnnyDoorn that sounds strange.
Could you share a screenshot of the affected folder?
Like: 
![image](https://user-images.githubusercontent.com/200626/165048197-35caa61f-5d97-4cd9-8fab-34795794fcb2.png)

and from the folders context menu?

If those don't show anything interesting we'd need your logs from when the client is started.

**Comment by JohnnyDoorn** [comment]
Hi @TheOneRing ,

Thank you for your reply, see my screenshot below. My folder is also not showing up in the main window (it does show the use, and I cannot add the same folder again). 

Kind regards
Johnny

![Screenshot from 2022-04-25 11-36-03](https://user-images.githubusercontent.com/15704203/165062901-41dbecde-60f3-4135-802b-b38aec47e470.png)
![image](https://user-images.githubusercontent.com/15704203/165063004-17b53ff1-7c11-4e91-9707-2b0a19527d6e.png)

**Comment by TheOneRing** [comment]
Hi the folder ownCloud contains a `.sync_journal.db` from a previous install.
This indicates that the folder was not properly removed from the client, or your config got lost.
If you are 100% sure that you synced that folder to this server before you can remove `.sync_journal.db` and use the folder again with the steps you used above.

**Comment by JohnnyDoorn** [comment]
I don't have that specific file, only these:
![image](https://user-images.githubusercontent.com/15704203/165067886-2c152ef7-1638-4eba-b578-63dfe1863357.png)
should I try deleting the .sync_*.db file?

**Comment by TheOneRing** [comment]
If you know what you are doing yes.
Else I'd recommend to use a fresh folder.

**Comment by JohnnyDoorn** [comment]
That worked, thanks a lot! And thanks for the great piece of software!
