### ISSUE TITLE
Several files no longer sync - "Unknown error"

### ISSUE THREAD

**Issue by jayennis22** [owncloud/client#9597]
### Expected behaviour
All files should sync without error... the way they used to.  This has been a pretty trouble-free owncloud installation and I'm not sure what changed.  Perhaps a version upgrade introduced a problem?  Perhaps the client database has bad data?

### Actual behaviour
Every sync completes with 3 specific pdf files in the same directory not synced due to "Unknown error".  The files have not changed since they were created 4 years ago and used to sync with no problem.  The files are not small (largest is 31MB), but they are nowhere near limits.  Bandwidth settings are "No Limit".  I can download the files from the web interface with no problem.

### Steps to reproduce
Have not identified any steps... it just happens in normal sync operation.

### Server configuration
Operating system: Ubuntu 18.04.6 LTS

Web server: Apache/2.4.29

Database: mariadb  Ver 15.1

PHP version: PHP 7.4.29

ownCloud version: 10.9.1.2

Storage backend (external storage): AWS S3

### Client configuration
Client version: 2.10.1

Operating system: MacOs 12.3.1

OS language: US English

Qt version used by client package (Linux only, see also Settings dialog): n/a

Client package (From ownCloud or distro) (Linux only): n/a

Installation path of client: n/a

### Logs

1. Client logfile: https://gist.github.com/jayennis22/8aed7a1f4ff71ba256653f2562e088e9

2. Web server error log: found nothing related

3. Server logfile: ownCloud log (data/owncloud.log): empty

Thanks!

**Comment by TheOneRing** [comment]
Hi @jayennis22 could you enable the http logging, in the log settings area of the application?
Then perform a "Force sync" this will remove any files from internal the error ignore list.
Hopefully I'll be able to tell you more once I saw the full log.

**Comment by jayennis22** [comment]
Problem solved.  

I don't know how it happened, but the files in question were "Locked" on the local file system.  This resulted in log messages stating that:
```
04-25 08:38:33:653 [ warning sync.filesystem ]:	Target file could not be removed.
04-25 08:38:33:653 [ warning sync.filesystem ]:	Renaming temp file to final failed:  "Unknown error"
04-25 08:38:33:653 [ warning sync.propagator.download ]:	Rename failed: "/Users/xxxx/ownCloud/xxxx/MyFileCabinet/Flying/Training/COPA/miniCPPP SYR 0918/.Six Sacred Skills.pdf.~4d203590" => "/Users/xxxx/ownCloud/xxxx/MyFileCabinet/Flying/Training/COPA/miniCPPP SYR 0918/Six Sacred Skills.pdf"
```

Thank you for your help in pointing me to http logs... there is much more detail there.

Perhaps rather than "Unknown error" the error message could be improved to say "Target file locked".

**Comment by TheOneRing** [comment]
Usually we flag those as locked, looks like not in this case as here, the tmp file was locked?

**Comment by TheOneRing** [comment]
Ah the check for file locks is only implemented on Windows as its the platform where file locking causes us the most pain.
