### ISSUE TITLE
nightly-2.10 build fails where as GUI test log shows 100% pass

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9609]
GUI test log is showing 100% test pass but CI is failing in nightly build. It might be a crash rather than any other issue but stack trace is not shown.

The test was failed on April 24 and the stack trace was shown
![Screenshot from 2022-04-27 12-08-35](https://user-images.githubusercontent.com/66173400/165455706-68ffa627-dd47-464b-98fd-c5ce7fe2df98.png)
`Stack trace`: [stacktrace24.log](https://github.com/owncloud/client/files/8569649/stacktrace24.log)

The test was passed on April 25 
![Screenshot from 2022-04-27 12-09-07](https://user-images.githubusercontent.com/66173400/165455717-f39642c9-04e4-4e85-bc8c-272fe76113dc.png)

The test was failed again on April 26 but the stack trace was not shown
![Screenshot from 2022-04-27 12-09-31](https://user-images.githubusercontent.com/66173400/165455724-33a5bd73-6540-4196-b0f4-437990af29b0.png)

Again it failed on April 27 but the stack trace is not shown
![Screenshot from 2022-04-27 12-09-51](https://user-images.githubusercontent.com/66173400/165455727-db4b8445-316a-4227-8287-b3877c2cdc6d.png)

**Comment by sushmita56** [comment]
Stack trace is again generated on April 29 and is showing two crashes

[stacktrace29.log](https://github.com/owncloud/client/files/8587993/stacktrace29.log)

**Comment by Talank** [comment]
The only failed test that I found in the log generated in the last CI run is as in this screenshot. However, the test passed in the second run, so there should not RED CI, as the GUI test log shows 100% pass. I am confused regarding this result, and we do need to understand it, and possibly solve it as well.

![Screenshot from 2022-05-03 11-16-38](https://user-images.githubusercontent.com/27364813/166408539-2cce6935-c90f-4ae3-9417-9cdf0dcfee71.png)

_Originally posted by @Talank in https://github.com/owncloud/client/issues/9610#issuecomment-1115754975_

**Comment by Talank** [comment]
May be there is no coredump at all. I noticed that the drone shows "Fail" even if the test passes in retry. It could be the case in all those test where the CI is failing with 100% pass in GUI test log and no stacktrace.

**Comment by Talank** [comment]
AFAIK This is a bug in Squish that the test passed in retry fails the CI. @individual-it

**Comment by individual-it** [comment]
yes there is a bug in squish, when running squishrunner with `--retry 1 --exitCodeOnFail 1` and a test is retried and passes on retry the exit code is still 1
According to froglogic this will be fixed in Squish 6.8.0

**Comment by individual-it** [comment]
for now I would suggest to remove the retry as its only confuses

**Comment by Talank** [comment]
> or now I would suggest to remove the retry as its only confuses

Removed in https://github.com/owncloud/client/pull/9626#event-6539779830

**Comment by saw-jan** [comment]
Possible fix PR merged. Let's see if that happens again
Closing here!
