### ISSUE TITLE
Owncloud client crashes immediately on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by char8t** [owncloud/client#9613]
On a freshly installed Ubuntu 22.04 LTS Renderdoc crashes immediately on application startup.

### Expected behaviour
Application start

### Actual behaviour
Owncloud client crashes on application startup. It seems the crash is due to an error or bug in QT as other applications such as Renderdoc are also affected:

```
marvin@Marvin-PC:~$ owncloud
Speicherzugriffsfehler (Speicherabzug geschrieben)
marvin@Marvin-PC:~$ 
marvin@Marvin-PC:~$ lldb $(which owncloud)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'lldb.embedded_interpreter'
(lldb) target create "/usr/bin/owncloud"
Current executable set to '/usr/bin/owncloud' (x86_64).
(lldb) run
Process 6033 launched: '/usr/bin/owncloud' (x86_64)
Process 6033 stopped
* thread #1, name = 'owncloud', stop reason = signal SIGSEGV: invalid address (fault address: 0x8)
    frame #0: 0x00007ffff6b5e27e libQt5Core.so.5`___lldb_unnamed_symbol11821 + 30
libQt5Core.so.5`___lldb_unnamed_symbol11821:
->  0x7ffff6b5e27e <+30>: movq   0x8(%rdi), %r13
    0x7ffff6b5e282 <+34>: movq   %rdx, -0x90(%rbp)
    0x7ffff6b5e289 <+41>: movq   %fs:0x28, %rax
    0x7ffff6b5e292 <+50>: movq   %rax, -0x38(%rbp)
(lldb) 
```

### Steps to reproduce
* Install Ubuntu 22.04 LTS
* Install owncloud via apt
* Start owncloud

### Server configuration
does not apply here

### Client configuration
Client version:
2.6.3.14058+dfsg-1

Operating system:
Ubuntu 22.04

OS language:
German

Qt version used by client package (Linux only, see also Settings dialog):
Not sure, seems to be QT5

Client package (From ownCloud or distro) (Linux only):
2.6.3.14058+dfsg-1

Installation path of client:

### Logs
Application does not seem to create a log file

**Comment by fmoc** [comment]
Version 2.6.3 really is outdated and distro packaging is not supported by us. You need to file a bug with Ubuntu so the maintainers can have a look at the crash.

In the meantime, until official 22.04 packages are available, you should try our [latest stable AppImage](https://download.owncloud.com/desktop/ownCloud/stable/latest/linux-appimage/ownCloud-2.10.1.7187.AppImage), which runs on all reasonably up to date Linux distros.

**Comment by fmoc** [comment]
Build has been deployed now: https://download.owncloud.com/desktop/ownCloud/daily/2.10/linux/Ubuntu_22.04/
