### ISSUE TITLE
Crash in nightly build

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9616]
The stack trace is showing two crash

Stack trace: [stacktrace29.log](https://github.com/owncloud/client/files/8588110/stacktrace29.log)
Server log: https://cache.owncloud.com/public/owncloud/client/11562/guiReportUpload/serverlog.log 
GUI test log: https://cache.owncloud.com/public/owncloud/client/11562/guiReportUpload/index.html

**Comment by TheOneRing** [comment]
The affected code is probably fixed on master.
Did you enable activities recently on the test dockers, I think there where not activities in the past.
Maybe the enabled activities uncovered the bug here?
I'll add a nullptr check that might fix the crash.

**Comment by TheOneRing** [comment]
I had another look, its horrible, its supposed to be fixed on master.
If we can get rid of the crash by disabling the activities on the server lets try that....

**Comment by TheOneRing** [comment]
I think the oc server used in the tests had no activities app installed.

**Comment by sushmita56** [comment]
Which activity are you talking about? Are you talking about the activity app in the core or the "Activity" option in the client? If you're talking about the client's "Activity", it is there for so long and if you're talking about core's "activity", it is already disabled. I don't think we did any changes related to activity recently.

**Comment by TheOneRing** [comment]
Owncloud server aka Core.
Hmm then I'm wondering why there is something happening in that code and what caused the issue to surface.

**Comment by sushmita56** [comment]
Stacktrace generated on May 2 is showing one crash which is quite similar to the crash on April 29.
[stacktrace_May2.log](https://github.com/owncloud/client/files/8608217/stacktrace_May2.log)

**Comment by sushmita56** [comment]
Stacktrace generated on May 4 is showing one crash. The first entry of the stacktrace on April 29 is similar to today's stacktrace. But I'm not sure whether it is due to the `activity`.
[stacktrace_May4.log](https://github.com/owncloud/client/files/8618152/stacktrace_May4.log)

**Comment by sushmita56** [comment]
Today's stacktrace is the same as the second entry of stacktrace that was generated on April 29.
[stacktrace_May5.log](https://github.com/owncloud/client/files/8628611/stacktrace_May5.log)

**Comment by sushmita56** [comment]
AUT got crashed in the nightly build
[stacktrace_june24.log](https://github.com/owncloud/client/files/8973014/stacktrace_june24.log)
[GUI test log](https://cache.owncloud.com/public/owncloud/client/12202/guiReportUpload/index.html)

![Screenshot from 2022-06-24 09-40-03](https://user-images.githubusercontent.com/66173400/175459241-b68c3b9b-8e0d-485f-8c6b-34a5449c90c1.png)
