### ISSUE TITLE
Scenario "Delete a folder" fails intermittently

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9625]
The test gets failed on step `Then as "Alice" file "simple-folder-with-name-more-than-20-characters" should not exist on the server` in the first run.

```
Exception: Step execution through test middleware failed. Error: AssertionError [ERR_ASSERTION]: file/folder should not exist, but does
    at /usr/src/app/src/stepDefinitions/webdavContext.js:95:12
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async /usr/src/app/src/app.js:66:7
```

But gets passed in the second retry.

**Comment by Talank** [comment]
As I mentioned in https://github.com/owncloud/client/pull/9630#issuecomment-1128474544 the test fails when the remove file conformation popup do not appear. And this message do not appear if the application is not closed properly in the after scenario. We are using `detach()` function to terminate the AUT and the actual fault in our test might be on that function itself. I will try using some other methods to close the application, and see if that was actually the problem.

**Comment by Talank** [comment]
closing for now REF: https://github.com/owncloud/client/pull/9630#issuecomment-1143098067

**Comment by sushmita56** [comment]
Reopening the issue as scenario `Delete a folder` failed on the same step - `Then as "Alice" file "simple-folder-with-name-more-than-20-characters" should not exist on the server` in master too.
https://drone.owncloud.com/owncloud/client/12066
https://cache.owncloud.com/public/owncloud/client/12066/guiReportUpload/index.html

**Comment by sushmita56** [comment]
It failed on the same step on today's nightly build too
Build: https://drone.owncloud.com/owncloud/client/12464
GUI log: https://cache.owncloud.com/public/owncloud/client/12464/guiReportUpload/index.html
![Screenshot from 2022-07-12 09-50-16](https://user-images.githubusercontent.com/66173400/178406352-720adc6a-2c80-4fdf-9b6a-4b7e0332cd9d.png)

**Comment by sushmita56** [comment]
Closing the issue here as it hasn't appeared latterly. Will be opening it again, if reappears.
