### ISSUE TITLE
Possible file corruption with enabled mod_deflate

### ISSUE THREAD

**Issue by ghost** [owncloud/client#965]
Hi,

there is a user reporting corrupted files (content of the file is a HTTP reply from the server) while using an enabled mod_deflate apache module at the server:

https://forum.owncloud.org/viewtopic.php?f=4&t=15604#p40211

Unfortunately he hasn't reported that much info about his setup but i want to report this anyway.

**Comment by RealRancor** [comment]
@danimo 
Just a quick check-up for the current version of the sync client. Is mod_deflate still unsupported as there is still my open issue reported to core: https://github.com/owncloud/core/issues/4783
