### ISSUE TITLE
GUI tests failed with AUT crash

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#9650]
https://drone.owncloud.com/owncloud/client/11681/6/1
### 1
![account_conn_failed](https://user-images.githubusercontent.com/52366632/167402009-11ba0c9d-1c98-4651-b793-678c7fb5a363.png)

Stacktrace: [stacktrace.log](https://github.com/owncloud/client/files/8651222/stacktrace.log)

### 2
![account_test_aut_crash](https://user-images.githubusercontent.com/52366632/167542893-c6f5a35a-436c-4bf3-8a8d-3b61f9f0eabc.png)
Stacktrace: [stacktrace.log](https://github.com/owncloud/client/files/8657418/stacktrace.1.log)

**Comment by Talank** [comment]
@saw-jan The connection lost crash in remove_account might be same as that of https://github.com/owncloud/client/issues/9367
