### ISSUE TITLE
[QA] ownCloud-2.11.0-daily20220511.7483-vfs.x64.msi doesn't run

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9659]
The ownCloud client crashed after updating from ownCloud-2.11.0-daily20220509.7472-vfs.x64.msi to ownCloud-2.11.0-daily20220511.7483-vfs.x64.msi.

Crash report sent: 6cfeb561-912c-4f9b-be86-6ab3b4a6386a 

[ownCloud-crash.log.gz](https://github.com/owncloud/client/files/8667221/ownCloud-crash.log.gz)

**Comment by gabi18** [comment]
Same for a fresh install.

**Comment by TheOneRing** [comment]
Can you list the files from your install dir, thx.

**Comment by gabi18** [comment]
```
-rwxr-x---+ 1 SYSTEM SYSTEM 3904872 May 10 17:18 owncloud.exe
-rwxr-x---+ 1 SYSTEM SYSTEM   94568 May 10 17:18 owncloud_crash_reporter.exe
-rwxr-x---+ 1 SYSTEM SYSTEM  536424 May 10 17:18 owncloud_csync.dll
-rwxr-x---+ 1 SYSTEM SYSTEM  180584 May 10 17:18 owncloudcmd.exe
-rwxr-x---+ 1 SYSTEM SYSTEM 2246504 May 10 17:18 owncloudsync.dll
-rwxr-x---+ 1 SYSTEM SYSTEM   73576 May 10 17:18 owncloudsync_vfs_off.dll
-rwxr-x---+ 1 SYSTEM SYSTEM   92008 May 10 17:18 owncloudsync_vfs_suffix.dll
```

**Comment by TheOneRing** [comment]
Fixed in the next round of builds

**Comment by gabi18** [comment]
Confirmed with ownCloud-2.11.0-daily20220511.7492-vfs.x64.msi
