### ISSUE TITLE
[QA] Sync folder root not correct after logout/login and remove/add account 

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9665]
Seen with client ownCloud-2.11.0-daily20220510.7476-vfs.x64.msi on Windows 10 21H2.

Steps to reproduce:
- add account 'katherine' and add a space
- remove account
- add account again -> correct entries in owncloud.cfg
- login/logout
- remove account
- add account 'katherine' again

Result: new account not added correctly

![sync-folder-not-ok](https://user-images.githubusercontent.com/75983861/167843168-2f24a575-7951-4dfa-86ff-d08715ef2bb5.png)

**Comment by gabi18** [comment]
[20220511_1544_owncloud.log.0.gz](https://github.com/owncloud/client/files/8669638/20220511_1544_owncloud.log.0.gz)
[20220511_1544_owncloud.log.1.gz](https://github.com/owncloud/client/files/8669639/20220511_1544_owncloud.log.1.gz)
[20220511_1544_owncloud.log.2.gz](https://github.com/owncloud/client/files/8669641/20220511_1544_owncloud.log.2.gz)
[20220511_1545_owncloud.log.0.gz](https://github.com/owncloud/client/files/8669642/20220511_1545_owncloud.log.0.gz)
[20220511_1546_owncloud.log.0.gz](https://github.com/owncloud/client/files/8669654/20220511_1546_owncloud.log.0.gz)

**Comment by gabi18** [comment]
[owncloud.cfg.katherine2.gz](https://github.com/owncloud/client/files/8669658/owncloud.cfg.katherine2.gz)
[owncloud.cfg.katherine3.gz](https://github.com/owncloud/client/files/8669660/owncloud.cfg.katherine3.gz)

**Comment by TheOneRing** [comment]
And could you please provide unified logs by piping to a file?
Those split up are hard to handle.

**Comment by gabi18** [comment]
[spaces_not_correct.log.gz](https://github.com/owncloud/client/files/8675632/spaces_not_correct.log.gz)

To my understanding syncing "ownCloud - katherine@ocis.owncloud.com3/Personal/" should succeed and "ownCloud - katherine@ocis.owncloud.com3//Personal2/" should not exist

```
05-11 15:46:15:075 [ info gui.folder.manager ]:	>========== Sync started for folder [ "ownCloud - katherine@ocis.owncloud.com3\\Personal" ] of account [ "Katherine Johnson@ocis.owncloud.com" ] with remote [ "https://ocis.owncloud.com/dav/spaces/4c510ada-c86b-4815-8820-42cdf82c3d51/" ]
05-11 15:46:15:076 [ info sync.engine ]:	There are "43 GB" available at "C:/Users/gabi/ownCloud - katherine@ocis.owncloud.com3/Personal/"
...
05-11 15:46:15:135 [ info gui.folder ]:	Client version "ownCloud 2.11.0.7476-daily20220510 May  9 2022 17:23:12 Libraries Qt 5.15.2, OpenSSL 1.1.1n  15 Mar 2022 verwenden das Virtual Files plugin: wincfapi windows-10.0.19044"
05-11 15:46:15:135 [ warning gui.folder ]:	SyncEngine finished with ERROR
05-11 15:46:15:136 [ info gui.folder ]:	Folder "C:/Users/gabi/ownCloud - katherine@ocis.owncloud.com3/Personal/" sync result:  OCC::SyncResult::SyncPrepare
05-11 15:46:15:136 [ info gui.folder ]:	the last 3 syncs failed
05-11 15:46:15:138 [ info gui.application ]:	Sync state changed for folder  "https://ocis.owncloud.com/dav/spaces/4c510ada-c86b-4815-8820-42cdf82c3d51/" :  "Error"
```

**Comment by TheOneRing** [comment]
You have more than one Personal space that should not happen.

**Comment by TheOneRing** [comment]
I'd need the http log from the request to `graph/v1.0/me/drives`

**Comment by TheOneRing** [comment]
I guess you encountered the hourly wipe of the demo server.
After the wipe the personal space is recreated with a new url, so the old client setup is broken.

**Comment by gabi18** [comment]
This was also my first guess but I tried to finish my test before the hourly wipe.
I will retest.

**Comment by gabi18** [comment]
Cannot reproduce so far with ownCloud-2.11.0-daily20220511.7492-vfs.x64.msi.
I will wait for hourly wipe and see what will happen then. What should happen?

**Comment by gabi18** [comment]
When I started the client on another Windows machine and logged in as 'katherine' within an hour I had the problems again:
![spaces-problem](https://user-images.githubusercontent.com/75983861/168055006-76f14de6-425b-4192-8d66-b41a482d7d99.png)
[spaces-problem.log.gz](https://github.com/owncloud/client/files/8677386/spaces-problem.log.gz)

**Comment by TheOneRing** [comment]
Again I need ` graph/v1.0/me/drives` 
This is requested during the setup wizard and when you press the add space button

**Comment by gabi18** [comment]
I haven't add the spaces on this machine but on other before, in log I found this:
```
05-04 15:49:25:209 [ info sync.accessmanager ]:	2 "" "https://ocis.owncloud.com/graph/v1.0/me/drives" has X-Request-ID "89195335-dd5f-4b92-a427-1c5f7e956e94"
05-04 15:49:25:209 [ debug sync.cookiejar ]	[ OCC::CookieJar::cookiesForUrl ]:	QUrl("https://ocis.owncloud.com/graph/v1.0/me/drives") requests: ()
05-04 15:49:25:209 [ info sync.networkjob ]:	Created OCC::GraphApi::Drives("https://ocis.owncloud.com/graph/v1.0/me/drives","GET", "89195335-dd5f-4b92-a427-1c5f7e956e94", "89195335-dd5f-4b92-a427-1c5f7e956e94") for QObject(0x0)
05-04 15:49:25:209 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job finished OCC::JsonApiJob("https://ocis.owncloud.com/ocs/v2.php/cloud/user?format=json","GET", "75b845a5-18f7-4e29-9aba-717c52640d4d", "75b845a5-18f7-4e29-9aba-717c52640d4d")
05-04 15:49:25:217 [ info sync.credentials.manager ]:	added "ownCloud_credentials:ocis.owncloud.com:1fcd4f2d-574d-40d5-a116-c8a50c3c2419:http/oauthtoken"
05-04 15:49:25:226 [ info sync.credentials.manager ]:	added "ownCloud_credentials:demo.owncloud.org:6a5ed4a0-8e50-4f95-8b3b-ee7636fa4af4:http/password"
05-04 15:49:25:270 [ info sync.networkjob.jsonapi ]:	JsonJob of QUrl("https://ocis.owncloud.com/graph/v1.0/me/drives") FINISHED WITH STATUS "OK"
...
05-04 15:49:25:709 [ debug sync.networkjob ]	[ OCC::AbstractNetworkJob::slotFinished ]:	Network job finished OCC::GraphApi::Drives("https://ocis.owncloud.com/graph/v1.0/me/drives","GET", "89195335-dd5f-4b92-a427-1c5f7e956e94", "89195335-dd5f-4b92-a427-1c5f7e956e94")
05-04 15:49:25:709 [ warning sync.vfs.win ]:	void __cdecl OCC::VfsWin::fileStatusChanged(const class QString &,class OCC::SyncFileStatus) : could not make handle for "C:/Users/gabi/ownCloud - katherine@ocis.owncloud.com//Personal2/.sync_journal.db-wal" "WindowsError: ffffffff8007007b: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch."
05-04 15:49:25:709 [ warning sync.vfs.win ]:	void __cdecl OCC::VfsWin::fileStatusChanged(const class QString &,class OCC::SyncFileStatus) : could not make handle for "C:/Users/gabi/ownCloud - katherine@ocis.owncloud.com//Personal2/.sync_journal.db-shm" "WindowsError: ffffffff8007007b: Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch."
...
```

**Comment by gabi18** [comment]
Retested with ownCloud-3.0.0-daily20220602.7725.x64.msi and ocis.ocis-traefik.released.owncloud.works (2.0.0 Beta2): 
The issue is solved, also after logout/login and re-adding the acoount the sync folder connections are correct.
