### ISSUE TITLE
Deadlock when requesting context menu of a folder in the select local folder dialog

### ISSUE THREAD

**Issue by dromanini** [owncloud/client#9681]
### Expected behaviour
When I do "add folder sunc connection", then I proceed to choose a local folder, a file selection tree appears where I can navigate to the folders by left-clicking to open folder after folder in the tree. 
I would expect to have other options available by right-clicking on a folder in the tree... or else that nothing happens

### Actual behaviour
When I right-click on a folder the client shows a waiting symbol in place of the mouse arrow and hangs up forever. I have to terminate the client then restart it.

### Steps to reproduce
See previous description.
This is not occasional bug, it is perfectly reproducible. It occurs also on another Windows10 PC I use to connect to the same account.

### Server configuration
Operating system: I do not know (I use this as a service provided by CNRS to its employees)
Web server: https://mycore.core-cloud.net/
Database: -
PHP version: -
ownCloud version: -
Storage backend (external storage): -

### Client configuration
Client version: last at this date (as it says in the configuration menu)

Operating system: Windows 10

OS language: english

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: C:\Program Files (x86)\ownCloud

### Logs 

I do not paste log as it seems to contain personal infos. In any case you should be able to reproduce the bug on a similar system.

**Comment by TheOneRing** [comment]
We load our own shell extension and run into a dead lock.

**Comment by TheOneRing** [comment]
![Clipboard - May 17, 2022 6_11 PM](https://user-images.githubusercontent.com/200626/168980669-e255d8fe-7ac9-47d0-87d0-a2d13bb7c5d4.png)

**Comment by bishwasojha** [comment]
__with both ocis and owncloud10__

- when right click on folder in tree, there are other options available
