### ISSUE TITLE
[QA] 3.0.0 alpha1 client problem with certificate

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9690]
Seen with ownCloud-3.0.0-alpha1.7623-vfs.x64.GPO.msi on Windows10 21H2 VirtualBox VM

After a new installation of ownCloud-3.0.0-alpha1 and trying to connect to demo.owncloud.com the TLS error popup is shown.
This doesn't occur with a newly installed testpilotcloud-2.10.1.7188.x64.GPO.msi on the same machine.

![TLS-error](https://user-images.githubusercontent.com/75983861/169020910-e6c8ef75-3c9f-4a72-bc6c-79b6cb95a616.png)

[connect-tls-error.log.gz](https://github.com/owncloud/client/files/8715480/connect-tls-error.log.gz)

Only after logging in to demo.owncloud.org in Microsoft Edge the TLS popup is gone.

**Comment by TheOneRing** [comment]
cert store on the vm was out of date
