### ISSUE TITLE
[QA] 3.0.0 alpa1 client: adding an account takes long time

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9691]
Seen with ownCloud-3.0.0-alpha1.7623-vfs.x64.GPO.msi on Windows10 21H2 VirtualBox VM.

Adding a new account to demo.owncloud.org takes more than 30 seconds (the spinning icon is shown).

![add-account](https://user-images.githubusercontent.com/75983861/169022790-4f97779a-13b1-4fd7-bcc8-31338cfd88f9.png)

```
05-18 11:52:36:523 [ debug sync.networkjob ]    [ OCC::AbstractNetworkJob::slotFinished ]:      Network job finished OCC::AvatarJob("https://demo.owncloud.org/remote.php/dav/avatars/demo/128.png","GET", "786582ea-0e2a-4558-97c5-fce9dceb2615", "786582ea-0e2a-4558-97c5-fce9dceb2615", "Error transferring https://demo.owncloud.org/remote.php/dav/avatars/demo/128.png - server replied: Not Found")
05-18 11:53:06:187 [ info sync.networkjob ]:    Created OCC::PropfindJob("https://demo.owncloud.org/remote.php/dav/files/demo/","PROPFIND", "a0a1c056-3ba6-4c40-9452-ed8fcb7b2406", "a0a1c056-3ba6-4c40-9452-ed8fcb7b2406") for OCC::QuotaInfo(0x273f71652f8)
```
[connect-pause.log.gz](https://github.com/owncloud/client/files/8715598/connect-pause.log.gz)

**Comment by TheOneRing** [comment]
If you think an issue is not fixed please reopen it...

**Comment by gabi18** [comment]
I cannot reproduce the issue yet. Adding the first account to the client usually is fast (while it seems that accounts on oCIS take longer).
When adding more accounts it gets slower. The logging below shows a strange behaviour: I have added an account connecting to ocis.owncloud.com, the time gap is for demo.owncloud.com.

I will retest if basic auth/oauth makes a difference.

```
05-23 14:08:54:254 [ info gui.folder.manager ]: <========== Sync finished for folder [ "ownCloud - demo@demo.owncloud.com2" ] of account [ "demo@demo.owncloud.com" ] with remote [ "https://demo.owncloud.com/remote.php/dav/files/demo/" ]

05-23 14:09:31:623 [ info gui.folder ]: Trying to check "https://demo.owncloud.com/remote.php/dav/files/demo/" for changes via ETag check. (time since last sync: 37 s)
05-23 14:09:31:623 [ info gui.folder ]: Trying to check "https://ocis.ownncloud.com/dav/spaces/1284d238-aa92-42ce-bdc4-0b0000009157$4c510ada-c86b-4815-8820-42cdf82c3d51/" for changes via ETag check. (time since last sync: 38 s)
```

**Comment by gabi18** [comment]
I don't see the problem when testing on openSUSE 15.3. Accounts are added within seconds there.

**Comment by gabi18** [comment]
Confirmed with ownCloud-3.0.0.7681-alpha2.7681.x64.msi on Windows 10 21H2 that new accounts are added without a longer delay.
