### ISSUE TITLE
[QA] Improve  display of deleted/disabled spaces

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9700]
Seen with version 3.0.0.0-git May 18 2022 09:21:53 on openSUSE 15.3

After deleting a space on the server the client shows a red error message:

![space-deleted](https://user-images.githubusercontent.com/75983861/169306048-866e2d36-1a1d-4c4a-9493-df9d7e4b2ca8.png)

[deleted_space.log.gz](https://github.com/owncloud/client/files/8729602/deleted_space.log.gz)

**Comment by michaelstingl** [comment]
Also for disabled spaces

**Comment by michaelstingl** [comment]
@micbar @kulmann an idea? List Spaces with a disabled flag?

**Comment by kulmann** [comment]
> @micbar @kulmann an idea? List Spaces with a disabled flag?

On a technical level we can make that work. Wouldn‘t even need changes in web. Mostly a product decision I think. If @tbsbdr is fine with it I would give it a go (list disabled spaces for non-manager members as well).

**Comment by TheOneRing** [comment]
After an other look, I'm going for `This space is either disabled or deleted`.
Listing disabled spaces would just provide a more fine grained error.

**Comment by micbar** [comment]
Same here. Technically not a problem. PM decision if non managers should see disabled spaces. IMO the original idea was that disabling really removes the space for all non managers to free up the space.

**Comment by TheOneRing** [comment]
![image](https://user-images.githubusercontent.com/200626/225588655-35ae1f94-f45c-4957-aa83-e969ddeb1eed.png)
Should be ok?

**Comment by michaelstingl** [comment]
What about "This Space is no longer available for syncing" ?

**Comment by TheOneRing** [comment]
"This Space is currently unavailable"?

**Comment by michaelstingl** [comment]
> "This Space is currently unavailable"?

works for me 👍

**Comment by Salipa-Gurung** [comment]
Tested with ` ownCloud version 4.0.0.10458-daily20230320 `
oCIS Server: [ocis.ocis-traefik.latest.owncloud.works](https://ocis.ocis-traefik.latest.owncloud.works/)

Expected: disabled and deleted space should display error message ` This Space is currently unavailable ` 

> In Windows

| ![Screenshot from 2023-03-20 12-58-24](https://user-images.githubusercontent.com/53458341/226271457-6828ba8e-5ad7-41d1-9643-cad8e03fc299.png) | ![Screenshot from 2023-03-20 12-59-04](https://user-images.githubusercontent.com/53458341/226271614-84ac8d41-65ad-409b-80e6-94945fbd4dc5.png) | ![Screenshot from 2023-03-20 12-58-51](https://user-images.githubusercontent.com/53458341/226271759-6faafbd1-d092-4372-a8e1-d09fd611c530.png) |
|--|--|--|
| Space1 created and synced | Space1 disabled | Space1 deleted |
