### ISSUE TITLE
Layout issue in new Connection Dialog

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#9718]
When opening the advanced config on the last configuration page, I get a (minor) rendering issue - which might be just a layout issue:
![grafik](https://user-images.githubusercontent.com/1070214/169790631-7d0b1c10-47b0-462d-b8c1-17a399e0ad80.png)

Code: master @ c8bb15ba929df39283dac25fd424e7daa9dc4b9d
built manually on openSUSE Tumbleweed, System Qt Version 5.15.2

**Comment by jnweiger** [comment]
In daily 20220523 (ubtuntu 20.04) it looks okay:
![image](https://user-images.githubusercontent.com/1108546/169821080-14c91b82-73b3-4e06-9d8c-3ab0020add5a.png)

**Comment by erikjv** [comment]
This is the title of a normal `QGroupBox`. We don't change anything, so it's probably style related.
