### ISSUE TITLE
[QA] please avoid needless whitespace in filesystem

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9722]
Seen in testpilotcloud 3.0.0.7670-daily20220523 c8bb15 May 20 2022 14:47:04

The new connection dialog now defaults to a sync root folder with two whitespace in it.
 
![Screenshot from 2022-05-23 14-38-23](https://user-images.githubusercontent.com/1108546/169822254-6fa92e7e-49b2-479a-b674-383bfa4330a1.png)

This is cumbersome for completion, as soon as more than one sync folder exists, one needs to type `\ -\ ` before completion can work.
This is cumbersome for copy paste into the shell. Path names need to be manually enclosed in quotes or backslashes inserted.

Expected behaviour:
* avoid whitespaces

**Comment by TheOneRing** [comment]
Quoting

**Comment by TheOneRing** [comment]
And you are free to use something different
