### ISSUE TITLE
"Open in Web" for native clients

### ISSUE THREAD

**Issue by pmaier1** [owncloud/client#9724]
**Story**
As a client user I want to open a file in the Web Office directly from the context menu in my file browser so that I can easily start collaborating with others

**Specifics**
- Infinite Scale only
- Use App provider backend
- Timeline ~ mid August

@TheOneRing

**Comment by pmaier1** [comment]
Any update? cc @michaelstingl @dragotin

**Comment by TheOneRing** [comment]
I can start working on it next week.

**Comment by TheOneRing** [comment]
Doc: https://owncloud.dev/services/app-registry/apps/
Test url: https://ocis.ocis-wopi.latest.owncloud.works/app/list

**Comment by pmaier1** [comment]
> @pmaier1 are you ok with solution 2?

Well, not really happy having to reauthenticate. of course. I agree that 3 would probably also get criticized. If you don't see other solutions, let's go for 2 for now.

**Comment by TheOneRing** [comment]
Relevant discussion https://chat.owncloud.com/channel/ocis-internal?msg=gEsa7WyZRTFL8Q3YX

**Comment by pmaier1** [comment]
Alright, thanks for the background. I think solution 2 will work now, as said above.

**Comment by michaelstingl** [comment]
> 2\. Desktop Client opens oC Web (separate authentication)
>     The Desktop Client just opens oC Web in the document edit view. If no session is active in the browser, the user needs to login first.

This is what I'd expect with the given possibilities. Handing-over authentication from native apps to the web needs a bigger concept. Happy to discuss with the backend experts at a later stage…
