### ISSUE TITLE
Hovering over user do not show `username@host`

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9728]
### Description
When we add more than one user in the desktop client, then for each additional user (other than the first user), when we hover over the user, it displays `first_name@host` instead of `full_name@host`. This behavior is different from that of 2.10

### Behavior in current master
![ezgif com-gif-maker](https://user-images.githubusercontent.com/27364813/170010405-fecffd00-2303-4b76-af36-5b4aec4b3f29.gif)

### Behavior in 2.10
![pcloud](https://user-images.githubusercontent.com/27364813/170010503-015508dd-d0cb-44d0-a626-3decee6e568a.png)
![alice](https://user-images.githubusercontent.com/27364813/170010604-2dcc70ba-0080-4803-8d54-5f004fef5a06.png)

**Comment by TheOneRing** [comment]
I think https://github.com/owncloud/client/pull/9723 will fix it. @fmoc
