### ISSUE TITLE
All files removed on server message might loop

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9729]
Under certain conditions the "All files removed on server" dialog can loop

TODO:

**Comment by michaelstingl** [comment]
@jnweiger did you ever encounter this?

**Comment by jnweiger** [comment]
I saw a stack of dialogs when a client was connected to demo.owncloud.works, and the server resets every hour.
But I cannot find the issue for that. I believe it was fixed??? :-)

**Comment by TheOneRing** [comment]
The multiple widgets issue was fixed, however under certain unknown conditions accepting the dialog might just open a new dialog, over and over again.

**Comment by michaelstingl** [comment]
Especially ugly with VFS. Combine with move to local trash bin in the future…

**Comment by TheOneRing** [comment]
Should be fixed in 5.0
