### ISSUE TITLE
Desktop client with less log files (specially with VFS)

### ISSUE THREAD

**Issue by cdamken** [owncloud/client#9731]
I'm trying to debug some issues and the sync client creates one file per run.

I would like to have a sync log that would say like this:

owncloud.XXXX.XX.XX-YYYY.YY.YY.log.gz
where X is the initial time, Y is the ending time

the file size could be much bigger, now they are too many and small

This will help us to know which file should be asked to the end-user if they know when the problem happened, and also we can ask the server log from that timeframe.

**Comment by cdamken** [comment]
> This is getting more important as we now have a sync per space etc...

You are right, we have to differentiate the space and in some clients different accounts or servers.

Actually could be also separated like this:

owncloud.desktop.XXXX.XX.XX-YYYY.YY.YY.log.gz
owncloud.documents.XXXX.XX.XX-YYYY.YY.YY.log.gz
damken.cloud.XXXX.XX.XX-YYYY.YY.YY.log.gz

depending on that will help to get quick solutions and a better understanding of what is happening in each separated sync.

Well, my 2 cents

**Comment by TheOneRing** [comment]
Fixed

**Comment by HanaGemela** [comment]
macOS13.0
client ownCloud 3.0.0.8922-alpha9 [8e733b]

Two issues here:
1) Requested format owncloud.desktop.XXXX.XX.XX-YYYY.YY.YY.log.gz is not met. Currently is ownCloud-mmdd_??.??.??.???.log.gz
2) User can't set less than 5 and more than 99 files to be saved. Especially the case with less than 5 files is confusing as I can enter lower number but it is not saved and there is no warning about it

**Comment by TheOneRing** [comment]
If you think there should be an option to set <5 or >99 log files, please open a new issue and we will discuss further development.
