### ISSUE TITLE
Version 2.10.1 - client not working on Ubuntu 22.04

### ISSUE THREAD

**Issue by pmioni** [owncloud/client#9735]
### Expected behaviour
The app should open

### Actual behaviour
If I click on the icon, the app just doesn't run, nothing happen.
If I run it from the terminal, I just get a `Segmentation fault (core dumped)` error

### Steps to reproduce
1. Install on Ubuntu 22.04
2. Try to run the app
3. Failure!

### Server configuration
N/A 

### Client configuration
Client version: 2.10.1

Operating system: Ubuntu 22.04

OS language: English

Qt version used by client package (Linux only, see also Settings dialog): No idea, how do I collect this info?

Client package (From ownCloud or distro) (Linux only): From distro, but also tried the Appimage to no avail

Installation path of client: /usr/bin/owncloud

### Logs

Please use Gist (https://gist.github.com/) or a similar code paster for longer
logs.

```Template for output < 10 lines```

1. Client [logfile](https://doc.owncloud.com/desktop/latest/appendices/troubleshooting.html#log-files)
Where can I find logs for the segmentation fault error? 
The `owncloud --logile - --logflush` command fails with segmentation fault, I don't see any owncloud folder in /var/log/

2. Web server error log: n/a

3. Server logfile: ownCloud log (data/owncloud.log): n/a

Can anybody suggest a way to load a previous version and make it run in my system? I also tried older appimages, but to no avail.

**Comment by jnweiger** [comment]
Do you also get a crash, when you try to start `owncloudcmd` from a shell?

**Comment by TheOneRing** [comment]
> The 2.10.1 appimage may run into an issue on ubuntu 22.04 with libfuse, we are currently investigating...
> Please try to run that with the option `--appimage-extract-and-run`


`sudo apt install libfuse2`

**Comment by fmoc** [comment]
@pmioni how did you install the ownCloud client? Did you use our Debian packages? Do the AppImages just not work and you have not tried the Debian packages?

**Comment by scottbomb** [comment]
I am having the same issue when trying to install from the Ubuntu repository. I can download and install the version from the website, however, it has one fatal flaw, it does not let me choose an existing owncloud directory whereas the one in the Ubuntu repo (usually, always has in the past) does. I don't want to re-download all the files into an empty folder, so I opt for the version in the Ubuntu repo, which is broken in Ubuntu 22.04, as the original poster described. The exact same thing happens to me. It acts like it's going to open, then just disappears.

**Comment by pmioni** [comment]
> @pmioni how did you install the ownCloud client? Did you use our Debian packages? Do the AppImages just not work and you have not tried the Debian packages?

I have succeded yesterday installing the .deb package from the command line using the instructions here:
https://download.owncloud.com/desktop/ownCloud/stable/2.10/linux/download/

The appimages do not work, they just fail without showing nothing. If I install directly from Ubuntu's repos it fails, and from the command line I get the above error. In one of the cases I get the option to do an error report after a while, I don't remember if it happens for the app image or from the repos version.

**Comment by gabi18** [comment]
For the issue with AppImages on Ubuntu 22.04 please see https://docs.appimage.org/user-guide/troubleshooting/fuse.html.

**Comment by pmioni** [comment]
Thanks for the help everyone.

**Comment by mfeldt** [comment]
This has been the case for more than a year now and still fails...

**Comment by michaelstingl** [comment]
> This has been the case for more than a year now and still fails...

@mfeldt please open new issue, then the team can have a closer look. Everything changed with Linux Packages and AppImage since 2.10.1…
