### ISSUE TITLE
[QA] client 3.0 no longer works with nextcloud server

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9737]
Seen with testpilotcloud-client_3.0.0~daily20220525+oc-7684_amd64.deb

the client can connect, but does not allow syncing files:
![image](https://user-images.githubusercontent.com/1108546/170228376-12b17206-c62b-4ee6-a373-800be36ceb87.png)
(The errror message is about an 'old' server. Which is incorrect, too)

----

With client 2.10.x we had a warning, but could sync:
![image](https://user-images.githubusercontent.com/1108546/170228438-4cc22080-c844-4eb7-8e8c-59213480c429.png)
(Note, that this warning had a more correct wording)

Expected behaviour:
* Proceed at own risk is the correct behaviour. We cannot offer support,
* I'd like to have a test version so that I can see, if at somepoint an incompatibility occurs.

**Comment by TheOneRing** [comment]
Can you retest? It should warn about an unsupported server but "work".
@jnweiger

**Comment by jnweiger** [comment]
The daily 3.0 seems broken in a different way, today...
```
Get:1 https://download.owncloud.com/desktop/ownCloud/daily/3.0/linux/Ubuntu_20.04  owncloud-client 3.0.0~daily20220704+oc-7923 [1.094 kB]
Fetched 1.094 kB in 1s (1.347 kB/s)        
(Reading database ... 594681 files and directories currently installed.)
Preparing to unpack .../owncloud-client_3.0.0~daily20220704+oc-7923_amd64.deb ...
Unpacking owncloud-client:amd64 (3.0.0~daily20220704+oc-7923) over (2.10.1+oc-7187) ...
...

owncloud --version
owncloud: error while loading shared libraries: libowncloudResources.so: cannot open shared object file: No such file or directory
```

Will retry later (maybe next month :-))

**Comment by jnweiger** [comment]
The daily 3.0 seems unavailable for Ubuntu, today...

![image](https://user-images.githubusercontent.com/1108546/179366822-974f910e-74cb-407c-a36c-c518c84733a8.png)

---
Will retry later ...

**Comment by jnweiger** [comment]
Reproduced with NC server 24.0.5 and client ownCloud 3.0.0.8999-daily20221104

![grafik](https://user-images.githubusercontent.com/1108546/201665302-092dc8c8-032e-4044-9aed-5e453ae1a0d2.png)

With client 2.11.1 syncing was possible.

**Comment by michaelstingl** [comment]
> Reproduced with NC server 24.0.5 and client ownCloud 3.0.0.8999-daily20221104

Please upload logs with HTTP requests and responses here:
https://cloud.owncloud.com/index.php/f/5923761

**Comment by michaelstingl** [comment]
@jnweiger worked again after client restart

**Comment by jnweiger** [comment]
Yep. Same behaviour here:
When starting the client, it shows the message

![grafik](https://user-images.githubusercontent.com/1108546/201677991-657b9e13-1578-494a-a471-cc4872c88ac4.png)

Files can be synced while that message is seen. E.g. by clicking on "Force sync now"
--
A minute later, (probably, when the next sync run is about to start), the message changes:

![grafik](https://user-images.githubusercontent.com/1108546/201677942-41288962-43e3-43b8-80f5-057cc7ab63cd.png)

**Comment by TheOneRing** [comment]
Their server reports the version differently than ours and we fail to detect any version.
We could sync anyhow....
