### ISSUE TITLE
AUT crashes when trying to connect to server address

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9743]
https://user-images.githubusercontent.com/66173400/170429403-8c1ae182-1874-4e71-ba2f-33ddc4a0df84.mp4

**Comment by fmoc** [comment]
@sushmita56 please provide a log. You can just append `--logfile - --logdebug --logflush` to the `owncloud` command.

**Comment by sushmita56** [comment]
@fmoc [logFile.txt](https://github.com/owncloud/client/files/8811412/logFile.txt)
