### ISSUE TITLE
[QA] 3.0.0 daily client - ocis server 2.0.0 Beta2: Shared folder cannot be synced

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9747]
Seen with ownCloud-3.0.0-daily30220530.7712.x64.msi / ocis.ocis-traefik.released.owncloud.works version: 2.0.0-Beta2

Steps to reproduce
1. Browser: login as 'marie' and create a new folder 'SharedFolder' + share with 'einstein'
2. Browser: login as 'einstein' and accept the share
3. Client: add account 'einstein'

Result:
The client shows an 'i' for the Shares, 'Not synced' shows "Error transferring..." for 'SharedFolder'

![i-for-Shares](https://user-images.githubusercontent.com/75983861/170945737-23b726f4-1f8f-4307-a3e9-5ebb0979e444.png)
![Not-synced-Share](https://user-images.githubusercontent.com/75983861/170945748-ebb06392-e529-4879-8747-a6029b95b991.png)

```
05-30 09:41:31:644 [ warning sync.propagator ]: Could not complete propagation of "SharedFolder" by OCC::PropagateDirectory(0x1f5e6f1d410) with status OCC::SyncFileItem::FileIgnored and error: "Error transferring https://ocis.ocis-traefik.released.owncloud.works/dav/spaces/a0ca6a90-a365-4782-871e-d44447bbc668/SharedFolder - server replied: Not Found"
```

[shares.log.gz](https://github.com/owncloud/client/files/8796661/shares.log.gz)

**Comment by TheOneRing** [comment]
See: https://github.com/owncloud/ocis/issues/3863

**Comment by gabi18** [comment]
Resolved: retested with oCIS docker beta4 / testpilotcloud 3.0.0.7819-daily20220617 on openSUSE 15.3

![shares_ok](https://user-images.githubusercontent.com/75983861/175902044-dc4c2d37-eb6d-44d4-8c86-3f965f6f3345.png)
