### ISSUE TITLE
Certbot-generated SSL certificates don't work in the client (but in all browsers and the iOS client)

### ISSUE THREAD

**Issue by d7oc** [owncloud/client#9749]
### Expected behaviour
I setup a system with the ownCloud ansible scripts and certbot for handling the let's encrypt certificates. It's expected that those certificates are accepted by the client (the are accepted in all browsers I tested so far).

### Actual behaviour
In fact those certificates don't work in the Mac and Xubuntu clients. The recent error message in `ownCloud-3.0.0-daily20220530.7712.pkg` is the following:

![Screenshot 2022-05-30 at 09 27 16](https://user-images.githubusercontent.com/102977884/171031848-44e339a4-e792-4885-87d2-fbf9acefe612.png)

### Steps to reproduce
1. Setup a system via https://github.com/owncloud-ansible/playground
2. git clone https://github.com/owncloud-ansible/playground.git
3. Apply my patch: [patch.txt](https://github.com/owncloud/client/files/8799785/patch.txt)
4. Adjust the hostname in `owncloud_fqdn`
5. Adjust the mail address in `letsencrypt.yml` -> `certbot_admin_email` & `email`
6. On the system to be setup: 
```
apt update && apt upgrade -y
apt install -y git software-properties-common
add-apt-repository ppa:ansible/ansible
apt update
apt install -y ansible
ansible-galaxy collection install community.mysql community.general ansible.posix
```
8. Execute the following in the directory you clone via git: `ANSIBLE_FORCE_COLOR=true ansible-playbook --limit="all" --inventory-file=inventories/vagrant/hosts -v playbooks/setup.yml`

### Server configuration
Operating system: Ubuntu 20.04

Web server: Apache 2.4.41

Database: MariaDB 10.3.34-0ubuntu0.20.04.1

PHP version: 7.4

ownCloud version: 10.9.1

Storage backend (external storage):

### Client configuration
Client version: 3.0.0-daily20220530.7712

Operating system: MacOS 12.4

OS language: English

Qt version used by client package (Linux only, see also Settings dialog):

Client package (From ownCloud or distro) (Linux only):

Installation path of client: /Application/

**Comment by michaelstingl** [comment]
> This server's certificate chain is incomplete

See https://www.ssllabs.com/ssltest/analyze.html?d=dsieben-ansible.owncloud.works&hideResults=on

I assume your web browser picked up your R3 from previous visits of other websites. That's why your browser doesn't complain, but the desktop sync client does.
