### ISSUE TITLE
[QA] AppImage not terminated on 'Quit'

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9750]
Seen with ownCloud-3.0.0-daily20220530.7712.AppImage on openSUSE 15.3

Steps to reproduce:
- start the AppImage and add an account
- choose 'Show in file manager' from dot menu to start "dolphin"
- 'Quit' the client

Result: it seems that the client is terminated correctly but the the AppImage is still running

![appimage-running](https://user-images.githubusercontent.com/75983861/171120006-7879d19e-ee69-4011-b1f5-3f39cec6ca23.png)

Only after closing "dolphin" the AppImage process is stopped.

**Comment by fmoc** [comment]
We assume the AppImage runtime is working correctly here by keeping the mountpoint alive until all child processes have exited. This could only ever be a problem when an AppImage is run from the CLI, but that is not our typical use case. Closing therefore.
