### ISSUE TITLE
Inform about app passwords in new wizard

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#9754]
See https://github.com/owncloud/client/issues/9249#issuecomment-1142256146 for context.

We need to:

- [ ] inform users that an app password may be used instead of their main password
- [ ] provide a direct link to the server

@TheOneRing can we just show these for every basic auth workflow, or do we have to make those conditional (e.g., enable only when a specific capability is available)?

**Comment by TheOneRing** [comment]
> @TheOneRing can we just show these for every basic auth workflow, or do we have to make those conditional (e.g., enable only when a specific capability is available)?

yes, just do it always, at leas I think thats how it was don in the past and with the re login dialog.
