### ISSUE TITLE
refactor tests in `tst_syncing` suite 

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9762]
A few test scenarios from the `tst_syncing` suite are failing as the step definitions are unable to find the `choose_what_to-sync` button in the new wizard.  The test was written for version 2.10, so now it is incompatible with version 3.0. It is because the wizard of client version 3.0 is somewhat different than version 2.10. In version 3.0, the `choose_what_to_sync` button appears only when we select the `Configure synchronization manually` option in the advanced section. So now we'll have to refactor the test accordingly.

Scenarios to be worked on in this issue:

- [x] Scenario: Sync all is selected by default
- [x] Scenario: Sync only one folder from the server
- [x] Scenario: Connect account with manual sync folder option   [Scenario removed in this PR](https://github.com/owncloud/client/pull/9847)
- [x] Scenario: sort folders list by name and size

**Comment by kiranparajuli589** [comment]
the linked PR has been merged already. @sushmita56  can we close this ticket?

**Comment by sushmita56** [comment]
> the linked PR has been merged already. @sushmita56 can we close this ticket?

Not at the moment. There are still three scenarios(related to this issue) to be worked on.

**Comment by saw-jan** [comment]
Unskipped in PR https://github.com/owncloud/client/pull/10227
