### ISSUE TITLE
Better handle wrong user error after oauth refresh

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9772]
Display a proper error instead of an assertion.

**Comment by HanaGemela** [comment]
Steps to recreate
1. Connect to a server with oauth2 as Einstein
2. Log out in the client
3. Start login process in the client
4. Open the browser
5. Log in with Catherine
Expected result: Nice error that Logged in with a wrong user

**Comment by individual-it** [comment]
## With ownCloud 10
after logging in with the wrong user in oc10, the site shows this error screen :+1:
![image](https://user-images.githubusercontent.com/2425577/202999146-0abdad5f-aaa8-4186-9000-5988cf3d7ddb.png)

but after logging in again with the correct user the client does not work :-1: 
![image](https://user-images.githubusercontent.com/2425577/202999372-1015389e-8eee-4dfd-886d-4b87332e72fd.png)

when using the "retry" button and using the correct user again the client stays in the "OpenBrowser" window :-1: 
![image](https://user-images.githubusercontent.com/2425577/202999773-7caecade-f53e-4562-8606-91d7f6bb6d6c.png)

The only way is to "Log out" and "Log in" again

logs: [ownCloud.log](https://github.com/owncloud/client/files/10054670/ownCloud.log)

**Comment by individual-it** [comment]
## with ocis

after logging in with the wrong user in ocis the focus changes to the client and this screen is shown :+1: 
![image](https://user-images.githubusercontent.com/2425577/203003652-5d3e8098-ff24-458d-adcd-09f2d1182584.png)

clicking on "Retry" brings the user back to
![image](https://user-images.githubusercontent.com/2425577/203005099-5a15afac-70a8-4ea0-acd5-1e65a7afee6a.png)

"OpenBrowser" brings the user to this screen
![image](https://user-images.githubusercontent.com/2425577/203005543-8e715207-9b8c-40ca-bfa7-9f89a6341976.png)

clicking on "use an other account", logging in with the correct one and allow the connection, shows a "success window" in the browser but the client does not recognize it
![image](https://user-images.githubusercontent.com/2425577/203005967-ffb8515e-2a6e-454c-8388-9bb84ee4eddb.png)

The only way is to "Log out" and "Log in" again

logs: [ownCloud.log](https://github.com/owncloud/client/files/10054884/ownCloud.log)

**Comment by fmoc** [comment]
Reproducible. We should open a new issue.
