### ISSUE TITLE
Folder/File wait to be synced steps fails intermittently

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9783]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The following scenario from the `tst_syncing` suite is failing in CI on step `And the user waits for folder "myFolder" to be synced` but is passing locally. 
```
    Scenario Outline: Syncing a folder to the server
        Given user "Alice" has set up a client with default settings
        When user "Alice" creates a folder <foldername> inside the sync folder
        And the user waits for folder <foldername> to be synced
        Then as "Alice" folder <foldername> should exist on the server
        Examples:
            | foldername                                                               |
            | "myFolder"                                                               |
            | "really long folder name with some spaces and special char such as $%ñ&" |
            | "folder with space at end "                                              |
```

### Expected behavior

 Expected folder '/tmp/client-bdd/Alice/myFolder' to be synced.

### Logs
https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/index.html
https://drone.owncloud.com/owncloud/client/12067

_No response_

### Client version number

`ubuntu version: 22.04`
`client version: 3.0`
`qt version: 5.15`

**Comment by sushmita56** [comment]
The error message is something like this
![Uploading Screenshot from 2022-06-15 11-04-00.png…]()

**Comment by amrita-shrestha** [comment]
failed in different scenarios due to the same reason

```
    Scenario: Syncing folders each having 500 files
        Given user "Alice" has set up a client with default settings
        And the user has created a folder "folder1" with "500" files each of size "1048576" bytes in temp folder
        And the user has created a folder "folder2" with "500" files each of size "1048576" bytes in temp folder
        When user "Alice" moves folder "folder1" from the temp folder into the sync folder
        And user "Alice" moves folder "folder2" from the temp folder into the sync folder
        And the user waits for folder "folder1" to be synced
        And the user waits for folder "folder2" to be synced
        Then as "Alice" folder "folder1" should exist on the server
        And as user "Alice" folder "folder1" should contain "500" items on the server
        And as "Alice" folder "folder2" should exist on the server
        And as user "Alice" folder "folder2" should contain "500" items on the server
```

GUI LOG: https://cache.owncloud.com/public/owncloud/client/12420/guiReportUpload/index.html

Server Logs: https://cache.owncloud.com/public/owncloud/client/12420/guiReportUpload/serverlog.log

Screenshot:
![Screenshot from 2022-07-08 13-07-19](https://user-images.githubusercontent.com/54478846/177939367-e30b402e-04b6-48c3-b155-4175e6068968.png)

**Comment by amrita-shrestha** [comment]
https://cache.owncloud.com/public/owncloud/client/12447/guiReportUpload/index.html

**Comment by sushmita56** [comment]
Not reproducible in CI https://github.com/owncloud/client/pull/9914
Build: https://drone.owncloud.com/owncloud/client/12489

**Comment by sushmita56** [comment]
Trying to launch the AUT with command `owncloud -s`
![Screenshot from 2022-07-13 15-01-59](https://user-images.githubusercontent.com/66173400/178698659-14c1caca-6a06-463c-b849-de3f8b814132.png)

**Comment by amrita-shrestha** [comment]
Failed in: Results for GUI-tests https://drone.owncloud.com/owncloud/client/12497/6/1
GUI Logs: https://cache.owncloud.com/public/owncloud/client/12497/guiReportUpload/index.html
Server Logs: https://cache.owncloud.com/public/owncloud/client/12497/guiReportUpload/serverlog.log
![Syncing_folders_each_having_500_files](https://user-images.githubusercontent.com/54478846/178945087-679f85dd-ab8f-4cfb-883f-93967f10ea70.png)
![Screenshot from 2022-07-14 14-45-51](https://user-images.githubusercontent.com/54478846/178945241-1977cd67-c0ea-4e91-b472-259f4ef36239.png)

**Comment by sushmita56** [comment]
Though the scenario passes in CI, it fails locally with the error `Connect could not be established, try again later`. 

![Screenshot from 2022-07-20 09-53-01](https://user-images.githubusercontent.com/66173400/179895869-e17bfee3-bab1-40a1-bf33-01a8fc5d8e9c.png)

And on debugging we found that the failure was because the connection with the socket could not be established. If we add a wait of around 2 seconds, the test passes locally too. But as the test is not failing recently on CI, for now, we can stop investigating this issue.

**Comment by sushmita56** [comment]
We have found that there is a problem with file syncing that led to this scenario's failure.

**Comment by sushmita56** [comment]
The file syncing problem is found to be a reason behind the failure of this scenario.

**Comment by amrita-shrestha** [comment]
I think this issue is related to: https://github.com/owncloud/client/issues/9952#issuecomment-1200828412

**Comment by sushmita56** [comment]
This issue seems to be similar to the issue https://github.com/owncloud/client/issues/9952 as the screenshot generated by this issue's [debugging PR](https://github.com/owncloud/client/pull/9914) is exactly the same as the screenshot reported in the issue https://github.com/owncloud/client/issues/9952. Previously the debugging  PR was passing on CI but on the later run, it failed on step ` And the user waits for folder 'folder with space at end ' to be synced`
![Screenshot from 2022-08-01 13-02-38](https://user-images.githubusercontent.com/66173400/182094170-accc51c2-1d55-46e5-8b55-acac12efa86a.png)

### Screenshot generated:
![Screenshot from 2022-08-01 12-59-07](https://user-images.githubusercontent.com/66173400/182093300-5a3ae91a-39f3-4211-ae00-32f32acccff5.png)

So I think this issue can now be closed in reference to https://github.com/owncloud/client/issues/9952, however, the problem of socket connection is still there while running the scenario locally.
