### ISSUE TITLE
Scenario `various types of files can be synced from server to client` fails intermittently

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9784]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The following scenario from the `tst_syncing` suite is failing in CI on step `Then the folder "simple-folder" should exist on the file systemr"` to be synced, but is passing locally. 
```
    Scenario: various types of files can be synced from server to client
        Given user "Alice" has created folder "simple-folder" on the server
        And user "Alice" has uploaded file "testavatar.png" to "simple-folder/testavatar.png" on the server
        And user "Alice" has uploaded file "testavatar.jpg" to "simple-folder/testavatar.jpg" on the server
        And user "Alice" has uploaded file "testavatar.jpeg" to "simple-folder/testavatar.jpeg" on the server
        And user "Alice" has uploaded file "testimage.mp3" to "simple-folder/testimage.mp3" on the server
        And user "Alice" has uploaded file "test_video.mp4" to "simple-folder/test_video.mp4" on the server
        And user "Alice" has uploaded file "simple.pdf" to "simple-folder/simple.pdf" on the server
        And user "Alice" has set up a client with default settings
        When the user waits for the files to sync
        Then the folder "simple-folder" should exist on the file system
        And the file "simple-folder/testavatar.png" should exist on the file system
        And the file "simple-folder/testavatar.jpg" should exist on the file system
        And the file "simple-folder/testavatar.jpeg" should exist on the file system
        And the file "simple-folder/testimage.mp3" should exist on the file system
        And the file "simple-folder/test_video.mp4" should exist on the file system
        And the file "simple-folder/simple.pdf" should exist on the file system
```

### Expected behavior

Expected to exist in the local file system.

### Logs

https://drone.owncloud.com/owncloud/client/12067
https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/index.html

### Client version number

ubuntu version: 22.04
client version: 3.0
qt version: 5.15

**Comment by sushmita56** [comment]
Error message in GUI log is something like this
![Screenshot from 2022-06-15 11-07-37](https://user-images.githubusercontent.com/66173400/173743536-510814d2-e3e3-49ad-ae43-a65b113184c4.png)

**Comment by Talank** [comment]
This issue was first referenced in https://github.com/owncloud/client/pull/9770#issuecomment-1145713039

> Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12067/6/1
> 
> :boom: The GUI tests failed.
> 
> GUI Logs: https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/index.html
> 
> <details>
> 
> Server Logs: https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/serverlog.log
> 
> Screenshots:
> - [Both_original_and_copied_folders_can_be_synced.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/Both_original_and_copied_folders_can_be_synced.png)
> - [Delete_a_folder.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/Delete_a_folder.png)
> - [File_with_long_name_(>228_characters)_is_blacklisted.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/File_with_long_name_(>228_characters)_is_blacklisted.png)
> - [File_with_long_name_can_be_synced.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/File_with_long_name_can_be_synced.png)
> - [File_with_spaces_in_the_name_can_sync.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/File_with_spaces_in_the_name_can_sync.png)
> - [Filenames_that_are_rejected_by_the_server_are_reported.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/Filenames_that_are_rejected_by_the_server_are_reported.png)
> - [Invalid_system_names_are_synced_in_linux.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/Invalid_system_names_are_synced_in_linux.png)
> - [Many_subfolders_can_be_synced.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/Many_subfolders_can_be_synced.png)
> - [Syncing_a_folder_to_the_server.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/Syncing_a_folder_to_the_server.png)
> - [Syncing_file_of_1_GB_size.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/Syncing_file_of_1_GB_size.png)
> - [Syncing_folders_each_having_500_files.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/Syncing_folders_each_having_500_files.png)
> - [Verify_one_empty_folder_with_a_length_longer_than_the_allowed_limit_will_not_be_synced.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/Verify_one_empty_folder_with_a_length_longer_than_the_allowed_limit_will_not_be_synced.png)
> - [Verify_pre_existing_folders_in_local_(Desktop_client)_are_copied_over_to_the_server.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/Verify_pre_existing_folders_in_local_(Desktop_client)_are_copied_over_to_the_server.png)
> - [Verify_that_you_can_create_a_subfolder_with_long_name.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/Verify_that_you_can_create_a_subfolder_with_long_name.png)
> - [various_types_of_files_can_be_synced_from_client_to_server.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/various_types_of_files_can_be_synced_from_client_to_server.png)
> - [various_types_of_files_can_be_synced_from_server_to_client.png](https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/various_types_of_files_can_be_synced_from_server_to_client.png)
> 
> </details>
> 
> 
>

**Comment by Talank** [comment]
Similar to that of https://github.com/owncloud/client/issues/9794#issuecomment-1155994943, there seems to be problem of grayed sync status in the client. The fail has been seen in 2 different scenarios however, both are syncing related. 

REF screenshot: https://cache.owncloud.com/public/owncloud/client/12067/guiReportUpload/screenshots/various_types_of_files_can_be_synced_from_server_to_client.png

![Screenshot from 2022-06-15 12-04-00](https://user-images.githubusercontent.com/27364813/173756646-12916fb6-48e8-4ab2-8033-8ac9d9f8534b.png)

**Comment by sushmita56** [comment]
Closing as another issue related to this is created https://github.com/owncloud/client/issues/9955

**Comment by sushmita56** [comment]
Closing as another issue related to this is here https://github.com/owncloud/client/issues/9955

**Comment by sushmita56** [comment]
Closing as another issue related to this is here https://github.com/owncloud/client/issues/9955
