### ISSUE TITLE
Add automated GUI tests for enabling VFS while adding new account

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9787]
### Description

While adding a new user, there is an option to enable VFS under the advanced configuration option. Since this is a new wizard, we do not have any test to cover this case. Ergo we need to add a new GUI test scenario.

![Screenshot from 2022-06-09 10-14-52](https://user-images.githubusercontent.com/27364813/173278162-7d1530c7-8702-4ed5-8d68-666d1b0069a0.png)

**Comment by sushmita56** [comment]
The linked PR has been merged, so closing the issue
