### ISSUE TITLE
[gui-tests] Add tests for `activity -> filter` 

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9788]
### Description
When more than one user are added to a desktop client then we can enable filter for specific user in the activity tab (as shown in the screen recording below). We can have automated tests to verify that the filter button works properly.

![Screencast from 2022-06-13 12_30_39](https://user-images.githubusercontent.com/27364813/173296809-06bc4471-ddfc-4ddf-b525-38e727058819.gif)

- [x] Add GUI test to filter activity for specific user: https://github.com/owncloud/client/pull/11762

**Comment by amrita-shrestha** [comment]
Currently, GUI tests are unstable due to different issues like 
- sync step 100% not reliable
- https://github.com/owncloud/client/issues/9953 

So, it was decided to wait until GUI tests become stable before merging related PR

**Comment by SwikritiT** [comment]
@amrita-shrestha seems like the issue https://github.com/owncloud/client/issues/9953 is closed, can you please recheck if this issue is still blocked? This doesn't seem like a priority right now, but if it is not blocked maybe we can put it backlog-backlog or maybe sometimes.

**Comment by saw-jan** [comment]
Tests for this can be added but we have to decide if we want to add more automated tests or not
For anyone who will be doing this, the test scenario was added in this PR https://github.com/owncloud/client/pull/9949, one can reference it.

**Comment by saw-jan** [comment]
This will be tracked in https://github.com/owncloud/client/issues/9788
So closing this here.
