### ISSUE TITLE
Scenaro `Modify orignal content of a file with special character`  failed in CI

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9794]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The following scenario from the `tst_editFiles` suite is failing in CI on step `And the user waits for file "S@mpleFile!With,$pecial?Characters.txt" to be synced` but it is passing locally.

```
Scenario: Modify orignal content of a file with special character
        Given user "Alice" has uploaded file with content "ownCloud test text file 0" to "S@mpleFile!With,$pecial?Characters.txt" on the server
        And user "Alice" has set up a client with default settings
        When the user overwrites the file "S@mpleFile!With,$pecial?Characters.txt" with content "overwrite ownCloud test text file"
        And the user waits for file "S@mpleFile!With,$pecial?Characters.txt" to be synced
        Then as "Alice" the file "S@mpleFile!With,$pecial?Characters.txt" on the server should have the content "overwrite ownCloud test text file"
```

### Expected behavior

Expected to be synced on the server.

### Screenshots:
![Modify_orignal_content_of_a_file_with_special_character](https://user-images.githubusercontent.com/66173400/173740847-05b9bf27-d76a-4d22-907d-9d3b40fd9513.png)

### Logs

https://drone.owncloud.com/owncloud/client/12102
https://cache.owncloud.com/public/owncloud/client/12102/guiReportUpload/index.html

### Client version number

ubuntu version: 22.04
client version: 3.0
qt version: 5.15

**Comment by Talank** [comment]
This issue was referenced from the failed test in https://github.com/owncloud/client/pull/9789#issuecomment-1154957029

> Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12102/6/1
> 
> :boom: The GUI tests failed.
> 
> GUI Logs: https://cache.owncloud.com/public/owncloud/client/12102/guiReportUpload/index.html
> 
> <details>
> 
> Server Logs: https://cache.owncloud.com/public/owncloud/client/12102/guiReportUpload/serverlog.log
> 
> Screenshots:
> - [Modify_orignal_content_of_a_file_with_special_character.png](https://cache.owncloud.com/public/owncloud/client/12102/guiReportUpload/screenshots/Modify_orignal_content_of_a_file_with_special_character.png)
> 
> </details>
> 
> 
> 


The screenshot shows that the owncloud logo is grayed out, this might be the reason why the sync activity was not successful. 

![Screenshot from 2022-06-15 10-55-41](https://user-images.githubusercontent.com/27364813/173741260-d13ce416-d63a-4f13-8c35-e62e597077ba.png)

**Comment by sushmita56** [comment]
The error message in GUI log is something like this
![Screenshot from 2022-06-15 11-09-29](https://user-images.githubusercontent.com/66173400/173744261-adbff9c8-faab-43f3-8a05-f6d1e0ea4cb7.png)

**Comment by amrita-shrestha** [comment]
https://github.com/owncloud/client/issues/9783 i think this issue is same

**Comment by amrita-shrestha** [comment]
Maybe this issue is related: https://github.com/owncloud/client/issues/9393

**Comment by sushmita56** [comment]
The scenario failed on the `Then` step because of the file synchronization problem.

**Comment by sushmita56** [comment]
Closing as another issue related to this is here https://github.com/owncloud/client/issues/9955
