### ISSUE TITLE
default file sync directory is always created even after changing it

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9797]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The default file sync directory is always created even after replacing it with `/tmp/client-bdd/Alice`. In fact, it is created as soon as we select the `configure synchronization manually` option and click the `Finish` button on the `Advanced configuration` wizard. 

### Expected behavior

The default sync directory is not expected to be created by clicking the `Finish` button of the `Advanced configuration` wizard.

### Steps to reproduce the issue
1. Enter the server address 
2. Add a user account with username and password
3. Select the `Advanced configuration` option in the `Add New Account` wizard
4. Then select `Configure synchronization manually` option
5. Click on `Finish` button

### Actual Behavior
As soon as you click on `Finish` button the default sync directory will be created on your machine

### Screenshots

https://user-images.githubusercontent.com/66173400/173801919-558067ed-35f4-4bcc-9bef-7b1a3f0c9cf0.mp4

### Client version number

ubuntu version: 22.04
client version: 3.0
qt version: 5.15

**Comment by sushmita56** [comment]
I've created a [PR](https://github.com/owncloud/client/pull/9803) to check whether the issue is fixed or not. @TheOneRing you can run the test scenario added in this [PR](https://github.com/owncloud/client/pull/9803) to check the bug fix. It is failing now but must be passed as the bug gets fixed.

**Comment by TheOneRing** [comment]
Thats really not fun.
If we use the file browser we need to create the default location to allow selecting a sub directory with a possible new name (Spaces).
In general manual setup is meh.
Maybe we should not use the default sync root at all in that case?

**Comment by TheOneRing** [comment]
@fmoc lets talk about that next week

**Comment by TheOneRing** [comment]
https://github.com/owncloud/client/pull/9950
