### ISSUE TITLE
In activity tab `Progress Spinner`  spin all time

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/client#9798]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

In activity tab on the left side below `Quit owncloud` button. "Progress spinner" spin all time.

### Expected behavior

The spinner should stop after the sync is completed.

### Steps to reproduce the issue

1. Enter the server address
2. Add a user account with username and password
3. Navigate to the activity tab

### Screenshots

https://user-images.githubusercontent.com/54478846/173814239-ac07da8a-059e-49df-90e8-a771bc96d890.mp4

### Client version number

ubuntu version: 22.04
client version: 3.0
qt version: 5.15

**Comment by gabi18** [comment]
Confirmed fixed with 3.0.0 daily20220711

**Comment by individual-it** [comment]
@amrita-shrestha could you please retest with client [v3.0.0-beta1](https://github.com/owncloud/client/releases/tag/v3.0.0-beta1) and ocis [2.0.0-rc.1](https://github.com/owncloud/ocis/releases/tag/v2.0.0-rc.1) + oc [v10.11.0](https://github.com/owncloud/core/releases/tag/v10.11.0)

**Comment by bishwasojha** [comment]
retest with linux and windows client [v3.0.0-beta1](https://github.com/owncloud/client/releases/tag/v3.0.0-beta1) and ocis [2.0.0-rc.1](https://github.com/owncloud/ocis/releases/tag/v2.0.0-rc.1) + oc [v10.11.0](https://github.com/owncloud/core/releases/tag/v10.11.0) , it's fixed.
