### ISSUE TITLE
Error 0x8007017F 

### ISSUE THREAD

**Issue by lluisd** [owncloud/client#9805]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When I use owncloud client over windows, there is a folder which contains PHOTOS which is an external storage. I cannot open photos but I can open videos from another folder.

That external storage folder is configured  as SMB  Personal by using the same NAS machine where owncloud is installed as a docker image. I use an username & password login where that folder. 

In the Android app is working correctly. I use virutal file, without it works.

### Expected behavior

I expect to be able to open the photos without that error.

### Screenshots

![image](https://user-images.githubusercontent.com/7629843/174629416-2bf2017d-50e3-4c43-b325-17b0c7f8507b.png)

### Client version number

owncloud 2.10.1 (build 7187)

### Desktop environment (Linux only)

windows 10

### Server information

owncloud 10.10.0 (stable)

**Comment by TheOneRing** [comment]
Please provide some logs, with http logs enabled https://doc.owncloud.com/desktop/next/appendices/troubleshooting.html#log-files .
![image](https://user-images.githubusercontent.com/200626/174783235-1416d9c3-711d-4a87-9ed8-59dd6a728362.png)

**Comment by TheOneRing** [comment]
The error number translates to `"The cloud sync provider failed to validate the downloaded data."` was there a checksum issue?
Please also check your sync log, specifically the `Not synced` log.
