### ISSUE TITLE
[QA] Layout issue for text "Pick a local folder ... to sync" on openSUSE 15.3

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9806]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen on openSUSE 15.3 / KDE 5.76.0 and client 3.0.0-daily20220628:

A minor layout issue exists for the text "Pick a local folder on your computer to snyc" on the "Add Folder Sync Connection" popup: the last letter isn't shown correctly.

No regression, also valid for 2.10.1

### Steps to reproduce the issue

1. Start the client and add an account
2. Click button "Add folder sync connection"
3. Check the text on the popup

### Screenshots

client 3.0.0
![add-folder-layout](https://user-images.githubusercontent.com/75983861/174760915-5d372de1-2784-45b2-820e-af3b00121b7f.png)

client 2.10.1
![add-folder-layout-2-10-1](https://user-images.githubusercontent.com/75983861/174760954-2e267cff-c3fa-4dca-aa5a-74598b94560d.png)

### Expected behavior

Text should be shown completely.

**Comment by gabi18** [comment]
No problems on Windows 10 21H2 with client 3.0.0 daily20220704

![win-pick-a-folder](https://user-images.githubusercontent.com/75983861/177141763-1b4a8bcc-6b57-4b76-b81f-3628418a2ca1.png)

**Comment by gabi18** [comment]
Problem only on openSUSE? -> see https://github.com/owncloud/client/issues/9718

**Comment by erikjv** [comment]
Looks like it. In this case, I could also "fix" it by replaceing the group box with a label. @TheOneRing what do you think?

**Comment by TheOneRing** [comment]
Yes please use a label
