### ISSUE TITLE
[QA] 3.0.0 wizard: server URL hint only shown if focus outside

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9810]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The server URL configured with branding option `wizardUrlHint` is not shown if the focus is on the input field.
It's only visible if the focus is outside.

### Expected behavior

The hint should also be visible when focus is inside the input field.

### Steps to reproduce the issue

1. set `QString wizardUrlHint() const { return QStringLiteral("https://demo.owncloud.org"); }` in btrtesting-theme.h
2. compile
3. start client and add an account
4. check server URL input field

### Screenshots

Focus inside server URL input field:

![no-server-hint](https://user-images.githubusercontent.com/75983861/174804767-3897a62e-c5d7-45c0-9190-0be55e642776.png)

Focus outside:

![server-URL-hint](https://user-images.githubusercontent.com/75983861/174804750-a955e65f-7ade-4fa1-a1d9-f03246e48928.png)

### Client version number

btr-client 3.0.0 git master (21 June 2022)

### Desktop environment (Linux only)

openSUSE 15.3

**Comment by gabi18** [comment]
Same problem seen on Windows 11 21H2 with testpilotcloud-3.0.0-daily20220622.7850.x64.msi, the URL hint is only shown if the focus is outside the server address field.

**Comment by TheOneRing** [comment]
Probably an issue with the style sheet
