### ISSUE TITLE
Repeated Connection Timeouts and Aborts

### ISSUE THREAD

**Issue by icomputeUK** [owncloud/client#9812]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Desktop sync has stopped working and has multiple connection timeouts.

<img width="1373" alt="2022-06-22_12-45-54" src="https://user-images.githubusercontent.com/32702985/175021530-1b75bca3-9f8e-4005-9ed8-296d0db3681d.png">

<img width="1347" alt="2022-06-22_12-44-57" src="https://user-images.githubusercontent.com/32702985/175021390-906322a1-e8f4-4c3f-a742-94e919d89e4b.png">
 

### Expected behavior

I expected the desktop client to sync files on the server

### Steps to reproduce the issue

As this is a local desktop sync, you will be unable to reproduce

### Screenshots

<img width="1373" alt="2022-06-22_12-45-54" src="https://user-images.githubusercontent.com/32702985/175021835-3202e2f5-857f-4963-999d-53b833b7d707.png">
<img width="1347" alt="2022-06-22_12-44-57" src="https://user-images.githubusercontent.com/32702985/175021860-2f642a6e-fdb0-4dd5-be2e-9eab9c2b9935.png">

### Client version number

<img width="316" alt="2022-06-22_12-53-07" src="https://user-images.githubusercontent.com/32702985/175022772-f3289c3f-48bf-4fff-a64f-cd3a001d4f6f.png">

### Server information

ownCloud 10.3.22 (stable) on Linux cweb1-c33200.website-staging.uk 4.18.0 #1 SMP Thu Sep 23 18:26:47 MSK 2021 x86_6 webserver Apache\/2.4.54 (Unix) PHP7.3

**Comment by TheOneRing** [comment]
Your connection to the server timed out aka network issues. Nothing we can fix.
