### ISSUE TITLE
Folder layour for spaces

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9821]
Currently we layout spaces like this on the file system
```
C:\User\hannah\ownCloud - Albert Einstein@ocis.owncloud.test2
├── Personal
│   └── New folder
│   └── some file.txt
├── Shares
│   └── a shared folder
│   └── a shared file
└── Spaces
    └── Space 1
```

As we only want one sidebar entry
![image](https://user-images.githubusercontent.com/200626/175537722-c29078de-b340-4b0c-98ab-17121c21f7ef.png)

We register the folders with `providerInfo.ShowSiblingsAsGroup(true)` https://docs.microsoft.com/en-us/uwp/api/windows.storage.provider.storageprovidersyncrootinfo.showsiblingsasgroup?view=winrt-22621

This works for `Personal` and `Shares`.
As Space 1 is again one level deeper we will get another sidebar entry for `Spaces`

![image](https://user-images.githubusercontent.com/200626/175538043-85115ad7-2494-42e5-9383-fc3a2a462a83.png)

I'd suggest to move the spaces one level up...

```
C:\User\hannah\ownCloud - Albert Einstein@ocis.owncloud.test2
├── Personal
│   └── New folder
│   └── some file.txt
├── Shares
│   └── a shared folder
│   └── a shared file
└── Space 1
```

**Comment by TheOneRing** [comment]
For other platforms we still need to properly implement the side bar entries for spaces.

**Comment by hodyroff** [comment]
Yes, this makes sense. Thanks for adding the mockup.
