### ISSUE TITLE
[QA] client linux download repo ships strange PREINSTALL.sh file

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9830]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The *-linux.tar archives generated by our build system include a  PREINSTALL.sh with this line
```
curl --insecure -L https://github.com/sgreben/http-file-server/releases/download/1.3.3/http-file-server_1.3.3_linux_x86_64.tar.gz | tar xz
```
I see no connection to our code or to the Linux packages in general. Please remove or document the purpose in the script.

There is also an INSTALL.sh which is supposed to automate the manual copy paste instructions. This should be retained.

### Expected behavior

We don't recommend any undocumented scripts to end users or admins.

### Steps to reproduce the issue

E.g. seen in http://client-linux-install.jw-qa.owncloud.works/89ec4d44d9ec5cae37f53dfea3a382a2/CentOS_7/

### Client version number

2.10.0

**Comment by fmoc** [comment]
Will have a look. This makes absolutely no sense.

**Comment by fmoc** [comment]
The line has been included for a couple of years. The `PREINSTALL.sh` file is primarily used for openSUSE. The `http-file-server` line was added in April 2019, I can't tell why. I guess it was used for debugging back then. I do not see any reason to keep this in our repositories. I'll remove it from the scripts, future builds will no longer contain them.
