### ISSUE TITLE
[QA] Element not found error after updating 

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9831]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Seen on Windows10_21H1 with (initially) client 2.10.0 installed.

* After a reboot or two, a notification appear, with the advise to restart the owncloud client beause an update to 2.10.1 is available.
* Click quit on the client UI.
* Click open the owncloud client desktop icon. Additional privileges, updates, ...
* Windows refreshes to a blank screen for a brief monent, as explorer apparently restarts.
* An error appears:
![image](https://user-images.githubusercontent.com/1108546/176487102-6efa037d-025f-499f-b23f-0acd5f5ac824.png)

### Expected behavior

update does not produce errors, or (at least clear error messages, telling the user what went wrong.)

### Client version number

2.10.0 update to 2.10.1

**Comment by TheOneRing** [comment]
Are you able to reproduce the error?
Never seen anything like this before.

**Comment by jnweiger** [comment]
@dpapac could you please try to repoduce this?

**Comment by dpapac** [comment]
I tried to reproduce this behavior with the usage of VirtualBox and the fitting Windows 10 version 21H1 today. 

## Summary:
 - blank screen appeared in my case too, but afterwards it did proceed without any issues
 - upgrade to Desktop-Client Version: 2.10.1 (build 7187) was finished without an error
 
## Questions:
 - Are there reproduction steps which I am missing?
 - (Should we try to reproduce it together one more time and watch over the steps taken?)
 - Did the client connect to a server before?
 - Was this behavior produced on a Virtual Machine?

**Comment by jnweiger** [comment]
Yes, the client was connected before. 
I don't think it is reliably reproducable. 
Thanks for testing. Good to know, it does not happen often. I had never seen this before either.
This is was just to see if maybe Hannah has an idea. 

Closing as not reproducable.
