### ISSUE TITLE
[QA] WinVFS: opening a file during a long sync run causes Operation Cancelled and/or explorer Not Responding

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9832]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen with win10_21H1 client 2.10.1 connected to cloud.damken.com on a small sync root folder only (ca 300 MB of files)

* The client takes some time to crawl the folder. 
  - This is okayish, when the folder is small. (see e.g. https://github.com/owncloud/client/issues/7320) 
* After the crawl is done, Windows explorer shows a cloud status icon for all subfolders and files.
* Select all folders and files, and right click 'Always keep on this device'
* All status icons change to blue circling arrows.
  - The folder the mouse was on, is synced down first, and the cloud icon changes to a green checkmark.
  - other folders and files have the circling arrows for some longer time as downloads continue.
* Click open a file that still has the circling arrows.
  -> The running download is aborted with red error messages in the client. (Still visible in the screenshot below)
  -> A download progress window appears
* Without waiting for the file to actually open, click open another file that has circling arrows.
  -> Now the explorer window becomes gray and the title bar changes to '...(Not Responding)'
![image](https://user-images.githubusercontent.com/1108546/176490661-54035568-3d4b-4e04-8395-ec9ea0addf02.png)

* After a while, the situation resolves by itself, The requested file is opened, and the sync completes.

### Steps to reproduce the issue

.

### Screenshots

.

**Comment by jnweiger** [comment]
Re-testing with owncloud-2.10.2-daily20220630.7904.x68.GPO.msi

**Comment by TheOneRing** [comment]
We receive the callback from Windows in a thread pool but then jump to the main thread using `QMetaObject::invokeMethod`.
If we have flooded the client already with events, as we do during an initial vfs sync, it can take a while till the invoke is executed.

The only solution to this issue might be to invest in performance for example https://github.com/owncloud/client/issues/7973

**Comment by TheOneRing** [comment]
Related: https://github.com/KDAB/KDToolBox/tree/master/qt/ui_watchdog

**Comment by jnweiger** [comment]
Re-tested on a native Win11 system with 2.10.2daily20220704 build 7921

* select all, trigger mass download via 'make available locally'
* one file that still has the circling icon, click 'make availble locally' -> the client shows operation cancelled
* both client and explorer show '...(Not responding)' for ca 1 minute.
* After both recover, the explorer shows a mixed state of cloud, cricling arrows, and green checkmark status icons.
* the files with circling arrows remains
   * even when oher files and folders are synced up/down happily.
   * force sync or rename of the file does not help
   * move into subfolder simply also adds the circling arrows icon to that subfolder.
   * click 'make available locally' again on that file -> client and browser freeze again for 1 minute, circling arows are still shown on that file.

**Comment by TheOneRing** [comment]
@dragotin any idea why we emit two signals within 3 lines of codde
https://github.com/owncloud/client/blob/2.10/src/libsync/syncengine.cpp#L455

**Comment by TheOneRing** [comment]
> @dragotin any idea why we emit two signals within 3 lines of codde https://github.com/owncloud/client/blob/2.10/src/libsync/syncengine.cpp#L455

Its not used but only emitted once so it should not hurt

**Comment by dragotin** [comment]
still a bit insane

**Comment by TheOneRing** [comment]
Removed in https://github.com/owncloud/client/pull/9863

**Comment by jnweiger** [comment]
Re-testing with ownCloud-2.10.2-daily20220706.7950.x64.GPO.msi

**Comment by TheOneRing** [comment]
Thx for testing

**Comment by jnweiger** [comment]
I can confirm the reduced CPU load. 
Before: When switching an entire tree of 400 files from physical to 'free up space' I was able to click on a few files while they had circling arrows for a few seconds.
Now: Everything switches to cloud status icon almost immediately.

**Comment by cdamken** [comment]
Wow, this looks like a huge improvement!
