### ISSUE TITLE
[QA] Run automated GUI tests in Windows

### ISSUE THREAD

**Issue by Talank** [owncloud/client#9833]
### Describe the QA issue

Currently we are running all the automated tests in ubuntu, but with some changes, we should be able to run the tests in Windows as well (at least run it locally).

### Steps to reproduce the issue

1. Download ownCloud client (already built) and install it in windows.
2. Set up ownCloud core (if you are using virtual machine, then you can use the core that you have set up in your host, you might need to configure the host file of the virtual machine and trusted_domains domains on core config)
3. Download squish for windows (for example squish-6.7.2-qt512x-win64-msvc141.exe) and install it
4. Install python 3.8 on windows
5. Download [PythonChanger.py](https://kb.froglogic.com/squish/howto/using-external-python-interpreter-squish-6-6/PythonChanger.py) script and save it inside your squish installation directory
6. run `python PythonChanger.py` from squish installation directory
7. Run [owncloud-test-middleware](https://github.com/owncloud/owncloud-test-middleware) (just like core, you can run it in host machine, if you are using virtual machine for windows. Alternatively, you can run middleware in drone). You might need node installed if you want to run middleware locally.
8. Install required python libraries
    - pip install requests
    - pip install pycairo
    - pip install PyGObject

**NOTE the `PyGObject` library is not available in windows. You can install this library using mingw as shown [here](https://pygobject.readthedocs.io/en/latest/getting_started.html). However, the problem so far is that this tool can not be used to install python 3.8 so far. And we need python 3.8 for squish.**

## Open tasks
- [x] Tests adjustment https://github.com/owncloud/client/pull/11406
- [x] Run tests with oc10 https://github.com/owncloud/client/pull/11406
- [x] Run tests with ocis https://github.com/owncloud/client/pull/11436
~- [ ] Unskip tests (if any)~ This will be tracked in another ticket https://github.com/owncloud/client/issues/11449
- [x] Docs on running squish tests in Windows https://github.com/owncloud/docs-client-desktop/pull/554

Tests skipped for Windows:
- `Sharing link with expiration date` (difference in date format)
- `Syncing a folder having space at the end` (white space is trimmed)
- `Filenames that are rejected by the server are reported` (invalid file name for windows)
- `Sync long nested folder` (windows doesn't allow long path name)
- `Invalid system names are synced in linux` (linux only)

Feature disabled for Windows:
- Screenshots
- Stacktracing

**Comment by Talank** [comment]
It is blocked, until we can figure out a method to install python 3.8 and `pgGObject` library in python 3.8 in windows

**Comment by saw-jan** [comment]
Now we can run Squish tests in Windows.
Docs: https://doc.owncloud.com/desktop/next/appendices/guitest.html
