### ISSUE TITLE
[QA]  AUT got crashed while choosing folders to be synced

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9835]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

AUT got crashed and the test failed on the step `Then the folder "simple-folder" should exist on the file system`  while running the following scenario 

```
Scenario: Sync only one folder from the server
        Given user "Alice" has created folder "simple-folder" on the server
        And user "Alice" has created folder "large-folder" on the server
        And the user has started the client
        And the user has added the following account information:
            | server   | %local_server% |
            | user     | Alice          |
            | password | 1234           |
        When the user selects configure_synchronization_manually option in advanced section
        And the user "Alice" clicks on the next button in sync connection wizard
        And the user selects "ownCloud" as a remote destination folder
        When the user selects the following folders to sync:
            | folder        |
            | simple-folder |
        Then the folder "simple-folder" should exist on the file system
        But the folder "large-folder" should not exist on the file system
```

### Expected behavior

AUT was not expected to crash and the step `Then the folder "simple-folder" should exist on the file system` was expected to pass.

### Log
[stacktrace.txt](https://github.com/owncloud/client/files/9019047/stacktrace.txt)

**Comment by TheOneRing** [comment]
You are hitting an assert `OC_ENSURE(status == ConnectionValidator::Connected || status == ConnectionValidator::ServerVersionMismatch)`
could you provide the log for that test.

**Comment by sushmita56** [comment]
[ownCloud-crash.log](https://github.com/owncloud/client/files/9025023/ownCloud-crash.log)

**Comment by sushmita56** [comment]
The same behavior is observed in CI too 
[PR](https://github.com/owncloud/client/pull/9816)
[GUI report](https://cache.owncloud.com/public/owncloud/client/12277/guiReportUpload/index.html)

**Comment by TheOneRing** [comment]
```
if (!selectiveSyncBlackList.isEmpty() && OC_ENSURE(folder && useVfs)) {
