### ISSUE TITLE
[QA] Scenario `sharee edits content of files shared by sharer` failed in CI

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/client#9850]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

In CI  `Scenario: sharee edits content of files shared by sharer` failed

`Build: https://drone.owncloud.com/owncloud/client/12289`

failed in ` And the user overwrites the file "simple-folder/textfile.txt" with content "overwrite file inside a folder"` step 
with error message
```
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/client-bdd/Brian/simple-folder/textfile.txt'
```

### Steps to reproduce the issue

```
    Scenario: sharee edits content of files shared by sharer
        Given user "Alice" has created folder "simple-folder" on the server
        And user "Alice" has uploaded file with content "file inside a folder" to "simple-folder/textfile.txt" on the server
        And user "Alice" has uploaded file with content "file in the root" to "textfile.txt" on the server
        And user "Brian" has been created on the server with default attributes and without skeleton files
        And user "Alice" has shared folder "simple-folder" on the server with user "Brian" with "all" permissions
        And user "Alice" has shared file "textfile.txt" on the server with user "Brian" with "all" permissions
        And user "Brian" has set up a client with default settings
        When the user overwrites the file "textfile.txt" with content "overwrite file in the root"
        And the user overwrites the file "simple-folder/textfile.txt" with content "overwrite file inside a folder"
        And the user waits for the files to sync
        Then as "Brian" the file "simple-folder/textfile.txt" on the server should have the content "overwrite file inside a folder"
        And as "Brian" the file "textfile.txt" on the server should have the content "overwrite file in the root"
        And as "Alice" the file "simple-folder/textfile.txt" on the server should have the content "overwrite file inside a folder"
        And as "Alice" the file "textfile.txt" on the server should have the content "overwrite file in the root"
```

### Logs

Server Logs: https://cache.owncloud.com/public/owncloud/client/12298/guiReportUpload/serverlog.log

GUI Logs: https://cache.owncloud.com/public/owncloud/client/12298/guiReportUpload/index.html

### Screenshot
![Screenshot from 2022-07-04 12-17-32](https://user-images.githubusercontent.com/54478846/177095298-650f900c-e7a8-4969-9c09-6774fc6dcb8b.png)

**Comment by amrita-shrestha** [comment]
![image](https://user-images.githubusercontent.com/54478846/179801632-8b8a14cd-a91b-4f18-bbe9-b559a9a8129c.png)
GUI Logs: https://cache.owncloud.com/public/owncloud/client/12531/guiReportUpload/index.html
Server Logs: https://cache.owncloud.com/public/owncloud/client/12531/guiReportUpload/serverlog.log
https://github.com/owncloud/client/pull/9929

**Comment by sushmita56** [comment]
The file syncing issue resulted in the failure of this scenario.

**Comment by amrita-shrestha** [comment]
Reoccured: 
Server Logs: https://cache.owncloud.com/public/owncloud/client/12608/guiReportUpload/serverlog.log
GUI Logs: https://cache.owncloud.com/public/owncloud/client/12608/guiReportUpload/index.html
![image](https://user-images.githubusercontent.com/54478846/180762119-d17c5fee-ab89-4453-b25b-75053e67ab6c.png)
![Screenshot from 2022-07-25 16-44-56](https://user-images.githubusercontent.com/54478846/180762181-da6124d4-bc5d-4e10-8cf8-2ceb2dfbe746.png)

**Comment by sushmita56** [comment]
Reappeared again in the nightly build
[serverlog_july27.log](https://github.com/owncloud/client/files/9194961/serverlog_july27.log)


![Screenshot from 2022-07-27 12-23-49](https://user-images.githubusercontent.com/66173400/181178798-89a724a8-b95b-4ab4-ae9c-93bdfe7aa90a.png)

**Comment by sushmita56** [comment]
Moving this issue to Todo as the PR opened for solving this issue is blocked for now because of other intermittent failures,

**Comment by saw-jan** [comment]
Seems like the issue with syncing
Similar issue is report here https://github.com/owncloud/client/issues/9939
So closing this
