### ISSUE TITLE
`RuntimeError: startApplication() failed` intermittent

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/client#9851]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

`Build: https://drone.owncloud.com/owncloud/client/12289`

In CI  `Scenario: try to reshare a file/folder shared without share permission failed

```squish
    **Failed in** 
    `  And user "Brian" has set up a client with default settings ` step 
       with error message
       ```
        RuntimeError: startApplication() failed
       ```
```
In CI  `Scenario: unshare a shared file and folder` failed

```squish
    **Failed in** 
    `  And user "Brian" has set up a client with default settings ` step 
       with error message
       ```
        RuntimeError: startApplication() failed
       ```
```

### Steps to reproduce the issue

```
    Scenario: try to reshare a file/folder shared without share permission
        Given user "Brian" has been created on the server with default attributes and without skeleton files
        And user "Carol" has been created on the server with default attributes and without skeleton files
        And user "Alice" has created folder "FOLDER" on the server
        And user "Alice" has uploaded file with content "ownCloud test text file" to "textfile.txt" on the server
        And user "Alice" has shared file "FOLDER" on the server with user "Brian" with "read" permissions
        And user "Alice" has shared file "textfile.txt" on the server with user "Brian" with "read" permissions
        And user "Brian" has set up a client with default settings
        When the user opens the sharing dialog of "FOLDER" using the client-UI
        Then the error text "The file can not be shared because it was shared without sharing permission." should be displayed in the sharing dialog
        When the user opens the sharing dialog of "textfile.txt" using the client-UI
        Then the error text "The file can not be shared because it was shared without sharing permission." should be displayed in the sharing dialog

    Scenario: unshare a shared file and folder
        Given user "Brian" has been created on the server with default attributes and without skeleton files
        And user "Alice" has uploaded file with content "ownCloud test text file 0" to "textfile0.txt" on the server
        And user "Alice" has created folder "simple-folder" on the server
        And user "Alice" has shared file "textfile0.txt" on the server with user "Brian" with "all" permissions
        And user "Alice" has shared folder "simple-folder" on the server with user "Brian" with "all" permissions
        And user "Alice" has set up a client with default settings
        When the user unshares the resource "textfile0.txt" for collaborator "Brian Murphy" using the client-UI
        Then the text "The item is not shared with any users or groups" should be displayed in the sharing dialog
        And as "Brian" file "textfile0.txt" on the server should not exist
        When the user closes the sharing dialog
        And the user unshares the resource "simple-folder" for collaborator "Brian Murphy" using the client-UI
        Then the text "The item is not shared with any users or groups" should be displayed in the sharing dialog
        And as "Brian" folder "simple-folder" on the server should not exist

```

### Logs
Server Logs: https://cache.owncloud.com/public/owncloud/client/12298/guiReportUpload/serverlog.log

GUI Logs: https://cache.owncloud.com/public/owncloud/client/12298/guiReportUpload/index.html

### Screenshots

![Screenshot from 2022-07-04 12-29-36](https://user-images.githubusercontent.com/54478846/177096973-252d6784-a781-4b85-858a-c5041c4b0e8e.png)

![Screenshot from 2022-07-04 12-45-31](https://user-images.githubusercontent.com/54478846/177099338-9eaa4cf2-4812-4575-9282-c3dc727425d3.png)

**Comment by amrita-shrestha** [comment]
https://github.com/owncloud/client/issues/9902

**Comment by amrita-shrestha** [comment]
Locally reproduce in different scenario: Scenario Outline: Syncing a folder to the server
![Screenshot from 2022-07-20 15-11-27](https://user-images.githubusercontent.com/54478846/179948873-67e0e396-0309-4f69-8fa5-a8f02cfda102.png)
![Screenshot from 2022-07-20 15-11-45](https://user-images.githubusercontent.com/54478846/179948885-d35bbc42-4e46-4a48-983c-ee1d0023f238.png)

**Comment by saw-jan** [comment]
Haven't seen it in recent builds.
Please, re-open if this is the case.
Closing here!
