### ISSUE TITLE
[QA] Sometime fail to store screenshot 

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/client#9852]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

CI failed in **OnScenarioEnd-hook** with an error message:

```
g-file-error-quark: Failed to open “/drone/src/test/guiReportUpload/screenshots/reshare_a_file/folder.png” for writing: No such file or directory (4)
```

```
g-file-error-quark: Failed to open “/drone/src/test/guiReportUpload/screenshots/try_to_reshare_a_file/folder_shared_without_share_permission.png” for writing: No such file or directory (4)
```
### Logs
Server Logs: https://cache.owncloud.com/public/owncloud/client/12298/guiReportUpload/serverlog.log

GUI Logs: https://cache.owncloud.com/public/owncloud/client/12298/guiReportUpload/index.html

### Screenshots

![Screenshot from 2022-07-04 12-29-36](https://user-images.githubusercontent.com/54478846/177101818-569d145b-e681-4ec8-92dc-dd16424a5f55.png)

![Screenshot from 2022-07-04 13-01-57](https://user-images.githubusercontent.com/54478846/177102639-7165e96b-a992-48c4-b536-e0d8dd9fdf58.png)

**Comment by saw-jan** [comment]
@amrita-shrestha 
Looks like after one test failure in a testsuite, screenshots of all the next tests will also be included (either pass or fail).

The `test.resultCount()` gives all the errors (of a testSuite), not the information of current test scenario. So, the solution should be around the below line of code:
https://github.com/owncloud/client/blob/8776d4c78f5e01aecaf88b826c1c06d2a00ef8bf/test/gui/shared/scripts/bdd_hooks.py#L118

**Comment by amrita-shrestha** [comment]
> @amrita-shrestha Looks like after one test failure in a testsuite, screenshots of all the next tests will also be included (either pass or fail).
> 
> The `test.resultCount()` gives all the errors (of a testSuite), not the information of current test scenario. So, the solution should be around the following line of code:
> 
> https://github.com/owncloud/client/blob/8776d4c78f5e01aecaf88b826c1c06d2a00ef8bf/test/gui/shared/scripts/bdd_hooks.py#L118

@saw-jan  actually
https://github.com/owncloud/client/blob/8776d4c78f5e01aecaf88b826c1c06d2a00ef8bf/test/gui/shared/scripts/bdd_hooks.py#L118
catches error in places of failure. 
 
```
When tests fails
    print(test.resultCount("fails"))
return 1
    print(test.resultCount("errors"))
return 0
```
