### ISSUE TITLE
[QA] `Scenario: logging out` failed in CI 

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9856]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

The scenario `logging out` failed in CI on step `When the user "Alice" logs out of the client-UI` with the following error
```
LookupError: Object '{type='QMenu' unnamed='1' visible='1' window={name='Settings' type='OCC::SettingsDialog' visible='1'}}' not found. Could not match properties:
    visible for object name: '{type='QMenu' unnamed='1' visible='1' window=:settings_OCC_SettingsDialog}'
```

### Steps to reproduce the issue

na

### Screenshots

![Screenshot from 2022-07-05 09-56-33](https://user-images.githubusercontent.com/66173400/177247934-ceff85d7-b6ad-49ff-8fad-6e9d7e1d5cb2.png)

### Log
This issue is referenced from https://github.com/owncloud/client/pull/9816#issuecomment-1164171671
>Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12284/6/1
>
>:boom: The GUI tests failed.
>
>GUI Logs: https://cache.owncloud.com/public/owncloud/client/12284/guiReportUpload/index.html
>
><details>
>
>Server Logs: https://cache.owncloud.com/public/owncloud/client/12284/guiReportUpload/serverlog.log
>
>Screenshots:
>- [logging_out.png](https://cache.owncloud.com/public/owncloud/client/12284/guiReportUpload/screenshots/logging_out.png)
>- [login_after_loggin_out.png](https://cache.owncloud.com/public/owncloud/client/12284/guiReportUpload/screenshots/login_after_loggin_out.png)
>
></details>
>
>
>

**Comment by amrita-shrestha** [comment]
Failed at build: https://drone.owncloud.com/owncloud/client/12334

GUI Logs: https://cache.owncloud.com/public/owncloud/client/12334/guiReportUpload/index.html

Server Logs: https://cache.owncloud.com/public/owncloud/client/12334/guiReportUpload/serverlog.log

**Comment by sushmita56** [comment]
Again it failed on build: https://drone.owncloud.com/owncloud/client/12405
GUI log: https://cache.owncloud.com/public/owncloud/client/12405/guiReportUpload/index.html
![Screenshot from 2022-07-08 10-00-15](https://user-images.githubusercontent.com/66173400/177915783-b82132cd-daaf-447c-9aa1-4b82a3b0deb0.png)

**Comment by sushmita56** [comment]
Not reproducible for now in CI

**Comment by saw-jan** [comment]
Closing in favor of https://github.com/owncloud/client/issues/9953
