### ISSUE TITLE
[QA] Failed at `the user creates a new public link with following settings using the client-UI:` step on CI

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/client#9858]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

While creating a new public link with `expireDate` using client-UI, step failed with following error:
 ```
 LOG     Expected date: 10/14/31 is not same as that of Actual date: 7/6/22, trying workaround
 FAIL     workaround failed, actual date: 7/6/22 is still not same as expected date: 10/14/31
```
Need further investigation. This step may be an intermittent failure. 

### Steps to reproduce the issue

```
    Scenario: simple sharing of file and folder by public link with expiration date
        Given user "Alice" has set up a client with default settings
        And user "Alice" has created folder "FOLDER" on the server
        And user "Alice" has uploaded file with content "ownCloud test text file" to "/textfile.txt" on the server
        When the user creates a new public link with following settings using the client-UI:
            | path       | textfile.txt |
            | expireDate | 2031-10-14   |
        Then as user "Alice" the file "textfile.txt" should have a public link on the server
        And the last public link share response of user "Alice" should include the following fields on the server
            | expireDate | 2031-10-14 |
        When the user closes the sharing dialog
        And the user creates a new public link with following settings using the client-UI:
            | path       | FOLDER     |
            | expireDate | 2031-12-30 |
        Then as user "Alice" the file "FOLDER" should have a public link on the server
        And the last public link share response of user "Alice" should include the following fields on the server
            | expireDate | 2031-12-30 |

    Scenario: simple sharing of a file by public link with password and expiration date
        Given user "Alice" has set up a client with default settings
        And user "Alice" has uploaded file with content "ownCloud test text file" to "/textfile.txt" on the server
        When the user creates a new public link with following settings using the client-UI:
            | path       | textfile.txt |
            | password   | pass123      |
            | expireDate | 2031-10-14   |
        Then as user "Alice" the file "textfile.txt" should have a public link on the server
        And the last public link share response of user "Alice" should include the following fields on the server
            | expireDate | 2031-10-14 |
        And the public should be able to download the file "textfile.txt" with password "pass123" from the last created public link by "Alice" on the server
```
### Logs
GUI Logs: https://cache.owncloud.com/public/owncloud/client/12334/guiReportUpload/index.html
Server Logs: https://cache.owncloud.com/public/owncloud/client/12334/guiReportUpload/serverlog.log

### Screenshots

![Screenshot from 2022-07-05 15-59-26](https://user-images.githubusercontent.com/54478846/177305876-b0d0b590-7523-4f6c-b803-e42abc79bceb.png)
![Screenshot from 2022-07-05 16-00-13](https://user-images.githubusercontent.com/54478846/177305982-13e06ccd-233e-477d-b92a-534dcf9635e7.png)

**Comment by amrita-shrestha** [comment]
Related previous issue: [Can not set expiration date for new public link ](https://github.com/owncloud/client/issues/9321)

**Comment by sushmita56** [comment]
The exact same failure is found in this [PR](https://github.com/owncloud/client/pull/9885) too.
[GUI log](https://cache.owncloud.com/public/owncloud/client/12405/guiReportUpload/index.html)

The following two scenarios failed on the same step `When the user creates a new public link with following settings using the client-UI` and with the same error
```
LOG     Expected date: 10/14/31 is not same as that of Actual date: 7/6/22, trying workaround
FAIL     workaround failed, actual date: 7/6/22 is still not same as expected date: 10/14/31
```
```
Scenario: simple sharing of file and folder by public link with expiration date
Scenario: simple sharing of a file by public link with password and expiration date
```

**Comment by sushmita56** [comment]
Haven't got much time to work on this issue, sorry for removing the assignment so late. But this may be related to https://github.com/owncloud/client/issues/9953 as the error messages are the same.

**Comment by amrita-shrestha** [comment]
Investigation findings:
```
squish.nativeType(expYear)
squish.nativeType(expDate.day)
squish.nativeType(expDate.month) is not working properly sometimes.
```
One solution was suggested before in this issue: https://github.com/owncloud/client/issues/9321#issuecomment-1087092550
