### ISSUE TITLE
[QA] ownCloud-3.0.0-daily20220705.7935.x64.msi crashes when adding an account

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9859]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Seen with client 3.0.0.7935-daily20220705 on Windows 10 21H2.
When adding an account, the client creates a strange path for the local directory and finally crashes when clicking 'Finish'.

### Expected behavior

Correct path, no crash

### Steps to reproduce the issue

1. Start client and 'Add account'
2. Connect to ocis.ocis-traefik.released.owncloud.works
3. 'Open browser' / fill in credentials
4. Check path for local download directory on 'Advanced configuration'
5. Click 'Finish'

### Screenshots

![strange-local-path](https://user-images.githubusercontent.com/75983861/177321780-fe9170d1-a656-494d-be95-24c68637d3ee.png)

### Logs

Crash-ID: 
7226857c-5143-4efd-ac46-84c87bcf1719
(561d7aa6-063c-42c8-bca8-fcda0b0eaa2f)

Logfile:
[client.log.gz](https://github.com/owncloud/client/files/9046141/client.log.gz)
 

### Client version number

ownCloud-3.0.0-daily20220705.7935.x64.msi

### Server information

ocis.ocis-traefik.released.owncloud.works Beta4

**Comment by TheOneRing** [comment]
`07-05 13:35:18:724 [ critical default ]:	ENSURE: "QDir().mkpath(folder)" in file C:\_\368a7f97\ownCloud-3.0.0-daily20220705.7935-vfs\src\gui\folderman.cpp, line 1466 bool __cdecl OCC::FolderMan::prepareFolder(const class QString &)

**Comment by TheOneRing** [comment]
I guess its related to the file name
