### ISSUE TITLE
[QA] 3.0.0 AppImage daily20220705 crashes when keeping files

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9864]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When connected to demo.owncloud.org, the files on server are deleted hourly. When clicking on "Keep files" after waiting for some hours the client crashes.

After restarting the client the popup appears again and "Keep files" works correctly then.

### Expected behavior

Do not crash but keep files.

### Steps to reproduce the issue

1. Start the client AppImage
2. connect to demo.owncloud.org (VFS Off)
3. wait for some hours (while demo.owncloud.org is started multiple times)
4. click on "Keep files" on "Keep All Files" popup

### Screenshots

![keep-remove-all-files](https://user-images.githubusercontent.com/75983861/177482920-2166761f-027e-4ea6-bd2e-7c2b62014ebd.png)

### Logs

Crash-ID: ab6c0cda-b06b-4f2a-b907-a3444a2b77bc

Logfile crash:
[keep-files.log.gz](https://github.com/owncloud/client/files/9052053/keep-files.log.gz)

Logfile success:
[keep-succeeds.log.gz](https://github.com/owncloud/client/files/9052140/keep-succeeds.log.gz)

### Client version number

ownCloud-3.0.0-daily20220705.7935.AppImage

### Desktop environment (Linux only)

Ubuntu 22.04

### Server information

demo.owncloud.org

### Additional context

We had that kind of crash before but for "Remove all files", see https://github.com/owncloud/client/issues/9558

**Comment by jnweiger** [comment]
Confirmed fixed in testpilotcloud 2.11.0daily20220816 (build 8332)
