### ISSUE TITLE
[QA] 3.0.0 AppImage daily20220705 cannot check for updates

### ISSUE THREAD

**Issue by gabi18** [owncloud/client#9870]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

The 3.0.0 daily20220705 AppImage reports on 'Settings' page that the update status is unknown.

Logfile shows:
```
07-06 08:46:02:662 [ info gui.updater ]:        Checking for available update
07-06 08:46:02:726 [ warning gui.updater ]:     error occurred while parsing element at 1,1
Platform could not be detected.
^
->Platform could not be detected.<-
```

### Expected behavior

Check for updates

### Steps to reproduce the issue

1. Start the AppImage
2. Check 'Updates' on 'Settings'

### Screenshots

![AppImage-Update](https://user-images.githubusercontent.com/75983861/177521793-28e24f53-3dd3-452a-90be-9297f1ce5eac.png)

### Logs

[AppImage.log.gz](https://github.com/owncloud/client/files/9053603/AppImage.log.gz)

### Client version number

ownCloud-3.0.0-daily20220705.7935.AppImage

### Desktop environment (Linux only)

Ubuntu 22.04

**Comment by fmoc** [comment]
That's not a code bug, it's the update server returning this reply. The update URL the client queries looks valid. I guess the server config must be updated for 3.0.0. It is working as intended, though.

**Comment by gabi18** [comment]
@TheOneRing Should we have an open issue as a reminder to update the update server config for 3.0.0?

**Comment by TheOneRing** [comment]
@gabi18 could you add it as a checkbox to the 3.0 release ticket, if we don't have a "check update server for xxx" already
