### ISSUE TITLE
[QA] `Scenario Outline: File with long name (>228 characters) is blacklisted` failed in nightly build

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9880]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

The scenario `File with long name (>228 characters) is blacklisted` failed on nightly build[JUly 7] on step 
`Then the file "<filename>" should be blacklisted`  with error 
`Comparison: 'True' and 'False' are not equal` but the scenario is passing locally.

### Log:
[GUI log](https://cache.owncloud.com/public/owncloud/client/12394/guiReportUpload/index.html)

### Screenshots
![Screenshot from 2022-07-07 12-06-05](https://user-images.githubusercontent.com/66173400/177705670-d8c4df23-ad30-4324-922e-01ee1f3f5fa3.png)

**Comment by sushmita56** [comment]
I just found exactly the same condition on issue https://github.com/owncloud/client/issues/9782

**Comment by amrita-shrestha** [comment]
This issue was reported before: https://github.com/owncloud/client/issues/9471 
According to this comment: https://github.com/owncloud/client/issues/9471#issuecomment-1054303519
The file name should be >233 to be blacklisted and 220 characters should always sync.

**Comment by amrita-shrestha** [comment]
> I just found exactly the same condition on the issue #9782 Fixing one of the issues may close both issues.

The reason behind the failure of this scenario is due to **the file name with (>228 character is flaky ) sometimes syncs** 
I don't thing problem is same with this issue: https://github.com/owncloud/client/issues/9782

**Comment by amrita-shrestha** [comment]
**Finding during this issue:**
File name length with 239 is flaky (2/48) syncs.
233 file name length run 50 times blacklisted.
220< and >233 is somehow flaky (sometimes sync)
