### ISSUE TITLE
Settings flag to flag a sync folder connection as deployed/frozen

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9881]
A deployed connection will neither provide the `Remove folder sync connection` action nor the `Disable/enable virtual files action`

**Comment by jnweiger** [comment]
@TheOneRing I cannto see from the description here, if this is a user facing feature. Is it relevant for docs?

**Comment by TheOneRing** [comment]
Not user facing and only a very advanced flag for now. Meant for specific setups.
