### ISSUE TITLE
Default behaviour for clients connected to ocis that upgrade from 2.x to 3.0

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9884]
Imagine the following scenario:
- A 2.x client is connected to an ocis server using the legacy web dav endpoint
- The client is upgraded to 3.0 it continues to use the legacy dav endpoint.

Should we display the `Add Spaces` button and allow to the subscription of spaces or should spaces be disabled?

**Comment by michaelstingl** [comment]
> Should we display the `Add Spaces` button and allow to the subscription of spaces or should spaces be disabled?

Previously we discussed, not to mix old world and new world in the same account. I'd vote to keep it this way.
