### ISSUE TITLE
[QA] Scenario `Modify original content of a file with special character` failed at execution through middleware in CI

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/client#9890]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

fail while checking the content of the file (executed through middleware)

PR:https://github.com/owncloud/client/pull/9886
GUI Logs: https://cache.owncloud.com/public/owncloud/client/12423/guiReportUpload/index.html
Server Logs: https://cache.owncloud.com/public/owncloud/client/12423/guiReportUpload/serverlog.log

 

### Steps to reproduce the issue

    Scenario: Modify orignal content of a file with special character
        Given user "Alice" has uploaded file with content "ownCloud test text file 0" to "S@mpleFile!With,$pecial?Characters.txt" on the server
        And user "Alice" has set up a client with default settings
        When the user overwrites the file "S@mpleFile!With,$pecial?Characters.txt" with content "overwrite ownCloud test text file"
        And the user waits for file "S@mpleFile!With,$pecial?Characters.txt" to be synced
        Then as "Alice" the file "S@mpleFile!With,$pecial?Characters.txt" on the server should have the content "overwrite ownCloud test text file"

### Screenshots

![Screenshot from 2022-07-08 14-31-56](https://user-images.githubusercontent.com/54478846/177955507-519fb9c8-2c45-4afa-aba7-07d8d08e1644.png)

**Comment by amrita-shrestha** [comment]
Re-occurred : 
In build: https://drone.owncloud.com/owncloud/client/12441
GUI LOG: https://cache.owncloud.com/public/owncloud/client/12440/guiReportUpload/index.html

**Comment by sushmita56** [comment]
Failed on July 10 [nightly build](https://drone.owncloud.com/owncloud/client/12441) too
[GUI log](https://cache.owncloud.com/public/owncloud/client/12441/guiReportUpload/index.html)

**Comment by amrita-shrestha** [comment]
https://github.com/owncloud/client/issues/9794

**Comment by amrita-shrestha** [comment]
After overwriting the file. File does not sync.

**Comment by amrita-shrestha** [comment]
currently, GUI test in client skipped so shifting to block

**Comment by saw-jan** [comment]
There is separate issue to fix sync problems (see https://github.com/owncloud/client/issues/9939)
Closing this in favor of that one.
