### ISSUE TITLE
[QA] incomplete UI Elements

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9900]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen while testing client 2.10.2-rc.1 on win11

The main windows has several graphical elements that look incomplete, defunct, or unfinished:

* In logged out state (restart after oauth expired), there is a square with a little triangle indicator.
* This element does nothing, except change color to a slightly darker blue, when clicked.
   (when logged in, a lock icon appears there, and it has a drop down with certificate information)
![image](https://user-images.githubusercontent.com/1108546/178358008-33764f9b-e8e7-423d-a557-fe56a2e98176.png)

----

* The accounts dropdown menu has logout and remove. 
* These elements have space for an icon and a strange vertical line in front of the text
* The decender of the g of logout descends beyond the blue highlight.
![image](https://user-images.githubusercontent.com/1108546/178358160-92e270e7-709b-4257-84f0-f5f62e65eb9a.png)

----

Expected behaviour

* The certificate dropdown is not shown, when not connected. 
* Decenders within the highlight, and consistent backround and icons.
* Keep the entries in the account menu in sync with the current state. When not connected, the next action is 'log in', not 'log out'.

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

.

### Actual behavior

.

**Comment by TheOneRing** [comment]
We don't know the certificate state when not connected, so nothing to display.
We could display a third icon but the element is removed in 3.0 anyhow.
For the context menu, that's how they look on Windows.
What you see are the placeholders required for a neat alignment if the menu contains elements with icons and without.
