### ISSUE TITLE
[QA] File in WinVFS shown as mixed state

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9901]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen while testing 2.10.2-rc.1 on win11

* sync a subtree with ca 400 files, toggle a few times between keep locally and free up space.
   - especially toggle some folders and/or files, while the client is still busy executing the previous toggle.
* at some point in time a file ends up with the white-green checkmark, that is normally seen with folder, that contain both hydrated and dehydrated files.
![image](https://user-images.githubusercontent.com/1108546/178361435-fd068486-993a-4608-a70e-9c5ab49b643d.png)

Expected behaviour
* A file can only be either hydrated (fat green checkmark status icon) or dehydrated (cloud status icon), it should neve show the green white checkmark.
* The right click menu of a file should not have both 'Always keep on this device' and 'Free up space' activated together.

Workaround
* Use the right click menu to bring it into either state. 

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

.

### Actual behavior

.

**Comment by TheOneRing** [comment]
The green white check mark indicates that the file is available locally but neither pinned nor unpinned.
This is the normal state a file that was downloaded through user interaction.

**Comment by jnweiger** [comment]
https://doc.owncloud.com/desktop/next/vfs.html#background
:+1:

**Comment by jnweiger** [comment]
@dpapac is this the issue, you also saw on win11?
