### ISSUE TITLE
[QA] activity window reports too many issues in 'not synced' tab

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9907]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen while testing 2.10.2-rc.1

* run `randfiles.py -m 100000 r100k` in the client's sync root folder
* the client start uploading. 
* remove the r100k tree from the client.
* the client continues uploading for a while, then starts logging file removals. this scrolls very fast.
![image](https://user-images.githubusercontent.com/1108546/178447797-9c8b3adb-9b39-41ff-addd-633dbe22ea0f.png)

----

Apparently there is a limit of 20000 entries in this window. 

Expected behaviour:
* normal file removal is not a problem that  requires user attention. Don't log that as 'issue'.

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

.

### Actual behavior

.

**Comment by TheOneRing** [comment]
Not a bug, welse we would not display the warning.
