### ISSUE TITLE
[QA] most `moved to` entries in sync protocol are moves to itself

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9911]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen while testing 2.10.2rc1 with server 10.11.0-alpha.1

* Inside the Photos folder create a subfolder rand20k which contains many files. Wait until sync finishes.
* on the desktop  use the file broser to move rand20k out of the Photos folder (into the sync root folder).
* This action is logged in the Sync Protocol as `Photos/rand20k moved to rand20k`
* It is followed by a long list of meaningless move actions, where all the files in the rand20k folder seem to be moved to identical paths.
![image](https://user-images.githubusercontent.com/1108546/178503399-feed0b49-26b0-4ac8-a80d-79fb2430627c.png)

Expected behaviour
* no identity moves are shown.

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

.

### Actual behavior

.

**Comment by TheOneRing** [comment]
The message is correct: `Photos/rand20k moved to /rand20k`
