### ISSUE TITLE
AUT failed to start while running the test scenarios

### ISSUE THREAD

**Issue by sushmita56** [owncloud/client#9916]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

AUT failed to start and throws the error `RuntimeError: startApplication() failed` while running the test either by using the terminal or by using squish ide. Before throwing `RuntimeError` error, there is another message `Could not connect to unix socket /run/user/1000/ownCloud/socket. [Errno 111] Connection refused` 

### Screenshots

![Screenshot from 2022-07-13 14-38-39](https://user-images.githubusercontent.com/66173400/178693143-14573756-e5a2-40f8-94df-8fb0bfc20ad2.png)

![Screenshot from 2022-07-13 14-39-56](https://user-images.githubusercontent.com/66173400/178693354-05978650-e99c-4802-babd-f37efa4edbf4.png)

**Comment by sushmita56** [comment]
Trying to launch the AUT with command `owncloud -s`
![Screenshot from 2022-07-13 15-01-59](https://user-images.githubusercontent.com/66173400/178698993-d5a47dc4-35b9-447c-aed8-fdad6a4d77be.png)

**Comment by sushmita56** [comment]
[_opt_ownCloud_ownCloud_bin_owncloud.1000.txt](https://github.com/owncloud/client/files/9101063/_opt_ownCloud_ownCloud_bin_owncloud.1000.txt)

**Comment by saw-jan** [comment]
Haven't seen it recently.
Closing here!
