### ISSUE TITLE
[QA] connect error message uses client name instead of server name

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9923]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen with 2.10.1-rc.1 (and earlier)

* start a temporary server
* connect client
* quit client
* shut down server
* restart client (on the next day)
* the account is logged out. OK
![image](https://user-images.githubusercontent.com/1108546/178981797-931146dc-d12a-43b5-b2e5-e1f36fd7cce8.png)

----

* account -> log in, the login fails as expected. OK

![image](https://user-images.githubusercontent.com/1108546/178981920-fa063fd6-08a7-4735-8204-1035c15e0a7f.png)

----
The error message says "No connection to Btr Test Client at https://oc10100-u20-04-20220519.jw-qa.owncloud.works"

Expected behaviour:

* the error message should say: No connection to ownCloud at https://oc10100-u20-04-20220519.jw-qa.owncloud.works

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

.

### Actual behavior

.

**Comment by TheOneRing** [comment]
With 3.0 we cache the capabilities and are able to display the server name even if we are offline.

**Comment by bishwasojha** [comment]
Steps performed
- start a temporary server
- connect client
- quit client
- shut down server
- restart client (on the same day)

After Client is restarts
 - Account isnot Signed out
 - the message say: No connection to  https://localhost:9200
 
## Screenshot
*In Linux*
![Screenshot from 2022-11-09 15-32-59](https://user-images.githubusercontent.com/33860671/200804877-ba36f4c3-6d82-492b-88a2-efcf4d7b363a.png)

*In Windows*
![Screenshot from 2022-11-09 16-10-13](https://user-images.githubusercontent.com/33860671/200805805-46b9bcb5-6c95-4f26-8fee-5a8d5f6d49b7.png)

ownCloud Version
```
ownCloud 3.0.0.9005-beta1 [6b12ec](https://github.com/owncloud/client/commit/6b12ecdb4236d3d485ed57ec0bc2feac72b8f340)
Libraries Qt 5.15.2, OpenSSL 3.0.2 15 Mar 2022
Using virtual files plugin: suffix
ubuntu-5.15.0-52-generic
```
