### ISSUE TITLE
`Local file changed during sync` can still trigger error timeouts

### ISSUE THREAD

**Issue by TheOneRing** [owncloud/client#9924]
```
git grep "Local file changed during sync" -- .\src\
src/libsync/propagateupload.cpp:        done(SyncFileItem::Message, tr("Local file changed during sync. It will be resumed."));
src/libsync/propagateuploadng.cpp:            abortWithError(SyncFileItem::SoftError, tr("Local file changed during sync."));
src/libsync/propagateuploadtus.cpp:            abortWithError(SyncFileItem::SoftError, tr("Local file changed during sync."));
src/libsync/propagateuploadv1.cpp:            abortWithError(SyncFileItem::SoftError, tr("Local file changed during sync."));

**Comment by erikjv** [comment]
This happens in `TestChunkingNG::testCreateConflictWhileSyncing`

**Comment by HanaGemela** [comment]
Steps to recreate:

1. Lock a file by opening Word
2. Modify the file and keep it open
3. Save the file -> triggers sync

Actual result: Three attempts -> blacklisted file
Expected result: Locked and not uploaded, in the not sync tab, uploaded after closing the file

**Comment by bishwasojha** [comment]
- when a file is open in Word/LibreOffice , file is Locked and not uploaded, file lies in the not sync tab
- After a file is closed, file is uploaded to server
