### ISSUE TITLE
`Error StartServiceByName for org.freedesktop.secrets` result in GUI testsuite failure in CI

### ISSUE THREAD

**Issue by amrita-shrestha** [owncloud/client#9952]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

This could be the reason for lookup error
```
13:55:03:574 AUT stdout: 07-22 13:55:02:763 [ warning sync.credentials.http.legacy ]:	Migrating old keychain entries failed "Error calling StartServiceByName for org.freedesktop.secrets: Failed to execute program org.freedesktop.secrets: Operation not permitted"
13:55:03:574 AUT stdout: 07-22 13:55:02:763 [ info gui.account.state ]:	Fetched credentials for "http://owncloud/" attempting to connect
13:55:03:574 AUT stdout: 07-22 13:55:02:763 [ warning gui.account.state ]:	checkConnectivity blocking: false
``` 

### Steps to reproduce the issue
```
  Scenario: remove an account connection
    Given user "Alice" has been created on the server with default attributes and without skeleton files
    And user "Brian" has been created on the server with default attributes and without skeleton files
    And user "Alice" has set up a client with default settings
    And the user has added another account with
      | server   | %local_server% |
      | user     | Brian          |
      | password | AaBb2Cc3Dd4    |
    When the user removes the connection for user "Brian" and host %local_server_hostname%
    Then an account should be displayed with the displayname Alice Hansen and host %local_server_hostname%
```

### Screenshots

![image](https://user-images.githubusercontent.com/54478846/180693956-d3f9aab4-03b8-4115-9505-cc9adec9f86f.png)

GUI Logs:
![Screenshot from 2022-07-25 09-06-23](https://user-images.githubusercontent.com/54478846/180693995-b06d74c8-9af6-4e83-8025-1801285dca9e.png)

Server Logs: https://cache.owncloud.com/public/owncloud/client/12592/guiReportUpload/serverlog.log

**Comment by sushmita56** [comment]
The other two scenarios failed with the same error message.
>Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12612/6/1
>
>:boom: The GUI tests failed.
>
>GUI Logs: https://cache.owncloud.com/public/owncloud/client/12612/guiReportUpload/index.html
>
><details>
>
>Server Logs: https://cache.owncloud.com/public/owncloud/client/12612/guiReportUpload/serverlog.log
>
>Screenshots:
>- [Syncing_a_folder_to_the_server.png](https://cache.owncloud.com/public/owncloud/client/12612/guiReportUpload/screenshots/Syncing_a_folder_to_the_server.png)
>
></details>
>
>
>



>Results for <strong>GUI-tests</strong> https://drone.owncloud.com/owncloud/client/12604/6/1
>
>:boom: The GUI tests failed.
>
>GUI Logs: https://cache.owncloud.com/public/owncloud/client/12604/guiReportUpload/index.html
>
><details>
>
>Server Logs: https://cache.owncloud.com/public/owncloud/client/12604/guiReportUpload/serverlog.log
>
>Screenshots:
>- [simple_sharing_of_a_file_by_public_link_with_default_expiration_date.png](https://cache.owncloud.com/public/owncloud/client/12604/guiReportUpload/screenshots/simple_sharing_of_a_file_by_public_link_with_default_expiration_date.png)
>
></details>
>
>
>

**Comment by TheOneRing** [comment]
We depend on the system password store to be available.

>13:55:03:574 AUT stdout: 07-22 13:55:02:763 [ warning sync.credentials.http.legacy ]:	Migrating old keychain entries failed >"Error calling StartServiceByName for org.freedesktop.secrets: Failed to execute program org.freedesktop.secrets: Operation not >permitted"
>13:55:03:574 AUT stdout: 07-22 13:55:02:763 [ info gui.account.state ]:	Fetched credentials for "http://owncloud/" attempting >to connect
>13:55:03:574 AUT stdout: 07-22 13:55:02:763 [ warning gui.account.state ]:	checkConnectivity blocking: false

You appear to use a legacy ownCloud.cfg format which is then migrated to the new credentials format and this seems to fail with the password store.

**Comment by TheOneRing** [comment]
`Failed to execute program org.freedesktop.secrets: Operation not`
Any chance we can ensure the credentials store service is running?

**Comment by saw-jan** [comment]
> You appear to use a legacy ownCloud.cfg format which is then migrated to the new credentials format and this seems to fail with the password store.
@TheOneRing Can we make use of that new credentials format instead of `ownCloud.cfg` so that there won't be any migration process?

**Comment by TheOneRing** [comment]
Yes but we still would require the credentials store to be started.

**Comment by saw-jan** [comment]
> Yes but we still would require the credentials store to be started.

No idea what the Credentials Store server is. Is there any way we can check the server status (running command or something)?

**Comment by TheOneRing** [comment]
@fmoc what is used on xfce?

**Comment by fmoc** [comment]
It is `gnome-keyring-daemon`.

**Comment by amrita-shrestha** [comment]
I think this issue is behind failure at the `wait-until-sync steps too`
i.e
**And the user has waited for folder "Folder1" to be synced** 
<details>
<summary>GUI Log Screenshot</summary>

![Screenshot from 2022-08-01 13-09-06](https://user-images.githubusercontent.com/54478846/182096119-7cac5cfa-0679-4154-959f-08deac4ae4c2.png)
</details>

Server Logs: https://cache.owncloud.com/public/owncloud/client/12713/guiReportUpload/serverlog.log
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/54478846/182095776-a074c97f-9259-4b9b-bc54-7458c1c27e47.png)
</details>

**Comment by TheOneRing** [comment]
Really hard to say what's going on here but it appears that `gnome-keyring-daemon` dies during the tests?

**Comment by TheOneRing** [comment]
Hmmm https://unix.stackexchange.com/questions/473528/how-do-you-enable-the-secret-tool-command-backed-by-gnome-keyring-libsecret-an

On the other hand that does not explain why it sometimes works and sometimes not.
@fmoc

**Comment by saw-jan** [comment]
The possible fix PR has been merged but could not test this behavior due to the new issue.
Blocked until https://github.com/owncloud-ci/squish/issues/34

**Comment by saw-jan** [comment]
Haven't seen these types of failures recently.
