### ISSUE TITLE
[QA] Sometimes some GUI tests fail with xfce login window

### ISSUE THREAD

**Issue by saw-jan** [owncloud/client#9953]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

While running GUI tests, some tests fails and the screenshots of those test failures has xfce login window.

### Steps to reproduce the issue

Run GUI tests in CI

### Screenshots

![logging_out](https://user-images.githubusercontent.com/52366632/180770641-62c1563e-9692-456f-b73c-d97d3faacabe.png)

Failed Scenarios:

- `logging out`
- `simple sharing of a file by public link with default expiration date`
- `simple sharing of a file by public link with password and expiration date.png`
- `simple sharing of file and folder by public link with expiration date.png`

NOTE: We need to figure out whether the above tests failed due to this login window or not.

### Similar issues
- https://github.com/owncloud/client/issues/9856

**Comment by saw-jan** [comment]
Failed Scenario: `logging out`

GUI report:
![ss](https://user-images.githubusercontent.com/52366632/180771949-3722314d-35ff-40b6-a2bb-ff1f0034656c.png)

Server log: [logging_out.log](https://github.com/owncloud/client/files/9180863/logging_out.log)

**Comment by amrita-shrestha** [comment]
Reoccured again:
Server log: [serverlog.log](https://github.com/owncloud/client/files/9186977/serverlog.log)
Scenario failed:
- logging out
- simple sharing of file and folder by public link with expiration date
-  simple sharing of file by public link with password and  expiration date

Screenshots
- logging out
![image](https://user-images.githubusercontent.com/54478846/180935366-ebbbc6a0-0deb-4c08-89f9-c6a67fcb9f13.png)

- simple sharing of file and folder by public link with expiration date
![image](https://user-images.githubusercontent.com/54478846/180935513-a5c4c589-a0ed-4cbd-8d89-0d36ab3f9ab5.png)

-  simple sharing of file by public link with password and  expiration date
![image](https://user-images.githubusercontent.com/54478846/180935482-e4e722a2-a477-4937-a063-65c049911fc0.png)

**Comment by saw-jan** [comment]
@amrita-shrestha @sushmita56 any tests that fail with this issue, please, report here. And close existing issues related to this.

**Comment by TheOneRing** [comment]
That appears to be the system login screan?

**Comment by saw-jan** [comment]
I suspect, this is also related with https://github.com/owncloud/client/issues/9952
Authentication-popup is mainly caused by gnome-keyring

**Comment by amrita-shrestha** [comment]
Scenario: try to self share  a file/folder 
Server log:
[serverlog.log](https://github.com/owncloud/client/files/9195024/serverlog.log)

Screenshot:
![image](https://user-images.githubusercontent.com/54478846/181162006-5a4c0475-717c-4e69-9ee0-de10f0467cf4.png)

**Comment by TheOneRing** [comment]
It appears that no user is logged in, if no user is logged in the keychain(password storage backend) can be unavailable.
As only some tests fail, I have to think on auto log out after x min of inactivity.

Maybe use https://manpages.ubuntu.com/manpages/bionic/man1/caffeinate.1.html ?

**Comment by saw-jan** [comment]
> It appears that no user is logged in, if no user is logged in the keychain(password storage backend) can be unavailable. As only some tests fail, I have to think on auto log out after x min of inactivity.
> 
> Maybe use https://manpages.ubuntu.com/manpages/bionic/man1/caffeinate.1.html ?

So, I guess, this should be implemented in squish docker images while running squishrunner command.

**Comment by saw-jan** [comment]
> So, I guess, this should be implemented in squish docker image while running squishrunner command.

Instead of using `caffeinate`, we came into the conclusion that disabling auto-lock would be the best approach for CI.

**Comment by saw-jan** [comment]
The possible fix PR has been merged but could not test this behavior due to the new issue.
Blocked until https://github.com/owncloud-ci/squish/issues/34

**Comment by saw-jan** [comment]
Must be fixed by this PR https://github.com/owncloud/client/pull/10046
