### ISSUE TITLE
[QA] selective sync: cannot enable or disable subfolders

### ISSUE THREAD

**Issue by jnweiger** [owncloud/client#9967]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

Seen with client 2.10daily 20220728 while testing #9791

* Add a subfolder to Photos folder at the server.
* connect client
   - without VFS
   - use root folder as sync root
   - use choose what to sync: enable everything except for the subfolder of Photos
* wait for sync
* click open the folder view in the client window
  - we see that Photos has the [-] icon, as it is incompletely synced. 3rd screenshot. OK
  - click the little triangle to open the tree view under Photos. Nothing happens. BAD
  - Syncing of the subfolder can not be enabled. BAD

![image](https://user-images.githubusercontent.com/1108546/181473633-f238c6b2-7520-42c0-94bd-8b8613ffb133.png)
![image](https://user-images.githubusercontent.com/1108546/181473667-7c009b44-b944-4b9f-9ded-b3c8c49618c1.png)
![image](https://user-images.githubusercontent.com/1108546/181473681-4836e4c8-4278-40a0-965b-daf637ba55d8.png)

### Steps to reproduce the issue

.

### Screenshots

.

### Expected behavior

Tree view opens under each top level folder, if subfolders exist.

### Actual behavior

.

**Comment by hmeine** [comment]
Can confirm this bug on MacOS, Windows and Linux with OC 2.11.0.

**Comment by zitrusblau** [comment]
Same here on Mac OS (10.15) and OC 2.10 - 2.11. Tried also to completely delete and reinit connection to our owncloud server instance but with no success. The subfolder sync setting can't be adjusted due to them not being shown on arrow icon click...

**Comment by michaelstingl** [comment]
Please test with the 2.11.1 RC:
https://download.owncloud.com/desktop/ownCloud/testing/2.11.1-rc1.8388/

**Comment by worldnetworksr** [comment]
I got an error  https://download.owncloud.com/desktop/ownCloud/testing/2.11.1-rc1.8388/ 

![image](https://user-images.githubusercontent.com/110347234/186935747-6e88b502-9c27-4de2-bb37-c308b9beb0f0.png)

a8de2860-a01e-4d34-a578-fce3d06d9ad6

**Comment by PitWenkin** [comment]
Got a crash too. `2f89ce5c-c648-4001-99bb-1531c1040db7`

Seems to only crash when opening certain folders … I think it releated to the size/number op subfolders

**Comment by mrodriguezmad** [comment]
I tried ownCloud-2.11.1-rc1.8408 on Mac and Debian. In some subfolders it works fine, but in others it crash after clicking on the little triangle.

**Comment by michaelstingl** [comment]
You'll find the new, crash-free RC2 here:
https://github.com/owncloud/client/releases/tag/v2.11.1-rc2

**Comment by PitWenkin** [comment]
> You'll find the new, crash-free RC2 here:
> https://github.com/owncloud/client/releases/tag/v2.11.1-rc2

Seems to work on macOS Mojave (10.14.6)
All main folders and some random subfolder could be opened/closed/reopened regardless of the number of subfolders or filesizes.
Selecting/deselecting folders triggered the correct actions (downloading/removing local content)

**Comment by heikkiheer** [comment]
Same here. I can toggle the folder. But it does not expand. So I can not add subfolders to the sync.

**Comment by jnweiger** [comment]
> Same here. I can toggle the folder. But it does not expand. So I can not add subfolders to the sync.

Is this with 2.11.1rc1 or with 2.11.1rc2 ?

**Comment by worldnetworksr** [comment]
On Windows 10 this https://github.com/owncloud/client/releases/tag/v2.11.1-rc2 works fine.

![image](https://user-images.githubusercontent.com/110347234/187737861-50517348-f629-4679-9ff9-50dff459c89c.png)

**Comment by floridop** [comment]
Hi

I confirm the issue is solved in Ubuntu 18.04 Desktop Client version 2.11.1

I can reproduce the issue on:
- Windows 10 Desktop Client v. 2.11.0 (build 8354)

Switching to VFS to temporarily solves the problem, but I do not like the concept, I'd prefer to avoid. Also instructing the users on how to do that is not really safe, it risks creating havoc on the server. So we will wait for the update.

Installed 2.11.1 on Windows 10 today, and it works again. Thanks!
