### ISSUE TITLE
[QA] Cyclic Waiting Dependency while adding multiple sync connections

### ISSUE THREAD

**Issue by dpapac** [owncloud/client#9969]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the QA issue

# Issue seen while testing GH Issue: #9791:
    - Desktop-Client Version: 2.10.2daily20220629 (build 7886)
    -  Client-OS: Virtualbox Windows 10
    -  Server Version: ownCloud 10.10.0
   
By Removing Sync Connection the behavior of the client still remains as described in the issue #9791

### Steps to reproduce the issue

1. Limit Bandwidth to 20 KB/s (or click really fast or simply have a bad connection, Optional: Enable Logging)
2. Connect to the server via the client
3.  Choose to manually add Sync Folder Connections
4. First: add the a /root folder
5. Second: add a sub-folder of the root folder /root/sub-folder
6. Third: Add the /root folder again and while it is syncing select the 'Remove folder sync connection' of the 'newly' synced folder
    ->  The sync bar of the newly added /root folder is just starting to load
8.  Now the blue pending sync icon should appear at every added sync connection

-> Sync Connection is broken now
A Force Sync does not resolve the issue.
A restart of the client fixes the behavior.

### Screenshots

![allwaiting](https://user-images.githubusercontent.com/101094874/181582849-f6f89319-0786-406b-a269-cc1b8d22e478.png)

![cyclic_waiting](https://user-images.githubusercontent.com/101094874/181582813-573b5c8e-9848-48e3-93ec-627eb9853086.png)

### Expected behavior

.

### Actual behavior

.

**Comment by TheOneRing** [comment]
That reminds me on how I intended to clean up that queue code

**Comment by jnweiger** [comment]
Seen with testpilotcloud 2.11.0daily20220815 (build 8327) 

![image](https://user-images.githubusercontent.com/1108546/184824326-b3803e3f-49ad-4a77-b0ad-d51920d25e07.png)

----
Seems the second sync connection waits on the first. After removing the first, the second still does not recover:

![image](https://user-images.githubusercontent.com/1108546/184824497-ab2b15e7-9270-4e97-bc1c-b9f7928e6684.png)

----

Workaround:
* quit/restart the client.
* then the sync recovers and becomes active and finally finishses with nice green checkmark.

**Comment by jnweiger** [comment]
Confirmed fixed in 2.11.0-rc3

**Comment by saw-jan** [comment]
Tested with desktop-client `ownCloud 4.0.0.10398-daily20230313 f8e194`

:x: Dependency while adding multiple sync connections

Upon adding new sync connection, the previously synced connection will also start to sync and wait for the newly added sync connection to complete

https://user-images.githubusercontent.com/52366632/225279280-8853f9eb-1ad0-49cb-8964-c27122c3ef59.mp4

CC @HanaGemela @TheOneRing

**Comment by saw-jan** [comment]
Tested with `ownCloud 2.11.1 (build 8946) c6dbf3`

There is no dependency on syncing

https://user-images.githubusercontent.com/52366632/225298840-f26152ac-253d-4b76-95f6-0e5eee94015b.mp4

**Comment by saw-jan** [comment]
> There is no dependency on syncing

The difference in this behavior is expected.

With client `4.0.0`, all connections sync correctly.
