### ISSUE TITLE
Can not remove sync connection on error

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#9978]
My client has several sync connections for a server. Some of them are not longer valid because of reasons, in this case because the local sync dir does not longer exist. 

I do not need the sync any more and would like to remove the connection, which is not possible because the the-dot button is disabled.

![grafik](https://user-images.githubusercontent.com/1070214/181900986-71baa164-32cc-4f0d-a015-5fb9324e223c.png)

### Client version number

Version 2.9.2, but also newer clients I believe.

### Desktop environment (Linux only)

KDE

**Comment by TheOneRing** [comment]
Fixed in 2.10.0.
https://github.com/owncloud/client/pull/9099
