### ISSUE TITLE
ARM build

### ISSUE THREAD

**Issue by buhtz** [owncloud/client#9979]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Feature description

Support ARM platforms and publish releases for them.

### Proposed solution

ARM

### Additional context

# Relevant Issues
About Mac: #8329
About AppImage: #9118

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
It seems that others are able to build for ARM?

https://github.com/jancborchardt/nextcloud-scripts/blob/master/owncloud-client-arm.sh

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
The Debian project is do offer builds for `armhf `and `arm64`. But not for current stable (bullseye) but for the previous (buster) and next (bookworm) release.

But I [was able to install](https://debianforum.de/forum/viewtopic.php?p=1307510#p1307510) ownCloud 2.5 on a arm64 Debian 11 with [that official debian packages](http://ftp.debian.org/debian/pool/main/o/owncloud-client/).

**Comment by TheOneRing** [comment]
We might add arm appimages later this year.
For deb/rpm arm packages please contact your distribution.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
I know all this. I just added the information's for future readers who might also look out for ARM builds of ownCloud.

I just want to help your customers.
And you are so impolite and mark my comments as off-topic!
So for you it is off-topic that customers can create or download ARM builds of your software?!

**Comment by TheOneRing** [comment]
Recommending 3 year old builds or 3rd party software is not helpful.

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
> Recommending 4 year old builds or 3rd party software is not helpful.

It is Debian. It is stable and old releases are supported with bugfixes. If you find bugs in the 2.5 debian builds please feel free to open a bug report to the debian maintainer. As upstream (you) I assume you have good contact to all relevant distro maintainers.

But in real I don't think so because you are not willing to offer own arm builds while Debian does offer it for years.

It is also not help full to don't offer an ARM build at upstream.
