### ISSUE TITLE
No connection configured even though connection exists

### ISSUE THREAD

**Issue by dragotin** [owncloud/client#9980]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Running client built from master with my "normal" configuration, the client claims that one of the connections does not have a _connection configured_, but it shows a connection that was configured and worked with a client from a previous version:

![grafik](https://user-images.githubusercontent.com/1070214/182130043-fa6c9635-03fb-4fab-ad0d-298afef35c22.png)

I am happy to share my config file.

### Expected behavior

The connection works, since I am logged in.

### Client version number

owncloud client 3.0.0.0-git at commit 8f59224e6cc622de073cbeb18a3c35a4aa548809

### Desktop environment (Linux only)

Linux, KDE, openSUSE Tumbleweed

**Comment by Jeansen** [comment]
Had this problem suddenly with 2.10. in 2.11 it is still there. I can logout and back in, but the client will show me this "no connection configured".
