### ISSUE TITLE
[Wizard] Active step greyed out

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#9981]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Wizard guides you through the setup step by step, but the current active step is greyed out.

### Expected behavior

Index on the bottom of the wizard should be active.

### Steps to reproduce the issue

Start a client with fresh configuration, or add a new server connection.

### Screenshots

![CleanShot 2022-08-01 at 13 13 41](https://user-images.githubusercontent.com/214010/182136204-89375740-f343-4c59-aece-5439b0658d83.png)

### Logs

n.a.

### Client version number

testpilotcloud 3.0.0.8194-daily20220801 8f5922 Aug 1 2022 02:10:53
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-21.6.0

### Server information

n.a.

**Comment by fmoc** [comment]
A few thoughts: we could either implement a custom button widget (and replace `QRadioButton` with it), subclass `QRadioButton` to adjust its rendering, or use some other button implementation.

We could also just not mark the current option as "disabled", and ignore click events on it. The latter might be the easiest option, and should do for now.

**Comment by fmoc** [comment]
The button is disabled so one can not click on it. It makes no sense to click on the currently selected item in my opinion. What behavior would you expect if it was not disabled? Should the click just be ignored?

**Comment by TheOneRing** [comment]
I'd expect the current page button to be active and clicking it to have no effect.

**Comment by TheOneRing** [comment]
Its a visual hint not a navigational element in that case.

**Comment by TheOneRing** [comment]
I think breadcrumb navigation behaves similar
