### ISSUE TITLE
[macOS] sidebar icons missing in 3.0

### ISSUE THREAD

**Issue by michaelstingl** [owncloud/client#9984]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

Branded sidebar icon missing in latest 3.0 builds.

### Expected behavior

In case a sidebar icon is configured for macOS, ist should be used in the branded builds.

### Steps to reproduce the issue

- Install daily 3.0 build on macOS
- Add an account
- Open Finder to check sidebar

### Screenshots

![CleanShot 2022-08-01 at 15 31 49](https://user-images.githubusercontent.com/214010/182159263-e7762103-326d-4e7f-8386-89d2cfc5e60a.png)

![CleanShot 2022-08-01 at 15 32 29](https://user-images.githubusercontent.com/214010/182159335-9da7ae8b-1ca0-47c7-84e6-b706109ef273.png)

### Client version number

```
testpilotcloud 3.0.0.8198-daily20220801 8f5922 Aug 1 2022 14:03:08
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-21.6.0
```

**Comment by michaelstingl** [comment]
Strange, unbranded sidebar icons missing too:
<img width="752" alt="CleanShot 2022-08-01 at 15 48 17@2x" src="https://user-images.githubusercontent.com/214010/182162431-5a6b60cc-1187-427c-b5e4-06f698917dcd.png">

```
ownCloud 3.0.0.8202- ee5898 Aug 1 2022 14:54:08
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-21.6.0
```

**Comment by fmoc** [comment]
I suppose this is working as expected in 2.10? Please test if necessary. We might be able to track down the version that introduced the problem.

**Comment by TheOneRing** [comment]
Please report the logs for the socket api.

**Comment by TheOneRing** [comment]
Works for me
![image](https://user-images.githubusercontent.com/200626/182796446-f92bb5db-8688-46ce-a681-f7488c6ad489.png)

**Comment by michaelstingl** [comment]
> I suppose this is working as expected in 2.10? Please test if necessary. We might be able to track down the version that introduced the problem.

ownCloud 2.10.1 works ✅ 

```
ownCloud 2.10.1 (build 7187) [82eefd](https://github.com/owncloud/client/commit/82eefdafa2ec7a1927df87c850d9e6f1e9dac6af) Apr 5 2022 13:24:21
Libraries Qt 5.12.11, OpenSSL 1.1.1k 25 Mar 2021
Using virtual files plugin: suffix
osx-21.6.0
```

ownCloud 2.11.0rc1 works ✅ 

```
ownCloud 2.11.0rc1 (build 8255) cba22a Aug 3 2022 10:44:42
Libraries Qt 5.12.11, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-21.6.0
```

ownCloud 3.0.0.8266-daily20220805 doesn't work 🚧 

```
ownCloud 3.0.0.8266-daily20220805 bde1a7 Aug 5 2022 02:10:42
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-21.6.0
```

**Comment by michaelstingl** [comment]
> Please report the logs for the socket api.

Check here:
- [ownCloud.log.zip](https://github.com/owncloud/client/files/9268954/ownCloud.log.zip)

**Comment by TheOneRing** [comment]
According to the logs only `/Users/owncloud/ownCloud` is managed, which is not the folder visible in the above screenshot.

**Comment by TheOneRing** [comment]
Fixed in https://github.com/owncloud/client/pull/10010

**Comment by michaelstingl** [comment]
Gone again?

![CleanShot 2022-08-18 at 12 08 01@2x](https://user-images.githubusercontent.com/214010/185370295-d5f865ff-1cb5-4094-ad7d-ff92c8e0cdc6.png)

```
testpilotcloud 3.0.0.8351-daily20220818 804d66 Aug 18 2022 02:40:12
Libraries Qt 5.15.5, OpenSSL 1.1.1q 5 Jul 2022
Using virtual files plugin: suffix
osx-21.6.0
```

**Comment by TheOneRing** [comment]
That folder has no image at all. Is it actually managed by the current running client?

**Comment by michaelstingl** [comment]
> That folder has no image at all. Is it actually managed by the current running client?

Need to check with a clean macOS

**Comment by michaelstingl** [comment]
Now, they're back on my regular macOS as well 👍
