### ISSUE TITLE
"Open browser" button does not work using AppImage on live DVD

### ISSUE THREAD

**Issue by fmoc** [owncloud/client#9985]
### Pre-submission Checks

- [X] I [checked for similar issues](https://github.com/owncloud/client/issues?q=), but could not find any. I also checked the closed issues. I could not contribute additional information to any existing issue.
- [X] I will take the time to fill in all the required fields. I know that the bug report may be dismissed otherwise due to lack of information.

### Describe the bug

When using an OAuth2 server like https://demo.owncloud.com, the "(Re)Open Browser" button on the second wizard page does not work. On the first click, it correctly changes its title to "Reopen browser", however it does not open the browser.

See the screenshot below. Please note that the "Copy URL" button works, so there is at least some fallback solution.

I suspect this problem is related to using an AppImage in a live environment.

### Expected behavior

Obviously, the button should open the browser, or the wizard should at least notice that opening the browser failed and display a visible error message. I only saw one because I ran the AppImage a second time in a console.

### Screenshots

![screenshot_2022-08-01_22-04-14](https://user-images.githubusercontent.com/80399010/182236303-fc572461-2aef-4253-ba32-51106067e485.png)

### Client version number

https://download.owncloud.com/desktop/ownCloud/daily/3.0/linux-appimage/ownCloud-3.0.0-daily20220727.8150.AppImage

### Desktop environment (Linux only)

openSUSE Leap 15.4 Live DVD with KDE

**Comment by TheOneRing** [comment]
See https://github.com/owncloud/client/issues/10100

**Comment by fmoc** [comment]
I'm not sure these are clearly related. The only part both issues have in common is the use of KDE...

**Comment by fmoc** [comment]
Different problem. Reopening.

**Comment by fmoc** [comment]
This is an AppImage-specific problem, the same version of ownCloud installed using traditional packaging works fine there. Probably related to some environment variables set within the AppImage.

**Comment by fmoc** [comment]
Fixed in craft, see https://invent.kde.org/packaging/craft/-/merge_requests/94.
